== Chapter 1

[.chapter-synopsis]
* Adey Bellamy
* John Hall
* Richard Jacob
* Sarah Jones
* Christiana Hustler
* Mercy Ransom
* Thomas Colley
* Francis Fox

ADEY BELLAMY was born at Framlingham in Suffolk, in the year 1739.
When about eleven years of age, he was placed with a relation in London,
with whom he was afterwards apprenticed;
and being endued with a good capacity and an ingenious mind,
he stored it with much useful knowledge, which rendered him an interesting companion.
Although his general conduct from early life had been such
as to gain for him the esteem and love of his friends,
yet, in taking a retrospect of the past, he writes thus:
"`I feel and know that time and expression would fail me,
were I to attempt to show the great mercy, long suffering,
and forbearance of a merciful God to my soul,
and the many sins of omission and commission which I have been guilty of;
rebelling against his grace and good spirit in my soul,
even while highly professing with his people.`"

In his youthful days,
after he had been favored with the convictions of the Spirit of Truth,
and had at times yielded to them, he indulged himself in reading plays,
and other works of the same character.
His own remarks, in after life, upon this dangerous practice,
contain the following reflections: "`I have found, and now record it as a caution,
that they were extremely hurtful to me,
and fed almost every evil propensity of the natural mind.
For though it is urged that honey may be extracted from even poisonous flowers,
yet I know by experience that the depraved mind will
suck in and retain that which had better be forgotten,
and forget those parts which, by some, are extolled for moral sentiments.
These hurtful parts choke every good desire,
and are instruments in the hand of the evil one, to bring into captivity,
or keep us there.
Oh! when favored in the light to see these things,
what would I at times have given to unlearn this unprofitable, may I not say earthly,
sensual learning.
It seems as though I scarcely could say or think enough on this subject,
so hurtful has it been, and so grievous are the effects still to me.
I remember the last play I ever read a deep tragedy --and which,
after having pretty much laid them aside, I read to please some present,
as I had a readiness in reading them as I supposed they who acted them spoke;
for I never saw but one play acted.
I was so struck in reading it,
particularly some of the wicked imprecations and expressions,
that I could not go through, but trembled very much,
and retired with a resolution not to attempt it again; which, by renewed mercy,
I was enabled to keep to,
though the love and root of the matter still remained in degree.`"

As Adey Bellamy advanced in years,
he became more decided in his attachment to the cause of piety and virtue.
Though encompassed with trials of flesh and spirit,
he acted as one whose mind was influenced by the love of God to labor after,
and keep a steady eye upon, an inheritance in his blessed kingdom.
He continued many years in London, engaged in trade,
in which he conducted himself with uprightness and integrity;
not allowing it to hinder him from being an active and useful member of our Society.
From conviction he was much attached to the principles of Friends,
and zealously concerned for the faithful maintenance of the same.
The following memorandums instructively show the exercise
of his mind on subjects of the highest importance.

1783+++.+++ --Fourth month, 13th. "`Is it not a near advance to Christian perfection,
if not the highest state of it, in this militant state,
to be made willing to do and suffer all the will of God, made manifest in us?
And is not watchfulness the first step towards this state of perfection?
O Lord, make me ever more watchful, humble, and attentive to your voice.`"

1785.--Eleventh month, 18th. "`When the light of the Lord shines most upon my soul,
oh! how it humbles the creature; then do I indeed appear as vile in his sight,
and that my sins ought to be forever before me,
and my whole life dedicated to acknowledge the same,
and to praise his mercy and goodness, in that I was ever brought to a sight of myself.`"

1793+++.+++ Fifth month, 1st. How precious it is, O Lord,
to have a heartfelt sense of the prevalence of your love over every sensible object.
How necessary, how desirable it is,
to be sought after and waited for in abstraction
and renunciation of all creaturely objects.
It is a sense of your power and greatness which alone can humble our hearts:
as it is a sense of your love and goodness which alone can tender our spirits,
and draw us towards You as our supreme and only good.
Unless You draw us, we should never follow You, much less run after You;
but be ever seeking enjoyment and consolation where they are not permanently to be found.
May we then, more often than the morning,
desire to experience the drawing cords of your love to be manifested in our souls;
and oh! strengthen us to follow You whithersoever You lead.`"

1795.--Ninth month.
"`I think I may say without boasting,
that I am no bigot--not disposed to favor any particular
system of religion merely as such;
but one who wishes for, and sometimes is enabled to pray for,
the happiness of the whole human race, both in time and in eternity.
I see in myself by and through the light of Grace, so many failings,
so many deficiencies, so much shortness of what, I believe, is attainable by all,
and ought to be pressed after by all, even to live in Christ, to put Him on,
to walk after his example, in self-denial,
and in the mortification of the will and wisdom which are
striving to attain the gratifications of this life.
I see in myself so much lack of the one, and proneness to the other,
that I can readily make allowance for others.
Yet, whatever our profession of religion may be, unless it is a principle which,
if followed, will bring us nearer to God, humble and contrite our spirits before Him,
and give us strength to overcome the propensities of fallen nature,
and to see the beauty of holiness,
and beget in us desires to become more and more like the holy Pattern, it will prove,
however ostensible and high in the sight of man, but an illusion, a dream.`"

Adey Bellamy first spoke as a minister in our Society,
in the forty-first year of his age,
in which character he was well accepted by his friends.
He paid two religious visits on the island of Guernsey, and one in the south of France.
In the year 1789, he removed to High Wycomb,
and his friends in those parts had reason to be glad he came among them,
having found him capable and willing to render himself truly useful.
He was very diligent in the attendance of meetings,
to accomplish which he frequently went through much bodily suffering.

He was twice married, and survived his second wife upwards of nine years.
Near the close of the year 1808, he was seized with a violent fit of illness,
which seemed likely to prove mortal;
and although of such a nature as to occasion great suffering,
yet his mind appeared to be preserved in much quietness and resignation.
Some hours after he had been relieved from this extremity, he spoke thus:
"`I desire not to be anxious as to the event,
for which of us by taking thought can add one day or one hour to our lives.
No, no, the great thing is, to be prepared for our final change;
to beg forgiveness for what we have done amiss,
and desire to do the will of him who has created us, and to be united to Him:
this is the end of suffering, to bring us to this,--`' You are my friends,
if you do whatsoever I command you.`'
Oh! it is a precious thing to be the friend of Christ, and to have Him for our friend:
'`Whom the Lord loves, He chastens, and scourges every son whom He receives.`'`"

Although at the commencement of his illness, and for many weeks afterwards,
it was not supposed that he could long survive,
yet he so far recovered as several times to attend meetings: he was, however,
seldom free from considerable pain,
and continued liable to repeated severe attacks of the complaint.
When somewhat recovered from a seizure of this kind, he said: "`I hope,
if one of these fits should terminate the life that now is,
it will open the way to one that is far better.
It becomes us poor creatures, under every difficulty, to say, '`Your will be done.`'
Oh, what a favor not to have a murmuring thought permitted to arise.
The power and goodness of the Most High ought to be looked up to above all.`"
And on another such occasion, he said, "`I should wish,
if it is the will of the Almighty, I might not go off in such extremity,
but that I might quietly leave my friends.`"
This desire was mercifully granted; for, on the 29th of the Third month, 1810,
he was released without apparent suffering.

[.asterism]
'''
JOHN HALL, of Little Broughton, near Cockermouth, was born there in the Third month, 1744.
His parents were Isaac and Alice Hall;
the latter of whom died at Philadelphia in the year 1762,
when on a religious visit to Friends in America.

No particular account of the early life of this Friend has been preserved;
but when about twenty-eight years of age, he first-'`bore public testimony, as a minister,
to the efficacy of the grace of our Lord Jesus Christ; having,
by obedience to its discoveries, measurably experienced a purification of heart,
and become prepared for the work of the ministry.
His communications in this way, though lively and acceptable to his friends,
were for several years not extensive.

In the year 1769, he was united in marriage with Hannah Wigham, of Cornwood,
in Northumberland.
Not being entrusted with much of the treasure of this world,
and having a large family to provide for,
(he left ten children at the time of his decease,) his time,
when he was released from the more important engagements of religious duty,
was much occupied in,
endeavoring to provide a comfortable subsistence for himself and his household,
which called for all the skill and industry he could employ upon a small patrimony,
and in some other occupations which he undertook with this view.
His daily walk through life manifested a continued desire
to live in accordance with the principles he professed,
and with his station in religious society.
Watchfulness and Christian humility marked his steps, endeared him to his friends,
and gained him the esteem and respect of his neighbors.

For several years he occasionally travelled from home on religious service,
in different parts of this nation, with the full unity of his friends;
and in the year 1799, with their approbation,
he proceeded on a similar gospel errand to the continent of America.
After a tarriance in that country of nearly three years,
he was favored to rejoin his beloved connections and friends, with peaceful feelings;
having performed an acceptable visit to his brethren on the other side of the Atlantic.

He did not again travel as a minister;
and appeared to be in great measure excused from further service in this character.
He was, however, diligent in his attendance of meetings at home,
and concerned to promote the right exercise of our discipline,
and the maintenance thereof in its true spirit and authority.

About the beginning of the year 1809, his health appeared to be declining.
He was attacked by a dropsical complaint, attended with great difficulty of breathing,
and other symptoms of debility,
which seemed to indicate the approach of the solemn close of life.
During the tedious and painful conflict that was allotted him,
his mind was preserved in quietness and resignation;
he was favored to rest in that hope which is as an anchor to the soul,
and to feel that he had endeavored to follow the pure light of the Gospel.

In the course of his illness he sometimes expressed a desire to go hence;
but prayed earnestly that he might be favored with patience to the last.
Being at one time exceedingly distressed with pain, he said,
"`How small are my sufferings, when compared with those of our dear Lord,
when he died upon the cross.
If these afflictions are designed for my purification and preparation for a better kingdom,
I accept them with thankfulness at your hands, O Lord.
What shall I render unto you for the many favors you have bestowed upon me, a poor,
unworthy creature?`"
He frequently spoke of the peaceful state of his mind, saying:
"`I die in peace with God and man.
I have fought the good fight;
I have kept the faith;`" and desired those about him to take notice
that he died "`sound in the Christian faith.`"

At one time, he said: "`I know my Redeemer lives; and because He lives, I live also.`"
And, at another time:
"`How precious a thing it is to feel the influence of divine love upon the mind!
I feel an evidence, that in the day when the Lord makes up his jewels, I shall be his.`"
Being asked how he was, he said, with a kind of melodious voice,
"`O Death! where is your sting?
O grave! where is your victory?
The sting of death is removed.
Oh that this may be my dying song!`"
And at another time, he said: "`I have seen the angel of the Lord`'s presence,
who is come to guard my weary soul to the mansions of eternal happiness;
and glorious was the appearance.`"
When some friends were about to take leave of him, he said:
"`I think I see the gates of heaven opened,
and an angel of the Lord waiting to receive my spirit.`"

For several days previous to his death, his articulation was very indistinct.
In the course of the night which preceded the solemn close,
he seemed desirous of expressing something, and, on being asked if he lacked any thing,
he answered with great difficulty, "`Nothing at all: I am going to heaven.`"
These were almost the last expressions which could be understood.
About noon, the following day, he quietly drew his last breath,
at his own house in Little Broughton, the 2nd of the Sixth month, 1810,
at the age of sixty-six.

[.asterism]
'''
RICHARD JACOB was the eldest son of Joseph and Hannah Jacob, of Waterford,
and was born there, in the Sixth month, 1758.
He had the benefit of a religious education; but,
being naturally of a lively turn of mind, and of a social disposition,
he found it difficult to take up his cross,
and deny himself in those things which he was favored to see, in the light of Christ,
were opposed to his advancement in true piety.
But he gradually submitted to the power inwardly revealed,
and proved it to be good for a man to bear the yoke in his youth, to sit alone,
and to keep silence;`" and thus there is reason to conclude, that even in early life,
he was brought under preparation for that solemn engagement, into which,
after having passed through many close baptisms, he was introduced at a future period.

About the year 1786, he came forth in the ministry;
and in the continued exercise of his gift,
severe conflicts and reasonings were frequently experienced,
in which he partook of the sympathy of such as were
qualified to comprehend these humiliating siftings,
whereby the chaff is separated from the wheat.
His communications as a gospel minister were marked with peculiar energy; and,
though not frequent, they were weighty,
and demonstrated his care to wait to be endued with power from on high,
in the fulfillment of this sacred office.
The fervent travail of his spirit for the young,
was conspicuously evinced in public and in private labor on their account.

He did not travel much on religious service,
but diligently attended meetings for the concerns of our Society in his native land,
and was an example of steady and patient waiting
therein for strength and ability to judge aright;
and was eminently useful in the promotion of good order.
He was several times acceptably engaged in visiting
the families of Friends as a Christian minister,
when he was at times enabled to speak to the religious states of individuals,
in "`demonstration of the Spirit, and of power.`"

He was particularly concerned to bear testimony to
the benefit and excellence of inward silence,
as a state of mind the fittest for the performance of pure and spiritual worship;
and he earnestly recommended a daily endeavor to retire
to the immutable source of instruction and strength,
from a deep conviction of the tendency of this practice
to preserve from inward and outward evil.

Richard Jacob was necessarily engaged in trade,
yet truly desirous of keeping his outward concerns within proper limits;
his countenance and deportment frequently denoting that he was
favored to experience these changeable things to be in subjection,
and the Spirit of Truth in dominion, in his own mind.

He was a bright example among his friends, in the discharge of his filial, parental,
and relative duties; and he performed a truly affectionate part,
when called upon to act as a master or a friend.
Laboring with conscientious perseverance that evil might be overcome by good,
he was solicitous to promote love and forbearance in all;
often enforcing these Christian virtues, by the revival of the Scripture declaration,
"`God is love, and he that dwells in love, dwells in God,
and God in him;`" and he was a good example in endeavoring
to live under the influence of this precious principle;
hence, also, he often sympathized with the afflicted,
and ministered to the necessities of the indigent.

In the year 1809,
he attended the yearly meeting in London as a representative from Ireland,
and his dedication to this service produced solid peace to his own mind.
His company and religious labors were acceptable,
and left a lively impression of his worth on the minds of many of his friends in England.
Soon after his return, he visited the quarterly meeting of Ulster,
with a committee appointed by the yearly meeting of Ireland.
He attended his own quarterly meeting in the spring of the year 1810;
his health was then visibly declining, and it continued to require attention and care.

On the 30th of the Eighth month of the same year,
he was present at a marriage at Waterford, and powerfully engaged in prayer,
on behalf of those who had then entered into covenant.
After the meeting, but before he reached his own dwelling, he was seized with apoplexy,
which, in about three hours, terminated his life.
The testimony of the monthly meeting of Waterford,
from which the foregoing account is compiled, adds: '`The solemn calm,
mercifully diffused at the time that he was thus suddenly
but peacefully translated from this probationary state,
was humbly accepted as an evidence of his admittance
into permanent and undefiled rest.`"

[.asterism]
'''
SARAH JONES, wife of George Jones, of Stockport, in Cheshire,
was born in the borough of Southwark, the 15th of Third month, 1768,
and died at the age of forty-three.
Her parents, James and Sarah Hargrave, were members of our religious Society.
When about fourteen years of age,
her mind was in a remarkable degree favored with
a gracious manifestation of the light of Christ;
and by following its discoveries, experienced true peace,
by which she was encouraged to seek after a closer communion with the Lord.
As she advanced in years, she was strengthened increasingly to give up her natural will,
and to walk in the path of Christian simplicity and self-denial;
and her dependence continuing to be placed on the Almighty for preservation and support,
she attained to.
a good degree of stability in the Truth.

Her humble, circumspect life and conduct,
preached loudly to those who were in early life;
and it tended not only to the encouragement of such as had a birth-right in our Society,
but also of others who were favorably impressed with our religious principles;
some of whom have thankfully acknowledged that her
example had an animating effect on their minds.
After her marriage, in the year 1793,
she further manifested her love to the cause of religion, in many ways.
She was exemplary in a diligent attendance of our meetings for worship and discipline,
and in making way for the attendance of those under her care.
She frequently went herself, when in a poor state of health; and her reverent,
patient waiting therein, as well as in opportunities of retirement at home,
was very instructive.
Through a watchful care to maintain the Christian warfare,
and by submission to the necessary baptisms of spirit, she was fitted,
and became willing, though naturally of a diffident disposition,
to support the good order and discipline of our Society;
and her services in her own monthly and quarterly
meetings were very acceptable to her friends.

For many years she experienced, at times, great poverty of spirit;
yet she was very cautious of expressing to others what she was passing through,
or of receiving consolation from them;
being anxiously concerned to feel after the evidence of the love of God to her own soul,
preferring this to all other enjoyments.

During her last illness she was favored with resignation and Christian fortitude; and,
in the course of her confinement of sixteen weeks,
was not heard to utter an impatient expression.
At one time,
her husband remarked to her that he had been greatly comforted in thinking of her,
in the belief that a language like the following might be applied to her:
"`Her secret prayers and alms-deeds are accepted by me:
they are come up as a sweet memorial before me.`"
She replied, that it was encouraging to her to understand that he had thus felt,
but she should be glad to feel it for herself;
and though she had often been under great discouragement, yet, within a day or two,
she had been at times favored with a little glimmering of light,
and the saying of Jonah had come feelingly before her view:
"`Though I am cast out of your sight, yet will I look again towards your holy temple.`"
Further saying, '`I do not feel any uneasiness or distress of mind,
but I fear it may be for lack of sensibility.`'
The following morning, on seeing her in tears,
he inquired if she wished to say anything to him, when she replied: '`No;
I have been thinking how much I am favored, many ways:
I am afraid I shall not be thankful enough.`"

A few days subsequently to this, after receiving a visit,
she remarked how comforting it was to have Friends call and see her,
and what a different effect their quiet sitting together,
and the feelings they were sometimes favored with, had on the minds of the visited,
compared with the more formal visits that some pay; observing also,
upon the hurtful tendency of the light conversation, which,
under the plea of raising the drooping spirits of the sick,
is often on these occasions promoted.
One morning, she expressed great thankfulness for the many favors she enjoyed, adding,
that she could not always feel her mind in such a thankful state;
and she had been thinking that, being at that time favored therewith,
afforded her some ground to hope and trust in divine goodness and mercy.
On another occasion she also said, "`I have at times been permitted to feel a hope,
of eternal salvation and I count it an unspeakable favor-an unmerited mercy.
I have thought, for a long time past, though I mourned all my days,
if at last I could but feel a hope, I should be very thankful.`"

A few weeks before her death, on retracing her early life,
she spoke of the time when she entered into covenant with the Almighty;
also of her love for faithful friends, and their kind notice of her;
and alluded to one occasion, when a friend in the line of ministry, addressing her,
had said, "`If there was but a keeping on the Lord`'s side,
He would provide for her;`" remarking, that this had been abundantly verified,
and the covenant of the Almighty had been fulfilled by Him.

During the evening which preceded her death, the conflict appeared to be severe;
yet those around did not apprehend she suffered so much pain as on some former occasions,
and she remarked how gently she had been dealt with.
She passed quietly away from time to eternity;
and her surrounding friends had the comfortable persuasion that,
having served the Lord in her generation, she fell asleep in Jesus, her Savior.

[.asterism]
'''
CHRISTIANA HUSTLER, of Undercliff, near Bradford in Yorkshire,
was the widow of John Hustler, of the same place, whom she survived many years,
and daughter of William and Sarah Hird,
who resided in an adjoining part of the same county.
Under a grateful remembrance of the blessing which she had derived through her parents,
she repeatedly spoke of the religious care and instruction
which they had bestowed upon her.
Her attention having in childhood been turned to the light of Christ in her own soul,
she was, through obedience to its manifestations,
preserved from many allurements that abound in the world,
and enabled to walk in the narrow way which leads to life.
She had, however, to endure various besetments and trials, which, to her diffident mind,
were rendered peculiarly poignant,
from an apprehension that she should be required to bear a public testimony to the truth;
but having, in her own experience, witnessed the sanctifying virtue of divine grace,
she became willing to declare unto others the goodness of her Heavenly Father.

When about twenty-eight years of age,
she was strengthened to surrender herself to the service of her Lord,
and first spoke as a minister.
She visited, in this character, most, if not all,
of the meetings of Friends in this country, and in Ireland.
In the exercise of her gift, she was sound in doctrine, and clear in discernment.
Her ministry was marked by an earnest and persuasive simplicity;
and attended with an affectionate solicitude,
that her friends might in no respect be inactive
or superficial in the pursuit of the one thing needful;
but really be what they professed to be, a spiritually minded people,
built upon the foundation of the apostles and prophets;
Jesus Christ himself being the chief corner stone.

In private life her conversation was interesting and instructive;
and her manners were affable and engaging, particularly to the young,
even such as were remotely wandering from the fold of rest.
To these she frequently imparted counsel, in so attractive a manner,
that they seldom quitted her company without feeling desires after those Christian virtues,
which in her they could but admire and love.
Her hospitality to her friends,
and more especially to those who were traveling as messengers of the gospel,
was well known.
The most experienced ministers of Christ are often greatly cast down,
and stand in need of the counsel and succor of those
who have trodden the same path with themselves.
Her dwelling was a place where these comforts were often to be met with,
and where such found rest, both to body and mind.

The recollection of her own happy experience,
of the effects produced by the early religious care of her parents,
induced her to lay particular stress upon a timely subjection of the will in children,
and, when opportunity offered, earnestly to urge attention thereto,
as contributing very materially to prepare the way of the Lord;
and to diminish in future life, the hardships of self-denial and the daily cross.

In the early part of the year 1811, her strength had so far declined,
that she was confined up-stairs.
Yet, while the powers of nature were sensibly giving way,
it was instructive to witness the liveliness of her religious feelings,
and her earnest concern for the spiritual welfare of her friends.
She often encouraged them,
with a clearness and energy which were striking to those who knew her feeble state,
to persevere in the path of dedication, by the animating assurance that,
in reviewing the various trials of a life protracted to a late period,
she could thankfully acknowledge,
that goodness and mercy had followed her all the days of her life.

Her weakness continued to increase.
On the 7th of the Sixth month she seemed much alive
to affectionate feelings for her children and attendants,
and appeared sensible of her own situation; and after an interval of silence,
with reverent awfulness broke forth in these words: "`Oh,
that I were safely gathered beyond the great gulf,
into that country that knows no change!
But oh that I may keep the word of His patience,
and then He will keep me in the hour of temptation, and what a favor will that be;
more to me than ten thousand worlds;`" adding, after a pause, "`I think I may say,
blessed and praised be his holy name forever.`"
She endured the last sinkings of nature with great meekness and patience, and,
without much apparent pain or suffering, continued to grow weaker,
until the 27th of the Sixth month, 1811, when, at the age of seventy-nine,
her spirit was released from the conflicts of mortality, prepared, we cannot doubt,
to partake of the joys of God`'s salvation.

[.asterism]
'''
MERCY RANSOM, late of Hitchin, in Hertfordshire, was, from her youth,
a friend of steady and consistent conduct; and was favored, when in the vigor of life,
to yield, in measure, to the power of that love,
which redeems the soul from the pleasures and friendships of this world.
But, as time advanced,
she had a clearer sense of the spiritual nature of
the reign of Christ in the soul of man,
and found that she had much to give up.
Earnest desires were raised within her,
that the work of purification might be completely accomplished;
and she underwent many sore conflicts and deep baptisms of spirit,
known to but few of her friends,
by which she became gradually fitted for service in the church of Christ.

About the fifty-eighth year of her age she came forth in the ministry.
In the exercise of the gift entrusted to her,
her communications were weighty and instructive:
she was cheerfully and faithfully devoted to do what she apprehended was required of her,
and paid religious visits to her friends in various parts of this nation,
and in Ireland.

In the autumn of the year 1802, when upwards of seventy-three years of age,
she had a fall, which confined her to the house about six months,
and brought on much pain and suffering, to which, with short intermissions,
she ever after was subject; but for several years, when her health admitted of it,
she was conveyed to meeting in a chair; and, though pressing through many difficulties,
she often signified her thankfulness that she could enjoy this privilege.

The following extracts from some memorandums made by her,
during this painful confinement, are introduced,
as exemplifying the consolations of religion, in the midst of much bodily suffering.

"`1806.--Fifth month, 7. Last night went to bed unwell, and in considerable pain,
which was unremitting, until near two o`'clock; but my mind was calm,
and enabled to aspire after heaven and heavenly things; and, I thought,
renewedly qualified to join in the language of David,
when he calls upon all the creation to praise the Lord.
Surely praise is always due to Him, whether we are in prosperity or adversity;
because he makes all things work together for good, to them that love and fear Him.

Sixth month, 15. Ill all day yesterday.
Went to bed poorly.
Dropped asleep; but soon waked in much pain; was relieved, yet no inclination for sleep.
As I lay musing, the excellency of pressing forward in the heavenly race,
was afresh opened to my view;
with desires that I might follow the example of the holy apostle,
in leaving the things that are behind, and pressing forward to the mark for the prize.

1807.--Fifth month, 30. Last night waked before twelve o`'clock in much pain,
which abated in about two hours; but I could get no sleep until after five:
yet my mind was favored with sweet serenity,
so that my pain of body was sustained without much sense of suffering.
Thanksgiving and praise, for the secret, humble hope vouchsafed,
of an admission within the pearl gates when time shall terminate.

1808.--Fifth month, 20. This morning under great pain of body,
and closely tempted and tried; I was reduced to great fear,
and almost sunk below hope of ever rising again;
but even then I was enabled to derive a little encouragement,
from the fresh remembrance of this gracious and animating assurance,
"`Blessed is the man that endures temptation; for when he is tried,
he shall receive the crown of life, which the Lord has promised to them that love Him.`"

1809.-- Seventh month, 22.
This morning early I was lifted up in recollection
of the Lord`'s mercies bestowed upon me,
and enabled to commemorate them: they are both ancient and new; yes, renewed every day.
I was under bodily pain; but heavenly dew refreshed my mind,
and then all my trials seemed light, and, as it were, driven away for a time,
as chaff before the wind.

Eleventh month, 27. Last evening the following language livingly arose in my mind:
"`I know that my Redeemer lives.`"

1810.--Fourth month, 1st. Musing this morning, under bodily distress,
my spirit earnestly craved patience in proportion to the trial,
which was mercifully granted;
and every disposition of soul was centered in entire resignation and thanksgiving;
and I thought I could adopt the language of the apostle:
"`In all things I am instructed.`"

Ninth month, 15th. My night watches were for some hours very comfortable;
many passages in Holy Writ were brought to my remembrance, with fresh instruction;
and some afforded consolation, being, as I apprehended, opened by Him that opens,
and no man shuts; and I was enabled to offer the sacrifice of brokenness of heart,
with tears that afforded joy.`"

This tried servant of the Lord was confined to her
bed for about four months before her death,
and during that time was seldom free from pain.
In the early part of this period, He,
whose dispensations to his dependent children are all in mercy,
though inscrutable to our finite understandings,
permitted her to be deeply tried with discouragement
as it respected her hopes of final acceptance.
She one day remarked, "`I have loved the Lord with all my heart, with all my soul,
and with all my strength; and I hope I have loved my neighbor as myself; but oh!
I am so tried with desertion.
If I had all the world,
I would give it to feel what I have felt;`" often requesting her friends to pray for her.
And at another time she said, "`My poor mind is so low:
the enemy is permitted to afflict me with bad thoughts, and I abhor bad thoughts.
I abhor all that is evil, and love all that is good.`"

But as the solemn close of life approached, more peaceful feelings prevailed,
and she thus expressed her animating hope: "`Open the gates,
that the righteous nation that fears the Lard may enter in.
Oh! joyful to be admitted.
I have sought the Lord and his strength,
and am mercifully supported in patience and resignation to the divine will.
Nothing will do but patience.`"
At another time she said, "`My sufferings are great; you cannot form any idea of them;
but I feel something very sweet, at times, that rolls over all;
and I hope it will continue to roll over all to the last.`"
She one day remarked, "`When I was waking this morning,
an unadvised word crossed my mind, but not with my consent.
I hope I shall be preserved from uttering an unadvised word.`"
And herein her desire seemed granted,
as she had throughout been preserved from showing any impatience.
As her sufferings increased, her hope of acceptance with God increased also,
and she often longed to be released; and when articulation became more difficult,
she was mercifully borne up under the last conflict.

She died at the age of eighty-three, on the 25th of the Fifth month, 1811.

[.asterism]
'''
THOMAS COLLEY, of Sheffield, was a friend well known in our Society,
and highly esteemed as a faithful and diligent minister of the Gospel of Christ,
in which character he labored for upwards of forty years.

He was born at Smeaton, a village near Pontefract, in Yorkshire, in the year 1742,
and educated in the principles of the established church of England,
and when about eleven years old went to reside at Sheffield as an apprentice.
In the course of his minority,
his mind was awakened to a sense of the importance of a religious life,
and he joined the society of the Methodists, among whom he was zealous, active,
and much esteemed.

In the year 1764, he married.
About this period the observations and performances, in which he was religiously engaged,
failing to satisfy the travail of his soul, he sought for something more substantial,
and in this disposition of mind attended the meetings of Friends.
Waiting reverently before the Lord,
he became further acquainted with the operation of divine grace,
and was engaged to press after a greater knowledge of things which accompany salvation.
His circumstances were then low in the world,
yet he attended our religious meetings diligently, until he observed that some,
who were active in the concerns of the Society,
absented themselves from those held in the course of the week.
He thought that he might follow their example; but found, that by so doing,
he suffered in a spiritual sense, and therefore resumed his former practice;
and giving proof of his sincere attachment to our Christian principles,
he was in due time admitted into membership with Friends.

In the year 1768, he first spoke as a minister in our religious meetings;
and being careful, in humility and watchfulness, to occupy the talents committed to him,
his services were acceptable and edifying.
Not long afterwards, he felt himself called upon to travel in the service of the Gospel;
and performed several journeys, with the unity of his friends.

In 1779, in company with his friend, Philip Madin, also of Sheffield,
he paid a visit to the then remaining members of our Society on the Island of Barbados,
and was also on a few of the other British West India islands.
He was brought very low when on his passage across the Atlantic; but his mind appears,
by a memorandum made at the time,
to have been greatly consoled in this season of conflict of spirit,
in the fresh remembrance of the sufferings of the unconquered Captain of our Salvation;
and he was enabled to look, in faith, unto Him,
and to lay hold on his gracious promises.

Being favored to return home in safety, he penned the following reflections.
"`Under a grateful remembrance of the many favors of the Almighty,
graciously extended to us, through the course of this long and perilous journey,
in preserving us in the midst of a raging and tumultuous war,
in opening our way in the service in which we were engaged,
and affording ability and strength to discharge the duty of the day,
are our spirits humbly bowed in deep reverence and thankfulness
to the Father and Fountain of all our living mercies.`"

A few years after his return from the above-mentioned voyage,
this devoted servant of Christ again left his near connections,
and travelled extensively in North America,
where his gospel labors were well received and made a deep and
instructive impression on the minds of many of those whom he visited.
In his native land he travelled much afterwards, as a minister; and was often concerned,
more particularly in the latter part of his life, to labor in word and doctrine,
among those of other religious societies.

In reference to one of the last-mentioned of these services, he thus writes from London:
"`I have labored many weeks in this populous place;
visited all the meetings in this city, and most of them on First-days;
and also have attended their quarterly and monthly meetings,
and have had public meetings at all the meeting-houses, and in other places;
in which service, I may with reverence acknowledge, that the Lord has been near,
and his ancient promise fulfilled: '`As the day is, so shall your strength be.`'
The meetings have generally been large; neither unfavorable weather,
nor snow on the ground, prevented the people from attending; and that living Power,
which is both ancient and new, was a crown and diadem to our assemblies.`"

When not engaged in religious service, he was diligent in attention to his business,
which was that of a cutler, and of which the superintendence,
during the periods of his absence from home, devolved in great measure upon his wife,
who, not only in a religious sense, but also in regard to temporal concerns,
was truly a "`help meet`" for her pious husband; and the honest industry of both,
was attended with the blessing of Providence.

He was a man whose deportment in life was such as becomes
one employed in preaching the glad tidings of salvation;
desirous to keep himself unspotted by the world, of unaffected gravity,
though at times innocently cheerful and communicative.
His general demeanor showed on whom his confidence was placed.
His reverent, silent waiting in religious meetings was obvious to others,
and had a tendency to draw them into the same profitable frame of mind.
He was uprightly concerned for the due preservation of our Christian discipline,
and careful to keep his place in the meetings established for its support.
In the exercise of the ministry he was diligent in
seeking after the renewed influence of Divine power;
and often eminently qualified to set forth the blessing of salvation,
through our Lord Jesus Christ, who came as a sacrifice for sin,
and as the light of the world;
fervently endeavoring to gather all to the teachings of his Holy Spirit,
in the secret of the soul.

In the year 1810, he attended the yearly meeting in London,
near the close of which he had a dangerous attack of illness;
but was restored to his family and friends.
He afterwards held a few public meetings in his own neighborhood,
and diligently attended other meetings at home.
Towards the latter end of the year,
there were obvious symptoms of a declining state of health,
on which he remarked to one of his friends,
"`I have for a considerable time apprehended I should have a lingering illness,
and have never desired it might be otherwise.
I do not, as some have done, wish for sudden removal, as I think divine Providence,
as well as divine Grace,
is as much manifested in times of sickness as in times of health;
and it now yields me great consolation,
that I worked while health and ability were afforded.
I now see but little to be done; and it is cause of great satisfaction,
that I was enabled to perform my last religious visit to London.`"

At his own meeting, where, for some time before, he had been but seldom heard,
he now frequently spoke, both in testimony and supplication, with clearness,
and in the power and love of the Gospel; manifesting, as a father in the church,
his continued and increasing solicitude for the spiritual progress
of those among whom he had long and faithfully labored.
The solemnity which prevailed on these occasions made a
deep and instructive impression on his friends.

In the Seventh month, 1811, he was seized with violent illness,
which he expected to survive only a few days; but being a little revived,
he said to a friend who visited him, "`I am a poor, weak creature,
uncertain how this attack may terminate; nor am I anxious about it.
For some time past, I have been concerned to use the strength afforded,
in discharging manifested duties; and, on a retrospect,
I do not see one religious duty or service left undone.`"

After this he gradually declined; and in the Sixth month, 1812, he became very weak.
On. the 10th, when one of his friends, who had called on him,
was about to take his leave,
having to attend a meeting of ministers and elders that evening, he said,
with a calm and expressive countenance, "`The Lord bless you;
and may He be with you in all your movements, in the promotion of his work.
How long the taper may glimmer in the socket, is uncertain; I think it will not be long.
My love to friends.
Farewell.`"

He spoke but little afterwards,
appearing to be in a state of patient waiting for the full
accomplishment of the Divine will concerning him;
and, on the 12th of the Sixth month, 1812, he expired in the seventieth year of his age,
having been a minister forty-four years.

[.asterism]
'''
FRANCIS FOX.--It is instructive,
and cause of thankful acknowledgment to the goodness of our heavenly Father,
to observe how divine grace, when yielded to in its pure and gentle intimations,
operates on the human mind,
under the various circumstances in life-how it enables
the benevolent Christian to exercise his affections,
and to employ the faculties of his soul, not for a selfish gratification,
not from a love of human applause,
but with a pure and fervent desire that all may redound to the glory of God,
and the good of our fellow-men.
Reflections similar to these arise in contemplating the character of FRANCIS Fox,
of Plymouth, who was born there in the Eleventh month, 1765,
and died at the age of forty-six, in the Ninth month, 1812.

He was a boy of modest, amiable dispositions,
endearing himself to his youthful associates by a readiness to contribute to their pleasure,
and to deny himself the gratifications that were within his reach,
for the sake of others.
Having been early deprived of his father,
he was an example of filial obedience to his surviving parent,
and cheerfully submitted to her will when at variance with his own.
For a time he indulged in fishing as an amusement;
but from a fear of inflicting pain on any of the brute creation,
and from a conviction that such amusements did not yield substantial enjoyments,
he soon abandoned it.

As he advanced towards manhood, his occupations became more rational and improving.
He pursued, with an ardor that was natural to him, the study of chemistry,
in which he made great proficiency;
and possessing a mind alive to the beauties of nature,
he feelingly rejoiced in them as the gifts of an all-bounteous Creator.
He early chose the path of virtue; and amidst the many allurements of the world,
and the opportunities for yielding to them which his situation afforded,
he was preserved from deviating widely from those
practices which our self-denying profession enjoins;
yet he has acknowledged that, at one time, he went so far as to alter his apparel,
that it might be something nearer to the fashion of the times.
This he found opened the way to his yielding to greater
temptations than he was at first aware of,
by leading him into company and conversation which brought a burden on his mind.
He afterwards became willing to submit to that simplicity in external appearance, which,
in his apprehension, became the disciple of our blessed Lord.

Having been early sensible of the visitations of the love of God,
and favored to see that nothing short of its power
can fully satisfy the desires of an immortal spirit,
or complete the work of redemption, as his judgment was more matured,
and as these convictions were mercifully renewed,
it became his first concern to turn from evil,
and to follow the guidance of his gracious Lord.

Continuing faithful in his endeavors to walk uprightly before the Most High,
when about thirty-one years of age,
he gave up to an apprehension of duty to speak as a minister in our religious meetings.
In the exercise of the gift committed to him, his offerings were convincing and clear,
attended by an evidence of right authority, and delivered in a remarkably simple,
humble manner.

Those amiable dispositions which had been discoverable in his youth,
shone forth with peculiar brightness in advancing years, evincing that true religion,
which operates by purifying the heart, necessarily produces works of righteousness,
and leads those who perform them, by the very manner in which they do so,
to ascribe the honor to Him to whom it is due.
Though naturally mild and unobtrusive, he was firm and bold,
when he found it his place to act as a Christian moralist and philanthropist.
Weakness of body was not permitted to plead as an excuse for indolence;
but using with caution his portion of strength,
and proceeding with regularity and clearness of purpose,
his exertions were turned to good account, and his time and labor were well employed.

Deeply interested in things connected with the welfare of his fellow-men,
he was a liberal and zealous promoter of public works of benevolence.
To the poor and wretched of every description he
was an unwearied but unostentatious benefactor;
and justly attributing many of the evils which exist among this class of society,
to the lack of right instruction in early life,
he was earnestly and successfully engaged in procuring this
benefit for the poor children of his native town.

While thus usefully and honorably employed as a man and a Christian,
it pleased unsearchable Wisdom to call him hence, deplored by the poor,
and esteemed and lamented in no common degree by his fellow-townsmen,
and fellow-professors of the Christian name of various classes.
His last illness was short; and his endeared companion,
to whom he had been united upwards of sixteen years,
was called upon to surrender him as at an unexpected moment.
As the close of life approached,
he expressed very little which indicated his religious feelings at that solemn period;
yet the sweetness of spirit that attended him,
seemed to imply that his peace was made with his God;
and that he had only to wait the awful summons,
to be admitted to the inheritance of a glorious immortality with the saints in light.
