== Chapter 2

[.chapter-synopsis]
* Hannah Jarrett
* Robert Marriage
* John Eliot
* John Glaisyer
* Mary Bevan
* Ann Kitching
* William Wright
* Jane Shipley

HANNAH JARRETT, widow of Stephen Jarrett, who resided near Banbury in Oxfordshire,
appeared from an early age to be religiously inclined.
She was earnestly engaged, as she advanced in life,
to obey the monitions of the Holy Spirit, and was enabled at times,
under an impression of duty, in gospel love,
to recommend to her friends a diligent waiting upon God for the renewal of their strength.
Being deeply impressed with the necessity of continued watchfulness and fear,
her conduct and conduct evinced a sincere desire, both for herself and others,
that they might possess that faith which works by love, and purifies the heart.

Though poor as to the things of this world, she was a diligent attender of meetings;
her confidence being strong in Him whom she experienced to be rich in love,
and able to add all things needful to the devoted mind.
And as she was concerned to show forth the example of a meek and quiet spirit,
her religious labors left a good impression upon the minds of her friends,
and especially of those among whom she dwelt.

For a considerable time before her decease, she was deprived of the power of speech;
yet her friends had cause to believe,
that she was not infrequently favored to partake of the feeling of peace.

She died the 18th day of the Tenth month, 1812, at the age of seventy,
having been a minister about forty-five years.

[.asterism]
'''
ROBERT MARRIAGE, of Chelmsford, in Essex, died on the first of the First month, 1813,
having attained to but little more than fifty years of age.
He was a man of an upright character, diffident of his religious qualifications,
and seldom speaking of his own experience,
but well concerned for the prosperity of the cause of Truth,
as upheld by our religious Society;
and he was for several years in the station of an elder.

He had been for some time in a declining state of health;
and towards the latter end of the year 1812, the symptoms of his disease became alarming.
Soon after the complaint made its appearance, he remarked to his wife:
"`I do not know how this may terminate; but as I was walking in the garden,
a day or two ago, I felt such a calm come over my mind, as I think, I never felt before;
but, perhaps, it was an enemy`'s work, for I cannot expect to feel so,
as I have been a poor creature, and not so much concerned as I should have been.`"

From the commencement of his illness,
his mind was turned to that Almighty Power which alone could help him,
and he used great diligence in setting his house in order,
and did what his hand found to do, with his might;
and though his pain was often very violent,
he was enabled to bear it with surprising fortitude and patience.

As the awful prospect of the invisible world opened before him,
he was permitted to take comfort in the belief that he had not consented with evil,
or with evil spirits; while, at the same time,
he felt and made the humiliating acknowledgment, that he had been a poor,
groveling creature.

To two friends who visited him he said: "`I have been favored with a tender heart,
and I may say, that goodness and mercy have followed me all my life long:
and I have not been a cast-away, but favored at seasons.
Oh! if I may but be enabled to work what I have to do, before I am taken away,
what a mercy!
If I am restored, it may be a favor to my family; but if I am taken away,
and numbered with the just, it will be a great favor to me,
and I shall escape many conflicts which might attend a longer stay here.`"

At another time, he observed to some who called upon him: "`You are come at a gloomy time.
I have been wishing to see you for days.
Wherein you have seen that I have erred, or fallen short, do you take warning,
and fear not the faces of men; be not fainthearted.
I have not been sufficiently devoted, nor so humbly dedicated as I might have been.
But I hope He who sees that there has been a degree
of uprightness and integrity of heart,
will be pleased to accept that, and pass by my weaknesses.
I have nothing to boast of but my infirmities, and the mercies of God.
I wish, above all things,
that my children may be brought up in the way of truth and righteousness,
in simplicity and lowliness of mind;
for with such a state the Omniscient is well pleased.
I have been fearful lest the enemy should have transformed
himself into an angel of light,
and deceived me; but I have desired, if there were any lurking sin in me,
that it might be brought to judgment.
I am a wonder to myself.`"

In the course of the last two weeks of his life, the disorder made rapid progress,
and his sufferings continued to be great.
At one time he remarked,
that he had performed all his little services-that he had nothing to do,
but was ready when his heavenly Father should call for him.
During these his closing days, he was engaged, for hours together,
in praising the Lord for his goodness; and said, "`I could sing aloud for joy.
Oh! that I had the tongue of an angel,
that I could plead with my friends to prepare for such a time as this.
What are all the riches and greatness of the world, to what I enjoy!`"

When under great debility, he said, "`You think I have been asleep, but I have not.
I have been enjoying such a quietude as I have not been favored with for days.`"
To some of his attendants he observed, "`This is a trying dispensation; you,
who are in health, should endeavor to prepare for such a time.`"
And again, "`This is a struggle.`"
A belief was expressed,
that it would work for him a far more exceeding and eternal weight of glory;
when he exclaimed, with great energy, "`Glory to God in the highest!
Oh! that You may come quickly-come quickly; but I will endeavor to wait your time.`"

He often prayed fervently for a little ease from pain,
and that his mind might be kept tender; and on one occasion, when under great suffering,
he remarked: "`Now I feel something run through me which takes away all my pain.
Is it possible that such a poor creature should be heard?`"
About a week before his decease, expressing a belief that he should not continue long,
he added, "`The arms of mercy are open to receive me.`"
He continued in a quiet, resigned state of mind; his understanding remained unclouded,
and his close was full of peace.

[.asterism]
'''
JOHN ELIOT was born in London, the second of the Twelfth month (old style), 1734-5,
of parents who were members of our Society.
Both of them dying in his early minority,
he came under the guardianship of his paternal grandfather,
who being engaged in foreign commerce, and designing his grandson for that line of life,
took care for his instruction in appropriate branches of learning,
particularly in the knowledge of different languages; and, at a suitable age,
placed him in a mercantile counting-house.
Amidst these facilities for his introduction into business,
the far more important advantage of a guarded education,
comporting with our religious profession, was unattended to.
The family in which he was placed were not of our Society;
and the example of his associates and connections was, with very little exception,
such as tended to lead away from our self-denying principles.
Thus situated, he freely indulged his inclinations in respect to dress,
and to the customary forms of deportment.

But soon after he arrived at manhood,
at a time when his prospects in life were flattering,
and when almost all outward circumstances concurred to immerse
his mind still further in the spirit of the world,
it pleased the gracious Author of his being to extend, in infinite mercy,
a powerful visitation to his soul.
He was favored with a sense of his unregenerate state to see, and deeply to lament,
that much of his time had been spent in unprofitable pursuits,
in seeking after worldly wisdom and acquirements, while the true wisdom,
which comes from God, and begins with his fear, had been neglected.
He saw the emptiness of all worldly possessions and enjoyments,
incapable as they are of affording lasting happiness to the human mind,
and the comparative unimportance of every pursuit,
which has not for its object the glory of the great
Creator and the welfare of the immortal soul.
It then became his concern to decline many of his former practices, to seek retirement,
and to be frequent in the attendance of meetings for worship.
Being advanced thus far, in obedience to the impressions of duty,
he felt (to use his own words,) an inward persuasion
to take up the cross openly to the world.
This he for some time withstood, trying many things with the hope of finding peace,
but in vain; until at length, after having been brought into much distress of mind,
he received strength to enter into that way of self-denial, with respect to language,
habit, and deportment, which our principles point out,
and which he afterwards often believed it right to recommend to others.

Not long after this observable change, which took place in the year 1757,
he yielded to a belief that it was required of him to bear a public
testimony to the efficacy of that Divine Grace of which he had
himself experienced the gradual and salutary operations.
But, before this, he was not lacking in earnest endeavors,
with some of his associates and connections,
to persuade them to adopt the same choice that he had made.
In one quarter, and that to him a peculiarly interesting one,
the effect of his example and of his counsel was early conspicuous.
An only and beloved sister, rather younger than himself,
had soon to acknowledge him as instrumental in strengthening her
previously visited mind to enter upon the path of Christian obedience;
which she pursued with much steadiness during the remainder of a short but useful life.

Within a few years after his first appearance as a minister,
he performed some visits in that capacity, chiefly in the southern part of this island.
In 1770, in company with several other Friends under appointment of the yearly meeting,
he visited the then remaining professors with us in Holland.
In 1788, he was engaged in further service on the continent.
It had become known that a number of persons at and about Congenies,
in the south of France,
held principles in several respects accordant with those of our Society;
and some Friends in the ministry, Sarah Grubb, Mary Dudley, and George Dillwyn,
having felt constrained to pay them a visit in gospel love, he, with Adey Bellamy,
united therein, and with the latter Friend was assistant also in interpreting.
Before the visit terminated, a consideration arose,
whether a public testimony to our principles and way of worship should not be borne,
by holding a meeting, open to all that might incline to attend.
This was a new proposal, the custom having been to assemble privately;
and there appeared some considerable risk of personal suffering,
in making the essay in a country where persecution had been formerly so grievous,
and where laws of extreme rigor were but then giving
way to the toleration which has since ensued.
The apprehension of danger did not, however, deter.
The meeting was held to satisfaction, and no molestation occurred.
In entering into this measure,
as the subject of the present brief memoir is understood to have done,
with promptitude and decision, he acted conformably with that Christian firmness,
in the performance of what he believed to be his own individual duty,
which may be said to have been prominent in his character.
Having endeavored to conduct himself as a faithful servant to his gracious Lord,
he had to take a peaceful retrospect of this arduous journey.

In general,
his services as a minister were confined to his own and some neighboring meetings,
and were not frequent.
His expressions, when so engaged, were mostly few and simple; the language, at times,
of consolation to the afflicted; at others,
of tender entreaty to the lukewarm and indifferent, exciting to the love and fear of God;
while, to the diffident and humble mind, his communications were often truly encouraging.
In the exercise of private admonition he was diligent, and he was anxious that,
in cases of departure from our religious principles,
or of a deviation from moral rectitude,
this office of love should be seasonably performed.

He was a humble man, of a meek and quiet spirit.
The tenor of his conduct with regard to the things of this life,
showed the influence of religious principle.
Alive to the need of guarding against a desire after the accumulation of wealth,
he was not solicitous to increase his paternal inheritance.
He entertained his friends with kindness and hospitality; and was, at the same time,
a good example of that simplicity in a domestic establishment,
which becomes the self-denying followers of our blessed Lord.
He also forcibly felt the obligation of making a right use
of that portion of outward substance with which he was entrusted.
Acting under this impression, he was one "`ready to distribute;`" and thus,
to many poor persons, as well as to others in reduced or straitened circumstances,
he was a kind and unostentatious, and he endeavored to be a discriminating, benefactor.

It is probably not unfrequent in the all-wise dispensations of Providence,
that those who may seem to meet with few adverse occurrences,
experience some of the deepest inward probations.
Of such this friend had, according to the observation of those who knew him best,
a large share.
Various were the exercises of mind which he underwent,
and amidst which he had often to pass as through solitary places;
yet he could at times derive encouragement from the belief that such seasons of conflict
and privation were the means of his furtherance in the Christian course.
Hence too he was well qualified to feel for those
who were brought low from inward conflict of spirit.
Of these exercises or trials,
some had reference to the consistent support of the testimonies, which, from its origin,
our Society has believed itself called upon to bear.
Faithfully to uphold them in his own practice with Christian meekness,
was his sincerely conscientious concern; and many are the proofs,
as regards his conduct in life, that might be given of the prevalence, with him,
of religious scruple over considerations of convenience, ease, and secular interest.

About a year before his decease, a close trial was permitted to befall him,
in the removal by death, of his endeared wife, who had been a truly helpful companion,
for a period of almost fifty years.
His own health, too, was infirm; and he was frequently in much pain,
which he bore with patience.
He had a prospect of his departure as near,
and it appeared that the view was to him a consoling one,
yet accompanied with very humble thoughts concerning himself,
as might be gathered from various sentences that he dropped,
but of which the particular words are not recollected.
A week or two before his last illness, in speaking to a friend, he emphatically said,
"`Mercy I want, and mercy I have.`"
His illness, which induced a great and rapid decay of strength, was short,
and he had little on his mind then to express, but desired his son and daughter,
who were attending upon him, to pray that he might have an easy passage; and afterwards,
on one of them expressing a concern for his great bodily weakness, he replied,
"`It is as the Lord pleases.`"

This '`dear and valued friend,`' to adopt the expressions
used by the members of his own monthly meeting,
very tranquilly departed this life on the 9th of the first month, 1813,
at his house in Bartholomew-close, London.
He had nearly attained the age of seventy-eight,
and had been a minister about fifty-three years.

[.asterism]
'''
JOHN GLAISYER, of Brighthelmstone, was born at Icklesham, near Rye, in Sussex,
in the year 1739, and was educated by his parents as a member of the church of England.
About the twentieth year of his age,
he became dissatisfied with the forms and ceremonies to which he had been accustomed;
and, after attending the meetings of several other religious societies,
without finding that solid comfort which his soul longed for,
he and a few others separated themselves from all forms of worship,
and met on First-days on the rocks by the sea-side.
In these secluded approaches before the throne of grace,
they were frequently refreshed by the presence of Him who has declared,
"`Where two or three are gathered together in my name,
there am I in the midst of them.`"

He was admitted as a member of our Society in the year 1769.
At this time, the discipline in the parts where he resided, was in a very low state;
but he soon found it to be his place to endeavor to put in practice our
salutary rules for the promotion and establishment of good order.
He manifested a fervent concern, both by his example, and exhortations to his friends,
that the important business of our meetings for discipline
should be transacted under the influence of the Holy Spirit.
When about forty-seven years of age,
he first spoke as a minister in our religious meetings.
His communications were not frequent,
and he was very cautious of interrupting the solemnity of true silent worship; indeed,
his friends were ready to apprehend that his diffident
mind sometimes gave way to too much discouragement,
and that this commendable care was carried too far.
But when he was strengthened to impart counsel, he was clear and sound;
his words few and impressive, inviting others to come and taste,
and see for themselves that the Lord is good.
He was often concerned that all might experience a secret exercise of mind, and in true,
inward silence, become worshippers of the Father in spirit and in truth.

He piously endeavored to discharge his religious
and relative duties as becomes a true Christian;
and, at a period of life when he was necessarily engaged in the cares of business,
it was his practice frequently to call his family together to wait upon the Almighty.
In these opportunities, he was often enabled to impart sweet counsel;
and there is reason to believe that his faithfulness, in this respect,
was blessed to himself and others.
He was a striking example of circumspection of conduct,
and watchfulness over his words and actions, jealous of himself,
and tender of exposing the failings or weaknesses of others;
yet faithful in offering private reproof or counsel, when duty required it of him.
And although but little known beyond the limits of
the quarterly meeting to which he belonged,
it may be truly said that his light shone with brightness in his own neighborhood.

Some time before his decease, he had several paralytic attacks,
which affected both his bodily and mental faculties; yet, at intervals,
his judgment was clear and sound.
At these times he was often engaged in fervent supplication, that he might be preserved,
both in word and deed,
from any thing that would cause the way of Truth to be lightly spoken of;
manifesting that his hope and trust were in redeeming love.
The love of God in Christ Jesus was a subject on
which he delighted to dwell from his youth;
and when he had the free use of his faculties, this seemed to be the anchor of his soul,
and that of which he was desirous that others should become partakers.

He died the 18th of the Fourth month, 1813, at the age of seventy-three.

[.asterism]
'''
MARY BEVAN, wife of Joseph Gurney Bevan, of Stoke Newington,
was the daughter of Robert and Hannah Plumsted, and was born in London, in the year 1751.
Her father, who had been for some time an acknowledged minister,
died when she was about nine years old.
The care of her education, as well as that of her younger sister,
of course devolved on their surviving parent,
who devoted her time and attention to her children, in a manner seldom surpassed,
and not often equalled.
The effects were very early visible in the subject of this memoir,
and she was remarkable for exemplary consistency of conduct in her station in life.
Her mother lived to an advanced age,
and this parental care was afterwards repaid by a
full share of filial love and attention.

In the more immediate circle of her friends she was much and deservedly beloved.
She was a humble woman, one who was concerned to live in the fear of the Lord,
very watchful over her words and actions,
careful not to over-rate her own religious impressions,
but sincerely desirous of being found in the way of her duty; and,
though her outward situation was exempt from many
of the cares and anxieties of this life,
she was conscientiously concerned to walk in the path of self-denial,
and to work out her own salvation with fear and trembling.
She manifested much interest in the spiritual advancement and comfort of those
who were uprightly endeavoring to walk in the right way of the Lord;
and often extended a friendly care to some who, from their secluded situation in life,
might not obtain much of the notice of their friends.
At the same time, she endeared herself, by her kind and affectionate behavior,
to many who had not so fully submitted to the yoke of Christ.

In the year 1784, from a conviction of duty which had long been on her mind,
she first appeared as a minister in our meetings for worship;
in which service she was acceptably engaged, while ability remained.
Her communications were short,
and she was particularly careful not to exceed what
she apprehended to be her commission.

This dear friend was seized with a fit of an apoplectic nature, in the year 1810,
but recovered so much, in the course of a few weeks,
as to encourage some hopes that its effects would wear off.
These hopes were, however, quite destroyed by a second attack;
and seizures of this kind afterwards became frequent.
During the course of this afflicting illness,
she appeared to derive much consolation from continuing
a practice which she had long observed,
that of allotting a portion of each day to wait in silence upon the Almighty.
On one of these occasions, having herself an apprehension of approaching death,
she sweetly uttered these expressions; "`Be pleased, O Lord, to forgive all my sins,
to pardon all my faults, and receive me into glory.`"
And at another time she supplicated in the following manner: "`Enable us, O Lord,
to be still, and know that You are God.
Preserve us from endeavoring to offer prayer merely in words of our own;
but grant us a degree of living faith that we are yours,
and that you will not forsake us.`"
About twelve hours after an attack, which for a time deprived her of recollection,
she uttered these few words: "`O Lord, be pleased to help me;
be pleased not to lay on me more than I can bear.`"
These sincere petitions, though simple in their style and character,
instructively portray a humble, pious mind, relying, in the midst of sore trial,
on the mercies and compassion of Him who is all-powerful and gracious.

Many distressing hours were subsequently at times her portion,
but the spirit of prayer and gratitude was often felt and acknowledged.
On the 23rd of the Fifth month, 1813, she was released from the conflicts of time;
and her surviving friends had the consolation to believe that her
purified spirit ascended to the realms of everlasting peace.

[.asterism]
'''
ANN KITCHING, daughter of William and Ann Kitching, of Darlington, was born there,
in the First month, 1776.
She was an amiable and dutiful child, and, when about nineteen years of age,
came to reside with her brother in London.
After his marriage, from an apprehension that,
by a more entire occupation of her time in the service of others,
she would render herself more useful in society,
she became an inmate in Joseph Foster`'s family at Bromley,
where she lived about thirteen years,
and was a very helpful assistant in the care and management of the children.
By her kind and judicious behavior, and an unwearied attention to their comfort,
she greatly endeared herself to them,
and left on their minds a deep and lasting impression of love and esteem.
She was an example of great humility and propriety
of conduct towards the servants in the family,
highly valued, confided in, and consulted by the friends with whom she lived;
endeavoring in all things to act upon religious principle, in "`singleness of heart,
as unto Christ.`"

In the summer of the year 1809, she left her kind friends at Bromley,
to pay a visit to her relations in the north, intending, after an absence of a few weeks,
to resume her usual engagements.
During this absence she had a serious attack of illness,
from which she partially recovered,
but was never well enough to return into the neighborhood of London.
Her protracted illness was peculiarly trying, and her sufferings were often severe; and,
in the course of the four years previous to her death,
it was considered that she scarcely knew what it was to be long free from pain.
Under these afflictions she manifested great cheerfulness:
her mind was much occupied with the things of eternity;
but she was cautious of speaking of her religious feelings,
and earnestly sought after resignation.
The following extracts from some of her letters to a beloved brother,
instructively show the progress of the work of purification.

1809.--Tenth month, 12.`' I far more dread a lingering illness,
than a removal from a state of mutability.
I think I could give up all that is dear to me in this world,
if it please the All-wise Disposer of events to cut the thread of my life before long,
having nothing that I know of to stand in my way, or make me very uncomfortable.
What I most desire is,
that I may stand fully resigned to whatever it is my lot to undergo,
whether my life be longer or shorter.`"

1811.--Third month, 16. "`If I am not mistaken, and I hope I am honest,
I have liberty to remark, that I have several times been enabled to say, Lord,
give me patience and resignation, with a humble hope that I may be accepted,
when it shall please You to deprive me of life; and then I am content, and can say,
'`Come life or death, all is well.`'
And oh! to feel the divine arm underneath,
to support in our trying conflicts with bodily infirmities,
is an attainment worth striving for.
I hope I have felt something of this under my late sufferings,
which has been a cause of thankfulness; and I believe a great support to me,
and many times kept me from complaining outwardly, which could do no good.`"

Eleventh month, 16. "`I can, after all, confess with gratitude,
that I have indeed my low times: although they are trying,
yet I firmly believe they are of great use,
and make a state of silent tranquillity an enjoyment,
which we should not sufficiently prize without them.
Command divine, '`Be still, and know that I am God.`'
What instruction has this single line at times been to me,
when my mind has comparatively been as a troubled sea, yet under all evidently supported;
yes, I may perhaps say comforted, by a secret something that kept me from despairing.`"

1812.--Fifth month, 5.--(Written by a friend, as dictated and signed by herself,
her weakness and sufferings being such as to prevent her writing herself.) "`As
you so affectionately desire to be informed of the feelings of my mind,
I can freely acknowledge, in the depths of humility, and, I sincerely trust,
without presumption, that since my close confinement to my chamber,
I have great comfort in believing that my commission +++[+++of evil]
will pass beforehand to judgment; and I feel freedom to tell you,
that I have been enabled to resign myself wholly into the hands of a never-erring,
merciful Creator, and desire to live, day by day, on daily bread,
and not on the manna gathered yesterday.
I do not so much as feel a desire to know how this weakness may terminate;
but certain I am, at least I believe it,
that my afflictions have been mercifully permitted for my soul`'s good.
With feelings like these, how can I but be cheerful, even under bodily suffering.
Low seasons, seasons of darkness, and, as it were,
the withdrawing of that consolation and quietude which are so desirable,
I have cause to believe, bring great good, when properly abode under.
Preservation, and fortitude to desire, wish or be anxious for nothing,
is what I most earnestly crave.`"

Eighth month,
15.--(Written in addition to a letter which had been begun three months previously,
but which she was then unable to finish.) "`When I look back,
and reflect on my apparent recovery from so very trying and additional suffering,
I cannot but admire the condescending goodness of a merciful Creator,
who dispenses a due portion of strength to support even the least of the family.
If I am but favored to continue resigned and peaceful,
I shall indeed be enabled to bear whatever is yet left for me to suffer.
What are the sufferings of the body, compared to a mind at ease!
Oh! that faith and patience may hold out; and why should I doubt,
seeing so much has already been granted, and my poor spirits kept up to admiration!
It is good to trust in the Lord, and to resign all into his Almighty hands.
He is indeed strength in weakness, and a never-failing helper in every time of need.
Oh! that I may never cease to praise Him for all his benefits,
for He is worthy of adoration and praise, at all times, and in all places.`"

Twelfth month, 4.-- "`To look towards a recovery seems now almost out of the question;
but still I think I feel the sufficiency of that
power that is able to calm the troubled sea.
My greatest fear is, that,
should it please our heavenly Father to restore me to health again,
I shall not be able to stand so firmly and faithfully
on the immoveable Rock as I could wish.
This nature of ours is so prone to evil, so anxious after perishable objects,
instead of laying up treasure that does not corrupt,
and will stand us in stead at a trying time.
I feel so poor and weak sometimes, as to be hardly able to crave a little bread,
and as if I were ready to faint by the way; still these have been profitable seasons.
We should not expect or desire always to be filled.
I seem as if there was no better way for me, at present,
but to endeavor to keep under the refining fire, to be resigned and willing,
either to remain still suffering, or to be restored.`"

1813.--Tenth month, 3. "`It is a good thing to feel resigned,
and requires great watchfulness to keep us in so safe a place:
if we do but resign ourselves, and everything belonging to us,
fully and freely to the hands of a kind and gracious Providence,
we need not be anxious for the future.
But then, are we sincere?
Do we in no wise deceive ourselves?
We must keep nothing back: nothing short of a total surrender will do;
nothing short will, I believe,
bring us that peace which the world can neither give nor take away:
it is worth seeking after, and patiently waiting for.
Be not weary in well doing: press forward for the prize.
Oh, to be deserted on a sick bed would be sad indeed!
What a melancholy time should I have had,
if a most kind and loving Father had not so tenderly condescended
to compassionate all the various states of a poor worm,
and held out the cup of consolation in the needful time.`"

She thus further describes her feelings to her absent friends.
"`Surely, while the Lord is our Shepherd, we shall not lack any good thing.
I have been as comfortable since our parting as I could wish.
Oh! how humble ought we to be,
when we consider the daily benefits that a most beneficent
and tender Parent is bestowing so bountifully upon us.
Let us then do all in our power to set a true value on such favors.

"`I sometimes find, in my weak, helpless state, satisfaction in exerting myself,
to try if I can find any way to be useful in the least degree, either in word or deed,
and do my best in that respect: it yields a pleasant thought, if the action fails;
and perhaps helps to keep the mind in a better state
than in ruminating on things that should be left.
I can acknowledge, that I never felt so comfortable,
until I was enabled to do my best in pressing forward daily,
without being anxious for the future, which saves much anxiety.
We know not how much may be ours; therefore, to do our best each day,
as we may be favored with them, is certainly wise.`"

We may be instructed in observing how, through the power of the Holy Spirit,
the afflictions of our departed friend became the means of her increased purification.
Not very long before her death,
when speaking of the many spiritual conflicts and
baptisms which she had passed through she remarked,
that three years before, when looking over her past life and conduct,
she did not see but that she was in a good degree prepared for heaven; but,
as time passed on,
the prospect of the life which is to come was increasingly solemn in her view.

In the Ninth month, 1813, in conversation with her brother, she remarked,
that while she had believed it right for her to be very
cautious in speaking of what was passing in her mind,
she then felt a liberty to converse with him on the various
mental trials and exercises which she had gone through,
and on the heavenly peace which she had often been permitted to enjoy.
She showed in a clear and affecting manner,
that she had found the way for her to partake of this blessing,
was an entire surrender of the will, and a full dependence on Almighty help;
not having a thought which would be offensive in the divine sight,
but day by day keeping continually on the watch, in inward stillness.
She had found this to be a state of mind which the enemy of man`'s happiness cannot disturb,
and in which the soul is enabled to rely upon the goodness and
all-sufficiency of the love and mercy of its God and Savior.

Towards the latter end of the year 1813, this patient sufferer became increasingly ill,
and her attendants apprehended that her end was near.
She remarked to an intimate friend who called to see her,
"`Oh! what a comfort it is to have the Lord for our support at a time like this!
I have not now to seek for help.`"
On its being noticed to her,
that she had been remarkably supported during the whole of her illness,
and that it was to be hoped she would continue to be so to the end, she said: "`Yes;
but the conflict is not yet over.
But I trust I shall be supported to the end.`"
And a day or two afterwards, when her seeing the light of another day seemed uncertain,
she requested that her friends might be informed,
that at this trying hour she was mercifully supported, beyond her expectation;
and that she could not have thought she could have felt so comfortable,
at the prospect of so awful an event as appeared likely very shortly to take place.

She was frequently refreshed by hearing the New Testament read to her,
but was only able to listen to a small portion at a time.
On one of these occasions, in allusion to what had been read, she remarked:
"`To feel comfort in tribulation is a great thing; but when the Comforter comes, then,
indeed, we do feel comfort.`"
She spoke with difficulty; and saying only a few words at a time was painful to her,
and increased the cough and irritation in her throat.

The stiffness and contraction of the ligaments and muscles of her back and limbs,
with which she had been so long afflicted, were now gone off; they had rendered moving,
and particularly coughing, extremely painful.
Her friends had been obliged to hold her back very firmly, when the cough came on;
otherwise the pain which it occasioned was almost insupportable:
the removal of these afflictions proved, therefore,
a great alleviation of her sufferings.

Within a few days of her death, she observed to one of her friends, that,
on looking at the separation of the spirit from the body, it seemed an awful thing;
but that she had been strengthened and comforted,
in a way which she did not know how far it was right for her to express;
and that when the awful moment came, she humbly trusted she should not be forsaken.
She said,
that during her illness it had been her lot to have many seasons of perplexity and difficulty,
so much so, at times, that she had almost resolved to speak to some experienced friend,
respecting the state of her mind; but she never could feel freedom to do so,
and this language had been impressed on her spirit: "`Be still, and know that I am God;
cannot I do all things for you?
Who is there in all the earth that can do you any good?`"
"`Yes,`" she added, "`Be still, and know that I am God.`"
But`' she continued,
"`We are so unwilling to endure all those operations of the divine hand,
which are so necessary for our purification, that,
instead of waiting in stillness and resignation of mind,
we are apt to look around us for help; thinking, perhaps,
that we are tried in a different manner from others, and that,
by unbosoming ourselves to a friend, we may get a little relief.
But we shall none of us have more laid upon us than we shall be enabled to endure;
and who is so able to assist us, as He who is not only able, but willing to save,
and mighty to deliver.`"

Her sufferings from frequent attacks of pain, the feeling of great irritation,
and difficulty in breathing, were often distressing, so that she could speak but little.
On one of these occasions, a few hours before her death, she clasped her hands, and said,
"`Lord, Lord, be pleased to release me:`" and again, towards morning, "`Oh, Father,
you have been merciful to me!`"
About an hour before she departed,
on observing her friends preparing to move her a little,
she desired them to "`wait awhile;`" and a short time before the solemn close, said,
"`I am going home.`"

Her closing moments were attended with an apparent release from all pain; and,
on the 5th of the Eleventh month, 1813,
her spirit was mercifully withdrawn from its afflicted tenement,
and no doubt was admitted into those regions of purity and peace,
of the nature of which it had so long and so largely partaken.

[.asterism]
'''
WILLIAM WRIGHT, of Cork, was the son of William and Mary Wright, of the same place,
and was born there in the year 1783.

Through submission to the influence of divine grace, he was, from early youth,
of steady conduct, and a good example in life and conduct.
He was a regular attender of meetings for worship and discipline; and, for several years,
was diligent in going to the quarterly and yearly meetings to which he belonged,
and was twice, in the character of a representative, at the yearly meeting in London.

In temper and disposition, he was conspicuously amiable and gentle,
a kind and sympathizing friend,
upright and punctual in his dealings and interactions among men; and,
although necessarily and industriously engaged in trade,
he appeared to live loose from the world,
and to be preserved from the contaminating influence of its spirit.
He was an example of moderation and temperance in his own family;
and careful to have a portion of the Holy Scriptures daily read in it.
A considerable portion of his time was devoted to
the important concerns of our religious Society;
and in the part which he had to take in the support of our discipline,
he manifested much humility and diffidence.
He was appointed to the station of an elder, a short time before his death.
Although in the ordering of unerring Wisdom,
he was early removed from a sphere of usefulness, yet it may be said of him,
that "`he was as a plant grown up in his youth,`" to whom the expressions appeared applicable,
"`Wisdom is the grey hair unto men, and an unspotted life is old age.`"

During a short, but painful illness, accompanied by a fever,
while his understanding continued he was preserved in calmness,
evincing that his mind was stayed in resignation to the will of God,
which he also expressed to be the case.
On the 4th of the Twelfth month, 1813, he quietly expired,
leaving the consoling evidence that his end was peace.

[.asterism]
'''
JANE SHIPLEY, daughter of John and Elizabeth Dearman, of Braithwaite, near Thorne,
in Yorkshire, was born in the year 1734.
When about the age of thirty-one, she was united in marriage to Thomas Shipley,
of Uttoxeter, one who was well esteemed by his friends;
and in the year 1770 they removed to within the limits of Shaftesbury meeting,
in Dorsetshire, of which they continued members during the remainder of their days.

Early in life, her soul was quickened by the invisible power of God,
and continuing obedient to its manifestations,
she was prepared for the work of the ministry;
a service in which she was first publicly engaged when about the age of twenty-one.
In the exercise of her gift, until near the termination of a long life,
having attained to her eightieth year,
she often found it to be her duty to encourage others,
to seek first the kingdom of God and his righteousness.
The inestimable benefits which result from being thus exercised,
she exemplified in humility and circumspect conduct;
and having known in her own experience, the sufficiency of the grace of God,
she earnestly entreated others, by a faithful dedication of heart,
to press after the attainment of true peace.
Her gospel labors were acceptable to her friends: they were nearly, though not wholly,
confined within the boundaries of the quarterly meeting of which she was a member.

During the course of her pilgrimage, she underwent a variety of close trials;
but as her mind was turned to Him whose tender mercies are over all his works,
these trials were sanctified to her; and as she advanced in life,
Christian simplicity and meekness were more and more conspicuous in her character.

She was a good example in the attendance of religious meetings,
even when much enfeebled by age and infirmity.
The last time at which she thus assembled with her friends,
which was about three months before her death,
she impressively revived among them the solemn language of the apostle Peter,
"`I think it meet, as long as I am in this tabernacle, to stir you up,
by putting you in remembrance; knowing, that shortly I must put off this my tabernacle,
even as our Lord Jesus Christ has showed me.`"
Adding, in humility, that she knew, by experience,
that there was a support in religion when all things else failed; and that she believed,
that whenever it might please the Most High to release her,
a place of rest was prepared for her immortal spirit.

Her last illness was at times attended with acute bodily pain,
which she was enabled to endure with patience, and resignation to the divine will.
In the course of it she uttered many pious expressions:
at one time she was led beautifully to mention the goodness of the Almighty
to those who were obedient to the discoveries of his will,
adding: "`I have for many years felt bound to the friends of my own meeting,
and I think I have been favored with a consoling
evidence of having been in my right allotment,
and that I have discharged my duty faithfully towards
those among whom I have had to labor.
My spirit still feels as anxious for their eternal salvation as at any period of my life,
and I believe I shall continue to do so unto the end of my pilgrimage.
I should be glad to have my dear love in Christ Jesus presented to them;
and they may be informed, my soul at this season salutes them,
in the love of the everlasting Gospel, and very affectionately desires they may,
through obedience to the monitions of divine grace,
become built up in the most holy faith.`"

Her son inquiring one morning after her health, she replied:
"`I scarcely know what to say; but I hope nature will soon yield to the disorder,
that my tribulated spirit may be at rest.
All I dare ask or hope for is, that my Almighty Father may,
through the mercies and merits of the dear Redeemer of mankind,
admit my spirit into rest and peace.
This is what I have earnestly labored after, even from early life; desiring,
according to my ability, to be made conformable to the divine will.`"

A few days after this she remarked, that it seemed wonderful,
at her advanced period of life, that her strength should hold out so long,
when nature seemed at times nearly exhausted; adding:
"`How long the infinite Holy One may see fit to continue me in this state, I know not;
but I ardently long to partake of the joys of God`'s salvation; and that you,
my dear children, may unite with me,
in praying that I may be speedily released from all pain and conflict,
and admitted into that bliss prepared for the righteous.`"

Being asked, the next day,
if she felt more comfortable than during the preceding morning, she replied;
"`I do not know that I have felt anything like comfort during the night,
for my mind has been involved in conflict and distress:
the accuser of the brethren seemed let loose to buffet me,
and to suggest such fears and discouragements:`" but added, "`It is said,
all things work together for good to those who love God;
and this morning a comfortable hope is again revived,
that my faith and patience will not fail; but that, through holy aid,
I shall be enabled to hold out to the end, and finally lay down my head in peace.
This is all I wish for, all I pray for.
My affections have, for a long time past,
been much fixed on the glorious Object of the saint`'s faith in all ages of the world.`"

The following day, on a hope being expressed that she had not to contend,
during the night, with conflict of mind as well as of body, she said: "`No;
that was measurably and mercifully withdrawn,`" and some time after added:
"`It is given me to believe, that when I lose sight of faith,
and fears and discouragements prevail, it is the effect of my great weakness,
and the height of my fever.
There is such an intimate connection between the mind and body, that,
when one is affected, the other, more or less, participates in its sufferings.`"
On another occasion, she said to one of her children: "`In low seasons,
I am apt to fear I have said or done something which has offended my great Master,
that it pleases him to keep me so long here, in a poor, afflicted state,
wherein I seem of no use in the creation; yet I know all his ways are just and equal,
and it is not for us to fathom his inscrutable designs.
These fears will, through weakness, intrude; yet, at other seasons,
my mind is favored with a full belief, that, whenever the solemn close may come,
my spirit will be graciously admitted into everlasting rest.`"
Again, speaking of the hope she had of salvation, she said:
"`I have nothing to trust to but the mercy of God in Christ Jesus our Lord;
for it is not by the works of righteousness which we have done,
but according to his mercy,
he saves us by the washing of regeneration and renewing of the Holy Ghost.
And, oh! that this necessary work may be fully accomplished in my soul,
that nothing may remain that is impure;
that my spirit may be arrayed in the white robes of righteousness.`"

To one of her daughters she said: "`You see me, my child, in a very suffering state:
nature seems to maintain a harder struggle with the force
of my disease than I once expected would have been the case;
but my duty is submission.
Oh, my dear, when you come to experience the same reduction of strength that I now do,
then, if not before, you will fully know of how small value is the greatness, grandeur,
or pleasures of this changeful scene ---how little they can avail in hours such as these.
I am very weak and full of pain;
but it is a great favor to feel nothing in the way-nothing to do but to die.`"

As the time of her departure drew near, she was often engaged in fervent supplication,
that she might be released from the sufferings of the body;
that she might be dissolved and be with Christ.
On her son`'s coming to her one evening, she said: "`You find me, my dear,
in the same suffering state as in the morning.
When it may please the Lord Jesus to release me, I know not;
but I know that here I have no continuing city; and, for many years,
it has been my earnest desire and endeavor to seek one which has foundations,
whose maker and builder the Lord is.`"
She then prayed: "`Oh, Holy Father, be pleased to look down in mercy upon me,
and in mercy admit my weary spirit into that blessed and glorious city,
whose walls are salvation, and whose gates are praise; but your will, O Lord, be done.`"
Soon after, she said: "`I am sometimes ready to fear my faith and patience will fail me,
or at least,
that I shall not be enabled to bow in that degree of holy
resignation to the divine will which I ought to do;
but if these light afflictions, which are but as for a moment,
should work for me a far more exceeding and eternal weight of glory,
it will be a blessed thing; and under the remembrance of many seasons of former favor,
my soul blesses and magnifies the name of Zion`'s King, who is worthy forever:
he has been as a stay and a staff to my mind, under many deep afflictions;
and I have learned to put my trust in Him.`"

On the 2nd of the First month, 1814, she prayed: "`O,
most merciful Father! if it be your blessed will,
be pleased to cut the work short in righteousness,
and receive me into your heavenly kingdom; for I have no one to trust to, but you,
for help; who still remain to be the strength and salvation of your people.`"
She afterwards said: "`Though I am very afflicted in body,
yet I am comfortable and resigned in mind;`" and on the
6th of the same month she quietly departed this life,
like one falling into a sweet sleep.
