== Chapter 4

[.chapter-synopsis]
* Robert Tregelles
* John Tregelles
* Joseph Tregelles
* Catherine Tregelles
* Henry Tregelles
* Mary Tregelles
* William Sowerby
* John Bateman
* Ann Dymond
* Richard Reynolds

ROBERT TREGELLES.
--In relating some particulars of the last days of several young persons,
children of Samuel and Rebecca Tregelles, of Falmouth,
all of whom survived their exemplary mother,
it should awaken pious reflections thus to observe
so many of one family early made fit for,
and removed to that city which has foundations, whose maker and builder is God.
The natural dispositions of these young persons were very different,
consequently their besetments were so: but the great Physician to whom they applied,
knew how to administer to all their needs.
The help of the Holy Spirit was not withheld from these sincere suppliants for its renewing,
sanctifying influence; and it will be seen, in the course of the following narratives,
that they were, in their different measures, enabled to witness a good confession,
and to lay down their heads in peace.

Although there is not much to record respecting Robert Tregelles,
yet the lively faith and hope which supported him,
during the progress of a very gradual consumption,
appear worthy of being briefly noticed.
In him the saying appears to have been exemplified,
that "`wisdom is the grey hair unto men, and an unspotted life is old age.`"
For though he had but just attained his sixteenth year,
when he was removed from this state of existence, his discretion was remarkable;
a strict attention to truth also, from very early childhood,
stamped such frankness on his character, as gave additional luster to every part of it.

As the disease gained ground,
and he became sensible that it was not likely he would ever
have to take an active part in the concerns of this life,
his mind was evidently more and more stayed on the immoveable Rock;
so that he could contemplate the approach of death without dismay,
trusting in that infinite mercy which had reached, and was redeeming his soul.
His views of himself were humble; but he appears, except on one occasion,
to have had this blessed hope of eternal peace unshaken.
Having, at that time, given way to some speculation, he evinced, by his manner,
that something distressed him.
This led to an inquiry as to the cause, when he replied,
that he had been endeavoring to fathom a great mystery: namely,
in what the joys of heaven could consist; and not being able to come to any conclusion,
he felt tried.
He was answered: "`Eye has not seen, nor ear heard,
neither have entered into the heart of man,
the things which God has prepared for them that love Him.`"
After a short pause he expressed himself fully satisfied,
and sensible that it was at least unprofitable thus to dwell on such subjects; saying,
that he could entirely trust to Divine mercy, for being in such hands, all must be well.

After an almost imperceptible decline, for more than a year,
he was at length taken off rather suddenly, having only a few hours of increased illness.
He had sat up the usual time, on the 10th of the Fifth month, 1815,
and retired to bed without any symptoms of immediate dissolution;
but very early the following morning the family were called up,
and it was seen that life ebbed quickly.
Being dressed and laid upon the sofa, he remarked more than once,
what a glorious morning it was;
which those around him considered as emblematic of the more
glorious one which was about to rise on his soul.
He desired one of his sisters to read, and when he could no longer speak,
showed evident marks of being still able to understand; pressing her hand,
and looking at her with great emotion, on her reading that passage of Holy Scripture,
"`Precious in the sight of the Lord is the death of his saints.`"
His face beamed with heavenly peace; and as he gently passed away,
a sweet smile fixed on his countenance.

[.asterism]
'''

JOHN TREGELLES died at Ashfield, near Falmouth, on the 8th of the Eighth month,
aged nineteen years and a half.
His early youth was marked by an unusual sweetness of natural disposition,
which gained him the love of those with whom he associated.

At the age of fifteen, he was placed as an apprentice at Wellington,
where there is reason to believe that he was concerned
to enter into covenant with the Lord,
and through his gracious assistance,
was enabled to walk before Him with uprightness and humility.
At this place he continued until the autumn of 1815, when a cough,
to which he had been subject, increased to such a degree,
that it was thought necessary to try his native air; but,
contrary to the expectations of his friends, he became rapidly worse,
so that a long voyage to a milder climate, during the remainder of the winter,
seemed the only expedient that could be tried with hope of benefit.
This he almost immediately undertook, accompanied by his brother Joseph.

They sailed for Jamaica, intending to touch at the Bermudas,
to which place they had a stormy passage of ten weeks,
and on their arrival were shipwrecked.
Staying some time there, they proceeded to Jamaica, and from there returned to England,
after an absence of twenty-four weeks; in which interval they had, from various causes,
undergone much suffering.
While in Jamaica, and on his return home, he was greatly tried in spirit;
but the arm of divine power was extended for his support,
which he acknowledged as a peculiar favor.
On one of these occasions, when everything outward looked discouraging,
and his mind was much bereft of consolation, a dream became the means of comfort.
It appeared as if he were alone on the water, in a small boat, exposed to a great storm,
so that he found it quite ineffectual to row: after much exertion he laid down the oars,
concluding that the only way was wholly to trust in divine help.
When enabled so to do, he soon found himself in safety,
and was received on the shore by his beloved mother, who showed extreme joy,
and expressed her thankfulness that another of her sons was safely landed.

On the 18th of the Seventh month, 1816,
in allusion to some matters which he had wished to attend to, he said he had found,
during the whole of his illness, and in the midst of many difficulties,
that when he could leave things entirely, and commit his cause to the Almighty,
a way was made for him where there appeared to be none.
At another time, being inquired of respecting the disposal of his books, he answered:
"`I have not been so careful in the choice of my books as I ought to have been.`"
On being told that none of them appeared to be of a hurtful tendency, "`No,`" he replied,
"`I hope not; but now I should wish to have such as would be really profitable.`"
After this, he gave many clear directions respecting things which he wished to have done;
saying,`" These appear trifles now; but I should not find them trifles on a deathbed.`"

On the 26th, he intimated that what had been said to him in the line of ministry,
in a time of religious retirement which had occurred, was very suitable;
"`for,`" he added, "`I have many times felt great poverty; and sometimes, while at sea,
was tried beyond what I can express;
but I can say the Lord has delivered me out of all my troubles.`"
Two days afterwards, conversing with one of his sisters, he said, with great affection,
"`I have a full hope; and I believe, after a few years are past,
we shall meet to part no more.
I trust all will conduct themselves so that we may meet again.
I have felt anxious about some; but it is taken from me, which is a great favor.`"

Early in the Eighth month, a great alteration appeared,
and extreme bodily suffering attended.
He once said,
"`It will be only a little longer;`" and being reminded that it was a great mercy,
at such a time, to have nothing to contend with but the pains of the body, he replied,
"`I find it so.`"
He had expressed some solicitude to see two of his brothers; and on their arrival,
acknowledged his thankfulness to his Heavenly Father
for permitting him to live to see them.
After some other counsel, he thus addressed one of them:

"`When you meet with difficulties, trust in that Power which is able to sustain you:
pray often to Him, and wait for his direction.
I have always found that He helped me out of my troubles.
I have settled my outward affairs to my satisfaction.
I have had time, and repented of all my sins;
and I believe they have been freely forgiven, through the merits of my Redeemer.
I owe no man any thing but love.`"

To an intimate friend, who was one of the family during the last part of his illness,
he said: "`My dear Charles, farewell.
I charge you, obey that Power which is sufficient to direct you in all your ways.`"
On the 7th, seeing some weeping, he said: "`Do not weep: there is no cause for mourning;
it is all thanksgiving.`"
He took an affectionate leave of many of his friends,
and sent messages of love to all he could think of; saying he felt it abundantly.
Between five and six the next morning nature gave way,
and in a few minutes his spirit was liberated without a struggle,
from its earthly tenement.

[.asterism]
'''

JOSEPH TREGELLES was removed from this state of being at the age of twenty-six.
He was a young man whose general demeanor, and obliging disposition,
gained the affectionate regard and esteem of those around him, in no common degree.
For seven years he had been liable to occasional attacks of illness;
but it was not until within about six months of his decease, that he became so ill,
as to excite apprehensions that his disorder, like that of his two brothers,
would prove consumption.

At an early age, he became sensible of the influence of the love of God upon his soul,
and in the view of others,
his general conduct appeared consistent with his religious profession; yet,
when the solemn prospect of death came before him,
great was the distress of mind in which he was involved,
for a time refusing to be comforted; and being afraid even to give sleep to his eyes,
lest he should be cut off, without feeling an evidence that his sins were blotted out;
his language often being, "`Oh, I have acted against conviction.`"
In this state he passed several weeks, crying earnestly day and night before the Lord;
for his soul could not feel satisfied without an inward
assurance that there was nothing retained against him.

On the 22nd of the Third month, 1817,
some symptoms appeared to indicate that his change was approaching.
On one of his sisters proposing his removal to a chamber
where he would have more air than in his own apartment,
he was much affected,
and answered that he did not deserve any of the comforts with which he was surrounded.
She endeavored to comfort him, and told him there was yet hope,
seeing he was sensible of the continued offers of mercy.
He replied, with great earnestness, "`Oh! yes I know that;
but I have rejected these offers so long, that I can expect nothing.
I feel as if I had left it to the very last hour.
If I could expect to live but a few weeks, what a blessing should I consider it;
but of this there is no probability.
The fever which I now have, must soon wear me out.
It is the uneasiness which I feel about myself, that prevents my sleeping:
if it were not for this, I could sleep soundly any where;
but I have so long rejected what I knew to be right, that I fear it is now too late.`"

On his sister`'s remarking,
that she thought he had taken an undesirable view of his past life, he replied,
that it had been very different from what it ought to have been;
and that he had squandered his time,
particularly since his return from the West Indies with his brother John.
He would several times repeat, that he felt destitute of all help from above,
and dared not hope for mercy; that he knew there was no way of being saved,
except through the merciful intercession of the Redeemer; but that,
as he had despised and refused him while in health,
he could not expect to have the invitation again extended.
On his being reminded, that our blessed Lord came into the world to save sinners,
and that his prayers and tears would not be disregarded by the Savior of men,
he seemed a little comforted.

He continued for some time in this tried state of mind;
but within a few days of his decease,
he was enabled to feel an undoubted evidence of acceptance in and through Christ, which,
in much humility, he thankfully acknowledged; impressively observing,
that a short time before, he seemed to hear a voice, saying:
"`I and my Father are one;`" after which the mystery
of redemption appeared to open before him,
which, he said, he had not before known, or rather, had not understood;
and now called on those around him to join in giving praise where alone it was due,
for they might truly say, "`This is the Lord`'s doing, and it is marvelous in our eyes.`"

Notwithstanding the comfort in which this day was passed, he was fearful,
the following morning,
that the enemy had been endeavoring to lull him into a state of security.
In the evening, that part of Scripture was read to him,
which treats of our Lord`'s temptations,
after he had been acknowledged as the beloved Son;
and a remark being made to him thereon,
that there was no cause for him to be discouraged, though thus buffeted,
he said with great emphasis, "`I know that the Lord`'s hand is not shortened,
that it cannot save; neither his ear heavy, that it cannot hear: but I also know,
that nothing short of the infinite mercy of an all-merciful God can reach my case.`"

After this he became tranquil, and remained so until the close of life,
frequently expressing his great thankfulness.
He was often fervent in supplication, and the night before his departure, in these words:
Oh!
Lord God Almighty, have mercy on me, and pardon me, through your beloved Son,
our blessed Redeemer, who gave himself a ransom for the sins of the whole world.`"

On the afternoon of the day preceding his death, great pain and distress on the lungs,
for some hours, attended him, after which he became quite easy;
and as long as he could articulate, he continued to speak of the mercy of the Most High,
and was heard in supplication, when only a few words were distinguishable.
On taking something to drink, he said, "`I believe this is the last:
there is but one step between me and eternity.`"
He appeared to sink into a sweet sleep, and thus gently passed away, at midnight,
on the 26th of the Seventh month, 1817;
a remarkable evidence being granted to those present,
that he had entered into that rest for which his soul had so ardently longed.

[.asterism]
'''

CATHERINE TREGELLES, daughter of Samuel and Rebecca Tregelles of Falmouth,
through early submission to the regulating power of the Lord`'s Spirit,
was a striking example in the discharge of social and relative duties;
she evinced a tender regard to the feelings of others,
and manifested her humility by an amiable condescension to all.

When sixteen years of age, she met with a very close trial,
in the death of her beloved twin brother, Robert,
during whose lingering illness she deeply entered into sympathy with him; and,
on his decease, her mind became much weaned from the things of time,
though she retained a true relish for its lawful enjoyments.
Soon after the completion of her nineteenth year, she took a cold,
which terminated in a consumption.
During the progress of her disease, she was much disposed to number her blessings,
but made little mention of her sufferings.
Indeed, such was her submission, that nothing like a murmur was known to escape her lips.
But she also passed through much distress of mind,
particularly in the early part of her illness,
in the remembrance of her secret sins and transgressions.

In the autumn of 1818, she became sensible that the disorder was of a serious nature.
At that time she had so far overcome her natural diffidence,
as to tell one of her sisters that she was quite aware of the uncertainty of her recovery;
adding, that in whatever way her illness might terminate,
she knew it would be for the best.
And after some further conversation, remarked: "`What I suffer every time you leave me,
enables me to form some idea of what my sufferings would
be with the prospect of a final separation before me.
Oh! the pang is indescribable.`"
Gratitude seemed to be the clothing of her spirit, first towards her heavenly Father,
for the immediate extension of his favor; and then towards her friends,
for their affectionate interest in her comfort and accommodation.

The prospect of death being very awful to her, she thus described her feelings,
in a letter written about the end of the Eleventh month, to one of her sisters:
"`I cannot be too thankful to my truly kind friends,
for the openness with which I have been treated respecting my complaint:
for so flattering is its nature, that I might have been kept in ignorance to this day.
It is not in my power to express what I felt for
some weeks after I became aware of my danger,
at the prospect of a separation from my beloved father, brothers, and sisters;
and inexpressively awful was the reflection on my own utter unworthiness.
I am ready to believe,
that had not best help been afforded in this time of deep distress,
I should have sunk under it.
I believe no one was aware of my sorrow,
for I felt it my duty to endeavor to be cheerful by day.
I have often wished for bedtime, that I might give vent to my feelings.
My dear sister, do not suppose I am complaining,
in telling you what my feelings have been since my indisposition;
for I do hope I am grateful in being able to feel,
that although in myself I am unworthy of the smallest of favors,
yet I am not forsaken.`"

Her health gradually declined for some months after writing the foregoing;
but she was at times favored with strong hopes of approaching bliss,
and strengthened to impart suitable counsel to her friends and relations.

At one time she remarked, that she was abundantly favored with peace,
and acknowledged that her cup overflowed with blessings: and to a friend,
who remarked that she had been preciously supported, her reply was,
"`I have indeed been most mercifully dealt with.
I have none but bodily pains.`"
Turning to one of her sisters, she said: "`I have yet one request to make;
daily retire to wait upon your God.
It has been my practice for many years, and I have found strength in so doing.
You may perhaps feel discouraged; but persevere, and you will, in the end,
find your strength and comfort increased.`"

On the morning of the 16th of the Fourth month, 1819,
she said that she hoped very soon to be in paradise, with her dear Redeemer;
but that she desired to have no will as to the time,
being willing to wait the Lord`'s time, if He saw good to detain her in suffering,
either for her own sake, or that of others.
In the course of the same day, she saw several of her friends,
and took leave of them with great composure;
and on one of them noticing her great sweetness and quietude, replied,
that if she once gave way to thinking of her bodily sufferings,
she should soon be overwhelmed.
The following day,
she was earnestly engaged in supplication on behalf of her nearest relations,
particularly her nephew, desiring that he would rather be taken out of the world,
than suffered to remain in it to dishonor the Almighty.
In the afternoon she took leave of him and her niece,
and gave them counsel suited to their ages, between six and eight years,
concluding with warm desires that they might love
and serve the Almighty all the days of their lives.

On the 20th, after being greatly tried by weakness, she was, during part of the day,
much distressed, admitting deep discouragement,
and saying to some who desired that she might be strengthened to persevere,
"`If I had any access to the throne of grace, I should hope,
but it seems denied me at present.`"

On the following day, the prospect brightened.
She spoke impressively of the solicitude she felt,
that not one of those most nearly connected with her,
might be so unwise as to neglect the important business of knowing their peace made;
that so they might be favored to join her in those realms of bliss,
into which through infinite mercy, she was about to enter.
She frequently expressed her desire to be liberated, but always with submission; saying,
she could leave all to Divine disposal.

On the morning of the 22nd of the Fourth month, 1819, the day on which she died,
she spoke sweetly on death,
and inquired whether there was any probability of her being released that day; saying,
the prospect of the pains of death did not affright her;
and earnestly supplicating that the Almighty would
be near her in the approaching trying hour.
In the afternoon, within an hour of her close,
she called one of her younger brothers to her, and said, "`My dear Henry,
it is an awful thing to die; and I desire you may so live,
that when the solemn moment arrives,
you may have nothing to contend with but the pains of the body.`"
After this she spoke no more, but gently drew her last breath, at the age of twenty,
at Ashfield near Falmouth.

[.asterism]
'''

HENRY TREGELLES.--Of this family, already so stripped,
another very promising branch was soon taken away; for,
in about two years after the decease of Catherine, Henry Tregelles,
to whom her last words were addressed, followed her.
He was a boy of great spirit;
but being early convinced of the excellency of that Divine instruction,
which is in mercy offered to each of us, he was concerned to yield obedience to it;
and a great portion of peace and comfort was his reward,
having often been known to acknowledge that he had not followed cunningly devised fables,
but living, substantial Truth.
This was proved by the patience and even cheerfulness, with which he was endued,
during a painful illness, attributing all to the mercy of God in Christ Jesus.

He spent about two years from home, the last of which was at Colchester,
as an apprentice, where the solidity of his deportment was observable,
and where he was much beloved among Friends,
his conduct being such as to render him truly an example to others.
But decided symptoms of consumption appearing, he was removed home, in the Fourth month,
1821.

In the course of his illness, as well as before,
he appeared to be very sensible of the privileges enjoyed by the members of our Society,
as they keep their places in the Truth.
He was particularly impressed with the importance
of a diligent attendance of meetings for divine worship:
and enforced the advice which he gave on that subject by going himself,
when in a very weak state; which, he said, proved strengthening to his mind.
He said but little respecting his religious feelings,
except sometimes in allusion to the mercy which had made
him sensible of the insignificance of everything,
in comparison with the love of his Heavenly Father;
a conviction which had induced a willingness to resign himself
to be formed according to his good pleasure.

Some of his friends had entertained the pleasing hope that he might be
spared for usefulness in that society to which he was so strongly attached;
but Infinite Wisdom saw fit to take him from the temptations of time,
at the age of sixteen years and a half; thus cutting short the work in righteousness,
and leaving a bright example to the youth of one who could say, from experience,
"`Godliness is profitable unto all things, having promise of the life that now is,
and of that which is to come.`"
Among other sources of virtuous enjoyment,
the friendships which he had formed were productive of much solid satisfaction:
and many were the testimonies, borne by persons of mature years,
to the value of his society, which, although permitted for so short a time,
had left a sweet impression on their minds.

In the latter part of his illness, he was particularly desirous of great quietude,
that there might be nothing to distract his attention from the
Lord Jesus from Him on whom he was enabled fully to cast himself,
as having nothing, and yet possessing all things in Him.
And in this state of deep stillness, he passed gently away,
on the 23rd of the Eighth month, 1821.

[.asterism]
'''

MARY TREGELLES, fourth daughter of Samuel and Rebecca Tregelles,
was born on the 1st of the Eighth month, 1795.

For several months previous to her death, she had not enjoyed robust health;
but after an attack of fever, in the spring of 1826,
consumptive symptoms became so increasingly apparent,
that alarm for the result was soon excited.
She did, however, appear in some degree to recover;
but disease was too deeply seated to be removed,
and the whole of the following winter she was confined to one room.

In the Second month, 1827, she tried change of air,
which recruited her strength so much that her friends flattered
themselves with the hope of seeing her entirely restored to health.
But this hope proved delusive, and again they witnessed a decline of her bodily powers,
and such a return of unfavorable symptoms,
that short excursions on the sea were recommended,
as the means most likely to benefit her.

In the Fifth month she tried a voyage to Wales, where she principally passed the summer,
and did not return till the Tenth month; when,
perceiving that the means resorted to had failed to produce the desired effect,
she became much more alive to her critical state.

Her passage home was tempestuous, but her mind was kept in great quietness.
Often afterwards, she spoke of this time with feelings of much gratitude; observing,
in allusion to this, and other proofs of the providential care which was over her,
that the words, "`Be careful for nothing;
but in everything give thanks,`" seemed very applicable to her.
One evening, soon after her return, when one of her sisters,
on taking leave of her for the night, remarking her suffering countenance, she told her,
that she had felt extremely anxious, from the appearance of a new symptom of disease;
that it seemed as if she was only just awake to the reality of life;
that she had been living many years in the world,
so differently from what she ought to have done;
that she had slighted the many advantages that had been offered her,
and had chosen her own path: this was said with much feeling.
Her sister endeavored to encourage her still to trust in
that Power which had sustained her in many seasons of trial;
and to believe, that although she was cast down, she was not forsaken.

Once, when in a state of great weakness, she said,
that she felt her situation to be very awful;
that she was daily sensible of an increase of disease,
but was so entirely unfit for the change that awaited her,
that she could not be otherwise than dismayed: such purity being requisite,
before we could be admitted into the heavenly kingdom.
She was reminded, that it is when under such a sense of poverty and nothingness,
that we feel the need of the great mediatorial Sacrifice.
Still, in the midst of her anguish, she was permitted to derive a little hope,
from the assurance that "`God is love;`" and those who witnessed
and measurably partook of the conflicts of her soul,
were enabled to believe, that one in whose heart the love of God was so prevalent,
could not eventually be cast out.

On the evening of the 3rd of the Twelfth month,
she asked one of her sisters to sit by her; when, in a very feeling manner,
she described some of the conflicts through which she had
had to pass during tile interval of their separation.
She said,
that some symptoms indicative of more disease in the lungs than she had been aware of,
had greatly afflicted her;
that she felt as if she could have rejoiced in the prospect of annihilation;
and that it would not be possible to give an idea of her sufferings: adding,
"`Throughout one week, I seemed in the depth of despair; my sins,
I was going to say all of them, were placed before me, but I believe not yet all of them;
yet I trust that none may be permitted to be covered,
but that everything may be brought to judgment.
Among other things,
it greatly distressed me to think of the irritability
which I have often shown towards you.`"

Here her sister interrupted her by saying, that she was scarcely sensible of it;
and if sometimes there was an appearance of irritability,
it was attributable to the nature of her disease.
She would not, however, admit the excuse.
She afterwards spoke of the constant kind attentions of her friends and relations;
adding, "`And how did I repay their love and kindness!
On my return home,
I wished to make my sisters promise that I should go nowhere and see no person:
this was pride and ingratitude.
But after the time to which I allude, I can hardly describe the change;
every one seemed to claim my love, and all the creation appeared lovely;
and should I now return to health, I trust this time may never be forgotten.`"
She then embraced her sister with much warmth of affection,
saying she hoped she could forgive every unkind word,
and every appearance of indifference.

During some part of her illness, she could scarcely bear reading or conversation,
lest it should divert her attention from the one
all-important subject which occupied her mind.
She did indeed pass through deep waters;
but she could occasionally acknowledge that she was not overwhelmed by the billows.
About this time, she referred to a circumstance which occurred some years before,
when she was addressed by a pious poor woman,
to whom a remarkable sense of her state appeared to be given.
She told her,
that a day would come when this language would be verified in her experience:
"`I have heard of you by the hearing of the ear; but now mine eye sees You:
wherefore I abhor myself, and repent in dust and ashes.`"
This was inexplicable to her,
as she considered that she had more than heard with the ear,
and had understood with more than the natural understanding; and it was not till now,
when the secret of her heart was, as it were, laid open before her,
that the full force of this passage was explained to her.

On Sixth-day morning, the 28th of the Twelfth month, 1827,
her family perceived that her life was drawing to a close.
She appeared about midnight to fall into a heavy slumber,
which they thought would terminate only with her earthly existence.
Very earnestly had they desired, that,
if consistent with the designs of that Wisdom which is unerring,
it might be permitted them to hear from herself, that her doubts and fears were removed.
Within about an hour of her departure, she appeared quite sensible, spoke very clearly,
and inquired whether she was not dying.
One of her sisters told her that the change appeared to be very near,
and inquired whether all were peace within; to which she clearly answered,
"`It is all peace.
I am ready to go, quite ready; do not hold me.`"
She then inquired for her father, and for other members of the family.
She recognized them all.
Very soon she said, "`I sought the Lord.`"
One who was near, answered, "`And He has heard you.`"
She added, "`Yes, and delivered me from all my fears.
Oh! praise the Lord.`"

As she gradually, for a few minutes, breathed more gently, she was heard to say,
"`It is nearly over: it is a very pleasant prospect, and very near;
and almost in the moment of death,
those around her distinctly heard the sound of "`Hallelujah! hallelujah!`"

These were her last words;
and about eight o`'clock her purified spirit was released from its very suffering tenement,
and, we may humbly trust, entered into the realms of light;
there to know the fruition of that bliss of which
so merciful a foretaste had been afforded her:
it being literally verified in her experience, that,
although "`weeping may endure for a night, yet joy comes in the morning.`"

[.asterism]
'''

WILLIAM SOWERBY, late of Wensleydale, in the north of Yorkshire,
joined our Society by convincement in early life,
and first appeared as a minister when about thirty-one years of age.

Soon after the opening of the school at Aekworth, in the year 1799,
from an apprehension of duty, he went to live in the family there as a servant.
He was a good example of fidelity and industry in that station;
and was concerned frequently to labor as a minister,
with the various branches of that large establishment,
under an awful sense of the nature of the engagement.

After a residence at that institution of about twenty years,
he returned into the compass of Richmond monthly meeting;
but though he felt the difficulties of traveling, occasioned by advancing years,
he paid several visits at Ackworth, where his religious labors were cordially received.
On some of these occasions,
he appeared to be singularly favored in the exercise of his gift in the ministry;
and he was esteemed there, and by his friends generally,
as a preacher of righteousness in life and conduct, as well as in word and doctrine.

He was a diligent attender of our religious meetings,
in which his deportment was grave and reverent.
About two weeks before his death, in his last public testimony he said,
in much brokenness of spirit, that he came to the meeting with so much difficulty, that,
on the way, he thought he must be under the necessity of giving up attending;
but he had found that reward, refreshment, and renewal of strength,
which he had coveted for those who were then, and perhaps too often,
absent from these opportunities;
desiring that they could be made sensible of the
great loss which they sustained in their best interests,
by allowing the chaining things of this life to prevent
them from assembling with their brethren,
and participating in that good, of which the patient,
sincere travailer might be permitted to partake.

He was seized with an apoplectic fit, a few days afterwards,
and died at the age of eighty-four, in the Second month, 1816.

[.asterism]
'''

JOHN BATEMAN was born at Bunhill, in Norfolk, in the year 1732,
of parents who were members of our religious Society;
and was brought up under the care of his grandfather.
He was early sensible of the power of divine grace, and when about seven years old,
was remarkably contrited in spirit, at a meeting for worship held in silence.
The precious remembrance of this extension of divine regard,
and of the religious example and precepts of his grandfather,
often proved instructive to him in the succeeding stages of life.
He served his apprenticeship at Wymondham, to a Friend, who endeavored,
by proper restriction and wholesome counsel,
to preserve him from those evils to which the young are particularly exposed:
a religious care which, he frequently observed, had been of lasting benefit to him.

When about twenty-six years of age, he settled at Chatteris, in the Isle of Ely.
In this allotment he had many secret exercises of soul to pass through;
but as he was concerned patiently to wait for the quickening influence of divine love,
He who knew his integrity became his shield and exceeding great reward,
and enabled him to walk in his holy fear.
He was for many years an elder in our Society,
and filled that station acceptably to his friends.
In the discharge of this duty, he believed it to be right for him, at times,
to leave his outward concerns,
and to perform the useful service of traveling as a companion to some of his friends,
who, in the exercise of their gifts in the ministry,
were concerned to visit their brethren.

In the more private walks of life, and in his daily interaction with his neighbors,
it was his pious concern to live as becomes the disciple of Christ;
and hence he gained the love and esteem of those around him.
"`For nearly fifty years that I have known him as an inhabitant
of Chatteris,`" says one of his intimate friends,
"`I always believed him to be a worthy and respectable man;
one concerning whom I am inclined to think might
be adopted the descriptive exhortation of the apostle,
'`not slothful in business, fervent in spirit, serving the Lord.`'
I have seldom had an opportunity of observing an individual who appeared to me to endeavor,
with more success, to keep things in their right places, by carrying on, from day to day,
the very disproportionate concerns of time and eternity, with a,
due regard to their distinct, yet relative importance;
which is not one of the least difficult lessons in the Christian course,
particularly to a man with a family, for whose support considerable exertion was,
I apprehend, for many years necessary.`"

In his declining years,
this upright-hearted friend believed himself called
upon to speak as a minister of the gospel.
He did not travel much in that character;
but was more peculiarly useful in his own meeting,
to many whose attention was turned to our religious Society,
and who were seeking the way to the kingdom of heaven,
to whom he was frequently made an instrument of good.
His ministry, having the savor of life, reached the witness in others,
to the consolation and encouragement of the humble
traveller towards the heavenly Canaan.

He was a very diligent reader of the Holy Scriptures, which,
through the blessing of the Most High,
were a means of conveying deep religious instruction to his mind,
even to the latest period of his life.
And as the close of it approached, he appeared to be much redeemed from the world,
and enlarged in Christian benevolence,
with an increasing desire to "`do good and to communicate,`"
as a sacrifice well-pleasing in the divine sight.

At a meeting of ministers and elders, held in the Ninth month, 1815,
the last which he was able to attend, he said that he was free to remark,
he was thankful in feeling a comfortable release from further service;
that he had only quietly to wait the appointed time, and he hoped,
through his gracious Redeemer, to be admitted into rest.
He was confined to his chamber and an adjoining apartment nearly six months,
in great bodily weakness; but his mind was preserved calm and serene;
and he observed at one time to a friend,
"`I feel very little or no dismay at the prospect before me;
but have a comfortable hope I may be received in mercy.`"
And not long before his death, he said, "`It was given him that day to believe,
that his day`'s work was done, and reconciliation mercifully vouchsafed.`"
He quietly drew his last breath, on the 24th of the Third month, 1816,
in the eighty-fourth year of his age.

[.asterism]
'''

ANN DYMOND was born in the Second month, 1768.
She was the eldest daughter of George and Ann Dymond, who were many years elders,
in good esteem, of the particular meeting of Exeter.
They were conscientiously concerned to bring up their children
in a manner consistent with our Christian profession;
manifesting, by the tenor of their lives, and by their counsel,
that they were much more solicitous that their tender charge
should obtain an inheritance in the Truth as it is in Jesus,
than that they might acquire the perishable riches of this world.

Ann Dymond was early favored with the visitations of divine love;
and she thus instructively describes the state of her mind at that period of life.
"`My beloved parents were often concerned to advise and reprove me,
and to give me good counsel; which,
although to appearance it had little or no effect at the time,
has undoubtedly been blessed to me;
for which I now desire to be humbly thankful to the great Dispenser of all good.
His witness, placed in the secret of my heart, even in these my very young years,
was often striving with me, so that, at seasons,
I was made sincerely desirous of altering my course;
but as often the enemy prevailed by dissuading me.
I can remember many a hard struggle in my tender mind,
even when I scarcely knew what it meant.
Thus did my heavenly Parent condescend to visit me by the in-shinings of his good Spirit,
although I knew him not.
Oh, wonderful condescension, indeed!
My soul now bows in reverent gratitude for these his unmerited favors.

For a time she resisted these heavenly calls, and gave way to a levity of disposition,
which opposed her entering into that narrow path,
which in mercy had been clearly opened to her view, as the only one that led to peace.
But it pleased the Almighty still to follow her with his reproofs.
There was a long and severe conflict between the convictions of divine grace,
and the strong propensities of the natural will; yet it was joyfully evident,
to some who felt an interest in her religious welfare,
that the pure principle of light and life was gradually
rising into dominion in her soul.

Thus she was prepared for the important work of the ministry,
her first appearance in which service was about the twenty-fifth year of her age; and as,
from time to time, she submitted to the humbling power of the cross of Christ,
she became an able and acceptable minister of the gospel.
She was, at different times,
engaged to visit the meetings of her friends at a distance from home,
and also to appoint them for those of other religious societies.

Though the chief concern of our departed friend, for others, was,
that through the discoveries of divine grace, inwardly manifested,
and a full submission to its sanctifying operations,
they might be turned from darkness to light, and from the power of Satan unto God,
yet she deeply felt for those who were struggling with outward trials.

She frequently visited the abodes of poverty and disease:
and finding her limited means inadequate to the relief which she thought needful,
was earnest and successful in pleading the cause of the afflicted,
with her more affluent friends and neighbors.

It was her disposition, as much as possible,
to conceal from others the religious exercises which she passed through.
She also felt,
that though she had been enabled by the power of the Lord to yield herself to his service,
constant watchfulness and frequent self-examination were needful.
In times of solemn retirement before Him, it appears from her own memorandums,
she was often enabled to pour out her soul in fervent supplication,
and to pray for the continuance of his help,
and for preservation from the snares of the enemy.

Her last public religious labors were in meetings which
she appointed in some villages adjoining to Exeter,
and in that, her native city, to which the inhabitants were successively invited.
In this arduous undertaking,
it appeared to be her sincere desire to be preserved
from having any confidence in the flesh,
and to depend alone on holy help.
This was graciously afforded from time to time;
so that she was enabled to advocate the great truths of the Christian religion,
and also the rectitude of those principles by which we, as a religious Society,
are distinguished.

In the Sixth month of the year 1816, she informed her friends of an apprehension of duty,
which she had for several years felt, to visit Friends in some of the eastern counties.
But it pleased Him, whose wisdom is unsearchable, to accept the resignation of her will.
On the 28th of the Sixth month, a fit, supposed to be apoplectic,
similar to a slighter attack about ten days previously,
put a sudden period to her existence; and thus she was, as in a moment of time,
released from further conflict, and from further service in the militant church;
and permitted, as we have good ground to believe,
to join the church triumphant in heaven.

"`Be also ready, for in such an hour as you think not the Son of Man comes.`"

[.asterism]
'''

RICHARD REYNOLDS was the son of Richard and Jane Reynolds,
and was a native of the city of Bristol.
He was for several years in the school of Thomas Bennet, at Pickwick in Wiltshire,
between whom, and his scholar, an intimacy subsisted long afterwards,
founded on that esteem and confidence which the conscientious
conduct of the master tended to excite,
and which it is so desirable to cultivate in the education of the young.
At the age of fourteen he was placed as an apprentice to William Fry,
a resident in his native city, and approved minister in our Society.

From early life he appears to have been favored with serious impressions,
and with a sense of the importance of living in the fear of God,
through the help of his blessed Spirit.
Thus was he, in degree, prepared to encounter many of those temptations, to which,
in youth, an affectionate, lively, ardent disposition is often exposed.
He had not many literary advantages in his education;
but afterwards obtained much valuable knowledge,
by an extensive and careful reading of the best English authors.
His mind was also improved and elevated by reflecting upon the varied works of the Creator,
and contemplating the beauty and simplicity of natural scenery,
on which he was accustomed to dwell with animation and delight.

In the year 1757, he married Hannah, the daughter of Abraham Darby,
of Coalbrook-dale in Shropshire, and settled at Ketley, in that neighborhood.
She was distinguished for her humility and piety;
and the similarity of her taste and religious views,
afforded a bright promise of domestic happiness.
But He who does all things in perfect wisdom,
saw fit that this happiness should be but of short duration; for, within five years,
this endeared companion was taken from her husband, and he was left with two children,
a son and a daughter.
Her death was sudden and unexpected, and was very acutely felt.

Richard Reynolds spent the greater part of his life in Shropshire.
He was for many years actively engaged as a partner,
in some extensive iron-works at Ketley, and in its neigbourhood,
as well as in some collieries and iron-mines connected with the works.
He was a man of great order and integrity in business; but possessing a generous heart,
being alive to what affected the interests of his fellow-men,
and having been early permitted to feel the great importance of a religious life,
he did not pursue these concerns with a mind engrossed
in the accumulation of earthly riches.
He entered, with much judgment,
into measures calculated to promote the benefit of the community
in a civil and commercial point of view;
and his sentiments were respectfully listened to
and considered by men of power and influence.
On several occasions of general distress among the poor,
he came forward to solicit the wealthy to unite for their relief,
and himself contributed largely to the funds raised for that purpose.
When the cruelties of the slave-trade were first
brought under public notice in this country,
forty years ago, he was among the foremost to exert himself for its total abolition;
and his lively interest in the termination of this traffic, and of slavery itself,
was continued until the close of a long life.

In the year 1789, having long wished to retire from business,
and be left more at liberty to prepare for eternity,
he resigned his property in the iron-works to two of his sons,
(having married again,) and removed to Coalbrook-dale.

A few days after the accomplishment of this important object,
he thus wrote to one of his friends: "`The first religious meeting I attended,
after quitting the trade, though small and silent, as ours generally are,
was a season of comfort and refreshment to me; and earnest were my desires,
that it might not only be a time of renewal of strength, but of renewal of covenant also;
that now I was, in one sense of the word, become more than before, my own free man,
I might be, more than ever I have been, a servant of Christ, of his church,
and of his people.`"

He had long been an active and useful member of our religious Society, advocating,
with Christian courtesy and firmness,
those testimonies to which he was conscientiously attached;
and as he was a true believer in the immediate guidance of the Lord`'s Spirit,
to those who wait for his holy aid,
and was fully convinced of the necessity of the work of regeneration,
and a daily bearing of the cross of Christ, he endeavored,
through watchfulness unto prayer, to walk consistently with so high a profession.
He was, for many years, acceptably in the station of an elder,
and diligent in taking his part in the discipline of the church.
And his residence near the borders of North Wales,
where the members of our Society were few in number, widely separated,
and many of them in low circumstances, afforded him frequent opportunities,
of which he availed himself, to render them important assistance,
in the various trials and difficulties incident to their situation.
But his kindness was far from being confined to them.

By diligently availing himself of the gift of the grace of God, bestowed upon him,
our dear departed friend was enabled to withstand his easily besetting sins;
and was strengthened to keep in subjection those dispositions,
which might have been cherished by the testimonies of flattering approbation,
received from many with whom his knowledge, exertions, and wealth led to some interaction.
His mind, naturally quick and sensitive, and alive to injury or injustice, was,
by the same gracious Power,
brought under the regulating influence of Christian love and meekness.
But this victory was not obtained without many painful mental conflicts; and,
according to his own testimony,
no one knew the poignancy of feeling which was experienced on some of these occasions.

The parental care and tenderness towards his beloved children,
which especially marked his character, even when engaged in the busy scenes of life,
are instructively shown in the two following extracts from his letters.

[.embedded-content-document.letter]
--

1776.-- Let not, my dear, the example of others, who may be ashamed of the cross,
and of the plainness and simplicity which we possess, influence your conduct;
nor the levity of heart incident to youth,
prevent your seriously and frequently reflecting
on the shortness and uncertainty of this life,
and the continuance of the next,
as well as on the infinity of the consequences of our present conduct.
We are advised to pass the time of our sojourning here in fear:
how different is the conduct of the world!
It ridicules, or despises, that fear in which are true safety and real wisdom.
But let us be rather the companions of the despised
followers of a despised and crucified Savior,
in meekness and lowliness of mind, than grieve them, and injure our own souls,
by conforming to the world and its fashions and practices.

1778.--Twelfth month.
The most earnest wish of my heart for my dear, as for myself, is, that by a constant,
earnest attention, and faithful obedience to the inspeaking word of divine grace, we may,
in the Lord`'s due time,
experience that change of heart which our Savior calls being born again;
but to which nature is repugnant, because it is only effected by the inward crucifixion,
or death, of the vain mind,
and manifested outwardly by a denial of the vanities and follies,
as well as of the impieties, of a wicked world.
Great would be the advantage, even in this life.
The truly happy are the truly religious, who having known, in their measure,
a death to sin, and a new birth to righteousness, love God above all;
while in a due subordination to Iim: they are more susceptible of pure impressions,
and better qualified for the endearing connections of affection and friendship,
than those whose licentious passions are not regulated
by the salutary restraints of religion.

I doubt not your admitting the truth of what I have written:
the assent of the understanding is readily obtained;
but to have the heart replenished with the holy preserving fear of the Lord does not,
at all times, depend upon the will of the individual, much less upon that of another.
There are seasons of grace,
times when the divine visitation is extended in an especial manner.
May we wait for it with more ardent breathings of soul than for every other blessing;
and by giving way to its leavening influences, experience that meekness, patience,
true charity, and self-denial, which, and than which nothing else,
will make us happy in ourselves, and a blessing to others.

I love your brother as I love you, and equally desire his happiness with yours.
Knowledge is not lacking to any of us, and oh! that obedience may not.
Give my dear love to him, and let him remember, let us all remember, God sees the heart.
If our professed desires to grow in grace are sincere, they will be heard and answered.
To the protection and preservation of the Almighty Arm,
in every season of danger and difficulty, I desire to commit you both,
with my own soul.

--

[.offset]
The subjoined extracts are introduced,
as instructively indicating that course of life and conduct which
his views of Christian purity led him to aspire after.

[.embedded-content-document.letter]
--

1777--Twelfth month, 17. You ask me how I feel myself as to the late news from America.
I do feel and sympathize with our suffering friends on that continent,
and am sorry for the effusion of blood the contest occasions;
but with respect to the political justice, or injustice,
of the pretensions of either party, I do not feel about it.
My opinion, were I capable of forming a right one, would have no influence; and,
as consistently with my profession, I can do nothing, I think it best to say nothing.
Were I a man of fighting principles, perhaps I might both say and do;
at least I should think it right to support the cause I espoused,
mediately or immediately; but as I trust I have been favored to have a sight,
if not an experience, of a state in which there can be no wars or fightings,
so I think it my duty to pity and pray for those I believe to be wrong,
and to acquiesce in every dispensation of Providence, with a steady belief,
that all things will work together for good to those who love God;
with an earnest endeavor to evince my love to Him by keeping his commandments, and,
in particular, the new commandment, to love one another.

1777.--Eleventh month, 7. I should not be just to the unmerited mercy of God,
if I did not acknowledge, with the deepest gratitude, my hope,
that through the assistance of his grace,
I have experienced a small degree of deliverance
from the sins that did most easily beset me;
yet, at the same time, I must as freely confess,
that if I had been more obedient and more watchful,
and had made use of all the assistance that had been held out to me,
I might have witnessed a much greater advancement; and that I have not,
is cause of much sorrow of heart unto me.
And oh! that it may continually operate to the quickening of my
desires and prayers for perfect redemption from the power of sin,
as well as from condemnation for past transgression.

1789.--Third month, 24. I often contrast the lively zeal,
the apparent heavenly-mindedness of some I know and love,
with my own cool or constrained devotion; the difficulty with which I restrain,
or rather attempt to restrain, my thoughts from wandering, when in public worship,
or private retirement, is painful to me.
It is the wish of my heart, that every faculty may be engaged,
may be absorbed in the devout application of my soul to Him who sees in secret; and that,
under the influence of divine assistance, I may acceptably worship,
and availingly supplicate, the adorable Object of all my hopes of happiness hereafter;
a sense of whose present forgiveness and favor can alone convert the consciousness
of former transgressions into an occasion of thankful acknowledgment of his mercy,
and an increased desire for instant and future preservation.
I believe it is a faithful saying, and worthy of all acceptation,
that Christ Jesus came into the world to save sinners;
and as confidently trust in the efficacy, as I am sensible of the need I have,
of his salvation, and am equally desirous of being delivered from the power,
as from the guilt of sin; still this appears to me, at times, more like a cool,
rational deduction from admitted premises,
than an experimental knowledge in my own particular; though I admit,
and admire it in others, more worthy.

1791.--Sixth month, 19. I am sure you will not be offended, if,
as an apology for my entertaining different sentiments on what you call '`innocent dissipations,`'
as concerts and theatrical exhibitions, I observe,
that if to withdraw a young man from the dangers of temptation is a visionary hope,
I cannot think leading him into them is advisable; or,
though intended to be the means of procuring him '`the enjoyment of life,`'
likely to effect it without a participation of its vices.

To those who call themselves Christians,
professing to believe the doctrines and follow the example of a self-denying,
a crucified Savior, a reference to what He taught, and what he practiced;
and to what his apostles after Him, inspired by his Spirit,
enforced by their writings and their conduct, must afford the most conclusive arguments;
and favorable, I think it, to my weakness in general, and at this time in particular,
that your thorough acquaintance with both, as declared in the New Testament,
makes it as little necessary for me to attempt to show the irreconcilable difference,
as the obvious contrast, between a Christian and a man of the world,
as including the spirit that influences, and the practices that distinguish them.
But the thought that occurred to my mind, when I first read your letter,
and with which I will conclude this subject, was,
whether any of those virtues to which our Savior, in his sermon on the mount,
annexed the beatitudes, were promoted by, no, were consistent with, the dissipations,
by so many of his professed disciples, considered as innocent.

1796.--Second month, 25. I may also further confess,
that considering our fallen estate,
and the momentous consequences of our present probationary existence,
with the necessity of our becoming new creatures, of our becoming new members of Christ,
through the process described by the apostle in the
fifth chapter of his Epistle to the Galatians,
I have too much reason to fear the proscribed dispositions would be more
likely to be strengthened than crucified by the incitement of the passions,
though upon imaginary subjects; the more forcibly agitated,
as the more interesting the narrative.
Nor is the incongruity of the practice, when compared with the examples recorded,
as well as the precepts enjoined in the New Testament, less obvious,
than I find the effect different after the perusal of a pathetic romance,
or the simple but pious productions of a Woolman among ourselves,
a Kempis among the Papists, or a Law among the Protestants.
And though the strong, genuine good sense of some persons may induce them,
after trying all, to prefer the things which are most excellent,
however plain the language in which they are communicated, I have been apprehensive,
that impassioned descriptions of fancied happiness or ideal woe,
related with all the advantages of elegance of style, and beauty of composition,
may have an effect on the mental taste of others,
similar to that which high-seasoned dishes have on the palate, by rendering plain food,
though most wholesome, insipid, if not disgustful.

--

In the year 1804, Richard Reynolds removed to Bristol,
to spend the remainder of his valuable life in his native city.
He had, in the course of the preceding year, been deprived, by death, of his second wife,
Rebecca, the daughter of William Gulson, of Coventry,
to whom he had been married between thirty and forty years.
She was a woman of sincere and unaffected piety: and, though living in affluence,
she was steadily concerned that her life might be one of simplicity and self-denial,
and that these Christian graces might increase and prevail
among her fellow-professors and in the world at large.
These qualities, combined with her charity and benevolence,
united to a good understanding,
rendered her a valuable companion and friend to the
individual whose life we are now reviewing.

He was, to the last,
unremittingly anxious to prove himself a good and
faithful steward of the wealth which he possessed.
He exhibited a rare example of Christian simplicity,
both in his domestic establishment and general habits.
In disposing of the riches with which he was entrusted,
he was munificent but discriminating, expending the whole of a large income, and,
in latter years, diminishing the actual sum of his property,
to alleviate the distresses of others.
He studiously endeavored to conceal his benevolence from the public eye;
so scrupulous was he in this respect,
that his accounts were kept in such a way as to prevent others from knowing
in what manner and on what objects his property was bestowed.

In his passage through life, he met with many domestic trials,
which he bore with Christian submission;
and he suffered deeply from feelings of great spiritual poverty,
in the course of his religious progress,
which tended to his purification and increased humility.
He was concerned to maintain the warfare with his soul`'s enemies;
not to rely on former experience.
Day by day he sought the Lord and his strength;
and in his declining years he was favored, under all his conflicts,
to keep hold of that faith which is as an anchor to the soul, sure and steadfast.
The following, extracts from two of his letters,
are a confirming evidence that he was strengthened
to trust in the Lord Jesus as his only hope of glory,
and to believe that he had an interest in Him.

[.embedded-content-document.letter]
--

1814--Eleventh month, 12.
This day I commence the eightieth year of my age a circumstance so awful,
that it indisposes for every other employment but the consideration of the speedy termination
of a life already so much protracted beyond the admitted natural term of human existence.
Most reasonably may I expect soon to follow those who are
gone from this state of probation and intended refinement,
from works to rewards.
And earnest are my desires, nor always faint my hopes,
that through the mercy of God in Christ Jesus, it will be to be again united, in heaven,
with those I have loved best on earth.
Not as though I had already attained a sufficient degree of refinement,
or were already perfect.
Alas! much remains to be removed, much to be acquired, and in how short a time!
If it depended on my own unassisted efforts,
or my expectation rested upon works of righteousness which I have done, or can do,
my hope would perish and my confidence fail; but I trust I may, in all humility,
though in a very limited degree, adopt the language of the apostle, and say,
'`I know in whom I have believed, '`and commit my soul to him as unto a faithful Creator,
and all-sufficient Redeemer.

1814--Eleventh month.
My dependence is truly not upon any works of righteousness that I have done, or can do;
but upon his mercy who saves us by the washing of regeneration,
and renewing of the Holy Ghost, through Jesus Christ our Savior: that,
being justified by his grace,
I shall be made an heir according to the hope of eternal life.
Though, through mercy, I am enabled, at times,
to confide that such will ultimately be my happy experience, frequent fears assault me;
the absence of all sense of good, or of the comfortable influence of divine favor,
suggests, with fearful apprehension, the possibility of my taking up a rest,
short of the rest which remains for the children of God.
But whatever sufferings it may be necessary I should endure, or deprivations sustain,
to prevent so fatal a delusion, may I be preserved from it;
and however inferior my talents, or imperfect my obedience, may I,
through the mercy of God in Christ Jesus, have hope in my death.

1816--Fifth month, 28. It is true, that in this variable state of things,
and especially as we advance towards the termination of the probationary scene,
the bitters may, at times, appear to exceed the sweets:
yet it is with thankfulness I acknowledge, that ever since we parted,
I have experienced a degree of support sufficient to prevent my
sinking below hope in seasons of apprehended desertion and weakness,
which have sometimes been so much as to deprive me
of the power of praying for the help I so much needed:
yet, in hearing the Scriptures read,
I have even at such times been enabled to apply (I hope I was not presumptuous,
if I thought I was permitted to appropriate) the gracious invitations
and promises of our blessed Savior more to my encouragement and confirmation,
than at some opportunities in times of greater bodily strength and mental energy.

--

As the diligence of this pious Christian induced
a care to leave nothing to be done on the morrow,
which could be accomplished on the day, in his outward concerns,
so in that which regarded his religious duties, and his preparation for a future state,
as the close of life drew near, nothing seemed to weigh upon his mind to communicate,
either in regard to himself or others,
and he had only patiently to wait the gradual declension of the vital powers,
trusting in the promises of the Gospel.

In the course of the summer of 1816, he paid a final visit to his son,
then residing at Ketley, and to his daughter, near Liverpool,
during which his strength obviously declined; but he accomplished the journey.
Not long after his arrival at home, he was induced,
by the anxious solicitations of his friends, to try the waters of Cheltenham,
when he thus wrote to one of his intimate friends:
"`I will not conclude without mentioning,
that throughout my illness I have not been without hope,
and which I may say with humility and thankfulness, is continued, and, I trust,
will be to the end;
but it is solely founded on the mercy of God in Christ Jesus who died for us,
in whom we have redemption through his blood, '`forgiveness of sins.`'`"

In the course of a few weeks after writing the foregoing lines,
Richard Reynolds was called to receive the reward of the righteous.
On the 10th of the Ninth month, 1816,
he was peacefully released from the vicissitudes of time, and added,
we may reverently trust, to the purified spirits of the just.
