== Chapter 5

[.chapter-synopsis]
* John Thorp
* Sarah Hustler
* Special West
* Hannah West
* Rebecca Bevan
* Sarah Hack

JOHN THORP was born at Wilmslow, in the county of Chester,
on the 5th of the Eleventh month, 1742.
He was the youngest son of Jonathan Thorp, a farmer, who left but little property.
His father dying before he was born, the charge of his maintenance and education,
with that of several other children, devolved upon his mother,
whose maternal care and affectionate solicitude,
under the trying circumstances in which she was thus placed,
he frequently mentioned with feelings of filial gratitude.
His parents were members of the church of England,
in profession with which he was educated.
He was, from very early life, sensible of the workings of the evil of his own heart,
and also of the manifestation of the divine principle of light and grace,
which showed him the evil.
He felt that this world is not the place of rest for man,
but that it is designed by Infinite Wisdom,
as a preparation for a state of uninterrupted happiness;
and that this great work can only be effected by taking up the cross to
all the corrupt desires and passions of our fallen nature.

Under these religious impressions,
he believed it to be required of him to decline the practice of singing,
in which he had taken great pleasure;
he had been a noted singer in that called the parish church of his own village.
He continued some time longer to attend that place of worship;
but being convinced that as God is a spirit,
they who worship Him must worship him in spirit and in truth,
the forms and ceremonies practiced there did not furnish
that edification and comfort which his soul longed for.
His regard, however, for, and his sense of duty to, his tenderly affectionate mother,
made the thoughts of separating from her,
in the solemn and important duty of public worship, very trying to him; though at times,
when present with her, he was so much distressed,
and felt such strong convictions that he was not in his proper place, that,
to use his own words, his knees have been ready to smite together.

In a lively remembrance of this season of early and divine visitation to his soul,
he remarked, a few days before his decease, that he had never since, for a moment,
had to doubt the certainty of those convictions which were thus, at a very early age,
so remarkably and so indelibly stamped on his mind;
and that shortly afterwards he attended a meeting of friends at Morley,
a village about two miles distant from his native place,
where he found publicly professed and advocated,
as the principles of a religious community,
doctrines consonant with the convictions which had operated so powerfully on his mind.
He added, at the time when he made these observations,
that if he were only preserved in the way of his duty to the end,
he should have cause to rejoice that his lot had been cast among them.

Continuing to attend the meetings of friends, he was, when at the age of twenty,
admitted a member of our religious Society.
Soon after he removed to London, where he resided about four years; and in 1767,
he settled at Manchester, was married not long after,
and was an inhabitant of that town the remainder of his life.

During his residence in the metropolis he lived much retired.
A relation who accompanied him from the country, and with whom he had joint lodgings,
and his eldest brother, an officer in the army, a man of talents and general knowledge,
formed, for some time, nearly the extent of his acquaintance.
With these companions, who were his superiors in information and learning,
he at times delighted to converse; but, through divine help,
he inflexibly resisted all their persuasions and entreaties to deviate,
in any one instance, from that steady and uniform religious practice of life and manners,
which he believed it to be his duty to adopt.
He occasionally accompanied them in an evening walk;
but if they gave way to any levity of conduct,
or turned aside into any tavern or place of diversion,
he immediately left them and returned to his lodgings.

This decision of character appears to have been blessed.
May it encourage others, who are exposed to similar temptations,
to adopt and persevere in the same holy resolution.
Young men who are thus circumstanced, have a claim on the kind notice of their friends;
but if they do not always receive this attention, let them remember that if,
with fervency and humility of heart, they look unto their gracious Redeemer,
he will guard them from all that is evil.

For some years after his admission into our Society,
John Thorp had to pass through much spiritual conflict;
continuing to find that there were in his heart propensities
opposed to that state of humble resignation which,
by the divine light, had been so clearly shown to him as necessary to be attained;
but through the effectual operation of the grace of God,
he was enabled to persevere in taking up his cross,
and prepared for service in the church of Christ.

He first appeared as a minister about the thirty-second year of his age.
He was reverently concerned to wait before the Lord,
in the exercise of the gift entrusted to him:
his powers of expression were strong and persuasive;
and these being sanctified by divine grace,
he was qualified affectionately to entreat others to come to that Fountain of mercy,
by which he had been often refreshed and strengthened.
But the most prominent and frequent subject of his gospel labors was,
closely recommending to all an earnest, serious,
and impartial examination into the state of their own hearts,
in order to see how their accounts stood with God;
and setting forth how great and irreparable would be the loss,
to those who unwisely neglect the opportunity afforded,
of embracing the all-sufficient means appointed for their redemption.

Being early convinced of the danger of seeking for the treasures of this world,
he was content to remain in a comparatively low station.
That he might not be unnecessarily encumbered with the cares of trade,
and that he might be more at liberty for the service of his Divine Master,
he steadily declined, though with an increasing family,
the offers that were made to him to enter more extensively into business,
and the repeated and earnest solicitations of his friends that he would accept them.
But he was favored to experience the fulfillment of the heavenly promise,
that to those who seek first the kingdom of God and his righteousness,
all things necessary shall be added.

He was much beloved; and among his more intimate friends, his natural cheerfulness,
tempered with Christian gravity,
and his deep experience and sound judgment in Divine things,
rendered him an interesting and instructive companion.

He spent much time in retirement; and it was his practice,
during a great part of his life, to take a walk, mostly alone,
in the forepart of the day, generally into the fields.
These walks, there is reason to believe,
often proved seasons of religious exercise and devotion; and some,
who have casually met him, have been struck with the solemnity of his countenance.
His reading had been extensive and various;
but the writings which he perused most frequently, next to the Holy Scriptures,
were those, by whomsoever written, which recommended religion as an individual,
experimental work; consisting in faith and obedience, not in speculative knowledge,
or in a mere profession.
Yet, notwithstanding the satisfaction this reading afforded him,
he often remarked how little all the knowledge that can be obtained,
even from the best of books,
will avail those who neglect a reverent attention
to the divine law written in their own hearts.

In the summer of 1806, he wholly declined his business, which had been that of a tailor,
having, through a blessing on his honest industry,
acquired a sufficiency for his future support.
In the course of that year he was deprived by death of his second wife, who had,
for thirty-one years, been his faithful and affectionate companion.

Having through life, while encompassed with human infirmities,
kept his eye steadily on the Captain of his salvation, he was remarkably favored,
at times, as he approached the confines of mortality, to look, in faith,
to that state of undisturbed happiness which is beyond the grave,
as the subjoined extracts, from letters to his long-loved and intimate friend,
Richard Reynolds, exhibit.

Let none, however, conclude, if the same bright prospects are not afforded to them,
that this is any mark of divine displeasure.
Infinite Kindness deals variously with his children; and, for wise and hidden purposes,
sometimes sees fit to prove even his most devoted servants,
by granting them less certain evidence of his acceptance; but to these also,
as they persevere unto the end, shall the consoling assurance be verified:
'`You shall reap, if you faint not.`'

[.embedded-content-document.letter]
--

1805.--Tenth month, 22. At seasons,
I feel a degree of consolation and Divine peace that cannot be expressed in words,
which I would not exchange for a thousand times the treasures of both the Indies;
in comparison of which I should esteem, I do esteem,
crowns and scepters as dung and dross.
And at the much more frequent seasons, when heavenly good is least sensibly felt,
(I hope I write it with humble, heartfelt gratitude,) my faith, and hope, and confidence,
are so firmly anchored on the everlasting rock, Christ Jesus,
that when the rains descend, and the winds and the storms beat, I am not greatly moved.
I know him in whom I have believed, and that he will, in mercy,
keep all those who have committed themselves to Him!

1813.--Sixth month, 10. With regard to myself, I am not destitute of hope;
for though many have been better stewards of the manifold grace of God than I have been,
I am not conscious, at any time, in my religious labors,
of having done the work of the Lord deceitfully.
Yet I might have been more diligent;
I might have watched more frequently at Wisdom`'s gate; I might have been more devoted,
and, like the holy prophet, more ready to say, '`Here am I, send me.`'
But I trust in divine mercy,
knowing`' in whom I have believed;`' and I am persuaded that He is able
to keep that which I have committed unto Him against that day.

1814.--First month, 28. With regard to myself,
I am moving on in my Christian pilgrimage in a low way; yet not destitute of hope,
that the dispensations I have, or may have to pass through,
may be graciously intended for my further refinement, of which I have gret need: so that,
in the solemn close, I may be numbered among all those, who,
through faith and patience, inherit the promises.`'
But if I should be thus happy to find acceptance with God, in the awful day of decision,
I am sure it will be the effect of his unfailing mercy in Christ Jesus;
for I have no claim from merits, to rewards.

--

He enjoyed an excellent constitution, and mostly uninterrupted health,
until the autumn of 1815, when he had a slight attack,
which assumed the appearance of a paralysis.
This, in some degree, impaired his powers of body and mind;
yet his understanding remained clear to the last,
and he continued to attend his own meeting.
He was able to walk about, and call on his friends;
and his mind was often filled with divine love.
A few days before his death, he was seized with a severe spasmodic affection;
when he manifested great composure of mind, saying,
that whichever way it might terminate, all would be well.

The evening before his decease,
he related to his family the following circumstance of his early life.
"`When a boy, about fourteen years of age, my attachment to music and singing was such,
that when walking alone in the lanes and fields, in an evening,
I frequently gratified myself by singing aloud; and indulged therein,
even after my mind became uneasy with the practice, until,
in one of my solitary evening walks, and when in the act of singing, I heard, as it were,
a voice distinctly say, '`If you will discontinue that gratification,
you shall be made partaker of a much more perfect harmony.`'`"
So powerful was the impression then produced, that, he added,
he never afterwards indulged in the practice.
In relating this short anecdote, he was, towards the latter part of it,
considerably affected, and could not suppress his tears,
which appeared as the tears of gratitude to God,
at this remembrance of his early merciful visitation.

He conversed cheerfully with his family the remainder of the evening,
and said that he thought it a great favor to be removed without much bodily suffering.
The following day, the 30th of Ninth month, 1817, while sitting in his chair,
he closed his eyes, and quietly departed.

[.asterism]
'''

SARAH HUSTLER was the daughter of John and Christiana Hustler, of Undercliff,
near Bradford, in Yorkshire; and was born there, in the Second month, 1765.
She enjoyed many privileges in early life,
from the pains that were taken to improve her mind by storing it with useful knowledge,
and from the pious endeavors that were used to train
her up in the nurture and admonition of the Lord.
But though sheltered under the paternal roof, and favored with good example and precept,
she did not escape the assaults of the enemy of man`'s happiness;
nor was she unacquainted with those propensities to evil,
incident to man in his natural and unregenerate state.

As her faculties ripened,
and she came more clearly to see the importance of faith in God,
and in the immediate teachings of his Holy Spirit,
and was concerned to practice what she knew to be right,
the care that had been bestowed upon her was blessed:
and those religious principles in which she had been educated,
became increasingly precious in her view.

She was a woman of superior mental endowments;
but it was her great concern that these should be employed in the church of Christ,
in subservience to the will of Him who had bestowed them.
Her friends who knew her best, entertained a high esteem for her worth,
and valued her services,
and in the maintenance of the discipline of our religious Society,
they considered her as possessing a clear and sound judgment.

In the exercise of a faithful friendship, she entered, with much Christian kindness,
into the inward conflicts of mind, and baptisms of spirit, of those who,
whether in their private character, or as ministers of the Gospel,
were laborers in the church: and to the young and inexperienced,
who were desirous of walking in the right way of the Lord,
she was a judicious and helpful counsellor.
A lively remembrance of the dangers incident to their critical period of life,
enabled her feelingly to enter into the circumstances of her young friends;
and as she possessed a refined and well-cultivated judgment,
and her conversation was marked by Christian kindness and affability,
her society was additionally instructive to them.

When about thirty-four years of age, she yielded,
though greatly in the cross to her natural inclination,
to an apprehension that it was her duty to speak as a minister in our meetings for worship.
Her first communications in this way, were in great simplicity and brokenness of spirit.
To adopt the language of the Friends of her own monthly meeting,
when describing her in this character, "`Her exercises were many,
and her baptisms frequent and deep: thus instructed in the mysteries of the kingdom,
she was qualified to administer suitable counsel
and admonition to the different states among us,
and at times commissioned awfully to warn the rebellious and backsliding;
and in the arduous work of paying religious visits to her friends in their families,
a service in which she was much engaged, she was often qualified,
in the authority of Truth, to divide the word aright.`"

For many years after the decease of her father,
the care of her beloved mother devolved increasingly upon her.
She was at once her friend, companion and nurse;
and evinced an ardent desire to discharge every duty
that filial tenderness could suggest.

In a memorandum, dated the 18th of the Second month, 1811, penned, as it appears,
after a time of very bitter conflict, are the following expressions:
"`There are seasons when all I ask is an ability to fulfill my duty to my Maker,
and my fellow creatures; to continue to the end my watchful, patient,
and affectionate attention to my dear parent; and to devote myself, body, soul,
and spirit, for the remainder of my days, to that work and service,
in doing or in suffering, which He who has been my Preserver, the dew of my youth,
the stay of middle age, and my support in many an hour of deep and hidden conflict,
shall be pleased to require at my hands.`"

Towards the close of the same year, in writing to some intimate friends, she remarks:
"`Let me not be thought ungrateful to the Preserver of men.
I forget not, I think,
to commemorate the mercy which has sustained in the way of affliction;
supported through many deep and hidden conflicts:
been a resting-place to my tossed spirit: as the shadow of a great rock in a weary land;
and enabled me, at seasons, not only to praise Him for mercies past, but also, I trust,
humbly to hope for more.
O! my precious friends, may we all be more willing to walk by faith, and not by sight;
and to profit by that which we have suffered; this is, of all Christian lessons,
one of the hardest to endure.
It has been a very frequent one, in my little experience, and continues to be so;
and were it not for a degree of confidence in the truth of the remark,
that steps taken in simple faith are large steps in Christian advancement,
I should be often ready to cast away the shield.
I know nothing I covet so much,
as to be able to adopt the language of David;`' My heart is not haughty,
nor my eyes lofty; neither do I exercise myself in great matters.`'
'`My soul is become as a weaned child.`'
And as to this world,
I hope I am losing my interest in every other prospect
than that of standing in o my right allotment:
whether it ever be required of me to run in the way of the Lord`'s commandments,
in a public line, again: or whether a short time only remains for me to trim the lamp,
and, through Divine aid, have it burning, when the midnight cry is heard.`"

This exercised servant of the Lord was often deeply
concerned for the spiritual welfare of our Society;
and she labored faithfully and acceptably in the work of the ministry,
in various places in this nation, during the latter years of her life:
but in the early part of the year 1814,
her mind was often secretly but strongly turned from her fellow-professors in this country,
towards many on the continent of Europe,
who had been awakened to a sense of the spiritual nature of the religion of Jesus.
In the course of the ensuing summer, in company with Elizabeth Coggeshall, of New York,
then on religious service in this country,
she visited the few professing with friends in Prussia and the south of France,
and other serious characters, whom they sought out as they passed along.
She returned to England in the Eleventh month,
with that warm and lively feeling of Christian interest for her friends,
which had been so conspicuous a trait in her character through life.

In a memorandum, made in the Seventh month, 1815, she observes:
"`I humbly trust I have been enabled to stand in dedication to the unfoldings
of duty;`" and after adverting to several services in which she had been engaged,
and reviewing her endeavors to fulfill her vows, she adds,
"`I commemorate the mercy which has hitherto kept me in heights and in depths,
so that the power of the enemy has not ultimately prevailed.
But though the cup of suffering has been largely administered;
though faith has been often ready to fail,
and many severe provings and conflicts have been my experience,
known only to the Searcher of hearts, the ability is yet, at seasons,
mercifully afforded, to bear testimony to the divine faithfulness,
in that his promise has so far been verified: '`Your life will I give unto you for a prey,
in all places where you go.`'
May patience then have its perfect work in me, and the fiery baptisms do their office,
until, in the end of days,
a capacity may be received to unite in the final surrender of the Holy Pattern,
Your will, O Father, and not mine,
be done!`' and thereby to join in the song of the redeemed, even,
'`Great and marvelous are your works, Lord God Almighty just and true are your ways,
you King of saints.`'
Amen, and amen,--says my soul.`"

In the course of the year 1816, she removed into Bradford,
and writes thus instructively of her new residence, in the Fourth month following;
"`I ought thankfully to say, that I have about me every outward means of comfort:
and having nothing left to desire, might be employed in numbering my blessings.
Nevertheless, I feel (and I am glad I can fee]) that nothing earthly,
or of earthly origin, can satisfy the needs of an immortal spirit; so that,
while my dwelling, and everything about it,
have been preparing to become all that I could wish them to be,
the habitation of the spirit has been in a land of deserts, of gins, and of snares;
and never more sensible danger has been experienced
of losing the portion of that better country,
where the voice of the oppressor of souls is not heard;
for `'they hear not the voice of the oppressor.`' None of my friends, therefore,
need have any apprehension that I am going to dwell at ease in my ceiled house;
for I know the state of my own heart, and I ask myself the question almost daily,
I would willingly leave it all for a safe passport to a better, or,
under the clothing of divine requisition, sensibly felt,
to go to any part of the heritage.
I can say of a truth, '`I have seen an end of all perfection,`' as to created good; and oh,
when the height and the depth, the length and the breadth,
the wonderful extent of the law of love, are in any degree opened to the mind,
how are earthly consolations swallowed up and lost!`"

In the Eighth month, 1817,
Sarah Hustler proposed to her friends to attend the half-year`'s meeting at Aberdeen,
and to visit the few other meetings in Scotland; and was liberated for that service.
For some time previous to this her last journey,
she had labored under much poverty of spirit; and she left home greatly discouraged,
often remembering the words of the apostle, "`Unto you it is given,
in the behalf of Christ, not only to believe on Him,
but also to suffer for his sake,`" However, she had thankfully to acknowledge, that,
through Divine help, she was enabled to perform the visit to her own peace, and,
as she humbly trusted, without bringing reproach on the cause of Truth.
On her return out of Scotland, she united with some Friends,
who had been appointed by the yearly meeting,
to visit the quarterly meeting of Cumberland,
though suffering at the time under the effects of the bodily
exertions and mental exercises she had recently sustained.
After some progress had been made in the visit, she was obliged,
from an increase of illness, entirely to rest, at the house of Willinson Ostle,
at Maryport.

She was for some time favored with great quietude,
though her bodily sufferings were occasionally very great.
These increased, and she was further tried with a deep sense of inward poverty;
her mind was afflicted and tossed, and she repeatedly observed;
"`This is indeed passing through the valley and shadow of death.`"
Yet, in this deeply-proving season, her faith in the mercy of her Redeemer,
and her hope of final acceptance, never failed.
In a message to a friend, after mentioning some other matters, she added, "`As to myself,
I am languishing into the presence of Infinite Purity,
having nothing to rest upon but the mercy of God in Christ Jesus.`"

At one time, when two young friends were sitting by her, she remarked to them,
that what she then felt was well worth their sacrificing all to obtain;
and exhorted them to yield faithful obedience to every manifestation of duty,
however despicable they might appear in the eyes of men.
Having been able to sit up a few hours in an adjoining room,
she expressed her thankfulness, and said,
that if it should please her great Master ever to call her into his service again,
she hoped the present dispensation would be a means
of fitting her to move with increased simplicity,
in the performance of his will.
At another time, addressing a near relative, she.exhorted her,
in the most tender and affectionate manner,
to submit to the restraints of that sacred Monitor in the soul,
whose influence she had been favored to feel: Oh, do not,`" she said energetically,
"`disregard this precious Teacher.
Submit your will to it: nothing short of this will bring you peace;
and what else can support you at such a time as this?`"
Adding, in substance, that the belief that she had herself endeavored to act up to it,
and to fulfill her allotted duties in life,
then raised her soul above the load of affliction under which her poor body labored,
and enabled her to wait the event with patience.

For about ten days she appeared gradually to gain strength:
but when this began to decline, she entertained little, if any expectation of recovery,
and repeatedly supplicated that the work might be cut short in righteousness.
In the course of the night of the 23rd of the Tenth month,
she lost the power of articulation;
and continued to languish in a state peculiarly distressing to those about her,
until the First-day following, when she became quite calm and collected; and,
on being asked if her mind was easy, she was enabled, very distinctly, to answer,
"`Yes;`" her countenance, at the same time,
being strikingly expressive of serenity and peace.

On the 26th of the Tenth month, 1817, at the age of fifty-two,
her soul was released from its afflicted tabernacle, prepared,
as we may reverently believe, through redeeming mercy,
to partake of the blessing which was promised to the pure in heart.

[.asterism]
'''

SPECIAL WEST was born in the Borough of Southwark, in the year 1740.
His parents professed with our Society,
and brought him up in the attendance of our religious meetings.
He lived with them until about the sixteenth year of his age,
and worked in his father`'s business, which was that of a furrier,
among unsteady persons, whose company proved a great snare to him;
and being also himself light and vain, he became very disobedient to his parents,
and left them.
The nation was at that time engaged in war, and he enlisted into the army.

About a year afterwards, with many others,
he volunteered to go on an expedition to Gaudaloupe;
but being thought too young and slender, he was refused,
which was a great disappointment to him.
In this, however,
he had afterwards to acknowledge the Protecting Arm that was extended over him: for,
in a little time, he heard that nearly all his companions were slain in battle;
he believed that only two escaped.
When reflecting on this event, he was led to view, in his rejection,
the hand of Providence, and his mind was humbled in thankfulness to God.

His next station was in the island of Jersey, where, according to his own account,
he had less liberty than he had been accustomed to, which, he said,
kept him from entanglements.
At this time he frequently felt reproofs for his misconduct:
but had not strength to withstand temptation.
Being on sentry one night, on the top of the castle, he fell asleep, which,
by military law, subjects the offender to the punishment of death.
The noise of the officer`'s approaching to inspect the guard,
awoke him in time to avoid detection:
this he considered as another instance of the interposition of merciful Providence; and,
in reflecting on his escape, his disobedience to his parents, and other sins,
were forcible, presented to his mind.
It appears to have been a very solemn time with him, and he prayed for deliverance;
this was about the eighteenth year of his age.
In making mention of this circumstance, at a later period of his life,
he spoke of it as a precious visitation of Divine goodness.
On the conclusion of the war he returned to England, and received his discharge:
he immediately sought his parents, and submitted himself to them,
asking their forgiveness, which they readily granted.

Very few particulars are known respecting Special West from this period,
until his marriage, in the year 1773, to Hannah Haggar; when he changed his residence,
and was recommended from Barking monthly meeting, to that of Hertford,
"`as at times appearing in the ministry, to the satisfaction of Friends.`"
For several years he occupied a small farm at Northaw, on the borders of Hertfordshire,
at a distance of seven or eight miles from meeting;
but he was diligent in his attendance, though encompassed with many difficulties.
He and his wife labored very hard for their support; they lived sparingly,
and were at times greatly tried with losses, on their little farm,
so that he was often ready to fear that he should be unable to pay his debts,
and that he might bring a disgrace upon the cause of Truth.
During the time of his living at Northaw, he lost, by disease,
several of his small stock of cattle;
and at one period his only remaining horse was stolen.
His worthy wife, in speaking of this trouble, has remarked:
"`When the thieves stole our horse, I said it was the enemy`'s doing,
to keep us from meeting; but I said, he shall not have his way now, so we used to walk;
but no one can tell what we suffered.`"

He was a man of great simplicity: in his dealings he was upright and punctual,
and by his consistent deportment he gained the esteem of those who knew him.
His honest industry was blessed to him; for though he did not, for a considerable time,
meet with much success,
yet his exemplary conduct attracted the notice of such as were able to help him,
and was the cause of his having, at different times, several small legacies,
which enabled him to rise above his difficulties;
and in the end he obtained a comfortable independence, for his station in life.

Our dear departed friend had very few advantages in his education:
his preaching was not in the wisdom of man, nor after the rudiments of this world;
but having been taught in the school of Christ, and, with a simple and believing heart,
received the truth as it is in Jesus, he became an able minister of his blessed Gospel.
He was well acquainted with the Holy Scriptures; and was often strengthened,
in a clear and powerful manner, to enlarge upon them,
to the spiritual instruction of his hearers.
He was plain and unassuming in his manners,
moving with propriety in that sphere in which Providence had placed him;
acting as one who was seeking to serve the Lord, and not to obtain the favor of men.

In the latter years of his life, he resided within three miles of Hertford;
and though laboring under great bodily infirmities,
continued diligent in the attendance of religious meetings,
even in very unfavorable weather, frequently appearing in public testimony,
to the comfort and edification of his friends.

During his last illness, which was rather short, he was remarkably patient.
On being asked how he felt in his mind, he replied, "`I do not abound:
I trust in the merits of my dear Savior; all my own righteousness is as filthy rags.`"
He afterwards many times expressed the Divine consolation
which he felt in this season of conflict,
saying,
"`The great work of the soul`'s salvation must be wrought out with fear and trembling.
O, death and eternity, how awful!
I am resigned, and willing to go.`"
On one of his sons asking him if he had anything more to say to him, he replied,
"`I desire you, my dear children, to live in love, and in the fear of the Almighty,
and then He will bless you.`"
His family standing by him, he said,
"`What a blessed thing it is to pass from death to life!`" adding,
"`I have nothing to do but to die.`"
He continued in a sweet frame of spirit, and sensible to the last;
and was favored to close, in great peace, a life of much piety and usefulness,
on the 30th of the Tenth month, 1817, in the seventy-seventh year of his age.

[.asterism]
'''

HANNAH WEST survived her husband nearly three years;
she had long been afflicted with a complaint, which terminated in a dropsy of the chest.
Her sufferings were great; but she was enabled to beg for patience,
which was graciously afforded her, so that she neither murmured nor repined;
but remarked, that her Lord would not forsake her,
that she felt his arm underneath to support,
and that He would carry her through the troubles of life.
During her illness, she said; "`Oh! that I might put off this body of clay.
I have an interest in Christ,
and shall soon enjoy that treasure which I was favored to lay up in the days of my youth;
that treasure which fades not away,
which is a consolation to me at this time of my bodily affliction.
I have no fear of death; the grave will have no victory over me.`"

At another time she said, For what cause my life is lengthened, I cannot see;
unless it is to refine me from the dross and tin; and I am resigned.
I long to go to my Heavenly Father, to join the spirits of my dear husband and relations,
who are gone before me, to sing the glorious song of the redeemed.`"
And further said, "`My dear children, I think you hold me.
Do not hold me; for I have an assurance of happiness.
Pray for me, that my patience may hold out to the end; and when I am gone,
rejoice evermore.`"
She quitted this scene of conflict at the age of eighty, the 4th of the Ninth month,
1820.

[.asterism]
'''

REBECCA BEVAN, who died on the ninth of the Eleventh month, 1817,
at the age of thirty-four, was the daughter of Jasper and Anne Capper,
of Stoke Newington, from whom she received a guarded and religious education;
and there is reason to believe, that their care in this respect was blessed to her.
In very early life, her mind was favored with serious impressions; for it appears,
from some memorandums of her own, made when about eleven years of age,
that she then felt earnest desires that she might live in the fear of the Lord,
and be strengthened to overcome everything that would hinder her eternal salvation.`'
She was, in her youthful days, no stranger to close conflict of mind,
in which a sense of her own remissness was deeply felt,
and the tear of sorrow often shed, from a feeling of great unworthiness.
Being preserved in this acceptable state,
her own inclinations became much subjected to the power of Truth, and she resisted,
in great degree, those temptations to which the youthful mind is exposed:
a portion of heavenly light shone upon her path,
by which she was enabled rightly to seek, and to find Him whom her soul loved.

When about the age of twenty-one, she was united in marriage to Paul Bevan,
and became a member of Tottenham monthly meeting.
Not very long after this event,
she was humbled under an apprehension that it would be right
for her to bear public testimony to the Lord`'s goodness;
and, under this impression,
it was her earnest petition that she might clearly know the divine will concerning her,
and not seek relief from any outward source.
After some years of close inward exercise, she yielded to the divine manifestation,
and was permitted to enjoy the reward of a quiet and peaceful mind therein.

The following memorandum is descriptive of her character,
and instructively marks the self-examination which she was concerned to maintain.

1811.--Tenth month, 27. Returned home on the 16th, and the following day,
after attending the marriage of M. M. (and there, for once,
endeavoring to do in simplicity, what was required of me,
in which I found peace,) was surprised with the information, that, during my absence,
the monthly meeting had acknowledged me as a minister.
The friends appointed to inform me, did it in a tender manner;
and my first emotion on hearing it, was a desire to kneel down,
and earnestly pray for that preservation in true humility,
of which I felt more than ever the need.
But recollecting, that He to whom the prayer was offered,
can accept the sincere breathing of the heart, as well as the more public petition,
I contented myself with turning to Him in secret,
and I think felt my strength renewed by so doing.
But have I dwelt in his fear,
or in a disposition to be dedicated to his service since that time?
No: I have again let in lukewarmness and indolence, both in and out of meetings;
and I am afraid I shall never be fit to be admitted of the number of his redeemed.
The opinion of my friends, though their unity is very pleasant,
cannot alter the real state of things between my soul and its Maker; and I much fear,
that it is possible to be thought well of by our fellow-pilgrims,
and yet to be weighed in the balance and found lacking.

In the exercise of her gift,
it was her great concern that she might not move
without clear impressions of divine requiring,
nor exceed the limits which Truth sets to its openings.
Her communications were neither long nor frequent; but attended with weight and solemnity.
She possessed a considerable share of mental endowments; and, being cautious in decision,
her judgment was sound and discriminating.
She was, from early life, of a tender conscience,
and remarkable for a strict adherence to truth.
One of the principal characteristics of her mind was sincerity,
accompanied with Christian humility.
She was exemplary in the discharge of the social and relative duties of life; and,
as a mother,
it was her continued care that her offspring might
be preserved from the evils of the world,
and, by an early obedience to the teachings of the Spirit of Christ,
be enabled to bear his cross.

Having, with her husband and family, removed for a short time to London, they returned,
about the latter end of the year 1816, to Tottenham.
From this time she felt herself gradually weaning from the world;
her mind being strongly impressed with the apprehension that her
continuance here would be but of short duration.

In the Sixth month, 1817, she wrote as follows: "`Since my return to this meeting,
my state of mind has been much as of late years;
mostly attended with great lack of earnestness in spiritual things; but now and then,
for a short time, aroused to greater diligence;
and a desire has been much impressed on my mind, that if, at the close of time,
I should be favored with the least sense of acceptance, no one may, in future,
sink under discouragement;
for I think it impossible that any should feel more destitute of good,
and even of living desires after it, than I do at times feel.`"

The illness which preceded her dissolution was both protracted and severe.
In its progress she endured much excruciating pain; yet,
when relieved from the acuteness of these paroxysms, she was able to converse,
with much calmness, upon her situation and approaching end.
In the early part of her confinement, she said to one who was with her:
"`I am afraid that I am not prepared; if I was prepared, I think I could go.`"
Upon its being intimated to her,
that her patience under suffering was an evidence of her being, in a great degree,
prepared, she replied emphatically, "`But if a little is lacking!`" At one time,
when in great pain, she said:
"`I feel now as if I could trust in the mercy of the Lord in Christ Jesus:`" and,
at another time, spoke thus: "`I am sure, if there is a door open, and I,
such an imperfect creature, so full of carelessness,
so continually off the guard! can rightly go,
I can never enough wonder at the merciful kindness of the Master we profess to serve.`"
On another occasion, after expressing her comfort in the prospect of being released,
she added, "`I have no ground in myself;
it will be all of mercy that these tears will be changed into tears of joy.
I wish that all who ask about my death,
may know that I had not a rag of my own to clothe myself with; but that,
if I make a good end,
it is entirely and purely through the mercy of Him with whom we have to do.
It was many days before I could lay hold on the least degree of that;
but I hope these sufferings are graciously intended as purifications.`"

About this time, when under great bodily suffering,
as her husband was supporting her on the bed, she supplicated thus: "`O,
merciful Father! send, I beseech you, and say, It is enough.
Or, if it be your will that these sufferings be protracted for days to come,
be pleased to give the balm of patience.
And for this, my dearest earthly friend, enable him to bear this affliction,
and any future trials that may be allotted.
You know that I have often asked for him your guidance
and direction through the wilderness of this world;
but, for the present day, send us help from your sanctuary,
and strengthen us out of Zion.`"
Shortly afterwards she said;
"`The Lord has been pleased to grant me a little quiet since the morning.
It is a sign that he is near, and what can be a greater comfort.`"
And to a near relation: "`Ah, my dear, I feel for you; but what I feel for myself,
is inexpressible thankfulness that the end may be near.`"
Upon being asked how she felt, she replied emphatically,
"`Animated with the prospect of the change!`"
And in the evening of the next day she remarked,
that it seemed as if she was longing to hear praises uttered.
After this, however, she was permitted to experience seasons of deep depression,
and privation of the sensible enjoyment of good,
and expressed herself as almost destitute of inward comfort.
Yet He who had thus far preserved, did not forsake her,
and she was again enabled to look with confidence towards Him.

There being at this time no indication of the immediate approach of death,
she manifested much earnestness to be endued with patience; saying,
that it was what she stood in need of, and that nothing could be done but to pray for it,
and that the Everlasting Arm might be underneath her to the end;
and hoped that she might adopt the language,
"`All the days of my appointed time will I wait.`"
But her pain increasing, she said to her sister: "`Oh! my dear sister,
you do not know how much I suffer many ways.
Oh! when the end comes, what a glorious change it will be to me.`"
One of her medical attendants remarking that her sufferings had been great, she said:
"`They have; but if they work out that far more exceeding and eternal weight of glory,
I shall not regret them.`"
And being in much pain, she uttered this short prayer: "`O,
heavenly Father! if it please you, hasten the time; but, more than all, enable me to say,
'`Your will be done.`"`'

For the last few days of her life,
the disorder under which she had labored made more rapid advances;
yet she was preserved in great calmness of spirit; and, on the day before her death,
in the prospect of being soon released, she was heard, in a feeble voice, to say,
"`What a comfort, inexpressible!`"

Thus He who had been graciously pleased to guide her by his counsel,
in the morning of her day, and to carry forward the work of purification,
condescended to support her by his presence in the hour of suffering;
and there is cause reverently to believe, that He granted her an admission,
through our Lord and Savior Jesus Christ, into the joys of his salvation.

[.asterism]
'''

SARAH HACK was the daughter of William and Mary Fairbank, of Sheffield,
and was born there, in the year 1762.
Her parents were concerned to train her up in the nurture and admonition of the Lord,
in accordance with our self-denying profession;
and though in her youth the natural vivacity of her disposition
rendered the salutary restraints to which she was subjected,
often irksome; yet, through the humbling, refining power of the Spirit of Truth,
with which her mind was at times tenderly visited,
she was made sensible of the beneficial effects of
early learning to bear the cross of Christ;
and in succeeding periods of her life, as encouragement to others,
she acknowledged with gratitude this timely exercise of parental care and love.

In the year 1788, she quitted her paternal home,
and united with a near relation in the superintendence of a boarding-school for girls,
at Tottenham.
Her cheerful disposition and natural abilities,
were well adapted to this arduous and important undertaking.

For some years she at times endured much humiliating exercise of mind,
from a belief that it was required of her to manifest
her love and dedication to her heavenly Father,
by a public acknowledgment of his goodness and mercy.
Her feelings, at the time of the first performance of this act of duty,
so contrary to her natural inclination, are thus described:
"`I found there was a power that could give a more convincing proof than any instrument,
and my dependence was to be there alone.
He that could give voice and utterance, set before me the fruits of obedience;
and I was raised, I know not how, off my seat, and expressed what I believe was right,
feeling no condemnation for so doing, but the evidence of peace,
though not quite to that degree immediately that I expected, resulting partly, perhaps,
from my unwilling compliance,
and calling in question a power to carry me through the great and arduous work.
A quietness and calmness of mind attended me that day and the following;
but may I never forget the state of mind I was brought into afterwards:
all that was good, every consolation seemed to be withdrawn; but I trust,
in my great suffering, my confidence never entirely left me,
although I was often almost overwhelmed with grief.
But in the depth of my distress my sorrows were suddenly removed,
comfort was poured in upon my soul: I could then experimentally say,
'`O Lord! you are my rock and my refuge; -- a present help in the needful time.`'
May the recollection of these things tend to preserve me in humility,
and to strengthen me in every manifest requiring;
may it keep down all self-love and self-seeking,
the greatest impediment in every good word and work.`"

In the year 1799,
the subject of this memoir was united in marriage to James Hack of Chichester,
to whom she was a true help-meet.
In her new station,
it was her concern to impress on the minds of her husband`'s children the advantages
arising from an early acquaintance with the teachings of the Divine instructor:
and her cheerful and affectionate disposition gave her free access to their minds,
and increased her influence over them.

Her communications in the ministry, both at home, and among her friends,
whom she acceptably visited in various parts, were sound and impressive:
and they were attended with an evidence that they
flowed from the Divine source of all saving knowledge.
She possessed qualifications for usefulness in the
meetings for discipline established among women Friends;
and was willingly disposed that they should be exercised in the service of the church.
She was also concerned diligently to occupy her talents
in the various duties of domestic life,
and was often employed in searching out and relieving the poor and afflicted.

In the early part of the year 1816, she had a severe attack of illness;
but so far recovered as to be able to pay an acceptable
visit to Friends in and about London,
in the spring of that year;
and was afterwards engaged in other religious service from home,
evincing her love to Him whom she had long endeavored faithfully to serve.
Her lamp shone with peculiar brightness, and she was strengthened,
in the power of the Gospel,
to offer instructive counsel to those among whom she travelled.

Towards the close of the year, in writing to a friend, she remarks:
"`The interruptions to my health, that have occurred of late, are, I have no doubt,
mercifully intended to prepare either for a better and more enduring inheritance,
or for engaging with more dedication and perfect love in whatsoever may be called for:
in order that the work which my great and good master may, in adorable condescension,
see fit to give me to do, may be finished to his praise,
and the exaltation of his name.`"

In a letter written when her health was in some degree improved, she says:
"`To know of the welfare of my dear connections and friends,
and that they felt me near to them, was all that I dared to ask to know;
feeling it to be of unspeakable importance to have
my communion and union with the Father of mercies,
who, when under great bodily oppression, attracted me to himself,
opened the joys of a glorious immortality,
and gave me a capacity to comprehend some of the mysteries of his kingdom.
Yes, blessed be the name of my God, I was sustained by the Son of his love.
It was a there I was delighted to dwell upon, that of redemption through Christ Jesus.`"

And in another letter, penned several months afterwards,
she thus alludes to her religious feelings:
"`I hope I have not forgotten the signal support granted, the forepart of my illness;
it was marvelous to myself to be so condescended to.
The dispensation has since been somewhat changed.
I believe, had not the sustaining arm been underneath, though invisible,
and ofttimes not known to be near, my faith would have failed me.
The condescension then so eminently displayed, to one of the least worthy in the family,
has been a means of fixing my reliance on the immutable rock --the rock Christ Jesus,
my Redeemer, my Savior.`"

In the course of a long and suffering illness,
she was often favored with the sweet influence of the love of God,
and qualified to administer counsel to those who visited her; and though, at times,
her disorder was very overpowering, her mind was clothed with humility and love,
and she was favored with an unshaken belief that
a place of rest and peace was prepared for her.
She died at the age of fifty-six, on the 5th of the Third month, 1818.
