== Chapter 8

[.chapter-synopsis]
* Abigail Pim
* Elizabeth Raper
* Thomas Marsh
* Charles Parker
* Joseph Naish
* William Tuke
* James Birch
* Mary Hanbury

ABIGAIL PIM was born on the 28th of the First month, 1767, in Dublin;
but upon the removal of her parents, John and Sarah Pim, to the neighborhood of London,
she, while yet a child, was brought with them.
Her early years were marked by weakness of constitution,
to which the vigor of her mental faculties formed a striking contrast; and even then,
in the morning of life, she was religiously inclined,
giving proof of her preference for that which is "`enduring substance.`"
As she advanced towards maturity, it appears, from some of her memorandums,
that she was not without much painful conflict of soul,
under which there is reason to believe that she was enabled,
through the efficacy of Divine grace, to experience an increase of faith,
and an advancement in the Christian course.
At a further period, she apprehended herself called to the work of the ministry,
in which she came forth in the twenty-ninth year of her age; being then,
as for some time previously, and during the remainder of her life,
a member of the Peel monthly meeting, in London.

Her ministry was clear, sound, and often, in gospel authority,
instructively argumentative.
She was frequently concerned to recommend an attention
to the gentle intimations of the Spirit of Truth,
without an undue expectation of very forcible impressions; believing,
as she would in substance express,
that "`the still small voice`" in the secret of the soul,
if hearkened unto in the daily occurrences of life,
and amidst the temptations to which mankind are exposed,
would not fail to conduct in the path of safety.

Besides her services at home, she was engaged, in the exercise of her gift as a minister,
to pay several visits within the limits of her own and of adjacent quarterly meetings;
and after the decease, in 1812, of her infirm, aged mother,
to whom she had long been an affectionately attentive companion,
she also performed a religious visit to the meetings,
and in several places to the families, of Friends in Ireland.

"`In adverting to the services of this our Friend,
whose memory is dear to many among us,`" say the Friends of her own monthly.
meeting, "`we ought not to omit her labors,
jointly with those of several others of her sex, in diffusing scriptural instruction,
and awakening religious feeling,
among the female prisoners in the principal jail of the metropolis;
a work well befitting a minister of the Gospel of Him,
who came to call sinners to repentance.`"

About fifteen months before her decease,
her constitution betrayed increased symptoms of decay; and she was, during this period,
mostly confined to the house.
Her long illness, although paroxysms of pain were frequent,
was endured with exemplary resignation, accompanied not only with serenity, but,
at times, with cheerfulness of mind.
Her love to her friends had increased with advancing years;
and as the infirmities of nature had become more obvious,
the influence of Divine grace was also more conspicuous.
Her spirit, it may be truly said, was borne up above her bodily suffering;
her intellectual powers remained with unclouded brightness;
and she continued to manifest a lively interest in whatever
related to the prosperity of the cause of Truth.

Of the secret exercises of her mind,
she was not much in the practice of speaking to others;
but to an intimate friend she mentioned, a short time before her decease,
after alluding to the awfulness of death, that she had been tried with many fears,
lest she should not be sufficiently purified to meet this solemn event; but that of late,
these fears had been removed.
And two days before the close of life, she said, speaking to her brother,
"`My mind is preserved in perfect calmness.`"

She very quietly expired, on the 19th of the Twelfth month, 1821,
at her house in Spencer-street, Clerkenwell.

[.asterism]
'''
ELIZABETH RAPER, of Amersharn, in Buckinghamshire, was born in the Twelfth month, 1739.
Her parents did not make profession with Friends, but were truly estimable characters;
and,
in conformity with their earnest desires to promote the best interests of their children,
endeavored to give them such an education as might induce them
to prefer truth and virtue to every worldly consideration.
From their situation in life, however,
they had much interaction with what is commonly called polished society;
and as their daughter, in her early years, had great delight in splendor and amusements,
she was induced to spend much of her time in a manner that gave her sorrow in the retrospect.
The opportunities for gratifying her inclination for display were also increased,
from the circumstance of her frequently passing a considerable
portion of the year at places of fashionable resort,
on account of a weakly state of health; and she arrived at mature age,
satisfying or endeavoring to persuade herself, that so long as she maintained morality,
nothing farther was required of her.

But in the course of an alarming illness,
with which she was afflicted when about thirty years of age, it appears,
by her memorandums,
that her mind became very awfully impressed with the prospect of her dissolution;
which she imagined to be near at hand,
and for which she believed herself to be wholly unprepared.
In this extremity she earnestly supplicated, "`Oh,
that I may be spared to live for some better purpose than I have hitherto done!
Oh, that a little time may yet be given me, to prepare for an everlasting existence!`"
Then was clearly discovered to her the necessity of taking up the cross,
in order that she might experience the redemption which is in our Lord Jesus Christ;
and when favored to regain her usual state of health,
the remembrance of the mercies as well as the judgments of the Most High,
continued with her,
so as to make her willing to give up all things for the sake of that redemption.

The following extract from her memorandums,
will furnish the best account of the manner in which
her views were first directed towards our Society.
After describing the grounds of her dissatisfaction with
the profession of religion in which she had been educated,
she says; "`I looked repeatedly on all the denominations I knew, and in so doing,
those called Quakers were the only people.
who appeared to live near that blessed Truth which is able to make us free indeed.`'
I had once, out of mere curiosity, read Robert Barclay`'s Apology,
and could neither understand nor make anything of it; but now,
the more I read of their writings,
the more clearly I perceived their principles to
coincide with the Divine principle in my own breast.
Now I discovered how closely my own convictions corresponded
with their doctrine in every particular,
and therefore exceedingly lamented that my education
had not been in this religious Society;
where they profess not only the necessity of worshipping in spirit and in truth,
but are not ashamed.to wait in silence,
until it shall please the Lord to prepare in them an acceptable offering.
Yet this wish was altogether unattended with any idea that
such a conformity would ever be required at my hands;
and when one thing after another became too burdensome for me to bear,
and the necessity appeared of testifying against them,
if I would attain that peace my soul longed for,
even when it appeared to me to be the Divine will
that I should become obedient in this respect,
still a conformity to so singular a persuasion seemed utterly impossible;,
and I wished that any other people had possessed
the Truth in the same purity they hold it.

"`Sometimes I prayed to be made obedient in all things, even unto death; and at others,
'`I sought to avoid the name of Quaker,
which I was sensible must incur many reproaches from men,
while all other professions accord in appearance with the world.
But although the prospect before me was such as made nature shrink back at the view,
yet I did not see all the groundless conjectures, false aspersions,
and uncharitable reflections I had to meet with, from some unexpected quarters.
Oh, my soul, bless the Lord, and forget not all his benefits!
For He who tried me, and saw the way that I took, was a present help in the needful time,
when vain was the help of man.
And here I found the peace of a Christian did not
consist in being free from temptations and difficulties,
but in calmly and steadily overcoming them, through Him who overcame.`"

When she became fully convinced that it was required
of her openly to make profession with Friends,
she thought it right, before making any change in her appearance, to acquaint her father,
(who was then her surviving parent,) with what she had in view;
upon which he expressed to her his entire disapprobation and displeasure.
This, as he knew little of Friends, but from unfavorable and vague reports,
and from casual observation, was not at all to be wondered at;
but perhaps few can conceive the depth of affliction
into which it plunged the pious daughter,
who,
although she had earnestly sought for Divine assistance to prepare and
strengthen her naturally anxious and timid mind for such an event,
found the reality of incurring the displeasure of a parent,
to whom she had habitually looked up with dutiful regard and tender affection,
to be the greatest outward trial she had ever experienced.

But she was not permitted a great while to remain under the bitterness of this affliction;
for when, in conformity to apprehended duty,
she persisted in making the alterations she had contemplated, her father,
with candor and Christian charity, soon gave up his prejudices,
and tenderly expressed to her his conviction of her sincerity,
and his admiration of her consistency;
at the same time encouraging her to persevere in
what she conscientiously believed to be her duty.
In this also he was followed by others of her nearest and dearest connections.
Yet, from various circumstances,
she found that a very narrow path was marked out for her;
and she did not fail to enumerate it among the many
favors of a kind Providence towards her,
that, during her residence at her father`'s house,
which was nearly fifteen years after her joining the Society,
she was enabled so to walk as to avoid giving occasion of offense,
without shunning the cross, or compromising her religious principles.

In the year 1793, she appeared as a minister.
In her communications she did not express many words;
but they evidently proceeded from a mind well taught by the Spirit of Truth,
and from a heart filled with the love and fear of that Great Shepherd,
by whose guidance and providence she had been instructed and sustained.
She did not travel much in the ministry; but to many she proved a tender mother,
by her lively sympathy and affectionate encouragement and counsel;
ever appearing to be on the watch to contribute, to the best of her ability,
towards the temporal and eternal welfare of those among whom her lot was cast.

She was a firm and true Friend,
and there seemed to be in her mind the very substance of Divine love.
The prevalence and enduring nature of this blessed
principle were strikingly obvious in her last illness;
for although, to a very advanced age,
her mental powers had been wonderfully preserved to her,
the nature of the disorder which brought her valuable life to a close,
was such as materially to weaken htr faculties: nevertheless,
fervent piety and heavenly love were retained in their full strength, and appeared,
indeed, to shine forth with increased brightness.
In this truly desirable frame of spirit, all care and anxiety were removed from her;
for her "`soul was even as a weaned child.`"
And although, by her countenance,
it was frequently evident that she was sensible of the pains of an emaciated body,
nothing like complaint was uttered; but all was gratitude and peace.

To one of her sisters, who was her constant and affectionate attendant in her illness,
she said: "`Old age is a great blessing,
notwithstanding all the sufferings incident to it; for they are like harbingers,
to bid us prepare:`" and, in allusion to her having joined our Society, she added,
"`The fear of offending my father was a circumstance very trying to me;
but the Lord showed me a way, and from that day to this,
He has manifested himself to be my God.`"
On another occasion, she said to those about her, "`What a good thing it is to be good:
the Lord loves good people.
I love you dearly, though I do not know you.
We should love one another, and strive to do all in our power for each other.`"
Not many days before her decease, she said to one of those who waited on her,
"`I know your kind voice,
but I cannot recollect who you are;`" and on this attendant expressing sympathy for her,
in reference to her suffering state,
but saying it was out of her power to do anything to relieve her, she answered,
"`I well know where to look for help,
as my hope is surely fixed on that Rock that will never deceive me.`"
And at another time she said, "`Through the mercies of Jesus Christ,
I have a sure hope.`"

Her peaceful spirit was released from its frail tabernacle,
on the 2nd of the Third month, 1822.
She was in the eighty-third year of her age,
and had been a minister about twenty-nine years.

[.asterism]
'''
THOMAS MARSH was the son of Samuel and Mary Marsh, of Ratcliff, London.
He was taken ill the beginning of the Third month, 1821,
with a painful and lingering local disorder, which yielded neither to medical skill,
nor change of air.
In the Ninth month he went to Ipswich,
intending to spend a few weeks with a much esteemed friend.
While there, his disorder rapidly increased, and he was confined nearly five months,
mostly to his bed;
during which time his mind appeared to be gradually preparing for his solemn change,
and at times deeply impressed with the prospect of its near approach.

Being desirous of returning home, he left Ipswich the latter end of the First month,
1822; but was unable to proceed further than London.
The very great change that was apparent in him,
gave his near connections the painful apprehension
that he could not remain long with them.
The manner in which he was enabled to resign all care respecting his business,
and the patience and composure with which he bore his great bodily sufferings,
were remarkable.
It was noticed by a relation who was much with him,
from the time he came to London until his decease,
that nothing like a murmur escaped his lips;
and very frequent were his expressions of gratitude to those who attended him.

Remarking, one evening, to his parents, his increasing weakness,
and the probability of his being soon taken away, his mother said,
she hoped he was resigned, whichever way his illness might terminate.
He replied, "`Not quite so, though I have sought for it with many tears.
I have had a strong desire to live, but now it is very doubtful.
I do not see that there is any more I can do.
I have neither burnt offering nor sacrifice to make;
but I am comforted in remembering Him, of whom it is said,
He would not break the bruised reed.
Many of the gracious promises contained in the Scriptures,
are brought consolingly to my mind; but, from the nature of my disorder,
requiring so much to be done during my waking hours,
I find it difficult to get to that quietude which is so desirable.
Short prayers frequently arise, which seem all that I am capable of.`"
He several times expressed his desire for a more full assurance of acceptance with God;
and once added, If that be granted but half an hour before the close,
it will be enough.`"

About a fortnight before his death, after expressing to one of his relations,
his apprehension that he should not live through the night, he said,
he did not feel so clear an evidence as many were favored with on a dying bed;
but he thought it would be a satisfaction to his friends to know,
that if he were taken off that night, he should die in the humble but firm hope, that,
through the mercy of his Redeemer, it would be well with him.
He had been placed, he said, in a more exposed situation than many;
and he was aware that his conduct had not been so circumspect as it ought to have been;
but, during his long illness, he had been earnest in supplication for forgiveness,
and preparation for the change; and he trusted his prayers had been heard.

In the morning of the day on which he died, he remarked to a friend,
that the near prospect of death was awful, very awful.
He also requested to hear a portion of Scripture.
Parts of the fourth and fifth chapters of the second
Epistle to the Corinthians were read,
on which he made no comment, but appeared deeply affected.
In the course of the same day,
he received a visit from a minister whom he had wished to see.
He adverted to a time of religious retirement,
which had taken place at his father`'s house some years before,
when they were both present; and added, that the impression made on his mind,
by her address to him at that time, had never been effaced: and further said,
"`Although I have had many faults, both of omission and commission, to lament,
still I think I may say, that not a day has since passed,
in which I have not endeavored to make some advancement towards the kingdom.`"
It had been his frequent, if not general practice, daily to retire alone,
after reading the Scriptures in his family.

Some remarks were made on the infinite love and mercy of God; to which he replied,
"`There is but one Power for all, and on that power I firmly rely.
I have thankfully to acknowledge, that the fear of death is almost, if not altogether,
taken away; and if I have desired the prolongation of my life,
it has been only that it might be more uniformly devoted to my Creator`'s service.`"
After a solemn pause, fervent supplication was offered on his behalf;
and when the visitor was about to take her leave, he said,
"`I have no other hope than in and through my Lord and Savior Jesus Christ;
and I humbly trust, if I am now removed, it will be well with me.`"
He was at that time much exhausted, and his strength continued rapidly to decline.
The conflict was for some hours very painful; but, towards the close,
a peaceful calm was mercifully granted.
He quietly passed away, at the age of twenty-nine, in the Third month, 1822;
leaving on the minds of those who witnessed the solemn scene,
a consoling evidence that his spirit had entered the mansions of eternal rest.

[.asterism]
'''
CHARLES PARKER was born in 1748, at Hilltop, near Bentham,
a small town in the north of Yorkshire.
His parents were members of the established church of England,
and commenced the education of their son,
with a view to his being a minister in that church;
but becoming early dissatisfied with the forms of that mode of worship,
to which he had been accustomed, he relinquished the prospect,
and was placed as an apprentice with a member of our Society.
His serious turn of mind led him for a time to associate with the Methodists;
but as this did not afford him that peace which he was seeking after,
he attended the meetings of Friends.
In doing this, he was at first afraid of observation, and unwilling to be noticed.

As he was earnest in the pursuit of substantial truth,
and desirous of living in the fear of God, he was favored, from time to time,
with the influence of his Holy Spirit.
He read the Scriptures diligently, with a mind sincerely turned unto the Lord;
and found that they were gradually opened to.
him, to his spiritual instruction.
He continued for some years to be a steady attender of our religious meetings;
and was admitted as a member of Lancaster monthly meeting,
when about twenty-one years of age.

In the earlier part of the time after he joined our Society,
he had to pass through many conflicts and trials; yet,
being concerned to act with uprightness, and faithfully to discharge his duty,
he was strengthened to hold fast his confidence in God,
and steadily to keep the even tenor of his course.
For many years he was a partner in an extensive linen manufactory at Bentham.
The management of the concern principally devolved upon him;
and he was assiduous in the discharge of his duty to those employed in it,
by promoting their religious and moral welfare,
providing for the religious instruction of the children,
and seeing that they were not overworked:
an evil which is too general in establishments of this description.

After he retired from business, he often expressed the comfort which he felt,
in having been kind to his workpeople; and it afforded him great satisfaction to reflect,
that he had been careful not to oppress the poor, or bear hard upon them,
to enrich himself.
He was not a man who accumulated great wealth;
but was kindly disposed to assist those who were in limited circumstances,
both in and out of our Society;
and the fatherless and widow were peculiarly the objects of his sympathy and care.

While necessarily engaged in trade,
he was careful that this might not interfere with higher duties:
hence he was diligent in the attendance of meetings, both at home and at a distance;
and cheerfully gave up his time to labor in the service of the Society,
for the maintenance of our discipline, and for the preservation of peace and good order.
He was a man of a cool, discriminating judgment,
and often usefully engaged in the Christian office of a peace-maker.
Loving, as he did, the Society to which he had early become united,
he was deeply interested for its prosperity:
and acted the part of a kind and sympathizing, but judicious friend,
to those who in early life were desirous, in singleness of heart,
to devote themselves to the Lord, and to yield, in self-denial,
to the guidance of his Spirit.

About the year 1788, he first spoke as a minister in our religious meetings;
but for several years he was not often heard in that character.
Towards the decline of life,
his public labors in the work of the Gospel were more frequent.
His ministry was clear and firm, neither presumptuous, nor timid;
but it bespoke a mind full of belief in settled truths,
in the profession and experience of which he had long lived.
His religious labors were principally confined to Friends in the northern counties; but,
when far advanced in years,
he felt it to be his duty to pay a general visit in other parts of the nation.
In the year 1820, he proceeded on a visit to friends in Ireland,
and in the southern and western counties of England.
On returning from this journey, he remarked:
"`I have been helped and preserved in and through all, which,
with the tranquillity of mind I now feel,
demands my humble gratitude to the Author of all our mercies.
It is the Lord`'s doing, and is marvelous in my eyes.`"
And, in allusion to the service in which he had been occupied, he observes:
"`It is no small part of my religious engagement,
to invite my fellow-professors to come out of form into power; and out of profession,
into the possession of that pure and undefiled religion,
which not only consists in acts of benevolence and humanity,
such as become the meek and humble followers of our holy pattern, Christ Jesus,
but in keeping ourselves unspotted from the world.`"

In the Fourth month, 1822, he left his home, which had latterly been at Yealand,
in the north of Lancashire,
in order to attend the meetings of friends where he had not before travelled.
Towards the close of this visit he was taken ill, in a meeting appointed at his request,
at Needham-market, in Suffolk.
His illness was of short continuance, as he survived the attack only four days.
In the course of it he spoke but little; but he bore his sufferings with much calmness,
and cheerful submission to the will of the Most High.
It appeared evident, that he had apprehended his continuance here would not be long.
He remarked to a friend, a short time before he was taken ill:
"`I do not expect my days to be many: I have wished to spend them in my Master`'s service,
and this has induced me to leave a comfortable home.`"
He peacefully departed this life, at the age of seventy-four, at the house of his friend,
Samuel Alexander, at Needham, the 7th of the Seventh month, 1822.

[.asterism]
'''
JOSEPH NAISH was a native of Bourton in Somersetshire.
From childhood he appears to have been of an amiable disposition, and engaging manners;
but becoming early susceptible of religious impressions, he was happily made sensible,
that these natural endowments,
although they might obtain for him the favorable notice of his friends,
did not supersede the necessity of a deeper and a progressive work,
in order to the attainment of a conscience void of offense toward God and men.
He saw that nothing less than a submission to the
regenerating power of the Spirit of Christ,
would procure for him the evidence of Divine acceptance,
or put him in possession of that peace which passes the understanding of the natural man.

He was placed, during his youth, with a tradesman at Bath, in which city, at that time,
resided John Benwell, another young man of promising disposition.
Between him and Joseph Naish was contracted a firm religious friendship, which,
throughout their lengthened lives, was a source of mutual benefit and comfort.
They were a strength to each other in the Lord, and in that obedience of faith,
by which they became increasingly subjected to the cross of Christ; and thus,
while resident in a place of great dissipation,
they were preserved in a remarkable degree of Christian circumspection.

Soon after leaving Bath, Joseph Naish settled in business in his native village,
and resided with his aged father; his mother being deceased.
Tn early life he married one who proved to him a faithful and affectionate help-meet;
and who, by her diligence in his temporal concerns,
set him much at liberty to pursue those religious duties to which he felt himself called.
She also united with her beloved husband,
in training up their children in the nurture and admonition of the Lord,
and in promoting the spiritual welfare of the whole family.
By ruling well his own house,
he evinced an essential qualification for an elder in the church,
an office which he adorned during the last thirty-six years of his life.

In the course of a few years he removed to Congersbury,
a village at no great distance from the place of his nativity,
where he resided during his remaining days.
His property was limited, but he had a sufficiency;
and his habitation became well known as a place of Christian hospitality,
and also of repose and succor, to many sincere laborers for the prosperity of Truth.
His moderate estimate of his own endowments,
rendered him less conspicuous`' than many in the larger meetings of his brethren;
but his gifts were well known and duly appreciated,
in his more constant sphere of action.
To women Friends, called to travel in the work of the ministry,
he was particularly disposed to afford personal assistance,
by accompanying them in this arduous engagement.
On these occasions his company, and the lively exercise of his spirit,
were a strength and comfort to those with whom he was thus
united in the love and fellowship of the Gospel.
In the monthly meeting to which he belonged,
which extends over a large district in the northern parts of Somersetshire,
he was much employed in paying visits to the meetings of which it consisted,
and in calling on many of its members, in the exercise of a religious care,
and performing the duties of Christian fellowship.
On these occasions he sometimes had a companion;
a circumstance which he always preferred, in order that others might partake,
not only in those visits of brotherly love, but also of that peaceful reward,
which he often acknowledged had been bountifully bestowed
upon him for such dedication of his time.

In the course of his life, he was no stranger to those afflictive dispensations, which,
when rightly endured, are eminently conducive to the salvation of the soul.
He sustained, with pious resignation, the loss of four lovely children, by the small-pox;
and of a fifth, his eldest daughter, a promising girl of fourteen,
whose deathbed formed an impressively instructive scene,
in the school at which the event occurred.

His humility and condescension were striking;
especially towards those whom he considered as children of the Heavenly Father`'s family,
even though comparatively of small growth in grace.
His concern to fulfill the apostolic injunction, "`to warn the unruly,
to comfort the feeble-minded, to support the weak,
and to be patient towards all men,`" is held in grateful remembrance by
many who were the objects and witnesses of these his labors of love.
His conduct in meetings for discipline,
was marked by tenderness towards the feelings of his friends;
while his devotedness to the cause of righteousness,
evidently invested him with an ascendency over the minds of others,
which nothing else could confer.
In acts of general benevolence, he diligently employed the talents committed to him;
often essentially aiding his neighbors, both by his property and counsel.

It is far from being assumed,
that his soul was not wounded by the assaults of the wicked one; or that,
through the infirmity of the flesh, he did not yield to occasional unwatchfulness;
yet it may be said, that his endeavor was as uniform as that of most men,
to keep under the influence of the Lord`'s Spirit,
which will assuredly preserve from falling, all those who are subject to its teaching.
Thus, what he was, he was by the grace of God; and this grace bestowed upon him,
was not in vain.

He attended the quarterly meeting at Taunton, on the 17th of the Sixth month, 1822,
and reached home,
without any apparent interruption of that good share
of health which he had for a length of years enjoyed,
evincing much cheerfulness, united with deep introversion and solemnity.
Soon after this he was taken ill,
and in the course of a short time his situation became alarming.
Although from the first, he entertained but little expectation of recovery,
he was preserved in great composure;
frequently expressing his desire to be prepared for the event, whatever it might be.

In the course of his illness he would frequently mention the poor, and say,
that he felt much for them; that they were near his heart.
"`What a favor it is,`" he observed, on one occasion,
"`to feel the lamb-like nature to predominate over that of the bear and of the lion.`"
And on another occasion, when speaking of heaven, he observed:
"`This is the only country I feel any relish for now.
How I wish I could take you all there!
Think no evil, speak no evil, do no evil; and then, if any one speak evil of you,
it cannot harm you.
The enemy is endeavoring to entice and draw you off your guard.`"
A while after, he said to a young woman who came to see him: "`You see me a dying man;
but quite happy in the prospect of a blessed immortality,
of which I have not the least shadow of a doubt.`"
Inquiring after a minister of the church of England,
with whom he had been united in several acts of benevolence in the village,
he sent this message: "`Give my dear love to him,
and tell him to persevere in doing all the good in his power;
and he will receive the sweet reward at last, as I have done.
Tell him, I should rejoice to see him.`"
At one time, when engaged in prayer, the following words only were collected; "`Oh, Lord,
look down upon me, for I am only as a little child.`"

Nearly all the friends of the meeting to which he belonged,
visited him in the course of his illness; and he imparted to every one suitable counsel.
Indeed, his manner was so impressive,
and his mind so richly furnished with heavenly wisdom,
that few left his chamber without being deeply affected.

One morning, on his son going to his bedside, he exclaimed:
"`How abounding is the love and mercy of God towards me.`"
And at another time, with much sweetness, he remarked:
"`There is nothing to obstruct the way: all is clear, clear as the light.`"
Being informed the day of the week, he said: "`Ah! it is meeting day:
I love to go to meetings.`"
And on its being observed that he had pressed through difficulties to attend them;
"`Yes,`" he replied, "`and have been amply compensated for it:
I have had such sweet meetings; my Master has been so good to me.
Ah!
He has blessed me in basket and in store.`"
For the last few days of his life, his sufferings were at times very great;
but when intimating his desire to be released,
he would check the least appearance of impatience, saying:
"`But I wish to await the Master`'s time.`"

He finished his course, on the 17th of the Seventh month, 1822,
in his seventy-second year, full of days, and full of the hope of a blessed immortality.

[.asterism]
'''
WILLIAM TUKE.
Of the very early part of the life of William Tuke, of the city of York,
who was an aged and honorable elder in our Society,
not much that is interesting has come to the knowledge of his friends.
But it appears, that as he grew up, though he possessed a great degree of uprightness,
and was preserved in conduct from things immoral or dishonorable;
yet it was not until about the twenty-first year of his age,
that his mind was peculiarly and strongly impressed
with the supreme importance of heavenly things,
and the necessity of making them the primary objects of pursuit;
and even after these convictions, the pleasures of the world,
the desire of accumulating wealth, and of obtaining preeminence among men, gained,
for a time, the ascendency in his mind.
Divine Goodness did not, however, leave him in this state; but,
by the teachings of afflictive providences,
and the secret operation of the Spirit of Christ upon his mind,
he was awakened from a state of carnal security,
deeply humbled under a sense of his transgressions, and led to flee,
with full purpose of heart, to the appointed means of Divine Mercy and acceptance.

Although his Christian walk was far from being unchequered,
and he was often led to deplore the secret imperfections of his own heart;
yet it soon became obvious, that a great change had taken place in his views;
that he had reversed the order of his pursuits;
and that he was now seeking first the kingdom of heaven and the righteousness thereof.
The degree in which he was ever afterwards kept aloof from the spirit of the world,
though necessarily engaged in its cares for the support of a numerous family,
and the superior claim which religious considerations had upon him,
strikingly evinced the continued influence of religious principle.

As his mind gained strength by obedience to the convictions of Truth,
he was led to take a part in the discipline of our Society, and to labor,
with great zeal, for the impartial and Christian exercise of it,
in the monthly and quarterly meetings of which he was a member; in both which,
though he had many difficulties to encounter, he was instrumental in effecting much good.
He soon became more extensively useful, in this department of the Society`'s affairs;
and the strict integrity of his mind, joined to the soundness of his judgment,
eminently qualified him for service on these occasions.
He allowed no considerations of personal ease or interest to interfere
with his attendance at the quarterly meeting of which he was a member,
or at the yearly meeting held in London; where, with very few exceptions, he was found,
for upwards of fifty years,
taking an important part in the deliberations of that meeting.
In the share which he took in support of the discipline of the Society,
in its various meetings, he expressed himself with firmness,
and sometimes with earnestness; but after having fully stated his own views,
if the meeting did not concur with them, he yielded to its judgment;
and as he advanced in years, his example, of a cheerful acquiescence in these respects,
became instructively conspicuous.

This active and indefatigable laborer in the cause of religion and Christian morals,
was a man much given to hospitality.
To those who travelled in the work of the ministry, or for promoting, by other means,
the cause of truth and righteousness among men, his heart and his house were open;
and in this cheerful dedication of his time and substance, he was blessed and comforted.
He was earnestly solicitous that Friends should contribute according to their ability,
to such matters as required pecuniary aid, whether for the maintenance of our poor,
the relief of the distressed, the accommodation of the Society,
or the forwarding of benevolent objects; and was a good example himself in this respect.
A few years before his death, in encouraging his friends to liberality, he informed them,
that when his means were small, he always gave a little;
that when he had more in his power, he did more; and that he believed,
those who withheld from giving, under the idea,
that they would be liberal when they became richer, would be in danger,
when that time came, of having their hearts so shut up,
that they would then do it very sparingly, if at all.

William Tuke was warmly interested in the progress of piety and virtue;
and was grieved when he heard of the increase of vice and infidelity.
In devising and executing measures beneficial to his fellow creatures,
and especially those which concerned our Society,
he appears not only to have been judicious and persevering,
but to have derived from them a satisfaction, which overpaid all his labors.
Among the objects which gained his peculiar attention, were the promotion of schools,
the abolition of the slave-trade, and the spread of the Holy Scriptures,
both at home and abroad;
and he was particularly exertive in the establishment
and management of that excellent institution,
the Retreat, near York, for insane persons.

Though he possessed an uncommon degree of firmness of mind, and was favored to rise,
with singular fortitude, above his own troubles and afflictions,
yet he knew and felt for the imperfections, trials, and infirmities,
incident to human nature; and this sympathetic regard towards others,
joined to a religious tenderness of spirit,
often disposed him to cheer and strengthen the drooping and afflicted mind;
and his feelings of this nature were far from being diminished,
in the latter part of his life.
Notwithstanding his very advanced age, he continued, to the last,
to be a useful member of society, and a comfort to his relations and friends.

He was twice married, and survived his last wife about twenty-six years.
His family was large, and except his daughter Sarah, the wife of Robert Grubb,
and his eldest son, Henry, such of them as attained to maturity survived him.
In the endearing relations of husband and parent,
his exemplary conduct was no less conspicuous, than in the more public duties of life.

When no longer able to leave home,
he continued to be a most diligent attender of our religious meetings,
even when under great weakness of body, and the affliction of blindness:
and this practice, in which his demeanor was solid and reverential,
he continued till within a few days of the close of his life;
evincing the spirit of the Psalmist, when he exclaimed,
"`How amiable are your tabernacles, O Lord of hosts!
My soul longs, yes, even faints for the courts of the Lord:
my heart and my flesh cries out for the living God!`"

There is reason to believe, that in a good degree of this favored state of mind,
the messenger of death summoned this Christian soldier from works to rewards.
The attack which terminated his life, though rather sudden, was gentle.
He appeared to be sensible that the close was approaching;
and though he said but little on the subject,
his deportment manifested that he was waiting for that solemn event.
A few days before it took place, he gradually became weaker, and departed quietly,
without any apparent pain, on the 6th day of the Twelfth month, 1822,
in the ninetieth year of his age.

[.asterism]
'''
JAMES BIRCH was born at Dedsbury, on the borders of Lancashire, in the year 1731.
His parents sent him to the village school,
where in a short time he acquired a tolerable share of useful learning.
He appears to have delighted in many of the vain amusements of the world;
but about the twenty-third year of his age,
he became acquainted with the society of Methodists,
and yielding to the convictions of the Lord for sin,
he soon after joined in religious profession with them,
continuing among them about ten years.

Being at Stockport, he went into a meeting of Friends, which was held in silence,
and in which his mind was powerfully visited by heavenly love.
He has often been heard to say,
that such a meeting he had never experienced before nor since.
He was admitted a member of our Society, by Morley monthly meeting, in Cheshire,
in the year 1769.
Soon afterwards, from an apprehension of duty, he quitted his business of shoe-making,
and opened a boarding-school at Morley; in the management of which,
it appears to have been his great concern to make
his pupils acquainted with the Holy Scriptures,
and the writings of pious men, and by his example,
to train them in a humble dependence on the Almighty.

In the year 1798, he removed out of the north of England, and settled,
with his eldest daughter and her family in the neighborhood of Chelmsford.
He was a diligent attender of our religious meetings, even in advanced age,
and was often engaged, when thus met with his friends,
to bear testimony to Divine goodness and mercy;
having for several years acceptably appeared as a minister.

He seemed to be much redeemed from this world,
and spent his time principally in reading and meditation.
His innocent life gained him the esteem of those about him;
and as he was a lover and promoter of unity among brethren, so he was a good example,
in his care to avoid and discountenance tale-bearing,
or anything that would lessen the good esteem of his absent friends.
During several of the last years of his life, his strength and memory gradually failed;
yet he was often enabled to impart counsel in a lively manner,
to those who called upon him, evincing a mind clothed with resignation and piety.

In the Second month, 1822, when upwards of ninety years of age,
he was visited with a paralytic affection, and not long after remarked:
"`I have endeavored to serve my Maker uprightly from my youth; and, blessed be his name,
he has not forsaken me in old age.`"
On a friend`'s taking leave of him, he remarked:
"`Oh! that we may be strengthened with grace unto the end of time,
and meet together in the holy, heavenly kingdom; and this I beg, not only for myself,
but for all my dearly beloved friends.`"
He often said, "`My mind is much in heaven;
but I am fearful I am deficient in praying always, and in everything giving thanks;
for every moment ought to be spent in serving my heavenly Father.`"
A few weeks previous to his dissolution, he said: "`Now let your servant depart in peace,
for mine eyes have seen your salvation;`" and at the same time,
taking leave of some of his relations, he added,
"`I believe I am going to my grave in peace.`"
He, after this, gradually became weaker, and expired on the 12th of the Third month,
1823.

[.asterism]
'''
MARY HANBURY was the daughter of William and Mary Allen, of London;
and was born in that city, in the Ninth month, 1797,
and died on the 17th of the Fifth month, 1823.

She was favored in very early years, with the visitations of the love of God,
which she was concerned to cherish;
and through obedience to the manifestations of pure wisdom, she grew in grace,
and deepened in religious experience, beyond what is often attained so early in life.

The following memorandums, begun when she was about thirteen years old,
instructively show the tender and pious frame of mind with which she was at times favored,
from her early years.

[.embedded-content-document]
--

1811+++.+++ In my retirement this evening, I felt the fresh extendings, I think,
of heavenly regard; and I measurably experienced, that they who early seek the Lord,
shall find Him.
And earnestly have I prayed that the morning of my day may be devoted to his service;
and that, as I grow in stature, I may grow in grace.
Oh! may I always walk in the narrow way that leads to eternal life,
and be among the few that find it.
May I be faithful in the few things,
simply resigning the little that no be called for at my hands,
and faithful to every manifestation.

1811+++.+++ have completed my fourteenth year.
Childish years are now passed,
and it is time for me to think as one who has her part to act in life.
It is the day of small things with me; but it is an important day; as,
by these small things, by every-day occurrences, my character is to be fixed.
May divine assistance be granted me, without which my endeavors are vain.

1813+++.+++ A sweet, peaceful state of mind, has been my allotment this morning,
for which I desire to be made thankful; but when this is the case,
after a season of mental conflict, I am sometimes afraid of taking up my rest,
short of the true rest.
Thus, in every state, doubtings and fears attend.
At this season, however, submission to what I apprehended a little requiring,
seems to have gained me admission into the quiet habitation.

1813+++.+++ My desire this morning is, to be enabled to stand still,
that the voice of the stranger be not mistaken for the voice of the true Shepherd.
I awoke under considerable depression; there did indeed seem a thick cloud,
through which prayer could not pass,
and this because of manifold transgressions and unwatchfulness: yet,
the desire of my soul was, and now is,
to be kept in patience through every refining dispensation,
and not to be taken out of the furnace until the work is done.

--

The virtues of this amiable young woman greatly endeared
her to those who enjoyed her intimate acquaintance;
nor was the attractive influence of her pious example
confined within these comparatively narrow limits.
While circumspection and humility evinced, from very early years,
her subjection to the cross of Christ, it was encouragingly apparent,
that she had proved his yoke to be easy, and his burden light.
She was entrusted with considerable talents, which were improved by culture;
her affectionate father, for she had been deprived of her mother in her infancy,
sparing no pains nor care to provide for her a liberal, yet guarded education.
But as she was one who feared the Lord,
she was preserved from presuming upon her endowments, either natural or acquired,
and mainly solicitous to dedicate them to the service
of Him from whom she had received every blessing.
On this subject she has left the following remark:
"`At times I felt that I must count all things loss, in comparison of heavenly wisdom;
and that human acquirements would be of little support when death was in view,
if the one thing needful were neglected.`"

Her judgment was remarkably matured for her years,
and being naturally of a prudent and discreet character,
she was qualified to act the part of a friend and a counsellor to her beloved father;
soothing the path of life by her participation in his cares and sorrows.

In the twenty-second year of her age,
after having passed through many secret conflicts and baptisms,
she came forth in the ministry.
Her communications were not long, but impressive and edifying,
and delivered in great simplicity;
and in prayer her spirit was remarkably clothed with solemnity and reverence.

In the Second month, 1822, she was united in marriage to Cornelius Hanbury.
For some months previous to the illness which terminated her course,
she was often occupied in close self-examination,
and in breathing to the Lord for further purification of heart.
In looking forward to an approaching trial of her strength, she remarked,
that her mind was at ease; that,
being fully satisfied nothing would be permitted
to befall her which was not designed for her good,
she could commit herself without anxiety into the Divine hand.
During her illness, which occurred a few days after the birth of a son,
her spirits were calm and cheerful,
so as to bear up those who had the privilege of waiting on her; and her remarks,
from time to time, clearly manifested that her soul was stayed upon her God.
She expressed, very sweetly, her love for those about her;
and on being asked whether she was in any pain, she said: "`No,
not in any pain:`" and that her mind was happy and peaceful.
She often remarked, that she was very comfortable;
but the heavenly expression of her countenance exceeded words.
And those who witnessed the solemn close, seemed to be made measurably sensible,
that her purified spirit was united to that blessed company,
whose garments are washed and made white in the blood of the Lamb.
