== Chapter 9

[.chapter-synopsis]
* Mary Dudley
* Samuel Tomson
* Maria Pollard
* Mary Jackson
* John Donbavand
* Samuel Alexander

MARY DUDLEY was the daughter of Joseph and Mary Stokes:
she was a native of the city of Bristol, where she was born in the Sixth month, 1750;
and died at her own dwelling, at Peckham in Surrey, on the 24th of the Ninth month,
1823.

Her parents professed the principles of the established church of England,
and strictly attending to the ceremonies instituted by that community, introduced her,
from a child, into a regular observance of them.
Notwithstanding this,
she was allowed to enter into most of the vain amusements of the world,
to which her natural disposition strongly inclined; and being of engaging manners,
her company was much sought after,
and her temptations to gaiety were thus greatly increased.
It appears, however, by some of her memorandums,
that she was very early favored with the visitations of the love of God;
and while pursuing the gratifications of time and sense,
she was often impressed with an awfulness and fear,
which led her to desire the possession of more substantial enjoyments,
and which ultimately produced a gravity of demeanor that exposed
her to the ridicule of her less thoughtful companions.

About the twentieth year of her age,
she withdrew from those scenes of dissipation and folly to which she had been accustomed;
became dissatisfied with the forms and ceremonies in which she had been educated;
and believing that the ministry of some of the Wesleyan
Methodists had been a benefit to her,
she was induced to connect herself with that society,
and remained a member of it between two and three years; but,
at the same time continued to attend the established worship.

In writing on this subject, she makes the following observations:
"`In the several ceremonies of this, and in different meetings of the other,
I felt unsatisfied; and often, while others were engaged in attention to the preaching,
singing, etc., has my spirit, in solemn silence, communed with the Lord, my strength;
so that I scarcely knew what was passing without me,
and even felt disturbed from this inward attraction,
when obliged to draw to the spot where the outward elements were prepared for the congregation.
Oh! how did I then feel the heavenly mystery, and sweetly partake of the bread of life;
so that all forms and shadows fled away,
and became no longer of use or efficacy to a mind
feeding spiritually on the substance.`"

In this state she frequently attended the meetings of Friends,
and was so drawn into fellowship with them, that,
although she had no outward instruction,
and was not assisted in the understanding of their
religious principles by the reading of books,
it appeared she had such a clear view of their profession and peculiar testimonies,
and was so strongly convinced of their consistency with the truth,
that she believed it would be required of her to demean herself conformably thereto,
both in profession and practice.
But in submitting to this sense of duty, the opposition from her family was so great,
and the cross to her own will so heavy,
that she thought the yielding up of her natural life would have been an easier sacrifice.
She was, however, through mercy, strengthened to obey the Divine requiring,
and in the twenty-third year of her age, on the ground of settled conviction,
joined our religious Society;
about which period she felt herself constrained to speak as a minister of the Gospel,
from which her natural disposition exceedingly shrunk.
After exercising for some time, the gift with which she was entrusted,
the conflicts of her spirit were so great, that she gave way to reasonings and doubts,
on the subject of her call to the sacred office,
and thus became involved in unspeakable distress,
from which at times she could see no way to escape.

In the year 1777, she was married to Robert Dudley, of Clonmel, in Ireland;
but the society of an affectionate husband, and an increase of domestic comforts,
were insufficient to afford that peace of which her
exercised spirit felt so much the need.
She describes her situation at this time, as "`often miserable:`" concluding,
that by disobedience, she had forfeited the Divine favor,
and should never again be commissioned to proclaim her Lord`'s goodness.
But he who had called her to his service, and designed to qualify her for his work,
brought her out of these perplexities and close probations
in which her mind had been long involved,
to the comfort of many who had suffered with and for her, and to his own praise,
enabling her again to bear public testimony to his goodness.

Her constitution being naturally delicate, she was often afflicted with illness;
and it was, at times, under the pressure of much bodily suffering,
that the prospect of religious services was opened to her,
and a preparation of mind to proceed in them was experienced.
This was strikingly the case in the year 1787, when, by a complication of disease,
she was brought so low as to be thought, by those about her, not likely long to survive;
yet, in this state of bodily infirmity, her spirit was attracted to distant parts, and,
in the love of the Gospel, a people of strange language was presented to her view.
In a short time, her love and obedience were put to the closest test,
by an apprehension that it was required of her, by her gracious Lord,
to unite with her beloved friend Sarah, the wife of Robert Grubb,
in a religious visit in Holland, Germany, and France.
She had seven children, the youngest only ten weeks old,
when she was about to enter on this engagement; her health was very delicate,
and in the progress of the journey she experienced many deep conflicts.
But the holy arm of power being extended, she was enabled to accomplish the service,
to the unspeakable relief and peace of her own mind,
and to the edification of many of those whom she visited,
who were thirsting for spiritual refreshment.
Her resignation to the foregoing requiring of duty,
was the commencement of that devotedness to the cause of religion,
which so conspicuously marked the future life of this dedicated servant of the Lord.

For the succeeding twenty years, Mary Dudley was much occupied in traveling; having,
within that period, visited all the meetings, and a large proportion of the families,
of Friends in Ireland, Scotland, and Wales, and in many of the counties of England,
and the meetings of Friends in other parts of the nation; besides which,
she was engaged in most places,
in holding meetings with those of other religious denominations.
These visits, also, were often entered upon in much bodily weakness,
and under a close exercise of faith, increased by having a large family,
to whom she was most tenderly attached;
but the Lord was graciously pleased to strengthen her to perform the assigned work,
to his praise, and to enable her, in the power and love of the Gospel,
to invite others to come and partake of its renovating, blessed influence.

After the decease of her beloved husband, and two children who had arrived at maturity,
trials which deeply wounded her susceptible feelings, she removed, in the year 1810,
under an apprehension of duty, into the neighborhood of London,
and resided for the most part of the remainder of her life,
within the compass of Southwark monthly meeting.
She was a minister highly esteemed, a mother in Israel, sound in faith and doctrine;
continuing to labor diligently in gospel love, in her declining years,
for the promoting of truth and righteousness, under the pressure of much bodily weakness:
so that it may be truly said of her, that she was "`fervent in spirit,
serving the Lord.`"

After coming to reside in England, she visited, in the character of a minister,
most of the families of Friends comprised within
the quarterly meeting of London and Middlesex;
and travelled in several counties on religious service.
The youth in our Society were the objects of her peculiar and affectionate solicitude,
for whom she was, at times, concerned to appoint meetings.
She was also eminently qualified for service,
in meetings with those not in religious profession with us;
in which she frequently advocated, in a clear and convincing manner,
the doctrine of universal free grace, the divinity of our blessed Lord,
and the great benefits of that redemption which comes through Him.

Our dear departed friend experienced many deep trials,
which she bore with exemplary resignation, thus evincing her reliance on Divine support;
and hence, she could feelingly sympathize with others under affliction,
and was often enabled to hand the cup of consolation for their encouragement.
Early in the year 1823, when in a very feeble state of health,
she was enabled to accomplish a visit to the families
of friends of Devonshire-house monthly meeting;
this was her last religious engagement,
during which she frequently expressed her belief
that her day`'s work was drawing to a close.

After this she continued to attend her own meeting, when health permitted,
until about the middle of the Fourth month, when she became unwell;
and in a few days the disorder had made so rapid a progress, that danger was apprehended.
She often expressed a belief,
that nature would sink under the weight of illness with which she was oppressed; saying:
"`I do not feel able to struggle as heretofore; but I have no sight as to how it may be,
nor any wish to go, unless it be the will of Heaven.`"
Again, she said: When the doubtings and hesitations of nature have been kept down,
the Divine will has been all to me.`'
Your will be done, '`is the highest anthem ever sung, on earth or in heaven.`"
She was eminently favored with the sensible enjoyment of the Lord`'s presence,
and often testified of the support and consolation thus afforded her:
"`I have loved the cause of my Redeemer: it was to draw to Him,
and fix the mind upon Him alone,
that I have been made willing to proclaim his goodness.`"

Being much tried with pain and other distressing symptoms, she observed: "`I only fear,
that through my long-continued suffering,
I may not exemplify that which I have held up to others, the sufficiency of Divine power.
May patience have its perfect work,
whether any glimpse of the unspeakable glory be afforded or not.
Oh! if this be known, it must be glory to God in the highest,
through Him who came to procure peace on earth.
The language of the redeemed, through all eternity, will be, '`Not unto us, not unto us;
but unto your name be the praise.`'
I could say much; my heart is full; but the poor body must have rest.`"

In the course of the night of the 1st of the Fifth month,
when solemnly conversing on her precarious situation, she said,
with peculiar calmness and feeling:
"`I seem to have nothing to do but with the present moment,
no looking back with uneasiness;
but in thankful remembrance of great and unmerited mercy, whereon, I trust,
there was a building long ago.
Oh! not to doubt the foundation, is a great mercy.
Tell all, there is no other way but that of resigning all.`"
About this time she was informed of the alarming illness of a valuable minister, when,
with much tenderness of spirit, she uttered the following emphatic language:
"`Oh! our poor Society.
Lord, raise up judges, counsellors, such as are quick of understanding in your fear;
and if children are to become teachers, give them wisdom and humility.`"

On allusion being made to the diligence with which she had
occupied the time and talents committed to her trust,
she sweetly replied: "`Feebly and unworthily as they have been used,
I trust it was with a single eye to the help of others,
and the glory of the dear Redeemer; and if he forgive all the mixture,
all that has been of the creature, and mercifully receive me into rest and peace,
whether he affords those bright prospects, which in the beginning of this illness,
and often since, have been vouchsafed, or not, oh! may I never doubt,
or cast away my confidence, that He who has loved with an everlasting love,
will continue to uphold me, notwithstanding the weakness of the flesh,
and the temptations of the cruel enemy.
Oh! this enemy, he never quits his hold of poor human nature while he can assail it.`"

Early in the Eighth month, she became increasingly debilitated,
and thought it probable that her remaining strength would be soon exhausted;
and one night, after having given directions respecting her funeral,
she expressed a wish, that nothing might be done, nothing said, nor, if possible,
thought, but what would lay the creature where it ought to be,
and where she trusted it then was, prostrate at the footstool of Divine mercy.

Her situation, at this period, was very fluctuating;
but the evidence of Almighty support and consolation became increasingly manifest.
On its being observed, that as she had no clear sight of the outcome of her disorder,
a hope was induced that she might be again raised up, she quickly replied:
"`That this is my death-illness, I have not the least doubt;
but the time may be mercifully concealed from me;
if it be the Lord`'s will to save me from agonizing pain, and grant a quiet dismissal,
what a favor it will be.`"
At a time when she was sending some messages of love to some of her friends, she said:
"`I am nothing, Christ is all! my friends are dear to me:
nothing in my heart but love to all.
God is love: glory, glory, glory, be to his name, now and forever.`"

During the last three weeks of-her life,
she suffered much from the difficulty of breathing, and general bodily uneasiness;
her mind was, however, wonderfully supported, so that, to those around her,
she frequently appeared to be favored with the rich
enjoyment of perfect happiness and peace.
At one time, when tried with restlessness and pain, she said: "`' It is only the body,
it does not get within; all there is peaceful, quiet trust.`"
Again, "`'`Nothing in the way.
Ah! do not hold me; yield me up; I must go:
I could have sung a song of praise this night.`"

After a distressing night, she prayed with earnestness: "`Grant a moment`'s ease of body,
if it be your blessed will.`"
The petition appeared to be soon answered for almost immediately after,
she proceeded thus: "`Praise, praise for this calm.
Now, Lord, into your hands I commend my spirit.
Bless my children: bless your own work.`"
The attributes of her God and Savior now became almost her only theme,
and she often seemed as if scarcely an inhabitant of earth.
Her departure was observable only by gradually ceasing to breathe;
and when approaching dissolution became apparent,
the following were some of her latest expressions:
"`Grace has triumphed over nature`'s feelings; the Lord has fulfilled his promise.
He has given the victory, through Jesus Christ, to whom be glory and power,
dominion and strength, now and forever; holy, holy, holy.`"

[.asterism]
'''

SAMUEL TOMSON was the son of William Bridge Tomson, of Mepal, in Cambridgeshire.
Though he was preserved from many of the evils to which the young are exposed, yet,
about eighteen months before his death, he was greatly afflicted,
under a sense of condemnation for past sins;
and the consciousness that he had not paid proper attention to the counsel of his parents,
became to him the cause of heartfelt sorrow.
Sending for his father,
he expressed his deep concern at having acted contrary to the wishes of his parents,
desiring that he might be forgiven by them.
His mind appeared to be relieved by thus disclosing his feelings,
and he earnestly craved the forgiveness of his Heavenly Father, under strong conviction,
exclaiming: Oh! that I might witness my salvation sealed this night.`"

During the time of his confinement,
many expressions evinced that the Lord was instructing him by his Holy Spirit, and that,
in adorable condescension, the purification of the soul was going forward.
"`What a comfort,`" he remarked, on one occasion, "`it is to have such parents,
and to be so cared for.
I now perceive that many young persons are not enough
sensible of the advantages of such care.`"
Happy is it for those parents, who at such solemn periods as this,
can feel the sustaining conviction,
that they have endeavored to train their beloved charge, when in health,
in the ways of religion and virtue,
and to fix their hopes of eternal happiness on that redemption which comes by Christ.

At one time, when speaking of his bodily affliction, he said;
"`Though my sufferings are great,
what are they when compared with what our Savior endured,
when He bore the sins of mankind?`"
Being afterwards in extreme pain, he repeatedly and fervently supplicated:
"`O gracious Savior,
be pleased to relieve me;`" and his prayer appeared to be mercifully answered,
he being shortly afterwards permitted to experience considerable alleviation.
A sense of this favor long continued to be a comfort and encouragement to his mind,
and he would repeatedly say: "`How comfortable do I feel, both in body and mind!
What a favor to be so free from pain.`"
He lay awake many hours in the night, and spent much time in contemplating,
with sincere gratitude, the goodness of his Heavenly Father,
in thus vouchsafing his Divine presence,
being firmly persuaded that nothing else would have afforded him such sweet peace.

He delighted in meditation,
and in reading and reflecting upon the Holy Scriptures and other religious books;
and his apartment being near to that of his parents,
their minds were many times comforted by hearing him engaged in vocal prayer,
in the course of the night.
Requesting, one morning, that his father would come to him,
he spoke of the remarkable manner in which he had been spiritually refreshed:
"`and now,`" he said, "`I could wish to be released;
but desire patiently to wait the appointed time.`"

Some time afterwards, he remarked "`Oh! what a consolation to poor sinners,
that Jesus Christ came into the world to save the chiefest:`" adding,
"`it is well for me that I was afflicted: before I was afflicted, I went astray.`"

Inquiring where that portion of Scripture is, which says,
"`Where the wicked cease from troubling,
and the weary are at rest;`" and his question being answered, he said,
with much sweetness, "`I shall soon be there, mother.`"

In this favored state he continued, until about thirty-six hours before his departure,
when his bodily sufferings were again increased,
and from this time he was deprived of the power of speaking,
but his feelings appeared to be impressively portrayed in his countenance;
everything there indicating a foretaste of the joys which should be hereafter revealed.

He died at the age of seventeen, on the 2nd of the Fourth month, 1824.

[.asterism]
'''

MARIA POLLARD was the daughter of John and Elizabeth Batger, of London,
and was born in the Twelfth month, 1787.
In a short account of her early life, which, during her last illness,
she believed it right to dictate to her husband, she says:
"`I was very early impressed with the fear of the Lord,
and between the age of twelve and thirteen was remarkably
visited with the day-spring from on high.`"
About this time, when at school, her mind was often`" drawn into retirement,
and she sometimes thought it right to express a few
words of Christian counsel to her companions.
In doing this, she acknowledges being as sensible of the Divine commission,
and of the evidence of its being accepted,
as of some services of a more public nature in after life.
At this tender age, she was under much religious exercise;
an impression being powerfully made on her mind,
that it would be required of her publicly to advocate the cause of Truth.

In the narrative already alluded to, she remarks: "`About the age of nineteen,
after passing through many provings,
it seemed clearly revealed to me that the time was come for the surrender;
but if my natural life might have been accepted,
I believe I could willingly have made the sacrifice.
I went to meeting time after time, and was often brought to a state of trembling;
but allowed the reasoner to come in, who persuaded me I was so little and low,
and of so little account,
it was not likely that my friends would receive any thing from me in that way.
Still the Lord continued to plead with me, and, in adorable mercy,
He left me not to myself, but dealt very kindly with me.`"

In the twenty-third year of her age, she came forth as a minister, and she observes,
on first yielding to this manifested duty:
"`Oh! the inexpressible peace that was my portion for this act of obedience:
notwithstanding this,
how did nature shrink at the prospect of further dedication in this line;
how often was the language of my heart, '`Send by whom you will send; but not by me.`'
And oh! the conflict which I endured; for though I knew it to be required of me,
I did not yield until I had suffered further for disobedience; but the Lord,
who chooses obedience rather than sacrifice,
gave me clearly to see this was the way of acceptance.`"

In the year 1813, she was married to Joseph Lamb, of Reading,
who was removed from her by death in about four years.
During her residence there,
which was much to the comfort and satisfaction of Friends of that meeting,
the following memorandum was written by her, after an illness:
"`I desire to feel sufficiently grateful to my gracious Benefactor, who,
I can thankfully acknowledge, has been with me all my life long, to the present day;
has sustained me by his never-failing arm of power through many deep trials;
and even in this illness has often enabled me, notwithstanding bodily suffering,
to sing praises to his name.
Oh! may I never forget his mercies, but surrender myself more unreservedly unto Him,
who has a right to the disposal of all that we possess.
On sitting down once more with my family, much humbled,
the secret aspiration of my soul was unto the Lord,
that increased qualification might be experienced, rightly to go in and out before them:
for oh, how awfully important, has it appeared to me in my late illness,
is the situation of those who are heads of families, and have under their care,
whether their own offspring or not, tender youth,
very susceptible of lasting impressions.`"

About four years before her decease she became a member of Southwark monthly meeting,
having married William Pollard, a Friend, of that meeting.
From this period she was generally in delicate health; but was, at the same time,
a striking example of diligence in the attendance of meetings,
and by the solidity of her deportment,
evinced that her mind was fixed on the Source of all good.
Her ministry was sound and weighty,
and she was particularly concerned that she might not exceed, by expression,
the requirings of duty: and sensibly feeling the great uncertainty of time,
was often led instructively to set forth the need of a preparation for eternity.

In her last illness, which was a consumption,
she was confined to the house for several months.
During the progress of the disorder, she suffered much from weakness,
yet she apprehended it right to discharge a debt of love to several individuals,
who at her request were sent for.
Although, previous to these religious engagements,
she was so low and weak as scarcely to be able to articulate,
she was strengthened to relieve her mind to her own humbling admiration,
seldom appearing fatigued by the exertion;
and she spoke of being mercifully favored with the reward of peace.
From her feelings afterwards, she was ready to conclude that the work was done,
and that she had only to wait the appointed time, until her change came, saying,
"`What a glorious day will that be;`" and requesting that 9he might remain very quiet.
She continued in this state of existence about six weeks longer,
in the course of which time she believed it required
of her to send for some of her young friends,
with whom she labored faithfully in the love of the Gospel.

On the 25th of the Fourth month, she appeared rapidly sinking, and at one time,
when in extreme suffering, said to her husband, "`Pray for me, that I may be released.`"
At another time remarking, "`What a mercy it is,
to have nothing to do but to bear the sufferings of the poor body.`"
On some friends calling to see her, she spoke to them nearly as follows: "`Be faithful,
you who are called to labor.
I have suffered much from unfaithfulness, in not yielding,
in the last meeting I attended, to a pointing of duty,
which repeatedly revived in my mind with clearness, relative to the uncertainty of time,
and the necessity of pressing onward at every period of life;
not sinking under the feeling of inability,
but endeavoring to look to our great High Priest,
who remains to be touched with a feeling of our infirmities.
Oh! how have I seen the purity that is needful for an admission into the heavenly kingdom;
and have so beheld the value of immortal souls, that to help one into the right way,
seems worth spending much strength for.
Notwithstanding my sins of omission and commission,
I have thankfully to acknowledge a sense of forgiveness,
and a belief that they are blotted out, through the efficacious blood of the Lamb;
and now I can trust in the mercy of God, through Jesus Christ.`"
At another time she said, "`I have been under great conflict of mind;
but it was hushed by peace, be still, '`and succeeded by a calm.
All is now centered in, Your will be done.`"

Through the whole of the day preceding her dissolution, she suffered much pain,
and it was difficult to understand what she said;
yet it was evident that she was at intervals engaged in prayer,
and she was several times heard distinctly to say, "`O! my God,
take me not away in anguish.`"
This petition seemed mercifully granted;
her breathing became gradually more and more easy, and,
on the morning of the 4th of the Fifth month, 1824, she fell into a sweet sleep,
in which she passed quietly away; being prepared, we may humbly trust,
to be added to those to whom, through redeeming mercy, this invitation applies, "`Come,
you blessed of my Father,
inherit the kingdom prepared for you from the foundation of the world.`"

[.asterism]
'''

MARY JACKSON was the daughter of James and Elizabeth Jackson.
Her father was a farmer, and resided near Ware in Hertfordshire.
He died when his daughter was young;
and the farm was placed under the occasional superintendence of her brother-in-law,
until the death of her mother, to whom she was a very tender and affectionate nurse,
during several years of infirmity, brought on by repeated paralytic attacks.

She was blessed with a clear and good understanding;
but had received no other education than what she obtained at a day-school,
when quite a child; and, in addition to the necessary attention to her aged parent,
was much engaged in the care of the dairy, and other matters connected with the farm.
She was, at the same time, a bright example of steadiness and propriety of conduct;
and constant in her attendance of our religious meetings,
pressing through many difficulties to go to them.

On the decease of her mother,
she undertook the charge of the family of her brother-in-law, he having become a widower.
As a mistress, she exercised an unremitting care for the servants,
both as to their temporal comfort, and their preservation from evil; and was careful,
that the men employed`' on the farm, who were inmates in the house,
should regularly attend the family reading of the Scriptures, on First-day evenings.
Such a Christian concern for individuals of this class of society,
was not so general fifty years ago, as we may hope is now the case;
and it is a practice worthy of imitation, by all who have it in their power,
thus to manifest an interest in the best welfare
of this too often neglected class of the community.
If the maid-servants, or farming lads, could not read, she taught them herself;
and some of those who did not know their alphabet when they came to her,
before they left could read a chapter in the Bible, so as to understand its contents.

Mary Jackson never had much property; and when she was advanced in years,
a person who held some of the little which she possessed, failed.
On this occasion, she wrote thus to a niece, whom she had tenderly watched over,
and cared for from early life: "`The sorrowful event,
which was feared when you were with us, and has since been realized,
has affected me much, and deprived me of many hours`' sleep; though I can say,
my share as to my own loss, has been the least part of my concern.
Indeed, I am ready to wonder how little that part has affected me.
It is no virtue in me;
but I can but esteem it an additional favor conferred by the Giver of every good.`"

After this circumstance, her income was so limited,
that it only allowed of her occupying a single room in a cottage;
where that humility and circumspect conduct,
which had marked her instructive walk through life,
were adorned by a sweetness and true Christian contentment,
which additionally endeared her to her friends.
The needs of her poor neighbors greatly interested her benevolent heart;
and as long as she was able, by her industry, to contribute to her own support,
she would assist them, remarking, on cases of distress:
"`I wish to do just what is right for such a one
as I. I am not afraid that I shall live to know lack.`"
And she endeavored, in after life, according to her ability, in some little way,
to relieve their sufferings,
frequently also representing their case to the more affluent.

While it is encouraging to observe those who are endowed with large possessions,
preserved by the influence of true religion, from being high-minded,
or trusting in uncertain riches; it is not less edifying to contemplate instances,
where the same blessed principle exalts those of low degree, and enables them,
amidst various trials and privations, in everything to give thanks.
Among these, the subject of this memoir may be justly classed,
as appears from the representation of her friends, and her own memorandums.
From this last-mentioned source of information, the following extracts are taken.

[.embedded-content-document]
--

1809.--Eleventh month, 12. Since my residence in my small apartment, I have had,
at times, to acknowledge with thankfulness, that I am provided with everything requisite,
and that, far from feeling uncomfortably lonely,
I have hitherto much enjoyed the degree of solitude it has afforded.
But the unwearied enemy being busy in every station and situation in life,
how do I at this moment long, that I may keep watchful while time is afforded; that,
after having been.
favored with more of the incomes of the presence of Him, who is above all to be desired,
I may not depend as upon the manna gathered yesterday, or sink into a lethargic state;
and that my faith may not fail, in times of desertion,
but that one grain may be afforded to the last.

1812.--Eleventh month, 21. After alluding to the death of two of her neighbors,
she remarks: "`Whenever the messenger may be sent, may I be in a state of readiness.
But, alas! my weakness is inexpressible;
though it is sometimes a consolatory consideration,
that our weaknesses are fully known to Him who mercifully took upon Him our nature,
and has a feeling of our infirmities; or there would be no hope.`"

1814.--Tenth month, 7. I have this morning been favored with renewed desires,
that I may endeavor to keep near to that unerring Guide,
who is alone able to protect from the snares of the adversary of man`'s happiness,
who is still very busy to draw aside; and I find that increasing watchfulness is needful,
even in the confined station in which I am mercifully placed by a tender Father.
He knows my great weakness and inability to occupy with a large talent,
even of the things of this world; that I am frequently sensible that thankfulness is due,
not only that I am favored with sufficient, at present, to supply all my needs; but also,
that a large share is not committed to my trust.
May I properly spend the small portion that I have, without either indulging too much,
or, on the contrary, denying myself what is needful;
without too great anxiety for the future.
In addition to the many favors conferred on so unworthy an object,
I esteem it no small one, that I am still in the enjoyment of contentment,
and not tried with fears that I shall be suffered to be in need.

1816.--Eleventh month, 9. Notwithstanding my indescribable poverty +++[+++of spirit]
it may afford me some encouragement to remark, that twice in this week,
when my head has been on my pillow,
having been favored with renewed desires to draw near to the Source of Good,
a degree of hope was experienced, that, through unspeakable mercy,
my weak endeavors would be blessed at last.
Oh! may it be so, says my soul at this time;
but various are the temptations that await me; yet I think my desires to overcome,
increase rather than abate, as age advances.

--

When her strength had so far declined, that it became unsafe for her to live alone,
she was kindly cared for, at the house of her nephew, John Brown, of Hertford,
by whom she was accommodated as a boarder, for the remainder of her life.
In the year 1818, she wrote as follows: "`At times,
I think I have been thankful for the privileges I share in my advanced age,
when nearly incapable of taking a part in active life;
the hearts of my kind friends being disposed amply to provide for all my temporal needs.
I now spend most of my time in my own apartment alone.
How frequently do I regret that, in a situation so favorable for retirement,
my weakness should be such, as to lack ability to improve it by watchfulness and prayer;
yet there are times wherein I feel desirous of the blessing of preservation,
and see the necessity of refinement, not only for myself,
but also for all my endeared relatives,
and in a peculiar manner for those of the younger class.`"

This aged Friend was a bright example of patience and composure, during her last illness;
and her expressions, while they marked deep humility,
manifested no less strikingly a readiness to number her blessings,
a disposition which had been instructively apparent through life.
She died at the age of seventy-nine, in the Sixth month, 1824.

[.asterism]
'''

JOHN DONBAVAND was the eldest son of Joseph Donbavand, who was, for many years,
a teacher of Ackworth school.
After having received his education in the institution, being an orderly boy,
and thought suitable for the station,
he was bound an apprentice to the school for seven years.
Though his conduct during this period, was apparently, in great measure,
consistent with his station and religious profession, yet,
when about twenty years of age, he wrote thus, on a retrospect of former years.
"`At the age of fourteen I was chosen for an apprentice.
How pleasant it would be to me, if I could, in giving an account of all my youthful life,
here state that I was preserved in innocency and watchfulness.
For lack of this latter blessed influence on my conduct,
in a year or two I deviated from that way into which, I have often since believed,
my feet had been happily turned;
and instead of endeavoring further to become established,
I wandered wider and wider from the fold of rest, till I reached my twentieth year.`"

About this time the Lord was graciously pleased to
awaken him to a sense of his undone condition,
and of his great need of redemption from the power and guilt of sin.
Under these convictions he made the following memorandums.

"`I had now no pleasure when alone, or when in company.
I passed over several weeks, and my soul could find no rest.
I sought private places and kneeled down,
beseeching the Lord that He would have mercy upon me.`"
"`Having undergone much chastisement, I am encouraged to hope, that, before long,
some relief from present distress and suffering will be afforded me.
O my God!
You only know the deep wadings I have to make.
Had You not most mercifully condescended to point towards a way for my deliverance,
I do not know what would have become of me.
In a while, I began to take delight in reading religious books,
and especially the Holy Scriptures; and a comfortable hope was raised,
that if I patiently endured, and remained faithful to manifested duties,
I should in time, come to enjoy a measure of Divine favor.`"

In the Second month, 1810, near the end of his apprenticeship,
John Donbavand was ballotted for the local militia.
For bearing his testimony against war, by declining to serve or to pay the fine,
he was committed for a month, to the house of correction at Wakefield,
in company with several others, who were in like circumstances.
Some of his remarks, written at this time,
clearly show that his suffering in this way was not a matter of course,
merely because the Society of which he was a member had
uniformly maintained a testimony against all wars;
but that he acted from a conviction,
that the true disciples of Christ ought not to be instrumental in destroying their fellow-men.
Within four years, he was again subjected to a similar trial of his religious principles,
and again committed, with two of his fellow servants at Ackworth,
to the house of correction at Wakefield, for the term of one month.
One of the county magistrates, as he had on the former occasion,
now also exerted his influence to obtain some privileges for him and his fellow-sufferers,
which rendered their confinement less irksome.

After the expiration of his term as an apprentice, he was engaged as a master in.
the school at Ackworth, which situation he filled the remainder of his life.
He was valued for his steady, diligent,
persevering attention to the duties of his station, both in and out of school.
His deportment was plain and unassuming,
and his daily interaction with the scholars afforded many opportunities,
which were gladly embraced by him, of opportunely giving a word of advice.
His counsel reached the witness for Truth in the minds of his tender charge,
and convinced them,
that though he considered improvement in their school-learning to be indispensable, yet,
a far more important lesson was, the knowledge that they were by nature prone to sin;
and the great need they had of becoming subject to Him,
who came to seek and to save that which was lost.
He appeared to maintain a constant, watchful care,
lest the solemn season of his youthful dedication should not be kept fully in remembrance;
and thus, being preserved in liveliness of spirit, he was enabled,
as he advanced in years, to make progress in the Christian race.

The superintendent of Ackworth school,
by whom the preceding delineation of character has been furnished, further adds:
"`He sometimes uttered, in our religious meetings,
a few words in simplicity and brokenness of spirit, by way of exhortation; and,
at other times, in supplication for a continuance of the Lord`'s mercies.
These little offerings, I believe, were generally acceptable to his friends.
In short, I think his life, after he attained to man`'s estate,
was one of great circumspection,
of much inward travail for the assistance of the Spirit
of his Divine Master in the regulation of his own heart,
and for the guidance of his conduct in his interaction with the children.
His labors in this institution, I think, were blessed; and I am quite satisfied,
that he had no joy like that which arose from a knowledge of the prosperity of Zion.`"

The following memorandums show the humble opinion
which this faithful assistant entertained of himself,
and his watchful care of his own conduct in the discharge of his important duties.

[.embedded-content-document]
--

1819.--Sixth month, 3. A fear often attends my mind,
that I am not making that progress towards Zion which many others do,
who, perhaps, are younger than myself.
However this may be, may I hold on my way in faith and patience,
seeing that it is he only who holds out to the end that shall be saved.
I have no desire to complain of the allotments of Providence concerning me;
for I plainly perceive, they are all in infinite wisdom.

1823.--Tenth month, 1. Oh! may I learn more and more to depend on You, O Lord,
in whom is all help; and may I, from time to time,
leave to your care the direction of the dear children,
when required publicly to go in and out before them.
I have long seen, that of myself I can do nothing acceptable unto You,
only as You are pleased to work in and through me.

Tenth month, 5. This morning, a desire arose in my mind,
as it has done at many other times, that the Lord would be my helper,
through my week`'s duty among the boys.
Oh! no one knows, +++[+++but by experience]
the care and watchfulness, and the great searching of heart,
attendant on the master on duty,
who is desirous to act faithfully in the discharging of every requiring.

Tenth month, 14. The Lord has been with me,
can my soul say! and He has helped me through the business of the day.
What shall I render to You, O Lord! for this and all your mercies vouchsafed to me,
a poor unworthy creature.

--

In the spring and summer of the year 1824,
the health of John Donbavand appeared to be declining:
he had for some years been far from robust.
He was absent from the Institution in the course of the Eighth month,
and returned to his accustomed duties, apparently in improved health and spirits.
In the Eleventh month, he was taken ill of an epidemic fever,
which had prevailed in the school, and very soon became extremely debilitated.
The medical assistance, and different means,
which proved useful in the cases of the other patients,
seemed to have no effect in arresting the progress of his disorder.
Throughout this illness, which was very severe,
he was favored with patience and tranquillity,
and entirely resigned to the will of his Lord.
He died at the age of thirty-five, on the 30th of the Eleventh month, 1824.

[.asterism]
'''

SAMUEL ALEXANDER was born at Needham-market, in the county of Suffolk, in the year 1749.
His parents were Friends of a pious character, who gave him a guarded education,
and trained him up to habits of diligence.
He was of a lively and cheerful disposition, and, in early life,
the buoyancy of his spirits sometimes led him to join in things
which did not comport with the apostolic injunction to youth,
to be sober-minded; but it is believed, that he was preserved from gross evil.
When he attained to manhood, and left his father`'s house,
his connection in business introduced him to habits
of intimacy with persons of gay and worldly dispositions,
which gave an unprofitable bias to his mind, and led to some deviations,
in dress and manners, inconsistent with the simplicity of our religious profession;
yet he always entertained a sincere regard for the
ministers and consistent members of our Society,
and his house and heart were open to them.

In the twenty-third year of his age, he married Elizabeth,
daughter of John and Lucy Gurney, of Norwich,
in whom he found a virtuous and amiable help-meet,
and to whom he was united about fourteen years.
She met with an affecting accident,
which was succeeded by an illness of some months`' continuance,
from which she never recovered: this made a deep and lasting impression on his mind:
he was led to see the vanity of the world,
and the insufficiency of temporal enjoyments to satisfy
the necessities of an immortal soul.
The strait gate, and the narrow way, appeared to his view as the only path of safety;
and he was made willing to forsake all, and follow Christ.
Continuing humble, watchful unto prayer,
and attentive to the manifestations of the Holy Spirit,
he soon found the constraining influence of Divine love
to awaken in his mind a concern for the welfare of others,
and about the year 1789, he came forth, in an acceptable manner,
as a minister of the Gospel.

Having been favored to acquire a competence of temporal possessions,
and not desiring an undue accumulation of wealth,
he retired from business at an early period of life;
devoting much of his income to the purposes of hospitality and benevolence,
and employing his time and talents more fully in religious service,
and in the promotion of acts of Christian philanthropy.

Courteous and affable in his manners, his society was generally engaging;
and being watchful to embrace opportunities to impart a word of caution or reproof,
where needed, he was, at times,
made instrumental to the help and encouragement of others.
His desire for the welfare of our youth was conspicuous;
and he was frequently concerned in love,
to impress upon their minds the importance of the precious cause of Truth;
and earnestly would he entreat them to come forward in support of its principles,
and to follow their Heavenly Guide, wheresoever He might be pleased to lead them.

At different periods, Samuel Alexander visited, as a minister,
the meetings and families of Friends in several parts of this nation.
He was a very constant attender of the yearly meeting in London,
repeatedly attended the half-year`'s meeting in Wales,
and was twice in Scotland on religious service.
His ministry was sound and edifying; and, as he advanced in years,
the general tenor of his life increasingly manifested that
he was concerned to observe the injunction of the apostle,
to become an example to believers, "`in word, in conduct, in charity, in spirit,
in faith, in purity.`"

He was cautious not to move in the exercise of his gift as a minister,
without a clear apprehension of required duty;
and it was to him a source of devout gratitude,
when permitted to feel the baptizing power of Truth prevailing in our meetings for worship.
In our meetings for discipline, it was instructively obvious to his brethren,
by his reverent deportment,
that he was often concerned to wait before the Lord for the arising of his power.

When in declining years, though not often from home,
he continued to feel a lively interest in all that
concerned the good of our religious Society,
or tended to promote the cause of Truth and righteousness in the earth and his diligence,
even to old age, in a conscientious discharge of what appeared to be present duty,
afforded a pleasing and animating example.

On the 4th of the Twelfth month, 1824,
having been actively engaged in devising means for the employment
of the children of the poor in his own neighborhood,
he was suddenly attacked with a spasmodic affection of the chest,
which greatly reduced his strength.
The painful symptoms speedily yielding to medical treatment,
hopes were entertained of his being spared a while longer.
He sometimes appeared in doubt as to his recovery; but was sweetly tranquil,
and said that he felt no condemnation.
He once observed, that if it were intended for his end,
he should like to see it with rather more clearness; and remarked,
that we have nothing to trust to but the mercy of God in Christ Jesus.

On waking one morning he requested his daughter,
who had sat up with him during the night,
to take from his pocket a short extract he had recently
made from a work which he had been reading.
It consisted of some expressions which were written in the prospect of death,
and among other pious sentiments were these: "`Abide with me,
my Jesus! for the time is far spent, the shadows of evening are stretched out,
and the day is declining upon me.
I earnestly entreat you, blessed Lord! to order such an end of life to me,
as may be truly Christian, acceptable to You, and perfectly void of sin and shame; and,
so far as you see fit, of extreme pain.`"
It was evident he intended to convey, that such were the breathings of his own soul.

About eleven days after the before-mentioned attack, he arose to breakfast,
and took his usual repast with some relish.
Soon after, he spoke of uneasiness in his neck and face,
of which he had before complained, and suggested the trial of a fresh remedy;
when pausing about the space of a minute, he leaned back in his chair,
and without the least struggle, expired.
Thus, at an unexpected moment, his spirit was gently called home,
and spared all further conflict.
This solemn event occurred on the 15th of the Twelfth month, 1824.

"`Many,`" it is said, "`are the afflictions of the righteous;
but the Lord delivers him out of them all.`"
It was evident to his most intimate acquaintance,
that our dear departed friend often experienced great poverty of spirit; and had,
at times, to pass through close conflict of mind,
both on his own account and that of the church.
These baptisms, as they were patiently endured,
became instrumental to his further refinement; and, being rich in faith,
and much redeemed from the spirit of the world, and having yielded, in meek submission,
to the sanctifying operations of the Holy Spirit,
we may contemplate his release from the trials of time, as a change unspeakably happy,
and an entrance into the joy of his Lord.
