== Chapter 10

[.chapter-synopsis]
* Robert Fowler
* Tabitha Lowe
* George Sanders
* Isaac Pease
* William Grover
* Sarah Knight

ROBERT FOWLER was born at Melksham, in the Fifth month, 1755.
The death of his pious mother deprived him of her tender care,
before he had attained his seventh year;
and though his valuable surviving parent watched over him with affectionate anxiety,
yet this loss, with some other circumstances,
introduced him into trials while very young.
It appears, however, that he was early sensible of the visitation of the love of God;
but as he advanced towards manhood, he was much exposed to temptation;
and though mercifully preserved from deviating from the path of moral rectitude, yet,
to use his own expressions, no words could convey the conflict through which he passed.
He was so deeply impressed with the necessity of striving to enter in at the strait gate,
that while his engagements, as an assistant in business, were too close during the day,
to admit of much, if any time for retirement,
it was his usual practice to spend a portion of the night in seeking after Divine direction,
and in craving a blessing.

The business to which he was brought up, that of a wine and spirit merchant, was,
in some of its branches, of a nature with which he felt uneasy:
and soon after it became his own,
though he was then in a situation principally dependent upon trade,
he resigned the more profitable part of it; and he has sometimes with thankfulness said,
he believed a blessing rested upon this sacrifice.
His circumspect life and conduct endeared him to his friends;
and he was for many years in the station of an elder.

When attending the yearly meeting in Dublin, in the year 1799,
he first appeared as a minister.
That diffidence and humility for which he was conspicuous through life,
and a deep sense of the solemn nature of the engagement, caused him to move with caution.
In the course of the latter years of his life,
he was given up to travel much in the service of the Gospel,
and visited many parts of this nation, some of them repeatedly,
and was three times in Ireland; and his pious example, and upright labor,
in word and doctrine,
made an instructive and more than transient impression in many places.

In the exercise of the gift which had been conferred upon him,
in the ministry of the Gospel of our Lord and Savior Jesus Christ,
he conscientiously sought to approve himself a faithful steward,
patiently and reverently waiting for the renewal of the heavenly unction;
being modest in speaking of his own commission,
and cautious not to exceed in expression the opening of the Word of Life.
His communications were weighty and comprehensive;
affording full evidence of his faith in that redemption which comes by the Lord Jesus;
ministering to the instruction and comfort of the seeking and exercised mind,
and to the confirmation and refreshment of those who were passing through many tribulations.
He was well versed in the Sacred Writings;
and in his spiritual and figurative illustrations of the Old Testament,
often strikingly instructive.
If his ministry had, at any time,
been attended with an unusual degree of Gospel authority,
it might afterwards be observed,
that his demeanor was then more peculiarly marked with humility: thus, he returned,
as it were, "`to sit at the gate.`"
Of the walkings of this devoted servant, it may be truly said,
that they were in deep poverty of spirit; but herein he was, at seasons,
favored to know the irradiations of the Sun of Righteousness, by which he saw how,
and when, and where to take his steps.

He was a truly valuable member of our Society,
being concerned for the right exercise of our discipline,
for the maintenance of sound views of Christian doctrine,
and for the support of our peculiar testimonies;
esteeming these as a precious trust committed by the Most High to our forefathers,
and through them to us: and earnest was his solicitude,
that from among the youth there might be a succession,
prepared by the baptism of the Holy Ghost,
to become faithful and devoted laborers in the church of God.

Robert Fowler possessed a clear and deliberate judgment;
his heart and ear were ever open to the trials of his fellow men;
he seemed to consider that his time and talents were
given him to serve others rather than himself;
hence his advice and counsel were often applied for,
and beneficially received by his neighbors.
Without any compromise of principle or of practice,
he evinced a liberal spirit and true esteem, towards those of other religious societies:
to them, and to all, he was courteous in his demeanor,
and mild and unassuming in his manners.
He was particularly cautious not to reflect upon the character of any,
and rarely felt a liberty to repeat any thing he might hear to the disadvantage of another;
endeavoring practically to keep in view the recommendation of meekness, temperance,
brotherly kindness, and charity.

Though evidently careful to keep under the yoke of Christ,
yet his conduct was marked by a well-regulated, cheerful piety.
Under the influence of the love of the Gospel, he often proved himself a faithful,
sympathizing friend, to those who were in suffering, either of body or mind.
He was frequently and fervently exercised in spirit before the Lord,
for the exaltation of his cause on the earth;
and being deeply sensible of the benefit of true silence,
often retired from his usual avocations, to wait upon the Almighty,
or to peruse the Holy Scriptures.
In his care, both with regard to himself and his family, in this latter respect,
he was indeed exemplary.

In the early part of the year 1823, when nearly sixty-eight years of age,
this devoted Christian informed his friends of an apprehension,
which he had entertained for some years,
that it would be right for him to go and reside for a short time in the city of Paris.
In this exercise of simple faith, he saw but little religious service before him;
but willingly surrendered himself to the disposal of his gracious Lord and Master.
He was liberated, with the full unity of his friends,
and in the Sixth month of the same year, left the many comforts of his own home,
and took up his abode in that city, for about six weeks,
among a people who were to him of a strange language.
Feeling at liberty to return to England, he again joined his beloved family,
and was favored, for a time, to feel his home to be a peaceful retreat.

In the spring of 1824, he believed it his duty to return to Paris, which he did,
accompanied by his wife and some of his children,
and resided there upwards of two months.
In the course of these visits, way did not open for much active religious service;
but the concern which was uppermost in his mind,
appears to be well set forth in the following extract from one of his memorandums.

"`In the remembrance of that uniting language of our dear Lord, '`One is your Master,
even Christ, and all you are brethren,`' a fervent desire has been raised in my heart,
that it may please the Father of the Universe, the Arbiter of the whole earth,
to spread more and more in the hearts of men universally,
the knowledge of his ways and of his goodness; and cause the dominion of his dear Son,
our holy Redeemer, to be enlarged; that thus the day may be advanced,
when nation shall not lift up sword against nation.
Since I have been in this land, my cry has often been,
that He who was pleased to restrain Rehoboam, king of Judah,
from going against his brethren, the children of Israel, may be pleased to grant,
that the two kingdoms of France and Great Britain, separated only by a narrow channel,
may be united by a perpetual bond of amity and peace.
As I have passed along the streets of this city, and beheld many of its inhabitants,
I have felt, with gladness, that I could hail them as my brethren, as my fellow-pilgrims;
with a strong desire,
that we may be enabled to hail each other in that charity which is the bond of perfectness,
and through the merciful dealings of our Heavenly Father,
become fellow-citizens with the saints in light, and with the household of God.`"

He also very deeply felt the importance of a circulation
of the Scriptures in that city and country;
remarking,
that he considered it would be a powerful means of bringing the people unto Christ:
hence, he was anxious for the success of the Bible Society in France.
He endeavored faithfully to discharge his duty,
in promoting this and other truly Christian objects,
in such a way as opened to him at the time, and his exertions were well received.

While thus absent from his native land, his faith was often deeply tried,
and he experienced great poverty of spirit; but was enabled to keep in patience,
and to retain his trust in divine guidance,
and his confidence in the goodness of the Almighty,
and thus not to give way to undue depression.
He was concerned not to enter into any service,
to which he did not believe himself called;
and his continued exercise of mind before the Lord,
and fervent prayers for the dispelling of the dark clouds of superstition and bigotry,
have, we cannot doubt, been graciously viewed with Divine acceptance.
He afterwards travelled with his friend Samuel Capper to the south of France,
and visited those professing with us at Congenies, and in its neighborhood;
and had some religious service on his way back to England.
When in the south,
his health was much affected by the heat of the climate and other circumstances,
yet he gave but little rest to his enfeebled frame.

Early in the Ninth month,
he was favored to return home to the bosom of his tenderly beloved family,
by whom he was thankfully received; but his appearance was so emaciated,
that they could only rejoice with trembling;
for though still enabled to edify and comfort others, by example and precept,
yet his strength gradually declined.
In the Twelfth month he went to Bath, and after spending a few weeks there,
proceeded to Clifton, near Bristol;
as it was hoped that further medical aid and change of air might be beneficial.
He was also desirous of attending some meetings in each of those cities.
He returned home on the 4th of the Third month, 1825,
without any improvement in his health;
but exerted himself for several weeks to get to meeting.
On these occasions, and during the absence from home,
to which allusion has just been made,
his kind and humble deportment still endeared him to his friends;
and while illness was making rapid inroads on his bodily powers,
he was strengthened in the authority and love of the Gospel, in a remarkable manner,
to exercise his gift in the ministry;
so that it seemed the consoling words of the Psalmist might have been adopted by him,
"`My flesh and my heart fails; but God is the strength of my heart,
and my portion forever.`"

During his illness he did not often feel at liberty to say much as to his mental feelings;
but once, after having suffered much pain, remarked,
that such occasions as these afford great opportunity to show forth
the exercise of patience;-a virtue of which he was,
throughout his illness, a bright example to those around him.
On the morning of the 20th of the Fourth month, after an easy night, he said:
"`I have been thinking what a favor it is, for those who are prepared,
to be taken away without much previous suffering;`" and then begged
to feel resignation to every permitted trial.

The following day, on awaking, he remarked, "`I scarcely knew where I was: I thought,
or dreamed, I was in a very pleasant place, to which I hope I am going;
and that it may please Divine Providence to release me from that portion of suffering,
which has been my cup for nearly forty years.`"
This, he said, related to the sufferings for the Gospel; adding,
"`No one can tell my conflicts, no one can tell what I have passed through;
but in mercy I now seem released from all.`"
During the night of the 25th, he suffered much from restlessness,
and difficulty of breathing.
The next day he requested to have some memorials of deceased friends read to him;
and to the last day of his life he read the Scriptures diligently.
In the following afternoon, his strength rapidly declined;
he looked upon those around him with if expressible sweetness,
his countenance conveying an impression of heavenly peace;
and in the evening of the same day, the 27th of the Fourth month, his spirit was,
without an apparent conflict or the least struggle,
released from an afflicted tabernacle.

The concluding expressions of the testimony of Friends of Wiltshire monthly meeting,
concerning this devoted follower of the Lamb,
may not unsuitably terminate the present narrative.

"`In closing this memorial of one who, through faith in God,
and in the redeeming power of Christ Jesus our Lord,
and through the efficacy of his grace, was a bright example among us,
we deeply feel our loss; at the same time we reverently believe,
that in his release from that tribulated path which
was his allotted portion in the militant church,
death is swallowed up in victory; and that the blessing pronounced by the lip of truth,
on the poor in spirit, is his reward forever.`"

[.asterism]
'''
TABITHA LOWE was the daughter of Joseph and Sarah Burgess, of Grooby Lodge,
near Leicester, and was born the 16th of the Eighth month, 1783.
The salutary effects of a guarded education were evident in her childhood,
not only producing a strict adherence to truth in what she said,
but a conscientious endeavor to do right.
She was, however,
early made sensible of her natural proneness to things of a frivolous and hurtful tendency;
and possessing an active and susceptible mind, although of a timid disposition,
she had much to struggle with, in the temptations and vanities incident to youth.
About the twenty-second year of her age,
through the contriting visitations of the Almighty to her soul,
she became fully awakened to the necessity of leading a watchful and religious life,
and entered upon a course of close self-examination,
and earnest endeavor to be found walking acceptably before the Lord.

She was of a delicate constitution, and subject to frequent attacks of illness.
These painful dispensations she seems to have viewed as blessings;
and the following observations are extracted from numerous others,
which evince a humble and resigned spirit.
I am favored to look upon a growth in righteousness,
as of incomparably more importance than the health of this poor, frail tabernacle.
All pilgrims meet with trials in passing through this vale of tears;
but the arm of our ever adorable Helper is graciously underneath,
to support and comfort those who humbly trust in Him.
There seems such depravity in my nature,
that it may be necessary I should go through many deep and proving baptisms.
This, I often think, will be my lot, if I faithfully tread in the path of revealed duty;
but may I never forget the Lord`'s gracious dealings with me in this sickness,
nor the covenant I have made with Him, be my trials and sufferings here what they may.`"

In the Third month, 1811, she was married to Hagger Lowe,
and became a member of Southwark monthly meeting.
Before, and subsequently to this event,
her mind was much exercised on the subject of a call to the ministry;
and the conflicts and baptisms which she experienced,
while under preparation for this awful service,
may be considered as descriptively conveyed in the following memorandum.

1809.--Twelfth month.
"`The Lord alone knows the state of my heart.
I often think, none ever experienced the like.
Lord! what will become of me?
I tremble, and, as it were, recoil,
when I think you may some time call me to become a public instrument in your hand.
I once thought my great inability,
and the trial it would be to my naturally timid disposition,
would be the most awful part; but that does not now seem the worst:
with my past manifold transgressions, how is it possible?
But I know all things are possible with You:
make me as clay in the hands of the potter.`"

On the 27th of the Third month, 1814,
she thus notices her entrance upon the important station which
she had believed herself designed to occupy in the church.
"`I had publicly to offer up supplication in our meeting at Southwark,
on First-day morning; and my heart acknowledges it is the Lord`'s doing,
and marvelous in our eyes.
May He be pleased to help me, then I need not fear; nor can I wish for more.`"

During a long confinement to the house, in the year 1816, she thus wrote: "`My faith,
in this weak and debilitated state of health, has been many times nearly tried;
yet I may with humble gratitude acknowledge,
that He who knows the hearts of his children,
has often graciously extended his all-sustaining, life-giving presence,
to the unspeakable comfort of my poor, feeble mind; so that I have been ready to say,
'`Lord! what am I, that you should thus regard me, and make my cup to overflow?`'`"

The religious communications of this departed Friend,
were evidently the fruit of lively exercise,
and of dependence on the fresh discoveries of the Divine will;
and were often accompanied with the baptizing influence of the Holy Spirit.
She was, at times,
strikingly concerned to speak to the spiritual condition of individuals;
enforcing the necessity of faithfulness and diligence, and she was, at the same time,
an instructive example of humility and dedication.
She was much in the practice of private retirement, and of perusing the Holy Scriptures,
and of meditating on them.

She evinced her concern for the present and eternal welfare of her children,
by frequent counsel adapted to their capacities,
and petitions of soul to the throne of grace on their behalf;
and in some records of her maternal and Christian solicitude, writes thus:
"`I trust I can with sincerity say, my chief desire for them is,
that they may be brought up in the fear of the Lord, and the love of his truth;
that they may be plain, simple, and humble.
I covet not great things for them, nor the possession of much riches:
they are attended with many snares, and the true comforts of life are not added thereby.
When we consider that we are only placed here for a very short time,
and must hereafter exist forever and ever, either in unspeakable misery,
or in the glorious presence of God and our blessed Redeemer,
how should we be seeking first the blessing of heaven,
and feel it our duty and privilege to have all things in subserviency thereto.`"

Her last illness was a consumption, and came on in the beginning of the year 1825.
Early in the disorder, she mentioned to an intimate friend,
that although the future was veiled from her, she felt quiet and peaceful,
and considered it right to do whatever might appear likely to benefit her health;
but was not anxious as to the event;
and while sensible of inward poverty and total unworthiness,
was enabled to trust in the mercy of her God and Savior; adding, with tender emotion,
"`Is it not wonderful that I am preserved from anxiety?`"

On the 20th of the Second month, she made the following memorandum:
"`The prayer of my heart this morning has been,
that if it should please Infinite Goodness to restore me to health,
I may indeed know a being more inward, more truly conformed to the example of Christ,
of a meek and quiet spirit.`"
And, at one time,
upon her husband`'s making some inquiry relative to the state of her mind, she replied,
in much brokenness of spirit: "`I feel, my dear, almost afraid to utter it,
lest I should be mistaken; but a short time since,
this language seemed to run through my mind, '`I have cast all your sins behind my back.`'
And oh! if it be so, it will indeed be in unutterable, unmerited mercy.`"
This precious assurance tended to strengthen her faith during the remainder of her days,
and to support her under those conflicts,
which at seasons attended the prospect of a final separation
from the nearest and dearest ties of life.

The following memorandum, dated the 1st of Fifth month,
seems to be the last which she penned: "`The language of my heart this morning has been,
'`Lord, we thank you for your mercies past, and humbly hope for more.`'
Oh! may you be pleased to continue near, in all our afflictions; for,
when your all-sustaining presence is graciously near, what do we need more?
it fills up every void, sweetens every cup, and lightens every burden.`"

Her sufferings towards the last were considerable;
but she was favored to continue sensible.
A few hours before her departure, she seemed much engaged in prayer; and supplicated,
that if consistent with the Divine will,
she might be released from further suffering adding, "`Not my will, but yours be done.`"
Thus resigned and peaceful, her redeemed spirit quitted its earthly tenement,
on the 3rd of the Sixth month, 1825.

[.asterism]
'''
GEORGE SANDERS.
Our late friend, George Sanders, was one of those useful characters,
who conscientiously endeavor, in their walk through life,
to serve the Lord in the way of his requirings,
faithfully occupying their station in the church; and who are concerned,
under the influence of Christian love,
to employ themselves in doing good to their neighbors and their fellow-men.

He was born at Whitby in Yorkshire, in the year 1755.
After attaining the state of manhood, through the visitations of the love of God,
his mind was deeply impressed with a sense of his utter helplessness, by nature,
to effect the salvation of his soul.
He yielded to the reproofs of instruction inwardly made known,
and was concerned to take up the cross of Christ;
and in difficult and discouraging circumstances,
steadily maintained our religious testimonies, of the importance of which,
he had not in his youth appeared fully sensible.
His prospects in life were flattering;
but the love of the world gave way to the love of God; and a will naturally strong, was,
in a great measure, brought under the influence of Divine grace.

Among other means which he adopted to advance his spiritual progress,
it was his frequent practice to seek after retirement.
His care in this respect, is thus described by himself,
in some memorandums made in the Fourth month, 1782.
"`Having often been convinced of the necessity of frequently waiting on the Lord,
in order to find strength and ability to walk in his way, I have, at times,
begun to dedicate about an hour in the morning to that service;
but through weakness and lack of proper attention,
have allowed small things to hinder me.
On the 15th of this month, it coming again upon me,
and being perfectly sensible of the necessity of it, +++[+++the practice of retirement,]
in order to keep me near the presence of my Savior,
and that I may be enabled to wait on Him in true silence,
and to hold sweet communion with my Lord,
I do propose to dedicate an hour every morning to Him, before business,
that I may thereby be enabled to dwell near his presence;
beseeching Him to vouchsafe to be with me, and help my weak endeavors;
for without this divine aid my efforts will be in vain.`"

On one occasion, after spending some time in waiting upon the Lord,
and in serious reading, he remarks: "`It pleased the Lord to break in upon my spirit,
in a very comfortable, tendering manner;
earnest were my desires that he may be pleased to guide and direct
me in the path of true obedience to his holy requirings,
and to enable me to dwell near Him,
that I may witness his fear to be the beginning of wisdom.`"

Reviewing his course of life, ten years afterwards, it appears that he had,
in a considerable degree, kept to the intention then formed,
and that these opportunities for waiting upon God had been at times blessed,
by the sensible visitations of heavenly love to his soul.
During this period, great trouble and distress had befallen him from outward causes,
as well as much spiritual conflict; and earnest were his desires,
that these afflictions might tend to his refinement.
He thus concludes some reflections on his spiritual state:
"`I stand in much need of frequent watchings;
and oh! that it may please the Holy Helper to look down on my poor distressed estate,
and administer what He sees fit for my deliverance from the bitter bondage of him,
who often interferes,
and prevents that abstractedness in which true watching and waiting are to be kept up.
Oh! help me, Lord, that I may experience,
that those that wait on You shall renew their strength.
Grant, if it be your will, that your unworthy one, yet the workmanship of your hand,
may experience this.`"

George Sanders gradually withdrew from the cares of this world, and having,
when in the meridian of life, a comfortable competency, though not possessing affluence,
he, in order more fully to devote himself to the service of his Creator,
retired from a good business, in which his natural inclination prompted him to continue.
Constitutionally active, and benevolent from principle,
he was often engaged in ministering to the temporal
or spiritual needs of those around him;
and few charitable plans were proposed or adopted, within the sphere of his influence,
in which he did not take a part.
Among other means of endeavoring to do good,
he was particularly active in distributing books and tracts of a religious description,
chiefly such as related to the principles of our Society.

As a minister he was earnest, affectionate, and zealous;
careful not to assume any merit to himself,
but to direct the attention of his hearers to the Divine source of strength and purity.
For several years he was often from home, in the service of the Gospel;
frequently on these occasions,
going as a helper and companion to his brethren and sisters who were thus engaged.
Although highly esteemed by his friends, and by the inhabitants of his native town,
he was preserved in much humility;
appearing not to forget that he was an unprofitable servant, and that,
in what he had done, he had done only what it was his duty to do.
Nor did he regard conspicuous sacrifices, or separate acts of devotedness,
as excusing the disciple from bearing his daily cross;
but desired that every pursuit and propensity might
be kept within the safe limits of Christian moderation,
so that all might be done "`to the glory of God.`"

For some years before his death,
a gradual decay of the powers of memory and intellect took place;
yet the prevalence of Christian love,
which his friends were sensible of when in his company,
alleviated their regret for the loss of his services; and they could not doubt,
when a short illness terminated his earthly existence,
that the change to him was unspeakably glorious.

He departed this life the 19th of the Ninth month, 1825, at the age of seventy,
having been a minister about thirty years.

[.asterism]
'''
ISAAC PEASE, son of Edward and Rachel Pease, of Darlington,
was a youth of quick abilities and kind dispositions.
After receiving a liberal education, under the Christian care of his parents,
he was placed in the office of a solicitor, in his native town,
where this care was still watchfully and tenderly extended.
He was advancing towards manhood, in the enjoyment of life,
and raising in his relatives the pleasing hope of
his future usefulness in civil and religious society,
pursuing, with diligence,
those studies which were designed to qualify him to act in his profession,
so far as a member of our Society can go with propriety,
when the state of his health became such as to produce
great anxiety in the minds of his friends.

In the Fifth month of the year 1825, he was too unwell to continue his usual occupations.
He appeared often to be very thoughtful, in reference to the salvation of his soul;
and in conversation with one of his brothers, remarked,
that he sometimes could acknowledge to the goodness of the Almighty; but at others,
he found great difficulty in bringing his mind into settlement.
It was consoling to observe, as the symptoms of his disorder became more alarming,
that a broken and a contrite spirit were often obvious.
At one time, when much tried with difficulty of breathing, he was inquired of,
under a sense of the solemn nature of such a question, as to his mental feelings,
when he replied: "`Oh! yes, I can trust in the mercy of God;
He is a God of mercy and truth:`" adding, soon after,
It is hard work to press forward aright, and be a good example.
I do believe, to be taken away in youth is a great favor;
and if it please Providence to take me away,
I shall escape all the vicissitudes of time.`"

He was at seasons, in the course of his illness,
enabled to believe that the Lord was near to support him; though, at others,
he feared that he had no good foundation on which to build his hopes of enduring happiness,
and several times observed, how difficult it was to feel anything of good,
and how poor he was; yet his prevailing desire was,
to be endued with patience and resignation.

He one evening remarked: "`It is trying, lying so long here.
My illness continues long, there is nothing but seeking for Divine support;
sometimes a little hope springs up, and then again it seems as if I must give up all,
and be prepared.`"
Further adding, how human nature "`does feel,
to think of parting with near and dear relations, father and mother,
brothers and sisters.
There is one dear sister, she is gone before us, (alluding to his sister Mary,
who died about twelve months before,) and we have comfortably to believe,
is safely centered in everlasting peace.`"
And upon being reminded, how many were strengthened, through the power of Divine love,
to triumph over all these things, he acknowledged that such was the case.

On the 20th of the Seventh month, addressing his beloved mother, he said:
"`It is difficult to be resigned,-to live, so as to be prepared to die.`"
And upon a hope being expressed,
that he was at times favored to attain to some feeling of resignation, he replied, "`Yes,
sometimes; but it is hard work to leave all, relations and friends,
and resign all the promised pleasures of time.
Oh!
I look back and see, I have been too earnest in pursuing the things of this life,
not altogether on my own account;-my mind is too full of them.
And then, in some of our meetings, how poor and barren my poor mind has been.`"
Thus the tenor of his remarks showed that his mind had been humbled,
and that the work of purification was going forward.

The following evening, after a solemn stillness,
which took place upon the reading of the forty-sixth Psalm,
which speaks confidently of the strength of those who make God their refuge,
he broke silence, saying with great sweetness and tenderness,
"`I believe the Almighty has been my refuge in time of trouble,
and has been near and supported me.`"
And on his father`'s remarking, how consoling it is to believe that Omniscience sees us,
and Omnipotence supports us in times of affliction, he replied, "`It is indeed.`"

At another time he observed, that he had frequently desired to be enabled to say,
"`Your will be done;`" and endeavored to feel after the Divine presence,
but found it difficult.
He was encouraged by a relation, who had come to visit him,
to keep his mind stayed upon the Almighty; a belief being expressed,
that from the comparative innocence of his life,
and the abundant mercy and kindness of God, He was near to support.
This was assented to by the humble acknowledgment,
"`I have endeavored after a degree of watchfulness;
but I have not worshipped my Heavenly Father as I ought.`"

On the 5th of the Ninth month, after being removed from his couch to the bed,
and evidently feeling the pressure of disease, this patient sufferer lay awhile quiet,
his countenance beaming with serenity, and afterwards said:
"`I trust I have a well-grounded hope of a better inheritance; bus it is all of mercy,
great mercy: it is not by works of righteousness which we have done! no, no,
but according to his mercy He saves us, or where would be my hope?
Oh! how precious is this love of Jesus: I have felt it very precious.
He gave his life as an atonement for our sins; an atonement! yes,
and a propitiatory sacrifice: how precious has the recollection of this been to me.`"
On his father`'s expressing his rejoicing that his son was thus comforted, and his hope,
that should lengthened days be allotted,
the recollection of these moments would accompany
the future steppings of the latter through life,
he replied, "`Yes, I hope so.
But oh, the deceitfulness, the allurements, the temptations of this world:
I know they are powerful, and I fear I should fall.
It is hard work to maintain our steadfastness through all,
and be good examples in the great cause.
I think I had rather go now.`"

On the 25th of the Ninth month,
after being much distressed through the night with coughing, he said:
"`I often try to get down to the Source of patience, but am so weak:
though I think I may exclaim, '`Bless the Lord, O my soul; for his mercies are ever new.`'
"`Many times, when severely tried with pain,
he prayed for patience and strength to endure the allotted conflicts.
The whole of the following day he appeared evidently sinking, and expressed very little;
but on one occasion said: "`I want to go home to-night.`"
Very early the following morning, he sunk quietly away; being, we may humbly trust,
rendered fit for an inheritance among the saints in light,
through the mercy of God in Christ Jesus.

He died at the age of twenty, on the 27th of the Ninth month, 1825.

[.asterism]
'''
WILLIAM GROVER was a friend much esteemed and beloved in our Society.
He was one who from early life appears to have chosen the right way of the Lord,
and to have endeavored to walk before him in reverence and godly fear.
As he advanced in years, he more and more submitted to the operations of Divine love;
and through continued watchfulness, and obedience to the pointings of duty,
attained to that experience and stability in the Truth,
which his conduct and services afterwards demonstrated;
and was for many years an instrument of great usefulness
in the quarterly meeting of Essex,
and in our yearly meeting.

He was a native of Brighthelmstone in Sussex, and was born there in the Eleventh month,
1752; but resided the greater part of his life at Stansted Mount-fitchet in Essex,
conducting the business of a country shop with reputation and integrity; being concerned,
while diligent in business, to have a mind so well regulated,
as that things of the first importance might have
the first place in his thoughts and affections;
and in the endearing relation of a husband, he was truly affectionate and kind.
He was for many years an elder in good esteem;
one who deeply felt the importance of that station,
tenderly sympathizing with those whom he believed rightly called to the ministry;
and was, at the same time,
fervently concerned that the preaching of the Gospel among us,
might be in the power and authority of the Holy Spirit.

In speaking of his character in some other respects,
the friends of Thaxted monthly meeting thus describe him.
"`It is not our intention to extol the character of the deceased as a man,
estimable as he was in the various relations of life;
but to exhibit his Christian virtues, and to ascribe, as he did,
all excellency to the power of Divine grace,
mercifully granted to mankind for their salvation,
through the mediation of the blessed Redeemer, our Lord and Savior Jesus Christ.
The rectitude of his conduct, in the discharge of his moral and religious duties,
his humility, meekness, and dedication to the cause of Truth,
were all fruits of faith in the means thus graciously afforded.

"`He was very exemplary in the fulfillment of his duty to his Maker,
by a constant attendance of religious meetings,
in which his solid deportment indicated great reverence of spirit,
and fervency of desire to gain access to the Fountain of all good;
and on these occasions,
we believe that his mind was often enriched with the incomes of Divine love and peace.

"`He was a great lover of retirement and meditation;
the frequent reading of the Holy Scriptures was also
a source of instruction and comfort to him;
and this practice he was often tenderly engaged to recommend to others,
as one of the means by which they might be strengthened
and encouraged to advance in the Christian path.

"`The views he took of himself were humble,
while his estimate of the true Christian character was a highly exalted one;
hence arose great vigilance and circumspection,
that no part of his demeanor should dishonor the cause he so greatly valued and loved.
This care was manifested in all his conduct;
and evidently so in transacting the affairs of the church,
in which his judgment was clear, and his language persuasive,
tending much to encourage Friends in the support of the discipline,
in the executive part of which he very rarely excused himself from service;
having a care for the prosperity of Truth,
and that his fellow-professors might be faithful in our testimonies,
and consistent in all their conduct,
endeavoring to keep the unity of the Spirit in the bond of peace.`"

His services during the transaction of the important affairs of our yearly meeting,
were highly and deservedly valued.
His first concern in that, and in all our meetings for discipline,
was to have his own mind brought under the regulating power of the Holy Spirit,
endeavoring, in the fear of the Lord, to judge righteously.
His observations were sound and pertinent; they were clear and concise;
and his exhortations were so well guarded, and so much in the love of the Gospel,
that they had a striking tendency to attract others to that
precious influence under which they were delivered.

"`Perhaps few have been so much favored with the prevalence of love;
it seemed to be the constant clothing of his mind,
and was evinced towards all classes of society.
The youth especially were the objects of his tender solicitude,
for whose early attention to the reproofs of instruction,
and for their growth and establishment in the Truth, he felt an unremitting concern.`"

A few expressive lines, thus describe his attachment to the cause of our blessed Redeemer.
"`I believe it is consistent with the genuine principles of Friends,
that all the communications of the mercy, love, power, and goodness of God,
to his creature, man, are in, by, and through our Lord and Savior Jesus Christ,
and no otherwise; and in this belief I am thankful to live and unite.`"

William Grover possessed a sound constitution,
and through the greater part of his life enjoyed good health.
On Second day, the 16th of the Fifth month, 1825,
he came to London to attend the yearly meeting,
from which he had been very rarely absent for forty years.
He was at the meeting of ministers and elders, the morning and afternoon of that day,
and took part in the business, with that Christian alacrity, combined with gravity,
which peculiarly marked his character.
In the course of the succeeding evening, he became alarmingly ill,
and for a few weeks it seemed as if life might have been very soon terminated.
He endured his great sufferings with much calmness and patience,
and about the end of the Sixth month, was able to return home.
Writing to a friend shortly afterwards, he says: "`I desire patience, humility,
and thankfulness may be, through Divine merciful assistance,
the daily clothing of my spirit.
What an eventful seven weeks have the last been to me, a poor, dependent creature.`"

For a while, hopes were entertained of his partial recovery;
but an increase of the disorder again prostrated his strength, and produced, at times,
extreme suffering: this also he bore with Christian fortitude.
For a few hours before his close he was mercifully relieved from all pain;
and his end was remarkably peaceful, on the 11th of the Tenth month, 1825.

The expressions of a religious nature, that were uttered towards the close of life,
were not numerous; but they all partook of that humble,
yet confiding and peaceful character, that distinguished our dear friend when in health,
and bespoke a mind looking towards heaven, of which he said, he had a pleasant view,
particularly of late; and that he was favored to feel very little condemnation.
At different periods he thus expressed himself:
"`The prevailing desire of my mind has been, for many years,
that I might close in peace.`"
"`I have had many blessings, many temptations, and many trials, in my time;
but have been mercifully helped through them.`"
At one time, when evidently under great tenderness of spirit, he observed:
"`The shadow of Divine mercy is very broad.`"
And at another, when conversing about his illness, he said:
"`It is a source of great consolation, to know that He who formed us is near.`"

In the afternoon of the day before his death,
he expressed himself to the following effect: "`My greatest desire is,
that my sun may go down in brightness.
There is nothing so precious, whether in youth or in age, sickness or health,
as a sense of the Divine presence and love.
I have had great cause thankfully to believe,
that the protecting care of kind Providence has been with me all my life long,
from my youth up;`" and, after a pause, added, "`It is my greatest desire, that my sun,
which now seems nearly set, may go down in brightness, without a cloud;
relying only upon the goodness of the Almighty, who can change a life of suffering,
for one of comfort and endless happiness, who can make a deathbed as a bed of roses.
Yes, I bless your holy name,
your presence and love can make a deathbed as a bed of roses.`"
Afterwards he said, in nearly these words: "`My life seems fast closing,
and my afflictions nearly at an end.
I have been greatly afflicted,`" alluding, no doubt, to his suffering during his illness,
"`but doubt not that it has been in unspeakable, unerring wisdom,
that I have been thrown again and again into the furnace,
which is no doubt designed for my further refinement.
Oh! may all the purposes of the Almighty be fulfilled.
Oh! what a precious state is that,
where nothing is lacking but the celestial gate to be opened.
All praise I ascribe unto the Lord`'s holy name.`"

Thus terminated the life of this honorable elder in the church of Christ,
to whom may be emphatically applied this holy declaration,
"`Blessed are the dead who die in the Lord from henceforth: yes, says the Spirit,
that they may rest from their labors; and their works do follow them.`'

[.asterism]
'''
SARAH KNIGHT, wife of Henry Knight, jun., of London, and daughter of John and Jane Lewis,
of Haverfordwest, died the 16th of the First month, 1826,
in the forty-first year of her age, after a suffering illness of about three weeks;
during which she was mercifully enabled to hold fast her confidence in her Redeemer.

She was of a gentle, amiable disposition, and piously inclined from very early life;
and in her later years she was especially concerned, in great humility and watchfulness,
for the salvation of her soul.
A reverence for sacred subjects, and love for the faithful servants of the Lord,
were conspicuous traits in her character;
and though innocently cheerful in company and conversation,
none seemed truly interesting to her, which did not partake of a religious character.
She had learned much in the school of affliction,
and her trials were greatly blessed to her.

Soon after the commencement of her illness, she observed to her brother:
"`I have sometimes been fearful,
that the state of calmness and freedom from anxiety in which my mind is,
arises from a deadness of feeling, or an unconsciousness of my real situation,
and that I am not sufficiently alive to it.`"
On a hope being expressed, in reply, that she was in a state of acceptance, she added,
"`I wish to be upon my guard against anything like presumption; yet I do believe,
that you who may remain to grieve when I am gone,
will not have to mourn as those without hope;
for I believe there is some measure of hope, even for so unworthy a creature as I am.
There is but one source of hope, the Lord Jesus Christ,
and my hope is fixed on Him and Him alone.`"

When suffering from great bodily pain and weakness, she said; "`Oh! merciful Providence!
I am undeserving of the least of your mercies;
but do you be graciously pleased to grant me that degree of patience which
may be needful to bear me through this state of suffering.`"

After supplicating for some time in a low tone of voice,
she called on her husband and sister-in-law to join her in endeavoring to feel after
ability to supplicate that the Lord would be pleased to grant her more light and life.
She then fervently prayed, that she might lie low at the feet of her Redeemer,
that she might be clothed with his righteousness,
and that the Lord`'s will might be done in her.
She often expressed a hope, that if she should be restored,
it might be that she and her endeared partner in life might
endeavor more closely to follow the footsteps of Christ;
many times saying to her beloved relatives who attended upon her,
"`I want you to be more decided,
and that each individual should become that beautiful character,
the decided Christian.`"

To her sister-in-law she remarked:
"`I depend on your letting me know if the doctor consider my case a dangerous one,
as I think it of the utmost importance that invalids should
be informed of their real situation at such an awful time.`"
On being told that it was considered there was danger,
although the case was not a hopeless one, she appeared quite resigned,
desiring that her will might be entirely given up;
and she often prayed in a solemn and impressive manner,
that her soul might be made ready for the final change.
She was naturally timid, and of a most affectionate disposition; yet it was remarked,
that during her illness she did not appear to feel distressed,
either with the fear of death,
or at the idea of parting from those whom she so tenderly loved;
so graciously did her Heavenly Father condescend to deal with her.

Her sister, who had just arrived from the country, on entering her chamber,
found her in supplication,
acknowledging the goodness of the Lord in sending her a mitigation of pain; adding,
"`I knew he would do so in his own good time.`"
In the evening of the same day she remarked: "`I believe I may truly say,
that I have prayed fervently that I may be resigned to the Lord`'s will,
and that the great Shepherd of the sheep may be pleased
in an especial manner to take my dear Henry,
with my other dear relatives, under his peculiar keeping,
and that He may be pleased to conduct them safely to his fold.`"
At another time she remarked: "`I have mourned my lack of gratitude to God;
but this morning I have felt it spring up afresh in my heart towards Him,
not for any one particular blessing, but for all.
I long to feel an increase of holy love for my Redeemer;
of that holy love which may be acceptable in his sight.`"

She expressed an earnest desire,
to be enabled to feel that she had undergone that great change which was necessary,
before she could be admitted to a state of happiness hereafter; adding impressively,
"`You must be born again;`" and that the declaration was to her one of very solemn import.
At another time she remarked: "`We must always remember,
it is not enough to have our affections loosened from earth,
they must be fixed in heaven.`"

At one time, in the course of her illness,
she experienced a withdrawing of the Divine consolation so generally afforded;
but it was soon succeeded by a return of peace and assurance which never forsook her.
She regretted the loss, which she believed she had sustained,
from a lack of more frequent self-examination, and remarked: "`I want all to go to rest:
I do not mean a false rest; but to cast all our care on Him who cares for us.
We have been mercifully, very mercifully cared for, many years.
I am enabled, and I have no doubt I shall be enabled,
fully to resign myself into the hands of the Lord;
let Him do with me as seems good in his sight.`"

Speaking of a fear which she felt,
lest the peace and assurance which covered her mind might arise from a false confidence,
her sister remarked, that it was, without doubt, the small, still voice of the Savior,
that so wonderfully supported and calmed her.
She replied, that she believed it was that blessed voice which spoke peace,
and that it demanded all her gratitude.
She said to those who were about her, at another timer:
"`If the Redeemer call me home to Himself, oh! what a debt of gratitude.
Not that I have felt a wish to leave you:
it would have been very pleasant to me to have been with you; but,
whichever way it may terminate, I desire to be thankful.
These light afflictions, which are but for a moment,
work for us a far more exceeding and eternal weight of glory.`"

A calm serenity, in a remarkable manner covered her spirit,
when the solemn close of life drew near;
and under its peaceful influence she was mercifully permitted to enter,
we may humbly trust, into that rest which her soul had earnestly desired.
