== Chapter 12

[.chapter-synopsis]
* Mary Proud
* John Conran
* Mary Fairbank
* Deborah Backhouse
* Elizabeth Bludwick
* Ruiter Sholl
* Containing Brief
* Susanna Whitrow

MARY PROUD was born in the Fourth month, 1742, at Ross in Herefordshire.
She was the daughter of Rowland and Elizabeth Jones,
who were Friends of exemplary conduct; her mother was a minister in good esteem.
Being left a widow with four small children,
and only a little business for their support,
she consented to part with her daughter Mary, when about fifteen years old,
who came to reside with a near relation in London.
While there, her youthful mind, through unwatchfulness and the prevalence of temptation,
was captivated with the delusive vanities of the present life.

Being, at times, subject to the company of some who did not profess with Friends,
in her twentieth year she accepted an offer of marriage from a young man,
not a member of our Society, but a sober, religious character,
with whom she lived about five years.
But it pleased Divine Wisdom to mar her pleasant prospects of happiness in this life,
for in the short space of four months,
an affectionate husband and their two children were taken off by death.
Thus rendered desolate, she felt as one without hope,
and her inward and outward afflictions considerably impaired her health.
But as she patiently submitted to the chastening of the Lord, she was comforted,
and through the redeeming influence of a Savior`'s love, she witnessed,
in an unexpected season, the weight of her transgressions to be removed,
and her mind became settled in a peaceful calm.

The subject of this memoir, now Mary Malham, left London, and returning to Ross,
was joyfully received by her valuable mother.
Her mind was about the same time,
strongly impressed with an apprehension that she was called to the work of the ministry;
to which, after passing through deep baptism of spirit, she gave up,
as one who was made willing in the day of the Lord`'s power.
Some years afterwards, in the year 1775, she was united in marriage to William Proud,
of Hull, where they resided for many years;
but towards the decline of life removed into Essex.
Shortly after this she was again left a widow,
and survived her husband upwards of twenty years.
At different periods of her life, she visited as a minister various parts of this island.
In this character she was patient in exercise and deep in travail,
for the arising of the Divine power;
being concerned not to speak but from the renewing of the Holy Spirit.

She was endued with a good natural understanding,
which inclination and a sense of duty led her to cultivate by reading and meditation:
this rendered her an instructive companion:
and being affable and courteous in her manners, she was much beloved.
As her heart was enlarged by Christian love,
her desire for the temporal and spiritual welfare of all was manifested,
and this was shown in an especial manner,
by the interest which she discovered in the advancement of the kingdom of Christ,
both at home and abroad.
She was much concerned for those under suffering,
contributing liberally for their relief.

In the Fifth month, 1823, while engaged in the ministry in a monthly meeting at Halstead,
Mary Proud was perceptibly affected with paralysis.
She was removed home that afternoon, but was unable to speak:
the composure of her countenance, and other tokens of mental introversion,
showed that her affections were fixed on heavenly things, to the enjoyment of which,
if in accordance with the divine will,
she greatly longed that her spirit might be speedily admitted.
When the faculty of speech returned,
it was employed on subjects appertaining to the great work of salvation.
To a friend she said: "`I am thankful that the enemy is turned backward.`"
These few words she revived in the hearing of many visitors,
affectionately entreating her younger friends that they would, through Holy help,
withstand his suggestions,
when they would witness all the snares laid for them to be broken; adding,
in the language of encouragement: The city, the strong city!
The city, the strong city! flee unto it!`"

From this state of weakness this dear ancient friend so far recovered
as to be generally able to attend meetings at and near home,
and also the two succeeding yearly meetings in London;
yet she experienced considerable bodily infirmity,
which was endured with Christian resignation.
On the 3rd of the Fourth month, 1826, the monthly meeting occurred at Kelvedon,
the place of her residence.
In the meeting for worship,
she was strengthened eminently to advocate the truths of the Gospel;
but returned hoi::e much exhausted, before the meeting for discipline was concluded,
remarking, "`That it would be the last.`"
Soon after this, her debility greatly increased;
yet she came down stairs until within a week of her death,
and felt satisfaction in receiving the visits of her friends.

During this last and short illness,
deep and proving were the spiritual conflicts which
Infinite Wisdom permitted her to pass through.
But after a season of mental trial, she spoke as follows: "`My God, my glory! this,
not in the letter, but in the spirit: how precious the feeling!
My God, my glory!
I have mourned his absence.
He regarded it, and regarded me, though I felt myself entirely unworthy of Him;
but he is returned, and I can now sing of his goodness from my youth up,
and speak to his praise.
Oh! his mercies have been beyond all count, daily, hourly,
and oftener than the hours of the day.`"
Saying at another time, "`I believe in that testimony, '`Having loved his own,
He loved them unto the end.`'
There seems nothing in the way: do not desire my life, but pray for my release:
though my sufferings are great,
yet they are as nothing compared to the joys in prospect-endless joys.`"

The last day of her continuance on earth, she remarked:
"`This is my dying day;`" and in the forenoon, being raised in her bed,
a solemn silence prevailed,
under which she breathed forth a few sentences with feeble accents.
First, a song of thanksgiving for the precious in-breaking of the Divine presence,
previous to the putting off of mortality; a humble petition,
that the blessing of heavenly preservation might rest upon survivors;-and concluding
with the solemn ascription of praise unto Him who is everlastingly worthy.

Her peaceful close took place the same night, the 23rd of Fourth month, 1826,
at the advanced age of eighty-four.

[.asterism]
'''
JOHN CONRAN was born in the city of Dublin, in the year 1739.
His parents professed with the established Church of England,
and being in easy circumstances, they provided him with a liberal education,
and afterwards placed him as an apprentice with a person in the linen trade at Lisburn.
In this situation he was much exposed to unsuitable company,
and drawn into many youthful dissipations,
for which he was in mercy soon permitted to feel condemnation;
and being led to examine himself, his secret breathings began to be after God.
He became more diligent in the attendance of public worship,
and zealous in those practices and observations in which he had been educated.

But he still found that he had to lament over the evils of his own heart,
and to see that he had not attained to that knowledge of God, and that inward purity,
which he considered as essential to a truly religious life.
He secretly cried for deliverance; sin became a heavy burden;
he gradually forsook the amusements in which he had indulged; sat much alone;
and in reading the Holy Scriptures,
they were often made a means of comfort to his tribulated soul.
Thus, in stillness and retirement,
he was led into an increasing dependence on Divine instruction.

While in this awakened state of mind, when about the thirty-third year of his age,
he attended a quarterly meeting of Friends at Lurgan,
where he was affected in an extraordinary manner by the ministry of Robert Willis,
of America, who was then on a religious visit in Ireland.
Although on terms of intimacy with several members of our Society,
he had previously felt dissatisfied with our principles;
but now the power of the Lord so broke in upon his soul,
that his views were completely changed,
and under a firm conviction of the rectitude of the measure,
he soon afterwards fully embraced the doctrines and views of Friends.
This, however, occasioned him many deep conflicts of spirit.
He often looked back on his former course of life,
and felt the Divine judgments for transgression: thus,
having experienced the terrors of the Lord for sin, he became willing to persuade men.

In the year 1780, John Conran first spoke as a minister of the Gospel.
Being deeply impressed with the solemn nature of the engagement, he was concerned,
in the employment of the gift entrusted to him,
to move under the influence of the Holy Anointing;
and continuing in watchfulness and humility, and in reverent waiting upon God,
his ministry was often delivered under the baptizing
power of the High-Priest of our profession.
Although he frequently spoke but for a short time, it came with Divine authority,
conveying counsel and reproof to the disobedient,
and comfort and strength to the drooping mind,
and to such as were seeking the way to the kingdom of heaven.
He had, at seasons, to endure great poverty of spirit,
and in this way was experimentally qualified to speak to this condition in others.
The doctrinal truths of the New Testament were often the subject of his communications:
he was concerned to draw his hearers from all types and shadows,
inviting them to Christ the substance,
by whom the true and faithful believers being nourished,
are enabled to die daily to the impurities of flesh and spirit,
and to live unto God through Him who died for them.

In the exercise of the discipline of our Society, our departed friend was very useful.
He was zealously concerned for the support of our religious character as a body,
in its original purity,
and for the preservation of his fellow-members in soundness of principle,
and consistency of practice.
Through the aid of Divine grace,
he stood with Christian firmness against that spirit of unbelief
which at one period was very prevalent in the north of Ireland,
when many in our religious Society sorrowfully departed from the truth as it is in Jesus.
This was a time of great distress to him;
but he was emboldened to avow and to maintain his belief in the
efficacy of the propitiatory sufferings and death of Christ,
of the redeeming power of our blessed Savior; and under all,
gave abundant proof that his first desire was,
to be found faithful to the commission which he had received,
as a good steward of the manifold grace of God.

He scrupulously allotted a portion of each day to religious retirement,
and endeavored also to maintain, in social interaction with his friends,
a watchful attention to the guidance of the Holy Spirit.
His conversation was thus sometimes rendered strikingly instructive; yet,
when to others he might appear to be highly favored, he often remarked, in true humility,
that he was but an unprofitable servant;
that to him belonged nothing but blushing and confusion of face.
He was a man of a grave and serious deportment,
endowed with a good understanding and sound judgment;
and his advice in matters of importance was much valued.
He labored fervently to impress upon his friends,
the necessity of not being conformed to this world;
and illustrated this doctrine by his own example,
sacrificing things of a secular nature which stood
in the way of performing his religious duties.

In the year 1805, he was deprived by death of an amiable and tenderly-beloved wife; this,
with other subsequent domestic afflictions, of a peculiarly trying nature,
he was enabled to bear with Christian resignation.

He repeatedly visited the meetings of Friends in Ireland,
and was diligent in attending all those for discipline of which he was a member;
and was several times at the yearly meeting in London.
In the autumn of 1819, when nearly eighty years of age,
he united in a religious visit to the families of Friends in the city of Dublin,
and was strengthened to perform this arduous undertaking
much to the satisfaction of his friends,
and the peace of his own mind.
In endeavoring to excite his brethren to greater devotedness to the service of the Lord,
he would say in substance, "`I serve the best of Masters, who,
I can testify from long and precious experience,
withholds no good thing from those who faithfully obey Him;
and though I have not allowed my outward affairs
to prevent me from attending to my religious duties,
yet even these have not prospered the less; for now, in my declining years, I am,
through mercy, favored, with more than a sufficiency,
having a little to spare for the relief of others.`"

During his long life, he was permitted to enjoy almost uninterrupted health;
and when the powers of nature were evidently giving
way under the pressure of advanced years,
his spiritual faculties were preserved in extraordinary brightness;
and the promotion of religion in our Society, and in the world at large,
was still dear to his heart.
His death, which was sudden, and rather unexpected at the time,
took place on the 14th of the Sixth month, 1827,
at the house of his kind friend Thomas Christy Wakefield, at Moyallen,
where he had resided for the last few preceding years.

The day before his decease, when in his eighty-eighth year,
he was at the week-day meeting, in which he was engaged in the ministry,
strongly pressing upon his friends to be diligent
in attending their meetings for worship and discipline,
and instructively commenting upon the parable of the supper;
warning them to be careful how they neglected calls from heaven; and saying,
in the course of his exhortation, "`I now again tell you, what I have so often declared,
that other foundation can no man lay than that is laid,
which is Jesus Christ;`" and when about to take his seat, he stepped forward,
and after a few words, closed with this devout acknowledgment,
"`For the many mercies I have received, I praise, honor and magnify, my God.`"

Thus terminated the Gospel labors of this aged and honorable valiant in the Lamb`'s warfare;
and there is no doubt, that through the redeeming mercy of Him whom his soul loved,
he has been admitted to "`an inheritance incorruptible, undefiled,
and that fades not away.`"

[.asterism]
'''
MARY FAIRBANK.
--In compiling this volume, an opportunity has been instructively afforded,
to survey the character of more than a few, who, from early to advanced age,
have endeavored to walk in the path of the just.
The lives of these have convincingly shown,
that there is an efficacy in the religion of Jesus, which sustains the faithful,
though tried disciple,
and enables him to look in humble faith to that Almighty Benefactor,
who richly rewards all that diligently seek Him.
Such may not have spoken of very bright prospects of future bliss; but the steady,
heavenward tenor of their course, has shown on whom their hopes of salvation were fixed,
and that to them the gracious promise was one of consoling reality,
"`Be faithful unto death, and I will give you a crown of life.`"

In this number may be included Mary Fairbank,
who died at the advanced age of eighty-eight.
She was the widow of William Fairbank, of Sheffield;
and they were both Friends highly esteemed in that meeting.
They early entered upon the narrow way which "`leads unto
life,`" and their affections being set on things above,
they were moderate in the pursuit of earthly possessions;
but being concerned to seek first the kingdom of heaven and the righteousness thereof,
found that all things needful were added.
They entertained their friends with much Christian hospitality,
and their house was especially open to such as were
traveling in the service of the Gospel.
They were of sound judgment, and were both in the station of elders,
and well qualified for usefulness in the conducting of the discipline.
A considerable portion of their time was also allotted to the service of the church,
in their own meeting, and in the large quarterly meeting of Yorkshire: a duty which,
when properly discharged, involves no inconsiderable occupation of time and talents;
while the right performance of it greatly contributes, under the Divine blessing,
to the well-being and prosperity of our Society.

Mary Fairbank survived her husband nearly twenty-six years, and though she deeply felt,
through the remainder of her life, the dissolution of this endearing tie,
she continued to cherish a lively interest in the welfare of her friends;
among other duties, watching over the ministry,
and encouraging and counseling the young and inexperienced, as a mother in Israel.

Her frank and courteous manners,
and liberal sentiments towards those who differed from her in religious profession,
were striking and attractive.
Her labors of love were not confined to our Society;
but her charity and sympathy extended to those whom she knew to be in suffering.
To the poor-around her she was a kind and feeling friend,
and a promoter of various useful establishments for their good;
and many years before the education of their children
became so popular as we may rejoice that it now is,
she exerted herself in this benevolent work.

She had seen great changes in the meeting of which
she had been a member nearly seventy years;
and survived most of those with whom she had been
associated in the more active years of life.
The loss of these did not bring with it gloom or repining;
and she found in others less advanced in age,
those whose Christian friendship she valued,
and to whom her society and example were animating and instructive.
That humble trust in God, which had been her support through life,
was mercifully continued, and was an anchor to the soul.
Her energy of mind and cheerfulness of disposition were but little, if at all, abated.
She took a lively interest in what was passing;
and it afforded her sincere delight to hear of devotedness
to the service of her Lord and Savior,
both in and out of our religious Society.
She was, at the same time, no stranger to conflicts of spirit on her own account,
and not insensible to the trials and sorrows which
the faithful followers of Christ have to endure,
in mourning over those who do not come up in their ranks in righteousness,
or who fall away from that to which they had attained.

As the termination of life approached,
her tranquillity under the trials incident to humanity,
gave fresh evidence of the certainty of that support on which she had long depended.
Her mind appeared not infrequently to be borne above the infirmities of advanced age;
and gratitude and praise were often the prevailing feelings of her soul;
at the same time she manifested great humility, often saying,
that she had nothing to boast of;
but to feel no condemnation was a favor for which she wished to be sufficiently thankful.
Thus waiting the Lord`'s time, she died on the 22nd of the Sixth month, 1827.

[.asterism]
'''
DEBORAH BACKHOUSE was the daughter of Richard and Elizabeth Lowe, of Worcester.
Being deprived of her father at a very early age,
the care of her education devolved solely upon her mother,
who was piously concerned to train up her children in the right way of the Lord:
desiring much more that they might become possessors of heavenly riches,
than of any thing of a perishable nature.

The tendency of Deborah`'s mind is said, by herself, to have been such as to require,
in early life, much parental restraint;
and she has often feelingly acknowledged the benefit she derived from it,
and the influence which her mother`'s Christian example
and instruction had upon her future character.

When about twenty-five years of age, she had a serious attack of pulmonary disease;
and though evidently not then a stranger in the school of Christ,
there is reason to believe,
that this dispensation tended to deepen her in religious experience.
By continued submission to the baptizing power of the Holy Spirit,
she was prepared to labor for the edification of others,
and spoke first as a minister in the year 1819.
Her communications were neither long nor frequent; but they were clear and instructive;
manifesting great care that she might not minister otherwise
than through the ability which God gives.

In the year 1822, she was married to James Backhouse, of York.
Her delicate state of health often rendered her incapable of much active exertion;
yet her zeal for the cause of Truth showed itself by acceptable gospel labors,
and a humble, watchful deportment.
She was diligent in attending to the state of her own family,
and endeavored to suppress in her children, from very early life,
the appearances of self-will,
being mainly anxious that their tender minds might
be imbued with the fear and love of God.
In the management of domestic affairs she was orderly and industrious, rising early,
and directing her household by the law of kindness and discretion.
She was diligent in perusing the Holy Scriptures,
and particularly careful that the servants should not be prevented
from attending at the daily reading of them in the family.

After the spring of 1827, she was unable to attend our religious meetings;
and in the course of the summer and autumn, her disorder, which was a consumption,
made considerable progress, and left but little hope of recovery.
In this prospect,
she was for a time tried by the absence of that sense
of Divine support which she had often experienced,
and felt incapable of attaining that state of resignation which she so much desired.
But she was enabled patiently to wait upon the Lord,
and He was pleased to strengthen her cheerfully to adopt the language, "`Not as I will,
but as You will.`"

During the last month of her life, while her bodily strength was decreasing, her hope,
and faith, and love, became stronger;
and she spoke much on what the Lord had done for her soul,
and earnestly exhorted those around her to take up the cross of Christ,
and attend to the manifestations of his Spirit.
At one time she said, "`I feel myself to be a poor, weak creature,
nothing but a poor worm; and that it is through Divine grace alone,
as it has been measurably attended to, that I have been made any way tolerable.`"
She then earnestly enjoined all around her,
to be very careful not to say a single word that
could possibly attribute any thing to her;
again emphatically saying: "`I am nothing at all but a poor worm:
I have not one scrap of my own; no, not one scrap to trust to.
It is of Divine grace and mercy,
that I am permitted to feel such a portion of inexpressible peace.
For some time past I have seemed free from condemnation,
and have felt comfort in having endeavored to serve the Lord,
and in doing the little I have been enabled to do for the cause of Truth.`"

She spoke of her deep concern,
that her beloved children might be trained in the fear of the Lord,
and instructed in Divine things; that their tender minds might be closely watched,
and everything withheld from them which would encourage pride,
or any other wrong disposition: remarking,
that she considered children as a very important charge,
and that a great weight of responsibility attached to patents to whom they were committed.
She spoke much on the necessity of keeping to the simplicity of Truth,
in what may be termed little things; saying,
"`I have seen and found that nothing else will do.`"
She longed, that if her dear children should live to grow up,
they might be made as lights in the world;
and said that she had never desired much of this world`'s goods for them,
but only a sufficiency to live in a plain way; that she dreaded the idea of riches,
knowing they were often a great source of temptation.
She then committed her beloved husband and children to the care and keeping of the Lord.

During most of the day preceding her death,
she seemed as if on the confines of eternal glory,
and her hands and eyes were frequently raised in the attitude of adoration.
On several of her relations, and a few other friends coming into the room,
a solemn silence ensued, which she broke by the following expressions,
in an audible voice, "`Surely I believe that the everlasting arms of God,
through Jesus Christ my Savior, are stretched forth to receive me.
I feel the showers of heavenly love falling around us.
What can be comparable unto this!`"
After another pause, she said:
"`I have a clear view of the outward sufferings of our blessed and holy Redeemer.
Oh! let me adore!
All this for poor, fallen, lost man, that he might be saved.`"
Being requested to take a little water, and finding great difficulty in swallowing,
she said with a sweet and animated countenance:
"`I shall soon be led to living fountains of water,
where I shall drink everlastingly without fear of difficulty.`"

After this she was brought under considerable exercise of mind,
and expressed a belief that it was right for her
to wait "`in the Light,`" to discover the cause.
In a short time she remarked,
that there were some little things in her own house and family,
which were not enough in the simplicity that Truth requires,
which had she been sufficiently attentive to the manifestations of Divine light,
would not have been given way to.
She appeared closely to scrutinize every little thing; and again testified,
that if the light were attended to,
it would clearly show what was or was not in conformity to the Divine will.
She acknowledged in a humble, moving manner,
her regret at not having been more faithful in these matters, saying: "`Yes, Lord, I see;
and if I had paid more attention to the Light, I should have seen long since.
I do most sincerely repent and implore your forgiveness.`"
Some time after, she remarked to her husband,
that she again felt the showers of heavenly love descending as before.

In the course of the night, she fervently supplicated thus:
"`O gracious Father! be pleased to help me in this trying hour,
and be near to preserve and support me from bringing
any shade upon your holy Truth;`" adding,
shortly after, "`I believe You will not leave me nor forsake me unto the end.`"

In the morning of the following day she said to one of her husband`'s sisters:
"`O! my dear sister, help me to praise the Lord,
for He has given me the victory over death, hell, and the grave.`"
During the remaining time of her continuance, it appeared as if all was joy and peace,
not interrupted even by bodily suffering.
She passed quietly away, on the 10th of the Twelfth month, 1827,
at the age of thirty-four; and her spirit was added, we cannot doubt,
to the redeemed of the Lord.

[.asterism]
'''
ELIZABETH BLUDWICK, wife of John Bludwick of Warrington, was a native of Cheshire.
In early life her deportment was serious and orderly;
and through the influence of Divine love she became, when further advanced in years,
more deeply impressed with the importance of her eternal interests;
and by increasing attention to the teachings of the Holy Spirit,
she grew in religious experience.

She and her husband were both much esteemed by their friends,
for their conscientious endeavor to walk as became their religious profession;
and for their devotedness to the service of our Society,
and their lively concern for the support of our discipline.

Elizabeth Bludwick was at times concerned to labor as a minister in our religious meetings.
Her communications were not long;
but they were expressed under the influence of Gospel love, and very acceptable.
She had often to recommend inward waiting upon God, and dedication to Him;
engagements of mind which, she could say from experience, had been blessed to her.

For many of the latter years of her life, she suffered much from bodily disease;
but her patience and sweetness of spirit increasingly endeared her to her friends.
She survived her husband about two years; and though in advanced life,
and in a very weak state of health, frequently attended her own meeting.
She often expressed her desire to be able to bear her suffering with patience;
and though tried with poverty of spirit and a sense of her own unworthiness,
it was obvious that she was often favored with a
consoling evidence that her gracious Lord would,
in his own time, remove her from her present conflicts and sufferings,
to an inheritance in his heavenly kingdom.

On the 7th of the Twelfth month, 1827, she remarked:
"`I wish the friends of this meeting to be told,
that there is a new song for the righteous, a song of praise:
salvation has God appointed for walls and for bulwarks.`"
To a friend who called to see her, about three weeks before her death,
she expressed her desire to be dissolved, and said, "`Oh! that I had the wings of a dove,
that I might fly away and be at rest.
I have a well grounded hope, that whenever I put off mortality,
I shall put on immortality and eternal life,
and that this will be my portion and habitation forever.`"
Being in extreme pain, she prayed, "`O Lord, if it be your blessed will,
be pleased to send the guardian angel of your presence,
to conduct my poor soul to its mansion.
You only know my sufferings, and are able to deliver me out of them all.`"
On another occasion, she intimated, that her being saved was of mere mercy,
having no righteousness of her own to depend upon.
When it appeared probable that she would not continue much longer, she observed:
"`I shall die in peace with all, feeling inexpressible love to every one.`"
And again, she said: "`Now, Lord, let me depart in peace,
for mine eyes have seen your salvation.`"

In this heavenly state of mind she was permitted to look towards
an exchange of the trials of time for a peaceful immortality.
She died the third of the First month, 1828, at the age of eighty.

[.asterism]
'''
RUITER SHOLL, son of John and Elizabeth Sholl, of London,
was educated at Ackworth school; and in the Eleventh month, 1824,
was bound an apprentice to Joseph Hargrave, of South Shields.
In the early part of the time of his apprenticeship his conduct was very satisfactory,
and he highly valued his situation.
At South Shields no members of our religious Society resided,
except those of his master`'s family; and as he grew up,
he became acquainted with other young persons,
and showed some unwillingness to submit to the restraint
which a conscientious master thought it right to exercise:
at the same time, it does not appear,
but that his general conduct was such as to ensure
to him the esteem and regard of the family.

In the year 1827, he became unwell from the effect of cold,
and the complaint gradually settled on his lungs.
In the Sixth month he came to London; and in the course of the summer and autumn,
various means were tried to promote his recovery.
Towards the latter end of the year, some amendment took place;
but it was only of short continuance,
and it became obvious that he could not long survive.
Up to even so late a period,
very little had been said to him of the danger of his situation,
and he evidently appeared to avoid any conversation of a religious nature.

In the course of the Twelfth month, a kindly interested friend called to visit him,
who found him very weak, suffering from acute pain in the chest,
and his appearance indicated the near approach to the house appointed for all the living.
He received the visit with marks of satisfaction.
The family were collected, and a portion of Scripture was read:
feelings of great solemnity prevailed,
and the visitor felt it to be his duty to apprize the invalid of his condition,
expressing an earnest solicitude that the great work
of sanctification and redemption might be effected;
and turning the attention of his young friend to Him from whom saving help comes;
to the sacrifice of Christ, and the meditation of a crucified Savior.

From this time, his mind was much occupied with the prospect of death:
the certainty that his immortal spirit must soon quit its earthly tabernacle,
and appear before its Almighty Judge, deeply affected him;
and he ardently desired to be prepared for the final change.
Although he was enabled to state,
that he had been preserved from the commission of any "`gross sin,`" yet his
associating with some whose conduct was not under the control of religious principle,
had tended to lead him astray from obedience to the
will of God inwardly made known unto him;
and the consciousness of moral rectitude alone,
was insufficient to support his mind at this solemn moment.
Excellent and indispensable as morality of life is,
it is only as we come to pass from a state of nature to a state of grace,
and our souls experience the renewings of the Holy Ghost,
that our conduct among men will redound to the glory of God,
and be viewed with acceptance in his pure and holy sight.

Great were the sufferings in spirit which this young man had to pass through;
forcibly pointing out to those around him,
the necessity of submitting to the power of the cross of Christ.
While under these inward baptisms, he received a visit from two friends in the ministry,
who expressed their belief, that, through redeeming mercy,
a place of rest was prepared for him;
but notwithstanding their bright prospects concerning him,
his soul continued to be deeply tried.
He was often engaged in mental supplication,
and besought his Heavenly Father to permit him to see a little light upon the path.

These trials and conflicts of mind continued until First-day,
the 13th of the First month, 1828, when, in condescending mercy,
the cloud of distress and doubt was dispelled, and the cheering prospect presented,
of an admittance into a mansion of eternal rest.
His mind became composed and tranquil.
He spoke to his parents, brothers and sisters, in terms of gratitude,
and of solicitude on their behalf; saying at one time to his mother:
"`My dear and tender mother, do not grieve for me; but think of the blessed change,
when I shall be freed from my bodily sufferings,
and be permitted to have a mansion in heaven, where I shall behold my Savior`'s face,
there to join with angels, in singing hallelujahs forever and ever.`"

He was now so weak, that he could scarcely raise himself in his bed without assistance,
and he often begged to be released.
The fear of death appeared to be taken from him,
and he could look forward without dismay,
being comforted in the hope that all would be well; often saying:
"`Oh! that my hour were come: I want to be gone.`"
He was much interested on behalf of one of his school-fellows,
and on one occasion said to him in substance: '`Be very guarded in your conduct;
the enemy is constantly devising mischief.
You are in a very dangerous and critical situation; lay your soul open to your Redeemer,
and put your trust and confidence in him.
I am going to where I shall behold the face of my Redeemer.
He has guarded and watched over me.`'

He frequently said with much feeling: "`Oh! for patience.
Father of mercies, grant me a little ease.
Oh! grant a little ease; and if it be consistent with your gracious will,
preserve me in patience to the end.`"
At one time, when his parents and a friend were present,
in feeble accents he besought the Almighty to have compassion upon him, saying:
"`Have compassion upon me, a poor sufferer;
and if it be consistent with your good pleasure, take me to Yourself.
Wash me, and make me clean in the blood of your dear Son;
and do You be pleased to take me to Yourself.`"
He also prayed on behalf of his beloved mother,
and concluded with grateful acknowledgments for the
blessings which had been bestowed upon him.
At another time, he said to one of his brothers:
"`I am now favored with a clear prospect that when the change shall take place,
there is a mansion prepared for me in the kingdom of heaven.`"

To a friend, who called upon him a short time before his death,
he conversed on his having been placed at a distance from home; saying,
that he had felt much exposed, and, as it were, alone;
but that he was favored with preservation from many of the vices which he saw around him,
for which he felt very thankful: adding, that he recollected, when walking out alone,
he frequently endeavored to look forward, and form plans for the future,
when out of his apprenticeship;
but that upon these occasions he always felt a check in his mind,
so that he could not proceed, of which he now clearly saw the cause.
Speaking of his approaching dissolution, he remarked,
that he felt no obstacle in the way; but that his desire was,
to be favored with patience to await the time.

In this state of mind, and with but little apparent alteration,
he continued until the 20th of the First month, 1828.
Having passed a restless night, he was much exhausted,
and requested to be placed in an easy chair.
Soon afterwards he was heard to say: "`If consistent with your holy will,
be pleased to release me from my sufferings, and take me to yourself.`"
He then raised his eyes, and faintly uttered: "`It is done,
oh! it is done`" and thus passed peacefully away.

He was in the nineteenth year of his age, and,
until the period at which he was attacked with cold,
enjoyed an almost uninterrupted share of health.
The prospect of such an early termination of his earthly course,
appears to have been far from his thoughts.
Let us, then, who survive, seriously reflect upon the uncertainty of life,
and the awful situation of such as are suddenly called hence in an unprepared state.
And although there is good ground to believe this was not the case
with him whose steps we have briefly traced to the hour of death;
yet, had he attended more early and diligently to the visitation of the love of God,
and the reproofs of his Holy Spirit,
he might have escaped much of the distress through which he had to pass.

Other instances have been set before us in this volume,
which show that none ought to presume on lengthened days.
We are not to expect favor or acceptance with God, if we continue in sin:
the forgiveness which has been mercifully granted to others,
is no security that it will be alike extended to us.

May all, then, seek with increasing diligence,
an establishment upon the sure and immutable foundation, Jesus Christ, the rock of ages,
who lives and abides forever!

* * *

APPENDIX TO PIETY PROMOTED
CONTAINING BRIEF BIOGRAPHICAL NOTICES OF SOME OF THE MEMBERS
OF THE RELIGIOUS SOCIETY OF FRIENDS.

BY WILLIAM AND THOMAS EVANS.

"`Not by works of righteousness which we have done,
but according to his mercy he saved us by the washing
of regeneration and renewing of the Holy Ghost;
which he shed on us abundantly through Jesus Christ our Savior;
that being justified by his grace we should be made
heirs according to the hope of eternal life.`"

PREFACE

THE following accounts have chiefly been compiled from a,
collection of memorials published in the last century under the
direction of the yearly meeting of Friends of Philadelphia.
As the narratives in the preceding pages of Piety Promoted principally
relate to persons who lived in Great Britain and Ireland,
it has been thought that some addition respecting individuals in our own country,
would be acceptable in an American edition.
The volume which has furnished the materials for most of them has some prefatory remarks,
which may be appropriately introduced here.

Those who have departed hence in the Lord,
can receive no addition to their happiness by any testimonial of their surviving friends,
however just; yet to the wise in heart,
precious is the memory of the truly pious and upright,
whose humble walking in the fear of God has livingly witnessed
against the appearance of evil in its various transformations;
their conformity in spirit and practice to the holy law of the Lord,
evincing the delight and benefit to be found therein;
for "`Verily there is a reward for the righteous,
verily he is a God that judges in the earth.`"

"`What scene in this life more dignifies humanity;
what school is more profitably instructive, than the deathbed of the righteous,
impressing the understanding with the convincing evidence,
that they have not followed cunningly devised fables, but solid substantial truth;
and that there is a measure of divine light and grace in man,
which if duly minded and obeyed,
is sufficient to preserve through all the vicissitudes in life,
to give him the victory over his spiritual enemies, and in the end over death, hell,
and the grave.`"

It is right therefore, that the remembrance of those should be preserved,
whose lights have so shone before man as to incite
the beholders of their good works to glorify God,
the original and source from whom all good is derived, that though being dead,
the luster of their pious example through life, and on the approach of death,
may continue to display the inviting language, "`Follow us as we have followed Christ.`"

Some of the readers of the following narratives will be
reminded of the sincere piety and virtue of their ancestors,
who through the dangers and difficulties to which they were subjected,
in their removal from their native land, and forming a new settlement in a wilderness,
were happily preserved in a steady attention to their religious duties,
and many of them faithfully engaged in promoting
the cause of truth and righteousness among mankind.
To these, others succeeded, who,
through obedience to the powerful influence of Divine grace,
became alike eminent in their day, and serviceable in the church.

The following collection is affectionately recommended to the descendants of those worthies,
to the readers in general, and particularly to the youth,
who may derive profitable instruction by a serious observation
of the happy effects of an early devotion of the heart to God,
and the inexpressible advantages of embracing the merciful
visitation of that compassionate Savior who died for them,
in order to secure their true comfort in this life,
and enduring felicity in that which is to come.

Though the language and style of these memorials
may not be calculated to please such curious readers,
who, in their estimate of the value of a book,
are too much amused by the display of wit and literary accomplishments in the composition,
to give due attention to the instructive import of an artless account of the
Christian experiences of those who have not been so solicitous for the approbation
of men as to be found humble followers of Christ Jesus the Lord,
their meek and lowly pattern, and omnipotent Redeemer;
yet it is hoped that there are many to whom the contents
of this Collection will afford information,
edification, and encouragement in the pursuit of their most substantial interest,
a life of true wisdom, piety, and virtue;
and that the number of such may increase is the design of this publication.

[.asterism]
'''
SUSANNA WHITROW was the daughter of Robert and Joan Whitrow, of Covent Garden,
in the county of Middlesex, England.
Her father does not appear to have been a Friend, and he,
with several other members of the family,
seems to have lived in the corrupt ways and fashions of a world that lies in wickedness,
in opposition to the counsel, and greatly to the grief of Joan Whitrow,
who was a woman of true piety and self-denial,
much concerned for the best welfare of her family,
and one of the people in scorn called Quakers.
T

heir daughter Susanna was taken sick the 5th of the Third month, 1697,
and lay until the ninth day,
under the judgment and terrors of the Lord for sin and iniquity.
About four o`'clock in the afternoon she broke forth with great earnestness,
crying to the Lord for mercy, l Lord, are my sins forgiven?
Had not mine eyes seen those vanities, my heart had not gone after them:
shall I have no help for my distress?
Strengthen me but to see my desires;`" with other
similar expressions for about three hours,
when the Lord was pleased to hear and answer the desire of her soul.
Having thus obtained mercy for herself,
she fell into a fervent travail of spirit on behalf of her father,
praying after this manner: "`Lord, remember not his offenses, let me bear them,
make his friends to be his enemies, that you may have mercy on him: carry him through,
and let him not perish with the world.
Blessed Lord, hear me, leave me not unsatisfied, but grant my request.
Set his mind on things above; turn him, and he will be turned.
There is no way for him but to watch and pray continually, lest the tempter prevail.`"

Then addressing her mother, she said, "`Oh! my bowed down mother!
Oh, my bowed down and brokenhearted mother!
What have been your sufferings in this family!
Oh, how have you been oppressed with our iniquities!
Ah, how often have you told my father,
the Lord would visit him with sore and grievous judgment
if he did not repent and turn from the evil of his ways!
How often have you said, the Lord would plead your righteous cause with us!
Now the day is come you have so long warned us of; now the Lord is broken in upon us.
Oh, how great have been your care and pains,
which you have taken to bring us into the fear of the Lord!
Oh, you blessed of the Lord! great shall be your reward.
The Lord will give you beauty for ashes,
and the garment of praise for the spirit of heaviness: you are blessed, my mother.`"

Her mother being at that time praising and magnifying the Lord, she said,
"`My blessed mother, now is that vision fulfilled,
which the Lord showed you concerning me, that my soul should bless you,
and your soul should bless the Lord.`"
Then she broke forth into sweet melody, singing praises unto the Lord.
"`Blessed are the poor in spirit.
Lord, I am poor, I am needy, I need your strength continually to withstand the tempter.
O Lord, stand by me, move not from me; for if you go, the tempter will come.
I will hold you fast; you are my Savior; you shall save me from the tempter.
My dear mother, send for that dear friend, who prayed by me the other day.
She is a precious woman; her heart is upright before the Lord; he has showed it me.
I love her.
Let her pray by me to the Lord against the tempter.
And send for that servant of the Lord, W. P.;
the Lord will hear the prayers of the faithful; but I have been unfaithful.
Oh, how often have I sinned against my Savior,
whose light in my conscience showed me the way I should walk in!
How often has he knocked at my stony heart, saying,
This is the blessed truth which the Quakers preach,
by which all souls that I have made shall be saved!
Then have I said in my heart, After such a thing and such a thing is accomplished,
I will leave off my life of vanity, and become a new creature.
Oh!
I was she that trusted in lying vanities.
I thought I should have long life, and then I did intend to serve the Lord in my old age.

"`Oh, how I have been against a woman`'s speaking in a meeting!
But now, whether it comes from man, woman, or child, it is precious indeed.
O that I could be with my mother: the Lord is with her:
that I might have a little time longer,
that my dear mother and I might go in the country and walk in a wood together,
that we might seek the Lord until we have found him.

"`O Lord, my strength fails, I wait upon you, renew my strength:
be pleased to restore me to my former health, then will I wait diligently upon you.
I will sit on the ground, with my head in the dunghill.
I will never lift up my soul to vanity;
my heart shall never go after the sight of my eyes.
My dear mother, pray for me; for whatsoever you ask of the Lord, it shall be given you.

"`My dear mother,
you have often told us of the terrible and dreadful day of the Lord God that is at hand.
O, it will be a dreadful day to the wicked of all sorts, the Lord has showed it me.
Woe,-woe, to the children of scoffers! for as it was in Elisha`'s day,
so shall it be in this the day of the Lord`'s power
--the bears out of the wood shall devour them.`"
And trembling she said, "`I feel your terrible power, O God; strike dread, terror,
and astonishment in the hearts of your enemies, in all the workers of iniquity,
who make a derision of your people,
and take pleasure in the abominable ways which you abhor.
O my mother, I have heard God`'s thundering power rattle upon the heads of his enemies.
A woe will be to the children of pride in that day;
and woe will be to the blind guides that wear the long robes,
the false teachers of this nation.
Did not our blessed Lord say, if the blind lead the blind,
both should fall into the ditch?
Ah, Lord! how should it be otherwise?
for they hate the light, and count it an insufficient thing.
Did not our blessed Savior say, believe in light,
that you may be the children of the light?
and he bade them all watch and pray, lest they enter into temptation.
And how could they watch without the light?
for they could not see the tempter when he came in the dark.
Ah, that scripture is fulfilled upon this people, That darkness should cover the earth,
and gross darkness the people;
and then night should be unto them that they should not have visions,
and the day shall be dark that they shall not divine.
And this was Egypt`'s darkness.
Ah! but the children of Israel had light in the land of Goshen.
Extolled be your name, you God of power.
If you will be pleased to restore me to my former strength,
then I will speak of your wonderful power; yes,
my voice shall be as the sound of a trumpet, which shall convert sinners unto you; yes,
I will sit in the dust, and cover my head with ashes,
and put on sackcloth within and without.`"

Taking something to drink, she lay still a little time, and with joy in her heart,
made sweet melody to the Lord, but did not utter any words;
then she broke forth again in praising and magnifying his great works.

"`O that house of abominations, that play-house,
where they commit their abominable deeds, God will destroy it.`"
Her mother said, "`What house, my dear child?`"
She answered, "`That church, as they call it in Covent Garden,
the members thereof are proud persons, and covetous, and deceitful, liars, and drunkards.
Ah! my blessed Savior said, We should know them by their fruits.
O, these were my fruits which I brought forth when I was a hearer at that church,
pride and disobedience to my parents.
How often have I adorned myself as fine in their fashions
as I could make me! yet they have looked upon me with scorn,
and despised my dress, and said to me,
How you have dressed yourself! you are not at all in the mode!
Then I came home, and have gone immediately into my chamber, locked the door,
and altered all my laces; and so I have gone to their worship in their mode,
and then I have pleased them.
Pray, my mother, call my father; I have something to say to him.
I desire my body may not be laid in that abominable place,
but among the people of the Lord called Quakers.
Now I am a true Quaker, now I tremble before the Lord and his holiness.
Come, you holy prophets, who were quakers and tremblers at the word of the Lord; come,
Moses and Jeremiah; come, holy Habakkuk, now I am one with you: now my heart drops,
because of the Lord, and the greatness of his majesty.

"`O my Lord, yes, my Lord, for so I can call you, because you rule in me,
and my soul is subject to you.
But they have many lords and many gods; they have gods of silver and gods of gold,
the work of their own hands.

"`O my heavenly Father, I wait upon you; renew my strength, holy Father:
be pleased to restore me to my former health; then I will wait diligently upon you,
I will sit on the ground with my head in the dunghill,
my heart shall never go after the sight of my eyes.
My dear mother, pray for me; for whatsoever you ask of the Lord, it shall be given you.
The reason why I desire to live is,
because I have so greatly dishonored the Lord in my former life,
and now I would live the rest of my time to his praise;
for I shall be as one raised from the dead, to declare his wonders: but what shall I say?
Though one should rise from the dead, they will not believe.`"

She was exceedingly filled with the indignation of the Lord
against their idle practices and their abominable ways,
but her expressions were not taken in writing.
These words the maid-servant wrote down as she spoke them.
She cried out aloud, and said, "`Father, these priests deceive the people;
they study all the week what to say when Sunday +++[+++so called]
comes; but the day of the Lord is coming,
in which he will confound all their study and all their wisdom,
and in that day they shall not be heard for their much speaking;
they are physicians of no value.`"

"`My dear mother, I fear I shall not have a place so near the Lord as my soul desires;
for I am sensible, there are degrees of glory,
and as the creature acts here for the Lord, so shall its reward be hereafter.
I have done nothing for the Lord, but he has done all for me; therefore I desire to live,
that I might live a holy and righteous life, that my citizenship might be in heaven,
though my body be here on the earth, that I might invite all, as David did,
to taste and see how good the Lord is.
They have tasted of their perishing life of vanities, yes they have drank a full cup,
their measure is running over; but they never tasted the joys,
the unspeakable ravishments of soul that attend the humble, holy life of Jesus.
Oh! if they had ever tasted the least mite thereof,
they would bid adieu to all their life of vanity.
Ah, they would not dare to spend their precious time in adorning themselves like Jezebel,
patching and painting, and curling their monstrous heads.
The Christian life is another thing, they must not give themselves liberty.
to think their own thoughts, much less to act such abominations as these.`"

After she had lain awhile, praising and magnifying the Lord,
she spoke very deep and weighty things, which are not set down,
concerning the wise virgins and their lamps burning,
and exhorting all to keep very diligently upon their watch; "`for,`" said she,
"`the Lord will come as a thief in the night, and in a day when he is not looked for;
therefore watch and pray continually; here the tempter cannot enter.
This is the way my Savior spoke of when he said, you must take up your daily cross;
this is that flaming sword you must pass through, mark that, you must pass through it,
before you can come to the tree of life.
This is the cup my Savior asked if you could drink of,
and this was that baptism he asked if you could be baptized withal.
Come all you that call yourselves Christians, what of the life of holy Jesus is in you?
who was a man of sorrows.
You. light and airy ones, you wild and wanton ones,
you that are lovers of pleasure more than of God,
you workers of iniquity who are always crying Lord, Lord,
but do not the tlings that I say, this shall be your dreadful doom, that you are sayers,
but not doers: you workers of iniquity,
that think you can never have enough of the pride of life, the lust of the flesh,
and the lust of the eye, which is not of my heavenly Father,
and so you are of your father the devil, for his servants you are whom you obey.`"
At another time she said, "`I have heard them say,
that my mother is so grounded in her religion, that it is impossible ever to turn her.
My mother is grounded indeed, she is established upon the rock that shall never be moved:
my mother shall never be moved, her name is written in heaven, yes,
in the Lamb`'s book of life it is sealed: the Lord has told me so, and bid me tell her,
There should none be able to pluck her out of his hand.`"

"`Come, my blessed mother, I have something to say to you--you are Mary,
you have chosen that good part which shall never be taken from you;
you shall sit continually at the feet of your Lord, aye, this is my mother`'s portion: O,
what portion is like this?
this is more than to sit on the thrones of princes.`"

"`Be holy as I the Lord your God am holy: this they say is impossible.
O, would the holy, just and true Lord command that which is impossible?
In this they count the Lord a hard master.
But what can my soul say of your power?
When I sought you but could not find you, I knocked hard but none would open,
for my sins stood like mountains, that I could not come near you.
I would eagerly have prayed, but could not.
I lay several days and nights prostrate before you, struggling for life, but.
could find none; and I said, there is no mercy for me.
Then said I, I will never leave you; if I perish, I will perish here.
I will never cease crying unto you.
Then I heard a voice say, Jacob wrestled all night before he obtained the blessing.
O then your word was strength to my soul;
then my stony heart was broken to pieces before the Lord,
then the spirit of prayer and supplication was poured into my soul;
and now I can sing as David did of mercy and judgment.
Unto you, O Lord, will I sing: with a rent heart, and my mouth in the dust,
will I sing praises unto you, my blessed Savior.`"

For several days she had a very great conflict in soul and spirit concerning the tempter,
and strong were her cries to the Lord for strength to overcome the enemy.
She was so deeply engaged in the holy war of the Lord,
that she would not allow her head to be removed from her pillow, but said,
it must be as it were nailed there till she had overcome the tempter.
She said, "`I would not permit a thought to wander.
If I move I shall be drawn off my watch, and then the tempter will prevail.`"
Then she had a vision, and as it were the appearance of an angel,
giving us the full description thereof, which we have forgotten,
only that it was arrayed in white:
she had also a vision of the tempter which she said stood before her bound in chains.
Then she said, "`It is finished, I have overcome, my Savior has bound him.`"
She broke forth into blessing and praising and magnifying the Lord,
that it is beyond the power of language to give a relation thereof.
For many days and nights together she would hardly slumber,
but would waken herself to sing praises to the Lord,
and to declare of his wondrous works that he had done for her soul.

Some friends came into the room, but she saw them not:
and after many sweet and precious words, she said, "`Don`'t you feast, but fast and pray,
and be contented with mean things.
O what matter for fine houses or silken apparel!
Remember him who sat on the ground, and wore a garment without a seam, our blessed,
holy Lord, who went up to the mountain to pray,
and withdrew into gardens and desolate places of the earth;
my soul has fellowship with him.
O my dear mother, if it please our dear and heavenly Father to spare me this time,
we will get us into the country to some remote place, among the woods,
where none can hear us; then shall our cries pierce through the heavens,
and shall make the earth to ring, and the birds shall hear the echo thereof.
There my blessed mother, will we sing praises with rent hearts,
and our mouths in the dust, to the one, holy Lord.
O you glorious One, you have overcome my heart, you have ravished my soul.
You pure, holy One, what shall I say of you,
or what shall I render to you for your lovingkindness to me?
My heart is overcome with your love, praises be unto you for your lovingkindness to me.
How shall I do to set forth your goodness, for my heart drops before you?

"`Lord, if it be your holy pleasure to take me out of this life, then let me have,
I beseech you, one whole day, that my tongue may never cease praising you.`"
And the Lord answered her request.

All that day she was wonderfully filled with the sweet solace of the heavenly life,
singing praises and hallelujahs to the Lord, and spoke very much concerning the Lamb;
and of his followers,
who had washed their robes and made them white in the blood of the Lamb.
Towards the evening, while the power of the Lord was upon her,
there came in two persons to see her, when she uttered many precious, heavenly words,
and in great weightiness of spirit said, "`O Israel, what has your God done for you?`"
Then taking up a lamentation, said, What shall we do for the daughters of Jerusalem,
who are haughty, and go with outstretched necks and wanton eyes?`"

After several days lying in the sweet solace and heavenly life
of the Lord (in which time she uttered many heavenly things,
which were not taken in writing) she expressed these words,
"`O you beloved of my soul! what shall I say of you?
for you are too wonderful for me: praises be unto you.
Come all you holy prophets, '`praise the Lord with me: praise the Lord, O my soul,
upon the loud-sounding instrument; you glorious angels, that excel in glory,
sing praises to him that sits upon the throne.
O how am I overcome! you stones in the street why
rise you not up to praise him that lives forever?
O you light, praise you the Lord; and you darkness,
praise and exalt him above all things: you sun and moon,
you stars in the firmament of his power, magnify the Lord above all forever.
All you fishes in the sea, why come you not forth to praise the Lord, the mighty God,
who gives you breath and being?
I will praise you while I have any breath: praise the Lord, O my soul,
sing praises to the God of my salvation: my holy One, you have overcome my heart,
you have ravished my soul.
My dear mother, I shall be as a new born babe, I shall be very simple, but bear with me,
for the Lord is with me.

"`My dear mother, I must lay down this body,
the Lord will not trust me longer in this world; happy am I. My Savior,
my soul loves you dearly; your love is better than wine: my Savior, my holy One,
how glorious are you!
I have seen your glory; my heart is overcome with your sweet countenance.
O come away, why do you stay?
I am ready, I am ready.`"

After lying some time very still, she was heard in a heavenly harmony,
in which frame of spirit she departed without either sigh or groan, aged fifteen years.
