== Chapter 3

[.chapter-synopsis]
* John Estaugh
* Cadwalader Evans
* Willam Levis
* Evan Evans
* Alice Griffith
* Sarah Pleasants
* Ann Roberts
* Israel Pemberton
* Peter Andrews
* John Evans

JOHN ESTAUGH was born at Kelvedon in Essex, England, on the 23rd of the Second month,
1676.
His parents were pious persons, but not of the same religious profession;
and his mind being visited from on high, and brought into a tender, seeking state,
he could not unite with the way of worship practiced by either of them,
and for a time thought of joining with the Baptists.
Attending the funeral of a neighbor,
who was a member of the religious Society of Friends, Francis Stamper,
a gospel minister among that people, was led to speak with divine life and power,
directly to his state,
which made such a deep and lasting impression upon his visited mind,
that he was convinced of the principles of truth as held by Friends,
and united himself to them in the seventeenth year of his age.
Continuing faithful to the teachings of the grace of Christ,
it pleased the Head of the church to confer upon him a gift of the ministry of the gospel,
in which he experienced a growth,
and travelled much in the north of England and Scotland,
and in the year 1700 came to America to visit the churches.
He performed this service to the great satisfaction of friends,
and afterwards settled at Haddonfield, in New Jersey, where he married Elizabeth Haddon,
a worthy member of that meeting.

For some years after his marriage he was much engaged
in traveling in the work of the ministry;
being careful to yield to the drawings of the love of God,
whether in visiting neighboring meetings or those more distant;
and performed extensive journeys in Great Britain, Ireland, New England,
and some of the West India islands, several times.
He was a humble-minded, exemplary friend, solid and grave in his deportment,
well becoming a minister of Christ, zealous for preserving good order in the church,
and maintaining love and unity, that precious badge of discipleship;
remarkably careful in his conduct and conversation among men,
his words being few and savory.
He was a pattern of Christian moderation in all things,
not lifted up with any enjoyments, nor cast down with disappointments,
and endued with many good gifts, which rendered him very agreeable to his friends.

After enduring a state of ill heath which for several
years confined him at and about home,
he so far recovered as to be able to travel,
and feeling his mind drawn in gospel love to visit
the few friends on the island of Tortola,
after a season of deep and weighty exercise, he resigned himself to the service,
and having the unity of his brethren, he embarked with his companion, John Cadwalader,
on the 13th of the Eighth month, 1742, and arrived at the house of John Pickering,
a Friend residing in the island, on the 8th of Ninth month, following.
The subjoined account of him while there is taken
from a paper drawn up by one of the Friends:

[.embedded-content-document.paper]
--

They were received with much love and joy,
being made to rejoice together in the tender mercies and love of God,
which was manifested that day, to the honor and praise of his great name,
and also to the comforting of his poor people.
The testimonies of these servants of the Lord were with life and power,
and were as clouds filled with rain upon a thirsty land.

Your dear husband`'s memory is precious to me,
and many more whose hearts were open to receive the glad tidings which he brought.
His godly life and conduct spoke him to be a true follower of the Lamb,
and minister of Jesus Christ, whom he freely preached,
and by the effectual power of whose divine love he was called forth to our assistance;
for which we bless, praise, and magnify the God of all our mercies.
As a faithful messenger, with much love, in a tender frame of spirit,
would he invite all to the fountain which had healed him.
O! the deep humility that appeared in him in the time of his public testimony;
and when in private conversation with his near and dear friends,
as he often said we were to him,
how cheerful and pleasant would he be in that blessed
freedom wherein Christ had made him free.
Innocent, harmless, of a cheerful countenance, yet not without a Christian gravity,
well becoming the doctrine he preached.
He was valiant for the truth to the last, and though he is gone to his grave,
his memory is sweet and precious.

He had his health very well until the death of his dear companion;
but going to his burial, we were caught in a shower of rain,
which we and he believed was the occasion of his illness.
He was mightily favored with the Divine presence,
which enabled him to answer the service of that day; and the next,
being the First day of the week, we had a blessed meeting,
the Lord`'s presence accompanying us; and though your dear husband was so near his end,
his candle shone as bright as ever, and many were made to glorify God on his behalf.
This was the last opportunity on this island, save his farewell upon his dying bed,
where he both preached and prayed, a little before his departure.

On the next day, being the second of the week,
he went to a little island called Jos Vandyke`'s, accompanied by several friends.
On the Third day, in the morning, he complained very much,
yet was enabled to go to meeting, where many people were assembled,
and we had a blessed opportunity together,
tendering and melting our hearts into a heavenly frame.

He went on board the sloop that afternoon, and next morning came ashore at our house;
where he had not been long before a shivering fit seized him, and a fever soon followed,
which kept its constant course every day.
The last two days he was in much pain,
yet he was preserved in much patience and resignation,
and had his perfect senses to the last, exhorting friends to faithfulness.
On the 6th day of the Tenth month, about six o`'clock at night, he went away like a lamb,
with praises and thanksgiving in his lips but about two minutes before.

--

[.asterism]
'''

CADWALADER EVANS was a native of the principality of Wales,
and arrived in Pennsylvania in the year 1698 and
although he was not then in profession with friends,
yet he soon after entered into close fellowship with them,
and continued steadfast to his end.
He was a diligent and seasonable, attender of religious meetings:
on First days particularly he was ready an hour before the time appointed,
and then read several chapters in the Bible, or some religious book.
As the hour for gathering approached, he would frequently observe the time of day,
and by means of this watchful care, he was seated in meetings one of the first,
and scarcely ever after the time appointed.
The gravity and composure of his countenance, as he sat in silence,
was no less remarkable than his punctual attendance,
and bespoke much inward recollection and divine engagement of mind,
as often attracted the eyes and affected the hearts of others.

He received a gift in the ministry of the gospel,
in the exercise whereof he was generally led to speak of
his own experience in religion and the Christian warfare;
and his testimony, though short, was instructive, lively,
and manifestly attended with Divine sweetness.
Notwithstanding it was always acceptable, he was very cautious of appearing, lest any,
as he often said,
should be drawn from a right concern of mind to place their dependence on words.

He was zealously concerned for the honor and promotion of truth,
and support of our Christian discipline;
and being endued with discerning and clear judgment, tempered with charity,
he was very useful in many services of the church, especially that weighty one,
of visiting Friends in their families.
And although he was naturally of a warm disposition,
yet a tender regard to the service of truth,
and a continual awe of the Divine presence presided in his heart;
insomuch that meekness and condescension were conspicuous in his conduct.

There was a freedom and affability in his behavior and conversation,
which indicated a benevolence of heart, and endeared him,
not only to the household of faith, but also to the profligate and vain;
rendering him serviceable in composing differences,
and in comforting the sick and afflicted;
and particularly in that skillful and tender office of healing discord in private families,
wherein his endeavors were remarkably successful.
In such services he spent much of the latter part of his life,
riding about from one house to another; and where no cause of reprehension appeared,
he interspersed his discourse on common affairs with useful hints, solid remarks,
and lessons of instruction.
But where admonition or comfort were necessary, the propriety of his advice,
and the uprightness of his life, added weight to his labors,
and seldom failed of good effects.

In private life, few had a better claim to the virtues of temperance, justice,
industry and frugality; and as he well knew how advantageous it was,
"`To train up a child in the way he should walk,`" he took frequent opportunities
to communicate his experienced advice among those under his care.
It was his practice, in winter evenings especially,
to read the Holy Scriptures in his family;
and he was particularly careful that neither child
nor servant should be from home at unseasonable hours;
being highly sensible how slippery the paths of youth are,
and how numerous the snares which attend them.

He was greatly favored in the use of his natural abilities,
and enjoyed an uncommon share of health until his last illness, which was short.
During that time, very many came to see him,
who showed great marks of esteem and affection;
and even libertines whom he had often rebuked and treated with,
were deeply affected with sorrow.
Indeed it was rare to see so many tears shed at a sick bed,
more especially of one of his years,
which gave a proof that he had not outlived his services.
His soul overflowed with love to God and man,
and being favored in his last moments with a blessed hope and confidence
he was going to that place which God had prepared for those who love him,
he had a happy exit from time to eternity, the 30th of the Third month, 1745,
aged eighty-one.

[.asterism]
'''

WILLAM LEVIS, of Kennet, in Chester County, Pennsylvania, son of Samuel Levis,
an early settler in Springfield, in said county, was born in Springfield aforesaid,
about the year 1688, and removed to Kennet about 1718.
By giving heed to the measure of Divine grace bestowed upon him,
he became a serviceable friend in the Society; was a good neighbor,
kind and open-hearted to his friends, and has left a good report.

His last sickness was the small-pox, which was heavy upon him,
but he bore it with much patience and resignation of mind to the last; saying,
that when the distemper came into the house, it was no surprise to him,
for he was freely resigned, and thankful he was so, for he could not do it of himself.
The same evening he was taken sick,
he remarked how good it was to be contented to bear affliction.
One night, as those that watched with him were preparing something for him to take,
he said: "`You shall see your endeavors for me will avail nothing.`"
He continued in a state of resignation, and appeared cheerful in the time of his illness.

When nearer his end, he was concerned that others might do their duty faithfully,
according to the best of their understanding, saying:
"`I have often thought at other times as at this,
of the shortness of our lives and time here, and the, uncertainty thereof,
which ought to engage us to circumspection and faithfulness to the Lord;
and I charge you that are elders,
to discharge your trust faithfully in the sight of the Lord,
having your eye single to him, and let nothing of self rule,
and then his work will be carried on in love and patience.
I could be glad to have an opportunity once more with my friends, but if I should not,
I would have those present to acquaint them with what I have to say,
and press it home to the elders, that they may faithfully discharge their duty,
and acquit themselves of that charge wherewith they are entrusted.
Also, that parents of children and heads of families may faithfully
discharge that great duty which is laid upon them,
not only in being good examples to their children and families,
but also to be concerned that they follow their footsteps.
It was a noble testimony that God gave of Abraham: '`I know him,
that he will command his children, and his household after him.`'
And if parents were concerned to teach their children
and bring them up in the way of their duty to God,
and less concerned to deck and set them off,
and provide things to make them look great in the world,
it would be of far more benefit to them.

"`And my desire is, that elders may walk faithfully, as good stewards,
not only in their own families, but to the flock which they have the oversight of;
that so they may leave a good savor to the rising and succeeding generation.
I am sensible that all those who are rightly concerned
for the discipline and promotion of truth,
will meet with trials from that libertine spirit which would lay all waste.
These will say, that religion consists not in such small things; but I have observed,
that one small thing makes way for another, and greater things will take place;
and if there is not a careful watching against these small things,
the eye that should be kept open to see the evil of them, will become darkened.
But keep you your places, and labor in faithfulness with such, if possible to gain them;
but if after friends labor, they will not be gathered,
friends will be clear and have peace in themselves;
but a blast will come on such troublesome spirits.
And as Friends faithfully maintain this their discipline, the Lord will preserve them,
but if they neglect it, they shall surely suffer loss.`"

To some present, who had been engaged in the service of visiting families, he said,
"`It was a good work, and desired it might not be forgotten.`"
At another time, being in a weighty frame of mind, he said,
"`There is an enemy busy to accuse the innocent,
and prompt on the wicked in their wickedness.`"
Seeing his.
affectionate wife and sister, with some neighbors, weeping, he said, "`Don`'t weep for me,
but be faithful, and we shall meet again,
for it is the hardest of all to see you weep.`"

The morning before he died,
he desired to be helped to the chamber where his eldest son lay ill of the same disorder,
and sitting down by him, he charged his children to be dutiful to their mother,
and have a care of doing any thing that would be a trouble to her,
but mind to take her advice, and desired a blessing might attend them; adding,
'`My race is almost run, and I shall lay down my head in peace with the Lord;
and if you are faithful, (meaning his wife and children,) and live in the fear of God,
he will bless you.`'
After some time of silence, he said, '`Farewell, my son; the Lord bless you, my child,
and yours after you.`'

Being then helped down stairs, he sat in his chair, and after a time of silence,
clasped his hands together, saying, with a composed countenance, I bless you, O Lord.`'
Afterwards, lying still in a quiet, composed frame of mind, he grew weaker and weaker,
and about the ninth hour in the evening, departed without sigh or groan,
like one going to sleep, and, we believe,
in peace with God and unity with faithful friends.

He died the 17th of the Second month, 1747, in the fifty-ninth year of his age,
and was interred in Kennet burying-ground, the 19th of the same month.

[.asterism]
'''

EVAN EVANS, of Gwynedd, in Pennsylvania, was born in Merionethshire,
in the principality of Wales, in the year 1684,
and came to Pennsylvania with his parents in 1698;
under whom he received a sober religious, education.
But, being early in life convinced that a form of godliness,
without the real enjoyment of the quickening principle of grace and truth,
would not afford solid and lasting peace to his soul, he sought earnestly after it,
and resigned his heart to the baptizing power of God,
which fitted him for eminent services in the church.

In his constant attendance at our religious meetings,
he was a remarkable example of unaffected piety; for while he sat in silence,
the earnestness wherewith his soul wrestled for a blessing, was obvious in the steady,
engaged appearance of his countenance.
He was favored with an excellent gift in the ministry,
which he exercised in solemn dread and reverence;
and as he always retained an awful sense of appearing in public testimony,
he was particularly cautious and watchful,
not to presume to speak without assurance of a necessity being laid upon him,
and equally careful to attend to the continuance of it;
and therefore his "`Preaching was not with enticing words of man`'s wisdom,
but in the demonstration of the spirit and of power.`"
His service was rendered more effectual, by the distinguishing marks which he bore,
of "`An Israelite indeed,
in whom was no guile,`" adorned by a plainness and simplicity of manner in word and deed,
with a zeal seasoned by divine love;
and as he had large experience in the work of regeneration
and the mysteries of the heavenly kingdom,
as well as the snares of the world,
he was thereby well qualified to administer to the states of the people.

He travelled through many of the colonies of North America in the service of the ministry,
in company with his relation and dear friend, John Evans.
Their friendship was pure, fervent, and lasting as their lives,
and their separation a wound to the latter,
the remembrance of which he never wholly survived.
He also frequently visited the several counties in Pennsylvania, and more particularly,
many of the adjacent meetings in their infancy; wherein his unwearied labors of love,
tended much to their comfort, growth, and establishment in the truth.

He was religiously concerned for the support of the Christian discipline of the Society;
and as he was always diffident of himself,
he labored faithfully for the discovery of truth,
and a disposition of mind to embrace it;
whereby he was often enabled to lay "`Judgment to the line,
and righteousness to the plummet,`" whether in reproof to the obdurate,
or instruction and comfort to the penitent.
In visiting friends`' families, his service was great;
for being endued with a spirit of discerning and the authority of truth,
his advice was adapted, with great propriety and advantage,
to the particular states and conditions of persons and families.
His conduct and conversation in common life, adorned the doctrine he preached,
being a good example of plainness, moderation, and uprightness of heart.

He was abroad in the service of truth when attacked with his last illness;
and as the disorder was slow and tedious,
he attended several meetings in the forepart thereof; in some of which, his lively,
powerful testimonies clearly manifested, that the God of his youth,
who had raised him up an instrument in his hand, and on whom he had relied all his life,
continued to be his shield and support in the evening of his days and close of life;
which was on the 24th of the Fifth month, 1747.
He was buried at Gwynedd.

[.asterism]
'''

ALICE GRIFFITH, late wife of Hugh Griffith, of North Wales, in Pennsylvania,
was one that feared the Lord from her youth, remarkable for her modesty and plainness.
When she was married and settled,
she evinced a religious concern for the advancement
of truth and the welfare of the professors of it;
and being a woman of great integrity and uprightness of heart,
became very serviceable in several respects;
zealous for maintaining good order and Christian discipline in the church.

She was well qualified for that weighty service of visiting families, having,
at such opportunities, to communicate of her own experience,
and tell what God lad done for her soul; and under a good degree of heavenly influence,
would often be drawn forth in opening divine mysteries,
as if she had been in a large assembly, as many can testify,
who have been sensibly reached and baptized by her religious visits;
at which she was furnished with matter,
adapted to the different circumstances of individuals and families.

She was often concerned to stir up her friends, to a close attendance of meetings,
both on First and other days, as also to observe the hour appointed,
being herself a good example therein, until,
by old age and infirmity of body she was disabled,
which was about three years before her removal.
Notwithstanding the circumspect life and watchful state she was preserved in, yet,
in the time of her weakness, she was visited with discouragement and dejection, and,
at a certain time, was heard to say, "`Lord, how long will you withdraw yourself from me,
and not show for what cause I am thus afflicted?
I have been acquainted with your righteous judgments, which were ever mixed with mercy;
but now, my trouble is more than I am well able to bear, being almost ready to sink.`"
Again, she said, "`Lord, wherein have I offended you;
what part of my duty have I neglected, that you should thus hide your face from me?
Time was when my hope, in full assurance, was to rest in you,
but now I fear I shall become a cast-away.`"
At another time, "`What have I done that I should be thus afflicted?
Lord, shall there be any end of my sorrow?
Many sweet times I have had when alone, but now am left as in the dark,
fearing to make one step forward lest I stumble:
he that once was my guide has now left me.`"

Again, "`I still desire to be willing to suffer while in this body,
anything you may please to bring upon me, be the exercise of what kind soever,
if you will favor me with your living presence; then, Lord,
shall not anything be too near or dear to part with, or to suffer for your namesake.
Yes, Lord, if you should see fit to deprive me of my sight or hearing, health or speech,
let me never murmur, but,
oh! give patience to bear this inexpressible exercise to the end.`"

One morning, after calling her two daughters, she said, "`Put by your work, my children,
for I have to tell you of a glorious visitation the Lord was pleased to favor me with.
As I was making my supplication to him for deliverance and redemption from my sore exercise,
and to obtain some refreshment to my poor, distressed soul,
the Lord was graciously pleased to answer my request in a satisfactory manner.
He opened the eye of my mind to see him coming in
his glory to relieve me from my long distress.
May my whole trust and confidence ever abide in him who has so filled my heart with joy,
that pain and grief vanished away.
This glorious season surpassed all that I had ever known before.
At which time the Lord gave me a sure promise, that, although my afflictions were many,
and more I had yet to go through, yet I should, in the end,
be rewarded with a crown of righteousness in the kingdom
of rest and peace,`" with more to the same effect.

It was observed that a change appeared in her countenance from that time forward,
she being cheerful and pleasant, and never sad, as before.
Her decease was on the First-day of the Second month, 1749,
and was buried on the 3rd of the same.

[.asterism]
'''

SARAH PLEASANTS, fourth daughter of Thomas and Mary Pleasants,
was taken ill the 26th of the Seventh month,
and departed this life the 7th of the Eighth month; 1749,
in the seventeenth year of her age.
In the time of her illness,
she called several persons present to view her blooming youth, how changed,
and likely in a short time to bid adieu to the world and all its enjoyments;
praying that the moment she was prepared she might go.
In a particular manner,
she desired the physician who attended her to observe the frailty of poor mortals,
as well as the uncertainty of time in this life, saying, "`Look on me, doctor.
I am like a bud cropped from the vine before it is fully blown; yet, young as I am,
I have something to repent of, which in health and strength we are apt to overlook,
and flatter ourselves is no crime.
I have been too much given to laughter and jesting with those of
my companions who have returned the same,`" naming one in particular,
whom she expressed a great desire to see before she died,
that she might warn her of the weight she now felt, not only in these two things,
but in a third, which was taking too much delight in dress.

Then directing her discourse to the doctor, she said,
'`Nothing else have I to charge myself with, yet, dear doctor, I find it enough;
therefore let me prevail with you to take warning by me.
I am sensible that some things you are in the practice of are fully as dangerous,
if not more so, than those which now lay so heavy on me; that of drinking to excess,
to oblige company, as your excuse and that of many others is,
yet you will find it of greater weight when you come to lie in the condition I now am in,
than now you may think possible.
You will surely wish it had been left undone, with all other unprofitable things.`"
The doctor replied, weeping, "`I take it very kind, and hope I shall observe it.`"
Many more good expressions and advice she uttered to him and others then about her.
She one day called her brother Thomas to her bedside, and said to him, "`Dear brother,
I know your situation to be very lonesome, and destitute of suitable company;
notwithstanding, I pray you, keep as much as possible out of low company,
not the poor do I mean, because they are poor, but the loose and vulgar,
whether poor or rich, who are of a corrupting spirit,
and will tend to the hurt of those who associate with them; but keep your place,
and you will be like a light set on a hill, as a guide to others,
who will praise God on your behalf.`"

[.asterism]
'''

ANN ROBERTS, of Gwynedd, in Pennsylvania,
was convinced of the truth in her native country, Wales, when young,
which incurred her father`'s heavy displeasure, but in time he became reconciled to her.
Some years after her convincement, she came over into Pennsylvania,
where she received a gift in the ministry, and by a diligent improvement thereof,
together with the influence of a pious life, she was made useful in her generation,
and a blessing to many.
Her love and compassion for the widow, the fatherless, and others in affliction,
appeared by her often visiting them.
She was one of the wise in heart, who was favored to foresee the enemy in his approaches,
and would arouse and excite her fellow-soldiers to
use their utmost endeavors to repel his attempts,
which was often done with desirable success.
She was also zealously concerned for maintaining Christian discipline in the church.

She was rightly qualified for the weighty service of visiting Friends`' families,
and at those opportunities was frequently favored with something suitable to every state,
which was attended with beneficial effects, especially on the youth.
Such indeed was the divine savor which usually accompanied her discourse and conversation,
one could rarely be an hour with her without sensible edification.

Her first coming to reside in Pennsylvania was seasonable,
for there being but few ministers, the field before her was extensive,
in which she labored fervently,
tenderly inviting those afar off to draw nigh unto the Lord Jesus,
and querying with them, whether they knew what he had for them to do.
By the visitations of heaven, and a blessing on her labors,
many came to have their mouths opened to speak of God`'s goodness to their souls;
whereby was verified,
what she had declared at the meeting before she came to dwell there,
though it then seemed improbable, and some doubted the accomplishment thereof.
To those who were in the ministry, she, who had a large share of experience in the work,
was not lacking to administer suitable caution and advice.

She travelled much in the work of the gospel, visiting friends in Pennsylvania,
and the adjacent provinces, namely, the Jerseys, Maryland, Virginia and Carolina,
accompanied to the remotest parts by her near and dear friend, Susanna Morris.
In her more advanced years she visited Great Britain, accompanied by our esteemed friend,
Mary Pennel, between whom a near and strict union was preserved throughout their travels;
and she brought home very comfortable accounts of
her acceptable service in the gospel ministry,
and her godly conduct in Christ.

After her return from Great Britain,
she met with great difficulties in respect to her outward circumstances,
which she sustained with Christian fortitude.
A near friend of hers asking her how she felt under them, she replied,
"`While I keep my eye steadily directed to the object worthy of our chief regard,
it seems as if a wall was on each side; all is calm, and nothing hurts or annoys.
But if I allow my eye to wander to the right hand or the left,
the enemy breaks in upon me like a torrent, which hurries me away,
and it is with great difficulty I recover myself.`"
After this, she met with a very heavy affliction in the loss of her husband,
which she likewise bore with becoming resignation and composure of mind.
In a few months afterwards, she fell into a lingering disorder; and as,
in time of health, she preferred the prosperity of truth to her chief joy,
so in her illness she rejoiced much to hear of any
young people appearing hopeful in the ministry.
On the other hand, she would, even in time of great weakness,
lament with anxiety of mind the low situation of the seed, and say,
"`Oh! what will become of us?
Will this dark cloud which hangs over our assemblies,
terminate in a boisterous storm to try the foundations of the children of men?`"

By the long continuance of her disorder,
she was reduced to great weakness some time before her end; yet it was evident,
that love to God and his people, continued with her to the last.

She died on the 9th day of the Fourth month, 1750, in the seventy-third year of her age,
having been a minister fifty years, and was buried at Gwynedd aforesaid;
on which solemn occasion, we had a good meeting,
the extendings of Divine love being witnessed.

[.asterism]
'''

ISRAEL PEMBERTON was born in the county of Bucks, in Pennsylvania, in the year 1684,
being descended of pious parents,
well esteemed among Friends in the first settlement of this province.
He served his apprenticeship and settled in the city of Philadelphia.
Having chosen the fear of the Lord in his youth, and being preserved therein,
he established and supported an unblemished character by his justice, integrity,
and uprightness in his dealings among men, and his mild, steady,
and prudent conduct through life.
He was a member of the monthly meeting of Philadelphia nearly fifty years;
and being well grounded in the principles of truth, of sound judgment and understanding,
he approved himself a faithful elder; adorning our holy profession by a life of meekness,
humility, circumspection, and a disinterested regard to the honor of truth;
of great use in the exercise of the discipline,
being a lover of peace and unity in the church; careful to promote and maintain it;
constant in the attendance of meetings, and his deportment therein grave, solid,
and reverent and a true sympathizer with those who were honestly concerned in the ministry:
a conspicuous example of moderation and plainness; extensive in his charity,
and of great benevolence; in conversation cheerful,
attended with a peculiar sweetness of disposition,
which rendered his company both agreeable and instructive.

A few days before his decease,
being in a free converse with two of his friends whom he much loved and respected,
he took occasion to recount many occurrences of his life,
and with a grateful sense of gratitude,
to express the lively remembrance he retained of the merciful
extendings of Divine love towards him in his youth,
by the continuance whereof he had been enabled to persevere
in a conscientious discharge of his religious duties,
to the best of his knowledge;
and that being still favored with a degree of the same love,
it was his greatest comfort in his declining years.

His death was sudden, though not altogether unexpected;
having been at intervals affected with a dizziness in his head,
and several times so as to deprive him of his speech.

He was very lively and pleasant the morning before his departure,
and in the afternoon went to the burial of an acquaintance,
and accompanied the corpse to the graveyard, where he was seized with a fit,
supposed to be of the apoplectic kind, and expired in about an hour,
being the 19th of the First month, 1754, and was buried on the 22nd of the same month,
in the sixty-ninth year of his age.

[.asterism]
'''

PETER ANDREWS, of Burlington, in New Jersey,
having received from the Lord a gift in the ministry, he was faithful thereto,
and made helpful to many; being devoted to the service of God;
and when any religious duty was required of him, he was fervently engaged to perform it,
as strength was afforded.

He was careful to attend meetings for worship and discipline, and when there,
manifested a real concern to wait upon God for strength and wisdom,
that so such meetings might be truly profitable.
Among his neighbors he was serviceable,
his example having a tendency to strengthen the good in them and others,
and to discourage that which was wrong.

His engagements in the exercise of the ministry occasioned him to be much from home;
yet his regard for the family was becoming his station, both as a husband and a father.
It was his frequent practice to sit down with them to wait upon the Lord;
and his faithfulness therein was of considerable service.

In the year 1755, he, in a weighty manner,
laid before his friends a concern that had for some time rested on him,
to visit the churches in England.
And having obtained their concurrence, and settled his temporal affairs,
he embarked about the 29th of the Fourth month, the same year.

He landed in the south part of England, in or about the Sixth month, 1755,
and went directly to London, where he was kindly received by Friends,
and had very good service during a short stay there;
but being desirous of being at the quarterly meeting to be held at York,
in company with several Friends of London, he went to that city,
being nearly two hundred miles distant, and reached it by the 24th of the Sixth month,
at which time the quarterly meeting began.
This dear friend had a very memorable and weighty opportunity in ministry,
in the meeting of ministers and elders at the opening thereof; but,
in the succeeding meetings for worship, was mostly silent; yet in those for discipline,
was divinely led to set forth the nature, good end, and tendency of such meetings,
and very zealously pressed the necessity of keeping them up in
the same wisdom and power in which they were first established;
setting forth,
"`That they proceeded from that which gathered our forefathers to be as a peculiar
people unto God;`" to the no small edification and comfort of many sincere hearts.

After the quarterly meeting was ended he went to Pickering,
where a very large meeting is kept annually for worship,
and had seasonable and profitable service.
He travelled to many other places in that county,
and Friends were greatly refreshed and edified by his Christian visit,
though not always attended by public declarations
in their religious meetings appointed on his account,
which were mostly very large, and expectations high,
yet his eye was to his great Master`'s putting forth.
He often was led to famish the too eager desire after words;
and in several public meetings he had nothing to say among them; which,
though a great disappointment to many for the present,
yet there afterwards appeared a signal service in it.

He was at Yarm, Stockton, Bainbrig, and several other meetings in and about the Dales;
then went to Leeds, Bradford, Wakefield, Doncaster, and so into Lincolnshire;
which county he visited pretty generally; also the isle of Ely, and into Norfolk,
in the Eleventh month, 1755.
He was at most, if not all, of the meetings in this county;
then went into Suffolk and Essex,
and returned to London the latter end of the First month, 1756,
where he remained a few weeks, being exceedingly ill;
yet was at most of the meetings in that city, and was very serviceable,
with many other Friends,
in affairs particularly relating to the Society in Pennsylvania.

He went back again into Essex, and so for Hertfordshire, some parts of Buckinghamshire,
Oxfordshire, Gloucestershire, and to the yearly meeting at Bristol, in the Fifth month,
1756; and had good service both in meetings for worship and discipline,
which was well received, and, it is hoped,
made lasting impressions on the minds of many.

His indisposition still continued, but did not hinder him from traveling.
From Bristol, he passed through some part of Gloucestershire, Wiltshire, and Oxfordshire,
and got to the yearly meeting at London in the Sixth month,
and although his ill health continued, he was enabled to bear several living testimonies,
in the demonstration of the spirit and of power.

After the yearly meeting was ended,
he attended the yearly meetings at Colchester and Woodbridge,
where he was eminently supported to be serviceable in the churches.
At Woodbridge he was strengthened to bear a powerful
and affecting testimony in the last meeting of worship,
to the tendering of many hearts, whose states were effectually spoken to:
and that favored meeting might be fitly compared to the
excellency and glorious situation which the Psalmist described,
when he says, "`How good and how pleasant a thing it is,
for brethren to dwell together in unity!
It is like the precious ointment upon the head, that ran down upon the beard,
even Aaron`'s beard, that went down to the skirts of his garment.
As the dew of Hermon, and as the dew that descended upon the mountains of Zion;
for there the Lord commanded the blessing, even life forevermore.`"
It was indeed a heavenly, precious, baptizing season,
this being the last public opportunity our dear friend had,
in which he was wonderfully led to set forth the progressive
steps the Almighty was pleased to make use of,
in appearing to Gideon, confirming him in the certainty of his requirings,
condescending to grant his requests in a very peculiar manner,
and sealing them with his presence, and giving him victory over his enemies,
as he was faithful to follow the blessed Author that pointed out the beginning as well
as the finishing of that great work to which that extraordinary servant of God,
in his day, was called.
This memorable service of our dear friend, there is reason to believe the Lord,
who prepared him for the same, was graciously pleased to fix, as a nail,
in a sure place.

He continued very weak during his stay in Woodbridge,
but no persuasions could prevail to hinder his setting forward on his journey,
having strong desires in his mind to see friends in Norwich again;
and to a particular friend he expressed that his love was so great to Friends there,
"`That he thought he could willingly die with them.`"
He was favored to accomplish this journey in two days, though with great difficulty,
and lodged at the house of his friend John Osley,
but took to his bed soon after he got in, to which, the remaining part of his time,
he was mostly confined.

It being the time of the yearly meeting there, many friends went often to visit him,
and he expressed to some, "`That he was satisfied he was in his place,
in giving up to follow the requirings of the Lord, in leaving his outward habitation,
and those near blessings of a most tender, affectionate wife, and dutiful children.`"

The severity of his illness kept him mostly delirious,
yet he was favored with some clear intervals; in one of which, being in a sweet,
heavenly frame of mind, he broke forth in the following fervent supplication:
"`Oh! this poor soul has been for many days on the brink of the pit of distress.
But you, dear father, do not afflict your children willingly,
but for some good cause known only to yourself.
Dear father! permit not your children ever to despair of your mercies,
but that we may be helpful, as much as may be in our power,
to one another in all such times of trouble.
Dearest Father!
You have been pleased to open, and to favor with your goodness; my soul is thankful,
and can say, You are worthy of glory and praise forevermore.`"

He continued to the 13th of the Seventh month, 1756, and then departed this life,
aged forty-nine years, a minister about fourteen years.
He was interred in Friends`' burying-ground the 18th of the same, after a solemn meeting,
his corpse being attended by a very large number of friends and others;
and no doubt he rests, with the spirits of the just made perfect,
in those glorious mansions prepared for all those
that hold out in faithfulness to the end.

[.asterism]
'''

JOHN EVANS, of Gwynedd, in Pennsylvania, was born in Denbighshire,
in the principality of Wales, in the year 1689,
and arrived in Pennsylvania with his parents in 1698,
under whom he received a pious education.
He was a man of good natural understanding,
and favored early in life to see the necessity of
a diligent attention to the voice of Divine wisdom,
to establish and preserve him in peace with God; and by a steady adherence to it,
he became honorable in religious society and eminently
serviceable in the church of Christ.
In the twenty-third year of his age, he appeared in the ministry of the gospel,
and his deportment therein was reverent,
as became a mind sensible of the awful importance of the service.
He had a clear, engaging manner of delivery, was deep in heavenly mysteries,
and plain in declaring them; and being well acquainted with the Holy Scriptures,
he was made skillful in opening the doctrines therein contained,
and was often led to draw lively and instructive similitudes from the visible creation.

He travelled through most of the northern colonies in the service of truth,
and several times through Pennsylvania.
He was often drawn to attend general meetings, funerals, and other public occasions,
particularly the adjacent +++[+++meetings after their first establishment,
over which he had a tender fatherly care, as a good shepherd taking heed to the flock;
and the Great Shepherd of Israel blessed his labors,
and afforded him at times great satisfaction and comfort.

The latter part of his time,
the visible declension of many from the life and power of truth,
frequently made sorrow and deep lamentation his portion.
His labors were fervent with the youth, in much love and zeal,
that they might come to know God for themselves, bow their necks to the yoke,
and lay their shoulders to the work, saying:
"`That their remembering their Creator in the days of their youth,
would be as marrow to his bones.`"
It was, indeed, his great joy to behold the peaceable fruits of righteousness,
and his labors for the promotion thereof made him
honorable among men of various ranks and professions,
and his testimony generally acceptable to them.

In the support of our Christian discipline, he was zealous, active, and unwearied,
and favored with qualification to advise in difficult cases,
which seldom failed of succeeding.
His testimony was close against hypocrisy, and an outside show of religion only,
but full of paternal tenderness to the afflicted, weak, or diffident in spirit;
of sound judgment, and deep in divine experience, yet modest and condescending,
and being favored with the descendings of the Father`'s love,
that at times appeared to clothe him as a mantle;
he had an open door in the hearts of his friends,
and an ascendency over the spirits of.gainsayers.
He was a zealous promoter of visiting friends in their families,
was many times engaged in that weighty work, and his labors were awakening and useful;
often employed in visiting the sick, the widow, and the fatherless,
and others in affliction.
On these occasions, he was seldom large in expression,
but his silent sympathy and secret breathing for their relief,
were more consolatory than many words.
A considerable part of his time was spent in assisting widows,
and the guardianship of orphans, which, though laborious to him,
was of much advantage to them.

Deeply sensible of the importance of love and peace to civil and religious society,
he was diligent in promoting them both by precept and example,
and successful in restoring harmony where any violation of it appeared.
His conduct and conversation in private life were exemplary, and implied an inward,
close inspection into the secret operations of his own heart.

He was apprehensive of his approaching end for some time before his last illness,
and told a friend, "`He should not survive one year,`" who admired he was so positive;
but he made no further reply than, "`See what will follow.`"
In his public testimony also, he frequently said,
"`He had but an inch of time to treat with us.`"
In the first part of his illness, he went to some meetings, one whereof was large,
and he was favored with strength to speak in a powerful
and instructive manner to the youth,
for whose welfare his desires were ardent.
His disorder was slow and lingering,
wherein he was favored with his understanding almost to the last; and although,
at some seasons,
he was much concerned on account of the gloominess
of the times in religious and civil affairs,
yet in general, he possessed a very great degree of calmness and serenity of mind,
with a perfect resignation to the will of God,
whether life or death should be his portion.

On the day of his departure, observing his wife troubled,
he said with a cheerful countenance, "`I am easy, I am easy,
and desired her to be easy also;`" indeed,
it appeared that the Lord had strengthened him on the bed of languishing,
and made all his bed in his sickness.
Thus having served God in his generation, he departed the 23rd day of the Ninth month,
1756, aged sixty-seven years; having, we hope,
put on the beautiful garment of Christ`'s righteousness,
and entered the wedding-chamber of the bridegroom of his soul,
and enjoys the reward of his faithful labors.
He was buried on the 25th day of the same month, in friends`' burial-ground at Gwynedd.
