== Chapter 17

[.chapter-synopsis]
* Ellen Evans
* William Mott
* Margaret Ellis
* Mary Moore
* John Churchman
* Sarah Morris

ELLEN EVANS, of Gwynedd, in Pennsylvania, was the daughter of Rowland and Margaret Ellis,
born near Dollegelly, in the principality of Wales, in the year 1685.
She was favored with a good understanding,
which being improved by a religious education and
strict attention to the dictates of divine grace,
soon distinguished her as one seeking after heavenly treasure,
which made her in riper years an honorable member of society.

She married John Evans, a much esteemed friend, to whom she was truly a help-meet,
more especially in public religious services;
for whenever she discovered the least inclination in him to visit the meetings of friends,
whether far or near, she did all in her power to cherish and encourage the motion.
She was also a great support and comfort to him under his spiritual conflicts,
about the time of his first appearing in a public testimony.

In her family she was an example of piety and industry, rising early in the morning,
and encouraging others to do so; often observing that those who lay late,
lost the youthful beauty of the day, and wasted the most precious part of their time;
that the sun was the candle of the world,
the light of which called upon us to arise and apply to our several duties.
When the affairs of the morning were transacted, it was almost her invariable practice,
except on meeting days, to retire about noon,
with the bible or some other religious book, where a portion of her time was spent alone;
from which retirement she often returned with evident tokens,
that her eyes had been bathed in tears.

She was remarkably well acquainted with the Holy Scriptures,
as also with the writings and characters of our ancient worthy friends,
together with those of her own time; frequently expressing,
"`The many advantages she reaped from often conversing with the dead and absent;
endeavoring to cultivate the same disposition in her family,
by often calling them together in the winter evenings,
and requiring one of her children to read audibly in the bible or some other
religious book;`" repeatedly observing to them, "`The benefit which attended
preserving the characters of those faithful ministers and elders in the church,
whose pious lives and happy dissolution, if held up to the view of posterity,
might be a likely means of kindling the same holy zeal,
and resolution to tread in their footsteps.`"
When ministering friends,
whom she truly loved as brethren and sisters in gospel fellowship,
in the course of their visits came where she lived, they generally lodged at their house,
at which times she seldom missed to prepare her family,
and inform the neighborhood of an intention to sit a while together in the evening;
which opportunities were often singularly blessed with divine comfort and edification.

Her diligence in attending meetings for religious worship,
was no less manifest than her steady zeal for supporting Christian discipline,
and that she and others might adorn the doctrine of God our Savior in all things.
Yet was her zeal mixed with charity,
for having long experienced how few were qualified to lay justice precisely to the line,
and righteousness to the plumbline,
she thought it safest rather to incline to the merciful side;
firmly believing that the grace of God which brings salvation, had appeared unto all men.
She delighted to converse with the uninstructed Indians
about their sentiments of the Supreme Being;
and often said,
"`She discovered evident traces of Divine goodness in their uncultivated minds.`"

In her friendship she was warm and steady,
and on her deathbed earnestly pressed her children,
"`Not to forget the friends of their father and mother;`" and the sensibility of her
heart made her very attentive to the needs of the poor in her neighborhood.

Some years before her decease she lost, in the husband of her youth, a bosom friend,
and the great support of her age, which proved so great a trial, that she said, "`If God,
whom she loved all her life long, had not enabled her to sustain it,
she must have sunk under it.`"
This dispensation of Divine Providence weaned her from all temporal enjoyments.
She continued attending meetings,
and frequently visiting the sick and afflicted while her strength permitted,
and when that failed, much of her time was spent in reading the holy Scriptures,
and in meditation.

The early state of religion in Pennsylvania was a grateful
subject of conversation to her in the evening of her day,
but upon turning her eyes to the present time, she would say with a deep sigh,
"`Oh! what is become of the morning dew and celestial rain,
that used to fall and rest upon our assemblies.`"
For herself, she often prayed,
"`That she might possess a lively relish of truth to the last,
and retain the greenness of youth in old age,`" which
God was graciously pleased to favor her with.

Her last illness began about a year before her decease.
In the forepart of it, she felt a lowness and depression of mind,
which caused her to cry, "`Tell me, oh! you whom my soul loves, where you feed,
where you make your flocks to rest at noon.`"
But after some time, this cloud was removed, and she was enabled to say,
"`He brought me to the banqueting house, and his banner over me was love.`"

Thus, by remembering her Creator in the days of her youth,
and a steady perseverance in the path of humble obedience to the will of God,
relying on his mercy in and through Jesus Christ, her crucified and risen Savior,
she was enabled to meet the king of terrors with a serene countenance,
and resigned her breath without a sigh or groan, the 29th day of the Fourth month,
and was buried at Gwynedd, the 2nd of the Fifth month, 1765; being, we trust,
admitted to the general assembly and church of the first-born,
which are written in heaven.

[.asterism]
'''
WILLIAM MOTT, of Mamaroneck, in New York government,
being on a religious visit to Friends in Pennsylvania,
after attending the yearly meeting at Philadelphia, intended proceeding to Nottingham;
and on his way there, was at New Garden monthly meeting in the Tenth month, 1765, where,
after a time of silence, he appeared in a short, yet satisfactory testimony.
Being much indisposed, he left the meeting in a few minutes afterwards,
and went to a friend`'s house, where his disorder, which proved to be the small-pox,
increased and lay heavy upon him.

Two days afterwards, some friends going to visit him,
he mentioned his desire of having a time of retirement together,
in which opportunity he expressed, in a lively and sensible manner,
his resignation to the will of God respecting his indisposition,
and spoke of the great advantage it would be to the members of our Society,
if they were more drawn from the spirit and friendship of the world,
and the eager pursuit after the riches and grandeur thereof.
He said the professors of truth suffered great loss in a spiritual sense,
for lack of being often deeply inward, when about their lawful callings,
laboring to have their minds retired,
where true comfort and instruction are to be witnessed;
and that Friends who are heads of families ought
to wait for the movings of the Spirit of Truth,
to make way for them to call their children and servants together;
and if this was the engagement of their minds,
way would be made for such opportunities beyond their expectations.
On this, and some other subjects, he, at that time, spoke in a sensible, humble manner.

At other times he frequently mentioned his uneasiness in beholding,
that many of the professors of truth did not keep within
the bounds of true moderation respecting clothing and furniture,
but rather pleased the natural disposition, to no real advantage,
and consumed much precious time that might be profitably spent in doing good among mankind.
He remarked, that if Friends lived near enough to the inward teacher,
that discovers things to be as they really are,
there are many things among us termed small and trifling,
which would appear inconsistent with the pure truth.

Notwithstanding his affliction was great, he bore it with remarkable patience,
appearing more concerned for the glory of God and the good of his church and people,
than any temporal considerations.
He frequently expressed his resignation to the Divine will, being freely given up,
either for life or death.
The retired frame of mind he generally appeared to be in, was instructive;
often saying he felt easy in spirit, having witnessed a comfortable, refreshing season,
and expressed his thankfulness for such peculiar favor in so trying a dispensation.
Yet he had no other prospect but that he should recover,
until a few hours before his decease, when he signified,
"`he had almost done with time.`"
And changing fast, he quietly departed, the 15th of the Tenth month 1765, in a sensible,
composed frame of spirit.

[.asterism]
'''
MARGARET ELLIS, late of Radnor, was born in the principality of Wales,
of parents professing episcopacy, and religious in that way.
By a short memoir she has left, she was early visited by the Almighty,
which she expresses in this manner.
"`At fourteen years of age, the call of the Lord was to me,
when seeing some of my companions carried to the grave, a concern came over my mind,
with a consideration, where their souls were gone, and where mine would be,
if I should then be taken away; and this followed and remained with me for many days.`"
But being young, and not willing to bear the cross,
the witness for God was so far suppressed,
that she gave way to follow the vanities and diversions of the world;
yet the Lord did not forget her; but some years after, the visitation was renewed.
"`Then,`" she says, "`I turned in earnest to look within, to my own state and condition,
and to the anointing mentioned by the apostle John, which opened clearly in my mind.`"
This brought her to a close exercise, and often into secret prayer,
that the Lord would be pleased to manifest her duty.
Soon after this, she went to visit a brother at Dolobran, who had, a short time before,
joined in communion with Friends; and being at a meeting, she was further reached to,
and the thoughts of her heart declared by a, worthy minister then present.
Her father took pains to dissuade her from joining Friends,
and got several priests to assist him with their endeavors;
but being enlightened to see the formality and deadness
of the profession of religion in which she had been educated,
and the blindness and emptiness of their priests, she acquainted her father,
"`that she could never come more to their church,
unless it was to his and her mother`'s burial.`"

In a few years after this,
she found a concern to appear in public testimony in Friends`' meeting,
and soon afterwards removed to Pennsylvania; in which she apprehended a Divine direction,
believing the Lord would go along with her, which she experienced to her comfort,
and was cordially received by Friends;
increasing in the gift of gospel ministry bestowed on her.

She passed through various baptisms and trials in her young years in her native land,
and many conflicts and exercises afterwards,
yet experienced the arm of the Lord revealed for her help and support.

She was a sincere-hearted woman, diligent in the exercise of her gift,
which was in much plainness and simplicity.
She visited the meetings frequently in some parts of Pennsylvania and New Jersey,
and in the year 1752, with the concurrence of Friends, embarked,
in order to visit Friends in some parts of Great Britain, which she performed,
and was in several places engaged to visit many of the families of Friends,
where her labors were acceptable and serviceable.
She was favored to return, and continued lively in the exercise of her gift.

Being taken ill in Philadelphia, in the Eleventh month, 1765,
immediately after the quarterly meeting, which she attended,
after a few days`' illness she departed this life.
She had several times, to her particular friends, expressed her desire,
if it was the Lord`'s will, to finish her days in that city;
and in her sickness expressed her willingness to depart,
but requested she might be favored with some interval of ease from extreme pain,
that she might take her leave of her friends, which was granted her.
She uttered many lively and savory expressions in her sickness,
was favored with an evidence of her future well-being, and,
as she lived in the fear of God, we doubt not she was accepted of him,
and enjoys the reward of her faithfulness.
She died the 13th of the Eleventh month, 1765, in a good old age.

[.asterism]
'''
MARY MOORE, late wife of James Moore, of Sadsbury, in Pennsylvania,
and daughter of Joseph and Sarah Wildman, of Bucks county,
was born the 8th day of the Eighth month, 1720.
She was adorned with a meek and quiet spirit,
favored with a gift in the ministry of the gospel,
and her testimony was generally well received, her words being few and savory,
and her sober deportment and exemplary conduct both at home and abroad,
worthy of imitation.
About a year before her decease she was taken with a lingering disorder,
in which time of weakness she was often tenderly affected, advising her children?
and others, "`To prepare for their latter end,
and not leave their work behind hand;`" observing, in a humble manner, what a serious,
bowed people we ought to be.

About four hours before her departure many friends came to see her,
and she desired they would sit down, that they might truly wait in God`'s fear,
and that those who knew how to wait would get deep in true silence.
At this time, notwithstanding her great weakness, she was divinely favored,
and her tongue loosed to leave her last testimony, saying, "`Friends, if you love God,
he will love you, and if you do not love God, how can you expect to be beloved of him?`"
"`'`If`' you would gather your families more often together, and sit down in his fear,
and wait in true silence, to have your minds drawn from this world,
you would grow in the truth,`" with more to the same effect,
desiring they might remember her words.
She desired her husband would freely give her up and not mourn after her,
at the same time encouraged him to faithfulness,
and desired Friends would be still and quiet until her departure.
Being sensible to the last, she quietly expired the 13th of the Seventh month, 1766,
aged forty-five years.

[.asterism]
'''
JOHN CHURCHMAN was born at Nottingham, Chester county, Pennsylvania,
the 4th of the Sixth month, 1705.
His parents were pious and consistent members of the religious Society of Friends,
and much concerned for the best welfare of their children encouraging
them in the diligent attendance of meetings for Divine worship;
"`Which,`" says he, in an account of his life,
"`is a practice often owned by the visitations of Divine love,
even to those who are very young in years, of which I am a living witness.`"
Very early in life he was favored with the convictions of the Holy Spirit,
reproving him for evil words and actions, but knew not from where those feelings came,
until about eight years of age, when, as he was sitting in a small meeting, the Lord,
by his heavenly love and goodness, broke in upon his soul, contriting it before him,
and revealing to him the knowledge of himself.
Then he clearly saw his sinful condition,
and who it was that had been thus striving with him,
and was made to confess that childhood and youth,
and the levity and foolish words and actions incident to them, are truly vanity.
He was also shown, in great mercy, that if, for the time to come,
he would mind the secret teachings of the Lord`'s holy Spirit, and obey them,
those things which he had done amiss in times past,
would be forgiven and blotted out for Jesus Christ`'s sake.

This heavenly visitation had a good effect upon him,
inducing a reverent and loving fear of offending his Heavenly Father,
and watchfulness over his words and actions.
When he retired at night for sleep, it was his practice to look back over his conduct,
and examine how he had spent the day;
endeavoring to feel the presence of the Lord near him,
which had now become his chief delight.
While he kept his own exercises and Divine enjoyments much to himself,
through a fear of losing ground by too freely conversing about them,
he was quick in observing the example of others.
Being sent to school, and naturally of ready perception and good understanding,
he made considerable proficiency in learning;
but allowing his mind to be diverted from the state of inward
retirement and watchfulness which he had known,
he lost ground, and, through disobedience,
began to shun the voice of the Holy Spirit in his heart.
Still he was in great mercy followed, both by outward correction,
from a severe fit of illness, and by inward judgments,
in order to draw him from the paths of vanity and folly.
But, through a strong desire for the gratification of his natural inclinations,
he gradually fell from the happy state he had known,
and running on in the pursuit of what is falsely called pleasure,
lost the relish for religious things.
In this lapsed state many were his strong compunctions,
and deep at seasons the sense of condemnation which he felt;
so that he began to fear that after having been permitted
so wonderfully to taste of the good word of life,
and the powers of the world to come, he had so shamefully fallen away,
that there remained no hope for him,
but only a fearful looking for the fiery indignation of an offended God.
He was afraid to be alone, for it seemed to be proclaimed in him,
that the state he was in was accursed;
and great was his anguish lest death should cut him off
in his misery and consign his spirit to endless woe.

His cruel enemy, who sought his destruction, presented many temptations,
and sore indeed were the conflicts and distress he passed through,
until the nineteenth year of his age; when,
reflecting on the sweet enjoyments he had known in the days of his innocency and obedience,
and contrasting them with his present distressed condition,
he besought the Lord to visit him with sickness,
or any other chastisement which he should see fit; so that his will might be slain,
and everything in him, which the Divine controversy was against, entirely done away,
and he become a sanctified vessel,
and know his redemption wrought out and his peace made.

Soon after this, he was visited by a severe illness, which, in a few days,
so fully awakened him, that he had no hope of being again entrusted with health.
"`My misspent time,`" says he, "`and all my transgressions,
were brought to my remembrance, and heavy judgment was upon me for them.
I was met with in this narrow path,
and could no longer fly from God and his Spirit in my conscience,
whose sore displeasure I had justly incurred.
I had heard of men who had been notorious offenders,
and fled from the justice of the law, until they became outlawed;
such in a spiritual sense my case appeared to be.
I thought I had, as it were, heard an act of grace and free pardon repeatedly proclaimed,
if I would return, and live uprightly for the future;
but in the time of these visitations, I concluded it was only to bring me under judgment,
and to take me from my pleasure; and so I had withstood or neglected these visitations.
I now saw clearly, that herein I had followed the lying suggestions of Satan, my enemy.
At this time, my old will in the fallen nature gave up its life, and I cried:
'`I am not worthy to live or enjoy your favor; yet, O Lord,
if you will be pleased to look on me with an eye of pity; do what you will with me;
magnify your own name; prepare me by your judgments and power,
that your mercy may be shown in and by me, whether you cut the thread of my life,
or grant me more days.`'`"

His heart was now tendered,
and his tears flowed freely in deep penitence and contrition of soul;
and He who delights to show mercy,
was pleased to grant him an evidence that his past sins
were forgiven for the sake of Him who died for mankind.
A willing and obedient heart was given him,
and strength and patience to bear the baptisms of the Spirit of Truth,
by which fallen man is created anew in the heavenly image,
and prepared acceptably to praise, serve, and worship the Author of his being.

After his recovery from this sickness, he continued in a humble, watchful state of mind,
often afraid lest he should again fall away,
which led him into retirement and frequent waiting before the Lord for
the renewal of spiritual strength and the revelation of his will.
Thus.
he grew in grace and in the knowledge of heavenly things,
and in time found it his place to take some part in the meetings for discipline,
of which he thus speaks.
"`I loved to attend religious meetings, especially those for discipline,
and it was clearly shown me that all who attend those meetings should
wait in great awfulness to know the immediate presence of Christ,
the Head of the church, to give them an understanding what their several services are,
and for ability to answer his requirings;
for it is by his light and spirit that the Lord`'s work is done with acceptance,
and none should presume to speak or act without his motion and direction.`"
"`It was in great fear that I attempted to speak in these meetings, and as I kept low,
with an eye single to the honor of truth,
I felt power and inward strength to increase from time to time.`"

In the twenty-fifth year of his age he married Margaret Brown, a pious young woman, who,
during their long union,
proved herself a valuable wife and true helpmeet in spiritual as well as temporal affairs.
Soon after this, he was appointed to the station of an elder,
in which he acted with great caution, humility, and fear,
and was concerned to walk circumspectly,
that in all things he might set an example becoming an overseer of the flock.

After passing through various preparatory exercises,
it pleased the blessed Head of the church,
who alone rightly calls and qualifies for the work of gospel ministry,
to confer upon him a gift and employ him in this solemn service;
and by a steady perseverance in the path of Divine requiring,
he grew to be an able minister, rightly dividing the word,
and laboring in the power and authority of Truth.
He was soon concerned to leave all that was near and dear to him in life,
and travel abroad in the exercise of his gift,
in which service he several times visited most of the adjacent provinces, and, in 1742,
he went into New England: in 1743, to New York and parts contiguous,
and was again there in 1774.
Having, for a long time, apprehended it was required of him to visit, in gospel love,
the churches in Great Britain and other parts of Europe,
and believing the time for entering upon it to be fully come, he embarked in 1750,
and spent more than four years in the engagement,
attending the meetings of Friends in England, Scotland, Wales, Ireland, and Holland,
where his service was cordially received,
and tended to the edification and comfort of his brethren.

On his return to England from Holland, he relates the following circumstance.
"`Before going to Holland, I was several times at the shop of a barber in this city,
+++[+++Norwich,]
and the second time I was there had to wait awhile for my turn.
When the others were gone, he told me if I would come on Saturdays and Wednesdays,
in the forenoon, I need not wait, but in the afternoon others came.
I asked him what days of the week those were.
He seemed to wonder at my ignorance, but knew not how to tell me otherwise.
I said, '`I do not read in the Scriptures of any days so named.`'
He replied, '`That is true.`'
'`For what reason, then, '`said I, '`do you call them so?`'
'`Because it is a common custom,`' said he. '`Suppose then,`' said I,
'`we lived in a heathen country, among infidels, who worshipped idols.
Should we follow their customs because common?`'
He replied, '`By no means.`'
I then said, '`If I have understood rightly,
the heathen gave the days of the week those names.`'
'`I never heard that before,`' said he; '`pray, for what reason?`'
I answered, that they worshipped the sun on the first day of the week, and named it,
after their idol, Sunday; the moon on the second day of the week-so came Monday;
third day they called Tuesday, after their idol Tuisco; and, after their idol Woden,
they called fourth day Wednesday; fifth day, after their idol Thor, they called Thursday;
from Friga, Friday; and, after Saturn, they called the seventh day Saturday.
As I believe in the only true God, and Jesus Christ whom he has sent,
and expect eternal life by no other name or power, I dare not, for conscience`' sake,
own the gods of the heathen, or name a day after them,
but choose the names the days were called by,
when the Almighty performed his work of creation, namely: first, second, third,
and so on, which is scriptural, most plain, and easily understood.

"`He seemed much affected with the information,
and I desired him to inquire into the matter for himself,
and not to think I designed to impose upon him.
On my return to Norwich, a man ran to me in the street, putting a paper into my hand,
and immediately left me, whom I soon found to be this barber.
The letter contained an acknowledgment to me for my freedom with him,
in language rather too much, showing his value for me as an instrument;
and believing him to be reached by the love of truth, and in measure convinced of it,
I thought it best to leave him in the Lord`'s hand for further instruction,
to learn by the immediate teaching of the Holy Spirit.
I mention this passage with a view to stir up my friends of the same holy profession,
to let their language be the language of truth to all men, in purity of spirit,
and not to name the days of the week, or the month, after the heathenish,
idolatrous customs; saying, for excuse,
that those to whom they speak best understand them,
and that it saves further explanation; which excuse is far from a disposition apt
to teach, and letting the light of truth shine as they ought.`"

After his return home from Europe,
he continued to be much devoted to the service of Christ;
and although of a weakly constitution, and often infirm,
he visited many of the neighboring yearly, quarterly, and other meetings,
greatly desiring to see the truth prosper,
and to promote the everlasting welfare of his fellow creatures.
He was concerned to keep his affections loose from the world and its cares, not seeking,
but refraining from, opportunities of procuring wealth which were presented,
endeavoring to lay up treasure in heaven, even durable riches and righteousness.
He was eminently qualified for service in the discipline and government of the church,
having a clear discernment and sound judgment,
and was a good example of diligence in attending religious meetings, and in humble,
reverent waiting on the Lord in them.
He was cautious of appearing in the ministry,
and careful to wait for Divine qualification and authority therefor,
and was often an example of humble, silent waiting; and when he did speak,
it may truly be said his doctrine dropped as the dew,
being lively and edifying to the honest-hearted,
though close and searching to the careless professor,
and to the profane and hypocritical.

Thus, as an elder worthy of double honor,
he ruled well in the church of Christ and over his own household,
setting an example of moderation and simplicity,
and adorning the doctrine of his Savior by a godly life and conduct,
and his memorial is precious.

On the 11th of Sixth month, 1775, he returned home, after performing his last journey,
which was to visit Friends on the eastern shore of Maryland,
and attend the yearly meeting at Third-haven.
Soon after, he was attacked by fever, which continued several weeks,
during which he was favored with much patience and resignation,
and uttered many lively and instructive expressions, some of which are as follows:

On the 4th of the Seventh month, he said, "`I am glad that I am at home.
I have ever found it best, when my service abroad was over,
to get home as quickly as might be,
and though I have felt great inward poverty and weakness since my last journey,
so that I can neither see my beginning nor ending, but seem as if all was hidden,
yet I hope if Providence shall see fit to remove me at this time,
some light will appear again, and that it will be otherwise before I go.`"

At another time he spoke to this purpose:
"`I have found myself much stripped as to a sense of good,
and tried with poverty many days.
I suppose I have been accounted by some, as one of the better sort of people;
but I have seen great occasion to beware of a disposition that
would seek to feed upon the praise or commendations of others.
A carnal, selfish spirit, is very apt to present, and creep in here if possible,
aid I have seen it hurt many who have had right beginnings.
It always introduces dimness and oppression to the pure, precious,
innocent life of truth, which only grows up into dominion,
through deep abasement of soul, and the entire death of self.`"

At several other times, he signified to this effect:
"`My present baptism of affliction has tended to the further refinement of my nature,
and to bring me more perfectly into the image of my Master.`"
He frequently expressed his full submission to the Divine will,
either respecting life or death several times saying:
"`I now experience my life and my will to be slain, and I have no will left.`"

In the last two weeks of his time, it appeared that his desire and hope,
mentioned in the forepart of his illness, for light again to appear,
was fully answered by the fresh influence thereof,
so that although his pain was often great,
he would many times in a day break forth into melody with his voice,
without uttering words, which, as he sometimes intimated,
was an involuntary aspiration of his soul in praise to the Lord,
who had again been pleased to shine forth in brightness
after many days of poverty and deep baptism,
which, though painful, had proved beneficial to him,
being a means of further purifying from the dregs of nature,
saying he was at times afraid to discover that melody
in the hearing of some who visited him,
lest they could not comprehend its meaning, and might therefore misconstrue it.

On Second-day morning, the 17th of the Seventh month, being asked by a friend how he was,
he replied: "`I am here in the body yet,
and when I go out of it I hope there is nothing but peace.`"
Soon after, he further said:
"`I have seen that all the bustles and noises that
are now in the world will end in confusion;
and our young men that know not an establishment in the truth,
and the Lord`'s fear for a ballast, will be caught in a trying moment.`"
At another time he said: "`I feel nothing but peace,
having endeavored honestly to discharge myself in public, and privately to individuals,
as I apprehended was required; and if it be the Lord`'s will that I should go now,
I shall be released from a great deal of trouble and exercise,
which I believe friends who are left behind will have to pass through.`"

On the 20th of the same month he thus expressed himself:
"`I love Friends who abide in the truth as much as ever I did,
and I feel earnest breathings to the Lord,
that there may be such raised up in the church, who may go forth in humility, sweetness,
and life, clear of all superfluity in expressions and otherwise,
standing for the testimony,
that they may be useful to the church in these difficult times.`"

About three days before his death, several Friends being in his room, he spoke as follows.
"`Friends in the beginning, if they had health and liberty,
were not easily diverted from paying their tribute of worship
to the Almighty on weekdays as well as First-days.
But after a while, when outward sufferings ceased, life and zeal decaying,
ease and the spirit of the world took place with many,
and thus it became customary for one or two out of a family to attend meetings,
and to leave their children much at home.
Parents, also, if worldly concerns were in the way,
could neglect their weekday meetings sometimes, yet be willing to hold the name,
and plead excuse because of a busy time, or the like;
but I believe that such a departure from primitive integrity ever did, and ever will,
occasion a withering as to the life of true religion.`"

To a friend who came to visit him on the 21st of the Seventh month, he said:
"`I feel that which lives beyond death and the grave,
which is now an inexpressible comfort to me after
a time of deep baptism that I have passed through.
I believe my being continued here is in the will of Providence,
and I am fully resigned.`"

His illness increasing, he said but little on Seventh-day, the 22nd;
in the afternoon he was very low, and speechless about twelve hours.
Early on First-day morning he recruited a little,
and gave directions about his coffin to a friend who sat up with him, being a joiner:
continuing rather easier the forepart of that day, and appearing cheerful,
he expressed several weighty sentences,
like farewell exhortations to some who came to see him.
On Second-day morning he sat up a considerable time;
in the afternoon he appeared lively and sensible, though very weak,
thus expressing himself: "`I am much refreshed with my Master`'s sweet air;
I feel more life, more light,
more love and sweetness than ever before;`" and often mentioned the divine refreshment
and comfort he felt flowing like a pure stream to his inward man,
saying to those who were with him: "`I may tell you of it,
but you cannot feel it as I do.`"

In the evening a young person coming into the room,
looking at her earnestly and affectionately, he said:
"`Deborah arose a mother in Israel;`" and shortly after: "`The sweetness that I feel.`"
His difficulty of breathing increased, and being turned once or twice,
he requested to be helped up, and was placed in his chair,
in which he expired on Second-day night, the 24th of the Seventh month, 1775,
being aged nearly seventy, and a minister about forty-two years.

[.asterism]
'''
SARAH MORRIS was born in the city of Philadelphia,
and was the daughter of Anthony and Elizabeth Morris,
who were careful to instruct her in the fear of the Lord,
in a diligent attendance of religious meetings,
and an early acquaintance with the Holy Scriptures;
the advantage whereof she at times expressed to be a great comfort to herself,
and of benefit to others.
Her father died when she was about seventeen years of age,
and near his end gave this testimony respecting her, "`That she had never disobeyed him,
and was his comfort;`" which is inserted with desires
it may so impress the minds of youth,
that by duly regarding the Divine command of obedience to parents,
they may be their comfort, merit the like testimony,
and secure peace to their own minds.

She was endued with understanding superior to many, which, with her sociable,
agreeable disposition, occasioned her conversation in the younger part of her life,
to be sought and acceptable to such who were accounted
wise in the estimation of the world;
but from her religious inclination,
preferring the company of those who exceeded her in age and experience,
she was mercifully preserved from the snares and temptations to levity
and vanity by which many of the youth are too readily captivated.

The state of mind, and the religious exercise she was brought under,
through the early visitations of Divine grace,
being sensibly expressed in a short account written by herself,
is worthy to be preserved, as follows:

[.embedded-content-document]
--

Having been one who was born of religious parents,
I was by that means favored with a sober and virtuous education;
but what was far beyond all outward blessings,
the Lord in his mercy was pleased to make very early impressions of religion on my soul,
by his immediate grace and good spirit,
and made me sensible of the touches of Divine love when very young.
At times these merciful visitations were continued from my very infancy,
and through every part of life,
by which I was in a good degree preserved from the evils and vanities of the world,
and not only so, but comforted and supported in every time of trouble and difficulty,
as there was a secret regard to that good hand which is, and ever will be,
the help of all those who put their trust in it.

But though the Lord had so favored me that I was made capable of being
in some respects serviceable among my acquaintance and friends,
from a propensity in my natural disposition (which is likewise
a blessing from Heaven) to assist or oblige those with whom I conversed;
yet after it pleased God, by the death of a sister whom I entirely loved,
to give me a fresh instance of the uncertainty and
unsatisfactoriness of all temporal blessings,
he was pleased to strengthen my desires after the enjoyment
of that which is eternal and fades not away.
Strong cries were raised in my soul that I might be brought to a nearer acquaintance,
and a more constant abiding with him who is the beloved of souls, and who,
by the secret touches of Divine goodness,
had raised such a hunger and thirst after righteousness,
that my soul could not be satisfied short of it.

After it had pleased God thus to incline my mind to seek
after a more full enjoyment of that inward life and virtue,
which is communicated and conveyed to the soul through
the illumination of the Holy Spirit,
I was visited with sickness, in which I had so near a prospect of eternity,
that I seemed just entering into it.
O! then, the emptiness and vanity of all the world, the pleasures and friendships of it,
appeared in a clear and strong light.
Nothing then but the hope of an entrance into the kingdom of Heaven seemed of any value,
and that hope the Lord was at that time pleased in some degree to afford me;
but yet I thought I saw a great deficiency, and was made to desire of the Lord,
that if it was his will to restore me,
he might enable me to live more close to his teachings,
and follow him more fully than I had hitherto done.
But in order to this,
a work of greater mortification than ever had been experienced by me, was necessary.

Great distress of soul and affliction of body was I brought into,
insomuch that I knew not where, or what I was;
such temptations and buffetings of Satan that I had till now been a stranger to,
were allowed to beset me, in the absence of spiritual comfort and refreshment;
yet in all this the Lord was very merciful,
and let me see that his dealings with my soul were
in order to qualify and fit for some further service.
O! then the solemn engagements my soul was willing to enter into at this Bethel!
If you, O Lord! will be with me in the way that I go, and give me bread to eat,
and raiment to put on, in.
a spiritual sense, and bring me to my Heavenly Father`'s house in peace,
you shall be my God, and I will serve you!
And the Lord, who knew the tenderness of.
my heart at that time, for it was his own work,
was pleased graciously to shower down of the heavenly rain of his kingdom,
by which my soul was greatly comforted and refreshed in his presence;
and in a true sight and sense of my own nothingness and inability to do
anything that was acceptable in the sight of God without his assistance,
was my spirit greatly humbled before him;
and a resignation wrought in my will to be given up in all things to him,
who had thus enabled my soul to praise his name upon the banks
of deliverance from great and sore conflicts and troubles,
which were unknown to any in that day.
Then was the Lord my refuge and sure hiding-place,
and under the shadow of his wing was I kept, and in the sweet enjoyment of Divine love,
light and life, at times was made to say,
surely nothing shall ever be able to make a separation
from the love of God in Christ Jesus.

But alas! this lasted not long,
for when it was clearly shown me what was required of my hands,
which was to bear a public testimony for God,
and to declare unto others what he had done for my soul,
then consultations with flesh and blood began.
Though the merciful visitations of love were long continued to me, yet doubts,
fears and reasonings increased, so that great darkness and distress came upon me;
nor could I now apply with that confidence and trust as formerly,
to him who alone can help, but began to disclose something of my condition to others,
from which time I was sensible that my strength decreased.
Yet all this while I was willing to hope that a fresh
visitation might be some time afforded,
for without it, I saw my state very dangerous.
What would I not then have done to recover my former condition?

I went under great distress and perplexity day and night for some months;
the comfortable refreshments and Divine openings
with which I had been so plentifully favored,
were withdrawn, and I left in unspeakable anguish and distress.
Under this sense of terror, I cried to the Lord to show me his will,
and enable me to perform it, but the sense of his love was so far withdrawn,
and fears and doubts had so prevailed, that I began to question everything,
and by degrees the unwearied adversary so far succeeded,
or it is so permitted for ends I know not, that I am at this time,
according to my weak apprehension, left very much to myself,
without the sensation of Divine love upon my soul, or the ability to seek after it,
or rightly to wait for it, or to stir or move any way as to my soul, but,
in a stupidity not to be described, stripped of all inward comfort,
and not able to take pleasure in any thing this world can afford.

--

Being, through the mercy of the Lord, preserved under this close probation, and,
in his time,
graciously relieved by the quickening virtue of His Divine presence and power, she,
in great abasement and humiliation, became resigned to his holy requirings,
and appeared in public testimony in a religious meeting.
Being thus brought forth in the ministry, through great mortification of her own will,
her appearance was much to the comfort and satisfaction of friends,
it being evident to the sensible and judicious members of the church,
that she was rightly called to this weighty work.
Several friends who sympathized with her, were spiritual helpers,
watching over her in much love and tenderness; and through faithfulness to her gift,
she increased in knowledge and experience, and became an able gospel minister,
being sound in doctrine, pertinent in exhortation, clear and audible in utterance,
and careful to adorn the doctrine she preached by a pious, exemplary life and conduct.

Her first journey in the service of truth was to
some adjacent meetings as companion to Margaret Ellis;
being afterwards, through the efficacy of divine love,
drawn forth to visit many of the meetings in Pennsylvania, New Jersey,
and the yearly meetings in Maryland and Long Island; and in the year 1764,
in company with Joyce Benezet and Elizabeth Smith, attended that at Rhode Island.
But her religious labors were chiefly in Philadelphia, manifesting a steady,
uniform concern for the cause of truth,
and the preservation of true Christian fellowship,
not only in the exercise of her gift in the public ministry,
wherein she was eminently favored,
but also of Christian discipline among friends of her own sex,
for which she was well qualified and of real use.

After the decease of her ancient mother, who, in the ninety-fourth year of her age,
departed in a calm and peaceful state of mind,
and toward whom she had manifested a filial affection and care;
an exercise which she had many years been under to visit friends in Great Britain revived,
and the weight of the service, and her apprehension of being disqualified therefor,
affected her so deeply, that she was reduced to such a low state of mind and body,
that her recovery appeared doubtful.
But after a distressing season of conflict,
she was favored with strength to communicate her concern to her monthly meeting,
and obtaining a certificate of the near sympathy and concurrence of friends,
she was left to proceed, with their free approbation,
as the Lord might be pleased to furnish ability.
Her affectionate niece Deborah Morris offered to accompany her, which,
being also concurred with, they embarked for London, in the Third month, 1772.
After her arrival there, though in a weak state of health,
she was enabled to perform her visit to Friends in
most of the principal counties and towns,
from Exter in the west, as far north as Cumberland,
and those called the Eastern counties.
They attended two yearly meetings in London,
and some general meetings in other parts of the nation;
and being favored with strength beyond expectation,
and with that wisdom which truth gives to those who faithfully resign to its holy requirings,
she discharged her religious duty to the edification of the churches and her own peace.
She returned home in the Ninth month, 1773, accompanied by her niece,
who had been truly helpful to her, and also by three Friends from Great Britain,
on a religious visit.
Her having been thus mercifully sustained through this weighty service, and,
under such apparent infirmity, advanced to the seventieth year of her age,
was both matter of comfort, and occasion of grateful admiration to Friends.

Having soon after her return, attended the general meeting at Shrewsbury,
the quarterly meeting of Bucks and some other meetings,
she united that winter with Mary Leaver and Elizabeth Robinson, from Great Britain,
in visiting many of the families of Friends in Philadelphia,
being eminently favored with divine help therein,
as she had been at times before in the like service.

In the Fifth month, 1774, she visited Friends at New York and Long Island,
attending the yearly meeting there, and several others; and in the summer and fall,
visited some meetings in New Jersey and Pennsylvania,
besides diligently attending those in Philadelphia, as she was enabled,
being favored in most of them with a lively, edifying testimony.

For about six months before her departure,
a dropsical disorder subjected her to great bodily weakness; yet her love to God,
his truth and people, was so prevalent, that when unable to walk to a meeting,
she was several times carried to her seat.
One of the last she attended in public, was on the 4th of the Sixth month, 1775,
to which she was brought with great difficulty,
and was enabled to bear a lively testimony;
affectionately expressing her great concern for the welfare of the people,
that they might be gathered to God; and,
mentioning the passage of our blessed Savior weeping over Jerusalem,
tenderly exhorted the rising youth to embrace the call of the Lord,
submit to his teaching, and thereby experience preservation.

During her illness, she had to endure great bodily pain, and, at times,
depression of spirit; yet was at seasons much favored,
and uttered many comfortable and edifying expressions, some of which being noted down,
are as follows:

Sixth month, 1775.
On hearing the sound of a drum passing, it being a time of great commotion, she said,
"`Oh! it is the Spirit of Christ that is the Christians`' glory and strength!
It makes us humble, meek and wise; it is this teacher that cannot be removed;
a guide into that righteous way, which, if but lived in,
would have kept off this impending storm.
O! that they would even now but humbly seek to learn the Christian warfare,
and be earnestly engaged to fight under the banner of Christ,
to know their own hearts`' lusts totally subdued.`"
At another time being in great pain, she cried out, "`O! sweet Lord Jesus,
that you would be pleased to give me a little ease, who am an unworthy creature,
undeserving your sweet presence; but you are merciful; and you,
O Lord! know that nothing less can ease and comfort me;
your living presence is all I want.`"

After the favor was mercifully granted, which for an hour she enjoyed, she said,
"`Oh! how good is my God, thus to hear my feeble cry.
O! how sweet is this ease!
All my pains are eased by one secret look from you.
O! that I could be thankful enough for this favor; this sweet, though short, quiet,
which we cannot get at but when you, O Father! please.
O! that the people would but believe, that in your peace their strength consists;
and that they would more generally seek to know it before it is too late.
But too many are contented without witnessing the frequent renewings of Divine love,
in which only there is life:
if they are but preserved from gross evils and go on in prosperity,
they sit down easy and think all is well; but O! that they may not, when too late,
find their mistake,
and that they have pleased themselves with favors which they have unthankfully received,
and so stopped short of greater, by not desiring them, and more frequently than the day,
waiting to know the renewings of that life,
without which there is no life to the truly begotten children, and which would show them,
not only what they ought to do, but would give them strength to do it.`"

Seventh month, 2nd. In a quiet sitting of some friends in her room,
she said in substance,
"`If I may take the freedom to express my experience
of the Lord`'s gracious dealings with me,
when in a land of darkness and drought, where no water is, a land of pits and deserts,
beset as with noxious creatures, and among serpents and scorpions,
from which none could deliver but him who can open
and none can shut -- have seen the necessity,
after having done the will of God,
to wait with patience to receive the promise of him who is the same today as yesterday,
and will so continue forever.
Many are the comfortable assurances in holy writ to those who keep the word of his patience.
I will keep such in the hour of temptation, which shall come upon all the earth,
to try them that dwell therein.`'
I have many times, my dear, may I not say my beloved, friends,
for so at seasons you have been to me, though at other times I hardly dare say so;
I have many times been glad to feel a little opening of strength with my friends,
and may say, I am thankful for this quiet, solemn opportunity,
for great have been and still are my trials, and close may be your provings.
I do not speak it to discourage any, but I find,
without the renewings of divine love and life,
we are incapable of keeping the word of his patience,
being so frequently beset and surrounded with weakness and infirmities.

"`O may you, my dear friends, who have been called and anointed for services,
witness a renewed supply of holy oil, whereby your lamps may be kept burning,
and your lights shining; and experience the law to go forth from Zion,
and the word of the Lord from Jerusalem,
and remember your covenants made in the day of deep distress.
May you be supported through every future difficulty and trial,
and I through the present conflict;
that when every pool and channel of comfort shall be dried up,
and all human help found unavailing, we may witness him to be near, who has promised,
that, for the cry of the poor, and for the sighing of the needy he would arise.
Therefore, cry mightily to him, that we may know him to do so for us; for I find,
without sensibly feeling the drawing cords of his love,
which opens and enlarges the heart,
we cannot apply those gracious promises to our comfort.

"`When he draws, let not the cares of this life, nor slavish and unnecessary fears,
prevent your following him faithfully, whatever afflictions may attend.
O may we be so preserved in his holy hand,
as that nothing may be permitted to pluck us out of it, and so assisted to conduct,
as to be found among that happy number who have come through many tribulations,
where all sorrows and sighing will be done away, and all tears wiped from our eyes,
to join those who can acceptably sing the song of praise,
having had their robes washed in the blood of the Lamb and made white.`"

On the 3rd, though with some difficulty of utterance, she said,
"`Though the floods beat high at times, and the waves roar,
I am sensible of the Divine love being present, and in that love salute my friends.
As she hoped each one there had, in a greater or lesser degree,
known the sanctifying power of religion on their minds,
she very earnestly and affectionately urged them to a more
close and solemn attention to this important work,
not to rest satisfied short of witnessing daily advancing forward on the way;
that when this earthly tabernacle was dissolved,
we might have a well grounded hope of a house eternal in the Heavens,
whose maker and builder was God.
That our blessed Savior had told his immediate followers,
in his father`'s house were many mansions, and that he went to prepare a place for them,
that where he was they might be also;
and that though the sensible enjoyment of Divine love was much withdrawn
from many who had formerly been eminently favored with its living influence,
yet not to be discouraged, as living faith in Christ Jesus, though but in a small degree,
was abundantly sufficient for our strength and safety;
and as his Divine love still continued with those who are far advanced,
and as on the verge of time,
it would also be the guide and blessed guardian of the younger in years,
as they humbly and steadily kept upon their watch,
and paid a due obedience to the Divine instructions of his Holy Spirit.`"

The last night of her life, being in bodily pain, and under some discouragement of mind,
she was reminded of some late favors of Divine love extended to her;
after lying some time in awful silence, she replied,
"`Now I see it to my Comfort that the Lord has been with me through all this illness,
and I, at times, knew it not; such was my distressed situation,
it was hard for me to believe it.`"
Afterwards falling into a sweet sleep, in about two hours she awakened much refreshed,
and remarked, she had not slept so sweetly in all her illness,
for she had been in company with her father`'s God, her mother`'s God, and her God.
She asked her niece, Deborah Morris, who had with abundant care attended on her,
if she thought life would hold all night, who answering, she thought I might,
as the night was far spent, she desired her to sit by her until the Lord came,
(meaning to the close of her life), then slumbered again, and awakening, admired, saying,
"`It is strange I should sleep at such a time as this.`"
Being told her work was done, and it was a favor to her she could sleep, she replied,
"`I believe it is, and am thankful.`"
Inquiring what time it was, and being told it was after three o`'clock,
she lifted up her hands as if engaged in mental prayer;
and soon after uttered some words, but not intelligibly,
and seeming again to drop into a sweet sleep, neither stirred nor spoke more,
but continuing till between eight and nine o`'clock, passed easily away,
on the 24th of the Tenth month, 1775, in the seventy-second year of her age,
and thirty-first of her ministry, fitted, no doubt, for the enjoyment of that rest,
which is prepared for the righteous,
having accomplished her warfare in the church militant.

Her burial on the 26th, after a solemn meeting,
was respectfully attended by many Friends, and others of her fellow-citizens.
