== Chapter 6

[.chapter-synopsis]
* Joseph White
* Susanna Lightfoot
* John Reynell
* William and Katharine Jackson
* Joseph Harris

JOSEPH WHITE was born at the Falls, Bucks county, Pennsylvania,
the 28th of the Eleventh month, 1712-13. Being young when his father died,
he was brought up under the care of his relations and friends;
and through the early extendings of heavenly regard while young,
and attending to the teachings of Divine grace,
he was preserved from many of the follies and extravagances incident to unthinking youth.
About the twentieth year of his age he appeared in
public testimony in our religious meetings,
and continuing in a good degree faithful to the measure of light and grace communicated,
he grew in his gift, and became a lively and able minister.

He was naturally of an open, cheerful disposition,
and honestly concerned for the promotion of piety and virtue,
and for the support and maintenance of good order in the church;
for which service he was eminently gifted and truly serviceable,
being often concerned that the authority of truth might be kept up in meetings of discipline,
and that true judgment might be placed upon the disorderly and irreclaimable.
He was exemplary in his life and conduct,
a diligent and timely attender of religious meetings when health of body permitted;
and was often favored therein in public testimony and supplication,
much to the comfort and edification of the truly humble waiters.
Although he had a large gift in the ministry, he many times sat meetings in silence,
waiting upon the Lord, not being hasty or forward in the exercise of his gift;
but careful not to minister without the heavenly
life and power that first raised him up in the ministry,
whereby his public service was greatly to the consolation and refreshment of many.

He several times had a concern to visit the churches abroad, and,
with the concurrence of his friends, visited many of the meetings in Pennsylvania,
and several of the adjacent provinces, and once through some parts of Maryland,
Virginia and North Carolina.
Having for some time been under a weighty concern to pay
a religious visit to friends in several parts of Europe,
with the concurrence and unity of his friends,
he took shipping for that purpose in the year 1758, and, after a short passage,
landed in England.
He visited Friends`' meetings in England and Ireland, and`' some parts of Wales,
pretty generally,
and returned to his family and friends`' having been from
home in truth`'s service nearly three years.

He was several times engaged in visiting families,
being well qualified for that weighty service.
He much loved the company and conversation of his friends;
was a loving and affectionate husband a tender parent and a good neighbor;
generally beloved by his friends and others that knew him being in several
respects useful and serviceable in the neighborhood where he lived.

He was attended from his youth at times, with a pain at his breast,
with seasons of health, sometimes for years, and at other times but short;
but as he advanced in age, intermissions of health grew shorter and pain increased,
which brought on other bodily infirmities.
These he bore with patience and resignation,
often craving he might not be off his watch when his pains were exquisite,
nor his faith fail in the time of trial, believing it to be the goodness of God,
through his thus dealing with him,
more and more to wean him from all his outward connections and the nearest ties of nature,
that being as the pure gold, refined through the furnace,
he might with triumph join the redeemed that were gone before,
of which he at times had a foretaste and evidence but the period when,
as he himself sometimes expressed, he did not then see,
believing it to be consistent with Divine Wisdom to keep it hid from him.

The latter part of his time, for several months, he slept but little in the night,
being at times engaged in reverent intercessions and Divine contemplation,
and appeared to be waiting for the solemn moment.

He lived in the compass of the Falls particular meeting
until a few years before his death,
and then removed to Makefield, a branch of the same monthly meeting.
Having for some months felt strong desires, if favored with health,
to go to the Falls meeting, on a monthly meeting day, he set out to go there;
but the weather being cold, and he in a weak state of health,
he soon found himself unable to perform the journey, and returned home.
But some time after, feeling his bodily strength in degree restored, and love renewed,
he set out, in company with his wife, one First-day morning, and got to the meeting,
where he was favored with an open time in public testimony,
much to the satisfaction of those present.
After the meeting was over, and Friends had gone out,
a person being desirous of speaking to him, not seeing him out of doors,
returned into the house, and found him sitting on a seat, unable to move without help.
The Friend assisted him, and took him to his house, where he was taken care of.
The fit being of the paralytic kind, was much more favorable than at some other times,
though it continued ebbing and flowing for several hours;
in which time he expressed several things, some of which being then taken down,
are nearly as follows.

Being asked by his son Samuel how it was with him, he answered:
"`I don`'t know but that I am near my end.
My desire at this time for you is, that you seek to the Lord for assistance,
to govern you in your conduct in this fluctuating life;
for I have found him to be a sure help and counsellor to me.
If you follow after him in truth and sincerity, as I have endeavored to do,
he will be to you a sufficient director, a teacher that cannot be removed into a corner.
I have not been anxious to gather a portion of this world,
nor to make to myself mammon of unrighteousness for I think I have
seen a snare that has attended many young people on these accounts.
I have ever, from my youth, had a desire to be more in substance than in show.
Let me appear as I might in the sight of men, their praise I sought not for;
but I have sought the honor of God:
therefore there is a place where no trouble shall annoy,
prepared for me as a reward for obedience.

"`You that stay, be more humble; and when trouble awaits you,
look not upon nor trust to the arm of flesh for assistance,
but stay yourselves upon Him who suffered for you, for me, and for all mankind.
I have for some time believed, and lived in the hopes thereof,
and am now in measure confirmed,
of more glorious things yet to be revealed to the church of Christ;
and that further and greater discoveries will yet be made,
with respect to the Christian religion, than ever yet has been since the apostasy.`"

After a short pause, he broke forth in these expressions: The door is open.
I see an innumerable company of saints, of angels, and of the spirits of just men,
which I long to be unbodied to be with: but not my will, but your will be done, O Lord!
I cannot utter nor my tongue express, what I feel of that light, life,
and love that attend me, which the world cannot give, neither can it take away from me.
My sins are washed away by the blood of the Lamb
that was slain from the foundation of the world.
All rags and filthiness are taken away,
and in room thereof love and goodwill for all mankind.

O! that we may become more united in the church militant,
and nearer resemble the church triumphant "`O! that
we all might make such an end as I have in prospect,
for it is all light, all life, all love and all peace.
The light that I see is more glorious than the sun in the firmament.
Come, Lord Jesus Christ, come when you please; your servant is ready and willing.

"`Into your hands I commit my spirit; not my will, but your will be done, O Lord!
Let this mortal body be committed to the dust; be with me,
with my children and my grandchildren; he with all them that love you,
that love your appearance.
O! the pains that I feel, that attend this mortal body,
they are more comely to me than jewels!
I rejoice in my sighs and groans, for to me they are most melodious.
I am near to enter that harmony with Moses and the Lamb, where they cry Holy, holy, holy.`'
I cannot express the joy I feel.
My heart, if it were possible, would break for joy.
If any inquire after me, after my end, let them know all is well with me.`"

Many more weighty expressions he spoke, which not being taken down,
cannot be recollected.

The next day, his pain abating, and finding himself somewhat relieved from his disorder,
he was taken to his own house, where he remained in a weak state of health for some time,
being unable to go much abroad.
One night, a short time before his death,
his pain had been sharp the forepart of the night, but the latter part it abating,
his wife lay down by him, and fell asleep; but, as usual, he slept not,
but after some time called to his wife in these words: "`My dear,
I believe I must take my leave of you.
I have never seen my end till now, and now I see it is near,
and the holy angels enclose me around, waiting to receive me.`"
His wife asked him if she should call up the children: he said,
he did not see anything further he had to say to them,
except to his son Joseph who being called,
and he having expressed what he had on his mind, was much spent,
and appeared as though he was near his desired port; but after some time he revived,
with these words: "`Life is yet strong in me, and will not yield.`"

Thus he continued during his few concluding days,
waiting in resignation and retiredness of mind,
until the repeated returns of the paralytic complaint
reduced his faculties and senses so,
that he knew not what was done for some days, and departed in much stillness,
as in a sleep, the 10th day of the Third month, 1777,
and was decently interred in Friends`' burying-ground, at the Falls meeting-house,
the 12th of the same;
his body being attended to the grave by a number of friends and neighbors.
Aged sixty-four, and a minister about forty-four years.

[.asterism]
'''

SUSANNA LIGHTFOOT was born at Grange, in the county of Antrim, in the north of Ireland,
the 10th of the First month, Old Style, 1719-20,
and descended of religious parents professing the truth, John and Margaret Hudson.
Her father dying in low circumstances when she was young,
she was placed out by her mother, to earn her living by her own labor;
who sought a portion in the truth for her daughter, esteeming it the best riches;
and lived to see the desire of her heart in that respect in a degree accomplished.
The tendering visitations of Divine love being mercifully
extended to this dear friend early in life,
she happily closed in therewith, and witnessed an advancement in piety and godliness.
Such was her love to the truth, and zeal for the attendance of meetings when young,
that she would go many miles on foot to them, and being an honest servant,
she labored hard to make up the time to her employer.
In those days,
her cup was often made to overflow with the goodness of the Lord to her soul;
which she has frequently been heard to speak of with tenderness of spirit,
for the encouragement of servants and others in low circumstances;
and that the rich and full, who have horses to ride on,
and are blessed both with the necessaries and conveniences of life,
might prize their time and privileges,
and bring forth fruits adequate to the favors conferred on them.

A dispensation of the gospel was committed to her to preach,
to which she gave up in the seventeenth year of her age;
and she grew therein as a willow by the water-course; for in the exercise thereof,
with the unity of her friends at home, she came over to this country with Ruth Courtney,
in the latter part of the year 1737,
and paid a religious visit to Friends generally on this continent, to good satisfaction;
some having cause to remember her, and the sweetness of her spirit at that time.
With the same friend she also travelled in England and Wales, in 1740,
spending upwards of fifteen months there in the service of truth.

On the 25th of the Ninth month, 1742, she was married to Jesse Hatton; in which state,
she for many years, underwent great outward difficulties,
as well as inward exercises and trials on account of the
cause and testimony of truth which she had espoused,
and was favored with firmness to hold her integrity thereto;
which she has been heard to commemorate with thankfulness to the Lord, her deliverer,
rendering the praise to him alone, who, even during that trying dispensation,
opened her way to labor considerably in his cause in many places, as in Ireland,
Scotland, and again in England.

About the year 1754 she removed with her husband and family, and settled in Waterford,
where she was made truly near to Friends, and useful in the Lord`'s hand.

In the year 1759 her husband died; and in 1760, being constrained by the love of truth,
and having the concurrence of her friends at home,
and of the meeting of ministers and elders in London,
she entered on a second visit to America,
which for many years had rested weightily on her mind.
In the Ninth month, of the same year, she arrived in America,
and visited Friends`' meetings generally throughout the continent,
as far southward as Charleston, in South Carolina,
and to the eastern parts of New England, to the comfort and satisfaction of Friends,
leaving seals of her ministry in many places; and after a labor of upwards of two years,
embarked for England.
In the summer following she visited Munster province in Ireland.
On the 25th of the Ninth month, 1763, she was married to Thomas Lightfoot;
and continuing fervent in spirit for the discharge of her religious duties,
finished her visit to that nation by midsummer following.

In the beginning of the Eighth month, 1764,
she embarked at Cork with her husband and family in order to settle in Pennsylvania,
and arrived in the Ninth month following.
She was engaged, in the love of the gospel,
to visit many of the meetings of Friends in that and the adjacent governments,
also the neighboring yearly meetings; and, in the year 1774,
went into New`'England with Elizabeth Robinson, from Great Britain;
in which visits her company and services were weighty,
strengthening and establishing to Friends.

At several meetings previous to the breaking forth of the American Revolution, she had,
in an awful manner, to proclaim the approach of a stormy day,
which would shake the sandy foundations of men,
and that many of the formal professors in our Society would be blown away.

The last journey she took, was to the yearly meeting at Third-haven, in Maryland,
held in the Sixth month, 1779, wherein deep wading and wasting exercise,
with feebleness of body, were her lot.
Soon after her return home,
a fit of illness contributed much to the breaking of her constitution;
but the balm of sweet peace of mind was still her comfort and support.
She recovered so as to get abroad again to her own,
and many other meetings about the country, and to the yearly meeting in Philadelphia,
though in a weak state of health.
The last she attended was the select meeting at Uwchlan, the 27th of the First month,
1781, under increasing weakness of body, but to the comfort of Friends then assembled.

She was an excellent example of steady waiting upon the Lord in silence, and,
out of meetings, was solid and grave in her deportment,
instructive and weighty in conversation, watchful over her own family for their good,
bearing her testimony against wrong things in them as well as in others;
of a discerning spirit; and when her lot was cast in families as well as meetings,
was often led to feel for, and sympathize with the hidden suffering Seed.
Having passed through the deep waters of affliction herself,
her eye was not unused to drop a tear for and with those in distress,
either in body or mind; and she rejoiced in comforting and doing them good.

She was a living and powerful minister of the word,
careful not to break silence in meetings,
until favored with a fresh anointing from the Holy One,
whereby she was preserved clear in her openings, awful and weighty in prayer,
her voice being solemn and awakening under the baptizing power of truth.

Many were the heavenly seasons with which she was favored during a lingering illness,
in some of which she was led to express herself in a lively, edifying manner,
and often with Divine pertinence to the states of those who were present;
as also her belief that she should join the spirits of the just made perfect,
in that city whose walls are salvation, and its gates praise.

One evening, after a solemn silence, she broke forth in a sweet melody, saying,
I have had a prospect this evening of joining the heavenly host,
in singing praises to Zion`'s king, for which favor, my soul,
and all that is sensible within me,
magnifies that arm which has been with me from my infant days,
and cast up a way where there was no way, both by sea and land.`"
She then signified what an exercise she had labored under for the good of souls,
and how it wounded her very life to behold the professors of Christianity
acting inconsistently with the example of a crucified Savior.

She frequently supplicated the Lord for the continuance of his help,
and that she might be endued with patience, adding, "`Oh! what would become of me now,
if I had a wounded conscience?
The work with me is not now to do.
This winnowing day must come closer to the dwellings of some than it ever has done,
even to the shaking of them.
from the gods of silver and of gold, hay or stubble.`"

The quarterly meeting being nigh, she urged her husband to leave her, saying,
"`There is nothing yields such comfort on a languishing bed as an evidence
of having performed our religious duties to the best of our understanding;
I can speak it at this time by experience.`"
She spoke of the necessity there was for Friends to guard against keeping
in their families persons of corrupt morals and evil communication,
which has a tendency to poison the tender minds of the children;
and signified her apprehension,
that some parents were stained with the blood of their offspring thereby.
At another time, she encouraged some present to be faithful to the Lord,
and to keep to their gifts; adding,
"`Oh! what a fine thing it is to sit lively in meetings,
and to witness the holy oil to run as from vessel to vessel.`"
Feeling herself grow worse, she gave directions about the laying out of her body,
that it should be done with exemplary plainness.

One morning, in the hearing of a few friends, she cautioned against a light,
chaffy spirit getting up in a show of religion, and was led, in a remarkable manner,
to utter reproofs against the ungodly Quaker,
signifying that a terrible day would sooner or later overtake such.

She expressed herself one day nearly as follows: "`When I have sat down in our meetings,
and cast my eye over the people,
how have I been grieved to see the haughtiness of the young men,
and the folly of the young women, looking one upon another,
as if there was nothing to do: coming to meetings just to see and be seen.
Oh! will not the Lord visit for these things?
Yes, surely he will, and call to an account those haughty sons and forgetful daughters.
I have been grieved with it when I have sat as with my lips sealed;
and yet there is a remnant who are near to my life among the youth.`"

At another time, being raised by Divine aid from great weakness,
she thus expressed herself; "`The Lord will search Jerusalem:
he will blow away the chaff; but the wheat, oh the weighty wheat,
he will gather into his holy garner.
It seems to me, that many of the better sort are hastening to their graves.
I do not repine at my afflictions,
for how small are they compared with His who suffered for us all, when he said, '`My God,
my God, why have you forsaken me?`'
Oh! the professors of truth!
How often have I thought of their great privileges!
How often have they been called unto and watered, and yet remain unredeemed!
There is much impurity about the skirts of some; if they refuse,
they will be rejected and others called in; he will have his table filled:
he will have a people that will stand for his name.`"
After some time, asking for a friend, she said,
"`I have something to say to you about the city.
The folly, I would not willingly call it iniquity,
but upon a strict examination I believe it may be so called, of laying out their dead,
has been a burden to me many times of late when I have been there.
I have wondered at the pomp, and vanity, and the cost; how much for no purpose at all,
but to be buried with the mouldering body.
How much better it would be, to spare this expense for the benefit of some poor families.
I did not know but I should have mentioned it at the yearly meeting, but I got enfeebled,
and I prayed it might rest on some others,
that it might be done then or at some other time.`"

In the afternoon of the same day, she mentioned some of the words of Amos,
"`' I was no prophet, nor a prophet`'s son, but I was a gatherer of sycamore fruit:
'`low employments,`" said she, "`But the Lord raises the poor out of the dust,
and lifts up the beggar from the dunghill, to set them among princes.
I have been one of sorrows, and much acquainted with grief.
It is true, this has been a pleasant spot to live in, and with an agreeable companion,
and it was nothing short of the good hand that thus provided for me;
but I have never forgotten the wormwood and the gall.`"

She continued quiet and sensible the remainder of her time, saying,
"`Oh dearest Lord! take me to yourself, even into your heavenly kingdom;
take me into Paradise, for I long to be with you there.`"
After expressing the desire of her soul respecting one of her sons,
she took leave of her husband and others present with a look of endearing love,
and expired about the fourth hour in the morning, like one falling into an easy slumber,
on the 8th of the Fifth month, 1781.
Aged sixty-one, and a minister forty-four years.

[.asterism]
'''

JOHN REYNELL, who died in the city of Philadelphia,
was early visited with the offers of Divine love, and by wisely closing in therewith,
came to experience preservation from many temptations and allurements,
wherewith the minds of unwary youth are liable to be ensnared.

When about eighteen years of age, purposing to embark on a voyage to Jamaica,
and being thoughtful lest he might lay down the body at that place,
as had been the case with many, he received, as he believed,
a Divine assurance that his life should be preserved.
During his residence there, he had a sight given him,
of a grievous calamity by means of a violent hurricane,
to befall the inhabitants of the island as a chastisement for their iniquities,
which came to pass according to his prospect.
Soon afterwards an occurrence happening which occasioned
his being called upon to give evidence in a court of judicature,
he was required to take an oath, which he conscientiously refusing to do,
it proved for a time no small trial of his faithfulness.
Although he had few or none outwardly to look to
for strength and encouragement under that exercise,
he was nevertheless favored to experience Divine support to be near,
so that neither threatening nor persuasion could prevail on him
to deviate from his Christian testimony in that respect.
Very few of the members of the religious Society of Friends then resided on that island,
yet a meeting-house belonging to them still remaining in Kingston,
he was not easy to omit attending at the times appointed for meeting,
though he sometimes sat there alone.

About the twentieth year of his age he came to Pennsylvania,
and settling in Philadelphia, became a serviceable member,
both in a religious and civil capacity,
cheerfully employing his talents and much of his time in beneficial and laudable purposes,
and was often engaged as a peacemaker in reconciling differences.

As an elder,
he approved himself in faithfulness and uprightness
in the discharge of that important trust,
being well qualified for the station he filled.
He was a good example in diligently attending religious
meetings as long as ability of body permitted,
and very useful in the exercise of the discipline,
being a man of integrity and sound judgment.

Having abundance of temporal riches, he endeavored to fulfill his duty as a good steward,
by liberally communicating of his substance to such as stood in need.
Besides his repeated acts of liberality throughout the course of his life,
the many charitable legacies he bequeathed by his will,
are further proofs of his benevolent disposition;
so that we believe it may justly be said,
he was one that "`Feared God and hated covetousness.`"

In the spring of the year 1784, his natural strength evidently failing,
he beheld the prospect of his approaching dissolution
with the serenity and composure of a Christian.
He continued gradually declining for several months,
during which time he did not impart much respecting his spiritual state,
being desirous to be more in substance than show,
yet found it needful to keep up a steady watch until his warfare should be accomplished.
Two friends visiting him one evening, he mentioned, "`That on looking over his past life,
he was sensible of many deficiencies,`" yet expressed "`A hope that all would be well.`"
On the evening previous to his departure, he said, "`I am ready.
I feel myself happy,
and surrounded with divine glory;`" and expired the 3rd of the Ninth month, 1784,
aged seventy-six years.

[.asterism]
'''

WILLIAM AND KATHARINE JACKSON were born in Ireland,
and came into Pennsylvania with their parents,
and settled within the limits of New Garden meeting, in Chester county.
About the year 1733 they were joined in marriage, proving true help-meets to each other;
and as they advanced in age, grew in grace,
and a qualification for service in the church in the prime of life,
being of a meek and inoffensive disposition,
well beloved and truly useful members in the meeting to which they belonged.
In dealing with offenders, they endeavored to convince and restore,
yet were careful that the testimony of truth might be preserved blameless.

Notwithstanding their beginning in the world was small,
a blessing attending their industry and frugality,
they procured a comfortable subsistence for themselves, and to bring up their family;
cheerfully and kindly entertaining many friends in those early days.
Having a near sympathy with the messengers and servants of the Lord,
who were tried and proved with humbling baptizing seasons,
they were often enabled to speak a word of comfort and encouragement to such;
they were affectionate and helpful to those in affliction,
and charitable and considerate to the poor, many partaking of their bounty.

Their care over their family, and concern to bring tip their children in plainness,
simplicity, industry, and the attendance of religious meetings, were great.
Katharine, through weakness and infirmity, particularly in old age,
often endured much pain in riding to meetings, yet, when there, her solid,
innocent countenance, and deportment therein, were edifying.

During several weeks`' painful sickness,
she retained her innocent sweetness of disposition,
expressing resignation to her allotment;
often advising her children and those about her to live in love.
Some of her last expressions that could be understood, were,
"`There is rest and peace prepared for me,
where I shall sing hallelujahs to the Highest!`"
And, after a little pause, said: "`Your sweetness, O Lord, is great!`"
She quietly departed, the 2nd of the Fourth month, 1781,
in the sixty-eighth year of her age.

William was supported under the trial of this separation
with becoming resignation to the Divine will,
having through life been an example of punctuality, justice,
temperance and brotherly kindness.

On account of bodily infirmity, which at times made riding hard to bear,
he often went on foot, when about seventy-five years of age,
upwards of four miles to meeting.
His faithfulness and example therein, and the becoming manner of his sitting there,
evidencing a watchful, solid frame of mind, were very instructive.
On the 22nd of the Tenth month, 1785, having been for some time much confined at home,
he was taken ill, and though afflicted with much pain of body,
his understanding was preserved sound, and his faculties clear.
In the morning of the 23rd, to two of his children he said:
"`There is always something comes to take us out of the world, and if we are prepared,
it is the less matter.`"
One of them expressing a hope that he did not feel anything to the contrary, he replied:
"`No, no, I don`'t; I have a comfortable hope and belief that all will be well.`"

Remarking some time after, on the settlement of his affairs, his small beginning,
and how he had been favored through life,
he expressed his concern and sympathy for Friends in straitened circumstances,
and that he had been much exercised at times,
on account of many in the Society who appeared forward and zealous,
but through neglect or mismanagement of their outward affairs,
had ministered cause of reproach; observing,
that it was wisdom not to appear more in show than in substance,
either in our religious or temporal concerns.
The night of the 25th he communicated to some of his children
much seasonable and heart-tendering advice;
recommending above all things to strive for an everlasting inheritance,
whereinto they might enter when done with time; concluding in these words: "`Love truth,
love one another, love Friends and all good people, even all mankind;
and be careful to hurt none, no, not the very meanest; if you can do them no good,
you should do them no harm.`"
Then mentioning the uncertainty of his continuance here,
gave directions that his coffin should be plain, no polish or stain upon it.

Being very low on the 28th, and apprehensive of his end being near,
he spoke to some of his children, desiring when the change came,
all might keep still and quiet; adding, it was an awful time,
and ought to be so to those about him.
Some hours after, saying, it would be a relief if he might be favored in his passage,
his bodily distress being great; "`I But I must not complain;
it does not become us to complain; but we may tell each other of our afflictions,
without complaining or murmuring.
The Almighty has been good to me in my affliction,
so that we have great cause to love him.`"
A few hours after, he said, "`What manner of persons ought we to be,
to bear every dispensation of affliction and trial that comes upon us,
as we ought to do?`"
At another time he said:
"`Many tedious days and wearisome nights have been my lot these eighteen months past.`"
His son expressing his belief that rest would be very acceptable, he replied: "`Yes,
an everlasting rest.`"

On the 13th of the Eleventh month, he uttered the following supplication,
"`O Lord God Almighty! if it be your blessed will, mitigate my affliction,
and relieve me in my distress; not my will, but yours be done.`"
And a little after he said: "`The appointed time will come, and it must be waited for;
he knows best the right time; his wisdom is very great,
and his care and providence over his poor creatures very great indeed.`"
To one of his children, taking leave of him, he said, in substance:
"`There is great corruption in the world among mankind,
and there is need of care in bringing up children, and young people, to restrain them;
for many are running as the wild asses upon the mountains.`'

A few days before he departed, he said:
"`It is a comfort to me to have my children with me,
and it may be a satisfaction to them to see me go.
I feel easy in mind on looking backward and forward.
I see nothing in my way: the Lord has been good to us,
and especially to me in my affliction.`'

Much more he expressed at times; continuing sensible, but gradually weakening,
he departed this life, on the 24th of the Eleventh month, 1785,
in the eighty-first year of his age; having been an elder upwards of forty years,
and having ruled well, was worthy of double honor, his memory being of good savor.

[.asterism]
'''

JOSEPH HARRIS, son of Joseph and Jane Harris, died at Cork, the 2nd of the Seventh month,
1800, aged eleven years.
Some time after the decease of his father he was taken ill with the measles,
which proved very severe, and in a short time terminated his life.
It had been his concern to take heed to the convictions
of the Spirit of Truth in the secret of his heart,
and to endeavor to live in the fear of the Lord;
the happy effects of which he experienced on a dying bed,
being borne up above the fear of death, and enabled to give good advice to his brother,
sisters, and others who came to see him.

His aunt sitting by him, he said to her, "`I believe I shall not recover.`"
She told him he had been worse and yet recovered; to which he replied,
"`I think I shall go to my dear father in Heaven: I have much pain here,
but I shall not have any pain there, where the Lord`'s blessing is.
It is good to pray.
O Lord, you know how often I have prayed to You; you also know my sins.
O let your will be done.
Preserve my dear mother and sisters, also my dear brother Thomas,
and enable her to bring them up in the purity of righteousness.
Preserve my dear uncles, aunts,
and cousins-set their sins before them and strengthen them to overcome;
for you are a merciful God, able to work wonders, even to make the dead arise,
and the dry bones walk as if they had life.`"

To his mother, he said, "`My dear mother, if I should be taken from you, do not grieve,
for there is no cause.
If you do grieve, and it were possible for me to know it,
it would be a very great trouble to me.`"
His mother requesting him to try to sleep, he said, "`I would rather not.`"
She told him stillness was good for him in every respect.
"`Yes, mother,`" said he, but it is good to speak when the Lord requires it.`"
Speaking of one of his uncles who had lately gone into the army,
he seemed much concerned about him, and prayed; "`O! gracious Father,
look down upon my poor uncle Henry, who is roving about on the face of the earth.
Be pleased, O Lord, to preserve him from shedding the blood of his fellow creatures;
enable him to see the danger of his ways,
and to return unto you and become a Lamb of your fold.`"

Wishing to have his sisters called, he thus addressed the eldest of them,
in an affectionate and solemn manner:
"`Do you know that it is your duty to pray to the Lord every night,
to return him thanks for his preservation of you through the day,
and to desire his protection during the night;
also in the morning to return Him thanks for relieving you from darkness.
When you sit down to meals, recollect how many there are,
who would be glad of the smallest morsel, while you have full and plenty.
Return the Almighty thanks for his bounty, and be good to the poor.
Be dutiful to your mother; mind the advice of your uncles, aunts, and friends:
love everybody, even those who do not love you-love your enemies.
Endeavor to assist your poor, afflicted mother,
who is struggling through the world with four children without a father,
and the fifth going to be taken from her.
Love your little brother and sisters; endeavor to teach them the truth,
and walk in the paths of truth, and the Almighty will be a Father to you.`"
Seeing her affected, he said, "`Do not cry, for no harm will happen to me.`"
He also gave good advice to his other sisters, and to his brother,
charging him to mind the advice of his mother, and good Friends,
and to be careful always to tell the truth; desiring them not to forget his counsel;
observing, "`The children of Israel, after they saw the wonders of the Lord,
soon forgot them; but do not you forget what I have said.`"

Calling his uncle J. Harris, who conducted the business for his mother, he said, "`Uncle,
sit down; I wish to speak to you.
If I should be taken away, will not you comfort my poor, dear mother,
and help her to rear up her children, and be as their father.
I have always esteemed and loved you as mine,
since our dear father was taken away from us.
I know you love me, and I am fully sensible of your kindness.
I have prayed for you, that you may be preserved in the truth.
The Almighty can and will do much for you if you serve him truly.
He is still a merciful God.
Did he not take his people from their enemies through the Red Sea, as on the dry land?
But they forgot him: yet he was still inclined to turn to them.
I have prayed for my uncle Henry, that the Lord would turn his heart from evil,
and protect him, for he is like a lamb torn from its dam-though he was not torn,
but has forsaken.
Dear uncle, do you comfort and protect the dear widow and the dear orphans,
and help her to bring them up.
Pray to Him, who is a husband to the widow, and a father to the fatherless,
to protect them.
Be as their earthly father, and bring up my dear little brother Thomas, and sister Jane,
in the truth.
When you retire to your secret chamber to pray to the Almighty,
remember my dear mother and aunt, and do you help to comfort them.

"`Dear uncle, be a good Friend: when you are in meeting do not be looking about,
like many others, but retire inward.
Do not let your thoughts wander from the Lord, but let your hopes be stayed on him,
for he only is worthy to be worshipped.`"
He also requested his uncle Samuel to take care of his dear mother,
and afterward told her that he had two dear uncles, who had promised to take care of her,
which seemed to satisfy him much.
His aunt and cousin sitting by him, he prayed fervently for them,
beseeching the Almighty to be with and preserve them,
as he did the three children in the fiery furnace, to keep them from sin,
and to make them lambs of Christ`'s fold.
At another time he said: "`I do not know whether I shall die at this time,
but am quite satisfied, whichever the Lord pleases.
I know he is able to raise the dead.
His power is the same that ever it was.`"

To his mother he said: "`My precious mother, I feel so nearly attached to you,
you seem like my own flesh; and surely we are one flesh.`"
To her and his cousin: "`I hope you will be preserved,
and endeavor to walk in the paths of righteousness, out of which there is no true peace.
I was thinking of Jacob, when he had a stone for his pillow, and dreamed he saw a ladder,
the top whereof reached to heaven and the bottom to the ground,
and he saw the angels ascending and descending thereon; he said:
'`Surely the Lord is in this place.`'
Remember, he did not remain there, but went forward.`"

About a year before this,
he had made use of an improper expression to one of the servants,
which caused him much sorrow, and he now requested her to excuse him, saying,
it had been a burden upon his mind, and he had often prayed to the Lord for forgiveness.
Some allusion being made to his home, he said: It is at home with my Heavenly Father.`"
He prayed to the Lord thus: "`O preserve my soul, for you, O Lord I can do it.`"
The night before he died, the physician inquiring how he was, he replied:
"`I am almost gone: farewell forever.
I am almost gone.
I hope if we meet again, it will be in a better place.`"
Being greatly tried with restlessness, he said: O, that my body was in my peaceful grave,
and my soul in heaven.`"
His mother encouraged him to be patient,
and in the Lord`'s time he would experience relief; he replied:
"`I mean when it is his holy, Divine will.
I am in great agony.
O Lord, relieve me.
Mother, I hope I have not offended the Almighty, that he afflicts me with such pain.
I do not think I have.`"
His mother told him the Almighty sometimes permitted his dear children to suffer,
perhaps for the good of others.
"`Consider how he permitted his own beloved Son to
suffer unspeakable agonies on the cross for us.`"
He replied: "`Well, I am satisfied.
O Lord, if I have committed any sins, be graciously pleased to blot them out of your book.
If any one has anything against me, I hope they will excuse me,
and that the Almighty will forgive me.`"

Being urged to take a drink, he declined, saying: I am almost exhausted;
I desire nothing but death, and the presence of the Lord God Almighty.`"
O! that I was with my Heavenly Father.
O! that you were sensible of what I feel.`"
He desired his uncle to pray for him, and looking steadfastly at him, said:
"`Is your heart truly and firmly fixed on the Lord God Almighty?
It will be to your own great benefit.
I have been made sensible this morning what kind relations I have,
and what a precious mother, who takes such good care of me.
I think I am not worthy of such a dear mother.`"
Suffering greatly from oppression, he said: "`what shall I do for breath.
This is a trying time: prepare, O! Israel, to meet your God.
His power is the same that ever it was;
the same as when he divided the Red Sea for the children
of Israel and caused them to pass over on dry ground.
Lord take me away, if it be consistent with your will.
O! Lord, I am ready; take me-Lord Jesus come-if it consist with your Divine will,
relieve my agony, if not, I am satisfied.
O! that I was one of your flock-I never was so near death before.
O! Lord, when will you send your angels to guard me up to you.`"

Early in the morning of the day on which he died, he said,
"`I hope I shall soon rejoice in the Lord.
Nothing but the Lord and heaven can satisfy me.
Now you may all go, and let me sleep, except this dear one, looking at his mother:
you are all dear, but this is my dearest.`"
His pain and difficulty of breathing greatly increased,
and during his extreme suffering he said, "`Can nothing be done to relieve me?`"
He then desired the Lord to bless those who were about him, and added:
"`I believe the Lord will bless you.
I say it from my heart;`" and looking earnestly at his mother, said,
Oh! that the Lord may bless you and me, and all the family.`"
He was now very desirous that his heavenly Father would be pleased to remove him, always,
however, adding, "`If it be your Divine will.`"
Then turning to his mother, he said, "`Mother pray for me: all of you pray for me,
pray to my Heavenly Father to take me-I have but little breath, and am almost exhausted,
nothing can relieve me but death.`"
Soon after he addressed the Almighty, saying, "`O! Lord, you sit on your throne,
and have said to them on your left hand,
'`Depart from me you workers of iniquity into everlasting fire,
prepared for the devil and his angels, '`but to those on your right hand, '`Come,
you blessed, inherit the kingdom prepared for you from the foundation of the world.`'
O! may I be of this happy number.`"

The solemn close was now evidently near,
and this precious child having been made a partaker
of the redemption which is in Christ Jesus,
was about to be translated into the kingdom of his Savior.
Raising his eyes, and clasping his hands, he said, "`O! Lord God Almighty,
if it be your Divine, all-powerful will, send death,
and your holy angels to conduct me to heaven.`"
Presently after, "`I must go, my precious mother; do not hold me.
I must go.`"
Then lying still a little while, he broke forth, "`It is just done-my heavenly Father,
it is just done;`" and raising himself in the bed, exclaimed, "`I am going,
I am going`"-and quietly departed,
we have no doubt to join the blessed company of those who being forgiven for Jesus`' sake,
cannot die any more, but are as the angels in heaven.

[.asterism]
'''

=== CONCLUSION

The memoirs contained in these volumes furnish ample testimony that the happy effects
of pure and undefiled religion are peculiar to no age or condition in life.
The child of tender years,
and the aged veteran in the Lamb`'s army-the humble servant as well
as the master-the unlearned no less than those who were skilled
in knowledge-as they submitted to the cross of Christ,
and under the teachings of the Holy Spirit,
learned of Him who is meek and lowly in heart, accepting the Lord Jesus in living faith,
as their Redeemer, their propitiation, their Leader and Sanctifier,
were made joyful partakers of that Salvation which
he purchased for us by his precious blood,
and amid the pains of expiring nature,
were supported by the hope of a glorious immortality.
Jesus Christ was their Rock and Refuge, and their hope of Salvation;
and he remains to be the only foundation to the present day.
Those who build upon Him,
through obedience to the power of his Spirit in the secret of their own hearts,
will find that He is a Rock against which neither death nor hell can prevail.

Religion is a work of daily self-denial and mortification to the natural mind;
and those who expect to enjoy its consolations and its privileges, must deny themselves,
take up the daily cross, and follow the Lord Jesus in the regeneration.
And seeing there is such a cloud of witnesses to its excellency and advantages, who,
though dead, yet speak to us, in the inviting language,
"`follow us as we followed Christ,`" may their bright
examples induce the reader to lay aside every weight,
and the sin which may easily beset, and to run with patience the heavenly race,
looking unto Jesus, the Author and Finisher of the saints`' faith,
that at the close of life he may inherit a crown of glory that shall never fade away.

[.the-end]
END OF FOURTH VOLUME
