[quote.epigraph, , Ps. 116:15]
____
Precious in the sight of the Lord, is the death of his saints.
____

[quote.epigraph, , Heb. 9:27]
____
It is appointed unto men once to die, but after this the judgment.
____

== Preface

Jesus Christ being both the author and foundation of the Christian religion,
they who believe in him, and build upon him as their foundation and rock,
lay the foundation of the building so sure, that as they abide thereon,
neither the winds nor rains are able to overturn it; for it stands all tempests.

It was upon this that the patriarchs, prophets, and apostles were founded.
And as he was their rock, so he was to all the people of the Lord,
throughout their generations; and another foundation can no man lay,
than that which is already laid.
It is here we may assure ourselves to be safe, respecting our salvation.
And as we acknowledge no other bottom for our religion,
neither do we look to have salvation any other way than by Jesus Christ our Lord,
who gave himself a ransom for all.
It has been by faith in him, and through the work of his grace in our hearts,
that many in our day, as in ages past, have had their salvation sealed unto them,
that when their deathbed sickness has come, they have had cause of rejoicing,
that through faith they had witness that they had pleased God,
by whose power they were enabled to work out their salvation with fear and trembling.

As they knew it had been the Lord who had prepared them for his kingdom,
they had given him the glory, as was their duty; for, says the Psalmist,
All your works shall praise you, O Lord, and your saints shall bless you;
they shall speak of the glory of your kingdom, and talk of your power,
to make known to the sons of men his mighty acts,
and the glorious majesty of his kingdom.

Thus have many pious souls entertained their relations and visitors,
with what may be properly called the triumphant songs of salvation.
This has much abated the sorrow of their afflicted kindred,
and has made some choose to be in the houses of mourning,
because their hearts have been overcome, in a sense of that presence and power of God,
which has been felt on such occasions.
Here the faith of the living has been strengthened by the sayings of the dying,
who speak of their own experience in the work of the Lord upon their souls.

By all which it appears, that though these, while they walked among men,
might be accounted by some not to be in the way to life;
yet it is certain they were in the path that leads to eternal happiness,
and that they were seeking another country, that is, a heavenly one; and therefore God,
even their God, has prepared for them a city.

It was the assurance many had of this in old time,
which made them valiant for truth upon earth,
and emboldened them to bear the reproaches and persecutions
which often befell them on the account of their testimony;
concerning some of whom it is said, '`They accepted not of deliverance,
that they might obtain a better resurrection.
And others had trial of cruel mockings and scourgings; yes, moreover,
of bonds and imprisonment.
They were stoned, they were sawn asunder, were tempted, were slain with the sword;
they wandered about in sheep-skins and goat-skins, being destitute, afflicted, tormented;
of whom the world was not worthy.`'

Had not these had regard to the recompense of an eternal reward,
what else could have obliged them to undergo such cruelties,
not only to the loss of life, but also were deprived of the comforts,
which they otherwise might have shared among men, in things pertaining to this world;
no, it was the certain hope they had of heaven and eternal life,
which made them triumph over the exquisite tortures of their persecutors.

This plainly shows, that they suffered not out of an obstinate humor,
as by some might be suggested;
but because they would not sacrifice the cause of their God,
therefore they were sacrificed.
And when the apostle had recited a few of the many instances which had been,
he assures us that all these had obtained a good report through faith.

It was in this faith that Isaac blessed Jacob and Esau, concerning things to come;
that Jacob, when he was dying, in the remembrance of the Lord`'s appearance to him at Luz,
and of the great promises God made him there, blessed the two sons of Joseph.

It was in this faith that he blessed his own sons;
his heart being opened in a prophetic manner, he spoke to them severally,
and predicted what in after times should happen to their tribes.
It was when this prophetic spirit was upon him that he spoke of the coming of the Messiah,
calling him Shiloh.

The dying sayings of this good old man are a monument of
the continued and especial favor of the Lord to him.
For aught that appears, he had a sight of that at his death,
of which he had till then been silent all his life.
It was at this time he acknowledged that, '`The Lord had fed him all his life long,
and the angel had redeemed him from all evil.`'
It was in the sense of this that he opened his mouth, and blessed his children.

And as for Moses, the servant of the Lord, who was faithful in all God`'s house,
he was a man whom neither the preferment of the Egyptian court,
nor the probability of wearing the crown,
could hinder either from defending his brethren, or taking his share in their affliction.
This was not a childish or an over-forward choice in him,
but doubtless was from a serious consideration, as seeing him who is invisible;
for we are expressly told, that`'When he was full forty years old,
it came into his heart to visit his brethren, the children of Israel.`'

This visit of his to the Hebrews had such a consequence, that he,
who the other day was a prince, left his greatness,
and stooped so low as to become a stranger and a shepherd in the land of Midian.
It was at this employ the Lord appeared unto him in a bush,
which burned and was not consumed, and told him the end of his appearance,
and the service which he should now undertake for
the deliverance of the children of Israel.
After which deliverance they became a nation, and were a great people,
to whom the Lord gave laws and ordinances, and gave them a charge to do them.

I conceive it neither needful nor expected,
that a recital of the many laws delivered to that people should be given here,
only let it be observed,
that they were obliged to continue in those commands to do them.

Among the many things Israel was expressly forbidden to do,
there are some which in this place, and on this occasion, I think proper to mention.
Lev. 19:28: "`You shall not make any cuttings in your flesh for the dead,
nor print any marks upon you.
I am the Lord.`"

We are informed by history,
that such practices were in use among the heathens in their funeral rites;
and lest Israel should follow these idolatrous customs,
Moses gave them a strict charge not to do them.
(Lev. 19:28, and Dent.
xiv. 1.)

Thus we see the care of the Lord over his chosen people, in prohibiting these,
among other things, that they might be holy to the Lord their God.

But from which arose that fashion of wearing mourning habits,
whether at first among the Jews or Gentiles, I know not; but this I am assured of,
that when Moses, the servant of the Lord, died, though there was very great mourning,
we do not find that they altered their habit;
but that their sorrow was expressed by their weeping and
lamenting the loss of so great a prophet of the Lord.
From which I infer,
that whatever surprise or sorrow might seize the minds of the living for their dead,
it was to be contained within, and no marks or tokens of it to be worn without.

This seems agreeable to that practice which the spirit of truth led our forefathers into,
when they were called out of the world`'s ways and vain fashions;
of which this of wearing mourning clothes was one which they complied not with,
as knowing, that that divine principle the Lord had placed in them,
required a conformity to his will in all things,
a thorough reformation and disuse of all vain customs,
since they were not to fashion themselves according to their former lusts in their ignorance,
etc., as said the apostle Peter.

May these things, which were of old prohibited the people of the Lord,
be remembered in these days, that none of us do any thing on such occasions,
as may be in any sense rendered printing marks upon us,
or rather disguising ourselves for the dead.

Now, because that some among us have, and are creeping into a sort of mourning habit,
a thing contrary to our ancient practice,
I am at this time concerned to testify against it;
for whatever was the practice of other people in this respect,
when our forefathers in the truth came forth, we find they were kept out of it,
and walked in their plain simple way, without mixing with the ways of the world.
Not but they might be accounted singular, for avoiding the modes of their neighbors;
yet it is recorded, that no such practice, as that called wearing of mourning,
was among us in the year 1694, as in Rise and Progress, page 56, it is stated:
'`Neither do the kindred of the deceased ever wear mourning,
they looking upon it as a worldly ceremony and piece of pomp;
and that what mourning is fit for a Christian to
have at the departure of a beloved relation or friend,
should be worn in the mind, which is only sensible of the loss.`'

I cannot inform the reader when this practice first began,
and am also ignorant by whom it was at first introduced into our society;
but this I may say, it is not agreeable to that self-denying principle we profess,
neither is there the least shadow of precedent for it in the New Testament.
Therefore, according to the words of the apostle Peter in another case,
Let the time past suffice, wherein you have wrought the will of the Gentiles.`'
I say, let us cast off concerning the former manner of living, the old man,
which is corrupt, according to the deceitful lusts,
and be renewed in the spirit of your mind.

Though I speak thus as to this particular, none, I hope, will count me as an enemy,
for I deliver it as a brotherly caution; and the rather,
because I apprehend it to be a spreading evil among many,
for my eye has affected my heart in this matter, as well as in some other things,
as pride, and an undue liberty that some take; which, as well as the other,
are a reproach to our society.

All these things have repeatedly been testified against, not only by some single persons,
but in a more general way.
I am at this present, writing under a Christian concern for the church of our God;
that she may be holy in all things relating to life and godliness,
that no spot or wrinkle may be upon her; for so it behooves the people of Christ to be;
and they who really are his, have crucified the flesh, with the affections and lusts.

If it be asked, how have these attained to this good state?
it may truly be answered, through faith in Jesus Christ.
For as they came to believe in him,
they saw it was absolutely needful for them to obey
the discoveries of his light in their hearts;
and by being faithful to that, they came to a sense of their sins.
This sense begat a godly sorrow,
and this sorrow wrought them into repentance never to be repented of.

These were the steps they trod in the way of their conversion;
this was a time when they sowed in tears; they wept, they mourned,
and made supplication to.the Lord, that he would remember mercy in the midst of judgment.
Oh! then the everlasting arms were underneath, by which they were borne up,
that they sunk not in the floods of their spiritual afflictions; for,
though the Lord had laid his hand upon them, by which they were brought very low,
yet he who had thus slain them, that they might know sin slain,
was pleased again to revive and make them alive.

And as thus sin and the evil conduct came to be mortified through the spirit,
the new life sprang up from that heavenly seed God had placed in them; many of whom,
after they had known the terrors of the Lord in themselves, by which they were warned,
were constrained in the love of God to warn others to flee from the wrath to come,
and no longer to content themselves with the thought,
that as they are in the outward profession of Jesus Christ,
therefore that would save them; for they must also know and experience, as they had done,
the work of Christ within them,
to prepare them to bring forth fruits worthy of repentance,
as the only way of their conversion and salvation.

Some received this advice, and clave unto this doctrine,
which had proved so effectual to many; but others have mocked,
not unlike the epicurean and stoic philosophers who encountered the apostle Paul,
because he preached unto them Jesus and the resurrection.
Like these, many have slighted the gospel of salvation,
and evilly entreated those who brought the glad tidings of grace, peace and pardon,
through Jesus Christ our Lord.

Therefore, since the testimonies of the living have not had place in the hearts of some,
may the words of the dying effect what the others have not.
And if such experimental relations, as several of the children of the Lord have given,
of the assurances they have had of their salvation in their last hours of life,
are not arguments and persuasions strong enough to provoke
the living to a timely preparation for their latter end,
I know of none that will;
since they spoke from a certain sense of their states at that important moment, which,
how soon any of us may arrive to, is generally hid from our eyes.
And since we are assured that God has appointed a day,
wherein he will judge the world in righteousness, may men`'s fruits be unto holiness,
that their end may be everlasting life;
as it is not doubted is the portion of these in the following treatise.

Should the way and call to repentance and conversion be
wholly neglected by any in this short space of life,
which should be spent to the glory of God alone, in obeying his righteous laws,
how dreadful are the states of those!
There is no retrieving time in the grave; they fall into the gulf of misery;
and in this condition they have no communication with us,
nor have we any intelligence or warning from them.
The ardent request of the rich man, in the parable,
of sending one from the dead to warn his brethren,
lest they should come into the place of torment with him,
was refused him for this reason, that seeing they had Moses and the prophets,
if they would not hear them, neither would they if one should rise from the dead.
Also by this may be learned, that men are not to expect miracles,
when other sufficient means are afforded.

Therefore, seeing that in these latter days, the Lord,
who in times past spoke unto the fathers by the prophets, does speak unto us by his Son,
whom he has raised from the dead, and sent by his grace to us;
let all thereby be turned away from their iniquities,
and serve the Lord in reverence and fear; which they do,
who have received that dispensation or kingdom that cannot be moved,
and are resolved so to walk, passing their sojourning here in fear,
counting the price great which was offered for their redemption.
And as through faith they have laid hold on Jesus Christ the Lord,
they are persuaded that nothing shall be able to separate
them from the love of God which they have in him.
And as men are guided with the counsel of the Lord, in their pilgrimage on earth,
to order themselves to his honor; such, when they go hence, will be received into glory.

Now, since it to this the grace of God has led many,
let none be so unwise for themselves, as either not to receive it,
or afterwards to turn from it.
For it was through the operation of this grace that many
of old were saved from the evils of this present world;
as thanks be to God through Jesus Christy not a few
in our day have attained to the like experience,
as they came to repentance towards God, and faith in our Lord Jesus Christ;
for it is he who washes his servants from their sins,
and saves them with an eternal salvation.
Blessed therefore are they who are sincerely concerned to know the new birth,
which is to be born from above, that they may inherit the kingdom of heaven.
But, alas! though heaven be desired by many,
how few of the sons of men are willing to walk in the way that leads unto it.
No, no; they are for an easy path, in which they may live unto themselves;
they like not the cross, though they would have the crown.
Oh! how are many spending their time in vanity.
Some in a voluptuous course of life, feeding themselves without fear;
others take excessive pains in attiring their bodies
with their changeable suits of apparel,
to the dishonor of the Lord; no, to such a pitch of excess are many come,
that as one says in a discourse on this subject, relating to superfluity of clothing,
Here is the end, '`says he, of all their fashions and recreations,
to gratify the lust of the eye, the lust of the flesh, and the pride of life;
clothes that were given to cover shame, now lack a covering for their shameful excess;
and that which should remember men of lost innocency, they pride and glory in.`'
No Cross, No Crown.`"

Yet, although it be thus with many of the children of men,
that they spend much treasure and time in decking these houses of clay,
let them know that for all these things they must be brought into judgment.

Time here would fail me, to treat particularly concerning the extravagances,
in manifold respects, into which some are fallen,
to their own hurt and the grief of many.
But I cannot here forget, that there is forgiveness with the Lord that he may be feared;
and he calls to the backsliding children to return unto him, that he may heal them.

This I write, that all to whom my caution is of need,
may hasten to the Lord in humiliation and contrition,
and he will yet help them to redeem the time; which, that they may,
wishes and prays their friend, who is concerned for the sake of Zion,
that her wilderness may become like Eden, and her desert like the garden of the Lord;
that joy and gladness may more and more be found in her,
thanksgiving and the voice of melody.

[.signed-section-signature]
T+++.+++ Raylton

[.signed-section-context-close]
The Tenth month, 1716.

[.asterism]
'''
