== Chapter 2

[.chapter-synopsis]
* William Crouch
* Robert Hill
* Anne Humphreys
* Joseph Stone
* Mary Turner
* Thomas Dockery
* Mary Post
* Richard Priestman
* William Rigge
* Samuel George

WILLIAM CROUCH, according to his best calculation,
was born the 5th day of the Second month, called April, 1628,
in a small village called Penton, by Weyhill, near Andover, in Hampshire.
His father was a substantial yeoman, of good repute in the country,
and well beloved of his neighbors.
His mother was a religious woman,
and had fellowship among the people in that day called Puritans.
She was very watchful over her children, to preserve them from committing any evil,
either in word or action, and would often get them together,
and be with them on their knees in prayer to God;
wherein she has left a good example to others of her sex.

When he was a child, the Lord often visited him in mercy; and as he grew up,
preserved and delivered him from many great temptations and evils incident to youth,
inclining his heart to shun the rude and extravagant company of the times,
and to associate himself with those that were soberly and religiously disposed.
He diligently attended the ministry of such public preachers as were most esteemed,
and followed by the most religious, as he apprehended; and often wrote their sermons,
and was sometimes much affected, returning home, and retiring himself;
and offering his supplications to God.
But not knowing that the Lord was so near unto him as he was,
he witnessed little growth or increase of grace in his heart,
or power over his affections and lusts but was sometimes overcome by sinful temptations,
and often prevailed upon by vain objects,
which afterwards proved a burden and load upon his soul.
Yet the Lord, in his great mercy, did not cast him off,
but with much long-suffering and patience, followed him with the reproofs of instruction,
which he found by experience to be the way of life.
For now, in the year 1656,
he came to be in some measure convinced of the everlasting truth of God,
revealed to the people called Quakers.
And having been at some of their meetings in London,
where he heard the testimony of truth declared, he was further reached by it,
and by degrees fully convinced,
that salvation is only in and through Christ Jesus the gift of God,
and the light of the world spiritually revealed in the heart and conscience,
and sincerely believed in and obeyed.

As he was convinced of the truth, so was he, by the grace of God, enabled to walk in it,
and to keep up a faithful testimony to it in life and conduct,
according to the measure of the divine gift bestowed upon him.
He rested not in the beginning of regeneration, where too many content themselves,
but waited for, and labored after,
through the assistance and influences of the holy spirit,
the gradual and progressive work of sanctification,
having a state of perfection in his view;
and believing it attainable on this side the grave, by the grace of God,
through perseverance in faith, humility, watchfulness and prayer, looking unto Jesus,
that he, who had begun the good work, would confirm it unto the end.
He had a sincere love towards God, his church and people; yes,
towards all the children of men.

When differences arose among Friends, or others, he endeavored what he could,
to reconcile them, being kindly affectioned towards all,
but especially those in whom the love of God appeared.

As to the things of this world, he placed not his affections upon them, but,
as a Friend who well knew him testifies, '`His treasure was in heaven;
and for the treasures of this world,
he put no value upon them any further than to be his servants for necessary uses,
and to do charitable acts therewith towards others.
His charity was large, and many ways, being ready to assist such as were in trouble,
or under affliction of any sort, where either his advice or purse was lacking;
for he spared neither purse nor pains,
when he was called to serve others who needed them.
He practiced the pure religion and undefiled before God and the Father; that is,
he frequently visited the fatherless and widows in their affliction,
and kept himself unspotted from the world.
He was in particular a great support to the poor of the neighborhood where he lived,
in the country, often distributing by others`' hands largely of his charity to them.
Nor did the stranger in distress go empty-handed away from his gates.`'

Nor was he less remarkable for doing justice than exemplary in showing mercy to the poor,
and in helping and supporting the weak and afflicted.
He felt a necessity upon him to keep his word, perform his lawful contracts,
pay his just debts, and to do to all men as he would have others do to him.

What he was in his family, whether considered as a husband, father, or master,
his children and servants, who were immediately under his care,
give an ample testimony of him,
and speak of him to have been a singular pattern of piety and virtue,
in the discharge of all those relations.

The Lord enriched him with a large stock of spiritual and experimental knowledge,
which he had been gathering and treasuring up for many years.
And though he lived not upon his former experiences, but upon Christ, the living bread,
and only nourishment of the immortal soul;
yet those experiences of the lovingkindness of God
were comfortable to him in the openings of life,
to remember, and helpful to him in giving advice and counsel to others.

In his illness, which sometimes was severe upon him,
being sorely afflicted about the space of two years before his death,
the Lord enabled him to manifest much patience,
and meekly to submit himself to the divine will.

About nine months before his own departure,
and at a time when his distemper was sharp upon him, his second wife,
whose name was Ruth, daughter of John Brown, and Ruth his wife, of Wood street, London,
a woman who was an helpmeet indeed, of a loving and tender spirit,
and of the same mind with him in the things of God,
with whom he had lived for fifty years and upwards, in the fear of the Lord,
and entire affection, was by death removed from him.
The parting with so near and dear a relation, of whom he left this testimony,
that she would deny herself to a very great degree to serve him,
beyond what he could ask or expect of her; could not but make a,
deep impression upon him:
but such was his resignation to the will of his heavenly Father,
that he possessed his soul in patience, acknowledging with Job, that "`' The Lord gave,
and the Lord has taken away: blessed be the name of the Lord.`" Job 1:21.

And now drew on the time of his own dissolution,
which the Lord had graciously prepared him for,
and which he patiently expected the accomplishment of.
He often admired the goodness of God to him,
in inclining his mind to seek after good from his youth,
and in preserving him through the whole course of his life to old age.
He also often retired in prayer,
and waited upon the Lord for support under his daily exercise.

He had attained, through divine grace, to that inward peace and satisfaction of mind,
that he declared he had nothing to do but to die.
When he saw his children concerned for him,
he often exhorted them not to desire his life, for he was, through age and weakness,
incapable of being serviceable according to his desire;
and that he had done his day`'s work in his day.

The day before he died, a friend, who had made him several visits in his illness,
went to see him; and found him very weak.
And sitting some time with him waiting upon the Lord,
he was moved to supplicate the Lord on his behalf,
who was pleased to answer the cry of his servant,
and they were greatly comforted together in a sense of the Lord`'s presence and goodness.
After prayer, he expressed his great satisfaction in that heavenly visit, and said,
as before, he had now nothing to do but to die, and waited for the time,
when it should please God to call him out of this world,
and take him to his eternal rest.

The night following, he took his solemn leave of his children who were then present,
telling them he now thought he had but little time,
and the time which he so greatly desired and waited for was near at hand;
which was matter of joy to his soul, desiring the Lord to make his change easy,
that so his patience might hold out to the end; and the Lord granted him his request.

He departed this life the 13th of the Eleventh month, 1710, aged about eighty-two years,
at the house of his son-in-law, Michael Lovell, in London;
and was on the 19th following decently buried in Friends`' burying-ground at Winchmore-hill,
in the parish of Edmonton, Miiddlesex; his corpse being attended by his children,
relations and friends.

[.asterism]
'''
ROBERT HILL, born in the parish of Droitwich, in the county of Worcester,
about the year 1630 was convinced of the blessed truth in the town of Bromsgrove,
in the said county.
The great Lord of the harvest called him to work in his vineyard,
and sent him forth to preach the everlasting gospel; which he zealously did.
The Lord`'s power and presence was with him, and his blessing was so upon his labors,
that he was instrumental to convince many in those
parts Though he met many oppositions in his travels,
and several imprisonments, as he often said,
the Lord was never lacking to carry him on to do his work,
with strength and holy boldness, to stand and make answer for his God and for the truth,
before all opposers.
And when he was brought before the magistrates, and threatened by them,
he feared not their threatenings, nor their jails.

Some years before his latter end he was troubled with much bodily weakness,
which he bore`' with patience; and though his outward sight decayed,
yet his spiritual sight remained: so that, in a good measure,
he beheld the invisible things of God,
and in the sense and love thereof he was often in raptures of life, and said,
'`I am overcome; overcome with the love of my beloved.
So now, come, Lord Jesus, for I am ready; receive my soul into your everlasting glory.
I have a fall assurance of my Father`'s love,
and I long to be with the innumerable company of angels and spirits.
I have an earnest desire, and long to be in the fulness of enjoyment,
where I may ever be singing praises to God and the Lamb forevermore.`'

He frequently gave counsel to those who came to visit him, for the good of their souls,
with much tenderness and tears, that they might not walk in the broad way of the world;
and declared of the Lord`'s mercy towards the sons of men,
if they would hearken to the call of the Lord, and be obedient thereunto;
testifying that was the way to everlasting life.
And it pleased the Lord to make him instrumental to bring many to a sight
of their inward condition for the good of their souls.

And as by Providence his dwelling in his latter time was near to the meeting-place,
he would often give thanks to God for that privilege; and when he was weak in body,
he would say, '`I must go to meeting as long as it pleases God to enable me,
and see if he has any service for me to do.`'
Many times, notwithstanding his weakness, the Lord was pleased to make use of him;
and he returned thanks to God for affording him his presence,
and enabling him by his power,
to publish and declare what the Lord had done for his soul.
He was a great lover of the poor, very charitable to them, and often prayed for them,
and entreated the Lord, he would be pleased to order for their relief,
as it seemed good to him.
His wife, knowing the blessed work of charity was well-pleasing to him,
sometimes told him what she had done in that work; he would say to her,
'`I pray God bless you for it,
and be sure you will have your reward for relieving the poor;
for the Lord delights in a cheerful giver.`'

He often mentioned the goodness of God, being truly sensible of it to his soul;
and having a regard to the poor,
he manifested the same by his frequently administering to his necessitous neighbors,
and also by the gifts and legacies he left them.

He departed this life in peace with the Lord, the 7th of the Twelfth month, 1710,
and was buried the 10th of the same.
Aged about eighty years.

[.asterism]
'''
ANNE HUMPHREYS, late of Saffron-Walden, in the county of Essex, widow,
was a young woman whom the Lord was pleased to visit and bless
with the knowledge of himself and his unchangeable truth,
which she received.
in the love thereof; and by waiting upon the Lord therein,
came to know the work of it in her soul,
and to experience the sanctifying virtue thereof through her obedience thereto.
And the Lord, who by his grace made her what she was,
was pleased to confer upon her a gift of the ministry about three years before she died,
in which she labored faithfully.

In the Fourth month, 1711, she was concerned to go into Ireland to visit Friends,
and landed at Dublin the same month, accompanied by Anne Chapman, of America;
and they visited several meetings in and about the city of Dublin,
and so passed towards the north of that nation.
Being taken ill with a strong fever, she was forced to keep her bed;
but after the fit was somewhat abated, a meeting being appointed for them,
she was desirous to go, and did: and the Lord was pleased eminently to appear with her,
to Friends`' mutual joy and comfort; but she went no more abroad,
the small-pox soon coming out upon her.
Then she expressed herself, saying, '`Lord Jesus, my spirit waits your coming;
my soul waits for you, my Redeemer.
Oh!
Lord God Almighty, you surely have prepared for me a habitation in the heavens with you.
You it is who make me sensible, that here I am not to stay much longer.
O Lord,
I feel at this time your great love and heavenly
spring of life to refresh and comfort my soul.
Into your arms (for you know it is that I have travailed for) I am ready +++[+++to be received],
Lord;
and you have given me to know that my soul is ready to enter into your everlasting kingdom.
O Lord; for this your great mercy, in affording your servant this opportunity,
I do at this time, in all reverent thankfulness, bless and praise your most holy name,
who are surely worthy forevermore.`'

She departed this life at Colerain, on the 20th of the Fifth month, 1711;
aged about thirty, and a minister three years.

[.asterism]
'''
JOSEPH STONE, Jun., of Witney, in Oxfordshire, was born in the Sixth month, 1683,
and descended of honest parents.
He was educated by them in the way of Friends, and was well inclined when young;
and by the early visitations of the grace of God upon his
heart he embraced the yoke of Christ in his youth,
and as he was taught of his Savior himself to eschew the evil and to do good,
he was the more fit to be a messenger to carry the glad tidings of salvation to others,
and to make known to them what the Lord had done for his soul.
Yet this work he could not undertake,
until it pleased the great Lord of the harvest to gift him for it,
which was in the year 1703.
In this work he labored, according to the ability he received,
by whose ministry the seed and heritage of God was often refreshed;
for the springing of love from the spirit of God in one,
will certainly answer to the same divine principle in others,
and fix it as an evidence upon their hearts, that it is the truth.
He was also exemplary in conduct, and of an innocent deportment.

He loved solitariness, choosing to be much alone,
and approved himself a faithful servant and minister of Christ:
he was zealous for promoting the honor of God,
laboring in word and doctrine for that end,
not only in the neighboring meetings about him, but also in several counties in England.
He had a great concern upon him that he might be instrumental in the Lord`'s
hand for turning the hearts of the children of men from darkness to light,
and from the power of Satan unto God.
In his testimony he was concerned for the hinder-most of the flock;
in prayer fervent for the offspring of Friends,
that they might come to witness the grace of God to save them from a vain manner of life;
for he knew that, though.he had his education among Friends,
yet it was not that alone that did make him what he was, but the grace of God,
as he gave up to be guided thereby.
And because of his experience,
which he gained in yielding to the guidance of the spirit of truth,
he was the more frequent in exhorting the youth of
our day to seek the Lord in their early days,
agreeably to the voice of wisdom, who advised the same of old.

He wrote a short account of his call to the ministry,
with some of his labors and travels therein;
as also the comfort and satisfaction he reaped in his service for truth, as follows:

[.embedded-content-document.letter]
--

After it pleased God, in the riches of his love, to bestow on me a gift of the ministry,
and, by his grace, to call me to and qualify me for the same,
which was in the Ninth month, 1703, I was obedient to the heavenly call,
and gave up freely, but not forwardly, to the call.
And, after some time,
I visited some neighboring meetings in some parts of Worcestershire, Warwickshire,
Gloucestershire, and Oxfordshire.
In the year 1707 I went down to the yearly meeting at Bristol,
and then returned home again, where I remained three years,
only visiting some neighboring meetings, and took one journey to London.
But having a concern to visit Friends in the West,
which rested upon me till the year 1710, I then gave up and went,
though not likely to have a companion but part of the journey.

--

On the 4th of the Fifth month, 1710, he left his habitation at Witney,
and went southward to Abingdon quarterly meeting, where he met with his friends,
John and Thomas Wagstaffe, who accompanied him part of his journey, where they left him,
and returned, he pursuing his journey to the Land`'s-End; from which he returned,
visiting Friends through the counties till he got home,
which was on the 30th of the Sixth month.`'

"`I had a very satisfactory journey,`' says he, '`for the Lord was with me,
and was to me mouth and wisdom, language and utterance;
blessed be his glorious name forever.`'

And his divine presence and glorious power was prevailing in our meetings;
for I had many glorious and heavenly meetings in this journey,
to my great satisfaction and comfort,
and to the comfort and edification of the Lord`'s people.

And it is the desire of my soul that the consideration of the Lord`'s
love and goodness may be a binding obligation to us,
forever to walk in true humility and self-denial before him.
The people who were not acquainted with the work of truth,
were free and willing to come to our meetings in those parts,
and were very attentive to the testimony of truth,
and seemed to be well affected with it, many of them appearing very tender in meetings.
I believe the Lord will add to his church such as shall be saved,
and will more and more bring people off from the idle shepherds of this world,
who feed themselves and not the flock,
and will bring them under the guidance and conduct of his Son, the Lord Jesus Christ,
the everlasting Shepherd, who watches over his flock both night and day,
and feeds them in green pastures of life,
and leads them by the still waters of Shiloh`'s brook,
and will at last bring them to the everlasting fold of rest.

Oh! that all who profess the blessed truth might be faithful to him,
that so they might preach for God in their lives and conduct,
and become instrumental in the hand of God,
to the carrying on that great work which he has begun in the earth,
which must be completed by the spirit of judgment, and the spirit of burning.

[.signed-section-signature]
J+++.+++ Stone, Jr.

[.signed-section-context-close]
The 7th of the Fourth month, 1711

In the Sixth month following, he had a concern to visit Friends westward again,
and went so far as Cirencester, in Gloucestershire; but being taken very ill,
he returned back again to his father`'s house at Witney,
and his illness increasing upon him, proved him sorely.
Yet he continued in much resignedness to the will of God,
and signified that people had need not have their day`'s work to do then,
for there was work enough to bear up under the pain of body;
and desired Samuel Waring to remember his love to all Friends.
In the evening, as he sat by him,
he signified that he did not know how the Lord would be pleased to deal with him;
but for the sake of his dear parents, and others, to whom he might be of service,
he should be glad if the Lord should see fit to spare him;
but he freely resigned his will to the will of God.
But before he parted with him, he told him he was going, and that all was well,
all was well, twice; and desired all to go out of the room, except him, to whom he said,
'`I have seen the glory of heaven,
and it is a brave place;`' and could make his appeal to the Lord, and say, '`O Lord,
you know how I have walked before you,
and served you;`' he having that assurance in his own bosom could call death sweet,
because by it he passed out of this house of clay into the mansions of glory!

When he had been ill a few days, he said to them about him, '`This is ordered for my end,
and it will be well with me my soul shall go to rest.`'
One who was with him said, '`How did he know but the Lord might raise him up again?`'
He answered, '`A man that lived a righteous life,
he believed often knew a little beforehand how it would be with him.`'
His nurse wishing those present were as fit to die as he, he answered,
'`I thank God I have nothing to do but to die; all the world is nothing to me,
I have done with it.`'
But adding, his care was a little for his dear father and mother,
and sister and her children, saying, how would they do without him;
for indeed he was very assisting to them.

Another time he said, '`When I am gone hence, I shall receive a new name.`'
At another time he sent for his father, mother, and sister, to take his leave of them:
his father asked him how he did; he said,
'`Very bad;`' and asking him what he had to say to him, he answered, '`Farewell, farewell,
farewell.`'
Then his mother and sister went, and his sister asked him how he did; he answered,
It will be well with me, and that he was not afraid to die;
he did not fear death if it was that minute.`'
And so departed this life the 30th of the Sixth month, 1711,
and left a good savor and blessed memory behind him.
He was a dutiful son, a kind brother, a faithful friend, and a good neighbor.
He left a small treatise behind him, in manuscript, entitled, '`A Call to the Disobedient,
'`and some other papers.

He was buried at Friends`' burying-ground at Witney, many Friends and others attending.
Aged twenty-eight years; and a minister about eight.

[.asterism]
'''
MARY TURNER, the wife of John Turner at Tottenham High Cross, in the county of Middlesex,
was the third daughter of that remarkable sufferer for the testimony of a good conscience,
Richard Vickris, of Chew-Magna, in Somersetshire, deceased, and Elizabeth his wife,
daughter to that ancient worthy, George Bishop, of Bristol.
In her tender years, by the grace of God, through the care of her religious parents,
she was instructed in, and seasoned with the principles of the holy truth,
as professed by the people called Quakers; in which she continued faithful,
and was an example of piety and virtue through the course of her life.

When a little child, our much esteemed friend William Penn coming in at her father`'s,
where he was very conversant, and affected with her pretty innocent deportment,
broke forth, extempore, thus:

[verse]
____
'`Sweet soul!
What makes you stray
From the angelic way?
Was it to teach us how to love
The happy regions above?
If so, O! let your wandering prove our gain,
And take us with you back again.`'
____

She was naturally of a lively and cheerful temper,
which remained when she came to years of discretion,
yet took pleasure in frequent retirement, and divine meditation, in meetings for worship,
and religious conversation,
and received worthy public Friends with great comfort and satisfaction.
When at home alone, she entertained herself chiefly in reading the Holy Scriptures,
Friends`' writings, and the three first books of Thomas a Kempis,
on the Imitation of Christ; at other times with her pen and needle;
for it was rare to find her unemployed in something useful or necessary,
when her health permitted.
In her dress and apparel she was very neat and plain.
The tenderness of her love and affection to her husband, mothers, brother and sisters,
was more than common) and very remarkable,
and likewise so generally extended to her acquaintance,
especially where truth had a prevalence, that it may be said, love predominated in her.

A few years before her death, she was sensible of a gradual decay of bodily strength,
and when weakness and faintness prevailed,
she bore it with much patience and resignation to God`'s holy will.
In a sense of the uncertainty of the comforts here below,
she wrote thus to a near friend:

[.embedded-content-document.letter]
--

The enjoyments of this life appear very changeable,
and we are apt to seek them more than is good for us, which hinders our inward comfort:
so we have something to war against every day.
I desire you may be directed by that divine hand
which orders all things for our good every way,
as we have an eye to it.

--

[.offset]
And in another to a relation:

[.embedded-content-document.letter]
--

I am very sensible of my happiness,
and desire to walk worthy of the mercies I enjoy;
yet the lack of my health has been an affliction to me: but I do not repine at that,
since it is an advantage to us to have some alloy to the comforts of this life,
which are mostly attended with disappointments of one kind or other.

--

On her bed of sickness she said to her brother,
she admired people should so much place their affections on the things of this world,
which are but as dross, and like traveling in misery;
and earnestly desired their family might, with Jacob, obtain a blessing;
and as they had such worthy parents, who had educated them in the ways of truth,
and enjoyed so many favors beyond many others,
there ought to be a double thankfulness to the giver.
She desired her brother to be a comfort to their tender mother,
and to keep up their honorable father`'s name, as one of the branches of the family,
and then there would be a blessing laid up for him.

Speaking to her sisters, she said,
'`We should be good examples in the plainness of our habits,
as we make profession of the principle of truth, and should take up the cross daily;
for we were not born to serve ourselves, but to honor the Lord.
That pain and weakness were hard to bear and when we are going out of the world,
we had need to have nothing then to do: that she waited for the presence of the Lord,
in which was more pleasure than in all the joys of this world.`'
Then turning to one of them said, '`The Lord has done great things for you,
and may have a work for you to do; there is good seed sown in your heart,
and I desire the Lord will bless you.`'

Having been tendered in her spirit, some friends came to visit her, and prayed with her;
whereupon she said, she saw the Lord had not forsaken her,
but sent his servants to visit her, which was a great comfort to her.

Another time one of her sisters coming into the room, '`O sister,`' said she,
'`the old accuser of the brethren lies very near, but the Lord`'s hand is underneath,
and sweetly supports.`'

Some days after, the same sister being by her bedside,
she had an extraordinary concern for her own welfare and her near relations, saying,
'`Dear sister, I have a steadfast hope, but not yet a full assurance.
I desire you, pray earnestly for me, lest there should be anything committed by me,
that may have slipped out of my remembrance,
and I not be earnest enough with the Lord for forgiveness.
I also pray earnestly for you all, that you may come where I hope to be;
and for my dear husband likewise: '`and expressed her great care,
that not one of the family might be lost.

Another of her sisters, leaving her a little time,
desired the Lord would support her under her weakness, she answered, '`He has,
and I believe will;`' and seemed comfortably resigned in her spirit.

A few hours before her departure she desired to be raised in her bed,
on which she seemed as if she should pass away, and bade all farewell; but reviving,
said, '`I thought I had been going,
but the Lord has given me life from the pangs of death, praised be his name:
oh! praises be to the Lord, he has given me a little ease.`'

Her fear was so great of offending the Lord, that perceiving some disposition to slumber,
she said to her mother, then near her,
'`Do you think he will be angry if I should drop asleep?`'

Some time after, being moved again, she seemed refreshed,
and lay in a sweet frame of mind, praising the Lord, saying, '`Lord, you are merciful,
compassionate and true.
You have given me ease: oh!
I will praise your name at all times, from time to time; every hour,
every minute while I live I will praise you.`'
Being in great pain, she said to some that were near her,
'`He will give me ease by and by;`' and earnestly prayed
to the Lord for it after this manner:
'`Dear Lord, give me ease: sweet Lord Jesus, give me ease;`' and then said to her sister,
he would.
Her sister said, she did not doubt but the Lord would answer her desire,
and give her a full assurance; to which she answered, '`I believe he will.`'
Then she desired those by her to pray for her.

Having slumbered a little, she awoke refreshed, and looking on one of her sisters,
she said to her, '`Dear sister, I shall do well, I shall do well.`'
After which she was heard very sweetly in prayer to the Lord to receive her;
and was sensible to the last.

Toward the conclusion of her days,
her weakness was attended with such faintness and pain, sometimes,
that it made her apprehensive it would be very hard
to bear the struggles of her final dissolution,
which she frequently begged of the Lord to make easy;
and he was pleased to answer her desires accordingly;
for she passed hence almost without sigh, groan,
or any visible alteration of countenance.

She departed this life at Tottenham aforesaid, on the 31st of the Sixth month, 1711,
and was decently interred in Friends`' burying-ground in Bunhill-fields, at London,
on the 5th day of the Seventh month following, about the thirty-third year of her age.

[.asterism]
'''
THOMAS DOCKERY, late of Silverdale, was born in Cumberland, near Portinscall,
brought up a scholar, and was reader at Withburne Chapel, in that county;
and being a sober young man,
and having inclinations in his heart after the true worship of God, which is spiritual,
it pleased the Almighty to open his understanding,
and to show him the mysteries of the kingdom of life and salvation,
and the emptiness of the ways, forms, and traditions of the world, and the evil of them,
wherein he had been, among many others.
He was concerned in love, to go to their public places of worship,
and bear a testimony against them; and what wages he formerly had received for reading,
as aforesaid, he carried back and left it with the people,
and told them they were the wages of unrighteousness, for which he could not keep them.

Being joined in society with friends, he grew in the truth,
and became very instrumental in the service of the gospel,
for the confirming of friends in the faith,
and information of such as opposed the truth.

After some time he was drawn forth, in the love of God,
to visit friends`' meetings in England, Scotland, and Ireland.
Five times he visited friends in Scotland, and three times in Ireland;
and at his returns had great peace and satisfaction.

Once at Aberdeen, in Scotland,
the envious priests incensed the magistrates against friends, and he was put in prison,
and remained there about three months;
but the Lord`'s love and presence he enjoyed therein, and great was his peace;
for he experienced the Lord`'s power to preserve him,
and the truth was set over his persecutors, and they set him at liberty.

Then he returned into Cumberland, and abode there a considerable time;
and from there went to Swarthmore, in Lancashire, and continued several years.
Also several times accompanied G. Fox to London, and elsewhere,
in the service of the gospel.

In the year 1683, he settled in Silverdale, in Lancashire,
and belonged to the Yelland meeting and continued
a member of the said meeting above twenty-seven years,
being a diligent attender thereof.
Notwithstanding he was weak and infirm in body for several years before he died,
yet he was frequent in testimony, to the edification of friends,
and the understanding of others.

He was exemplary in humility and lowliness of mind,
lived in peace and unity with friends, and was well esteemed among his neighbors.
When his outward strength decayed, that he grew weaker in body, he was always content,
and after he took to his bed he continued several weeks,
not being much afflicted with pain, the Lord dealing gently with him;
yet he grew weaker and weaker; and when asked how he did, replied, '`Very weakly,
but well content to die, and be removed to eternal rest with the Lord,
whom I have served; which is now to me great satisfaction and content.`'

He continued very quiet in his mind, and sensible to the last,
and as he had lived in peace and unity with Friends,
he died in the same the 6th of the Tenth month, 1711,
and was buried at Friends`' burying-place at Yelland, the 8th day of the said month,
about the eightieth year of his age, and a minister of the gospel fifty years.

[.asterism]
'''
MARY POST, daughter of Benjamin and Elizabeth Post, of London, was of a tender spirit,
sober behavior, religiously inclined, and a lover of plainness in habit and speech,
and kept to it; but a disliker of pride and finery in apparel.
When but about eight years of age, she was at a neighbor`'s house who desired her company,
being solid and grave,
and the said neighbor having a daughter about fifteen years of age,
who loved this child well; Mary said to her, '`Anna,
what signify these fine things you have on?
they will not carry you to heaven.`'
To which Anna answered, '`Pride is not in the things, it is in the heart.`'
To which the child replied,
'`But if your minds (i. e. those that wore them) were not proud, you would not wear them.`'
She also signified to her mother,
that she much wondered at the great pride she observed
in some young ones who professed truth,
saying, '`I hope I shall never be like them.`'
Her mother thereupon said to her, '`I hope you will never be like them;
but be an orderly child, that you may be in favor with God.`'
At which she wept, and said, '`If I should love fine things, I must alter much:
what signify fine things when folks come to die?`'

Hearing some boys in the street taking God`'s name in vain, she said,
'`They take God`'s name in vain enough to frighten one.`'
She also said she should delight to go to meetings.

The day before she was taken ill, her mother sending her out on an errand,
and her brother being newly come out of the country, she desired him to go with her,
which he refused; at which she stood by him a while,
and then with a solid countenance said, '`Will you not go with me?
It may be, the next time you come up,
you may not have a sister to go with;`' as if she had a sense of her death.

In her sickness, which was violent convulsions; she often said, '`Oh! dear Lord,
if you see fit, give me a little ease: '`and lifting up her hands,
repeated such like expressions, and said, '`I had rather die than live;
through mercy I am not afraid to die-I shall go to rest,
where I shall feel no more pain.`'

Her mother standing mourning by her, the child looking upon her, said, '`Mother,
do not cry, let us be contented; the Lord can lay me low, and he can raise me again;
if I were dead, he can raise me again:`' then she repeated as before, '`Oh! dear Lord,
if you see fit or convenient, give me a little ease`' and seemed earnest to die,
and go to rest.
Her mother said to her, '`My dear, why are you so earnest to die;
the Lord can ease you of your pain, and give you life?`'
She answered, '`One must once die, and if I recover I must or may be sick again;
and I had rather die while I am young.
If I should live till I am older, the devil may tempt me to be naughty,
and I might offend the Lord.
I am not afraid to die, through mercy I shall go to my rest;`' and said,
'`If I live I am satisfied, and if I die I am satisfied.
I am willing to die; I had rather die than live.`'

Her mother said, '`I shall dearly miss you.`'
She replied,
'`I am willing to see my little sister (who was at nurse)
and my brother;`' and he was at school in the country.
Her mother said she would send for them: '`but,`' said the mother,
'`if any alteration should be before your brother come, what would you say to him?`'
She replied, '`If I can speak, I will bid him be a good boy, and fear God,
that he may go to God Almighty.`'
She left him the little money she had; and some other things to her father, mother,
and two sisters.

Her mother desiring her to take something (as she
had before done) that was prepared for her,
she seemed to refuse, and said, '`What signify doctors and apothecaries,
if the Lord please to take one`'s life?`'

A little before her end, she lamented folks taking pleasure,
and not considering the love of God; and the last words she was heard to speak were,
'`Dear Lord God Almighty, open the door.`'
And so sweetly departed this life, the 12th of the Eleventh month, 1711.
Aged above eight years.

[.asterism]
'''
RICHARD PRIESTMAN, of Coldbeck, in the county of Cumberland,
was descended of honest parents.
His father received truth early, and finished in the same; and his son,
the said Richard Priestman, was educated in the way thereof;
yet was at a loss till he found truth in himself,
and came to know the work of it in his heart, and came to be faithful thereto.
In due time, the Lord, whom he loved, was pleased to give him a gift of the ministry,
whereby he became a minister of the gospel,
and declared to others what great things God had done for him.

Though he was not large in testimony, yet his ministry was edifying,
comforting the weak travelers, who were on their way towards Zion,
often supplicating the Lord for the preservation of his people,
and that he would be pleased to continue his love and kindness towards them.

He labored to keep peace, and things in order, where his lot was cast.
He was against that which tended to division and scattering;
he walked in the fear of the Lord, with fervent desires in his heart to Almighty God,
that he would be pleased to give him strength, that he might be preserved in well-doing,
and kept steadfast iii the faith, which overcomes the world, to the end of his days.

In the time of his sickness, his spirit was borne up, to his great comfort,
and many came to visit him, to whom he expressed the comfort he felt in his heart.
The more his afflictions increased, the more his strength was renewed in his inward man,
and he would be often speaking to his family, and said, '`Know the Lord for yourselves,
and mind the teaching of his grace in your hearts;
you need not go far to seek for a teacher.`'
With the like expressions, he often exhorted them and many others who came to visit him,
and said to his neighbors, '`I advise you to make your peace with God,
while you are in health and strength; for when you are cast upon a sick bed,
you will have enough to bear your sickness.
Do not delay, and have your peace to make with the Lord at last.`'
With many more expressions he exhorted them,
and was much refreshed in spirit in having such opportunities.

The night before he departed this life, he called his family to him,
and took his last farewell of them, and said, '`Keep to truth, and do justly,
and do to every one as you would they should do to you; and the Lord will bless you,
and keep you from evil.`'

He finished his course in perfect unity with the brethren,
the 23rd of the Eleventh month, 1711.

[.asterism]
'''
WILLIAM RIGGE, of Coltshouse, near Hawkshead, in the county of Lancaster,
received truth in the year 1672, being the thirty-sixth year of his age.

A little after he received a gift of the ministry, in which he was faithful,
and endowed with a good understanding, in the mysteries of the kingdom of God,
and had a clear and sound testimony, and travelled much in the work of the ministry,
both in this nation and in Scotland, although he was a very tender-bodied man,
and troubled with a sore cough for many years.
It was his delight to be speaking of the things of God, and the mysteries of his kingdom,
to the refreshing of many.

Towards his latter end he was attended with great weakness of body,
so that he could not get to the meeting, or scarcely out of doors for many weeks,
which he bore with great patience,
and to the great comfort and refreshment of many that came to see him.
He was of a clean life and conduct, which answered his testimony.

In the time of his weakness he waited patiently for his dissolution, and often said,
'`I have done my day`'s work in the day time, to my great peace and satisfaction,
and have nothing to do but to die, and put off this earthly tabernacle,
being well assured of my eternal rest with the Lord:`' into which, no doubt,
he is entered.
He died the 29th day of the Second month, 1712; aged seventy-six,
and a minister about forty years.

[.asterism]
'''
SAMUEL GEORGE, of the parish of Landewybrevy, in Cardiganshire,
lived there with his parents till he was about twenty-one years of age.
In which place the excellent truth, being despised by many,
had not that place and dominion in the hearts of the people, which it ought to have;
and he was careless, like others, going on in the broad way,
playing and sporting therein,
and unconcerned for the everlasting welfare of his poor soul.
But the Lord met with him in the prime of youth, opened his ears,
and sealed instruction to him in a dream, or vision of the night,
as he lay slumbering upon his bed.
In which dream, or vision, he thought he was going to hear that called divine service,
and saw a man winnowing corn, which seemed to him to be good and sound,
but when raised to the wind, it was blown and scattered away, like white chaff,
towards the north.
And as he looked behind him, he saw a man who asked him, whether he knew what that meant?
he answered, '`No.`' Then, said the man, '`the chaff represents ungodly men,
who are as the chaff which the wind drives away.`'

By this, and other dreams and visions which he had, he came under a concern of mind,
and cried out, '`What shall I do to be saved?`'
Then it pleased the Lord, in his infinite love and mercy,
so to visit the heart of this young man, that he came to know the Lord,
and was made willing to bear the indignation of God because he had sinned against him.
And the Lord by his invisible power wrought his deliverance,
notwithstanding he allowed him to be tried many ways;
and when under great and deep exercises, both inwardly and outwardly,
the Lord was pleased by his hand to help him in the time of need,
of which he was greatly sensible,
and experienced the great truth declared by the holy prophet of old, that,
'`Zion shall be redeemed with judgment,
and her converts with righteousness;`' although he had been
ready to think no one was exercised like him.

He often used retirement, and in the night-season, and at other times,
he waited upon the Lord, pouring out his soul in supplication,
and fervently prayed unto him in secret; and the Lord rewarded him openly,
and many times gave him the oil of joy for mourning.

On the 26th of the Sixth month, 1711, the Lord opened his mouth to declare in his power,
and to bear his testimony against unfaithfulness and disobedience to the Lord.
And the Lord made him also sensible,
and gave him a sight that his time was but short to work in his vineyard; so,
although his service was heavy and hard, he labored diligently.

About six months after, he travelled and visited
Friends at their meetings in Radnorshire; and about two months after,
he did the like in several counties, as Merionethshire and Montgomeryshire.
And when he had eased his mind, and finished his service for the Lord in those parts,
he returned home.

In a little time after, he went to the yearly meeting of Wales,
at Llandiloes in Montgomeryshire, and after his return had but three meetings.
The last was the 4th of the Third month, 1712, where many people came in, and he,
in great tenderness to those who had true desires in their hearts after the Lord,
preached to them in much love and fervency,
and his words and doctrine were as the dew falling on the tender grass.
Afterwards, in great concern of spirit and in trembling, he thundered against the light,
airy, and hard-hearted ones, who slighted and reproached the truth and its followers,
and spoke evil of that they knew not,
telling them the Lord would plead with such in his righteous judgments;
and he exhorted them to repent speedily,
lest the Lord should cut them off in his fierce anger.

On the sixth of the Third month following,
it pleased the Lord to visit this zealous young man with an indisposition of body,
and a voice run through him, '`Put your house in order, for you must die.`'
And he declared he was willing to give up all to the Lord,
to dispose of him as seemed good in his sight.
Feeling the Lord`'s power over all, his heart was refreshed, and he declared,
"`Blessed are the dead that die in the Lord, from henceforth; yes, says the Spirit,
that they may rest from their labors, and their works follow them.`'
He charged his brother, John George, who gives this relation,
that these things should not be forgotten, and fall to the ground;
and bade his said brother give him up freely, adding,
if he and Friends continued faithful the Lord would
be their helper and sufficient support.

Afterwards he called for his parents, and spoke to them, saying,
'`I do not expect to recover from this sickness, but be not overmuch concerned;
for I have peace with God, and had rather, if it is the Lord`'s will,
die than live any longer.`'
He desired them to prize their time,
and seriously consider how precious a thing it is to know peace with God, their maker,
on a dying-bed.
He valiantly bore his testimony for the precious truth in their presence,
and showed the barrenness of men-made ministers, who plead for sin and imperfection;
advising his parents to beware of hindering any of their children,
his brothers or sisters, from coming into the way of truth;
and desired them rather to encourage them therein.
He exhorted his parents, saying, '`Give up all,
that you may have an inheritance in that kingdom wherein there is no trouble nor sorrow,
but eternal joy and peace.`'
He likewise exhorted his brothers and sisters to be faithful
to that which the Lord had made known to them of his will.
He often heartily prayed for them unto Almighty God,
that none of them who had turned their faces Zionward,
might look back into the world again, but might all press forward.

Some days before his departure he fervently said,
'`Remember my love in Christ Jesus unto all my faithful
friends and brethren in the incorruptible Seed;
to which seed the promise is,
and wherein peace and acceptance with God are livingly known.`'

He finished his course here the 18th of the Third month, 1712, aged twenty-five years,
and a minister about nine months.
