== Chapter 3

[.chapter-synopsis]
* John Airey
* Peregrine Musgrave
* Joshua Arnold
* George Benson
* Roderick Forbes
* Robert Fisher
* Ruth Padley
* Eleanor Perkin
* Richard Kinman
* Susannah Garton
* Phebe Doughty
* Taner Costard
* Rebecca Toovey
* Joseph Grove
* Esther Champion

JOHN AIREY, belonging to Sedberg meeting, in the county of York,
was convinced of the blessed truth, as professed by the people called Quakers,
about the twenty-ninth year of his age, and was of an innocent life and good conduct,
and faithful in every branch of his testimony relating to truth.

It pleased the Lord to commit to him a dispensation of the gospel and part in the ministry;
and although he was not large in testimony, yet had the movings of life upon him,
which made his offerings acceptable to Friends.

As he lived a harmless and innocent life, so,
when he came to be tried with much bodily weakness,
which attended him for several months before he died, he bore it with much patience,
and was very sweet in his spirit, and often said to friends,
It is a precious thing to wait upon God, to feel his life,
power and presence to quicken and raise us up to praise his powerful name,
who is worthy forever.`'

He departed this life the 15th of the Fourth month, 1712,
in the sixty-ninth year of his age.
He was one that held out unto the end,
and partook of the salvation of God through the Lord Jesus Christ.

[.asterism]
'''
PEREGRINE MUSGRAVE was born at Lanyna, in the parish of Lanynarth,
and county of Cardigan, the 4th of the First month, 1643.
He was by trade a clothier, and of good repute among men;
and the Lord endued him with wisdom and understanding,
whereby he was very serviceable in the church,
especially in meetings of business and the care of the poor.
Great concern was upon him that Friends might be preserved in love and unity;
and where he saw anything that tended to the breach thereof,
he earnestly labored to put a stop to it, both at home, and in the adjacent counties.
His heart and house were open to Friends,
and he had great delight in the conversation of faithful brethren;
and it is not doubted but he laid down his head in peace with the Lord,
and`' he himself signified the same in the time of his sickness.

In which time his wife and daughters sitting in the room by him, and seeing him so weak,
his daughter wept; he hearing her, said, '`Susanna, make no noise for me.
What would you children have?
Your father has lived to a good old age, and I die in peace with my God,
and in credit with men.
I leave no stink behind me, which is a mercy to you beyond many children.
I desire you to be satisfied, and give me freely up,
and let your concern be inward;`' adding, '`I want to see your brother and his wife,
and your husband, that I may ease my mind to them.`'

Then he asked if it was day; his daughter said, It is not.`'
He said, '`Call your brother and his wife.`'
When he came, he said, Lewis, I find this distemper come so hard,
that I am not likely to continue long.`'
He gave him good advice in many words, and withal desired him to keep close to meetings,
and not to forget week-day meetings; and to mind truth, which would adorn them above all;
and said, '`Be serviceable to Friends, and stand a man in my place.
My dear Lewis, remember what I say, live in love: you have a pretty many relations here;
if you keep your places and live in love, you may be a comfort one to another.`'
He called for his daughter-in-law, and took leave of them, and said,
'`I pray God bless you and your poor babes.
I desire you, be tender of them in bringing them up.`'
Then he kissed them and said, '`I have not much more to say.`'
So continued very sensible all the day, and often said, '`Dear God,
I pray you make my passage easy;`' and said,
'`the love of God is more to me now than all the world.`'
He took leave also of his neighbors and friends,
and seemed to be cheerful and willing to die.
He departed as if he had been going to sleep, and was very sensible to the last,
which was the 14th of the Fifth month, 1712.
This worthy old man was honorably and decently interred at East-hookit,
the 16th of the Fifth month, 1712, aged sixty-nine years.

[.asterism]
'''
JOSHUA ARNOLD, of Whittington, in the county of Derby,
was educated in the blessed truth among the people called Quakers;
and was by occupation a carpenter, and much employed by the great men,
being just and honest in his dealing, moderate and temperate in his life,
and in his conversation Christian and exemplary,
so that therein he preached to professors and profane:
being faithful to the witness of God in his own heart, he answered it in others.

The Lord, who made him what he was,
at times was pleased to open his mouth in the assemblies of his people, that he,
in a sense of the goodness of God, did bear witness thereto.
In true love he exhorted Friends to watchfulness,
and to keep their conduct clean and void of offense towards God and man,
and to dwell in that which would keep them humble,
and ever to avoid pride and covetousness;
to wait patiently for the appearing of the Lord,
and to hear his still small voice in their own hearts; and for the arising of life,
that they might be taught, kept, and preserved thereby,
so that they might bring no reproach upon the holy truth they professed.

This was the earnest desire of this godly man, who was indeed a good example,
both to the great men with whom he was concerned, and to his family, friends,
and all he conversed with: in moderation, plainness, and the fear of God he lived,
and thereby gained a good report and the love of many.

He took opportunities to wait upon the Lord in silence in his family;
and many times the Lord was pleased to take such notice of them in those retirements,
as to break in upon his children,
and manifested his powerful presence to the edifying
and encouraging them and the whole family,
to take up the cross of Christ and follow him.

In a sense of the vanities of this world, he said, some years before he died,
he was willing to leave it,
and did often advise his family to be humble and lowly in their minds,
and to love the truth, which he recommended as the best portion to his children.

About two years before his departure he was much afflicted with lameness and weakness,
by reason of the palsy, that had attended him some years before,
so that he was confined to his room, and seemed not likely to recover.
Then he advised his family both in spirituals and temporals;
but he so far recovered that he could go to meetings, and did,
till it pleased the Lord to visit him with a return of his distemper so suddenly,
that his dying words were but few; but while his speech remained, he said he was well,
and in a little time all would be well.
Then one of his children coming to his bedside, for he was seized in his bed,
he held her by the hand, and seemed overcome with the presence of the Lord;
but had neither strength nor utterance to speak, and presently falling into a deep sleep,
departed this life, it is believed, without any sensible pain,
the 16th of the Sixth month, 1712, and was decently interred;
and as his friends and neighbors believe and are satisfied, he is at peace with the Lord.
Aged about sixty-four years and four months.

[.asterism]
'''
GEORGE BENSON, of Strong End, in the parish of Hawkshead, in Lancashire,
was convinced of the unchangeable truth in his early years,
near the breaking forth of the same in those parts,
and was a very faithful man to his conclusion,
being often exposed to various kinds of suffering,
both by reason of keeping meetings at his house,
and in other respects relating to the several branches of the ancient testimony of truth,
which faithful friends in that time were liable to:
all which he bore with much patience and courage.

Toward the latter part of his time his mouth was opened in a public testimony,
and he travelled into some neighboring counties in the service of truth.

He was a faithful minister, according to his measure,
his life and conduct being also answerable to his ministry.
In the time of his sickness he gave much good advice to his family,
warning them to keep to truth, and out of the love of this world.
He dropped several comfortable expressions to such as came to see him,
saying he had done his day`'s work, while the day lasted,
and had nothing to do but to die.
He departed this life in great peace with the Lord, the 19th day of the Eighth month,
1712, being in the seventy-sixth year of his age.

[.asterism]
'''
RODERICK FORBES, son of Arthur and Elizabeth Forbes, of Brux, in Scotland,
was a man of great reputation in the world.
In his youthful days, he had some knowledge of the principles of the Christian religion,
as held by the people called Quakers, and walked soberly for a time;
but his elder brother dying, he became heir to the estate.
Then he left the narrow way, and threw off the cross,
and continued without a due sense of his loss, till about the year 1702,
after the death of his worthy mother, who in her lifetime was greatly concerned for him,
and desirous that the Lord would visit him,
and bring him into the knowledge and obedience of the holy truth.
And accordingly it pleased the Lord to reach unto,
and awaken him by his righteous judgments, and by his divine power humbled him,
and caused him to sigh and cry to the Lord,
who was graciously pleased to answer those desires
and earnest cries that he begat in him,
and brought him not only to behold the dawning of his gospel day,
but in a spring of love to his soul, enabled him clearly and boldly to own the truth.

This caused the priest to visit him, who pretended a concern,
that one of so honorable a family should be deluded, as he apprehended;
to whom Roderick said, '`If the Lord were pleased to awaken and touch your conscience,
as he has done mine, he would make you quake,
every joint of you;`' which stopped the priest so that he said no more.

By this principle of truth was this visited man taught and
strengthened to leave his loose and debauched companions,
and to live a sober and godly life, to the astonishment of his former associates,
who admired to see such a wonderful change wrought upon him;
for he indeed now adorned the doctrine of God his Savior in his life and conduct,
walking according to the convictions of the grace of God,
in solidity and weightiness of spirit.

In the year 1712, in his return from London, he was taken sick at Edinburgh,
but retained a perfect memory, and was minded to make some alteration in his will,
which he did,
being greatly concerned for the good education of his children in the way of truth;
and gave directions for his burial, and the manner of it;
directing that his body should be interred in his own burying-place,
by his father and worthy mother, and two children of his own,
after the plain and decent way of Friends.

He was afterwards much exercised in prayer to God,
and thankfulness to him for his visitation,
and assisting him to bear a faithful testimony to the blessed
truth he had brought him to the knowledge of,
saying, "`As the hunted deer pants after the water brooks,
so has my soul panted after you,
O Lord.`"'`I can bear witness that truth is truth;`' and turning to his wife, he said,
'`My dear, you know it to be so, and I know you are convinced of it;
therefore be faithful to it.`'

About two hours after, he desired to be set up in his bed, saying,
I am now in readiness to go;`' and immediately the pains of death seized on him;
which though they were violent, he endured with patience,
and was borne up in a Christian courage, triumphing over the powers of death; saying,
'`The truth is precious, cleave unto it; yes, more precious than the gold of Ophir:
it has delivered me from many infirmities.`'
One standing by, said, '`Trust in God and he will deliver you.`'
He answered, '`I have good cause to trust in him, he never failed me:
and now I feel his presence supporting me in the very agonies of death; yes,
on the very brink thereof I can and do rejoice through Jesus Christ my Savior and Redeemer.
I feel his hand above me and below me, supporting me; and I defy all the powers of hell.
I have seen their strength and their malice, they have not prevailed: praises, praises,
oh! everlasting praises to his ever-blessed name.`'

Then seeing some about him weep, he said with much concern, Why should you be troubled;
since I undergo the agonies, you may look on: a small time will put an end to it,
and I have a view of my journey`'s end.
I am entering the joys thereof already, where I shall enjoy everlasting happiness.`'

In this condition he continued for some hours,
and in intervals speaking always very sensibly,
and recommended his dear wife to the tender regards of friends as a widow:
and then desired R. Barclay to hold up his head in the time of his greatest agonies,
till his speech began to fail; so that he could utter but broken sentences,
the last of which that was distinctly known, was,
"`Unless your righteousness exceed the righteousness of the Scribes and Pharisees,
you shall in no wise enter into the kingdom of heaven.`"

So having given before a great deal of good advice to all about him,
to leave nothing to a dying bed, and to prefer the truth above all,
with much more not noted, about the eighth hour in the morning his speech left him,
and he lay only breathing until about the fifth hour towards evening,
and then quietly resigned up his breath without any struggling.
He died in the Eighth month, 1712, and was buried according as he desired;
aged forty-two, and convinced about ten years.

[.asterism]
'''
ROBERT FISHER, late of Preston Patrick, in the county of Westmoreland,
was convinced of the blessed truth by the ministry of that ancient servant of Christ,
John Banks, at a meeting at Dalehead in Cumberland, his native country,
and with gladness of heart received the truth in the love of it,
and faithfully walked therein.
And the Lord not only gave him to believe, but, being faithful,
gave him also a part in the ministry of the gospel, and he testified to the holy truth,
and preached the word of reconciliation.

In which work, according to his measure, he was a faithful laborer,
though he did not travel much abroad, neither was his testimony often known to be long,
but comfortable and refreshing to the faithful.

He was also a faithful sufferer for that testimony,
which the Lord raised in his heart to bear against the anti-christian yoke of tithes,
for which he many times suffered the spoiling of his goods,
although his outward substance was but very small;
yet he stood true and firm in his testimony to the end of his days.

He began to be ill on the 26th of the First month, 1713,
and his sickness increased and was very sharp upon him;
yet he was preserved in a comfortable frame of spirit,
patiently enduring those bodily infirmities he was under,
and much resigned in his mind to God`'s will,
sounding forth praises to his great and excellent name,
and often expressing the great satisfaction and comfort
he felt from the Lord under his exercise.

Some few hours before his death, his wife sitting by him, he said,
I feel the power and presence of the Lord to be with
me;`' and though weakness of body was upon him,
yet he felt that hand and arm of divine power, which in times past had preserved him,
to support and bear up his spirit over his exercise;
with several other words to the same effect, which are not perfectly remembered.

After this his sickness renewed, and was very sharp upon him for a small time,
but then abated; and then he took leave of his wife, and bade her farewell;
and soon after passed away as if he had fallen into a sleep,
without either sigh or groan, the 30th of the First month, 1713,
and was buried the 1st of the Second month following,
in Friends`' burying ground at Park End, in Preston Patrick,
aged about seventy-three years.

[.asterism]
'''
RUTH PADLEY, wife of John Padley, of Shad-Thames, in Southwark, timber merchant,
and daughter of Richard Parkes, of Hook-norton, in the county of Oxford,
was a woman who truly feared the Lord, and loved his truth and people,
very sincere and upright in her conduct among all,
was very affectionate and loving to her husband,
kind and loving to his children he had by a former wife,
dutiful and tender to her aged parents, tender and loving to her brothers,
sisters and other relations, compassionate to those under affliction,
and ready to sympathize with them, charitable to the poor,
and in an especial manner to those of the household of faith.
She was in her conduct so adorned with a meek and quiet spirit, as made her lovely,
and therein was very exemplary; as also in plainness of apparel, becoming her profession,
and in using the plain language to all, and in calling the days according to Scripture,
which, although by some it may be looked over but too lightly,
yet is what many have witnessed the spirit of truth, which leads into all truth,
to lead them into.
She also hated deceit, and was more in substance than in show.

She passed the time of her sojourning here in fear,
as one that had an eye to another country, namely, a heavenly;
of whom it may be truly said, she was of the number of the wise virgins,
whose lamps were burning,
and so ready to enter with the bridegroom into the marriage chamber.

She was visited with a declining distemper several months before she died,
and although much means were used for her recovery;
yet her distemper increased fast upon her, which she bore very patiently,
and was resigned.

Some little time after she was taken ill, she had a prospect of her departure hence,
which was pleasant to her, but she avoided speaking thereof to her husband,
till a little before her end, lest he should be over-earnest in desiring her life,
and said, Her Maker laid nothing to her charge,
and that she was sensible he had regard unto her.`'

At another time, to her sister, E. Vokins, she expressed her assurance,
saying she did not question having a place in the kingdom.
At another time, she signified to her said sister her dear love to her husband,
that she never could be displeased with him for any thing,
and although his company was so desirable to her, she was very willing to give him up;
and said she would have him mind his Master`'s business.

To a niece, of whom she had a tender and motherly care,
she advised and desired that she would take up the cross while young; saying,
it would be harder if deferred,
and that she had been well rewarded since she took it up.

To her sister E. V. she expressed her satisfaction with her company in her illness,
saying that she had been a great comfort to her since she came.

About two or three hours before she departed, being in prayer to the Lord,
but her voice low, her niece asked her what she said; her answer was,
she was speaking to her Maker.
About two hours before her departure, she said to her niece,
'`You may think my affliction hard, but it is not;
my Maker has dealt very graciously or mercifully with me, more than I can express.`'
Her niece asked her if she thought it would be harder; she answered,
she did not think it would; adding, but if it should,
she doubted not but her Maker would support her under it.
And when her said niece asked her where she would have her dwell, her answer was,
'`Where it may be best for your soul.`'

About one hour before she died, she said,
'`Be sure to remember my dear love to my brother John, and to all friends.`'
Afterwards, she said to her husband,
'`O my dear!`' which were the last words that were heard;
but lifted up her dying hands and eyes as a sign of her breathing to the Lord in spirit,
and so departed this life, and entered into everlasting rest with the Lord.
She died the 26th of the Second month, 1713,
and was buried from Horslydown meeting the 30th of the same,
and several living testimonies were borne on that occasion.
Aged about thirty-four years.

[.asterism]
'''
ELEANOR PERKIN was born in the parish of Hemsterly, in the county of Durham,
and at the age of seventeen years was convinced of the truth.
She was of a sweet and innocent conduct, and of a meek and humble spirit,
desirous to be conversant with such as feared God.
She was taken ill the latter end of the Sixth month, 1713.

In the time of her illness she was much resigned to the will of the Lord,
whether to live or die.
A friend asking her whether she desired to die rather than to live, she answered,
'`I desired that long since.`'
Again she was asked if she had any trouble upon her mind about any thing; she replied,
'`No.`' Then it was queried of her whether she thought she should be accepted of the Lord;
she answered, she hoped she should; and supplicated the Lord in a heavenly frame of mind,
to the reaching of the standers by,
and the Lord`'s goodness and presence were felt and witnessed;
and she desired those present to be ready when the Lord called for them, saying,
'`You know not whether he may call at midnight, or at cock-crowing,
or at dawning of the day.`'

One time, being under great affliction, she said, '`Lord, give me ease,
and grant me patience;`' which in a little time she received,
and she made her acknowledgment to the Lord for the same, saying, O Lord,
when I get any ease, it comes from you.`'
A relation of hers being by, desired a book to pray, or read prayers by her,
to whom she answered, with respect to prayer, that it was beyond books.
She spoke of the goodness of God, and what he had done for her, saying,
'`I desire I may praise him while I live.`'
And to her sister she said, '`I desire you may be a good child,
and the Lord will love you; for the Lord loves all that draw near to him.`'

One evening several of her friends came to visit her,
and sat down in silence waiting upon the Lord;
in which time his presence was wonderfully felt and witnessed among them,
insomuch that she, with several others, were broken into tears and sweet harmony,
with some words she uttered, which were not noted.
A friend then present kneeling down to prayer, supplicated the Lord for her.

After one had taken leave of her, Eleanor said, '`My dear friend,
the Lord be with you and with me.
Oh! that I may praise him while I have a day; for he is worthy,
for his great mercy and kindness this day.
Truth is precious: Oh! that every one would come to it,
and that many would come and taste of it.
Oh! that I may take straight steps while I am here; for good is the Lord:
he has been very good to me all along.
Oh! that many were partakers of his goodness; for the Lord has been wonderfully good to.
me. Oh! what this truth is, that many may know and be partakers of it,
and that we may honor the Lord, for he is worthy; he is worthy of all honor.
The Lord was never so good to me as now.
This was a good opportunity.`'
With many other words, which, by reason of her weakness, and her voice being low,
could not be well understood; but she remained sensible to the last,
and on the 8th of the Eighth month, 1713, she departed this life,
and was buried the 11th, at Raby, in the county of Durham.

[.asterism]
'''
RICHARD KINMAN, an ancient friend, who was truly owned and in unity with his friends,
and of an upright and blameless life and conduct; and loved the truth,
and sometimes bore testimony to it in meetings.

A little time before he departed this life, he said, '`I know my Redeemer lives,
and that he has done that for me none else can do;
and I believe it will be well with me.`'
With which testimony friends declared their unity.

This, though short,
is published to show how this honest ancient man retained his integrity,
died in the faith, and obtained a good report.
He died the 23rd of the Tenth month, 1713, at Bishampton, in Worcestershire.
Aged seventy-two years,

[.asterism]
'''
SUSANNAH GARTON, widow of William Garton, late of Ifield, in the county of Sussex,
was one who in her young years received the blessed truth in the love of it,
and walked faithfully therein to the end of her days.
It may be truly said she was a mother in God`'s Israel;
a preacher of righteousness in her day, not so much in words as in life and conduct;
though it pleased the Lord, towards her latter days,
to bestow on her a gift of the ministry, which, though small,
was very sound and acceptable.

She was always of a meek and lowly mind, not esteeming herself upon, or because of,
any service she was found in; but was humbled in thankfulness to the Lord,
for that he had in any measure counted her worthy,
and enabled her to be serviceable in the church,
thinking no service therein too mean for her to be employed in.
She was given to hospitality, was an entertainer of strangers,
willing to wash the disciples`' feet, took care of the widows and fatherless,
and visited the afflicted.
To do good and communicate, as the Lord had blessed her, she was not unmindful;
for with such sacrifice she knew the Lord was well pleased.

She was also a cheerful sufferer with her dear husband for the testimony of truth,
being often left to manage his affairs in the world,
while he lay in prison for his testimony against tithes,
and sometimes for meeting to worship the Lord.
All which she bore and went through with great cheerfulness and zeal for the Lord,
rather counting it all joy or rejoicing,
that they were counted worthy not only to believe,
but also to suffer for the Lord Jesus Christ`'s sake,
whose love and favor was more than all the world, or the enjoyments that were therein.
Therefore they did not reason with flesh and blood,
but were faithfully given up to serve the Lord with all that he had blessed them with,
believing the righteous should never be forsaken,
nor their seed be found begging their bread, if they likewise followed their steps.
Words are indeed too short to set forth the worth and value of such elders,
who through faith and patient suffering have obtained a good report,
and left a sweet savor behind them; of whom it may be said,
though their bodies be dead their spirits live,
and their memorial is sweet to the living and sincere in heart,
who had acquaintance with them,
who will in their hearts set their seals to this testimony.

This worthy woman was also a pattern of great plainness,
and was often grieved to see and hear of the superfluity
that abounded among some of the professors of truth,
and the undue liberty they took, saying, '`It was not so in the beginning,
for then there was nothing too near and dear to part with for truth`'s sake.`'
She was likewise much troubled to hear the needless vain talking, foolish jesting,
and see the light and airy carriage among such, that were unbecoming our holy profession,
saying, '`Time ought not to be so spent,
for an account must be given unto God for all these things.`'
It pleased the Lord to preserve her out of such things to the end of her days,
and it is not doubted but the Lord has given her a portion among his redeemed ones.

What can be written cannot add to her virtue or happiness,
but is written in fear and true love,
with desire that those into whose hands it may come,
may be encouraged to hold on their way,
and that drooping souls may look unto the Rock that followed the ancients,
and was with them in all their tribulations.
Unto which Rock they now sing praises, and render honor, glory and thanksgiving forever.
Amen.

It was the care of this worthy matron to walk circumspectly in the time of her health;
and`' when it pleased the Lord to visit her with weakness,
which continued and increased on her for about half a year,
she was preserved in great patience, quietness and resignation to the will of God,
often saying, '`It is preparation for my end, and I am well content;
for the Lord has given me many days.
And if this had not come upon me, I could not expect to live long in this world.`'

And although she was one of few words in her health,
yet in her illness she lacked not a word of advice to those that came to visit her,
and it has caused some trouble it was not taken from her mouth as it was spoken.
She was much concerned for her grandchildren, and when any of them came to see her,
she advised them to prize their precious time, saying, '`I was once young as well as you,
or others, and delighted in the pleasures and vanities of this world.
But the Lord in his love and mercy met with me, yes,
he laid the axe to the very root of the tree,
and made me willing to part with all my lovers, my pride and vanities,
and become a fool and a gazing-stock to the world.
But all was as nothing to me in that day,
in comparison to the love and favor of God to my poor soul,
that had long wanted peace with the Lord.
In that day it was my care to accompany myself with
those that I thought walked most circumspectly,
and dwelt nearest the Lord in their spirits; and not to look out at, or take example by,
those that were for most liberty, as too many now do.`'

Then she in much thankfulness, said, '`Oh! it was a good day, a blessed day;
a day never to be forgotten.
My soul has it in grateful remembrance before the Lord;
praised be his holy name for his goodness.`'
And in tears of joy she exhorted all to be faithful unto death,
that they might obtain a crown of life.

Again, upon some coming to visit her, and asking her how she did, she answered,
'`I am going a little before, and you must follow after:
all had need to be faithful to the gift they have received.
I never found that going to meeting barely would do for me.
We must all be faithful according to what we have received,
and there is no more required.`'

Another time, a Friend of London being with her,
she tenderly inquired after the affairs of truth, saying,
'`How do Friends in that great city come up in good order and discipline in the church?
Are they truly concerned to seek out the lost sheep, that they may be brought home again?`'
And when she took her leave of the Friend, she said, '`Farewell,
I shall never see you again in this world;
but hope to have a part in that which is to come.`'

She was preserved in great tenderness and brokenness of spirit all the time of her illness,
and did often say to her friends that came to visit her,
'`I do not weep because I see death approaching; for I cried to the Lord,
that if any thing did lie in my way, he would be pleased to show it me:
but I do not find any thing laid to my charge.`'
Another time, when some friends came to visit her, she,
pouring out tears in a sweet frame of spirit, said,
'`I believe that saying will be fulfilled on me,
that those that sow in tears shall reap in joy.`'

She also often expressed her great thankfulness, that the Lord should be so good to her,
as to open the hearts of many to visit her in her weakness;
and acknowledged the goodness and mercy of the Lord, saying,
'`How wonderfully good is the Lord to me,
a poor creature i What a gentle hand does he lay upon me!
How comfortably have I rested this night!
What a mercy do I receive at the Lord`'s hand, in this my weak condition,
that I can sleep so sweetly!`' And with tears of joy she
gave thanks to God for his great favor and goodness to her,
saying, '`I spend many hours in thinking upon the Lord and his goodness.
I admire how people can lay them down and fall asleep, and not think upon the Lord,
and see or consider how things are with them.`'
Sometimes she would signify her desire to be dissolved and go to the Lord;
but it was in a resigned frame of spirit, saying, '`O Lord,
grant I may patiently wait your appointed time, knowing your time is the best time.`'

She often begged of the Lord, that he would give a double reward to her daughter,
for the love and care extended to her: and her daughter being near her time,
she was in great care for her: and afterward the child being brought to her,
she cheerfully took it in her arms, kissed it, and said, '`I pray God bless it,
and make it a good woman.`'
And afterwards said, '`I must go to my God.`'
She lifted up her eyes, folded her hands, and gave up her soul in sweetness to the Lord,
without either sigh or groan, the 10th of the First month, 1714,
and was buried at Charlewood, in Surry, her corpse being accompanied by many friends,
neighbors, and relations.
Aged seventy-nine years.

[.asterism]
'''
PHEBE DOUGHTY, wife of William Doughty, of Flushing, in New-England,
was daughter to Sarah Taylor.
She was dutiful to her parents, and a great comfort to them,
and from a child was mindful of eternity, meditated on the best things,
had God in her thoughts, and would inquire the meaning of some Scriptures.
She was never given to speak that which was not true.
Many heavenly and weighty prayers she put up to God, who hears the contrite in heart,
and he answered her petitions, to her great comfort;
for she declared the Lord had given her assurance of her salvation,
and death was no terror to her;
and that she had rather die than live longer in this troublesome world;`'though, said she,
'`I have not lacked that which is convenient for me.
I have as clear a husband as a woman need to have, a tender mother, and a sweet child;
yet it is better for me to go and leave you all; this is the best time;
for I am going to meet my Lord Jesus.`'
And she said to her husband, some time before she died, '`My dear, we must part;
it is made known to me: give me up freely.`'
And desired all about her to be faithful to improve their
talents which they had all received from the Lord,
and not put it off to a dying hour; for that is poor work.
Oh! how hard a thing will it be, to die and lack peace with God;
but it is joy and comfort to me to depart this life; for it was said to me,
after my great exercise, Your peace is made;
and I have nothing to charge myself with since.`'

She desired her mother to tell her sister from her,
the Lord had bestowed a great deal on her, and where much is given, much is required;
and advised she might improve her talent, and not put it off till a dying hour,
that is poor work; saying if she could see her poor sister,
she would give her good counsel.

She spoke to others to the same effect, and uttered many weighty expressions in prayer,
which were not noted down.
The day she died, she said to her mother, seeing her weep, '`Mother,
I leave you my little son to take a delight in; take him as your own, I give him to you,
and bring him up in the way of truth; to be sure in the way of truth.`'
She spoke of the goodness of God and his mercies to her,
and declared her full satisfaction of her future well-being, often saying, Sweet Jesus,
'`and declared she was ready.
And after she had been fervent in prayer,
and therein desired the Lord to open the door for her, she said, '`Sweet Jesus,
my trust is in you.`'

A few minutes before she died she kissed her mother, and desired her husband to kiss her,
and bade them take care of the child: '`Now, '`said she,
'`I will go to sleep;`' and so departed the 10th of the First month, 1714,
the fourth day of the week,
and was accompanied by many friends and others to the meeting-house in Flushing,
and after meeting to the burying-ground, near the market-house,
where she was decently interred, the 12th of the First month, 1714.

[.asterism]
'''
TANER COSTARD, son of John and Ruth Costard, late of Amersham, in the county of Bucks,
was of an innocent conduct, dutiful, loving and affectionate to his parents,
religiously inclined from his infancy, and greatly delighted to read the Holy Scriptures,
especially the New Testament.

He lived with his grandfather, and was brought up by him, and in his practice,
being a physician.
Though not in profession with the people called Quakers,
yet this young man came to receive that holy truth professed by them,
and to experience the work of it in his heart;
as may appear by what he wrote in the time of his weakness, not long before his death,
and by what he expressed to his mother near his end.

He likewise spoke several excellent things which were not noted;
for he was indeed much devoted to the service of God in the time of his health,
and very diligent to wait upon the Lord from a child;
and when very young he learned to read in the New Testament,
and often wept when he read of the sufferings of Christ.

A little before he died, his mother going to see him,
when she came and had been by him for some time, she said to him,
'`I am made easy and willing to part with you,
because I have satisfaction it will be well with you.`'
To which he replied, looking on her gravely, and with a pleasing countenance,
I know it will be well; I know it will be well; I know it will be well.`'

And when he departed, it was observed to be in great stillness and sweetness,
and those present felt the life and power of God in a large measure,
to their great comfort at that time, which was as an assurance to them,
that it was well with him, and that the Lord took him to himself.

He died the 23rd of the First month, 1714,
and his corpse was accompanied from the meeting-house in Amersham aforesaid,
by many friends and others who loved and esteemed him,
and interred in Friends`' burying-ground near the said place.
Aged about twenty-two years.

[.asterism]
'''
REBECCA TOOVEY, daughter of Joseph and Rebecca Toovey, of London, aged about nine years,
was a dutiful and pious child,
a great reader and lover of the Holy Scriptures and Friends`' books;
of an innocent and wise behavior and carriage,
and her conduct was pleasing and acceptable.
Though she was but a young plant,
it pleased the Lord to endue her with a large understanding
in things both natural and divine.
She was comely in her person, virtuous in her practices, quick of apprehension,
very just and equal in all she undertook,
and never known to tell a lie or speak an ill word.
She loved to go to meetings, and said it was sweet to her.

Some few weeks before her sickness she had been at a meeting,
wherein she was very diligent and attentive to a Friend,
who earnestly exhorted the children of Friends to
make choice of the blessed truth for their portion,
while they were in the enjoyment of their health,
that they might be prepared for a dying hour.
Whereupon this child was much reached and melted into tears,
and after meeting she got apart to read, which was her usual practice.

After she was taken ill, she was in great pain;
but her heart was filled with the incomes of the Lord`'s love and mercy,
which caused her to utter many sweet and heavenly expressions.

She bore her great pain with much patience,
and was observed to be fervent in supplication to the Lord, in a tender, humble,
and submissive manner.
When her pain was sharp, she often cried out, '`Sweet Jesus, give me ease.
Sweet Jesus, look down with an eye of pity upon your poor, poor servant.`'

Another time, being in great pain, she said,

Sweet Jesus, give me ease;

For mercy I do crave:

And if you will but give me ease,

Then mercy I shall have.`'

With many other pathetical expressions not noted,
which she uttered in deep supplication and humiliation; and then she said, '`O Lord,
you desire not the death of a sinner; but rather that he would repent, return,
and live;`' adding, '`I know it to be so.`'

Another time she said, '`Lord, if you please you can give me ease.`'
And again, '`Lord, you will help them that love and fear you.
O Lord, remember your poor servant, and give me a little ease.`'
And seeing the maid cry, she asked her what she cried for; the maid said,
'`To see you so full of pain.`'
To which the child replied, '`Do not cry; I shall be well in a while.`'

Perceiving her school-mistress, R. Trafford, to be troubled for her, she said,
'`Dear mistress, do not be troubled; there is a rest prepared for the righteous.
There is no ease here, but there is ease in heaven.`'
She also said, '`It is a sad thing to speak bad words, and to tell lies,
which I never did.`'

Near her end, she said to her maid, '`I wish you well, and I shall be well.`'
Then naming her relations and particular acquaintance, she bade them farewell,
and departed this life in a sweet frame of spirit, at Croydon, in Surry,
on the 8th of the Fourth month, 1714, and was brought to London,
and buried in Friends`' burying-ground, in Bunhill-Fields.

[.asterism]
'''
JOSEPH GROVE, of Botherhithe parish, in Surry, merchant, was the son of John Grove,
of Mary Magdalen`'s parish, mariner and master of a ship,
and for many years in the Barbados trade;
and this Joseph Grove resided in the island of Barbados for many years, where,
as well as since his return to his native country,
he was of a sober conduct and good reputation,
and a lover of truth and the friends of it, who kept their places therein.

In the latter part of his time, he was often indisposed in body,
and much afflicted with pains, notwithstanding which,
he was not unmindful of making his peace with the Lord;
for a little before his departure, he said, '`I hope I have fought a good fight,
and am waiting for the crown, which I doubt not at all but is laid up in heaven for me.
Oh! how I long to be dissolved: to live indeed is Christ, but to die is gain.`'
Then speaking to his wife, said, '`My dear love, weep not for me;
for I seek death with more pleasure than all the riches the Indies can afford.
You have been my love, but I have another lover, Christ Jesus our Lord; to him I go,
and to him I recommend you and my dear children: he will be a husband, a friend,
a counsellor and helper, yes, all in all, if you will cleave unto him.
Seek, and you shall find; knock, and he will open the treasures of divine wisdom to you,
and by his mighty power you will be preserved out
of all such things that would spot and defile.`'

Great was his concern for his children, insomuch that he would often say,
'`Oh! that they may choose the fear of the Lord.
I desire that for them more than all things here below;
that is the best riches and the greatest honor.`'
And as his love was great to his wife and children, yet it was not bounded there;
but said, What strong love have I in my heart for the servants of the Lord,
and although I cannot be present with them at meetings,
I often meet with the Lord in my solitary chamber; forever blessed be his holy name.
Oh! that they may love him, and then they must and will love one another.`'
And frequently spoke to this effect.

He departed this life the 9th of the Eighth month, 1714,
in the sixty-second year of his age,
and his corpse being attended by many friends and others,
was decently buried in Friends`' burying-ground, near Barnaby-street, Southwark.

[.asterism]
'''
ESTHER CHAMPION, wife of Richard Champion, of Bristol, daughter of Joseph Palmer,
of Flushing, Long Island, in America,
was religiously inclined from her young and tender years,
for the Lord inclined her heart to seek after him, and was pleased to be found by her.
The Lord gave her a large measure of his Holy Spirit, and caused her,
as she grew in years, to increase more and more in his eternal truth,
and fitted and prepared her for his work and service whereunto he called her.
And after some time he sent her to visit his people and churches,
and to preach the gospel of peace and salvation by Christ,
and declared his coming by his divine light and spirit in the hearts of all men,
inwardly to teach them, and labored to gather them to him,
in order to their coming to know salvation by him.
In this work she labored in many parts of America, namely, Rhode Island, Long Island,
New England, the Jerseys, East and West, Pennsylvania, Maryland, Virginia, Carolina, etc.
She had meetings in several places among many people, where there had been none before,
and the Lord was pleased to bless her labor,
so that many were gathered to the knowledge of his truth,
and therein to worship him in the spirit of his Son, our blessed Savior,
the Lord Jesus Christ.

After she had travelled many thousand miles in the Lord`'s service,
in the work of the ministry of the gospel in those American parts,
she found for some years a concern,
which so continued upon her that she could not with satisfaction omit it,
which was to visit some parts of Great Britain,
but more particularly the inhabitants of London,
at which place she arrived the 20th of the Eighth month, 1710,
and had good service there, which many that were witnesses and sharers can testify.

She was a woman of a solid yet cheerful spirit,
much abounding in love and true zeal for the Lord and his truth;
and would express her great grief when there was
any disorder or lack of true love in any church,
meeting, or family where she travelled, which was in many parts of this nation.

The 23rd of the Eighth month, 1714, in the morning,
she complained of sharp pains in her breast and back,
which continued most part of three days, and then the small-pox appeared,
which distemper has proved mortal to many of those parts where she was born.

She retained a sound understanding,
and oftentimes spoke of the goodness of God to her soul,
and by the aboundings of his love her heart was filled, and her cup made to overflow,
to the comfort of those who were present.

She was freely resigned to the will of God, either to die or live,
though she had inexpressible love to her husband and children, and desired, if she lived,
to be farther serviceable to the church of Christ, yet said, The Lord`'s will,
and not mine, be done.`'

She often desired those who were present to love, seek,
and serve the eternal God with all their hearts.
And, speaking to Dr. Logan, said,
'`Many good and precious opportunities you have in your way of practice,
if rightly applied, in seeing the advantage,
inexpressible joy and comfort the Lord is pleased oftentimes, on a dying bed,
to give and afford those who live in his fear; and on the contrary, the cries,
bemoanings, and bitter bewailings of others,
who have not improved and spent their time well in this world.`'
All which she desired him to improve; and further added,
'`It is not a profession of religion only that will render men acceptable to God;
but serving him in and by the assistance of Jesus, the Son of God,
the only Intercessor for man`'s salvation.`'

She was then reminded of her great weakness of body, to which she replied,
'`The Spirit of Christ in me, raises my spirit and strength to speak of his goodness,
and praise his great and good name;`' and added, '`All that man can do is but his duty:
therefore the Lord, through his Son, our Savior, the immaculate Lamb,
ought to have the honor.`'
She desired the Lord would be a Shepherd to his people,
as he had been and still was to her soul, who had given her to enjoy sweet pastures,
and made her heart exceedingly to overflow;
and that his staff and rod had been and still were her inexpressible comfort.

And as she frequently, in a sweet and heavenly frame, supplicated the Lord,
so she did then, praising his eternal name for his goodness to her soul,
and that she knew her Redeemer to live, and to be with her, saying,
'`It is an easy thing to talk of death;
but it is an inexpressible comfort to be prepared for a dying hour, and to meet death,
when it appears, cheerfully; as I now do, by the help of the same Jesus, my Savior,
who suffered without the gates of Jerusalem.`'
Then she prayed very fervently for the return and repentance
of those that run into a loose and libertine spirit;
and that the glory of God might appear in a particular
manner to the inhabitants of this great city;
and that God`'s church might be preserved in perfect peace, as a light to the beholders.
She also prayed very earnestly for the young generation,
that the Lord would incline their hearts in their visitation, in the days of their youth,
to seek and serve him, before it was too late,
as he had done to her soul in her early days; for which, said she,
I have cause forever to admire his inexpressible love.

She bore the extremity of her distemper with more
cheerfulness and discretion than was common,
with a continual resignation to the will of God.

A few hours before her departure, she said her time in this world was nearly spent,
and cheerfully desired her husband to resign her up into the bosom of her blessed Savior;
and requested her husband to live in God`'s fear, and serve him faithfully all his days.
She signified her satisfaction in their coming together in marriage,
and declared that the same power which engaged and united their spirits,
now called her home to God.

Then she spent some time in holy supplication to God, although she was very weak in body,
yet fervent in spirit, and she earnestly besought her heavenly Father,
that the brightness of his day might appear abundantly
in his people and churches all the world over.
Then embracing her husband, took her farewell in the Lord Jesus Christ.

Then she sent for her husband`'s two children,
(whom he had by a former wife,) whom she affectionately loved and treated as tenderly,
while she lived with them, as if they were her own,
embraced them in her arms and took her leave, advising and desiring them,
being of years of understanding, to seek, serve,
and love the eternal God in the days of their youth.
She declared to them the advantage they would receive thereby,
and recommended them into the hands of God,
desiring he would preserve them out of the evil of the world, while they were therein;
and fervently prayed that they might be the Lord`'s servants all their days;
and desired them to be dutiful to their father, observe his advice,
and love their little brother and sister.
Her two children being young, she took them in her arms and affectionately embraced them,
and desired the Lord would take them, with the two elder, to himself,
when their time here shall come to an end.

Then she sent for some of her servants, to whom she gave good counsel and advice,
recommending and exhorting them to love, serve,
and fear the great and good God in the days of their youth, and while they had strength,
signifying the advantage they would receive thereby.
She also gave them in charge to take care and discharge
their trust to her children while they were with them;
and those of her servants that were not present,
she desired might be acquainted with her advice to them.

She also signified her heart was filled with the love of God,
in which she again desired the prosperity of his church and people.

Her speech beginning to fail, she said,
I desire my dear love in the Lord Jesus Christ may be remembered
to all my relations and friends that ask after me,
even in the same love (said she) that now makes my heart to overflow:
'`and then declared her satisfaction of going to her eternal rest,
and again embracing her husband in her arms, and in the bowels of her Father`'s love,
sweetly took leave and bid him finally farewell, and soon departed this life,
as quietly as one that sleeps with much sweetness, in Bristol,
the 3rd of the Ninth month, 1714, after eleven days`' sickness,
and was interred in Friends`' burial-ground of that city.
Her love and labor in that city, in the work of the word of life,
had been large for her time, and in the parts aforesaid; in which she was blessed of God,
and made successful to the good and comfort of many.

She was a virtuous woman, of a sound judgment, and very quick understanding,
abounding in true love and zeal for the Lord and his truth; solid and grave,
yet of a cheerful disposition, greatly desiring the good of all people,
and that they might come to the knowledge of the truth, live therein,
and enjoy peace and acceptance with the Lord.

She was a faithful minister of the gospel of peace, a good, virtuous,
and affectionate wife, a tender mother, a loving mistress, a true Friend,
and of an exemplary conduct in holiness and true piety.
