== Chapter 4

[.chapter-synopsis]
* Daniel Taylor
* John Thompson
* Samuel Waldenfield
* Joseph Welsh
* Susannah Saunders
* Thomas Williamson
* John Close
* William Greenup
* Richard Ransome

DANIEL TAYLOR, of Bridport, shopkeeper,
was convinced of the holy truth in his young days,
about the nineteenth or twentieth year of his age, and received it in the love thereof.
Through its work and power in him, he became a very solid, grave, religious man,
greatly serviceable in the church of Christ and exemplary in his life and conduct,
adorning the doctrine of God our Savior, by walking as became his holy profession,
of which Jesus Christ is the apostle and high priest,
until the Lord who he loved was pleased to take him to himself.

In the time of persecution he was a cheerful sufferer for the testimony of truth,
both by imprisonment and spoil of goods, which he took joyfully,
whereby he became a strength to his brethren, who were fellow sufferers with him:
for he could pray for his enemies, and had love to all mankind,
and desired their salvation, knowing it was the will of God.

And God blessed him with outward substance, with which he honored the Lord,
and liberally, with cheerfulness, gave great part thereof to charitable uses,
as by his several gifts and legacies appear.
He was a great friend to the poor of all sorts, and had a tender regard to them,
among whom he will be greatly missed, as well as in the church.

His sickness was but short: he kept his bed but a few days before his departure.
In which time he was sweet in his spirit, and had near access to the Lord,
and in much humility said, '`O you great Jehovah, in whom is everlasting strength,
my soul praises you, and all that is within me blesses your holy name.`'
Again, with more not noted down, he said '`my soul praises you,
and my spirit magnifies your holy name: '` He added, '`My love, in the Lord Jesus Christ,
is to all friends; I am in love and amity with them.`'
Being apprehensive his departure drew near,
he took his solemn leave and farewell of both his
relations and friends who came to see him,
praying for them, and gave wholesome counsel and advice to several;
particularly the young generation related to him,
and likely to survive him in this world.

And being content in the will of God, which he prayed for, and was answered in,
he died the 7th of the Ninth month, 1714, in the seventy-third year of his age,
and was honorably buried the 12th of the same, in Friends`' burying ground at Bridport,
his corpse being accompanied to the grave by many of his friends and neighbors,
and testimony given to truth, both at the meeting and grave, on that solemn occasion.

[.asterism]
'''

JOHN THOMPSON, late of Crook, in the county of Westmoreland,
was very early convinced of the blessed truth, in the year 1652,
by that eminent minister of the gospel, George Fox, at his first going into those parts.

The said John Thompson had been seeking the way of the Lord for several years,
and when his understanding came to be opened by the light of Christ,
to which he was turned, he was convinced of the truth and way of the Lord,
and his soul greatly rejoiced that the day was broken forth,
which let him see the dry and empty forms, and lifeless religion he had been in.
And although he had been strict in profession, he then saw by the light of Christ,
there was abundance of things which were not agreeable to the mind of the Lord;
and the righteous judgments of God he found to work in him,
in order to redeem him out of those things.
Notwithstanding he saw the way was strait, and the sufferings many,
which he was likely to meet with, yet through the work of the power of God,
he was made willing to bear and go through all, even cruel mocking, buffetings,
revilings, imprisonment, and spoiling of goods, and rejoiced that the Lord,
made him willing to suffer for his name`'s sake.

He was zealous for the truth against that libertine spirit,
which opposed the discipline and good order of the gospel,
standing as a watchman upon Zion`'s walls,
having a clear discerning of many things that might creep in to eclipse her glory,
under whatsoever pretense they might appear.
And as the light made them manifest,
it placed judgment in the wisdom of truth upon the transgressor.

After some time the Lord was pleased to open his
mouth by way of testimony for his blessed truth,
in which he faithfully labored; and though he never travelled much abroad,
yet his ministry was reaching and refreshing to those who heard,
and edifying to the churches where his lot was cast.

He was very tender towards that which was good, in the least appearance of it;
but very sharp against that which was evil,
especially against those who professed the truth,
and were not faithful in that testimony truth had called them to bear,
but gave way to a libertine spirit, and were not willing to bear the cross.
His spirit was often grieved with such, and he was made sharply to reprove them,
being much concerned for their good, and also for the honor of truth;
often saying that those who professed the truth and walked contrary to it,
were the greatest enemies truth had, being a stumbling block in the way of others.

He suffered long imprisonment upon the account of his testimony
against that anti-christian yoke of tithes,
and also great spoiling of goods by fines imposed on him for his testimony to the truth;
all which he bore patiently, and underwent with abundance of pleasure,
having a regard to the recompense of reward which would follow.

He stood valiantly through all those days of tribulations and sufferings,
after which he lived to a good old age.
He was visited with sickness the 11th of the Third month, 1715,
and though his pains were great, yet he bore them patiently,
often saying that in a little time all would be well.
One asked him how he was; he replied, many being present,
'`I am very weak of body and full of pain, and it seems to me,
as if my stay here must not be long: but I have had a long time here,
and the Lord has been very kind to me beyond what I have desired or deserved;
but all is well.
The Lord`'s power is over all, and there is no guilt, no condemnation,
nor bar between the Lord and my soul`'s peace; but the pure holy Seed reigns over all,
and I feel life spring up into dominion, and my heart is comforted among you,
my dear friends.`'
Then he continued quiet, enjoying peace with the Lord.

Thus he sweetly finished his course the 26th of the third month, 1715,
at the house of James Wilson, and was buried in a decent manner the 29th of the same,
in Friends`' burying-ground at Kendal; and though his earthly house be dissolved,
yet we are satisfied he has a house with God, eternal in the heavens.
Aged eighty-seven years.

[.asterism]
'''

SAMUEL WALDENFIELD, late of Bush-hill, in the county of Middlesex,
died the 7th of the Eighth month, 1710, at his own house.

He was born about the year 1652, at Edmondsbury, in Suffolk, and after lived at Sudbury,
in the said county.
He was religiously inclined in his youth, and sometimes a hearer of the Independents.

About the year 1670, or `'71, he was, by the word of life,
convinced of the blessed truth by that eminent minister
of the gospel of our Lord Jesus Christ,
Giles Barnardiston, and received it in the love thereof,
and came to be obedient thereunto, and to know the work of it upon his heart,
and by keeping to the teachings of the grace of God,
came to live a sober and a godly life, and was very zealous for the Lord,
and his holy name and truth.

It pleased the Lord, about the year 1672, to bestow upon him a gift of the ministry,
and the Lord called and sent him forth to proclaim the acceptable year of the Lord.
He published the glad tidings of peace, and proclaimed liberty to the captives,
by Christ, and for Zion`'s sake he could not hold his peace,
for Jerusalem`'s sake he could not rest,
being greatly desirous that all might come to Christ the light,
and that the abundance of the sea might be converted,
and the forces of the Gentiles might come unto him.
In the Lord`'s work he freely spent, and was spent,
in true love and zeal for the Lord`'s name and truth, and the good of souls,
traveling in England, Scotland, Ireland, Holland, and Germany,
and by his powerful preaching of the word of life, and the Lord`'s blessing on his labors,
many were convinced of the holy truth, and turned from darkness to light,
and from the power of Satan to God, and.were as the seals of his ministry.

He was loving and tender to those that truly loved and served the Lord, especially such,
whether male or female, whom the Lord called into his work and service,
to speak a word in season to Zion`'s travelers, and to comfort those that mourned.

In the year 1684 he married and settled in London,
and continued faithful and diligent in the work he was called to,
and suffered for his testimony by imprisonment, etc.
But when at liberty he was frequent in travels as before said,
and visited the churches of Christ in most of the counties of this nation,
and much in the east parts thereof.
His labors of love and service were well received abroad and at home, and by his grave,
solid, and exemplary conduct, he adorned the doctrine of God our Savior,
and walked as became a minister of the gospel, and that holy profession he made,
of which the Lord Jesus Christ is the high priest and apostle.

He was humble and merciful, very considerate of the poor, ready to every good work,
and to communicate he did not forget.
He was, in the Church of Christ, an elder worthy of double honor.

About the year 1706 he left the city and dwelt at Bushhill,
being often not well in health; but when he was, and not engaged in travels,
or other services on truth`'s account, for the ease of Friends,
he constantly attended the meetings about where he lived, and his testimony was clear,
living, and effectual, and reached the witness of God, both in Friends and others.

He also was very tender to the newly convinced,
and administered suitable advice to their several states, as a nursing father,
and encouraged all under a right sense.
He had a more than ordinary concern in testimony,
to press and exhort to such a good life and conduct, as becomes our Christian profession,
often signifying that coming to meetings, or pretense to religion,
and professing Christianity, was of little value,
without the life and conduct were agreeable.

He often expressed himself to this effect, that the pride, liberty,
and ill conduct of too many under the profession of truth and the Christian religion,
were a great grief and exercise to him,
and the sins and miscarriages of such administered to him much sorrow and affliction.
He was under great exercise of spirit for the prosperity of truth,
and that the testimony thereof, in all the branches of it, might be duly kept up;
and that all looseness, pride and haughtiness,
and that libertine spirit that would lay waste the heritage of God,
might be discouraged and suppressed;
and that none might take upon them to be rulers in the church but men of truth,
men fearing God, and hating covetousness.

This concern grew upon him for several years to the end of his days.
So that he zealously exhorted as aforesaid to a holy and righteous life,
and all to be just and true in all their concerns among men:
in which he was exemplary in his practice, being a man truly religious,
and of an innocent and virtuous life, full of love, good nature, and good works,
punctual to his word, just in his dealings, a fair trader,
choosing rather to suffer injury than do any wrong.

He was a bright ornament to our holy religion in his conduct,
and thereby great reputation was gained to truth and Friends, among both rich and poor,
with whom he was concerned.
The poor loved him, to whom he was courteous and charitable;
and the rich esteemed him greatly for his prudent and innocent behavior;
so that his company was acceptable and much desired by them.
Many who had entertained a mean opinion of Friends as a people,
since their acquaintance and conversation with him, have other sentiments of them:
and as he was beloved in his life, so his death was generally lamented.

He has left so good a name and savor behind him,
that his memory will not be easily worn out, either among his friends or others.

He was ill about two months before his decease; and, although he was often in great pain,
he bore it with wonderful patience, and was frequently very cheerful,
though his end drew near.
The sting of death being taken away, death was not terrible to him;
often signifying all was well with him, and in much tenderness said,
'`I have done the work of my day.
I have peace of conscience.
I have wronged no man.
I have received a great deal of wrong and injury, but I forgive them all,
and I desire the Lord may forgive them also.
I die in charity with all the world.`'

Another time he said, '`What a brave thing it is for Friends to dwell in unity.
Here we can sit together as the children of God, the church of the first-born,
whose names are written in heaven.
Truth is what will endure forever, and be comfortable to the children of men,
and the Lord will exalt it, and make Zion a quiet habitation,
and Jerusalem the praise of many generations.
He will exalt his truth and name in the earth,
and will bring down that which would oppose his work,
and will purge them out of the church who are exalted, and setting up self,
and ruling in their own will and spirit.
The Lord will do it all away.
I have endeavored to live inoffensively towards God and man.
And now I have no occasion to repent that I have endeavored to live well;
and as I have nothing to boast of, I have no occasion to complain; all is well.`'

Many more sweet expressions, in a tender, heavenly frame of spirit, very affecting,
he uttered to those about him in the time of his sickness, that were not noted.

He continued in a sweet, composed frame of spirit and resignation of mind to the last,
and departed in great peace the 7th of the Eighth month, 1715;
and no doubt is in eternal rest,
receiving the reward of his many faithful labors and services for the truth,
for the promotion of which, as by the account he kept, his travels to the year 1700,
were nearly forty thousand miles; besides his travels from the year 1700 to 1715,
in which he died, were also very considerable.

His body was brought to London;
and being greatly beloved by people of several professions,
his corpse was attended by a great company from Devonshire-house meeting-place,
to the burying-ground belonging to his friends in Bunhill-Fields,
and there he was honorably interred.

[.asterism]
'''

JOSEPH WELSH, of Chesham, in the county of Bucks, was born at Aylesbury,
in the said county, in the year 1651, and was convinced of the truth in 1674.
It pleased the Lord to call him forth in a public testimony about 1676,
and he became a faithful laborer, and serviceable in the work of the Lord in Chesham,
and other adjacent meetings,
though for some years past he was disabled by infirmities of body.

He was a diligent frequenter of meetings on other days as well as the First-day.
He was also a promoter of good order in the church, and so continued to his end.
His testimony was attended with life and power,
to the comfort and satisfaction of the hearers.

A few hours before his death, he declared the Lord has a great work to do in the earth,
and that it would go well with the faithful,
whom the Lord would hide in the hollow of his hand.

This honest man was a loving husband, a tender father to his children,
and a lively minister.
He departed this life the 11th of the Eighth month, 1715,
and was buried in Friends`' burying-ground at Chesham, the 16th of the same;
being accompanied by many Friends, and others.
Aged about sixty-three, and a minister about thirty-nine years.

[.asterism]
'''

SUSANNAH SAUNDERS, late wife of Edward Saunders, of Clifton, in Bedfordshire,
was one whom the Lord called and sent to labor in the ministry of the word of life,
by which she was fitted and qualified to labor in true love for the good of souls,
and left her husband and tender children to preach the gospel freely,
and to visit the churches of Christ in several parts of England, Wales, and Ireland.
And her visits were serviceable and acceptable,
and her conduct was as became the profession she made.

She landed in Ireland with her companion, Benjamina Padley,
on the 10th of the Fifth month, 1715, and travelled in many parts of that nation,
visiting most of Friends`' meetings there.
On the 31st of the Seventh month, 1715, they came to Lurgan,
and having been at some meetings in that town,
on the 8th of the Eighth month went to Raffer Island,
and the next day were at a marriage at the house of Jacob Wilson,
where the said Susannah Saunders went with some difficulty, being ill;
but the Lord was pleased to enable her to bear testimony for him.
She afterwards was at a meeting ten miles further;
and the Lord was with her and strengthened her;
but when the meeting was over she was very ill, and finding herself much out of order,
her companion desiring her to go back,
she consented yet went to meetings as long as she was able.

On the 26th she was at a meeting,
where she was engaged in testimony to the great satisfaction of Friends;
for the Lord gave her suitable ability to do what he required of her,
which she did perform to the honor of his name.
But after this she weakened much, and her bodily affliction was great,
which she bore with much patience and resignation to the will of God,
and often declared she thought she should not return home; yet said,
'`I am easy and resigned,
and have endeavored to discharge my duty according to my small measure,
and have been freely given up to spend and be spent for the gospel`'s sake,
and the Lord has been good to me.
I pity my dear husband,
and often think on him but hope he will be enabled to bear his exercise.
My poor little babes will miss their mother; but I commit them to him that gave them me,
who I believe will take care of them.
The Lord took care of me when I was tender in age,
and he has been good to me from my childhood.`'
She advised her companion to faithfulness and watchfulness,
and reminded her of the goodness of God which she had been a partaker of;
and was fervent to the Lord for her preservation;
and that she might give her up freely to the Lord`'s disposing hand;
and that he might endue her with patience to bear her exercise;
and in a very tender and sensible manner expressed herself, saying,
I have a secret hope it will be well with me.`'
Then said again, '`Freely I resign myself into the hand of God:`'
and she returned thanks unto him for her preservation.

Another time, several friends being present, she said,
'`There is great satisfaction in an easy mind.
I have great peace in that I have been faithful.
I have not spared this piece of clay;
but while I had strength I have been willing to answer what I was called to:
and now it seems as if my time was nigh at an end.`'

At another time she said to her companion, '`The Lord has been good to you; be faithful,
for it is good to have an easy mind.`'
One night she seemed as if she was nigh to depart this life;
her companion being in sorrow, she took her by the hand, and said, '`Dear child,
give me up freely, and have your eye to the Lord, and he will be with you,
and give you strength.
He has been with me,
and I can say it is a good thing to have a clear mind at such a time as this.`'

Again, '`How vain are men to be so taken up with the concerns of this life,
and seeking to get riches in this world.
What is this world worth?
It is not worthy to be compared with the joys of heaven;
they that are faithful to the Lord will have their reward.
I am now glad that I served the Lord, for I feel the peace and satisfaction of it,
and find nothing, but all is well: I cannot say when I shall go,
but it seems as if it might not be long; however, that is in the hand of the Lord,
and I am resigned whether in life or death.`'
Much more she said to them that were about her, exhorting them to fear the Lord,
and to seek a portion in the truth, which, she said, would be more to them,
when they were about to leave this world, than any other enjoyment.

Another time she said, '`The man is blessed whose God is the Lord.`'
Again, '`It is a good thing to have the mind truly stayed upon God,
they shall be kept in perfect peace: a great mercy! a mighty privilege!`'

Another time, being very ill, and to appearance nigh unto death,
her companion being sorrowful and loth to part with her,
Susannah took her by the hand and kissed her, saying, '`Dear child, why will you hold me?
let me go, and do not be sorrowful, but keep to the Lord and he will preserve you.
Farewell.
Be good and do well, and the Lord will bring you through all.
You have yet some light afflictions to pass through; but be not discouraged;
nor look at what may seem mountainous, but be watchful and look to the Lord,
and that hand that has hitherto helped you, will help you.`'

She said to friends, '`Dear friends, love truth, it is excellent, it is above rubies.
Oh! it is precious, it is above all things, it makes a deathbed easy.
I am glad my lot is cast in this place, with a couple of young plants that love truth;
keep to it, and it will make you noble.
Dear landlady, farewell; the blessings of the everlasting hills be upon your heads;
the Lord bless you and make you serviceable in his church.`'
Then speaking of her illness, said, '`All that I crave now is patience,
that I may hold out to the end, that I may not dishonor the Lord:
the honor of his name has been as dear to me as my life.`'

A few days before she died, several friends came to see her,
and after some time her mouth was opened among them in
a sweet exhortation to love truth and keep to it,
and to be watchful and to keep to the Lord,
and not let their minds be too much after the world:
and testifying of the goodness of the Lord, she committed them, with her own soul,
to his protection, giving honor to his name.
That night she was very ill, and said, '`It is hard work to leave this world;
one had not need have anything else to do, '`or to that purpose.

Next day, being First-day, she was very much weakened,
and some friends coming in that evening to see her, she said,
'`I am glad to see so many of you, I did not expect to be here so long.
I am long a dying, it is hard work to die.`'
Then friends sitting in silence a while, she exhorted them to faithfulness and diligence,
and to love truth, and to seek the honor of God, adding,
'`Oh! that the youth of our age would love truth, and seek the Lord,
and serve him in their youthful time: they will have the benefit of it.
It would be more to them than all the world.
But many of them are careless, and contenting themselves with a profession,
and that will do nothing for them.
My soul has often mourned for the youth of our time,
and I have been under great travail of soul, that they might come to fear the Lord;
but there are many of them that grieve the Lord,
and are following the pleasures of this world.
Friends, love truth, and it will make you noble.
Oh! that the elders would love truth: there are elders that love the Lord,
and they are a comfort and a strength to the youth that fear God, and to one another;
they are as joints and bands that cannot easily be broken, my soul loves them.
Seeing it was the will of the Lord to visit me with weakness,
so that I am not likely ever to see my habitation again,
I am thankful my lot was cast in this place.
Dear friends, keep near truth, and it will keep you in a trying time;
for there is a trying time approaching, in which there will be great desolation.`'
With much more to the same purpose.

She often spoke of the goodness of God to her from her very childhood,
and enumerated his favors, and acknowledging his care,
said he had been a tender Father to her, and she believed he would be so to hers.
Her affliction being very great, she besought the Lord, in a humble frame,
that he would be pleased either to relieve her or release her,
or to give her patience that she might not murmur.
Then looking on them about her, said,
'`It is hard work to go out of this troublesome world.`'

About four days before she died she wrote to her husband,
wherein she signified that she weakened daily,
and that the Lord by his divine hand had wrought a willingness
in her to spend and be spent for his name`'s sake,
and that she felt sweet comfort, '`quietness and content, which,`' said she,
'`out-balances all things else.
My dear, I fervently desire the Lord may be with you, and bring you to a resignation.
Stand faithful in every branch of your testimony for the blessed truth;
you will have the comfort of it.
Dear heart, if I should never see your face more,
I desire you to take care of our tender babes, and bring them up, as much as in you lies,
in the fear of the Lord.
I have been deeply bowed on their accounts, am fully satisfied, if they live,
the Lord will visit them in their tender years,
and it seems to me as if my dear Susannah may tread in many respects,
in her mother`'s steps.
The Lord preserve her, and bring her to choose him for her portion; then it will be well,
and she may be serviceable when my head is laid in the silent grave.
My dear little boy, if he grows up, it will be hard for him to submit to the yoke,
yet I secretly hope he will in time be made to bow,
which is some satisfaction to my mind.
I must commit them to the tender care and protection
of Him who gave me them;`' with more not abstracted,
which she concludes in entire love, his affectionate wife, etc.

The day she departed, sitting in a chair, the pangs of death being upon her,
she desired to lie down, which she did, and waited for her change; and R. H. being there,
was concerned in supplication for her.
When he had done, she said, '`There is a divine hand has laid some hold at this time,`'
and so went on sweetly, declaring of the goodness of God,
and desiring her friends might be faithful,
warning them of the judgments of God that were near to be poured forth upon the nations,
and exhorted them to flee to the Lord,
who would be their defense and strong tower in the time of distress.
And having spoken much of the wrath of God that was ready to break forth,
exhorted Friends to abide upon the rock.

Then she broke forth in a sweet manner, setting forth the glory of the kingdom of Christ,
that the Lord, after he had punished the nations, would exalt the kingdom of his Son,
and set him upon his holy hill of Zion, and all nations should flow unto him,
and he should exalt the scepter of his righteousness above all scepters,
and his kingdom above all kingdoms.
Then blessing God for his preservation and mercy towards her,
and for the assurance given her that it would be well with her, she said,
'`I have not sought a name or fame among men;
but have discharged myself faithfully in the sight of God.
I have not desired to appear in show what I was not;
but to be in substance more than I appeared to men.
And it was neither for honor nor esteem that I left my dear husband and tender babes;
but that I might answer the will of God,
and in a concern for the promotion of truth and the honor of God.`'
She desired the Lord would bless his people in that nation,
and particularly that meeting and family where she then was,
and reward friends for their love and care towards her.

She continued her exhortation to them to be faithful;
again declared of the goodness and mercy of God; and so lay in a sweet frame of spirit,
giving glory to God and magnifying his power, until her strength and speech failed.
Then, lying still, she looked on those there with a pleasant countenance,
as one who had a sight of the joys she was entering into;
and about the 7th hour in the evening, departed this life, the 9th of the Ninth month,
1715, and was buried the 12th of the same, in Friends`' burying-ground in Lurgan,
her corpse being accompanied by a large number of Friends and others;
and there was a good meeting, in which the glory of truth was eminently manifested,
to the tendering of many hearts, which was as a seal upon the spirits of friends,
that it was well with her.
Aged about thirty-eight, and a minister eighteen years.

[.asterism]
'''

THOMAS WILLIAMSON, late of Bannerig, in Applethwait, in the parish of Windmoor,
and county of Westmoreland, was born at Common, in the said parish,
about the latter end of the Fourth month, 1633, of honest parents and of good report,
and educated according to the manner of the Church of England.

He was naturally of a cheerful and free disposition,
inclining in his youth to the vanities and pastimes,
in which too many spend their precious time,
though at that time he was very circumspect in observing
those outward performances he esteemed religious duties.
But in the year 1670 it pleased the Lord to visit him with some affliction of body,
and to open his understanding to see the emptiness of all his former formal profession,
and the vanities of his past life; and sorrow and distress took hold upon him for it,
and cries and breathings were raised in him to the Lord, that he would show him his way,
and he would walk in it.
It pleased the Lord to answer his desire, and to convince him of the blessed truth,
which he received with joy and gladness,
before he had been at any meeting of the people called Quakers;
and he gave up thereto according to his understanding.

About the latter end of the year 1673,
his mouth was opened in a public testimony to declare the goodness of the Lord to him,
'`and to encourage all to faithfulness, in which he was a good example,
and a considerable sufferer for his testimony,
both by imprisonment and spoiling of goods.

In the year 1678, he was imprisoned three months for preaching truth in a steeple-house,
and most of his goods were taken from him by some justices, on the Conventicle Act.
He was not only fined for himself;
but ten pounds laid on him for being present at a meeting held at Bownass,
the 15th of the Seventh month, 1678.

His testimony he delivered in much plainness and simplicity.
He was tender to the good in all, though sharp in rebuking that which was evil.
He was a man who feared God, sincerely loved truth, and hated hypocrisy and deceit;
sound in judgment, of a good conduct; just and honest towards all men;
bold and valiant for truth upon earth; undaunted in suffering,
rejoicing that the Lord had counted him worthy to suffer for his name`'s sake.
He was zealous in his testimony against the payment of tithes,
and those called church rates, for which he was a constant sufferer;
and an encourager of others also to faithfulness therein;
diligent in reading the Holy Scriptures, and in attending of meetings,
as well those for good order in the church, as those for the worship of God,
until by age and infirmity of body he was deprived of that privilege.
He often said, '`The worship of God, and the good of the church,
ought to be preferred before our business.`'

He truly confided in the Lord, and gave this testimony on his dying-bed,
that God had dealt bountifully with his soul, and had given him all he had need of,
and that he had peace with the Lord, and his soul was returning into rest;
with more words not noted.

He died the 22nd of the Tenth month, 1715, and was buried at Kendal,
the 25th of the same, aged about eighty-two, and a minister about forty years.

[.asterism]
'''

JOHN CLOSE was convinced of the blessed truth about the year 1705,
and was very diligent in frequenting meetings,
though it was through much difficulty at times,
by reason of his father`'s unwillingness and aversion thereto.
Nevertheless, having a due regard to truth, he was preserved so blameless in conduct,
that he not only gained upon his father to leave him to his liberty,
but was likewise instrumental towards convincing his brother and two sisters.

After some time he received a gift of the ministry of our Lord Jesus Christ,
in which he labored faithfully and fervently, being sound in doctrine.

He travelled much in truth`'s service,
visiting the southern parts of England several times, as well as counties nearer home,
and in Scotland, Holland, and Wales,
being zealously concerned for the prosperity of truth and the promotion thereof.
He was an encourager of the good in all,
and careful to suppress every appearance of evil;
very diligent in visiting the afflicted.
His care over the church was great, his advice seasonable, his judgment sound;
he was chiefly concerned for the honor of truth,
and that Friends therein might live in unity, and be at peace one with another.

In the beginning of the Eleventh month, 1715,
having drawings upon his spirit to visit Friends in Cumberland,
he went with the unity of the brethren, and visited several meetings in that county.
On the 15th of the same he was at Wigton, where he began to be ill.
The next day he travelled to Holme meeting, where, notwithstanding his illness,
he bore a faithful testimony, to the great satisfaction of Friends.

That evening he came to a meeting at Allonby; but his sickness increasing,
he sat but a little time in the meeting,
and signified in a few words he felt the goodness of the Lord upon his spirit,
and his gladness thereof;
and advised Friends to be faithful and steadfast in their love to God,
and to do whatever they could for the Lord in their day and time, adding,
he believed some in that place had not long to live in this world.

He took his leave of the meeting and went into his chamber,
where he continued the most part of two weeks; but by reason of his distemper,
(the small-pox,) lying heavy upon him, he could not speak much without great uneasiness,
yet he bore it with great patience.
While his speech continued, some friends sitting by him, he said,
'`We had need to be prepared for our change; when sickness comes,
we have enough to grapple with, and not to have our peace with the Lord to make then.`'

He was several times exercised in prayer to the Lord, and at one time to this effect:
'`Lord, you who have been with me in the deeps, leave me not to the end.`'
The day before he died, being asked how he had rested, he said,
I think I know when my rest will be; tomorrow morning,
some time after the day be light;`' at which time he died,
being the 27th of the Eleventh month, and sixth day of the week.
He was buried the 29th, in Friends`' burying ground at Allonby, in Cumberland,
and his corpse accompanied by many Friends and others.
And it is assuredly believed that he is entered into the rest prepared for the righteous.
Aged about thirty-five, and a minister nine years.

[.asterism]
'''

WILLIAM GREENUP, late of Flatts, in Cumberland,
was a worthy and faithful servant of the Lord, whose name remains among the living,
and his service and footsteps may be exemplary to those that succeed him, to follow.

He was of great value and esteem, being an elder worthy of double honor,
the Lord having committed to him a gift of the ministry,
and his testimony was living and powerful.
He was fervent in prayer, and his doctrine sound,
delivered in the power and demonstration of the spirit,
and to the edification and comfort of all the true and faithful among whom he ministered.
He was greatly helpful to the meeting to which he did belong,
in managing the affairs of truth, being zealously concerned for the keeping up,
maintaining and promoting good order in the church,
and often advised Friends to faithfulness,
and to keep up their testimony against undue liberty.

He labored to preserve love and unity among brethren,
and travelled for the promotion of truth in many parts of this nation,
as also in Ireland, Scotland, and Wales.
His labor and travail were, both in body and spirit,
to bring men to the knowledge of the truth, and to be acquainted with the Lord,
and to know their peace made with him.
Several were convinced by his testimony, and not only so,
but became fellow-laborers with him in the ministry.

He was very careful and tender over those who were young in the experience of truth,
and where he saw good inclinations to grow,
would often encourage them to their great help and comfort,
as several have good cause to remember.
So that the loss of him is great, though his being taken away is his gain,
being one that truly loved and feared the Lord, and was freely devoted to serve truth,
and his heart and house were free and open to entertain friends.
It pleased the Lord to incline his heart first to
seek the kingdom of God and the righteousness thereof,
in his young years, and as he gave up in obedience to the Lord,
he increased his faith and knowledge; so that he was made able not only to believe,
but to suffer for his name.
And that which crowned his labors was, that he kept steadfast and faithful to the end.

He was sorely afflicted with a pain in his head for some months.
Then it pleased the Lord to visit him with a sharp sickness for about three days,
which he endured with much patience, as was observed by those who went to visit him,
to whom he expressed his being freely resigned to the Lord`'s will,
whether to live or die.

This good man departed this life the 4th of the First month, 1716,
and was buried in Friends`' burying-ground near his own house, at Flatts, in Cumberland.
Aged seventy-five years.

[.asterism]
'''

RICHARD RANSOME, miller, late of North Walsham, near Norwich, in the county of Norfolk,
was convinced of the holy truth about the year 1676, and to him,
through the Lord`'s mercy,
it was given not only to believe in God and in Jesus Christ his Son,
but also to suffer long and hard imprisonment for his name`'s sake nearly fifteen years.
He was faithful and zealous for the Lord, and the Lord was pleased to qualify, call,
and send him forth freely to preach the gospel of peace and of the grace of God,
and he attended him with his presence and power,
and blessed his labors of love for the good of souls.
He travelled much in England, Wales, Scotland, and Ireland.

In his travels in Gloucestershire, he was taken ill, and at Bristol, in the Ninth month,
1716, he took his bed, being visited with the small.pox; which, when he perceived,
he said that as the Lord had carried him through the nation to this time,
and now laid this distemper on him, he thought it was for his end.
So he made his will, and desired a letter might be written to his wife and children.
Considering the great distance they were from him,
he had no desire of their coming to him;
but desired his near and dear love might be remembered to them,
with fervent desires to the Lord for their preservation in the truth,
that they might be kept in true faithfulness and obedience to his requirings,
and that in this their exercise they might keep in
true patience and obedience to the Lord,
who would keep and provide for them to the end of their days, as he had done hitherto.

He said to Friends at Bristol he was glad to see them, '`and that which makes me,
'`said he, '`more glad, is to find truth alive among you.
Keep to truth, the pure truth, the unspotted truth,
and that will keep you a clean people to God; keep to truth, and that will be over all:
'`and he prayed that the Lord would be with his young ones, whom he was bringing up.

Another time he said to Friends,
'`Poor things! do you stand faithful for God and his truth.
Be valiant for the truth, and it will be a comfort to you.
As it is given way to, it will come up into dominion and be over all.
I know what I say.
I have felt the comfort of it many a time, and do now to this very day.`'
Then he spoke of the meeting he had been at, at Thornbury, saying, '`I got comfort there;
Friends were near to my life.`'
Also said, '`I am glad to see the Lord is at work.
He is bringing forth a people that shall stand faithful to him.`'
After a time he kneeled down and prayed fervently for them.

On the second of the Ninth month he took his bed, and several friends came to see him,
to whom he said, '`Friends, the Lord has given me an understanding,
and has let me see many years ago, but more especially of late,
why he afflicted his little ones.
It is in order to drive them nearer home to himself;
for the Lord is about to try his people.
But, dear friends, be not discouraged; for though you may go through the fire,
and through the water, the Lord`'s arm is underneath.
My soul is a living witness of it, and I speak it for your encouragement,
for Jesus carries his lambs in his arms, and leads his along into the low valleys,
in green pastures of life, and to lie down as at noon-day,
where none shall make them afraid.
The Lord is faithful to all those that trust in him.
Therefore be faithful and not wavering;
for those that waver are like the waves of the sea.
There is a day coming, and will come, that shall try the foundations of all,
young and old; and those that are not established on the rock shall be blown away:
but the Lord is raising up some that shall stand as iron pillars for his truth,
and shall not value their lives unto the death.`'

Another time he said, '`Friends, I desire you not to look at any instrument,
but let your trust be in the God of Israel, who shall keep and preserve you,
as he has my soul.`'
Then he prayed that the Lord would`' bless Friends in their meetings and in their families,
and to comfort his afflicted wife and children, whom he had left behind,
and that the Lord would bless and preserve his little ones in this city.

Again, after a little silence, I have another word rises in my heart to speak to you all,
and it is this: endeavor to delight in silence.
Worship the Lord in the silence of all flesh.
Retire in your own families from the clutter and hurries of business of the world,
and wait upon the Lord in stillness; for the Lord will have a willing people.`'

A friend expressed his concern that he should be so suddenly taken,
and with such a dangerous distemper, he replied, in a very comfortable manner,
'`I am well satisfied and content with the will of the Lord therein;`'
and further signified that he found nothing troubled him,
and he was clear, and easy, and willing to die;
and bid the friend give his dear love to Friends at Bath.
And in a solemn and sweet frame, said, '`Farewell; if I never see you more,
be sure to keep to truth, and that will keep you, and do not part with, or lose,
your sense of that for any thing whatsoever.`'

Another time, not long before he died, he said to Friends about him,
'`I am glad to see you, and it is a comfort to me this day;
and I am well pleased that I was brought here to die with you,
and that I shall lay my bones with you at Bristol.
I desire you (that is,
Susannah Thurston and Susannah Parker of Thornbury) that you would be at my burial;
it is the last office of love you can show me,
and send for John Hodges and Henry Sanger.`'

To some Friends who were going to meeting, he said,
(this was not long before he died)'`The Lord be with you, the Lord be with you.
I hope you will have a good meeting.`'

Another time he said,
'`I have made it my care to be obedient to what the Lord has required of me,
and in that I find peace and satisfaction.
Peace on a dying bed is more than all, and I bless God,
I can say in truth without boasting, I feel his peace.
I am easy and freely resigned in his will, and have nothing to do but to die;
for I have faithfully discharged myself of what the Lord required of me,
and am going to receive the reward of my doings.`'

Friends taking their leave of him, he said, in a weighty frame of mind, '`Farewell,
farewell, farewell in the Lord Jesus; for in him alone is it we can fare well.`'

About half an hour before he died, he was raised up in his bed, and said to friends,
'`What need have we to center down in the night season, to feel blessed Jesus,
sweet Jesus, heavenly Jesus to commune with us;
for when he comes he puts an end to all rovings and hurries which are in the world,
with many trials, tribulations and afflictions, which rise not out of the dust.
But dear friends, Israel`'s God will not leave his afflicted ones,
for he will prosper his work which he has begun,
and you shall see it as you are faithful;
and here you shall be made witnesses that one hour in the
presence of the Lord is better than a thousand elsewhere.
For in the world are trouble, strife, animosities and contentions, as you may see;
but all this will come to an end, as we keep in the patience and stillness of Jesus;
for that will conduct us safely to our desired rest, where all sorrows will cease,
and tears be wiped away; and that you may be preserved in true faithfulness,
is the desire of my soul.`'

In about half an hour after, he departed in peace, the 8th day of the Ninth month,
about midnight, 1716.
He was buried the 10th of the same month, in Friends`' burying ground in Bristol.
