== Chapter 5

[.chapter-synopsis]
* John Dickinson
* Ruth Willan
* Richard Hingston
* Alexander Clarke
* Christopher Pearson
* Stephen Manning
* Joan Sley
* Mary Dickinson
* John Gratton
* Joseph Baynes
* William King
* Blessing Fenn
* Ebenezer Slocomb

JOHN DICKINSON, late of Berkhouse, in Grayrig, in the county of Westmoreland,
a few hours before his departure, some friends being there, said,
'`I have taken an inspection into the course of my life,
since the time of my convincement, and I have no ill thing to accuse myself with;
for the fear of the Lord was before mine eyes, by which I was preserved.
Only, said he, when I was set at liberty from my imprisonment,
I thought myself too eager for the getting of this world together;
yet I have not to charge myself with oppressing any man; but what I have,
I obtained honestly.`'
Then he said,
'`I have great peace in that I have been faithful
in bearing my testimony against the payment of tithes;
for I could never either pay, or permit any to pay for me,
hating in my heart such hypocrisy.`'
And to friends by him, he said, '`Give up freely to come to week-day meetings,
to wait upon God, to feel him to renew your strength; for when I had work and business,
I could not be easy to stay from a week-day meeting.
I felt the movings of truth to draw me, and set me at liberty from my outward employ;
not only for my own growth, but that I might be exemplary to others.`'

[.embedded-content-document.letter]
--

[.letter-heading]
The quarterly-meeting at Kendal gave the following testimony,
the 17th of the Second month, 1712, concerning John Dickinson:

He was one whom the Lord was pleased to visit in his young and tender years.
In the time of his apprenticeship he was convinced of the blessed truth,
and afterward suffered great cruelty from his master for using the single language.
And though his said master beat him often, to the loss of much blood,
yet he bore it patiently,
and did not shrink in his testimony which God had given him to bear;
upon which occasion he expressed to several the great
peace and comfort he had from God to his soul.

Some time after his apprenticeship,
it pleased the Lord to open his mouth in a powerful and living testimony,
which was to the great comfort of Friends,
and the edification of the churches of Christ where his travels were;
which were mostly in several of the northern counties, and in Scotland;
and many were convinced by him.

He was valiant for the truth upon earth, and did not turn his back in the day of battle;
but suffered joyfully the spoiling of his goods, imprisonments, and other hardships,
counting the reproaches of Christ great riches; it being given him not only to believe,
but to suffer for his name.

He was a man well beloved of his brethren,
and always had a tender regard for the preservation of unity in the spirit of truth;
a man very careful in answering his word and promise to men; just in his dealing,
often advising Friends to be true to God,
and then they would be just in their dealing with men:
so that we have good ground to believe that his latter end was happy,
and that he finished his course in peace with the Lord.

Thus far we found ourselves obliged in duty to revive the memory of our deceased friend,
that those of succeeding generations may know how our ancients
came to receive the truth in this latter age of the world,
after a tedious and long night of apostasy;
that those who succeed may walk worthy of the privileges they now enjoy,
who are entered into the labors of the ancients, and reap the fruits thereof.

[.signed-section-context-close]
Signed at our Quarterly-Meeting at Kendal, the 17th of the Second month, 1712, by

[.signed-section-signature]
Samuel Parrat, Joseph Peasonn William Williamson, John Towanson, Nicholas Booke,
Richard Skyring, John Skyring, Robert Thompson, John Jopson, Joseph Atkinson.

--

[.asterism]
'''
RUTH WILLAN, wife of Thomas Willan, of Sedbcrg, in the county of York,
and daughter of Thomas Robertson, of Grayrig, in the county of Westmoreland,
was educated in the way of truth, as professed by the people called Quakers,
and was of an innocent life and good conduct, well beloved of her friends and neighbors,
and lived in great unity.
She was long troubled with an asthma, or shortness of breath,
which she bore with great patience.

In the time of weakness, towards her latter end,
she admonished her children to take the advice of good Friends,
and be subject to their father, and to keep to plainness in their apparel,
and not covet after high matters; for she never did; and that the Lord had blessed her,
and had been good to her every way.
She was resigned and willing to leave this world, as she signified several times.
She also said at another time, when her husband, children,
and several friends were present, who came to visit her,
'`The Lord has blessed us both inwardly and outwardly,
and I dearly love my husband and children;`' who were crying about her bed; and she said,
'`My mind is taken off from all visible enjoyments.`'
She blessed God upon her sick bed, saying,
'`I bless God`'s holy name for the many sweet and comfortable
seasons I have had upon my sick bed.`'

She was never heard to murmur in all the time of her weakness,
but lay in a sweet and quiet frame of spirit.
She was visited by many friends and neighbors, to whom she said,
'`I am not able to express the goodness of God I have felt to my soul: '`saying also,
'`I am glad I have been charitable to the poor,
and that I have done good in my day and time.
I have the comfort of it now, and great satisfaction therein.`'

She was a charitable woman to the poor,
and took great delight to serve and entertain her friends.
A little before her departure, she told her husband she had a sweet dream or vision,
and a sight of a glorious place she was going to;
and that she should have an easy passage out of this world;
and asked him if he thought she might continue another night.`'
But, '`said she, '`I am willing to wait the Lord`'s time, though I had rather be dissolved,
and be with Christ.`'
Her husband said he hoped she might.

She was sensible to the last, and in the evening she departed this life very quietly,
like one falling into a sweet sleep, and is at rest with the Lord forever.
She was aged forty-five years and six days.

[.asterism]
'''
RICHARD HINGSTON, a ministering Friend, of the town of Plymouth, in the county of Devon,
being on a journey to visit Friends in Cornwall,
was taken sick with a fever the 4th of the First month, at the house of Thomas Giddy,
of the parish of Kea, being about forty miles short of his home.

In all the time of his sickness he was endued with patience, and many times declared,
'`I am content in the will of God, either to live or to die.
To live a little longer for my family`'s sake, I could desire;
but if the Lord be pleased that I must lay down my head here, I am content.
I shall lay down my head in peace with God, and in love with all men,`'
adding several times, and upon several occasions,
'`I have made it my business from my youth, to make my peace with God, '`etc.

On the 8th day of the aforesaid month, his mournful wife came to see him, and he,
lifting up his hands and eyes, said,
I am thankful to God that it is our lot to see each other again.
We came together in joy and in love, and so let us part.
I desire you and our children may live in the fear of God, and in humility,
and you will never lack.`'
His wife asked him whether he had anything upon his mind concerning his outward affairs;
he answered her,
'`Trouble me not about the world;`' saying he had in the time
of his health declared to her how things should be.

Several friends asked him from time to time how he did; his answer was,
'`I am full of pain, and in hard labor: but I bless God,
it is well with me as to my inward condition.`'
He declared how well it is to make preparation for death in the time of health;
and how unfit poor mortals are for such a work in the time of sickness;
with pretty much more to this effect not noted down.

On the 10th of the said month he quietly departed this life,
and his body was decently buried in Friends`' burying place, in the parish of Kea,
the 12th of the Eleventh month,
and accompanied by many friends and others from several parts,
where testimony was given relating to eternal life,
to the great satisfaction of the concourse of people.

[.asterism]
'''
ALEXANDER CLARKE was by occupation a shepherd, whom the Lord visited in his youth,
when given to pleasure and worldly delights,
and begat in him a true hunger and thirst after the knowledge of God and his truth.
He was drawn from the public ways of worship of many that professed God and Christ,
and from following those that said, '`Lo, here is Christ`' and '`Lo,
there!`' seeing by the light of Christ in his heart,
that their lives and conduct were not agreeable to their profession;
and he became earnest in his desires,
to join with those whose lives and conduct were agreeable to that holy profession,
of which Christ was the high priest and Apostle.
And observing the lives and conduct of the people called Quakers to be agreeable thereto,
he inclined to hear them, and to be joined to them-;
but was cautioned by those professors who knew him, to beware of the Quakers,
telling him they were an erroneous and pernicious people,
so that he became an earnest contender against them.
Some time after this he went to hear them at Geddinton in the county of Northampton,
and after at Wellingborough, where that zealous minister and servant of Christ,
William Dewsberry, preached the gospel powerfully;
so that Alexander Clarke was convinced,
and became a frequent attender of friends`' meetings,
received the truth in the love of it, and waited upon the Lord in silence,
and came to know the spirit and power of God to work in and upon him;
and he became a faithful follower of him.

And when the Lord had fitted him for his work,
and committed to him a dispensation of the gospel of peace,
the word of the Lord came to him as he was following his flock in the field,
and said to him, '`Be faithful, and you shall prophesy: '`and indeed he did,
and freely preached the gospel of Christ.
Though he knew not letters, he was well acquainted with the word of life,
and he often reached to the hearers, and stirred up friends to feel life,
and was instrumental to bring them to the feeling thereof, as they witnessed:
to whom he would often appeal or say, '`You are my witnesses in the Lord,
that I am his servant to serve you in love, and that I preach not myself,
but Christ the Lord.`'

He labored in his Master`'s harvest nearly forty years;
and a little before he died he gave friends who came
to visit him much good counsel and Christian advice,
which is not inserted, because not taken down in writing,
and told them he had finished his course;
and charged his family to love God and each other, and not to forget the Lord, saying,
'`Grace teaches us all;`' which was the last sentence.

So this faithful servant of the Lord kept the faith, finished his course,
and fell asleep in the Lord, and is at rest.
He died in the seventy-fifth year of his age, having been a minister forty years.
Many friends attended his body to the burying-ground at Kittering, in Northamptonshire,
where he was honorably buried.

[.asterism]
'''
CHRISTOPHER PEARSON, of Ulluck, in Cumberland, when he was a lad,
went to a meeting of the people called Quakers, at Pardsay Cragg, in the said county,
in the year 1656.
But when he heard the messengers of the gospel of Christ declare the everlasting truth,
who were sent of God to turn people from darkness to the light of the Lord Jesus Christ,
through their testimony, he was convinced by the spirit of truth,
and was thereby reproved for his vanity, and was reached by the Lord`'s power,
and came to know the work of it, and to wait upon the Lord therein,
to witness a being cleansed thereby, and his faith to stand in it;
and so to experience the sufficiency of it.
It was not only given to him to believe in the Lord Jesus,
but also to suffer joyfully for his sake the spoiling of his goods,
and in his deepest sufferings he was supported.

A few days before he died, he said, '`The Lord has been kind to me from a child,
and has done more for me than I could either ask or think:`' adding,
'`I never turned my back upon an informer,
nor ever wronged any man of one halfpenny in all my life to my knowledge.`'
Then he advised his children to be careful, and said to them,
'`Do no harm either to man or beast; but do good wherever you come,
as I have showed you an example.`'
He was a good neighbor, an honest friend, a loving husband, a tender father,
a man given to hospitality, and careful to entertain strangers.
The Lord was with him when on a sick bed,
and his heart was tendered with a sense and feeling of his love and kindness.

A friend being by him, asked him how he did, and how he was satisfied;
he cheerfully answered, '`I am very well satisfied that all will be well;
for I find the Lord`'s mercies are great: but, '`said he, '`I am in great pain,
and think the time long till I am released.`'
Adding, to the friend, '`We have seen much since we were convinced.
We have gone to the meetings in true humility, fear and plainness:
and truth is what it was,
and all that keep faithful to it will be kept by it out of all evil.
I am glad to see my son settled, and I doubt not but he will stand up in my place;
I advise him to be a good neighbor.`'
This ancient Friend, being in great affliction of body, often prayed to the Lord Jesus,
that he would remember him, and take him to his mercy,
that he might be eased of his pains and this troublesome world.
He kept his integrity to the end, and it is not to be doubted but he finished in peace.
His corpse being attended by many friends and sober people to Eaglesfield,
was there honorably interred, and the Lord`'s power was manifest among them,
and the way of life and salvation proclaimed,
with a warning to all to repent of their wickedness, and turn to the Lord,
that they might be prepared for their final change.

[.asterism]
'''
STEPHEN MANNING, son of Edward and Alice Manning, of Edmondsbury,
in the county of Suffolk, was educated in the way of truth,
and was from a child of an innocent and upright life,
zealous and constant in attending religious meetings,
and went several miles to them on foot.
He was a diligent waiter upon the Lord therein, and received much benefit thereby,
in having his understanding enlarged, his strength renewed,
and his heart filled with the love of God, who was pleased to put him into the ministry,
and caused him to declare his everlasting truth,
and to exhort the Lord`'s people in faithfulness to persevere in the way of the Lord,
and to be diligent to wait on God,
that they might live in and enjoy what they were convinced of.
He was also zealously concerned to caution against pride and covetousness,
and superfluity in apparel, and to beware of those sins,
and the various workings of the enemy.

He was a meek, steady man, and lived in what he preached, being exemplary in his conduct,
as became his holy profession.

He was also concerned that the orphans of poor Friends should be taken care of,
and educated in sobriety and in the way of truth.
Being sensible that in some places there was too much neglect,
he wrote an epistle to Friends on that account, which Friends were well affected with,
and read in the meetings which they had for that and other concerns,
as taking care of the poor, etc.

He travelled into several neighboring counties, as Essex, and Norfolk, to London,
and other places, and his labor of love was well received: but growing very ill and weak,
he was unable for such journeys,
and in his bodily weakness travelled and visited
Friends in their meetings ten or eleven miles about.
And when he could not go so far, he attended the meetings nearer,
till he was so weakly he could not: then many friends came to visit him,
to whom he declared truth, and said, '`I have desired to have a name among the righteous,
and the Lord has answered my request.
I have served the Lord faithfully, and have the answer of well done in my bosom.`'

Several tender people, not called Quakers, came to see him, to whom he said,
'`It is well with me, and the Lord will carry me through to my desired place.
It is a brave thing to have a conscience void of offense towards God and men:
there is heaven upon earth.`'

He was a man of few words, but savory;
he had great love and large compassion towards those who had any good desires in them,
and was tender to those whom the enemy, by his subtlety and their unwatchfulness,
had drawn aside out of the right way, and often exhorted,
that they and all might labor to have a possession in the truth, and said,
'`A profession thereof only will not do.`'

He bore his illness with great patience,
to the admiration of those who came to visit him:
he was truly resigned to the will of the Lord, whether in life or death.
He acknowledged his dear and tender father and mother`'s care over him,
and his brothers and sister`'s love, also friends and neighbors who came to visit him,
and said to them, '`My peace is made.
I have nothing to do, but to wait for my change, which I long for.
I have served the Lord to my uttermost, and am sure of an inheritance with him,
who is worthy to be served; he is a good rewarder.`'

After a meeting several friends came to see him,
and one friend spoke to him of his journey to Hopton, after which, he was taken ill:
he said, '`I cannot tell but it might weaken me, but I do not repent it,
being in the service of truth.`'

He exhorted friends to love and unity among brethren, which he delighted in, and said,
'`There was a spirit getting in among the professors of truth, which sought discord;
beware of it.`'
He also signified the judgments of the Lord were come, and coming in this nation,
and said, '`Do nothing whereby to cause the Lord to be grieved;
but be faithful in all things.`'

Some time before his death, on a First-day,
one of his brothers and sister sitting by him, he spoke several things relating to truth,
and the peace and joy he felt: '`And one thing,`' said he, '`I know not, and that is,
why the Lord so filled me with his love this morning,
who account myself but as dust and ashes.`'

About three days before his departure he thought he had been going to his desired place,
and took his leave of his parents and relations, and bade them farewell;
'`I hope I am going to an everlasting habitation,
where I shall dwell forever with the righteous generation;`' more he then said,
which could not be understood: his lips going, his brother endeavored to hear,
but could only understand these words, '`Innocency you love, Lord.`'
After he revived, and next day, though his voice was very low,
he spoke several weighty things, and said, '`Dwell in love, and let it increase.`'

On the third day of the week, and first of the Third month, he said, '`I am extremely ill,
but I hope the Lord will shortly ease me.`'
About the sixth hour at night, he fell as it were into a sleep,
and lay nearly three quarters of an hour, and so passed away quietly;
and a few days after, he was buried,
being carried from Bury meetinghouse to Friends`' burying-ground,
accompanied by many Friends and others,
and several testimonies were borne in love to the truth,
that had made the deceased what he was,
and of their satisfaction that he was gone to his everlasting rest.
Aged thirty-one and three-quarters; and a minister eleven years.

[.asterism]
'''
JOAN SLEY, late of Alton, in Hampshire, was an honest, zealous and faithful woman,
one that loved our Lord Jesus Christ, his ministers and faithful followers,
and was very diligent in meeting with the Lord`'s people to worship and serve him.
Whatever loss or suffering she met with for the same, she neglected hot that service;
and as she diligently sought the Lord, he rewarded her, renewed her strength,
increased her love and zeal for the truth,
and preserved her in his fear to a good old age.
He endued her so with his wisdom,
that she thereby was directed to order her conduct
as became the holy profession she made,
and in that plainness and uprightness of heart that becomes a mother in spiritual Israel,
whose faith and example is worthy to be followed; and she, among the righteous,
to be had in everlasting remembrance.

She was also very tender and charitable to the poor,
and forgot not to do good and communicate.
She was early convinced by that ancient and eminent minister, George Fox,
and being faithful to the Lord, was zealously concerned to bear her testimony for him,
against whatever he showed her to be contrary to truth and the purity of it.

After her first convincement,
she met with sufferings and afflictions from her own husband for a time,
and afterwards from others in her own house; for, after her husband`'s death,
she kept the Crown inn, at Alton, about forty-six years.
She was faithful in her testimony relating to truth,
and zealous in her own house against all manner of excess:
all which gained her a good report.

In the time of her illness, and near her end,
she commemorated`' the dealings of the Lord with her, and how he had been on her side,
and stood by her in the many great dangers and sufferings she had gone through,
in bearing her testimony among the soldiers and rude
persons that sometimes were in her house.

To the last she was lively in her spirit,
and the Lord was indeed wonderfully good to her, and carried her through all her trials,
and the temptations and provocations of the enemy, both within and without,
that attended her.

She had her memory and understanding to the end,
though in the eighty-fourth year of her age,
and was concerned for the prosperity of truth to the last, saying,
'`If it be the Lord`'s will,
I desire he may extend to the young generation a fresh visitation;
for nothing short of a holy life and godly conduct will do.`'

She advised the youth to read the Holy Scriptures,
and particularly the last chapter of Joshua,
that all might serve the Lord in sincerity and truth, which she had done,
and had the comfort thereof in her dying hour, which was in peace with God.

And as she was well beloved in her life, so, when she was dead,
her body was attended by a great many friends and neighbors, and interred at Alton.

[.asterism]
'''
MARY DICKINSON, daughter of Daniel Dickinson, of Plumland, in Cumberland,
departed this life the 25th of the Eleventh month, in the fourteenth year of her age;
of whom take the account following:

She was naturally of a cheerful disposition, but well inclined to what was good;
patient under what she met with that was not pleasing to her; not apt to be provoked.

The Lord was pleased to give her an understanding of his divine truth,
and so affected her heart with love to it,
that when he was pleased to visit her with that sickness,
of which she died in about fourteen days after,
she was very patient and resigned to the will of the Lord.

Her father, some days before her departure,
asked her whether she had rather die than live; she answered readily, she had rather die,
because she hoped a better place was prepared for her;
and the same question being put to her another day, she gave the same answer.
With brokenness of heart she often prayed unto the Lord.

The day she departed, her mother being by her, said, '`Wait with patience,
the Lord will not tarry long.`'
Then this young virgin, being broken in spirit in much tenderness,
with a heavenly harmony sang praises to the Lord, and uttered many divine sayings,
and cried unto the Lord, saying, O Lord!
I pray you remember me this day, and open a door of mercy for me, and take me to yourself.
Lord, have mercy upon my poor soul this day, and open to me this day, I beseech you;
for there is none like unto you; no, not one.`'
Then, speaking to those by her, said, '`Fear God, and love him, and keep his commandments,
all of you; and be merciful to the poor, I beseech you all that hear me.`'
After, her father asked her if she had any pain; she answered, '`My pain is taken away.`'
Again, her father said to her, Do you know, my child,
that the Lord has prepared a place for you?`'
She answered, '`Yes; and not for me only, but for all those that love and fear him,
and keep his commandments.`'
About an hour before her death, she being tendered in spirit,
and melted as wax before the fire, asked for a Bible; which being given to her,
she readily turned to the eighth chapter of Genesis, and distinctly read it; then,
covering herself, sweetly died without either sigh or groan.

[.asterism]
'''
JOHN GRATTON was a man of note,
and one whose Christianity showed itself in the spirit of meekness and humility,
notwithstanding many troubles and exercises which he met with.
He was also an able minister of the everlasting gospel,
being made instrumental for the convincement of many.
He had great openings, was sound in doctrine, and skillful in hitting the mark.
His ministry was lively and powerful, plentifully opening the Scriptures.
He travelled much in the service of truth, both in this nation,
and in other countries adjacent.
His residence was at Monyash, in the county of Derby, above forty years,
where friends were often comforted in his company, and therefore loved him in the truth,
and do believe that he lived and died a servant of the Lord.

The winter before his decease he sensibly decayed,
so that he would often say he could not continue long; his stomach being so weak,
he could take little food for several months before he died.
His desires were great to go hence, if the Lord saw it good;
and as his weakness increased, his desires, if could be,
grew stronger and more earnest with the Lord,
to remove him out of this troublesome world,
being well satisfied his day`'s work was over; yet desired to wait the Lord`'s time.
A grand daughter of his being then very ill,
he often gave good advice and counsel to her, to fear the Lord,
and be obedient to her parents; with more to that effect to all his grandchildren.

About a month before his decease, his daughter was called on so suddenly,
that it was thought he could not live till she came to him.
She found her children and the maid weeping, thinking he would not have spoken again,
but when he saw her, he broke out into tears,
saying he thought he should never have seen her more;
but soon got a little strength to sit up in his chair,
and called all the children to him, one by one, and kissed them, giving them good advice,
saying it was a great comfort to him,
to see that they should part in so much love and unity one with another.
Calling for the maid, he spoke very tenderly and lovingly to her:
and being attended with sore sickness and pain, he said, '`Lord,
I pray you give me ease if it be your holy will, and remove me soon out of this body.
You know it is through your great mercy that we have hope in you.
Lord, I pray you, be with my children that I leave behind,
and with all friends and neighbors, of what profession soever.
It is through Christ Jesus our Advocate, who is gone before us,
that we are enabled to come to you.`'
And further said, '`Lord, if it be your holy will, remove me out of this troublesome body.`'
Another time some friends being come to visit him,
he was told there were such friends come to see him:
he said they might see he was a weak man: and looking on them as they sat by him,
he said, '`The Lord bless his people and prosper his truth among them,
and enable them to live in love one with another.`'
Not long after, weakening very fast, he said, '`Lord,
I freely commit my soul and spirit unto you.`'
He desired to have his dear love given to friends, naming several particulars;
and a little before he died, told his daughter,
now he thought he should be gone in half an hour; being very sensible to the last.

He departed this life at Farnsfield, in Nottinghamshire, on the 9th of the First month,
1712, and is at rest with the Lord, where the wicked cease from troubling,
and where the weary are at rest.
He was buried the 11th of the same month, in the sixty-ninth year of his age,
having been convinced of the blessed truth about forty years.

[.asterism]
'''
JOSEPH BAYNES, of Stangerthwaite, in Killington, in the county of Westmoreland,
was born of honest parents.
In his young years he was desirous to attain to the true knowledge of God;
which desire God graciously answered to his seeking soul,
in convincing him of his blessed truth, by that faithful laborer and servant of Christ,
George Fox, at his first coming into these parts, being in the year 1652,
by whose ministry he was turned to the light of Christ Jesus,
by which he came to see the emptiness of those outward forms
and ceremonies in which he had been educated.

He was a man who truly loved and feared the Lord,
making it his daily care to keep his conscience void of offense towards God and man.
A considerable time after his convincement,
it pleased the Lord to open his mouth in a public
testimony for the truth he was convinced of.

His doctrine was sound, expressed deliberately with clear distinction,
and a solid grave countenance.
His deportment was such as very much adorned his ministry;
all which rendered his service the more acceptable both to friends,
and others not professing with us, among whom he gained a good esteem.

He suffered joyfully the spoiling of his goods,
for his testimony against that anti-christian yoke of tithes,
and on several other accounts for truth`'s sake:
He endured many imprisonments with steadfastness and great patience,
being truly thankful that the Lord had counted him worthy to suffer for his name.

In the latter part of his time he travelled very much in this nation for many years,
He had a great love and esteem for the yearly meeting in London,
which he manifested by diligently attending it, even from his youth,
until by old age he was unable to travel so far.
He very much labored to promote love and unity among friends;
expressing how hard a thing it is to reconcile an offended brother.

He was a nursing father to the youth, lending a hand of help to the weak,
and young convinced, in order for their settlement and growth in the truth;
and was careful to visit the sick,
imparting such advice and counsel as was proper for them.

A little before he was seized with bodily weakness,
a concern fell upon him to advise young men and women to wait for the power of God,
which would work a change in their hearts, and make them new creatures; otherwise,
said he, they will but have a form of godliness, without the power;
and such live in an unregenerate state, who produce the fruits of nature,
but not of grace.
Mark, said he, grace teaches to deny ungodliness, and the world`'s lusts; to live soberly, etc.
But alas! too many of our youth, for lack of taking the grace for their teacher,
go into a false and undue liberty in their words and apparel,
making that of no conscience to them, that the power of truth made conscience to us.
For by that power we were made willing to put off all superfluity in eating, drinking,
and wearing of apparel.
Our words were few and savory, for the Lord`'s dread was before our eyes,
and our peace with him was precious to us, which we,
through obedience to the grace of God in our hearts, enjoyed.
This, with much more wholesome counsel, he imparted to the youth.

He was under bodily weakness for a considerable time,
in which he told friends who came to visit him, that the Lord was good to him,
and that he had many precious openings upon the Holy Scriptures,
brought very clearly before him, beyond what he had ever seen before:
several of which he spoke of with much tenderness and brokenness of heart,
to the refreshment of those present;
in particular concerning the death and sufferings of Christ,
and the hard-heartedness of that unbelieving generation,
making a parallel between them and the hard-hearted,
and unbelieving in his spiritual appearance, in this age of the world; which, said he,
'`makes a sorrowful impression upon my spirit.`'

'`I had a sense,`' said he, '`that I must not continue here long, but lust die and not live;
but I covet not long life,
hoping to be gathered to my dear brethren that are gone to their rest before me:`'
signifying his satisfaction and assurance of peace to his soul,
when his days in this world should be at an end.

The day before he died he sent for a friend whom he desired to see, and when she came,
he said, '`I much longed to see you once more, '`she having made him several visits.
I am under great affliction of body,
but hope the Lord will cut the thread of my life before long.`'
She replied, '`It has been a long time of illness to you, nearly three quarters of a year.`'
'`Yes,`' said he, '`but I have had great ease at times,
for the Lord has been very good and gracious to me all along,
though I am not worthy of the least of his mercies;
but for his Son`'s sake I hope he will remember me in a little time,
and ease me of all my pain.`'
Though he was exceedingly short of breath, besides great pain of body,
yet he spoke of several matters relating to truth,
being engaged in his mind for the honor of it.
After this, he had a sweet time in supplication to the Lord, for his goodness to him;
then lifting up his dying hands, which trembled through weakness,
he took leave of the friend, saying, '`Farewell, the Lord be with you.`'
He said little more, but lay still, as if he felt not much pain,
and so departed this life in much peace, upon the 26th day of the First month, 1714,
and was buried the 28th of the same, in Friends`' burying-ground at Brigg-Flatts,
near Sedburgh, aged eighty-one years.

[.asterism]
'''
WILLIAM KING, late of Oakeliff, in Yorkshire, was a man fearing God,
of a peaceable conduct, not only in the church, of which he was a faithful member,
but likewise to such as were without; and he obtained a good report among both,
and has left a sweet savor behind him.

It pleased the Lord to commit to him a dispensation of the gospel,
and therein he approved himself a faithful and true laborer,
according to the measure of the gift bestowed,
to promote truth and righteousness in his day, and was a good example;
and manifested to all,
that it was his chiefest care to live a life answerable to what he made profession of,
often advising friends to keep to the root of life, the spring of divine wisdom,
from which all good comes.

He was also a diligent attender of meetings, and advised friends to faithfulness therein.
When his departure was near at hand, he, as he often had,
gave good advice and counsel to his children, to keep to the truth,
and to set their hearts and doors open to the friends of it;
saying he had as much love to friends and truth as ever.
To a friend who came to visit him, he said, '`I am fitted to die.`'
At another time he said, '`I can with the apostle say, measurably,
I have fought the good fight, and kept the faith, and well nigh finished my course,
and there is a crown laid up for me.`'
He often declared his full satisfaction concerning his future well-being;
and uttered many more weighty expressions, not noted.
He departed this life the 17th of the Third month, aged sixty-five years.

[.asterism]
'''
BLESSING FENN, daughter of Joseph and Patience Fenn, of Cork,
was born the 8th day of the Fourth month, 1700.
She was a child of a weakly constitution, and for several years very sickly,
but of a ripe and ingenious wit.
For the most part, while she had health and strength,
she delighted to be employed about some business that was innocent and profitable,
not loving idleness; and also was much delighted in reading the Holy Scriptures,
and other good books,
and would often make her remarks on several passages
as she read and speak of them to her mother,
asking several weighty questions.
She was very dutiful to her parents, and extraordinarily tender of her mother,
who was sickly.
She loved honest Friends, but would be troubled when she beheld any, professing truth,
behave themselves unseemly.

Some weeks before she died, her mother went with her a mile or two out of the town,
to a neighbor`'s house, for the benefit of the fresh air,
where she continued until she ended her days.

In the time of her sickness she was very careful of her mother,
and would often keep her pain much to herself, lest her mother should be troubled.
The sharpness of the pain, together with her great weakness,
would cause her at times to fret,
and speak a little angrily to the nurse that attended her,
but she would soon be sorry for it, and say to the nurse,
'`Do not take notice of what I say,
for I love you very well;`' and would discourse sweetly with her,
and give her good advice.

She did not seem to take much notice of her end being
so near till the morning before her departure;
at which time, her mother perceiving an alteration in her,
asked her if she was willing to leave heir.
She answered, '`What the Lord will.`'
Her mother replied, '`It is hard for me to part with you.`'
After a little pause she said, '`It is true I am very weak,
but the Lord is able to restore me to you again;`' and more to that effect,
which was thought to be spoken to prevent her mother`'s grieving for her.
Her mother asked her if she was willing to see a Friend who was expected in town soon:
she answered`' Yes, or any honest Friend.`'

In the afternoon two Friends came to visit her, and being in the room with her mother,
the nurse was on the bed by her; she said, '`Nurse,
do you think I shall live till tomorrow?`'
The nurse answered, '`Yes, and a great deal longer.`'
No, '`said she, I shall not; and immediately cried out, '`Lord help me,
Lord help me!`' Her mother hearing her, stepped hastily to her,
and asked her what was the matter.
The two Friends coming to her as she sat up in bed, she looked solidly at them, and said,
'`Pray to the Lord that I may have a short and easy passage.`'
One of them said, '`You have had a long time of consideration.`'
She answered,
I was never wanton in the time of my health;`' and so immediately fell into a great agony,
death-pains seizing her.
She again desiring them to pray for a short and easy passage; a Friend answering, said,
'`We must wait God`'s time, and I believe it will not be long.`'

Her mother asked her where her pain was; she said, '`Everywhere.`'
Then she said, '`Lord, give me patience;`' and asked several times`' Will it be long?`'
After some time the extremity of her pain left her,
and she sat pretty quietly with her eyes shut, then opening her eyes again,
a friend told her she had got a little sleep.
'`No,`' said she, '`I was enjoying sweetness.`'
After a little while her pain increased again, but not so violent as before:
her mother asked if she had a desire to see her father: she said, '`Yes,
if he will come quickly.`'
Her father being sent for, soon came with some other of her relations, and he,
sitting on the bed by her, asked her how she did.
She looked at him, but did not speak;
at which her mother asked her if she would not speak to her father.
She said, '`I cannot yet;`' being in pain.
After some time, she looking earnestly at him, said, '`Father, pray for me,
that I may have a short and easy passage.`'
Her father being nearly concerned for her,
after a little while kneeled down by her bedside to pray,
and desired that as the Lord had been pleased to give her to him,
he would be pleased to take her to himself, and that he might make her passage easy,
and all of us subject to his will; and more to that effect;
concluding with thankfulness for all the mercies we receive:
at which time she was very quiet and attentive.

After a little while her father asked her if she was freely given up in her mind:
she said, '`Yes, I am, freely.`'
Being asked if she was willing to leave her father and mother, she said, '`Yes, I am.`'
After that, she said, '`Lord, take me to yourself.`'
So she continued in a sweet frame of mind; desiring those about her to be quiet,
when she heard any speaking, or noise in the room.
She remained quiet and sensible to the very last,
and so died about the ninth hour in the evening, the 12th of the Third month, 1713,
being four weeks short of thirteen years old.

[.asterism]
'''
EBENEZER SLOCOMB, who departed this life at his own house in James Town,
on Conanicut Island, the 14th day of the Second month, 1715,
in the sixty-fourth year of his age, was born in Portsmouth, on Rhode Island,
the 25th day of the First month, 1652,
and had his education among those people called Baptists.

Being a man of great stature, and strong and nimble of body,
he was given to those recreations that were in those days accounted civil;
but about the twentieth year of his age,
it pleased God to send his faithful servant George Fox, into those parts,
and he was willing to go to hear him preach, which he did.
But being in that nature which understood not the things of the spirit of God,
he came to this conclusion in his mind, never to hear any of the Quakers again,
boasting in himself that the Baptists were nearer the rule of the Scripture than they.

Thus he went on for some time, until God, who brings down the high from their seats,
and scatters the proud in the imaginations of their own hearts,
was thus pleased to manifest himself to him.
He, with two more of his company, were passing by a barn, where there was a meeting,
at which was that eminent gospel minister, John Burnyeat, of Cumberland,
of the nation of England; and he being preaching as they were passing by,
they all went to the outside, to hear two or three words,
to talk of as they went on their way.
It so pleased God,
that at that instant John Burnyeat was treating of that saying of John the Baptist,
where, speaking of Christ, he said,
"`He shall baptize you with the Holy Ghost and with fire;`"
which Ebenezer did not remember he had ever read,
although he thought he knew more Scripture than any of the Quakers.
He was willing to lean against the door-post to hear farther,
although his companions jogged him to be gone.
Yet he stayed,
until through the powerful preaching of the gospel he was reached to the heart,
and made in his own soul to confess,
that all his Scripture knowledge and high notions of water baptism,
had left him short of the new birth,
and the baptism of Christ by the one Spirit into the church, which is his body.
Yet he did not give up in obedience for some time,
until the fire of God began to kindle in his own
soul against the root of the corrupt tree,
and every branch thereof; for he found that saying of the prophet fulfilled,
that "`There is no peace to the wicked.`"

About this time, being with his newly-married wife at a merry-making,
where they were pitching the bar, they persuaded him to pitch with them, but he refused,
being sensible the Lord had appeared to him, to redeem him out of such vain delights.
But they at last set his wife to work; and she, through much entreaty,
prevailed with him to pitch once.
And although he outdid all the company, to their rejoicing who set him to work,
yet the Lord, who requires obedience according to the understanding given,
set his folly and shunning the cross so powerfully before him,
that for a time he thought the day of his visitation was over.
Yet he, who in judgment remembers mercy, after some time,
was graciously pleased to show him, that he might come out of condemnation,
by obeying the law of the spirit of life, which now, through Christ,
was made manifest in his mortal body, to reprove sin in the flesh:
to which he gave up in faithfulness.

The Lord was near to him, both to comfort him in his exercises,
and also to give him sound wisdom,
and a divine understanding in the mysteries of his kingdom.
After a few years He called him into the work of the ministry,
in which he approved himself a laborer who needed not to be ashamed;
for he rightly divided the word of truth, being sound in doctrine,
and his speech very often ministered grace to the hearers,
and was sealed by the spirit of God to many of his auditors,
to the turning them home to Christ, the great minister and mediator of the new covenant,
which God has made with his people in this latter age of the world.

He was also made an overseer of the church in these parts, by the great Bishop of souls,
and Shepherd of the sheep; in which he acquitted himself like a true servant of Christ,
being a pattern to the flock in his conduct and Christian humility;
as also in his apparel and furniture.

He travelled much in the work of the ministry for the space of thirty-six years,
both in the colonies of New England, and also several times to Long Island,
East and West Jersey, and Pennsylvania, and in his latter years to Maryland,
about 500 miles from his habitation;
in which travels several were convinced of the everlasting truth through his ministry;
also the convinced were built up in the most holy faith,
which gives victory over all the works of the flesh.

He was also very serviceable in meetings of business where he came,
that the professors of truth might, in all their conduct, be brought to walk in the same,
having an excellent gift in the service of the church.

In the latter part of the year 1714, he travelled to Boston, Lynn, Salem, Hampton,
and Dover, taking his leave of Friends, saying he never expected to see them again;
for he had a sense that his time in this world was near to a period;
and was also in this journey very serviceable in
preaching the gospel of Christ with power,
and with an audible voice, and in giving good counsel to Friends.
When he was at home, he always delighted in the company of Friends,
who stood zealous for a right godly discipline and good order in the church of Christ,
which the Lord has measurably established among Friends, that so the honest,
though weak, might be preserved, and all disorderly walkers who would not be reclaimed,
might be testified against, as professors who are gone from our holy communion;
in which good work,
this Friend was one of the first rank in these American parts of the world.

As on one hand he always accounted the disorderly walkers, under profession of truth,
his enemies, and they often found from him a stroke of sound judgment,
so on the other hand,
he was a tender nursing father to the honest-hearted
and young scholars in Christ`'s school.
He ruled not with severity over any, because they were younger than he;
but always delighted to see young men come up in a part
of the good order established among his people.
And if at any time they were too zealous to be borne
by the old and loose professors of truth,
he would commend their zeal, but gently instruct them to use wisdom in their management;
in which good work the Lord greatly blessed his labor to his people.

He would also give way very much to those newly called into the work of the ministry,
if they kept to sound words and doctrines, which are according to godliness,
ministering from the ability which God gives.

Thus he, with much sweetness,
continued a faithful elder until the sixty-third year of his age,
and then he was taken ill with the yellow jaundice,
and other distempers setting in together, he continued very weak all the winter,
very often expressing his willingness to submit to the will of God,
either in life or death.
He was often concerned in the time of his sickness for his children,
that they might walk in the way that is strait and narrow, and leads to eternal bliss;
telling them he had done his duty in teaching and instructing them,
as much as in him lay,
and letting them know his earnest desire that they should keep in the unity of Friends;
and that it would prove their utter ruin, if they went from it.

He would in his sickness very often be talking of his desire
that Friends might be kept in love and unity;
and so continued at times in a divine sense of God`'s goodness and sweet peace.
At one time, several friends being present, he gave to each of them suitable counsel;
and soon after said to his near friend and kinsman, Jacob Mott, then present,
with whom he had very often travelled to preach the gospel,
'`I desire you to remember my dear love to all Friends in New England;`' and further said,
he had done his day`'s work, having peace with God, and unity with his people.
And then like a composed Christian, who had fought the good fight of faith,
he took leave of his family one by one; and after some time, departed very quietly,
and doubtless is entered into that rest which is prepared for the people of God.

He was buried from the meeting-house at Jamestown,
after there had been several testimonies borne to that truth
made manifest in this latter age of the world,
by the spirit of God, in the hearts of the sons of men,
in which this dear Friend had lived and died.
