== Chapter 6

[.chapter-synopsis]
* Isabel Gill
* Daniel Gould
* John Bowstead
* Sarah Elkington
* William Taylor
* Richard Heydon
* Margaret Hoare
* Jonathan Tyler
* John Skelton
* Anne Dixon
* John Crudson

ISABEL GILL, wife of Joseph Gill, was born near Carlisle, in Cumberland,
in the year 1670, of honest parents, who, with most of the family,
were convinced of the blessed truth.
In her young years, about the age of twenty, she went to London,
where she lived seven years; and after her return into Cumberland,
was married at Carlisle aforesaid, in the year 1702,
and soon after went with her husband into Ireland, and settled at Dublin.

She was a loving and faithful wife,
a true help-meet both in spiritual and temporal concerns;
a tender mother to her children; a good example to her servants in plainness;
a woman of an excellent temper and good understanding,
mostly cheerful and loving in her family,
having attained to a good degree of growth in the truth, more in substance than in show;
a fervent lover of honest friends, and open-hearted to them.

Towards the latter end of her time she was much attended
with infirmity and weakness of body,
yet cheerful in her spirit, truly sympathizing with her husband under exercises;
encouraging, counseling, and helping him forward, in what she was sensible was his duty.
She often advised him to be careful to do his day`'s work in his day;
cheerfully giving him up, and putting him forward to go abroad upon truth`'s account,
even when she had need of his company at home, by reason of her weakness;
often expressing her desire never to hinder him, though his company was dear to her.
And when he was abroad she concealed her illness, lest she should draw him home too soon.

Some time before her decease, when confined to her chamber, by reason of bodily weakness,
many friends came to visit her, and often had sweet seasons with her,
the Lord`'s power and presence breaking forth,
to the tendering of both her and them together.
She often expressed a great concern for the good of others,
testifying that the Lord was angry because of pride, drunkenness, and other wickedness;
and faithfully admonished several who came to visit her,
giving counsel and advice suitable to their states and conditions,
of which she had often a clear sense, and would desire them to prepare for such a time,
meaning a dying bed.
She expressed her satisfaction with the Lord`'s dealings with her,
and the comfort and peace she enjoyed in him, often praising and glorifying him,
for his preservation and goodness to her from a child to that time,
with many sensible expressions, some whereof do follow.

She said to her husband, My dear, do you give me up?
Pray give me up freely to the Lord who gave me to you.
He is worthy to be submitted to; his secret hand was with us, in bringing us together,
and we felt his love and living presence at our marriage, and it is with us at this time,
and I hope will be at our parting.
Be not troubled to stay behind me, the Lord who has been near, and with us together,
will be with you, and help you, and bear you up in all exercises and difficulties,
and provide for you, if you still keep near him, and serve him,
according to his requirings: '`with more expressions to the same effect.

Being very ill, and observing her eldest daughter and another friend crying by her,
she said, '`Cry not for me,
but for yourselves;`' and pressed them several times to take
care and lay up something against a time of need,
and seek to be married to the Lord, and that will be a good marriage.
I see no cause to cry, or be sorrowful for me, for I am happy.`'
She often sensibly expressed that her peace was made with the Lord,
and she was not afraid, nor dismayed at death,
but was freely resigned to the Lord`'s will,
who had been her strength and support from her childhood,
and now found him near to help her over exercises,
and make her willing to leave her tender babes, and all that was dear to her,
to his providence.

A public friend, whom she loved, being in town, and having visited her in the evening,
she sent for him next morning, and having a concern upon her,
charged him to cry out against the crown of pride, and drunkenness, etc., saying,
'`The Lord has put an arrow in your hand, let it fly,
and spare not;`' with other exhortations to him of the like nature.

When some young women came to visit her, she charged them not to be high-minded,
nor give way to pride and nicety,
by reason of the riches their parents might have to give them,
which would be of no value without the blessing of the Lord;
which she advised them to seek after above all things.

At another time, when some young married women visited her,
she advised and warned them not to be nice or high-minded,
neither to deck nor adorn their children too nicely, dressing them up like pictures,
and then admiring them; for if they did so, the Lord might take them away from them;
but to keep them clean and sweet, out of nicety, and the Lord would bless them.

Some that had been of loose and ungodly conduct, who came to see her along with others,
she advised to keep under judgment; and plainly told one person that he was too high,
and had abundance yet to go through for his transgression;
and that if he did not come down lower, he would fall again.

Her distemper increasing, she grew weaker, and being often in great pain,
she was concerned to pray to the Lord for some ease,
that she might know what it was before her departure,
and that he would give her an easy passage, meaning her death.
Both which requests the Lord was graciously pleased to grant her;
for about two weeks before her death she obtained great ease, and lay pretty quietly,
without any discernible alteration, until about two minutes before she departed,
which was as one falling asleep in a quiet manner.
She died in the city of Dublin, in Ireland, the 8th of the Twelfth month, 1713.

[.asterism]
'''

DANIEL GOULD received the blessed truth about the year 1658,
and followed the Lord in the way of his requirings,
going through many and deep tribulations.
After some time a concern came upon him to visit his brethren,
William Robinson and Marmaduke Stevenson, who were under sufferings at Boston,
in New England, where they afterwards suffered martyrdom for their obedience to God,
in bearing a testimony to his blessed truth; with whom he also suffered imprisonment,
and cruel whipping, being then about the thirtieth year of his age.

After his discharge there, he retired to Rhode Island, and the Lord opened his mouth,
and made him a minister of the everlasting gospel of Christ Jesus.
In which service he labored about forty-five years,
and travelled in many parts of New England, Staten Island, Long Island, New York,
East and West Jersey, Pennsylvania, to Maryland and Virginia, several times;
and God blessed his labors, so that several were convinced,
and turned to the Lord through his ministry.

He was a man richly furnished with the gifts of the Holy Spirit; patient under exercises;
grave in behavior; pleasant and exemplary in conduct; his ministry weighty and deep,
tending to the consolation and comfort of God`'s people.
Unity of brethren was his soul`'s delight.
He endured many hardships for his faithful testimony to the blessed truth,
and was greatly capable, through his long experience,
to advise and give counsel to persons in all conditions,
and was a diligent and early comer to meetings.

His understanding and memory in his latter years had more than common brightness.
In the time of his sickness, he greatly desired and delighted in the company of Friends;
and some days before he died he said to a friend who was with him,
'`I have a desire to see some Friends,
(that were gone to a quarterly meeting,) inquiring if they were returned.
The Friend answered, '`They are not; we look for them every day.`'
He replied, '`I fear I shall not live to see them: but let death come when it will,
my reward is sure`'

He often expressed great satisfaction and resignation in the will of the Lord;
and with much patience he endured his long and tedious sickness,
although at times attended with sharp pains.
On the 26th of the First month, 1716, he died in the Lord,
at his own house in Rhode Island, aged about ninety-one years.
A minister about forty-five years.

[.asterism]
'''

JOHN BOWSTEAD was born at Aglionby, near Carlisle, in Cumberland,
the 30th of the Second month, in the year 1659,
and was convinced of the blessed truth when young; and in a few years after,
he received a gift of the ministry, in which he improved both at home and abroad.
He labored in the gospel, and travelled from north to south,
as also into Scotland and Ireland, where he not only visited Friends,
but had meetings among other people,
and several were turned to the Lord through his ministry.
As he preached Christ in word and doctrine,
he also adorned the same in an exemplary life and conduct, plainness and gravity;
was faithful to our ancient testimony against the great oppression of tithes,
suffered the spoiling of his goods patiently,
and assisted others when they were under persecution for conscience sake,
and went with them before magistrates.

He duly attended meetings for the worship of God,
and had his children and family with him, and was a good example to them.
He was ready to do good to all,
and his heart and house were open to entertain his friends freely.

In his ministry, his doctrine was plain and powerful, and he divided the word aright,
preaching the gospel freely, and was zealous in contending for the faith.
He loved good order, promoted the same in the church,
and labored fervently for its support.
He was a universal lover of faithful Friends, an encourager of the weak,
and sought the good of his neighbors and countrymen, and was well beloved.

He was tender over such as were under exercise; he loved liberality,
and hated covetousness; was diligent in his travels to visit the churches,
and careful when at home for the support of his family.
He had much exercise with wrong spirits, against whom he bore a faithful testimony.

The time of his sickness was short; and though it lay heavily upon him,
he retained his inward and outward senses clear all along,
and settled his affairs in the world, and was in a sweet frame of mind,
and uttered such heavenly expressions, that the apothecary who attended him,
though not of our profession, declared that he had been with people of several ranks,
and never heard the like before.

Several friends visiting him, he said,
'`Oh! how easy am I in the company of clean-spirited friends;`'
with many other sensible and weighty expressions.

Perceiving the time of his departure drew nigh, he desired to see his wife,
who then lay weak of a fever, who was brought to him, and they took leave one of another;
and he said to them about him, he was for leaving them; and in a little time,
in a sweet frame of spirit, departed this life the 30th of the Second month, 1716.

He was buried in Friends`' burying-place at Scotby,
on the 2nd of the Third month following,
where many friends and others accompanied his body to the grave,
where he was decently interred.
Aged fifty-seven years.
A minister thirty-five years.

[.asterism]
'''

SARAH ELKINGTON, wife of Thomas Elkington, of Epping, in the county of Essex,
was a woman of a blameless conduct, delighting to retire often in secret,
to seek acquaintance and favor with the Lord.
That she might increase in the same, she seldom missed attending their week-day meeting,
though sometimes very small, yet kept to it constantly, and was diligent therein,
to keep her mind under a right exercise,
which she would often say required strict watchfulness.
She was often inward and retired in her mind to the Lord,
and was concerned to have truly in possession that which she professed,
as did more manifestly appear when she came towards
the conclusion of her time in this world,
which was occasioned by a cough and consumption, that attended her some time.

It increased very fast upon her in the beginning of the Eleventh month, 1717;
so that she was apprehensive her end drew near,
but said that her peace was made with the Lord,
and that through his great mercy he had enabled her so to walk,
that now she had true contentment and satisfaction,
in that she had been faithful according to her measure of grace received.
Not many days before her departure out of this world,
she said her heart was filled with praises to the Lord;
but her condition of body was such,
that she could not express the same as she should have done, had she but strength.
Speaking to her husband, she said, '`My dear, do not mourn so for me.
I am but going the common way of all flesh.
I am not afraid of death; for, seeing it is the will of the Lord,
I am thankful that my will is subjected to his.
His time is the best time; and this I can say, my peace and enjoyment are such,
that I had now rather die than live.`'

Several times, as she found herself enabled,
she gave good advice to her own and her husband`'s children,
advising them to obey their father, and remember his advice,
and to be careful to walk humbly before the Lord, and truly to fear him,
and then it would be well with them here and hereafter.

This, with much more that she at several times uttered, was spoken with such awfulness,
and in a sweet, tender frame of spirit,
that it tendered the hearts of those she spoke to; and drawing near her end,
as her children came to see her, she took her solemn leave of them,
blessing them in the name of the Lord.
Then, lying some time still and retired in her mind, she said that she felt no pain,
neither was she sick, but very easy, and also well contented,
and esteemed it a very high favor that the Lord dealt so kindly by her,
that she should be so free from pain of body, and clear from trouble of mind.
In the sense of this, and of the overflowings of the goodness of God,
she said her heart was tendered, and that tears of joy flowed from her eyes.
And further added, it was now her great comfort, that in the past time of her life,
she had, through the grace of God,
been careful to order her conduct according to the holy profession she made;
that she with trouble had observed too great a lack of that among many,
who gave themselves so great a liberty to speak at large, and unwarrantably: which,
she said, she had been careful to avoid;
and now she saw the advantage and profit of such self-denial and watchfulness.

Another time, lying in a still, retired frame of mind,
she broke forth in praises and thanksgivings to the Lord, saying, '`Oh!
Lord, you have been good to my soul:
you are the everlasting fountain of unspeakable goodness.`'
Three or four of her children being by her bedside, she said, '`Oh! dear children,
mind and dwell in the fear of the Lord, and he will manifest his goodness to you.
Mind, I desire you, the words of your dying mother,
for the Lord has been good to my soul many a time, praises be to his holy name.
O my soul praise the Lord.
He deals now kindly by me, for I am very easy.
I seem at times to doze away my life; if it goes away so it will be very easy.
Were I capable of body, I would write something to leave behind me,
of my experience concerning the dealings of the Lord with me,
and what a brave thing it is to fear and serve him, and what I now enjoy.`'

Her husband telling her that something of what she had said was taken down in writing,
which he believed would be of service when she was gone, she seemed to be pleased,
and continued very easy, often saying her eye was to the Lord;
hoping he would enable her patiently to go through
what might yet be permitted to come upon her.
She signified what a brave thing it was to trust in the Lord,
and constantly to watch against the enemy; and said,
'`I now rejoice in the goodness of the Lord, for he is with me;
and although I am now coming to hard work, for to die is not an easy thing,
yet I am easy;`' and laying her dying hands upon her breast, said,
'`I have peace and true contentment here.`'

She further added about half an hour before she departed, to those about her,
This is hard work that I am in, but I am easy; my mind is easy.
I have peace at heart, the Lord is near me, and my time now will be short.
Desiring to take her last leave of her husband, she said, '`My dear,
a little time will now accomplish my labor; farewell, dearly.`'
Then desiring to know what time of the night it was, which was told her,
she lay very still, breathing to the Lord:
and as she had prayed that she might have an easy passage, so it was granted;
for in about half an hour she breathed shorter and shorter,
and went away as if she had fallen into natural sleep.

She departed in great quietness, about the second hour in the morning,
on the 3rd day of the First month, 1717, in about the forty-fifth year of her age.

[.asterism]
'''

WILLIAM TAYLOR, son of John and Agnes Taylor, in Whitehaven,
was servant to Ebenezer Pike, of Cork, who, with many others there,
declare that he approved himself faithful; was sober and well inclined,
and in his conduct very exemplary.
His love to truth, and those that walked therein,
drew an esteem from honest friends towards him, being careful to keep meetings,
and not to miss the advantage of such opportunities, whether public or private.

He was taken ill with the small-pox, and was visited by Friends.
Some time before his departure, he said, '`Peter Tomey, I have desired your company,
and some more honest friends, that you may see my departure;
for the time seems to be short, and my poor mother will never see me more.`'
Being in a sweet and sensible frame of mind, he said,
'`I desire you to remember my dear love in the truth, to my father and mother,
sisters and brother, and to friends in Cumberland.
I am thankful my mind is kept easy and quiet, and I account it a great mercy from God,
and hope I may continue so to the end.
I desire you may be concerned in your spirit, that I may finish my journey in peace.`'

He said to Deborah Bell, '`The Lord has been good to me from my childhood to this time,
and I have loved him since I knew him,
though at times there has not been such a close walking with him as ought to have been.
But I hope if the Lord sees fit to take me away at this time, he will be merciful to me;
and if I live longer, I hope to be more careful to answer his will.
But, said he, I am as if I was under a cloud,
and cannot enjoy so much of the love of God as I gladly would,
and which we poor creatures want, when we come to such a time as this.
I do not think I shall get over it; the Lord is good to me,
and at times gives me tastes of his love.`'

The day before he died, he said, '`To my great comfort, the Lord is come,
and has filled my soul with his love; and now I am ready.`'
And afterwards signified he was going to everlasting rest,
where he should sing praises and hallelujahs forever and ever.
He also added, '`It will be a hard thing for my dear father and mother,
when they hear of my death, but tell them from me,
I desire they may bear it with patience, for I am happy, and remember my love to them.`'

He desired those present to bear witness,
that he went out of this world in a sensible condition,
and with full evidence and assurance of eternal life: saying,
'`Now the enemy is driven away, and never shall return again; he has done with me forever;
glory, glory to my God.`'
He continued in praises and thanksgivings for a considerable time,
and gave very excellent advice to several persons, for he was exceedingly full and open,
and strengthened to admiration to speak for the Lord.

About an hour after, he said to his nurse and some others,
'`Now I am going;`' and so quietly departed the 8th of the Sixth month, 1717, like a lamb.

Here follows a paper that was written by him, giving an account of his age when visited.

[.embedded-content-document.letter]
--

In the Seventh month, 1706, I being then between twelve and thirteen years of age,
the Lord was pleased to visit my soul by his divine power, which seized upon me,
and brought me to a sense of my state and condition.
I had never been addicted to any gross evil,
but had spent too much time in playing with other children,
and in light and vain discourse:
and although I had been soberly educated among friends,
and constantly frequented meetings,
yet I saw I had not lived so in the fear of God as I ought to have done.

Now I also saw in some measure the necessity of an inward work,
and that I must forsake and part with all my former vanity and pastimes.
This brought great sorrow upon me, so that I was ready to say,
this inward sorrow and exercise of soul is harder to be borne than all outward affliction.
I was in great trouble and sorrow for some time,
not so much from a sense of former guilt, but the Lord`'s power working in me,
changed my heart, and I was very sad and heavy,
and the cross of Christ seemed hard to bear.
I thought it was very hard, that I, who was so young,
should part with all youthful pastimes.
But soon after, the Lord was pleased to let me see, in some measure,
the beauty of his truth, and how he would love those that feared him;
and did so overcome my heart in a sense of his love, that I was ready to say,
I will give up my heart to the Lord; he shall have my youthful days.

Then the fear of the Lord seized upon my heart, and as I kept to it,
with my mind exercised in spiritual things, I was preserved out of my former vanity,
and became sober, and was much inclined to reading of friends`' books,
which before I did not mind,
and delighted to read those authors who had written their own experience,
concerning the Lord`'s work in them at their first convincement,
and the first breaking forth of truth, also their travels and sufferings.
In the reading of these I was much affected, and often comforted,
having a sight of the glory of that day,
and also of the Lord`'s goodness to those his faithful servants in the beginning,
and how they were preserved through all their exercises.

My business at that time being among some loose and vain people,
who did not fear the Lord, their idle talk and vain communication were very uneasy to me;
and I saw they were strangers to the work of regeneration,
and I lamented their condition; and when I awoke in the morning,
oh! the fear and dread that was upon me.

Thus for some time I was religiously exercised, but a while after,
I frequented the company of some young people, some of whom were Friends`' children,
but they were light and airy in their conduct, and much given to mirth and merriment.
I being drawn in among them, began to take delight in their company,
and many hours were spent, in the winter evenings, in idle talking and foolish jesting,
by which I was much hurt, as to my inward condition, and began to be settled in ease,
and so got from under that concern of mind which had for some time been upon me.
Yet the Lord by his light and grace in my heart often reproved me for my wantonness,
so that I was preserved from gross evils, but too much given to lightness and mirth.

But the Lord, whose love was still towards me, did not leave me in that state.
I remember one time when I was sitting in a meeting, the power of the Lord seized me,
which turned my heart towards him;
and by the shining of his light and grace in my heart at that time, I clearly saw,
that if I would be Christ`'s disciple, I must take up his cross,
and give up my heart to the Lord; have my mind taken off from the things of this world,
and stayed upon God.
And that saying of the Apostle was brought to my remembrance:
"`To be carnally minded is death, but to be spiritually minded is life and peace.`"

--

[.asterism]
'''

RICHARD HEYDON, late of Oddington, in the county of Gloucester, was an honest, plain,
sincere-hearted man; of a tender, loving, compassionate spirit;
a nourisher of good in all,
and one who bore a testimony against every appearance of evil.
Having a fervent love and zeal for truth, he labored for the prosperity of it,
and was a good example in his day, to both old and young.
He was one of whom it may be well said, he was a preacher of righteousness,
his life and conduct being agreeable to his profession;
so that the innocency and sweetness of truth appeared in him,
even in his commerce and dealing among men,
it being his care to give no offense to either Jew or Gentile, or the church of Christ.
It may be said in a good measure of him, as was said of Nathaniel,
that he was an Israelite indeed, in whom was no guile;
for he preached in life and conduct, even to those that were without,
and was a good example in so doing, to all who made a profession of the blessed truth,
among whom he also labored in word and doctrine, exhorting all to faithfulness to God,
and his truth, that so they might feel the living virtue of it in themselves,
whereby they might come to be seasoned with the salt of the covenant.

He was often under great concern of mind for his children,
and in order that they might come to witness a growth in the truth,
he was concerned to wait upon the Lord in his own family,
to seek to him in supplication for them;
and the Lord was pleased to answer the desire of his soul in a good measure,
so that he lived to see the travail of his soul, and was greatly comforted therein.

Although his gift in the ministry was not large, yet finding a concern upon his mind,
which rested upon him for some years, to visit the churches of Christ in Wales,
and a companion offering, he set forward in his journey with the unity of friends,
in which service he had great satisfaction.
It pleased the Lord, who knows what is best for his people,
to visit him with the small-pox, at our worthy friend John George`'s house,
at Landewybrevy, in Cardiganshire, in South Wales;
in which illness he was resigned to the will of the Lord,
and declared of his goodness to his soul.
Although he was in great pain, and very ill in body,
his soul was visited with the tendering power and sweet love of God,
so that he sat up in his bed, and with tears declared of the sweetness and virtue of it.
'`Oh! how sweet is the love of God; it is now sweet to my taste; it is sweeter than honey,
yes, than the honey-comb; it seasons our exercises; it sweetens the bitter cup to us,
and the divine streams of it bring comfort and refreshment to the weary soul.`'

He signified his concern that Friends might witness the Lord to be near at such a time,
saying, '`A profession of truth, without faithfulness thereto, is to little purpose.
It will bring no comfort in a time of trial,
which comes many times when we are not aware of it.`'
And again he said, '`Many are those to whom the Lord has made known his way;
and oh! that all might make straight steps in it.`'

Some friends coming to see him, he was opened in advice to them,
and in great tenderness of spirit, said, It is necessary for friends,
when they meet together, in order to worship God,
to sit down under a right exercise of mind,
and with diligence wait to feel his bowing power
to tender and bow down their spirits before him,
that so they may come to feel the virtue and weight of truth upon their spirits,
which in itself is pure and weighty.`'

And as they thus come, they will be livingly concerned for the honor thereof;
for it is too common to see some among us, yes, some that profess the truth,
with sorrow I speak it, overcome with sleep when they are in meetings,
which brings trouble and sorrow to the diligent and honest-hearted,
and they may be stumbling-blocks to other people that may drop in among us.`'

Thus this dear friend was concerned for the prosperity of truth to the last,
and his distemper increasing upon him, which proved him greatly,
yet he continued in a quiet frame of spirit, and on the 23rd of the Tenth month,
departed this life like a lamb, without either sigh or groan, and is, we doubt not,
entered into that rest that God has prepared for the righteous.

His body was accompanied by several friends, to Friends`' burying-place at Llandovery,
where he was interred the 25th of the same month, 1717, aged sixty-seven years.

[.asterism]
'''

MARGARET HOARE, the wife of Joseph Hoare, of Cork,
was dearly beloved by Friends in general,
for they came frequently to visit her in the time of her weakness;
in several of which visits they had very sweet and heavenly seasons with her,
wherein the melting power and love of God were at times richly manifested among them;
and in some of them she was sweetly drawn forth in testimony,
to the tendering many hearts, as likewise were some other Friends on the like occasions.

Some time before her departure, many Friends being in her room,
and waiting in silence upon the Lord, she was drawn forth very livingly in testimony,
by way of advice and counsel to them, as well as something relating to her service,
and testimony for the Lord.
To Friends she pressingly recommended their seeking after and loving the Lord above all;
and the enjoyment of truth, and the life of it, beyond the world, and the things of it;
and not to let their minds be taken up,
and encumbered with fading and transitory objects;
and then they would both clearly see their way,
and be ready and willing to do and answer what the
Lord might be pleased to require of them.
Adding, in great tenderness of spirit, that as to herself,
she could in great humility and reverence, as well as thankfulness, say,
that she had answered the Lord`'s requirings in her day,
by giving herself up to his service;
and that she could not charge herself with declining any journey,
or service in testimony, that the Lord required of her.
'`This,`' said she, '`is now my great comfort and satisfaction of soul,
in this the time of my weakness.`'
Much more to the same purpose she uttered at that time,
in a heavenly sweetness of spirit, which could not be remembered.

At another time, being overcome with the love of God,
she spoke in a holy admiration thereof, and of the divine excellency of God`'s salvation,
and of her feeling of it at that time: adding,
with great sweetness and fervency of spirit, '`My salvation is scaled.`'
Another time, seeing some Friends very sorrowful for her, she said to them,
'`Be not concerned for me, I pray you; there is no cause of sorrow on my account.`'
Upon several occasions she expressed her great love
and affection to her husband`'s two children,
and likewise of their affection and dutifulness to her; and not long before her death,
she spoke to her son-in-law saying that she could never
make any difference between them and her own children;
desiring him, that as his little brothers grew up,
they should live in love with one another; adding thus,
'`The Lord was pleased once to bring you very low,
and he had a good end in raising you up again; and that the Lord loved him,
and desired he might love the Lord, which she hoped he would do.`'
To her brother Pike she expressed herself after this manner, with much affection:
'`My dear brother, I have loved you very dearly in the truth,
ever since our first acquaintance,
and my soul has been nearly united to you by the Lord`'s spirit, in which our love, union,
and fellowship have stood.
We must part, but in a little time we shall meet again, never to part more.`'

At another time, seeing several friends weeping about her, she said to them,
'`Do not cry for me.
I do not die as one without hope.
I shall have no more tears; they are all wiped away.`'
Some time after, her lips moving, she was heard to speak softly to herself;
upon which her sister Pike, putting her ear near her, heard her praying to the Lord,
and praising him, saying, '`My soul does magnify the Lord, '`with more to the same purpose;
which she could not so distinctly understand,
by reason of her weakness and lowness of voice.

At several times she expressed to some friends her satisfaction in coming for Ireland,
and of her being in her right place.
She desired that her dear love might be remembered to her mother;
and the day before she died, she said to some friends about her,
'`Remember my dear love to all my dear Friends, and tell them I am going to my God,
and their God; to my King, and their King.
I have a clear conscience, void of offense towards God, and towards all men;
the Seed reigns: '`and so went on magnifying the Lord.
The same day she was taken with a violent fit of coughing, so that her-,self,
and the Friends about her, thought she was going off; but recovering again, she said,
with a holy concern of mind, '`And must I stay longer?
I thought I was sweetly passing away.`'

Her brother Pike coming to see her, she said to him, '`Dear brother, I am glad to see you,
but should have been more glad to have been gone.
I thought I was sweetly passing away.
Oh! sweetly, sweetly, I thought I was going.`'
Growing weaker and weaker, her strength and speech began to fail,
yet she spoke softly to herself; which some friends about her observing,
and listening to hear, perceived by what she uttered, as if she saw a vision,
and had a sight of a glorious city which she saw; for she was heard to say,
'`An excellent city, paved +++[+++as they understood she meant]
with gold;`' adding, '`It will be mine forever.`'
And thus by degrees her strength and speech failing, she died in the Lord,
the 24th day of the First month, 1718, being greatly lamented by others,
as well as Friends in general.

The foregoing instances are but a few,
in comparison of the many sweet and heavenly expressions
which she uttered in the time of her weakness,
which yet were thought fit to be kept as a memorial of her for time to come.

[.asterism]
'''

JONATHAN TYLER, son of Charles Tyler, of Calne, in the county of Wilts,
was convinced of the blessed truth about the 21st or 22nd year of his age;
and after some months it pleased God to open his mouth,
and give him a large gift in the ministry, in which he was a faithful laborer,
and divided the word aright; and the divine presence of God attended him in his ministry,
to the making glad and refreshment of many.

He travelled through most parts of England to visit Friends,
and also Scotland and Ireland; and in America, as Pennsylvania, New York, New England,
East and West Jersey, Maryland, Virginia, and Carolina.
In all these places he took abundance of pains,
and travelled for the space of three years in those American countries.
He was a noble instrument in the hand of God,
and had great service for God and his truth in those places;
and many were turned from darkness to light,
and from Satan`'s power to the power of the Lord God,
by his living and powerful ministry.

He was a loving and affectionate husband, and a tender father,
both to his own children and to the church of Christ.
He was a good and peaceable neighbor, and of a sweet and pleasant temper.

After he came from America he married and settled at Bradford,
in the county above mentioned, and was very serviceable, in those parts,
to the churches of Christ, and for his loss many have been sad,
yet there still remain seals of his living ministry.

After long struggles with his distemper, the gout, which settled in his stomach,
he was confined to his bed; and on the 22nd of the Tenth month, 1717,
on the First-day of the week, his wife and children,
with several other relations being about him in the evening, after meeting,
he seemed somewhat refreshed and comforted thereby; and raising himself on his bed,
in a living frame of mind, expressed himself to them as follows:
'`If the Lord please he can restore me.
So long as there is life there is hope; but when death is come,
then there is no more hope.
The Lord God can, if he please, work miracles upon me, and preserve my life, which,
if he do, it must be for some good and glorious purpose.
He is a good God to me;`' and said, '`O you good and sweet God.
Who can forget so good a God`'

He was proceeding further,
but was interrupted by the coming in of several friends to visit him;
and being taken out of his bed, a little to refresh him,
and understanding it was First-day, after some inwardness, he said, Oh!
I have lost two feast-days.
These and Fourth-days used to be my feast-days,
and if I could have but one good meeting more,
that would do;`' intimating that then he should be entirely satisfied.
Then remaining silent he proceeded, '`By this I know that I am passed from death to life,
because I love the brethren.`'
He also cited the text to the same purpose, repeating several times,
that God was good to him; and with great admiration and emphasis, said several times, '`O,
dear God! you are glorious, and livest forever and ever.`'

Being put into his bed again, a friend asked him if he knew him; he replied, '`Yes,
'`naming lis name: then the friend asked him how he did; he replied, '`Very ordinary.
I hardly know any thing now, only this I do know, that I am yet alive upon the earth,
and that is a mercy; and I know that God is good to me, and that is a great mercy.`'
About the middle of the night, being worse than ordinary,
the family was called about him, but somewhat recovering, he was heard to say,
'`To know you, the only true God, and Jesus Christ, whom you have sent,
is life eternal;`' several times expressing his sense of God`'s great goodness to him,
and was often in great inward melody, and sometimes audibly sang praises to God.

The next day, being the 23rd, notwithstanding his pains were very pungent,
he remained patient, and generally sensible, and a sister-in-law coming to him,
expressed her trouble to find him so weak.
He told her, '`It is better to come to the house of mourning,
than to the house of mirth;`' and his near friends weeping about him, he said,
'`Oh! why do you trouble me; it is a brave thing to be quiet.`'
Being under a painful operation of his physician, he told us,
that he should live his appointed time, and no longer.`'
The Lord has been the keeper of my soul and body, to this time;
and he will keep me forever.`'
He remained till after the middle of the night in a sleeping condition,
his distemper lying pretty much in his head, when awaking, he very livingly uttered,
'`O death I where is your sting?
O grave, where is your victory?
Lord Jesus come quickly.`'
Then his son-in-law asking him how he did; he answered, '`I am going into another world.`'
He called his brother Joseph, and said, '`The Lord is good to m;`' and pausing a little,
repeated, '`death! where is your sting?
grave, where is your victory?`'
also signifying he was not afraid of death, nor of what came after.

About three or four in the morning, he called his wife and told her,
that after some exercise of mind, he could now tell her,
that he knew that he had a being yet in this world,
and that God would give him a being hereafter.
This was occasioned, as was apprehended, by a struggle with his distemper,
affecting his head, which had for some little time before hindered his utterance,
because that now he said, he was fully satisfied.
His wife asked him, if he had any thing to say to his children; he answered,
'`They will have a great loss of a tender father.`'

Great part of the next day, the 24th, his spirits and strength so failed,
that he said but little,
unless it was now and then when he seemed to have
some short intervals of ease from his pain.
He would thank the Lord, and speak of his goodness to him.
His resignedness and patience were remarkable,
for notwithstanding the greatness of his pains, yet he was never observed to repine,
or utter any irreverent expressions, but in his greatest extremity, would praise God,
and acknowledge his goodness to him;
and when his speech so failed that he could not speak intelligibly to those about him,
yet he would clearly and distinctly call on the Lord to the last

He deceased in great quietness, without sigh or groan,
about the eighth hour in the evening, on the 24th of the Tenth month, 1717,
aged about forty-eight years.

[.asterism]
'''

JOHN SKELTON, late of London, received the blessed truth in the love of it,
by which in time he was sanctified, and the Lord, through the work of his Holy Spirit,
prepared him for, and called him into, the ministry of the gospel of Christ.
Therein, through the grace of God, he was enabled,
according to the measure of the gift bestowed upon him, to be a faithful laborer;
his conduct being agreeable to the truth he preached,
and his love to God and the brethren unfeigned,
and through diligence he improved in the talent received.

In the year 1716,
he was drawn forth in the love of God to visit Friends
in many counties of England and Wales,
and the Lord`'s living presence was with him, to the joy of his soul, as he declared.

He travelled, in two years, 1665 miles; and after his return, for several months,
he visited the meetings of Friends in London and the adjacent parts.
When he was taken ill he had a complication of distempers, i.e. a cough,
shortness of breath, and dropsy.
He was in a heavenly frame, and resigned to the will of God, whether to live or die; '`for,`'
said he, '`I witness peace with God, through Jesus Christ,
in whom alone I trust for eternal life and salvation.`'
Great tenderness of spirit appeared in him,
and several other sweet and comfortable expressions at sundry times dropped from him.
At one time he said, '`The Lord is abundantly good to my soul;
he has fitted and prepared me for himself.`'
At another time he said, '`The Lord`'s will be done;
for I will wait all the days of my appointed time, till my change come.`'

He oftentimes made humble and grateful mention of the goodness of God,
and love of Christ to his soul, and broke forth into praises to his excellent name.
The morning before he departed,
being asked whether he had any thing more to say to his wife and daughter, he answered,
'`I have no more to say to them.`'
A friend a little after said, '`Dear John,
I perceive you are not far from your journey`'s end;
it will not be long before you will be at your heavenly Father`'s house,
where are many mansions of bliss and glory.`'
He very sensibly answered, '`I hope so;`' and soon after,
he quietly departed in peace with the Lord,
and is entered into that blessed and everlasting
rest that is promised to the people of God.

His body was interred on the 10th of the First month, 1718,
at Friends`' burying-ground near Bunhill-fields,
being accompanied from the Peel meetinghouse by many friends and others.
Aged sixty-three years.

[.asterism]
'''

ANNE DIXON, daughter of Christopher and Elizabeth Dixon, of Streatham,
in the county of Durham, was from a child religiously inclined,
and tenderly affectionate to those who kept their places in the truth,
being much delighted in reading good books, and was of a very sober life and conduct,
gaining a good report, and well-beloved of all;
watchful that she might not offend the Lord, by being an evil example to others.
Falling sick of the small-pox, upon the 7th day of the Second month, 1718,
she continued in great weakness of body the space of six days,
during which time these expressions following, among others, were observed.

She being under great affliction, said, '`One had need be near the Lord;
for we know not how soon we may be taken away.
I hope the Lord will be merciful to me, not through my good works,
but by his favor and great lovingkindness.
It is well I lived so near the Lord, it stands upon us so to do,
and if the Lord should spare me any longer I hope I should live nearer to him than ever.
Saying, '`O God remember me.`'
She said to her father, '`Dear father,
have a care that you do nothing that may offend God;
and if you have done any thing that has offended him, let the time past be sufficient.
She also desired some present to tell her brother Joseph Dixon,
'`To live well for the time to come;`' and she bade her younger brother be a good lad,
and the Lord will be kind to you;`' exhorting a cousin then present, not to mind pride,
and finery, but the fear of the Lord.

Being in some agony of spirit, she said, '`Oh! that I had a full assurance of my entrance.`'
Desiring all present to withdraw, her mother only excepted,
and turning her face to the wall, her lips were perceived to move,
and in a little time she broke forth into praises, saying,
I have now received full assurance from the Lord.
Now I can return him praises.
Oh! glory to my God;`' repeating it over again: '`saying further, '`The Lord was near,
and I knew it not;`' praising the Lord then in a harmonious manner.
Another time she said, '`If I go now, I hope I shall be no dishonor to the truth,
for I have nothing but love and good will to all.
I have wronged nobody, neither done an ill thing that I know of, in all my life.
I doubt people will praise me when I am gone, but all the praise is due to the Lord.`'
At another time being very weak, she said, '`Though my afflictions are very great,
yet I am borne up over them all.
It is a brave thing to be prepared for a dying-bed.
Lord, hasten your work.`'
Several times expressing her willingness to die; and in true love and charity with all,
departed this life in peace with the Lord, upon the 12th, and was buried at Raby,
the 15th day of the Second month, 1718, aged twenty-six years and about three months.

[.asterism]
'''

JOHN CRUDSON, of Kendal, Westmoreland,
at one time speaking of the exercises of the Lord`'s people, said,
the Lord was still with them so long as they kept faithful to him;
mentioning in particular, the wonderful deliverances of God to the children of Israel,
while they stood faithful to him.
He also spoke of the great exercise of the three
children that were cast into the fiery furnace,
and their wonderful preservation therein, with what became of the men that cast them in:
as also of the trial of Daniel being cast into the lion`'s den,
and standing faithful to God, he was preserved through all.
Under the consideration thereof, he advised all to be true and faithful to the Lord,
that they may witness preservation in, and through, all their exercises.

At another time speaking of being removed hence, he said, he desired,
whether he lived or died, it might be to the glory of God;
and that if it pleased the Lord to remove him at this time,
he would be a husband to the widow, and a father to the fatherless children;
and that he would be pleased to enable him to leave a testimony for him,
to them that were left behind; expressing at that time his great satisfaction,
that he felt salvation near to him.
He was often concerned to advise those present,
to be very careful how they spent their time while in health,
for he found there was enough to do when we come upon a sick-bed,
and that many did not rightly consider how swiftly time slipped away,
which seemed to show they did not walk in an exercising path.
He also earnestly desired, that the Lord would be pleased to carry on,
and prosper that great work he had begun;
and that he would be with Friends in their several meetings for discipline,
especially in this place.

Another time, being in a heavenly frame.
of mind, he prayed fervently to the Lord, to the tendering the hearts of friends present,
saying, '`O Lord you know my weakness and inability of body, and that I am as a worm,
and no man, and scarcely am able, at many times, to think a good thought,
the enemy is so busy, now in the time of my great weakness.
Yet, most holy Lord, I am humbly thankful to you,
for that you have been graciously pleased, to my great satisfaction,
to promise that you will make war, and fight all my battles for me.
O Lord! your love, and the enjoyment of your presence,
are more to me than all the enjoyments of this fading world; yes,
far beyond all cordials.
I humbly crave it of you, if it be your will, to favor me therewith more and more,
in this time of great weakness, even to the end.
O, most holy Lord!
I am truly thankful to you, for your many favors and blessings to my family,
both spiritual and temporal; and if it be your good pleasure to separate us,
I beg of you, that you will receive whom you are pleased to remove,
and stay with them that are left behind.`'

And Lord,
you know I have many times been earnestly concerned in my spirit for a young generation:
grant that my children may come up to serve you in your fear;
and although I have educated them according to the best of my understanding and persuasion,
yet Lord I beg of you, let them know your work in their own hearts for themselves,
lest a libertine spirit should at any time prevail.`'
Then returning praises to the Lord, who over all is worthy,
he concluded sweetly at that time.

Another time several friends being present, he said, '`Dear friends,
I feel something upon my mind, to say to you, which is,
the Lord is wonderfully good to his chosen and redeemed people;
and although I have been very poor, inwardly poor of late,
yet may say as I have waited upon, and sought the Lord,
he has been pleased to open to me the spring of life and truth again,
to the comforting of my poor soul.
And though my exercise of body is, and has been, very great,
so that I never had the like in all my time, never so near death as I seem to be,
yet I feel the supporting hand of the Lord underneath:
and notwithstanding I have as comfortable enjoyments in this world as most of men,
yet the enjoyment of truth is above all.`'

'`Dear friends, labor in your meetings, and in your families,
to witness the work of truth for yourselves, to help over the dark, dull, heavy spirit,
that clouds Friends in their meetings.
There is great need of it for both old and young.
There is also the earth, and the clods of the earth,
that very much hurt the minds of friends,
but as friends abide near the truth in themselves, when they come to die,
they will not lack a crown.`'
This, with several other things relating to his journey to and from London,
was to the tendering and satisfaction of friends; and so he concluded with
'`Praises, high praises, to the Lord God, and the Lamb,
who over all is worthy, now and forever. Amen.`'

He departed this life the 25th of the Fourth month, 1718,
in the forty-third year of his age,
and was buried in Friends`' burying-ground in Stramangate, in Kendal, Westmoreland.
