== Chapter 5

[.chapter-synopsis]
* Thomas Williamson
* John Close
* William Greenup
* Richard Ransome
* John Dickinson
* Ruth Willan
* Richard Hingston
* Alexander Clarke
* Christopher Pearson
* Stephen Manning
* Joan Sley
* Mary Dickinson

THOMAS WILLIAMSON, late of Bannerig, in Applethwait, in the parish of Windmoor,
and county of Westmoreland, was born at Common, in the said parish,
about the latter end of the Fourth month, 1633, of honest parents and of good report,
and educated according to the manner of the Church of England.

He was naturally of a cheerful and free disposition,
inclining in his youth to the vanities and pastimes,
in which too many spend their precious time,
though at that time he was very circumspect in observing
those outward performances he esteemed religious duties.
But in the year 1670 it pleased the Lord to visit him with some affliction of body,
and to open his understanding to see the emptiness of all his former formal profession,
and the vanities of his past life; and sorrow and distress took hold upon him for it,
and cries and breathings were raised in him to the Lord, that he would show him his way,
and he would walk in it.
It pleased the Lord to answer his desire, and to convince him of the blessed truth,
which he received with joy and gladness,
before he had been at any meeting of the people called Quakers;
and he gave up thereto according to his understanding.

About the latter end of the year 1673,
his mouth was opened in a public testimony to declare the goodness of the Lord to him,
and to encourage all to faithfulness, in which he was a good example,
and a considerable sufferer for his testimony,
both by imprisonment and spoiling of goods.

In the year 1678, he was imprisoned three months for preaching truth in a steeple-house,
and most of his goods were taken from him by some justices, on the Conventicle Act.
He was not only fined for himself;
but ten pounds laid on him for being present at a meeting held at Bownass,
the 15th of the Seventh month, 1678.

His testimony he delivered in much plainness and simplicity.
He was tender to the good in all, though sharp in rebuking that which was evil.
He was a man who feared God, sincerely loved truth, and hated hypocrisy and deceit;
sound in judgment, of a good conduct; just and honest towards all men;
bold and valiant for truth upon earth; undaunted in suffering,
rejoicing that the Lord had counted him worthy to suffer for his name`'s sake.
He was zealous in his testimony against the payment of tithes,
and those called church rates, for which he was a constant sufferer;
and an encourager of others also to faithfulness therein;
diligent in reading the Holy Scriptures, and in attending of meetings,
as well those for good order in the church, as those for the worship of God,
until by age and infirmity of body he was deprived of that privilege.
He often said, "`The worship of God, and the good of the church,
ought to be preferred before our business.`"

He truly confided in the Lord, and gave this testimony on his dying-bed,
that God had dealt bountifully with his soul, and had given him all he had need of,
and that he had peace with the Lord, and his soul was returning into rest;
with more words not noted.

He died the 22nd of the Tenth month, 1715, and was buried at Kendal,
the 25th of the same, aged about eighty-two, and a minister about forty years.

[.asterism]
'''

JOHN CLOSE was convinced of the blessed truth about the year 1705,
and was very diligent in frequenting meetings,
though it was through much difficulty at times,
by reason of his father`'s unwillingness and aversion thereto.
Nevertheless, having a due regard to truth, he was preserved so blameless in conduct,
that he not only gained upon his father to leave him to his liberty,
but was likewise instrumental towards convincing his brother and two sisters.

After some time he received a gift of the ministry of our Lord Jesus Christ,
in which he labored faithfully and fervently, being sound in doctrine.

He travelled much in truth`'s service,
visiting the southern parts of England several times, as well as counties nearer home,
and in Scotland, Holland, and Wales,
being zealously concerned for the prosperity of truth and the promotion thereof.
He was an encourager of the good in all,
and careful to suppress every appearance of evil;
very diligent in visiting the afflicted.
His care over the church was great, his advice seasonable, his judgment sound;
he was chiefly concerned for the honor of truth,
and that Friends therein might live in unity, and be at peace one with another.

In the beginning of the Eleventh month, 1715,
having drawings upon his spirit to visit Friends in Cumberland,
he went with the unity of the brethren, and visited several meetings in that county.
On the 15th of the same he was at Wigton, where he began to be ill.
The next day he travelled to Holme meeting, where, notwithstanding his illness,
he bore a faithful testimony, to the great satisfaction of Friends.

That evening he came to a meeting at Allonby; but his sickness increasing,
he sat but a little time in the meeting,
and signified in a few words he felt the goodness of the Lord upon his spirit,
and his gladness thereof;
and advised Friends to be faithful and steadfast in their love to God,
and to do whatever they could for the Lord in their day and time, adding,
he believed some in that place had not long to live in this world.

He took his leave of the meeting and went into his chamber,
where he continued the most part of two weeks; but by reason of his distemper,
(the small-pox,) lying heavy upon him, he could not speak much without great uneasiness,
yet he bore it with great patience.
While his speech continued, some friends sitting by him, he said,
"`We had need to be prepared for our change; when sickness comes,
we have enough to grapple with, and not to have our peace with the Lord to make then.`"

He was several times exercised in prayer to the Lord, and at one time to this effect:
"`Lord, you who have been with me in the deeps, leave me not to the end.`"
The day before he died, being asked how he had rested, he said,
"`I think I know when my rest will be; tomorrow morning,
some time after the day be light;`" at which time he died,
being the 27th of the Eleventh month, and sixth day of the week.
He was buried the 29th, in Friends`' burying ground at Allonby, in Cumberland,
and his corpse accompanied by many Friends and others.
And it is assuredly believed that he is entered into the rest prepared for the righteous.
Aged about thirty-five, and a minister nine years.

[.asterism]
'''

WILLIAM GREENUP, late of Flatts, in Cumberland,
was a worthy and faithful servant of the Lord, whose name remains among the living,
and his service and footsteps may be exemplary to those that succeed him, to follow.

He was of great value and esteem, being an elder worthy of double honor,
the Lord having committed to him a gift of the ministry,
and his testimony was living and powerful.
He was fervent in prayer, and his doctrine sound,
delivered in the power and demonstration of the spirit,
and to the edification and comfort of all the true and faithful among whom he ministered.
He was greatly helpful to the meeting to which he did belong,
in managing the affairs of truth, being zealously concerned for the keeping up,
maintaining and promoting good order in the church,
and often advised Friends to faithfulness,
and to keep up their testimony against undue liberty.

He labored to preserve love and unity among brethren,
and travelled for the promotion of truth in many parts of this nation,
as also in Ireland, Scotland, and Wales.
His labor and travail were, both in body and spirit,
to bring men to the knowledge of the truth, and to be acquainted with the Lord,
and to know their peace made with him.
Several were convinced by his testimony, and not only so,
but became fellow-laborers with him in the ministry.

He was very careful and tender over those who were young in the experience of truth,
and where he saw good inclinations to grow,
would often encourage them to their great help and comfort,
as several have good cause to remember.
So that the loss of him is great, though his being taken away is his gain,
being one that truly loved and feared the Lord, and was freely devoted to serve truth,
and his heart and house were free and open to entertain friends.
It pleased the Lord to incline his heart first to
seek the kingdom of God and the righteousness thereof,
in his young years, and as he gave up in obedience to the Lord,
he increased his faith and knowledge; so that he was made able not only to believe,
but to suffer for his name.
And that which crowned his labors was, that he kept steadfast and faithful to the end.

He was sorely afflicted with a pain in his head for some months.
Then it pleased the Lord to visit him with a sharp sickness for about three days,
which he endured with much patience, as was observed by those who went to visit him,
to whom he expressed his being freely resigned to the Lord`'s will,
whether to live or die.

This good man departed this life the 4th of the First month, 1716,
and was buried in Friends`' burying-ground near his own house, at Flatts, in Cumberland.
Aged seventy-five years.

[.asterism]
'''

RICHARD RANSOME, miller, late of North Walsham, near Norwich, in the county of Norfolk,
was convinced of the holy truth about the year 1676, and to him,
through the Lord`'s mercy,
it was given not only to believe in God and in Jesus Christ his Son,
but also to suffer long and hard imprisonment for his name`'s sake nearly fifteen years.
He was faithful and zealous for the Lord, and the Lord was pleased to qualify, call,
and send him forth freely to preach the gospel of peace and of the grace of God,
and he attended him with his presence and power,
and blessed his labors of love for the good of souls.
He travelled much in England, Wales, Scotland, and Ireland.

In his travels in Gloucestershire, he was taken ill, and at Bristol, in the Ninth month,
1716, he took his bed, being visited with the small-pox; which, when he perceived,
he said that as the Lord had carried him through the nation to this time,
and now laid this distemper on him, he thought it was for his end.
So he made his will, and desired a letter might be written to his wife and children.
Considering the great distance they were from him,
he had no desire of their coming to him;
but desired his near and dear love might be remembered to them,
with fervent desires to the Lord for their preservation in the truth,
that they might be kept in true faithfulness and obedience to his requirings,
and that in this their exercise they might keep in
true patience and obedience to the Lord,
who would keep and provide for them to the end of their days, as he had done hitherto.

He said to Friends at Bristol he was glad to see them, "`and that which makes me,`"
said he, "`more glad, is to find truth alive among you.
Keep to truth, the pure truth, the unspotted truth,
and that will keep you a clean people to God; keep to truth, and that will be over all:`"
and he prayed that the Lord would be with his young ones, whom he was bringing up.

Another time he said to Friends,
"`Poor things! do stand faithful for God and his truth.
Be valiant for the truth, and it will be a comfort to you.
As it is given way to, it will come up into dominion and be over all.
I know what I say.
I have felt the comfort of it many a time, and do now to this very day.`"
Then he spoke of the meeting he had been at, at Thornbury, saying, "`I got comfort there;
Friends were near to my life.`"
Also said, "`I am glad to see the Lord is at work.
He is bringing forth a people that shall stand faithful to him.`"
After a time he kneeled down and prayed fervently for them.

On the second of the Ninth month he took his bed, and several friends came to see him,
to whom he said, "`Friends, the Lord has given me an understanding,
and has let me see many years ago, but more especially of late,
why he afflicted his little ones.
It is in order to drive them nearer home to himself;
for the Lord is about to try his people.
But, dear friends, be not discouraged; for though you may go through the fire,
and through the water, the Lord`'s arm is underneath.
My soul is a living witness of it, and I speak it for your encouragement,
for Jesus carries his lambs in his arms, and leads his along into the low valleys,
in green pastures of life, and to lie down as at noon-day,
where none shall make them afraid.
The Lord is faithful to all those that trust in him.
Therefore be faithful and not wavering;
for those that waver are like the waves of the sea.
There is a day coming, and will come, that shall try the foundations of all,
young and old; and those that are not established on the rock shall be blown away:
but the Lord is raising up some that shall stand as iron pillars for his truth,
and shall not value their lives unto the death.`"

Another time he said, "`Friends, I desire you not to look at any instrument,
but let your trust be in the God of Israel, who shall keep and preserve you,
as he has my soul.`"
Then he prayed that the Lord would bless Friends in their meetings and in their families,
and to comfort his afflicted wife and children, whom he had left behind,
and that the Lord would bless and preserve his little ones in this city.

Again, after a little silence, "`I have another word rises in my heart to speak to you all,
and it is this: endeavor to delight in silence.
Worship the Lord in the silence of all flesh.
Retire in your own families from the clutter and hurries of business of the world,
and wait upon the Lord in stillness; for the Lord will have a willing people.`"

A friend expressed his concern that he should be so suddenly taken,
and with such a dangerous distemper, he replied, in a very comfortable manner,
"`I am well satisfied and content with the will of the Lord therein;`"
and further signified that he found nothing troubled him,
and he was clear, and easy, and willing to die;
and bid the friend give his dear love to Friends at Bath.
And in a solemn and sweet frame, said, "`Farewell; if I never see you more,
be sure to keep to truth, and that will keep you, and do not part with, or lose,
your sense of that for any thing whatsoever.`"

Another time, not long before he died, he said to Friends about him,
"`I am glad to see you, and it is a comfort to me this day;
and I am well pleased that I was brought here to die with you,
and that I shall lay my bones with you at Bristol.
I desire you (that is,
Susannah Thurston and Susannah Parker of Thornbury) that you would be at my burial;
it is the last office of love you can show me,
and send for John Hodges and Henry Sanger.`"

To some Friends who were going to meeting, he said,
(this was not long before he died)"`The Lord be with you, the Lord be with you.
I hope you will have a good meeting.`"

Another time he said,
"`I have made it my care to be obedient to what the Lord has required of me,
and in that I find peace and satisfaction.
Peace on a dying bed is more than all, and I bless God,
I can say in truth without boasting, I feel his peace.
I am easy and freely resigned in his will, and have nothing to do but to die;
for I have faithfully discharged myself of what the Lord required of me,
and am going to receive the reward of my doings.`"

Friends taking their leave of him, he said, in a weighty frame of mind, "`Farewell,
farewell, farewell in the Lord Jesus; for in him alone is it we can fare well.`"

About half an hour before he died, he was raised up in his bed, and said to friends,
"`What need have we to center down in the night season, to feel blessed Jesus,
sweet Jesus, heavenly Jesus to commune with us;
for when he comes he puts an end to all rovings and hurries which are in the world,
with many trials, tribulations and afflictions, which rise not out of the dust.
But dear friends, Israel`'s God will not leave his afflicted ones,
for he will prosper his work which he has begun,
and you shall see it as you are faithful;
and here you shall be made witnesses that one hour in the
presence of the Lord is better than a thousand elsewhere.
For in the world are trouble, strife, animosities and contentions, as you may see;
but all this will come to an end, as we keep in the patience and stillness of Jesus;
for that will conduct us safely to our desired rest, where all sorrows will cease,
and tears be wiped away; and that you may be preserved in true faithfulness,
is the desire of my soul.`"

In about half an hour after, he departed in peace, the 8th day of the Ninth month,
about midnight, 1716.
He was buried the 10th of the same month, in Friends`' burying ground in Bristol.

[.asterism]
'''

JOHN DICKINSON, late of Berkhouse, in Grayrig, in the county of Westmoreland,
a few hours before his departure, some friends being there, said,
"`I have taken an inspection into the course of my life,
since the time of my convincement, and I have no ill thing to accuse myself with;
for the fear of the Lord was before my eyes, by which I was preserved.
Only,`" said he, "`when I was set at liberty from my imprisonment,
I thought myself too eager for the getting of this world together;
yet I have not to charge myself with oppressing any man; but what I have,
I obtained honestly.`"
Then he said,
"`I have great peace in that I have been faithful
in bearing my testimony against the payment of tithes;
for I could never either pay, or permit any to pay for me,
hating in my heart such hypocrisy.`"
And to friends by him, he said, "`Give up freely to come to week-day meetings,
to wait upon God, to feel him to renew your strength; for when I had work and business,
I could not be easy to stay from a week-day meeting.
I felt the movings of truth to draw me, and set me at liberty from my outward employ;
not only for my own growth, but that I might be exemplary to others.`"

[.embedded-content-document.testimony]
--

[.blurb]
=== The quarterly-meeting at Kendal gave the following testimony, the 17th of the Second month, 1712, concerning John Dickinson:

He was one whom the Lord was pleased to visit in his young and tender years.
In the time of his apprenticeship he was convinced of the blessed truth,
and afterward suffered great cruelty from his master for using the single language.
And though his said master beat him often, to the loss of much blood,
yet he bore it patiently,
and did not shrink in his testimony which God had given him to bear;
upon which occasion he expressed to several the great
peace and comfort he had from God to his soul.

Some time after his apprenticeship,
it pleased the Lord to open his mouth in a powerful and living testimony,
which was to the great comfort of Friends,
and the edification of the churches of Christ where his travels were;
which were mostly in several of the northern counties, and in Scotland;
and many were convinced by him.

He was valiant for the truth upon earth, and did not turn his back in the day of battle;
but suffered joyfully the spoiling of his goods, imprisonments, and other hardships,
counting the reproaches of Christ great riches; it being given him not only to believe,
but to suffer for his name.

He was a man well beloved of his brethren,
and always had a tender regard for the preservation of unity in the spirit of truth;
a man very careful in answering his word and promise to men; just in his dealing,
often advising Friends to be true to God,
and then they would be just in their dealing with men:
so that we have good ground to believe that his latter end was happy,
and that he finished his course in peace with the Lord.

Thus far we found ourselves obliged in duty to revive the memory of our deceased friend,
that those of succeeding generations may know how our ancients
came to receive the truth in this latter age of the world,
after a tedious and long night of apostasy;
that those who succeed may walk worthy of the privileges they now enjoy,
who are entered into the labors of the ancients, and reap the fruits thereof.

[.signed-section-context-close]
Signed at our Quarterly-Meeting at Kendal, the 17th of the Second month, 1712, by

[.signed-section-signature]
Samuel Parrat, Joseph Peasonn William Williamson, John Towanson, Nicholas Booke,
Richard Skyring, John Skyring, Robert Thompson, John Jopson, Joseph Atkinson.

--

[.asterism]
'''

RUTH WILLAN, wife of Thomas Willan, of Sedbergh, in the county of York,
and daughter of Thomas Robertson, of Grayrig, in the county of Westmoreland,
was educated in the way of truth, as professed by the people called Quakers,
and was of an innocent life and good conduct, well beloved of her friends and neighbors,
and lived in great unity.
She was long troubled with an asthma, or shortness of breath,
which she bore with great patience.

In the time of weakness, towards her latter end,
she admonished her children to take the advice of good Friends,
and be subject to their father, and to keep to plainness in their apparel,
and not covet after high matters; for she never did; and that the Lord had blessed her,
and had been good to her every way.
She was resigned and willing to leave this world, as she signified several times.
She also said at another time, when her husband, children,
and several friends were present, who came to visit her,
"`The Lord has blessed us both inwardly and outwardly,
and I dearly love my husband and children;`" who were crying about her bed; and she said,
"`My mind is taken off from all visible enjoyments.`"
She blessed God upon her sick bed, saying,
"`I bless God`'s holy name for the many sweet and comfortable
seasons I have had upon my sick bed.`"

She was never heard to murmur in all the time of her weakness,
but lay in a sweet and quiet frame of spirit.
She was visited by many friends and neighbors, to whom she said,
"`I am not able to express the goodness of God I have felt to my soul:`" saying also,
"`I am glad I have been charitable to the poor,
and that I have done good in my day and time.
I have the comfort of it now, and great satisfaction therein.`"

She was a charitable woman to the poor,
and took great delight to serve and entertain her friends.
A little before her departure, she told her husband she had a sweet dream or vision,
and a sight of a glorious place she was going to;
and that she should have an easy passage out of this world;
and asked him if he thought she might continue another night.
"`But,`" said she, "`I am willing to wait the Lord`'s time, though I had rather be dissolved,
and be with Christ.`"
Her husband said he hoped she might.

She was sensible to the last, and in the evening she departed this life very quietly,
like one falling into a sweet sleep, and is at rest with the Lord forever.
She was aged forty-five years and six days.

[.asterism]
'''

RICHARD HINGSTON, a ministering Friend, of the town of Plymouth, in the county of Devon,
being on a journey to visit Friends in Cornwall,
was taken sick with a fever the 4th of the First month, at the house of Thomas Giddy,
of the parish of Kea, being about forty miles short of his home.

In all the time of his sickness he was endued with patience, and many times declared,
"`I am content in the will of God, either to live or to die.
To live a little longer for my family`'s sake, I could desire;
but if the Lord be pleased that I must lay down my head here, I am content.
I shall lay down my head in peace with God, and in love with all men,`"
adding several times, and upon several occasions,
"`I have made it my business from my youth, to make my peace with God,`" etc.

On the 8th day of the aforesaid month, his mournful wife came to see him, and he,
lifting up his hands and eyes, said,
"`I am thankful to God that it is our lot to see each other again.
We came together in joy and in love, and so let us part.
I desire you and our children may live in the fear of God, and in humility,
and you will never lack.`"
His wife asked him whether he had anything upon his mind concerning his outward affairs;
he answered her,
"`Trouble me not about the world;`" saying he had in the time
of his health declared to her how things should be.

Several friends asked him from time to time how he did; his answer was,
"`I am full of pain, and in hard labor: but I bless God,
it is well with me as to my inward condition.`"
He declared how well it is to make preparation for death in the time of health;
and how unfit poor mortals are for such a work in the time of sickness;
with pretty much more to this effect not noted down.

On the 10th of the said month he quietly departed this life,
and his body was decently buried in Friends`' burying place, in the parish of Kea,
the 12th of the Eleventh month,
and accompanied by many friends and others from several parts,
where testimony was given relating to eternal life,
to the great satisfaction of the concourse of people.

[.asterism]
'''

ALEXANDER CLARKE was by occupation a shepherd, whom the Lord visited in his youth,
when given to pleasure and worldly delights,
and begat in him a true hunger and thirst after the knowledge of God and his truth.
He was drawn from the public ways of worship of many that professed God and Christ,
and from following those that said, "`Lo, here is Christ`" and "`Lo,
there!`" seeing by the light of Christ in his heart,
that their lives and conduct were not agreeable to their profession;
and he became earnest in his desires,
to join with those whose lives and conduct were agreeable to that holy profession,
of which Christ was the high priest and Apostle.
And observing the lives and conduct of the people called Quakers to be agreeable thereto,
he inclined to hear them, and to be joined to them;
but was cautioned by those professors who knew him, to beware of the Quakers,
telling him they were an erroneous and pernicious people,
so that he became an earnest contender against them.
Some time after this he went to hear them at Geddinton in the county of Northampton,
and after at Wellingborough, where that zealous minister and servant of Christ,
William Dewsberry, preached the gospel powerfully;
so that Alexander Clarke was convinced,
and became a frequent attender of friends`' meetings,
received the truth in the love of it, and waited upon the Lord in silence,
and came to know the spirit and power of God to work in and upon him;
and he became a faithful follower of him.

And when the Lord had fitted him for his work,
and committed to him a dispensation of the gospel of peace,
the word of the Lord came to him as he was following his flock in the field,
and said to him, "`Be faithful, and you shall prophesy:`" and indeed he did,
and freely preached the gospel of Christ.
Though he knew not letters, he was well acquainted with the word of life,
and he often reached to the hearers, and stirred up friends to feel life,
and was instrumental to bring them to the feeling thereof, as they witnessed:
to whom he would often appeal or say, "`You are my witnesses in the Lord,
that I am his servant to serve you in love, and that I preach not myself,
but Christ the Lord.`"

He labored in his Master`'s harvest nearly forty years;
and a little before he died he gave friends who came
to visit him much good counsel and Christian advice,
which is not inserted, because not taken down in writing,
and told them he had finished his course;
and charged his family to love God and each other, and not to forget the Lord, saying,
"`Grace teaches us all;`" which was the last sentence.

So this faithful servant of the Lord kept the faith, finished his course,
and fell asleep in the Lord, and is at rest.
He died in the seventy-fifth year of his age, having been a minister forty years.
Many friends attended his body to the burying-ground at Kittering, in Northamptonshire,
where he was honorably buried.

[.asterism]
'''

CHRISTOPHER PEARSON, of Ulluck, in Cumberland, when he was a lad,
went to a meeting of the people called Quakers, at Pardsay Cragg, in the said county,
in the year 1656.
But when he heard the messengers of the gospel of Christ declare the everlasting truth,
who were sent of God to turn people from darkness to the light of the Lord Jesus Christ,
through their testimony, he was convinced by the spirit of truth,
and was thereby reproved for his vanity, and was reached by the Lord`'s power,
and came to know the work of it, and to wait upon the Lord therein,
to witness a being cleansed thereby, and his faith to stand in it;
and so to experience the sufficiency of it.
It was not only given to him to believe in the Lord Jesus,
but also to suffer joyfully for his sake the spoiling of his goods,
and in his deepest sufferings he was supported.

A few days before he died, he said, "`The Lord has been kind to me from a child,
and has done more for me than I could either ask or think:`" adding,
"`I never turned my back upon an informer,
nor ever wronged any man of one halfpenny in all my life to my knowledge.`"
Then he advised his children to be careful, and said to them,
"`Do no harm either to man or beast; but do good wherever you come,
as I have showed you an example.`"
He was a good neighbor, an honest friend, a loving husband, a tender father,
a man given to hospitality, and careful to entertain strangers.
The Lord was with him when on a sick bed,
and his heart was tendered with a sense and feeling of his love and kindness.

A friend being by him, asked him how he did, and how he was satisfied;
he cheerfully answered, "`I am very well satisfied that all will be well;
for I find the Lord`'s mercies are great: but,`" said he, "`I am in great pain,
and think the time long till I am released.`"
Adding, to the friend, "`We have seen much since we were convinced.
We have gone to the meetings in true humility, fear and plainness:
and truth is what it was,
and all that keep faithful to it will be kept by it out of all evil.
I am glad to see my son settled, and I doubt not but he will stand up in my place;
I advise him to be a good neighbor.`"
This ancient Friend, being in great affliction of body, often prayed to the Lord Jesus,
that he would remember him, and take him to his mercy,
that he might be eased of his pains and this troublesome world.
He kept his integrity to the end, and it is not to be doubted but he finished in peace.
His corpse being attended by many friends and sober people to Eaglesfield,
was there honorably interred, and the Lord`'s power was manifest among them,
and the way of life and salvation proclaimed,
with a warning to all to repent of their wickedness, and turn to the Lord,
that they might be prepared for their final change.

[.asterism]
'''

STEPHEN MANNING, son of Edward and Alice Manning, of Edmondsbury,
in the county of Suffolk, was educated in the way of truth,
and was from a child of an innocent and upright life,
zealous and constant in attending religious meetings,
and went several miles to them on foot.
He was a diligent waiter upon the Lord therein, and received much benefit thereby,
in having his understanding enlarged, his strength renewed,
and his heart filled with the love of God, who was pleased to put him into the ministry,
and caused him to declare his everlasting truth,
and to exhort the Lord`'s people in faithfulness to persevere in the way of the Lord,
and to be diligent to wait on God,
that they might live in and enjoy what they were convinced of.
He was also zealously concerned to caution against pride and covetousness,
and superfluity in apparel, and to beware of those sins,
and the various workings of the enemy.

He was a meek, steady man, and lived in what he preached, being exemplary in his conduct,
as became his holy profession.

He was also concerned that the orphans of poor Friends should be taken care of,
and educated in sobriety and in the way of truth.
Being sensible that in some places there was too much neglect,
he wrote an epistle to Friends on that account, which Friends were well affected with,
and read in the meetings which they had for that and other concerns,
as taking care of the poor, etc.

He travelled into several neighboring counties, as Essex, and Norfolk, to London,
and other places, and his labor of love was well received: but growing very ill and weak,
he was unable for such journeys,
and in his bodily weakness travelled and visited
Friends in their meetings ten or eleven miles about.
And when he could not go so far, he attended the meetings nearer,
till he was so weakly he could not: then many friends came to visit him,
to whom he declared truth, and said, "`I have desired to have a name among the righteous,
and the Lord has answered my request.
I have served the Lord faithfully, and have the answer of well done in my bosom.`"

Several tender people, not called Quakers, came to see him, to whom he said,
"`It is well with me, and the Lord will carry me through to my desired place.
It is a brave thing to have a conscience void of offense towards God and men:
there is heaven upon earth.`"

He was a man of few words, but savory;
he had great love and large compassion towards those who had any good desires in them,
and was tender to those whom the enemy, by his subtlety and their unwatchfulness,
had drawn aside out of the right way, and often exhorted,
that they and all might labor to have a possession in the truth, and said,
"`A profession thereof only will not do.`"

He bore his illness with great patience,
to the admiration of those who came to visit him:
he was truly resigned to the will of the Lord, whether in life or death.
He acknowledged his dear and tender father and mother`'s care over him,
and his brothers and sister`'s love, also friends and neighbors who came to visit him,
and said to them, "`My peace is made.
I have nothing to do, but to wait for my change, which I long for.
I have served the Lord to my uttermost, and am sure of an inheritance with him,
who is worthy to be served; he is a good rewarder.`"

After a meeting several friends came to see him,
and one friend spoke to him of his journey to Hopton, after which, he was taken ill:
he said, "`I cannot tell but it might weaken me, but I do not repent it,
being in the service of truth.`"

He exhorted friends to love and unity among brethren, which he delighted in, and said,
"`There was a spirit getting in among the professors of truth, which sought discord;
beware of it.`"
He also signified the judgments of the Lord were come, and coming in this nation,
and said, "`Do nothing whereby to cause the Lord to be grieved;
but be faithful in all things.`"

Some time before his death, on a First-day,
one of his brothers and sister sitting by him, he spoke several things relating to truth,
and the peace and joy he felt: "`And one thing,`" said he, "`I know not, and that is,
why the Lord so filled me with his love this morning,
who account myself but as dust and ashes.`"

About three days before his departure he thought he had been going to his desired place,
and took his leave of his parents and relations, and bade them farewell;
"`I hope I am going to an everlasting habitation,
where I shall dwell forever with the righteous generation;`" more he then said,
which could not be understood: his lips going, his brother endeavored to hear,
but could only understand these words, "`Innocency you love, Lord.`"
After he revived, and next day, though his voice was very low,
he spoke several weighty things, and said, "`Dwell in love, and let it increase.`"

On the third day of the week, and first of the Third month, he said, "`I am extremely ill,
but I hope the Lord will shortly ease me.`"
About the sixth hour at night, he fell as it were into a sleep,
and lay nearly three quarters of an hour, and so passed away quietly;
and a few days after, he was buried,
being carried from Bury meetinghouse to Friends`' burying-ground,
accompanied by many Friends and others,
and several testimonies were borne in love to the truth,
that had made the deceased what he was,
and of their satisfaction that he was gone to his everlasting rest.
Aged thirty-one and three-quarters; and a minister eleven years.

[.asterism]
'''

JOAN SLEY, late of Alton, in Hampshire, was an honest, zealous and faithful woman,
one that loved our Lord Jesus Christ, his ministers and faithful followers,
and was very diligent in meeting with the Lord`'s people to worship and serve him.
Whatever loss or suffering she met with for the same, she neglected hot that service;
and as she diligently sought the Lord, he rewarded her, renewed her strength,
increased her love and zeal for the truth,
and preserved her in his fear to a good old age.
He endued her so with his wisdom,
that she thereby was directed to order her conduct
as became the holy profession she made,
and in that plainness and uprightness of heart that becomes a mother in spiritual Israel,
whose faith and example is worthy to be followed; and she, among the righteous,
to be had in everlasting remembrance.

She was also very tender and charitable to the poor,
and forgot not to do good and communicate.
She was early convinced by that ancient and eminent minister, George Fox,
and being faithful to the Lord, was zealously concerned to bear her testimony for him,
against whatever he showed her to be contrary to truth and the purity of it.

After her first convincement,
she met with sufferings and afflictions from her own husband for a time,
and afterwards from others in her own house; for, after her husband`'s death,
she kept the Crown inn, at Alton, about forty-six years.
She was faithful in her testimony relating to truth,
and zealous in her own house against all manner of excess:
all which gained her a good report.

In the time of her illness, and near her end,
she commemorated the dealings of the Lord with her, and how he had been on her side,
and stood by her in the many great dangers and sufferings she had gone through,
in bearing her testimony among the soldiers and rude
persons that sometimes were in her house.

To the last she was lively in her spirit,
and the Lord was indeed wonderfully good to her, and carried her through all her trials,
and the temptations and provocations of the enemy, both within and without,
that attended her.

She had her memory and understanding to the end,
though in the eighty-fourth year of her age,
and was concerned for the prosperity of truth to the last, saying,
"`If it be the Lord`'s will,
I desire he may extend to the young generation a fresh visitation;
for nothing short of a holy life and godly conduct will do.`"

She advised the youth to read the Holy Scriptures,
and particularly the last chapter of Joshua,
that all might serve the Lord in sincerity and truth, which she had done,
and had the comfort thereof in her dying hour, which was in peace with God.

And as she was well beloved in her life, so, when she was dead,
her body was attended by a great many friends and neighbors, and interred at Alton.

[.asterism]
'''

MARY DICKINSON, daughter of Daniel Dickinson, of Plumland, in Cumberland,
departed this life the 25th of the Eleventh month, in the fourteenth year of her age;
of whom take the account following:

She was naturally of a cheerful disposition, but well inclined to what was good;
patient under what she met with that was not pleasing to her; not apt to be provoked.

The Lord was pleased to give her an understanding of his divine truth,
and so affected her heart with love to it,
that when he was pleased to visit her with that sickness,
of which she died in about fourteen days after,
she was very patient and resigned to the will of the Lord.

Her father, some days before her departure,
asked her whether she had rather die than live; she answered readily, she had rather die,
because she hoped a better place was prepared for her;
and the same question being put to her another day, she gave the same answer.
With brokenness of heart she often prayed unto the Lord.

The day she departed, her mother being by her, said, "`Wait with patience,
the Lord will not tarry long.`"
Then this young virgin, being broken in spirit in much tenderness,
with a heavenly harmony sang praises to the Lord, and uttered many divine sayings,
and cried unto the Lord, saying, "`O Lord!
I pray you remember me this day, and open a door of mercy for me, and take me to yourself.
Lord, have mercy upon my poor soul this day, and open to me this day, I beseech you;
for there is none like unto you; no, not one.`"
Then, speaking to those by her, said, "`Fear God, and love him, and keep his commandments,
all of you; and be merciful to the poor, I beseech you all that hear me.`"
After, her father asked her if she had any pain; she answered, "`My pain is taken away.`"
Again, her father said to her, "`Do you know, my child,
that the Lord has prepared a place for you?`"
She answered, "`Yes; and not for me only, but for all those that love and fear him,
and keep his commandments.`"
About an hour before her death, she being tendered in spirit,
and melted as wax before the fire, asked for a Bible; which being given to her,
she readily turned to the eighth chapter of Genesis, and distinctly read it; then,
covering herself, sweetly died without either sigh or groan.

[.the-end]
END OF THE FIFTH PART
