== Chapter 7

[.chapter-synopsis]
* Samuel Randal
* George Gibson
* Margaret Fothergill
* Tobias Edwards
* Thomas Rudd
* Sarah Clark
* Alice Hayes
* Johanna Noyes

SAMUEL RANDAL.
A short account from Ireland, concerning our dear deceased friend, Samuel Randal,
of Cork, dated the Twelfth month, 1719.

His first coming to dwell among us was about forty years past, as some of us do remember,
when but a young man, at which time, by his grave and solid conduct,
he adorned the blessed truth he made profession of.
In commemorating his station and services in the church of Christ,
and those qualifications wherewith the Lord was pleased to furnish him withal,
whereby he became serviceable therein,
we cannot but be sorrowfully affected for the great loss we have sustained.
For, as he was a good example himself, in plainness, temperance, and justice among men,
so he was also zealously concerned for the honor of God,
and the promotion of his holy truth;
and that good order and discipline might be maintained among the professors thereof;
and that gospel order,
and the line of justice and judgment might be extended
towards loose and disorderly walkers,
that thereby the holy truth might be cleared from the reproach
and scandal that such brought upon it.

In his dealings either with particular families or persons,
he discharged his duty faithfully, without partiality, or respect to persons,
wherein he was sometimes zealously sharp as occasion required.
And as he was deeply sensible, that the world`'s conduct,
and the eager pursuit after the riches and greatness thereof,
was not only hurtful in itself, but had proved so to many,
so was he in both respects concerned to be exemplary.
For when considerable advantages of getting money presented themselves,
with a very probable prospect, he often denied himself for truth and example sake.
Although he had not a public gift in the ministry,
he was often concerned to speak closely to the states and conditions of many,
to the reaching of their understandings.

Thus in the place of an elder, we may say he was worthy of double honor,
as giving himself up cheerfully and willingly to the service of truth, not only at home,
but by his constant attendance at national and province meetings,
frequently attending the former for many years, in winter as well as summer,
until of late, being hindered by age and weakness of his constitution,
he could not go so frequently as before

Much more might be said, as to his many and particular services in love to truth,
and the churches of Christ, but intending brevity, we have given this short testimony,
to be recorded as a memorial of him, with desires,
that as the Lord fitted and qualified him for every
good word and work he concerned him in,
so he may raise up many more to supply the place of him,
and the many other worthy elders, who of late have been removed from among us,
that so from one generation to another, there may be a faithful people,
who may be rightly concerned,
that the testimony of the Lord`'s holy truth may be kept up in all its branches.

He was taken violently ill of a pleuritic fever, and said at first,
he thought he was death-struck, and was well content to die, being, as he said,
weary of a troublesome world; that he had lived to the years of his father,
and if it were the Lord`'s will, he was contented to go now.
So, as one given up and resigned to the Lord`'s will, he said he was not afraid of death,
having nothing that stood in his way.
In the continuance of his sickness, he spoke many sweet expressions,
some of which follow: that he had loved, and sought the Lord in his youthful days;
and that he had been with him,
and preserved him through many difficulties and exercises.
'`And now,`' said he, '`I have a sense of, and do feel his goodness,
which is more joy to me than all visibles; and though he has brought me to a weak bed,
I can praise his name;`' often lifting up his hands, and making melody in his heart.
Being one morning very weak, and short-breathed,
he spoke of the goodness of the Lord to him the evening before.
'`The sweet savor,`' said he, '`still remains with me;`' adding,
that he desired none of his dear friends or relations would pray for his recovery,
but rather that he might have an easy passage, and patience to bear the pains of death.

As he was often, in his health, deeply concerned for his children,
that as they grew in years, they might grow in truth and the fear of the Lord;
so he often told them, he was more concerned, that they might walk orderly,
and have a portion in the truth, than for the great things and riches of this world.
The day before he died, he called for them, to whom he gave sweet and heavenly advice;
and particularly he fervently expressed himself to his son Samuel
how great his concern had been for his welfare every way,
desiring him to seek the Lord, trust in him, and he would preserve and bless him;
also to bring up his children in the fear of the Lord, and keep them from evil company,
and to employments.
And in a general way to them all, he said thus: '`have been often concerned for you,
that you might seek the Lord for yourselves, and live in his holy fear,
and then it will be well with you when you come to die.`'

After this, growing weaker and weaker, two friends coming to see him,
he looked cheerfully on them, and said, '`I am about finishing my course.`'
His breath growing shorter, he lay quietly; and being sensible to the last,
after eight days`' sickness,
we are fully satisfied he laid down his head in peace with the Lord,
and in sweet unity with his people, the 26th day of the Fourth month, 1718,
and was buried the 29th of the same, aged about sixty-four years.

[.asterism]
'''
GEORGE GIBSON was born of believing parents,
who were taken from him when he was but young, yet he was educated among Friends.
It pleased the Lord to visit him with his grace and good spirit,
in his very tender years,
whereby he was early inclined to seek after the kingdom of God and his righteousness;
and he being obedient thereunto,
came to have an experience of the work thereof in himself,
which made his conduct sober and grave, as became the religious profession he made.
And it pleased God to endue him in a good measure,
with a spirit of wisdom and of a sound mind,
whereby he was enabled to stop the mouths of gainsayers, while he was yet but young.

It pleased God, who saw the sincerity and uprightness of his heart,
to call him to the work of the ministry, in or about the 25th year of his age,
which he entered into with great fear and humility.
He was slow of speech, and not hasty to deliver what was upon his mind,
and notwithstanding his voice was low, the savor of life attended his ministry,
which he was very careful to wait for, and thereby was made beautiful,
as well as serviceable and honorable in the church.
A godly care was constantly upon him, to adorn his doctrine,
by a conduct suitable thereto,
by which he obtained a good report in the parts where he dwelt,
among those who made not profession with us.
He travelled pretty much in the work and service of the ministry in this nation;
he was also in Ireland and Scotland,
and his service was well accepted among friends and others where he came.

This is further to be observed,
that when he was not employed in the service of the ministry,
he was very diligent and industrious in his outward business,
thereby endeavoring to maintain his family and bring up his children decently;
and it pleased the Lord so to bless his labors, that the end thereof was answered.
He was much concerned for his children`'s welfare, not only as to outward things,
but that they might be subject to the Lord his God,
often advising and exhorting them to fear the Lord in their young and tender years;
which advice, there is reason to hope and believe, has had, and may have,
some good effect on them.

It pleased the Lord to visit him with the small-pox, about the first of the First month,
1718, which was very sore and hard upon him,
but he bore his affliction with true Christian patience,
and resignation to the will of God.
He was visited by several friends, to whom he expressed,
that he was fully resigned to the will of God;
and that although he had undergone a great deal of bodily affliction during his illness,
yet it was little to him; for he had a being that was not shaken.
He further said, that if the Lord had any further service for him in this world,
he`' did not doubt but he was sufficient to raise him again;
but if it pleased God to remove him now, there was nothing stood in his way: but said,
he could have been glad to see his children settled in the world: nevertheless added,
'`Not my will, but the Lord`'s will be done.`'

His distemper increased upon him until the 12th of the same month,
when a little before he died, his son asked him how he did; to whom,
after a little pause, he answered, '`I am under grace, in the power of truth,
and that is my comfort;`' which was the last sentence he was heard to speak,
and so quietly departed this life, the 12th day of the First month, 1718,
at his dwelling house in Thetford, in the county of Norfolk, in the 48th year of his age,
having labored in the ministry about twenty-two years,
and was buried in Friends`' usual burial-ground in the said town.

[.asterism]
'''
MARGARET FOTHERGILL, late wife of John Fothergill, in Wenslydale, Yorkshire,
was carefully educated, when a child, by her parents, among the people called Quakers;
and while she was but very young, not only delighted to go to friends`' meetings,
but came under a concern of heart,
that she might become acquainted with the Lord for herself,
and be made a partaker of his quickening power and virtue in her own soul.
This concern the Lord was pleased to regard, and graciously came in upon her heart,
by his power and love, and thereby helped her to draw near him,
and worship him knowingly, while she was but very young.
As she grew up, she continued to delight in waiting upon God,
and feeling after his goodness secretly, through the pure influence whereof,
she came to be clothed with a meek and quiet spirit,
and also helped to show it forth in a grave, modest, and exemplary behavior;
because whereof, she was much beloved by most that knew her.
Some time before she was married, being likely to leave her own country,
she came under some exercise to exhort friends in
several of their meetings to a close walking with,
and a true depending upon God;
and to beware of an unconcerned mind when they appeared before him in meetings;
which exercise she made mention of, being fresh in her mind, on her dying bed.

After she was married, she continued a true lover of meetings,
and a humble waiter for the resurrection of the life of truth,
right well knowing that therein is all ability for
the performance of worship acceptable to the Lord.
As she was often attended with fear and care,
lest any thing should divert her mind from the fervent search after the truth itself,
which is absolutely necessary,
so she would often express her sorrow of heart concerning a dulness and
indifference which she apprehended to be growing upon some people`'s minds,
who had long professed the truth.

Notwithstanding her being often unfit for attending meetings,
as she had a good will to do, especially monthly and quarterly meetings,
by reason of having young children,
and sometimes being very tender and weakly as to her constitution of body,
yet would she often express her care that the affairs of truth, in those meetings,
might be managed with suitable zeal and care for the glory of God;
sometimes saying she could be glad,
and was not without hopes of living to be a little more at liberty to attend those services,
and to discharge herself more fully among Friends, for righteousness sake,
whereof she was a pattern in her conduct,
being humbly careful that the Lord`'s holy name might be glorified.

At the birth of her last child, she expressed much thankfulness to the Lord, saying,
in a reverend mind,
'`How shall we be thankful enough for all his help and wonderful goodness!`'
And although she as hopefully got so far as at any other time,
that being her eighth child, yet she grew suspicious of herself,
and the third day after discovered her apprehensions of being taken away, in these words:
'`I wonder that I cannot be troubled that I am likely to leave my little ones,
and my dear husband.`'
These expressions nearly affecting her husband, she added,
'`They (meaning her children) will be cared for, and you will be helped,
and there is a place prepared for me.`'
She continued in a steady expectation of being taken away,
and spoke of things relating thereto, with such cheerfulness and resignation,
as was much admired.
She spoke to several persons in particular, advising them to prize their time,
and make a right use of the visitation of God to them.
She also expressed herself in a living concern that young people, among Friends,
might not content themselves with barely going to meetings; and said,
in a weighty manner, '`It will not do; it will not do: '`and so spoke of her own concern,
and desire to meet with the Lord in her young years, when she went to meetings;
and that she could not be content without his presence, or his love;
and humbly acknowledged his mercy and goodness to her, from her youth upward.
She also said that she had often thought herself poor and bare,
but she followed on after him, and could not let him alone; and humbly acknowledged,
he had often appeared to her as a morning without clouds.
Her heart then being filled with the love of God,
with unspeakable joy in the Holy Spirit,
she sung praises and hallelujahs to the Lord God, and the Lamb, her Savior,
for his lovingkindness and goodness to her, in many respects, till that very time.

Another time, one coming in to see her, of whom she quickly took notice,
called her by name,
and charged her to be careful about going to meetings among the Lord`'s people;
and that she did not go in a careless, or unconcerned mind,
but to sit down at his foot-stool, and wait to hear his gracious words.
She charged her to tell her daughter thereof,
and spoke further of the sorrow which had seized upon her spirit,
because of an unconcerned mind, and indifference,
with respect to waiting for the knowledge of the truth itself,
that she had seen coming in among Friends, which that day,
(or thereabout) she said she well remembered, she had to advise Friends against,
the last time she had any thing to say in meetings, before she left her own country.
And with great weight further said, '`It is great, or absolute mockery,
to go to sit down before the Lord in meetings in a careless mind.`'
After some little stillness, in the strength of the word of life,
she said there was a terrible day of judgment coming,
or hastening upon the backsliders in Zion.
After that she seemed to be easier in her spirit, and lying some time more still,
her husband softly asked her how she was; she replied, '`Well, or pretty well, my love;
I find nothing but ease and peace.`'
Though her weakness had then prevailed much upon her,
and she lay pretty still for some time,
yet her strength was renewed in the power of truth,
wherein she broke forth in supplication, in a very humble and fervent manner,
for the church in general; and also mentioned her little ones.

She farther said, '`Let me be bowed down before the Lord,
that the fruit of my body may be enriched with the same favor,
love and goodness;`' and so went on in praising and glorifying God,
in the aboundings of his love and merciful goodness,
to the tendering the hearts of most about her.
After some time, she being entreated to endeavor after rest or sleep, she answered,
'`I had a fine or easy day yesterday, but this will be a hard day;
for I think I shall rest little more, till I rest for altogether;`' that being about,
or before, the middle of the day.
She continued in humble acknowledgments to the Lord for his goodness and mercy,
and in praises to him whom she often said was worthy, worthy of it forevermore,
so long as her words were intelligible.

Though she had a hard struggle with death, yet the sting of it being taken away,
she seemed not to regard it, or complain,
her spirit being borne over it by the sense of that joy and lasting
pleasure she was near to launch into the full fruition of;
and that evening she departed, being the 16th day of the Second month, 1719,
in the forty-second year of her age; and was buried the 18th day,
in Friends`' burying-place, accompanied by a great concourse of people,
among whom the testimony of-truth was borne,
in the power and goodness of the Lord Almighty,
to the comfort and strengthening of many.

[.asterism]
'''
TOBIAS EDWARDS, of Fordmill, near Warwick, in the same county,
was born in the Eighth month, 1642, and was convinced of the blessed truth,
as professed by the people called Quakers, about the year 1666,
in a meeting of Friends held in Warwick jail,
many Friends being then prisoners there for their testimony to the truth.
About the year 1674 he received a gift in the ministry, in which he was a zealous,
diligent, and faithful laborer.
The manner of his ministry was plain, but very powerful and affecting;
not in the enticing words of man`'s wisdom, but in the demonstration of the spirit.
The tendency of it, many times,
was to encourage and press Friends to a diligent waiting upon the Lord,
that none might content themselves only with a belief, profession,
and outward show of the way of truth,
but that all might come to know and experience the
work of the Spirit of truth upon their own hearts,
that they might depend upon it for relief and comfort in all times of trials,
afflictions and temptations which attend the faithful.
He grew very laborious in his service in his latter time,
being concerned in love to visit some of the meetings
of Friends in several adjacent counties,
in which his service was very acceptable.

He had also a gift in prayer, very powerful, in which he was frequently exercised,
both in our public assemblies and at his visits to`'Friends in their families.
He made frequent visits to the afflicted, and to the poor,
as well as to persons of other persuasions than Friends; and at such visits,
he was often concerned in exhortation, which was weighty, seasonable, and helpful;
and also he was often bowed to supplicate the Lord on their behalf,
which plainly declared, he sought the good of all souls;
and those visits were very serviceable and acceptable to persons of several persuasions.

The Lord not only gave him to believe,
but also to suffer imprisonment for his testimony to the truth,
against that anti-christian yoke of tithes, with a godly resolution,
in patience and resignation to the will of the Lord.
He was committed to prison the 17th of the Third month, 1718,
and continued a prisoner until he died, but through the kindness of the jailor,
had liberty of going to meetings, and to visit his relations and friends.

The 6th of the Seventh month, 1719, in Warwick meeting,
(being the last meeting he was at,) he spoke to this effect:
that calamities would come upon the careless professors of these times,
and desired that the professors of truth would lay it to heart;
for if they were found unfaithful to the gift of God that is manifested in their hearts,
the Lord would be more severe with them in judgment
than to others that know not the truth.
At the close of his testimony,
he said that he felt what lay upon his spirit bore great weight,
so was willing to come to that meeting to clear himself,
not knowing whether he might have the like opportunity again.

He was taken ill the 13th of the same month,
and one of his sons being about to give him something to ease him, he cheerfully said,
'`It may be the hour is coming that I have long looked for and desired.`'
He was brought very weak, yet said the Lord dealt very favorably with him.

On the 18th, two friends went to visit him, and one of them at taking leave, said,
'`Farewell.`'
He answered, he did fare well;
and spoke much of the goodness and kindness of the Lord to him.
The other friend said, I do not bid you farewell, knowing and finding you do fare well;
and that it will not be long before you do enter into your everlasting farewell.`'
To which he answered to this effect: '`I desire that I may not be covetous,
to think the Lord`'s time too long, but that I may be endued with patience,
to wait the Lord`'s time, until I am brought into the full enjoyment of it.`'
After this, he expressed himself to the same purpose as when last at a public meeting,
that is, that the Lord would try us all one way or another.
Some would be tried with deep temptations of the enemy of their souls;
and that the Lord would try the professors of truth, and others also;
and that against those who are not faithful to the Lord during the day of their visitation,
he would be severe in wrath.
Then he was drawn forth in supplication to.the Lord, not only for his church and people,
but also for all people, under whatsoever persuasion or profession of religion,
that they might be brought near to the Lord.

At another time he spoke of the merciful dealings of God towards this nation,
and by way of query, said, '`What reformation has it wrought in a general way?
But little as I can see, except here and there in a poor creature;
but I believe the Lord will deal in his severity, and make them know that he is God.`'

During the time of his illness,
he often expressed the refreshment that he received in the visits of Friends.
At one time a Friend made him a visit,
and was concerned in supplication to the Lord that he would be pleased to be with him,
and give him an answer of peace in his bosom,
for all his faithful services of love among his people;
and if it were the Lord`'s pleasure to remove him,
that he would please to raise up more faithful laborers in his stead.
The powerful presence of the Lord was then with him,
and he poured out his soul in prayer and praises to God,
to the tendering of the hearts of all present, and then said, '`Oh! how good the Lord is;
how comfortable has he made this sickness; how has my soul longed for this.`'

At another time, when several friends were come to visit him, he said,
'`I am but weak of body, but pretty well content to bear it:`'
and added further; '`I have been willing to bear my exercise,
and to suffer affliction with the people of God; for they that will not suffer,
cannot be the people of God.
They that shuffle, and will not bear the cross, will not be accepted of God,
but he will turn them off.`'
Being raised up in his bed, he said, '`Friends, I am glad to see you.
I desire you may be watchful, and have true regard to the truth in yourselves,
that so you may be preserved by it,
and come to be acquainted with the goodness and love of God,
which I feel is renewed to my soul: and also rightly to know yourselves,
that so you may not be beguiled by the enemy.
Some, for lack of having a right knowledge of themselves,
have soared aloft in their minds, and not coming down to the true witness in themselves,
have been mistaken, thinking it to be well with them,
when they have been ensnared by the enemy.
But, said he, '`by the light of the Lord Jesus Christ, you may see your states clearly.
We had need to be very careful to watch against the enemy, for he is very subtle,
and has many wiles, lurking places, and crafty ways to beguile poor souls.
I should be glad, if I were able, to speak of them, and lay them all open,
that you might be forewarned, and so escape his snares.`'

He also advised friends, not to be over careful about the things of this world,
and thereby bring themselves into forgetfulness of God.
He desired friends would not forget his words: '`For, said he,
'`I knew not that I should have been thus concerned among you,
but am helped by the grace of Jesus Christ.`'
These things he spoke with much sweetness and weight,
to the refreshing and tendering the hearts of friends then present.

At another time, being the 20th of the Seventh month, and three days before his death,
several friends being in his room, he said,
the work he was called to was hard for him to express,
because of the weakness of his body; adding,
'`We should not judge according to outward appearance.
But as you have been often exhorted,
so now be steadfast in waiting on the Lord as oft as you can, not only in meetings,
but out of meetings, in your families.`'

He was much enlarged in testimony, but being very weak,
the latter part could not be so clearly understood.
Taking his leave of friends,
he desired those near him to visit him as often as they could;
for they were a comfort to him.
After this he was heard to speak but little,
except to express the love and goodness of God to his soul,
and to return thanks and praises to God for the same.

He died the 23rd of the Seventh month, 1719, and was buried the 27th of the same,
in Friends`' burying-ground in Warwick.
Aged seventy-seven; a minister forty-five years.

[.asterism]
'''
THOMAS RUDD, of Wharfe, near Settle, in Yorkshire,
was convinced of the blessed truth in the early part of his days,
and soon after raised up to bear a faithful testimony for the same,
being called into the work of the ministry, by the visitation of God from on high,
agreeable to the account given of him by Friends of the monthly meeting of Settle,
in the county of York aforesaid, to which he belonged,
and who have given testimony concerning him,
from a certain knowledge of his life and conduct among them,
as well as of his labors and services, on the account of truth in several respects.
He was raised up to be a serviceable instrument for the good of many;
and in his public testimony,
from a sensible experience in himself of the dealings of God,
he became a faithful and diligent laborer in the work of the ministry,
and zealous for the honor of God, and good of people`'s souls.

He travelled in many places of England, Scotland, and Ireland,
as well as some other remote parts, in order to preach repentance,
and warn people to fear the mighty God of heaven and earth, who is, and will be,
as he often used to say, a just and, terrible God to the workers of iniquity,
of what kind so ever,
yet a faithful rewarder of all those that wait upon him in truth and sincerity.
Being often exercised after this manner,
in the streets and market-places of many towns and cities where he travelled,
as well as other places of public concourse, his labors many times had a good effect,
being favored, upon certain occasions,
with remarkable instances of that eminent hand of power that attended him therein,
sometimes to the convincing of gainsayers.

For this labor of love he, in his day, had his various exercises and afflictions,
being many times imprisoned, as well as sorely beaten and abused;
all which he patiently endured, and, like a faithful and valiant soldier,
did not turn his back in the day of battle,
but on the contrary approved himself a faithful warrior
in the Christian warfare wherein he was engaged;
having an eye of faith,
whereby he was made to see as well as taste of the
recompense and reward of the diligent servant,
who is careful to improve his master`'s talent,
as it is believed this esteemed Friend was, agreeable to his measure,
and the dispensation of the gospel committed to him.

He was much in public service abroad for several years, which,
together with his long imprisonment,
often occasioned him to be absent from his family and friends, to whom, when present,
his company was very acceptable, he being a loving husband to his wife,
a tender father to his children, and also very serviceable among his friends;
not only in word and doctrine, in which he often labored in meetings,
with great sweetness, fervency and zeal, but also in the work of discipline,
being earnest after, and greatly desirous for the prosperity of the work of truth in all;
and more especially, that the camp of God might be kept clean,
and that spiritual Israel might be beautiful,
and in no wise stained with any of the vain customs or fashions,
or the corrupt spirit of the world.

For this end he fervently labored both at home and abroad,
wherein he exposed himself to many hardships and perils of several kinds,
until his natural strength and the ability of his outward man were very much spent,
by which he was prevented from attending meetings,
as in the time of health he diligently used to do,
wherein he was very exemplary in coming exactly at the hour appointed,
advising Friends to constancy and diligence therein,
and not to be careless or negligent in that great and incumbent duty.

In the time of his bodily weakness,
he had his memory and understanding very clear and sound,
till near the time of his departure, and always showed great gladness to see friends.
It was his great delight to inquire after, and hear tell of the affairs of truth,
and the prosperity thereof among Friends;
and therein his deportment and behavior were very comfortable,
as well as edifying to several who had such opportunities with him.
It was plainly manifested his chief concern was for the prosperity of truth,
and Friends`' growth and increase therein;
having also an exercise upon his mind in respect of the youth among Friends,
that they might be preserved from the many snares and entanglements of this life,
he himself being carefully concerned to be an example of humility, patience,
and self-denial.

At a certain time, being visited by a friend in the time of his weakness,
he expressed himself after this manner:
'`I have of late time had under my consideration the various and
unusual exercises I have met with in the course of my life,
and the many great afflictions I lave undergone for truth`'s sake,
wherein I have now cause to rejoice,
that I was made willing faithfully to discharge that
concern which many times was laid upon me.
I have the comfort of it now in my declining days,
for I feel the reward of peace and satisfaction in my inward man,
which is a sufficient recompense for all my labor,
notwithstanding I have met with many exercises in my time.`'

His bodily weakness increasing upon him,
and finding his outward man yet more and more to decay,
he was often ready to expect his latter end drew nigh,
which brought a fresh and renewed concern upon his mind,
like a wise virgin) to examine how he was prepared to meet the heavenly bridegroom.

A friend going to visit him, he, in great brokenness of heart, several times said,
It is enough, it is enough, that I feel inward peace.`'
And further added, '`Although I have jeoparded my life many times,
in answering what I believed the Lord required of me, it is all too little.
If any inquire after my conclusion, let them know it is in peace with the Lord.`'
He continued for some time in that tender frame of spirit,
even as though he was filled with a divine sense of the love of God.
And at several times afterwards he was heard to say,
'`Oh! what an excellent thing it is to be at peace with the Lord and all men.`'

There is no cause to think,
but that he had the comfortable assurance and evidence
of peace and reconciliation with God,
through Jesus Christ, having been faithfully concerned in his day and time,
according to the gift or measure of grace bestowed on him;
whereby he was made instrumental to turn many to righteousness.
Having served the Lord and his people in his generation,
it is believed he has laid down his head in peace,
and is entered into that rest prepared for the righteous,
according to Rev. 14:13. "`Blessed are the dead which die in the Lord,
from henceforth, yes, says the Spirit, that they may rest from their labor,
and their works do follow them.`"

He died at his own house, at Wharfe, near Settle, the 22nd day of the Twelfth month,
and was buried on the 25th of the same, in the year 1719, at Friends`' burying-ground,
in Settle, about the seventy-sixth year of his age.

[.asterism]
'''
SARAH CLARK, wife of Robert Clark, of the parish of Bartholomew the Great, London,
was convinced of the blessed truth in the one-and-twentieth year of her age,
and about the nine-and-thirtieth thereof,
her mouth was sometimes opened in meetings in testimony
to that truth she was a witness of.

She was one that aimed after a life of righteousness, godliness, and faith;
often exercised with bodily distempers, which she bore patiently.
In her last illness, being visited by several friends,
one then present was so affected with the sense he
had of the goodness of God to her soul,
that he would not omit penning down the following
savory sayings that dropped from her mouth,
and communicating them to others.`'

'`I have been,`' said she, '`more concerned for the substance,
than for the form and that I might be a preacher in life and conduct,
more than in words.`'
Again,
'`My desire was that the Lord would be pleased to make me thoroughly and entirely clean,
that nothing might be lacking to render me acceptable in his sight.`'

Then, after a little pause, she said, '`I witness my peace to be made with God,
through Jesus Christ, and am willing to depart when he pleases.
Death has no sting; for through the grace of God, I can say with the Apostle Paul,
"`O death, where is your sting?
O grave, where is your victory?`"`' 1 Cor. 15:55.

One asking her how she was reconciled to part from her husband and children;
she answered, '`I enjoyed them in the Lord, and when he is pleased to call me away,
I hope I shall be willing to leave them to him;
for his love is more to me than all the world.`'
As one having full assurance of faith, she said, but in a very humble manner,
'`I know that my Redeemer lives, and because he lives, I shall live also.`'
Adding, as conscious of her own weakness, '`I have no ability of my own,
but all my ability is of God.`'

She continued for some weeks after, under much infirmity of body,
but was preserved in a heavenly frame of spirit, and on the 7th of the First month, 1720,
she departed this life: and after a very large and good meeting at the Peel,
on the 12th following, her body was interred in Friends`' burial ground,
near Bunhill-fields, she being about fifty years old.

[.asterism]
'''
ALICE HAYES was born of honest parents, at Rickmansworth, in Hertfordshire,
in the year 1657,
who educated and brought her up in the profession of the church of England.

It pleased the Lord to make known his truth to her, about the year 1680,
by a servant of the Lord, whose name was Elizabeth Stamper.
She was called forth into the work of the ministry,
and concerned to visit the churches in several parts of this nation,
and many have been reached and convinced through her ministry.
She also travelled through Holland, into Germany, as far as Fredrickstadt,
and had excellent.service; and many were reached and tendered by her ministry,
it being in the demonstration and power of the spirit.

She removed out of Hertfordshire, and came to settle at Tottenham, about the year 1712;
and friends had true unity with her,
both with respect to her innocent exemplary life and conduct,
and also her gift in the ministry, in which she was made very serviceable,
for the encouragement of friends to faithfulness, in every branch of their testimony.
She frequently attended meetings of business,
in which she often gave very solid and seasonable advice.

She being at the Yearly meeting in London, in the year 1720, was taken ill,
but her love being strong to her friends there, she stayed some days,
and then returned home to her house at Tottenham, and grew weaker and weaker,
till she quietly departed this life like a lamb.
But during the time of her sickness, she gave much good advice and counsel to her family,
as also to others who came to visit her,
and dropped many sweet sayings of her comfortable enjoyment of the Lord`'s presence,
some of which are as follows:

James Dickinson and Peter Fearon came to visit her in their return from London,
and had a comfortable time with her,
and she broke forth in admiration of the Lord`'s goodness that attended his servants,
and at that time had enlarged their hearts together.
She said she trusted the Lord would be with them, and be with her to the end,
and help her safely through;
desiring to be remembered by them in their near approaches to the Lord, when separated.
She also desired them to give her love to her dear friends in the North,
not expecting to see them again; but said all would be well.
She was resigned to the Lord`'s time,
and desired the Lord would conduct them safely to their families,
and give them plentifully to enjoy his peace, for their labors in his work and service.

At another time, a Friend of Tottenham coming to visit her,
and some more Friends coming in, she said, '`Oh! love one another,
and the Lord make you a living people to himself,
and preserve you in perfect love and unity.
I am in perfect love to all people;`' with many more weighty expressions,
and then desired friends to give her up freely to her God; saying, '`I am willing to die,
and I hope it will not be long first.
But oh!
I would go exactly in the Lord`'s time.
All that I desire is, that the Lord`'s presence may be continued to me,
and then I fear not the pinching time, the hour of death.
My God is my resurrection and my glory.
Here is my strength, my refuge, and I am thoroughly resigned to his will.
It will be but a little time, and my soul shall sing praise to the Lord on Mount Zion,
with the redeemed of him, out of the reach of trouble.`'

Our ancient Friend, George Whitehead,
was several times to visit her in the time of her weakness,
and had comfortable seasons with her,
wherein she expressed her great satisfaction in his kind and tender visits.

Some friends being come to visit her at another time,
she broke forth in a tender frame of spirit, and said, '`I do wait on my God,
and he is a God of everlasting lovingkindness,
and has been good to my soul all my life long.`'
And then said, '`Friends,
do not put off making your peace with him till you come upon a dying bed.
Here is enough to do, to labor under the afflictions of the body.
I would not be without the favor of God now, for all the world.
The Lord, the God of Abraham, of Isaac, and of Jacob, my God and your God, bless you,
and be a God to you in all your trials; for he has been so to me,
a sufficient helper in times of trouble.`'

Several young people being with her at another time,
she tenderly advised them to be good, and serve God faithfully,
and not put off the great work of their day to the last,
but timely to prepare for a dying hour; '`that,`' said she, '`you may have oil in your lamps,
and be in readiness whenever that time shall come.`'

She farther said, '`It has been the joy of my heart to go to a meeting,
and to meet with the Lord there;
but much more joy it will be to my soul to meet with him in heaven,
and to have a place in his kingdom.
Through mercy, I am under no terror of death, but am in true peace.
Oh! blessed be my God forever, his goodness is exceedingly large.
I would praise him for his goodness, but that I am very weak, and desire,
if it be his will, not to see the light of another day, my affliction being great;
but all in his own time.`'
She then broke forth in prayer, saying, '`Dear God,
make my passage easy;`' and desired to be supported under her affliction,
which at times was very sharp; yet she bore it all with great patience,
still looking to the Lord her Comforter, under the deepest provings.
And often said, '`Oh sweet Lord Jesus, receive my spirit, for I long to be with my Savior;
yet let me not offend you, but patiently wait your time.`'

She greatly desired at another time, that the Lord would bless her children,
and that they might serve him faithfully in their generation.
She was often deeply engaged in spirit before the Lord, for her children, who were all,
save one, at a great distance from her.
She desired they might be men of truth, fearing God.

A few days before her death, some friends of Tottenham being come to see her,
sat down to wait on the Lord God with her.
His love was largely manifested, and sprung up as a fresh spring;
and after a friend had been concerned in supplication to the Lord, she broke forth,
and said, Oh! love; this is love that may be felt.
My God, your goodness is wonderfully large!
My soul praises you for the overflowings of your love at this time;
an opportunity unexpected.`'
With many more sweet heavenly expressions;
and tenderly acknowledged the kindness of her friends in that visit.
Taking leave in brokenness of spirit, she desired the Lord to be with them,
and strengthen them to be valiant for his truth,
and to keep their meetings in his name and power: saying,
'`Oh what comfortable times we have had often in our week-day meetings;
how have our cups overflowed with the love of our
heavenly Father;`' with more affecting expressions,
as to abide in the unity of the spirit of Christ,
every member keeping in his proper place, and concerned for the honor of truth,
in maintaining good order in the church, etc.

At another time near her end,
she desired her dear love might be remembered to all friends,
wishing well to them and to their posterity.
She desired those about her,
when they should see her going to breathe out her last moments, to be very still,
and inward with the Lord in their spirits, breathing for her easy passage.
Adding, '`All will be well; I am going home.
I am going home.
I have done with the world, and all that is in it;
but breathe that the Lord may pour out of his spirit upon a young generation,
that they may serve him in cleanness of heart.`'
And farther said, she had fought the good fight, and should obtain the crown immortal:
adding, '`My beloved is mine, and I am his: he is my All in All.`'
And then prayed sweetly, '`Oh! everlasting God, and mighty Jehovah,
send the angel of your power and presence, to conduct my soul into the heavenly mansion,
my holy King, where there is joy and rejoicing, and singing of praises forevermore.
Into your arms, sweet Lord Jesus Christ, I offer up my soul and spirit.`'

The last words she was heard to say, her voice being low, were,
'`The Lord my God will help me.`'
She was a lover of peace and unity,
and did promote it to the utmost of her understanding;
and in her ministry very plain and powerful: but oh! to the disconsolate,
it often dropped like rain, and run like oil to the wounded;
and she had a word in season to most or all conditions.
But she is now removed,
and no doubt entered into that joy and bliss prepared for the righteous.

One thing must not be omitted: she greatly desired the Lord, by his good presence,
might attend the meeting at her interment; which was eminently answered,
she being accompanied by many friends and others, to Winchmore-hill meeting,
where several living testimonies were borne, and the way of salvation opened,
and many hearts tendered by the Lord`'s power.

She departed this life the 8th of the Seventh month, 1720, aged about sixty-three years,
and was buried the 13th of the same, in Friends`' burying-ground at Winchmore-hill..

[.asterism]
'''
JOHANNA NOYES, wife of Israel Noyes, of Bradford, in the county of Wilts,
and daughter of Jeffery Pinnel, of Bristol, deceased, was a virtuous maiden,
a loving and affectionate wife, a tender mother, a kind mistress, and a good neighbor.
She had a true sense of the blessed truth, which seasoned her heart,
and she was very solid, and truly religious,
and loved to go to meeting on week-days as well as First-days,
and was well fitted for her change.
She is, no doubt,
entered into that glorious city and place of rest
that is prepared for all the followers of the Lamb,
where all sorrow and sighing shall flee away,
and the Lord God will wipe away all tears from their eyes.

Her stomach failed, and she was attended with a cough and intermitting fever,
so that she grew weaker and weaker; and on the 6th day of the Eleventh month, 1720,
she took to her chamber; and though her weakness increased,
yet her spirit grew stronger and stronger.
She often signified how good the Lord was to her;
and desired her husband to bring up her children in the way of truth,
and keep them to Friends`' school, that they might be kept to the plain language.
Also she desired of the Lord that he would be pleased to make them his servants.

She oft-times was in a heavenly frame of mind,
and told those present that the Lord had given her
a full assurance that it would be well with her,
and she should go to that glorious kingdom of rest and peace.
She desired her husband to take care to live in the fear of God;
and at the same time advised her sister, Anne Pinnel, and her sister-in-law, Mary Tyler,
to keep to their exercises in meetings, telling them they had no assurance of time here,
and that it would not do barely to go to meeting,
but they should be diligent to wait upon God in meetings.
She felt so much of the power of the Lord that it made her cup to overflow.

She expressed that the power of the Lord was in such an extraordinary manner with her,
that she seemed to be in heaven already:
and several relations being present with her at that time,
were deeply affected before the Lord,
under a living sense of his mighty power that was then felt among them,
to their great comfort; a day, it is hoped, never to be forgotten by them.
Also she said, the spirit of the Lord in her strengthened her to speak:
she signified that her children were near,
but she could not see room to desire to stay from heaven for them.
She bore her illness patiently,
and with much resignation of mind to the will of the Lord, often saying, '`Lord,
if you please to take me, I am ready;`' and often supplicated the name of the Lord,
and had a longing desire to be dissolved, and be at rest.

Another time, on a First-day morning, she said, '`Ah! this is First-day;
sometimes I have had good meetings, and if I was well, I would go to meeting.`'
And said to her husband, '`My dear,
the sweetness of the Lord`'s spirit is upon me to a great degree.`'
A little before her departure she often said, '`Come, Lord Jesus,
and receive the soul of your handmaid.`'
She spoke to her servant-maid, and desired her to think on the hour of death;
and advised her not to tell lies; and pressed upon her to mind her advice,
as they were the words of her dying mistress.

She said the night before she departed, '`O Lord, be pleased to give me a little ease,
and take me to yourself; for here is nothing but ups and downs in this world;
trouble on one band, and trouble on the other.`'
Then she broke out in a heavenly frame of mind, saying, '`Lord,
you are a fountain of living mercies;`' and desired that
the spirit of the Lord might remain upon her aunt and sister,
that were then present with her, continuing praising the Lord.
She said to her mother-in-law,
'`The Lord has made you a mother to me`' and in a while after, '`Mother,
now I shall be in heaven in a little time.`'

She quietly departed this life like one falling into a sweet sleep,
between the second and third hour in the afternoon, on the fourth day of the week,
and the 22nd of the Twelfth month, 1720, aged twenty-nine years, four months,
and two days.
The Second day following, being the 27th,
her corpse was interred in Friends`' burying-ground at Comerwell,
belonging to Bradford meeting, where a great number of people, both friends and others,
attended the corpse to the meeting-house which joins to the graveyard,
where was a living and powerful testimony borne to the truth.
