== Chapter 9

[.chapter-synopsis]
* Alexander Seaton
* Thomas Raylton
* John Wynn
* Deborah Wynn
* Deborah Bell

ALEXANDER SEATON was born at Cuttle-Craggs, near Lethinty,
in the parish of Daviot and shire of Aberdeen, in the north of Scotland,
in or about the year 1652; son of John Seaton, from the Seatons of Meldrum;
and brought up a scholar, and for some time in the college in the old town of Aberdeen.
While he was a scholar, there was a dispute between the students of Aberdeen,
and Robert Barclay and George Keith, who defended the principles of truth,
as held by the people called Quakers, against the students, in the year 1675.
He being present, was so far convinced of the truth of the doctrine held by Friends,
as afterwards to own the same publicly.
So that while he was a young man, it pleased the Lord to open his understanding,
and show him the mysteries of his kingdom, and way of life and salvation;
and being joined in society with the people in scorn called Quakers,
he grew in the truth, and became very instrumental in the service of the gospel,
for the confirming of friends in the truth, and information of others,
yes even such also that opposed the truth.
He was drawn forth in the love of God, to visit Friends`' meetings in Scotland,
Ireland and England, several times, was imprisoned at Aberdeen,
and suffered very much at Glasgow for his testimony to the truth.
He was a faithful,
zealous and sound minister of the gospel of our Lord and Savior Jesus Christ;
exemplary in humility and lowliness of mind, lived in peace and unity with friends,
and was well esteemed among his neighbors.

When under weakness and affliction of body, he bore it with much patience,
and was very sweet in his spirit, as may appear by the following expressions.
Several being come to see him, he said, "`Since these severe fits,
I was concerned about my latter end, and it was opened to me,
that I should depart in peace.
There is a mansion of glory prepared.`"
At another time, when his family was about him, he said,
"`Do not put off repentance and amendment of life until the time of a dying bed,
for commonly it has enough to do for itself.
The Lord has been very good to me, even from my youth,
and has followed me with his goodness, and never left me in the time of many exercises.
His presence is near, and it is manifested to me, that when my departure comes,
it shall be in peace.
The Comforter is near, and will endure, and the afflictions will have an end.`"

At one time when some friends came to see him, he said,
'`I have partaken of the earnest of that joy that will never have an end.
My rock, my fortress, my strong tower, dwells with me,
and does not leave me or forsake me, blessed be his name.
I hope to be with him forever, and that is more than a thousand worlds.
There is a mansion of glory prepared.
In my Father`'s house, said Christ, there are many mansions,
if it had not been so I would have told you;
there has been a discovery of a mansion of glory.`'

Some friends coming before meeting, to see or visit him, he said,
'`Job was hardly put to it, and his friends were all mistaken,
in that they did not believe that the Lord afflicted man without a sinful cause.`'

His wife persuading him to take something, lest he should faint, he consented, saying,
Let me try to eat one bit with my friends, '`but turning the case, added, '`Christ said,
labor for the bread that perishes not, but nourishes up to eternal life.
Praises wait for the Lord in Zion.
No trials, no afflictions, no temptations,
can obstruct his presence from the inhabitants thereof.
Praise is comely for the upright, but becomes no wicked person.`'

Sometimes, being much pained, he would say, '`Lord give me some ease,
or take me to yourself.
O Lord give patience, sustain and support me under these sharp afflictions.
Let the lifting up of my hands be as the evening sacrifice, acceptable unto you.`'

'`O Lord! you are my rock, the shadow of a mighty rock in a weary land.
The Lord has promised to be with his children through the region and shadow of death,
and bring them to a lasting eternity,
where there is joy forevermore;`' and therefore said to his wife, '`Be content.`'

Another time, after having got some rest in sleep, he said, '`Why am I kept here.
Let me go home.
Lord receive my spirit.
I recommend my soul to you.
Receive me into your everlasting kingdom, and the mansion of glory you showed me.`'

A near friend coming in to see him, asked him how he was; he said,
'`I would eagerly be gone, the Lord has been very good to me,
and led me through the cross to inherit the crown.

When he seemed to be a little eased of the pain which was often violent upon him,
his wife asked him if anything troubled him,
as to the settling of his affairs or children; he said, '`No,
the greatest trouble that attends me, is to part with you,
who have been made a blessing to the family.`'

At another time he said, '`The Lord has been good to me from my childhood.
He began to place his fear in my heart very early.
The Lord never fails those who trust in him, he will be with them to death,
and through death unto eternity.
Fear God and serve him, prefer his fear above all things, and he will provide for you.
And said to his wife, '`My dear, the Lord is a father to the fatherless,
and a husband to the widow, that love and fear him,
therefore be content and resigned to the will of the Lord.`'

About two or three weeks before his decease, several friends having been at meeting,
went to see him, and after a time of silence, a friend spoke a few words,
after which Alexander being very much broken into tears, said,
'`It is the invisible power that supports under affliction.
Moses endured, seeing him that is invisible.`'
At another time he said, '`A sharp war, the sooner peace,`'

Several Friends, belonging to Lurgan, Ballindery and Lisburn meetings,
hearing that he was very weak, came to see him,
whereupon his wife asked him if he knew them; he said, '`I do very well,
but it is a trouble to me to speak; but all is well, and will be everlastingly well.`'

His distemper was tedious, being often extremely sharp,
all which he bore with admirable patience,
and departed this life in great peace and quietness, the 23rd day of the First month,
1723.
And we have good ground to believe that the Lord has received
him into his kingdom of everlasting rest.
His corpse was decently buried the 25th day of the said month,
lovingly accompanied by friends and neighbors.
Aged about seventy-one years; a minister about forty-seven.
"`Precious in the sight of the Lord is the death of his saints.`"
Ps. 116:15.

[.asterism]
'''
THOMAS RAYLTON.
--Some account of the birth, education,
and convincement of that faithful minister of the everlasting gospel, Thomas Raylton,
found after his decease, in his own hand-writing:
to which is added some farther relation of his ministry, etc.,
since his settlement in London,
taken from the testimony of the Bull and Mouth monthly meeting, concerning him.

'`I was born on the 30th day of the Sixth month, 1671, in Bowes,
in the north part of Yorkshire, and educated in the way of the church of England.
But in the year 1685, being about fourteen years of age,
and then a scholar with one Richard Wharton, priest of the parish,
and teacher of a free school in Bowes aforesaid,
it providentially happened that by the invitation of Francis Wrightson,
one called a Quaker, at whose house a meeting was kept,
about two miles from the place of my abode, my mother went to a meeting there,
and took me to ride before her.
At this meeting were two ministers, namely, John Bowron and George Rook,
the latter then living in Cumberland, but since in Ireland,
being come to visit Friends thereaways, by whose powerful ministry and lively prayer,
it pleased God to open my heart, and to let me see the vanity of this present world,
of which, for my short time, I had had some share,
for which I had been often secretly smitten by the just witness of God in my own heart.
Yet, for all that, I was pretty much a stranger to it,
and so was not sensible from where it came, until I came to be affected with the gospel,
which, I may say, was glad tidings of salvation to me.
From that day, I was joined in heart with those people that directed to Christ within,
the hope of their glory.
And although I have had many instructors in Christ since, yet I have not many fathers,
for the said George Rook, who preached the word by the gospel of Jesus Christ,
was the instrument under the Lord for my convincement; for which, I bow my knees,
and worship and thank the Lord for his goodness hitherto.`'

After I was joined with those people, the word of God more powerfully wrought in me,
and showed me that I was to alter the course of my conduct; that was,
to leave the corrupt life, and shun evil company.
And forasmuch as I was bowed before the Lord, and had given up my name to serve him,
I then saw I must walk in the narrow way, and leave the vain compliments,
the putting off the hat, and bowing the knee to man, etc.
I was soon taken notice of, and complaint made to my mother,
of my neglecting to conform to these things, by the priest, my then master,
who was moved at my behavior, and I suppose, intended at that time to have used the rod,
and having made preparation, called me to him.
He said, I. heard today that you went by Mr. Bounskell, and did not put off your hat,
and bid good morrow; adding, What is your reason for so doing?
whether is it pride or religion?
Upon which I told him it was not pride.
Then, said he, it must be religion; and if so,
you must not be whipped and so laid down the rod.
But, said he, if for religion, let me know why you refused, and give me some precedent.
So I told him I had been reading in the Revelations,
and there I found that an angel showed John many things, and that John said,
"`When I had heard and seen,
I fell down to worship the angel that showed me those things; but the angel said,
See you do it not, for I am of your fellow servants, and of your brethren the prophets,
and of them which keep the sayings of this book: worship God.`"
And from this I told him, I refused to do it unto men.`'

But he endeavored to persuade me, that what he requested of me, was.
no more than a civil respect between man and man;
and from there he thought I might the better conform to it.
To make me the more willing to believe it was no worship, but respect,
as he had said before,
he turned me to the place of Heth and Abraham`'s bowing to each other,
and also proceeded to show me something of the like kind among the Children of Israel,
in the time of Moses and Joshua.
But all these were to no purpose to me,
for my eye was open to see a more glorious dispensation than that of Moses, yes,
or the prophets.
For though they were good men, and by the spirit of Christ in them,
they did foretell the coming of Christ, and of his sufferings;
yet they did not live to see those things come to pass, which they had spoken of.
So that he had no force in his argument to make me use those things,
which might be used among the fathers, and also after the law.
And since the New Testament is silent,
and gives no account of either Christ or his apostles being in the practice of bowing;
I did not see why either knee or hat should be expected of me.
As for the latter, I have no account at all, therefore I stood to my principle,
and kept to the light and understanding the Lord
has given me through Jesus Christ my Savior,
who then was come to my house in spirit, and had brought salvation with him.`'

That day I told one of my school-fellows that what
my master had shown me was but out of the law,
and not of the gospel, which he told my master, and I had a quiet day.
It is to be observed that this was but the beginning of further exercise,
for as it was in some measure begun,
(though I had at that time met with favorable treatment from my examiner whose moderation,
as I have said, then appeared,) yet after this,
whether it was grief which he was then in,
being in all probability likely to part with one from his flock,
over which he might look upon himself to be pastor, or from the persuasion of my parents,
he began to be more severe, and told me that unless I would make congees to him,
as he called them, he would teach me no longer.
Although I must confess I would gladly have learned a little more,
being then a bible-scholar, yet +++[+++rather than]
to have it in a, way I saw I must deny and bear testimony against,
I forsook the school at that time, and went home to my father`'s house,
and told my mother the occasion of my coming.
Although she took me to the first meeting but a few weeks before,
yet she then repented it, and would not hear of my suffering by my master,
so as to give me any relief; upon which I left the house for a while.`'

But I think I may say, the arm of the Lord wrought for me,
for my master presently sent word to my mother,
that he had done what was in his power to persuade me to be conformable,
but he saw it would not do, therefore desired her to send me to school again,
and said he would leave me to my liberty about religion.
The tidings were brought to me, as I was alone under a hedge, where I was retired,
not then knowing what would become of me, who had both left the school,
and knew not with whom to lodge.
But while I was in this condition, the tidings I have mentioned were brought to me,
which I received gladly, and went to school again,
and found it pretty much as had been told me;
and thus the Lord pleaded my innocent cause, to whom be glory ascribed forever.`'

Thus far I was got on my way, and was still to go farther.
My parents had taught us from our childhood to ask of them to pray to God to bless us;
and though it is true there is not an evil in the thing itself,
yet the bringing of it into such a form as to use it every night and morning,
this also I found was my place to leave off, at which they were very much offended,
and began to beat me into a compliance with them.
But that would not do, for I had read that saying of our Lord,
"`Whosoever loves father or mother more than me, is not worthy of me.`"
So that in a holy resolution I went on,
not much doubting but the Lord would help me over that as he had over other things before,
which, in time, he did.`'

The course I took, after much threatening and several beatings upon the above subject,
was this.
I left my father`'s house, and was kept privately for about fifteen days; but as Moses,
by the good providence of God, and care of his sister,
who watched to see what would become of him,
was ordered to his mother again to be his nurse, a providence to be commemorated,
so was I watched over by some of those people to whom I was joined in fellowship,
and by them sent for to come to one of their meetings.
I being then remote from it, yet at their request I went;
for meetings were precious to me.
I had been but at about two meetings from the first,
and that was about three quarters of a year before,
and a good meeting this also was to me.
After the meeting was over,
some of the Friends undertook to go and offer me to my father again.
I went along with them, and coming there,
they told my father it was their desire that he would take me home again,
as I was his son; and if he would not accept of me as a son,
then as a servant into his house; but if he would not as either, then, said they,
he must become our care, forasmuch as he is become one of us.
This proposition took such place with my parents,
that the Friends were thanked for the care they had over me.`'

Thus I was brought home again, and had free access to their presence morning and evening,
without insisting upon the aforementioned ceremony,
which was the cause of my leaving their house,
because they were wroth that one of their children should leave their religion,
and decline going to church, as they called it.
For about seven weeks more I lived with them at peace,
and went to meetings with their knowledge; and at the end of that time,
being the 30th day of the Fourth month, 1686,
I went apprentice to a Friend in the county of Durham, by the approbation of my parents,
being conducted there by my father.
Thus my freedom was brought about, so that I might well, with some of old,
sing unto the Lord, and say, he had delivered me from the noise of the archers,
in the places of drawing water.`'

In the time of my seven years`' apprenticeship to a laborious trade, being a blacksmith,
at leisure times I often read the Scriptures of the Old and New Testament,
in which I found great benefit, being often broken into many tears when I read,
and especially when I met with places that mentioned the call of God to sinners,
and their return to his call, in order for their conversion and salvation.
My delight was much in reading some places of the prophets,
which prophesied of the coming of the just One,
and of the work of restoration that he would bring to pass,
and although I have said I delighted in those things, yet the crown of my rejoicing was,
that I was counted worthy to know this blessed work begun.
I not only read in private, but in the family we used to read much by candle-light,
my master and mistress allowing it, and were in the practice thereof themselves,
being honest Friends who feared God, with all their children,
who were dutiful to their parents,
and kept very much out of the evil communication of the world,
so that we were a comfort one to another, as we kept to that which was good.
When I have been alone at my work, the Lord very often comforted me with his holy spirit,
and gave me a sight that he would give me a dispensation of the gospel to preach;
and for seven years the word of the Lord was often very powerful in my heart,
not only to the fitting of me for so great a work,
but growing upon me to the affecting of my heart.
During those years, living breathings often ran through me to the Lord,
that he would preserve me in his fear.

After I had served out the full time of my apprenticeship,
I went to the place of my birth, and there followed my trade about a year.
But it was not long until the Lord brought that which I had seen before more near,
that is, the work of the ministry.
The nearer it came to me, I still saw the more need to be weighty and solid,
and much inward in spirit, often filled with the word of life,
so that I could scarcely hold my peace in the assemblies of the people of God;
yet much inward and still, often remembering the building of Solomon`'s temple,
where there was not the sound of a hammer or iron tool.
In this quietness in meetings,
I was greatly refreshed and filled with inward joy to the Lord,
but could not yet utter by words what I felt.
For, indeed, as the ministry is a great work,
it made me the more cautious how I entered into it,
remembering it was not approved that one of old laid hold of the ark +++[+++unbidden]
when it was shaken.`'

By all this experience and carefulness,
in not offering until I was fully satisfied it was my incumbent duty,
I found it safe not to appear in the ministry until
I was fully satisfied of the Lord`'s requirings therein,
although the Lord had been often with me from meeting to meeting, and,
in his visitations, left his holy dew upon my spirit.
Thus was I filled with the odor of his good ointment,
with which I was anointed to preach the gospel; and thus I was led into the ministry.`'

Upon or about the 30th day of the Tenth month, 1695,
in a meeting at the house of John Bowron, in Cotherstone, where I was, among many more,
after a little time, my soul was divinely touched with the power of God,
and his word was again in my heart, as a burning fire in my bones.
I could no longer contain; my tongue being loosed,
my mouth was opened to speak of the Lord unto his people in that meeting.
I cannot but observe one thing, and that was,
the holy silence which was in the forepart of that meeting, before my mouth was opened.
Although there were several there that had public testimonies,
yet that power by which I was opened, bound them to silence.
But after I had spoken what I then delivered, there stood up a Friend,
and was like one that had a seal to set to the words I had spoken.
As I grew in testimony, a concern came into my mind to visit Friends in Cumberland,
where, after some time, I went, and was kindly received by them,
and was at most of their meetings, if not all.

T+++.+++ Raylton

This our dear friend Thomas Raylton,
after he had travelled much in the service of the truth,
settled in London about the year 1705,
where he was very serviceable and edifying in his ministry, sound in his doctrine,
mighty in the Holy Scriptures, zealous for the truth,
and a faithful reprover of any undue liberty in the professors of it.

He was many years afflicted with infirmity of body; but being fervent in spirit,
was strengthened in the work of the ministry beyond expectation;
so that he bore his testimony to the truth at times, in the meetings of Friends,
not only in London, but in most counties of England.
The year before his death, in much bodily weakness, he took a journey from London,
and visited the brethren in his native county, to their mutual comfort,
and returned home well satisfied in his service there.

In his last sickness, which took him about the beginning of the Ninth month, 1723,
he bore the extremity of his pain with great patience and resignation;
having some time before signified a sense of his approaching departure, by saying,
'`My day`'s work is nigh finished.`'
And but a few days before his death, he told a friend that he had settled his affairs,
being satisfied that his departure was at hand; adding in a sensible and humble manner,
'`Doubtless it will be a glorious change to me.`'
To his wife he thus expressed himself, '`My dear, be easy, let me go,
and rejoice when I am gone to so great salvation.`'
He departed this life in peace and full assurance
of future happiness at two in the morning,
the 6th day of the Tenth month, 1723, in the fifty-third year of his age,
and was decently buried on the ninth of the same month,
in Friends`' burying-ground near Bunhill-fields.

[.asterism]
'''
JOHN WYNN, of Bradford, in Yorkshire,
was convinced of the blessed truth at a meeting of Friends in Pall-Miall,
near Westminster,
about the time of the coming in of king Charles II. Being then in the army,
and standing among the rest in their ranks to be viewed by some of the chief officers,
he laid down his arms because he could practice war no more, and when discharged,
he went down into Yorkshire, and worked at his trade there, being a clothier.
As he continued faithful to the visitation of truth, he grew in grace,
and in the saving knowledge of Jesus Christ our Lord;
and being subject to the divine manifestation and work of the power of God in his heart,
he became a sanctified vessel fitted for the great Master`'s use,
who in his wisdom called him to the work of the ministry,
in which he grew and labored faithfully in those times of persecution,
wherein he suffered deeply for his testimony.

He was a man of courage, filled with a holy zeal, and qualified,
as a good soldier in the Lamb`'s warfare, for the work in those perilous times;
his bow abiding in strength, and his arrows being sharp and piercing,
were carried home to the mark, so that he fought manfully under the banner of Christ,
and turned not his back in the day of battle.
He was an able minister of the everlasting gospel, and labored faithfully therein,
and travelled much for the spreading of it in those
trying times in most parts of England and Wales,
and especially in the eastern parts.
His service on that account tended much to the strengthening
and confirming the children of God,
and convincing of gainsayers.
He retained his integrity to the end,
and the strength of that holy zeal kindled in his heart for the blessed truth,
and the promotion of its cause, remained always with him.
For a further account of his labors, service, and sufferings,
the reader is referred to several testimonies concerning him,
published in the year 1715.

Towards the latter part of his time, he travelled into the west parts of Yorkshire,
to visit the meetings of friends there.
Having a sense that his day`'s work was nigh finished,
he told friends in several places he was come to take his leave of them,
although then in a good measure of health.
After his return, he signified his great satisfaction and easiness of mind.
About three weeks after he had finished that journey,
going a few miles to visit a neighboring friend who was sick,
a service that he was frequently concerned in, he came home not very well,
and continued weakly about thirteen days.
In the time of his weakness, the great concern that was upon his mind was,
that friends might stand faithful to the Lord God,
exhorting such thereto as came to visit him.
He declared, a little before his departure, that he was clear and easy in his spirit,
and saw nothing to stand in his way, but witnessed the peace of God to abide upon him,
saying he had labored faithfully to clear himself
of those who were of a libertine and frothy spirit,
as he then called it.

The day that he died, a little before his departure, as he was walking about the room,
a fainting fit seized him, and he sat down and leaned back in his chair,
and seeing his wife weeping over him, he looked upon her, and said, '`Why will you,
my dear?
the Lord gave you unto me, and you must give me up again.`'
She answered and said, '`I hope I shall as far as the Lord enables me,
for I hope it will be well with you.`'
He said, '`I never doubt that: '`which were the last words he spoke,
for the Lord was pleased to make his passage easy out of this world,
so that he gave neither sigh nor groan, but in a quiet stillness,
like one falling asleep, he departed this life the 16th day of the Ninth month, 1699,
in the sixty-fourth year of his age,
having been a true laborer in the work of the ministry about thirty-six years.
Having, through the grace of God, fought the good fight of faith,
and finished his course,
we have no cause to question but that his soul is at rest with the Lord,
being entered into the possession of that crown of eternal
life that is laid up in store for all the righteous,
where he will live to praise and magnify the Lord God,
and the Lamb who sits with him upon the throne, forever and evermore, world without end.
Amen.

His body was buried in Friends`' burying-ground, at Bradford aforesaid,
the 20th day of the aforesaid month,
being accompanied to the grave by many Friends and sober neighbors,
where several living testimonies were borne to the comfort of the upright in heart,
and particularly by that eminent minister of Christ, William Ellis,
who had been effectually reached to by his ministry in his young years.

[.asterism]
'''
DEBORAH WYNN, wife of the aforesaid John Wynn, had a sober and religious education,
and was favored with the visitation of truth in her young years,
and by giving up to the manifestation thereof,
she came to experience the work of its power in her heart, and,
by being obedient thereto, attained to a degree of settlement in the truth when young.
This prepared her to undergo those trials and exercises
which early began to fall to her lot;
for about the sixteenth year of her age,
her father and mother were both taken up and carried prisoners
to York for the testimony of a good conscience towards God.
She being their only child,
the management of their trade and business fell under her care;
and during their imprisonment she travelled, to York, twenty-two miles, on foot,
twice in two weeks, to visit them,
and to carry them what money she had got for their support.
Being sincere in heart to God, and through his grace faithful to the truth,
she grew in experience,
and about the eighteenth year of her age she was
concerned to bear a public testimony in meetings,
to the comfort and edification of Friends.

She was afterwards married to John Wynn, and they settled at Bradford,
the place of her nativity, and, being both ministers,
and the meeting in its course held at their house,
heavy sufferings fell to their share in the time of the informers,
who stripped them three several times of all their outward substance that was valuable.
For such was the cruelty of the persecutors and informers in those days,
that at one of the times mentioned she was lying sick,
and they went to take the bed from under her; but the neighboring women,
abhorring the inhumanity of such an attempt, interrupted their design,
and would not permit it; but they, finding a pewter flagon in the room with caudle in it,
poured it out, and took the flagon away with the rest of the booty.
Their avarice being not yet satisfied, they met her husband in the street as they.
went away, who had been at a`' neighboring market, and was driving his horse before him,
with the goods on his back, and his riding-coat upon the pack;
all which they seized and took away with the rest of the plunder.

Being deprived of his horse, pack and coat,
he came home and found his shop stripped of the goods, and his house of the furniture,
that he had neither chair nor stool to sit down upon to rest him,
until some of his kind neighbors, whom he found there bemoaning this unchristian usage,
went and brought him in, some one thing, and some another, for their present use,
until they could procure furniture of their own for their necessary accommodation.
Afterwards, several of the inhabitants of the town,
hearing of his intention of buying more goods to carry on his trade, came to him,
and earnestly entreated him he would buy no more,
for he might see they were resolved to ruin him.
He told them he was not at all discouraged; he had a little money left,
and intended to lay it out for goods as far as it would go;
and if they took them from him also, they could have no more than all;
but he believed they would be limited in the Lord`'s time;
which came to pass accordingly.

Through all which, with her dear husband, she retained her integrity,
and stood faithful to truth`'s testimony,
so that they were favored of the Lord together to surmount
all difficulties their great sufferings brought upon them.
She was a woman of a sound judgment,
great sincerity and circumspection in the course of her conduct,
tender and living in her public ministry;
and by her godly and courteous conduct she gained the love and esteem
of both Friends and others in the town and country where she lived.
Her heart and house were open to receive and entertain the messengers of Christ,
who were concerned to go to and fro to promote piety and virtue,
and publish the gospel of glad tidings to mankind;
and she delighted much in that service.
It was my lot to marry her only daughter,
after which time she chose to live with us to the end of her days,
which was upwards of seventeen years,
which tended much to our satisfaction and mutual comfort.
She being acquainted with several of the first publishers
of the gospel of glad tidings in these latter days,
her conduct was very agreeable and informing.
She was a loving and affectionate mother, a faithful friend,
and endued with wisdom to give counsel in times of greatest difficulty,
having had large experience of the dealings of God,
and the preserving power of Jesus Christ our Lord;
she retained her zeal for truth and concern for its promotion,
and was diligent in attending meetings as long as
her ability of body continued to go abroad.

She was confined to the house the last year of her time,
growing weak by reason of old age; and during that time,
she employed herself much in reading the Holy Scriptures and Friends`' writings,
with many of whom, in her youth, she had been acquainted.
She continued in a sweet, heavenly frame of mind, often expressing, in much tenderness,
the lovingkindness and goodness of God to her, frequently saying,
'`The Lord has been my support in all my difficulties, and has preserved me from danger;
and his goodness is still continued,
and I have great cause to praise him and speak well of his name.`'
This she would often repeat, with many other weighty and lively expressions,
signifying how resigned she was to the will of God, and desirous to be dissolved,
being duly prepared for that great change.
About three months before her departure she was confined to her chamber,
but still continued in a sensible frame of mind, and waited patiently for her removal,
expecting its drawing nigh,
although she had no distemper upon her but weakness through old age.

Her daughter`'s affection and care were great over her both night and day,
for fear she should drop off suddenly, though a nurse constantly attended her.
When she saw +++[+++her]
weep, and under trouble at the apprehension of parting with her, she would send for me,
and would desire me to advise my wife not to be troubled or concerned on her account;
for, though she had no distemper, pain nor sickness,
she said we must not expect she would always continue with us,
but would have us give her up freely, she being prepared,
and ready to be received by Jesus Christ into eternal felicity.
I told her we were resigned to the will of God,
and thankful he had so long prolonged her days,
and accounted it a great blessing our being favored with her company to that time.
She added, '`Your care over me, and your concern for me,
have been too great in every respect, I think;
and I have been often thankful to the Lord,
who has been pleased to bless me with such loving and affectionate children.
I have been afraid my dear daughter would hurt her own health by caring too much for me.
The Lord who was the stay of my youth, and has been with me to old age,
is still near to comfort, and will be so to you when I am gone,
and bless and preserve you to his own honor and your peace unto the end:
'`with much more at several times, too tedious to relate.

She grew gradually weaker, yet sat up most days,
and could walk over the room with a little help.
In the evenings, when business was over, we went up and sat down by her,
and had many comfortable seasons together, for she continued in a sweet frame of mind,
and very cheerful and sensible.
On the 14th of the Sixth month, 1727, being the second day of the week,
my dear wife and the nurse took her up and dressed her about ten in the morning,
as usual, and she sitting in her chair, they perceived she grew very weak,
and sent for me.
I went up and sat down by her, and taking her by the hand, asked her how she was,
she answered, '`Very weak, child.`'
I asked if she was sick or faint, she said`' No.`' I asked if she had any pain, she said,
'`No.`' I asked if she apprehended herself going, she said she could not tell,
but she was weaker than ever she was before.
I bade her lean her head upon my breast, which she did, and was as quiet for some time,
as if she had been in a doze, that we could scarcely discern her breathe;
and her daughter sitting by weeping, she lifted up her eyes and said, '`Dear child,
weep not for me, '`and leaning her head on my breast again,
near the middle of the day she passed away so quietly,
that we scarcely knew when she drew her last breath.
She was about eighty-two years of age, and a minister about sixty-four years,
and I doubt not,
is entered into that undisturbed and glorious rest prepared for the sincere
and upright-hearted followers of the Lord Jesus Christ.

On the seventeenth day of the aforesaid month,
her body was carried from our dwelling-house in Clement`'s
lane to the meeting-house in Gracechurch-street,
where many friends met on that occasion,
and several living testimonies were borne to the truth; and after a solemn meeting,
her corpse was accompanied by a large number of friends
to Friends`' burying-ground near Bunhill-fields,
and there decently interred.

[.asterism]
'''
DEBORAH BELL, wife of John Bell, of Bromley, in Middlesex, late of Gracechurch-street,
London, daughter of the before-mentibned John and Deborah Wynn, was born at Bradford,
in Yorkshire,
and being carefully educated in the way of truth by her pious and faithful parents,
she sought the way of the Lord, and the knowledge of his blessed truth, when very young,
and was mercifully favored to partake of that virtue and
divine goodness which makes fruitful towards God,
as she frequently expressed herself.
In her minority she often earnestly desired that the Lord
would be pleased to enable her to come up in doing his will,
and that in all things she might be perfectly resigned to answer his holy mind and requirings,
and be fully given up in heart in all sincerity,
and by his grace devoted to serve and obey him, according to the ability received.
He in mercy and lovingkindness heard her humble petitions,
and granted the early visitations of his love and goodness,
in the pourings forth of his holy Spirit, and gradually,
by the work of his own divine power, so prepared and sanctified her heart,
that she was made a vessel of honor.

As she became acquainted with his divine and living word, when very young,
she grew in experience of that work which is wrought by the power of Christ,
by which alone salvation and perfect redemption is witnessed.
Being a humble follower of Jesus Christ our Lord,
and through the operation of his grace freely resigned, and cheerfully given up,
to follow these manifestations of the divine light and workings of the Spirit,
which are inwardly revealed, she was so fitted for her Master`'s use and service,
as early to become a branch in Christ Jesus, the true and living vine,
laden with fruit to the praise and glory of God, the good husbandman.
Being led through deep travail, and close exercise and affliction of mind,
she thereby gained great experience,
and was made sensible of various states and conditions,
which tended to qualify her for that great and weighty
work whereunto she was afterwards called.

About the nineteenth year of her age the Lord saw fit in his wisdom
to commit a dispensation of the everlasting gospel to her to preach,
in which service, she being faithful, grew in the knowledge of God,
and had great experience of his dealings, and like the wise scribe,
who was well instructed to the kingdom,
brought forth out of the good treasury of her heart, things both new and old;
so that she became an able minister thereof,
to the comfort and edification of the churches where she came.
Many, who were unacquainted with the work of the blessed truth in themselves,
were reached to by her powerful and lively ministry,
in the service of which she often appeared strong when in bodily weakness,
which frequently attended her,
to the admiration of those who had the knowledge of her outward infirmities.

She labored faithfully in word and doctrine,
and visited many of the meetings of Friends in most parts of England, Wales, Scotland,
and was twice in Ireland, and had good service where she came,
for she duly regarded the motions and guidance of truth in all her services,
and in an especial manner, when under a concern to travel on that account.
She earnestly desired to be fully satisfied of being rightly called,
and to see her way clearly opened, both as to the time when, the place where,
and the people to whom, it was her duty to minister,
and was ever very careful to return when she found her mind clear and easy.
She would often say, which I mention for the instruction of others,
that there was great danger in exceeding the commission
by staying abroad beyond the right time.

She greatly desired that all the ministers of Christ,
who found themselves concerned to travel in the service of the gospel,
might take due care not to miss their way on that hand; neither might,
when in their travels, be drawn aside out of the right line opened to them by the truth,
through the persuasion of unwary inconsiderate people,
but might wait for the power of Christ our Lord to preserve them steady
in mind in all their services for the promotion of the blessed truth,
frequently repeating that she had observed several
whom she believed to have been rightly drawn forth,
who yet through weakness and instability had missed their way in those particulars,
and thereby received hurt and lessened their service.
When she was under a concern to go abroad to visit the churches,
the weight of that exercise brought her very low, both in body and mind.
She waited diligently for the counsel of God, and full satisfaction in herself,
before she made her concern known to any; for her whole dependence was,
in great humility, on Christ our Lord, to put her forth, and go before her,
and to give her strength and wisdom,
to discharge herself faithfully to her own comfort and peace,
the edification of the people, and his honor.
But though she was strong in the Lord, and zealously concerned for the cause of truth,
yet, by nature, of a weakly constitution, and through hard travel, and close exercise,
which often was upon her for the truth`'s sake,
her bodily infirmities increased before old age came on.

Towards the latter part of her time, being often infirm,
she frequently rejoiced in the Lord, and expressed the great comfort, peace,
and satisfaction which she had in having devoted her youthful days to his service,
and being freely given up faithfully to obey his calls and holy
requirings while a degree of health and strength was granted,
and she was able to undergo such service,
often saying an early devotion was very acceptable to God,
and the strength of youth could never be so well and profitably employed,
as in faithfully serving the Lord in humility and sincere obedience in
whatsoever work he in his wisdom may be pleased to qualify them for,
and call them into.
For wheresoever it happened that any such lived to
be attended with the infirmities of old age,
the comfort and peace they would enjoy,
would be abundantly more to them than all the comforts of this life;
for she could by living experience say,
that nothing in this world was worthy to be compared with it.

She often earnestly desired the sense thereof might lay hold of our youth,
that they might give.
up their minds to seek the Lord early,
and devote the strength of their time to his service,
that in the end they might be made partakers of the same comfort and peace,
which was her greatest joy and real cause of rejoicing,
and became more and more so as she drew near her conclusion.
This I publish for their perusal, that if by any means they might be prevailed on,
and stirred up to consider how necessary and truly profitable it
is to begin early in that great duty recommended by the wise man,
"`Remember now your Creator in the days of your youth, while the evil days come not,
nor the years draw nigh, when you shall say, I have no pleasure in them.`"

Being under a concern to visit a few meetings in Hertfordshire, and as far as Huntington,
though in a weak state of health, she undertook that journey, which proved her last,
towards the middle of the Seventh month, 1738.
She was from home ten days, and had six meetings, and although weak in body,
yet she appeared strong in her ministry, and had good service,
much to the satisfaction and comfort of Friends where she came.
When she came home she rejoiced much,
and said she was humbly thankful to the Lord who had enabled her to perform that journey,
and had given her strength to discharge herself faithfully of that concern she was under,
and that her heart was filled with that peace and comfort
which he is pleased to favor his obedient servants with,
and that she apprehended her day`'s work was nigh finished,
for she saw no more work her great Master had for her to do;
and she had no desire to live, but to serve and glorify him.

The last time she was at an evening-meeting at Bromley, about two weeks before she died,
she bore a living testimony to the truth,
and was concerned in supplication to the Lord in a particular manner,
and in great fervency prayed for the preservation, growth,
and settlement of the youth among us, in the living, eternal truth,
to the affecting and tendering of many hearts.
When she came home from the meeting she was filled with divine comfort and said,
'`t is now finished, I do not expect you will have me with you at that meeting any more.`'
Afterwards her weakness of body increased, and she took a cold, which seized her lungs,
and occasioned a hoarseness, which she was often liable to.
On the 22nd day of the Eighth month, being the first day of the week,
we went to London to meeting, but being so much indisposed,
she was under some difficult y to stay the time of it, and did not go in the afternoon,
but waited for me at a friend`'s house until meeting ended.
Coming home, she continued weakly,
though a little better at times till Fourth-day evening,
but she grew much worse again that night; she therefore had the advice of a physician,
but it had not the desired effect.

Her affliction increasing, on Sixth-day morning a pleurisy came on,
which distemper she had been liable to, more or less, for the last ten years of her time,
having had several severe fits of it, which much affected her breathing.
Though means were used to remove it, she found no relief, and the pain grew more violent,
so that her affliction was great,
and in a humble submission she earnestly desired of the Lord that
he would give her strength to bear her pain and affliction patiently.
Her petition was fully granted, for she was endued with patience to an uncommon degree,
and bore her affliction with such a firm resignation and thankfulness of heart,
and with tender love and condescension to all about her,
and abundance of sweetness she still enjoyed,
as appeared by many precious and lively expressions which dropped from her,
which deeply affected, and often tendered the hearts of all about her.

When her pain was very great, she expressed herself at times after the following manner:
'`This is hard work indeed.
One had need to have nothing else to do at such a time as this.
I am sure it is as much as I am able to endure, to bear the afflictions of the body.
One had not need to have terror of mind besides.
Appealing to a young woman standing by her, whom she dearly loved,
and who had duly attended her in her illness, she said,
'`You know I have had very little respite from pain since I was first taken ill.
I would have none put off that great work of repentance till such a time as this;
if I had that work to do, what a dreadful thing it would be.`'
At another time, several young people being present, she said,
I would have our young people be willing to bear the cross in their youth,
and despise the shame; for that is the way to have true peace in themselves.`'
Another time she said, I now feel that which my soul has longed for.`'

Seeing several young women standing round her bed,
whose growth and settlement in the blessed truth she had often been concerned for,
she looked solidly upon them, and spoke as follows:
'`I was early convinced that unless I was born again, I could not see the kingdom of God.
I have witnessed it, and you know I have preached this doctrine to you;
and you must know it for yourselves.`'
This she spoke with such authority as pierced the hearts of all present,
and I believe will not easily be forgotten.
At another time, looking steadily upon us, with a composed countenance, she said,
'`I have always been sincere, and never had anything in view but the great cause of God,
and that I might be clear of the blood of all men;
and I have discharged myself faithfully, for whatsoever my hand found to do,
I did it with all my might, and I never spared myself; and I am fully clear and easy,
and my day`'s work seems to be done.`'

At another time, observing the distress I was in, she looked earnestly upon me, and said,
The Lord brought us together, and has been with us,
and you must give me freely up to him again, and he will support you,
and take care of you.`'
At another time, I being in deep distress of mind,
under the consideration of my great loss of so dear a companion,
if she should be removed, I asked her if she had not rather live with me a little longer,
if Providence saw fit.
She looked pleasantly upon me, and, after a little pause, said,
'`I have no desire nor will of my own.
I stand in the will of God.`'

At another time, under the sense of her great pain, she said,
'`I earnestly desire the Lord may release me while
I have strength and patience to bear my afflictions;
but I neither murmur nor repine.`'
Observing the sadness of my countenance, she said, '`Why should I not go now?
I can never go better.`'
I told her if Providence pleased to raise her again, she might be with me longer,
and be of service, and yet go well.
She readily answered, '`There may be danger in that; I am now ready.`'
At another time I told her, when bemoaning myself,
if the Lord should see fit to remove her from me at that time,
that I believed he would receive her into the mansions of glory.
She replied and said, '`I never doubt that.
I trust through Christ to be received into the arms of eternal bliss, for I am in peace,
and perfectly easy.`'
At another time she looked upon me, and said, '`The Lord gave me to you,
and you must give me up to him again.`'

Toward the latter part of her illness, being in great pain,
and observing the concern I was in for her, she said, '`My dear,
I am afraid you boldest me.`'
I answered, '`No; I have freely given you up, and stand resigned in the will of God.`'
She looked pleasantly upon me, and replied, '`That is very good in you.`'
Afterwards, her affliction and pain being very great and heavy upon her,
she prayed fervently, and said,
'`Lord be pleased to grant me a little ease before I go hence, and be seen of men no more,
no more, no more.`'
And the Lord was pleased to answer her fervent supplication;
for the day before her departure, all pain and affliction seemed to be removed,
and she continued quiet and easy, in a still, sweet frame of mind.
Although she spoke not much during that time, which could be perfectly heard,
yet she remained very sensible,
and her sweet and lively breathings plainly declared she
continued in inward prayer and praises to the Lord,
her lips often moving;
and sometimes expressions were heard tending to signify the full assurance
she had of an inheritance in eternal felicity and glory among the just.
Many more precious and weighty expressions she dropped during her illness,
which the distress of my mind prevented me from remembering perfectly.

About the fifth hour in the evening, being the Fifth-day of the week,
and the 2nd of the Ninth month, 1738, she sweetly finished her course,
and went away like an innocent lamb;
and notwithstanding the great affliction and pain
she underwent for seven days and seven nights,
that brightness and innocency which truth had impressed,
remained on her countenance when the soul was released,
and had taken its flight into the regions of bliss and glory.

She was aged about forty-nine years, and a minister upwards of thirty years.
She was endowed with many eminent gifts and qualifications; an able minister,
rightly dividing the word of truth through that wisdom received from God,
which proved effectual to the convincing of many, and the edifying and reaching of many.
She was zealous for the cause of God, and of a discerning spirit and good understanding,
so that the enemies of truth could not stand before her, for her bow abode in strength,
and her arrows were often carried to the mark, and were sharp against undue liberty,
deceit, and the works and workers of unrighteousness.

She dearly loved the children of the light,
and sincerely sympathized with such in their afflictions
who were seeking the way to Zion,
and often had a word of comfort to them.
Her heart and house were always open, according to the example of her pious parents,
to receive the ambassadors of Christ, remembering what he said,
"`Whosoever shall give to drink unto one of these little ones a cup of cold water only,
in the name of a disciple, verily I say unto you, he shall in no wise lose his reward.`"
And likewise what he told his disciples, "`Verily, verily I say unto you,
he that receives whomsoever I send, receives me; and he that receives me,
receives him that sent me.`"
Her delight was in the company of those who labored for tie promotion of the gospel, and,
through a good degree of experience,
she had sometimes a word of advice and encouragement to such.

She was a loving and affectionate wife, and the gift of God to me,
and as such I always prized her; a help-meet indeed both in prosperity and adversity,
a steady and cheerful companion in all the afflictions and trials which attended us,
and a true and faithful yoke-fellow in all our services in the church.
Being ever one in spirit, we became one in faith and practice,
in discerning and judgment, and our concern and labor was the same,
which nearly united us, and a life of comfort and satisfaction we lived;
our souls in the nearest union, delighting in each other,
and the love and presence of God,
wherewith we were often favored in our private retirements, sweetened every bitter cup,
and made our passage easy and pleasant to us.
But, alas! what shall I say; the Lord, who is all-wise,
and only knows what is best for us, has called her hence,
who is worthy to do whatsoever he sees fit.
Therefore, in humble submission to his will who gave, and has taken away, as knowing,
though it is my loss, it is her everlasting gain, I rest,
and can in sincerity and truth bless his name who is worthy forever.

J+++.+++ B.

On the 7th day of the month aforesaid, her body was accompanied from our dwelling-house,
at Bromley, to the meeting-house in Gracechurch-street, London, from which,
after a solemn meeting, many being affected with the removal of so near a friend,
it was carried to Friends`' burying-ground near Bunhill-fields, and buried by her mother,
according to her desire.
"`Precious in the sight of the Lord, is the death of his saints.`"
Psalms 116:15.
