== Chapter 1

[.chapter-synopsis]
* John Gratton
* Joseph Baynes
* William King
* Blessing Fenn
* Ebenezer Slocomb
* Isabel Gill
* Daniel Gould
* John Bowstead
* Sarah Elkington

JOHN GRATTON was a man of note,
and one whose Christianity showed itself in the spirit of meekness and humility,
notwithstanding many troubles and exercises which he met with.
He was also an able minister of the everlasting gospel,
being made instrumental for the convincement of many.
He had great openings, was sound in doctrine, and skillful in hitting the mark.
His ministry was lively and powerful, plentifully opening the Scriptures.
He travelled much in the service of truth, both in this nation,
and in other countries adjacent.
His residence was at Monyash, in the county of Derby, above forty years,
where friends were often comforted in his company, and therefore loved him in the truth,
and do believe that he lived and died a servant of the Lord.

The winter before his decease he sensibly decayed,
so that he would often say he could not continue long; his stomach being so weak,
he could take little food for several months before he died.
His desires were great to go from here, if the Lord saw it good;
and as his weakness increased, his desires, if could be,
grew stronger and more earnest with the Lord,
to remove him out of this troublesome world,
being well satisfied his day`'s work was over; yet desired to wait the Lord`'s time.
A grand daughter of his being then very ill,
he often gave good advice and counsel to her, to fear the Lord,
and be obedient to her parents; with more to that effect to all his grandchildren.

About a month before his decease, his daughter was called on so suddenly,
that it was thought he could not live till she came to him.
She found her children and the maid weeping, thinking he would not have spoken again,
but when he saw her, he broke out into tears,
saying he thought he should never have seen her more;
but soon got a little strength to sit up in his chair,
and called all the children to him, one by one, and kissed them, giving them good advice,
saying it was a great comfort to him,
to see that they should part in so much love and unity one with another.
Calling for the maid, he spoke very tenderly and lovingly to her:
and being attended with sore sickness and pain, he said, "`Lord,
I pray you give me ease if it be your holy will, and remove me soon out of this body.
You know it is through your great mercy that we have hope in you.
Lord, I pray you, be with my children that I leave behind,
and with all friends and neighbors, of what profession soever.
It is through Christ Jesus our Advocate, who is gone before us,
that we are enabled to come to you.`"
And further said, "`Lord, if it be your holy will, remove me out of this troublesome body.`"
Another time some friends being come to visit him,
he was told there were such friends come to see him:
he said they might see he was a weak man: and looking on them as they sat by him,
he said, "`The Lord bless his people and prosper his truth among them,
and enable them to live in love one with another.`"
Not long after, weakening very fast, he said, "`Lord,
I freely commit my soul and spirit unto you.`"
He desired to have his dear love given to friends, naming several particulars;
and a little before he died, told his daughter,
now he thought he should be gone in half an hour; being very sensible to the last.

He departed this life at Farnsfield, in Nottinghamshire, on the 9th of the First month,
1712, and is at rest with the Lord, where the wicked cease from troubling,
and where the weary are at rest.
He was buried the 11th of the same month, in the sixty-ninth year of his age,
having been convinced of the blessed truth about forty years.

[.asterism]
'''

JOSEPH BAYNES, of Stangerthwaite, in Killington, in the county of Westmoreland,
was born of honest parents.
In his young years he was desirous to attain to the true knowledge of God;
which desire God graciously answered to his seeking soul,
in convincing him of his blessed truth, by that faithful laborer and servant of Christ,
George Fox, at his first coming into these parts, being in the year 1652,
by whose ministry he was turned to the light of Christ Jesus,
by which he came to see the emptiness of those outward forms
and ceremonies in which he had been educated.

He was a man who truly loved and feared the Lord,
making it his daily care to keep his conscience void of offense towards God and man.
A considerable time after his convincement,
it pleased the Lord to open his mouth in a public
testimony for the truth he was convinced of.

His doctrine was sound, expressed deliberately with clear distinction,
and a solid grave countenance.
His deportment was such as very much adorned his ministry;
all which rendered his service the more acceptable both to friends,
and others not professing with us, among whom he gained a good esteem.

He suffered joyfully the spoiling of his goods,
for his testimony against that anti-christian yoke of tithes,
and on several other accounts for truth`'s sake:
He endured many imprisonments with steadfastness and great patience,
being truly thankful that the Lord had counted him worthy to suffer for his name.

In the latter part of his time he travelled very much in this nation for many years,
He had a great love and esteem for the yearly meeting in London,
which he manifested by diligently attending it, even from his youth,
until by old age he was unable to travel so far.
He very much labored to promote love and unity among friends;
expressing how hard a thing it is to reconcile an offended brother.

He was a nursing father to the youth, lending a hand of help to the weak,
and young convinced, in order for their settlement and growth in the truth;
and was careful to visit the sick,
imparting such advice and counsel as was proper for them.

A little before he was seized with bodily weakness,
a concern fell upon him to advise young men and women to wait for the power of God,
which would work a change in their hearts, and make them new creatures; otherwise,
said he, they will but have a form of godliness, without the power;
and such live in an unregenerate state, who produce the fruits of nature,
but not of grace.
Mark, said he, grace teaches to deny ungodliness, and the world`'s lusts; to live soberly, etc.
But alas! too many of our youth, for lack of taking the grace for their teacher,
go into a false and undue liberty in their words and apparel,
making that of no conscience to them, that the power of truth made conscience to us.
For by that power we were made willing to put off all superfluity in eating, drinking,
and wearing of apparel.
Our words were few and savory, for the Lord`'s dread was before our eyes,
and our peace with him was precious to us, which we,
through obedience to the grace of God in our hearts, enjoyed.
This, with much more wholesome counsel, he imparted to the youth.

He was under bodily weakness for a considerable time,
in which he told friends who came to visit him, that the Lord was good to him,
and that he had many precious openings upon the Holy Scriptures,
brought very clearly before him, beyond what he had ever seen before:
several of which he spoke of with much tenderness and brokenness of heart,
to the refreshment of those present;
in particular concerning the death and sufferings of Christ,
and the hard-heartedness of that unbelieving generation,
making a parallel between them and the hard-hearted,
and unbelieving in his spiritual appearance, in this age of the world; "`which,`" said he,
"`makes a sorrowful impression upon my spirit.`"

"`I had a sense,`" said he, "`that I must not continue here long, but lust die and not live;
but I covet not long life,
hoping to be gathered to my dear brethren that are gone to their rest before me:`"
signifying his satisfaction and assurance of peace to his soul,
when his days in this world should be at an end.

The day before he died he sent for a friend whom he desired to see, and when she came,
he said, "`I much longed to see you once more,`" she having made him several visits.
I am under great affliction of body,
but hope the Lord will cut the thread of my life before long.`"
She replied, "`It has been a long time of illness to you, nearly three quarters of a year.`"
"`Yes,`" said he, "`but I have had great ease at times,
for the Lord has been very good and gracious to me all along,
though I am not worthy of the least of his mercies;
but for his Son`'s sake I hope he will remember me in a little time,
and ease me of all my pain.`"
Though he was exceedingly short of breath, besides great pain of body,
yet he spoke of several matters relating to truth,
being engaged in his mind for the honor of it.
After this, he had a sweet time in supplication to the Lord, for his goodness to him;
then lifting up his dying hands, which trembled through weakness,
he took leave of the friend, saying, "`Farewell, the Lord be with you.`"
He said little more, but lay still, as if he felt not much pain,
and so departed this life in much peace, upon the 26th day of the First month, 1714,
and was buried the 28th of the same, in Friends`' burying-ground at Brigg-Flatts,
near Sedburgh, aged eighty-one years.

[.asterism]
'''

WILLIAM KING, late of Oakeliff, in Yorkshire, was a man fearing God,
of a peaceable conduct, not only in the church, of which he was a faithful member,
but likewise to such as were without; and he obtained a good report among both,
and has left a sweet savor behind him.

It pleased the Lord to commit to him a dispensation of the gospel,
and therein he approved himself a faithful and true laborer,
according to the measure of the gift bestowed,
to promote truth and righteousness in his day, and was a good example;
and manifested to all,
that it was his chiefest care to live a life answerable to what he made profession of,
often advising friends to keep to the root of life, the spring of divine wisdom,
from which all good comes.

He was also a diligent attender of meetings, and advised friends to faithfulness therein.
When his departure was near at hand, he, as he often had,
gave good advice and counsel to his children, to keep to the truth,
and to set their hearts and doors open to the friends of it;
saying he had as much love to friends and truth as ever.
To a friend who came to visit him, he said, "`I am fitted to die.`"
At another time he said, "`I can with the apostle say, measurably,
I have fought the good fight, and kept the faith, and well nigh finished my course,
and there is a crown laid up for me.`"
He often declared his full satisfaction concerning his future well-being;
and uttered many more weighty expressions, not noted.
He departed this life the 17th of the Third month, aged sixty-five years.

[.asterism]
'''

BLESSING FENN, daughter of Joseph and Patience Fenn, of Cork,
was born the 8th day of the Fourth month, 1700.
She was a child of a weakly constitution, and for several years very sickly,
but of a ripe and ingenious wit.
For the most part, while she had health and strength,
she delighted to be employed about some business that was innocent and profitable,
not loving idleness; and also was much delighted in reading the Holy Scriptures,
and other good books,
and would often make her remarks on several passages
as she read and speak of them to her mother,
asking several weighty questions.
She was very dutiful to her parents, and extraordinarily tender of her mother,
who was sickly.
She loved honest Friends, but would be troubled when she beheld any, professing truth,
behave themselves unseemly.

Some weeks before she died, her mother went with her a mile or two out of the town,
to a neighbor`'s house, for the benefit of the fresh air,
where she continued until she ended her days.

In the time of her sickness she was very careful of her mother,
and would often keep her pain much to herself, lest her mother should be troubled.
The sharpness of the pain, together with her great weakness,
would cause her at times to fret,
and speak a little angrily to the nurse that attended her,
but she would soon be sorry for it, and say to the nurse,
"`Do not take notice of what I say,
for I love you very well;`" and would discourse sweetly with her,
and give her good advice.

She did not seem to take much notice of her end being
so near till the morning before her departure;
at which time, her mother perceiving an alteration in her,
asked her if she was willing to leave her.
She answered, "`What the Lord will.`"
Her mother replied, "`It is hard for me to part with you.`"
After a little pause she said, "`It is true I am very weak,
but the Lord is able to restore me to you again;`" and more to that effect,
which was thought to be spoken to prevent her mother`'s grieving for her.
Her mother asked her if she was willing to see a Friend who was expected in town soon:
she answered "`Yes, or any honest Friend.`"

In the afternoon two Friends came to visit her, and being in the room with her mother,
the nurse was on the bed by her; she said, "`Nurse,
do you think I shall live till tomorrow?`"
The nurse answered, "`Yes, and a great deal longer.`"
"`No,`" said she, "`I shall not;`" and immediately cried out, "`Lord help me,
Lord help me!`" Her mother hearing her, stepped hastily to her,
and asked her what was the matter.
The two Friends coming to her as she sat up in bed, she looked solidly at them, and said,
"`Pray to the Lord that I may have a short and easy passage.`"
One of them said, "`You have had a long time of consideration.`"
She answered,
"`I was never careless in the time of my health;`" and so immediately fell into a great agony,
death-pains seizing her.
She again desiring them to pray for a short and easy passage; a Friend answering, said,
"`We must wait God`'s time, and I believe it will not be long.`"

Her mother asked her where her pain was; she said, "`Everywhere.`"
Then she said, "`Lord, give me patience;`" and asked several times "`Will it be long?`"
After some time the extremity of her pain left her,
and she sat pretty quietly with her eyes shut, then opening her eyes again,
a friend told her she had got a little sleep.
"`No,`" said she, "`I was enjoying sweetness.`"
After a little while her pain increased again, but not so violent as before:
her mother asked if she had a desire to see her father: she said, "`Yes,
if he will come quickly.`"
Her father being sent for, soon came with some other of her relations, and he,
sitting on the bed by her, asked her how she did.
She looked at him, but did not speak;
at which her mother asked her if she would not speak to her father.
She said, "`I cannot yet;`" being in pain.
After some time, she looking earnestly at him, said, "`Father, pray for me,
that I may have a short and easy passage.`"
Her father being nearly concerned for her,
after a little while kneeled down by her bedside to pray,
and desired that as the Lord had been pleased to give her to him,
he would be pleased to take her to himself, and that he might make her passage easy,
and all of us subject to his will; and more to that effect;
concluding with thankfulness for all the mercies we receive:
at which time she was very quiet and attentive.

After a little while her father asked her if she was freely given up in her mind:
she said, "`Yes, I am, freely.`"
Being asked if she was willing to leave her father and mother, she said, "`Yes, I am.`"
After that, she said, "`Lord, take me to yourself.`"
So she continued in a sweet frame of mind; desiring those about her to be quiet,
when she heard any speaking, or noise in the room.
She remained quiet and sensible to the very last,
and so died about the ninth hour in the evening, the 12th of the Third month, 1713,
being four weeks short of thirteen years old.

[.asterism]
'''

EBENEZER SLOCOMB, who departed this life at his own house in James Town,
on Conanicut Island, the 14th day of the Second month, 1715,
in the sixty-fourth year of his age, was born in Portsmouth, on Rhode Island,
the 25th day of the First month, 1652,
and had his education among those people called Baptists.

Being a man of great stature, and strong and nimble of body,
he was given to those recreations that were in those days accounted civil;
but about the twentieth year of his age,
it pleased God to send his faithful servant George Fox, into those parts,
and he was willing to go to hear him preach, which he did.
But being in that nature which understood not the things of the spirit of God,
he came to this conclusion in his mind, never to hear any of the Quakers again,
boasting in himself that the Baptists were nearer the rule of the Scripture than they.

Thus he went on for some time, until God, who brings down the high from their seats,
and scatters the proud in the imaginations of their own hearts,
was thus pleased to manifest himself to him.
He, with two more of his company, were passing by a barn, where there was a meeting,
at which was that eminent gospel minister, John Burnyeat, of Cumberland,
of the nation of England; and he being preaching as they were passing by,
they all went to the outside, to hear two or three words,
to talk of as they went on their way.
It so pleased God,
that at that instant John Burnyeat was treating of that saying of John the Baptist,
where, speaking of Christ, he said,
"`He shall baptize you with the Holy Spirit and with fire;`"
which Ebenezer did not remember he had ever read,
although he thought he knew more Scripture than any of the Quakers.
He was willing to lean against the door-post to hear farther,
although his companions jogged him to be gone.
Yet he stayed,
until through the powerful preaching of the gospel he was reached to the heart,
and made in his own soul to confess,
that all his Scripture knowledge and high notions of water baptism,
had left him short of the new birth,
and the baptism of Christ by the one Spirit into the church, which is his body.
Yet he did not give up in obedience for some time,
until the fire of God began to kindle in his own
soul against the root of the corrupt tree,
and every branch thereof; for he found that saying of the prophet fulfilled,
that "`There is no peace to the wicked.`"

About this time, being with his newly-married wife at a merry-making,
where they were pitching the bar, they persuaded him to pitch with them, but he refused,
being sensible the Lord had appeared to him, to redeem him out of such vain delights.
But they at last set his wife to work; and she, through much entreaty,
prevailed with him to pitch once.
And although he outdid all the company, to their rejoicing who set him to work,
yet the Lord, who requires obedience according to the understanding given,
set his folly and shunning the cross so powerfully before him,
that for a time he thought the day of his visitation was over.
Yet he, who in judgment remembers mercy, after some time,
was graciously pleased to show him, that he might come out of condemnation,
by obeying the law of the spirit of life, which now, through Christ,
was made manifest in his mortal body, to reprove sin in the flesh:
to which he gave up in faithfulness.

The Lord was near to him, both to comfort him in his exercises,
and also to give him sound wisdom,
and a divine understanding in the mysteries of his kingdom.
After a few years He called him into the work of the ministry,
in which he approved himself a laborer who needed not to be ashamed;
for he rightly divided the word of truth, being sound in doctrine,
and his speech very often ministered grace to the hearers,
and was sealed by the spirit of God to many of his auditors,
to the turning them home to Christ, the great minister and mediator of the new covenant,
which God has made with his people in this latter age of the world.

He was also made an overseer of the church in these parts, by the great Bishop of souls,
and Shepherd of the sheep; in which he acquitted himself like a true servant of Christ,
being a pattern to the flock in his conduct and Christian humility;
as also in his apparel and furniture.

He travelled much in the work of the ministry for the space of thirty-six years,
both in the colonies of New England, and also several times to Long Island,
East and West Jersey, and Pennsylvania, and in his latter years to Maryland,
about 500 miles from his habitation;
in which travels several were convinced of the everlasting truth through his ministry;
also the convinced were built up in the most holy faith,
which gives victory over all the works of the flesh.

He was also very serviceable in meetings of business where he came,
that the professors of truth might, in all their conduct, be brought to walk in the same,
having an excellent gift in the service of the church.

In the latter part of the year 1714, he travelled to Boston, Lynn, Salem, Hampton,
and Dover, taking his leave of Friends, saying he never expected to see them again;
for he had a sense that his time in this world was near to a period;
and was also in this journey very serviceable in
preaching the gospel of Christ with power,
and with an audible voice, and in giving good counsel to Friends.
When he was at home, he always delighted in the company of Friends,
who stood zealous for a right godly discipline and good order in the church of Christ,
which the Lord has measurably established among Friends, that so the honest,
though weak, might be preserved, and all disorderly walkers who would not be reclaimed,
might be testified against, as professors who are gone from our holy communion;
in which good work,
this Friend was one of the first rank in these American parts of the world.

As on one hand he always accounted the disorderly walkers, under profession of truth,
his enemies, and they often found from him a stroke of sound judgment,
so on the other hand,
he was a tender nursing father to the honest-hearted
and young scholars in Christ`'s school.
He ruled not with severity over any, because they were younger than he;
but always delighted to see young men come up in a part
of the good order established among his people.
And if at any time they were too zealous to be borne
by the old and loose professors of truth,
he would commend their zeal, but gently instruct them to use wisdom in their management;
in which good work the Lord greatly blessed his labor to his people.

He would also give way very much to those newly called into the work of the ministry,
if they kept to sound words and doctrines, which are according to godliness,
ministering from the ability which God gives.

Thus he, with much sweetness,
continued a faithful elder until the sixty-third year of his age,
and then he was taken ill with the yellow jaundice,
and other distempers setting in together, he continued very weak all the winter,
very often expressing his willingness to submit to the will of God,
either in life or death.
He was often concerned in the time of his sickness for his children,
that they might walk in the way that is strait and narrow, and leads to eternal bliss;
telling them he had done his duty in teaching and instructing them,
as much as in him lay,
and letting them know his earnest desire that they should keep in the unity of Friends;
and that it would prove their utter ruin, if they went from it.

He would in his sickness very often be talking of his desire
that Friends might be kept in love and unity;
and so continued at times in a divine sense of God`'s goodness and sweet peace.
At one time, several friends being present, he gave to each of them suitable counsel;
and soon after said to his near friend and kinsman, Jacob Mott, then present,
with whom he had very often travelled to preach the gospel,
"`I desire you to remember my dear love to all Friends in New England;`" and further said,
he had done his day`'s work, having peace with God, and unity with his people.
And then like a composed Christian, who had fought the good fight of faith,
he took leave of his family one by one; and after some time, departed very quietly,
and doubtless is entered into that rest which is prepared for the people of God.

He was buried from the meetinghouse at Jamestown,
after there had been several testimonies borne to that truth
made manifest in this latter age of the world,
by the spirit of God, in the hearts of the sons of men,
in which this dear Friend had lived and died.

[.asterism]
'''

ISABEL GILL, wife of Joseph Gill, was born near Carlisle, in Cumberland,
in the year 1670, of honest parents, who, with most of the family,
were convinced of the blessed truth.
In her young years, about the age of twenty, she went to London,
where she lived seven years; and after her return into Cumberland,
was married at Carlisle aforesaid, in the year 1702,
and soon after went with her husband into Ireland, and settled at Dublin.

She was a loving and faithful wife,
a true helpmate both in spiritual and temporal concerns;
a tender mother to her children; a good example to her servants in plainness;
a woman of an excellent temper and good understanding,
mostly cheerful and loving in her family,
having attained to a good degree of growth in the truth, more in substance than in show;
a fervent lover of honest friends, and open-hearted to them.

Towards the latter end of her time she was much attended
with infirmity and weakness of body,
yet cheerful in her spirit, truly sympathizing with her husband under exercises;
encouraging, counseling, and helping him forward, in what she was sensible was his duty.
She often advised him to be careful to do his day`'s work in his day;
cheerfully giving him up, and putting him forward to go abroad upon truth`'s account,
even when she had need of his company at home, by reason of her weakness;
often expressing her desire never to hinder him, though his company was dear to her.
And when he was abroad she concealed her illness, lest she should draw him home too soon.

Some time before her decease, when confined to her chamber, by reason of bodily weakness,
many friends came to visit her, and often had sweet seasons with her,
the Lord`'s power and presence breaking forth,
to the tendering of both her and them together.
She often expressed a great concern for the good of others,
testifying that the Lord was angry because of pride, drunkenness, and other wickedness;
and faithfully admonished several who came to visit her,
giving counsel and advice suitable to their states and conditions,
of which she had often a clear sense, and would desire them to prepare for such a time,
meaning a dying bed.
She expressed her satisfaction with the Lord`'s dealings with her,
and the comfort and peace she enjoyed in him, often praising and glorifying him,
for his preservation and goodness to her from a child to that time,
with many sensible expressions, some whereof do follow.

She said to her husband, "`My dear, do you give me up?
Pray give me up freely to the Lord who gave me to you.
He is worthy to be submitted to; his secret hand was with us, in bringing us together,
and we felt his love and living presence at our marriage, and it is with us at this time,
and I hope will be at our parting.
Be not troubled to stay behind me, the Lord who has been near, and with us together,
will be with you, and help you, and bear you up in all exercises and difficulties,
and provide for you, if you still keep near him, and serve him,
according to his requirings:`" with more expressions to the same effect.

Being very ill, and observing her eldest daughter and another friend crying by her,
she said, "`Cry not for me,
but for yourselves;`" and pressed them several times to "`take
care and lay up something against a time of need,
and seek to be married to the Lord, and that will be a good marriage.
I see no cause to cry, or be sorrowful for me, for I am happy.`"
She often sensibly expressed that her peace was made with the Lord,
and she was not afraid, nor dismayed at death,
but was freely resigned to the Lord`'s will,
who had been her strength and support from her childhood,
and now found him near to help her over exercises,
and make her willing to leave her tender babes, and all that was dear to her,
to his providence.

A public friend, whom she loved, being in town, and having visited her in the evening,
she sent for him next morning, and having a concern upon her,
charged him to cry out against the crown of pride, and drunkenness, etc., saying,
"`The Lord has put an arrow in your hand, let it fly,
and spare not;`" with other exhortations to him of the like nature.

When some young women came to visit her, she charged them not to be high-minded,
nor give way to pride and nicety,
by reason of the riches their parents might have to give them,
which would be of no value without the blessing of the Lord;
which she advised them to seek after above all things.

At another time, when some young married women visited her,
she advised and warned them not to be nice or high-minded,
neither to deck nor adorn their children too nicely, dressing them up like pictures,
and then admiring them; for if they did so, the Lord might take them away from them;
but to keep them clean and sweet, out of nicety, and the Lord would bless them.

Some that had been of loose and ungodly conduct, who came to see her along with others,
she advised to keep under judgment; and plainly told one person that he was too high,
and had abundance yet to go through for his transgression;
and that if he did not come down lower, he would fall again.

Her distemper increasing, she grew weaker, and being often in great pain,
she was concerned to pray to the Lord for some ease,
that she might know what it was before her departure,
and that he would give her an easy passage, meaning her death.
Both which requests the Lord was graciously pleased to grant her;
for about two weeks before her death she obtained great ease, and lay pretty quietly,
without any discernible alteration, until about two minutes before she departed,
which was as one falling asleep in a quiet manner.
She died in the city of Dublin, in Ireland, the 8th of the Twelfth month, 1713.

[.asterism]
'''

DANIEL GOULD received the blessed truth about the year 1658,
and followed the Lord in the way of his requirings,
going through many and deep tribulations.
After some time a concern came upon him to visit his brethren,
William Robinson and Marmaduke Stevenson, who were under sufferings at Boston,
in New England, where they afterwards suffered martyrdom for their obedience to God,
in bearing a testimony to his blessed truth; with whom he also suffered imprisonment,
and cruel whipping, being then about the thirtieth year of his age.

After his discharge there, he retired to Rhode Island, and the Lord opened his mouth,
and made him a minister of the everlasting gospel of Christ Jesus.
In which service he labored about forty-five years,
and travelled in many parts of New England, Staten Island, Long Island, New York,
East and West Jersey, Pennsylvania, to Maryland and Virginia, several times;
and God blessed his labors, so that several were convinced,
and turned to the Lord through his ministry.

He was a man richly furnished with the gifts of the Holy Spirit; patient under exercises;
grave in behavior; pleasant and exemplary in conduct; his ministry weighty and deep,
tending to the consolation and comfort of God`'s people.
Unity of brethren was his soul`'s delight.
He endured many hardships for his faithful testimony to the blessed truth,
and was greatly capable, through his long experience,
to advise and give counsel to persons in all conditions,
and was a diligent and early comer to meetings.

His understanding and memory in his latter years had more than common brightness.
In the time of his sickness, he greatly desired and delighted in the company of Friends;
and some days before he died he said to a friend who was with him,
"`I have a desire to see some Friends,`"
(that were gone to a quarterly meeting,) inquiring if they were returned.
The Friend answered, "`They are not; we look for them every day.`"
He replied, "`I fear I shall not live to see them: but let death come when it will,
my reward is sure`"

He often expressed great satisfaction and resignation in the will of the Lord;
and with much patience he endured his long and tedious sickness,
although at times attended with sharp pains.
On the 26th of the First month, 1716, he died in the Lord,
at his own house in Rhode Island, aged about ninety-one years.
A minister about forty-five years.

[.asterism]
'''

JOHN BOWSTEAD was born at Aglionby, near Carlisle, in Cumberland,
the 30th of the Second month, in the year 1659,
and was convinced of the blessed truth when young; and in a few years after,
he received a gift of the ministry, in which he improved both at home and abroad.
He labored in the gospel, and travelled from north to south,
as also into Scotland and Ireland, where he not only visited Friends,
but had meetings among other people,
and several were turned to the Lord through his ministry.
As he preached Christ in word and doctrine,
he also adorned the same in an exemplary life and conduct, plainness and gravity;
was faithful to our ancient testimony against the great oppression of tithes,
suffered the spoiling of his goods patiently,
and assisted others when they were under persecution for conscience sake,
and went with them before magistrates.

He duly attended meetings for the worship of God,
and had his children and family with him, and was a good example to them.
He was ready to do good to all,
and his heart and house were open to entertain his friends freely.

In his ministry, his doctrine was plain and powerful, and he divided the word aright,
preaching the gospel freely, and was zealous in contending for the faith.
He loved good order, promoted the same in the church,
and labored fervently for its support.
He was a universal lover of faithful Friends, an encourager of the weak,
and sought the good of his neighbors and countrymen, and was well beloved.

He was tender over such as were under exercise; he loved liberality,
and hated covetousness; was diligent in his travels to visit the churches,
and careful when at home for the support of his family.
He had much exercise with wrong spirits, against whom he bore a faithful testimony.

The time of his sickness was short; and though it lay heavily upon him,
he retained his inward and outward senses clear all along,
and settled his affairs in the world, and was in a sweet frame of mind,
and uttered such heavenly expressions, that the apothecary who attended him,
though not of our profession, declared that he had been with people of several ranks,
and never heard the like before.

Several friends visiting him, he said,
"`Oh! how easy am I in the company of clean-spirited friends;`"
with many other sensible and weighty expressions.

Perceiving the time of his departure drew near, he desired to see his wife,
who then lay weak of a fever, who was brought to him, and they took leave one of another;
and he said to them about him, he was for leaving them; and in a little time,
in a sweet frame of spirit, departed this life the 30th of the Second month, 1716.

He was buried in Friends`' burying-place at Scotby,
on the 2nd of the Third month following,
where many friends and others accompanied his body to the grave,
where he was decently interred.
Aged fifty-seven years.
A minister thirty-five years.

[.asterism]
'''

SARAH ELKINGTON, wife of Thomas Elkington, of Epping, in the county of Essex,
was a woman of a blameless conduct, delighting to retire often in secret,
to seek acquaintance and favor with the Lord.
That she might increase in the same, she seldom missed attending their week-day meeting,
though sometimes very small, yet kept to it constantly, and was diligent therein,
to keep her mind under a right exercise,
which she would often say required strict watchfulness.
She was often inward and retired in her mind to the Lord,
and was concerned to have truly in possession that which she professed,
as did more manifestly appear when she came towards
the conclusion of her time in this world,
which was occasioned by a cough and consumption, that attended her some time.

It increased very fast upon her in the beginning of the Eleventh month, 1717;
so that she was apprehensive her end drew near,
but said that her peace was made with the Lord,
and that through his great mercy he had enabled her so to walk,
that now she had true contentment and satisfaction,
in that she had been faithful according to her measure of grace received.
Not many days before her departure out of this world,
she said her heart was filled with praises to the Lord;
but her condition of body was such,
that she could not express the same as she should have done, had she but strength.
Speaking to her husband, she said, "`My dear, do not mourn so for me.
I am but going the common way of all flesh.
I am not afraid of death; for, seeing it is the will of the Lord,
I am thankful that my will is subjected to his.
His time is the best time; and this I can say, my peace and enjoyment are such,
that I had now rather die than live.`"

Several times, as she found herself enabled,
she gave good advice to her own and her husband`'s children,
advising them to obey their father, and remember his advice,
and to be careful to walk humbly before the Lord, and truly to fear him,
and then it would be well with them here and hereafter.

This, with much more that she at several times uttered, was spoken with such awfulness,
and in a sweet, tender frame of spirit,
that it tendered the hearts of those she spoke to; and drawing near her end,
as her children came to see her, she took her solemn leave of them,
blessing them in the name of the Lord.
Then, lying some time still and retired in her mind, she said that she felt no pain,
neither was she sick, but very easy, and also well contented,
and esteemed it a very high favor that the Lord dealt so kindly by her,
that she should be so free from pain of body, and clear from trouble of mind.
In the sense of this, and of the overflowings of the goodness of God,
she said her heart was tendered, and that tears of joy flowed from her eyes.
And further added, it was now her great comfort, that in the past time of her life,
she had, through the grace of God,
been careful to order her conduct according to the holy profession she made;
that she with trouble had observed too great a lack of that among many,
who gave themselves so great a liberty to speak at large, and unwarrantably: which,
she said, she had been careful to avoid;
and now she saw the advantage and profit of such self-denial and watchfulness.

Another time, lying in a still, retired frame of mind,
she broke forth in praises and thanksgivings to the Lord, saying, "`Oh!
Lord, you have been good to my soul:
you are the everlasting fountain of unspeakable goodness.`"
Three or four of her children being by her bedside, she said, "`Oh! dear children,
mind and dwell in the fear of the Lord, and he will manifest his goodness to you.
Mind, I desire you, the words of your dying mother,
for the Lord has been good to my soul many a time, praises be to his holy name.
O my soul praise the Lord.
He deals now kindly by me, for I am very easy.
I seem at times to doze away my life; if it goes away so it will be very easy.
Were I capable of body, I would write something to leave behind me,
of my experience concerning the dealings of the Lord with me,
and what a brave thing it is to fear and serve him, and what I now enjoy.`"

Her husband telling her that something of what she had said was taken down in writing,
which he believed would be of service when she was gone, she seemed to be pleased,
and continued very easy, often saying her eye was to the Lord;
hoping he would enable her patiently to go through
what might yet be permitted to come upon her.
She signified what a brave thing it was to trust in the Lord,
and constantly to watch against the enemy; and said,
"`I now rejoice in the goodness of the Lord, for he is with me;
and although I am now coming to hard work, for to die is not an easy thing,
yet I am easy;`" and laying her dying hands upon her breast, said,
"`I have peace and true contentment here.`"

She further added about half an hour before she departed, to those about her,
"`This is hard work that I am in, but I am easy; my mind is easy.
I have peace at heart, the Lord is near me, and my time now will be short.`"
Desiring to take her last leave of her husband, she said, "`My dear,
a little time will now accomplish my labor; farewell, dearly.`"
Then desiring to know what time of the night it was, which was told her,
she lay very still, breathing to the Lord:
and as she had prayed that she might have an easy passage, so it was granted;
for in about half an hour she breathed shorter and shorter,
and went away as if she had fallen into natural sleep.

She departed in great quietness, about the second hour in the morning,
on the 3rd day of the First month, 1717, in about the forty-fifth year of her age.
