== Chapter 11

[.chapter-synopsis]
* Thomas Busbey
* Joshua Brook
* Rebecca Jacob
* Frances Griffitts
* Jeremiah Waring
* Ellen Bewley
* Mary Bewley
* Alexander Hopwood

THOMAS BUSBEY, of Banbury, in Oxfordshire,
was one whom the Lord endued with the knowledge of the truth in his youthful days,
to which, through the operation of his holy spirit,
he was made willing to give up in faithful obedience.
In the time of his last illness,
through the renewed visitations and fresh influences of divine love,
he dropped many precious and comfortable expressions.

In a short time his distemper increased so upon him as to confine him to the house.
On a First-day some Friends came to visit him,
and sitting together in a weighty frame of mind, he said,
'`If it please the Lord to take me away by this illness, I am not afraid to die,
blessed be the name of the Lord my God, whom I have loved and served from my young years,
and now in this low condition he has not forsaken me.
All glory and honor be given to him, and the dear Lamb that sits with him on the throne,
world without end.
Though I have near and dear things to leave behind me, as wife and children,
to whom I would have been as a shepherd a little longer, if the Lord had seen fit,
but his will be done.
I shall leave and commit them to him,
who has been as a tender father to me from the time
that he first visited my soul unto this day:
oh! what shall I say of his goodness and matchless love.`'

At another time, to a friend that came to visit him,
after having spoken a great deal of the love and
goodness of the Lord to him in the time of his youth,
in turning his feet from the paths of vanity into
the narrow way that leads to eternal rest,
he said, '`Oh! that our young friends, who are growing up,
would come to seek the Lord in their early years.
He would be assuredly found of them; my soul is a witness of what I now speak.
When I was but a lad, I had secret desires after him,
insomuch that I thought I could be content to mourn out my days in a cave of the earth,
so that I might have an assurance of a dwelling with him,
when time here should be no more.
So strong were the desires that the Lord had raised in me,
that nothing short of this would satisfy, which caused me many times, I might say years,
to go mourning and seeking the Lord,
till at length he was pleased to appear by his in-speaking
word in the secret of my heart,
saying, You are mine, wait you on me and I will protect you.
Oh! how has he made good his promise; yes, he has done more for me,
both inwardly and outwardly, than at any time ever entered my heart to desire or expect;
the which causes adoration and praises to ascend from me,
who am but as a worm before him.`'

At another time, he being as it were overcome by the love of God,
and in a tender frame of mind, said, '`One +++[+++taste]
of my Father`'s love is better than all the doctor`'s cordials.
Oh! it is this that supports my drooping spirits.
I thank you, O Father, that you have not forgotten me in this low condition.`'
One time speaking to some young friends that came to see him,
some of his expressions were these: '`Keep in the narrow way spoken of by our Savior,
Christ, in whatsoever company you may be.
Keep to an inward exercise of mind, and to the teaching of the Holy Spirit in yourselves,
that you may be thereby prepared,
and ready for whatsoever work and service the Lord may be pleased to call you to;
for he works in whom he pleases, and how he pleases.
Time will fail, and strength will fail; therefore improve your time,
and prepare yourselves while you have time.
My dear friends, my love is to you, and remember my love to friends,
for I shall depart hence before it be long.
Blessed be the Lord, I am strengthened in spirit beyond what I expected.`'
Some Friends of Ireland, in their journey to the yearly meeting at London,
gave him a visit, and the Lord was pleased to favor them,
a little before they took leave of him,
with a degree of divine sweetness and harmony upon their spirits,
by which they were so reached and tendered,
that they declared their great comfort and satisfaction in their visit.

At another time, in sweet composure of mind, speaking to his wife, he said, '`Oh! my dear,
what manner of love is this, wherewith the Lord has loved my soul, that I am, as it were,
overcome therewith, so that I am ready to shout aloud for joy,
and to go beyond my strength,
for I see no end of praising him for his many mercies and visitations of love?
Surely it is as a brook by the way, to confirm my faith and hope in him,
which is as an anchor sure and steadfast,
that all tempests and contrary winds have never been able to shake or overturn,
because it was built upon the invincible rock,
the rock of ages and foundation of all the righteous.
My soul shall sing eternal praises unto it,
because I have tasted of the streams that issue therefrom,
at this time as well as at many other times.
Glory be to God and the Lamb forever and forevermore.`'
Speaking of that power whereby the soul is renewed and made alive to God; '`Oh!`' said he,
'`that we may all keep to it,
it is this which will give us the victory over the
many things that would draw away our minds from him,
and from a faithful dependence upon him.
My soul is a witness for the pure God, that if we keep to the power, in that,
we are made more than conquerors by him who has loved us,
and shed his most precious blood for us.
Though I am weak, and my outward man decays, yet my faith and hope are renewed in him,
so that I know whose I am, and whom I serve,
and nothing shall be able to pluck me out of his hands,
for it is by this power I have been upheld to this day.
Though the archers shot at me, my bow abode in strength,
so that with the patriarch I can say,
the arms of my hands have been made strong by the hands of the mighty God of Jacob,
who has preserved me; endless glory be given to him.`'

The 25th day of the Seventh month, 1726, a friend,
who lived at some distance came to see him, and asking him how he was, he answered,
'`All is well, except the poor body, and that is sorely afflicted,
but the Lord has graciously supported me under it, beyond expectation.`'
After having been a little in silence, he broke forth into prayer,
and returned praises to the Lord for his wonderful lovingkindness,
in affording him his comforting presence in a time of great exercises,
and his strengthening power and supporting arm under such
great pains and long and sore afflictions of body,
with which he was attended.

The 27th of the aforesaid month, some friends who had tarried all night,
in the morning asked him how he was.
He answered, '`I was in hopes I was going once to-night;`' (for he had had a very ill fit,
in which they who were with him thought he was departing.) '`I am very desirous
to be released from this great affliction of body I am under,
if it please the Lord; but his will be done.`'
About two hours after, the said friends being about to take their leave of him, he,
though very weak, being then near his end, raised himself up in the bed,
strengthening him beyond expectation,
and in the aboundings of divine goodness supplicated the Lord to this effect:
that the Lord would be pleased to strengthen and uphold all the weak,
and comfort all the afflicted, whether in body or mind; and that the Lord,
according to his heavenly will, and divine wisdom,
would raise up a powerful and living ministry of the young people among friends;
and that he would graciously vouchsafe of his favor to his people,
to endue the present ministry with a larger demonstration of the spirit,
so that nothing might appear among them but the pure streams and current of life;
that those who were lately convinced, belonging to Eadon meeting, might be preserved,
and attain to an establishment in the truth, and persevere to the end;
and that the youth among us in general,
might be favored with a fresh visitation of the love of God,
to draw their affections from the pleasures and vain fashions of the world,
to an earnest seeking of the Lord,
and thereby to a possession and enjoyment in themselves
of the power and excellency of truth,
which will afford them comfort in a time of trouble and afflictions,
and strength under exercises and weakness, and peace in an hour when all the world,
and the glory thereof, will stand them in no stead.

Towards his end, being weak in bed, a friend came to visit him,
and speaking of the state of things,
and the liberty some of the professors of truth took to revile the innocent, he said,
'`Dear friend, be not discouraged.
Though there is darkness in Egypt, there is light in Goshen; yes,
it is such darkness as may be felt.
My soul has travailed under the weight of it many times; and though it is so,
and has been so, the Lord will have regard to his own seed.
He knows who they are, and where they are.
I could say a great deal, but am much spent,
having had a large morning sacrifice with some of my friends that are gone away today.
Oh! glory to God!
Do not distrust his goodness, he never fails those who have a true dependence upon him;
my soul is a living witness of it.`'
And farther said, '`Although I have been under so long and sore affliction of body,
yet the enemy has never been allowed to tempt me to despair,
or doubt of my future happiness.`'

He left it as a charge with his family, that nothing of mourning apparel,
or anything that had the least appearance thereof,
might be worn on the account of him after his decease.
Many more excellent sayings which he delivered, worthy of memorial,
might have been here inserted for the benefit and encouragement of others,
to follow the ways of piety and virtue,
had it been possible to retain them exactly in mind.
He departed this life the 13th day of the Eighth month, 1726, aged about sixty years,
and was buried in Friends`' burying-ground at Eadon, in Northamptonshire,
the 19th of the same month;
and his funeral was attended by a large company of friends and neighbors.

[.asterism]
'''

JOSHUA BROOK, son of Richard Brook, and Martha, his wife, of Raw, near Huddersfield,
in Yorkshire, was born the 17th day of the Twelfth month, 1701,
and educated in the way of truth, as professed by the people called Quakers.
He was inclinable to learning from his childhood, and as he grew to riper years,
he pursued it with more diligence.
When others, equal with him in age, were spending their time in vanity and play,
he would often be writing, or reading the Holy Scriptures, and some other books,
in which he much delighted;
which was a means of preserving him from the many foolish
and hurtful vanities youth are too much inclined to.

But afterwards, falling into the company of some who pretended to great learning,
he was led to be a great admirer of it, so that his mind was too much taken up with it,
and diverted from a due regard to that inward principle of light and grace in himself.
Afterwards, the manifestation of that divine light shining clearly in his heart,
showed him his neglect of minding that inward teacher;
and then he came to see he must begin to learn anew,
and was brought under great exercise and inward trouble,
insomuch that he was scarcely fit for conversation, but very much desired to be alone.
The company of those who had been his companions became unpleasant to him;
and continuing in a strict course of life,
he was very zealous and diligent in going to meetings, and much retired in them.
His care was such, not to neglect that great duty of the public worship of God,
that long after his infirmity came upon him, which was lameness,
and continued to his end, he would go with his staff and crutch to meetings,
though obliged to rest by the way.
When his infirmity increased upon him that he was not able to walk,
he would ride to meetings as long as he had strength of body to bear it;
but growing weak, he was obliged to stay at home, and in process of time to keep his bed,
when many lively and heavenly expressions dropped from him.

After a long and sore affliction for about four years with his lameness,
which began first on his knee and broke on his leg, and afterwards in his thigh,
a dropsy came on, which proved mortal.
It began about seven months before his end, and grew gradually until he was very big,
and could not lie down in his bed, but sat up in it,
not being able to turn himself without assistance for about seven weeks before his departure.
And although in the time of his long illness his affliction was great and hard to bear,
yet it was much overbalanced by that heavenly love
and inward refreshment which he was favored with.
His patient conduct and the many seasonable expressions
that dropped from him under this heavy exercise,
had great influence,
and were very affecting to all ranks of people that came to visit him, which were many.
How lively he was in his spirit,
and innocent and sweet in his conversation while on his deathbed,
it is to be hoped will not be forgotten by those that visited him.

He often gave good advice to the youth, saying,
'`Though you are young and in the flower of your age, yet think not yourselves secure.
You may see a pregnant example in me,
who was once of as healthful a constitution as most of you.
How soon that overruling hand may bring you into the same condition, you know not.`'
Warning them to give all diligence to make their calling and election sure,
that when pale death looked them in the face, they might not be surprised,
but being fitly prepared, embrace it with rejoicing.

One First-day morning, before the meeting, which was held at his father`'s house that day,
his brother went to see him, and perceiving him dejected in mind,
asked him if he was not under some exercise;`'Yes, '`said he,
'`The Lord is withdrawn from me,
so that I do not feel that comfort and satisfaction as heretofore.`'
His brother replied to this effect: '`Be not discouraged, the Lord is a merciful God,
he may try, but will not leave any that put their trust in him.`'
After the meeting was over many friends went to his bedside,
and several lively and powerful expressions were uttered by him,
with which many were reached, and some young friends, his companions,
were tenderly affected.
His brother going to him, he said, '`The Lord is come again.
I have had a sore day of exercise, with most part of last night,
but now the Lord is returned again, for which I bless his holy name.`'

Some young friends tarried with him that night, thinking him near his conclusion,
having had a sore fit the night before, and his surviving it not being expected,
of which he had a return the night following.
When he felt it come on he beckoned to each of them, and they coming near,
he took them by the hand one by one and kissed them; taking his solemn leave of them.
They remained by his bed side expecting his departure;
but after some time he recovered out of that fainting fit, and looking up,
said with great reverence and sedateness of mind,
'`I thought I had been near the port of eternal rest,
and would gladly have remained there, but I see my time is prolonged,
and for a while I must return again into this troublesome world;
but God will deliver me from all my exercises, blessed be his eternal name:`'
with much more to the same effect.
At another time, one of his familiar friends coming to visit him, asked him how he did;
he answered in much brokenness of spirit,
'`The Lord will in his appointed time cure me of all my maladies,
blessed be his holy name;`' with many more pious expressions to those who visited him.
At another time he said, '`The Lord has plucked my feet out of the mire and clay,
and set them upon a rock.
The Lord has delivered my soul from all unrighteousness;
there is no obstruction in my way.
Death is no terror to me; it is the most pleasant thing that ever my eyes beheld.
I would not, if I might have my health again, remain here.`'
Sometimes saying '`I see to the end of mortality, but I cannot come at it yet.`'

Henry Jackson, a Friend who had a great respect for him in the time of his health,
and often visited him in his sickness, to their comfort and inward refreshment,
the last time he came, a few days before his end, prayed by him;
after which he said in much tenderness to this effect, '`My work is almost done;
I am going to the patriarchs, prophets, and apostles,
to sing hallelujahs and praises forever and evermore.`'
Henry said, as he was coming to visit him,
it seemed to him as though the holy angels of God were waiting to receive
the word of command to conduct his soul into the mansions of glory,
and that he would have wished himself in his condition; to which he answered,
'`It will not be long before we shall meet again;`'
which took such impression on Henry`'s mind,
that soon after he told a friend, he believed it would come to pass,
for he thought his days in the world would not be many.
And about fourteen weeks after, Henry also finished his course.

His distemper growing more violent, he weakened fast; but as his outward man decayed,
his inward comfort increased,
and waiting in patience and resignation to the will of God for
the word of command from the great Disposer of all things,
in a full assurance of his soul`'s salvation, saying he should go to his everlasting rest,
to sing praises forever and evermore.
He departed this life the 13th day of the Seventh month, 1727,
in the twenty-sixth year of his age, and, it is not to be`' doubted,
is arrived where the wicked cease from troubling, and the weary are at rest.

His funeral was attended by a large number of Friends and sober neighbors;
and the aforesaid Henry Jackson being present, bore testimony to the truth,
and repeated several pious expressions which dropped from him on his dying-bed,
with which many were much affected.

[.asterism]
'''

REBECCA JACOB, wife of Isaac Jacob, of Waterford, in Ireland,
daughter of William Penrose and Margaret his wife, of the same city,
was from her childhood of a meek and innocent behavior, and as she advanced in years,
witnessed a growth in the blessed truth,
often being favored in religious retirements with the Lord`'s tendering goodness,
whereby she was strengthened in faith to walk humbly before him.
She was an affectionate and tender friend, companion, and wife.

It pleased the Lord to visit her with a lingering
sickness about two months before her end,
in which time she was not known to repine,
but with cheerfulness of mind yielded to that affliction and weakness of body,
which increasing and her end drawing near,
she asked her mother-in-law if she thought her near departing; who replied,
she thought she was.
Then she desired to wait on the Lord, and, after some time, said,
'`I have a good and loving husband, a good mother-in-law, and lack nothing,
and never repented my coming into the family.
We have what the world can afford, but now the Lord is more to me than all.
I have had many good times alone, when no eye saw me;`' and soon after said,
'`Oh! you great Preserver of men, you have comforted my soul when alone,
and preserved me from evil,
and now I feel your good presence near me;`' then fervently
prayed to the Lord not to forsake her in the needful time,
saying, '`Oh! you holy One, be near me still.`'

She remembered her dear love to friends, and those who might enquire after her,
and calling for her brothers, tenderly advised them to fear God,
and to be dutiful to their parents, and not to grieve them.
Then prayed to the Lord for her husband, saying, '`Oh! you great Preserver of men,
bless and preserve him, I beseech you, in all his ways, in his goings out,
and in his comings in, and in all that he does, or takes in hand to do.`'
Desiring her mother to keep near her to the last, said to her,
'`The comfort of the Lord is more to me than all the world,
and that which grieves me most, is to part with my dear husband.`'
She continued to praise and supplicate the Lord,
entreating him to be near her in the needful time, meaning her passage hence,
and said she was afraid the Lord would be angry if she praised him not.
Then taking her leave of her relations and friends present,
was not heard to speak much after; only once said, '`Oh! you God of my father!
Oh! you holy One, be near me still.`'
Her speech failing from the twelfth hour till half after nine at night,
it then pleased God to put a period to her being here,
and no doubt He has taken her into his glorious rest.

She died the 3rd day of the Second month, 1728.
And the 6th day of the same,
her corpse was attended by friends and friendly neighbors to the meetinghouse,
where several testimonies were borne to the truth,
and was afterwards carried to Friends`' burying-ground and decently interred:
aged twenty-five years seven weeks, and three days.

[.asterism]
'''

FRANCES GRIFFITTS was born at Baltimore, in the county of Cork, in Ireland,
in the year 1656.
She came to`' Cork when she was very young,
where she was convinced of God`'s everlasting truth,
about the twenty-fourth year of her age,
and as she became obedient to the manifestations and dictates thereof, she grew in grace,
and in the saving knowledge of it.
About the thirty-seventh year of her age she received a gift in the ministry,
in great humility, fear, and tenderness,
wherein she was all along very exemplary and careful
not to appear without the motion of divine life,
and a necessity upon her, so that what she delivered was edifying, seasonable,
and satisfactory to friends.
She travelled in some parts of England and Wales in the service of truth;
was a woman of great sincerity, plainness, and self-denial,
very exemplary to her children and family,
for whom being frequently concerned and engaged at heart,
that the Lord would be pleased to reach unto and visit them in mercy and love,
she was favored to see her desire in some degree answered.
She was zealously concerned for the promotion of truth and righteousness,
and was a sympathizer with the afflicted in body, or mind;
a frequent visitor of the sick, and industriously concerned for the relief of the poor.

She was taken ill the 4th day of the Seventh month, 1728, and continued so for some days;
during which she lay in a sweet composed frame of mind,
bearing her sickness with great patience and resignation to the will of God.
Some friends who came to see her, at their taking leave,
desired she might be restored to us, if it were the Lord`'s will.
She answered, it was time for her to look from the world,
and it would be safe for those who were younger than she,
to do nothing against the truth, but for the truth,
and that would administer peace to them in the end.
To a relation and his wife, that asked her how she did, she replied, weak in body,
but not in mind, and that she had nothing to do then but to die; adding,
'`It is a brave thing to be chaste; chaste in our love to God;
to leave nothing to do at such a time as this.`'
The same person desired she might be restored to us again; she answered,
'`There is little likelihood of it.
However, be it as the Lord will, I am ready.
It is no surprise to me; I have been long preparing for it.
The Lord has helped me to do it;`' adding, '`I have not much to say, being weak in body,
but this short sentence I leave with you, Do nothing against the truth,
but all that you can for the truth.`'
And when the aforesaid friends were taking leave of her, she, calling her by her name,
said, '`Be faithful to what is manifested to you.
The Lord has made known his will to you, and oh! be faithful to it,
and you will do well.`'

To a friend who lived in the neighborhood, visiting her,
she said there was a short sentence which was much in her mind,
and she had recommended it to several, '`To do nothing against,
but all that you can for the truth, '`the reward of which will be great peace in the end,
and that she now witnessed, which was more to her than all the world; adding,
'`You are a pretty knot of Friends in this neighborhood,
and I would have you to be preachers.
I do not mean in words or apparel only, but also in life and conduct.`'
To her daughter, Elizabeth Taylor, and another Friend, who were sitting by her, she said,
'`There is a short sentence which has lived in my mind most part of this night,
Have salt in yourselves,
and be at peace one with another;`' with many other sweet
and comfortable expressions which were not perfectly remembered,
signifying her inward peace and satisfaction.
She lived to a good old age, and was taken away, like a shock of corn fully ripe,
the 10th day of the Seventh month, 1728, in the seventy-second year of her age; and,
we are satisfied, died in the Lord,
and is entered into that rest prepared for the righteous.

[.asterism]
'''

JEREMIAH WARING, son of Henry Waring, was born at Hayly, in the parish of Witney,
and county of Oxford, in the year 1652.
While very young, he had the fear of God so impressed on his heart,
that he was led out of many childish vanities and diversions that others,
his equals and contemporaries, were in the practice of;
and by a sober conduct gave early indications of being under the
operation of that power which prepares for the service of God.
As his mind became more and more enlightened by the light of life,
he grew dissatisfied with various ceremonies, customs,
and usages of the church of England, into which he had been initiated.
Hence he was led, while an apprentice in London,
to seek carefully after a people whose doctrines were purely apostolic, and whose lives,
like the primitive Christians, were full of piety and good works.
After having, with a religious, seeking mind,
tried several other professions without finding among them the desired satisfaction,
his unwearied and commendable search after truth at length
led him to a meeting of the people called Quakers,
where the testimonies delivered that day, cooperating with the spirit of God in himself,
he embraced their doctrines with joy and gladness of heart,
and soon became thoroughly convinced of the blessed truth,
which broke in upon his understanding with demonstration and power,
and dispelled the many doubts,
fears and troubles that had heretofore surrounded his mind.

About two years after this, as we judge, being out of his apprenticeship,
he received a dispensation of the gospel to preach to others,
and though in the discharge of his duty he twice suffered imprisonment
in London with others of the then afflicted people of God,
yet he was no ways discouraged thereby, but, as soon as liberty was granted him,
continued visiting the meetings there and thereaway,
exhorting friends to be faithful to the discoveries
of his will which God had made in their souls,
and to stand immoveable for his name and truth on earth.

About the year 1681,
he visited the meetings that were settled near his native place in Oxfordshire,
where his testimony was well received, many having been lately convinced in those parts.
Among these was Mary, the daughter of Henry Wheeler, of Witney, a modest, discreet,
religious young woman, with whom he contracted an honorable intimacy,
and at length obtained her in marriage.

They settled first at Croydon, in Surry, and not long after removed to Ensham,
in Oxfordshire, and at last, about the year 1685, to Witney,
where the Lord was pleased to bless them with many temporal and spiritual blessings,
which enabled them to open their hearts and house to entertain friends,
and to contribute to the necessities of others in distress.
And as he was often engaged abroad in the discharge
of his duty to God and the churches round about,
the conduct and diligence of his wife in their temporal affairs,
rendered his absence very little inconvenient to his family and business.
Inspired with the hope of sharing in the reward of his labors, she spared no pains,
and grudged nothing she could do, to render the benefit thereof as diffusive as possible,
and her endeavors, she used to think, were blessed the more,
the more he was given up to the service of truth,
in which he was indeed an unwearied laborer,
even when old age and infirmity of body might have pleaded his excuse.

He was a minister of the New Testament,
and diligently labored according to the degree of the gift bestowed on him.
His ministry was plain and instructive, and according to the measure of it,
tended to convince the understandings of the ignorant,
to the reformation of those who obeyed not the gospel,
and to the confirming the feeble-minded, and the refreshment of the drooping soul.

For the weak and hindermost of the flock he had a tender regard,
that they might come forward;
and that those meetings might be visited to which no public friend belonged,
rather than too many to go to one meeting at the same time.
He would often say, he went not out at the invitation of others,
except to marriages and burials, but as he found drawings in his own mind,
which have at times engaged him to travel much in this nation,
but more especially in his own and adjacent counties.
He was generally well received, not only for this his labor in the ministry,
but also for his cheerful, free,
and easy behavior in the families where his lot was cast.

He was a zealous promoter of brotherly love and unity,
and where any difference had arisen in families,
would endeavor to reconcile the parties by visiting and treating
with them in a manner becoming a minister of the gospel of peace,
whose labor of love in this respect was generally well accepted,
and doubtless by some to their no small advantage.

His company was sought after by the sick and distressed,
to whom he had frequently a word of advice suitable to their state and condition.
His service in meetings of discipline was too considerable to be wholly omitted here,
or easily forgotten by those who knew it.
Being an elder in the church, he was concerned that the flock of God might be fed,
and took the oversight thereof; not by constraint, but willingly; not for filthy lucre,
but of a ready mind; not as a lord over God`'s heritage, but as an example to the flock.

About three months before his death,
it pleased God to remove hence his dear and loving wife,
after they had lived together above forty-six years,
of whose virtue it may not be amiss to give the following short account.

She was a kind and faithful wife, frugal and industrious, but not covetous.
A mother tenderly affectionate and evenhanded, shining in example; a neighbor peaceable,
obliging, and beneficent, of good report; and it may be said of her,
she was a mother in the church: having brought up children, lodged strangers,
relieved the afflicted, and was diligent in good works.

She departed this life in great peace, in unity with friends,
and in full assurance of an inheritance with the saints in light,
saying on her deathbed, she had done her day`'s work in the day time.
It were easy to enlarge on their virtues, both public and private,
but to avoid prolixity, I shall hasten to make some mention of his last illness,
which seized him the 14th of the Eleventh month, 1729-30,
being the morrow after his return from visiting Stow meeting, and continued about a week,
in which time having some intervals of ease,
he spoke many sweet and heavenly sentences to his children,
and those that came to see him,
among which the following few to his children are remembered.

'`Dear children, when your mother and I came together, it was in the fear of God.
We had but little of this world, yet we were content, and he made that little sufficient.
Our hearts were always open, and our house too, to receive friends,
and we never thought we had the less,
but on the contrary believed we were blessed the more;
for we experienced that saying verified,
They who seek the Lord shall not lack any good thing.
Oh! he is a good and a gracious God.
If you keep to truth and love him, he will never leave you nor forsake you.`'

His daughter speaking to him when he thought he had been alone, he said, '`Are you there?
I felt the love of God so strong upon my heart, I have been supplicating his name,
and I have freely offered up myself to his disposal, to do which way it pleases him.
He can bring down to the grave, and he can raise up again; his will be done.
I had once a desire, with submission, to have visited two or three meetings more,
observing in my last journeys how thin the elders everywhere appeared,
and how religion appeared to be at a low ebb.
Yet the principle of truth must prevail; for the Lord has promised,
he will give his Son the heathen for his inheritance,
and the uttermost parts of the earth for his possession.
And though we see but little of this yet, I shall die, as several elders have before me,
in the faith of it.
Abraham saw but little of that large promise made
to him of multiplying his seed as the stars of heaven,
and as the sand upon the sea shore.`'

Being asked how he did, he said, '`I had a comfortable time both in body and mind,
and have been looking back to my youth, reviewing the narrow way that leads to life;
remembering how our ancient friends used but few words,
and lived in love one with another.
And as it was in the beginning, so it must be again.
But now how many are there who love and take a delight in backbiting, detracting,
and exposing the failures of one another,
and their conversation too often turns upon modes and forms of dress,
things too mean for a true Christian spirit.`'

His children mentioning what a loss it would be to part with such dear and tender parents,
he said, '`We have lived to a good old age, and the Lord has never forsaken us,
and if you cleave to him, he will never depart from you.`'

'`And you, my grandchildren, I caution you against reading profane and idle books,
but read the holy Scriptures, and regard there the precious promises of Christ.`'
After having taken something, he said, '`This will not do.
This poor old house will not do, but I have a new house eternal in the heavens,
where is no pain, no sorrow; where all tears are wiped away.
No need of the light of the sun, nor of the moon to shine in it;
for the glory of God and the Lamb is the light thereof.`'

Mention being made of the Lord`'s rewarding him for his labor and service in the church,
he said, '`We are poor empty creatures, we can merit nothing.
All we have we receive from him, and all we do is but our reasonable duty.
The Lord has no need of us, for he is altogether glorious and happy in himself;
but we have need of him.`'

Another time, when he could take no rest, he said,
'`Sweet Lord! ease your servant for his sake, who loved me from my youth upward.`'

Recovering out of a violent fit of pain, he cried, O Lord,
your will be done! your will be done! your will be done!
You have been with me all my life long; oh! be with me now in these my dying moments,
and with my children and grandchildren, that so we may meet in your heavenly habitation,
where we shall never part more.
Oh! you Shepherd and Keeper of Israel, who neither slumbers nor sleeps,
into your everlasting arms of mercy do I commit them with my own soul.
I sought you in my tender years, and you were found of me,
and have been with me till this very day.
You have cast all my weaknesses behind your back,
where they shall never be remembered more;
and have many times given me a full assurance of
a resting place with you forever and ever.`'

He departed this life the 21st of the Eleventh month,
1729-30. And on the 24th of the same, his corpse,
accompanied by a great many friends from several parts of the county,
was decently interred at Friends`' burying-place in Witney,
after a meeting held on the occasion,
wherein the power and presence of the Almighty was eminently felt,
tendering the hearts of many,
and sealing upon their spirits that he is entered
into that rest which remains for the people of God,
which rest is glorious.
Aged seventy-seven, and a minister nearly fifty years.

[.asterism]
'''

ELLEN BEWLEY, wife of Daniel Bewley, of the city of Dublin, in Ireland,
and daughter of Joseph Inman and Elizabeth his wife, of the said city,
being religiously inclined from her childhood,
was concerned not only in meetings for the worship of Almighty God,
but also at other times, to wait to feel the incomes of that divine power,
which as it is given way to, cleanses the heart,
and nourishes up the soul unto life eternal.
She would often repeat that saying of our blessed Lord and Savior Jesus Christ, Matt. 22:12.
"`Friend, how came you in here, not having a wedding garment?`"
Showing thereby, that being only called a Friend, would avail nothing,
without the wedding garment, the white linen, the saints`' righteousness.
This she was earnestly concerned for at many times, as well as in her last illness,
wherein she expressed to this effect;
that at times she enjoyed so much peace and comfort,
as she had thought mortals could scarcely have been made partakers of;
saying she was easy in her mind to die or live; being freely resigned to the Lord`'s will.

At another time, sitting with her husband and children,
she said they were happy who did not rest only in a name or form of religion,
but waited for the power; and often expressed her trouble for such who seemed at ease,
and satisfied barely in a form, giving way to sleepiness,
and unconcernedness in religious meetings.
She several times expressed her satisfaction in friends`' visits;
and said the Lord was very kind to her in her weakness,
in renewing his blessed presence to the comforting and strengthening of her.
She earnestly desired the Lord would enable her to bear her affliction patiently,
being willing to be dissolved, and was fully satisfied of her future happiness, saying,
'`Praises are due to the eternal God.`'
She was also earnestly concerned for her children, desiring the Lord would bless them,
and that they might walk according to truth, in humility and plainness;
saying she had rather they should die than live, except they did well;
and also desired those about her to be careful to live so as they might be fit to die.

She departed this life in great peace, in Dublin, the 8th day of the Sixth month, 1730,
and was buried in Friends`' burying-ground at Cork-street, Dublin,
the 11th day of the said month.

[.asterism]
'''

MARY BEWLEY, daughter of George Bewley and Blessing, his wife, of the city of Cork,
in Ireland, was a sober, orderly, dutiful and affectionate child to her parents, loving,
meek, and courteous in her behavior, and generally beloved by all who knew her.
She loved and kept to plainness in speech and apparel,
and rather disliked than affected finery and vain fashions.
She was of a weakly constitution,
and seemed in a declining state of health for some time before her last sickness,
which she was taken with in the Sixth month, 1730.
She recovered again so much that, at her desire to see her grandmother, Blessing Fennel,
of Youghall she was carried there the 9th day of the Seventh month; but a few days after,
her weakness and disorder returned, which continued till her death.

She was often thoughtful of her latter end, and under a close concern of mind,
with prayers to the Lord to prepare her for it,
and soon became resigned to the will of God, and grew indifferent,
and rather unwilling to take many medicines,
saying she thought it not well to take too many things, or have a dependence upon them,
or doctors.
When, at one time,
she saw her mother troubled because she did not take things thought suitable for her,
she said, '`Dear mother, be not concerned for me, for if I am to live, I take enough;
but I do not desire to live except to serve the Lord:`'
and desired she might be endued with patience to bear her affliction and sickness.
She was in a close exercise and consideration how she had spent her time,
and what she had said or done amiss;
and prayed to the Lord to pardon and pass by her offenses.
She also desired her parents and near relations about her to pray for her, saying,
'`I am so weak I think I am not able to pray for myself,`' but added, '`we must do it,`'
i.e., pray for ourselves.

The 1st day of the Eighth month, she said to her sister Hannah,
then about twelve years of age, '`My dear sister, honor your father and mother,
and do not give way to little foolish things,
for by small things the enemy draws away the minds of poor children.
My dear, mind your dear sister`'s dying words, and do not put things off to a dying day,
and think it is time enough.`'
That evening her father came from Cork to see her,
to whom she expressed her willingness to die,
but longed for a more full assurance of the love and favor of God.
Next morning he asked her how she did; she answered, '`Very weak,
but I feel a little more comfort now.
I hope the Lord is my strength;`' and in a sensible frame of mind called on the Lord,
saying, '`Dear Lord, forgive me my sins, and teach me to pray.
Lord have mercy on me; my Savior have mercy on me.
Take me, dear Lord, if you please.
Draw me, dear Lord, with the cords of your love;`' with more sensible words,
but her breath failing,
she desired those present might pray to the Lord to make her passage easy.

The doctor one day came, and asked her how she did; she said, '`I am weak,
but the Lord is strong, and on him alone is my dependence.`'
To one of her relations and intimates, about her own age, who came to see her,
first kissing her, she said, '`Dear cousin, I have always loved you, and do so still,
and I believe you are the same to me.
Dear cousin, we are going to part; remember your latter end, and take care of the world;
do not mind the things of it.`'
The 3rd day of the Eighth month she called for her father and mother,
and told them of her weakness of body and exercise of mind,
and how busy her soul`'s enemy was to put thoughts into her mind to disturb her.
She prayed to the Lord to strengthen her,
and also expressed the dearness of her love and affection to them,
for their care over her in keeping her from sundry things which too many run into.
She also said, she formerly seemed to rest satisfied with her education,
but when she grew more in years and understanding, she found that not sufficient;
and then the fear of the Lord, and to live therein,
was what she desired more than the things of this world.

At another time,
she desired her grandmother would pray to the Lord to take her to himself;
and spoke of the temptations of the enemy, and how strongly she was beset thereby.
Her grandmother spoke encouragingly to her, bidding her not to believe the enemy,
who often besets those who are near the Lord.
The child answered, I am very weak, and can do nothing for myself,
but it is the Lord that does all for me;`' adding,
'`Oh! the Lord has been very merciful to me, and is so still.`'
Being filled with a sense of his love, she said, '`How sweet is the love of God to my soul.
Oh! that I could praise him enough for his love and mercy.
Oh! if the love of God is so sweet now, what will it be when I get fully to it.
Oh! that I was with you now, dear Lord; take me into your arms,
dear Lord;`' and so went on praising the Lord, and said,
'`I do not now wonder to have heard so many praising the Lord,
for he is worthy of more praise than I have strength to give him.`'
Afterwards, finding withdrawings of the love of God,
she was under a fresh exercise on that account, and prayed to the Lord to be near her,
and to lift up the light of his countenance upon her,
desiring to be removed where the wicked cease from troubling, and the weary are at rest.

The 4th day of the Eighth month, and First day of the week, inquiring what day it was,
she said she thought she could not have continued so long,
'`but may be I am kept the longer,
because I have too earnestly desired to be gone;`' and therefore
she desired the Lord to give her patience to wait his time,
which is the best time.
Next day she visibly changed for death, and was much spent,
having taken little nourishment for several days; and being asked to take something,
'`Oh`' said she, '`the love of God is what I desire;`' and prayed fervently for it, saying,
Dear Lord, send comfort; why will you withdraw yourself from your poor creature?
One taste of your love before I go.`'
That afternoon she desired to take her last leave of her parents, sister and brother,
and near relations, and said she thought it was better for her to do it then,
lest afterwards she should not be so fit.
And in a very sensible and endeared manner she took leave of them;
and soon after was taken with a faintness, so that it seemed as if she was passing away;
but she revived again,
and that evening the Lord was pleased graciously to satisfy her
soul with the renewed and fresh incomes of his divine love,
in a feeling sense whereof she broke forth, saying, Oh! dear Lord,
how sweet is your love and presence I No tongue can tell it but those that feel it.
Oh! praises to the Lord:
how shall I praise him enough!`' She desired those present to praise the Lord for her,
and said she believed that night she should be with her dear Savior;
and a few hours after, the pangs of death increased, which she bore with great patience,
frequently calling on the Lord while she had strength,
and about the fifth hour in the morning quietly departed this life,
the 6th day of the Eighth month, 1730, aged fifteen years and five months.

[.asterism]
'''

ALEXANDER HOPWOOD, son of Samuel Hopwood and Ann his wife, was born at Austle,
in the county of Cornwall, the 14th day of the First month, 1713.
His parents being such as feared the Lord, having an eye to his honor,
endeavored to inform his mind of the principles of truth when very young,
which had a good effect upon him;
for he was careful in his conduct to avoid those vices which too
much prevail upon the minds of many of the youth in our time.

In the year 1732 he inclined to accompany his father to London,
and they set forward the 26th day of the Second month for Bristol yearly meeting,
and from there to London.
In his journey, but more especially during his stay in the city of London,
the Lord was pleased to renew the visitation of his love to him,
and gave him to experience an increase of the knowledge of his blessed truth.

He got well home with his father the 30th day of the Fifth month,
but afterwards was much out of health at times,
and on the 1st day of the Seventh month was seized with a violent fever.
Next day, his mother being by him, he said, '`If the Lord is pleased to take me,
I am fully satisfied I shall go well, and my soul will be happy,
and have a place among the righteous.`'
The day before he departed, being in a heavenly frame of mind,
which carried him above his bodily weakness,
he broke forth in supplication unto the Lord to this effect:
'`O Lord! you that preserved Shadrach, Meshach, and Abednego, in the fiery furnace,
are able to preserve me unto the end.
O God, what shall my soul say?
I will wrestle with you like Jacob, if I pray all night.
However, if you will not make me like him, give me an evidence of favor with you;
whether I live or die, give me a place within your house.
Lord, if you are pleased to spare my life,
I will obey your commands in everything you are pleased to require of me.`'

He also said he never was guilty of any gross evil, and he was not afraid to die;
and being spent, he lay still in a sweet frame of mind.
His father, mother, sister, and others being in the room,
he looked earnestly on his father, and said.`'
Have you anything on your mind?`'
He answered, '`Yes, child;`' and kneeling down, prayed by him,
and the goodness and love of God came over all present.
The young man making melody,
seemed to have an evidence of that divine favor which
his soul had been so deeply engaged for;
and soon after said, '`O Lord, what shall my soul say?
I have not breath to praise you, O my God! but will do it as long as it lasts.`'

After a little pause, he said, I believe I must take my leave of you.`'
His mother answered, '`Do you think so, my dear?`'
He replied, '`Yes, I do; farewell, all my dear relations.
I hope we shall meet again in heaven.
Give my dear love to my dear brother,
who lay very ill of the same distemper in another room.
Looking on his sister, he said: '`Pray, dear sister, do not weep;
that will but trouble me.`'
Then he began his last farewell, saying, '`Farewell, father,`'
and kissing him several times;
also expressing himself with much love and affection to his mother; and desired,
if the Lord did not see fit to give him a longer time in this world,
he might be favored with a quick and easy passage.
The Lord, of his infinite goodness, was pleased to grant his request,
for after having spent the night pretty much in slumber, near his end said,
'`Call my dear mother that I may take my farewell of her;`' and next morning, like a lamb,
without sigh or groan, he departed this life, being the 10th day of the Seventh month,
1732, aged eighteen years, six months, and twenty-seven days:
and we doubt not is entered into that rest prepared for the righteous.

His body was carried to the meetinghouse at Austle,
where several testimonies were borne to the truth, to the satisfaction of those present;
and from there accompanied by many friends and a great number
of the inhabitants of the town to Friends`' burying-ground,
and there interred the 12th day of the aforesaid month.
