== Chapter 13

[.chapter-synopsis]
* William Blundon
* Samuel Cater
* Gilbert Thompson
* John Butcher
* George Bowles
* Christian Barclay
* George Whitehead
* Thomas Aldam
* Richard Claridge
* John Brown
* Daniel Roberts
* James Oldham
* John Fothergill
* Benjamin Kidd

WILLIAM BLUNDON was born in the parish of Kingsclear, in the county of Southampton,
in the year 1655, and educated in the way of the Church of England.
Until about the twenty-eighth year of his age,
he lived according to the course of this world,
in the reigning vanities and sinful diversions of the times,
having little regard to religion, till about that time;
being visited with a lingering illness, which brought him low,
he began to consider how he should account for his misspent time.
Whereupon he in some measure reformed and left the Established Church,
and joined with those high professors, the Presbyterians,
but did not find that satisfaction he was in the pursuit of.
The cowardliness of their pastor, who for fear of persecution left his flock,
and the lifeless profession of his hearers,
discovered to him the foundation they were upon;
yet he remained in hopes to find something more certain and substantial;
and having heard of the people called Quakers,
he inclined to go to one of their meetings,
to see if he could find what his soul longed for.

Accordingly, he went to a meeting in a right disposition of mind, in great humility,
earnestly desiring of the Lord,
that if they were a people who did in truth enjoy
the sweet influence of his love and life,
that he might then be made a partaker with them.
And his cries were answered,
for in that meeting he was made sensible of the presence of the living God,
and found his heart livingly touched and broken in a sense of the goodness of the Lord;
and '`Oh!`' he has been heard to say, '`let me never forget that day;
let me never forget the bowings down of my soul at that time.`'
We have good reason to believe he never did forget it;
for from that time forward he came constantly to Friends`' meetings, and,
by a circumspect conduct, approved himself a religious, solid, and good man; and,
as he said, through many trials within and without,
he at length arrived to solid peace of mind.

About the year 1710 he found it his duty sometimes
to bear testimony to the truth in our public meetings,
and being faithful therein, the Lord, who often chooses the mean things of this world,
enlarged his gift, and made him an acceptable preacher of glad tidings to many.
In his ministry he was very plain, severe against pride, licentiousness,
and every evil way; but tender towards those in whom were good inclinations,
wherever he found them.
And as Paul advised Timothy to rebuke those that sinned, before all,
that others might beware; so this good man did, without respect of persons,
being neither to be awed by fear, nor biased by favor.
It seemed to be the delight of his soul to deliver
the whole counsel of God as revealed to him,
that he might be clear of the blood of all men;
and though some might be ready to account him their enemy for his plain dealing,
yet he thought it his duty to warn them, whether they would hear or forbear.
But to the living among us, he was witnessed to be a son of consolation, indeed,
and a waterer of the vineyard of God.
This was his life and delight, to enjoy the life of God in his own soul,
and to recommend it to others; and as he had felt the virtue of it,
he was therefore a zealous and faithful witness to it.
This was what he labored to settle all upon,
that they might come to feel Christ by the power of his Spirit in their own hearts,
which might redeem them from all iniquity, and purify them to himself,
a peculiar people zealous of good works;
and the word of life has often been witnessed to flow through him,
to the consolation and comfort of the church.

He continued fresh, green and living to the very last, and as he often said,
the guide of his younger years was the staff of his age.
In the time of his weakness,
he advised Friends that came to see him to keep to the truth,
and to hold it in the power of it,
that they might know it to keep them clean from the evils of the world,
and from the world`'s ways, fashions and spirit.

Some weeks before his death, a Friend, of the ministry, going to visit him,
found him in a sweet frame of mind,
and he expressed his desire of death rather than life, if it were the will of God;
and said, '`I have done all that such a poor old man as I can do.
I find nothing, but I am clear of all.
I have often spread my case before the Lord with earnest breathings to him,
that he would be pleased to show me if any thing stood in my way,
if any thing in me was contrary to his will,
and I find there is nothing laid to my charge; the great God speaks peace to me,
and his pure life is with me.`'
Then applying himself to the Friend, he said, '`Dear Friend,
take care of the friendship and love of this world to which you are much exposed; and,
in your ministry to others, oh! be careful and watchful, get down low, and abide low.
Take care of selfish thoughts and of selfish wisdom,
and open not your mouth till the pure life is witnessed to arise in you,
and then you will answer and reach to the life in others,
and will enjoy peace in your own mind.
Oh! keep to the pure sense of life,
and it will keep you as it has kept me all along to this day:`'
with more words to that purpose.
His mind seemed to be quite weaned from this world, and full of divine joy and comfort,
hoping to put off a weak and feeble body, and to be clothed with immortality,
that he might no longer, as through a glass, but face to face,
see and enjoy Him whom he loved and had served,
and join the glorious company and church of the first-born above,
and there rest with saints and angels, and the spirits of the just.
The faith and approaching prospect of this, as he said, made him contemn death, yes,
made him long for it, being no king of terrors to him,
but a welcome messenger of a joyful release, a summons from mortality to immortality,
from the infirmities, pains and watchfulness of this life,
to the joys and comfort of an endless one.

He was beloved of his neighbors for his just, humble, and inoffensive life;
and in the church was a bright example of primitive simplicity and truth.
Great was his love to God, and zeal for his name,
laboring much in his own and neighboring meetings, though he never travelled much abroad,
to bring the young generation to a sense of truth,
and to encourage and establish the elders in it.
He was a heavenly-minded man; for though he was a sojourner here,
his mind and meditations were much in heaven,
so that with the apostle Paul he might well say, "`I am crucified with Christ,
nevertheless I live, yet not I but Christ lives in me,
and the life which I now live in the flesh I live by the faith of the Son of God,
who loved me and gave himself for me.`" Gal. 2:20.

He was very diligent in attending meetings,
and careful to be exemplary in going one of the first to them;
and so diligently exercised in them to retire down out of self to the springings of life,
that sleepiness, even in others, was a very great burden to him;
and it is a plain evidence of a lack of that exercise of spirit,
and sense of that divine presence, in which the great benefit of our meetings consists.
In his living he was very abstemious,
which good observation on a weak constitution led him to,
and by which his life was lengthened out to a great age.

He was, in brief, a man much devoted to God and his service, and who had,
by living under a sense of the virtue and power of the spirit of God,
gained a conquest over the world, the flesh and the devil,
and was renewed up in a good degree into the image of him that created him,
Col. 3:10; and it may be said of him, that he was a just man in his generation,
one who feared God, and eschewed evil, whose memory, as says the wise man, is blessed.

His weakness and confinement were long,
but that part of it which seemed to usher in death, but of few days`' continuance.
He was patient and sensible to the last hour, and expressed his hope that he was going.
He died with ease, as if he had fallen asleep, and was taken from us in a good old age,
and has left a sweet memorial behind him.
He departed this life the 19th day of the First month, 1740,
aged upwards of eighty-four years, and a minister about 29 years,
and was buried in Friends`' burying-ground at Baghurst the 23rd of the same month.

[.asterism]
'''

SAMUEL CATER, formerly of Littleport, in the Isle of Ely,
was convinced of the principles of truth, as held by the people called Quakers,
about the year 1655, by the ministry of James Parnel, who,
though but a youth about eighteen years of age,
was raised up powerfully to preach the gospel,
and became instrumental in settling and establishing many therein,
both by testimony and writing,
and finished his course in Colchester Castle before he reached his twentieth year,
for his testimony to the truth.

Soon after his convincement, the said Samuel Cater was excommunicated by the Baptists,
among whom he had walked; and by the records of Friends`' sufferings,
it appears he was several times imprisoned for his testimony to the truth.
With respect to his Christian progress through a long course of years,
from his convincement to his decease, no particular account appears,
but what is noted above.

About the latter end of the Seventh month, 1711, he was taken ill;
in the course of which illness he expressed himself to some friends and neighbors,
who came to visit him, to this effect: that God would have them to be saved,
and desired them to mind the grace of God that brings salvation,
or the light of Jesus Christ in their consciences that reproves for evil.
This he often repeated,
with many more such like expressions to all that came to see him in his last illness,
desiring them that were not of`' our society, not to take it ill that he spoke to them,
for it was in true love to their souls,
and that they might not put off time till strength failed,
for they would find enough to do to wrestle with the pains of the body; '`Therefore,`'
says he, '`prize your time.`'
At another time, when in great pain, he desired, that he might quietly hope,
and patiently wait for the salvation of God; for neither grace nor glory,
nor any good thing would the Lord withhold from them that walk uprightly;
often praising God that he felt the presence of his dear Son Jesus Christ,
who died on the cross for all, to fill his soul.
Again desiring, that he and his house might serve the Lord, let others do as they would;
he remarked, that Caleb said, he was four score and five years of age,
and he was as strong for war as he was forty years before; '`I am,`' says he,
'`going of four score and six,
and I am as strong for the spiritual war as I was forty years ago.`'

To his daughter Elizabeth Hawkes, he would say with great zeal on First and Fourth days,
being meeting days; '`Come, dear child, let us wait on the Lord,
that though we be absent in body, we may not be in spirit.`'
Often speaking very comfortably to his wife and daughter, saying he felt little pain,
but a difficulty of breathing; and that he was well satisfied with the will of the Lord.
If he lived, he hoped to live to the Lord; and if it was his lot to die,
he felt true satisfaction therein,
and it would be gain to him to be in his Father`'s kingdom,
to behold the glory of his Redeemer, Jesus Christ.

A friend taking leave of him, he said, '`Dear child, the Lord be with you and many more.
Mind it is an excellent blessing to feel and witness
the Ancient of days to be with his people,
without whose presence we are poor nothing creatures,
and not of ourselves able to do anything to the honor of our God.`'
Not long before his departure, his eyes being shut, he felt for his daughter`'s hand,
and said, '`Dear child, I find the man`'s words fulfilled.`'
She asking what man; he answered, '`The first Quaker that I saw.
I was at work upon such a house in the town; he looked upon me and bade me repent,
for the kingdom of heaven was at hand: and now I can say it is at hand.
Magnified be your holy name,
O Lord!`' several times expressing he felt the kingdom nigh to his soul.
The day before he died, he said, '`Now, O Lord! do my eyes see your salvation;
now let your servant depart in peace.`'
Being much spent for breath, he said, '`Lord, you who gave me breath, can take it away.
If it be your will, do so: not my will but yours be done, O Lord my God!`'

He departed this life the 19th of the Eighth month, 1711.
Aged nearly eighty-six years.

[.asterism]
'''

GILBERT THOMPSON, of Sankey, in Lancashire, was born in Sedbergh, in Yorkshire,
about the year 1658.
He was in his time a man of great use and service in the church,
and in his station of a school-master was eminently
qualified for the instruction of youth,
being endued with wisdom and skill to govern them by mild and gentle means,
laboring to find out their several dispositions,
that his application might be suitable thereto.
Being an example of humility and good conduct,
his labor for their instruction was manifest in their improvement in learning,
understanding, and conduct.
While under his care, many of them were so reached by truth,
and made like tender plants`' replenished with heavenly dew,
as gave encouragement to hope they might prove useful in due season,
which has been verified since in several.

But as it is common when truth prevails, the enemies thereof stir up war,
so by some envious persons this our friend was persecuted for keeping a school,
and carried prisoner to Lancaster castle, which he bore with Christian patience,
till discharged by due course of law.
About the forty-first year of his age, he was called to the ministry,
in which his labors were edifying,
being pure and unmixed with enticing words of man`'s wisdom.
He travelled through most parts of Great Britain and Ireland,
where his service was well accepted; his whole conduct cheerful, yet innocent,
was agreeable to the gospel.
As if sensible of his approaching conclusion,
he visited his friends in his native country, and at London,
and signified his great satisfaction therein,
saying his time drew near for his being divested of his earthly tabernacle;
which proved so, for about two weeks after his return home,
he was seized with an intermitting fever, and in about two weeks more died,
bearing his sickness with patience, saying he had done his day`'s work.
He died the 22nd of the Fourth month, 1719, at his house at Sankey,
and was buried the 25th of the same at Penketh.
Aged sixty-one years.

[.asterism]
'''

JOHN BUTCHER, of the city of London, was born of religious parents, in the Seventh month,
1666, about two weeks after the dreadful conflagration.
His father lived to a great age, dying about his eighty-eighth year,
and his mother about her sixty-eighth year; both leaving a sweet memorial behind them.

He, the said John, was by them religiously educated in the way of truth; and,
through the grace of God, early receiving it in the love thereof,
it pleased the Lord to endue him with a gift of the gospel ministry,
and to open his mouth about the fifteenth year of his age,
in a public testimony to the true light, Christ Jesus, not only in his outward, but also,
and more especially, in his inward appearance, by his grace and Holy Spirit;
and he gradually grew therein, and became an able minister, not of the letter,
but of the spirit.

He travelled into various parts of England, being well accepted therein,
laboring for the prosperity of truth, and was a lover of peace, unity and concord.
Being endued with a large portion of wisdom and understanding in the things of God,
he was enabled to speak to the states and conditions of many.
He was a peace-maker,
endeavoring to heal breaches and reconcile differences among brethren.

He retained unfeigned love to his brethren to the end of his days,
although afflicted with great weakness for some time before his death,
which impaired his memory; yet that true love continued in him,
was evident by his cheerful countenance, friendly and courteous deportment.
In a visit of some Friends, about a year before his decease,
he expressed himself very sensibly with respect to
the Lord`'s tender dealings with him all along,
and the hope he had of happiness through Christ.

George Whitehead and Gilbert Molleson visiting him,
he expressed his kind acceptance thereof,
and took it as a token of the love and mercy of God to him;
and signified the Lord`'s tender dealing with him,
and helping him since he visited him in his young years,
and that the Lord was now with him.
After remembering his dear love to Friends, as apprehensive his end drew near,
he said his way was bright and clear before him,
and that he was truly resigned to the will of the Lord.

He died at Palmer`'s Green, near Edmonton, in Middlesex, the 16th of the Ninth month,
1721, and was buried on the 21st of the same, in Friends`' burial-ground,
near Bunhillfields, after a meeting at the Bull and Mouth meetinghouse,
attended by a numerous company of Friends and friendly people;
aged about fifty-five years.

[.asterism]
'''

GEORGE BOWLES, formerly of Giles Chalfont,
within the compass of Jourdan`'s meeting in Buckinghamshire,
was convinced of truth in London, about the year 1681.
He was a man whom the Lord favored with a good understanding;
and although he had not much human learning,
yet he was eminently endued with divine gifts,
whereby he was qualified and made an able minister of the everlasting gospel;
and under the influences thereof was enabled to declare the doctrine of truth
in a living powerful testimony to that divine light which leads to salvation.
His doctrine was sound, instructive, very solid, and free from affectation,
tendering the hearts of the hearers.
He was not only serviceable in ministry,
but was eminently so in the discipline and government of the church,
in which he was frequently concerned,
and zealous that nothing might remain which would eclipse the lustre and beauty thereof;
and that all who professed the truth might walk worthy thereof.
Thus sweetly did he walk through a course of many years and when,
through bodily infirmities, rendered incapable of getting to meeting,
which was a mile from his house, he removed to High Wycombe,
that he might be near the meetinghouse.

About five days before his death, he was seized with a strong fever,
in which the Lord was pleased to be with him,
to the comfort of friends who were about him.
The evening before his end,
he was opened in spirit to speak in lamentation of the unhappy state of many,
who through unwatchfulness, and by lending an ear to the enemy,
had neglected those great privileges God in his mercy had offered them,
in order for their everlasting good; and also of the Lord`'s goodness,
declaring his love in preserving the faithful in ages past, and even down to this day,
and concluding with a sweet supplication to the Lord.

He departed this life on the 18th of the Eleventh month, 1721, and his body,
accompanied by Friends, was interred in their burial-ground at New-Jourdans,
the 22nd of the same.

[.asterism]
'''

CHRISTIAN BARCLAY, of Ury, in Scotland, widow of Robert Barclay, author of the Apology,
to whom she was married in the year 1669, and survived him thirty-two years,
was daughter of Gilbert Molleson, of Aberdeen, merchant, and Margaret his wife,
whose pious life is recorded in the preceding volume.
She was born in 1647, and by accounts preserved was religiously inclined from her youth,
and publicly embraced the testimony of truth about the sixteenth year of her age, and,
through many hardships and sufferings,
walked in a steady conduct consistent with her profession.
Her care and concern were great, that all who professed the truth might possess it;
grave, serious, and weighty in conversation, diligent in business, and fervent in spirit,
being often attended with the power and presence of divine goodness,
in which many precious opportunities of refreshment to many
present were plentifully manifested and experienced,
both in her company and under her ministry, to their great joy and comfort.

Her care and concern were great to prevent slackness or indifference in the church,
but that diligence might be used to make our calling and election sure.
Her daily concern for her children and grandchildren, that they might be preserved,
was evident to all; her care to assist the poor, and supply them with necessaries,
especially the sick, left lasting impressions of love and regard on their minds.
She was taken ill the 12th of the Ninth month, 1722,
and from that time continued in a weak state,
in which she witnessed many comfortable opportunities.
Her concern for the truth and church`'s prosperity continued with her to the last,
for sickness seemed not to alter her temper or concern:
many pious expressions dropped from her during her illness,
and he who had been with her all her life long,
blessed her with his presence to the drawing of her last breath,
which appeared to be in great peace and quietness, the 14th of the Twelfth month, 1722,
aged seventy-six years.

[.asterism]
'''

GEORGE WHITEHEAD, of the city of London, was one who,
in the first breaking forth of truth in this nation,
as professed by the people called Quakers,
was raised up in his very young years to bear testimony thereto,
and through laborious and exercising travail became instrumental
in the first planting thereof about the city of Norwich,
and parts adjacent.
Having been conducted through a long course of years unspotted to his conclusion,
for the encouragement of all who may read this account,
the following extract from the testimony of Devonshire-house
monthly meeting concerning him,
of which he was a very serviceable member for about fifty years,
is thought worthy a place in these memoirs.

[.embedded-content-document.testimony]
--

He was born at Sun-big, in the parish of Orton, in the county of Westmoreland,
about the year 1636, of honest parents, who gave him education in grammar learning.

At or about the seventeenth year of his age, when friends, by the mighty power of God,
were gathered to be a people, the Lord was pleased to visit him,
and by the testimony of truth, he was reached to,
and convinced of the necessity of an inward and spiritual
work to be known and wrought upon the souls of men;
and of the emptiness of outward show and formality in religion.
In the year 1654, and the eighteenth year of his age,
the Lord sent him forth to preach the everlasting gospel in life and power;
and having passed through York, Lincoln, and Cambridge, traveling on foot,
had some service in his journey.
He came while a youth into Norfolk and Suffolk,
where he visited some few meetings of Friends and sober professors; at one of which,
nearly the whole meeting was convinced by the mighty power of God,
through his lively and piercing testimony and prayer.

He continued some months in Norfolk, and about Norwich, where having meetings,
he preached the everlasting gospel, and thereby turned many from darkness to light,
and from the power of sin and Satan, unto God and his power;
that people might not continue in empty forms and shadows,
but come to the life and substance of true religion; and to know Christ,
their true teacher and leader.
Great was his service, labor, and travel in those counties, whereby many were reached to,
convinced of, and established in the blessed truth;
and some raised up to bear a public testimony thereunto.
He suffered great opposition, hardships, long and sore imprisonments,
and severe whipping for his testimony to the truth, in those his tender years,
'`as by his journal of more than six hundred pages,
wherein many of his services and travels throughout
most parts of this nation are largely related,
will appear.

He was one whom the Lord had fitly qualified and prepared,
by his divine power and Holy Spirit, for that work whereunto he was called,
and whereby he was made an able minister of the gospel.
He was a large experiencer of the work of God,
and deep mysteries of the heavenly kingdom,
and was frequently opened in meetings to declare of,
and unfold the same in the clear demonstration of the spirit and power,
dividing the word aright,
to the opening and convincing the understandings of many
who were unacquainted with the way and work of truth,
and to the comforting, confirming, and establishing,
of the people and children of the Lord, in their journey and travel towards Zion.

He was not only a zealous contender for, and asserter of,
the true faith and doctrine of our Lord and Savior Jesus Christ,
in a sound and intelligible testimony,
but also was valiant and skillful in the defense thereof,
against adversaries and opposers of the same; and one,
who through a long course of many days,
was careful to adorn the doctrine of our holy profession,
by a circumspect life and godly conduct, wherein the fruits of the spirit, namely, love,
joy, peace, long-suffering, gentleness, goodness, faith, meekness, and temperance,
did eminently shine forth through him, to the praise and glory of God.

Being thus qualified, and of a meek and peaceable disposition,
he was had in good esteem among most sorts of people that were acquainted with him;
which tended much to the opening his way in his public service for truth,
and frequent solicitations of the king and parliament, bishops,
and great men in his time,
for the relief and release of his suffering friends and brethren,
under sore persecutions and hard imprisonments, and for liberty of conscience,
and also for relief in case of oaths.
In which labor of love and eminent services, among other brethren,
this our dear friend was principally exercised, and the Lord was with him,
and made way for him in the hearts of the rulers;
so that his faithful labor was often crowned with success,
to the comforting and rejoicing the hearts of many suffering brethren.

He was a good example to the flock in his diligent frequenting
of First and week-day meetings for public worship,
and other meetings for the service of truth, so long as his ability of body remained;
willing to take all opportunities for publishing and promoting the truth;
zealous to support good order and discipline in the church of Christ.
As he was not suddenly for taking hold of any,
so he was as exemplary in not being forward to cast any off,
in whom there appeared anything that was good,
being always desirous to encourage the good in all, condescending to the weak,
but admonishing the faulty, in the spirit of meekness and wisdom,
that they might be preserved in love to truth, and come into the unity of the one spirit,
which is the bond of peace.

He was a tender father in the church, and as such, was of great compassion,
sympathizing with the afflicted, whether in body or mind; a diligent visiter of the sick,
and laboring to comfort the mourning soul; careful to prevent,
and diligent in composing differences.

It pleased the Lord to visit him with some severe pains and weakness of body,
so that he was disabled for some weeks from getting to meetings;
but he often expressed his desires for the welfare of the church of Christ,
and that friends might live in love and unity.
He continued in a patient resigned frame of mind to the will of God,
waiting for his great change, rather desiring to be dissolved and be with Christ,
saying '`the sting of death was taken away.`'
He expressed, a little before his departure,
that he had a renewed sight or remembrance of his labors
and travels that he had gone through from his first convincement;
he looked upon them with abundance of comfort and satisfaction,
and admired how the presence of the Lord had attended and carried him through them all.

He departed this life in great peace and quiet the 8th day of the First month, 1723,
about the eighty-seventh year of his age, having been a minister about sixty-eight years,
and was buried the 13th of the same, in Friends`' burial-ground in Bunhill-fields,
attended by a large number of his friends and others.

--

[.asterism]
'''

THOMAS ALDAM, formerly of Warmsworth, in Yorkshire,
was educated in the way of truth we profess.
He was in his youth early visited with the spiritual appearance thereof in his soul,
and by and through faithfulness thereto he was fitted and prepared for
a dispensation of the gospel about the twenty-fourth year of his age;
in which he was fervent in stirring up friends to
faithfulness in the several testimonies of truth,
and which he also adorned with an exemplary life and conduct,
giving testimony thereto by two years and a half`'s imprisonment,
about the years 1671 and 1684.

He was diligent in attending meetings both for worship and discipline,
in which he was very serviceable, being of a sound judgment and able in counsel.
Much might be said of, his labors,
in which he always sought the preservation of peace and unity among Friends,
and retained his integrity to old age.

He was taken ill about the Seventh month, 1722,
and from that time kept his room under great weakness of body;
but was preserved in a weighty, tender frame of spirit.
As he had always been a diligent attender of meetings,
so at his desire the meeting was often kept in his room,
in which he was fervent in prayer, and bore testimony to the goodness of God to his soul,
and had a word of encouragement and exhortation to others,
to their mutual comfort and edification.
During his illness he was frequently visited by Friends,
to some of whom he expressed his hope and confidence in the Lord,
that through the mercy of God in Christ Jesus,
he should have a place of rest in the world to come,
and an inheritance among those who are sanctified.

He departed this life the 17th of the First month, 1723,
and was buried in the burying-place at Warmsworth, which himself had enclosed,
and built a meetinghouse therein, and in his life-time given to the use of Friends,
the 19th of the same.
Aged seventy-four years.

[.asterism]
'''

RICHARD CLARIDGE was born in the Tenth month, 1649, at Farmborough,
in the county of Warwick, of sober and reputable parents,
who brought him up to learning from his childhood,
and in the seventeenth year of his age sent him to the University of Oxford, where,
after some years`' continuance, he took his degree of B. A., and was ordained a deacon.
In the year 1672 he was ordained a priest,
and had his induction to the rectory of Peopleton, in the said county of Warwick,
where he continued a public preacher upwards of nineteen years.

During this time, the Lord was often pleased, by the in-shining of his divine light,
to open his understanding, and showed him the inconsistency of his then employment;
and for the sake of a good conscience towards God,
he quitted his parochial charge and tithe revenue,
and freely resigned the service in the year 1691.

After this he joined himself to the Baptists,
and was for some time a public preacher among them but his seeking soul not finding
that satisfaction which he earnestly longed for and sought after,
his eye being still to the Lord for the guidance and direction of his Holy Spirit,
tie mystery of the pure evangelical dispensation was clearly manifested,
and he was brought to embrace the truth as professed by us,
and made a public profession thereof in the year 1697.
He was brought to a patient waiting in silence,
not daring again to open his mouth until it pleased the Lord,
by the immediate operation of his blessed Spirit, to influence him thereto,
and make him a free minister of the gospel of Christ;
in which his testimony was sound and edifying, pressing all to purity of life,
adorning the same in his life and conduct.
His piety towards God and love to his neighbor,
the truth and justice of his words and actions, made him as a light in the world,
and gave forth a testimony to the truth in the hearts of others.
In his own family he was a living example of virtue, being an affectionate husband,
a loving father, and a kind and gentle master;
frequent in supplication to the Lord for the preservation
of himself and household in the way of truth and righteousness,
charitable to the poor, and a frequent visiter of the sick.
In his more public service, his various treatises, written in defense of truth,
will stand as lasting monuments of his unwearied endeavors for its promotion.

For some years before his death, he was in a declining state as to bodily health,
yet his love and zeal declined not;
but he kept close to meetings till about a week before his departure,
when he was taken with a shortness of breath, attended with a fever,
which continued on him to his end.
During the time of his sickness, he expressed to several friends who visited him,
his inward peace and satisfaction of soul, and a humble resignation to the divine will,
in an assured hope of a glorious immortality,
placing his whole trust and confidence in the free grace and mercy of God.
He departed this life the 28th of the Second month, 1723, aged seventy-three years;
and was buried in Friends`' burial ground near Bunhill-fields,
attended by a numerous company of Friends and others.

[.asterism]
'''

JOHN BROWN, an ancient Friend in the county of Surry, was born at Laleham, in Middlesex,
the 1st of the Sixth month, 1639,
and was one of the first convinced in the county where he dwelt,
and became a member of the monthly meeting of Kingston
upon Thames when the meetinghouse was built,
and continued a member thereof forty-eight years.
According to the talent received, he was a zealous contender for the faith,
not fearing the face of marl, nor turning his back in the day of battle;
but patiently suffered imprisonment in Newgate six or seven times,
as well as other jails, one of which was before the fire of London,
when he was obliged to carry his bed out on his back, when the prison was burnt;
besides the spoiling of goods which he many times suffered.
He neither fled in the winter, nor on the Sabbath day;
but remained steadfast to the truth to the day of his death.

He was taken ill at his son-in-law`'s, Jacob Forster`'s, in Blackman street, Southwark,
about the Fourth month, 1723, which he endured with great patience and satisfaction,
being sensible it was for his end; and expressed his resignation thereto,
full of heavenly expressions and divine exhortations to all who were about him.

He died the 6th of the Fifth month, 1723, and was buried in Friends`' burial-ground,
at Kingston aforesaid; aged upwards of eighty-two years.

[.asterism]
'''

DANIEL ROBERTS, an ancient Friend, of Chesham, in the county of Bucks,
was born at Siddington, near Cirenester, in the county of Gloucester,
about the year 1656.
His father, John Roberts of the same place,
was convinced in the first breaking forth of truth as professed by us,
by that servant of Christ, Richard Farnsworth, of whom some memoirs are extant.
This our worthy friend was one whom in his early
age the Lord was pleased to call into his vineyard,
and committed a dispensation of the gospel to him;
in the exercise of which he was often made an instrument of edification and comfort,
and by his labor therein some were convinced before his removal to Chesham.
He not only had to do, but to suffer for his testimony,
being imprisoned in Gloucester castle about two years,
till discharged about the year 1684.

After his settlement at Chesham,
great was his care to show forth an exemplary conduct of a meek and peaceable spirit,
seeking the peace and unity of the church,
being often opened in tender counsel to the weak,
yet steady in his zeal against every appearance of evil.
In his family he was a loving husband, a tender father, and a kind master;
to his neighbors courteous and kind;
his honest and innocent conduct raising an honorable esteem for him.

In his last illness he appeared to be in a sweet frame of mind,
much to the comfort of some friends who visited him,
and gave them good cause to believe he died in peace with the Lord and entered into rest.
He departed this life the 16th of the Twelfth month, 1726,
and was interred in Friends`' burial-ground the 19th of the same,
aged about seventy years.

[.asterism]
'''

JAMES OLDHAM, was born at Warrington, in the county of Lancaster, about the year 1715.
His conduct was according to the course of this world,
and according to the prince of the power of the air,
the spirit that now works in the children of disobedience,
until about the twentieth year of his age, when reading some books on religious subjects,
he perceived the necessity of experiencing judgment because of sin,
and the work of redemption through Jesus Christ our Lord.
After having been for some time seeking the way to Zion,
according to the degrees of light and knowledge imparted,
he was convinced of the truth professed by the people called Quakers,
and became a deeply-exercised, exemplary and well-approved member of their society.

The awfulness and simplicity of his conduct is still remembered by some,
to whom in their religious infancy he was as a nursing father,
although himself but a stripling in respect to years.
Having tasted that the Lord was gracious,
he had strong sympathy with the sincere travailers under various denominations;
nevertheless he was very careful not to go before or beyond
the guidance of truth for the help of others.

Being seized with a fever, at some intervals his understanding was affected;
but at others the composure and solemnity of his spirit were comfortably apparent.
He addressed several of his friends in a manner suitable to their states,
and signified his sole dependence was upon that merciful arm whereby he had been visited.
The day before his decease, a friend sitting by his bedside,
he bore a short but powerful testimony to the love and goodness of God;
expressed the views he then had of the divine light and glory, adding,
by way of appeal to the Almighty,
'`Oh Lord! you know I have loved you with an unfeigned love;`' or in words of like import.

After some time spent in solemn silence, he broke forth into an audible melody,
which was very affecting;
and having been singularly cautious of expressing more than he enjoyed,
there is abundant reason to think he was at that season
favored with a sense his warfare was nearly accomplished,
and of a settlement in the divine presence and favor forever.

He departed this life at the house of William Wagstaffe, in Martin`'s-le-Grand,
in remarkable quietness, as a lamb, in the Third month, 1740,
aged about twenty-five years; and after a large and solemn meeting,
was decently interred in Friends`' burial-ground in Bunhill-fields.

[.asterism]
'''

JOHN FOTHERGILL, of Carr-end, in Wensleydale, late of Knaresborough, in Yorkshire,
was born of religious parents, and carefully educated in the principles of truth.
Being made sensible in his early years, that neither tradition, outward regularity,
nor any thing short of real inward purification of soul,
would render him acceptable in the sight of the Lord;
he therefore gave up his heart to him, who,
through the effectual operation of his divine grace,
baptized and gradually purified his spirit,
and prepared and fitted him to be an able minister of the gospel of peace and salvation.
To which service he was called when but young, and readily gave up,
not allowing the things of this world to take up his mind and time;
but labored diligently and faithfully therein,
from his young years to the conclusion of his days.

In all the stations of life,
his testimony was confirmed and adorned by a conduct becoming a minister of Christ,
whom he served faithfully and with great diligence;
and by a daily inward dwelling with the spring of wisdom and light,
his mind was often opened,
and his spirit sustained to secret worship when his hand was upon his labor.
His delight was in the law of his God, to meditate therein day and night,
and to talk of his statutes in his house to his family, and those with whom he conversed;
and many times by a transition from earthly to heavenly things,
instructed and edified the minds of those present.

In his public testimony, +++[+++he was]
awful and weighty, being endued with true wisdom,
strong and immovably bent against all unrighteousness; quick in discerning,
and powerful in detecting the mysteries of antichrist,
who has sought to stupefy the people with the golden cup,
and thereby to spread the power and enlarge the borders of the kingdom of death.
As a flame of fire was he to the rebellious and stubborn;
but refreshing as the dew on Hermon to the honest traveller,
ministering counsel and comfort to the drooping soul; being not only an instructor,
but a father to many.
Zealous and wise in the support of the discipline established among us;
impartially and honestly doing judgment and justice; no family connections,
not even his own, could bias him from laying the line upon offenders,
nor from a steady endeavor to keep clean the camp of God;
in which labor he was often successful, being made a terror to evil doers,
and a praise to them that did well.

Thus conducted in every station of life, he became honorable among men,
and greatly esteemed by those of superior rank who knew him;
being adorned with that dignity which truth confers on its faithful followers.

In the course of his gospel labors he travelled much in this nation,
in Scotland and Wales.
He visited Ireland several times,
and thrice he crossed the seas to America in the same service,
to the comfort and edification of the churches,
leaving seals of his ministry in many places.
In the year 1744 he attended the yearly meeting at London,
in company with his ancient friend, Boswell Middleton, for whom he had a singular esteem;
and although his weakness rendered it difficult for
him to attend the large meetings for business,
nevertheless he did attend them, and his exemplary, reverent,
watchful frame of mind therein, rendered his company truly acceptable and serviceable.
On his return, he attended the midsummer quarterly meeting at York; after which,
in a letter to a friend, after mentioning the weakness of his body, '`Yet,`' says he,
'`I think my better part is almost uncommonly supplied in several respects,
much to my comfort, and the reviving of my faith in the heavenly influence,
which is strength in weakness, and will be, where his only worthy name has the praise.`'

In the latter part of the said year he attended the circular yearly meeting at Worcester,
where he was enabled to bear a noble Christian testimony
to the all-sufficiency of that power which had preserved,
supported, and guided him in the way that was right and well-pleasing;
and is likewise able to do the same for all the children of men.
After visiting Bristol, Bath, and some other meetings, he returned home by easy journeys,
having meetings as opportunities offered.
After his return he got to meetings for some weeks,
and his testimony was as lively and powerful as ever;
several times expressing his satisfaction and inward peace,
in having performed his last journey,
saying his shoulders were a good deal lightened by it,
and he was reconciled to his grave, if he was now to be taken away.

The last two weeks he slept almost continually, day and night,
his memory and capacity being much impaired;
yet when almost all other expressions failed,
he was observed to repeat the following in a very fervent and emphatic manner:
'`Heavenly Goodness is near; heavenly Goodness is near.`'
Thus, the mighty God who visited him in his youth with the discovery of his saving power,
who thereby cleansed him from unrighteousness,
and sanctified him to himself as a chosen vessel,
supported him in all his faithful labors by sea and land,
covered his head in all conflicts, and by whom his bow abode in strength,
became his evening song and stay in the decline of life;
that heavenly goodness he had ever prized, as his chiefest joy,
remained as a seal upon his spirit, that he had pleased God, and was accepted of him.

He departed this life at Knaresborough, the 13th of the Eleventh month, 1744,
and was honorably buried in Friends`' burying-ground at Scotten, near the said town,
the 15th of the said month; aged sixty-nine, and a minister nearly fifty years.

[.asterism]
'''

BENJAMIN KIDD, of Banbury, in Oxfordshire, was born at or near Settle,
in the county of York, and educated among friends.
While very young he was favored with a visitation of truth, to which he was faithful,
and through the powerful operation thereof,
was in or about the twenty-first year of his age called to the work of the ministry;
wherein he was eminently qualified rightly to divide the word of truth;
and to unfold the mysteries of the gospel in great brightness,
to the informing and convincing many,
and to the comfort and encouragement of such as were under affliction
and distress of mind in their religious progress.

He was eminently qualified for great and singular services in the church,
a diligent attender of meetings, both for worship and discipline;
in both which he was very serviceable.
He was a man of sincerity and integrity,
of good understanding in matters useful to mankind, and freely communicative;
universal in his benevolence, and laborious to do good to all.
Deep in divine experience, sound in judgment, wise in counsel,
zealous for the promotion of truth and righteousness,
and the exaltation of the cause of his Lord and master in the earth.
He was instructive and weighty, yet becomingly cheerful in conversation;
exemplary in life and conduct, peculiarly kind and fatherly towards his friends,
compassionate to the poor and distressed, generous and noble in his disposition,
highly useful and agreeable to his neighbors,
and generally beloved by persons of all ranks and denominations to whom he was known.

The principal design of these observations is to excite you, reader,
to consider in what manner he was raised to this dignity in the church;
and also to reflect, that the same divine principle is in you,
and if you are faithful thereto, the same fruits will appear according to your measure.

About the thirtieth year of his age he visited America, where many were convinced,
and others confirmed through his powerful ministry.
His service there was very great, and much to the edification, comfort,
and satisfaction of Friends, as appears from sundry accounts.

After he settled at Banbury, he visited Ireland and various parts of Great Britain.
The city of London, in particular, frequently partook of his pious and fervent labors,
to the great help and consolation of many,
who have had just reason to bless the Lord on his behalf.

A few months before his death he was greatly afflicted
with a disease which was very painful to bear;
but at times he got a little out,
and particularly he attended the quarterly meeting at Oxford, in the Tenth month, 1750,
O+++.+++ S., though under great affliction of body, which gradually increased,
together with a dropsical disorder attending;
through all which his patience and resignation were very remarkable.
About a month before his decease, he attended the meeting at Banbury,
at the burial of a young man whom he greatly esteemed,
which he got to with great difficulty, being obliged to be supported by two friends.
In the course of the meeting, he was raised, beyond all expectation,
to preach the gospel powerfully for about an hour,
to the tendering the hearts of almost all present.
Many of his neighbors being there, confessed, with admiration,
to the power by which he was raised that day,
remarking that he had been a good man all his time,
and that the Almighty had crowned him in the conclusion.
After this he was mostly confined within doors,
and continued in great submission to the divine will, without murmuring or repining.

A Friend from London visiting him, found him under great bodily affliction,
but freely resigned to the divine will,
expressing his firm hope in that power which had all along supported him; and that,
though the greatest kindness to him was to solicit a release from his pains,
yet he desired to be content and wait the Lord`'s time.
When the said Friend took his leave of him,
he expressed himself to him in an affectionate manner,
to his great comfort and encouragement.

At another time, having delivered some excellent exhortations to those present with him,
he added, for their encouragement to persevere in their Christian progress,
'`I am under no fear or doubtful apprehensions; for I know that for me to live is Christ,
and to die is gain.`'

When he was first seized with the hiccough, he seemed full of joy, saying,
'`This is a welcome messenger, it is one step nearer.`'
His wife standing by, asking why, he answered, It will be a glorious change;
I am not afraid to die and to put on immortality; that will be desirable; yet I leave it,
though of choice I had rather be dissolved; but the Lord`'s time will be the best time:
'`often saying death would be the most welcome messenger he ever met with.

Thus this good man finished his course, his sun going down in great brightness,
at Banbury, the 21st of the Third month, 1751, O. S.,
and was buried the 24th of the same, after a large and solemn meeting;
aged about fifty-nine; a minister about thirty-eight years.
