== Chapter 14

[.chapter-synopsis]
* Sarah Artis
* William Pitts
* Robert Plumsted
* Lydia Lancaster
* William Backhouse
* Hannah Smith
* Mary Slater
* John Ransome
* Agnes Iall
* Sarah Marsden
* Samuel Watson
* Grace Chambers
* Alice Hall

SARAH ARTIS was born at Woodbridge, in the county of Suffolk, in the year 1714,
of religious parents, who were both taken away while she was young.
She early discovered a sincere desire after the knowledge of the truth,
and the seed thereof falling upon good ground, it took root downward;
and being humble in spirit, and patient under the operations of it,
it brought forth plentifully,
so that about the twenty-sixth year of her age she came forth in testimony,
in which she was clear in her delivery, sound in judgment, and,
being seasoned with gospel love, it might truly be said,
she was one of the wise-hearted women in our Israel.

She was often concerned to visit particulars, more especially of the younger sort,
and was often made instrumental to open their present states,
and to administer the wine and the oil as the occasion required.
She visited several parts of this nation and Ireland, and,
her life and conduct corresponding with the doctrine she preached,
her services therein were acceptable.

Her illness, which was a cancer in her mouth, was very long,
and much affected her speech,
so that she could not utter words but with great difficulty.
She languished for some months,
and was earnest in spirit that she might be preserved in patience and an entire resignation,
whether to live or die.

She expressed great satisfaction in that she had
been faithful in the discharge of her duty,
and near her end had a great desire of being dissolved,
in a full assurance of entering into that rest which
is prepared for them that die in the Lord.

She departed this life about the forty-fourth year of her age,
and was interred in Friends`' burial-ground at Woodbridge, the 19th of the Fourth month,
1758.
A minister eighteen years.

[.asterism]
'''

WILLIAM PITTS, of Southwark, in his young years,
was early visited with a call of divine grace,
and by adhering thereto and submitting to its operations,
he became convinced of the essential doctrines of Christianity, as professed by us.
In his minority he was educated by a priest,
under whose tuition he attained a considerable knowledge in several of the learned languages;
yet the tender scruples which were raised in his mind,
under a clear conviction of the impropriety of the needless
ceremonies and salutations in which he had been educated,
exposed him to many sufferings from his father, from whom he received unkind treatment,
which he endured with much patience and fortitude,
and which tended much to his growth and advancement in religious experience,
and preparation for further service.

From some minutes he left,
he was under some conflict of mind respecting his appearing in the ministry,
which continued nearly three years before he gave up thereto;
and having a clear sense of the importance of that weighty service,
and the necessity of obtaining a certain evidence of his mission,
he waited for a confirmation thereof, lest he should run, before he was sent.
In the Fifth month, 1738, he was enabled publicly to utter the following sentence,
'`If the trumpet give an uncertain sound, who can prepare himself for the battle.`'
This, as he has been heard to say,
afforded him instruction through the future service of his day, which was very great,
his heart being fully given up to do whatever his hand might find to do,
as was evident from his own expressions to some Friends who visited him in his illness,
whom he encouraged to faithfulness,
saying that for the last twenty years he had never omitted
one service which had appeared to be his duty,
and he had now the comfort and satisfaction thereof, or words to that effect.
Great as were his services,
his talents and qualifications were employed to the glory of the giver.

In the Fourth month, 1760, he set out to visit Friends in Buckinghamshire,
and some adjacent parts; but being much indisposed, he returned homewards,
and at the house of our friend Thomas Goring, at Uxbridge,
he was suddenly taken very ill; during which he uttered the following expressions: '`Oh,
my Father! my Father! be pleased to be with me in my affliction.`'
He gave it as his judgment that his time in this world would be short,
and that he should die of this present illness; and said,
'`I am fully resigned to the will of Providence;`' declaring he coveted not length of days,
and that he was very easy in body and mind.
Being asked how he did, he said he was very sick in body,
'`but I have a great physician in heaven, who is very merciful to me,
and near me in this illness.`'

At another time,
after having repeated his perfect resignation to the will of his great Master, he said,
'`If it pleased him, he had rather die than live,
unless he had any further service for him to do.
And he could rejoice, saying, "`O death, where is your sting?
O grave, where is your victory?
The sting of death is sin, and the strength of sin is the law; but thanks be to God,
who gives us the victory.`"

Many Friends from London and elsewhere went to see him, whose visits he took very kindly,
and to one of them he expressed himself in the following manner:
'`I never coveted riches nor power; and indeed, if I had obtained them, what could they,
or all the friendships of the world, do for me now?
Nothing but the testimony of a pure conscience, and the inward sense of divine favor,
can comfort my soul in these moments.
Thanks be to my heavenly Father, I feel his supporting arm underneath,
and it is a rest indeed, a joy that overcomes all.
It makes this bed easy, and enables me to bear calmly, and without complaint,
the dispensations of his gracious providence.
I wish for nothing to myself otherwise than it is.
I accept with satisfaction and thanks the kindness of my friends:
in compliance with their request, and thinking it my duty to do what may be in my power,
I take the medicines prescribed, which,
though it may not seem meet to Providence in his wisdom
to render instrumental in the restoration of health,
yet, through his blessing,
they have so far succeeded as to remove the sense of acute pain.
To be thoughtful of, and prepare for this trying time,
have I frequently and earnestly exhorted others,
not without considering and knowing the many strong temptations of this world, which,
however, as we are obedient to the spirit of Christ, we shall be enabled to overcome;
that in the conclusion they might have this answer of peace,
this divine consolation of mind.
It always appeared best to me, to do this in great love and gentleness,
so that I might persuade, not force them to Christ.
When this time comes, it will be found hard work, without any additional weight,
to struggle on a dying-bed with the pangs of the body.
But how much more to be lamented is the condition of those,
whose consciences accuse them with having enriched
themselves by oppressing the poor and helpless;
and when in an unprepared state, after a life of rebellion and hardened in iniquity,
such must feel the terrors of a guilty mind, added to the agonies of a perishing body.`'

A friend who went to visit him, a day before his death, asked him how he did;
after a short pause he said, '`I am waiting for my great change.
O my Father! be pleased to be with me, and comfort me in my last moments.`'
The last words he was heard to speak were these: '`There is a great God in heaven,
who is Zion`'s king.
O Zion!
O Zion!
O you great King of kings!`' Soon after which,
he departed in great tranquillity and composure of mind, the 15th of the Fifth month,
1760.
His body was brought to his own house in Black`'s-fields, Southwark; and from there,
after a solemn meeting at Horslydown, attended by many Friends,
was decently interred at Friends`' burial-ground in the Park, Southwark.
Aged about fifty-one years, and a minister twenty-two years.

[.asterism]
'''

ROBERT PLUMSTED, of Gracechurch-street, London,
was in his youth addicted to gaiety and the delusive pleasures of this transitory world;
but was preserved out of the gross evils thereof.
About the twenty-eighth year of his age,
it pleased Divine Providence in great mercy to manifest to him,
that if he would obtain peace he must walk in the narrow path of self-denial.
Thus by adhering to the dictates of divine grace,
he was enabled to deny himself of the pleasures and pomps of this world,
take up his cross,
and in a good degree was brought into conformity to the leadings of truth.
Sometimes for about a year before his decease,
he appeared in a few words in our religious assemblies in a tender manner,
which was acceptable to Friends.

He was afflicted with a long and painful illness,
in which he had at times access to the throne of grace, and when reduced very low,
uttered these words distinctly: '`Lord!
As you have continued me to this moment,
let me not depart without undoubted evidence of your favor.`'

He quietly departed this life the 14th of the Seventh month, 1760,
at the Hot-Wells near Bristol, and his corpse being brought to London,
was interred the 23rd of the same, at Winchmore-hill, in Middlesex,
accompanied by many friends,
after a large and solemn meeting at Devonshire-house in London.
Aged thirty-six years.

[.asterism]
'''

LYDIA LANCASTER was the daughter of Thomas and Dorothy Rawlinson, of Graithwaite,
in the county of Lancaster, who both descended from families reputable among men;
and they both came among friends on the principle of convincement,
and were religiously concerned to instruct and example their children therein,
as the most precious of all blessings.

That powerful hand which alone can give the increase,
mercifully extended an excellent blessing to several of their children,
and particularly to this their daughter; and as it opened the heart of Lydia of old,
so it opened her`'s, to receive the heavenly message.
In her young years she became sensibly acquainted with the Lord,
and witnessed his gracious dealings with her, in order to redeem her to himself,
and make her a sanctified vessel to place his name in.

About the fourteenth year of her age,
she had a view of the will of Providence to engage her in the ministerial service;
under which concern she continued about ten years, growing in wisdom and experience,
that she might come forth in the right time, endued with proper qualifications.
In this time of deep travail and heavenly discipline,
she learned to say with the prophet Isaiah, "`He awakens me morning by morning,
he awakens my ear to hear as the learned.`"

About the twenty-fourth year of her age, she came forth in a living`', powerful testimony,
and grew therein.
The blessed author of all spiritual riches having abundantly
replenished her with the treasures of his kingdom,
she soon became an able dispenser thereof to the churches,
having a word in due season to several states; and like the well-instructed scribe,
brought out of the treasures committed to her, things new and old.
And as she was eminently favored by her great lord and master,
she became humbly devoted to his requirings.
When called forth into the various parts of his vineyard,
she freely gave up to spend and be spent for his name`'s sake.

She visited this nation, or the greatest part of it, several times;
Ireland and Scotland twice; also the continent of America;
in all which she was rendered instrumental to build up many in the most holy faith;
particularly in America she left many seals of her ministry,
both in the edification and help of those who were of the society,
and the convincement of others, gathering them to the great Shepherd of the flock.

Her openings into the mysteries of the kingdom were deep and instructive,
adapted to the state of those among whom she labored;
close and with authority to the negligent and careless;
yet all her ministry was attended with that love
and tenderness which accompanied her lord and master,
who came to seek and to save that which was lost.
She was favored with a most excellent utterance, her gesture awful, her voice solemn;
and all her demeanor in the exercise of her gift,
becoming the dignity of the gospel ministry.
She was signally favored in supplication,
having near access in spirit to the throne of majesty and grace,
before whom she worshipped with calm rejoicing and awful reverence.

Thus, through a course of many years she retained her zeal and integrity,
and in her old age was strong in the power of an endless life.
Great indeed was her growth in religious experience, even to the stability of salvation,
and an assurance that she should never fall, yet accompanied with the deepest humility.
Filial love, which casts out fear, was the covering of her spirit,
and rested almost constantly upon her for several months before her removal.

About six weeks before her departure,
she thus expressed herself to a Friend she had favored with an intimate acquaintance:
'`My natural strength is not so much impaired as to give
me reason to expect a sudden removal from this world;
but I feel so constantly day and night the virtuous life,
and my Father`'s holy presence is so constantly with me,
and I enjoy so much the spiritual communion and fellowship of saints,
as to give me an apprehension I am not far from mine
everlasting home;`' to which she sweetly added,
'`A glorious crown and everlasting song is before me.`'
The Friend to whom she thus expressed herself being deeply affected with
the sense of the over-shadowing of the Holy wing at that instant of time;
she further added, '`If the foretaste be so joyous,
what are the riches of the saints`' inheritance beyond the grave?`'

She was supported to labor in the gospel almost to the conclusion of her days,
having attended the funeral of an ancient Friend, William Backhouse, several miles off,
on the First-day of the week,
and preached the gospel in the demonstration of its own power;
and finished her course the Seventh-day following; and as she lived so she died,
in great favor with God and man, full of days, and full.of peace.

She died at Lancaster the 30th of the Fifth month,
and was honorably interred in Friends`' burial-ground, the 1st of the Sixth month, 1761.
Aged about seventy-seven years, and a minister about fifty-three years.

[.asterism]
'''

WILLIAM BACKHOUSE was born in the year 1695, at Yealand, near Lancaster,
of religious parents.
His father dying when he was about two years old, a prisoner in Lancaster castle,
for his conscientious testimony against the payment of tithes,
the education of his children devolved solely on his mother,
who was religiously concerned in this duty, both by precept and example,
and it pleased divine Providence to bless her endeavors with success therein.

About the twenty-sixth year of his age he came forth in a public testimony,
and by faithful obedience to the requirings of the heavenly giver,
he witnessed an enlargement in his gift, and was an acceptable minister.

He visited the churches in most parts of this kingdom, Scotland, Ireland,
and the continent of America, much to the comfort and satisfaction of friends,
he being furnished with sufficient strength for the service of the day;
being sound in doctrine, tending to information, instruction, and edification;
exemplary in attending meetings both for worship and discipline,
in the latter of which he was highly serviceable, being a lover of peace, of a loving,
courteous disposition to all; an affectionate husband, a tender parent,
and kind neighbor, which procured the love and esteem of them all.

In his last sickness, being a gradual decay of nature,
it pleased the Almighty to favor him with many precious earnests of a blessed inheritance.
Several friends who visited him, were in a good degree made sensible thereof.
In some of these opportunities he was engaged in a lively manner,
though in deep humility,
to commemorate the gracious dealings of the Lord with him in the course of his pilgrimage,
and thankfully to rejoice that he had labored in his day
to perform what he believed was required of him;
and could make his appeal to his heavenly Master, saying,
'`Although I have had the world to struggle with for
the support and prudent provision for my family,
yet you know, O Lord, I have been more concerned for your honor and the good of souls,
than for any other considerations.`'

Though greatly blessed in his nearest connections of life,
yet being weaned from this world and its enjoyments,
he waited with great patience and resignation for his dissolution.
He departed this life the 21st of the Fifth month, 1761,
and was buried at Yealand the 24th of the same.
Aged sixty-six: a minister above forty years.

[.asterism]
'''

HANNAH SMITH, wife of John Smith, of Philadelphia,
was the daughter of James and Sarah Logan,
and born there on the 21st of the Twelfth month, 1719-20.

By the care of her parents she was in a great measure
preserved from the levities incident to early youth,
and by opportunities of improvement afterwards,
she acquired such qualifications as gained her much respect and esteem.
Though the affluent situation in which her parents were placed,
yielded flattering prospects of the ease and gaiety of the world,
the durable riches of true religion appeared to her a treasure of much more consequence,
and not to be relinquished for shadows and delights that die in the enjoyment.
Thus at a period when the slippery paths of vanity in a succession of increasing allurements,
are apt to ensnare youthful minds,
it pleased the Lord to bless her endeavors against
the temptations of vain and unprofitable company,
and to strengthen her love to inward retirement.
Having tasted of the visitation of divine love to her soul,
she saw it to be the pearl of great price,
and that her all must go to purchase the field where it lay.
From that time forward there is reason to believe this purchase
became the principal business of her life,
and with great sincerity and ardor she labored to have all those
disquieting affections silenced which arise from temporal objects,
and she was helped at times to know the breathing of her soul answered,
and was made to partake of the joys of God`'s salvation;
under which her care over her words and deportment was increased.
She continued to take suitable opportunities of retirement,
and for reading the Holy Scriptures; and in the relation of a child, wife, and mother,
was tenderly careful to fill up her place becoming those stations.

About the year 1756 she appeared +++[+++in the ministry of the gospel]
in a few words in much simplicity of heart and godly sincerity,
and was concerned in visiting Friends in their families,
and also accompanied some of her own sex to several
large yearly meetings in the neighboring provinces.
After her return to Philadelphia, which was half a year before her departure,
she continued to attend religious meetings with as much
diligence as the weakness of her constitution would admit,
and when there to clear herself of what she believed required of her.

During her last illness she told her husband several
times that she believed she should not recover;
and though her bodily pain at times was very sharp, she was favored,
with an entire confidence in the mercy of God through Jesus Christ,
whom she found to be a refuge from storms, and a sure defense in the day of distress.
Another time, acquainting him, with great sweetness of spirit, of the state of her mind,
she said, '`Notwithstanding the close trials I undergo, my foundation remains sure,
and I have a hope, yes, an unshaken hope, that there is a place of rest prepared for me.`'
At another time, mentioning the prospect of her change being near,
she entreated her husband to strive for resignation, '`for`' says she, '`I am easy,
I feel no guilt.`'
A few evenings before her decease, as her husband sat by her bedside,
she desired that her children and all about her might
keep as still and quiet as possible when she departed,
and after mentioning several other things relative thereto,
told her husband that she felt pardon and forgiveness for all omissions of duty;
and concluded this very affecting conversation with these words,
'`Oh the infinite lovingkindness of a merciful God,
who has made such a poor creature as I am so rich in faith and firm in hope,
that I shall be accepted of him.`'

She departed this life on the 19th,
and was decently interred on the 23rd of the Twelfth month, 1761;
aged about forty-one years.

[.asterism]
'''

MARY SLATER, late wife of William Slater, of Lothersdale, in Yorkshire,
was descended of honest parents, though her mother did not profess with us,
her father being after his marriage convinced of our principles.

Being of a very gay, sprightly temper,
she was soon carried away with the delusive vanities and pleasures which abound;
though often attended, when very young, with strong convictions.
These were stifled for a time by various scenes of dissipation and folly,
to which she had recourse, till the Father of mercies, by his good Spirit,
effectually reached her when in the full career of mirth,
being at a public evening entertainment of the neighboring youth,
about the fifteenth year of her age.
This strong and humbling visitation, as she often expressed,
brought her to see the folly of such mirth and merriment,
being at that time attended with such an awful dread on her mind,
as made her willing to depart from these vain amusements,
having no longer pleasure in them.

She now began to see the situation she was in, and the need she had of saving help,
by which a secret hunger and thirst were begotten
in her after divine and substantial food,
which led her with diligence to attend the way of worship in which she had been educated;
but finding no true satisfaction or proper nourishment for her disconsolate panting soul,
she often returned from the place of worship in tears and great anxiety of mind.
She then went among the Baptists, in hopes of meeting what she so ardently desired after;
but, being here also disappointed, she was led to attend Friends`' meetings;
though till now she even abhorred the name, yet at length,
through several close conflicts and probations,
she came to experience that divine comfort and consolation
which her soul had so longed for and labored after.
The way of life and salvation being then pointed out to her,
she had soon to tell to others what the Lord had done for her soul; for,
about the seventeenth year of her age, she came forth in a public testimony;
and being faithful and diligent in the exercise of her gift,
she became an able minister of the word,
being freely given up to her great Master`'s service,
though often under great temporal inconveniences.
Her husband was never possessed of much of this world,
yet their house and hearts were open to entertain their friends with the best they had;
and it was often cause of humble thankfulness to her mind that,
notwithstanding their low beginning, they never lacked what was needful,
ever preferring the welfare of Zion before her chiefest joy.

She visited, several times, most parts of England, Scotland and Ireland,
in which her services were acceptable, and left lasting impressions on many minds;
her ministry being in the demonstration of truth, and in the power thereof.
She was fervent in prayer, being often favored with near access to the throne of grace,
to the baptizing of the assemblies into an awful adoration of him who lives forever.

Thus through a variety of services she labored faithfully,
as well in the discipline as ministry,
so that the memorial of her labors has left a sweet savor behind.
In private life, she was exemplary in conduct,
and in the near relation of wife and mother; in conversation innocently cheerful,
yet solid and savory, which rendered her company very acceptable.

For some weeks before her death she was confined to her bed,
under such bodily affliction that she had not strength to say much
further than signifying her satisfaction at seeing Friends,
and her unity with them.
At one time she said to a friend who visited her, that she was very weak in body,
but the Lord was strong; adding that she was easy and had peace of mind,
her day`'s work being done.
There is no doubt but she has laid down her head in peace.

She departed this life the 3rd of the Third month, 1762, aged sixty-nine years,
and was interred the 7th of the same,
in Friends`' burial ground in Lothersdale aforesaid.

[.asterism]
'''

JOHN RANSOME, of Northwalsham, in the county of Norfolk,
was a lively example of true piety,
and through a course of many years labored for its promotion;
which he continued till illness deprived him of his faculties,
and by which means we are deprived of any expressions from him in his last illness.

That such an example should not be lost,
as an incitement to future generations to fill up every duty,
and be truly serviceable also in their day,
the following abstract of a testimony from the quarterly
meeting of Norfolk concerning him is here inserted:

[.embedded-content-document.testimony]
--

He was educated in the profession of truth, and in his young and tender years,
reached by the extendings of divine love, and happily closing in therewith,
he soon gave ample proofs of its efficacy,
that as he grew in years he grew in the knowledge and obedience of truth.

He came forth in the ministry about the twenty-eighth year of his age.
Many were the precious gifts bestowed upon him,
and the testimony given him to bear was truly comfortable;
his openings deep and instructive,
and he became an instrument of singular benefit to many,
from a true sense that was given him of their states and conditions.

As an elder and overseer he was without rebuke:
his mind being filled with unbounded charity and love,
counsel and reproof were well received from him;
and as he felt deeply for the infirmities of all, so he exposed the failings of none.
Thus eminently covered with the spirit of healing,
he seldom met with an obstinacy able to withstand it.
He never designed offense to any, and if through misapprehension it was conceived,
he was unwearied in his application to remove it; strong in the truth,
yet for the sake of it, subject to the weakest; suffering all things,
and in condescension sacrificing every selfish consideration to their help.
He loved mankind in truth, and thus qualified, he became a pattern in word and conduct,
adorning the gospel he preached.
He was endued with a large share of natural understanding,
which being sanctified by the great and good hand that blessed him with it,
rendered him very successful in putting an end to
differences among his neighbors and friends.

In the nearest connections of life he was equally exemplary; being a tender,
loving husband, an indulgent parent, an affectionate relation,
and strictly regardful of every duty towards his servants,
his care over whom was attended with singularly good consequences.
In these and many other respects, the loss of him is sensibly felt by us;
but we firmly believe it is his eternal gain.

His services in the wholesome and necessary discipline
established in our society were very great,
both in monthly and quarterly meetings.
As he was exceedingly industrious in what he believed to be his duty,
so was he likewise in visiting the churches;
devoting much of his time and outward substance to that service,
more particularly in the last ten or twelve years of his life.

He constantly attended the service of the yearly meeting in London for many years;
the last time of his being there he was seized with
that illness which concluded his natural life;
but notwithstanding his indisposition,
he visited several large meetings in Hertfordshire, Essex, and Suffolk.
He got to his own dwelling-house at Northwalsham, the 20th of the Sixth month,
and departed this life the 2nd of the Seventh month, 1762,
in the fifty-second year of his age.

His body was interred on the 6th of the same, in Friends`' burial-ground there;
a very large concourse of friends and others attending the solemn occasion.

--

[.asterism]
'''

AGNES IALL, daughter of William and Dorothy Kidd, of Settle, in the county of York,
gave early tokens of a religious inclination and filial affection;
being very serviceable in her youth to her infirm mother, during her widowhood,
in bringing up a pretty numerous family of children, she being the eldest,
her father dying when she was about seventeen.
Her conduct may truly be said to have been exemplary in plainness, moderation,
and industry; in benevolence and unaffected piety; being of a meek and quiet disposition,
her words few and savory, which made her company truly valuable.

About the thirty-seventh year of her age she had to preach the glad tidings of the gospel;
though not large or frequent for some years, yet was seasonable, sweet, and edifying,
much tending to encourage the youth to give up the prime of life to the service of truth;
having to acknowledge her thankfulness to the Almighty,
that he had wrought a willingness in her heart in her early days to bow to his yoke,
which she found by blessed experience to be easy, and his burden light.

She never travelled much in the work of the ministry,
but was a diligent attend r of meetings near home,
and very serviceable in the management of the affairs of the church.
Her indisposition of body rendered her unable to get to meetings a year before she died.
When friends visited her, though she lamented her lonely situation,
and being deprived of getting to meetings,
yet she had at times to rejoice that she felt the great I AM to be near;
he that had been the stay of her youth, to be a staff to lean upon in old age,
and to bear up with patience, under great affliction of body,
in a lively hope and assurance of a resting-place among the righteous.

A friend visiting her a little before her death,
she was much affected with a sense of the great declension in the church,
and of many superfluities that were crept in,
which our ancient Friends had to take up their cross to,
and bear their testimony against, the thoughts whereof much discouraged her;
being convinced our principle remained the same,
and that we had no nearer way now to the fold of rest than they had.

About an hour before her death, several Friends visiting her, she being set up in bed,
in a lively frame of mind, expressed her great satisfaction in their company,
that she sensibly witnessed the goodwill of her heavenly Father to be near,
which she had valued all her life long.
Under the influence hereof she rejoiced and was comforted,
and was strongly engaged on the youths`' account (some young friends being present),
that they might choose truth for their portion,
and Jacob`'s God for the lot of their inheritance,
which far exceeded everything this transitory world would afford.
She was sorry she had not had more frequent opportunities of their company while she
had strength to express her warmth of desire for their growth in the best things,
that would stand them in stead when everything else would fail.
When they took their leave, she said she was glad of that opportunity;
and if she never saw them more, she hoped they should meet in a better place.

She was soon after got up in a chair,
where in a few minutes she quietly departed this life, on the 1st of the Eighth month,
1762.
Aged seventy-six years; and was decently interred in Friends`' burial-ground, at Settle,
the 4th of the same.

[.asterism]
'''

SARAH MARSDEN, wife of Caleb Marsden, of Highflatts,
within the compass of Pontefract monthly-meeting, was born in the year 1706,
and being favored with a religious education,
and the visitations of truth in her young years,
by yielding obedience thereto she became a sober, grave, discreet young woman,
a diligent attender of meetings, and honestly laboring to improve her time therein.

About the year 1749, it pleased the Lord to call her into the work of the ministry,
which she in great fear and tenderness gave up to; and although never large in testimony,
yet she was plain, sound, and edifying, rather backward in her public appearances,
and afraid, as she said, to awake her beloved till he pleased.
But when she felt the holy fire burn, then she offered her gift,
and was careful when that abated to sit down in meetings,
where too many are intent on words.
She was a diligent laborer in spirit, her very countenance being awful and affecting,
and like the worthy elders and nobles of the people (Num. 21:18),
digging as with the staff the Lord had given her,
and sometimes broke forth in solemn supplication to the great Law-giver,
that the well of life might spring up,
which at times she was the happy instrument of effecting,
to the consolation of the right-minded.

She was naturally of an affable, peaceable disposition, an affectionate wife,
a tender mother,
and weightily concerned to train up her children
in the nurture and admonition of the Lord;
kind to her friends, charitable to the poor, and an example of humility,
self-denial and resignation to the divine will,
and also of industry and prudent management of the affairs of this life.

Her last illness was long and tedious,
which she endured with much patience and resignation; saying, '`My body is full of pain,
yes, more than I can well bear.
O the sad state of those in my weak condition, who lack peace of mind!
But forever blessed be my God, who now on my sick-bed answers the desire of my mind,
in giving me an evidence of my peace with him,
having nothing to do but to bear with patience the painful
afflictions that are permitted to attend me.
I find it work enough to struggle with nature; one had need have nothing else to do.
My breathing and travail of soul has often been to the Lord that
he would let me see my duty and give me strength to perform it.
If I had my time to spend over again, I know not that I could spend it much better.
I can truly say, I have never been too forward in my appearances in meetings,
and other things relating to the Society; but always in great fear,
which sometimes has been so great that I have been too backward,
and hurt myself thereby.`'

To some friends present, she said, '`Dear friends, stand in your lots: fear not man;
come up in your proper places, and the God of peace will be with you,
and strengthen you to perform and come up in the way of your duty to him,
and one unto another;
and so you will be preserved in the pure love and unity of one spirit.`'

At another time a friend called to see her, to whom she said,
'`You and I have been very near one to another.
O my body is full of pain!
I am sometimes ready to say, Lord! what have I done?
I want to be eased and dissolved: my stay here seems very long,
at morning I wish for night, at night I long for morning; but yet blessed be my God,
I feel his hand underneath, and he bears up my spirit,
or I could not tell how to endure my affliction.`'

At another time, being very weak, she said to her husband and children,
'`At the time of my departure be as still as you can, and feel for yourselves,
and do not mourn to excess, for all will be well.
Do not mourn for me; but rather rejoice when I am delivered from these pains,
for my change will be a happy one.`'

One evening lying very still,
those who attended her thought she had been going to depart;
but after some time she opened her eyes, and seeing her relations standing by her,
she raised her voice in a surprising manner, and said, '`I am entirely sensible,
and behold you every one, and glad I am to depart in peace.`'
She took her solemn farewell of all present, in a very loving,
affecting and cheerful manner,
those present thinking the time of her departure had been very near;
but she continued some days longer, mostly lying in a still, quiet,
peaceable and resigned frame of mind, patiently waiting her dissolution.
Near her conclusion, her voice being very weak, she was heard to say,
O that my sweet Redeemer would come and take me to himself!
Do not hold me, let me go freely.`'

She died the 8th of the Eighth month, 1762,
and was interred in Friends`' burial-ground at High-flatts, the 11th of the same;
aged fifty-six years.

[.asterism]
'''

SAMUEL WATSON, of Killconner, in the county of Carlow, in Ireland,
having been a bright and lively pattern of true religion and virtue,
in order that such an example should not be lost,
the following testimony given forth concerning him
is thought fit to be inserted in this collection:

[.embedded-content-document.testimony]
--

Our dear and well esteemed friend Samuel Watson, of Killconner, in the county of Carlow,
in Ireland, succeeded his worthy and honorable father John Watson, of the same place,
not only in his outward possessions there,
but in a zealous concern for the testimony of truth, and support of its cause.
Blessed with the great advantage of a religious education,
and made livingly sensible in his childhood of the precious
influence of divine goodness extended to his soul,
he grew up in sobriety, circumspection, and in the favor of God and good men,
being preserved through the dangerous path of youth from the evils that are in the world.
When a young man and introduced into meetings of discipline,
great was the holy fear that attended his mind therein,
and his ardent desire was that he might never say
or do anything against the cause of truth.
As this fear was happily kept to,
he not only found it to be a fountain of life to preserve him from the snares of death,
but experienced it to initiate him into the rudiments of true wisdom,
by which in process of time he had skill to rule well in the house of God.

Qualified and influenced by this wisdom,
he was not only of singular service in the monthly meeting to which he belonged,
but of eminent and memorable use in the more general meetings of business, which,
while of ability of body, he attended with exemplary diligence, in this nation;
and was also much esteemed and well received by Friends in England for his visits there;
for it had pleased the Lord to endue him in a good measure
with the gifts and qualifications of an elder in his house,
and a father in the family.
Often under the fresh influence of the divine anointing,
he was enabled to drop living counsel, to the affecting and tendering of many hearts,
and to raise that life in meetings of discipline
which alone is the crown of all our religious assemblies.
Though sharp in reproof to those in general who trampled upon the testimony of truth,
or lived in a carnal security,
yet he greatly rejoiced to see the buddings forth of good desires in any of the youth,
and was a tender nursing father to such.

Strong and fervent were his desires that the youth among us,
and particularly his own children and their offspring,
might dedicate their hearts fully to the service of God,
that there might be a succession of faithful members
in the church whereof Christ is the head,
following the ancients in that self-denying path which they had walked in:
at times observing, that when Friends lived more retired and inward,
the revelation of the spirit and divine help was witnessed in a larger degree;
often desiring in his declining years,
when his natural strength and faculties gradually decayed,
that he might never survive the inward sense and
feeling of that which is the life of the soul:
also sorrowfully remarking, that some by grasping at the present visible enjoyments,
had left large possessions to their families; but their table had become a snare,
and to several there was left neither name nor memorial among us.

In religious visits to the families of Friends he was often
eminently favored and opened in suitable counsel,
in an extraordinary manner; and indeed not only on these appointed occasions,
but in more private conference with those of his family and his friends,
it was apparent he dwelt near he fountain of divine sweetness, for words of sweet savor,
edification, and tenderness would often at such times flow from him.

To conclude, he was a careful, affectionate father, husband, and friend,
helpful in a civil as well as a religious capacity among his neighbors,
and charitable to the poor.`'
He departed this life in peace, at his own house in Kilconner,
the 14th of the Fifth month, 1762,
and was interred in Friends`' burying-ground at Ballybrumhill,
in the county of Carlow aforesaid, the 17th of the same; aged seventy-six years.

--

[.asterism]
'''

GRACE CHAMBERS, an ancient and honorable Friend, of Kendall, in Westmoreland,
was born at Munckhelsden, in the county of Durham,
and while young was virtuously inclined, and when she grew up was of a strict,
exemplary life and conduct, remarkable for her plainness and simplicity of apparel,
manners, and deportment, endowed with a good understanding and benevolent disposition,
and exerted herself to the utmost of her power to be serviceable in her day.
This gained her an extensive acquaintance among Friends and others,
having occasionally free access to several families of distinction in her neighborhood,
to whom her affectionate visits were acceptable and of service,
and from whom she met with that civil and courteous behavior
which was due to one of her amiable qualities.

She had considerable skill in surgery, and in administering relief in many disorders,
which she did without fee or reward,
and was much devoted to visit the sick and those under affliction,
to whom she was greatly helpful.
Her openness and generosity to her friends and hospitality to the poor,
were very remarkable.

In the close of her time she was strong and lively in her testimony,
even when bodily strength was so much abated,
that it was with difficulty she got out to meetings;
but having been exemplary in this and other respects, she continued so to the last.

Being far advanced in years, and attended with the infirmities incident to old age,
she bore all with Christian patience and resignation to the all-wise, disposing hand,
and finished a well-spent life, accompanied with the evidence of a future well-being,
at her house at Sedgwick, near Kendall, the 22nd of the Ninth month, 1762,
and was decently interred in Friends`' burial-ground at Preston-Patrick,
the meeting she belonged to, the 26th of the same; aged eighty-five years.

[.asterism]
'''

ALICE HALL, wife of Isaac Hall, of Little-Broughton, in Cumberland,
was born the 30th of the Eleventh month, 1708, at Blackhouse, in Allendale,
in Northumberland, and daughter of John and Isabella Fetherstone,
who being religious Friends,
carefully educated their children in the principles of truth.
She was early favored with divine visitations, and being obedient thereto,
grew in religious experience to a good degree of stability and settlement therein.
Having received a gift in the ministry,
through a humble attention to the leading of the Good Shepherd,
she became skillful and serviceable in the church, and freely gave up to that service,
as she found her mind engaged and drawn thereto.

In her unmarried state she was concerned to visit friends twice in Ireland,
most parts of England, Wales, and Scotland; was both a good example in private life,
and in her public ministry,
abiding under the seasoning virtue which rendered her conversation edifying and agreeable.
After her marriage, which was in the year 1743,
she remained zealous for the cause of truth,
and was often concerned to travel in the service thereof,
visiting several parts of her native land, and Ireland a third time.

In the year 1760, she found an engaement to visit the churches in America,
which proved a very close trial, in parting from her husband and children;
but after recommending them to the protection of that hand which is forever sufficient,
she proceeded on her voyage, and landed in America in the Tenth month, 1761,
and diligently set about her services, visiting the provinces generally,
although weak in body, in company of a Friend, of Pennsylvania, named Ann Newland.
Her labors of love through the different provinces
were to the general satisfaction of Friends,
as appears by several certificates transmitted from there.

She was also enabled to visit many meetings in the
provinces of Pennsylvania and the Jerseys,
although under great bodily weakness and exercise of spirit; yet her meek, lowly,
and innocent deportment, together with her lively and edifying ministry,
made lasting impressions on many minds, and rendered her company very acceptable.

In the course of her visit, she was an example of great patience and humility,
steady in attention to her own business, and prudent in conversation,
discharging her duty faithfully in her weighty undertaking.

A little before she was confined by illness, she expressed to some Friends,
after the last public meeting she was able to attend, which was at Chester,
in New Jersey, that she was clear;
and although the yearly meeting at Philadelphia was then to be held in a few days,
she said she could not see that she should be at it.

She got to her lodging at Isaac Zane`'s, in Philadelphia, the 22nd of the Ninth month,
1762, and her distemper increasing,
notwithstanding all the tender care affection could dictate,
she expired the 6th of the Tenth month following.
She endured her last illness, which was very sharp, without any signs of murmuring,
but in lamb-like patience expressed an entire resignation in the divine will,
whether to live or die.

Her body was carried to one of the meetinghouses in Philadelphia,
and after a large and solemn meeting was decently
interred in Friends`' burial-ground in the city,
the 8th of the Tenth month, 1762.
