== Chapter 15

[.chapter-synopsis]
* Boswell Middleton
* John Goodwin
* Catharine Burling
* John Alderson
* Stephen Sedgewick
* Elizabeth Kendall
* Gharrett van Hassen
* Rachel Chandler
* David Coulson

BOSWELL MIDDLETON, of Boroughbridge, in the county of York,
having through a long course of years maintained
a steady testimony in opposition to all undue liberties,
and labored for the promotion of truth,
which he was enabled to do through divine experience and obedience to the heavenly light;
and though, through extreme old age,
his memory became impaired for the last two or three years of his life,
yet a short account of him, for the encouragement of such as may hereafter read this,
claims a place in these memoirs.

He was a diligent attender of meetings,
and peculiarly qualified for the support of discipline,
awfully waiting for the arising of that divine power which is unerring,
to direct his judgment.

He twice suffered imprisonment by a priest for the nonpayment of his demands,
about eleven years, which he bore with much Christian patience and resignation,
being exemplary in suffering, and was so attended by divine assistance,
that he fervently desired his adversary might be forgiven.

About the seventieth year of his age, his mouth was opened in public testimony,
which was sound, refreshing and edifying,
greatly to the satisfaction of the right-minded; and as he bought the truth,
he was careful not to sell it: so it may be justly said,
truth and its friends were his beloved companions,
and his conduct among men gained him love and esteem.

To some friends who visited him a little before his decease,
he appeared to be in a still, quiet, sweet, composed frame of mind,
and took his last leave of them in his usual tender and affectionate manner.

Much might be said of this worthy Friend;
but as his life was a series of close exercises and trials, it may suffice to say,
he endured them as a man whose mind was weaned from the world,
having his eye fixed on a far better country, namely, a heavenly,
into which there is no doubt of his being entered.

He departed this life the 8th of the Fifth month, 1763,
in the ninety-sixth year of his age, and a minister about twenty-seven years;
and was buried at Burton, near Barnsley, the 10th of the same.

[.asterism]
'''
JOHN GOODWIN, an ancient Friend at Eskyrgoch, in Montgomeryshire, in North Wales,
was early favored with the blessed visitation of +++[+++the Spirit of]
truth, and by faithfully adhering to the dictates thereof,
he experienced its effects to be redeeming him,
and purifying him as a vessel for the great Master`'s use.
At about the twenty-seventh year of his age, he was called to the work of the ministry,
in which, through faithfully and diligently waiting for all-sufficient help,
he became an able minister of the gospel,
and was instrumental to turn many from darkness to light,
and from the power of Satan to the power of God.
He might well be numbered among the valiants of Israel;
often visiting the principality of Wales, and, in the younger part of his life,
several parts of England.
He filled up the several duties of life with good repute, being an affectionate husband,
a tender father, a good neighbor; also, in a religious sense, a wise, nursing father,
pleasant in conversation,
yet weighty and instructive to those who inquired the way to Zion; when led to reprove,
he was careful to abide in the spirit of meekness and wisdom.
He was of an upright life and conduct,
a fervent lover of the cause of truth and people of God,
zealous of the honor of truth and the support of its testimony in all its branches.

In his younger years, when in low circumstances,
and anxious for the support of his family, he purposed removing to America, (his parents,
brother and sisters being gone there before,) but finding a stop in his mind,
and feeling after divine counsel, he found it his place to settle in his native land,
and it livingly arose in his heart that the Lord would provide for him and his family,
in which he believed.
And in the close of his days, he said with thankfulness,
the Lord had fulfilled it to him; which is worthy of commemoration,
and may serve as a way-mark to others who read this account,
to have their eye to Him in faith, with whom counsel dwells for direction,
in all their concerns of life.

He continued fresh and lively to old age, and about three weeks before his decease,
at the last public meeting he attended,
he was enabled to bear testimony in the life and
power of truth in a remarkable manner to those present,
among whom were many not in society with us.
After meeting, he said he was fully clear of the people, and released from that service;
signifying his time here was near a conclusion, and that now, after a painful affliction,
he should soon be at rest with the righteous, for which he longed; yet said,
'`Let patience have its perfect work.`'

During his illness he appeared to be in a heavenly frame of mind,
abounding with praises to God for his continued mercies,
often expressing how valuable the enjoyment of the love of God is on a dying-bed.
He desired his love might be remembered to his brethren and sisters in Christ,
being sensible and clear in his understanding to the last hour.

He quietly departed this life, as one falling into a sweet sleep,
the 7th of the Twelfth month, 1763, and was buried in Friends`' burial-ground at Llwyndee,
the 12th of the same; aged about eighty-two years.

[.asterism]
'''
CATHARINE BURLING, daughter of John and Arn Burling, of the city of New York, in America,
was taken ill of a slow fever, which weakened her gradually, so that,
to use her own expressions, she was reduced step by step;
all means used for her help proving ineffectual.

When she was brought low, and her recovery appeared doubtful,
she was for a time under great exercise of mind concerning her future state,
and prayed to the Lord for a little more time, and that she might witness a better state;
which he was graciously pleased to answer, not long after,
she saying her mind was changed.
She came to witness the child`'s state, filled with innocency, abounding in love;
often saying,
'`My mind is like a little child`'s.`' Her heart came to be filled with the love of God,
and in the aboundings thereof, for several weeks before her departure,
she was at times enabled to declare of the Lord`'s goodness to her in a wonderful manner;
and also, to exhort many who came to visit her, to amendment of life,
that when they came to lie on a sick bed they might be made
enjoyers of that peace she was then made a partaker of;
often saying she felt his peace flow in her mind as a gentle stream,
and that her cup ran over.

Though order of time may not be kept strictly to,
yet many were the sweet expressions which this young woman uttered, some of which,
as nearly as could be remembered, are as follows:

'`Many wearisome nights have I gone through, and have watered my pillow with my tears.
I was long in doubt of my eternal happiness, and in the time of greatest distress,
I cried to the Lord that he would be pleased to lengthen my time a little longer,
that I might be more fully prepared.
And he was graciously pleased to hear and grant my request;
and now he has been pleased to grant me a full assurance of it, and to lengthen my time,
that I might speak of his goodness to others, and tell what he has done for my soul.
O praises, praises, praises, be given to his great and glorious name!
My tongue is too short by far: O if, I had the tongue of an angel,
I could not sufficiently express my gratitude to that gracious God who
has been thus pleased to favor me in so eminent a manner!`'

'`My disorder is very changeable: very flattering it would be to some,
but it does not flatter me.
I am resigned to the Lord`'s will, let him do just as best pleases him with me,
his poor frail creature.
A few days ago, when I thought I was just launching into eternity,
that boundless ocean of eternity,
I prayed to the Lord that he would be pleased to give me a little longer time,
and he was graciously pleased to hear and grant my request.
The work of regeneration is a great work.
I know it now experimentally.
I am become a new creature, new thoughts, new desires,
my affections set upon things above.
I have a new name written in the Lamb`'s book of life,
and the white stone is given to me.`'

She at the same time advised her brothers and sisters to plainness of speech and apparel,
saying, '`Remember our blessed Lord, that great pattern of plainness,
who when on earth went up and down doing good, and wore a garment without seam.
He was crucified, he was nailed to the cross for our sins, for my sins:
O love inexpressible!`'

During the last five weeks of her illness she was
frequently speaking of the Lord`'s goodness to her,
being favored in an extraordinary manner; often saying,
'`I have nothing to do with this world.
O let my time be employed in praising the Lord,
and telling of his gracious dealings with my soul!`'

One evening, as her father was sitting by her bedside, she said to him,
'`You are my father, but now I have another father; I have a heavenly father.
I love you dearly, but I love him much more.
Oh! he is the chiefest of ten thousands!`'

She would often say, '`I am thankful to the Lord for all his favors conferred on me,
and when I do not speak I am thankful in my heart, and that is more than words.
The Lord does not require lip-honor, but when my heart is filled I cannot help speaking.`'

At another time, '`Many are the changes and vicissitudes I experience,
and what may come next none of us knows;
but I am resigned and thankful for all his mercies, his poor frail creature:
he must do with me just as he pleases; we should be thankful for all the Lord`'s favors.
I hope and pray that I may be kept thankful and humble, meek and low, before him,
waiting for my change, and a happy change it will be to me.`'

One morning, as her mother and sisters were putting on her clothes,
she desired them to stop, and then expressed herself to this effect:
'`I now no longer wonder that the martyrs could sing in the flames.
I could do the same.
I think I could go through burning flames, if required, for the love of Christ.
O it is inexpressible! and spoke much more, and then prayed in an extraordinary manner.

At another time she spoke to the purpose following: '`Now I know how precious the soul is.
O that people would prize their time, and prepare while health is granted them!
I bless the Lord I am prepared; if he is pleased to call me the next moment, I am ready.
But I am thankful for the little time he has granted me to be with you; but,
O how shocking,
how horribly shocking must it be for such poor souls who are unprepared
and deprived of their senses at such a time as this!`'

She often exhorted and advised many young people, at different times,
against reading romances and idle books, saying,
It has been the greatest trouble and exercise of mind to me,
more than anything I have done.
It has cost me many a wearisome night, and many a bitter tear,
though I have never read but a few, and those that were deemed the most harmless.
I know there are some who deem them innocent amusements,
and say those books are instructive, and there are good morals in them.
But, O! must we go to such books for good morals?
Read the Scriptures, which are the best of all books.
And there are other good books`'

One following the sea coming into the room, and standing by her bedside,
after a few minutes she spoke to him to this import:
'`You are one that sails on the great waters,
and there you may see God`'s wonders in the great deeps;
and you are much in company with sailors and such like men,
and I know they are light and frothy in their conversation.
I desire you to keep your mind watchful and near the Lord, which if you do,
you will be preserved in his fear.`'

When she mended, after a severe turn of illness,
one evening she called her little brothers to her,
and kissed them in a very loving manner; and then being removed to the bedside,
as she sat thereon she said, '`O I am full of love!
I feel a degree of divine love.`'
A neighbor being in the room, noticing how easy and composed her countenance was,
she answered, '`How can my countenance be sad when my mind is at peace.`'
The neighbor answering, '`Which the world cannot give, '`she returned, '`No, nor take away.`'

Two neighbors, not of our Society, coming into the room, she spoke to one of them,
saying, '`You see me very weak and low, but my mind is at peace,
sweet heavenly peace of mind.
I hope and pray that you may feel the same when you come to lie on a sick-bed.`'

Through the prevalence of her distemper, and for lack of sleep,
she became delirious for some days, with small intermissions;
and then at such intervals she seemed filled with divine love.
The last day before her departure, she bade her sister tell her mother, '`I am resigned,
patiently waiting and quietly hoping for my happy change.`'
A little before her departure, she told her father she was not afraid to die.
Soon after she said to one of her sisters, '`I feel as if I am going to paradise.`'
About noon the same day she desired her mother to tell a
friend present that she should go easy and to rest.
She departed this life, without sigh or groan, the 10th of the Fourth month, 1764,
between the hours of eight and nine in the evening, in the eighteenth year of her age,
and was decently interred in Friends`' burying-ground in New York.

[.asterism]
'''
JOHN ALDERSON, of Ravenstondale, in Westmoreland, was the son of our ancient Friends,
Ralph and Alice Alderson, of the same place,
and was educated by them in a religious manner, who both by example and precept,
were signally serviceable to him in the time of his youth, to whom he demeaned himself,
as he became truly religious, in a very dutiful manner.

About the nineteenth year of his age,
he was remarkably favored with a humbling visitation from on high,
and as he kept under it he became fitted for the work of the ministry,
into which he was called about twelve years afterwards.
In a short time he grew skillful in it, and labored with unwearied diligence,
visiting several parts of England several times: he also visited Ireland and Scotland;
in all which there is good reason to believe his labors were acceptable,
and of good service to the churches.
In time of silence he was close and steady,
in a fervent travail of spirit before the Lord;
was often enabled to unfold the deep mysteries of the kingdom and the work of regeneration;
and also strongly to press Friends to a steady watchfulness against the
many subtle wiles and temptations of the enemy of man`'s happiness.

In the beginning of the year 1764, although under great weakness of body,
he found a concern to pay a religious visit to Friends in the southern
parts of the nation and in company with his beloved friend Anthony Mason,
he came to London, but under great indisposition,
being able to attend but a few meetings in that city,
in which he appeared in public testimony, to the comfort and satisfaction of many,
particularly in the meeting of ministers and elders.
But his natural strength decreasing,
he was confined about seventeen weeks at the house of our friend Thomas Jackson,
where all necessary care and assistance were administered to him.

In the course of his illness he was led, under the influence of divine love,
to leave a few hints respecting the beginning and progress of truth upon his soul,
and expressed himself to this effect:
'`That he was mercifully visited with the dayspring from on high,
and in the light of the Lord it was clearly discovered to him,
what he should do and what he should abstain from.
But being addicted to youthful follies and vanities, he was unwilling to renounce them,
as well as to come up in obedience to the advice and admonitions
of his faithful and experienced parents in the truth.
By his disobedience he put out the candle which the Lord had lighted in his soul,
and continued for some time to walk in darkness.
In this dark and wilderness state, the Almighty, for wise purposes by him unseen,
permitted Satan to try and prove him with various temptations;
not only with the glory of temporal delights,
but with sins exceedingly sinful in their nature.
He had received a measure of light and grace, but he rebelled against it;
and though he was kept from gross pollutions, yet his vain, light, and airy mind,
and aspiring imagination, were unwilling to submit to the yoke of Christ,
to follow him in humility and self-denial.`'

As he had, by transgression against the inward law, which is light,
forfeited his right to the tree of life,
he found no way for a return but by the flaming sword,
which in an eminent manner seemed furbished for him
in order to divide the precious from the vile,
and which did execute the fierce anger of the Lord upon his transgressing nature,
which was strong, and unwilling to have sin destroyed both root and branch.
For some time the Lord executed his just judgments,
so that his terrors made him afraid that his mercy was clean gone from him forever,
which brought him to despair of attaining life eternal.`'

But when the Almighty, who redeems Zion through judgment,
was pleased to say it was enough,
and this dispensation of condemnation had humbled his spirit,
and bowed his neck to the yoke of Christ,
by the powerful operation of his spirit he became as clay in the hands of the potter;
and though the ministration of condemnation had been glorious,
he could now sing of judgment and mercy.
And as he kept faithful to the discoveries of the light,
which shone brighter to the perfect day,
he was preserved therein from turning against folly; knowing, by purchased experience,
that all who are saved from sin, and persevere in a life of righteousness,
must walk steadily in the light of the Lord.`'

While he was in the employment of a shepherd, being alone,
he was by the love of God so powerfully attracted to love him again, and all mankind,
that under the sacred influence and holy anointing thereof,
he found the gospel of salvation flowed universally towards all,
and the word of life sprang and flowed in his soul
as if he had been preaching to many people.`'

Thus this dear Friend became qualified for the work of the ministry,
a dispensation of which was given to him,
that he might show unto man the way of life and salvation.

Much excellent counsel and advice also dropped from him, in the course of his illness,
to ministers.and elders in their various states and allotments,
his understanding and memory being preserved clear and strong to the last,
being also blessed with remarkable serenity and calmness in that proving season.
Towards the close of his time, after commending every one to God,
and to the word of his grace and good spirit, he added, '`For whose sake, '`says he,
'`I have travelled in the deeps; and now, in the seeming conclusion of my time,
I witness renewed peace and divine refreshment, and with my languishing breath,
under the influence of gospel love, I am enabled to pray for the peace of our Zion,
that truth and righteousness may prosper within her gates,
and the salvation of our God may be appointed as walls and bulwarks about her city.
This is what I continue earnestly to wish, not only for my brethren and fellow-members,
but for every one who may receive the invitation of God`'s
love and be obedient to the dictates of his spirit,
and so become inhabitants of this holy city, the city of the great king,
who is ever worthy to rule and reign in the hearts of his people.`'
Then added, '`Thus having relieved my spirit,
there remains nothing but to desire my endeared love
may be remembered to my affectionate wife,
who, '`says he, '`I desire may not grieve beyond measure,
but freely resign me into the hands of my faithful Creator; also to my dear children,
with my dear aged parents and relations according to the flesh; telling them,
that through the continued lovingkindness of a merciful Savior, it is well with me.
I am favored with a comfortable evidence,
that if I am removed with the present weakness of body,
he will receive me into the arms of his mercy; and that I go to their God, and my God,
to their Father and my Father, to join the heavenly host,
in ever magnifying his love and mercy,
who has loved and washed us in the blood of the immaculate Lamb: to whom,
with the Father, through the holy spirit, be glory, honor, and praise, now,
and eternally in the heavens.
Amen.`'

He departed this life the 26th of the Fourth month, 1764, about midnight,
and his body was interred in Bunhill-fields the 30th of the same,
after a large and solemn meeting at Devonshire-house, held for that purpose:
aged nearly forty-three, and a minister about twelve years.

[.asterism]
'''
STEPHEN SEDGEWICK, an ancient Friend belonging to Bentham monthly meeting, in Yorkshire,
was born about the year 1684, and educated in the way of truth as professed by us.
When very young, he became concerned to live a sober and religious life,
frequently seeking solitary places to pour forth his soul in supplication to the Lord,
that he might know an inward acquaintance with him for himself.
As he grew in years he grew in saving knowledge,
so that about the twentieth year of his age his mouth was opened in the ministry,
and through faithfulness he became an able minister of the gospel,
having frequently to declare to others what the Lord had done for his soul,
to the encouragement of the weak and sincere mind.

He labored diligently, and visited most parts of the meetings in this nation, Scotland,
and Ireland, and was frequently engaged in visiting the families of Friends;
for which service he was eminently qualified.

During the latter part of his life he was afflicted with bodily weakness,
yet still continued a constant attender of meetings, both for worship and discipline;
and it was clearly observable, the nearer he drew towards his final change,
the more lively and bright he grew in his gift in the ministry.

His life and conduct were remarkably regular and inoffensive,
his benevolence extended to all, whereby he obtained a good report and esteem.

During his last illness he often declared to those who visited him,
that his day`'s work was done, that he had nothing to do but to die,
and that he was in true peace with the Lord and all men.

He departed this life the 10th of the Fifth month, 1764,
and was buried in Friends`' burial-ground at Lower-Bentham: aged about eighty years,
and a minister sixty years.

[.asterism]
'''
ELIZABETH KENDALL, late of Manningtree, in Essex,
was convinced of truth in her young and tender years;
although in the beginning she was not sensible what it was that followed her with reproofs,
if at any time she missed or turned out of the way
which she was convinced she should walk in;
which brought great anguish upon her tender mind,
and made her to seek solitary places to pour out her tears before the Lord,
who heard her prayers and supplications for preservation, and was her alone helper.

Her parents not being at all sensible of her trouble of mind,
and that it was for her soul`'s sake, that it might rest in the day of trouble,
began to be very harsh with her,
by threatening and using all endeavors to drive her from such thoughtfulness,
fearing it would be her ruin.
But powerful was that good hand and arm which was made bare for her support,
so that the more her suffering increased the stronger she grew.

At this time she was quite unacquainted with Friends,
not knowing there was such a people; but some time after,
her parents removing to a place near which some Friends resided,
she became acquainted with them, in whose company she was often refreshed,
and her afflicted mind much comforted.
Hearing of a meeting she found means to get to it, in which,
though there were but few words spoken, she was melted down as wax before the fire,
not wanting to hear words; but was sensible these were the people she was to join with,
which she did for peace sake, about the nineteenth year of her age.
Then did her sufferings increase by her parents,
but in a more severe manner from her father,
he having a great dislike to the name Quaker, saying,
'`I had rather she had been any thing but that, '`and spoke much against them.
Yet was she steady and immoveable,
many times having much to say in vindication of the truth, but he could not bear it,
therefore was more severe against her.

About the twenty-first year of her age she came forth in a public
testimony to the great comfort and satisfaction of Friends,
which occasioned a fresh trouble to her parents,
and made her sufferings still greater from them;
yet it did not alter her steady resolutions in pressing
forward in that which brought peace,
neither occasioned her to show any uneasiness to her parents.

One day her father being in great warmth took her
by the arm and thrust her out at the door,
saying,
'`Let me never see you more if you do not leave the Quakers;`'
she patiently bore it and went to a Friend`'s house,
who gladly received her until further way was opened.

After some time it pleased the Almighty to grant her father
a visitation of the day-spring from on high,
which brought him to a sight of his state and condition,
and made him seek a place of repentance.
He became willing to suffer and to endure the cross,
and betook himself to a very circumspect way of life and after a considerable time,
hearing his daughter was to be at a meeting near where he resided,
he privately got to it; in which she was favored to bear a living testimony to the truth,
and was made instrumental to his being fully convinced.
After meeting he embraced her with tears, saying, '`My dear child, hold on your way,
fear no man, you are in the right.`'
And from that time he constantly went to meetings;
and continued faithful to the end of his time; some time after his wife, one son,
and another daughter, joined Friends.

After some time she settled at Bradfield, near Manningtree in Essex,
and being freely given up to the Lord`'s requirings, grew much in the truth;
her testimony was large, lively, and powerful,
to the great comfort and satisfaction of the honest-hearted.
She was often concerned to go forth and leave all that was near and dear to her behind;
was several times drawn to visit friends in this nation, once in Ireland,
twice in Wales and Scotland, and in all was well received.
She appeared much to the consolation of the afflicted,
but as a sharp threshing instrument to the careless,
and to the stirring up and awakening many.

A pattern of plainness and true humility, zealous for promoting the truth,
having no greater joy than to see its professors prosper in it,
nor spared any pains to admonish or rebuke where occasion required.

For several years before her decease she was attended with great bodily weakness,
yet as long as it was possible to be had to meetings did not give it over.
Soon after her being disabled from attending meetings,
she was taken with something of the palsy, which affected her speech,
so that she could not well express herself, but was sometimes understood to say, '`I love,
I love all;`' nothing more pleasant to her than to see her friends.
She was often retired in her mind, sweetness appearing in her countenance;
a pattern of patience, not finding fault with what was done for her,
nor heard to say it was hard she should be afflicted with so many weaknesses;
but always appearing in an easy frame of mind with great pleasantness,
endeavoring to make those about her sensible she
counted it a great favor she was provided for.

She departed this life the 19th, and was interred the 24th of the Second month, 1765,
in Friends`' burial-ground at Manningtree, about the eightieth year of her age,
having been a minister about fifty-eight years.

[.asterism]
'''
GHARRETT VAN HASSEN, an ancient friend of Dublin, was born in Holland.
He was a signal instance of the mercy and long forbearance of a gracious God,
having been favored with a divine and powerful visitation
about the fortieth year of his age,
and thereby reclaimed from a state of unregeneracy and sin, witnessing true repentance.
He joined in society with us the people called Quakers, and through faithfulness,
being led on in the paths of piety and love to God and men,
he received a gift in the ministry in England,
and about the year 1737 he went to Ireland,
and for the most part of the remainder of his time resided at Dublin.

He was a fervent laborer in the ministry,
and zealous in his testimony against the inordinate love of the world,
affectionately tender to the youth, and was often concerned for their preservation.

He visited the meetings of friends in Great Britain;
and in the year 1747 he performed a visit to most
or all the families of friends in Ireland,
and also to such as had by misconduct justly incurred the censure of the Society;
in which labor he was well received, having extensive charity.

During the latter part of his time, he was greatly afflicted with bodily infirmities,
disabling him in a great measure for public service;
but he still retained his love to God and the brethren,
and at or near his conclusion had the comfortable
assurance of his removal to a better state,
which he signified by the following expressions among others:
'`I am going to your Father and my Father; to your God and my God.
I die daily, nevertheless I live, and not I, but Christ lives in me.`'

He departed this life the 30th of the Sixth month, 1764; aged about seventy,
and a minister upwards of twenty-eight years.

[.asterism]
'''
RACHEL CHANDLER, formerly PENFOLD, was born at Guildford, in the county of Surry.
Her mother dying when she was young, subjected her to many inconveniences,
which she occasionally mentioned;
but being favored with an early visitation of divine love,
was preserved from the grosser pollutions of the age.
By gradually submitting to the sanctifying operation of +++[+++the Spirit of]
truth, she was fitted for the work of the ministry,
and diligently laboring to improve the talent committed to her trust,
in due time became an able minister of the gospel, sound in doctrine,
rightly dividing the word of truth.
She travelled through several parts of this nation in full unity with her friends,
and to the peace and satisfaction of her own mind.

Her ministry was attended with a lively demonstration of the spring from which it flowed;
she was often favored with near access to the throne of grace,
in fervent supplication for the restoration of Zion to her primitive purity and beauty;
and in commemoration of the Lord`'s goodness to her
through the various dispensations of his providence,
would frequently exhort the youth to remember their Creator in the days of their youth,
and dedicate the prime of their days to his service.

She was a nursing mother to the tender and well-inclined,
and a true sympathizer with the bowed-down and afflicted in spirit,
but a sharp reprover of the rebellious and stiff-necked;
an affectionate friend and kind neighbor; a pattern of industry, humility,
and self-denial;
a good example in discharging the several relative duties
suitable to her station and circumstances in life,
which made her beloved both by friends and others.

She was long afflicted with a sore disorder,
which rendered her incapable of traveling for a considerable time;
but she constantly attended her own meeting, and after, when her inability increased,
the meeting was held at her house, where she frequently appeared in public testimony,
under a living sense that the Lord had not forsaken
her in this time of outward affliction.

To her husband and a friend who came to see her, she said, if she died then,
her desire was that they would look to their own standing, and not grieve for her,
but rather rejoice she was landed safely from a world of peril and difficulty,
a life of temptation and probation;
that the last thing she had to struggle with was death, and that was made easy,
the sting thereof being taken away.

At another time, being in great pain, +++[+++she said,]
Oh! if I had my peace to make now, what should I do!
It is enough to bear the infirmities of the body without the load of a guilty conscience.`'
Being a little easier, she said that her pain was often very strong,
yet at times she witnessed great sweetness,
which supported and enabled her to bear her affliction; further adding,
a little of the balm of Gilead was very comfortable to her,
and that she longed for the time to come when she might
drink large draughts of water from the well of life.

She was several months confined to her bed,
but bore her affliction with remarkable patience and resignation,
and continued sensible to her end, departing this life the 18th of the Fifth month, 1765,
and was interred in Friends`' burial-ground at Kingston the 24th of the same;
aged forty-two, and a minister sixteen years.

A few months before her death,
she drew up a brief memorial of the gracious dealings of the Lord with her soul,
which she desired might be communicated to Friends, and is here annexed.

[.asterism]
'''

A brief memorial of the Lord`'s gracious dealings with RACHEL CHANDLER,
formerly RACHEL PENFOLD, late of Esher in Surry,
written by herself a few months before her decease,
and at her particular request communicated to Friends.`'

'`When I consider that the grave cannot celebrate the praise that is due
to the Lord on account of his gracious and merciful dealings to my soul,
I am inclined to say so much on God`'s behalf as may suffice to let mankind know,
that he of his own free mercy first visited my soul,
when it was gone very far astray from the right path,
and at about the seventeenth year of my age,
laid the axe to the root of the corrupt tree, and shook my sandy foundation;
so that my feeble building, grounded on profession and name, was made to totter,
and I to cry out in the anguish of my spirit,
What shall I do to become what I ought to be,
that so I might obtain favor and peace with God!`'

'`Such was my sorrow night and day, that I often wished I had never been born,
or that I had died very young, before I had knowledge of good and evil;
for now that the book of the law was opened, the commandment came,
sin revived that had been hid and covered with a fig-leaf covering, and I died;
and as one sensible of the terrors of the Lord, I often cried,
O wretched creature that I am, who shall deliver me from this body of sin and death?`'

Thus went I secretly mourning on my way for a long time,
while my adversary laid many baits in my way to catch my unwary feet;
yet whenever I yielded to the forcible power of conviction,
though in ever so trivial things, I found peace.
But as I had gone a great way from the Father`'s house, so I had a great way to come back,
and it took up much time,
for there was a long war between the house of Saul and the house of David;
but blessed be God, the father and fountain of life,
the house of David grew stronger as the house of Saul grew weaker,
so that in time my enemies were discomfitted,
and what I had seen and heard in secret at the bottom
of Jordan and in the depth of the sea,
was I required to proclaim as on the house-top.
This was so weighty an engagement, that it took up much time to be fitted for,
lest no-t being rightly prepared I should be drawn in a
forward zeal to do that which was not required of me,
as poor Uzzah did, or being rightly anointed, yet through a forward mind to be doing,
should be hastily drawn to offer sacrifice before Samuel came.
After repeated manifestations and convincing circumstances had been afforded,
yet the confirming evidence being lacking,
I dared not appear in public testimony for God, until, Gideon-like,
I had tried the fleece every way,
by which the long-forbearance of the Lord was discovered to me-ward,
who knew my withholding was not from obstinate rebellion,
but through fear of taking that on me which I was not called to,
and that my desire in doing his work was that I might be his servant,
and found answering the end for which I was made, that, rightly improving my talent,
I might at last have an entrance into the joy of my Lord.`'

At length,
having waited the season for the accomplishing the
work of manifesting my love by my obedience,
I gave up in great weakness and trembling to speak a few words in meetings,
in the twenty-sixth year of my age, and had great peace in so doing.
Although I have never been called to much service, yet,
having one talent committed to my trust,
I have found an absolute necessity to improve the small portion of grace received,
and also to watch and guard against temptations, which I have had my share of many ways,
but find none more dangerous nor subtle than self, the most cruel foe,
of which I am the more free to speak in order to inform others,
that they may beware and not attribute that honor to self which belongs to God.
I have seen it in many shapes, had many a combat with it, and do rejoice in this,
to see it under foot and the Lord to be uppermost.
There self is of no reputation; and that I may still witness this,
that as my eye has been steadily fixed on my good guide,
who first found me out when alone in a desert land,
and a concern has been raised to follow him only in the way of his leadings,
so he also may have the glory and praise in conducting me safely
thus far on my journey through many difficulties and straits,
which but only to look back upon makes me shudder,
insomuch that approaching death appears a pleasant
release from a world of trials and besetments,
which while here we are liable to.`'

'`I am ready to conclude my work is almost done, my day nearly at an end,
my sun nigh setting,
in which the curtain of the night will be drawn over my earthly tabernacle,
which pain and weakness make to shake, so that I suppose what I do,
I had need to do quickly, for no device or work can be done when the spirit is departed.
Therefore having love to my fellow-citizens, as well as goodwill to strangers,
I am willing for their encouragement to leave this
small hint of the goodness of God to a poor worm,
who am far from being able to speak one half of what has been done for me,
only that men may glorify God when they find my footsteps,
and consider that as weak as I have been,
yet the great condescension of divine wisdom and omnipotence is such,
that now being confined as a prisoner at home by my incurable malady in the flesh,
my spirit is at liberty to praise God and give glory to him,
under a renewed sense that I have so far fought the good fight,
and have been hitherto helped to keep the faith.
I feel peace to be my reward, which makes ample amends for all my sorrows, yes,
and the present pain.
Hallelujah to God on high, peace on earth, and goodwill to men, says my soul.
O let all cleave to him as to a most sure and certain guide,
who will not leave his people comfortless,
blessed be his name! but will come again and cause them to rejoice,
and their joy shall exceed the joy of harvest, when corn and wine increase.`'
RACHEL CHANDLER.

Esher, Ninth month, 1764.

[.asterism]
'''
DAVID COULSON, was born at Nottingham, the 9th of the Fourth month, 1713,
of religious parents, and educated in the way of truth.
In his youth he was strongly addicted to vain amusements and company,
gratifying himself therein for some years.
His father dying when he was young, he was much labored with by his tender mother,
who with many tears sought his reformation, which often affected him for a short space;
but still his inclination to vanity was so great,
that he stifled the convictions of truth.

About the twenty-first year of his age, happening to lodge in a damp bed,
an inflammation in his eyes followed, by which he lost his sight,
and being visited with sickness, was reduced very low.
Nevertheless he did not break off from his companions,
their vain conversation serving for an excuse to divert him in his dull situation,
and although pain and sorrow of heart were often his portion,
yet it was hard for him to take up the cross and follow Christ in the way of self-denial,
until about the twenty-sixth year of his age, when a powerful visitation was extended,
that he dared no longer to resist.
He had to see that if he did not join in therewith,
it would be the last visitation that would be afforded;
he therefore consulted not with flesh and blood, but gave up to the heavenly vision;
of the humiliation of which day he would often speak with reverence and gratitude.

About the thirty-third year of his age,
his mouth was first opened to declare to others what God had done for his soul,
and a concern was soon raised in him to visit the churches; to which,
notwithstanding his lack of sight, he gave up, and excepting Kent and Sussex,
he visited all the counties in England, and some of them several times;
and through the merciful care and protection of his great Lord and Master,
he was so preserved as never to meet with any fall or accident
to lay him up one day in all his travels.

For some years before his death, he was afflicted with a sharp,
painful disorder in his stomach and bowels,
which rendered traveling on horseback impracticable,
yet occasionally attended some neighboring +++[+++meeting]
or the quarterly meeting he belonged to; under all which he had to remark,
that he had not neglected his day`'s work, in which, he said, he found peace,
and that he could say without boasting,
he never had omitted anything that he apprehended his duty.

The next day after his return from the circular-meeting at Stourbridge, he was taken ill,
and continued so for some time, but at times got out to meetings.
On the 24th of the Eleventh month, 1765, in the afternoon he went to meeting,
and in the evening had an acceptable time in the family,
in which the divine life spread like to the odor of the precious ointment.

In the course of his illness he dropped many heavenly expressions, some of which follow:
'`O! it is a good thing to live near the Lord while in health,
for I find it now enough to do to grapple with the pain of the body.
But I thank God I am quite easy whether I live or die.
Death is no terror, for my life is in Christ, and the Lord sweetens every bitter cup.
But it is not so with those who follow lying vanities,
for they are forsaking their own mercies.
The Lord can bring low, and can raise again, at his pleasure.
If I should at this time be restored, I hope I shall be more redeemed,
and brought nearer the Lord in that pure covenant of life.
I often think what will become of them that are lukewarm in religion,
for if we keep ever so near the Lord, and serve him with all our mind and strength,
we have nothing to spare, no, no; we are but unprofitable servants,
we have done but that which is our duty.
I pray God support me under all the trials and exercises of this day.`'

To one who attended him, he said to this effect: '`Keep near the Lord,
and seek him with all your heart, for you know not how soon the messenger may come,
whether at midnight, at cock-crow, or at the dawning of the day.
O let nothing hinder you from seeking him!
Look not at your poverty, for what signifies all the greatness and riches of this world?
if we keep near the Lord, he can be abundantly more than this unto us.`'

To another he said, '`O poor girl, serve the Lord! you can never do anything better;
the Lord loves an early sacrifice; give him, therefore, the sacrifice of your youth.
I can say nothing more than to desire you to keep near the Lord, for I wish you all well.
The Lord has been my strength and preserver, my all in all; the Lord is my shepherd.`'

To some friends coming into the room: '`Now, friends,
do you think it is fit-to put off repentance to such an hour as this?
O, it is a sad thing! for we all know we must die, it cannot be otherwise with any.
But if we take not up our daily cross, and be regenerated and born again,
we cannot see the kingdom, much less enter into it.
The Lord can bring low and raise again, blessed be his holy name; his holy will be done,
come life, come death.`'

The latter part of the day he spoke little, but lay in a sweet disposition,
desiring to be still, was sensible to the last, and quietly departed this life,
as one going into a sweet sleep, about the second hour in the morning,
the 9th of the Twelfth month, 1765; aged fifty-two, and a minister twenty years.
