== Chapter 16

[.chapter-synopsis]
* Lucy Ecroyd
* Joseph Milthorp
* Alice Alderson
* Mary Waring
* Candia Corbyn
* Richard Hipsley
* Edmund Peckover
* Elizabeth Roberts
* Kezia Day
* Benjamin Trotter
* Rebecca Smith
* Thomas Dann
* John Burton
* William Reckitt
* Joshua Toft

LUCY ECROYD, wife of John Ecroyd, of Edge-End, in the county of Lancaster,
and daughter of James and Ann Bradley, of Bromyard, in Herefordshire,
was mercifully visited with the manifestation of divine grace while very young.
The tender care of an affectionate parent, who watched over her children for good,
was blessed to her in an eminent manner;
the wholesome advice she was frequently concerned to administer,
made deep and awful impressions on her mind,
though she was soon deprived of this great blessing,
her mother dying when she was about thirteen years of age.
After which, being exposed to unprofitable company,
she found the truth of the apostle`'s assertion,
that "`Evil communications corrupt good manners;`" for she was thereby drawn into vanity,
leavened into the spirit of this world, and too much attached to its fading enjoyments.
In this time of forgetfulness and departure from her first love,
she met with many close inward trials and outward disappointments,
finding no rest to her weary soul, till passing through judgment,
by which Zion must be redeemed, and enduring many sore conflicts,
her feet were mercifully turned into the way of peace.

About the nineteenth year of her age, her mouth was first opened by way of testimony,
being a good example in word, in conduct, in charity, in faith and purity,
she adorned the doctrine of our Lord.
Much might be added to commemorate her worth,
the innocency of her deportment and exemplary conduct
through the various parts of her service,
whether in her public station or more private service; let it suffice to say,
her heart was devoted to God, and from there out of the good treasures thereof,
she brought forth things new and old.

About the twenty-fourth year of her age she visited London,
in company with her beloved friend Rebecca Smith, of Nailsworth, in Gloucestershire,
since deceased, where her service was very acceptable.
Indeed, it may be recorded to the memory of them both,
they were instrumental of good to many in their said visit; and,
in all her services being carefully concerned to keep under
the guidance of the holy hand which put her forth,
she was kept in the right line, conducted therein with safety through her service,
and was favored with the return of peace in her own bosom.

In the latter part of her life, when in health,
she frequently intimated a persuasion that her race was nearly over,
expressing a fervent desire that, through divine mercy, she might be enabled,
by patient continuance in well-doing, to hold out to the end.
Thus she retained her integrity to the close of life,
ever preferring Zion`'s welfare before her chiefest joy.

In her last illness she spoke but little;
but her patience under such great bodily affliction,
and the sweet composure of her countenance and deportment,
clearly evinced she had access to the place where prayer is wont to be made.
She departed this life the 26th of the First month, 1776,
and was interred in Friends`' burial-ground in Marsden, in Lancashire;
aged forty-one years.

[.asterism]
'''
JOSEPH MILTHORP, a member of Pontefract monthly meeting, in Yorkshire,
was educated in the principles of the church of England.
But as he advanced towards man`'s estate, being of a thoughtful disposition,
and unsatisfied with the principles of his education, he,
after various researches among the different modes of profession,
joined himself to the Romish church,
and for several years constantly attended their worship,
and strictly observed their ceremonial institutions,
for some time firmly believing Christ Jesus to be the author thereof.
At times he was led to believe there was a subduing
of the passions and a renovation of heart,
which the truly righteous experienced, also a fruition of inward peace,
which they at times possessed; to all which he found himself,
in great measure a stranger.
This caused him many times secretly to mourn and
pour forth earnest prayers to the Father of mercies,
that he might become a partaker of the same happy experience.

While he was thus exercised it came into his mind
to go to a meeting of the people called Quakers,
for an account of which see his own words, in a letter.
He writes '`I sat at ease a long time,
yet earnestly desired that if the Lord had any particular regard to that people,
or approved of their manner of worship, he would make me sensible of it.
Being thus set and grown weary of silent waiting, divine power seized upon my body,
soul and spirit, which caused me to break out into abundance of tears,
and my body greatly to tremble.
Then said I, O Lord! why am I thus?
To which inward cry of mine, something which till then I knew not,
though I had often felt a measure of the same power, though never to that degree,
answered, '`If you did but love the Lord your God with all your heart, mind and soul,
that love would be so prevalent over you, that it would teach you what to do,
and what to leave undone.`'
O the surprising state I then found myself in!
How was my heart then filled with love, peace and joy unspeakable and full of glory!
Soon after, an honest Friend stood up in tears and much trembling, and said,
It is an excellent thing if we can say of a truth, Jesus Christ lives in us.
These words reached my state, I then bowed in my mind,
adoring the divine power that then influenced me, and said,
Dear Lord! if you are he that I have long sought and mourned for, tell me,
O you that have ravished my heart! what I should do to be saved,
or to continue in your favor?
Upon which the humble Jesus, the divine bridegroom of my soul, affectionately answered,
'`I require no rite or ceremonial worship of you, but that you give up your heart.
It is there I would reign, it is there I would rule,
and there I would be worshipped in spirit and truth.`'

It was some time before he could get from under the
prejudices he had in favor of the Roman church,
but continued to frequent both the mass house and Friends`' meetings,
until through a further visitation by an instrumental means, he was effectually reached,
became a valuable and useful member, exemplary in conduct,
careful to have the discipline maintained,
and at times was concerned in a short testimony, which was very acceptable.
+++[+++He was]
a peaceable neighbor, and being of extensive knowledge,
was capable of advising in many cases, which he was always ready to do,
demonstrating that the living divine principle he had embraced,
led him to the exercise of every Christian virtue.

For several years before his death, he was at times sorely afflicted with disease,
the acuteness of which he bore with exemplary patience.
His last illness was short,
and apparently attended with no symptoms of death till near the time of his departure;
and though he was suddenly called, yet not unprepared, for,
being asked a little before his death how he was, he expressed himself thus:
'`I am pretty easy, though not without some bodily pain,
yet inward comfort helps greatly;`' and added, '`I am weary, weary of this world,
if it would please Providence to take me to himself, O how acceptable it would be!`'

He departed this life the 3rd, and was interred the 5th of the Seventh month, 1766,
in Friends`' burial-ground at Burton; aged about fifty years.

[.asterism]
'''
ALICE ALDERSON, wife of Ralph Alderson, of Ravenstondale, in the county of Westmoreland,
was convinced of truth in her young years,
and carefully abiding under its divine teachings
consistent to the advice of the wise king Solomon,
"`Trust in the Lord with all your heart,
and lean not to your own understanding,`" she came to receive a gift in the ministry,
and though for a considerable time in a few words,
yet greatly to the edification of the church.
Being faithful in a little, she witnessed an increase therein, and,
clothed with the comeliness of the gospel, became valuable in the Lord`'s house,
devoting the prime and flower of her youth, her middle age and decline of life,
to his service; laboring diligently in the cause of truth, both in England, Scotland,
and Ireland, and once in America; in all which, her labors of love were well received,
and tended much to the edification of the church.
In her ministry, though she had not much human learning,
she was frequently furnished with copious expressions
well adapted to the matter she had to deliver,
deep and weighty in her delivery,
and enabled to speak feelingly to the state of meetings and individuals.
She was remarkably diligent in attending meetings when at home, even to old age,
often signifying that she believed none would be injured thereby;
their outward circumstances,
as the blessing of Divine Providence upon the honest endeavors of the faithful
would be ample recompense for all their labor and seeming loss of time.
When old age had so far weakened her constitution that she could no longer attend meetings,
she retained the divine anointing which had been
her support through the various stages of life.

The last meeting she was at, being the day she took to her bed,
she had to revive the encouraging invitation of the prophet Hosea,
"`Come and let us return unto the Lord, for he has torn and he will heal us;
he has smitten and he will bind us up; after two days will he revive us;
in the third day he will raise us up, and we shall live in his sight.
Then shall we know, if we follow on to know the Lord,
his going forth is prepared as the morning, and he shall come to us as the rain,
as the latter and former rain unto the earth.`" Hosea 6:1-3.

A few days before her departure, when some friends were sitting by her,
she was remarkably favored with the overshadowing of divine goodness,
wherein she had weightily to caution ministers and elders
to be exceedingly watchful over their own spirits,
strongly advising them to live in the bond of love and unity,
signifying she clearly saw the subtle enemy of man`'s
happiness endeavoring to draw them aside,
in order to mar or deface that work which Divine
Providence allotted them to be engaged in,
saying that the Lord had permitted her to be buffeted and brought low,
even to the gates of hell,
and had again in great mercy lifted up her head and
given her the glorious earnest of eternal happiness;
concluding in fervent prayer for the small meeting she was a member of,
and for all the small gatherings of the Lord`'s people the world over.

In the time of her illness she was afflicted with exceedingly sharp pain,
which she bore with great resignation,
often praying for patience to bear what might be permitted to be laid on her.
A divine serenity and sweetness accompanied her last moments,
that indeed it might be said her sun went down in brightness.

She departed this life on the 15th of the Eighth month, 1766,
and was honorably interred in Friends`' burial-ground the 18th of the same,
at Ravenstondale, accompanied by many Friends and others; aged eighty-eight,
and a minister sixty years.

[.asterism]
'''
MARY WARING, late wife of Jeremiah Waring, of Wandsworth, in the county of Surry,
and widow of Daniel Weston, of Ratcliffe, was the daughter of Joseph Pace, of Southwark;
being favored with an early visitation of divine love,
she was clearly convinced of the evil tendency of those undue liberties
whereby too many of our unwary youth have been ensnared and gone astray.
As she submitted to the sanctifying operation of truth,
her mind was redeemed from a vain manner of life,
and gradually fitted for the work of the ministry;
and being careful to improve the gift received,
she became an able minister of the gospel, sound in doctrine,
and skillful in dividing the word aright.

She travelled much in the service of truth,
having at sundry times visited Friends in most of the counties of England and Wales,
and once most of the colonies on the continent of America;
in all which her service was acceptable,
and she labored much for the preservation of good order and discipline in the church.
Of an open, generous, and charitable disposition, a lover of truth and the friends of it,
and was much beloved by them.

In her last illness, which was lingering and painful,
being confined from meeting about six months,
she was favored with some acceptable visits from several of her friends,
and would frequently say to them that her mind was preserved in a calm,
peaceable resignation to the divine will.

Among other expressions of weight which she uttered, the following are remembered:
that she believed herself near her end,
for she did not see that she had any thing more of religious duties to do,
meaning of a public nature; `'For,`' said she, when I look at our meetings,
I seem to have no concern there;
and whereas I used to be anxious about the quarterly meetings,
I now scarcely think of them, yet, '`added, '`I wish well to the cause,
and believe it will prosper, but that a trying day will come first.`'

She departed this life at Wandsworth, the 9th of the Tenth month, 1766,
and was buried at Ratcliffe, near London, the 16th of the same, attended by many friends;
aged fifty-four, and a minister thirty years.

[.asterism]
'''
CANDIA CORBYN, wife of John Corbyn, of the city of Worcester,
was born about the year 1671, at Pontypool, in Monmouthshire,
and about the eighteenth year of her age, was reached by truth,
through the powerful ministry of Thomas Wilson, which, taking deep root in her heart,
she brought forth good fruits.

In a few years she received a gift in the ministry,
in the exercise of which she was sound and clear,
and evidently favored with the renewings of that
divine life which preserved her fresh and green;
being often tenderly concerned both in testimony and supplication on behalf of the youth,
that their tender minds might be preserved from the many snares that lie in the way,
and be so formed and enlarged by the divine hand,
as to become living branches in the true vine, and serviceable members in society.

She was frequently engaged to bear testimony to the
universality and sufficiency of the grace of God,
extended through the Christian dispensation, to all mankind;
and she earnestly labored that Friends would retain
a grateful sense of the liberties we now enjoy,
to hold our religious meetings without molestation; often recounting the many hardships,
which she well remembered,
our ancient Friends were permitted to undergo for the trial of their faith.

She continued a diligent attender of meetings both for worship and discipline,
in love and charity as a mother in Israel, faithfully discharging her duty towards all,
hospitable to strangers, a friend to all, especially the poor, fatherless, and widow;
in her connections in life, a steady pattern of piety and virtue, so that it may be said,
in doctrine and practice,
the dew of heaven rested on her branches even to very advanced age.

Her last illness being but short,
she calmly departed this life the 28th of the Fourth month, 1767,
and her remains were decently interred in Friends`' burial-ground
at Worcester the 3rd of the Fifth month following;
aged ninety-six, and a minister seventy-three years.

Although no expressions of this ancient friend are preserved,
yet as through a long course of years she was preserved unspotted and strong in her love,
as was the case of Caleb formerly, the account is worthy of preservation,
that all may see and be encouraged, that if they keep to this living divine principle,
they will be enabled to hold out to the end.

[.asterism]
'''
RICHARD HIPSLEY, a member of Claverham monthly meeting, in the county of Somerset,
was born in the parish of Church-hill, in the said county, about the year 1708:
his parents were religious, faithful Friends,
who carefully educated him in the way of truth, and as he grew in years he grew in grace,
by which his understanding was opened and enlarged,
that about the thirty-fifth year of his age his mouth was first opened in a public testimony,
in which he was very diffident and cautious.
And the Lord, who knew his sincerity, was pleased so to enlarge his heart therein,
that he became an able minister,
and being fitted and prepared he could no longer withhold,
but was concerned to visit several parts of this nation and Ireland,
to general satisfaction.

He was eminently qualified to speak a word in season, in monthly and quarterly meetings,
which he was diligent in attending, as well as frequently the yearly meeting in London.

He was a man of a cheerful spirit, pleasant and affable in conversation, a good husband,
and tender father, a kind neighbor, doing to all as he would be done unto;
his house and heart were open to entertain his friends.

He was afflicted with a long illness, the dropsy, and was often in great pain,
which he bore with much patience, believing his departure drew near,
frequently expressing his resignation to the divine will,
and often signified to them who visited him in his illness,
that it appeared to him all was well, and that he had nothing to do but to die.

He quietly departed this life the 8th of the Fifth month, 1767,
and was buried in Friends`' burial-ground at Sidcott, the 13th of the same,
accompanied by a large number of friends and others,
where several living and powerful testimonies were borne,
to the satisfaction and comfort of those who were present.

[.asterism]
'''
EDMUND PECKOVER, of Wells, in Norfolk, was the son of Joseph and Catharine Peckover,
both persons of great esteem in the Society.
He was early favored with a divine visitation,
of which a more particular account cannot be given than
is in a paper found in his own hand-writing.

[.embedded-content-document.paper]
--

The tender dealings of the Almighty with me in my youth,
being often fresh in my remembrance, brings a most grateful sense thereof over my mind,
under which I cannot but with reverence commemorate the same.
It was no small advantage to me, that I was favored with religious and godly parents,
whose concern and care to bring me and the rest of their children
up in the nurture and admonition of the Lord was great.
What I look upon as very remarkable, is,
that before I arrived at an age capable to retain those good and wholesome admonitions,
which in the wisdom of God, they often communicated to me,
I felt the good hand of the Lord at work in me,
in a manner suitable to my tender capacity,
impressing upon my heart a living sense of his greatness and goodness,
which often brought me under much awfulness and fear,
dreading to do anything that I knew was not well-pleasing in his sight.

Here I could distinguish that I had peace and satisfaction,
and met with encouragement in myself, beyond what I am able to express;
and when I had been drawn away into anything which tended
to hinder my growth in that which I found to my soul`'s advantage,
sorrow and trouble took hold of me.
Under a sense hereof, I often made vows and promises,
that I would never join with the like again, which being my first-fruits before the Lord,
I believe he had a tender regard to,
and often assisted me to perform those covenants into which,
through some good measure of divine influence, I then entered.

In the time of this exercise, great and many were the conflicts I had to encounter with;
but, to the praise of his great name, I speak it,
his compassionate fatherly care was over me,
and always attended me with such a portion of his divine and saving grace,
that I knew preservation thereby through things of the most trying and pinching nature,
in the experience whereof thankfulness would arise.

--

Thus through faithfulness to the divine manifestations,
he was early anointed to preach the gospel, even in his minority,
while at the school of our friend Gilbert Thompson (mentioned in
the forepart of this treatise) in the fifteenth year of his age.
And as he abode in faithfulness he increased in his gift, and in the year 1714,
and in the eighteenth year of his age, in company with Edward Upshur, of Colchester,
he visited several counties; and also Ireland, about the twentieth year of his age,
in company with George Gibson, as well as most parts of this nation, Scotland, Ireland,
and America, in the succeeding part of his time.

He was indeed an elder worthy of double honor,
being of an exemplary life and unstained character,
and in the exercise of his gift frequently opened and enlarged in divine counsel,
and as a cloud filled with celestial rain to the reviving
and refreshment of the living heritage of God.
Zealous for the prosperity of the church and for the ingathering of all,
he spared not to spend himself in the strength of his days,
and divine goodness was pleased to preserve him a strong
man and an able minister for a long course of years.
He usually delivered himself with great fervency in the
flowing forth of divine love upon his spirit.

About three years before his decease, he received a shock of a paralytic kind,
which both in his own apprehension and that of his friends,
seemed to threaten him with a hasty dissolution.
Under this affecting visitation,
by the account of a relation who visited him the same evening,
he was graciously preserved in a broken, tender, living frame,
and expressed himself after this manner:
that he had now the satisfaction of a good conscience,
and of having discharged himself in the duty required of him,
according to the ability afforded him; declaring at the same time,
the great consolation he inwardly enjoyed.
The next morning after a short sleep, and taking some little refreshment,
he was somewhat revived,
and signified he was well pleased that his outward affairs were settled,
and was fully satisfied with the manner in which they were ordered.
That he was entirely resigned to the disposal of all-wise Providence,
whether it might be to lengthen his days or to take him hence;
but he felt a blessed assurance,
and found the Lord who had been his support through many trials,
from his youth to his advanced years, still to be near him, and could experimentally say,
his Redeemer lived, who has been the strength of his faithful people,
and who had brought to pass many things in his no short pilgrimage,
which to outward appearance seemed very unlikely.

After this he lay in a sweet and quiet frame, and his pain lessening,
he appeared pretty cheerful,
and in time he became so far restored as to be able to go abroad in a carriage,
but with considerable difficulty to himself.
And though in common conversation his apprehension and memory seemed much impaired,
yet his public appearance in meetings continued sound, consistent, and savory.

A few months before his death he was rendered totally unable to attend meetings,
and continued gradually to decline, and the gracious Lord,
who had been his strength and stay in the prime of his life,
supported him in his last moments,
for then he appeared to be favored with a comfortable foretaste
of that glorious immortality which is prepared for the righteous.
Though he was deprived of bodily strength to speak so distinctly as usual,
yet he was sufficiently understood to intimate the
inexpressible joy and felicity that he felt,
and seemed to pass away as with a heavenly song of divine praise in his mouth.

He departed this life at Wells, the 19th of the Seventh month, 1767,
and his remains were interred at Fakenham, the 22nd,
after a large and solemn meeting of relations, friends, and neighbors;
aged about seventy-two, and a minister about fifty-seven years.

[.asterism]
'''
ELIZABETH ROBERTS, late wife of William Roberts of Edmundsbury, in Suffolk,
was daughter of James Morley, of Wymondham, in Norfolk.
This our friend was early impressed with a sense of religion, which attending to,
she grew in grace and in the knowledge of the truth.
About the twenty-second year of her age she was raised up to bear testimony thereto,
in which she faithfully labored in much zeal and Christian love for some years.
In conduct and behavior she was exemplary, as well as in word and doctrine instructive,
devoting the prime of her youth and health to the service of truth.

About two years before her decease she fell into a great decline of bodily strength,
which disabled her from traveling;
but she retained a lively sense of the divine goodness,
rejoicing that she had in the time of health and strength been
diligent to do her duty according to ability received.

She bore her affliction, which was great, with becoming patience and resignation,
and the day she died,
prayed the Lord to be with her to the last and give her an easy passage;
which it is believed she happily experienced,
passing away without any apparent uneasiness, at the age of forty-one years,
the 9th of the Tenth month, 1767.

[.asterism]
'''
KEZIA DAY, late wife of Samuel Day, of Stansted Mountfitchet, in the county of Essex,
was visited in her tender years, and being faithful, had, at times,
to recommend her friends to the internal teacher,
and being careful not to move in the wind, earthquake, or fire,
but waiting to hear the still small voice,
her appearances were truly satisfactory and comfortable to the living.
In the course of her bodily weakness she was enabled to bear her affliction with patience,
and being weaned from a dependence on visibles,
her attention seemed to be fixed on an everlasting inheritance.
She was favored with much serenity, and a comfortable evidence,
that He who had been her support in life,
would preserve her to a happy conclusion in his favor,
and that she should enter the joy of her Lord.
Her lively exhortations and sincere breathings to God near
her end were to the comfort and edification of those present,
to whom she had to declare, that the truth had been her preservation until that time;
having to acknowledge the riches of divine love.
She desired, that those with whom she was most nearly connected would give her up freely,
and not grieve too much, but rather rejoice in hope.
At another time she said, she hoped she had been faithful to what had been required.
She quietly departed this life without sigh or groan, on the 20th of the Second month,
1768, and was interred in Friends`' burial-ground at Stansted aforesaid,
the 28th of the same; aged about twenty-eight years, and a minister about six years.

[.asterism]
'''
BENJAMIN TROTTER, of the city of Philadelphia, was born in that city about the year 1699,
and was one whom the Lord early visited and reached
to by the reproofs of his divine light and grace,
for those youthful vanities and corrupt conversation which by nature he was prone to,
and pursued, to the grief of his pious mother,
who was religiously concerned to restrain him.
But as he became obedient to the renewed visitations of the heavenly call,
denying himself of those things he was reproved for, he not only ceased from doing evil,
but learned to do well; and continuing faithful,
became an example of plainness and self-denial,
for which he suffered much scoffing and mocking of
those who had been his companions in folly;
yet he neither fainted nor was turned aside by the reproaches of the ungodly,
which thus fell to his lot for his plain testimony against their evil conduct.

In the twenty-sixth year of his age, he appeared in the work of the ministry,
and labored therein in much plainness and godly sincerity,
adorning the doctrine he preached by a humble circumspect life and conduct,
being exemplary in his diligence and industry to labor honestly for a livelihood,
though often in much bodily infirmity and weakness, desiring as he sometimes expressed,
that he might owe no man anything but love.
His inoffensive openness and affability,
drawing many of different denominations to converse with him,
he had some seasonable opportunities of admonishing
and rebuking the evil doer and evil speaker,
which he did in the plainness of an upright zeal for the promotion of piety and virtue,
tempered with true brotherly kindness and charity,
respecting not the person of the proud, nor of the rich because of his riches,
but with Christian freedom declaring the truth to his neighbor, and was thus,
in private as well as public, a preacher of righteousness.

He at several times visited most of the meetings
in the provinces of Pennsylvania and New Jersey,
and some in the adjacent provinces,
and for upwards of forty years was a diligent attender
of our religious meetings in the city of Philadelphia,
and zealously concerned for the maintenance of our
Christian discipline in meekness and true charity;
careful in the exercise of that part of pure religion,
visiting the widow and fatherless in their afflictions,
and often qualified to administer relief and consolation to their dejected minds.

In his public testimony, a little before his last sickness,
he expressed his apprehensions that his time would be short,
and fervently exhorted to watchfulness and care,
to keep our lamps trimmed and our lights burning,
and urged the necessity of being prepared to meet the bridegroom,
as not knowing at what hour he would come.

In his last sickness, which lasted upwards of six weeks,
he underwent great difficulty and pain, being afflicted with the asthma and dropsy,
which he bore with exemplary patience and resignation,
and was never heard to utter a murmur or complaint,
but frequently expressed his thankfulness that he had not more pain;
and was often engaged in prayer that he might be preserved in patience to the end,
which was graciously granted him, so that he was capable of speaking,
to the comfort and edification of those who visited him.

He departed this life in the Third month, 1768, and after a solemn meeting,
in which several living testimonies were borne,
was interred in Friends`' burial-ground in that city, the 24th of the same,
aged upwards of sixty-eight years.

[.asterism]
'''
REBECCA SMITH, late of Nailsworth, in the county of Gloucester,
was one who was a good example in purity of life and manners, sincerely loved the truth,
and diligently sought the promotion thereof.
Through the operation of divine love on her mind, in her young years,
she preferred the cause of truth,
and about the twenty-ninth year of her age received a call to the ministry, and,
being inwardly sensible that a dispensation of the gospel was committed to her,
she delayed not with vain consultations,
but readily submitted to that proving engagement, and,
cheerfully surrendering her will to divine requirings,
soon grew skillful in dividing the word; thereby evidently showing, to serious,
awakened minds, that in this, as in other religious services,
the Lord loves a cheerful giver.

She was a diligent, exact attender of meetings,
and there was something instructive in that weighty
retired manner in which she usually sat in them,
often long in silence,
being careful to feel divine life precede and put forth to service,
and when raised in ministry, not to exceed the opening of the gift.
Thus her testimony was preserved clear and edifying, truly acceptable to Friends,
both at home and abroad where she travelled, being also serviceable in the discipline.

Having known many deep inward afflictions and close refinings,
she obtained the tongue of the learned, and often had a word to speak in due season.
Thus serving her generation,
she fulfilled the ministry she received to testify to the sufficiency of divine grace,
and finished her course with joy the 28th of the Eleventh month, 1768;
aged fifty-four years.

[.asterism]
'''
THOMAS DANN, a member of Dorking monthly meeting, in the county of Surry,
was born at Nutfield, in the said county, of honest and religious parents.
In his young years he was much addicted to vanity,
yet by the tender visitations of kind Providence, he was preserved from gross evils.
As he grew to man`'s estate, through the same gracious visitations,
the beauty and comeliness of this world was stained in his view,
and he fitted for service, into which he was called about the thirtieth year of his age.
He was a preacher of righteousness, not only in word and doctrine,
but in life and conduct; a diligent attender of meetings for worship and discipline,
earnestly recommending friends to a humble waiting on the Lord,
for counsel and direction in the management of the affairs of the church;
and though not concerned to travel much abroad,
yet he visited some adjacent counties to good satisfaction.
A just reprover of the libertine, but very tender to the sincere-hearted,
ready to give advice and counsel to those who stood in need, much concerned for peace,
and often instrumental in composing differences among his friends and neighbors;
a sympathizer with the afflicted, liberal and compassionate to the poor,
a loving husband and tender father,
yet not indulging his children in anything he believed inconsistent with the truth;
a good master, and a sincere friend.

It pleased the Lord, some time before his departure,
to give him a sense that his day was near at an end, his work was almost done,
and that all was well with him.
He often expressed in his illness that he found nothing stand ii his way;
in the forepart of which his pain was very great,
but he was fervently engaged to beseech the Lord to grant him patience,
that he might endure it with becoming resignation, which was mercifully afforded him;
for which, and the many repeated favors received,
he had to praise and magnify God`'s holy name, and to declare with Jacob of old,
that the Lord had been with him all his life long.
In this comfortable assurance he quietly departed this life,
the 23rd of the Second month, and his corpse, accompanied by many Friends and neighbors,
was decently interred at Rygate, the 1st of the Third month, 1769; aged sixty-five,
and a minister thirty-five years.

[.asterism]
'''
JOHN BURTON, a member of Sedberg monthly meeting, in Yorkshire, was born at Dent,
within the compass of that meeting,
and was favored with the visitation of divine love in his young years,
whereby he came to see the emptiness of all mere outward profession and performances,
and that no worship would find acceptance with his
Creator but that performed in spirit and truth.
Under the influences thereof he was brought into communion with our Society,
and by taking heed to the inward anointing, and abiding faithful thereto,
agreeable to 1 John 2:27, he arrived to a good degree of Christian experience,
and to see the necessity of regeneration, the refining hand working powerfully in him,
in order to fit him for further service,
to which he was called in the early part of his time,
and became truly devoted to the great Master`'s use,
to be led and conducted according to his requirings.

Though he had but little human learning, he was often led forth in a living,
powerful testimony, in matter exceedingly copious and pertinent,
being enabled to divide the word aright,
and to speak feelingly to the states of the people.
He was endued with a large gift in the ministry,
and often dipped into great sufferings with the seed
of life that lay oppressed in the hearts of many.
But when he who was his life appeared, he was as a holy flame,
warming and comforting the hearts of the afflicted,
and as a sharp sword to the lukewarm and careless,
tender and affectionate to those who were young in the ministry,
greatly rejoicing when the word of life arose in them,
though declared but in a few expressions, treating them with much love and respect,
lest they should sink under discouragement.

In the course of his Christian progress he had to visit Ireland,
and several of the northern counties, and London several times:
he also visited the American colonies;
in all which he conducted much to the satisfaction of Friends.
Though of a free, cheerful disposition and behavior, yet he was properly guarded,
being a plain man,
bearing a faithful testimony against the pride and vain show of the present age.
He was a man that was truly engaged for the good order of the church,
and that the line of discipline might be kept to,
waiting in those meetings in a humble manner for divine direction,
whereby he was qualified in much love to speak with authority and judgment,
being clear-sighted in difficult matters.

In the latter part of his time he was much confined at home, through bodily infirmities;
when visited by friends, he received them in much love,
his mind still retaining strong and hearty desires that the church of Christ might flourish,
and appear in her ancient beauty, and Zion keep her garments unspotted of the world.

In the beginning of his illness, he, in a very moving, pathetic manner, bewailed,
to some friends who visited him,
the loss the church sustained by many pursuing the
riches and grandeur of this perishing world,
instead of durable riches and righteousness.

About two days before he died,
he expressed himself to some intimate friends who visited him,
that he had passed through many deep and humbling
baptisms in the course of his own experience,
and on the account of the backsliding of many under our name, and some of his own family.
But now they seemed to him to be all over, being filled with light,
divine consolation and peace on every hand, which was enough for all;
and that it would be the happy experience of all such who served the Lord in sincerity,
and had Zion`'s welfare at heart.
But that a fearful and terrible day would overtake the careless,
if there was not a turning to the Lord while the offers of mercy were extended.

He likewise said that when he believed it his duty
to leave his family and the near connections of life,
he had never omitted one journey on truth`'s account, in which he had then great peace.

Thus this servant of the Lord departed in faith and
full assurance of a resting-place with the righteous,
the 23rd of the Third month, 1769, in the eighty-seventh year of his age,
having been a minister about sixty years;
and was interred in Friends`' burial-ground in Dent,
a large and solemn meeting being held on the occasion.

[.asterism]
'''
WILLIAM RECKITT, of Wainfleet, in Lincolnshire, having, through a variety of exercises,
and many trying seasons, given evident marks of stability of mind,
and through a firm confidence in that hand which led him forth into service,
filled up his duty; for the encouragement of others,
that they also may follow the footsteps of those that are gone,
although under the most trying seasons,
the following account of him claims a place in these memoirs.

He was born in the year 1706, and educated among Friends; and,
about the thirty-sixth year of his age, came forth in the work of the ministry,
in much simplicity and innocency, to the satisfaction of Friends,
it being in the life of truth, the only authority of all true ministry.
He labored faithfully in several parts of England and Ireland; and about the year 1756,
a concern came on him to visit America; and, with his friends`' unity and concurrence,
he embarked for Philadelphia, but was, soon after they sailed,
taken by a privateer and carried into Morlaix.
Through the favor of a French merchant there, who voluntarily became his security,
he was sent to Carhaix, in Brittany,
where he resided five months before his liberty was obtained;
during which he was preserved in meekness and innocence.
By accounts from there,
his lamb-like nature gained much on some of the French inhabitants,
and led them to treat him with much respect,
and he had several opportunities with them to his satisfaction,
particularly with the chief magistrate of the town.
In a letter to a Friend he gives this account of it:

[.embedded-content-document.letter]
--

He asked me many questions concerning our principles, which I answered short,
but so full that he made no objections; and I was thankful in my mind it was so,
for it was somewhat difficult for the young man my interpreter,
though he is always ready to assist me when I have occasion.
When I got home to my solitary dwelling,
and considered how often the Lord had appeared on my behalf, and had been my advocate,
I was much bowed in thankfulness before him.
I much desire I may be remembered by you, (meaning Friends,) for good,
when it is well with you, for I am afraid I should not hold out to the end,
or that I should bring some dishonor to truth.
O how grievous a thing I have thought it would be if I should
now bring up an evil report of the good land,
and so thereby discourage poor souls that have set their faces thitherward!
I had rather, if it was consistent with the will of my heavenly Father,
be gathered home in a good time.
My fears have all been concerning myself, for surely I never saw more of my own weakness.
It has been indeed a searching time to me; and yet it springs in my heart to say,
if the Lord has any delight in me, he will bring me safely through all.
He knows the integrity of my heart.
I did not set out in a forward spirit, but in his counsel, and in it at this time I stand.
He knows best what will be most for his own honor.
And as to what will become of this earthen tabernacle,
it seems to be the least of my care, so that I may finish my course with joy.

--

After his return from France he returned home, but the concern remaining,
in about four weeks he came back to London, and again embarked,
and arrived safely at Philadelphia in the year 1757.
After visiting most of the provinces in North America,
to the comfort and edification of Friends, he embarked for Barbados,
but was again taken and carried into Martinico, and after about two weeks`' confinement,
through the favor of the commissary,
he embarked on board a cartel ship for the island called St. Kitt`'s,
where he had several meetings, and also at Nevis, where he had two meetings;
at one of which a priest stood up, and addressing the people,
told them the everlasting gospel had been preached among them that day;
and recommended it to the observation and practice of all present;
and our friend declared he never felt the power of truth rise so high as at those meetings.
After which, finding his mind clear, although invited to stay and have more meetings,
and was told many of the inhabitants were descendants from friends,
he returned to St. Kitt`'s, so called, and soon after embarked for Philadelphia,
and from there for London.
In about three years after, he again visited America, and several parts of this nation.

In private life he was an affectionate husband, a tender father, and kind friend,
adorning the gospel with a becoming conduct.
Thus persevering in a course of virtue, about a year before his decease,
he wrote again to the friend before mentioned in the following manner,
which shows the integrity of his heart continued:

[.embedded-content-document.letter]
--

The sap of life lies very deep in the root,
and that must be waited for in those sorrowful and pinching times I have met with.
Yet I have had a comfortable hope raised in me of late that all would be well in the end,
the prospect of which to me has seemed exceedingly pleasant;
and if safe I should much desire it might be hastened;
but that is not my proper business,
to look for or desire the reward before the day`'s work is finished.
I have served a good master,
but have ever looked on myself one of the weakest of his servants;
yet have endeavored to come up in faithful obedience to his will made manifest in me,
and in this now I have great peace,
and an assurance of an inheritance that will never fade away,
if I continue in the way of well-doing to-the end of the race.

--

After this he visited the city of London,
which he often hinted he thought might be the last time:
but his love and integrity to the cause of truth continued,
and it was evident the fervency of his mind was as strong as ever.

His illness was very short: he was taken with a fit of the ague at night,
and next morning about four departed this life, the 6th of the Fourth month, 1769,
and was interred in Friends`' burial-ground the 9th of the same;
aged about sixty-three years.

[.asterism]
'''
JOSHUA TOFT, an ancient friend of Leek, in Staffordshire,
was favored in the early part of his life with the knowledge of the blessed truth,
and by obedience thereto became when young in years an example of religion and virtue.

His concerns in business at that time requiring his being much from home,
and to be conversant with those unacquainted with the circumspect
conduct and manner of behavior of the people he had joined in communion,
he was exposed in the youthful part of his life to severe and ill treatment.
But his mind being clothed with the patience of the holy word,
he experienced by its blessed fruits of meekness and love,
the ignorance of foolish men not only silenced, but sometimes their wrath and enmity,
through his faithful testimony, turned into respect and friendship.
Though his beginning in the world was small, yet being blessed by Providence,
whose is the earth and the fullness thereof, as well as the dew of heaven,
he was satisfied with a moderate competency,
and in the full strength of life and flow of business,
which would have enabled him to accumulate much wealth, with noble fortitude,
believing it to be required of him, he declined trade,
more fully to devote himself to his great Lord and master`'s service in the gospel ministry,
into which he had been called about the thirty-second year of his age,
in which he diligently and faithfully labored many
years in various parts of this nation and Ireland,
to the comfort and edification of the church, and his own peace.

Nearly twenty years before his decease, he was disabled from traveling much from home,
being seized with a disorder in his head, which affected at times his understanding,
and deprived him, for more than fourteen years of the latter part of his life, of sight.
After the loss of which, his faculties became as strong as before,
and his understanding perfect which continued to the last.
With exemplary patience, cheerfulness and resignation, he bore great affliction of body,
as well as deprivation of sight,
signifying all that was laid upon him was in love and intended for his good,
and hoped he should receive it as such.

A day or two before his departure, he said he had been much consoled,
having received a most gracious promise, "`I have been with you, I am with you,
and will be with you.`"

He quietly departed this life the 15th of the Eighth month, 1769, aged upwards of eighty,
a minister forty-eight years, and was interred in Friends`' burial-ground at Leek,
on which occasion the same ever-glorious truth that had been with
him in the beginning and close of his pilgrimage through life,
was manifested to the renewed encouragement of many, to prove for themselves likewise,
that the gifts and callings of God are without repentance.
