== Chapter 17

[.chapter-synopsis]
* Richard Reynolds
* James Wilson
* Daniel Stanton
* Elizabeth Atkinson
* Thomas Mawditt

RICHARD REYNOLDS, late of Winterburn, in Gloucestershire, was born at Banbury,
in the county of Oxford, and in his very early years manifested a religious disposition,
and knew in some degree the purifying hand of divine goodness to fit him for service,
so that, about the twentieth year of his age, he appeared in the ministry,
to the satisfaction of Friends.

He resided for many years in the city of Bristol, where his business,
before he retreated from it to Winterburn, lay;
which he was induced to do from a desire of withdrawing
from the encumbering pursuit of temporal things,
often expressing the hurt sustained by an over solicitude for things of this life.

A considerable time before his decease he was taken with a sudden indisposition of body,
as he was traveling on the account of temporal concerns,
and his mind became alarmed with this instruction,
'`Set your house in order;`' to which he diligently attended,
in a spiritual sense especially.

In the course of his illness he appeared much resigned to divine disposal,
and uttered many instructive sayings to those who were with him,
very intelligibly and with clear understanding,
expressing that`' the Father`'s love is the best cordial.
This is a trying time.
We had need to lay up a good foundation against the time to come.
That the peaceful state of his mind was all owing to divine goodness; for to us,
O Lord I belongs shame and confusion of face.`'
He was under deep travail of spirit that he might
be thoroughly purified and made fit for the kingdom,
and was enabled to pray that the Lord would lift up the light of his countenance,
and through Christ forgive all his omissions,
which there is good reason to believe was granted.
With much sensibility he mentioned the saying of the leper to Christ,
"`Lord! if you will, you can make me clean;`" and the gracious answer, "`I will;
be clean.`"

That which lay with the greatest weight and dissatisfaction on his mind,
was his having been too closely attached to worldly things.
And a little before his departure, he said in an affecting manner,
'`Too much assiduity! too much care!
I might have been a better example.
So much care and pains alienate the mind: the Lord is merciful;
I hope he will forgive me that sin.
I would have you take warning by me.`'
This last saying he repeated with much concern,
and then laying in a composed manner for a few hours, quietly expired at Bath,
the 8th of the Twelfth month, 1769,
and was buried in Friends`' burial-ground near the Friars, in Bristol,
the 15th aged about sixty years, and a minister about forty years.

[.asterism]
'''

JAMES WILSON, of Kendal, was born in the parish of Kirby-Lonsdale, in Westmoreland,
in the year 1677.
His parents, Edmund and Jane Wilson, educated him in the way of the church of England.
When young in years, his heart was much bent to seek after real religion,
being uneasy with the dead formalities in which he was educated,
his soul thirsting after the enjoyment of the Lord`'s presence.
In this time of seeking after good,
he devoted much of his leisure time to reading the Holy Scriptures,
especially the New Testament; in the perusal whereof his mind was more informed,
tendered, and broken, than by all the instrumental labor he had partaken of.
Some time after, being convinced of the principles of truth, he joined our Society;
and in the thirtieth year of his age came forth in the work of the ministry,
and was soon drawn into, and eminently qualified for, much extensive labor in the church,
and among the people in Great Britain and Ireland.

He devoted much of the prime and strength of his life to the service of truth,
diligently laboring in the ability it gives, both home and abroad,
to the honor of the great name, and the edification of many;
frequently attending meetings on public occasions, and several appointed in fresh places,
wherein his labors were well received,
and he was made instrumental to the convincement of many.
He was very serviceable and successful in accommodating differences among his neighbors;
and having frequent access to persons of high rank in life,
he was thereby very useful not only to remove prejudices from their minds,
by opening the doctrines and principles most surely believed among us,
but in obtaining their friendly regard and assistance when occasion required.
Thus he spent a long and useful life,
through many close trials and afflictions which attended him both within and without.
He bore all with steadiness and resignation,
and his memory and understanding were preserved to the admiration of many who knew him.

Some lines he wrote about sixteen years before his decease,
seem to describe the state of his mind in succeeding years:

'`I am now waiting,
and beseeching God Almighty to grant me the continuance
of his blessed grace and holy spirit,
to aid and assist me for a full preparation for death, and calmly to resign myself to it;
and above all, to grant me his aid in that painful and trying season,
that I may forever praise his holy name, who is forever worthy with his dear Son,
who is my dear and blessed Savior.
Amen.`'

He departed this life at his house in Kendal, the 30th of the Twelfth month, 1769,
and was interred in Friends`' burial-ground the 1st of the First month, 1770;
aged ninety-two and a minister upwards of sixty years.

[.asterism]
'''

DANIEL STANTON, of the city of Philadelphia, was born there about the year 1708.
His father dying before his birth, and his mother a few years after,
he suffered great trial and hardships when very young;
but being early concerned to seek the knowledge of God,
he had a fervent desire to attend religious meetings,
though subjected to many difficulties and discouragements
before that privilege was allowed him.
Yet being earnest in his desires to obtain divine favor,
he was eminently supported under great conflicts and probations,
and continuing faithful to the degrees of light and grace communicated,
a dispensation of the gospel ministry was committed to him
some time before the term of his apprenticeship was expired;
and abiding under the sanctifying power of truth, he grew in his gift,
and became a zealous and faithful minister.

Though he was very exemplary in his industry and diligence,
in laboring faithfully at his trade to provide for his own support,
and after he married and had children, for their maintenance,
and was often concerned to advise others to the same necessary care;
yet he continued fervent in spirit for the promotion of truth and righteousness,
so that he was soon engaged to leave home, and the nearest connections of nature,
to publish the glad tidings of the gospel,
frequently visiting the meetings of Friends in the
province of Pennsylvania and the adjacent provinces,
and several times as far as the eastern parts of New England.

In the year 1748, in company with Samuel Nottingham,
he visited the few meetings in the Island of Barbados,
and by the way of Antigua to Tortola, where after staying some time,
they embarked for Europe.
Their voyage there was attended with some singular hazards and danger,
which occasioned their landing in Ireland, where,
after he had visited the meetings of Friends, he embarked for England,
and visited the meetings generally in Great Britain,
to the comfort and satisfaction of Friends; his meek,
circumspect conduct and conversation, and lively, edifying ministry,
rendering his visits very acceptable, and his memory precious.

After his return to his native country he visited Friends
in all the southern provinces as far as South Carolina,
and about two years before his death,
the families of Friends in some parts of West Jersey, the city of New York,
and Long Island.
He returned from this service with great peace and satisfaction,
expressing his apprehension that he was now clear of all places,
and that his stay here was nearly over,
having an evidence that he had been faithfully concerned
from his youth to fear and serve God.

When at home he was much employed in visiting the sick and afflicted,
to whom he administered his spiritual advice and experience,
and was often engaged in humble prayer for their support;
and in the distributing to the necessitous according to his circumstances,
he manifested his benevolent disposition.
His love to the rising generation was very great,
which he manifested by his affectionate notice of them,
and especially of those who were religiously inclined,
his house being open to receive such.
His concern was great, that those who had the glad tidings of the gospel to publish,
might be true examples to the flock,
and adorn the doctrine they had to deliver by a circumspect life and conduct.

On the 5th day of the Fifth month, 1770, he was violently seized with the bilious colic,
and continued in great pain for several days, but being somewhat easier,
he attended two meetings on First-day,
in which he was much favored in his public ministry, and expressed,
that he thought his time would not be long.
He was enabled to attend the monthly meeting at Philadelphia the 25th of the said month,
which was the last public meeting he was at,
being the next morning seized with a renewed attack of the same disorder,
which increased on him for several days;
yet through all he was mercifully supported in much resignation and patience,
rather inclining, if it was the Lord`'s will, to be released.

During the time of his sickness,
he often expressed his concern lest his friends should be too anxious for his recovery,
saying, if he should live longer,
and through any human frailty or infirmity occasion any reproach,
it would be the cause of sorrow to them.
The evening of the First-day before he died, several friends coming to see him,
he spoke a considerable time to them,
having before been desirous of such an opportunity of the company of his friends,
to sit down and wait on God, which was his great delight.
The evening before he died, he expressed to his friend Israel Pemberton,
who sat up with him, his great thankfulness, that his head was preserved from pain,
and his understanding clear;
and that though it had been a time of close trial and deep probation,
he could say he felt the evidence of divine support to attend him.

He died the 28th of the Sixth month, 1770,
in the sixty-second year of his age and forty-third of his ministry,
and the next day his body,
attended by a large number of people of several religious denominations,
after a meeting being held for that purpose was interred
in Friends`' burial-ground in that city.

[.asterism]
'''

ELIZABETH ATKINSON, of Milden-Hall, in Suffolk,
was the daughter of Edward and Elizabeth Peachy, of the same place,
Friends well esteemed, who gave this their daughter a religious education.
While very young, she was favored with a divine visitation,
and yielding obedience to the heavenly vision, she became qualified for her master`'s use,
and received a gift in the ministry about the twenty-second year of her age.
She was faithfully concerned to yield obedience to the manifestations of duty,
in which she experienced peace.

When about thirty, she joined in marriage with Samuel Atkinson,
a Friend of the same meeting, and some few years after,
it pleased the Lord to try her in a close manner,
by dissolving this very near and close connection.
Thus being left a widow with six young children and in low circumstances:
this dispensation of heaven was attended with baptisms and exercises on many accounts,
her situation being such that she found it necessary to
use unwearied diligence for the support of her family,
not willing to be burdensome, but having a few things, was therewith content.
It does not seem that her family,
whose necessity she ever appeared to have due regard to,
hindered her in her gospel-labors;
but she was obedient to the requirings and manifestations of duty,
faithfully given up to go on the Lord`'s errands.

At the awful approach of the undeniable messenger of death,
she possessed a quiet composure of soul, often wishing to be dissolved,
to be with Christ; yet humbly waiting the Lord`'s time for the accomplishment of his will.
Being full of days and full of peace,
she was greatly favored to very near the end of her time, sensible and lively,
and was frequently engaged to express that the Lord`'s
goodness to her had been great and wonderful;
earnestly recommending to those who visited her to serve him faithfully,
and in an especial manner to the youth,
to dedicate the bud and blossom of their days to him,
for that they could not serve a better master.

A short time before her death, finding her mind very low,
she was fearful she had offended.
Earnest were her cries unto the Lord, that she might not depart under a cloud,
which he graciously answered by the renewing of his love,
and lifting up of his glorious countenance,
so that she broke forth in the following words, '`Glory,
honor and high renown be given to him, who wears the heavenly crown.
The Lord is my reward, and at his right hand are rivers of pleasure,
and that forevermore.`'

She departed this life the 3rd of the Seventh month, 1770,
and was buried in Friends`' burial-ground at Milden-Hall, the 8th of the same;
aged eighty-eight, and a minister sixty-six years.

[.asterism]
'''

THOMAS MAWDITT, of Collumpton, in the county of Devon,
was educated in the way of the church of England,
and about the twentieth year of his age was convinced of the blessed truth.
By the accounts received of him,
he appeared in the ministry about the thirty-third year of his age,
and his services therein were acceptable.
He was a diligent attender of meetings, though of an infirm constitution of body;
of an exemplary conduct among men, and of an innocent deportment.

Having left behind him a narrative in manuscript of his convincement,
the following is a copy of it:

[.embedded-content-document.testimony]
--

Some passages of my life having of late been brought fresh into my remembrance,
I thought proper to commit them to writing, that others might see the great love of God,
in Christ, to my soul, and be encouraged to follow on to know and obey him.

While I was young and tender in years,
the Lord was pleased to put his fear into my heart,
which was to me the beginning of wisdom,
because it made me careful both of my words and actions.
So long as I kept upon my watch against sin,
the Lord gave me true peace and quietude of mind, but when I was unwatchful,
the tempter often prevailed with his temptations,
which brought the righteous judgments of God upon my soul,
and made me cry unto him for mercy and forgiveness.
The Lord was gracious to me, and forgave me time after time, as I repented of the evil,
so that I can from my own experience say,
that there is mercy with the Lord that he may be feared;
and thus he gave me strength to call upon him while he was near,
and to seek him while he was to be found.
He was near in Spirit, reproving me for my sins, although I then knew him not;
and in this state I often made covenant, that if the Lord would forgive me,
then I would live more watchfully than I had hitherto.
But as it was made in my own will, it was soon broken,
and I was still under`' the administration of condemnation;
the sense thereof often made me cry unto God,
that he would deliver me from the body of this death.
In this state, when I would do good, evil was present with me,
and I did the things I would not; and finding myself overcome time after time,
notwithstanding my endeavors to the contrary,
I was ready to conclude that there was no living without sin in the world,
although I found it a burden too heavy to bear.

About this time I began to think what people to join with,
for I was not satisfied in the way I was in,
and I besought the most high God that he would direct me what people to join with.
While I was under this concern of mind, on a First-day of the week,
as I was walking to the place of worship in company with two of the people called Quakers,
one of them asked me to go with them to their meeting, adding,
that there were to be two strangers there that day.
I accordingly went, and after we had sat some time in silence,
one of them stood up and spoke, and after that the other.
I do not remember much of what they said,
but it appeared to me that their preaching was like that of the apostles,
and that they were enabled by a measure of the same
spirit and a degree of the same power.
I also felt such a measure of that spirit and power which
helped them in their ministry as I never enjoyed before;
and it was to me a day of glad tidings of great joy, and my soul did magnify the Lord,
and my spirit rejoiced in God my Savior.

This gave me full satisfaction of mind what people to join with,
although at first it looked strange to me to see a people sit in silence as they did,
for I had been feeding upon words, until I was directed unto Christ,
the word nigh in the heart, and to know him to be my teacher.
Thus the Lord brought me off from a man-made ministry,
to the minister of the sanctuary and true tabernacle, which God had pitched and not man,
everlasting praise be given to his name.
Here the Lord brought me into a state of silence,
out of my formal prayers and will-worship, to wait upon him,
until he was pleased to help me to pray with the spirit and with understanding.
But when he was pleased to show me that I must use the singular number,
as thee and thou to one person, it was as death to me,
for I saw I should be despised and rejected.
Here I found in degree that cross which the apostle spoke of,
that crucified to the world, and the world to him;
and until I knew my own will in measure slain, I was not able to use it.
But when I did use it, after I believed it was required of me, I had great peace of mind;
and if at any time I did not use it for fear of offending man,
I was under condemnation and trouble of mind until I used it without respect of persons.
I know it was the Lord`'s doing, for I did it not in imitation but by revelation.
Neither could I any more pull off my hat and bow to any man.
Thus the Lord led me step by step-into obedience to him;
and as long as I lived in obedience to what he was pleased to manifest unto me,
I reaped that peace and joy in the Holy Ghost,
that all the favor and friendship of men is not to be compared with.

About this time a concern came upon my mind to bear
a public testimony in meetings to the truth,
which made me both to fear and tremble; whereupon I let in the reasoner,
and looked to my own weakness as a man,
and how unfit I was for so great a work as the work of the ministry;
when I should have looked unto the Lord,
who is able to strengthen the weak and confirm the feeble-minded,
and which I had in times past witnessed to my comfort.
Here it was I lost my peace and quiet which I had in a state of obedience,
for I went from the true witness within, even the spirit of truth, which did lead,
and would have led me into all truth, and I joined with the reasoner,
and so erred and went astray from the way of the Lord as a lost sheep.
Here the enemy of mankind got advantage upon me,
and I could not stand faithfully in my testimony for the truth as I formerly had,
but grew weaker and weaker, and was tossed with a tempest and not comforted.
Yet in this sorrowful state I sometimes had a little hope that the Lord would deliver me,
which was some stay to my mind, and I was made to cry, Lord! if you slay me,
yet will I trust in you.
I would often pray unto God, that he would restore me again,
and that if it pleased him to bring the like concern upon me any more,
I would be faithful and obedient to his requirings.
But this I could not attain to, which brought me very low in my mind,
and I was almost ready to despair,
for I found myself so hardened that I could not lament my state and condition as formerly,
so that I was afraid the day of my visitation was over.
When all hope seemed to be lost, the word of God was unto me,
As you have gradually fallen, so you shall gradually rise;
which had so good an effect as to bring with it a living hope,
that was an anchor to my soul, steadfast and sure,
and preserved my mind from being carried away with the floods of temptation,
which were many and great in those days.

It was through faith in Christ, the word nigh in the heart,
which I found to be quick and powerful,
that I came to be restored again in due time to a state of obedience;
and the Lord now favored me with many good meetings,
which made me often desire for the meeting-time, for in my silent waiting upon him,
I found my strength renewed.
After this it was shown me that I must alter the place of my sitting; and one day,
as the meeting-time drew on,
I prayed to God in my heart that he would favor me with a good meeting.
But the answer was, If you do not go and sit in that place,
how can you expect a good meeting?
Until now I was not come to a resolution; but now, when the meeting-time came,
I went and sat in the place showed me, not knowing further what might be required of me;
and, after some time of silence,
I found a concern of mind to speak to the people as follows:
There is a seed of God among you, but it lies oppressed, etc.

And now I can say, after many years experience, Hitherto the Lord has helped me,
and he is not a hard master, as some slothful servants have said,
for he does not gather where he has not sown, neither reap where he has not sown.
All who are born of that seed which is incorruptible,
and of the word of God which lives and abides forever,
can say there is no condemnation to them that are in Christ Jesus,
who walk not after the flesh, but after the spirit;
for the law of the spirit of life has made them free from the law of sin and death.
Here, in brief, have I shown what the Lord has done for my soul,
for it is he that has plucked my feet out of the miry clay,
and set them upon a rock that was higher than I; wherefore to him shall the honor, glory,
and praise be given, who is over all worthy forever and evermore.

[.signed-section-signature]
Thomas Mawditt

[.signed-section-context-close]
1748

--

In his last illness his understanding and senses were preserved,
and he expressed his being refreshed in his spirit;
and as he found his end approaching he frequently desired,
if agreeable to the will of the Almighty, that he might be released,
under a well-grounded apprehension that his day`'s work was done.
He departed this life the 13th of the Seventh month, 1770; aged eighty-one,
and had been a minister about forty-eight years.

[.the-end]
End of Second Volume
