== Preface.

The memorials of the persons mentioned in this work,
were extracted from testimonies concerning them, or other authentic accounts,
and are collected, as those in the seven preceding parts were,
with a view to the promotion of piety and virtue;
that by having the footsteps of those before them, who have finished their course well,
others might be incited and encouraged to follow them as they followed Christ.
It is in my heart more particularly to address the rising youth,
with desires that they may be raised up and qualified to
fill the places of those who are gone from works to rewards;
that the testimony given us to bear may be faithfully maintained,
the borders of Zion enlarged, and the glorious unchangeable truth,
in the course of divine wisdom, be more established among men.

And first, to those of both sexes, who are yet in their minority,
and who often feel the touches of divine love tendering their hearts,
and drawing them to good and the love of good men, though, perhaps,
like Samuel when a child, they may at first be ignorant of the cause thereof.
Let these therefore be entreated not to get from under these precious visitations,
but as they feel them to arise, be careful not to neglect, much less oppose them;
and in due time such will experience them to be a degree of that divine light "`which
enlightens every man that comes into the world,`" John 1:9. By bringing all their thoughts,
words and actions thereto, they will clearly discern the ground and tendency of them.

It was through the influence of this divine principle that many were led in very early
youth to wait for and seek after that consolation which they had felt,
without knowing from where it came, until he who first visited,
enlarged their understandings, and led them to a further degree of knowledge,
and convinced them it was of a divine nature,
and that their growth in true virtue lay in a steady attention thereto.

To those who are of riper years,
and who have been mercifully favoured with a further enlargement of this divine life,
and are in measure turned to it;
the safety of all such depends in waiting for its instructions,
and under its heavenly influence faithfully following them.
Let these be encouraged in the language of the prophet: "`Then shall we know,
if we follow on to know the Lord; his going forth is prepared as the morning;
and he shall come unto us as the rain, as the latter and former rain unto the earth.`"
Hosea 6:3.

These will, in true wisdom, see the service of their day,
feel divine support through this state of probation, and preservation to the end;
partaking as they go along of that peace which Christ promised his true followers,
"`Peace I leave with you, my peace I give unto you, not as the world gives,
do I give unto you.`" John 14:27.
It was this which supported the righteous in all ages,
and is cause of encouragement to look forwards.
The same hand which supported our predecessors,
is still near to help us in every needful time.
Thus by filling up every duty, we may experience in our conclusion,
the truth of the prophet`'s declaration, that "`The work of righteousness shall be peace,
and the effect of righteousness, quietness and assurance forever.`" Isaiah 32:17.

[.signed-section-signature]
T+++.+++ W.

[.signed-section-context-close]
London, the 8th of the First month, 1774.
