[short="Preface"]
== Preface. +++[+++By another Hand.]

// NOTE: NOT MODERNIZED
Wonderful hath been the love of God to the children of men,
and various have been the methods whereby he hath given demonstrations of it.
All ages and generations abound with the testimonies of his bounty to them;
for his goodness hath been always so plentifully extended,
and also in such an indulgent manner;
as if his happiness was not complete unless mankind partook of it.
So that he had great reason indeed to ask,
What could have been done more to his vineyard (the house of Israel),
that he had not done in it?
For he gave them his good Spirit to instruct them, he sent his servants, the prophets,
to reprove them, and which was the most stupendous kindness of all,
he also sent his only begotten Son to reclaim them, and to be a propitiation for them.
Yet such was the obstinacy of that impenitent generation,
that few would thereby see or do the things that belonged to their
peace so that at last they were hid from their eyes;
a doom dismal and just!
May their calamities be our caution, that by their harms we may learn to beware.

We have also, in this our day, been honoured with a visitation from heaven,
a high and holy calling indeed; a call to be holy in order to be happy.
But few have obeyed, though Christ himself hath called by his Spirit and by his servants,
by his judgments and by his mercies,
that men might be reduced to the paths of the righteous,
which are paths of pleasantness and ways of peace.
But alas! instead of being melted to contrition by
these endearing testimonies of his goodness,
such hath been the ingratitude of many,
they have done despite to the holy Spirit of Grace
that was given for their eternal profit,
and have also very evilly entreated his servants and messengers,
whom he sent to proclaim that accepted time, the day of salvation.
Yet these good men were not, by their hardships, weary of their well-doing,
but persevered to the end in doing good to them, though they returned hatred for love,
persecution for kindness, as thou wilt find by some instances in these collections,
which the industrious author presents thee with;
that the drowsy world might be awakened to holiness by the voice of the dead,
since that of the living is so little regarded.

The matter thou wilt soon see is very excellent,
since it shows thee that to live holily is the way to die happily.
In short, it is a continued persuasion to virtue,
and a compendious directory in the way to it, by the great means of example,
which at once gives both light and strength in that indispensable duty of living well.
It is free of what might excite thy displeasure,
not intermeddling with the controversies of the times;
so that charity persuades me that scarcely any can read it and not be bettered by it.
This gives me the boldness to recommend these following
sheets to the serious perusal of all;
high and low, rich and poor, friends and enemies;
that all may be humbled to the improvement of their time,
that treasure of eternal consequence, and be wise, and consider their latter end; lest,
when it is too late, they may desire to die the death of these righteous persons;
and that their latter end may be like theirs,
who breathed out their pious souls in faith,
and full assurance of an immortal crown of glory.

For the voice was true, +++[+++which]
the holy man declared he heard, and that bade him write,
"`Blessed are the dead which die in the Lord, that they may rest from their labours,
and their works do follow them,`" to their comfort and everlasting consolation;
and stay behind them too, for the example of the living, who desire to live to God,
and follow them as they followed Christ, in humility, self-denial, brotherly-kindness;
though thereby they are a proverb of reproach, and their life accounted madness,
and their latter end without honour; yet they will be numbered among the children of God,
and their lot will be among the saints.

I will detain thee no longer from what is better,
only reconmmend thee to the holy Spirit of Truth,
that is able and willing to guide thee into the same
blessed Truth it led these happy souls into,
and then thy latter end will be like to theirs, comfortable and glorious.
This is earnestly desired for thee by the author of these treatises;
for I know his sole design is thy profit and advantage.
He desires none for himself, but the comfort of well-doing;
being actuated by a better principle than to make gain of Godliness,
too much the practice of men of great pretences.
