== Chapter 3

[.chapter-synopsis]
* Benjamin Middleton
* Henry Tuke
* Joseph Gurney Bevan
* John Kendall
* Mary Pryor
* Jane Pearson
* Elizabeth Ashby

BENJAMIN MIDDLETON, of Wellingborough, was well esteemed as an elder in our Society;
and much beloved on account of his bright and amiable example,
and his steady adherence to the truth of the Gospel as professed among us.

In the earlier part of life it was needful for him to enter into trade;
but his desires were so bounded by the precepts of the Gospel that he did not attempt,
although it was in his power,
to extend his business beyond the provision of what would be sufficient
for the comfortable accommodation of his family and a life principally
devoted to the service of his Divine Master.
His humble endeavors were so blessed, in regard to his outward undertakings,
as instructively to bring into view that encouraging declaration,
"`The steps of a good man are ordered by the Lord,
and he delights in his way;`" nor shall they that seek him lack any good thing.

Being thus enabled, in a great degree, to abstract his mind from worldly pursuits,
he was more at liberty to become useful to others,
both in our own Society and among his neighbors.
It was often his pleasing employment to plead the cause of the poor and needy; and,
in the place of his residence,
he was frequently solicited to assist in settling differences; and through his counsels,
delivered in the spirit of genuine Christianity,
he had sometimes the satisfaction of seeing them brought to a favorable conclusion.

He was a man of unassuming, courteous manners; diffident of his own abilities,
and showing a great preference to others.
This gentleness, being the fruit of a pious heart,
had a sweet and benign influence on all around him.

During the last ten years of his life, he suffered much from a painful malady.
In the commencement of the disorder he travelled a little,
being unwilling to give up the attendance of the meetings
for worship and discipline of which he was a member.
He had long felt a lively zeal for the welfare of our Society,
and the unity of the brethren:
and his social disposition rendered it a source of real enjoyment to him,
to meet with his friends on these occasions.

A little more than five years before his death, he was deprived of his beloved wife.
His feelings were naturally acute, so that this affliction deeply proved his faith;
but his trust remained fixed on the Captain of his salvation,
by whose power he was strengthened to meet all with becoming fortitude and resignation.

In his Christian warfare he was often deeply tried,
by the withdrawing of those consolations which, at other times,
flowed from Him who was the light of his countenance, and his God.
He ceased not, however, to wait for the renewings of heavenly love;
and was thus permitted to experience preservation,
and to advance in the way of holiness.

His bodily sufferings were so much greater, during the latter part of his life,
that he was unable to ride at all, and could walk very little;
but he attended the meeting for worship to which he belonged,
until within two weeks of his death.
He did not murmur or complain; but, by quietude and patience,
evinced to all around him his humble dependence upon the Lord; so that,
though his mind was, at times, depressed, he was often very cheerful and communicative,
and much pleased when his friends came to visit him.

A short time before his death, he submitted to a surgical operation,
believing that it would be an allowable means of seeking
relief from a disorder that became more and more painful,
and which, in all probability, must otherwise shortly have terminated his life.
He bore his great sufferings with Christian fortitude;
but the reduction of bodily strength which ensued,
was more than nature was able to sustain at the age of sixty-eight;
and after his bed of languishing had been anxiously
watched by his affectionate daughter for nine days,
his purified spirit quitted the afflicted tenement, on the 12th of the Seventh month,
1814.

[.asterism]
'''

HENRY TUKE, son of William and Elizabeth Tuke, was born at York in the year 1755,
and died in that city, the 11th of the Eighth month, 1814.

He was, when a boy, of a lively, active disposition,
and though of an affectionate temper, quick of resentment;
but when about thirteen years of age,
the forbearing principle of religion often gained the ascendency in his heart,
and those opposing feelings were controlled,
and yielded to the gentle but powerful influence of the spirit of Christ.
About his seventh year, he was deprived of his mother;
but this loss was remarkably supplied by the affectionate
and maternal care of his father`'s second wife.
He was indeed blessed with the guardianship of discreet and religious parents,
who were deeply concerned for his welfare in every point of view.

He possessed an excellent understanding, and when placed at school,
made rapid progress in learning, and became a great favorite with his master.
He contracted a taste for the study of medicine,
and employed some of his leisure hours in that science;
but his father being desirous that he should assist him in his own concerns,
he did not hesitate to give up this inclination,
and diligently applied himself to the business.
At the same time, this industrious youth found opportunity,
by early rising and extraordinary exertion, to indulge, in a moderate degree,
his turn for literature;
and to retain and extend the classical learning he had acquired at school.
Some of those with whom the nature of his business led him frequently to associate,
were of a stamp far from being likely to promote either his moral or intellectual improvement;
but having set the fear of the Lord before him,
he was preserved from the contagion of vicious example.
The diligent pursuit of useful knowledge, with the care of religious parents,
and the society of virtuous and pious friends, doubtless, under the divine blessing,
contributed much to his preservation,
and also to form that religious character which was conspicuous in him in future life.

The love, as well as the fear of God, had early impressed his heart;
and his mind turned to Him, in gratitude for his manifold mercies.
In obedience to what he believed to be the divine will,
he first appeared as a minister of the gospel in his twenty-fifth year.
Although diligently engaged in business,
and in the cares and provision connected with a family,
having entered into the married state at the age of twenty-six,
he continued greatly solicitous to secure the one thing needful,
the pearl of great price.
Hence, under all his outward concerns,
and with the daily temptations of flesh and spirit,
maintaining a care to move under holy influence,
and that his life might correspond with the sacred
office to which he believed himself called,
he experienced an increase in true religion, and in the exercise of his ministry,
which was sound and edifying.

The humble, devoted feelings which clothed his mind,
when reflecting upon his own experience in this station,
are agreeably manifested in the following extract from a letter,
written in the latter part of his life.

[.embedded-content-document.letter]
--

I can say that I sympathize with you in your various exercises,
from within and without; but thus it behooves some to suffer,
that they may be the better qualified to speak a word in due season,
to the weary traveller;
and patiently undergoing the various exercises allotted in Infinite Wisdom,
may experience them ultimately to terminate in the increase of
joy and peace;--in believing that faithful is He that has promised,
'`I will never leave you nor forsake you;`' and, '`who also will do it.`'
One thing I find,
that the longer I live the more I am reduced to that state which breathes the language,
'`Lord, I am a child;`' sometimes with an addition like that of, '`I cannot speak;`' though,
at others the more resigned language will prevail: '`Take me,
and lead me where you would have me to go.`'
And here I wish to center, and leave all to Him who does all things right; and who,
my small experience has taught me, is worthy to be served and obeyed in all things.

--

In the discipline of the Church, the subject of this memoir was active, skillful,
and extensively useful.
He felt the great importance of preserving, unimpaired,
this hedge and guard to our religious principles and practice;
and was desirous that his zeal for its maintenance
might always correspond with its design,
the encouragement of the right-minded,
and the discountenancing and recovery of backsliders.
In these services,
there was evidently a watchful care not to press
his own views beyond that deference and regard,
which are due to the sentiments of others.

Though not exempt from trials and conflicts, he bore them with meekness and submission;
and evinced the dignity of his Christian profession,
by that constancy and cheerfulness which are recommended by our Lord to his disciples,
when he enjoins them "`not to appear unto men to fast.`"
As he knew that he served a good Master, he served him with a willing mind,
and was engaged frequently to number his blessings,
and to ascribe them all to the bounty of that gracious Being,
"`who opens his hand and satisfies the desire of every living thing.`"

He had made himself well acquainted with the writings of our early predecessors,
and was fully satisfied that they entertained sound views of Christian doctrine; but,
beyond all other writings, he studied and reverenced the Holy Scriptures.
Hence, he was well qualified to advocate our religious principles;
and the services which he rendered to our Society, as an author,
were well accepted and valued by his friends.

Having endeavored to walk faithfully before the Lord,
and been concerned that his natural disposition might be
regulated and restrained by the power of divine grace,
his heart became more and more expanded in love to all mankind;
and while his attachment to his own religious principles increased with lengthened years,
his love and charity for those who differed from him increased also.
The prosperity of true piety and righteousness cheered his spirit;
and he was ready to unite with his fellow-citizens
in any measure for relieving the sorrows,
or advancing the temporal and eternal happiness of others,
when he could do it without a compromise of his own views of Christian truth:
and no object of this description was nearer to his heart,
than the free and universal dissemination of the Holy Scriptures.
He was naturally a man of a sanguine temperament:
religion did not destroy this character; but regulated and sanctified it.
He was zealous for good, and earnestly opposed to evil;
but when called upon to act towards those who pursued a wrong course of conduct,
he was an example of moderation.
And, as he possessed unfeigned and active love,
so he was greatly beloved by a numerous circle of relations and friends.

In the midst of his benevolent views and pursuits, He,
whose ways are all in perfect wisdom,
saw it good to remove his servant from this scene of trial,
before he had attained his sixtieth year.
He had through life, until the last year of it,
enjoyed a comfortable and even vigorous state of health.
About a year before his decease, he began to be affected with bodily infirmities;
they gradually increased,
and at length confined him to his house for nearly eleven weeks previous to his dissolution.
Having been concerned to serve his Lord and Master faithfully,
and knowing in whom he had believed,
he contemplated the near approach of eternity with seriousness, but not with dismay;
and thankfully spoke of the goodness of the Almighty to him.
To those about him, who tenderly ministered to his necessities,
he often expressed his grateful acknowledgments; and manifested his concern for them,
lest they should not be sufficiently attentive to themselves.
Through the whole of his illness, which was, at times, very painful,
he exhibited great and exemplary patience and resignation to the divine will.

A few weeks before his decease, he was visited by one of his friends,
who loved and esteemed him much, and who was struck on observing his general debility,
and the great alteration in his appearance.
But his countenance indicated a sweetness and serenity of mind,
accompanied with a holy solemnity, which cannot be easily described.
He manifested much kindness and affection, and remarked,
though not in the language of complaint, that it was trying not to be able to write,
or talk much to his friends.
He added, that his omissions and commissions had been many;--that he found, more and more,
it would not do to trust to any merits of his own,
but to look to Him who had washed away his sins by his blood.

A short time before his death,
he wished his eldest daughter to read to him the twenty-third Psalm;
and when she had finished, repeated, with great feeling, the last verse, in this manner:
"`Surely goodness and mercy shall follow me all the days of my life;
and I hope I may add, I shall dwell in the house of the Lord forever: but,`" he added,
"`all is mercy, unmerited mercy.`"

Through life, and even to its latest period,
he cherished and evinced great esteem and reverence towards his father,
who loved and valued him in a high degree.
A few hours before his decease, he said to him, with Christian fortitude:
"`My dear father, how I have loved and revered you! and now we are likely to part.
But I am perfectly resigned to the will of my heavenly Father.
If I die, I die as I have lived, in the faith and hope of a Christian.`"
Thus closed his useful life, in peace with God and man.

[.asterism]
'''

JOSEPH GURNEY BEVAN was born in the city of London, in the year 1753.
He was a youth of a lively, intelligent mind,
and endowed with a quick perception and superior understanding,
so that he readily acquired much useful learning and information.
His situation in life was that of outward ease:
his company was attractive to his associates, and he enjoyed the pleasures of society.
Hence he was peculiarly exposed to some of the dangers of early life,
and to the growth of those dispositions which are inimical to the cross of Christ.

But having felt the powerful visitations of the love of God,
arresting him in the pursuit of self-gratification,
and inviting him to walk in the narrow way, he listened to the heavenly call;
and although many a low and solitary hour evinced his consciousness
of the slippery path in which he trod,
he was enabled to turn his back upon the temptations which surrounded him;
and notwithstanding that he had often, through life,
to contend with the enemies of his own heart,
he was favored to keep his eye steadily fixed upon
the unconquerable Captain of our salvation.

On his marriage, in the year 1776, his father introduced him into his own business,
that of a chemist and druggist.
In his dealings in trade, he maintained an unblemished character for integrity of conduct.
The fear of violating, in his interaction with the world,
any of the precepts of the Gospel, or of acting contrary to its spirit,
either for the sake of gain, or to procure outward enjoyment,
early subjected him to much thoughtfulness.
He exceeded most men in earnestly endeavoring to
carry into the daily habits of life the sentiment,
that he ought to avoid in any way contributing to that in another,
which he was not satisfied to perform himself.
He considered that a Christian ought to act upon principle,
and not to be deterred from doing right, by any apprehension of consequences;
and he was concerned faithfully to observe these rules.
Being a man of a tender conscience,
and entertaining elevated ideas of the purity which becomes a real Christian,
and of that truth and sincerity with which he should live among men,
his own life was often that of great inward conflict and self-examination.

In the year 1796, he removed to Stoke Newington,
having retired from business about two years.
With a firmness and decision of character, which become the disciple of Christ,
he devoted the strength of his days, the vigor of his mental powers,
both natural and acquired, to the service of his great Lord and Master,
with a steady reference to that power by which his efforts could be blessed.
His time was much occupied in promoting the best interests of our religious Society;
and his pen was often judiciously employed in support of its principles.

For many years he filled the station of an elder, with acceptance to his friends;
endeavoring faithfully to discharge his duty in this character.
Many can acknowledge that he was, to them, a counsellor, and.a sympathizing friend,
when they apprehended themselves called to appear first in the ministry,
at the same time carefully turning them to the Lord alone for strength and direction.
His acquaintance with the Scriptures, his meditation upon their contents,
and the perusal, in a pious disposition, of annotations upon the sacred volume,
furnished him with a rich store of information; and his views on passages of Holy Writ,
were often striking and just.

This dear friend manifested a lively and peculiar
interest in the religious welfare of young persons:
his remarks in conversation were often replete with counsel to such,
conveying much instruction in a few words;
and a cheerful manner and natural vivacity at times so prevailed,
when he unbent in their company, that there was not any appearance of gloom,
calculated to induce a distaste for religion.
Those who knew him best, loved him most: to these he was endeared,
not only by the high sense which they entertained of his uprightness and worth,
but by his kind and affectionate exercise of a genuine Christian friendship.

Within the last few years of his life, his health declined:
his sight became greatly impaired, so that he was much dependent upon others,
for care and help; and the illness of his beloved wife, at times,
greatly affected his spirits.
As, however, he advanced towards the confines of the grave,
his soul increasingly partook of that Christian love,
and those other heavenly dispositions, which he had been long pressing after;
although his low estimate of his own attainments often led him
to speak and to write of himself with very great fear.

He had appeared among his brethren as an intrepid
advocate for the pure truths of the Christian religion;
and earnest were his desires, that that redemption, which comes by the Lord Jesus,
might be experimentally felt and borne witness to among us;
-- that his name and power might be magnified.
Yet such was his humility,
so exalted were his views of that holiness without which no man shall see the Lord,
that he was often ready to fear,
whether those promises of rich consolation in Christ Jesus belonged to him.

In the course of the year 1814, his bodily powers were still more weakened.
On the 9th of the Seventh month, he remarked,
that it was very awful to think of leaving probation for a fixed state, and added:
"`I do not know how it is: I am sure I have nothing to trust to of my own,
yet I do not feel dismay.`"
And in the course of the day he mentioned with much humility,
that the idea of Christ was precious to him.
A few days afterwards he observed,
that now that he was taught to believe that his continuance
in this tabernacle would not be long,
it was his greatest comfort to have a hope of admission
into "`a house not made with hands.`"

In a letter dictated to a much-loved relative, on the 1st of the Ninth month,
after alluding to his health, he adds:
"`I hope what I have said will not be set down as the language of repining;
for I believe I may say that, in a retrospect of my complaints, I have scarcely, if ever,
dared to desire that things had been ordered for me, otherwise than they have been.
I am ready to be surprised,
that so unworthy a creature has hitherto been preserved in the
degree of composure which I have been permitted to experience;
and well will it be, if self-love, or some other hidden cause,
does not make me think more favorably of the state of my own mind than I ought.`"

On the 11th of the same month, being First-day, he spent the morning pleasantly.
In the evening he desired to have a little stillness,
in which his mind was comforted and refreshed.
He sat with the family during the usual reading of the Scriptures.
The following day he appeared as well as usual.
On retiring to the sofa for his customary repose in the afternoon,
he entered into conversation on the state of things in our Society,
which he considered as calling for increased diligence,
especially among its more conspicuous members; after which he fell asleep.
In a few minutes he was heard to cough, and, without any indication of pain,
soon passed quietly away.

[.asterism]
'''

JOHN KENDALL was a Friend who, during a long and honorable life,
manifested a zeal for the cause of truth and righteousness,
which was well tempered with Christian charity and love.

He was born at Colchester, in the year 1726, of parents religiously disposed,
and early in life became an upright supporter of the doctrines of the gospel,
and of our Christian discipline; and about the twenty-first year of his age,
he first appeared as a minister.

In the year 1750 he accompanied Daniel Stanton, a friend from North America,
on a religious visit to Friends in the northern parts of England, and in Scotland;
and was frequently engaged, during nearly forty years,
in similar visits in various parts of this kingdom.
He was five times in Holland on religious service;
and attended the yearly meeting in London, with little intermission,
for the space of sixty years.

In the year 1764, he married Ann Havens, of Colchester, who died in 1805,
and of whom he left the following short testimony: "`She was a woman of great humility,
never aiming at high things, nor to be highly thought of; one who,
from her youth upwards, was preserved walking in the fear of the Lord.
The benevolence of her mind appeared in many instances,
especially in a charity for the benefit of poor widows, in the town of Colchester;
which she was the means of instituting,
and contributed largely towards building a house for their accommodation.
Her lively hope in Christ, and increasing love of God and man,
filled her mind with comfort and peace.`"

John Kendall was concerned through life as well by example as precept,
to encourage all around him to the exercise both of civil and religious duties.
If the character of any individual happened to be brought under review, he would,
if he could not excuse their failings, avoid the conversation;
thus evincing "`that charity which thinks no evil.`"
His latter years were much occupied in preparing works for the press,
principally consisting of Extracts;
the design of these publications being to promote
the moral and spiritual welfare of his friends.
Such was his concern for the good of all,
that it led him frequently to call at the public houses in his native town,
to admonish those whom he found there, against the baneful evils of intemperance.
Twice he attended at the theatre, and, at different times, other public entertainments,
to warn those collected,
against the evil consequences of such an occupation of their time.
His fellow-townsmen entertained so much respect for him,
that these proofs of his sincere desire for their
eternal good were very generally well received.

In the Sixth month, 1812, when at the advanced age of eighty-six, he met with a fall,
by which he fractured his arm,
and was in consequence confined to his chamber several weeks.
On a friend calling upon him during this confinement, he remarked,
"`It is trying to lie in so very weak a state of body;
but I hope it will all tend to my further preparation,
and fitness to meet my dear Savior.`"
He so far recovered his strength as to be able to walk to meeting,
which he attended several times in the course of the ensuing autumn.
He one evening remarked to a friend who visited him, "`My greatest comfort is,
to lie still in supplication to the Almighty.`"
And at another time said, "`Oh! if but one glance of my Savior`'s presence,
it makes amends for all the pain I feel.`"

About a year after his first accident, he fell down in his parlor,
and fractured his thigh; after which he went no more out, but was confined up stairs.

On taking a retrospect of his lengthened life, he once remarked,
a few months before his death "`It is frequently the desire of my mind,
that no complaining may be heard in my streets;
but rather the voice of thanksgiving and praise,
to Him who has been my Preserver and Helper all the days of my life.
I have not aimed at great things;
but have endeavored to promote the cause of truth and righteousness up to this day.`"
And at another time he said: "`Our lives are in the hand of a kind Providence,
to give or take away; and I desire we may be helped to be thankful for his dispensations.
I wonder my days are thus prolonged; but amidst afflictions,
I have cause to be thankful for many mercies.
We have an unwearied enemy, who seeks to draw us aside; and if he cannot by great things,
he will by little ones.
But while I am speaking, I feel great thankfulness in my mind,
that we are not left without One to help us; this is.
an unspeakable mercy.
I have had a great share of the Lord`'s goodness, both by sea and land,
and now my life is spared in a wonderful manner.
I can recommend nothing better to us than the love of God.
Oh, this brings great sweetness with it!`"

The following portions of Scripture were often repeated by him during his illness:
"`The Lord is my shepherd, I shall not want.
He makes me to lie down in green pastures: He leads me beside the still waters.`"
"`All the days of my appointed time will I wait, till my change come.`"
"`There is a river, the streams whereof make glad the city of God:`" saying,
he was frequently favored to partake of the streams of this river,
which he believed to be divine love,
flowing from the fountain and source of all goodness and perfection.
On being asked, a few days before his departure, how he felt in his mind, he replied:
"`All sweetness:`" and soon after added, "`O! death, where is your sting?
O grave, where is your victory?`"

On the 27th of the First month, 1815, about half an hour before his close,
he said to a friend; "`I am gradually going;
resignation slopes;`" but could not articulate more than "`farewell
--farewell;`" and in great quietness quitted this life,
in the eighty-ninth year of his age; evincing, by the calmness of his evening,
that his day had been blessed.

[.asterism]
'''

MARY PRYOR, wife of John Pryor, of Hertford, was born in the city of London,
in the year 1738.
She lost her mother when very young;
and in earlier life was exposed to some of those temptations by which the youthful
mind is drawn aside from the simplicity of the Truth as professed by Friends.
On an occasion of this sort, when about to be introduced into unsuitable company,
she remarked to her companion, as they were walking along: "`I can go no further.`"
This sacrifice to duty appears to have brought with it a corresponding reward; for,
on relating the circumstance, in after life, to one of her daughters, she acknowledged,
that she had hardly ever felt more true joy than she at that time did,
on her solitary walk home.

When about the age of twenty-five,
she gave up to an apprehension that it was required
of her to bear public testimony to the Lord`'s goodness.
In looking forward to this awful service,
for several months previous to the time when she first ventured
to speak publicly in the name of the Lord,
she was in the habit of retiring frequently in the course of the day, to wait upon Him.
Her ministry was acceptable and edifying to her friends, and having early experienced,
that the way to the kingdom of heaven is by bearing the cross of Christ,
she was strengthened, in the obedience of faith,
to yield to many services of a humiliating nature.
In the performance of these acts of dedication,
her genuine love and simplicity gained her the esteem of those with whom she labored.

She was a friend whose affectionate and cheerful disposition,
joined to a pious and exemplary life, rendered her company pleasant.
She felt tenderly for her friends and others,
under the varied trials incident to this state of existence manifesting,
in Christian love, her sympathy with the afflicted, and her anxiety for their comfort.
She was diligent in seeking out objects of benevolence;
in endeavoring to procure the means of their relief, and to administer to their needs.

Towards the decline of life, she was liberated,
with the full unity and sympathy of her friends, to proceed to America,
on a visit in gospel love.
She embarked in the Twelfth month, 1797, in company with about twenty fellow-passengers,
chiefly mechanics and artists, on board a vessel bound from London to New York.
They had not been long at sea,
before it was found that the ship was totally unfit for the voyage; so much so that,
after every gale of wind, the leaks increased considerably;
and all attempts to discover particular ones were ineffectual.
The danger continued and increased for several weeks.
The sailors despaired of saving the vessel,
and the passengers were obliged to be constantly assisting them at the pumps.
All the men who were able to exert themselves took their turns;
and they succeeded each other in small companies, every four hours, night and day.
Throughout this state of painful suspense, which often amounted to despair,
Mary Pryor was preserved in great calmness,
and her faith in Him who is Omnipotent did not fail:
she was supported by a secret persuasion that their lives would be saved.

In the evening of the 2nd of the Third month, two pumps were continually at work,
and on the following morning the water was gaining so fast on the vessel,
and the strength of the men was so much exhausted,
that they had scarcely any hopes of being rescued from a watery grave.
The crew were employed in throwing out some articles of the cargo,
when a schooner bound from Nova Scotia to Philadelphia came in sight.
On being made acquainted with the distress of the crew and passengers, Captain Macey,
the commander of this vessel, and his company,
though they supposed they were six hundred miles from the shores of America,
and had only a vessel of sixty tons burden,
generously consented to submit to an allowance of
one pint of water each in twenty-four hours,
and to take all the sufferers on board.
Their removal was effected in the course of that evening,
and it was thought that the vessel sunk about two hours afterwards.
The captain gave up his berth to Mary Pryor,
and behaved to her as if he had been her own son.

In her passing to the schooner, the water in the boat rose as high as her knees,
and she had no change of clothes until they reached the port.
In about two weeks they reached the port of Philadelphia in safety.
The serenity and cheerfulness of her countenance,
removed all anxiety respecting her from the mind
of a friend who went on board to see her,
on hearing of her arrival.
It was raining very fast when this faithful disciple
of Christ again set her foot upon land;
but, with that fervent piety for which she was distinguished,
she immediately knelt down on the quay,
and returned thanks for her providential deliverance,
and asked a blessing upon the captain.

She tarried about twelve months among Friends in America, where her fervent labors,
to do the will of her gracious Lord, and the sweetness and humility of her deportment,
endeared her to those whom she visited.

After her return home, she paid an acceptable visit to Friends in Ireland;
but did not subsequently go far from home.
She retained the love and esteem of her friends,
as one who continued to love the Lord Jesus, and having served him uprightly,
was able to testify of his goodness,
and to encourage others to walk in the path of obedience.

In her last illness, which appeared to be a gradual decay of nature, she remarked,
that she had been enabled to rely with confidence
on the merits and intercession of her Redeemer,
adding, "`To sit at the feet of my beloved Lord, in his kingdom, is more than I deserve;
but not more than I covet.
I know that it is by grace we are saved, through faith, and that not of ourselves,
it is the gift of God.
Oh, that it may be continued to the end.`"
At another time she said:
"`I feel that I have nothing more to do than to wait for
admission into the promised rest;`" further remarking,
"`What a favor, a blessed favor, to have nothing to do but wait for the last summons.
O! Lord Jesus, my Savior, be pleased to deal mercifully with your poor handmaid,
who has nothing to depend upon but your mercy.`"

How instructive and animating is it to contemplate the latter days of those, who,
having worshipped God in the Spirit, rejoiced in Christ Jesus,
and had no confidence in the flesh, peacefully close their earthly pilgrimage.
Such was the lively experience of this devoted Christian, who died in the Second month,
1815, at the age of seventy-seven.

[.asterism]
'''

JANE PEARSON, daughter of Jonathan and Jane Gibson, was a native of Cumberland,
and died at Whitehaven, at the advanced age of eighty-one, in the Third month, 1815.

It pleased the Lord, when she was young in years,
to work upon her heart by his good Spirit,
and to awaken her to a sense of the importance of a religious life,
and of the awfulness of eternity.
She early loved to read the Scriptures, and especially the New Testament,
and was deeply afflicted in reading of the sufferings
and crucifixion of our blessed Lord.
Her father dying when she was young,
the education of four surviving children devolved on their mother,
who manifested a pious solicitude and concern for them,
by the care which she bestowed on their education.
She was of a lively turn of mind, and of warm, affectionate feelings; and, in early life,
was strongly inclined to gaiety;
but submitting to the powerful operations of divine love,
these natural propensities were, in great measure,
brought under its restraining influence.

In the year 1757, being then about twenty-two years old, she was married to John Pearson,
of Greysouthen, a religious young man.
In the course of several succeeding years, she passed through much secret conflict;
her distress of mind was often very great, and the provings of her soul very deep: but,
in due time, she was enabled to yield obedience to the power of God inwardly revealed,
and, in the year 1773, first appeared as a minister, very acceptably to her friends.
In the following year her husband was removed by death; this was a heavy affliction,
and a few remarks, in a testimony which she wrote to his worth,
may be not unsuitably here introduced.
"`Oh, my loss is inexpressible!
His kindness, his nearness in a religious sense, cannot be set forth by me;
his compassion, his patience towards me,
his condescension to my weakness in my infant state, cannot be penned.
For indeed I had gone through various and deep provings;
many weary years had passed over my head,
while I was under the preparing hand of my God.`"

Not long previously to this event,
she had lost her two youngest children by the small-pox;
five survived their excellent father, some of whom were taken away in early life,
and the others at different periods after they grew up;
but they all died before their affectionate mother.

Jane Pearson was diligent and exemplary in the attendance of meetings.
Her ministry was sound and edifying; and though she spoke not infrequently,
and sometimes at length,
she was particularly concerned that she might not
go beyond the pure openings of the Holy Spirit.
She was deeply impressed with the solemn nature of public prayer;
and her offerings in this way were remarkably powerful and fervent.
In conversation she was lively, affable, and instructive,
being endowed with an excellent understanding.
She retained her natural cheerfulness to very advanced years,
and her mental faculties were unimpaired to the last.

It will be obvious, from this brief memorial of her tribulated life,
that she partook largely of outward affliction and conflict of mind; but through all,
her faith continued steadfast,
and she sought to place her whole trust in the mercy and
goodness of Him in whose ways are all in infinite love,
and in wisdom unerring and unfathomable.
He who had been the guide of her youth, and her support in seasons of great extremity,
was, at times, graciously pleased, in her declining years,
both in her silent waiting before him in religious meetings,
and in her secret retirements in her own dwelling,
to break in upon her with his life-giving presence;
to grant her the evidence of his love, and an undoubted assurance,
that when the trials of time should terminate,
she should be admitted to an inheritance incorruptible, that fades not away.

Not many weeks before her death, upon a friend`'s taking leave of her,
she seemed affected, and said, '`Though I drop tears, I am not left comfortless.
No; we have not followed cunningly-devised fables.
I think, what I feel might convince the whole world.
Oh, it is marvelous! it is marvelous!`"

At another time, she requested that her two grand-daughters,
being all the family she had, would not grieve after her;
but rather rejoice that she was released from all her sufferings:
"`for I believe,`" she added, "`that, at my dissolution, death will have no sting,
nor the grave any victory.`"

On the 17th of the Second month, 1815, being much tried with infirmity and pain,
she said with earnestness to those about her,
"`Join with me in petitioning the Father of mercies to relieve me from my sufferings.
Oh, that I had wings like a dove; for then I would flee away, and be at rest.`"

Very early in the morning of the 20th, her cough became troublesome,
and her breathing much affected.
About this time she was thought to be exercised in prayer,
but the words could not be understood.
She quietly drew her last breath about three the same morning;
and there is every reason to believe that she entered
into the rest prepared for the people of God.

[.asterism]
'''

ELIZABETH ASHBY was the daughter of James and Elizabeth Stevens, of Stains,
in the county of Middlesex, from whom she received a guarded and religious education.
In early life she was deprived of an affectionate father;
and by close attention to her surviving parent, through a long illness, her own health,
naturally weak, became considerably impaired.
This circumstance, together with a sense of the awfulness of death,
which was deeply impressed on her mind in childhood, were probably the means,
under the divine blessing,
of rendering her more obedient to the convictions of the Spirit of Truth,
and of subjecting her natural temper and inclinations
to the power of the cross of Christ.

In the year 1797, when about twenty-six years of age, she appeared as a minister.
In this character she moved with much humility and fear; and her communications,
which were not long, were acceptable and instructive to her friends.
In the following year she married Thomas Ashby, a Friend, resident in the same town,
by which union, the charge of six young children, his offspring by a former marriage,
devolved on her.
She seemed peculiarly adapted to this important trust; for,
though liable to frequent attacks of illness, the activity, and, at the same time,
the guarded state of her mind, in what related to the family,
rendered her a valuable acquisition to them.
By her affectionate attention, and solicitude for their religious welfare,
she greatly endeared herself to the objects of her care,
and promoted their best interests;
and was afterwards anxiously desirous that no distinction
might be felt between them and her own children.
She was naturally of a lively, cheerful disposition,
and wished not to depress those around her with a gloomy view of religion;
but rather to speak of it as producing an enlivening effect on the mind,
and rendering us better capable of true enjoyment.

In the spring of 1811, more than four years before her death,
she suddenly became the object of a distressing malady, which continued,
in a greater or less degree, during the remainder of her life.
At first it seemed probable that she could not long survive the attack;
and the prospect of a speedy termination of life, and of leaving her family,
brought her into much affliction and close exercise of mind.
To a relative, who came from a distance to see her, she spoke nearly as follows:
For a time there was a hard struggle, and nature still feels.
I hoped I might have been spared to my numerous family,
to have done the best I could for them, though that is but little!
I see many things I have been deficient in, and that I have evinced much frailty,
when I ought to have been more firm.
It is the way to lessen our strength, to give way in little things,
for thereby we are led on to greater deviations!
But nothing is little that tends to draw us further from, or strengthen us in, our duty.
And now my desire is, while ability to speak remains,
to impress it on those I leave behind,
that they will be so kind as to extend a little care towards my dear infants;
and when any thing occurs, by way of advice, that may seem needful,
do not be afraid to give it; for much may be done this way,
much may be done through love.`"
Adding, after some further remarks: "`We have not a hard master, I can truly testify:
he richly rewards our obedience.
But it is not for any deserts of mine, that I am favored to feel Him near as I now do,
to support, but merely of his mercy, his infinite mercy,
which surpasses all our capacity to comprehend.
We can have no adequate idea of it: we are poor, finite creatures.`"

At another time, waking composedly, she said in substance,
on looking round to see who were with her: "`How kindly I am attended:
I should not like to have such about me, as had no feeling; I mean,
no sense of what is good in their own minds.
While we are obedient as far as we know, we shall be accepted;
for it matters not of what kindred, tongue, or nation we are,
our merciful Creator is mindful of all.
He knows the heart;
and there are many that are but little accounted of by their fellow creatures,
who are precious to Him.
I often think, when we look round and are ready to suppose things are growing worse,
and that there is so much wickedness in the world, that it is very distressing;
that we should look on the other side,
and believe that there is much more good than we know of.`"

One morning early, she was much tried with acute pain, and said: "`Oh,
this is hard for the poor body to bear; but there is a better part,
and if that is but prepared to go, it does not matter.
It is a great favor not to have distress of mind; and the way for this to be the case,
is to be obedient: we shall be well paid for it.
Do not be afraid to give up in little things, but endeavor to walk by faith:
for were it not for faith and hope, what should we do in an hour like this?
This is indeed a trying hour, and it sometimes is very hard to walk by faith.`"
When under great suffering, she frequently exclaimed: "`Oh! pray for me,
that I may have an easy passage to those realms of bliss, where, above all things,
I long to go.
I have been favored with a foretaste of peace, beyond what I could ever have expected,
well knowing how undeserving I am of it;`" and added, "`Oh, what a favor,
in such a conflict of the poor body, to have no other conflict!
But there is no merit in me: it is mere mercy,
unbounded mercy! it is nothing but mercy that supports me in this state.`"

After uttering these and some other expressions, she was much exhausted,
and for several hours lay in a convulsed state,
attended with symptoms which seemed to indicate the near approach of death;
but she afterwards revived, and, for a few days,
appeared to be gaining a little strength.
She sweetly expressed her thankfulness for some abatement of violent pain, saying,
This may look a little like recovery; but I desire not to build upon it,
neither to be uneasy at again entering into life.
I desire to be resigned either way.`"

After passing nearly a sleepless night, she remarked to one of her kind attendants:
"`Ah! they little know what passes within, when the poor body lies here: sometimes,
though tried with great pain, the mind is favored beyond what I can express;
and that has been the case this night.
It has been a sweet night to me; such as, I am ready to think,
is a foretaste of a still better state.
Many passages in the Psalms have been brought to my remembrance, with great encouragement.
I am ready to wonder, that such a poor creature as I am,
should ever be made capable of experiencing what I at times do:
it is altogether unmerited on my part.
And I hope you will not think that I speak boastingly;
but I think it is no more than gratitude demands,
to tell a little to those that can understand the goodness of our merciful Creator:
it is very great.
I often have thought of the expression, '`He knows our frame:
He remembers that we are dust;`'--yet He is a God of justice.`"

At another time, when a little revived,
she said in reference to her state of uncertainty as to recovery: "`I have thought,
if I were only permitted to be able to sit and give directions,
and have some oversight of my family, I should be content;
but even this is scarcely likely, and I must not look that way.
There is One that can be a Father to the fatherless; and I trust He will care for them.
It is our duty, when we can not be doing, to submit to a state of suffering;
and by endeavoring to do so patiently, when it is our allotment,
we are fulfilling his will, perhaps as much as when in more active employ.
But this is hard to nature, and, unassisted, cannot be attained.`"

When her own complaints were very trying,
on being informed that her husband`'s mother was thought
to be so fast declining that she could not continue long,
but was in no pain, she said, "`That is a great favor; or, at least, I,
that am tried with so much, am ready to think so.
But we do not always know what are favors to us:
perhaps my sufferings may be a blessing to me, though very hard to bear.
I have no cause to complain.
I have been wonderfully favored in this illness.
I can truly say, the Lord has made my bed in my sickness;
and I desire to be resigned to what He may see fit to allot for me.`"

For upwards of two weeks the disorder continued nearly stationary,
accompanied with very trying circumstances, which often excited her anxiety,
lest patience should not hold out to the end; but through all,
the bias of her mind remained the same.
When tried with extreme suffering, she said:
"`Oh! that I might be preserved from impatience; that not a murmuring thought,
or impatient word, might escape me.
I have been so supported, that I have much indeed to be thankful for:
but through the constant wearing pain that I have, my spirits seem less able to bear up,
quite as they did some time ago.
Yet it is only my spirits,
for my mind remains unshaken in confidence and dependence upon all-sustaining Goodness.
Oh! who can disbelieve the existence of a Divine Being,
who has felt his support and assistance as I have done: and all of his free mercy,
for I deserve nothing?`"

On one of her relations expressing a wish, when she was in pain,
that it were in her power to do any thing to alleviate her sufferings, she replied: "`Oh,
no; you cannot.
You are all very kind, and do all you can; but there is only One that can ease my pain,
or enable me to support it: and that He has done wonderfully, beyond what I can express.
Oh, the sweetness, the heavenly sweetness, that I am sometimes favored to feel:
it is beyond my ability to describe.
But there are times of desertion too, and these I must expect while in this poor body;
yet there is no cause for us to complain,
when we remember the sufferings of our merciful Redeemer.
Oh! the wonderful love and condescension of Him who came to save poor sinners.
He suffered the ignominious death of the cross, and offered himself a sacrifice for all,
that we, through Him, might be saved.
Oh! then, these short afflictions,
if they do but work for us a far more exceeding and eternal weight of glory,
will be light indeed, compared with the everlasting reward.`"

To another relation she said, at another time: "`When I was almost at the worst,
that text often ran through my mind: '`O! death, where is your sting?
O! grave, where is your victory!`' I remembered, that the sting of death is sin;
and I hoped that sin was done away.
I have esteemed it an inexpressible favor, in this time of great trial,
to feel no condemnation; yet the approach to eternity has felt so exceedingly awful,
that I cannot describe it.`"

After a time, she continued very slowly to recover; and, beyond all expectation,
was so far restored as to be active in her family for more than a year and a half,
though in a state of great weakness,
and with frequent relapses that confined her to her chamber.
Her daily conduct, in this interval of time,
was such as to manifest a strong and steady desire that
her example might correspond with the divine precept,
of letting her light so shine before men,
that others might glorify that gracious Being who had eminently
displayed his love in the further refinement of her mind,
through a season of great affliction.

In the Eleventh month, 1814, she was again seized so alarmingly, that it appeared,
for several hours, as though the faintness of death was upon her.
On reviving from this attack, she said, "`I desire to be resigned,
and not to inquire why I am so tried.
I have much to be thankful for, in having been so supported,
and enabled to resign all my family into the hands and keeping
of Him who can do more for them than I can.
But this has not been attained without great conflict; nature will feel,
and sometimes seems as though it would be overwhelmed!
Then again a little encouragement is administered, in the remembrance of the dear Savior.
Our Lord himself, though in his divinity above all these feelings,
yet in his humanity He suffered the feelings of our nature,
when He prayed that the cup might pass from Him;
and then again his submission was shown (no doubt
for our instruction,) when he said to His Father,
'`Not my will, but yours, be done.`'
Oh! this is the grand point to aim at, but it is hard to reach.`"

After this, she was confined to her bed for several months,
and preserved in a state of great tranquillity and resignation,
which was consoling and instructive to her friends.
On the 17th of the Tenth month, 1815, she said to her husband, "`My dear,
I wanted to see you; I shall not live many hours longer.`"
On his asking her how she felt in mind, she replied, "`Quite easy,
the day`'s work is done.`"
Her weakness gradually increased for several hours; but she was sensible to the last,
and quietly expired the same day, at the age of forty-four.
