== Chapter 6

[.chapter-synopsis]
* James Abell
* Charles Coleby
* Joseph Ransom
* James Graham
* Robert Searles
* Hadwen Bragg
* Mary Naftel
* Elizabeth Sybilla Fry

JAMES ABELL was the son of Joseph and Mary Abell, of the city of Cork,
and was born there, the 15th of the Sixth month, 1751.
He was considered a young man of religious life and conduct;
one who had early surrendered his natural will to the restraining
and sanctifying influence of the grace of God,
and had thus been prepared for usefulness in the church.

Early in life he relinquished the concerns of trade, thinking,
if he rightly estimated the blessings of the life which is to come,
that it would be unwise in him to continue such pursuits,
when blessed with a sufficiency for his comfortable accommodation,
while passing through this probationary state.
He was moderate in his expenses, and thus had the means of contributing liberally,
which he did, to the various subscriptions raised for the use of our Society.
He showed himself also a true friend to the poor, in different ways:
and in a kind and benevolent manner assisted in relieving their needs,
without regard to name or profession.

When about thirty-three years of age, he was appointed to the station of an elder.
He fulfilled the duties of this office as a faithful
and vigilant laborer in the Lord`'s vineyard,
indicating by his conduct and conversation,
that he preferred Jerusalem above his chief joy.
And his friends have cause to believe that he might
have united in adopting the language of the apostle:
"`As the sufferings of Christ abound in us, so also our consolation abounds by Christ.`"

In manifesting his love for the truth as it is in Jesus,
he had many sore conflicts to endure, which he did with holy stability and meekness,
in a time of great suffering to the faithful members of our Society, in his native land;
maintaining his confidence in God,
and an unshaken attachment to the principles of his profession.

He was a steady and diligent attender of all the
religious meetings of which he was a member,
and occasionally visited the general meetings in the other provinces of Ireland.

To the young he was a tender friend; exercising, as a father in the church,
a wise and judicious care over them,
and being much concerned that they might walk in the path of simplicity and self-denial.
In his interaction with men, his conduct and example were strikingly circumspect;
and he was a bright pattern in the discharge of the relative duties of life.
He possessed great sweetness of disposition,
and was conspicuous for love without dissimulation;
an essential feature in the character of those who are disciples of our blessed Lord.

While preparing to leave home, to attend a quarterly meeting at Limerick,
he had an apparently slight attack of illness.
Exempted from those sufferings which often precede a final separation from this world,
he only survived this seizure about one hour, and then peacefully,
and almost imperceptibly, expired, on the fifteenth of the Seventh month, 1818,
at the age of sixty-seven.
His burial was numerously attended by his friends and fellow-citizens,
amidst the general regret of all classes.

[.asterism]
'''

CHARLES COLEBY, of Alton, in Hampshire, was the son of Joshua and Mary Coleby, of London.
In childhood he discovered an active and cheerful disposition; and at Ackworth,
and other schools, gained the affection of his school-follows,
and the esteem of his teachers.
After the completion of his education, he was placed as an apprentice with his uncle,
at Alton,
where he discharged his duties in business with fidelity and affectionate attention.

He very early evinced a serious turn of mind, by a reverent deportment in meetings,
and in the time of silence before meals, and by his general orderly conduct.
He also manifested a desire to read books on religious subjects;
especially the Holy Scriptures, in which he appeared to delight.
When about the age of fifteen, in reply to a letter from his father,
on the subject of books,
he observed that he had been reading Newton`'s Dissertations on the Prophecies,
from which he derived much satisfaction;
and that he was surprised any one could entertain principles of infidelity,
after a careful perusal of this work,
in which there are such clear proofs of Scripture
prophecies having been already fulfilled.

For many months previous to the commencement of the
affliction which terminated his earthly existence,
there appeared to be an increased watchfulness in all his actions,
with renewed attention to his religious duties, retiring, when opportunity offered,
for meditation and prayer.
Those who witnessed his comparatively innocent life,
entertained the hope that he would have but little conflict of`' mind to pass through;
yet it pleased Divine Wisdom to try him with deep baptisms of spirit,
from the awful impression of the extreme sinfulness of sin.

He often lamented, that during the time he had been at Ackworth,
he told some known untruths, the recollection of which occasioned him real sorrow;
as did also the following circumstance, which occurred when he was about seven years old.
While with his uncle at Harleston, he had taken a farthing without his leave,
which he now requested his aunt, who kindly attended him during his last illness,
to return to his uncle; remarking, that it might appear a small sum,
but that it was not the amount, but the act, which pressed upon his mind.
This request being complied with, he appeared to be relieved.

He bore his long illness with much patience, and often asked to be left alone, or,
when able, frequently retired into another room,
when he was earnestly engaged in prayer to the Almighty,
that he might be assisted to hold fast his faith,
and be favored to close his life with calmness, and resignation to the Divine will.
When engaged in vocal supplication,
he evinced a strong sense of the necessity of a Redeemer; believing,
that by and through Him alone, we obtain forgiveness of sins, and have access to God.
He was so desirous to have his mind abstracted from all outward objects of dependence,
that, when it became improper, from his weak state, to leave him alone,
he often asked his kind attendants to withdraw into
situations where he could not see them:
fearing lest the sight of them might occasion him to look for help from them,
when the Lord required the whole heart and affections to be surrendered to him;
observing: "`Oh! that I could love Him more and more,
and that He would be pleased to give me a broken heart and a contrite spirit.`"
On its being remarked, at times, that his sufferings were great, he would reply:
"`They are small, indeed, when compared with those of my dear Redeemer.`"
At other times he remarked, that his bodily afflictions would be very light to bear,
could he but experience a comfortable hope of acceptance with God.
Once, about midnight, he broke forth in fervent supplication for a considerable time,
concluding with these expressions: "`Yours is the power, mine is the weakness:
yours is the glory, mine is the shame.
Amen.`"

For the last few days of his life, being extremely sore and weary with lying,
he suffered much pain whenever he was moved; yet, under all, he did not complain;
but said, that he humbly hoped his patience might be permitted to hold out to the end;
often asking others to pray for him, when,
from being unable sufficiently to collect his thoughts,
he seemed incapable of discharging that important duty properly himself.
The day before his death he suffered much.
He said, he had prayed that the conflict might be over that night;
but he was afraid it was presumption in him,
as it might be too much the result of feelings arising from great bodily affliction;
adding, very sweetly, "`Dear father, pray for me; but be sure say, Your will be done,
and not mine.`"
He then fell into a short sleep; but soon awoke under considerable agitation of mind,
which continued through the night, with but short intervals of composure.
In these he expressed much fear,
lest he might have spoken hastily during the unsettled state of his mind.

In the morning, through Divine mercy, this state was succeeded by a holy calm,
which no language can express, and of which all in the room seemed in degree to partake.
From this time until his death, about an hour and a half, he continued in supplication,
although the voice was so feeble, that his attendants could not collect the substance;
except that, in one instance, he clearly articulated, "`Your will be done forever.`"
After this he departed without a struggle, at the age of sixteen years and a half,
on the 1st of the Fifth month, 1819.

[.asterism]
'''

JOSEPH RANSOM, son of John and Ailn Ransom, of Hitchin in Hertfordshire,
was a young manl of orderly conduct, and well respected by his friends and acquaintance.
He was of active, industrious habits; and having a taste for agriculture, rural scenery,
and natural history,
he combined rational amusement with the pursuit of his usual occupations.
About the middle of the year which preceded his death, his constitution,
which was naturally strong, appeared to be generally giving way,
under the effects of a complaint in the hip,
by which he had been affected from very early life;
and a spasmodic affection of the throat, about the same time,
led his family to look upon his continuance with them as short and precarious.
The progress of his disorder, which at first in part, and afterwards wholly,
confined him to the house, and was particularly trying to his natural disposition,
gradually weaned him from outward enjoyments; awakening greater solicitude,
that the all-important end of our being here might be fully answered;
and thus his long-protracted illness was made a blessing to him.

On the 11th of the Fourth month, 1819,
his mother inquired of him as to the state of his mind, when he replied:
I am comfortable, very comfortable.
Indeed, I have often felt so, that I have wondered, and been afraid to acknowledge it,
when I considered my own great unworthiness, lest it should be a false feeling;
but I believe it is not so.
As to the event, I have not had any desire from the first, to choose, being willing to go.
Though I am not tired of life, and could like to be longer with you;
but if I am now taken, I believe you will not have cause to mourn on my account,
nor on your own.
I am only, in my weak state, a trouble to others.`"
On being assured that it was far from being so considered by his friends, he said:
"`Well, I trust if I am longer spared, it will be a blessing to me.
I believe it will be sanctified.`"
And on a hope being expressed, that, as the outward man declined,
the inward might increase in strength, he said: "`It is so, it is so:
I am comfortable and comforted.`"

Some months previous to this,
he had expressed his conviction that his afflictions had been to him blessings.
On occasions afterwards, he repeatedly spoke of his humbling sense of Divine regard;
and appeared evidently to confide in the God of all consolation, for support and comfort,
who he knew would not afflict but for some good purpose.

On the day preceding his death,
being told that the doctor thought he was rapidly becoming weaker, he said:
"`A little time back I thought my view of enjoyment here was rather brightening,
and I could like to stay longer with you; but that is now closing,
and I am willing to leave.`"
A hope being expressed, that he had brighter prospects than these in view, he replied:
"`Yes, far, far!`"

In the course of the day he often said, it was hard work, but he believed all would,
in the end, be well; and of this, at one time, he said very impressively,
he had no doubt.
He frequently petitioned for patience to endure the violent pain,
which was indeed distressing; but, he said,
"`The presence of my Savior makes up for all.`"
Affectionately pressing his mother`'s hand in both his, he said, in substance:

"`Farewell, my dearest mother: may the Lord reward you and yours,
for all your kindness to me.`"
In the evening he took an affectionate leave of his surrounding relations;
and to two of his cousins, added emphatically: "`Remember your latter end,
now in the days of your youth.
May all take warning not to defer any thing to a time like this.
It is, indeed, hard enough to have to struggle with the pains of the body.`"
In the extremity of his sufferings, he exclaimed: "`It is hard, very hard to bear.
Blessed Jesus! come quickly; but your will be done.`"
And he soon added: "`Oh, if for purposes of your glory,
it be yet lengthened out for hours and days, grant me patience, and all will be well.`"
He soon after exclaimed: '`Oh, how the prospect brightens!`"
About this time, which was nearly two hours before his decease,
the acuteness of his suffering ceased, and his breathing gradually became shorter.
During this time he was repeatedly heard to say, "`Jesus, precious Jesus!
Praises!
Praises!
Praises!`"
With this last expression his articulation became indistinct,
and he passed from time into eternity, at the age of thirty-five,
on the 8th of the Eleventh month, 1819.

[.asterism]
'''

JAMES GRAHAM was born at Westerkirk, on the borders of Scotland, in the Eleventh month,
1734.
His parents were religious characters,
and carefully educated their son as a member of the Presbyterian church of Scotland.
When about eighteen years old,
at which time he was a zealous professor of the principles
in which he had been brought up,
he removed into Cumberland; and,
having frequent opportunities of becoming acquainted with the members of our Society,
he thought it pitiable that a seriously-disposed people
should be so blinded as he apprehended they were.

In the twenty-third year of his age, it pleased the Lord,
by the powerful operation of his Spirit, to introduce him into deep mental exercise,
which brought him very low, both in body and mind.
In this tried situation, he was thought to be in a declining state of health;
but as he faithfully endured the chastening of the Divine hand,
he was delivered from this humiliating conflict.
In the year 1763, about six years after he had, to use his own expressions,
embraced the Truth in the love of it, at which period he was, probably,
admitted a member of our Society, he was constrained to appear in public testimony,
and to warn Friends to be more inward with their God.
In the course of the same year, he married a young woman of Carlisle monthly meeting,
to which meeting he then, and for many years afterwards, belonged.

Being in low circumstances,
he was obliged to work very hard in his employment as a sawyer,
for the maintenance of himself, his wife, and a large young family.
He submitted to this with cheerfulness and exemplary diligence;
believing that that gracious Being, in whom he had trusted,
would enable him to make a sufficient provision for their support.

His ministry was well received by his friends as edifying and instructive;
and he was much beloved and esteemed by them, as a man of sound judgment,
and one who had learned in the school of Christ.
In the year 1783, and in several successive years,
he travelled acceptably in the service of the Gospel, in various parts of the nation.
His last journey in this way, was performed at the age of seventy-seven;
and on his return, he made this short memorandum: "`Came home to my house,
with a heart thankful to the Father of all our mercies, for his care.`"

He was a good example in the attendance of religious meetings; and having,
in the performance of this great duty,
himself partaken of that spiritual refreshment which
is often derived from silent waiting before God,
he was concerned to invite his friends to increasing care in this respect.
He especially exhorted those who, from their situation in life,
had to labor hard for their support,
to be regular in frequenting their week-day meetings.
His own experience enabled him to couple this with a belief,
that if it were done under a proper engagement of mind,
their outward affairs would not suffer.

James Graham had received very little education in early life,
having been barely taught to read and write;
but he brought up a family of nine children with reputation.
He never possessed much property; nearly the whole of what he had,
was acquired by hard labor and economy; but he was hospitable to his friends,
and a generous contributor to the pecuniary claims of our Society.
He exemplified, in his conduct, that "`godliness with contentment, is great gain;
having the promise of the life which now is, and of that which is to come.`"

Towards the close of the year 1815,
having about eight years previously removed with
his wife and family into Pardshaw monthly meeting,
he was suddenly attacked by paralysis, which, in a great measure,
deprived him of his customary activity, and considerably affected his speech.
After he had somewhat recovered,
he intelligibly and pathetically repeated the following
stanza from one of Addison`'s hymns:

[verse]
____
My life, if you preserve my life,
Your sacrifice shall be;
And death, if death should be my doom,
Shall join my soul to thee.
____

Some time afterwards, he was again able to attend meetings,
though the power of articulation was not fully restored.
In the First month, 1818, a-recurrence of the same disorder took place; and,
on being asked how he was, he replied, that he could not be better;
that he felt his Maker very near, and that he longed to be with him:
and to a friend who went to visit him, he said,
"`Though I am much broken down as to the outward, yet all is peace within;
all is peace within.`"
Not long after, he entirely lost the power of speech; and in this situation he was,
for many months, in a tolerably good state of health.
It was apprehended that his mental faculties were still continued;
and he appeared to be frequently engaged in fervent supplication.
He was preserved in a meek and quiet spirit,
tears often trickling down his furrowed cheeks.
He died on the 5th of the Twelfth month, 1819, at the age of eighty-five.

[.asterism]
'''

ROBERT SEARLES was horn at Glatten, in Huntingdonshire, in the year 1764,
of parents professing the religion of the Church of England.
In his youth, he was a frequent associate with persons of irreligious character,
in the lowest stations of life; but when about twenty-three years of age,
he became seriously disposed, and soon after joined the Society of Calvinistic Baptists;
among whom he was esteemed a highly valuable member.

The circumstances which gradually led to a change
in his views on the most important subjects,
are described by himself nearly in the following words.
After regretting that a difference in religious sentiments should
produce so hostile a disposition in some serious minds,
as at that period he had observed, he proceeds to remark:
"`The great Leader and Pattern of Christianity said to his disciples,
'`He that is not against us, is on our part;`' but some think,
because another does not see as they do, and does not walk with them,
he cannot be a disciple.
Whereas it would be much better to endeavor to imitate our holy Pattern,
who was meek and lowly, kind and compassionate, willing to endure the cross,
and despise the shame.

"`I began to listen to what some of our neighbors said, that this was right,
and the other wrong.
I left off going to the meetings of the General Baptists,
who held salvation possible to all men; and went among the Calvinistic Baptists,
who profess that salvation is provided for only a part of mankind;
and that this part are sure of it, without any possibility of their missing.
But although they thus profess,
how often do their ministers invite all to the Gospel Feast,
to partake of that bread of which, according to their own doctrine,
there may be none provided for them!
But what a favor, that no one is excluded from it but those who exclude themselves.
Welcome the ignorant and polite; the learned and the rude.

"`I constantly attended the meetings of the Calvinistic Baptists,
was very earnest to be instructed, paid all the attention I possibly could,
and was glad when meeting-day was near, that I might go and hear another sermon.
I also wanted to feel more of that power within,
which was so much talked of among them; but in that I knew I fell short,
although I greatly longed for it.

"`I read much; prayed earnestly and constantly;
endeavored to get with those who I thought were spiritual:
but all would not make me quite satisfied.
I thought the people with whom I walked in a religious way were right,
but that I was wrong myself.
I thought I did not enter in at the right door.
Thus I went on until I became a member of their community;
took part of the bread and wine; and was immersed in the river Ouse at Holywell:
but I did not find myself so fully satisfied,
as I thought others were who practiced these things.
My conduct all this time was steady and regular.
I was respected as a servant or laborer; but felt a great deal of that about me,
which needed doing away: yet not applying rightly for the perfecting of the work,
it went slowly on.

"`In the course of time my wife also became a member with the same people,
and remained so until her death.
I think I went on in this way about eight or nine years,
and did not gain much spiritual ground, as I thought.
In process of time an occurrence happened which led to another change with me.
My master who employed me, died; and another came who professed Quakerism,
as it is called.
He being observant of his new set of men, and religiously inclined,
left books in our counting-house, which,
being desirous of knowing religious people and things, I used to get and read.
One of these books was, Robert Barclay`'s Apology for the Christian Faith,
as held by the people called Quakers.
I thought myself a match for that, but was mistaken; for whenever I read in it,
it used to reach my feelings.

"`I cannot very well remember how it happened,
but I went to one of the quarterly meetings of Friends;
and there being a pretty-many ministering Friends
that day on an appointment from their yearly meeting,
a great many living testimonies were borne in the power and authority of Truth,
to the tendering of my spirit: and a refreshing meeting it was to me.
On my returning home, I thought,
surely these must be the people who hold the solemn meeting;
and if I were clear of those other people, I should go to the meetings of Friends;
but I did not know what I must do, nor how the matter would end.
However, I was so far inclined to them,
that I ventured the next first day to attend their meeting again:
and some of the same Friends were there, and bore living testimony to the power of Truth,
and again refreshed my spirit.`"

Robert Searles became a diligent attender of our religious meetings;
and in the course of a few years, was, with the full unity of friends,
admitted as a member of our Society.
He was brought up to the trade of a miller, and,
for about the last thirty years of his life, resided at Houghton, in his native county,
in the capacity of a servant.
He was a widower for several years after being united in membership with Friends,
and married a second time, in the year 1808.

His exemplary life and conduct, and unaffected simplicity of manners,
joined to deep humility,
and his care honestly and conscientiously to discharge his duty as a servant,
gained him the love and esteem of his friends.
Private retirement was his regular, daily practice: and on these occasions,
as appears by a short diary published since his death,
he often impartially examined his conduct, and the state of his own heart.
At these times, too, he meditated on those rich consolations which are in Christ Jesus,
and was permitted sensibly to partake of the influence of his spirit.
This record of a lively concern for the salvation of his soul,
offers an example worthy of imitation by all,
and especially by those who are in a dependent situation in life,
to be industrious in this most important work.
Private admonition was also a duty which he often performed,
though much in the cross to his own inclination.
The discharge of this kind office, so beneficial to his own mind,
was not confined to the members of our own Society, but extended to many others,
by whom it was generally well received;
being accompanied by that love which breathes "`peace on earth and good will to men.`"

Thus dwelling near the fountain of Divine life, he was, in due season,
enabled to yield to an apprehension of duty,
to appear as a minister in our religious meetings,
which was to the comfort and edification of Friends.
His testimonies were clear and impressive, accompanied by the baptizing power of Truth,
and eminently owned, as the duties of a faithful minister of his Lord and Master.

The following extracts from two letters, written in the early part of the year 1820,
describe the watchful state of his mind.

[.embedded-content-document.letter]
--

1820.-- First month, 21. I feel glad to find myself at home again,
among the concerns relating to this present life:
although my service in this matter seems to me on the decline;
yet I am most easy to do what is proper for me to do.

I cannot think that I have done any thing, or suffered any thing,
worthy of the regard of him who so plentifully promises to reward in this life,
and in the world to come with life everlasting; but I feel myself as a beginner,
desiring to obtain a measure of strength to abide the day of trial,
and to do the day`'s work in the day.

1820.--Fourth month, 7. I long that I may be one of the subjects of Christ`'s kingdom,
which, he tells us, is not of this world;
so that I may be redeemed from the root of all striving,
patiently submitting unto the Heavenly Father`'s will in all things.
I hope I shall not complain, nor think my case hard.
I am mortal, and must decay as to the outward, but am at times,
(although at some others very much discouraged,) in the
hope that the inward man gains a little strength.
But more deepening is necessary,
to come to a certainty of being prepared for an admittance into peace,
when the spirit leaves the mortal tabernacle.

Oh! remember, dear friend, how frail man is! at best but a fading flower,
which while the day of sunshine and heavenly rain continues, does and looks well;
but how soon may a blast nip it, or drought dry it up, and the freshness thereof fade.
Therefore, learn more and more to cease from man,
and trust in the Lord alone for help and strength, to work while it is day,
and vigor is felt, before desire fail.
Oh! fear not man; neither what he can do unto you; but look inward,
have your mind centered in the life alone, and as that moves, move with it.

--

In the spring of the year 1820, he was taken unwell, but generally attended to his work.

On Seventh day, the 15th of the Fourth month, he became much worse.
Although suffering under much debility of body, he attended the meeting at Ives,
on the following day, where he was favored to labor as a minister, for the last time,
in a remarkable manner;
forcibly impressing upon Friends the necessity of
a frequent recurrence to that Divine Power,
which had called us to be a people, in order to obtain instruction and direction,
so to walk, as happily to be found among those,
who had not seen their Lord and Master naked, sick, or in prison,
without ministering to Him.

He was confined to the house about a week.
In a note to a friend, about this time, he concludes thus: "`O dear friend,
what a happy escape,
to be removed from these changing scenes to a state of uninterrupted
tranquillity! but I desire first to bear patiently all that
is needful for a preparation for such a pure state.`"

On the 17th, a friend going to see him,
in the course of conversation he instructively remarked:--
"`There is nothing will do but keeping in the cross;`" and further observed,
that he knew not how it might be, but in this illness he felt no condemnation.
The same friend visited him again on the 21st when under great suffering of body;
but his mind was remarkably calm and tranquil:
he had done his day`'s work in the day time, and having now nothing to do but to die,
he again emphatically repeated, "`I feel no condemnation.`"

Feeling a little revival of strength,
he requested his wife and a few friends to sit with him a while, when he said: "`Now,
what I want for us is,
that we may be more fully dedicated-more resigned to follow the Lord,
to follow Jesus Christ: there is no other way.`"
And soon after he remarked:
"`I do not see but I may yet abide;`" at the same time adding,
Oh! that I had wings like a dove, then would I flee away and be at rest,
and hasten my escape from the windy storm and tempest.
I have need of resignation to bear these sharp afflictions.`"

In this peaceful state of mind,
was this dedicated servant of the Lord prepared to exchange time for immortality.
This solemn event took place on the 24th of the Fourth month, 1820.
That Divine Power which had been so eminently his support in life,
did not forsake him in sickness; that which had been to him riches in poverty,
was now a present help in the time of need;
evincing the truth of that declaration concerning our Lord, that "`having loved his own,
He loved them unto the end.`"

[.asterism]
'''

HADWEN BRAGG was born at Whitehaven in Cumberland, about the year 1763.
His parents, John and Margaret Bragg, were Friends in good esteem,
of whose tender and pious care over him, in his early years,
he often spoke with gratitude.
Being placed as an apprentice with a respectable tradesman of his native town,
who was not a member of our religious Society,
he was exposed to temptations tending to lead into some
deviations from the principles of his religious profession.
This occasioned him much thoughtfulness;
and as the termination of his apprenticeship drew near,
he was increasingly concerned to seek after an experimental acquaintance with that power
graciously afforded to preserve the dependent mind in the path of safety.

After the expiration of the term, he spent a short time in London,
where goodness and mercy continued to follow him.
The state of his health did not permit him to remain long there;
yet he found in that great, crowded, and, to many an unwary youth, polluted city,
those with whom he took sweet counsel;
and being privileged with the instructive society of religiously-concerned Friends,
his pious resolutions, and earnest aspirations after Divine aid, gained strength;
and his tarriance there was a time of much profit to him.

On his return to Whitehaven,
he had an advantageous offer of a share in the business
of the individual to whom he had been an apprentice,
which he thought it right to decline.
This arose from a conscientious fear,
lest by being connected with one of different religious views,
he should be induced to deviate from a strict adherence to testimonies which,
though some may esteem them of minor importance, he had seen it right for him to bear.
This step was a close trial of his faith,
from the surprise which it occasioned to his kindly interested friends; and because,
at that time, no other situation, as a necessary provision for a livelihood,
presented itself.

After accompanying two women Friends on a religious engagement in Scotland,
he visited the town of Newcastle upon Tyne, when an-entire stranger to the place;
and in the year 1788, concluded to fix his future residence there.
On his entering upon the cares of life, he sought, and was favored to find,
wise and experienced counsellors, in whose society he took great delight;
and it was his sincere desire to walk in the footsteps of the followers of Christ.

In the latter years of his life, he was often led to look back,
with feelings of pious gratitude, in contemplating that providential arm,
which in his early years had protected, and which, at the period above alluded to,
had guided him to this conclusion; and the various circumstances that marked his course,
all tended to confirm his views of the advantage which those derive
who seek Divine counsel in their outward concerns.

Such were his stability and consistency of conduct,
that he was appointed by the monthly meeting to the station of an overseer,
at an early period of life; and a few years afterwards, to that of an elder;
offices of no small importance in the church; both of which he filled,
with much propriety and usefulness, until the time of his death.
The reverent frame of mind which he sought to attain in religious meetings,
was often indicated by his countenance;
and his lively exhortations in meetings for discipline, were impressive and instructive.
By his faithfulness and prudent zeal in the affairs of our Society,
carefully following what he believed to be the pointings of the Spirit of Truth,
he was made instrumental in promoting the firm,
yet tender exercise of the discipline of the church.

He was diligent in providing for his family, and executive in attending to his business,
which was that of a linen and woollen draper,
but was enabled to keep these outward concerns subordinate to higher duties; and,
through watchfulness,
was preserved from the injurious and engrossing tendency of worldly pursuits.
He had many young men in his employ, as apprentices and assistants,
whom he treated and watched over with a kind, paternal care;
possessing in a more than common degree,
the talent of rendering social conversation pleasant and instructive.

He was a man given to hospitality, and liberal in promoting works of charity;
and being of a clear and sound judgment, of great urbanity of manners,
and having his heart warmed with an expansive benevolence,
he was very useful in assisting to conduct several institutions in the town of Newcastle,
for the relief of distress, the instruction of the ignorant,
and the spreading of the knowledge of the great and saving truths of pure Christianity.

Thus he endeavored to improve the talents with which he was entrusted,
and to serve the Lord, the Creator of heaven and earth;
yet was he deeply sensible that it is only through the mercy of God,
in Christ Jesus his Son, that we can know the remission of sins,
and access to that grace wherein alone we can safely stand; and whereby,
as its influence prevails, the evil propensities of our nature are overcome,
and strength is afforded to persevere in the path of the just.

The illness which terminated the life of this humble Christian was a protracted one,
and often attended with great bodily suffering; yet he was, through all,
preserved in an unshaken confidence in redeeming power and love;
many times expressing the ardent desire which he felt, "`to be sanctified throughout,
in body, soul, and spirit.`"

In the early part of the Fourth month, 1820, when taking leave of some of his relations,
he spoke, in great tenderness and humility, nearly as follows:
"`I may commemorate the goodness of the Almighty to me all my life long,
who has abundantly blessed; and although I often feel poor, and very unworthy,
his gracious arm is now felt to be underneath, to support in this season of trial.`"
At another time,
after a day or two which had been passed under much bodily weakness and depression,
he intimated, that, though consolatory feelings had at times been permitted,
yet it was then a season of proving; and, in the evening,
inquired relative to that verse in Isaiah:
"`You will keep him in perfect peace whose mind is stayed on you,
because he trusts in you.`"
The following morning, he acknowledged, in much brokenness of spirit,
the consolation which the preceding passage had afforded him during the night,
and that peaceful feelings were again renewed.

At one time, when under great bodily suffering,
he expressed the solicitude which he felt,
to be preserved from desiring anything but what was best for him; adding,
"`"When under severe pain, it is difficult to suppress the wish to be relieved;`"
and remarked on this, as on a similar occasion,
that any little plaintive accents which might escape him,
were not from an uneasy mind, being favored to be free from all anxiety.
A restoration to health, he said, would look grateful, for the sake of his dear family;
yet dissolution appeared desirable, rather than long-continued suffering;
but herein he evinced Christian resignation and patience.

His disorder assumed an increasingly serious aspect; and, on the 1st of the Ninth month,
his beloved wife,
on expressing the anxiety of the family to do all they could for his relief, added,
"`But there is only One who can help.`"
He replied, "`Ah! no, there is but one source of support, and to that I look.
I crave, I crave that the support hitherto extended may be continued;
and that none may be dismayed by my sufferings.
I desire entire resignation: is it not said, '`Though he slay me, yet will I trust in Him?`'
Nothing but coming again and again to the footstool, will do.`"
A few days afterwards, upon a belief being expressed that, at times,
he felt sensible support, he replied, "`Yes; were it not so,
I should be overwhelmed;`" impressively adding,
"`I cast myself entirely upon a merciful and gracious Creator.`"
On the intimation of a hope being entertained that he had an unclouded prospect of happiness,
he said, "`Inasmuch as I feel no condemnation; mercy,
nothing but mercy and goodness are near.`"
On others of his relations coming into the room, he alluded to what he had just said,
remarking, that though his soul had often had deep wadings, yet, not dismayed,
he was enabled to place his dependence upon Divine mercy;
that he felt his situation to be serious and awful; and a constant solicitude attended,
that in nothing he might offend.
This, he said, had been his state for months past.

On the morning of the 5th of the Ninth month, 1820,
the day on which his peaceful spirit was released from its afflicted frame,
on reviving a little after a violent attack of sickness,
he remarked that many had been the vicissitudes in his complaint;
that it was wonderful to him that he was again restored; but continued,
"`I am not careful about another hour;`" and upon his most endeared attendant saying,
"`Then you cast your care upon a merciful Creator,`" he replied, very emphatically,
"`Yes; upon a gracious God, in whom all around my bed may confide.
Let all do their duty: keep in a tender, watchful, humble state of mind.`"

Articulation had now become more difficult;
but that.gentleness and gratitude which had been the clothing
of his mind during a long and painful illness,
shone conspicuously to the last.
While free from extreme suffering, he seemed centered in stillness,
at times desiring that his quiet might not be disturbed.
The words "`dear Jesus,`" were distinctly heard,
when the connected aspiration was not collected.

Thus closed the earthly existence of one whose life
was peculiarly marked by love to his fellow-men,
and by a more than common interest in the peace and welfare`'
of the religious Society of which he was a member;
and we may consolingly believe,
that his purified spirit was mercifully translated to the realms of eternal bliss.

[.asterism]
'''

MARY NAFTEL was born at Austle in Cornwall, in the Tenth month, 1756.
Her parents, John and Joanna Higman, were members of our Society;
and as the meeting to which they belonged was very small,
they had but little fellowship with Friends.
On a retrospect of her early life, she remarks:
"`So long back as I have any recollection, I had some sense of God upon my mind.
Manifold have been the gracious dealings of the Lord with me,
from my very infant days unto the present time.`"

The watchful care of her grandmother seems to have made a deep impression on her mind,
and was revived in after life.
She was taken from her at an early age; after which period, by unwatchfulness,
she deviated from the simplicity of our testimonies.
But, through Divine mercy afresh extended, her mind was humbled,
and she became sensible of the dangers to which she had been exposed;
and wrote as follows: "`You are my God, and I will praise you; my Savior,
and I will extol you.
What moved you, O you Father of infinite goodness and mercy! to cast an eye,
a pitying eye, upon me, a poor worthless creature,
when I was running in the sure road to eternal destruction?
Nothing, nothing but your unbounded love to the poor souls of men,
who would not that any should perish, but that all should come,
and have everlasting life.
When I was sitting low in the earth,
wearied with following the vanities of this licentious age,
wanting to find more of happiness than this transitory world can give,
then you looked upon me, O Lord! in your infinite and unspeakable mercy, and said,
'`Follow me:`' no, not only so, but led me forth, free from the entanglements of the world,
and from the many snares that are therein.`"

About the twenty-second year of her age she first spoke as a minister; and,
in the year 1789, was married to Nicholas Naftel, and settled in the island of Guernsey,
where they resided more than fourteen years.
She travelled diligently in many parts of this nation as a minister,
and in the latter part of her life removed with her husband to Chelmsford;
from which place she was absent about two years, on a religious visit in America,
where her gospel labors and circumspect conduct were edifying.
On a review of this visit, she writes thus:
"`Since my return to my own habitation in peace,
in commemoration of the Lord`'s gracious dealings with me,
how can I do less than leave testimonies to his goodness and tender mercy,
in permitting me to return with joy.
Strength has been afforded me to give in my certificates,
both to the monthly and quarterly meetings, with those from the American continent.
Oh! how often is my mind bound up with some there,
in the ever-blessed covenant of love and life, which, I trust,
will never be dissolved or broken.`"

The friends of her own monthly meeting, in their testimony concerning her, remark:
"`Having had large experience, and being favored with clear discernment,
she was often engaged to minister in the love of the Gospel,
to the different states of those present, to their edification;
and in supplication she was clothed in great reverence and weightiness of spirit.
Her deportment was grave and serious, yet her conversation cheerful and instructive;
and her memory is precious.`"

In the course of the year 1820,
she paid a religious visit to friends in Dorsetshire and Hampshire,
and on the island of Guernsey, where she was, for some weeks, closely occupied.
She reached home the latter end of the Ninth month, very much exhausted;
and though medical aid was called in, her illness continued to increase.
In the course of it,
she evinced much solicitude for friends and those under convincement in Guernsey; and,
in speaking of the journey, remarked,
"`I do not know but paying the last visit may be a means of shortening my days,
and sometimes I think it will be so; but I feel peace in it, sweet peace;`" adding,
"`What a favor, at such a time, to feel so resigned,
and to have only the pains of the body to struggle with.`"
Soon after, speaking of resignation, she said, "`Oh! it is a fine thing to be resigned,
to be quite resigned, and to love the Lord with all the heart;`" and after a short pause,
added, "`What a very sweet place it is, where it is said,
'`I know your works and tribulation.`'`"
And at another time said, "`Oh! how precious is love.
I wish my love to all friends, everywhere.
I never felt greater love than I do now;`" and then added, "`The joy I feel.`"

On a few friends going into her room she remarked:
"`How sweet is the fellowship of congenial spirits, even here!
What must it be with saints and angels, where there is no alloy?`"
She afterwards said,
"`I have wished that both the elder and younger may be encouraged to faithfulness.
I remember how earnestly I waited upon the Lord in early life,
to know the revelation of his will, which now affords me much comfort.`"

Her illness continued for several weeks,
and was sometimes attended with considerable pain,
which she bore with Christian patience,
evincing that her mind was greatly favored with Divine love, and said, "`Through mercy,
I have a hope that, if I am taken, I shall be gathered to the just of all generations.`"
She passed away quietly, from time to eternity, on the 18th of the Eleventh month, 1820.

[.asterism]
'''

ELIZABETH SYBILLA FRY, wife of William Fry, of Stamford-hill, near London,
was born the 4th of the Seventh month, 1775, and was educated by her parents,
with a conscientious care, in the principles of the church of England.

She was admitted a member of our religious Society in the year 1797,
having previously passed through much conflict of mind,
and found that her peace could only be ensured by walking in that
path of self-denial in which our Christian testimonies are borne.
Remaining under the effect of those contriting impressions
which were felt at this important period,
and yielding to the renewed visitations of Divine love,
she was preserved in a lively concern for her spiritual welfare.

In the year 1813, she first appeared as a minister.
Her communications were generally short, and offered in much humility;
bespeaking a mind clothed with Christian love,
and a warm interest in the well-being of her friends.

Though of a delicate constitution, and liable to sudden and alarming attacks of illness,
she was a remarkable example of diligence in the attendance of our religious meetings;
and she was piously concerned that her conduct in her own
family might harmonize with the profession she was making.
Towards her beloved offspring, she extended the most tender parental care,
manifesting a steady and earnest solicitude for their preservation in that path of simplicity,
into which her own feet had been happily turned.
Her Christian care was also conspicuously evinced on behalf of her servants,
whose welfare, in every respect, she was concerned to promote.

In the course of her last illness, which was of several months`' continuance,
she was favored to feel her mind replenished with Divine love,
and enabled to commit her soul as into the hands
of a faithful Creator in humble reliance on his mercy,
through Christ Jesus our Lord.

The following, found among other valuable memorandums,
made in reference to her declining health, mark the state of her mind.

"`What times for telling us the truth such seasons of sickness are;
but oh! for an abidance under these feelings.
How do I fear for myself, upon my recovery, in returning to the world,
lest I should not keep near enough to that preserving Power,
in true simplicity and humility.
This humility, that seeks not the praise of man.
What a desirable attainment! the chief one to be longed for.
May I more and more press after it,
that I may the more closely follow the great and perfect Pattern of humility.

"`'`Be also ready, for at such an hour as you think not, the Son of man comes.`'
How awful and unexpected was my attack on the 29th of Eleventh month, 1819.
When I left my home in the morning, I was not much more poorly than I often am; and,
in less than an hour, obliged to return, by a seizure, which, I was well aware,
might be uncertain in its consequences.
I felt the awfulness of eternity;
but I was enabled to throw myself entirely at the footstool of mercy and redeeming love;
feeling that I had not the least degree whatever of any thing like merit;
or any thing that I had ever done, that I hoped might have been right in his pure sight,
to trust to; for, that I was truly and altogether an unprofitable servant.
But in his very abundant lovingkindness, He was pleased to lay no burden on me to bear,
not even the weight of the smallest offense.
Thus, then, did I wholly rely upon Him, and commit myself unto Him,
leaving the termination to be as He might see fit.
And let me remember, for my future instruction, how truly then the world,
and the opinion of it, seemed but as dross; and the belief I had, that,
to discharge faithfully my own duty,
in simply attending to every little manifestation of light,
was the way to stand approved in his all-perfect sight,
with which no estimate of the world, or any other consideration, would balance.
How was Divine goodness pleased to break in upon my soul,
when I was endeavoring to wait upon Him for help!
And I was permitted to feel the inestimable privilege
of knowing what that language means,
'`Be still, and know that I am God.`'

"`Oh! the entire unworthiness I feel of any claim to everlasting good;
and I am thankful in being made sensible of it,
and in feeling that it is wholly and alone of the free mercy of a gracious God,
and the redeeming love of a crucified Savior,
whereby I can hope to be made a participator in immortal light, love, and praise.`"

At one time she remarked,
that her sufferings during the preceding evening and night had been indescribable,
in the anticipation of a final separation from her tenderly beloved family,
who were then surrounding her; but having been enabled, in some good degree,
to resign them, and to prostrate herself at the footstool of mercy,
she felt that the trial had been gone through,
and believed that she should not have to pass through similar feelings again.

After an occasion of much suffering, brought on by a very severe attack of her complaint,
she raised her voice, and said, "`Gracious Lord! permit me to thank You,
that You have filled my heart with praises rather than complaints.`"
At another time, being inquired of as to the state of her mind, she remarked,
that it was like a smooth river with nothing in the way, as it had been,
with little exception, during the whole of her illness.
A few days before her death, she expressed to her beloved husband,
that she had nothing to do but to die that the work was done;
and on his asking her whether she had any fresh assurance, she replied, "`No;
for there is no need of it: He has promised me,
that He will never leave nor forsake me.`"

During the last two days of the life of this dear friend, she was unable to articulate:
but appeared at times sensible, until within a few hours of her peaceful close,
which occurred on the 9th of the Third month, 1821.
