== Chapter 7

[.chapter-synopsis]
* Priscilla Gurney
* Thomas Fox
* Margaret Watson
* James Tanson
* Anne Capper

PRISCILLA GURNEY was the youngest daughter of John and Catharine Gurney, of Earlham,
near Norwich, and was born in the Eleventh month, 1785.
Deprived, by death, when very young, of an affectionate and watchful mother,
and left in the midst of much indulgence,
she had many temptations to turn her from the pursuit after Truth.
She was, however, from a child, of a tender conscience; and, as she advanced in years,
delighted in benevolent objects, and in the cultivation of her own mind,
rather than in the gay and fascinating pleasures of the world.
This amiable disposition, no doubt, guarded her in her search for a path to walk in:
and in her progress towards conviction,
it was instructive to observe the conflict maintained in her humble and dedicated mind.
About the twentieth year of her age, under the quickening influence of the Lord`'s Spirit,
she became fully convinced, for herself, of the truth of the principles of Friends;
and being thus led into a narrow, yet peaceful path, was, from that time forward,
enabled, steadfastly and openly, to uphold our various religious testimonies.
Having accepted the all-important truths of the Gospel,
in simplicity and sincerity of heart,
she was strengthened to look unto the Lord Jesus as her Savior:
and during the remainder of her valuable life,
was a bright example of devotedness to his cause, and of a willingness to spend,
and to be spent, for his name`'s sake.

In about the twenty-fifth year of her age, with great diffidence and humility,
she came forth in the ministry: and very assiduous, for several years,
were her public labors, both among the Friends of her own meeting,
and in other places where her lot was cast.
Her preaching was clear and convincing, and being delivered in the love of the Gospel,
and accompanied by the evidence of the Holy Spirit, it was instructive to the hearers.
She was often led to set before them the importance
of yielding to the power of this Heavenly Teacher,
and to turn their attention to the promises of salvation, through faith in Christ,
as our Mediator and Redeemer.
She was deeply impressed with the need of a constant and entire dependence upon God;
and was frequently clothed, both in public and private, with the spirit of supplication,
and enabled vocally to offer prayer unto Him.

The following extracts from some of her letters,
instructively exhibit her concern for her own spiritual advancement.

[.embedded-content-document.letter]
--

1812.--Fifth month, 14.
Most fully do I unite with you in the blessedness of obedience to the Divine will.
In the Christian life we see there is such a variety
of means for the attainment of the same great end,
that it has always appeared to me that we are not sufficient
of ourselves to choose those means which are best for us:
and that, the more we commit our way unto the Lord,
the more we are likely to prosper in that spiritual life, which is life and peace.`'
And I think that the Scriptures authorize us to believe, that the Light, or Holy Spirit,
is all-sufficient to lead us in the way in which we should go;
that it reproves us for every evil thought and word,
and`' that it instructs us in our duties.
And does it not also open our minds to understand the important doctrines of Christianity?
Surely obedience, which is so enforced by Friends,
does not lessen but increase our faith in the redeeming power of Christ.
At those times, when we most endeavor to do right,
have we not sufficient proofs of our great infirmity,
and of the corruptions of human nature, to teach us, that, of ourselves, we are blind,
and poor, and miserable, and naked, until clothed with the righteousness of Christ.

1812.--Fifth month, 24. It is consoling,
under the sense and burden of our manifold infirmities,
to find that others have had the same trials, the same pilgrimage to pass through.
At times, the present state of probation,
and the prospect of what is at the end of the race,
wears a more serious aspect than at others, and seems to come more home to the heart.
And yet,
how much more cause we have to wonder that this should have so little effect upon us,
than that it should impress us awfully.
Oh! how important it is, that we should at all times be found watching;
but how far I am from attaining this desirable state,
no mortal knows but myself:--almost every day proves my unwatchfulness and lack of faith;
this makes me feel the necessity of going on quietly, and professing little; in short,
of showing our faith more by our works than our words.

1816.--First month, 17.
Though the travelers towards Zion often have to walk in the wilderness,
yet it is the appointed way towards the promised land: and though the way is narrow,
and the gate strait, yet it leads to eternal life.
It would be pleasant to escape the wilderness;
but if we were always permitted to partake of the fulness of Divine love,
where would be our walk in faith?

--

In the year 1816, Priscilla Gurney accompanied a relation in a declining state of health,
to the south of France, and spent several months at Nice On her way homewards,
she paid a short but acceptable visit to those who
profess with our Society at and near Congenies.
When thus separated from Friends, and from her near relations in her native land,
to whom she felt very closely united,
her mind was preserved in great watchfulness and care on her own account,
and in a lively concern for others,
as appears by the following extracts from some of her letters and memorandums.

[.embedded-content-document]
--

Lyons, 1816.--Tenth month, 31. Our separation from the church,
as well as from our various natural ties, is no light matter.
It is often the secret prayer of my heart,
that this separation may lead us to a nearer union with, and more undivided love,
towards Him who is the Head of the Church.
For myself, I have felt it like a call, separated from every outward dependence and help,
to examine how far we really are in the faith--how
far we are so established in a degree of that faith,
which will really stand amidst all the circumstances of life.
Under an almost inexpressible sense of my own poverty and nothingness in every way,
which I think were never more forcibly brought home to me, than on this journey,
I do not know that I ever felt the consoling and the unsearchable
riches which are in and through Christ,
more than I have done at times in the secret of my heart:
this has sustained me through many pains and many discouragements.

Nice, 1816.--Twelfth month.
It is no easy, no light work,
to keep a conscience void of offense towards God and towards man.
I believe the first is what we should continually aim at, and then the next must follow.
I can say, with truth,
that the experience of this journey has not weaned my heart from friends,
or lessened my value for that holy, actuating, and living principle which, I believe,
is the ground-work of our profession, if not as much as it ought to be of our practice.
On the contrary, I long for its prevalence in the world,
which certainly does appear to me (I hope without the spirit
of judgment) enchained and darkened by forms and ceremonies.
But this submission to the Spirit, to its guidance, to its baptisms, to its humiliations,
its teachings, and its sanctifications, we find daily and hourly in the way of the Cross;
and therefore, alas! it is too much of a stumbling-block to many of us.

Nice, 1817.--
First month.
I have felt an earnest desire that you may not be discouraged
in the important duty of attending meetings.
It appears to me most desirable,
that we should ever bear in mind for what we go to meeting; not to seek man,
nor the help of man; but to seek the Lord, and the help of the Lord.
And I can truly say, I am increasingly persuaded of the truth of these words,
"`The Lord is good to those that wait for Him, to the soul that seeks Him.`"
How does every fresh experience of life make me desire, for those in early life,
that they may remember their Creator in the days of their youth:
I feel so very sure that they will never have cause
to regret any sacrifice made in his service,
or for his sake.

Nice, 1817.
--Second month, 2.
Oh! how I long to be more willing to submit to that
nothingness which it is often my allotment in life to feel;
but to be really brought down, to be really sensible that we are, of ourselves, naked,
blind, etc., I believe one of the hardest lessons to human nature to learn.
O Lord, teach us to become as little children, more humble, more dependent upon You.
Enable us to come unto You, that in your beloved Son we may be made rich,
and that we may be clothed with the raiment of his righteousness.

--

In private life,
the conduct and conversation of this self-denying
follower of Christ were amiable and circumspect.
From a high sense of the value of time, she was a good economist of this sacred trust,
and diligently occupied a considerable portion of it in works of charity and love.
Sensibly alive to the sufferings of the poor and distressed,
she was anxious to administer to their needs, and when she could do no more for them,
to participate in their trials by kindness and sympathy.
This Christian compassion was alike conspicuous towards
those who were suffering from disease,
being ever ready to do what was in her power to mitigate their pains,
and promote their comfort.
She was assiduous in visiting the sick and afflicted.
Her society was pleasant to the mourners in Zion: great was the tenderness of her heart;
and often was she qualified, by the great Physician of souls,
to pour the oil and balm into the wounded spirit.

Her solicitude for the welfare of the youth among us, and especially of the children,
was conspicuous; much of her time being devoted to promoting their religious edification,
and especially their being made intimately acquainted with the truths of Holy Scripture.

Soon after her return from Ireland, where she had paid a general and acceptable visit,
in the spring of 1818, in company with her beloved friend, Anna Forster;
the anxiety of her friends was painfully awakened on account of her health,
which was perceptibly undermined.
After having passed some months on the southern shore of the Isle of Wight, she appeared,
for a time, considerably revived, and returned to her home in the Fourth month, 1820.
There, however, she soon became much debilitated,
and wishing for the refreshment of sea air, removed, in the Eighth month,
to the house of her brother-in-law, T. F. Buxton, at Cromer,
where she continued until her death.

The reader may have already observed,
that Priscilla Gurney possessed the talent of describing, with simplicity and ease,
her religious feelings, when writing to her absent friends.
The following extracts from some of her letters, written near the close of life,
very instructively describe the humility and liveliness
of spirit which continued to prevail.

[.embedded-content-document.letter]
--

1820+++.+++ --Sixth month, 30. The future is entirely in obscurity to me,
nor do I wish to penetrate it; but rather confine my views to the present,
seeking day-by day for the gift (for I am sure it
is nothing of our own) of a meek and quiet spirit,
which can enable us to receive our daily bread with thankfulness and contentment.
I am thankful to say, I am able, very much, to leave the past.
I have sometimes felt that if I had had more faith, more child-like obedience,
my situation might in some things have been different, and my life more fruitful;
but we cannot judge ourselves, '`There is one that judges.`'
Nothing I have found availingly consoling in illness, and the prospect of death,
but looking to that mercy and redemption which covers our transgressions,
and forgives our sins.

Tenth month.
Oh! that I could be always humbly and reverently thankful,
that our dear Lord and Master has kept me in some degree of submission to his will,
and in some degree of that perfect peace, which we can only feel when the soul,
and all belonging to us, is stayed on Him; that he has sometimes given me a glimpse,
at least, of his salvation,
and of that eternal rest which is prepared for the children of God:
but in these things I have nothing to boast of I do not
often feel much brightness or elevation of soul;
but this, I am sure, I have no right to expect.
That my weak, frail, and fearful frame should be preserved in quietness, trust;
and composure, through all that may yet await me in this pilgrimage,
is my earnest desire, and all that I can venture to ask for myself.

Eleventh month, 20. Deeply sensible as I am of my shortcomings,
I have had some comforting assurance of the unsearchable riches of Christ,
as our Redeemer from sin and from death.
In the prospect of the uncertainty of life.
and the probability of a nearness to death, I have, I believe,
known a little what it is to cast all our burdens on Him who has suffered for us;
and have had some glimpse, at least,
of that only state of preparation for a heavenly and eternal state,
the being washed white in the blood of the Lamb.
A child-like submission, waiting in a quiet spirit, is devoutly to be wished for.
Many and great as have been the discouragements which I have had to pass through,
from within and from without,
I can yet bear testimony to the tender mercy and all-sufficiency of that power, who,
when He sees fit, can make use of the most feeble instruments in his service.
I can hardly do otherwise, than encourage others to be faithful,
keeping a single eye to our Lord, watching against imaginations,
and the delusions of our own framing, or of our spiritual enemy.

Twelfth month, 29. My experience has long been,
that of walking through the valley to which I see not the end,
yet a quiet hope generally prevails, that I shall be upheld through it,
that it may be the passage to more of the glorious liberty of the children of God,
even here; but should it prove "`the valley of the shadow of death,`" still, I believe,
there is cause for faith and confidence, that the good Shepherd will be with me,
that his rod and his staff will comfort me.
I cannot but hope, that this wilderness journey, and my many low estates,
will be blessed, in more effectually shaking all self-dependence,
and in leading me to place my trust, more simply and more faithfully in the Savior,
as our only hope of glory.

--

The disease of our departed friend, which was consumption,
made a constant yet gradual progress; the more gradual, probably,
on account of the great quietness of mind, which, in the midst of continued suffering,
she was happily enabled to preserve.
Her patience and submission, during this time of trial, were exemplary,
and apparently uninterrupted, and she was strengthened to cast all her care upon God.
A large proportion of her time was passed in solemn silence;
and she desired that Friends might be informed, that "`although, during her illness,
she had been so much absent from them,
she had never more strongly felt the power of that principle in which they believe;
for she found that outward administrations and words, were not that which sustained her;
but the secret operation of grace in her own mind,
that inward power which really subdues self love.

She was often, during her illness,
brought into sweet unity of Spirit with individuals not of our Society;
and while she felt closely bound to the members of our religious body, love towards all,
was, in a remarkable degree, the clothing of her spirit; and earnestly did she desire,
that this heavenly treasure might be more generally sought after and possessed,
that it might increase and abound among the professed followers of Jesus.
"`In extreme weakness,`" she observed, "`we find disappointment in all human things;
but love does not disappoint, that is better than all.`"
At another time she observed: "`We do not live by gifts,
and I am thankful that my ministry is so much taken from me,
to show me how little the life of religion in my soul depends upon it,
and also how entirely the work is out of myself.`"
Sometimes, however, she spoke concisely, both in testimony and prayer,
with great life and sweetness.

For the youth among us she continued to feel a lively concern.
"`I wish it to be communicated to them,`" she said,
"`how grateful I feel for the kindness with which they have treated me.
The word of encouragement is due from me,
to such among them as are seeking the pearl of great price.
I fear, however, that with many of our young men, religion is too secondary an object.
My desire for them is,
that they may seek first the kingdom of God and his righteousness.`"

One of the subjects which frequently occupied her mind, during her illness,
was the dissemination, among all nations,
of the knowledge of the great truths of Christian redemption;
and she was fervent in her desires,
that friends might be animated to continue to take
their own part in this great and interesting work.
Another subject which dwelt weightily with her, even until near the close of life,
was the slave-trade.
Her own sufferings, she used to say,
reminded her of the sufferings of the afflicted Africans,
and deeply did she feel the moral guilt of the oppressors.
On one occasion, she emphatically observed:
"`I believe the Gospel will never spread largely in the world,
until that dreadful evil be done away.`"

In her life, and in her death, Christ was precious unto her; while,
in the purifying influence of his Spirit, she diligently sought a preparation for heaven.
Her hope of acceptance with the Father of mercies, was founded on the settled conviction,
that Christ died for her; and although, she said,
she was not often favored with bright apprehensions of approaching glory,
she was enabled thankfully to acknowledge, that respecting her future state,
all fear was taken from her.

Thus trusting, and thus patiently waiting the Lord`'s appointed time,
she peacefully expired, on the 25th of the Third month, 1821.

[.asterism]
'''

THOMAS FOX, of Wellington, in Somersetshire,
was a friend much esteemed for the soundness of his judgment,
and the religious consistency of his conduct.
He had a large family, and was, for many years, diligently engaged in business,
conducting an extensive woollen manufactory, with reputation and integrity.
At the same time, he was conscientiously concerned in the education of his children,
by guarding them from the evils which abound in the world,
and by turning their attention, from early life,
to the monitions of Divine grace in the secret of their own hearts,
to act in conformity with our high profession.
He was for many years in the station of an elder,
which office he filled with acceptance to his friends.

He had been long in a declining state of health; but in the early part of the year 1821,
became much more enfeebled; and on the 15th of the Second month, he remarked,
"`My situation is, and must be considered, one of danger.
I do not wish it otherwise.
My glass is nearly run: but I desire to be preserved in resignation and patience,
until the Almighty may be pleased to say, '`It is enough.`'
I have no oil to spare, if I can only keep the lamp burning;
but I rely on the goodness of a merciful Creator, through the Redeemer,
that my change will be for the better.`"

A few days afterwards he said: "`In the midst of my sufferings,
it is a comfort to look round on my wife and children.
Keep in the littleness, keep in the simplicity, keep in the dependence,
seeking the manna daily.
The Lord will indeed preserve them that are his;
and may he strengthen and support you all through this trial:`" adding,
"`I may now tell you, that notwithstanding all my sufferings,
I would not exchange situations with the greatest potentate.
Everything on earth is nothing, yes, less than nothing, and vanity,
compared with an interest in Christ.
With what I am now permitted to feel, nothing here is worthy to be compared.`"

At another time he remarked:
"`Although I am convinced that we are not saved by our own righteousness,
I believe that numbers miss the mark, by imagining,
that the manner in which their lives are spent, is a matter of indifference;
(alluding to their dependence solely on the atonement of our Savior,
without being careful to maintain good works.) This I consider a very dangerous doctrine,
and that there is no safety but in closely following the Divine Guide,
no other reasonable ground for hope that we shall be favored
to participate in the benefits of the great sacrifice.`"
He further observed: "`It is an unspeakable consolation to me to reflect,
that die when I may, I shall die in peace and love with all mankind.
I have no malice nor dislike to any; and those who have endeavored to injure me,
I heartily forgive.
I wish to be affectionately remembered to our servants and work-people;
particularly to the foremen, and to those who conduct themselves well.
Unknown and unrevealed as are the purposes of Divine Wisdom respecting me,
I desire the prayers of all my dear children and family, as they may be enabled,
that I may be preserved in resignation and patience to the end;
and that I may be prepared to render up my accounts with joy,
through the powerful mediation of our Lord and Savior Jesus Christ.`"

Having requested to see his servants,
after a short pause he addressed them in a very affectionate manner; observing,
that the more Christian communities kept to Christian principles,
the more interested would their members feel in each others`' welfare;
that masters and servants might be helpful to each other; that not only were masters,
at times, qualified to administer counsel to their servants,
but likewise servants to their masters.
He charged them, to receive it from him, as a dying legacy, that real, vital religion,
the religion of the heart, is the most acceptable to the Almighty; and observed,
that on our pillows we may sometimes receive more benefit,
than when engaged in the strictest observance of any formal, religious ceremonies.
He said, that he had often felt for those in their stations,
apprehending they had much to endure from the caprice of their employers; but that,
when they bore provocation patiently,
he believed it was well-pleasing in the Divine sight: that if, at any time,
he had hurt their feelings, which he supposed he must have done,
he entreated their forgiveness, as he heartily forgave all those who had injured him:
with more of an instructive import.

On the 11th of the Third month he remarked,
that notwithstanding all his sufferings and privations, he had been sensible,
and still was so, of receiving many favors; that, as all along,
so he still-desired to be preserved from murmuring,
though it was sometimes difficult to be resigned to do and to suffer whatever
might be necessary for the entire reduction of all that was to be reduced.
He had once or twice thought his close was very near;
and perhaps he had been too much rejoiced at it, and thereby sustained loss.
He loved his wife, he loved his children, he loved his friends;
but the joys and comforts on which he expected to enter, were very great.

He continued gradually to decline, until the 29th of the Fourth month, 1821, when,
at the age of seventy-three, he was released from all his sufferings.

[.asterism]
'''

MARGARET WATSON was born in the year 1767.
Her parents, John and Abigail Wright, of Balinaclay, in the county of.
Wexford, in Ireland, endeavored to bring up their children in the fear of the Lord.
Through his blessing, this religious care was the means of preserving her,
in good degree, from the follies incident to youth.
She devoted her time, with diligence, to domestic duties,
assisting her mother in the care of a large family.
When about twenty-six years of age, she was married to William Watson, of Dublin,
to whom she proved an affectionate and true help-meet,
taking her share of the burden of providing for their young family.
In the year 1801, he was taken from her by death, after an illness of only ten days.
This privation she deeply felt; and though much care and anxiety now devolved upon her,
especially in the management of a manufacturing business, and a shop;
yet the same good Hand which had preserved her in early life,
was mercifully extended in more advanced years,
so that she was enabled to fulfill her engagements,
to obtain a sufficiency for her offspring, and to make a provision,
from which she was supported in a lengthened illness.

In the winter of the year 1803, she was attacked by a rheumatic complaint,
during the early part of which she suffered much pain.
Every succeeding winter the disorder increased; so that, in 1810,
she judged it most prudent to retire from business.
Various means of relief were tried: these were unavailing; but she was made willing,
in patience, to submit to the dispensations of the Almighty, who had seen fit,
in perfect wisdom, thus to permit her to be afflicted and proved.
In 1815, she removed with her family to Rathangan, being then entirely unable to walk.

For the last two years of her life, she could not raise her hand to her head,
and was much tried with lack of rest, weariness, and many other painful privations.
Her health began visibly to decline, and there were evident symptoms of mortification.
This did not make much progress until the night of the 16th of the Second month, 1821,
when excruciating pain seized her legs and feet, which continued for several hours:
during these extreme sufferings, her petition was for patience.
Towards morning the violence of the pain abated;
but it returned on the night of the 18th, when she said: "`Some time ago,
in the former part of my illness, I thought,
if I were favored with peace and quietness to the end,
it would be as much assurance as I could look for or desire;
but now my poor mind looks for something more.`"
It was indeed evident, that she was earnestly engaged for the salvation of her soul;
and through much exercise and close searchings of heart,
she became sensible of a reconciliation with God, expressing, at different times,
a belief, that her long and painful illness had been blessed to her.

At one time, in reply to a kind inquiry from one of her attendants, she said:
"`I lack nothing; my gracious Father has taken away all my pain:
something must come to reduce the poor body.`"
And shortly after spoke thus: "`To you, O my gracious God, I commit my soul and spirit.
If I should never again open my eyes in this world, I know you can do all things for me.`"
The next morning she mentioned to her sister,
that in the night she had thought herself going,
and had wondered that she felt so peaceful and easy,
not having any of that fear or dread, which she supposed persons had at such a time.

Her gratitude for any little service was great,
and she would thus express how sensibly she felt it;
"`Oh! such attendance as I have --I must never forget to thank the Giver,
who gives me every good thing.`"
She was often earnestly engaged on behalf of her children,
that they might live in the fear of the Lord and serve Him: at one time saying,
they had a tedious attendance on her, but she hoped it had tended to refine them;
and that there was no pleasure or gratification in the world worth living for.
Addressing one of them thus: "`I desire with all my strength,
that you and your sister may live in the fear of the Lord, that you may live in love.
You have many friends; but remember the natural tie which should bind you one to another.
My dear, you have been always very tender and careful of me,
I hope the Lord will reward you: strive to live more in his fear.`"
At another time, in addressing the same child, she remarked:
"`This is a close trial to you, and I pray my gracious heavenly Father,
that He will give you strength to bear it.
He does not allow more privations to attend, than He gives us strength to bear.`"

On one occasion, being very weak and low,
she petitioned the Almighty for patience to hold out to the end, saying:
"`I expect to have sharp sufferings yet:
many good people have gone through much suffering towards the close,
and why should not I? I do not ask that my sufferings may be lessened.
Let not your hand spare, nor your eye pity,
until everything is removed that should be taken away.
My Lord and Savior suffered much.
Oh! gracious Father, receive my spirit.`"

At one time she desired her daughter to sit down by her, and said to her:
"`I thought it would be a comfort to you to hear of the goodness of the Almighty to me.
When I awoke out of that quiet sleep this morning there
was such a sweetness on my mind as I cannot describe,
I do not want to boast; but the Almighty himself has comforted me,
and given me assurance; the time is near at hand, when I shall be at my everlasting rest.
I have that within me, that will bear me up to the end.`"
And again; "`The Rock of Ages is underneath to sustain me:
the Lord is my shield and my buckler, and then, who can make me afraid?
Inquiry being made relative to her bodily sufferings, she sweetly remarked:
"`I would rather always be meditating on my blessed Savior.`"

Being once asked if she were in pain, she replied: "`Yes; but I am supported.
I do hope to be received into everlasting rest; and oh,
that my dear children may be enabled to meet me there, where is neither sin nor sorrow.`"
The time of her release appeared now so near,
and her mind so sweetly clothed with peace and love,
that it seemed as if the adversary were cast out, and had no more power to assail her;
but it pleased Infinite Wisdom again to permit her mind to be buffeted,
for a fresh trial of her faith and constancy.

On the forenoon of the day of her decease, she was, for a considerable time,
engaged in solemn supplication; humbly petitioning the Lord,
that if any stain yet remained, it might be done away.
She felt it an awful thing, to be so near having the soul separated from the body;
but she expressed her hope of salvation through the Lord Jesus, and her belief,
that the grave would have no victory over her.

About three in the afternoon her speech became suddenly affected,
extreme pain succeeded for three or four hours.
During this time her petitions were addressed to the Throne of Grace for support,
and she requested her friends to pray for her.
Her last words, which could be distinctly understood, were, "`'`Gracious Father,
grant patience for the few remaining moments.`"
She was favored with ease for some time before her death, and passed very quietly away,
on the 1st of the Fourth month, 1821.

[.asterism]
'''

JAMES TANSON, of Darlington, was born there, in the year 1784,
and died on the 10th of the Sixth month, 1821, at the age of thirty-seven.
Some particulars of his early life and religious experience are described by himself,
in a written communication to his children.
They contain much that is instructive to the young; and are now introduced,
with a warm desire that they may awaken profitable
reflections on the importance of a religious life,
at that critical period to which they more particularly refer.
The following extracts are made from the paper already alluded to.

[.embedded-content-document.paper]
--

I have not the least doubt,
that the Spirit of the Almighty began to influence my mind while I was yet very young;
but those propensities to which childhood is so prone, led me away an easy captive.
I do not recollect that my younger years were remarkable
for any thing of a very evil nature;
yet I well remember, I often gave way to wrong dispositions; but not without, at times,
feeling a love for that which was good, and a desire, that if I lived,
I might become a good man.
But the resolutions I from time to time formed for this purpose, were too soon forgotten;
and the gratification of self was what I sought after more than almost any other thing.

As I grew up,
an inclination for drawing and reading drew me from my more childish amusements.
Entomology was, I think, my first pursuit;
but botany and ornithology held me longest engaged.
The excess of ardor with which I at times pursued these studies,
almost precluded the possibility of attending seriously to anything else;
and the most important of all pursuits, that which affects our eternal wellbeing, was,
alas! often entirely neglected.
I may confess,
that I could not behold the beauty and harmony of the creation without admiration;
but then I failed in giving God the glory.
And as I went on from year to year, without remembering my Creator,
I became less and less disposed for any thing of a serious or religious nature; and,
about the eighteenth or nineteenth year of my age,
my inclination for vain pleasures became great; and I have cause for thankfulness,
that I was so situated as not to have an easy opportunity of indulging it.
Yet, notwithstanding my heart was so much disposed for gaiety and carelessness, it was,
at times, brought into a state of heaviness and disquietude,
when all my pleasant pictures seemed to be covered with gloominess,
and my customary amusements lost their relish.
At those seasons, my mode of life appeared to me a very unprofitable one,
and I at times resolved to endeavor to improve it.
I had no satisfaction in looking back, and no hope or comfort in looking forward.

Thus I went on, yet not without getting more sober ideas of things,
and more stability of mind, until the beginning of the year 1810,
being then about twenty-six years of age;
when I was more fully given to see the necessity of a closer
attention to things which appertained to eternal life.
I was now induced to ponder and look around for something
more true and stable than any thing I had hitherto known.
And although I was, at times,
made sensible there was a way by which I might attain
more pure and lasting peace of mind,
yet this way seemed too narrow for me to walk in.
At length my eyes were more fully opened, and it was shown me,
that I had been hitherto floating as it were in a polluted stream,
and had thereby become contaminated with its impurities;
so that the rays of hope and consolation, which shone on the head of the good man,
enlightened not my path; and I saw, that before I could obtain rest to my soul,
I must be thoroughly washed and cleansed.

It was now that the world and its allurements seemed lighter than air and vanity;
it was now that I looked to the Eternal Fountain of pure and living water,
sincerely desiring to be made willing to have the many impurities,
with which I felt myself to be burdened, removed; and now I wished to believe,
that the precious blood, which was shed for me and all mankind, would,
if I submitted to Divine operation, take away all my stains.
But faith was to me a stranger, and I had to inquire, What is it?
until by degrees, as I continued to be truly and humbly desirous to be taught,
the way in which I should go, and the means by which I should be purified,
were more clearly pointed out.
And oh, that I may, from time to time,
be favored with strength to advance in the path of righteousness,
as well as to bear those washings and baptisms to which it is necessary I should submit,
before I come to a state of acceptance with the Almighty
Source of purity and perfection.

--

James Ianson having now entered upon that path which leads to blessedness and peace,
it became his first concern to walk in humility and fear before God;
to seek to have his whole life regulated by the power of Divine grace,
and to be redeemed from the spirit of this world.
It is to him, with the aid of another friend,
that we are indebted for the little instructive volume, entitled,
"`The Guide to true Peace.`"
Having yielded obedience to the inward manifestation of Truth, he became qualified,
from his own experience, thus to describe the work of religion:
"`Religion is no enemy to innocent cheerfulness,
and forbids not the enjoyment of any reasonable pleasure or gratification.
It bestows upon us the highest privilege of which human nature is capable,
even that of having communion with our Maker.
What greater consolation is it possible to enjoy, than to be able,
in all our difficulties, to place our entire dependence upon Him; relying,
in full confidence, on his goodness and mercy; feeling an assurance that,
however we may be tried, He regards us with compassion, knows all our needs,
and is ever willing to relieve them.`"

The Friend whose religious course we are now reviewing, was a man of an unassuming,
retiring character; amiable in private life, and of unspotted integrity.
His countenance often portrayed a degree of sweetness and pious settlement of mind,
which was instructive and endearing; especially to the young,
to whom he was uniformly kind, and whom he anxiously endeavored to interest and improve.
He was diligently and conscientiously concerned to
act consistently with our Christian profession;
and, for a few years before his death, he filled, with acceptance,
the office of an elder.

He was not of a strong constitution, and for several years suffered much from poor health.
In the course of his last illness, he was favored with much sweetness and patience,
and with resignation to whatever Infinite Wisdom might see meet to dispense to him;
often expressing a desire to be kept sufficiently patient and quiet,
under whatever he might have to endure, of mental or bodily suffering.
He evinced, on all occasions, great caution in speaking of his religious experience;
and this was increasingly the case during the last few weeks of his life,
being very fearful lest he should describe in words, that which he did not really feel.

On the day of his decease, however,
after being informed that the doctors apprehended that his time would not be long,
he replied, it was rather unexpected intelligence,
the event having been quite hid from him.
After this,
he appeared more at liberty to speak of what he had
had to pass through within the preceding few days.
He observed,
in allusion to his present peaceful state of mind in the prospect of so solemn a change,
that his mental feelings, for many days, had been most distressing.
He seemed to have had no control over the imagination,
which presented the most trying apprehensions:
although he was convinced they were all illusions,
yet he had not ability afforded to turn from them,
or to rest his mind upon the only Source from which comfort and consolation can be administered.
At these trying seasons,
the grand adversary of his soul`'s peace was permitted to buffet and beset him on.
every side, without his having power given to resist.
He added, in the midst of these distressing conflicts,
he had a firm belief they would only be for a season;
for a trial of his faith and confidence,
and perhaps as a means of his further purification.

He also gratefully and reverently acknowledged the
condescending goodness of his Heavenly Father`'s love,
at other times, in visiting and strengthening his poor, tossed mind: these were, indeed,
felt to be seasons of refreshing, as from the presence of the Most High.
He said, he believed all was well with him,
and that he had brightening prospects before him;
humbly hoping he should soon be permitted to join the spirits of the just made perfect,
in celebrating the great and glorious name.
He assured his beloved wife that he felt nothing but peace, sweet peace,
to clothe his mind at that awful period,
accompanied with a full confidence in the promises, mercy, and love of his Redeemer;
and that the love which he felt for his dear relations and friends,
was beyond any thing which language could convey.
He remarked,
how much of late his desire had increased for a closer communion with his Maker;
that he was rather afraid whether he might not have
been endeavoring to do too much in his own strength;
but that his hungering and thirsting had been such,
that every other consideration appeared like dust in the balance.
Worldly matters he felt that he had quite done with:
even his dear wife and children he was strengthened to give up,
and to commit to a kind and compassionate Savior, who, he was well assured, would,
if rightly sought unto, prove an unfailing protector.

He took a tender leave of his dearest relations,
and his strength now seemed greatly exhausted.
His close, which had been for some hours gradually approaching, was calm and peaceful;
his countenance beamed with sweetness: and before his spirit departed,
he appeared to have a foretaste of those transcendent
joys which were about to be revealed.

[.asterism]
'''

ANNE CAPPER.--The life of Anne Capper,
though not distinguished by striking or uncommon circumstances,
but much employed in domestic cares and duties,
afforded an instructive example of pious zeal,
and continued endeavors to occupy diligently with the talent received;
and its close was such as to raise a consoling persuasion in her surviving friends,
and relatives, that her labors of love were accepted by her Lord and Master; and that,
through redeeming mercy, she was about to enter into eternal rest.

She was the daughter of John and Frances Fry, and was born at Melksham in Wiltshire,
in the Eighth month, 1756.
Her parents removed during her childhood to London;
and her mother soon became much indisposed,
so that the care of the family devolved upon her while she was yet in early life.

In the year 1778, she was married to Jasper Capper;
and almost on their setting out in the world,
they had to encounter a series of trials and difficulties,
chiefly occasioned by straitened circumstances.
This obliged her to use extraordinary exertions,
in assisting her husband to provide for their family.
They were careful to observe strict frugality,
and to accommodate their manner of living to their circumstances;
and their honest endeavors were abundantly blessed.
They had a large family,
and were conscientiously concerned to bring them
up in the simplicity of our religious profession,
and to guard them from the evils which abound in the world;
thus endeavoring to preserve them from everything
that would tend to diminish religious sensibility.
Active benevolence was a distinguishing feature in the character of this dear friend;
and she was ever ready to form and to execute plans for the relief of the distressed,
in which she was greatly assisted by the influence
she had acquired among persons of various classes,
and different denominations in religion, in consequence of that sincerity of mind,
that cheerful, frank, and open disposition, by which she was distinguished,
and for which she was much beloved.

In the year 1819, her husband, whose health had been gradually declining,
was taken from her, and in so humble and sweet a state of mind,
as to render the retrospect of the event, so far as the immortal part was concerned,
consoling.
Her own health had long been in a very weak state;
and towards the middle of the Sixth month, 1821, her illness increased.
At one time she remarked to one of her daughters, "`I hope I am not deceiving myself,
but I have always had a great dread of the parting moment,
and now that is entirely removed.`"
A few days afterwards, she said,
"`The abounding consolation is beyond what I can describe:
all in great simplicity and nothingness, not any thing in which self can be exalted.
I trust that my transgressions and my sins are blotted out.`"

Although thus favored with the incomes of her heavenly Master`'s love,
she had to pass through seasons of deep spiritual poverty,
in which the separation of soul and body appeared very awful;
and she saw distinctly that she stood in absolute need of an interest in Jesus,
"`the advocate with the Father.`"
This made her pray fervently for yet deeper and stronger
evidence that her sins were forgiven her,
for his name`'s sake;
and that her spirit might be sufficiently purified
to be admitted into the presence of her Lord.
She passed several weeks under great bodily suffering,
continuing to exhibit resignation to the Divine will; saying once,
when she thought herself near the end, "`I do not ask for an easy passage,
only that His will may be done.`"
At another time she said,
"`I have considered myself greatly favored by the
recollection that death is the gate of life;
and a humble hope has been raised, that the conflicts of time may end in eternal rest,
through the unmerited mercy of the Redeemer;
which has brought my mind into an anxious desire for all my children, far distant, near,
and present, that they may experience the fulness of eternal joy.`"

On the 2nd of the Ninth month, she remarked to one of her daughters,
"`I hope you endeavor to feel after Christ.
I hope I do not deceive myself, when I think that He will support me through,
little and unworthy as I am.
I am one for whom He made the propitiatory sacrifice; and I think I may say,
I have loved Him.
In Him is mercy and plenteous redemption.`"`' On the following day she appeared to have
been largely favored with the manifestation of Divine love in the secret of her soul;
saying, that the promise to her that morning had been great,
almost too great for her to express, that the close should be in perfect peace.
On the 4th of the Tenth month, in a message to a near relation, she said,
"`Give my love to him, and tell him how empty and vague all things are,
except the life of God in the soul of man.`"
She spoke of her sufferings being prolonged; but added,
she did not wish the change to take place.
one minute before the right time.

At one time, when distressingly ill, her daughter remarked,
how great her sufferings were; she replied, "`But my God is underneath.`"
She often said, while in distress of body, Your will be done.`"
Her strength continued very gradually to decline, and her bodily sufferings, at times,
were great; but her mind was still stayed upon the Almighty.
All anxiety for the future was taken away;
and on one of her sons asking her whether she had then any pain, she answered, "`None,
only weariness.
I should be thankful to be released,
if it pleased my Heavenly Father to break my bands.`"

She was preserved through the few remaining days of her life in the same humble resignation,
full of love to her friends, and grateful for the attention of all about her; and,
on the 19th of the Eleventh month, 1821,
she peacefully expired at her house at Stoke Newington, near London,
at the age of sixty-five, having been a minister for about twenty years.
