== Preface

The following accounts have chiefly been compiled from a
collection of memorials published in the last century under the
direction of the yearly meeting of Friends of Philadelphia.
As the narratives in the preceding pages of [.book-title]#Piety Promoted# principally
relate to persons who lived in Great Britain and Ireland,
it has been thought that some addition respecting individuals in our own country,
would be acceptable in an American edition.
The volume which has furnished the materials for most of them has some prefatory remarks,
which may be appropriately introduced here.

Those who have departed from here in the Lord,
can receive no addition to their happiness by any testimonial of their surviving friends,
however just; yet to the wise in heart,
precious is the memory of the truly pious and upright,
whose humble walking in the fear of God has livingly witnessed
against the appearance of evil in its various transformations;
their conformity in spirit and practice to the holy law of the Lord,
evincing the delight and benefit to be found therein;
for "`Verily there is a reward for the righteous,
verily he is a God that judges in the earth.`"

"`What scene in this life more dignifies humanity;
what school is more profitably instructive, than the deathbed of the righteous,
impressing the understanding with the convincing evidence,
that they have not followed cunningly devised fables, but solid substantial truth;
and that there is a measure of divine light and grace in man,
which if duly minded and obeyed,
is sufficient to preserve through all the vicissitudes in life,
to give him the victory over his spiritual enemies, and in the end over death, hell,
and the grave.`"

It is right therefore, that the remembrance of those should be preserved,
whose lights have so shone before man as to incite
the beholders of their good works to glorify God,
the original and source from whom all good is derived, that though being dead,
the luster of their pious example through life, and on the approach of death,
may continue to display the inviting language, "`Follow us as we have followed Christ.`"

Some of the readers of the following narratives will be
reminded of the sincere piety and virtue of their ancestors,
who through the dangers and difficulties to which they were subjected,
in their removal from their native land, and forming a new settlement in a wilderness,
were happily preserved in a steady attention to their religious duties,
and many of them faithfully engaged in promoting
the cause of truth and righteousness among mankind.
To these, others succeeded, who,
through obedience to the powerful influence of Divine grace,
became alike eminent in their day, and serviceable in the church.

The following collection is affectionately recommended to the descendants of those worthies,
to the readers in general, and particularly to the youth,
who may derive profitable instruction by a serious observation
of the happy effects of an early devotion of the heart to God,
and the inexpressible advantages of embracing the merciful
visitation of that compassionate Savior who died for them,
in order to secure their true comfort in this life,
and enduring felicity in that which is to come.

Though the language and style of these memorials
may not be calculated to please such curious readers,
who, in their estimate of the value of a book,
are too much amused by the display of wit and literary accomplishments in the composition,
to give due attention to the instructive import of an artless account of the
Christian experiences of those who have not been so solicitous for the approbation
of men as to be found humble followers of Christ Jesus the Lord,
their meek and lowly pattern, and omnipotent Redeemer;
yet it is hoped that there are many to whom the contents
of this collection will afford information,
edification, and encouragement in the pursuit of their most substantial interest,
a life of true wisdom, piety, and virtue;
and that the number of such may increase is the design of this publication.
