== Chapter 1

[.chapter-synopsis]
* Susanna Whitrow
* John Simcock
* Eleanor Smith
* John Smith
* Benjamin Jordan
* Elizabeth Small
* Ellis Pugh
* William Haig
* Mary Haig
* Joseph Glaister
* Vincent Caldwell
* Anthony Morris
* James Daniel
* Caleb Pusey
* Hannah Hill
* John Bevan

SUSANNA WHITROW was the daughter of Robert and Joan Whitrow, of Covent Garden,
in the county of Middlesex, England.
Her father does not appear to have been a Friend, and he,
with several other members of the family,
seems to have lived in the corrupt ways and fashions of a world that lies in wickedness,
in opposition to the counsel, and greatly to the grief of Joan Whitrow,
who was a woman of true piety and self-denial,
much concerned for the best welfare of her family,
and one of the people in scorn called Quakers.

Their daughter Susanna was taken sick the 5th of the Third month, 1697,
and lay until the ninth day,
under the judgment and terrors of the Lord for sin and iniquity.
About four o`'clock in the afternoon she broke forth with great earnestness,
crying to the Lord for mercy, "`Lord, are my sins forgiven?
Had not my eyes seen those vanities, my heart had not gone after them:
shall I have no help for my distress?
Strengthen me but to see my desires;`" with other
similar expressions for about three hours,
when the Lord was pleased to hear and answer the desire of her soul.
Having thus obtained mercy for herself,
she fell into a fervent travail of spirit on behalf of her father,
praying after this manner: "`Lord, remember not his offenses, let me bear them,
make his friends to be his enemies, that you may have mercy on him: carry him through,
and let him not perish with the world.
Blessed Lord, hear me, leave me not unsatisfied, but grant my request.
Set his mind on things above; turn him, and he will be turned.
There is no way for him but to watch and pray continually, lest the tempter prevail.`"

Then addressing her mother, she said, "`Oh! my bowed down mother!
Oh, my bowed down and brokenhearted mother!
What have been your sufferings in this family!
Oh, how have you been oppressed with our iniquities!
Ah, how often have you told my father,
the Lord would visit him with sore and grievous judgment
if he did not repent and turn from the evil of his ways!
How often have you said, the Lord would plead your righteous cause with us!
Now the day is come you have so long warned us of; now the Lord is broken in upon us.
Oh, how great have been your care and pains,
which you have taken to bring us into the fear of the Lord!
Oh, you blessed of the Lord! great shall be your reward.
The Lord will give you beauty for ashes,
and the garment of praise for the spirit of heaviness: you are blessed, my mother.`"

Her mother being at that time praising and magnifying the Lord, she said,
"`My blessed mother, now is that vision fulfilled,
which the Lord showed you concerning me, that my soul should bless you,
and your soul should bless the Lord.`"
Then she broke forth into sweet melody, singing praises unto the Lord.
"`Blessed are the poor in spirit.
Lord, I am poor, I am needy, I need your strength continually to withstand the tempter.
O Lord, stand by me, move not from me; for if you go, the tempter will come.
I will hold you fast; you are my Savior; you shall save me from the tempter.
My dear mother, send for that dear friend, who prayed by me the other day.
She is a precious woman; her heart is upright before the Lord; he has showed it me.
I love her. Let her pray by me to the Lord against the tempter.
And send for that servant of the Lord, W. P.;
the Lord will hear the prayers of the faithful; but I have been unfaithful.
Oh, how often have I sinned against my Savior,
whose light in my conscience showed me the way I should walk in!
How often has he knocked at my stony heart, saying,
This is the blessed truth which the Quakers preach,
by which all souls that I have made shall be saved!
Then have I said in my heart, After such a thing and such a thing is accomplished,
I will leave off my life of vanity, and become a new creature.
Oh! I was she that trusted in lying vanities.
I thought I should have long life, and then I did intend to serve the Lord in my old age.
Oh, how I have been against a woman`'s speaking in a meeting!
But now, whether it comes from man, woman, or child, it is precious indeed.
O that I could be with my mother: the Lord is with her:
that I might have a little time longer,
that my dear mother and I might go in the country and walk in a wood together,
that we might seek the Lord until we have found him.
O Lord, my strength fails, I wait upon you, renew my strength:
be pleased to restore me to my former health, then will I wait diligently upon you.
I will sit on the ground, with my head in the dunghill.
I will never lift up my soul to vanity;
my heart shall never go after the sight of my eyes.
My dear mother, pray for me; for whatsoever you ask of the Lord, it shall be given you.

"`My dear mother,
you have often told us of the terrible and dreadful day of the Lord God that is at hand.
O, it will be a dreadful day to the wicked of all sorts, the Lord has showed it me.
Woe,--woe, to the children of scoffers! for as it was in Elisha`'s day,
so shall it be in this the day of the Lord`'s power--the bears out of the wood shall devour them.`"
And trembling she said, "`I feel your terrible power, O God; strike dread, terror,
and astonishment in the hearts of your enemies, in all the workers of iniquity,
who make a derision of your people,
and take pleasure in the abominable ways which you abhor.
O my mother, I have heard God`'s thundering power rattle upon the heads of his enemies.
A woe will be to the children of pride in that day;
and woe will be to the blind guides that wear the long robes,
the false teachers of this nation.
Did not our blessed Lord say, if the blind lead the blind,
both should fall into the ditch?
Ah, Lord! how should it be otherwise?
for they hate the light, and count it an insufficient thing.
Did not our blessed Savior say, believe in light,
that you may be the children of the light?
and he bade them all watch and pray, lest they enter into temptation.
And how could they watch without the light?
for they could not see the tempter when he came in the dark.
Ah, that scripture is fulfilled upon this people, That darkness should cover the earth,
and gross darkness the people;
and then night should be unto them that they should not have visions,
and the day shall be dark that they shall not divine.
And this was Egypt`'s darkness.
Ah! but the children of Israel had light in the land of Goshen.
Extolled be your name, you God of power.
If you will be pleased to restore me to my former strength,
then I will speak of your wonderful power; yes,
my voice shall be as the sound of a trumpet, which shall convert sinners unto you; yes,
I will sit in the dust, and cover my head with ashes,
and put on sackcloth within and without.`"

Taking something to drink, she lay still a little time, and with joy in her heart,
made sweet melody to the Lord, but did not utter any words;
then she broke forth again in praising and magnifying his great works.

"`O that house of abominations, that play-house,
where they commit their abominable deeds, God will destroy it.`"
Her mother said, "`What house, my dear child?`"
She answered, "`That church, as they call it in Covent Garden,
the members thereof are proud persons, and covetous, and deceitful, liars, and drunkards.
Ah! my blessed Savior said, We should know them by their fruits.
O, these were my fruits which I brought forth when I was a hearer at that church,
pride and disobedience to my parents.
How often have I adorned myself as fine in their fashions
as I could make me! yet they have looked upon me with scorn,
and despised my dress, and said to me,
How you have dressed yourself! you are not at all in the mode!
Then I came home, and have gone immediately into my chamber, locked the door,
and altered all my laces; and so I have gone to their worship in their mode,
and then I have pleased them.
Pray, my mother, call my father; I have something to say to him.
I desire my body may not be laid in that abominable place,
but among the people of the Lord called Quakers.
Now I am a true Quaker, now I tremble before the Lord and his holiness.
Come, you holy prophets, who were quakers and tremblers at the word of the Lord; come,
Moses and Jeremiah; come, holy Habakkuk, now I am one with you: now my heart drops,
because of the Lord, and the greatness of his majesty.
O my Lord, yes, my Lord, for so I can call you, because you rule in me,
and my soul is subject to you.
But they have many lords and many gods; they have gods of silver and gods of gold,
the work of their own hands.
O my heavenly Father, I wait upon you; renew my strength, holy Father:
be pleased to restore me to my former health; then I will wait diligently upon you,
I will sit on the ground with my head in the dunghill,
my heart shall never go after the sight of my eyes.
My dear mother, pray for me; for whatsoever you ask of the Lord, it shall be given you.
The reason why I desire to live is,
because I have so greatly dishonored the Lord in my former life,
and now I would live the rest of my time to his praise;
for I shall be as one raised from the dead, to declare his wonders: but what shall I say?
Though one should rise from the dead, they will not believe.`"

She was exceedingly filled with the indignation of the Lord
against their idle practices and their abominable ways,
but her expressions were not taken in writing.
These words the maid-servant wrote down as she spoke them.
She cried out aloud, and said, "`Father, these priests deceive the people;
they study all the week what to say when Sunday +++[+++so called]
comes; but the day of the Lord is coming,
in which he will confound all their study and all their wisdom,
and in that day they shall not be heard for their much speaking;
they are physicians of no value.

"`My dear mother, I fear I shall not have a place so near the Lord as my soul desires;
for I am sensible, there are degrees of glory,
and as the creature acts here for the Lord, so shall its reward be hereafter.
I have done nothing for the Lord, but he has done all for me; therefore I desire to live,
that I might live a holy and righteous life, that my citizenship might be in heaven,
though my body be here on the earth, that I might invite all, as David did,
to taste and see how good the Lord is.
They have tasted of their perishing life of vanities, yes they have drank a full cup,
their measure is running over; but they never tasted the joys,
the unspeakable ravishments of soul that attend the humble, holy life of Jesus.
Oh! if they had ever tasted the least mite thereof,
they would bid adieu to all their life of vanity.
Ah, they would not dare to spend their precious time in adorning themselves like Jezebel,
patching and painting, and curling their monstrous heads.
The Christian life is another thing, they must not give themselves liberty
to think their own thoughts, much less to act such abominations as these.`"

After she had lain awhile, praising and magnifying the Lord,
she spoke very deep and weighty things, which are not set down,
concerning the wise virgins and their lamps burning,
and exhorting all to keep very diligently upon their watch; "`for,`" said she,
"`the Lord will come as a thief in the night, and in a day when he is not looked for;
therefore watch and pray continually; here the tempter cannot enter.
This is the way my Savior spoke of when he said, you must take up your daily cross;
this is that flaming sword you must pass through, mark that, you must pass through it,
before you can come to the tree of life.
This is the cup my Savior asked if you could drink of,
and this was that baptism he asked if you could be baptized with.
Come all you that call yourselves Christians, what of the life of holy Jesus is in you?
who was a man of sorrows.
You light and airy ones, you wild and careless ones,
you that are lovers of pleasure more than of God,
you workers of iniquity who are always crying Lord, Lord,
but do not the tlings that I say, this shall be your dreadful doom, that you are sayers,
but not doers: you workers of iniquity,
that think you can never have enough of the pride of life, the lust of the flesh,
and the lust of the eye, which is not of my heavenly Father,
and so you are of your father the devil, for his servants you are whom you obey.`"
At another time she said, "`I have heard them say,
that my mother is so grounded in her religion, that it is impossible ever to turn her.
My mother is grounded indeed, she is established upon the rock that shall never be moved:
my mother shall never be moved, her name is written in heaven, yes,
in the Lamb`'s book of life it is sealed: the Lord has told me so, and bid me tell her,
There should none be able to pluck her out of his hand.
Come, my blessed mother, I have something to say to you--you are Mary,
you have chosen that good part which shall never be taken from you;
you shall sit continually at the feet of your Lord, aye, this is my mother`'s portion: O,
what portion is like this?
this is more than to sit on the thrones of princes.

"`'`Be holy as I the Lord your God am holy:`' this they say is impossible.
O, would the holy, just and true Lord command that which is impossible?
In this they count the Lord a hard master.
But what can my soul say of your power?
When I sought you but could not find you, I knocked hard but none would open,
for my sins stood like mountains, that I could not come near you.
I would eagerly have prayed, but could not.
I lay several days and nights prostrate before you, struggling for life, but
could find none; and I said, there is no mercy for me.
Then said I, I will never leave you; if I perish, I will perish here.
I will never cease crying unto you.
Then I heard a voice say, Jacob wrestled all night before he obtained the blessing.
O then your word was strength to my soul;
then my stony heart was broken to pieces before the Lord,
then the spirit of prayer and supplication was poured into my soul;
and now I can sing as David did of mercy and judgment.
Unto you, O Lord, will I sing: with a rent heart, and my mouth in the dust,
will I sing praises unto you, my blessed Savior.`"

For several days she had a very great conflict in soul and spirit concerning the tempter,
and strong were her cries to the Lord for strength to overcome the enemy.
She was so deeply engaged in the holy war of the Lord,
that she would not allow her head to be removed from her pillow, but said,
it must be as it were nailed there till she had overcome the tempter.
She said, "`I would not permit a thought to wander.
If I move I shall be drawn off my watch, and then the tempter will prevail.`"
Then she had a vision, and as it were the appearance of an angel,
giving us the full description thereof, which we have forgotten,
only that it was arrayed in white:
she had also a vision of the tempter which she said stood before her bound in chains.
Then she said, "`It is finished, I have overcome, my Savior has bound him.`"
She broke forth into blessing and praising and magnifying the Lord,
that it is beyond the power of language to give a relation thereof.
For many days and nights together she would hardly slumber,
but would waken herself to sing praises to the Lord,
and to declare of his wondrous works that he had done for her soul.

Some friends came into the room, but she saw them not:
and after many sweet and precious words, she said, "`Don`'t you feast, but fast and pray,
and be contented with mean things.
O what matter for fine houses or silken apparel!
Remember him who sat on the ground, and wore a garment without a seam, our blessed,
holy Lord, who went up to the mountain to pray,
and withdrew into gardens and desolate places of the earth;
my soul has fellowship with him.
O my dear mother, if it please our dear and heavenly Father to spare me this time,
we will get us into the country to some remote place, among the woods,
where none can hear us; then shall our cries pierce through the heavens,
and shall make the earth to ring, and the birds shall hear the echo thereof.
There my blessed mother, will we sing praises with rent hearts,
and our mouths in the dust, to the one, holy Lord.
O you glorious One, you have overcome my heart, you have ravished my soul.
You pure, holy One, what shall I say of you,
or what shall I render to you for your lovingkindness to me?
My heart is overcome with your love, praises be unto you for your lovingkindness to me.
How shall I do to set forth your goodness, for my heart drops before you?
Lord, if it be your holy pleasure to take me out of this life, then let me have,
I beseech you, one whole day, that my tongue may never cease praising you.`"
And the Lord answered her request.

All that day she was wonderfully filled with the sweet solace of the heavenly life,
singing praises and hallelujahs to the Lord, and spoke very much concerning the Lamb;
and of his followers,
who had washed their robes and made them white in the blood of the Lamb.
Towards the evening, while the power of the Lord was upon her,
there came in two persons to see her, when she uttered many precious, heavenly words,
and in great weightiness of spirit said, "`O Israel, what has your God done for you?`"
Then taking up a lamentation, said, "`What shall we do for the daughters of Jerusalem,
who are haughty, and go with outstretched necks and wanton eyes?`"

After several days lying in the sweet solace and heavenly life
of the Lord (in which time she uttered many heavenly things,
which were not taken in writing) she expressed these words,
"`O you beloved of my soul! what shall I say of you?
for you are too wonderful for me: praises be unto you.
Come all you holy prophets, praise the Lord with me: praise the Lord, O my soul,
upon the loud-sounding instrument; you glorious angels, that excel in glory,
sing praises to him that sits upon the throne.
O how am I overcome! you stones in the street why
rise you not up to praise him that lives forever?
O you light, praise the Lord; and you darkness,
praise and exalt him above all things: you sun and moon,
you stars in the firmament of his power, magnify the Lord above all forever.
All you fishes in the sea, why do you not come forth to praise the Lord, the mighty God,
who gives you breath and being?
I will praise you while I have any breath: praise the Lord, O my soul,
sing praises to the God of my salvation: my holy One, you have overcome my heart,
you have ravished my soul.
My dear mother, I shall be as a new born babe, I shall be very simple, but bear with me,
for the Lord is with me.
My dear mother, I must lay down this body,
the Lord will not trust me longer in this world; happy am I. My Savior,
my soul loves you dearly; your love is better than wine: my Savior, my holy One,
how glorious are you!
I have seen your glory; my heart is overcome with your sweet countenance.
O come away, why do you stay?
I am ready, I am ready.`"

After lying some time very still, she was heard in a heavenly harmony,
in which frame of spirit she departed without either sigh or groan, aged fifteen years.

[.asterism]
'''

JOHN SIMCOCK was a nursing father in Israel, tender over
the seed of God, and wherever he saw it, in the least appearance,
he was a cherisher of it, without respect of persons;
but he abhorred deceit and hypocrisy.
His ministry was sound, edifying and helpful to many,
he being endued with a spirit of discerning, and wisdom, beyond many,
in spiritual things.
He was a great sufferer for truth`'s sake, both by imprisonments and loss of goods.
He travelled much in truth`'s service, and notwithstanding all his sufferings,
he was in no ways chargeable to any, but rather helpful to those who stood in need.

In Joseph Besse`'s [.book-title]#History of Friends`' Sufferings,#
are some accounts of those sustained by him, and of his pious,
meek disposition towards his oppressors.
Once he was imprisoned a year and three months,
for accompanying his wife to a steeple-house,
for a sign and testimony against their false ways and worships.
His persecutors, at different times,
distrained from him to the amount of several hundred pounds sterling, for preaching;
taking nineteen cattle at one time, and twelve at another, besides corn, cheese,
and other goods; all which he bore patiently.
Once when they were driving away his cows, his servant-maid,
who did not profess among Friends, said to him: "`Master,
how can you stand by and see them drive away so many cattle?`"
He replied, it did not trouble him any more than if they had driven away so many geese.

He removed to Pennsylvania in early times, and settled in Chester county;
and when the spirit of division began to appear in George Keith,
he was active in visiting him, to endeavor to recover him;
and when the labor of Friends in that respect proved ineffectual,
he joined steadily with faithful Friends in testifying
against the said George Keith and his party.

In the time of his last sickness, he appeared to be in a heavenly frame of mind,
and uttered many lively expressions.
At one time he said: "`I have had many hard besetments with the enemy of my soul,
since I knew the truth, and have been in many straits,
and great combats and buffetings for the trial of my faith.
But the Keeper of Israel is near to all them that wait upon him,
and truly put their trust in him, and their faith is made strong in him,
whereby they are enabled to make war against the adversary of souls,
and to fight the good fight of faith, for whom is laid up a crown of endless joy, peace,
and heavenly comfort and glory.
And now I may say in truth, that I have kept this living faith,
in which my soul has renewed cause to magnify the name of my holy Redeemer,
and powerful Savior, Christ Jesus, in whom my faith has been made strong at this time.`"

The day before his departure, his wife and son, with some other friends, being present,
he bore a living testimony to the necessity of dwelling in love,
even that holy love which labors for the peace, welfare and everlasting good of all;
concluding in these words, "`I desire my love may be remembered to friends in general:
and it is the desire and earnest prayer of my soul,
that the heavenly spring of true love, and the stream of Divine life,
may ever be known to spring and run among those who would be accounted children of God,
and followers of Christ Jesus, our blessed Lord and eternal Savior,
who laid down his life to be a ransom for fallen man,
and to be an atonement for all them that would come to God by him,
who is the living Word and promised seed of the covenant.`"
He died the 27th of the First month, 1703.

[.asterism]
'''

ELEANOR SMITH, wife of John Smith of Darby, in Pennsylvania, was born at Harborough,
in Leicestershire, Old England: her maiden name was Eleanor Dolby.
She received truth about the age of thirteen years, and lived and died therein,
being a religious, exemplary woman;
and some years before her death received a gift of
the ministry of the Gospel of our Lord Jesus Christ.
Being taken sick a little before her departure,
she desired that her husband and children should come and sit down by her,
when she spoke as follows:

"`I entreat you, my children, to walk soberly, plainly, and to keep to the truth,
and the Lord will provide for you every way beyond your expectation.
I am clear of you, having done the part of a tender mother to you.
I leave and commit you to the Lord, who is able to keep you to the end of your days.`"
She desired them not to mourn if it should please God to remove her from among them,
saying, "`It will be my great gain.`"
She often repeated her full assurance of future happiness, adding,
"`I can praise your name O Lord in the midst of affliction,
for surely you are worthy of all praise, honor and glory, and that forever more;
for you neither leave nor forsake those that put their trust in you.`"
Then said, "`Dear children be content, for I shall die in favor with God,
and true love and unity with his people.`"
She desired to be dissolved, saying,
"`I can freely give up husband and children and all this world, to be with the Lord,
whose presence I feel flowing as a river into my soul.`"

She died the 10th day of the Seventh month, 1708, aged fifty-five years.
In the time of her last illness, she wrote the following epistle to the monthly-meeting,
of women friends at Darby:

[.embedded-content-document.epistle]
--

[.salutation]
Dear Sisters,

Herewith I send you the last salutation of my love,
with whom I have been many times refreshed and truly comforted.
I have travelled with you through various exercises and difficulties,
when the Lord has been sometimes pleased to give
us (as it were) the bread of adversity to eat,
and the water of affliction to drink; yet blessed be his name,
he has sweetened our cups many times as with honey,
and sustained us as with the oil of the cruse;
and by his sweet presence caused our cups to overflow, to the praise of his great name.
Therefore, dear sisters, I entreat you to dwell in the love of God,
which love is the bond of peace.
Let charity be found to dwell among you; and then, I believe,
you will be neither barren nor unfruitful,
but your branches laden with good and weighty fruit, which will find acceptance with God.
So no more, but my tender love to you in the blessed truth.
I take my leave and bid you farewell in the Lord.

[.signed-section-closing]
The last from your loving sister,

[.signed-section-signature]
Eleanor Smith

--

[.asterism]
'''

JOHN SMITH, of Darby, in Pennsylvania, was born in Leicestershire, in Old England,
in 1645, and was convinced of the truth at the age of fourteen years,
and being faithful thereto, after some time he came forth in the ministry.
He was an early settler in Pennsylvania, where he was well beloved.
Being taken sick, he was visited by many friends;
and about two days before his departure, being asked how he did, he answered,
"`I am very poorly and weak indeed, but much easier than I have been,
for I was extremely ill, and full of pain, such as I never had undergone before;
so that I could not retire in my mind to God, my extremity was so great.
But now the Lord has been pleased to give me ease, so that I can stay my mind on him,
for which I am truly thankful.
I feel the fresh renewings of the love of God, flowing into my heart,
which is of much more comfort to my soul than all transitory things that are here below.
I feel his living Divine presence with me,
which bears up my spirit over that which flesh and
blood would not or could not be able to bear.`"

Shortly after, a friend taking leave of him, asked him if he thought he should recover.
"`That,`" said he, "`I am not worthy to know; however, I am content: and this I know,
that if we abide faithful to God to the end, we shall receive a goodly portion;
so farewell, and the Lord go along with you.`"
At another time he said, "`He was full of pain,
yet he could sing of the mercy and goodness of God to his soul in the midst of affliction.`"
Afterwards adding, "`Do not mourn for me, but be still and quiet,
and let me pass away quietly, that so my soul may enter into God`'s everlasting rest;
for my conscience is clear from guilt in the face of all men;`" saying, "`Come, Lord Jesus,
receive my soul, your servant is ready, come quickly.`"

This he spoke in great freshness and cheerfulness of spirit, saying,
"`Now I think I am near my end;`" but reviving again, he sat up,
and his children being present, he said to them,
"`I was never covetous to get a great deal of this world`'s riches,
but I have endeavored to bring you up in the fear of the Lord,
and educate you in the way of his truth, to the best of my understanding;
and if you do but wait upon the Lord in the sincerity of your hearts,
for the dropping down of the love of God upon your
souls in the meetings of the Lord`'s people,
he will shed his blessings among you;
for he has been and is a father to the fatherless, and as a husband to the widow.`"

This he spoke just before his departure, being fresh in spirit,
and perfect in sense and memory to the last hour.
He died the 11th day of the Twelfth month, 1714, aged sixty-nine years and four months.

[.asterism]
'''

BENJAMIN JORDAN was born the 18th of the Seventh month, 1674,
in Nancemond county in Virginia, of believing parents,
who were careful to educate their children in the blessed truth for which they suffered,
and whose example, together with the influence of Divine grace,
was sanctified to this our friend, as well as several others of their numerous offspring.
He was a man who gave up much of his time in waiting upon God,
and in services for the church, being clerk both to the monthly and yearly meeting;
and he was a good example of piety and charity, and kept his integrity to the last.

The day before he died, several neighbors coming to see him,
one of them being in a flourishing state as to the world,
and to whom the way of truth seemed too low and despicable, he said, "`Rejoice,
O young man, in your youth, and let your heart cheer you in the days of your youth,
and walk in the ways of your heart, and in the sight of your eyes: but know,
that for all these things, God will bring you into judgment.`"
He looked upon another who seemed to be under some convincement of truth,
but did not live in obedience to it, and said,
"`Blessed are they that hear the word of God and do it.`"
To another who appeared to have sought after the
honor of this world more than the Lord`'s honor,
he said, "`He looked too big to enter in at the strait gate.`"

He gave particular directions concerning the place and manner of his burial,
desiring that no more provision might be made than was sufficient, having,
while in health,
borne a testimony against making such occasions a time of feasting instead of mourning.
One of his brothers asking him how it was with him, he replied, "`As to my eternal state,
nothing but well.`"
Soon after, holding up his hands and looking upwards, he said, "`Lord Jesus,
into your hands I commit my spirit.
Lord, help me at this time.`"
And so departed in quietness, the 12th of the Twelfth month, 1716,
aged about forty-two years.

[.asterism]
'''

ELIZABETH SMALL, wife of Benjamin Small, of Nancemond county, Virginia,
was born the 31st of the Sixth month, 1666.
Her parents, Edmund and Elizabeth Betson, were pious Friends and zealous for the truth,
whose care in the education of their children, had the desired effect on her mind.
Being obedient to the manifestation of Divine light, it so improved a tender,
affectionate, and affable disposition, that she became qualified for,
and was endowed with, an acceptable gift in the ministry,
so as suitably to dispense doctrine, edification, and consolation to the churches.
She was very diligent in attending the meetings of Friends in this colony,
even beyond what could be reasonably expected from one of so weakly a constitution,
and was earnest in, and much devoted to, the cause of truth,
greatly desiring the growth and prosperity thereof, saying,
"`She could lay down her natural life for it, if required.`"

She was a woman of a generous and kind disposition,
as well in helping the poor as entertaining friends, saying,
to such as were ready to think she would do more than her circumstances would admit of,
that she hoped the Lord would so provide for her,
that she should never lack what was convenient,
having never desired long life or riches for herself or her children,
but that they might live in his fear.

She was taken ill the 21st of the Seventh month, 1717,
being the first day of the yearly meeting at Chuckatuk,
which gave opportunity to friends from different parts of the country to visit her,
to whom she expressed her peace of mind and submission to the Divine will, saying,
among other things; If the Lord has any more work for me to do, he can raise me up again;
otherwise, I am easy and freely resigned to his will.`"
To a beloved relation she said, "`Dear cousin, you are bone of my bone,
and flesh of my flesh: live in the fear of the Lord,
that every high thought may be brought down.`"
To two friends belonging to a distant meeting which she had often visited, she said,
"`I have not ceased to admonish you heretofore,
and now again desire you would be valiant for the truth, and walk steadily therein,
and remember my dear love to friends of the meeting to which you belong.`"
She often spoke to friends,
"`To be steadfast in the truth;`" and once to a public
friend belonging to the same meeting,
earnestly desiring him "`To be valiant for the good cause.`"
She told her son William, "`She hoped that day would be a good one to her,`" and said,
"`She had prayed for an easy passage.`"
And accordingly she quietly departed the 25th of the Seventh month aforesaid,
aged fifty-two, a minister about eleven years.

[.asterism]
'''

ELLIS PUGH was born in the parish of Dolgelly, in the county of Merioneth,
and principality of Wales, in the Sixth month, 1656.
His parents were religious people; but his father died before he was born,
and his mother a few days after.
In the days of his youth, when going with the multitude into folly,
it pleased God by his judgments to stand in his way,
and cause him to consider the things that belonged to his soul`'s everlasting peace.
In the eighteenth year of his age, the Lord visited him more eminently,
kindling a zeal in him to serve his Creator more diligently;
having been also reached by the testimony of John-ap-John,
one of the people called Quakers.

God, who promised to be a father to the fatherless, took care of him;
and about the year 1680, gave him a part in the ministry of the gospel of Christ.
Notwithstanding he was not one of the wise of this world, nor had human learning,
yet he was made a profitable instrument to turn many from vanity,
and to exhort and strengthen them in their spiritual journey, both in his native land,
and also in Pennsylvania, where he finished his course.

In the year 1686, he and his family, with several of his acquaintance,
prepared to come over to Pennsylvania, and while they waited for the ship to be ready,
there came great trouble and exercise upon him, so that he was sick for some days.
In this strait the Lord showed him,
that they should meet with trouble and exercises in their way,
and that he had a work for him in that country (Great Britain), and that he must return,
after a time, to his native land.
After they sailed, they met with storms and troubles;
and having been upon the tempestuous sea all winter, they arrived at Barbados,
where they were joyfully and lovingly received by their friends.
In the summer following, in the year 1687, they arrived in Pennsylvania;
where this our friend was a serviceable instrument in the Lord`'s hand,
to cherish and instruct many, in meekness and tenderness,
to obey that which God made known to them of his will,
and to follow and understand the operation of his spirit,
discovering the snares of the enemy of their souls.
His pious labors, among others who were fitted for the same service,
were profitable in directing and edifying many in the way of truth;
for by the tenderness and influence which came as
dew upon their souls while they sat under his ministry,
they believed his doctrine was of God.

In the year 1706 he was engaged to visit the inhabitants of his native country,
according to what the Lord revealed to him before he came from there;
which service he performed to the benefit and acceptance of many,
and returned to his family in 1708.
After he came home, three of his children, in the flower of their age,
who from their youth had walked orderly and were hopeful, died within one month;
in the time of which trial the Lord was near to him;
and he mourned not as one without hope.
Strength was given him to bear his affliction.
He said in a public meeting,
"`If he could bear his affliction acceptably in the sight of God,
it would be as marrow to his bones;`" which testimony, among several other things,
was to the edification and comfort of the hearers.

His ministry was living, profitable, and to edification.
He was of a meek and quiet spirit, considerate and solid in his judgment, of few words,
honest and careful in his calling;
and several have been heard to speak of the benefit they received by his chaste conduct,
and his loving and comfortable expressions while he was among them in their families.
He was honorable among his friends, and of good report among people generally,
therefore his memory will not soon wear out.

He was in a declining state of bodily health about
a year and three months before his decease,
so that he was not well able to follow his calling; but his candle shone brighter,
as may be seen by perusing his treatise,
called [.book-title]#A Salutation to the Britons,# which he wrote in his own language +++[+++Welsh]
in the time of his long sickness,
when his view was towards that which pertains to eternity.
It was designed more especially for the sake of those to whom the
salutation of his love and life reached over sea and land,
for the encouragement and instruction of such as were seeking the way to Zion,
the New Jerusalem, the city of the Great King, whose walls and bulwarks are salvation.

The last meeting he was at, he was weak of body, but fervent in spirit,
as one taking his last leave in a great deal of love and tenderness, saying,
that the Lord granted him his desire to come and visit his friends once more;
putting them in mind to live in love and unity, and to keep out from among them,
as much as they could, all strife and discord; and when anything appeared,
which had a tendency thereto, that endeavors should be used without delay to end it;
and that none should depend upon his own eye, or balance, in judgment,
but on the Lord alone.
He was fitted to counsel others,
because his life and conduct were answerable to his testimony;
and among his family he was tender,
and careful to counsel them to live in the fear of God.
His friends testify that they looked upon him as one who had finished his work, and,
sensible that the time of his dissolution drew near,
that he might say in the words of Paul, according to his measure,
"`I have fought a good fight, I have finished my course, I have kept the faith.
Henceforth there is laid up for me a crown of righteousness, which the Lord,
the righteous judge, shall give me at that day; and not to me only,
but unto all them also that love his appearing.`"

Being patient in his tedious indisposition, and contented to wait the Lord`'s time,
he slept with his fathers on the 3rd day of the Tenth month, 1718, in favor with God.

[.asterism]
'''

WILLIAM HAIG, of Pasquotank county, who removed from Antigua with his family,
and settled in the province of North Carolina, was of a loving and sweet spirit.
In his last sickness, as some friends were sitting by him,
he was filled with heavenly joy, and said, "`Friends, I am glad of your company,
I feel so much of the blessed truth as I hope will carry me into that joy,
where I shall praise the Lord among the redeemed.
I hear that truth prospers greatly in England, blessed be the Lord for it.`"
He exhorted all his children with many heavenly expressions,
took his solemn leave of them, and in a living sense of the life of the Lord Jesus,
prayed to God for his blessing upon them; charging them "`to love and obey their mother,
learn their books, and keep to the truth.`"
He said to his wife, "`My dear, you have been a true wife to me.
When my mind was drawn to love you, I did not inquire what you had, nor you what I had,
but we came together in love and we have lived in love.`"
And when his speech was very low, he spoke to his wife thus:
"`The Lord bless you and my children.
God Almighty protect you.`"

To a young woman who came to visit him, he said: "`Fear God, keep to the truth;
never turn your back upon it, lest the days come, in which you shall say,
I have no pleasure in them.
As for me, I am going to my place, and I hope it will be in everlasting rest.`"
To another who had been visited with great sickness, he said:
"`It had been better for you to have died in your sickness, than to live to forget God.`"
He prayed that God would remember all his people,
and that their dwelling might be with the Lord; adding: "`But what shall I say;
there are too many that tread the testimony of truth under foot.
O! gather them into your fold of rest, I pray you, O Lord.`"

To a friend in the ministry, he said: "`You are of the ministry,
and have been employed in it a great while, and I am but young,
but I would advise you to be careful in your testimony,
not to enlarge beyond your gift or concern.
Have a care you do not stand in the way of others,
or speak anything to hurt others that may be but small or tender;
but wait until you are filled, and then be humble, and not puffed up with pride,
for pride goes before a fall.`"
After praying to the Lord to settle him upon the
sure foundation and rock that can never be removed,
he quietly departed this life, at his own house, on the 6th of the Eleventh month, 1718,
and now rests in joy.

[.asterism]
'''

MARY HAIG, wife of the aforesaid William Haig,
was a woman of an exemplary life and conduct, of a sweet and loving behavior,
and was favored with a gift in the ministry of the gospel of Christ Jesus.
In her last sickness, after imparting her mind to a friend about her outward concerns,
she spoke as follows: "`According to my small gift, I have discharged myself,
so that nothing lies at my door.
Oh! that the people would remember the words I have spoken among them,
and that this young generation would come up in the truth.
As for me, I had never left the island of Antigua,
if it were not that I might have my children among faithful Friends.
I have seen the wonders of the Lord in the deep ocean,
and witnessed his delivering arm in many exercises,
and he has kept me sweet and clean all along since I knew the truth.
Oh! that my children may remember the advice they have received of their father and me.
I am clear, having done my duty.`"
She then praised God, and also uttered many sweet and comfortable expressions.

At another time, she said to some friends, "`When I was but nine years old,
the Lord made himself known to me; but I then lived where there were no Friends;
and after some time, I went to Pennsylvania, and there met with Friends.
Some were loose and light, others were solid and weighty, and with these I joined,
and received much benefit from the family of the Lloyds.
After I was married we went to Antigua; and there, in the first meeting,
the power of the Lord was greatly with me,
insomuch that the people`'s expectations were upon me for words.
But soon after, it pleased the Lord to send two of his servants,
Josiah Langdale and Thomas Thomson, to visit the island,
when the power of the Lord broke in upon me like thunder.`"
She signified she had been faithful ever since, in her measure,
in giving up to the work of the Lord.

On the day of her decease, she said to some present, "`Friends, be loving one to another,
that the Lord may bless you.
The love that I feel in my heart is inexpressible.`"
After a while she desired a friend to remember her love to Lydia Lancaster,
Elizabeth Rawlinson, and friends generally, adding, "`Tell them,
I die in unity with all faithful Friends.`"
Afterwards she said, "`My husband is gone, but I shall not be long a sorrowful widow;
yet not my will, but yours be done.
My speech fails quickly.
Sweet Lord Jesus, you have loved me from a child,
and I have loved you ever since I knew you, and my case is no doubtful case.
I come, I come; hasten my journey.`"
She died the 13th of the Eleventh month, 1718, aged about thirty-nine years.

[.asterism]
'''

JOSEPH GLAISTER, of Pasquotank county, in North Carolina,
formerly of Cumberland in Great Britain, who removed with his family,
and settled in North Carolina, was a valuable minister,
and very serviceable in discipline, being well qualified therefor;
a constant attender of meetings with his family,
and one who travelled much for the spreading of truth.
In his last sickness, he said to some friends who visited him, "`I am very ill,
but am out of all doubt of my salvation, being well assured of it.`"
Two other friends coming in, he added,
"`Now I think I have most of the chief friends about me that I have desired to see.
Dear friends, give me up freely, that I may not be kept longer in misery,
for I can say with one of old, Lord, I have long waited for your salvation,
and now have an assurance of it; and although the pains of death
are great, yet the comfort and pleasure I see before me outbalance them all.`"

Again he said, he hoped that friends might keep their places in being faithful,
and not shrink one from another when troubles or differences may arise in the church,
or among neighbors, by any evil spirit that may get into any unfaithful one,
for lack of a true and faithful watch.
"`And if any such thing does happen, pray friends, I hope that such as now are,
or may then be, will stand firmly together, and give judgment in or by a living, fresh,
and Divine spirit, and keep constant in mind,
and thereby the transgressor or transgressors may be judged down,
and not be able to resist; but if you see in them anything tender, then, dear friends,
turn to them with bowels of love, and perhaps in so doing,
you may gain such as in times past may have gone astray.`"

He went on speaking of the great love and unity,
and the many good times he had had with Friends;
having his spirit borne up by the ancient arm that
had been from time to time his great support.
Near his end, those about him were sensible of his being engaged in prayer,
but being almost spent, they could not hear every word so as to pen it down.
Thus this good man ended his life, with a sense of the great love of God to his soul,
on the 31st of the Eleventh month, 1718, aged about forty-five years,
and a minister about twenty-four years.

[.asterism]
'''

VINCENT CALDWELL was born in Derbyshire, Great Britain,
and was convinced of the principles of truth held by the religious Society
of Friends about the seventeenth or eighteenth year of his age,
by the ministry of John Gratton.
Having received the truth in the love of it, and continuing faithful,
the Lord was pleased to commit to him a dispensation of the gospel of Christ Jesus,
so that he had to declare to others of the goodness of God to his soul.
He came over into Pennsylvania, and after his marriage, settled in East Marlborough,
in Chester county.
His ministry was sound and edifying, being attended with the power of truth,
and adorned with an exemplary conduct;
in the exercise whereof he twice visited the meetings of Friends in the southern provinces,
and once in several of the West India islands,
where he was made instrumental to the convincing of many.
Though he had but little school-learning, yet being as a good scribe,
well instructed unto the kingdom,
he at times brought forth out of the treasury things new and old.

His last sickness continued about six days, wherein he was preserved in a sweet,
sensible and tender frame of spirit, and at times spoke in substance as follows:
The doctor coming to visit him, he said with cheerfulness,
"`I would have you speak your mind freely concerning me, for I am not afraid to die.`"
The doctor after some pause, signified the doubt he had of his recovery;
which bringing an awful silence over his mind,
he broke forth in earnest supplication to the Lord for the welfare of Zion,
and exhorted friends present to love and unity,
and to beware of that spirit which would lead into separation.
He spoke clearly to the states of some,
warning them to fear the Lord and walk humbly before him,
and then they would be made partakers of his divine and heavenly blessing.
He prayed the Lord to prosper his work, and said,
"`The Lord will cause his glorious truth to break forth in the north country,
and among the Ethiopians,`" in a sight and sense whereof he rejoiced.

Another time, his wife sitting by him, he looked earnestly at her and said, "`My dear,
don`'t be surprised, for in time you will come into that rest I am going to.`"
She queried, "`Do you think so?`"
He said "`I have no doubt of it.`"
Then taking leave of her, he said, "`You have been a loving wife,
a tender mother and a good neighbor.`"
Taking leave of his children one by one,
he charged them to be loving and obedient to their mother,
and not to go out in their marriages.
He prayed the Lord to make his passage easy,
and receive him graciously into his arms of rest and peace forever;
and desired his love to friends in general at their monthly,
quarterly and yearly meetings, and meeting of ministers.
After which, being sensible that his end drew near, he said, "`Give me a little water,
and I think I shall not need any more,
till I drink at that fountain which springs up into eternal life.`"

Thus, in a resigned frame of mind, he finished his course,
the 10th day of the First month, 1719-20, in the forty-sixth year of his age,
and was interred in Friends`' burying ground at Kennet; and we believe,
he is entered into the mansions of glory,
where "`The wicked cease from troubling and the weary are at rest.`"

[.asterism]
'''

ANTHONY MORRIS,
a well-esteemed member of the monthly meeting of Friends
of Philadelphia at the early institution thereof,
appeared in the ministry, in the year 1701,
and being obedient and faithful in that station, he soon became acceptable and edifying,
being sound in word and doctrine.
He was advanced to his forty-seventh year when he engaged in this service,
and having a prospect of a great work before him, requiring his close application,
he drew his worldly business into a narrow compass,
and devoted his time principally to the service of truth;
not only visiting neighboring meetings, but also travelled through New Jersey,
Long Island, Rhode Island, New England and Maryland; and about the year 1715,
performed a visit to friends in South Britain.
He was early appointed clerk of the monthly meeting,
which service he performed many years to satisfaction;
being zealous and serviceable in the discipline,
a diligent attender of all our religious meetings,
careful in observing the time appointed,
and often concerned to exhort such to amendment as were remiss herein.

In the Eighth month, 1721,
his speech was much affected by frequent attacks of a paralytic disorder,
but his understanding remaining clear,
and being favored with the enjoyment of divine love,
he was enabled to utter some sentences to those who visited him, saying, "`That if,
consistently with the divine will, the time of his dissolution was at hand,
it would be more joyous to depart now, than to continue longer in the body.`"
Yet he expressed his free resignation to the will of God, and in a humble,
tender frame of spirit,
mentioned the testimony Christ gave concerning the
woman who poured on his head the precious ointment,
saying, "`He was favored with the evidence in himself, that he had done what he could,
and felt peace.`"
At the same time, he said,
"`That his hope for eternal salvation was alone in the mercy of God through his son,
Christ Jesus, the only Savior and Mediator.`"
Some friends who were going to attend a neighboring yearly meeting coming to visit him,
he took an affectionate leave of them,
saying "`Remember my dear love to friends in general; tell them I am going,
and all is well.`"

He departed this life the 23rd of the Eighth month, 1721, aged sixty-seven years;
and on the 25th his corpse was borne to the meetinghouse in High street, Philadelphia,
accompanied by many friends and neighbors;
as well as friends from the adjacent country meetings,
and from there to the burial-ground where it was interred.
Concerning him there is reason to believe that he has obtained
an entrance into the mansions prepared by Christ Jesus our Lord,
for those who continue faithful to the end of their time here, as did this friend.

[.asterism]
'''

JAMES DANIEL SR.--The memory of the righteous cannot
soon be forgotten by those who follow their footsteps,
for they are as memorials deeply engraven on their minds,
and are worthy to be had in remembrance.
Of this number was that steady friend and exemplary elder, James Daniel,
whose pious life and savory conduct, say his friends, are fresh in some of our memories.

He was born in Ireland about the year 1675; his father, Neal Daniel,
brought him over sea when about five years of age,
and settled in Alloway`'s Creek township, in the county of Salem, West Jersey;
at which time the white people were but few, and the natives a multitude.
He learned their language perfectly; and has frequently said,
that at that time the natives were a sober, grave and temperate people,
and used no manner of oath in their speech.

About the 15th year of his age his father died, leaving him in the care of friends,
to be educated in the way of truth, as professed by them;
which he embraced in the love of it; and as he grew in age,
he grew in experience and divine favor,
and had a share of the oversight of the flock and eldership conferred upon him,
which he faithfully performed in the spirit of love and meekness,
thereby rendering his service acceptable and obtaining a good report.
He ruled his own house well, having his children in subjection;
and was diligent in attending meetings for worship and discipline,
although for many years with difficulty, the country being new and roads not made;
but afterwards, with considerable cost and labor,
he got bridges erected over some creeks, and a public road made near his own house.
His house and heart were open to entertain friends according to his ability;
and he was zealously concerned for the honor of God and the promotion of truth.

He often lamented that as the country grew older the people grew worse,
and had corrupted the natives in their morals,
teaching them bad words and the excessive use of strong drink, which,
during many years in the latter part of his time, for example`'s sake, he took none of,
and frequently admonished such as were in the use thereof, to observe great temperance.

Towards the close of his life,
he desired his eldest sons to take the care of his temporal concerns upon them,
for his mind seemed redeemed from them as much as though he possessed nothing:
a good example for all elders; for sorrowful experience shows that too many,
as they grow in years, grow more closely attached to the earth;
which is a lamentable state and a poor example to the rising generation.
He devoted his mind and time to truth`'s service,
often accompanying friends in their religious engagements, to his great satisfaction.

While in health, the Lord gave him a sense that his departure drew near;
and soon afterwards he was taken with the pleurisy and was sick about eight days,
during which time he gave much good advice to his family,
friends and neighbors who came to see him,
to whom he also gave evident proofs of a happy exit.
The day before his departure,
many friends and neighbors came and had a religious meeting, after which,
several taking leave, he said, "`I am glad of this visit and of the meeting,
but I have a great concern on my mind for this generation,`"
mentioning many growing evils then prevalent,
and said, "`Many of the elders are called away and more must be soon;
but I hope the Lord will raise up some who shall be faithful and zealous.`"

The evening of his decease, he took his solemn leave of all present,
beginning with his wife, and afterwards his children, in order,
giving each something in charge; to one particularly he said,
"`You do not know what service the Lord has for you to do in your generation.`"
So, remaining sensible, he departed in the faith and hope of the gospel,
like one falling into a sweet sleep, at his own house, on the 26th of the Tenth month,
1726, in the fifty-second year of his age.

[.asterism]
'''

CALEB PUSEY was born in Berkshire, Old England, and educated among the Baptists,
but after he arrived to years of religious consideration,
he was convinced of the principles of truth professed by the people called Quakers.
In the year 1682, he removed to Pennsylvania, and settled near Chester,
where he resided a considerable time, then removed to Marlborough in the same county,
where he dwelt the remainder of his days.

He was a worthy elder in the church, being endowed with a good natural capacity,
sound in judgment,
and zealous in maintaining the cause of truth against contrary and contending spirits.
His constancy in attending meetings for worship and discipline was remarkable,
and worthy of imitation.
Much might be said of his zeal and integrity for truth, which he retained to the last,
but, for brevity`'s sake, let it suffice, that he was a just man;
therefore let him be had in remembrance.

His last illness was heavy upon him for six days; during which he was preserved sensible;
signifying what a brave thing it was to be prepared for death.
The morning before he died, being asked by his son-in-law how he did, he answered,
"`The time was nearly come that he must leave the world;`" to which his son replied,
"`I hope that is no surprise to you;`" he answered, "`No,
no;`" after which he spoke little that could be understood,
only desired "`That friends might keep their meetings in uprightness.`"

He died the 24th of the Twelfth month, 1726-7, in the seventy-sixth year of his age,
and was interred in Friends`' burying-ground at London Grove.

[.asterism]
'''

HANNAH HILL, wife of Richard Hill, and daughter of Thomas Lloyd,
formerly governor of the province of Pennsylvania, by Mary,
the daughter of Gilbert Jones, of Welchpool, was born in Montgomeryshire, North Wales,
at the seat of her ancestors, called Dolobran, the 21st of the Seventh month, 1666.
She was a woman highly favored of the Lord,
and possessed many excellent Christian virtues, as well as natural accomplishments.
Coming over into Pennsylvania with her parents when young,
soon after their arrival it pleased the Lord to remove her pious mother by death,
when the care of the younger children devolved upon her.
This close trial in the earlier part of her time was abundantly sanctified to her;
for her mind being engaged to seek the Lord for her portion,
and her father`'s God for the lot of her inheritance, he was graciously pleased,
not only to favor her with the knowledge of himself,
and the enjoyment of his living presence in the days of her youth,
but also made her a singular instrument of good, and a blessing to her father`'s family.

As she grew in years, her conspicuous virtues, joined with a courteous deportment,
justly gained the esteem and favor of most, if not all, of those with whom she conversed.
Being earnestly solicited in marriage by John Delaval, who, though a worthy man,
was not at that time of the same religious communion, she,
by her prudent conduct and pious resolution to maintain the principles she professed,
without deviating therefrom in a matter of such importance, did not agree thereto;
until he after some time embraced the truth in sincerity of heart,
and bore his cross like a humble follower of Christ.
He received a gift in the ministry, and continued faithful therein to his death;
concerning whom she gave this testimony:
"`That he never used to her an expression of anger,
or the product of a disturbed mind.`"

The decease of her husband proved to her a time of deep probation,
having been heard to say,
that in eight weeks`' time she lost eight of her family by death,
beginning with the decease of her beloved husband,
and ending with that of her only child.
Under these afflicting circumstances,
as well as those which attended her during the remaining part of her life,
of which she had a large share,
she approved herself a shining example of patience in tribulation, and a meek, humble,
self-denying follower of Jesus, her crucified and risen Savior.

In the affluent station wherein Divine Providence had placed her,
her benevolent disposition was conspicuous in administering
to the necessities of the indigent;
her enlarged charity not being limited to those of her own profession.
She was a true servant of the church, and in the sense of the apostle`'s expression,
"`One that washed the saints`' feet,`" receiving with joy
into her house the ministers and messengers of the gospel,
for whom her love was great: The low, the poor and the mean,
were objects of her peculiar care.

In her younger years she received a gift in the ministry of Christ`'s gospel,
which she retained with faithfulness to the end; and though not large in her testimonies,
yet they were with great modesty and soundness of expression.
"`Her doctrine dropped as the dew,
and distilled as the small rain,`" and was therefore truly acceptable.
She travelled in the service of the gospel to New England,
and several other parts of this continent,
and was also concerned for the good order and discipline of the church,
having for a number of years served in the station of clerk of the women`'s monthly,
quarterly, and yearly meetings, wherein she gave satisfaction.

Although bodily weakness frequently attended her in the latter years of her life,
it did not abate her love and zeal for the everlasting truth,
which she experienced to be her support in every time of trial.
When her dissolution drew near, she made many seasonable remarks and observations,
and signified her acquiescence with the divine will,
in the dispensations of his providence towards her;
at one time particularly mentioning the expressions of the apostle,
"`That no chastening for the present seems to be joyous, but grievous; nevertheless,
afterward it yields the peaceable fruit of righteousness
to them that are exercised thereby.`"

This was her happy experience; and after a well-spent life,
interspersed with a variety of exercising vicissitudes,
she exchanged this state of existence, no doubt,
for a blessed immortality in the regions of unmixed felicity;
after about three weeks`' illness, on the 25th of the Twelfth month, 1726-7,
in the sixty-first year of her age.
Her corpse was respectfully attended by a large number of friends and others,
to the High street meetinghouse in Philadelphia,
where several living testimonies were borne,
after which it was interred in Friends`' burial-ground.

She was twenty-six years the wife of Richard Hill,
who was a serviceable member both in church and state, and died in good esteem,
the 4th of the Seventh month, 1729.

[.asterism]
'''

JOHN BEVAN was born in Wales, about the year 1646, and well descended;
his parents died when he was very young, leaving five children,
of whom he was the eldest.
In 1665 he married a religious woman.
His father had left him a considerable estate,
but the rest of the children were unprovided for; he, therefore, when he came of age,
(his sister being dead before) portioned all his brothers,
and gave them the means of subsistence in the world.
Some years after he was convinced of the blessed truth as it is in Jesus;
the manner of which, as he himself has left it in writing, was thus:

[.embedded-content-document]
--

My wife was religiously inclined in her young years,
and zealously concerned to observe the ceremonies of the church of England, and,
I believe, as she has often told me,
she aimed sincerely therein at God`'s glory and the salvation of her immortal soul.
After we were joined in marriage, she continued very zealous in that way;
but when a weighty concern came upon my mind for the well-being of my immortal soul,
I saw it very needful for me to make a narrow search after the best way,
and those people who performed that worship and service which was acceptable before God.
Being in a weighty frame of spirit,
the people called Quakers came before the view of my mind;
and hearing of a book written by George Fox, the younger, at a relation`'s house,
I was willing to go there for it; and in the reading thereof I was so well satisfied,
that I can truly say, what I then read answered the witness of God in my own bosom,
as "`Face answers face in a glass.`"
Soon after I came home,
my wife perceiving me to be more serious and weighty in my spirit than formerly,
was jealous that I had an inclination towards the way which
the people called Quakers made profession of;
and finding I had the said book, she came up to the chamber where I was,
and cautioned me not to be beguiled.
I spoke to her in simplicity and much brokenness of heart,
of the sense and satisfaction I had,
that those who were faithful to that divine principle
+++[+++the Spirit of the Lord Jesus Christ]
which the people called Quakers bore testimony to, were the people God owned,
or to that import; and it reached to God`'s witness in her,
so that we parted in much tenderness at that time.

However, she continued somewhat zealous in her way still, and would be
often arguing with me in vindication thereof, for about twelve months; but at one time,
when she was at their worship, the priest pronounced his excommunication against me,
and she being in a seat just under him,
it came so near her that she was close to fainting away.
When their worship was over, she went to the priest and spoke closely to him,
and that she thought she deserved more civility,
at least so much as to know beforehand of their excommunication,
for he might know that she sincerely loved her husband;
though he dissented from her in judgment.
After that time she became more willing to search closely
into the weighty work of the salvation of her immortal soul;
and the Lord`'s love was manifested to her, so that, in a little while after,
her understanding was opened,
and she came to be convinced of God`'s everlasting Spirit of truth,
that was promised "`To lead into all truth.`"
And having tasted of that living bread which gives life to the soul,
she came to see there was no need of the outward bread,
which formerly she was zealous and conscientious in the observation of,
to commemorate the death and passion of our Lord Jesus Christ;
the true remembrancer being now come and witnessed,
even he who stands at the door of men`'s hearts and knocks for an entrance,
that he may come in to sup with them and they with him.

Soon after our convincement, the enemy of souls mustered his forces,
and endeavored to stifle our convictions,
and we were hard put to it both within and without; but as our eyes were to the Lord,
and in poverty and humility of spirit we leaned upon him, he made the hard things easy,
and in the sense of his divine love, which was often shed abroad in our hearts,
we were made willing to deny ourselves, to take up the cross, and to despise the shame.
And though we were but a few,
we thought it convenient to meet together to wait upon the Lord,
being fully satisfied it was a duty incumbent upon his people in all ages.
In the performance of our duty herein, in the year 1675,
several friends were taken from our house at two different times,
and brought before two justices of the peace,
who tendered the oath of allegiance and supremacy to them, and because,
for conscience`' sake, they could not break the command of Christ, who said,
"`Swear not at all,`" they were committed to prison,
where they remained about fourteen weeks, and then were set at liberty; ever since which,
the meeting has been quietly kept either at our house or at the meetinghouse,
without any more disturbance.

Some time before the year 1683, we heard that our esteemed friend, William Penn,
had a patent from King Charles the Second for that province in America called Pennsylvania;
and my wife had a great inclination to go there,
and thought it might be a good place to train up children among sober people,
and to prevent the corruption of them here, by the loose behavior of the youth,
and the bad example of too many of those of riper years.
She acquainted me therewith, but, for several reasons,
I then thought it not likely to take effect;
but as I was sensible her aim was upright on account of our children,
I was willing to weigh the matter in a true balance; and I can truly say,
my way was made easy and clear to go there, beyond my expectation;
and the Lord`'s great mercy preserved us over the great deep to our desired port.
Those hardships we met with at the beginning of our settlement,
the Lord was our helper and support to go through; and I can in a sweet remembrance say,
many were the blessed seasons we had with God`'s people in that remote country,
and I believe and am well satisfied that the Lord has a remnant there,
who sincerely aim at his glory and the prosperity of his truth,
blessed and praised be his holy name forever.

We stayed there many years, and had four of our children married with our consent,
and they had several children;
and the aim intended by my wife was in a good measure answered.
Then a weighty concern came upon my mind to return to my native country,
and that chiefly on truth`'s account.
I laid it before my wife, and she could not be easy to stay behind me,
and we came over in the year 1704;
and through the Lord`'s great mercy we were preserved in that tedious voyage,
north about Scotland, through many difficulties,
and from the cruelties also of the privateers,
of which there were many then on that coast, as we were afterward informed.
This wonderful preservation deserves to be remembered with thanksgiving.
Having lost the fleet, we were only four ships coming together from Virginia,
and one of them belonging to Bristol, we thought to remove to that ship,
because Bristol was nearer to our habitation in Wales than London,
where our vessel was bound.
We agreed with the master for our passage, and next morning we were to go on board;
but that night I was under a weighty exercise about our removal,
and in the morning it happened to be so stormy that he could not take us in,
so he parted from us, and bore his course towards Bristol.
Then the weight I was under was removed, and I was very easy in my spirit;
and as I was afterwards informed, that ship was taken as a prize near to Lundy Island.
This deliverance, therefore, and our preservation,
I ascribe to the Lord`'s great favor and mercy towards us; thanks, honor,
and praises be rendered to him for the same and all other mercies forever.

In this voyage our youngest daughter, Barbara Bevan, accompanied us,
and she was of good service on truth`'s account; the short time she remained in the body,
her innocency and sweet behavior preached truth wherever she came.
It is my comfort and great satisfaction, that she left a good savor,
and has finished her course in peace with her Maker,
and is gone to her eternal rest in the mansions of bliss and joy,
to laud and magnify him forever.^
footnote:[A short testimony concerning her, worthy of perusal,
is printed in the fifth part of [.book-title]#Piety Promoted.#]

We landed at last at Shields in Northumberland,
and stayed over the meeting on the First day, where we were comforted with friends.
Next day we set forward towards our habitation in Wales,
having nearly three hundred miles to travel.
We had several good meetings in our way; and about the beginning of the Eighth month,
1704, we came to our home at Treveyrick;
and from that time forward my dear wife was given
up as before to be serviceable on truth`'s account,
and so continued during her pilgrimage here, being six years and upwards.
Her house and heart, since her convincement, were open to receive the Lord`'s messengers,
both here and in America,
and she was very careful and open-hearted to help the poor and weak,
both among us and others.

In her last sickness she was sensible she was not likely to recover out of it,
and she was satisfied and contented therein to submit to the Lord`'s will.
Speaking to me, she said, "`I take it as a great mercy that I am to go before you.
We are upwards of forty-five years married,
and our love is rather more now one towards another, than at the beginning,
yet I am willing to part with all, for the Lord is better than all.`"
She quietly departed this life the 26th of the Eleventh month, 1710;
aged seventy-three years and about four months; and though my loss thereby is great,
yet it is her eternal gain.

--

John Bevan and his wife were examples of meekness, temperance, and charity,
and having lived in love and fellowship with their brethren and sisters,
were in good esteem among all.
He received a gift of the ministry,
which was to the comfort and edification of the church,
and visited New England in company with Hugh Roberts, about the year 1701;
and soon after he returned from Pennsylvania,
he and his daughter Barbara visited together several
meetings of Friends in South and North Wales,
and were eminently favored therein with the Divine presence.
His sufferings, considering his faithfulness and the time he lived in,
were not very many; his relations at times diverting the strokes of persecution from him.
However, after a long prosecution by the vicar of the parish for his pretended dues,
he was at last confined to Cardiff jail, in 1721, upon an _excommunicato capiendo_;
but there being some error in it, he was discharged the following sessions,
and ever after left unmolested.

He was endued with a good understanding in things spiritual and temporal,
discreet and prudent in his ways, of an unspotted life and conduct,
grave and solid in his deportment, and careful to keep concord and unity among Friends;
constant and immoveable against that which would divide and rend,
yet laboring to restore those who were beguiled thereby.
In his last sickness, he had no small conflict, but he was favored with much patience,
and possessed his soul therein, and bore his indisposition to admiration.
At one time he said, "`Ever since I had the knowledge of the truth,
I have endeavored to be innocent.`"
To a relation, asking him how he did, he answered, "`Weakly,
but I find some strength to bear my weakness.`"
