== Chapter 2

[.chapter-synopsis]
* Hannah Carpenter
* Robert Jordan
* Rowland Ellis
* Ann Parson
* Joseph Elgar
* Joseph Jordan
* Christopher Wilson
* Thomas Chalkley
* Robert Jordan

HANNAH CARPENTER was born at Haverford West, in South Wales, where,
having the opportunity of seeing the patient, innocent,
and steady sufferings of Friends who were imprisoned for their religious testimony,
together with their good conduct in Christ, she was convinced of the blessed truth,
and became very serviceable to those who were in bonds there for Christ`'s sake.
She came over to Philadelphia in the early settling of Pennsylvania,
and after some time was married to Samuel Carpenter, a Friend well esteemed in that city.
She received a gift of the gospel ministry,
which was seasoned with a lively savor of Divine sweetness;
and though not frequent in her appearances, was very acceptable.
Her heart and house were open to receive and entertain the true gospel ministers,
to whom she was a tender nursing mother both in sickness and in health;
being full of warmth and love to faithful Friends,
a bright example of meekness in the church as well as in her own family;
and her life and conduct being adorned with the Christian
virtues of benevolence and charity,
rendered her beloved, respected, and useful in her station.

She died the 24th of the Fifth month, 1728, in the eighty-third year of her age.

The following epistle to parents concerning the education of children,
manifesting her pious regard for the youth,
and her anxiety for the increase and prosperity of the church of Christ,
is thought proper to be here annexed:

[.embedded-content-document.epistle]
--

Upon the 4th day of the Fourth month, I was drawn forth to wait on the Lord,
and as I was waiting,
the consideration of my dear children whom the Lord had taken to himself in their innocency,
came before me, and my soul blessed his holy name for his great love towards them and me,
in that they are gone to their rest,
and shall never partake of those exercises and sorrows
which they do who remain in the world.
Then my soul was poured forth before the Lord for those that remain,
that as they grow up in years, they may grow in grace,
and in the knowledge of our Lord and Savior Jesus Christ.
I would rather follow them to their graves while they are young,
than that they should live to the dishonor of his worthy name.

Then a more general and weighty concern also came
upon me for Friends`' children who are grown up,
and do not come under the yoke nor bear the cross.
Oh! the cry that ran through my soul;
and in the anguish and bitterness of my spirit I said, Lord,
what will you do with Friends`' children when we are gone off the stage of this world?
Will you raise up children +++[+++in your church]
and not those of believing parents?
And this was the word that livingly sprung up in my soul.
They reject my counsel, and cast my law behind their backs,
and will have none of my reproofs,
and though my hand be stretched forth all the day long, yet they will not hear,
but go after their own hearts`' lust.
Then I said in my heart, Lord, are they all so?
The answer was, There are some who are innocent,
whom I will bless with a blessing from me, and they shall shine forth to my praise.
And now, Oh friends! that you may abide in the innocent life,
and so you may feel the blessing of the Lord daily to descend upon you.
But for you that '`Reject the counsel of the Lord, and cast his law behind your backs,
and will have none of his reproofs,`'
which are sorrowful sayings concerning you who are the children of believing parents,
you who are under the profession of the truth, which will do you no good,
unless you return unto the Lord, I desire you may all return unto him,
while the day of a long-suffering, merciful God lasts.
But if you still reject the counsel of the Lord,
and the many faithful warnings you have had,
how will you answer it in the day when he comes,
'`To render unto every one according to their deeds?`'

Something further is with me to parents of children.
Dear friends, you that have been convinced of God`'s unchangeable truth,
and have known the work and operation of it,
working out and bringing down that which was of a contrary nature to it.
Oh! that we may all abide faithful in his work, and retain our integrity to the Lord,
then let our breathing cries and prayers be offered up to the Lord for our children,
that he would be pleased to look down in mercy upon them,
and visit them as he did our souls.
But as David said, '`If I regard iniquity in my heart,
the Lord will not hear me;`' so I desire we may all
be clear in our offerings before the Lord,
that he may smell a sweet savor from them.

Dear friends, what is here written is with great caution,
knowing that I have children of my own,
and that many honest parents have had bad children, which is no small exercise;
but if we keep faithful to the Lord,
and discharge our duty to them by precept and example,
we shall be clear of them in the sight of God.
Therefore, friends, faithfulness is the word that runs through me,
not only for our own souls, but for our children`'s also;
that a generation may grow up to his praise in this part of the world,
when our heads are laid in the dust.
Great and manifold have been the love and mercy of God towards us,
the consideration of which, many times has deeply affected my mind.
It was he by his power who reached unto us,
and brought a concern upon us in our native land;
and I believe that many had as clear a call to leave their native country,
as some of old had,
which caused many days and nights of sore travail and exercise before the Lord,
and no ease could we have, but in giving up life and all to him, saying,
'`Lord do what you will with us, only let your presence preserve us.`'
And to his praise we can say, he has been with us since we came to this country,
and preserved us through many and various exercises, both inwardly and outwardly.

And now that which lies on our parts I desire may be considered by us all,
that so suitable returns may be made to the Lord,
by walking in humility and godly fear before him; that so we may be good patterns,
by keeping our places '`To the praise of him who has called us,`'
for he is worthy forever more.
And, friends, something more is with me which I thought to omit,
but find I can not well do it; that is, concerning our children,
that we be very careful while they are young,
that we permit them not to wear such things that truth allows not;
and though it may be said, they are but little things and well enough for children,
yet we find, that when they are grown up, it is hard for them to leave them off;
which it may be, if they had not been used when young,
would not have been expected when grown up.
So I desire we may all be clear in ourselves,
and keep our children out of the fashions and customs of this world.
And oh! that we were all of one heart and mind in these and other things;
then would the work of the Lord go on easily, which is the sincere desire of your friend,

[.signed-section-signature]
Hannah Carpenter

--

[.asterism]
'''

ROBERT JORDAN was son of Thomas and Margaret Jordan, of Nancemond county in Virginia,
born the 11th of the Seventh month, 1668,
and carefully educated in the way of truth by his worthy parents,
who lived to see the religion of his education become
that of his choice and practice in his mature years,
in which he was preserved to the last without wavering,
in great peace with the Lord and unity of his brethren.

He was a hospitable man, very ready to entertain strangers,
especially the Lord`'s messengers, whom he treated with great respect and affection,
honoring them for their work`'s sake; being also charitable to the pool, and,
as a man of trade and commerce, obtained a good reputation,
having declared he had never wronged any man knowingly in all his life.

In the time of his illness, which continued about two weeks,
he seemed very patient and resigned to the will of God,
and much concerned for the everlasting welfare of his children,
which he expressed in a lively manner.
He often, in fervent prayer,
desired they might be preserved from the vanities and corruptions of this world,
and that they might love and fear the Lord in their youth, saying at one time,
"`O Lord preserve my flock: let them never go astray, nor forget you, or one another:
O my God! hold them in your arms that none of them be lost:
let not the enemy prevail over them.`"
Being humbly thankful,
he blessed God that he had been pleased to support him through
every dispensation of his providence to that time.
He died the 3rd of the Eighth month, 1728, and on the 9th of the same month,
after a large meeting held on the occasion, was interred in the family burying-ground.

[.asterism]
'''

ROWLAND ELLIS was born in the year 1650, in Merionethshire, North Wales,
convinced of the truth about the twenty-second year of his age,
and suffered several years`' imprisonment with constancy on account of his testimony,
it being then a time of sore persecution.
The two judges who committed him, with many others,
for refusing to take the oath of allegiance and supremacy,
declared openly at the assizes: "`That in case they refused a second time to take it,
they should be proceeded against as traitors, the men hanged and quartered,
and the women burned.`"
In 1686, he came over into Pennsylvania, to prepare a settlement for his wife and family,
with whom he returned in 1697.
He was endued with a gift in the ministry,
and though not very frequent in his appearance therein,
his service was acceptable and to edification.
Being of sound judgment,
and ready and willing to assist his neighbors and friends in all cases,
civil or religious, when desired, he was very useful,
both in spiritual and temporal affairs.

He was zealous for supporting the Christian discipline of the Society,
and exemplary in conducting himself agreeably therewith; sometimes saying:
"`If the hedge of discipline was not kept up,
the labor of the husbandman would soon be laid waste.`"
He was careful in educating his children religiously,
by timely endeavoring to inculcate in their minds the principles of piety and virtue;
a practice tending thereto, was, having meetings frequently in his family,
which he long continued.
In the last monthly meeting he attended he was taken unwell,
but afterwards said to several friends present: "`I am glad I was here today,
for I had a lively meeting, and though I now feel much weakness,
and the infirmities attending my advanced age, yet I can say,
truth is as dear and as sweet as ever.`"
He also said: "`Satan sometimes lies in wait like a roaring lion to devour me,
but I find he is chained by a secret hand, which limits his power,
so that he cannot harm me.`"
His indisposition continued a few days, which he bore with Christian patience,
expressing "`His sense of his near arrival at the haven of rest and quiet,
where none could make him afraid.`"

He expired at the house of his son-in-law, John Evans, in the eightieth year of his age,
and was interred in Friends`' burying-ground at Plymouth,
to which particular meeting he belonged, in the Seventh month, 1729.
We trust it may be said concerning him, he rests in Jesus,
enjoying the reward of the righteous, and his works do follow.

[.asterism]
'''

ANN PARSON, of Wrightstown monthly meeting, in Bucks county, Pennsylvania,
appeared in the ministry in her youthful days, and continuing faithful,
travelled in that service several times through New England, the Jerseys, Pennsylvania,
Maryland and Virginia, in America, and through England, Ireland, Scotland and Wales,
in Europe; her ministry being savory and to edification.
She was a good example of an inoffensive life, patient in affliction,
and died in good unity with the church.

In her last illness, she said to her brother, Abraham Chapman:
"`I have travelled a pretty deal in my time, and, according to my ability,
have labored in the love of God, in the service of truth, and good-will to all men,
which springs in my bosom now as fresh as ever: blessed be His name.
I desire you, if I die now, by a few lines, to remember my kind love to Friends,
desiring they may stand in the counsel of God; for I have often rejoiced and been glad,
to see Friends stand in his counsel, and keep their places in the truth.
On the contrary, it has often wounded my spirit,
to see those that have made a profession of the truth,
and some of them children of good parents, take undue liberty,
taking pleasure in vanity and folly,
and neglecting that which would be to their everlasting peace.
It is my advice to Friends, that they stand in the counsel of God,
which will be to them as a mighty rock in a weary land,
and enable them to wade through the various exercises and troubles which
may fall to their share to meet with in this troublesome world.
I have found it by experience to be a sure help in every needful and difficult time,
when exercises seemed to surround me on every hand like the billows of the main;
then I found, to stand in the counsel of God,
was the only place of refuge that I could retire to, where I found safety,
and was often refreshed,
strengthened and comforted by the influence of the love of God in me;
and I would counsel and advise, that all Friends keep close to meetings,
and patiently wait to feel their strength renewed in God.
As it has been the desire and labor of my spirit,
that Friends should keep up their meetings in good order, and in the wisdom of truth,
so I recommend it as my advice and counsel to Friends, to be careful to keep to meetings,
and patiently wait to feel the overshadowing power of truth,
to strengthen and renew their hope in God,
which brings down and abases everything that would exalt
itself above the peaceable government of truth.`"

After having lain some time in great stillness, she in fervent prayer besought the Lord,
"`To carry on the work he had begun, so that many might flock to his church,
as doves to the windows; and that sin and iniquity might cease,
and righteousness and truth cover the earth,
as the waters cover the sea;`" fervently beseeching the Lord, "`To bless his people,
and her near relations,
and that her companion might be favored with the visitation of Divine love,
and know his last days to be his best days;
and that he might find admittance into rest and peace,
when time to him in this life should be no more,`" with many more of the like expressions,
at several times during her illness.

She died the 9th of the Tenth month, 1732, in the fifty-seventh year of her age,
having been a minister thirty-three years.

[.asterism]
'''

JOSEPH ELGAR was born at Folkstone, in Kent, Old England, the 30th of the Fourth month,
1690, of believing parents; and came into America about the year 1720,
living some time near Philadelphia, and, in 1728,
removed within the limits of East Nottingham meeting.
After his coming to this country, he was called to the work of the ministry,
wherein he was not forward, yet his appearances being lively and edifying,
friends had near unity therewith.
He was a good example in attending meetings, a faithful laborer therein,
and careful in keeping to the hour appointed.
He was industrious in outward affairs,
though cheerfully given up to answer the requirings of truth;
visiting the meetings of Friends in Pennsylvania,
as also in New Jersey and Maryland generally.

He was gifted in the discipline of the church,
and likewise qualified for the service of visiting families,
wherein he was engaged the last time he was absent from home,
within the limits of Bush River and Deer Creek particular meetings.
On his return from there, he told a friend, '`There was
an unusual weight over his spirit, and a cloud that he could not see beyond,
which made him think his day`'s work was nearly over.`"
The night he returned home, he was affected with sickness and much pain,
which continued several days, and he bore them with exemplary patience.
Afterwards, growing weaker, but remaining sensible, he often expressed,
"`He had done with the world, and was willing to leave it,
for he had been faithful to what was made known to him,
since he gave up to the requirings of truth.`"

Continuing in a sweet composure of mind, he departed on the 19th of the Eleventh month,
1733-4, in the forty-fourth year of his age, a minister about twelve years.
His remains were interred in Friends`' burying-ground at East Nottingham;
on which solemn occasion, Mungo Bewley, of Ireland,
who was then on a religious visit`' in America,
exercised his gift to the comfort of many Friends.

[.asterism]
'''

JOSEPH JORDAN was born in Nancemond county, in Virginia, in the year 1695,
being the third son of Robert Jordan,
and one of the third generation who have walked in the truth.
He was of a sprightly genius, affable disposition, and even temper, which,
as he grew to manhood, gave him easy access to company, esteemed the better sort.
A visitation of Divine love being extended to him
about the twenty-second year of his age,
he, like Zaccheus, made haste,
and with joy embraced both the message and the messenger of salvation.
Being endued with a gift in the ministry,
he acquitted himself "`As a workman that need not be ashamed,`"
and had great place in the minds of men.
Although he had not much school literature,
yet he might be said to have had the tongue of the learned,
being both correct and concise in speaking the word in season,
insomuch that many confessed to the truth, and embraced the doctrine he preached.
Being patient in tribulation,
he was favored with that hope which affords content and solace of mind.

After laboring in the gospel in his own country and the adjacent provinces,
he visited most parts of England, Ireland, and parts of Holland;
being absent on this service above three years.
He returned with peace, and found his presence necessary at home;
for his father being deceased, and his brother Robert then absent,
the care of the family devolved upon him, which trust he discharged with judgment,
being a good economist, kind neighbor, and steady friend.

He often intimated that he should not continue long,
and was therefore concerned to use diligence.
Not long before his decease, he visited friends in Virginia and North Carolina,
edifying them with his gift; and in the beginning of the month in which he died,
though very weak in body, attended their quarterly meeting, signifying at his return,
his great satisfaction therein,
believing it would be the last meeting of the kind he should ever be at;
and accordingly he never afterwards went from home,
except to a week-day meeting in the neighborhood.

On the morning of the day of his dissolution, he uttered many savory expressions,
saying to some young ministers, "`Mind your gifts and the Lord will bless you,
and you will be a blessing to the church.
Be humble and obedient; obedience brings sweet peace.
I have a great desire there might be a right ministry continued in the church,
for there are many not strictly of this fold, who in due time the Lord will bring in.
As you come to have an experience of the work of truth in your own hearts,
you will be able to confute those who persuade themselves
there is no living without sin in this world.
I am not in a condition to speak much; neither is it, I hope, very needful;
as you are thus taught of the Lord,
you will have cause to rejoice in him on whom you have believed.`"

Thus, having happily completed his day`'s work,
he laid down his head in much resignation and peace with the Lord Jesus,
the 26th of the Ninth month, 1735, aged forty years; a minister about 17.

[.asterism]
'''

CHRISTOPHER WILSON was born in Yorkshire, Old England,
of parents who were members of the church of England.
In his youth he was inclined to vanity,
but his mind being reached through the visitation of divine grace,
he was strengthened to take up his cross and despising the shame, to follow his Redeemer,
the Lord Jesus, in the regeneration.
When he grew up, he joined in fellowship with friends; and came to America in 1712,
being well recommended by certificate, though then a servant.
About the year 1728 he appeared in the ministry, first in a few words, but,
growing therein, his appearances were seasonable and savory,
and attended with a degree of that life which "`Makes glad the heritage
of God;`" being likewise serviceable in the discipline of the church,
according to his ability.

He began the world with little, but, being industrious,
and concerned for truth`'s prosperity, the Lord blessed his labors,
so that he lived comfortably and maintained his family reputably,
supporting the character of an honest, peaceable man,
and was often instrumental in restoring peace among others.
In his last sickness, being asked by a friend "`How it was with him?`"
he answered, "`If the messenger of death comes, I see nothing in my way.`"
Keeping mostly still and quiet, he, in a resigned, composed frame of mind,
and in the faith of the Lord Jesus, finished his course the 11th of the Seventh month,
1740, in the fiftieth year of his age; a minister about 12 years;
and was interred in Center burying ground.

[.asterism]
'''

THOMAS CHALKLEY was born in Southwark, London, the 3rd of the Third month, 1675.
He was descended of honest, religious parents,
who were concerned to bring up their children in the fear of the Lord,
often counseling him to sobriety, and reproving him for wantonness and levity,
so that he acknowledges he had cause to bless God, through Christ Jesus,
for their tender care over him.
Very early in life the Lord was pleased to visit him by his Holy Sprit,
and he felt it required of him, in tenderness and love,
to reprove those children who took the name of God in vain,
for which some mocked and derided him, but others, affected by his admonitions,
refrained from such evil language.
Having to walk about two miles to school, which was in the suburbs of London,
and being distinguished as a Friend by the plainness of his dress,
he had to endure much ill usage from wicked persons, by beating and stoning,
some of them telling him they thought it would be no sin to kill him.
These trials, however, he was strengthened to bear,
and as he grew in years he grew in grace, and in the knowledge of his Savior,
Jesus Christ.

On one occasion, while still a boy, being among some men,
he reproved one of them for his sinful conduct.
The man told the others of it, and charged Thomas with being no Christian,
asking him if he said the Lord`'s prayer.
Without making an immediate reply, Thomas asked him, if he said it.
The man replied, "`Yes.`"
"`I then asked him,`" says he, "`how he could call God, Father,
and be so wicked as to swear and take God`'s name in vain;
and told him what Christ said to the Jews, '`You are of your father the devil,
because his works you do;`' and those that did the devil`'s work could not truly call God,
Father, according to Christ`'s doctrine.`"
These remarks carried conviction to the minds of his hearers, who made no reply,
but wondered that one so young should speak in such a manner;
and his faithfulness afforded great peace to his own mind.
Although thus preserved in the fear of the Lord, he was sprightly and fond of play,
sometimes to excess,; and at one time, in the midst of his sport,
the Spirit of Christ so tendered and humbled his soul,
that he could not refrain from weeping.
But for lack of faithfulness to these convictions, and by giving way to levity,
he gradually contracted a fondness for sports and games,
which he practiced out of the sight, and without the knowledge, of his concerned parents.
He secretly bought a pack of cards, intending to amuse himself with them,
when he went to visit some gay relatives in the country; who,
though high professors of religion, yet indulged in the vanities of the world.
On the way there, he stopped at Wanstead meeting, where a Friend, a minister of Christ,
was led to set forth the sin of gaming in so forcible a manner
that it made a deep and lasting impression on his mind.
When he reached his relations, he found the priest of the parish there;
and in the evening, Thomas`' uncle called them all to come to their games at cards.
On hearing this, strong conviction seized his mind,
and he besought the Lord to keep him faithful to him, and raising his eyes,
he saw a bible lying on the window, which he gladly took up and began to read to himself;
rejoicing that he had strength to escape the snare.
His uncle, seeing his unwillingness to play, tried the others,
but none of them seemed inclined, seeing that Thomas was better disposed;
and for that time their sport was given up; and soon after,
he committed his new and unused pack of cards to the fire.

Being still mercifully followed by the strivings of the grace of Christ,
he was at times brought under much distress of mind
for his past unfaithfulness and disobedience;
and at one time was made to tremble greatly, hearing, as it were,
a voice saying intelligibly to him, "`What will become of you this night,
if I should take your life from you.`"
This brought anguish and fear upon him,
and he covenanted with the Lord that if he would please to spare his life,
he would be more sober, and live in his fear.
At length, being broken and deeply humbled under the power of the cross of Christ,
he was strengthened to cry to Him for help to keep his covenant;
and He who delights in mercy heard his prayer and granted his holy assistance.
Then he began to delight in reading the Scriptures of Truth
and meditating in the law of the Lord written in the heart,
and was separated from all his former sinful delights,
and became obedient to the will of God.

When about fourteen years of age he was disposed to shun the offense of the cross by
departing from the use of the plain Scripture language of Thee and Thou to one person,
for which he felt condemnation;
and at one time having some business with a great
man and officer in the neighborhood where he lived,
he felt much fear lest, through weakness,
he should prove unfaithful to what he knew to be right.
But the Lord helped him to be obedient, and the great man seemed at first much affronted,
saying sharply, "`Thou! what do you thou me for?`"
Thomas soberly asked him if he did not say Thou to his Maker in his prayers;
and whether he thought himself too great or too good to
be addressed in the same language which he used to the Almighty.
The man seemed affected, and made no reply, but ever after showed respect to Thomas;
who rejoiced that he had been preserved faithful.

About the twentieth year of his age,
he was impressed and carried on board a vessel belonging to a man-of-war,
where he was thrust into the hold,
and kept all night among a company of wicked and debauched men, without light,
or anything but casks to lie upon.
In the morning a lieutenant called him upon deck,
and asked him whether he was willing to serve the king.
Thomas replied he was willing to serve him according to his conscience, but that Christ,
in his excellent sermon on the mount, had forbidden wars and fightings,
and therefore he could neither bear arms,
nor be instrumental to destroy or injure his fellow men.
The commander of the vessel being appealed to in the case,
it was finally concluded to put him ashore; for which he was thankful,
enjoying peace of mind for his firmness in bearing his testimony against war.

As he advanced in years,
the cares of the world began to engage too much of his attention,
and the subtle adversary persuaded him that it was
lawful and necessary to be very diligent in business;
but He in whose presence and love he had been made to delight,
withdrew and deprived him of the sensible enjoyment of his favor,
by which he perceived that his course did not please the Lord,
and he was enabled to let the world go, rather than to lose the grace and favor of God;
believing that the Lord would not withhold any good thing from them that walk uprightly.

Humbly waiting upon Him in order to distinguish rightly between
the voice of Christ Jesus and the whisperings of Satan,
he grew in religious experience and knowledge; and before he attained to manhood,
he received a gift in the ministry of the gospel,
in which he diligently labored to turn people to the light of Christ in their consciences,
and to repentance and amendment of life.
Having entered on this solemn work, "`I had,`" says he, "`such a fear of dishonoring God,
that I often cried with tears, '`Never let me live to dishonor You!
Oh! it had been better for me that I had never been born,
than that I should live to dishonor You, or willfully reproach the name of Christ, who,
with the Father, is only worthy of Divine honor.`"

Soon after he was out of his apprenticeship,
he began to travel in the work of the ministry,
and visited many of the meetings of Friends in Great Britain; and in the Tenth month,
1697, with the unity of his brethren, he embarked for America,
in company with Thomas Turner, William Ellis, and Aaron Atkinson,
fellow-laborers in the gospel, to visit the churches in that land.
Having performed his religious service in those parts, he returned to England in 1699,
and the same year was married to Martha Betterton, s religious young woman,
who proved a help meet to him.
About the year 1700 they emigrated to Pennsylvania,
and settled in the city of Philadelphia;
and in the following year he made a religious visit to the island of Barbados,
in company with Josiah Langdale, and at times for many years after,
was engaged in similar service among friends in the American provinces.
In 1707 he visited the meetings of friends in England, Scotland, Wales, Ireland,
and in Holland and Germany, being accompanied from Philadelphia by Richard Gove,
who died while on the visit.
Soon after his return, he met with a severe trial in the decease of his beloved wife,
to whom he had been closely united, and who had a precious gift in the ministry,
and departed in much peace, and in near unity with her friends.
He had previously buried four sons and one daughter, all the children he had,
so that he was now left in a lonely condition; but was favored to bear these,
and many other afflictions, with Christian fortitude and resignation.

For some years he was almost constantly engaged in religious labors,
traveling extensively, and often employed his pen in the same blessed cause.
In 1714 he again entered into the married state; and meeting with heavy pecuniary losses,
engaged in business for the purpose of providing for his family,
and paying his just debts, which required him frequently to cross the seas,
either as master of vessels, or as supercargo.
These concerns, however, did not abate his godly zeal for the cause of Christ,
nor his religious care in visiting the churches,
and diligently occupying his gift in the ministry,
in which he was often drawn to those who might be considered
as the outcasts of Israel and dispersed of Judah,
endeavoring to gather them to the fold of Christ Jesus,
the everlasting Shepherd and Bishop of souls.

His patience was remarkable in disappointments and afflictions,
of which he had a large share; and his meekness, humility, and circumspection,
in his life and conduct, were conspicuous and exemplary;
and as he frequently exhorted others to the observation
and practice of the many excellent precepts of Christ,
our Lord and lawgiver, and more especially those in his sermon on the mount,
which contains the sum of our moral and religious duties,
so he manifested himself to be one of that number whom Christ compared to the wise builder,
who laid a sure foundation;
so that his building stood unshaken by the various floods
and winds of tribulations and temptations he met with,
both from within and without.

He was a lover of unity among brethren, and careful to promote and maintain it,
showing the example of a meek, courteous, and loving deportment, not only to friends,
but to all others with whom he had conversation or dealings;
so that it may be truly said, that few have lived so universally beloved and respected.
And it was manifest this did not proceed from a desire of being popular,
or to be seen of man;
for his love and regard for peace did not divert him from the discharge
of his duty in a faithful testimony to those that professed the truth,
that they ought to be careful to maintain good works.
He was often concerned zealously to incite and press
friends to the exercise of good order and discipline,
established in the wisdom of truth, by admonishing, warning,
and timely treating with such as fell short of their duty therein,
and to testify against those who, after loving and brotherly care,
could not be brought to a due sense and practice of their duty,
in consequence of which he sometimes incurred the ill-will and opposition of such.

In the Fifth month, 1741,
he acquainted his friends with a concern which had for some time attended his mind,
to visit the people in the Virgin Isles, more particularly Anguilla and Tortola,
"`in order,`" says he,
"`to preach the gospel of our Lord Jesus Christ freely
to those who might have a desire to hear,
as the Lord should be pleased to open my way.`"
Having their unity and certificates, he embarked,
and arrived at Tortola on the 12th of the Eighth month.
On the 15th he had a large and favored meeting, and another on the 18th,
which the governor of the island thought was the largest that had ever been held there.
Of this season he says, "`I was so affected with the power, spirit,
and grace of our Lord Jesus Christ, that when the meeting was over, I withdrew,
and in private poured out my soul before the Lord,
that he would be pleased to manifest his power and glorious gospel more and more.`"
He also visited many of the families, where the people collected,
being desirous of his company;
and many of these opportunities were favored with the Lord`'s power and presence,
tendering and solemnizing the spirits of those assembled.
In recording his exercises at this place, he says,
"`I cannot but note that the hand of the Lord God was with us,
and I felt his visitation as fresh and lively as ever; for which I was truly thankful,
and thought if I never saw my habitation again,
I was satisfied in this gospel call and religious visit.`"

On the Fifth day, the 29th of Eighth month, he was much indisposed,
yet went to the meeting, and after it was over, sent for the doctor, who,
finding he had a high fever, bled him, which afforded so much relief,
that he was able to go out on the following day.
The fever, however, returned, and continued for some days;
but being desirous of attending the meeting on First-day, he went, though very sick;
and was largely engaged in the ministry, with much brokenness and contrition, and,
as if he had a foresight of his approaching end,
solemnly closed his testimony with these words of the apostle Paul:
"`I have fought a good fight, I have finished my course, I have kept the faith;
henceforth there is laid up for me a crown of righteousness.`"
On the next day the fever abated; but soon returned again, and continued,
with but little abatement, until Fourth-day morning, the 4th of the Ninth month, 1741,
when he departed, we doubt not, to receive a crown of glory that shall never fade away.
He was aged about sixty-six, and a minister about forty-six years.

[.asterism]
'''

ROBERT JORDAN was born in the county of Nancemond, in Virginia,
the 27th of the Tenth month, 1693, of parents in good esteem among Friends,
and about the year 1718 he received a gift in the ministry,
as did his brother Joseph about the same time;
and to their first appearance in that weighty work,
the labors of Lydia Lancaster and her companion,
then on a religious visit from Great Britain, were, under divine help,
made instrumental.

Of his first travels in the service of truth,
the following is an abstract from an account committed to writing by himself:

[.embedded-content-document]
--

I early found a concern on my mind to visit Friends in Maryland,
which I did on both sides of the Chesapeake bay, in fear and trembling,
being young and weak, and the work very exercising, by reason of an obvious declension,
which occasioned me much exercise in speaking and writing against the spirit of liberty,
superfluity, and conformity to the world, for a testimony against which,
in many particulars, ancient Friends suffered much; but now,
with many is the offense of that cross ceased, and Friends`' sufferings are trampled upon,
to the great grief of my spirit, respecting tithes, apparel, etc.
And as the Lord has been pleased to commit a part of the ministry to me,
and of that part which is more necessary than desirable, in this age of the church,
he has been graciously pleased hitherto to furnish with a suitable ability for his honor,
and my faithful discharge of duty.
Before my appearance I was long under the concern,
being fully convinced it was required of me, but giving way to reasonings,
the suggestions and buffetings of Satan, I was likely to lose my condition,
had not the Lord been very gracious, who knew that I did not hold back obstinately,
but through human weakness, and contempt of myself for such a weighty service.
So, in a deep travail of soul once in a meeting, breathing for strength to bring forth,
I desired that the Lord would commit the hardest part of the work to my charge,
which I think was granted, and a hard travail I had in my first appearance.
But it fared otherwise with my brother, whom I prefer;
he was not disobedient to the heavenly vision, submitting speedily to the call,
and has been very prosperous hitherto;
may the Lord preserve us steady and faithful to the end.

After this, we travelled together in Maryland,
visiting Friends on each side of the bay, and at the yearly meeting near Choptank,
having meetings also on the way on our return,
and were frequently employed and zealously concerned in the Lord`'s work.
Blessed be his name who has called us out of darkness,
and with the day spring from on high visited our souls,
accounting us worthy of this high vocation,
even to hold forth the glory of this gospel day,
giving encouragement and enlargement of heart in
the mysteries and doctrines of his kingdom,
so that in the ability of divine faith, we frequently travelled about,
both in Virginia and Carolina, while young.
But as there is a diversity of gifts, so there is of operation,
according to the good pleasure of our great Benefactor,
and the emergency of times and occasions;
so let not us of the ministry imitate one another in this respect, but be careful,
dear friends, to keep to our true guide, the holy Spirit; for youth is warm, zealous,
and, without seasonable caution and watchfulness, apt to exceed ability and experience,
and so may be overstrained, and sustain loss and injury.

--

In the year 1722, he performed a religious visit as far as New England,
which employed him about ten months, and on his return home,
he was sued in the beginning of the following year for priests`' wages,
and for his refusal to comply with the demand, he offered to the magistrates in writing,
sundry considerations, which being taken amiss, he was, after some time,
indicted by the grand jury, and summoned before the governor and council.
In this time of trial he says, "`Some forsook me as being ashamed of my testimony,
and of my sufferings for it.
At my first appearance the fierceness of the dragon was felt,
his dark power seeming to be great and terrible,
as though he would have swallowed me up quickly,
and truth`'s adversaries seemed to rejoice, for I was made to stand like a fool,
for them to glory over me.
However, my mind being composed, and stayed in stillness on the Lord,
and with earnest breathings for Divine aid in this his cause, for which and myself,
I found it safest to say little at that time,
being greatly desirous that I might not give way one jot from my testimony,
through fear even of death itself;
for I thought I felt the bitterness of it strike at my natural life.

"`On the day when final judgment on the case was to be given,
I was brought before them the third time,
and they demanded what I had further to say before sentence was passed.
I then desired liberty to make my defense,
and to give my sense on the contents of my paper,
the commissary or chief priest having perverted my meaning.
This request the governor seemed disposed to allow, but it was afterwards denied,
as I apprehend, through the influence of the priest.
Howbeit, I told them I remembered to have read a proviso of the act of parliament,
that no man should be punished for any offense against the act,
unless he was prosecuted within three months after the fact; but this, said I,
was about seven months after.
But some of the court resolving on severity to induce me to submit,
they proceeded to give sentence of a year`'s imprisonment,
or bonds with security for good behavior, when, with a composed mind,
and an audible voice, I said, this is a hard sentence,
and I pray God to forgive my adversaries,
which affected several of the bystanders with tears, and one in particular, a judge,
and man of note.
He was much affected, made himself acquainted, and conversed with me more than once,
appears to be a tender man, and well convinced,
having since gladly received meetings into his house, and, as he has told me,
laid down his commission.

"`Being committed to prison, I was first placed in the debtors`' apartment,
but in a few days was removed into the common side, where condemned persons are kept,
and, for some time had not the privilege of seeing any body, except a negro,
who once a day brought water to the prisoners.
This place was so dark, that I could not see to read even at noon,
without creeping to small holes in the door; being also very noisome,
the infectious air brought on me the flux, that,
had not the Lord been pleased to sustain me by his invisible hand,
I had there lost my life.
The governor was made acquainted with my condition,
and I believe used his endeavors for my liberty.
The commissary visited me more than once under a show of friendship,
but with a view to ensnare me, and I was very weary of him.
I wrote again to the governor, to acquaint him of my situation; so,
after a confinement of three weeks, I was discharged,
without any acknowledgment or compliance, and this brought me into an acquaintance with,
and ready admittance to the governor, who said I was a meek man.
Thus I returned home with praise and thanksgiving in my heart to the Lord,
who had caused his truth to triumph over the strong
efforts of man and the powers of the earth.`"

In the year 1725, accompanied by Thomas Pleasants, he again visited friends in Maryland,
and the yearly meeting near Choptank.
My concern here (he says) "`Was principally to labor
for the restoration of wholesome discipline,
the neglect whereof I conceive has been a great cause of the disorder
and undue liberty prevailing among the professors of truth there.
When the service of this meeting was over, we visited the meetings on the western shore;
and returned home,
having left an example of that useful and necessary practice of visiting families,
joining friends therein for some time; we are, thanks be to God,
come and coming into the same in Virginia, which, with some assistance,
I have pretty generally performed through our monthly meeting, and never I think,
was more sensible of the company and ability of +++[+++the Spirit of]
truth in any service, according to the dignity of it.`"

A malicious person getting into his possession the judgment
obtained against him for the demand of tithes before mentioned,
had seven of his cattle seized and appraised,
but deferred taking them away until about two years after,
when he procured a new action against him, alleging, but not proving,
that Robert had converted at least a part of them to his own use.
He so managed the matter in his absence, as to make the debt amount to twenty pounds,
though the demand was but eight pounds, and serving the execution on his body,
he was again committed to prison in the Twelfth month, 1727, where,
being confined fifteen weeks, he was at length discharged,
without any person paying any thing for him, which he would not allow.

Soon after he was brought under a trial, with others of his friends,
by the operation of a militia-law,
whereupon they addressed governor Gooch on his arrival,
representing to him their sufferings by spoil of goods and imprisonment, which,
with the friends who attended on the occasion, he received with kindness.

"`Having this year, he remarks, suffered persecution in body and estate,
as a preparative to a greater affliction, all which does and will work for good, my dear,
affectionate wife was called away.`"

The next year, 1728, he embarked for Great Britain, with our friend, Samuel Bownas,
who had accomplished his journeys on this continent in the service of the gospel;
and after performing a religious visit to the meetings of friends in England, Scotland,
Wales and Ireland, he proceeded to Barbados,
and arrived from there in the city of Philadelphia, in 1730, then went to Virginia,
and in the same year performed a visit as far eastward as Rhode Island,
accompanied by his intimate friend, Caleb Raper, of Burlington.

The following year, marrying with Mary, the widow of Richard Hill,
he became a member of the monthly meeting of Philadelphia,
and after a visit to the meetings of friends in Maryland and Virginia,
he embarked on a second visit to Great Britain,
from which he returned in the summer of 1734, between which time and the year 1738,
he performed another visit eastward, and three to the southern provinces,
besides one to South Carolina and Georgia.
From there he proceeded to Rhode Island, and to Boston,
and in 1740 he went on a second visit to Barbados, and in the succeeding year,
accompanied by Caleb Raper, he accomplished his last visit eastward as far as Boston.

Hereby we may observe his unwearied application and exercise,
to fulfill the ministry which he had received of the Lord.
Though his time was much employed in his religious duties abroad,
he did not omit the adjacent meetings,
being industrious and laborious for the general welfare and prosperity of the churches;
for the promotion whereof he was, through the divine anointing, eminently qualified.

His ministry was convincing and consolatory, his delivery graceful but unaffected;
in prayer he was solemn and reverent; he delighted in meditation,
recommending by example religious retirement, in his familiar visits among his friends.
In his sentiments he was generous and charitable,
yet a firm opposer of obstinate libertines in principles or practice,
demonstrating his love to the cause of religion and righteousness above all other considerations,
being careful to adorn the doctrine of the gospel by a life of piety and benevolence;
and we have ground to hope and believe he was prepared for.
the sudden`' summons from his pilgrimage here,
which was on the fifth day of the Eighth month, O. S. 1742.

Being at the house of one of his most intimate friends
on the third day of the week in the morning,
waiting for the hour of meeting, he was seized with a fit of apoplexy,
which very soon deprived him of speech, and he died about midnight following,
in the forty-ninth year of his age, being a minister about 24 years.
His burial on the 7th of the same month was attended by a great number of his fellow-citizens,
to the meetinghouse in High street, and from there to the graveyard.
