[#catherine-payton, short="The Life and Letters of Catherine Payton"]
== Selection from the Life and Letters of Catherine Payton

As the dealings of the Almighty with me from my youth have been singular,
and are worthy to be retained in remembrance with thankfulness,
I have committed to writing some remarkable circumstances of my life,
which I hope will awaken future thanksgiving and watchfulness in myself.
And considering how wonderfully the divine arm has been manifested for my help,
I desire that the penning of these lines may encourage me to steadily trust therein,
and to persevere in submission thereto.
A concern also rests upon me to leave to my surviving relations some memorials
of the various exercises and dangers which I have passed through,
and of the merciful support and preservation graciously bestowed upon me by the Lord.

But first, it appears proper for me to leave a short testimony to my parents,
who not only professed the Truth, but also had it in possession.
My father, Henry Payton, of Dudley in Worcestershire, son of John and Catherine Payton,
respectable members in the Society of Friends,
was called into the work of the ministry about the eighteenth year of his age.
When young, he travelled much in the service of Truth in many parts of this nation,
Ireland and Scotland, as also in the American colonies;
and from the testimonies of Friends,
I have good reason to believe that his services were
truly acceptable and edifying to the churches.
His ministry was living and clear,
and it was his great care never to exceed the openings of Truth made manifest to him.
His deportment was grave, his conduct clean and steady,
and his charity in proportion to his circumstances was extensive.
He was an affectionate husband, a tender father, and a kind master;
serviceable amongst his neighbors, and beloved and respected by them.

Many years before his decease,
he was disabled not only for public service in the ministry,
but for acting in the private duties of life in providing for his family,
being afflicted with a paralytic disorder under which his faculties gradually gave way.
I was often his companion in his long weakness, reading to him and attending upon him;
and I can give this testimony respecting him:
that he retained the savor of the divine life to the end;
and frequently manifested a true spiritual concern for his children,
and particularly for me his youngest child and tenderly beloved by him.
When his speech faltered so that he could articulate but little, he would yet often say,
"`The Lord bless you my children.`"
In the seventy-fifth year of his age he was released from his affliction,
and I doubt not has entered into everlasting bliss.

My mother was the daughter of Henry and Elizabeth Fowler, of Evesham in Worcestershire.
She was a religious woman, endued with a strong and steady understanding,
and many remarkable virtues, whereby she was fitted for the role she had to play in life.
The Lord greatly blessed her endeavors for her children,
and I doubt not heard her prayers that "`the dew of heaven might rest upon them.`"
She would say, she desired not great riches for her children,
but that they might dwell in the fear of God.
Her steady and strong marital affection was manifested during my
father`'s long indisposition by her tender attention to him;
and after his decease,
by her frequently mentioning him in terms which evinced that their
union was founded in that love which death cannot dissolve.
She said that when she married him,
she was so far from being intimidated at the thought of
his leaving her to travel in the work of the ministry,
that she entered into a solemn covenant with the Lord,
with a resolution to do her utmost to set him at liberty in such services.
And when it pleased divine Wisdom to deprive her
of a husband whom she might offer up to His service,
she was desirous that at least one of her offspring might be called to the ministry.
This was fulfilled in me, whom she tenderly loved; but,
I believe she as freely dedicated me to the Lord as Hannah did Samuel,
and was always ready to put me forward in His work;
though she was always careful that I might not run before my Guide.
And although, after I was called to the ministry,
it was often my lot to be absent from her, yet she never repined at it,
but frequently encouraged and incited me to faithfulness;
so that among the many mercies bestowed upon me by bounteous Providence,
I may justly number as not the least, having such a parent as she.

She was an affectionate mother to all her children,
yet very discerning of their faults and quick to reprove them;
not indulging them in the time of their childhood,
but raising them to be industrious and diligent.
Truly, she was an example of fortitude, cheerfulness, gravity, hard work, economy,
self-denial, and resignation to the divine will.
She was generous to her friends;
her house and heart were always open to receive the Lord`'s messengers,
for which she would say she thought a blessing was dropped upon her family.
She was charitable to the poor;
choosing rather to save from other expenses so that she might have more to give away.
She died in the ninety-first year of her age;
and retained a considerable degree of soundness of judgment
until near the close of her useful and careful life.

Having descended from such parents,
it may be supposed that I was in the way to receive religious instruction from my infancy;
and indeed I cannot date the first dawning of divine light upon my soul.
With humble thankfulness I may say,
that early in the morning of my life I knew the Lord to be a God near at hand,
who convinced me of evil,
and raised longings after the saving knowledge of His divine love and power.

Friends who travelled in the ministry usually lodged at my father`'s house.
I loved their company when very young,
and their tender notice of me I commemorate with gratitude.
Here I may remark,
that if our youth today would prize the company and conversation
of those whose "`feet appear beautiful upon the mountains`"^
footnote:[Isaiah 52:7; Romans 10:15]
of salvation, and who have had great experience of the love of God,
they might very much profit thereby.
But, alas! how often do some in our day avoid the company of solid and discerning ministers,
scarcely giving them an opportunity of manifesting to them
the tender affection wherewith their spirits are clothed;
being probably afraid of reproof, on account of their indulging liberties in the flesh,
contrary to the pure liberty of Truth.
Such reproof they think hard to bear,
even though it be given in that love which seeks the true happiness of their souls.

I could read well when very young, and spending much time with my afflicted father,
I read often to him.
The experiences and sufferings of faithful martyrs, and of our early Friends,
with the accounts of their glorious exits out of
time in full assurance of everlasting bliss,
made profitable impressions upon my mind.
Indeed, my spirit was often made tender thereby,
and my love of virtue and piety was strengthened,
so that I may truly say of such holy persons, that "`though they are dead,
yet they speak.`"^
footnote:[Hebrews 11:4]
May their voices be heard by the youth of the present and succeeding generations,
and incite them to shun the paths of vanity,
and to follow the footsteps of Christ`'s companions.

But, notwithstanding these promising beginnings,
as I grew up I yielded to various temptations,
so that the evil propensities in nature got the ascendency,
and I was allured away from the simplicity of Truth.
But even in my childhood I experienced many conflicts,
and my convictions for evil were strong;
so that at times my heart was sorrowful and my pillow was watered with my tears,
although my countenance and deportment were mostly cheerful.
Once, having yielded to temptation,
my sense of guilt was so great that I concluded I had sinned against the Holy Spirit,
and so, agreeably to Christ`'s testimony, I "`should not be forgiven,
either in this age or in the age to come.`"^
footnote:[Matthew 12:32]
This so affected my tender mind with sorrow and unutterable distress,
that it could not be entirely concealed from the family; although I was enabled,
even in childhood, to keep most of my inward exercises to myself.
I think I must have been about eight or nine years old when I was in this condition,
and because in childhood I was several times visited with fevers,
which brought me very low,
I was led to consider whether I was prepared for the awful change with which I was threatened.
A weighty sense then rested upon my spirit that my soul was not
pure enough for admittance into Christ`'s holy kingdom.

Sometimes I would covenant with the Lord to be more
circumspect and watchful for the future;
but my careless natural inclination would again get the ascendency,
and make fresh occasion for repentance.
My natural disposition was very volatile, and my comprehension quick;
and as my faculties further opened,
I delighted much in books of a very contrary nature and
tendency to those which had engaged my attention in childhood.
I had a near relation, who,
notwithstanding his having been favored with a divine visitation in his youth,
had slighted his soul`'s mercies and pursued lying vanities.
He kept a house in the same town; and through him,
myself and my sisters had opportunities of obtaining plays and romances,
which I read with avidity.
I spent enough time at his house as to be introduced into
amusements very inconsistent with the simplicity of truth,
and with my former religious impressions.
Indeed, my state then was indeed very dangerous,
and were it not for the interposition of divine Providence,
I had been left to pursue a course which must have terminated deplorably.

I also read history, was fond of poetry, and had a taste for philosophy;
so that I was in the way to "`embellish my understanding,`" as the saying goes,
and become more accomplished in my conduct;
which might have tended to feed the vain and proud nature,
render me pleasing to those who lived in it, and make me conspicuous in the world.
But the Lord, in His wisdom,
had a design to bring me into public view in a way directly opposite to worldly wisdom,
pleasure, or honor.
And when He was pleased to more fully open my understanding concerning
His great and glorious work of renovation of spirit,
I saw that I must desist from these publications
and studies and pursue the one thing necessary,
namely, working out the salvation of my immortal soul; and truly,
I esteem it a great mercy that I readily attended to this intimation.

However lawful it may be, in proper seasons, to look into the works of nature,
and become acquainted with the history of former or present times,
my attention was now powerfully attracted to higher subjects;
and had I pursued those lower things,
I might have become as a "`vessel marred upon the wheel.`"^
footnote:[Jeremiah 18:4]
Alas, this is the case with many who have been divinely visited, but who,
not deeply and steadily attending to the instructions of pure wisdom,
but seeking to be wise and learned in matters which merely relate to this present world,
have not advanced in the simplicity of divine knowledge.
And although it has remained obvious that the Lord`'s hand has
mercifully moved upon some of these to form them for His service,
yet they have not grown up to that degree of usefulness
in Christ`'s church which they might have attained,
had they passively submitted to the turnings of His preparing hand.
Were the sons and daughters of our religious Society,
who are favored with good natural understandings, clothed with heavenly wisdom,
they would then become and appear truly great in the dignified
simplicity and humility of the service of the King of kings.
Human knowledge and acquirements too often puff up the minds of youth; and indeed,
some who are of more advanced age also pride themselves in these things, when,
as examples to the rising generation, they should be clothed with humility.

It was observed of a truly honorable member of our favored Society,
that "`he was a divine and a naturalist, and all of God Almighty`'s making.`"^
footnote:[William Penn`'s account of George Fox.]
I have read very little natural philosophy,
and am not in a place to boast of my acquired knowledge of either human, natural,
or divine things; but I may say,
that I have often admired how by one gleam of heavenly light the
understanding can be opened into natural things so as to behold,
as in one glance, the general economy of the divine Former of all things,
as it is displayed in the outward creation.
This produces adoration to Him under the humbling sense of His power, mercy, and wisdom,
along with great admiration for His works, seeing that they are indeed marvelous,
and in their full extent incomprehensible.
Therefore,
let not the faculties of His adopted children be improperly occupied
in exploring these outward works in any way that might prevent
an advance in their various stations in His militant church;
for when happily their souls are fixed in the triumphant One,
they will know enough as to forever inspire the angelic song,
"`Great and marvelous are your works.
Lord God Almighty, in wisdom have you made them all!`"

From these remarks I return to my education, which, while I was at home,
had not been entirely neglected as far as it pertained to useful and necessary learning.
However,
as the afflicting circumstances of our family had caused me to be kept
pretty closely there until I had attained my sixteenth year,
my mother then concluded to send me to London,
and put me for one year under the care of Rachel Trafford.
She, together with her sister, kept a respectable boarding-school,
and my mother had no doubt of their kind attention to me,
for when young Rachel had spent a considerable time in my father`'s family.
She was affectionately kind to me, and, both as a minister as well as a mistress,
I believe her mind was frequently exercised for the spiritual improvement of her students,
which at times was manifested by verbal supplication for them,
as well as by appropriate advice and reproof.

I improved much in the time I stayed in the school,
and my school-fellows behaved well towards me;
but being so far advanced towards maturity, tall, and proportionally grown for my age,
I looked rather too much like a woman for a boarding school.
Yet some of my school-fellows were older than myself,
which I believe increased my mistress`'s anxious concern for our preservation,
we being (to use her own expression) more like a "`school of women.`"
I was most intimately acquainted with my mistress`'s niece, who acted as a teacher,
and with one of the students--a sensible, agreeable, well-behaved young woman,
but not of our Society,
who was admitted into the school to qualify herself in needle-work,
and for a school-mistress.
As neither of them were much under the influence of true religion,
I did not profit in the most essential respect by my fellowship with them.
But after I had been a few months in the school,
I was favored with a renewed visitation of divine love,
and began to grow uneasy with my situation.
Home became desirable, although I knew it to be a house of affliction;
and upon my intimating this to my dear mother,
my brother James came and fetched me there,
sooner than my mother had intended when I left her.

Thus far I have commemorated the dealings of the Almighty
with my soul manifested principally in tender mercy;
but now the day was coming wherein His righteous judgments would
be manifested against all that was high and lifted up in me,
and opposite to His pure Spirit.
In this day,
my wanderings from Him (the Shepherd of Israel) were brought to my remembrance,
and my sins were set in order before me.
Indeed, this wrought great humiliation and brokenness of heart,
with strong cries to Him that He would graciously pass by
my transgressions and receive me into covenant with Himself.
Although this dispensation was not agreeable to degenerated nature, which,
like Adam when he had transgressed, seeks to evade the condemnation; yet,
because of the glory which I knew lay beyond it, and the divine love which I saw therein,
I said, in the secret of my soul, "`It is good for me to be under it.`"
I was made willing to patiently abide the judgments of the Lord for sin,
in order that I might witness remission thereof through the baptism of repentance,
and the sanctifying life or Spirit of His Son Jesus Christ.
And this mercy (in the appointed season of infinite wisdom) I at last experienced;
so that my past transgressions were blotted out of the book of remembrance,
upon the terms of my future and steady perseverance in the fear of God.
And in the discernible triumph of divine mercy over judgment,
my soul rejoiced with humble thankfulness.

Yet just as the children of Israel who were delivered out of Egypt,
and then travelled through the wilderness,
found new trials of various kinds to encounter,
insomuch that they thought their sufferings rather increased than diminished,
and frequently feared perishing in that desert land; so too I found that,
being relieved from the oppressive weight of past actual transgressions,
I had to travel on to attain the saints`' promised inheritance,
which is a state of real establishment in righteousness.

I soon found myself in many deep baptisms and exercises of faith and patience.
I was brought to look into my own heart, which,
by reason of the irregularity of its passions and inclinations,
might well be compared to an uncultivated wilderness, through which I saw I must travel,
and in which I must receive the law for the ordering of my outward conduct.
Oh, the seasons of hunger and thirst, the tossings and perplexities, the "`thunderings,
lightnings, and tempests,`" which I had to pass through in that day,
all of which seemed to threaten my destruction!
These are to be held in everlasting remembrance,
with thanksgiving to that divine hand which preserved me from being so far dismayed
at them as to look back with a desire to return to that country,
or condition, from which I happily escaped.
The adversary here transformed himself as into an angel of light, and,
under the specious appearance of righteousness,
represented the way so narrow that it was impossible
to walk therein and still act as a rational being.
Hereby he endeavored to discourage me,
or prevent my attaining to the true gospel liberty in the use of created things,
and in the course of my conduct.

Indeed, in this season of deep distress, both the "`earth and heavens were shaken.`"
Some of those religious principles which I had received
by education were called into question,
and I was left without any foundation of certainty respecting them;
nor could I attain such a certainty by the testimony of others,
or by the writings of those who had vindicated them to the world;
being made to receive my convincement of truth from
the deep and sure ground of divine revelation.

I have seen that all of this was necessary to fit
me for the service which was appointed to me,
so that the foundation of my faith might be laid in certainty,
and that I might be able to testify with boldness that I
had _experienced_ what I asserted to be the truth;
and also be suitably qualified to sympathize with, and minister to,
those who were in similar states.
I saw early for what station I was designed in Christ`'s Church.
My soul received this manifestation of the divine will with a good degree of resignation;
nevertheless, until the Lord`'s time for putting me forth in His service had come,
I was frequently assaulted with fears, lest it should be required of me at such a time,
or in such a manner, as would be doubly hard to flesh and blood.
The adversary was also very busy with his presentations,
intending thereby either to discourage my mind from pursuing its proper duty, or,
by hurrying me into what had a false appearance thereof,
in order to bring me into confusion.

But, in all these "`voices of the stranger,`" there was a lack of that certainty which
I had concluded should attend such a manifestation of the divine will,
and which I was happily led to look for.
And at length I was strengthened to covenant with the Almighty,
that whenever the evidence was clear and strong, I would submit thereto.

And here it may not be unprofitable to remark,
that some minds are perhaps more liable to struggle with these things than others.
Those who have a strong and quick imagination,
and whose hearts have been deeply affected with the exceeding sinfulness of sin,
and of the love of God to mankind;
whose desires are strong that the one might come to an end,
and the other abound in the earth--it is difficult for these at all times (especially
when young in religious experience) to keep in the quiet habitation where alone the
voice of the true Shepherd is to be heard and distinguished from that of the stranger.
But as the will becomes gradually resigned to the will of God,
and the imagination in its natural working is silenced,
and the soul comes more constantly to worship in the Lord`'s temple,
the adversary in these false appearances is bound; or if he is permitted to present them,
there is strength acquired to stand still and try the spirits.
This I have seen, in the light of Truth,
to be absolutely necessary before we move forward in the Lord`'s service.
And the lack of this has been productive of much confusion,
and has been a cause of great reproach on our high and holy profession,
to such who are seeking an occasion to lay waste the belief in divine revelation.

But to return: Having come to the aforesaid state of resignation,
I waited quietly to discern the puttings forth of the divine hand in a state
of earnest prayer that I might not be permitted to move before the proper time.
This, I have good ground to believe, was heard and answered;
and from the motion of divine life I was constrained to
supplicate the Almighty in our little meeting at Dudley,
the tenth day of the second month, 1748,
having then newly entered the twenty-second year of my age.

May all of the Lord`'s children whom He appoints to the solemn and important
service of the ministry humbly and patiently wait to know when to move therein;
for through neglect of this,
some have stepped into it before they have fully passed
through the dispensation of preparation for it;
and, if ever they have become strong in His service,
they have first had to continue long in a state of weakness.
Yet let none despise "`the day of small things.`"^
footnote:[Zechariah 4:10]
A few words spoken under divine direction are often blessed to
those to whom the Master of the solemn assemblies directs them.

I continued to minister as the Lord was pleased to give me ability,
in great brokenness of heart, and for a time I spoke but a few words a time;
for great fear was upon my spirit lest I should minister in the wisdom of the creature,
which always brings death and begets its own image.
In a sense of this danger,
strong were my cries to the Almighty that what I
handed forth to the people might be unmixed,
let it appear ever so simple or despicable in the view of the worldly-wise and learned.
And as I continued to move in the ministry in fear and trembling, the Lord was with me.
In time He enlarged my understanding and increased my service in the openings of Truth,
at which His people rejoiced, and, in obedience to His requirings, I felt sweet peace.

Yet my spirit was frequently in heaviness,
being humbled with many deep exercises which I found profitable to establish it in righteousness,
although they were painful to nature.
I leave it as an observation, that I have seldom, if ever, seen anyone continue,
and arrive to any considerable degree of usefulness in the Church,
whose foundation has not been deeply laid in afflictions and exercises,
whereby they are crucified with Christ,
and shall therefore rise with Him to glory and honor,
both in the present as well as in a future state.
But in all my afflictions and deep baptisms, the Shepherd of Israel was with me,
and preserved and supported my spirit to the honor of His own name,
to whom alone I could attribute the praise.
For in those allotted days and years of tribulation,
very little instrumental help was afforded me;
my lot being cast in a quarter where there were none near
who were capable of giving me much assistance or wise counsel,
not having trodden in the same steps.
I sometimes thought my case was hidden from some of the
Lord`'s servants who were concerned to visit His heritage;
or else that they were in part restrained from ministering to my condition;
and my tongue was much sealed in silence, for my exercises were unspeakable.

All this I saw to be of excellent usefulness,
as the contrary might have led me to a dependence
upon the Lord`'s servants (which ever brings weakness),
or been productive of confusion,
through my imparting my case to such as were not skillful enough to minister to it,
but who nevertheless might have given counsel therein.
I have seen it to be profitable and necessary for such as are in
a state of infancy in religion to dwell with their own exercises,
leaning simply on that Arm which alone is able to carry through them; and,
until the mind has acquired a depth of judgment to
distinguish clearly who is on the Lord`'s side,
to be very cautious to whom they communicate their trials,
lest they be wounded by discovering that those whom they have chosen for their friends,
prove to be enemies of the cross of Christ.
Yet when, in times of great difficulty,
the Lord directs to seek counsel from one of His experienced servants,
this will undoubtedly be advantageous.
Indeed, a steady,
sympathizing friend is a great strength and blessing when afforded in divine wisdom.

[.asterism]
'''

[.offset]
+++[+++__Note from Editor:__ At this point in her journal,
Catherine Payton commenced a detailed account of her travels in the work of the ministry,
which services occupied her almost continually for the next twenty years of her life.
Though there is much interesting biographical information and many
instructive anecdotes to be found in the accounts of these journeys,
it was thought that, for the purposes of this shorter publication,
a sample of her letters might present the reader with a clearer
view into the life and worth of this extraordinary woman of God.

The first letter was written to young Rebecca Jones^
footnote:[Rebecca Jones became a beloved minister in the Society
of Friends who was regarded by all who knew her as a meek disciple, a gifted preacher,
a loving "`mother in Israel,`" and a shining example of every Christian virtue.
Her diary and letters are available on www.friendslibrary.com.]
during Catherine Payton`'s long ministerial journey
in the American Colonies between 1753 and 1756.
An excerpt from Rebecca Jones`' journal is included
in order to give context to the letter that follows.]

[.offset]
Rebecca Jones writes:

[.embedded-content-document]
--

In the year 1754, and in the 16th year of my age,
there came from old England on a religious visit to the churches of Christ in America,
Catherine Payton, in company with Mary Peisley from Ireland.
I was at several meetings in this city with Catherine Payton,
and heard several testimonies which she bore, with which I was much pleased;
but like many others, I only _heard,_
and sought not to learn the way of salvation in sincerity.
But, forever blessed and praised be the great Minister of all ministers,
and Bishop of souls,
who in His abundant compassion to a poor creature
on the very road that leads to the chambers of death,
was graciously pleased through this handmaid to set
my state and condition open before me.
Indeed, He enabled her, in one of our first-day evening meetings,
to speak so pertinently to my situation,
in showing the consequences of trifling with Divine conviction,
and proclaiming God`'s love through Christ to all returning sinners,
that I cried out in the bitterness of my heart, "`Lord,
what will you have me do to be saved?`"
And so effectually was my heart reached,
that I was made willing to forsake everything here to obtain true peace; yes,
my natural life would not have been too great an offering, if it had been required,
that I might have inherited eternal salvation.

Oh, then the many days of sorrow and nights of deep distress that I passed through!
How frequently did I cry out, "`Lord, save me or I perish!`"
I almost despaired of finding mercy, for not only did "`sin appear exceedingly sinful,`"^
footnote:[Romans 7:13]
but my soul`'s enemy almost persuaded me that my sins were of so dark a color,
and had been so often repeated, that I had neglected the day of my visitation;
and that now, though like Esau I might seek the blessing with tears,
I could not obtain it.

But, forever magnified be the kindness and goodness of the Lord my God,
the everlasting Father; for He left me not here,
though I was in the situation described by the prophet Ezekiel: I was greatly polluted,
and lay wallowing in the filthiness of the flesh,
without any help from my earthly connections, and a stranger to the Lord`'s family.
Indeed I was "`not washed with water, nor rubbed with salt,
but cast out as into an open field, void of any enclosure; no eye pitied me,
to do any of these things to me.`"^
footnote:[Ezekiel 16:3-5]
But when the sure Helper passed by, He beheld me in my deplorable situation,
cast His mantle of Divine love over me, and with a most powerful voice said, "`LIVE--yes,
He said unto me--LIVE.`"^
footnote:[Ezekiel 16:6]

I was again encouraged by the renewal of divine favor to enter into solemn
covenant with that gracious Being against whom I had so highly rebelled,
and whom I had so justly offended;
and fervent were the breathings of my soul that I might be enabled to
stick close to the terms of the covenant made in this the day of my humiliation.

My love to this instrument in the Lord`'s hand +++[+++Catherine Payton]
was very great; and on a certain time, being reduced very low in my mind,
under the consideration of my many and deep transgressions,
I took up my pen and opened a little of my condition to her,
though I was afraid to sign my name to it.
I watched for an opportunity and then slipped it into her hand,
just as she was going into a meeting,
and in two days after I received (by the hands of
one of her friends) the following answer,
which,
as it had a blessed effect in encouraging my mind
reverently to confide in the Lord`'s infinite mercy,
I here transcribe at large.
On the receipt and reading of this letter my heart
was melted into great tenderness before the Lord,
and my mind encouraged to trust in His boundless mercy, thus extended to me, a poor,
unworthy creature.
Perhaps the reading of it may revive the hope of some afflicted soul.

[.letter-heading]
Catherine Payton to Rebecca Jones

[.signed-section-context-open]
Philadelphia. 4th month 1st, 1755.

[.salutation]
Dear Child,

I have carefully read your letter, and,
from a tenderness of spirit which I feel towards you,
conceive much hope that you will do well,
if you keep close to that Power which has visited you.
Which, as it has already appeared as a light to convince you of sin, will also,
if you will permit it, destroy it in your heart.
This dispensation having already begun is the reason
of that anguish of spirit which you feel,
which will lessen gradually as you are assisted to overcome.

And be not too much discouraged, neither at what you have committed against the Lord,
nor at what you may have to suffer for Him;
for though your sins may have been as scarlet,
He is able and willing to make your heart as snow,
upon your sincere repentance and humble walking in His fear,
and also to give you strength to do whatsoever He commands you.

If you are willing and obedient for the future,
you shall eat the good of the land in the Lord`'s time, and,
as you have already been instructed that "`you shall only receive
consolation as you are fit for it,`" therefore wait patiently,
and let the administration of condemnation be perfected,--so shall
the administration of Light and Peace be more clear and strong;
which will assuredly come upon you,
if you abide faithful to that Power which has visited you.

You desired me to explain some portions of Scripture
to you that I mentioned in the meeting,
which I am willing to do as far as the mentioning of them concerns your
state--which I believe was to awaken watchfulness and care over your conduct,
that your soul may bring forth the fruits of purity and love to God,
which will be manifested only by your obedience;
and also that you may not rest in anything short of the knowledge
of His Power revealed in your heart as a refiner and teacher,
nor place your happiness in anything short of the experience of His salvation.

I go out of town tomorrow, and not knowing your name by your letter,
know not how to get to speak to you.
I have therefore committed the care of this letter to Anthony Benezet, who, I believe,
will use his utmost endeavors to convey it to you.

Farewell; and may the Lord continue to bless you.
I conclude, in much haste, your sympathizing friend,

[.signed-section-signature]
Catherine Payton.

[.postscript]
====

P+++.+++ S. I had rather you keep this to yourself; and be sure,
be careful how you tell your condition to such as have no understanding of it.

====

--

[.asterism]
'''

[.offset]
+++[+++The following letter was written by Catherine Payton
and addressed to a group of people at Cardiff, in Wales,
who had in part relinquished their former profession of
religion and sat down together to wait upon the Lord,
but who remained in an unsettled state.]

[.embedded-content-document.epistle]
--

[.blurb]
=== To the few who have been convinced of the rectitude of waiting upon the Lord in silence, and accustomed to meet for that good end, in Cardiff.

[.salutation]
Friends,

In the love of my heavenly Father, joined with a sense of duty,
I am engaged to salute you in this way,
desiring your steadfastness in the unchangeable Truth,
that being grounded in right faith,
you may not be carried away with every wind of doctrine, but in stability of mind,
may be able to distinguish between what proceeds pure from the Fountain of wisdom,
and what is mixed with human policy and the traditions of men,
which tend to alienate the mind from the simplicity
of gospel worship and fix it in outward performances,
amusing it with bodily exercises which profit but little.

By this means, many times, that tender spiritual sensation,
with which the soul (in the infancy its religious experience) is blessed,
is in measure lost, and the understanding becomes clouded.
The mind then is either plunged into a labyrinth of thought,
or is exalted above that meek childlike state in which the
humble followers of the Lamb delight to abide,
because therein they are capable of knowing His voice from that of a stranger,
and receiving strength to follow Him through the several
dispensations of probation that He is pleased to allot them.

Many times since I saw your faces have I looked towards you,
and I wish I could say I have beheld all keeping their habitations in the Lord.
But alas, instead of this, has there not been a swerving aside,
and building again that which you had taken some good steps towards abolishing?...which,
says the apostle, causes whosoever does so to make himself a transgressor.^
footnote:[Galatians 2:18]
May I not query: "`How long will you falter between two opinions?`"^
footnote:[1 Kings 18:21]
I believe this to be one cause of your weakness, and I fear, if persisted in,
will prove your destruction.

I believe it was the merciful design of the Almighty
to redeem you from a dependency upon man,
and to bring you to wait for the immediate teachings of His Spirit,
and to confide in His power from a living sense of its sufficiency.
And had you simply followed Him,
His Almighty arm would have been exalted in the bringing down of your enemies,
and the enlarging of your understandings,
so that you would not only have seen that there is such a thing as light,
but the miraculous cure of your blindness would have been perfected,
and in the light you would have discerned objects clearly.
Here you would have grown in Christian experience,
and having received the holy anointing, and abiding under it,
you would have found that you had need of no man to teach you,
for this anointing was sufficient to instruct in all things.
And here you would have been enabled to distinguish between words accompanied with,
and those without, the power of God,
by the different effects which each had in the soul--the
one tending to make alive unto God,
and the other tending to bring death over the spiritual life.

According to the nature of things,
a ministry that comes not from the life of the gospel can only beget its own likeness.
It may fill the head with notions, but it can never replenish the soul with grace.
And as it is the business of the enemy to delude the judgment with false appearances,
he will endeavor (by puffing up the mind with vain ideas)
to make a likeness of the effects or fruits of the Truth.
Thus, when the head is stored up with knowledge,
and Christianity is partly understood in theory by the working of the imagination,
then the poor deluded creature may boast of visions and enjoyments, and,
soaring upon the wings of deception, may abound in rapturous expressions.
But though he may talk of God and Christ from morning till evening,
he is but "`warming himself at a fire of his own kindling,`"^
footnote:[Isaiah 50:11]
being destitute of the real efficacy of grace.

Truth has a natural tendency to humble all the faculties of the soul,
to make it "`rejoice with trembling,`"^
footnote:[Psalm 2:11]
and to clothe it with meekness, resignation, and contrition.
In this state it seeks to repose itself on the breast of the Beloved;
or in silent adoration to bow before His throne,
and in tenderness pour forth itself in mental prayer, or praises;
and if it addresses Him verbally in the congregation of His people,
it is with the greatest reverence and humility,
knowing that it is presumption to do so apart from the moving of His Spirit.
And if the soul is long deprived of His presence, it seeks Him in sorrow;
but as it advances in experience,
it is cautious of disclosing its condition (as in
the night) to the various reputed watchmen;
lest by unveiling its conflicts to men of unregenerate minds,
they (either through uncharitableness or unskillfulness) wound instead of heal;
or direct the soul to other objects,
instead of informing it where to find Him whom it seeks.

These observations occurring to my mind, I hope you will receive them in gospel love,
in which I think they are communicated.
I now conclude, with desires that if any inconsistency has appeared in your conduct,
you may for the future keep more close to the divine Guide,
and thus be clothed with wisdom and strength,
and witness salvation and peace to accompany you.

[.signed-section-closing]
I am your real friend,

[.signed-section-signature]
Catherine Payton.

[.signed-section-context-close]
Dudley, 16th of the Third month, called March, 1752.

--

[.asterism]
'''

[.offset]
+++[+++The following general epistle, written by Catherine Payton in 1758,
was addressed to Friends in Ireland at a time when many in that
country had fallen into a sad state of degeneracy from the life,
purity, and power of the Spirit that had so characterized the early Society of Friends,
and instead had settled into lifeless formalism on the one hand,
and fleshly liberty on the other.]

[.embedded-content-document.epistle]
--

[.salutation]
Dearly beloved,

For with a feeling of gospel compassion I may so call you--have you ever
seriously considered that "`here you have no continuing city?`"^
footnote:[Hebrews 13:18]
Have you understood that, as your souls are immortal,
it is the proper (and ought to be the _principal_) business of your lives,
to seek a habitation for them that is suitable to their being and nature,
wherein they may have a happy residence forever, which is alone to be found in God,
who is the source and supply of His people?

Now, in order that your souls may at last center in God,
it is necessary that they should be made habitations for Him through
the sanctifying operation of the Spirit of His Son,
which alone can render us (who have been defiled with sin and therefore
unfitted for a residence with Him) fit objects of His favor.
Allow me therefore to ask you,
and oh that you would ask yourselves!-- what you
have truly known of this work in your experience?
Has the Spirit of judgment and of burning done its office in your hearts?
Have you passed through the first part of the work of sanctification--I
mean the administration of condemnation for sin?
Have you been bowed under the testimony of the righteous Witness of God in your conscience?
Or have you rather suppressed and disregarded this heavenly messenger,
not allowing it to tell you the Truth, or perhaps,
disbelieved the doctrine it preached because it did not condone some of your actions?
Indeed, have not some gone so far as to slay the
"`two witnesses for God`"--the internal evidence of His Spirit,
and the external testimony of His servants--and at
this time are perhaps exulting in their victory,
and proclaiming to themselves "`peace, peace;`" when alas, a day of fearfulness,
amazement, and unutterable anguish awaits them and is near?
For surely, the curtains of mortality shall soon be drawn,
and all must stand before the Judge, tremendous in majesty,
and see that righteous Witness, which in time they slew,
raised up in power to testify against them for their rebellion,
and then attest to the justice of their exclusion from the realms of light and blessedness.

What effect this faint description of the day of judgment to the wicked,
and to those who forget God, may have upon the minds of such, I know not;
but feeling my heart impressed with an awful sense of its certainty,
I am provoked to attempt to wrest as many as possible from such eternal consequences,
by persuading them to bow in the day of God`'s merciful visitation to their souls,
and to "`kiss the Son lest He be angry,
and they perish from the way`" of life and salvation,
"`before His wrath be kindled but a little.`"^
footnote:[Psalm 2:12]

Do not vainly and proudly imagine that you are able to withstand the force of Omnipotence.
He is, and will be King,
whether you are willing to allow Him the right of sovereignty or not;
and His sacred laws of unchangeable truth are as manifest in the
punishment of transgressors as in the reward of those that do well.
And oh!--if it were possible to convey to you a sense of that sweet peace, glory,
and joy, which are, and shall be, revealed to those who love and serve God,
you would be convinced that no punishment could be too great for such as (by
a contrary conduct) slight and cast away so great salvation and happiness.
But as no eye can see, nor heart conceive,
the exceeding grace of God in Christ Jesus besides such
as have happily witnessed its sanctifying operations;
I cannot help but invite you to "`Come, taste, and see that the Lord is good,
and that His mercy endures forever.`"

It is true, that in the way to this attainment you must pass through judgment;
for "`Zion must be redeemed through judgment, and all the converts with righteousness,`"^
footnote:[Isaiah 1:27]
and a portion of indignation and wrath, tribulation and anguish,
must (consistently with the law of Divine justice)
be administered to every soul that sins.
But this judgment when received in the day of God`'s merciful visitation,
is followed by such inexpressible peace and assurance of Divine favor,
as abundantly compensates for the pains it may have occasioned.
For truly, the carnal "`eye has not seen, nor ear heard, nor heart conceived,`"^
footnote:[1 Corinthians 2:9]
what good is in store for those who manifest their love to God by their obedience.
Believe me, my beloved friends,
when I tell you that my heart is strongly engaged for your welfare,
as you stand in your various conditions.
I feel much more for you than I can write, and beseech you by the mercies of God,
as well as by His judgments, that you present the whole body of your affections unto Him,
which is no more than your reasonable service.

Has He not dealt bountifully to some of you the things of this life?
For what cause do you think He has entrusted you with such an abundance?
Is it to gratify the lust of the eye and the pride of life?
Is it to make you haughty,
and assume a superiority over those who in this respect may be below yourselves,
but who perhaps may, some of them, be higher in the Divine favor?
Surely no!--but in order that you may improve this gift to His honor,
to the good of others, and to your own eternal advantage;
and that you may also be humbled in a sense of the
disproportion of His mercies compared to your deserts.
Has He not favored some of you with superior natural abilities?
And for what end, but that you might be in a greater degree serviceable in His hand?
Has He not afforded to all a day of merciful visitation,
wherein He has (by various means) endeavored to bring
you into that fold of immortal rest,
wherein He causes His flocks to feed and lie down beside the clear streams of salvation?
Oh, says my soul, that you may consider His mercies and make a suitable return for them;
that the Most High may delight in this present generation
and dwell among His people as in days past!
Oh, you of this rising generation,
open the doors of your hearts to that Divine Visitor
who has long stood and knocked for entrance.
Let Him prepare your hearts,
and He will assuredly spread His table and admit you into His happy communion.

Think not that it is too early in life for you to
look steadily towards a future state of existence;
but consider,
that the solemn message to summon you from works to rewards
may be sent to you at an early and unexpected hour.
It therefore behooves you to be prepared to meet the great Judge.
My heart is particularly engaged for your welfare,
and pained in the consideration of how widely some of you
have deviated from that path of primitive simplicity,
wherein your worthy predecessors walked.
Let me therefore beseech you to seek for the "`good old way`" of holiness,
and to walk therein, that you may experientially know the "`God of your fathers,
and serve Him with a perfect heart and willing mind:`"^
footnote:[1 Chronicles 28:9]
so will His blessing forever rest upon you, which makes truly rich,
and brings no sorrow with it.

Let the cloud of witnesses to the power and unutterable riches of pure and living religion,
prevail with you to submit to its holy influence, that you may rightly understand,
and diligently pursue, the things that belong to your peace both here and hereafter.
Let the examples of the righteous in all generations;
let their peaceful lives and their happy conclusions, triumphing over death, hell,
and the grave, in a lively and full assurance of faith;
let the solemn importance of time and eternity excite you while it is still day,
and while light is upon your tabernacles, to seek an increase of your talent,
that so you may be numbered amongst the wise,
who shall be instrumental to turn many to righteousness,
and shine as the brightness of the firmament as stars forever and ever.

The negligent and careless, the hard-hearted and they that are far from righteousness,
may receive instruction from viewing the end of those who are like-minded in all generations.
Such have not escaped the righteous judgments of the Almighty,
who has sealed it as a certain truth: "`Verily there is a reward for the righteous;
verily He is a God that judges in the earth.`"^
footnote:[Psalm 58:11]

And now, dear Friends,
as I have endeavored in plainness to communicate what has
freely opened to the several states among you,
I would warn all to beware of putting their proper portion far from them;
but let each examine themselves, saying, "`Is it I? Is it I?`"^
footnote:[Matthew 26:22]
And let not the iniquities of others,
which some may observe to be struck at by this letter,
allow any to fix themselves in a state of self-security;
for assuredly every one must suffer for his own transgression.
I know and am thankful that the Lord has a remnant amongst you, of all ranks,
whom He has preserved near unto Himself.
To these, my soul feels united in the tribulations and rejoicings of the gospel;
and unto them a salutation reaches forth, and seems to arise in my heart in this way:
Brethren and sisters, be of good cheer, "`be patient,
and hope to the end,`" for the hand of that God whom
you serve is stretched out for your help;
and if you abide faithful to Him,
in His own time He will crown your sufferings with rejoicing.

Finally, dearly beloved, farewell; and may the grace of our Lord Jesus Christ,
the love of God, and the fellowship of the Holy Spirit, be with you all, Amen.

[.signed-section-closing]
I am your friend and sister in the Truth,

[.signed-section-signature]
Catherine Payton

[.signed-section-context-close]
Dudley, 10th of Tenth month, 1758.

--

[.asterism]
'''

[.offset]
+++[+++This final letter is addressed to her elder brother Henry,
who was the son of her father by a previous marriage, but not the son of her mother.
Speaking of this brother in another place in her journal, Catherine says: "`When a youth,
he was much humbled under the visitation of Divine love;
but when he arrived to mature age, he was drawn aside by vain company.
And having addicted himself to pleasure and to the gratification of his natural appetites,
he lost the simplicity of his upbringing;
and because he desired to indulge himself in liberties which
he knew were inconsistent with the profession of Truth,
he threw it off; saying, he would not retain the name +++[+++of a Quaker]
and be a reproach to the people.]

[.embedded-content-document.letter]
--

[.letter-heading]
To her brother, Henry Payton.

[.salutation]
Dear Brother,

Heretofore when absent,
I have felt easy in remembering you with sincere desires for your welfare; but now,
finding in myself a desire of writing to you, I am unwilling to stifle it,
though it were only to do all in my power to strengthen that affection
which ought to subsist between persons so nearly united by nature.

But alas!--when I consider the differences in our affections, pursuits,
and sentiments with regards to all that concerns right and wrong,
I am fearful to set pen to paper,
lest I should not be read with candor and understanding.
Nevertheless, I encourage myself with this conclusion,
that you will at least receive this as a token of my regard for you.
Regard, did I say?
I will alter the term to affection;
which indeed I have felt gently to spring in my soul towards you;
not only as to a creature formed by the same Almighty hand as myself,
and for the same noble end--namely, to glorify Him who gave us being,
and who has loaded us with a multitude of favors which call loudly for a grateful response--but,
also as to a brother who has strayed from the path of peace and safety,
and is seeking satisfaction in the grasp of empty bubbles,
which have assumed the form (in his sight) of something substantial.
But your own experience, if you are impartial,
will tell you that these bubbles have broken when touched, and dispersed in the air,
leaving nothing real behind them but a keen sense of remorse,
and the painful remembrance that they are now lost, along with all the time,
pains and anxiety that were bestowed in the pursuit of them.
Yet in this vain pursuit (Oh,
sad but too just a charge!) has a great part of your life been spent;
ardently traversing the destructive mazes of delusive pleasure,
and industriously avoiding the One only Good,
in the possession of which your soul might have found substantial
happiness--a happiness which would have afforded that true contentment
and fulness of joy which alone can satisfy the immortal part,
being itself immortal in its nature.

You will perhaps say that these are my sentiments.
But allow me to ask you, why they are not yours?
Why do we differ in opinion and practice,
but because the desire and pursuit of sensual gratifications has blinded your judgment,
and biased your actions?
I will venture to assert that it was the kingdom or possessions of this world,
its friendships, vanities, and sensual pleasures, spread before the view of your mind,
that drew you from your early love and allegiance
to Him who is truly worthy of love and obedience.
Nature joined together with well-adapted temptations (being always fond of present enjoyment,
though it be forbidden fruit),
and renounced submission to the pure law of grace written in the heart; which,
had it been observed, would have rectified her impure and irregular appetites,
and placed you in the true state of manhood, as lord over, and not a slave to,
the creation of God.
Then you would be governor of yourself in happy subjection to the Divine will;
a will which invariably points out the everlasting happiness of mankind.
But nature--a rebel to her own best interest, blinded by false affection,
and fraught with pride,
like our first parents--is not fond of having a superior who shall control her perverseness,
and prescribe laws for her direction;
but rather chooses to take the reins of government into her own hand,
and plan out a way for herself.

Here reason, blind fallen reason, enthroned by the power of Satan,
usurps the sovereign seat and sits in the temple of God, being honored as God; power,
wisdom, and discretion to govern and direct being ascribed unto it.
This false king called human reason (who, had he occupied his proper place,
would have made a good subject), then joins in a strict league with the passions,
and prescribes rules directed by these his allies.
"`Shall man (says reason) be confined within the narrow rules of virtue and religion?
No, I proclaim for him liberty!
Let him indulge himself in what is desirable;
let him gratify the sight of his eye and the pride of his heart,
in endeavoring to make himself agreeable to and admired by mankind.
Yes, let him join with others in full society and free communion,
entertaining and being entertained.
Why may he not partake of the pleasures of sense,
seeing he has appetites for such things;
why may he not satisfy his curiosity in knowing evil as well as good?`"

These are the genuine suggestions of the reasoning faculty when guided by the passions
(though I confess that I believe the subtle deceiver of mankind sometimes teaches this
reason to speak in a language more concealed than what I have here set down).
But I think it will be no hard matter to prove,
that this boasted liberty is real bondage,
and that this acquisition of knowledge brings no more than a sense of guilt,
resulting from the loss of that innocence which gave man boldness
to appear before the face of Almighty justice and purity,
free from distracting fear.

If we examine the extent of virtue and true religion,
and then take note of every passion implanted by Providence in the nature of man;
we shall find that in them alone +++[+++i.e. in virtue and true religion]
it is possible for these longings to be rightly gratified,
and that whenever man breaks from their righteous bounds,
he flies from the mark of his own happiness.

I have looked upon love to be the governing passion in the soul, which, as it moves,
draws everything else after it in its train;
and being strongly fixed on a worthy or an unworthy object,
is the cause of our joy or misery.
This being granted, we must then consider _what_ object is worthy of our entire affection;
and in this consideration let it be remembered that this seed of love,
or desire of enjoyment, is so deeply seated in the soul, as never to be taken from it.
Now certainly, whatever object is worthy of our soul spending its force upon,
or seeking to be united to without limitation, must not be dependent upon time,
for death soon deprives it of that;
but it must be as durable as the soul`'s own existence,
and so perfect as to fully satisfy an everlasting desire of possession.
Clearly, this can be nothing else but the Eternal Excellency,
from whom this spark of affection or love is derived;
and if divine order were not inverted,
it would as naturally bend towards its source as a stone falls to the earth,
where alone it can find a happy settlement.

In this love of God, stands virtue; it is this that inspires it.
If we truly love God, who is infinite in purity and wisdom,
we shall naturally hate their contraries, impurity and folly,
and shall hate ourselves because of them; because whatever defiles the soul,
destroys its likeness to the divine Being and renders it unacceptable in His sight.
Therefore,
as it is the nature of a true affection to seek after the love of the beloved object,
from here proceeds an ardent desire of purification,
and a child-like fear of offending God;
a fear that is most rationally founded in a deep sense of gratitude,
considering Him as the Author of all the good we possess, or can rightly hope for.
This, coupled with the knowledge of His power and justice in punishing transgressions,
brings a keen awareness that whatever would amuse our senses so
as to draw our affection away from this Fountain of goodness,
should be dreaded and renounced as forbidden fruit.

In true religion,^
footnote:[The life and light of Christ reigning in the soul of man.]
the soul is enlarged and set at liberty to exercise its most noble faculties in actions,
or upon objects, that are worthy of the dignity of its nature.
On the contrary, without such religion, the soul remains in bondage,
and debases itself in the pursuit of what scarcely deserves the name of pleasure,
being of no real worth or lasting duration.
In short,
religion places man in the sphere that the wise Author of nature designed for him;
directing his affections to ascend towards the Creator,
and then to descend towards the creation.
If the ascent is sufficient, the descent will be righteous.
Created things will be loved as the works and gifts of the Creator;
and yet they will be possessed with due caution from this consideration,
that they are allotted to us for an uncertain season,
and it is therefore in our best interest to be able to surrender them when called for,
with as little pain or anxiety as possible.
On the contrary,
the immoderate descent of the affections into created
things ties us down to the earth and earthly possessions,
shackles us in sensual gratifications,
greatly prevents the soul`'s ascending towards God,
and destroys its delegated sovereignty over the creation,
to which it finds itself in bondage.
How true is that assertion of the apostle, that while some boasted of their liberty,
or promised it to others, they themselves were the slaves of corruption.^
footnote:[2 Peter 2:19]

I have sometimes considered how the excuses of these
boasted libertines only manifest their slavery:
"`We cannot help such-and-such a conduct,`" they say,
or "`We have not power to resist such temptations.`"
If this were true,
it would be an acknowledgment that they had lost that valuable blessing,
the freedom of the will, and are now utterly destitute of power to withstand evil,
having become the devil`'s captives.
Such they are indeed, though not necessarily, but voluntarily.
For wisdom and power, through the grace of God,
is given to man to discover and resist the temptations of his enemy;
and if man will renounce such a gift,
his blindness and subjection to the power of delusion is procured by himself,
along with its miserable consequence, namely,
an everlasting separation from the Fountain of all good.

You will easily perceive,
that the intention of the foregoing hints is to influence your mind in
favor of a more strict course of virtue than you have formerly pursued.
What shall I say to persuade you to turn,
and carefully and impartially to look into yourself?
Shall I plead your advancement in years?
You are now (I believe) rather in the decline of life,
hastening towards the gate of the garden.
Shall I beseech you by the mercies of God to return
to Him from whom you have deeply revolted,
and seek reconciliation by unfeigned repentance,
if you can find room so to do--which I have a lively hope you may,
though you have so long, and so distantly, strayed from the fold of Christ.

I shall plead no excuse for the freedom with which I have here written to you,
except to say, that I think a true freedom in communicating our sentiments,
with a design for each other`'s eternal well-being,
is a part of that love which should clothe the spirits of the followers of Jesus Christ.
The largeness of my subject will, I hope, excuse the length of my letter.
Upon a review of what I have written it will readily be observed,
that the hints given are but like titles of chapters, which, if fully enlarged upon,
might fill a volume instead of a letter.
And, that the everlasting Minister of the sanctuary may
enlarge them in the view of your understanding,
to your lasting benefit, is the sincere and ardent desire of your affectionate sister,

[.signed-section-signature]
Catherine Payton.

[.signed-section-context-close]
Written at sea on board the Alexander, 6th of the Tenth month, 1753.

--

[.asterism]
'''

__As mentioned previously,
Catherine Payton began to minister in 1748, at 22 years of age,
and travelled almost incessantly in the work of the gospel until
her marriage to William Phillips in 1772.
Subsequent to her marriage, she remained an active laborer in the church for many years,
but having sustained several injuries from falls from her horse,
and being increasingly afflicted with a stiffness in her joints
that "`baffled all medical application,`"
she was slowly reduced to a quite debilitated condition,
and was at last largely confined to her home in Cornwall.
She died the 16th of the eighth month, 1794, in the sixty-eighth year of her age,
and forty-sixth of her ministry.__

__It is difficult to convey the true worth of this handmaid of the Lord,
the influence of her ministry,
or the esteem in which she was held by her contemporaries and fellow-ministers.
The following passage is taken from the journal of Sarah R. Grubb,
written after a visit to Catherine Payton near the end of her life.
"`She has been a faithful, laborious servant in the church,
especially under the exercise of her gift, which was eminent for its purity,
its copiousness, and clearness.
Her ministry has had a tendency to raise into dominion the pure Life,
and in supplication she has been often wonderfully favoured with near access to the throne,
and enabled to cast down every crown, and to ascribe worship and praise,
salvation and strength, to the Lord God and the Lamb.
Since my mind has been graciously visited with a sense of Truth,
such have been my sentiments concerning this great and good woman.
But about two years ago, to my humble admiration in a season of great proving of spirit,
this conviction was deeply renewed and sealed to me;
for I felt the inward attraction so strong,
and an undoubted evidence that she was a faithful follower of the Lamb.
Indeed, I heard a language sweetly flowing through my mind,
saying, '`I have chosen her and she is mine.`'`"__
