== Chapter 5

[.chapter-synopsis]
* Sarah Wagstaffe
* Abraham Shackleton
* Joseph Bevington
* Ann Gurney
* William Hunt
* Elizabeth Smith
* Priscilla Gurney

SARAH WAGSTAFFE, of Chipping-Norton, in Oxfordshire, widow of Thomas Wagstaffe,
formerly of Banbury, in the same county, was born in the year 1695,
and educated in the way of truth in the city of London, where her parents lived.
Being faithful to the dictates thereof in her young years,
she experienced its supporting influence under many
exercises which fell to her lot through life,
having often to remark to her children the benefit thereof; and by suitable instructions,
endeavored to lead their minds to regard its dictates when very young;
and when remote from her, was often, by writing, reviving suitable counsel to them,
being herself a good example, a tender parent,
and well beloved among her neighbors and friends.

Towards the decline of her life she was afflicted with bodily weakness,
which confined her to her chamber for some months before she died,
which she bore with much resignation and patience,
often desiring she might hold out to the end, for which she patiently waited.
Before she became incapable,
she employed her pen to such of her children as were at a distance from her,
particularly to one of her sons.
When she, by letter, took her last leave of him and his family,
she expressed herself thus:

[.embedded-content-document.letter]
--

That my children and grandchildren may be so conducted through mutability,
as that we may all meet in joy and bliss, I entreat (says she) in love,
that you and yours may mind your future state above all,
and let not the hurry of this transitory world, with all its tinsel glare, pride,
grandeur, and vanity, choke the good seed, which, as it is permitted to take root,
will bring forth the good fruit, which will entitle you to discipleship,
and give you a beauty and glory which all these things cannot give.

Dear son, be on your guard, and watch over your children; repress all pride, ambition,
and vain conduct in them as much as possible.
O this world`'s fading enjoyments have overrun the major part of our Society!
How few live up to what they profess!
I write with a fervent desire for all your immortal souls,
each of which is of more value than all this world,
which with all its checkered pleasures and afflictions,
must soon end as the bubble on the water,
and then peace with our Maker will only stand us in stead.

--

At another time, when to appearance she grew near her end,
she expressed herself to this effect:
that her trust and dependence was on her Almighty Protector, Savior, and Redeemer,
by whose grace she doubted not, but that she should close in peace.

After which she continued some weeks, in much quietness and patience,
until the 5th of the First month, 1771, when she quietly departed without sigh or groan,
and was interred in Friends`' burial-ground at Chipping-Norton aforesaid,
after a solemn meeting, the 13th of the same; aged near seventy-six years.

[.asterism]
'''

ABRAHAM SHACKLETON, born at Harden, in the parish of Bingley, Yorkshire,
according to the best information,
was the youngest child of Richard and Sarah Shackleton of that place.
His mother died when he was about six years of age, his father when he was about eight.
Though deprived so early of religious parents,
the impression made by their careful education of him was not in vain;
he used often to commemorate the tender care and concern of his pious father,
how he followed him (his son) when very young to his bedside,
and on leaving him to his repose, awfully recommended him to seek the divine blessing.
And this blessing remarkably attended him during the course of his life.
When very young, and exposed to manifold dangers in his education afterwards,
this blessing followed him, and by its precious influence,
led him aside from his companions, and into solitary places to seek the Lord,
and to witness the operation of his hand.

His employment being that of a school-master,
he labored in it with conscientious care for many years;
in which he had not only the education of children of the members of our own Society,
but also some of various denominations,
some of whom fill conspicuous stations in the world,
and retain an affectionate regard for his memory, and,
from a remembrance of his diligence and care in their tuition,
his living example of uprightness, temperance, and humility,
a great regard for the Society.

Although in this arduous employment he met with many probations,
yet keeping to a feeling sense of divine support, he grew from strength to strength,
and became a very useful and valuable member of the Society;
and in the station of an elder, had often to minister in his own house,
in the families of friends, and in the church,
in which counsel dropped from him in much tenderness and sweetness.

Thus, through a course of many years,
he was conducted in great circumspection in a living travail for the prosperity of truth,
and that the professors of it might be preserved out of hurtful things;
had frequently to testify against such superfluities as sometimes came in his way,
particularly a practice too prevalent among many,
that of sitting long after dinner with bottles and glasses before them,
as having a tendency to draw many into snares.

He was also much concerned at a custom too prevalent among Friends,
of uncovering the head by way of ceremony upon entering into a room,
and was pained when he saw the youth or others in that practice.
He used to say, that when he was a young man,
he dared not baulk his testimony in that respect,
though the cross occasioned thereby seemed as bitter as death.

After a diligent discharge of his laborious employment for many years,
he became in a greater degree separated from the cares of this life,
and devoted much of his time in attending meetings for discipline
in various parts of the nation of Ireland,
where he was settled in his school, and also the yearly meeting in London,
to the help of his brethren and his own peace.

After the death of his wife, who had been his beloved and faithful help-meet many years,
and who departed this life in cheerful resignation, great composure and sweet peace,
in the eightieth year of her age,
he quitted house-keeping and retired to live with a relation in
the same village where he was visited with his last illness,
which he bore with great patience, saying he was mercifully dealt with.

During the course of his disorder, and while able, he got out to meetings,
and when rendered incapable thereof, many friends visited him,
to whom he was drawn forth in sweet counsel to the tendering of their spirits.
Many were the seasonable opportunities of this sort, and many sensible,
savory expressions dropped from him,
which showed his mind was often replenished with heavenly oil.

A little before his departure, he said to his relations about him,
"`I have no cause to grieve,
neither would I have you to do so;`" yet mentioned he had
nothing to trust to but the mercies of the Almighty.
His mind was often favored with heavenly joy, and one night, after much pain,
he expressed with a melodious voice, "`I am well, I feel no pain, I feel good.
O the elders! the elders! they should dig for the arising
of the well of life as with the staves in their hands.
Spring up, O well, and I will sing unto you!`" At another time,
in a manner similar to this, he uttered these words,
"`Those that are faithful to the end shall receive a crown, a crown that fades not away;
but rebellion is as the sin of witchcraft.`"

Much more dropped from him, but not being taken down, could not be perfectly remembered.
He departed in great peace the 24th of the Sixth month, 1771,
and was interred the 27th of the same; aged seventy-four years.

[.asterism]
'''

JOSEPH BEVINGTON, son of Timothy and Hannah Bevington, of the city of Worcester,
was a young man, who from a child was sober and well-inclined, exemplary in his conduct,
dutiful to his parents, and of a tender and loving disposition.
As he grew up towards man`'s estate,
he gave evident proofs of a suitable attention to that divine principle in his own mind,
by which his conduct was so regulated,
as to give ground of hope he would fill up his station with
reputation to himself and comfort to all his friends.

He was taken ill about the 1st of the Sixth month, 1771,
and his disorder gradually increasing,
his father found his mind engaged to go and sit by
him one evening on his going to bed sooner than usual,
and in much tenderness expressed, that though he had hoped he might,
in the appointment of Providence, have been his successor,
both in the church and in the world, yet,
when illness attacked even one so young and healthy as he, the outcome might be doubtful,
and therefore desired him to examine his accounts and meetness for a final change,
if the Lord should please to remove him.
He, in affectionate, lively terms,
expressed the sense he had of his father`'s tender regard for him,
and they parted that evening under a sweet sense of that
love which unites beyond the ties of nature.

His distemper increasing, which proved to be a fever,
he was mercifully preserved sensible.
His father and mother being often concerned to wait on the Lord by his bedside,
he was frequently broken into tenderness, but did not say much.

Getting a little better, he went into the country for the air.
In some conversation with a friend there who was in a declining state, he expressed,
that he did not know how it might please Providence to deal with him; "`but,`" said he,
"`I had rather, if consistent with his will, go now, than live longer,
and fall into anything that might bring dishonor to our holy profession.`"

A near friend visiting him, found him in tears,
and expressing her fears lest anything had grieved him, he answered, no,
but he was looking towards another world.

He returned out of the country in about a week rather poorly,
and on the morrow was seized with a shivering fit, and sending for his father,
he with earnestness took him by the hand, and said, "`Dear father,
I have already gone through a very trying time,
but I believe this will be much more so;`" and expressing his care for his parents, added,
"`He that made me has a right to take me away when he pleases; and I desire,
as he has favored me with much resignation of mind to his will hitherto, it may continue.
I have not always been so careful and circumspect in my conduct as I ought to have been;
but lately, and especially since my illness, I do not know that I could have done better,
and trust it will be well with me.`"

His indisposition increasing, all hopes of his recovery were removed, in which,
he being in extreme pain and sickness,
his parents were engaged to wait on the Lord with him,
who was graciously pleased to comfort their minds; and under this broken, humble,
contrite state before him, who sustains his people in every needful time,
this beloved youth with an audible voice said,
"`O what a dreadful day would this have been to me,
if I had cause to fear I was going to meet an angry judge, that might say,
'`Depart from me, you worker of iniquity!`' but,`" said he, "`I have hope in God,
that I shall be admitted into his rest.`"
This much bowed the hearts of all his near connections present,
and helped to bear up their spirits in that trying season.

Soon after,
this dear object of paternal affection quietly departed this life in his father`'s arms,
having, in a good degree, escaped the dangers, jeopardies,
and temptations attendant on human life,
and we trust was gathered with the beauty of innocency upon him,
to the just of all generations, in the twenty-first year of his age,
on the 9th of the Seventh month, 1771, and was buried in the city of Worcester,
on the 14th of the same.

[.asterism]
'''

ANN GURNEY, daughter of John and Ann Gurney, of the city of Norwich, was a comely person,
of quick parts, and a lively turn.
Hence she early showed a natural inclination to height and gaiety,
which brought a concern upon her parents on her account,
lest she should be carried away with the common stream into liberties of a hurtful nature.
But such was the gracious dealing of divine mercy towards her,
that some time before she was taken with her last illness,
an agreeable alteration was observed in her disposition and conduct,
which undoubtedly arose from the cordial reception
she had given to a heavenly visitation upon her spirit;
for, in the sequel, it evidently appeared, a state of preparation was thereby effected,
properly to endure the tedious illness and solemn event that ensued.

For many months, her usual state of health seemed, at times, to be broken in upon,
and tokens of infirmity appeared, which increased upon her,
and at length terminated in a settled decline.

Several weeks before her decease, she cheerfully said to her sisters,
"`My little tenement is much shaken, and will soon be in decay.`"
A while after,
her mother saying she should be very thankful if
it pleased Providence to raise her up again,
she replied, "`That must be as it pleases Providence,
but I can never go with less guilt.`"

She said, she believed divine goodness had often been very near to her,
and supported her; for she could not have supported herself.

To her sister Lucy she said, "`My dear,
I hope you will never do anything to grieve your father and mother,
and be sure do nothing against your own conscience.
Do not grieve for me; for though we have loved one another, it is right we should part.`"

She acknowledged she had sometimes gone contrary to the testimony of her conscience;
but she had known sorrow for it, and, she believed, forgiveness; and made no doubt,
but if it pleased Providence to take her away, she should go to heaven.

To her mother she said, "`I know it will be a loss; make it but a little one.`"
Her mother replying, "`It is a bitter cup, my dear,`" she answered,
"`But Providence will sweeten the bitter cup.`"
And on her mother`'s saying she believed a glorious mansion was prepared for her,
she replied with much earnestness, "`I make no doubt of that,
and I expect to see you and my father there.`"

Desiring her sisters to be called, she told them she was glad to see them; and,
lying a while sweetly still, she awfully said,
she hoped they would always live in the fear of the Lord,
and never do anything against their consciences.

Being told her uncle Edmund Gurney said that she was in a sweet frame,
and compared her to Mount Zion, that could not be moved, she answered,
"`Then why does my mother grieve so?`"

Her father going one morning into her chamber, she desired him to come by her bedside,
saying she was glad to see him, and that she thought herself not worse.
On his saying he hoped her better parent, her heavenly Father,
had been near to her that night, she answered, "`Yes, that he has,
and I hope near you too.`"

Two days before her decease, she earnestly prayed the Lord would be with her to the end,
and give her patience to the last; and that, if he pleased,
he would mercifully grant her an easy passage,
as her uncle Edmund had prayed for on her account.
She declared she was very willing to go, with many other comfortable expressions.

She was composed and easy in her mind throughout her long and painful illness,
and never once expressed a wish to live.
She said she had many near and dear relations to leave;
but she should not know the pain of losing them.

Thus having shown a steady example of faith, patience, resignation,
and heavenly composure, in the bloom of youth, she departed the 19th of the First month,
1772; aged fourteen years and nine months.

[.asterism]
'''

WILLIAM HUNT, of New Gardon, in the province of North Carolina, in America,
was born in the province of Pennsylvania; and, by accounts received,
he was first reached by truth about the eighth year of his age,
which continued to follow him from time to time,
that when in company with his acquaintance,
he has been often tendered and led to seek solitary places to vent his tears;
although he then did not know what it was that so broke in upon his spirit.

Being situated in a part, at that early period of his life, where no religion prevailed,
but the people lived rather dissolutely,
he had no one to tell the distress and exercise of his mind to,
for his mother dying when he was young, who he had been informed was a religious woman,
and his father when he was about twelve, he was left quite alone.
But after some time going to live with his sister,
and those tender impressions continuing,
the Lord in mercy showed him they were from the immediate operation of his own spirit,
and that his growth in truth and experience of its pure virtue,
lay in his being faithful to the dictates thereof; by which he was fitted for service,
even in very early years,
his mouth being opened in testimony before he was fifteen years of age;
and through the heavenly influence of the Spirit, he became an able minister,
rightly dividing the word of truth,
to the great comfort and edification of the church where his lot was cast.

He was concerned to travel in truth`'s service before his twentieth year,
and visited the provinces of Virginia and Maryland;
and afterwards in the course of his Christian progress, all the provinces of America,
and almost all the meetings therein.
Although he had a large family, whose subsistence much depended on his industry and care;
yet, when he found the requirings of truth, and became fully satisfied thereof,
he cheerfully gave up all into the care of that hand which drew him into service,
relying thereon for the preservation of himself and all his,
in every dispensation of Providence, and which was mercifully afforded to him.

In the year 1771 he came to Great Britain on a religious visit,
and travelled through most parts of the north of England, Scotland and Ireland,
and after the yearly meeting, 1772,
he visited the general quarterly meetings at Colchester, Woodbridge and Norwich.
Soon after this he proceeded through Lincolnshire for Hull, from which,
with his companion, Thomas Thornborough, our friend Samuel Emlen, Jr., of Philadelphia,
and Morris Birkbeck, he embarked for Holland; and after visiting the few Friends there,
he embarked in a vessel bound to Scarborough, but, by contrary winds,
landed at Shields the latter end of the Eighth month,
with a dedication of heart for further service if required; but was,
soon after he landed, taken ill of the small-pox.
In the course of this illness, his mind was preserved perfectly calm,
and his patience and fortitude were truly great,
as was also his resignation to the divine disposal,
signifying to his companion that his coming there was providential,
but that his sickness was near unto death, if not quite; "`for,`" says he, "`when I wait,
I seem enclosed, I see no further.`"

To a friend who remarked that whatever affliction we may be tried with,
we may yet see cause of thankfulness, he replied, "`Great cause, indeed;
I never saw it clearer.
Oh! the wisdom! the wisdom and goodness, the mercy and kindness,
have appeared to me wonderful!
And the further and deeper we go, the more we wonder.
I have admired since I was cast on this bed,
that all the world does not seek after the enjoyment of truth,
it so far transcends all other things.`"

At another time, to some Friends who came to see him, he said,
"`The Lord knows how I have loved you from our first acquaintance,
and longed for your growth and establishment in the blessed truth,
and I now feel the same renewed afresh:`" adding,
that he much desired they might fill up the places Providence intended,
and lay up treasure in heaven; "`for,`" says he,
"`what would a thousand worlds avail me now.`"
He also expressed his satisfaction that he had not
spent his time idly since he came to England,
nor neglected one meeting he could well attend;
and that under so great a load of bodily affliction, what a treasure a quiet mind was.

At another time he said, with great composure, "`The Lord knows best.
I am in his hand, let him do what he will.`"
Leaning on Morris Birkbeck, he said, "`Dear Morris, I have a request to make, which is,
in case I am suddenly taken away, do you write to my dear wife,
and let her know all is well.
Write also to my children,
to improve the hints I frequently gave for their conduct while with them and since.`"

At another time, a day or two before his death, he said to him, "`This is a trying time,
but my mind is above it all;`" and it was observable that
a sweet melody was in his heart when few words were expressed.

A little before his death, he said triumphantly, "`Friends,
truth reigns over all;`" and soon after quietly departed this life,
the 9th of the Ninth month, 1772,
and was interred in Friends`' burial-ground at Newcastle upon Tyne, the 11th of the same;
aged thirty-nine, a minister twenty-four years.

[.asterism]
'''

ELIZABETH SMITH, of Burlington, in West Jersey, in America,
was one whose deportment from a child was composed and steady.
Frequently, while others sought recreation and amusements abroad,
she chose to be at home, employing herself in the business of the family,
or improving her mind by some useful application.
As she grew up, the reproofs of instruction became the way of life to her,
and she was governed by a meek and quiet spirit;
her conversation and conduct seemed to be almost one continued
example of child-like simplicity and innocence.
Her mother dying while she was young,
the care of her father`'s family devolved upon her
for a considerable time before his death.
Her duty to him, and behavior in general, gained the love of a careful religious parent,
and a blessing attended her, as her future life manifested.
Her words were few, but savory and instructive; she had a feeling heart,
and the distressed were often relieved by her charity: happy in herself,
she endeavored to make all about her so.
She had a great regard for the Holy Scriptures; on taking up a bible,
she remarked to a particular friend, what a treasure it contained;
and sought to inculcate the reading thereof,
and to discourage the fashionable books of the times.

It was her concern frequently to retire to wait on the Lord,
to know her strength renewed in him,
and the effects were visible by a cheerful serenity in her countenance.

In her early youth she was called to the work of the ministry,
in which she delivered herself in a clear, consistent manner;
and it flowing from the right spring, was often attended with good effect.
She was concerned to travel in the exercise of her
gift as far to the northward as New England,
and also to some of the southern provinces, and frequently to the meetings about home.
But in her latter time she was greatly afflicted with a dropsical disorder,
which subjected her to be tapped, by which she was so far relieved,
that for several years she had a better state of health.
In this interval she frequently attended meetings for worship and discipline;
and the last summer before her death, though much enfeebled in body,
had often very acceptable service in the ministry: alive and strong in the best sense,
her company was greatly satisfactory to friends about her.

Her disorder returning, she waited for her change with a lively hope;
and a serenity of mind attended her,
being inwardly supported beyond mere human attainment.

She uttered many expressions during the conflicts of her illness,
much to the comfort and satisfaction of those present.
In solemn supplication to the Almighty on her own account, to be near and support her,
she expressed herself in great reverence to the following effect:
"`You who are the God of my life, who have kept and fed me all my life long,
be now near and support me by your presence,
and if it is your will to put an end to my being here, I submit.
Be graciously pleased to give me rest in your mansion, with your dear Son,
the Lamb immaculate, forever and ever.`"

She often said she had nothing to do but to bear her pains with patience.
Once in great extremity of pain, she remarked that she had reasoned,
"`Why am I so afflicted?`"
and had received this answer in her mind, "`My beloved son, who never offended me,
drank of the cup before you.`"
"`Thus,`" said she, "`I am helped along with one kind hint after another.`"
She frequently expressed the peace and consolation she felt in those trying moments,
in having lived in the fear of her Creator.

A night or two before her departure,
she said she thought it easier for her to leave the
world than for those who had children to leave.
A near and intimate friend replied, there were many who loved her;
she said she did not know but it was so, and that love would be consummated hereafter.
Towards the conclusion she said with great tenderness of spirit,
that she thought she was going; and added, "`I would not have you to be troubled,
it is to joy unspeakable and full of glory.`"

She died the 2nd of the Tenth month, 1772; aged about forty-eight years.
Among other of her writings she left the following epistle,
which is thought fit to be here inserted:

[.embedded-content-document.epistle]
--

[.letter-heading]
To the Quarterly and Monthly meeting of Women Friends,
held at Burlington and Chesterfield in West New Jersey, in America.

[.salutation]
Dearly beloved Friends,

In a fresh remembrance of the many seasons of divine favor,
we have been made partakers of together,
in these meetings appointed for transacting the affairs of the church,
does my spirit affectionately salute the living:
and not expecting to have the like opportunity again,
it rested with me to visit you after this manner,
with fervent desires for the prosperity of truth and righteousness in general;
and in a particular manner,
I have a desire that our sex may not fall short in living
up to the faithful performance of their respective duties,
and discharging that trust which the Lord has committed to them, honestly,
as in his sight.
For this good end, I tenderly beseech you all, both elder and younger,
who have known and may know the Master`'s will concerning you, that you may be obedient.
Let not reasoning with flesh and blood, or pleading excuses because of unfitness,
as you may think, prevail.
Bear with me, if I observe, where that is the case,
dwarfishness and weakness will be the consequence,
and the best life is in danger of being quite lost,
as it may with sorrow be remarked of some who profess with us,
that a name to live and be accounted as wise virgins has seemed to suffice,
whose case I have often lamented.
It is the ardent prayer of my soul for such, while I am writing this,
that they may awake to righteousness,
and diligently attend to the teachings of the spirit of the Lord,
who will not fail to fit and qualify for every good word and work.
I am satisfied as that becomes the principal concern of individuals,
the cause of complaining of misconduct would be much removed,
and our Zion would more conspicuously shine,
and there would be none found within her walls barren
or unfruitful in the saving knowledge of God;
but that the ancient promise made to Israel shall
remain to be the portion of his people forever,
"`That he would be as the dew of Hermon,
and as the dew that descended upon the mountains of Zion,
for there the Lord commanded the blessing, even life forevermore.`"
Ps. 133:3.

My dear young friends, with love unfeigned do I affectionately salute you,
whose company in these meetings I have been glad of;
and I would encourage all who have a right to membership,
to the steady attendance of them at the set time,
as often as you can while health permits.
We are, by nature, very short sighted,
and know not when the times of refreshment may come from the presence of the Lord;
and therefore it is good for us to endeavor patiently
to wait and quietly to hope for his salvation,
which I fully believe he is about to reveal in your hearts.
If you are faithful to the discoveries of divine grace,
your understandings will be more and more opened in the mysteries of God`'s kingdom,
even that which was hid from ages and generations; and, as the apostle testifies,
is now revealed by the spirit of the dear Son of God,
our holy advocate with the father.

I have hinted above and hope I shall die in the faith of it,
that the Lord will form a people to himself, that shall show forth his praise,
and will yet beautify the house of his glory.
Under this prospect my spirit is at times deeply bowed in
intercession for the descendants of faithful Friends,
that they may not render themselves unworthy of so great a mercy,
and other especial favors that they are blessed with beyond many;
but that they may not only be the called, but chosen of the Lord.
Now, in a degree of my heavenly Father`'s love, do I affectionately bid you farewell,
desiring that grace, mercy and peace may be multiplied in and among you,
and conclude your true friend,

[.signed-section-signature]
Elizabeth Smith

[.signed-section-context-close]
Burlington, the 30th of the third month, 1772

--

[.asterism]
'''

PRISCILLA GURNEY, wife of Edmund Gurney, of Norwich, was seized in the Sixth month, 1772,
with a bleeding from the lungs, which to her appeared likely to end her
days speedily.
She laid quietly, and said calmly,
she had not anything criminal in outward things on her mind,
and she hoped in the mercy of God.

For many weeks there seemed some flattering symptoms, she said not much about them,
but appeared to be under a secret exercise of mind.
As her husband was sitting by her one forenoon, she, in a very solid,
humble frame of spirit, spoke to this effect: "`My dear, God is good indeed,
a father of tender mercies.
I feel his mercy renewed to me.
I shall die of this illness; but I shall be happy, and I am quite willing to go.
When I was visited with the truth, I had, as it were,
an offer made me of a rich seat in the kingdom of heaven; but,
O the world has been too much for me! and many have been my bitter baptisms for disobedience;
and yet, O you merciful Father! you have forgiven me,
and I shall have a mansion with you to eternity.`"

Many, very many, were the comfortable expressions she uttered upon various occasions.
One evening, on her husband taking leave of her, she said sweetly,
"`I have an afflicted body, but an easy mind.`"
She frequently expressed her perfect resignation to her heavenly Father`'s will,
who might justly be said to be long-suffering and forbearing to her,
though very unworthy; but she had loved and served him in some degree, and further said,
if it was his will to spare her life, and to require it of her,
she would acknowledge him in the congregations of his people,
or in any other way he pleased.

When her three brothers came from London to see her,
observing one of them to be much tendered and affected,
she desired they would not grieve for her, but for themselves,
that they might experience the same comfort when
the same awful visitation might be theirs,
as it certainly in a little time would be: or to the same import.

The second visit her father paid her in her illness, she expressed herself thus:
"`Dear father, I have always loved you.
No child could love a parent more than I have loved you.`"
And after some pause, "`Dear father,
I have been enabled to pray fervently to the Almighty for an easy passage,
and that I might have a small mansion in the kingdom; and, O father,
there never can be a stronger proof of the Holy Spirit for the answer was,
as if it was an outward voice, You shall enter into a full fruition of joy.`"

The divine mercy of God was indeed richly extended to her throughout her whole illness,
and was her stay and support, by which, although her sufferings were great,
her patience and meekness were wonderful.
Such a calmness and composure covered her mind, that she disposed all her affairs,
and directed things to be done after her decease
without any visible discomposure to herself.
She lay many weeks wishing for her dissolution,
and when she thought her husband too anxious for her, she would say,
"`I desire you not to grieve for me.
It would be cruel to desire my continuance in this affliction,
as all will be well with me.`"

The last day of her life, as he was sitting by her as usual,
she desired everybody to leave the room but him and the young woman that attended her;
and after a pause of quietness, she uttered such expressions as these: "`My dear,
it has for some time been a close trying season to me.
Many deep conflicts have I passed through,
and that heavenly peace I felt in weeks past has much left me;
but yet I have a little hope I shall have a mansion in the kingdom.`"
In reply to this state of deep probation,
her husband spoke a little to her as matter came before him,
and she was very calm and humble,
and after a considerable time in silence she called him again to her, and said,
"`How gracious and merciful is God!
I think I now see the seat I was first offered in my heavenly Father`'s house,
and I feel an assurance I shall have it.
This affliction has been a great refinement to my poor mind.
My heavenly Father`'s arms are open to receive me, and I die rejoicing.`"

After this unutterable favor she laid very quiet,
and in divine sweetness fell into a doze.
When she awoke, she expressed her fears lest she should have a hard passage,
wishing it might be otherwise, and seemed revived.
The family were ordered to go to bed, it being about nine in the evening,
except a friend and Elizabeth Parkinson, the young woman who waited on her,
who with her husband sat quietly by her.
About ten o`'clock, without any visible alteration to them, she departed,
having had her desire granted, and no doubt is entered into everlasting felicity.

She died the 4th of the Tenth month, 1772, in the thirty-fifth year of her age,
and was interred in Friends`' burying ground at Norwich, the 11th day of the same month.
