== Chapter 6

[.chapter-synopsis]
* John Woolman
* William Young
* Hannah Dudley
* Samuel Fothergill

JOHN WOOLMAN, of the province of West Jersey, in America, was born at Northampton,
in that province, of parents professing with Friends, who had a tender care over him,
and, being good examples themselves, promoted every appearance of good in him.

About the seventh year of his age,
he became acquainted with the operations of divine love in his heart;
and as he went from school one Seventh-day, while his companions were at play,
he went forward out of sight, and sitting down, read the 22nd chapter of the Revelations:
"`He showed me a river of water, clear as crystal,
proceeding out of the throne of God and the Lamb,`" etc.
In reading of which,
his mind was drawn to seek after that pure habitation
which he then believed God had prepared for his servants.
The place where he sat, and the sweetness that attended his mind,
remained fresh in his memory for many years afterwards.
This and the like gracious visitations had such an effect upon him,
that when he heard boys make use of ill language it troubled him,
and through the continued mercies of God he experienced preservation from it himself;
and the pious instruction of his parents would recur freshly in his mind,
when he happened to be among wicked children, which was of use to him.
His parents, who had a large family of children, frequently on the First-day of the week,
after meeting, employed them in reading the Scriptures, or other good books,
one after the other, the rest sitting by for instruction.

In some memoirs left behind, he records this as a good practice,
and worthy of imitation by those who are entrusted with the care of children.
Thus, in his very young years, through the renewings of divine love on his tender mind,
he was preserved from many snares incident to youth,
until he had attained about the sixteenth year of his age, when,
as appears by his own account,
through unwatchfulness he allowed his mind to be
carried away by a love of improper company,
and, though preserved from profane language or scandalous conduct,
there was still a plant alive which brought forth wild grapes.
Though at times he was brought seriously to consider his ways,
which affected his mind with sorrow, yet,
by an inattention to these reproofs of instruction, vanity was added to vanity,
and repentance to repentance, and his mind became alienated from the truth,
and hasted towards destruction.`'
While, '`says he in his memoirs, '`I meditate on the gulf towards which I travelled,
and reflect on my youthful disobedience, my eyes run down with water.`'

Nevertheless, afterward, his mind became more estranged from the enjoyment of real good,
and he ran greater lengths in vanity,
until it pleased the Lord to visit him with sickness,
which appeared to be nigh unto death; in which state, darkness,
horror and amazement seized his mind,
and he thought it would have been better for him never to have had a being in this world,
than to see such a day of confusion and affliction of body and mind.
Herein he bewailed himself, and cries ascended to an offended God,
who in his mercy at length heard him, and that word which is as a fire and a hammer,
broke and dissolved his rebellious heart into a state of contrition,
which was succeeded with inward consolation and desires,
that if the Lord would be pleased to restore his health, he might walk humbly before him.
Though the first part of his desire was granted, he again relapsed into folly and vanity;
of one instance thereof I take his own account:
'`I remember once having spent a part of the day in wantonness; as I went to bed at night,
there lay in a window near my bed a Bible,
which I opened and first cast my eye on the text, "`We lie down in our shame,
and our confusion covers us.`"
This I knew to be my case, and meeting with so unexpected a reproof,
I was somewhat affected by it, and went to bed under remorse of conscience,
which I soon cast off again.`'

But at length, through the powerful operation of divine love,
he was enabled to take up the cross, and lived a very retired, religious life,
until it pleased the great Author of our being, about the twenty-second year of his age,
to commit to him a dispensation of the gospel ministry; through faithfulness thereto,
he witnessed an increase of those talents committed to his care,
and visited most of the American provinces at different times.
About the year 1763, during the Indian war,
he travelled about two hundred miles into the back parts of Pennsylvania,
though attended with great fatigue of body and danger of his life,
in order to pay a religious visit to an Indian settlement there,
which was favorably received by the natives,
and doubtless was attended with peace to his own mind,
as he found many of them susceptible of divine impressions.
He was for many years deeply exercised on behalf of the poor enslaved Africans,
and both by word and writing, endeavored to convince mankind of that unrighteous traffic,
and injustice of keeping them in slavery.

In the year 1772, with the concurrence and unity of his brethren,
he came over to England to visit Friends here,
and landed in London about the 8th of the Sixth month.
The yearly meeting being then sitting, he attended that meeting,
in the course of which he had to drop several weighty and instructive remarks.
His mind being drawn towards the north, he soon departed from this city,
and by the way of Hertford, Buckinghamshire, Northampton and Banbury quarterly meetings,
he proceeded to the quarterly meeting at York, where,
after having attended most of the sittings thereof, he was taken ill of the small-pox,
in which disorder he continued about two weeks, at times under great affliction of body,
and then departed in full assurance of a happy eternity, as the following expressions,
among others, taken from his own mouth, plainly evidence.

One day being asked how he felt himself, he meekly answered,
'`I do not know that I have slept this night.
I feel the disorder making its progress,
but my mind is mercifully preserved in stillness and peace.`'
Some time after, he said he was sensible the pains of death must be hard to bear,
but if he escaped them now, he must some time pass through them,
and did not know he could be better prepared, but had no will in it.
He said he had settled his outward affairs to his mind;
had taken leave of his wife and family, as never to return,
leaving them to the Divine protection; adding,
'`and though I feel them near to me at this time, yet I freely give them up,
having a hope they will be provided for.`'
A little after said, '`This trial is made easier than I could have thought,
by my will being wholly taken away; for if I was anxious as to the event,
it would be harder; but I am not, and my mind enjoys a perfect calm.`'

In the night a young woman having given him something to drink, he said, '`My child,
you seem very kind to me, a poor creature, the Lord will reward you for it.`'
A while after he cried out with great earnestness of spirit,
'`O my Father! my Father! how comfortable are you to my soul in this trying season.`'
Being asked if he could take a little nourishment, after some pause he replied,
'`My child, I cannot tell what to say to it;
I seem nearly arrived where my soul shall have rest from all my troubles.`'
After giving in something to be put in his journal, he said,
'`I believe the Lord will now excuse me from exercises of this kind,
and I see no work but one, which is to be the last wrought by me in this world.
The messenger will come that will release me from all these troubles,
but it must be in the Lord`'s time, which I am waiting for.`'
He said he had labored to do whatever was required, according to the ability received,
in the remembrance of which he had peace.
Though the disorder was strong at times, and would come over his mind like a whirlwind,
yet it had hitherto been kept steady, and centered in everlasting love; adding,
'`And if that is mercifully continued, I ask or desire no more.`'

At another time he said he had long had a view of visiting this nation;
and some time before he came, he had a dream,
in which he saw himself in the northern parts of it;
and that the spring of the gospel was opened in him, much as in the beginning of friends,
such as George Fox and William Dewsbury;
and he saw the different states of people as clearly
as he had ever seen flowers in a garden;
but in his going on he was suddenly stopped, though he could not see for what end,
but looked towards home, and fell into a flood of tears, which waked him.

At another time he said, '`My draught seemed strongest to the north,
and I mentioned in my own monthly meeting, that attending the quarterly meeting at York,
and being there, looked like home to me.`'

Having repeatedly consented to take a medicine with a view to settle his stomach,
but without effect, the friend then waiting on him said, through distress,
'`What shall I do now?`'
He answered with great composure, "`Rejoice evermore,
and in everything give thanks:`" but added a little after,
'`This is sometimes hard to come at.`'

One morning early he broke forth in supplication in this way:
'`O Lord! it was your power that enabled me to forsake sin in my youth,
and I have felt your bruises since for disobedience,
but as I bowed under them you healed me;
and though I have gone through many trials and sore afflictions, you have been with me,
continuing a father and a friend.
I feel your power now, and beg that in the approaching trying moments,
you will keep my heart steadfast unto you.`'
Upon his giving the same friend directions concerning some little matters, she said,
'`I will take care, but hope you may live to order them yourself.`'
He replied, '`My hope is in Christ; and though I may now seem a little better,
a change in the disorder may soon happen, and my little strength be dissolved,
and if it so happen, I shall be gathered to my everlasting rest,
'`On her saying she did not doubt that,
but could not help mourning to see so many faithful servants removed at so low a time,
he said, '`All goodness comes from the Lord, whose power is the same,
and he can work as he sees best.`'
The same day, after giving her directions about wrapping his corpse,
and perceiving her to weep, he said,
I had rather you would guard against weeping or sorrowing for me, my sister.
I sorrow not, though I have had some painful conflicts; but now they seem over,
and matters all settled; and I look at the face of my dear Redeemer,
for sweet is his voice, and his countenance comely.`'

Being very weak, and in general difficult to be understood,
he uttered a few words in commemoration of the Lord`'s goodness to him; and added,
'`How tenderly have I been waited upon in this time of affliction,
in which I may say in Job`'s words,
"`Tedious days and wearisome nights are appointed unto me.`"
And how many are spending their time and money on vanity and superfluities,
while thousands and tens of thousands lack the necessaries of life,
who might be relieved by them, and their distresses at such a time as this,
in some degree softened by the administering of suitable things.`'

An apothecary who attended him of his own accord,
he being unwilling to have any sent for, appeared very anxious to assist him,
with whom conversing,
he queried about the probability of such a load of matter being thrown off his weak body,
and the apothecary making some remarks implying he thought it might,
he spoke with an audible voice as follows: '`My dependence is on the Lord Jesus Christ,
who I trust will forgive my sins, which is all I hope for;
and if it be his will to raise up this body again, I am content, and if to die,
I am resigned: and if you can not be easy without trying to assist nature,
in order to lengthen out my life, I submit.`'
After this, his throat was so much affected,
that it was very difficult for him to speak so as to be understood,
and he frequently wrote when he wanted anything.
About the second hour on Fourth-day morning, being the 7th of the Tenth month, 1772,
he asked for pen and ink, and at several times, with much difficulty, wrote thus:
'`I believe my being here is in the wisdom of Christ; I know not as to life or death.`'
About a quarter before six the same morning, he seemed to fall into an easy sleep,
which continued about half an hour, when seeming to awake,
he breathed a few times with more difficulty, and so expired without sigh, groan,
or struggle.

He often said it was hid from him whether he might recover or not,
and he was not desirous to know it; but from his own feeling of the disorder,
and his feeble constitution, he thought he should not.

[.asterism]
'''

WILLIAM YOUNG, son of William Young, of Leominster, in the county of Hereford,
and Hannah his wife, she being deceased,
was in his childhood of a sweet and sprightly natural temper,
and although of a tender frame, seemed healthy, until he contracted a cold,
which at length brought on a consumption.

In the course of his affliction his deportment was grave, and as he grew worse,
he became more thoughtful,
and made many sensible remarks of the uncertainty of visible things;
and expressed a grateful sense of the kindness of Providence many ways,
and particularly in the visits and good advice he received from friends.
Although he had been preserved in a more innocent conduct than most young men of his age,
he knew that would not entitle him to the felicity of the redeemed,
and was therefore earnestly desirous of attaining such a state of inward
purity and renovation of heart as would procure divine favor;
and on this account had many painful conflicts.
When his recovery was thought doubtful,
he often lamented his having lost that tenderness and fervency
of spirit towards God which he had formerly experienced.

For many weeks before his death he was apprehensive of his end being near, and said,
'`If I die now in my youth, it may be all for the best,
and may put other young people upon the consideration of their latter end.`'
On his father`'s saying it would be well for us to be resigned to the divine will,
but intimating a reluctancy to part, he replied with much earnestness, '`Aye,
do be resigned;
let us all be resigned;`' and frequently expressed
a desire to be resigned either to life or death;
but said, if it pleased the Lord to fit him for his change,
and take him from the slippery paths of life at so early a period,
he should think it a favor; for he had no desire to live,
except it was to the glory of his Creator.

He several times showed great concern at hearing
of the disorderly walking of some among us,
and a deep sense of the wonderful goodness and condescension
of Christ in suffering for mankind.

Some weeks before his death, observing his sister weep, he said, '`We must part.
I must leave you; but I hope and believe we shall meet again.`'

The 2nd of the First month he was very ill, and seeing his father affected, he said,
'`father, what a mercy it would be if the Lord should be pleased to take me to himself!
Do not grieve, for if I should be spared and turn out naught,
it would be a greater affliction.`'

The next morning, after having had a very bad night, he was weak and low,
but appeared quite calm in mind; and on his sister`'s saying,
after some other conversation, she hoped he was resigned, he replied with much sweetness,
'`Yes, sister, I hope I am quite resigned to the Almighty`'s will;
but surely if it is his will,
it will be a mercy to be taken from this troublesome world to himself.
And I have a hope he will take me to himself;
he has been pleased wonderfully to calm my mind.`'
She observed there was great room to hope,
and that the sufferings of his friends would be greatest; he replied very earnestly,
'`my sufferings will be nothing in proportion to my
offenses! but I have a hope my offenses will be forgiven.
O how merciful is the Lord!
How great is his goodness!
How pure is his love!
Mercy, goodness, purity, belong to him.`'
Seeing his sister much affected at what he said, he continued, '`We cannot tell, sister;
some worse than I have been restored.
He is able to raise me up, and if he should,
and make me some sort of a member (meaning of his church militant),
I hope I shall be careful to keep near to him; but I desire not to live, no,
not a moment, as one of this world.`'

That night he was so weak, those about him were apprehensive he could not continue long.
The next day he seemed pretty free from pain, but drowsy, and his expressions rambling,
but innocent; indeed, his countenance and conversation were sweet and lamb-like.
The next morning he desired to be put to bed, being in great pain,
but could not rest there;
and being replaced in the easy chair and same posture he had lain in for many nights,
he seemed much easier, and told his sister he was going;
she said she hoped to a better inheritance; he replied, '`Aye,
for I believe in one that can save me;`' and repeatedly
said the fear of death was taken away.
And a day or two before his death, he said, '`I am going to leave an affectionate father,
to meet the great Almighty Father.`'

Another time, his sister saying it was a favor he was preserved so patient, he said,
'`I hope I shall be kept so; I am under the Lord`'s care entirely; nothing else will do.
I see nothing else will do.`'
The same day he uttered many sweet and lively expressions,
but his voice was too low to be understood, so as to connect the sentences.
The day before his decease it was so weak and broken,
that he could scarcely articulate a sentence; but was meek and patient as a lamb,
and once said something about rejoicing in the house of God,
and when he could no otherwise express himself,
would reach up to kiss his father and sister, his heart being full of love.
When asked if he would have anything sent to his eldest sister then in Cornwall,
he said, '`Nothing but my love, or dear love; adding, '`In that love I feel for all.`'
He frequently desired those about him not to grieve, and would sometimes say, '`Why,
if you think I am going well, should you grieve?`'
and observed, that if he had brought on his illness by any bad course of life,
it would be hard to bear; but added, '`I believe you have no reason to think I have.`'

He took a most affectionate leave of his sister, bidding her love and adore the Lord;
and said something about his father, which could not be understood.
His father then telling him he hoped there was a
place prepared for him among the blessed,
and that he loved to be with the good, he replied as well as he was able, '`Aye, dearly,
dearly.`'
And in about two hours after, he departed so quietly,
that those present apprehended him to be fallen asleep, the 7th day of the First month,
1773, in the nineteenth year of his age.

[.asterism]
'''

HANNAH DUDLEY, late wife of Robert Dudley, of Clonmel, in Ireland,
was born at Woodbridge in Suffolk, and religiously educated, which was blessed to her.
Through the prevailing power of divine love,
she was brought to know a state of submission to
several near trials which fell to her lot;
and having her heart weaned from the world and its delusive profits and friendships,
she became more and more refined, being an example of humility, plainness,
and self-denial.

About the year 1772 some symptoms of a consumption appeared,
but for some time she attended meetings both for worship and discipline,
in some of which she was enabled to bear a living testimony to the truth.

In the course of her illness many friends visited her,
to whom she was enabled to drop some tender expressions,
and it seemed to be her greatest joy to see and hear of the prosperity of truth;
and at several opportunities she had suitable counsel
and instruction to give to those about her.

About a week before her departure, our friend Robert Willis, of West Jersey in America,
being in the course of his religious visit at her house,
had a comfortable and tendering opportunity with her, her husband and sister.

About two days before her decease,
she dropped much excellent advice to her husband and sister,
expressing her desire to be released;
but added her hope she should be preserved patient to the end;
and afterwards on some mitigation of her pain,
signified her entire resignation to the divine will.
Speaking to her husband`'s eldest son, in a very weighty manner,
she advised him to remember her admonitions; saying also, '`Shun bad company,
obey your parent, and do not offend him; seek the Lord and he will be found of you,
but if you forsake him, he will cast you off forever.`'

To their apprentice she said, '`Jemmy, love plainness and continue in it,
for truth leads to plainness.
You have been favored with an education beyond many, therefore prize it,
and have known truth, therefore beware of trampling on the testimony,
but be circumspect in all your ways and conduct.
You are just entering on the slippery part of life, the slippery paths of youth,
and are no stranger to the temptations and allurements of the adversary.
I have often thought it a great mercy that you have
been preserved from (I believe) almost any vice.`'
Just after, she very affectionately took her leave of her brother and sister-in-law,
saying, '`Our acquaintance has been short,
but we have loved one another;`' and then prayed very fervently
that a blessing might rest upon their family.

Being pressed to try and take a little sleep, she replied,
'`O that I could sleep in the arms of my beloved!`' And with great fervency prayed,
'`O Lord God, have mercy upon me! and let your compassionate ear be opened.
Lord God Almighty! send the guardian angel of your presence to conduct my spirit.`'
After which she lay in great peace and serenity of mind, growing weaker and weaker,
yet sensible to the last, and with her hand closed in her husband`'s,
departed without sigh or groan, as one falling into a sweet sleep,
the 25th of the First month, 1773; aged about forty-seven years,
a minister about nine years.
After a very large and solemn meeting, her body was decently interred the 29th,
in Friends`' burial-ground in Clonmel aforesaid.

[.asterism]
'''

SAMUEL FOTHERGILL, of Warrington, in Lancashire,
was the sixth son of our worthy ancient friend John Fothergill mentioned in this treatise,
and of Margaret his wife.

This their son being of an active and lively disposition,
and during his apprenticeship mostly from under the
watchful eye of his affectionate parent,
he fled from the holy cross of Christ,
and indulged himself in the gratifications of folly and licentiousness,
violating the repeated convictions of divine grace in his own mind,
which had been mercifully extended from his early years,
thereby wounding the soul of his tender father,
of whose religious care to form and lead the tender minds of his children
to piety and virtue we have an account in the memoirs of his life.
Yet his pious admonitions proved, nevertheless, as bread cast on the waters,
which returned after many days; for about the twenty-first year of his age,
the visitation of divine love was so powerfully renewed,
that it proved effectual to turn his steps out of the paths of vanity; and,
as he has expressed, with humble and awful gratitude to the Preserver of men,
it then appeared clear to his understanding,
that would be the last call the Heavenly Father would favor him with.
He therefore consulted no longer with flesh and blood,
but gave up to the holy visitation,
devoting his whole heart and affections to seek reconciliation with God,
through the mediation of Jesus Christ;
and abiding in great humility under the purifying operation of the Holy Ghost and fire,
he became thereby qualified for those eminent services he was called into.
In a few months, by the constraining power and love of God,
his mouth was opened to bear a testimony to the sufficiency of that holy
arm that had plucked him as a brand out of the fire.

Thus a dispensation of the ministry being committed to his charge,
he attended faithfully thereto, and moved therein at the requirings,
and under the direction of, divine wisdom,
by which means he soon became an able minister of the gospel,
called thereto and qualified by the Holy Ghost.
Under this influence he labored with diligence,
and devoted much of his time and strength, when health permitted,
to the service of his dear Lord and master,
for the continuance of whose favors he counted nothing too near or dear to part with,
that he might be instrumental in gathering souls to God,
which was the object he had in view in all his gospel labors.
Being diligent himself,
he endeavored much to excite Friends to a due and
constant attendance of meetings for religious worship,
and those for the discipline of the church.

Through the course of his gospel labors, both in public and private,
animated by divine love,
he expressed an uncommon warmth of affection for the rising youth of this generation,
with whom he was led into a deep brotherly feeling
and sympathy for their present and eternal welfare;
under which concern his love to this class of both sexes, under all denominations,
was strong and ardent.

He travelled much in England and Scotland, several times in Ireland,
and once through most of the North American colonies, in the service of truth; where,
though singularly humbled in a sense of poverty,
weakness and insufficiency on his first landing, he was, by accounts received,
marvelously strengthened, both in public and private, in gospel authority and love,
to the awakening and comforting of many.

In the forepart of the year 1769,
he visited most of the families of Friends in the monthly meeting of Gracechurchstreet,
London;
in which service he was divinely strengthened and enabled to extend
a helping hand to many in close and necessary labor,
for their increasing care, to live and act consistently with our holy profession,
to the comfort and help of many, and his own peace; and afterwards,
at two different opportunities,
he visited the families of Friends in Horslydown
and Westminster monthly meeting in that city,
to the same good effect.

He mostly attended the yearly meetings in London, and other places,
when of bodily ability; in which his gospel labors were very acceptable and edifying;
being particularly careful, when called from home,
to return to his family and friends with as much
expedition as the nature of his service would admit.
Having acquired a moderate competency by his diligence and industry,
he declined trade for several years before his decease,
devoting his time and talents to the service of the churches.
As a pillar in the Lord`'s house he was steadfast,
being actuated by a Christian and manly zeal; in deportment grave;
his private conversation was savory and edifying, corresponding with his ministry,
which at times went forth as a flame, piercing the obdurate,
yet descended like dew upon the tender plants of our heavenly Father`'s planting,
the true mourners in Zion; with these he travailed in a deep sympathy of spirit.
In his gospel labors he was free from affectation; in doctrine, clear,
sound and pathetic, filled with charity, allowing for the prejudices of mankind,
being indeed a minister and elder worthy of double honor, speaking whereof he knew,
and what his own hands had handled of the good word of life.

He endured a long and painful illness with much patience and resignation;
and towards the close of his time, expressed himself to some of his relations,
when they took leave of him,
previous to their setting out for the yearly meeting in London, to the following effect:

'`Our health is no more at our command than length of days:
mine seems drawing fast towards a conclusion;
but I am content with every allotment of Providence, for they are all in wisdom,
unerring wisdom.

There is one thing which, as an arm underneath, bears up and supports;
and though the rolling tempestuous billows surround, yet my head is kept above them,
and my feet are firmly established.
O! seek it, press after it, lay fast hold of it.

Though painful my nights, and wearisome my days,
yet I am preserved in patience and resignation.
Death has no terrors, nor will the grave have any victory.
My soul triumphs over death, hell, and the grave.

'`Husbands and wives, parents and children, health and riches, must all go.
Disappointment is another name for them.
I should have been thankful had I been able to get
to the ensuing yearly meeting in London,
which you are now going to attend, where I have been so often refreshed with my brethren;
but it is otherwise allotted.
I shall remember them, and some of them will remember me.
The Lord knows best what is best for us.
I am content and resigned to his will.

'`I feel a foretaste of that joy that is to come;
and who would wish to change such a state of mind? I should be
glad if an easy channel could be found to inform the yearly meeting,
that as I have lived, so I shall close, with the most unshaken assurance,
that we have not followed cunningly devised fables, but the pure, living,
eternal substance.

'`Let the aged be strong, let the middle-aged be animated, and the youth encouraged;
for the Lord is still with Zion; the Lord will bless Zion.
If I be now removed out of his church militant,
where I have endeavored in some measure to fill up my duty,
I have an evidence that I shall gain an admittance into his glorious church triumphant,
far above the heavens.`'
My dear love is to all them that love the Lord Jesus.`'
He departed this life at his house in Warrington, the 15th,
and was buried the 19th day of the Sixth month, 1772, at Penketh,
in the fifty-seventh year of his age, and the thirty-sixth of his ministry.

And now, Reader, before you close the book, pause a little, and consider,
what progress you have made in this heavenly race.
The prophet Isaiah, after describing the coming of Christ,
and very emphatically setting forth his office, the peaceable government of his power,
and its glorious effects upon his followers, in chap.
xi., in the next chapter declares what the faithful experience:
'`And in that day you shall say, O Lord!
I will praise you; though you were angry with me, your anger is turned away,
and you comforted me.
Behold, God is my salvation, I will trust and not be afraid,
for the Lord Jehovah is my strength, and my song, he also is become my salvation.`' Isaiah 12:1-2.

The same living, divine power,
the same inexhaustible source of wisdom and goodness remains.
The enjoyments of time are transient, its pleasures are delusive;
let therefore all trust in his arm: this is the strength and beauty of men;
their alone help and dependence is here, in all their exercises through time,
that when they come to close, as has been the case with the just in all generations,
in effect, to declare, "`Behold, God is my salvation, I will trust and not be afraid;
for the Lord Jehovah is my strength and my song, he also is become my salvation.`"
