== Preface.

The general approbation which publications of this kind have had,
makes a continuance of the collection desirable.
Memorials of the circumspect lives and dying expressions
of such as finish their course well,
show the efficacy of the divine principle +++[+++the holy spirit of the Lord Jesus]
which we profess,
and that obedience to its dictates yields the peaceable fruits of righteousness.

To promote an attention to this principle in the youth,
to whom this is particularly addressed,
the following accounts of many who have been faithful in their day,
are recommended to their perusal; with the intent that, excited by the example,
they also may fill up their duty as they go along,
and partake of the same peace these had to rejoice in,
when no human help could afford them comfort.
The experience of those who are gone before, is as a waymark to those who follow after;
and their example calls loudly, "`Follow us, as we have followed Christ.`"

Those who in early youth are happily brought under the teachings of this divine principle,
and are faithful to its precepts,
are prepared to encounter the world and all its allurements.
If prosperity be their lot, they can receive it as the bounty of an Almighty Father,
and keep in that state of humility which becomes dependent beings,
applying it to the honour of Him who has entrusted them therewith.
If afflictions attend,
and it is sometimes the lot of good men to experience
adverse winds and tempestuous seasons,
they can look with a humble confidence to Him for protection in their conflicts,
and bow to the hand which has permitted them.

It was not the offering of any temporal things, according to the Psalmist; but, says he,
"`Offer unto God thanksgiving; pay your vows to the Most High;
then call on me in the day of trouble, and I will deliver you,
and you will glorify me,`" Psa. 50:14-15.
This has been the experience of those who have had their trust in God`'s power,
in every age; and as they have gone along in this valley of tears,
for such it has been to many, they have, from time to time, had their faith renewed,
and their hope confirmed, so as to set up their Ebenezer,
"`Hitherto has the Lord helped us.`"
"`We have,`" as says the apostle,
"`no continuing city here;`" neither have we any state of
security beyond "`Give us this day our daily bread.`"

Whatever may be our growth and experience in religion,
it will never go beyond that state of dependence.
Our only safety is a truly humble state, wherein the mind is exercised in a daily watch,
care, and travail, for the arisings of the divine life; under a sense of which,
such have a hope that He who has been their morning light,
and hitherto conducted in safety, will, in the conclusion, be their evening song; and,
in effect, adopt the language of the prophet, "`I will greatly rejoice in the Lord;
my soul shall be joyful in my God;
for he has clothed me with the garments of salvation.`"

[.signed-section-signature]
Thomas Wagstaffe

[.signed-section-context-close]
Stockwell, Surry, Eleventh month, 1795.
