== Chapter 1

[.chapter-synopsis]
* Luke Howard
* Margaret Fox
* Lucy Chopping
* Thomas Wilson
* Andrew Jaffray
* Thomas Thompson
* George Chalkley
* James Dickinson
* Benjamin Holme
* John Hayward

LUKE HOWARD, of Dover,
was a serviceable man in the early breaking forth of truth in this nation,
a faithful sufferer for its testimony, and preserved to the end in peace.
The following account is extracted from a short journal and collection of his writings.

In his tender years he experienced in himself the
appearance of the love and grace of God,
reproving for evil; and when about fourteen years of age,
he was bound an apprentice to a shoemaker in Dover.
His master, being in a seeking state,
and having forsaken the public worship and joined with some who were separated from it,
treated him kindly; which so wrought on him,
that he took a resolution to become more conscientious towards God,
and more orderly to his master, than he had been,
not daring to wrong him by neglecting his work.
Thus he served out his apprenticeship to his master`'s content; and,
a few weeks after his time was expired, he came to London to work,
frequented a meeting in Coleman-street, and was admitted a member thereof.
The war between the king and parliament being then very hot,
and forts raising about the city, he sought to be entered in the army;
but many pressing to go, '`It was my lot,`' says he, '`to be left out;
that so I might be clear of the blood of all men, as since I have seen it and rejoice,
though then troubled at my dismission.`'

He then returned to Dover, where there were several young men inquiring the way to Zion,
with their faces thitherward, and searching the Scriptures,
hoping to find the right way.
'`There, and in that day,`' says he,
'`I was convinced that singing of psalms in rhyme and meter,
was a lie in me as to my own condition, and a mock service as to the Lord;
and was forced to sit silent under the cross, when others sung.`'
This, at that period, was so strange, that the priest took notice of him,
and in a little time it was noised abroad as a great wonder,
that he refused to sing psalms.
His master, with whom he had served his apprenticeship, being also troubled at it,
got Samuel Fisher, their priest, to come and discourse with him.
Fisher had much to say to him: '`But,`' said he,
I said what was in my own conscience manifested,
and I did not know another in the world of my mind; but so it was, my peace abounded,
and knowledge increased.`'
Samuel Fisher returned home, and never dared to sing more in the steeple-house;
but was soon after convinced of the everlasting truth,
in which he ended his days in prison, for his testimony thereto.

Luke Howard, meanwhile, went among the Brownists, also the Presbyterians,
and the Independents, and then among the Baptists,
with whom he chose rather to join than with any other.
He passed through their ceremony of water baptism,
but still knew not where to find a resting-place,
not knowing he had a guide within him to keep him out of all evil;
and in this state he mourned with tears.
Nevertheless he got over his convictions, and went into liberties;
'`In this great loss,`' says he,
'`I continued until I did, as too many do, got above the witness,
and I sought to make merry over it, and to take my fill of the world,
with all I could enjoy thereof.`'

But soon after,
coming to London on business he went to hear a preacher in Lombard-street;
and afterwards a young man, named William Caton, stood up,
and sounded an alarm out of Zion,
and proclaimed the gospel of peace out of the Lord`'s holy mountain;
but L. Howard`'s mind being after visible things, he slighted it at that time.
The next First-day, being at home, he was told a Quaker was preaching; and,
going to see what manner of man he was, found him to be the afore-named William Caton.
Luke was reached by his testimony,
was a guard to him from the boys and others who offered him abuse,
and in the evening went to visit him, where he found his companion, John Stubbs.
He invited them to go home with him, which they did, and had several meetings there,
and their testimony was to him as a pleasant song, and he bore them company out of town.
Then exercise fell to his lot,
but he was led along in safety under the teachings of truth,
so that he expresses himself thus,
after giving an account of the exercises he had to pass through: '`My experience has been,
and is, as I abode in obedience to the Lord, in waiting on him,
which I hope I shall ever do; the word of the Lord opened to me when in a great strait,
saying, "`I will cleave the rocks and mountains,
that the redeemed of the Lord may come to Zion;`" at which I felt and saw a little light,
and a hope sprung up of getting over and through those rocks
and mountains of thick and black darkness in me,
which the enemy presented to be so great, that it was impossible to get over.
So then, and ever since, in that grounded hope, as an anchor to my soul,
I have cast my care upon the Lord, and have rode through many bitter storms, and,
I bless the Lord, my flight has not been in the winter, and now, I hope in the Lord,
it will not be in the Sabbath-day.
Even so, amen.`'

In the course of his pilgrimage it was sometimes his lot to be imprisoned.
Once he was sent to Dover castle, with three more, and detained sixteen months,
because he could not forbear meetings.
At this time he employed six men in his trade,
but he was obliged to shut up his shop for six months,
neither could he work in prison for a time;
but obtaining the liberty of an entry to the grate,
where they drew their meat up with a cord, he worked a little there,
and his wife kept cows and sold milk, to assist in supporting his family; '`and,`' says he,
'`I had perfect peace, joy, and content, in it all; and the Lord made it all good to me,
both within and without.`'
It also appears he suffered a long imprisonment in the castle, in 1684; during which,
he often pleaded with the magistrates on account
of their cruel and unjust treatment of him.

Thus persevering, he was preserved in greenness to old age.
The following expressions were taken down during his illness by a friend present,
as delivered:

'`God, the Lord of heaven and earth, appeared to me in an acceptable time,
in the year 1655, by his word, through his servants John Stubbs and William Caton,
in the gift of his grace, the Son of his love, Christ Jesus,
whom he sent out of his own bosom, and by the sword of his own mouth,
and by the brightness of his arising, cut me off from the wild olive tree,
which I was rooted in by transgression, and grafted me into the true olive root,
the life of which is the light of the world, and by his love and spirit in my heart,
raised me to worship him in spirit and truth.
Then the cross appeared so great, that if it had been his will,
I would rather have parted with my natural life, if I could have had peace,
than to have taken it up; but in the day of his love and power, through the word of life,
and the arising thereof, I was made willing to do his will, and to take up the cross,
not for a little while, but with a resolution as long as life continued.
And though many temptations have attended, yet the Lord has delivered me out of them all,
and has engaged my soul and all within me, to serve him in newness of life,
and begot and continued a breathing,
that he would never give more knowledge than he would give me power to obey,
and in the day thereof has made me willing to serve him, and deny myself,
and his reward is and has been in my bosom.
He is worthy to be worshipped, obeyed, and feared forever,
for he speaks peace to his children, that they turn not again to folly.
In his peace stands my rest, which rest remains for the people of God, and in this,
I take my leave of the world, with soul, body, and spirit, given up to the Lord,
in and through his grace, the life of Christ Jesus, in whom all the promises are yes,
and amen.`'

He departed this life the 7th of the Eighth month, O. S. 1699.

The Morning Meeting of London, in a testimony concerning him,
dated the 26th of the Sixth month, 1704, say, he was preserved to the end,
and died in the faith of our Lord and Savior Jesus Christ;
and we doubt not that he received the crown of righteousness,
from God the righteous judge.

[.asterism]
'''

MARGARET FOX, widow of our ancient Friend and elder George Fox,
was convinced of the principle of truth,
on his first coming into that part of Lancashire where she dwelt, in 1652;
being then the wife of Thomas Fell, one of the Welsh judges,
a man much esteemed in his country for his wisdom, moderation, and mercy,
being also a tender husband and loving father,
and one who sought after God in the best way it was made known to him.
He frequently entertained those who were accounted serious and godly men;
and had often prayers, and religious exercises in the family;
and in this manner also Margaret was seeking after the right way for many years,
though often afraid she was short of it.

She was born in the year 1614; her parents were of honorable repute in that country,
and her father, John Askew, was of an ancient family and estate,
and a pious charitable man.
It was in the seeking state before-mentioned that it pleased
divine wisdom to move the heart of George Fox,
to visit the family of the judge, who was then in London,
and to open to them the eternal truth; by which means the minds of herself, children,
and a great part of the servants, were convinced and turned to God.
When the judge returned home, and found the great change wrought on them,
he was much surprised, and appeared to be troubled; but Richard Farnworth,
and some other friends, who came to the house soon after George Fox had been there,
had some discourse with him, and he was still and quiet, and weighed things.
George Fox returning in the evening, and being admitted,
spoke so powerfully and convincingly,
that the judge was so far satisfied that it was the truth,
that he offered his own house as a meeting-place, and was kind to Friends,
on every occasion, to his decease: which was about the year 1658,
being then sixty years of age.

His widow labored to promote the cause of truth, applied frequently to the king,
on behalf of her suffering friends; and visited them in various parts of the nation,
sometimes accompanied by one of her daughters.
About the year 1661, she was sent for from her own house,
and carried to Lancaster castle, because she would not swear; was premunired,
and sentenced to forfeit her real and personal estate to the king,
and to be imprisoned during life; but after having been in prison about four years,
she was set at liberty by order of the king and council.
Soon after this she was married to George Fox, but was again, on the old premunire,
taken from her house, and carried to prison;
where she.continued another year in a sickly state,
till her husband obtained her discharge under the great seal.
All these sufferings she endured with much patience, and neither fainted nor murmured;
but was kept so cheerful and easy under them, that her enemies were amazed to see it;
and several of them that persecuted her came to nothing; while,
as she denied and despised the glory of this fading world, for Christ`'s and truth`'s sake,
God gave her honor and a name among the righteous; and qualifications, many ways,
for considerable service in the church.
In this she shone as a morning star, being filled with real wisdom and understanding,
for the propagation of truth and righteousness; of a clear discerning of spirits,
and the working of the enemy to draw from the life and power of truth,
into a liberty that genders to bondage,
and to separation and breach of unity among friends;
appearing firm and zealous against the same.

She was fervent and living in her ministry,
and in supplication and prayers to Almighty God;
to the edifying and building up many in that most precious truth,
which gives victory over the world.
She was not only a great and exemplary sufferer for truth,
but a visitor and a sympathizer with the faithful in their sufferings;
zealously interceding for their relief, with such as were in authority;
as being afflicted with the afflicted, and mourning with those that mourned.

She never spared herself in her manifold labors on truth`'s account,
both in her ministry abroad, in most places in this nation, and other services;
but approved herself as one that needed not to be
ashamed of her work and service for the Lord,
his truth, and people; which she performed with all sincerity,
while God was pleased to give her strength and ability.

She was preserved in a good understanding to the last; and in the time of her sickness,
she was in a sweet frame of spirit.
She uttered many heavenly expressions near her conclusion in this world,
some of which are as follows:

'`Come, come,`' said she, '`let us join to the Lord, and be of one spirit;
let us join to the Eternal God, and be of one spirit.`'
A friend visiting her, who had been acquainted with her upwards of forty-five years,
she said, '`The Lord is with me, and I am with the Lord, and in him only will I trust,
and commit all to the divine providence of the Lord,
both concerning my children and grandchildren, and all things they do enjoy from him,
both in spirituals and temporals;
who is the God of all the mercies and blessings to his people throughout all generations;
to him be glorious praises forever, amen.`'
At another time she said, '`Oh, my sweet Lord,
into your holy bosom do I commit myself freely,
and not desiring to live in this troublesome, painful world, it is all nothing to me,
for my maker is my husband.`'
At another tine she said, '`Come, Lord, I am freely given up to your will.`'
Again she said, '`I freely forgive all people upon the face of the whole earth,
for any wrong done to me; as freely as I desire to be forgiven:
'`and seeing those about her sorrowful, she said, '`Be quiet,
for I am as comfortable in my spirit as ever I was.`'
A little before she departed, she said to one by her, '`Rachel, take me in your arms:
I am in peace.`'

She departed this life at Swarthmore-hall, the 23rd day of the Second month, 1702,
being near the eighty-eighth year of her age;
and was buried in the burial-ground at Simbrooke, belonging to Swarthmore,
the 27th of the same, attended by many Friends and others.
Her writings were collected and printed in an octavo volume,
from which the foregoing account is extracted.

[.asterism]
'''

LUCY CHOPPING, of Stebbing, in Essex, whose maiden name was Wait,
was born in Worcestershire, in the early part of the last century.
She was soberly and religiously educated by her grandmother, who lived to a great age,
being in her one hundred and fourteenth year when she died;
and who often informed her of the hard sufferings many of the family had gone through,
on account of religion, in Queen Mary`'s days.
After her death, she was left under the care of an uncle, who was a Puritan,
and had a tender care over her.
He gave her good advice, and cautioned her to shun idle company,
never to learn to dance or to read ballads, nor to wear lace nor ribbons on her clothes;
but to go and hear the best men that preached at that time:
so that she acknowledged that it was good for her that she had been so warned.
She came to London in the time of the civil wars, and lived in a religious family,
who wanted her to learn to sing psalms, which she was not easy to do,
but returned back into Worcestershire.
About this period, many were going to New England,
and thinking that all who went there at that time,
to enjoy the liberty of their consciences, were good and religious people,
and that it must be pleasant living in such a land, where all were such,
she inclined also to go there; but, communicating her mind to Vavasor Powel,
an eminent preacher among the Puritans in that day,
he told her that the word was near in her heart and mouth,
that she might hear it and obey it;
and that she need not go beyond the seas on that account.
This stopped her journey;
but she still earnestly sought to hear those preachers who were accounted gifted men.
She went to hear Humphrey Smith in particular,
who was esteemed to have an excellent gift,
and did not think it lawful to take money for preaching.
He, being once at a meeting, sat a great while in silence;
at which the congregation wondering, he stood up,
and told them that he had formerly spoken what was opened to him, '`But now, '`says he,
'`my mouth is stopped, and I believe, whenever it may please the Lord to open it again,
it will be more to his glory than ever it has been.`'
This made her very desirous to know where he went;
but soon after it pleased the Lord to send one of his servants, called a Quaker,
by whom Humphrey Smith was more fully convinced, as she also was herself.

In a little time it pleased the Lord to qualify him for the ministry;
and he travelled abroad, in the service thereof, into the west of England, where he,
with many more, was imprisoned.
She then found it her concern to visit them in prison;
and went from one prison to another,
doing them service in mending and making their clothes;
and many of them being far from their homes, she went and visited their families.
She spent many years in this service,
which was very acceptable to those that could not
have liberty to see their families themselves;
and great was her labor of love, in that she did it freely,
although she travelled on foot: be sides which,
she frequently attended the yearly meeting, when established.

Having, at the request of her friend Humphrey Smith, conducted his son into Essex,
where he was bound an apprentice, she often went to visit him.
At length she became the wife of John Chopping, of Stebbing;
with whom she lived but about two years, and survived him about twenty-eight years.
She was a mother in Israel, of a good understanding,
a visitor of the afflicted in body or mind,
and often had a word of advice and comfort to them.
She particularly exhorted the young convinced to faithfulness;
and when any were grown careless, she was tender in advice and exhortation;
and often to so good effect, as to reach the witness in them.

About two weeks before her death, she walked six miles to a meeting,
in order to visit a woman, who, being overcome with the cares of the world,
neglected meetings: whom she warned of her danger,
and who became more careful afterwards in her duty.

The day following she was taken ill, when she expressed herself thus:
'`I cannot say that what I feared is come upon me, but that which I have long desired;
for I am very ill, and do think it will be my end.
But it will be well with me.
I shall go to my mansion which is prepared for me
and all the faithful followers of the Lamb;
and I have nothing to do but to die.
The Lord has been with me, even as with Jacob, and I knew it not; and,
blessed be his name, he has been with me,
and made known the way of life and salvation to me,
and preserved me through many hard exercises and deep afflictions,
and sorrowful travails in spirit.
He has been with me through my pilgrimage, and kept me safe through many long journeys,
in which I have walked many hundred miles, to serve my friends in the truth,
and for the truth`'s sake, and mostly alone; and the Lord preserved me,
so that none were permitted to do me any harm:
for which I have often been humbly thankful, and now I feel peace,
and shall in a little time rest with Him in everlasting joy and peace.`'

At another time she said, '`It is good to have nothing to do but to die:
for now I feel it hard to bear the pain and sickness of this body.`'
She often expressed her concern for the churches, that good order might be kept up;
and for the poor, for whom she always had a great care.
A woman in high station visiting her, she advised her to prepare for such a time;
telling her she had peace,
and that was of more worth than all the pleasures of the world;
and advised her to mind the gift and manifestation of the Spirit in her,
which would lead her also into the way of life and peace.
The woman, filled with admiration, said she never heard the like,
that any person could have such a satisfaction and victory over death,
for that there was no terror or fear of death in her; to whom Lucy Chopping answered,
'`Perfect love casts out fear.
I have loved the Lord with all my heart, and served him with all my strength,
and I have peace: the Lord is with me, and it will be a glorious change.`'
Again she said, '`The Lord has been with me in many hard afflictions, and given me hope,
which has been as "`an anchor to my soul.`"
I can say with David, "`He has plucked my feet out of the mire and clay,
and set them upon a rock,`" and I shall not be moved.`'

Growing weak, and having many sick fainting fits the day before she died, her niece,
Elizabeth Wyatt, offered her something to take; she answered, '`I lack nothing;
the Lord is with me, and his Spirit comforts me.
I have bread to eat which the world knows nothing of,
and the wine of his kingdom refreshes me, and I desire no more of this.
Do not endeavor to keep me here, for to die will be my gain,
and though my body grows weak, my inward man grows strong.
Speaking to her niece, and giving her good advice, she said, '`The Lord is with me,
and I have an earnest of that which I shall in a
little time launch into the full enjoyment of.`'

She departed this life, being sensible to the last, the 6th of the Sixth month, 1705,
and was buried in Friends`' burial-ground at Stebbing.

[.asterism]
'''

THOMAS WILSON, of Ireland, was born in Cumberland,
and educated in the profession of the church of England.
While a youth he had great hungerings after righteousness,
and the true knowledge of the living God, and his son Jesus Christ;
and went with great diligence to hear the priests, and carefully minded what was spoken.
If he heard of a priest that was noted for a good man,
and preached two sermons in one day, he would go sometimes eight miles on foot,
after hearing the morning sermon, to hear another in the afternoon;
and the more he sought to hear, the more his hunger and thirst increased,
so that he was sensible of great poverty of spirit.
In the time of singing psalms a thoughtfulness came over him,
that men should be made holy before they could rightly
sing to the praise and glory of God;
and he was stopped from singing them, through a godly sorrow which was in his heart,
with secret cries and humble prayers to the living God of heaven and earth,
for the knowledge of the way of salvation.
In this state he travailed in great godly sorrow, weary of the heavy load of sin,
as also of the doctrines and worships of men`'s making;
and many texts of Scripture being opened to his understanding,
he began to see that which was not of faith was sin, even in points of worship,
and the pretended service to the great God.

Being thus made sensible that too many of the doctrines of the church,
in which he was educated, were precepts of men`'s making; and that "`God is a spirit,
and they that worship him,
must worship him in spirit and truth;`" this worship he greatly longed to know;
and conversed with priests thereon, but they could not direct him where to find it.
But, after long travail of spirit, and great concern of soul,
the Lord was graciously pleased to make him sensible, that what was to be known of God,
was manifested in man.
About this time he went into an evening meeting of the people called Quakers,
with strong desires in his mind to the Lord,
that if it was the true way of salvation which this people preached,
he might have some inward feeling and testimony thereof in his own heart.
After sitting some time in silence, a friend began to speak,
directing and exhorting to an inward waiting upon the Lord in faith,
to receive power from him over every unclean thought,
by which heavenly power they might glorify and praise the name of the Lord,
through the ability of his own free gift.
This Thomas understood to be the holy word of grace, which the apostle preached,
and to which he turned the minds of the people;
and he felt his soul much in love therewith, saying in his heart,
'`This is what I greatly wanted.`'
The Lord`'s power arose in the meeting to the breaking and tendering of his heart;
and inward cries were raised in him to this effect, "`O Lord,
create in me a clean heart.`"

Now his heart was opened, and he felt the Lord`'s fierce anger because of sin;
and he was made willing to love, and dwell under, his righteous judgments,
being truly convinced that was the way to come to the mercy-seat.
He saw he was to cease from the doctrines of men, and mind the gift which was in him,
and sit down among friends in their silent meetings,
to wait on the Lord in retiredness of mind, for his heavenly teachings and holy leadings;
in the performance of which inward, divine, and heavenly worship, he,
with many more young people, was convinced of the inward work of God,
and turned to the Lord with all their hearts.
Those who attended this meeting from time to time,
became very tender and heavenly-minded, and in great love with each other:
the heart-tendering power of the Lord being renewedly felt, inwardly revealed,
when no words were spoken.

This our friend being thus raised up and qualified, came forth in a public testimony;
and was concerned not only to travel and visit many parts of this nation, Scotland,
and Ireland, but also America; which he visited twice, in company with James Dickinson.
He left there many seals of his ministry, which was sound, plain, and powerful,
frequently attended with a heavenly sweetness,
as he was divinely enabled to open the mysteries of life and salvation.
He was also richly endowed with the spirit of supplication,
in which he was drawn forth in great tenderness and fervency of spirit;
not only on behalf of Christ`'s church and people, but for mankind in general.

After more than forty years`' labor, his natural strength decayed;
and towards the close of his time,
having not long been returned from a journey of ten months through many parts of England,
he expressed himself thus, '`Now I rejoice in that I have served the Lord in my day;
and as I have labored to promote the truth in my generation,
I feel great peace from the Lord flowing in my soul,
and am thankful that I have been made willing to serve him.`'

He was taken ill about the Eleventh month, 1724, and continued weakly for several months;
in which time he uttered many weighty expressions,
and at several times was concerned in fervent prayer for the young and rising generation,
that they might be faithful witnesses for the truth in their day.
He expressed his concern that Friends should live agreeably to the doctrine of Christ;
and that the good order established among us might be kept up and maintained,
and that all differences and disorders might be kept out of the church.
Among many weighty expressions, he said, The Lord`'s goodness fills my heart,
which gives me an evidence and assurance of my everlasting peace in his kingdom,
with my ancient friends, who are gone before me,
with whom I had sweet comfort in the work of the gospel.`'
Notwithstanding our friend had been eminently attended with the power of truth,
and had great service several ways, he would speak very humbly of himself,
ascribing all the honor to the Lord; saying,
'`Although the Lord has made me serviceable in his hand,
what I trust in is the mercy of God in Jesus Christ;`' and added,
some friends sitting by him, '`The Lord visited me in my young years,
and I felt his power, which has been with me all along,
and I am assured he will never leave me, which is my comfort.`'

Near his conclusion, he often desired that he might be favored with an easy passage,
which was granted, and he was preserved sensible to the last:
passing away without sigh or groan, as if he was going to sleep,
the 20th of the Third month, 1725.
His remains were buried the 22nd of the same; aged about seventy-one years.
He was a minister about forty-five years.

[.asterism]
'''

ANDREW JAFFRAY, of Kingswell, in Scotland, was born in 1650;
being the son of Alexander Jaffray, of the same place.
He gave his son, Andrew Jaffray, a liberal education; who,
becoming convinced of truth about the time of his father`'s death,
quickly came to esteem learning but as dross and dung,
compared with the learning and knowing Jesus Christ,
in his inward and spiritual appearance in the heart,
and being thereby purified from dead works, to serve the living God;
of which learning he soon became a zealous, faithful, and able teacher.

He cheerfully underwent great sufferings on account of truth;
and was a constant fellow-prisoner in Aberdeen, with David and Robert Barclay,
Alexander Forbes, Patrick Livingstone, and other early Friends,
in the long sufferings they underwent for the truth.
He was cheerfully given up to any service to which he found himself called;
particularly going through the streets of Aberdeen,
and to many places of worship therein, exhorting the people to repentance;
and it was particularly remarked,
that in the same streets where he had been reproachfully pointed at for the truth,
and his testimony`'s sake; he, in his latter years, was looked upon with affection,
and blessed as he passed along.
He went through many deep, bitter, and severe exercises of spirit,
by being made the butt and mock of people,
because of his zeal against a man-made ministry; yet the Lord supported him through all,
and he was preserved to bear a clear and faithful testimony
for the truth in the meeting of Friends in Aberdeen,
the very day before his illness.

He was confined to his bed for months, under the infirmity of old age, weakness,
and distress of body.
In the course of his illness,
he bore a very clear testimony to the goodness of God to his soul,
and mentioned the satisfactory remembrance he had,
of his being separated for the work of the gospel;
and that he had dedicated himself for that service, ever since his being called thereto.

He departed this life the 1st of the Second month, O. S. 1726, aged seventy-six years,
and was buried in his own burying-ground at Kingswell the 4th of the same.

[.asterism]
'''

THOMAS THOMPSON, of Saffron Walden, in Essex,
was born in a small village in the East Riding of Yorkshire,
and received a dispensation of the gospel ministry
in or about the twenty-fourth year of his age;
which, as he received freely, he preached freely, traveling in England, Ireland,
and twice in America, visiting Friends and laboring for the promotion of truth.

In the year 1727, it pleased the Lord to visit him with a consumption, under which,
after a time, he was kept in patience and resignation to the divine will.
A few days before he died, being under great weakness of body,
he was concerned to supplicate the Lord on account of his church and people;
which prayer was delivered under a tender sense and frame of spirit,
and affected those present.

A few minutes after, he expressed himself in this manner,
'`To those who inquire what end I make, let them know,
I die in the faith that saves and triumphs over death and hell;
through the mercy and goodness of God, finding no cloud in my way;
but perfect peace with God through Jesus Christ, the presence of whose glory is with me;
and I feel the comforts of his spirit attending me every day.
I never felt the like comfort before.
I may say, as was said of old, "`Comfort you, comfort you my people, says your God:
speak comfortably to Jerusalem, say to her, her warfare is accomplished,
her iniquity is pardoned,
for she has received double at the hand of the Lord for all her sins.`"
Thus has God dealt with my spirit; by his judgments refined me,
and prepared me for a habitation with himself, in his heavenly kingdom;
so that I may say, as David did,
"`Although I walk through the valley of the shadow of death, I fear no evil,
because you are with me; your rod and your staff comfort me.
You prepare a table for me in the presence of my enemies; you anoint mine head with oil.
My cup runs over`" with praises to your glorious name,
you glorious Fountain of brightness, who took notice of me in my childhood,
in your love and mercy.
You compass me about with the bands of your salvation,
and you have made me yours forever: O, glory, glory, to your divine name and power,
you infinite Fountain of light and immortality.
My soul blesses you, and my spirit magnifies your name,
in the sense of that eternal word and wisdom that was in your bosom from eternity;
that intellectual light which shone everlastingly,
and will be a glory and crown to all them that believe and walk therein:
and in the faith of that I live and die.`'

At another time, being under the sense and power of truth, he said, '`Glory, glory,
to the excellent name of the Lord; the sweetness of his love can never be told;
the rays of his beauty shine upon me; I am filled with the power of his love;
glory be to his name forever!`'

A little before his departure he said, '`I have fought a good fight;
I have finished my course.
Henceforth is laid up for me a crown of glory,
which God the righteous judge shall give me at the last day; and not to me only,
but to all those who love his appearance.`'
And, just as he was dying, he said, '`Rejoice with me,
rejoice!`' and so departed this life in peace, the 30th of the Ninth month, November,
O+++.+++ S., and was buried the 3rd of the Tenth month, 1727.

[.asterism]
'''

GEORGE CHALKLEY, son of Thomas Chalkley, of Frankford, in Pennsylvania,
was a lad much inclined to read the Holy Scriptures, and other good books;
and was obliging and dutiful to his parents,
and ready and willing to do any service he could for his friends;
diligent in going to religious meetings, and an entire lover of religious people.
He was, in an uncommon degree, affectionately concerned for his mother,
doing whatever he could freely and cheerfully to serve her;
and told her not to do several things which he thought too much for her; saying, '`Mother,
let me do it, for, if I was a man, you shouldest not do anything at all,`'
meaning as to labor.
And she,
affected with his filial love and care for and towards her in her husband`'s absence,
would sometimes turn about and weep.

If this dear and tender youth, when reading, met with anything which affected him,
either in the Scriptures or other good writings, he would write it down,
and get it by heart.
One passage, which he had written down, and got by heart, much affected his father.
It was the 15th verse of the lvii.
chap.
of Isaiah: "`For thus says the High and Lofty One, that inhabits eternity,
whose name is Holy, I dwell in the high and holy place,
with him also who is of a contrite and humble spirit: to revive the spirit of the humble,
and to revive the heart of the contrite ones.`"

It was usual for his father to advise his mother,
not to set her affections too much upon him,
thinking he was too ripe for heaven to stay long on earth.
He was taken sick the 5th of the Eighth month, 1733;
and in his sickness behaved himself more like a wise
man than a child of ten years of age.
His father was in another part of the world, and he would gladly have seen him;
but he said that he should never see him more,
and desired his mother to give his dear love to him,
and to tell him that he was gone to his heavenly Father.
He was very fervent in prayer, in the time of his sickness;
and entreated that God would preserve his people all the world over.

One time, when in great pain, he prayed thus: '`Sweet Jesus, blessed Jesus,
give me patience to bear my misery and pain,
for my misery is greater than I can well bear.
O come, sweet Jesus, why are you so long in coming?
I had rather be with you, than in the finest places in the world.`'
One day he said, '`My misery and pain are very great; but what would it be,
if the wrath of God was in my soul.`'

His heart was full of love to his relations, acquaintance, and friends,
who came to see him in his illness;
and he took his last leave with a tenderness and sweetness which greatly affected many.

He departed this life the 13th of the Eighth month, 1733,
and his remains were carried to the Bank meetinghouse in Philadelphia,
and buried from there the First-day following,
being accompanied by many friends and others.
He was ten years and seven days of age when he died; and,
as he was greatly beloved for the sweetness of his disposition,
he was greatly lamented by many who were acquainted with him.

His father returning home, and meeting with this trial, said,
'`Although it was a great and sore exercise and deep
affliction to me to lose this promising youth,
my only son, yet it was made tolerably easy to me;
for he departed this life in much brightness and sweetness,
more like an old Christian than a youth of ten years of age.`'

[.asterism]
'''

JAMES DICKINSON, of Cumberland, was born in the year 1659.
His parents, Matthew and Jane Dickinson, being convinced of the principles of Friends,
educated him in the way of truth; and the Lord, by his power,
reached him when very young, and often his heart was broken into true tenderness,
so that many times he had a secret delight in being
inwardly retired to feel the virtue thereof,
which was the cause of true gladness to his parents,
whose delight was in the enjoyment of the Lord`'s presence.
They were good examples to their children, educating them in the way of righteousness,
often exhorting them, with tears, to fear the Lord.

The following account of the first moving of the divine principle, or spirit of Christ,
on his mind, is extracted from a short journal of his, long since out of print.
'`My father,`' says he, '`died when I was ten years old,
and I not taking the counsel of the wise man, namely, to take counsel of my father,
which was, to mind the light or measure of grace given unto me,
my mind was drawn out after the vain plays, customs, and will-worships of the world,
in which state I continued some time.
Yet the Lord, by his power, did many times reach my heart, and,
by the Spirit of his dear Son, the Lord Jesus Christ, reproved me for my vain conduct;
many times calling me to return to him, from whom I had gone astray; whose power,
in some measure, I had felt to tender my heart.
But I, not minding to turn at the reproofs of wisdom,
but going on in rebellion against his blessed spirit, ran,
as with a multitude to do evil, into wildness and vanity,
until the Lord in his mercy did visit my soul by his righteous judgments,
and thereby turned my mirth into mourning, and joy into heaviness,
and deep sorrow was my portion.

'`Being warned to repent and turn to the Lord, a godly sorrow was begun,
which I experienced to lead to true repentance.
Then my familiars became my enemies, and I was a taunt and a by-word to them; yet still,
as I loved the Lord in the way of his judgments,
and waited upon him to know the way of them, I found the Lord to give victory,
and saw my greatest enemies were those of my own house; and the war was begun there.
As I was careful to keep in the light, I came to see the kingdom rent from Saul,
and given to David,
though there was a long war between the house of Saul and the house of David,
yet as I kept my eye unto the Lord,
I came to see the house of Saul grow weaker and weaker,
and the house of David to grow stronger and stronger.
Yet many were the days of mourning and nights of sorrow my soul went under,
that I may say it was the day of Jacob`'s trouble, and of Joseph`'s affliction.
Many times I cried unto the Lord, O that I had a cave in the ground,
that I might mourn out my days, that in the end I might find peace with you.
In those deep afflictions and exercises, the Lord was very near,
and often mixed mercy with judgment,
so that my soul began to delight to wait upon him in the way of his judgment,
seeing it was by the spirit of judgment and burning that
the filth of the daughter of Zion must be done away.
As I kept here, I felt the love of God to increase in my soul, which deeply affected me,
and a hunger was increased in my heart, after the enjoyment of the Lord`'s power,
and the operation of it, whether it was in mercy or judgment.
So I knew my faith to be increased in the sufficiency of the power of God;
then I saw "`it was good for me that I was afflicted,
for before I was afflicted I went astray.`"
I found, as David said,
"`his rod and his staff comforted me;`" and the Lord
did often overcome me with his love.`'

When about eighteen years of age, he was first concerned to bear a public testimony.
'`Great,`' says he, '`then was my exercise.
Seeing the work to be very weighty, and looking at my own weakness,
made me unwilling to give up to answer the Lord`'s requirings.
But the Lord, in his great love filled my soul with the emanations of his power,
which strengthened and encouraged me,
that I was made willing to give up in obedience to his divine will.
In great dread and fear I stood up and bore a public testimony in our own meeting,
warning Friends to be more inward and faithful to the manifestations
of his light and grace in their souls;
and, after I had answered the requirings of the Lord,
I found great peace flowing in my soul; which so prevailed upon my spirit,
that I was bowed down under the sense of the Lord`'s goodness,
and the weight of the exercise which I had felt upon me was removed.`'

He visited Ireland twelve times, and was three times in America,
once in Holland and Germany, and labored much in his native country of England,
and many were convinced through his ministry.
He was very tender to the youth, a nursing father to the least,
and full of charity to all rightly anointed, yet not hasty to join with forward spirits.
He was also careful not to join in party,
but was greatly concerned for the promotion of truth.

About a year before his death he was struck with the palsy,
which deprived him of the use of one side,
and his speech was in a great measure taken from him;
yet he seemed to surmount the decays of expiring nature, and,
in a sweet and heavenly disposition of mind, intimated his day`'s work was done,
and that God whom he had served was still with him,
and that he had the evidence of peace and future felicity sealed upon his soul,
and was only waiting to be removed; but was fully resigned unto the Lord,
to wait his time.

To a friend who visited him, he expressed himself to the following purport:
'`I have served the Lord and his truth in my generation,
and now I feel the blessed reward thereof.
The accuser of the brethren is cast down as to me,
and my peace with God is sealed forever.`'

He departed this life on the 6th of the Third month, O. S., 1741,
and was buried the 8th of the same, aged about eighty-three,
and a minister sixty-five years.

[.asterism]
'''

BENJAMIN HOLME was born of parents professing with Friends about the year 1682, who,
as he grew up, took him along with them to meeting.
Nevertheless he exceeded many in wildness and vanity,
until it pleased the Lord so to touch his heart with his divine power and love,
as to bring him under a concern in his very tender age, for peace with God.
His exercise was great at that time,
and he walked often alone in fields and secret places, seeking the Lord,
that he might not miss peace to his soul.
As the love of God prevailed in him, his love to God and his people increased,
and he grew zealous for meetings, and was often bowed and tendered in them.
His mouth was opened in supplication to the Lord, and in testimony,
when about fourteen years of age; and, growing in the ministry,
he travelled abroad to visit Friends when about seventeen years of age,
accompanied by Joseph Kirkbride of Pennsylvania, and Leonard Fell.

He was a man devoted to the service of truth,
and labored almost incessantly in the work of the ministry, in this nation, Wales,
and Scotland; was several times in Ireland, twice in Holland, and some parts of Germany;
and in the year 1715, he took shipping for America,
and visited Friends on that continent, and most of the West India Islands.
In the course of his labors and travels, several were convinced by him; many,
through his innocent carriage, as well as by his ministry,
which was delivered in that plainness which becomes the simplicity and purity of truth,
have been reached and brought to judge and speak favorably of Friends,
and their Christian principles.
In the latter part of his time,
he was concerned to hold meetings in many places where no meetings of Friends had been.

His ministry was adorned with good conduct.
He sought the good of all with sincerity,
and was engaged to speak his mind with prudence and caution, both to old and young,
and had a persuasive faculty in his exhortations beyond many,
and was strictly careful not to divulge what he saw amiss in any, to others.
He envied not, nor detracted from any; but lived in universal love and goodwill to all.
It was his daily food to be found doing the will of God.

In his way to Haverford-west, to the yearly meeting for Wales,
being in a poor state of health, he was prevailed on to stay at Paul Bevan`'s, at Swansea,
and attended two meetings there on a First-day;
but being soon after taken with a fit of the ague, he was confined to bed,
and proper care was taken of him.
He appeared to be quite easy and resigned, and told Friends there in his illness,
that it was a fine thing to make a right use of time,
both with respect to this life and that which is to come;
and often desired that Friends in that place might be good examples to their neighbors;
that they might be brought from their forms of will-worship to the divine counsel,
and then all would be safe and well.
He reached Swansea the 8th of the Second month, 1749, and died the 14th of the same,
aged about sixty-seven years, and a minister about fifty-three years;
and as he lived so he died, a pattern of meekness and innocency.

[.embedded-content-document.epistle]
--

=== Benjamin Home`'s Last Legacy, or Serious Advice; recommended by him, a little before his decease, to the youth under the tuition of several schoolmasters.

[.salutation]
Dear Children,

I hereby tenderly salute you, with desires that as you advance in years,
you may in grace, that so like good Samuel,
you may grow in favor with the Lord and good men.
Virtuous and pious living will not only very much
recommend you to the better part of mankind,
but it is the way to obtain the blessing which makes rich, and adds no sorrow with it.
Live in love and peace; speak lovingly and meekly one to another; and if you behave well,
you will be a credit to your master and to your friends.
Make good use of your time; strive to excel in learning, and in the best things.
If you live in the fear of God, and take good ways,
and it should please the Lord to spare you, you may be serviceable in your generation.
John, the holy man of God, told the elect lady, whom he wrote to,
that he rejoiced greatly, that he found her children walking in the truth;
and to be sure it would be a great comfort to many of your parents and good friends,
to have you take good ways.
If any of you should be put out to trades, if you are honest, peaceable,
and careful to speak the truth,
and to make a good improvement of your time while you are at school,
so that the master can give a good account of you,
his good recommendation may be a means to help several of you to good places.

'`Dear children,
"`remember your Creator in the days of your youth,`" and
consider the obligations which you are under to serve him,
who is the author of your being,
and the fountain from whom all the good things which you receive come.
As the wise man says, that "`God hates a proud look, a lying tongue,
and him that sows discord among brethren,`" be sure that you hate to tell an untruth,
and have a care of being proud; because we read that "`Pride goes before destruction,
and a haughty spirit before a fall.`"
I would have you to guard against a quarrelsome spirit and temper,
and if at any time any ill-natured people should call any of you unbecoming names,
be sure that you do not give one harsh or unhandsome word for another,
nor render reviling for reviling; but remember that the wise man says,
that "`A soft answer turns away wrath;`" neither give flattering titles to any.
Remember Elihu said, that "`he accepted no man`'s person,
nor gave flattering titles to man, lest his Maker should soon take him away.`"
Now, although I advise you not to give these compliments,
which may tend to gratify a vain and proud mind;
yet I would have you learn to speak handsomely and becomingly to every body,
even to the poorest servant or apprentice about any of your parents`' houses,
or to the beggar who asks alms.

Seek and pray, like good Jabez, that the Lord may keep you from evil;
and we read that God granted him that which he requested.
The fear of the Lord is a great blessing to all them that live in it.
It is a fountain of life, which preserves from the snares of death;
and if you would not be drawn into any evil or hurtful things,
I would have you be very choice of your company,
which often has great influence upon youth.
Remember the wise man`'s counsel, "`My son,`" says he, "`if sinners entice you,
consent you not.`"
Many good-natured people have been ruined, to a great degree,
through hearkening to the enticements of sinners; but they are wise,
who learn by others`' harms to beware.
Love to read the Holy Scriptures, and other good books, avoiding such as are pernicious,
which may tend to corrupt, or make bad impressions on your tender minds.
I very much desire that you may be prevailed upon by the power of divine life,
to bear the yoke and cross of Christ in your youth;
that in the end you may witness that peace which
the world can neither give nor take away.
That you may make a right and good application of this friendly admonition,
and have the benefit hereby intended, is, with true love to you, the sincere wish of,

[.signed-section-closing]
Your Friend,

[.signed-section-signature]
Benjamin Holme

--

[.asterism]
'''

JOHN HAYWARD, of London, was born of reputable parents, not of our Society,
who gave him an education suitable to the station in which they intended to place him.
When of proper age, he was put under the care and tuition of an eminent surgeon.
During his apprenticeship, he was favored with a powerful visitation of divine love,
which eclipsed the prospects of temporal greatness; and things permanent,
objects of a higher nature, were presented to his view;
and to seek after durable riches and righteousness,
became the principal bent of his mind.
Being thus in an earnest pursuit of substantial good, an external show of religion,
in an observation of ceremonies, afforded him no solid peace;
nor could he reap any benefit under a ministry not attended with divine power and authority.
His understanding being opened, his inward conflicts and exercises increased,
and the language of his disconsolate soul was,
'`Can you tell me where the beloved of my soul feeds his flock,
or where the fold of true rest is to be found?`'

About the twentieth year of his age, he was made willing to take up the cross,
and sit down in silence among a despised people,
to worship the Father in spirit and truth.
He was effectually convinced,
and having attained to some degree of establishment in religion,
it became his duty to confess Christ before men,
and to express the religious sentiments he had embraced,
by the reformation of his whole conduct and demeanor.

Such a visible alteration caused him to become a wonder to his acquaintance;
but his conversation being very circumspect and truly religious,
accompanied with great modesty and affability,
their prejudices and misapprehensions were removed,
and upon all occasions they manifested an affectionate regard for him.

Having lived near the divine principle, or Spirit of truth,
and under the forming hand of the Lord, who prepares for service in his church,
he appeared in a public testimony about the thirtieth year of his age,
which was well received and truly acceptable.
He did not find it his concern to travel much abroad,
yet visited some of the western and southern counties, and some neighboring ones,
to his own satisfaction, and the comfort and edification of Friends.

He early declined the profession of surgery,
and with great caution entered into the concerns of trade,
keeping a watchful care that he should not dishonor his high and holy profession.
But a few years before his death he removed to Plaistow, in Essex, where he lived,
not to himself alone, but to his friends and the public,
seldom omitting proper opportunities of promoting
love and good works by precept and example.

He gradually declined, without much pain, and at times he was cheerful and easy,
discovering to those who were about him a mind occupied about a better world;
occasionally mentioning, yet with due fear of presuming, that though nature might shrink,
and be apprehensive for the dissolution of the frame,
yet he felt nothing beyond it to give him pain, but a steady hope of the reward of,
"`Well done.`"

A few days before his decease, a friend visiting him, he signified to him,
that all was easy, and that his day was nearly over.
He departed this life the 20th of the Second month, 1763,
and was buried at Bunhill Fields the 27th of the same, aged eighty years.
A minister about fifty years.

He left a considerable part of his substance to trustees, as a permanent fund,
the interest whereof to be given to poor Friends, at their discretion;
which proves a comfortable relief to a considerable number.
