== Chapter 5

[.chapter-synopsis]
* Thomas Ross
* Claude Gay
* Martha Williams
* Mary Gurney
* Robert Harvey
* Daniel Burns
* Thomas Finch
* William Rathbone
* Elizabeth Merryweather
* Mary Leaver
* Sarah Taylor

THOMAS ROSS, of Wrightstown, in Bucks county, Pennsylvania, having,
with the near sympathy and unity of his friends and brethren,
come over to England to pay a religious visit to Friends there,
arrived a few days before the yearly meeting in 1784, which he attended,
and afterwards visited Ireland that summer.
On his return, he joined his friend John Pemberton, of Philadelphia,
in visiting the quarterly meetings at Woodbridge and Norwich,
and proceeded forwards to Lincoln, York, and, by Durham, into Scotland.
They had many meetings among those of other societies,
which were generally large and satisfactory; but his bodily indispositions increasing,
he was under the necessity of resting at sundry places; and,
taking a few meetings by the way, he reached York the 2nd of the Eleventh month, 1785,
and attended their monthly meeting the day following,
which was the last meeting he was at.

During the course of his travels, his religious labors were truly acceptable to Friends,
and well received by others; for,
having an especial eye to the putting forth of the Divine hand,
his ministry was attended with living virtue and deep instruction;
and though not in the words which man`'s wisdom teaches, yet in godly simplicity,
and with a zeal becoming true religion.

In meetings for business, he was particularly serviceable;
his remarks being mostly short, pertinent, and very instructive;
exciting to a steady attention to divine counsel
in the transacting of our Christian discipline,
and therein to exercise true judgment, without partiality or respect of persons.

During the course of his illness he was preserved in a heavenly frame of mind.
On many occasions dropping instructive counsel and advice
to the friends who attended on and visited him;
of which the following collection is but a small part.
He frequently said that he knew not why he was continued
in such an exercised state of bodily weakness;
yet doubted not but that it was all in wisdom, and for some good end; adding,
it was not for the clay to say to the potter, '`Why have you made me thus?`'

Sitting in the family where he was, during the forepart of his illness,
he expressed himself thus: '`Dear young people, keep to your first love;
the bridegroom of souls will not be unmindful of the bride while she remains chaste;
some of you, I believe, are espoused to Christ.
O, the ardent desire which I feel for the youth! "`Your name is as ointment poured forth,
therefore do the virgins love you.`"`'

The same day, I have not sought my own honor,
but the honor of Him who first drew me from my habitation,
and have great reason to praise his name.
One thing which inclines me to think my work may be nearly done is this;
that it never appeared to be laid upon me to pay a general visit to England.`'
At another time he said,
'`O the harmony there is in the Lord`'s family! "`Ephraim shall not envy Judah,
nor Judah vex Ephraim; nothing shall hurt or destroy in all your holy mountain.`"`'

Again he remarked, on his being under bodily oppression,
'`I find no relief but when I feel a revival of that which is the healer of breaches;
but that is not at my command.
My mind was last night much drawn out to my fellow-laborers; O, that they +++[+++may]
keep little!
I have remembered that saying,
"`There are a few names even in Sardis who have not defiled
their garments,`" and I hope there are a few in York.
Dear friends, what a people should we be, did we dig deep enough.
Our lights would shine before men; we should be as the salt of the earth.
How many, who have begun well, have had their garments defiled with the world,
and are become like the salt that has lost its savor.
These are as dead weights in our assemblies,
so that the living are scarcely able to bury the dead.
O, Friends, keep to the truth, for it shall rise above the heads of gainsayers.`"

At another time, '`I could not be more at home any where.
It revives me to see the children about me.
I tell you; young people, the hardest thing I ever found in my passage was,
when I was right, to keep so.
Oh, the desire I felt to get here!
The love I feel for you is like the love of Jonathan and David.
It extends over sea and land; it is like the precious ointment;
so that some can say with one formerly, "`Neither heights nor depths,
principalities nor powers, things present, or to come, shall ever separate us from it.`"
The least sun casts a luster, as the glorious luminaries in the outward creation;
so that we may say, "`Great and marvelous are your works, Lord God Almighty;
just and true are your ways, you King of saints!`"

Again, '`Commune with your own heart, and be still;`" this is doing business.
Oh, how precious is truth!
It may employ us on the highway, and in our outward engagements.
Dear friends, let us prize it.`'
Speaking to the physician, he said, '`The outward man grows weaker;
yet inward support waxes stronger and stronger.`'
The same day he said, '`It is a great favor to have a brook by the way!
Oh! I see my way over all!
It is like a foretaste of what is to, come.
"`Blessed are the dead that die in the Lord!`"
When he breaks in upon us it is like balm.
"`There is balm in Gilead.`"
There are many not willing to go to the house of mourning; but there is occasion for it;
it being high time to repair the breaches.
I have thought for many weeks past, the curtain was nearly drawn.
There seemed but few sands left in the glass;
and yet I sometimes feel such a travail for Zion`'s prosperity,
and the enlargement of her borders,
that I am ready to think the day`'s work is not yet done; and at other times,
I feel so feeble and weak, that all seems nearly over.
The event I cannot tell, but am`' favored to be resigned.`'

At another time, '`Think nothing too near, or too dear, to part with, dear young people,
to purchase the truth.
Your parents cannot give it you, though they may give you all they can.
It is the Lord`'s prerogative.
I have thought it was a great favor to have an education in the truth;
but I have been grieved to see many born in the Society, like Esau,
selling their birthright.
Be not ashamed of the cross, dear friends, deny Him not before men.`'

Again he added, '`Beware of lawful things;
these lawful things are the strongest bait Satan ever laid for our society.
Oh, these lawful things, they have hurt many.
What a testimony would it be, if Friends were to shut up their shops on week days,
to go to meetings, which ought to be the main concern;
though many consider worldly things as such.
When we have done all we can, we are but as unprofitable servants;
we can add nothing to Him who is the fountain of goodness.
Oh, that ocean of ancient goodness!
I seem at times as if I was swallowed up in it.
I have cause to be thankful, that I am favored with a resigned mind, and have no will,
either to live or die.
Oh, Father, receive me into your bosom.`'
At another time, '`Oh, my heart is knit to you, my friends;
and to the seed which is in bondage in many hearts;
and though you may have to go with it into the wilderness, yet be not discouraged.`'

Feeling himself easier, and his mind favored, he said, '`Oh, when he puts his hand in,
as at the hole of the door, how does it smell of sweet myrrh.
I hope I am not insensible from where my help comes.
He sometimes hides himself as behind the curtain,
yet we must not awake or disturb our beloved until he please.`'

Speaking on the general state of mankind, he said thus: '`Oh,
how has my mind been oppressed,
in observing that profaneness which abounds among the people;
many of whom draw iniquity as with cords of vanity, and sin as with a cart-rope.
Yet I have this satisfaction,
that I have not failed to reprove many of those I have seen in this state;
and have often advised innkeepers and others,
to discourage all kinds of wickedness in their houses.
My advice has been generally received without gainsaying,
and I have comfort in the discharge of this duty.
Oh, the vileness of the land of Ireland!
Surely if any nation ever had occasion to mourn because of oaths, that has.`'

Being under much bodily affliction, he said,
'`How can one die better than in the Lord`'s service;
for he has been indeed a wonderful counsellor; he has many times opened a way,
when I could see no way; he will never leave nor forsake those who trust in him.`'
Again, '`It is a trying time, and yet,
I believe I have a well-grounded hope of having done my duty.
I feel no condemnation.
O, dear friends, what a favor indeed, that we have an unction from above!
Keep to the truth and its testimony, whatever may be the consequence,
for it will rise over the heads of gainsayers.`'

At another time,
'`It will not do for any to rest contented with having known the Lord in days past,
and years that are over and gone.
We must follow on to know him; a supply of daily bread is requisite;
and if there is not a hunger and thirst after righteousness,
we may be sure the mind is distempered.
But oh! how have I been pained to see and feel, many of the professors of the truth,
going after the world and its spirit; who, instead of being way-marks,
are as stumbling-blocks to honest inquirers: the state of these is lamentable.
I have been comforted in the prospect of a rising generation,
if they are not hurt by those who ought to be helpers, loving this present world.
I have, in my time, met with many cross winds and boisterous waves;
but have been preserved in a care to keep near the point,
that guides to the harbor of rest.
For these fifty years I have been endeavoring to fight the good fight of faith.
O, dearest Father! not my will, but yours, be done.
Oh, when will the curtain be drawn; that this mortal may put on immortality,
and eternal life, which will, I do believe, be my happy portion!`'

He would often, in thankful commemoration of the goodness of God to him,
break forth in these words, '`What shall I render unto you, O Lord,
for all your benefits.`'

A few days before his decease, on
a friend returning from meeting, he said he had been favored with such a sweet calm,
that he hoped he should have passed away.
A day or two before he died, he broke forth sweetly in these words;
'`Oh joy! joy! joy!`' Again, '`O death, where is your sting?
O grave, where is your victory?
The sting of death is sin!`"
I see no cloud in my way.
I die in peace with all men.`'

He departed this life the 13th of the Second month, 1786, at the house of Lindley Murray,
at Holgate, near York; and was interred in Friends`' burial-ground, in that city,
the 16th of the same, in the seventy-eighth year of his age.

[.asterism]
'''

CLAUDE GAY, of Barking, in Essex, was a native of France,
being born in the city of Lyons, about the year 1706,
and was educated in the church of Rome,
of which he continued a zealous member till about the thirty-sixth year of his age, when,
being at Morlaix on account of business, he came under a religious exercise of mind.
During this season, perceiving a New Testament in a room, he took it up,
and observing it was licensed by two popes, he concluded he might lawfully read it.
On opening the book, the first words he read were these; "`God, that made the world,
and all things therein, seeing he is Lord of heaven and earth,
dwells not in temples made with hands, neither is he worshipped with men`'s hands.`"
Acts xvii., verse 24, etc.

On the perusal of this passage,
he was convinced in his judgment of the errors of the Romish doctrine of transubstantiation;
and he saw clearly, that the adoration of the bread and wine,
as the body and blood of Christ, was idolatrous,
and contrary to the doctrine of the gospel; but,
at the instance of a person who persuaded him not to forsake the public worship at once,
he went to one of the smallest mass-houses in that town,
and placed himself at the greatest distance from the priest.
He did not keep kneeling steadily as was customary,
but first on one knee and then on the other, with great restlessness;
till the priest elevated the host, that the congregation beholding it,
might prostrate themselves as usual before it.

This query strongly impressed his mind, '`Will you also prostrate yourself?`'
Being affected therewith, he could continue there no longer; but, putting on his hat,
with fear and trembling he arose, and hastily left the place;
and confessed to his former adviser,
he felt great condemnation for conforming that day against his conscience;
and that being clearly convinced of the errors of the doctrine of that church,
he ought to forsake them.

He continued about one year longer in France; but desiring to dwell with Protestants,
he went to Jersey, and resided there; where meeting with Robert Barclay`'s Apology;
he was, on perusing it, convinced of the truth of the doctrine contained therein,
and embraced the principles of Friends.

About the year 1741, he was imprisoned by order of the magistrates there; and,
after nine months`' confinement, was banished to England; but returning,
he was again imprisoned, and banished under pain of corporal punishment if he returned.
He was afterwards relieved by order of the king and council,
and left at liberty to return to Jersey; but being thus liberated,
he settled at London about the year 1745.

In the exercise of his ministry he travelled much, chiefly on foot.
In 1763 he visited Holland, some parts of Germany, and Switzerland,
where his labors in the cause of piety seem to have been well received.

When not engaged in traveling his time was employed in attending meetings,
teaching the French language, and translating several religious treatises into French.
His diligence in attending meetings for worship and discipline was exemplary,
even when suffering under the weight of age and infirmities;
and he was also an example of humility, self-denial, and charity.
Being careful in his ministry not to go beyond his guide,
his appearances were seldom long, but lively, sound, edifying,
and pertinent to the states of the people.
He was fervent in prayer,
and evinced a deep knowledge and experience in the things of God.

He endured a lingering and painful disease with much patience and resignation;
his mind appeared abstracted from earthly things,
and centered in the enjoyment of divine peace,
declaring to those about him and with whom he conversed,
that all fear of death was removed.

He departed this life at Barking, the 19th of the Second month, 1786,
and was interred in Friends`' burial-ground there, aged nearly eighty;
and a minister about forty years.

[.asterism]
'''

MARTHA WILLIAMS, of Neath, in Glamorganshire, was the daughter of John and Abigail Binns,
of Carleton Biggin, near Skipton, in Yorkshire, and was born in the Fifth month, 1710.
She was educated in Friends`' principles, but in her youth was prone to vanity.
Nevertheless, by divine grace,
she was effectually enabled to turn her back on the
pleasures and allurements of this world,
and her mind became engaged to seek an inheritance incorruptible.

About the twenty-eighth year of her age she found it to be her duty to bear a
public testimony to the sufficiency of that power which had visited her;
and great were her sufferings and conflicts under a sense
of her unworthiness and inability for so great a work;
but being renewedly helped and instructed by the extendings of divine love,
she was strengthened to yield obedience to the requiring.

In 1746, she married Ambrose Williams, and settled at Pont-y-pool, in Monmouthshire.
They were true helpmeets, giving up each other freely to the service of truth,
trusting in the Lord, and,
making it their principal care to seek first the
kingdom of heaven and the righteousness thereof,
all things necessary in this life were added unto them.

Under this devotedness of mind she was frequently concerned
to visit Friends in most parts of England and Wales,
and was twice in Ireland.
She was a great encourager of the weak, a seeker after the scattered,
and a sympathizer with the afflicted;
and her cheerful temper gained her much place in the affections of young people,
who were the particular objects of her tender care,
and her advice often proved the means of drawing them nearer to the pure witness within.

The latter part of her life she lived with her son-in-law and daughter,
Evan and Elizabeth Reese, of Neath.
She was chiefly confined at home for about six months,
and in the last two months suffered great pain;
but was preserved in quietness and peace of mind,
and was at times strengthened to express her thankfulness,
that she was waiting the Lord`'s time to remove her to an everlasting rest.
She tenderly advised her children to do their day`'s work in the daytime;
putting up her prayers to the Father of mercies for their preservation,
with great fervency; and praising the name of the Lord,
who had been the stay of her youth, was the staff of her declining age;
and who graciously favored her with his presence to her latest moments.

She quietly departed this life at Neath, the 19th of the Second month, 1788,
and was interred in Friends`' burial ground, at Swansea, the 24th of the same;
aged seventy-eight, and a minister about fifty years.

[.asterism]
'''

MARY GURNEY, of Norwich, was the daughter of Edmund and Mary Gurney, of that city;
Friends well esteemed,
and religiously concerned to educate their children in the way of truth;
and their care herein was the means of her being, in a good degree,
preserved from the vanities of the world, in the time of her youth.

About the thirty-third year of her age she was favored
with a close humbling visitation of divine love,
under which she was concerned to bear testimony thereto, by way of public ministry,
in which Friends had unity with her; and though she did not travel much abroad,
she visited some of the meetings in her own, and some adjacent counties.
In the year 1788, she visited the meetings of Friends in Bristol, Worcestershire,
and in several other places, in which her public ministry,
and religious services in Friends`' families where her lot was cast,
were to the comfort and satisfaction of many.

In the close of her visit she stayed a short time in London,
and attended some meetings there; and having visited the week-day meeting at Plaistow,
and had acceptable service therein, she was soon after taken ill,
and was conveyed to the house of Joseph Cockfield, at Upton, where,
her indisposition rapidly increasing,
she said that she hoped she should be favored with patience to bear all.
The following day, her disorder continuing to gain ground, and a person present saying,
she might still live to do further good, she replied to this effect,
that she endeavored to make such matters easy to her mind, by thinking,
"`Shall not the Judge of all the earth do right?`"
and that she believed, if it pleased him to remove her, it would be in mercy,
and that she might never go better.

Her quiet composure of spirit and resignation to the divine will during her illness,
which, although short, was attended with much bodily pain,
were truly edifying to those about her.
She said to her companion, '`Oh! what greater happiness,
than to enter into the fulness of joy;`' and that she felt no guilt.
Other comfortable and instructive expressions dropped from her at different times.
About an hour before her dissolution she appeared to be engaged in supplication;
but her voice failing, she could not be clearly understood.
Her last words, which were distinctly heard, a short time before she expired, were,
'`Ready, ready, ready!
Jesus Christ, my Lord!`'

She departed this life on the 2nd of the Eleventh month, 1788, aged sixty-one;
a minister about twenty-seven years; and was buried on the 9th of the same month,
in Friends`' burial-ground, near Bunhill fields,
after a meeting in Gracechurch-street meetinghouse.

[.asterism]
'''

ROBERT HARVEY, of Old Meldrum, in Scotland,
having been a faithful laborer for the promotion of piety and virtue, in his time,
that his example should not be lost,
the following short account of him seems to claim a place in this collection.
He was a man of exemplary conduct, a diligent attender of meetings,
and an upright laborer in them, his ministry being sound and edifying.
He visited most of the meetings in England and Wales, between the years 1754 and 1757,
and soon after Ireland, returning by the north of England, to general satisfaction,
and his own peace: and,
although we have no further account of his travels in truth`'s service,
yet it is evident he retained his integrity to his conclusion;
as he signified a little before his departure, that all his accounts were clear,
and that he found nothing but peace of mind.

He departed this life on the 21st of the Twelfth month, 1788,
and was buried in Friends`' burial-ground at Acquorthies the 23rd of the same,
aged seventy-seven years, and a minister fifty years.

[.asterism]
'''

DANIEL BURNS, of Lewes, in Sussex,
was convinced of truth about the twentieth year of his age, while a soldier in the army;
and being faithful to what was made manifest to be right,
he bore his testimony against bearing arms.
By the interposition of some friends of Hampshire, he was discharged in 1752,
at Chichester, where he remained a short time,
and then removed into the compass of Lewes monthly meeting.
Abiding under the influence of the spirit of truth, he experienced a growth therein, and,
after a while, had a few words to declare in meetings, by way of testimony.

He was exemplary in conduct and conversation,
and labored according to his ability in the service of truth; and many times,
in much brokenness of spirit,
would endeavor to strengthen and encourage the weak and sincere in heart,
to come up in faithfulness to the manifestations of life and grace within.
He was a pattern of meekness and tender affection for all in distress,
whether friends or others, and used his endeavors for their relief;
which many times were blessed with good success.

In his last illness, which was but short, he appeared perfectly resigned,
and expressed himself somewhat after this manner;
that he believed his day`'s work was done, all was well, and he felt peace.

He departed this life the 9th of the Third month, 1789,
and was buried in Friends`' burial-ground at Lewes, the 15th of the same,
aged fifty-eight years.

[.asterism]
'''

THOMAS FINCH, of Brentford, in Middlesex, was born at Winkfield, in the county of Berks,
of pious parents, under whom he had a guarded education; and,
about the eighteenth year of his age, was favored with a heavenly visitation, to which,
if he had given way, he has since told an intimate acquaintance,
he thought he should then have been called to the work of the ministry.
But neglecting to live under the influence of this divine principle,
and turning his attention to the reading of deistical authors,
his understanding became so darkened, that his mind seemed closed up,
in an unbelief of the truth of inward revelation;
and he thought there was nothing greater than reason to be known in man; but,
as he has said, he continued with friends, among whom he was educated,
because he believed them the best moralists.

Although he continued many years disputing against the truth,
yet it pleased the Most High, about the latter end of the year 1756,
to favor him again with a fresh visitation of divine love.
He now no longer consulted with flesh and blood,
but gave up to its heavenly instructions; and being humbled under the mighty hand of God,
he, in due time, received a part in the ministry of the gospel of Jesus Christ;
in whose spiritual as well as outward appearance, he now firmly believed.
Having tasted of the Lord`'s judgments and mercies,
he labored to persuade men to let their conduct be as becomes the gospel.
He was diligent in attending meetings for worship and discipline, till near his decease;
zealous for the promotion of righteousness, and of a benevolent disposition,
which endeared him to friends and others of his acquaintance.

During his illness, which was long and painful,
he was favored with that resignation and peace which
bespoke a mind elevated above earthly things.
To some friends, not many days before his decease, he expressed himself thus:
that although, during his indisposition, he had felt great poverty of spirit,
and at times as though deserted, yet he trusted in the Lord`'s mercies;
believing that he should be favored, before the closing scene, to feel the Lord nigh,
as in days past.
This there was good cause to believe he experienced; for,
the First-day evening before his decease,
he broke forth in a living testimony to the mercy and lovingkindness of the Almighty;
encouraging all who had known something of his goodness, to trust in him; saying,
'`There is no shortness in him.
If there is any shortness, it is in us, not in him.
I bear this my last testimony to his goodness.`'

At another time, being asked how he did, he said,
'`I have been praying for help to carry me through with that
patience which I love to see in myself and others.`'
To one who attended meetings, he observed, '`How comfortable a thing it is,
to have nothing to do but to die;`' that nothing stood in his way;
and that the way to die the death of the righteous,
was to live the life of the righteous.

He departed this life at Brentford, the 5th of the Fourth month, 1789;
and his corpse was interred in Friends`' burial ground near that town,
the 12th of the same: aged seventy-seven years, and a minister about thirty years.

The following remarks were dictated by him to a friend,
whom he desired to write them down, in the course of his illness.
'`As surely as things are in their places, the best things will be uppermost.
Now, as we read,
"`The king`'s daughter is all glorious within,`" so there is something
truly beautiful in the regulation made by true religion,
where the objects of our affections are rightly regulated.
It is of great consequence what we love best,
because our lives and conduct are generally according to the order or disorder within.

'`Notwithstanding the increase of knowledge among men,
it seems but little of the best sort.
There seem to be many who understand Latin, Greek, and Hebrew,
who know but little of themselves.
It must be allowed to be a material point whether a man has liberty or not;
and if he has, wherein it consists, and which is the way to make the right use of it.
This, well considered,
may help us to discern the great importance of spiritual-mindedness.
The carnally-minded world seems to know little of these divine things.
Men, in common, seem but little aware how necessary a good state of mind is,
in order to live a good life.
Accordingly we see few men in much care about the state of their minds.`'

[.asterism]
'''

WILLIAM RATHBONE, of Liverpool, was born there in 1726,
of parents who were members of the national church.
His mother died before he was two years old,
and his father being soon after convinced of Friends`' principles,
he was carefully educated therein; and,
being in a good degree obedient to the visitations of divine grace,
he became while young an example of sobriety and industry.

About the seventeenth year of his age, being under discouraging circumstances,
he formed the intention of going abroad, with a view to acquire wealth;
but when he thought himself on the point of carrying this design into execution,
his mind was brought under a weighty exercise,
and he was impressed with a persuasion that his appointed
station was in his native place,
where a field of religious labor was opened before him; and,
that if he persevered in his intention, his religious interests would be subverted,
and the divine will concerning him be opposed.
In this state of conflict he was convinced that,
if his sole dependence was fixed on the Almighty arm, it would supply all his needs,
and be an unfailing support in the various trials that might be allotted to him.

Through the continued extension of divine regard,
he was enabled to yield obedience to these convictions;
to enter into covenant with a covenant-keeping God;
to limit his desires after perishing riches,
and to bear the turning of his hand upon him.
As he was favored to enter on the active scenes of
life with faith and dedication of heart,
so he was supported, in his passage through it,
to bear his portion of disappointment and affliction with Christian fortitude.

The gracious Being, who had directed his feet into the right way,
was mercifully pleased to be with him, from step to step:
so that he increased in stability and usefulness;
and about the forty-ninth year of his age,
he was concerned to bear a public testimony to the sufficiency of this divine grace,
which had been the stay of his youth.

For some time before his decease,
he was more than commonly enlarged in his public testimony;
and accompanied two women Friends in visiting the families
of Friends in his own and a neighboring meeting.
The minds of some of his friends were singularly impressed with
the exercise he was under the First-day preceding his illness,
when he had to express, in the morning meeting,
the necessity of having oil in our vessels, and our lamps trimmed;
calling upon some present to remember in what awakening
manner this exhortation had been sounded in their hearing;
saying, it was given him afresh to believe that there were those present who,
when the solemn summons should be issued,
"`Behold the Bridegroom comes; go forth to meet him;`"
however diligent they might have been in having their vessels replenished,
would find they had nothing to spare.

The following day he was a little unwell, but cheerful; on Third-day,
complained of a violent cold that affected his head;
and in the afternoon was obliged to go to bed.
He was confined to his chamber about a week,
during which his patience and fortitude were exemplary; and although,
through the extremity of his bodily illness, he was at times delirious,
yet at intervals his understanding returned; in one of which he expressed audibly,
'`Who would not love and praise your name,
you King of saints;`' and continued with solemn prostration of soul,
for a considerable time, and then said, very intelligibly, '`O, poor creatures;
called upon to offer an offering in righteousness; who can but, who dare but,
obey the call.`'
It was a season of awful quietness;
his spirit was again powerfully engaged in fervent prayer, for full two hours,
except once or twice, when raised up to take something,
he let fall a wandering expression, but when he was laid quietly down,
he was again favored with the renewed influence of the spirit of supplication.

Through the weight of his illness, his voice was much interrupted,
but sundry expressions were at times distinctly heard, '`Most Holy Father;`' '`Lord, God,
Almighty;`' '`I have known the rod, and bless the hand.`'
What followed could not be distinctly heard,
but it is not easy to set forth the awful solemnity of the season.

In the evening, his wife and children being in the room,
and one of his daughters beside him, he took both her hands in his,
looked at her with a most sensible expression of affection, then closed his eyes, and,
without a sigh or struggle, breathed his last.

He departed this life the 11th of the Eighth month, 1789,
and was interred in Friends`' burial-ground the 14th of the same,
in the sixty-fourth year of his age; and a minister about fourteen years.

[.asterism]
'''

ELIZABETH MERRYWEATHER was the daughter of Samuel and Deborah Waring,
mentioned before in this collection, and widow of Joseph Merryweather,
all of the county of Hants.
She had the advantage of a religious education, and was,
through the influence of divine grace, enabled to escape many of the corruptions,
follies, and vanities, incident to youth; and, in a good degree,
to preserve an irreproachable character, from childhood to mature age.
As she advanced in years, she gradually grew in grace,
and in that saving knowledge which prepares and qualifies for service.

About the fortieth year of her age she came forth in a lively and edifying testimony;
was very cautious not to enlarge beyond the limits of her gift in the ministry,
and the present concern;
and was desirous and careful that her conduct and conversation
might be such as becomes a gospel minister.

She visited the meetings of Friends in Oxfordshire, Dorsetshire, and London;
likewise the families of Friends in her own county, to general satisfaction,
and her own peace, and retained her love and zeal for the cause of truth,
unabated to the end.
She was, for many years, frequently afflicted with long and painful attacks of illness;
which, with some other very trying dispensations,
she was enabled to bear with exemplary patience and resignation.

A short time before her decease she gave her daughter
a strict charge that her funeral might be very plain,
and free from all unnecessary expense;
and also desired her relations and friends might be informed of her death,
that if any of them should incline to attend her burial,
they might have the opportunity of doing it, but that no invitation should be given;
intimating that she had done nothing to deserve any extraordinary marks of regard.

About ten days before her close,
she apprehended it was required of her to visit a Friend`'s family; which,
with some difficulty, through great weakness,
she was enabled to perform to good satisfaction; and on her return home,
signified that she was favored with an evidence that this was the
last public service that would be required of her.

The same evening, on going to bed, she was seized with something like a fit; which,
being followed with her old complaint, the gout in her stomach,
she was confined to her bed for the last time;
and said to her daughter that she had often thought the time of her release was nigh,
but never saw it so clearly before; and now she had an evidence that the time was come,
and charged her not to mourn for her, but rather to rejoice: adding,
'`I have nothing to do; all is quietness and peace.`'
At another time, '`I am sweetly and peacefully passing away.
The Lord is my support.
The great Physician is near.`'
And soon after said, '`I have had a twelve month conflict, and now, I believe,
my heavenly Father has pronounced it finished.`'

Some friends sitting one day in the chamber, she was engaged to speak nearly as follows:
'`I have been thinking many times what John said of
those who had "`come through great tribulations,
and had washed their garments, and made them white in the blood of the Lamb.`"
I have been brought through many, and have desired that my garments might be washed,
that all might tend to my sanctification; and, under all, the Lord knew my integrity,
and has given me a sure evidence of a resting-place with him, where sorrow cannot reach.
And this is all I want my friends to know.
I want no other testimonies to be borne of me.`'

She then was led to praise and magnify that good hand, which, she said,
had been with her all her life long, and would not forsake her in her last hour.
To a friend in the ministry she spoke very encouragingly,
exhorting her to be faithful to the least discovery of duty, saying,
'`The widow`'s mite has often been a comfort to me; though but a mite,
it was not overlooked by the great Master: '`adding,
'`I have ever found that obedience to the smallest requirings brings peace,
but disobedience will bring poverty.`'

While she retained her speech and faculties she had a suitable
word of exhortation or advice to most who visited her;
and took an affectionate leave of her relations and friends.

Thus, favored to close a life of much pain and sorrow in great peace,
she expired without a struggle or a sigh, at Alton, the 7th of the Twelfth month, 1789,
and her remains were interred in Friends`' burial-ground there the 13th of the same;
aged nearly sixty, and a minister about twenty years.

[.asterism]
'''

MARY LEAVER, wife of John Leaver, of Nottingham, was born in the year 1720,
of parents professing with Friends.
She was endowed with a good natural understanding,
and had the advantage of a religious education.
Through faithfulness to the humbling visitations of divine grace,
she was raised up to bear testimony to the efficacy
and sufficiency thereof about the year 1753.

She loved retirement,
yet found it her concern to visit Friends in most counties in England; and,
in the year 1773, many provinces in North America, where her service was very acceptable.
Some time after her return, she met with a trying dispensation,
her three daughters being removed from her by death in the space of a few years;
all of them grown up to women`'s estate, and hopeful;
which affliction she appeared to bear with becoming resignation to the Divine will.

Her last illness was very short, and part thereof attended with considerable pain,
which she bore with truly Christian patience, saying to one of her near relations,
the evening before her departure, '`I am content:`' to which he replied, '`That is a favor:`'
she said, '`A great one;`' and added, It has put me upon thinking every way;
but I feel no condemnation; I am easy.`'

She was mostly favored with her understanding till near her conclusion;
and quietly departed this life the 15th of the Twelfth month, 1789;
and was interred in Friends`' burial-ground, at Nottingham, the 18th of the same,
aged about sixty-nine years; and a minister about thirty-six years.

[.asterism]
'''

SARAH TAYLOR, of Manchester, was the daughter of John and Margaret Routh,
of Wensley-dale, in Yorkshire.
She was religiously educated,
and through the merciful visitations of the day-spring from on high,
divine impressions were made on her tender mind;
through faithfulness to the manifestations whereof, in patient resignation,
she was fitted for further service,
and appeared in the ministry about the nineteenth year of her age, and visited London,
in company with Mary Slater.
About the twentieth year of her age she removed to Manchester,
and resided with her brother John Routh.
In the year 1748 she was married to William Taylor.
He survived but a few months,
but she often expressed that they were united in a bond of heavenly fellowship.
After his decease she continued unmarried.

In testimony she was lively, clear, and pertinent,
reverently careful to wait for the opening and authority of the word of life,
and skillful in dividing it to the people; and in her addresses to the Almighty,
her mind was sensibly clothed with that which gives access to the throne of grace.
Under the engagement of divine love, with the full concurrence of her brethren,
she visited at several times the meetings of Friends in most parts of this kingdom,
Wales, and Ireland.
She was diligent in visiting the widows, fatherless, and afflicted,
and exemplary in attending meetings for worship and discipline.

When the infirmities of old age attended, and she was, by a dropsy,
confined to her house, and mostly to her bed,
she expressed herself to a friend nearly as follows:
'`I was never more sensible than in this time of my
confinement and separation from my friends,
of the various ways in which the Lord`'s work is marred, and his merciful designs,
with respect to individuals, frustrated,
through the reluctance of the creature to become
as passive clay in the hands of the potter,
vessels of the Lord`'s own forming, without any mixture.
Some hesitate; some are too forward; but all this is from unreduced self,
and all tends to mar the Lord`'s work.
We are to be formed into pure vessels, quite emptied,
that the divine word may have free course; no hesitation,
no activity or contrivance of the creature, to choose or to refuse.`'
After a little pause she added, '`But he knows human weakness,
who is a God of infinite compassion, and he stands ready to help us,
if we look to him in sincerity.
A sigh, a tear, arising from true contrition, is a sacrifice well pleasing in his sight;
because it is of his own preparing,
and will arise as incense from the temple of our hearts, if we are dedicated to him.`'

The same friend going to her early in the morning,
she mentioned a person who desired to be remembered to her, and by her.
Sarah said, '`I have been thinking much of him in the night, and would have you say,
when you see him, that in looking at me,
and the probability of my being nearer the solemn close than some others;
and having been in a good degree preserved through many exercises,
he may think there is a cause to rejoice.
But I never passed through more proving conflicts than at present,
nor ever had greater need of watchfulness,
lest the enemy should get any advantage over me;
or had at any time more distressing fears of losing ground,
and the great work of redemption falling short, and receiving damage,
by my poor mind being turned aside to objects of inferior importance,
and so the victory not be obtained.
Day and night, to be solicitous for preservation, was never more needful.`'

'`Oh, that great work of redemption! "`I pray not,`" said our blessed Redeemer,
"`that you shouldest take them out of the world,
but that you shouldest preserve them from the evils.`"
We are called to victory.
All depends upon keeping close to him who can alone preserve us in the hour of temptation.
I will keep you in the hour of temptation; then is the trying time,
when the grand enemy endeavors to gain his end;
it is his work to draw the mind into captivity; he wants to keep us in bondage.`'

Some months before her removal, she said, '`I am not apprehensive my close is very near,
though I feel nothing to stand in my way.
I am quite resigned, and desire to be preserved in the patience; for though so feeble,
and nearly worn out, a natural quickness about me, often under my sufferings,
prompts to disquietude; but when thus tried, I invite patience;
and also pray to the Giver of every good and perfect gift for it,
and am favored to feel its return.`'

She also mentioned, that as her bodily strength became more impaired,
her understanding was more opened to prospects which
no language was copious enough to express;
in which she experienced a freedom from all the fetters of earthly connections,
or objects of sense.
It was as the place of broad rivers where were no storms or tempests;
neither galley with oars, nor gallant ship could pass; no work nor invention of man;
but as in the ocean of divine love, her mind was filled with silent worship,
and adoration of the Supreme Being.
She added, few of her early acquaintance were now remaining in this life; yet, she said,
there were situated in several parts of the nation,
those whom her mind often visited in near love,
and she felt them near in the covenant of truth.

She expressed, with much tenderness,
her desires that those who were entering upon a situation, surrounded with dangers,
might seek after the pearl of great price; and be willing to sell all,
to purchase the field where the treasure was hid;
for it would remain when all other supports failed.

On two friends visiting her, she said that she knew not how it might be with her,
in respect either to life or death; nor did she desire to know;
but it was abundantly made up by a prospect that was frequently laid open,
and enlarged into a scene of ineffable glory and brightness,
that at times it seemed too vast for her to bear; but as it was mercifully continued,
her capacity for receiving it increased.
She had been favored to behold a state so glorified,
in perpetual union with glorified spirits,
that at seasons she seemed enclosed in a scene of universal brightness, glory,
and beauty, too great for human comprehension.
But she soon added, with awfulness, '`Yet this has not always been the case;
there was a time when the heavens were as brass, and the earth as iron,
and my soul encompassed as in clouds of impenetrable darkness; but since,
that is mercifully removed, and the before-mentioned prospect has graciously succeeded.`'

She had been made to view the past errors of her life,
and also to feel that judgment must pass over the transgressing nature,
and even upon every wrong impulse of the mind,
though it might not break forth into action; by giving way to which,
she had often prepared herself a cup of sorrow unknown to others.
She said, what she felt for her friends in religious profession, was not to be expressed;
nor the strength of her desire,
that those who had yielded themselves into the purifying hand of judgment,
might be preserved under it steadfast and immovable.

Nor could she set forth in words her ardent solicitude, that those who had been,
and were wandering from the fold of rest,
might be given to see their dangerous situation; adding, '`O,
what I feel for those wanderers!
Could I but gather them, could I open one of these prospects to their view,
how would it stain all their worldly pursuits.
Surely it would make them covet an establishment on this immutable foundation.
I have often thought of those expressions, "`If the righteous scarcely be saved,
where shall the ungodly and the sinner appear?`"
What my mind has felt for some of you of late,
has indeed exceeded anything that I ever experienced before.`'

Another time she said, '`I have had deep sufferings and baptisms to pass through,
but I now see, with indubitable clearness,
that there is a rock and fortress at the bottom; which, if we cleave to,
no power of darkness, however great, shall be able to move us from it long together.`'
To a friend who sat with her, she said, '`The body is weak,
but my mind is preserved in quietness, and seasons of consolation come unsought for;
when clear prospects are opened to my view,
of "`the spirits of the just made perfect,`" and of the church triumphant,
which words are insufficient to describe.
It appears like a boundless expanse, an ocean of love, a river clear as crystal,
which the vulture`'s eye cannot see; no galley with oars, nor gallant ship,
can pass thereby.
There the spirits of the just, the church triumphant, enjoy full fruition;
are gathered into the place of pure prayer, adoration, and worship.
Precious in the eyes of the Lord is the death of his saints;
because in these crusts and shackles of the body, they cannot enjoy perfect,
uninterrupted blessedness;
and he wills and loves that those whom he has redeemed by his power, should enjoy,
perfect, unmixed happiness.`'

She added, '`I have learned with the apostle,
that it is not by works of righteousness that I have done,
but of his mercy that he has saved me, by the washing of regeneration,
and the renewing of the Holy Ghost.
O, I would not change my situation for all the possessions of this world;
nor for all the knowledge and speculation that the
wise system builders of the present age can acquire;
and, whatever they may vainly suppose, it is not a delusion,
nor the workings of imagination, nor of prejudice; but solid, enduring,
substantial truth.`'

After a solemn pause, before some friends took leave of her, she signified,
with a sweet calmness, the probability of its being a final farewell; then added,
But there is one thing of more importance, that I feel my mind pressed to fix upon yours;
which is, that you may be gathered into entire resignation,
to abide with your great Master on Mount Calvary.
Remember what he declared, that "`Where I am,
there shall my servant be;`" and this you know was under suffering.
What I have wished for you is, that you may travail for a willingness to be kept here;
for what can we desire more or greater, than to be where our great Lord and Master is.
He knows your state and your weaknesses, and his eye is over you for good.
But if, like Peter, you slide from his testimony, he may bring it to your remembrance;
and though your trials may be many and severe,
and you may be beset and buffeted on every hand; yet he is omnipotent,
all-powerful to preserve and keep you.
It is the Father`'s good pleasure to give his adopted children the kingdom:
for his regard is to his little flock,
and all the combined powers of darkness shall not be able
to pluck any of his lambs out of his hands.`'

On the 19th of the Sixth month, to a friend, she spoke to the following import;
"`On looking over my past life, I cannot charge myself with being presumptuous;
but I know I have not at all times been as honest as I should have been;
especially in our large public meetings for worship.
When things have arisen with clearness, that I should have communicated to the people,
I have let the right time slip, by deliberating on my own unfitness.
This is indeed consulting with flesh and blood; listening to an enemy.
I have not only hereby increased my own portion of sorrow and conflict;
but the blessed cause has suffered.
The free circulation of life has been obstructed,
when I have had reason to believe it would have flowed as from vessel to vessel.`'

After sitting a while under the covering of a sweet and solemn quietness, she said, '`O,
what an awful thing is pure gospel ministry!
How few understand, or are sufficiently baptized into the true nature and spirit of pure,
living, powerful, gospel ministry!`' The following day, to the same friend,
when taking leave of her, she said, '`You see, dear child,
how I am carried on from day to day; neither seeing, nor desiring to see,
how the present dispensation is to terminate;
but faith and patience are mercifully vouchsafed to sustain;
though sometimes it seems as if they were ready to fail; and then, I am deeply tried.
It is a great thing to be able to say, "`I have fought the good fight;
I have kept the faith.`"
O, this keeping the faith, this cleaving close to him, who has indeed loved us freely!
If some of you will keep the faith, you will be strengthened more and more,
to make war in righteousness against the enemies of your own houses;
and be able to lift up a standard against wrong things in others.`'
She afterwards added, '`I often visit you in that love which is wider than the ocean,
and extends over sea and land, and do you remember to keep the faith,
in him who is invisible and invincible too.`'

On Second-day preceding her departure,
she was much afflicted with pain and shortness of breath;
when a relation expressing her reluctance to leave her, to attend the monthly meeting,
she said, '`I would have you go; for though I have a trying putting on,
I do not quite see the end; but it may not be long before it comes.
You may tell Friends, I do not expect to see any of them again;
and give my dear love to all, for it spreads universally.`'

On Sixth-day morning the symptoms of approaching dissolution were more apparent;
and her outward sight much gone, so that she did not seem to know those about her,
but by their voices; yet her religious exercise did not cease.
She frequently expressed much care and concern for a young woman in the family,
earnestly entreating her to do all she could to inherit eternal life;
with many other expressions of strong solicitude for her preservation.

About eight o`'clock in the evening she took a little wine and water,
but found it difficult to swallow; and when she had taken a small portion, said,
with a strong and clear voice,
'`No more;`' and soon after dropped the following expressions: '`Be still, be still,
and you shall soon see the salvation of your God;`' which were the last words uttered.
They were accompanied with such an evidence that they were spoken concerning herself,
and that it was her own blessed experience,
as greatly bowed the spirits of those present, in resignation to the divine will.
About ten she quietly breathed her last, the 19th of the Eighth month, 1791;
and was buried in Friends`' burial-ground, the 21st of the same, aged seventy-four years,
and a minister fifty-four years.
