== Chapter 1

[.chapter-synopsis]
* Mary Evens
* Sarah Evens
* Robert Evens
* Francis Evens
* Anna Maria Bowman
* Elizabeth Evens
* Benjamin Evens
* Jonathan Raine
* Sarah Clare
* Potto Brown

MARY EVENS, a young woman of seventeen, daughter of Benjamin and Elizabeth Evens,
of Woodbridge in Suffolk, and eldest sister of Kezia Merryweather,
mentioned in the Ninth part of Piety Promoted, was taken from the probations of time,
on the 1st of the Eighth month, 1770:
the following account of her close is but little altered
from one penned by her pious and affectionate mother.

She may be truly said,
to have been an example of patience and resignation
through the whole course of her affliction;
and though (continues her mother) I was almost constantly with her,
yet I never heard her in the least murmur or repine,
though her pain was often very violent; but, she frequently said,
that she was afraid she should not have patience enough.

On the last day which she lived, she lay pretty easy till towards noon,
when she was seized with violent pain in her side.`'
Dear mother, '`said she '`lift me up, I cannot breathe.`'
The pain continued exceedingly sharp for three hours,
during which time she was often concerned to beg for patience;
and desired her father and me to pray for her, that she might have patience granted.
'`Dear mother,`'she said, '`you can not think what pain this is.
This is pain indeed.`'

In her greatest anguish, she broke forth in supplication to the Lord for a little ease,
saying, '`I have received many comforts from your hand, O Lord;
more than I could expect or desire;
and if you are pleased to take me to yourself this afternoon,
it will be the greatest comfort I ever received in my life.`'
After this, observing her to lie still,
I asked if she should like to speak to her brothers and
sisters +++[+++most of whom were younger than herself]. She said,
'`Yes,`' distinctly took leave of them all, and said at parting, '`All, mind and be good.`'
Seeing one of her sisters much concerned, she added,
'`Don`'t fret for such a poor thing as I am.`'

After this, it pleased the Lord to grant her request, and to give her ease.
She gratefully acknowledged it, and had such sharp pain no more;
but lay in a sweet frame of mind, but drawing her breath shorter and shorter,
till the solemn moment arrived.
A few moments before her close, she gave me one hand, and an intimate friend the other;
thus quietly departing about six in the afternoon, as she had besought the Lord, and,
I doubt not, is entered into the heavenly rest of the righteous.

[.asterism]
'''

SARAH EVENS.--An account has just been given of Mary,
daughter of Benjamin and Elizabeth Evens, of Woodbridge.
I come now to relate another deprivation which, in less than half a year after her death,
these pious parents had to undergo in the loss of their daughter Sarah Evens,
who died at the age of nineteen, early in the year 1771.
In this relation, the memorandums of her mother will be my principal guide;
and I shall generally form my little narration in her own words.

But here,
seeing I have still the pious close of another sister and of two brothers to relate,
by which means Piety Promoted will probably contain accounts
of two sons and of four daughters of the same family,
it may not be improper, once for all,
to mention that the parents were persons not only of exemplary conduct themselves,
but very vigilant over that of their children.
Being themselves imbued with a sense of the value of the restraints of the cross,
they were careful to train up their dear offspring in such
a manner as to prepare them for bearing it faithfully,
when they had by degrees to act for themselves.
Some of them, we see, were early delivered from the trials of the world,
passing to final peace through a short path: others still survive,
to bless the Christian care and love, and even the pious restraints,
of their honorable parents.

On the 15th of the Twelfth month, 1770,
Sarah Evens had been downstairs for the last time;
and was very much fatigued with getting up again.
When a little recovered, she said, in an awful manner, '`Mother, I was afraid,
some time ago, I should never get to heaven; but now am in hopes I shall:
for I thought in my sleep, some days since,
that there was only a little piece of something white that kept me;
and I pulled it very hard to get it away; which I did, and then I got there.`'
Some days after, she said, '`I hope the time of my release will soon come.`'

On the 24th, having had a very restless morning,
between twelve and one she fell into a very comfortable sleep.
When she awoke, she said, '`I have been asleep, for which I am thankful.
It was what I prayed for: but I thought my prayers were not worth being regarded;
but they have been mercifully granted.`'
After a little pause she said, '`What should I do now, if I was like some?
May they be brought to a consideration of their ways.`'
Her mother replied, '`My dear, I hope your mind is easy;`' to which she answered, '`Yes,
quite so.
I have not anything that makes it otherwise.`'

Nevertheless, one day being very full of pain, and exceedingly low in her mind,
she said to me, '`Dear mother, I am afraid now I shall not be safe at last.`'
I asked her if there was anything that made her uneasy.
She replied, '`No, but only fears.`'
I said, '`My dear, endeavor to keep your mind still,
and I hope you will again be made easy.`'
On my going to her in the morning, and asking her how she did, she said,
'`My body is no better; but I am favored with an easy mind.
I never knew such a day in all my life as yesterday.
I am like another creature now, for now I witness peace.`'
She continued in patient resignation to the divine will,
not once expressing a desire to live longer,
but often saying it was better for her to go than to stay.
Thus she grew gradually weaker;
and on the last night of her sufferings she was exceedingly restless.
On my requesting her to be as still as she could, she lay still for a few minutes,
and then broke forth in supplication to the Lord, '`O! Father,
be pleased to grant me a little ease before you take me to yourself.`'
In a very short time her request was granted, and then she said,
'`I was afraid my prayers were not worth being regarded; but they have entered,
and I have rest.`'
She was often earnest to be released.
A friend about this time asking her how she did, '`You see,`' said she, '`how I do
I am going, I hope, to heaven.`'

She uttered many more expressions to the same import,
continuing to draw her breath shorter and shorter,
till between six and seven on the 16th of the First month, '`when,`'
continues her sorrowing, not repining mother, '`it pleased the Lord, who gave her to us,
to take her from us; and I doubt not in the least,
that she is entered into that rest which she so earnestly desired and prayed for.`'

And, though it is a close trial to part, yet,
as she expressed a little before her departure that she
had not the least doubt that we should all meet again,
several of her near relations being by her, the fervent breathing of my spirit is,
that we may be enabled to follow her, and live forever in realms of eternal bliss.

[.asterism]
'''

ROBERT EVENS, son of Benjamin and Elizabeth Evens, of Woodbridge,
finished his short course of eighteen years the 29th of the Eleventh month, 1772.
His decease was occasioned by a fall,
in which the butt-end of a fork was forced with violence against the pit of his stomach.
It did not prove immediately mortal, though he had more or less of constant pain,
which he endured with great patience.
His employment was at that time in agriculture,
and he was able to go about his usual business,
if he took care not to pursue it too eagerly;
otherwise the ill effects of over-exertion would occasion a confinement of several days.
He appeared to possess a firm mind, not easily to be moved; and a pleasant temper,
exceeded by few.

As his ailments did not yield to the means made use of, but were rather growing worse,
his employer thought it best for him to be under parental care;
and he returned home about ten weeks before the period of his life.
A rapid decline came on, accompanied with violent pain in the breast and stomach,
and with an almost incessant cough.

In the forepart of his illness,
he seemed to have some expectation that he should recover; but as his disorder advanced,
he was wholly divested of all thoughts of that kind;
and many times expressed to his parents the goodness of the Lord which he felt,
and the comfortable seasons which were his portion.
Being asked how he found his mind when looking to
that awful period which might shortly approach,
his answer was,
'`Entirely easy;`' and the last time a question of this sort was put to him, he added,
'`but it looks as if I might have a lingering time,
yet I hope to be preserved in patience.`'
Contrary, however, to his expectation, on the evening of the same day,
his pain greatly increased, attended with great difficulty of breathing.
No impatient expression escaped him; but, in the greatest extremity,
he fervently prayed for patience; and, between nine and ten, he resigned his breath; and,
says his pious mother and careful attendant, arrived, I fully believe,
at that mansion of rest, where he will sing high praises to Him who sits on the throne,
and to the Lamb, forever more.

[.asterism]
'''

FRANCIS EVENS, son of Benjamin and Elizabeth Evens, so often mentioned in this volume,
died when he had nearly attained the age of twenty-one, on the 25th of Tenth month, 1779.
I take this account of him, as most of the others, from the memorandums of his mother,
and I am inclined here to prefix the little introduction
with which she has prefaced her account of this loss.

"`My mind,`" says she, "`has often been humbled under the late trying dispensation,
wherewith it has pleased Infinite Wisdom again to try and prove us;
and the fervent breathing of my spirit at seasons is, '`Though tried, O Lord,
grant we may not be forsaken; and, though proved, let us not be forgotten of You,
you Fountain of all good, who, in the midst of judgment, remembers mercy.`'

Francis underwent much conflict of mind before he was enabled
to repose with confidence on the bosom of mercy.
Many days and nights he was tossed with tempest,
'`lest he should not be favored to obtain a habitation in the heavens.`'
But, after much labor, and fervent cries to Him who knows the integrity of the heart,
the arm of everlasting mercy was extended, and he was enabled to acknowledge it,
though he did not choose to enter into much conversation.
He appeared from time to time broken and contrited, and would often say,
'`No matter what becomes of the body, if the soul may but enter the glorious kingdom.`'
About two weeks before he died, his mother, perceiving him to be very low,
asked him whether he had any expectation of recovery; '`No,`'
he replied; `'in a very short space I shall be at my everlasting habitation.`'

His mother attended him constantly, and they had many solemn seasons together, which,
says she, were graciously owned by the incomes of the heavenly Father`'s love,
to the tendering of our hearts.
His fever, towards the last, affected his head; and,
when he could not be distinctly heard, his mind seemed attracted upwards.
Yet, probably from the degree of delirium which sometimes prevailed,
he felt occasional disquietude; and once, looking steadfastly at his mother,
who only was then with him, he said, '`I admire my mind should be so tossed;
but not from an apprehension I shall not be received,
for I have had a sure evidence of that.`'

The last two days of his life his pains left him in a good degree,
but the evening before he expired, he appeared to have a hard struggle for half an hour.
The next morning his sister,
passing the door of the chamber in which her dying brother lay, heard him loudly calling,
Father.
She thought her father had been in the room, but she found him below.
He went up directly, and told the youth that his sister said he had called him.
The youth looked attentively at his parent.
'`I did not,`' he replied, '`call for you; but to my heavenly Father.`'
Then he lay still again a few minutes, and quietly breathed his last.

[.asterism]
'''

ANNA MARIA BOWMAN, wife of Henry Bowman, of Ringwood in Hampshire,
and daughter of Benjamin and Elizabeth Evens, of Woodbridge in Suffolk,
sister to the subjects of the four preceding memoirs,
was carried off by a consumption in little more than a year after her marriage,
and in the 27th year of her age, the 20th of the Twelfth month, 1793.

About a month before this, she had been confined to her chamber,
from which time she gave up all expectation of recovery.
About this time a message of love was delivered to her from Samuel Emlen,
of Philadelphia, then in England.
He said that a passage of Scripture had dwelt on his mind on her account,
and that he should hardly do justice to his feelings if he withheld it.
"`In me shall the Gentiles trust, and their reign shall be glorious.`"
This Friend was remarkable for his acquaintance with the Scriptures,
and therefore I think there is some reason to suspect an error,
either in the delivery of the message, or the recollection of it;
for the text stands thus: "`To it (that is, the root of Jesse) shall the Gentiles seek,
and his rest shall be glorious.`"
The languid, diffident, and humble young woman, wondered that he,
an eminent and much beloved minister,
should notice her so much as even to send his love to her;
but she said that the sight which he had of her state was as balm to her mind.

The same evening she requested her husband not to grieve for her,
but to give her up cheerfully.`'
The more readily,`' said she, '`you resign me, the greater will be your peace.
We have lived in love the little time we have been together; and, as I said before,
the more readily you give me up, the greater will be your peace.`'
Afterwards she repeated to an elder sister, who was attending her,
the message of Samuel Emlen, and said to her, '`Well,
I have great encouragement to look forward; and I desire patience,
to continue to the end.`'
She desired her sister, who was writing to their parents, to give her duty to them,
and request them not to grieve;
and to tell them that she should be glad to see them once more,
but that she desired to stand resigned.

The next afternoon she was convulsed to such a degree,
as that those who were with her believed her to be near her close;
but on being put o bed, toward evening she revived, and,
after some inquiry respecting the attack from which she had just recovered, she said,
'`It was a fit, and a warning of what is coming.`'

To a young woman who visited her, she said, '`We have witnessed many seasons together,
and some, I hope, to profit.
I know your situation is much exposed.
You have kept your place, to your credit, and the admiration of many.
Stand open to the manifestations of truth.
Give up, give up, to what you know to be right, and you will find your account in it.`'
On the first of the Twelfth month, John Merryweather, the husband of her sister Kezia,
mentioned in the ninth part of this work,
was telling of the satisfaction which he had in seeing her so easy and resigned;
to which she replied, '`I stand ready, whenever the Lord is pleased to call.`'
Soon after, she desired to see her own brother, and, requesting him to take a chair,
said thus: '`Dear brother, I cannot express what I have felt for you this day.
I know your situation, and the difficulties you labor under;
but let me impress the necessity of attending week-day meetings as much as you can.
You will find your reward.
As to your wife (who the reader should understand
was not at this time a member of the Society),
let her alone.
She is a woman of tender feelings.
Do not persuade her one way or another, as to religion.
Be steady.
The Lord loves you.
I am sure he loves you.`'
She many times desired her relations not to fret; for that, she said, grieved her;
and once she said to her husband, '`Look as cheerful as you can.`'

The next day she was again faint and convulsed, but not so much as before;
yet in the night her sister thought her worse,
and inquired of her whether she were faint.
After a while she replied, '`No. I felt as if I wanted for nothing just then.
Be not frightened.
I do not feel as if I was going.
I think I shall have a clearer evidence at that time.
I think I shall.`'
Her cough and shortness of breath were often very afflicting;
but a sweetly composed frame of mind was the means of her daily support,
and was an instructive lesson to those who attended her.

On the 7th, as she was undressing, in order to retire to rest, she said,
'`I fear I shall not experience such a calm as I did last night.
I have reasoned several times today whether the favor was not too great to be mentioned,
for I felt as if I was in heaven, and saw the angels there.`'
She not infrequently talked in her sleep, and once was heard to say very distinctly,
'`When shall I drink of the water of that clear river?`'
This seemed to show that her sleeping, as well as waking thoughts,
were fixed on the eternal recompense of reward.`'

Her decline was rapid, and her patience did not fail;
but she often begged that it might be continued to her.
The day preceding her departure, her body was restless, she took but little food,
and requested that not any might be offered to her.
About one the following morning, she seemed inclined to sleep,
and desired the family would also retire.
At five, they were again called, and her husband going to her, she only said,
'`My dear Henry,`' and then fell asleep.
In about half an hour her breath became greatly affected for a few seconds;
but again recovering it, she laid her head on the pillow, and in her sleep,
so quietly as scarcely to be perceived, she sweetly breathed her last.

[.asterism]
'''

ELIZABETH EVENS.-- Though I have not to record many
particular expressions of Elizabeth Evens of Woodbridge,
wife of Benjamin Evens;
yet as notice has been taken in this volume of so many of her children,
who were conducted by the grace of their Redeemer to a peaceful close,
some account of their pious mother seems an addition almost requisite.

She was the eldest daughter of Francis and Mary Lawrence of Norwich,
and was deprived of both parents by the time she was about sixteen years of age;
at which early period the care of four younger sisters devolved on her;
and she performed her trust so well, that on her marrying, and removing to Woodbridge,
they also came, and dwelt in a house adjoining to her residence.

About the twenty-eighth year of her age, she came forth in the work of the ministry,
uttering in her own meeting at Woodbridge, these words;
"`Obedience is better than sacrifice, and to hearken to the voice of the Lord,
than the fat of rams.`"
This was in the year 1753.
Rather more than three years afterwards,
she set out on a visit to the meetings of Friends in Essex;
after the accomplishment of which service, she had this testimony to bear;
"`I had renewed occasion to be thankful that it pleased my great Master,
not only to move upon my mind to go forth in that service, but to go along with,
and safely conduct me again to my habitation in peace.
It is a cause of more joy than words can express.`"

Notwithstanding she had the care of a large family of children,
and much affliction fell to her lot,
by the decease of several of them when they were just entering,
or had entered that time of life in which dutiful children become, in some respects,
the companions, the friends, the support, and the solace of their parents;
she continued freely given up to travel in the exercise of the gift which she had received,
as the pointings of duty were manifested to her.
The eastern counties, some of the northern and midland,
with the cities of London and Bristol,
were the principal parts to which her services were directed.

In the year 1782, she was much enfeebled by a paralytic stroke;
nevertheless she continued a diligent attender of meetings when bodily ability admitted;
and even sometimes, when many would think their weakness an almost insuperable bar.
'`Do not give up,`' said she on a particular occasion, '`the assembling with your friends,
for it is many times strength in weakness; and the poor mind,
being stayed upon Him who is the only helper of the helpless, is sometimes,
out of deep poverty, made in secret to bless the name of Israel`'s God.`'

It was also after this debilitating disease had been permitted to enfeeble her frame,
that she paid a religious visit to the meetings of London and some others in the neighborhood;
and after this she visited the families of Friends in Norwich,
and most of the meetings in the county of Norfolk.

She was at length removed from this state of trial,
in which she had so long endeavored to fulfill the gracious design of her Lord,
in visiting her with his love, the 13th of the Fourth month, 1796.
She was not long confined to her chamber, and during this time,
did not express much of her mental feelings;
but there was a sweet composure on her countenance,
which seemed to evince that her day`'s work was done; and that,
with becoming patience and holy resignation, she was waiting for the period which,
through his adorable mercy, should unalterably unite her to the beloved of souls.

[.asterism]
'''

BENJAMIN EVENS--It has generally been esteemed particularly encouraging, to observe,
in collections of this sort, the lively hope expressed by young persons,
who have early felt the touches of redeeming love,
have submitted to its purifying power in the dawn of their faculties,
and have been early gathered into the garner of rest.
But the survey of a long life,
passed in almost uniform conformity to the law of the gospel,
and closing in its peaceful spirit,
even though it has not been marked with the performance
of many signal and attractive acts of service in the church,
holds out probably an instruction equally valuable,
although of a species somewhat different.
One prompts the youthful mind to enter with alacrity,
and without reserve on the heavenly race; the other encourages the humble diffident mind,
which aspires after the crown that is at the end, and has already made some progress,
to persevere in it without fainting.

Benjamin Evens, of Woodbridge, in Suffolk, who finished a course of about eighty years,
the 27th of the Twelfth month, 1798, was considered by the Friends of that county,
as a good example, and a very diligent attender of their meetings.
In those for worship he at times bore a public testimony for truth,
having long been an acknowledged, and approved minister; and,
while his faculties retained their vigor,
he was conspicuously useful in supporting the Christian discipline of the Society.

He did not travel much.
There are not accounts of more than two journeys with a certificate.
The first was to Friends in the counties of Lincoln, Cambridge, Huntingdon, and Norfolk;
the other to those of London and its neighborhood.
At the time of this last visit he was already an old man, but humble and unassuming:
which just tribute to his memory, the writer of this short memorial,
who had then the privilege of having him for a guest,
is desirous of adding to the testimony of his Suffolk friends.

A little incident occurred during this engagement which may not be improper to relate.
In a meeting in which he had been largely engaged in testimony,
he misquoted a passage of Scripture, and in a way that materially affected the sense.
Finding out his error,
he rose again towards the close of the meeting to acknowledge it to the congregation,
to show how his variation implied a doctrine, differing from that of the text,
and to testify his adherence to the latter.
And in his walk from the meeting,
his tears of sorrow flowed as he continued to expatiate on his mistake;
and he appeared to claim and to need all the consolation
which his attendant could afford him.

Some time before his decease, his faculties gave way;
and his last illness was accompanied at times with violent pain;
but he was preserved in love to all,
and enabled to bear his sufferings with a comfortable degree of patience,
and resignation to the will of God: to whom he frequently prayed,
'`O you fountain of all good, look down upon me if it be your will,
and ease me of my pain.`'
Once he expressed himself after this manner: '`My love is to all,
but especially to the faithful.
Let it be known, I die in peace with all men.`'
One night, before composing himself to rest, he exclaimed, '`Farewell, farewell.
All is peace, peace, peace and joy.`'
These consoling words he again repeated, and then he fell asleep.

His prayer seemed mercifully granted during the two last weeks of his life,
as he was generally much relieved from pain; and he at length departed, full of days,
and full of peace.

[.asterism]
'''

JONATHAN RAINE, of Sunnyside, near Crawshaybooth, Lancashire,
where he had removed from Trawden, departed this life the 27th of the Eleventh month,
1773, aged about seventy-five years.
His parents being members of the Society of Friends,
educated him in the principles of our profession;
but he seems to have neglected in great degree the circumspect
way in which they had endeavored to direct him;
and to have been much infected with the spirit of the world, and the vanities of life.
Thus he seems to have remained until his fortieth year, during which time he married,
had three children, and was deprived of them all, and also of his wife.
His residence was then in the county of Durham.

At length, as his friends relate in their testimony of him,
it pleased the Lord to reveal his righteous judgments
against the transgressing nature in him;
when he stooped to the cross of Christ,
and patiently endured the baptism of the Holy Spirit:
thus becoming qualified for the work to which he was called.
The reader may here truly anticipate,
and conclude that the work in question was gospel ministry;
but let him also be sure that by these means also, and only,
qualification for other services, and for every service, in the Lord`'s house,
must be obtained:
and who is there that will not ultimately wish to be the Lord`'s servant,
seeing that his undeceiving lips have declared, "`Where I am, there shall my servant be.`"

In order to be more fully at liberty to follow the vocation
with which this Friend perceived himself to be called,
he left off business, into which he had engaged when young;
for something of what has been termed '`true moderation`' now bounded his desires.
His first appearance as a minister was about the year 1740.

In the year 1746, he married Margaret Birtwistle, daughter of Henry and Mary Birtwistle,
of Rossendale, Lancashire, and soon after came to reside at Trawden,
within the compass of Marsden monthly meeting; where he was a diligent, zealous,
and exemplary minister, and member of religious society.
He travelled through various parts of Great Britain; and in the year 1760,
was one of a committee appointed by the yearly meeting
to visit the meetings of Friends in Ireland.
He attained to a good old age, and had, in the winding up of his days,
but a short allotment of illness.

About two hours before he breathed his last, having lain still for some time,
he desired to be helped up, and, as nearly as can be remembered, spoke as follows:
'`I want to tell you a little of what has appeared to the view of my mind,
as I was lying and reflecting, that my time seemed to be near the conclusion.
I earnestly breathed to the Great Informer,
that he would be pleased to show me my own state, and how it was with me,
and to forgive all my sins.
And there was shown me some little stones, laid in regular order,
and a path through the middle of them.
The first heap, it was told me, were the sins of my youth;
and they were all passed by and forgiven, for the sake of Christ:
though my sins and backslidings were many.
Yes, there was a time when my trouble and distress were such,
I could have wished that man had died as the beast that perishes,
and that there had been no rewards nor punishments after death.
I could have been content to have been shut up in a dungeon,
never to have seen the light again, if I thereby might have gained peace.
In unutterable condescension it pleased the Lord to break in upon my soul,
as the light of the sun after a long darkness; which so overcame me,
that I believe if an account had been brought me
that all I had in the world had been lost,
it would have given me no concern.
Oh, Friends, you that are young, my desires have been earnest for you,
that you might seek after that which is better than any earthly enjoyment;
and bend your necks to that which is able to yoke down every unruly passion,
and every inordinate desire; that thereby you may obtain everlasting peace.

'`The others that were showed me were all white stones.
There was no dirt upon them.
Though there had been many slips, and many omissions,
yet they were all washed away and remitted.
There remained only one, which was,
that I had been sometimes too thoughtful that the
people might have somewhat spoken to them;
and as that sprung from a good intention, it was also remitted: and then, friends,
the peace, the comfort, and sweetness that I felt was unspeakable.

'`I was desirous to leave this as a legacy with you.
Oh, you that are young, seek after it.
Press after that divine help,
which alone can make you possessor of that peace which the world cannot take away.`'
A little while after this, he perceived his wife to be sorrowing, and said,
'`Do not grieve for me, my dear.
I am quite easy.
I could not have believed a few days since, I could be so resigned,
and willing to be dissolved.
But, oh! the condescension of the Almighty,
and the unutterable love which fills my heart!`'

[.asterism]
'''

SARAH CLARE, was the daughter of Thomas and Hannah Clare, of Warrington,
born there in the year 1759, and was removed the 31st of the Seventh month, 1781.
She was an innocent young woman;
but not noticed for anything particularly striking in her conduct,
till she was visited by the illness which terminated her days.
It was a consumption; and after it became the means of confining her,
was only about ten weeks in performing its office.
She had then entered her twenty-third year,
and from the beginning of her illness she appeared to be resigned,
and often bore testimony to the Lord`'s goodness, and to his tender dealing with her,
in favoring her with his presence,
and the lifting up of the light of his countenance upon her.
In an affecting manner,
she once said `'I am afraid I shall not be able to be thankful
enough for the kindness and goodness of the Lord to me:
and this latter part exceeds all.
I cannot convey to another what I have felt, and the desirable prospect I have in view:
nothing in this world to compare to it.
If I might choose, I had rather die than live;
but I do not wish to go before the right time; but to wait in patience.`'
Patience, indeed, seemed to be the covering of her mind.

On one occasion, she expressed her sorrow in observing,
that so many of our youth were strangers to retirement; saying also, '`I love it,
and the company of solid friends.
But,`' said she, '`if others want to come and see me, if it might instruct them,
or cause them to consider their latter end, I should be glad.
One knows not.
It may be brought to their remembrance in future.`'

At another time, she expressed herself thus: '`I feel quite easy.
Death has no terror.
It is a fine thing to have no will or choice of one`'s own, but to trust in the Lord.
Though my cough seems troublesome, and matter hard to get up,
yet hard things are made easy to me.`'
Indeed, such sweetness attended her mind,
that she seemed as though she were in heaven while on earth.

About an hour before her gentle spirit departed,
she took an affectionate leave of the family, who were present,
thinking she was then about to enter into the rest of God.
She was however again detained for a while, and said, with an audible voice,
'`I have been at the door of heaven.
It was open for me.
I beheld the Almighty sitting on his throne.`'
She also said,
that it was then intimated to her that there was something more for her to do.
Then she embraced her sisters, and with great fervency of mind added,
'`Do come and see how good he is.
Oh, it is a sweet place.
He gathers his lambs in his arms, and carries them in his bosom.
Oh, I could invite all to come and see how good he is.
He is not a hard master.
Praises and glory be to him forever.`'

She afterwards, when her voice faltered, was heard to utter the words Jacob and Israel;
and appearing to be in what may be termed a triumphant melody,
breathing shorter and shorter, she quietly passed away.

[.asterism]
'''

POTTO BROWN, son of John and Sarah Brown, of Earith in Huntingdonshire,
was born there the 16th of Fifth month, 1765.
He discovered, in early youth, a serious and religious turn of mind,
which his tender parents were concerned to cherish; and as he grew up towards manhood,
the seed of the kingdom sprung up in his heart, and gradually increased.
He was a good example to the youth, in his words and actions;
and was beloved by those who had any acquaintance with him, both friends and others.
He left behind him a journal of his life; in which many minute particulars,
and incidents relating to himself and others, are noted;
and from which the following extracts are made:

In a letter addressed to a youth with whom he had formed
an intimate acquaintance at school,
he expresses himself after this manner:

[.embedded-content-document.letter]
--

I hope, as we travel on through this transitory state,
we shall be enabled to cast the cares of this world behind us,
looking to the Author of all good: who will help all those who trust in Him.
I believe, beyond all doubt,
that all those who trust in Him will not lack the bread of life.

--

On the 6th of Eleventh month, 1783, a remarkable occurrence fell to his lot,
which take nearly in his own words: '`This morning, a little after four,
I set off from Ely to go to Ramsey,
to attend the marriage of my cousin Joseph Brown Allen, and Ann Turner.
When meeting was gathered, we sat in silence about half an hour; when Thomas Cox,
of Earith, rose up; and having appeared in public testimony about half an hour, sat down:
about a minute after which he was seized with an apoplectic fit, and expired immediately.
This sudden and awful stroke threw the meeting into confusion.
We gathered again in about a quarter of an hour, when Isaac Gray stood up and spoke.
Soon after he had finished his testimony,
cousin Joseph Brown Allen and Ann Turner were married, and the meeting broke up.

'`In this meeting I was favored with a vision as follows: I held down my head,
and shut my eyes; when lo! to my inward view,
I beheld our Savior coming down in the clouds, in the dress of a country farmer,
with a great coat on.
He stretched forth his right hand toward a man who walked to him;
and took hold of his hand.
This man went with him; and he looked towards me with an eye of concern.
I went as I thought towards him, and took hold of his hand;
but he told me that I could not go till the briers and thorns
were removed which lay between him and me.
This gave me a surprise, and all vanished away.
I then held up my head, and saw Thomas Cox dying.

'`The 9th of the same month Thomas Cox was buried at Earith, but I could not go,
because my foot had been very much strained: so I lay in bed till dinner.
The Lord then showed me, to my great comfort, that my dependency must be on him:
so that I began to inquire how it stood with me and my God.
Then was I humbled to cry, "`Help me, O Lord, or I perish.`"
The word was, "`Draw nigh unto God, and he will draw nigh unto you, indeed.`"
Then began I to meditate on the Lord in the night season,
and was greatly refreshed thereby.
A voice passed through me, saying, "`You must not have any conversation,
but what may profit your soul; for unto that man that orders his conduct aright,
will I show my salvation.
Your mind must be set on heavenly things, and your conversation on heaven.`"`'

In a discourse he had shortly after with his cousin Ann King,
on the subject of what he had seen in the meeting at Ramsey, she said to him,
'`I see the interpretation is plain.
The briers and thorns must be cut up before you can go to heaven.
Keep to the exercises that are within you;`' for I had told her, says he,
'`how it had been with me ever since.`'
'`You have read some books to your hurt, which I advise you in future to avoid.`'
'`These words,`' said he, '`were spoke with such authority,
that I knew full well she was empowered of the Lord.
They ran through my heart like oil, and gave strength and comfort to my soul.
Trust in the Lord, O my soul; for the Lord loves holiness,
and purity is his delight.`'

The 29th of Eleventh month he wrote after this manner:
'`For the last three days nothing material has occurred; but glory be to our God,
for he has dealt wonderfully with his servant.
I cannot express the comfort I have felt in keeping
to the operation of the word of life in my own heart.
The Lord has showed to me the pure state in which our primitive Friends stood;
and also the fallen state of many among us at this day; which is to be mourned by me.
I hear some American friends are landed, who will come and strengthen those,
to whom it pleases the Lord to manifest his glorious work.
He will not be mocked by men of low degree; who set their minds on earthly enjoyments,
and think not on the name of the Lord.
He has given every man ability to know that he is a just God, who dwells in the heavens;
and those who will serve him must set their minds on heaven;
from which they shall receive their help.
Those who are heavenly shall declare his name to all generations,
to the convincement of thousands, that the Lord is God!
Blessed be his name! says my soul, for taking me by the hand,
and leading me out of the paths of vanity!
May I be enabled to evince, by words and actions,
that in conduct the Lord is to be praised; and honored in stillness.
I hope those who shall see my journal after my decease,
may not think I have written this of myself.
I can honestly say, that the Lord has guided my hand and opened my mouth.

'`The next day I went to Littleport meeting;
where it pleased the Lord to open my mouth in a public manner,
in which I had great satisfaction, in that I had been obedient to the divine will.`'

In answer to a letter he received from his mother,
in which she expresses her great concern for his welfare; he says,
'`The Lord has been pleased to pluck my feet out of the miry clay;
and to open my mouth to make known his will among his people.
I hope it will ever be my care to keep near him,
as I have experienced a drawing near of the Lord to me; my heart is broken and contrited:
blessed be his holy name!
He has showed me the way wherein I am to walk.
O, entreat my brothers from me, to follow after the Lord in purity and holiness,
and to wait for his counsel.
O that I could express the hundredth part of what I feel in being renewed in his counsel;
but I must leave them to the Lord.`'

The 2nd of Twelfth month.
This day a cloud covered me, and a temptation wounded my soul.
I was drawn to consider how the Lord pardoned the thief on the cross,
and to make it a cloak for trusting to a dying hour;
but I felt the rod that chastised me, and heard a voice, saying,
"`How camest you to take thought against your God?
He will not be slighted, but looked unto with a single heart, for all help.

The 11th. I found that, during my late journey, while my mind was turned inward,
then was his presence with me; I was preserved in the truth, to my inexpressible comfort.
O may I always keep watch, lest the enemy draw my mind from being stayed on the Lord.

The 17th. Many are the temptations which the enemy lays to draw my mind from the Lord;
but, look you, O my soul, to the Lord with unfeigned sincerity,
and with full purpose of heart,
in the humility of that spirit which enlightens you
and strengthens you against them all.

The 4th of the First month, 1784.
In the course of a visit I lately made to my parents,
two of my relations opened their minds to me, concerning my public appearances,
wishing I might be favored to support the honor of the blessed truth;
which was done in so affecting a manner, that it helped and strengthened me much.
This day I went to Littleport meeting, where I spoke a few words.
Oh, how I felt the Lord with me this day; blessed be his name!
Many were the breathings of my soul at times,
that the Lord would keep his fear always before my eyes, that I might not speak a word,
but to his honor.
Oh, that it was the case of all those who profess with us,
that nothing might be done but to the glory of God: that we may say,
"`Yours is the kingdom, the power and the glory, forever!`"
Then should we answer our high and holy calling.

The 15th of the Second month.
I never used to write concerning my spiritual welfare
till I was in a right frame of mind,
under the influence of the power of truth.
From the 19th of last month I have known a going backwards, as from Jerusalem to Jericho;
but the hand of God was not shortened:
but he has made me know that I must be obedient to him.

The 17th. This day, in my retired thoughts,
I was made sensible how much we ought to keep ourselves in humble reverence to our God,
under a consideration of his omniscience and our nothingness.
Oh, if people would but behold their dependency on Him,
they would be afraid of having their minds taken from under his protection;
much more of doing anything that would not tend to his glory; but, on the other hand,
they would testify against everything of a contrary tendency;
knowing that God is jealous of his honor,
and will be sought unto with fear and trembling.
David says (Ps. lxxvi.), "`You, even you, are to be feared,
and who may stand in your sight when once you are angry.

The 19th. This day was a day of hard labor to me, because I was off my guard last night,
by entering into a long and needless discourse, which drew my mind from the Lord;
but he was good to me, and heard me when I cried,
for my spirit was bowed down in humility before him,
and heavenly joy abounded when I confessed my error to him.
This is an evil which many of our Society fall into,
even those who have been religiously inclined.
(See Book of Extracts, on the head of Conduct and Conversation.)

The 25th. I have this day oftentimes felt a refreshing power, with a secret promise that,
if I kept under the guidance of the power of truth,
I should not do anything to dishonor it,
for a fear arose in me that I did things that were not an honor to it.
A voice was in me, "`Humble yourself, and you shall be favored.`"
I have felt a service in keeping a journal, as it helped to keep me from going back;
encouraged me in seeing how I was favored before,
and what progress I had made in the truth.
What pleasure has it given me to write of my progress heavenwards!
On the contrary, what lashes have I felt, when I was not in a frame to write!
When I had walked obedient to his power, he always gave me a frame to write.

The 27th. Last First-day, I wrote to a Friend concerning our serving burials,
which I saw, in a clear light, was not consistent with us as a people; because,
when we serve a burial, it is to gratify the pomp and vanity of the people of the world,
which is a plain contradiction to that Spirit which we profess to be guided by.

The 8th of Third month.
This day I had a concern to speak to a Friend concerning gaping in meeting,
and on another subject.
He was very high in his expressions; but, finding that I spoke according to the Spirit,
he was silent, for truth will always prevail.

The 9th. This day, being alone, I read my journal over to the Second month,
which helped me to see how I followed after God,
who called me to be more and more humbled.
Oh, I felt his goodness to flow towards me!

The 18th. I saw I could not be in such a humble state as I had been called
to come into without I became as clay in the hands of the Great Potter.
I saw that my body was to be the temple of the Holy Spirit,
and that no defiling thought must lodge within me.

The 21st. I went to our meeting at Ely,
and many were the refreshings that my mind there felt.
I saw that the Spirit of Christ was the only way that leads to celestial bliss,
and that he teaches his followers to be humble as he was humble;
that we must not barely believe that he came down among men,
in a body prepared for him, but must also believe in his power,
that leads to life eternal.
Be still, O my soul, and you will find his power made manifest in you.

The 16th of Fourth month.
I find that the more I give up my mind to seek after the kingdom of God and his righteousness,
the more I advance in the work; the more I keep in the power, the stronger I grow.
My soul longs for the living God; yes, my inward cry is raised for the bread of life,
more than the natural man hungers after natural food.
Here ends the journal of this pious young man.

About this time his health began to decline,
and some symptoms appeared that seemed to threaten a consumption;
he was therefore removed from his master`'s to his father`'s house,
that he might try his native air and the effects of medicines;
but the disorder baffled both.
In the latter part of his illness, he was remarkably patient under his bodily affliction,
which was long and sharp; those who assisted in his illness,
said they never saw any one bear so great pain with so much patience.
A little before he was confined to his chamber, his mother, who was helping him to bed,
found he grew weaker, and said to him, '`Potto,
do you not think you are grown weaker within these few days?`'
He answered with as much cheerfulness as if he had been in health, '`Yes, I know I am;
but what matter?
If the outward man grows weaker, the inward man grows stronger;
I experience the strengthening of the new man every day.`'

Another time, being very sick and in great pain, he said he could not bear too much,
mentioning how much Christ bore for him;
but his mother could not expressly remember his words.
One day his father, sitting by his bedside, and observing him appear dull,
asked him if he was any way uneasy about his future state.
He said, No; for he had many comfortable assurances it would be well with him.
He then burst into tears, and said he was uneasy for his brothers,
fearing they might be drawn from the truth.
His father desired him not to make himself uneasy about them;
for there was the same divine hand to guide them, which guided him;
and if they adhered to it, it would do the same for them.

A few days before his departure, a friend from Ely came to see him,
and asked him how he did.
He said he was very ill, but did not wish to live,
nor did he think it his place to pray for death.
The night before his departure, he said to the woman that sat up with him,
'`Go tell my mother that I am very bad, and think she would like to be here.`'
When she came to him, he told her he was a great deal worse;
but he desired that she would not be troubled at his change,
which he expected would be soon.
He uttered many more sweet expressions, which cannot be remembered,
and departed this life the 16th of Tenth month, 1784, aged nineteen years.

The following was found in his pocket-book, after his decease,
giving an account how he spent his time, while ill at home.
Eighth month, 13th. 7 to 8, reading; 8 to 9, walking; 9 to 10, writing; 10 to 11,
retirement; 11 to 12, walking; 12 to 1, dinner; 1 to 2, walking; 2 to 3, reading; 3 to 4,
writing; 4 to 5, walking; 5 to 6, reading; 6 to 7, retirement.
