== Chapter 4

[.chapter-synopsis]
* Esther Tuke
* William Prideaux
* Sophia Pope
* Sarah Crawley
* Mary Bass
* Samuel Emlen
* Hannah Wilson
* Benjamin Kidd
* Sarah Bland

ESTHER TUKE, of York, long known and beloved in the Society of Friends,
who died the 13th of the Twelfth month, 1794, was daughter of Timothy and Ann Maud,
and born at Westcoals, near Halifax, in the year 1727.
Her parents afterwards removed into the neighborhood of Bingley,
where her father died when she was about twenty-five years of age.
In the early part of her life,
she was captivated with some of the vanities to which youth is liable;
but the loss of her father, and a concurrence of some other trying events,
tended to humble her, and to prepare her for the reception of a divine visitation which,
about this time, was powerfully extended to her.
To this gracious influence she bowed in filial submission.
She was willing to bear the cross, and to despise the shame;
and chose rather to suffer affliction with the people of God,
than to enjoy the pleasures of sin for a season.

At this time of her life she was very distantly situated
from the particular and monthly meetings to which she belonged;
yet she was a diligent attender of both.
Many were the exercises which she had to experience;
but as she abode in patience under the operations of the holy Hand,
she became a vessel sanctified, and prepared for the Master`'s use.
About the thirty-fourth year of her age, she gave way to an apprehension of duty,
which had long been in her view; and appeared in public as a minister,
with these few words; "`The just shall live by faith.`"
From this beginning, apparently small, she was enabled to increase;
and as she grew in years she was thought also to grow in faithfulness and dedication;
and truly attained to the state of a mother in Israel.
About four years after this more public espousal of the cause of righteousness,
she entered into the marriage state with William Tuke, of York, then a widower,
with several children.
In this station her discretion as a mother,
and the impartiality of her affection towards her own children,
and those of the former marriage, were such as are too seldom found,
and afforded an instructive example.

As to her travels in the service of truth, they were extensive.
She paid a general visit to the meetings of Friends in Ireland,
was several times in Scotland,
and Friends in most parts of this nation were partakers of her religious labors.
But it is rather the weight than the extensiveness of her service
which those who knew her best have been desirous to commemorate.
She not only deeply lamented the obvious departure
of many among us from our various testimonies;
but the state of such as are engrossed with the cares of this life; for she knew that,
though such may have been in past time awakened,
and may yet retain a specious appearance; yet,
their affections being centered in the earth,
they lose the qualification for religious service, and often obstruct it,
even when they appear to be its advocates.

She was particularly solicitous for the right education of youth;
and such was her concern on this subject,
that she united with a few other Friends in establishing a school at York for girls; and,
at their request, took the superintendence of it.
In the execution of this charge,
she appeared to gain the general good will of the children;
but she had greatly to lament the neglect of parents,
to bring into due subjection the tempers and wills of their offspring.
This neglect increases the difficulty of education,
causes the cross occurrences of life to be more painfully felt,
and renders it harder for the youthful mind to submit to
the necessary restraints of the Christian life.

In the middle stages of life, she was much tried by bodily indisposition.
This increased with advancing years;
but did not prevent her exertions when duty called her into religious service;
and she often travelled under difficulties that few would have encountered.
Still, she looked beyond these afflicting dispensations;
and frequently expressed her desire gratefully to number
the blessings with which she was favored.

Thus, as the course of her life was instructive, not less so were her closing days:
they were strongly marked with the humility of a disciple of Jesus.
She had often mentioned her apprehension that her last illness would be short,
and would not afford much opportunity for verbal expression of her feelings;
and in the view of her final change,
she often testified much satisfaction and peacefulness.
Her last illness accordingly only continued about a week.
Great, at that time, was the sweetness, and deep the solemnity,
frequently felt by her attending relations and friends.
In the self-abasement, already mentioned, she once did express herself to this purpose:
That notwithstanding she felt herself as one of the lowest of beings, yet,
as she had been favored to administer what might be only like a cup of cold water,
in the name of a disciple,
she fully believed that it was not the divine intention that she should lose her reward;
and that, though she should continue as in the depth of poverty,
this belief was sufficient.
And well might she thus say: Her confidence was in the promise of her Lord,
whose words are yes and amen forever! "`Blessed are the poor in spirit,
for theirs is the kingdom of heaven!`"

[.asterism]
'''

WILLIAM PRIDEAUX--In the ninth part of this work, published by Thomas Wagstaffe, in 1795,
there is an account of Mary Prideaux, a Friend, of Cornwall.
It is a pleasing portraiture of a dedicated and happy mind.
She was the wife of William Prideaux, the subject of the present memoir;
and it appears that they were united in a relation even more than conjugal.
The married state is generally allowed, by the virtuous,
to afford the most complete specimen of human happiness: but when,
to the ordinary requisites for producing this happiness,
is added a unity of religious feeling,
and a joint and harmonious endeavor to serve the Lord, then,
the state has attained the summit of the felicity of which it admits.

William Prideaux, of Kingsbridge, in Devonshire, was born about the year 1716;
and in the early part of his life did not profess the tenets of the Society of Friends;
but being convinced about the thirty-third year of his age,
he became a lively and useful member of it.
He was long in the stations of an elder and overseer,
and was a man peculiarly qualified for sympathizing
with the afflicted either in body or mind.

He lived to a very advanced age, surviving his pious wife nearly twenty-three years;
but the various lively expressions that fell from him during
the illness which terminated his lengthened course,
demonstrate that in mind he resembled the prophetic description of the Psalmist,
speaking of the righteous, "`They shall still bring forth fruit in old age;
they shall be fat and flourishing.`"

A few days after he was taken ill, he said, '`It is a mercy, that I feel ability to say,
"`Your will be done.`" `'Tis not in man`'s power to say so;
but I feel the power which enables me, and am thankful for it.
There is no terror in looking forward.`'
Then he broke out, '`O my soul;`' but seemed too full for further utterance,
otherwise than in sounds which bespoke the melody of his heart.
After this, by means of some medical assistance, he appeared to recruit;
but a symptom succeeded which appeared to portend, unless removed, a speedy dissolution;
and he received pleasure when he discovered it.

One day subsequent to this, on taking leave of a relation, he said,
'`I have always loved the truth, and now it does not fail me.
What I have always desired, I now experience.
I have nothing but peace in looking forward or backward.`'
Soon after he said, he loved to see his friends, but loved better to feel them:
twice exclaiming, '`All is well:`' and the same evening he said, '`I have nothing to do now.
What a great favor! we who have loved the truth in our health,
to experience its support on a dying bed!`'

The next day he remarked, '`It is not enough to call God Father by creation only;
but we must know him to be so by regeneration also.`'
On being asked if he were pretty comfortable, '`Yes,`' said he,
'`I don`'t know when I was otherwise.
How should I be otherwise?
My Lord God Almighty is with me, my dear Redeemer, whom I wish you and all to honor,
even in the little concerns of life.
He has done for me far beyond what I could ask or think.`'

Thus he continued a few days, evincing from time to time his resignation, his gratitude,
and his hope; and on the evening before his departure,
on an ineffectual attempt to relieve him by a surgical operation,
the calmness of his mind did not appear to be interrupted.
He had, however, suffered much fatigue from the attempt,
and complied with the request of his medical attendant, in taking an anodyne medicine;
but between four and five in the morning, he distinctly said,
'`I am going;`' and his breathing soon becoming more difficult, it ceased in a short time,
and he passed away without a sigh, in the eighty-third year of his age.
During his illness it had been evident that death was his desire;
but it is not recollected that he ever complained that his sufferings were tedious:
and the true resignation which through grace he had been enabled to attain,
was to be discerned in the serenity of his countenance.

[.asterism]
'''

SOPHIA POPE, daughter of Robert and Margaret Pope, of Staines, in Middlesex,
departed this life the 10th of the Fourth month, 1799,
in the twenty-second year of her age.
She was a young woman of a lively disposition,
and had not been remarkable for peculiar attention to religious duties,
and the concerns of a future state, until about the last year of her life.
About the time that she began to show symptoms of increasing care on these subjects,
her youngest sister Harriet was removed by a consumption, at the age of nearly 18 years.
Harriet had been infirm from her infancy.
A paralytic affection, which occurred before she was one month old,
had disabled her right side.
She, too, closed her days awake to the true interest of life; and Sophia,
the more immediate object of this memoir, now also alive to similar feelings,
penned the following short memorandum respecting her departed sister.

'`My dear sister, a few days before her decease,
mentioned how uncomfortable the state of those must be,
who delayed repentance till an hour when nature seemed scarcely
able to support the weakness under which a debilitated frame labored.
And, though she was not conscious of having committed any great error; nevertheless,
being too unguarded, her disposition had, she feared,
betrayed her into an unbecoming quickness of speech;
but having felt deep remorse whenever that was the case,
she hoped she had met forgiveness: for a sick-bed was not a place to recount past faults:
the mind, at such a time, had enough to do to preserve perfect stillness.
And, as she thought she should soon leave us, she wished that we, who remained,
would be comfortable; and added, that had she lived to a more advanced period,
she might not live in the manner she wished.`'
Her decease was the 25th of the Sixth month, 1798.

Sophia`'s good impressions continued with her; and beside the language of conduct,
are also evinced by some notes which relate to the end of this year,
and the opening of the new one, and were copied from her pocket-book.
On the former of these occasions she says, '`Another year of my life passed!
Ah, could I but improve every one of my remainder!
And though health has forsaken me for the present, still,
if it should please him in whose hands the determination of things pass,
to restore me to health,
I hope a greater attention to the truly needful will be my case.`'
Her new year`'s meditations ran in the language of prayer:
and here I would warn the critical reader, that in such expressions,
he must neither expect perfect accuracy of language,
nor be offended when he perceives it to be lacking.
The mind may be too intensely fixed upon the thing, to advert to the mode.

'`Teach me,`' says she, '`you great Author of all events below,
to bear your dispensations with patience becoming me, who am entirely dependent on you.
And although health has left me,
and I seem gently following a current that leads to my final end,
be pleased to make the passage through the valley of the shadow of death easy: easy,
I say, for O, that the sting might pass first.
Hard it is to the natural part to leave kind parents and friends; but, with your aid,
may they with fortitude support their minds,
hoping that the change may be for a more worthy inheritance
than I could have attained below.`'

By these remarks we see that disease had already seized and impaired her frame.
The same lingering but sure conductor of many a blooming youth to the tomb,
which had cut short her sister`'s days, was now preparing to do the like to hers.
She did not see a third of the advancing year;
but for the most part was preserved in resignation,
and in near affection to her parents and relations.
About three days before her departure, she prayed thus: '`Father,
although I have not walked before you so circumspectly as I ought,
yet you have been pleased, at seasons unknown to any but yourself, in my retirement,
to enable me alone to worship you.
You have many times comforted me.
Support and preserve my dear friends under their trial.
You have been pleased to take my dear sister, I trust, to yourself.
I pray you that my spirit may mingle with hers.`'
After a little pause, she remarked that long life was not desirable,
on account of the many temptations to which we are liable here:
and at another time she said, that she hoped her lamp was trimmed.

[.asterism]
'''

SARAH CRAWLEY was born at Hitchin, in Hertfordshire, in the year 1717.
Her mother, who, like herself, lived to a great age, was, I think,
the daughter of John Field, the compiler of the third, fourth,
and fifth parts of '`Piety Promoted`', and was so ancient as to remember William Penn,
in whose company she had been.
This, her daughter, came forth in the ministry when very young, and found it her concern,
in early life, to visit the meetings in different parts of Great Britain and Ireland.
After this, she travelled little for many years, having, as she said,
no concern for such engagement.
She continued, nevertheless, in the frequent exercise of her gift,
at home in her own meeting, manifesting her constant dedication,
and demonstrating the liveliness of her spirit.
During this long recess from traveling, she kept a small shop,
in the business of a confectioner, in her native town,
and had a long while for an inmate her aged mother.

At length, in the decline of life,
she apprehended herself again called forth to travel in the work of the ministry;
and she accordingly travelled into many parts of England, and once more into Ireland,
sometimes under great weakness of body, yet evidently borne up in spirit.

One of her later visits had been to London,
and at length she believed it her duty to come and reside there.
She accordingly removed into the limits of the Peel monthly meeting,
where she continued the last four years of her life.
In this new situation she was not idle, but frequently visited the meetings of Friends:
until a hurt which she received from a fall in her apartment,
was the means of confining her to her bed-chamber, and mostly to her bed,
during the remainder of her time.
She was admirably supported under this trial, and said,
that all was made up to her by the precious communion
which at seasons her spirit was favored to feel.
She several times remarked,
that her coming so late in life to London might seem strange to others,
as it often had done to herself: nevertheless,
she continued to believe she had been right in taking that step,
and said that she had not repented of it, even in her most proving seasons.

When circumstances which used to give her pleasure were mentioned to her,
she remarked that she seemed to have done with things relating to time;
and that when she was capable of thinking clearly, all her thoughts centered on eternity.
At one time she said, that her mind was particularly struck by that passage of Scripture,
"`I have refined you; but not with silver.
I have chosen you in the furnace of affliction.`"
She also remarked that she had a firm hope that all would be well with her;
for she thought she had been favored to see, as it were, the gate of heaven open;
into which, in a humble manner,
she expressed her trust that in a short time she should be admitted.
Once, also, when a Friend, returning from the Peel meeting,
not far from which Sarah`'s lodging was situated, called on her in her chamber,
she remarked, that although she was then prevented from meeting with her friends,
she had that morning been meeting with the `'General assembly and
church of the first born which are written in heaven.`'

She was a woman of a cheerful disposition,
which did not forsake her when she was finally confined for many months to her bed;
in which, nevertheless, from the nature of the injury she had received,
she was unable to take the repose of a recumbent posture; but constantly,
sleeping and waking, night and day, sat up;
having some contrivance to lean on before her, when she went to sleep.
I several times called on her in this state,
and scarcely ever left her without having been witness to her cheerful turn of mind.

She died the 5th of the Second month, 1799, aged about eighty-one,
having been a minister about sixty years.

[.asterism]
'''

MARY BASS, was the eldest daughter of Henry and Elizabeth Bass, of Ramsey,
in Huntingdonshire, and was born about the year 1775.
She was considered an exemplary young woman;
and as she was bereft of her pious mother at a very early age,
the care of a large family soon devolved on her.
Her mother was daughter of Isaac and Barbara Gray, of Hitchin;
and on the decease of Henry Bass, which took place in the year 1796,
his three daughters settled in that town.

In the year 1799,
she showed symptoms of that disease which was the means of terminating her earthly course.
It was thought to be that afflicting ailment known
by the descriptive name of water in the head.
The pain which it occasioned was at times very intense;
and did not always occur without inducing a temporary delirium.

She did not at first appear to believe that her disease was mortal,
as will further appear;
and she suffered a long train of deep bodily suffering with great resignation.

Taking leave once of a brother, she advised him to be diligent, saying,
'`I am sure there is need of it,
for it is a hard thing to have anything to do on a sick bed.
What a comfortable thing it is that I have nothing to do!
But I believe I shall get better.`'
Her brothers (for it seems more than one were present) appearing affected, she added,
'`You need not grieve, for if I die, I shall go to heaven.`'
Something similar to this she said to one of her sisters.`'
If I die, it is hid from me, and no doubt wisely so.
It is often the case.
I do not wish to be presumptuous about it; but I do not think I shall.
If I do, you have had a greater loss.`'
Here she referred to that of their parents.

After having passed a few days in comparative ease,
her pain returned with great violence: on which she remarked,
'`How trying it is to pass through the fire a second time!`' On another occasion,
being in great suffering,
she signified her apprehension that she should be soon laid low.
To an aunt she once said, '`I do not wish to be selfish;
but I think I had rather die than live.`'

She once desired a sister to be called up in the night,
for she had felt herself so much exhausted by the pain,
that she seemed to believe her end to be approaching.
When her sister arrived she addressed her thus: '`Let me kiss you,
my dear sister;`' then pausing, added, '`Can you give me up?`'
Her sister expressed her hope of submitting to the will of Providence; and Mary replied,
'`But you should do it cheerfully.`'
On First-day evening, after a day of great suffering, she said,
'`I am now only waiting the will of the Lord;`' but
a sense of her close was not yet given to her,
for after a pause she added, '`I do not know but I shall get better yet.`'

The Third-day following, she was very quiet and composed,
and she desired to have some of the Scripture read.
This had not been done for some weeks, though it had been her own daily practice,
when in health.
After this had been done, she remarked that it seemed to her like First-day.
'`Indeed,`' said she, '`it has been to me a Sabbath, a holy day of rest.`'
In the evening she said, '`When the pain has been sometimes so great,
as to make me sweat to a great degree, then I have thought my sufferings, though great,
were nothing in comparison of sweating great drops of blood, through agony of mind.`'

At another time she observed one of her brothers to weep, and said to him, '`Don`'t grieve.`'
Her brother then expressed his sympathy,
and his hope that she might be favored with a little ease: to which she answered,
'`It is very kind.
If it had not been for the presence of the Lord, my sufferings would have been tenfold;
but he has been exceedingly good to me all through my illness.`'

Once, on a First-day in the afternoon, after having been very ill,
she broke forth in supplication, saying, '`O Lord God Almighty,
permit me this once to supplicate your holy name on behalf of my dear brothers and sisters,
both present and absent.
Be pleased, O Lord, to multiply their blessings.
Feed them with food convenient for them.
Make them as pillars in your house.
And my dear sister, be pleased to sanctify her afflictions unto her.
Grant her patience, O Lord.
You can do all things according to your might.
And if it be your will, receive my soul,
and grant me an easy passage into your heavenly kingdom.
You know I love to serve you above all things:
and if I have withheld anything that is right, it has not been through disobedience,
but for fear of being too forward.`'
After some time, she added,
'`I am glad I am thought worthy to be taken from the troubles to come:
for they will be great, and I hope Friends will stand fast.`'

The same evening she was assisted to get out of bed,
when she addressed several of her relations, who were standing by, after this manner:
'`You cannot think how easy this illness has been made to me.
The Lord has been so good to me, that I have not even thought the time long.
I can`'t see my way clear to heaven yet; but I do not know that anything is in my way.`'
A relation remarking that she hoped there was nothing in the way but time, Mary replied,
'`I hope not.
If there was, I hope the Lord would make it manifest, for he has been so kind to me.`'
After sitting awhile in great composure of mind, she said, '`The land mourns,
because of great bloodshed.
Lord, forgive them, for they know not what they do.`'

About this time one of her brothers, not having been lately present, came to see her:
with which visit, though then she was very ill, she appeared to be much pleased;
and after expressing her gladness, she advised him not to look at others for example,
but to follow the dictates +++[+++of truth]
in his own mind.
A wish for her recovery having been mentioned by one of the company, she replied,
'`The Lord is as able to raise me up now as at the beginning, if it be his will.
If not, I hope he will soon release me.`'

She continued about three weeks after this, in great quietness of mind,
and several times signified she was only waiting to be released;
being perfectly resigned to the will of Providence,
which ever way her disorder might terminate.

Thus, being favored to close her days in great peace, on the 20th of the Twelfth month,
1799, and about the twenty-fourth year of her age, she expired without a sigh.

[.asterism]
'''

SAMUEL EMLEN, of Philadelphia,
a frequent and much-loved visitor of Friends in this country, who died in that,
his native city, the 30th of the Twelfth month, 1799,
was the descendant of one of the early settlers in Pennsylvania,
and born the 15th of the Third month,
1729-30. He had the advantage of probably the best
education which Philadelphia then afforded;
and his own genius, aided by a memory uncommonly retentive,
enabled him to improve himself in learning as he advanced in life.
He served a mercantile apprenticeship with James
Pemberton (also mentioned in the present volume),
but never himself engaged in trade.
He was religiously disposed from early youth; and, having the prospect of competency,
he devoted his maturer age, and indeed his whole life,
to pursuits and services of a religious nature.

In the year 1756, Samuel Fothergill, Catharine Peyton,
and Mary Peisley (of whom there is some account in this volume),
were returning from religious visits in North America.
Samuel Emlen bore them company in a vessel bound to Dublin; and,
falling in with Abraham Farrington, a ministering friend also from America,
became his companion in a religious visit to friends in some parts of Ireland.
On this journey, at a meeting at Carlow, Samuel Emlen first appeared as a minister.
He passed the winter chiefly at Warrington with his friend Samuel Fothergill,
a man well adapted to please and instruct him; and,
after continuing some years in England,
he embarked for South Carolina with John Storer of Nottingham,
and accompanied him in his religious visit to that province,
and some other southern parts of North America.

In 1764 he married Elizabeth Mode of Philadelphia,
and as the health of both himself and his wife was infirm, they came to England,
and resided some years at Bristol, in order to be near the Hot well.
Here he had two children born, but his wife was taken from him,
departing in the First month, 1767.
He then returned to Philadelphia; but came again to England the next year,
to conduct to America his two sons.

In 1772 he came again to England on a religious visit.
He crossed the sea with John Woolman.
They arrived in time for the yearly meeting, and Samuel, shortly after,
had to attend the burial of his beloved friend Samuel Fothergill; whom,
in his last journey to England,
he had joined in visiting the families of one or two monthly meetings in London.
In the course of his visit he went to Holland, with William Hunt and Thomas Thornborough,
two American friends, also traveling on religious service.
It is remarkable that his friend and ship-mate John Woolman,
and this his later companion, William Hunt,
were both removed by the small-pox in England in this year:
as his former companion Abraham Farrington had been, but not by that disorder, in 1758.
Of the two former, there are accounts in the eighth part or volume of Piety Promoted;
and of the latter there is one in the Collection
of Testimonies concerning public friends deceased,
published in 1760.
Samuel Emlen, whose talent did not appear to lie so much in general traveling,
as in visiting friends in cities,
and places where he could readily go from house to house, returned to Philadelphia,
if my information be correct, in the following year.

In the year 1784 he came to England again on a religious visit,
in company with four other ministering friends, namely, Thomas Ross, George Dillwyn,
Rebecca Jones, and Mehetabel Jenkins.
They landed in time for the yearly meeting, and soon after,
Samuel Emlen went with George Dillwyn, and John Kendall, of Colchester,
to visit the few friends then resident in Holland.
Previously to his departure from America, he had entered again into the married state,
with a friend of Philadelphia; and he returned to his family in the autumn of 1785.

His next visit to England was in 1792.
He then crossed the Atlantic with Sarah Harrison,
a ministering friend coming to visit England,
and Mary Ridgway and Jane Watson of Ireland, returning from a like visit in America.
He returned, in 1794, with John Wigham and Martha Routh,
two friends going on religious visits from this country, and landed at Boston.

He was a man of a feeble frame of body,
and was afflicted with a disorder which rendered traveling peculiarly harassing to him;
and which probably was some means of preventing him from coming
to London in his seventh and last visit to these nations.
He arrived at Liverpool in the summer of 1796,
accompanied by Deborah Darby and Rebecca Young,
on their return from visiting friends in America; and by William Savery,
a fellow-minister of his own monthly meeting,
that for the Northern District of Philadelphia.
The services of Samuel Emlen were chiefly confined to Lancashire,
and some parts of Ireland.
His absence from home was about eighteen months,
an interval shorter than is often taken up in these religious services;
but during this absence he became again a widower.

Samuel Emlen passed so much of his time in some parts of England,
that we have little need of other information, than that which recollection affords,
to describe his character; and, generally speaking, it is by comparing the life,
and the approach of death; the path which has been trodden,
and the prospects which open on its close;
that instruction and encouragement are derived from narratives like these.
To say little of his cheerful temper, and the store of his memory,
which made his company pleasant to those who loved
to contemplate religion under its brighter forms;
and of course especially so to well-disposed young people,
in whose society he took great delight, I think I may venture to say,
he was a man fearing God, and hating covetousness.
His mind, though often at liberty for lively conversation on outward matters,
seemed to be constantly revolving on the more important
things which pertain to life and salvation.
Thus, few were so ready with a word in season on religious topics;
particularly in addressing with pertinence the various persons to whom
from time to time he thought himself required to minister.

He was well read in the Scriptures,
and eminently versed in some of the prophetical writings: and in later life,
when by a residence with him under the same roof,
I had the most opportunity of observing him,
he used to have the Bible read to him after he had retired for rest.
In his public service he was very fervent,
particularly in endeavoring to arouse the careless professors of a religion which does
not allow all the indulgences which they seem to think themselves at liberty to use.
With all this, and crowning all this, he was a humble man.
He ascribed all he had, and all he was, to the favor of his Lord.
I was considerably struck, once when he was sick in London, to hear him say,
'`Thanks be to the Lord, for the hope I have in his mercy.`'
It then seemed a less strong expression of confidence than, probably,
through inexperience,
I should have expected from a man whose whole life seemed devoted to God.
I have since lived to see that it contained everything
which the self-abased Christian can desire:
and such a Christian was he.

His constitution, as has been hinted, was naturally infirm;
and in the latter years of his life,
had been further impaired from the frequent recurrence
of the pain to which his disorder subjected him.
In the autumn of 1798, after a long walk in a cold wind,
he was attacked by new symptoms of disease,
which his physicians supposed to be those of the gout.
His wrist was affected with violent pain, which immediately spread up his arm,
and seemed to affect the region of the heart.
Such attacks seldom lasted more than fifteen or twenty minutes;
and seldom confined him to the house more than two or three hours,
until within a short time before his decease.

In the Eighth month, the following year, while residing with his son at Westhill,
near Burlington, on account of the prevalence of the yellow fever in Philadelphia,
he thought himself sensible of a slight paralytic affection;
but on his return to the city in the Tenth month, his health seemed to be improved,
and he experienced little interruption in his accustomed employment
of calling on his friends and of visiting the abodes of affliction.
This latter was a practice to which a considerable
portion of his time had long been devoted.
He considered it a religious duty, and it was congenial to his benevolence.
In the Twelfth month his gouty spasms returned with increased violence,
and on the 15th of that month, being at meeting, and having delivered a lively testimony,
he found himself ill; and leaning, through weakness,
on the rail of the ministers`' gallery,
he repeated pathetically those well-known lines of Addison,

[verse]
____
"`My life, if you preserve my life,
Your sacrifice shall be;
And death, if death should be my doom,
Shall join my soul to thee.`"
____

On this, the meeting was broken up; he was assisted to go into an adjoining dwelling;
and, after he recovered a little, was conveyed home;
but the next morning he was well enough to attend
the usual meeting of ministers and elders,
and his own meeting on Third-day.
In this last,
he was large in testimony to the excellency of that faith which had been his shield:
commenting on the text, "`This is the victory that overcomes the world,
even our faith.`"

In the latter part of this week, his spasms returned so frequently,
that his physician urged him to confine himself to his house; and he went out no more.
But during the succeeding week, he received the visits of his friends in his parlor;
and conversed cheerfully with them, and with his family.
Once, while two of his fellow-laborers in the ministry were with him,
he was attacked by a fit of acute pain:
during the extremity of which he manifested the trust of his mind, by saying,
'`I have a comfortable hope that my spirit will be reposed in the bosom of Jesus:
'`and when his suffering abated, he addressed them in a very lively manner,
with this language, '`Remember, "`You have not chosen me; but I have chosen you,
and ordained you, that you should go, and bring forth fruit,
and that your fruit should remain.`"`' When he was alluding
to the care taken of him by those about him,
he said, '`I deem their sympathy and affectionate attendance on me,
as a blessing from heaven; for which God will bless them.`'

During his wakeful hours, the attributes of the Almighty were almost his perpetual theme.
He frequently acknowledged the rich consolation with which he was favored;
and he often repeated these words:
"`Their sins and their iniquities will I remember no more;
and I will cast all their sins behind my back.`"
At one time he exclaimed, '`You shall have a song, as in the night,
when a holy solemnity is kept: and gladness of heart, as when one goes with a pipe,
to come in to the mountain of the Lord.
Oh, the tears of holy joy, which flow down my cheeks!
Sing praises, high praises to my God.
I feel nothing in my way.
Although my conduct through life has not been in
every respect as guarded as it might have been;
yet the main bent of my mind has been to serve you, O God: who are glorious in holiness,
and fearful in praises.
I am sure I have loved godliness and hated iniquity.`'

The day before his decease was the only one in which he was confined to his chamber.
He was on that day visited by several Friends, with whom he still conversed pleasantly.
One of them remarked, that the frame of his mind seemed as serene and peaceful,
as could be conceived of a spirit on the verge of a happy immortality.
At the accustomed time he went to bed easier than usual;
but he was awakened before midnight by a violent return of pain;
and when the common means of alleviation had been unsuccessfully tried,
he desired that nothing more might be done: saying, '`All I want is heaven.
Lord, receive my spirit.`'
He requested those about him to pray for his preservation in patience, himself adding,
'`My pain is great.
My God, grant me patience: humble, depending patience.`'
Presently afterwards he repeated this passage: "`Call upon me in the day of trouble.
I will deliver you; and you shall glorify me.`"
Then with great fervency he said a considerable part of that called the Lord`'s prayer,
subjoining, '`Oh, how precious a thing it is,
to feel the spirit itself bearing "`witness with our spirits that we are his.`"`'

Soon after this he said, '`Oh, the soul is an awful thing.
I feel it so.
You who hear me, mind.
It is an awful thing to die.
The invisible world,
how awful!`' As he was apprehensive of the near approach of dissolution,
he entreated that nothing might be done to him but what he might request, '`that my mind,`'
said he,
`'may not be diverted that my whole mind may be centered
in aspirations to the throne of grace.`'
About three o`'clock in the morning, which was the 30th, he inquired the time;
and when he was told it, he said '`The conflict will be over before five.`'
Shortly after, he prayed for deliverance, saying, Almighty Father, come quickly,
if it be your blessed will, and receive my spirit.`'

He then lay quiet a while, and seemed released; but,
as if he felt again the clog of humanity, he said, in a low voice,
'`I thought I was gone;`' adding,
'`Lord Jesus receive my spirit.`"`' These worthy words
were the last which this Christian uttered,
and about half-past four, he gave up the spirit.

[.asterism]
'''

HANNAH WILSON, a Friend, who attained to an advanced period in life, and who appears,
from the testimony of her monthly meeting, to have been green in old age,
was born at Simgill, in Grayrig, Westmoreland, the 20th of the Seventh month, 1717.
Her parents were John and Margaret Blamier,
who are said to have given her a religious education.
Being favored when young with the visitation of divine love,
and receiving and adhering to it, she found it a stay to her mind,
and the means of preservation from the dangers incident to youth.
She was frequent in seeking for seasons of retirement, and solitary places,
wherein to wait upon the Lord for the renewal of her strength.
Thus, in her conversation and conduct, she became circumspect herself,
and a good example to others.

About the fortieth year of her age,
and a few years after her marriage with George Wilson of High Wray,
near Hawkshead in Lancashire, she came forth in public testimony;
to the comfort of her friends,
who judged her ministry to flow from the fresh influence of Divine Life.
In this service, she visited some of the counties near that of her birth;
and was esteemed to be well qualified in the useful,
but delicate employment of religious visits to families.
For she was clothed with the spirit of love,
by which means she had much place in the minds of those,
who seemed to dwell at a distance from due subjection of conduct.
She was a very diligent attender of religious meetings,
even when suffering under much weakness of body; and often,
when she came to them with considerable difficulty, she had to minister,
in a lively manner, for the encouragement of others,
to wait steadily and patiently for the help of the Lord: and He,
who had been her morning light, became evidently and remarkably her evening song.

During a long and painful illness, she was favored with much peace of mind;
and at various times said, with clearness and animation,
'`It is sealed to my mind that the day`'s work is done;
and when this painful conflict is over, there is a place of happiness prepared for me.
Lord Jesus come.
Your servant is ready.`'
A few hours only before her departure, she exclaimed with an audible voice,
'`Thanksgiving and glory!`'

She departed the 7th of the Third month, 1800, in remarkable stillness,
having been sensible to the last.

[.asterism]
'''

BENJAMIN KIDD.
Those who have endeavored to travel on, in the path which leads to the heavenly Canaan,
the region of rest, have more or less, at times, found it beset with difficulties;
notwithstanding its just and sole claim to the title of a way of pleasantness,
and a path of peace.
They have in a degree partaken of the experience, "`Without are fightings,
within are fears.`"
To such,
it is pleasant to see these difficulties all surmounted at the close of a long life,
through the love of the Redeemer: who, says the writer to the Hebrews,
is a high priest touched with a feeling of our infirmities.

Thus closed, at the age of seventy-five, the life of Benjamin Kidd, of Godalming.
He was a man of a meek and quiet spirit, humane and charitable,
and conscientiously upright in his dealings among men;
and he was enabled to assert in the decline of life, that his care had been great,
that he might do nothing to offend his God.`'

He was an acceptable minister, but was not engaged to travel much,
or to a great distance; yet he once visited, namely, in 1785, the meetings of London;
and also travelled into some counties westward of his habitation.

But, though his conduct was exemplary,
and seemed to hold out to others an invitation to follow him, as he followed Christ; yet,
during his last and long illness, he was at times assailed with doubts,
under the apparent desertion, or withdrawing of that support, that divine good,
which his soul loved, and longed for above all things.
But this solace was again mercifully extended; his doubts were removed; and,
as he told a near relation, '`a sweet assurance was granted him,
of an admission into eternal rest.`'
He added,
that '`he never before had had so bright a prospect;`' and he enjoined her not to grieve,
'`for,`' said he, '`it will be well with me.`'
After this he spoke but little that could be understood;
though he frequently appeared to be engaged in prayer to be released;
yet that he might be enabled patiently to wait the Lord`'s time.

He departed the 15th of the Third month, 1800, having been forty-three years a minister.

[.asterism]
'''

SARAH BLAND, of Norwich, was the daughter of Francis and Mary Lawrence of that place,
and born the 27th of the Fifth month, 1732.
The testimony given by the monthly meeting of Norwich,
imports that she was early visited by the power of truth;
though her youthful inclinations induced her to deviate, in some degree,
from the narrow path, in which its followers find it their safety, as well as duty,
to walk.
But it was at length her happy experience to know her unregenerate will subdued; and,
having passed through various exercises, and baptisms in spirit,
she became able to testify to others what her own eyes had seen,
and her hands had handled;
and received a gift in the ministry about the twenty-second year of her age.

This account which I am now about to prepare,
will probably differ in two respects from the greater
part of those which compose this volume.
Of dying expressions, properly so called, it will contain but few;
and as for a long series of years I was acquainted with Sarah Bland,
and knew something of her worth,
I may take the liberty of deviating the more from the province of compiler,
and of speaking from knowledge.
Her first husband was my maternal uncle; her second, my friend from my childhood.

She was married in or about the year 1755, to Samuel Gurney, of Norwich,
son of Joseph Gurney, of whom there is an account in the Collection of Testimonies,
published in 1760.
To him she was a faithful companion during about fifteen years, which they lived together.
Previous to their marriage, a paralytic disease,
which afterwards increased so as to render him incapable of moving any limb,
had begun to affect him; but when at length it had attained its extreme of disability,
his exemplary patience made his company instructive;
and his knowledge and good humor rendered it pleasant, even to the active and the young.
He departed this course of patient suffering in the early part of the year 1770.

In 1775, she married Thomas Bland, of Norwich,
with whom she passed the remaining part of her life, except occasional journeys;
one of which, in the year 1786, was a visit to Friends in Lincolnshire,
and several counties, as far as Westmoreland,
with the concurrence of her monthly meeting.
She was also concerned to visit some meetings in
the counties bordering on that of her residence;
but her travels in the work of the ministry were not extensive.

A general view of her religious life may be had from a paper,
in the form of an address to the Lord, in acknowledgement of his mercies,
which she wrote about the year 1788.
A part of it is as follows:

[.embedded-content-document.paper]
--

How has mine heart been led to meditate in your law,
and to adore your boundless mercies towards me, from my early infancy to this day!
Your hand, which fashioned me, has pointed out my path;
and in unutterable condescension have you, as a tender father,
checked me when straying from it; and, like a shepherd carrying his lambs in his arms,
brought me back!
Oh! adorable mercy! let me never forget your kindness in my youth.
And when past the days of childhood and of youth, how bountifully did you provide for me,
granting me not only the dew of heaven, but the fatness of the earth! a south land,
and springs of water!
And when, in your wisdom, you have seen good to dispense the bitter cups, the wormwood,
and the gall, your hand bore up my head; yes, your right hand was my support.
You made my bed in my afflictions, and gave me a song of praise in my troubles.

--

She was in some respects of a tender constitution; and as she advanced in age,
had frequent interruptions of health,
which prevented her from the usual engagements of social life,
and from the constant attendance of religious meetings.
On one of these occasions,
at a date subsequent to that of the paper from which the foregoing thanksgiving is extracted,
she committed to writing a memorandum of some further retrospections and meditations,
of which the following is a specimen:

'`Having, from lack of health,
had much leisure to look back and trace the footsteps of my life,
from the early visitations of divine love to my poor soul unto the present day,
my mind has been often bowed under a humble sense of the great mercy,
and unutterable kindness of Providence, in granting his protecting and preserving grace.
I feel at this time, as at many others,
an ardent desire that I may experience the same near to me,
through the remaining days of my life; and be permitted, at the solemn close,
to die the death of the righteous, that my last end may be like theirs.`'

These two extracts were inserted in the testimony
issued by the monthly meeting respecting her;
but she had added to the latter,
some hints of her experience on the subject of those written
memorials which the yearly meeting annually receives,
and in some degree requires, respecting deceased ministers.
'`My mind,`' says she, '`has been often impressed, on hearing the testimonies read,
of several ministering friends deceased; and I have felt,
that whenever it shall please Him in whose hand is the breath of all the living,
to call me from this field of painful labor,
if then my friends have ground for a hope that I have kept the true and living faith,
and unity with my brethren, it is all I desire,
and should rather nothing more might be said:
being sensible it is through the abounding mercy of the Most High, we are preserved.`'

The foregoing extracts may serve to show the tenor of her life,
and that humility was a principal ingredient in her character:
consonant to which disposition I believe it may be remarked,
that in the exercise of her talent as a minister,
she was remarkable for being often engaged in prayer.
She lived to the age of sixty-eight, and departed in peace in the year 1800.
Her last address to some of her relations was finished with these words:
'`You see how a Christian can die; in hope, and humble confidence in her God.`'
