== Chapter 8

[.chapter-synopsis]
* Jacob Bell
* Hannah Bowly
* Hannah Hall
* Job Thomas
* Mary Stansfield
* Thomas Fayle
* Abigail Fayle
* Lucy Barton

JACOB BELL was born the 17th of the Fourth month, 1737, Old Style, in London;
and departed at Plaistow, in Essex, the 19th of the Twelfth month, 1806.
His parents were Jacob and Margaret Bell, of London.
He resided the chief part of his life in the city of London, afterwards in Wapping,
then for a short time at Ilford in Essex, and lastly at Plaistow.

According to his own account,
his mind was sweetly impressed with the love of God at an early age;
but not sufficiently abiding under its holy influence,
he too much yielded to his natural inclinations, particularly in vanity of dress;
though in this, it is probable, his subsequent humility, and the consciousness of motive,
overrated his juvenile vanity.
Nevertheless, to continue his own relation, the Almighty so followed him,
by the Spirit of his Son, Christ Jesus, that he was preserved from gross evils;
and at length, by means of some close trials, he was brought to serious reflection,
and witnessed "`repentance to salvation not to be repented of.`"

He married, in 1771, Sarah, daughter of James and Anna Sheppard, of Wapping;
and of ten children who were born from this marriage, four only survived their father:
so that he was no stranger to that great domestic affliction,
which arises from being bereft of children.
Of one of these, an account is given in order of date in the present volume.

His first appearance in public testimony was in the year 1774,
when he was about thirty-seven years of age.
This engagement was not only entered on, but continued in,
very much in a cross to his own will, and at first with great difficulty.
Through life he was a man that avoided public notice; yet,
persevering steadily through the difficulties incident to his peculiar turn of mind,
and careful to endeavor after due evidence of the requiring,
he became an acceptable and lively minister.

At different times during the latter part of his life,
in which he had laid aside the engagements of trade,
he visited with certificate a great part of the meetings of friends in Great Britain,
with the Isles of Wight, Guernsey, and Jersey;
and also sometimes appointed meetings among persons of other religious professions.
His last journey of this kind was entered on,
under the pressure of recent afflictions from the loss of children:
one of them the youth already hinted at.
He was then in his sixty-ninth year;
and it fell to my lot to be a witness to his conflict; when, on one hand,
life was fast ebbing from a beloved and hopeful son; and, on the other,
the time for setting out on his mission was fast approaching.
Death, that death I trust which is the entrance to life,
even the death of the righteous-death decided the question:
he followed the remains of his son to the grave, and as it were,
consecrated his sorrows in the service of his Lord.
When he came back from this journey, which was to Guernsey, Jersey, etc.,
and returned his certificate to the monthly meeting, he bore his testimony,
in much tenderness of spirit, to the goodness of the Lord,
in sustaining him through this engagement: peculiarly arduous to him at that time.

He was a man humble in spirit, and a great lover of retirement,
very diligent and exemplary in the attendance of religious meetings,
and careful over his own family.

The state of his mind in the near prospect of his approaching dissolution,
may appear from a passage in some notes of his, dated a few weeks before his departure,
and left in his own handwriting.
After remarking that he had great consolation in looking back,
having been preserved solely by the arm of Divine strength,
from many dangers in the progress of life, he adds, '`Thanks be to God; I trust,
through his mercy, I am yet in the road to that city, whose walls are salvation,
and whose gates are praise; and do feel, according to my measure,
that quiet and resignation under my present indisposition,
that I am made easy as to the event;
desiring that the Lord would favor with his continued protection
through the varied dispensations of his providence.
Then, I have to believe, I trust from a well-grounded hope, that all will be well.`'

[.asterism]
'''

HANNAH BOWLY was the daughter of Daniel and Sarah Bowly, of Cirencester,
in which place she was born, in the year 1763.
In the early part of her life, and as she was advancing to her twentieth year,
she seemed much inclined to reject the simple attire of a Friend;
and having about this time a visit to Bristol in prospect,
she provided herself with gayer apparel than she had been accustomed to wear.
But in Bristol her career of vanity received a check,
and her mind was favored with religious impressions,
by means of the ministry of Robert Valentine of Pennsylvania.
Her gay attire was soon laid aside,
and she became a consistent and conspicuous example in her father`'s family.
She remained at home during the lives of both her parents;
but soon after the decease of her mother and surviving parent,
she resided a while with a brother; and afterwards with a niece,
who jointly with another friend, kept a school for girls in Cirencester.
After some time, the school was given up, but she still remained on the spot, till,
on the decease of her brother, before mentioned,
(whom she tenderly and closely attended in his illness,) she at length finally settled,
for the short remainder of her life, in the habitation from which death had removed him.

Before a survey is taken of the closing days of this Friend,
it will be useful further to remark, that by nature her temper was high and inflexible.
Of the effects of Divine grace it is not, probably, for man to say which is the greatest.
His limited capacity should make him cautious in judging.
But it may possibly be said without presumption,
the redemption generally appears to have a brightness,
proportioned to the previous bondage.
Nor is this confession of what she was in her nature, derogatory to her character;
since she willingly yielded herself up to follow a meek and humble Savior,
when she perceived upon her mind the attractions of his love.
It may also convey encouragement to others,
who think they feel their own complexions and tempers,
unfavorable to the growth of that true Christian humility,
which their enlightened judgment approves and desires,
if the triumph of grace be here more fully set forth,
by the knowledge of what it had to overcome.

Hannah Bowly was taken ill on the last day of the year 1806,
with a sudden and very considerable discharge of blood;
supposed to arise from the rupture of some vessels in the lungs.
She was almost immediately confined to her bed,
which she kept for the most part during three months.
Towards, however, the latter part of this time, symptoms of amendment appeared,
and she was able to remain up some hours of each day; till at length one forenoon,
as she was preparing to sit up, another violent discharge of blood took place,
which seemed to suffocate her, and she expired.
Her decease was in her forty-fourth year, on the 21st of the Third month, 1807.

The retired state of her mind during the intervening time was very instructive;
and bespoke her reliance on the same Divine power
that had visited her in more early life.
But she was at times much tried for lack of that assurance,
for which she earnestly waited; and in attaining which, she was in mercy enabled to say,
'`I can now call God, Father.`'
It was under great depression that once she said,
'`My mind seems to partake with my body in weakness;`'
and that she repeated those awful words,
"`My God, my God, why have you forsaken me?`"'`This, '`said she,
'`was the language of the Savior;
and I suppose this deprivation is needful to complete the cup here.`'

She confessed to a relation,
that she had to regret the not having attended to some manifestations of duty.
'`These omissions,`' said she, '`have lain heavy upon me; but now they seem removed.
By resisting secret apprehended calls publicly to espouse and exalt the cause in meetings,
I have sometimes involved myself in unspeakable gloom, and incurred weakness many ways.
I might not now have been in this situation, if I had given up in simple obedience.
I may possibly recover, which if I do, and feel an impulse in the same way,
I hope I should be faithful, but never forward.
My heart seems now remarkably bound to the willing in Israel.
I hope impressions received at this time will be so indelibly fixed,
as to produce submission to any service that may be pointed out as duty,
should my life be lengthened; for which I have no desire,
but to evince myself more zealously bound, in heart and mind,
with those who are pursuing the right way.
But I know not how far I might withstand the besetments, snares, and trials of time.
I believe I should have as much need of the prayers of my friends in life, as in death.
Perhaps some may think I am taken away because more
enveloped in the gratifications of time;
but they have not been such to me; for of late, in particular,
surrounding things have been more burdensome than pleasant.
It now affords me comfort,
that I am conscious of not intending to make a show with the addition to my income,
or spending it for self-gratification: but I designed applying it to useful purposes,
that would yield solid satisfaction.
If I were to live longer, and enjoy all the comforts of this life,
I might not be more fit to go than now.
I look back on all the accommodations of it, without any regret in leaving them.`'

At another time, she said, '`Yesterday, I anticipated, not with pleasure,
a lengthened illness; but the exertion of leaving my bed, to have it made,
in the evening, convinced me of such increased weakness,
that I need not fear a long continuance.
I am very comfortable.
How thankful I ought to be, for the sweet support I feel!
I trust death is now robbed of its terrors; but not of its awfulness.`'

Mentioning once the opportunities of speaking to several of her friends,
which she had had during her illness, she said,
'`I hope what I have expressed will not do any harm,
and have not been words without knowledge; neither have I spoken from premeditation,
but simply from fresh arisings.
If I could do anything to help those philosophers, who believe, or try to believe,
in the sufficiency of reason for the guide of conduct, I should rejoice to do it;
but such are not easily reached, even by what is uttered from dying lips:
having fortified themselves against such communications.`'
A friend present asked her whether she did not think examples of consistent
Christian conduct to be the most convincing to such sort of people.
She replied, that she believed they were.

At another time she observed, that the Holy Scriptures were an invaluable treasure.
'`They have many times,`' said she, '`afforded me great comfort,
and I regret not having read them more.
What beautiful, instructive passages they contain!
I once had a sweet opening, that was given me, I thought,
chiefly for encouraging instruction to myself; and that,
if I yielded entire obedience to divine requirings,
swords should be beaten into plough-shares, and spears into pruning-hooks:
those strong powers and dispositions of the mind, comparable to hurtful weapons,
instead of being destructive, should be so sanctified,
as to be turned into usefulness in the vineyard.`'

As her strength decreased, she was favored with great tranquillity of mind.
Several times she said, '`I feel peaceful poverty.`'
At other times she abounded, by the prevalence of a lively faith,
which gave her ability to say, '`I feel unmoved confidence, supporting me,
and opening my prospects to brighter scenes.`'
Once she added, '`I believe,
however gloomy and discouraging the appearance of
things relating to the state of our Society may be,
that some will see brighter days;
and that its testimonies will continue to be maintained by some, in their purity:
and a succession of those +++[+++will be]
prepared, who will support the ministry.
I think the solicitude I now feel on account of others,
is not so much on account of individuals, near connections, or families;
but that the real right may increase and prevail among Friends generally: true, right,
ancient simplicity.`'

She one night asked a Friend, who was sitting up with her,
whether she thought that there would be, in a future state, a knowledge of each other;
and remarked that some were of that opinion.
But Hannah confessed the question to be above her comprehension.
She said there was something pleasing and gratifying in it;
yet that she thought looking that way was looking short
of one great object of eternal enjoyment and adoration.
She thought that not to be the best aspiration of soul which desired any
felicity but that which proceeds from the Divine presence.

Once, when very low in body, she was also much contrited in mind, and said,
'`I feel as unworthy to approach the throne of grace
as it is possible for any poor mortal to feel.
So abased am I to dust and ashes, +++[+++that]
the reduction, the nothingness, I am brought into, is not to be described or conceived.
It may partly be occasioned by the connection of the mind with the body.
It is very trying and proving to bear:
but may contribute to the work of preparation for a triumphant end.
Though I have no cause to presume mine will be evidently so,
yet I am favored with a consoling, supporting hope, that, through adorable mercy,
I shall sing of victory hereafter.`'

She mentioned one day the saying of Richard Hubberthorne,^
footnote:[R. Hubberthorne died in Newgate in the year 1662, where he had been committed,
after some personal abuse, by a persecuting alderman,
in consequence of being taken up at the Bull-and-Mouth meeting.
The prison was then crowded with Friends,
and the noisome confinement probably occasioned not only this Friend`'s death,
but that of his fellow prisoner, Edward Burrough.
See Sewell`'s History Anno.
1662.]
one of our early Friends, in his illness: '`Out of this straitness, I must go;
for I am wound up into largeness; and am to be lifted up on high, far above all.`'
'`With humble admiration,`' said she, '`for all boasting is excluded,
it has seemed to me that I can now adopt this expression.`'

The last instance which it may be necessary to give of her mind being fixed on the Lord,
may be that of her adopting the words of a still more ancient servant, in his day;
and whose writings the spiritual traveller still feels fraught with consolation,
when permitted not merely to read, but to feel their energy.
Her mind seemed tenderly affected with the incomes of the love of her God,
and she said that she had been thinking of some comfortable expressions of David.
Then in a sweet manner she repeated several.
"`Bless the Lord, O my soul, and forget not all his benefits:
who forgives all your iniquities, who heals all your diseases,
who redeems your life from destruction,
who crowns you with lovingkindness and tender mercies.`"

[.asterism]
'''

HANNAH HALL.--It often happens, and it is cause of reverent thankfulness that it is so,
that tedious sickness is allowed to be the means
of refinement and preparation for the great change.
Happy also is it for such as have "`their loins girded,
and their lamps burning,`" and are ready at a short notice to meet the bridegroom.
This seems to have been the case of Hannah Hall, of Little Broughton, near Cockermouth,
in Cumberland.

She was the daughter of William and Rachel Wigham, of Cornwood, in Northumberland,
and was born in the year 1747.
A few years after her marriage with John Hall, of Broughton,
and about the twenty-seventh year of her age,
she came forth in a public testimony in meetings,
and her services were acceptable to Friends.

She did not travel much, but had a large family to watch over,
which she brought up in an exemplary manner,
and was herself a pattern of economy and industry.
Nevertheless, in 1783, she visited meetings in Lancashire and Cheshire,
in company with her mother, a valuable minister; and about ten years afterwards,
paid a religious visit, in company with some other Friends,
to the inhabitants of the Isle of Man.
In this visit her short and lively offerings seemed often
to open the way to larger communications of her companions.
In 1801, she visited the meetings in Scotland;
and afterward the families in the greatest part of her own monthly meeting of Pardshaw:
where she was herself a diligent attender of meetings,
and esteemed as a woman of a meek and quiet spirit.

She often proclaimed the uncertainty of life,
and was strenuous in exhorting all to make timely
preparation for their solemn and final change;
and in both these respects was herself an example, for she was removed,
at about the age of sixty, by a violent disorder, in twenty-four hours.
She expressed an unshaken confidence that a place of rest would be her allotment,
when the pains and conflicts of time should pass away.
Her decease was on the 29th of the Fourth month, 1807, and her last moments,
so far as an indistinct articulation could be understood,
were employed in solemn supplication.

[.asterism]
'''

JOB THOMAS.
In adding to the accounts, prepared for this volume,
of the happy departure of many faithful servants of the Lord,
that of the triumphant conclusion of Job Thomas,
I feel an inclination to avow that I consider it as no light employment.
He appears to have been favored with a more immediate manifestation
of the glorious state which was about to crown his suffering life,
than is commonly allowed to spirits yet clothed with mortality.
The veil seemed to be withdrawn: the beatific vision to be displayed.
He spoke of what he saw, and was on the point of possessing;
and if it be lawful to publish an account of condescension so transcendent,
of mysteries so sacred, of glories so infinite,
I can hardly believe that admiration is the only
feeling that should be excited by the perusal.
There is a holy awe, a reverential dread, that seems to be due from the awakened mind,
on being thus, as it were, a witness of a frail mortal putting on a glorious immortality.
And when we almost see the omnipotent and righteous
Judge dispensing his reward with his own holy hand;
and placing on the Christian the crown of righteousness;
surely deep self-abasement should possess the creature,
and the heart of every reader should bow before him,
who holds these infinite and inestimable treasures at his will: and,
as a part of that holy will, has made known that,
through the redeeming virtue of his beloved Son,
they are accessible to the broken and contrite spirit.

But before we survey the conclusion, let us advert to the path, through which, this,
our departed Friend, was led to blessedness, so far as it is known.

His youth, probably,
had been tinctured with some of the vanities incident to that stage of life:
for he has been frequently heard to lament that he had not
been more obedient to the Lord`'s requirings in early life.
But he was scarcely known to his surviving friends in any other capacity
than that of a diligent attender of meetings for worship and discipline,
an approved minister, sound in doctrine,
and holding fast without wavering the profession of the Christian faith.
Gospel love enlarged his heart,
and he had a universal desire for the salvation of his fellow creatures.
He was bold in delivering plain truths, and in the Welch, his native tongue,
he was persuasive, clear, and fluent.
His religious visits, however, were much confined to Wales;
the meetings of Friends in which principality he visited several times; and,
in the compass of the monthly meeting to which he belonged,
he frequently had more public meetings with those of other societies.

He once attended, as a representative, the Yearly Meeting in London;
and when in this great city, his heart yearned towards his numerous countrymen,
dispersed within its circuit.
He wished to have a meeting with them, but as he had not, on leaving home,
asked for a certificate of his monthly meeting`'s
approbation of his then traveling in the ministry,
it was judged irregular to convene one:
and his disability of body not long after supervening,
an opportunity did not again occur.

In the estimation of the world he would have been accounted a poor man;
and his habitation was certainly mean.
It was a small farm house in Caermathenshire: such as, on this side the Severn,
would be called a cottage; retired and sequestered,
but not far distant from the public road;
and nearly midway between Llandovery and Llandilo.
Yet here he was hospitable, and gladly received his friends;
of which hospitality I can testify from experience.
His means of support arose not only from the trade of a shoemaker,
but from the occupancy of a small farm.

About the year 1797, near his own dwelling, he was thrown from a young horse,
and received so great an injury on the spine,
as at length to occasion the deprivation of voluntary motion in every limb.
His head, only, remained subject to his will.
This he could still turn,
while he was beholden to personal assistance for his removal from his bed to his chair,
for any slight alteration of position in it, and in short,
for almost every common function of the body: the free performance of which,
though it is scarcely observed by the healthy and vigorous,
constitutes much of the comfort of animal life.
But his body, thus deprived of motion, was still sensible to pain: and much, very much,
of this positive affliction was added to the negative one of total helplessness.
He used to be fastened, rather than to sit, in a chair,
and his body and legs were nearly in one strait and stiff line;
with his useless arms lying before him, and his bowels,
or some other of the interior parts, often grievously affected with violent pain:
to which his worn and pallid countenance gave ample testimony.
Yet his mind seems to have been unimpaired.
He received much comfort from the visits of his friends,
especially of such as he esteemed alive in the truth;
he kept up religious meetings in his house, and often labored in them in doctrine,
for the edification of those who were assembled with him; and he dictated some epistles.

It was my lot to see him three times during this trying confinement.
The first time was in 1802, in company with several others,
and among the rest a ministering Friend, on her way to embark at Milford,
for a religious visit in Ireland.
As I remember, he was at that time very lively in his spirit,
and imparted much encouragement to the traveling minister;
but I am not quite sure whether it was at this,
or at a succeeding visit that I was particularly struck, if not edified,
with observing how steadfastly his mind seemed to be anchored in Christ;
and hearing how clearly and fully he spoke of that confidence.

Thus suffering, and thus supported, he continued about ten years.
At length, towards the beginning of the Eighth month, 1807,
his symptoms of disease increased, and on the 15th of that month,
being considerably more indisposed in bodily health,
he called his wife and son to his bedside; and, with a pleasant countenance,
spoke to them, in the Welsh language, nearly as follows.

He inquired of them, whether they had anything to say to him; "`for,`" said he,
"`the blessed hours are approaching; yes;
and before this night I shall have escaped in safety,
where neither trials nor troubles shall come.
Be content, and do not grieve after me; for I am setting off to endless joy,
to praise him who has brought me patiently through the whole of my troubles,
and inexpressible afflictions.
Support me, O Lord, for these few minutes;
for I am nearly come beyond the boundary of time, to a boundless eternity.
I am now near giving you the last farewell; but take warning, and be daily on your watch,
for, in the hour you do not suspect, death, that is, the king of terrors,
will come to meet you, who will make no difference between one or the other.
But in the strength and love of Jehovah, you will not fear death;
if you seek him while he is to be found,
and serve him with a willing mind and an obedient heart;
for his paths are paths of peace, and his ways are ways of pleasantness.
O, pray continually to the Lord,
to draw your desires and affections from off earthly things,
and to establish them upon things heavenly and everlasting.

"`My hope is in the mercy of him,
who has washed me in the fountain set open for the house of David,
and the inhabitants of Jerusalem.
Not through my own merits, but through the merits of the crucified Immanuel,
who died for the sins of all mankind.
And you who have to remain a little after me, give the praise, the reverence,
and the honor to him; and supplicate day and night before his throne,
until you have certain knowledge that you have been
baptized with the baptism of the Holy Spirit;
which was sealed by the blood of the everlasting covenant.
Remember, it is not an outward baptism that will serve;
which is but the practicing the old shadows.
Know also, that it is not the profession of religion that will do;
but one that is pure and undefiled before God.
This will conduct you in safety to the everlasting habitations.

"`Now the time of my dissolution draws near;
for me to go to the place where I have been these two nights.
The Lord himself came to meet me; and took me with him to the height of heaven;
among myriads of his holy angels; where his saints were before him,
and will be forever.

"`Behold, now I give up the spirit: and lo! my comely companions,
coming to hold my head above the waves of Jordan.
Behold! the gates of heaven open,
and the Lord himself with arms stretched out to receive me to his mercy.
I hope that you, who are behind will follow me there.
Success to the gospel from sea to sea, and from the river to the end of the earth:
also to my dear brethren;
that they may persevere in their faith to the end of their days,
and then their rest will be with the Lamb, where no pain or affliction will come.
Behold, the blessed time is come, for me to depart in peace with every one,
with good desires for every one, and forgiving every one.
Receive my last farewell, and the Lord bless you with the blessings of Mount Zion.`"

Having uttered these expressions, he soon quietly breathed his last.
The end of this man was peace!

[.asterism]
'''

MARY STANSFIELD, wife of John Stansfield, of Lothersdale,
in the West Riding of Yorkshire, was daughter of John Slater, of the same place,
and grand-daughter of Mary Slater, mentioned in the Eighth part of Piety Promoted.
She was, when an infant, deprived of the benefit of a mother`'s care,
the decease of her own falling out soon after her birth;
but she grew up in stability of conduct,
so as not only to be able to attend to her father`'s domestic concerns; but as,
for a considerable time before his decease,
he was much disabled from attending to his trade, she had the management of that also:
and after she lost this surviving parent,
she continued it till her marriage with John Stansfield, also of Lothersdale.

It has been already mentioned, in this volume, in the memoir concerning Joseph Brown,
that seven persons were, with him, committed to the county jail of York Castle,
on an exchequer process for non-payment of small tithes.
One of these was John Stansfield, the husband of Mary; but the suit had been commenced,
and had been long carried on, even after her marriage, in the name of Mary Slater.
This induced her to believe that, in the long-expected conclusion of the prosecution,
her own person would be the victim of the asperity with which it was conducted;
and she endeavored to reconcile her mind to it, and to prepare for it,
by weaning an infant at the breast.
Nor was her resignation to suffer, and her preparation of mind, lost on her,
when it was determined that her husband should be the imprisoned person:
she bore the separation, and his absence, with becoming fortitude;
and was chiefly desirous that the testimony which
they believed themselves required to bear,
might not be weakened by any improper conduct on their part.

When the prosecution at length issued, as has been already related,
in distraints of the goods and property of the prisoners,
her only care seemed to be lest she should not have one good bed left,
for the accommodation of traveling Friends;
as the house had long been a free and hospitable place of entertainment for such visitors.
She was not, however, tried to so great a degree as this; and indeed,
not only during the whole of this trying business, but in other parts of her conduct,
she seems to have been a preacher of righteousness.
She was a woman much beloved,
and her decease was felt as a general loss in her neighborhood,
both by Friends and others; for her disposition to perform the duties of social life,
by rendering assistance to those who were in need of it,
was considered as fully equal to the ability which she possessed.

Having thus endeavored to be upright in her day,
she was further enabled to support the character of a pious woman,
during a long and painful illness.
In the early part of this suffering dispensation,
she committed to writing some of the feelings of her mind,
and the following brief extract is taken from that memorial:
'`Having of late felt my mind much tendered at times,
through the Lord`'s unspeakable goodness to a poor unworthy creature, I trust,
if I be removed, it will be in mercy: and from my feelings at this time,
I think I can say, The Lord`'s will be done.`'

After this, however, she passed through some deep baptisms.
She often said that her pains of body were permitted for good,
being intended for her further refinement;
and that she believed it would be well with her when her sufferings were over.
Though these were great indeed '`they were light,`' said she,
'`in comparison of those experienced by our blessed Savior; who, although without sin,
sweat as it were great drops of blood; and when athirst, and in the agonies of death,
had vinegar and gall offered him to drink; while I,`' she continued,
'`have everything I can take.`'

Much weighty advice did she impart, particularly to her husband and children,
whom she often exhorted to trust in the Lord; '`and then,`' said she,
'`you will have nothing to fear.`'
She reminded them of the Psalmist`'s language, "`I have been young, and now am old;
yet have I not seen the righteous forsaken, nor his seed begging bread.`"
To her husband she added, '`O, my dear, you must endeavor to look to the Lord for help;
and then, never fear, never fear.
I can say from experience he has been very good to me, even in the midst of affliction,
now as well as formerly; for I was left, having nothing but him to trust in;
and have found him a merciful helper and preserver.`'
To her mother-in-law, probably her husband`'s mother, she said,
'`I have never experienced real satisfaction or consolation
in anything short of Divine goodness.
In my greatest trials and exercises, he has comforted me the most.`'

On one occasion she said, '`Pray for me, you that can pray.
I am desirous to be released, and you all seem to hold me back.
Do not hold me.
You see I cannot live.
Pray for me, that the silver cord may be loosed.`'
Then she prayed herself with fervor.
'`O Lord, cut short your work in righteousness; yet not my will, but yours be done.
'`It is an awful thing,`' said she, '`to live, and I find it a serious thing to die;
yet can with thankfulness acknowledge, I am not afraid of it.
But this I could not obtain in my own strength.
Oh, no.
It is the unspeakable goodness of the Lord to a poor unworthy creature.`'
About a week before she died, some return of appetite occasioned, in an observer,
a hope of recovery; but Mary said, '`I much dread going into the world again.
The Lord knows it.
I had rather depart, fearing I may not be +++[+++again]
so well prepared.`'

One time she had all the children called to her,
and in a lively manner expressed her wish that they
might experience preservation from evil;
adding, that she had prayed to the Almighty on their account,
to whose care she committed them.
She said she had never desired much of this world`'s substance for them,
and that her principal concern was for the good of their immortal souls.
At another time, to her husband, she said, '`O, my dear, how have I prayed for you,
that you may be preserved from the inordinate love of the world!
Oh, this world, this world!
If not minded,
it will be apt to steal away the mind from a right relish of that which is good.
Remember that one soul is of more value than all the world.
If we have food and raiment, we ought to be therewith content.`'

A little before she died, she said, '`What a blessing it is,`'
alluding to the quiet which she enjoyed; '`and Divine goodness favors me so,
that I feel no lack of anything, either in body or mind.`'
After this she grew gradually weaker; and at the age of about forty-three,
on the 21st of the Second month, 1808, she quietly departed.

[.asterism]
'''

THOMAS FAYLE, a much esteemed Friend, of Dublin, who died in that city,
the 21st of the Fifth month, 1808, was born in the King`'s county, in 1742.
He was placed as an apprentice with a friend in Dublin,
which afterwards was his place of settlement and residence.
He was of a sober and thoughtful disposition in early life; and from his youth up,
continued to evince the effects of the preserving influence of truth.
As his years increased, he advanced in usefulness in our religious Society.
He was much concerned that its Christian discipline should be well supported;
and much engaged himself in the administration of it.
He was a man of plainness, sincerity, and firmness.
He spoke his sentiments honestly, whether in meetings for discipline or to individuals;
and he encouraged others to speak the truth, every man to his brother:
he was also many times engaged in visiting Friends in their families.

Nor was his usefulness confined to precept alone:
he acted as he recommended others to act.
He was an elder who endeavored to rule his own house well;
being very solicitous that his children might walk in the path of simplicity,
consistency, and safety.
The preservation of them was one of the objects nearest to his heart.
He encouraged the appearances of good in them;
he warned them of that which had a contrary tendency; and, when he saw it needful,
he added restraint to admonition.
Thus, by endeavoring to check every wrong thing at its beginning,
and to prevent its growth before it had gained strength, he was a blessing to his family.
This wise, provident, and one may almost say politic concern,
of a man who had at heart the preservation of youth,
remained with him almost to the last: for, not long before his departure,
in a large committee of the yearly meeting of Dublin,
he addressed the parents on the subject of their deficiency in restraining their children,
particularly in dress.
He expressed his apprehension that some parents making a plain appearance themselves,
even led their children into this deviation,
by dressing them while very young in a way conformable to the fashions of the times.

He was a constant attender of his religious meetings,
where his countenance and demeanor bespoke the humility and reverence of his mind,
and he was several times at the yearly meeting of London.
In his own dealings with other men he was upright and punctual;
and he was very desirous that Friends might not pursue
their trade so as to encumber their minds,
prevent their growth in the truth, or interfere with their religious service:
here also he was an example.

With apparently a strong constitution of body,
he had been allowed the privilege of almost uninterrupted health,
till the 15th of the Fifth month, 1808.
It was First-day; and though he then appeared to be somewhat unwell,
he attended both the meetings.
In the evening he desired the Bible might be read; and after a time of silence,
which was usual when the Scriptures had been read in his family,
he made some observations on the instructive parable of the sower.
The two following days he continued to be indisposed,
but was not so ill as to alarm his family until the next day;
and even then he walked out to a considerable distance.
But on Fifth-day he kept his bed;
the physicians seemed to have but little hope of his recovery,
and he desired to be allowed to remain quiet and undisturbed.
He spoke also of the probability that his end would be the result of his illness,
adding nearly thus: '`There seems no sting.
I never made much show; but what I did, I endeavored to do it honestly.
I have a hope to be admitted within the pearl-gates.`'

After this his strength declined rapidly; yet he did not appear to suffer much,
if any pain.
On Seventh-day he was confirmed in the opinion that he should not recover, and said,
'`I am favored with great quietness.
A short time after, in a humble, thankful frame of mind,
and deeply feeling the favor of which he was partaking, he said,
'`What a strange sight it is for me to see`' Being asked what he meant, he replied,
'`For me to be called away, and to be quite ready!`' Thus, with quick gradation,
yet gently, he sunk away; and about midnight quietly breathed his last.

[.asterism]
'''

ABIGAIL FAYLE.
Though the decease of Abigail Fayle was more than two years before that of her husband,
I am induced here to place the record of it,
that the instruction of their exemplary lives,
and the encouragement of their peaceful retreat,
may continue together to shed a salutary influence
on the mind of the traveller to the holy city.

She was the daughter of James and Susannah Malone, of the county of Carlow;
and born in the year 1745.
In her youth she was of an orderly conduct, religiously disposed, plain in her attire,
and studious to be consistent.
When she was about twenty-eight years of age,
she was married to the subject of the preceding memoir, Thomas Fayle, of Dublin.
To him she proved an affectionate and sympathizing wife.
She was not only desirous to do what she herself thought to be right,
but to encourage him to fulfill every duty to which he believed himself called:
even though it might lead him into service at a distance, and deprive her of his company
and encouragement at home.
She was also, on her part, very anxious for the preservation of their children;
solicitous to keep them out of hurtful company: and consonant with this caution,
she was also desirous to restrain them from hurtful books.
This is an insidious evil,
and probably requires in many families a more vigilant care than it obtains.
The advancing state of modern education will sometimes leave the child
to peruse writings of which the parent may have little knowledge;
but it is probable that an upright,
awakened parent will generally have discernment sufficient
to detect error and to observe a snare;
and to such it will be but a poor excuse,
that the children are deluded into sin by their ignorance and lack of vigilance.

In her domestic economy she was desirous to avoid superfluity, particularly in furniture;
and she united with her worthy husband, according to apostolic injunction,
in a readiness to entertain strangers,
especially such as were traveling in the service of Truth.
This is a kind of hospitality often repaid by the benefit accruing
to the younger branches of the hospitable family.

The health of this Friend had been in an impaired state for several years;
and in the spring of 1805, she became evidently much more indisposed,
and suffered much pain:
in which condition she earnestly desired that the Lord would grant her
patience to bear what it might be his will that she should suffer.
To one of her sons, she spoke to the following effect: '`Seek first the kingdom of heaven,
and all things will be added.
All things necessary will be added.
Do not permit the honors or profits of this world to draw
your attention from that which is alone necessary.
The riches of this world should be considered as dross and dung,
that so we may win Christ.
My pain is great.
What a long illness I have had, now nearly two years!
I believe it is for my good.
I am not murmuring.
I hope I am not murmuring at the long illness I have been favored with.
How thankful I ought to be for the many favors and blessings I have experienced!`'

On the 12th of the Fourth month she had been downstairs;
the next day she was increasingly ill; on the 14th she was manifestly declining,
and the following day she quietly departed.

[.asterism]
'''

LUCY BARTON, daughter of Benjamin and Martha Jesup, of Woodbridge, in Suffolk,
was born in the year 1781.
In very early life, her mind appeared to be favored with serious impressions,
which were considerably strengthened by a delicate state of health;
and her conduct and conversation were uniformly such
as endeared her to her friends and relations.

In the twenty-sixth year of her age she was married to Bernard Barton,
also of Woodbridge;
and during the short period which intervened between their marriage and her decease,
her mind was seriously exercised that she might attain a more solid establishment
in the Truth than is the result of mere education or tradition.
The following lines, found after her decease, among some memorandums,
are thought worthy of preservation: they were written, it is supposed,
not long before that event took place: '`This morning, being more than usually unwell,
I was led seriously to reflect on my unfitness to
exchange a mortal for an immortal state of existence.
Religion is with me, I am afraid, little more than theory;
yet I should not do justice to the great Author of it, did I not acknowledge that,
if my unrestrained inclination did more frequently yield to my judgment, I should,
in a much greater degree, possess the practical part of it.
This, I am sensible,
can alone render me an object of approbation in the sight
of Him "`who is of purer eyes than to behold iniquity.`"

'`How often do I feel compunction for not cordially embracing
those marks of Divine mercy and condescension which are,
from time to time, offered me.
Oh! may I not withstand the day of heavenly visitation to my soul! but
rather may I endure all that human nature is capable of supporting,
though it may amount to a deprivation of every earthly enjoyment,
if that sense of the Divine presence, which I am now sometimes favored to enjoy,
might from time to time be renewed.
This would fully compensate for all that could befall
me in this fading and transient state of existence.
I am so well aware of my own utter inability, in my own strength,
to resist those suggestions which are congenial to my natural inclination,
that I am often ready to despair of ever attaining
to that degree of advancement in Christian experience,
which, in some moments of deep humiliation, I have believed it was intended I should.`'

With a mind thus exercised,
it may be supposed she was in degree prepared to receive the awful summons,
though it might come unexpectedly; which was the case.
On the 20th of the Sixth month, 1808, she was confined by the birth of a daughter; and,
for two days after that event, no unfavorable symptoms appeared; but on Fifth-day,
the 23rd, she complained of considerable pain, which increased on Sixth-day morning,
but rather abated towards evening.
On Seventh-day morning,
unfavorable symptoms so much increased as greatly to alarm those about her,
and induced her relations to wish for further medical advice.
A physician was called in,
who informed them that he could give very little hope of her recovery,
or of her long continuance.

Her aunt, Mary Alexander, who had been with her through the day,
was desirous of knowing how far she was aware of her own situation,
but had avoided intimating anyhing like an apprehension of danger;
hoping a suitable opportunity might offer on her mother`'s arrival, who, with her father,
had been absent.
After Lucy had seen her parents, and her aunt was alone with her,
without any previous remark, she said, '`Aunt, does the doctor think me in danger?`'
Mary replied, '`He does, my dear, consider you in a precarious situation.`'
To this, after a solemn pause, Lucy observed, '`Well!
I have been looking at it for a day or two;
and I believe I can say I feel both faith and hope in the goodness of a merciful Redeemer;
but it has sometimes felt hard to part with Bernard and the dear baby; for,
though I have no doubt but she will be cared for, yet nothing can be quite like a mother!
But I am resigned.
I feel no fear; and humbly hope the close may be soon,
rather than remaining long in present suffering.`'

About two o`'clock on First-day morning,
she complained much of a blister which had been applied to her stomach,
and wished it might be removed.
The apothecary was sent to for his advice; but before he could get to her,
she called her aunt to her bedside, and said, '`Aunt, I would not have you be alarmed,
but I do not know but I am going.
I feel so great a release from extreme suffering to no pain at all;
and a coldness which began at my feet, and runs through my whole frame.`'
When the apothecary came,
he did not suppose this event so near as she herself apprehended;
but he was much affected to hear her speak of the prospect of so sudden a change,
with the Christian firmness which her composed remarks on the subject plainly evinced.

Her husband and mother came to her immediately;
and after a short time she requested her father might be sent for,
and also the apothecary`'s wife,
who had been a very kind assistant during her confinement.
After they both came in, and all were sitting round the bed,
she took leave of them individually,
in a manner which tendered the hearts of all present;
and then requested the child might be brought to her.
She held it in her arms, kissed it most affectionately,
and after that time took but little notice of it.
About this time she likewise spoke of some of her absent relations,
several of whom she mentioned by name, requesting her love might be presented to them;
particularly some on her husband`'s side, who were distantly situated;
and she expressed the satisfaction it would have given her to see them again.

Her brother, Alexander Jesup, had been with her the evening before;
and in the course of the night she said it would have been
pleasant to see her brother and sister Maw,
but she supposed it was now too late.
They came, however, a short time afterwards, and she was then much revived;
and remarked to her aunt that she had thought herself going,
but now it seemed hidden from her how it would terminate: adding,
'`but whichever way it may be,
to feel so relieved from suffering is cause of humble thankfulness.`'
When the physician came on First-day morning,
he was much surprised to find her so revived,
though she was thought to be still in great danger.
She dropped many interesting expressions in the course of the day,
several times repeating how great a favor it was to be freed from suffering;
and that so much ease was more than she had expected, before she departed.

While some part of the family were at dinner, she sent for her husband,
wishing to see him alone.
During her conversation with him, among other observations,
she expressed her fervent wish that, in case of her removal,
he might be enabled to support the trial with becoming resignation.
On her being afterwards asked whether she had any
directions to give respecting the infant,
she replied, with great composure, '`Then I suppose my situation is decided.`'
She was informed it was not entirely decided,
yet there was great reason to apprehend how it might terminate.
She said, '`Well; as to the dear babe,
I wish to leave it to those who know better than myself;
I believe it is not right for me to encumber my mind about it.`'
But she afterwards informed her sister,
that many of the infant`'s clothes were left unmade; and she expressed a wish,
that if her sister had the care of them, she would let them be made plain and simple.

On First-day evening she appeared fast declining;
and her mother sitting on one side of the bed, and her aunt on the other,
she put out a hand to each, and said, '`Oh! how I love you all,
you are all more near and dear to me than ever.`'
About this time she said,
'`I should like to have seen Jeremiah (meaning her
brother) but he no doubt will come to the interment.`'
She now declined so rapidly,
that it was not expected she would have continued through the night;
but she again revived, and in the course of a short time,
there appeared a wonderful amendment.
So great was the change,
that her medical attendants gave her relations some reason to hope that she might recover;
but though she continued rather improving for two days,
nature gave way to the remaining disease, and about 7 o`'clock on Fourth-day morning,
the 29th of the Sixth month, 1808,
after having entertained some expectation of being again restored to health,
she quietly and resignedly closed this life; evincing her willingness to leave all below,
by her last words, '`Providence knows best.`'
