== Preface.

In preparing the following biographical memorials,
it has been my endeavour to exhibit the power of religion on the
respective characters of those whose lives are here briefly described;
many of whom, from a personal acquaintance with them, I highly esteemed and loved.
If in some instances it may be considered, that human infirmities are but slightly,
or not at all, adverted to,
let it not be supposed that this has arisen from a desire to eulogize the dead,
or from a forgetfulness that such infirmities have existed.
It is, however, highly important to us who survive, that we should not,
from the remembrance of these,
be less concerned in regard to our own easily besetting sins.
To him that knows to do good, and does it not, to him it is sin.
And it is a solemn truth, of which we may often need to be reminded,
that it is to the Lord, the righteous judge of all men,
that we must individually stand or fall.

My principal wish has been, in proceeding with the work,
to show the transforming power of Divine grace,
and to furnish the reader with additional instances of the efficacy of that grace,
to make wise unto salvation all who receive it and obey it;
desiring that others may be thereby animated to pursue
that course of obedience and self-denial,
in which those who are taken from us have endeavoured to walk.
While thus performing the office of an editor,
I have often found it no light undertaking, and that it was indeed a serious employment,
to attempt to portray the feelings of those who were about to enter the invisible world.
At the same time, in contemplating the lives of our departed friends,
my faith has been confirmed in the soundness of that
part of the Christian profession of our Society,
which includes a belief in the inward manifestation
of the will of God to the soul of man.

In examining the materials which were brought under notice for this work,
it was found needful to make a selection; but it is by no means to be inferred,
that those who are not brought forward, were not examples of piety and Christian virtues.
It is, on the contrary, a pleasing and animating reflection,
that through the power of the Holy Spirit,
many others who were acceptable ministers among us,
or who were less conspicuous in our Society, have run their spiritual race in faith,
and finished their course with joy.
In some of these memorials,
there is more frequent mention of the Lord Jesus than in others.
Many who have entertained a sincere faith in the essential doctrines of the Gospel,
doctrines which have been uniformly believed in and upheld by our religious Society,
have, I apprehend, often avoided conversing upon them, from a fear,
lest by such discourse they should imperceptibly
weaken their reverence for these sacred subjects,
and their sense of those inestimable blessings conferred
on us by the coming of the Son of God in the flesh.

Faith in the benefits of the propitiatory sacrifice of Christ,
and in the guidance and help of his blessed Spirit,
are indispensable articles in the belief of a Christian.
But it is not the mere profession of these important
truths which constitutes the true disciple.
It must be the earnest endeavour of all who desire to bear that name,
to be delivered from the bondage and guilt of sin, by the power of a living,
operative faith; and to walk humbly before God, keeping his holy commandments.
May we then be daily pressing after these things, in watchfulness and prayer,
looking unto the Lord Jesus, and confiding in Him, as a true and unfailing Shepherd.
Then shall we experience Him to be unto us both "`wisdom and righteousness;`"
and then may we entertain the humble hope,
that He will finally "`be made unto us sanctification and redemption.`"

[.signed-section-signature]
J+++.+++ F.

[.signed-section-context-close]
Tottenham, 9th Of 2nd Mo., 1829.

+++[+++In transcribing extracts from letters, or other documents,
which were about to be inserted in this volume,
it has been found necessary sometimes to supply a word or two;
but care has been studiously taken,
not to introduce anything which should affect the meaning of the sentence.]
