== Chapter 1

[.chapter-synopsis]
* Elizabeth C. Secor
* Mary Post
* Rebecca Shewell
* Sarah Camm
* Rebecca Milnes
* Jennet B. Mott
* Thomas Hains
* Rebecca Toovey
* George Powell
* Jane Bennis
* Sarah Lidbetter

[quote.scripture, , Matt. 21:16.]
____
Out of the mouths of babes and sucklings thou hast perfected praise.
____

ELIZABETH C. SECOR was born at New Rochelle, in the State of New York,
in the first month, 1814.

In very early life she manifested an uncommon gravity and seriousness in her deportment,
was scrupulously careful not to do anything which she thought wrong,
and was remarkably cleanly and neat in her person and habits.
Towards her parents, she evinced a tender and affectionate attachment,
cheerfully obeying all their commands,
and avoiding whatever she apprehended would give them uneasiness.

When about two years and a half old, she desired her uncle to read in the Bible for her;
he accordingly read the narrative of Abraham`'s offering up his son Isaac,
at which she was greatly affected, and requested him to read no more,
as she could not help crying.

Some friends intending to have a religious opportunity in the family,
she appeared anxious for the time to arrive;
sat with becoming gravity while it continued,
and expressed a wish that they might have more such seasons, saying,
"`I had no idea that we should have such a good meeting.`"

It was her wish to attend religious meetings,
but the delicate state of her health mostly prevented her from going.
In the spring of 1818, her parents removed to Long Island,
where the change of air and frequent riding, so improved her health,
that she was able to go to meetings, in which she was an example of stillness,
and observed to her friends that she well knew the intent of assembling for divine worship.
Conversing with her mother on one occasion, she said, "`I try, when at meeting,
to sit still and think of the great and Almighty Being, and to love him.
I love him better than I do my parents,
because he is so good as to let me have my parents.
He is very kind to us.
We have a great many good things.
I think we are greatly blessed.
I love my parents next to Him, and I love every body.`"
She frequently concluded her observations with the expression "`I love every body.`"

She was endowed with a sympathetic mind,
and showed great sensibility for the wants and sufferings of the indigent.
A poor woman having called on her mother to solicit some necessaries,
Elizabeth heard her say that her children would be
glad of the crumbs she and her sister threw away,
which affected her greatly; and ever after, she was careful not to waste any thing.

She spent many hours in reading, and became very conversant with the New Testament,
often repeating to her mother the particulars of what she read there.
Hearing one of her acquaintances tell an untruth,
Elizabeth told her that it was a very wicked thing, and she should not dare to do it;
"`because, continued she, the great and Almighty Being sees and knows everything we do:
He knows all our thoughts; He knows what I am now doing, and what I am now thinking.`"
She then got her Testament and read the fifth chapter of the Acts of the Apostles;
and also repeated a dialogue on the subject of lying,
which she had learned by rote from one of her school books--telling
her acquaintance the consequence of speaking falsely,
and remarking again "`I should be afraid of doing so, it is so wicked.`"

Sitting at the table one day, after the family had finished their meal, she said,
"`Mother, O! how I love that Almighty Being who is so good to me.
He permits me to have so many excellent things.
He has a number of names--I have read them in my Testament.
He is called Lord, sometimes God, and sometimes Jesus Christ; but they all mean one.`"

She was frequently engaged in contemplating the solemn subject of death,
bringing it home to herself,
and speaking of it in a manner that reminded her
parents she was not to continue long with them.
When expressing her intention to do any thing, it was her practice to make this reserve,
"`If I should live and nothing prevent;`" and on
being asked by her mother why she spoke so,
she answered, "`Mother,
I do not know that I shall live until then--I do
not know that I shall live until tomorrow morning.
What a wonderful thing it would be to you if I should be taken away.`"

Alluding to one of her acquaintances, who was lately deceased, she observed,
"`I want to see her, but I know I cannot--for she is now a spirit.
When we die, our bodies go to the dust; it is only our spirits that can live;
and if we are good they live forever with Him who gave them to us.`"

On the 20th of the 9th month, 1820, she was taken ill with a fever,
and her sickness soon became alarming.
Her mind, however, was preserved very calm and pleasant,
and she bore her sufferings with great patience, to the admiration of those who saw her;
remarking cheerfully, when her pain appeared almost insupportable,
"`I do not know that I groan.`"

She manifested much concern for her mother, lest she should be wearied with nursing her,
frequently saying, very tenderly, "`Mother,
do lay down behind me and take a little rest.`"

She desired that the Bible might be read to her during her sickness,
although she could not bear to hear much at a time,
owing to the extreme irritability of her system.
Being requested to take something, she replied "`O! mother,
I cannot live,--I cannot get well.`"
Her mother observed that she could not give her up,
and wished her to do everything that might conduce to her recovery; Elizabeth answered,
"`well, then,
I am willing to try and take everything you wish me--I have suffered much to get well,
and cannot.`"

Observing her mother grieve, she said, very affectionately, "`Don`'t mother,
do so--why dost thou cry?
wilt thou not go with me?`"
Her mother replying that she could not help weeping to see her suffer so much, she said,
"`I do not suffer much-I am better than I appear to be.`"
She desired some of her relations to be sent for and seemed anxious for their arrival,
saying, "`If they do not come soon, I cannot wait.`"
Just before her close,
she requested her father to call all into the room--and being in extreme pain,
her mother asked her if she was going.
"`Yes,`" said she, "`the doctor cannot cure me,`" and soon after, "`Mother,
wilt thou come?
Father,
wilt thou come with mother?`"--and was gone immediately without a groan or struggle,
as if she had fallen into a sweet sleep.
She died the first of tenth month, 1820, aged six years and eight months.

The short, but exemplary and instructive life of this dear child,
furnishes abundant evidence that she had early submitted
to the tendering visitations of divine grace,
and carefully improved those outward means of religious
instruction with which a kind Providence had blessed her:
there is no doubt but she was accepted through the
merits and mercy of her Lord and Saviour,
and is now one of that happy number, concerning whom He said,
"`their angels do always behold the face of my Father who is in Heaven.`"
After observing what grace accomplished in her, who was but an infant,
surely none can say they are too young to become religious.
Her early removal out of this world,
ought to incite little children to serious reflection,
and to an earnest endeavour to follow in her footsteps,
that if it should please the Lord to call them away also,
they may experience that happy state of preparation, in which they can say,
"`Come Lord Jesus, come quickly, thy servant is ready.`"

[.asterism]
'''

MARY POST was born in London, in the year 1703.
Her disposition was amiable, inclined to religious thoughtfulness,
and her deportment grave and sober beyond her years.
Through submission to the operations of divine grace,
she became an example of humility and of plainness in dress and address,
manifesting a dislike to every appearance of pride and of finery in apparel.
The sweetness of her temper and the solidity of her
manners rendered her company pleasant and instructive,
and endeared her to her friends.

When about eight years of age,
visiting one of her acquaintances who was much attached to her,
and who indulged in gaiety of apparel, she said to her, "`Anna,
what signify these fine things thou hast on?
They will not carry thee to Heaven.`"
To which her friend answered, "`Pride is not in the things; it is in the heart.`"
"`But,`" said Mary, "`if your minds were not proud, you would not wear them.`"
She remarked to her mother,
that she greatly wondered at the pride she observed
in some of the youth who professed to be friends,
adding, "`I hope I shall never be like them.`"
Her mother said "`I hope thou never wilt be like them, but be an orderly child,
that thou mayest be in favour with God;`" at which Mary wept and said,
"`If I should love fine things, I must alter much;
what signify fine things when folks come to die.`"

The day before she was taken ill, she was sent on an errand,
and her brother having lately come from the country, she desired him to go with her,
which he refused.
She stood by him awhile, and then with a serious countenance said,
"`Wilt thou not go with me?
It may be, the next time thou comest up, thou mayest not have a sister to go with.`"

In the time of her sickness, being in pain, she often said, with uplifted hands,
"`O! dear Lord, if thou seest fit, give me a little ease;`" and again,
"`I had rather die than live: through mercy I am not afraid to die; I shall go to rest,
where I shall feel no more pain.`"

Her mother standing by her and sorrowing at the prospect of her dissolution,
the child said to her, "`Mother, do not cry; let us be contented;
the Lord can lay me low,
and He can raise me again,--If I were dead He can raise me again.`"

Through the mercy of God she was prepared for death;
and appearing anxious to die and go to rest, her mother said to her,
"`Why art thou so earnest to die! the Lord can ease thee of thy pain and give thee life.`"
She replied "`One must die once; and if I recover now I may be sick again;
and I had rather die while I am young.
If I should live until I am older, the devil might tempt me to be naughty,
and I might offend the Lord.
I am not afraid to die; through mercy I shall go to my rest.
If I live I am satisfied, and if I die I am satisfied.
I am willing to die, I had rather die than live.`"

Expressing a wish to see her brother, her mother said she would send for him;
but inquired what she desired to say to him,
in case a change should take place before he arrived.
She replied, "`If I can speak, will bid him be a good boy, and fear God,
that he may go to God Almighty.`"

A little while before her death, she lamented that people should be taking pleasure,
and not considering the love of God to their souls;
and the last words she was heard to express were,
"`Dear Lord God Almighty open the door.`"
In this heavenly frame of mind she departed to her everlasting rest,
aged about eight years.

[.asterism]
'''

REBECCA SHEWELL, of Camberwell in Surry, England, was a child adorned with meekness,
humility and innocence;
dutiful to her parents and affectionate to her brothers and sisters.
She loved the servants of Christ--was fond of perusing the Holy Scriptures,
and often contrited while reading them, so that those who heard her were edified thereby.

Being attacked with an illness which continued for many months,
she bore it with patience and resignation; expressing her belief that she should die,
and desiring her mother to pray for her; and her mother being enabled to do so,
it appeared to afford much relief to her mind.
A few days after, she observed, "`I have often been desirous of recovering;
but I find desires will not do, I must have patience.`"
Some remarks being made respecting the pleasing things of this world,
and what she might enjoy of them, she answered, "`I have no desire for these things;
I had rather die and go to Christ.`"
She was frequently engaged in prayer,
and desired to have the curtains drawn about her bed, and to be left alone,
evincing an earnest engagement of mind to be prepared for her great change.
On the day before her decease, her mother inquiring if she thought she should die,
she replied "`yes, and would rather die than live, but am afraid I am not good enough.`"
Her mother expressing her belief that a mansion in heaven was prepared for her,
the child said she was willing to go to it,
and again entreated her mother to pray for her.
Her mother answered "`I do--dost thou do it thyself?`"
She replied, "`I do, I do,`" and being asked if it was with words,
she said very fervently "`no, no--in my heart.`"
She appeared to be quite easy in mind, bade the family farewell,
and quietly departed this life, aged eight years and four months.

[.asterism]
'''

SARAH CAMM, of Camsgill in Westmoreland,
was visited with illness when about nine years of age.
She expressed a belief that she should be taken away by death, saying,
"`I am neither afraid nor unwilling to die,
but am freely given up thereto in the will of God.`"

Her father asking her if she could not pray to the Lord for help,
she answered that she could and did pray, and further said,
"`it was her belief that the Lord, the great God of heaven and earth,
would keep and preserve her soul, whatever might become of her body.`"

On the fifth day of her sickness, she was under more than usual exercise of mind,
and raising herself up in the bed, she said, with a cheerful countenance,
"`My sins are forgiven me, and I shall have a resting place in heaven.`"
Then, looking at her mother, proceeded, "`O! my mother,
there is also a place prepared for thee in heaven,
and thou shalt as certainly enjoy it as any here.
I do not desire my mother`'s death or removal from you,
yet we shall meet in Heaven in God`'s time.`"
Seeing her friends weep she said,
"`O! you should not do so--I am well--I am well,`"
alluding to the happy and heavenly state of her mind;
and soon after added, "`Shall I go down to the horrible pit?
Nay--the Lord hath redeemed my soul.`"

After addressing her brother in a lively and sensible manner, she spoke to her sister,
saying, "`Be content, for it is, and it will be, well with me.
I must go to a more fair place than ever my eyes beheld.
It will be well with me, and with all them that fear the Lord,
for we shall have everlasting joy in heaven,
when the wicked shall be tormented in hell.`"
Observing her sister weep, she said "`Do not cry, my dear Mary, lest thou grieve the Lord.
Be subject to the Lord`'s will in all things; love and be faithful to the truth,
and do not forsake thy religion whatever thou mayest suffer for it.`"
Again, "`I am satisfied with my religion--I will not forsake it,
although I should be fed with the bread of adversity and the water of affliction.
Oh! praises, praises, to my God and my Father.
Our Father, who art in heaven,
hallowed be thy name,`"--and repeated the Lord`'s prayer twice,
and the third time until she came to the petition "`Thy will be done in
earth as it is done in heaven,`" which she spoke very deliberately,
and signified to those about her that they were all to mind that--adding,
"`I am freely given up to his blessed will in all things;
praises to my God--bless his name; Oh, my soul.`"

On one occasion, her father having taken her in his arms, she said to him "`O,
my dear father, thou art tender and careful over me,
and hast taken great pains with me in my sickness, but it availeth not.
There is no help nor succour for me in the earth;
it is the Lord that is my health and my physician,
and he will give me ease and rest everlasting.`"

Near her close she took leave of all the family, saying, with a pleasant voice,
"`farewell--farewell to you all--only farewell;`" intimating
that now she had nothing more to do but to praise the Lord;
and thus, in a sweet frame of mind, she departed to her eternal rest.

Such are the happy effects of an early surrender of the will and affections to God;
denying ourselves those things which are displeasing in his sight,
and through the aid of His blessed spirit,
endeavouring to follow Christ Jesus in the way of humility and self-denial.

[.asterism]
'''

REBECCA MILNES of Botley-Carr, near Dewsbury, England,
was an invalid for about two years before her death,
during a part of which time her sufferings were great.
Her patience under affliction; her humble resignation,
her sense of the need of forgiveness, her love for her Saviour,
and her hope of salvation through Him,
showed that thus early in life she had experienced the great
work of regeneration to be begun and carried on,
and that she was, as she herself expressed, "`one of the lambs of Christ`'s fold.`"
She remarked, on one occasion, "`Ah, mother, what should I do without a Saviour?
He died for us, that we might be saved.`"
When in great pain she would frequently pray for patience and strength to bear it,
in a most affecting manner, saying, "`Oh! dear Lord, do give me patience; do please,
Lord, to give me strength to bear it!`"--At another time she said,
"`I believe I shall go to heaven.
I believe I am one of the +++[+++Saviour`'s]
dear little lambs.`"--When asked how she knew she was so, she replied,
"`He loves those that love him, and I love him very dearly.`"

About two months before her death, she wrote thus to her sister;
"`I have a great deal of pain; but I am very happy and comfortable.
I hope thou wilt pray to God to give thee a new heart.
I pray to him every night to blot out all my sins, and to give me a new heart;
and to give me less pain and more patience.`"
While having her wounds dressed, she prayed very fervently for patience, saying;
"`O! Father in heaven, be pleased to give me less pain.
Have mercy on me, O Lord.`"
Afterward with much feeling, she repeated the prayer which our Lord taught his disciples,
dwelling particularly on the words, "`Thy will be done.`"

She deceased the 2nd of fifth month 1842, aged 8 years.

[.asterism]
'''

JENNET B. MOTT was born at Nine Partners, in the State of New York, in the year 1803.
In her third year she received an injury in the back, by a fall from a chair,
which was productive of severe and long continued sufferings.
Her back became deformed,
and her debility increased so much that she was often
incapable of taking a step for some minutes.
She was put under strict diet, and had two blisters applied every day for six months,
which occasioned much pain; but she bore it with remarkable patience, often saying,
"`Dear mother, I will try to be patient;`" and when medicine was given her,
she would take it without the least complaint,
manifesting great self command and obedience.
It was distressing to behold the sufferings she passed through.
Before she was five years old, she was so reduced by a white swelling,
that for many months she could not bear her own weight,
and when a little recovered had to learn to walk as though she had been an infant.

After being permitted to enjoy the pleasure of walking again, for a short time, she was,
in the next spring, brought down to the borders of the grave; in which illness,
as well as in the former, she often spoke in a manner far beyond her years,
respecting her own situation and the Lord`'s power,
of which she manifested a lively sense.

Her conversation was marked by a peculiar strength of mind and ripeness of judgment;
her observations on the conduct of persons and on circumstances which happened,
bespeaking a degree of reflection rarely found in a child.
She enjoyed the company of grown people more than childish play,
and was particularly attentive to such as she thought pious.
During religious opportunities, though often in bodily distress,
she would sit or lie very still, and with a becoming solemnity of manner;
and at the pause usually observed before and after meals,
her countenance evinced that her mind reverently
acknowledged the bounty of our heavenly Father,
of which she often spoke.
On one of these occasions, she remarked while sitting at table after tea,
"`How many good things we have--we don`'t deserve half +++[+++of them:]
we deserve very little.`"
After being put to bed one night, she said "`O, mother, how good the Lord is,
to let us have such a good bed,
when so many poor little children have not any to lay on.`"

Her compassion for the poor and afflicted was worthy of imitation,
speaking of them with tenderness,
and contrasting the comforts she enjoyed with their privations,
as an incitement to gratitude and thankfulness.
She frequently asked to hear the Holy Scriptures read,
and would remember and apply them to herself and others:
the tenderness of her spirit on hearing particular passages of them, was very affecting.

A neighbour speaking of the distress she had witnessed,
in consequence of the storekeepers selling liquor to intemperate men,
for the money which their wives and children needed for their support;
Jennet listened to the conversation with evident sorrow and concern;
and in the evening said to her mother, "`Since we talked of +++[+++the storekeeper]
this afternoon I have been thinking he will see the cup of bitterness before he dies.`"
She was then so much affected that she paused; adding, afterwards,
"`If he could see all the people he sells rum to,
I don`'t believe he would do it any more.
He don`'t think how many it is, because he don`'t see them all together;
but he ought to think and take time to reflect: Is it not strange, mother,
he is such a clever man in other things, and yet does so wrong in this.`"
Being told that it showed how easy it was for us to do wrong,
if we did not reflect properly, she replied, very earnestly, "`Ah,
but it is very easy for us to do right too, if we would but think.`"

When about seven years old, after a friend had prayed and preached in the family,
she seemed much comforted, saying, "`I loved to hear him--I could have set all day,
it was so sweet`"--showing that she loved religion
and serious things more than any other.
In the evening, her breathing being oppressed, she was moved, when she said,
"`Now I am comfortable, only this pain in my breast,
and nothing can make that comfortable but patience, and I do try to be patient.`"
Afterwards she remarked,
"`I have been very quiet in my mind today;--I have been thinking
a great deal about what the friend said this morning;`" and,
on going to bed, alluded to the subject again, saying, "`If I was able,
I should love to go to meetings.`"

Although her sufferings were extreme, and, in the ordering of inscrutable wisdom,
so long protracted, she never questioned the Lord`'s goodness,
never murmured or repined at her situation;
yet she often spoke of her deformity and trials in a moving manner.
On one occasion, when she was so sore and weak that it was difficult to move her,
she said to her mother, "`Ah! dearest mother, thou hast had many doctors to me,
and they cannot cure me; but the Lord can cure me if He pleases;
and if it is not his will, I am willing to be sick to the day that I die.`"

Thus did she learn in the school of affliction,
and through the teaching of the grace of God, the important lesson,
so necessary for all to know the reduction of her will and the subjection of her temper,
which were strong, and to endure with patience and quietude, becoming a christian,
such things as were a great cross to her natural inclination.

A short time previous to her decease,
a friend expressed a belief that her heavenly Father
would soon release her from her sufferings,
and take her to himself.
She was much affected at the time,
and on its being afterwards mentioned to her as a consolation,
she signified she had not doubted before that she should go to happiness,
assuring her mother, with great firmness and composure, that she was not afraid to die.
She related the particulars of the death of a religious woman who
had been long sick and dreaded the conflict of dissolution;
but who prayed, very fervently, that she might go easily,
and that she did drop away like one going to sleep.
As she narrated this, her eyes were filled with tears,
and the expression of her countenance and her manner
evinced that she felt the same desire,
though she only added, "`Mother don`'t thou think the Lord heard her prayer?`"

Not long after this,
He who regarded her tears and had her sighs and sufferings in remembrance,
was pleased to spare her the apprehension of death by taking her to Himself,
as in the twinkling of an eye, by the rupture of a blood vessel,
which quickly stopped her breath, without a struggle, on the 14th of 2nd month, 1812,
aged eight years and eight months.

Her sudden removal from works to rewards,
ought to be a solemn warning to children to prepare
for death while in the enjoyment of health,
because they know not how soon, or how suddenly, it may come.
Her unspotted life, her patience and resignation under suffering,
and her constant dependance and trust in the Lord`'s power and goodness,
furnish an example for the imitation of all those who desire to
enter into that rest which is prepared for the people of God.

[.asterism]
'''

THOMAS HAINS, of Southwark, England,
was educated by his parents in the principles of truth,
as professed by the people called Quakers.
He was a dutiful child, and had a sense of the fear of God on his mind,
so that he behaved during his sickness more like a man than an infant,
(as he called himself) being concerned lest he should even say a word amiss.
He was very grateful for the love and tender care of his parents towards him,
and several times expressed it to them;
and when he took any thing which refreshed him he would acknowledge it with much thankfulness,
evincing that he was a grateful receiver of the Lord`'s mercies.
He bore his illness with great patience, and often expressed his willingness to die,
saying,
"`It is better for me to die--it is a troublesome world--we
should every day and every moment think upon the Lord.`"
A short time before his decease,
he uttered many expressions in prayer and praises to the Lord; saying,
"`Thou art a God of love--thou art a God of mercy--thou knowest the hearts
of them that love thee--Lord remember thy people--thou knowest the hearts
of the ungodly--thou hast nourished and brought up children,
and they have rebelled against thee.`"
He also mentioned the care we ought to take of the never-dying soul.

At another time,
speaking of the satisfaction he had in the prospect of a future state of joy and blessedness,
he said, "`Glory--glory--joy--joy--come mother, come father,
come all;--it is a brave place,--there are no tears or sorrow.`"
He then praised God, saying,
"`Thou art worthy to have the honour and the glory forevermore,
for to thee it doth belong.
Thou art God of heaven, and of the whole earth`"--and so continued,
about a quarter of an hour, in prayer to the Lord, observing, "`I am an infant,
and cannot do any thing without thee.`"
One evening, several friends coming to visit him, he desired their prayers,
and the next day prayed again himself, saying, "`Our Father, which art in heaven, etc.`"
Afterwards he remarked, "`It is a brave,
thing to be at peace with the Lord:`" His end drawing near, he exclaimed,
"`Father--Father,`" (his father, being present, asked what he desired;
to which he answered, "`I do not speak to thee,
but to my Heavenly Father,`") "`have mercy on me.`"
After expressing the joy he had with the Lord, he desired of those about him,
that he might be still; and laid secretly praising the Lord.
A few hours before he died, he said, "`I come,--Father, I come`"--being very weak,
his voice was low, yet he was heard to say,
"`God is my Father,`" and so quietly finished his days, the 12th of the 12th month, 1700,
between nine and ten years old.

Those who desire to have God for their Father, and to be the friends of Christ,
must imitate the example of this pious child, and live in the fear of the Lord,
obeying His will instead of following the evil propensities of their own corrupt hearts,
for, saith the Lord Jesus, "`Ye are my friends, if ye do whatsoever I command you.`"

[.asterism]
'''

REBECCA TOOVEY, daughter of Joseph and Rebecca Toovey, of London,
was a dutiful and pious child, a frequent reader, and a lover, of the Holy Scriptures,
and other religious books.
Although young in years, it pleased the Lord to endow her with a large understanding,
in things natural and divine, and being of an innocent and prudent demeanour,
her company and conversation were pleasing and instructive.
She was virtuous in her practices, quick of apprehension,
just and equal in all she undertook, and was never known to tell a lie,
or speak an ill word.
She loved to attend religious meetings, saying "`It was sweet to her.`"
Some few weeks before her sickness she was at a meeting,
in which a friend exhorted the children present to
make choice of the blessed truth for their portion,
whilst in the enjoyment of health, that they might be prepared for their dying hour;
to which she was very attentive, and was melted into tears;
and after the meeting was over retired by herself to read, which was her usual practice.

Having lived in the fear of the Lord, which preserves from evil,
when taken with her last illness, though her body was in great pain,
her heart was filled with the sweet incomes of the Lord`'s love and mercy,
which caused her to utter many heavenly expressions.

She endured her suffering with much patience and resignation,
and was observed to be in solemn supplication to the Lord,
in a humble and submissive manner, saying, when the pain was very severe, "`Sweet Jesus,
give me ease--Sweet Jesus, look down with an eye of pity upon thy poor, poor servant.`"
Some time after, she said, "`O! Lord, thou desirest not the death of a sinner;
but rather that he would repent, return and live,`" adding, "`I know it to be so.`"
At another time, "`Lord, if thou pleasest, thou canst give me ease;`" and again, "`Lord,
thou wilt help them that love and fear thee.
O! Lord, remember thy poor servant, and give me a little ease.`"

One of her attendants being affected to tears at her sufferings, the child observed it,
and said, "`Do not cry, I shall be well in a while.`"
Perceiving her school mistress to be troubled for her, she desired her not to do so,
saying, "`there is a rest prepared for the righteous; there is no ease here;
but there is ease in heaven.`"
On another occasion she observed, "`It is a sad thing to speak bad words,
and to tell lies; which I never did.`"
Having, through divine mercy, a well grounded hope of acceptance,
through Jesus Christ our Lord, she was not afraid to die;
but bade her relations and acquaintances farewell;
and in a heavenly frame of mind departed this life, aged nine years.

[.asterism]
'''

GEORGE POWELL, son of Jonathan and Mary Powell, near Colchester, England,
deceased the third of 7th month, 1822.
The precious effects of submission to the visitations of divine love,
were strikingly exhibited in the subject of this memoir at a very early age,
by a meek and exemplary demeanour, beyond most of his years.
He was a dutiful son, and affectionately attached to his parents, brothers and sisters.
He was fond of reading the Holy Scriptures, and other works of a serious character,
and delighted much to read to the servants, and converse with them on religious subjects;
and from his solid deportment in meetings for divine worship,
there is good reason to believe he was made acquainted with that worship
in spirit and in truth which is acceptable to the Almighty.

When about eight years of age, one of his school fellows having misused him,
he was advised, by another boy, to resent it, to which he calmly replied,
"`I do not read so in my testament.`"

About two weeks before his death, he was taken unwell,
and during the course of his illness uttered many expressions
which served to show the heavenly state of his mind,
and his preparation for that kingdom where nothing that is impure or unholy can enter.
On the 25th of 6th month, most of the family sitting around him, he said,
"`Wait patiently;--that when He comes we may be ready,
for here is nothing but trouble--I shall die and leave all my relations.
I delight in thy word, strengthen me, O! Lord, according to thy will.`"
Again, "`Praise Him; praise Him; and that forevermore;
that He may be with us in all the paths of our lives; then we shall have peaceful days.`"
Soon after, he said, "`I have felt it in my mind to say something to you:
"`Affliction cometh not of itself, neither doth trouble spring out of the dust;
but man is born to trouble as the sparks fly up.
Many are the afflictions of the righteous, but the Lord delivereth them out of them all!
O! Lord, deliver--Jesus Christ deliver.`"
Then asking for two of his brothers, he put out his hand and said, "`Farewell--farewell,
all!`"

About four o`'clock in the morning, as his sister was sitting by him,
he looked at her with a pleasant countenance and remarked,
"`I am going to enter an everlasting kingdom;`' and awhile after,
"`Angels and archangels wait to receive me--I go triumphant.`"
From this time his weakness was so great as to render articulation difficult;
yet his mind appeared calm and composed,
and he was favoured with much stillness until he departed;
aged nine years and six months.

[.asterism]
'''

JANE BENNIS, of Limerick, in Ireland, died in the first month, 1840, aged nine years.

During most of her life she was a constant sufferer from sickness,
and though of a pleasant and cheerful disposition,
yet a gravity and seriousness of demeanour always attended her.
She loved plainness and simplicity, and delighted much in reading the holy Scriptures,
the writings of Friends, and other religious books.
While able, she was a diligent attender of religious meetings,
in which her solid deportment was remarkable for one of her years.
Much of her time was passed in retirement and meditation,
and it was instructive to sit with her.
Frequently, before retiring to rest,
she was engaged to kneel in prayer to her heavenly
Father and beg for preservation from evil,
and the remarkably circumspect tenor of her life evinced that her petitions were granted.

When her disorder, which was consumption, assumed a more serious aspect, she said,
"`At one time I was afraid to die, but now I am not.
I do not wish to live--I am going fast; but I feel comfortable and happy.
The fear of death is taken away.
I know I am going to heaven.
I am now too weak to pray for myself; pray for me.`"
The day before her decease,
she had her brothers and sisters called to take leave of them, one by one,
and seemed particularly concerned for one of her brothers, that he might be a good boy.
A chapter in the bible being read, on hearing that verse,
"`The city had no need of the sun, neither of the moon, to shine in it,
for the glory of God did lighten it,
and the Lamb is the light thereof,`" she expressed in a very animated
manner the joy she felt in the prospect of so soon being there;
and in a little while after peacefully departed.

[.asterism]
'''

SARAH LIDBETTER, daughter of Bridger and Elizabeth Lidbetter, of Brighton, England,
was born the 3rd of third month, 1822.
From a very little child, she was fond of reading the Holy Scriptures,
and showed a decided preference for works of a religious character,--Piety Promoted,
The Guide to True Peace, The Saints`' Rest, and Pilgrims`' Progress,
being her favourite choice.
She was of a very unassuming, diffident disposition;
yet her observations on subjects that were discussed in her hearing,
evinced that her understanding was good,
and that she was a child of quick perception and matured judgment.
She much enjoyed meetings for Divine worship,
and mentioned the comfort and instruction she received in attending them,
even when they were held in silence.
Being fond of retirement and waiting on the Lord,
she early experienced the benefits and comfort of secret prayer,
endeavouring to bear in mind that she was always in the presence of her heavenly Father,
and must seek for the aid of His Spirit, to teach her to pray aright.

To her parents, she was dutiful, obliging and affectionate--orderly in her behaviour,
and of but few words.
She loved her brothers and sisters tenderly, watching over them for good,
and when they had done amiss, would plead with them in a very affectionate manner,
often saying on such occasions,
"`thou wilt displease thy heavenly Father;`" evincing that
her infant mind was supported and directed by Divine wisdom,
and the love of her heavenly Father shed abroad in her heart.
This preserved her in such fear of offending the Lord,
and such great tenderness of conscience,
that if at any time she said or did any thing amiss,
her sorrow and grief were very great.

From the age of seven years,
it was her daily practice to read a portion of the Holy Scriptures to the other children,
endeavouring to impress it on their minds,
by asking them questions upon what they had heard.
This she continued until within about two months of her decease,
having them around her bed;
and exhorted them (when she became too weak herself to do so) that
they should continue in the frequent practice of reading the Bible;
"`which,`" she added, "`is the best of books.`"

She was from early life a child of prayer;
and on one occasion asked her mother if she thought the Almighty
required that persons should always kneel when they prayed.
On her mother`'s replying that she believed every
prayer that came from a sincere heart was accepted,
whether with or without that form; the child answered very sweetly,
"`so I think mother.`"

When about eight years of age, she was attacked with an alarming disease,
of the danger of which she seemed fully aware; remarking one evening to an acquaintance,
that she should have liked to live and help her mother and be a comfort to her,
but added,
"`If I die I shall only go out of a wicked world where there are many
troubles and temptations.`"--Her patience during this illness was exemplary,
and proved an alleviation and comfort to her mother under the affliction.

She recovered so far as to be able to attend school, in which she took much delight,
particularly in the Scripture lessons, saying they often cheered and comforted her mind,
and that she considered it a privilege to be able to learn
and hear others repeat several chapters and hymns.
The fifty-third chapter of Isaiah was one that she greatly enjoyed.

About the beginning of the year 1831, she was visited with another illness,
of a more painful and distressing nature; yet her anxiety to be useful to her mother,
and to repay her in some measure for the care she had taken of her,
induced her to exert herself--and even after her symptoms had become very doubtful,
to look forward with a hope that her health might be restored.
Her anxious mother felt concerned at this,
and wished her to be fully aware of her critical situation;
and as they were sitting together one first-day, Sarah said to her, "`Mother,
which wouldst thou rather, see me in perfect health,
enjoying the pleasures of this world, or afflicted and suffering, as I now am?`"
Her mother replied, "`My dear,
far rather as thou now art:`" to which the child
rejoined--"`O so would I--so would I:`" adding,
"`Mother, I have for some time wished and prayed to be resigned to die,
and this evening I have been made to believe that I shall soon die,
and I am so happy to feel I am quite resigned;
thou canst not think how happy it makes me.
I feel so full of joy to think I am going out of this wicked world into heaven,
to my Saviour.
Oh, mother! it seems as if a heavenly voice said,
'`The gates of heaven will be open to receive thee.
How glad I am--how thankful I am.`"

For some days afterward her mind seemed wholly engaged with the delightful prospect;
and though her bodily sufferings became excruciating,
yet her subsequent expressions evince how patient and resigned she was to the
will of her heavenly Father. She showed much concern on account of the Jews,
lamenting their want of belief in the Saviour, saying,
"`What should I do without a Saviour now?-Oh! how much they miss--what
a sad thing! cannot something be done for them?`"

For weeks together her limbs were paralyzed,
from the violence of her disease and the greatness of her sufferings,
yet never did a murmur escape her lips, but she often remarked,
"`I have never once thought my situation hard--I have not one pain too many.`"
She one day inquired of her grandmother how much longer she thought she should live,
and being told that the time for her release would soon come,
though none of them could tell when, she replied,
as though checking herself for the question,
"`Never mind how long--a crown of glory is worth waiting for.`"
Being questioned one day respecting the state of her mind, she said,

[verse]
____
All gracious Lord, whate`'er my lot
At other times may be,
I welcome now the heaviest grief,
Which brings me nearer Thee.
____

"`This is the state of my mind at this time, mother.`"

Her mother grieving over her accumulated sufferings, she seemed anxious to console her,
and observed, "`Mother, I think this is not all on my own account;
but I believe thou wilt live to see for whom, and why, I have suffered so long.`"
During the night, when she had severe spasms in her side,
so that the perspiration would trickle down her face from the violence of the pain,
she would say, with a sweet smile, "`Mother,
how these pains remind me of the sufferings of my Saviour.`"
One of her cousins, to whom she was much attached, calling to see her,
expressed a desire that she might be entirely resigned to the will of her heavenly Father,
whether it was to live or die,
and experience the everlasting arms of Divine love underneath,
to support her through all her sufferings--tenderly
inquiring if she did not experience this.
Sarah meekly replied, "`I don`'t know that I do.`"
Her cousin encouraged her by saying, "`I have no doubt, dear, but thou wilt;
these feelings are not at our command.`". Some time after this,
having been favoured to partake largely of the sweet feeling of Divine support,
when in much pain, and also entire resignation to her heavenly Father`'s will, she said,
"`Now, dear mother, if cousin was here,
I could join with her and tell her that I have experienced what it is to be resigned,
and to feel, as it were, my Saviour`'s arms open to receive me;
this makes me very thankful and happy.`"

About three weeks before her death, she called her sister, her little brother,
and two young relations, who lived in the family, around her bed;
to each of whom she gave much suitable advice, part of which is as follows.
Addressing the elder of them, aged eight years, she said, with much earnestness:
"`I am very soon going to die, and perhaps may not be able to speak to thee again;
and although thou sees me so ill, I am very happy,
for I know that I am going to my heavenly Father in heaven, among happy angels,
who are constantly singing praises, where I shall see my dear Saviour, whom I love,
face to face.
Now I want thee to be a good boy, that when thou dies,
thou may be permitted to meet me there; but there must be a great change in thee,
for thou art very naughty:--Thou must pray earnestly
to thy heavenly Father to make thee a better boy;
and never tell stories, or fight,
for these ways are very displeasing to thy heavenly Father.
I do not remember ever to have told a story, or hurt any body, but I have often sinned,
and sin will follow us while in this world;
but I prayed to my heavenly Father very earnestly, and kept on until I was forgiven,
so that now I have nothing to trouble me; and sometimes am so happy,
I seem as if I could sing for joy.
Try to be a good boy, and read the Bible very often, and pray to be made a good boy;
for what a sad thing it would be, when thou dies, to see me happy among holy angels,
and for thee to be miserable in the wicked place, shut away forever.
Now, Thomas, wilt thou try to pray earnestly to thy heavenly Father?
for he can and will make thee a good boy, if thou pray to Him,
and try to love and fear Him and serve Him; think of this when I am gone,
often think to thyself how happy I must be in heaven--that will help thee to try to
be good--and there is nothing in this world that can make thee happy.`"

Then looking towards her sister with a lovely smile, she said, "`Betsy,
I believe I am very soon going to my heavenly Father in heaven;
in such a beautiful place, among happy angels, who wear crowns on their heads,
and are always singing praises,--won`'t that be delightful?
And there I shall be quite well, never sick any more, nor grieve any more,
nor do wrong any more.
Wouldst thou like me to go there out of all my suffering,
and wouldst thou not like to meet me there, with our dear mother,
and all our dear relations, in that beautiful place?
Well, then, thou must be a good girl, and never tell stories,
nor give thy mind to be proud, nor give way to thy temper;
but pray to thy heavenly Father very often indeed, to make thee a good girl.
Love good things, and read thy Bible, and pray when thou reads there,
then thou wilt learn many things: And as thou wilt be mother`'s oldest daughter,
when I am gone, thou must try to comfort her; and when thou sees her tried,
(for mother has many trials,) thou must look about,
and see what thou canst do to help her, and be very good to her, and pray for her,
as I used to do.
Never want any thing she refuses, for mother does a great deal for us,
and we want a good deal of money for shoes and food;
so thou must be satisfied with what thou hast.
Take care of the children, and then thy heavenly Father will love thee,
and as thou prays to Him, He will make thee grow better and better;
and when thou art laid on a bed of sickness, He will make it easy to thee.
See how He enables me to bear my sufferings, and how happy I am,
because I know I am soon going to Him.
So thou wilt try and remember what I have said to thee, dear, won`'t thou?
and then thou wilt some day come to me in heaven,
where we shall never have to part again, and be so happy forever.`"

To her cousin, a little girl about six years of age, she affectionately said,
"`Dost thou know I am going to die?
I am very glad, because I shall be happy; I shall go to heaven,
where I shall see my heavenly Father, and His holy angels, and where I shall be happy,
and shall never more suffer pain.
Would thou like to meet me there, in that beautiful, happy place,
when it pleases Providence thou should die?
Well, then, thou must be a good girl: now thou art a little child,
and knows but very little, so if thou wish to grow a good girl,
thou must be humble and very attentive when mother talks to thee, or reads to thee,
or any other friends; that will be the way for thee to learn a good deal.
Try to remember their advice, and always think, if thou art doing any thing wrong,
that if my mother does not see thee, thy heavenly Father sees,
and can punish thee much more than mother, for He can make thee very miserable here,
and when thou dies He can cast thee into the wicked place--how shocking that would be?
But if thou art good, thou wilt go to Heaven and be happy:
but thou must pray very much--thou art old enough to pray--thou
knows how to ask mother for any nice thing,
and so thou knows how to ask thy heavenly Father to make thee good, and that is praying;
and when thou art old enough, thou must read the Holy Scriptures,
and they will teach thee a great deal.
Dost thou understand me?
Well, then, try to think of it when I am gone, and never tell stories, or be sly,
for that will grow, and thou wilt get worse and worse,
if thou dost not try to pray to have thy temper changed;--and thou wishes to be good,
don`'t thou?
Well, then, thy heavenly Father will make thee good if thou prayest to Him.`"
She also spoke in a sweet, kind manner, to her little brother.

Once she said, "`Dear mother, this has been a day of prayer for thee,
that thou mayest be supported through all.
Do not grieve for me when I am taken; I know thou wilt feel it much,
but I have prayed for thee to be supported; as to myself.
I seem to have nothing to do but to wait my dismission; I think the words in my mind are,
'`I am preparing a mansion for thee, so I have no cause to be unhappy.`"

She much enjoyed having the Bible and other good books, and hymns read to her,
and selected several passages and verses,
which she requested her mother to write on cards,
with her love to several of her near relations;
to be sealed up and delivered to them after her decease, as mementos of her regard.
One morning as the children were preparing to go out,
and planning their amusements for the day, one of them said,
"`that will be a change,`" Sarah observed it, but not in a fretful or impatient manner,
and remarked, "`there is no change for me, but from one pain to another; the spasm,
the cold fit, the fever, and convulsion.`"
Her mother said, "`No, my dear, there is not indeed;`" but she quickly replied,
"`All will be made up in the end.`"
After two or three days, she said, "`Mother, how grieved I have felt,
that I should have suffered such a murmuring word to escape me.`"
Her mother said, "`What word, my dear, I have not heard thee murmur.`"
She replied, "`Oh, yes!
I said, no change for me, the other day;
how wrong--when I am so soon to have so glorious a change.`"

On fifth-day, the 18th of eighth month,
when the whole length of the spine was much inflamed, she said, "`Oh! my dear mother,
the pain, the pain in my back is extreme, pray for me.
Oh! my dear, my gracious Saviour, if it be thy holy will, take me to thyself,
or give me patience to endure this suffering;`" this she repeated several times,
and added, "`Oh! my beloved mother,
if my prayer is not heard--I seem as if I could not pray; what, if after all,
I should be turned out and go among the wicked, what shall I do!
Oh! my dear mother, there seems a doubt; do pray for me.`"
The perspiration flowed at the thought, and she exclaimed, "`But oh! my dear,
my own heavenly Father, take me to Thyself.`"
On her mother saying that she believed this to be a temptation of the enemy,
who was permitted at times to tempt Christians almost to the last, she became quiet,
and after a time of silence, she sweetly smiled, and soon after, in an ecstasy of joy,
exclaimed, "`Oh mother! now I can pray; how comforted I feel that I can pray!
I know not how to be thankful enough for this favour; the word in me is,
'`I will deliver thee from the power of the enemy, and take thee shortly into Heaven.
How happy I am,`" she added, in a feeble voice,
"`I believe the worst of my sufferings are over;
I do not know how to be thankful enough to my heavenly Father for ease;
I feel so happy I am able to pray; and though you cannot hear me, that does not matter;
though my lips do not utter, I pray inwardly.`"
After remaining some time in this happy state, she said, "`Oh that great enemy,
I hope he will not again be suffered to tempt me;
I seem to think I have gone through the worst.`"

On sixth-day, the 19th, after a quiet, but sleepless night,
free from those acute spasms and convulsive throes,
from which she had lately suffered so much, she appeared unusually low,
and her mother anxiously inquired the cause.
After a little reluctance, and shedding many tears, she said, "`I believe I am better,
and perhaps likely to live some time longer--this is a great trial to me.
Oh! the impatience I suffer to be gone; oh!, pray for me,
that I may get rid of such anxious thoughts,
for how wrong it must be to feel so impatient;
oh! that my faith and patience may hold out to the end.`"
After this she enjoyed some hours of calm, and smiling, said, "`Mother,
now I seem not to mind pain; and though sharp, I can rejoice in the midst of it;
I feel so sure it will be well with me, and so comforted in thinking,
that every pain makes me weaker, and brings me nearer Heaven.`"

At another time she said, "`Oh! my dear mother, the heavenly voice says,
(for I think it is,) "`Thy day`'s work is done, thou hast only to wait.`"
Oh! how full of love I feel for my dear Saviour! his arms
are open how I long to rush into them and embrace Him,
for the happiness I this moment enjoy; I am happier now than I have ever been;
oh! how thankful I ought to be.
He seems to say, I am preparing a mansion for thee: all my will is gone,
I have no will but to wait His time, that is the best time.`"
Soon after, "`Mother, how I feel for thee, the separation will be keen, very keen.
I have asked my cousins to come and see thee, and comfort thee,
and have no doubt they will do their best; but pray, dear mother; that is the best way;
God is the best friend.
I`'ve no doubt it will be made up to thee.
When ill, if thou should have to feel much pain, think of me;
think how it has been made up to me, how every pain is made up in the joy I now feel.`"

As she drew nearer the close, her weakness and difficulty of respiration,
which seemed to threaten suffocation for several days before the event,
increased her wish to be gone; and her anxious inquiry of her medical attendants,
"`How long do you think I shall last?`"
was very affecting.
One of them remarking, "`You have lived, my dear,
much longer than I expected,`" she said, "`Dost thou think I shall go through the week?`"
On his replying, "`It is not likely you will,`" she said, when he left, "`Oh,
mother! it felt as if my hands would clap together of themselves for joy!`"
Yet her desire for faith and patience to hold out to the end, was very strong,
and she would often request those about her to pray that they might not fail.

On seventh-day afternoon, the third of ninth month,
she requested her mother to come to her bedside, saying, "`Mother,
I believe my breath is going: give me a sweet kiss,
and send for my dear father and uncle upstairs, that I may bid them farewell.`"
This being done, she took an affectionate leave of them, and said,
"`I feel cold chills in my chest, are they not the cold chills of death?`"
She then repeated,

[verse]
____
That voice, oh! believer, shall cheer and protect thee,
When the cold chill of death thy frail bosom invades.
____

But soon added, "`I will say no more of these feelings, they may make me shrink at death,
which I do not wish to do.`"
Soon after she said, "`Farewell, my dearly beloved mother, if I should go in my sleep,
as I feel very heavy for sleep.`"
She dozed until within five minutes of her death,
and agreeably to her earnest prayer to retain her senses to the last,
was enabled to speak with her latest breath; for on her saying her head was uneasy,
her mother remarked, "`My dear,
thou art just entering into glory,`" when with a smile and the inquiry,
"`Am I?`" She ceased to breathe, without a struggle, or even a sigh.
Thus died this lovely, pious child, on the day she was nine years and a half old.

May the foregoing narrative prove an incitement to those into whose hands it comes,
often to ponder seriously the injunction of our blessed Lord,
"`Be ye also ready,`" that by living in the fear of God
and in obedience to the manifestations of his Holy Spirit,
whether they are called out of time sooner or later,
they may at that solemn period be prepared to die,
and "`have only to wait their dismission`" from this life,
to be received into the arms of our dear Redeemer.
