== Chapter 3

[.chapter-synopsis]
* Hayes Hamilton
* William Fennell
* Elizabeth Furly
* Jesse Cadbury
* Joseph Briggins
* Sarah Scott
* Amy Elizabeth Lloyd
* Thomas Burling
* Ann Reeve
* Robert Boadle
* Putnam F. Locke

HAYES HAMILTON, son of Hugh Hamilton of Ireland,
a short time previous to his death observed that several times when alone,
he had enjoyed so much of the comfortable presence of the Lord,
in silent waiting upon Him and meditating in His law,
that he could have wished to remain in that state of mind forever.
He seemed to have a presentiment of his approaching dissolution,
and when about leaving school told his teacher that he should see
him go that way no more until he saw him carried to his burial.
His master inquired the reason of his saying so,
he replied that he knew he had taken the smallpox and should die of it,
which came to pass about twelve days after.

Speaking on the subject of baptism, "`he said he could prove from Ephesians,
fourth chapter, fifth verse, that there was one Lord, one faith and one baptism;
those that will be satisfied with water +++[+++baptism]
let them hold it, for my part I depend nothing upon it:
I depend only upon the baptism of the spirit.
I fear there are many that talk about baptism, who know very little what it is.`"
About a quarter of an hour before he died, he inquired the hour of the day,
and then said "`Heaven is not far from me.`"
Being asked if he was willing to go and leave his connections and the world, he replied,
"`Yes, I am; it is a sweet change.`"
A relation present desiring that the Lord might prepare him,
and clear the way before him, he looked earnestly at her and said "`I know the way,
and +++[+++Him]
who hath cleared it.`"
He departed this life, to a better and more glorious inheritance,
aged twelve years and seven months.

[.asterism]
'''

WILLIAM FENNELL of Youghall, in Ireland, was often visited with the love of God;
and followed by the reproofs and convictions of the Holy spirit,
when he had been wild and unruly and run with other boys to play.
When laid on a sick bed, he was under much exercise of mind,
and desired to have the ten commandments read to him, which being done,
he was asked how far he had kept them.
He answered, that he had not, as he could remember,
ever taken the Lord`'s name in vain--that he had loved and honoured his father and mother,
and been careful not to tell lies,
or false stories on any one--nor had he stolen any thing, except once taking some plums,
without asking leave; which he hoped the Lord would pass by,
with whatever else he had done amiss.

Two friends being in the town,
he requested they might have a religious meeting in the chamber with him,
with which opportunity he afterwards expressed his satisfaction,
and then broke forth in much trembling and humility, saying, "`O Lord,
forgive all my faults, and have mercy and pity on my poor soul.
Keep out the enemy that is ready to come in upon me, for none but thee, O Lord,
is able to do it.`"
He called his brothers and sisters and exhorted them to "`love and fear God,
and to pray to Him to fit them to die; to love truth and go to religious meetings,
and wait upon God; to do what their father and mother bade them,
and to read in their bibles,
where they would find it was God`'s command to children to obey their parents,
for this is well pleasing unto the Lord.`"

One of his companions coming into the room, William said to him,
"`Dost thou think thou art fit to die?
If thou thinkest thou art not, then pray to the Lord and desire him to make thee fit.`"
He also advised him not to mind play too much,
saying "`he was very sorry that he himself had so long done so,
but hoped the Lord would forgive him.`"
Lying still for some time, and appearing under concern,
he was asked what it was and answered,
"`I am desiring the Lord to bring me in with the rest of his lost sheep.
I have cried unto him many a night since I have been ill,
for I have been a wild boy and loved play too well, and when you +++[+++meaning his parents]
sometimes corrected me I took it a little hardly, but now I am glad you did,
and I cannot express the love I now have for you for taking
that care of me--you did well--had you not done it,
I might have been wilder.
The Lord hath been following me, and striving with me, to bring me down these two years;
and has let me see, when I have been running to play,
that if I continued running on to be wild, than weeping,
wailing and lamentation would be my portion--and sometimes I have turned back,
and gone into the garret and wept bitterly,
and have desired the Lord to help me--but afterwards, when enticed by my comrades to go,
I was not able to resist the temptation, which was my great trouble;
and I have got into a secret place to endeavour to retire,
and often have prayed to the Lord, in the night season, on my knees,
when others have been asleep.
Oh!
He doth not love laughing and joking--I never read that
Christ smiled--but often prayed and wept.`"

Soon after this, he prayed, "`O Lord, hear me, and have pity on me,
for thou knowest I am very sorely afflicted-Lord, help me--O, it is none but thou Lord,
that can do it.
O Lord, be near me, and suffer not the enemy to prevail over me.`"
Speaking on the subject of prayer, this child observed,
"`I have much lamented to consider how people teach their children the Lord`'s prayer,
without minding the depth there is in it--saying Our Father which is in heaven--but
they that remain in wickedness are not his children and cannot rightly call him Father.
Hallowed be thy name--but too many dishonour it by their wicked words.
Thy will be done in earth, that is in our earthen bodies,
as it is done in heaven--and we all know there is nothing but the will of God there--Oh,
but how little of the Lord`'s will is done here.
Give us this day our daily bread--O Lord, give me daily bread from thee.
Forgive us our trespasses as we forgive them that trespass against us--but Oh,
how unwillingly do many people forgive those that trespass
against them--how can such expect forgiveness of the Lord!
Lead us not into temptation but deliver us from evil--O, leave me not in temptation,
but deliver me from the tempter, for thine is the kingdom, and all power is with thee,
and glory forever.
This prayer, people teach their children by heart, and think it is enough.
I have been at play with a boy in the street, and his father has called to him, saying,
Have you said your prayers today! and he has gone in from me and stood behind the door,
and said this prayer as fast as he could, for haste to go to play again;
I hearkened to him all the while.`"
He lamented much over such careless professors of religion;
and to many who visited him he gave good advice, tho`' his breath begun to grow short;
saying, "`I desire to please the Lord always.`"

Through divine mercy he was favoured to feel entire resignation to the will of God,
and requested his parents to give him up freely,
taking his leave of them and the family with much tenderness and composure.
He then paused and said, "`O,
what joy I feel`"--and continuing to praise the Lord as long as his strength remained,
he sweetly departed this life; aged twelve years and six months.

[.asterism]
'''

ELIZABETH FURLY, of Colchester, in the county of Essex, England,
was a child who early loved and feared the Lord,
delighted in the society of those who excelled in piety, and abhorred lying.
Being taken sick, her heart was filled with the love of God,
and two days before her death she uttered many precious expressions,
respecting the Lord`'s mercies to her, and prayed to Him,
that she might be preserved faithful to the end.

Several persons being in the room, she supplicated as follows:
"`Whatever is not of thyself, O Lord, purge out of me, yea,
purge me thoroughly,--leave no wicked word in me--thrust away the power of darkness.
O, Lord, make me able to praise thee; let me not come into that way which is evil,
for if I do, I shall dishonour thee and thy truth:
I hope I shall never rebel against thee any more,
but have full satisfaction in thee and in thy ways, and not in the evil one and his ways.
Wash me, O Lord, thoroughly; let not an unadvised word come out of my mouth.
Shew those, O Lord, that have done evilly, the evil of their ways;
and lay a burden upon their spirits, that they may leave it.`"
Adding, "`I feel no pain; the Lord is good to me--good is the will of the Lord;
let thy will be done in earth as it is done in heaven;
everlasting kindness hast thou shown me,
and I hope I shall never forget it while I am in this world.`"

She warned one of her brothers of the danger of an evil life,
and affectionately exhorted him to turn to the Lord, saying, "`Improve thy time,
for thou knowest not how soon thou mayest be taken
away;`" and putting her arms about his neck,
entreated him to mind what she said.
To her other brothers she also imparted tender admonition, saying, "`Love the Lord,
brothers, love good men; hate the wicked one.
O, love the Lord, and then you will be a joy to your father and mother.`"
Observing one of her sisters weeping, she said, "`Weep not for me; I am very well.
All +++[+++of you]
serve the Lord, that He may be your portion: in my Father`'s house there is bread enough;
there is fullness, want of nothing; yea, there is fullness of bread,
durable riches and honour.
I desire never to forget the Lord.`"

As she had lived in the fear of the Lord and in innocency before Him,
she was favoured with the enjoyment of sweet peace on her death bed,
and joyfully departed to eternal glory, aged thirteen years.

[.asterism]
'''

The instructive and interesting events which occurred
during the last illness of JESSE CADBURY,
son of Richard and Elizabeth Cadbury, of Birmingham, England,
induced a near connection to preserve a short account of his life and some of his expressions:
furnishing even to those of mature years,
an example of the christian`'s hope and consolation, in the last conflict of nature.
To children it may serve to evince the advantage
of an early acquaintance with pure religion,
and that by following the dictates of the holy spirit of Christ in their hearts,
they may become of that happy number, of whom it is declared,
"`Out of the mouth of babes and sucklings thou hast perfected praise.`"

In the early part of his life he evinced an amiable and grateful disposition,
while his steady,
consistent and innocent conduct showed that he had
sought an acquaintance with Him who graciously said,
"`Suffer the little children to come unto me, and forbid them not,
for of such is the kingdom of heaven.`"
When about nine years of age, symptoms of an alarming and painful disease appeared,
which baffled the skill of his physicians and continued
to afflict him during the remainder of life.
The constant irritation occasioned by the malady tended to produce fretfulness of temper,
yet he seldom gave way to this disposition,
and for the last two years of his life was enabled, through divine grace,
entirely to control its influence,
his mind appearing uniformly placid and grateful for the comforts he enjoyed.

The Holy Scriptures, which were his frequent companion,
proved a source of much delight to him; and he took pleasure in reading the psalms,
before bed time, to his younger sister, to whom he was particularly attached.
To the comfort and efficacy of prayer he was no stranger,
and on one occasion mentioned to his sister that
he awoke in the night with great uneasiness of mind,
from having omitted to put up his supplication to the Almighty before he went to sleep.
In the attendance of religious meetings he manifested an exemplary seriousness of deportment;
and from the satisfaction he expressed,
there is reason to believe that his mind was often made
sensible of the tendering influences of divine love.

About the thirteenth year of his age, he was attacked with a severe illness,
which continued four weeks, during which time he underwent the most acute sufferings,
yet he was preserved in patience and resignation, never uttering a murmur or complaint,
but frequently expressing himself with cheerfulness and gratitude to those around him.
About four o`'clock in the afternoon of the last day of his life,
being sensible of his approaching change, and evincing great clearness and serenity,
he requested one of his attendants to read a chapter in the bible,
and soon after this was done, he raised himself up and said,
"`I believe the Lord is near to help me,--I am going to a better world.`"

To his father he said, "`Farewell,
the Lord is on my right hand--I know I shall not be moved.`"
He then took an affectionate leave of his brothers and sisters who were present,
and likewise of the servants and assistants, telling them he was going to a better world.
A person who was standing by, observing,
"`I hope we shall meet again in a better world,`" he replied,
"`I hope we shall be found worthy to enter the glorious city,
to sing praises and hallelujahs to Him that sitteth upon the throne.`"

During this affecting scene, he uttered many instructive expressions,
which shewed that amid great bodily suffering, arising from the last conflict of nature,
his mind was stayed upon Christ Jesus "`the rock of his salvation,`" and that he was
favoured with a foretaste of that heavenly joy which awaited his redeemed spirit.
At one time, however, he was tried with distress of mind;
yet through the goodness of the Lord, it was not permitted to continue long;
for in a little time he emphatically exclaimed, "`O, the beautiful sound!
What delightful melody:
I see my Saviour coming to meet me with his arms open`"--and afterwards,
"`I know that I die in the Lord--I know that I am going to sing praises, high praises,
to my God, through Jesus Christ my Lord.`"

He was frequently engaged in prayer,
sometimes his lips moving and his hands raised when no sound could be
heard--in a faint voice he supplicated for his brothers and sisters,
whose names he mentioned with distinctness.
From nine o`'clock, he was evidently in the conflict of death,
and several times prayed to be released, saying, "`O, Lord, pity me--I am willing to go.
This is death!
O Lord, give me patience to bear my afflictions.`"

His mother kissing him, he observed to her,
"`My face is cold--I am going to die--I shall be happy in
another world--here there is nothing but trouble.`"
As the clock struck eleven, he remarked, "`I have now been two hours dying,
by the clock;`" and soon after putting out his hand to his mother he said,
with much emphasis, "`Farewell!
Farewell!
The Lord is near at hand to bless us!
O, grave, where is thy victory!
O, death, where is thy sting!
O, Lord, please to send death.`"
These were the last words he was heard to utter-turning his head on the pillow,
his spirit quietly departed to that glorious rest prepared for the righteous.
He died on the 19th of 9th month, 1818, aged about thirteen years.

[.asterism]
'''

JOSEPH BRIGGINS, of Bartholomew Close, in London,
was taken ill in the fourteenth year of his age,
and the disease being violent he was soon reduced very low.
His conduct while in health had been orderly and dutiful to his parents;
and in the near prospect of death he was favoured with the enjoyment of sweet peace.
On one occasion, after having laid still for about an hour,
his mind appearing to be filled with joy and pleasantness, he said,
"`I shall praise the Lord, for He only is to be praised.
O, I have never heard of any other God but thee, my Holy One,--I have heard of thee,
but now I see thee in glory.`"
Calling for his father he said, "`Oh! pure and glorious is my Saviour,
who hath appeared and hath taken me into His kingdom.
Oh! my eye has seen His glory.`"

Shortly after this, he prayed very solemnly in the following words,
"`Thou most glorious God--great and wonderful things are brought to pass by thy own pure,
holy power, by which thou hast revealed thy Son.
O my King, let all people stand in awe of thy power,
by which thou hast gathered many out of their sinful ways, into pure obedience to thee.
Thou hast given us a pure knowledge.
O pure, glorious and holy God, let thy life reach unto all my dear friends,
and keep them that know thee, steadfast on thy holy foundation, Christ Jesus my King;
whose appearance is very glorious at this day, and of his government no end is to be;
but thousands of thousands shall come to see and be made partakers of his glorious,
bright, and shining day.`"

At another time he said, "`There are many ways and baptisms in the world, but O,
thou holy One, we have known thy spiritual baptism into Christ Jesus, my Lord,
by whom we have known and felt the living water.
Oh, it is indeed exceedingly pure, by which we have been washed from all our sins.
O my King, thou wast slain, and by the virtue of thy pure blood, we have this given.
Oh that all may wait continually upon thee,
that they may be kept from all the deceitful ways of the world.`"
To those standing by him he said, "`Mind and serve the Lord in your day;
for the holy truth received by you, is the way in which you must wait and obey.`"

After laying still a short time, he said, "`The Lord hath taken me into his kingdom;
he hath discovered the fresh springs of his love to my soul.
All you that know the Lord,
be obedient to his power and he will discover himself more +++[+++fully]
to you.`"
Some of his acquaintance wondering to hear him express himself in so remarkable a manner,
he told them the Lord had fully made known to his soul,
that which he had some feeling of before.
On the following day, he was very earnest in prayer, but in a low voice:
he also sung of the Olive tree and the fruit thereof,
on which his soul fed and was refreshed, and being asked what tree he meant,
answered very distinctly, "`The tree of life.`"

[.asterism]
'''

SARAH SCOTT, of Hambridge, county of Somerset, England,
was a girl of affectionate and affable temper and sober behaviour,
and not addicted to any bad actions or words.

When laid upon a sick bed, with but little prospect of recovery,
it seemed hard for her to be reconciled to her situation;
but in reading several passages in the New Testament,
concerning the afflictions and chastisements which the Lord appoints for his children,
as Hebrews xii, etc. she was favoured to experience resignation,
and afterwards received great comfort,
so that her heart was often enlarged in the love of God,
to magnify and praise the great Author of her salvation.

Her uncle asking her if she was willing to die, she said,
"`If I had assurance of the love of God,
I should;`" and on his inquiring if there was any
particular thing which troubled her mind,
she answered, "`Nothing in particular, except that I have not been more circumspect.`"
Upon his mentioning to her the great mercy of God in Christ Jesus, who died for her,
she seemed comforted,
and signified that if it was the Lord`'s will to take her to himself she was content.
She was frequently engaged in secret prayer,
and desired to be left alone that she might meditate on God--observing afterwards,
that she enjoyed the streams of his love, but found the enemy so busy,
that it was hard to keep her mind stayed on the Lord.

She lamented the situation of those who lived in wickedness,
especially when they are brought on a death bed;
and sent a message to one of her acquaintance to take more care of her words and actions,
or she would find it hard work to die.
Alluding to her own temptations and conflicts, she said, "`I have had much trouble,
the enemy having been busy when I was in meetings,
so that I looked out sometimes and neglected the inward work,
for which I have known sorrow.

"`I have gone through nights of sorrow and prayer, but now I am made willing to die.
I shall go to a glorious place,
where there is no temptation or sorrow and where all tears shall be wiped from the eyes.
My spirit is comforted in the love of God; and if I had lived more in the fear of God,
I should have been more comforted.
The Lord has been good to me--I am willing to die--it has seemed hard to me sometimes,
yet now it is made easy.`"

On another occasion, she expressed,
"`All must be humbled and brought low one time or other--they must bow;
if they will not bow in mercy, they must in judgment.
It is well for me that I have been afflicted,
else I might not have known the things that belong to my peace; but now I cannot say,
I do not know them, for I do see them and rejoice in them.`"

Next morning, she expressed much concern on account of a near relation,
desiring that she might live in the fear of God;
and lamented the folly of those who lived in pride and spent much of their
precious time in adorning the poor body and walking wantonly.

She commemorated the Lord`'s goodness to her, saying, "`The Lord is a gracious God,
and of great mercy and righteousness, and I trust in Him.`"
One of her acquaintance being present, she gave her much pertinent advice,
particularly be watchful over her words and conduct,
and when in religious meetings to have her mind inward,
for God was to be worshipped in spirit and in truth;
and that as he had given her a measure of his grace,
she should serve him while in health, and not to put it off to a sick bed.

Soon after this, she prayed, "`O, Lord Jesus, receive my soul, if it be thy heavenly will.
I am truly resigned to thy will.
O Lord Jesus, come quickly, if it be thy heavenly will, and make my passage easy.
Send thy angel to conduct me to thy heavenly kingdom--O Lord, hear my prayer,
and grant my request if it be thy heavenly will; give me power over the enemy;
he is a cunning enemy, a subtle serpent--O Lord keep me from his temptations,
who lays his baits at every corner.`"
At another time, she observed, "`There is nothing to be compared to thy love;
all the world is but as a fading flower.
O, what will it avail a man to gain the whole world and lose his own soul?
What need have people to go with their heads so high,
when they must all be laid in the dust!
O Lord, thou art sweet,
thy countenance is comely--thou hast refreshed me
many a time when I have prayed unto thee;
O, that thou wouldst crown me with glory.
O, Lord Jesus, there is none like unto thee, the Author and Finisher of our faith,
to help when none else can.`"

The day before she died, she again bore testimony to the Lord`'s power and goodness,
saying, "`Lord,
thou art the great physician of value--the heavenly Physician who
canst do that which none else can--thou canst raise from the dead;
speak the word and it shall be done; thou art a gracious God,
of great mercy and full of righteousness--thy mercies
deserve to be had in everlasting remembrance.
O, Lord Jesus, thou hast tendered my spirit and humbled my soul;
thy works are too wonderful to be fully spoken of.`"

In the evening she appeared to be dying,
and took a solemn leave of all who were with her, observing to her aunt,
"`Now I am just going,`" and soon after, "`Come, Lord Jesus, come quickly;
into thy hands I render my soul`"--and so passed away without any struggle,
aged thirteen years wanting four days.

[.asterism]
'''

AMY ELIZABETH LLOYD, daughter of Samuel and Mary Lloyd, of Wednesbury, England,
was early visited by the grace of God, which oftentimes tendered her heart,
and drew her affections towards heaven and heavenly things.

The following extracts from a diary which she kept,
afford evidence that the Lord`'s voice is distinctly made known in the soul,
in very early years, and that He who said, "`Suffer the little children to come unto me,
and forbid them not,`" is still drawing the lambs unto himself.
The first is dated in her 10th year.

[.embedded-content-document]
--

First-day, first month 10th, 1840.
I felt very restless in meeting,
and it was with great difficulty that I could keep my thoughts to the Lord;
and I do not think, I altogether did so.

17th of fifth month.
I felt in meeting today the delightful meaning of these words,
'`Surely goodness and mercy shall follow me all the days of my
life.`' Oh that I might dwell in the house of the Lord forever.`"

No date.
I lately have not behaved well; I must pray to the Lord to be helped to obey him,
not only in the outward appearance, but in the inward also; and may God be with me.

1st of twelfth month.
I hope that I become a better child;
till lately I was not sensible of the blessings I receive.

It is first-day.
I could not keep my thoughts, in meeting; they roved away before I was aware of it;
but still I tried to wait patiently on the Lord.
Oh! that I were good and humble.
I ought to be thankful that I know the way to live forever in heaven,
singing praises to Him who died for us, and by whose stripes we are healed.

7th of twelfth month.
I hope the Lord will guide me;
for strait is the gate and narrow is the way that leadeth unto life eternal.

20th of twelfth month.
I have been very naughty.
I desire to feel thankful for the many blessings I enjoy.
O Lord, blot out all my sins from thy book;
make me clean through the blood of thy dear Son.

11th of ninth month, 1843.
Last first-day I read my diary through, and think I am more gone back than improved.
How to give myself wholly up to Christ, and let Him be all in all, I know not;
I should like to be a Christian today; but then,
instead of thinking that God must do the work, I attempt it myself,
and think I am so good.
I need God`'s help.
I know that he would help me.
Mother told me this should be our prayer, '`Lord, teach me to know myself and thee.`"

--

Her standard of holiness was high;
and consequently every departure in heart and every failure in her duty,
was deeply felt and deplored; and while others would have esteemed her very good,
her sensitive mind was the subject of much conflict and suffering from a sense of sin.

In the year 1842, she had a severe illness;
and though she recovered so as to resume her duties in the family and school,
yet some symptoms gave cause for serious apprehensions as to the result.
This had an evident effect in quickening her diligence in spiritual concerns,
and in her daily walk there was a constant reference to the things of eternity,
and the "`one thing needful`" appeared to be uppermost in her thoughts.
Her mother believing it best to inform her of her critical situation, the child replied,
"`I am glad thou told me.
I hope I shall feel differently before I die--more
of the love of Jesus brighter views of heaven,
and a clearer evidence that my sins are forgiven.`"

In alluding to her sufferings, she remarked, "`How light are they,
compared to his who bore the weight of our sins in his own body on the tree!`"
But while she fully acknowledged the truth,
and felt the preciousness of the Scripture doctrines respecting the coming,
propitiatory sufferings, and death of her dear Redeemer,
she was convinced that they could only bring consolation to the
soul by submitting to the work of the Holy Spirit in the heart,
so as to know them to be applied individually to herself,
and to feel the testimony of the Spirit,
bearing witness with her spirit that she was the Lord`'s.
She panted after the blessed experience of "`being justified
in the name of the Lord Jesus and by the Spirit of our God.
Subsequent to this period of inward exercise,
she was made sweetly sensible of the love of Jesus to her soul, in larger measure,
which caused her to pour forth the tribute of thanksgiving and praise in simple strains,
concluding with the following stanza:

[verse]
____
In thy presence, I am happy;
In thy presence I`'m secure;
In thy presence, all affliction
I can easily endure.
____

She was not forward to speak on sacred subjects;
though her mind evidently dwelt almost constantly upon them; she seemed sweetly at rest,
reposing in the Lord`'s will, whether it should be for life or death,
desiring to be wholly devoted to His service and glory who had done so much for her.
She still suffered at seasons from the buffetings of her soul`'s enemy,
but found the spirit of prayer an unfailing refuge;
and when her bodily weakness was so great that she could
not distinctly utter the breathings of her soul,
the recollection that the Lord knew and graciously
regarded the aspiration of the spirit toward Him,
was a source of comfort; and He who hears in secret was pleased to reward her openly,
by granting her such supplies of faith and patience,
as made her more than conqueror through Him who loved her.

Two days previous to her decease,
she repeated in feeble but melodious accents the following lines:

[verse]
____
How sweet to the soul are the breathings of peace,
When the still voice of pardon bids sorrow to cease!
When the welcome of mercy falls soft on the ear,
Come hither, ye laden,--ye weary, draw near.

There is rest for the soul that on Jesus relies;
There`'s a home for the homeless, prepared in the skies;
There`'s a joy in believing, a hope, and a stay;
Which the world cannot give, nor the world take away.

Oh! had I the wings of a dove; I would fly
And mount on the pinions of faith to the sky;
When the still and small breathings on earth that are given.
Shall be changed to the anthem and chorus of heaven.
____

The Solemn period of death being near, she called for one of her sisters,
and said to her "`These are the damps of death,
at least I think so.`" Her sister asked if she was happy;
to which she answered with much emphasis, "`Yes--I think I am--hope I am--trust I am.`"
To her younger sister she said, "`Annie, I am going to die; I am going to heaven.`"
A smile of tranquillity and peace rested on her countenance,
and when it was remarked to her how mercifully she was dealt with
in being permitted to pass away with so little pain or conflict,
she calmly said, "`Not yet.`"
The power of articulation had nearly failed,
but after her position had been a little adjusted, she asked in reference to it,
"`Am I right?`"
and soon gently departed under a holy peace and solemnity,
which extended to all around her bed,
and was a precious evidence that her Saviour was near to receive her into glory.
She died fifth month 1st, 1843, aged thirteen years.

[.asterism]
'''

THOMAS BURLING, of the city of New-York, was taken ill the 8th of 3rd month, 1790.
In the forepart of his sickness he appeared to be much concerned about his future happiness,
yet his mind was divinely supported under the trying dispensation,
and he was enabled to bear his sufferings with patience.
On seventh day morning he grew much worse, and observed to his aunt,
"`I believe I am going--dost thou not think so?`"
She did not reply directly to his question,
but inquired if he was willing to die--to which he readily answered,
"`Yes--and shall go to the Lord.`"
He then prayed that the Lord would be pleased to take him
and cause him to sit down with Him--observing afterwards,
"`He hath made my feet like hinds feet and set me on high places.`"

In a little while after this,
he prayed again with great fervency of spirit nearly as follows: "`O, blessed,
holy Father--thou that makest a way in the deep, and paths in the great waters;
if it be thy blessed will, with thy dear Son who gave himself for the world,
grant that I may witness thy light to shine on my tabernacle,
and join angels and archangels, who forever worship thee, in singing hallelujah,
with might, majesty and dominion; for thou art worthy, world without end-amen--amen.`"

One of his uncles coming in to see him, he said, "`thou hast been very kind to me,
I am going to leave thee`"--and added that he hoped shortly to be in heaven,
should it be the will of the Lord to allow him a seat in his heavenly mansions,
there to join in hallelujahs to his great name.

As there appeared to be no hope of his recovery,
he was anxious that his father should freely give him up, saying, "`Don`'t be uneasy,
father, about me`"--and soon after prayed again in a very affecting manner,
making use of expressions, of which until then, they scarcely supposed he had an idea.
One of his aunts offering him some drink, he looked at her with a composed countenance,
and said, "`I shall go before my cousin Benjamin,
+++[+++who was then supposed to be near his end:]
I little thought of being taken away at this time of life.`"
Soon after, "`O,
that I may be founded and grounded on the mighty Rock of
ages;`" and being filled with gratitude and praise,
he frequently prayed very earnestly and returned thanks unto the Lord, acknowledging,
with concern of mind, that he had not aforetime been so thankful as he ought,
for the many benefits and mercies he had received.

He was very affectionate to his attendants,
often expressing his concern for their religious welfare,
that they might be brought into true humility and obedience,
so as to worship God in spirit, who alone he said was worthy of all honour and glory.
Soon after this he prayed, "`Holy Father, if it be thy blessed will,
look down on thy poor servant this evening.`"
His strength was much exhausted by frequent speaking, and as his breath was very short,
it was proposed to him to lay as quiet as he could, to which he answered,
"`I cannot help acknowledging the many favours +++[+++which]
the Lord has bestowed on me.`"

His end being near, he expressed a wish to take leave of his connections,
which was a very solemn and affecting scene,--he took each one by the hand, saying,
"`Farewell--I am going--the Lord`'s will be done.`"
After this he continued praying and praising the Lord,
sometimes with a voice so clear and strong as to be heard into an adjoining room,
until his gradually declining strength appeared to be exhausted,
and he quietly departed the 13th of 3rd month, 1790, aged fourteen years.

Thus died this pious youth--exhibiting in his last moments
the blessed fruits of early dedication to the Lord`'s will,
and such fortitude of mind and resignation to the disposal of Infinite Wisdom,
as may serve for an instructive example, not only to the rising generation,
but also to those of mature years.

[.asterism]
'''

ANN REEVE, daughter of Mark Reeve, of Greenwich, New-Jersey,
deceased in the eighth month, 1778, aged fourteen years and six months.

Her disposition was amiable and social,
and her conduct adorned with modesty and gravity;--she was
industrious in her habits and particularly fond of reading,
in which she manifested a good judgment,
selecting such works as were useful and instructive.
She was an affectionate and obedient daughter,
careful to consult the wishes of her parents,
and to avoid everything which she apprehended might grieve them.
Towards her brothers, she acted with much kindness and prudence,
evincing an uncommon solicitude for their religious welfare.
In retirement and the society of her elder friends,
particularly such as were esteemed pious, she took great delight,
and though innocently cheerful and affable towards her youthful acquaintances,
she seldom went into much company.

When attacked with her last illness she manifested great composure of mind,
and expressed her willingness to die if she was prepared.
Her mother observing that she hoped she had been preserved in a good degree
of innocence and had not done any thing to make her uneasy,
she replied, "`Not so fully as I ought to have done--I see wherein I have been short;
but hope I may be forgiven.`"
On the next day, her father sitting by her and perceiving that she was under exercise,
inquired whether she thought she should get better--to which she readily replied,
"`No--I don`'t expect it.
Some days before I was taken sick I thought I should not live long.`"
Alluding to the death of her brother, who was buried a few days before, she said,
"`it was such an awakening alarm to me that I thought I should never forget it;
yet I found it began to wear off.
I think this season will never be forgotten by me if I should recover,
but I do not expect it.`"

At another time she said to her parents,
"`I have often thought it would be very hard for me to part with either of you,
and it is hard to leave you--there is a great duty due from children to their parents,
and I hope you will forgive me wherein I have fallen short.`"
Being answered that she had been very affectionate and dutiful, she continued,
"`It is very kind; but I see that I have been short,
and if I should live I would be much more affectionate and dutiful--I
have often desired that I might not live to dishonour you--it has
seemed to me that young people are ashamed of sobriety.`"
She then mentioned a young woman to whom she had spoken
respecting some part of her conduct which she did not approve,
and observed that she said there "`was no harm in it;`" adding,
"`Our young friends are accounting them little things,
but they will become serious things one day or other.`"

She desired her father to pray for her,
and her pain being very severe seemed almost ready to complain,
but quickly checked herself, saying, "`not my will be done.`"
Though favoured with remarkable patience,
yet such was her concern lest she should do any thin amiss, that she would often say,
"`I am afraid that am not patient enough--O, that my time was come;
but not my will be done.`"
A person present expressing a hope that she would
be supported through the pains of death,
though they were hard to bear, she replied,
"`they are very little to the pains of an endless eternity.`"
"`I hope,`" said her mother, "`thou art under no fear on that account.`"
"`There is one thing,`" answered the child, "`that lies heavy on my mind,
which I am ashamed to let my father and mother know.`"
Being desired to unbosom herself freely, she went on, "`I have been, of late,
sleepy in meetings sometimes,
and I am afraid I have not striven against it in such a manner as I ought.`"
After this acknowledgment she seemed relieved.
On the following day, her pain being very severe, she said, "`I long to go;
but not my will be done.`"
Toward night, her hands growing cold, and apprehending her change was near,
she observed with much composure,
"`It is hard work for the spirit to be separated from this house of clay,`"
and then took leave of the family in a calm and affectionate manner,
giving much good advice to her brothers, saying, "`Be loving and dutiful to your parents,
and as much as may be in your power make up for their
loss--be sure you never grieve them,
and by no means dishonour them in any part of your conduct.`"
After this she revived, and on second day, in a most moving manner,
conversed with her two brothers respecting their past conduct,
which had been trying to her mind; and in language dictated by heavenly love,
advised them respecting their duty towards God and their parents,
desiring that they might experience forgiveness for past offences,
and rightly improve the time to come,
and never dishonour their parents or be ashamed of sobriety,
which was too much the case amongst young people.
Soon after this she said,
"`I long for the time to come,`" and on fourth day night her spirit departed,
we doubt not, to a better inheritance.

[.asterism]
'''

ROBERT BOADLE, of Whitehaven, England, a youth of solid and serious deportment,
was taken sick in the 2nd month, 1824.
During his illness, he was preserved in patience,
so that although his sufferings were great, he was never heard to murmur.
He expressed to his mother, "`If it should please the Lord to take me now,
I hope I shall be happy,
and though the thoughts of a separation from you are very trying,
yet I trust we shall all meet again never to part.`"

His expressions were generally descriptive of the sense he had of his own unworthiness,
and his hope of acceptance through his blessed Redeemer,
and his countenance indicated the sweet serenity of his mind;
yet at seasons he was permitted to feel some discouragement; especially on one occasion,
when he expressed a fear that he was not fully prepared for his change.
He requested to have some portions of scripture read,
which was done--and after a time of silence, he said,
"`I feel comfort--the Lord has been good and gracious to me all along,
and surely he will not leave me now.`"
During the last two months of his life, he was drawn into much stillness;
he spoke very feelingly respecting some of his school fellows,
and wished they might be more thoughtful respecting their latter end, saying,
"`Death is awful:`" being in great pain he observed,
that "`if he only had an easy passage at last, he should not mind his present sufferings,
for they would soon be over, and then all will be joy forever.`"
"`O, said he, only to think of--forever.`"
He fell into a gentle sleep, during which his redeemed spirit took its departure,
there is no doubt, to the mansions of eternal peace.
He was 14 years old at the time of his decease.

[.asterism]
'''

PUTNAM F. LOCKE, was born in the county of Rutland, state of Vermont, in the year 1791.
In the 5th year of his age he was sent to school,
and being of quick apprehension soon learned to read.
It was his practice to rise early in the morning,
and the first object of attention was his book.
He took much pleasure in reading the holy scriptures
and became so well acquainted with their contents,
that when only seven years old he could immediately turn to almost any passage.
At about eight years of age he grew more serious,
manifested some anxiety about the state of his soul,
refrained from playing with his associates,
and spent his time mostly in reading the bible.
He lamented that boys should use profane language,
and would not associate with those who did so.

One morning he was found weeping, and inquiry being made as to the cause,
he answered that he had heard a voice which told
him he had not long to live in this world.
Many arguments were used to compose him, but in vain; he said,
"`I must lay aside all play and prepare for death.
What shall I do to be saved?
Will not the great God have mercy on my soul?
I will fall down on my knees and pray to Him that made me, to save me, lest I perish.
Let me die at the feet of Jesus, who died to save lost men.`"
He inquired of his mother if she was willing to part with him,
saying that if he should die, she would still have one son left to comfort her,
that God had the best right to us, and she must glorify Him by giving all up.`"

He also said "`I am determined to spend the few days I have in this world,
in praying and reading good books, not novels and romances,
for it may be very hurtful to me, who am but a child, to read any thing but the truth.
I am very young, but I must have a standard in my own breast.
I must never tell a lie--I must not allow myself to speak evil against any person.
If I have any thing against them, I must first go and tell them.
This practice would prevent much uneasiness in the world.
If we believe every story we hear,
we may not have as good an opinion of people as we ought.
We should be very careful of each other`'s character.`"

His disposition was sympathetic and charitable, and when he acquired a few pence,
he would cast in his mite for the relief of the poor.
He was of a mild and amiable temper, obedient and affectionate to his parents,
modest and respectful in his deportment to all,
patient and tender towards his companions,
and remarkable for his love to God and reverence of his great and holy name.

When in the ninth year of his age, he was one day left at home alone,
and on the return of his parents, he said to them, "`While alone by myself,
thinking how my mother had given me up to God,
I felt so happy that I fell on my knees in prayer,
and gave myself up to the service of the living God.
I have now set out to do everything +++[+++I can]
for his honour and glory.
May I never dishonour the cause of religion I resolve to read much
in my bible and avoid trifling conversation and vain amusements.`"

He manifested much solicitude for the education of children,
and having a good capacity for teaching, at the age of ten years he commenced a school,
which he continued for three summers in succession,
and was very successful in the employ.
Being taken ill, and the disorder increasing,
he was confirmed in the belief that his dissolution was near;
and having his loins girt about, rejoicing in the hope of a glorious immortality,
in his 15th year, he bid adieu to all things below, and his spirit, we trust,
ascended to God who gave it.
