== Chapter 6

[.chapter-synopsis]
* Deborah Emlen
* Lucy A. Pancoast
* Samuel Tomson
* Mary Scaif
* Alexander Hopwood
* Catharine Burling
* Rachel Moxham
* Ann Taylor
* Maria Mott

DEBORAH EMLEN, daughter of Samuel and Sarah Emlen, of the city of Philadelphia,
deceased the 16th of fifth month, 1789, aged about seventeen years.

In the beginning of the year 1788 her health began to decline,
and during a long and painful illness, the sweetness of her temper,
and the calmness and patience in which she was preserved,
evinced her entire resignation to divine disposal.
When any new remedy was proposed by her physicians,
she would generally express her doubts of its success,
but conclude with saying that if her friends desired it,
she would follow their directions.

One night when she saw that her physicians were at a loss what to do next,
she requested to know what her mother and aunt thought of her situation,
and after hearing their opinions, she said, "`I think myself in a very dangerous way,
more likely to die than recover.
I have no wish for either.
I feel resigned to the will of Him who best knows what is best.
If I should recover now, I must die sometime,
and pass through another painful tedious illness--but if I go now,
I shall escape many snares,
and temptations and sorrows that attend us in our passage through this life.
Though my connections are very dear to me, I feel no regret in leaving the world.
I never loved it as much as seems common at my age,
nor ever saw the charms in it that young people generally suppose.
I have not looked on myself as an inhabitant of it,
but as a traveller who was bound to another country.
When very young,
I often had serious thoughts on the importance of living so as to die in peace.`"

A few nights before her close, as her aunt was supporting her,
she alluded to her weak and helpless condition, and said, "`My dear aunt,
join me in prayer to the Almighty,
that he will be graciously pleased to take me out of the world.
I desire to be resigned, but if it is his will,
I had rather go--I trust he will receive me, for in him, and in Him alone,
I put my trust.`"

After a religious opportunity in her chamber, inquiry was made if she felt fatigued,
to which she replied, "`No--I should not have been,
if the visit had continued several hours, had I felt the same inward support.`"
Some time after, she told her aunt she never knew what perfect happiness was,
until that evening,
having a foretaste of that felicity which she was soon to enjoy forever.
On fifth-day morning, the 16th of fifth month, she grew much worse,
and gradually breathing shorter was happily released from all her sufferings,
and received into the arms of everlasting mercy.

[.asterism]
'''

As it is particularly interesting to trace the footsteps
of those who have given early evidences of piety,
and through obedience to the visitations of the love of Christ,
have been prepared to testify of his goodness to their souls,
it has been thought proper to preserve some account
of the last illness and death of LUCY A. PANCOAST.

It furnishes an instructive example of the blessed effects resulting from
an early dedication to the Lord and a submission to the power of his cross,
by which only, we can be redeemed from the corruptions of our fallen nature,
and prepared for an admittance into that glorious kingdom of peace and joy,
where nothing that is in the least degree impure or unholy, can ever enter.

She was the daughter of John and Ann Pancoast, of Springfield, New Jersey,
and from her childhood manifested a sweet and amiable disposition,
which qualified her to share in sympathetic feeling with her parents and family.
A striking instance of this occurred at a time when it pleased divine
Providence to permit a dispensation of great affliction to overtake them;
this precious child with unwearied attention and earnest solicitude
entered deeply into feeling with them and especially with her father,
who was reduced very low by severe illness.

Soon after his recovery, she was taken ill with a putrid sore throat,
and although from that time until she was attacked
with the illness which terminated her life,
her constitution gradually weakened,
yet it pleased her heavenly Parent so far to restore her,
that she mingled in the society of her friends for a few months.
On the 3rd of eleventh month 1816,
without having complained of being more unwell than usual,
she was seized with a fainting fit,
and from that time until her decease was confined to her bed.

She was an example of patience and resignation to
the divine will through the whole course of her sufferings,
never being heard to murmur,
though her pain was often extreme--yet such was her diffidence and humility,
that she several times expressed a fear of not being as patient as she ought to be.
Her mind was much exercised from the commencement of her
illness and desirous of quietness and retirement.

The second day after she was taken sick, her mother sitting by her bedside,
she affectionately took her hand and pressing it to her face, said in a solemn manner,
"`O, mother--dear mother,
pray for me--but pray that the Lord`'s will may be done respecting me`"--and
several times when she supposed all in the room were asleep,
she was heard to repeat, with uplifted hands, "`Thy will be done.`"
She often desired that her parents would not grieve for her, saying,
"`I love you dearly--very dear you have been to me, and never more so than at this time.
I find it a great thing to be entirely resigned to the Lord`'s will,
which has been my constant endeavour for some time.`"

She once observed "`Oh! what a trying time when brought upon a death bed.`"
Seeing her parents in tears, she said, "`do not grieve,
the Lord`'s will must be done--you feel for me, but I dare not let my mind dwell on you,
for I feel that I have need of all my strength,
and of your prayers in this trying time.`"

About the second week of her illness she requested that her parents,
brothers and sisters might be called, and affectionately kissed each of them,
after which she lay still for several hours; an impressive silence prevailed around,
and when any one approached her she gently waved her hand for all to be still.
While in this peaceful and quiet state of mind, the doctor came in and aroused her,
she looked at him expressively and said, "`O, doctor why didst thou disturb me?
I have had such a taste of happiness, real happiness,
the most pure I ever enjoyed`"--and spoke in a moving manner
of the mercy and goodness of the Lord to her.

On third-day the 12th, she was affected with delirium,
and continued so at intervals until sixth-day morning;
though during a part of that time she knew most of those around her,
appeared very sweet and composed, and expressed great love for all,
inquired if she had been impatient, or said any thing improper,
tenderly desiring her friends to excuse it if she should, and observed,
"`at times I know not what I do.`"

About 6 o`'clock on seventh-day morning,
her attendants were apprehensive that she was departing and called the family.
On entering the room, they found her engaged in supplication in a clear, audible voice,
saying, "`O Lord, thy will be done.
I have no will but thine.
Wilt thou, O Lord, forgive a poor repentant sinner and take me to thyself.`"
Presently after she looked around the room and asked, "`are you all here;
I want to see you all.`"
Her sisters and brothers going to her, she addressed them separately with much affection,
saying; "`I am very happy, and do not know that I shall be taken very soon,
but am wholly resigned to my heavenly Father`'s will`"--then addressing her Creator,
added, "`I have no will but thine; Oh!
I love thee, dearly love thee; I wanted only thee.`"
She remarked that her prayers had been daily offered for a long time past,
though they had sometimes been short and imperfectly uttered, such as,
"`Lord make me wholly thine.`"

After this she spoke to her parents,
particularly desiring her father not to have his
attention so taken up with worldly concerns,
as to cause him to neglect the diligent attendance of week-day meetings.
Then turning to her sister, she said, "`My dear sister,
pray daily to the Lord--dress plain; it will be a comfort to thee on thy dying bed--Oh,
how often when my head has been laid on my pillow, have my prayers been +++[+++put up]
for you.`"
To impress her words more fully on the minds of her younger brothers and sisters,
she took them in her arms and kissed them, saying,
"`Sister is going to die and wants you to remember to pray;
never close your eyes to sleep without it.`"

She requested an opportunity with the persons employed in the kitchen,
who having been called in, she took several of them by the hand,
and imparted suitable advice to them.
To one she said, "`Pray to the Lord to forgive thee;
it is a dreadful thing to die in an unprepared state;
a dreadful thing to be brought upon a dying bed and no Saviour to look to.`"
After a pause she repeated the Lord`'s prayer, and in a little time, the following lines:

"`Great God! thy name be blessed,

Thy goodness be adored;

My soul has been distressed,

But thou hast peace restored.`"

Several times during the course of the day she said--"`Thy will be done.
I have no other,`" which indeed appeared to be the
constant breathing of her redeemed spirit.
On seventh-day night the 16th of the month, she desired her parents might be called,
and appearing entirely sensible,
her countenance replete with tender affection and her voice solemn and melodious,
she said, "`I have been twice this night with the Lord my Saviour,
who said he would take me to himself.`"
She then entreated her parents to give her up, saying,
"`I know your love for me is great,
but it is not to be compared to the love of my heavenly Father.`"
Her parents replying that they would endeavour to resign her to Him who gave her,
she seemed filled with joy, clasped her arms around her mother`'s neck and said, "`O,
take me to thy bosom until my Saviour comes.
O mother, I have always loved thee dearly,
but feel now as if I loved thee more than ever.`"

On first-day evening, her dissolution seemed to be fast approaching;
she frequently put up her prayers with great fervency,
calling upon her dear Lord and Saviour, saying, "`I have sacrificed all for thee,
my dearest Saviour.`"
A few minutes before her close she was distinctly heard to utter these words,
"`I am willing--I am willing--dearest--Father--which art in--heaven--blessed Saviour.`"
Soon after this she quietly departed, on the 17th of eleventh month, 1816,
aged seventeen years;
and we have no doubt her ransomed spirit joined that innumerable company, who,
having washed their robes and made them white in the blood of the Lamb,
are continually before the throne of God, saying with a loud voice,
Worthy is the Lamb that was slain, to receive power and riches, and wisdom, and strength,
and honour, and glory,
and blessing--for thou wast slain and hast redeemed us unto God by thy blood.`"

[.asterism]
'''

SAMUEL TOMSON was the son of William Bridge Tomson, of Mepal in Cambridgeshire, England.
Though he was preserved from many of the evils to which the young are exposed, yet,
about eighteen months before his death,
he was greatly afflicted under a sense of condemnation for past sins;
and the consciousness that he had not paid proper attention to
the counsel of his parents became a source of heartfelt sorrow.
He sent for his father and expressed to him his uneasiness
at having acted contrary to the wishes of his parents,
desiring that he might be forgiven by them.
He appeared to be relieved by thus disclosing his feelings,
and earnestly sought the forgiveness of his heavenly Father,
under strong conviction of mind, exclaiming,
"`Oh! that I might witness my salvation sealed this night.`"

During the time of his illness,
many of his expressions evinced that the Lord was instructing him by his Holy Spirit,
and that in adorable condescension the purification of the soul was going forward.
"`What a comfort,`" he remarked on one occasion, "`it is to have such parents,
and to be so cared for.
I now perceive that many young persons are not enough
sensible of the advantage of such care.`"

At such an awful period,
when death is about to separate them from the society of their beloved parents,
what an unspeakable consolation must it be to children to feel the sustaining
evidence that they have honoured and obeyed them while in health;
and cheerfully submitted to the instructions of those who were endeavouring
to lead their tender minds in the ways of religion and virtue,
and to fix their hopes of eternal felicity,
on that redemption which comes by Jesus Christ our Lord.

Speaking of his bodily affliction, he said, "`Though my sufferings are great;
what are they when compared with what our Saviour endured when he bore the sins of mankind.`"
Afterwards, being in extreme pain, he repeatedly and fervently supplicated,
"`O gracious Saviour, be pleased to relieve me,`" and his prayer appeared to be answered,
for shortly after he was permitted to experience considerable alleviation.

A sense of this favour continued to be a source of
consolation and encouragement to his mind,
and he would often say, "`How comfortable do I feel,
both in body and mind--what a favour to be so free from pain.`"
He laid awake many hours of the night,
and spent much time in grateful commemoration of
the mercy and goodness of his heavenly Father,
who graciously vouchsafed his sustaining presence-being firmly persuaded
that nothing short of this could have afforded him such sweet peace.

He delighted in meditation, and in reading and reflecting upon the holy scriptures;
and his apartment being near that of his parents,
they were often comforted by hearing him engaged in vocal prayer during the night.
One morning requesting his father to come to him,
he mentioned that he had been remarkably refreshed in spirit, during the preceding night,
and added, "`Now, I could wish to be released,
but desire patiently to wait the appointed time.`"

Sometime afterwards he observed, "`Oh! what a consolation to poor sinners,
that Jesus Christ came into the world to save the chiefest,`" adding,
"`It is well for me that I was afflicted--before I was afflicted I went astray.`"
He inquired where that portion of scripture was, which says,
"`Where the wicked cease from troubling and the weary
are at rest`"--and his question being answered,
he said with much sweetness, "`I shall soon be there, mother.`"

About thirty-six hours before his departure he lost the power of speech,
but the calm and peaceful expression of his countenance indicated a mind already
enjoying a foretaste of that unspeakable felicity which shall be revealed hereafter.
He died at the age of seventeen, on the 2nd of the fourth month, 1824.

[.asterism]
'''

MARY SCAIF was taken ill at the same time, and with the same disease as her sister,
of whom some account has been given at page 81 of this work,
and survived her about two weeks.
During their sickness, her sister was under much concern on Mary`'s account,
and frequently engaged in supplication to God,
that he would be pleased to make her acquainted with his peace.
And in due time, He who keepeth covenant and sheweth mercy,
was pleased to break in upon her soul by his holy Spirit,
and give her a clear understanding of spiritual things.
Under the influence of this divine visitation,
she broke forth in supplication on this wise, "`O great God--Jehovah of heaven and earth;
whose splendor filleth heaven and thy wonders fill the earth, have mercy upon me,
thine handmaid, who am as a worm before thee,
yet a part of thy creation--Lord help my weak--revive my drooping spirit,
by thy consolating presence; strengthen my faith, I beseech thee,
and keep me through this exercise.
I beseech thee, Lord, that thy will may be done in earth as it is done in heaven.`"

From early life she had been fond of reading the holy Scriptures,
and often spoke of the experience of David, Job and others of the Lord`'s servants;
"`and now, said she, I do know God`'s love to be the same to me as it was to them;
so that I am neither afraid nor unwilling to die,
for God blotteth out my transgressions and lays nothing to my charge.
I believe there is a place prepared for me in heaven.
And dear mother, do what thy canst not to sorrow--my love is great to thee,
and my advice is,
that you go and live near some meeting and bring up my brother amongst friends.`"
She spoke of her death as being near,
and expressed an assurance that her spirit would ascend to God in heaven.
Her illness increasing, she departed this life aged eighteen years.

[.asterism]
'''

ALEXANDER HOPWOOD, was the son of Samuel and Ann Hopwood, of Austle,
in the county of Cornwall, England.
His parents being pious persons,
who were more concerned for the spiritual welfare
of their son than for his worldly interest,
endeavoured to give him a religious education,
and to inform his mind respecting the great truths of christianity,
and under the divine blessing their christian care in these respects
was the means of preserving him from those vices with which the
minds of too many of the youth are ensnared.

In the year 1732, he accompanied his father to London, in which journey,
as well as during his stay in the city,
the Lord was pleased to renew the visitation of his love to his soul,
and give him an increased knowledge of heavenly things.

After his return home, he was frequently indisposed, and on the 1st of the seventh month,
was seized with a violent fever.
On the following day he observed to his mother, "`If the Lord is pleased to take me,
I am fully satisfied.
I shall go well, my soul will be happy, and have a place amongst the righteous.`"

The day before he departed, being filled with the love of God,
which seemed to raise him above the feeling of bodily weakness,
he broke forth in fervent supplication to this effect,
"`O Lord! thou that preservedst Shadrach, Meshach and Abednego in the fiery furnace,
art able to preserve me unto the end.
O God, what shall my soul say?
I will wrestle with thee like Jacob,
if I pray all night--if thou wilt not make me like him, give me +++[+++at least]
an evidence of favour with thee; whether I live or die, give me a place within thy house.
Lord, if thou art pleased to spare my life,
I will obey thy commands in any thing thou art pleased to require of me.`"

Soon after this, his father was engaged in vocal prayer by his bed side,
which tended to comfort and strengthen the mind of the dying youth;
and through the Lord`'s goodness he received an evidence
of that favour which his soul longed for,
under a grateful sense whereof he returned praises and thanks to the Most High, saying,
"`O Lord, what shall my soul say?
I have not breath to praise thee, O my God; but I will do it as long as it it lasts.`"

After a little pause, he said he believed he must take leave of his relations,
which he did with much affection and tenderness,
and then desired of the Lord that if it was not his
will to give him longer time in this world,
he would be pleased to grant him a quick and easy passage,
which petition was mercifully answered.
He passed away on the following morning without sigh or groan,
and we have no doubt obtained an admittance into the kingdom of heaven.
Aged about eighteen years.

[.asterism]
'''

CATHARINE BURLING, daughter of John and Ann Burling, of the city of New York,
was taken ill of a fever which gradually weakened her strength and brought her down,
to use her own expressions, step by step to the borders of the grave.
Her recovery being considered doubtful,
she was introduced into close conflict respecting her future state,
and earnest were her prayers to God for a little longer time,
that through the effectual operation of his transforming grace,
she might come to witness a preparation for er final change.
And He who is rich in mercy to those that call upon him in humble faith,
was graciously pleased to hear and answer her petition.
She experienced the great work of regeneration to be accomplished,
and being created anew in Christ Jesus, was prepared to say,
"`My mind is like a little child`'s.`" In the aboundings
of the love of God shed abroad in her heart,
she was enabled to "`publish with the voice of thanksgiving,
and to tell of all the wondrous works,`" which her Saviour had wrought for her soul.
She also frequently exhorted those who came to see her, "`to amendment of life,
that when they came to lay on a sick bed,
they might enjoy that peace which she was then made a partaker of,`" saying,
"`She felt the Lord`'s peace flow in her mind like a gentle stream,
and that her cup run over.`"

On another occasion she observed, "`Many wearisome nights have I gone through,
in which I have watered my pillow with my tears.
I was long in doubt of my eternal happiness;
and in the time of my greatest distress I cried to the Lord
that he would be pleased to lengthen my time a little,
that I might be more fully prepared;
and he was graciously pleased to hear and grant my request.
And now he has been pleased to grant me a full assurance of +++[+++my eternal happiness,]
and to lengthen my time, that I might speak of his goodness to others,
and tell what he has done for my soul.
Oh! praises--praises--praises--be given to his great and glorious name.
Oh! if I had the tongue of an angel,
I could not sufficiently express my gratitude to the gracious God,
who has been thus pleased to favour me in so eminent a manner.`"

Again, she said, "`My disorder is very changeable; very flattering it would be to some,
but it does not flatter me.
I am resigned to the Lord`'s will; let him do just as best pleaseth him with me,
his poor frail creature.
A few days ago, when I thought myself just launching into eternity,
the boundless ocean of eternity--I prayed to the Lord that
he would be pleased to give me a little longer time,
and he was graciously pleased to hear and grant my request.
The work of regeneration is a great work; I know it now experimentally.
I am become a new creature, new thoughts, new desires;
my affections set upon things above;
I have a new name written in the Lamb`'s book of life,
and the white stone is given to me.`"

She advised her brothers and sisters to plainness of speech and apparel, saying,
"`Remember our blessed Lord, that great pattern of plainness; who,
when on earth went up and down doing good, and wore a garment without a seam.
He was crucified;
he was nailed to the cross for our sins--for my sins--Oh! love inexpressible.`"

Having, through adorable mercy,
experienced the necessary work of purification and
being transformed by the renewing of her mind,
it pleased the Lord to permit her ransomed spirit to partake of the joys of his salvation;
and during the last five weeks of her life,
she was often engaged in thankful commemoration of the spiritual favours she received,
saying, "`I have nothing to do with this world;
Oh! let my time be employed in praising the Lord,
and telling of his gracious dealings with my soul.`"

As her father was sitting by her bed side one evening, she said to him,
"`Thou art my father; but now I have another.
I have an heavenly Father.
I love thee dearly, but I love Him much more.
Oh! he is the chiefest of ten thousands.`"
She would frequently say "`I am thankful to the Lord for all his favours conferred on me.
When I do not speak, I am thankful in my heart, and that is more than words.
The Lord does not require lip honour; but when my heart is filled,
I cannot help speaking.`"

At another time she observed, "`Many are the changes and vicissitudes I experience,
and what may come next none of us knows;
but I am resigned and thankful for all His mercies to his poor frail creature.
He must do with me just as he pleases; we should be thankful for all the Lord`'s favours.
I hope and pray that I may be kept thankful and humble, meek and low before Him,
waiting for my change; and a happy change it will be for me.`"

One morning, as her mother and sisters were dressing her, she desired them to stop,
and thus expressed herself,
"`I now no longer wonder that the martyrs could sing in the flames.
I could do the same.
I think I could go through burning flames, if required, for the love of Christ:
Oh! it is inexpressible.`"

On another occasion, she spoke to the following import;
"`Now I know how precious the soul is Oh! that people would prize their time,
and prepare while health is granted them.
I bless the Lord, I am prepared, if he is pleased to call me the next moment, I am ready;
but I am thankful for the little time he has granted me to be with you.
Oh! how shocking! how horribly shocking,
must it be for those poor souls who are unprepared,
and deprived of their senses at such a time as this!`"

She warned many young people at different times against reading romances and idle books,
saying, "`It has been a great trouble and exercise of mind to me,
more than any thing I have done.
It has caused me many a wearisome night and many a bitter tear,
though I have never read but a few, and those that were deemed the most harmless.
I know there are some who deem them innocent amusements,
and say these books are instructive, and that there are good morals in them.
But Oh! must we go to such books for good morals?
Read the scriptures, which are the best of all books;
and there are other good books beside.`"

A person who was accustomed to a seafaring life, coming into the room,
after a few minutes pause, she thus addressed him,
"`Thou art one that saileth on the great waters,
and there thou mayest see God`'s wonders in the great deeps--and
thou art much in company with sailors and such like men,
who are light and frothy in their conversation.
I desire thee to keep thy mind watchful, and near the Lord, which if thou doest,
thou wilt be preserved in his fear.`"

One evening she called her little brothers to her and embraced them very affectionately,
and being then removed to the bed side, she said, "`Oh!
I am full of love.
I feel a degree of divine love.`"
A person in the room remarking how easy and composed her countenance was, she replied,
"`How can my countenance be sad when my mind is at peace,`" the person adding,
"`Which the world cannot give,`" she rejoined "`No-nor take away.`"

Two of the neighbours coming in, she addressed one of them, saying,
"`Thou seest me very weak and low but my mind is at peace--sweet, heavenly peace.
I hope and pray that thou mayest feel the same when thou comest to lie on a sick bed.`"

The day before her departure,
she desired her sister to inform their mother that "`she was resigned;
patiently waiting and quietly hoping for her happy change;`" and soon after, remarked,
"`I feel as if I am going to Paradise`"--which blessed anticipation was soon realized.
She deceased the 16th of the fourth month, 1764, in the eighteenth year of her age.

[.asterism]
'''

RACHEL MOXHAM, daughter of John and Esther Moxham, of Melksham, Wiltshire, England,
was naturally of an amiable, social temper and fond of company, on which account,
her pious mother thought it needful to watch over and restrain her.
About the fifteenth year of her age,
it was observed that religious impressions had fastened on her mind; she became sedate,
loved retirement, and through the operation of the Spirit of Christ,
was mercifully taught how to wait on the Lord, and what to wait for.

One evening, after an opportunity of silent, mental introversion,
she said to her mother nearly as follows,
"`I have thought it my duty to thank thee for thy care in
preventing and restraining me from unsuitable company,
which I took hardly, and I believe if I had had the liberty I coveted,
I should not have known the peace and comfort I now feel,
in obedience to the principles of truth,
but should have gone into the broad road that leadeth to death.`"

She continued to be serious and steady in her deportment,
looking towards the eternal recompense of reward, and a few days before her decease,
expressed a desire to attend the Quarterly Meeting.
On this occasion,
a minister spoke of the uncertainty of time and the
comfort of having hope toward God in a dying hour.
This communication she took to herself,
and in the evening said that "`her work was nearly finished.`"

The Quarterly Meeting occurred on second-day; and on sixth-day morning following,
she complained of illness.
In about two hours, her parents were so apprehensive of danger, as to be much affected,
which she observed and said, do not grieve for me, but rejoice evermore;
and give thanks that I am going to everlasting rest,`" adding,
"`I hope`"--paused a moment, and then repeated,
"`I am going to everlasting rest and peace.`"

She mentioned to a friend the presentiment she had of her departure,
and "`her hope that the Almighty would be near and
sustain the spirits of her parents under the trial,
as he did hers at that time.`"
She then settled herself quietly in bed, took leave of her friends,
and under the influence of a sweet and awful solemnity,
which tendered the hearts of those present, departed to her rest in Jesus;
no words being spoken, except her saying, "`Lord, receive my spirit.`"
She died after about eight hours illness, on the 20th of the third month, 1772,
aged nearly eighteen years.

[.asterism]
'''

ANN TAYLOR, who died at Manchester, England, the 7th of the fourth month, 1806,
was the daughter of John and Ann Taylor of that place.
She received the principal part of her education at home,
and during the latter part of her time was mostly
occupied in the acquirement of useful learning,
under the care of her father`'s second wife.
The following interesting particulars respecting
the final illness of this pious young woman,
will show that the tender care extended to her, had not been in vain.

On fourth-day, the 25th of ninth month, 1805, she was much affected in meeting,
under the ministry of a friend who remarked in the course of his communication,
"`Day after day--week succeeding week--and year after year, pass away,
and what preparation is made for our latter end?`"
The awakening consideration "`Am I ready for the awful change?`"
deeply impressed her mind.
At the close of the meeting she attended a corpse to the graveyard,
and although then apparently in good health,
had a strong belief that her own interment would follow before long.
On the succeeding seventh-day she was attacked with a spitting of blood,
which confined her to the bed for several days,
and excited some apprehensions in her mind, lest she should be removed from time,
before the work of preparation was completed.
In about two weeks, however, she so far recovered as to be able to go about the house.

A short time after this partial amendment, the disease returned,
and she appeared under much distress saying, "`I don`'t yet feel sufficiently prepared.`"
She was asked whether any particular offence stood in her way, to which she replied,
"`I don`'t know of any thing but a want of attention--not
having my thoughts turned inward whilst in meetings,
which I now see has been a great loss to me.
By suffering my mind to ramble, I have wasted much precious time,
surely it is playing the hypocrite--seeing this to be the case, I resolved,
when last at meeting, that if permitted to go there again,
I would be more careful and diligent, but I now believe I shall never go more.`"

It being remarked that it was a great favour to be brought
to see where we had omitted or committed anything,
contrary to our known duty, she replied, "`Yes, mother--and I hope to be very careful,
every way,
during the little time allotted me here--all things are
possible with Him who knows what is best for us.`"
She was often employed in taking a retrospect of
her past life and strictly scrutinizing her conduct,
and on one occasion she observed, in allusion to it,
"`I never knowingly told a falsehood; which now affords me great peace.`"

She expressed a tender concern for several young
persons who belonged to the same meeting with herself,
saying, "`I believe if some of them were laid on a sick bed as I am,
they would see the folly of pursuing +++[+++with avidity]
any thing but that which is most likely to fit them
for an inheritance in the kingdom of heaven.
Oh! how pure must all be that enter there.
There are too few, when young, and in health,
who think deeply enough of their latter end.`"

During the many returns of the disorder which she had,
her mind was favoured in a remarkable manner with patience and resignation.
"`It is the Lord`'s doing,`" she would say,
"`let him do what he will-I know it is for my refinement,
and if I had a greater evidence of going well,
I could leave all earthly things with joy--for it will be but a little
time before those I leave behind me must go also--yet I hope my great
Master will favour me with patience and resignation to wait his time.`"
Her mother expressing her belief that a clearer assurance
of divine acceptance would be vouchsafed before her close,
she replied, "`Then I want nothing more, but shall be happy.`"

One evening she said, "`I fear I have not loved my Maker so much as I ought,
which may be the cause of his presence being so long withdrawn, now in my affliction.`"
As a source of consolation to her tried mind,
her mother remarked that the patience and resignation with which she was favoured,
came not from man--she rejoined, "`I hope to be preserved from murmuring,
for that would be unwise;
and I give myself up entirely into my Maker`'s hands to do with me as he sees best.`"

She evinced great compassion for those of her fellow creatures
whose situation excluded them from enjoying the comforts,
or even the common necessaries of life: "`How much, said she, have I to be thankful for,
in being provided with everything needful to relieve my bodily suffering,
and also with affectionate attendance.
There seems very little ground to hope for my recovery, yet it is not impossible,
and if I should be restored to health,
the rest of my days shall be spent to the honour of a merciful Creator;
but I have but little prospect of ever getting much better.`"

A relation calling to see her, remarked her exemplary patience,
and that he should think it a great favour to experience the same precious resignation,
when near his close.
After he had left her, she said, "`I cannot expect to be rewarded like him.
He has given up much; but what have I done to look for any reward?
What crosses have I taken up for Christ`'s sake?`"
It was observed that she had denied herself many gratifications,
which were deemed by the world, innocent and allowable; she answered,
"`Yes--because I considered myself only a steward over everything I possessed,
and believed it wrong to indulge in anything that would take up too much of my time,
or fill my mind with what was unprofitable;
and though I never felt uneasy with any part of my dress,
yet I now believe it right to make clothing in a manner that will take up the least time;
convenience and cleanliness should be +++[+++principally]
looked to in apparel, for it is vanity to adorn these poor bodies that are but dust.`"

Observing her mother weep, she repeated several times,
in an earnest and affectionate manner, "`Don`'t shed tears for me;
I am going well,`" and after some further conversation, observed,
"`Thou knowest it is said, in my Father`'s house there are many mansions;
and if I get to one of the very lowest, I shall be content.`"
She desired a friend in the room not to be so affected, for she should soon be happy,
and her mother confirming this, by the expression of a similar belief,
she said with a tenderness and a melody that can only be felt,
"`Yes--Mother--yes--I shall be happy, and I hope thou and I shall meet there together.`"

It being thought that her end was near, the family were called, and soon after,
she bade each individual farewell, and in a distinct manner said, "`And now, O Father,
if it be thy will, take me quickly;`" then breathed shorter,
until about 7 o`'clock in the morning, when her ransomed spirit entered into rest.
She was eighteen years old.

[.asterism]
'''

MARIA MOTT, daughter of Richard and Abigail Mott, of Mamaroneck,
in the state of New York, deceased the 7th of twelfth month, 1816, aged eighteen years.

In early life she exhibited traces of an active and vigorous mind,
and being naturally of an amiable and affectionate temper,
the pleasing anticipation was indulged that under the sanctifying power of divine grace,
those gifts of the understanding would, in after time,
become devoted to the service of the blessed Giver.
As she advanced in years,
the vivacity of her disposition and the prevalence
of the natural will were observed to be increasing,
and proofs were soon given that they would require the watchful
and religious care of her parents properly to regulate them.
Under the divine blessing, however,
the judicious endeavours used to convince her judgment of the impropriety of wrong things,
and the satisfaction and advantages resulting from correct conduct,
were happily successful,
and her parents had the comfort of seeing her increase
in stability and religious thoughtfulness.

About the tenth year of her age,
she was favoured with the renewed visitations of divine love,
which produced obvious and lasting impressions on her mind; she became more attentive,
affectionate and docile in her manners,
regarding the feelings and admonition of her parents with such scrupulous tenderness,
that they have no recollection of her committing any act afterwards
which she knew would be disagreeable to them.

In the spring of 1815 her parents being about to leave home for a few weeks,
she observed to her mother, "`Though it is much against our inclination to part with you,
as we feel the loss of your company very much,
yet I hope you will not be anxious about home in your absence;
for I think we endeavour to be as careful of our conduct as when you are with us,
and to manage the affairs of the family, as nearly as we can,
in a manner which we suppose would be agreeable to you;
it is our practice to have the family collected,
and to read the Scriptures as you do when at home.`"

Being furnished with books adapted to her age,
she acquired a taste and fondness for reading; selecting her books with much care,
and avoiding such as were not instructive,
or which she knew her parents would not approve.
Though fond of history and works on moral and literary subjects,
yet she delighted most in those of a religious character,
which she read with deep interest.
She was well acquainted with the history of the Society of Friends,
and with the writings of some of its most distinguished members,
and often made pertinent remarks upon their sufferings and faithfulness,
in support of their religious principles.

She highly estimated that kind of conversation which
tends to inform and improve the human mind,
and regretted that so much of the time of young persons, when in company,
was wasted in trifling amusements and converse.
A few months previous to her dissolution,
conversing with her mother and an intimate friend
on the benefits and design of social life,
she remarked,
"`I have often regretted that so much precious time should
be spent to so little purpose as it appears to be.
I fear in some places, the practice is increasing,
of young people collected in companies, amusing themselves with various kinds of play,
which appear to me not calculated to promote real happiness or enjoyment,
nor is such an employment of time suited to that dignity of character,
after which we all ought to aspire.`"

Having been trained to habits of industry,
she was fond of useful employment and willing to
render assistance in such business as was necessary;
and being prompted by her sympathy and commiseration for the wants of the suffering poor,
she sought and embraced opportunities of relieving that class in the neighbourhood;
frequently employing her needle to render them comfortable
during the inclement season of the year.
Her benevolent mind derived much satisfaction from these works of charity,
and she would often remark that time passed pleasantly while thus occupied.

In the eleventh month she accompanied her parents and two of their friends,
in a journey to Dutchess County.
She had been fond of attending religious meetings from her childhood,
often spoke of the nature and importance of the duty,
and was an example of becoming sobriety in them;
and she appeared grateful for the opportunity thus
afforded her of attending those held by these friends.
From her subsequent remarks,
it is evident that serious and profitable impressions were
made upon her mind during the course of this visit,
and some time after her return, she observed to her mother,
"`In time past I had a strong inclination to have some articles
of clothing different from those I had been accustomed to,
and observing that many girls of my acquaintance were in
the practice of curling the hair on the forehead,
I was inclined to take the same liberty.
But as I reflected that father and thou would be uneasy with it,
that it would grieve you,
I became sensible that I could have no substantial enjoyment in it;
for I could never feel happy, or enjoy true satisfaction in any thing,
how much soever I have desired it, which I knew would be unpleasant to you.
And it has sometimes been rather difficult to submit cheerfully to your wishes,
peace and satisfaction have always been the result of a ready compliance--and that to
a much greater degree than I could possibly have experienced from a contrary procedure.
My views however, are much changed--I have not any wish for such things now.`"

After a pause, she added,
"`It is a great favour to have religious and concerned parents and care-takers;
and I have sometimes wondered how it can be that young people who have such,
can find enjoyment or even be satisfied, in the use of things disagreeable to them.
Their views of happiness must be very different from mine.`"

On fifth-day evening, the 28th of eleventh month, she became unwell,
and the progress of the disease was so rapid,
that before morning it had assumed a very serious aspect.

Her sufferings throughout the course of her illness were extreme,
yet her mind was mercifully preserved calm and composed;
and she evinced a degree of patient resignation which Divine grace only could confer.
The severity of the pain did not diminish the kindness and affection of her manner,
nor prevent her from acknowledging with gratitude,
the tenderness and attention of those who waited on her.

On second-day, the physician apprehended that the drink she took, promoted vomiting,
and thought it necessary to withhold it from her.
The thirst occasioned by a high fever, so far from producing a murmur,
seemed only to excite her commiseration for those
whose sufferings she supposed must resemble her own,
observing,
"`I have frequently thought of those people who traverse the deserts of Arabia,
parching with thirst,
and without water--but I have never until now been
in a situation fully to sympathise with them:
I apprehend that my tongue and throat are now in such a situation as to
give me a pretty correct idea of the distress and suffering under which
they must languish when water fails them in that burning clime.`"

Shortly after this, she adverted to the religious communication of a friend,
in the family, and said to her mother,
"`How often I have thought of what our friend said to me on the morning he left us;
"`Maria, dear Maria--whatever trials or afflictions may be thy lot,
keep hold of the covenant thou hast made.
I have endeavoured to do so previous to my sickness,
and will still strive to do it--but ah! how little did I think
that I should so soon be brought to a situation like this.
It is very desirable to have the mind composed,
but it is not easily attained when the body is tortured with pain.`"

On seventh-day morning, having passed the previous day and night in extreme suffering,
one of her parents remarked the necessity there was for resignation to the divine will,
to which she replied with much serenity,
"`I have earnestly wished for it--I know the Lord
is good--I felt his goodness this morning,
and it was precious to me; and I then thought I was resigned either to live or die,
as it should please him.`"

About 10 o`'clock she said, "`My dear parents, I weaken very fast,
and think I shall not last long.`"
Her father remarked that he hoped she was resigned; she answered, "`Yes--I think I am,
and I hope that you, my dear parents, will endeavour to be so too.
I have very often been sensible of the kindness of the Lord to me.
I do not see any thing in the way of my happiness,
and though I have not always been as faithful as I ought to have been,
and fear that I have sometimes been rather too much inclined to levity,
yet I have been favoured with many precious seasons and divine visitations.`"

To a young woman for whom she entertained a strong attachment, she said,
"`I shall not stay long--but I think I am quite willing to go.
I have always loved you, +++[+++meaning the family]
but I never felt it so strongly as I have done many times during my present sickness.`"

Being partially relieved from extreme suffering, she gratefully acknowledged it,
and her redeemed spirit appearing to be raised above all transitory things,
she thus addressed her parents and brother,
"`I have been desiring that we might have a solemn opportunity together before I die,
but I have been so distressed with pain for some hours past,
that it has been difficult to have my mind composed or my thoughts properly directed.
This morning I had a sweet assurance that my peace
was made--but during the extremity of my suffering,
I have sometimes been almost ready to doubt.
I am now thankful to feel it renewed--yes,
to feel an assurance that there is a resting place
for me in heaven--and to be admitted into bliss,
is all I wish--all I ought to desire.
I do not ask for a high mansion--I have done but little, and am not entitled to one.
My hope is in the Lord`'s mercy: I have always loved you, but I never felt the force,
nor understood the nature of love, as during this illness.`"
"`I can`'t say much--I am but a child and have done but little for the truth,
yet I hope I have not done it harm.
I have endeavoured to be a good example,
and I know not that I have committed any flagrant sins.`"

She added, "`Some persons have said--I think Dr. Johnson said,
he did not believe that people felt what they said,
when they spoke of their willingness to die;
but I feel it to be true when I say that I am willing to die,
and many others have known it to be true.`"

A fear being expressed lest she should exhaust herself by speaking, she replied, "`Yes,
my dear father, I am almost exhausted; but I feel such a flow of love--love to all,
that I cannot refrain from expressing it.`"
"`If it were the Lord`'s will,
it is probable I might have a choice in continuing a little longer in this world.
I have many strong attachments--such precious parents, and a dear brother.
Oh! how dear they are to me! but if it is his will to take me away,
I am willing to go--yes, this very night.`"
A little after she said,
"`I think I have been favoured to keep hold of the covenant;`"--and
looking on those who were sitting by,
her countenance beaming with sweetness and resignation, she said,
"`I am going to the Lord and hope you will follow me.`"

About nine in the evening, her bodily distress being very great, she said,
"`My dear father, I cannot last long--I think I shall not live through this night.
May the Lord be with us all--with me who am going, and with you who stay.`"
After this the violence of her pain,
and the restlessness produced by the irritability of the nervous system subsided,
and she became quite calm.
A solemn and impressive silence prevailed in the room, when she said,
"`I shall soon go`" "`I long to be gone;`" and remarking
that her voice began to grow tremulous and fail,
she calmly added,
"`I will lay me down to die--the fear of the Lord
is round about to preserve us--yes--to preserve all.`"
She laid perfectly still, as if in a sweet slumber, and gently resigning her breath,
her ransomed and purified spirit took its flight to the mansions of eternal glory,
to join the just of all generations in ascribing "`Salvation to the Lamb, forevermore.`"
