== Chapter 8

[.chapter-synopsis]
* George Newland
* William Young
* Abigail Knight
* Potto Brown
* Hannah Maria Miles
* Sarah Beckwith
* Ann Leaver
* Mary Pooly
* Richard Hunter

GEORGE NEWLAND, son of George and Susannah Newland, of the city of Dublin,
died the 24th of eighth month 1708, in the nineteenth year of his age,
a minister of the gospel, about six years.

He was favoured with the tendering visitations of the love of Christ when quite a child,
and yielding his will and affections in submission thereto,
he became an example of love and obedience to his parents,
and of a circumspect and orderly deportment.
Such was the tenderness of his conscience,
and the fear which rested on his spirit of offending the Almighty,
that if at any time he was persuaded by his school-fellows to be rude and wild,
although perhaps not more so than many would esteem innocent,
he was afterwards under trouble of mind therefor.

As he continued in this state of watchfulness and fear, he grew in grace,
his conduct evincing that he was "`seeking another and a better country, that is,
an heavenly;`" and about the twelfth year of his age,
it pleased the Head of the church to call him to the ministry of the gospel,
and enable him "`to publish with the voice of thanksgiving and
tell of all the wondrous works`" which the Lord had done for him.
In the exercise of the gift bestowed upon him,
he travelled in most of the provinces of Ireland,
and though endued with a good understanding and solid experience,
he was careful not to utter words without feeling
the Holy Spirit to move and assist him therein,
so that his ministry was pertinent and edifying.
He was greatly beloved by those among whom he travelled,
because of his exemplary conversation and conduct,
which were in conformity with the doctrine and precepts of our Lord Jesus Christ.

In the nineteenth year of his age, he was visited with a lingering illness,
and being asked if he thought he should recover, replied, "`He did not know,
but if it was the Lord`'s will, he had rather die than live,
but durst not desire it,`" adding, that "`although his time had been short in the world,
he had gone through a great deal of exercise and
trouble that none knew but the Lord alone.`"
On another occasion he remarked to his mother,
"`I have felt more of the Lord`'s love to me since I was sick, in a wonderful manner,
than ever before.
I strove to serve the Lord in my health and now I reap the benefit of it.
I can look forward +++[+++with peace]
and that is a mercy.`"

He was frequently comforted and filled with the love of God,
under the sense of which he would exclaim, "`O, if the earnest be so precious,
what will the fulness be!`"
As his bodily weakness increased,
he was strengthened in spirit to magnify and praise
the excellent and worthy name of the Lord.

Taking his brother affectionately by the hand, he kissed him, and said,
"`I love thee dearly--be sure thou fear and serve the Lord,
and be obedient to thy parents; for though thou be young and strong now,
yet thou knowest not how few thy days may be.
I speak to thee in love.
Remember my dying words when I am gone,
and that it will be enough when in a dying condition,
to bear the pain and affliction of body, without having a troubled conscience.`"
He manifested the same tender and brotherly concern for his sisters,
recommending to them,
to "`Love and fear the Lord and be dutiful to their parents;`" and added, "`In my health,
when I went to bed, I did meditate and think upon the Lord, and now in my sickness,
I find the benefit thereof.`"

He gratefully acknowledged the love and care of his parents, observing, "`If I live,
I can never make you amends for your trouble and
care over me,`" and afterwards said to his mother,
"`I hope the Lord will reward thee for all thy trouble and care over me,
and that we shall meet shortly, where we shall never part again.`"
Some hours before his departure, being overcome with the goodness of God to his soul,
he broke forth in humble admiration, saying, "`How good, Lord, art thou to me.
I am not worthy of the least of all thy mercies and favours`"--and continued
praising the Lord in a remarkable manner until near his end.
Being sensible this was near, he desired all to be still,
and in a triumphant state of mind quietly departed to everlasting glory.

In contemplating the peaceful termination of a life
so pure and so devoted to the service of God,
who but must exclaim in the language of Holy Scripture,
"`Let me die the death of the righteous, and let my last end be like his.`"
It is however well for us to remember that we can have no
solid hope of dying a death so glorious and triumphant,
unless we are engaged to live a life of self-denial and holiness unto the Lord.
We must experience the new birth unto righteousness,
and our sins to be washed away in the atoning blood of the Son of God;
who died for us--not that we might live to ourselves,
in the indulgence of the evil propensities of our fallen and corrupt nature,
and in the pursuit of those things which the controversy of God is against, but that,
through the power of the daily cross,
we should live unto Him who died for us and rose again, having our fruit unto holiness,
the end whereof is everlasting life, through Jesus Christ our Lord.

The following testimony concerning George Newland was given by Friends in Dublin, viz:

[.embedded-content-document.testimony]
--

It pleased the Lord to favour this youth with a gracious visitation,
even in his childhood, and so to prepare him for his service whereunto he appointed him,
that there appeared deep impressions of a concerned
mind for the good and eternal well-being of his soul;
and as he grew in years, he grew in grace and in the knowledge of God and his Son,
the Lord Jesus Christ--so that the Lord was pleased to put him into the ministry,
although young, and he being sensible of the appearance of the Son of God in his heart,
did deliver his testimony with a good understanding,
not being forward or rash to utter words,
but waited for that which is the fountain of all true ministry, viz:
the help of the spirit of God, that enables God`'s ministers to speak,
to the instructing and building up of one another in the love of God.

And this being the concern of this innocent youth,
made him to be beloved of faithful friends that knew him, and the more so,
because his conversation agreed with his doctrine.

He went abroad sometimes to visit friends in the province of Leinster,
and was also in Ulster and Munster provinces,
and friends generally had a love and respect for him,
and there would commonly be great meetings where he was,
both friends and others admiring the Lord`'s dealings with him, in his tender years,
being but about twelve years old when his mouth was first
opened in meetings in a testimony for God.

We have a great loss of him, he being such a good example to our youth,
both in that and also in his conversation,
too few being willing to follow him in that true nearness of walking with God,
as he did--but love liberty to the flesh and will,
that work not the righteousness of God,
but bring trouble and grief on those who are concerned
for the well-being of their immortal souls.
His behaviour was more like a man of gray hairs, than one not attained to nineteen years.

He was not desirous of long life in this world, as he used to express sometimes;
but rather that he might do his days`' work,
being ready and prepared when the Lord was pleased to call him hence, to have a portion,
in God`'s kingdom, of that life and peace which is everlasting.
And when he was visited with the sickness of which he died,
which continued on him about a quarter of a year,
he bore it with much patience and resignation to the will of God, and very cheerfully,
which was comfortable both to his parents and friends
that visited him in the time of his illness.

Before his departure he was concerned to advise his
brother and sisters to fear and love God,
and be dutiful to their parents, etc.

Though it is our loss to have such an one taken from us, we believe it is his gain,
to be removed from where trouble and temptations attend,
to where the wicked cease from troubling and the weary are at rest.

From our Meeting in Dublin, the 19th of the second month,
1709--And signed on behalf of the said meeting by,

[.signed-section-signature]
Amos Strattell, Richard Sealey, George Rook.

--

[.asterism]
'''

WILLIAM YOUNG, of Leominster in the county of Hereford,
possessed a sprightly and amiable disposition, and although of a delicate constitution,
appeared to enjoy good health,
until he contracted a cold which terminated in consumption.
While labouring under this afflicting, though flattering malady,
he became more thoughtful and grave in his deportment,
and frequently made sensible remarks on the uncertainty of all temporal prospects,
expressing,
also a grateful sense of the many kindnesses received from a gracious Providence.

Although he had been preserved through life,
in greater innocency and purity than most young men,
yet he now saw that this alone would not entitle him to
a participation in the felicity of the redeemed.
He was therefore earnestly desirous of experiencing that entire renovation of heart
which is produced by the washing of regeneration and the renewing of the Holy Ghost.
His anxious solicitude on this subject gave rise to many painful conflicts,
and he often lamented having lost that tenderness and fervency
of spirit which he formerly experienced.

But God,
who is long suffering and full of compassion "`and keepeth
mercy for thousands`" of them that fear his name,
did not leave his wrestling spirit in this uncertain and painful state.
In his own time,
he was pleased to grant him a full assurance of salvation and enable
him to sing of mercy as well as of judgment.

Some weeks before his decease, being apprehensive that his end was near, he observed,
"`If I die now in my youth, it may be all for the best,
and may put other young people upon the consideration of their latter end.`"
His father expressing a desire that they might be resigned to the divine will,
although it would be hard to part with him, he replied with much earnestness, "`Aye,
do be resigned--let us all be resigned,`" and frequently remarked
it was his wish to be resigned either to life or death,
but added, "`If it pleased the Lord to fit him for his change,
and take him from the slippery paths of life at so early a period,
he should think it a favour,
for he had no desire to live except it was to the glory of his Creator.`"

He several times expressed the deep sense he had
of the wonderful condescension and goodness of Christ,
in suffering for mankind; and observing his sister weep, said to her,
"`We must part--I must leave you--but I hope and believe that we shall meet again.`"

The 2nd of the first month 1773, he was very ill, and seeing his father affected,
he said, "`O father,
what a mercy will it be if the Lord should be pleased to take me to himself.
Do not grieve--if I should be spared and turn out naught,
it would be a greater affliction.`"
Thus did his affectionate and sympathising mind endeavour to alleviate
the sorrow of those whom he was shortly to leave,
and to reconcile them to the dispensations of an unerring and merciful Providence.

The next morning, having had a very poor night, he was weak and low,
but appeared peaceful in mind.
His sister expressing a hope that he was resigned, he replied with much sweetness, "`Yes,
sister, I hope I am quite resigned to the Almighty`'s will.
Surely, if it be his will, it will be a mercy to be taken from this troublesome world,
to himself;
and I have a hope he will take me to himself--he hath been pleased wonderfully
to calm my mind.`". She observed there was ground to hope,
and that the sufferings of his friends would be greatest.
"`Oh! said he very earnestly, my sufferings will be nothing in proportion to my offences,
but I have a hope my offences will be forgiven.
Oh! how merciful is the Lord! how great is his goodness--how pure is his love!
Mercy, goodness, purity, belong to him.`"
His sister being much affected during this conversation, he continued, "`We cannot tell,
sister, some worse than I, +++[+++as to health]
have been restored.
He is able to raise me up, and if he should,
and make me some sort of a member +++[+++of his church],
I hope I shall be careful to keep near to him, but I desire not to live--no,
not a moment, as one of this world.`"

On the following morning, he was in great pain, and told his sister he was going;
she added, "`I hope to a better inheritance;`" he replied, "`Aye,
for I believe in one that can save me,`" and repeatedly said,
"`The fear of death is taken away.`"
Afterwards, "`I am going to leave an affectionate father,
to meet the great Almighty Father.`"
It being observed that it was a favour he was preserved so patient, he said,
"`I hope I shall be kept so.
I am under the Lord`'s care entirely--nothing else will do.
I see nothing else will do.`"

His mind seemed remarkably clothed with love--a sweet
and peaceful serenity prevailed in his chamber,
and though his voice was so weak that his words were not always intelligible,
yet it was evident that he was enjoying "`the peace of God which passeth the understanding.`"
Being asked if he wished any message conveyed to his absent sister, he replied,
"`Nothing but love`"--adding, "`In that love I feel for all.`"
He several times desired those about him not to grieve, saying,
"`If you think I am going well, why should you grieve?`"
He took a most affectionate leave of his sister,
recommending her "`to love and adore the Lord`"--and shortly after,
put off mortality so quietly that his attendants thought he had fallen asleep.
He slept in Jesus--and "`as we believe that Jesus died and arose again,
so them also that sleep in Jesus, God will bring with him,
and they shall ever be with the Lord.`"

He died on the 7th day of the first month, 1773, in the nineteenth year of his age.

[.asterism]
'''

ABIGAIL KNIGHT, of Messing, in Essex, England,
being taken with an illness which threatened her life,
her father tenderly acquainted her with the danger she was in;
and although she seemed willing to die if she could feel prepared for the awful change,
yet she was brought under great distress of mind respecting her future happiness,
and strong convictions for having done many things which she knew were wrong,
and neglected the affectionate counsel which her father had frequently given her.

In a private interview with her father,
she told him of the condemnation she felt for attending religious meetings so carelessly,--that
she thought it was mockery to sit in such an indifferent state of mind,
and suffer the things of the world to engross the attention,
for which she thought she had felt as much uneasiness,
as for any thing she had done amiss.
That when at times she had endeavoured to gather
her mind home to the consideration of heavenly things,
the enemy obstructed it, and she found herself so weak,
through unwatchfulness at other times,
that she was not able to withstand his temptations.
This conversation seemed to afford her some relief.
She expressed a hope that her sins would be forgiven,
and although she did not feel the fear of death,
yet she wished to be favoured with a clearer evidence
of acceptance before her departure.

Observing that the day was very fine,
she said it reminded her of the expressions of one who remarked,
"`How gloriously the outward sun doth shine!
So doth the Sun of righteousness shine this day upon my soul!`"
which she thought she could in measure adopt as her own;
the things which had stood in her way having been gradually removed.
She remarked to her sister, "`If I had my time to spend over again,
I should spend it very differently.
If I may have the least place in the kingdom of heaven, it is all I desire--and this,
I think will be granted.`"

Sometime after, she said, "`I believe I shall be happy, I feel so easy in my mind.
What a fine thing it is to have peace of mind upon
a dying bed--the nearer I am to the close,
the more easy and clear my way seems.
I do not dread death--but seem as though I could meet it with a smile.`"
This happy change in her feelings she gratefully acknowledged
as a favour for which she could not be sufficiently thankful,
and as her death drew near, she said the sting of it was taken away, pleasantly adding,
"`I think tomorrow or next day will finish here.`"

The following morning her father going to speak to her, she appeared very calm,
said she loved to be still, and felt her heavenly Father near, as an arm underneath,
and admired the goodness and mercy of the Almighty,
in removing those things which had been in her way.
About ten o`'clock, being taken with the pains of death,
she besought the Lord to grant her patience to bear them,
and just before her departure said,
"`Lord Jesus receive my spirit--Lord--take me to thyself.
Farewell--all--in the Lord--my pain will soon be over--the gates
of heaven are open to receive me--the time is almost come.`"
She died on the 24th of the second month 1794, in the nineteenth year of her age.

[.asterism]
'''

POTTO BROWN, was born at Earith in Huntingdonshire, the 16th of the fifth month, 1765.
He discovered in early youth a serious turn of mind,
which being cherished by his parents,
as he advanced towards manhood the seed of the kingdom sprung up in his heart,
producing those blessed fruits of the Spirit, the end whereof is everlasting life.
He was a good example in his words and actions,
nand was generally beloved by his acquaintance.

In a letter addressed to a youth with whom he had
formed an intimate acquaintance at school,
he says,

[.embedded-content-document.letter]
--

I hope as we travel on through this transitory state,
we shall be enabled to cast the cares of this world behind us,
looking to the Author of all good, who will help all those who trust in Him, I believe,
beyond all doubt, that all those who trust in Him, will not lack the bread of life.

--

The following extracts from a diary which he kept,
may serve to evince the state of his mind, as well as furnish instruction to the reader.

[quote]
____
Eleventh month, 9th, 1783.
The Lord showed me to my great comfort,
that my dependence must be on him--so that I began
to inquire how it stood with me and my God.
Then I was humbled to cry "`Help me, O Lord, or I perish.`"
The word +++[+++to me]
was, "`Draw nigh unto God, and He will draw nigh unto thee.`"
Then I began to meditate on the Lord in the night season,
and was greatly refreshed thereby.
A voice passed through me, saying,
"`Thou must not have any conversation but what may profit thy soul,
for unto that man that ordereth his conversation aright will I shew my salvation.
Thy mind must be set on heavenly things, and thy conversation on heaven.`"

Eleventh month, 29th. For the last three days nothing material has occurred.
But glory be to our God, for he hath dealt wonderfully with his servant.
I cannot express the comfort I have had in keeping
to the operation of the Word of life in my own heart.
The Lord hath showed unto me the pure state in which our primitive friends stood;
and also the fallen state of many among us at this day, which is to be mourned by me.
He will not be mocked by men of low degree, who set their minds on earthly enjoyments,
and think not on the name of the Lord.
He has given every man ability to know that he is a just God,
who dwelleth in the heavens,
and those that will serve Him must set their minds on heaven,
whence they shall receive their help.
Those who are heavenly shall declare his name to all generations,
to the convincement of thousands that the Lord is God.
Blessed be his name, saith my soul, for taking me by the hand,
and leading me out of the paths of vanity!
May I be enabled to evince, by my words and actions,
that in conversation the Lord is to be praised, and honoured in stillness.
____

Soon after this, it pleased the Lord to call him to the work of the gospel ministry,
being in the eighteenth year of his age.
In allusion to his entering upon this awful engagement,
he says in a letter to his mother,

[.embedded-content-document.letter]
--

The Lord hath been pleased to pluck my feet out of the miry clay,
and to open my mouth to make known his will amongst his people.
I hope it will ever be my care to keep near him,
as I have experienced a drawing near of the Lord to me.
My heart is broken and contrited, blessed be his holy name.
Oh! entreat my brothers from me, to follow after the Lord in purity and holiness,
and to wait for his counsel.
Oh! that I could express the hundredth part of what I feel in being
renewed in his counsel! but I must leave them to the Lord.

--

[quote]
____
The 2nd of the twelfth month.
This day a cloud covered me, and a temptation wounded my soul.
I was drawn to consider how the Lord pardoned the thief on the cross,
and to make it a cloak for trusting to a dying hour--but
I felt the rod that chastised me,
and heard a voice, saying, "`How camest thou to take thought against thy God?
He will not be slighted, but looked unto with a single heart for help.`'

The 11th. I found, during my late journey, that while my mind was turned inward,
His presence was with me.
I was preserved in the truth, to my inexpressible comfort--O may I always keep watch,
lest the enemy draw my mind from being stayed on the Lord.

The 17th. Many are the temptations which the enemy lays to draw my mind from the Lord.
But, look thou, O my soul, to the Lord,
with unfeigned sincerity and with full purpose of heart,
in the humility of that Spirit which enlightens thee
and strengthens thee against them all.

The 4th of the first month, 1784.
This day I went to Littleport meeting, where I spoke a few words.
Oh! how I felt the Lord with me this day--blessed be his name.
Many were the breathings of my soul,
that the Lord would keep his fear always before my eyes,
that I might not speak a word but to his honour.
Oh! that it was the care of all those who profess with us,
that nothing might be done but to the glory of God--that
we might say '`Thine is the kingdom,
the power, and the glory, forever.
Then should we answer our high and holy calling.

The 17th of the second month.
This day in my retired thoughts I was made sensible how much we
ought to keep ourselves in humble reverence to our God,
under a consciousness of His omniscience and our nothingness.
Oh! if people would but behold their dependency on Him,
they would be afraid of having their minds taken from under his protection; much more,
of doing any thing that would not tend to his glory--but on the other hand,
they would testify against everything of a contrary tendency,
knowing that God is jealous of his honour,
and will be sought unto with fear and trembling.
David saith, Ps. lxxvi.) '`Thou, even thou art to be feared,
and who may stand in thy sight when once thou art angry.`'

The 19th. This day was a day of hard labour to me,
because I was off my guard last night, by entering into a long and needless discourse,
which drew my mind from the Lord.
But he was good to me and heard me when I cried;
for my spirit was bowed down in humility before him--and
heavenly joy abounded when I confessed my error to Him.
This is an evil into which many of our society fall who have been religiously inclined.

The 9th of the third month.
I saw I could not be in such a humble state as l had been called to come into,
without I became as clay in the hands of the great Potter.
I saw that my body was to be the temple of the Holy Ghost,
and that no defiling thing must lodge within me.

The 16th of the fourth month.
I find that the more I give up my mind to seek the kingdom of God and his righteousness,
the more I advance in the work; the more I keep in the power, the stronger I grow.
My soul longeth for the living God--yea, my inward cry is raised for the bread of life,
more than the natural man hungereth after natural food.
____

This appears to be the last entry made in his journal; shortly after,
his health began to decline, and symptoms of pulmonary consumption ensued.
He was removed from his master`'s to his father`'s house,
that he might try the effect of a change of air,
but the disease baffled every course of treatment.
He was enabled through divine assistance to bear
his long and painful illness with becoming resignation;
his mind appearing to be supported above the fear of death.
His mother asking him if he did not perceive that he grew weaker,
he answered with as much cheerfulness as though he had been in perfect health, "`Yes,
I know I am; but what matter?
If the outward man grows weaker, the inward man grows stronger.
I experience the strengthening of the new man every day.`"

At another time, being in great pain, he said he could not bear too much,
considering how much Christ bore for him.
His father observing him to be sad,
inquired if he was under any doubt as to his future state.
He said "`No,
he had many comfortable assurances that it would
be well with him`"--then bursting into tears,
he remarked that "`his uneasiness was on account of his brothers,
fearing they might be drawn away from the truth.`"
Being asked how he was, he replied that "`he was very ill, but did not wish to live,
nor did he think it his place to pray for death.`"
He continued in this resigned and composed state of mind,
and calmly departed to the kingdom of eternal blessedness, the 16th of the tenth month,
1784, aged nineteen years.

[.asterism]
'''

HANNAH MARIA MILES, daughter of Robert and Hannah Miles, of Melbury Abbotts, Shaftsbury,
Dorsetshire, England, was born in the year 1787,
and from her childhood was serious and orderly in her conduct.

About the nineteenth year of her age, she was attacked with pulmonary consumption,
which gradually reduced her and finally terminated in her dissolution.
In the early part of her illness, she seemed fully aware that she should not recover,
observing, "`I am very unwell and believe I shall not recover,
but shall have a lingering illness.
I should not mind it, if I had spent my time better;
for I have seen enough of this world, not to wish to live any longer in it,
if I had true peace of mind.
I have given way to many hurtful things; such as dress,
not so consistent as it ought to have been--likewise reading +++[+++improper]
books, which,
if it have no other bad tendency takes up that time which may be better employed.
I sincerely hope that our family may be careful to
avoid those hurtful and hindering things,
and not put off the great work until sickness comes.
I have had many good meetings and precious visitations,
but too soon forgot them,`" adding,
"`It is some satisfaction to me that I have been
preserved from talking much when in company,
but I have nothing to boast.`"

The concern and distress of her mind continued for some time, but through divine mercy,
she was preserved from desponding,
and at length obtained that evidence of pardon and
acceptance for which she ardently longed.
She informed her mother that the command to her, seemed to be, "`Watch and pray,
lest ye enter into temptation,`" and there is cause to believe
she was enabled in good measure to observe it.
For some weeks she said but little by way of religious communication,
but was much engaged in inward retirement and waiting upon God.
"`I have reason to be thankful, said she, on one occasion,
that I was not taken away suddenly.
If I had been--I fear it would have been bad for me.`"

Reading the Scriptures was her daily practice and delight,
and through the enlightening influences of the Holy Spirit,
they were profitably opened and experimentally sealed on her understanding.
In this state of humble reverent dependence upon the Lord, she patiently continued:
and after having been brought very low, by a violent bleeding from the nose,
she remarked to her sister, "`I thought I should have gone before now,
but I seem a little recovered for the present, but it will not be long.`"
To her elder brothers, she said, "`O, brothers,
I hope you will seek the Lord in time of health, for it is a great blessing.
I have a great love for you: I may be taken away suddenly,
but I hope you will remember what I have said to you.`"
Her aunt coming into the room, she thus addressed her, "`Thou dost not shun a sick house,
but it may be best for thee;
it is better to go to the house of mourning than to the
house of feasting;`" then speaking to those about her,
added, "`Seek the Lord,
for it is not such a very hard thing--seek ye him and he will be found of you.`"

Some days after, she was visited by her grandfather to whom she spoke as follows, "`O,
my dear grandfather, do thou seek the Lord God, for he is very merciful:
Thou art an old man, and ought to be prepared, for there are so many sudden deaths,
that we know not how soon we may be taken.
Do thou prepare to meet me in heaven.`"
After a short silence she was assisted to kneel down,
and prayed for her grandfather and other relations;
on rising from her knees she seemed refreshed and comforted by this religious exercise.

Awaking from uneasy slumber, one evening, she prayed with great fervour, "`O Lord,
do thou protect me, and preserve me, under the afflictions of the body.
O Lord, thou knowest thou art dear to me; and if it be thy blessed will,
take me to thyself, from the various pains and tribulations of this life.
Yet, not my will, but thine be done, O Lord.`"
Her parents expressing their desire to be enabled freely to give her up,
painful as the separation would be,
and their hope that her mind was favoured with resignation, she replied, "`Yes,
I have given you all up, for '`they that love father or mother more than me,
are not worthy of me.`"
Yet I have had a hard struggle with myself, to give up such near and dear relations.`"

Apprehending that her change was near, she prayed thus:
"`O Lord! do thou be pleased to take me this night if it be thy will,
and grant me an easy passage out of this world to the next.
O, Lord, I pray thee take me to thyself whilst my lamp is burning,
that I may not be like the foolish ones, who, when the Bridegroom came,
found their lamps gone out.`"

After taking an affectionate and solemn farewell of some present,
she again interceded for an easy passage to the realms of bliss,
and a pause of stillness ensuing, she broke forth, in holy joy, "`Oh! it seems to me,
I see the angels walk in white robes!
O death, where is thy sting!
O grave, where is thy victory!
What hath Jesus done for poor sinners!
He bled and died for us.
Oh! what sweetness have I felt in my affliction;
that peace which nothing in this world can give or take away.
Sometime since, I thought I felt something like peace, but it was not the true rest,
for I was then in a doubting state, but when I came to believe,
no tongue can describe the sweetness I felt.`"

Finding herself extremely weak and scarcely equal to the exertion of speaking,
she said to those about her, "`Pray for me,
for my weakness is so great that I fear I shall not
be able to pray for myself`"--and presently after,
"`Oh! the enemy will be busy--but I hope my patience will hold out to the end.
My trust is in the Lord.`"

Her cough having left her, the difficulty of breathing increased,
and articulation was so weak and indistinct,
that she could scarcely be understood--She began to say,
"`The Lord is my staff`"--but the rest of the sentence could not be heard.
The approach of death was now rapid--she took a small portion of drink,
and with a look of sweet expression, said,
"`no more`"--then desired all to be very still, and giving one hand to her mother,
reclined her head on the other, and thus drew her last breath,
as gently as the infant sinks to slumber.

[.asterism]
'''

SARAH BECKWITH, of Audborough, in Yorkshire,
was from childhood sober and grave in her deportment,
not addicted to light or trifling conversation,
but demeaned herself as one who was watchful lest she should offend the Lord,
or be an improper example to others.
To her parents she was obedient and affectionate, kind and courteous to all,
and sincerely devoted to serve the Lord,
and seek the kingdom of heaven and the righteousness thereof.
She loved retirement, and frequently when the employment of the day was over,
would walk alone in the fields, to commune with the Lord and sing his praises.

In her last illness she was afflicted with shortness of breath,
but yet was anxious to declare the goodness of God to her soul,
often praying that he would "`enable her to praise Him while she lived.`"
A few days before her decease obtaining some relief, she desired to be raised up in bed,
and spoke largely of the tender dealings of the Lord with her,
desiring those who were young to prize their time,
seeing they knew not how few their days might be.
"`Many,`" said she, "`are the temptations of the enemy, especially to youth,
presenting length of days,
to persuade them that it is soon enough to trouble themselves with such a concern.
So he would have persuaded me, and many ways was I tempted,
which caused me such exercises that I was brought nigh to despair.
I sought the Lord night and day--no ear heard me but the Lord alone, who heard my call,
and afterwards gave me a comfortable assurance of
my salvation--but the enemy has been very busy,
and sorely bruised me since the beginning of this illness.`"

Afterwards she prayed thus: "`O Lord,
give me full assurance of my salvation before I depart hence.
Let not my distemper overcome my senses until I come to a full enjoyment--I
pray thee let not my desires cease until thou answerest them,
and let nothing quench thy love in my heart.`"

It pleased the Lord, in the riches of his mercy, to hear and answer her petition,
and so to fill her soul with the consolations of the gospel,
that she sung praises to his great and worthy name.

She earnestly entreated her sisters to fear and love the Lord above all,
and to keep in the Truth--saying, "`Oh! press after it,
to feel the working of it in your own hearts, and when you are in it, keep in it,
and under the government of it--heed not to deck yourselves, but be meek and lowly.
None ought to pride themselves on any endowment, either beauty or any other thing,
because it is not theirs, but the Lord`'s, who gave it to them,
and can take it away when he pleaseth,`" adding, "`What is all now to me.`"

Speaking of some professors of religion who had grown
careless and were taking improper liberties,
she remarked, "`Such are ill examples to those who are coming up.
There are many who profess the truth, that little know what truth is.
It does not consist only in coming to meetings, wearing plain apparel and the like,
unless they come to feel the operation of Truth +++[+++the Spirit of Christ,]
in their hearts.
For all such outward appearances will stand in no stead,
without the love of God is inwardly felt and enjoyed.
It is an easy thing to come to meetings,
and some are ready to think that doing so and behaving themselves soberly, is sufficient,
but the Lord seeth at all times and he will have no such mockery--I bless God,
I have not been guilty of seeming to be what I was not.`"

She often gratefully acknowledged the love and mercies of God, and her own unworthiness,
saying,
"`It is not for my deserts--for I have nothing to engage
the Lord with--it is his free love to me`"--again,
"`There is man`'s righteousness, and the righteousness of God;
but man`'s righteousness must be rent off,
and man covered with the righteousness of Christ Jesus, who said,
"`I lead in the way of righteousness, in the midst of the paths of judgment,
that I may cause those that love me to inherit substance.`"

Speaking of the way of the cross,
which leads to the possession of a crown of eternal glory, she observed,
"`It is a strait and narrow way, and not to be kept in without a daily watch.
But although a strait way, yet it is a pleasant path and delightsome.
Oh! there is peace in abundance!
It is so sweet, I could delight always to enjoy it,
and to live therein--gold is not worthy to be compared to it.`"
Her mind continued to be employed in the contemplation and enjoyment of heavenly things,
and on one occasion she broke forth in this manner, "`Lord,
give me to drink fully of the well of water that is within the gate--for
thou hast touched my heart and I am overcome with thy love.
Oh, I long--I long--O Lord, open thou the windows of heaven,
and pour out thy blessings into my soul until there be no
room to receive--that I may bless and praise thy name.`"

Her dissolution was now near; and looking upon those about her, she said,
"`I am as sensible as any of you--and I am well content to die.
I have no doubt of my salvation.`"
Soon after, she added,
"`Lord--take me away--Lord--take me away`"--and presently
departed out of this state of being,
to live forever with the Lord.

[.asterism]
'''

ANN LEAVER, daughter of John and Mary Leaver, of Nottingham, being taken unwell,
expressed her apprehension that she should not be continued
long--that the prospect of eternity was very awful;
and although she had not been guilty of any great crime,
yet she had found it difficult when at meeting to get to that steady
watchfulness and settled composure which she longed for;
and the sense of her deficiency in this respect was a trouble to her.
Yet she gratefully acknowledged her thankfulness for the precious
opportunities she had sometimes been favoured with in the family,
and was supported by the secret hope that her sins would be forgiven;
praying earnestly for patience to endure the trying dispensation she had to pass through,
and for a clear evidence that her close would be
happy--which through adorable mercy was granted her.

"`How awful`" said she on one occasion, "`to look at eternity!
Few young people in time of health,
think so much of their latter end as they ought to do,
though they have as much cause as those further advanced,
having no more certainty of life.`"
Again, "`Those who are taken away in youth,
escape many snares and temptations that such as live
longer are in danger to be hurt by.`"
Several times she expressed her gratitude for the last weeks illness,
saying it had been a profitable though a painful dispensation to her,
and on one occasion, when in great pain, remarked to her mother, "`Oh it is hard work.
How needful, when in health, so to live as to be in readiness,
for it is enough to struggle with the pains of the body.`"

Being favoured with an interval of stillness and composure after a very painful day,
she apprehended herself going, and took a solemn leave of all her connections present,
desiring them to make preparation for that awful season
when the soul must be separated from the body--adding,
"`I want to be gone--but the Lord`'s time is the best time.`"

On the evening of the day she died, her sufferings were great.
"`No one can think`" said she,
"`what I feel--but if it is to purify me for an admittance into that holy place,
where no impure thing can enter, I am willing to bear still more.
I hope I am not impatient, but really the conflict is so sharp at times,
that I cannot forbear crying out.
O Lord, keep me--my God, help me, and please to release me this night.
I long to be gone.
Although I have had many pleasant prospects in view, I have resigned them all,
and would not return again to the world for any consideration.`"

Her mother having retired from the room for a short time, she sent for her,
and with sweet composure,
informed her she was now going and would wish her father and sister to come in,
that they might all sit together for a little while, and take a solemn final leave.
She was strengthened to pass through this affecting scene with great calmness,
and admired that she could so easily part with her beloved connections, observing,
"`I have no tears to shed--but it is not hardness of heart,
for I love you all as well as ever,
but it is to me an earnest that I am going to something greater.`"

Soon after, she said,
"`It is all over--I am perfectly happy--I have no pain--the conflict is at an
end--farewell--farewell--I am now going to join saints and angels and the spirits
of just men made perfect:`" then laying her head quietly on the pillow she expired,
the 22nd of the third month, 1777, aged twenty years.

[.asterism]
'''

MARY POOLY, of Southwark, London, died on the 12th of the eleventh month, 1792.
Her parents had been concerned to educate her in plainness and sobriety,
and their christian endeavours to preserve her from the evils which are in the world,
were not ineffectual.
Although of a sprightly disposition,
she early evinced a love of religion and of those who lived in conformity with its restraints,
and was solid and becoming in her deportment.
About the eighteenth year of her age, she showed symptoms of declining health,
which gradually became more alarming and settled in pulmonary consumption.
In the commencement of this painful dispensation, she apprehended she should not recover,
yet was preserved throughout, in remarkable patience and cheerfulness of spirit,
often saying, "`Through mercy I do not repine.`"

About a month before her decease, she observed to her father,
"`I seem to be gradually going--I have remembered the words of Job,
'`The Lord giveth and the Lord taketh away--blessed be the name of the Lord.
It is best to be resigned--do not grieve, my dear father--the Lord will be with thee.
We must part some time, and I cannot go better than well.`"

She had long been pressing after the knowledge of heavenly things,
and endeavouring to live in obedience to the will of her Lord and Saviour,
and in the course of her illness the same exercise of mind attended her, remarking,
"`There is a language that I have often thought of in the time of health--which is,
'`Oh! that I might walk in all things consistent with the truth I make profession of.`'`"

At another time, near her end, she said,
"`I think I may truly say that I have not murmured
in all this illness--the Lord is my refuge.
I am comfortably resigned to His divine will, and seem to have nothing to do but to die.`"

[.asterism]
'''

RICHARD HUNTER, of Sherburn, England, (brother to Frederick Hunter,
of whom some account has already been given,) received his education
at the best schools which the Society of Friends afforded,
and afterwards entered on the study of law.
He soon found that his conscientious mind could not
pursue this profession in its unlimited extent,
and after about twelve months,
confined his attention to such parts only as he thought he could consistently engage in.

The closeness with which he applied himself to study probably contributed to the disease,
which by slow degrees wasted his physical strength
and eventually conducted him to the silent tomb.
In the fifth month, 1820, he was seized with an inflammation of the lungs,
and was removed home.
His medical attendants calling to see him,
he perceived they were not sanguine about his recovery, and remarked,
"`I don`'t murmur at these afflictions,
and whether I am restored to health or taken away, the Lord`'s will be done.`"
When a little relieved from pain, he enjoyed the reading of the Holy Scriptures,
and would often ask to have them read to him.
On one of these occasions he was much affected and observed,
"`I have long been convinced that much personal happiness
arises from a strict performance of moral obligations;
and although I do not feel sensible of many deviations from moral rectitude,
yet I find this alone will not do for me.
I feel the necessity of regeneration; for he that is in Christ Jesus is a new creature.`"

In the Spring of 1822, he recovered so far as to walk and ride out a little,
and by the advice of his medical friends took a journey to Scarborough,
but returned home under increased weakness;
and in the following tenth month was again confined to a sick-bed.
His mind was often engaged in serious contemplation,
and through divine kindness he was strengthened to
resign himself wholly to the Lord`'s disposal.
His aspirations were after God and heaven, often breathing forth this language,
"`As the hart panteth after the water brooks, so panteth my soul after Thee, O Lord.`"

After a short silence, one day, he remarked, "`Oh, the exceeding sinfulness of pride!
A proud heart is an abomination to the Lord.
Above all things, learn of Jesus Christ to be meek and lowly as he was.`"
On first-day, the 12th of first month, 1823, his end was thought to be near,
but he revived a little, and perceiving that he was surrounded by weeping friends,
he said, "`Do not weep--I am only waiting for an admission into that beautiful city,
the new Jerusalem.
What a favour it is when we can say in sincerity and truth, Thy will, O Lord, be done.`"
After a portion of Scripture had been read, he was asked if it fatigued him?
he replied,
"`I cannot be fatigued with that which is so good;`" and another chapter being read,
he said he was much refreshed.
On third-day morning he desired his mother not to leave him, for he was going to die,
and accordingly about two o`'clock he quietly passed
away to a better inheritance--aged twenty years.
