== Chapter 9

[.chapter-synopsis]
* Eleanor Southam
* Isaac Pease
* Deborah B. Massey
* Springett Penn
* Mary Ann Gilpin
* Maria Cross
* William Baynes
* Rachel Tanner
* Sarah Drewry
* Joseph Elliott

ELEANOR SOUTHAM, of Coventry, deceased the 26th of fourth month, 1823, aged twenty years.

She was naturally of an affectionate and lively disposition, fond of reading,
and possessed a very retentive memory,
and took great pains in the cultivation of her mind;
yet notwithstanding she was endued with superior abilities,
she entertained a humble opinion of herself and was desirous not to be more highly
esteemed than * She was of a solid and reflecting turn of mind,
and her serious deportment in religious meetings evinced that she was not a stranger
to the solemn purpose for which she assembled with her friends.

When prevented by indisposition from attending meetings she greatly regretted the privation,
and employed the time in retirement and reading, especially in the sacred volume.
As her disorder advanced,
she became deeply impressed with the necessity of a more
entire surrender of her heart to the blessed Saviour,
and a material change took place in her estimation
of many things in which she had formerly delighted,
particularly as related to the lighter part of her reading;
the bible now affording her the greatest satisfaction.
She would frequently query, in the language of Newton,

[verse]
____
Tis a point I long to know,
Oft it causes anxious thought;
Do I love the Lord or no,
Am I His or am I not!
____

This profitable self-examination was sometimes succeeded
by grateful acknowledgment of the Lord`'s goodness and mercy,
saying,

[verse]
____
Jesus sought me, when a stranger,
Wandering from the fold of God;
He, to rescue me from danger,
Interposed his precious blood.
____

Her illness, which was consumption, made rapid progress and soon confined her to the bed.
After a fit of coughing attended with acute pain in the side, she observed,
"`I hope my patience will hold out to the end;`" a desire which was mercifully granted,
not a murmur or impatient expression escaping her,
during the whole course of her sickness.

Her mother being a constant attendant on her,
they were favoured with many precious opportunities together, the daughter informing her,
with much tranquillity, that she had no wish to recover; and on another occasion,
expressed her love for, and hope in, her dear Redeemer.
Throwing her trembling arms around her mother`'s neck, she softly repeated these lines,
which so feelingly allude to the faithfulness of the Lord`'s love to his redeemed children,

[verse]
____
Can a mother`'s tender care
cease towards the child she bare?
Yes--she may forgetful be,
Yet will I remember thee.
____

She remarked on one occasion that "`she had gone through many deep
baptisms and inward conflicts during the early part of her illness,
but that now she believed if she should be taken away, she would be accepted.`"
The passage being read from the Epistle to the Corinthians where it is said,
"`We are troubled on every side, yet not distressed, we are perplexed,
yet not in despair.`"
She sweetly said, in allusion to the forepart of it, "`My dear mother, I was once,
but am not now.`"

Some observations being made on the love of the Saviour, she said,
"`I do love Christ--but I often wish I felt a greater evidence of my love to Him.`"
The declaration of the great Apostle being cited to her,
as affording much consolation on a dying-bed,
viz. "`It is a faithful saying and worthy of all acceptation,
that Jesus Christ came into the world to save sinners,`" she emphatically replied,
"`Those are sweet words.`"

Shortly before her departure, she desired her father to pray for her,
that she might not be as one of the foolish virgins.
She was then engaged in supplication herself, and presently after,
as though every doubt and fear had been mercifully removed, she observed to her mother,
"`My robes have been washed white in the blood of the Lamb.
Though thou slay me, yet I will trust in thee.`"
With her dying breath she supplicated nearly in the words of the Lord Jesus,
"`Our Father who art in heaven,
hallowed--hallowed--hallowed be thy name!--thy kingdom come--thy will be done,
on earth--as it is in heaven`"--and in a few minutes she peacefully breathed her last.

[.asterism]
'''

ISAAC PEASE, son of Edward Pease, of Darlington, in England,
was a youth of quick abilities and kind disposition.
After receiving a liberal education under the christian care of his parents,
he commenced the study of law in his native town.
In this new situation the care of his parents was still watchfully extended over him,
and he was advancing towards manhood in the enjoyment of life,
and raising in the minds of his relations the pleasing anticipation
of his future usefulness in civil and religious society.
He pursued with diligence those studies which were
designed to qualify him for acting in his profession,
so far as a member of our society can with propriety go,^
footnote:[The difficulties which a consistent friend must
meet with in the employment of a lawyer are so many,
and the exposure to improper company and examples as well as the temptations
to violate the christian testimonies of the Society so great,
that we should suppose a friend who had a proper
regard for the religious welfare of a son,
would hardly be willing to place him in so dangerous a situation.
The most flattering prospects of worldly advantage would be far overbalanced
by the liability of leading into temptation and perhaps ruin.]
until the declining state of his health produced much anxiety in the minds of his friends.

In the fifth month 1825, he was too unwell to continue his usual occupations.
He often appeared very thoughtful in reference to the great work of the soul`'s salvation,
and in conversation with one of his brothers remarked,
that although he sometimes could acknowledge to the goodness of the Almighty,
yet at others, he found great difficulty in bringing his mind into settlement.
It was, however, consoling to observe,
as the symptoms of his disorder became more alarming,
that a broken and contrite spirit was often obvious.
At one time, when labouring under great difficulty of breathing,
inquiry was made respecting his mental feelings, when he replied,
"`Oh! yes--I can trust in the mercy of God.
He is a God of mercy and truth;`" adding soon after,
"`It is hard work to press forward aright and be a good example.
I do believe, to be taken away in youth is a great favour,
and if it please Providence to take me away,
I shall escape all the vicissitudes of time.`"

In the course of his illness, which was of several months`' duration,
he was at times enabled to believe that the Lord was near to strengthen and support him;
but there were seasons of spiritual poverty and desertion,
in which he feared that he had not a solid foundation
on which to rest his hopes of eternal happiness,
yet through mercy, the prevailing desire of his heart was,
to be endued with patience and resignation.
He remarked one evening--"`It is trying; lying so long here.
My illness continues long--there is nothing +++[+++will do for me]
but seeking for Divine support.
Sometimes a little hope springs up,
and then again it seems as if I must give up all and be prepared.`"

On the 20th of the seventh month, addressing his beloved mother, he said,
"`It is difficult to be resigned--to live so as to be prepared to die.`"
The hope was expressed that he was at times favoured to attain to some feeling of resignation;
when he added, "`Yes--sometimes, but it is hard work to leave all, relations and friends,
and resign all the promised pleasures of time.
Oh!
I look back and see that I have been too earnest in pursuing the things of this life,
not altogether on my own account; my mind +++[+++has been]
too full of them; and then,
in some of our meetings how poor and barren my mind has been.`"

The following evening, after the reading of the forty-sixth Psalm,
which beautifully describes the confidence and hope
of those who have God for their refuge,
a solemn stillness occurred, when he observed with great tenderness,
"`I believe the Almighty has been my refuge in time of trouble,
and has been near and supported me.`"
At another time he said "`he had frequently desired to be enabled to say,
Thy will be done--and endeavoured to feel after the Divine presence,
but found it difficult.`"
He was encouraged by a relation present, to keep his mind stayed upon the Almighty,
and an allusion being made to the comparative innocency of his life,
he replied by the humble acknowledgment,
"`I have endeavoured after a degree of watchfulness,
but I have not worshipped my heavenly Father as I ought.`"

On the 5th of the ninth month,
this patient sufferer was evidently enduring the pressure of severe disease,
and after laying quietly awhile, with a countenance expressive of heavenly serenity,
he said, "`I trust I have a well grounded hope of a better inheritance;
but it is all of mercy-great mercy--It is not by
works of righteousness which we have done,
no, no, but according to his mercy he saveth us,
or where would be my hope--Oh! how precious is this love of Jesus!
I have felt it very precious.
He gave his life as an atonement for our sins--an atonement--yes,
and a propitiatory sacrifice.
How precious has the recollection of this been to me.`"
His father expressed his joy that his son was thus comforted,
and his hope that should lengthened days be allotted him,
the recollection of these precious moments would accompany his future steps through life:
he replied, "`Yes, I hope so--But oh! the deceitfulness,
the allurements--the temptations, of this world.
I know they are powerful, and I fear I should fall.
It is hard work to maintain our steadfastness through all,
and be good examples in the great cause.
I think I had rather go now.`"

On the 25th of ninth month, after having passed a very distressing night, from coughing,
he said, "`I often try to get down to the source of patience,
but am so weak--though I think I may exclaim, "`Bless the Lord, O my soul,
for his mercies are ever new.`"
Many times, when tried with severe pain,
he prayed for patience and strength to endure the allotted conflicts.
During the following day he was evidently sinking, and expressed very little,
but on one occasion said,
"`I want to go home tonight`"--very early the following morning he gently sunk away;
being, as we humbly trust, rendered meet for an inheritance among the saints in light,
through the mercy of God in Christ Jesus.

[.asterism]
'''

DEBORAH B. MASSEY, daughter of William Massey, of Spalding, Lincolnshire, England,
deceased the 24th of the first month, 1827, aged about twenty years.

After having been unwell for sometime,
she expressed a desire to know the opinion of the doctors respecting her case; adding,
"`It signifies little when we die, if we are prepared;
and should it be the will of Providence to remove me,
I hope to be more fit for the change than I now feel myself to be.
The things of time have had too much place in my heart.`"

On the 8th and 9th of 12th month, 1826, her mind endured much close conflict;
and in the afternoon of the latter day she was seized with violent convulsions,
which seemed to threaten speedy dissolution.
The paroxysm, however, gradually subsided; she leaned on her father,
and taking a beloved uncle by the hand, said in a distinct, though altered tone of voice,
"`O my dear uncle--O my dear father--I am going--this is death.
I had no idea that dying was like this, but I can bear it.`"
Then addressing the Almighty, "`Thou enablest me to bear it--Lord,
into thy hands I commend my spirit.
Jesus, receive my spirit.
Oh, take me to thyself.`"
Afterwards, to her mother, "`I thought I was going--I am disappointed,
but I desire patiently to wait the Almighty`'s time.`"

On the 11th, her uncle coming to her, she remarked, "`I am very ill.
I much desire I may trust in the Lord to the end, and not cast away my confidence.
I believe I have tasted what death is, and I find it is quite supportable.
I am not afraid of death now, and Oh! how glad I am that I can say so with sincerity.`"
A solemn silence ensued, and her uncle supplicated at the throne of grace on her behalf;
soon after which, her father coming into the room, she looked at him with much affection,
and observed, "`I am very comfortable`"--adding with great emphasis,
"`I can now say--for all I thank thee--most, for the severe.`"

First-day, the 14th, was a time of much bodily suffering to her: being in great pain,
she prayed thus "`Almighty God, release me from my troubles,
if it be thy Divine will--if not, grant me patience and resignation.`"
On third-day, after her father had read a portion of Scripture to her, she said,
"`I hope my dear Saviour will be near to support me.
I was greatly distressed a little while ago.
I thought he had left me.`"
Sometime after, she remarked, "`I am not so deeply tried as in the morning,
but I want to feel more peace.
I want to feel fully forgiven.`"

In the evening of the 21st, she prayed again, "`Lord, have mercy.
Why art thou so long in coming?
Oh, may it please thee now to take me.`"
Afterwards, under the returning feeling of the withdrawing of the Divine presence,
she plaintively said, "`Oh, my Saviour! where art thou gone--Why hast thou left me?`"
He who is abundant in mercy and compassion to all those who trust in his name,
and who for wise purposes was pleased thus to try
her with bodily pain and poverty of spirit,
now saw meet to change the dispensation,
and cause both her outward sufferings and inward conflicts to cease;
and under a humble sense of the unmerited favour,
she gratefully acknowledged the change.

On third-day, the 23rd, her uncle coming to the bed side,
she repeated the following lines--

[verse]
____
Oh! Teach me, in the trying hour
When anguish swells the dewy tear,
To still my sorrows--own thy power--
They goodness love--thy justice fear.
____

Her pain returning, she interceded after this manner, "`Gracious Lord,
be pleased to mitigate my pain, or enable me to bear it with patience`"--again,
"`Blessed Jesus, why +++[+++dost thou]
tarry--why do thy chariot wheels delay?`"
In the morning of the 24th, her father standing by her, she said, "`My Saviour is coming.
I have been distressed.
I thought he had forsaken me--but he is coming--he is coming`"--and
about half past six she quietly expired.

[.asterism]
'''

SPRINGETT PENN, the eldest son of William Penn, Governor of Pennsylvania,
deceased in the twenty-second year of his age.

For a considerable time before it pleased the Lord to visit him with sickness,
his mind was seriously impressed; he became retired in his habits,
much disengaged from youthful delights,
and evinced great tenderness of spirit in religious meetings,
even when they were silent.

When his illness increased so that his recovery became doubtful,
he turned his mind and meditations more earnestly towards heaven and heavenly things,
often praying with fervency to the Lord,
and offering thanksgiving and praises to his holy name.
He was entirely given up to the dispensations of an all-wise Providence, saying,
"`I am resigned to what God pleaseth.`"
He knows what is best--I would live, if it pleased Him, that I might serve Him; but,
O Lord, not my will but thy will be done.`"

In reply to some observation respecting the things of the world, he remarked,
"`My eye looks another way where the truest pleasure is.`"
His father being about leaving him to go to meeting, he said, "`Remember me,
my dear father, before the Lord.
Though I cannot go to meetings, yet have I many good meetings.
The Lord comes in upon my spirit.
I have heavenly meetings with Him by myself.`"
Fixing his eyes on his sister, he took her by the hand, saying with much affection,
"`One drop of the love of God is worth more than
all the world--I know it--I have tasted it.
I have felt as much, or more of the love of God in this weakness,
than in all my life before.`"

Taking something one night just before going to rest,
he sat up and reverently prayed thus--"`O Lord God! thou whose Son said to his disciples,
'`Whatsoever ye ask in my name, ye shall receive, I pray thee in his name,
bless this to me this night, and give me rest, if it be thy blessed will, O Lord.`"
This supplication was mercifully answered, and he passed a comfortable night,
which he thankfully acknowledged.
Having inadvertently said "`he was resolved he would have such a thing done,`" the positive
manner in which he expressed himself produced uneasiness in his mind;
he checked himself, and with much contrition made this acknowledgment--"`O Lord,
forgive me that irreverent and hasty expression.
I am a poor weak creature and live by thee, and therefore I should have said,
if it pleaseth thee that I live, I intend to do so and so.
Lord, forgive my rash expression.`"

With a countenance expressive of the awfulness which covered his spirit,
he thus addressed his brother, "`Be a good boy;
and know that there is a God--a great and mighty God, who is a rewarder of the righteous,
and so he is of the wicked, but their rewards are not the same.
Have a care of idle company, and love good company and good friends,
and the Lord will bless thee.`"
Taking leave of his relatives, he said, "`Come life--come death--I am resigned.
Oh! the love of God overcomes my soul.`"
Soon after which he expired.

[.asterism]
'''

MARY ANN GILPIN, daughter of James and Mary Gilpin, of Bristol, England,
died the 11th of sixth month, 1838, aged twenty-five years.

In very early life she was favoured with the visitations of the Holy Spirit,
which strives with children when very young.
She was the subject of frequent attacks of severe disease,
which brought her down to the borders of the grave,
often with very little hope of recovery,
yet she was again and again raised up to testify
to the mercy and goodness of that blessed Saviour,
whom she loved and endeavoured to serve.
She endured much bodily suffering,
yet there is good reason to believe that these afflictions were sanctified to her,
tending to wean her affections from everything earthly and to fix them on heaven,
engaging her . to walk as a pilgrim and stranger upon earth.

In the year 1830, she was attacked with a disease which was considered to be mortal,
and was brought so low that her medical attendants believed her to be dying.
She took leave of her beloved connections with sweet composure, saying,
"`May the evening of your day, my beloved parents,
be soothed by the consolations of religion; and may you my beloved brothers and sisters,
now in the morning of your day, choose the Lord for your portion.`"
Her mind was preserved in great peace, and in humble reliance on her Saviour,
she was enabled to rejoice with joy unspeakable and full of glory.

From this extreme illness she gradually recovered,
and it required no small degree of faith and resignation
to be willing to return to the busy scenes of active life,
after having been permitted such a near approach to,
and blessed foretaste of the joys of heaven.
Her humble and consistent walk, her subsequent dedication to the will of God,
her holy watchfulness and fear,
showed that she did not forget the lessons learned upon the bed of languishing,
but was engaged with increasing earnestness to devote
herself wholly to the will of the Lord.
While recovering from this illness,
some prospects of religious duty were opened to her view,
in reference to which she thus wrote to a friend:
"`When conversing with thee this morning on my future prospects,
I mentioned my youth and inexperience,
but I have since regretted that I did not allude to that
goodness and mercy which have hitherto followed me.
Although a very unworthy little one, I have, in the midst of affliction,
been borne at seasons above its deep waters,
and I can indeed sing of mercy as well as judgment.
I have been most tenderly dealt with; and O,
I do most earnestly desire that I may not in the least frustrate
the gracious design of my heavenly Father concerning me,
but that I may simply and faithfully follow the intimations of his will
who alone can lead his children in the way in which they should go.`"

In the fifth month 1837,
she experienced the first attack of the disease which terminated her life;
respecting which she makes the following remarks, viz:
"`The last two days have been passed in bed, in bodily suffering.
A sweet sense of the love which marked the chastening was, however, very present with me,
and I was enabled in a good degree to commit my all to the Lord.
The night of the 16th was one of suffering from the state of my chest.
I was also deeply tried with believing hat I was
receiving chastisement for want of faithfulness,
and in agony of heart I was ready to adopt language similar to this, '`Lord,
I am ready to go with thee to prison and to death.`' But
although in searching the motives which prompted this,
I was made sensible of my great frailty,
I continued to desire ability closely to follow Jesus
in whatever way he may point out for me to walk in.
I do desire to be wholly His, and I crave this blessing for many loved ones,
when endeavouring to commend them to the care of the Shepherd of Israel.`"

"`The 21st was a day long to be remembered.
I was bowed under a renewed sense of unworthiness,
but did not sufficiently realize the fulness which is in Christ.
Oh! with what unutterable tenderness has he dealt with his wandering child.
How gently has he again and again chastened me with the rod of his love,
whilst upholding me with the staff of his power!
Gracious and omnipotent Father!
I do at this time afresh desire to commit myself unto thee,
craving for my Saviour`'s sake, the blessed privilege of being brought nearer to thee;
of having my way tried, my thoughts proved by thee.
Ah, leave me not until thy work is fully accomplished in and by me;
until I am made wholly thine.
Although it may be needful for me to pass through
even deeper waters than I have yet done,
if my Saviour, my Shepherd, is there,
I know the billows will not be permitted to overwhelm.`"

Sixth month 8th. "`The appearance of a symptom of disease I never had before,
and serious in its nature,
has placed afresh before me the great uncertainty of my long continuance
here and renewed my very earnest longings to be made fully meet
for an inheritance with the saints in bliss;
having my robes washed and made white in the blood of the Lamb, knowing the sanctifying,
purifying influence of the Spirit of Jesus.
Under a deep sense of divine love and mercy,
I have been at times almost overwhelmed with the
fear of wandering from my heavenly Leader,
and not sufficiently realizing his power and willingness to save.`"

In the eighth month, she was removed from Leominster,
where she had been staying some time, to the residence of her father,
respecting which she thus writes:
"`It has been thought best for me to return to my beloved family, and new amongst them,
I desire to give up my whole heart to the; solemn work of preparation,
whether it be for life or death;
to seek more and more the fulness of the blessing of the gospel.
The night before I left Leominster was one of refreshment to my spirit;
one precious promise after another was recalled to my remembrance,
to my unspeakable comfort, and I was enabled to commit myself and all dear to me,
unto the Lord, Then, in sincerity of soul, I cried, "`I come to thee +++[+++O Lord,]
to be made whatsoever is pleasing in thy sight.`"

Ninth month 5th. "`In my time of retirement I earnestly
sought ability to watch unto prayer;
and although during the morning my thoughts wandered too much to terrestrial things,
many and ardent longings were felt after heavenly good.
In the afternoon and evening I suffered much from unwatchfulness;
but ere I closed my eyes to sleep, I was strengthened to approach the footstool of mercy,
and to feel the unspeakable privilege of having`' an Advocate with the Father.`"

She was, from conviction, closely attached to the principles of the Society of Friends,
and often was her spirit clothed with mourning at the inconsistency of many of its members.
She longed that Friends might live more in conformity
with the simplicity which the Gospel enjoins,
and she felt it cause for regret that some who were looked up to as examples
should so widely depart from that simplicity in the furniture of their houses.
"`O, I do wish,`" she would exclaim, "`that Friends were more simple.`"

From the 13th of second month, 1837,
she was wholly confined to a recumbent posture and almost entirely to her bed.
In reference to the state of her mind, she remarked on the 21st,
"`My body has again been brought very low, but I have been most tenderly dealt with.
Last night was a restless one, but I was unspeakably happy.
No doubt appeared to darken the future,
and I was favoured to feel entire resignation to the divine will.`"
To one of her brothers she said, in taking leave of him,
"`Do not think of me as I am now, in a state of suffering, but think,
of me as a joyful partaker of the grace of life though very unworthy.
O do not weep for me--I am very happy--our separation may be a very short
one--Oh! look forward to the time when we shall meet again.
Thou knowest how exceedingly I have dreaded sinning--O
how joyful to be where temptation cannot enter!
I shall see his face, and never, never sin.
It seems to me as if the very absence of all sin would of
itself make heaven a very bright and a very glorious place.`"

On the evening of 9th of fourth month, being in extreme suffering,
she repeated with much emphasis:

[verse]
____
How sweet to think of rest at last.
To feel that death is gain!
____

On the 11th a faintness came over her, which induced her to say, "`O mother,
I am either very faint or I am going,--am I going!`"
Her mother replied, that if she was going, she trusted she was quite ready.
"`O yes,`" she rejoined, "`quite, quite, ready.`"
Something being given her to revive her, she partook of a little, but soon put it aside,
saying, "`I am going, I am going--to my happy--happy home.`"
Articulation had nearly failed,
but it being remarked that her Saviour was with her through the dark valley,
with a heavenly smile on her countenance, and considerable effort, she exclaimed,
"`O yes--yes--very--very--happy;--`" and peacefully expired.

[.asterism]
'''

MARIA CROSS, daughter of Joseph and Elizabeth Cross, of Colchester, England,
departed this life on the 18th day of the twelfth month, 1821, aged twenty-one years.

She was of a lively, cheerful disposition,
and being in declining health for a considerable time before her decease,
her mind became seriously impressed,
and through divine grace she was enabled to bear her affliction with patience and resignation.
One of her sisters taking leave of her, inquired how she felt,
to which she made little reply at the time; but on her sister`'s return, said,
"`I wanted to see thee to tell thee what I could not when thou left me--that
fears and doubts are now all removed and my way seems clear.
It is now all sweetness.`"

She gave some salutary advice to one of her brothers,
pressing upon him the necessity of guarding carefully
against lightness in conduct and conversation.
On first-day as the family were going out to meeting, she observed to her mother,
"`I view the principles of friends in a very different light to what I did when in health,
and now see the beauty there is in silence--if I ever should go to meetings,
I hope to sit in a very different frame of mind.`"
She impressively addressed two of her brothers who had families,
on the importance of their charge,
at the same time seriously advising them not to put off
the great work of salvation till they came to a sick bed.
To another brother she said,
"`I have nothing to do but to die--all is peace--sweet peace.`"

One of her sisters coming into the room, she said to her, "`I think I am going.
I dreamed last night, that I was trimming my lamp, and it was full of oil,
which was very comfortable.
All I have to do now is, to pray that patience may hold out to the end.`"
A near relation going to see her, she spoke of his making her coffin, and added,

[verse]
____
I long to see my Saviour`'s face,
That I may sing redeeming grace
____

Nearly the last words she uttered were, "`Lord Jesus, if it be thy most holy will,
come quickly--quickly--quickly,`" and with a sweet smile resting on her fixed features,
quietly departed to her home in heaven.

[.asterism]
'''

WILLIAM BAYNES of North Shields, in England, deceased the 25th of sixth month,
1843 in the 21st year of his age.

He was much beloved for his kind and amiable disposition and circumspect deportment,
which endeared him to a large circle of friends.
His illness was of long continuance,
yet he evinced great patience and humble submission to the Divine Will.
Some time before his decease he endured much deep exercise of mind,
not being able to attain that true and solid peace with God, which he greatly longed for;
but, through redeeming love and mercy,
he was at length permitted to partake of that faith,
hope and joy which were his consolation and support during the residue of his days.
He could now testify that he had indeed found the pearl of great price,
and that it was worth seeking after and parting with all to obtain.
To one of his sisters, he said, with much affection,
"`Seek the Lord now in the time of health:
do not leave it until thou art laid upon a bed of sickness.
I have not been so watchful as I ought to have been,
but I hope all my sins are now forgiven me, through Jesus Christ,
who died upon the cross.
Read the Scriptures more than thou hast done; also Friends`' books,
particularly Barclay`'s [.book-title]#Apology#--He frequently said he
thought Barclay`'s [.book-title]#Apology# was not enough read;
that every member of the Society of Friends should read it carefully; adding,
that he had received much instruction from it.

Near his close he was favoured with great composure of mind;
and on one occasion after being very still for some time, he said,
"`Oh! how peaceful I feel.
I am thankful for all the blessings received.
You must look to the Lord Almighty for your reward.
Oh!
I could sing praises, praises, and give glory.`"
It being remarked that he bore his sufferings with much patience,
he said with much humility, "`What are my sufferings compared with our Saviour`'s,
who died upon the cross.`"
His medical attendant saying it must be a comfort to his
friends to hear that his hopes were fixed on his Saviour,
he replied, "`There is nothing like it at such a time as this.`"
His quiet,
peaceful end furnishes the consoling assurance that
his spirit is entered into the joy of his Lord.

[.asterism]
'''

RACHEL TANNER of Winthill, Somersetshire, England, deceased the 16th of the sixth month,
1841, in the 21st year of her age.

She was the only child of her parents;
and from an early period of life had manifested much
seriousness of mind and stability of deportment.
In the autumn before her decease,
she was attacked with symptoms of a pulmonary character,
respecting which she thus wrote to her mother;
"`I believe it right to use means to restore health,
yet at the same time I have so +++[+++fully]
experienced the fallacy of all earthly pleasure,
as to feel perfectly resigned to the Lord`'s will;
and when at any time I feel a love for life,
it is my prayer that I may be given to see that the great
object of my life should be to prepare for another.`"

On the 17th of twelfth month, 1840, she remarked,
"`It is very humiliating to be brought so low in so short a time;`" and on the 22nd,
in allusion to an attack of fainting which, threatened her dissolution, she said,
"`I thought I was going--Oh! how dreadful must such a change be to those
who are not prepared for it--I hope my faith will not become weak.
I felt that if I had gone +++[+++then,]
the Lord in his mercy would have taken me.
I used in health to have sweet communion with heaven, so much so,
that I thought I could enter into its joys, I felt such a participation in them.
When reading the Scriptures,
I was favoured to feel my spirit ascend and they became the subject of
my prayers.--I should like to have a fresh foretaste of the joys of heaven.
I would not lift up a finger to frustrate any of the Lord`'s designs: my prayer is,
Thy will be done.
It has, of late,
often been my prayer that I might not place my affections on things below,
but that they might all be centered on things above.
I used to think that when my time for leaving this world should come,
trusting in the mercy of God in Christ Jesus, it would be a joyful departure:
I now fear whether the feelings of the poor body may not occasion it to be otherwise,
but I do not mistrust the mercy of the Lord--May
it please Him to permit me to pass from time,
rejoicingly, for your sakes.`"

On the 9th of fifth month, 1841, she said, "`It would be wrong to wish for it,
but I should be very thankful to be released--Oh! very thankful,--pray
for me--I have need of all your prayers.`"
She was asked whether she wished them to pray that she might be released from suffering;
her reply was "`No--for patience to be enabled to bear it.`"
On the 14th she said to her mother, "`O, I have cause to praise the Lord;
He has assured me my end shall be peace`"--and a few days after,
"`I am a poor creature both in body and mind.
Is it not said, '`God shall wipe away all tears from our eyes?
And there is another encouraging passage,
'`I will never leave thee nor forsake thee`'--yet
it seems very trying to me to feel so much desertion,
after having had such happy moments.
There was a short time in the early part of my illness,
when I felt dissatisfied with myself for my lukewarmness;
and after feeling a sensation like death, I became more earnest to know the Lord;
I looked to him, and saw him full of love.`"

On the 30th she exclaimed,
"`O that I could praise the Lord! that I could feel my heart expand with love to Him,
as I used to do in health; but this is not permitted--what a privation!`"
The 5th of sixth month, symptoms of approaching +++[+++dissolution were apparent,
and her few remaining days were mostly passed in great suffering;
but her patience was mercifully renewed from time to time,
and she often joyfully anticipated a release from the afflicted tabernacle.
She remarked, "`I cannot say I would not wish one pain removed:
I should be very thankful for a little relief--I have long been willing,
but I should now be very thankful, to be taken.`"
The 13th verse of the 68th Psalm being read at her request, she observed,
"`I have been among the pots, when seeking repentance;
now how beautiful it would be to fly away!
My sufferings are great, but my blessings are many`"--and after repeating the passage,
"`they wandered about in sheep-skins and goat-skins, being destitute, afflicted,
tormented,`" she said,
"`My afflictions are light compared with what the saints suffered formerly.`"
Reviving from a fainting fit, she petitioned, "`O Lord, be pleased to release me,
and take me to thy kingdom.
Come quickly, if it be thy will.
Jesus, lover of my soul,
let me to thy bosom fly`"--desiring that the rest of the hymn might be read to her.

Alluding to her being apparently so nearly gone, she said,
"`I do not know that I have anything more to say or do;
the Lord loves me--when will he take me?
Again, "`How happy I am, though suffering so much! but what is +++[+++suffering]
compared with the glory that shall be revealed.`"
At another time, "`Precious in the sight of the Lord is the death of his saints:
perhaps the Lord considers me one of his saints--I hope
I am not exalting myself--I feel very humble and lowly.
I have everything to humble me.`"
Again she remarked, "`As a father pitieth his children,
so the Lord pitieth them that fear him.
I never saw that passage so beautiful before--fear him.`"

The day before her close, after a time of silence,
she was asked if she had been asleep--and replied, "`Not sleeping, but happy,
happy--I thought I was going,
but I may be with you another day before I shall sleep and be with Jesus,
where there is no more pain--no more death.`"
In the midst of her sufferings, she would often pray for patience and for a release,
but adding, "`Not my will but thine be done.`"
Once she said, "`I never doubted the Lord`'s promise,
'`thy end shall be peace,`' it was so distinctly sounded in my ear--O, no,
I have never doubted.`"
A little season of ease was granted to her before the close,
and she quietly ceased to breathe,
leaving the consoling assurance that for her dear Saviour`'s sake,
she was numbered among those who surround the throne of God.

[.asterism]
'''

SARAH DREWRY, of Whitehaven, died the 21st of first month, 1825, at the age of twenty-one.

In the early part of her illness, she evinced considerable anxiety to recover,
but her mind was soon seriously impressed with a belief that she should not,
which caused her to be very thoughtful, and at times, her spirits were much depressed.
Yet through the tender mercy of the Most High, these discouraging feelings were removed,
and her mind sweetly comforted by the consolations of the gospel of Christ,
under the precious sense of which she was enabled to resign herself to the will of heaven.
So great was the peace with which she was at times favoured,
that she was tempted to fear whether it might not be a delusion,
but checking herself for such a thought, said, "`Oh! `'tis the enemy,
I know it is the insinuation of the enemy.`"

During an illness of six months`' continuance,
a considerable portion of which time she was confined to her bed,
and suffered much from bodily weakness, not a murmur escaped her.
On one occasion she observed,
"``"Tis all in wisdom that I am thus afflicted--for I felt before I was taken ill,
that I was getting high; and if things had continued to prosper with me,
I believe I should have got very high--so that `'tis
all in wisdom I am to be taken away.`"
Again--"`I have no desire to get better, unless it be the will of the Almighty;
then I feel as if I should be willing to recover.`"

Her sister remarking how little she appeared to suffer in mind,
to what many did at such a time, she replied,
"`But thou little knowest what I had to suffer before I attained to this state,
yet things have been made easier to me than I ever expected.`"
At another time, feeling herself growing weaker, she remarked,
with a sweet smile upon her countenance,
"``'Tis a happy thought--I shall soon leave this weary world--I hope it will be soon.
How pleasant when I can rest in peace--in sweet, happy peace.`"

She advised her sister not to devote much attention to dress, saying,
"`Although I dressed consistently,
I have now to regret that I should have been so particular
in wishing to have my apparel of the finest quality:
were I to recover, my clothing should be plain and homely.`"
She also advised her against reading unprofitable books;
and her sentiments on this subject, which were found in her pocket book,
are worthy of serious attention,
viz. "`It is cause of sorrow to me that so much of my precious
time should have been devoted to reading books of that kind
which are supposed to improve the style of writing +++[+++merely;]
though they may contain nothing of a hurtful tendency,
the perusal of them never yielded me any solid satisfaction.
Did young people consider how short their time may be here,
and how soon the blessing of health may be taken from them,
I believe they would be more careful in employing it to the best advantage.`"

The following lines were found pencilled in her pocket book, viz.

[verse]
____
Sweet the hours of resignation,
When the soul can firmly cry,
Lord! each painful tribulation
Patiently to bear, I`'ll try.

Oft, the mind knows no restriction
Till the pangs of anguish come;
Softened then by each affliction,
Gladly it would seek a home.

Sweeter than a couch of roses,
Does this bed of sickness prove,
While my soul in faith reposes
On the Saviour`'s arm of love.

Jesus! mayest thou still be near me,
May thy light forever shine;
May thy holy presence cheer me--
And, at last, may I be thine.
____

[.asterism]
'''

JOSEPH ELLIOTT, of Liskeard, deceased the 22nd of seventh month, 1841.

From a child he was remarkably steady and serious, dutiful to his parents,
affectionate to his brothers and sisters, and of a kind and condescending disposition.
He was fond of reading the Holy Scriptures, and possessing abilities beyond many,
made great proficiency in the mathematics, ancient languages,
and other branches of useful learning.
Whilst a school-boy, he was in the practice of frequent retirement,
which he continued to the end of life.
He was very watchful and circumspect in his deportment and conversation,
and particularly careful not to say anything which
would cast a shadow over the character of another.
When he saw any of his young friends deviating from
the plainness of their religious profession,
it appeared to give him much concern, which he sometimes expressed.
He frequently visited the poor, read to them in the Bible,
and in other ways evinced his desires for their spiritual welfare,
besides administering to their outward wants.

In the beginning of 1841, he wrote thus in his diary:
"`In looking back on the past year +++[+++I feel]
a good degree of peace, and freedom from condemnation,
and I am ready to hope I have not much, if at all, gone back in my heavenward journey.
But it has been rather a low time on the whole,
in which I have not been permitted to feel much of the joys and consolations of religion.
This may have been handed to me in very tender mercy,
and I hope it will all work together for the good of myself or some other poor traveller.`"

In the fourth month of that year, he took a cold, followed by cough,
and his lungs were pronounced to be decidedly diseased.
On the 14th of sixth month he writes in reference to this circumstance:
"`This information neither alarms nor disappoints me, which is a favour.`"
It being remarked to him that it was hoped he could adopt the lines,

[verse]
____
Sweet to lie passive in His hand
And know no will but His.
____

He was silent for some time, and then said,
"`'`And know no will but his,`' is saying a great deal; but I hope I can say as much.`"

On the 16th of seventh month he was removed to Plymouth for change of air,
and the next day remarked, "`How many comforts I am surrounded with I +++[+++I have]
everything I want, though I am not able to enjoy them much.
Perhaps the change of air may do me good, but if not,
it will be in the right time I am taken,
and I hope the change will be a happy one,`" adding with emphasis,
"`Oh! people ought to think of their latter end.`"

On the 20th he was taken home, without amendment,
and next morning the shortness of his breathing, and other symptoms,
evinced that his end was not far distant.
He said, "`O, if my day`'s work were done, glad should I be to be gone.
It would be joyful--joyful.
He appeared at a loss for strength and for words to express
his delight at the prospect of an early release,
and addressing those present, said,
"`O that you all may do your day`'s work in the day time.
Mind best things; and retire often; the soul needs daily bread.
Try to keep the world under--seek often for best help;
don`'t let difficulties prevent retirement, and don`'t let it be a matter of form.`"
He again pressed upon those present the great importance of retirement,
and of minding the words of the Psalmist,
"`Evening and morning and at noon will I pray.`"

The prospect of the happy state into which he was soon to enter,
filled his heart with a joy which beamed from his countenance, and he exclaimed,
"`glories--glories--glories,`" desiring to be released before another night,
if consistent with the divine will;
yet he repeatedly prayed that patience might be granted him.
On being told that his pulse was becoming more feeble, he looked up with a sweet smile,
and said,
"`It is good news--O how pleasant--I have nothing
to offer--It is all of mercy.`" Reviving a little,
he said to those about him, "`Let me press upon you what I have said before,
do your day`'s work in the day time,
and O remember retirement--retirement--there is a work which must be done.`"
About 10 o`'clock he said, "`Going to my happy--happy home--to my heavenly Father.`"
He then gave some directions about his funeral,
and while his widowed mother was wiping the cold perspiration from his face, observed,
"`I think I feel the cold hand of death coming over me`"--sweetly adding,
"`The Lord will come in his own good time.`"
Soon after, his purified spirit took its flight, as we humbly trust,
to the regions of unclouded day.
