== Chapter 11

[.chapter-synopsis]
* Isaac Alexander
* Daniel Bowly
* Hannah Quinby
* John Pim
* Mary Ann Harris
* Anne Harford Lury

ISAAC ALEXANDER, son of Thomas and Alice Alexander, of Bendrig, in Killington,
Westmoreland, was a youth of sober and innocent deportment,
and much engaged for the salvation of his soul.
In the fourteenth year of his age he was convinced of the principles
of the christian religion as held by the society of Friends,
and joined in fellowship with that despised people.
Continuing in patient obedience to the manifestations
of the spirit of Christ in his mind,
he received a gift in the gospel ministry,
and about the seventeenth year of his age believed himself
required to preach unto others the way of life and salvation,
which he had found to his own unspeakable peace and consolation.

Being faithful in the exercise of the gift, he became an able minister of Christ,
capable of dividing the word aright to the various
conditions of those among whom he laboured;
and freely devoting himself to the Lord`'s work,
he visited nearly all the meetings of Friends in England, Scotland, Wales and Ireland,
many of them more than once, to the satisfaction and edification of his brethren.

In the twenty-fifth year of his age his health began to decline,
and though for a time he continued to get out to meetings,
yet he was soon entirely confined.
During the course of his illness he was enabled to show forth the
blessed effects of the religion he had preached to others,
and his mind being filled with that peace and consolation which
the Lord is at times pleased to bestow on his obedient servants,
he seemed raised above all pain and weakness,
and enabled to triumph in Christ over death and the grave.

Several friends sitting by him on one occasion,
his mind seemed contrited in humble admiration of the goodness of God
in sending his beloved Son into the world to save us from our sins,
and in freely giving to all a manifestation of his blessed
spirit as a light and guide to them in the work of salvation,
when he exclaimed, "`To thee, O Lord, to thee be salvation and praise;
this is a day of great salvation`"--observing what a mercy it was that the Lord should
visit us in our young years and make known the way of salvation to our souls.
Again he remarked, "`How good has the Lord been to me in the time of my sickness!
Although I have formerly felt much of his power and presence,
yet never enjoyed such plenty thereof as since I have been visited with this sickness.`"

At another time he said, "`O,
what an excellent thing it is to keep in the Truth and visit one
another in the life of it;`" drawing a contrast between those who
visit the sick in a serious and religious frame of mind,
and such as go merely to talk upon common topics of conversation.
Speaking to some of his brethren, he earnestly said, "`Friends,
get into an inward acquaintance with the Lord in spirit,
for it is a good thing to retire to the Rock--there is safety--there is good standing,
an excellent bottom and room enough.
If any go out of the bounds of Truth, thinking thereby to bring others in,
they will find themselves to be in slippery places--Beware
of joining with false unsettled spirits.`"

Two friends sitting by him one day,
and his heart being filled with the presence and love of God,
he sang praises to Him in a heavenly manner, observing afterward,
"`My heart is full--though I can truly say I have no desire
to speak but as I feel it spring from the Divine life.`"
Again; "`As I lay on my bed, very weak in body, I thought I could never die better,
for I felt my salvation sealed unto me.
O, love God--love God, for he is worthy.
You may love any thing else too much, but you can never love God too much.
Oh! what hath he done for my soul! He hath given me everlasting
comfort--It is enough--it is enough indeed.`"

"`There are two things,`" said he, "`which are my great satisfaction.
The first is,
that ever since the Lord manifested himself to me
I have freely given myself up to his requirings,
and delivered his word faithfully; and have not sought to please men,
neither did I look for great things.
What I desired was, that I might have a place among the sanctified.
Secondly, I have always been against libertine spirits,
and have had no familiarity with them.
These things are now my comfort.`"

At another time he broke forth in this manner: "`Oh!
I have seen glorious things, yea, such things as I never saw before--I beheld a friend,
lately deceased, in a glorious place, and that I was to be with him,
and I said it is enough to be there.
Oh, such salvation I am glad I can say, O death, where is thy sting! and grave,
where is thy victory!`"

Some friends sitting by him,
he related to them how the Lord had raised him up from nothing to bear a testimony for
his name and Truth--and that wheresoever the Lord by his spirit had drawn him,
he had endeavoured to follow him, and sought not favour or interest from men.
He also warned the negligent to be diligent and faithful,
and come up in the service of Christ; "`for,`" said he,
"`the Lord will cause a dreadful day to overtake the disobedient and negligent--It
is sealed to my soul that it hastens on apace.`"

Being in great weakness of body, he said,
"`I desire to be dissolved and to be with Christ; but the Lord`'s will be done.
The Lord`'s presence is here.`"
He gratefully acknowledged the Divine support and consolation
he had experienced in the course of his illness,
observing, "`I never wanted comfort from the Lord in this time of sickness.
Friends, it is an excellent thing to have a conscience void of offence towards God.
Keep your hearts clean.
I have discharged my duty to all people,
so that I find nothing but that I am fully clear--I am fully clear.`"

A little while after he broke forth in melody to the Lord,
praising his goodness and mercy, saying, "`O, Lord God,
though my exercises and pain of body abound,
thy life and power much more abounds and carries me over all--Worthy, worthy,
worthy art thou, O Lord, of all honour, thanksgiving and praise.`"
He fervently besought the Lord to be with all his faithful labourers the world over; and,
if consistent with his blessed will, to grant him an easy passage out of this world.
This petition was remarkably answered, for he soon fell into a sweet sleep,
and after some hours awoke and requested a friend present
to lay his head in a better position for dying,
which being done, he said, "`Now I will fall asleep`'and immediately departed this life,
as though he had fallen into an easy slumber.
He died the 12th of twelfth month, 1705, aged twenty-five years.

[.asterism]
'''

DANIEL BOWLY, JR. son of Daniel and Sarah Bowly, of Cirencester, England,
was a young man of good understanding and amiable disposition; the pliability of which,
together with an employment which exposed him to many temptations,
promoted a wide deviation in his conduct from the
religious principles in which he had been educated.
Of this deviation he became painfully sensible during the course of a long illness,
which he acknowledged to be a mercy from that Divine providence whose fatherly
care had many times preserved him from sudden death while unprepared.

In the commencement of his sickness,
his mind seemed to be deeply affected with the danger of his situation,
though he expressed but little.
As the disorder increased,
he remarked how exceedingly awful the prospect of the final change appeared,
earnestly desiring that he might be prepared for eternity,
and experience the Divine presence to be near, when the time came.
He now saw that his past conduct had been very erroneous, which caused him much sorrow,
but he observed that his supplications for forgiveness, during his illness,
had been attended with such sweet refreshment as
to induce the hope that they would be availing.
Yet at other seasons,
his sins appeared so great that he could hardly entertain
a hope it would be well with him.
"`What can be expected,`" said he, "`from a deathbed repentance?
That is a time when all would gladly be saved.
There will not, probably,
be an opportunity given me of proving my sincerity by an amendment of life,
so that men may doubt it; but the omniscient Being knoweth how far I am sincere,
and I hope, if it really be so, it will be accepted by Him.
Yet there is nothing equal to a proper dedication of time +++[+++while]
in health.`"

At another time he said, "`I hope the Almighty will forgive my sins.
It is mercy alone that can save me,
who have devoted so much of my time to business and the amusements of this world--pleasure,
as it is generally called; but it is a strange sort of pleasure.
It is pain, I feel it +++[+++to be]
pain.`"
Again, "`What I have to deliver, is from a prospect of the awfulness of death,
which in a short time will be my lot.
Mankind in general are certainly under strong delusions;
yet how kindly the Almighty condescends, from time to time,
to give a degree of his light and help!
But man may outlive this day of grace, which,
through the merciful mediation of my dear Saviour, is now extended to me.`"

On another occasion he observed,
"`I long that my friends would begin the work of religion in the life of it:
for if the first offers are slighted,
Oh! how does the visitation deaden on the mind!`" "`How comfortable
would it be to meet my relations in that state of happiness,
where I believe a residence to be preparing for my soul.
I believe the Almighty detains me here as an example of his great mercy,
and as a warning to some;
but I earnestly entreat that none will depend upon the same singular act of mercy.`"
"`All the friendships of this world must be given up--and if the mind be not
illuminated with an immediate proof of the presence of our dear Saviour,
yet it should be resigned, and prepare for the reception thereof,
by a surrender of everything which does not appear
consistent with a state of preparation.`"

At one time he remarked, "`In the forepart of my illness, a few times,
I asked for recovery if consistent with the Divine will,
with desires to be strengthened to lead a different life from my past,
and serve that good Master whose doctrines I have, as it were, trampled under foot;
but I have since seen the favour it may be to me, to be taken from such a trial.`"
"`What a favour it is to be members of our society
Its rules forbid nothing that is good for us.
How earnestly do I wish that my near connections in particular may keep to the truth.
Though the path may appear hard at first,
yet as they follow their Leader with a single eye, it will become more easy.
There may be times of withdrawing of the Divine presence,
and then the enemy will seek to enter; but by earnest supplication,
preservation will be granted, and at times,
a comforting foretaste of future happiness--the prospect of getting
every day nearer to such an incomprehensible reward,
is a favour beyond expression.`"

"`How little satisfaction results from a life of pleasure; attending places of diversion, etc.
Ah! the disappointments such meet with!
I believe bitter portions are often their lot.`"
Observing also, that he had been struck with the conviction,
when at those places of amusement, that he was far more blameable than his companions,
who had not had so guarded an education, and however innocently some of them might go,
it was not so with him.

One morning, inquiring if tomorrow would not be meeting day,
and being answered in the affirmative, he said, "`I almost long to go.
How pleasant is the thought of being retired there from the world,
when the generality of the people are in the height of its engagements.
How foolish and unwise are men who are bartering their souls for gold,--paltry gold!
The too eager pursuit of it, is a great hurt to some of our society.
If I were to recover, and found business stood in my way to peace of mind,
I would give it up entirely, or do but little and live accordingly.
What signifies grandeur or curious food?
The taste goes no further than the mouth, and then it is over.
If some men heard me talk thus, they would think me foolish,
but in this I am wise and know what I say.`"

A friend asking him how he did, he replied, "`I am very weak,
but I hope I shall be willing to bear everything
the Almighty may be pleased to lay upon me,
so that I can but just get within the gates of peace.`"
At another time, "`I wish I had served my dear Saviour in my health!
Oh! he is a kind Master.
How much time have I lost!
How distressing must be the situation of those who are sleeping the sleep of death,
until the last trumpet be sounded in their ears.`"

Several friends being in his chamber one evening,
he spoke of the gift of the Holy Spirit which is
dispensed to all mankind through our Lord Jesus Christ,
and earnestly recommended an immediate compliance with its sacred discoveries,
"`for,`" said he, "`since these illuminations are not at our command,
it is very unsafe to trifle with them, by giving way to the suggestions of the enemy;
but rather +++[+++let us]
resign whatever may be called for,`"--adding,
"`Can we not return a part to Him who gave the whole?
What if it deprive us of a few luxuries?
We can have but food and raiment,
which only differ a little in kind between rich and poor.`"

"`Our profession,`" said he, "`is a very exalted one, and if we keep to it,
would make us as lights in the world.
Our religion teaches us to believe in immediate communication with God,
through his beloved Son, which is an unspeakable privilege to all who attend to it;
and wonderful condescension, that He who is Lord of all, should thus notice poor man,
and time after time, be visiting +++[+++us]
with the offers of his mercy, to insure our happiness.
+++[+++These]
visitations we should be very careful not to reject, as being a common favour,
and think we will accept them at some future time;
for though the Almighty is long-forbearing and delighteth in mercy,
we know not when may be the last offer of his grace to assist us in the work of salvation.
What a dreadful thing would it be to withstand the last.`"

Speaking of the evidence he had of his future peace, he said,
"`I have a clear view that I shall be received into the kingdom of rest and peace.
I see the gates of heaven standing open to receive me,
and thousands of the just waiting to embrace me.
I desire but just to get within the pales of safety, to be in the presence of the Lord,
and to behold his glorious countenance.
O death, where is thy sting?
O grave, where is thy victory?
Christ taketh away the sting of death.
My dear Saviour is reconciled to me--I know he is.
His mercy is very great.
I cannot speak enough of his mercy.`"

It being remarked, how rapidly the preceding three weeks had passed, he replied, "`Yes,
and perhaps there are some who have not done any thing in the time;
which is a serious consideration, for in one week a man may be taken sick and die,
and if we do not close in with the visitations of God, in time,
we shall be lost forever.`"
Again, "`Let us be earnest in making ready for the glorious kingdom of rest and peace,
where, Oh, that we may enter!
And all may if they will.
Let us endeavour to do a little every day; let none be discouraged,
though their progress in religion may be slow, yet let them keep on in their little way.
I believe our kind Saviour may, at times,
withdraw his sensible presence from us to try how our faith will continue;
yet if we hold on, our reward at last will be great,
as much as those who feel a present one.`"

At another time he said, "`Be religious,
and then you will have our Saviour`'s arm to lean upon.
Oh! he is a merciful Saviour!
I have found him such; an easy Master, a kind Friend.
Ah! how I regret that I neglected serving him for some years.
Think what a superior education we have had, to most;
what a nice institution is ours--the peculiar institution of God,
and I believe it is not to die away, although some of our society have gone from it,
for whom I am sorry.`"

"`I believe great advantage may arise from frequently comparing time with eternity;
an awful eternity!
It appears to me exceedingly awful!
Heaven and hell are placed before us.
We have our choice; and we know what wretches hell is composed of--foul minds,
full of remorse forever, for their worm never dieth.
On the other hand, in heaven there is great harmony.
Oh!
I have had beautiful prospects!
I have seen the innumerable company of angels, and the spirits of good men.
But how is it?
We are ashamed of not complying with man, and not ashamed of doing so to God.
We can apologize to men, and say we are sorry we did not do so or so,
and we can directly commit neglect before God, and feel no sorrow for it.
Oh! what mercy there is!
In great wisdom and unspeakable kindness is the good Mediator given,
to reconcile us and work redemption in us.
Do not let us fear man; what is he?
Look upon me and see a poor weak thing that can hardly speak.`"

After this he was much exhausted, and desiring to be put to bed,
uttered the following short ejaculation: "`O Lord God Almighty,
be thou pleased to look down upon, and be with us.`"
It was with difficulty he got to bed,
and for some hours his symptoms seemed to threaten dissolution,
but after having slept some time he revived.`"

Cautioning some of his friends to beware of the incumbrances and fatigues of business,
he observed,
"`It will not do for those who have been all the week in the hurry of business,
to go to meeting and appear before the Lord in form only.
A man whose time is wholly engrossed in business in common, +++[+++although]
he goes to meeting pretty constantly, and sits there two hours,
yet it is to be feared his thoughts will be engaged
on that which takes up the greater part of his time;
and if it be so, it is great mockery of God.
Neither will it do to go in an outward show of dress and address,
if not true worshippers of the Lord in spirit and in truth.
They must daily give up their minds to him; daily retire to worship him.
I know a man ought to provide for his family, and carry on a proper business,
which I believe to be right, but it should by no means be the first object,
for riches will be nothing in the end.
What would I give now for all the world?
Nothing at all.`"

"`I don`'t regard what the natural man may advance in opposition
to the doctrine of giving up all for the sake of religion.
I am now upon the brink of death to the body, but opening into the life of the spirit.
I am going to live forever;
and I am certain nothing will do but giving up every
earthly obstruction for the cause of God.
Make him a sacrifice; offer up all you have; offer up your lives to Him,
as Christ did his for your sakes and mine.
Perhaps some may, from the strength of health and abilities,
be ready to conclude that what I say proceeds from weakness.
I know it does not, but that it is the truth, and you will all find that it is so:
that man who trusts to the strength of his own mind or natural understanding,
will be wrong, for nothing will do without God.
Now remember this; think of it upon your deathbed, and you will feel that it is true.`"

The 12th of the eighth month he said to one of his sisters,
"`How many times have I been preserved from death! times more than I can remember.
Ah! how often, sister, have some of us been raised, as it were, from death.
We should often think of it, and how we have answered the kind intention.
It may not be so again.
The next may be the last time.
Then do let us begin to prepare and do everything that is required of us.
I believe plainness of dress is.
We are indeed a chosen people, and what may not be wrong in others, is so in us.
Plainness of dress is an hedge about us.
The world is not then seeking our company.
Do remember what our Saviour said, '`Whosoever denieth me before men,
him will I also deny before my Father who is in heaven.`"
After this he impressively said, "`The enemy is still very busy with his insinuations,
and would persuade me that all is done, and so lead to neglect,
but I must watch and pray to the end,
and be very earnest with the Almighty to continue his favours
and that he will support me through all.`"

For some time he was proved with deep poverty of spirit, added to great bodily weakness,
but he earnestly desired to be favoured with patience; observing,
"`It is very trying to bear such great lowness and sinking of body and mind.
What can I do but endeavour patiently to bear it, looking constantly to the Almighty.`"
His strength being considerably increased for a few days,
the possibility of a recovery was mentioned to him,
which seemed almost more than he could bear, but after a pause he said,
"`In this also I will endeavour to seek after resignation,
and keep mine eye to my Saviour, who I ardently hope will now take me,
having in kind mercy so prepared me for my change.
Can it be, after the near prospect I have had +++[+++of death]
that I shall enter life again; I must endeavour, earnestly endeavour, after patience.`"
Some hours after, being asked how he was, he replied, "`I feel myself quite resigned.
I have supplicated for patience,
and hope I shall be contented to live if it be the Lord`'s will.
I know he can preserve and keep me.
Indeed I have experienced such resignation,
that I think I could feel pleasure in living that I might bear my cross in the world.`"

He was preserved in a state of humble, patient waiting,
and expressed but little for some days,
but the sweetness and solidity of his deportment evinced
that his spirit was centred to the Source of Divine life.
On the 1st of ninth month he remarked,
"`The state I expect to enter is that of calmness and peace, divine peace;
the purest spirituality.
I hope to live in the presence of God and to feel constant support from him,
and I do not wish to know more.`"
The following day he was very weak, and left his chamber with reluctance.
Soon after, he was seized with so violent a fit of coughing,
that the hour of his dissolution seemed near at hand.
In a short respite from the paroxysms,
he triumphantly said--"`I am happy--I am happy--If I never speak more,
give my dear love in Christ Jesus to all my friends.`"
After getting into bed he remarked,
"`Death is awful! very awful! but I have full faith in my foundation.`"

At another time, "`I believe my dear Saviour is ready to receive me into purity,
and that is what all good minds desire to enter into.`"
In the evening, some one remarking how hard it rained, he said,
"`I like to hear it--the sound of it is solemn--it is the work of the Almighty.
The withdrawing of the sun, and darkness,
is like what good souls experience in the work of redemption,
when Divine light is withdrawn from them.
In these seasons, what strange ideas is the mind tried with,
such as are very apt to cast down the timid--but there is a sweet support sustains,
though at such times not sensibly felt.`"
On the 3rd, he seemed anxious to be gone, and prayed thus; "`O,
Lord God Almighty! have pity upon me.
It was thou who created both soul and body.`"
Some time after, he said to a near friend,
"`I believe the enemy has now almost done with me.`"

On the 4th he was very weak, but calm and composed,
remarking that he was going to the Father and the Son, and bade his friends farewell.
About twelve o`'clock he took an affectionate leave of two cousins who waited on him,
and his voice became so weak that little he said could be heard:
the last sentence which was distinctly understood
proved as a seal to the foregoing truths,
viz. "`I have the satisfaction to say that I have been washed in Jordan.`"
He put off mortality in the manner for which he had often prayed,
without a groan or even a sigh, aged twenty-five years and eight months.

[.asterism]
'''

HANNAH QUINBY was the daughter of Josiah Quinby, of North Castle, Westchester county,
New York.
She was enabled, through Divine assistance,
to maintain an innocent life and conversation,
was an example of obedience to her parents from childhood,
a diligent attender of religious meetings,
and would often use her endeavours to excite her brothers
and sisters to faithfulness in the same important duty,
and also to the frequent perusal of the Holy Scriptures.
She was favoured with the enjoyment of almost uninterrupted good health,
until the summer of 1820, when she took a heavy cold, attended with cough,
which continued for several months, and terminated in consumption.

She was confined to the house nearly three months,
and in the early part of her illness apprehended her recovery
doubtful and was often under close exercise of mind,
yet she said little as to her future prospects.

About the beginning of the second month 1821,
she appeared like one who had gained that victory over sin, which is the gift of God,
through Jesus Christ our Lord, to the humble and penitent seeker.
Having through adorable mercy received an evidence of salvation,
she expressed her entire resignation to the Divine will,
and that the feeling of her mind was joy and quietness,
evincing the truth of that saying of the Psalmist,
"`The righteous shall be glad in the Lord and the upright in heart shall glory.`"

Although the peace of God which passeth the understanding,
and love to Him and to all her fellow creatures seemed
the almost constant clothing of her redeemed spirit,
yet there were seasons in which she was tried with doubts and fears, saying,
"`I am afraid that I am deceived--my peace is so great--I am fearful that I have
not suffered enough to be worthy of the peace and comfort I now enjoy.`"
The pain and languor of a long and tedious illness she bore with christian patience,
and was never heard to murmur, or utter a complaint,
but freely and cheerfully submitted to the disposal of that
kind Providence who doeth all things well.

On the 7th of the second month, recovering from a fainting fit, she said,
"`Oh! that I might lay down my head in the mansions of bliss--it is all
I ask--it is all I desire`"--then addressing the family--"`I want you
to prepare for such an hour as this--it will soon overtake you--when the
grasshopper shall be a burden--Although Paul may plant and Apollos water,
it is God that giveth the increase.`"
Alluding to the care that had been taken of her in sickness,
and the exertions used for her recovery, she proceeded;
"`You have had the physician and done all you can
for me--Oh! don`'t mourn for me--don`'t hold me,
if my time is come.
Oh! the sweet love that I feel to flow towards you, my dear brothers,
was never so strong as since I have been cast on this bed of sickness.
I want you to go to meetings--you will never have cause to repent of it.
May you love one another and not provoke each other, and if provoked,
do not revile--it is better to suffer wrong than to do wrong.`"

The 9th, she expressed as follows;
"`The day is approaching when we must all appear before the tribunal bar of Justice,
there to be tried for the deeds done in the body.
If I had a thousand--yea--ten thousand worlds,
what would it avail me in such an hour as this--they
would be no more than a drop from the bucket,
or as the dust of the balance.
O, my dear brothers, I want you to endeavour to live in the fear of the Lord,
for one hour in his presence is worth a thousand elsewhere;
his hand is not shortened that it cannot save, nor his ear heavy that it cannot hear.
Dear father and mother, I want you to be faithful,
that we may meet in the mansions of bliss.`"

To her brothers and sisters she said,
"`I have craved that you may be preserved from going in the road that leads to destruction.
I desire you to choose the Lord for your portion,
and the God of Jacob for the lot of your inheritance.
It will be like crowns upon your heads, and chains of gold about your necks.
I want you to give up while you are young and forsake
the vanities and pleasures of this world--in so doing,
you will never have cause to repent.
Cast your care upon Him while you are young,
for youth are not exempt from the stroke of death--you now behold it.
Oh! the comfort I have taken on this bed of sickness--I feel as if I had
been in heavenly places in Christ Jesus--don`'t mourn for me,
but rather mourn for yourselves.
It seems as if His everlasting arm was round about you--there is balm in Gilead,
and a physician there, who sits as a refiner to purify the sons of Levi.
Oh! that you may be healed and cleansed, that your robes may be made white as wool.
He is not a God afar off, but he is near.
I know what I say.
My heart glows with love towards you that have grown up with me.
May you forsake the friendships and pleasures of this world,
for the day is approaching when we must all appear before the bar of Divine justice,
there to give an account for the deeds done in the body.
We cannot do the work one for another, but each +++[+++of us]
must do his own work: be entreated to take his yoke upon you,
for his yoke is easy and his burden is light.
I want you to give up while young;
there is no time so acceptable as in the days of youth; I have experienced it;
and what a comfort it has been to me on this bed of sickness;
it has eased my pains and made my bed comparable to a bed of roses.`"

On the morning of the 16th of third month, she seemed nearly gone, but reviving a little,
said, "`Sweet Jesus, give me ease, for in Thee is life and peace;
thou art near at hand to succour all those that put their trust in Thee.`"
Soon after this, she took an affectionate and solemn leave of all the family,
earnestly pressing on them the necessity of being faithful to the revealed will of God,
and that a preparation for everlasting happiness must be effected while here.
"`There is no returning,`" said she, "`to tread the path over again;
there is no repentance hereafter;
I fervently desire that all may be engaged to begin this great Work.`"

It seemed difficult for her fully to convey to her
brothers the ardent solicitude she felt for them,
saying, "`Do remember your Creator in the morning of your days.
I want you to choose the good that you may lay down your heads in peace.`"
To the eldest she said,
"`I want thee to be faithful in the discharge of
thy duty to the younger branches of the family.
I think much depends on thy faithfulness in encouraging them to attend meetings,
and in keeping them together, on the first day of the week.`"
Some of the neighbours coming in, she addressed them: "`Dear people,
the day is approaching when you must appear before your final Judge,
and there be tried for the deeds done in the body.`"

Several near connections coming to visit her, she imparted suitable advice to them,
exhorting to faithfulness in the discharge of manifested duty;
after which she was very quiet and calm, as one whose day`'s work was nearly done,
and with much sweetness ejaculated, "`O Father, now let thy servant depart in peace.`"
On the 18th she said to a person present, "`I desire thee to put away pernicious books,
and to read good books, and attend religious meetings.
If thou wilt truly confess thy sins, they will be blotted out and remembered no more;
although they be as scarlet or as crimson dye,
they will be washed and made white as wool or snow.`"
She then observed to him,
"`What an awful thing it would be when brought before the bar of the Almighty,
to hear the voice, Depart from me ye workers of iniquity,
I know you not--and then to be cast into utter darkness, where will be weeping,
wailing and gnashing of teeth.
Thou hast no more lease for thy life than I have.`"

She then addressed her father, saying, "`I desire thy everlasting welfare.
Oh! that thou mayest lay down thy head in peace.`"
And to her mother, "`Don`'t mourn for me; I shall be better off.`"
The day before she died she observed to her parents, "`I must leave you.
The Lord will bless you; he has blessed you.`"
A few minutes before her departure,
with great sweetness of spirit she took a last leave of her mother,
embraced her in her arms, and said,
"`I must leave thee,`" and looking on those around her with a solemn and composed countenance,
without a sigh, quietly breathed her last, entering, as we have no doubt,
into that everlasting rest of which she was permitted to enjoy a blessed foretaste.

She died the 24th of the third month, 1821, aged twenty-five years.

[.asterism]
'''

JOHN PIM, son of Samuel and Margaret Pim, of Waterford, in Ireland,
was a young man of an amiable disposition.
He was early deprived by death of his beloved father,
and after serving his apprenticeship in Cork with fidelity,
he returned to Waterford and resided with his mother and sisters,
to whom he was an affectionate son and brother.
He inherited considerable property, and did not engage in any business.
His leisure presented a temptation to indulge in some amusements
which were adverse to the increase of true religion in his heart.
He took particular delight in hunting,
an employment very far from promotive of that meekness and tenderness of spirit,
and that watchfulness and circumspection,
which are incumbent on all who profess to be the followers of Christ;
and which so highly become us, as dependent creatures, liable,
as in the twinkling of an eye, to be summoned before the tribunal of Infinite justice.
In the midst of prosperity and enjoyment, in the 25th year of his age,
he was suddenly arrested by mortal disease.

He was taken ill on the 13th of the seventh month, 1811.
During the four following days,
his physicians employed every means which appeared likely to relieve him, but in vain.
For a short time some favourable effect appeared to be produced,
but symptoms of extreme danger quickly returned,
and his situation was pronounced to be beyond the reach of human aid.
On being apprized of this,
his agitation and anxiety indicated a strong sense
of the awful prospect that opened before him.
To one of his sisters he said, "`My dear sister,
the sentence is passed! `'Tis an awful thing to die!
Dost thou think I can make my peace with God?`"
earnestly repeating the inquiry, "`Can I make my peace?`"
desiring his sisters to pray for him.
He exclaimed, "`I am in such pain, I am afraid I cannot pray for myself as I ought!
When I might have prayed, I did not do it as often as I should.`"
He bade his mother and sisters farewell, saying, "`Farewell, once more,
whilst I am able to speak, for by and by I shall not be able.`"
He said, "`What a blessing health is, and how many thousands there are who trifle with it!
If I had but a short time longer, I would devote it to the service of the Lord.
I am a sinner,
a miserable sinner! though I have not committed any of what the world calls gross sins,
yet I have neglected serving the Almighty as I should have done.
He is a most gracious God, worthy to be served.
It is better to be a doorkeeper in the house of the Lord,
than to enjoy all the gratifications of this world.`"
He then prayed earnestly, "`Oh Lord! Be pleased, if consistent with thy will,
to make me the very lowest doorkeeper in thy house.`"
And then, as though sensible of some degree of access to Him who heareth prayer, he said,
"`Oh, I have a most merciful Saviour to deal with me!`"
To a friend whom he much and justly esteemed, he said, "`I might have taken thy warning:
thou now seest the state I am in.
What shall I do?
How long dost thou think I can continue?`"
On being told the time was reduced to hours, he seemed awfully affected; and exclaimed,
"`I have so much to do, and time is so short.`"

On being asked what he had to do, he replied, "`I have my peace to make,
and to settle my outward affairs, but that seems impossible to be done now.`"
On being told that much could be done in a little time, if he could be composed, he said,
"`Dost thou think so?`"
and then gave directions for that purpose.

After he was relieved from this last worldly care, he appeared more tranquil,
and endured his bodily sufferings with patient submission.
To a friend who stood by his bedside, he expressed, with much feeling,
his sense of the awfulness of his situation.
On being reminded that the Lord is merciful, he exclaimed, "`O mercy,
mercy!`" and sometimes, as if enabled to lay hold of this mercy,
in a sense of its extension towards himself, he added,
"`For thy mercy endureth forever:`" yet thinking himself unworthy of it,
on account of his own forgetfulness.
To the same friend he very sweetly observed, "`Ah! thou often advised me,
if I had but minded it.
Do pray for me--wilt not thou pray for me?
I am a great sinner--shall I obtain salvation?`"
He acknowledged that the errors of his past life were fully brought into his view,
and deeply affected him;
and that it grieved him that he had not attended week-day meetings;
but hoped the young people would now attend them,
and that they would before long be different from what they had been;
intimating that his illness and death ought to be a warning and produce a change.

After repeatedly mentioning his desire to see his aunt, and being told she was come,
he answered, with emphasis, "`Bring her up, bring her up with the family.`"
She came immediately--and then addressing her, he said, "`My dear aunt,
I wished to see thee; I am about to die.
It is an awful thing to die! pray for me! stay by me, and see me die,
if thou canst bear it.
Oh, I have a short warning! if I were spared a little longer,
I would live a very different life.`'

Several young men, his relatives and intimate associates, being present,
he took an affectionate farewell of them, and declared his hope,
that his death would deeply impress on their minds the uncertainty of all things here;
adding, "`they are vanity! yea,
lighter than vanity! and all the pleasures of this world are but for a moment.`"

On seeing a particular friend, he said, "`My dear +++_______+++, I wish thou hadst come sooner;
tell thy sons, with my love, to read this lesson,
and take care of themselves:`" and to his immediate relatives he repeatedly said,
"`Serve the Lord.
I hope through mercy, I shall be admitted into the Lord`'s vineyard:
at first it seemed very hard for me to die; but I now find it has been made easy,
more so than I thought was possible.
Oh!
I have a most merciful Saviour to deal with me: now I can testify that my Redeemer liveth.
I hope we shall all meet in Heaven.`"
He further remarked,
"`Oh I when the awful sentence was passed '`Time to thee shall be no longer,`'
I had as little thought this morning of being in the state I now am,
as any one here,`" and expressed his fear that some present were not prepared;
often desiring, that those about him, and every one, might be instructed,
particularly the youth.
To a young man, who was much affected with this impressive scene, he said, "`Be prepared;
be prepared;`" recommending that none should defer making their peace till a dying hour,
and added, "`What can be expected from a deathbed repentance?
It is only to serve ourselves.
Oh!
He only that rules in heaven above and in the earth beneath, is worthy to be served,
for his mercy endureth forever, even to the very ends of the earth.`"

He several times said, "`Farewell, farewell, in the Lord!
I hope we shall all meet in a better place.`" and near the close he said,
"`I have no doubt, no,
not the smallest doubt of an entrance into rest,`" or words to the same effect.

During the last solemn and deeply interesting hours of this dear young man`'s life,
several friends were favoured to join his wrestling spirit in supplication;
this appeared consoling to him,
and we humbly trust was regarded by the Shepherd of Israel, whose compassions fail not.

[.asterism]
'''

MARY ANN HARRIS, wife of John Harris, of Darlington, England,
deceased the 11th of fifth month, 1838, aged 26 years.

Her removal presents a striking proof of the uncertainty of all temporal things,
and the necessity of having the affections fixed in heaven.
She was married a short time before her death,
and in every respect comfortably settled in life--but was soon laid upon a bed of languishing,
and called to leave all her earthly enjoyments.
But the messenger of death did not find her unprepared.
She had been taught in the school of Christ the value of true religion,
and frequent attacks of illness had led her to anticipate, at no distant period,
the full fruition of its blessings in another world.

The following memorandum, made on her 22nd birthday,
will serve to illustrate the exercise of her mind:
"`I have been reading over the notes I made on my last +++[+++birthday]
and I wish to draw a comparison between my feelings then and at the present time.
I desire this self-examination may be made in sincerity, meekness and humility.
I think I can say that I feel I have greatly erred by not
more diligently persevering in watchfulness unto prayer.
I believe the blessed influence of the Holy Spirit has very often been shed upon me,
and the still small voice has sounded in my mental ear, '`Come,
that thou mayest have life.`' Alas! how much have
I lost by not giving more heed to the heavenly Monitor.
I feel more than ever I did before that my heart is very corrupt,
and that of myself I can do nothing to cleanse it.
Yet, I feel hope and comfort in those precious words,
'`The blood of Christ cleanseth from all sin.
Oh, I desire and fervently pray that I may know my heart to be sprinkled with that blood.

"`Fourth month 12th, first-day.
A precious day to those who love the Lord.
I trust I have in some degree been enabled to worship Him in spirit and in truth,
and I have indeed longed to know more of this worship--I
have this evening been sweetly favoured in prayer.
Oh, it is a delightful and unspeakably gracious privilege thus to
be permitted and even required to pour out all our wants and weaknesses,
all our trials, all our hopes and fears,
before one who is ever ready both to hear and to help.
My heart is joyful, for I am as it were resting beneath the covert of my Father`'s wing.
How refreshing are such seasons as these--how they show forth the goodness of the Lord!
But I must not expect it always thus.
I know that in the world I shall find tribulation,
if in the world to come I would have life eternal.
Dearest Father! for the Saviour`'s sake, guide me by thy Holy Spirit in all things.
Show me the way in which I must walk--Strengthen and uphold me in the hour of temptation,
and enable me to give myself wholly unto thee.`"

On her 26th birthday, she remarks,
"`I have again had the prospect of an awful eternity brought very near to my view.
I have again seen the vanity and insufficiency of all earthly things; and,
(Oh that my heavenly Father may enable me to perform it,) I have again resolved, looking,
I trust, for help from above, to enter into fresh covenant with the Lord,
to devote myself to Him in everything.`"

During her illness her mind was sweetly sustained in peace,
a favour which she frequently acknowledged with feelings
of deep gratitude to her heavenly Father.
On one occasion, when alluding to the early visitations of Divine grace to her soul,
she said, "`When I was about 8 years of age, my dear father,
who was then upon his deathbed, took me by the hand,
and after imparting much affectionate counsel, encouraged me to trust in the Lord,
who would be a Father to me--adding '`He is a Father to
the fatherless.`' Though I have been a poor wandering creature,
yet this has been fulfilled to me all my life long.`"

Alluding to the peaceful state of her mind, she said, "`From the first,
I have never been permitted to doubt.
The love of my heavenly Father seems always around me.
I feel afraid of returning to the things of time, having been favoured to resign them all.
I have no strength of my own.
I often think it quite a miracle that one so poor and weak,
should be permitted to trust so entirely in the mercy of my Redeemer.`"
At another time, "`I am like a little child, casting all my care upon my heavenly Father.
He will not suffer me to be deceived.
I feel his love around me.
I often think what a mercy it is my mind has been
so long preparing for this solemn change.`"

On the day of her death, her sufferings became extreme,
and she prayed for a little relief, saying: "`O most merciful Father,
give me a little ease.
Blessed Saviour, take me in mercy.
Grant me patience--thou knowest my sufferings.
O most merciful Father, send the moment of release.`"
Again she exclaimed, "`O most merciful Father, take me--O take me.`"
She soon after peacefully passed away,
giving evidence that unto her the victory was granted
through our Lord and Saviour Jesus Christ.

[.asterism]
'''

The subject of the following memoir, ANNE HARFORD LURY,
was the daughter of John and Sarah Lury, of Bristol.

She was of a retiring disposition, but possessed a kind and affectionate heart.
A tenderness of conscience and scrupulous adherence to truth,
marked her character in very early life.
A few pieces which she then wrote, show the thoughtful habit of her mind,
and induce the belief,
that even in childhood she was frequently engaged in self-examination.
About the close of the year 1808, she lost her dear father,
an event which appears to have made a deep and lasting impression on her mind.
In one of her memoranda, dated in the year 1811, she mentions his decease;
accompanied with a desire to meet on that angelic shore, where,
in his Saviour`'s presence, she believed him to be partaking of unmixed joy.
At this time she appeared to be often engaged in religious meditation,
in watching against the assaults of the enemy of her soul,
and in seeking for ability to live in the fear of the Lord.

In the year 1812, it pleased Divine Providence to visit her with a fever:
during the course of this illness, she passed through some mental exercise,
which tended to bring her increasingly under the power of Redeeming Love.
From this period it became more evident to those around her,
that her thoughts were frequently abstracted from terrestrial objects and selfish considerations,
and fixed on Him whom to know in life eternal;
and that he was gradually drawing her nearer to Himself.

In 1816 her sister Maria died with consumption when about fourteen years of age.
In a letter to a friend after this afflicting event,
she mentioned that she found she must not dare to grieve, for it was the Lord`'s will;
and she believed it was designed as a signal mercy to herself.
In another letter she says,
"`My feelings and affections appeared to be superior to natural ties,
and my heart seemed fixed on heaven, resolved on dedication.
I felt death to be awful; and thought I might be the next;
that this might only be the prelude to my own:
I cannot give thee an idea how I felt at the interment; exquisite natural feeling,
refined or checked by the command, '`Be still.`' We had a very impressive opportunity.
Nearly all the young Friends in Bristol attended,
and I think every heart must have felt the occasion.`"

From this time her health became impaired, and she was incapacitated for much exertion,
being frequently confined as an invalid.
It is a pleasing and consoling reflection, that during the whole course of her illness,
the early impressions of religious feeling were gradually deepening,
and the preparation for that awful change which a few short years were to produce,
was proceeding in her heart.
In some memoranda made in the latter end of 1816 she says, in speaking of true religion:

[.embedded-content-document]
--

I understand it to be a faithful and willing following of our Lord and Saviour.
I do believe that every sincere heart will be shown its respective line of duty.
My duty, I feel persuaded, is to be still, and quietly wait for the salvation of the Lord.
I do not entertain this opinion of duty from education or from prejudice;
but I feel it to be the will of God revealed in the secret of my soul.
When blessed with this silence of all flesh, when self is laid in the deepest abasement,
and I know no will of my own,
no secret aspiration or desire but what the Divine influence immediately inspires,
then and then only, do I feel perfect peace,
and a blessed foretaste of the saints`' rest.

I think it very dangerous for a tender mind to
be searching into different doctrines and controversies.
I find that the enemy is sometimes endeavouring to stagger my faith,
and on these points I have so great a disposition to reason,
that I am afraid to take up a book of the kind.

--

After alluding to the baptism of the Spirit as the only saving baptism,
and expressing her belief that those whose minds are Divinely enlightened
would feast largely in stillness on the saints`' communion,
she adds, "`they would need no outward ceremony,
they would know that they might obtain redemption and remission of sins,
and acceptance with God the Father,
through the merits and intercession of his Son Christ Jesus,
the Saviour of the whole world, who gave himself for us,
and died on the cross that we might obtain salvation.
'`Come unto me all ye that labour and are heavy laden,
and I will give you rest,`' said Christ to the multitudes.
'`Take my yoke upon you and learn of me, for I am meek and lowly in heart,
and ye shall find rest unto your souls: for my yoke is easy and my burden is light.`'`"

In a memorandum dated 2nd month, 1817, she says:

[.embedded-content-document]
--

I have often felt anxious to know what is real religion,
and have entreated my heavenly Guide to lead me into it,
however painful the surrender of heart and life may be; for I find that without it,
there is no true and lasting peace to be found,
and no preparation for the enjoyment of the Divine
presence in a state of perfect holiness hereafter.

I have at different times,
been desirous to know whether that profession in which I
have been educated is the right one for me to retain,
or whether any other form of worship will be more acceptable to God from me.
I believe my secret prayers were accepted by Him
who knew the sincerity in which they were addressed.
After waiting to be instructed, my desires are, at length, fully answered;
mine must be a religion of stillness and total resignation of self;
that whether the feeling of devotion be that of prayer, praise, gratitude or adoration,
I must be immediately influenced by the Spirit of Christ,
before I can feel union and communion with my heavenly Father; this,
whether words are used or not, constitutes the essence of worship.
I feel convinced, whatever the outward form of worship may be,
the only true and acceptable offering is a sacrifice of the heart;
and the more I feel of a devotional spirit, the more I am led to be still,
and not to look for instrumental aid; for I feel that Christ,
the inward Teacher and Comforter, is all-sufficient,
and that he is waiting to do me good.

--

The, disposition of this dear young Friend was so retired,
that little was known of the state of her mind;
though enough remains of her memoranda to show that mental conflicts and
discouragements at times attended her for the trial of her faith in Him,
whom she was ultimately enabled fully to rely on as her stay and support,
her Comforter and Redeemer, her only "`Hope of glory.`"

In the year 1820, the complaint from which she was suffering, advanced so greatly,
that hope of her eventual recovery was no longer cherished.
During this time she felt much consolation from religious meditation,
and manifested a desire that those around her might be brought
more seriously to consider their eternal interests.
She occasionally disclosed her views of the vanity of all sublunary things,
and the incomparable importance of those which were to endure through all eternity,
pressing her friends to use all diligence to make their calling and election sure.

On the 9th of the eighth month, 1820, she said, "`Mother,
I wish to explain more fully my answer to thee the other day,
respecting the state of my mind.
About two weeks ago I felt myself so extremely ill and declining,
that I apprehended I might not be afforded much more time.
I then queried with myself, '`Am I in a fit state to meet perfect purity?
I felt uncomfortable, and was made sensible of my extreme mental weakness.
No human help was likely to avail me; no works of my own were at all availing.
After some time I was made sensible that if I placed my reliance on the Redeemer,
all would be well.
The words, '`Look unto me and be ye saved,`' came forcibly into my mind.

"`Since that time I have been so happy, no one can tell or even think.
I want no outward sacraments; though, at one time I thought there was a need of it.
I have found great comfort in reading the Scriptures to myself:
many times I have not been in a fit state to receive good; at others,
when I have been uncomfortable or under discouragement,
some beautiful passages have been presented, which were very consoling,
such as '`The Lord is my Shepherd, I shall not want;
he maketh me to lie down in green pastures, he leadeth me beside the still waters.`"
I will never leave thee nor forsake thee.`'`"

About a week afterwards, writing to a friend, she says,

[.embedded-content-document.letter]
--

I hang almost between time and eternity; everything seems for the latter,
but I know God is all-powerful, and may be pleased to restore me.
I do not see the end fully, but I rely on Him.
My anticipations of approaching beatitude are sweet and frequent, and more calm,
more bright, than I can express.

In this awful moment, in past sickness, in comparative health,
I have been taught that God is the best, the only safe Guide.
To be a child of His, we must give up to do his will,
at least to strive to do it without reserve.

--

The awful change from time to eternity, anticipated in the above letter,
was yet distant about two months; it occurred on the 28th of the tenth month, 1820.
On the day preceding, observing her sister, she said, "`Dear Sarah,
I cannot enough impress on your minds the vanity and folly
of the world;`" and repeated something to the same effect,
when her younger sisters came into the room.
During the few previous weeks, she often spoke of the blissful state that awaited her;
and to one of her aunts she observed, '`Floods of bliss were in store for her.`"
But it was not until the night previous to her death,
that she felt fully at liberty to express her feelings:
she then aroused in an unusual manner, describing with animation,
how happy and delightful her prospects were,
and her gratitude to her Redeemer for having thus early prepared her.
"`I impute,`" said she, "`nothing to the creature, I impute all to the Creator;
I place all my hope of mercy in the merits of our Saviour, in faith in his birth,
his miracles, his death, his resurrection and ascension, his mediation and redemption.`"
Almost in an ecstasy of pleasure, she said, "`My prospects are bright, very bright;
you may try to imagine, but you can have no conception of my delight.`"

After having spoken for some time,
she took an affectionate leave of several of her relatives individually.
She requested to have the chapter of the Revelations read, containing the words,
"`What are these which are arrayed in white robes, and whence come they?`"
While the chapter was sought for, she fell asleep;
in which state she continued several hours, and at length, without again speaking,
quietly breathed her last.
