== Chapter 3

[.chapter-synopsis]
* Mary Post
* Richard Priestman
* William Rigge
* Samuel George
* John Airey
* Peregrine Musgrave
* Joshua Arnold
* George Benson
* Roderick Forbes
* Robert Fisher
* Ruth Padley
* Eleanor Perkin
* Richard Kinman
* Susannah Garton

MARY POST, daughter of Benjamin and Elizabeth Post, of London, was of a tender spirit,
sober behaviour, religiously inclined, and a lover of plainness in habit and speech,
and kept to it; but a disliker of pride and finery in apparel.
When but about eight years of age,
she was at a neighbour`'s house who desired her company, being solid and grave,
and the said neighbour having a daughter about fifteen years of age,
who loved this child well; Mary said to her, "`Anna,
what signify these fine things thou hast on?
they will not carry thee to heaven.`"
To which Anna answered, Pride is not in the things, it is in the heart.`"
To which the child replied,
"`But if your minds (i.e. those that wore them) were not proud,
you would not wear them.`"

She also signified to her mother,
that she much wondered at the great pride she observed
in some young ones who professed truth,
saying, "`I hope I shall never be like them.`"
Her mother thereupon said to her, "`I hope thou wilt never be like them;
but be an orderly child, that thou mayest be in favour with God.`"
At which she wept, and said, "`If I should love fine things, I must alter much:
what signify fine things when folks come to die?`"
Hearing some boys in the street taking God`'s name in vain, she said,
"`They take God`'s name in vain enough to frighten one.`"
She also said she should delight to go to meetings.

The day before she was taken ill, her mother sending her out on an errand,
and her brother being newly come out of the country, she desired him to go with her,
which he refused; at which she stood by him a while,
and then with a solid countenance said, "`Wilt thou not go with me?
It may be, the next time thou comest up,
thou mayest not have a sister to go with;`" as if she had a sense of her death.
In her sickness, which was violent convulsions; she often said, "`Oh! dear Lord,
if thou seest fit, give me a little ease:`" and lifting up her hands,
repeated such like expressions, and said, "`I had rather die than live;
through mercy I am not afraid to die.
I shall go to rest, where I shall feel no more pain.`"

Her mother standing mourning by her, the child looking upon her, said, "`Mother,
do not cry, let us be contented; the Lord can lay me low, and he can raise me again;
if I were dead, he can raise me again:`" then she repeated as before, "`Oh! dear Lord,
if thou seest fit or convenient, give me a little ease,`" and seemed earnest to die,
and go to rest.
Her mother said to her, "`My dear, why art thou so earnest to die;
the Lord can ease thee of thy pain, and give thee life?`"

She answered, "`One must once die, and if I recover I must or may be sick again;
and I had rather die while I am young.
If I should live till I am older, the devil may tempt me to be naughty,
and I might offend the Lord.
I am not afraid to die, through mercy I shall go to my rest;`" and said,
"`If I live I am satisfied, and if I die I am satisfied.
I am willing to die; I had rather die than live.`"
Her mother said, "`I shall dearly miss thee.`"
She replied,
"`I am willing to see my little sister (who was at nurse)
and my brother;`" and he was at school in the country.
Her mother said she would send for them: "`but,`" said the mother,
"`if any alteration should be before thy brother come, what wouldst thou say to him?`"
She replied, "`If I can speak, I will bid him be a good boy, and fear God,
that he may go to God Almighty.`"

She left him the little money she had; and some other things to her father, mother,
and two sisters.
Her mother desiring her to take something (as she
had before done) that was prepared for her,
she seemed to refuse, and said, "`What signify doctors and apothecaries,
if the Lord please to take one`'s life?`"
A little before her end, she lamented folks taking pleasure,
and not considering the love of God; and the last words she was heard to speak were,
"`Dear Lord God Almighty, open the door.`"
And so sweetly departed this life, the 12th of the Eleventh month, 1711.
Aged above eight years.

[.asterism]
'''

RICHARD PRIESTMAN, of Coldbeck, in the county of Cumberland,
was descended of honest parents.
His father received truth early, and finished in the same; and his son,
the said Richard Priestman, was educated in the way thereof;
yet was at a want till he found truth in himself,
and came to know the work of it in his heart, and came to be faithful thereto.
In due time, the Lord, whom he loved, was pleased to give him a gift of the ministry,
whereby he became a minister of the gospel,
and declared to others what great things God had done for him.

Though he was not large in testimony, yet his ministry was edifying,
comforting the weak travellers, who were on their way towards Zion,
often supplicating the Lord for the preservation of his people,
and that he would be pleased to continue his love and kindness towards them.
He laboured to keep peace, and things in order, where his lot was cast.
He was against that which tended to division and scattering;
he walked in the fear of the Lord, with fervent desires in his heart to Almighty God,
that he would be pleased to give him strength, that he might be preserved in well-doing,
and kept steadfast in the faith, which overcomes the world, to the end of his days.

In the time of his sickness, his spirit was borne up, to his great comfort,
and many came to visit him, to whom he expressed the comfort he felt in his heart.
The more his afflictions increased, the more his strength was renewed in his inward man,
and he would be often speaking to his family, and said, "`Know the Lord for yourselves,
and mind the teaching of his grace in your hearts;
you need not go far to seek for a teacher.`"
With the like expressions, he often exhorted them and many others who came to visit him,
and said to his neighbours, "`I advise you to make your peace with God,
whilst you are in health and strength; for when you are cast upon a sick bed,
you will have enough to bear your sickness.
Do not delay, and have your peace to make with the Lord at last.`"
With many more expressions he exhorted them,
and was much refreshed in spirit in having such opportunities.

The night before he departed this life, he called his family to him,
and took his last farewell of them, and said, "`Keep to truth, and do justly,
and do to every one as you would they should do to you; and the Lord will bless you,
and keep you from evil.`"
He finished his course in perfect unity with the brethren,
the 23rd of the Eleventh month, 1711.

[.asterism]
'''

WILLIAM RIGGE, of Coltshouse, near Hawkshead, in the county of Lancaster,
received truth in the year 1672, being the thirty-sixth year of his age.
A little after he received a gift of the ministry, in which he was faithful,
and endowed with a good understanding, in the mysteries of the kingdom of God,
and had a clear and sound testimony, and travelled much in the work of the ministry,
both in this nation and in Scotland, although he was a very tender-bodied man,
and troubled with a sore cough for many years.
It was his delight to be speaking of the things of God, and the mysteries of his kingdom,
to the refreshing of many.

Towards his latter end he was attended with great weakness of body,
so that he could not get to the meeting, or scarcely out of doors for many weeks,
which he bore with great patience,
and to the great comfort and refreshment of many that came to see him.
He was of a clean life and conversation, which answered his testimony.
In the time of his weakness he waited patiently for his dissolution, and often said,
"`I have done my day`'s work in the day time, to my great peace and satisfaction,
and have nothing to do but to die, and put off this earthly tabernacle,
being well assured of my eternal rest with the Lord:`" into which, no doubt,
he is entered.
He died the 29th day of the Second month, 1712; aged seventy-six,
and a minister about forty years.

[.asterism]
'''

SAMUEL GEORGE, of the parish of Landewybrevy, in Cardiganshire,
lived there with his parents till he was about twenty-one years of age.
In which place the excellent truth, being despised by many,
had not that place and dominion in the hearts of the people, which it ought to have;
and he was careless, like others, going on in the broad way,
playing and sporting therein,
and unconcerned for the everlasting welfare of his poor soul.
But the Lord met with him in the prime of youth, opened his ears,
and sealed instruction to him in a dream, or vision of the night,
as he lay slumbering upon his bed.
In which dream, or vision, he thought he was going to hear that called divine service,
and saw a man winnowing corn, which seemed to him to be good and sound,
but when raised to the wind, it was blown and scattered away, like white chaff,
towards the north.
And as he looked behind him, he saw a man who asked him, whether he knew what that meant?
he answered, "`No.`" "`Then,`" said the man, "`the chaff represents ungodly men,
who are as the chaff which the wind driveth away.`"

By this, and other dreams and visions which he had, he came under a concern of mind,
and cried out, "`What shall I do to be saved?`"
Then it pleased the Lord, in his infinite love and mercy,
so to visit the heart of this young man, that he came to know the Lord,
and was made willing to bear the indignation of God because he had sinned against him.
And the Lord by his invisible power wrought his deliverance,
notwithstanding he suffered him to be tried many ways;
and when under great and deep exercises, both inwardly and outwardly,
the Lord was pleased by his hand to help him in the time of need,
of which he was greatly sensible,
and experienced the great truth declared by the holy prophet of old, that,
"`Zion shall be redeemed with judgment,
and her converts with righteousness;`" although he had been
ready to think no one was exercised like him.

He often used retirement, and in the night-season, and at other times,
he waited upon the Lord, pouring out his soul in supplication,
and fervently prayed unto him in secret; and the Lord rewarded him openly,
and many times gave him the oil of joy for mourning.
On the 26th of the Sixth month, 1711, the Lord opened his mouth to declare in his power,
and to bear his testimony against unfaithfulness and disobedience to the Lord.
And the Lord made him also sensible,
and gave him a sight that his time was but short to work in his vineyard; so,
although his service was heavy and hard, he laboured diligently.

About six months after,
he travelled and visited Friends at their meetings in Radnorshire;
and about two months after, he did the like in several counties,
as Merionethshire and Montgomeryshire.
And when he had eased his mind, and finished his service for the Lord in those parts,
he returned home.
In a little time after, he went to the yearly meeting of Wales,
at Llandiloes in Montgomeryshire, and after his return had but three meetings.
The last was the 4th of the Third month, 1712, where many people came in, and he,
in great tenderness to those who had true desires in their hearts after the Lord,
preached to them in much love and fervency,
and his words and doctrine were as the dew falling on the tender grass.
Afterwards, in great concern of spirit and in trembling, he thundered against the light,
airy, and hard-hearted ones, who slighted and reproached the truth and its followers,
and spoke evil of that they knew not,
telling them the Lord would plead with such in his righteous judgments;
and he exhorted them to repent speedily,
lest the Lord should cut them off in his fierce anger.

On the sixth of the Third month following,
it pleased the Lord to visit this zealous young man with an indisposition of body,
and a voice run through him, "`Put thy house in order, for thou must die.`"
And he declared he was willing to give up all to the Lord,
to dispose of him as seemed good in his sight.
Feeling the Lord`'s power over all, his heart was refreshed, and he declared,
"`Blessed are the dead that die in the Lord, from henceforth; yea, saith the Spirit,
that they may rest from their labours, and their works follow them.`"
He charged his brother, John George, who gives this relation,
that these things should not be forgotten, and fall to the ground;
and bade his said brother give him up freely, adding,
if he and Friends continued faithful the Lord would be their helper and sufficient support.

Afterwards he called for his parents, and spoke to them, saying,
"`I do not expect to recover from this sickness, but be not overmuch concerned;
for I have peace with God, and had rather, if it is the Lord`'s will,
die than live any longer.`"
He desired them to prize their time,
and seriously consider how precious a thing it is to know peace with God, their maker,
on a dying-bed.
He valiantly bore his testimony for the precious truth in their presence,
and showed the barrenness of men-made ministers, who plead for sin and imperfection;
advising his parents to beware of hindering any of their children,
his brothers or sisters, from coming into the way of truth;
and desired them rather to encourage them therein.
He exhorted his parents, saying, "`Give up all,
that you may have an inheritance in that kingdom wherein there is no trouble nor sorrow,
but eternal joy and peace.`"
He likewise exhorted his brothers and sisters to be faithful
to that which the Lord had made known to them of his will.
He often heartily prayed for them unto Almighty God,
that none of them who had turned their faces Zionward,
might look back into the world again, but might all press forward.

Some days before his departure he fervently said,
Remember my love in Christ Jesus unto all my faithful
friends and brethren in the incorruptible Seed;
to which seed the promise is,
and wherein peace and acceptance with God are livingly known.`"
He finished his course here the 18th of the Third month, 1712, aged twenty-five years,
and a minister about nine months.

[.asterism]
'''

JOHN AIREY, belonging to Sedbergh meeting, in the county of York,
was convinced of the blessed truth, as professed by the people called Quakers,
about the twenty-ninth year of his age,
and was of an innocent life and good conversation,
and faithful in every branch of his testimony relating to truth.
It pleased the Lord to commit to him a dispensation of the gospel and part in the ministry;
and although he was not large in testimony, yet had the movings of life upon him,
which made his offerings acceptable to Friends.

As he lived a harmless and innocent life, so,
when he came to be tried with much bodily weakness,
which attended him for several months before he died, he bore it with much patience,
and was very sweet in his spirit, and often said to friends,
"`It is a precious thing to wait upon God, to feel his life,
power and presence to quicken and raise us up to praise his powerful name,
who is worthy forever.`"

He departed this life the 15th of the Fourth month, 1712,
in the sixty-ninth year of his age.
He was one that held out unto the end,
and partook of the salvation of God through the Lord Jesus Christ.

[.asterism]
'''

PEREGRINE MUSGRAVE was born at Lanyna, in the parish of Lanynarth,
and county of Cardigan, the 4th of the First month, 1643.
He was by trade a clothier, and of good repute among men;
and the Lord endued him with wisdom and understanding,
whereby he was very serviceable in the church,
especially in meetings of business and the care of the poor.
Great concern was upon him that Friends might be preserved in love and unity;
and where he saw anything that tended to the breach thereof,
he earnestly laboured to put a stop to it, both at home, and in the adjacent counties.

His heart and house were open to Friends,
and he had great delight in the conversation of faithful brethren;
and it is not doubted but he laid down his head in peace with the Lord,
and he himself signified the same in the time of his sickness.
In which time his wife and daughters sitting in the room by him, and seeing him so weak,
his daughter wept; he hearing her, said, "`Susanna, make no noise for me.
What would you children have?
Your father hath lived to a good old age, and I die in peace with my God,
and in credit with men.
I leave no stink behind me, which is a mercy to you beyond many children.
I desire you to be satisfied, and give me freely up,
and let your concern be inward;`" adding, "`I want to see thy brother and his wife,
and thy husband, that I may ease my mind to them.`"

Then he asked if it was day; his daughter said, "`It is not.`"
He said, "`Call thy brother and his wife.`"
When he came, he said, Lewis, I find this distemper come so hard,
that I am not likely to continue long.`"
He gave him good advice in many words, and withal desired him to keep close to meetings,
and not to forget week-day meetings; and to mind truth, which would adorn them above all;
and said, "`Be serviceable to Friends, and stand a man in my place.
My dear Lewis, remember what I say, live in love: you are a pretty many relations here;
if you keep your places and live in love, you may be a comfort one to another.`"
He called for his daughter-in-law, and took leave of them, and said,
"`I pray God bless you and your poor babes.
I desire you, be tender of them in bringing them up.`"
Then he kissed them and said, "`I have not much more to say.`"
So continued very sensible all the day, and often said, "`Dear God,
I pray thee make my passage easy;`" and said,
"`the love of God is more to me now than all the world.`"
He took leave also of his neighbours and friends,
and seemed to be cheerful and willing to die.

He departed as if he had been going to sleep, and was very sensible to the last,
which was the 14th of the Fifth month, 1712.
This worthy old man was honourably and decently interred at East-hookit,
the 16th of the Fifth month, 1712, aged sixty-nine years.

[.asterism]
'''

JOSHUA ARNOLD, of Whittington, in the county of Derby,
was educated in the blessed truth among the people called Quakers;
and was by occupation a carpenter, and much employed by the great men,
being just and honest in his dealing, moderate and temperate in his life,
and in his conversation Christian and exemplary,
so that therein he preached to professors and profane:
being faithful to the witness of God in his own heart, he answered it in others.

The Lord, who made him what he was,
at times was pleased to open his mouth in the assemblies of his people, that he,
in a sense of the goodness of God, did bear witness thereto.
In true love he exhorted Friends to watchfulness,
and to keep their conversation clean and void of offence towards God and man,
and to dwell in that which would keep them humble,
and ever to avoid pride and covetousness;
to wait patiently for the appearing of the Lord,
and to hear his still small voice in their own hearts; and for the arising of life,
that they might be taught, kept, and preserved thereby,
so that they might bring no reproach upon the holy truth they professed.

This was the earnest desire of this godly man, who was indeed a good example,
both to the great men with whom he was concerned, and to his family, friends,
and all he conversed with: in moderation, plainness, and the fear of God he lived,
and thereby gained a good report and the love of many.
He took opportunities to wait upon the Lord in silence in his family;
and many times the Lord was pleased to take such notice of them in those retirements,
as to break in upon his children,
and manifested his powerful presence to the edifying
and encouraging them and the whole family,
to take up the cross of Christ and follow him.
In a sense of the vanities of this world, he said, some years before he died,
he was willing to leave it,
and did often advise his family to be humble and lowly in their minds,
and to love the truth, which he recommended as the best portion to his children.

About two years before his departure he was much afflicted with lameness and weakness,
by reason of the palsy, that had attended him some years before,
so that he was confined to his room, and seemed not likely to recover.
Then he advised his family both in spirituals and temporals;
but he so far recovered that he could go to meetings, and did,
till it pleased the Lord to visit him with a return of his distemper so suddenly,
that his dying words were but few; but whilst his speech remained, he said he was well,
and in a little time all would be well.

Then one of his children coming to his bedside, for he was seized in his bed,
he held her by the hand, and seemed overcome with the presence of the Lord;
but had neither strength nor utterance to speak, and presently falling into a deep sleep,
departed this life, it is believed, without any sensible pain,
the 16th of the Sixth month, 1712, and was decently interred;
and as his friends and neighbours believe and are satisfied,
he is at peace with the Lord.
Aged about sixty-four years and four months.

[.asterism]
'''

GEORGE BENSON, of Strong End, in the parish of Hawkshead, in Lancashire,
was convinced of the unchangeable truth in his early years,
near the breaking forth of the same in those parts,
and was a very faithful man to his conclusion,
being often exposed to various kinds of suffering,
both by reason of keeping meetings at his house,
and in other respects relating to the several branches of the ancient testimony of truth,
which faithful friends in that time were liable to:
all which he bore with much patience and courage.

Toward the latter part of his time his mouth was opened in a public testimony,
and he travelled into some neighbouring counties in the service of truth.
He was a faithful minister, according to his measure,
his life and conversation being also answerable to his ministry.
In the time of his sickness he gave much good advice to his family,
warning them to keep to truth, and out of the love of this world.
He dropped several comfortable expressions to such as came to see him,
saying he had done his day`'s work, whilst the day lasted,
and had nothing to do but to die.
He departed this life in great peace with the Lord, the 19th day of the Eighth month,
1712, being in the seventy-sixth year of his age.

[.asterism]
'''

RODERICK FORBES, son of Arthur and Elizabeth Forbes, of Brux, in Scotland,
was a man of great reputation in the world.
In his youthful days, he had some knowledge of the principles of the Christian religion,
as held by the people called Quakers, and walked soberly for a time;
but his elder brother dying, he became heir to the estate.
Then he left the narrow way, and threw off the cross,
and continued without a due sense of his loss, till about the year 1702,
after the death of his worthy mother, who in her lifetime was greatly concerned for him,
and desirous that the Lord would visit him,
and bring him into the knowledge and obedience of the holy truth.
And accordingly it pleased the Lord to reach unto,
and awaken him by his righteous judgments, and by his divine power humbled him,
and caused him to sigh and cry to the Lord,
who was graciously pleased to answer those desires
and earnest cries that he begat in him,
and brought him not only to behold the dawning of his gospel day,
but in a spring of love to his soul, enabled him clearly and boldly to own the truth.

This caused the priest to visit him, who pretended a concern,
that one of so honourable a family should be deluded, as he apprehended;
to whom Roderick said, "`If the Lord were pleased to awaken and touch thy conscience,
as he hath done mine, he would make thee quake,
every joint of thee;`" which stopped the priest so that he said no more.
By this principle of truth was this visited man taught and
strengthened to leave his loose and debauched companions,
and to live a sober and godly life, to the astonishment of his former associates,
who admired to see such a wonderful change wrought upon him;
for he indeed now adorned the doctrine of God his Saviour in his life and conversation,
walking according to the convictions of the grace of God,
in solidity and weightiness of spirit.

In the year 1712, in his return from London, he was taken sick at Edinburgh,
but retained a perfect memory, and was minded to make some alteration in his will,
which he did,
being greatly concerned for the good education of his children in the way of truth;
and gave directions for his burial, and the manner of it;
directing that his body should be interred in his own burying-place,
by his father and worthy mother, and two children of his own,
after the plain and decent way of Friends.

He was afterwards much exercised in prayer to God,
and thankfulness to him for his visitation,
and assisting him to bear a faithful testimony to the blessed
truth he had brought him to the knowledge of,
saying, "`As the hunted hart panteth after the water brooks,
so hath my soul panted after thee, O Lord.
I can bear witness that truth is truth;`" and turning to his wife, he said, "`My dear,
thou knowest it to be so, and I know thou art convinced of it;
therefore be faithful to it.`"

About two hours after, he desired to be set up in his bed, saying,
"`I am now in readiness to go;`" and immediately the pains of death seized on him;
which though they were violent, he endured with patience,
and was borne up in a Christian courage, triumphing over the powers of death; saying,
"`The truth is precious, cleave unto it; yea, more precious than the gold of Ophir:
it hath delivered me from many infirmities.`"
One standing by, said, "`Trust in God and he will deliver thee.`"
He answered, "`I have good cause to trust in him, he never failed me:
and now I feel his presence supporting me in the very agonies of death; yea,
on the very brink thereof I can and do rejoice through Jesus Christ my Saviour and Redeemer.
I feel his hand above me and below me, supporting me; and I defy all the powers of hell.
I have seen their strength and their malice, they have not prevailed: praises, praises,
oh! everlasting praises to his ever-blessed name.`"

Then seeing some about him weep, he said with much concern, "`Why should ye be troubled;
since I undergo the agonies, you may look on: a small time will put an end to it,
and I have a view of my journey`'s end.
I am entering the joys thereof already, where I shall enjoy everlasting happiness.`"
In this condition he continued for some hours,
and in intervals speaking always very sensibly,
and recommended his dear wife to the tender regards of friends as a widow:
and then desired R. Barclay to hold up his head in the time of his greatest agonies,
till his speech began to fail; so that he could utter but broken sentences,
the last of which that was distinctly known, was,
"`Unless your righteousness exceed the righteousness of the Scribes and Pharisees,
ye shall in no wise enter into the kingdom of heaven.`"

So having given before a great deal of good advice to all about him,
to leave nothing to a dying bed, and to prefer the truth above all,
with much more not noted, about the eighth hour in the morning his speech left him,
and he lay only breathing until about the fifth hour towards evening,
and then quietly resigned up his breath without any struggling.
He died in the Eighth month, 1712, and was buried according as he desired;
aged forty-two, and convinced about ten years.

[.asterism]
'''

ROBERT FISHER, late of Preston Patrick, in the county of Westmoreland,
was convinced of the blessed truth by the ministry of that ancient servant of Christ,
John Banks, at a meeting at Dalehead in Cumberland, his native country,
and with gladness of heart received the truth in the love of it,
and faithfully walked therein.
And the Lord not only gave him to believe, but, being faithful,
gave him also a part in the ministry of the gospel, and he testified to the holy truth,
and preached the word of reconciliation.

In which work, according to his measure, he was a faithful labourer,
though he did not travel much abroad, neither was his testimony often known to be long,
but comfortable and refreshing to the faithful.
He was also a faithful sufferer for that testimony,
which the Lord raised in his heart to bear against the antichristian yoke of tithes,
for which he many times suffered the spoiling of his goods,
although his outward substance was but very small;
yet he stood true and firm in his testimony to the end of his days.

He began to be ill on the 26th of the First month, 1713,
and his sickness increased and was very sharp upon him;
yet he was preserved in a comfortable frame of spirit,
patiently enduring those bodily infirmities he was under,
and much resigned in his mind to God`'s will,
sounding forth praises to his great and excellent name,
and often expressing the great satisfaction and comfort
he felt from the Lord under his exercise.
Some few hours before his death, his wife sitting by him, he said,
"`I feel the power and presence of the Lord to be
with me;`" and though weakness of body was upon him,
yet he felt that hand and arm of divine power, which in times past had preserved him,
to support and bear up his spirit over his exercise;
with several other words to the same effect, which are not perfectly remembered.

After this his sickness renewed, and was very sharp upon him for a small time,
but then abated; and then he took leave of his wife, and bade her farewell;
and soon after passed away as if he had fallen into a sleep,
without either sigh or groan, the 30th of the First month, 1713,
and was buried the 1st of the Second month following,
in Friends`' burying-ground at Park End, in Preston Patrick,
aged about seventy-three years.

[.asterism]
'''

RUTH PADLEY, wife of John Padley, of Shad-Thames, in Southwark, timber merchant,
and daughter of Richard Parkes, of Hook-norton, in the county of Oxford,
was a woman who truly feared the Lord, and loved his truth and people,
very sincere and upright in her conversation among all,
was very affectionate and loving to her husband,
kind and loving to his children he had by a former wife,
dutiful and tender to her aged parents, tender and loving to her brothers,
sisters and other relations, compassionate to those under affliction,
and ready to sympathize with them, charitable to the poor,
and in an especial manner to those of the household of faith.

She was in her conversation so adorned with a meek and quiet spirit, as made her lovely,
and therein was very exemplary; as also in plainness of apparel, becoming her profession,
and in using the plain language to all, and in calling the days according to Scripture,
which, although by some it may be looked over but too lightly,
yet is what many have witnessed the spirit of truth, which leads into all truth,
to lead them into.
She also hated deceit, and was more in substance than in show.

She passed the time of her sojourning here in fear,
as one that had an eye to another country, namely, an heavenly;
of whom it may be truly said, she was of the number of the wise virgins,
whose lamps were burning,
and so ready to enter with the bridegroom into the marriage chamber.
She was visited with a declining distemper several months before she died,
and although much means were used for her recovery;
yet her distemper increased fast upon her, which she bore very patiently,
and was resigned.

Some little time after she was taken ill, she had a prospect of her departure hence,
which was pleasant to her, but she avoided speaking thereof to her husband,
till a little before her end, lest he should be over-earnest in desiring her life,
and said, "`Her Maker laid nothing to her charge,
and that she was sensible he had regard unto her.`"
At another time, to her sister, E. Vokins, she expressed her assurance,
saying she did not question having a place in the kingdom.

At another time, she signified to her said sister her dear love to her husband,
that she never could be displeased with him for any thing,
and although his company was so desirable to her, she was very willing to give him up;
and said she would have him mind his Master`'s business.
To a niece, of whom she had a tender and motherly care,
she advised and desired that she would take up the cross while young; saying,
it would be harder if deferred, and that she had been well rewarded since she took it up.
To her sister E. V. she expressed her satisfaction with her company in her illness,
saying that she had been a great comfort to her since she came.

About two or three hours before she departed, being in prayer to the Lord,
but her voice low, her niece asked her what she said; her answer was,
she was speaking to her Maker.
About two hours before her departure, she said to her niece,
"`Thou mayest think my affliction hard, but it is not;
my Maker has dealt very graciously or mercifully with me, more than I can express.`"
Her niece asked her if she thought it would be harder; she answered,
she did not think it would; adding, but if it should,
she doubted not but her Maker would support her under it.
And when her said niece asked her where she would have her dwell,
her answer was,`" Where it may be best for thy soul.`"

About one hour before she died, she said,
"`Be sure to remember my dear love to my brother John, and to all friends.`"
Afterwards, she said to her husband,
"`O my dear!`" which were the last words that were heard;
but lifted up her dying hands and eyes as a sign of her breathing to the Lord in spirit,
and so departed this life, and entered into everlasting rest with the Lord.
She died the 26th of the Second month, 1713,
and was buried from Horslydown meeting the 30th of the same,
and divers living testimonies were borne on that occasion.
Aged about thirty-four years.

[.asterism]
'''

ELEANOR PERKIN was born in the parish of Hemsterly, in the county of Durham,
and at the age of seventeen years was convinced of the truth.
She was of a sweet and innocent conversation, and of a meek and humble spirit,
desirous to be conversant with such as feared God.
She was taken ill the latter end of the Sixth month, 1713.

In the time of her illness she was much resigned to the will of the Lord,
whether to live or die.
A friend asking her whether she desired to die rather than to live, she answered,
"`I desired that long since.`"
Again she was asked if she had any trouble upon her mind about any thing; she replied,
"`Nay.`"
Then it was queried of her whether she thought she should be accepted of the Lord;
she answered, she hoped she should; and supplicated the Lord in a heavenly frame of mind,
to the reaching of the standers by,
and the Lord`'s goodness and presence were felt and witnessed;
and she desired those present to be ready when the Lord called for them, saying,
"`You know not whether he may call at midnight, or at cock-crowing,
or at dawning of the day.`"

One time, being under great affliction, she said, "`Lord, give me ease,
and grant me patience;`" which in a little time she received,
and she made her acknowledgment to the Lord for the same, saying, "`O Lord,
when I get any ease, it comes from thee.`"
A relation of hers being by, desired a book to pray, or read prayers by her,
to whom she answered, with respect to prayer, that it was beyond books.
She spoke of the goodness of God, and what he had done for her, saying,
"`I desire I may praise him while I live.`"
And to her sister she said, "`I desire thou mayest be a good child,
and the Lord will love thee; for the Lord loves all that draw near to him.`"

One evening several of her friends came to visit her,
and sat down in silence waiting upon the Lord;
in which time his presence was wonderfully felt and witnessed among them,
insomuch that she, with several others, were broken into tears and sweet harmony,
with some words she uttered, which were not noted.
A friend then present kneeling down to prayer, supplicated the Lord for her.

After one had taken leave of her, Eleanor said, "`My dear friend,
the Lord be with thee and with me.
Oh! that I may praise him whilst I have a day; for he is worthy,
for his great mercy and kindness this day.
Truth is precious: Oh! that every one would come to it,
and that many would come and taste of it.
Oh! that I may take straight steps whilst I am here; for good is the Lord:
he hath been very good to me all along.
Oh! that many were partakers of his goodness;
for the Lord hath been wonderfully good to me.
Oh! what this truth is, that many may know and be partakers of it,
and that we may honour the Lord, for he is worthy; he is worthy of all honour.
The Lord was never so good to me as now.
This was a good opportunity.`"
With many other words, which, by reason of her weakness, and her voice being low,
could not be well understood; but she remained sensible to the last,
and on the 8th of the Eighth month, 1713, she departed this life,
and was buried the 11th, at Raby, in the county of Durham.

[.asterism]
'''

RICHARD KINMAN, an ancient friend, who was truly owned and in unity with his friends,
and of an upright and blameless life and conversation; and loved the truth,
and sometimes bore testimony to it in meetings.
A little time before he departed this life, he said, "`I know my Redeemer liveth,
and that he hath done that for me none else can do;
and I believe it will be well with me.`"
With which testimony friends declared their unity.

This, though short,
is published to show how this honest ancient man retained his integrity,
died in the faith, and obtained a good report.
He died the 23rd of the Tenth month, 1713, at Bishampton, in Worcestershire.
Aged seventy-two years,

[.asterism]
'''

SUSANNAH GARTON, widow of William Garton, late of Ifield, in the county of Sussex,
was one who in her young years received the blessed truth in the love of it,
and walked faithfully therein to the end of her days.
It may be truly said she was a mother in God`'s Israel;
a preacher of righteousness in her day, not so much in words as in life and conversation;
though it pleased the Lord, towards her latter days,
to bestow on her a gift of the ministry, which, though small,
was very sound and acceptable.

She was always of a meek and lowly mind, not esteeming herself upon, or because of,
any service she was found in; but was humbled in thankfulness to the Lord,
for that he had in any measure counted her worthy,
and enabled her to be serviceable in the church,
thinking no service therein too mean for her to be employed in.
She was given to hospitality, was an entertainer of strangers,
willing to wash the disciples`' feet, took care of the widows and fatherless,
and visited the afflicted.
To do good and communicate, as the Lord had blessed her, she was not unmindful;
for with such sacrifice she knew the Lord was well pleased.

She was also a cheerful sufferer with her dear husband for the testimony of truth,
being often left to manage his affairs in the world,
while he lay in prison for his testimony against tithes,
and sometimes for meeting to worship the Lord.
All which she bore and went through with great cheerfulness and zeal for the Lord,
rather counting it all joy or rejoicing,
that they were counted worthy not only to believe,
but also to suffer for the Lord Jesus Christ`'s sake,
whose love and favour was more than all the world, or the enjoyments that were therein.

Therefore they did not reason with flesh and blood,
but were faithfully given up to serve the Lord with all that he had blessed them with,
believing the righteous should never be forsaken,
nor their seed be found begging their bread, if they likewise followed their steps.
Words are indeed too short to set forth the worth and value of such elders,
who through faith and patient suffering have obtained a good report,
and left a sweet savour behind them; of whom it may be said,
though their bodies be dead their spirits live,
and their memorial is sweet to the living and sincere in heart,
who had acquaintance with them,
who will in their hearts set their seals to this testimony.

This worthy woman was also a pattern of great plainness,
and was often grieved to see and hear of the superfluity
that abounded among some of the professors of truth,
and the undue liberty they took, saying, "`It was not so in the beginning,
for then there was nothing too near and dear to part with for truth`'s sake.`"
She was likewise much troubled to hear the needless vain talking, foolish jesting,
and see the light and airy carriage among such, that were unbecoming our holy profession,
saying, "`Time ought not to be so spent,
for an account must be given unto God for all these things.`"

It pleased the Lord to preserve her out of such things to the end of her days,
and it is not doubted but the Lord hath given her a portion among his redeemed ones.
What can be written cannot add to her virtue or happiness,
but is written in fear and true love,
with desire that those into whose hands it may come,
may be encouraged to hold on their way,
and that drooping souls may look unto the Rock that followed the ancients,
and was with them in all their tribulations.
Unto which Rock they now sing praises, and render honour, glory and thanksgiving forever.
Amen.

It was the care of this worthy matron to walk circumspectly in the time of her health;
and when it pleased the Lord to visit her with weakness,
which continued and increased on her for about half a year,
she was preserved in great patience, quietness and resignation to the will of God,
often saying, "`It is preparation for my end, and I am well content;
for the Lord hath given me many days.
And if this had not come upon me, I could not expect to live long in this world.`"

And although she was one of few words in her health,
yet in her illness she wanted not for a word of advice to those that came to visit her,
and it hath caused some trouble it was not taken from her mouth as it was spoken.
She was much concerned for her grandchildren, and when any of them came to see her,
she advised them to prize their precious time, saying, "`I was once young as well as you,
or others, and delighted in the pleasures and vanities of this world.
But the Lord in his love and mercy met with me, yea,
he laid the axe to the very root of the tree,
and made me willing to part with all my lovers, my pride and vanities,
and become a fool and a gazing-stock to the world.
But all was as nothing to me in that day,
in comparison to the love and favour of God to my poor soul,
that had long wanted peace with the Lord.
In that day it was my care to accompany myself with
those that I thought walked most circumspectly,
and dwelt nearest the Lord in their spirits; and not to look out at, or take example by,
those that were for most liberty, as too many now do.`"
Then she in much thankfulness, said, "`Oh! it was a good day, a blessed day;
a day never to be forgotten.
My soul hath it in grateful remembrance before the Lord;
praised be his holy name for his goodness.`"
And in tears of joy she exhorted all to be faithful unto death,
that they might obtain a crown of life.

Again, upon some coming to visit her, and asking her how she did, she answered,
"`I am going a little before, and you must follow after:
all had need to be faithful to the gift they have received.
I never found that going to meeting barely would do for me.
We must all be faithful according to what we have received,
and there is no more required.`"
Another time, a Friend of London being with her,
she tenderly inquired after the affairs of truth, saying,
"`How do Friends in that great city come up in good order and discipline in the church?
Are they truly concerned to seek out the lost sheep,
that they may be brought home again?`"
And when she took her leave of the Friend, she said, "`Farewell,
I shall never see thee again in this world;
but hope to have a part in that which is to come.`"

She was preserved in great tenderness and brokenness of spirit all the time of her illness,
and did often say to her friends that came to visit her,
"`I do not weep because I see death approaching; for I cried to the Lord,
that if any thing did lie in my way, he would be pleased to show it me:
but I do not find any thing laid to my charge.`"
Another time, when some friends came to visit her, she,
pouring out tears in a sweet frame of spirit, said,
"`I believe that saying will be fulfilled on me,
that those that sow in tears shall reap in joy.`"

She also often expressed her great thankfulness, that the Lord should be so good to her,
as to open the hearts of many to visit her in her weakness;
and acknowledged the goodness and mercy of the Lord, saying,
"`How wonderfully good is the Lord to me, a poor creature!
What a gentle hand doth he lay upon me!
How comfortably have I rested this night!
What a mercy do I receive at the Lord`'s hand, in this my weak condition,
that I can sleep so sweetly!`"
And with tears of joy she gave thanks to God for his great favour and goodness to her,
saying, "`I spend many hours in thinking upon the Lord and his goodness.
I admire how people can lay them down and fall asleep, and not think upon the Lord,
and see or consider how things are with them.`"
Sometimes she would signify her desire to be dissolved and go to the Lord;
but it was in a resigned frame of spirit, saying, "`O Lord,
grant I may patiently wait thy appointed time, knowing thy time is the best time.`"

She often begged of the Lord, that he would give a double reward to her daughter,
for the love and care extended to her: and her daughter being near her time,
she was in great care for her: and afterward the child being brought to her,
she cheerfully took it in her arms, kissed it, and said, "`I pray God bless it,
and make it a good woman.`"
And afterwards said, "`I must go to my God.`"
She lifted up her eyes, folded her hands, and gave up her soul in sweetness to the Lord,
without either sigh or groan, the 10th of the First month, 1714,
and was buried at Charlewood, in Surry, her corpse being accompanied by many friends,
neighbours, and relations.
Aged seventy-nine years.
