== Chapter 4

[.chapter-synopsis]
* Phebe Doughty
* Taner Costard
* Rebecca Toovey
* Joseph Grove
* Esther Champion
* Daniel Taylor
* John Thompson
* Samuel Waldenfield
* Joseph Welsh
* Susannah Saunders

PHEBE DOUGHTY, wife of William Doughty, of Flushing, in New-England,
was daughter to Sarah Taylor.
She was dutiful to her parents, and a great comfort to them,
and from a child was mindful of eternity, meditated on the best things,
had God in her thoughts, and would inquire the meaning of some Scriptures.
She was never given to speak that which was not true.
Many heavenly and weighty prayers she put up to God, who hears the contrite in heart,
and he answered her petitions, to her great comfort;
for she declared the Lord had given her assurance of her salvation,
and death was no terror to her;
and that she had rather die than live longer in this troublesome world; "`though`",
said she, "`I have not wanted that which is convenient for me.
I have as clear a husband as a woman need to have, a tender mother, and a sweet child;
yet it is better for me to go and leave you all; this is the best time;
for I am going to meet my Lord Jesus.`"

And she said to her husband, some time before she died, "`My dear, we must part;
it is made known to me: give me up freely.`"
And desired all about her to be faithful to improve their
talents which they had all received from the Lord,
and not put it off to a dying hour; for that is poor work.
"`Oh! how hard a thing will it be, to die and want peace with God;
but it is joy and comfort to me to depart this life; for it was said to me,
after my great exercise, Thy peace is made;
and I have nothing to charge myself with since.`"
She desired her mother to tell her sister from her,
the Lord had bestowed a great deal on her, and where much is given, much is required;
and advised she might improve her talent, and not put it off till a dying hour,
that is poor work; saying if she could see her poor sister,
she would give her good counsel.
She spoke to others to the same effect, and uttered many weighty expressions in prayer,
which were not noted down.

The day she died, she said to her mother, seeing her weep, "`Mother,
I leave thee my little son to take a delight in; take him as thy own, I give him to thee,
and bring him up in the way of truth; to be sure in the way of truth.`"
She spoke of the goodness of God and his mercies to her,
and declared her full satisfaction of her future well-being, often saying,
"`Sweet Jesus,`" and declared she was ready.
And after she had been fervent in prayer,
and therein desired the Lord to open the door for her, she said, "`Sweet Jesus,
my trust is in thee.`"

A few minutes before she died she kissed her mother, and desired her husband to kiss her,
and bade them take care of the child: "`Now,`" said she,
"`I will go to sleep;`" and so departed the 10th of the First month, 1714,
the fourth day of the week,
and was accompanied by many friends and others to the meetinghouse in Flushing,
and after meeting to the burying-ground, near the market-house,
where she was decently interred, the 12th of the First month, 1714.

[.asterism]
'''

TANER COSTARD, son of John and Ruth Costard, late of Amersham, in the county of Bucks,
was of an innocent conversation, dutiful, loving and affectionate to his parents,
religiously inclined from his infancy, and greatly delighted to read the Holy Scriptures,
especially the New Testament.
He lived with his grandfather, and was brought up by him, and in his practice,
being a physician.
Though not in profession with the people called Quakers,
yet this young man came to receive that holy truth professed by them,
and to experience the work of it in his heart;
as may appear by what he wrote in the time of his weakness, not long before his death,
and by what he expressed to his mother near his end.

He likewise spoke several excellent things which were not noted;
for he was indeed much devoted to the service of God in the time of his health,
and very diligent to wait upon the Lord from a child;
and when very young he learned to read in the New Testament,
and often wept when he read of the sufferings of Christ.
A little before he died, his mother going to see him,
when she came and had been by him for some time, she said to him,
"`I am made easy and willing to part with thee,
because I have satisfaction it will be well with thee.`"
To which he replied, looking on her gravely, and with a pleasing countenance,
"`I know it will be well; I know it will be well; I know it will be well.`"

And when he departed, it was observed to be in great stillness and sweetness,
and those present felt the life and power of God in a large measure,
to their great comfort at that time, which was as an assurance to them,
that it was well with him, and that the Lord took him to himself.
He died the 23rd of the First month,
1714 and his corpse was accompanied from the meetinghouse in Amersham aforesaid,
by many friends and others who loved and esteemed him,
and interred in Friends`' burying-ground near the said place.
Aged about twenty-two years.

[.asterism]
'''

REBECCA TOOVEY, daughter of Joseph and Rebecca Toovey, of London, aged about nine years,
was a dutiful and pious child,
a great reader and lover of the Holy Scriptures and Friends`' books;
of an innocent and wise behaviour and carriage,
and her conversation was pleasing and acceptable.
Though she was but a young plant,
it pleased the Lord to endue her with a large understanding
in things both natural and divine.
She was comely in her person, virtuous in her practices, quick of apprehension,
very just and equal in all she undertook,
and never known to tell a lie or speak an ill word.
She loved to go to meetings, and said it was sweet to her.

Some few weeks before her sickness she had been at a meeting,
wherein she was very diligent and attentive to a Friend,
who earnestly exhorted the children of Friends to
make choice of the blessed truth for their portion,
whilst they were in the enjoyment of their health,
that they might be prepared for a dying hour.
Whereupon this child was much reached and melted into tears,
and after meeting she got apart to read, which was her usual practice.

After she was taken ill, she was in great pain;
but her heart was filled with the incomes of the Lord`'s love and mercy,
which caused her to utter many sweet and heavenly expressions.
She bore her great pain with much patience,
and was observed to be fervent in supplication to the Lord, in a tender, humble,
and submissive manner.
When her pain was sharp, she often cried out, "`Sweet Jesus, give me ease.
Sweet Jesus, look down with an eye of pity upon thy poor, poor servant.`"

Another time, being in great pain, she said,

"`Sweet Jesus, give me ease;

For mercy I do crave:

And if thou wilt but give me ease,

Then mercy I shall have.`"

With many other pathetical expressions not noted,
which she uttered in deep supplication and humiliation; and then she said, "`O Lord,
thou desirest not the death of a sinner; but rather that he would repent, return,
and live;`" adding, "`I know it to be so.`"

Another time she said, "`Lord, if thou pleasest thou canst give me ease.`"
And again, "`Lord, thou wilt help them that love and fear thee.
O Lord, remember thy poor servant, and give me a little ease.`"
And seeing the maid cry, she asked her what she cried for; the maid said,
"`To see thee so full of pain.`"
To which the child replied, "`Do not cry; I shall be well in a while.`"
Perceiving her school-mistress, R. Trafford, to be troubled for her, she said,
"`Dear mistress, do not be troubled; there is a rest prepared for the righteous.
There is no ease here, but there is ease in heaven.`"
She also said, "`It is a sad thing to speak bad words, and to tell lies,
which I never did.`"

Near her end, she said to her maid, "`I wish thee well, and I shall be well.`"
Then naming her relations and particular acquaintance, she bade them farewell,
and departed this life in a sweet frame of spirit, at Croydon, in Surry,
on the 8th of the Fourth month, 1714, and was brought to London,
and buried in Friends`' burying-ground, in Bunhill-Fields.

[.asterism]
'''

JOSEPH GROVE, of Rotherhithe parish, in Surry, merchant, was the son of John Grove,
of Mary Magdalen`'s parish, mariner and master of a ship,
and for many years in the Barbados trade;
and this Joseph Grove resided in the island of Barbados for many years, where,
as well as since his return to his native country,
he was of a sober conversation and good reputation,
and a lover of truth and the friends of it, who kept their places therein.

In the latter part of his time, he was often indisposed in body,
and much afflicted with pains, notwithstanding which,
he was not unmindful of making his peace with the Lord;
for a little before his departure, he said, "`I hope I have fought a good fight,
and am waiting for the crown, which I doubt not at all but is laid up in heaven for me.
Oh! how I long to be dissolved: to live indeed is Christ, but to die is gain.`"
Then speaking to his wife, said, "`My dear love, weep not for me;
for I seek death with more pleasure than all the riches the Indies can afford.
Thou hast been my love, but I have another lover, Christ Jesus our Lord; to him I go,
and to him I recommend thee and my dear children: he will be a husband, a friend,
a counsellor and helper, yea, all in all, if thou wilt cleave unto him.
Seek, and thou shalt find; knock,
and he will open the treasures of divine wisdom to thee,
and by his mighty power thou wilt be preserved out
of all such things that would spot and defile.`"

Great was his concern for his children, insomuch that he would often say,
"`Oh! that they may choose the fear of the Lord.
I desire that for them more than all things here below;
that is the best riches and the greatest honour.`"
And as his love was great to his wife and children, yet it was not bounded there;
but said, "`What strong love have I in my heart for the servants of the Lord,
and although I cannot be present with them at meetings,
I often meet with the Lord in my solitary chamber; forever blessed be his holy name.
Oh! that they may love him, and then they must and will love one another.`"
And frequently spoke to this effect.

He departed this life the 9th of the Eighth month, 1714,
in the sixty-second year of his age,
and his corpse being attended by many friends and others,
was decently buried in Friends`' burying-ground, near Barnaby-street, Southwark.

[.asterism]
'''

ESTHER CHAMPION, wife of Richard Champion, of Bristol, daughter of Joseph Palmer,
of Flushing, Long Island, in America,
was religiously inclined from her young and tender years,
for the Lord inclined her heart to seek after him, and was pleased to be found by her.
The Lord gave her a large measure of his Holy Spirit, and caused her,
as she grew in years, to increase more and more in his eternal truth,
and fitted and prepared her for his work and service whereunto he called her.
And after some time he sent her to visit his people and churches,
and to preach the gospel of peace and salvation by Christ,
and declared his coming by his divine light and spirit in the hearts of all men,
inwardly to teach them, and laboured to gather them to him,
in order to their coming to know salvation by him.
In this work she laboured in divers parts of America, viz., Rhode Island, Long Island,
New England, the Jerseys, East and West, Pennsylvania, Maryland, Virginia, Carolina, etc.

She had meetings in several places among many people, where there had been none before,
and the Lord was pleased to bless her labour,
so that many were gathered to the knowledge of his truth,
and therein to worship him in the spirit of his Son, our blessed Saviour,
the Lord Jesus Christ.
After she had travelled many thousand miles in the Lord`'s service,
in the work of the ministry of the gospel in those American parts,
she found for some years a concern,
which so continued upon her that she could not with satisfaction omit it,
which was to visit some parts of Great Britain,
but more particularly the inhabitants of London,
at which place she arrived the 20th of the Eighth month, 1710,
and had good service there, which many that were witnesses and sharers can testify.

She was a woman of a solid yet cheerful spirit,
much abounding in love and true zeal for the Lord and his truth;
and would express her great grief when there was
any disorder or want of true love in any church,
meeting, or family where she travelled, which was in divers parts of this nation.
The 23rd of the Eighth month, 1714, in the morning,
she complained of sharp pains in her breast and back,
which continued most part of three days, and then the small-pox appeared,
which distemper hath proved mortal to many of those parts where she was born.

She retained a sound understanding,
and oftentimes spoke of the goodness of God to her soul,
and by the aboundings of his love her heart was filled, and her cup made to overflow,
to the comfort of those who were present.
She was freely resigned to the will of God, either to die or live,
though she had inexpressible love to her husband and children, and desired, if she lived,
to be farther serviceable to the church of Christ, yet said, "`The Lord`'s will,
and not mine, be done.`"

She often desired those who were present to love, seek,
and serve the eternal God with all their hearts.
And, speaking to Dr. Logan, said,
"`Many good and precious opportunities thou hast in thy way of practice,
if rightly applied, in seeing the advantage,
inexpressible joy and comfort the Lord is pleased oftentimes, on a dying bed,
to give and afford those who live in his fear; and on the contrary, the cries,
bemoanings, and bitter bewailings of others,
who have not improved and spent their time well in this world.`"
All which she desired him to improve; and further added,
"`It is not a profession of religion only that will render men acceptable to God;
but serving him in and by the assistance of Jesus, the Son of God,
the only Intercessor for man`'s salvation.`"

She was then reminded of her great weakness of body, to which she replied,
"`The Spirit of Christ in me, raises my spirit and strength to speak of his goodness,
and praise his great and good name;`" and added, "`All that man can do is but his duty:
therefore the Lord, through his Son, our Saviour, the immaculate Lamb,
ought to have the honour.`"
She desired the Lord would be a Shepherd to his people,
as he had been and still was to her soul, who had given her to enjoy sweet pastures,
and made her heart exceedingly to overflow;
and that his staff and rod had been and still were her inexpressible comfort.

And as she frequently, in a sweet and heavenly frame, supplicated the Lord,
so she did then, praising his eternal name for his goodness to her soul,
and that she knew her Redeemer to live, and to be with her, saying,
"`It is an easy thing to talk of death;
but it is an inexpressible comfort to be prepared for a dying hour, and to meet death,
when it appears, cheerfully; as I now do, by the help of the same Jesus, my Saviour,
who suffered without the gates of Jerusalem.`"
Then she prayed very fervently for the return and repentance
of those that run into a loose and libertine spirit;
and that the glory of God might appear in a particular
manner to the inhabitants of this great city;
and that God`'s church might be preserved in perfect peace, as a light to the beholders.
She also prayed very earnestly for the young generation,
that the Lord would incline their hearts in their visitation, in the days of their youth,
to seek and serve him, before it was too late,
as he had done to her soul in her early days; for which, said she,
I have cause forever to admire his inexpressible love.

She bore the extremity of her distemper with more
cheerfulness and discretion than was common,
with a continual resignation to the will of God.
A few hours before her departure, she said her time in this world was nearly spent,
and cheerfully desired her husband to resign her up into the bosom of her blessed Saviour;
and requested her husband to live in God`'s fear, and serve him faithfully all his days.
She signified her satisfaction in their coming together in marriage,
and declared that the same power which engaged and united their spirits,
now called her home to God.

Then she spent some time in holy supplication to God, although she was very weak in body,
yet fervent in spirit, and she earnestly besought her heavenly Father,
that the brightness of his day might appear abundantly
in his people and churches all the world over.
Then embracing her husband, took her farewell in the Lord Jesus Christ.
Then she sent for her husband`'s two children,
(whom he had by a former wife,) whom she affectionately loved and treated as tenderly,
whilst she lived with them, as if they were her own,
embraced them in her arms and took her leave, advising and desiring them,
being of years of understanding, to seek, serve,
and love the eternal God in the days of their youth.

She declared to them the advantage they would receive thereby,
and recommended them into the hands of God,
desiring he would preserve them out of the evil of the world, whilst they were therein;
and fervently prayed that they might be the Lord`'s servants all their days;
and desired them to be dutiful to their father, observe his advice,
and love their little brother and sister.
Her two children being young, she took them in her arms and affectionately embraced them,
and desired the Lord would take them, with the two elder, to himself,
when their time here shall come to an end.

Then she sent for some of her servants, to whom she gave good counsel and advice,
recommending and exhorting them to love, serve,
and fear the great and good God in the days of their youth, and whilst they had strength,
signifying the advantage they would receive thereby.
She also gave them in charge to take care and discharge
their trust to her children whilst they were with them;
and those of her servants that were not present,
she desired might be acquainted with her advice to them.
She also signified her heart was filled with the love of God,
in which she again desired the prosperity of his church and people.

Her speech beginning to fail, she said,
"`I desire my dear love in the Lord Jesus Christ may be remembered
to all my relations and friends that ask after me,
even in the same love (said she) that now makes my heart to overflow:`"
and then declared her satisfaction of going to her eternal rest,
and again embracing her husband in her arms, and in the bowels of her Father`'s love,
sweetly took leave and bid him finally farewell, and soon departed this life,
as quietly as one that sleeps with much sweetness, in Bristol,
the 3rd of the Ninth month, 1714, after eleven days`' sickness,
and was interred in Friends`' burial-ground of that city.
Her love and labour in that city, in the work of the word of life,
had been large for her time, and in the parts aforesaid; in which she was blessed of God,
and made successful to the good and comfort of many.

She was a virtuous woman, of a sound judgment, and very quick understanding,
abounding in true love and zeal for the Lord and his truth; solid and grave,
yet of a cheerful disposition, greatly desiring the good of all people,
and that they might come to the knowledge of the truth, live therein,
and enjoy peace and acceptance with the Lord.
She was a faithful minister of the gospel of peace, a good, virtuous,
and affectionate wife, a tender mother, a loving mistress, a true Friend,
and of an exemplary conversation in holiness and true piety.

[.asterism]
'''

DANIEL TAYLOR, of Bridport, shopkeeper,
was convinced of the holy truth in his young days,
about the nineteenth or twentieth year of his age, and received it in the love thereof.
Through its work and power in him he became a very solid, grave, religious man,
greatly serviceable in the church of Christ, and exemplary in his life and conversation,
adorning the doctrine of God our Saviour, by walking as became his holy profession,
of which Jesus Christ is the apostle and high priest,
until the Lord who he loved was pleased to take him to himself.

In the time of persecution he was a cheerful sufferer for the testimony of truth,
both by imprisonment and spoil of goods, which he took joyfully,
whereby he became a strength to his brethren, who were fellow sufferers with him:
for he could pray for his enemies, and had love to all mankind,
and desired their salvation, knowing it was the will of God.
And God blessed him with outward substance, with which he honoured the Lord,
and liberally, with cheerfulness, gave great part thereof to charitable uses,
as by his several gifts and legacies appear.
He was a great friend to the poor of all sorts, and had a tender regard to them,
amongst whom he will be greatly missed, as well as in the church.

His sickness was but short: he kept his bed but a few days before his departure.
In which time he was sweet in his spirit, and had near access to the Lord,
and in much humility said, "`O thou great Jehovah, in whom is everlasting strength,
my soul praises thee, and all that is within me blesses thy holy name.`"
Again, with more not noted down, he said "`My soul praises thee,
and my spirit magnifieth thy holy name:`" He added, "`My love, in the Lord Jesus Christ,
is to all friends; I am in love and amity with them.`"
Being apprehensive his departure drew near,
he took his solemn leave and farewell of both his
relations and friends who came to see him,
praying for them, and gave wholesome counsel and advice to several;
particularly the young generation related to him,
and likely to survive him in this world.

And being content in the will of God, which he prayed by and was answered in,
he died the 7th of the Ninth month, 1714, in the seventy-third year of his age,
and was honourably buried the 12th of the same, in Friends`' burying-ground at Bridport,
his corpse being accompanied to the grave by many of his friends and neighbours,
and testimony given to truth, both at the meeting and grave, on that solemn occasion.

[.asterism]
'''

JOHN THOMPSON, late of Crook, in the county of Westmoreland,
was very early convinced of the blessed truth, in the year 1652,
by that eminent minister of the gospel, George Fox, at his first going into those parts.
The said John Thompson had been seeking the way of the Lord for several years,
and when his understanding came to be opened by the light of Christ,
to which he was turned, he was convinced of the truth and way of the Lord,
and his soul greatly rejoiced that the day was broken forth,
which let him see the dry and empty forms, and lifeless religion he had been in.

And although he had been strict in profession, he then saw by the light of Christ,
there was abundance of things which were not agreeable to the mind of the Lord;
and the righteous judgments of God he found to work in him,
in order to redeem him out of those things.
Notwithstanding he saw the way was strait, and the sufferings many,
which he was likely to meet with, yet through the work of the power of God,
he was made willing to bear and go through all, even cruel mocking, buffetings,
revilings, imprisonment, and spoiling of goods, and rejoiced that the Lord,
made him willing to suffer for his name`'s sake.

He was zealous for the truth against that libertine spirit,
which opposed the discipline and good order of the gospel,
standing as a watchman upon Zion`'s walls,
having a clear discerning of many things that might creep in to eclipse her glory,
under whatsoever pretence they might appear.
And as the light made them manifest,
it placed judgment in the wisdom of truth upon the transgressor.
After some time the Lord was pleased to open his
mouth by way of testimony for his blessed truth,
in which he faithfully laboured; and though he never travelled much abroad,
yet his ministry was reaching and refreshing to those who heard,
and edifying to the churches where his lot was cast.

He was very tender towards that which was good, in the least appearance of it;
but very sharp against that which was evil,
especially against those who professed the truth,
and were not faithful in that testimony truth had called them to bear,
but gave way to a libertine spirit, and were not willing to bear the cross.
His spirit was often grieved with such, and he was made sharply to reprove them,
being much concerned for their good, and also for the honour of truth;
often saying that those who professed the truth and walked contrary to it,
were the greatest enemies truth had, being a stumbling block in the way of others.

He suffered long imprisonment upon the account of his testimony
against that antichristian yoke of tithes,
and also great spoiling of goods by fines imposed on him for his testimony to the truth;
all which he bore patiently, and underwent with abundance of pleasure,
having a regard to the recompense of reward which would follow.
He stood valiantly through all those days of tribulations and sufferings,
after which he lived to a good old age.

He was visited with sickness the 11th of the Third month, 1715,
and though his pains were great, yet he bore them patiently,
often saying that in a little time all would be well.
One asked him how he was; he replied, many being present,
"`I am very weak of body and full of pain, and it seems to me,
as if my stay here must not be long: but I have had a long time here,
and the Lord hath been very kind to me beyond what I have desired or deserved;
but all is well.
The Lord`'s power is over all, and there is no guilt, no condemnation,
nor bar between the Lord and my soul`'s peace; but the pure holy Seed reigns over all,
and I feel life spring up into dominion, and my heart is comforted among you,
my dear friends.`"
Then he continued quiet, enjoying peace with the Lord.

Thus he sweetly finished his course the 26th of the third month, 1715,
at the house of James Wilson, and was buried in a decent manner the 29th of the same,
in Friends`' burying-ground at Kendal; and though his earthly house be dissolved,
yet we are satisfied he hath a house with God, eternal in the heavens.
Aged eighty-seven years.

[.asterism]
'''

SAMUEL WALDENFIELD, late of Bush-hill, in the county of Middlesex,
died the 7th of the Eighth month, 1710, at his own house.
He was born about the year 1652, at Edmondsbury, in Suffolk, and after lived at Sudbury,
in the said county.
He was religiously inclined in his youth, and sometimes a hearer of the Independents.
About the year 1670, or `'71, he was, by the word of life,
convinced of the blessed truth by that eminent minister
of the gospel of our Lord Jesus Christ,
Giles Barnardiston, and received it in the love thereof,
and came to be obedient thereunto, and to know the work of it upon his heart,
and by keeping to the teachings of the grace of God,
came to live a sober and a godly life, and was very zealous for the Lord,
and his holy name and truth.

It pleased the Lord, about the year 1672, to bestow upon him a gift of the ministry,
and the Lord called and sent him forth to proclaim the acceptable year of the Lord.
He published the glad tidings of peace, and proclaimed liberty to the captives,
by Christ, and for Zion`'s sake he could not hold his peace,
for Jerusalem`'s sake he could not rest,
being greatly desirous that all might come to Christ the light,
and that the abundance of the sea might be converted,
and the forces of the Gentiles might come unto him.
In the Lord`'s work he freely spent, and was spent,
in true love and zeal for the Lord`'s name and truth, and the good of souls,
travelling in England, Scotland, Ireland, Holland, and Germany,
and by his powerful preaching of the word of life,
and the Lord`'s blessing on his labours, many were convinced of the holy truth,
and turned from darkness to light, and from the power of Satan to God,
and were as the seals of his ministry.

He was loving and tender to those that truly loved and served the Lord, especially such,
whether male or female, whom the Lord called into his work and service,
to speak a word in season to Zion`'s travellers, and to comfort those that mourned.
In the year 1684 he married and settled in London,
and continued faithful and diligent in the work he was called to,
and suffered for his testimony by imprisonment, etc.
But when at liberty he was frequent in travels as before said,
and visited the churches of Christ in most of the counties of this nation,
and much in the east parts thereof.
His labours of love and service were well received abroad and at home, and by his grave,
solid, and exemplary conversation, he adorned the doctrine of God our Saviour,
and walked as became a minister of the gospel, and that holy profession he made,
of which the Lord Jesus Christ is the high priest and apostle.
He was humble and merciful, very considerate of the poor, ready to every good work,
and to communicate he did not forget.
He was, in the Church of Christ, an elder worthy of double honour.

About the year 1706 he left the city and dwelt at Bushhill,
being often not well in health; but when he was, and not engaged in travels,
or other services on truth`'s account, for the ease of Friends,
he constantly attended the meetings about where he lived, and his testimony was clear,
living, and effectual, and reached the witness of God, both in Friends and others.
He also was very tender to the newly convinced,
and administered suitable advice to their several states, as a nursing father,
and encouraged all under a right sense.
He had a more than ordinary concern in testimony,
to press and exhort to such a good life and conversation,
as becomes our Christian profession, often signifying that coming to meetings,
or pretence to religion, and professing Christianity, was of little value,
without the life and conversation were agreeable.

He often expressed himself to this effect, that the pride, liberty,
and ill conversation of too many under the profession of truth and the Christian religion,
were a great grief and exercise to him,
and the sins and miscarriages of such administered to him much sorrow and affliction.
He was under great exercise of spirit for the prosperity of truth,
and that the testimony thereof, in all the branches of it, might be duly kept up;
and that all looseness, pride and haughtiness,
and that libertine spirit that would lay waste the heritage of God,
might be discouraged and suppressed;
and that none might take upon them to be rulers in the church but men of truth,
men fearing God, and hating covetousness.

This concern grew upon him for several years to the end of his days.
So that he zealously exhorted as aforesaid to a holy and righteous life,
and all to be just and true in all their concerns amongst men:
in which he was exemplary in his practice, being a man truly religious,
and of an innocent and virtuous life, full of love, good nature, and good works,
punctual to his word, just in his dealings, a fair trader,
choosing rather to suffer injury than do any wrong.

He was a bright ornament to our holy religion in his conversation,
and thereby great reputation was gained to truth and Friends, among both rich and poor,
with whom he was concerned.
The poor loved him, to whom he was courteous and charitable;
and the rich esteemed him greatly for his prudent and innocent behaviour;
so that his company was acceptable and much desired by them.
Many who had entertained a mean opinion of Friends as a people,
since their acquaintance and conversation with him, have other sentiments of them:
and as he was beloved in his life, so his death was generally lamented.
He hath left so good a name and savour behind him,
that his memory will not be easily worn out, either among his friends or others.

He was ill about two months before his decease; and, although he was often in great pain,
he bore it with wonderful patience, and was frequently very cheerful,
though his end drew near.
The sting of death being taken away, death was not terrible to him;
often signifying all was well with him, and in much tenderness said,
"`I have done the work of my day.
I have peace of conscience.
I have wronged no man.
I have received a great deal of wrong and injury, but I forgive them all,
and I desire the Lord may forgive them also.
I die in charity with all the world.`"

Another time he said, "`What a brave thing it is for Friends to dwell in unity.
Here we can sit together as the children of God, the church of the first-born,
whose names are written in heaven.
Truth is what will endure forever, and be comfortable to the children of men,
and the Lord will exalt it, and make Zion a quiet habitation,
and Jerusalem the praise of many generations.
He will exalt his truth and name in the earth,
and will bring down that which would oppose his work,
and will purge them out of the church who are exalted, and setting up self,
and ruling in their own will and spirit.
The Lord will do it all away.
I have endeavoured to live inoffensively towards God and man.
And now I have no occasion to repent that I have endeavoured to live well;
and as I have nothing to boast of, I have no occasion to complain; all is well.`"

Many more sweet expressions, in a tender, heavenly frame of spirit, very affecting,
he uttered to those about him in the time of his sickness, that were not noted.
He continued in a sweet, composed frame of spirit and resignation of mind to the last,
and departed in great peace the 7th of the Eighth month, 1715;
and no doubt is in eternal rest,
receiving the reward of his many faithful labours and services for the truth,
for the promotion of which, as by the account he kept, his travels to the year 1700,
were nearly forty thousand miles; besides his travels from the year 1700 to 1715,
in which he died, were also very considerable.

His body was brought to London;
and being greatly beloved by people of divers professions,
his corpse was attended by a great company from Devonshire-house meetingplace,
to the burying-ground belonging to his friends in Bunhill-Fields,
and there he was honourably interred.

[.asterism]
'''

JOSEPH WELSH, of Chesham, in the county of Bucks, was born at Aylesbury,
in the said county, in the year 1651, and was convinced of the truth in 1674.
It pleased the Lord to call him forth in a public testimony about 1676,
and he became a faithful labourer, and serviceable in the work of the Lord in Chesham,
and other adjacent meetings,
though for some years past he was disabled by infirmities of body.
He was a diligent frequenter of meetings on other days as well as the First-day.
He was also a promoter of good order in the church, and so continued to his end.
His testimony was attended with life and power,
to the comfort and satisfaction of the hearers.

A few hours before his death, he declared the Lord hath a great work to do in the earth,
and that it would go well with the faithful,
whom the Lord would hide in the hollow of his hand.
This honest man was a loving husband, a tender father to his children,
and a lively minister.
He departed this life the 11th of the Eighth month, 1715,
and was buried in Friends`' burying-ground at Chesham, the 16th of the same;
being accompanied by many Friends, and others.
Aged about sixty-three, and a minister about thirty-nine years.

[.asterism]
'''

SUSANNAH SAUNDERS, late wife of Edward Saunders, of Clifton, in Bedfordshire,
was one whom the Lord called and sent to labour in the ministry of the word of life,
by which she was fitted and qualified to labour in true love for the good of souls,
and left her husband and tender children to preach the gospel freely,
and to visit the churches of Christ in divers parts of England, Wales, and Ireland.
And her visits were serviceable and acceptable,
and her conversation was as became the profession she made.

She landed in Ireland with her companion, Benjamina Padley,
on the 10th of the Fifth month, 1715, and travelled in many parts of that nation,
visiting most of Friends`' meetings there.
On the 31st of the Seventh month, 1715, they came to Lurgan,
and having been at some meetings in that town,
on the 8th of the Eighth month went to Raffer Island,
and the next day were at a marriage at the house of Jacob Wilson,
where the said Susannah Saunders went with some difficulty, being ill;
but the Lord was pleased to enable her to bear testimony for him.
She afterwards was at a meeting ten miles further;
and the Lord was with her and strengthened her;
but when the meeting was over she was very ill, and finding herself much out of order,
her companion desiring her to go back,
she consented yet went to meetings as long as she was able.

On the 26th she was at a meeting,
where she was engaged in testimony to the great satisfaction of Friends;
for the Lord gave her suitable ability to do what he required of her,
which she did perform to the honour of his name.
But after this she weakened much, and her bodily affliction was great,
which she bore with much patience and resignation to the will of God,
and often declared she thought she should not return home; yet said,
"`I am easy and resigned,
and have endeavoured to discharge my duty according to my small measure,
and have been freely given up to spend and be spent for the gospel`'s sake,
and the Lord hath been good to me.
I pity my dear husband,
and often think on him but hope he will be enabled to bear his exercise.
My poor little babes will miss their mother; but I commit them to him that gave them me,
who I believe will take care of them.
The Lord took care of me when I was tender in age,
and he hath been good to me from my childhood.`"

She advised her companion to faithfulness and watchfulness,
and reminded her of the goodness of God which she had been a partaker of;
and was fervent to the Lord for her preservation;
and that she might give her up freely to the Lord`'s disposing hand;
and that he might endue her with patience to bear her exercise;
and in a very tender and sensible manner expressed herself, saying,
"`I have a secret hope it will be well with me.`"
Then said again,
"`Freely I resign myself into the hand of God:`"
and she returned thanks unto him for her preservation.

Another time, several friends being present, she said,
"`There is great satisfaction in an easy mind.
I have great peace in that I have been faithful.
I have not spared this piece of clay;
but while I had strength I have been willing to answer what I was called to:
and now it seems as if my time was nigh at an end.`"
At another time she said to her companion, "`The Lord has been good to thee; be faithful,
for it is good to have an easy mind.`"

One night she seemed as if she was nigh to depart this life;
her companion being in sorrow, she took her by the hand, and said, "`Dear child,
give me up freely, and have thy eye to the Lord, and he will be with thee,
and give thee strength.
He has been with me,
and I can say it is a good thing to have a clear mind at such a time as this.`"
Again, "`How vain are men to be so taken up with the concerns of this life,
and seeking to get riches in this world.

What is this world worth?
It is not worthy to be compared with the joys of heaven;
they that are faithful to the Lord will have their reward.
I am now glad that I served the Lord, for I feel the peace and satisfaction of it,
and find nothing, but all is well: I cannot say when I shall go,
but it seems as if it might not be long; however, that is in the hand of the Lord,
and I am resigned whether in life or death.`"
Much more she said to them that were about her, exhorting them to fear the Lord,
and to seek a portion in the truth, which, she said, would be more to them,
when they were about to leave this world, than any other enjoyment.

Another time she said, "`The man is blessed whose God is the Lord.`"
Again, "`It is a good thing to have the mind truly stayed upon God,
they shall be kept in perfect peace: a great mercy! a mighty privilege!`"
Another time, being very ill, and to appearance nigh unto death,
her companion being sorrowful and loth to part with her,
Susannah took her by the hand and kissed her, saying, "`Dear child,
why wilt thou hold me?
let me go, and do not be sorrowful, but keep to the Lord and he will preserve thee.
Farewell.
Be good and do well, and the Lord will bring thee through all.
Thou hast yet some light afflictions to pass through; but be not discouraged;
nor look at what may seem mountainous, but be watchful and look to the Lord,
and that hand that hath hitherto helped thee, will help thee.`"

She said to friends, "`Dear friends, love truth, it is excellent, it is above rubies.
Oh! it is precious, it is above all things, it makes a deathbed easy.
I am glad my lot is cast in this place, with a couple of young plants that love truth;
keep to it, and it will make you noble.
Dear landlady, farewell; the blessings of the everlasting hills be upon your heads;
the Lord bless you and make you serviceable in his church.`"
Then speaking of her illness, said, "`All that I crave now is patience,
that I may hold out to the end, that I may not dishonour the Lord:
the honour of his name has been as dear to me as my life.`"

A few days before she died, several friends came to see her,
and after some time her mouth was opened amongst them in
a sweet exhortation to love truth and keep to it,
and to be watchful and to keep to the Lord,
and not let their minds be too much after the world:
and testifying of the goodness of the Lord, she committed them, with her own soul,
to his protection, giving honour to his name.
That night she was very ill, and said, "`It is hard work to leave this world;
one had not need have anything else to do,`" or to that purpose.

Next day, being First-day, she was very much weakened,
and some friends coming in that evening to see her, she said,
"`I am glad to see so many of you, I did not expect to be here so long.
I am long a dying, it is hard work to die.`"
Then friends sitting in silence a while, she exhorted them to faithfulness and diligence,
and to love truth, and to seek the honour of God, adding,
"`Oh! that the youth of our age would love truth, and seek the Lord,
and serve him in their youthful time: they will have the benefit of it.
It would be more to them than all the world.

But many of them are careless, and contenting themselves with a profession,
and that will do nothing for them.
My soul hath often mourned for the youth of our time,
and I have been under great travail of soul, that they might come to fear the Lord;
but there are many of them that grieve the Lord,
and are following the pleasures of this world.
Friends, love truth, and it will make you noble.
Oh! that the elders would love truth: there are elders that love the Lord,
and they are a comfort and a strength to the youth that fear God, and to one another;
they are as joints and bands that cannot easily be broken, my soul loves them.
Seeing it was the will of the Lord to visit me with weakness,
so that I am not likely ever to see my habitation again,
I am thankful my lot was cast in this place.
Dear friends, keep near truth, and it will keep you in a trying time;
for there is a trying time approaching, in which there will be great desolation.`"
With much more to the same purpose.

She often spoke of the goodness of God to her from her very childhood,
and enumerated his favours, and acknowledging his care,
said he had been a tender Father to her, and she believed he would be so to hers.
Her affliction being very great, she besought the Lord, in an humble frame,
that he would be pleased either to relieve her or release her,
or to give her patience that she might not murmur.
Then looking on them about her, said,
"`It is hard work to go out of this troublesome world.`"

About four days before she died she wrote to her husband,
wherein she signified that she weakened daily,
and that the Lord by his divine hand had wrought a willingness
in her to spend and be spent for his name`'s sake,
and that she felt sweet comfort, "`quietness and content, "`which,`" said she,
"`out-balanceth all things else.
My dear, I fervently desire the Lord may be with thee, and bring thee to a resignation.
Stand faithful in every branch of thy testimony for the blessed truth;
thou wilt have the comfort of it.
Dear heart, if I should never see thy face more,
I desire thee to take care of our tender babes, and bring them up,
as much as in thee lies, in the fear of the Lord.

I have been deeply bowed on their accounts, am fully satisfied, if they live,
the Lord will visit them in their tender years,
and it seems to me as if my dear Susannah may tread in many respects,
in her mother`'s steps.
The Lord preserve her, and bring her to choose him for her portion; then it will be well,
and she may be serviceable when my head is laid in the silent grave.
My dear little boy, if he grows up, it will be hard for him to submit to the yoke,
yet I secretly hope he will in time be made to bow,
which is some satisfaction to my mind.
I must commit them to the tender care and protection
of him who gave me them;`" with more not abstracted,
which she concludes in entire love, his affectionate wife, etc.

The day she departed, sitting in a chair, the pangs of death being upon her,
she desired to lie down, which she did, and waited for her change; and R. H. being there,
was concerned in supplication for her.
When he had done, she said,
"`There is a divine hand has laid some hold at this time,`" and so went on sweetly,
declaring of the goodness of God, and desiring her friends might be faithful,
warning them of the judgments of God that were near to be poured forth upon the nations,
and exhorted them to flee to the Lord,
who would be their defence and strong tower in the time of distress.
And having spoken much of the wrath of God that was ready to break forth,
exhorted Friends to abide upon the rock.

Then she broke forth in a sweet manner, setting forth the glory of the kingdom of Christ,
that the Lord, after he had punished the nations, would exalt the kingdom of his Son,
and set him upon his holy hill of Zion, and all nations should flow unto him,
and he should exalt the sceptre of his righteousness above all sceptres,
and his kingdom above all kingdoms.
Then blessing God for his preservation and mercy towards her,
and for the assurance given her that it would be well with her, she said,
"`I have not sought a name or fame among men;
but have discharged myself faithfully in the sight of God.
I have not desired to appear in show what I was not;
but to be in substance more than I appeared to men.
And it was neither for honour nor esteem that I left my dear husband and tender babes;
but that I might answer the will of God,
and in a concern for the promotion of truth and the honour of God.`"
She desired the Lord would bless his people in that nation,
and particularly that meeting and family where she then was,
and reward friends for their love and care towards her.

She continued her exhortation to them to be faithful;
again declared of the goodness and mercy of God; and so lay in a sweet frame of spirit,
giving glory to God and magnifying his power, until her strength and speech failed.
Then, lying still, she looked on those there with a pleasant countenance,
as one who had a sight of the joys she was entering into;
and about the 7th hour in the evening, departed this life, the 9th of the Ninth month,
1715, and was buried the 12th of the same, in Friends`' burying-ground in Lurgan,
her corpse being accompanied by a large number of Friends and others;
and there was a good meeting, in which the glory of truth was eminently manifested,
to the tendering of many hearts, which was as a seal upon the spirits of friends,
that it was well with her.
Aged about thirty-eight, and a minister eighteen years.
