== Chapter 2

[.chapter-synopsis]
* William Taylor
* Richard Heydon
* Margaret Hoare
* Jonathan Tyler
* John Skelton
* Anne Dixon
* John Crudson
* Samuel Randal
* George Gibson

WILLIAM TAYLOR, son of John and Agnes Taylor, in Whitehaven,
was servant to Ebenezer Pike, of Cork, who, with many others there,
declare that he approved himself faithful; was sober and well inclined,
and in his conversation very exemplary.
His love to truth, and those that walked therein,
drew an esteem from honest friends towards him, being careful to keep meetings,
and not to miss the advantage of such opportunities, whether public or private.

He was taken ill with the small-pox, and was visited by Friends.
Some time before his departure, he said, "`Peter Tomey, I have desired thy company,
and some more honest friends, that you may see my departure;
for the time seems to be short, and my poor mother will never see me more.`"
Being in a sweet and sensible frame of mind, he said,
"`I desire thee to remember my dear love in the truth, to my father and mother,
sisters and brother, and to friends in Cumberland.
I am thankful my mind is kept easy and quiet, and I account it a great mercy from God,
and hope I may continue so to the end.
I desire thou mayest be concerned in thy spirit, that I may finish my journey in peace.`"

He said to Deborah Bell, "`The Lord hath been good to me from my childhood to this time,
and I have loved him since I knew him,
though at times there hath not been such a close walking with him as ought to have been.
But I hope if the Lord sees meet to take me away at this time, he will be merciful to me;
and if I live longer, I hope to be more careful to answer his will.
But, said he, I am as if I was under a cloud,
and cannot enjoy so much of the love of God as I gladly would,
and which we poor creatures want, when we come to such a time as this.
I do not think I shall get over it; the Lord is good to me,
and at times gives me tastes of his love.`"

The day before he died, he said, "`To my great comfort, the Lord is come,
and hath filled my soul with his love; and now I am ready.`"
And afterwards signified he was going to everlasting rest,
where he should sing praises and hallelujahs forever and ever.
He also added,`" It will be a hard thing for my dear father and mother,
when they hear of my death, but tell them from me,
I desire they may bear it with patience, for I am happy, and remember my love to them.`"
He desired those present to bear witness,
that he went out of this world in a sensible condition,
and with full evidence and assurance of eternal life: saying,
"`Now the enemy is driven away, and never shall return again;
he has done with me forever; glory, glory to my God.`"

He continued in praises and thanksgivings for a considerable time,
and gave very excellent advice to several persons, for he was exceedingly full and open,
and strengthened to admiration to speak for the Lord.
About an hour after, he said to his nurse and some others,
"`Now I am going;`" and so quietly departed the 8th of the Sixth month, 1717,
like a lamb.

[.offset]
Here follows a paper that was written by him, giving an account of his age when visited.

[.embedded-content-document.paper]
--

In the Seventh month, 1706, I being then between twelve and thirteen years of age,
the Lord was pleased to visit my soul by his divine power, which seized upon me,
and brought me to a sense of my state and condition.
I had never been addicted to any gross evil,
but had spent too much time in playing with other children,
and in light and vain discourse:
and although I had been soberly educated amongst friends,
and constantly frequented meetings,
yet I saw I had not lived so in the fear of God as I ought to have done.
Now I also saw in some measure the necessity of an inward work,
and that I must forsake and part with all my former vanity and pastimes.
This brought great sorrow upon me, so that I was ready to say,
this inward sorrow and exercise of soul is harder to be borne than all outward affliction.

I was in great trouble and sorrow for some time,
not so much from a sense of former guilt, but the Lord`'s power working in me,
changed my heart, and I was very sad and heavy,
and the cross of Christ seemed hard to bear.
I thought it was very hard, that I, who was so young,
should part with all youthful pastimes.
But soon after, the Lord was pleased to let me see, in some measure,
the beauty of his truth, and how he would love those that feared him;
and did so overcome my heart in a sense of his love, that I was ready to say,
I will give up my heart to the Lord; he shall have my youthful days.

Then the fear of the Lord seized upon my heart, and as I kept to it,
with my mind exercised in spiritual things, I was preserved out of my former vanity,
and became sober, and was much inclined to reading of Friends`' books,
which before I did not mind,
and delighted to read those authors who had written their own experience,
concerning the Lord`'s work in them at their first convincement,
and the first breaking forth of truth, also their travels and sufferings.
In the reading of these I was much affected, and often comforted,
having a sight of the glory of that day,
and also of the Lord`'s goodness to those his faithful servants in the beginning,
and how they were preserved through all their exercises.

My business at that time being amongst some loose and vain people,
who did not fear the Lord, their idle talk and vain communication were very uneasy to me;
and I saw they were strangers to the work of regeneration,
and I lamented their condition; and when I awoke in the morning,
oh! the fear and dread that was upon me.
Thus for some time I was religiously exercised, but a while after,
I frequented the company of some young people, some of whom were Friends`' children,
but they were light and airy in their conversation, and much given to mirth and jollity.

I being drawn in amongst them, began to take delight in their company,
and many hours were spent, in the winter evenings, in idle talking and foolish jesting,
by which I was much hurt, as to my inward condition, and began to be settled in ease,
and so got from under that concern of mind which had for some time been upon me.
Yet the Lord by his light and grace in my heart often reproved me for my wantonness,
so that I was preserved from gross evils, but too much given to lightness and mirth.

But the Lord, whose love was still towards me, did not leave me in that state.
I remember one time when I was sitting in a meeting, the power of the Lord seized me,
which turned my heart towards him;
and by the shining of his light and grace in my heart at that time, I clearly saw,
that if I would be Christ`'s disciple, I must take up his cross,
and give up my heart to the Lord; have my mind taken off from the things of this world,
and stayed upon God.
And that saying of the Apostle was brought to my remembrance, viz.,
"`To be carnally minded is death, but to be spiritually minded is life and peace.`"

--

[.asterism]
'''

RICHARD HEYDON, late of Oddington, in the county of Gloucester, was an honest, plain,
sincere-hearted man; of a tender, loving, compassionate spirit;
a nourisher of good in all,
and one who bore a testimony against every appearance of evil.
Having a fervent love and zeal for truth, he laboured for the prosperity of it,
and was a good example in his day, to both old and young.
He was one of whom it may be well said, he was a preacher of righteousness,
his life and conversation being agreeable to his profession;
so that the innocency and sweetness of truth appeared in him,
even in his commerce and dealing amongst men,
it being his care to give no offence to either Jew or Gentile, or the church of Christ.

It may be said in a good measure of him, as was said of Nathaniel,
that he was an Israelite indeed, in whom was no guile;
for he preached in life and conversation, even to those that were without,
and was a good example in so doing, to all who made a profession of the blessed truth,
amongst whom he also laboured in word and doctrine, exhorting all to faithfulness to God,
and his truth, that so they might feel the living virtue of it in themselves,
whereby they might come to be seasoned with the salt of the covenant.
He was often under great concern of mind for his children,
and in order that they might come to witness a growth in the truth,
he was concerned to wait upon the Lord in his own family,
to seek to him in supplication for them;
and the Lord was pleased to answer the desire of his soul in a good measure,
so that he lived to see the travail of his soul, and was greatly comforted therein.

Although his gift in the ministry was not large, yet finding a concern upon his mind,
which rested upon him for some years, to visit the churches of Christ in Wales,
and a companion offering, he set forward in his journey with the unity of friends,
in which service he had great satisfaction.
It pleased the Lord, who knows what is best for his people,
to visit him with the small-pox, at our worthy friend John George`'s house,
at Landewybrevy, in Cardiganshire, in South Wales;
in which illness he was resigned to the will of the Lord,
and declared of his goodness to his soul.
Although he was in great pain, and very ill in body,
his soul was visited with the tendering power and sweet love of God,
so that he sat up in his bed, and with tears declared of the sweetness and virtue of it.
"`Oh! how sweet is the love of God; it is now sweet to my taste;
it is sweeter than honey, yea, than the honey-comb; it seasoneth our exercises;
it sweeteneth the bitter cup to us,
and the divine streams of it bring comfort and refreshment to the weary soul.`"

He signified his concern that Friends might witness the Lord to be near at such a time,
saying, "`A profession of truth, without faithfulness thereto, is to little purpose.
It will bring no comfort in a time of trial,
which comes many times when we are not aware of it.`"
And again he said, "`Many are those to whom the Lord has made known his way;
and oh! that all might make straight steps in it.`"

Some friends coming to see him, he was opened in advice to them,
and in great tenderness of spirit, said, "`It is necessary for friends,
when they meet together, in order to worship God,
to sit down under a right exercise of mind,
and with diligence wait to feel his bowing power
to tender and bow down their spirits before him,
that so they may come to feel the virtue and weight of truth upon their spirits,
which in itself is pure and weighty.
And as they thus come, they will be livingly concerned for the honour thereof;
for it is too common to see some amongst us, yea, some that profess the truth,
with sorrow I speak it, overcome with sleep when they are in meetings,
which brings trouble and sorrow to the diligent and honest-hearted,
and they may be stumbling-blocks to other people that may drop in among us.`"

Thus this dear friend was concerned for the prosperity of truth to the last,
and his distemper increasing upon him, which proved him greatly,
yet he continued in a quiet frame of spirit, and on the 23rd of the Tenth month,
departed this life like a lamb, without either sigh or groan, and is, we doubt not,
entered into that rest that God has prepared for the righteous.
His body was accompanied by several friends, to Friends`' burying-place at Llandovery,
where he was interred the 25th of the same month, 1717, aged sixty-seven years.

[.asterism]
'''

MARGARET HOARE, the wife of Joseph Hoare, of Cork,
was dearly beloved by Friends in general,
for they came frequently to visit her in the time of her weakness;
in several of which visits they had very sweet and heavenly seasons with her,
wherein the melting power and love of God were at times richly manifested among them;
and in some of them she was sweetly drawn forth in testimony,
to the tendering many hearts, as likewise were some other Friends on the like occasions.

Some time before her departure, many Friends being in her room,
and waiting in silence upon the Lord, she was drawn forth very livingly in testimony,
by way of advice and counsel to them, as well as something relating to her service,
and testimony for the Lord.
To Friends she pressingly recommended their seeking after and loving the Lord above all;
and the enjoyment of truth, and the life of it, beyond the world, and the things of it;
and not to let their minds be taken up,
and encumbered with fading and transitory objects;
and then they would both clearly see their way,
and be ready and willing to do and answer what the
Lord might be pleased to require of them.
Adding, in great tenderness of spirit, that as to herself,
she could in great humility and reverence, as well as thankfulness, say,
that she had answered the Lord`'s requirings in her day,
by giving herself up to his service;
and that she could not charge herself with declining any journey,
or service in testimony, that the Lord required of her.
"`This,`" said she, "`is now my great comfort and satisfaction of soul,
in this the time of my weakness.`"
Much more to the same purpose she uttered at that time,
in a heavenly sweetness of spirit, which could not be remembered.
At another time, being overcome with the love of God,
she spoke in a holy admiration thereof, and of the divine excellency of God`'s salvation,
and of her feeling of it at that time: adding,
with great sweetness and fervency of spirit,`"My salvation is sealed.`"

Another time, seeing some Friends very sorrowful for her, she said to them,
"`Be not concerned for me, I pray you; there is no cause of sorrow on my account.`"
Upon several occasions she expressed her great love
and affection to her husband`'s two children,
and likewise of their affection and dutifulness to her; and not long before her death,
she spoke to her son-in-law thus, viz.,
that she could never make any difference between them and her own children; desiring him,
that as his little brothers grew up, they should live in love with one another;
adding thus, "`The Lord was pleased once to bring thee very low,
and he had a good end in raising thee up again; and that the Lord loved him,
and desired he might love the Lord, which she hoped he would do.`"
To her brother Pike she expressed herself after this manner,
with much affection:`"My dear brother, I have loved thee very dearly in the truth,
ever since our first acquaintance,
and my soul hath been nearly united to thee by the Lord`'s spirit, in which our love,
union, and fellowship have stood.
We must part, but in a little time we shall meet again, never to part more.`"

At another time, seeing several friends weeping about her, she said to them,
"`Do not cry for me.
I do not die as one without hope.
I shall have no more tears; they are all wiped away.`"
Some time after, her lips moving, she was heard to speak softly to herself;
upon which her sister Pike, putting her ear near her, heard her praying to the Lord,
and praising him, saying,
"`My soul doth magnify the Lord,`" with more to the same purpose;
which she could not so distinctly understand,
by reason of her weakness and lowness of voice.

At several times she expressed to some friends her satisfaction in coming for Ireland,
and of her being in her right place.
She desired that her dear love might be remembered to her mother;
and the day before she died, she said to some friends about her,
"`Remember my dear love to all my dear Friends, and tell them I am going to my God,
and their God; to my King, and their King.
I have a clear conscience, void of offence towards God, and towards all men;
the Seed reigns:`" and so went on magnifying the Lord.
The same day she was taken with a violent fit of coughing, so that herself,
and the Friends about her, thought she was going off; but recovering again, she said,
with a holy concern of mind, "`And must I stay longer?
I thought I was sweetly passing away.`"

Her brother Pike coming to see her, she said to him, "`Dear brother,
I am glad to see thee, but should have been more glad to have been gone.
I thought I was sweetly passing away.
Oh! sweetly, sweetly, I thought I was going.`"
Growing weaker and weaker, her strength and speech began to fail,
yet she spoke softly to herself; which some friends about her observing,
and listening to hear, perceived by what she uttered, as if she saw a vision,
and had a sight of a glorious city which she saw; for she was heard to say,
"`An excellent city, paved +++[+++as they understood she meant]
with gold;`" adding, "`It will be mine forever.`"
And thus by degrees her strength and speech failing, she died in the Lord,
the 24th day of the First month, 1718, being greatly lamented by others,
as well as Friends in general.
The foregoing instances are but a few,
in comparison of the many sweet and heavenly expressions
which she uttered in the time of her weakness,
which yet were thought fit to be kept as a memorial of her for time to come.

[.asterism]
'''

JONATHAN TYLER, son of Charles Tyler, of Calne, in the county of Wilts,
was convinced of the blessed truth about the 21st or 22nd year of his age;
and after some months it pleased God to open his mouth,
and give him a large gift in the ministry, in which he was a faithful labourer,
and divided the word aright; and the divine presence of God attended him in his ministry,
to the making glad and refreshment of many.

He travelled through most parts of England to visit Friends,
and also Scotland and Ireland; and in America, as Pennsylvania, New York, New England,
East and West Jersey, Maryland, Virginia, and Carolina.
In all these places he took abundance of pains,
and travelled for the space of three years in those American countries.
He was a noble instrument in the hand of God,
and had great service for God and his truth in those places;
and many were turned from darkness to light,
and from Satan`'s power to the power of the Lord God,
by his living and powerful ministry.
He was a loving and affectionate husband, and a tender father,
both to his own children and to the church of Christ.
He was a good and peaceable neighbour, and of a sweet and pleasant temper.

After he came from America he married and settled at Bradford,
in the county above mentioned, and was very serviceable, in those parts,
to the churches of Christ, and for his loss many have been sad,
yet there still remain seals of his living ministry.
After long struggles with his distemper, the gout, which settled in his stomach,
he was confined to his bed; and on the 22nd of the Tenth month, 1717,
on the First-day of the week, his wife and children,
with several other relations being about him in the evening, after meeting,
he seemed somewhat refreshed and comforted thereby; and raising himself on his bed,
in a living frame of mind, expressed himself to them as followeth:
"`If the Lord please he can restore me.
So long as there is life there is hope; but when death is come,
then there is no more hope.
The Lord God can, if he please, work miracles upon me, and preserve my life, which,
if he do, it must be for some good and glorious purpose.
He is a good God to me;`" and said, "`O thou good and sweet God.
Who can forget so good a God.`'

He was proceeding further,
but was interrupted by the coming in of several friends to visit him;
and being taken out of his bed, a little to refresh him,
and understanding it was First-day, after some inwardness, he said, "`Oh!
I have lost two feast-days.
These and Fourth-days used to be my feast-days,
and if I could have but one good meeting more,
that would do;`" intimating that then he should be entirely satisfied.
Then remaining silent he proceeded, "`By this I know that I am passed from death to life,
because I love the brethren.`"
He also cited the text to the same purpose, repeating divers times,
that God was good to him; and with great admiration and emphasis, said several times,
"`O, dear God! thou art glorious, and livest forever and ever.`"

Being put into his bed again, a friend asked him if he knew him; he replied,
"`Yes,`" naming his name: then the friend asked him how he did; he replied,
"`Very ordinary, I hardly know any thing now, only this I do know,
that I am yet alive upon the earth, and that is a mercy;
and I know that God is good to me, and that is a great mercy.`"
About the middle of the night, being worse than ordinary,
the family was called about him, but somewhat recovering, he was heard to say,
"`To know thee, the only true God, and Jesus Christ, whom thou hast sent,
is life eternal;`" several times expressing his sense of God`'s great goodness to him,
and was often in great inward melody, and sometimes audibly sang praises to God.

The next day, being the 23rd, notwithstanding his pains were very pungent,
he remained patient, and generally sensible, and a sister-in-law coming to him,
expressed her trouble to find him so weak.
He told her, "`It is better to come to the house of mourning,
than to the house of mirth;`" and his near friends weeping about him, he said,
"`Oh! why do you trouble me; it is a brave thing to be quiet.`"
Being under a painful operation of his physician, he told us,
that he should live his appointed time, and no longer.
"`The Lord has been the keeper of my soul and body, to this time;
and he will keep me forever.`"
He remained till after the middle of the night in a sleeping condition,
his distemper lying pretty much in his head, when awaking, he very livingly uttered,
"`O death I where is thy sting?
grave, where is thy victory?
Lord Jesus come quickly.`"
Then his son-in-law asking him how he did; he answered, "`I am going into another world.`"
He called his brother Joseph, and said, "`The Lord is good to me;`" and pausing a little,
repeated,`"death! where is thy sting?
grave, where is thy victory?`"
also signifying he was not afraid of death, nor of what came after.

About three or four in the morning, he called his wife and told her,
that after some exercise of mind, he could now tell her,
that he knew that he had a being yet in this world,
and that God would give him a being hereafter.
This was occasioned, as was apprehended, by a struggle with his distemper,
affecting his head, which had for some little time before hindered his utterance,
because that now he said, he was fully satisfied.
His wife asked him, if he had any thing to say to his children; he answered,
"`They will have a great loss of a tender father.`"

Great part of the next day, the 24th, his spirits and strength so failed,
that he said but little,
unless it was now and then when he seemed to have
some short intervals of ease from his pain.
He would thank the Lord, and speak of his goodness to him.
His resignedness and patience were remarkable,
for notwithstanding the greatness of his pains, yet he was never observed to repine,
or utter any irreverent expressions, but in his greatest extremity, would praise God,
and acknowledge his goodness to him;
and when his speech so failed that he could not speak intelligibly to those about him,
yet he would clearly and distinctly call on the Lord to the last.
He deceased in great quietness, without sigh or groan,
about the eighth hour in the evening, on the 24th of the Tenth month, 1717,
aged about forty-eight years.

[.asterism]
'''

JOHN SKELTON, late of London, received the blessed truth in the love of it,
by which in time he was sanctified, and the Lord, through the work of his Holy Spirit,
prepared him for, and called him into, the ministry of the gospel of Christ.
Therein, through the grace of God, he was enabled,
according to the measure of the gift bestowed upon him, to be a faithful labourer;
his conversation being agreeable to the truth he preached,
and his love to God and the brethren unfeigned,
and through diligence he improved in the talent received.

In the year 1716,
he was drawn forth in the love of God to visit Friends
in many counties of England and Wales,
and the Lord`'s living presence was with him, to the joy of his soul, as he declared.
He travelled, in two years, 1665 miles; and after his return, for several months,
he visited the meetings of Friends in London and the adjacent parts.
When he was taken ill he had a complication of distempers, viz., cough,
shortness of breath, and dropsy.
He was in a heavenly frame, and resigned to the will of God, whether to live or die;
"`for`", said he, "`I witness peace with God, through Jesus Christ,
in whom alone I trust for eternal life and salvation.`"
Great tenderness of spirit appeared in him,
and several other sweet and comfortable expressions at sundry times dropped from him.
At one time he said, "`The Lord is abundantly good to my soul;
he hath fitted and prepared me for himself.`"

At another time he said, "`The Lord`'s will be done;
for I will wait all the days of my appointed time, till my change come.`"

He oftentimes made humble and grateful mention of the goodness of God,
and love of Christ to his soul, and broke forth into praises to his excellent name.
The morning before he departed,
being asked whether he had any thing more to say to his wife and daughter, he answered,
"`I have no more to say to them.`"
A friend a little after said, "`Dear John,
I perceive thou art not far from thy journey`'s end;
it will not be long before thou wilt be at thy heavenly Father`'s house,
where are many mansions of bliss and glory.`"
He very sensibly answered, "`I hope so;`" and soon after,
he quietly departed in peace with the Lord,
and is entered into that blessed and everlasting
rest that is promised to the people of God.
His body was interred on the 10th of the First month, 1718,
at Friends`' burying-ground near Bunhill-fields,
being accompanied from the Peel meetinghouse by many friends and others.
Aged sixty-three years.

[.asterism]
'''

ANNE DIXON, daughter of Christopher and Elizabeth Dixon, of Streatham,
in the county of Durham, was from a child religiously inclined,
and tenderly affectionate to those who kept their places in the truth,
being much delighted in reading good books,
and was of a very sober life and conversation, gaining a good report,
and well-beloved of all; watchful that she might not offend the Lord,
by being an evil example to others.
Falling sick of the small-pox, upon the 7th day of the Second month, 1718,
she continued in great weakness of body the space of six days,
during which time these expressions following, amongst others, were observed.

She being under great affliction, said, "`One had need be near the Lord;
for we know not how soon we may be taken away.
I hope the Lord will be merciful to me, not through my good works,
but by his favour and great lovingkindness.
It is well I lived so near the Lord, it stands upon us so to do,
and if the Lord should spare me any longer, I hope I should live nearer to him than ever,`"
saying, "`O God remember me.`"
She said to her father, "`Dear father,
have a care that thou do nothing that may offend God;
and if thou hast done any thing that hath offended him,
let the time past be sufficient.`"

She also desired some present to tell her brother Joseph Dixon,
"`To live well for the time to come;`" and she bade her younger brother "`be a good lad,
and the Lord will be kind to thee;`" exhorting a cousin then present, not to mind pride,
and finery, but the fear of the Lord: Being in some agony of spirit, she said,
"`Oh! that I had a full assurance of my entrance.`"
Desiring all present to withdraw, her mother only excepted,
and turning her face to the wall, her lips were perceived to move,
and in a little time she broke forth into praises, saying,
"`I have now received full assurance from the Lord.
Now I can return him praises.
Oh! glory to my God;`" repeating it over again: saying further, "`The Lord was near,
and I knew it not;`" praising the Lord then in an harmonious manner.

Another time she said, "`If I go now, I hope I shall be no dishonour to the truth,
for I have nothing but love and good will to all.
I have wronged nobody, neither done an ill thing that I know of, in all my life.
I doubt people will praise me when I am gone, but all the praise is due to the Lord.`"
At another time being very weak, she said, "`Though my afflictions are very great,
yet I am borne up over them all.
It is a brave thing to be prepared for a dying-bed.
Lord, hasten thy work.`"
Several times expressing her willingness to die; and in true love and charity with all,
departed this life in peace with the Lord, upon the 12th, and was buried at Raby,
the 15th day of the Second month, 1718, aged twenty-six years and about three months.

[.asterism]
'''

JOHN CRUDSON, of Kendal, Westmoreland,
at one time speaking of the exercises of the Lord`'s people, said,
the Lord was still with them so long as they kept faithful to him;
mentioning in particular, the wonderful deliverances of God to the children of Israel,
while they stood faithful to him.
He also spoke of the great exercise of the three
children that were cast into the fiery furnace,
and their wonderful preservation therein, with what became of the men that cast them in:
as also of the trial of Daniel being cast into the lion`'s den,
and standing faithful to God, he was preserved through all.
Under the consideration thereof, he advised all to be true and faithful to the Lord,
that they may witness preservation in, and through, all their exercises.

At another time speaking of being removed hence, he said, he desired,
whether he lived or died, it might be to the glory of God;
and that if it pleased the Lord to remove him at this time,
he would be a husband to the widow, and a father to the fatherless children;
and that he would be pleased to enable him to leave a testimony for him,
to them that were left behind; expressing at that time his great satisfaction,
that he felt salvation near to him.
He was often concerned to advise those present,
to be very careful how they spent their time whilst in health,
for he found there was enough to do when we come upon a sick-bed,
and that many did not rightly consider how swiftly time slipped away,
which seemed to show they did not walk in an exercising path.
He also earnestly desired, that the Lord would be pleased to carry on,
and prosper that great work he had begun;
and that he would be with Friends in their several meetings for discipline,
especially in this place.

Another time, being in a heavenly frame of mind, he prayed fervently to the Lord,
to the tendering the hearts of friends present, saying,
"`O Lord thou knowest my weakness and inability of body, and that I am as a worm,
and no man, and scarcely am able, at many times, to think a good thought,
the enemy is so busy, now in the time of my great weakness.
Yet, most holy Lord, I am humbly thankful to thee,
for that thou hast been graciously pleased, to my great satisfaction,
to promise that thou wilt make war, and fight all my battles for me.
O Lord! thy love, and the enjoyment of thy presence,
are more to me than all the enjoyments of this fading world; yea,
far beyond all cordials.
I humbly crave it of thee, if it be thy will, to favour me therewith more and more,
in this time of great weakness, even to the end.
O, most holy Lord!
I am truly thankful to thee, for thy many favours and blessings to my family,
both spiritual and temporal; and if it be thy good pleasure to separate us,
I beg of thee, that thou wilt receive whom thou art pleased to remove,
and stay with them that are left behind.
And Lord,
thou knowest I have many times been earnestly concerned in my spirit for a young generation:
grant that my children may come up to serve thee in thy fear;
and although I have educated them according to the best of my understanding and persuasion,
yet Lord I beg of thee, let them know thy work in their own hearts for themselves,
lest a libertine spirit should at any time prevail.`"
Then returning praises to the Lord, who over all is worthy,
he concluded sweetly at that time.

Another time several friends being present, he said, "`Dear friends,
I feel something upon my mind, to say to you, which is,
the Lord is wonderfully good to his chosen and redeemed people;
and although I have been very poor, inwardly poor of late,
yet may say as I have waited upon, and sought the Lord,
he hath been pleased to open to me the spring of life and truth again,
to the comforting of my poor soul.
And though my exercise of body is, and has been, very great,
so that I never had the like in all my time, never so near death as I seem to be,
yet I feel the supporting hand of the Lord underneath:
and notwithstanding I have as comfortable enjoyments in this world as most of men,
yet the enjoyment of truth is above all.
Dear friends, labour in your meetings, and in your families,
to witness the work of truth for yourselves, to help over the dark, dull, heavy spirit,
that clouds Friends in their meetings.
There is great need of it for both old and young.
There is also the earth, and the clods of the earth,
that very much hurt the minds of friends,
but as friends abide near the truth in themselves, when they come to die,
they will not want a crown.`"
This, with several other things relating to his journey to and from London,
was to the tendering and satisfaction of friends; and so he concluded with "`Praises,
high praises, to the Lord God, and the Lamb, who over all is worthy, now and forever.
Amen.`"

He departed this life the 25th of the Fourth month, 1718,
in the forty-third year of his age,
and was buried in Friends`' burying-ground in Stramangate, in Kendal, Westmoreland.

[.asterism]
'''

[.blurb]
=== A short account from Ireland, concerning our dear deceased friend, SAMUEL RANDAL, of Cork, dated the Twelfth month, 1719.

His first coming to dwell among us was about forty years past, as some of us do remember,
when but a young man, at which time, by his grave and solid conversation,
he adorned the blessed truth he made profession of.
In commemorating his station and services in the church of Christ,
and those qualifications wherewith the Lord was pleased to furnish him withal,
whereby he became serviceable therein,
we cannot but be sorrowfully affected for the great loss we have sustained.
For, as he was a good example himself, in plainness, temperance, and justice among men,
so he was also zealously concerned for the honour of God,
and the promotion of his holy truth;
and that good order and discipline might be maintained among the professors thereof;
and that gospel order,
and the line of justice and judgment might be extended
towards loose and disorderly walkers,
that thereby the holy truth might be cleared from
the reproach and scandal that such brought upon it.

In his dealings either with particular families or persons,
he discharged his duty faithfully, without partiality, or respect to persons,
wherein he was sometimes zealously sharp as occasion required.
And as he was deeply sensible, that the world`'s conversation,
and the eager pursuit after the riches and greatness thereof,
was not only hurtful in itself, but had proved so to many,
so was he in both respects concerned to be exemplary.
For when considerable advantages of getting money presented themselves,
with a very probable prospect, he often denied himself for truth and example sake.
Although he had not a public gift in the ministry,
he was often concerned to speak closely to the states and conditions of many,
to the reaching of their understandings.

Thus in the place of an elder, we may say he was worthy of double honour,
as giving himself up cheerfully and willingly to the service of truth, not only at home,
but by his constant attendance at national and province meetings,
frequently attending the former for many years, in winter as well as summer,
until of late, being hindered by age and weakness of his constitution,
he could not go so frequently as before.

Much more might be said, as to his many and particular services in love to truth,
and the churches of Christ, but intending brevity, we have given this short testimony,
to be recorded as a memorial of him, with desires,
that as the Lord fitted and qualified him for every
good word and work he concerned him in,
so he may raise up many more to supply the place of him,
and the many other worthy elders, who of late have been removed from among us,
that so from one generation to another, there may be a faithful people,
who may be rightly concerned,
that the testimony of the Lord`'s holy truth may be kept up in all its branches.

He was taken violently ill of a pleuritic fever, and said at first,
he thought he was death-struck, and was well content to die, being, as he said,
weary of a troublesome world; that he had lived to the years of his father,
and if it were the Lord`'s will, he was contented to go now.
So, as one given up and resigned to the Lord`'s will, he said he was not afraid of death,
having nothing that stood in his way.
In the continuance of his sickness, he spoke many sweet expressions,
some of which follow: that he had loved, and sought the Lord in his youthful days;
and that he had been with him,
and preserved him through many difficulties and exercises.

"`And now,`" said he, "`I have a sense of, and do feel his goodness,
which is more joy to me than all visibles; and though he has brought me to a weak bed,
I can praise his name;`" often lifting up his hands, and making melody in his heart.
Being one morning very weak, and short-breathed,
he spoke of the goodness of the Lord to him the evening before.
"`The sweet savour,`" said he, "`still remains with me;`" adding,
that he desired none of his dear friends or relations would pray for his recovery,
but rather that he might have an easy passage, and patience to bear the pains of death.

As he was often, in his health, deeply concerned for his children,
that as they grew in years, they might grow in truth and the fear of the Lord;
so he often told them, he was more concerned, that they might walk orderly,
and have a portion in the truth, than for the great things and riches of this world.
The day before he died, he called for them, to whom he gave sweet and heavenly advice;
and particularly he fervently expressed himself to his son Samuel
how great his concern had been for his welfare every way,
desiring him to seek the Lord, trust in him, and he would preserve and bless him;
also to bring up his children in the fear of the Lord, and keep them from evil company,
and to employments.

And in a general way to them all, he said thus: "`I have been often concerned for you,
that you might seek the Lord for yourselves, and live in his holy fear,
and then it will be well with you when you come to die.`"
After this, growing weaker and weaker, two friends coming to see him,
he looked cheerfully on them, and said, "`I am about finishing my course.`"
His breath growing shorter, he lay quietly; and being sensible to the last,
after eight days`' sickness,
we are fully satisfied he laid down his head in peace with the Lord,
and in sweet unity with his people, the 26th day of the Fourth month, 1718,
and was buried the 29th of the same, aged about sixty-four years.

[.asterism]
'''

GEORGE GIBSON was born of believing parents,
who were taken from him when he was but young, yet he was educated among Friends.
It pleased the Lord to visit him with his grace and good spirit,
in his very tender years,
whereby he was early inclined to seek after the kingdom of God and his righteousness;
and he being obedient thereunto,
came to have an experience of the work thereof in himself,
which made his conversation sober and grave, as became the religious profession he made.
And it pleased God to endue him in a good measure,
with a spirit of wisdom and of a sound mind,
whereby he was enabled to stop the mouths of gainsayers, while he was yet but young.

It pleased God, who saw the sincerity and uprightness of his heart,
to call him to the work of the ministry, in or about the 25th year of his age,
which he entered into with great fear and humility.
He was slow of speech, and not hasty to deliver what was upon his mind,
and notwithstanding his voice was low, the savour of life attended his ministry,
which he was very careful to wait for, and thereby was made beautiful,
as well as serviceable and honourable in the church.
A godly care was constantly upon him, to adorn his doctrine,
by a conversation suitable thereto,
by which he obtained a good report in the parts where he dwelt,
among those who made not profession with us.
He travelled pretty much in the work and service of the ministry in this nation;
he was also in Ireland and Scotland,
and his service was well accepted among friends and others where he came.

This is further to be observed,
that when he was not employed in the service of the ministry,
he was very diligent and industrious in his outward business,
thereby endeavouring to maintain his family and bring up his children decently;
and it pleased the Lord so to bless his labours, that the end thereof was answered.
He was much concerned for his children`'s welfare, not only as to outward things,
but that they might be subject to the Lord his God,
often advising and exhorting them to fear the Lord in their young and tender years;
which advice, there is reason to hope and believe, hath had, and may have,
some good effect on them.

It pleased the Lord to visit him with the small-pox, about the first of the First month,
1718, which was very sore and hard upon him,
but he bore his affliction with true Christian patience,
and resignation to the will of God.
He was visited by divers friends, to whom he expressed,
that he was fully resigned to the will of God;
and that although he had undergone a great deal of bodily affliction during his illness,
yet it was little to him; for he had a being that was not shaken.
He further said, that if the Lord had any further service for him in this world,
he did not doubt but he was sufficient to raise him again;
but if it pleased God to remove him now, there was nothing stood in his way: but said,
he could have been glad to see his children settled in the world: nevertheless added,
"`Not my will, but the Lord`'s will be done.`"

His distemper increased upon him until the 12th of the same month,
when a little before he died, his son asked him how he did; to whom,
after a little pause, he answered, "`I am under grace, in the power of truth,
and that is my comfort;`"which was the last sentence he was heard to speak,
and so quietly departed this life, the 12th day of the First month, 1718,
at his dwelling house in Thetford, in the county of Norfolk, in the 48th year of his age,
having laboured in the ministry about twenty-two years,
and was buried in Friends`' usual burial-ground in the said town.
