== Chapter 2

[.chapter-synopsis]
* Richard Hubberthorn
* Edward Burrough
* John Audland
* Richard Farnsworth
* Mary Harris
* Josiah Coale
* Francis Howgill
* Thomas Loe
* Elizabeth Furly
* Margaret Molleson

RICHARD HUBBERTHORN was born in the north part of Lancashire;
his father was a yeoman of the county, and of good repute.
Richard was his only son, inclinable from his youth to religion, fearing the Lord,
and was faithful in all things according to the light and knowledge received.
His natural disposition was meek and lowly, and he loved peace among men,
and he sometimes preached among his sober and sincere companions.

When it pleased God to raise up his people in the north parts of England,
this same person was one among the first whose heart
the Lord touched with the sense of his power,
and he went through great afflictions,
through the dispensation of the grace and spirit of Christ Jesus,
until such time as the same power that killed did make alive; it wounded,
and also healed.
Being raised up by the holy spirit of the Lord,
he was made a minister of the everlasting gospel,
and accordingly went forth in the name and power of the Lord Jesus Christ,
and travelled to and fro in the nation for the space of nine years;
and thousands were as seals to the power and verity of his ministry,
and of his faithfulness among the churches of Christ.

He was a man of small stature, of a weak constitution of body, and though slow of speech,
yet he was very wise, and knew his season when to speak, and when to be silent.
When he spoke, it was with such discretion and plainness of words,
that reached perfectly the matter intended; and his speech being with grace,
and his ministry savory, God made him and his service a blessing to many.
He was not easily moved into grief by adversity, or into joy by prosperity;
a faithful contender for the living faith once delivered to the saints,
which stands in the power of God, and works by love.

He was, with many others of the people called Quakers,
taken from the Bull and Mouth meetinghouse in London, and had before Sir Richard Brown,
who with his own hands did violence to him, and then committed him to Newgate,
where being thronged up in a nasty prison, he was taken sick,
and in a few days grew weaker and weaker.

About two days before his decease, some of his dearest friends visiting him,
asked if any thing was on his mind; his answer was,
that there was no need to dispute matters, he knew the ground of his salvation,
and was satisfied forever in his peace with the Lord; and we know, said he,
one another well, and what each of us can say about these things.
During his sickness he expressed much love to friends;
and his mind was redeemed out of all visible things; and several times he would say,
'`The word of the Lord is with me.`'
And farther, '`That faith which has wrought my salvation I well know,
and have grounded satisfaction in it.`'

In the time of his sickness, he was kept feeding in retiredness within,
so that one might feel his strength in the Spirit, that kept him so still,
that it was not remembered that he groaned all the time of his sickness.
On the seventh day in the morning he asked for the mistress of the house, and said,
'`This night, or tomorrow, I shall depart hence.`'
The next morning he said to one sitting by him, '`Do not seek to hold me,
for it is too strait for me; and out of this straitness I must go,
for I am wound into largeness, and am to be lifted up on high, far above all.`'
So in the evening, being the first day of the week, and the 17th of the Sixth month,
1662, he finished his course, according to his own words,
and was gathered up to his Father.
He wrote many treatises, which are collected together in print.

[.asterism]
'''

EDWARD BURROUGH, born in the county of Westmoreland, about the year 1635,
of honest parents, was in his childhood ripe in knowledge,
and did far excel many of his years.
Grey hairs were upon him when but a youth,
and he was inclinable to the best things and the
nearest way of worship according to the scriptures,
accompanying the best men.
His natural disposition was bold and manly, dexterous and fervent,
and what he took in hand, he did with his might.
Loving, courteous, merciful, and easy to be entreated; he delighted in conference,
and reading of the holy scriptures.

When it pleased God to visit his people in the north of England,
this servant of Christ was early called, in the year 1652,
when about seventeen years of age.
He was sent forth by the Spirit of the Lord to preach the everlasting gospel, repentance,
conversion, salvation, and remission of sins,
in the name and power of the Lord Jesus Christ, the savior of mankind;
and was an able minister of the glad tidings of salvation.
In most parts of England, and through Ireland several times,
and in Scotland and Flanders, his ministry was made effectual by the mighty power of God,
in turning many thousands from darkness to light; for as he began early,
so he labored much in the heat of the day, breaking up rough places, and untilled ground,
and often walked as it were among briars and thorns, which scratched, pricked,
and tore with great opposition.
But he broke through them all, not regarding the opposition,
and the sufferings that he met with, for the good of souls.

His industry in the Lord`'s work was very great, he seldom having many hours repose,
making the Lord`'s work his whole business,
not taking so much liberty as to spend one week to himself, about any outward occasion,
in ten years; and it was his grief if any opportunity was missed in doing good.
He was a man of no great learning, which men so much admire,
yet he had the tongue of the learned,
having had experience of the work of God in many conditions,
so that he could speak a word, in due season,
to the understandings and consciences of all men with whom he had converse,
for his words administered grace to the hearer.

At the age of nineteen, in the year 1654, he came up to London,
and was one of the first who preached in that city,
and great opposition he met with there;
but God made his ministry effectual to the conversion of hundreds.
He continued about London very much, at times, between eight and nine years,
speaking of the things of the kingdom of God.
His heart was much drawn towards London, and he often said,
when sufferings came for the gospel`'s sake, '`I can freely go to that city,
(i. e. London,) and lay down my life for a testimony of that truth
which I have declared through the power and spirit of God.`'

In the year 1662, visiting friends in the city of Bristol, he took his leave,
and said to many, '`I am going up to the city of London,
to suffer among friends in that place.`'
A little after his return to the said city,
he was taken from a meeting of the people called Quakers,
at the Bull and Mouth meetinghouse, by soldiers under the command of Sir Richard Brown,
mayor, and committed to Newgate by the said mayor, not for evil doing,
but for testifying to the name of the Lord Jesus, and for the worship of God.
There he lay in prison with six or seven score friends more, upon the same account,
many of them being shut up among felons in nasty places;
and for lack of prison-room they grew weak, sickened, and died,
among whom this young man was one; his sickness increasing upon him daily,
though in much patience he was carried through all.

He was in prayer often, both day and night, saying at one time,
'`I have had a testimony of the Lord`'s love to me from my youth,
and my heart has been given up to do his will.
I have preached the gospel freely in this city,
and have often given up my life for the gospel`'s sake.
Lord, rip open my heart, and see if it be not right before you.`'
Another time he said, '`There lies no iniquity at my door;
but the presence of the Lord is with me, and his life I feel justifies me.`'
Afterwards he said to the Lord, '`You have loved me when I was in the womb,
and I have loved you from my cradle, and from no youth unto this day,
and have served you faithfully in my generation.`'

He spoke to friends that were about him to live in love and peace, and love one another;
and said, '`The Lord takes the righteous from the evil to come:`'
and prayed for his enemies and persecutors, and said, '`Lord,
forgive Richard Brown who imprisoned me.`'
Again he said, '`Though this body of clay must turn to dust, yet I have this testimony,
that I have served God in my generation; and that spirit which has lived, and acted,
and ruled in me, shall yet break forth in thousands.`'
In the morning before he departed, being sensible of his death, he said,
'`Now my soul and spirit is centered in its own being with God,
and this form of person must return from where it was taken.`'
And after a little season, he gave up the ghost, as a martyr for the word of God,
and testimony of Jesus.

He was born in 1635, began to preach 1652, and died 1662,
of whose written labors there is a volume printed,
containing almost nine hundred pages in folio.

[.asterism]
'''

HUMPHREY SMITH, of Little Cowrne, in the county of Hereford, formerly a public preacher,
was convinced of truth about the year 1655,
and came to be an able minister of the gospel of Christ, which he freely preached,
and turned many to righteousness,
and gave forth many warnings and exhortations to the people,
as may be seen at large in the printed collection of his works.
The Lord showed him in a vision, in the fifth month, 1660,
the destruction of the city of London by fire,
which was six years before it came to pass; and which vision he published before-hand,
as a warning to the people to repent; part whereof is as follows:

[.embedded-content-document.paper]
--

[.blurb]
=== Part of the vision of Humphrey Smith, which he saw concerning the burning of the city of London, in the fifth month, 1660, which was three years before his decease, and six years before it was fulfilled.

As for the city herself, and her suburbs, and all that belonged to her +++[+++I beheld]
a fire was kindled therein, but she knew not how, even in her goodly palaces,
and the kindling of it was in the foundation of her buildings.
There was none could quench it, neither was there any able;
and the burning thereof was exceedingly great, and burned inward in a hidden manner,
which cannot be expressed.
The fire consumed foundations which the city stood upon, and the tall buildings fell,
and it consumed all the lofty things therein,
and the fire searched out all the hidden places, and burned most in secret places,
but the consumption was exceedingly great wherewith it was consumed.

And as I passed through her streets, I beheld her state to be very miserable,
and very few were those that were left in her, who were but here and there one,
and they feared not the fire, neither did the burnings hurt them;
but they were (and walked) as mournful people, and the fire burned everywhere,
so that there was no escaping of it.
And thus she became a desolation, and as an astonishment;
for the burning was allowed of God for her chastisement,
and could not be quenched nor overcome.
There was none could stop the flaming; and the fire consumed all things,
both stone and timber; and burned under all things, and under all foundations;
and that which was lifted up above it fell down, and the fire consumed it.
The flaming continued, though the foundation was burnt up,
and all the lofty part brought down by the fire; yet there was much old stuff,
and part of broken desolate walls and buildings in the midst,
which the fire continued burning against; and that which was taken, as to make use of,
which yet escaped the fire, became useless in men`'s hands, as a thing of naught.
And the vision thereof remained in me, as a thing that was secretly showed me of the Lord.

And now let her wise men find out the matter, and her prudent men read, and her divines,
so called, interpret the vision, and let every one look to their own ways.

--

This, with much more that Humphrey Smith saw, was printed and published in the year 1660,
as a warning whereby people might stand in the day of trial,
and endure the hour of trouble.
See it at large in his printed vision in the year 1660.

Besides other things which the Lord revealed to him,
he had also a clear sight of his own sufferings, and death thereby.
For about the year 1662, traveling among friends about London,
he told some of them that he had a narrow path to pass through; and said several times,
before he was taken up, he saw he should be imprisoned,
and that it might cost him his life.
Taking leave of his friends, he set forward, in the will of God, westward;
and being in a meeting of the people called Quakers, at Alton in Hampshire,
he was taken from there, and had before the two lieutenants of the county,
who committed him to the stinking close prison of Winchester, where,
after a whole year`'s imprisonment, he fell sick.

In the time of his sickness he spoke many precious words to friends about him,
signifying that he was given up to the will of God, either in life or death.
And as he lay under great illness, he said,
'`My heart is filled with the power of God;`' and, '`It is good for a man,
at such a time as this, to have the Lord to be his friend.`'
Another time he said, '`Lord, you have sent me forth to do your will,
and I have been faithful unto you in my small measure, which you have committed unto me;
but if you will yet try me further, your will be done.`'
Also he said, '`I am the Lord`'s; let him do what he will.`'
And near the time of his departure, he prayed earnestly, saying, '`O Lord,
hear the inward sighs and groans of your oppressed,
and deliver my soul from the oppressor: hear me, O Lord, uphold and preserve me.
I know that my Redeemer lives: you are strong and mighty, O Lord.`'
He prayed that the Lord would deliver his people from their cruel oppressors;
and for those who had been convinced by him, that the Lord would be their teacher.

He lay quiet and still, sensible to the last moment, and died a prisoner for the truth,
in the common jail of Winchester, on the 4th of the Eighth month, in the year 1663.

[.asterism]
'''

JOHN AUDLAND was born in the county of Westmoreland, near Cam`'s-gill, and when a child,
he was ripe and quick of understanding.
About the eighteenth year of his age, the Lord inclined his heart towards himself,
and he delighted in reading the scriptures; and having a large knowledge and memory,
could discourse of things relating to religion, and became an eminent preacher,
not only among the most strict sort of professors, but sometimes also at chapels,
and public parishplaces of worship,
where great multitudes of people would flock after him.

About the twentieth year of his age he married Anne Newby, of Kendal,
belonging to the same religious meeting, afterwards the wife of Thomas Camm,
of Cam`'s-gill in Westmoreland.
This John Audland was one of those before mentioned,
who was convinced the first time that he heard George Fox at Firbank chapel,
and received him into his house.
Seeing the emptiness of his own high-flown notions and profession in religion,
he sat down in silence and astonishment, like Job, for many days;
and great was the work of the Lord upon him, being stripped of his earthly wisdom,
and in that state he mourned and wept bitterly, for he saw where he had been,
and that it was the Lord alone that could help him.

In great compassion the Lord revealed his saving health and arm of power,
by which he raised him up,
and filled him with wisdom and strength for the performance of that work +++[+++in which]
he would concern him, in gathering home the outcasts of Israel,
and the dispersed of Jacob; and sent him forth to preach redemption,
in the name of the Lord Jesus Christ, to the poor, and deliverance to the captive,
and the day of vengeance upon the wicked.
Leaving all his outward concerns; he went forth, and the dread, wisdom,
and majesty of the Lord was with him,
and many hundreds were turned to the Lord through him, as an instrument in God`'s hand.
Bristol, and several counties in the west of England,
were witnesses of the power and efficacy of his ministry, who with John Camm,
was of the first of those called Quakers who went to that city,
preaching Christ Jesus the light of the world.
He was often concerned in disputations, and the Lord furnished him with matter,
so that he stopped the mouths of gainsayers; his testimony was large and free,
affecting almost to all sorts of people, and he had a word in season to all conditions;
but notwithstanding he was young and strong,
yet that service much spent him several years before he died.

He had been several times in prison for his testimony`'s sake, as at Newcastle,
and at Bristol; and often in great perils, sore beatings, and cruel mockings,
both of the rabble, and also of the bitter spirited professors, but through all,
the Lord preserved him faithful.
He growing weak by a lingering distemper of a cough and consumption,
would often say in his sickness, '`Ah! those great meetings in the orchard at Bristol,
I may not forget.
I would so gladly have spread my net over all, and have gathered all,
that I forgot myself, never considering the inability of my body.
But it is well, my reward is with me, and I am content to give up and be with the Lord,
for that my soul values above all things.`'

Near his death, friends visiting him,
the Lord did wonderfully open his mouth in exhortation,
to their great refreshment and joy, as if he had been without sense of sickness.
He had a tender regard to his dear wife;`'But in this,`' said he,
'`my will is in true subjection, submitting to the will of the Lord,
whether life or death.`'
He desired his wife to give him up freely to the disposing hand of the Lord;
and the Lord strengthened her freely to recommend him into his hands,
which made him easy.

He was often, in the time of his sickness,
exceedingly filled with the high praises of God,
being overcome in the sense of God`'s love, joy, and everlasting peace.
When he grew weaker, he would be helped up upon his knees,
and upon his bed fervently supplicated the Lord, in the behalf of his whole heritage,
that they might be preserved in the truth, out of the evil of the world;
and that his gospel might spread, and be published,
to the gathering of all that appertain to Israel.
So was he sweetly taken away in the joy of the Lord, on the 22nd of the First month,
in the year 1664.

He was convinced in 1652, and died 1664, being aged about thirty-four years.

[.asterism]
'''

RICHARD FARNSWORTH, of Balby, in Yorkshire,
was also one of those whom the Lord raised up early in the work of the ministry.
He suffered about twelve months`' imprisonment at Banbury, in Oxfordshire,
in the year 1655, and many were turned to God by him.
He was mighty in discourses, and disputes with priests and professors,
and after much labor in the work of the ministry, and great sufferings and persecutions,
he at last finished his testimony in London.

A little space before his departure out of this life, sitting up in his bed,
he spoke in as much power and strength of spirit
as he had ever done at any time in his health,
these words following: '`Friends, God has been mightily with me,
and has stood by me at this time,
and his power and presence have encompassed me all along.
God has appeared for the owning of my testimony, and has broken in upon me as a flood,
and I am filled with his love more than I am able to express;
and God has really appeared for us.
If God himself had come down, and spoken as a man,
he could not have spoken more clearly to us than he has done,
by the many testimonies from heaven in his people.
Therefore I beseech you, friends, here of this city of London, whether I live or die,
be faithful to your testimony God has committed to you.`'

He died in the city of London, in the year 1666.

[.asterism]
'''

MARY HARRIS, of London, a maid young and beautiful,
went often with her relations to the meetings of the people called Quakers,
and had a love raised in her to the blessed truth,
and to them who held it in a pure conscience;
yet still lived in the customs and fashions of this evil world.
But the same love of God that had begotten tenderness in her heart, and love to truth,
followed her, and would not allow her to sit down in the world without trouble.
The Lord visited her with great weakness, so that she grew ill,
and fell into a consumption for about three years;
and being often visited by Josiah Coale, and put in mind to consider,
whether the hand of the Lord was not upon her for her unfaithfulness and disobedience,
she did consider the matter, and the Lord set it home upon her heart,
and she cried to him for mercy; and applied her heart to the Lord,
and his faithful messengers, saying, '`I have hardened my heart at many precious meetings,
when the Lord has smitten me; and I have seen plainly,
that the Lord would have gathered me; but I said in my heart, if I receive this,
if I give up to this, I must be a Quaker, and I cannot be a Quaker.
Then would I take my heart from attending upon the ministration of truth,
and then my heart became more hard.
'`What shall I do,`' said she,
'`that now I may receive the faithful sayings of the servants of the Lord?
Oh! that my heart were open; but it is shut and hard:
when shall I find mercy in this state?`'

She remained so for some time, and grew weaker and weaker in body;
and on the first day she took her bed she was much
under the righteous judgments of the Lord,
and felt his word in her heart as fire.
But the Lord in judgment remembered mercy, and having brought her very low,
he showed her the child`'s state, which she with great delight desired;
and indeed she became as a little child, fit for the kingdom of heaven.
Then did the Lord rend the veil, and showed her his glory,
and the preciousness of his pure truth, and the light shined out of darkness,
and in it she saw light, and received the knowledge of God;
and her heart was filled with joy and praises to the Lord, saying, '`I am well;
I feel no pain.
I am full; my cup runs over.
I am filled as it were with marrow and fatness.
I have seen his glory, and tasted his precious truth.
How pure is God`'s everlasting truth?
Nothing so pure; and they who indeed receive it, are made pure by it.
Praised be the Lord who has made me partaker of it, and placed me among his people.
Oh! blessed God, who has given me cause to sing aloud of your praise.`'
Many precious words she spoke to several persons who came to visit her,
to their several conditions, showing to some, who lived in pleasure, her hands, saying,
'`See here, the Lord has made these bones bare for my rebellion;
because I would not submit to his precious truth.
He has brought me to the dust, and I must lay down this body as a sacrifice.
Oh! do not you stand out, it will cost you dear, if ever you find mercy.`'
Then she would sing praises to the Lord, and exhorted all speedily to embrace truth,
and warned others professing truth, from following the fashions of the world,
crying to the Lord to wash her thoroughly.
Some would say to her, '`It may be you may recover.`'
'`No, no,`' she replied, '`I must lay down this body for my rebellion.
In my vain life, if any had said I should recover,
it would for a little time seem to refresh me;
and if they had said surely I could not live long, it would cast me down;
but now I long for death.
I must lay down this body; '`for,`' said she, '`when I received God`'s everlasting truth,
I received the sentence of death:`' and this she was positive in all along.

More sensible expressions she uttered, which I omit for brevity.
About half an hour before her departure, she was taken with a very great trembling,
and seemed to be somewhat troubled; when one near her said, '`What is the matter?
are you in any doubt concerning the truth of which you are made partaker?`'
She replied, '`No, no; that is God`'s pure everlasting truth, which the people of God,
called Quakers, are made partakers of, and for which they suffer; that is everlasting,
that is the true spirit, and their God is my God;
and although I see it not now as I have seen it, yet I bring in my testimony,
that is the truth that shall abide forever; that is pure,
and nothing that is defiled shall be sheltered under it.
That is the truth which enlightens every man coming into the world:
the little seed in me is become great, great, great!
Blessed be God who has placed me among his people, and I possess what they possess;
and when the faithful die as I die, my portion will be their portion; and my cup is full,
it runs over and over.`'
Then she breathed a little thicker for about the space of a quarter of an hour;
and so without groan or sigh, or the least motion, she shut her eyes and slept.
Glory to God forever.

She died at the widow Mary Forster`'s, in that called St. John`'s street, near Smithfield,
London, in the year 1668

[.asterism]
'''

JOSIAH COALE, born of a family of good repute among men, near the city of Bristol,
was convinced of God`'s everlasting truth,
through the powerful ministry of that servant of God, John Audland, about the year 1655.
The word of life pierced Josiah to the heart,
and wrought effectually to his salvation and redemption.
He walked for a time under deep judgment, and mournfully,
so that he became a gazing stock and wonder to his former acquaintance.
But God`'s arm was strong, and plucked up every evil plant, and purified him,
and made him fit for the Lord`'s use,
and an able minister of the everlasting gospel of Christ Jesus; an incessant laborer,
few more spent in God`'s service.
His soul seemed wholly bent to the renowning the name of Christ;
and the enemies of truth he ever accounted his enemies.

His declaration was to the ungodly like an axe, or hammer,
and a sword sharp and piercing,
being mostly attended with an eminent appearance of the dreadful power of the Lord,
to the cutting down many tall cedars, and making the strong oaks to bow;
but to the faithful and diligent, who minded the things of Christ more than their own,
oh! how soft and pleasant were the streams of immortal life that ran through him,
to the refreshing of those!
It was his life and joy to be speaking the word of the Lord, and not his own words;
and many thousands were living witnesses to the power,
virtue and efficacy of his ministry; but above all,
he was terrible to the sowers of strife, secret backbiters,
and such as rend the holy body, and separated from the life, love,
and fellowship of the blessed truth; who, in their own selfish spirits,
set themselves over their brethren, by feignedness and deceitful appearances,
to the destroying the simple-hearted.

In his conversation, his kindness was so mixed with seriousness,
and his familiarity with a stayed and exemplary behavior,
that he was an honor to the truth,
and therein a confirmer of his holy testimony and weaker brethren.

He was hardy, valiant, and fixed; not of those who shun the cross,
or sell their birth-right for a mess of pottage.
He baulked no danger for the sake of his blessed testimony,
which he bore faithfully in England, Holland, the Low Countries, and Barbados;
and had also sore travels among the heathen in America, as in Maryland, Virginia,
and New England, preaching the gospel of Christ among them.
He travelled on foot through the wilderness, from Virginia to New England,
in danger of wild beasts and venomous creatures, +++[+++enduring]
much hunger and cold, and weariness, and through bogs and waters,
often obliged to eat chestnuts for food when hungry,
as appears at large in the record of New England`'s persecution.

He was a good example, as well for his liberality as faithfulness;
for as the prosperity of God`'s truth was above all things most in his eye,
so he was always cautious of making the gospel chargeable to any; for,
having some estate of his own, he freely employed it in the Lord`'s service,
counting nothing too dear for the name and service of the Lord.

Thus having labored his natural strength away in this heavenly warfare,
for the promotion of the glorious truth of the Lord,
and for the advancement of its interest and dominion in the world,
for above twelve years together, he did, with perfect understanding,
and in an extraordinary enjoyment of the Lord`'s life, majesty, and presence,
to the refreshment of the beholders, cheerfully lay down his mortal body.

George Fox, visiting him upon his sick-bed,
queried whether he had any thing upon his mind to write to friends in England,
or beyond sea.
He said that he was clear of writing to them;
and that as the Lord by his power had carried him through England and other nations,
so he had nothing to write; but he desired his love to all friends.
One thing, he said, did lie upon him,
in that he understood Lodowick Muggleton (a most blasphemous
ranter) and his company would boast against him;
and understanding George Fox was preparing a book in answer to the said Muggleton,
desired he might put in a few words as his last testimony against Muggleton;
which George Fox desired him to prepare, and he would call for it as he came back.
He spoke them forth in the power of the Lord, as fresh as if he had ailed nothing,
and a friend took it in writing, which is as follows:

[.embedded-content-document.letter]
--

Forasmuch as I have been informed,
that Lodowick Muggleton has vaunted concerning my departure out of the body,
because of his pretended sentence of damnation given against me;
I am moved to leave this testimony concerning him, behind me:
That he is a son of darkness, and a coworker with the prince of the bottomless pit,
in which his inheritance shall be forever.
The judgment that I then declared against him, stands sealed by the Spirit of the Lord,
by which I then declared unto him,
That in the name of that God that spans the heavens with his span,
and measures the waters in the hollow of his hand, I bind you here on earth,
and you are bound in heaven; and in the chain under darkness,
to the judgment of the great day you shall be reserved;
and your faith and strength you boasted of I defy and trample under foot.
I do hereby further declare the said Lodowick Muggleton to be a false prophet,
in what he said to me at that time, namely,
That from henceforth I should always be in fear of damnation,
which should be a sign to me that I was damned; which fear I never was in since;
so that his sign given by himself did not follow his prophecy,
which sufficiently declares him to be a false prophet.

--

George Fox, when he came back again, found Josiah sitting by the fireside,
filled with the power of the Lord, and speaking to friends about him as follows: '`Well,
friends, be faithful to God, and seek nothing for self, or your own glory;
and if any thing wrong arise, judge it down by the power of the Lord God,
that so you may be clear in his sight, and answer his witness in all people;
then will you have the reward of life.
For my part, I have walked in faithfulness with the Lord,
and I have thus far finished my testimony, and have peace with the Lord,
and his majesty is with me, and his crown of life is upon me:
so mind my love to all friends.`'

Then he spoke to Stephen Crisp, saying, '`Dear heart, keep low in the holy fear of God;
that will be your crown.`'
Afterwards he said, '`A minister of Christ must walk as I have walked.`'
Then he desired George Fox to pray, that he might have an easy passage:
and friends seeing him begin to be heavy, desired him to go and lie down on the bed,
which he did; and friends sat about him, and held him,
and he was filled with the power of the Lord and seed of life, which was over all.
So in that he departed away, in the arms of friends, as he sat on the side of his bed,
and had a very easy passage into eternal life.

He died in London, aged thirty-five years and two months, in the year 1668.
He labored in the ministry twelve years, and wrote many treatises,
which are collected together in one volume.

[.asterism]
'''

FRANCIS HOWGILL, of Grayridge, in the county of Westmoreland,
an early minister of the gospel of Jesus Christ,
was convinced of the blessed truth by George Fox,
at that notable meeting at Firbank Chapel, in Westmoreland, in the year 1652.
He soon became a powerful minister, and preached Christ freely as he had received him.
He came to London with Edward Burrough early, to visit that city;
and travelled to Bristol and several parts of the nation,
and suffered imprisonment in Appleby jail, in the year 1652; and a nasty,
stinking prison it was.
He was set at liberty the latter end of the year,
and grew valiant and bold for the name of the Lord, traveling up and down on foot,
preaching the gospel.
He went to the steeple-houses, and to many places,
warning both priests and people of the day of the Lord that was coming upon them,
directing them to Christ Jesus their teacher and Savior.

He came also to London, on foot, with John Camm, to admonish Oliver Cromwell,
soon after he was made protector; and he went with Edward Burrough to Ireland,
and preached Christ under great sufferings there, until he and Edward Burrough aforesaid,
were banished by Henry Cromwell out of Ireland.
Afterwards he was imprisoned in London, in the year 1661,
at the time when the Fifth Monarchy people rose up in arms,
but was clear of that bloody act; and so was set at liberty,
and continued laboring up and down the nation, in the work of the Lord,
and turned many to God.
In the latter end of the Fifth month, in 1663,
he was sent for out of the market in Kendal, by the magistrates,
who tendered him the oath of allegiance,
and because for conscience-sake he could not take it, they sent him to Appleby jail;
and at the assizes, for refusing to take the oath,
sentence of premunire was given against him by the judge, in these words:
'`You are put out of the king`'s protection, and the benefit of the law;
your lands are confiscated to the king during your life,
and your goods and chattles forever; and you to be a prisoner during your life.`'

[.discourse-part]
F+++.+++ Howgill replied, '`A hard sentence for my obedience to the commands of Christ;
the Lord forgive you all.`'

[.discourse-part]
_Judge:_ Well, if you will yet be subject to the laws of the king,
the king will show you mercy.

[.discourse-part]
_Francis Howgill:_ The Lord has showed mercy unto me,
and I have done nothing against the king, or government, or any man, blessed be the Lord,
and herein stands my peace; for it is for Christ`'s sake I suffer,
and not for evil doing.

[.small-break]
'''

The court broke up, and many were sorry to see what was done against him;
but he signified how contented and glad he was,
that he had any thing to lose for the Lord`'s precious truth,
of which he had publicly borne testimony,
and that he was counted worthy to suffer for it.
He was kept a prisoner in Appleby jail four years and a half;
and his body being much spent in his public travels and labors in the gospel,
was not able to endure such close confinement,
though he bore his suffering in much patience and
cheerfulness until the time of his decease.

He was taken ill the 11th of the Eleventh month, 1668,
and though his departure drew nigh, yet was he kept in perfect understanding,
being often very fervent in prayer; and uttered many comfortable expressions,
to the refreshment of those about him.
Two days before his death, his wife and friends being present, he said, '`Friends,
as to matter of words you must not expect much from me,
neither is there any great need of it,
or to speak of matters of faith to you who are satisfied;
only that you remember my dear love to all Friends who enquire of me,
for I ever loved Friends well, and any other in whom truth appeared.
Truly God will own his people, as he has ever hitherto done,
and as we have daily witnessed;
for no sooner had they made that act against us for banishment,
to the great suffering of many good Friends,
but the Lord stirred up enemies against them, even three great nations,
whereby the violence of their hands was taken off.
I say again, God will own his people, even all those that are faithful; and as for me,
I am well, and content to die; I am not afraid at all of death.
Truly one thing was of late in my heart,
and that I intended to have written to George Fox and others,
even that which I have observed, which thing is, that this generation passes away,
when so many good and precious Friends, within these few years have been taken from us;
and therefore Friends had need to watch and be very faithful,
so that we may leave a good, and not a bad savor, to the next succeeding generation;
for you see that it is but a little time that any of us have to stay here.`'

Often he said in the time of his sickness, that he was content to die,
and that he was ready;
and praised God for the many sweet enjoyments and refreshments
he had received on that his prison-house bed where he lay,
freely forgiving all who had a hand in his restraint.
And he said, '`This was the place of my first imprisonment for the truth at this town;
and if it be the place of my laying down the body, I am content.`'

Several persons of note, inhabitants of Appleby, as the mayor and others,
went to visit him some of whom praying God might speak peace to his soul,
he sweetly replied, '`He has done it;`' and they all spoke well of him.
A few hours before his death, some being come to visit him,
he prayed fervently with many heavenly expressions,
that the Lord by his mighty power would preserve
them out of all such things as would spot and defile.
A little after, recovering some strength, he further said,
'`I have sought the way of the Lord from a child, and lived innocently, as among men;
and if any enquire after my latter end, let them know,
that I die in the faith that I lived in and suffered for.`'
These words he spoke, with some other words in prayer,
and sweetly finished his course in much peace with the Lord, in the Eleventh month, 1668.

He labored in the gospel sixteen years:
there is a volume of his works printed in about 740 pages in folio.

[.asterism]
'''

THOMAS LOE, of Oxfordshire, was a faithful servant and minister of Christ Jesus,
and converted many to truth, especially in Ireland,
where he travelled through great hardships.
His first going there was about the year 1657; Francis Howgill, Edward Burrough,
and others, having been there before him.
He had an excellent gift, sound and clear in the ministry, powerful in speech,
sharp and quick in his understanding; and many people flocked after him,
and received truth by his ministry in that nation;
and others he confirmed in the truth who were convinced before.
He was often publicly engaged with priests and opposers,
and the Lord made him a sharp instrument in his hand
to confound the adversaries of truth,
and the mouths of gainsayers were stopped.
His company was very desirable, being pleasant and sweet in conversation,
and sympathizing with his friends in affliction,
so that he could speak a word in due season.
He was several times a prisoner for the testimony of truth,
and went out of England several times to visit the nation of Ireland,
in which travels his natural strength was much impaired.
He also labored in the work of the ministry in London, being often there;
and was taken sick in that city,
expressing on his deathbed what exceeding encouragement
and glory he saw and felt of the Lord,
as follows:

'`Glory to you, O God, for your power is known.
God is the Lord.`'
Then speaking to William Penn, whom the Lord had made him instrumental to convince,
he said, '`Dear heart, bear your cross.
Stand faithful for God, and bear your testimony in your day and generation,
and God will give you an eternal crown of glory, that shall not be taken from you.
There is not another way that the holy men of old walked in, and it shall prosper.
God has brought immortality to light, and immortal life is felt: glory, glory,
for he is worthy.
My heart is full, what shall I say?
His love overcomes my heart; my cup runs over, my cup runs over.
Glory, glory to his name forever.
He is come, he has appeared, and will appear.
Friends, keep your testimony for God, live with him, and he will live with you.`'

Another time he said to some friends, '`Be not troubled,
the love of God overcomes my heart.`'
And again he spoke to George Whitehead, and other friends present, saying, '`George,
the Lord is good to me; this day he has covered me with his glory.
I am weak, but I am refreshed to see you: the Lord is good to me.`'
Another friend asked him, '`How are you, Thomas?`'
He answered, '`I am near leaving you, I think; but as well in my spirit as I can desire,
I bless the Lord; and I never saw more of the glory of God than I have done this day.`'
And then being expected to depart, the power of the Lord arose in him,
and he sung to the Lord, '`Glory, glory to you forever.`'
And so continued praising God for some time, which much affected the standers by.

He departed in peace with God, on the 5th of the Eighth month, in the year 1668,
at London.

[.asterism]
'''

ELIZABETH FURLY, daughter of John Furly of Colchester, in the county of Essex,
was a child that loved the Lord,
and also those who feared him.. Her delight was to hear truth preached,
and to be with such who excelled in virtue; she feared and hated a lie,
and lived and died in the faith which the people called Quakers profess.
She was taken sick at her father`'s house in Colchester, the 11th of the Twelfth month,
in the year 1669.

Two days before she died, being filled with the love of God,
she uttered many precious sayings concerning the Lord, and his mercies towards her;
praying to the Lord that she might be faithful to the end.
In the presence of several persons she spoke as follows: '`Whatever is not of yourself,
O Lord, purge out of me; yes, purge me thoroughly, leave no wicked word in me,
thrust away the power of darkness.
O Lord, make me able to praise you: let me not come into that way which is evil,
for if I do, I shall dishonor you and your truth.
I hope I shall never rebel against you more, but have full satisfaction in you,
and in your ways, and not in the evil one and his ways.
Wash me, O Lord, thoroughly,
let not an unadvised word come out of my mouth;`' with more to the same purport.
'`Show them, O Lord, the evil of their ways, that have done evilly,
and lay a burden upon their spirits, that they may leave it.
I feel no pain, the Lord is good to me; good is the will of the Lord.
Let your will be done in earth as it is done in heaven.
Everlasting kindness have you shown me,
and I hope I shall never forget it while I am in this world;`'
with more in admiration of the kindness and mercies of God,
and her desire to serve him while she lived.

To one of her brothers she said, '`Improve your time,
for you know not how soon you may be taken away;`'
warning him of the danger of an evil life,
and took him about the neck and kissed him, saying, '`Mind what I say,
O dear brother;`' and with many more words she exhorted him.
She also admonished her other brothers with tender expressions, saying, '`Love the Lord,
brothers, love good men: hate the devil; but oh, love the Lord,
and then you will be a joy to your father and mother.`'
When she saw one of her sisters weep, she said, '`Weep not for me, I am very well.
All serve the Lord, that he may be your portion.
In my Father`'s house there is bread enough, there is fulness, lack of nothing; yes,
there is fulness of bread, durable riches and honor.
I desire never to forget the Lord.`'

As she walked in innocency, so she died in peace, and entered into glory,
the 16th day of the Twelfth month, in the year 1669, aged thirteen years and five weeks.

[.asterism]
'''

MARGARET MOLLESON, wife of Gilbert Molleson of the city of Aberdeen in Scotland,
was in her youth an enquirer after the best people,
and joined herself in worship with the most strict
and refined in profession then in that city.
But it having pleased God,
who beheld her hungering desires after himself and his righteousness,
to send some of his faithful witnesses and servants called Quakers,
from the nation of England into the north of Scotland,
who preached the everlasting gospel;
she was one of the first in those parts that received the same.

Coming to taste of the unspeakable love of God, she delighted often to retire therein,
out of the cumbering cares of her family and business.
And although her love to her husband, and cares of her many children, were great,
yet her greatest delight and care was,
to draw nearer and nearer to the true and living God,
the chiefest beloved of her travailing soul.
For that end she often resorted to the public meetings of the people called Quakers,
as well as being frequently in private with the Lord in prayer;
which gave her husband (who was not one called a Quaker) cause to say,
that her knees were worn with kneeling at prayer.

For about four months before her departure hence, he usually found her,
when he awaked in the night-time, in meditation; and after her departure,
he also said before several people coming to visit him,
that he had lost a true Mary and a Martha, none knowing how great his loss was,
and he could not but much lament it.

On the 16th of the Tenth month, 1669, in the morning, she was taken suddenly sick,
and the same day in the evening died,
having been for some time before made sensible of her end; yet her physician,
not supposing that she had been so dangerous, said to her, she needed not fear,
his life for hers; to which she answered, '`Fear, I have no cause;
but you will see you are mistaken.`'
Many relations and neighbors being in her chamber, were in great sorrow;
among whom was a great professor, and an old acquaintance of hers,
who desired those about her to pray for her; which she hearing,
when others thought she had been dying, answered, '`My Advocate is with the Father,
and my peace is made.
I am feeding at a table none of you perceive.`'

Some lamenting much her being like to be taken away from her nine children,
who were all about her bed, she said, '`As many of them as shall truly fear the Lord,
and follow him, shall be provided for:`' which has been since truly fulfilled.
Fixing her eyes on her son Gilbert, who was then about ten years of age,
she said in a heavenly frame of mind, '`Truth is precious, cleave to it.`'
She observing the people in her chamber much lamenting, said to them, '`Settle yourselves,
and be stayed in your minds, for you are now to see the last.`'
Being to reap eternally the fruit of her great and spiritual labors,
she had true cause given her then to declare before those present:
'`Now interruption is to cease,
and my eternal joy is already begun;`' the certain earnest of which she received,
and +++[+++had]
often preferred before all other enjoyments.

Her life and conduct, as well as her latter end,
were such as gained her not only great love and esteem from friends of truth,
but also from others of her acquaintance.
She departed hence on the 16th of the Tenth month, in the year 1669,
about the forty-second year of her age, at Aberdeen, in the kingdom of Scotland.
