== Chapter 3

[.chapter-synopsis]
* Jane Whitehead
* William Bayley
* Joseph Briggins
* Robert Jeckel
* William Sixsmith
* Francis Patchet
* Christopher Bacon
* William Coale
* Sarah Beck
* John Matern
* Giles Barnardiston
* Alice Curwen
* Mary Samm
* Mordecai Hearn
* Sarah Camm
* Joseph Featherstone
* Judith Fell
* Jonah Lawson
* Elizabeth Braithwait

JANE WHITEHEAD was the wife of Thomas Whitehead, of North Cadbury in Somersetshire.
Her maiden name was Jane Vaugh, and she was born in Westmoreland,
her relations living about Hutton in the same county;
whom she left in obedience to the Lord, and travelled in his service,
and bore witness against the false ways and worships of the world;
and for the sake of her testimony endured much persecution.

In the year 1655, coming to Banbury in Oxfordshire,
to visit her dear friend Anne Audland, then a prisoner for the truth, she,
for bearing witness thereto, and against their cruelty and wickedness,
was also taken and committed to prison, and lay there five weeks.
Not long after, coming again to the said town,
the magistrates tendered her the oath of abjuration;
which she refusing for Christ`'s sake,
who says "`Swear not at all,`" was imprisoned twelve months in a low, wet, nasty place,
in the winter season, that sometimes she would be over shoes in water;
which she endured with much patience.

In the Fourth month, 1662, she was again imprisoned at Banbury,
for worshipping God at a meeting of the people called Quakers,
where she lay in the same nasty prison three months.
These things she suffered before she was married.
Afterwards Thomas Whitehead, aforesaid, took her to be his wife,
by whom she had five children that she left behind her.

At Ivelchester, she endured five months imprisonment, with a young child at her breast,
in a cold winter,
for speaking the words of truth and soberness to the priests of North Cadbury.
But the Lord upheld her by the word of his power,
in the manifold exercises and tribulations which she passed through,
too tedious here to relate.
Those abuses which she endured brought her tender body into weakness,
which attended her several years before she died; and,
under great exercises and weakness of body,
she acknowledged that the Lord was wonderfully good to her.
She often said that the Lord had broken in upon her,
and with his heavenly presence did fill her, to the comfort of her soul: and said,
'`O that the Lord may never take his presence from me.`'
To the last she was kept sensible, and declared that she had the testimony of God`'s love,
and that it would be well with her,
and that she had no desire to live any longer in this world.
She charged her children to be obedient to their father, and that they should mind truth,
and then the blessing of the Lord would be with them.

The morning before she died, being sensible her death was at hand,
she told a Friend that she was going to her long home; and soon after departed this life,
in the love and peace of God, on the 28th day of the Seventh month, in the year 1674.

[.asterism]
'''

WILLIAM BAYLEY, who was a Baptist teacher at Poole, was convinced of the blessed truth,
as professed by the people called Quakers, in the year 1655,
and travelled up and down in many places in the service of the Lord.
His gift in the ministry, both as to matter and utterance, was plain and prevalent;
he divided the word aright, for he fed the fat with judgment;
and yet he had milk for babes, and stronger meat for those of riper age.
He was mighty in the holy Scriptures,
being well acquainted both with the history and mystery thereof,
through the assistance of the Holy Spirit, which gave him a true understanding in both.
It was given him, not only to believe and preach the word of faith,
but also to suffer for the same, sometimes by cruel persecutions;
being thrown down and dragged upon the ground by the hair of his head;
and his mouth and jaws endeavored to be rent and broken asunder,
that the ground whereon he lay was smeared with blood.
Yet as if this butchering of him had not been enough to make him a sacrifice,
a heavy gross-bodied persecutor stamped upon his breast with his feet,
endeavoring to beat the breath out of his body;
and when this persecutor had done his pleasure, he commanded the jailor to take him away,
and put him in some nasty hole for his entertainment and cure.

For the maintenance of his family,
he several times adventured his life upon the mighty waters, being master of a ship;
and many beyond the seas were partakers of his labors, and comforted by his ministry.
In his return home from visiting friends in Barbados, he fell sick;
and a little before his departure,
desiring to be remembered to his dear wife and children, he said, '`Well,
shall I lay down my head in peace upon the waters?
God is the God of the whole universe, and though my body sink,
I shall swim a-top of the waters.`'
Remembering his love to Friends in general, and some by name, he immediately sung,
being filled with the power of God,
'`The creating word of the Lord endures forever;`' and spoke to them who sat by,
and took several by the hand, exhorting them to fear God, and not to fear death.
He said, '`Friends at London would have been glad to see my face.
Tell them, I go to my Father and to their Father; to my God, and to their God.
Remember my love to my wife; she will be a sorrowful widow;
but let her not mourn in sorrow, for it is well with me.`'

He then took his leave of the Friends on board, saying, '`I see not one of you,
but wish you all well.`'
A Friend of New England asked him how it was with him: he said, '`I am perfectly well:
and mind my love to Friends in Rhode Island, and New England, and to Friends in Barbados.
I went freely in tender love to them.`'
He uttered more sensible words; and about half an hour past four in the morning,
he departed this life, as if he had gone to sleep, being on 1st day of the Fourth month,
in the year 1675, on board the Samuel of London,
in the latitude of 46 degrees and 36 minutes.

[.asterism]
'''

Concerning a child about thirteen years old
JOSEPH BRIGGINS, son of William Briggins of Bartholomew Close, in London,
having been a dutiful child to his parents, and ready to receive instruction,
was taken sick the 20th of the fourth month.
Being, as it was thought, very near death; after he had lain silent for about an hour,
he began to appear full of joy and pleasantness, saying, '`I shall praise the Lord,
for he is only to be praised;`' with many more words which they could not remember.
He said, in admiration, '`Oh!
I have never heard of any other God but you, my holy One; I have heard of you,
but now I see you in glory.`'
Calling for his father and mother, he said, '`Father, father, oh! father,
oh! pure and glorious is my Savior who has appeared, and has taken me into his kingdom.
Oh! my eye has seen his glory.`'
Then he prayed, '`You most glorious God,
great and wonderful things are brought to pass by your own pure holy power,
by which you have revealed your Son.
Oh! my King, let all people fear and stand in awe of your power,
by which you have gathered many out of their sinful ways, into pure obedience to you.
You have given us a living knowledge.
Oh! pure, glorious, and holy God, let your life reach unto all my dear friends,
and keep them that know you sure and stedfast upon your holy foundation, Christ Jesus,
my king, whose appearance is very glorious at this day,
and of his government no end is to be, but thousands of thousands, millions of thousands,
shall come to see, and be made partakers of his glorious, bright, shining day.`'

Another time he said, '`There are many ways and baptisms in the world; but oh! you pure,
holy, holy One, we have known your spiritual baptism into Christ Jesus my Lord,
by whom the living water we have known and felt.
Oh! it is indeed exceedingly pure, by which we have been washed from all our sins.
Oh! my King, you were slain, and by the virtue of your pure blood we have this given.
Oh! that all may wait continually upon you,
that they may be kept from all the deceitful ways of the world.`'
To those standing by he said, '`Mind and serve the Lord in your day,
for the holy truth received by you is the way in
which you must wait and obey;`' with much more.
Then he lay silent a little while; but again said,
'`The Lord has taken me into his kingdom,
he has discovered the fresh springs of his love to my soul.
All that know the Lord be obedient to his power,
and he will discover himself more to you, and you shall know more.
Thousands, thousands, millions, shall the Lord call.`'
With more words, after some time of silence.

Some who knew him very well, wondered to hear him speak as he did,
and said they had never heard such words come from him before.
He replied, '`The Lord has fully made known that to my soul,
which I had some feeling of before.`'
The next day he was very earnest in prayer softly to himself,
but the following words were heard: '`Oh! let all that know the pure truth,
come and receive it, says my soul.`'
He also sung of the olive tree, and of the fruit thereof, which he fed on,
and of his refreshment thereby.
He was asked what he meant by the olive tree.
He said, '`The tree of life.`'
Many more sayings he uttered before he departed to his everlasting rest,
which was on the 3rd day of the Fifth month, in the year 1675,
in the thirteenth day of his sickness.

[.asterism]
'''

ROBERT JECKEL, of Newcastle-upon-Tyne, in the county of Northumberland,
having a desire to visit George Fox, who was then at Swarthmore, set out on his journey,
in company with several friends,
but began to be sick the same day that he went from home,
and was ill at several places by the way; but still pressed forward,
and would not be satisfied to stay short of Swarthmore,
where he came the 2nd of the Fifth month, 1676,
and went to bed presently after he came in, and lay sick there nine days.
During his illness, these following words, with many more, were spoken by him:
'`No separation like unto this; soul separated from the body,
the spirit returning to God that gave it, and the body to the earth, from which it came.
Great has the lovingkindness of the Lord been to me, and not to me only,
but to all my dear friends who are faithful unto death.
I have always been faithful to the truth, as to what was manifested;
for God has loved me from a child.`'

He added, spreading out his hands, '`O! the blessed precious truth is above all the world,
and this is my living testimony I have to bear for the Lord, and his truth;
for always I loved truth, and preferred it before all the world; for truth is precious;
and to be valued before all things.
Therefore, oh! my dear friends! prize this precious truth, for it abides forever;
let nothing divert your minds from that service of truth you have,
for as that is kept to, truth answers truth in every heart.
As to the principle of truth, it will reign over all.
Though strange things may happen in this nation,
yet the Lord will crown his blessed truth, and his glory is over all.
Therefore, all my dear friends,
be faithful to that manifestation in your own particulars,
for a profession will stand none in stead,
unless they live in the life and power of truth.`'
Another time he said, '`Though I was persuaded to stay by the way, being indisposed,
before I came to this place, yet this was the place where I would have been,
and the place where I should be, whether I live or die.`'

George Fox visiting him,
exhorted him to offer up his soul and spirit to the
Lord who gives breath and life to all,
and he takes it again; and he lifted up his hands and said, '`The Lord is worthy of it,
and I have done it.`'
George Fox then asked him if he could say, '`Your will, O God, be done on earth,
as it is done in heaven;`' and he lifted up his hands and eyes, and cheerfully said,
he did it.
His mouth was often filled with praises to the Lord, exhorting those about him, saying,
'`Dear friends, dwell in love and unity together, and keep out of jars,
strife and contention, and be sure to continue faithful to the end,
and be not weary in well-doing; for this is a good testimony,
they that continue faithful to the end shall be saved.`'

He said, '`If any bad spirits speak evil of me when I am gone,
you are living witnesses`' (speaking to two friends present,
who were his neighbors)'`that I am an innocent man, and the Lord has cleared me,
and I lay down my head in peace.
As to my wife, I give her freely up to the Lord; for she loves the Lord,
and he will love her.
I have often told my dear wife, as
to what we have in outward things, it was the Lord`'s first before it was ours,
and in that I desire she may serve the truth to the end of her days.
And now, my dear friends, I commit you all to the Lord,
to be preserved and kept in his everlasting power, and bid you all everlastingly, yes,
everlastingly, farewell.
All is done, and to the Lord I leave you all; I commit you all, farewell.`'
Afterwards he said, '`Let us go hence in peace, for I shall go hence,
and be no more seen in mutability.`'

About two hours before he died, George Fox took him by the hand,
and asked him if he was satisfied of his seeing him.
He lifted up his hands, and with a gladness of heart, and smilingly,
praised the Lord and said that his comfort flowed in as a flood.
George Fox asked him what he said; and he spoke those words over again.
And in much patience the Lord did keep him;
and he was in perfect sense and memory all the time of his weakness, often saying,
'`Dear friends give me up, and weep not for me, but be willing to bear a part with me,
for I am content with the Lord`'s doings.`'
He often said that he had no pain; but went away by little and little,
lifting up his hands while he had strength, praising the Lord,
and made a comfortable end, on the 11th of the Fifth month, in the year 1676.

[.asterism]
'''

WILLIAM SIXSMITH, of Warrington in the county of Lancaster,
a young man about twenty-one years of age,
was in time of health a pattern of piety and good example.
When he was taken sick, he freely resigned up himself into the hand of the Lord,
refusing a physician, saying,
'`I am satisfied with the Lord`'s love;`' and that he knew his Redeemer lived, who,
if he pleased, was able to restore him to health, and if not, he was content.
In the time of his sickness he was very patient and quiet, often praising God.
A little before his death, calling his father,
with an innocent look he gave him his right hand, saying,
'`I desire you will not be troubled.`'
And so laid down his life in peace, the 24th of the Seventh month, in the year 1677.

[.asterism]
'''

FRANCIS PATCHET, of Scotforth, in the county of Lancaster,
was a prisoner for his testimony against tithes:
the priest who prosecuted him removed him up to the Fleet prison in London,
where he died a prisoner.

In the time of his sickness he prayed, '`Lord God everlasting,
glory and honor forever be given to your name.
You have made way for your redeemed as in ancient days,
when you made the sea dry land for your people Israel to go through.
O glory and honor forever be unto your name, who are unchangeable in all your ways.
You made man in your own image, but he lost it through disobedience.
O Lord, in your unspeakable love you sent your only Son Christ Jesus to redeem us again.
Oh! everlasting praises to your name forever;`' with many other words.
Again he said, '`There is no God like our God;
he has given his Son a light into the world, and his salvation to the ends of the earth.
Oh! this blessed day wherein truth has appeared: Oh!
England`'s glory.
Friends, obey the truth, love the truth, buy the truth, and sell it not: Oh!
Christ Jesus, the way, the truth, and the life.`'

Again he said, '`Glorious is the house of God, a house of holiness, a pure house,
a house of love, and her gates praise.
Our God is a consuming fire; he consumes all that is bad, all impurity, all uncleanness,
all that is unholy, all that is wrong.`'
Thus he went on praising God for sending his Son for the redemption of man,
and spoke much of the Lord`'s making a way for his people in the nation of England.
At another time he said, '`My strength fails me.`'
On which, one by him replied, '`I hope the Lord does not fail you:`' he answered,
'`Through mercy the Lord never failed me;`' with more
concerning the Lord`'s building of Zion, etc.
Another time he said, speaking of the Lord, '`Oh! your precious light,
in which I see your glory: what will become of them that despise your light?`'
Again, '`The false prophet and the hireling the Lord will cut down,
and all that resist his blessed work which he has begun in this
nation of England;`' with more words of exhortation to friends,
and praises to God; and so finished his testimony, a prisoner for truth,
the 2nd of the Tenth month, in the year 1677.

[.asterism]
'''

CHRISTOPHER BACON, of Polling-hill, in Somersetshire,
was formerly a soldier in the king`'s army.
About the year 1656, some of the Lord`'s servants, called Quakers,
coming into that country to preach the gospel, he went to one of the meetings,
not to receive good, but rather to scoff and deride.
But, through the Lord`'s mercy, he was reached in his conscience,
and received the blessed truth in the love of it;
and afterwards received a dispensation of the gospel of Christ to preach,
and was a diligent laborer in the work of the ministry.
He travelled to London, and into Ireland and Wales,
and many parts of the nation of England, and several were convinced of the truth by him.

In the year 1678, he came into the county of Cornwall, and there fell sick,
being weak of body before, but had a good meeting of Friends in the town.
Upon his sick bed he desired a Friend by him to write comfortably to his wife,
if the Lord should take him away, and advise her,
that she bring up her children in the fear and counsel of the Lord;
and it was his fervent desire that his wife might be kept to truth; and +++[+++likewise]
for all friends.
And said, '`Since it is my lot,
after many great labors and travels for the service of truth,
to come here and lay down my body, I am well satisfied in God`'s will and pleasure,
and am at this time free and clear in my mind, willing to be with God.`'
Then making some pause, he said, '`O! friends, keep in mind your latter end,
and that will make you draw nigh to the Lord, and seek after him.`'

He further said, '`Friends,
take heed that you lose not a heavenly inheritance for an earthly.`'
The day before he died, being the First-day of the week,
he spoke to friends as they were going to meeting, minding his dear love to friends,
and said, '`The Lord`'s presence be among you,
for his presence has attended me in all my labors, travels, sufferings, and exercises,
for his name`'s sake.`'
His end drawing near, and his body weak,
he continued to the last moment in sweet harmony, lifting up his hands,
and in much quietness and peace he gave up the ghost the 29th of the Tenth month,
in the year 1678, aged about fifty-five years.

[.asterism]
'''

WILLIAM COALE, of Maryland, in America,
was convinced of the blessed truth about the year 1657,
and was a man of an innocent and tender spirit, of true judgment,
and stood in the power and love of God against unrighteousness and false liberty;
and for true liberty in Christ Jesus, and for holiness, peace, and unity in the church.
He freely and tenderly preached the cross of Christ,
and was living and weighty in his testimony.
He suffered imprisonment in Jamestown prison, in Virginia, with George Wilson,
a Friend of Old England, who travelled into America to preach the gospel,
whom the magistrates of that town persecuted to death,
after they had cruelly beaten and whipped him, and kept him long in iron chains;
and the said William Coale was also much decayed in his body by that cruel imprisonment,
and never recovered it.

His visit to friends in Virginia was very serviceable to many,
some were turned to the Lord through his ministry,
and many were established in the blessed truth.
In the time of his sickness he was cheerful in spirit,
freely given up to the will of God, as a living man prepared to die, saying,
'`The living presence of the Lord is with me;`' with many words more
of the great satisfaction he had from the Lord concerning his peace,
saying, '`I bless the Lord, I have finished my course,
and I have nothing to do but to wait on the Lord to die.`'
So in a short time he departed very peaceably and quietly, about the year 1678.

[.asterism]
'''

SARAH BECK, wife of John Beck, of Dockra, in the county of Westmoreland,
was an innocent woman, and one that feared the Lord.
Even from a child, her heart was set to seek him and the prosperity of his truth,
and the welfare of all people; and her chiefest care was to serve and obey the Lord.
Being sick near unto death, it was thought she was dead, but recovering a little,
she said, '`I was well, I was very well, if I had gone.`'
And after that, she praised and magnified the name of God,
which much affected the hearts of many who were with her in her sickness.
She said, '`O Lord, you have satisfied my soul.
I desired that I might praise you, and I am satisfied: honor,
glory and hallelujahs be to you, you God of my life.
I feel sweet peace and great joy: oh! the joy that is laid up for the righteous: oh!
Who would not fear the Lord?
Who would not be faithful?`'

Taking her leave of her husband and her friends, one by one, she said,
with a cheerful countenance, '`I am near going; this sweet end will come;
it makes my heart glad when I remember my end;
it will be the happiest hour that ever came to me.`'
Some observing her to be in great pain and very sick, said one to another,
'`It is very hard;`' she answered, '`No, it is very easy,
for the Lord sweetens it.. Oh! you glorious God, you have satisfied my soul.
I am filled with your pure presence;`' with these words,
'`that I may praise you while I have breath and being!`' as indeed she did,
for even at the very hour of death she said,
'`Call in the family;`' and holding her husband by the hand,
made sweet melody in her heart, saying, '`Dear God,
what shall I render to you for this evening sacrifice?`'
Thus she went on praising God till her natural strength failed,
and then turned her face to the pillow and said no more;
but died as if she had fallen asleep, being the thirteenth of the Sixth month,
in the year 1679.

[.asterism]
'''

JOHN MATERN was a German, and educated in the learning of the schools,
intending to be a priest.
But it pleased God to visit him, even in his own country, in the year 1674,
and his wife`'s father, Christopher Proham, who was a priest, was convinced also,
and was a faithful friend, and died in peace with God in England,
where they and their families came to live.

John Matern labored about six years in great integrity,
instructing youth in the knowledge of the tongues,
and endeavored to bring them to the fear of the Lord, and knowledge of his blessed truth.
He lay sick about a week, and about four hours before he departed, at his desire,
they called the youth of the school into his bed-chamber,
where he had a meeting with the family, and he was filled with divine praises,
magnifying the great power of God; and his prayer was fervent,
that the Lord would carry on the good work begun among the children,
and prosper his truth daily everywhere.
He exhorted the children, as they sat around about him,
to be faithful in their measures to a little, and more should be added.
He gave thanks to God for many particular mercies, but more especially,
that he had received the knowledge of the everlasting truth,
and had walked uprightly therein; for which, he declared at that time,
that he had the testimony of a good conscience,
and was entering into eternal rest with the Lord.

He died in rest and peace on the 1st of the Seventh month, in the year 1680.

[.asterism]
'''

GILES BARNARDISTON, of Clare, in the county of Suffolk,
came of a family of great account in the world,
and had his education accordingly at the university,
and his natural parts were answerable thereto; but when he received the truth,
he saw not only the emptiness of those things, but of their way of worship also; and,
like Moses, chose rather to join with the poor suffering people of God, called Quakers,
than to enjoy the pleasures of sin for a season.
After he was converted, it pleased God to commit a dispensation of the gospel unto him,
and He laid a necessity upon him to preach the same;
which he faithfully performed to the day of his death,
not regarding the tenderness of his body so much, as to fulfill the will of God.

When he was about to enter upon a hard journey, or otherwise exercised, he would say,
'`That is but for a short time, and we shall have done in this world;
and I desire that I may be faithful to the end,
that I may enjoy that of the hand of the Lord, that I received the truth for.
If it had not been to obtain peace of conscience while I am in this world,
and hopes of everlasting rest with God in the world to come,
I would never have left the glory and pleasure of this world, which I had,
and might have had, a share of, with them that are in it.
Neither would I now leave my house and home, where I have a loving wife,
with all that a man, fearing God, needs to desire, if it was not to obey the Lord,
and to make known his truth unto others, that so they may come to be saved.
For this cause do I forsake father and mother, wife and estate;
and whosoever thinks otherwise of me,
with the rest of my faithful brethren whom God has called into his work,
to declare his name and truth among the sons of men, they are all mistaken of us,
and I would they knew us better.`'
He continued faithful in the Lord`'s work to the end; and he was blessed in his labor,
for he turned many to righteousness.

It pleased the Lord to visit him with sickness, in his return from London to Chelmsford,
and his sickness was short; in which time he gave testimony to the goodness of God,
and said that the Lord was his portion, and that he was freely given up to die,
which was gain to him.
And on the 11th of the Eleventh month; in the year 1680, he departed in peace.

[.asterism]
'''

ALICE CURWEN, of Lancashire, with her husband Thomas Curwen,
travelled in the work of the ministry in various parts of America, such as New England,
New York, Long Island, Rhode Island, and Barbados; and after many long journeys,
and much service, returned home about the Third month, 1677.

The said Alice, being upon her dying bed,
was asked if she thought she should recover of her sickness; to which she answered,
'`I do not know what the Lord has to do; but I am freely given up to his will,
whether it be life or death; I am as clear as a child.`'
Another time, complaining of the unfaithfulness of some professing truth, she said,
'`But those who are faithful, the Lord will preserve them,
though they may meet with many trials and besetments, both inwardly and outwardly.`'
And again, '`All stand faithful for the Lord in their day,
and none need be afraid of death, for it will be easy to them as it is to me.`'

She often, in the time of her sickness, made melody to God in her heart, and said,
'`Oh! my heavenly Father, how have you filled my cup, and made it to overflow;
for I can do no less than bless and praise your eternal name.`'
She often desired God`'s will might be done, whether it was life or death; '`For,`'
said she, '`to me to live is Christ, and to die is gain.`'
She exhorted friends to be diligent, and to know life and virtue in themselves;
'`For,`' said she, '`the time will come that words shall cease,
and life shall more arise;`' and said, if she lived she must declare it; and if she died,
she must leave it as a testimony for the Lord.
Toward the latter end of the last night she lived, her pain was great,
and she spoke to friends about her, saying, '`Pray to the Lord for me,
that he lay no more upon me than I am able to bear; that I may not offend this good God.`'
And immediately she prayed to the Lord, and had a little ease,
and lay still as if she had been in a slumber, and so grew weaker,
and was sweetly carried through to the end.
She died in London in the year 1680.

[.asterism]
'''

MARY SAMM, daughter of John Samm, of Bedfordshire,
and grand-daughter of William Dewsbury, of Warwick, aged about twelve years,
being taken sick, and her aunt finding her under a concern of mind, asked her,
why she walked so often alone in the garden, when she was well,
for she would many times be weeping alone.
She replied, '`Dear aunt,
I am troubled for lack of a full assurance of my eternal salvation.
Not any knows my exercise but the Lord alone,
what I have gone through since I came to Warwick.
It was begun before I came, but it was but a little.
This was my trouble, I thought I should not live long, and that if I did die,
I did not know where my soul should go;
but I hope the Lord will give me satisfaction before I die.
It is but hope, and though but hope, yet for this my soul shall praise his name forever.`'

The next day, having more assurance of her future happiness,
and some friends coming into her chamber, she said,
'`I have been twice in my days nigh to death,
but the Lord in his tender mercy prolonged my days,
that I might seek his face in the light of Christ,
and come to be acquainted with him before I go hence.`'
Also she said, '`If this distemper do not abate, I must die;
but my soul shall go to eternal joy;
eternal and everlasting life and peace with my God forever.`'
At another time, '`They that live longest, endure the greatest sorrow; therefore, O Lord,
if it be your will, take me to yourself, that my soul may rest in peace with you.`'
With many more good words.

The day following she desired all to go forth of the room.
After a considerable time, her mother and grandfather went in again, when she said,
'`I have now received full satisfaction of my eternal salvation.
It is now done, it is now done.`'
And after saying something to her mother, she said, '`I am very willing to die,
that the Lord may glorify his name this day, in his will being done with me:
often praying to the Lord, to lay no more upon her than she was able to bear, saying,
'`Help me, O my God, that I may praise your holy name forever.`'
Her grandfather advising her to stillness, she answered, '`Dear grandfather, I shall die,
and I cannot but praise the name of the Lord while I have a being.
I do not know how to do to praise him enough.`'
Her grandfather inquiring how she did, she replied, '`I have had no rest to-night,
nor today.
I did not know but I should have died this night, but very hardly I tugged through it;
but I shall die today, and a grave shall be made, and my body put into a hole,
and my soul shall go into heavenly joy, and into everlasting peace forevermore.`'
After more expressions, her aunt asked her if she thought she was upon her deathbed:
she replied, '`Yes, yes, I am upon my deathbed.
I shall die today, and I am very willing to die,
because I know it is better for me to die than to live.`'

After some time, and other expressions, she inquired the time of the day,
which being told, she said, '`I thought it was more.
I will see if I can have a little rest and sleep, before I die.`'
So she lay still, and had a sweet sleep, and awaked without complaint;
and then in a quiet, peaceable frame of spirit laid down her head the same day in peace,
being the 9th of the Second month, in the year 1680, in the twelfth year of her age.

[.asterism]
'''

MORDECAI HEARN was a young man whom the Lord in his mercy reached to in his tender years,
and called by his holy Spirit in his heart, and he hearkened to the call of the Lord,
so that he became a prepared vessel, by the Lord, for his use and service.
God opened his heart, and mouth also, sometimes, to declare of his goodness and mercy,
and speak to the praise of his grace in the congregations of his people,
until the twenty-third year of his age, when it pleased the Lord to accept of his mite,
offered in faithfulness and sincerity, and to cut his work short in this evil world,
and give him his heavenly crown of reward.

He was visited with illness, which brought him into a consumption;
and in his weakness and great affliction of body,
he said to some friends who stood by him, as he lay in bed, as follows:
'`Blessed be the Lord,
that ever he made me to remember my Creator in the days of my youth,
seeing old age is not likely to be my portion;
but a portion has the Lord provided for me among the faithful,
in which my soul rejoices with you, dear friends; for this is our joy,
and the crown of our rejoicing.`'
Another time he said, '`Friends, the Lord is wonderfully good to me in my sore affliction;
he comforts me with his sweet presence,
which is more to me than all the fading things of this world.
Oh! it is good to trust in the Lord, for he never fails them that put their trust in him.`'
And so he lay in a sweet, quiet, and tender frame of spirit.

Many friends being about him, he exhorted them, with tears on his cheeks,
to follow the Lord fully, and to go on in his work and service,
and the Lord would be with them.
This he spoke in so living a sense of the Lord`'s power,
that those about him were much broken into tears, which, when he beheld, he,
with a sweet heavenly countenance said, '`Friends, weep not for me; it is well with me.
Death is no terror to me, for the sting thereof is taken away,
so that I am not afraid to die.
And although my body be laid in the dust, yet in this, dear friends,
remember that I am now going but a little before, and you must follow me.`'
And soon after these words were spoken, he raised himself upon his knees, being in bed,
and returned praises to the Lord for his goodness and
lovingkindness that was then shed abroad in their hearts.
He besought the Lord that he would be with his servants and handmaids;
and that he would prosper that work which he had begun.

At another time, a near relation came to visit him, whom he entirely respected and loved,
who had much lost his former condition in the truth,
to whom he spoke in much love and tenderness, saying,
'`Oh! that our portion might be together.
I fear you despair.
Oh! do not distrust the Lord, for he is all sufficient; he is able to restore you:
but I fear you do distrust his mercy.
The thought of it is more grievous to me than all my afflictions.
Oh! that we should be separated; that grieves me.`'

Being full of pain, and weak, he groaned, saying,
'`Surely the Lord will release me in his time; surely the Lord will ease me of this pain,
for I am pained.
I do not desire to live here.`'
When he drew near to his departure, he awaked out of sleep or slumber; and soon after,
his mother discerning him to breathe short, said to his sister,
'`I think your brother is now dying:`' and he, hearing her voice, spoke these words:
'`I am glad, I am glad; I go away with joy.`'
He called for his father, mother, and sister, to kiss them, and said, '`Weep not for me,
for I have peace with the Lord.`'
He lived some hours after, and lay praising him, saying,
'`The Lord is worthy to be waited upon; he will release me in his own time, '`etc.
Speaking to those about him, he said,
'`To outward appearance my time is but short in this world; but this I have to say,
the Lord has been good to me in my pilgrimage,
and therefore be faithful to the Lord in his requirings, to the end of your days,
and he will never leave you nor forsake you.`'

He quietly departed this life, the ninth day of the Seventh month, in the year 1681,
being twenty-three years and ten months old, at Sabridgworth in Hertfordshire.

[.asterism]
'''

SARAH CAMM, daughter of Thomas Camm, of Cam`'s-gill, in Westmoreland,
and of Anne his wife, a child of nine years old,
was visited with sickness the 13th of the Seventh month, 1682.
She declared that she should be taken away by death, saying,
'`I am neither afraid nor unwilling to die,
but am freely given up thereto in the will of God.`'
When she saw her relations weep, she would say, '`Oh! do not so, do not so.`'
Being near death, her sickness increased; but she was very patient, only had deep sighs.
Her father asked her if she could not pray to the Lord for help; her answer was,
she could, and did pray.
She further said, it was her belief, that the Lord, the great God of heaven and earth,
would keep her, and preserve her soul, whatever might become of her body.

In the fifth day of her sickness,
being under more than usual exercise of mind and spirit,
after a little space she revived, and sat upright in her bed,
and with a cheerful countenance said as follows, '`My sins are forgiven me,
and I shall have a resting place in heaven.`'
Then looking at her mother, she said, '`Oh! my mother,
there is also a place prepared for you in heaven,
and you shall as certainly enjoy it as any here.
I do not,`' said she, '`desire my mother`'s death, or removal from you;
yet we shall meet in heaven in God`'s time.`'
Seeing her friends weep, she said, '`Oh! you should not do so; I am well, I am well.`'
Her father desired the company to withdraw,
lest they should trouble her but she soon called them in again, and said,
'`Shall I go down to the horrible pit?
No, the Lord has redeemed my soul: and called her brother,
to whom she spoke very sensibly.
To her sister she said, '`Be content, for it is, and will be well with me.
I must go to a more fair place than ever my eyes beheld.
It will be well with me, and all that fear the Lord,
for we shall have everlasting joy in heaven, when the wicked shall be tormented in hell.`'

Seeing her sister weep, she said, '`Do not cry, dear Mary, lest you grieve the Lord:
be subject to the Lord`'s will in all things, and love and be faithful to the truth,
and do not forsake your religion, whatever you suffer for it.`'
And further said, '`I am satisfied with my religion.
I will not forsake it,
though I should be fed with the bread of adversity and water of affliction.
Oh! praises, praises to my God, and my Father.
Our Father, which art in heaven,
hallowed be your name;`' and so said to the end of the Lord`'s prayer twice over;
and the third time till she came to that petition, '`Your will be done on earth,
as it is done in heaven,`' which she spoke deliberately, signifying to those about her,
that they were all to mind that; '`For,`' said she,
'`I am freely given up to his blessed will in all things: praises to my God,
bless his name, O my soul.`'

Another time, her father having her in his arms, she said, '`Oh! my dear father,
you are tender and careful over me, and have taken great pains with me in my sickness,
but it avails not, there is no help nor succor for me in the earth;
it is the Lord that is my health and physician,
and he will give me ease and rest everlasting.`'
Near her end she took leave of the family particularly, saying, with a pleasant voice,
'`Farewell, farewell unto you all, only farewell; signifying,
that now she had no more to say; and so went on praising the Lord,
and continued in a sweet frame till she died, lacking eleven days of nine years old.

She died the 18th of the Seventh month, in the year 1682.

[.asterism]
'''

JOSEPH FEATHERSTONE, of Crowland, in Lincolnshire,
was a man whom the Lord endued with much meekness, and he loved truth,
and to do the will of God.
In the time of his sickness he was freely resigned to the will of God,
saying to his wife, '`My dear, give me up to the will of the Lord,
for I can freely give up all.`'
When some of his friends came to visit him, he exhorted them to faithfulness, and said,
'`The Lord will make a dying-bed comfortable to you;`' that
though he felt much sickness and pain upon his body,
yet the refreshment he felt from the Lord made all his troubles easy.

He prayed that his wife and friends might be preserved
in God`'s holy fear and undefiled way,
to bear a testimony to the blessed truth to the end of their days.
The day before he died, being somewhat restless, his wife said, '`Dear heart,
you are restless;`' he answered, with a cheerful countenance,
'`Do you not know where the weary go to rest?`'
and said, '`My rest and fellowship are with the Lord.`'
A little before his death, he rested a pretty while, and being asked how he did, he said,
'`I am well, blessed be the Lord;`' and desired his wife to be satisfied;
and then lifting up his hands, he said, '`O Lord, you are the eternal God.`'
And so fell asleep in the Lord the 26th of the Ninth month, in the year 1682.

[.asterism]
'''

JUDITH FELL, a young woman twenty-four years of age, daughter of Thomas and Anne Fell,
near Ireby, in Cumberland, was never inclinable to vain company,
nor to pride nor lightness of carriage, but always was very sober,
and ready to be a good example to others,
so that she abundantly enjoyed the love of the Lord;
insomuch that on her sick-bed she was wonderfully filled, to the refreshment of others.
Her sickness increasing, which was at times very severe upon her,
some inquired of her how she did; she replied, '`I am well every way.
If I should live ever so long, it can never be better; for my heart is fully satisfied,
and my soul magnifies God, who is worthy forever.`'
Another time she requested her father not to desire her health,
for she said she felt that which was beyond all her weakness and sickness.
Another time she said the sting of death was removed,
and she felt victory over the grave; and so praised the Lord, saying, '`Surely it is you,
O God, that lives and reigns, and must reign forever;
and they are ever blessed who serve you, and fear your name.
You, O God, reignest in the hearts of the sanctified, and you have sanctified my heart,
so that I can truly praise your name.
You know, Lord, for what end you have cast me on this bed of sickness;
surely it is for the glory of your name; therefore, Father, glorify yourself in me.`'

The day before she died, she said she saw that that day she was given to her friends;
and so continued quiet and easy in her spirit, and several times slept very sweetly.
At the end of that night her sickness increased, and she desired to see some friends;
and spoke words to their great refreshment.
The next day, after great fits of illness, she broke forth in praises, saying,
'`He is come that brings joy: Oh! the streams of his love run over all,
even to the skirts of the garment.
Now is the fountain set open for Judah and Jerusalem to bathe in.
Once more solace yourself, my soul, and delight yourself in your Savior;
for I feel his love and life run afresh in my soul,
so that now my spirit does magnify him that lives forever.`'
Her distemper prevailing upon her, they thought that she would not have spoken any more;
but she lifted up her head and said, '`This is the way to rest;
this is the way to rest forever.`'
In a little time she drew her last breath, and ended her life comfortably,
in the twenty-fourth year of her age, in the year 1682.

[.asterism]
'''

JONAH LAWSON, son of Thomas Lawson, of Westmoreland, aged about fourteen years,
was a youth well inclined, of a peaceable spirit, and not known to tell a lie.
He was taken sick of the small-pox; and in his sickness,
his father putting him in mind of the difference between this world and heaven,
where is nothing but joy, the lad answered, '`Ay, father,
I hope I have but little to answer for, and that I have a good conscience.
I have abhorred lying and swearing, and what I saw to be evil; and am willing to die,
if it be the Lord`'s pleasure, or to live to praise him.`'
His sister weeping, he said to her, '`Weep not, I hope we shall meet in a better place.`'
Soon after he uttered these words to the Lord:
'`The time you have appointed for me on earth; give me grace to praise your name.`'
Presently after, as if answered from heaven, he said, '`O, sweet God.`'
A little before his departure, his father and sister being present, he said,
'`I am coming, I am coming.
I must yield, I must yield.`'

He died on the 23rd of the Twelfth month, in the year 1683, aged fourteen years.
After his death, his father found the following verses of Jonah`'s making, namely:

[verse]
____
Humility the spring of virtue is;
Humbling yourself, virtue you can not miss.
Delight in virtue; vice be sure to shun:
He`'s happy that a virtuous course does run.
____

[.asterism]
'''

ELIZABETH BRAITHWAIT, a young maid of seventeen years of age,
died in prison for the testimony of a good conscience, at Kendal, in Westmoreland.
From a child, God by his grace inclined her heart to love, fear, and serve him;
and she was truly obedient to her parents, sober and chaste in her life and conduct,
kind to all, and of a meek and quiet spirit.
She was, with several others of the people called Quakers, taken up by a warrant,
dated the 25th of the Fifth month, 1684,
for not going to church (so called) and carried to Kendal jail.
After some time, she had liberty for a few days to be at her brother`'s house;
but complaint being made against the keeper, she was sent for,
and she was not easy till she returned to prison, for she said, '`That is my place,
and my present home; there I have most peace and content.`'

About two months after her commitment, that is, the 17th of Seventh month,
she was taken sick in prison, and her mother coming to visit her,
asked if she had a mind to go home; she replied, '`No, no; I am at home in my place,
to my full content; and if my God so order it that I be dissolved,
I had rather die here than in any other place.
I am glad that I got to this place before I began to be sick:
here I have peace and true content in the will of God, whether life or death.
I am only grieved that there should be so little
tenderness or pity in the hearts of my persecutors,
to keep such a poor young one as I am in prison.
The Lord forgive them, I can freely.`'
She further said, that her imprisonment was by the permission of the Almighty,
who is greater, and above the greatest of my persecutors,
who I believe will shortly set me free from these, and all other bonds,
over all their heads; and in his peace, in true patience I possess my soul,
and am contented, if it be his will, to be dissolved.`'
A friend asked her why she was so willing to die.
"`Oh,`" said she, '`I have seen glorious sights of good things.`'
The friend queried, '`What things?`' she answered,
'`They are so excellent and glorious that it is not utterable;
and now I have nothing but love and good-will to all.`'
But more especially she was glad in the love and unity she felt with friends; with whom,
said she, '`I have been often refreshed in our meetings together,
with the refreshment that comes from the presence of the Lord.
Oh! the good evening meetings we have had.`'
Another time she said to her mother,
'`They say that we shall spend all our riches with lying here in prison; no,
our riches are durable, and our treasure hidden, laid up in heaven.`'

Her mother seeing her lie under great weight of sickness, would sometimes weep;
but she was always troubled at it, and said, '`Dear mother, do not weep,
but resign me freely up into the hand of the Lord.
Weep not for me, for I am well, Christ my Redeemer is with me.`'
And to her sister she said, '`Come sister, lie down by me, do not sorrow for me,
I am well content to live or die; for my God has blessed me, and will bless me,
and his blessings rest upon me.`'
A little before she departed, her speech failed; after which she would sing in her heart;
lifting up her hands with a cheerful countenance,
and taking her friends by the hand with great affection,
so fell asleep in the Lord on the 28th of the Seventh month, in the year 1684,
in the seventeenth year of her age.
