== Chapter 5

[.chapter-synopsis]
* Springet Penn
* Richard Baker
* Robert Barrow
* Tudor Brian
* Thomas Hains
* William Dewsbury
* Robert Wardel
* Elizabeth Harman
* Anne Mercy
* Morgan Cadwalader

SPRINGET PENN, eldest son of William Penn of Worminghurst, late of Pennsylvania,
was a young man about twenty-one years of age.
For more than half a year before it pleased the Lord to visit him with weakness,
he grew more retired, and much disengaged from youthful delights,
showing a remarkable tenderness in meetings, even when they were silent.
But when he saw himself doubtful +++[+++as to health]
he turned his mind and meditations more apparently towards the Lord,
often praying with fervency to the Lord,
and uttering many thankful expressions and praises to him, in a deep and sensible manner,
saying one day, '`I am resigned: what God pleases: he knows what is best:
I would live if it pleased him, that I might serve him: but, O Lord, not my will,
but your will be done.`'
One speaking to him of the things of this world, he answered, '`My eye looks another way,
where the truest pleasure is.`'

Another time, his father going to a meeting, at parting he said, '`Remember me,
my dear father, before the Lord.
Though I cannot go to meetings, yet have I many good meetings:
the Lord comes in upon my spirit.
I have heavenly meetings with him by myself.`'
With more to the same purpose, expressing his sentiments of the vanity of this world,
and of his entering into secret covenant with the Lord,
and his thankfulness for the Lord`'s preservation and goodness to him.
Fixing his eyes upon his sister, he took her by the hand, saying, '`Poor Tishe,
look to good things; poor child, there is no comfort without it.
One drop of the love of God is worth more than all the world.
I know it; I have tasted it.
I have felt as much or more of the love of God in this weakness,
than in all my life before;`' with more that he said to his father.

Taking something one night in bed, just before going to rest, he sat up,
and reverently prayed thus: '`O Lord God, you whose Son said to his disciples,
whatsoever you ask in my name you shall receive, I pray you in his name,
bless this to me this night, and give me rest, if it be your blessed will, O Lord:
'`and accordingly he had a very comfortable night,
of which he took thankful notice the next day.
At another time he expressed his desire to serve the Lord if he lived.
He one day saying thus,
'`I am resolved I will have such a thing done;`' immediately he catched himself,
and fell into this reflection with much contrition, '`O Lord,
forgive me that irreverent and hasty expression.
I am a poor weak creature, and live by you, and therefore I should have said,
If it pleases you that I live, I intend to do so or so.
Lord forgive my rash expression.`'
He desired his mother-in-law not to trouble herself for such a poor creature as he;
and to pray for him, that he might live and employ his time more in the Lord`'s service.

To his brother he said, looking awfully upon him, '`Be a good boy,
and know there is a God, a great and mighty God, who is a rewarder of the righteous;
and so he is of the wicked; but their rewards are not the same.
Have a care of idle company, and love good company, and good Friends,
and the Lord will bless you.
I have seen good things for you since my sickness, if you do but fear the Lord;
and if I should not live, remember what I say,
when I am dead and gone;`' with many more religious expressions.
Taking his leave of his father, brother, and sister, he said, '`Come life, come death,
I am resigned.
Oh! the love of God overcomes my soul.`'
Feeling himself decline quickly,
and one seeing him not able to bring up the matter that was in his throat,
went to fetch the doctor; but so soon as he came, he said,
'`Let my father speak to the doctor, and I`'ll go to sleep;`' which he did,
and waked no more.

He died the 10th of the Second month, in the year 1696,
in the twenty-first year of his age.

[.asterism]
'''
RICHARD BAKER, of Jordan`'s in Buckinghamshire, received the truth in the love of it,
many years since, and he testified his love to it; 1st. In a circumspect walking,
showing himself a pattern of good works.
2ndly.
By suffering cheerfully for it, and took joyfully the spoiling of his goods,
and the imprisonment of his body; and would often say,
'`If people knew the pleasure of godliness, they would not live in the earth as they did.`'
3rdly.
By a hearty zeal for the prosperity and propagation of it.

A vigilant watchman he was in his station, a sharp reprover of evil,
and an encourager of the good, and a diligent laborer in the work of the ministry,
earnestly endeavoring to bring those he ministered
to into an inward exercise of spirit towards God,
that therein they might be more acquainted with, and subject, to the divine power of God:
concerning which he wrote a treatise, published since he deceased,
although it was written about twenty-six years before;
the reasons whereof he gave upon his dying bed, namely,
That he had read of many in former days, and had observed some in his own time,
who had made fair progress in the way of truth; and had said, done,
and suffered much on behalf of it, who yet had not held out to the end;
but through too great security, or self-confidence,
and for lack of a continual subjection to the power of God,
in and by which alone strength and preservation are to be found,
have by the violent assaults, the subtle insinuations,
or mysterious workings of the enemy, been drawn back again under the power of Satan,
to the invalidating (at least in the eye of the world) the testimonies
such had before given to the sufficiency of the power of God.
And he having by others`' miscarriages learned to beware, had,
from a godly jealousy over himself, suspended the publication of the said sheets,
until he could with greater confidence, and more full assurance,
say with the holy apostle, when the time of his departure was at hand,
"`I have fought a good fight, I have finished my course, I have kept the faith,`" etc.,
which bespoke his great modesty.
Upon his dying-bed, he had the witness in himself that God was pleased with him,
and had a suitable word to every one`'s state that came to him;
and would often clap his hand on his breast, and say, '`All is well here.`'

The day before he departed, many Friends visiting him,
he spoke to all in expressions of great love, and took his leave of them;
and taking his leave of a child who wept, he said, '`Do not cry, I am well,
my peace is made with the Lord.
If you cry, cry that iniquity may be brought down and righteousness brought up.
The power of God and strength of God is with me.
I am going the way of all flesh; I am going before, and others must follow after.`'
So he laid down his life, in the feeling of that power, about the year 1697.

[.asterism]
'''
ROBERT BARROW, born in the county of Lancaster,
but removed and brought up from a child in Westmoreland,
was early convinced of God`'s blessed truth,
and was a zealous laborer in the gospel for twenty-six years,
and a faithful sufferer for the same in London, and other places;
traveling much in this nation, and twice through Scotland, Ireland, and Wales,
to preach Christ Jesus, the light of the world.

In the year 1694 he went forth in the love of God, in company with Robert Wardel,
of Sunderland, both of them being ancient men, to preach the gospel in America.
After they had visited Pennsylvania, and some other parts on the continent,
they took shipping for Jamaica,
where Robert Wardel died the 22nd day of the Second month, in the year 1696.
After Robert Barrow had finished his testimony there,
he took shipping in order for Pennsylvania again, and on the 23rd of the Sixth month,
1696, embarked with various passengers and seamen on board the barque Reformation,
Joseph Kirle, master.
But on the 23rd of the Seventh month, by a storm in the Gulf of Florida,
the vessel ran aground, and to save their lives,
they were forced among the savage cannibals of Florida,
and underwent grievous sufferings of various kinds, being often in great danger of death;
traveling naked in heat and cold, hunger and thirst,
and having no proper food to eat from +++[+++the time of]
their suffering shipwreck, that is,
from the 23rd of the Seventh month to the 15th of the Ninth month following.

At last they arrived at a poor garrison town called St. Augustine,
belonging to the Spaniards in America, maintained partly by the king of Spain,
and partly by the Pope; but the governor, etc., were courteous and generous,
according to their ability, who, after they had clothed and refreshed them,
assisted them to Carolina, which province they reached on the 23rd of the Tenth month,
1696; but several of their company died under the hardships they met with.
Robert Barrow,
by feeding upon such unwholesome food (that little
which they did eat,) was taken with a flux,
which continued upon him;
and together with the great sufferings he underwent in his journeys, being ancient,
he was thereby much decayed in his body;
but his desire was to see his friends once more in Philadelphia,
and he reached Philadelphia from Charleston, in Carolina, in fourteen days.

One remarkable passage I may not omit, namely, the company Robert Barrow was with,
to save their lives, assumed the name of Spaniards,
for the savage Indians stood in fear of them;
and this true-hearted man being directly asked the question, '`Are you a Nickaleer?`'
which is an Englishman; he answered, '`Yes.`'
For his plain dealing, he was stripped naked of his clothes, which till then he had saved.
God permitted not these savages to touch his life, nor the lives of those with him;
though at one time these bloody creatures placed themselves each behind one,
having their arms extended, with their knives in their hands,
ready to execute their bloody design, some taking hold of them by their heads,
with their knees set against their shoulders, waiting for their chief to begin.
They were very high in words, which the English understood not;
but on a sudden it pleased God to work wonderfully for their preservation,
and instantly all these savage men were struck dumb, and like men amazed,
for the space of a quarter of an hour; in which time their countenances fell,
and they looked like another people, and quitted the places they had taken behind them,
and fell to plundering their chests and trunks.

But to return to our friend Robert Barrow,
who behaved himself under all those calamities in great patience,
and by faith overcame even the worst of men, looking to him who is invisible,
who by his grace supported him under all.
By prayer he wrestled with God, to be delivered from those unreasonable creatures,
desiring to lay his bones among his faithful friends in Philadelphia.
And God was so gracious that he sealed an assurance upon his spirit,
even before he was yet off his knees, that his prayer was heard,
and should be answered in due time.
And great strength and comfort he was to his companions in affliction.

When he arrived at Philadelphia, several friends went on board to help him on shore;
but he was so weak that he could not be removed that night,
being the 4th of the Second month,
but he signified to Friends his great satisfaction that the Lord had granted
his request that he might lay down his bones in that place;
that his heart was strong, and he hoped he might see Friends again at the meeting.
He made mention of the goodness of God to him,
and that his presence had attended him in all his exercise.
Next morning he was removed to the house of Samuel Carpenter,
where he slept a considerable time: the same day friends coming to visit him,
he rejoiced, putting forth his hand ready to embrace them, to whom he said,
'`Although my body be weak, my mind is sound and memory good;
and the Lord has been very good to me all along to this very day,
and this morning has sweetly refreshed me.`'
And farther added, '`The Lord has answered my desire, for I desired content,
and that I might come to this place to lay my bones among you.`'
Afterwards he said, '`It is a good thing to have a conscience void of offense,
both towards God and towards men.`'

On the day that he died, he desired a friend to write to his friends in England,
and to acquaint his relations that he had settled his affairs;
and afterwards declared to several friends that were by him, that the Lord was with him,
and all things were well, and that he had nothing to do but to die.
Accordingly, on the same day he departed this life in peace with God,
being the 4th of the Second month, in the year 1697; and was buried the 6th of the same,
in Friends`' burying-ground in Philadelphia, in Pennsylvania.

[.asterism]
'''
TUDOR BRIAN, of London, a youth about seventeen years of age,
was taken ill about the Tenth month, 1696, and from that time decayed daily,
falling into a deep consumption, till the Tenth month following.
Being in the country for his health,
he was often observed to be in retirement in the fields,
sometimes returning with wet eyes;
and his friends apprehending it might proceed from his distemper,
or else from fear of death, his frequent answers were, he was no ways afraid to die,
but willingly resigned himself to the will of God, either for life or death.
About a month before he died,
he was taken so ill as not to be able to go out of his chamber; and so continued,
being daily with a great sense of God upon his spirit;
and would often repeat a full assurance of his future happiness, saying, '`Come,
Lord Jesus, come quickly, and receive my soul.`'
A few days after, he called for a bible, desiring to read; his mother`'s answer was,
'`Child, you are weak;`' he said he could read; and so read the 17th chapter of John,
with trembling lips.
When he came to the 20th verse, "`Neither pray I for these alone,
but for them also which shall believe on me through
their word,`" he took particular notice,
and wept.

On the day before he departed, he fell so ill they thought he was smitten with death;
and several friends, as well then as before, visiting him,
he was much refreshed and comforted, and said, '`O mother,
how merciful is the great God to me,
that has put into the hearts of good friends to visit me!
There are healthier and younger lads than I, that are gone before me,
a poor consumptive lad; he has spared me; surely I shall never forget his mercies.`'
And to the Lord he said, Oh! glory, glory and praises, for they are yours forevermore.`'
Then sitting still, he said, '`Oh, you merciful God, you are merciful.
I can say that I have found it so; that when I had no breath, I have sought you,
and it has been given me.`'
His parents, hearing him, wept; but he answered, '`Wherefore are you troubled,
my dear parents?
Be not troubled for me, for I am going to a better place.
If it be the will of the Lord, he can raise me; but if not, his will be done:
it may be he may spare me two or three days.`'
Turning his eyes on his parents, he said, '`You are the nearest in the world to me,
but yet there is a nearer who is above.`'
After some silence he said,
'`I can say that in my younger years I have gone by myself down into the meadows,
and have cried to the Lord, but knew not where he was;
and when I heard his voice I trembled; and as I gave up,
the Lord Jesus made himself known to me.
Then I knew what I sought for:
'`with more concerning a vision he had of his future happiness;
and he testified against superfluity in the house.

About twelve hours before his death, a near relation desiring,
on behalf of those present, that they might be fitted for their latter end, he said,
'`You must pray, and hang and lean upon the Lord Jesus Christ: for it is of him,
and through him, that we must expect salvation.
Without him you can do nothing.
He died for sinners, and he is merciful to forgive, for he has forgiven me,
blessed be his holy name.
Although some be hardened and stubborn, yet the Lord is merciful; he can and may forgive;
but you that are in the truth, keep in the truth: '`with more which he said,
concerning remembering our Creator betimes, and concerning death.

About two hours before he died, he prayed thus: '`Lord God be merciful; you are good,
you are bountiful.
Lord have mercy on me!
Come, Lord Jesus, have mercy: you died for sinners; glory,
glory to the God of heaven! oh! praises to your name.
Lord Jesus receive my soul: '`with more that he said to his father and mother.
Lying still a little, he said,
'`O what a glorious kingdom I am going to! there are dainties enough.
Lord Jesus you have pardoned me.
O what a numerous army has my God!
He has a great one.`'
And so lay praising God till he finished this life, about two in the morning,
on the 3rd of the Tenth month, in the year 1697.

[.asterism]
'''
THOMAS HAINS, son of Thomas Hains and Hannah, his wife, of Southwark,
in the county of Surrey, was educated in the truth,
as professed by the people called Quakers, by his father;
and also for some time at the school of Richard Scoryer, of Wandsworth.
He was a dutiful child, and had a sense of the fear of God upon his heart,
so that during his sickness he behaved himself more like a man than an infant,
(as he called himself) having a care, lest he should say any word amiss.
If he refused to take any thing offered to him, and was again pressed to take it,
he replied, '`Would you have me tell a lie?`'
Once having refused something, he was desired to promise to take it in such a time;
his answer was`'Can I tell what is to come?`'
When he took that which he found refreshed him,
he with much thankfulness acknowledged it;
being also very sensible of the love and tender regard which his parents had towards him,
and expressed it several times to them.
He bore his sickness with much patience, and often expressed his willingness to die;
saying, '`It is better for me to die; this is a troublesome world;
and we should every day and every moment think upon the Lord.`'

A few days before his decease,
he uttered many expressions in prayer and praises to the Lord, saying,
'`You are a God of love, you are a God of mercy;
you know the hearts of them that love you; you know the hearts of them that seek you.
Lord remember your people.
You know the hearts of the ungodly; you know the hearts of the wicked;
you have nourished and brought up children, and they have rebelled against you.`'
He also spoke of the care we ought to take of the never-dying soul,
and that the Lord will send forth his messengers.
Another time, expressing his inward satisfaction at a future state, he said, '`Glory,
glory; joy, joy: come mother, come father, come all; it is a brave place,
there are no tears nor sorrow: '`and praised God, saying,
'`You are worthy to have the honor and the glory forevermore; for to you it does belong.
You are God of heaven,
and of the whole earth;`' and continued about a quarter of an hour in prayer,
and said to the Lord, '`I am an infant, and cannot do anything without you.`'

One evening, several friends coming to visit him,
he desired their prayers to the Lord for him: and the next day himself prayed again,
saying, '`Our Father, who art in heaven, '`etc.
Afterwards he said, '`It is a brave thing to be at peace with the Lord.`'
His end drawing near, he said, '`Father, let me die.`'
And again called out`' Father, father.`'
His father being present, asked what he desired?
He said, '`I do not speak to you, but to my heavenly Father:
have mercy on me;`' and expressed much joy that he had with the Lord;
and desired them about him that he might be still; and so lay secretly praising the Lord.
A few hours before he died, he said, '`I come, Father, I come: '`and being very weak,
his voice was low, but he was heard to say, '`God is my father:
'`and so like a lamb he quietly finished his days the 12th of the Twelfth month,
in the year 1700, aged nine years.

[.asterism]
'''
WILLIAM DEWSBURY was one whom God raised up in the morning of his glorious day,
broken forth in our age.
After that eminent servant of Christ, George Fox, was set at liberty,
having been almost twelve months in Derby jail,
whereof nearly six months he was in the dungeon, for his testimony to the truth,
in the year 1651, he, passing from there through several counties, came to Balby,
in Yorkshire, where he was instrumental to convince several friends of note,
who were afterwards serviceable in their days, namely, Richard Farnsworth, Thomas Aldam,
Thomas Goodyear, Thomas and John Kilham, James Nayler, etc.
George Fox having a meeting at lieutenant Roper`'s house,
William Dewsbury and his wife came to it, and heard truth declared.
The same evening, they having some conference with George Fox,
confessed to the truth and received it; and after some time,
William Dewsbury publicly preached the same truth.

In the year 1653 he went into Westmoreland, Cumberland and Lancashire,
and declared truth both in steeple-houses and in meetings;
and underwent great sufferings, beatings, etc., and was imprisoned at York,
and also at Northampton in the year 1654.
Indeed, God made him an eminent instrument in his hand,
for the publication of his mighty day of power,
preaching repentance in order to the remission of sins.
He bore a faithful and universal testimony of the free grace of God to mankind:
and the Lord was with him, and prospered him in his manifold sufferings, travels, labors,
and exercises, in the gospel of Christ, and word of the ministry,
as may be seen in his several books, testimonies and epistles,
collected together in print.
Many were made sensible of the benefit of his labors, counsel,
admonition and encouragement, to the good and welfare of their immortal souls.
For the Lord, in whose dread and zeal he labored, endowed him with faith and courage,
and great boldness for his name and truth; and he published the same in great plainness,
and in the simplicity thereof.
To the tender-hearted he was exceedingly mild,
but to the stubborn and lofty he was sharp and plain; admonishing them,
and declaring the righteous judgment of God against that state;
watching with much patience and long-suffering the recovery of such,
who through the subtlety of the enemy, had fallen from the truth,
and from unity with the people of God.
But when any made it their work to cause division and discord,
and to sow dissension among brethren, he would plainly testify against them,
and reject them, as he did in his last visit to London.

A little time before his departure he had a concern upon him for the honor of God,
and that those who had believed, and made profession of the truth,
might answer it in a holy and blameless conduct; which he would often say,
could not be done by largeness of knowledge, and strength of comprehension,
but by a real dying to their wills and affections, by virtue of the daily cross.

The envy of wicked and unreasonable men was very great and fierce against him,
especially in those early days of his travels and labors;
and for the sake of his testimony he was often beaten, stoned, and imprisoned.
He feared neither their malicious threats nor blows, but boldly went forth,
publishing the truth, testifying to that of God in all consciences;
and the hand of divine Providence often delivered him out of the hands of his enemies,
for his name`'s sake.

A few weeks before his decease he came up to the city of London,
and visited most of the public meetings there, and bore a faithful testimony to truth,
and for love and unity; preaching up the cross of our Lord Jesus Christ,
by whom the world "`is crucified unto us, and we unto the world.`" Gal. 6:14.

It being the Third month, 1688, when he was in London,
and he intending to tarry there with friends till the Yearly meeting,
which was approaching, was taken ill about the 29th of the same month,
so that he could no longer be in the city.
He then determined to return home; but before he went,
he left a letter for the Yearly meeting, which is as follows:

[.embedded-content-document.letter]
--

[.salutation]
Dear Friends and Brethren,

I did not know till this last night but that I should
have been with you at the Yearly meeting;
but it pleased the Lord to visit me with my ancient distemper,
which has accompanied me in prison; and since I was released,
the distemper was so sharp upon me, as to my sense,
this last night I did not know whether I should have lived to see another day.
But crying to the Lord, he ordered and cleared my way to go into the country,
so that I cannot be with you at this Yearly meeting;
but desire the Lord to assist you with his blessed power and heavenly life,
to bring in the scattered ones to their everlasting comfort, and his glory forever.
Amen.

[.signed-section-closing]
And that it may be so with you, is the prayer of your loving brother,

[.signed-section-signature]
William Dewsbury

[.signed-section-context-close]
London, the 30th of the 3rd Month, 1688.

--

He lived but seventeen days after he left London; and making short journeys,
got home to Warwick, and continued weak in body.
A few days before his departure, some friends being together with him in his chamber, he,
rising up in his bed, in great weakness of body, said to them as follows:

'`My God has yet put in my heart to bear a testimony to his name and blessed truth,
and I can never forget the day of his great power and blessed appearance,
when he first sent me to preach his everlasting gospel,
and proclaim the day of the Lord to all people;
also he confirmed the same by signs and wonders.
Therefore, friends, be faithful, and trust in the Lord your God; for this I can say,
I never played the coward, but as joyfully entered prisons as palaces,
bidding my enemies to keep me there as long as they could;
and in the prison-house I sung praises to my God,
and esteemed the bolts and locks put upon me as jewels;
and in the name of the eternal God I always got the victory:
for they could not keep me any longer than the determined time of my God.`'

'`And, friends, this I must once again testify to you in the name of the Lord God,
that what I saw above thirty years ago, still rests as a testimony to leave behind me,
that a dreadful, terrible day is at hand, and will certainly come to pass.
But the time when, I cannot say; but all put on strength in the name of the Lord,
and wait to feel his eternal power to preserve you through
the tribulations of these days that approach very near.
In the sense of which I have often been distressed and bowed in my spirit,
with cries and tears to my God for the preservation of his heritage.`'

'`And this I have further to signify, that my departure draws nigh.
Blessed be my God, I am prepared.
I have nothing to do but die, and put off this corruptible and mortal tabernacle,
this flesh that has so many infirmities; but the life that dwells in it,
ascends out of the reach of death, hell and the grave; and immortality, eternal life,
is my crown forever and ever.`'

'`Therefore, you that are left behind, fear not, nor be discouraged;
but go on in the name and power of the Lord,
and bear a faithful and living testimony for him in your day;
and the Lord will prosper his work in your hand,
and cause his truth to flourish and spread abroad; for it shall have the victory,
and no weapon formed against it shall prosper.
The Lord has determined it shall possess the gates of his enemies,
and the glory and the light thereof shall shine more and more unto the perfect day.`'

He concluded in prayers to the Lord,
with fervent breathings and supplications for all his people everywhere,
but more especially for his dearly beloved friends
assembled together at the Yearly meeting at London,
where he had intended to be, if the Lord had given him health:
his dear love was to all Friends who inquired after him.

He departed this life at his house in Warwick, in a good old age,
on the 17th of the Fourth month, in the year 1688.

[.asterism]
'''
ROBERT WARDEL, of Sunderland, in the county of Durham,
received truth about the year 1661, and bore a public testimony to the same,
not only in England, but also in Scotland, Ireland, Holland, and some parts of Germany.
In the latter part of his days, in the year 1694,
he went with our dear friend Robert Barrow, to visit the churches of Christ in America.
They travelled through nine provinces, or distinct governments, in those parts;
among whom they had three hundred and twenty-eight meetings with the people,
for the worship of Almighty God, to their comfort and mutual refreshment in the Lord.
And God enabled them to perform their service to the desire of their hearts,
in their old age;
and by his power supported them under all exercises which they met withal.

They left the continent to visit the islands;
and after they had been at Antigua and Bermudas,
where they had considerable service among Friends and others in those islands,
they arrived at Jamaica on the 10th of the Second month, 1696, intending,
if the Lord permitted, to go to Pennsylvania, etc., again.
After their arrival at Jamaica, they had several meetings; but,
about the 18th of the said month, Robert Wardel was taken ill,
for the climate was exceedingly hot, which made great alteration upon them both,
especially on Robert Wardel, who was very much indisposed.
A friend asking him how he found himself, he answered, '`I have been sick many times,
but I never felt myself as I am now; therefore I know not how it may be with me:
the will of the Lord be done: I am given up, and am content with God`'s will.`'
Another time he said to the woman Friend at whose house he was,
'`The Lord reward you for your tender care; it makes me think of my dear wife.
I know not whether I may ever see her more; but, however, the will of God be done.
I am, and was willing to be, contented with the will of God, whether life or death,
before I came here; and I bless God I am not afraid to die.`'
He continued to the end in a resigned frame of mind, submitting to the will of God.
On his dying bed he gave many good exhortations to Friends who came to visit him,
concerning the education of their children, their care in discipline in the church,
and that things might be kept in good order,
and that Friends might answer God`'s love to them.
After a few days`' sickness,
he peaceably finished his course on the 22nd of the Second month, in the year 1696,
at the house of John Dobbin, in Elizabeth Parish, in Jamaica.

[.asterism]
'''
ELIZABETH HARMAN, wife of John Harman, haberdasher in London,
and daughter of John Staploe, grocer of the same city,
was visited with a lingering distemper, which continued upon her for about four months;
in which time,
God was graciously pleased to give her many opportunities of great comfort,
inclining several friends to visit her, and to pray to the Lord on her behalf.
She much desired retirement, to feel her mind stayed upon the Lord,
that she might feel his living power to prepare her, that whether life or death,
she might be freely resigned and given up to the will of God.
But she said, '`Oh, how hard it is to come there!
It is hard work to die without having a full assurance of the love of God.`'

She had great travail and exercise of spirit, with strong cries to the Lord,
and wrestlings against the enemy, who endeavored to hurry her mind,
and bring her into doubts and fears, so that she would often say,
'`How busy is the enemy in a time of weakness,
and how hard it is to have a mind stayed upon the Lord!`'

After some time it was thought convenient, for the benefit of the air,
to remove her into the country to Mill-hill, in the county of Middlesex;
which being done, she was satisfied therewith, saying,
she hoped she should have more opportunity of retirement to seek the Lord,
and find him near her.

One day her father being near her, she said, '`Oh,
it is a good condition truly to wait and feel the mind stayed upon the Lord.`'
Her father related something of his own experience,
having been greatly distressed for lack of the presence of the Lord,
and help in the time of need.
She acknowledged her father`'s experience, and spoke with great respect of him,
and low thoughts of herself.
At another time she said,
'`Oh the enemy takes advantage of my outward weakness;`' but faith arising, she said,
'`I trust the Lord will drive him quite away.`'

A few days before she died,
her father and another friend coming late one night to visit her,
found her under great inward travail for the enjoyment of the love of God to her soul,
that being all she desired.
The next day, waiting upon the Lord in her chamber,
the friend signified the sense he had of the mercy and love of God towards her;
desiring that she might wait to feel more of it, and trust therein,
watching against the enemy;
and he believed God would graciously answer her desire and breathing;
and she acknowledged his regard to her.
The friend added, '`I believe this day shall not pass over,
before the Lord gives you your longed-for desire;`'
(which was God`'s presence,) and she believing,
answered, '`I believe the Lord will hear your prayers for me.`'
About the third hour in the afternoon,
while her husband and friend sat by her waiting upon the Lord, the same friend prayed,
and God did in a large manner manifest his love among them,
and by his living power drove away the clouds and darkness,
to the refreshing of the mourner,
and the comfort of her that could not be comforted
without the feeling of his power and goodness.
She said, '`Oh, now is the good time come!
Now I feel the love of God towards me, in my soul!
He has opened my heart and brought me into liberty.
How good a God have I! O the merciful God that I have to do with, that has remembered me!
He that said to the thief upon the cross,
"`Today you shall be with me in paradise,`" has looked upon me.
Now I am satisfied.
Now I am freely resigned, and given up to the will of God;
for now has the Lord given me the assurance of his love '` It was observable how
careful she was all along of speaking anything beyond what she enjoyed.

All her near friends and relations sympathized with her
in the deep exercise and travail of soul she underwent,
before she received the full assurance of eternal happiness; which,
when she had attained to, was occasion of comfort and gladness of heart to them.

Soon after, some came to visit her,
to whom she signified something of the Lord`'s dealings with her,
remembering them of their latter end,
and the necessity of a preparation for that time and, withal, how hard it was to die.
One of them being under some convincement of truth,
she declared the need there was to mind and have
regard to the convictions of the spirit of truth,
and discovery of light; certifying the principle of truth to be most excellent;
and so many as are led by it, are fit to die;
but if any professing the same did act contrary, the fault was their own.
Desiring, that not anything of that kind might be a stumbling-block to them;
with more that she said,
speaking of the great assurance of the love of God which she enjoyed,
and now was willing to die, having nothing else to do but to die.
This so greatly affected the persons she spoke to, that they wept much,
and said they never should forget what she had spoken.
At night, her husband and father, and others, being present, she said, '`Come now,
rejoice with me; the good time is now come, because the Lord is good.
The Lord is good,
and has given me the assurance of eternal life! so that you may now rejoice with me,
and I hope you will have a joyful parting.
The Lord give you a good meeting, where I am to be buried,
and bless the opportunity to them that may be there.
O that all might be diligent who have been careless,
and let their minds out after vain things;`' desiring that all might love plainness.

The next day she signified to those about her the
continuance of the favor and love of God,
that she was engaged to speak of, and praise him for the same,
who supported her under great weakness;
and that she saw clearly through the secret and subtle workings of the enemy of her soul,
who would have discouraged her;`'but, '`said she,
'`I know the power that has driven him back, and he must enter no more.
Now is my soul redeemed to God, and he that has redeemed me is near me.
The sufferings and death of Christ, and his agonies; the shedding of his blood,
and what he has done for me; I feel now that I have the benefit of +++[+++them]
all: blessed be my Redeemer who is near me.`'

On the sixth day of the week several of her relations
and friends came from London to see her,
and were much comforted because of the good condition that they found her in;
and the time was good,
because the good God of life opened the living spring in their hearts;
that which stopped the well being taken away,
so that those who loved her most were reconciled to part with her.
To one of those present, whom she loved much, she said, '`Oh, why have you stayed so long?
If you had been here before, I believe I had been gone.
But oh, when I wrestled with the Lord for my own soul, you were still before me,
and it was often in my mind to send for you.
Indeed, I may say, the Lord constrained me; and it was to tell you this,
that your state is as mine was, not as mine is.
No, no, you have hard work to do first.
Oh the anxiety, the sorrow, the agony and perplexity of soul,
the Lord has been pleased to lay upon me; yet +++[+++I was]
blameless as to my life and conduct.
None can accuse me of any evil, neither do I believe they can you;
neither can I. Therefore take it not amiss,
for in pure love to your never-dying soul do I persuade you and exhort you;
for I cannot but say, I have seen clearly into your state.
Because I love you, I am concerned for you.
I know it is as I was: I have sometimes gone to a meeting, and not keeping on my watch,
my mind was cumbered with many things, and I have gone away never the better.
Answer me; has it not been so with you?`'
No reply being made, she spoke earnestly, and asked again, Prithee tell me, tell me.`'
Then an answer being given, she said, '`Watch and pray, dear friend,
for you will find it hard to die; live as well as you can:
and you know not but it may be your turn next.
Though you are a flower, so was I; yet see how I am faded away.
Forget not my dying words, forget them not; they are spoken to you in pure love.
Therefore, dear and tender friend, take them so.`'
Then she said, '`Farewell, farewell; I am going to eternal glory.
But, oh! how hard was it to obtain an assurance thereof!
But now, glory, glory to my God!
I have obtained pardon, and am going to him.
And one word more, dear friend; keep in all plainness both in house and apparel,
for that becomes us best; that will last longest;
that we shall have most peace in;`' then bid her again, '`Farewell, farewell.`'

That night another friend came to visit her, who, with her husband, father,
and several other friends, had a good meeting in her chamber.
After which, she expressed her affection to her husband and tender children,
desiring the blessing of God upon them,
and that her children might be brought up in the fear of the Lord,
and in that plainness which truth leads into; and said affectionately to her father,
You have been a tender father to me, be so to mine; a grandfather, double, double.`'
She further said, '`Though I have a dear, loving husband and two fine children,
and plenty enough of the things of this world, so that there is nothing lacking; but oh,
what is all that?
It is as nothing in comparison of the overcoming love of God which I feel.
Oh, how gracious a God have I. Now I want to go hence.
I long to be dissolved.
Come Lord, come Lord Jesus, receive my spirit.`'
And for the comfort of her friends, said,
'`My gracious God has given me the full assurance.
Oh, the light that I see before me,
and the glory of that kingdom I shall soon enter into`'

The night before her departure, it having been the monthly-meeting at Mill-hill,
several of her friends came from London to visit her.
After they were gone, her father took notice what a company of friends had been below.
She replied, '`I pray God bless you,
and grant to you all as happy an end as I am like to make;`'
with many more sensible expressions which she uttered.
That night she received a letter from our friend William Penn, whom she much esteemed,
and who had been to visit her in the beginning of her sickness; part of it is as follows:

[.embedded-content-document.letter]
--

[.salutation]
Dear Elizabeth,

I am grieved that I am hindered from seeing you, but the Lord I have sought for you,
and in spirit abundantly sympathized with you.
I beseech him, make all easy to you in life or in death.
The Lord God of your life and the life of his dear people, be with you,
and do his blessed good pleasure: in the love of which endless life I bid you farewell,
farewell.
Your friend and brother in the Lord, where we shall meet again and live forever.

--

The which letter, a friend present, at her desire, answered, and she, at the conclusion,
expressed these words, '`My love in the Lord Jesus, in whom I received his love,
is dearly to him, and my dear love to his wife.`'

The next day, being the second day of the week,
she said in the morning to them about her, '`Dear friends, farewell;
the Lord God of heaven and earth be with you, bless you and preserve you.`'
Having taken leave of her husband, and all in order,
leaving directions not only about her children, as to the bringing them up,
but also the family she left behind, and concerning several acts of charity,
also her burial and the manner of it;
about the third hour in the afternoon she said to a minister present,
who often visited her in her sickness, A true friend,
the Lord reward you when I am gone.`'
And having an easy passage, she soon fell asleep, and is now at rest in the Lord.
She remembered her love in the Lord Jesus Christ to friends.
She died at Mill-hill on the 12th, and was buried in London the 15th of the Second month,
in the year 1698, aged twenty-eight years.

[.asterism]
'''
ANNE MERCY STAPLOE, daughter of John Staploe of Aldersgate-street in London,
a young maid between fourteen and fifteen years of age,
was a dutiful child to her parents, a pattern of contentment in the family,
and was seldom out of temper, whatever happened.

She had been at school the 18th of the First month, 1700,
and was taken sick the same day of a violent fever,
yet was preserved in her senses to the last.
At the time of her first being ill, a neighbor being with her,
she said she thought herself to be taken much after the manner that the servant maid was,
who died out of the family two or three months before.
She was heard to say, as she lay in a quiet and still frame, '`Your will,
your will be done.`'
Another time, her mother asking her how she did, she cheerfully answered,
'`that she thought she should not recover;
but desired to be contented with the will of the Lord.`'
When her friends came to see her, she affectionately acknowledged their visit, and said,
'`A broken heart and contrite, was accepted of the Lord;`' with many more words,
but her voice being low, they could not well understand them.
A friend taking leave of her, desired the Lord to comfort her, and she answered,
'`He has;`' and said, '`I have been in the sweetest frame that ever I was in in my life.
Praises, praises be to the Lord; for you are worthy of it.`'

She declared her willingness to die, and that she was happy in the Lord;
and being asked to take something to moisten her mouth she said, '`None;
for in a few minutes I shall be at ease: '`and looking on her friends about her,
she turned her face to the pillow, and said, '`Anne Mercy bids all farewell.`'
A neighbor asking her if she was willing to die, she said`'Yes,
and go to God;`' and departed in about two minutes after, having been sick four days.

She died on the 22nd of the First month, in the year 1700,
and was buried from the Bull and Mouth meeting-house the 25th of the same month,
aged between fourteen and fifteen years.

[.asterism]
'''
MORGAN CADWALADER, son of Morgan Cadwalader, of Merion Township in Pennsylvania,
being under weakness of body, said,
when he was in health he was not so careful as he should have been;
so that when he heard friends speak it was to use but few words in our conversation;
he was not careful enough concerning these things:
and when it happened that he was among some who were light and vain,
it was pleasing to him.

But when the Lord was pleased to visit him with sickness,
and bring him in his apprehension very near death,
then he began to consider his condition, and saw himself lacking.
Then the fear of the Lord came upon him, and he took delight in his service;
and the company of those who were most serious, and careful to keep close to the Lord,
was most acceptable to him.
He desired that they would pray for him;
and the Lord put it into his heart to go alone to wait upon him, and pray unto him.
It was his chief concern to be serious and grave,
and to refrain from that company which he formerly delighted in.
Such a fear was upon his heart, that he would desire his friends and relations,
if they heard him at any time say amiss, to tell him of it.
When he was in his last sickness, a friend visiting him, enquired how he did, he replied,
'`I am not afraid of death, nor punishment after it;
for I know and am satisfied that the Lord will have mercy on me:
and yet I wait to come one step nearer to him.`'
To another friend he said, taking his leave of him, '`When your heart is tendered,
remember me; for it is good for one that is weak to have help.`'
He often said, '`The time of my going to my long home draws nigh;`' '`How good is the Lord,
and how great is his love!`'

One time he asked his mother how short he was of twenty years, she replied,
'`Three-quarters of a year.`'
'` Then, '`said he, '`if I go to my grave in my youthful days,
I shall escape a great deal of trouble that is in the world.`'
And farther said, '`I very often used to go alone into the woods,
and fall on my knees to pray to the Lord, and make covenants with him,
and that with many tears.
Though I have sometimes been too short in performing
my covenants which I made in my distress;
yet the Lord has been merciful to me, and I am willing to die.
This poor carcass, which is much decayed already, will go to the grave;
but the purer part, or spirit that is in it, will go to the Lord that gave it.`'

He said to his brother, '`I know you are tender, and often broken into tears:
if you will be careful, the Lord will be good to you.
I desire you, after meeting on First-days, and on other days, when you have time,
to read the Scriptures, and Friends`' books, and spend less time in reading history;
though I do not say there is harm in so doing, if it do not too much employ your mind,
for these things will be of little worth at last.
I hope you will think on my words, when my body is in the dust.`'
He prayed in this way, '`O! Lord, who does hear and see in all places,
let it be good in your sight to look upon me a poor mortal.
Comfort and strengthen me,
against the time that you may see it convenient to take me out of this world;
and if there be any under great trouble, Lord, do you help them.`'

The morning before he departed, a friend asked him how he did; his answer was,
'`I am very well.
I can wait bravely today,
better than at any time before;`' and desired his father to wait with him that day;
and also entreated both his father and mother to pray to the Lord for him.
He gave good advice to his sisters, to shun vain company; adding,
'`Through the goodness and mercy of the Lord I am going to a good place.
Do not despise your father and mother.`'
Farther speaking to them all, he said, '`When I am departed, be silent,
and have a care you make no noise; but for weeping, you cannot help that.`'
Then he said, '`Turn me on my right side, and I will trust in the Lord.`'
These were his last words that he spoke, and so slept about half an hour,
and departed this life without struggling, as if he had fallen into his natural sleep.

He died the 16th day of the Twelfth month, in the year 1698,
aged nineteen years and three months.
