== Chapter 6

[.chapter-synopsis]
* Richard Samble
* James Martyn
* Mary Mollineux
* Andrew Taylor
* Elizabeth Cowperthwaite
* William Wilson
* Mary Watson
* Grace Watson
* George Harrison
* Elizabeth Barker

RICHARD SAMBLE was born at a place called Penn Hall, in the parish of Enoder,
in the county of Cornwall, and baptized according to the manner of the church of England,
the 24th of the Fifth month, 1644.
His education was in that Society;
and he continued in it until it pleased God to call him by his grace,
and to reveal his Son in him, which was about the year 1666,
at which time the Lord sent some of his messengers, called Quakers, into those parts,
to make known the way of salvation, and to turn people from darkness to light.
Their testimony he received and closed with, and, like Ephraim,
lamented his misspent time, under a form without power;
and then joined himself to the Lord and his people,
as in a perpetual covenant that can never be broken.
He was brought into deep humility,
and sat down in silence in the assemblies of God`'s people for several years,
in tenderness, fear, and trembling,
waiting upon the Lord for that wisdom which is from above.
Sometimes when his heart was filled with the power of the Lord,
he would in much tenderness speak a sentence or two in a meeting of God`'s people,
which was received and accepted.
Though his presence was contemptible to the great men, rabbis,
orators and disputers of this world, yet his testimony was made powerful to many.

He was improved in his gift for the work of the ministry, through great diligence;
and in his last six years he travelled frequently from county to county,
visiting the meetings of Friends in many parts of England and Wales.
At his return from his journeys he fell diligently to his trade, which was a tailor,
for the help of his family.

He gave up his weak body to spend and be spent in God`'s service,
and was as careful of his time as if he had seen
the shadows of the evening stretched out.

He adorned his testimony by a circumspect life, and was very temperate;
and all things were so sanctified to him in the fear of the Lord,
that he was a sweet savor in his day.
His wife did not remember that ever she heard him speak one unsavory word,
during the twelve years she was his wife; and he was contented in every condition;
exhorting her and his children to live in God`'s fear.
In the church he was a nursing father; never sparing his labor,
though many times through much difficulty, to visit the people of God,
both in season and out of season; rebuking some, exhorting others,
and comforting and confirming many, in that heavenly power that accompanied him;
being willing to serve the Lord with all his heart, mind, understanding, and strength.

About the First month, 1680, being then on his travels,
and having been weak some months before, he was taken sick at Poole, in Dorsetshire;
from which, expecting to see them no more, he wrote an epistle to Friends in Cornwall,
the county where he was born, and where he received truth,
and also where his family dwelt; which is as follows:

[.embedded-content-document.epistle]
--

[.letter-heading]
To Friends in Cornwall.

[.salutation]
Dear friends,

I send this salutation, as though it were my last unto you,
wherein I take my leave of you in the Lord Jesus Christ,
desiring you all may obey the truth, and live and die in it.
The many sweet and heavenly opportunities which my soul has had with you,
are fresh in my remembrance.
And now, dear hearts, my body grows very weak, but my soul is strong in the Lord,
who has greatly renewed the lasting seal of his love unto my soul this morning,
Oh! how could I sleep when my heart was so awakened unto
the blessed sense of my acquaintance with the Lord,
which sounded through my soul,
that my name should not be blotted out of the book of life, and of the holy city,
the heavenly Jerusalem, whose foundation is full of precious stones,
and where the river of the water of life flows; where the gates are not shut all day,
neither is any night there.
Which, when my soul heard, my heart was dissolved and broken within me,
and my head was as it were turned into water, and my eyes gushed out with tears,
in the consideration of the endless love of God to such a poor creature as I.

Now, dear friends, who are truly near me in the Lord,
you know the time of our first knowledge and acquaintance, which was a time of love;
and to this day my heart is filled with the same towards you, though I am likely,
as to the outward, to see your faces no more.

O Friends! be not ensnared or entangled with things of this world,
nor let your minds go out of truth,
and so lose the everlasting stay and support of your souls in the last day;
but rather let go all, and hold fast the truth,
and keep your hearts from being overrun with the world`'s spirit;
and so will the spirit of truth spring up in you as a well to refresh your souls.

And all you, whose hearts are truly tendered to the Lord,
whose trials and exercises are not a few, be not daunted nor discouraged,
although the enemy may seek to frighten you with many temptations,
and would seek to lead you out of the fellowship with your dying day;
which exercise my soul has sometimes passed under.
But blessed be the Lord forever, the enemy is found a liar;
for the Lord has been pleased to make this sick-bed to me better than a king`'s palace.
I have great fellowship with my last day, and do rejoice in the Lord,
who does so sweetly visit me with the glorious light of his countenance.
It is with me as it is with one who has travelled many weary journeys,
and at last is come to the sight of his desired end, which, when he sees,
he greatly rejoices in a sense of a further satisfaction which he shall after enjoy.
Even so it is with me,
who have passed no opportunity where I saw the way of life clear and open before me;
but have been ready, night and day, to do the will,
and answer the requirings of the Lord; and so running, as one in a race,
knowing my time that it is but short.
Blessed be the Lord,
I have great peace and satisfaction in this my weak and low condition; and satisfied,
seeing my lot was not at this time among you, that it is here in this place;
and I hope it will be well, whether I live or die.

My dear and well-beloved friends, dwell in love one with another,
walking in the unspotted life,
so shall you grow up as pleasant plants in the garden of the Lord,
and the dew of life will more and more descend upon you,
and this you will feel from day to day; and when you shall come to your latter end,
your reward will be sure with the Lord.

I have much in my heart towards you, but my strength fails me.
Only this I desire of you, seeing I am likely to leave my wife and tender babes with you,
whom I know not whether I shall see more.
Great is my love and tender respect to them,
for we have lived from the beginning as two joined together by the Lord,
who gives victory over the world; believing that, when I am gone,
the care of my God will be over them.
I have been a tender father to them, and they have been to me very tender children,
and my wife has been to me as bone of my bone, and flesh of my flesh,
yet I must leave both her and them unto the Lord.

And this would I leave with you, my dear brethren and sisters,
who have known me from the beginning, that you esteem her, when I am gone,
as one who was wife to him that was made willing
in his day to spend and be spent for God`'s truth,
and his church`'s sake.
I desire you in the Lord Jesus Christ,
that my dear wife may meet with no discouragements from you; she is a tender woman;
and that you will be encouragers of her.
I know when this comes to your hands, there will be no lack of sorrow;
but I trust in my God,
that both my dear wife and you will be so endowed
with the power and presence of the Lord,
that if you should hear of my going hence, you will conclude, as becomes true Christians,
that you must come to me, and that I cannot come to you.

My dear friends, in the opening, free love of God,
which this morning my soul is visited withal, I dearly salute you,
desiring the Lord may be a husband to my dear wife, and a father to my children,
and you friends to both.

And whereas I have never been lacking in my labor
and service for the glory of the Lord and your good,
when with you; and if the Lord yet lengthen my days,
I trust I shall be as ready and as willing as ever I have been;
so I conclude in a sweet and living sense of that love which will never die,
my wife`'s dear husband, my children`'s tender father,
and your own dear friend and brother, in the immortal seed of life,
where we are nearly and dearly related one to another.

[.signed-section-signature]
Richard Samble

[.signed-section-context-close]
Poole, the 1st of the First month, 1680.

--

Thus our dear friend had a true sense of his death;
and this letter manifests that he was a true Christian, a good husband, a tender father,
and a faithful friend and brother.
They were his dying and last words to them, as he said,
for he did not live to see his family and friends in that county, to whom he wrote,
though he continued some weeks after this.

Recovering a little strength,
he was desirous to be at home with his wife and small children,
and relations in Cornwall; and in order to it, he travelled in much weakness to Topsham,
and after a few days`' rest he reached Champet, near Moreton, in Devonshire,
and there he fell into a relapse, and his wife came to him.
The day before his departure, taking leave of his wife, he said, '`Oh! my dear wife,
come here to me, and let me take you in my arms once more.
The Lord will be to you a husband, and a father to our little children,
as you abide faithful to the Lord.`'
Then, after a few words more to her, he prayed a considerable time; yes,
as long as life lasted, he was praising and magnifying the Lord.
To a friend who visited him a little before his death, as he lay weak on his bed,
he declared how well it was with him; that he did give up to the Lord`'s requirings,
to spend and be spent for the church`'s sake;
and said he knew his time would be but short, and labors, travels,
and exercises would have their end, and be no more;
with many more heavenly expressions in much tenderness,
with tears running down his cheeks; which was a great comfort to the Friends present.

So he finished his testimony, and slept with his fathers, the 15th of the Third month,
in the year 1680, and is entered into rest from his labors, and his works follow him.
Aged thirty-six years.

[.asterism]
'''

JAMES MARTYN, born at East Acton, in the county of Middlesex, in the year 1646,
was convinced of truth in the year 1672.
He was a man whose conduct adorned the doctrine of Christ Jesus, which he preached,
and faithfully and zealously labored to spread the truth abroad;
on which account he travelled in America as well as in England.
The first time he went to America was in the year 1682,
and he returned into England in the beginning of 1684;
and went over into America a second time in 1685,
and returned again in the latter part of 1687:
after which he continued laboring in the ministry,
according to the gift of Christ received.

He was a weakly man in body, and was taken sick when he was abroad on a journey in Essex;
and being near his end, he said as follows: '`Good is the Lord:
great is his work which he has wrought in the hearts of his people,
to whom he has given power to follow him faithfully in the regeneration,
through great tribulations, and has made their garments white in the blood of the Lamb,
who has cleansed and redeemed them from the vain conduct of the world;
so that the image of the earthly is done away, and the image of the heavenly is borne.
Their citizenship and treasure is in heaven,
and it is their hearts`' delight to be there also.`'
In which blessed work, this dear servant of the Lord made a good progress,
even to the finishing of his course with joy;
and he received witness in himself that he pleased God, to his great consolation.

In the time of his sickness he had free access to the Lord,
who was pleased to give him the returns of his divine love and life,
to the overcoming of his heart and soul, and the comfort of them who were with him.
O! the heart-breaking power that attended him night and day,
which caused him to sing forth praises to the God of his life.
He often said, '`Oh! precious it is to dwell low with the Lord! not to aspire too high,
but to keep in the low valley, where the streams of life flow freely.`'
Again he said, '`O my dear God, how good are you to me! your goodness breaks my heart!
My dear Father, I have loved you ever since I knew you!
I have followed you faithfully ever since I did know your truth!
You blessed God! Let all that is within me praise
your name! You have given me a good reward!
Death is swallowed up of life.
You have given me victory over the grave.
My soul longs to be with you, my sweet Father!`' With much more,
even continually praising the Lord, and rejoicing in his mercy.
He admonished Friends who visited him to live in the life of their profession, saying,
'`A profession without life will stand none in stead when they come to die.
It is a dreadful condition to see death approaching,
and the terrors of God lie upon the conscience for disobedience.
O it is a blessed thing, when death approaches,
to know peace and consolation with the Lord, and an answer of well done.`'

He afterwards said, '`O what a blessed thing it is to feel life.
Friends, life is that which will make your hearts glad.`'
When his speech was almost gone, those about him could many times hear him say,
'`My soul praises the Lord.
My soul is glad with your joy.`'
He finished this life in great peace with the Lord, on the 30th day of the Eighth month,
in the year 1691, at the house of John Salmon, of Bocking, near Braintree, in Essex,
and was buried in Friends`' burial-ground at Ratcliffe, near London,
the 3rd of the Ninth month following, aged forty-five years.

[.asterism]
'''

MARY MOLLINEUX, wife of Henry Mollineux, of Liverpool, in Lancashire,
was one who in her childhood was much afflicted with weak eyes,
which made her unfit for the usual employment of girls.
Being of a large, natural capacity, quick and studiously inclined,
her father brought her up to more learning than is commonly bestowed on her sex;
in which she became so good a proficient, that she well understood the Latin tongue,
and fluently discoursed in it, and made a considerable progress also in the Greek.
She wrote several hands well, and was a good arithmetician;
as also versed in the study of several useful arts.
She had a good understanding in medicine and surgery, delighting in the study of nature,
and to admire the great God of nature in the various
operations of his power and goodness.

She was one who loved the blessed truth, and those who walked according to it,
from a child, being early convinced thereof,
and was not satisfied with a profession of religion only, but earnest for the life of it,
both in herself and others.
Not proud or conceited of
her parts and learning, but was adorned with humility; plain and decent in her clothes,
which she valued for service more than sight.
She loved to read the Holy Scriptures, and delighted much in solitude,
setting apart some time in the day for retirement.

She delighted in frequenting the religious meetings of the people called Quakers,
and suffered imprisonment for the same in Lancaster castle, in the year 1684.
Afterwards she was married to Henry Mollineux, to whom she was a loving wife,
an affectionate mother to her children, and a kind, charitable neighbor,
especially to such as were in distress, sick, or in affliction, though ever so poor,
giving both advice and medicines to them that stood in need;
whereby she was made an instrument of good to many.
She was noble in enduring hardships upon the account of her husband`'s imprisonment,
which was several times.
For him and his fellow-sufferers she made application to Dr. Stratford,
bishop of Chester, they being imprisoned upon the writ De Excommunicato Capiendo,
for not appearing at the bishop`'s court,
though they had no citation or lawful notice given them;
and after her discourse with the bishop, he was so favorable,
that they were set at liberty.
But afterwards, the priest who prosecuted them before, threatened them again.

She wrote many poems upon religious subjects, which were printed for public service,
having a gift that way.

Upon the 8th of the Tenth month, 1695, she was taken with sickness,
under which she continued nearly a month.
About nine days after she was taken ill, she said, '`I am well contented,
if the Lord see fit, that he take me away; for my pain is great,
and I know not what in this world I should stay to enjoy, except it be my husband,
and my little lads;`' her two sons; of whom she then said,
'`I would rather have my children enriched with the fear of the Lord,
than with all manner of worldly riches.`'
She grew daily weaker, inclining to sleepiness,
yet would sit up five or six hours at a time towards evening, and discourse freely;
and said to her husband, that she was well satisfied,
if the Lord took her away by that distemper, she should be eternally happy;
with more comfortable expressions that are not set down.
One evening it was thought she would have died; but recovering somewhat,
she spoke in Latin of being clothed hereafter;
whereby they understood that she was minding how the Lord would clothe her,
when her mortal clothing was put off.

Her husband asking her if she had any thing on her mind concerning her children,
or any other thing farther to communicate to him, she soon replied in Latin,
'`Why do you speak such things?`'
as if all temporal things were out of her thoughts; '`do not you understand me?`'
he replied, '`Yes, very well, you spoke of spiritual things;`' she answered, '`Yes;
but I have nothing concerning outward things farther to say.`'

The next morning, her breath being short, and her husband expecting her departure,
he expressed to friends present somewhat of his concern for her; to whom she said,
'`Be not you over-much careful or troubled.`'
When company was present she sometimes spoke in Latin,
when she intended it only to her husband.
Afterwards being asked how she did, her answer was,
'`Drawing nearer and nearer;`' with many other sweet and good sentences,
and so departed without any noise, sigh or groan, on the 3rd day of the Eleventh month,
in the year 1695, aged forty-four years.

[.asterism]
'''

ANDREW TAYLOR received truth in the year 1672,
when it pleased God to visit many about the borders of England, in Cumberland,
by sending his servants to declare the word of life among them.
Through his faithfulness and true zeal for the Lord, he came to be wonderfully changed,
and suffered several imprisonments for meeting among the Lord`'s people.
A man diligent in business, faithful and upright among men.
His way was, to be better than he appeared, so that people loved and esteemed him.
After several years, having approved himself just and honest towards men,
God bestowed his heavenly riches upon him,
and called him to the work of the ministry about the year 1679, fitting him for the same;
so that by him many were convinced of the truth and right way of the Lord,
not only in his own country, where he was best known, but in other parts;
for he travelled diligently in many parts of England, and also in Scotland and Ireland.

He was zealous to reprove sin, and careful to preach the gospel freely,
his own endeavors sufficiently supplying his necessities.
At last his body being much spent through his many labors and travels,
a universal weakness or consumption seized him.
Having little pain or sickness, he grew weaker and weaker, and,
being satisfied that his end drew nigh, there continued a travail upon his spirit,
that the Lord God who had been with him,
and borne him up in many deep trials and exercises, would receive him into his rest.
The friends present were witnesses of the hope that he had in his latter end;
and a little before he died, he prayed, saying, '`Come, Lord Jesus, come quickly;
for now I am ready.`'

Being filled with heavenly joy, he departed this life the 3rd day of the Third month,
in the year 1698, in the fifty-fifth year of his age,
and about nineteen years a preacher of the gospel.

[.asterism]
'''

ELIZABETH COWPERTHWAITE, wife of Hugh Cowperthwaite, of Flushing,
in Long Island in America, was convinced of truth about the year 1652,
in the north part of Old England, and continued therein faithful to the end.
She was a woman serviceable to the church of Christ in several respects,
as well by a public testimony to the blessed truth,
which she bore in much plainness and sincerity, delighting in the prosperity of truth,
and of the people of God.
She had true judgment when to speak, and when to be silent;
and divided between the precious and the vile, being tender to the brokenhearted,
but as a sword against that which was evil,
and which tended to division in the church of Christ;
very desirous that the young generation might grow up in the life of truth,
as in the education thereof.

She was at times sick several months before she died,
which she endured with great contentedness, often expressing the love of God to her,
and said that she felt his heavenly presence.
In the time of her sickness she bore many faithful
testimonies to the glory of the worthy name of God,
strengthening and encouraging friends in his work and service,
and against the spirit of separation; for the Lord had sealed it upon her heart,
that that which leads out of the heavenly unity, and brotherly fellowship,
was a false spirit, and not of the Father.
She often said that such could not be heirs with the true seed,
and exhorted those about her against the superfluity of the world;
showing them the ill consequence thereof.
Those friends who came to see her, she exhorted to faithfulness,
saying there is nothing like it.
She continued sensible to the last,
and departed this life on the 15th of the Tenth month, in the year 1697.

[.asterism]
'''

WILLIAM WILSON, of Langdale-chapel, in the county of Westmoreland,
was a man of an innocent life, and though he had little of outward learning,
yet God was pleased to teach him himself, and called him to bear a testimony to his name;
and he did it faithfully, not only in many parts of this nation, but in Germany,
and was several times in Scotland.

He was a man of a lowly and meek spirit, upright and just among his neighbors,
which caused them often to submit their matters in difference to his arbitration,
in which he was careful to find out the truth and ground of things,
and would never countenance deceit.
In this service he had success, seldom missing his desired end, which was to make peace.
Faithful he was in his testimony for the truth,
and a sufferer for the same in the prison of Kendal, in the year 1666,
and several other times afterwards, as well as by distress on his goods.
Besides that, he suffered cruel mockings, stockings, stoning, blows and wounds,
by cruel usage, both from priests and people; particularly at Eshdale in Cumberland,
where he exhorted the people to mind that of God in their consciences,
and turn to that holy light and law which he had put into their inward parts,
that by the same they might come to know the will of God, and do it.

Because of these and such like words, one Parker, a priest,
in cruel rage did beat and wound him, and with one of his crutches broke his head,
and caused the blood to run down his shoulders.
The priest being lame, and not able, as he would, to effect his cruel purpose,
caused his horse to be brought, on which he mounted,
and in the sight of the people broke his staff in three pieces upon William`'s bare head,
which made the people cry out against such merciless work;
but before the said Parker got home he was struck with sickness,
that he never came more to the steeple-house;
and during the time of his sickness he was very loathsome while above the ground,
and so died.

A few weeks after, the said W. Wilson went to the same place at Eshdale;
and for speaking a few words to the people, one Fogo, a priest,
took him by the hair of his head, pulled him to the ground,
and drew him out of the steeple-house; and also in rage and cruelty abused his brother,
Michael Wilson.
But a few months after, this same Fogo, riding over some sands,
accompanied with several people, fell into a quick-sand, and was immediately smothered.

William Wilson left behind him a widow and two daughters,
to whom he was a true husband and a tender father,
instructing his children to keep in the fear of the Lord,
and to walk in the way of truth, which he walked in himself, often saying to them,
it would be the best portion that they could enjoy.

His sickness was short.
Being lately come off a long journey, wherein his body was much spent and weak, he said,
'`I have not served the Lord unfruitfully.
I have no trouble upon me, and I am very sensible that all is well with me.`'
Again he said he was content whatsoever way the Lord pleased: he was as a dove, harmless;
and as a lamb, innocent.
A few hours before he died, he walked several times over the room, and said,
as he had often before, '`My peace far exceeds my pain.`'
And standing upon his feet between two friends, he said,
'`Oh that every one would mind the Lord, that they might keep life.`'
Then he sat down, and drew breath no more.

He deceased at his own house, at Langdale-chapelsteel, in Westmoreland,
the 10th of the Fifth month, in the year 1682.

[.asterism]
'''

MARY WATSON, wife of Samuel Watson, of the county of York, was one who,
for the sake of the blessed truth, denied herself,
and was made willing to part with those things which she thought stood in her way,
abhorring all manner of evil; and was a tender, nursing mother; nourishing, exhorting,
and building up the young in the most holy faith.
Though weak in body, she was much given to fasting on religious accounts,
and giving of alms; spending much of her time in private retirement,
frequent in prayer and praising the Lord, delighting in meditations; like Mary,
of whom our Lord said, she had chosen that good part,
which shall not be taken away from her. Luke 10:42.
While she had strength of body to go to public meetings,
she had a word to speak in season, suitable to the states and conditions of many;
and also was instrumental, in the Lord`'s hand,
in keeping things in good order relating to church affairs.

In the time of her weakness of body,
she was sometimes under fears of her great passage from mortality;
but through travail of soul,
in the living faith which she received of Christ the author of it,
she was kept steadfast, and obtained victory,
which God in his own time manifested to her soul.
And afterwards she made acknowledgments of the same to the refreshment of others.

Several weeks before her decease, she gave an account,
that the work of her redemption was wrought and completed,
and all her doubts and fears were removed; and now she waited to be dissolved,
and to be with Christ who redeemed and sanctified her; so that, as a wise virgin,
she was prepared to enter into eternal joy.
She was filled with praises while she had any strength remaining;
and her eye was to that heavenly family, out of all the families of the earth,
where she gladly desired to be rejoicing with her dear children and relations gone before,
as often her expression was.

She had a tender regard to her offspring whom she left behind, that they might,
through the grace of God, be gathered to Christ Jesus, the heavenly Shepherd;
with many heavenly prayers for them.
Her exhortation to them who were with her, and also for those absent, on her dying bed,
was that they might walk humbly before the Lord their Creator,
and watch against all the evil temptations of this world; the flesh,
and the vanity and lusts thereof; that so they might not be captivated with pride,
vain-glory, or intemperance; but, abiding in the holy fear of God,
all evil would be suppressed and slain upon the cross; and humility, righteousness,
meekness of spirit, and holiness, should grow up in them,
and be not only to them as a comely garment, but as a never-failing portion.

At last, all visible helps and outward enjoyments failing,
she had the Lord for her portion,
and kept in possession of that heavenly treasure in her soul,
and fed upon that living bread and wine of the kingdom,
of which she is now in the more full enjoyment.
She spoke often of her being surrounded with the glory of the Lamb,
and was sensible in her expressions to the last few hours; and said to her husband,
'`Love, pray for me.`'
So gave up the ghost, in a sweet, still manner, on the 2nd day of the Ninth month,
in the year 1694.

[.asterism]
'''

GRACE WATSON, daughter of Samuel Watson, of the county of York,
was well inclined from her infancy, being subject to her parents, and hating a lie;
and in the latter part of her time was much given to retiredness and reading.

In the time of her sickness she had more than ordinary concern
in a travail of spirit and combating with the enemy of her soul;
in which exercise she kept close to the power of an endless life inwardly;
but made no great appearance until the Lord had given her victory over the enemy,
and delivered her from his secret temptations.
Having passed through the ministration of judgment, her enemy,
the crooked serpent (as she expressed herself), was driven far from her dwelling,
so that nothing hindered her refreshments; and the well springing up, her joy was great;
and through her experience she sung the song of Moses, and the song of the Lamb,
in a spiritual triumph, with humiliation and brokenness of spirit.
She spoke seasonably and distinctly concerning the wiles of the devil, who, she said,
had laid his snares in trades, dealings, and conduct in the world, and also in families.
Though, according to common prudence,
one would have advised her to silence (her weakness of body considered),
yet she was so full, and had such constraint upon her,
that words flowed from her a long time, in great sweetness and heavenly refreshment;
insomuch that those with her were humbled before the Lord, in the sense of his presence,
which caused many tears.

As any came into her chamber, whether her friends (called Quakers) or others,
she had a suitable testimony, as if she had felt no weakness of body;
so that much was spoken which was not taken down.
Some of that which was taken, is as follows:

'`Oh, heavenly Father! What have you done for me this night?
How have you removed the crooked serpent! And not only removed him,
but taken him quite away; so that I can truly say, oh,
heavenly Father! your will be done!
You have shone in upon me with your marvelous light;
you have showed me the glory of your house,
the most glorious place that ever my eyes beheld:
neither did I think you had such a place for any, much less for me, a poor worm,
a pelican, once ready to think myself destitute.`'

Again she said, '`But now has the Lord taken me up; he has removed the crooked serpent;
so that I can say, I defy him, I defy him.`'

And further said to the Lord, '`If you require my life this night of me,
I freely give it unto you.
Oh, heavenly Father, your will be done; and if you have farther work for me,
keep me in that which I now enjoy,
for there will my greatest care be;`' meaning to be kept therein.

She said, '`You have made my cup to run over, over, over.
O heavenly Father, you have taken away all my pain.
I am as if I ailed nothing, though of myself I could do nothing;
scarcely move one of my fingers, my tongue being ready to cleave to the roof of my mouth;
but you have been a light to my feet, and a lantern to my path.
How can I cease praising you, you God of power! you are more to me than corn,
wine and oil.
Your love is sweeter to my taste than the honey, or the honey-comb.
Oh! it is more to be valued than the costly pearls, and the rich rubies.
The gold of Ophir is not to be compared unto it, O blessed, O praised,
O be magnified forever!`'

When she was asked how she did, her reply was, '`I am but weak of body,
but strong in the Lord, and in the power of his might.`'

Once she was questioning something, but she checked herself.
'`Why do I so?
My case is no doubting one;
the Lord has created a clean heart and renewed a right spirit within me,
so that all fears and doubts are taken away.
For,`' she added, '`the gates are open,
and the angels are ready to receive me into the bosom of my heavenly Father,
where I shall sing praises with his redeemed ones.`'

It was not perceived, in all the time of her sickness, that she desired to live;
but many times she said as above, '`If you require my life this night,
it is freely given to you.
Oh!
Lord, do with me what you please.
Oh! heavenly Father, your will be done.
What have you done for me, a poor stripling, in comparison of many?
You have made my bed, you have taken away my pain, and my sickness is gone.`'
And so lay all that day, with many other times, in this frame of spirit.

She said, '`The Lord has a people in this city, and other parts,
that he will take to himself, and crown with glory and honor.`'
She exhorted those present to prize their time,
and not to give themselves too much to the things of this world.
'`How many,`' said she, '`have laid up great riches, earthly treasure,
and in one night have been deprived of all!`'

Her sister weeping by her, she said, '`Weep not; remember David and be comforted.
The tongues of men and angels cannot declare the wonderful greatness of God.
O heavenly Father, how sensible of you have you made me!
You have strengthened me, otherwise I should not have been able to speak so much of you.
With you is fulness of joy, and at your right hand are rivers of pleasure forevermore.`'

She spoke of the parable of the ten virgins, '`Oh! therefore,`' said she,
'`keep upon your watch-tower, that whether he comes at midnight, or cock-crow,
or dawning of the day, +++[+++you may]
be ready; for that is the wedding-chamber indeed, and he is the heavenly bridegroom.`'

Speaking of her parents and relations,
she said they were as near to her as the flesh to the bone;
and taking her sister by the hand, she said to her, '`Though we be separated outwardly,
we shall meet in the kingdom of glory.
O! what cause have I to bless the Lord on their behalf,
whom I am sure never countenanced any evil in any of us, but reproved it.
The words of my dear and tender mother I do remember, since I was but ten years of age,
who said, she had fought the good fight of faith,
and the crown of glory was laid up for her.
These words having remained upon my mind, and taken deep impression upon me,
I can now say, I finish my course with joy, and shall receive the crown of glory.`'

She further said, that the Lord was a God at hand in six troubles, and in seven; '`no,
if you bring me to the eighth, you will never leave me:`'
such was her confidence in the Lord.
She departed this life in London, the 20th of the Sixth month, in the year 1688,
aged nineteen years and nine months.

[.asterism]
'''

GEORGE HARRISON, of the parish of Killington, in the county of Westmoreland,
came of a family of note in the world,
and underwent some hardships from his relations upon the account of truth,
which he received in the year 1652,
and soon after travelled in the service of the gospel in many counties of England,
through great afflictions, sufferings, and persecution,
from those who were high in profession of religion in that day.

He was an able minister of Jesus Christ, and valiant for the Lord.
When he came into a meeting of professors,
he would challenge of them the order of the true church, according to 1 Cor. 14:30,
which is, "`If any thing be revealed to another that sits by,
let the first hold his peace.`"

In the latter part of his time he went southward, and came to Edmundsbury, in Suffolk,
and declared truth through the streets of that town.
Afterwards he went to an inn there, desiring some refreshment for his money,
but they would not entertain him.
So he went to Bradfield-manger, and put up his horse at an inn,
and called for something to eat and drink;
but they perceiving by his language that he was a Quaker, refused also to entertain him,
and led his horse out of the stable; for which cruelty he meekly returned to them,
in the words of Christ, Matt. 25:43, "`I was a stranger, and you took me not in.`"
This innocent young man was obliged to ride abroad all night;
and it being a very wet season, and he having been tenderly brought up,
took a great cold.
He went to Haveril, a town between Suffolk and Essex,
where the people grievously beat him for his testimony to the truth; which hardship,
with the great cold that he had received by being forced abroad all night without food,
greatly injured his health, and put him in a fever.
After this, with difficulty, he got to Coggeshall, in Essex,
and was kindly received by Robert Ludgater;
and afterwards he removed to the house of Thomas Creek, of Little Coggeshall,
a mile further.

During his sickness, he felt the love and peace of God to be with him,
and said to the friends about him, '`Come, friends,
rejoice with me:`' and so lay praising God to the last hour.

He died at the house of Thomas Creek aforesaid, aged about twenty-six years,
and was buried in the orchard of Thomas Sparrow, tanner, at Stansted, in Essex,
the latter end of the Fifth month, in the year 1656.

[.asterism]
'''

ELIZABETH BARKER, wife of John Barker, merchant in Tower street, London, being sick,
a Friend went to visit her; and when she understood that he was below,
she caused those present to withdraw, and sent for him up.
He asking her how she did, she wept, and said, '`I am a poor weak woman;
and I have prayed to the Lord that if I am to die of this sickness,
he would let me know it; and I do not see it yet, though I am weak enough to expect it.`'
She expressed much concern for her three children, if she should be taken away.
The Friend answered, it was true that children are very near to tender parents,
but we ought to be resigned, and commit them to God who gave them to us; and besides,
if she should die, their grandfather and grandmother Barker were not only able,
but willing to take care of them.

Upon which she seemed somewhat satisfied: after a space of silence she said,
'`It is assurance of my peace with God that I do earnestly desire.`'
And further, '`For these two years past God has been at work in my heart,
and I endeavored to answer his will, and have denied myself of some things;
but I have had a care not to do it in imitation of others,
but from a conviction in my own conscience.
I hope, if I live, I shall be faithful to God,
and keep those covenants that I have made with God.`'
Afterwards she said, '`Oh the presence of God! it is that which my soul desires to enjoy.
God has been good to me many times; for when I have been alone at home,
as well as in meetings, the Lord has broken in upon my heart.
When I have been troubled and exercised in my mind,
I have gone in secret and prayed to the Lord, and I know he has heard me,
and several times answered my prayer, not only for myself, but for my children also.`'
She particularly mentioned one time,
when one of her children was in appearance near to
death; '`I bowed my soul before the Lord,
with earnest cries to him for my child; and the child fell into a sleep,
and awakened much better, even before she took any medicines.`'

After some pause, she asked the Friend who was with her,
what his thoughts were concerning her recovery; to which he replied,
he had little to say to that; and desired her to keep her mind stayed upon the Lord,
whom she acknowledged had mercifully visited her,
and she would find him still to extend his mercy and favor to her,
with his good presence, which was the most comfortable support upon a sick-bed.
She replied, '`God has been with me in this sickness, but I want more of his presence:
'`and added, '`In the first of my sickness, and before, at times,
I used to be terrified with the thoughts of death; but now it is not so.
I am not afraid of death; that fear is taken away.
Yesterday they thought I was dying, and they were in a great hurry about me;
but I was not so in myself, for I felt great sweetness and stillness upon my mind.`'
Afterwards she said, '`I do not find that the Lord does lay any thing to my charge.`'

Speaking concerning her child, she said, '`When I was last year in Yorkshire,
God did many times visit my soul, and I had large enjoyments of him;
and one time praying to him, I fervently asked the Lord to give me a son;
and now God has answered me in this request;
my desire is (which she spoke with much concern) that, when he is grown up,
he may be a preacher of righteousness.`'
She spoke upon several things, which are omitted, for she had a clear understanding,
and was in a right mind and frame of spirit.

Another time the same person visiting her, she desired all in the room might be still,
and she waited in much retiredness of mind, secretly breathing to the Lord in her heart;
and the Friend prayed by her, with whom she heartily joined.
Upon his leaving her, she said, '`This has been a good time.
I have many visitors, but too few of this kind.
I have felt the Lord`'s presence, but he will be quickly gone again.
I have not so much of these sweet enjoyments as I desire.`'
After some more that passed,
he asked her if she desired to speak with any particular Friend in the city,
and he would acquaint them with it; she answered, '`I have not; I am easy in my mind.`'

About three days before her departure, when it was thought she was dying,
the same Friend being sent for, she told him that she was willing to die,
if it was the will of God;
and gave him an account of the concern that she had upon
her mind for a relation who came lately to visit her,
whose sister had married one that was not called a Quaker.
Said she, '`I entreated her not to do the like; also I prayed her mother,
that she would not allow it to be; and I desired her not to forsake the truth,
and God would never forsake her; and they both wept; and when she comes again,
I will endeavor to make her promise me not to marry one that is not a Friend.`'
The person replied,
'`But then she must also keep her promise;`' to which she earnestly answered,
'`Ah! so she must.`'
The rest that she said at that time is omitted; only,
that she had a great desire to speak to the other sister who is married;
but she said she was in the country.

Her father and mother coming to visit her, found her in a heavenly frame of mind;
and she said, '`O mother, you know that I have been afraid of death,
and how I have loved vain and foolish things;
but I have prayed to the Lord to forgive me all my sins.
And now, instead of that fear of death, there is much sweetness upon my soul;
and all those vain things I once loved, I now loathe; and all the world is nothing to me:
with much more, expressing her satisfaction and peace of conscience.
She spoke of the exceeding joy and comfort that she felt,
and how sweet the presence of God was to her soul;
and she made heavenly melody to God in her heart,
which tenderly affected the minds of those present.

Her sickness increasing, she grew weaker; and though sometime before,
she did not see that she should die,
yet afterwards was satisfied concerning her departure; and, in order thereunto,
bequeathed several things to her relations and children,
and gave directions concerning the ordering of her children and family,
and also where she would be buried.
She received assurance of her future happiness; for, a few hours before her decease,
the said Friend before mentioned, coming to visit her, found her very much spent,
and her kindred and relations mourning about her; and he prayed,
desiring that all might submit their wills to the will of God,
who gives and takes away as he pleases.
A considerable time after he was gone, lying very still, she said, '`The voice said,
"`Submit, submit;`" and I say, I have submitted,
I have submitted;`' or to the same effect.
When these words were spoken, a relation present said,
'`You are going to leave us;`' she replied, '`I shall be happy.`'
She also, in the time of her sickness,
saw a vision of the difficulty of her passage out of this world,
and of the felicity of the place she at last was to arrive at.

She peaceably ended her days the 6th of the Third month, in the year 1701,
aged twenty-eight years.
