== Chapter 7

[.chapter-synopsis]
* John Crook
* Sarah Beckwith
* John Burnyeat
* Henry Haydock
* Thomas Janney
* Henry Stout
* Thomas Aldam
* Margaret Kellam
* Joan Kellam
* Sarah Brown
* William Walker

JOHN CROOK was born in the year 1617, and received the blessed truth,
as testified of by the people called Quakers,
at its first being preached in Bedfordshire, which was about the year 1654.
He was a man of note in that county, having been a justice of the peace;
and the Lord by his spirit made him an able minister of the gospel of Jesus Christ.
He had great discoveries in the mysteries of the gospel, was sound in doctrine,
and a skillful archer, hitting the mark.

In former years, when he was out of prison, he labored much in publishing the gospel,
and many were the seals of his ministry.
As he had received a part of the ministry,
so also he had a share of sufferings for his faithful testimony,
being imprisoned in several places, as at London, Huntingdon, Aylesbury, and Ipswich;
and as he sealed to the truth by sufferings,
so he was careful to adorn the same by conduct,
and had regard to the power of godliness in life and doctrine, above dead forms,
and to the spirit above the letter, yet highly esteemed the Holy Scriptures,
with respect to the sacred doctrine thereof, being well read therein,
and devoted for the faith and practice thereof, as the Lord gave him understanding.

He was eloquent, allegorical, and mysterious, many times in his ministry;
but did not thereby deny or invalidate the history of Christ, etc.,
as recorded in the Holy Scriptures.

The mystery of Christ in spirit, and as revealed and formed in true believers,
and their sincere conformity to him in spirit and conduct, he greatly esteemed;
desiring the professors of Christianity might come
into the true sense and experience thereof,
by a true, living and feeling faith in Christ, and sincere obedience to him.

He spent his former years mostly in and about Bedfordshire and the counties adjacent,
and his latter years in Hertfordshire,
being often disabled from traveling far by reason of several infirmities of body,
so that he would say (with Israel), "`I have been afflicted from my youth,`" Psalm cxxix.
Under the sorrow and grief that.he had with some of his children, he would sometimes,
in a tender frame of spirit, comfort himself in the words of David,
"`Although my house be not so with God, he has made with me an everlasting covenant,
ordered in all things, and sure,`" 2 Sam. 23:5; and said,
that the Lord did remember the kindness of his youth.

His patience under his bodily infirmities was very remarkable,
and as a good Christian he made the best use of them,
saying that the furnace of affliction was of good
use to purge away the dross and earthy part in us;
and that, did he not feel and witness an inward power from the Lord to support him,
he could not subsist under his pains, they were so great,
which continued with him to his end;
yet he was not remembered to have uttered an unsavory word, or impatiently to cry out;
and when the extremity of his fits was over,
he would express his inward joy and peace that he had with the Lord.

He would many times say, that many of our ancient friends were gone to their long home,
and we are making haste after them;`' Thus, '`said he, '`they step away before me,
and leave me behind, and I that would go, cannot.
Well, it will be my turn soon;`' in which he seemed to rejoice.

He finished his course the 26th day of the Second month, in the year 1699,
in the eighty-second year of his age, and was buried at Friends`' burial-ground, at Sewel,
in Bedfordshire.

[.asterism]
'''

SARAH BECKWITH, daughter of Marmaduke Beckwith, of Audborough, near Masham in Yorkshire,
was from a child sober and grave in her deportment,
not addicted to light and needless words,
but behaved herself as one who was watchful lest she should offend the Lord,
or be an evil example to others.
She was obedient to her parents, and tenderly affectionate to others,
one sincerely devoted to serve the Lord,
and seek his kingdom and the righteousness thereof.
She loved retirement, and when her business was over,
would walk alone in the fields and other places, where she sought the Lord,
and would sing praises to him, when she thought nobody saw or heard her.

In her sickness she was much troubled with shortness of breath,
and often prayed to the Lord, to enable her to praise him while she lived.

About five days before her decease, having some ease,
she desired to be raised up in her bed,
and spoke largely of the tender dealings of God with her,
desiring those who were young to prize their time,
not knowing how few their days might be;`' For, '`said she,
'`many are the temptations of the enemy, especially to youth, presenting length of days,
and persuading them that it is soon enough to trouble themselves with such a concern,
for so he would have persuaded me; and many ways was I tempted,
which caused such exercises that I was brought nigh to despair.
I sought the Lord night and day.
No ear heard me but the Lord alone, who heard my call,
and afterwards gave me some comfortable assurance of my salvation:
but the enemy has been very busy, and has sorely hurried me,
since I began with this illness.`'
Afterwards she prayed, '`Lord,
give me full assurance of my salvation before I depart hence!
O Lord, let not my distemper overcome my senses, till I come to a full enjoyment!
I pray you, let not my desires cease, till you answer the desires of my heart;
and let nothing quench your love.`'
And the Lord answered her cries, and caused her cup to overflow,
so that she sung heavenly praises to the God of her salvation.

She also gave tender advice to her sisters,
and desired them to love and fear the Lord above all, and keep in the truth; saying,
'`Oh! press after it, to feel the working of it in your own hearts;
and when you are in it, keep in it, and under the government of it.
Heed not to deck yourselves, but be meek and low.
None ought to pride themselves in any endowment, either beauty, or any other thing;
because it is not theirs, but the Lord`'s who gave it them,
and can take it away when he pleases;`' saying, '`What is all now to me?`'
She also spoke of the condition of some who were grown careless,
and were got into liberty;`'Such, '`said she,
'`are ill examples to those that are coming up.`'
She said there were many who professed truth that knew little what truth is.`'
It does not consist only in coming to meetings, and wearing plain apparel and the like,
unless they come to feel the operation of truth in their own hearts;
for all such outward appearances will stand in no stead,
without the love of God be inwardly felt and enjoyed.
It is an easy thing to come to meetings; and some are ready to think, that doing so,
and behaving themselves soberly, is sufficient; but the Lord sees at all times,
and he will have no such mockery.
I bless God, I have not been guilty of seeming what I was not.`'

Her love was great to faithful friends, and she much desired their company,
and wonderfully prized the love and mercies of God, saying, '`It is not for my deserts,
for I had nothing to engage the Lord with, but it is his free love to me.`'
She said there was man`'s righteousness, and the righteousness of God;
but man`'s righteousness must be rent off,
and man covered with the righteousness of Christ Jesus, who said,
"`I lead in the way of righteousness, in the midst of the paths of judgment,
that I may cause those that love me to inherit substance.`"`' Speaking of the way of truth,
she said, it was a strait and narrow way, and not to be kept in without a daily watch;
and further said, '`But although a strait way, yet it is a pleasant path, and delightsome.
Oh! here is peace in abundance.
It is so sweet, I could delight always to enjoy it, and to live therein;
gold is not worthy to be compared to it.`'
She thus continued, being taken up with heavenly thoughts, saying, '`Lord,
give me fully to drink of the well of water that is within the gate,
for you have raised my heart, and I am overcome with your love.
O! I long, I long!
O! Lord, open you the windows of heaven, and pour of your blessings into my soul,
until there be not room to receive, that I may bless and praise your name.`'

Her end drawing nearer, she prayed the Lord to give her an easy passage;
and taking her leave of her sister Hannah, she said if she was worse,
some should call her.
Taking her by the hand, she said, '`Dear sister, you have been near and dear to me,
and careful of me: the Lord requite you,
and be near to you when you come to lie on your dying bed.`'
Near morning, her distemper growing upon her, she said, '`I am as sensible as any of you,
and I am well content to die.
I have no doubt of my salvation: '`with many more good expressions,
which could not be perfectly understood, her voice being low;
but she was sensible to the last,
saying within a very little time of drawing her last breath, '`Lord,
take me away;`' and presently after, she gently and comfortably passed out of this world,
to live forever in a world which has no end.

She departed this life the 24th of the Ninth month, in the year 1691.

[.asterism]
'''

JOHN BURNYEAT was born in the parish of Lowes-water, in the county of Cumberland,
about the year 1631; and when it pleased God to send his faithful servant George Fox,
with other of the messengers of the gospel of peace and salvation,
to proclaim the day of the Lord in the county of Cumberland, and north parts of England,
this dear servant of Christ was one that received their testimony,
which was in the year 1653, when he was about twenty-two years of age.
Through his waiting in the light of Christ Jesus, unto which he was turned,
he was brought into deep judgment, and great tribulation of soul,
such as he had not known in all his profession of religion,
and by this light of Christ were manifested all the reprovable things;
and so he came to see the body of death, and power of sin which had reigned in him,
and felt the guilt thereof upon his conscience,
so that he did possess the sins of his youth.`'
Then, '`said he, '`I saw that I had need of a Savior to save from sin,
as well as the blood of a sacrificed Christ to blot out sin,
and faith in his name for the remission of sins;
and so being given up to bear the indignation of the Lord because of sin,
to wait till the indignation should be over,
and the Lord in mercy would blot out the guilt that remained,
which was the cause of wrath, and sprinkle my heart from an evil conscience,
and wash our bodies with pure water,
that we might draw near to him with a true heart in the full assurance of faith,
as the Christians of old did.`' Heb. 10:22.

Thus did this servant of the Lord, with many more in the beginning,
receive the truth (as more at large may be seen in
the journal of his life,) in much fear and trembling,
meeting often together, and seeking the Lord night and day,
until the promises of the Lord came to be fulfilled, spoken of by the prophet Isaiah,
chap.
xlii.
7, xlix.
9, and lxi.
3+++.+++ Some taste of the oil of joy came to be witnessed,
and a heavenly gladness extended into the hearts of many,
who in the joy of their souls broke forth in praises to the Lord,
so that the tongue of the dumb, which Christ the healer of our infirmities unloosed,
began to speak, and utter the wonderful things of God.
Great were the dread and glory of that power,
which in one meeting after another were graciously and richly manifested among them,
to the breaking and melting many hearts before the Lord.
Thus, being taught of the Lord, according to Isa. 54:13, John 6:45,
they became able ministers of the gospel,
and instructors of the ignorant in the way of truth.

After four years waiting, mostly in silence, he appeared in a public testimony,
which was in the year 1657,
being at first concerned to go to several public places of worship,
reproving both priests and people for their deadness and formality of worship,
for which he endured sore beating with their staves and bibles, etc.,
and imprisonment also in Carlisle jail,
where he suffered twenty-three weeks`' imprisonment
for speaking to one priest Denton at Brigham.

After he was at liberty he went into Scotland in the year 1658,
where he spent three months, traveling both north and west.
His work was to call people to repentance,
from their lifeless hypocritical profession and dead formalities,
and to turn to the true light of Christ Jesus in their hearts,
that therein they might come to know the power of God, and the remission of sins.

In the year 1659 he went into Ireland,
and preached the truth and true faith of Jesus in many parts of that nation.
About the Seventh month following, meeting with Robert Lodge,
a minister concerned in the same work, he joined with him,
and they labored together in that nation for about twelve months,
in the work of the gospel, and returned to Cumberland in the Seventh month, 1660.

In the year 1662 he travelled to London, where he met with George Fox,
Richard Hubberthorne, and Edward Burrough; and in his returning home through Yorkshire,
at Rippon he was committed to prison, and kept fourteen weeks,
for visiting the friends who were prisoners there.

After he was discharged of that imprisonment he returned home, where he abode,
except at times visiting friends in adjacent counties,
till the beginning of summer in 1664, when he took shipping again for Ireland,
and visited most of the meetings in that nation.
From there he embarked for Barbados, in order to perform his journey into America,
which had lain before him for four years; and from Galway he arrived at Barbados,
after a passage of seven weeks, and stayed three or four months there,
and had great service, and much exercise also,
occasioned by the imaginations of John Perrot,
and that fleshly liberty he had led many into, not only there,
but in Virginia and other places.
From Barbados he went to Maryland about the Second month, 1665,
and afterwards to Virginia, laboring in the work of the gospel.
In the Fourth month, 1666, he came to New York, so to Rhode Island, New England,
and Long Island, till the Second month, 1667, at which time he went again to Barbados,
and spent that summer there.
In the Seventh month of the same year he sailed from there, and arrived at Milford-Haven,
in Wales, and labored much in the gospel in this nation,
from the time of his arrival from America, till the latter end of the year 1669,
when he went over and spent that winter among friends in Ireland,
and returned to London in the year 1670.

In the Fifth month, 1670, he embarked for Barbados again,
in company with William Simpson, who died in peace with the Lord in that island.
From there he went to New York, Long Island, Rhode Island, and New England,
and afterwards to Virginia and Maryland, where he met George Fox and several brethren,
just come from Jamaica.
Having spent much time and labor up and down in America,
till the 25th of the Second month, 1673, they came from the Capes of Virginia,
and arrived at Galway in Ireland, the 24th of the Third month,
and from there they came to the yearly meeting at London, in 1674.

From that time he continued in this nation, laboring among the churches,
until the Eighth month, 1681, when he went to Ireland again,
and tarried there till the Sixth month, 1684, and then he came into Cumberland,
and so to Scotland, and into the north parts of England again,
visiting the meetings of Friends, and so returned to Ireland the 25th of the First month,
1685, where he tarried till he departed this life.

In the latter part of his life he took a wife in Ireland, and had by her one son.
After the death of his wife, he had some intentions to go for England,
about the year 1688; but seeing the troubles and wars in Ireland coming on,
and that many afflictions would attend Friends in that nation,
and people being possessed with fears fled for England; our dear friend,
though he had opportunity, had no freedom to go,
but gave himself up to stay with Friends there,
and bear a part of the sufferings that might attend them.
In this time he was a precious instrument in the Lord`'s hand,
able and skillful in the ministry, for the comforting of his people;
for he was a cheerful encourager of them, a dear friend and true brother;
a diligent overseer and tender father; a perfect and upright man in his day.

Having been at a province-meeting at Rosenallis,
where he bore a living testimony to the comfort of friends,
he went from there to Mountrath and Ballinakill,
and so to a monthly meeting at New Garden; after which he came home with John Watson,
and feeling himself not well, took his bed, and was visited with a fever,
and continued sick twelve days; in all which time he was preserved in his senses,
and in a sweet frame of spirit.
He often said he was finely at ease, and quiet in his spirit,
and the Lord did attend him with his heavenly power and presence, to his comfort,
and the satisfaction of those about him.
He said that he ever loved the Lord, and the Lord loved him from his youth.

He peaceably departed this life on the 11th day of the Seventh month, in the year 1690,
and was decently buried at New Garden, the 14th of the same.

Convinced at the age of twenty-two; a laborer in the gospel thirty-three;
aged fifty-nine years.

[.asterism]
'''

HENRY HAYDOCK, of Warrington, in the county of Lancaster,
was a faithful man in life and conduct, and walked as becomes the blessed truth,
of which he made profession

When he was upon his dying-bed, and in outward appearance nigh gone, the Lord,
who is the God of the living, raised him up by his divine power,
to the admiration of those present, to bear a living testimony for him, which was thus:

'`Friends, I was never a public preacher in all my life; but now, by the power of God,
I am one at my death.
Glory be to God forevermore, who has the life and breath of all men in his hand,
and can lengthen at his pleasure; who knows how to dispose of us.
Therefore, friends, all be faithful to the Lord,
for great things will the Lord bring to pass for his people,
who are true in their hearts to him.
Such as serve God faithfully, they shall have a living reward from him,
and their rest shall be with the Lord Jesus Christ;
which rest my soul is already entered into,
and is set down with God in the Paradise of his pleasure,
taking its repose with God the Father, and our Lord Jesus Christ,
and all the holy men of God since the foundation of the world.
And though my body go down to the earth,
yet my soul and spirit shall have its residence with the living God in heaven,
where they who are unfaithful to the Lord cannot come.`'
I was well nigh my last breath, but the Lord loosed my tongue,
that I might declare of his goodness.`'

Again he said, '`The Lord in my healthful days did put his living word in my heart,
and though I have been by some looked upon as a stripling,
and as one that knew not much of the things of God,
yet my soul has had many sweet seasons and opportunities.`'
Again he said, '`I have a very good wife, faithful and loving to me,
and three sweet children; call them, that I may kiss them before I die,
for my time here will not be long.`'
So they brought one of his daughters to him, and he said, '`You are Elizabeth,
my youngest daughter, '`and kissed her many times.
He farther said, '`Silver and gold I have not much to leave you;
you have hitherto been a good child; the blessings of the living God rest upon you,
and the blessing of me, your dying father, be with you also.`'
So then he took his son, and said, '`You are Roger, my sweet son.
In you I have taken great delight; yet now your father is about to take his last breath;
and that which I desire of the Lord, is, that he will bless you and your two sisters,
and bless you all, that you may keep up my name, and live as your father has done.
Though I have not filled up the number of many years, yet I, your father,
do witness peace with God.`'
Being pretty much spent, he said, '`The Lord bless you, my son, and your two sisters;
the blessing of your father be with you all;`' and so kissed him many times,
and let him go.

Then he called for his daughter Alice, and said, '`You are Alice, my first born,
and I love you well.
It has been real and true; and though some men can show it more, yet I love you all well,
and I hope the Lord`'s care will be over you when I am dead and gone;
and I believe you will not lack.
Alice, (said he) kiss me, for you must never kiss me more: '`so clasping her in his arms,
he kissed her, and bade her farewell.
And then said, '`I have now made an end of what lay upon my mind; therefore, everlasting,
living, pure, invisible God, into your hand of power I recommend my soul.`'
He lay still and quiet till a little before his departure,
when the very pangs of death seized on him; then were his sighings many,
yet had the savor of life in them.
Afterwards he lay still and very quiet, rejoicing in his spirit, and said,
'`My soul does magnify the Lord, and my spirit rejoices in God my Savior,
who has saved me from sin; but what shall I say to the rebellious?
If they will serve the devil, they will have a bad portion in the end.`'

He said, '`Though there may some of all persuasions find salvation, yet that people,
in scorn called Quakers, who are really faithful to God, are satisfied in God,
and they know salvation to their immortal souls, having been redeemed by Jesus Christ,
who is come to save many.`'
He prayed for his brother and sister, saying, '`Lord,
you know I have one brother and sister,
who are not in that faith in which I am about to lay down my head.
Lord, bring them to it, if it be your blessed will, and confirm them in the same,
that they may receive that blessed reward you have made my soul a witness of.`'
And said, '`So my strength now failing, as to my outward man,
I once more recommend my soul into your hands, Lord Jesus Christ.`'

He departed this life the 5th day of the Fourth month, in the year 1688,
aged about thirty-three years.

[.asterism]
'''

THOMAS JANNEY was born in Cheshire,
and received the blessed truth at the first preaching thereof in that county,
which was about the year 1654, being then in the twenty-first year of his age.
The next year he received a gift in the ministry, preaching the gospel of Christ freely;
and travelled into many parts of England and also in Ireland,
and had a fervent and sound testimony for truth;
and his conduct and course of life accorded with his doctrine.

In the year 1683, he with his family went to Pennsylvania, and there settled,
where he stayed about twelve years; and in the year 1695,
he came over again in company with his friend Griffith Owen, of Pennsylvania,
to visit his brethren in England: and after he had stayed some time in London,
he went into Cheshire in the Sixth month of the same year,
where he had many relations who were faithful friends; and though they were dear to him,
and their houses might have been his home, yet he rested little,
but visited the meetings of Friends in several neighboring counties.

The next spring he travelled through several counties where he had been in former years;
and as he had a desire to see the brethren at the yearly meeting in London,
he was there at that time; soon after which he was taken so ill,
having decayed in his natural strength before, that his recovery was much doubted;
and some advised him to go out of the city for the recovery of his health.
After some time he adventured by short journeys from London to Enfield, so to Hertford,
and from there to Hitchin, where his distemper increasing he could go no further,
having a purpose to go for Cheshire.
At Hitchin he lay a considerable time at the house of our friend William Turner;
and friends there were careful and tender over him;
and he having endured much hardship formerly in the service of truth,
by traveling into several climates, and enduring heats and colds,
his body was attended with much pain, so that few expected his recovery.

Two of his relations, who were friends, came from Cheshire to Hitchin to visit him,
and one of them being with him in his chamber, he said to this effect: '`Cousin,
I am glad that you are come.
I hardly expect to recover so as to be able to get into Cheshire.
It is some exercise to think of being taken away so far from my home and family,
and also from my friends and relations in Cheshire.
I would gladly have got down into Cheshire; but I must be content,
however it pleases God to order it.
Worse things have happened in this life to better men than I am.
I shall be missed in America; friends there were troubled when I came away.
I have labored faithfully among them; they will be grieved at the tidings of my death.
My family will miss me.
My care has been for my sons, that they may be kept in the fear of God.
I have been a good example to them.
I have a care upon me, that they may be kept humble while they are young,
that they may bend their necks under the yoke of Christ.
If I am taken away, I am very clear in my spirit.
I have answered the requirings of God; I have been faithful in my day,
and I have nothing that troubles my spirit; my spirit is very clear.`'
He also expressed his concern for his brethren in the ministry, especially the young,
that they might observe the leadings of God`'s spirit in their ministry,
and not lean upon their own natural parts, which, he said,
occasioned various inconveniences;
of which he spoke particularly in the time of his sickness.

After this, the Lord answered his desire, that he recovered,
so as to be able to get down to Cheshire to his relations there;
and he got abroad to some meetings that winter, but yet was weakly in body; and,
towards the spring, he made preparation to get home to his family in Pennsylvania;
but before the ship set sail, his distemper, which had not quite left him,
returned sorely upon him.
He went to his sister`'s, near where he was born,
and she spoke something to him about his family; but he said little,
only these words;`' If it be the will of God that I be taken away now,
I am well content;`' which was the most he said in his last illness,
save to a Friend concerning his burial.

He departed in much quietness of mind, the 12th of the Twelfth month, in the year 1696,
and was buried the 15th of the same, in Friends`' burying-place, in Cheshire,
aged sixty-three years: having been a public minister forty-two years.

[.asterism]
'''

HENRY STOUT, of Hertford, born at Ware, in the county of Hertford, in the year 1631,
was convinced of the blessed truth by the ministry of a woman, in the year 1655,
being then about the twenty-fourth year of his age.
At which time some of the people called Quakers came into that part of the county,
concerning whom he had heard evil reports, and that they denied the Scriptures;
which had prejudiced his mind against them.
But it so happened that there came a woman called a Quaker, and preached in Ware market;
and afterwards a rude rabble followed her down the street, and he seeing them,
followed her also, in pity towards her, and to rescue her from them.
But she turned into a house where there was a meeting; and a Friend was speaking there,
unto whom he listened, and heard him speak much Scripture,
although he named neither chapter nor verse; at which he wondered,
because he had heard that they denied the Scriptures.

After he thus lent an ear, the woman stood up and spoke;
and such a power attended her ministry, that his spirit was much broken,
and astonishment seized on him; and he saw others also with paleness of face,
and they smote their hands.
This brought great fear upon him, lest he should be deceived;
yet was he afraid also that he should offend God, and resist the day of his visitation.
This brought great sorrow upon him for a time, he not being able to distinguish;
but afterwards going to another meeting, he heard another woman,
by whose preaching his convincement was increased; and he was so confirmed,
that he could set to his seal that it was the very
truth which had long been veiled in him;
but now, by the preaching of the gospel, was revealed.
He could say, Christ was come, and he looked not for another;
and it was confirmed by the work that was wrought both within and without.
First, within, the eye which had been shut was now opened,
and the ear that had been deaf, now heard, and the mouth of the dumb could speak,
and the lame could walk, and the mysteries of the kingdom of God were known,
which before were in parables.

He searched the Holy Scriptures, and found it was the good old way,
though new to him and others;
and the Scriptures were opened by the spirit that gave them forth,
and a witness for God he had in himself, according to John 1:10-5. "`He that believes,
has the witness in himself.`"
Then he took up the cross and denied himself, and so became a gazing stock to the world,
as the Lord`'s people were in those days, as well as in former ages.
Soon after he was moved of the Lord to go to the public places of worship,
to declare against them, and to preach the truth.
Persecution and sufferings soon followed;
for many and various were the trials and exercises which
the Lord`'s people went through in their day.

He was the first called a Quaker who suffered imprisonment in Hertford jail,
for the testimony to the truth; where his sufferings were great,
the prison-windows being shut, that he might not have the benefit of the air,
or the light of the day.
After he was released of that imprisonment,
he was a prisoner five times more in that town of Hertford;
the last of which he was sentenced for banishment,
and continued a prisoner nearly eight years, to the great detriment of his health,
being often put into the common jail;
which trials the Lord carried him through with much patience,
contentedness and quietness of mind, he being given up to the will of God.

He was a serviceable man in many respects,
and willing to do what offices of love he could for any.
He travelled pretty much in the service of truth in his younger years,
while he had strength of body, but some time before his death, distempers grew,
and weakness increased upon him, which made him incapable of being much from home.

The last four months before his death, he went little abroad, but grew weaker and weaker;
the which his wife perceiving, did much importune him to advise with some doctor;
but he answered her thus, '`I would not have you confide too much in doctors,
for they will all prove physicians of no value to me.
I thank God, I know that power which in former ages raised the dead,
and healed all diseases; and if it is the will of God, he can restore and heal me;
if not, I am satisfied; his will be done.`'

His greatest infirmity was a stoppage at his stomach, and shortness of breath,
which often brought faintings upon him; but he bore all with great patience.
And when some friends came to visit him,
he told them his weakness was such that he thought he should hardly recover it;
but however it pleased God to order it, he was fully satisfied:
for he had this testimony, that he had served the Lord with faithfulness,
and with an upright heart, to the best of his knowledge: with more to that effect,
which cannot be well remembered.
At another time to a friend that came to see him, he said,
'`None know the virtue and goodness of truth so well
as when they draw near their latter end,
when all outward comforts fail, and are leaving them,
and sickness and weakness come upon them.`'

He further said that he had travelled in the service of truth in former years,
when he had strength of body,
and the Lord had given him many living testimonies to bear for his name;
in all which he was faithful, and the remembrance of it warmed his heart at that time;
for he could say that his care was,
not to speak more than what the Lord gave him to speak,
that thereby his name might be honored.
Many times, and upon several occasions, he so expressed himself,
as fully manifested the true satisfaction and peace he had with the Lord;
often desiring to be dissolved, that he might go home to his rest.

The Lord`'s love and gentle dealing appeared very largely towards him,
in giving him many times ease of body, and comfortable seasons of refreshment;
and he generally rested well in the night, till about a week before his death.
The sense of it would often make him break forth
into praises and thanksgiving to the Lord,
for his goodness and mercy to him in the night-season.
When he awaked out of his sleep, and when his sleep was taken from him,
he continued quiet, patient, and sensible to the last moment.
And when his wife saw that he slept little, and took little,
hardly enough to keep him alive, she was full of grief; which he perceiving, said to her,
'`You must give me up, for I shall not long continue here:
but it will not be long before you and I shall meet again in that blessed state,
where all tears shall be wiped from our eyes.`'

He kept his bed but four days; and the day before his death, his children being by him,
he said to them, You, who are likely to enjoy what I have,
I would have you to remember the advice of your father when I am gone,
and live in the fear of God, and as it becomes the truth; then you will be as monuments,
when I am gone, and it will go well with you, and what I leave will be a blessing to you.
Beware of earthly-mindedness, and pride, and prodigality,
which is a dishonor to any family; and bring up your children in plainness,
and not in the fashions and superfluities of the world, which passes away.
Remember my advice, who speak to you in love: for woe will be to the wicked.
I would say more to you, but my strength fails.`'

The day he died he spoke little, but lay as if he slept;
but sometimes fainting fits would come,
that it was thought he would have gone away in one of them; but he did not,
but fell into a slumbering; and when he awaked,
he desired to be turned on the other-side, and then he stretched out his hands and feet,
and said, '`Now I am going to the Lord;`' which were the last words he spoke:
and so departed in peace, without so much as a groan or sigh.

Thus he finished his course, and laid down his body, the 6th of the Tenth month,
in the year 1695, in the sixty-fifth year of his age.

[.asterism]
'''

THOMAS ALDAM, of Warnsworth, in Yorkshire,
received the glad tidings of the gospel of life and salvation very early, that is,
in the year 1651, by the preaching of that eminent and faithful servant of Christ Jesus,
George Fox, soon after he was delivered out of the dungeon in Derby prison.
At this time, Thonlas Aldam, John Kellam, Thomas Kellam, Richard Farnsworth,
Thomas Goodyear, and several others of note, received the truth; and many sufferings,
beatings, reproaches, spoiling of goods, and imprisonments he endured,
for Christ`'s sake and the gospel`'s; being often concerned to go into marketplaces,
and public places of worship, bearing testimony against the wickedness of the world,
and against such teachers and leaders as caused them to err, through lightness, pride,
and covetousness.

Before he was convinced,
he was a great follower of the priests and teachers of those times,
but his hungering and thirsty soul not being satisfied among them, he left them,
and waited as alone, until it pleased the Lord to send his servant George Fox,
as aforesaid, into those parts of the country.
And he having received the truth, was valiant for the same upon earth,
and gave up his strength and substance to serve the Lord.
He was very zealous and fervent in spirit, severe against evil,
but tender to the least appearance of that which was good,
watching over his children in the fear of God; given to charity, and to do good to all.

He was one of the first called a Quaker,
who was imprisoned in York Castle upon that account, in the year 1652.
It was for going to Warnsworth steeple-house, and speaking to Thomas Rookbey,
a priest of that place, who procured his imprisonment at York,
where he was kept two years and six months so close,
that he was not permitted once to come home, nor to see any of his children;
and sometimes not permitted to see his wife and relations when they went to visit him.
He was also fined during that imprisonment £40, at the assizes,
for appearing before the judge with his hat on his head,
and for speaking thee and thou to him.

During the aforesaid imprisonment, his adversary Rookbey, the priest, and one Vincent,
an impropriator, sued him at the law for treble damages,
and they made spoil of his goods to the value of £42;
not leaving one cow to give milk for his young children and family.
Thus he suffered for his faithful testimony to the
coming of the Lord Jesus Christ in the flesh,
and for his free ministry;
at other times also he suffered the loss of goods for his testimony to the truth.

As he had been a sufferer himself, so he had a tender sympathy for the Lord`'s people,
his brethren, who were sufferers for the truth,
and would go oftentimes to Oliver Cromwell, and others, the rulers of those times,
and lay the sufferings of Friends before them.

He also travelled into Scotland and Ireland,
and went to the chief rulers there upon the same account.
He went to all, or most of the prisons in England,
where there were any of the people called Quakers,
to take a perfect account of their sufferings,
that he might be the more capable to advocate their cases before the government,
being ready at assizes, sessions, or elsewhere, to plead the cause of God`'s people.

He had a tender regard to love and unity among brethren,
bearing good esteem in his mind for such as labored in the gospel.

When he was about to undertake any journey upon truth`'s account,
he would call his family together,
and in much humility pour out his supplication to God to preserve them.

After thus having served his generation in faithfulness, he was visited with sickness,
in which time he set his house in order; and in the time of his weakness,
the Lord was good to him, and eminently appeared with him, so that he said to his sister,
near his latter end, that he found his strength so renewed,
that he believed he could get to London if the Lord required it: but he answered again,
'`I am clear of the blood of all men.
I find nothing to this man,`' meaning king Charles the Second,
then lately restored to his kingdom.

He was very sensible of his latter end; and the day he died he called for his children,
and exhorted them to live in the fear of God, and to love and obey their mother: and so,
being freely resigned into the hands of God his Creator,
he departed this life in the Fourth month, in the year 1660.

His wife, Mary Aldam, survived him but three months.
She was a woman fearing God, and served him in her generation.
In all the exercises which her husband passed through in those early days,
she never was heard to grudge or repine,
but was given up in all things to God`'s disposing.
Her remembrance is sweet,
and her name to be recorded among the faithful of God`'s people.
She received truth by the ministry of George Fox, at the same time her husband did,
and bore testimony to the same truth, according to her measure.
He had also two sisters, faithful women.

[.asterism]
'''

MARGARET KELLAM, who was convinced about the year 1651,
travelled much in truth`'s service in the breaking-forth thereof,
and many were convinced by her.
She also suffered imprisonment for the same at Exeter, York, and Banbury in Oxfordshire;
and great was the courage that attended her in preaching truth in the streets, markets,
and public places of worship, and to the rulers of the people;
and the Lord was with her.

She finished her course in faith,
signifying before her departure the great peace she enjoyed with the Lord,
and the clearness of conscience she had before him.
And so departed this life in the year 1672.

[.asterism]
'''

JOAN KELLAM was also a woman that truly feared God, and a good example where she dwelt:
she was of sound judgment, and well experienced in the work of the Lord;
zealous for his honor, and faithful to the truth; an encourager of virtue,
and watching over the young, and an instructor of them in the right way of the Lord.
She could speak a word in due season to an afflicted soul,
having passed through many states, and seen the wonders and goodness of the Lord therein;
and was as a mother in Israel.

In the time of her sickness she was well disposed,
and gave good advice to them she left behind her,
that they might persevere in faithfulness,
to the finishing of that work which the Lord had for them to do.
So departed this life in the year 1681.

[.asterism]
'''

SARAH BROWN, wife of Capt.
Brown, of Leicestershire, and mother to Samuel Brown, physician in the town of Leicester,
was one who in her young years fervently and sincerely sought the Lord,
and frequented the assemblies of the best sort of people in that day, called Puritans;
afterwards she joined herself to the Baptists, among whom she walked inoffensively.

But when it pleased God to raise up his people called Quakers,
in the northern parts of this nation,
and gave some of them commission to publish the way of life and salvation,
she received their testimony with great joy and thankfulness
to the Lord and was a nursing mother among that people.
Her husband, at her request, gave up his house for Friends to keep meetings in,
even at the breaking forth of truth in that day:
and she counted nothing too dear to part with for
truth`'s sake and was a good example in conduct,
in temperance, meekness and charity, towards those with whom she was concerned.
She was a true wife and a tender mother, a loving relation,
a good neighbor and firm friend.
She had a word of comfort in due season to many when in afflictions;
she loved to visit the widow and the fatherless, the prisoners,
and the house of mourning; and to feed the hungry, and clothe the naked,
and to wash the saints`' feet.
She suffered imprisonment, and spoiling of goods for the truth`'s sake,
counting all as dross and dung, that she might win Christ.

When death came she received it with contentedness,
being given up to God`'s good will and pleasure, and she lived to old age.

A friend visiting her in her last sickness, said to her,
'`The Lord has sent his messenger`' (meaning, that her end was at hand); she made answer,
'`He is come;`' and desired the Lord to give her an easy passage.
She was first taken ill in the night with a violent pain in her legs,
and her son Samuel Brown being presently called,
she prayed to the Lord to mitigate the violence of her pain,
and to give her strength to bear his hand with patience.
Her son was much grieved for her; which she perceiving, said, '`Child, do not do so;
rejoice and be glad, for you have no other cause.
You have been a dutiful and loving son to me, even to the full.`'
The Lord answered her prayer; and in a short time took away the violence of her pain;
and she praised the Lord, and blessed his name, for his mercies and goodness;
speaking of his great mercy and favor to her all her life long,
to the great comfort of her children about her; and blessed her son, saying,
The Lord bless you and yours, for your love and duty to me;
for I do rejoice that you were born unto me.`'
Also to her son`'s wife she said, '`Daughter, you did promise to take care of me,
when weakness should approach; and now you are as good as your word:
the Lord bless you and yours, for all your love to me.`'
And in the sense of the love of the Lord to her she prayed, '`O Lord,
guide your poor hand-maid into your everlasting kingdom,
where I may sing hallelujahs to you forever.`'

She gave order, two days before her departure,
(being sick but six days) to be buried at Leicester, by her grandchildren;
and so died in a good old age, at her son, Samuel Brown`'s, at Leicester,
on the 30th of the Ninth month, in the year 1693, aged eighty-three years.

[.asterism]
'''

WILLIAM WALKER, an inhabitant of Pennsylvania, born in Yorkshire,
but convinced in Pennsylvania,
was one who bore a living testimony to the truth of God in the assemblies of his people.
He came over to visit his friends and brethren in England,
about the latter end of the year 1693, in company with other Friends from those parts,
which was about the time George Keith came over from America.
This our friend often expressed his great sorrow for George Keith,
and the sore exercise and trouble he gave to friends in America,
by his contention and jangling;
and he had a testimony against that spirit but a few days before he died,
that God would judge it.

After he had visited friends about London, he went into several counties,
and also into Wales; and returned to London,
in order to be at the yearly meeting in 1694;
a little before which time he was taken sick there,
and endeavors were used for his recovery, but they proved unsuccessful.
In the time of his sickness he was often filled with
the love and power of God in his soul,
to the comfort of those present.
Observing some to weep, he said, '`Weep not, dear hearts, lest you trouble me.`'
Afterwards he said, '`the goodness of the Lord!`' And lifting up his hands, he said, '`Lord,
you are altogether able to do wonderful things!
You shall be my physician.
Oh the wonders of the Lord!
What have I seen of the transcendent glory!
Though I see but a little, yet it is admirable glory.`'
Again he said, '`The old enemy would have had me let go my hold; but I said,
I have an interest in you, and I will hold you, Lord.`'

Those about him being desirous that he might recover, he said, '`No,
I have no promise of life.`'
Speaking of Christ, he said, '`I can see him; his arm is open to receive me.`'
After some time he said, '`The Lord is a physician indeed, a physician of value.`'
Another time he said, '`We must all double our diligence, '`Another time,
lying in a still frame of mind, he sang in sweet melody as follows:
'`His compassion fails not; he waits to be gracious: Oh the wonders of the Lord!
The wonders of the Lord in the deep.`'
Another time he said, '`My faith is steadfast in the dear Son of God;
that although I am under great weakness and afflictions,
yet in the strength of my Father`'s love I shall be
enabled to stand against the mists of darkness.
The enemy would eagerly unpin my faith:
God`'s people are always preserved while they wait still at home.
Oh! Lord Jesus Christ!
I will hold you fast; your compassion fails not.
Oh! sweet Jesus Christ, I have great cause to hold you fast.
Oh! sweeten death unto me!
Oh! your sweet presence!
In it there is life.
Oh!
Lord, give me strength; I will not let you go: you have regard to them that fear you,
your compassion fails not; you are at my right hand to uphold me.
Oh! my Savior! you are at my right hand to save me; your compassion fails not, O Lord.`'
Afterwards he said, '`Oh!
Lord Jesus!
Come, sweet Jesus, I long for you; now death is pleasant.`'

His wife`'s sister being by him, he said, '`Fear the Lord God.`'
She said, '`Would you +++[+++say]
any thing to your wife.`'
He answered, '`My dear and tender love in the Lord Jesus unto her,
and to all my dear friends everywhere; and that you may double your diligence,
to your soul`'s comfort, the days you have here.
My dear love to our dear friends in America, where I have been sweetly refreshed,
and had many good meetings among them.`'
After a little repose, he said, '`Oh!
Fountain of Life!`' Then stopped, and thus spoke again,
'`I cast the care of my dear wife and children, if living, upon the Lord; I trust in him.`'
After some rest, he said, '`Lord Jesus Christ, come, receive my poor soul: come,
O my soul`'s beloved!
Come, Lord, I long for you.
Lord Jesus Christ, if there be any iniquity in me, search it out.`'

Afterwards he said, '`I feel the angel of your presence to surround me: come,
Lord Jesus Christ, come, come, receive my soul into your bosom.`'
Again he said, '`Come, Lord Jesus Christ, let me entreat you come away,
and receive me out of all sorrow; come away, my Lord.
After a little time he said, '`I feel the Fountain of Life; my soul`'s beloved, is come.`'
He died in peace with the Lord, as those then present can testify,
that he was in a sweet, heavenly frame of spirit when he drew his last breath,
which was on the 12th of the Fourth month, in the year 1694, at the house of John Padley,
in Olave`'s Parish, Southwark.
