== Chapter 8

[.chapter-synopsis]
* Ruth Middleton
* Alexander Jaffray
* Mary Padley
* Charles Marshall
* Sarah Padley
* William Garton
* Charles Ormston
* John Ormston
* Thomas Robinson
* Stephen Smith
* William Allen
* William Simpson

RUTH MIDDLETON, daughter of Samuel Middleton and Rebecca his wife,
was visited with a consumption in the Tenth month, 1700,
and continued in much weakness of body till the 16th of the Fifth month, 1701.
During her sickness, these expressions, among others, were observed.

One time, her mother being much concerned to part with her,
the child lying still as if she was in a slumber, opened her eyes and said,
'`What`'s the matter?
What`'s the matter?
My dear mother, do not be troubled for me; do not sorrow for me, I shall be happy.
It is the Lord`'s will that I am thus afflicted, and we must be contented.
You know that Abraham was willing to offer up his only son Isaac;
and you do not know if you could freely give me up,
but that the Lord might spare me a little longer to you;
and if it be his good pleasure to take me to himself, his holy name be blessed forever.`'
Another time her mother said, '`How are you now?`'
She replied, '`But indifferent; but I am well satisfied,
for it is the will of God that I am thus afflicted.
Oh! my dear mother, I would be glad if you could freely give me up.`'

One time, going to slumber, she prayed thus: "`Our Father who art in heaven,
hallowed be your name, your kingdom come, your will be done in me,
as it is in heaven.`"'`Oh! sweet Lord Jesus,
feed me daily with the bread that comes down from heaven.
Lord, if it stand with your will, grant that I may sleep to refresh this poor needy body:
but you, Lord, know what I stand in need of, better than I can ask.
Lord, be with me, and my father, and mother, and brother.`'
Thereupon she went to sleep: and when she awoke, she said,
'`Oh! blessed and praised be your holy name,
O Father of life! for you have heard my desires, and have answered me;
for I have slept sweetly.`'

Another time she said, '`The Lord said to his followers,
"`Permit the little children to come unto me, and forbid them not,
for of such is the kingdom of heaven.`"
And if I be not happy, what will become of ungodly men and women?
For truly I am afraid of offending anybody, for fear I should offend the Lord.`'
One time she said, '`Pray, mother, have a strict eye over my brother,
for he is very full of play.`'
A friend, after inquiring how she did, said, '`I hope your eye is still to the Lord:`'
her reply was,
'`Although I can hardly speak, I think upon the Lord,
and he knows my thoughts, and answers them;`' with more sensible words.

Another time she said, '`It will not be long before I shall be at rest and peace,
where there is no more pain to the body nor to the mind;
and where there is nothing but joy forevermore.
Dear mother, be willing to part with me, for I am willing to part with you all.
I am not at all concerned for myself, but for you, poor mother,
who does and will make your bed a bed of tears often for me.`'

Hearing her mother question her recovery, she said, '`Oh! what the Lord pleases;
for I am not afraid of death.
I never wronged anybody of a pin to my knowledge, nor loved to make excuses.
I never told a lie but once; when I should have said yes, I said no:
that has been a great trouble to me; but the Lord, I hope, will forgive me,
for I called the maid, and told her the truth.`'

Near her end she desired to come out of the country to London, and said,
'`The air does me no good, and the doctor does me no good:
the Lord is the same at home as here.`'
And when she was removed home, she said, '`Now I am glad;
if I die it is better to be here, and will save a great deal of trouble.`'

A Friend asked her if she was willing to leave father and mother, and go to the Lord;
after some pause she answered, '`If the Lord please,
I am willing this very minute to leave all, for I shall be happy.`'

The night before her departure, after a Friend had prayed by her, she said,
'`I do understand well, and am inwardly refreshed.
I am sorry that I cannot speak so that the Friend could hear,
or else I would give an account of my inward peace with the Lord.`'

A few hours before her death she thus prayed, but her voice was very low: '`Oh,
Lord! withhold not your tender mercies from me at the hour of death.
Oh, Lord! let your lovingkindness continually preserve me.`'
Afterwards she said, '`I desire to slumber; but if I die before I wake,
I desire the Lord may receive my soul.`'

She was thankful for the tender regard her mother had to her, and with a low voice said,
'`Farewell, dear mother; in the love of the Lord, farewell.`'
And then desired to see her father and brother; and feeling for her brother`'s face,
she stroked him and said, '`Farewell, be a good boy.`'

Her father asking her how it was with her, she replied, '`am just spent,
but I am very easy, and shall be very happy. My body is full of pain,
but the angel of the Lord is with me,
and his presence will forever preserve me;`' and so kissed her relations,
and bade them all farewell.

Her last words were her desire to be remembered to
the Friends who visited her in her sickness;
and, in less than half a quarter of an hour, like a lamb she departed this life,
on the 16th of the Fifth month, in the year 1701, being eleven years, two months,
and four days old.

[.asterism]
'''

ALEXANDER JAFFRAY, of Kingswell, in the north of Scotland, born in the city of Aberdeen,
was one who early remembered his Creator;
and as he grew in years he increased in a religious concern towards God,
and those who he thought feared him.
He joined, when young, with the Presbyterians,
though he was educated in another form of religion; but some time after,
when those people got into rule and government,
they forgot their former low and persecuted condition, and grew high, rigid,
and fierce persecutors of others; therefore he soon disliked them,
and signified the same to some of the chiefest among them,
having been himself one of those commissioners who were deputed by the
nation of Scotland to treat on articles with King Charles the Second,
then in Holland, in the year 1650.

After he left the Presbyterian way, for some time he was among the Independents,
and finding them also to be for setting up themselves, and persecuting others,
he could no longer follow them.
After this he remained in private for some years, a solitary mourner,
not joining with any profession in religion;
nor allowing several of his children to be sprinkled or baptized (as they called it),
because he could not own their way of constituting national churches;
and this was long before he was called a Quaker.
In his solitary retirement he sought the Lord,
waiting for a people who were spiritually touched with a divine coal from the altar,
to kindle true and spiritual sacrifices to God.

When he first heard that God had raised up such a people in England,
who directed all to God`'s pure light, spirit and grace in their own hearts,
as the most sure teacher and leader into all truth, worship and religion,
he said he felt his heart to leap within him for joy.
After weighty examination concerning the people called Quakers,
who preached the truth among them, he found his heart and soul united to them.
This was in the year 1662,
a time when it was as bitter a cross even as death to own them,
especially to one of his repute; and shortly after, several more men of note,
in that nation, were convinced of the same way of truth,
as John Swinton in the southern parts, David Barclay, Alexander Skein, Thomas Mercer,
and others.

This made the priests and others persecute them; but they stood their ground,
through the grace of God, and boldly bore their testimony valiantly,
particularly Alexander Jaffray,
contending for the truth in solemn conferences with the bishop of Aberdeen,
and the chief preachers of that city.

He was faithful in his testimony to the truth to the last;
and in his sickly old age was imprisoned many miles from his own house,
for non-payment of tithes.
It is remarkable that, a little before this imprisonment, being near to death,
as was judged by all who saw him, he signified under his hand,
being altogether unable to speak, by a great swelling in his throat,
that his God had yet a service for him to do, in suffering for his precious truth;
and that he was not to die at that time.

He was taken sick the latter end of the Fourth month, 1673;
and during the twelve days of his sickness,
he uttered many living testimonies to the blessed truth, before many witnesses,
both Friends and other people, who visited him; and a few of them are as follows:

He said that "`it was his great joy and comfort in that hour,
that ever he had been counted worthy to bear a testimony to, and suffer for,
that precious testimony of Christ Jesus,
his inward appearance in the hearts of the children of men, visiting all by his light,
grace and spirit, that convinces of sin; and that it was,
and would be the great judgment and condemnation of many in this nation,
particularly of the professors, that they have so slighted and despised, yes,
hated the said light and witnesses thereunto.`"

Sometimes being overcome in spirit, he said, '`Now Lord, let your servant depart in peace,
for mine eyes spiritually have seen, my heart has felt, and is feeling,
and shall ever feel, your salvation.`'

He also prophesied of a great and near trial shortly to come,
wherein some that were not what they seemed to be, should be discovered and fall;
but the upright and lowly ones, the lowly shrubs should be preserved,
when tall and sturdy oaks should be overthrown; which is since fulfilled upon some.

He farther said, that the Lord had given him the garments of praise,
instead of the spirit of heaviness.
Sometimes, when very sick, he would bless the Lord,
that now fighting with a natural death, he had not an angry God to deal with.
'`Oh!`' says he, '`the sting of death is fully gone, and death is mine;
being reconciled to me as a sweet passage, through him that loved me.`'
Another time, seeing the candle almost out, he said, '`My natural life is near an end,
like that candle, for lack of nourishment or matter to entertain it;
but in this we shall differ, that if it be let alone, that goes out with a stink,
and I shall go out with a good savor, praises to my God forever.`'

A little before his breath ceased, he said he had been with his God,
and had seen deep things;
about which time he was filled with the power of God in a wonderful manner,
which much affected those present, and in a little time after, he died like a lamb,
being the 6th day of the Fifth month, in the year 1673, aged fifty-nine years;
and was buried in a piece of ground set apart near his own house at Kingswell,
the 8th of the same month.

[.asterism]
'''

MARY PADLEY, wife of John Padley, timber-merchant, of Olave`'s, Southwark,
was a woman adorned with truth and innocency, chaste, upright, and sincere-hearted,
industrious, yet void of covetousness, so that virtue shone forth in her conduct.
She was also charitable to the poor, plain in apparel, adorning the truth in her conduct,
punctual in performing her promise, and in the discharge of any trust reposed in her.
She spent her days in the fear of God, so the Lord was gracious to her at her death.

She was taken with pains, the 6th of the Seventh month, 1695, at which time she said,
in much tenderness and fervency of spirit, '`My God, and my father, deliver me.`'
And after she was delivered, she praised God for his mercies towards her:
and afterwards being asked by her husband how she did,
finding some unusual symptoms attend her, she answered, '`Weak, but well satisfied.`'
And as a confirmation thereof, she broke forth into sweet praises to the Lord; and died,
leaving behind her four young children.
Aged about twenty-eight years.

[.asterism]
'''

CHARLES MARSHALL, born at Bristol in the year 1637,
was religiously educated by his parents in the Independent way.
In his tender years he had inward desires after the knowledge of God.

After he had continued some years among the Independents, and also the Baptists,
he grew more and more dissatisfied with the empty and lifeless
profession of those among whom he walked.
He spent much time in retirement alone in the fields,
under a sense of his state and condition, crying unto the Lord,
and seeking after his saving knowledge.
In this state he continued,
until it pleased God to send to that city his faithful servant John Audland,
from out of the north of England,
by whose powerful ministry he was turned to the light of Christ Jesus in his own heart,
which had before discovered his state and condition to him.
After he came to turn in his mind to the light of the Lord,
and was thereby and therein resigned, he witnessed God`'s pure power,
love and life to break in upon him; and after manifold exercises and troubles,
was raised up a powerful minister of Christ Jesus,
and an instrument in God`'s hand to turn many to righteousness.

He was moved in the year 1670 to go through the nation of England,
and visit God`'s heritage, which he did within the compass of one year;
and although it was then a time of great persecution,
yet in all his passage through cities, towns, and all the counties of the land,
no man was allowed to lay hands on him, or stop his way.

He continued a faithful minister,
and labored much in the gospel to the time of his sickness, which lasted several months;
in all which time great patience and meekness appeared in him,
although under weakness and affliction of body.

He had some sight and knowledge of his end;
for a little before he was taken ill he earnestly pressed
a particular friend of his to ride out of town with him,
having something of moment to impart to him.
When they were a few miles from London, he said, among other things,
that he was satisfied his departure drew near,
and therefore had a desire to discourse with him
about some particular things before he died.
And when he was taken ill he sent for the same friend,
and told him now he was satisfied he should go abroad no more;
although in his first illness there was no such appearance to others,
which the said friend told him; but whatsoever he said to take him off of such thoughts,
it had no impression upon him; he continued fixed in his mind,
that he should die of that illness.

Several of his friends pressed him to go into the country,
but he desired only to go to John Padley`'s, a Friend that dwelt near the river side,
which he much liked; and at his first going there he was a little better,
but soon altered again.
He lay ill there about three months, under great weakness;
and several Friends often came to see him,
and he would be frequently giving them seasonable counsel and advice,
in many heavenly expressions, and would often exhort them to keep in love and unity,
and to the living divine power and life of truth,
that thereby they might be kept a people fresh and green, and living to God,
that so formality might not prevail over them.
He pressed that a great regard might be had of the poor,
and that some way might be found out for their employment; often saying to this effect,
that in an inexpressible manner he felt their sufferings, by reason of their poverty.
Indeed he was a man who greatly sympathized with
those who were afflicted either in body or mind,
being of a very tender spirit.

A little before his departure, he sending for John Padley and his wife into his chamber,
said to him, '`Dear John, do what you can for the honor of truth,
and the Lord bless you and yours for generations to come.`'
To his wife he said that he desired the Lord might be with
her when she came to such a time as that he was then in,
i.e., a deathbed, and make her passage easy; and his desire was granted,
for she died in less than a year after; and said, on her dying bed,
that the Lord had answered dear Charles Marshall`'s request, for she lay very easy,
and freely given up.
As he lay in this weak condition he was often opening his mind to several of his friends;
particularly when several ministering Friends came to see him, he spoke to this effect:
'`I have loved the brotherhood;
I have sought the unity and peace of the churches for these forty years,
and to my great comfort I never did any thing tending to the breach thereof.
I have two things that lie upon me to Friends,
which I desire may be communicated to them.`'

'`The first is,
that they gather down into the immortal Seed and Word of life in themselves,
and be exercised in it before the Lord,
and duly prize and set a value upon the many outward and inward mercies, and blessings,
and heavenly visitations, that the Lord has eminently bestowed upon them,
since the morning of the day of his blessed visitation;
then shall they grow and be preserved in a living freshness to him:
and the Lord will continue his mercies to them,
and they shall not lack his divine refreshing presence
in their meetings together before him.

'`The second thing is, that those Friends to whom the Lord has given great estates,
ought to cast their bread upon the waters, and do good therewith in their lifetime;
for those who are enjoyers of such things should see that they are good stewards thereof.
Oh! the many poor families that such persons might be a help to! how easily might they,
with a little,
assist many a family to live in the world! and what a comfort would it
be for such to see the fruits of their charity in their lifetime.`'

When our friend George Whitehead came to see him, with much tenderness of spirit,
he signified his great peace and satisfaction, and that he always, from the first,
had an honorable esteem of the unity of his brethren.
A little before his departure,
when our friend William Penn and several others visited him,
he lay as a man gathered up in his spirit unto God; and though he was almost spent,
his voice being very low, hardly to be heard, yet by what was understood,
it might be perceived that he had in possession the earnest of
that blessed peace which he was going to receive the fulness of.
The observation of his peace, and happy condition, much affected those present.
He departed like a child, in a quiet frame of spirit, the 15th of the Ninth month,
in the year 1698, aged sixty-one years,
and was buried from Grace-church-street meeting-house, in Friends`' burial ground,
near Bunhill-fields, London.

[.asterism]
'''

SARAH PADLEY, second wife of John Padley, aforesaid, of Olave`'s, Southwark,
was a woman of a meek and quiet spirit, and had great sympathy with those in affliction;
and bore a public testimony for God in the assemblies of his people,
and she had an honorable esteem of the faithful elders in the church.

She was taken ill the 26th day of the Fifth month, 1699,
and was sensible her end was near, and on that account was concerned for her husband.
The love of God, with which she was filled, caused her sweetly to praise his name,
so that the sense of the pains and weakness of her body seemed to be taken away.
One time, in the sense of the love of God to her soul, she cried out, "`Oh! death,
where is your sting?`"
Often praying and praising God,
and during the whole time of her sickness she was freely given up to die.

A few days before her departure she said to her husband,
'`You are the dearest of any thing in the world to me; yet I can freely leave you.`'
Another time she said to him,
'`The Lord has answered dear Charles Marshall`'s prayer for me;`' remembering that C. M.,
who died at her house, had desired, upon his dying-bed,
that she might have an easy passage when she came to such a time as he was in; '`for,`'
said she, '`I am very easy;`' and often said that she was resigned to the will of God.

A little before her death,
much through her husband`'s great affection to her and his earnest desire of her life,
she seemed a little to desire life, but presently checked herself for it,
and returned to her former resignation of spirit;
and so lay supplicating and praising God, so that a neighbor present,
not called a Quaker, said that she never saw any lie so sweetly in all her life.
Seeing some about her weep, she said, '`Do not cry for me, for I am going to my rest.`'
A friend said, '`Are you willing to leave your husband?`'
She answered, '`I have often told him I am willing to go when the Lord pleases:`'
and in a little time after she said, '`In a few days, in a few days, they will say,
Sarah Padley is dead.`'
It much affected those about her to see how reconciled she was to death,
speaking very pleasantly concerning it,
and of the felicity that would accrue to her thereby.
She finished her course on the 8th day of the Sixth month, in the year 1699,
aged about thirty-four years.

[.asterism]
'''

WILLIAM GARTON, of Ifield, in the county of Sussex, was an early fruit to God,
a faithful believer in his blessed truth, and a servant in the church of Christ.
He was zealous against all unrighteousness,
and much for the unity of the spirit in the bond of peace among brethren;
an elder indeed, watching for good over the flock, a sympathizer with the afflicted,
and a mourner in the house of mourning, more in deed than in words.
Though but a plain man,
yet God endowed him with a large understanding and sound judgment,
which has been approved in difficult cases.

He was firm and constant in spirit in times of suffering and persecution,
preferring the service of truth, and the testimony of it, before all worldly things.
He was an example of virtue in the church, also in his family;
and his removal hence was a great loss to both; a true loving husband and tender father.
He had a great care that his children might be trained up in the fear of God,
and knowledge of his blessed truth;
which labor God was pleased to answer to his satisfaction.
He would often say,
the greatest portion he desired of the Lord for his children was the blessed truth,
and that they might love, fear, and serve the Lord,
and then he did not doubt that they would lack any good thing;
and to that end he would often be giving them good counsel and admonition.

Two days before his decease, being visited by a friend,
he said that he had always endeavored +++[+++to promote]
the prosperity of truth to the best of his understanding;
and that he had nothing of trouble upon him;
but did bless God that he had an opportunity to give this testimony to those present;
exhorting an ancient friend to keep low in God`'s fear, and make straight steps,
that he might lay down his grey hairs in peace.

Another time, several Friends coming from a meeting to visit him,
he desired that his love might be remembered to all Friends.

Another time he said, '`I have always sought the peace of the church,
according to my ability.`'
Being asked by a young man that watched with him how he did, he replied,
'`I am the better to see young men come up in the truth.`'

A friendly person coming to see him on his sick-bed, he put out his hand to him, saying,
'`Ah! you lack something: these are serious times.`'

Two ministering Friends visiting him the day before he died, he seemed very much revived,
and said, '`I never did any thing against the truth knowingly, since I was convinced.`'

One taking his leave of him, hoping for his recovery, he replied,
'`If it be the Lord`'s will, let me go in peace:
'`he also said that he felt the Lord to come in upon his spirit.
Near his end he prayed for his wife, and children, and grandchildren,
that God would make up the loss of him to them.
He further said, '`Oh Lord, I pray you, remember the ancients,
that they may still hold on their way; and, oh! my God, if it stand with your will,
visit more and more those who are not of your fold, and bring them in by your arm,
that they may come to know rest for their souls,
that at the last we may be bound up together in the bundle of life;`'
and so concluded with hymns and praises unto God.

Another time, after some friends had prayed by him, which was to his great satisfaction,
and the room being clear of company, he said to his daughter who was standing by,
'`Oh dear child, I have known much of the goodness of the Lord,
but not in such a large manner before as now: the very fountain is open,
and the love of God is over all; praises, praises to the Lord.`'
He uttered many heavenly expressions, and gave good exhortation to those about him,
which are not here inserted.
A little time before he died, he called for his relations, embraced his wife in his arms,
and took his last leave of her, and of his son and daughter;
holding out his hand and taking leave of all Friends who came to see him,
till his strength failed; and so sweetly died in the Lord, in an honorable good old age,
the 8th day of the Seventh month, in the year 1701,
being the sixty-sixth year of his age.

[.asterism]
'''

CHARLES ORMSTON, merchant at Kelso, in Scotland,
was convinced of the blessed truth about the year 1665.
He was a good example and pattern of godliness,
which he showed forth in the upright life and conduct he had among men,
and bore a faithful testimony among the Friends of that meeting to which he belonged,
and at whose house the meeting was kept to his dying day.

He was in the year 1668 cast into Edinburgh prison,
upon the account of his owning those people called, in scorn, Quakers.
He remained prisoner about twenty-two months; and his wife,
who was not at that time called a Quaker,
having several times made application to the privy council for his release,
did at length obtain an order for the same on the 20th of the Twelfth month, 1669.
Afterwards, Friends settling their meeting at his house, the earl of Roxburgh,
whose lodging was hard by, being angry that it should be so near by,
caused the town-militia to be raised, and by force hauled Friends out of their meeting,
and laid several of them up in prison, among whom C. Ormston was one.
His adversary at length perceiving that neither keeping them out of their meeting-room,
nor yet locking up his doors, would hinder them to meet under the pillars of the house,
gave over his persecution.

This our friend fell sick about the latter end of the year 1684,
and continued to grow weaker for about two months time.
Having before put his outward affairs in order,
and feeling himself very weak and nigh his end, upon the 21st of the Twelfth month, 1684,
in the evening, he called for his two sons,
(his daughters not professing truth) the elder whereof came to him,
whom he took by the hand, and exhorted him to a faithful walking in the truth,
as he had formerly done, and instructed them in many things.
About three quarters of an hour after, he fell asleep in the Lord,
having left a good savor of his upright life and conduct behind him.

[.asterism]
'''

JOHN ORMSTON, eldest son to the aforesaid Charles Ormston,
was an example of sobriety and godliness, having from a child shunned evil;
and when he was mocked for refusing to bear company with others in their vain recreations,
he bore it patiently, not reviling again.
He was given to retirement, and a careful instructor of his younger brother.
He was much troubled with bleeding, which brought him into a consumption,
and he told those about him he did believe he should die.
Being near his end, he desired his father to pray by him, which he did;
and about three or four days before he died,
he inquired of his sisters the day of the month, which being told him, he answered,
'`The twenty-second shall be my day;`' which proved true,
for upon the 22nd of the Tenth month, in the year 1682, he departed this life,
and entered into that blessed rest prepared for the faithful.
Aged twenty years and four months.

[.asterism]
'''

THOMAS ROBINSON, of Bridge-end, near Kelso, in Scotland,
was convinced of the truth about the year 1669, in which he walked circumspectly,
in a good conduct, to his latter end, being a good example in the place where he lived;
and often exhorted his friends and brethren, in the meeting to which he belonged,
to faithfulness.

He was several times imprisoned about the years 1672
and 1673 for meeting with the people called Quakers,
to worship God.
After having lived to a good old age, it pleased the Lord to visit him with sickness,
which continued about twelve days, in which time he was kept in patience,
and often signified that he felt the love of the Lord in his soul;
and exhorted his neighbors and relations, who came to see him,
to fear the Lord and to turn to him, while they had time.
Many more seasonable expressions he spoke, even when he was in great pain,
which much affected the standers by; to whom he said,
'`Let patience have its perfect work:`'
he also signified that being walking one evening by himself, as his manner was,
he prayed fervently to the Lord that he might have
a seal of his assurance before his departure;
and immediately he was filled with great joy, and the word of the Lord came to him,
saying, '`Is not my grace sufficient for you?
That is done already: your peace is made.`'

A little before he departed some of his children, with others, being present,
and he being about to take his last leave of them, said,
'`Humble your hearts before the Lord, and make use of your time,
and slip no opportunity of making your peace with God.`'
At last, recommending his spirit into the hands of the Lord Jesus Christ,
he sweetly laid down his head in peace upon the 28th of the Ninth month,
in the year 1698, being about the seventy-third year of his age.

[.asterism]
'''

THOMAS ROBINSON, son of the before mentioned Thomas Robinson,
was convinced of the truth about three years before his parents,
when he was about thirteen years of age, and but few Friends in those parts;
and he was so effectually converted, that although many endeavors were used,
both by promises and threatenings, they were not able to overturn his faith.

He was a youth of a sober and religious conduct, insomuch that he was a wonder to many;
and by his faithfulness to the truth, though a child,
he was very instrumental to the convincement of his parents,
who afterwards lived and died in the same faith.
Many disputes he had with priests and others, and was so furnished with arguments,
that they were often astonished at him.

About the twentieth year of his age,
God was pleased to call him to the work of the ministry;
at which time he was concerned to go to public places of worship,
and bear testimony to the people against their evil deeds.
His ministry was living, and he had a clear discerning of the spirit of antichrist,
that secretly worked for the hurt of God`'s heritage,
which he advised friends to watch against.

He travelled through the northern counties of England,
and also visited all the meetings of Friends in his own nation,
and had several sights of things to come, some of which he saw come to pass;
and also had a vision of his own death two years before he died.
He was visited with sickness, which continued about seventeen weeks,
and in all that time he was not heard to repine, or speak frowardly,
though his sickness was attended with much exercise.
Many times he sung praises to the Lord, to the affecting of others who heard him;
and declared that he valued not the pains and trouble
of his body if it was the Lord`'s will so to try him;
but that the Lord`'s everlasting truth might be raised over all;
and all lets and hindrances be taken out of the way,
and he to feel preservation in the truth, to the end of his days.
With many more good expressions.

The night before he died, he entreated his parents not to repine at the Lord`'s doing,
saying it was his will to remove him from the evil to come.
After a little silence his father asked him if he
had any thing more upon his mind to say;
he answered, '`Little more, but that all might be kept faithful who profess the truth,
the precious truth.`'
And farther said, '`Let me rest, I have done, I have done;`' and fell asleep,
and slept till about break of day,
and then departed this life on the 2nd of the Eighth month, in the year 1678,
about the twenty-third year of his age.

[.asterism]
'''

STEPHEN SMITH was born the 19th of the Seventh month, 1623.
He received the truth in the love of it in the year 1665,
and gave up to obey and walk therein.
He truly loved God`'s faithful messengers and people,
how despised and suffering soever they were; and he suffered with them,
both in person and estate, by imprisonment and spoil of goods,
for his tender conscience and testimony on behalf of Christ Jesus.

He was a man fearing God, and of good report in that county,
being an exemplary preacher of righteousness in his conduct,
and one truly kind and ready to do good in his day.
God also endued him with a living ministry and experimental
testimony to tell of his goodness,
and speak of his praise to others, from an inward sense thereof in himself,
and to the comfort and encouragement of many who heard.
He travelled in many parts of the nation, in the work and service of God,
in the gospel of his Son.

In the time of his sickness, when he was in the greatest extremity of weakness,
he often declared of the lovingkindness of the Lord God,
by which he was upheld above the fear of death.

To several who came to visit him on his sick-bed, he said,
it was a blessed and heavenly thing to have the mind clear and holy,
free from all troubles and cumbers of this world, as he said his mind was,
having all given up to the will of the Lord, that it might be truly done on earth,
as it is in heaven; adding,
'`O what a blessed and heavenly habitation is this for the soul of man to rest in,
which I have a full assurance of!`' At another time,
one who came to see him he exhorted to dread and fear the Lord God, and to repent of all,
whatsoever that holy and pure witness in his conscience makes manifest to be evil,
if happily he might find mercy with the Lord; which will be better to you (said he),
than all the world besides.
A little after came into the chamber another person,
and the power of the Lord being with him, he was refreshed in his spirit,
and he desired the said person to fear the Lord,
that thereby she might be preserved out of all evil; and added,
'`Love the truth above all, for the truth is a very precious thing;
and be sure keep low and humble to it,
and be not high-minded nor exalted above the pure witness of God in your conscience,
for that would be hurtful.`'

Another time, in remembrance of the tender dealings of the Lord to him,
he said to his sons, who were present, '`My days are very near drawing to an end;
and though my father and mother cast me off when I was a little lad,
the Lord has always preserved me, and his blessings did always attend me,
having been often in many great dangers, both by sea and land.
Having my mind sober and chaste to God,
and having the fear of the Lord placed in my heart, by which I was preserved out of evil,
I did the thing that was right in the sight of the Lord,
so that I found favor of the Lord, and gained the love and favor of people,
in dealing justly and truly with all people, not wronging any man.`'
This he gave in charge to his sons,
that they might always be kept sober and chaste in their minds,
having always regard to the fear of the Lord placed in their hearts,
that thereby they might be preserved out of evil,
doing always that which is just and right;
and to be sure to be courteous and kind to all, loving the good in all,
and bearing their testimony against the evil in all, wheresoever it did appear.

He farther said, '`And whensoever you go about that which is weighty,
take counsel of good and sound Friends,
so that all things may be done to the glory and honor of the Lord and his blessed truth,
in which your blessings are all yes and amen.`'
He moreover advised his sons, saying, '`Do not run into the cumbers of the world,
but wait upon the Lord, and he will find out a way for you in his time;
for the Lord is calling, and taking me out and from all troubles and cumbers,
and from the evil that is coming upon this wicked world, in a good time,
wherein I am assured of that sound and perfect peace,
wherein my soul will rest with the Lord forever; so that I have no more to do now,
but desire the Lord to make my passage easy to my heavenly rest.`'

A little before his departure, being filled with the spirit,
he praised and magnified God, and prayed, saying, '`Lord, and dearest God,
oh! assist in this heavenly passage from death to life;`' and soon after said,
'`Now I am going into my sweet sleep;`' and immediately and innocently
laid down his head in perfect peace with the Lord,
the 22nd of the Seventh month, in the year 1678, at his house, near Guildford, in Surrey,
aged fifty-five years and three days.

[.asterism]
'''

WILLIAM ALLEN, of Earls Colne, in the county of Essex,
received the blessed truth in the year 1654,
and the power of the Lord made a speedy change in him.
Soon after, he had a dispensation of the gospel of Christ Jesus given to him from God,
and he was stirred up with zeal in his soul against the false ways, worships,
superstitions, and profaneness of those times;
which zeal for God produced living testimonies from him,
in many towns and places where he travelled, against those things which were evil,
which sometimes occasioned him to come under hard sufferings, bonds and imprisonments.
In these he behaved himself as a faithful and courageous soldier of Christ Jesus,
and a good example to his fellow-sufferers, preaching the gospel of peace,
both in life and doctrine, and stopped the mouths of gainsayers.
This had a sweet and comfortable effect upon many,
who were reached in their consciences by his testimony and ministry,
and by his innocent conduct;
so that they embraced the truth he preached and suffered for,
and became heirs of the salvation of God, to their everlasting comfort,
and the furtherance of the gospel.

He was of severe carriage to such as made profession of truth,
and walked not with a straight foot in the gospel;
but he was very tender over all such as were young,
and under exercise about their inward condition,
and sometimes spoke effectually to their conditions,
to the easing of their afflicted spirits.

He was an example in the county where he lived,
encouraging Friends to observe the good order of the truth,
and to keep the gospel void of offense; not exalting himself above his brethren,
but carried a good respect to them, and to their counsel and judgment.

He served the Lord Jesus Christ, and his church and people,
without weariness to the end of his days;
and would lament those who sat themselves down at ease,
and would often say that a terrible day would overtake them who were at ease in Zion.
In the time of his health, when he was able to go abroad and visit Friends, he would say,
'`God has made me a huntsman,
and I must visit many of them who are in their holes and caves;
I must be clear of their blood:`'
and would relate the sore travails and pangs that he had for some,
which often made his soul very sorrowful.

His labors in the gospel were chiefly in the counties of Norfolk, Suffolk, Cambridge,
and Essex; and for his testimony to the truth he was imprisoned in Colchester castle,
where he was instrumental to gain many to the truth.
He was also imprisoned at Cambridge, and at Ely, and Lynn in Norfolk,
and many were turned to God by his ministry.

He was a diligent laborer in the Lord`'s vineyard for about twenty-four years,
and the last year and a half of his time he was much
afflicted with bodily weakness and sickness;
but he would often say that he was content with the will of his Father.
In the time of his sickness he showed the meekness
and patience of Christ which dwelt in him;
but the Lord, in due time, seeing his exercise to be enough, put a period to his days.
He was filled with the peace of God to the last, so that he said he could shout for joy,
but that he lacked strength of body; and which, he said,
was but an earnest of what he should more fully enjoy
when his earthly tabernacle was dissolved.
He spoke largely of the enjoyment of the glory of God in his soul,
and of the assurance he had of eternal life;
some of his expressions in his sickness were as follows:

'`The earth is filled with the glory of the Lord: praises, praises unto my God,
who reigns over all, over all.
He has redeemed my soul from the grave, and my life from the horrible pit.
He has plucked my feet out of the mire and clay.
Glory, glory be given unto your great name, oh! my good God.
As for my part I have fought the good fight, and have kept the faith;
and a large share of the glory of my God is sealed in my soul.
It is but an earnest that I have here of that crown of life
and glory which my Father has in store for me.`'

Concerning his sickness, he said, '`It has pleased the Lord to exercise me as he did Job,
for the trial of my faith and patience.
I have trodden his steps these twelve months.
A full reward you have given me of life and glory.
Oh! my good God, how good are you to me!
I have received abundance of good at your hand, and shall not I receive a little evil?
Blessed be your name for your goodness.
My cup overflows, I cannot utter it;`' and so continued,
often speaking of the glory of the Lord, and the immortality that rested upon him.
He charged friends to be faithful,
that the dread of God might always rest upon their hearts,
that they might answer his love, in yielding obedience to his requirings; and then,
if they met with exercises for the trial of their faith, yet the Lord would be with them,
if they abode faithful to the end; and the same crown of life they should enjoy,
which he had assurance of.

'`Therefore,`' said he, '`watch, and keep your garments, and oil in your vessels,
that you may be ready to enter with the bridegroom.
But as for those that continue in hypocrisy and disobedience,
and shun the cross of Christ, and neglect to work while it is day,
the night will come upon such unawares,
and the foolish virgins`' state they will be found in;
and though they may desire oil of the wise, the wise will have none to spare;
but the door will be shut upon such, and misery will be their portion.
He also gave good counsel to his two daughters, saying there was a blessing for them,
for their father`'s sake, if they would bow to truth, and abide faithful therein.

He longed to haste away; but was also willing to wait God`'s pleasure.
More was spoken by him as friends came to visit him, and as his strength would permit,
which was not taken in writing.

After his speech grew low he could not well be heard,
and seemed for some hours as if he was departing.
At last he said to a friend, '`I was almost gone, but I cannot go yet;
there is some secret counsel of God in it.`'
After some little time, more friends coming in, he was, beyond outward likelihood,
enabled to declare much to them, exhorting them to faithfulness, and said,
'`I am glad to see my friends about me.
I go to my God and your God, my Father and your Father.
My bosom is full of love to all my Father`'s children;`' and then said, '`Now, Lord Jesus,
how acceptable is it to leave all the world, and be gathered up to you:`' and so,
committing his spirit to the Lord, soon fell asleep.

His end was honorable, and he is crowned with immortality and eternal life,
and he left the world in a good age, having attained to about sixty-three years.
He died the 21st of the Eleventh month, in the year 1679, at Earls Colne,
in the county of Essex.

[.asterism]
'''

WILLIAM SIMPSON, born in Lancashire, where he also received the truth,
was a faithful minister and prophet of the Lord,
and was much concerned in going through markets and towns,
and to great men and magistrates, and priests`' houses, and public places of worship,
declaring against their false worship, and evil ways and works;
and was often imprisoned for the truth,
and underwent cruel and hard sufferings by the jailers.
He was moved of the Lord to go at several times, for the space of three years,
barefoot through markets, courts, cities and towns, and to priests`' houses,
as a sign to the people; telling them so should they be stripped, as he was.
Sometimes he was moved to put on hair sackcloth, and to besmear his face black,
and to tell them so would the Lord besmear all their religion.
Great sufferings did this poor man undergo; many sad blows, and sore whippings,
with staves, and wands, and thorn-bushes, coach-whips, and horse-whips, on his bare body.
This was before king Charles the Second came in;
that that generation might have taken warning, and they would not,
but rewarded his love with cruel usage: only the mayor of Cambridge did nobly to him,
for he put his gown about him, and took him into his house.

In the year 1670 he went to Barbados, in company with that faithful servant of God,
John Burnyeat, to preach the gospel of Christ Jesus in that island;
and after they had some service for God there, he was taken sick of a fever,
in which time he felt great peace and consolation of the spirit.
After he had been sick several days, he signified to Friends about him that he should die.
In the observation of his submission and innocent behavior on his sick-bed,
some shed tears; and he taking notice of it,
tenderly desired that they should not be grieved.
Growing weaker, and his voice low, he said to those about him, '`Friends, be noble,
and do not hinder me in my passage, for I am an innocent man.`'
Being asked where he would go, he said,
'`I must pass away;`' and by what more was said at that time,
Friends were assured that his heart was wholly fixed upon the Lord.

A few hours before he died, a person came to visit him who had not been, though invited,
at any meeting William had been at in the island,
and taking him by the hand asked him how he did; he answered,
'`I am a very sick man;`' and looking towards the man,
he was endowed with the power and spirit of the Lord,
by which he marvelously preached the glorious gospel of our Lord Jesus Christ,
for about a quarter of an hour, praising and magnifying the Lord;
which was so contrary to the expectations of those about him,
(considering the circumstances of his weak condition,) that it caused amazement,
trembling, and tears.

He preached the doctrine of perfection, and freedom from sin on this side the grave,
exhorting friends to be valiant for truth upon earth;
and that they should not be again entangled with the yoke of bondage;
but to stand fast in the liberty wherewith Christ has made them free;
that every bond and yoke might be broken, and that which is pure and holy,
of the Lord God, might go free in all; that God might be glorified and honored,
and they preserved in the day of trial, which must come upon all flesh;
and so to grow from grace to grace, and from strength to strength,
and from one degree of holiness unto another,
and that a daily growth might be witnessed in all.
Farther saying, '`O friends! it is the life that the Lord looks at;
for he that has the Son has life; and he that has not the Son has not life.
Examine yourselves; no Son, no life; without the Son, without life:`'
and thus he declared wonderfully, often praising and glorifying God after this manner;
--'`Oh! all that is within me praise and magnify the Lord God,
who is worthy forever and ever of all glory.
Everlasting praises to the God of my life, who is only worthy, and lives over all,
and is above all, God blessed forever.
Amen.`'

About three hours after he had given this testimony,
he departed this life in much quietness, being the 8th day of the Twelfth month,
in the year 1670, and was honorably buried in a garden belonging to Richard Forstal,
at Bridge-town, in Barbados.
