== Chapter 9

[.chapter-synopsis]
* Joseph Coale
* William Smith
* John Steel
* Thomas Lloyd
* Elizabeth Moss
* John Bowron
* Hugh Roberts
* Priscilla Cotton
* Andrew Graham
* Thomas Wresle
* William Captain
* Roger Gill
* William Smith
* Margaret Thompson

JOSEPH COALE, of Reading, in the county of Berks,
a young man about nineteen years of age,
was convinced of truth in the breaking forth of God`'s blessed day in our age.
When the ministers of Christ Jesus our Lord came to Reading,
he was one of the first that received their testimony,
and was one of the first in the county of Berks that
suffered imprisonment on the truth`'s account.
In the year 1655 he was committed to the counter in Reading, by Henry Frewin, justice,
and afterwards to the jail, for declaring, in the public place of worship,
that Cain`'s sacrifice was not accepted, but was an abomination to the Lord.

He preached the everlasting gospel, and the day of God`'s visitation to the world;
and his ministry was effectual,
not only for the convincement but also for the establishment and confirmation of many,
he being experienced in the work and dealings of the Lord God,
and also of the wiles and baits of the enemy of the souls of mankind;
a faithful witness-bearer to the truth, not in words only but in life and conduct also;
walking in innocency and lowliness of mind, in which he was a good example and pattern,
as became the gospel of Christ Jesus.

Being delivered out of prison, he was moved, in the year 1656,
to travel abroad in the west of England,
to visit his friends and brethren who were prisoners
for the truth in Launceston jail in Cornwall,
where, at that time, our dear Friend George Fox was also a prisoner, with other Friends.
In compassion to their sufferings he was conscientiously concerned to lay before
justice Anthony Nichols the cruelty of the jailor towards his friends,
carrying also with him a letter from George Fox to the said justice; who,
instead of relieving the oppressed,
committed the said Joseph Coale to the rest of his friends at Launceston as a vagrant.
He lay there many months, after he was fined at the assize,
for the most part in a wretched place called Doomsdale, where they used to put murderers,
after they were condemned to die.
It was so noisome that it was observed few who went in ever came out in health;
and the filth of the prisoners, that from time to time had been put there,
had not been carried out, as the people said, for many years; so that it was like mire,
and in some places to the top of the shoes in water, etc.
The jailor would not let Friends clean it,
neither would he let them have beds or straw to lie on.
Being released, he went on farther westward to visit Friends,
but was committed by justice Ceely again to Launceston jail as a wanderer,
where he lay three months.

In the year 1657, he being with other Friends met to worship God, near Penryn,
in Cornwall, captain Fox, governor of Pendennis-Castle, with a troop of horse,
came and abused Friends in a wicked manner, and Joseph was much beaten,
and some of his blood shed, to the hazard of his life.

He was also afterwards, for declaring truth in the public place of worship at Exeter,
fallen upon by the rude people, and haled by the hair of the head,
and had to the town-hall, and from there to jail, a very filthy place;
and they put a great pair of double irons upon one of his legs,
and ordered the jailor not to let him have any bed nor straw to lie upon;
but the next week he was set at liberty.

In the same year he was committed to Dorchester jail for
exhorting people to repentance in the market-place at Lyme,
and for declaring truth in the steeple-house at Bridport.

In 1661 he was again imprisoned at Exeter for not swearing;
being taken from a peaceable meeting, and tendered the oath.
Many other times he hazarded his life for the testimony of the blessed truth, in stocks,
and stonings, and various other hardships and difficulties.
He was once in Ireland with Edward Burrough, in the service of the gospel.

Last of all, he was committed to the jail of Reading, on the 13th of the Fifth month,
1664, by William Armourer, a justice of the peace, because,
for conscience-sake towards the Lord, he could not break his command, who had said,
"`Swear not at all.`"
After six years being shut up in prison, and much deprived of common air to breathe in,
he was greatly impaired in his health.
In the time of his sickness,
he gave forth many heavenly exhortations to Friends who came to visit him;
and this was his faith, which he declared on his dying bed, saying,
that the light of that glorious everlasting day of the Lord,
which is broken forth in this our day, shall never be extinguished,
notwithstanding all that men can do: '`And though,`' said he,
'`it may be in the hearts of men to destroy and root out, if it were possible,
the righteous from off the earth, yet the Lord does not intend so,
neither is it in his heart to allow it so to be,
but to exalt his own name and kingdom over all;
and the wrath of man shall turn to the glory of God, and the rest he will restrain.`'

Death was made easy to him;
and near his departure he bid one of his fellow-prisoners farewell,
and resigned up to him that office of love and care
which he exercised among his brethren and sisters,
in bonds for the truth`'s sake.
Being filled with heavenly love and life, and fully satisfied,
he laid down his head in peace,
and full assurance of everlasting rest and joy in the Lord.
Aged about thirty-four years.

[.asterism]
'''

WILLIAM SMITH, born at Besthorp, in Nottinghamshire,
was formerly a pastor of an Independent congregation,
and lived after the strictest manner of that people,
and was convinced of God`'s everlasting truth about the year 1658.
He was a faithful laborer in the gospel, and many were turned unto God by his ministry;
for he approved himself a minister of Christ Jesus, in tumults, in labors, in travails,
in watchings, in necessities and distresses,
which came upon him through the often spoiling of his goods,
and long and tedious imprisonments of his body.
For refusing to pay tithes to an impropriator,
he was kept close prisoner one time twenty-one weeks among felons,
in a dungeon in Nottingham jail;
and another time he had the value of forty-two pounds taken from him,
at the same time he was in prison for seven pounds, demanded by Dove Williamson,
priest of Elton.

Indeed, many were his sufferings for his testimony to the truth,
which for brevity sake are omitted; all which he patiently endured,
as seeing him who is invisible, that he might hold fast faith and a good conscience.

In the times of his imprisonment he wrote several useful books,
which remain in the printed collection of his writings.
When he was at liberty he travelled abroad,
to the nourishing and strengthening of them who did believe.
Though he was often visited by sickness, he was kept in much patience and contentment;
and much of the power and presence of God appeared in him many times,
when he was in great weakness of body, to the admiration of the beholders.

In his last sickness, he was a great comfort to them who visited him,
being a living man in the life of truth.
After he had been ill seven weeks, his pains began to cease,
yet he continued in weakness; but other distempers came upon him,
which he bore with great patience.
Waiting quietly, and having his mind retired, he spoke little till one evening,
when many Friends being in the room, sitting in silence, and he in his bed,
he turned towards them, and plentifully declared of the great love of God:
and Friends were much refreshed and tendered.
He also testified of a large portion which he had in life eternal;
and then he spoke to Friends to be mindful of truth, and of their service therein,
more than of their daily food; and so committed them to the grace of God.

The day before he was taken away he called for all his children, who were six or seven,
and tenderly exhorted them to keep in the fear of God, and to love the truth,
and God would be a father and portion to them.
The next day he departed this life, being the 9th of the Eleventh month,
in the year 1672.

[.asterism]
'''

JOHN STEEL, of Cumberland, was brought to the knowledge of the truth in the year 1654,
and was obedient thereunto;
and the Lord gave him a public testimony to bear not long after he was convinced,
which continued with him to the end of his days.

He was a man of an excellent spirit,
and clear in discerning the states and conditions of many,
to whom he was made very serviceable by good counsel, wholesome advice and instruction.
His manner in public testimony was to deliver himself in few words, and not often,
yet very weighty and profound.
He was severe against deceit and wrong spirits,
but very willing always to encourage the well-doers;
a good example in conduct in his family, and abroad among men,
as well as in the church.

When he was first taken sick he said to his wife, '`I must leave you;`' she replied,
'`My dear, why are you of that belief?`'
He answered, '`It is my belief, and that I shall be well,
and get to the place of pleasantness that I have been travailing for above these twenty
years;`' exhorting her to take heed to the pure light wherewith she was enlightened,
'`for,`' said he, '`it is the way, and there is not another.`'
He bore a living testimony on his dying-bed, in the name and power of the Lord,
to several who came to visit him, both Friends and other people, exhorting, warning,
and reproving, as he was moved of the Lord.

The day before he died, several Friends being come to see him,
he bade them sit down and mind well what he said;
and he uttered many very weighty sayings, which were not written down;
but this was remembered, that he said,
'`None could die the death of the righteous but they that lived the life of the righteous.
Though death may seem hard to some, it does not seem hard to me;
for I feel my passage sweetened this day.`'
He exhorted Friends to keep the unity, and beware of a wrong spirit, and then said,
'`I have little more to Friends, but it may be I have something to say to others.`'

After a little time he desired several of his neighbors, who were not called Quakers,
to be sent for, and most of them being come, the power of the Lord came upon him,
and he said,
'`I am not ashamed this day to say the spirit of the Lord
is upon me;`' and so declared to them several weighty things,
and said, '`Though some of you have been long in a profession of religion,
if the question were put to you, What is the guide of your minds?
I believe you will be put to a stand for an answer.`'
Some of their hearts were so reached that they wept.
A few hours before he died, he uttered many heavenly expressions in prayer to the Lord,
to the great refreshment of the standers-by. Thus the Lord,
who alone is worthy of praise, accompanied him by his power to the last.

He was convinced of truth in the year 1654, and died in Cumberland, in 1680.

[.asterism]
'''

THOMAS LLOYD formerly dwelt at a place called Macemore, in Montgomeryshire, in Wales.
In his young days he was brought up at the university of Cambridge,
and afterwards removed with his family to Pennsylvania,
where he was president and deputy-governor of that province several years;
and in the last part of his time he had his share with other friends in the exercises
occasioned through the contention of George Keith with Friends in that country.

Being taken sick, and near his end, he said to Friends about him, '`Friends,
I love you all.
I am going from you, and I die in unity and love with all faithful Friends.
I have fought a good fight, I have kept the faith,
which stands not in the wisdom of words, but in the power of God.
I have fought, not for contention and strife, but for the grace of our Lord Jesus Christ,
and the simplicity of the gospel.
I lay down my head in peace, and desire you may all do so: friends, farewell all.`'

He farther said to Griffith Owen, a Friend who was then intending for England,
'`I desire you to mind my love to Friends in Old England,
if you livest to go over to see them.
I have lived in unity with them, and do end my days in unity with them,
and desire the Lord to keep them faithful unto the end, in the simplicity of the gospel.
After a few days`' sickness, he departed this life on the 14th of the Seventh month,
in the year 1694, aged about forty-five years, leaving six children behind him,
and was buried in Friends`' burial-ground in Philadelphia, in Pennsylvania.

[.asterism]
'''

ELIZABETH MOSS, daughter of Thomas Monk of South Liverton Hall in Nottinghamshire,
whose mother afterwards married Samuel Watson of Knight Stainforth,
in the county of York, and late wife of Thomas Moss, merchant in London,
was educated under a tender, zealous, and religious mother,
who brought her up in the nurture and admonition of the Lord;
and she was a dutiful and obedient child.
When she grew up, and came to receive the truth, she gave up to it,
and continued faithful therein to the end.
She was exemplary in her family, and took great pains to instruct her servants,
that she might bring them to a sense of their dangerous condition without a Savior.

She was a great lover of retirement, and much given to prayer, contemplation,
reading of the Holy Scriptures, and spent much of her time alone in her chamber;
so that frequently, when her husband returned home from his affairs abroad,
he found her weeping; upon which he has sometimes said to her,
'`If some persons saw you at these times, they might think you were under discontent:`'
her answer was, '`No, my dear, there is nothing at all of that;
but the Lord`'s power and presence has broken my heart and tendered my spirit,
in a living sense of his goodness and tender dealings towards me.
I can say he is truly good to my soul,
and I have tasted of the incomes of his heavenly love and life.
I heartily wish that all who make profession of the blessed truth, were enjoyers with me,
for my soul has been overcome with his love; and although I have lost all my children,
and many of my near relations, yet is the Lord pleased to sweeten all my afflictions,
and make hard things easy to me.`'

She was indisposed some time before she kept her chamber,
and her sickness increasing upon her,
she was advised to remove out of the city for the recovery of her health, which she did,
and was some time at Shacklewell.
But notwithstanding, she grew worse; and being sensible that her end drew near,
she sent for Samuel Waldenfield, George Whitehead, and some other Friends,
that she might see them before she died.
The day before she died, Samuel Waldenfield and John Field coming to visit her,
she was much revived, and spoke to this purpose, as follows,
directing her speech to Samuel Waldenfield.

[.embedded-content-document.testimony]
--

I had a desire to see you,
and to invite you to my burial,`' she having sent for him the day before; '`but I hope,`'
said she to John Field, '`you will not take it amiss that I spoke first to Samuel,
for I did not know of your coming.
Your visit being altogether free, I kindly accept of it as freely,
and desire you also to be at my burial.
Though I did not know that I should have seen the light of another day,
yet the Lord having spared me, I am glad to see your faces,
that I may tell you how good and gracious the Lord has been to my soul;
for I can truly say, I have sought him with many tears, in my secret chamber,
and poured out my soul unto him; and said, O Lord, do you come down and tabernacle in me,
and take up your abode with me.
For I testify Jacob`'s seed has wrestled with God for a blessing, and has prevailed;
and now he is become my portion, and the lot of my inheritance forever.
He has poured of the oil of joy into my sorrowful soul,
and has fed me with the finest of the wheat,
and with honey out of the rock has he sustained me, and the sting of death is taken away.
I say, my dear friends, I have not the work to do now, I bless my God for it,
but am ready to be dissolved; and I do freely resign my life to my God.
I remember my dear and tender mother, who was a woman that truly feared him,
and her prayers and petitions were often put up to the Lord,
on the behalf of her offspring; and we have reaped much benefit thereby.
I have blessed the Lord many a time that ever I was born of her.
I speak not these things boastingly; no, for what am I but a poor lump of clay?
But only to extol the powerful name and goodness of my God,
who has been so bountiful and gracious to me,
for there is forgiveness and mercy with him, that he may be feared.

Therefore be encouraged to keep faithful to the Lord,
all that are within the hearing of my voice, both husband, friends, and servants.
I exhort you all, do justly, love mercy, and walk humbly with your God,
that so it may be said unto us all, '`Come, you blessed of my Father;`'
which is what my soul has desired, and that I might never hear that dreadful sound, '`Go,
you cursed.`'
The Lord has answered my desire this day, and has loosed my tongue,
that was ready to cleave to the roof of my mouth,
and has strengthened me to praise his great and honorable name.
Oh! praise the Lord with me, my friends, and pray for me,
as I shall do for you while I have breath,
that I may be preserved and kept in patience to the end;
for it is they that hold out to the end that shall be saved.
And though I have a dear and tender husband, and lack nothing that is convenient for me,
yet I can freely part with all.
I hope the Lord will preserve him near to himself to the end of his days.

--

Cornelius Mason coming in, she said,
'`Remember my dear love to your wife and dear children; she has been kind in visiting me,
and we have lived in much love and friendship together.
I truly desire the Lord may keep you faithful to himself to the end of your days;
and now I am comforted, and can say, Lord, here I am before you,
do with me as it seems good in your sight.`'

This is the substance of but part of what she said,
for she continued a considerable time speaking of
the mercies and dealings of God to her soul,
and praising him for the same, to the comfort of those present.
Samuel Waldenfield spoke a few words,
and returned praise and thanksgiving to the Lord for his
endless love and tender mercies to his servants and people;
during which she was filled with heavenly joy, and spoke some words afterwards,
desiring her dear love might be remembered to all faithful Friends, with whom, she said,
she was in perfect unity; and so parted with them in much sweetness,
love and satisfaction.

Soon after came our friend George Whitehead, whom she had desired to see,
and she was refreshed and comforted to see him; and said, '`Dear George,
I am glad to see you, having always had much love and respect for you,
you having been at my father`'s house, and known my mother well.
Though I am weak of body, yet the Lord has comforted me with his living presence,
and death is no terror to me;
but I am freely resigned and given up into the hand
of my God;`' with much more to the same effect.
Being much spent with the other Friends, she could not raise her voice as she did before;
but with love and sweetness, and a smiling countenance,
spoke of the goodness of the Lord to her soul,
and recommended her counsel to those that were present,
that they might not leave that work to do,
but labor to make their calling and election sure,
before they were cast upon a bed of languishing, as she was upon;
but through the love of her heavenly Father, she was waiting for her change,
and desired that she might hold out to the end in true patience.
She desired George Whitehead also to be at her burial,
and after he had spoken a few words in prayer and supplication on her behalf,
she parted with him in much love and unity.
Afterwards she said, '`O that I had wings like a dove! For then would I fly away,
and be at rest:`' with many other living and heavenly expressions.

These things are written,
not only for the comfort but encouragement of those who are yet behind,
to love the Lord above all, and follow him fully,
that he may not forsake them in the day of distress.
This Friend often said the eternal God was her refuge,
and underneath was the everlasting arm of his power,
to uphold and lift up her head above the floods of
temptations and trials that she met withal;
by which she was enabled to sound forth praises,
and humble thanksgiving to his holy and blessed name.

She departed this life the next day, being the 3rd day of the Second month,
in the year 1702, aged about thirty-nine years,
and was buried at Friends`' burial ground in Bunhill-fields, London.

[.asterism]
'''

JOHN BOWRON, was born at Cotherstone in Yorkshire, near Barnard-Castle, in the year 1627,
which was the place of his outward habitation to his death.
He received the truth by the ministry of George Fox and James Nayler,
when they came into those parts; which was about the year 1653.
Soon after he went to Stratford steeple-house, and preached to the priest and people,
and from there to the cross, and at Barnard-Castle, and at Rumbel steeple-house,
and the people threw snow at him, as he stood upon a stone speaking to them.
Then he went to Bowes, and stood up in the steeple-house yard,
and spoke to the people there; and one of the men cried out to the people, '`Hang him,
hang him in the bell-house;`' and some time after, that man hanged himself.
After that he travelled into Allandale, and had a meeting there, and so to Scotland.
At Edinburgh he preached to the people as he went through the streets of that city,
and at the cross, and there were English soldiers who were kind to him;
and he travelled through that nation.
The soldiers were very kind to him, but the priests were in a rage against him,
for he was a dread to them.

About the year 1656 he took another journey to Scotland,
and at Birkwell he took shipping for Barbados, and was kindly received in that island,
and had many good meetings there;
and they would have had him tarry with them as long as he lived.
When his service was over in that island, he took shipping for Surinam,
and travelled upon the coasts of Guiana, a country of South America,
three or four hundred miles.
He went to their sort of worship, which was performed by beating upon hollow trees,
and making a great noise with skins, like a sort of drums;
and he declared the word of the Lord among them by an interpreter.
He travelled +++[+++among the Indian natives in several of their settlements],
and spoke to their kings,
who were arrayed with fish-shells hung about their necks and arms;
and they spoke to him in their language, and confessed he was a good man,
come from far to preach the white man`'s God.

After he had declared the name of the Lord in this barbarous country,
he returned with his interpreter back to Barbados again, and stayed a little time there,
visiting Friends; and a ship presenting, he embarked for England,
which proved a long perilous voyage of thirteen weeks.
After they had been at sea about six weeks, they met with a violent storm,
which took away their rigging, and their provisions grew scanty,
so that for five weeks they were reduced to a pint of water,
and a biscuit a day each man.
There were about sixty persons on board, and some died;
but at length they arrived at Dover, where he took passage by land for London,
and met with George Fox, and Francis Howgill, to whom he gave an account of his voyage.
This was about the time that Richard Cromwell was made protector of England,
to whom he went with a message from the Lord, and warned him of the day of the Lord.

After John Bowron returned home into Yorkshire, and rested a little time,
he took his journey into Scotland again, and so into Ireland,
traveling through all that nation from sea to sea, and returned back again;
and so continued visiting that nation of Ireland six times in six years.
He was several times in prison for the testimony of truth; as at Durham jail,
and at Richmond house of correction twenty weeks in a sharp winter;
and for being at a meeting at Croft-bridge, they took from him a horse and two steers,
and imprisoned him again in Durham jail;
afterwards he was released by the bishop of Durham.

He oftentimes travelled to London in company with John Langstaff, and to Bristol,
and the west of England, till of latter years hindered by age and bodily infirmity.
After many journeys, and sore travail and labor, the Lord gave him this blessing,
that he lived to be full of days, and died in peace in the same house where he was born.
About two weeks before his death he rode to the meeting as he used to do,
and bore his testimony among Friends; and two or three days after,
went to the burial of an ancient Friend; and his grandchild waited upon him,
where he spoke at the graveyard a pretty while.

The first-day after, finding his strength decay, he desired his son, Henry Bowron,
to go to the meeting, and acquaint Friends that his days were almost spent,
and he knew not that he should come any more among them;
and his son answered his desire, and many Friends came to see him.
Two days after, he arose without help, and came cheerfully forth of his chamber,
desiring his son to trim him, which he did; after, he took his grandchildren by the hand,
saying, '`Stay with me, go not away, for I am taking my journey to a city, New Jerusalem,
that needs not the light of the sun, nor the light of the moon,
for the Lord God and the Lamb is the light thereof.`'
He added, '`Zion is a precious habitation:
he that dwells within the gates of Zion shall never be in need.`'
Again, '`What can be expected?
I have seen many good days.
I have seen the wonders of God both by sea and land.
The sea saw the wonders of God, and fled, and Jordan was driven back.`'

Sometimes he would pray to the Lord, saying, '`Lord bless this nation,
and the city of London, which I dearly love.`'
The night before he died, Thomas Raylton came to visit him, and being told who it was,
he said, '`Thomas, pray with me,`' and he did so,
and the presence of God was felt among them, and praises were given to the Lord.
Though he was weak in body, yet strong in the inward man,
and expressed his satisfaction with that opportunity.
After, he said, '`Thomas, what meeting had you yesterday?`'
meaning the quarterly-meeting; he answered they had a good meeting, of which he was glad;
further he inquired, '`What way are you going?`'
Thomas told him southward; he said, '`Tell friends of London how I am,
and mind to give my love to them and to G. Whitehead;`' and in great sweetness of spirit,
and peace of soul, he continued till about midnight, sensible to the last.

He died the 5th day of the Eighth month, 1704, aged seventy-seven years;
a minister fifty-one years.

[.asterism]
'''

HUGH ROBERTS, late of Pennsylvania, formerly of Wales,
was a man fitted and qualified by God`'s power to be a serviceable
minister of the gospel to the church of Christ in America,
in which country he lived about eighteen years.
His company was very desirable, being greatly edifying;
he had passed through many trials and exercises,
so could by experience speak a word in season to the travailing and weary soul.
His doctrine in the meetings of God`'s people dropped as dew,
and his speech as small rain upon the tender plants; for in the openings of life,
things both new and old came forth of the treasury of wisdom.
His testimony was comfortable to the hearts of the people, in the sense of God`'s love,
who is the author of all good to his people; a man zealous for good order in the church,
and skillful to accommodate differences when they happened.
He travelled in the work of the gospel in Maryland, Long Island, Rhode Island,
and New England, where his service was effectual to the people,
and to himself a great satisfaction.

At his return homewards, being weakly of body, having been much spent,
he lay sick at the house of John Rodman in Long Island,
where his friend John Bevan visiting him, he said,
'`Nothing lies in my way as an obstruction to hinder my peace with God.`'
After that he got home to Pennsylvania.
A friend of his taking his farewell of him, said to him,
'`I believe your deep trials and exercises are nearly at an end,
and that peace and joy everlasting will be your portion from the Lord for your faithfulness.`'
In much brokenness of heart, and sense of the presence of God upon his spirit,
he answered the friend after this manner, '`I am satisfied thereof,
and can bless my God for it.`'

He departed this life the 18th of the Sixth month, 1702,
and his body was buried at Merion the 20th of the same.

[.asterism]
'''

PRISCILLA COTTON, formerly wife of Arthur Cotton,
who then dwelt at Plymouth in Devonshire, now of Colchester in Essex,
was one of the first that received Friends in Plymouth; namely,
John Audland and Thomas Arey, in 1654.
She lived an honorable life, and was valiant for truth,
and often bore public testimony to it in steeple-houses, and other places,
against the priests and professors, who walked out of the truth;
and for her testimony she suffered several imprisonments and cruel dealings from them,
and other instruments employed by them.
She travelled in several places, bearing testimony for truth in the living power of God.
She also in her life-time gave forth several good papers, which are printed; and lastly,
the day she died, she left a paper for Friends,
as a testimony of her good will and love to them all; which is as follows.

[.embedded-content-document.testimony]
--

[.blurb]
=== The Testimony of Priscilla Cotton, to Friends, the day she died.

All my dear friends, who have found your Redeemer, oh! wait upon him at all times,
that you may stand continually in his presence where life is,
that with the light you receive from him, you may see your thoughts, and deny them,
that in stayedness you may be kept, when the hasty forward spirit would arise,
and keep it down.
With the measure of God`'s spirit all may be weighed, the words to what they tend,
that no lightness may appear in your words, nor unsavoriness, that no offense come,
but edification by all you speak.
Let the elders watch, that at no time the younger may see lightness, laughter,
or words of offense, but that you may always keep down the evil in yourselves,
and may minister grace to all you have to do withal, that God`'s spirit be not grieved.
So keep the field clean, that was once plowed up and made green and beautiful,
that no stones or hurtful weeds grow in it to oppress the Seed.

Friends, the cross is the power of God; when you flee the cross, you lose the power;
that which pleases self, is above the cross, and that which pleases man,
is above the cross; and that which shuns the cross, yields to the carnal part,
and loses its dominion.
Though the cross seems foolishness, stand in it; though it seems weak, stand in it;
though it be a stumbling-block to the wise, stand in it; there the dominion, authority,
and crown are received.
This is not for you to be exercised in for a time only, as at your first convincement,
but daily, even to the death, as long as a desire, will or thought remains in you,
contrary to God`'s pure light, and judge it by it; and as you wait in the light,
you will come to know a cross in the use of meat, drink, and apparel,
and keep to the cross when alone, or in company;
what the pure mind of God stands against in you, that the cross is against.

So friends, watch daily to keep Christ`'s command,
'`Take up your daily cross;`' be not at liberty one day, but deny your own will,
your own thoughts, and your own self.
Taking up the cross, you feel the power, the strength of the Lord God,
which breaks down all, keeps in order, in safety, and in peace.
This preserves from stubbornness, willfulness, and headiness,
and brings all to be subject, as dear children, unto God,
and subject one unto another as brethren.
In the light and in the cross there are no evil thoughts, no hard speeches,
no contention, no loving preeminence; but as brethren and sisters, pitiful,
tenderhearted, courteous, forgiving, forbearing, long-suffering,
and supporting one another.
Here the power of the cross is known, which brings all to God`'s praise,
and to his honor and glory, and to his children`'s prosperity and peace: so let it be.
Amen.

[.signed-section-signature]
Priscilla Cotton

--

After this, seeing her departure was nigh at hand,
she desired several Friends to be called; being come,
she desired to be lifted up in her bed;
and in a sense of life she spoke suitably to every one for some time,
exhorting Friends to peace and unity, and to keep in the cross,
which is the power of God, that all might witness a mortification to sin,
and a renewedness to life,
that the living God and his holy truth might be honored by all;
and that Friends might keep out of the fashions and customs of the world,
both in words and apparel, every one answering the truth therein.

After this she called for her husband, who was at that time weak; embracing him,
she said, '`My dear husband, the Lord has largely manifested his love to us,
and large has been our experience thereof, ever since he brought us together to this day.
And now, my dear, the Lord will separate us, but grieve not;
let your eye and expectation be to him,
and the Lord who has hitherto helped us will be your help and support;
in whom let your trust be forever!`'

In like manner she called for her daughter,
and gave her charge to live in subjection to God`'s truth,
and to forsake what she was convinced to be sin and evil, saying if she feared the Lord,
and walked in his truth, it should be well with her; but if not, you will be miserable.
She also spoke to other friends and relations, which for brevity is omitted.
Afterwards she said,
'`Let me lie down that I may die;`' so in great stillness
and quietness she departed this life,
about four hours after she had spoken these words, the 4th day of the Sixth month, 1664.

[.asterism]
'''

ANDREW GRAHAM, of Cumberland, near the borders of Scotland,
was a man of large understanding, a loving temper, and willing to do good unto all,
which increased his esteem with all sorts of people.
When the Lord was pleased to send his servants called
Quakers to preach the gospel in the borders of England,
in Cumberland, he with many hundreds came to hear their testimony,
and did confess unto the truth.
But he was before closely joined in fellowship with a people of good repute in the country,
and it was hard for him to leave them, which occasioned his halting as between two,
some considerable time, until the Lord was pleased to renew his visitation to him,
and by his righteous judgments awakened him to a true sense of his state;
so that he was deprived of peace,
until he gave up to be faithful to what the Lord
by his spirit discovered to him to be his duty.

He joined with the people called Quakers from that time,
and was a good example in conduct among men, in humility, and in self-denial,
and in suffering;
and in about two years time the Lord committed to him a part of the ministry,
and he faithfully labored in the work of the gospel, in the churches of Christ,
both in some parts of England, and in Scotland.
His service was great in the meeting to which he more peculiarly belonged;
and the more for his innocency, true zeal, and being devoted to the service of the truth,
laboring to bring people to the life and power of godliness.
He was as a nursing father,
or cherisher of those in whose hearts he saw God had begun his work,
as well as he was terrible against ungodliness.

He was suddenly seized with a great sickness, and lay sick but a short time;
in which he said, '`I see they are happy who, when death comes,
have nothing to do but to die;
for the pains of the body at this time are enough to struggle with.`'
As he lived, so he died, ending his days in a travail of spirit,
that Friends might be faithful; and Friends visiting him,
the Lord`'s power and presence was plentifully enjoyed,
to the tendering of the hearts of many.
He finished his course in this life on the 15th of the Eleventh month, 1704.
Aged sixty-two years.

[.asterism]
'''

THOMAS WRESLE, of Winteringham, in the county of Lincoln,
was an early seeker of truth and righteousness;
and for some time had fellowship among the Baptists.
He received the truth in the year 1655, wherein he much improved,
and approved himself a faithful man, loving truth, and the friends thereof,
with all his heart, and serving it and them faithfully to the end of his days.
He was exemplary in his conduct, and helpful to his neighbors;
and having a good understanding, was able to give counsel and advice,
which was esteemed among them.
In his sickness he said, '`I have seen where the weary are at rest,
and where the wicked cease from troubling;
and I have received an earnest of that blessed inheritance,
which is laid up in store for all the faithful.`'

A day or two before he died, some of his friends visited him,
which greatly comforted him, as he signified; to whom he said,
'`I have loved truth with all my heart, and all the friends of it, and feel nothing,
but that all is well with me.`'
In and with much fervency, he said,
'`I desire that Friends would keep up their meetings
in the name and power of the Lord Jesus Christ,
and that the Lord may bless and prosper them.`'
He exhorted Friends to keep their ancient zeal, love, and integrity,
which the Lord raised in them in the beginning, saying,
'`That is my great comfort now upon my dying bed;`' and taking his leave of Friends, said,
'`It is life, it is life, Friends, that overcomes death.
Give my dear love to all faithful Friends everywhere;`' and life
and truth was felt to flow among them at that time.

He died the 21st of the Twelfth month, 1704

[.asterism]
'''

WILLIAM CAPTAIN came out of England with his parents into Ireland, after the civil wars;
and was convinced at Mountmellick meeting.
He was bred a scholar, and in his youth intended for a priest.
He was a faithful, patient, and deep sufferer for the testimony of a good conscience,
and often in prison for meeting to worship God, and for tithes;
holding forth good conduct, as became the gospel.

In the time of his sickness, some Friends being present, he said to them as follows;
'`The Lord has appeared to me in a wonderful manner,
when I was ready to sink under great affliction; then did he take me by the hand,
as he did Israel of old, and raised me over my afflictions.
Whereas I had need of a physician, the Lord was unto me instead of a physician;
and when I had need of patience, he gave me patience; and when I had need of sleep,
he accompanied me with his living presence from time to time;
whereby my soul was sweetly consoled, so that I can say with the Psalmist,
"`It is good for me that I was afflicted;`" and with Simeon,
that "`My eyes have seen his salvation;`" and with Job, that "`My Redeemer lives,
and my eyes have seen him.`"
See how good the Lord is.
Oh! my soul, praise the Lord, let all that is within me praise the Lord.`'
Another time he said, '`The truth which the Quakers profess is the way to salvation,
and there is no other way.`'

He died a prisoner for the testimony to truth, the 30th day of the Ninth month, 1672.

[.asterism]
'''

ROGER GILL, of London, shoe-maker, received the blessed truth,
as professed by the people called Quakers, about the year 1683.
He formerly went among those called Baptists,
and I have heard him say that before he received
truth he was guilty of many gross and enormous crimes.
But by the power and virtue of the spirit of God, he came to know his heart changed,
and being washed and sanctified, and the fear of God placed therein,
which preserved him from those vices he had formerly been addicted to,
for which he was very thankful to the Lord.
Some years before he died,
God gave him a dispensation of the gospel of our Lord Jesus Christ to preach,
and he was faithful and diligent in that service, and was an able minister,
having a word in season to speak to the weary soul;
and very zealous he was for the prosperity of the truth.

In the year 1699 he had a concern upon his mind to visit the brethren in America,
and to preach the gospel to the people on that continent.
He went over the sea for that purpose, in company with his friend Thomas Story,
concerned in the same work; where they had not travelled long,
before they heard the people in Philadelphia, in Pennsylvania,
were visited with a malignant distemper, which caused great mortality.
At hearing thereof Roger Gill said he felt a great weight and exercise to come upon him,
so that he had no ease in his spirit till he came among them at Philadelphia.
The sickness increasing, he visited the sick, and preached in their public meetings,
saying that when he was one hundred miles off them,
his love in the Lord was such to them, that had he wings he would fly into Philadelphia.

It was the time of their yearly-meeting while he was there; where he, with others,
was concerned in public, earnestly to supplicate the Lord for the people;
and particularly Roger Gill fervently and devoutly interceded the Lord to stay his hand,
and if he would please to accept of his life for a sacrifice,
he did freely offer up his life to the Lord for the people.
When meeting was over he often expressed the ease of his mind,
and that it was with him that he had not much to do but visit Friends of Burlington,
in West Jersey, about twenty miles off.
He accomplished that journey;
and at his return to Philadelphia was taken sick with the distemper,
which filled him with great pain and affliction of body,
and he remembered in his sickness the free-will-offering up of himself unto the Lord;
saying to Friends about him, '`It is not in my heart to repent of the offer I have made.`'

He was cheerful, notwithstanding his great affliction of body;
and exhorted Friends to faithfulness, and said,
'`The Lord has sanctified my afflictions to me, and has made my sickness as a bed of down:`'
and when some did speak of their hope of his recovery, he said in much love,
'`Truly I have neither thoughts nor hopes about being raised in this life;
but I know I shall rise sooner than many imagine,
and receive a reward according to my works.`'
His sickness continued seven days upon him;
and a few hours before his death he took his leave and said, '`Farewell, farewell,
farewell forever,`'
and sweetly passed away out of this life on the 2nd day of the Eighth month, 1699.
It was observed that the sickness stopped, and very few were buried of it after him.

He left a widow and two sons behind him in England.
He was aged about thirty-four years.

[.asterism]
'''

WILLIAM SMITH, of Elsham, in the county of Lincoln, was an elder in the truth,
having received it in the love of it, and walked faithfully therein to the end,
and was a preacher of righteousness; in conduct a man of sincerity and godly simplicity,
giving no occasion of offense to Jew or Gentile, neither to the church of Christ,
and much beloved by friends and neighbors.
When on his dying bed, several Friends visiting him,
found him in a heavenly frame of mind.
He being told Friends`' love was to him, he answered, '`I have friends on earth,
and friends in heaven, the Father, Son, and Holy Ghost,
whom I have true fellowship withal, though yet in this earthly tabernacle;
my treasure being in heaven, my heart is there also, where the Father, Son,
and Holy Spirit dwells.`'
As he lived, so he died in the Lord, and is blessed, for so says the spirit,
and he is at rest from his labors.

He departed this life the 17th of the Twelfth month, 1701.
Aged seventy-nine years.

[.asterism]
'''

MARGARET THOMPSON, wife of John Thompson, near Mountmellick, in Ireland, being
upon her deathbed, and a few days before she died, calling her children to her,
said unto them, '`Fear the Lord, and abide in the fear of the Lord.
I do not allow you any thing further, than as you abide in the truth,
and love one another.`'
After that she said, '`The Lord helps me, and I find all temptations taken away.`'
Another time she said, '`They that die in the Lord,
have unity one with another;`' and she confessed the love of God, and said,
'`I will lean upon my beloved;`' and further said to Friends present,
'`Dear brethren and sisters, I exhort you in the Lord to love one another,
and walk in God`'s truth forever.
Women Friends, I exhort you all in the love of God, govern well in your own houses,
or else you cannot govern well in the church of Christ.
Likewise, young women, be sober-minded, and fear the Lord, and be charitable,
and walk in love to the end.
Dear friends, I salute you all in the Lord;
and I here give in my testimony against paying of tithes, for I never paid any tithes,
nor ever condescended to the paying of any, this being my last testimony.`'
She also exhorted Friends to their first love, which they had received in the beginning,
bearing her testimony against the vain fashions of the world.
She died the 5th of the Third month, 1688.
