== Chapter 9

[.chapter-synopsis]
* John Bowron
* Hugh Roberts
* Priscilla Cotton
* Andrew Graham
* Thomas Wresle
* William Captain
* Roger Gill
* William Smith
* Margaret Thompson

JOHN BOWRON, was born at Cotherstone in Yorkshire, near Barnard-Castle, in the year 1627,
which was the place of his outward habitation to his death.
He received the truth by the ministry of George Fox and James Nayler,
when they came into those parts; which was about the year 1653.
Soon after he went to Stratford steeple-house, and preached to the priest and people,
and from there to the cross, and at Barnard-Castle, and at Rumbel steeple-house,
and the people threw snow at him, as he stood upon a stone speaking to them.
Then he went to Bowes, and stood up in the steeple-house yard,
and spoke to the people there; and one of the men cried out to the people, '`Hang him,
hang him in the bell-house;`' and some time after, that man hanged himself.
After that he travelled into Allandale, and had a meeting there, and so to Scotland.
At Edinburgh he preached to the people as he went through the streets of that city,
and at the cross, and there were English soldiers who were kind to him;
and he travelled through that nation.
The soldiers were very kind to him, but the priests were in a rage against him,
for he was a dread to them.

About the year 1656 he took another journey to Scotland,
and at Birkwell he took shipping for Barbados, and was kindly received in that island,
and had many good meetings there;
and they would have had him tarry with them as long as he lived.
When his service was over in that island, he took shipping for Surinam,
and travelled upon the coasts of Guiana, a country of South America,
three or four hundred miles.
He went to their sort of worship, which was performed by beating upon hollow trees,
and making a great noise with skins, like a sort of drums;
and he declared the word of the Lord among them by an interpreter.
He travelled +++[+++among the Indian natives in several of their settlements],
and spoke to their kings,
who were arrayed with fish-shells hung about their necks and arms;
and they spoke to him in their language, and confessed he was a good man,
come from far to preach the white man`'s God.

After he had declared the name of the Lord in this barbarous country,
he returned with his interpreter back to Barbados again, and stayed a little time there,
visiting Friends; and a ship presenting, he embarked for England,
which proved a long perilous voyage of thirteen weeks.
After they had been at sea about six weeks, they met with a violent storm,
which took away their rigging, and their provisions grew scanty,
so that for five weeks they were reduced to a pint of water,
and a biscuit a day each man.
There were about sixty persons on board, and some died;
but at length they arrived at Dover, where he took passage by land for London,
and met with George Fox, and Francis Howgill, to whom he gave an account of his voyage.
This was about the time that Richard Cromwell was made protector of England,
to whom he went with a message from the Lord, and warned him of the day of the Lord.

After John Bowron returned home into Yorkshire, and rested a little time,
he took his journey into Scotland again, and so into Ireland,
traveling through all that nation from sea to sea, and returned back again;
and so continued visiting that nation of Ireland six times in six years.
He was several times in prison for the testimony of truth; as at Durham jail,
and at Richmond house of correction twenty weeks in a sharp winter;
and for being at a meeting at Croft-bridge, they took from him a horse and two steers,
and imprisoned him again in Durham jail;
afterwards he was released by the bishop of Durham.

He oftentimes travelled to London in company with John Langstaff, and to Bristol,
and the west of England, till of latter years hindered by age and bodily infirmity.
After many journeys, and sore travail and labor, the Lord gave him this blessing,
that he lived to be full of days, and died in peace in the same house where he was born.
About two weeks before his death he rode to the meeting as he used to do,
and bore his testimony among Friends; and two or three days after,
went to the burial of an ancient Friend; and his grandchild waited upon him,
where he spoke at the graveyard a pretty while.

The first-day after, finding his strength decay, he desired his son, Henry Bowron,
to go to the meeting, and acquaint Friends that his days were almost spent,
and he knew not that he should come any more among them;
and his son answered his desire, and many Friends came to see him.
Two days after, he arose without help, and came cheerfully forth of his chamber,
desiring his son to trim him, which he did; after, he took his grandchildren by the hand,
saying, '`Stay with me, go not away, for I am taking my journey to a city, New Jerusalem,
that needs not the light of the sun, nor the light of the moon,
for the Lord God and the Lamb is the light thereof.`'
He added, '`Zion is a precious habitation:
he that dwells within the gates of Zion shall never be in need.`'
Again, '`What can be expected?
I have seen many good days.
I have seen the wonders of God both by sea and land.
The sea saw the wonders of God, and fled, and Jordan was driven back.`'

Sometimes he would pray to the Lord, saying, '`Lord bless this nation,
and the city of London, which I dearly love.`'
The night before he died, Thomas Raylton came to visit him, and being told who it was,
he said, '`Thomas, pray with me,`' and he did so,
and the presence of God was felt among them, and praises were given to the Lord.
Though he was weak in body, yet strong in the inward man,
and expressed his satisfaction with that opportunity.
After, he said, '`Thomas, what meeting had you yesterday?`'
meaning the quarterly-meeting; he answered they had a good meeting, of which he was glad;
further he inquired, '`What way are you going?`'
Thomas told him southward; he said, '`Tell friends of London how I am,
and mind to give my love to them and to G. Whitehead;`' and in great sweetness of spirit,
and peace of soul, he continued till about midnight, sensible to the last.

He died the 5th day of the Eighth month, 1704, aged seventy-seven years;
a minister fifty-one years.

[.asterism]
'''

HUGH ROBERTS, late of Pennsylvania, formerly of Wales,
was a man fitted and qualified by God`'s power to be a serviceable
minister of the gospel to the church of Christ in America,
in which country he lived about eighteen years.
His company was very desirable, being greatly edifying;
he had passed through many trials and exercises,
so could by experience speak a word in season to the travailing and weary soul.
His doctrine in the meetings of God`'s people dropped as dew,
and his speech as small rain upon the tender plants; for in the openings of life,
things both new and old came forth of the treasury of wisdom.
His testimony was comfortable to the hearts of the people, in the sense of God`'s love,
who is the author of all good to his people; a man zealous for good order in the church,
and skillful to accommodate differences when they happened.
He travelled in the work of the gospel in Maryland, Long Island, Rhode Island,
and New England, where his service was effectual to the people,
and to himself a great satisfaction.

At his return homewards, being weakly of body, having been much spent,
he lay sick at the house of John Rodman in Long Island,
where his friend John Bevan visiting him, he said,
'`Nothing lies in my way as an obstruction to hinder my peace with God.`'
After that he got home to Pennsylvania.
A friend of his taking his farewell of him, said to him,
'`I believe your deep trials and exercises are nearly at an end,
and that peace and joy everlasting will be your portion from the Lord for your faithfulness.`'
In much brokenness of heart, and sense of the presence of God upon his spirit,
he answered the friend after this manner, '`I am satisfied thereof,
and can bless my God for it.`'

He departed this life the 18th of the Sixth month, 1702,
and his body was buried at Merion the 20th of the same.

[.asterism]
'''

PRISCILLA COTTON, formerly wife of Arthur Cotton,
who then dwelt at Plymouth in Devonshire, now of Colchester in Essex,
was one of the first that received Friends in Plymouth; namely,
John Audland and Thomas Arey, in 1654.
She lived an honorable life, and was valiant for truth,
and often bore public testimony to it in steeple-houses, and other places,
against the priests and professors, who walked out of the truth;
and for her testimony she suffered several imprisonments and cruel dealings from them,
and other instruments employed by them.
She travelled in several places, bearing testimony for truth in the living power of God.
She also in her life-time gave forth several good papers, which are printed; and lastly,
the day she died, she left a paper for Friends,
as a testimony of her good will and love to them all; which is as follows.

[.embedded-content-document.testimony]
--

[.blurb]
=== The Testimony of Priscilla Cotton, to Friends, the day she died.

All my dear friends, who have found your Redeemer, oh! wait upon him at all times,
that you may stand continually in his presence where life is,
that with the light you receive from him, you may see your thoughts, and deny them,
that in stayedness you may be kept, when the hasty forward spirit would arise,
and keep it down.
With the measure of God`'s spirit all may be weighed, the words to what they tend,
that no lightness may appear in your words, nor unsavoriness, that no offense come,
but edification by all you speak.
Let the elders watch, that at no time the younger may see lightness, laughter,
or words of offense, but that you may always keep down the evil in yourselves,
and may minister grace to all you have to do withal, that God`'s spirit be not grieved.
So keep the field clean, that was once plowed up and made green and beautiful,
that no stones or hurtful weeds grow in it to oppress the Seed.

Friends, the cross is the power of God; when you flee the cross, you lose the power;
that which pleases self, is above the cross, and that which pleases man,
is above the cross; and that which shuns the cross, yields to the carnal part,
and loses its dominion.
Though the cross seems foolishness, stand in it; though it seems weak, stand in it;
though it be a stumbling-block to the wise, stand in it; there the dominion, authority,
and crown are received.
This is not for you to be exercised in for a time only, as at your first convincement,
but daily, even to the death, as long as a desire, will or thought remains in you,
contrary to God`'s pure light, and judge it by it; and as you wait in the light,
you will come to know a cross in the use of meat, drink, and apparel,
and keep to the cross when alone, or in company;
what the pure mind of God stands against in you, that the cross is against.

So friends, watch daily to keep Christ`'s command,
'`Take up your daily cross;`' be not at liberty one day, but deny your own will,
your own thoughts, and your own self.
Taking up the cross, you feel the power, the strength of the Lord God,
which breaks down all, keeps in order, in safety, and in peace.
This preserves from stubbornness, willfulness, and headiness,
and brings all to be subject, as dear children, unto God,
and subject one unto another as brethren.
In the light and in the cross there are no evil thoughts, no hard speeches,
no contention, no loving preeminence; but as brethren and sisters, pitiful,
tenderhearted, courteous, forgiving, forbearing, long-suffering,
and supporting one another.
Here the power of the cross is known, which brings all to God`'s praise,
and to his honor and glory, and to his children`'s prosperity and peace: so let it be.
Amen.

[.signed-section-signature]
Priscilla Cotton

--

After this, seeing her departure was nigh at hand,
she desired several Friends to be called; being come,
she desired to be lifted up in her bed;
and in a sense of life she spoke suitably to every one for some time,
exhorting Friends to peace and unity, and to keep in the cross,
which is the power of God, that all might witness a mortification to sin,
and a renewedness to life,
that the living God and his holy truth might be honored by all;
and that Friends might keep out of the fashions and customs of the world,
both in words and apparel, every one answering the truth therein.

After this she called for her husband, who was at that time weak; embracing him,
she said, '`My dear husband, the Lord has largely manifested his love to us,
and large has been our experience thereof, ever since he brought us together to this day.
And now, my dear, the Lord will separate us, but grieve not;
let your eye and expectation be to him,
and the Lord who has hitherto helped us will be your help and support;
in whom let your trust be forever!`'

In like manner she called for her daughter,
and gave her charge to live in subjection to God`'s truth,
and to forsake what she was convinced to be sin and evil, saying if she feared the Lord,
and walked in his truth, it should be well with her; but if not, you will be miserable.
She also spoke to other friends and relations, which for brevity is omitted.
Afterwards she said,
'`Let me lie down that I may die;`' so in great stillness
and quietness she departed this life,
about four hours after she had spoken these words, the 4th day of the Sixth month, 1664.

[.asterism]
'''

ANDREW GRAHAM, of Cumberland, near the borders of Scotland,
was a man of large understanding, a loving temper, and willing to do good unto all,
which increased his esteem with all sorts of people.
When the Lord was pleased to send his servants called
Quakers to preach the gospel in the borders of England,
in Cumberland, he with many hundreds came to hear their testimony,
and did confess unto the truth.
But he was before closely joined in fellowship with a people of good repute in the country,
and it was hard for him to leave them, which occasioned his halting as between two,
some considerable time, until the Lord was pleased to renew his visitation to him,
and by his righteous judgments awakened him to a true sense of his state;
so that he was deprived of peace,
until he gave up to be faithful to what the Lord
by his spirit discovered to him to be his duty.

He joined with the people called Quakers from that time,
and was a good example in conduct among men, in humility, and in self-denial,
and in suffering;
and in about two years time the Lord committed to him a part of the ministry,
and he faithfully labored in the work of the gospel, in the churches of Christ,
both in some parts of England, and in Scotland.
His service was great in the meeting to which he more peculiarly belonged;
and the more for his innocency, true zeal, and being devoted to the service of the truth,
laboring to bring people to the life and power of godliness.
He was as a nursing father,
or cherisher of those in whose hearts he saw God had begun his work,
as well as he was terrible against ungodliness.

He was suddenly seized with a great sickness, and lay sick but a short time;
in which he said, '`I see they are happy who, when death comes,
have nothing to do but to die;
for the pains of the body at this time are enough to struggle with.`'
As he lived, so he died, ending his days in a travail of spirit,
that Friends might be faithful; and Friends visiting him,
the Lord`'s power and presence was plentifully enjoyed,
to the tendering of the hearts of many.
He finished his course in this life on the 15th of the Eleventh month, 1704.
Aged sixty-two years.

[.asterism]
'''

THOMAS WRESLE, of Winteringham, in the county of Lincoln,
was an early seeker of truth and righteousness;
and for some time had fellowship among the Baptists.
He received the truth in the year 1655, wherein he much improved,
and approved himself a faithful man, loving truth, and the friends thereof,
with all his heart, and serving it and them faithfully to the end of his days.
He was exemplary in his conduct, and helpful to his neighbors;
and having a good understanding, was able to give counsel and advice,
which was esteemed among them.
In his sickness he said, '`I have seen where the weary are at rest,
and where the wicked cease from troubling;
and I have received an earnest of that blessed inheritance,
which is laid up in store for all the faithful.`'

A day or two before he died, some of his friends visited him,
which greatly comforted him, as he signified; to whom he said,
'`I have loved truth with all my heart, and all the friends of it, and feel nothing,
but that all is well with me.`'
In and with much fervency, he said,
'`I desire that Friends would keep up their meetings
in the name and power of the Lord Jesus Christ,
and that the Lord may bless and prosper them.`'
He exhorted Friends to keep their ancient zeal, love, and integrity,
which the Lord raised in them in the beginning, saying,
'`That is my great comfort now upon my dying bed;`' and taking his leave of Friends, said,
'`It is life, it is life, Friends, that overcomes death.
Give my dear love to all faithful Friends everywhere;`' and life
and truth was felt to flow among them at that time.

He died the 21st of the Twelfth month, 1704

[.asterism]
'''

WILLIAM CAPTAIN came out of England with his parents into Ireland, after the civil wars;
and was convinced at Mountmellick meeting.
He was bred a scholar, and in his youth intended for a priest.
He was a faithful, patient, and deep sufferer for the testimony of a good conscience,
and often in prison for meeting to worship God, and for tithes;
holding forth good conduct, as became the gospel.

In the time of his sickness, some Friends being present, he said to them as follows;
'`The Lord has appeared to me in a wonderful manner,
when I was ready to sink under great affliction; then did he take me by the hand,
as he did Israel of old, and raised me over my afflictions.
Whereas I had need of a physician, the Lord was unto me instead of a physician;
and when I had need of patience, he gave me patience; and when I had need of sleep,
he accompanied me with his living presence from time to time;
whereby my soul was sweetly consoled, so that I can say with the Psalmist,
"`It is good for me that I was afflicted;`" and with Simeon,
that "`My eyes have seen his salvation;`" and with Job, that "`My Redeemer lives,
and my eyes have seen him.`"
See how good the Lord is.
Oh! my soul, praise you the Lord, let all that is within me praise the Lord.`'
Another time he said, '`The truth which the Quakers profess is the way to salvation,
and there is no other way.`'

He died a prisoner for the testimony to truth, the 30th day of the Ninth month, 1672.

[.asterism]
'''

ROGER GILL, of London, shoe-maker, received the blessed truth,
as professed by the people called Quakers, about the year 1683.
He formerly went among those called Baptists,
and I have heard him say that before he received
truth he was guilty of many gross and enormous crimes.
But by the power and virtue of the spirit of God, he came to know his heart changed,
and being washed and sanctified, and the fear of God placed therein,
which preserved him from those vices he had formerly been addicted to,
for which he was very thankful to the Lord.
Some years before he died,
God gave him a dispensation of the gospel of our Lord Jesus Christ to preach,
and he was faithful and diligent in that service, and was an able minister,
having a word in season to speak to the weary soul;
and very zealous he was for the prosperity of the truth.

In the year 1699 he had a concern upon his mind to visit the brethren in America,
and to preach the gospel to the people on that continent.
He went over the sea for that purpose, in company with his friend Thomas Story,
concerned in the same work; where they had not travelled long,
before they heard the people in Philadelphia, in Pennsylvania,
were visited with a malignant distemper, which caused great mortality.
At hearing thereof Roger Gill said he felt a great weight and exercise to come upon him,
so that he had no ease in his spirit till he came among them at Philadelphia.
The sickness increasing, he visited the sick, and preached in their public meetings,
saying that when he was one hundred miles off them,
his love in the Lord was such to them, that had he wings he would fly into Philadelphia.

It was the time of their yearly-meeting while he was there; where he, with others,
was concerned in public, earnestly to supplicate the Lord for the people;
and particularly Roger Gill fervently and devoutly interceded the Lord to stay his hand,
and if he would please to accept of his life for a sacrifice,
he did freely offer up his life to the Lord for the people.
When meeting was over he often expressed the ease of his mind,
and that it was with him that he had not much to do but visit Friends of Burlington,
in West Jersey, about twenty miles off.
He accomplished that journey;
and at his return to Philadelphia was taken sick with the distemper,
which filled him with great pain and affliction of body,
and he remembered in his sickness the free-will-offering up of himself unto the Lord;
saying to Friends about him, '`It is not in my heart to repent of the offer I have made.`'

He was cheerful, notwithstanding his great affliction of body;
and exhorted Friends to faithfulness, and said,
'`The Lord has sanctified my afflictions to me, and has made my sickness as a bed of down:`'
and when some did speak of their hope of his recovery, he said in much love,
'`Truly I have neither thoughts nor hopes about being raised in this life;
but I know I shall rise sooner than many imagine,
and receive a reward according to my works.`'
His sickness continued seven days upon him;
and a few hours before his death he took his leave and said, '`Farewell, farewell,
farewell forever,`'
and sweetly passed away out of this life on the 2nd day of the Eighth month, 1699.
It was observed that the sickness stopped, and very few were buried of it after him.

He left a widow and two sons behind him in England.
He was aged about thirty-four years.

[.asterism]
'''

WILLIAM SMITH, of Elsham, in the county of Lincoln, was an elder in the truth,
having received it in the love of it, and walked faithfully therein to the end,
and was a preacher of righteousness; in conduct a man of sincerity and godly simplicity,
giving no occasion of offense to Jew or Gentile, neither to the church of Christ,
and much beloved by friends and neighbors.
When on his dying bed, several Friends visiting him,
found him in a heavenly frame of mind.
He being told Friends`' love was to him, he answered, '`I have friends on earth,
and friends in heaven, the Father, Son, and Holy Ghost,
whom I have true fellowship withal, though yet in this earthly tabernacle;
my treasure being in heaven, my heart is there also, where the Father, Son,
and Holy Spirit dwells.`'
As he lived, so he died in the Lord, and is blessed, for so says the spirit,
and he is at rest from his labors.

He departed this life the 17th of the Twelfth month, 1701.
Aged seventy-nine years.

[.asterism]
'''

MARGARET THOMPSON, wife of John Thompson, near Mountmellick, in Ireland, being
upon her deathbed, and a few days before she died, calling her children to her,
said unto them, '`Fear the Lord, and abide in the fear of the Lord.
I do not allow you any thing further, than as you abide in the truth,
and love one another.`'
After that she said, '`The Lord helps me, and I find all temptations taken away.`'
Another time she said, '`They that die in the Lord,
have unity one with another;`' and she confessed the love of God, and said,
'`I will lean upon my beloved;`' and further said to Friends present,
'`Dear brethren and sisters, I exhort you in the Lord to love one another,
and walk in God`'s truth forever.
Women Friends, I exhort you all in the love of God, govern well in your own houses,
or else you cannot govern well in the church of Christ.
Likewise, young women, be sober-minded, and fear the Lord, and be charitable,
and walk in love to the end.
Dear friends, I salute you all in the Lord;
and I here give in my testimony against paying of tithes, for I never paid any tithes,
nor ever condescended to the paying of any, this being my last testimony.`'
She also exhorted Friends to their first love, which they had received in the beginning,
bearing her testimony against the vain fashions of the world.
She died the 5th of the Third month, 1688.
