== Chapter 10

[.chapter-synopsis]
* William Gibson
* Eleanor Barcroft
* Thomas Gettos
* James Blackhouse
* Mercy Johnson
* Tacy Davis
* Mercy Emies
* Sarah Kirkbride
* Sarah Thompson

WILLIAM GIBSON, born in Caton, near Lancaster, about the year 1629,
being a soldier in the garrison in Carlisle, Cumberland, and he, with three others,
understanding that a preacher called a Quaker, who was a stranger,
had appointed a meeting in that city, agreed to go together to the meeting,
with an intent to abuse the said Friend, whose name was Thomas Holmes.
William coming first to the meeting,
and hearing the Friend powerfully declaring the truth,
was so affected and reached by his testimony, that he stepped up into the meeting,
near the place where Thomas Holmes stood, and knowing the design of his fellows,
waited to defend the Friend +++[+++against]
any that dared offer to abuse him.
From this time he became a constant frequenter of Friends`' meetings,
and quitted his place in the garrison, and employed himself in the trade of shoemaking,
and waited upon God in silence, under the exercise of his power,
for the space of three years.
Afterwards he received a dispensation of the gospel to preach,
and became very serviceable in several places of the county of Lancaster.

On the 22nd day of the Sixth month, 1662, he married Elizabeth Thompson,
daughter of William Thompson, of Crossmore, in Lancashire, and settled in Sankey meeting,
near Warrington, for some years; and some were convinced of truth by his ministry,
who continue faithful to this day, and many others confirmed in the blessed truth;
so that his memorial is of good savor in those parts.
He afterwards travelled southwards in the work of the gospel,
and was imprisoned at Maidstone, in Kent, for his testimony, which imprisonment was long;
from which being discharged, he went to London, and removed his wife and family there,
where his service was well known to Friends in that city,
and many other parts of the nation, and many are the seals of his ministry.
Though he was severe in reproof,
and terrible in his ministry to the hypocrite and the workers of iniquity,
yet he was as a tender father to the mourners in Zion, and divided the word aright,
speaking a word in season to the tempted, afflicted, and travailing soul;
a cherisher of such as loved and feared the Lord;
and oftentimes his ministry was to the refreshment of the weary,
and the overflowings of his cup administered true comfort and consolation to the thirsty,
panting souls.

He was a lover of unity among brethren, but as a sword against that spirit, which,
under pretense of love to the light of Christ Jesus in their consciences,
would plead for a liberty that was out of the truth,
and sought to draw others from the footsteps of the flock of Christ:
to which purpose he wrote a book, entitled, '`An Epistle of Love.`'
He was a man devoted to the service of God, and was an example to believers,
even in word, in conduct, in charity, in spirit, in faith, and in purity,
and gave attendance to reading, and to exhortation, and to doctrine,
given to hospitality, and apt to teach, and was approved as a minister of God.
He had suffered hard imprisonments, and the spoiling of his goods,
for his testimony`'s sake against hireling priests, who feed themselves and not the flock,
and against their maintenance by tithes.

In the Third month, 1684, he travelled into his native country, Lancashire,
though he had been out of health;
and in his return home was taken sick of an ague and fever at Coventry,
yet got to London, and continued ill for three months.
On his sick-bed he exhorted Friends who came to visit him, to faithfulness,
and trust and confidence in the Lord, and to the love of the brethren;
and testified against that spirit which leads out of unity into a self-separation.

He left two sons and one daughter,
to whom he gave good advice in the time of his sickness,
directing them to that blessed and divine light of Christ, which he had preached,
and by which he had received the knowledge of God, and by walking in it,
salvation to his soul; desiring that they might know the same, and walk in it.`'
It will show you, '`said he, '`what is good, and what is evil: refrain from evil,
and do the good; take heed to God`'s word in your hearts,
so you will know your ways cleansed by it.`'
He charged them to avoid all vain and idle company,
and to be diligent in frequenting assemblies of the Lord`'s people,
and to have an ear open to receive the good counsel and advice of them who fear the Lord,
and are faithful to him, and to keep society with such, and to flee youthful lusts,
which war against the soul.
Moreover he said, '`Love the righteous judgments of the Lord,
and have regard to the fear of God, and love humility;
so shall you receive wisdom and understanding.
Be obedient to your mother, and be tender over her; and be not conceited,
nor high-minded.`'
He also charged them to read the Scripture, and other good books.

Thus did this good man, like Abraham, charge his children to walk before the Lord.
He was very resigned, and given up to die, and expressed his love to the brethren,
saying, '`My love in the Lord Jesus is to all the faithful.
Remember my dear love to them, and to all the faithful laborers.`'
Not long before he died, John Field visiting him, he looked earnestly on him;
his wife asking if he knew him, he answered '`No;`' she told him; he replied,
'`He is the first man I did not know.`'
At this time he seemed very retired in his mind unto the Lord, his rock, and his refuge;
several times lifting up his hands, and showed a willingness to be turned, and then said,
'`I have spoken my mind while I could speak, and now I cannot.`'

He died the 20th of the Ninth month, 1684, about five in the afternoon,
and was honorably buried at Friends`' burying ground, in Bunhill-fields,
many hundreds of friends and brethren accompanying his corpse to the grave.
Aged fifty-five years, a minister twenty-six years.

[.asterism]
'''
ELEANOR BARCROFT, daughter of William Barcroft, near Edenderry, in King`'s County,
Ireland, was a young woman of a clean and innocent conduct,
obedient to her parents and loving to all, but especially to the godly,
whose company was her delight; and as her life was good, so was her death.
In the time of her sickness, she desired to have the tenth chapter of Luke read,
wherein two passages were remarkable to her;
the one of the man inquiring who was his neighbor, the other of Martha and Mary;
at the reading of which she was much refreshed.

The morning before she died, it was observed she prayed with a low voice,
and did wrestle in spirit with the Lord; and in the afternoon the Lord did so appear,
that the pangs of death were as it were taken away,
so that she sung hymns and spiritual songs of praise to Christ her Redeemer;
and afterwards said, '`Oh! that I might live with you forever, and forevermore.`'
Then she took leave of her parents and relations.
Being asked how she did, she answered,
'`I feel neither pain nor trouble;`' and hearing her mother weep, said,
'`Why does my mother weep, for I am well.`'
With these and some other words which cannot be well remembered,
because of the sorrow of those about her,
she departed this life with the seal of assurance in the true faith,
and is gone to her rest, and has left a good memorial behind her.

She died the 27th of the Eighth month, 1678, in the nineteenth year of her age.

[.asterism]
'''

THE words and testimony of THOMAS GETTOS, of Bandon, in Ireland,
about eight hours before his departure out of this life.
He was weak in body, but fervent in mind, and perfect in memory;
taken from his mouth the 22nd of the Third month, 1682.

[.embedded-content-document.testimony]
--

I have known the terrors of the Lord for sin,
and for transgression committed against him in the time of my youth.
But he that is an everlasting fountain of life and mercy,
did not leave me in the greatness of my wickedness,
but in the abundance of his pity and compassion visited me, and found me out,
and laid hold on me by his judgments, and did awaken me,
even in that dead state and condition he found me in.
He made manifest his living truth, that is, Christ Jesus, the light of the world,
which enlightens every one that comes into the world, of the whole stock of mankind.
So the light and life being made manifest to me, it became the joy of my heart,
and the life of my soul.
I was brought to see that I must come to deny the world,
and the glory and riches thereof, and the honor thereof, and all things that are beneath.
It became a very great cross to the fleshly part, which I saw I must daily keep to;
for when I went from that which crucified me to the world, and the world to me,
my enemy prevailed over me; so that I saw the words of Christ fulfilled in me,
in that respect, according to his testimony, who declared in this way;
Whosoever does not bear his cross, and come after me, cannot be made my disciple.`'
When I came to see that heavenly treasure, made manifest, and revealed in my soul,
and kept my affections thereunto,
the yoke of Christ which seemed to be so heavy became light;
even so it is unto all them that keep in faithful obedience unto him,
and take up his daily cross.
I have known a travel towards that spiritual kingdom of our Lord and Savior Jesus Christ;
for I saw a race set before me, and I saw, if I did run with all my might,
it was possible for me to obtain the prize.
Therein I have had an exercise of my faith;
for had I not believed in the object of my faith, Christ Jesus,
it had been impossible for me to run that blessed race.
As I was faithful and obedient to the manifestation of Christ,
who is God`'s righteousness, which is manifest and received in the internal parts,
I received daily supplies of strength in my greatest exercises.
Unto whom then shall I return the glory and the praise
of this wonderful work of my salvation,
and eternal happiness, but unto Christ Jesus, the great fountain of life, mercy,
and truth, and righteousness! which I do desire to return at this time,
and at all other times, unto him who lives and reigns forever, God over all,
blessed forevermore.

And now, my friends, as the Lord brought these things unto my remembrance,
I could do no less than declare unto you the wonderful dealings of the Lord to my soul,
that all thereby might receive the instructions of the Lord,
who is forewarning the sons and daughters of men,
according to the greatness of his wisdom.
Certainly, although the Lord never created man to destroy him,
yet his determination shall stand forever; that is,
they that take warning in the day of their visitation, and return with all their hearts,
and with all their souls, shall find the way of life made manifest, and revealed in them,
which leads unto the Father, who is an eternal fountain of life.
But they that neglect the day of their visitation, must he shut up under darkness,
until the great day of the Lord.
And then they shall come to know they have rebelled against him,
and must know his righteous judgments, although it be to their everlasting destruction.
Here they shall see and know that their destruction was and is of themselves;
and God will be glorified, even in the destruction of his enemies.

And now it is the desire of my heart and soul, even before the Lord God Almighty,
that all may be warned and awakened out of that state of deadness
and security which the god of this world has brought them into,
so that the righteous judgments of the Lord might be made manifest unto them;
that so they may lay hold of his mercy in the day of their visitation.
And as for my dear friends,
who have known the gathering arm of his power into the holy habitation of our God,
which is Jerusalem, which is from above, the mother of us all,
I warn you all in the fear of the Lord to be careful to keep your habitation,
for in that consists your safety.

While Israel kept the place wherein God ordained them to be outwardly,
Balaam could not curse them, nor could any enchantment be found to prevail against them;
but when the wiles of their adversaries enticed them out of their habitations,
how many thousands were destroyed thereby!
The enemy stands without this holy habitation of the people of the Lord,
to entice his people to mix with a wrong seed,
and then we give our strength to our enemies,
and so befool away that heavenly treasure which God has committed to our charge.
Notwithstanding the enemy has prevailed over many upon this account,
yet I have taken notice of the goodness of this heavenly shepherd,
and great bishop of our souls, who has sought after them also,
that have been scattered out of the fold by that means.
Many he has laid hold on by the crook of his judgments,
and brought them back to the fold again.
And behold how many have perished, to the grief of the shepherd, and of the flock also.
But oh! forever blessed and praised be the Lord,
that has kept and preserved a remnant that have faithfully followed him,
who are built upon the rock Christ Jesus, where they stand steadfastly,
showing forth the greatness of his love.
They are as a city on a hill, that are seen far and near,
and are become the light of the dark world, by the shining of their holy lives;
and so shining by reflection, receiving their light continually from Christ Jesus,
the true light of the world.
Blessed are all they who know the gathering into this blessed city,
and abide steadfast unto the end; for the Lord has chosen Mount Zion unto himself,
that from there his glory might be proclaimed throughout all generations.

And now, my dearly beloved friends, whom I dearly salute,
even in the bowels of our Lord and Savior Jesus Christ;
oh! my love unto you all is beyond expression,
who have kept in faithful obedience to the truth.
Oh! the blessed satisfaction that we have found in him,
when we have been gathered into his name, and there drank together in one spirit,
so that our souls have been exceedingly refreshed,
and we have been made partakers of the heavenly bread,
which has been broken plentifully unto us, even at the table of the Lord.
Oh! never forget those blessed opportunities; but as you are kept in spiritual health,
you will feel a hungering after the bread of life, day after day,
and a thirsting after the water of life also.
So being kept here, you are capable of the blessing of the Lord,
and will see the-Scripture fulfilled in yourselves, which says,
"`Blessed are they that hunger and thirst after righteousness,
for they shall be satisfied.`"

--

About eight hours after he had delivered this to Friends present,
he died in peace the 22nd of the Third month, 1682.

[.asterism]
'''
JAMES BLACKHOUSE, of Yelland Conyers, in the county of Lancaster,
was born of believing parents, called Quakers, in the year 1668,
and when he grew up he received the same faith,
and for several years professed truth in much sincerity and plainness.
He was a man of a blameless conduct, and a good example,
and of great service in several affairs of truth, until, in the year 1697, he was,
at the suit of the dean and chapter of Worcester,
apprehended and committed to Lancaster castle for his Christian testimony against tithes.
Here he continued for some time a faithful sufferer, until he fell sick of body,
which increased upon him to the finishing of his life in this world.

When he was, as to outward appearance, nigh unto death, the Lord revived his spirit,
and he sang, and made pleasant melody unto God in his heart; and said,
'`The Lord has appeared in a wonderful manner unto my soul,
and has removed and taken away the pains of this my outward body,
and has received me into his bosom, and has set me upon his holy mountain,
which is as sure as Mount Zion, that cannot be moved,
and it is better for me to die than to live.`'

He died, a faithful sufferer for the testimony of Jesus Christ, in Lancaster castle,
the 13th day of the Fourth month, 1697.
Aged twenty-nine years.

[.asterism]
'''
MERCY JOHNSON, wife of Elihu Johnson, of Manchester, and daughter of Samuel Watson,
of Stanforth, in the county of York, was born the 7th day of the Fifth month, 1670.
She received a gift of the ministry while unmarried;
and in the year 1697 travelled with Jennet Stow in the work
of the gospel into the western and southern parts of England,
and in some part of Wales.
In the year 1699 she went, with her father, Samuel Watson, into Scotland,
to visit the meetings of Friends in that nation.
She was a tender woman, of a weakly constitution of body, though many times,
when in the Lord`'s service, she seemed very strong,
and was concerned in her spirit for good of all, and for the prosperity of truth,
and desired no long life in this world.

In the beginning of her illness she often desired of the Lord to give
her patience to undergo what might be allowed to come upon her.
Her illness abated, but in some time came again violently upon her;
also she was sensible her end drew near,
and often desired it in the time of her sickness.
The Lord favored her with his presence, and made her sick bed pleasant to her,
insomuch that she sang praises to the Lord, the giver of all good things.
Many Friends visited her in her sickness,
and it was a comfort to them and her relations to feel the Lord`'s presence with her;
and she declared of the goodness of God,
and how well content she was to be taken off the stage of this world, saying,
'`I am not in love with it.`'

Many were her excellent sayings, which are not remembered.
Near her latter end she was more filled with God`'s salvation,
and some of her words were as follow; some Friends being present,
'`Happy are you whose kingdom is not of this world, but of the Father`'s;
the Father`'s kingdom, your kingdom Friends, love God better than all.
Be faithful to the Lord every one, although you are but few.
I could have been glad that the whole meeting had been here;
surely they will remember what I said the last meeting I opened my mouth among them;
that was, to prize their precious time, not knowing how long they might have time,
neither what exercises they have yet to meet withal.
Now the time draws near that I shall go to an everlasting kingdom, where all sorrow,
tears and sighing shall be done away.
Glory, glory in the highest, to the Lord my God, who has been with me,
and borne up my head in time of great exercises.
I have nothing to do but to die.
Keep you near to the Lord,
that so when you come to lay down your heads you may have nothing to do but die.`'

Speaking to her husband, she said, '`Oh! my dear,
I have in the time of my health desired to live with the Lord, and to be faithful to him,
and now I see I have nothing to spare;
what will become of those who live a careless life,
and do not make a right use of their precious time?`'
She was, in the time of her speaking these words, filled with the love of God,
and the sweet spirit of life did attend her, to the comfort of those present;
and she said, '`This outward body grows weaker and weaker,
yet blessed and praised be the Lord, my inward man grows stronger and stronger.`'
In time of silence she made songs of melody to God in her heart;
and after a Friend prayed by her, she said, '`am so filled with God`'s love,
I shall never be emptied again.`'
She much longed to go out of this world,
waiting for the coming of the Lord to remove her, and said, '`My dear children,
I have prayed for them who are near and dear to me; but now I can leave them freely,
and commit them into the hand of my God.`'

Speaking to her husband and them, she said, '`I must part with all,
and I will bid you all farewell; the Lord bless you all, and keep you all,
in all your exercises that will come upon you.
I believe the Lord will be with you, as you have an eye to him.`'
Another time she said, '`Have nothing to do with them of ill spirits, but keep to God,
and he will give you power over them.`'
She was much grieved to see any professing truth to be light and airy,
out of the savor of it, and said, '`A day of trial will come upon them.
Another time, being in a quiet frame of mind, she said,
'`The sooner a period is put to this life,
the sooner I shall go to my everlasting comfort.`'
One wishing her a good night, she said, '`I shall have a good night,
let it be how it will; blessed and praised be the name of the Lord,
I am full of his goodness.
What a great difference between being thus, and in some of my sick fits!
There is a great comfort in one, but not in the other;
only that I think that it is doing the work, and hastening me to my everlasting joy.`'

A little before she was taken away, having got some rest in sleep, when she was awakened,
said, '`Now I am very sensible I must go soon to my joy,
that will last forever;`' and speaking to her husband, said, '`Fare you well, my dear,
now I shall be well in a little time.`'
She lay still a little while again, then said to those present,
'`Oh! the`' Lord is the best master you can serve while you live,
for he will reward you in your afflictions as he rewards me.
Oh! he is a fountain set open for me in a full manner in my affliction.
Glory, glory, praises, praises to his eternal name.
I will praise him while I have breath in my nostrils; he has been a merciful God to me,
and has helped me over many things, and has blotted out my sins,
and will remember them no more.
Oh! praise, honor, and glory to him forevermore.
Now into your hand I commit my dear husband and children, whom you have bestowed upon me,
and will take me from them; bless and preserve them to the end.`'

Thus she was drawn forth to supplicate the Lord for all, saying, '`I love all,
and God above all, for what he has done for me.`'
After this, she asked what hour it was; they told her four in the morning; she said,
'`I shall surely be gone in a few hours to my everlasting rest;`'
desiring her dear love might be remembered to all Friends in general.
Then she lay down quietly, waiting for her change, and desired all might be still,
and none come to disturb her in her passing away; after she awaked, she said,
'`Let us praise the Lord once more; we will love him above all.
All glory, praise, and eternal renown to his most worthy name; he has filled my heart,
and is near to crown my soul.
I would not live if I might choose to have the whole world.
Oh! you, the Lord, are better than all; my soul magnifies you; honor, glory,
and eternal praises be given to you forever, and forevermore;
I will praise you to the end.
Lord be with my dear husband and children to the end.`'
She said, '`I hope you will remember me when I am gone, to the comfort of your souls.`'
She said to her husband, '`The Lord united us in his own love together,
and in his love he will part us.
I was always satisfied before and since, that the Lord`'s hand brought us together.`'

The First-day of the week several friends came to visit her,
whom she exhorted to be faithful to what God had made known to them;
and her words had power with them, to the tendering the hearts of them she spoke to.
A little before her departure, she had a mind to send for her father to her burial,
who was an ancient man, about eighty years of age, and dwelt forty miles off.
He coming, she was glad,
and told him how good God had been unto her in the time of her sickness, and said,
'`If it was not for the hope of glory which is to come, I had fainted.`'
After this, she said, '`Now, Lord, when you please, remove me;
I am content with your will, when you see fit.`'

She continued in a heavenly frame of mind;
and a young woman who used to go to meeting coming to see her, she gave her good advice;
and afterwards fell asleep.
When she awoke, her husband asked her if she would drink any thing; she said,
'`I have had a full draught of the goodness of my God;
I did not so much as think of cordials;`' and so continued
praising the Lord for his goodness,
and the enjoyment of his presence.
She said, '`My troubles in a little time will be over,
and I shall be at rest and peace with my God,
where I shall praise him forever;`' and she said,
'`I think in a vision I have seen my dear mother and sisters, in shining garments,
where I shall be soon.
He is a great and mighty king that I am going to.
Oh! love so, that you that stay a little behind may come after.`'
A little before she died her husband asked her how she did, and she said, '`Come near,
'`and she kissed him, and bade him farewell; and presently again she said,
'`Let us bid farewell again;`' and so died, as if she had fallen asleep,
about the tenth hour at night, the 14th of the Twelfth month, 1704,
in the thirty-fourth year of her age.

[.embedded-content-document.epistle]
--

[.letter-heading]
A few words of tender counsel and advice to Friends,
given forth by Mercy Johnson upon her dying bed, two days before she died;
which she desired might be communicated to Friends.`'

Dear friends, both old and young, wherever these may come, my love salutes you dearly,
desiring the welfare of your bodies and souls.
I have in my measure labored among Friends in many places while with them,
for the prosperity of truth and good of souls, and now shall be taken away.
I find great concern upon me to leave as advice and tender caution to all,
that you may keep near to truth, and love it, seeking the honour of it above all things.
Dear Friends, love one another, and as you have an eye to truth,
and seek the honor of it before your own, then will your love flow one unto another;
and whispering, with backbiting, and tale-bearing, will be removed from you,
for I have seen the ill effects of such things many times.
And, dear Friends, in your meetings for business upon truth`'s account,
have your eye to the Lord, and wait to have your minds stayed upon him,
respecting one another above yourselves for truth`'s sake,
and you waiting upon the Lord to work in you, and for you,
and to open your mouths to speak a word in season.

Reason not, but give up freely to act and speak for truth, whether you be young or old;
not in high-mindedness, but in true fear before the Lord.
For I must tell you, the humble, and those that abase themselves, the Lord will exalt;
but the high-minded, and those of an exalted spirit, the Lord will abase and humble,
and make them know he is God, and will be bowed to by every high spirit.

Therefore, dear friends, let the truth have the reign in you, to govern your words,
though never so few, that they may be rightly seasoned with grace,
that so you may edify one another.
Permit no unruly spirit to appear in your meetings, neither in old nor young;
but stand in the counsel of God, and he will give you a word in due season,
to stop the mouths of all gainsayers of the blessed truth,
and of the work you are called to do in your days.
Thus the Lord will bless, and more and more prosper his work in you, to your comfort,
and his eternal praise, to whom all is due.
I can tell you, it will be well with you to be faithful to the Lord,
when you come to a dying-bed, as I now am.
I feel peace and true consolation with the Lord, and my love herein dearly salutes you,
and bids you all farewell, who am your dear and tender sister,

[.signed-section-signature]
Mercy Johnson

--

[.asterism]
'''
TACY DAVIS, wife of Richard Davis, of Welsh Pool, in Montgomeryshire,
formerly dwelt in London, but after her marriage,
removed with her husband to Pool aforesaid, where were few or no Friends at that time,
which was about the year 1659.
She had a public testimony in meetings, and was instrumental to bring many to the truth,
and was an entertainer, with her husband, of strangers,
and a nursing mother to those in prison for the testimony of a good conscience.
They lived together to old age,
and she cheerfully went through the various exercises and hard sufferings which attended,
in those days, those that professed the blessed truth.

She was taken sick the 29th of the Second month, 1705,
and had been at a meeting the same day, which was kept at their house about forty years.
After the extremity of her pain was somewhat abated, she said,
'`People do not think it so hard to die, as I find it;`' and prayed thus; '`O Lord,
accept of me in your well-beloved Son, Christ Jesus.
I have loved you with all my soul and spirit.
I have kept your commandments.
Oh!
Lord, bless my family with all heavenly blessings;
grant to them that they may live in your fear.`'
She said to the servant-maid, who was not a Friend,
'`Remember your Creator in the days of your youth;
leave off your vanity before such a day as this overtake you.
I have nothing to do but to strive with this natural distemper.
I loved the Lord in my young days, and he kept me from many evils;
and when he was pleased to make known his blessed truth to me,
he helped me to work out my salvation with fear and trembling.
That work I have not to do now; the Lord Jesus Christ did it in me,
and for me;`' upon which the maid wept much.

At another time, pain coming on her, she said, '`I feel I am of a strong constitution,
and that nature would not yield to my distemper;`' and prayed fervently, saying, '`Come,
Lord Jesus Christ, come quickly and put an end to my pain.
Lord, I long to be with you forever.`'
Another time she prayed, '`Lord, I am the workmanship of your hands;
you have often helped me in the time of need,
for your name`'s sake help me now in the time of my distress; you are my God, my hope,
and my help, I will trust in you, oh my God!
Oh God! hasten your coming for your son Christ Jesus`'s sake.`'
Another time she said to her husband, '`I have done too little for the Lord.`'
Her husband put her in mind of her many former services,
and particularly visiting his servants when in prison for Christ`'s sake,
feeding them when hungry, entertaining strangers, and when sick,
very tender in helping them, etc., she replied,
'`All this is too little to do for the Lord Jesus`'s sake, who has loved us.
We must not depend upon these things,
but we must depend and trust in our Lord and Savior Jesus Christ;
and when we have done all, let us account ourselves unprofitable servants,
for we have done but that which was our duty.`'
A little before she died,
she desired her husband to praise the Lord with her for all his mercies, and said,
'`At this time I feel his living presence to my great comfort.`'
She prayed herself, saying, '`O Lord, you have been a father to me,
you have kept me from evil, and now I trust in your great name,
that you will not forsake me; for your Son Christ Jesus`'s sake, take me to yourself.`'

And she was heard: about the sixth hour in the afternoon,
on the First-day of the Third month, in the year 1705,
the Lord in his love and mercy took her to himself,
in great quietness and peace of spirit, in about the ninetieth year of her age.

[.asterism]
'''
MERCY EMIES, was the wife of Charles Emes, of Warwick, and daughter of John Garner,
of Kinningsworth, of the same county, yeoman.
Her first husband`'s name was Charles Devalc, a Frenchman,
who was formerly a priest of the church of England, and chaplain to the Earl of Essex,
but for conscience-sake he left that church, and joined with the Baptists in London;
among which people he continued until his death.
The said Mercy, before she was his wife, attended upon the countess of Ranclagh,
from which family Charles Devale married her.
She did from a child seek after the kingdom of heaven,
and when she was among the Baptists,
was dissatisfied with the doctrine which she often
heard preached of God`'s absolute reprobation of men;
and upon that account sought for a people who had better tidings to preach.
In her inquiry she came to a meeting of the people called Quakers,
where she heard preached the "`free grace of God, which brings salvation,
that it appeared to all men, teaching them to deny ungodliness and worldly lusts;
that we should live soberly, and righteously, and godly, in this present world, etc.`"

From that time she, with two other of her acquaintance who were with her,
left the Baptists and embraced the truth,
and joined in fellowship with the people called Quakers;
among which people she married Charles Emes.
She often praised the Lord for the knowledge of his truth,
which she loved and valued above all outward enjoyments,
and ordered her conduct according thereto, unto the end of her days.

Her sickness held her about five weeks,
in which time she said it was a good thing to be ready to die,
and not to have that work to do when we are to leave the world.
The Lord was large in his love to her;
for which she blessed his name in the sense of his mercy;
and as her friends and neighbors came to visit her,
she exhorted them in great love and tenderness,
which caused much brokenness of heart among them.
One visiting her, she said, '`I have a love to you; you are convinced, but not converted;
hold on your way, the Lord will do you good.`'
Another time, two friends visiting her, one inquired how she did, she answered,
'`I am a dying woman; I am going to my God and your God;`' she said,
'`Why so long coming to see me?`'
he told her the reason: she replied, '`Your heart is towards Zion,
and so is the other friend`'s; keep your shoulder to the work which God has put upon you;
hold him forth to the nations; be not ashamed of Christ, he is a glorious Savior;
if I should live I must declare it; if I live I cannot hold my peace.`'

She testified to the service of women`'s meetings, saying,
'`Women have a service for God as well as men, and women`'s meetings are of service,
and this is my testimony before I die.`'
To a friend who was under some doubtful thoughts, she spoke by way of encouragement,
saying, '`You will meet with many troubles,
but it will be well with you in the end;`' with more words to that purpose.
She spent much of the time of her sickness in praising God.
The day before she died,
she spoke to several friends concerning their states and conditions in the truth.
She was freely resigned to die, and nothing seemed hard to her to part with,
except her two little children, of whom she often said,
'`My little babes;`' but she declared her satisfaction
that the Lord would provide for them,
which is in part fulfilled already.
A few hours before she died, her husband coming to her bedside about midnight,
found her pouring out her soul to the Lord, and she said to him,
'`The sting of death is taken away; I am not afraid to die.
I have the evidence of God`'s love sealed to me:
my bed is a bed of roses;`' which expression she used several times in her sickness;
so resigning her soul unto the Lord.

She finished this life the 31st of the Eighth month, 1697,
and was buried among friends at Warwick.

[.asterism]
'''
SARAH KIRKBRIDE, wife of Joseph Kirkbride, of Pennsylvania, and daughter of Mahlon Stacy,
of West Jersey, in America, was virtuous from her childhood,
and very dutiful to her parents, and an example of piety to her latter end.
She was taken sick the 24th day of the Ninth month, 1703.
In the time of her sickness she uttered many living and weighty expressions,
desiring to be dissolved, saying, '`I have not been afraid of death these many years;
death is no terror unto me; my God has taken away its sting.`'
She being under great weight of bodily affliction,
and seeing her husband under trouble for her, said, '`My dear,
if it please the Lord to strip you of your help-mate again, my God will be your rock,
he has been your stay hitherto, and he will never leave you.
The Lord will bring me to his holy hill, and I shall praise him upon Mount Zion,
with the saints and holy angels.`'

She again said, '`I shall praise you, O my God, and my Christ, world without end.`'
Soon after, her husband was moved to pray by her,
that the Lord would be pleased to support and strengthen
her in her distress and great affliction,
and to bear up her exercised soul,
and to make them truly willing to submit to his holy will, whether in life or death;
at which words she said, '`Amen, Amen.`'
A little after, her husband asked her how she did, she said,
'`I am sweetly comforted in my affliction; the Lord is exceeding good to my soul.`'
Many more good expressions she uttered upon several occasions, that cannot be remembered.
The evening before she departed this life, some friends being come to see her, she said,
'`I am weak of body, but the Lord is very good to my soul,
and has filled me with his love; but my bodily weakness is such,
that it renders me incapable of praising him as I ought to do.`'
To her husband she said, '`The Lord has heard your prayers for me this morning,
and has satisfied my soul to the full;`' more she said to the same purpose,
taking her husband`'s children by the hand, embracing them,
and exhorting them to fear the Lord, and to love and obey their father; and said,
'`He has been a good father to you.`'
A little before she died, she said, '`My God, I come,
I come;`' and soon after she departed this life,
and is entered into that rest that will never have an end.

She died the 28th of the Ninth month, 1705, aged twenty-nine years.

[.asterism]
'''
SARAH THOMPSON, daughter of George Thompson, of Crook, in Westmoreland, was a maid who,
in her life-time, did truly fear the Lord,
and remembered her Creator in the days of her youth.
She sought the honor and promotion of truth,
according to the measure of grace which she had received;
and according to the understanding God had given her, she was faithful,
and her understanding was good, and capacity large in things natural,
as well as religious.
She took great delight in reading the Holy Scriptures, and other religious books,
and was careful to put in practice what she did read,
and would often be speaking of heavenly things in the family,
and exhorting to virtue and patience;
for it was a great trouble to her when she saw any
impatience or indifference in the family.
She was obedient to her parents, and very tender over them;
kind and compassionate to all, and was beloved of them that knew her.
Her temper was sweet, and of a cheerful spirit and good courage, but not rash,
and of few words,
and very careful not to give offense to those she was at any time in company with,
who were not of our profession in religion,
and very sorrowful when she saw any professing the truth,
who did not walk answerably to the same.

She was much afflicted with shortness of breath, which she patiently bore,
and would say she dared not murmur at it, lest she should offend the Lord.
She often retired alone into solitary places, and said that when she had been alone,
and meditating upon the things of God,
that the Lord did wonderfully break in upon her soul,
by his glorious light and good spirit, and let her see over the world, time,
and mortality, into eternity, which appearance of his presence did very much affect her.
She also said that the Lord had showed her that the time would
not be long until he would ease her of all her pain and sorrow,
and take her to himself.
Another time she said the Lord was present with her,
and comforted her in the midst of all her afflictions,
and spoke peace to her soul in the midst of her troubles,
which she said made hard things easy to her.

She sickened the 1st of the Twelfth month, 1702.
In the time of her illness the Lord`'s power and presence attended her,
and she uttered many weighty expressions, with wholesome counsel and advice,
to the comfort of those about her.
Observing her friends sorrowful, she said, '`You trouble me to see you so;
why are you so unwise?
It would be more satisfaction to me, if you did not one of you shed a tear for me;
must we not all part?
What! is death a terror to you?
It is no terror to me.
I am not at all daunted at it, for I am content whether I live or die;
for if I am spared at this time, you must not keep me long,
having been sensible some time, that I have not long to live.
Cannot you freely give me up, and part with me?
I am but a poor infirm creature, and it will be well with me.
I shall be freed from many troubles, and from many dangers,
which you will be exposed to that stay behind; for I see as long as we are here,
we are liable to many temptations.
I know they will be exercises to you, but keep to that which is good,
and God will keep you, for he has kept me many a time, as I have kept my mind to him.`'
This she spoke on the Sixth day of the week, in the afternoon.

At another time, her father and mother, and two sisters, standing at her bedside,
she said to them, '`I must die; and I have a word of counsel to you all;
be faithful to your gifts that God has given you; I beg it of you;
and overcharge not your minds with any thing of this world,
for you see how frail flesh is,
and how soon we are gone;`' with many more weighty expressions which were not remembered.
After this she said, '`I desire you to remember my words when I am gone,
that it may be well with you at your latter end,
that you and I may meet in the mansions of glory, where we may never part.
And be all of you content, for it is well with me.
I have made my peace with God, and I feel nothing to rise up in judgment against me,
for the Lord has forgiven me my sins and mine iniquities,
and I feel my mind is very quiet and still,
and has been ever since I begun with this illness.
There is nothing cumbers my mind, not so much as a temptation is presented,
and I have been borne over my exercises far beyond my expectation.`'

Her brother Isaac being from home, in the service of truth, she said,
'`Remember my dear love to my dear brother.
If I die, tell him from me, that my soul is gone into everlasting rest,
where I hope we shall meet again in the heavenly joy, where we shall never part.
I think I have done,
and I will take my leave of you;`' then taking them one by one by the hand,
she kissed them, and bade them all farewell; and said,
'`I do not know when my life will go; I would gladly die.`'
She prayed to the Lord, and continued in prayer a considerable time;
in which she was very powerful, and was filled with divine praises,
and the power of God was felt by them that were present with her,
and their hearts were abundantly comforted,
and were made to bless the name of the Lord on her behalf.
She prayed fervently for the preservation of those
who should he left behind when she was gone;
he had kept and preserved her from the many hurtful things that are in this world,
and that he would help them through their exercises, as he had helped her many a time,
for which she blessed his name,
and so concluded her prayer with returning living praises and thanksgivings unto God.
Then she signified to them how she had felt the
Lord`'s power to support her in her life-time;
'`for,`' said she, '`I have often cried to the Lord to help me through my exercises,
and he has answered my prayer many a time, to my great admiration.`'

She lay still a while, and afterwards began to pray again to the Lord,
with a heavenly sweet melody, which did attend her; but she spoke so low,
few of her words could be distinctly understood by them that were present.
Then she asked for her grandmother, who was above eighty years of age, who coming to her,
she took her by the hand, and said to her, '`You are now very ancient:
the Lord has been very merciful to you, and has given you many years,
far above what many attain to; and if you come short of making your peace with God,
you can not say it was for lack of days.
But see to the improvement of your gift, I beg of you before your days be over,
that it may be well with you at your latter end,
that your soul and mine may meet again in heavenly joy.`'
Her cousin, Robert Thompson, a young man, coming in, asked her how she did; she answered,
'`I am passing away in peace, and so may all do that keep faithful to their God.`'
forever, Then lying quiet, and slumbering a little, afterwards said,
I have had a sweet dream;`' her mother asked what: she answered,
'`I thought there were four angels that were conducting me to the land of rest.
I have had this dream, '`said she, '`twice over, but I am here yet.
I am long a going, you have waited long: '`her mother said,
'`Your death is hard to win;`' she said, '`It will come by and by,
I have prayed to the Lord to make my way easy through death.`'

Her sickness increasing upon her, she grew very weak,
so that it was thought she would not have spoken any more,
it being about two hours before her departure,
yet the Lord was pleased to give her strength again,
so that many weighty words proceeded from her,
to the tendering of the hearts of them that were about her, both friends and others.
Speaking to her father and mother, desiring them not to mind the things of this world,
but to serve the Lord in their day, who is worthy to be served, who is the Lord of lords,
and the King of kings; desiring them to remember the words of their dying daughter;
exhorting to love and charity, and to be prepared for their latter end,
where they might meet in everlasting joy, never to part.
Then asking for her cousin above-named, he came to her, and she said, '`Dear cousin,
whom I love as my own soul, you are young, and in the prime of your time,
see you serve God in the flower of your age.
The Lord has created you that you might serve him;
see you answer the end for which you were created.
And dear cousin, I believe the Lord has a service for you if you be faithful to him,
and I wish well for your soul, as for my own,
desiring you may be faithful to God in your day, that you may have your account ready,
against the day of dissolution, that you and I may meet again,
where we shall live to sing Hosannah to the Lord forevermore.`'

Asking for one who was related to her, she said,
'`I have something to say to him;`' he coming to her, she said to him,
'`I remember there was a time when you thought you should have died,
and you were under great exercise, for I believe you had lived a very loose life,
and the Lord smote you with his judgments, and I remember you made a vow,
that if the Lord would spare you at that time, you would amend and do so no more;
and it pleased the Lord to spare you; but oh!`' said she, '`have you fulfilled your vow?`'
She exhorted him to more faithfulness, that he might obtain peace to his soul,
before the day of his visitation went over his head.
She said to her sisters, '`Be sure you be good to my mother when I am gone,
and mind not the fading things of this world;`' after which she spoke not many words;
but if she was asked how she did, she would reply, '`I am very well, and in a sweet frame;
I am going to a sweet place!`'

She departed the 6th day of the Twelfth month, being the Seventh day of the week,
about the first hour in the afternoon, 1702.
Aged nineteen years.
