== Chapter 11

[.chapter-synopsis]
* James Baines
* John Blaikling
* Thomas Gilpin
* Richard Andrews
* Priscilla Richards
* William Turner
* Francis Blaikling
* Richard Vokins
* Elizabeth Wills

JAMES BAINES, son of William and Sarah Baines,
of Strangerthwait in the county of Westmoreland,
was one who began to seek the Lord in his young years.
As he grew in sincerity and zeal for the blessed truth,
and increased in his concern for the promotion thereof, some time before he died,
God opened his mouth in a public testimony for the Lord Jesus Christ and his pure religion;
in which he was very fervent,
having a sight how eminently God would appear for those who were faithful.
He had a word of encouragement to them,
but was sharp in judgment to the backsliders and unfaithful:
and although he was under much affliction,
by reason of bodily infirmities and distempers which grew upon him,
yet he was more and more devoted to truth`'s service,
as if he had known that his time was not to be long in this world,
even to within some hours that his last sickness seized upon him.
Notwithstanding he was under great pain and exercise of body,
yet the power and presence of the Lord were with him,
which was his great support and strength.
He often spoke of the goodness of God to his soul, and of that inward sweetness,
peace and comfort, that the Lord was pleased to afford to him in his afflictions,
to the great satisfaction of those who were present.

He gave much wholesome advice in the time of his sickness to Friends and others,
and spoke of the prosperity of truth, and said in particular to his relations as follows:
'`As we are children of believing parents, and have had our education among Friends,
so I would not have you to rest contented there, but be solid, and weighty,
and humble yourselves under the mighty hand of God;
and as you abide here you will feel the goodness of the Lord to spring in your souls,
to your great comfort and inward peace and satisfaction.
I know our natural tempers are inclinable to be light and airy, like other people,
therefore we have more occasion to be bowed and weighty in our minds.`'
Speaking concerning tithes,
he desired Friends would keep up their testimony against them; '`For,`' said he,
'`I could have slipped sufferings if I would have given way to it,
but it was a thing I dared not do;
but I accounted it a great mercy that the Lord had blessed me with
something to part with for his name and truth`'s sake.`'
Although he suffered pretty much at times, upon the account of tithes,
yet the Lord`'s goodness to him did overbalance all,
so that he had a word of encouragement to others on that account.

Upon occasion, speaking of the uncertainty of riches, he said,
'`At some time I pursued them,
and they fled from me;`' but this use he said he made of
it;`'to conclude it was not a city here I was to look after,
but one in the heavens, whose maker and builder is God.`'
This he spoke as caution to others.
At several times he expressed his great peace with God here,
and full assurance of eternal blessedness in the world to come,
through the atonement made by the Lord Jesus Christ,
and the work of sanctification of his Spirit.
The day before he died, hearing that that ancient Friend, Anne Camm, was deceased,
he said, '`Ah! that honest, honorable woman, is she gone to her eternal rest before me?
I shall follow her very shortly, where we shall meet never to part again.`'
Many were the comfortable expressions and seasonable
advices which he gave forth in his sickness,
that cannot be remembered; and as, in his lifetime, he honored the truth,
so was his latter end comfortable and full of peace; in which he departed this life,
the 1st of the Tenth month, 1705, aged fifty-one years;
and was buried at Friends`' burying-ground, at Sedbergh meeting-house.

[.embedded-content-document.testimony]
--

[.letter-heading]
The Testimony of Isaac Alexander concerning James Baines,
in a letter dated the 8th of the Tenth month, 1705,
who also died the 11th of the Twelfth month, after him.

Our truly beloved and esteemed friend, James Baines,
departed this life the 1st of this instant; and though he was afflicted with great pain,
yet he bore it with admirable patience.
Though I live remote from him, and notwithstanding my unfitness,
I went often to visit him; and I do not remember that since I came among Friends,
any Friend was so universally visited by all sorts of people as he was,
especially by faithful Friends.
Neither did I ever visit a Friend in such a case,
who had that reach upon all sorts of people,
both in the expressions he declared in the time of his sickness,
and also the frame of his spirit.
It was admirably reaching and melting, beyond what I can express,
and so continued to the end, as sweet and sensible as ever.
He died with the greatest esteem and love to Friends and truth,
and in great esteem and interest in the hearts of Friends;
he died in a most happy and blessed condition.

[.signed-section-signature]
Isaac Alexander

--

[.asterism]
'''
JOHN BLAIKLING, of Draw-well, In the parish of Sedbergh, in Yorkshire,
bordering on Westmoreland, was born in the Ninth month, 1625, and he and his wife,
and his father and mother,
were people of good repute and esteem among all that knew them,
being all very religiously inclined from their youth.
They were all convinced of the truth in the Third month, 1652,
by the ministry of that truly honorable servant of Christ, George Fox,
whom they received into their house with joy,
because of the glad tidings of salvation that he brought to them;
soon after which John Blaikling accompanied George Fox to Firbank chapel,
where many were also convinced of truth.
About the latter end of the year 1654, or beginning of 1655,
John Blaikling received a dispensation of the gospel to publish to the world,
and was very serviceable therein to many, and soon after,
he was called by the Lord into the county of Durham, Northumberland,
and the east of Yorkshire, where he had then,
and many times since in his frequent visits of those places, good service,
and was with great respect received and loved while he lived.
A few years after, he travelled into Scotland, visiting a great part of that nation,
and in his return, as well as going out, visited the northern counties of England.
After it pleased God to raise up others to bear testimony
of his truth in the meeting John Blaikling belonged to,
and the adjacent meetings, to answer the service in part,
which before lay much upon John, he was not only glad thereof,
but a great encourager of them,
and all others at all times that came up in a public testimony for the Lord Jesus Christ,
who is the true light.

He also travelled into many other cities and counties; as at London, Bristol,
Lincolnshire, Norfolk, Suffolk, and Essex, and most counties of England,
and many times to London;
in which service he faithfully continued till weakness of body and old age prevented.
The last time he visited London, was when he came up to the yearly meeting in 1698;
that service being over, he visited the most of Friends`' meetings in the county of Kent,
and his service was very acceptable among them.

He was endued with a great gift of discerning, of solid judgment,
and deep understanding in heavenly things,
as well as in the things relating to this life; his ministry was attended with power,
and though his utterance was not eloquent, yet full of profound and weighty matter,
suitable to the several states in the auditory where he did minister.
He was an example in a tender, humble life and conduct,
and zealous for good order in the Church of Christ,
as well as steadfast in opposing and bearing testimony
against such as would endeavor to break unity,
and so lead into a loose liberty, disorder, and confusion, as well as other evil works.
It was at J. Blaikling`'s house, which is called Draw-well,
that the memorable meeting was held for the endeavoring the recovery of John Story,
and John Wilkinson, and others,
who opposed the good order and discipline now established in the churches of Christ.
The said meeting began upon the 3rd day of the Second month, 1676,
and continued four days:
but notwithstanding the labors of many brethren met
at that time from several parts of the nation,
and particularly four Friends from the city of London,
the said John Story and John Wilkinson continued
in their contention and opposition to Friends;
and not long after William Rogers published a book against Friends, which J. Blaikling,
etc., answered, entitled '`Anti-christian treachery discovered,
and its way blocked up;`' a volume in folio, of about 50 sheets.

He was a great supporter of such as were in low circumstances in the world,
often assisted them in difficult cases, to the exposing himself to great hazard of loss;
and many times he was blessed with good success therein.
He obtained the blessing of a peace-maker, being of a good understanding,
was qualified with judgment and patience to reconcile differences about temporal affairs,
which was a means to bring him into many concerns of trust for orphans, etc.,
which is always attended with great care and trouble, and which often fell to his lot.
The loss of him in the church, as well as among the neighborhood, is great.
He was not only called to believe in, and preach Christ Jesus, the truth, the way,
and the life, but also to suffer for his name`'s sake,
not only by loss of goods to a great value,
but also by imprisonments several times at York, about sixty miles from his family,
both on account of meetings for the worship of God,
and in a firm testimony against tithes.
While he had strength, he was diligent in attending meetings;
but old age and bodily infirmities growing upon him latterly, sometimes prevented him.
Several times he expressed to friends in private the comfort that he had in the
Lord`'s peace and presence with him to his satisfaction in his old age,
and that his day`'s work was nigh done, and his reward and rest with God sure.
This testimony agrees with the last letter I received from him, save one part,
as follows:

[.embedded-content-document.letter]
--

[.salutation]
Dear John,
I love you in the truest love that springs from Jesus Christ the fountain thereof,
by and in which my life stands;
though as to bodily health and strength I grow weak and feeble,
but my life in God stands, whose I am, and I am comfortably content.
I am scarcely able to walk to the door, nor have I been at a meeting these several weeks,
but the Lord`'s will be done.
I am comforted in the remembrance of my former services for the Lord, his truth,
and people, for which I lack not my reward in this my old age.
I take time to read.
I am almost blind, yet well content.

[.signed-section-signature]
John Blaikling

--

He often signified his preparedness to leave this world,
with fervent desires for truth`'s prosperity,
and the preservation of unity and concord among brethren,
in a faithful and steady testimony for the same in every part thereof,
as led into by God`'s power in the beginning.
Not long before his death,
his ancient and intimate friend and acquaintance Thomas Camm being with him,
he said to him, '`You and I have not sought our own interest,
but have devoted ourselves to serve the Lord, his truth and people; he is,
and will be our great reward in the end of all our troubles.
I am greatly satisfied that I have faithfully served the Lord, and done my day`'s work,
and enjoy the earnest of that peace and rest God has laid up for his people;
and if you and I shall never have opportunity to meet again in the outward,
yet in eternity our spirits, with the spirits of just men made perfect,
shall meet never to part again.
I pray God with all my soul, if it be his will for his truth and people`'s sake,
to lengthen your days, and grant that strength of body and health,
that at least you may be able once more to visit London, Bristol,
and the southern parts of this nation, which will be of great service,
and acceptable unto many.`'
This he spoke with great tenderness of spirit; to which Thomas Camm replied,
'`The will of the Lord be done, I am in his hand:
'`so in much brokenness embracing and kissing each other, they parted;
this was four or five days before his death.
He had a short sickness, and an easy death, falling into a fainting fit,
as sometimes before.

He passed quietly away out of this world, without sigh or groan,
short about four months of eighty years,
and was honorably buried at Friends`' burial-place, at Sedbergh meetinghouse,
the 4th day of the Fifth month, 1705.

[.asterism]
'''
THOMAS GILPIN was born in the year 1622, son of Thomas Gilpin, of Mill-hill,
in the parish of Caton, near Lancaster.
His parents had five sons, and five daughters, whereof Thomas was youngest son;
they were people of good repute in the country, and were religious,
being called Puritans, who educated their children very strictly.
After his father`'s decease, his mother removed with her children to Kendal,
in Westmoreland, five of her children being dead;
and she was so zealous as to force them into acts
of religion before they knew what they did,
as to pray without a form, etc.
Thomas being but about ten years of age, considered it was not right,
for he said he knew not who to pray to.
After he grew up in more years, and his mother deceased,
he ran into foolish and wanton delights, as sports and pastime, music and dancing.
He went to London as apprentice to a tallow-chandler, and after went into the wars,
(being the time of the civil wars in England,) where he was tempted into more evils.
Yet in all this time the Lord followed him by his good spirit,
reproving him in his own conscience for his sins,
which brought great fear and trouble upon him;
but by one means or other he endeavored to get over these convictions,
and so continued a considerable time striving against the good spirit of God.
But oftentimes the Lord again did awaken him,
and brought the consideration of death upon him, even in the time of sickness,
and of battle, which he was often in.
Then he would cry to the Lord for mercy,
and that he would deliver him from death at such times,
making promises of reformation for the future.
And God was merciful and spared him, yet he forgot his promises and covenants,
and fell into the same evils again;
after which the Lord brought double fear and torment upon him.

At last he received the blessed truth, as preached by the people called Quakers;
and in believing in and obeying the light and spirit
of Christ manifested in his own heart,
he came to receive power over those sins which had prevailed in times past over him,
and so came truly to know repentance, and remission of sins, in the name of Jesus Christ,
the true light of the world.
And afterwards,
in the remembrance of the unspeakable long-suffering and mercy of God unto him,
he said in his life-time,
'`Shall it not be recorded to posterity for the benefit of my children,
and my children`'s children, that it may be a warning to the obstinate and rebellious,
to turn from the evil of their ways, while the spirit of the Lord strives with them,
lest the day of their visitation go over their heads.`'

In 1653 Ambrose Rigg, Thomas Robinson, and Jane Waugh, came into the county of Oxford,
to preach the free gospel of the grace of God;
at which time Thomas Gilpin received their testimony.
After eight or nine years waiting upon God in silence,
God gave him a dispensation of the same gospel to preach to others,
and he became an able minister, showing himself approved unto God,
a workman that need not be ashamed, rightly dividing the word of truth.
In this service he labored much, traveling through many parts of England,
but chiefly in the counties of Oxford, Berks, and Bucks;
he was a prisoner for his testimony to the truth twice at Oxford,
and once in Newgate in London.
His settlement was in the parish of Warborough, in the county of Oxford,
where he married Joan, the daughter of Thomas Bartholomew, of the same parish,
husbandman;
in which place he was instrumental to settle a church
or meeting of the people called Quakers,
which remains to this day, as well as in many other parts where he travelled.
He was successful by his ministry to turn many to righteousness,
and for building them up, and establishing them in the most holy faith.

In the year 1702, and the eightieth of his age,
he was weak in body for the most part of the winter,
but complained little of either sickness or pain, his body gradually decaying.
In the time of his sickness he desired one of his
sons to remember his dear love to friends,
and give them account of his sickness and departure.
As he was zealous for God and his truth in the time of his health, so he was to his end,
for he went to Friends`' meetings for the worship of God as long as he was able, saying,
'`I am willing to be a good example so long as I have strength to go.`'
When he was so weak that he could hardly go out of his chamber,
he desired friends to meet in his room, which was not long before he died;
at which time he signified to friends that he was satisfied,
that as to words he must cease, but this was his comfort,
that he enjoyed the power of the Word of life, which is beyond all words.
He exhorted friends to faithfulness, and to keep their meetings,
and not to look out at his being removed from them;
putting them in mind of the goodness and love of God,
which had been largely manifested both to him and them,
in carrying them through many trials and exercises,
and in preserving them in love and unity one with another,
which he desired they would be careful to continue in.
When he had done speaking, a friend prayed,
and Thomas Gilpin`'s heart was much comforted in feeling the presence of the Lord,
as well as those present, who were much tendered and broken into tears,
and at the conclusion he again recommended love and unity one with another;
and also declared that he was given up in the will of the Lord,
and took his leave of them all.

This was the last meeting he had with friends; but he was much visited by friends,
and it was a comfort and delight to him to see them,
and sometimes it was hard for him to part with them, saying,
'`This is such a parting as we never had before.`'
The Lord was very good to him all the time of his sickness,
and did often cause his heart in the feeling of life
to sound forth praises to the name of God;
and he said he believed he as much desired to die, as ever any one did desire to live,
although he lacked nothing in this world; but said, '`I long to be dissolved,
and be with the Lord, yet am willing to wait God`'s good pleasure.`'
The day before he died, i.e. the 2nd of the 12th month, some friends visiting him,
he desired one of them to supplicate the Lord on his behalf, to put an end to his days,
and make his passage easy.
After some time the friend prayed to that purpose; when he had done,
Thomas Gilpin lifting up his hands, said,
'`The Lord grant your request which you have made to him this day.`'
Though at that time to outward appearance he seemed likely to have lived some days,
yet he quickly altered, and the morrow, about the fifth hour in the afternoon,
he departed this life, being the 3rd day of the Twelfth month, 1702.
He left behind him three sons and two daughters, and all of them had children.

He was buried honorably the 8th of the Twelfth month, 1702,
after he had professed truth forty-nine years,
and had been a minister of the gospel forty years.

[.asterism]
'''
RICHARD ANDREWS, son of Richard Andrews, late of London, silk-man, and his mother,
one of the daughters of our ancient friend, Thomas Gilpin aforesaid,
was educated by his father-in-law, Moses West, of Hempsted, in Hertfordshire,
and his own mother, not only in useful learning,
in order to his accomplishment for trade and good settlement in the world,
but also it was their great care to have him brought up in the way of truth.
He was put apprentice in London to the silk trade; but after some years,
what by the examples of others, and temptations of the enemy,
he declined from his former simplicity and sobriety, and good inclination to truth,
into more liberty and vain company and fashions of the world,
which was a grief to his father and mother.

He was taken ill about eight or nine months before he died, of a decay of nature,
which terminated in a consumption; and such was the goodness of God to him,
that he was awakened in himself to a consideration of his inward condition,
the visitation of God by his spirit being upon him,
and he had frequent visions in the night of the near approach of his latter end.
Being at Hempsted with his father and mother,
he had opportunity to retire alone into private places,
where he poured out his soul to the Lord in supplication,
and great travail of soul came upon him, especially towards his latter end,
for he was bowed in deep humility, praying for the light of God`'s countenance,
in whose presence is life, peace and comfort.
But the Lord was pleased to chastise him, by hiding his face from him for a time,
yet he kept his hold, trusting in the Lord;
though in this state he met with many assaults from the devil,
and temptations to despond of God`'s mercy.
Now he knew what it was to read in the book of conscience,
and for his works to go beforehand to judgment.
Now he disliked the company of those young men, his former companions,
with whom he us to walk abroad in the fields, sometimes on First-day afternoon,
and neglecting going to meeting for the public worship of God,
which now became a very great trouble to him,
and that he should spend his precious time so vainly.
His powdering and apparel, and such like follies,
he particularly expressed a great sorrow for,
promising that if the Lord should prolong his days,
he would endeavor to follow the best examples and
strictest way of living among faithful Friends;
calling to mind, and praising the good life of his grandfather Gilpin.

A friend visiting him,
together with the good advice of his father concerning the Lord`'s hand that was upon him,
it being not in anger but in mercy, that he might turn unto him,
with fervent desire after him, and enjoyment of him, and when he should obtain that,
his needs should be supplied; so after some time the Lord did appear in him,
and did lift up his spirit as a standard against the enemy of his soul,
who came in like a flood, and tempted him to doubt of his mercy,
so that he was comforted like a man reprieved from judgment,
though not as yet having a full assurance of his pardon;
but a living hope sprang up more and more, which became as an anchor to his mind.
His company became delightful, because of those serious reflections he made on things,
and religious discourses which he had with those about him.
One time he said to his father and mother, '`I will appeal to you,
if you ever heard me repine at the exercise and pain
I have gone through since I have been at home,
all this time of my great weakness?
No, '`said he, '`I have desired the Lord to let me have all my punishment in this life.`'
Indeed, he was sweet and cheerful under all his pain, which was very great;
and he grew very bright and living when he had got dominion over his doubts and fears.

Near his latter end, through the prevalence of his distemper,
he was somewhat broken in understanding, and wandered in his discourse,
though his talk was inoffensive; yet, as if he had foreseen this, a little before,
a kinsman of his, not one called a Quaker, offered to tarry with him;
to which he showed himself unwilling, giving this reason to his father and mother,
saying, '`May be I shall be light-headed, and ramble in my words,
and he or others may inconsiderately reflect upon my profession.`'
Though his sickness was long, his death was pretty sudden,
having kept his bed but four days, in which time, while sensible,
he was kept in a most sweet, resigned frame of soul;
being by his bedside was like being in a well-replenished meeting.
Near his end, he said to his father and mother, '`Do not grieve, the Lord is with me,
'`with much more to the same purpose; so lying still and quiet, he went away with a smile,
and is at peace with the Lord.
He died about the twenty-first year of his age.

[.asterism]
'''
PRISCILLA RICHARDS, daughter of John Richards, of Howsey, near Liskeard,
in the county of Cornwall, and of Priscilla his wife,
was born at Liskeard the 18th of the Sixth month, 1680;
and though educated in her father`'s family,
who were mostly strangers to the living way of truth, now in this our age revealed,
only her mother frequented the meetings of the people called Quakers;
yet did this young maiden begin according to the advice of the wise man,
to remember her Creator in the days of her youth.
She not only came to the meetings of the said people,
but turned with her heart to the Lord; and as she came towards seventeen years of age,
she grew in the fear of God, and in plainness and solidity,
not regarding the gaiety of this perishing world so as to set her heart thereon,
but became very modest in her habit, speech, gesture, and in all her deportment,
and was greatly in love with the company of the best Friends,
to whom she also became very acceptable.
Though the family in which she lived might minister occasion to her,
to look out at the ways and glory of this world, yet she was as one weaned therefrom,
and delighted in retirement of spirit,
and in that society which might be helpful to her in her
way to that heavenly habitation to which she was traveling,
and whereunto the Lord brought her in the very prime of her blooming years.

She was scarcely twenty years of age when she was visited with some infirmities of body,
which still drove her nearer the Lord;
and although she met with some exercises grievous to her tender spirit,
yet she was resigned to the will of God.
About the beginning of the year 1704, it was perceived by some symptoms,
that her distemper tended to a dropsy, in which abundance of care,
both of parents and able physicians was used, yet her disease increased,
so that it was apparent some months before she died,
that there was little or no hopes of her recovery, which she foresaw,
yet was very well satisfied and resigned to the will of God,
in which she had peace and great quietness of mind,
and would often testify as much to her mother and those about her,
as well as friends who frequently visited her;
for she having her affections drawn out of the world,
it became easier to her to leave it.

In a letter to a particular friend, who married her near relation,
written about fourteen days before she died, she says thus:

[.embedded-content-document.letter]
--

[.salutation]
Dear Cousin,

I should have given an account of my sickness, but exceeding illness hindered me,
and my mother, what with sorrow for me, and lack of time, occasioned the same neglect.
I am now very ill, being swollen all over my body, except my hands and arms,
and am scarcely able to walk the chamber without help;
but I am freely given up to the will of my heavenly Father, whether for life or death.
I should be glad to see any of you here,
for my time in this world is not likely to be long.
I have been a little better at my heart this four or five days,
but how it will please the Lord to deal with me, I know not.
My dear love is to you, your wife and children,
wishing you health and peace in this life, and happiness in the life to come; being,
dear cousin, your affectionate, etc.,

[.signed-section-signature]
P+++.+++ Richards

--

This was written in a time of great weakness of body,
but her spirit was strong in the Lord, having kept the faith,
and by it was made a conqueror.
About this time, her mother sitting by her, she said,
'`It is well for me that I feared the Lord in my youth,
seeing old age is not likely to be my lot.`'

Those friends who visited her in the time of her weakness,
were greatly comforted in the testimony she gave,
and sense they had of.her living condition of soul, in a dying state of body.
To a friend who said to her, '`I hope, if you do recover,
you will live to praise the Lord;`' she replied,
I do not desire life upon any other terms.`'
Her expressions were many and frequent as to her peace and acquiescence of mind, but,
her friends not supposing her end to be so near, they were not duly written down.
Her mother at a certain time,
hearing her speaking of her willingness to be with the Lord, said,
'`What! have you no sympathy with my sorrow and grief, at the parting from you, etc.,
she replied, '`Mother, you begin to grow old,
and it will not be long before we meet again in a better place,
if we are found doing the will of God.`'

In this sweetness of temper she abode without reluctancy
or impatience at her state of body,
which decayed daily.
On the twelfth of the Seventh month, 1704, she was taken with some fainting fits,
which made her attendants stir more than usual, at which she reviving said,
'`Why did you not let me alone, I was very easy,
and in much quiet;`' and then turning to her mother, she said, '`Time will come;
do not grieve, nor make the Lord angry.`'
To some about her, '`Do not leave repentance until a dying hour,
for the body has enough to do to bear its pains.`'
At night, her father going to bed, took leave of her.
She said, '`If she never saw or spoke to him more, she was well.`'
But then her pains returned on her, yet she got up the next day,
but had again some such dying fits, however continued till the next day after,
always being very sensible, under no manner of disturbance in mind.
On the 14th of the Seventh month, being sensibly weakened,
and feeling the approaches of death, she said, '`Come, come, come,
why so long;`' and in a very little time after called out, '`Lord Jesus, receive my spirit,
'`and presently breathed forth her last, according to her prayer to the Lord,
that she might not go stupified out of the world, for she died in full understanding,
and soundness of mind, and is gone to rest in the Lord, blessed be his name forever.

On the 18th of the Seventh month, 1704, her body was decently buried,
from her father`'s house, in Friends`' burial ground, in the parish of Liskeard.

Thus we have here an example of what one of old said of youth that is soon perfected,
which shall condemn the many years and old age of the ungodly.

[.asterism]
'''
WILLIAM TURNER, of Hitchin, in Hertfordshire,
was one who sought after truth and righteousness from his childhood,
and when but a youth complained to a professor that
he much desired an inward acquaintance with the Lord,
and to be acquainted with the spirit of God, was what his soul longed for.
The professor advised him to be acquainted with the Scriptures, which he had done before,
and could not be satisfied with the reading of what
God did for his people in former ages,
without feeling after God and knowing him for himself.
And it pleased the Lord in the riches of his love to answer the desires of his soul,
and to open the way of life, and to manifest the truth,
as believed by the people called Quakers.
He was convinced thereof, when he was about twenty years of age,
by the ministry of Thomas Green, and having attained to that which his soul longed for,
namely, the true knowledge of God,
he presently became obedient to the good spirit of God,
and suffered both spoiling of his goods and imprisonment for the truth`'s sake;
his love to which he manifested by bearing a faithful testimony to the same.
He was a man of a blameless life and godly conduct,
having regard to the honor of truth in all things,
seeking the advancement thereof over and above his own temporal interest.
He was a hearty lover of the friends of truth,
and especially of the faithful publishers of the gospel,
whom his heart and house were always open to receive.
He was a lover of peace and unity in the church,
and steady in his testimony against looseness and undue liberty,
and those who opposed gospel order.
He was indeed a pillar in the church, and a careful overseer in the flock,
whom sometimes he was concerned to exhort in a brief testimony;
which being delivered in much tenderness and brokenness of spirit,
was of service and comfort to the faithful people of God.

He was much afflicted with pain and weakness of body a considerable time before he died,
but bore it with much patience.
His wife cannot remember that she ever heard one unadvised
word proceed out of his mouth all the time of his illness;
and he would say, that his affliction was not laid upon him in anger,
but whom the Lord loved, he chastises.
When his wife bewailed the loss she should have of him, he said,
'`It will be better for me to go hence, for I shall be at rest and peace,
where there shall be no more trouble.`'
About three days before his death, he called for his children and said,
'`What I have to say, I shall speak in a few words, but remember them when I am gone.
Mind truth above all, and then God will bless you! and be kind to your mother,
and do nothing without her advice;
and do not marry to any but them that love truth well.`'
He charged his children to be none of them that strive to stay at home,
but strive who shall go to meeting.
A little before he died, he said,
'`I find nothing but that it will be well with me to all eternity.`'
To his eldest daughter Elizabeth, wife of John Pryor, he said,
'`Be an upright-hearted woman, and walk uprightly before the Lord.`'
He departed this life the 6th of the First month, 1704,
in the sixty-first year of his age, after he had believed in truth forty-one years.
His body was decently buried in Friends`' burying-ground at Hitchin.

[.asterism]
'''
FRANCIS BLAIKLING, of Winder, near Sedberg, in Yorkshire,
was a harmless man from his youth, born of good sober parentage.
He was convinced of the blessed truth about the time
of George Fox`'s first coming to publish truth,
which was in the year 1652.
He gladly received the truth in the love of it, and faithfully walked in it,
and cheerfully suffered for it, not only extreme spoiling his goods,
but by a pretty long imprisonment in York castle.
The Lord not only gave him to believe and to suffer,
but also gave him a part of the ministry, to testify unto the blessed truth,
which he had believed in, and to that word of reconciliation, nigh in the heart.
In work, according to his measure, he was a faithful laborer,
though he did not travel far abroad; neither was his testimony long,
but it was very easy and comfortable to the faithful; and he, in a plain testimony,
hit the mark, both in reproof to the wicked and the comfort of true mourners in Zion.
He was a man well beloved, and esteemed both by Friends and others; wherefore,
in the time of his sickness, many came to visit him,
who found him in a comfortable frame of spirit;
he patiently enduring those bodily infirmities which he was under,
and much resigned in his mind to God`'s will, whether for life or death, often saying,
the Lord was, and always had been, very good and favorable to him,
and he found nothing but peace to his soul from the Lord,
and he was ready to leave this world whenever the Lord pleased to call him out of it.

Thus in much patience and cheerfulness his spirit was borne up in his sickness,
increasing in sweetness of spirit, and in expressions which are not written down,
being not perfectly remembered.
As he lived in love and unity with his brethren, so he died,
saying to many friends who came to visit him, '`Dear friend,
my love and life is with you.`'

He departed this life the 20th of the First month, 1704, aged seventy-three years,
a believer in truth fifty-two years.

[.asterism]
'''

[.letter-heading]
An Account of some remarkable words spoken by HAYES HAMILTON, son of Hugh Hamilton,
of Ireland, a little before his death.
Aged twelve years.

He said he had been several times in a place by himself,
where he wished he had been forever,
he enjoyed so much of the comfortable presence of the Lord in silent waiting upon him,
and meditating in his law, which drew his soul in a rapture.
He also told his schoolmaster, about twelve days before he died,
the day he left the school (as the said schoolmaster did testify),
that his said master should see him go no more that way,
until he saw him carried to his burial.
His master asked the reason for his saying so.
He said he knew that he had taken the small-pox, and that he should die of that disease,
which accordingly came to pass about twelve days following.

He hearing his mother reading the first of Cor.
15:50, where the apostle Paul says,
"`Flesh and blood cannot inherit the kingdom of God,`"
he asked his father what he thought of that saying;
the father turned that question to his son, and asked his opinion of it; he replied,
as God was a spirit, that which was for his use, he would make it spiritual,
and therefore no longer flesh and blood.

When troubled with several questions about baptism,
he said he could prove from Eph. 4:5, that there was one Lord, one faith,
and one baptism; and he said, '`them that will be satisfied with that of water,
let them hold it; for my part, I depend nothing upon it.
I depend only upon the baptism of the spirit,
and I doubt there are many that talk most about baptism, know very little what it is.`'

He was taken sick, and about a quarter of an hour before he died he sat up in his bed,
his mother and sisters by him, and he asked what day of the week it was.
She told him, and he asked the hour of the day, the which she told; then he said,
'`Heaven is not far from me;`' his aunt asked him if
he was willing to leave his father and mother,
and all the world, to go to heaven; he said, '`Yes, I am;`' and further said,
'`It is a sweet change.`'
She desired the Lord to prepare him, and clear the way for him; he looking in her face,
said, '`I know the way, and who has cleared it.`'
And so died in peace, the 7th of the Third month, 1697,
in the twelfth year and seventh month of his age.

[.asterism]
'''

The dying words of THOMAS VOKINS, son of Richard and Joan Vokins, of West Charlow,
in the county of Berks.
The day before his departure he prayed thus: '`Oh! blessed God,
if it be your will to take me this night, make my passage easy; not my will be done;
your will be done.
Oh, Lord! you delivered Jacob out of all his troubles.`'

Another time he said, '`There is a good spirit as well as a bad spirit;
and if the good spirit be taken heed unto, it will be felt as strong to lead into good,
as the bad spirit is to lead into wickedness.`'
Not one hour before he died, his mother and others being present, he said, '`Mother,
the Lord is exceedingly good to me,
and has been all along the eight or nine weeks of my exercises,
and when I could hardly speak, his sweet presence has been with me,
and his life has sweetly refreshed me.`'

As his mother sat by him, she felt the power of the Lord,
and spoke to Friends in the chamber to be still,
and this innocent young man died like a lamb, without sigh or groan,
and those present felt the power of the Lord with him at his departure,
and were greatly refreshed; much was spoken by him of the goodness of the Lord,
but his voice being low, it could not well be heard.
He died the 23rd of the Second month, 1683.

[.asterism]
'''
RICHARD VOKINS, brother to the aforesaid Thomas Vokins, in the time of his sickness,
kept feeding in retirement within,
and when he first took his bed he examined himself before the Lord thus; saying, '`Lord,
have I done any thing to offend you, have I wronged any man?`'
and desiring the Lord would take off all reproach from his people.
During his sickness he was preserved in a quiet frame of mind,
no impatient words coming from him;
expressing how the Lord had preserved him in true simplicity,
which was his great comfort, and gave good advice to several who came to see him;
saying to them;`'It is well with me, you cannot think what I enjoy.`'
In the time of his health, he was a humble, tender-hearted man,
considerate of his servants and poor people that worked for him;
often saying that he would not enrich himself out of their labors;
and was glad when he could do good to any.
One time he called for his two children, and prayed the Lord to bless them;
his wife asked him, if it did not seem hard to part with them; to which he replied, '`No,
all is well, there is nothing troubles me,
all is well;`' desiring his dear children might take him for an example,
and live no worse a life than he had done.

After this, his wife said,
'`The Lord is able to raise you again if it be His will;`' he replied, '`I know he is able,
but he does not intend to restore me again;`' and
he told his doctor he could do him no good.
In the time of his sickness,
the impropriator and servants cleared his orchard of apples to the value of £4,
for tithes.
His wife asked if those people plundering them did not trouble him, he replied, '`No,
not at all, the Lord forgive them, they know not what they do.`'
When his wife perceived his speech to alter,
she again asked him if he was willing to leave the world; he replied, '`Yes,
very willing;`' soon after, his speech went quite away, and next day he died in peace,
being the 12th of the Eighth month, 1696.

[.asterism]
'''
ELIZABETH WILLS, daughter of Daniel and Mary Wills, of Northampton River, in West Jersey,
in America, was on the 2nd of Eighth month, 1687, visited with an ague and fever,
which continuing some days hard upon her, she often called upon the Lord, saying,
'`The Lord help me,
the Lord ease me;`' patiently begging of God for help in her great exercise,
and her cries were felt to proceed from the stirrings of life.
About the tenth hour of the sixth day of her sickness, her extremity being great,
she desired to be remembered to her mother,
who at that time was very ill in another chamber, and her mother understanding it,
she came to her, which much satisfied the child.
Turning to her mother, she embraced her, and said, '`O mother,
I will lie with you;`' and when she had manifested
her kindness and tender love to her mother,
for a little time lay still; there being her father and sister in the room,
she raised herself upright without help, and said,
'`Now I am well;`' giving living praises and thanksgiving to God, saying,
'`Lord God of power and glory; all power, glory and honor be given to you forever, Amen;
for you have helped me, you glorious God of life.
You have eased my heart, O you powerful God of glory; praises, and glory, and honor,
be given to you forever, Amen.
O you God of eternal glory! what shall I say unto you?
all praises be given unto your name, you glorious God of life, you have helped my soul;
praises forever be given unto you, forever, and forever.
Amen.`'
Often saying in this wise, '`What I speak,
God gives me to speak;`' and then speaking much more to the same effect,
all tending to the praise and glory of God,
and to the extolling of his great and wonderful name; often saying, '`God is good,
God has touched my heart.`'

Thus she remained praising and giving thanks to God for the space of an hour,
and it grew towards midnight.
Then she desired her two brothers, and her younger sister should be called,
who were in their beds, and when they came, she looked upon them,
but still remained praising and glorifying God, often saying, '`Now I am well,
I feel no pain.
I am willing to live; I am willing to die.
I am willing to leave the world, or I am willing to stay in the world;`' often saying,
'`I am content to live or to die;`' which expressions
greatly tendered the hearts of all present.
She again spoke much, praising and magnifying the great name of God,
to the same effect as before; several times saying, What I speak,
God gives me to speak;`' also saying,
'`I did not know God would have given me so much to speak,
for I was never sensible of these things before.`'
Then she took her father by the hand, and kissed him, saying, '`Farewell,
my dear father;`' and then took her mother by the hand, and kissed her, saying, Farewell,
my dear mother;`' and then her brothers, taking each of them by the hand,
and kissing them, saying, '`Farewell, my dear brothers;`' and lastly,
took her sisters by the hand, and kissed them, saying, '`Farewell, my dear sisters.`'
Her father hearing her use that expression to every one of them,
he called her by her name, saying, '`Where is that farewell you speak of?`'
she looked upon her father, and readily answered, saying, '`It is in my heart.`'

Her speech was so affecting, that it exceedingly tendered the hearts,
and caused tears to run much from the eyes, of all present; which she beholding,
as one without all sense of sorrow, looked upon her father, saying, '`Father,
you are troubled;`' he answered, no, he was not troubled, but glad;
saying it was more to him to behold her in that condition, than life, or length of days.
Then she said, '`I am well pleased.`'
She beholding her mother weeping, said, '`My mother is troubled;`' her mother answered,
saying, she was not troubled, but desired her to be content in the will of God.
Then she said, '`I am content.`'
She caused her brothers and sisters to speak their minds one by one,
of their satisfaction concerning her condition, which was done by them.
She hearing their sayings, was well satisfied; she often said,
as she was parting with them, '`God has eased me of my pain.`'
And after a little time she talked familiarly with them, as one that ailed nothing;
and in her discourse, spoke in this manner, saying,
'`James Martin (who was a minister of the gospel) is a good man; I would I could see him,
but he is gone to England; I shall see him no more; and John is a good man;`' her father,
standing by, asked her what John; and she said, '`that John who had a meeting in the barn,
'`(which was John Hayton); likewise she said, '`I shall see him no more.`'
She also said, '`Thomas Olive is a good man, and I shall see him tomorrow,
'`which accordingly she did.
When James Martin went away, she said, '`I am sure I cried;`' and said again,
'`Would I could see him.`'
Her father desired her to be satisfied, saying,
'`God has given you a share of that same life which
James has;`' so she mentioned him no more,
but something further of the goodness of God to her, and spoke of one Sarah Kem,
saying she was a good child, she died well.

She lay still, and after a little time her sense of pain came again,
and then she called upon the Lord, saying, '`The Lord help me,
the Lord ease me;`' and as it increased, the more earnestly she called upon the Lord,
saying, '`O Lord, how shall I ascend to you, that you may hear me?`'
And in time the Lord gave her some ease, and she took some rest; and the ninth day,
being the first day of the week, Friends coming to the meeting,
several came to see her before the meeting, unto whom she put forth her hand,
and tenderly asked several of them how they did;
but after meeting she seemed to be somewhat more weakened, and not so quick of memory,
but took her leave of several friends, as they came to her.`'

That day she several times inquired for a servant boy, who she knew to be negligent,
and often would lie out all night, and at the same time was gone,
and that night late he came again.
She desired to speak with him, so soon as she heard he was come.
When he came to her, she turned herself, and steadfastly looked upon him,
as one renewed with sense and strength, saying, '`God gave me much to speak last night,
and you were not here.
It is better for you that you shouldest walk with God.
You must die as well as I; you must go to the grave as well as I;
and if you do not do better you shall have torment, and I shall have peace.
It would be better for you that you wouldest walk with God, but time is past and gone,
and cannot be recalled.`'
Saying to him, '`Is it not better for you to do well than ill?`'
Her father standing by, asked her what she would have him to do then, if time were past.
She answered, she would have him do well, but she believed he would not;
she then said he might go away; and some time after called to him again, saying,
she would not have him forget what she had said to him.

On the 11th of the Eighth month, 1687, she departed this life,
having laid down her head in peace and rest with the Lord.
