== Chapter 12

[.chapter-synopsis]
* Richard Pike
* Thomas Thompson
* Hugh Stamper
* Reuben Satterthwaite
* Joshua Bunion
* Peter Fletcher
* Abraham Fuller
* Robert Barclay
* Hannah Turner
* Thomas Upsher
* Priscilla Cuthbert
* Elizabeth Whiddon

RICHARD PIKE, late of Cork, in Ireland, was born at Newbury, in England,
in or about the year 1627, and came from Ireland, belonging to the horse in the army,
which were sent from England, for the reduction of that nation,
upon the rebellion of the natives.
While he was in the army he had the character of a very sober, conscientious man,
but of great courage, for which he was much esteemed by his superior officers.
In those days he was accounted religiously inclined, and one who sought the Lord,
and the Lord was pleased to be found of him, and revealed his truth to him.
In or about the year 1655, the Lord sent some of his faithful ministers, called Quakers,
to that nation to preach the everlasting gospel,
by whom he was convinced of the way of life and salvation,
to which he became truly obedient,
and soon denied the use of carnal weapons for the destruction of mankind;
and in other things taking up the cross of Christ, despising the shame,
and for truth`'s sake became a great sufferer, by patiently enduring reproaches,
abuses and imprisonments, as well as loss of outward substance.
As he was a faithful follower of the Lord Jesus,
so he was greatly beloved by all faithful friends who knew him; and his deportment,
conduct and commerce among the world, were such as adorned the blessed truth,
being a very upright and just, as well as a very inoffensive man;
insomuch that his greatest persecutors have been heard to say,
if there were any good or honest men among the Quakers, he was one.

In the year 1668 he was, with several friends more, cast into prison by one Rye,
then mayor of Cork, for meeting together to worship God;
in which place he got a violent cold, which ended in a flux, that brought him very low,
the prison being thronged, and without convenience at that time for the sick.
The jailor indulged him for a little time to be a prisoner in his own house.
After his coming home, the distemper increasing upon him,
brought him exceedingly weak and low; though in much pain, yet very patient under it,
and much retired to the Lord, and in a sweet frame of spirit.
The Fifth-day before he died came that worthy mother in Israel, Susannah Mitchel,
to visit him; who, sitting in silent waiting upon the Lord by his bedside,
was moved to pray, which she did with great fervency of spirit.
At which time also the power of the Lord fell upon him in a wonderful manner,
greatly melting and tendering his spirit,
causing him to give forth several sweet and heavenly expressions;
and though he was exceedingly weak in body,
and neither able nor fit to rise out of bed before,
yet the presence and power of the Lord so strengthened him,
that he immediately rose out of his bed, as one that ailed little,
and put on his clothes, in order to go to the prison,
to see and meet his dear companions and fellow-sufferers.
His wife and friends present, seeing this great and sudden alteration;
were in great hopes the Lord would restore him to his health again.

He went abroad to prison, as one that was not sick,
and had a good meeting with Friends there;
the jailor gave him leave in the evening to return home again, which he did,
with little appearance of illness; but soon after his return,
as one that was only raised from his deathbed to
give his last visit to his beloved friends,
his distemper returned again, and he grew exceedingly ill that night,
and so continued growing worse till about the Third-day, in the evening,
at which time he was so bad that it was concluded he was dying.
In his weak conditions the power of the Lord came
upon him again in an extraordinary manner,
so that he was revived, and as one that had new life and strength given him,
and he spoke of the wonderful love of God to his soul, and the preciousness of truth,
with seasonable exhortation to all that were about him.
Thus he continued with the Lord`'s power upon him until the Fifth-day, whereon he died;
having a spirit of discerning given him from the Lord,
by which he saw and spoke directly to the inward states
and conditions of most or all that came to visit him,
giving counsel and advice accordingly, and in particular to some who had been unfaithful.
He spoke so home to their states, that they were almost amazed,
warning them to prize their time, and be more faithful for the time to come.

He also called those of his children who were come to some years of understanding,
in particular Joseph, Elizabeth, and Ebenezer Pike,
and gave them heavenly advice and counsel; and among the rest,
he spoke to them to this purpose: '`Fear the Lord, and be faithful to him,
and be obedient to your mother, and then the Lord will be a father to you,
and provide for and bless you, and the rest of you every day,
and let the blessing of your dying father rest upon
you;`' with more that cannot now be remembered.
It would require a volume to contain the many blessed and heavenly sayings and exhortations,
if they could be remembered, which came from him in the time of his sickness,
especially the last two days of his life, some of which were taken from his mouth,
and committed to writing by a friend present, and read at his burial;
which paper is through some neglect mislaid or lost.

He quietly departed this life, and died in the Lord, the Fourth month, 1668,
being about forty-one years of age.

[.asterism]
'''

THOMAS THOMPSON, of Skipsea,
was convinced of the truth of God by that ancient
and faithful minister of the gospel of Christ,
William Dewsbury, in the Eighth month of the year 1652,
and shortly after had his mouth opened to declare the name of the Lord,
and preach repentance to the people.
He was preserved in faithfulness to the truth to the end of his days,
not turning his back from sufferings, but patiently endured reproach for Christ`'s sake,
and spoiling of goods, with many years`' imprisonment.
When it pleased the Lord to visit him with the illness whereof he died,
which began on the 26th day of the Sixth month, 1704,
his heart was filled with the love of God,
and he was enabled through the goodness of God, though very weak in body,
to go to several meetings, in which the Lord`'s heavenly power did livingly attend him.
On the sixth day of the Seventh month, he was at the monthly meeting held at Harpham,
being the last public meeting he was at,
where he bore a plain and powerful testimony to the ancient truth,
laboring to encourage all Friends to be faithful to God,
and to be diligent in the service of truth, according to their several abilities, gifts,
and endowments,
that so an increase of the peaceable government of Christ might be witnessed,
both in the particular and also in the general.

He was indeed a laborious man in the work of the gospel,
having travelled in truth`'s service several times through Scotland,
and in many places in this nation; and, as he said when upon a dying-bed,
for many years had not omitted any opportunity of being serviceable.
His testimony was plain, but powerful; sound and convincing,
and severe against wickedness;
but to the young and tender-hearted he was very loving and affectionate,
even as a nurse that cherishes her children.
On the tenth day of the month, in the year aforesaid, being the First day of the week,
several Friends visited him in his chamber, he being then very weak,
to whom he declared the lovingkindness of God, and of his tender dealings with his soul,
from his youth to that day; and that he felt the Lord,
who had been the guide of his youth, to be the staff of his old age;
and exhorted Friends to faithfulness and confidence in God,
that they should depend upon the arm of his power and providence forever.

On the 13th day of the month, several Friends being with him,
he said that he was content to live or die, as the Lord pleased, in whom he had peace;
and that he was in no doubt concerning his salvation, but was satisfied forever,
and could say with Job, the Lord had granted him life and favor,
and his visitations still preserved his spirit.
The next day, being the 14th, and the day of his departure out of this world,
he spoke little in the forenoon, being under much bodily weakness and pain at times;
but about the second or third hour in the afternoon, in a heavenly, melting manner,
he said, '`The Lord is my portion, and the lot of mine inheritance forever.
I am not dismayed;`' and after a little time,
'`I have peace with God;`' and after a considerable pause,
'`Since the day that the word of the Lord came unto me, saying, As you are converted,
strengthen your brethren; and if you love me, feed my lambs; I have spared no pains,
either in body or spirit,
neither am I conscious to myself of slipping any
opportunity of being serviceable to truth and Friends;
but have gone through what was before me with all willingness possible.
And now I feel the love of God,
and the returns of peace in my bosom;`' which words were
spoken in so living a sense of God`'s heavenly power,
that it wonderfully broke and tendered Friends present.

Another time he said, '`The Lord Jesus Christ has shed his precious blood for us,
and laid down his life, and became sin for us,
that we might be made the righteous of God in him.
O, this is love indeed.`'
Again he said, '`My heart is filled with the love of God.
Oh the excellency! oh the glory! oh how glorious and excellent
is the appearance of God! the rays of his glory fill his tabernacle:`'
and so he sung melodiously, saying, '`O praises, praises, high praises,
and hallelujah to the King of Zion, who reigns gloriously this day.`'
All which being spoken in a heavenly sense of the aboundings
of the sweet life of the divine and living Word,
which was with the Father in the beginning,
mightily overcame and melted the spirits of Friends.
To a neighbor who came in to see him, he said, '`We must put off these mortal bodies;
but for them that fear the Lord there is an immortal one prepared.`'
He continued very cheerful and sensible to the last,
and spoke very cheerfully to several neighbors who came to see him.
About three quarters of an hour before his death,
he spoke to one that had been under convincement several years,
but had not been faithful,
exhorting him to repent and be faithful to what God had manifested to him,
that so he might find mercy; with many more words not remembered,
telling him that he would find it a terrible thing to appear before an angry God.
He said that he spoke to him in love, and would have him take it so;
and bade him remember the words of a dying man, and so bade him farewell.

Another time he said to friends, '`You are my witnesses,
that I have not withheld from you the counsel and mind of God,
and have labored to provoke you to faithfulness and diligence in his service,
that so you might receive a crown of glory at the hand of the Lord,
which is laid up in store for all the righteous,
and my conscience is clear in God`'s sight.`'
Being filled with the living power and love of God,
he often praised his holy and glorious name;
and about the seventh hour he passed away like a lamb, into his Father`'s bosom,
without so much as either sigh or groan, and is at rest in the Lord forevermore.

He departed this life in the seventy-third year of his age,
the 14th of the Seventh month, 1704.
A laborer in the gospel about fifty years.

[.asterism]
'''

The testimony of HUGH STAMPER, of Lurgan, in Ireland,
near his departure out of this life.

About twenty friends being present, he said,

[.embedded-content-document]
--

I die in the same faith that I have made profession of, and lived in,
and suffered for these twenty-three years, and I am as willing to die as to live.
All the desire I have to live, is to see truth prosper, and if sufferings come,
I am willing to suffer for it.
There is no weight or burden lies at my door.
I have wronged no man, neither have I been burdensome to any,
but always if there was any difference, I suffered wrong for peace-sake.
I have not oppressed any man.
So, my dear friends, beware of oppression, walk in love one to another,
passing by infirmities, forgiving one another, for even as Christ said,
if you forgive not one another, how shall your heavenly Father forgive you?
Even as he who would not forgive his brother, missed of pardon.
Keep your hearts clean, and let no rottenness remain therein.
Keep the heart void of offense towards God and man, and when any evil does appear,
judge it down with the light, and be not peevish, nor fretting;
it hinders the springs of life.
Walk humbly before your God, and be of a pure mind to him,
Walk in true love one towards another, and stand not at a distance one from another,
for envy and strife lead from God, and eat as a canker,
so miss of the blessing which is poured down upon the righteous,
as showers of latter rain.
Blessed be the Lord God forever.
Bear up your heads, and give not away your crowns for any visible thing here below,
for they are but trifles, and things of no value.
Dear friends, keep your crowns sure, and then you need not care what scoffers, mockers,
liars, backbiters, and drunkards say, for their way leads to hell,
and they cannot inherit the kingdom of heaven.

Dear friends, in the suffering of all things, you shall come to wear the crown.
No cross, no crown; take notice of that.
Friends, keep your crown, that your bow may abide in full strength in the needful time,
when the pains of death come upon you, which will come upon all in due time.
Death troubles me not, for blessed be the Lord forever,
the enemy dared never so much as once set up his head, either to twist or twine;
since I lay on this my bed of sickness, there is nothing but peace on every side.

My dear friends, I desire you in the bowels of tender love to love one another,
and you will be a comely people, and an honor to God and one to another.
Bear the daily cross, that you may be crowned when time shall be no more,
and come to partake of the mercies of David, namely,
an everlasting covenant which has no end.
If the righteous scarcely be saved, where shall the wicked and ungodly appear?
Oh! the joy and endless felicity that shall be upon the righteous,
and what horror and misery shall be upon the wicked!

And, dear friends, let not a bare profession serve your turn,
for it will not stand you in any stead in such a needful time as this,
but walk answerably to what you profess, that your bow may stand in full strength,
as mine does at this time.
Blessed be the name of the Lord forever, I have no more lying upon me that I know of,
to hinder my journey, than a child.
So, my dear friends, do not will and run in your own wills, but wait daily upon the Lord,
and let your whole dependence be upon him, that you may come in at the right door,
for whosoever climbs up another way is a thief and a robber.
Cast your care upon the Lord, and he will in no wise cast you off,
but he will work in you, and for you, and you will become the children of the day,
and of the light.
I do not speak these things to exalt myself, for there is no exalting in the grave,
but I must bear my testimony for God, and for his truth.
Friends, you know these things before;
this is to stir up your minds to stand steadfast in the truth,
and let not your crown be taken from you.
Be faithful in the day of small things, and despise them not,
and the Lord will make you rulers over much, so shall you be honorable men and women,
and he will shower down multitudes of blessings upon your heads.

O friends, I desire you again not to slight this glorious day, which is now dawned,
for it can be called no less than salvation upon earth,
but walk faithfully to the receiving of your crown,
and you will return with sheaves in your bosoms.

--

Thus often exhorting Friends to faithfulness, and to be of an honest heart,
and to keep nothing there but that which is of a right nature, saying,
'`Take notice of my words, for they are the words of a dying man,
and they are very weighty; and if you will not hear,
you shall be made to remember hereafter when I am gone.`'

When the time of his departure came near, he said, '`Come Lord Jesus,
come when it is your blessed will, for I am ready for you.`'
Just before he died he sat up in his bed and spoke these words, '`Now, Lord Jesus,
receive my soul into your everlasting kingdom of glory,
for your kingdom is from everlasting to everlasting;`' and
so departed this life about the ninth of the Seventh month,
1676.
Aged about sixty-five years.

[.asterism]
'''

REUBEN SATTERTHWAITE, born at Skinerhow, in the parish of Hawkshead,
in the county of Lancaster, came of believing parents,
who used a godly care in educating him in the way
of truth as professed by the people called Quakers.
This young man had a care over his own words and actions, that they might become truth,
and he received a gift of the ministry about the twenty-third year of his age,
wherein he did much improve himself until the twenty-sixth year of his age,
wherein he died; in which time he faithfully labored in the gospel.
He travelled into Scotland in company with his friend George Knipe,
who was a nursing father to him,
and they visited every meeting of Friends in that nation.
Being clear of that nation, he came back through Northumberland bishopric,
and the east parts of Yorkshire, and so home: and in the Second month of the year 1694,
he with his said friend set forward for London, and was at the yearly meeting there,
and afterwards visited Friends in the west of England,
even to the Land`'s-end in Cornwall, and so back by Bristol.
In this journey he had very good success,
and was much enlarged in his gift of the ministry;
and from Bristol travelled through Wales to Lancashire home again.
He travelled into Derbyshire, Nottingham and Lincolnshire; and in the Third month, 1696,
again into Scotland with his former friend, George Knipe,
and returned from there through Cumberland, which was the last journey he had,
for he was removed out of this troublesome world the same year.

He was a good example and pattern in righteousness and holiness,
and was valiant for the truth upon earth, and was of a sound mind,
and preached sound doctrine, and often opened the Holy Scriptures,
to the edification of the hearers.
When he was visited with sickness, he bore it patiently, and in the first part,
he got up and walked about the house, but feeling himself weak in body, he said,
'`I am a poor mortal, a worm, and dust and ashes.`'
Though his body was weakened and decayed, yet he was strengthened inwardly,
and often spoke of the kind dealings of the Lord with him,
and how mercifully he had helped him in his travels.
His sickness increasing he kept his bed, and many came to visit him;
to whose conditions he spoke, to the admiration of those about him.
Not long before he died, his sister-in-law being present, he said, '`Oh!
Lord, you know I have passed through many exercises for your name`'s sake,
and you have rewarded me well for the same, for which I praise your holy name.
The Lord God is my staff, as he was to David, who said his staff did comfort him.`'

Some young friends visiting him, he said,
'`I desire you to wait upon the Lord all your days, for the promise of the Lord is to you,
if you will wait upon him,
and love him to the end;`' with more expressions that could not be remembered.
He passed that night in a very good frame of spirit, breathing to the Lord.
On the morrow, being the First-day of the week, several young people came in,
to whose conditions he spoke distinctly,
exhorting them to remember their Creator in the days of their youth.
He was very weak in body, but his words did so affect them,
that they were tendered and broken into tears,
and several Friends present were much comforted thereby.
That night, Margaret his sister, and another Friend sitting up with him,
he taking his sister by the hand, said, '`Dear sister,
tell my father and mother that I must go, I must go home.`'
After some sight which he had, which brought some exercise upon him,
he broke forth into an inward rejoicing of spirit;
and after that he expressed the travail that was upon his mind
for some Friends and meetings in parts which he had visited,
and prayed to the Lord to be gracious and merciful to them,
and spoke many more seasonable words that are not here mentioned.
That same night he departed this life, being the 12th of the Eleventh month, 1696.

[.asterism]
'''

JOSHUA BUNION, who lived near Ipswich in Suffolk in England,
went over to preach the gospel in Ireland in the year 1696.
He was remarkable for his extraordinary innocency in his conduct,
chiefly minding the discharge of his duty, with respect to his ministry,
which was edifying.
He was taken sick going from Dublin to the north of Ireland,
and coming to Ballyhagan in the county of Armagh,
was so weak that he could scarcely alight off his horse without help,
yet his zeal was such that he bore a faithful testimony
for truth in the public meeting the same day.
Afterwards he went to bed, continuing very ill about two weeks.
In the time of his sickness he was very fervent in prayer, and the day before he died,
sitting in a chair, desired another to be set before him, on which he leaned,
and prayed fervently and powerfully to the Lord.
The next day he departed this life, the 23rd of the Fourth month, 1696.
Aged about forty years.
He was buried in Friends`' burying-place, near Ballyhagan aforesaid.

[.asterism]
'''

PETER FLETCHER was born near Pardsay, in Cumberland, in England,
and educated in the profession of truth.
He came over to be an apprentice in Dublin;
and after he had served his apprenticeship he settled in the said city;
he was of good conduct, both in respect to his Christian duty towards God,
in duly attending meetings for the worship of God, and other religious performances,
and ready and cheerful in doing those offices of love which we owe one unto another.
About three years before his death the Lord was pleased to call him into the ministry;
in which he was sound and deliberate in his delivery,
being careful to minister from that ability which God had given him.
He was under weakness of body some months before his death,
in which time he spoke of the Lord`'s dealings with him,
and how he inclined his heart to seek him when he was young,
and had kept him all along to that day,
in a sense of his goodness and power which had preserved him.
He was freely given up to the Lord`'s disposing,
and rather willing to leave the world than stay any longer therein,
if it were the Lord`'s will;
and further said he found nothing but sweet peace to abound in his heart from the Lord;
and so being prepared for his latter end, he departed this life in Dublin,
the 29th of the Fourth month, 1698.
Aged about thirty years.

[.asterism]
'''

ABRAHAM FULLER was convinced of the truth in or about the year 1660,
being about the forty-first year of his age.
He lived most of his time after his convincement at Lyhensa in King`'s county;
he feared the Lord,
and was a serviceable man on several accounts in the church of Christ,
and bore a testimony for the truth, and was a free and open-hearted man to his friends,
distributing of his substance unto those that were in necessity.
He was taken sick about the beginning of the Eighth month, 1694, of an ague and cholic.

In the time of his sickness he expressed his concern for the prosperity of truth,
and sent to speak with some that made profession of it,
and did not walk answerably thereto, and did admonish them to repent,
and amend their lives.
He was often in his illness in supplication to the Lord,
and in returning praises to him for his mercies which he had received from him.
About the 4th day of the Ninth month, most of his children being about him,
and sitting awhile in silence, he then prayed the Lord that he would bless his children,
and preserve them from the evils that were in the world.

One day having a pretty sharp fit of the ague upon him,
his daughter-in-law who attended him said, '`Father,
the fit you had yesterday went away easily;`' he replied, '`Yes,
the Lord`'s power took the pain away.`'
He gave his children good counsel and admonition,
according as he had a sense of their states.
He often in the time of his illness expressed how good the Lord was to him.
Six days before his death, being gone to his bed at night,
he desired to speak with his children that were in the house,
there being two of his sons and his son`'s wife.
After they had sat a little time silent by his bedside,
he said he had a desire to let them know,
that if the Lord had no further service for him to do, he was willing to die;
and then spoke to one of his sons, giving him good advice;
and then called to his other son by name, and said,
'`The Lord make you a sanctified vessel fit for his use.`'

His eldest son, living nearly a mile off, being newly recovered from a fit of sickness,
came to see his father, and when he was about to take leave of him,
which was but about two hours before his death, he spoke to him,
admonishing him to take care of his soul, for it was of great value.
He desired several times in his sickness,
if it were the Lord`'s will that he might be sensible at his departure,
and have an easy passage.
His desire was answered, for in less than a quarter of an hour before his death,
he laid his hand on the bedside, and turned himself,
and desired to be a little raised in his bed; and so departed quietly,
and finished his course about the twelfth hour at night, on the 4th of the Tenth month,
at his son Isaac`'s house at Lismina, and was buried at Friends`' burial-place,
at the Moat a Green.

[.asterism]
'''

ROBERT BARCLAY, of Urie, in Scotland.
This worthy man of God, whose character is written,
as well for their example and encouragement who have
or hereafter may receive the eternal truth,
in which he lived and died, and lives forever,
as for a testimony to the power and goodness of God, in raising him up to his church,
and to his lasting memorial in the churches of Christ, which is blessed forever.
The said Robert Barclay was the son of Colonel David Barclay,
descended of the Barclays of Mathers, in the kingdom of Scotland,
an ancient and honorable family among men, and Katherine Gordon,
from the Gordons of the house of the duke of Gordon.
He was born at Edinburgh, in 1648, educated in France,
and had the advantage of that tongue as well as the Latin.

He returned to Scotland about 1664, being sixteen years of age, where,
by the example and instruction of his honest and worthy father,
who in his absence had received the everlasting truth,
and his conversation was with other servants of God,
he came to see and taste an excellency in it,
and was convinced thereof about the year 1667.
He publicly owned the testimony of the true light, enlightening every man,
and came early forth a zealous and fervent witness for it, enduring the cross,
and despising the shame that attended his discipleship,
and received the gift of the ministry as his greatest honor,
in which he labored to bring others to God, and his labor was not in vain in the Lord.
He was much exercised in controversy, from the many contradictions that fell upon truth,
and upon him for its sake, in his own country chiefly,
in which he ever acquitted himself with honor to the truth,
particularly by his Apology for the Christian divinity
professed by the people called Quakers,
which contains a collection of our principles, our enemies`' objections,
and our answers augmented and illustrated closely and amply,
with many authorities for confirmation.
He wrote several other books which are printed,
and make a volume of nigh two hundred and thirty sheets,
which contain many standing books of sound judgment,
and good service to the truth and church of God.

He travelled often in Scotland and England, and also in Holland and Germany,
to spread the gospel of our Lord Jesus Christ.
He loved the truth, and the way of God, as revealed among the people called Quakers,
above the world, and was not ashamed of it before men,
but bold and able in maintaining it, sound in judgment, strong in argument,
cheerful in travails and sufferings, of a pleasant disposition, yet solid and plain,
and exemplary in his conduct.
He was a learned man, a good Christian, an able minister, a dutiful son,
a loving husband, a tender and careful father, an easy master,
and a good and kind neighbor and friend.
These eminent qualities in one who had employed them so serviceably,
and who had not lived much above half the life of a man,
having outlived his father but four years,
and died at least thirty years short of his age, aggravate the loss of him.

His sickness was short: our friend James Dickinson, of Cumberland,
in his travel into that nation, visiting him when on his deathbed, as he sat by him,
the Lord`'s power and presence bowing their hearts together,
Robert Barclay was sweetly melted in the sense of God`'s love,
and with tears expressed his love to all faithful brethren in England,
who keep their integrity to the truth.
He added, '`Remember my love to Friends in Cumberland, and at Swarthmore,
and to dear George,`' meaning George Fox, '`and to all the faithful everywhere;`' and said,
'`God is good still,
and though I am under great weight of sickness and weakness as to my body,
yet my peace flows; and this I know, whatever exercises may be permitted to come upon me,
it shall tend to God`'s glory, and my salvation, and in that I rest.`'

He died at his own house in Urie, in Scotland, the third day of the Eighth month, 1690,
leaving behind him seven children, four sons and three daughters.

He was born 1648; convinced of truth 1667; wrote his first book for truth 1670;
and his notable Apology in and about the 27th year of his age, 1675.
He died in the forty-second year of his age.

[.asterism]
'''

HANNAH TURNER, daughter of Thomas Turner, of Coggeshall, in the county of Essex,
in visiting her acquaintance, was taken sick at Goussingbeckingham-hall,
in the said county, and quickly after being taken sick was sensible she should die.
Her mother being with her, she desired her to bear it with patience,
and remember how it was with Abraham, and with many in our day,
in parting with their only child.
'`Dear mother, consider, it may be this great trial may prove to our sanctification;
bear it with patience.`'
For several days she lay in a composed state, praying to the Lord to forgive her offenses.
She was troubled that she was so far from her friends and neighbors,
and would have been glad to see them.
She expressed her concern for an acquaintance of hers,
entreating her mother to say to her as follows: '`Consider my death as a precedent,
and remember she must come before the bar of the great God, as well as I,
and can no way shun it; and how does she think to stand there without great repentance.`'

Another time she desired to have her love remembered to Friends at London,
and ordered the manner of her burial.
Her father coming off a journey to see her, she said, '`Dear father,
how often have I been comforted to consider how the Lord
has preserved you through many jeopardies of your life,
both by sea and land.`'
She also admonished her nurse not to go into mirth and pastime,
nor be ashamed of the cross of Christ.
'`What if people mock you, be not ashamed; remember Solomon`'s words,
that "`know for all these things God will bring you into
judgment.`"`' Many other exhortations she gave to this lass,
saying, '`Take notice of what I say;`' to which she answered, breaking forth into weeping,
'`I hope I shall.`'
At other times she spoke several weighty and seasonable exhortations,
which are not taken down, and so passed away, inwardly breathing to the Lord,
which was a great comfort to those with her;
and died on the 8th day of the Twelfth month, 1705, in the nineteenth year of her age.

[.asterism]
'''

THOMAS UPSHER was born in the parish of Lexden, in the borough of Colchester,
in the county of Essex, and was sprinkled or baptized, as they call it, a few days after,
according to the manner of the church of England, the 11th of the Sixth month, 1672,
but was educated in the Presbyterian way, and was religiously inclined from his youth,
often seeking the Lord for the good of his soul,
and delighted in reading the Holy Scriptures.
About the fourteenth year of his age he left the Presbyterians,
and joined himself with the people called the General Baptists,
and was zealous in that way, and became a preacher among them when young,
and was well esteemed by them,
until it pleased the Lord more effectually to visit him by the light of Jesus Christ,
unto which he turned his heart,
and came to see the emptiness of his former professions and talk of religion,
without the knowledge of God and Christ by the revelation of the Spirit.

A few days after he was convinced of truth, he wrote a letter,
which was sent to the Baptist meeting, to be read on the first day of the week,
showing the cause why he left them.
This letter was dated the 13th of the Ninth month, 1692,
so that he was twenty years of age when he came among the people called Quakers,
and was a diligent attender of the meetings of that people for the worship of God,
waiting upon him in silence and retirement of mind, for his teaching and counsel,
until he was pleased to give him a gift in the ministry,
which he received in great humility, and entered upon his ministry,
in speaking a few words among Friends, in much fear and tenderness,
to the comfort and refreshment of many.
God in tender mercy did increase his gift,
so that he became an able minister of the gospel,
to the turning of many from darkness to the light of Christ Jesus;
and in that service he travelled in most parts of England, and also in Ireland.

As he often in the time of his health remembered and spoke of his death,
so he did in his sickness, saying, '`I do not expect to live long in this world.
I have been preparing for a better.
I do not desire to live here on my own account.
I long more and more to be at home with my God,
yet I would not be of that sort to desire my reward before my work is done.
There is nothing here can invite my stay,
but if God has further service for me in this world,
I am resigned and given up to his will.`'

In a letter to a particular friend, written in the time of his sickness,
he expressed himself in these words:

[.embedded-content-document.letter]
--

When I consider those many unaccountable changes which we, and ours,
and all we have in this world are subject to,
it seems a sufficient antidote against the inordinate love of it, and it appears to me,
that it is the lack of due thoughtfulness which makes many so much engaged in it,
as almost wholly to sequester all those religious endeavors which
are really necessary to make sure of an eternal interest.

It is now a long time since I have enjoyed one day of perfect health as heretofore.
I consider it as a preparatory summons from this frail state of life; and to conclude,
I thank God I am not altogether unmindful of my duty,
in setting my house in order against the time shall come that I must die, and not live.
I hope to live in a far better state,
and there to enjoy all the generations of the just that are gone before,
and shall hereafter follow.

--

About the same time, several Friends being with him, he, speaking of his death,
desired they might bear him witness, saying, '`My dependence, hope, and trust,
is only and alone in the Lord Jesus Christ,
and that I do not value myself upon any qualification or endowment,
but lay all down at the feet of Jesus, and am as nothing before him.`'
About two days after, though weak in body, he was carried in a coach to Ipswich,
to the burial of a Friend.
When he came there, he seemed very unfit for the service of the day,
there being much people at the burial; but the Lord strengthened him to declare,
as at other times, the truth and word of life for about an hour and a half,
which much affected the people in general; and Friends, who knew his weakness of body,
admired the love and goodness of God to him.
He prayed also, and spoke at the grave some time,
and appeared stronger after the meeting than before,
and continued better a few days after.
But his sickness returned again, and he was very patient under the extreme pains,
which he said no tongue could express, desiring to be resigned;
and the Lord blessed him with resignation, faith, and patience, under all.

To a Friend that came to visit him,
who made some observation of the prevalence of his distemper, he said, '`Now,
in all likelihood, I am about to take my last leave of you all,
and I pray God from my heart to bless you.`'
Many sound expressions were spoken to those who visited him in his sickness; to some,
counsel and advice; to others, his own experience of the mercy and goodness of God.
Being desired to send for another physician, he answered, '`No, I am satisfied:
if God had been pleased to have said amen to means,
there has been sufficient means used for my recovery,
and therefore I shall have my eye only to the Lord for help.`'
At another time he said,
'`My tongue is not able to express what I feel of the love
and goodness of God now when I have most need of it;
that saying used by that plain, despised people is very true,
that life is better than words.
There is one thing I cannot find out,
why the Lord should so abound in his love and mercy to me,
who am unworthy of the least of his mercies.`'

There was a great refreshment felt many times in being with him in silence,
in time of his sickness.
On a First day, in the morning, several Friends being in his chamber,
he desired that they might wait upon the Lord together;
and the Lord was pleased to open his mouth to praise his holy name.
Although very weak in bed,
some Friends desiring him to say little to those who came to visit him, his answer was,
'`I know not whether I may have another opportunity to do it.`'
He remembered the faithful, and spoke of their blessed estate; at the sight of which,
he was even as it were in a rapture of joy,
praising the Lord to the comfort of those present, saying,
'`Oh! that I might declare of the wonders of the Lord that I have seen in the deeps,
but I am resigned to the will of the Lord.`'
His pains and exercises were very great, and, as he often said, unknown;
yet he also said, '`The Lord is very good to me,
and bears up my spirit in the midst of them all.`'
Taking leave of several friends who visited him, he said, '`Oh! that you may so live,
that we may meet again in the mansions of eternal rest.`'
He remembered his dear love to friends everywhere, saying, '`They are near my life,
I have true unity with them in spirit.`'
At another meeting in his chamber, about fourteen days before he died,
the state of the church, and many precious truths were opened to him,
and in a heavenly frame of spirit he spoke of the wonderful wisdom, love,
and goodness of God,
exhorting Friends to be more faithful and diligent in the service of the Lord.

About ten days before his death, finding himself, as he thought, somewhat better,
he went to the meeting, being the First-day of the week,
and prayed fervently in the forenoon meeting, praising the name of the Lord,
in a true sense of his mercy and goodness.
But in a day or two he altered much, his distemper prevailing upon him.
He desired to be carried decently to his grave, saying, '`I love decency,
and desire to die in great humiliation,
and commit my spirit into the hands of the Lord Jesus Christ.`'
About the time of his death, he was in a heavenly frame of spirit,
and spoke of a glorious meeting, and said,
'`The Lord in the riches of his mercy will keep all them that trust in him,
under all their trials to the end.`'
And so departed this life, the 10th of the Eighth month, 1704.
Aged thirty-two years two months.
He left behind him three children; and his wife, in the time of his sickness,
was much indisposed, which was an addition to his exercise.

[.asterism]
'''

PRISCILLA CUTHBERT, born at Brentford, in Middlesex, in 1697,
was the daughter of Thomas and Isabella Cuthbert, of the same place.
Some months before her sickness,
she was observed to have a religious concern upon her mind,
and retired from the rest of the children, and denied herself diversions among them,
and got into solitary places, and read in good books, and sometimes weeping by herself,
and other times praising the Lord.
She had a sight of her death before she sickened, and spoke of it to several.
When her sickness came, which continued three weeks, she bore it with much patience,
praying to the Lord to be her comfort, and said,
'`I hope the Lord will comfort my dear father and mother;`' acknowledging the labor
and tender care and cost which her parents had been at for her bringing up,
and the education of herself and sisters and brothers.
When her father came to her, upon her inquiry after him,
she laid her arms about his face to wipe off the tears, and said, '`Lord,
comfort my father and mother, and bless my poor sisters,
and my brothers;`' and gave good advice to her brother to obey his parents,
and fear the Lord, saying he will bless you.
She said to her father, '`I am willing to live to praise the Lord,
and I am willing to die, if it were at this moment of time.`'
She desired that when she was buried, none that laughed or were vain should be there,
but such as feared the Lord; and in a sweet frame of mind praised the Lord.

Another time she said, '`I have, in the time of my health,
been afraid when I have seen any dead nailed up in their coffins;
but now the Lord has taken away that fear, blessed be his name.
Therefore take you notice, who stand by me,
that I am neither afraid of death nor the grave,
but I am willing to die when it pleases the Lord;`' and soon after fell asleep.
She often prayed for her parents,
to whom she expressed more than ordinary affection
and regard for their love and tenderness to her,
expressing her willingness to die, and her comfort in the Lord.
Her school-mistress visiting her, she said,
'`I am going where I trust in the Lord I shall have rest, for the Lord is my rest.`'
Near her end, her father speaking of his purpose to stay with her that night,
she replied, '`No, no, for I shall not die this night,
though it will not be long before I do.`'
He went to bed: and the next day her father coming to her,
she having had some rest in the night, she praised the Lord;
a neighbor present supposed she might, by her praising God, disturb her father,
to which she made no answer, till after some time, she said,
'`Is my father disturbed at my praising the Lord?
no, no, I know he is not.
Indeed if I was dying, as some have done of late, rending and tearing with bad words,
my father and mother too would have great reason to be troubled,
but to have a child die in the Lord, I hope great is their comfort.
I know their trouble is mixed with joy,
blessed be the Lord for it;`' upon these words several
young women present broke forth into tears.

About two hours before she died,
her father asked her if he and her mother should
turn her to see if she could have a little rest,
she answered, '`Do what you please.`'
A friend present advised all to be quiet and still,
and in a little time hearing one weep, she said, '`Who is that, my sister Elizabeth?`'
reply was made, no; she replied, '`For the Lord`'s sake do not cry for me,
do not cry for me.`'
These were the last words she was heard to speak:
and so departed this life without sigh or groan,
about the ninth hour of the sixth day of the Sixth month, 1701,
in the fourteenth year of her age.

[.asterism]
'''

ELIZABETH WHIDDON, wife of Henry Whiddon, of Cork, in Ireland;
was from her childhood given to sobriety, beyond what was common in one of her years,
when she was about fourteen years of age,
and was a woman of an exemplary life and conduct.
She was called of the Lord to give testimony to his name and truth,
though she was backward and unwilling to be concerned in so weighty a work,
yet afterwards grew more strong, and declared of the wonderful things of God.

In the time of her sickness she enjoyed a great refreshment
from the presence of the Lord,
which tendered the hearts of friends present,
and caused her to praise and magnify the God of her salvation,
some days before her death.

Her brother, Joseph Pike, visiting her one morning, and inquiring how she did, she said,
'`Oh! dear brother, though I have not slept all this night,
yet I am as one that needs it not.
Though my body is extraordinarily weak, yet I am strong,
the power of the Lord carrying me over all weakness; but above all,
the Lord said this night to me, in the powerful and fresh openings of life,
"`You shall praise me in the heavens;`" which has so overcome my soul,
and raised my spirits, that I am as one that lacks no sleep,
nor is sensible of pain or weakness;`' and so went on in praising and magnifying the Lord,
with many good expressions that cannot well be remembered.
About a day before she died, observing her sister Elizabeth Allen to weep,
looking upon her with a composed countenance, she said, '`Sister, why do you weep?`'
She answered, because unwilling to part with her.
She replied, '`Oh!
I shall go to everlasting joy and felicity, where I shall be at rest.`'

She departed this life the 23rd day of the Fifth month, 1693,
to receive the recompense of reward, even a crown eternal,
of which she had received before-hand a full assurance.
