== Chapter 13

[.chapter-synopsis]
* Robert Sandham
* Deborah Sandham
* Edward Parker
* Eleanor Cannings
* Henry Pontyn
* Isaac Alexander
* Anne Camm
* John Whiting
* Anne Dewsbury
* Anthony Patrickson
* Mary Page

ROBERT SANDHAM, born near Petworth, in Sussex, in England,
was convinced very early of truth at Youghall, in Ireland, where he then dwelt,
and he soon became a faithful follower of it, and sufferer for it,
bearing a steadfast testimony to it against its opposers;
and was a preacher of it in his life and conduct among
the inhabitants of that town until the end of his days.
He lay sick two weeks,
in which time he often exhorted Friends that came
to visit him to be faithful to the truth;
and to some, negligent therein, he said much in warning them to be no longer so,
but to hasten out of a lukewarm state, lest the portion thereof should be theirs.
Some relations and neighbors visiting him, he exhorted them to receive the truth; '`For,
'`said he, I bear my testimony now on my dying-bed,
that it is the truth which the Quakers profess;
therefore be faithful to the Lord and his truth, while you have health and strength,
and delay not till you come to a dying-bed, as too many are apt to do,
for then oftentimes men and women find it enough to bear their
sickness and pains;`' which affected most present.

To his wife, with whom he had lived about twenty-four years in much love, he said,
'`I am freely given up to the Lord`'s will.
I therefore desire you also to give up, and bear my death with patience,
and the Lord will make up your loss of me in being near unto you.`'
He often exhorted his children to love the Lord and his truth,
and be obedient to their mother, and love one another, and all honest Friends,
and delight to go to meetings.
One of his children being of age to remember what he said, he said to her,
'`Tell your two young sisters when they are grown up,
that it is my charge to them so to do, for they may not remember what I say to them now,
and the Lord will be a father to you and a husband to your mother.`'
Seeing one of them crying, he said, '`Be good children, love the Lord,
and obey your mother, and though I am taken away,
you will have your mother left with you, and she will take care of you.`'

Soon after he drew nigh his end, being in a sweet frame of mind,
resigned up to the Lord`'s will, often speaking of his mercies to him.
He said,
'`The Lord has fully satisfied my desires;`' and took
a solemn farewell of his wife and children.
A friend being present, prayed to the Lord to be near him in that present exercise,
and make his passage easy; after which he took the said friend by the hand,
and expressed his great peace and satisfaction, and passed away,
being sensible to the last.
He died the 28th of the Eighth month, 1675.

[.asterism]
'''

DEBORAH SANDHAM, wife of Robert Sandham aforesaid, was born near Youghall, in Ireland;
she received truth soon after her husband, and was a faithful,
serviceable woman to her end, bearing a true and sound testimony for God and his truth,
and was very exemplary in conduct.
She survived her husband about twenty years, taking due care of her children,
which fulfilled their father`'s dying words to them.
When it pleased the Lord to visit her with the sickness whereof she died,
she perceiving one of the family to be much concerned at it, said, '`Be not concerned,
I am freely given up to the will of the Lord, either to live or to die.
If the Lord have any further service for me, he can lengthen my days, if not,
I am freely resigned to his will.`'
She was often in her sickness inward with the Lord,
being kept in great patience and quietness, exhorting Friends,
and inviting some of her relations and neighbors who came to visit her,
to receive the truth; also warning some unfaithful ones,
not to let slip the day of their visitation.
She also exhorted her children to mind her frequent advice and counsel to them,
and to fear the Lord, and to keep out of all that which grieves his righteous spirit;
as (said she) your dear and tender father on his deathbed exhorted you, even so do.
Love the truth, and love one another, and then the Lord will be a father to you,
as truly he has been a husband to me.
My desires have been, and are still, that you may fear and love the Lord,
and reverence him, for your mother does not die without a hope,
that the Lord who has begun his good work in you, will carry it on,
and that the blessing of the Lord will rest upon you,
which is more than all visible things; as my soul has been a witness of,
as my mind has been kept from coveting after them, having seen,
that godliness is great gain, and in the gain of it is great peace.

One of her daughters not being with her in the time of her sickness,
she desired to be helped up, that she might write a few lines with her own hand,
as her last words to her, which were as follow: '`I not knowing as yet,
whether it be the will of my heavenly Father to finish my days, I am,
through the great mercy of God, freely given up.
Oh! this I have in my heart to say to you, be faithful, be faithful,
and dwell in holy patience; and the same is to your husband.
Oh! that you may come to holy silence with fear and dread,
then will the work of the Lord prosper, which is more than all works.
You have many of my exhortations, which get together, and keep and mind,
and the God of peace support you; you not being in a condition to come to me,
so farewell in the Lord.`'

The day before her departure, she was fervent in prayer to the Lord,
that he would bless his people, and enable them to walk faithfully before him,
and that his truth might prosper,
and that he would please to raise more faithful laborers
for the gathering many more unto righteousness;
also that he would be pleased to bless her children, and their offspring,
and make them his; with much more which cannot be remembered.
The day she died, she said to one of her daughters, '`You are my first-born,
and always very dear to me.
I cannot now say much more to you, but mind my former exhortations,
and remember that truth was more than all, and truth was over all with me,
and truth was your mother`'s chiefest treasure;`' often saying, '`My dear child give me up,
give me up; entreat the Lord to enable you to give me up,
for I am freely given up to the Lord`'s will.
Taking her last farewell of her children and grandchildren, with friends and the family,
she desired to have her dear love remembered to Friends at Cork, and elsewhere;
my love also (said she) extends farther, to all Friends in England.
Some time after, turning herself about in her bed, she said,
'`I am now a going to leave you.`'
And so she quietly, and in great peace,
departed this life the 15th day of the Fifth month, 1695, in Youghall, where she dwelt.

[.asterism]
'''

EDWARD PARKER, of Thornbury, in Gloucestershire,
was convinced of the blessed truth by John Audland and John Camm,
at their first coming into those parts, which was about the year 1654.
He bore a public testimony for truth, and continued faithful to his death;
and on his dying bed gave very living testimonies to the truth,
to many Friends and others about him.
His last words were, '`Lord, come, your servant is ready:
'`and then departed this life in the year 1667, in the fiftieth year of his age.

[.asterism]
'''

ELEANOR CANNINGS, wife of Joseph Cannings, of Thornbury, in Gloucestershire,
was convinced by John Audland and John Camm, about the year 1654,
when they came into that county.
She was a zealous woman,
and often exercised in bearing a faithful testimony for the truth against the priests,
for which she suffered many and great abuses from the rude people.
She continued a sincere-hearted Friend to the end of her days,
and on her dying bed gave many good exhortations to friends about her, saying,
a little before her death, '`I am well satisfied, and am going to a better habitation.`'

She was buried at Hasel, the 19th of the First month,
about the seventy-third year of her age.

[.asterism]
'''

HENRY PONTYN, of French-Hay meeting,
was a faithful laborer in the ministry of our Lord Jesus Christ, as well beyond sea,
as in this nation of England, and endured many sufferings and hardships,
and several years`' imprisonment at Gloucester for his faithful testimony for God,
and continued faithful to his death.
On his dying bed he said that the Lord had done well for him,
and the chastisements of the Lord are good;
exhorting his children and friends about him to live in the fear of the Lord,
that they might die in his favor, saying, '`The end will crown all.`'
He died in the sixty-seventh year of his age.

[.asterism]
'''

ISAAC ALEXANDER, son of Thomas and Alice Alexander, of Bendrig, in Killington,
in the county of Westmoreland, was born in the year 1680,
and convinced of the blessed truth in the year 1694, in the fourteenth year of his age.
In his seventeenth year he received a gift of the ministry,
and became an able minister of the gospel of our Lord Jesus Christ.

In 1698 he travelled abroad in the work of the gospel, and went into Yorkshire,
and through the east parts of England, till he came to London;
and after his return home he travelled in the same service into Scotland,
and visited all the meetings of Friends in that nation.
After his return from there, he went into the southern and western parts of England;
and three years after, he visited all the meetings of Friends in Ireland,
and most of the meetings in England and Wales.

In the Eighth month, 1705, he began to be much out of health,
and yet attended Friends`' meetings till the middle of the
Tenth month following.. On the 21st of the same,
several friends sitting by him, he, being sensible of God`'s salvation,
said in admiration thereof to the Lord, '`To you, to you, be salvation and praise!
This is a day of great salvation.`'
He signified what great mercy it was that the Lord should visit us in our young years,
and reveal his blessed truth to us,
and how unworthy many were before the Lord did make bare the arm of his salvation;
further saying, '`How near has the Lord been to me in the time of my sickness!
Although I have formerly felt much of his power and presence,
yet never enjoyed such plenty thereof,
as since I have been visited with this sickness;`' instancing one night,
wherein he could not sleep,
he enjoyed more abundantly of the love of God than at any other time before.
He said, '`Oh! what an excellent thing it is to keep in the truth,
and visit one another in the life of it.`'
He made a great difference between those who visit
the sick in the sense of the divine life,
and other visitors, who no sooner meet but they begin to talk of their worldly affairs.
He said, '`Friends, get into an inward acquaintance with the Lord in spirit,
for it is a good thing to retire to the rock; there is safety, there is good standing,
an excellent bottom, and room enough.`'
He further said, '`If any go out of the bounds of truth,
thinking thereby to bring others in,
they will find themselves to be in slippery places;`' and`'Beware of joining with false,
unsettled spirits.`'
Another time, two friends sitting by him, he felt the power and presence of the Lord,
and sang praises to him after a heavenly manner, saying, '`My heart is full,
though I can truly say, I have no desire to speak,
but as I feel it spring from the life.`'

On the 28th of the Tenth month he said, '`As I lay on my bed very weak of body,
I thought I could never die better, for I felt my salvation sealed unto me.
Oh! love God, love God, for he is worthy.
You may love any thing else too much, but you can never love God too much.
Oh! what has he done for my soul; he has given me everlasting comfort; it is enough;
it is enough, indeed.`'
He said, moreover, '`There are two things which are to my great satisfaction:

_1st._ That ever since the Lord manifested himself to me,
I have freely given up myself to his requirings, and delivered his word faithfully,
and have not sought to please men, neither did I look for great things.
What I desired was, that I might have a place among the sanctified.`'

_2ndly._
I have always been against libertine spirits, and have had no familiarity with them;
these things are now my comfort.`'

He also said, '`Oh!
I have seen glorious things, yes, such things as I never saw before.
I beheld a friend lately deceased in a glorious place, and that I was to be with him;
and I said it is enough to be there.
Oh! such salvation!`' Again, '`I am glad I can say, O death, where is your sting;
and grave, where is your victory?`'
Another time, some friends visiting him,
he related to them how the Lord had raised him from nothing to bear a testimony for him,
and wheresoever the Lord drew me I have followed him,
both in this nation and other nations, and sought not favor and interest among men.
He warned and cautioned the negligent to be diligent and faithful,
and come up in the service of truth; and said,
The Lord will cause a dreadful day to overtake the disobedient and the negligent;`' saying,
It is sealed to my soul, that it hastens on quickly.`'

He often said at times, in great weakness of body,
I desire to be dissolved and to be with Christ, but the Lord`'s will be done;`' adding,
'`The Lord`'s presence is here;`' giving thanks for his divine help, saying,
'`I never lacked comfort from him in this time of sickness.
Friends, it is an excellent thing to have a conscience void of offense towards God.
Keep your hearts clean.
I have discharged my duty to all people,
so that I find nothing but that I am fully clear; I am fully clear.`'
After a little time he broke forth in a sweet harmony,
and lifted up his voice in prayer to the Lord, which had been very low several weeks,
saying, '`Lord God! though my exercises and pain of body abound,
your power and life do much more abound,
and carry me over all;`' fervently begging of the Lord to
be with all his faithful laborers all the world over,
rendering thanks for his glorious appearance, saying, '`Worthy, worthy, are you, O Lord,
of all honor, thanksgiving and praise.`'
He prayed for an easy passage out of this world, which the Lord granted him;
for about the second hour the same day, in the afternoon, he fell asleep,
and twelve hours after, he said to a friend present, '`Lay my head better;`' which done,
he said, '`Now I will fall upon my sleep,
'`and immediately went away as if he had fallen into a natural sleep.

He died the 12th of the Twelfth month, 1705, at the house of James Wilson, at Aba,
near Kendal; and the 15th of the same month was buried at Brigflats, near Sedberg.

[.asterism]
'''

ANNE CAMM, late wife of Thomas Camm, of Camm`'s-Gill, was daughter of Richard Newby,
in the parish of Kendal, in Westmoreland, a family of good repute,
being always religiously inclined.
Her father was convinced of the blessed truth in 1652, and died therein a faithful man.
Anne Camm was born in the Eighth month, 1627;
and was well educated in learning proper for her sex.
About the thirteenth year of her age,
she was sent up by her parents to an aunt at London,
where she became acquainted with a religious people called Puritans.
Her stay in London was about seven years, from which she returned to Kendal.
After some time there, she removed to the city of York,
and dwelt in a family of great account in the world, her mistress being a pious woman,
after whose decease she returned again to Kendal,
her society still being with the most religious where she came.

At Kendal there was a seeking people, who met often together,
sometimes sitting in silence, other times in religious conferences,
and often in fervent prayer.
John Audland living remote, yet sometimes fell in among them; and about the year 1650,
John Audland and she married,
and they were both convinced of truth in the beginning of 1652,
by the ministry of that honorable servant of Christ, George Fox.
So powerfully did God, by his sanctifying word and spirit, work upon them,
that they were thereby made effectual instruments in his hand,
to preach the gospel unto others in the next year, 1653, and so forward,
until the Lord put a period to their days.

The first place the said Anne Audland was called of the Lord to visit, except about home,
was the county of Durham, about the beginning of the year 1654,
and she preached truth to the people in the town of Aukland, in the said county,
on a market day, for which she was imprisoned in the town jail,
where she spoke to the people through the window,
and several were affected with her testimony; and towards evening she was discharged.
John Langstaff, who was of great repute among his neighbors, owned her testimony,
and went with her into prison, and when released brought her to his house;
but John`'s wife being no Friend, chid with her husband,
which made Anne very uneasy to stay there.
So she walked out in the fields to seek some covert place to take up her lodging in;
but Anthony Pearson, of Rampshaw, a late justice of the peace,
who lived some miles distant, having knowledge by George Fox, who was at his house,
of Anne`'s coming to that town, came with a horse and pillion,
and took her home to his house that night.

After her service in those parts was over, she returned home;
and in the winter following, she, with Mabel Camm, wife of John Camm,
travelled through Yorkshire, Derbyshire, Leicestershire, into Oxfordshire,
to the town of Banbury, where Mabel Camm had a concern to go to the steeple-house;
and spoke to the priest and people, and Anne accompanied her.
Whereupon the people rudely hurried them out of the house, and abused them in the yard.
The priest passing by, Anne Audland said, '`Man, behold the fruits of your ministry.`'
Next day they were sent for before the mayor,
who had got two witnesses to swear Anne had spoken blasphemy,
for which they committed her to prison.
Mabel Camm was dismissed, and travelled to Bristol, where she met with her husband,
John Camm.
After some days, two men in Banbury gave bond for her appearance at the next assize,
by which she was a kind of prisoner at large,
which gave opportunity for her to have several meetings with the people in the town.
Her two bonds-men, and several hundreds more, came to be convinced of truth,
and turned to the Lord Jesus Christ,
being the fruits of that effectual powerful ministry God had called her to bear,
so that many were added to the church,
and a large meeting of Friends there was in that town,
and several other meetings in the country adjacent were settled.
For this cause their adversaries were angry,
and they threatened that she should be burned when the assize came.

When the assize came, John Audland, John Camm, and Thomas Camm were there,
and some Friends from London and Bristol;
and the substance of the charge or indictment drawn up against her was,
that she had said God did not live,
because she had said concerning the priest at Banbury,
that`'True words may be a lie in the mouth of some that speak them;`' alleging,
Jer. 5:2, "`And though they say the Lord lives,
(which nothing can be more true,) surely they swear falsely.`"
The judge of the court was moderate,
observing her sober and wise answers to his questions, and her innocent boldness,
and comely personage, and seeing the uncertainty of the evidence against her,
and that the matter of fact charged, did not amount to what was designed,
gave the matter to the jury thus:
'`That she acknowledged the Lord her God and Redeemer to live,
and that there were gods of the heathen and of the Philistines that were dead gods.`'
Some upon the bench perceiving their end would not be answered,
went off to influence the jury to bring in something against the prisoner,
lest they should come off with discredit.
One of the bench observing the injustice in that matter, stepped off also, telling them,
he would sit no longer with them, till more justice was among them,
and was convinced of truth.
Other officers in the court threw away their staves,
and bore testimony against their arbitrary proceedings.

The jury returning into court, and being asked if they were agreed,
they answered they were; and being asked what they found, they made answer,
'`Only misdemeanor.`'
A friend present told them it was illegal to indict
her for one fact and bring her in guilty of another;
for they ought to have found her either guilty or not guilty,
upon the matter of fact charged in the indictment.
The judge told Anne, if she would give bond for her good behavior,
she might have her liberty.
She refusing, they sent her to prison again: but the judge was heard to say,
that the prisoner should have been discharged,
but the judge had a mind somewhat to please the angry justices.
Her adversaries were confounded, and slipped off the bench one after another,
in disorder, without dismissing the court, so that truth was that day exalted,
and the Lord`'s power magnified in frustrating the designs of wicked men.
The prison where Anne was sent to, was a close nasty place, several steps below ground,
on the side whereof was a sort of common sewer,
that received much of the mud in the town, that at times did stink sorely;
besides frogs and toads did crawl into the room, and no place for fire,
yet she was in great content because it was God`'s cause.
Her fellow-prisoner was Jane Waugh, a laborer in the gospel,
who came some months before to visit her, and was committed to prison with her;
but God`'s presence and peace being with them, made their nasty stinking jail a palace,
where she remained seven or eight months, and from her first commitment,
about a year and a half, and was at last discharged by the mayor and aldermen.
The same day Richard Farnsworth was set at liberty, who,
with other men Friends were prisoners in another room;
but Jane Waugh still continued a prisoner.

Anne had frequent meetings in Banbury before she left it;
and also went to the mayor to demand the liberty of her friend Jane Waugh,
who was imprisoned for no other fact,
than for coming many miles in love to visit her in prison,
and she was soon after set at liberty.
Being clear of those parts, she travelled through the counties to Bristol,
where she met with her husband John Audland.
John and Anne Audland continued in their service and labor
in the ministry in several parts of this nation,
south, west, and northward, until John Audland fell sick,
and died in the latter end of the year 1663,
having been married to his wife Anne about thirteen years, and left behind one daughter,
since dead, and one son named John, born a few days after his father`'s death.

The 30th of the Third month, 1666, Thomas Camm married the said Anne Audland,
and they lived together in true love, serving the Lord six months short of forty years.
She was one with her husband in all his services and sufferings,
as at one imprisonment three years at Kendal,
he not being permitted so much as to see his family; another time at Appleby,
near six years, during the first part of which he was straitly confined, the latter,
through favor of the sheriff and jailor, he had much liberty.
They travelled together in the work of the ministry into the southern parts of the nation,
as London and Bristol, etc., especially at London.
About twenty-six years ago, she had like to have died in that city,
as also of later years at Bristol.
The last time she was there, she was brought nigh the grave;
at which time she expressed many heavenly sayings,
that will not be easily forgotten by some, warning all to prize their time,
and prepare for their latter end, as God had inclined her to do,
so that she enjoyed unspeakable peace here,
with full assurance of eternal rest and felicity in the world to come, which, said she,
I have desired to enter into as gain, rather than to live, if God so please.

It was her manner often to retire alone in her closet, or some private place,
exercising herself in fervent prayer,
and to set apart some time almost daily for reading the holy Scriptures,
and other good books,
and she was very diligent in frequenting meetings for the worship of God, etc.
She was not forward to appear in preaching or prayer in public meetings,
but when she did, it was fervent, weighty, and with the demonstration of the spirit,
and with power, to the refreshment of the church, her doctrine dropping as dew,
but with zeal to lay waste the mountain of Esau.
She had wisdom to know the time and season of her service,
in which she was a good example to her sex,
for without extraordinary impulse and concern,
it was rare for her to preach in large meetings,
where she knew there were brethren qualified for the service of such meetings.
She was grieved when any, especially of her sex, were too hasty, forward,
or unseasonable in their appearing in such meetings; and would give advice to such,
not without good effect.
She behaved herself as a humble servant of her Lord and Master, Christ Jesus,
washing his disciples`' feet, and helping and serving, as a nursing-mother,
the weakest and tenderest of the flock of Christ,
and was an encourager of those who came forth in a testimony for God,
though but of a stammering tongue.

The last opportunity she had among friends was the 2nd of the Ninth month, 1705,
at a monthly-meeting at Kendal; and notwithstanding her great age and weakness of body,
with the coldness of the season, she would not excuse herself from that day`'s service;
and the Lord was with her in good counsel and advice to friends,
pressing all to faithfulness and diligence in their service for God,
that they might receive their reward with those who had nearly served out their day.
The next day her illness began.
About the 16th of the said month, finding her husband under concern,
because of her sickness, she said as follows:

'`My dear, if it be the Lord`'s good pleasure, who joined us together,
and has blessed us hitherto, to separate us outwardly,
I entreat you be content therewith, and give me freely up to the Lord,
for you know we must part,
and if I go first it is but what I have desired of the Lord many a time.
I believe the consideration of the desolate condition I should be in, if left behind you,
will have that place with you, that you will the more freely commit me to the Lord,
whose I am, and whom I loved, feared and served with an upright heart all my days.
His unspeakable peace I enjoy, and his saving health is my portion forever.
I pray you be content with what the Lord pleases to do with me; whether life or death,
his holy will be done.
Let us, my dear, leave all to the Lord.
However it be, it will be well.
I have loved you with my soul, and God has blessed us, and will bless you,
and be with you, and make up all your losses.
Death is gain to me, though it be your loss, and for my gain`'s sake,
I hope you will bear with patience your loss.
I bless the Lord I am prepared for my change.
I am full of assurance of eternal salvation, and a crown of glory,
through my dear Lord and Savior Jesus Christ, whom God the Father has sent to bless me,
with many more, by turning us from the evil of our ways into the just man`'s path,
which shines more and more to the perfect day.
If God now please to finish my course, and take me out of this earthly tabernacle,
I am well content.
I am clear, and have discharged myself in the sight of God to all Friends,
except something of late has been upon my mind,
to send Friends in the south a farewell epistle,
especially to Friends about Bristol and Banbury.
She said the substance thereof was the remembrance
of her dear love to them all in the truth,
with tender advice to the professors of truth, to walk in, and keep to,
the simplicity thereof, out of heights and exaltedness,
under the power of the cross of Christ,
by which they will be more and more crucified to the world, and baptized into Christ,
and put him on, the new and heavenly man, in whom they will become new creatures,
and enabled to serve God in spirit,
and keep to the unity thereof in the bond of peace and love,
which the god of the world is still laboring to break and dissolve.
I have seen him at work to make a breach and separation among Friends,
and if he prevail,
it will be under specious pretenses of a more angelical
appearance than at any time before,
and will be a bait taking to all that live above the cross and true self-denial.
I would all were warned to stand their ground in the power of God,
which only can bruise Satan, and preserve out of his subtle baits and snares.`'

Next day several Friends came to see her, to whom she gave good advice and counsel,
'`To prize their time: and oh!
I bless my God, '`said she, '`that I lie now in great peace, And content of mind and soul,
though my body be held with pain.
Oh! that it may be so with you all, my dear friends.`'

When she was very weak, some Friends would ask her if she knew them;`' Yes, '`said she,
'`I know you every one.
I have my understanding as clear as ever, for how should it be otherwise,
since my peace is made with God through the Lord Jesus Christ.
I have no disturbance in mind,
therefore is my understanding and judgment so good and clear,
for it were sad to lie under affliction of body and mind, to feel pinching pangs of body,
even to death, and to lack peace with God.
Oh! that would be intolerable to bear.
Oh! let my soul praise the Lord for his peace and plenteous redemption.`'

Her son-in-law, John Moore, having skill in medicine, administered somewhat to her,
after which they thought she was better, and he was gone towards Swarthmore.
She soon grew worse again; upon which her husband would have sent for him back,
and also for her daughter, but she was unwilling, saying, '`Be not careful in the matter;
the Lord my God is near me, and I have your company, and it is enough,
and all will be well.
If this lump of clay, in which I dwell, be dissolved,
I have full assurance of an house and dwelling, God is the maker of,
that will never wax old, nor be dissolved.
Oh! my soul, bless you the Lord, and be glad in his salvation forevermore.`'

Her illness increased upon her, and many friends came to visit her, to whom she said,
'`Oh! the cross is the only way to the crown immortal.
Shun it not, therefore, lest you fall short of the crown;
and stand up nobly for your testimony to the truth in all things,
and particularly against the popish anti-christian yoke of tithes,
for which many have not only suffered great spoil of goods, but imprisonment till death,
and have received a crown of life.
Oh! if all that have been called to this testimony, had stood firm and true therein,
God would have wrought wonders more abundantly, but unbelief makes a long wilderness;
it is well if some die not in it, and never see the promised land.`'

About two days before she died, she gave good advice to her grandchildren and servants,
and said to her husband, '`My dear,
you have spent much time and strength in serving truth and Friends;
your reward with God is sure.
I never grudged your absence in that good service; and if it be the time of our parting,
as I think now it will, I pray you quit yourself of the things of this world,
as much as may be,
that you may with the more freedom pursue that honorable
service for truth to the end of your days.
I hope the Lord will give you strength to travel into the southern parts again,
and remember my love to all friends, and warn all, but especially the rich, to keep low,
and not be high-minded, for humility and holiness are the badge of our profession.
God Almighty keep us all low and humble; it is a safe and blessed state.
And, my dear, one thing I beg of you; give me up freely to the Lord.
The Lord joined us, and gave us to each other; let us bless his name,
if he now take us from each other in the outward, that is all;
for our joining in spirit stands and remains forever.
Oh! therefore let me go easy out of this world,
where I have had a great share of trouble many ways you know,
and get to that haven of rest, that I have the full assurance of sealed upon my spirit.`'

A little before she died, some fainting fits taking her, she revived again, and said,
'`I was glad, thinking I was going to my eternal rest without disturbance.`'
Again she said,
'`I have both a sight and sense of eternal rest with God in the world to come;
and therefore I labor hard to be swallowed up in immortal life,
and to be made possessor of that rest that cannot be disturbed, where sorrow will cease,
and be no more forever.
Oh! my soul, this is your glorious portion; therefore bless you the Lord,
and wait patiently his good and appointed season.`'
Then she desired to be helped up in her bed; but her pains increased:
she grew very weak and faint, and said, '`I think I grow weak and cold.
My hands and feet are grown very cold, yet my heart is very strong before it yields.
I must meet with sharper pangs than I have yet felt.
My God has hitherto laid a gentle hand upon me.`'
She desired to lie down again, but could not stay, but being set up in bed again,
she said, '`This pain is hard to flesh and blood, but must be endured a little time;
ease and eternal rest is at hand.
I am glad I see death so near me.
Oh! remember me to all my dear babes and grandchildren.
I shall with these eyes behold them no more.
God Almighty bless them all, and make them all his children,
that I may enjoy them forever in the heavens above.
Neither shall I see my sons and daughter.
Ah! my prodigal son, what shall I do for him?
I have prayed and longed for his return.
The time may come, God grant it may, but I shall not see it in my time.
He is my son, the son of a godly father, and therefore I cannot but love him.
Tell him it is his immortal soul`'s well-being that I am concerned for;
not so much his outward state here, for that, though never so miserable,
will quickly end, but the misery of the soul separated from God will never end.
And, my dear, though our counsel has not had the desired end, yet I do entreat you,
remain a father to him in repeated counsel.
Leave him not to run on in the way of misery, but labor and pray for his return.
Oh! you have been true to me in bearing with me many a heavy burden,
and have done abundance for him every way, for my sake;`' with more to that purpose.`'
My love to his wife; I desire she may mind heavenly things,
and pray God bless their offspring, that they may walk in the steps of their grandfather,
who is gone to his eternal rest;`' with well-wishes for her son and daughter Moore,
and blessings upon their children.

The day she died, many friends came to see her, being their monthly meeting-day,
to whom she gave good advice, and expressed her joy and comfort in the salvation of God,
peace and perfect redemption.
Seeing friends weep, she said, '`Be not concerned, for all is well;
I have only death to encounter, and the sting of it is wholly taken away;
the grave has no victory, and my soul is ascending above all sorrow and pain.
So let me go freely to my heavenly mansion, disturb me not in my passage.
My friends, go to the meeting, let me not hinder the Lord`'s business,
but let it be chief, and by you all done faithfully,
that at the end you may receive your reward, for mine is sure.
I have not been negligent, my day`'s work is done.`'

Friends went to the meeting, and in a little time her pains increased,
which she bore with patience, but sighed deeply,
praying the Lord to help her through her agony of death.
After some words, she said, '`Oh! my God, oh! my God, you have not forsaken me,
blessed be your name forever.
Oh! my blessed Lord and Savior who suffered, for me and all mankind,
great pains in your holy body upon the cross, remember me, your poor hand-maid,
in this my great bodily affliction.
My trust is in you, my hope is only in you, my dear Lord.
Oh! come, come, dear Lord Jesus, come quickly, receive my soul.
To you I yield it up; help me now in my bitter pangs.`'
These indeed were very great, and her husband prayed by her,
that the Lord would make her passage easy; and she had no more such pangs,
but drew her breath shorter by degrees, and said very little more,
but that it was good to leave all to the Lord; saying, '`Oh! pray, pray, pray,`'
and so fell asleep in the Lord, in a good old age, being in her seventy-ninth year,
as a shock of corn in season.
She died the 30th of the Ninth month, 1705, and was honorably buried:
many ancient Friends of about thirteen adjacent meetings accompanied her to the grave,
the 3rd of the Tenth month, 1705.

[.asterism]
'''

JOHN WHITING was of Naylsey, in the county of Somerset, yeoman.
In the year 1654, when John Audland and John Camm,
two eminent ministers among the people called Quakers,
were first sent from the north of England to Bristol, and the adjacent counties,
freely to preach the gospel of the grace of God,
and to turn people from darkness to light, and from the power of Satan unto God;
the said John Whiting was convinced of the blessed truth,
and received it in the love thereof, as it was professed by those called Quakers.
He also received the ministers of it into his house,
as he had the truth they declared into his heart; and had meetings held at his house,
to wait upon God, and worship him in the spirit of his dear Son;
and for his ministers freely to preach the gospel of peace and salvation,
as they were sent and required by him.

Although the truth, and those that received it,
were greatly despised in those early days, yet this disciple of Christ,
being made partaker of the like precious faith that was once delivered to the saints,
was zealous for the truth, it being given to him not only to believe,
but also to suffer for the sake of Christ,
among the first of those people to whom he was joined, in that county,
and remained faithful unto death.

In the time of his sickness, and near his end, in a sense of the love of God,
and in love to his wife, with desires for her,
who was then young in the truth which he had received, professed, and had suffered for,
and found peace and comfort in; he exhorted her, saying,
'`As you have believed in the light, so walk in it;`' which showed,
as he loved Christ the true light, he desired she might walk therein.
Truly there are none but those that do evil, who hate the light;
neither can such be saved, until they come to believe and walk in the light,
as all the nations of them that are saved do,
and it is not doubted but this our friend did, and died in the faith of Christ,
and in peace with God through him.

He died the 9th of the Fourth month, 1658; aged about twenty-seven years,
having been convinced four years.

[.asterism]
'''

ANNE DEWSBURY, wife of William Dewsbury, then of Wakefield, in Yorkshire,
a hand-maid of the Lord, in the beginning of the Seventh month, 1659,
had a revelation or dream from the Lord, that her life was nearly finished,
and though she might be exercised with much weakness,
yet in the midst thereof the Lord would strengthen her with his presence,
and in him she should overcome the last enemy, which is death.
Having assurance of what was revealed, though at that time she was in good health,
she made ready what might be serviceable when her change came.
About the 29th of the said Seventh month, some weakness came upon her,
which increased so much, that she was many times, to outward appearance,
near laying down the body; yet the Lord preserved her in much patience,
and fresh in his love.

Her husband, being gone to the farthest part of Scotland in the service of truth,
and to publish the day of the Lord, and preach the gospel of Christ,
was moved of the Lord, the 9th of the Eighth month, to return to her,
and on the 28th of the Eighth month, 1659, he was brought to her with joy in the Lord.
After this she was weaker in her body;
but the Lord gave her strength by his living presence to wait till her change came,
which drew near, and being exercised in her affliction, which lay heavy upon her,
she called to her husband, with certain friends, saying,
'`Pray to the Lord that he may ease his afflicted hand-maid.`'
And the Lord moved them to call upon him,
and immediately he took away the heavy affliction.
Then she magnified the Lord, saying, '`Blessed be his name, he has heard our prayers,
and caused his hand-maid to rejoice.`'
Then she embraced her husband in her arms, saying, '`You are my dear husband;
you are my dear husband; you are clear before the Lord, and have discharged your duty,
and answered your place, like an honest man to your wife.
You are blessed of the Lord; large is your reward.`'
Then she expressed these words, saying, '`Dear husband,
I am clear before the Lord your God.
I have no guilt upon my spirit in the covenant of light and life,
sealed with the blood of Jesus.
I am at eternal peace with him.`'

She exhorted the friends present, saying, '`Oh! friends,
get into the covenant of light and life, get into the covenant,
be faithful to the voice that cries, "`This is the way,
walk in it.`"`' Her strength was much gone, yet prayed to God a season longer,
and breathing to the Lord till much spent, some that stood by her,
seeing her lips and mouth move, but did not understand what her words were,
asked her if she spoke to them, and what she wanted.
She answered, '`I spoke not to you, neither do I want any thing of you.`'
Some time after she called for her husband, who was near, and presently spoke to her,
saying, '`Dear wife, what wouldest you with me,`' she answered,
'`I would have you be with me and see me die.`'
He sat down by her; then embracing her husband in her arms,
and with breathings to the Lord, she laid down her body with joy in peace with him.

[.asterism]
'''

ANTHONY PATRICKSON, formerly of Stockhow, in the parish of Lamplugh, in Cumberland,
received truth in those parts of the country with the first,
and was made by the Lord a minister of the everlasting gospel,
and travelled in several places of the nation of England, and through Scotland, Ireland,
and the Isle of Man, and was diligent in attending meetings,
and admonishing and instructing the weak, and remained steadfast to the end.
He was of a lamb-like spirit, meek, gentle, not easily provoked, ready to do good,
and walked honestly; was of godly conduct,
and preached therein to those that were enemies to the gospel;
so that they would confess, if all the Quakers were like him,
surely they were a good people.
When taken sick, he saw he must depart this life,
and immediately the incomes of the love of God did break in upon his spirit,
with sweet comfort and consolation, and he said,
'`The Lord has given me an assurance of that blessed
inheritance that never will have end.`'

Thus did this faithful witness finish his testimony,
and end his race of this mortal life, the latter end of the Sixth month, 1660.

[.asterism]
'''

MARY PAGE, wife to William Page, of Wellingborough, in the county of Northampton,
a true and faithful hand-maid of the Lord, was taken sick at Warwick prison,
where she had been a prisoner during the space of eleven months and upwards,
for the testimony of the name of the Lord,
which faithful testimony she sealed with her blood,
to the joy of all that beheld her innocent passage, in the power of the eternal God.
This hand-maid of the Lord was enlarged through the
pourings forth of the spirit of the Lord,
and upon her deathbed, in great power,
exhorted all to be faithful and abide in the covenant of light,
and be truly obedient in the meek, lowly, humble,
and self-denying spirit of our Lord Jesus, that,
in the pure love and righteousness of God,
all the dear babes and children of our Father might live in pure union with the Lord,
and one with another, to bear a bold and faithful testimony for the Lord.
Whatever became of the body, it would, she told them, be well every way,
both to the inward and outward man, and to the praise and glory of the Lord forever.

Many times, when she ended her exhortation,
she poured forth her spirit in supplication to the Lord with great fervency,
and what follows is noted.`'
Oh! you powerful God, who are the searcher of all hearts, behold your hand-maid;
and if there be any thing that is not upright before you in the heart of your hand-maid,
make it known to me, you searcher of hearts.
You know I delight to stand approved in your sight in all your ways;
for you are my dear Father,
and have not failed your hand-maid in whatever you have called me to unto this day;
but your presence has attended me, and comforted me through every trial and besetment,
that the enemy of my soul has compassed me about withal.
Oh, blessed God! how have you kept and preserved me to yourself,
and through the power of the Lord Jesus Christ made
me to trample upon the enemy of my soul`'s peace.
Therefore in the name and power of the Lord Jesus Christ, does my soul praise you,
O my God, for my preservation in the power and authority of your spirit,
to bear my faithful testimony for you my God,
all my days until I have finished my course in your will,
oh Lord! my strength and life forever and ever.`'

And, dear Father, look upon your poor oppressed ones, that have no life but in you.
Oh! how do they cry in a sense of their misery, Lord help, or we die.
Oh Lord! you know their necessities, and their needs are not hid from you,
whose righteousness without you is as filthy rags.
Therefore do they cry unto you.
Nothing will satisfy them but your presence.
Oh, powerful Father! raise up your own begotten in the
power and authority of the Lord Jesus Christ,
to reign over all its besetments, that the mourner may rejoice,
and the bowed-down head may be lifted up,
and every hungry and thirsty soul satisfied with the bread and water of life,
which you freely hand forth by the hand of our Mediator, Christ Jesus our Lord,
not for any thing that we have done, or do, but for your own name`'s sake,
that all flesh and boasting may be laid in the dust, and all crowns cast down before you,
that you alone may have all the glory, whose right is over all, says my soul,
forever and ever.`'

And yet notwithstanding that all we have or receive,
is in your free mercy in Christ Jesus, yet this gives not any liberty to sin, oh!
Lord, you know, but rather engages us that are born again to abhor ourselves,
and to stand upon our watch diligently,
that the enemy may not enter with any of his wiles,
to cause us to abuse your grace and free mercies,
which you have so freely manifested to us, in the name of the Lord Jesus,
when we had not any power to help ourselves.
Therefore does my soul, with the souls of your dear and faithful children,
cry unto you to keep us pure in your holy power,
that in meekness and true sincerity of heart, we may wait upon you,
and be obedient in whatever you call us unto, even to the loss of husband, or wife,
or children, or whatever else you require.
If it be to the laying down of the outward man, for your glorious truth,
it will be well every way with all that have not any comfort or help but in you,
you ever-living God, to whom be all glory and honor forever.`'

'`And holy glorious Father of life,
bless and preserve all the people that make mention of your holy and eternal truth, here,
and here-away, and all my fellow-prisoners, with all your suffering members everywhere,
and my dear husband and children.
God bless and preserve them, and take care of them.
Oh! my God, do well for them every way, in keeping them faithful, with my own soul,
unto the end of our days; whether they be few or many, your will be done.
Oh! you holy eternal God, keep your dear children whom I leave.
Oh Lord! you know how dear they are to me; but I commit them wholly to your care,
oh! my God; whom I know certainly will never fail them that are of an upright heart,
and cannot be satisfied but with your living eternal presence in the Lord Jesus,
to whom I commit them all, if I never see their faces in the outward any more.
I know it will be well both with me and them, as we give up unto you,
to be ordered according to your will, our little time we have here to be upon the earth;
to the glory and honor of your great name, you everlasting glorious Father of life,
to whom alone it does belong, says my soul,
with the souls of all your beloved and faithful children and servants,
that you have chosen to glorify you, who alone are God over all, blessed forever,
and evermore.`'

When she had done, a friend asked her how she did, she said, '`I am weak,
but I would go home.`'
'`What,`' said the friend, '`to your eternal home?`'
she smiled and said, '`Yes, when it pleases my heavenly Father.`'
Her tender and loving husband being there with her, drew near unto her,
and she in much love stroked him on the face with her hand,
when tears trickled down his cheeks, and friends weeping by her,
after a little time she put her husband from her, and said,
'`Give me up freely into the arms of my heavenly Father.`'
She spoke no more, but within a little time finished her course with joy,
and laid down her body in peace, near the fourth hour in the morning,
the 17th of the Tenth month, 1665.
