== Chapter 14

[.chapter-synopsis]
* Robert Hatton
* Elizabeth Huntington
* Edward Jefferys
* Margaret Berry
* Thomas Fell
* William Tovey
* William Bevan
* Nicholas Beard
* Elizabeth Hopkins
* John Beere
* Sarah Scott
* William Fennell
* Sarah Soundy

ROBERT HATTON, of Hatton, in Cheshire, was an eminent minister of the gospel,
and faithful in his labors and travels to preach the same for many years,
of a good example, and adorned the doctrine of Christ,
and in his innocent life preached righteousness at home and abroad.
He was a man of substance, solid and grave, and had a good sense of God upon his spirit,
and a divine understanding of things that tended
to the honor of God and the church`'s peace.
He dearly loved unity, and labored earnestly to promote it.
Every appearance of that which obstructed it was grief to him,
but the increasing fellowship of the church his soul rejoiced in.
He was zealous for the holy truth, and concerned for the glory of God;
his soul hated the very appearance of evil, and +++[+++he was]
a sharp reprover of the loose, profane, heady and high-minded,
and such as were lovers of pleasures more than lovers of God.
Being a possessor of the wisdom that is from above, he was mild in exhortation,
and loved tenderness in whomsoever it appeared, and was ready to help the weak.
In suffering, of a noble spirit, bold for the truth, wholly resigned in the will of God,
come what would come, being a man of courage,
and gave great encouragement to suffering friends.
He was a faithful follower of the Lamb,
whatever tribulations or imprisonments he met with, or fines that were imposed upon him,
for the testimony that the Lord had given him to bear.
When spoken to not to preach, he mildly answered, '`If the Lord kindle a sacrifice,
who can forbear to offer;`' and wherever he travelled, he left a good savor behind him.

The day before he departed this life, some of his friends were with him,
to whom he spoke of things relating to the inner man, and said cheerfully,
'`My spirit is very easy, and there is no guilt or burden upon me;`' and at their parting,
he said, '`The Lord knows whether we may see the faces one of another again.`'
The day following, he laid down his head, no doubt in peace with God, and is at rest.

[.asterism]
'''

ELIZABETH HUNTINGTON, daughter of Robert Huntington, of Bowsted-hill, in Cumberland,
was of an innocent life and blameless conduct, and a good example,
of a meek and gentle spirit,
careful and tender over all in whom the least appearance of truth manifested itself.
When it pleased the Lord God, by his mighty power,
to raise her up as an instrument in his hand,
to declare his wonders and show forth his praise,
her travels and labors were great for the truth`'s sake, to turn people unto the Lord;
being not satisfied to eat her morsel of bread alone: and her faithfulness to truth,
was as her crown to her latter end.

About the Seventh month, 1678, her mouth was opened by the power of the Lord,
in which she grew exceedingly in the truth, and the Lord gave her wisdom abundantly,
and she became valiant for the Lord,
and bore an honorable testimony for his name and truth, and was a good example.
By her faithfulness many were turned to the Lord,
for she labored earnestly for the good of all people;
and in the year 1679 she travelled with William Johnson, and Jane Seally,
into Northumberland, Bishopric, and Yorkshire.

In 1680 she visited Friends in Scotland,
with her companions Frances Liddle and Richard Perkin,
and returned to her father`'s house after about three months`' travel.
Soon after, she went again into Northumberland, Bishopric, and Yorkshire,
and returned to her father`'s in the Sixth month.
Upon the 3rd of the Seventh month she was taken sick,
and after some time said to her sister, '`I must leave this troublesome world,
and go into immortality.`'
The Lord kept her near to himself; and as though she had fallen asleep,
she laid down her head in peace on the 9th of the Seventh month, and was buried the 10th,
in the twenty-third year of her age.
In the ministry two years.

[.asterism]
'''

EDWARD JEFFERYS, of Charlecot in Wiltshire, was concerned,
after he had spoken several precious words to those that were with him upon his deathbed,
to give forth the following paper, which was taken from him by Andrew Shepperd,
and being remarkable and prophetical, it is here inserted:

[.embedded-content-document.paper]
--

[.blurb]
=== A word of exhortation and warning from the servant of the Lord, Edward Jefferys, written on the 4th of the Eleventh month, 1685. The power of the Lord was in him, and it constrained him powerfully to exhort all to faithfulness, saying,

Dear hearts! a trying day is yet coming on this nation;
for the Lord will yet farther visit it, and he will sweep away thousands to the grave.
I prophesy of it in the pure fear of Almighty God, who speaks through me his instrument,
who have followed him faithfully, and now heaven`'s joys are prepared for me,
and for all those that faithfully follow him, as I have done.
I have walked in the narrow way of life and peace;
but how many are running in the broad way that leads to destruction?
All my time, from my youth upward, I was inclinable to that which was good.
And who would spend away his day in vanity and folly?
seeing the shortness of time that we have here, to that we shall have hereafter.
Dear hearts, be not concerned for me, although the Lord is pleased to remove me,
he will raise up many Friends when I am gone,
for I must certainly go the way of all flesh, and it will be but a little time,
until you will come after me.
Therefore I desire you may so walk, as becomes the blessed truth of our God;
for because of pride,
the Lord is offended with many that are under the profession of the blessed truth,
which I have sought to promote in my day,
and that the Lord would carry it on to his own praise.
Often has my heart been bowed down in the night season,
intreating the Lord in behalf of all;
often crying to the Lord for the restoration of poor fallen man, universally for all.
Often has my spirit been poured out to the Lord for this king, James the Second,
that now is,
that he might be a promoter of the blessed truth and righteousness in his day.
But I fear whether this will be the man; yet, I say,
the Lord will raise up one in his stead, that shall be as a nursing father,
and as a nursing mother in Israel.
God`'s truth shall prosper in this land.

[.signed-section-context-close]
Fourth of the Eleventh month, 1685.

--

The deceased was an honest, faithful man in his day,
and a minister of the gospel of peace, and labored therein freely for the good of souls,
and died in peace with God, and is at rest.

[.asterism]
'''

MARGARET BERRY, wife of William Berry, of Choptank, in Maryland, was a mother in Israel,
a teacher of good things, desired the good of all, and the Lord was with her.
She was of a meek spirit, diligent in meeting, and stirred up Friends thereunto,
faithful to the Lord in all her trials and exercises she met with in this world,
not willing to gratify the world`'s spirit;
but ready to testify against all superfluity in what kind soever, as in apparel,
or other ways.
She went plain and decent, in modest apparel, with sobriety,
and was exemplary therein to young women,
preferring a meek and quiet spirit as the best ornament, willing to do good to all,
especially to the household of faith, careful to see all things in order in her family,
discreet, chaste, obedient in her place,
ready to give up her husband freely to the Lord`'s service even to the last,
and loved unity among Friends.

And as she lay upon her deathbed, her husband being from home in the service of truth,
with Daniel Gould, of Rhode Island, in and about Accomack, before several Friends,
she said, '`I am freely given up to the will of the Lord,
and if it be his will to remove me hence,
I am well satisfied with what his will and pleasure is,
and am satisfied that I shall lay down my head in peace with him,
blessed be his name forever.
And though my pain be great upon my outward man, I am kept and borne above my pain,
through the goodness of the Lord, in that I have nothing laid to my charge;
but that I have discharged my conscience in his sight by his assisting power.`'
Finding herself very weak in body, not knowing how short her time might be,
she desired her brother Pitt to write what she had on her mind by way of a will;
and said, at that time, '`I would have all left to my dear husband, if living;
and if any part of what I have done, or the whole, be not agreeable to his mind,
he may make it void at his pleasure; for I would not do any thing that should grieve him,
for he never deserved it at my hands.`'

Then she also desired him to write a letter for her to her husband, as follows:

[.embedded-content-document.letter]
--

[.salutation]
Dear and loving husband, William Berry.

After my endeared love to you and dear Daniel Gould,
I thought it right to let you know that I, being very weak in body,
and not knowing what the will of the Lord is touching my outward man;
yet in this am I comforted and refreshed,
that the Lord is not lacking to refresh me with the smiles of his countenance,
and am satisfied it shall be well with my inward man, and that,
when I shall lay down my head, it will be in peace with the Lord,
into whose hands I commit myself, being freely given up, whether life or death,
which is more satisfaction than my tongue can express.

So, dear heart, having something in my mind, to have a few lines written as a will,
and I could not see your face, which thing I more desired than any outward enjoyment,
so could not confer with you; yet what I have done in that kind,
if I should not see your face in mutability,
it is not my mind to do any thing to grieve you, or against your mind.
But when you peruse what I have written, you may, if it please you,
perform or make it void at your pleasure, which I leave to your consideration,
not desiring to grieve you,
nor that you should be straitened in your mind or otherwise upon this account,
or bring yourself under upon any account, but as I have said,
it may be with great clearness.
So committing you, with myself, to the Lord, I take leave,
and remain your true and loving wife,

[.signed-section-signature]
Margaret Berry

[.signed-section-context-close]
The 12th of the Second month, 1688.

--

The day she departed, several friends being there,
she desired them to be called together, and said, '`I have something to say,
if the Lord enable me.
As touching my burial, my dear husband being from home, it must be left to you;
and I desire there may be nothing of great preparation for the same;
though some may say it is covetousness, it matters not.
We have enough, but I am against gratifying the world`'s spirit;
for since I professed the truth,
I never had unity with superfluity at burials or marriages, especially at burials,
and have borne my testimony often against such things, as some of you are my witnesses;
and my dear husband is one with me,
and I know if such a thing should be at my burial it would grieve him,
who is gone upon truth`'s account, and I have freely given him up.
So if any Friend have anything to object, they may freely speak.`'

All Friends were one with her in that concern, and she further said,
'`I desire you may all keep in unity, and be of one mind.`'
She desired James Berry to make her coffin, being cheerful in her spirit;
and desired friends to remember her dear love to her dear husband,
and dear Daniel Gould and friends.
At another time she said to friends that were with her, '`Have your eyes to God,
whom I desire may support the little remnant that is left behind.
There are but a few, but the Lord is all-sufficient; and as you are faithful,
you will be preserved;
for indeed there are a few that have the weight of truth upon their spirits.
The Lord, if it be his will, raise up standard-bearers, and carry on his own work.`'

At another time she said,
'`Surely people had need have nothing to do at this time but to wait upon God,
when it shall please him to remove them; and if it be so with me,
O how will many do when their dying hour approaches!`' Then said, '`Lord, hasten your work,
for there is no ease upon this feather bed for my body,
but I shall be at ease when my body is laid in its cold bed of clay.`'
Some hour before she departed, she desired all friends to go to bed,
and took her leave of them, as if she was going to her long home, as indeed she was.
A little before she departed, the Lord gave her ease,
which she said she never expected in her body,
for which she praised the name of the Lord; so lay still afterwards,
and all was well with her, being freed from the pangs of death,
as appeared by her patient waiting the appointed time of the Lord,
as if she was slumbering.
In that quiet stillness she continued till she gave up the ghost,
and no doubt but she is blessed: as she lived in the Lord, she died in him,
and rests from her labors, and her good works follow her.

She had given many other heavenly exhortations, not noted, to several friends,
and to her youngest son, and others of her family, and several relations,
exhorting all to faithfulness, diligence, and true humility before the Lord.

Her age, the day of her death, and place of burial, I have no exact account of.

[.asterism]
'''

THOMAS FELL, late of Chapel-house, in the parish of Ireby, and county of Cumberland,
was convinced in the year 1653,
it being soon after the Lord had revealed his truth in the North;
and he was also the first married among Friends, at least in those parts.
Although he owned marriage as an ordinance of God,
yet he could not find in all the Holy Scriptures that God ever
appointed any of his priests or ministers to marry any,
or appointed they should have money for so doing;
yet he was cast into prison at Carlisle for not being married by a priest,
and giving him money.
There the said Thomas Fell remained prisoner one year,
and before he had his liberty his wife died.

Afterwards he was a prisoner nearly ten years at
the suit of one Edward Relf and Hugh Simpson,
impropriators, for not paying ten pence per year for tithes,
which they called prescription-money; for which he suffered cheerfully and with patience,
and never murmured.
After it pleased the Lord that he got his liberty clearly,
he travelled in the public service of truth, bearing testimony thereto,
freely preaching the gospel of Christ in England and Scotland,
and divine openings of heavenly things he had.
He was of a blameless life and conduct, and serviceable where he lived;
and as he grew in years, he grew in gravity and zeal for the Lord,
and for the promotion and prosperity of the great work the Lord has begun in the earth,
even to the day of his departure.

A friend visiting him near the hour of his departure, his memory was perfect,
and he said, '`Truth is as precious as ever,
for which I have been freely given up to suffer, labor, and travel,
both in our own country and in Scotland.`'
Indeed, he became as a pillar in the Lord`'s house, and when,
by reason of bodily weakness, he could not travel,
he was concerned that Friends might be kept in unity,
and walk in the fellowship of the gospel.
A little before his departure, he inquired whether they were in love one with another,
and if there were no rent or division;
and when it was reported to him that Friends were mostly well, and truth prospered,
he was comforted, and in great peace he departed this life in 1697,
in unity with the brethren, aged seventy-three years.

[.asterism]
'''

WILLIAM TOVEY, late of Henley-upon-Thames, Oxfordshire, malster,
was convinced of the blessed truth in his young days, and lived to a good old age,
and had many children, whom he had a care to train up in the way they should walk,
and therein he, through faithfulness, has found peace.
He was a just and religious man, careful to discharge his duty to Almighty God,
and to preserve his peace with him, through Jesus Christ his dear Son,
whom God has sent a light into the world, that all men through him might believe.
By that power, which through faith he received,
he was enabled to show a godly and exemplary conduct,
and therefore did adorn the doctrine of Christ our Savior,
and in the time of his bodily weakness was kept in a sweet and tender frame of spirit.

A few days before he departed out of this mortal life, his children being by him, he,
in sweetness and tenderness of spirit, said to them, '`Be faithful to the Lord,
and serve him in your generation.`'
And in particular, calling his son Caleb unto him, and taking him by the hand, said,
'`Dear Caleb, the Lord has a blessing in store for you, be faithful;`' and repeating it,
said, '`Be faithful,
and the Lord has a blessing in store for you;`' with more weighty expressions not noted;
and he added, '`I desire you may succeed in my place; but some may say,
you being but a young man, are too forward; mind it not, but be faithful,
and keep your eye to the Lord, and he will be your reward.`'
Then he said, '`Oh! that a young generation may be raised up in this place,
(Henley) if it be the will of the Lord, that may bear a faithful testimony to his truth,
his living truth.
I am not without hopes, though at present not very likely,
for there is a great deal of rubbish to be removed out of the way.`'
Adding, '`It is not high notions or a bare profession that will do, it is heart work.`'
Being asked to drink some cordial, he said,
'`It is my cordial to do the will of my God;`' adding,
'`I did not know I should have any thing to say; but it is the Lord`'s doings.`'
Then said to them present, '`Be not backward in going to meeting, and say,
we are hindered; no, no, that is the devil`'s work; but be valiant, miss no opportunity;
for as you are diligent in waiting upon the Lord,
that may be revealed to you at one time, that may not at another, or afterwards.`'

Speaking of the goodness of the Lord to the humble,
and how he guided those whose hearts are upright towards him, he said in much tenderness,
'`Seek the Lord while he may be found, call upon him while he is near:
let the wicked forsake his ways, and the unrighteous man his thoughts,
and let him return unto the Lord, and he will have mercy upon him, and to our God,
for he will abundantly pardon.`'
He then prayed tenderly and fervently to the Lord
for the prosperity of his truth in that place;
and expressed the satisfaction he had in discharging his duty in the sight of the Lord,
saying,
'`The quarterly-meeting was pleased to confer the
care of the church in this place upon me,`'
(i. e. he being desired to take care of the poor,
and to have an eye over the professors of truth there,
that they might walk as became their holy profession.)
'`I never did anything in an overly way.
No, no, but in humility and tenderness.
I watched over them for good, though I have been spurned at by some for it,
but the Lord forgive them.`'

He was preserved very sensible, and in greet patience all the time of his illness,
several times saying he had no clog upon him, but was freely given up, saying,
'`I am ready, come my Lord when you please, I am ready.`'
Another time he said,
'`The Lord does not withhold his living presence from me;`' so lifting up his hand again,
said, '`All is well, all is well, I am ready.`'
Near his departure, several of his children being by him, he looking upon them, said,
'`The Lord bless you all, the Lord bless you altogether,
and preserve you in his blessed truth until your last breath.`'
Giving order who should be invited to his funeral,
he said his end in desiring many should be there was for the salvation of their souls;
and if but one should be reached and come to the knowledge of the truth and be saved,
it would be well, and that which he desired.
Then said, '`I am wholly given up to the will of the Lord,
and I hope he will make my passage easy;`' and indeed
the Lord was pleased to answer his desire,
for he went away without sigh or groan, the year 1700, being seventy-seven years old.
He is entered into the joy of his Lord, and by faith, he being dead, yet speaks,
or is yet spoken of, as it is said of righteous Abel.
The weighty sayings following, being found of his own hand-writing,
some years after his decease, by his son Caleb, are here printed,
being worthy of observation.

[.offset]
'`Stand in awe of the living God, that created you to glorify his name.`'

[.offset]
'`Refrain from all evil, and love righteousness.`'

[.offset]
'`Do nothing that may bring dishonor to truth,
if the whole world might be gained thereby.`'

[.offset]
'`According to the ability or talents the Lord does give you inwardly or outwardly,
do you serve the Lord, his truth, and people.
Those that profess and possess the truth, that love it above all things,
that can venture all for truth`'s sake; such do you have true unity with,
but not with backbiters, or careless professors of truth.`'

[.offset]
'`If any difference does arise between Friends or others,
do you endeavor to put an end to it, in the spirit of meekness.
The rough nature is Esau, but the meek and lowly is the true seed.`'

[.offset]
'`Do justly, love to be merciful, that you may walk humbly with your God;
that when you have ended the days of your natural life,
you may lay down your head in peace with the living God; which far exceeds all the world,
or the world`'s enjoyments.
And in so doing, you will not only answer the requirings of the Lord,
but of your dear and tender father also.`'

[.asterism]
'''

WILLIAM BEVAN, of Swansea, in the county of Glamorgan, aged seventy-four years,
being sick and weak in body, and judging the time of his dissolution to be nigh,
said unto his son Silvanus Bevan, his daughter Hester being present,
'`I desire that you may live in love together when I am gone, and keep to meetings,
and let your houses be open to those that bring glad tidings of the kingdom of peace,
for they are faithful laborers, and if you have but little, God will add a blessing.`'
Being asked if he would take any thing to support his spirits, he refused, and said,
'`All is well, and that he saw no cloud of darkness before him, but blessed God,
that he had brought him into the inner court,
and if he had strength he could sing for joy;`' with many other comfortable expressions.
At another time when weak in bed, his son Michael, James Picton,
and kinsman William Bevan, and his son Silvanus Bevan, being present,
he said to this effect, '`Grandson William, be obedient to those you are under;
fear God always, and run not into the fashions of the world;
but behave yourself humbly and lowly, and God will add a blessing to your endeavors.
And son Michael, you know much, and God has given you much understanding.
You have a large memory of the Holy Scriptures; mind the gift of God`'s Holy Spirit,
and then you will be a good man, and a serviceable man,
and a preacher of righteousness in your life and conduct.`'

He also exhorted his sons to be kind to their sister,
and to honor and assist her in the choice of a husband,
that he might be one that fears God, and lives uprightly, and on all occasions; '`For,`'
said he, '`she has been careful and tender of me since your mother died,
and a support to my old age: so live in love together,
that others may behold you as a family of love, and then the Lord will bless you.`'
At another time, his son Silvanus, and many of his grandchildren being by his bedside,
he said, '`Fashion not yourselves after this world,
but transform yourselves to the image of the dear Son of God.
Be not puffed up in pride and gaudy apparel, but in the fear of God:
adorn yourselves modestly, as becomes Christians to do,
and keep to the small grain of the kingdom,
and then you will grow and flourish in holiness to the praise of God,
and lie down in peace, as you see me now.`'
And renewing his advice, of being a family of love when he was gone, said,
'`Strive not who shall be greatest,
but who shall be the humblest and most serviceable among you,
for that will be joy and peace in the Holy Ghost.
But an exalted mind brings pain and trouble; I know it.
If you will be careful and obedient to that small grain which God has sown in your hearts,
he will fulfill his promise; I am sure he will fulfill his promise,
and you will lie down in peace.
I have left something to every one of you.
If you do well, it will be a blessing, if not, a curse;
as the children of Israel desiring flesh, not obeying the Lord,
not content with their condition, God gave them flesh in his wrath,
and they died while it was between their teeth.
So to the Lord I leave you, desiring him to bless you,
which is the best portion I can give you.`'
His children all kissing him, concluded at this time in much tenderness and tears.

Many other comfortable expressions dropped from him, which were not taken in writing,
nor can it be justly remembered, importing tender advice and exhortation to his children,
showing forth greatly the joys of a peaceable conscience in our Lord Jesus Christ.
At another time, though very sick, and in much pain, about midnight,
on a sudden he was still and quiet, and in a little while said,
'`The Lord has removed the pains of death, his glory shines in his weak servant.
Hallelujah, hallelujah, praises, praises be to him forever;`' with other good expressions,
and so continued singing a minute or two,
as one whom the Lord had assured of his salvation, and exalted above the fears of death,
or the terrors of the world to come, being supported by the spirit and power of religion,
which the agonies of death are not able to shake.
So having seen twenty of his children`'s children, and growing weaker and weaker in body,
he resigned up this life in that quietness and innocency in which infants go to sleep,
the 5th of the Twelfth month, 1701,
and was buried by his wife in Friends`' burying-place in Swansea.
This good old man, through faith and obedience in and to the Lord Jesus Christ,
and by a patient continuing in well-doing to the end,
has no doubt the reward of immortality, eternal life, and inherits glory, honor,
and peace with God in his holy, kingdom, and will do forever and ever.

[.asterism]
'''

NICHOLAS BEARD, of Rottingdean, in the county of Sussex, was in his youth a tender,
seeking young man after the knowledge of the Lord,
and for nearly twenty or thirty years would often ride many
miles to hear the best reputed teachers the times afforded.

In the year 1655 he was convinced of the blessed truth of God,
by the ministry of that eminent servant of Christ, George Fox,
and received it in the love thereof, and was faithful thereto.
It pleased the Lord to call him into the ministry,
and he labored in the work thereof in the county wherein he lived,
and the neighboring counties.
He was a constant attender of quarterly, monthly, and weekly meetings,
as long as strength of body would admit; and after that failed, that he could not go far,
continued visiting the nearest meetings, constant, sound in doctrine, fervent in prayer;
and to his children would often say, '`That which is right do, and the Lord be with you.`'
And in the sense of the Lord`'s goodness, would often say, '`Be bowed before the Lord,
oh! my soul.`'
Growing weak in body, being in his chamber, and some of his children with him,
with lifted up hands and eyes, he said, '`I must leave you to the teachings of the Lord,
and the Lord in mercy be with you.`'
Being weak in his bed, in melody of spirit, he was heard to say, '`Oh!
Lord, my soul blesses you, and all that is within me magnifies your holy name.`'
He often desired to depart, and be with Christ in peace,
which he also signified would be his portion in the world to come.
So departed this life, in peace with the Lord and unity with the brethren,
the 2nd of the Fifth month, 1702,
having ordained in his will that his executor should entertain his friends,
the people called Quakers, in his house, as he in his lifetime did: aged eighty years;
a minister about thirty years.

To show that he was not only called to believe, but also to suffer,
I shall briefly recite some of his sufferings.

For his testimony against paying tithes in this gospel-day,
he had taken from him by one Robert Baker, priest of Rottingdean,
for one year`'s tithes demanded, twelve oxen, six cows, and one bull,
which were sold the same day at Lewis-clift fair
for one hundred and eleven pounds five shillings;
but worth more.

For the worship of God, or meeting only for that end,
and keeping the testimony of a good conscience, in obeying Christ`'s command,
"`Swear not at all,`" and abiding in his doctrine, and for not bearing arms,
or sending out in the militia, and not frequenting the public worship,
he was prosecuted on the statute of twenty pounds per month, and underwent imprisonment,
and sustained the loss of his goods, and many other abuses.
Yet it pleased the Lord to support and bless him;
so that although his loss was more than one thousand pounds,
and his charge of children considerable, being the father of above twenty,
yet he gave them that lived good portions, being twelve;
also lived to see several of them well settled in the world,
leaving his youngest son in his own seat,
in a much more plentiful estate than his parents left him,
though he was a prisoner several years.

[.asterism]
'''

ELIZABETH HOPKINS, wife of Thomas Hopkins, of Glastonbury, in Somersetshire, loved truth,
and those that were faithful to it, although she was but young in it;
and when taken sick was not discontented, but resigned to the will of God.
Being asked whether she was willing to die, she said, '`I am fitted to die,
and fully satisfied.
I find nothing in my way that hinders me from peace with the Lord;`' and lay often
praising the Lord for his great lovingkindness and mercy to her,
in bringing her to the knowledge of the truth.
Towards her end, she said, '`Lord,
make my passage out of this world easy;`' which he was pleased to grant,
and she passed away like a lamb, or one going to sleep.
She departed in true and living faith, the 16th of the Sixth month, 1703,
after several months`' weakness, and was buried in Friends`' burying-ground at Glastonbury.

[.asterism]
'''

JOHN BEERE, of Weymouth, in the county of Dorset,
was born of believing parents in the year 1659,
and when he grew up he embraced the same faith,
and professed truth in much plainness and sincerity, and was, through the power of it,
of a blameless conduct, a good example, and of great service in the church.

In the year 1693, being about thirty-four years of age,
he received a gift of the ministry, in which he was a faithful laborer,
though he did not travel far, but had good service in his own country,
and was well beloved and esteemed by his friends and near neighbors,
to whom he administered much tender and wholesome advice.
In his last sickness, two days before he died, he sent for a friend and neighbor, who,
when he came, asked him how he did; he replied, '`I have but one pain to encounter with,
that is the pain of my body, for my mind is at ease.`'
And at another visit of the same friend he repeated the same.
The day that he departed there were several friends and others to visit him,
to whom he gave seasonable advice, desiring them to be faithful, saying,
'`Although you are few in number,
if you continue faithful the Lord will increase you;`' and desired
them to make their peace with the Lord in the time of their health,
for on a deathbed they would have enough to do to struggle with the pain of the body;
for he said if he had not made his peace with the
Lord before he came on a dying-bed he had been miserable.
Another time, his eldest daughter asking how he did, he said,
'`I am waiting for my change;`' and desired his children to be obedient to their mother,
and keep out of all evil company.
Many were the seasonable and comfortable expressions which he gave
forth in the time of his weakness that cannot be remembered.
He died the 5th of the Seventh month, 1703.
Aged forty-four years; a minister ten years.

[.asterism]
'''

SARAH SCOTT, daughter of Francis Scott, of Hambridge, in the county of Somerset,
aged four days short of thirteen years,
was educated in the way of truth professed by the people called Quakers,
from the age of three years, by her uncle and aunt Whiting, who took her as their own.
She was of a loving and affable temper, and sober behavior, but of a weakly constitution,
not given or addicted to any bad words or actions; yet, when she came upon a sick bed,
it seemed hard sometimes for her to be reconciled to her sickness.
But upon reading several places in the New Testament,
concerning afflictions and chastisements, as Heb.
xii., etc., she came to be reconciled to both, and afterward received great satisfaction,
so that her heart was often enlarged in the love of God,
and her soul did magnify the God of her salvation.

Her uncle, J. Whiting, asked her if she was willing to die; she said,
'`If I had assurance of the love of God, I should.`'
Then he asked her if she had any thing that lay upon her mind that troubled her.
She answered no, nothing in particular, but that she had lived no better,
or more circumspectly; but upon his mentioning to her the mercy of God in Christ Jesus,
who died for her, she said, '`If it be the will of God to take me to himself,
I am content.`'
She frequently prayed in secret to the Lord; and once, being spoken to when still,
she said, '`Let me alone, that I may meditate on my God;`' and afterward said,
she enjoyed the streams of the love of God, but found the enemy so busy,
that it is hard to keep my mind stayed on the Lord;`' adding,
she was sorry for all that did live wickedly,
and lamented what many would do when they came upon a deathbed;
and desired her aunt to advise one of her acquaintance to take more
care of her words and actions, or she would find it hard when she came upon a deathbed.

She said, '`I have had much trouble, the enemy having been busy, when I was in meetings,
so that I looked out sometimes, and neglected the inward work,
for which I have known sorrow.
I have gone through nights of sorrow and prayer; but now I am made willing to die.
I shall go to a glorious place, where there is no temptation nor sorrow,
and where all tears shall be wiped from the eyes;`' adding,
'`My spirit is comforted in the love of God, and if I had lived more in the fear of God,
I should have been more comforted.
The Lord has been good to me, I am willing to die; it seemed hard to me sometimes,
yet now it is made easy.`'
And said, '`All must be humbled, and brought low, one time or other.
They must bow; if they will not bow in mercy, they must in judgment.`'
Adding, '`It is well for me that I have been afflicted;
else I might not have known the things that belong to my peace;
but now I cannot say I do not know them, for I do now see them, and rejoice in them.`'

Next morning she expressed a concern for a near relation,
desiring that she might live in the fear of God, saying,
"`The fear of the Lord is the beginning of wisdom.`"
She lamented those that live in pride, and spend much time in adorning the body,
and walking wantonly.
After, she magnified the Lord`'s goodness, saying, '`The Lord is a gracious God,
and of great mercy and righteousness, and I trust in him.`'
She prayed very devoutly, and implored the Lord`'s mercy,
and praised him for his goodness, and gave good advice to those present,
particularly to the party afore hinted, saying, '`Be careful of your words and carriage,
especially in meetings, to keep in your mind,
for God is to be worshipped in spirit and truth,
and that God had given her a measure of his grace,
that she should serve him while she was in health, for when she came to a sick-bed,
and in pain, it would be harder.`'
After, she said, '`Remember my love to all Friends that ask for me;`' and then prayed,
saying, '`O! Lord Jesus, receive my soul, if it be your heavenly will.
O! Lord, I am truly resigned to your will.
O! Lord Jesus, come quickly, if it be your heavenly will; and!
Lord, make my passage easy.
O Lord! send your angel to conduct me to your heavenly kingdom.
O Lord! you are beautiful.
O Lord! hear my prayer, and grant me my request, if it be your heavenly will.
Give me power over the enemy; he is a cunning enemy, a subtle serpent.
O Lord! keep me from his temptations, who lays his baits at every corner.`'

Again she said, '`There is nothing to be compared to your love;
all the world is but as a fading flower!
What will it avail a man,
to gain the whole world, and lose his own soul.
O! what need have people to go with their heads so high,
when they must all be laid in the dust.
O Lord! you are sweet, your countenance is comely.
O Lord! how have you refreshed me many a time, after I have prayed to you.
O! that you wouldest crown me with glory.`'
And said, '`O! that we may all meet again in the kingdom of heaven.`'
After, she said, '`O Lord Jesus! there is none like unto you,
the author and finisher of our faith, to help, and none else can.`'

The day before she died, she said, '`O Lord! you are the great physician of value,
the heavenly physician, who can do that which none else can.
You can raise from the dead.
Speak the word, and it shall be done.
You are a gracious God, and of great mercy, and full of righteousness.
Your mercies deserve to be had in everlasting remembrance,
from the beginning of the world, to the end thereof.
O! Lord Jesus, you have tendered my spirit, and humbled my soul.
Your works are too wonderful to be +++[+++fully]
spoken of;`' with many other heavenly expressions.
In the evening, her relations thinking she had been departing,
after some time she looked up, and said, '`Pray for me.`'
Her uncle Bowles being present, found a concern upon him to pray to the Lord for her.
Then she said to her aunt,
'`Do not grieve when I am gone;`' and desired her the
next time the Lord did visit her in that manner,
not to disturb her.
That night she took her leave of all who were about her, in a very solemn manner,
taking them by the hand, and bidding them farewell; and after, said to her aunt,
'`Now I am just a going,`' and said, '`Come, Lord Jesus, come quickly.
Into your hands I render my soul.`'
Her aunt Bowles coming in, asked her how it was with her; she answered,
'`Very well;`' which were her last words,
and in a few minutes passed away without sigh or groan, on the 27th of the Eighth month,
1703.
Aged four days short thirteen years.
She was buried the 30th of the same, from Bull and Mouth meetinghouse,
at Friends`' burying-ground, near Bunhill-fields, London.

[.asterism]
'''

WILLIAM FENNELL, aged about twelve years, son of William Fennell of Youghall in Ireland,
shop-keeper, took to his bed the 24th of the 12th month, 1703,
the Lord having visited him about two years before,
and often followed him with the reproofs and convictions of his Holy Spirit,
when he had sometimes been wild, and run to play among other children.
When he was brought on his sick bed, not many days after,
he was under an inward exercise of mind, and desired his mother to read by him.
Another time he desired to have the ten commandments read to him; which were,
and he was asked how far he found he had kept them.
He answered he had not, as he could remember, ever taken the Lord`'s name in vain,
and that he loved and honored his father and mother,
and had been careful not to tell lies or false stories on any one,
nor had he stolen any thing, except taking some plums without asking leave,
and hoped the Lord would pass it by, with what else he had done amiss.
Remaining very weak, he was asked if he was willing to die; he answered,
'`If I thought I was fit.`'

The 3rd of the First month, two English friends being in town,
he desired they might have a meeting in the chamber with him; which they had,
and he afterwards expressed his satisfaction therein;
and then he broke forth in much trembling, saying,
'`Lord! forgive all my faults that I have done, and have mercy and pity on my poor soul.
Keep out the enemy that is ready to come in upon me, for none but you,
O Lord! is able to do it;`' with much more.
He then called for his sisters and brother, and exhorted them to love and fear God,
and pray to him to fit them to die, and to love truth, and to go to meetings,
and to think upon God and good things, and the Lord would love them.
He bade them do what their father and mother bid them, and be obedient to them,
and look in their bibles,
and they would find it was God`'s command to children to obey their parents,
for it is well pleasing to the Lord.

To one of his companions, being near, namely Edward Lawndry, he said,
'`Do you think you are fit to die?
If you think you are not, then pray to the Lord, and desire him to make you fit,
and do not mind play too much;`' saying he was sorry he had so long,
but he hoped the Lord would forgive him.
Lying still some time, being under a concern of mind, he was asked what his concern was.
After some pause he answered,
'`I am desiring the Lord to bring me in with the rest
of his lost sheep;`' with more to that purpose,
saying, '`I have cried unto him many a night, since I have been not well;
for I have been a wild boy, and loved play too well,
and when you have sometimes corrected me, I took it a little hard;
but now I am glad you did, and I cannot express the love I now have for you,
for taking that care of me.
You did well; had you not done it, I might have been wilder; for,`' said he,
'`the Lord has been following me, and striving with me, to bring me down these two years,
and let me see when I have been running to play, if I continued running on to be wild,
then weeping, wailing, and lamentation would be my portion.

'`Sometimes I have turned back, and have gone into the garret and wept bitterly,
and have desired the Lord to help me; but after, when enticed by my comrades to go,
I was not able to resist the temptations, which was my great trouble,
and I have got into a secret place to endeavor to retire,
and often have prayed to the Lord in the night-season on my knees,
when others have been asleep.`'
This child cried out, saying, '`Oh! the Lord loves solitariness,
he does not love laughing and joking; I never read that Christ smiled,
but often prayed and wept.`'
Then he prayed, '`O Lord! hear me, and have pity on me;
for you know I am very sorely afflicted.
Lord help me.
Oh! it is none but you that can do it, Lord.
O Lord! be near me, and allow not the enemy to prevail over me.`'
Speaking of the Lord`'s prayer, this child said,
'`I have much lamented how people teach their children the Lord`'s prayer,
without minding the depth that is in it, saying,
"`Our Father who art in heaven;`" but they that remain in wickedness are not his children,
so cannot rightly call him Father.
"`Hallowed be your name;`" but too many dishonor it by their wicked words.
"`Your kingdom come:`" Oh! but too few let the Lord live and have dominion in them.
"`Your will be done in earth, that is,`' said he, '`in our earthen body.
"`As it is done in heaven;`" and alas! we all know
there is nothing but the will of God done there:
oh! but how little of the Lord`'s will is done here.
"`Give us this day our daily bread:`" O Lord,`' said he, '`give me daily bread from you.
"`Forgive us our trespasses,
as we forgive them that trespass against us;`" but oh! how unwillingly
do many people forgive them that trespass against them.
How can such expect forgiveness of the Lord?
"`Lead us not into temptation, but deliver us from evil.`"`' Then he said,
'`Oh! leave me not in temptation, but deliver me from the tempter;
for yours is the kingdom, and all power is with you, and glory forever.
This prayer,`' said he, '`people teach their children by heart, and think it is enough.
I have been at play with a boy in the street, and his father has called to him, saying,
"`Have you said your prayers today?`"
and he has gone in from me, and stood behind the door,
and has said this prayer as fast as he could, for haste to go to play again.
I hearkened to him all the while.`'

Such careless ones he lamented; and he gave good advice to many that came to him,
and advised the servant-maid against speaking bad words;
and though his breath grew short, he said,
'`I desire to please the Lord always;`' and so continued in a wonderful manner.
He was very resigned to the will of the Lord,
and desired his parents to give him up freely, and then took his leave,
in great tenderness, of his father, mother, sisters, and brother, and relations;
desiring to have his love remembered to his grandmother,
and some other relations and friends that were not present.
Pausing, he said, '`Oh! what joy I feel!`' praising the Lord, while strength remained,
till near the minute of his departure, and resigning himself to the Lord.
His last words heard were, '`O Lord!`' What followed could not be understood,
his breath failing, and so sweetly departed, being the 14th of the First month, 1704.
Aged twelve years and a half, and two days.
He kept his bed about eighteen days.

[.asterism]
'''

SARAH SOUNDY, wife of William Soundy, of Reading, and daughter of William Tovey,
of Henley-upon-Thames, in Oxfordshire, was trained up in the fear of God,
and when on her deathbed,
she breathed forth in an extraordinary manner praises to the Lord; and said,
'`The Lord is a merciful God.
I find him so to my soul.
He spreads a table for his children, and the dainties he sets thereon,
and his children feed thereat.
He honors me with his presence, and that is favor enough.
As for this world, it is but a bubble.
I would not change my condition for any of yours,`' meaning those then by her bedside,
'`although I might have my health; for I can never be better satisfied to die,
than now I am;`' with many more heavenly expressions,
which she delivered one day after another; which were not noted.
She farther said, '`What have I done that the Lord should be so good to me?
Many have been great sufferers; but I have done nothing;
so that if I have but the least place in the kingdom, I shall be satisfied,
although it be but a door-keeper.`'

She died the 24th of the Twelfth month, 1703, at Ridge,
and was buried in Friends`' burying-ground in Henley-upon-Thames,
the 28th of the Twelfth month, 1703.
