== Preface.

[.chapter-subtitle--blurb]
+++[+++By Another Hand.]

[.salutation]
Friendly Reader:

Give ear to that advice which was given by the lawgiver in Duet. 32:29,
in the words of that song wherein he broke out, saying, "`Oh! that they were wise,
that they understood this, that they would consider their latter end.`"
Herein is expressed his care for the good of that people;
but how little many regarded it is apparent by their forgetfulness of the Lord,
who had done marvellously for them.
For how did they provoke the Lord to anger, after various manners, as is recorded of them,
some by a vicious course of life,
thereby neglecting both their present good and future happiness;
which might well occasion the prophet Amos to say, chap.
4:12, "`Prepare to meet your God, O Israel!`"
Here is an agreement, and holy harmony of these good men, in a matter of so great an importance.

A cloud of the like-minded might be produced on this occasion,
which for brevity sake are here omitted,
to show the care of the religious on this account,
and also the negligence of the irreligious.
They did not lack a profession, but for lack of fearing the Lord, and serving him,
although they had the law dispensed to them by the disposition of angels;
nevertheless they were disobedient, and rebelled against the Lord,
and cast his law behind their backs, and resisted the Holy Spirit,
as said the blessed martyr Stephen, whom they stoned to death,
though they were not able to resist the wisdom and spirit by which he spoke.
Let none professing Christianity follow their example,
but by these foregoing instances beware,
and learn to mind the grace of our Lord Jesus Christ,
that so they may choose the things that belong to their peace,
before they are hid from their eyes.

The promotion of piety was intended by the compiler
of the three former volumes of dying sayings,
which met with such general acceptance,
that many have desired the continuation of so good a work,
which does in a measure conduce, through the good Spirit of God,
to awaken people to a preparation for death; a work, indeed,
so very necessary for the children of men to observe, and be concerned about,
that none ought to neglect it; for death most certainly will overtake all flesh;
but when, where, or how, is generally hid from men;
it is a secret that the Almighty has kept from them.

How does it therefore behoove all to be in readiness against the coming of the Lord.
There are few but will readily confess such a preparation ought to be,
though by too many it is neglected; in order to which,
I entreat that it may be your chiefest care to fear God, and keep his commandments,
for that is the conclusion of the whole matter; without which, profession, worship,
and confession to the very truth, profit little.
Wherefore let godliness be your chiefest concern,
that you thereby may have the profit of this life, and of that which is to come,
life everlasting.

Oh! prize the season of the love of God unto you, in affording you heavenly light,
by which you may see his way, and how to walk well-pleasing to him therein,
who calls to you by a word behind you, saying, "`This is the way, walk in it.`"
Reader, take heed to this teacher, which is come near to your soul,
that you may be guided into all truth, by the Lord Jesus Christ manifested in spirit.
Let him be your counsellor; and if sinners entice you, consent not;
for blessed is the man who walks not in the counsel of the ungodly.

Awake, oh! daughter of Zion, and wait for the coming of the bridegroom.
You have a lamp: take oil in your vessel, that you may enter in with him.
Be wise betimes, for wisdom says, "`I love them that love me,
and they that seek me early shall find me.`"
And again, it is advised to get wisdom, and with all your getting, get understanding;
the first is got by fearing the Lord, the second by departing from evil.
The exhortation of old was, "`Remember your Creator in the days of your youth,
before the evil days come, when you shall say, I have no pleasure in them;
in the day when the keepers of the house shall tremble,
and the strong men shall bow themselves.`"

Prepare for such a day, for what do you know but it may be near to your door?
Therefore spend not your time in vanity, or excessive care, saying, "`What shall I eat,
or what shall I drink, or with what shall I be clothed?
But first seek the kingdom of God, and his righteousness,
and all these things shall be added; for your heavenly Father,
(said our blessed Lord,) knows that you have need of these things.`"
The Psalmist said, "`I have been young, and now I am old;
yet have I not seen the righteous forsaken, nor his seed begging bread.`"
By all which it does appear, that the Almighty, who feeds the ravens,
provides a necessary supply for his children,
and a little with the blessing of the Lord is sufficient,
although with some a great deal has not served.
For lack of a moderate care, some, like the prodigal, have spent their portion;
others through sloth, which comes to what the wise man said,
"`He that is slothful in business, is brother to him that is a great waster.`"
Therefore let your moderation appear in all things; neither be overly thoughtful to get,
nor careless in spending.

Live not unto yourself, but unto him who died for you, and rose again,
who was our great pattern of self-denial; and taught,
that if any man would come after him, he must deny himself, and take up his daily cross.
This, alas! proves hard to some, as it did to the young man, Matt. 19:22,
who went away sorrowful, and would no more sell all that he had,
though for the gaining of eternal life, than many will now forsake evil, and do good,
that they may do well forevermore.

What argument shall be used, to persuade men to seek after peace with God,
and acceptance with him?
to choose with Mary, the good part;
which may be attained to by true humility and the fear of the Lord,
as was evidenced by her patience and true contrition,
which is but little regarded by some, especially of the youth;
who rather are pleasing themselves with the gaiety and other vanities of this world,
spending much of their precious time in adorning themselves
after the foolish modes and vain fashions thereof,
which pass away.

How many spend their days thus, and in a moment go down to the grave,
and their candle is put out.
So little is eternity thought on, that when death comes,
it is the greater surprise to such, who are ready to say, "`Woe unto us,
for the day goes away,
and the shadows of the evening are stretched out.`"
Then a little more time to recover strength,
or make their peace with God,
would be greatly acceptable to such whose glass is nearly run,
who are travelling through the valley of the shadow of death;
and the glory of this world is stained, and the beauty of it is fled away.
What would a soul in such distress give, if it were to be purchased,
for an inheritance in the kingdom of heaven?

Much might be said on this subject, of reminding the living to prepare to die,
that a volume might be written on purpose,
without meddling with the sayings of the deceased;
but the words of the dying may make a deeper impression than what is here written.
I therefore recommend you, serious reader, to the perusal of what follows;
and to the grace of God,
by which it may be made advantageous to your everlasting well-being,
when time here shall be no more.
