== Chapter 2

[.chapter-synopsis]
* William Fennell
* Sarah Soundy
* Mary Stubs
* Ambrose Rigge
* George Fooks
* Anne Truss
* Humphrey Woolbridge
* William Harris
* Gilbert Latey
* William Stovey
* Elizabeth Dickinson
* Sarah Blackhouse
* John Tomkins
* Robert Huberstie
* John Carlile
* John Ellis

WILLIAM FENNELL, aged about twelve years, son of William Fennell of Youghall in Ireland,
shop-keeper, took to his bed the 24th of the 12th month, 1703,
the Lord having visited him about two years before,
and often followed him with the reproofs and convictions of his Holy Spirit,
when he had sometimes been wild, and run to play among other children.
When he was brought on his sick bed, not many days after,
he was under an inward exercise of mind, and desired his mother to read by him.
Another time he desired to have the ten commandments read to him; which were,
and he was asked how far he found he had kept them.
He answered he had not, as he could remember, ever taken the Lord`'s name in vain,
and that he loved and honored his father and mother,
and had been careful not to tell lies or false stories on any one,
nor had he stolen any thing, except taking some plums without asking leave,
and hoped the Lord would pass it by, with what else he had done amiss.
Remaining very weak, he was asked if he was willing to die; he answered,
"`If I thought I was fit.`"

The 3rd of the First month, two English friends being in town,
he desired they might have a meeting in the chamber with him; which they had,
and he afterwards expressed his satisfaction therein;
and then he broke forth in much trembling, saying,
"`Lord! forgive all my faults that I have done, and have mercy and pity on my poor soul.
Keep out the enemy that is ready to come in upon me, for none but you,
O Lord! is able to do it;`" with much more.
He then called for his sisters and brother, and exhorted them to love and fear God,
and pray to him to fit them to die, and to love truth, and to go to meetings,
and to think upon God and good things, and the Lord would love them.
He bade them do what their father and mother bid them, and be obedient to them,
and look in their bibles,
and they would find it was God`'s command to children to obey their parents,
for it is well pleasing to the Lord.

To one of his companions, being near, namely Edward Lawndry, he said,
"`Do you think you are fit to die?
If you think you are not, then pray to the Lord, and desire him to make you fit,
and do not mind play too much;`" saying he was sorry he had so long,
but he hoped the Lord would forgive him.
Lying still some time, being under a concern of mind, he was asked what his concern was.
After some pause he answered,
"`I am desiring the Lord to bring me in with the rest
of his lost sheep;`" with more to that purpose,
saying, "`I have cried unto him many a night, since I have been not well;
for I have been a wild boy, and loved play too well,
and when you have sometimes corrected me, I took it a little hard;
but now I am glad you did, and I cannot express the love I now have for you,
for taking that care of me.
You did well; had you not done it, I might have been wilder; for,`" said he,
"`the Lord has been following me, and striving with me, to bring me down these two years,
and let me see when I have been running to play, if I continued running on to be wild,
then weeping, wailing, and lamentation would be my portion.
Sometimes I have turned back, and have gone into the garret and wept bitterly,
and have desired the Lord to help me; but after, when enticed by my comrades to go,
I was not able to resist the temptations, which was my great trouble,
and I have got into a secret place to endeavor to retire,
and often have prayed to the Lord in the night-season on my knees,
when others have been asleep.`"

This child cried out, saying, "`Oh! the Lord loves solitariness,
he does not love laughing and joking; I never read that Christ smiled,
but often prayed and wept.`"
Then he prayed, "`O Lord! hear me, and have pity on me;
for you know I am very sorely afflicted.
Lord help me.
Oh! it is none but you that can do it, Lord.
O Lord! be near me, and allow not the enemy to prevail over me.`"
Speaking of the Lord`'s prayer, this child said,
"`I have much lamented how people teach their children the Lord`'s prayer,
without minding the depth that is in it, saying,
'`Our Father who art in heaven;`' but they that remain in wickedness are not his children,
so cannot rightly call him Father.
'`Hallowed be your name;`' but too many dishonor it by their wicked words.
'`Your kingdom come:`' Oh! but too few let the Lord live and have dominion in them.
'`Your will be done in earth,`' that is,`" said he, "`in our earthen body.
'`As it is done in heaven;`' and alas! we all know
there is nothing but the will of God done there:
oh! but how little of the Lord`'s will is done here.
'`Give us this day our daily bread:`' O Lord,`" said he, "`give me daily bread from you.
'`Forgive us our trespasses,
as we forgive them that trespass against us;`' but oh! how unwillingly
do many people forgive them that trespass against them.
How can such expect forgiveness of the Lord?
'`Lead us not into temptation, but deliver us from evil.`'`" Then he said,
"`'`Oh! leave me not in temptation, but deliver me from the tempter;
for yours is the kingdom, and all power is with you, and glory forever.`'
This prayer,`" said he, "`people teach their children by heart, and think it is enough.
I have been at play with a boy in the street, and his father has called to him, saying,
'`Have you said your prayers today?`'
and he has gone in from me, and stood behind the door,
and has said this prayer as fast as he could, for haste to go to play again.
I hearkened to him all the while.`"

Such careless ones he lamented; and he gave good advice to many that came to him,
and advised the servant-maid against speaking bad words;
and though his breath grew short, he said,
"`I desire to please the Lord always;`" and so continued in a wonderful manner.
He was very resigned to the will of the Lord,
and desired his parents to give him up freely, and then took his leave,
in great tenderness, of his father, mother, sisters, and brother, and relations;
desiring to have his love remembered to his grandmother,
and some other relations and friends that were not present.
Pausing, he said, "`Oh! what joy I feel!`" praising the Lord, while strength remained,
till near the minute of his departure, and resigning himself to the Lord.
His last words heard were, "`O Lord!`" What followed could not be understood,
his breath failing, and so sweetly departed, being the 14th of the First month, 1704.
Aged twelve years and a half, and two days.
He kept his bed about eighteen days.

[.asterism]
'''

SARAH SOUNDY, wife of William Soundy, of Reading, and daughter of William Tovey,
of Henley-upon-Thames, in Oxfordshire, was trained up in the fear of God,
and when on her deathbed,
she breathed forth in an extraordinary manner praises to the Lord; and said,
"`The Lord is a merciful God.
I find him so to my soul.
He spreads a table for his children, and the dainties he sets thereon,
and his children feed thereat.
He honors me with his presence, and that is favor enough.
As for this world, it is but a bubble.
I would not change my condition for any of yours,`" meaning those then by her bedside,
"`although I might have my health; for I can never be better satisfied to die,
than now I am;`" with many more heavenly expressions,
which she delivered one day after another; which were not noted.
She farther said, "`What have I done that the Lord should be so good to me?
Many have been great sufferers; but I have done nothing;
so that if I have but the least place in the kingdom, I shall be satisfied,
although it be but a door-keeper.`"

She died the 24th of the Twelfth month, 1703, at Ridge,
and was buried in Friends`' burying-ground in Henley-upon-Thames,
the 28th of the Twelfth month, 1703.

[.asterism]
'''

MARY STUBS, daughter of Thomas Stubs, belonging to Pardshaw meeting in Cumberland,
came of believing parents, by whom she was educated in the way of truth,
and reached thereby in her young years, walking circumspectly, as becomes the truth.
She received a public testimony seven years before her death,
and visited friends in Northumberland, some part of Bishopric, Yorkshire,
and Lancashire, and friends generally in the nation of Ireland, and was well received.
When visited with sickness, she was borne up in her spirit;
and when her mother seemed to be troubled and sorry to part with her,
she desired her to be content, for it was her great joy, and farther said,
"`I see nothing that I have to do but die.`"
She also said, "`I am fully clear,`"
and so departed very sensibly the 11th of the Twelfth month, 1704,
in the thirty-third year of her age,
and was buried in Friends`' burying-place at Eaglesfield.

[.asterism]
'''

AMBROSE RIGGE, late of Ryegate, in Surry, was born at Banton, in Westmoreland,
and convinced of the truth about the year 1652.
Being called of God to preach the gospel of peace and salvation,
he was drawn to visit London, and the south and west parts of England,
about the year 1655, enduring great hardships, being often imprisoned in jails,
not for evil-doing, but preaching the truth.
For refusing to swear, in obedience to Christ, who commanded,
"`Swear not at all,`" he was premunired, and made prisoner at Horsham, in Sussex,
above ten years at one time.
He was also whipped, and often evilly entreated and abused,
which he bore with much patience, and continued faithful unto death.
In the time of his sickness, wherein he died,
he had great assurance of the mercy and favor of God, and said,
"`I am going where the weary are at rest.`"
He bore his sickness with much patience; and a little before his departure, he declared,
saying, "`If friends keep to the root of life in themselves,
they would be the happiest people in the world.`"

He departed this life the 30th of the Eleventh month, 1704,
and was buried the 4th of the Twelfth month in Friends`' burying-ground at Ryegate,
in Surry.
Aged above seventy, and a minister about forty-nine years.

[.asterism]
'''

GEORGE FOOKS, late of Gray`'s-Inn-lane, in the parish of Andrew`'s, Holborn,
in the county of Middlesex, shoemaker, was born at Boston, in Cambridgeshire,
in the year 1649, and religiously inclined from his youth.
He was convinced of the blessed truth, as professed by the people called Quakers,
with whom he joined in society about the age of one-and-twenty;
and by believing in Christ the true light,
he came to receive power to walk inoffensively; and though he could not then read,
he afterwards learned to read the Holy Scriptures, and greatly delighted therein.
When he came to have a family, he was careful to have them frequently read therein;
and would direct those of his family to that Holy Spirit in themselves,
which the Scripture testifies of,
that thereby they might come to have an understanding of them,
and find help in themselves to withstand evil, and to be preserved out of it.
He cautioned them also against evil,
and exhorted them to that which was good and well-doing.

He was a man of a tender heart and meek spirit, pitiful to the poor,
and faithful to the Lord,
who was pleased to give him a part in the ministry of the word of life,
about the year 1691, and he travelled some time in the work thereof,
and was serviceable for several years, while he enjoyed his health.

In the year 1704 it pleased the Lord to visit him with sore affliction of body,
which he bore with much patience;
and in the time of his weakness had many visits from his friends and neighbors,
being well beloved by them.
When some came to visit him, and said, "`The Lord comfort you,`" he answered,
"`The Lord is with me, and is my comfort night and day,
and has made my bed easier than I could think.
Although the Lord has been pleased to afflict my body, yet he comforts my soul;
as he has taken away the strength of my limbs,
he has preserved my senses to praise him.`"

Before he died he called his son, and bade him read the 5th, 6th,
and 7th chapters of Matthew, and then observed to him the blessings mentioned therein,
and said to him, "`You have a privilege beyond many poor children,
I would not have you slight it; but read them often,
and desire the Lord to open your understanding in what you read, for it is for our help;
and as you do so, I do believe the Lord will help you, as he did me.
My concern is for your soul`'s good, which is of greater value than your body.`"
Then he added, "`The Lord has blessed my honest endeavors and labors hitherto;
so that you have been fed and clothed with the rest of my children and family,
and I have something to spare.
But the greatest blessing the Lord has blessed me with, is the knowledge of his truth;
and you have often heard me say,
that whatever the Lord should be pleased to bereave me of,
he would be pleased to keep me in the sense of this blessing;
and at this time I have a living sense thereof;
with earnest desires to the Lord it may be so with you.
My dear child, I am going out of this world, and must leave you,
and you will lose a tender father; but as you do mind the Lord, and think upon him,
he will be a father to you, as he was to me.
Be sure you be kind and loving to your mother, and be ruled by her when I am gone;
and remember what I have said to you,
and keep the commandments of the Lord in your lifetime,
and it will be well with you hereafter, and then you will not be afraid to die.
For your sake I could have been willing to stay longer here, but it must not be,
and I am willing to submit to the will of the Lord; for it is well, it is well,
or I would not have told you so.
I am not afraid to die.
Once more I bid you remember your father`'s dying words.`"
He said also to his son,
"`I never kept back the wages of any man that did any thing for me,
nor ever over-reached any man in dealing, nor ever wronged any man one penny.`"

Then desiring to see his daughter, she came.
He said unto her, "`My child, you were my first-born, and the child of my love;
but you have grieved me to the heart, and grieved the Lord,
and many friends that wished you well.
I am now going out of this world, and when my trouble ends, yours may begin.
I do forgive you, and desire the Lord to pass by and forgive you.
I do forgive you, and I hope and believe he will;
but you must be very diligent in seeking and crying to him.
You are now a mother of children; be sure to be a good example to them,
teach them to read the Scriptures, and do you so too;
quit yourself to your husband as a woman fearing God should.
Be loving to your mother, and she will be loving to you and yours I know.
I have seen your condition, and considered it; the Lord bless you, is my earnest desire.
Think upon my dying words when I am gone; they may do you good.
I have been a tender father to you: so hereafter you may say.
Oh! wife, how has been and is my soul ravished with joy.
I cannot express the joy my soul has been in this night.
Oh! wife, it is well; do not be troubled for me, for it is well;
and as we keep close to the Lord it will be well.`"

This is the account which he gave in the time of his sickness;
though he sometimes met with exercises, the Lord was with him, and stood by him,
for he was an honest man, and so lived and died,
and no doubt is at rest in the paradise of God.

He died the 27th of the Eighth month, 1704, aged about fifty-five,
convinced about thirty-four, and a minister about thirteen years.
He was decently and honorably buried, being accompanied by his relations,
and many friends, to their burying-place near Bunhill-fields.

[.asterism]
'''

ANNE TRUSS was born at Reading, where she received the truth,
and suffered imprisonment for her testimony to it.
She was well esteemed, being a woman who loved truth,
and was zealously given up to promote its honor,
and encouraged faithfulness among the professors of it, both by exhortation and example.
She was often concerned in public to speak of the goodness of God, in Christ Jesus,
to mankind, from a sense and taste thereof,
and pressed to diligence in the worship of God, and holiness of life:
and life and power attended her testimony.
She often desired her last sickness might not be long;
and it was indeed but about four days, and in that time she counseled her friends,
neighbors, and grandchildren, who came to see her, and were with her,
to prize their precious time, and to keep out of everything that would offend the Lord,
and said, "`My peace is made with the Lord.`"
She prayed with much sweetness for her grandchildren,
and that the Lord would destroy all that in his people which was contrary to himself.
A few hours before she departed, she said, "`I now hope I shall be at rest.`"

She died the 17th of the First month, 1704.
Aged seventy-six years.

[.asterism]
'''

HUMPHREY WOOLBRIDGE was convinced of truth early, and received a public testimony for it;
he travelled pretty much about England in the service of truth, and wrote several books.
About the year 1705, being at London, he was taken ill,
and continued so some time at Friends`' work-house near Clerkenwell,
being troubled with a great swelling in his face and mouth,
which much deprived him of his speech.
But he wrote several times to Friends, that the Lord was good to him,
and desired Friends to pray for him, saying, "`I see a farther weight of glory,
into which I am not entered.`"
Another time, "`My love in the Lord is to you; my present thought is, to die is my gain,
without doubt; because the love and mercy of God, that casts out fear,
is shed in my heart, to whom I bow my knee, and bless his holy name, his gracious name.`"

In the Fifth month, a little before his death, he wrote to some Friends in London thus:
"`The Lord is my rock, and my salvation and tower, in the time of my distress and anguish.
I cried to the Lord when the billows went over my head,
and the proud waves did afflict my soul.
Then was my faith in God, and underneath was the everlasting arm, my salvation.
So that with David I could say, '`The Lord sits upon the floods,
he reigns as king forever and ever.`'`"

He died the 31st of the Fifth month, 1707.
Aged about seventy-four years.

[.asterism]
'''

WILLIAM HARRIS, of Radford-seemly, in the county of Warwick,
was one who received the Truth in the love of it, in his youthful days,
and being faithful, a part of the gospel ministry was given to him;
in which he labored with zeal and fervency of spirit.
He was very serviceable in doctrine and discipline,
serving truth and Friends in singleness of heart; seeking much the prosperity of truth,
and the love and unity of Friends in it.
He was fervent and frequent in admonition and exhortation
to all people where his lot was cast;
always having a regard to the fear of the Lord unto the last,
and very honorable for his innocent life and upright conduct, wherein he walked,
as a true pattern of virtue; ruling well his own house,
and keeping his family in good order, wherein he was exemplary,
often calling upon them to love and fear the Lord,
and to wait together upon the Lord in his own family.
And with much diligence, and due order to frequent their public meetings,
wherein his love and faithfulness were manifest to the last.

He was taken ill in a meeting which Joseph Bains
had appointed in the public meetinghouse at Harbury,
on the 18th of the Seventh month, 1705, but sat the meeting; and after;
he was well satisfied in the will of the Lord being done, for he was not afraid to die.
Being something better, he went home, and grew weaker: but the Lord enabled him,
on the 23rd of the Seventh month, being First-day,
to go to the meeting of Friends at Harbury,
and publicly declare the word of truth with much fervency, both to Friends and others;
and after meeting hastened home, and grew weaker and weaker in body.
On the 3rd of the Eighth month, a Friend went to visit him, to whom he said,
the night before had been very comfortable to him, for the Lord gave him sweet repose,
so that he felt no pain.
The Lord was so large in his love to him,
that he showed him that the walls of salvation were about him,
and that he would give him an entrance into everlasting life.

On the 6th of the same month he was taken so ill that it
was thought he would scarcely live till morning.
When a Friend came to see him next morning, he was a little revived,
and spoke comfortably to him and those present.
The next day the Friend came again to see him; and when he came into the chamber,
he put forth his hand, and took him by the hand, saying,
"`You are come to see me this once more.
I am now a dying man; I wait to be dissolved; I am weary of this frail body.
When the Lord pleases, I would be freed from it.`"
Several Friends coming to see him, he spoke very sensibly to them;
and when they took their leave, he exhorted them to fear the Lord,
and be faithful in the truth.
A Friend who was related to him, taking his leave of him, seemed to be troubled; he said,
"`Make no ado, neither be troubled, it is the Lord`'s doing.`"
He exhorted his elder servant to fear the Lord,
and charged her to exhort her fellow servant to fear him also, saying,
"`Without it the heart will not be kept clean.`"

A friend said to him, "`You have been a comfort to many,
I hope the Lord will remember you in his mercy,
and be a comfort to you in this your affliction.`"
He answered, "`The Lord is good to my soul.
I can say, I have fought the good fight of faith, I am now finishing my course;
the Lord will give me a crown of life.`"
A little before he departed, he signified his great love to all friends in general,
and said, "`My love is to all my friends and old acquaintance.`"
A friend observing his exercise, said, "`You have hard labor;`" he said,
"`The Lord will visit me in his mercy,
and give me an easy passage in his own time out of this body.`"
And so he did, and he entered into stillness, lay the space of an hour,
and quietly and peaceably departed, as a lamb going into his rest,
about the 12th hour at night, the 7th of the Eighth month, 1705,
aged about seventy years.

[.asterism]
'''

GILBERT LATEY, an ancient professor of the holy truth, was born in the parish of Issey,
in the county of Cornwall, in the year 1626, and came to London in the year 1648.
He was of a sober conduct and religiously inclined,
and followed those that were esteemed the most religious preachers at that time.
About the year 1654, he was,
by the spirit of Christ and the powerful preaching of that eminent servant of the Lord,
Edward Burrough, convinced of the blessed truth,
as it is professed by the people called Quakers,
at a meeting held at the house of Sarah Matthews, in Whitecross-street, London,
in the year 1654.
In the year 1659 he was concerned to bear a public testimony for truth,
and against superfluity; and being by trade a tailor, would not meddle with,
nor allow his servants to put upon apparel, to set it off, any superfluities,
as lace and ribbons.

He was also concerned to solicit, with other friends, the several powers in his time,
for suffering friends, and used to say friends should keep to truth,
or the anointing in their solicitations, and then they might expect a blessing,
and be made serviceable.

And in the year 1705, the seventy-fourth year of his age, being weak,
he said he had done the work of his day faithfully, and was set down in the will of God,
and there was no cloud in his way.
The night before he departed, he gave counsel to those that were in the room,
to fear the Lord, and not to do evil for evil, but to do good for evil; for there is,
said he, no overcoming of evil, but in and by that which is good.
Exhorting much to love and tenderness,
saying the Lord would bless such as were found therein.
A few hours before his departure,
he said that there was no condemnation to them that were in Christ Jesus, "`for,`" said he,
"`he is the lifter up of my head, he is my strength and great salvation.`"

He departed this life the 15th of the Ninth month, 1705,
and was buried in Friends`' burying-ground, at Kingston-upon-Thames.

[.asterism]
'''

WILLIAM STOVEY, late of Helperston Marsh, near Trowbridge, in the county of Wilts,
was born at Aberry in the said county.
He received truth as it is professed by the people called Quakers,
upon its first publication in those parts,
and was a very zealous encourager of faithfulness among Friends.
He also received a gift of the ministry,
and was often very much concerned in his travels,
that truth`'s testimony might be kept up in its several branches,
and particularly against the anti-christian oppression of tithes.
For bearing this testimony, as well as keeping up meetings, he was a great sufferer,
being cast into several prisons, and had his cattle, and other goods,
several times taken from him, even to the bed he lay on,
and almost all that was thought worth removing.
His last sickness was not very great in appearance, nor long;
yet he signified he should never go forth of his chamber, and said,
"`I can and do forgive all my enemies.`"
He was very cheerful in the time of his illness,
and more than ordinarily glad of friends`' company that came to see him,
and said he was satisfied and willing, when the Lord pleased, to leave this world,
in expectation of a far greater happiness in that which is to come.

He departed this life the 7th of the Eleventh month, 1705, and was buried at Cummerell,
in the said county.

[.asterism]
'''

ELIZABETH DICKINSON, widow, was convinced in her husband`'s lifetime;
though her husband was concerned thereat, and she met with great exercise;
yet was made willing to give up, to answer the requirings of truth, and in a little time,
through the grace of God bestowed upon her, being faithful to the Lord,
she was made a publisher of the everlasting gospel of Christ Jesus,
being well near the first, in Abby-holme meeting.
The Lord added to her days, and the number of the church;
that she lived not only to see many gathered to the Lord in her time,
but many also raised to bear a public testimony for him, to the gladdening of her heart,
in the thirty years she lived after she received the truth.
She was of a blameless life and conduct, living answerable to the doctrine of Christ.
She loved the unity of good people,
and hated that which was the cause of the breach thereof.
She was never tedious in her testimony.
She was a mother in Israel, a terror to evil doers,
and bore a faithful testimony against the workers of iniquity.
She ruled well her own house; so that her advice and counsel took place with others.
She was endued by the Lord with meekness and wisdom,
and was freely given up to serve the truth with what she had, and the Lord blessed her.
She visited Friends in Northumberland, Bishopric, Westmoreland, Yorkshire,
and Lancashire, where she had good service for the Lord.
And in the year 1688 she visited Friends in Scotland, and had also good service,
the Lord accompanying her with his heavenly power and presence.

In the time of her sickness, though very sharp, the Lord preserved her in patience,
and she desired friends to remember her in their near approaches to the Lord, and said,
"`Lord, I am willing to die.
You who have made me willing, are able to make me ready.
Look down upon your afflicted handmaid, and lay no more upon me than I am able to bear.`"
She often desired the Lord to be near,
and her last words that can be remembered before she departed, were,
"`You Lord God of Israel,
be near and fasten my spirit;`" which it is not doubted but he was pleased to do,
and received her into rest with the righteous, where no disturbance can come;
but praises everlasting are sung to the Lord God and the Lamb forevermore.

She departed this life the eighth of the Eleventh month, 1705,
in the sixty-sixth year of her age, and was buried at Friends`' burying-place at Allonby,
upon the seacoast in Cumberland, being accompanied with many friends and relations.

[.asterism]
'''

SARAH BLACKHOUSE, of Yeoland-Redman, in the county of Lancaster,
was convinced of the truth,
by receiving the testimony of that eminent messenger and minister of the gospel of Christ,
George Fox, in the year 1653, being in and about the twenty-seventh year of her age.
Within a few years after, it pleased the Lord to concern her in a public testimony,
to the refreshing and edifying of his churches and people,
in which she faithfully labored and travelled in the meetings whereunto she belonged,
and some other adjacent meetings.
She was exemplary in her life and conduct, and preached truth therein to her neighbors,
and those she was concerned with.

A few days before she died, her friends and relations being by her bedside, she said,
"`See that in all your meetings you wait upon the Lord, and be not sleepy.
Be faithful to what he has made known, and revealed to you:
for it need not be said to you, know the Lord; you know enough,
be faithful to what the Lord has revealed, for that is the sum of all religion.`"
A little after she said, "`I am weak, and in much pain, I desire to be eased,
when the Lord`'s pleasure is; through mercy he has given me peace and rest to my soul.`"
She then said, "`Farewell, fare you all well in the Lord,
I desire your growth and prosperity in the truth, every one for yourselves.`"
So in much peace and quietness of mind and spirit,
she departed this life the 30th of the Fifth month, 1706,
being nearly eighty years of age; had a testimony for truth about fifty years.

[.asterism]
'''

JOHN TOMKINS, who collected the three volumes of [.book-title]#Dying Sayings,# formerly printed,
entitled, [.book-title]#Piety Promoted,# was born about the year 1663,
and his honest parents were in society with the people called Quakers.

His father died when he was very young,
after which his mother took care to have him religiously educated,
and the Lord blessed her care,
and was graciously pleased in his tender years to incline him to love and fear him.
He was an obedient son, and assisting to her in her business; and as he grew in years,
continued so.

When his mother married again, she had several more children by her second husband.
And after she died, and her husband was reduced to a very low condition,
this his son-in-law was both tender and charitable,
and had a great care and regard to his children.
As his love and tender compassion began to be early manifested to his relations,
so did his love greatly appear to those who preached the gospel of Christ,
and to the poor and afflicted in body and mind, whom he relieved, visited, and comforted.
He also greatly loved and delighted in the Holy Scriptures,
and diligently read and searched them.
As he grew in years, he grew in grace,
and in the knowledge of our Lord and Savior Jesus Christ; and being faithful to the Lord,
he was pleased to put him into the ministry,
and committed to him the word of reconciliation,
and made him a skillful minister for his time, in the word of life;
so that he could divide it aright.

He was filled with such a holy zeal for the name and truth of God,
as was accompanied with knowledge, and was well acquainted with our Christian discipline,
and careful that it might be maintained,
greatly desiring where any professing truth walked not according to it,
that they might be admonished and reproved;
and that the works and ways of those who would not receive either,
but continued loose and unfaithful, should be testified against,
that friends might be clear, and the church and Zion of God might shine.
He greatly delighted in her prosperity, and travailed for her welfare,
and prayed that the Lord would favor her dust, and satisfy her poor with bread,
and comfort all her mourners.
One asking him how he did, he replied, "`Very weak, but I am willing to die,
and leave this troublesome world, if the Lord sees fit to remove me at this time.`"

Lying on his bed very weak, he declared to friends then present,
very fervently for some time, concerning the work of the Lord,
and the prosperity of his truth in the earth; and in particular,
that the Lord would have a glorious church and people, when all the dross and chaff,
that did yet cleave to them, should be purged out, and blown away.
That the Lord would remove that which had been the
occasion of any disunion among his people,
and bring them more and more into unity, and to be of one heart and mind,
and that the work of the Lord should go forward in the earth,
and his truth prosper over all the kingdoms of it,
and many nations should be gathered to it.
He also said, "`I believe the Lord will bless his people,
and carry on the work he has begun in the earth.
It is my faith,
that the time will come that the wicked shall be as few as the righteous are now;
but there is much to be purged out of the church;
there is much pride and superfluity to be done away.`"
Again he said, "`I have seen great things since my sickness;
things which I think not lawful to be spoken.`"
Much good counsel and advice dropped from him, at sundry times,
that was not taken down in writing,
which he gave at times to his friends and relations about him,
and often said to his wife, "`My dear, grieve not, you must not grieve;
I want to be where the weary are at rest, and where the wicked cease from troubling.
I want to be dissolved, that I may be with the Lord Jesus Christ.
The Lord will provide for you and your children: he has said,
'`Let the widows trust in me, and I will take care of their fatherless children.`'`"

When he was asked if he desired to see his youngest child, he being some miles distant,
he answered, "`He is young, and has little knowledge of me.
I commit him to the great God: he will take care of him.`"
He spoke this with more than ordinary sedateness, adding, "`I am not afraid of death.
I have sought the honor of God in my day, and my reward is with him.
The Lord has been very good to me in this sickness.
I can say with the Psalmist, he has made my bed in my sickness.
I have many sweet seasons from the Lord in the night when I cannot sleep.
Oh!
I enjoy sweet peace from him.
Oh! the love of the Lord Jesus Christ is great to mankind.
The Lord visited me in my tender years, and I have feared him from my childhood.
I have delighted to wipe the shoes of those that preach the gospel, when I was a boy.
Since I have been a man, I have taken more delight in serving the Lord,
his church and people, than in getting worldly riches.
I love the poor, and have loved to serve them, and to visit them in their afflictions.
Remember my love to the poor in the quarter where I dwell.
I love the ministry, I have a valuable esteem for the ministers,
and pray God sanctify and purge them, that they may go before the flock.
I pray God bless the young generation of ministers that are coming up,
and make them skillful in the work, that they may divide the word aright,
that like the Benjamites of old, they may shoot an arrow +++[+++or sling a stone]
to a hair`'s breadth.`"

He died the 12th of the Seventh month, 1706, aged about forty-three years;
and was decently buried from the meetinghouse near Devonshire-square,
accompanied by a great number of friends to Bunhill burying-ground,
and many living testimonies were borne to the truth, in which he lived and died.

He collected and wrote the several books following: [.book-title]#The Harmony of
the Old and New Testament; a Concordance;# [.book-title]#A Trumpet
Sounded;# [.book-title]#The Great Duty of Prayer;# [.book-title]#Piety Promoted,# first, second, and third parts; which are proofs of his zeal for truth, his love to all people,
and that he was well acquainted with the Holy Scriptures.

[.asterism]
'''

ROBERT HUBERSTIE, late of Yelland-Compers, in the county of Lancaster,
was visited with the day-spring from on high,
and brought to the knowledge of God`'s eternal truth,
as professed by the people called Quakers, about the year 1653, which he received, loved,
and obeyed.
He was often a great sufferer by imprisonment for his faithful testimony to the truth,
and by spoiling of his goods for peaceably meeting to worship Almighty God,
in the spirit of his Son, according as he requires,
and bearing his testimony faithfully against that
cruel and anti-christian oppression of tithes.
After his release out of prison, he travelled in the work of the ministry,
the Lord having bestowed a good gift upon him,
and committed to him the word of reconciliation.
He travelled in the power of it for the good of souls,
and visited the churches of Christ, through most parts of this nation,
exhorting and advising friends in the love of God,
to feel the life-giving presence and power of the Lord in all their meetings,
that therein they might be refreshed and strengthened to wait upon God,
and to worship him in his eternal spirit and truth.

Being returned, he was taken sick,
and in the time thereof he had many comfortable expressions, saying,
"`I have peace with God, through Jesus Christ,
and am content in his heavenly will to live or die,
having sought God`'s glory before my own interest in this world.`"
He often advised those present to be faithful to what God had manifested to them,
and to bear a faithful testimony to the truth.
After a sore fit of pain, he said,
"`It is good to have the Lord near at such a pinching time as this,
and to have nothing to do but to die.`"
A few days before he died, he called his son and the rest of his family,
and said he must take his leave of them;
and desired them to live in love and peace one with another,
and to love the truth above all,
and to bear a faithful testimony for God and his truth while on earth,
and the Lord would bless them.
He desired that his love might be remembered to faithful friends,
some of whom he mentioned by name.

He bore his sickness and pain with much patience, and uttered many sweet expressions,
which were not taken.
He was preserved sensible to the last,
having been a believer in the truth about fifty-three years,
and a prisoner near five years; aged about seventy-one years.

He died the 12th, and was buried the 14th of the Eighth month, 1706.
Here follows a Testimony of an ancient friend and acquaintance of R. Huberstie`'s.

[.embedded-content-document.testimony]
--

Since I have had the opportunity of reading the above-written lines,
relating to my dear deceased friend and brother in the nearest
and dearest relation of God`'s blessed truth,
who was convinced thereof in the next year after I was, when we were both young in years;
and remembering the glory of that day of visitation of our souls,
and the comfortable fellowship of the Spirit we have since enjoyed together;
and also Providence so ordering, that my lot fell to see him in his bodily weakness,
and to be comforted in the beholding that sweet contented frame of spirit he lay in,
together with the affecting words that then dropped from him,
I felt some concern upon my mind to add in short, as follows:

That he was a man truly fearing God, faithful to the manifestation of truth,
firm and noble in his testimony and sufferings therefor.
He was
of latter years, an able, zealous, and laborious minister of Christ Jesus,
concerned for good order in the church; serving the Lord faithfully in his day,
and died the death of the righteous.
His latter end was like theirs, namely, full of joy in righteousness,
and assurance of eternal life and glory, as he intimated to me in a divine sense thereof,
a very few days before his departure, saying that he was well in mind,
freely given up to the will of God, and possessed perfect peace,
patiently waiting for his being delivered out of
that pain and trouble of body in God`'s time,
desiring to be remembered to all faithful friends, and desiring me, and one other friend,
to be at his burial.
And the Lord by providence made way, that I therein answered his desire,
it being the day aforesaid, in Friends`' burying-place at Yeland,
where a great appearance of Friends was,
and a great many of the chief and sober neighbors, yes, several that were not invited;
which did demonstrate the good respect he had among all sorts of people.
The Lord was pleased upon that solemn occasion, to bless us with his glorious presence,
and to open the mouths of several of his servants in a living testimony to his truth;
and also to magnify his holy and powerful name for his marvelous salvation,
revealed in and through the Lord Jesus Christ our Savior, to whom, with the Father,
belong dominion, glory, and eternal praise, world without end, Amen.

[.signed-section-signature]
Thomas Camm

[.signed-section-context-close]
Oldworth, 26th of First Month, 1707

--

[.asterism]
'''

JOHN CARLILE, of the city of Carlisle, in the county of Cumberland,
was born at Blackwell, three miles from the city of Carlisle, and was by trade a tanner.
Through the gracious visitation of God,
he was convinced of the blessed truth about the year 1673,
by the ministry of John Graves,
being much reached and confirmed by virtue of the power of truth.
He grew and increased in faithfulness, according to his measure;
and was drawn forth sometimes in a public testimony, and preached the gospel,
not in the eloquence of speech, but very powerful and reaching,
and in simplicity and sincerity.
Although illiterate as to outward learning,
yet in his doctrine and testimony he considerably opened the scriptures of truth,
by the assistance of that holy Spirit that gave them forth,
to the edification of the hearers,
and confirmation of those gospel truths by him preached.
He labored in the work of the ministry in several counties, as Cumberland, Westmoreland,
Bishopric, and part of Lancashire; also in Northumberland, and in Scotland.
Several were convinced by his labors of love in the gospel of Christ in many places,
and remain as seals of his ministry.

He was open-hearted, and zealous for the testimony of truth,
and in much love received the friends of it, who travelled in the same work,
into his house.
As he delighted to draw near to the well-spring of life,
for divine succor and consolation,
he was not unmindful often to wait upon the Lord in his family,
to whom the Lord was pleased to reach, in order to their convincement,
by his blessed truth.
He was sometimes opened to speak a few words to them of information or exhortation;
and sometimes to supplicate the Lord; and other times in silence,
to wait upon the Lord in his family,
to feel an increase and growth in the virtue of truth among them.
Many are witnesses of the benefit and comfort they received in those his family meetings,
that have been at them.
Although at his first convincement in the city,
and when he came to bear testimony to the truth,
he was as a speckled bird among the birds of the wood,
there being none who bore the same profession in the said city,
and was warred against by the bitter magistrates, and severe informers,
and cruel persecutors; yet such was the Lord`'s goodness to him,
that he was preserved faithful in his testimony for the Lord through all.
Some of his persecutors fell into great distress, and died miserably;
and others of them fell into great poverty; so that a prison became their dwelling,
and therein they died.

He was always ready to help forward and encourage every good work on truth`'s account,
and was much given to hospitality, and was open-hearted to the poor of any society.
He was of blameless conduct, just in his dealings, and of a good report among all people,
and valiant for truth and its testimony to the end.
In his sickness he often exhorted Friends to be faithful to the Lord and his truth,
according to their measure; saying, then the Lord would stand by them,
and bring them through all the exercises they might meet with for the same,
and they should have the reward of well done; with more expressions of the like nature.

Having some sight of the glory and joys of heaven,
that those who are faithful and upright-hearted shall enjoy,
and that evidence in himself, of his soul`'s everlasting peace,
he signified his desire of a change,
and that his wife and children might give him freely up, saying it would be well.
Being sensible the time of his departure drew near,
he said to his friends and neighbors present,
that a little time would finish and make all things easy.
In about half an hour he passed away, being the 25th of the Twelfth month, 1706;
and died in the faith of Jesus, and in full unity with Friends,
having borne an innocent testimony for truth in his generation,
and left a good savor behind him.
Aged about seventy-four years.

[.asterism]
'''

JOHN ELLIS was one on whom the Lord bestowed a gift in the ministry,
who labored in the gospel of the grace of God for the good of souls,
and freely preached it in the authority of divine life,
to the reaching God`'s witness in many hearts.

He was zealous for God, and tender of the good in all;
but terrible against the workers of iniquity.
Grave and reverend in the exercise of his gift,
his testimony full of reproof and caution;
but in that meekness which made the same to be edifying.
His doctrine sound,
flowing from the living fountain and divine spring of life and heavenly wisdom.

He was a man of great kindness, loving, meek, and humble;
a visitor of the widows and fatherless in their distress, he sympathized with them;
fed the hungry, clothed the naked, according to his ability,
and labored greatly in Dorsetshire, Hampshire, Wiltshire, and Devonshire,
and other places; often saying, his Father`'s business must not be neglected,
or done negligently.
As he was traveling in the service of truth,
he was taken sick ten miles from his habitation.
He exhorted that every one should keep close to the truth,
that the Lord had made known to them, and said on his deathbed to his wife,
"`It is hid from me,`" speaking of his death, "`but if this is my time, I am ready.
There is nothing to be laid to my charge;
there is a fountain of life that we must all come to, that runs sweetly.`"
His daughter standing by, he gave her a charge,
that she should not mix with any in the world, and that she should not be troubled;
"`for,`" said he, "`I have a sure foundation.`"
He uttered many other sweet expressions, that could not be distinctly understood;
but concluded, saying, "`I salute you all;`" and departed the 31st of the First month,
1707, and was decently interred in Friends`' burying-ground at Poole,
the 4th of the Second month following,
and several testimonies were borne to the truth on that occasion.
