== Chapter 4

[.chapter-synopsis]
* Samuel Watson
* John Boulton
* Margaret Diamon
* John Taylor
* William Ellis
* William Barcraft
* Thomas Barcraft
* Oliver Sansom
* Samuel Wright
* Christopher Richardson
* Elizabeth Haydock
* John Banks

SAMUEL WATSON, of Night Stanford, in Yorkshire, was early convinced of the blessed truth,
as professed by the people called Quakers, and being faithful to the Lord, was,
by his divine power and spirit, fitted for the ministry of the word of life,
and called by the grace of God to preach the gospel of peace,
and to labor in the service of God, for the good of souls, for many years.
The Lord was with him,
and he was kept in a sweet sense and feeling of the life and power of truth to the end;
though in his latter time he had a long season of bodily weakness.
He would very often express,
not only the goodness of God to him since the time of his first convincement,
but also was frequent in giving religious advice to those who visited him, saying,
"`Keep in the pure fear of God, it is as a fountain of life,
and from there all our comforts come.
It is that which makes people honorable, both in their youth and old age!`"

He died at Chester, and was buried there the 24th of the Ninth month, 1708.
Aged about eighty-eight years.

[.asterism]
'''

JOHN BOULTON, late of Gaunt`'s-Ircot, in the parish of Aldmunsbury,
in the county of Gloucester, was a faithful laborer, and true minister of the gospel,
who travelled freely to preach the same, and had eminent service therein,
as many can witness; for a divine power attended his ministry,
and many hearts were tendered, and brought into true contrition,
and to sit under his doctrine with delight, and were greatly comforted, refreshed,
and edified.
He was very serviceable in monthly and quarterly meetings,
and zealous against the anti-christian yoke of tithes,
and esteemed it an honorable testimony; and his faith was,
that none would ever prosper in the truth, who were unfaithful therein.
He was of an innocent life, and exemplary conduct, of a peaceable spirit,
and made it his concern to keep love, unity, and concord,
and frequently exhorted thereunto; and was an elder who deserved double honor,
as a nursing father in the church of Christ, and his memory is sweet and blessed.

In his last illness he often advised friends to be
faithful to what the Lord had make known to them,
while they had their health; and said, "`The Lord is good to me, it is well with me.
The Lord is wonderfully good to me.`"
Again, "`If the Lord`'s will is to take me out of this troublesome world,
I am very well content.
I am in love and peace with all men; all is well.
I shall go but a little before you.
I have made my peace with the Lord; his will be done by me, I am contented,
it is well with me.`"

These words he spoke a little before his death, and growing weak,
he desired the Lord to make his passage out of this life easy.
A Friend then taking leave of him, who was going to the quarterly-meeting, he said,
"`The salutation of my dear love, in the Lord Jesus Christ,
is to all Friends;`" and about an hour after, he said,
"`The Lord has been wonderfully kind to me,
in making my passage easy;`" and a little time after, departed in much quietness,
the 29th of the Ninth month, 1709, and was honorably buried at Hossel,
being accompanied by many Friends and neighbors.
Aged sixty-one years.

[.asterism]
'''

MARGARET DIAMON, wife of Richard Diamon, of London, merchant,
was daughter of captain John Groves, late of the parish of Bermondsey, in Surry, mariner,
deceased, and religiously educated by her parents in the Christian religion,
among the people called Quakers, in which she continued to her end.
In the latter part of her time she was visited with much sickness, and great pain;
yet retained her love to the Lord, his truth, and faithful people,
and her faith and hope in God, as appeared by what she declared.
She said to her husband one morning, "`Oh, my dear!
I have had a very wearisome night, and no rest; I have been in a bewildered state;
but the Lord I believe will satisfy my poor soul, it is that I now wait for.`"
After this she desired her husband to call all their children, which was done; to whom,
when come, she said, "`Be careful to keep near the Lord, and in plainness;
that it may not be said to you, '`If your mother was alive,
she would not allow you to take this liberty.`'`"

When she had given them this charge, and tender advice on her dying-bed,
worthy to be remembered, and duly observed,
she desired her husband to send to her relations, which he did.
When they came, she in much love spoke to them; and,
although the words were not noted down, it is hoped they will be remembered by them,
and her dying counsel taken; which, when she had given, she,
in much sweetness took her leave of them.
And after, said to her husband, "`The Lord has been very good to us,
I desire we may walk worthy; for a little time will finish here,
and I am contented in the Lord`'s will, and hope we shall meet together in heaven,
my dear and tender husband.`"

Another time she said, "`The Lord has often comforted me,
and made my bed a bed of ease to me;`" and then added,
"`I have been wrapped up too much in outward enjoyments, now I am out of them.
I have desired the Lord to search me thoroughly,
that nothing may remain in me that is displeasing to him.
My great care and desire to the Lord has been, that I may hold out to the end.`"
Her husband answered, "`The Lord hears your unfeigned prayers;`" she replied,
"`If Daniel and Moses stood by me, and said it would be well with me,
it would avail nothing, unless I have the witness in myself;`" adding,
"`He that has been my support to this day,
I do hope and believe will be with me to the end;`" and then lay still.
Afterward she said, "`Lord, I beseech you, shorten this great work for your mercy`'s sake,
for your dear Son my mediator`'s sake, if it be your blessed will,
and support me through the valley of the shadow of death, that my faith fail not;
but that an eye of faith may be kept open to look to you.
Lord, you that command the winds and the raging waves of the sea to be still,
and they obey you, are able to make this sick-bed a bed of ease.
Lord, be with me, I beseech you; and then no matter what becomes of this body,
nor what I go through, for there will be an end to that.
Lord, be with me this night, I beseech you, for I am a poor, weak creature; therefore,
O Lord, I beseech you, support me, receive me into your merciful arms,
and lead me into the bride-chamber, where I may forever rest with you.`"

Then she took her husband by the hand,
and earnestly entreated his heart might be to the Lord, and said,
"`Leave off the cares of this life, and seek the Lord above all.`"
Requesting all might be still, she lay down in a sweet state,
desiring to be kept humble at Christ`'s feet.

The day before she was taken speechless,
she told her husband her speech would be taken away, saying, "`For it is the twelfth hour,
and the midnight cry, that the bridegroom is come;`" and said, "`I am satisfied,
my lamp is ready trimmed;`" and farther said, "`Oh!
Jacob`'s God, and Israel`'s king, you are able to do all things,
nothing is too hard for you.
Lord, grant that my passage may be quick and short,
and rather that my tongue may cleave to the roof of my mouth,
than I should speak one word to dishonor you, Lord.
Lord, you know what a night of sorrow and exercise this has been to me;
but you are able to do all things, for if you speak the word, it is done.`"
Then she said to her husband, "`Oh! have your heart to the Lord for me,
and speak to them you know to be honest, good Friends,
to have their hearts to the Lord for me.`"
She then spoke her last words: "`Lord, Lord, Lord, you are Jacob`'s God, and Israel`'s king;
you are a shadow of a mighty rock in a weary land;`" adding, "`Oh!
Zion, Zion, the city of saints`' solemnity, beauty, the beauty of holiness.`"
Then spoke no more, and died some time after, in peace with God, it is not doubted,
and is in his paradise.
She was a virtuous woman, a good wife, a tender mother, and charitable.

She was born the 16th of the Twelfth month, 1658, and died the 1st of the Tenth month,
1708, aged about fifty years;
and was decently buried from the meetinghouse at Horslydown,
and her corpse accompanied to the burying-ground belonging to the same,
by her relations and Friends, who loved her, and lamented the loss of her.

[.asterism]
'''

JOHN TAYLOR was born at Sillath, in Abbey-holme, in the county of Cumberland,
in the year 1654, of honest parents,
who educated him with the foremost in that part where he lived.

In the year 1674, the twentieth of his age, he was convinced of the blessed truth,
by the testimony of John Graves, and gladly received the same in the love of it,
and so continued with the people of God,
waiting upon the Lord in silence the space of three years.
Then it pleased the Lord to open his mouth to bear a testimony to the blessed truth,
in which he was very serviceable, both among friends and others at home,
and abroad in Scotland also, where he travelled three or four times;
and had good service in many parts of this nation.
He bore a faithful testimony for the Lord; was sound in doctrine,
and of a good understanding in discipline,
whereby he became very serviceable in monthly and quarterly meetings.
He was a sincere-hearted man, and his deportment and behavior such,
that he had an influence upon all sorts of people,
for his good deportment and meek and quiet spirit.
He met with many trials of various sorts,
and yet was preserved in a meek and even temper,
and he suffered much upon the account of tithes, which he bore with great patience,
and was never known to murmur.

In the year 1708, in the Fourth month, he was visited with sickness,
and then he gave good advice to many who came to see him, both Friends and others.
Being restored to a measure of health, he visited Friends in Yorkshire,
where he had good service for the Lord, and returned in great peace.
About a month after he was taken with the sickness, of which he died;
and in the time of his sickness he was preserved in a sweet frame of spirit,
and had the evidence that he should have a mansion in the Lord`'s house, saying,
"`I feel the spirit of the Lord coming down upon me,
to change me from mortality to immortality;`" and
desired the Lord would make his passage easy,
and he had his desire.
Aged about fifty-four, convinced thirty-four, a minister about thirty-one years.
He died the 8th of the first month, 1709, and was buried at Abbey-holme,
his corpse being accompanied by many friends and others.

[.asterism]
'''

WILLIAM ELLIS, of Airton, in Yorkshire, was born the 5th of the Eighth month, 1658,
and convinced of the living and powerful truth in the Third month, 1676.
Being called and qualified by the Lord to be a minister of the gospel of peace and salvation,
he was faithful to his call,
and labored and travelled in the work of the ministry in England, and Ireland,
also in Maryland, Virginia, Carolina, Pennsylvania, New England,
and other parts of America.
A few days before his departure, he said, speaking of his convincement,
"`It was a glorious day to him.
And he had large tokens, that the day of his death would be so likewise.`"
Many sweet and edifying expressions dropped from him, in cheerfulness of mind,
which showed how ready he was to embrace death.

He died on the 4th of the Fourth month, 1709.
Aged nearly fifty-one years.
Convinced of truth about thirty-three years.
He was buried at Friends`' burying-ground, at Airton, and a large meeting there was,
which was eminently attended with the presence of the Lord,
and several living testimonies were there borne,
to the comfort and satisfaction of many.

[.asterism]
'''

WILLIAM BARCRAFT, late of Bally-Britton, in King`'s County, in the kingdom of Ireland,
aged twenty-eight years, before his departure, was taken speechless in a violent fit,
but his speech returning again,
he expressed himself thus to his dear wife and mother-in-law, and friends present,
(being in a heavenly frame of mind,
and his pain seeming to them to be taken away,) "`I am exceedingly glad to see you.
The Lord`'s love and mercy is exceedingly great, and this is beyond my expectation,
that I have mercy of the Lord to speak to you.
The presence of the Lord at such a time as this, makes afflictions easy to his people,
and it is an advantage friends have in feeling and enjoying the presence of the Lord.
I am easy to leave this world, in hopes of a glorious time to come,
in the kingdom of eternal peace.`"

He then desired his mother-in-law to remember his dear love to his father, brother,
sister, relations, and friends, and that as they had bestowed their daughter on him,
now he would bestow, or commend her, and his children to the Lord,
and her tender parents; "`And to my uncle,`" said he,
"`whom I am sure has been tender of me.`"
Then desiring his wife several times, to give him freely up to the Lord,
that he might be easy, he said, "`Who knows, but there may be a service in my going now.
I desire you, (i. e. his wife,) bring up my children in the fear of the Lord,
and in plainness of habit and speech, and in lowliness,
and whether they have little or much, it will be well enough.`"
He further said to her, "`Trust in the Lord, and keep near to Friends,
and it will be well with you.`"
His wife being in a tender or melted frame of heart, said, "`I do trust in the Lord,
and give you up to him;`" which seemed to give him much satisfaction.

He called his brother-in-law James to him, and warned him to be of a savory life,
and to love the fear of the Lord, and to be careful to keep out of pride and height,
and out of bad company; and added, "`Be sure to walk low and humble,
and be obedient to your parents;
for I never knew any disobedient to their parents do well.
Be sure to tell your brother Joseph to walk low and humble;
and if ever he expects joy and comfort, to be obedient to his mother;
for when I at any time grieved my mother, I was always troubled and sorry for it.
And advise your sister Martha, to have a care of that high city,
(i. e. Dublin,) and be sure to keep low and humble;`" saying,
"`there was great danger in that city, for youth to be led away from the Lord;
but if they served the Lord carefully, it would be well with them.`"

He desired a friend who was present, to tell his brother Thomas,
to be of a sober life and conduct among people,
and to be a good example in the place where he lived,
and in whatever he did he should have an eye to the Lord, and not to be high-minded,
but low and humble.
He said, "`From a child I always loved the company of good honest friends,
for which I was always the better.
Though I have had weary nights and days; yet through all,
I had an eye to the Lord;`" adding,
"`It is a brave thing to have nothing to do but to die.`"
To his wife, he said, "`My dear, comfort yourself, in that it will be well with me.`"
And to his friends that stood by, "`How many precious heavenly meetings have we had;
but it has been a great trouble to me, to see how dull and sleepy some have been,
and others unconcerned, both old and young, in such a glorious day as this is,
where the Lord has appeared so eminently among us.
Many times of late, I thought I saw a more glorious day approaching than ever.
Oh! is not this (speaking of the opportunity he had
with his friends) a precious comfortable thing,
to have this sweet opportunity: this is what my heart desired.
I care not how many young people were here, I should be glad if all the meeting,
and several others were here;`" adding,
"`I wish all the high and lofty ones would look back, and see what they were.`"

All which being spoken in a good sense of the Lord`'s heavenly presence,
did mightily tender Friends`' hearts who stood by,
and ended in prayer and thanksgiving to him who lives forever and ever, Amen.
He gave good ground of hope, that the Lord showed him mercy,
and called him to glory and peace forever.
And when he took leave of friends, he said,
"`I am very easy;`" and departed the 5th of the Sixth month, 1709.

[.asterism]
'''

THOMAS BARCRAFT, brother to the aforesaid William Barcraft,
was taken ill of the same distemper upon the 15th of the Eleventh month following.
His uncle and aunt Barcraft sitting by him,
and perceiving him to be under exercise of mind for peace with the Lord,
his uncle inquired of him as to his condition, and he answered as follows:
"`Sometimes I think I shall recover, and other times I think I shall not.
But my desire is, if I recover, to improve my time.
I find most ease in submitting myself to the will of God.
I never wronged any body knowingly, nor acted any gross thing;
but that which is my great trouble, is,
that I did not live so savory a life and conduct as I should have done;
but gave way to lightness that was hurtful to me, of which, if I live,
I hope to warn others.`"
He said to his uncle and aunt,
"`Whenever you reproved me for such things I was always glad of it,
but did not take the notice of it that I now see I ought to have done.
That which seemed but little to me then, now seems a great deal; but if I should live,
and not improve my time, it is best for me to go now,
for I am in hopes there is mercy for me.`"

He departed this life the 18th of the Eleventh month, 1709,
so that he lay sick but three days.
Therefore it is needful for all to improve the present time; fear God, and live soberly,
and to have their conducts coupled therewith, and to take heed to reproof;
not give way to lightness, nor esteem that a little thing;
for it behooves young men and women, and all, to be sober,
and gird up the loins of their minds, and hope to the end.

[.asterism]
'''

OLIVER SANSOM, late of Abingdon, formerly of Farrington, in Berkshire,
was convinced of the blessed truth of God in the year 1657,
received it in the love thereof, and was faithful to it.
The Lord having fitted him for his service, and endued him with wisdom, understanding,
and sound judgment, was pleased to call him into the ministry,
to preach and labor in the gospel of Christ and love of God for the good of souls;
which he did freely in this nation and Ireland, and was a valiant sufferer for the truth,
and the testimony thereof, against all swearing and tithes,
and what the Lord raised him up in his power to testify against.
When on his deathbed, a friend came in love to see him, who said,
"`We who are young in years shall greatly miss your
company among us;`" to which Oliver Sansom replied,
"`By reason of my age, it is not likely I shall continue long with you; but be faithful,
as I have been, and you will have the same reward as I am likely to have.
Be followers of Christ, as you have had me for an example,
for I have been true to what the Lord has committed to my charge.`"

He was released, and taken from all his troubles and exercises here below,
and received by the Lord into his paradise the 23rd of the Second month, 1710,
and his body was honorably buried at Abingdon.
Aged about seventy-four years.

[.asterism]
'''

SAMUEL WRIGHT, of Welllinborough, in Northamptonshire,
a faithful and honest man whom the Lord called, qualified, commissioned,
and sent freely forth to preach the gospel of life and salvation by Jesus Christ,
was greatly beloved and very serviceable in the country where he lived,
and adorned the doctrine of God our Savior, by a conduct becoming the gospel,
and was of a good repute among his neighbors.

Being visited by the Lord with bodily weakness, and being at a time somewhat better,
he was below stairs, but after a while he went up,
when his wife asked him if he was not spent; he said, "`I feel so much comfort,
and so much of the goodness of the Lord,
I am come up that you may partake of the same with
me;`" and she said she in some measure did,
though under exercise, because of his weakness.
He said to her often, "`Do not trouble and grieve for me,
for the Lord may raise me up still, if he sees it best; if not, be contented,
and put your trust in the Lord; he can make hard things easy.
Is it not better to part from your husband in this condition,
wherein you are satisfied it will be well with him, than if not?`"
His wife replied, "`It will be well with you I am well satisfied,
and that is the greatest comfort I have in parting from you.
But still my loss is the greater, to part with such a good husband, with whom,
if the Lord saw good, it might be as well another time, or some years from now.`"
He answered, "`It must not be another time; the Lord`'s time is the best time.
I should be glad to see you in a mind to submit to the will of the Lord in all things;
for it troubles me to see you so sorrowful.
It will not be your case alone, although I know it will be hard for you to bear.
I would not have you cast yourself down, for then you will not be able to look after me,
and I shall like no body so well.`"

Another time some neighbors came to see him, with whom was a great professor.
They asked him how he was; he answered he was troubled with pain of body,
and sick besides.
They replied, he had been sick a long time.
He said he never thought the time long or tedious, he had so much of the
enjoyment of the presence of the Lord, and felt so much comfort,
that he never thought the time long, nor his afflictions tedious,
saying he was as sensible as in a time of health, and his faith the same as it had been;
and his mind was stayed upon the Lord, and his life was in his hand.
He farther said he had not his work to do;
declaring largely his great satisfaction how happy he should be in the world to come,
saying he had a taste and earnest of it.

Another time, a Friend, with several others, visiting him,
he was much concerned to exhort Friends to love one another,
and to strengthen one another, saying, "`It is well known what labor of love,
and travail of spirit, I have had among you for the service of truth.`"
He expressed the great love of God to his soul, saying, "`What can I desire more;
I am fully satisfied eternal life will be my portion; and the comfort that I feel,
outbalances my pain.`"
He returned praises to the Lord, and was freely resigned up to his will,
saying there were but two things for which he could desire to live, and they were,
for the sake of his family, and upon the service of truth.
He then desired his dear wife not to be too much grieved,
but to be freely resigned to the will of God, saying,
if she had her eye to the Lord he would bless her.
And said farther, "`The Lord who has been and is, my comfort, will be your comfort,
and that is my consolation, and will be your consolation,
for you had not your eye to beauty; you had not your eye to riches;
but your choice was for one that feared the Lord.
Therefore I do believe the Lord had a blessing for you.`"

Being concerned for his dear wife, he added, "`Seeing the Lord provided a husband for you,
according to your desire, can not you say with Job, '`The Lord gives,
and the Lord takes away, blessed be the name of the Lord.`'
Remember what Job said to his wife, '`Shall we receive good at the hand of God,
and shall we not receive evil?`'
For, although the Lord gave you a husband according to your desire,
you are not willing to give him up into his hands; for it would be better for you,
and easier for me.`"
She answered, "`It is too hard for me to do at present;
but the Lord can make hard things easy, if I could put my trust in him.`"
Then he said, "`Remember how it was with Jephtha, who had but one only daughter,
and when he had made a vow, that if the Lord would give him victory over his enemies,
whatsoever came first forth out of his house to meet him, should surely be the Lord`'s;
and the first that came was his daughter;`"
so he bid her remember the nobility of the damsel; "`when her father wept to see her,
she said, '`Father, if you have opened your mouth unto the Lord,
do to me according to that which proceeded out of your mouth.`' And she gave up herself,
and can not you give me up?`"

Another time some came to see him, to whom he declared he had great satisfaction to die,
saying, "`I feel the Lord to be with me, and what would the great men of the earth give,
to feel the same peace with God, when they come to lie upon a dying-bed.`"
He uttered many more sweet exhortations to his wife and friends,
to the tendering and affecting of the hearts of those there present; saying,
"`If I find myself weaker in body,
I should be glad to have Friends in general come and see me, to wait upon God together.`"

Another time he said, "`In all the afflictions I ever met with,
my mind was never so stayed as in this,
my mind being so much out of the encumbering things of this world,
that I do believe this affliction will be for my good;`" with much more.

Another time he said he did not know but death might come of a sudden,
but it would be no surprisal to him.
"`I am both ready and willing to die;`" or if it should please the Lord to restore him,
he could be willing to live, for the sake of his family,
or that he might be serviceable in the gospel, for the promotion of truth; but said,
"`I have such satisfaction and full assurance of my future being,
that my heart is often overcome with joy;`" with much more.

At another time he said, "`Lord, you visited me in my youth,
when I was but young in years, and I was given up to serve you; as was stripling David,
when he went to battle against the uncircumcised Philistine;
for he went in the name of the Lord.`"
He also spoke concerning the brazen serpent, how the wounded were to look thereto;
and of Joseph`'s being a fruitful bough by a well, whose branches run over the wall;
saying, the archers shot at him, but the bow of faith was too strong for them.
Also he said, "`It will be well with me when I am gone to another world,
though I have not death very much in my view.
I have been as though I was at the brink of the grave,
but the Lord has been pleased to spare me a little longer.`"

Another time, friends coming to see him after a meeting, one said to him,
"`You have had a long time of illness;`" he replied, "`I do not think the time long,
by reason I have felt so much of the goodness of the Lord to me.`"
He testified, saying, "`According to my strength, great has been my labor,
and travail in spirit, for the prosperity of Zion, and the welfare of Jerusalem,
since I was exercised with affliction;`" and so bowed down, and went to prayer.

Another time he said to several friends, "`I see the wonders of the Lord in the deep,
and what I now enjoy of the goodness of God, is beyond what I can express.
The Lord has been always with me in my afflictions,
and is still with me;`" with many more sweet expressions, that are not noted.

One asking him at another time how he did, he said, "`I am poorly,
but I think I shall not die at present or suddenly, but I have not my work to do.`"
At another time, about an hour before his departure, being restless as he lay in bed,
his mother said, "`My poor dear child;`" to which he answered,
"`I am rich;`" and so he departed this life, the 29th day of the Third month, 1710.
He was buried in Friends`' burying-ground,
and was accompanied there by many friends and others,
and several good testimonies were then borne unto the truth.

[.asterism]
'''

CHRISTOPHER RICHARDSON, late of Burton, in Yorkshire, was born at Caperby,
in the same county, of honest parents, and was religiously educated.

In the time of his weakness of body, which increased so much upon him,
that his recovery was somewhat questioned, his wife speaking to him,
asked him how it was with him?
He answered,
"`It is no light matter to be concerned about our soul`'s salvation;`" but said,
"`I feel hopes to spring.`"
Then taking his wife by the hand, he said, "`My dear,
you have been a loving and obedient wife to me.
I desire you to keep in
patience, the Lord will be a husband to you, and he will provide for you,
he did take care for you before you had a husband.
So he that thus helped you through many troubles
and deep exercises is the same that ever he was;
he will be strength to you in time of weakness.
It was the Lord`'s providence that brought us together;
and he has many times honored us with his presence;
but whether we be separated now or not, the Lord`'s will be done,
for we have had a comfortable time together,
and I desire we may have a comfortable parting, and things may be made easy to you.`"

Then he spoke to his father, and said, "`This I have to say to you,
you have been dear and tender over me, and much concerned about me,
and your care has been to bring me up in truth`'s way;
the Lord will reward you for it in another world.`"

His father replied, "`Child, this I have to say for you,
you have been a dutiful child to me.`"
Then his son said to him again, "`Remember my dear love +++[+++or duty]
to my tender mother, and desire her to keep in patience.`"

Then to his brother John, he said, "`Keep in the fear of the Lord,
let it be always before you, and it will learn you true wisdom.
Love the teachings of the Lord Jesus Christ,
and that which inwardly does check and reprove for evil; hearken to that inward voice,
which tells you when you are turning to the right hand, or to the left;
for they that disobey the teachings of it, and will have none of its reproofs,
a day of desolation will overtake them, before they be aware,
and such will be ruined forever.`"
Then taking a brother of his by the hand, he said, "`Farewell,
I do wish your eternal welfare,
and desire you to be faithful to what God has made known to you.
I believe you know enough, give up to the manifestation of the spirit of truth,
and bring your children up in the nurture of it.`"
The brother answered, "`We can do nothing of ourselves,
without God Almighty`'s assistance;`" his reply was,
"`God has extended a measure of his grace to every one to profit withal;
so there will be no pleading of excuse.
I desire you to have a care of giving way to that
which will draw your mind away from the Lord,
for if you do, you will be undone forever, as sure as I hold you by the hand.`"

He also declared he was willing to leave the world, and all that might be enjoyed in it,
if it should please the Lord to take him away at that time,
that he might leave a good savor behind him; signifying the troubles that are here,
and the peace that is with the Lord, and his satisfaction he had in his own particular.
One who was by, said, "`It is well it is so with you;
I am glad to hear such expressions from you.`"
He then said to them about him, "`There are many, when they are brought low in sickness,
begin to consider how they have spent their time, and see their lamps untrimmed,
and lack oil, like the foolish virgins, that are ready to say,
Oh! that it would please the Lord to lengthen their days, so as to raise them up again;
then they would be better prepared for their final change.`"
Then he said, "`I see a portion in the kingdom of heaven,
a place among the sanctified is better than a thousand worlds.
So,`" said he, "`let not the things of this world hinder you; for the cares of this life,
and cumbering things, do but beget bondage.`"

Then he said, "`My dear love to all my brothers and sisters.
I desire they may be careful to bring up their children in the nurture of truth.`"
Adding, "`Tell my sister Jane from me, that she be not unmindful of her first love;
but that she bow to truth, and stand in the dominion of it, and learn humility,
and prize truth above all.`"
He then remembered his love to some particular friends; and added,
"`My love is to all faithful Friends.`"
His wife asking him how it was with him, he said, "`I am very easy,
the Lord`'s will be done:`" then he ceased to speak any more for a while,
till about three or four hours before he departed; and then he said,
though with a very low voice,
"`Seek Christ Jesus our Savior;`" these were the last words those present could remember.

He was patient in his sickness, and freely resigned to the will of the Lord,
and concerned in love to give advice, as aforesaid,
and declare his sense and experience of the Lord`'s goodness, and salvation by him;
and no doubt is entered into that which,
as he declared to his wife in the early part of his sickness,
is better than outward rest, the paradise of God,
or holy kingdom of eternal life and glory, where his soul will rest in peace forever.

He departed this life the 7th of the Sixth month, 1706, and was buried the 9th,
at Caperby, in Friends`' burying-ground;
being accompanied there by many Friends and neighbors.

[.asterism]
'''

ELIZABETH HAYDOCK, daughter of Henry and Martha Haydock, was born at Warrington,
in Lancashire, the 17th of the Sixth month, 1686.
Her father died before she was two years old,
and she was educated among the people of God called Quakers, by her mother,
and was loving and obedient to her till death,
and lived in love and peace with her brother and sister,
and was very affectionate to them, never being known to jar or contend with them.
She was of a kind and courteous behavior to all, by which she gained abundance of love,
both with great and small.
Some time before her death, she labored with her mother,
for her consent that she might go and live with some honest Friend,
to which her mother at last complied, and she went to her beloved uncle, Robert Haydock.
But in a short time, being taken ill, she returned to her mother,
and soon after she came home, said, "`I fully believe I must not recover,
and I am content in the will of God.`"

Her sickness continuing, her mother,
brother and sister were desirous a doctor might be had, which was proposed to her,
and she said, "`To make you easy, I am willing, but I believe he will do me no good,
for I must not recover, I believe.`"
Her mother seeing she grew very weak, asked her how things were with her,
as to her future state in the world to come; she, after some due deliberation, said,
"`My dear mother, I am no ways afraid to die, for things are now well.
I have a very easy mind upon all accounts, and towards every body.
I find nothing stands in my way but you, my tender mother.
I fear it will be hard for you; but be easy, for I am well; and if I live to old age,
I can but be well.
I am given up to die, or to live, as the Lord pleases, since I came to you;
but before I came, I had a hard time.
The enemy would needs have persuaded me that there was little hope for me,
and that I should not find peace, under which I wept, and labored,
none knowing my sorrow I was in, neither did I make it known to any till now.
But I bless God I am now satisfied, and free from any fear, and believe all will be well,
and I shall go to rest; for, dear mother, I see nothing but trouble in the world,
and I do not desire to live in it; we must leave it.`"

Though her weakness continued, and her pain was sharp, she was preserved still and quiet,
and in abundance of patience, and was not heard to murmur in the least, but said,
"`Lord afflict me how you please,
so you will but be pleased to give me patience and an easy passage at last.`"
Then she lay still some time, and after said to her mother,
being then under a deep travail of spirit, because of her sore affliction,
"`Let us pray to the Lord.`"
Soon after, her mother knelt down, and prayed to the Lord for her,
and freely resigned her up to him, that his will might be done in and with her;
after which she was pretty easy in herself, and said, "`Oh! dear mother,
I once thought I never should have come to that experience I now have.
I now know a stay to my mind, and silence to my own thoughts.
I am at times quit of all thoughts of the things of this world.`"
Her mother being weeping by her, she said, "`Weep not, my tender mother,
it is better for me to die, than to live;`" her mother said,
"`If it be the will of the Lord,
I desire none of mine might die of such a lingering distemper, as now you are under,
your pain is so great.`"
She replied, "`Do not desire so, for it is sad for youth to be quickly snapped away,
and not have time to remember their latter end; it has been good to me.`"

About two weeks before she died, she took her bed,
for the most of which time she uttered many sweet and sensible expressions.
One time her mother withdrew from her into another room, yet in her hearing,
and heard her say unto the Lord, "`All might,
power and glory is with you;`" and continued pouring forth her spirit unto God, saying,
"`Lord, I am ready.
Oh! tarry not sweet Lord.
Oh! deliverance, deliverance, I cry to you for.
Oh!
God, deliver my soul.
I feel nothing to hinder; but, oh!
Lord, if any thing be in my way remove it, oh! my God.`"
Afterward said to her mother, "`I fear you hold me, oh! do not so; neither weep for me,
for my tears are dried up.
I feel no cause for any; neither mourn for me, for I shall go to rest.
I had rather be with Almighty God, than enjoy all this world, it is nothing to me.`"

At another time, when her mother and relations thought her near going,
recovering a little strength, she kissed her mother, father, brother, and sisters,
and said, "`Lord Jesus, receive my spirit.
I am ready, tarry not, but deliver me out of my pain.`"
Her mother said, "`The Lord is supplicated for you, and your deliverance draws near,
I do believe, and your time will not be long; my spirit is earnest with yours,
that he may ease you; but it is the Lord, he must do what he pleases; breathe you to him,
my dear child, for patience.`"
She replied, "`Poor Job had it, and the Lord has given it me all along,
and I hope he will give it me still.`"

She desired that her ever dear friend, Benjamin Bangs, might be sent for; and he was,
and came.
After he had been some time with her, she fixed her eyes upon him steadfastly, and said,
"`My pain is very great, pray you to the Lord for me;`" and was very still a while,
in which time the spirit of prayer from God came upon him,
and he prayed both powerfully and with much fervency of spirit to the Almighty for her,
that it might please him to ease her of her pain.
And the Lord was entreated for her, and in a little time her pain was wholly taken away;
and she said, "`I bless the Lord, I am easy, both in body and mind.
I have nothing to do, but wait the Lord`'s time.`"

That night she had some rest, and lay very still, and free from pain;
and in the night said to her mother, "`My dear love is with you.
I love you above all the world; and my love to all my dear relations,
I shall see them no more, and to my weak aunt at Penketh,
who was kind to me when I was there.`"
Next day she said to her mother, with a cheerful countenance, "`Dear mother,
I have now done, four or twelve of the clock, I think I shall not pass that time.
Be easy and content, or else your time will be but short.
There is nothing in all this world has been so dear to me as you;
but I hope you can not desire my stay.`"
Her mother asked her if she was sensible of her coldness; she replied, "`Yes,
and of my sweating too, and if it is death`'s sweat, it is welcome to me.
Let it be so to you, dear mother.
The Lord Jesus is my Savior, I can embrace death with open arms, it is welcome,
I fear nothing.
I have sometimes heard you, and some other Friends say in meetings, that the dead,
though ever so lovely when alive, were in no way pleasant to the living, when dead.
I am partly dead, and must be buried out of your sight.
The Lord be with our spirits, and bless you all.`"
She went away like a lamb, innocently, the 8th of the Sixth month, 1710,
and was buried the 13th of the same,
being attended to her grave by many Friends and others.
Aged eight days short of twenty-four years.

[.asterism]
'''

JOHN BANKS was born in the year 1637, in Sunderland, in the parish of Issell,
in the county of Cumberland, of honest parents, his father a fell-monger and glove-maker.
At sixteen years of age, he was, by the great power and pure spirit of God,
and the revelation thereof, in and through the Lord Jesus Christ, in his heart,
brought to the knowledge of God, and the way of his blessed truth,
before ever he heard any one called Quaker preach;
and in himself was directed to go to the meeting of the said people, it being shown him,
and signified to him they were the Lord`'s people.
So he went the next first day to a meeting of the aforesaid people at Pardshaw,
where very few words were spoken; but a paper was therein read,
which was suitable to his condition;
and through waiting diligently in the light of Christ, and keeping to the power of God,
he came to experience the work thereof, and freedom from bondage,
through faithfulness to the Lord.

In the year 1663, being qualified by the Lord,
he was drawn in his spirit to visit some neighboring counties,
and labored in the work of the ministry.

In the year 1668, being farther grown in the truth, he was made willing to forsake all,
to answer the Lord`'s requirings,
and he travelled into the south and west of England in the Lord`'s service.
After that, from year to year he labored zealously to preach the gospel of peace,
not only in England, but Scotland and Ireland; he crossed the sea twelve times,
and often with great difficulty and danger of life by sea, in great tempests and storms,
and by robbers on land.
He was made instrumental to turn many by his zealous labors in the gospel of God,
to righteousness, who remain witnesses of the same, and seals of his ministry.
He had much suffering by loss of goods, imprisonment, and hardships therein;
which he was enabled to go through, for the Lord was with him, and supported him,
and blessed his labors; so that many, both men and women,
were convinced and confirmed in the truth by him, and became faithful and able ministers,
and so continued until death, and others yet remain.

In the year 1696 he married his second wife at Glastonbury in Somersetshire,
settled at Mear, until about two years before his death he removed to Street,
in the said county.
He likewise was concerned, in the love of God, a month or two before his death,
notwithstanding his age and weakness, to visit Friends at several of their meetings,
and had comfortable seasons with them, both at their meetings of public worship,
and at their monthly meetings,
held to take care of the poor and fatherless children and widows;
for he was zealous for good order and Christian discipline in the church,
and that those things that were honest, just, pure, and of good report,
and that had any praise in them, should be followed.
Indeed, it was admirable to those who knew him, and the weak condition he was in,
how in his last journey at Somerton, he was in the meeting, which was very large,
enabled to preach nearly an hour and a half, and bore a sound testimony to truth,
and against outside shows, that lacked substance, with much presence of mind,
and with good distinction in his doctrine; the which gave demonstration,
not only of the strength of his memory and quick understanding,
but sound judgment in things spiritual.
His preaching was comfortable, refreshing, and edifying to the meeting;
and he earnestly pressed Friends to be faithful to the small appearance of truth,
encouraging such as were weak, on whom Amalek chooses to vent his malice,
to a holy zeal.

After meeting, it was sufficient task for two men to lead him to his quarters,
though he was very cheerful,
and signified his great satisfaction in his service and travail,
and next went to Friends`' meeting at Puddimore, and after to a meeting at Yeovill,
where many Friends were.
In his public service there,
he was very lively and quick in discerning the states of several,
and afterward returned home, where, in the Seventh month, 1710,
he was taken with great pain in his back; yet he often said, "`Though my pain is great,
my soul does magnify the Lord for his goodness towards me;`" adding,
"`He has provided a good place for me in heaven.`"

On the 22nd of the Seventh month 1710, several Friends being present,
after some time of waiting in silence upon the Lord, he said these words,
or to this effect:

"`Dear friends, I counsel you in the love and fear of God,
to keep your meetings for the worship and service of God, both First-days and week-days,
(mind that), and also monthly and quarterly meetings,
which were set up by the power of God, to keep things in good order among us.`"
Farther he said, "`My love has been so great to Friends at Glastonbury and Street,
that I have ventured my life in riding through deep waters to visit them,
when I have had a concern from God upon my mind: so that you can say,
I have been a good example to you in keeping to meetings, as well as in other things.`"

Then he said, "`Although I am weak in body,
and do not know whether I may live much longer or not, yet I do not see death at present.
However, I am strong in the Lord, and in the power of his might,
and have nothing to do but to die, for I am rich in faith and good works towards God,
and my cup is full of the love of God.
Whether I live or die, it will be well with my soul; for, blessed be the Lord, I can say,
with the wise and holy Apostle Paul, that I have fought a good fight,
I have kept the faith, henceforth there is laid up for me a crown of righteousness.
And did the apostle say for himself only?
No, he was wiser than so, but to all them that love his appearing.`"

Some Friends of Somerton taking their leave of him, he said to them,
"`Give my dear love to Friends at Somerton, and tell them that my soul is alive unto God.`"
To a young man of that place, lately convinced, dear John Banks said,
"`Are you the young man that lives at Somerton, lately convinced of the blessed truth?`"
he answered, "`Yes.`"
"`The Lord,`" said John Banks, "`be with you; and I desire you, in his love,
to give up in obedience to the working of the Spirit of God in your heart,
and then he will do great and glorious things for you.
And do not you stumble at the cross; for the more you look at it, and put it off,
the harder it will be for you to take it up.`"

To another Friend, when he took him by the hand at parting, he said,
"`My dear love to you, and all that are faithful unto God.`"

To another that bade him farewell, he answered, "`I do fare well in the Lord;
my love is to you, and all the faithful in Christ;`" adding, "`Joseph is yet alive,
and that is enough.`"
Then he earnestly desired Friends to keep in the unity of the spirit,
which is the bond of peace.

A great deal more good advice,
in the living and eternal power of the great eternal God that attended him, he gave,
which is not noted; but at the delivery thereof, the hearts of many were tendered,
and tears ran down from their eyes.

On the 24th of the Seventh month, a Friend, visiting him, asked him how it was with him;
he answered, "`Very sick, and full of pain in my feet and legs, thighs and bowels;
but the Lord helps me, else I should cry out aloud; truth helps me, and ever has,
since I believed in it.`"

The day he died, being the 6th of the Eighth month, 1710, and Sixth day of the week,
he said to a Friend, "`It is well with me, and I have nothing to do but to die;`" and said,
"`I shall end in truth as I began.`"
So had an easy passage from here, and after all his labors, sufferings, and travels,
is entered into rest;
and there is no doubt of his portion in the everlasting kingdom of eternal glory forever,
to sound forth praises and hallelujahs unto the Lord God,
and the Lamb that sits upon the throne, who is worthy.

He was honorably buried in Friends`' burying-ground at Street, in Somersetshire,
the 12th of the Eighth month, 1710.
Aged seventy-three, convinced fifty-seven, and a minister forty-seven years.

[.the-end]
END OF THE FIRST VOLUME
