== PART 2 TEMP

[.chapter-synopsis]
* William Dewsbury
* Robert Wardel
* Elizabeth Harman
* Anne Mercy Staploe
* Morgan Cadwalader
* Richard Samble
* James Martyn
* Mary Mollineux
* Andrew Taylor
* Elizabeth Cowperthwaite
* William Wilson
* Mary Watson
* Grace Watson
* George Harrison
* Elizabeth Barker
* John Crook
* Sarah Beckwith
* John Burnyeat
* Henry Haydock
* Thomas Janney
* Henry Stout
* Thomas Aldam
* Margaret Kellam
* Joan Kellam
* Sarah Brown
* William Walker
* Ruth Middleton
* Alexander Jaffray
* Mary Padley
* Charles Marshall
* Sarah Padley
* William Garton
* Charles Ormston
* John Ormston
* Thomas Robinson
* Stephen Smith
* William Allen
* William Simpson
* Joseph Coale
* William Smith
* John Steel
* Thomas Lloyd
* Elizabeth Moss

WILLIAM DEWSBURY was one whom God raised up in the morning of his glorious day,
broken forth in our age.
After that eminent servant of Christ, George Fox, was set at liberty,
having been almost twelve months in Derby jail,
whereof nearly six months he was in the dungeon, for his testimony to the truth,
in the year 1651, he, passing from there through several counties, came to Balby,
in Yorkshire, where he was instrumental to convince several friends of note,
who were afterwards serviceable in their days, namely, Richard Farnsworth, Thomas Aldam,
Thomas Goodyear, Thomas and John Kilham, James Nayler, etc.
George Fox having a meeting at lieutenant Roper`'s house,
William Dewsbury and his wife came to it, and heard truth declared.
The same evening, they having some conference with George Fox,
confessed to the truth and received it; and after some time,
William Dewsbury publicly preached the same truth.

In the year 1653 he went into Westmoreland, Cumberland and Lancashire,
and declared truth both in steeple-houses and in meetings;
and underwent great sufferings, beatings, etc., and was imprisoned at York,
and also at Northampton in the year 1654.
Indeed, God made him an eminent instrument in his hand,
for the publication of his mighty day of power,
preaching repentance in order to the remission of sins.
He bore a faithful and universal testimony of the free grace of God to mankind:
and the Lord was with him, and prospered him in his manifold sufferings, travels, labors,
and exercises, in the gospel of Christ, and word of the ministry,
as may be seen in his several books, testimonies and epistles,
collected together in print.
Many were made sensible of the benefit of his labors, counsel,
admonition and encouragement, to the good and welfare of their immortal souls.
For the Lord, in whose dread and zeal he labored, endowed him with faith and courage,
and great boldness for his name and truth; and he published the same in great plainness,
and in the simplicity thereof.
To the tender-hearted he was exceedingly mild,
but to the stubborn and lofty he was sharp and plain; admonishing them,
and declaring the righteous judgment of God against that state;
watching with much patience and long-suffering the recovery of such,
who through the subtlety of the enemy, had fallen from the truth,
and from unity with the people of God.
But when any made it their work to cause division and discord,
and to sow dissension among brethren, he would plainly testify against them,
and reject them, as he did in his last visit to London.

A little time before his departure he had a concern upon him for the honor of God,
and that those who had believed, and made profession of the truth,
might answer it in a holy and blameless conduct; which he would often say,
could not be done by largeness of knowledge, and strength of comprehension,
but by a real dying to their wills and affections, by virtue of the daily cross.

The envy of wicked and unreasonable men was very great and fierce against him,
especially in those early days of his travels and labors;
and for the sake of his testimony he was often beaten, stoned, and imprisoned.
He feared neither their malicious threats nor blows, but boldly went forth,
publishing the truth, testifying to that of God in all consciences;
and the hand of divine Providence often delivered him out of the hands of his enemies,
for his name`'s sake.

A few weeks before his decease he came up to the city of London,
and visited most of the public meetings there, and bore a faithful testimony to truth,
and for love and unity; preaching up the cross of our Lord Jesus Christ,
by whom the world "`is crucified unto us, and we unto the world.`" Gal. 6:14.

It being the Third month, 1688, when he was in London,
and he intending to tarry there with friends till the Yearly meeting,
which was approaching, was taken ill about the 29th of the same month,
so that he could no longer be in the city.
He then determined to return home; but before he went,
he left a letter for the Yearly meeting, which is as follows:

[.embedded-content-document.letter]
--

[.salutation]
Dear Friends and Brethren,

I did not know till this last night but that I should
have been with you at the Yearly meeting;
but it pleased the Lord to visit me with my ancient distemper,
which has accompanied me in prison; and since I was released,
the distemper was so sharp upon me, as to my sense,
this last night I did not know whether I should have lived to see another day.
But crying to the Lord, he ordered and cleared my way to go into the country,
so that I cannot be with you at this Yearly meeting;
but desire the Lord to assist you with his blessed power and heavenly life,
to bring in the scattered ones to their everlasting comfort, and his glory forever.
Amen.

[.signed-section-closing]
And that it may be so with you, is the prayer of your loving brother,

[.signed-section-signature]
William Dewsbury

[.signed-section-context-close]
London, the 30th of the 3rd Month, 1688.

--

He lived but seventeen days after he left London; and making short journeys,
got home to Warwick, and continued weak in body.
A few days before his departure, some friends being together with him in his chamber, he,
rising up in his bed, in great weakness of body, said to them as follows:

[.embedded-content-document.testimony]
--

My God has yet put in my heart to bear a testimony to his name and blessed truth,
and I can never forget the day of his great power and blessed appearance,
when he first sent me to preach his everlasting gospel,
and proclaim the day of the Lord to all people;
also he confirmed the same by signs and wonders.
Therefore, friends, be faithful, and trust in the Lord your God; for this I can say,
I never played the coward, but as joyfully entered prisons as palaces,
bidding my enemies to keep me there as long as they could;
and in the prison-house I sung praises to my God,
and esteemed the bolts and locks put upon me as jewels;
and in the name of the eternal God I always got the victory:
for they could not keep me any longer than the determined time of my God.

And, friends, this I must once again testify to you in the name of the Lord God,
that what I saw above thirty years ago, still rests as a testimony to leave behind me,
that a dreadful, terrible day is at hand, and will certainly come to pass.
But the time when, I cannot say; but all put on strength in the name of the Lord,
and wait to feel his eternal power to preserve you through
the tribulations of these days that approach very near.
In the sense of which I have often been distressed and bowed in my spirit,
with cries and tears to my God for the preservation of his heritage.

And this I have further to signify, that my departure draws nigh.
Blessed be my God, I am prepared.
I have nothing to do but die, and put off this corruptible and mortal tabernacle,
this flesh that has so many infirmities; but the life that dwells in it,
ascends out of the reach of death, hell and the grave; and immortality, eternal life,
is my crown forever and ever.

Therefore, you that are left behind, fear not, nor be discouraged;
but go on in the name and power of the Lord,
and bear a faithful and living testimony for him in your day;
and the Lord will prosper his work in your hand,
and cause his truth to flourish and spread abroad; for it shall have the victory,
and no weapon formed against it shall prosper.
The Lord has determined it shall possess the gates of his enemies,
and the glory and the light thereof shall shine more and more unto the perfect day.

--

He concluded in prayers to the Lord,
with fervent breathings and supplications for all his people everywhere,
but more especially for his dearly beloved friends
assembled together at the Yearly meeting at London,
where he had intended to be, if the Lord had given him health:
his dear love was to all Friends who inquired after him.

He departed this life at his house in Warwick, in a good old age,
on the 17th of the Fourth month, in the year 1688.

[.asterism]
'''

ROBERT WARDEL, of Sunderland, in the county of Durham,
received truth about the year 1661, and bore a public testimony to the same,
not only in England, but also in Scotland, Ireland, Holland, and some parts of Germany.
In the latter part of his days, in the year 1694,
he went with our dear friend Robert Barrow, to visit the churches of Christ in America.
They travelled through nine provinces, or distinct governments, in those parts;
among whom they had three hundred and twenty-eight meetings with the people,
for the worship of Almighty God, to their comfort and mutual refreshment in the Lord.
And God enabled them to perform their service to the desire of their hearts,
in their old age;
and by his power supported them under all exercises which they met withal.

They left the continent to visit the islands;
and after they had been at Antigua and Bermudas,
where they had considerable service among Friends and others in those islands,
they arrived at Jamaica on the 10th of the Second month, 1696, intending,
if the Lord permitted, to go to Pennsylvania, etc., again.
After their arrival at Jamaica, they had several meetings; but,
about the 18th of the said month, Robert Wardel was taken ill,
for the climate was exceedingly hot, which made great alteration upon them both,
especially on Robert Wardel, who was very much indisposed.
A friend asking him how he found himself, he answered, '`I have been sick many times,
but I never felt myself as I am now; therefore I know not how it may be with me:
the will of the Lord be done: I am given up, and am content with God`'s will.`'
Another time he said to the woman Friend at whose house he was,
'`The Lord reward you for your tender care; it makes me think of my dear wife.
I know not whether I may ever see her more; but, however, the will of God be done.
I am, and was willing to be, contented with the will of God, whether life or death,
before I came here; and I bless God I am not afraid to die.`'
He continued to the end in a resigned frame of mind, submitting to the will of God.
On his dying bed he gave many good exhortations to Friends who came to visit him,
concerning the education of their children, their care in discipline in the church,
and that things might be kept in good order,
and that Friends might answer God`'s love to them.
After a few days`' sickness,
he peaceably finished his course on the 22nd of the Second month, in the year 1696,
at the house of John Dobbin, in Elizabeth Parish, in Jamaica.

[.asterism]
'''

ELIZABETH HARMAN, wife of John Harman, haberdasher in London,
and daughter of John Staploe, grocer of the same city,
was visited with a lingering distemper, which continued upon her for about four months;
in which time,
God was graciously pleased to give her many opportunities of great comfort,
inclining several friends to visit her, and to pray to the Lord on her behalf.
She much desired retirement, to feel her mind stayed upon the Lord,
that she might feel his living power to prepare her, that whether life or death,
she might be freely resigned and given up to the will of God.
But she said, '`Oh, how hard it is to come there!
It is hard work to die without having a full assurance of the love of God.`'

She had great travail and exercise of spirit, with strong cries to the Lord,
and wrestlings against the enemy, who endeavored to hurry her mind,
and bring her into doubts and fears, so that she would often say,
'`How busy is the enemy in a time of weakness,
and how hard it is to have a mind stayed upon the Lord!`'

After some time it was thought convenient, for the benefit of the air,
to remove her into the country to Mill-hill, in the county of Middlesex;
which being done, she was satisfied therewith, saying,
she hoped she should have more opportunity of retirement to seek the Lord,
and find him near her.

One day her father being near her, she said, '`Oh,
it is a good condition truly to wait and feel the mind stayed upon the Lord.`'
Her father related something of his own experience,
having been greatly distressed for lack of the presence of the Lord,
and help in the time of need.
She acknowledged her father`'s experience, and spoke with great respect of him,
and low thoughts of herself.
At another time she said,
'`Oh the enemy takes advantage of my outward weakness;`' but faith arising, she said,
'`I trust the Lord will drive him quite away.`'

A few days before she died,
her father and another friend coming late one night to visit her,
found her under great inward travail for the enjoyment of the love of God to her soul,
that being all she desired.
The next day, waiting upon the Lord in her chamber,
the friend signified the sense he had of the mercy and love of God towards her;
desiring that she might wait to feel more of it, and trust therein,
watching against the enemy;
and he believed God would graciously answer her desire and breathing;
and she acknowledged his regard to her.
The friend added, '`I believe this day shall not pass over,
before the Lord gives you your longed-for desire;`'
(which was God`'s presence,) and she believing,
answered, '`I believe the Lord will hear your prayers for me.`'
About the third hour in the afternoon,
while her husband and friend sat by her waiting upon the Lord, the same friend prayed,
and God did in a large manner manifest his love among them,
and by his living power drove away the clouds and darkness,
to the refreshing of the mourner,
and the comfort of her that could not be comforted
without the feeling of his power and goodness.
She said, '`Oh, now is the good time come!
Now I feel the love of God towards me, in my soul!
He has opened my heart and brought me into liberty.
How good a God have I! O the merciful God that I have to do with, that has remembered me!
He that said to the thief upon the cross,
"`Today you shall be with me in paradise,`" has looked upon me.
Now I am satisfied.
Now I am freely resigned, and given up to the will of God;
for now has the Lord given me the assurance of his love. It was observable how
careful she was all along of speaking anything beyond what she enjoyed.

All her near friends and relations sympathized with her
in the deep exercise and travail of soul she underwent,
before she received the full assurance of eternal happiness; which,
when she had attained to, was occasion of comfort and gladness of heart to them.

Soon after, some came to visit her,
to whom she signified something of the Lord`'s dealings with her,
remembering them of their latter end,
and the necessity of a preparation for that time and, withal, how hard it was to die.
One of them being under some convincement of truth,
she declared the need there was to mind and have
regard to the convictions of the spirit of truth,
and discovery of light; certifying the principle of truth to be most excellent;
and so many as are led by it, are fit to die;
but if any professing the same did act contrary, the fault was their own.
Desiring, that not anything of that kind might be a stumbling-block to them;
with more that she said,
speaking of the great assurance of the love of God which she enjoyed,
and now was willing to die, having nothing else to do but to die.
This so greatly affected the persons she spoke to, that they wept much,
and said they never should forget what she had spoken.
At night, her husband and father, and others, being present, she said, '`Come now,
rejoice with me; the good time is now come, because the Lord is good.
The Lord is good,
and has given me the assurance of eternal life! so that you may now rejoice with me,
and I hope you will have a joyful parting.
The Lord give you a good meeting, where I am to be buried,
and bless the opportunity to them that may be there.
O that all might be diligent who have been careless,
and let their minds out after vain things;`' desiring that all might love plainness.

The next day she signified to those about her the
continuance of the favor and love of God,
that she was engaged to speak of, and praise him for the same,
who supported her under great weakness;
and that she saw clearly through the secret and subtle workings of the enemy of her soul,
who would have discouraged her; '`but,`' said she,
'`I know the power that has driven him back, and he must enter no more.
Now is my soul redeemed to God, and he that has redeemed me is near me.
The sufferings and death of Christ, and his agonies; the shedding of his blood,
and what he has done for me; I feel now that I have the benefit of +++[+++them]
all: blessed be my Redeemer who is near me.`'

On the sixth day of the week several of her relations
and friends came from London to see her,
and were much comforted because of the good condition that they found her in;
and the time was good,
because the good God of life opened the living spring in their hearts;
that which stopped the well being taken away,
so that those who loved her most were reconciled to part with her.
To one of those present, whom she loved much, she said, '`Oh, why have you stayed so long?
If you had been here before, I believe I had been gone.
But oh, when I wrestled with the Lord for my own soul, you were still before me,
and it was often in my mind to send for you.
Indeed, I may say, the Lord constrained me; and it was to tell you this,
that your state is as mine was, not as mine is.
No, no, you have hard work to do first.
Oh the anxiety, the sorrow, the agony and perplexity of soul,
the Lord has been pleased to lay upon me; yet +++[+++I was]
blameless as to my life and conduct.
None can accuse me of any evil, neither do I believe they can you;
neither can I. Therefore take it not amiss,
for in pure love to your never-dying soul do I persuade you and exhort you;
for I cannot but say, I have seen clearly into your state.
Because I love you, I am concerned for you.
I know it is as I was: I have sometimes gone to a meeting, and not keeping on my watch,
my mind was cumbered with many things, and I have gone away never the better.
Answer me; has it not been so with you?`'
No reply being made, she spoke earnestly, and asked again, '`Prithee tell me, tell me.`'
Then an answer being given, she said, '`Watch and pray, dear friend,
for you will find it hard to die; live as well as you can:
and you know not but it may be your turn next.
Though you are a flower, so was I; yet see how I am faded away.
Forget not my dying words, forget them not; they are spoken to you in pure love.
Therefore, dear and tender friend, take them so.`'
Then she said, '`Farewell, farewell; I am going to eternal glory.
But, oh! how hard was it to obtain an assurance thereof!
But now, glory, glory to my God!
I have obtained pardon, and am going to him.
And one word more, dear friend; keep in all plainness both in house and apparel,
for that becomes us best; that will last longest;
that we shall have most peace in;`' then bid her again, '`Farewell, farewell.`'

That night another friend came to visit her, who, with her husband, father,
and several other friends, had a good meeting in her chamber.
After which, she expressed her affection to her husband and tender children,
desiring the blessing of God upon them,
and that her children might be brought up in the fear of the Lord,
and in that plainness which truth leads into; and said affectionately to her father,
You have been a tender father to me, be so to mine; a grandfather, double, double.`'
She further said, '`Though I have a dear, loving husband and two fine children,
and plenty enough of the things of this world, so that there is nothing lacking; but oh,
what is all that?
It is as nothing in comparison of the overcoming love of God which I feel.
Oh, how gracious a God have I. Now I want to go hence.
I long to be dissolved.
Come Lord, come Lord Jesus, receive my spirit.`'
And for the comfort of her friends, said,
'`My gracious God has given me the full assurance.
Oh, the light that I see before me,
and the glory of that kingdom I shall soon enter into.`'

The night before her departure, it having been the monthly-meeting at Mill-hill,
several of her friends came from London to visit her.
After they were gone, her father took notice what a company of friends had been below.
She replied, '`I pray God bless you,
and grant to you all as happy an end as I am like to make;`'
with many more sensible expressions which she uttered.
That night she received a letter from our friend William Penn, whom she much esteemed,
and who had been to visit her in the beginning of her sickness; part of it is as follows:

[.embedded-content-document.letter]
--

[.salutation]
Dear Elizabeth,

I am grieved that I am hindered from seeing you, but the Lord I have sought for you,
and in spirit abundantly sympathized with you.
I beseech him, make all easy to you in life or in death.
The Lord God of your life and the life of his dear people, be with you,
and do his blessed good pleasure: in the love of which endless life I bid you farewell,
farewell.
Your friend and brother in the Lord, where we shall meet again and live forever.

--

The which letter, a friend present, at her desire, answered, and she, at the conclusion,
expressed these words, '`My love in the Lord Jesus, in whom I received his love,
is dearly to him, and my dear love to his wife.`'

The next day, being the second day of the week,
she said in the morning to them about her, '`Dear friends, farewell;
the Lord God of heaven and earth be with you, bless you and preserve you.`'
Having taken leave of her husband, and all in order,
leaving directions not only about her children, as to the bringing them up,
but also the family she left behind, and concerning several acts of charity,
also her burial and the manner of it;
about the third hour in the afternoon she said to a minister present,
who often visited her in her sickness, '`A true friend,
the Lord reward you when I am gone.`'
And having an easy passage, she soon fell asleep, and is now at rest in the Lord.
She remembered her love in the Lord Jesus Christ to friends.
She died at Mill-hill on the 12th, and was buried in London the 15th of the Second month,
in the year 1698, aged twenty-eight years.

[.asterism]
'''

ANNE MERCY STAPLOE, daughter of John Staploe of Aldersgate-street in London,
a young maid between fourteen and fifteen years of age,
was a dutiful child to her parents, a pattern of contentment in the family,
and was seldom out of temper, whatever happened.

She had been at school the 18th of the First month, 1700,
and was taken sick the same day of a violent fever,
yet was preserved in her senses to the last.
At the time of her first being ill, a neighbor being with her,
she said she thought herself to be taken much after the manner that the servant maid was,
who died out of the family two or three months before.
She was heard to say, as she lay in a quiet and still frame, '`Your will,
your will be done.`'
Another time, her mother asking her how she did, she cheerfully answered,
'`that she thought she should not recover;
but desired to be contented with the will of the Lord.`'
When her friends came to see her, she affectionately acknowledged their visit, and said,
'`A broken heart and contrite, was accepted of the Lord;`' with many more words,
but her voice being low, they could not well understand them.
A friend taking leave of her, desired the Lord to comfort her, and she answered,
'`He has;`' and said, '`I have been in the sweetest frame that ever I was in in my life.
Praises, praises be to the Lord; for you are worthy of it.`'

She declared her willingness to die, and that she was happy in the Lord;
and being asked to take something to moisten her mouth she said, '`None;
for in a few minutes I shall be at ease:`' and looking on her friends about her,
she turned her face to the pillow, and said, '`Anne Mercy bids all farewell.`'
A neighbor asking her if she was willing to die, she said '`Yes,
and go to God;`' and departed in about two minutes after, having been sick four days.

She died on the 22nd of the First month, in the year 1700,
and was buried from the Bull and Mouth meetinghouse the 25th of the same month,
aged between fourteen and fifteen years.

[.asterism]
'''

MORGAN CADWALADER, son of Morgan Cadwalader, of Merion Township in Pennsylvania,
being under weakness of body, said,
when he was in health he was not so careful as he should have been;
so that when he heard friends speak it was to use but few words in our conversation;
he was not careful enough concerning these things:
and when it happened that he was among some who were light and vain,
it was pleasing to him.

But when the Lord was pleased to visit him with sickness,
and bring him in his apprehension very near death,
then he began to consider his condition, and saw himself lacking.
Then the fear of the Lord came upon him, and he took delight in his service;
and the company of those who were most serious, and careful to keep close to the Lord,
was most acceptable to him.
He desired that they would pray for him;
and the Lord put it into his heart to go alone to wait upon him, and pray unto him.
It was his chief concern to be serious and grave,
and to refrain from that company which he formerly delighted in.
Such a fear was upon his heart, that he would desire his friends and relations,
if they heard him at any time say amiss, to tell him of it.
When he was in his last sickness, a friend visiting him, enquired how he did, he replied,
'`I am not afraid of death, nor punishment after it;
for I know and am satisfied that the Lord will have mercy on me:
and yet I wait to come one step nearer to him.`'
To another friend he said, taking his leave of him, '`When your heart is tendered,
remember me; for it is good for one that is weak to have help.`'
He often said, '`The time of my going to my long home draws nigh;`' '`How good is the Lord,
and how great is his love!`'

One time he asked his mother how short he was of twenty years, she replied,
'`Three-quarters of a year.`'
'`Then,`' said he, '`if I go to my grave in my youthful days,
I shall escape a great deal of trouble that is in the world.`'
And farther said, '`I very often used to go alone into the woods,
and fall on my knees to pray to the Lord, and make covenants with him,
and that with many tears.
Though I have sometimes been too short in performing
my covenants which I made in my distress;
yet the Lord has been merciful to me, and I am willing to die.
This poor carcass, which is much decayed already, will go to the grave;
but the purer part, or spirit that is in it, will go to the Lord that gave it.`'

He said to his brother, '`I know you are tender, and often broken into tears:
if you will be careful, the Lord will be good to you.
I desire you, after meeting on First-days, and on other days, when you have time,
to read the Scriptures, and Friends`' books, and spend less time in reading history;
though I do not say there is harm in so doing, if it do not too much employ your mind,
for these things will be of little worth at last.
I hope you will think on my words, when my body is in the dust.`'
He prayed in this way, '`O! Lord, who does hear and see in all places,
let it be good in your sight to look upon me a poor mortal.
Comfort and strengthen me,
against the time that you may see it convenient to take me out of this world;
and if there be any under great trouble, Lord, do you help them.`'

The morning before he departed, a friend asked him how he did; his answer was,
'`I am very well.
I can wait bravely today,
better than at any time before;`' and desired his father to wait with him that day;
and also entreated both his father and mother to pray to the Lord for him.
He gave good advice to his sisters, to shun vain company; adding,
'`Through the goodness and mercy of the Lord I am going to a good place.
Do not despise your father and mother.`'
Farther speaking to them all, he said, '`When I am departed, be silent,
and have a care you make no noise; but for weeping, you cannot help that.`'
Then he said, '`Turn me on my right side, and I will trust in the Lord.`'
These were his last words that he spoke, and so slept about half an hour,
and departed this life without struggling, as if he had fallen into his natural sleep.

He died the 16th day of the Twelfth month, in the year 1698,
aged nineteen years and three months.
== Chapter 6

[.chapter-synopsis]
* Richard Samble
* James Martyn
* Mary Mollineux
* Andrew Taylor
* Elizabeth Cowperthwaite
* William Wilson
* Mary Watson
* Grace Watson
* George Harrison
* Elizabeth Barker

RICHARD SAMBLE was born at a place called Penn Hall, in the parish of Enoder,
in the county of Cornwall, and baptized according to the manner of the church of England,
the 24th of the Fifth month, 1644.
His education was in that Society;
and he continued in it until it pleased God to call him by his grace,
and to reveal his Son in him, which was about the year 1666,
at which time the Lord sent some of his messengers, called Quakers, into those parts,
to make known the way of salvation, and to turn people from darkness to light.
Their testimony he received and closed with, and, like Ephraim,
lamented his misspent time, under a form without power;
and then joined himself to the Lord and his people,
as in a perpetual covenant that can never be broken.
He was brought into deep humility,
and sat down in silence in the assemblies of God`'s people for several years,
in tenderness, fear, and trembling,
waiting upon the Lord for that wisdom which is from above.
Sometimes when his heart was filled with the power of the Lord,
he would in much tenderness speak a sentence or two in a meeting of God`'s people,
which was received and accepted.
Though his presence was contemptible to the great men, rabbis,
orators and disputers of this world, yet his testimony was made powerful to many.

He was improved in his gift for the work of the ministry, through great diligence;
and in his last six years he travelled frequently from county to county,
visiting the meetings of Friends in many parts of England and Wales.
At his return from his journeys he fell diligently to his trade, which was a tailor,
for the help of his family.

He gave up his weak body to spend and be spent in God`'s service,
and was as careful of his time as if he had seen
the shadows of the evening stretched out.

He adorned his testimony by a circumspect life, and was very temperate;
and all things were so sanctified to him in the fear of the Lord,
that he was a sweet savor in his day.
His wife did not remember that ever she heard him speak one unsavory word,
during the twelve years she was his wife; and he was contented in every condition;
exhorting her and his children to live in God`'s fear.
In the church he was a nursing father; never sparing his labor,
though many times through much difficulty, to visit the people of God,
both in season and out of season; rebuking some, exhorting others,
and comforting and confirming many, in that heavenly power that accompanied him;
being willing to serve the Lord with all his heart, mind, understanding, and strength.

About the First month, 1680, being then on his travels,
and having been weak some months before, he was taken sick at Poole, in Dorsetshire;
from which, expecting to see them no more, he wrote an epistle to Friends in Cornwall,
the county where he was born, and where he received truth,
and also where his family dwelt; which is as follows:

[.embedded-content-document.epistle]
--

[.letter-heading]
To Friends in Cornwall.

[.salutation]
Dear friends,

I send this salutation, as though it were my last unto you,
wherein I take my leave of you in the Lord Jesus Christ,
desiring you all may obey the truth, and live and die in it.
The many sweet and heavenly opportunities which my soul has had with you,
are fresh in my remembrance.
And now, dear hearts, my body grows very weak, but my soul is strong in the Lord,
who has greatly renewed the lasting seal of his love unto my soul this morning,
Oh! how could I sleep when my heart was so awakened unto
the blessed sense of my acquaintance with the Lord,
which sounded through my soul,
that my name should not be blotted out of the book of life, and of the holy city,
the heavenly Jerusalem, whose foundation is full of precious stones,
and where the river of the water of life flows; where the gates are not shut all day,
neither is any night there.
Which, when my soul heard, my heart was dissolved and broken within me,
and my head was as it were turned into water, and my eyes gushed out with tears,
in the consideration of the endless love of God to such a poor creature as I.

Now, dear friends, who are truly near me in the Lord,
you know the time of our first knowledge and acquaintance, which was a time of love;
and to this day my heart is filled with the same towards you, though I am likely,
as to the outward, to see your faces no more.

O Friends! be not ensnared or entangled with things of this world,
nor let your minds go out of truth,
and so lose the everlasting stay and support of your souls in the last day;
but rather let go all, and hold fast the truth,
and keep your hearts from being overrun with the world`'s spirit;
and so will the spirit of truth spring up in you as a well to refresh your souls.

And all you, whose hearts are truly tendered to the Lord,
whose trials and exercises are not a few, be not daunted nor discouraged,
although the enemy may seek to frighten you with many temptations,
and would seek to lead you out of the fellowship with your dying day;
which exercise my soul has sometimes passed under.
But blessed be the Lord forever, the enemy is found a liar;
for the Lord has been pleased to make this sick-bed to me better than a king`'s palace.
I have great fellowship with my last day, and do rejoice in the Lord,
who does so sweetly visit me with the glorious light of his countenance.
It is with me as it is with one who has travelled many weary journeys,
and at last is come to the sight of his desired end, which, when he sees,
he greatly rejoices in a sense of a further satisfaction which he shall after enjoy.
Even so it is with me,
who have passed no opportunity where I saw the way of life clear and open before me;
but have been ready, night and day, to do the will,
and answer the requirings of the Lord; and so running, as one in a race,
knowing my time that it is but short.
Blessed be the Lord,
I have great peace and satisfaction in this my weak and low condition; and satisfied,
seeing my lot was not at this time among you, that it is here in this place;
and I hope it will be well, whether I live or die.

My dear and well-beloved friends, dwell in love one with another,
walking in the unspotted life,
so shall you grow up as pleasant plants in the garden of the Lord,
and the dew of life will more and more descend upon you,
and this you will feel from day to day; and when you shall come to your latter end,
your reward will be sure with the Lord.

I have much in my heart towards you, but my strength fails me.
Only this I desire of you, seeing I am likely to leave my wife and tender babes with you,
whom I know not whether I shall see more.
Great is my love and tender respect to them,
for we have lived from the beginning as two joined together by the Lord,
who gives victory over the world; believing that, when I am gone,
the care of my God will be over them.
I have been a tender father to them, and they have been to me very tender children,
and my wife has been to me as bone of my bone, and flesh of my flesh,
yet I must leave both her and them unto the Lord.

And this would I leave with you, my dear brethren and sisters,
who have known me from the beginning, that you esteem her, when I am gone,
as one who was wife to him that was made willing
in his day to spend and be spent for God`'s truth,
and his church`'s sake.
I desire you in the Lord Jesus Christ,
that my dear wife may meet with no discouragements from you; she is a tender woman;
and that you will be encouragers of her.
I know when this comes to your hands, there will be no lack of sorrow;
but I trust in my God,
that both my dear wife and you will be so endowed
with the power and presence of the Lord,
that if you should hear of my going hence, you will conclude, as becomes true Christians,
that you must come to me, and that I cannot come to you.

My dear friends, in the opening, free love of God,
which this morning my soul is visited withal, I dearly salute you,
desiring the Lord may be a husband to my dear wife, and a father to my children,
and you friends to both.

And whereas I have never been lacking in my labor
and service for the glory of the Lord and your good,
when with you; and if the Lord yet lengthen my days,
I trust I shall be as ready and as willing as ever I have been;
so I conclude in a sweet and living sense of that love which will never die,
my wife`'s dear husband, my children`'s tender father,
and your own dear friend and brother, in the immortal seed of life,
where we are nearly and dearly related one to another.

[.signed-section-signature]
Richard Samble

[.signed-section-context-close]
Poole, the 1st of the First month, 1680.

--

Thus our dear friend had a true sense of his death;
and this letter manifests that he was a true Christian, a good husband, a tender father,
and a faithful friend and brother.
They were his dying and last words to them, as he said,
for he did not live to see his family and friends in that county, to whom he wrote,
though he continued some weeks after this.

Recovering a little strength,
he was desirous to be at home with his wife and small children,
and relations in Cornwall; and in order to it, he travelled in much weakness to Topsham,
and after a few days`' rest he reached Champet, near Moreton, in Devonshire,
and there he fell into a relapse, and his wife came to him.
The day before his departure, taking leave of his wife, he said, '`Oh! my dear wife,
come here to me, and let me take you in my arms once more.
The Lord will be to you a husband, and a father to our little children,
as you abide faithful to the Lord.`'
Then, after a few words more to her, he prayed a considerable time; yes,
as long as life lasted, he was praising and magnifying the Lord.
To a friend who visited him a little before his death, as he lay weak on his bed,
he declared how well it was with him; that he did give up to the Lord`'s requirings,
to spend and be spent for the church`'s sake;
and said he knew his time would be but short, and labors, travels,
and exercises would have their end, and be no more;
with many more heavenly expressions in much tenderness,
with tears running down his cheeks; which was a great comfort to the Friends present.

So he finished his testimony, and slept with his fathers, the 15th of the Third month,
in the year 1680, and is entered into rest from his labors, and his works follow him.
Aged thirty-six years.

[.asterism]
'''

JAMES MARTYN, born at East Acton, in the county of Middlesex, in the year 1646,
was convinced of truth in the year 1672.
He was a man whose conduct adorned the doctrine of Christ Jesus, which he preached,
and faithfully and zealously labored to spread the truth abroad;
on which account he travelled in America as well as in England.
The first time he went to America was in the year 1682,
and he returned into England in the beginning of 1684;
and went over into America a second time in 1685,
and returned again in the latter part of 1687:
after which he continued laboring in the ministry,
according to the gift of Christ received.

He was a weakly man in body, and was taken sick when he was abroad on a journey in Essex;
and being near his end, he said as follows: '`Good is the Lord:
great is his work which he has wrought in the hearts of his people,
to whom he has given power to follow him faithfully in the regeneration,
through great tribulations, and has made their garments white in the blood of the Lamb,
who has cleansed and redeemed them from the vain conduct of the world;
so that the image of the earthly is done away, and the image of the heavenly is borne.
Their citizenship and treasure is in heaven,
and it is their hearts`' delight to be there also.`'
In which blessed work, this dear servant of the Lord made a good progress,
even to the finishing of his course with joy;
and he received witness in himself that he pleased God, to his great consolation.

In the time of his sickness he had free access to the Lord,
who was pleased to give him the returns of his divine love and life,
to the overcoming of his heart and soul, and the comfort of them who were with him.
O! the heart-breaking power that attended him night and day,
which caused him to sing forth praises to the God of his life.
He often said, '`Oh! precious it is to dwell low with the Lord! not to aspire too high,
but to keep in the low valley, where the streams of life flow freely.`'
Again he said, '`O my dear God, how good are you to me! your goodness breaks my heart!
My dear Father, I have loved you ever since I knew you!
I have followed you faithfully ever since I did know your truth!
You blessed God! Let all that is within me praise
your name! You have given me a good reward!
Death is swallowed up of life.
You have given me victory over the grave.
My soul longs to be with you, my sweet Father!`' With much more,
even continually praising the Lord, and rejoicing in his mercy.
He admonished Friends who visited him to live in the life of their profession, saying,
'`A profession without life will stand none in stead when they come to die.
It is a dreadful condition to see death approaching,
and the terrors of God lie upon the conscience for disobedience.
O it is a blessed thing, when death approaches,
to know peace and consolation with the Lord, and an answer of well done.`'

He afterwards said, '`O what a blessed thing it is to feel life.
Friends, life is that which will make your hearts glad.`'
When his speech was almost gone, those about him could many times hear him say,
'`My soul praises the Lord.
My soul is glad with your joy.`'
He finished this life in great peace with the Lord, on the 30th day of the Eighth month,
in the year 1691, at the house of John Salmon, of Bocking, near Braintree, in Essex,
and was buried in Friends`' burial-ground at Ratcliffe, near London,
the 3rd of the Ninth month following, aged forty-five years.

[.asterism]
'''

MARY MOLLINEUX, wife of Henry Mollineux, of Liverpool, in Lancashire,
was one who in her childhood was much afflicted with weak eyes,
which made her unfit for the usual employment of girls.
Being of a large, natural capacity, quick and studiously inclined,
her father brought her up to more learning than is commonly bestowed on her sex;
in which she became so good a proficient, that she well understood the Latin tongue,
and fluently discoursed in it, and made a considerable progress also in the Greek.
She wrote several hands well, and was a good arithmetician;
as also versed in the study of several useful arts.
She had a good understanding in medicine and surgery, delighting in the study of nature,
and to admire the great God of nature in the various
operations of his power and goodness.

She was one who loved the blessed truth, and those who walked according to it,
from a child, being early convinced thereof,
and was not satisfied with a profession of religion only, but earnest for the life of it,
both in herself and others.
Not proud or conceited of
her parts and learning, but was adorned with humility; plain and decent in her clothes,
which she valued for service more than sight.
She loved to read the Holy Scriptures, and delighted much in solitude,
setting apart some time in the day for retirement.

She delighted in frequenting the religious meetings of the people called Quakers,
and suffered imprisonment for the same in Lancaster castle, in the year 1684.
Afterwards she was married to Henry Mollineux, to whom she was a loving wife,
an affectionate mother to her children, and a kind, charitable neighbor,
especially to such as were in distress, sick, or in affliction, though ever so poor,
giving both advice and medicines to them that stood in need;
whereby she was made an instrument of good to many.
She was noble in enduring hardships upon the account of her husband`'s imprisonment,
which was several times.
For him and his fellow-sufferers she made application to Dr. Stratford,
bishop of Chester, they being imprisoned upon the writ De Excommunicato Capiendo,
for not appearing at the bishop`'s court,
though they had no citation or lawful notice given them;
and after her discourse with the bishop, he was so favorable,
that they were set at liberty.
But afterwards, the priest who prosecuted them before, threatened them again.

She wrote many poems upon religious subjects, which were printed for public service,
having a gift that way.

Upon the 8th of the Tenth month, 1695, she was taken with sickness,
under which she continued nearly a month.
About nine days after she was taken ill, she said, '`I am well contented,
if the Lord see fit, that he take me away; for my pain is great,
and I know not what in this world I should stay to enjoy, except it be my husband,
and my little lads;`' her two sons; of whom she then said,
'`I would rather have my children enriched with the fear of the Lord,
than with all manner of worldly riches.`'
She grew daily weaker, inclining to sleepiness,
yet would sit up five or six hours at a time towards evening, and discourse freely;
and said to her husband, that she was well satisfied,
if the Lord took her away by that distemper, she should be eternally happy;
with more comfortable expressions that are not set down.
One evening it was thought she would have died; but recovering somewhat,
she spoke in Latin of being clothed hereafter;
whereby they understood that she was minding how the Lord would clothe her,
when her mortal clothing was put off.

Her husband asking her if she had any thing on her mind concerning her children,
or any other thing farther to communicate to him, she soon replied in Latin,
'`Why do you speak such things?`'
as if all temporal things were out of her thoughts; '`do not you understand me?`'
he replied, '`Yes, very well, you spoke of spiritual things;`' she answered, '`Yes;
but I have nothing concerning outward things farther to say.`'

The next morning, her breath being short, and her husband expecting her departure,
he expressed to friends present somewhat of his concern for her; to whom she said,
'`Be not you over-much careful or troubled.`'
When company was present she sometimes spoke in Latin,
when she intended it only to her husband.
Afterwards being asked how she did, her answer was,
'`Drawing nearer and nearer;`' with many other sweet and good sentences,
and so departed without any noise, sigh or groan, on the 3rd day of the Eleventh month,
in the year 1695, aged forty-four years.

[.asterism]
'''

ANDREW TAYLOR received truth in the year 1672,
when it pleased God to visit many about the borders of England, in Cumberland,
by sending his servants to declare the word of life among them.
Through his faithfulness and true zeal for the Lord, he came to be wonderfully changed,
and suffered several imprisonments for meeting among the Lord`'s people.
A man diligent in business, faithful and upright among men.
His way was, to be better than he appeared, so that people loved and esteemed him.
After several years, having approved himself just and honest towards men,
God bestowed his heavenly riches upon him,
and called him to the work of the ministry about the year 1679, fitting him for the same;
so that by him many were convinced of the truth and right way of the Lord,
not only in his own country, where he was best known, but in other parts;
for he travelled diligently in many parts of England, and also in Scotland and Ireland.

He was zealous to reprove sin, and careful to preach the gospel freely,
his own endeavors sufficiently supplying his necessities.
At last his body being much spent through his many labors and travels,
a universal weakness or consumption seized him.
Having little pain or sickness, he grew weaker and weaker, and,
being satisfied that his end drew nigh, there continued a travail upon his spirit,
that the Lord God who had been with him,
and borne him up in many deep trials and exercises, would receive him into his rest.
The friends present were witnesses of the hope that he had in his latter end;
and a little before he died, he prayed, saying, '`Come, Lord Jesus, come quickly;
for now I am ready.`'

Being filled with heavenly joy, he departed this life the 3rd day of the Third month,
in the year 1698, in the fifty-fifth year of his age,
and about nineteen years a preacher of the gospel.

[.asterism]
'''

ELIZABETH COWPERTHWAITE, wife of Hugh Cowperthwaite, of Flushing,
in Long Island in America, was convinced of truth about the year 1652,
in the north part of Old England, and continued therein faithful to the end.
She was a woman serviceable to the church of Christ in several respects,
as well by a public testimony to the blessed truth,
which she bore in much plainness and sincerity, delighting in the prosperity of truth,
and of the people of God.
She had true judgment when to speak, and when to be silent;
and divided between the precious and the vile, being tender to the brokenhearted,
but as a sword against that which was evil,
and which tended to division in the church of Christ;
very desirous that the young generation might grow up in the life of truth,
as in the education thereof.

She was at times sick several months before she died,
which she endured with great contentedness, often expressing the love of God to her,
and said that she felt his heavenly presence.
In the time of her sickness she bore many faithful
testimonies to the glory of the worthy name of God,
strengthening and encouraging friends in his work and service,
and against the spirit of separation; for the Lord had sealed it upon her heart,
that that which leads out of the heavenly unity, and brotherly fellowship,
was a false spirit, and not of the Father.
She often said that such could not be heirs with the true seed,
and exhorted those about her against the superfluity of the world;
showing them the ill consequence thereof.
Those friends who came to see her, she exhorted to faithfulness,
saying there is nothing like it.
She continued sensible to the last,
and departed this life on the 15th of the Tenth month, in the year 1697.

[.asterism]
'''

WILLIAM WILSON, of Langdale-chapel, in the county of Westmoreland,
was a man of an innocent life, and though he had little of outward learning,
yet God was pleased to teach him himself, and called him to bear a testimony to his name;
and he did it faithfully, not only in many parts of this nation, but in Germany,
and was several times in Scotland.

He was a man of a lowly and meek spirit, upright and just among his neighbors,
which caused them often to submit their matters in difference to his arbitration,
in which he was careful to find out the truth and ground of things,
and would never countenance deceit.
In this service he had success, seldom missing his desired end, which was to make peace.
Faithful he was in his testimony for the truth,
and a sufferer for the same in the prison of Kendal, in the year 1666,
and several other times afterwards, as well as by distress on his goods.
Besides that, he suffered cruel mockings, stockings, stoning, blows and wounds,
by cruel usage, both from priests and people; particularly at Eshdale in Cumberland,
where he exhorted the people to mind that of God in their consciences,
and turn to that holy light and law which he had put into their inward parts,
that by the same they might come to know the will of God, and do it.

Because of these and such like words, one Parker, a priest,
in cruel rage did beat and wound him, and with one of his crutches broke his head,
and caused the blood to run down his shoulders.
The priest being lame, and not able, as he would, to effect his cruel purpose,
caused his horse to be brought, on which he mounted,
and in the sight of the people broke his staff in three pieces upon William`'s bare head,
which made the people cry out against such merciless work;
but before the said Parker got home he was struck with sickness,
that he never came more to the steeple-house;
and during the time of his sickness he was very loathsome while above the ground,
and so died.

A few weeks after, the said W. Wilson went to the same place at Eshdale;
and for speaking a few words to the people, one Fogo, a priest,
took him by the hair of his head, pulled him to the ground,
and drew him out of the steeple-house; and also in rage and cruelty abused his brother,
Michael Wilson.
But a few months after, this same Fogo, riding over some sands,
accompanied with several people, fell into a quick-sand, and was immediately smothered.

William Wilson left behind him a widow and two daughters,
to whom he was a true husband and a tender father,
instructing his children to keep in the fear of the Lord,
and to walk in the way of truth, which he walked in himself, often saying to them,
it would be the best portion that they could enjoy.

His sickness was short.
Being lately come off a long journey, wherein his body was much spent and weak, he said,
'`I have not served the Lord unfruitfully.
I have no trouble upon me, and I am very sensible that all is well with me.`'
Again he said he was content whatsoever way the Lord pleased: he was as a dove, harmless;
and as a lamb, innocent.
A few hours before he died, he walked several times over the room, and said,
as he had often before, '`My peace far exceeds my pain.`'
And standing upon his feet between two friends, he said,
'`Oh that every one would mind the Lord, that they might keep life.`'
Then he sat down, and drew breath no more.

He deceased at his own house, at Langdale-chapelsteel, in Westmoreland,
the 10th of the Fifth month, in the year 1682.

[.asterism]
'''

MARY WATSON, wife of Samuel Watson, of the county of York, was one who,
for the sake of the blessed truth, denied herself,
and was made willing to part with those things which she thought stood in her way,
abhorring all manner of evil; and was a tender, nursing mother; nourishing, exhorting,
and building up the young in the most holy faith.
Though weak in body, she was much given to fasting on religious accounts,
and giving of alms; spending much of her time in private retirement,
frequent in prayer and praising the Lord, delighting in meditations; like Mary,
of whom our Lord said, she had chosen that good part,
which shall not be taken away from her. Luke 10:42.
While she had strength of body to go to public meetings,
she had a word to speak in season, suitable to the states and conditions of many;
and also was instrumental, in the Lord`'s hand,
in keeping things in good order relating to church affairs.

In the time of her weakness of body,
she was sometimes under fears of her great passage from mortality;
but through travail of soul,
in the living faith which she received of Christ the author of it,
she was kept steadfast, and obtained victory,
which God in his own time manifested to her soul.
And afterwards she made acknowledgments of the same to the refreshment of others.

Several weeks before her decease, she gave an account,
that the work of her redemption was wrought and completed,
and all her doubts and fears were removed; and now she waited to be dissolved,
and to be with Christ who redeemed and sanctified her; so that, as a wise virgin,
she was prepared to enter into eternal joy.
She was filled with praises while she had any strength remaining;
and her eye was to that heavenly family, out of all the families of the earth,
where she gladly desired to be rejoicing with her dear children and relations gone before,
as often her expression was.

She had a tender regard to her offspring whom she left behind, that they might,
through the grace of God, be gathered to Christ Jesus, the heavenly Shepherd;
with many heavenly prayers for them.
Her exhortation to them who were with her, and also for those absent, on her dying bed,
was that they might walk humbly before the Lord their Creator,
and watch against all the evil temptations of this world; the flesh,
and the vanity and lusts thereof; that so they might not be captivated with pride,
vain-glory, or intemperance; but, abiding in the holy fear of God,
all evil would be suppressed and slain upon the cross; and humility, righteousness,
meekness of spirit, and holiness, should grow up in them,
and be not only to them as a comely garment, but as a never-failing portion.

At last, all visible helps and outward enjoyments failing,
she had the Lord for her portion,
and kept in possession of that heavenly treasure in her soul,
and fed upon that living bread and wine of the kingdom,
of which she is now in the more full enjoyment.
She spoke often of her being surrounded with the glory of the Lamb,
and was sensible in her expressions to the last few hours; and said to her husband,
'`Love, pray for me.`'
So gave up the ghost, in a sweet, still manner, on the 2nd day of the Ninth month,
in the year 1694.

[.asterism]
'''

GRACE WATSON, daughter of Samuel Watson, of the county of York,
was well inclined from her infancy, being subject to her parents, and hating a lie;
and in the latter part of her time was much given to retiredness and reading.

In the time of her sickness she had more than ordinary concern
in a travail of spirit and combating with the enemy of her soul;
in which exercise she kept close to the power of an endless life inwardly;
but made no great appearance until the Lord had given her victory over the enemy,
and delivered her from his secret temptations.
Having passed through the ministration of judgment, her enemy,
the crooked serpent (as she expressed herself), was driven far from her dwelling,
so that nothing hindered her refreshments; and the well springing up, her joy was great;
and through her experience she sung the song of Moses, and the song of the Lamb,
in a spiritual triumph, with humiliation and brokenness of spirit.
She spoke seasonably and distinctly concerning the wiles of the devil, who, she said,
had laid his snares in trades, dealings, and conduct in the world, and also in families.
Though, according to common prudence,
one would have advised her to silence (her weakness of body considered),
yet she was so full, and had such constraint upon her,
that words flowed from her a long time, in great sweetness and heavenly refreshment;
insomuch that those with her were humbled before the Lord, in the sense of his presence,
which caused many tears.

As any came into her chamber, whether her friends (called Quakers) or others,
she had a suitable testimony, as if she had felt no weakness of body;
so that much was spoken which was not taken down.
Some of that which was taken, is as follows:

'`Oh, heavenly Father! What have you done for me this night?
How have you removed the crooked serpent! And not only removed him,
but taken him quite away; so that I can truly say, oh,
heavenly Father! your will be done!
You have shone in upon me with your marvelous light;
you have showed me the glory of your house,
the most glorious place that ever my eyes beheld:
neither did I think you had such a place for any, much less for me, a poor worm,
a pelican, once ready to think myself destitute.`'

Again she said, '`But now has the Lord taken me up; he has removed the crooked serpent;
so that I can say, I defy him, I defy him.`'

And further said to the Lord, '`If you require my life this night of me,
I freely give it unto you.
Oh, heavenly Father, your will be done; and if you have farther work for me,
keep me in that which I now enjoy,
for there will my greatest care be;`' meaning to be kept therein.

She said, '`You have made my cup to run over, over, over.
O heavenly Father, you have taken away all my pain.
I am as if I ailed nothing, though of myself I could do nothing;
scarcely move one of my fingers, my tongue being ready to cleave to the roof of my mouth;
but you have been a light to my feet, and a lantern to my path.
How can I cease praising you, you God of power! you are more to me than corn,
wine and oil.
Your love is sweeter to my taste than the honey, or the honey-comb.
Oh! it is more to be valued than the costly pearls, and the rich rubies.
The gold of Ophir is not to be compared unto it, O blessed, O praised,
O be magnified forever!`'

When she was asked how she did, her reply was, '`I am but weak of body,
but strong in the Lord, and in the power of his might.`'

Once she was questioning something, but she checked herself.
'`Why do I so?
My case is no doubting one;
the Lord has created a clean heart and renewed a right spirit within me,
so that all fears and doubts are taken away.
For,`' she added, '`the gates are open,
and the angels are ready to receive me into the bosom of my heavenly Father,
where I shall sing praises with his redeemed ones.`'

It was not perceived, in all the time of her sickness, that she desired to live;
but many times she said as above, '`If you require my life this night,
it is freely given to you.
Oh!
Lord, do with me what you please.
Oh! heavenly Father, your will be done.
What have you done for me, a poor stripling, in comparison of many?
You have made my bed, you have taken away my pain, and my sickness is gone.`'
And so lay all that day, with many other times, in this frame of spirit.

She said, '`The Lord has a people in this city, and other parts,
that he will take to himself, and crown with glory and honor.`'
She exhorted those present to prize their time,
and not to give themselves too much to the things of this world.
'`How many,`' said she, '`have laid up great riches, earthly treasure,
and in one night have been deprived of all!`'

Her sister weeping by her, she said, '`Weep not; remember David and be comforted.
The tongues of men and angels cannot declare the wonderful greatness of God.
O heavenly Father, how sensible of you have you made me!
You have strengthened me, otherwise I should not have been able to speak so much of you.
With you is fulness of joy, and at your right hand are rivers of pleasure forevermore.`'

She spoke of the parable of the ten virgins, '`Oh! therefore,`' said she,
'`keep upon your watch-tower, that whether he comes at midnight, or cock-crow,
or dawning of the day, +++[+++you may]
be ready; for that is the wedding-chamber indeed, and he is the heavenly bridegroom.`'

Speaking of her parents and relations,
she said they were as near to her as the flesh to the bone;
and taking her sister by the hand, she said to her, '`Though we be separated outwardly,
we shall meet in the kingdom of glory.
O! what cause have I to bless the Lord on their behalf,
whom I am sure never countenanced any evil in any of us, but reproved it.
The words of my dear and tender mother I do remember, since I was but ten years of age,
who said, she had fought the good fight of faith,
and the crown of glory was laid up for her.
These words having remained upon my mind, and taken deep impression upon me,
I can now say, I finish my course with joy, and shall receive the crown of glory.`'

She further said, that the Lord was a God at hand in six troubles, and in seven; '`no,
if you bring me to the eighth, you will never leave me:`'
such was her confidence in the Lord.
She departed this life in London, the 20th of the Sixth month, in the year 1688,
aged nineteen years and nine months.

[.asterism]
'''

GEORGE HARRISON, of the parish of Killington, in the county of Westmoreland,
came of a family of note in the world,
and underwent some hardships from his relations upon the account of truth,
which he received in the year 1652,
and soon after travelled in the service of the gospel in many counties of England,
through great afflictions, sufferings, and persecution,
from those who were high in profession of religion in that day.

He was an able minister of Jesus Christ, and valiant for the Lord.
When he came into a meeting of professors,
he would challenge of them the order of the true church, according to 1 Cor. 14:30,
which is, "`If any thing be revealed to another that sits by,
let the first hold his peace.`"

In the latter part of his time he went southward, and came to Edmundsbury, in Suffolk,
and declared truth through the streets of that town.
Afterwards he went to an inn there, desiring some refreshment for his money,
but they would not entertain him.
So he went to Bradfield-manger, and put up his horse at an inn,
and called for something to eat and drink;
but they perceiving by his language that he was a Quaker, refused also to entertain him,
and led his horse out of the stable; for which cruelty he meekly returned to them,
in the words of Christ, Matt. 25:43, "`I was a stranger, and you took me not in.`"
This innocent young man was obliged to ride abroad all night;
and it being a very wet season, and he having been tenderly brought up,
took a great cold.
He went to Haveril, a town between Suffolk and Essex,
where the people grievously beat him for his testimony to the truth; which hardship,
with the great cold that he had received by being forced abroad all night without food,
greatly injured his health, and put him in a fever.
After this, with difficulty, he got to Coggeshall, in Essex,
and was kindly received by Robert Ludgater;
and afterwards he removed to the house of Thomas Creek, of Little Coggeshall,
a mile further.

During his sickness, he felt the love and peace of God to be with him,
and said to the friends about him, '`Come, friends,
rejoice with me:`' and so lay praising God to the last hour.

He died at the house of Thomas Creek aforesaid, aged about twenty-six years,
and was buried in the orchard of Thomas Sparrow, tanner, at Stansted, in Essex,
the latter end of the Fifth month, in the year 1656.

[.asterism]
'''

ELIZABETH BARKER, wife of John Barker, merchant in Tower street, London, being sick,
a Friend went to visit her; and when she understood that he was below,
she caused those present to withdraw, and sent for him up.
He asking her how she did, she wept, and said, '`I am a poor weak woman;
and I have prayed to the Lord that if I am to die of this sickness,
he would let me know it; and I do not see it yet, though I am weak enough to expect it.`'
She expressed much concern for her three children, if she should be taken away.
The Friend answered, it was true that children are very near to tender parents,
but we ought to be resigned, and commit them to God who gave them to us; and besides,
if she should die, their grandfather and grandmother Barker were not only able,
but willing to take care of them.

Upon which she seemed somewhat satisfied: after a space of silence she said,
'`It is assurance of my peace with God that I do earnestly desire.`'
And further, '`For these two years past God has been at work in my heart,
and I endeavored to answer his will, and have denied myself of some things;
but I have had a care not to do it in imitation of others,
but from a conviction in my own conscience.
I hope, if I live, I shall be faithful to God,
and keep those covenants that I have made with God.`'
Afterwards she said, '`Oh the presence of God! it is that which my soul desires to enjoy.
God has been good to me many times; for when I have been alone at home,
as well as in meetings, the Lord has broken in upon my heart.
When I have been troubled and exercised in my mind,
I have gone in secret and prayed to the Lord, and I know he has heard me,
and several times answered my prayer, not only for myself, but for my children also.`'
She particularly mentioned one time,
when one of her children was in appearance near to
death; '`I bowed my soul before the Lord,
with earnest cries to him for my child; and the child fell into a sleep,
and awakened much better, even before she took any medicines.`'

After some pause, she asked the Friend who was with her,
what his thoughts were concerning her recovery; to which he replied,
he had little to say to that; and desired her to keep her mind stayed upon the Lord,
whom she acknowledged had mercifully visited her,
and she would find him still to extend his mercy and favor to her,
with his good presence, which was the most comfortable support upon a sick-bed.
She replied, '`God has been with me in this sickness, but I want more of his presence:
'`and added, '`In the first of my sickness, and before, at times,
I used to be terrified with the thoughts of death; but now it is not so.
I am not afraid of death; that fear is taken away.
Yesterday they thought I was dying, and they were in a great hurry about me;
but I was not so in myself, for I felt great sweetness and stillness upon my mind.`'
Afterwards she said, '`I do not find that the Lord does lay any thing to my charge.`'

Speaking concerning her child, she said, '`When I was last year in Yorkshire,
God did many times visit my soul, and I had large enjoyments of him;
and one time praying to him, I fervently asked the Lord to give me a son;
and now God has answered me in this request;
my desire is (which she spoke with much concern) that, when he is grown up,
he may be a preacher of righteousness.`'
She spoke upon several things, which are omitted, for she had a clear understanding,
and was in a right mind and frame of spirit.

Another time the same person visiting her, she desired all in the room might be still,
and she waited in much retiredness of mind, secretly breathing to the Lord in her heart;
and the Friend prayed by her, with whom she heartily joined.
Upon his leaving her, she said, '`This has been a good time.
I have many visitors, but too few of this kind.
I have felt the Lord`'s presence, but he will be quickly gone again.
I have not so much of these sweet enjoyments as I desire.`'
After some more that passed,
he asked her if she desired to speak with any particular Friend in the city,
and he would acquaint them with it; she answered, '`I have not; I am easy in my mind.`'

About three days before her departure, when it was thought she was dying,
the same Friend being sent for, she told him that she was willing to die,
if it was the will of God;
and gave him an account of the concern that she had upon
her mind for a relation who came lately to visit her,
whose sister had married one that was not called a Quaker.
Said she, '`I entreated her not to do the like; also I prayed her mother,
that she would not allow it to be; and I desired her not to forsake the truth,
and God would never forsake her; and they both wept; and when she comes again,
I will endeavor to make her promise me not to marry one that is not a Friend.`'
The person replied,
'`But then she must also keep her promise;`' to which she earnestly answered,
'`Ah! so she must.`'
The rest that she said at that time is omitted; only,
that she had a great desire to speak to the other sister who is married;
but she said she was in the country.

Her father and mother coming to visit her, found her in a heavenly frame of mind;
and she said, '`O mother, you know that I have been afraid of death,
and how I have loved vain and foolish things;
but I have prayed to the Lord to forgive me all my sins.
And now, instead of that fear of death, there is much sweetness upon my soul;
and all those vain things I once loved, I now loathe; and all the world is nothing to me:
with much more, expressing her satisfaction and peace of conscience.
She spoke of the exceeding joy and comfort that she felt,
and how sweet the presence of God was to her soul;
and she made heavenly melody to God in her heart,
which tenderly affected the minds of those present.

Her sickness increasing, she grew weaker; and though sometime before,
she did not see that she should die,
yet afterwards was satisfied concerning her departure; and, in order thereunto,
bequeathed several things to her relations and children,
and gave directions concerning the ordering of her children and family,
and also where she would be buried.
She received assurance of her future happiness; for, a few hours before her decease,
the said Friend before mentioned, coming to visit her, found her very much spent,
and her kindred and relations mourning about her; and he prayed,
desiring that all might submit their wills to the will of God,
who gives and takes away as he pleases.
A considerable time after he was gone, lying very still, she said, '`The voice said,
"`Submit, submit;`" and I say, I have submitted,
I have submitted;`' or to the same effect.
When these words were spoken, a relation present said,
'`You are going to leave us;`' she replied, '`I shall be happy.`'
She also, in the time of her sickness,
saw a vision of the difficulty of her passage out of this world,
and of the felicity of the place she at last was to arrive at.

She peaceably ended her days the 6th of the Third month, in the year 1701,
aged twenty-eight years.
== Chapter 7

[.chapter-synopsis]
* John Crook
* Sarah Beckwith
* John Burnyeat
* Henry Haydock
* Thomas Janney
* Henry Stout
* Thomas Aldam
* Margaret Kellam
* Joan Kellam
* Sarah Brown
* William Walker

JOHN CROOK was born in the year 1617, and received the blessed truth,
as testified of by the people called Quakers,
at its first being preached in Bedfordshire, which was about the year 1654.
He was a man of note in that county, having been a justice of the peace;
and the Lord by his spirit made him an able minister of the gospel of Jesus Christ.
He had great discoveries in the mysteries of the gospel, was sound in doctrine,
and a skillful archer, hitting the mark.

In former years, when he was out of prison, he labored much in publishing the gospel,
and many were the seals of his ministry.
As he had received a part of the ministry,
so also he had a share of sufferings for his faithful testimony,
being imprisoned in several places, as at London, Huntingdon, Aylesbury, and Ipswich;
and as he sealed to the truth by sufferings,
so he was careful to adorn the same by conduct,
and had regard to the power of godliness in life and doctrine, above dead forms,
and to the spirit above the letter, yet highly esteemed the Holy Scriptures,
with respect to the sacred doctrine thereof, being well read therein,
and devoted for the faith and practice thereof, as the Lord gave him understanding.

He was eloquent, allegorical, and mysterious, many times in his ministry;
but did not thereby deny or invalidate the history of Christ, etc.,
as recorded in the Holy Scriptures.

The mystery of Christ in spirit, and as revealed and formed in true believers,
and their sincere conformity to him in spirit and conduct, he greatly esteemed;
desiring the professors of Christianity might come
into the true sense and experience thereof,
by a true, living and feeling faith in Christ, and sincere obedience to him.

He spent his former years mostly in and about Bedfordshire and the counties adjacent,
and his latter years in Hertfordshire,
being often disabled from traveling far by reason of several infirmities of body,
so that he would say (with Israel), "`I have been afflicted from my youth,`" Psalm cxxix.
Under the sorrow and grief that he had with some of his children, he would sometimes,
in a tender frame of spirit, comfort himself in the words of David,
"`Although my house be not so with God, he has made with me an everlasting covenant,
ordered in all things, and sure,`" 2 Sam. 23:5; and said,
that the Lord did remember the kindness of his youth.

His patience under his bodily infirmities was very remarkable,
and as a good Christian he made the best use of them,
saying that the furnace of affliction was of good
use to purge away the dross and earthy part in us;
and that, did he not feel and witness an inward power from the Lord to support him,
he could not subsist under his pains, they were so great,
which continued with him to his end;
yet he was not remembered to have uttered an unsavory word, or impatiently to cry out;
and when the extremity of his fits was over,
he would express his inward joy and peace that he had with the Lord.

He would many times say, that many of our ancient friends were gone to their long home,
and we are making haste after them; '`Thus,`' said he, '`they step away before me,
and leave me behind, and I that would go, cannot.
Well, it will be my turn soon;`' in which he seemed to rejoice.

He finished his course the 26th day of the Second month, in the year 1699,
in the eighty-second year of his age, and was buried at Friends`' burial-ground, at Sewel,
in Bedfordshire.

[.asterism]
'''

SARAH BECKWITH, daughter of Marmaduke Beckwith, of Audborough, near Masham in Yorkshire,
was from a child sober and grave in her deportment,
not addicted to light and needless words,
but behaved herself as one who was watchful lest she should offend the Lord,
or be an evil example to others.
She was obedient to her parents, and tenderly affectionate to others,
one sincerely devoted to serve the Lord,
and seek his kingdom and the righteousness thereof.
She loved retirement, and when her business was over,
would walk alone in the fields and other places, where she sought the Lord,
and would sing praises to him, when she thought nobody saw or heard her.

In her sickness she was much troubled with shortness of breath,
and often prayed to the Lord, to enable her to praise him while she lived.

About five days before her decease, having some ease,
she desired to be raised up in her bed,
and spoke largely of the tender dealings of God with her,
desiring those who were young to prize their time,
not knowing how few their days might be; '`For,`' said she,
'`many are the temptations of the enemy, especially to youth, presenting length of days,
and persuading them that it is soon enough to trouble themselves with such a concern,
for so he would have persuaded me; and many ways was I tempted,
which caused such exercises that I was brought nigh to despair.
I sought the Lord night and day.
No ear heard me but the Lord alone, who heard my call,
and afterwards gave me some comfortable assurance of my salvation:
but the enemy has been very busy, and has sorely hurried me,
since I began with this illness.`'
Afterwards she prayed, '`Lord,
give me full assurance of my salvation before I depart hence!
O Lord, let not my distemper overcome my senses, till I come to a full enjoyment!
I pray you, let not my desires cease, till you answer the desires of my heart;
and let nothing quench your love.`'
And the Lord answered her cries, and caused her cup to overflow,
so that she sung heavenly praises to the God of her salvation.

She also gave tender advice to her sisters,
and desired them to love and fear the Lord above all, and keep in the truth; saying,
'`Oh! press after it, to feel the working of it in your own hearts;
and when you are in it, keep in it, and under the government of it.
Heed not to deck yourselves, but be meek and low.
None ought to pride themselves in any endowment, either beauty, or any other thing;
because it is not theirs, but the Lord`'s who gave it them,
and can take it away when he pleases;`' saying, '`What is all now to me?`'
She also spoke of the condition of some who were grown careless,
and were got into liberty; '`Such,`' said she,
'`are ill examples to those that are coming up.`'
She said there were many who professed truth that knew little what truth is.`'
It does not consist only in coming to meetings, and wearing plain apparel and the like,
unless they come to feel the operation of truth in their own hearts;
for all such outward appearances will stand in no stead,
without the love of God be inwardly felt and enjoyed.
It is an easy thing to come to meetings; and some are ready to think, that doing so,
and behaving themselves soberly, is sufficient; but the Lord sees at all times,
and he will have no such mockery.
I bless God, I have not been guilty of seeming what I was not.`'

Her love was great to faithful friends, and she much desired their company,
and wonderfully prized the love and mercies of God, saying, '`It is not for my deserts,
for I had nothing to engage the Lord with, but it is his free love to me.`'
She said '`there was man`'s righteousness, and the righteousness of God;
but man`'s righteousness must be rent off,
and man covered with the righteousness of Christ Jesus, who said,
"`I lead in the way of righteousness, in the midst of the paths of judgment,
that I may cause those that love me to inherit substance.`"`' Speaking of the way of truth,
she said, it was a strait and narrow way, and not to be kept in without a daily watch;
and further said, '`But although a strait way, yet it is a pleasant path, and delightsome.
Oh! here is peace in abundance.
It is so sweet, I could delight always to enjoy it, and to live therein;
gold is not worthy to be compared to it.`'
She thus continued, being taken up with heavenly thoughts, saying, '`Lord,
give me fully to drink of the well of water that is within the gate,
for you have raised my heart, and I am overcome with your love.
O! I long, I long!
O! Lord, open you the windows of heaven, and pour of your blessings into my soul,
until there be not room to receive, that I may bless and praise your name.`'

Her end drawing nearer, she prayed the Lord to give her an easy passage;
and taking her leave of her sister Hannah, she said if she was worse,
some should call her.
Taking her by the hand, she said, '`Dear sister, you have been near and dear to me,
and careful of me: the Lord requite you,
and be near to you when you come to lie on your dying bed.`'
Near morning, her distemper growing upon her, she said, '`I am as sensible as any of you,
and I am well content to die.
I have no doubt of my salvation:`' with many more good expressions,
which could not be perfectly understood, her voice being low;
but she was sensible to the last,
saying within a very little time of drawing her last breath, '`Lord,
take me away;`' and presently after, she gently and comfortably passed out of this world,
to live forever in a world which has no end.

She departed this life the 24th of the Ninth month, in the year 1691.

[.asterism]
'''

JOHN BURNYEAT was born in the parish of Lowes-water, in the county of Cumberland,
about the year 1631; and when it pleased God to send his faithful servant George Fox,
with other of the messengers of the gospel of peace and salvation,
to proclaim the day of the Lord in the county of Cumberland, and north parts of England,
this dear servant of Christ was one that received their testimony,
which was in the year 1653, when he was about twenty-two years of age.
Through his waiting in the light of Christ Jesus, unto which he was turned,
he was brought into deep judgment, and great tribulation of soul,
such as he had not known in all his profession of religion,
and by this light of Christ were manifested all the reprovable things;
and so he came to see the body of death, and power of sin which had reigned in him,
and felt the guilt thereof upon his conscience,
so that he did possess the sins of his youth. '`Then,`' said he,
'`I saw that I had need of a Savior to save from sin,
as well as the blood of a sacrificed Christ to blot out sin,
and faith in his name for the remission of sins;
and so being given up to bear the indignation of the Lord because of sin,
to wait till the indignation should be over,
and the Lord in mercy would blot out the guilt that remained,
which was the cause of wrath, and sprinkle my heart from an evil conscience,
and wash our bodies with pure water,
that we might draw near to him with a true heart in the full assurance of faith,
as the Christians of old did.`' Heb. 10:22.

Thus did this servant of the Lord, with many more in the beginning,
receive the truth (as more at large may be seen in
the journal of his life,) in much fear and trembling,
meeting often together, and seeking the Lord night and day,
until the promises of the Lord came to be fulfilled, spoken of by the prophet Isaiah,
chap.
xlii.
7, xlix.
9, and lxi.
3+++.+++ Some taste of the oil of joy came to be witnessed,
and a heavenly gladness extended into the hearts of many,
who in the joy of their souls broke forth in praises to the Lord,
so that the tongue of the dumb, which Christ the healer of our infirmities unloosed,
began to speak, and utter the wonderful things of God.
Great were the dread and glory of that power,
which in one meeting after another were graciously and richly manifested among them,
to the breaking and melting many hearts before the Lord.
Thus, being taught of the Lord, according to Isa. 54:13, John 6:45,
they became able ministers of the gospel,
and instructors of the ignorant in the way of truth.

After four years waiting, mostly in silence, he appeared in a public testimony,
which was in the year 1657,
being at first concerned to go to several public places of worship,
reproving both priests and people for their deadness and formality of worship,
for which he endured sore beating with their staves and bibles, etc.,
and imprisonment also in Carlisle jail,
where he suffered twenty-three weeks`' imprisonment
for speaking to one priest Denton at Brigham.

After he was at liberty he went into Scotland in the year 1658,
where he spent three months, traveling both north and west.
His work was to call people to repentance,
from their lifeless hypocritical profession and dead formalities,
and to turn to the true light of Christ Jesus in their hearts,
that therein they might come to know the power of God, and the remission of sins.

In the year 1659 he went into Ireland,
and preached the truth and true faith of Jesus in many parts of that nation.
About the Seventh month following, meeting with Robert Lodge,
a minister concerned in the same work, he joined with him,
and they labored together in that nation for about twelve months,
in the work of the gospel, and returned to Cumberland in the Seventh month, 1660.

In the year 1662 he travelled to London, where he met with George Fox,
Richard Hubberthorne, and Edward Burrough; and in his returning home through Yorkshire,
at Rippon he was committed to prison, and kept fourteen weeks,
for visiting the friends who were prisoners there.

After he was discharged of that imprisonment he returned home, where he abode,
except at times visiting friends in adjacent counties,
till the beginning of summer in 1664, when he took shipping again for Ireland,
and visited most of the meetings in that nation.
From there he embarked for Barbados, in order to perform his journey into America,
which had lain before him for four years; and from Galway he arrived at Barbados,
after a passage of seven weeks, and stayed three or four months there,
and had great service, and much exercise also,
occasioned by the imaginations of John Perrot,
and that fleshly liberty he had led many into, not only there,
but in Virginia and other places.
From Barbados he went to Maryland about the Second month, 1665,
and afterwards to Virginia, laboring in the work of the gospel.
In the Fourth month, 1666, he came to New York, so to Rhode Island, New England,
and Long Island, till the Second month, 1667, at which time he went again to Barbados,
and spent that summer there.
In the Seventh month of the same year he sailed from there, and arrived at Milford-Haven,
in Wales, and labored much in the gospel in this nation,
from the time of his arrival from America, till the latter end of the year 1669,
when he went over and spent that winter among friends in Ireland,
and returned to London in the year 1670.

In the Fifth month, 1670, he embarked for Barbados again,
in company with William Simpson, who died in peace with the Lord in that island.
From there he went to New York, Long Island, Rhode Island, and New England,
and afterwards to Virginia and Maryland, where he met George Fox and several brethren,
just come from Jamaica.
Having spent much time and labor up and down in America,
till the 25th of the Second month, 1673, they came from the Capes of Virginia,
and arrived at Galway in Ireland, the 24th of the Third month,
and from there they came to the yearly meeting at London, in 1674.

From that time he continued in this nation, laboring among the churches,
until the Eighth month, 1681, when he went to Ireland again,
and tarried there till the Sixth month, 1684, and then he came into Cumberland,
and so to Scotland, and into the north parts of England again,
visiting the meetings of Friends, and so returned to Ireland the 25th of the First month,
1685, where he tarried till he departed this life.

In the latter part of his life he took a wife in Ireland, and had by her one son.
After the death of his wife, he had some intentions to go for England,
about the year 1688; but seeing the troubles and wars in Ireland coming on,
and that many afflictions would attend Friends in that nation,
and people being possessed with fears fled for England; our dear friend,
though he had opportunity, had no freedom to go,
but gave himself up to stay with Friends there,
and bear a part of the sufferings that might attend them.
In this time he was a precious instrument in the Lord`'s hand,
able and skillful in the ministry, for the comforting of his people;
for he was a cheerful encourager of them, a dear friend and true brother;
a diligent overseer and tender father; a perfect and upright man in his day.

Having been at a province-meeting at Rosenallis,
where he bore a living testimony to the comfort of friends,
he went from there to Mountrath and Ballinakill,
and so to a monthly meeting at New Garden; after which he came home with John Watson,
and feeling himself not well, took his bed, and was visited with a fever,
and continued sick twelve days; in all which time he was preserved in his senses,
and in a sweet frame of spirit.
He often said he was finely at ease, and quiet in his spirit,
and the Lord did attend him with his heavenly power and presence, to his comfort,
and the satisfaction of those about him.
He said that he ever loved the Lord, and the Lord loved him from his youth.

He peaceably departed this life on the 11th day of the Seventh month, in the year 1690,
and was decently buried at New Garden, the 14th of the same.

Convinced at the age of twenty-two; a laborer in the gospel thirty-three;
aged fifty-nine years.

[.asterism]
'''

HENRY HAYDOCK, of Warrington, in the county of Lancaster,
was a faithful man in life and conduct, and walked as becomes the blessed truth,
of which he made profession.

When he was upon his dying-bed, and in outward appearance nigh gone, the Lord,
who is the God of the living, raised him up by his divine power,
to the admiration of those present, to bear a living testimony for him, which was thus:

'`Friends, I was never a public preacher in all my life; but now, by the power of God,
I am one at my death.
Glory be to God forevermore, who has the life and breath of all men in his hand,
and can lengthen at his pleasure; who knows how to dispose of us.
Therefore, friends, all be faithful to the Lord,
for great things will the Lord bring to pass for his people,
who are true in their hearts to him.
Such as serve God faithfully, they shall have a living reward from him,
and their rest shall be with the Lord Jesus Christ;
which rest my soul is already entered into,
and is set down with God in the Paradise of his pleasure,
taking its repose with God the Father, and our Lord Jesus Christ,
and all the holy men of God since the foundation of the world.
And though my body go down to the earth,
yet my soul and spirit shall have its residence with the living God in heaven,
where they who are unfaithful to the Lord cannot come.
I was well nigh my last breath, but the Lord loosed my tongue,
that I might declare of his goodness.`'

Again he said, '`The Lord in my healthful days did put his living word in my heart,
and though I have been by some looked upon as a stripling,
and as one that knew not much of the things of God,
yet my soul has had many sweet seasons and opportunities.`'
Again he said, '`I have a very good wife, faithful and loving to me,
and three sweet children; call them, that I may kiss them before I die,
for my time here will not be long.`'
So they brought one of his daughters to him, and he said, '`You are Elizabeth,
my youngest daughter,`' and kissed her many times.
He farther said, '`Silver and gold I have not much to leave you;
you have hitherto been a good child; the blessings of the living God rest upon you,
and the blessing of me, your dying father, be with you also.`'
So then he took his son, and said, '`You are Roger, my sweet son.
In you I have taken great delight; yet now your father is about to take his last breath;
and that which I desire of the Lord, is, that he will bless you and your two sisters,
and bless you all, that you may keep up my name, and live as your father has done.
Though I have not filled up the number of many years, yet I, your father,
do witness peace with God.`'
Being pretty much spent, he said, '`The Lord bless you, my son, and your two sisters;
the blessing of your father be with you all;`' and so kissed him many times,
and let him go.

Then he called for his daughter Alice, and said, '`You are Alice, my first born,
and I love you well.
It has been real and true; and though some men can show it more, yet I love you all well,
and I hope the Lord`'s care will be over you when I am dead and gone;
and I believe you will not lack.
Alice, (said he) kiss me, for you must never kiss me more:`' so clasping her in his arms,
he kissed her, and bade her farewell.
And then said, '`I have now made an end of what lay upon my mind; therefore, everlasting,
living, pure, invisible God, into your hand of power I recommend my soul.`'
He lay still and quiet till a little before his departure,
when the very pangs of death seized on him; then were his sighings many,
yet had the savor of life in them.
Afterwards he lay still and very quiet, rejoicing in his spirit, and said,
'`My soul does magnify the Lord, and my spirit rejoices in God my Savior,
who has saved me from sin; but what shall I say to the rebellious?
If they will serve the devil, they will have a bad portion in the end.`'

He said, '`Though there may some of all persuasions find salvation, yet that people,
in scorn called Quakers, who are really faithful to God, are satisfied in God,
and they know salvation to their immortal souls, having been redeemed by Jesus Christ,
who is come to save many.`'
He prayed for his brother and sister, saying, '`Lord,
you know I have one brother and sister,
who are not in that faith in which I am about to lay down my head.
Lord, bring them to it, if it be your blessed will, and confirm them in the same,
that they may receive that blessed reward you have made my soul a witness of.`'
And said, '`So my strength now failing, as to my outward man,
I once more recommend my soul into your hands, Lord Jesus Christ.`'

He departed this life the 5th day of the Fourth month, in the year 1688,
aged about thirty-three years.

[.asterism]
'''

THOMAS JANNEY was born in Cheshire,
and received the blessed truth at the first preaching thereof in that county,
which was about the year 1654, being then in the twenty-first year of his age.
The next year he received a gift in the ministry, preaching the gospel of Christ freely;
and travelled into many parts of England and also in Ireland,
and had a fervent and sound testimony for truth;
and his conduct and course of life accorded with his doctrine.

In the year 1683, he with his family went to Pennsylvania, and there settled,
where he stayed about twelve years; and in the year 1695,
he came over again in company with his friend Griffith Owen, of Pennsylvania,
to visit his brethren in England: and after he had stayed some time in London,
he went into Cheshire in the Sixth month of the same year,
where he had many relations who were faithful friends; and though they were dear to him,
and their houses might have been his home, yet he rested little,
but visited the meetings of Friends in several neighboring counties.

The next spring he travelled through several counties where he had been in former years;
and as he had a desire to see the brethren at the yearly meeting in London,
he was there at that time; soon after which he was taken so ill,
having decayed in his natural strength before, that his recovery was much doubted;
and some advised him to go out of the city for the recovery of his health.
After some time he adventured by short journeys from London to Enfield, so to Hertford,
and from there to Hitchin, where his distemper increasing he could go no further,
having a purpose to go for Cheshire.
At Hitchin he lay a considerable time at the house of our friend William Turner;
and friends there were careful and tender over him;
and he having endured much hardship formerly in the service of truth,
by traveling into several climates, and enduring heats and colds,
his body was attended with much pain, so that few expected his recovery.

Two of his relations, who were friends, came from Cheshire to Hitchin to visit him,
and one of them being with him in his chamber, he said to this effect: '`Cousin,
I am glad that you are come.
I hardly expect to recover so as to be able to get into Cheshire.
It is some exercise to think of being taken away so far from my home and family,
and also from my friends and relations in Cheshire.
I would gladly have got down into Cheshire; but I must be content,
however it pleases God to order it.
Worse things have happened in this life to better men than I am.
I shall be missed in America; friends there were troubled when I came away.
I have labored faithfully among them; they will be grieved at the tidings of my death.
My family will miss me.
My care has been for my sons, that they may be kept in the fear of God.
I have been a good example to them.
I have a care upon me, that they may be kept humble while they are young,
that they may bend their necks under the yoke of Christ.
If I am taken away, I am very clear in my spirit.
I have answered the requirings of God; I have been faithful in my day,
and I have nothing that troubles my spirit; my spirit is very clear.`'
He also expressed his concern for his brethren in the ministry, especially the young,
that they might observe the leadings of God`'s spirit in their ministry,
and not lean upon their own natural parts, which, he said,
occasioned various inconveniences;
of which he spoke particularly in the time of his sickness.

After this, the Lord answered his desire, that he recovered,
so as to be able to get down to Cheshire to his relations there;
and he got abroad to some meetings that winter, but yet was weakly in body; and,
towards the spring, he made preparation to get home to his family in Pennsylvania;
but before the ship set sail, his distemper, which had not quite left him,
returned sorely upon him.
He went to his sister`'s, near where he was born,
and she spoke something to him about his family; but he said little,
only these words; '`If it be the will of God that I be taken away now,
I am well content;`' which was the most he said in his last illness,
save to a Friend concerning his burial.

He departed in much quietness of mind, the 12th of the Twelfth month, in the year 1696,
and was buried the 15th of the same, in Friends`' burying-place, in Cheshire,
aged sixty-three years: having been a public minister forty-two years.

[.asterism]
'''

HENRY STOUT, of Hertford, born at Ware, in the county of Hertford, in the year 1631,
was convinced of the blessed truth by the ministry of a woman, in the year 1655,
being then about the twenty-fourth year of his age.
At which time some of the people called Quakers came into that part of the county,
concerning whom he had heard evil reports, and that they denied the Scriptures;
which had prejudiced his mind against them.
But it so happened that there came a woman called a Quaker, and preached in Ware market;
and afterwards a rude rabble followed her down the street, and he seeing them,
followed her also, in pity towards her, and to rescue her from them.
But she turned into a house where there was a meeting; and a Friend was speaking there,
unto whom he listened, and heard him speak much Scripture,
although he named neither chapter nor verse; at which he wondered,
because he had heard that they denied the Scriptures.

After he thus lent an ear, the woman stood up and spoke;
and such a power attended her ministry, that his spirit was much broken,
and astonishment seized on him; and he saw others also with paleness of face,
and they smote their hands.
This brought great fear upon him, lest he should be deceived;
yet was he afraid also that he should offend God, and resist the day of his visitation.
This brought great sorrow upon him for a time, he not being able to distinguish;
but afterwards going to another meeting, he heard another woman,
by whose preaching his convincement was increased; and he was so confirmed,
that he could set to his seal that it was the very
truth which had long been veiled in him;
but now, by the preaching of the gospel, was revealed.
He could say, Christ was come, and he looked not for another;
and it was confirmed by the work that was wrought both within and without.
First, within, the eye which had been shut was now opened,
and the ear that had been deaf, now heard, and the mouth of the dumb could speak,
and the lame could walk, and the mysteries of the kingdom of God were known,
which before were in parables.

He searched the Holy Scriptures, and found it was the good old way,
though new to him and others;
and the Scriptures were opened by the spirit that gave them forth,
and a witness for God he had in himself, according to 1 John 5:10. "`He that believes,
has the witness in himself.`"
Then he took up the cross and denied himself, and so became a gazing stock to the world,
as the Lord`'s people were in those days, as well as in former ages.
Soon after he was moved of the Lord to go to the public places of worship,
to declare against them, and to preach the truth.
Persecution and sufferings soon followed;
for many and various were the trials and exercises which
the Lord`'s people went through in their day.

He was the first called a Quaker who suffered imprisonment in Hertford jail,
for the testimony to the truth; where his sufferings were great,
the prison-windows being shut, that he might not have the benefit of the air,
or the light of the day.
After he was released of that imprisonment,
he was a prisoner five times more in that town of Hertford;
the last of which he was sentenced for banishment,
and continued a prisoner nearly eight years, to the great detriment of his health,
being often put into the common jail;
which trials the Lord carried him through with much patience,
contentedness and quietness of mind, he being given up to the will of God.

He was a serviceable man in many respects,
and willing to do what offices of love he could for any.
He travelled pretty much in the service of truth in his younger years,
while he had strength of body, but some time before his death, distempers grew,
and weakness increased upon him, which made him incapable of being much from home.

The last four months before his death, he went little abroad, but grew weaker and weaker;
the which his wife perceiving, did much importune him to advise with some doctor;
but he answered her thus, '`I would not have you confide too much in doctors,
for they will all prove physicians of no value to me.
I thank God, I know that power which in former ages raised the dead,
and healed all diseases; and if it is the will of God, he can restore and heal me;
if not, I am satisfied; his will be done.`'

His greatest infirmity was a stoppage at his stomach, and shortness of breath,
which often brought faintings upon him; but he bore all with great patience.
And when some friends came to visit him,
he told them his weakness was such that he thought he should hardly recover it;
but however it pleased God to order it, he was fully satisfied:
for he had this testimony, that he had served the Lord with faithfulness,
and with an upright heart, to the best of his knowledge: with more to that effect,
which cannot be well remembered.
At another time to a friend that came to see him, he said,
'`None know the virtue and goodness of truth so well
as when they draw near their latter end,
when all outward comforts fail, and are leaving them,
and sickness and weakness come upon them.`'

He further said that he had travelled in the service of truth in former years,
when he had strength of body,
and the Lord had given him many living testimonies to bear for his name;
in all which he was faithful, and the remembrance of it warmed his heart at that time;
for he could say that his care was,
not to speak more than what the Lord gave him to speak,
that thereby his name might be honored.
Many times, and upon several occasions, he so expressed himself,
as fully manifested the true satisfaction and peace he had with the Lord;
often desiring to be dissolved, that he might go home to his rest.

The Lord`'s love and gentle dealing appeared very largely towards him,
in giving him many times ease of body, and comfortable seasons of refreshment;
and he generally rested well in the night, till about a week before his death.
The sense of it would often make him break forth
into praises and thanksgiving to the Lord,
for his goodness and mercy to him in the night-season.
When he awaked out of his sleep, and when his sleep was taken from him,
he continued quiet, patient, and sensible to the last moment.
And when his wife saw that he slept little, and took little,
hardly enough to keep him alive, she was full of grief; which he perceiving, said to her,
'`You must give me up, for I shall not long continue here:
but it will not be long before you and I shall meet again in that blessed state,
where all tears shall be wiped from our eyes.`'

He kept his bed but four days; and the day before his death, his children being by him,
he said to them, '`You, who are likely to enjoy what I have,
I would have you to remember the advice of your father when I am gone,
and live in the fear of God, and as it becomes the truth; then you will be as monuments,
when I am gone, and it will go well with you, and what I leave will be a blessing to you.
Beware of earthly-mindedness, and pride, and prodigality,
which is a dishonor to any family; and bring up your children in plainness,
and not in the fashions and superfluities of the world, which passes away.
Remember my advice, who speak to you in love: for woe will be to the wicked.
I would say more to you, but my strength fails.`'

The day he died he spoke little, but lay as if he slept;
but sometimes fainting fits would come,
that it was thought he would have gone away in one of them; but he did not,
but fell into a slumbering; and when he awaked,
he desired to be turned on the other side, and then he stretched out his hands and feet,
and said, '`Now I am going to the Lord;`' which were the last words he spoke:
and so departed in peace, without so much as a groan or sigh.

Thus he finished his course, and laid down his body, the 6th of the Tenth month,
in the year 1695, in the sixty-fifth year of his age.

[.asterism]
'''

THOMAS ALDAM, of Warnsworth, in Yorkshire,
received the glad tidings of the gospel of life and salvation very early, that is,
in the year 1651, by the preaching of that eminent and faithful servant of Christ Jesus,
George Fox, soon after he was delivered out of the dungeon in Derby prison.
At this time, Thomas Aldam, John Kellam, Thomas Kellam, Richard Farnsworth,
Thomas Goodyear, and several others of note, received the truth; and many sufferings,
beatings, reproaches, spoiling of goods, and imprisonments he endured,
for Christ`'s sake and the gospel`'s; being often concerned to go into marketplaces,
and public places of worship, bearing testimony against the wickedness of the world,
and against such teachers and leaders as caused them to err, through lightness, pride,
and covetousness.

Before he was convinced,
he was a great follower of the priests and teachers of those times,
but his hungering and thirsty soul not being satisfied among them, he left them,
and waited as alone, until it pleased the Lord to send his servant George Fox,
as aforesaid, into those parts of the country.
And he having received the truth, was valiant for the same upon earth,
and gave up his strength and substance to serve the Lord.
He was very zealous and fervent in spirit, severe against evil,
but tender to the least appearance of that which was good,
watching over his children in the fear of God; given to charity, and to do good to all.

He was one of the first called a Quaker,
who was imprisoned in York Castle upon that account, in the year 1652.
It was for going to Warnsworth steeple-house, and speaking to Thomas Rookbey,
a priest of that place, who procured his imprisonment at York,
where he was kept two years and six months so close,
that he was not permitted once to come home, nor to see any of his children;
and sometimes not permitted to see his wife and relations when they went to visit him.
He was also fined during that imprisonment 40, at the assizes,
for appearing before the judge with his hat on his head,
and for speaking thee and thou to him.

During the aforesaid imprisonment, his adversary Rookbey, the priest, and one Vincent,
an impropriator, sued him at the law for treble damages,
and they made spoil of his goods to the value of 42;
not leaving one cow to give milk for his young children and family.
Thus he suffered for his faithful testimony to the
coming of the Lord Jesus Christ in the flesh,
and for his free ministry;
at other times also he suffered the loss of goods for his testimony to the truth.

As he had been a sufferer himself, so he had a tender sympathy for the Lord`'s people,
his brethren, who were sufferers for the truth,
and would go oftentimes to Oliver Cromwell, and others, the rulers of those times,
and lay the sufferings of Friends before them.

He also travelled into Scotland and Ireland,
and went to the chief rulers there upon the same account.
He went to all, or most of the prisons in England,
where there were any of the people called Quakers,
to take a perfect account of their sufferings,
that he might be the more capable to advocate their cases before the government,
being ready at assizes, sessions, or elsewhere, to plead the cause of God`'s people.

He had a tender regard to love and unity among brethren,
bearing good esteem in his mind for such as labored in the gospel.

When he was about to undertake any journey upon truth`'s account,
he would call his family together,
and in much humility pour out his supplication to God to preserve them.

After thus having served his generation in faithfulness, he was visited with sickness,
in which time he set his house in order; and in the time of his weakness,
the Lord was good to him, and eminently appeared with him, so that he said to his sister,
near his latter end, that he found his strength so renewed,
that he believed he could get to London if the Lord required it: but he answered again,
'`I am clear of the blood of all men.
I find nothing to this man,`' meaning king Charles the Second,
then lately restored to his kingdom.

He was very sensible of his latter end; and the day he died he called for his children,
and exhorted them to live in the fear of God, and to love and obey their mother: and so,
being freely resigned into the hands of God his Creator,
he departed this life in the Fourth month, in the year 1660.

His wife, Mary Aldam, survived him but three months.
She was a woman fearing God, and served him in her generation.
In all the exercises which her husband passed through in those early days,
she never was heard to grudge or repine,
but was given up in all things to God`'s disposing.
Her remembrance is sweet,
and her name to be recorded among the faithful of God`'s people.
She received truth by the ministry of George Fox, at the same time her husband did,
and bore testimony to the same truth, according to her measure.
He had also two sisters, faithful women.

[.asterism]
'''

MARGARET KELLAM, who was convinced about the year 1651,
travelled much in truth`'s service in the breaking-forth thereof,
and many were convinced by her.
She also suffered imprisonment for the same at Exeter, York, and Banbury in Oxfordshire;
and great was the courage that attended her in preaching truth in the streets, markets,
and public places of worship, and to the rulers of the people;
and the Lord was with her.

She finished her course in faith,
signifying before her departure the great peace she enjoyed with the Lord,
and the clearness of conscience she had before him.
And so departed this life in the year 1672.

[.asterism]
'''

JOAN KELLAM was also a woman that truly feared God, and a good example where she dwelt:
she was of sound judgment, and well experienced in the work of the Lord;
zealous for his honor, and faithful to the truth; an encourager of virtue,
and watching over the young, and an instructor of them in the right way of the Lord.
She could speak a word in due season to an afflicted soul,
having passed through many states, and seen the wonders and goodness of the Lord therein;
and was as a mother in Israel.

In the time of her sickness she was well disposed,
and gave good advice to them she left behind her,
that they might persevere in faithfulness,
to the finishing of that work which the Lord had for them to do.
So departed this life in the year 1681.

[.asterism]
'''

SARAH BROWN, wife of Capt.
Brown, of Leicestershire, and mother to Samuel Brown, physician in the town of Leicester,
was one who in her young years fervently and sincerely sought the Lord,
and frequented the assemblies of the best sort of people in that day, called Puritans;
afterwards she joined herself to the Baptists, among whom she walked inoffensively.

But when it pleased God to raise up his people called Quakers,
in the northern parts of this nation,
and gave some of them commission to publish the way of life and salvation,
she received their testimony with great joy and thankfulness
to the Lord and was a nursing mother among that people.
Her husband, at her request, gave up his house for Friends to keep meetings in,
even at the breaking forth of truth in that day:
and she counted nothing too dear to part with for
truth`'s sake and was a good example in conduct,
in temperance, meekness and charity, towards those with whom she was concerned.
She was a true wife and a tender mother, a loving relation,
a good neighbor and firm friend.
She had a word of comfort in due season to many when in afflictions;
she loved to visit the widow and the fatherless, the prisoners,
and the house of mourning; and to feed the hungry, and clothe the naked,
and to wash the saints`' feet.
She suffered imprisonment, and spoiling of goods for the truth`'s sake,
counting all as dross and dung, that she might win Christ.

When death came she received it with contentedness,
being given up to God`'s good will and pleasure, and she lived to old age.

A friend visiting her in her last sickness, said to her,
'`The Lord has sent his messenger`' (meaning, that her end was at hand); she made answer,
'`He is come;`' and desired the Lord to give her an easy passage.
She was first taken ill in the night with a violent pain in her legs,
and her son Samuel Brown being presently called,
she prayed to the Lord to mitigate the violence of her pain,
and to give her strength to bear his hand with patience.
Her son was much grieved for her; which she perceiving, said, '`Child, do not do so;
rejoice and be glad, for you have no other cause.
You have been a dutiful and loving son to me, even to the full.`'
The Lord answered her prayer; and in a short time took away the violence of her pain;
and she praised the Lord, and blessed his name, for his mercies and goodness;
speaking of his great mercy and favor to her all her life long,
to the great comfort of her children about her; and blessed her son, saying,
'`The Lord bless you and yours, for your love and duty to me;
for I do rejoice that you were born unto me.`'
Also to her son`'s wife she said, '`Daughter, you did promise to take care of me,
when weakness should approach; and now you are as good as your word:
the Lord bless you and yours, for all your love to me.`'
And in the sense of the love of the Lord to her she prayed, '`O Lord,
guide your poor hand-maid into your everlasting kingdom,
where I may sing hallelujahs to you forever.`'

She gave order, two days before her departure,
(being sick but six days) to be buried at Leicester, by her grandchildren;
and so died in a good old age, at her son, Samuel Brown`'s, at Leicester,
on the 30th of the Ninth month, in the year 1693, aged eighty-three years.

[.asterism]
'''

WILLIAM WALKER, an inhabitant of Pennsylvania, born in Yorkshire,
but convinced in Pennsylvania,
was one who bore a living testimony to the truth of God in the assemblies of his people.
He came over to visit his friends and brethren in England,
about the latter end of the year 1693, in company with other Friends from those parts,
which was about the time George Keith came over from America.
This our friend often expressed his great sorrow for George Keith,
and the sore exercise and trouble he gave to friends in America,
by his contention and jangling;
and he had a testimony against that spirit but a few days before he died,
that God would judge it.

After he had visited friends about London, he went into several counties,
and also into Wales; and returned to London,
in order to be at the yearly meeting in 1694;
a little before which time he was taken sick there,
and endeavors were used for his recovery, but they proved unsuccessful.
In the time of his sickness he was often filled with
the love and power of God in his soul,
to the comfort of those present.
Observing some to weep, he said, '`Weep not, dear hearts, lest you trouble me.`'
Afterwards he said, '`the goodness of the Lord!`' And lifting up his hands, he said, '`Lord,
you are altogether able to do wonderful things!
You shall be my physician.
Oh the wonders of the Lord!
What have I seen of the transcendent glory!
Though I see but a little, yet it is admirable glory.`'
Again he said, '`The old enemy would have had me let go my hold; but I said,
I have an interest in you, and I will hold you, Lord.`'

Those about him being desirous that he might recover, he said, '`No,
I have no promise of life.`'
Speaking of Christ, he said, '`I can see him; his arm is open to receive me.`'
After some time he said, '`The Lord is a physician indeed, a physician of value.`'
Another time he said, '`We must all double our diligence.`' Another time,
lying in a still frame of mind, he sang in sweet melody as follows:
'`His compassion fails not; he waits to be gracious: Oh the wonders of the Lord!
The wonders of the Lord in the deep.`'
Another time he said, '`My faith is steadfast in the dear Son of God;
that although I am under great weakness and afflictions,
yet in the strength of my Father`'s love I shall be
enabled to stand against the mists of darkness.
The enemy would eagerly unpin my faith:
God`'s people are always preserved while they wait still at home.
Oh! Lord Jesus Christ!
I will hold you fast; your compassion fails not.
Oh! sweet Jesus Christ, I have great cause to hold you fast.
Oh! sweeten death unto me!
Oh! your sweet presence!
In it there is life.
Oh!
Lord, give me strength; I will not let you go: you have regard to them that fear you,
your compassion fails not; you are at my right hand to uphold me.
Oh! my Savior! you are at my right hand to save me; your compassion fails not, O Lord.`'
Afterwards he said, '`Oh!
Lord Jesus!
Come, sweet Jesus, I long for you; now death is pleasant.`'

His wife`'s sister being by him, he said, '`Fear the Lord God.`'
She said, '`Would you +++[+++say]
any thing to your wife.`'
He answered, '`My dear and tender love in the Lord Jesus unto her,
and to all my dear friends everywhere; and that you may double your diligence,
to your soul`'s comfort, the days you have here.
My dear love to our dear friends in America, where I have been sweetly refreshed,
and had many good meetings among them.`'
After a little repose, he said, '`Oh!
Fountain of Life!`' Then stopped, and thus spoke again,
'`I cast the care of my dear wife and children, if living, upon the Lord; I trust in him.`'
After some rest, he said, '`Lord Jesus Christ, come, receive my poor soul: come,
O my soul`'s beloved!
Come, Lord, I long for you.
Lord Jesus Christ, if there be any iniquity in me, search it out.`'

Afterwards he said, '`I feel the angel of your presence to surround me: come,
Lord Jesus Christ, come, come, receive my soul into your bosom.`'
Again he said, '`Come, Lord Jesus Christ, let me entreat you come away,
and receive me out of all sorrow; come away, my Lord.`'
After a little time he said, '`I feel the Fountain of Life; my soul`'s beloved, is come.`'
He died in peace with the Lord, as those then present can testify,
that he was in a sweet, heavenly frame of spirit when he drew his last breath,
which was on the 12th of the Fourth month, in the year 1694, at the house of John Padley,
in Olave`'s Parish, Southwark.
== Chapter 8

[.chapter-synopsis]
* Ruth Middleton
* Alexander Jaffray
* Mary Padley
* Charles Marshall
* Sarah Padley
* William Garton
* Charles Ormston
* John Ormston
* Thomas Robinson
* Stephen Smith
* William Allen
* William Simpson

RUTH MIDDLETON, daughter of Samuel Middleton and Rebecca his wife,
was visited with a consumption in the Tenth month, 1700,
and continued in much weakness of body till the 16th of the Fifth month, 1701.
During her sickness, these expressions, among others, were observed.

One time, her mother being much concerned to part with her,
the child lying still as if she was in a slumber, opened her eyes and said,
'`What`'s the matter?
What`'s the matter?
My dear mother, do not be troubled for me; do not sorrow for me, I shall be happy.
It is the Lord`'s will that I am thus afflicted, and we must be contented.
You know that Abraham was willing to offer up his only son Isaac;
and you do not know if you could freely give me up,
but that the Lord might spare me a little longer to you;
and if it be his good pleasure to take me to himself, his holy name be blessed forever.`'
Another time her mother said, '`How are you now?`'
She replied, '`But indifferent; but I am well satisfied,
for it is the will of God that I am thus afflicted.
Oh! my dear mother, I would be glad if you could freely give me up.`'

One time, going to slumber, she prayed thus: "`Our Father who art in heaven,
hallowed be your name, your kingdom come, your will be done in me,
as it is in heaven.`"'`Oh! sweet Lord Jesus,
feed me daily with the bread that comes down from heaven.
Lord, if it stand with your will, grant that I may sleep to refresh this poor needy body:
but you, Lord, know what I stand in need of, better than I can ask.
Lord, be with me, and my father, and mother, and brother.`'
Thereupon she went to sleep: and when she awoke, she said,
'`Oh! blessed and praised be your holy name,
O Father of life! for you have heard my desires, and have answered me;
for I have slept sweetly.`'

Another time she said, '`The Lord said to his followers,
"`Permit the little children to come unto me, and forbid them not,
for of such is the kingdom of heaven.`"
And if I be not happy, what will become of ungodly men and women?
For truly I am afraid of offending anybody, for fear I should offend the Lord.`'
One time she said, '`Pray, mother, have a strict eye over my brother,
for he is very full of play.`'
A friend, after inquiring how she did, said, '`I hope your eye is still to the Lord:`'
her reply was,
'`Although I can hardly speak, I think upon the Lord,
and he knows my thoughts, and answers them;`' with more sensible words.

Another time she said, '`It will not be long before I shall be at rest and peace,
where there is no more pain to the body nor to the mind;
and where there is nothing but joy forevermore.
Dear mother, be willing to part with me, for I am willing to part with you all.
I am not at all concerned for myself, but for you, poor mother,
who does and will make your bed a bed of tears often for me.`'

Hearing her mother question her recovery, she said, '`Oh! what the Lord pleases;
for I am not afraid of death.
I never wronged anybody of a pin to my knowledge, nor loved to make excuses.
I never told a lie but once; when I should have said yes, I said no:
that has been a great trouble to me; but the Lord, I hope, will forgive me,
for I called the maid, and told her the truth.`'

Near her end she desired to come out of the country to London, and said,
'`The air does me no good, and the doctor does me no good:
the Lord is the same at home as here.`'
And when she was removed home, she said, '`Now I am glad;
if I die it is better to be here, and will save a great deal of trouble.`'

A Friend asked her if she was willing to leave father and mother, and go to the Lord;
after some pause she answered, '`If the Lord please,
I am willing this very minute to leave all, for I shall be happy.`'

The night before her departure, after a Friend had prayed by her, she said,
'`I do understand well, and am inwardly refreshed.
I am sorry that I cannot speak so that the Friend could hear,
or else I would give an account of my inward peace with the Lord.`'

A few hours before her death she thus prayed, but her voice was very low: '`Oh,
Lord! withhold not your tender mercies from me at the hour of death.
Oh, Lord! let your lovingkindness continually preserve me.`'
Afterwards she said, '`I desire to slumber; but if I die before I wake,
I desire the Lord may receive my soul.`'

She was thankful for the tender regard her mother had to her, and with a low voice said,
'`Farewell, dear mother; in the love of the Lord, farewell.`'
And then desired to see her father and brother; and feeling for her brother`'s face,
she stroked him and said, '`Farewell, be a good boy.`'

Her father asking her how it was with her, she replied, '`am just spent,
but I am very easy, and shall be very happy. My body is full of pain,
but the angel of the Lord is with me,
and his presence will forever preserve me;`' and so kissed her relations,
and bade them all farewell.

Her last words were her desire to be remembered to
the Friends who visited her in her sickness;
and, in less than half a quarter of an hour, like a lamb she departed this life,
on the 16th of the Fifth month, in the year 1701, being eleven years, two months,
and four days old.

[.asterism]
'''

ALEXANDER JAFFRAY, of Kingswell, in the north of Scotland, born in the city of Aberdeen,
was one who early remembered his Creator;
and as he grew in years he increased in a religious concern towards God,
and those who he thought feared him.
He joined, when young, with the Presbyterians,
though he was educated in another form of religion; but some time after,
when those people got into rule and government,
they forgot their former low and persecuted condition, and grew high, rigid,
and fierce persecutors of others; therefore he soon disliked them,
and signified the same to some of the chiefest among them,
having been himself one of those commissioners who were deputed by the
nation of Scotland to treat on articles with King Charles the Second,
then in Holland, in the year 1650.

After he left the Presbyterian way, for some time he was among the Independents,
and finding them also to be for setting up themselves, and persecuting others,
he could no longer follow them.
After this he remained in private for some years, a solitary mourner,
not joining with any profession in religion;
nor allowing several of his children to be sprinkled or baptized (as they called it),
because he could not own their way of constituting national churches;
and this was long before he was called a Quaker.
In his solitary retirement he sought the Lord,
waiting for a people who were spiritually touched with a divine coal from the altar,
to kindle true and spiritual sacrifices to God.

When he first heard that God had raised up such a people in England,
who directed all to God`'s pure light, spirit and grace in their own hearts,
as the most sure teacher and leader into all truth, worship and religion,
he said he felt his heart to leap within him for joy.
After weighty examination concerning the people called Quakers,
who preached the truth among them, he found his heart and soul united to them.
This was in the year 1662,
a time when it was as bitter a cross even as death to own them,
especially to one of his repute; and shortly after, several more men of note,
in that nation, were convinced of the same way of truth,
as John Swinton in the southern parts, David Barclay, Alexander Skein, Thomas Mercer,
and others.

This made the priests and others persecute them; but they stood their ground,
through the grace of God, and boldly bore their testimony valiantly,
particularly Alexander Jaffray,
contending for the truth in solemn conferences with the bishop of Aberdeen,
and the chief preachers of that city.

He was faithful in his testimony to the truth to the last;
and in his sickly old age was imprisoned many miles from his own house,
for non-payment of tithes.
It is remarkable that, a little before this imprisonment, being near to death,
as was judged by all who saw him, he signified under his hand,
being altogether unable to speak, by a great swelling in his throat,
that his God had yet a service for him to do, in suffering for his precious truth;
and that he was not to die at that time.

He was taken sick the latter end of the Fourth month, 1673;
and during the twelve days of his sickness,
he uttered many living testimonies to the blessed truth, before many witnesses,
both Friends and other people, who visited him; and a few of them are as follows:

He said that "`it was his great joy and comfort in that hour,
that ever he had been counted worthy to bear a testimony to, and suffer for,
that precious testimony of Christ Jesus,
his inward appearance in the hearts of the children of men, visiting all by his light,
grace and spirit, that convinces of sin; and that it was,
and would be the great judgment and condemnation of many in this nation,
particularly of the professors, that they have so slighted and despised, yes,
hated the said light and witnesses thereunto.`"

Sometimes being overcome in spirit, he said, '`Now Lord, let your servant depart in peace,
for my eyes spiritually have seen, my heart has felt, and is feeling,
and shall ever feel, your salvation.`'

He also prophesied of a great and near trial shortly to come,
wherein some that were not what they seemed to be, should be discovered and fall;
but the upright and lowly ones, the lowly shrubs should be preserved,
when tall and sturdy oaks should be overthrown; which is since fulfilled upon some.

He farther said, that the Lord had given him the garments of praise,
instead of the spirit of heaviness.
Sometimes, when very sick, he would bless the Lord,
that now fighting with a natural death, he had not an angry God to deal with.
'`Oh!`' says he, '`the sting of death is fully gone, and death is mine;
being reconciled to me as a sweet passage, through him that loved me.`'
Another time, seeing the candle almost out, he said, '`My natural life is near an end,
like that candle, for lack of nourishment or matter to entertain it;
but in this we shall differ, that if it be let alone, that goes out with a stink,
and I shall go out with a good savor, praises to my God forever.`'

A little before his breath ceased, he said he had been with his God,
and had seen deep things;
about which time he was filled with the power of God in a wonderful manner,
which much affected those present, and in a little time after, he died like a lamb,
being the 6th day of the Fifth month, in the year 1673, aged fifty-nine years;
and was buried in a piece of ground set apart near his own house at Kingswell,
the 8th of the same month.

[.asterism]
'''

MARY PADLEY, wife of John Padley, timber-merchant, of Olave`'s, Southwark,
was a woman adorned with truth and innocency, chaste, upright, and sincere-hearted,
industrious, yet void of covetousness, so that virtue shone forth in her conduct.
She was also charitable to the poor, plain in apparel, adorning the truth in her conduct,
punctual in performing her promise, and in the discharge of any trust reposed in her.
She spent her days in the fear of God, so the Lord was gracious to her at her death.

She was taken with pains, the 6th of the Seventh month, 1695, at which time she said,
in much tenderness and fervency of spirit, '`My God, and my father, deliver me.`'
And after she was delivered, she praised God for his mercies towards her:
and afterwards being asked by her husband how she did,
finding some unusual symptoms attend her, she answered, '`Weak, but well satisfied.`'
And as a confirmation thereof, she broke forth into sweet praises to the Lord; and died,
leaving behind her four young children.
Aged about twenty-eight years.

[.asterism]
'''

CHARLES MARSHALL, born at Bristol in the year 1637,
was religiously educated by his parents in the Independent way.
In his tender years he had inward desires after the knowledge of God.

After he had continued some years among the Independents, and also the Baptists,
he grew more and more dissatisfied with the empty and lifeless
profession of those among whom he walked.
He spent much time in retirement alone in the fields,
under a sense of his state and condition, crying unto the Lord,
and seeking after his saving knowledge.
In this state he continued,
until it pleased God to send to that city his faithful servant John Audland,
from out of the north of England,
by whose powerful ministry he was turned to the light of Christ Jesus in his own heart,
which had before discovered his state and condition to him.
After he came to turn in his mind to the light of the Lord,
and was thereby and therein resigned, he witnessed God`'s pure power,
love and life to break in upon him; and after manifold exercises and troubles,
was raised up a powerful minister of Christ Jesus,
and an instrument in God`'s hand to turn many to righteousness.

He was moved in the year 1670 to go through the nation of England,
and visit God`'s heritage, which he did within the compass of one year;
and although it was then a time of great persecution,
yet in all his passage through cities, towns, and all the counties of the land,
no man was allowed to lay hands on him, or stop his way.

He continued a faithful minister,
and labored much in the gospel to the time of his sickness, which lasted several months;
in all which time great patience and meekness appeared in him,
although under weakness and affliction of body.

He had some sight and knowledge of his end;
for a little before he was taken ill he earnestly pressed
a particular friend of his to ride out of town with him,
having something of moment to impart to him.
When they were a few miles from London, he said, among other things,
that he was satisfied his departure drew near,
and therefore had a desire to discourse with him
about some particular things before he died.
And when he was taken ill he sent for the same friend,
and told him now he was satisfied he should go abroad no more;
although in his first illness there was no such appearance to others,
which the said friend told him; but whatsoever he said to take him off of such thoughts,
it had no impression upon him; he continued fixed in his mind,
that he should die of that illness.

Several of his friends pressed him to go into the country,
but he desired only to go to John Padley`'s, a Friend that dwelt near the river side,
which he much liked; and at his first going there he was a little better,
but soon altered again.
He lay ill there about three months, under great weakness;
and several Friends often came to see him,
and he would be frequently giving them seasonable counsel and advice,
in many heavenly expressions, and would often exhort them to keep in love and unity,
and to the living divine power and life of truth,
that thereby they might be kept a people fresh and green, and living to God,
that so formality might not prevail over them.
He pressed that a great regard might be had of the poor,
and that some way might be found out for their employment; often saying to this effect,
that in an inexpressible manner he felt their sufferings, by reason of their poverty.
Indeed he was a man who greatly sympathized with
those who were afflicted either in body or mind,
being of a very tender spirit.

A little before his departure, he sending for John Padley and his wife into his chamber,
said to him, '`Dear John, do what you can for the honor of truth,
and the Lord bless you and yours for generations to come.`'
To his wife he said that he desired the Lord might be with
her when she came to such a time as that he was then in,
i.e., a deathbed, and make her passage easy; and his desire was granted,
for she died in less than a year after; and said, on her dying bed,
that the Lord had answered dear Charles Marshall`'s request, for she lay very easy,
and freely given up.
As he lay in this weak condition he was often opening his mind to several of his friends;
particularly when several ministering Friends came to see him, he spoke to this effect:
'`I have loved the brotherhood;
I have sought the unity and peace of the churches for these forty years,
and to my great comfort I never did any thing tending to the breach thereof.
I have two things that lie upon me to Friends,
which I desire may be communicated to them.`'

'`The first is,
that they gather down into the immortal Seed and Word of life in themselves,
and be exercised in it before the Lord,
and duly prize and set a value upon the many outward and inward mercies, and blessings,
and heavenly visitations, that the Lord has eminently bestowed upon them,
since the morning of the day of his blessed visitation;
then shall they grow and be preserved in a living freshness to him:
and the Lord will continue his mercies to them,
and they shall not lack his divine refreshing presence
in their meetings together before him.

'`The second thing is, that those Friends to whom the Lord has given great estates,
ought to cast their bread upon the waters, and do good therewith in their lifetime;
for those who are enjoyers of such things should see that they are good stewards thereof.
Oh! the many poor families that such persons might be a help to! how easily might they,
with a little,
assist many a family to live in the world! and what a comfort would it
be for such to see the fruits of their charity in their lifetime.`'

When our friend George Whitehead came to see him, with much tenderness of spirit,
he signified his great peace and satisfaction, and that he always, from the first,
had an honorable esteem of the unity of his brethren.
A little before his departure,
when our friend William Penn and several others visited him,
he lay as a man gathered up in his spirit unto God; and though he was almost spent,
his voice being very low, hardly to be heard, yet by what was understood,
it might be perceived that he had in possession the earnest of
that blessed peace which he was going to receive the fulness of.
The observation of his peace, and happy condition, much affected those present.
He departed like a child, in a quiet frame of spirit, the 15th of the Ninth month,
in the year 1698, aged sixty-one years,
and was buried from Grace-church-street meetinghouse, in Friends`' burial ground,
near Bunhill-fields, London.

[.asterism]
'''

SARAH PADLEY, second wife of John Padley, aforesaid, of Olave`'s, Southwark,
was a woman of a meek and quiet spirit, and had great sympathy with those in affliction;
and bore a public testimony for God in the assemblies of his people,
and she had an honorable esteem of the faithful elders in the church.

She was taken ill the 26th day of the Fifth month, 1699,
and was sensible her end was near, and on that account was concerned for her husband.
The love of God, with which she was filled, caused her sweetly to praise his name,
so that the sense of the pains and weakness of her body seemed to be taken away.
One time, in the sense of the love of God to her soul, she cried out, "`Oh! death,
where is your sting?`"
Often praying and praising God,
and during the whole time of her sickness she was freely given up to die.

A few days before her departure she said to her husband,
'`You are the dearest of any thing in the world to me; yet I can freely leave you.`'
Another time she said to him,
'`The Lord has answered dear Charles Marshall`'s prayer for me;`' remembering that C. M.,
who died at her house, had desired, upon his dying-bed,
that she might have an easy passage when she came to such a time as he was in; '`for,`'
said she, '`I am very easy;`' and often said that she was resigned to the will of God.

A little before her death,
much through her husband`'s great affection to her and his earnest desire of her life,
she seemed a little to desire life, but presently checked herself for it,
and returned to her former resignation of spirit;
and so lay supplicating and praising God, so that a neighbor present,
not called a Quaker, said that she never saw any lie so sweetly in all her life.
Seeing some about her weep, she said, '`Do not cry for me, for I am going to my rest.`'
A friend said, '`Are you willing to leave your husband?`'
She answered, '`I have often told him I am willing to go when the Lord pleases:`'
and in a little time after she said, '`In a few days, in a few days, they will say,
Sarah Padley is dead.`'
It much affected those about her to see how reconciled she was to death,
speaking very pleasantly concerning it,
and of the felicity that would accrue to her thereby.
She finished her course on the 8th day of the Sixth month, in the year 1699,
aged about thirty-four years.

[.asterism]
'''

WILLIAM GARTON, of Ifield, in the county of Sussex, was an early fruit to God,
a faithful believer in his blessed truth, and a servant in the church of Christ.
He was zealous against all unrighteousness,
and much for the unity of the spirit in the bond of peace among brethren;
an elder indeed, watching for good over the flock, a sympathizer with the afflicted,
and a mourner in the house of mourning, more in deed than in words.
Though but a plain man,
yet God endowed him with a large understanding and sound judgment,
which has been approved in difficult cases.

He was firm and constant in spirit in times of suffering and persecution,
preferring the service of truth, and the testimony of it, before all worldly things.
He was an example of virtue in the church, also in his family;
and his removal hence was a great loss to both; a true loving husband and tender father.
He had a great care that his children might be trained up in the fear of God,
and knowledge of his blessed truth;
which labor God was pleased to answer to his satisfaction.
He would often say,
the greatest portion he desired of the Lord for his children was the blessed truth,
and that they might love, fear, and serve the Lord,
and then he did not doubt that they would lack any good thing;
and to that end he would often be giving them good counsel and admonition.

Two days before his decease, being visited by a friend,
he said that he had always endeavored +++[+++to promote]
the prosperity of truth to the best of his understanding;
and that he had nothing of trouble upon him;
but did bless God that he had an opportunity to give this testimony to those present;
exhorting an ancient friend to keep low in God`'s fear, and make straight steps,
that he might lay down his grey hairs in peace.

Another time, several Friends coming from a meeting to visit him,
he desired that his love might be remembered to all Friends.

Another time he said, '`I have always sought the peace of the church,
according to my ability.`'
Being asked by a young man that watched with him how he did, he replied,
'`I am the better to see young men come up in the truth.`'

A friendly person coming to see him on his sick-bed, he put out his hand to him, saying,
'`Ah! you lack something: these are serious times.`'

Two ministering Friends visiting him the day before he died, he seemed very much revived,
and said, '`I never did any thing against the truth knowingly, since I was convinced.`'

One taking his leave of him, hoping for his recovery, he replied,
'`If it be the Lord`'s will, let me go in peace:
'`he also said that he felt the Lord to come in upon his spirit.
Near his end he prayed for his wife, and children, and grandchildren,
that God would make up the loss of him to them.
He further said, '`Oh Lord, I pray you, remember the ancients,
that they may still hold on their way; and, oh! my God, if it stand with your will,
visit more and more those who are not of your fold, and bring them in by your arm,
that they may come to know rest for their souls,
that at the last we may be bound up together in the bundle of life;`'
and so concluded with hymns and praises unto God.

Another time, after some friends had prayed by him, which was to his great satisfaction,
and the room being clear of company, he said to his daughter who was standing by,
'`Oh dear child, I have known much of the goodness of the Lord,
but not in such a large manner before as now: the very fountain is open,
and the love of God is over all; praises, praises to the Lord.`'
He uttered many heavenly expressions, and gave good exhortation to those about him,
which are not here inserted.
A little time before he died, he called for his relations, embraced his wife in his arms,
and took his last leave of her, and of his son and daughter;
holding out his hand and taking leave of all Friends who came to see him,
till his strength failed; and so sweetly died in the Lord, in an honorable good old age,
the 8th day of the Seventh month, in the year 1701,
being the sixty-sixth year of his age.

[.asterism]
'''

CHARLES ORMSTON, merchant at Kelso, in Scotland,
was convinced of the blessed truth about the year 1665.
He was a good example and pattern of godliness,
which he showed forth in the upright life and conduct he had among men,
and bore a faithful testimony among the Friends of that meeting to which he belonged,
and at whose house the meeting was kept to his dying day.

He was in the year 1668 cast into Edinburgh prison,
upon the account of his owning those people called, in scorn, Quakers.
He remained prisoner about twenty-two months; and his wife,
who was not at that time called a Quaker,
having several times made application to the privy council for his release,
did at length obtain an order for the same on the 20th of the Twelfth month, 1669.
Afterwards, Friends settling their meeting at his house, the earl of Roxburgh,
whose lodging was hard by, being angry that it should be so near by,
caused the town-militia to be raised, and by force hauled Friends out of their meeting,
and laid several of them up in prison, among whom C. Ormston was one.
His adversary at length perceiving that neither keeping them out of their meeting-room,
nor yet locking up his doors, would hinder them to meet under the pillars of the house,
gave over his persecution.

This our friend fell sick about the latter end of the year 1684,
and continued to grow weaker for about two months time.
Having before put his outward affairs in order,
and feeling himself very weak and nigh his end, upon the 21st of the Twelfth month, 1684,
in the evening, he called for his two sons,
(his daughters not professing truth) the elder whereof came to him,
whom he took by the hand, and exhorted him to a faithful walking in the truth,
as he had formerly done, and instructed them in many things.
About three quarters of an hour after, he fell asleep in the Lord,
having left a good savor of his upright life and conduct behind him.

[.asterism]
'''

JOHN ORMSTON, eldest son to the aforesaid Charles Ormston,
was an example of sobriety and godliness, having from a child shunned evil;
and when he was mocked for refusing to bear company with others in their vain recreations,
he bore it patiently, not reviling again.
He was given to retirement, and a careful instructor of his younger brother.
He was much troubled with bleeding, which brought him into a consumption,
and he told those about him he did believe he should die.
Being near his end, he desired his father to pray by him, which he did;
and about three or four days before he died,
he inquired of his sisters the day of the month, which being told him, he answered,
'`The twenty-second shall be my day;`' which proved true,
for upon the 22nd of the Tenth month, in the year 1682, he departed this life,
and entered into that blessed rest prepared for the faithful.
Aged twenty years and four months.

[.asterism]
'''

THOMAS ROBINSON, of Bridge-end, near Kelso, in Scotland,
was convinced of the truth about the year 1669, in which he walked circumspectly,
in a good conduct, to his latter end, being a good example in the place where he lived;
and often exhorted his friends and brethren, in the meeting to which he belonged,
to faithfulness.

He was several times imprisoned about the years 1672
and 1673 for meeting with the people called Quakers,
to worship God.
After having lived to a good old age, it pleased the Lord to visit him with sickness,
which continued about twelve days, in which time he was kept in patience,
and often signified that he felt the love of the Lord in his soul;
and exhorted his neighbors and relations, who came to see him,
to fear the Lord and to turn to him, while they had time.
Many more seasonable expressions he spoke, even when he was in great pain,
which much affected the standers by; to whom he said,
'`Let patience have its perfect work:`'
he also signified that being walking one evening by himself, as his manner was,
he prayed fervently to the Lord that he might have
a seal of his assurance before his departure;
and immediately he was filled with great joy, and the word of the Lord came to him,
saying, '`Is not my grace sufficient for you?
That is done already: your peace is made.`'

A little before he departed some of his children, with others, being present,
and he being about to take his last leave of them, said,
'`Humble your hearts before the Lord, and make use of your time,
and slip no opportunity of making your peace with God.`'
At last, recommending his spirit into the hands of the Lord Jesus Christ,
he sweetly laid down his head in peace upon the 28th of the Ninth month,
in the year 1698, being about the seventy-third year of his age.

[.asterism]
'''

THOMAS ROBINSON, son of the before mentioned Thomas Robinson,
was convinced of the truth about three years before his parents,
when he was about thirteen years of age, and but few Friends in those parts;
and he was so effectually converted, that although many endeavors were used,
both by promises and threatenings, they were not able to overturn his faith.

He was a youth of a sober and religious conduct, insomuch that he was a wonder to many;
and by his faithfulness to the truth, though a child,
he was very instrumental to the convincement of his parents,
who afterwards lived and died in the same faith.
Many disputes he had with priests and others, and was so furnished with arguments,
that they were often astonished at him.

About the twentieth year of his age,
God was pleased to call him to the work of the ministry;
at which time he was concerned to go to public places of worship,
and bear testimony to the people against their evil deeds.
His ministry was living, and he had a clear discerning of the spirit of antichrist,
that secretly worked for the hurt of God`'s heritage,
which he advised friends to watch against.

He travelled through the northern counties of England,
and also visited all the meetings of Friends in his own nation,
and had several sights of things to come, some of which he saw come to pass;
and also had a vision of his own death two years before he died.
He was visited with sickness, which continued about seventeen weeks,
and in all that time he was not heard to repine, or speak frowardly,
though his sickness was attended with much exercise.
Many times he sung praises to the Lord, to the affecting of others who heard him;
and declared that he valued not the pains and trouble
of his body if it was the Lord`'s will so to try him;
but that the Lord`'s everlasting truth might be raised over all;
and all lets and hindrances be taken out of the way,
and he to feel preservation in the truth, to the end of his days.
With many more good expressions.

The night before he died, he entreated his parents not to repine at the Lord`'s doing,
saying it was his will to remove him from the evil to come.
After a little silence his father asked him if he
had any thing more upon his mind to say;
he answered, '`Little more, but that all might be kept faithful who profess the truth,
the precious truth.`'
And farther said, '`Let me rest, I have done, I have done;`' and fell asleep,
and slept till about break of day,
and then departed this life on the 2nd of the Eighth month, in the year 1678,
about the twenty-third year of his age.

[.asterism]
'''

STEPHEN SMITH was born the 19th of the Seventh month, 1623.
He received the truth in the love of it in the year 1665,
and gave up to obey and walk therein.
He truly loved God`'s faithful messengers and people,
how despised and suffering soever they were; and he suffered with them,
both in person and estate, by imprisonment and spoil of goods,
for his tender conscience and testimony on behalf of Christ Jesus.

He was a man fearing God, and of good report in that county,
being an exemplary preacher of righteousness in his conduct,
and one truly kind and ready to do good in his day.
God also endued him with a living ministry and experimental
testimony to tell of his goodness,
and speak of his praise to others, from an inward sense thereof in himself,
and to the comfort and encouragement of many who heard.
He travelled in many parts of the nation, in the work and service of God,
in the gospel of his Son.

In the time of his sickness, when he was in the greatest extremity of weakness,
he often declared of the lovingkindness of the Lord God,
by which he was upheld above the fear of death.

To several who came to visit him on his sick-bed, he said,
it was a blessed and heavenly thing to have the mind clear and holy,
free from all troubles and cumbers of this world, as he said his mind was,
having all given up to the will of the Lord, that it might be truly done on earth,
as it is in heaven; adding,
'`O what a blessed and heavenly habitation is this for the soul of man to rest in,
which I have a full assurance of!`' At another time,
one who came to see him he exhorted to dread and fear the Lord God, and to repent of all,
whatsoever that holy and pure witness in his conscience makes manifest to be evil,
if happily he might find mercy with the Lord; which will be better to you (said he),
than all the world besides.
A little after came into the chamber another person,
and the power of the Lord being with him, he was refreshed in his spirit,
and he desired the said person to fear the Lord,
that thereby she might be preserved out of all evil; and added,
'`Love the truth above all, for the truth is a very precious thing;
and be sure keep low and humble to it,
and be not high-minded nor exalted above the pure witness of God in your conscience,
for that would be hurtful.`'

Another time, in remembrance of the tender dealings of the Lord to him,
he said to his sons, who were present, '`My days are very near drawing to an end;
and though my father and mother cast me off when I was a little lad,
the Lord has always preserved me, and his blessings did always attend me,
having been often in many great dangers, both by sea and land.
Having my mind sober and chaste to God,
and having the fear of the Lord placed in my heart, by which I was preserved out of evil,
I did the thing that was right in the sight of the Lord,
so that I found favor of the Lord, and gained the love and favor of people,
in dealing justly and truly with all people, not wronging any man.`'
This he gave in charge to his sons,
that they might always be kept sober and chaste in their minds,
having always regard to the fear of the Lord placed in their hearts,
that thereby they might be preserved out of evil,
doing always that which is just and right;
and to be sure to be courteous and kind to all, loving the good in all,
and bearing their testimony against the evil in all, wheresoever it did appear.

He farther said, '`And whensoever you go about that which is weighty,
take counsel of good and sound Friends,
so that all things may be done to the glory and honor of the Lord and his blessed truth,
in which your blessings are all yes and amen.`'
He moreover advised his sons, saying, '`Do not run into the cumbers of the world,
but wait upon the Lord, and he will find out a way for you in his time;
for the Lord is calling, and taking me out and from all troubles and cumbers,
and from the evil that is coming upon this wicked world, in a good time,
wherein I am assured of that sound and perfect peace,
wherein my soul will rest with the Lord forever; so that I have no more to do now,
but desire the Lord to make my passage easy to my heavenly rest.`'

A little before his departure, being filled with the spirit,
he praised and magnified God, and prayed, saying, '`Lord, and dearest God,
oh! assist in this heavenly passage from death to life;`' and soon after said,
'`Now I am going into my sweet sleep;`' and immediately and innocently
laid down his head in perfect peace with the Lord,
the 22nd of the Seventh month, in the year 1678, at his house, near Guildford, in Surrey,
aged fifty-five years and three days.

[.asterism]
'''

WILLIAM ALLEN, of Earls Colne, in the county of Essex,
received the blessed truth in the year 1654,
and the power of the Lord made a speedy change in him.
Soon after, he had a dispensation of the gospel of Christ Jesus given to him from God,
and he was stirred up with zeal in his soul against the false ways, worships,
superstitions, and profaneness of those times;
which zeal for God produced living testimonies from him,
in many towns and places where he travelled, against those things which were evil,
which sometimes occasioned him to come under hard sufferings, bonds and imprisonments.
In these he behaved himself as a faithful and courageous soldier of Christ Jesus,
and a good example to his fellow-sufferers, preaching the gospel of peace,
both in life and doctrine, and stopped the mouths of gainsayers.
This had a sweet and comfortable effect upon many,
who were reached in their consciences by his testimony and ministry,
and by his innocent conduct;
so that they embraced the truth he preached and suffered for,
and became heirs of the salvation of God, to their everlasting comfort,
and the furtherance of the gospel.

He was of severe carriage to such as made profession of truth,
and walked not with a straight foot in the gospel;
but he was very tender over all such as were young,
and under exercise about their inward condition,
and sometimes spoke effectually to their conditions,
to the easing of their afflicted spirits.

He was an example in the county where he lived,
encouraging Friends to observe the good order of the truth,
and to keep the gospel void of offense; not exalting himself above his brethren,
but carried a good respect to them, and to their counsel and judgment.

He served the Lord Jesus Christ, and his church and people,
without weariness to the end of his days;
and would lament those who sat themselves down at ease,
and would often say that a terrible day would overtake them who were at ease in Zion.
In the time of his health, when he was able to go abroad and visit Friends, he would say,
'`God has made me a huntsman,
and I must visit many of them who are in their holes and caves;
I must be clear of their blood:`'
and would relate the sore travails and pangs that he had for some,
which often made his soul very sorrowful.

His labors in the gospel were chiefly in the counties of Norfolk, Suffolk, Cambridge,
and Essex; and for his testimony to the truth he was imprisoned in Colchester castle,
where he was instrumental to gain many to the truth.
He was also imprisoned at Cambridge, and at Ely, and Lynn in Norfolk,
and many were turned to God by his ministry.

He was a diligent laborer in the Lord`'s vineyard for about twenty-four years,
and the last year and a half of his time he was much
afflicted with bodily weakness and sickness;
but he would often say that he was content with the will of his Father.
In the time of his sickness he showed the meekness
and patience of Christ which dwelt in him;
but the Lord, in due time, seeing his exercise to be enough, put a period to his days.
He was filled with the peace of God to the last, so that he said he could shout for joy,
but that he lacked strength of body; and which, he said,
was but an earnest of what he should more fully enjoy
when his earthly tabernacle was dissolved.
He spoke largely of the enjoyment of the glory of God in his soul,
and of the assurance he had of eternal life;
some of his expressions in his sickness were as follows:

'`The earth is filled with the glory of the Lord: praises, praises unto my God,
who reigns over all, over all.
He has redeemed my soul from the grave, and my life from the horrible pit.
He has plucked my feet out of the mire and clay.
Glory, glory be given unto your great name, oh! my good God.
As for my part I have fought the good fight, and have kept the faith;
and a large share of the glory of my God is sealed in my soul.
It is but an earnest that I have here of that crown of life
and glory which my Father has in store for me.`'

Concerning his sickness, he said, '`It has pleased the Lord to exercise me as he did Job,
for the trial of my faith and patience.
I have trodden his steps these twelve months.
A full reward you have given me of life and glory.
Oh! my good God, how good are you to me!
I have received abundance of good at your hand, and shall not I receive a little evil?
Blessed be your name for your goodness.
My cup overflows, I cannot utter it;`' and so continued,
often speaking of the glory of the Lord, and the immortality that rested upon him.
He charged friends to be faithful,
that the dread of God might always rest upon their hearts,
that they might answer his love, in yielding obedience to his requirings; and then,
if they met with exercises for the trial of their faith, yet the Lord would be with them,
if they abode faithful to the end; and the same crown of life they should enjoy,
which he had assurance of.

'`Therefore,`' said he, '`watch, and keep your garments, and oil in your vessels,
that you may be ready to enter with the bridegroom.
But as for those that continue in hypocrisy and disobedience,
and shun the cross of Christ, and neglect to work while it is day,
the night will come upon such unawares,
and the foolish virgins`' state they will be found in;
and though they may desire oil of the wise, the wise will have none to spare;
but the door will be shut upon such, and misery will be their portion.
He also gave good counsel to his two daughters, saying there was a blessing for them,
for their father`'s sake, if they would bow to truth, and abide faithful therein.

He longed to haste away; but was also willing to wait God`'s pleasure.
More was spoken by him as friends came to visit him, and as his strength would permit,
which was not taken in writing.

After his speech grew low he could not well be heard,
and seemed for some hours as if he was departing.
At last he said to a friend, '`I was almost gone, but I cannot go yet;
there is some secret counsel of God in it.`'
After some little time, more friends coming in, he was, beyond outward likelihood,
enabled to declare much to them, exhorting them to faithfulness, and said,
'`I am glad to see my friends about me.
I go to my God and your God, my Father and your Father.
My bosom is full of love to all my Father`'s children;`' and then said, '`Now, Lord Jesus,
how acceptable is it to leave all the world, and be gathered up to you:`' and so,
committing his spirit to the Lord, soon fell asleep.

His end was honorable, and he is crowned with immortality and eternal life,
and he left the world in a good age, having attained to about sixty-three years.
He died the 21st of the Eleventh month, in the year 1679, at Earls Colne,
in the county of Essex.

[.asterism]
'''

WILLIAM SIMPSON, born in Lancashire, where he also received the truth,
was a faithful minister and prophet of the Lord,
and was much concerned in going through markets and towns,
and to great men and magistrates, and priests`' houses, and public places of worship,
declaring against their false worship, and evil ways and works;
and was often imprisoned for the truth,
and underwent cruel and hard sufferings by the jailers.
He was moved of the Lord to go at several times, for the space of three years,
barefoot through markets, courts, cities and towns, and to priests`' houses,
as a sign to the people; telling them so should they be stripped, as he was.
Sometimes he was moved to put on hair sackcloth, and to besmear his face black,
and to tell them so would the Lord besmear all their religion.
Great sufferings did this poor man undergo; many sad blows, and sore whippings,
with staves, and wands, and thorn-bushes, coach-whips, and horse-whips, on his bare body.
This was before king Charles the Second came in;
that that generation might have taken warning, and they would not,
but rewarded his love with cruel usage: only the mayor of Cambridge did nobly to him,
for he put his gown about him, and took him into his house.

In the year 1670 he went to Barbados, in company with that faithful servant of God,
John Burnyeat, to preach the gospel of Christ Jesus in that island;
and after they had some service for God there, he was taken sick of a fever,
in which time he felt great peace and consolation of the spirit.
After he had been sick several days, he signified to Friends about him that he should die.
In the observation of his submission and innocent behavior on his sick-bed,
some shed tears; and he taking notice of it,
tenderly desired that they should not be grieved.
Growing weaker, and his voice low, he said to those about him, '`Friends, be noble,
and do not hinder me in my passage, for I am an innocent man.`'
Being asked where he would go, he said,
'`I must pass away;`' and by what more was said at that time,
Friends were assured that his heart was wholly fixed upon the Lord.

A few hours before he died, a person came to visit him who had not been, though invited,
at any meeting William had been at in the island,
and taking him by the hand asked him how he did; he answered,
'`I am a very sick man;`' and looking towards the man,
he was endowed with the power and spirit of the Lord,
by which he marvelously preached the glorious gospel of our Lord Jesus Christ,
for about a quarter of an hour, praising and magnifying the Lord;
which was so contrary to the expectations of those about him,
(considering the circumstances of his weak condition,) that it caused amazement,
trembling, and tears.

He preached the doctrine of perfection, and freedom from sin on this side the grave,
exhorting friends to be valiant for truth upon earth;
and that they should not be again entangled with the yoke of bondage;
but to stand fast in the liberty wherewith Christ has made them free;
that every bond and yoke might be broken, and that which is pure and holy,
of the Lord God, might go free in all; that God might be glorified and honored,
and they preserved in the day of trial, which must come upon all flesh;
and so to grow from grace to grace, and from strength to strength,
and from one degree of holiness unto another,
and that a daily growth might be witnessed in all.
Farther saying, '`O friends! it is the life that the Lord looks at;
for he that has the Son has life; and he that has not the Son has not life.
Examine yourselves; no Son, no life; without the Son, without life:`'
and thus he declared wonderfully, often praising and glorifying God after this manner;
--'`Oh! all that is within me praise and magnify the Lord God,
who is worthy forever and ever of all glory.
Everlasting praises to the God of my life, who is only worthy, and lives over all,
and is above all, God blessed forever.
Amen.`'

About three hours after he had given this testimony,
he departed this life in much quietness, being the 8th day of the Twelfth month,
in the year 1670, and was honorably buried in a garden belonging to Richard Forstal,
at Bridge-town, in Barbados.

[.asterism]
'''

JOSEPH COALE, of Reading, in the county of Berks,
a young man about nineteen years of age,
was convinced of truth in the breaking forth of God`'s blessed day in our age.
When the ministers of Christ Jesus our Lord came to Reading,
he was one of the first that received their testimony,
and was one of the first in the county of Berks that
suffered imprisonment on the truth`'s account.
In the year 1655 he was committed to the counter in Reading, by Henry Frewin, justice,
and afterwards to the jail, for declaring, in the public place of worship,
that Cain`'s sacrifice was not accepted, but was an abomination to the Lord.

He preached the everlasting gospel, and the day of God`'s visitation to the world;
and his ministry was effectual,
not only for the convincement but also for the establishment and confirmation of many,
he being experienced in the work and dealings of the Lord God,
and also of the wiles and baits of the enemy of the souls of mankind;
a faithful witness-bearer to the truth, not in words only but in life and conduct also;
walking in innocency and lowliness of mind, in which he was a good example and pattern,
as became the gospel of Christ Jesus.

Being delivered out of prison, he was moved, in the year 1656,
to travel abroad in the west of England,
to visit his friends and brethren who were prisoners
for the truth in Launceston jail in Cornwall,
where, at that time, our dear Friend George Fox was also a prisoner, with other Friends.
In compassion to their sufferings he was conscientiously concerned to lay before
justice Anthony Nichols the cruelty of the jailor towards his friends,
carrying also with him a letter from George Fox to the said justice; who,
instead of relieving the oppressed,
committed the said Joseph Coale to the rest of his friends at Launceston as a vagrant.
He lay there many months, after he was fined at the assize,
for the most part in a wretched place called Doomsdale, where they used to put murderers,
after they were condemned to die.
It was so noisome that it was observed few who went in ever came out in health;
and the filth of the prisoners, that from time to time had been put there,
had not been carried out, as the people said, for many years; so that it was like mire,
and in some places to the top of the shoes in water, etc.
The jailor would not let Friends clean it,
neither would he let them have beds or straw to lie on.
Being released, he went on farther westward to visit Friends,
but was committed by justice Ceely again to Launceston jail as a wanderer,
where he lay three months.

In the year 1657, he being with other Friends met to worship God, near Penryn,
in Cornwall, captain Fox, governor of Pendennis-Castle, with a troop of horse,
came and abused Friends in a wicked manner, and Joseph was much beaten,
and some of his blood shed, to the hazard of his life.

He was also afterwards, for declaring truth in the public place of worship at Exeter,
fallen upon by the rude people, and haled by the hair of the head,
and had to the town-hall, and from there to jail, a very filthy place;
and they put a great pair of double irons upon one of his legs,
and ordered the jailor not to let him have any bed nor straw to lie upon;
but the next week he was set at liberty.

In the same year he was committed to Dorchester jail for
exhorting people to repentance in the market-place at Lyme,
and for declaring truth in the steeple-house at Bridport.

In 1661 he was again imprisoned at Exeter for not swearing;
being taken from a peaceable meeting, and tendered the oath.
Many other times he hazarded his life for the testimony of the blessed truth, in stocks,
and stonings, and various other hardships and difficulties.
He was once in Ireland with Edward Burrough, in the service of the gospel.

Last of all, he was committed to the jail of Reading, on the 13th of the Fifth month,
1664, by William Armourer, a justice of the peace, because,
for conscience-sake towards the Lord, he could not break his command, who had said,
"`Swear not at all.`"
After six years being shut up in prison, and much deprived of common air to breathe in,
he was greatly impaired in his health.
In the time of his sickness,
he gave forth many heavenly exhortations to Friends who came to visit him;
and this was his faith, which he declared on his dying bed, saying,
that the light of that glorious everlasting day of the Lord,
which is broken forth in this our day, shall never be extinguished,
notwithstanding all that men can do: '`And though,`' said he,
'`it may be in the hearts of men to destroy and root out, if it were possible,
the righteous from off the earth, yet the Lord does not intend so,
neither is it in his heart to allow it so to be,
but to exalt his own name and kingdom over all;
and the wrath of man shall turn to the glory of God, and the rest he will restrain.`'

Death was made easy to him;
and near his departure he bid one of his fellow-prisoners farewell,
and resigned up to him that office of love and care
which he exercised among his brethren and sisters,
in bonds for the truth`'s sake.
Being filled with heavenly love and life, and fully satisfied,
he laid down his head in peace,
and full assurance of everlasting rest and joy in the Lord.
Aged about thirty-four years.

[.asterism]
'''

WILLIAM SMITH, born at Besthorp, in Nottinghamshire,
was formerly a pastor of an Independent congregation,
and lived after the strictest manner of that people,
and was convinced of God`'s everlasting truth about the year 1658.
He was a faithful laborer in the gospel, and many were turned unto God by his ministry;
for he approved himself a minister of Christ Jesus, in tumults, in labors, in travails,
in watchings, in necessities and distresses,
which came upon him through the often spoiling of his goods,
and long and tedious imprisonments of his body.
For refusing to pay tithes to an impropriator,
he was kept close prisoner one time twenty-one weeks among felons,
in a dungeon in Nottingham jail;
and another time he had the value of forty-two pounds taken from him,
at the same time he was in prison for seven pounds, demanded by Dove Williamson,
priest of Elton.

Indeed, many were his sufferings for his testimony to the truth,
which for brevity sake are omitted; all which he patiently endured,
as seeing him who is invisible, that he might hold fast faith and a good conscience.

In the times of his imprisonment he wrote several useful books,
which remain in the printed collection of his writings.
When he was at liberty he travelled abroad,
to the nourishing and strengthening of them who did believe.
Though he was often visited by sickness, he was kept in much patience and contentment;
and much of the power and presence of God appeared in him many times,
when he was in great weakness of body, to the admiration of the beholders.

In his last sickness, he was a great comfort to them who visited him,
being a living man in the life of truth.
After he had been ill seven weeks, his pains began to cease,
yet he continued in weakness; but other distempers came upon him,
which he bore with great patience.
Waiting quietly, and having his mind retired, he spoke little till one evening,
when many Friends being in the room, sitting in silence, and he in his bed,
he turned towards them, and plentifully declared of the great love of God:
and Friends were much refreshed and tendered.
He also testified of a large portion which he had in life eternal;
and then he spoke to Friends to be mindful of truth, and of their service therein,
more than of their daily food; and so committed them to the grace of God.

The day before he was taken away he called for all his children, who were six or seven,
and tenderly exhorted them to keep in the fear of God, and to love the truth,
and God would be a father and portion to them.
The next day he departed this life, being the 9th of the Eleventh month,
in the year 1672.

[.asterism]
'''

JOHN STEEL, of Cumberland, was brought to the knowledge of the truth in the year 1654,
and was obedient thereunto;
and the Lord gave him a public testimony to bear not long after he was convinced,
which continued with him to the end of his days.

He was a man of an excellent spirit,
and clear in discerning the states and conditions of many,
to whom he was made very serviceable by good counsel, wholesome advice and instruction.
His manner in public testimony was to deliver himself in few words, and not often,
yet very weighty and profound.
He was severe against deceit and wrong spirits,
but very willing always to encourage the well-doers;
a good example in conduct in his family, and abroad among men,
as well as in the church.

When he was first taken sick he said to his wife, '`I must leave you;`' she replied,
'`My dear, why are you of that belief?`'
He answered, '`It is my belief, and that I shall be well,
and get to the place of pleasantness that I have been travailing for above these twenty
years;`' exhorting her to take heed to the pure light wherewith she was enlightened,
'`for,`' said he, '`it is the way, and there is not another.`'
He bore a living testimony on his dying-bed, in the name and power of the Lord,
to several who came to visit him, both Friends and other people, exhorting, warning,
and reproving, as he was moved of the Lord.

The day before he died, several Friends being come to see him,
he bade them sit down and mind well what he said;
and he uttered many very weighty sayings, which were not written down;
but this was remembered, that he said,
'`None could die the death of the righteous but they that lived the life of the righteous.
Though death may seem hard to some, it does not seem hard to me;
for I feel my passage sweetened this day.`'
He exhorted Friends to keep the unity, and beware of a wrong spirit, and then said,
'`I have little more to Friends, but it may be I have something to say to others.`'

After a little time he desired several of his neighbors, who were not called Quakers,
to be sent for, and most of them being come, the power of the Lord came upon him,
and he said,
'`I am not ashamed this day to say the spirit of the Lord
is upon me;`' and so declared to them several weighty things,
and said, '`Though some of you have been long in a profession of religion,
if the question were put to you, What is the guide of your minds?
I believe you will be put to a stand for an answer.`'
Some of their hearts were so reached that they wept.
A few hours before he died, he uttered many heavenly expressions in prayer to the Lord,
to the great refreshment of the standers-by. Thus the Lord,
who alone is worthy of praise, accompanied him by his power to the last.

He was convinced of truth in the year 1654, and died in Cumberland, in 1680.

[.asterism]
'''

THOMAS LLOYD formerly dwelt at a place called Macemore, in Montgomeryshire, in Wales.
In his young days he was brought up at the university of Cambridge,
and afterwards removed with his family to Pennsylvania,
where he was president and deputy-governor of that province several years;
and in the last part of his time he had his share with other friends in the exercises
occasioned through the contention of George Keith with Friends in that country.

Being taken sick, and near his end, he said to Friends about him, '`Friends,
I love you all.
I am going from you, and I die in unity and love with all faithful Friends.
I have fought a good fight, I have kept the faith,
which stands not in the wisdom of words, but in the power of God.
I have fought, not for contention and strife, but for the grace of our Lord Jesus Christ,
and the simplicity of the gospel.
I lay down my head in peace, and desire you may all do so: friends, farewell all.`'

He farther said to Griffith Owen, a Friend who was then intending for England,
'`I desire you to mind my love to Friends in Old England,
if you livest to go over to see them.
I have lived in unity with them, and do end my days in unity with them,
and desire the Lord to keep them faithful unto the end, in the simplicity of the gospel.
After a few days`' sickness, he departed this life on the 14th of the Seventh month,
in the year 1694, aged about forty-five years, leaving six children behind him,
and was buried in Friends`' burial-ground in Philadelphia, in Pennsylvania.

[.asterism]
'''

ELIZABETH MOSS, daughter of Thomas Monk of South Liverton Hall in Nottinghamshire,
whose mother afterwards married Samuel Watson of Knight Stainforth,
in the county of York, and late wife of Thomas Moss, merchant in London,
was educated under a tender, zealous, and religious mother,
who brought her up in the nurture and admonition of the Lord;
and she was a dutiful and obedient child.
When she grew up, and came to receive the truth, she gave up to it,
and continued faithful therein to the end.
She was exemplary in her family, and took great pains to instruct her servants,
that she might bring them to a sense of their dangerous condition without a Savior.

She was a great lover of retirement, and much given to prayer, contemplation,
reading of the Holy Scriptures, and spent much of her time alone in her chamber;
so that frequently, when her husband returned home from his affairs abroad,
he found her weeping; upon which he has sometimes said to her,
'`If some persons saw you at these times, they might think you were under discontent:`'
her answer was, '`No, my dear, there is nothing at all of that;
but the Lord`'s power and presence has broken my heart and tendered my spirit,
in a living sense of his goodness and tender dealings towards me.
I can say he is truly good to my soul,
and I have tasted of the incomes of his heavenly love and life.
I heartily wish that all who make profession of the blessed truth, were enjoyers with me,
for my soul has been overcome with his love; and although I have lost all my children,
and many of my near relations, yet is the Lord pleased to sweeten all my afflictions,
and make hard things easy to me.`'

She was indisposed some time before she kept her chamber,
and her sickness increasing upon her,
she was advised to remove out of the city for the recovery of her health, which she did,
and was some time at Shacklewell.
But notwithstanding, she grew worse; and being sensible that her end drew near,
she sent for Samuel Waldenfield, George Whitehead, and some other Friends,
that she might see them before she died.
The day before she died, Samuel Waldenfield and John Field coming to visit her,
she was much revived, and spoke to this purpose, as follows,
directing her speech to Samuel Waldenfield.

[.embedded-content-document.testimony]
--

I had a desire to see you,
and to invite you to my burial,`' she having sent for him the day before; '`but I hope,`'
said she to John Field, '`you will not take it amiss that I spoke first to Samuel,
for I did not know of your coming.
Your visit being altogether free, I kindly accept of it as freely,
and desire you also to be at my burial.
Though I did not know that I should have seen the light of another day,
yet the Lord having spared me, I am glad to see your faces,
that I may tell you how good and gracious the Lord has been to my soul;
for I can truly say, I have sought him with many tears, in my secret chamber,
and poured out my soul unto him; and said, O Lord, do you come down and tabernacle in me,
and take up your abode with me.
For I testify Jacob`'s seed has wrestled with God for a blessing, and has prevailed;
and now he is become my portion, and the lot of my inheritance forever.
He has poured of the oil of joy into my sorrowful soul,
and has fed me with the finest of the wheat,
and with honey out of the rock has he sustained me, and the sting of death is taken away.
I say, my dear friends, I have not the work to do now, I bless my God for it,
but am ready to be dissolved; and I do freely resign my life to my God.
I remember my dear and tender mother, who was a woman that truly feared him,
and her prayers and petitions were often put up to the Lord,
on the behalf of her offspring; and we have reaped much benefit thereby.
I have blessed the Lord many a time that ever I was born of her.
I speak not these things boastingly; no, for what am I but a poor lump of clay?
But only to extol the powerful name and goodness of my God,
who has been so bountiful and gracious to me,
for there is forgiveness and mercy with him, that he may be feared.

Therefore be encouraged to keep faithful to the Lord,
all that are within the hearing of my voice, both husband, friends, and servants.
I exhort you all, do justly, love mercy, and walk humbly with your God,
that so it may be said unto us all, '`Come, you blessed of my Father;`'
which is what my soul has desired, and that I might never hear that dreadful sound, '`Go,
you cursed.`'
The Lord has answered my desire this day, and has loosed my tongue,
that was ready to cleave to the roof of my mouth,
and has strengthened me to praise his great and honorable name.
Oh! praise the Lord with me, my friends, and pray for me,
as I shall do for you while I have breath,
that I may be preserved and kept in patience to the end;
for it is they that hold out to the end that shall be saved.
And though I have a dear and tender husband, and lack nothing that is convenient for me,
yet I can freely part with all.
I hope the Lord will preserve him near to himself to the end of his days.

--

Cornelius Mason coming in, she said,
'`Remember my dear love to your wife and dear children; she has been kind in visiting me,
and we have lived in much love and friendship together.
I truly desire the Lord may keep you faithful to himself to the end of your days;
and now I am comforted, and can say, Lord, here I am before you,
do with me as it seems good in your sight.`'

This is the substance of but part of what she said,
for she continued a considerable time speaking of
the mercies and dealings of God to her soul,
and praising him for the same, to the comfort of those present.
Samuel Waldenfield spoke a few words,
and returned praise and thanksgiving to the Lord for his
endless love and tender mercies to his servants and people;
during which she was filled with heavenly joy, and spoke some words afterwards,
desiring her dear love might be remembered to all faithful Friends, with whom, she said,
she was in perfect unity; and so parted with them in much sweetness,
love and satisfaction.

Soon after came our friend George Whitehead, whom she had desired to see,
and she was refreshed and comforted to see him; and said, '`Dear George,
I am glad to see you, having always had much love and respect for you,
you having been at my father`'s house, and known my mother well.
Though I am weak of body, yet the Lord has comforted me with his living presence,
and death is no terror to me;
but I am freely resigned and given up into the hand
of my God;`' with much more to the same effect.
Being much spent with the other Friends, she could not raise her voice as she did before;
but with love and sweetness, and a smiling countenance,
spoke of the goodness of the Lord to her soul,
and recommended her counsel to those that were present,
that they might not leave that work to do,
but labor to make their calling and election sure,
before they were cast upon a bed of languishing, as she was upon;
but through the love of her heavenly Father, she was waiting for her change,
and desired that she might hold out to the end in true patience.
She desired George Whitehead also to be at her burial,
and after he had spoken a few words in prayer and supplication on her behalf,
she parted with him in much love and unity.
Afterwards she said, '`O that I had wings like a dove! For then would I fly away,
and be at rest:`' with many other living and heavenly expressions.

These things are written,
not only for the comfort but encouragement of those who are yet behind,
to love the Lord above all, and follow him fully,
that he may not forsake them in the day of distress.
This Friend often said the eternal God was her refuge,
and underneath was the everlasting arm of his power,
to uphold and lift up her head above the floods of
temptations and trials that she met withal;
by which she was enabled to sound forth praises,
and humble thanksgiving to his holy and blessed name.

She departed this life the next day, being the 3rd day of the Second month,
in the year 1702, aged about thirty-nine years,
and was buried at Friends`' burial ground in Bunhill-fields, London.
