== Chapter 2

[.chapter-synopsis]
* William Young
* Hannah Dudley
* Samuel Fothergill
* Luke Howard
* Margaret Fox
* Lucy Chopping
* Thomas Wilson

WILLIAM YOUNG, son of William Young, of Leominster, in the county of Hereford,
and Hannah his wife, she being deceased,
was in his childhood of a sweet and sprightly natural temper,
and although of a tender frame, seemed healthy, until he contracted a cold,
which at length brought on a consumption.

In the course of his affliction his deportment was grave, and as he grew worse,
he became more thoughtful,
and made many sensible remarks of the uncertainty of visible things;
and expressed a grateful sense of the kindness of Providence many ways,
and particularly in the visits and good advice he received from friends.
Although he had been preserved in a more innocent conduct than most young men of his age,
he knew that would not entitle him to the felicity of the redeemed,
and was therefore earnestly desirous of attaining such a state of inward
purity and renovation of heart as would procure divine favor;
and on this account had many painful conflicts.
When his recovery was thought doubtful,
he often lamented his having lost that tenderness and fervency
of spirit towards God which he had formerly experienced.

For many weeks before his death he was apprehensive of his end being near, and said,
'`If I die now in my youth, it may be all for the best,
and may put other young people upon the consideration of their latter end.`'
On his father`'s saying it would be well for us to be resigned to the divine will,
but intimating a reluctancy to part, he replied with much earnestness, '`Aye,
do be resigned;
let us all be resigned;`' and frequently expressed
a desire to be resigned either to life or death;
but said, if it pleased the Lord to fit him for his change,
and take him from the slippery paths of life at so early a period,
he should think it a favor; for he had no desire to live,
except it was to the glory of his Creator.

He several times showed great concern at hearing
of the disorderly walking of some among us,
and a deep sense of the wonderful goodness and condescension
of Christ in suffering for mankind.

Some weeks before his death, observing his sister weep, he said, '`We must part.
I must leave you; but I hope and believe we shall meet again.`'

The 2nd of the First month he was very ill, and seeing his father affected, he said,
'`father, what a mercy it would be if the Lord should be pleased to take me to himself!
Do not grieve, for if I should be spared and turn out naught,
it would be a greater affliction.`'

The next morning, after having had a very bad night, he was weak and low,
but appeared quite calm in mind; and on his sister`'s saying,
after some other conversation, she hoped he was resigned, he replied with much sweetness,
'`Yes, sister, I hope I am quite resigned to the Almighty`'s will;
but surely if it is his will,
it will be a mercy to be taken from this troublesome world to himself.
And I have a hope he will take me to himself;
he has been pleased wonderfully to calm my mind.`'
She observed there was great room to hope,
and that the sufferings of his friends would be greatest; he replied very earnestly,
'`my sufferings will be nothing in proportion to my
offenses! but I have a hope my offenses will be forgiven.
O how merciful is the Lord!
How great is his goodness!
How pure is his love!
Mercy, goodness, purity, belong to him.`'
Seeing his sister much affected at what he said, he continued, '`We cannot tell, sister;
some worse than I have been restored.
He is able to raise me up, and if he should,
and make me some sort of a member (meaning of his church militant),
I hope I shall be careful to keep near to him; but I desire not to live, no,
not a moment, as one of this world.`'

That night he was so weak, those about him were apprehensive he could not continue long.
The next day he seemed pretty free from pain, but drowsy, and his expressions rambling,
but innocent; indeed, his countenance and conversation were sweet and lamb-like.
The next morning he desired to be put to bed, being in great pain,
but could not rest there;
and being replaced in the easy chair and same posture he had lain in for many nights,
he seemed much easier, and told his sister he was going;
she said she hoped to a better inheritance; he replied, '`Aye,
for I believe in one that can save me;`' and repeatedly
said the fear of death was taken away.
And a day or two before his death, he said, '`I am going to leave an affectionate father,
to meet the great Almighty Father.`'

Another time, his sister saying it was a favor he was preserved so patient, he said,
'`I hope I shall be kept so; I am under the Lord`'s care entirely; nothing else will do.
I see nothing else will do.`'
The same day he uttered many sweet and lively expressions,
but his voice was too low to be understood, so as to connect the sentences.
The day before his decease it was so weak and broken,
that he could scarcely articulate a sentence; but was meek and patient as a lamb,
and once said something about rejoicing in the house of God,
and when he could no otherwise express himself,
would reach up to kiss his father and sister, his heart being full of love.
When asked if he would have anything sent to his eldest sister then in Cornwall,
he said, '`Nothing but my love, or dear love; adding, '`In that love I feel for all.`'
He frequently desired those about him not to grieve, and would sometimes say, '`Why,
if you think I am going well, should you grieve?`'
and observed, that if he had brought on his illness by any bad course of life,
it would be hard to bear; but added, '`I believe you have no reason to think I have.`'

He took a most affectionate leave of his sister, bidding her love and adore the Lord;
and said something about his father, which could not be understood.
His father then telling him he hoped there was a
place prepared for him among the blessed,
and that he loved to be with the good, he replied as well as he was able, '`Aye, dearly,
dearly.`'
And in about two hours after, he departed so quietly,
that those present apprehended him to be fallen asleep, the 7th day of the First month,
1773, in the nineteenth year of his age.

[.asterism]
'''
HANNAH DUDLEY, late wife of Robert Dudley, of Clonmel, in Ireland,
was born at Woodbridge in Suffolk, and religiously educated, which was blessed to her.
Through the prevailing power of divine love,
she was brought to know a state of submission to
several near trials which fell to her lot;
and having her heart weaned from the world and its delusive profits and friendships,
she became more and more refined, being an example of humility, plainness,
and self-denial.

About the year 1772 some symptoms of a consumption appeared,
but for some time she attended meetings both for worship and discipline,
in some of which she was enabled to bear a living testimony to the truth.

In the course of her illness many friends visited her,
to whom she was enabled to drop some tender expressions,
and it seemed to be her greatest joy to see and hear of the prosperity of truth;
and at several opportunities she had suitable counsel
and instruction to give to those about her.

About a week before her departure, our friend Robert Willis, of West Jersey in America,
being in the course of his religious visit at her house,
had a comfortable and tendering opportunity with her, her husband and sister.

About two days before her decease,
she dropped much excellent advice to her husband and sister,
expressing her desire to be released;
but added her hope she should be preserved patient to the end;
and afterwards on some mitigation of her pain,
signified her entire resignation to the divine will.
Speaking to her husband`'s eldest son, in a very weighty manner,
she advised him to remember her admonitions; saying also, '`Shun bad company,
obey your parent, and do not offend him; seek the Lord and he will be found of you,
but if you forsake him, he will cast you off forever.`'

To their apprentice she said, '`Jemmy, love plainness and continue in it,
for truth leads to plainness.
You have been favored with an education beyond many, therefore prize it,
and have known truth, therefore beware of trampling on the testimony,
but be circumspect in all your ways and conduct.
You are just entering on the slippery part of life, the slippery paths of youth,
and are no stranger to the temptations and allurements of the adversary.
I have often thought it a great mercy that you have
been preserved from (I believe) almost any vice.`'
Just after, she very affectionately took her leave of her brother and sister-in-law,
saying, '`Our acquaintance has been short,
but we have loved one another;`' and then prayed very fervently
that a blessing might rest upon their family.

Being pressed to try and take a little sleep, she replied,
'`O that I could sleep in the arms of my beloved!`' And with great fervency prayed,
'`O Lord God, have mercy upon me! and let your compassionate ear be opened.
Lord God Almighty! send the guardian angel of your presence to conduct my spirit.`'
After which she lay in great peace and serenity of mind, growing weaker and weaker,
yet sensible to the last, and with her hand closed in her husband`'s,
departed without sigh or groan, as one falling into a sweet sleep,
the 25th of the First month, 1773; aged about forty-seven years,
a minister about nine years.
After a very large and solemn meeting, her body was decently interred the 29th,
in Friends`' burial-ground in Clonmel aforesaid.

[.asterism]
'''
SAMUEL FOTHERGILL, of Warrington, in Lancashire,
was the sixth son of our worthy ancient friend John Fothergill mentioned in this treatise,
and of Margaret his wife.

This their son being of an active and lively disposition,
and during his apprenticeship mostly from under the
watchful eye of his affectionate parent,
he fled from the holy cross of Christ,
and indulged himself in the gratifications of folly and licentiousness,
violating the repeated convictions of divine grace in his own mind,
which had been mercifully extended from his early years,
thereby wounding the soul of his tender father,
of whose religious care to form and lead the tender minds of his children
to piety and virtue we have an account in the memoirs of his life.
Yet his pious admonitions proved, nevertheless, as bread cast on the waters,
which returned after many days; for about the twenty-first year of his age,
the visitation of divine love was so powerfully renewed,
that it proved effectual to turn his steps out of the paths of vanity; and,
as he has expressed, with humble and awful gratitude to the Preserver of men,
it then appeared clear to his understanding,
that would be the last call the Heavenly Father would favor him with.
He therefore consulted no longer with flesh and blood,
but gave up to the holy visitation,
devoting his whole heart and affections to seek reconciliation with God,
through the mediation of Jesus Christ;
and abiding in great humility under the purifying operation of the Holy Ghost and fire,
he became thereby qualified for those eminent services he was called into.
In a few months, by the constraining power and love of God,
his mouth was opened to bear a testimony to the sufficiency of that holy
arm that had plucked him as a brand out of the fire.

Thus a dispensation of the ministry being committed to his charge,
he attended faithfully thereto, and moved therein at the requirings,
and under the direction of, divine wisdom,
by which means he soon became an able minister of the gospel,
called thereto and qualified by the Holy Ghost.
Under this influence he labored with diligence,
and devoted much of his time and strength, when health permitted,
to the service of his dear Lord and master,
for the continuance of whose favors he counted nothing too near or dear to part with,
that he might be instrumental in gathering souls to God,
which was the object he had in view in all his gospel labors.
Being diligent himself,
he endeavored much to excite Friends to a due and
constant attendance of meetings for religious worship,
and those for the discipline of the church.

Through the course of his gospel labors, both in public and private,
animated by divine love,
he expressed an uncommon warmth of affection for the rising youth of this generation,
with whom he was led into a deep brotherly feeling
and sympathy for their present and eternal welfare;
under which concern his love to this class of both sexes, under all denominations,
was strong and ardent.

He travelled much in England and Scotland, several times in Ireland,
and once through most of the North American colonies, in the service of truth; where,
though singularly humbled in a sense of poverty,
weakness and insufficiency on his first landing, he was, by accounts received,
marvelously strengthened, both in public and private, in gospel authority and love,
to the awakening and comforting of many.

In the forepart of the year 1769,
he visited most of the families of Friends in the monthly meeting of Gracechurchstreet,
London;
in which service he was divinely strengthened and enabled to extend
a helping hand to many in close and necessary labor,
for their increasing care, to live and act consistently with our holy profession,
to the comfort and help of many, and his own peace; and afterwards,
at two different opportunities,
he visited the families of Friends in Horslydown
and Westminster monthly meeting in that city,
to the same good effect.

He mostly attended the yearly meetings in London, and other places,
when of bodily ability; in which his gospel labors were very acceptable and edifying;
being particularly careful, when called from home,
to return to his family and friends with as much
expedition as the nature of his service would admit.
Having acquired a moderate competency by his diligence and industry,
he declined trade for several years before his decease,
devoting his time and talents to the service of the churches.
As a pillar in the Lord`'s house he was steadfast,
being actuated by a Christian and manly zeal; in deportment grave;
his private conversation was savory and edifying, corresponding with his ministry,
which at times went forth as a flame, piercing the obdurate,
yet descended like dew upon the tender plants of our heavenly Father`'s planting,
the true mourners in Zion; with these he travailed in a deep sympathy of spirit.
In his gospel labors he was free from affectation; in doctrine, clear,
sound and pathetic, filled with charity, allowing for the prejudices of mankind,
being indeed a minister and elder worthy of double honor, speaking whereof he knew,
and what his own hands had handled of the good word of life.

He endured a long and painful illness with much patience and resignation;
and towards the close of his time, expressed himself to some of his relations,
when they took leave of him,
previous to their setting out for the yearly meeting in London, to the following effect:

'`Our health is no more at our command than length of days:
mine seems drawing fast towards a conclusion;
but I am content with every allotment of Providence, for they are all in wisdom,
unerring wisdom.

There is one thing which, as an arm underneath, bears up and supports;
and though the rolling tempestuous billows surround, yet my head is kept above them,
and my feet are firmly established.
O! seek it, press after it, lay fast hold of it.

Though painful my nights, and wearisome my days,
yet I am preserved in patience and resignation.
Death has no terrors, nor will the grave have any victory.
My soul triumphs over death, hell, and the grave.

'`Husbands and wives, parents and children, health and riches, must all go.
Disappointment is another name for them.
I should have been thankful had I been able to get
to the ensuing yearly meeting in London,
which you are now going to attend, where I have been so often refreshed with my brethren;
but it is otherwise allotted.
I shall remember them, and some of them will remember me.
The Lord knows best what is best for us.
I am content and resigned to his will.

'`I feel a foretaste of that joy that is to come;
and who would wish to change such a state of mind? I should be
glad if an easy channel could be found to inform the yearly meeting,
that as I have lived, so I shall close, with the most unshaken assurance,
that we have not followed cunningly devised fables, but the pure, living,
eternal substance.

'`Let the aged be strong, let the middle-aged be animated, and the youth encouraged;
for the Lord is still with Zion; the Lord will bless Zion.
If I be now removed out of his church militant,
where I have endeavored in some measure to fill up my duty,
I have an evidence that I shall gain an admittance into his glorious church triumphant,
far above the heavens.`'
My dear love is to all them that love the Lord Jesus.`'
He departed this life at his house in Warrington, the 15th,
and was buried the 19th day of the Sixth month, 1772, at Penketh,
in the fifty-seventh year of his age, and the thirty-sixth of his ministry.

And now, Reader, before you close the book, pause a little, and consider,
what progress you have made in this heavenly race.
The prophet Isaiah, after describing the coming of Christ,
and very emphatically setting forth his office, the peaceable government of his power,
and its glorious effects upon his followers, in chap.
xi., in the next chapter declares what the faithful experience:
'`And in that day you shall say, O Lord!
I will praise you; though you were angry with me, your anger is turned away,
and you comforted me.
Behold, God is my salvation, I will trust and not be afraid,
for the Lord Jehovah is my strength, and my song, he also is become my salvation.`' Isaiah 12:1-2.

The same living, divine power,
the same inexhaustible source of wisdom and goodness remains.
The enjoyments of time are transient, its pleasures are delusive;
let therefore all trust in his arm: this is the strength and beauty of men;
their alone help and dependence is here, in all their exercises through time,
that when they come to close, as has been the case with the just in all generations,
in effect, to declare, "`Behold, God is my salvation, I will trust and not be afraid;
for the Lord Jehovah is my strength and my song, he also is become my salvation.`"

[.asterism]
'''
LUKE HOWARD, of Dover,
was a serviceable man in the early breaking forth of truth in this nation,
a faithful sufferer for its testimony, and preserved to the end in peace.
The following account is extracted from a short journal and collection of his writings.

In his tender years he experienced in himself the
appearance of the love and grace of God,
reproving for evil; and when about fourteen years of age,
he was bound an apprentice to a shoemaker in Dover.
His master, being in a seeking state,
and having forsaken the public worship and joined with some who were separated from it,
treated him kindly; which so wrought on him,
that he took a resolution to become more conscientious towards God,
and more orderly to his master, than he had been,
not daring to wrong him by neglecting his work.
Thus he served out his apprenticeship to his master`'s content; and,
a few weeks after his time was expired, he came to London to work,
frequented a meeting in Coleman-street, and was admitted a member thereof.
The war between the king and parliament being then very hot,
and forts raising about the city, he sought to be entered in the army;
but many pressing to go, '`It was my lot,`' says he, '`to be left out;
that so I might be clear of the blood of all men, as since I have seen it and rejoice,
though then troubled at my dismission.`'

He then returned to Dover, where there were several young men inquiring the way to Zion,
with their faces thitherward, and searching the Scriptures,
hoping to find the right way.
'`There, and in that day,`' says he,
'`I was convinced that singing of psalms in rhyme and meter,
was a lie in me as to my own condition, and a mock service as to the Lord;
and was forced to sit silent under the cross, when others sung.`'
This, at that period, was so strange, that the priest took notice of him,
and in a little time it was noised abroad as a great wonder,
that he refused to sing psalms.
His master, with whom he had served his apprenticeship, being also troubled at it,
got Samuel Fisher, their priest, to come and discourse with him.
Fisher had much to say to him: '`But,`' said he,
I said what was in my own conscience manifested,
and I did not know another in the world of my mind; but so it was, my peace abounded,
and knowledge increased.`'
Samuel Fisher returned home, and never dared to sing more in the steeple-house;
but was soon after convinced of the everlasting truth,
in which he ended his days in prison, for his testimony thereto.

Luke Howard, meanwhile, went among the Brownists, also the Presbyterians,
and the Independents, and then among the Baptists,
with whom he chose rather to join than with any other.
He passed through their ceremony of water baptism,
but still knew not where to find a resting-place,
not knowing he had a guide within him to keep him out of all evil;
and in this state he mourned with tears.
Nevertheless he got over his convictions, and went into liberties;
'`In this great loss,`' says he,
'`I continued until I did, as too many do, got above the witness,
and I sought to make merry over it, and to take my fill of the world,
with all I could enjoy thereof.`'

But soon after,
coming to London on business he went to hear a preacher in Lombard-street;
and afterwards a young man, named William Caton, stood up,
and sounded an alarm out of Zion,
and proclaimed the gospel of peace out of the Lord`'s holy mountain;
but L. Howard`'s mind being after visible things, he slighted it at that time.
The next First-day, being at home, he was told a Quaker was preaching; and,
going to see what manner of man he was, found him to be the afore-named William Caton.
Luke was reached by his testimony,
was a guard to him from the boys and others who offered him abuse,
and in the evening went to visit him, where he found his companion, John Stubbs.
He invited them to go home with him, which they did, and had several meetings there,
and their testimony was to him as a pleasant song, and he bore them company out of town.
Then exercise fell to his lot,
but he was led along in safety under the teachings of truth,
so that he expresses himself thus,
after giving an account of the exercises he had to pass through: '`My experience has been,
and is, as I abode in obedience to the Lord, in waiting on him,
which I hope I shall ever do; the word of the Lord opened to me when in a great strait,
saying, "`I will cleave the rocks and mountains,
that the redeemed of the Lord may come to Zion;`" at which I felt and saw a little light,
and a hope sprung up of getting over and through those rocks
and mountains of thick and black darkness in me,
which the enemy presented to be so great, that it was impossible to get over.
So then, and ever since, in that grounded hope, as an anchor to my soul,
I have cast my care upon the Lord, and have rode through many bitter storms, and,
I bless the Lord, my flight has not been in the winter, and now, I hope in the Lord,
it will not be in the Sabbath-day.
Even so, amen.`'

In the course of his pilgrimage it was sometimes his lot to be imprisoned.
Once he was sent to Dover castle, with three more, and detained sixteen months,
because he could not forbear meetings.
At this time he employed six men in his trade,
but he was obliged to shut up his shop for six months,
neither could he work in prison for a time;
but obtaining the liberty of an entry to the grate,
where they drew their meat up with a cord, he worked a little there,
and his wife kept cows and sold milk, to assist in supporting his family; '`and,`' says he,
'`I had perfect peace, joy, and content, in it all; and the Lord made it all good to me,
both within and without.`'
It also appears he suffered a long imprisonment in the castle, in 1684; during which,
he often pleaded with the magistrates on account
of their cruel and unjust treatment of him.

Thus persevering, he was preserved in greenness to old age.
The following expressions were taken down during his illness by a friend present,
as delivered:

'`God, the Lord of heaven and earth, appeared to me in an acceptable time,
in the year 1655, by his word, through his servants John Stubbs and William Caton,
in the gift of his grace, the Son of his love, Christ Jesus,
whom he sent out of his own bosom, and by the sword of his own mouth,
and by the brightness of his arising, cut me off from the wild olive tree,
which I was rooted in by transgression, and grafted me into the true olive root,
the life of which is the light of the world, and by his love and spirit in my heart,
raised me to worship him in spirit and truth.
Then the cross appeared so great, that if it had been his will,
I would rather have parted with my natural life, if I could have had peace,
than to have taken it up; but in the day of his love and power, through the word of life,
and the arising thereof, I was made willing to do his will, and to take up the cross,
not for a little while, but with a resolution as long as life continued.
And though many temptations have attended, yet the Lord has delivered me out of them all,
and has engaged my soul and all within me, to serve him in newness of life,
and begot and continued a breathing,
that he would never give more knowledge than he would give me power to obey,
and in the day thereof has made me willing to serve him, and deny myself,
and his reward is and has been in my bosom.
He is worthy to be worshipped, obeyed, and feared forever,
for he speaks peace to his children, that they turn not again to folly.
In his peace stands my rest, which rest remains for the people of God, and in this,
I take my leave of the world, with soul, body, and spirit, given up to the Lord,
in and through his grace, the life of Christ Jesus, in whom all the promises are yes,
and amen.`'

He departed this life the 7th of the Eighth month, O. S. 1699.

The Morning Meeting of London, in a testimony concerning him,
dated the 26th of the Sixth month, 1704, say, he was preserved to the end,
and died in the faith of our Lord and Savior Jesus Christ;
and we doubt not that he received the crown of righteousness,
from God the righteous judge.

[.asterism]
'''
MARGARET FOX, widow of our ancient Friend and elder George Fox,
was convinced of the principle of truth,
on his first coming into that part of Lancashire where she dwelt, in 1652;
being then the wife of Thomas Fell, one of the Welsh judges,
a man much esteemed in his country for his wisdom, moderation, and mercy,
being also a tender husband and loving father,
and one who sought after God in the best way it was made known to him.
He frequently entertained those who were accounted serious and godly men;
and had often prayers, and religious exercises in the family;
and in this manner also Margaret was seeking after the right way for many years,
though often afraid she was short of it.

She was born in the year 1614; her parents were of honorable repute in that country,
and her father, John Askew, was of an ancient family and estate,
and a pious charitable man.
It was in the seeking state before-mentioned that it pleased
divine wisdom to move the heart of George Fox,
to visit the family of the judge, who was then in London,
and to open to them the eternal truth; by which means the minds of herself, children,
and a great part of the servants, were convinced and turned to God.
When the judge returned home, and found the great change wrought on them,
he was much surprised, and appeared to be troubled; but Richard Farnworth,
and some other friends, who came to the house soon after George Fox had been there,
had some discourse with him, and he was still and quiet, and weighed things.
George Fox returning in the evening, and being admitted,
spoke so powerfully and convincingly,
that the judge was so far satisfied that it was the truth,
that he offered his own house as a meeting-place, and was kind to Friends,
on every occasion, to his decease: which was about the year 1658,
being then sixty years of age.

His widow labored to promote the cause of truth, applied frequently to the king,
on behalf of her suffering friends; and visited them in various parts of the nation,
sometimes accompanied by one of her daughters.
About the year 1661, she was sent for from her own house,
and carried to Lancaster castle, because she would not swear; was premunired,
and sentenced to forfeit her real and personal estate to the king,
and to be imprisoned during life; but after having been in prison about four years,
she was set at liberty by order of the king and council.
Soon after this she was married to George Fox, but was again, on the old premunire,
taken from her house, and carried to prison;
where she.continued another year in a sickly state,
till her husband obtained her discharge under the great seal.
All these sufferings she endured with much patience, and neither fainted nor murmured;
but was kept so cheerful and easy under them, that her enemies were amazed to see it;
and several of them that persecuted her came to nothing; while,
as she denied and despised the glory of this fading world, for Christ`'s and truth`'s sake,
God gave her honor and a name among the righteous; and qualifications, many ways,
for considerable service in the church.
In this she shone as a morning star, being filled with real wisdom and understanding,
for the propagation of truth and righteousness; of a clear discerning of spirits,
and the working of the enemy to draw from the life and power of truth,
into a liberty that genders to bondage,
and to separation and breach of unity among friends;
appearing firm and zealous against the same.

She was fervent and living in her ministry,
and in supplication and prayers to Almighty God;
to the edifying and building up many in that most precious truth,
which gives victory over the world.
She was not only a great and exemplary sufferer for truth,
but a visitor and a sympathizer with the faithful in their sufferings;
zealously interceding for their relief, with such as were in authority;
as being afflicted with the afflicted, and mourning with those that mourned.

She never spared herself in her manifold labors on truth`'s account,
both in her ministry abroad, in most places in this nation, and other services;
but approved herself as one that needed not to be
ashamed of her work and service for the Lord,
his truth, and people; which she performed with all sincerity,
while God was pleased to give her strength and ability.

She was preserved in a good understanding to the last; and in the time of her sickness,
she was in a sweet frame of spirit.
She uttered many heavenly expressions near her conclusion in this world,
some of which are as follows:

'`Come, come,`' said she, '`let us join to the Lord, and be of one spirit;
let us join to the Eternal God, and be of one spirit.`'
A friend visiting her, who had been acquainted with her upwards of forty-five years,
she said, '`The Lord is with me, and I am with the Lord, and in him only will I trust,
and commit all to the divine providence of the Lord,
both concerning my children and grandchildren, and all things they do enjoy from him,
both in spirituals and temporals;
who is the God of all the mercies and blessings to his people throughout all generations;
to him be glorious praises forever, amen.`'
At another time she said, '`Oh, my sweet Lord,
into your holy bosom do I commit myself freely,
and not desiring to live in this troublesome, painful world, it is all nothing to me,
for my maker is my husband.`'
At another tine she said, '`Come, Lord, I am freely given up to your will.`'
Again she said, '`I freely forgive all people upon the face of the whole earth,
for any wrong done to me; as freely as I desire to be forgiven:
'`and seeing those about her sorrowful, she said, '`Be quiet,
for I am as comfortable in my spirit as ever I was.`'
A little before she departed, she said to one by her, '`Rachel, take me in your arms:
I am in peace.`'

She departed this life at Swarthmore-hall, the 23rd day of the Second month, 1702,
being near the eighty-eighth year of her age;
and was buried in the burial-ground at Simbrooke, belonging to Swarthmore,
the 27th of the same, attended by many Friends and others.
Her writings were collected and printed in an octavo volume,
from which the foregoing account is extracted.

[.asterism]
'''
LUCY CHOPPING, of Stebbing, in Essex, whose maiden name was Wait,
was born in Worcestershire, in the early part of the last century.
She was soberly and religiously educated by her grandmother, who lived to a great age,
being in her one hundred and fourteenth year when she died;
and who often informed her of the hard sufferings many of the family had gone through,
on account of religion, in Queen Mary`'s days.
After her death, she was left under the care of an uncle, who was a Puritan,
and had a tender care over her.
He gave her good advice, and cautioned her to shun idle company,
never to learn to dance or to read ballads, nor to wear lace nor ribbons on her clothes;
but to go and hear the best men that preached at that time:
so that she acknowledged that it was good for her that she had been so warned.
She came to London in the time of the civil wars, and lived in a religious family,
who wanted her to learn to sing psalms, which she was not easy to do,
but returned back into Worcestershire.
About this period, many were going to New England,
and thinking that all who went there at that time,
to enjoy the liberty of their consciences, were good and religious people,
and that it must be pleasant living in such a land, where all were such,
she inclined also to go there; but, communicating her mind to Vavasor Powel,
an eminent preacher among the Puritans in that day,
he told her that the word was nigh in her heart and mouth,
that she might hear it and obey it;
and that she need not go beyond the seas on that account.
This stopped her journey;
but she still earnestly sought to hear those preachers who were accounted gifted men.
She went to hear Humphrey Smith in particular,
who was esteemed to have an excellent gift,
and did not think it lawful to take money for preaching.
He, being once at a meeting, sat a great while in silence;
at which the congregation wondering, he stood up,
and told them that he had formerly spoken what was opened to him, '`But now, '`says he,
'`my mouth is stopped, and I believe, whenever it may please the Lord to open it again,
it will be more to his glory than ever it has been.`'
This made her very desirous to know where he went;
but soon after it pleased the Lord to send one of his servants, called a Quaker,
by whom Humphrey Smith was more fully convinced, as she also was herself.

In a little time it pleased the Lord to qualify him for the ministry;
and he travelled abroad, in the service thereof, into the west of England, where he,
with many more, was imprisoned.
She then found it her concern to visit them in prison;
and went from one prison to another,
doing them service in mending and making their clothes;
and many of them being far from their homes, she went and visited their families.
She spent many years in this service,
which was very acceptable to those that could not
have liberty to see their families themselves;
and great was her labor of love, in that she did it freely,
although she travelled on foot: be sides which,
she frequently attended the yearly meeting, when established.

Having, at the request of her friend Humphrey Smith, conducted his son into Essex,
where he was bound an apprentice, she often went to visit him.
At length she became the wife of John Chopping, of Stebbing;
with whom she lived but about two years, and survived him about twenty-eight years.
She was a mother in Israel, of a good understanding,
a visitor of the afflicted in body or mind,
and often had a word of advice and comfort to them.
She particularly exhorted the young convinced to faithfulness;
and when any were grown careless, she was tender in advice and exhortation;
and often to so good effect, as to reach the witness in them.

About two weeks before her death, she walked six miles to a meeting,
in order to visit a woman, who, being overcome with the cares of the world,
neglected meetings: whom she warned of her danger,
and who became more careful afterwards in her duty.

The day following she was taken ill, when she expressed herself thus:
'`I cannot say that what I feared is come upon me, but that which I have long desired;
for I am very ill, and do think it will be my end.
But it will be well with me.
I shall go to my mansion which is prepared for me
and all the faithful followers of the Lamb;
and I have nothing to do but to die.
The Lord has been with me, even as with Jacob, and I knew it not; and,
blessed be his name, he has been with me,
and made known the way of life and salvation to me,
and preserved me through many hard exercises and deep afflictions,
and sorrowful travails in spirit.
He has been with me through my pilgrimage, and kept me safe through many long journeys,
in which I have walked many hundred miles, to serve my friends in the truth,
and for the truth`'s sake, and mostly alone; and the Lord preserved me,
so that none were permitted to do me any harm:
for which I have often been humbly thankful, and now I feel peace,
and shall in a little time rest with Him in everlasting joy and peace.`'

At another time she said, '`It is good to have nothing to do but to die:
for now I feel it hard to bear the pain and sickness of this body.`'
She often expressed her concern for the churches, that good order might be kept up;
and for the poor, for whom she always had a great care.
A woman in high station visiting her, she advised her to prepare for such a time;
telling her she had peace,
and that was of more worth than all the pleasures of the world;
and advised her to mind the gift and manifestation of the Spirit in her,
which would lead her also into the way of life and peace.
The woman, filled with admiration, said she never heard the like,
that any person could have such a satisfaction and victory over death,
for that there was no terror or fear of death in her; to whom Lucy Chopping answered,
'`Perfect love casts out fear.
I have loved the Lord with all my heart, and served him with all my strength,
and I have peace: the Lord is with me, and it will be a glorious change.`'
Again she said, '`The Lord has been with me in many hard afflictions, and given me hope,
which has been as "`an anchor to my soul.`"
I can say with David, "`He has plucked my feet out of the mire and clay,
and set them upon a rock,`" and I shall not be moved.`'

Growing weak, and having many sick fainting fits the day before she died, her niece,
Elizabeth Wyatt, offered her something to take; she answered, '`I lack nothing;
the Lord is with me, and his Spirit comforts me.
I have bread to eat which the world knows nothing of,
and the wine of his kingdom refreshes me, and I desire no more of this.
Do not endeavor to keep me here, for to die will be my gain,
and though my body grows weak, my inward man grows strong.
Speaking to her niece, and giving her good advice, she said, '`The Lord is with me,
and I have an earnest of that which I shall in a
little time launch into the full enjoyment of.`'

She departed this life, being sensible to the last, the 6th of the Sixth month, 1705,
and was buried in Friends`' burial-ground at Stebbing.

[.asterism]
'''
THOMAS WILSON, of Ireland, was born in Cumberland,
and educated in the profession of the church of England.
While a youth he had great hungerings after righteousness,
and the true knowledge of the living God, and his son Jesus Christ;
and went with great diligence to hear the priests, and carefully minded what was spoken.
If he heard of a priest that was noted for a good man,
and preached two sermons in one day, he would go sometimes eight miles on foot,
after hearing the morning sermon, to hear another in the afternoon;
and the more he sought to hear, the more his hunger and thirst increased,
so that he was sensible of great poverty of spirit.
In the time of singing psalms a thoughtfulness came over him,
that men should be made holy before they could rightly
sing to the praise and glory of God;
and he was stopped from singing them, through a godly sorrow which was in his heart,
with secret cries and humble prayers to the living God of heaven and earth,
for the knowledge of the way of salvation.
In this state he travailed in great godly sorrow, weary of the heavy load of sin,
as also of the doctrines and worships of men`'s making;
and many texts of Scripture being opened to his understanding,
he began to see that which was not of faith was sin, even in points of worship,
and the pretended service to the great God.

Being thus made sensible that too many of the doctrines of the church,
in which he was educated, were precepts of men`'s making; and that "`God is a spirit,
and they that worship him,
must worship him in spirit and truth;`" this worship he greatly longed to know;
and conversed with priests thereon, but they could not direct him where to find it.
But, after long travail of spirit, and great concern of soul,
the Lord was graciously pleased to make him sensible, that what was to be known of God,
was manifested in man.
About this time he went into an evening meeting of the people called Quakers,
with strong desires in his mind to the Lord,
that if it was the true way of salvation which this people preached,
he might have some inward feeling and testimony thereof in his own heart.
After sitting some time in silence, a friend began to speak,
directing and exhorting to an inward waiting upon the Lord in faith,
to receive power from him over every unclean thought,
by which heavenly power they might glorify and praise the name of the Lord,
through the ability of his own free gift.
This Thomas understood to be the holy word of grace, which the apostle preached,
and to which he turned the minds of the people;
and he felt his soul much in love therewith, saying in his heart,
'`This is what I greatly wanted.`'
The Lord`'s power arose in the meeting to the breaking and tendering of his heart;
and inward cries were raised in him to this effect, "`O Lord,
create in me a clean heart.`"

Now his heart was opened, and he felt the Lord`'s fierce anger because of sin;
and he was made willing to love, and dwell under, his righteous judgments,
being truly convinced that was the way to come to the mercy-seat.
He saw he was to cease from the doctrines of men, and mind the gift which was in him,
and sit down among friends in their silent meetings,
to wait on the Lord in retiredness of mind, for his heavenly teachings and holy leadings;
in the performance of which inward, divine, and heavenly worship, he,
with many more young people, was convinced of the inward work of God,
and turned to the Lord with all their hearts.
Those who attended this meeting from time to time,
became very tender and heavenly-minded, and in great love with each other:
the heart-tendering power of the Lord being renewedly felt, inwardly revealed,
when no words were spoken.

This our friend being thus raised up and qualified, came forth in a public testimony;
and was concerned not only to travel and visit many parts of this nation, Scotland,
and Ireland, but also America; which he visited twice, in company with James Dickinson.
He left there many seals of his ministry, which was sound, plain, and powerful,
frequently attended with a heavenly sweetness,
as he was divinely enabled to open the mysteries of life and salvation.
He was also richly endowed with the spirit of supplication,
in which he was drawn forth in great tenderness and fervency of spirit;
not only on behalf of Christ`'s church and people, but for mankind in general.

After more than forty years`' labor, his natural strength decayed;
and towards the close of his time,
having not long been returned from a journey of ten months through many parts of England,
he expressed himself thus, '`Now I rejoice in that I have served the Lord in my day;
and as I have labored to promote the truth in my generation,
I feel great peace from the Lord flowing in my soul,
and am thankful that I have been made willing to serve him.`'

He was taken ill about the Eleventh month, 1724, and continued weakly for several months;
in which time he uttered many weighty expressions,
and at several times was concerned in fervent prayer for the young and rising generation,
that they might be faithful witnesses for the truth in their day.
He expressed his concern that Friends should live agreeably to the doctrine of Christ;
and that the good order established among us might be kept up and maintained,
and that all differences and disorders might be kept out of the church.
Among many weighty expressions, he said, The Lord`'s goodness fills my heart,
which gives me an evidence and assurance of my everlasting peace in his kingdom,
with my ancient friends, who are gone before me,
with whom I had sweet comfort in the work of the gospel.`'
Notwithstanding our friend had been eminently attended with the power of truth,
and had great service several ways, he would speak very humbly of himself,
ascribing all the honor to the Lord; saying,
'`Although the Lord has made me serviceable in his hand,
what I trust in is the mercy of God in Jesus Christ;`' and added,
some friends sitting by him, '`The Lord visited me in my young years,
and I felt his power, which has been with me all along,
and I am assured he will never leave me, which is my comfort.`'

Near his conclusion, he often desired that he might be favored with an easy passage,
which was granted, and he was preserved sensible to the last:
passing away without sigh or groan, as if he was going to sleep,
the 20th of the Third month, 1725.
His remains were buried the 22nd of the same; aged about seventy-one years.
He was a minister about forty-five years.
