== Chapter 3

[.chapter-synopsis]
* Andrew Jaffray
* Thomas Thompson
* George Chalkley
* James Dickinson
* Benjamin Holme
* John Hayward
* Ellis Lewis
* John Gougii
* Rachel Moxham
* John Haslam
* Sophia Hume
* Ann Crowley
* Thomas Roylance

ANDREW JAFFRAY, of Kingswell, in Scotland, was born in 1650;
being the son of Alexander Jaffray, of the same place.
He gave his son, Andrew Jaffray, a liberal education; who,
becoming convinced of truth about the time of his father`'s death,
quickly came to esteem learning but as dross and dung,
compared with the learning and knowing Jesus Christ,
in his inward and spiritual appearance in the heart,
and being thereby purified from dead works, to serve the living God;
of which learning he soon became a zealous, faithful, and able teacher.

He cheerfully underwent great sufferings on account of truth;
and was a constant fellow-prisoner in Aberdeen, with David and Robert Barclay,
Alexander Forbes, Patrick Livingstone, and other early Friends,
in the long sufferings they underwent for the truth.
He was cheerfully given up to any service to which he found himself called;
particularly going through the streets of Aberdeen,
and to many places of worship therein, exhorting the people to repentance;
and it was particularly remarked,
that in the same streets where he had been reproachfully pointed at for the truth,
and his testimony`'s sake; he, in his latter years, was looked upon with affection,
and blessed as he passed along.
He went through many deep, bitter, and severe exercises of spirit,
by being made the butt and mock of people,
because of his zeal against a man-made ministry; yet the Lord supported him through all,
and he was preserved to bear a clear and faithful testimony
for the truth in the meeting of Friends in Aberdeen,
the very day before his illness.

He was confined to his bed for months, under the infirmity of old age, weakness,
and distress of body.
In the course of his illness,
he bore a very clear testimony to the goodness of God to his soul,
and mentioned the satisfactory remembrance he had,
of his being separated for the work of the gospel;
and that he had dedicated himself for that service, ever since his being called thereto.

He departed this life the 1st of the Second month, O. S. 1726, aged seventy-six years,
and was buried in his own burying-ground at Kingswell the 4th of the same.

[.asterism]
'''
THOMAS THOMPSON, of Saffron Walden, in Essex,
was born in a small village in the East Riding of Yorkshire,
and received a dispensation of the gospel ministry
in or about the twenty-fourth year of his age;
which, as he received freely, he preached freely, traveling in England, Ireland,
and twice in America, visiting Friends and laboring for the promotion of truth.

In the year 1727, it pleased the Lord to visit him with a consumption, under which,
after a time, he was kept in patience and resignation to the divine will.
A few days before he died, being under great weakness of body,
he was concerned to supplicate the Lord on account of his church and people;
which prayer was delivered under a tender sense and frame of spirit,
and affected those present.

A few minutes after, he expressed himself in this manner,
'`To those who inquire what end I make, let them know,
I die in the faith that saves and triumphs over death and hell;
through the mercy and goodness of God, finding no cloud in my way;
but perfect peace with God through Jesus Christ, the presence of whose glory is with me;
and I feel the comforts of his spirit attending me every day.
I never felt the like comfort before.
I may say, as was said of old, "`Comfort you, comfort you my people, says your God:
speak comfortably to Jerusalem, say to her, her warfare is accomplished,
her iniquity is pardoned,
for she has received double at the hand of the Lord for all her sins.`"
Thus has God dealt with my spirit; by his judgments refined me,
and prepared me for a habitation with himself, in his heavenly kingdom;
so that I may say, as David did,
"`Although I walk through the valley of the shadow of death, I fear no evil,
because you are with me; your rod and your staff comfort me.
You prepare a table for me in the presence of mine enemies; you anoint mine head with oil.
My cup runs over`" with praises to your glorious name,
you glorious Fountain of brightness, who took notice of me in my childhood,
in your love and mercy.
You compass me about with the bands of your salvation,
and you have made me yours forever: O, glory, glory, to your divine name and power,
you infinite Fountain of light and immortality.
My soul blesses you, and my spirit magnifies your name,
in the sense of that eternal word and wisdom that was in your bosom from eternity;
that intellectual light which shone everlastingly,
and will be a glory and crown to all them that believe and walk therein:
and in the faith of that I live and die.`'

At another time, being under the sense and power of truth, he said, '`Glory, glory,
to the excellent name of the Lord; the sweetness of his love can never be told;
the rays of his beauty shine upon me; I am filled with the power of his love;
glory be to his name forever!`'

A little before his departure he said, '`I have fought a good fight;
I have finished my course.
Henceforth is laid up for me a crown of glory,
which God the righteous judge shall give me at the last day; and not to me only,
but to all those who love his appearance.`'
And, just as he was dying, he said, '`Rejoice with me,
rejoice!`' and so departed this life in peace, the 30th of the Ninth month, November,
O+++.+++ S., and was buried the 3rd of the Tenth month, 1727.

[.asterism]
'''
GEORGE CHALKLEY, son of Thomas Chalkley, of Frankford, in Pennsylvania,
was a lad much inclined to read the Holy Scriptures, and other good books;
and was obliging and dutiful to his parents,
and ready and willing to do any service he could for his friends;
diligent in going to religious meetings, and an entire lover of religious people.
He was, in an uncommon degree, affectionately concerned for his mother,
doing whatever he could freely and cheerfully to serve her;
and told her not to do several things which he thought too much for her; saying, '`Mother,
let me do it, for, if I was a man, you shouldest not do anything at all,`'
meaning as to labor.
And she,
affected with his filial love and care for and towards her in her husband`'s absence,
would sometimes turn about and weep.

If this dear and tender youth, when reading, met with anything which affected him,
either in the Scriptures or other good writings, he would write it down,
and get it by heart.
One passage, which he had written down, and got by heart, much affected his father.
It was the 15th verse of the lvii.
chap.
of Isaiah: "`For thus says the High and Lofty One, that inhabits eternity,
whose name is Holy, I dwell in the high and holy place,
with him also who is of a contrite and humble spirit: to revive the spirit of the humble,
and to revive the heart of the contrite ones.`"

It was usual for his father to advise his mother,
not to set her affections too much upon him,
thinking he was too ripe for heaven to stay long on earth.
He was taken sick the 5th of the Eighth month, 1733;
and in his sickness behaved himself more like a wise
man than a child of ten years of age.
His father was in another part of the world, and he would gladly have seen him;
but he said that he should never see him more,
and desired his mother to give his dear love to him,
and to tell him that he was gone to his heavenly Father.
He was very fervent in prayer, in the time of his sickness;
and entreated that God would preserve his people all the world over.

One time, when in great pain, he prayed thus: '`Sweet Jesus, blessed Jesus,
give me patience to bear my misery and pain,
for my misery is greater than I can well bear.
O come, sweet Jesus, why are you so long in coming?
I had rather be with you, than in the finest places in the world.`'
One day he said, '`My misery and pain are very great; but what would it be,
if the wrath of God was in my soul.`'

His heart was full of love to his relations, acquaintance, and friends,
who came to see him in his illness;
and he took his last leave with a tenderness and sweetness which greatly affected many.

He departed this life the 13th of the Eighth month, 1733,
and his remains were carried to the Bank meeting-house in Philadelphia,
and buried from there the First-day following,
being accompanied by many friends and others.
He was ten years and seven days of age when he died; and,
as he was greatly beloved for the sweetness of his disposition,
he was greatly lamented by many who were acquainted with him.

His father returning home, and meeting with this trial, said,
'`Although it was a great and sore exercise and deep
affliction to me to lose this promising youth,
my only son, yet it was made tolerably easy to me;
for he departed this life in much brightness and sweetness,
more like an old Christian than a youth of ten years of age.`'

[.asterism]
'''
JAMES DICKINSON, of Cumberland, was born in the year 1659.
His parents, Matthew and Jane Dickinson, being convinced of the principles of Friends,
educated him in the way of truth; and the Lord, by his power,
reached him when very young, and often his heart was broken into true tenderness,
so that many times he had a secret delight in being
inwardly retired to feel the virtue thereof,
which was the cause of true gladness to his parents,
whose delight was in the enjoyment of the Lord`'s presence.
They were good examples to their children, educating them in the way of righteousness,
often exhorting them, with tears, to fear the Lord.

The following account of the first moving of the divine principle, or spirit of Christ,
on his mind, is extracted from a short journal of his, long since out of print.
'`My father,`' says he, '`died when I was ten years old,
and I not taking the counsel of the wise man, namely, to take counsel of my father,
which was, to mind the light or measure of grace given unto me,
my mind was drawn out after the vain plays, customs, and will-worships of the world,
in which state I continued some time.
Yet the Lord, by his power, did many times reach my heart, and,
by the Spirit of his dear Son, the Lord Jesus Christ, reproved me for my vain conduct;
many times calling me to return to him, from whom I had gone astray; whose power,
in some measure, I had felt to tender my heart.
But I, not minding to turn at the reproofs of wisdom,
but going on in rebellion against his blessed spirit, ran,
as with a multitude to do evil, into wildness and vanity,
until the Lord in his mercy did visit my soul by his righteous judgments,
and thereby turned my mirth into mourning, and joy into heaviness,
and deep sorrow was my portion.

'`Being warned to repent and turn to the Lord, a godly sorrow was begun,
which I experienced to lead to true repentance.
Then my familiars became my enemies, and I was a taunt and a by-word to them; yet still,
as I loved the Lord in the way of his judgments,
and waited upon him to know the way of them, I found the Lord to give victory,
and saw my greatest enemies were those of my own house; and the war was begun there.
As I was careful to keep in the light, I came to see the kingdom rent from Saul,
and given to David,
though there was a long war between the house of Saul and the house of David,
yet as I kept my eye unto the Lord,
I came to see the house of Saul grow weaker and weaker,
and the house of David to grow stronger and stronger.
Yet many were the days of mourning and nights of sorrow my soul went under,
that I may say it was the day of Jacob`'s trouble, and of Joseph`'s affliction.
Many times I cried unto the Lord, O that I had a cave in the ground,
that I might mourn out my days, that in the end I might find peace with you.
In those deep afflictions and exercises, the Lord was very near,
and often mixed mercy with judgment,
so that my soul began to delight to wait upon him in the way of his judgment,
seeing it was by the spirit of judgment and burning that
the filth of the daughter of Zion must be done away.
As I kept here, I felt the love of God to increase in my soul, which deeply affected me,
and a hunger was increased in my heart, after the enjoyment of the Lord`'s power,
and the operation of it, whether it was in mercy or judgment.
So I knew my faith to be increased in the sufficiency of the power of God;
then I saw "`it was good for me that I was afflicted,
for before I was afflicted I went astray.`"
I found, as David said,
"`his rod and his staff comforted me;`" and the Lord
did often overcome me with his love.`'

When about eighteen years of age, he was first concerned to bear a public testimony.
'`Great,`' says he, '`then was my exercise.
Seeing the work to be very weighty, and looking at my own weakness,
made me unwilling to give up to answer the Lord`'s requirings.
But the Lord, in his great love filled my soul with the emanations of his power,
which strengthened and encouraged me,
that I was made willing to give up in obedience to his divine will.
In great dread and fear I stood up and bore a public testimony in our own meeting,
warning Friends to be more inward and faithful to the manifestations
of his light and grace in their souls;
and, after I had answered the requirings of the Lord,
I found great peace flowing in my soul; which so prevailed upon my spirit,
that I was bowed down under the sense of the Lord`'s goodness,
and the weight of the exercise which I had felt upon me was removed.`'

He visited Ireland twelve times, and was three times in America,
once in Holland and Germany, and labored much in his native country of England,
and many were convinced through his ministry.
He was very tender to the youth, a nursing father to the least,
and full of charity to all rightly anointed, yet not hasty to join with forward spirits.
He was also careful not to join in party,
but was greatly concerned for the promotion of truth.

About a year before his death he was struck with the palsy,
which deprived him of the use of one side,
and his speech was in a great measure taken from him;
yet he seemed to surmount the decays of expiring nature, and,
in a sweet and heavenly disposition of mind, intimated his day`'s work was done,
and that God whom he had served was still with him,
and that he had the evidence of peace and future felicity sealed upon his soul,
and was only waiting to be removed; but was fully resigned unto the Lord,
to wait his time.

To a friend who visited him, he expressed himself to the following purport:
'`I have served the Lord and his truth in my generation,
and now I feel the blessed reward thereof.
The accuser of the brethren is cast down as to me,
and my peace with God is sealed forever.`'

He departed this life on the 6th of the Third month, O. S., 1741,
and was buried the 8th of the same, aged about eighty-three,
and a minister sixty-five years.

[.asterism]
'''
BENJAMIN HOLME was born of parents professing with Friends about the year 1682, who,
as he grew up, took him along with them to meeting.
Nevertheless he exceeded many in wildness and vanity,
until it pleased the Lord so to touch his heart with his divine power and love,
as to bring him under a concern in his very tender age, for peace with God.
His exercise was great at that time,
and he walked often alone in fields and secret places, seeking the Lord,
that he might not miss peace to his soul.
As the love of God prevailed in him, his love to God and his people increased,
and he grew zealous for meetings, and was often bowed and tendered in them.
His mouth was opened in supplication to the Lord, and in testimony,
when about fourteen years of age; and, growing in the ministry,
he travelled abroad to visit Friends when about seventeen years of age,
accompanied by Joseph Kirkbride of Pennsylvania, and Leonard Fell.

He was a man devoted to the service of truth,
and labored almost incessantly in the work of the ministry, in this nation, Wales,
and Scotland; was several times in Ireland, twice in Holland, and some parts of Germany;
and in the year 1715, he took shipping for America,
and visited Friends on that continent, and most of the West India Islands.
In the course of his labors and travels, several were convinced by him; many,
through his innocent carriage, as well as by his ministry,
which was delivered in that plainness which becomes the simplicity and purity of truth,
have been reached and brought to judge and speak favorably of Friends,
and their Christian principles.
In the latter part of his time,
he was concerned to hold meetings in many places where no meetings of Friends had been.

His ministry was adorned with good conduct.
He sought the good of all with sincerity,
and was engaged to speak his mind with prudence and caution, both to old and young,
and had a persuasive faculty in his exhortations beyond many,
and was strictly careful not to divulge what he saw amiss in any, to others.
He envied not, nor detracted from any; but lived in universal love and goodwill to all.
It was his daily food to be found doing the will of God.

In his way to Haverford-west, to the yearly meeting for Wales,
being in a poor state of health, he was prevailed on to stay at Paul Bevan`'s, at Swansea,
and attended two meetings there on a First-day;
but being soon after taken with a fit of the ague, he was confined to bed,
and proper care was taken of him.
He appeared to be quite easy and resigned, and told Friends there in his illness,
that it was a fine thing to make a right use of time,
both with respect to this life and that which is to come;
and often desired that Friends in that place might be good examples to their neighbors;
that they might be brought from their forms of will-worship to the divine counsel,
and then all would be safe and well.
He reached Swansea the 8th of the Second month, 1749, and died the 14th of the same,
aged about sixty-seven years, and a minister about fifty-three years;
and as he lived so he died, a pattern of meekness and innocency.

[.embedded-content-document.epistle]
--

=== Benjamin Home`'s Last Legacy, or Serious Advice; recommended by him, a little before his decease, to the youth under the tuition of several schoolmasters.

[.salutation]
Dear Children,

I hereby tenderly salute you, with desires that as you advance in years,
you may in grace, that so like good Samuel,
you may grow in favor with the Lord and good men.
Virtuous and pious living will not only very much
recommend you to the better part of mankind,
but it is the way to obtain the blessing which makes rich, and adds no sorrow with it.
Live in love and peace; speak lovingly and meekly one to another; and if you behave well,
you will be a credit to your master and to your friends.
Make good use of your time; strive to excel in learning, and in the best things.
If you live in the fear of God, and take good ways,
and it should please the Lord to spare you, you may be serviceable in your generation.
John, the holy man of God, told the elect lady, whom he wrote to,
that he rejoiced greatly, that he found her children walking in the truth;
and to be sure it would be a great comfort to many of your parents and good friends,
to have you take good ways.
If any of you should be put out to trades, if you are honest, peaceable,
and careful to speak the truth,
and to make a good improvement of your time while you are at school,
so that the master can give a good account of you,
his good recommendation may be a means to help several of you to good places.

'`Dear children,
"`remember your Creator in the days of your youth,`" and
consider the obligations which you are under to serve him,
who is the author of your being,
and the fountain from whom all the good things which you receive come.
As the wise man says, that "`God hates a proud look, a lying tongue,
and him that sows discord among brethren,`" be sure that you hate to tell an untruth,
and have a care of being proud; because we read that "`Pride goes before destruction,
and a haughty spirit before a fall.`"
I would have you to guard against a quarrelsome spirit and temper,
and if at any time any ill-natured people should call any of you unbecoming names,
be sure that you do not give one harsh or unhandsome word for another,
nor render reviling for reviling; but remember that the wise man says,
that "`A soft answer turns away wrath;`" neither give flattering titles to any.
Remember Elihu said, that "`he accepted no man`'s person,
nor gave flattering titles to man, lest his Maker should soon take him away.`"
Now, although I advise you not to give these compliments,
which may tend to gratify a vain and proud mind;
yet I would have you learn to speak handsomely and becomingly to every body,
even to the poorest servant or apprentice about any of your parents`' houses,
or to the beggar who asks alms.

Seek and pray, like good Jabez, that the Lord may keep you from evil;
and we read that God granted him that which he requested.
The fear of the Lord is a great blessing to all them that live in it.
It is a fountain of life, which preserves from the snares of death;
and if you would not be drawn into any evil or hurtful things,
I would have you be very choice of your company,
which often has great influence upon youth.
Remember the wise man`'s counsel, "`My son,`" says he, "`if sinners entice you,
consent you not.`"
Many good-natured people have been ruined, to a great degree,
through hearkening to the enticements of sinners; but they are wise,
who learn by others`' harms to beware.
Love to read the Holy Scriptures, and other good books, avoiding such as are pernicious,
which may tend to corrupt, or make bad impressions on your tender minds.
I very much desire that you may be prevailed upon by the power of divine life,
to bear the yoke and cross of Christ in your youth;
that in the end you may witness that peace which
the world can neither give nor take away.
That you may make a right and good application of this friendly admonition,
and have the benefit hereby intended, is, with true love to you, the sincere wish of,

[.signed-section-closing]
Your Friend,

[.signed-section-signature]
Benjamin Holme

--

[.asterism]
'''
JOHN HAYWARD, of London, was born of reputable parents, not of our Society,
who gave him an education suitable to the station in which they intended to place him.
When of proper age, he was put under the care and tuition of an eminent surgeon.
During his apprenticeship, he was favored with a powerful visitation of divine love,
which eclipsed the prospects of temporal greatness; and things permanent,
objects of a higher nature, were presented to his view;
and to seek after durable riches and righteousness,
became the principal bent of his mind.
Being thus in an earnest pursuit of substantial good, an external show of religion,
in an observation of ceremonies, afforded him no solid peace;
nor could he reap any benefit under a ministry not attended with divine power and authority.
His understanding being opened, his inward conflicts and exercises increased,
and the language of his disconsolate soul was,
'`Can you tell me where the beloved of my soul feeds his flock,
or where the fold of true rest is to be found?`'

About the twentieth year of his age, he was made willing to take up the cross,
and sit down in silence among a despised people,
to worship the Father in spirit and truth.
He was effectually convinced,
and having attained to some degree of establishment in religion,
it became his duty to confess Christ before men,
and to express the religious sentiments he had embraced,
by the reformation of his whole conduct and demeanor.

Such a visible alteration caused him to become a wonder to his acquaintance;
but his conversation being very circumspect and truly religious,
accompanied with great modesty and affability,
their prejudices and misapprehensions were removed,
and upon all occasions they manifested an affectionate regard for him.

Having lived near the divine principle, or Spirit of truth,
and under the forming hand of the Lord, who prepares for service in his church,
he appeared in a public testimony about the thirtieth year of his age,
which was well received and truly acceptable.
He did not find it his concern to travel much abroad,
yet visited some of the western and southern counties, and some neighboring ones,
to his own satisfaction, and the comfort and edification of Friends.

He early declined the profession of surgery,
and with great caution entered into the concerns of trade,
keeping a watchful care that he should not dishonor his high and holy profession.
But a few years before his death he removed to Plaistow, in Essex, where he lived,
not to himself alone, but to his friends and the public,
seldom omitting proper opportunities of promoting
love and good works by precept and example.

He gradually declined, without much pain, and at times he was cheerful and easy,
discovering to those who were about him a mind occupied about a better world;
occasionally mentioning, yet with due fear of presuming, that though nature might shrink,
and be apprehensive for the dissolution of the frame,
yet he felt nothing beyond it to give him pain, but a steady hope of the reward of,
"`Well done.`"

A few days before his decease, a friend visiting him, he signified to him,
that all was easy, and that his day was nearly over.
He departed this life the 20th of the Second month, 1763,
and was buried at Bunhill Fields the 27th of the same, aged eighty years.
A minister about fifty years.

He left a considerable part of his substance to trustees, as a permanent fund,
the interest whereof to be given to poor Friends, at their discretion;
which proves a comfortable relief to a considerable number.

[.asterism]
'''
ELLIS LEWIS, an ancient Friend of Tyddin y Garreg, near Dolgelly, in Merionethshire,
North Wales,
was born of parents professing the truth as held by the people called Quakers;
and in his very tender years was favored with a visitation of divine love,
which had such an effect on him that he appeared in a public testimony,
about the thirteenth year of his age, in the English language,
to which he was not accustomed, in a remarkable and tendering manner.

He continued faithful, and travelled in the work of the ministry several times,
through the principality, and likewise in several parts of England,
adorning the doctrine he preached by an innocent life and conduct,
and well esteemed by Friends in many parts where he came.

A few years before his death, the infirmities of age rendered him incapable of traveling;
yet he retained a lively sense of truth, and love to his brethren;
having that ornament of a Christian mind, a meek and quiet spirit.
Being patiently resigned to the divine will, he laid down his head in peace,
the 23rd of the Eleventh month, 1764, and was buried in Friends`' burial-ground,
at Tyddin y Garreg, the 28th of the same, aged eighty-seven,
and a minister seventy-four years.

[.asterism]
'''
JOHN GOUGH, son of James Gough,
was a young man of a good natural disposition and capacity,
well furnished with useful learning; and as he grew up,
being favored with deep religious impressions, he sought after and attained best wisdom,
to a degree in general exceeding his age.

On his entrance into active life, a propriety and steadiness of deportment,
that might adorn advanced years,
attracted the notice and respectful regard of the best Friends who had
the opportunity of observing or being acquainted with him.

He was a dutiful son, an affectionate brother, an exemplary pattern of plainness,
sobriety, and circumspection of life,
giving evident indications he was early acquainted
with the grace and truth which came by Jesus Christ.
He was, for a season, an assistant to his father in his school,
but meeting with an opportunity of engaging with a Friend of London as a clerk,
he removed there;
in which station he conducted himself with fidelity
and honor during the short time he continued in it.
Being taken ill of a fever, which terminated his life, he said,
a little before his departure, '`I have done all that I had to do, and must now go home.`'

He departed this life about the Tenth month, 1769, aged nearly twenty-one,
and was buried in Friends`' burial-ground, at the Park, Southwark,
after a very large and solemn meeting, in which the hearts of many were tendered.
His father, writing concerning him, says, '`Through divine favor and assistance,
I freely give him up; thankful for having such a son,
who has left behind him too few like him in pure unmixed goodness,
which diligently exerted itself to do well.`'

[.asterism]
'''
RACHEL MOXHAM, daughter of John and Esther Moxham, of Melksham, in Wiltshire,
was of an innocent and mild disposition, but fond of company,
so that it appeared needful to her mother to be watchful over her on that account.
About the fifteenth year of her age,
religious impressions were observed to fix on her mind, so that she became sedate,
loved retirement, and was mercifully taught how to wait, and what to wait for.
One evening, after a silent opportunity of mental introversion,
she said to her mother nearly as follows:
'`I have thought it my duty to thank you for your care in
preventing and restraining me from unsuitable company,
which I took hardly.
I believe, had I had the liberty I coveted,
I should not have known the peace and comfort I now
feel in obedience to the principles of truth;
but should have gone in the broad way that leads to death.`'

She continued steadily serious, looking towards the recompense of reward;
and a few days before her decease, expressed a desire to attend the quarterly meeting.
She accordingly went; and a Friend had there to mention the uncertainty of time,
and the comfort of having, in a dying hour, hope towards God.
This she took to herself, and said, that evening, her work was nearly finished.
The quarterly meeting was on a Second-day;
and the Sixth-day morning following she complained of illness.
In about two hours after, her parents were so apprehensive of danger,
as to be affected with sorrow, which she observing, said, '`Do not grieve for me,
but rejoice evermore, and give thanks that I am going to everlasting rest;`' then said,
'`I hope,`' paused a little, and added, '`I am going to everlasting rest and peace.`'
She expressed to a friend the sense she had of her departure;
and hoped the Almighty would be near,
and sustain the spirits of her parents under the trial, as he did hers at that time.
She settled herself in the bed, and took leave of her friends,
under the influence of such a sweet and awful solemnity
as much affected the minds of those present,
no words being spoken, except her saying, '`Lord receive my spirit.`'

Thus she quietly departed, after about eight hours`' illness,
on the 20th of the Third month, 1772, aged nearly eighteen years,
and Friends were favored with a remarkably solemn meeting at her interment, the 24th,
at Melksham aforesaid.

[.asterism]
'''
JOHN HASLAM, of Handsworth Woodhouse, in Yorkshire,
was of a sober and innocent disposition from his infancy.
His parents dying when he was young,
the care of his education devolved on Gilbert Heathcote, a physician.
Early giving up to a precious visitation from on high, he was prepared for service,
and called to the work of the ministry about the 25th year of his age.
He was soon drawn forth in the love of the gospel frequently
to visit the churches in various parts of this nation.
He visited Ireland twice, and Holland once,
and paid a general visit to Friends in most of the colonies in America.
He was exemplary in a deep inward exercise of spirit,
and in patient waiting for the arising of the divine life,
as a necessary qualification for service either in ministry or discipline, '`Being,`'
to use his own words addressed to ministers in an epistle found among his papers,
'`a strength to a living, edifying ministry,
and a check to that which was forward or floating; either not duly anointed,
or not waiting truly for the resurrection of that
life which reaches the witness in others,
and opens into the treasury, where wisdom to divide the word aright is received.`'
He had a clear discerning of the opening of the heavenly gift,
and was careful to give way to the requirings thereof, and was well accepted therein,
yet he was often proved with deep inward poverty;
and in imparting something of his experience in that respect to a friend,
who remarked it was a safe state, he replied, he knew it to be so,
but that it was possible sometimes to be depressed too low for the gift.

He was remarkably endued with patience and resignation in the loss of his wife, and,
in some years after, of an only daughter, whom he survived about six years;
and though her tender care over him was well supplied, yet, being far advanced in years,
his bodily strength and memory gradually declined.
He became incapable of attending meetings for about three years before his decease;
yet he expressed great satisfaction with the visits of his friends,
and appeared to be in a patient, resigned, and innocent frame of mind.

As his natural strength was thus worn out by almost imperceptible degrees,
he was divested of this state of mutability, without much appearance of pain,
the 4th of the Tenth month, 1773, and interred on the 6th of the same,
in Friends`' burial-ground at Handsworth Woodhouse, aged eighty-three years,
and a minister about fifty-seven years.

[.asterism]
'''
SOPHIA HUME was born in South Carolina, and was descended, on her mother`'s side,
from the stock of friends.
Her grandfather was William Bayley, formerly a Baptist preacher at Poole,
but was early convinced of truth, and became a living, powerful minister.
Her grandmother was Mary Fisher,
who was one of the first friends that visited New England in the year 1656, and who also,
before her marriage with William Bayley, about the year 1660,
under a great concern of mind, went to Adrianople, to visit the Great Turk:
the particulars of which are related in Sewel`'s History.

Her mother continued in profession with friends, but marrying out of the Society, this,
her daughter, was educated agreeably to her father`'s mind;
and for a considerable time took great delight in
the pleasures and delusive amusements of this world.
About the thirty-eighth year of her age her judgment was
opened to see the vanity and folly of these practices;
and she, in measure, forsook them,
but was not fully convinced of the principle of truth
in her own mind until about the year 1741,
when, having Barclay`'s Apology by her, she looked into it, as she often expressed,
to furnish herself with matter for conversation;
but in the perusal of it her judgment was convinced of the truth of friends`' principles:
she joined the Society, and became a steady, exemplary member.

She came afterwards from South Carolina to reside in London, and about the year 1747,
a concern came upon her to visit the inhabitants of her native country,
from which she sent the following account in a letter to a friend.

[.embedded-content-document.letter]
--

A concern I had often felt in my soul for the happiness
and eternal welfare of my native country revived in my breast;
when I was to return and abase myself, by telling what God had done for my soul,
and to call them from those things,
in which I had often run to an excess of riot with them; and from which I had been,
by the great love and powerful hand of God, brought and redeemed.
When I arrived in Carolina, I found it my place and duty to keep meetings,
with those few that professed with me; and though, at first,
the meetings were sometimes interrupted by the rude and uncivil treatment of many,
we met pretty quietly,
and some of the inhabitants would now and then come and sit with us,
to whom my mouth was opened at times in rehearsing what God had done for my soul.

--

During her continuance there,
she wrote a short account of the dealing of the Lord with her,
which was soon after published.
From there she went by land to Philadelphia,
a journey of between eight and nine hundred miles; and after her return from America,
under a tender concern, she labored, both by word and writing,
to bring people to believe and live under that divine principle, the spirit of truth,
which she had found, by happy experience, to be as a fountain of life.

In her private station she adorned the gospel by a life of humility and self-denial,
and was zealous against all superfluity, both in dress and furniture.
Thus preserved through a course of many years,
towards the close of her time she appeared in remarkable tenderness, and,
as if she were sensible that her dissolution was approaching, she gave directions,
in several respects, relating to her burial, with much composure.

On the 26th of First month, 1774, she was suddenly taken ill, and,
being seized with an apoplexy, in about twelve hours departed this life.
After a very large and solemn meeting at Gracechurch-street meeting-house, London,
her remains were interred in Friends`' burial-ground near Bunhill Fields.
She was nearly seventy-three years of age, and about twenty-five years a minister.

[.asterism]
'''
ANN CROWLEY, daughter of Thomas Crowley, of Gracechurch-street, London,
being seized with illness, which continued for several months,
was preserved in much patience,
and uttered many expressions which showed the fervency of her mind.
At one time she expressed herself thus: '`The pains of death are hard to bear,
but I am sensible they are not on me now, but they are near approaching;
death is no terror to me.
O death, where is your sting?
O grave, where is your victory?
My dear tender mother, it will be a bitter cup; but it is the Lord`'s preparing,
and therefore drink it willingly.`'
Being removed into the country for the benefit of the air,
she expressed herself to the following effect: '`This is hard work;
it is indeed hard to bear, but the Lord is with me in these trying moments.
I did not think my dissolution was so near, but I am ready, Take me, Father,
take me to yourself this evening, if it be your will,
for I long to be with you in paradise.
Though I have endured so many moments of agonizing pain,
the Lord has been my support through the whole, and, I doubt not,
will continue to be with me to the end.
Oh, Father!
Father!
Father! bow the heavens, and come down;
be with your people universally all the world over.
Why do you weep?
Weep not for me, but give me up to the Lord, for I am happy;
far happier than I can express.
I wish every one of you could feel what I feel at this time, for it is beyond expression.
Oh, it is like a heaven upon earth;
it has not entered into the heart of man to conceive what
good things God has in store for them that love him.`'

To one of her sisters she said, '`Oh! my sister, give up, give up now,
in the days of your youth; for the Lord loves an early sacrifice.
Oh, prepare yourself! lest it should please the Lord
to cut you down in the flower of your youth.`'

About two weeks before her departure,
she earnestly prayed that it might please the Almighty to take her that night,
and expressed herself as follows:
'`You have been pleased to give me a taste of your goodness, and a sight of your glory,
and it is glorious indeed; but, oh, Father!
I long to be with you, that I may enjoy it in a more plentiful manner.
The gates of heaven are open to receive me.`'
She said, '`I have never murmured at what it is the Lord`'s will I should suffer;
but I was content if the pain had been much greater,
if it was the will of my heavenly Father.
Oh, Lord!
I long to be with you,
where my soul shall join the angels and archangels that are in heaven.`'
She further added, '`It is my desire that you, my tender brothers and sisters,
may come to the same experience.
I was nearly visited, long before I was laid on this bed of sickness; if I had not been,
it would be miserable indeed: '`and a little after,
'`My spirit was warmed in the renewing of your love.`'

About six days before her close,
she sent for her three brothers separately to her bedside; and,
in a most affectionate and tender manner, cautioned them against the gaiety, riches,
and grandeur of the world; and exhorted them to walk in the path of virtue,
to keep close to divine instructions, and likewise to watch and pray continually: adding,
'`I feel it needful, even on my deathbed.`'
To one of them she said, '`Give up, O give up;
remember the fear of the Lord is the beginning of wisdom.
Seek you that wisdom now in the days of your youth.
Step gently along, and keep your mind low and humble before him.`'
After lying still a little time, she said, '`Though painful my nights,
and wearisome my days, as Samuel Fothergill said,
yet I am preserved in resignation and patience.`'

Some friends visiting her, she expressed to them, '`My pains of body are great,
but my dependence is on the Lord, and my only comfort is in him.
I thought from the beginning that I should not get over it;
but within these three weeks I have seen clearly I shall not.`'
She further observed, that she had been visited long before her illness,
and had found great uneasiness in wearing things that were gay,
and also in speaking in the plural language to one person; and added,
that she found it difficult to take up the cross, but when she did,
her satisfaction was great.
'`Oh! what I feel for those whose minds are involved in the world,`' with much more;
all importing the happy state of her mind; saying to one friend, '`I am ready,
I have nothing to do but die.`'

She particularly requested of her father, that after her decease,
her body might be buried from Devonshire-house meeting; and desired,
that the young folks of that quarter, in particular, might be invited to attend;
hoping it might prove a profitable time to them.

The evening preceding her departure,
she spoke to one of her sisters to the following effect: '`Gaiety proceeds from pride,
and pride is the root of all evil: '`and she fervently exhorted against it.`'

In the night her pains were exceedingly great, and she felt the approach of death;
and in the last two hours continued uttering prayers.
Calling for her mother, on her coming to her she said, '`Farewell:`' and expired,
the 12th of Second month, 1774, being not quite seventeen years of age.

[.asterism]
'''
THOMAS ROYLANCE, of Newton, near Middlewich, in Cheshire;
was born of parents professing truth; who,
having been weightily concerned for its promotion, and sufferers for its testimony,
had a great care of his education; which had a good effect on his mind,
as appears by his own account in manuscript, as follows: '`I was through divine favor,
early inclined to the love of truth,
and to seek after it to the best of my understanding, often seeking places to pray,
and pour out my soul to the Lord,
in beseeching him for wisdom and strength to enable
me to persevere in well-pleasing to him.
And blessed, magnified, and eternally praised be his holy and most worthy name;
he has many times, in his own time, answered,
and caused my cup to overflow in praises to his name, and admiration of his goodness.
My soul, being as a well watered garden, has rejoiced in his love; and,
in abasedness of self, has largely ascribed praises and glory to him, who,
with the Son of his love, through the Holy Spirit, is eternally worthy.
Amen.

'`I early loved good men, and had a desire to go to meetings;
so that while I was but very young, if anything offered to let or hinder my going,
I can remember I have wept to go, though four miles distant from us.
I can also remember, that in my very young years, I loved to be speaking of good things;
and often found it my place to reprove boys that were my companions,
and sometimes others, for unsavory words, or anything unseemly.
The Lord always sufficiently helped me,
though it was with persons of greater age and capacity, as to the outward, than myself,
when I found my mind engaged to converse with them on religious subjects;
and as I grew up, I had great love to truth, and honest, sincere friends;
in whose company and good conversation I much delighted.`'

He was much given up to the service of truth;
and much concerned that the discipline of the church
might be managed in a weighty and proper manner.
He was an example of plainness,
and zealously concerned to warn those who took undue liberties,
and was helpful in opening the understandings of many.

About the sixtieth year of his age, he came forth in a few words in the ministry,
which was acceptable and edifying.
He left a few remarks on that subject, worthy to be preserved.

'`Although,`' says he, '`there have sometimes been words in my heart, and, as it were,
in my mouth, which I do not know but they might have been of ease to myself,
and of service to others, had I delivered them;
and I have been spoken to by some Friends, both in a private and public capacity,
or station, thereon; but was always forbearing and backward that way,
and have been afraid of too much forwardness in some, who,
I have been and still am afraid, have not edified thereby.
+++[+++I had]
always a fear of, and a dislike to, the noise of the tool,
the working of self and the creature, in our meetings,
as it was not to be heard in the building of the Lord`'s house or temple of old.
But that ministry which comes with a true flow from the divine spring,
having its evidence and authority with it, I still loved, and greatly do love,
and the vessel it flows through, for its sake, whether it be in rebukes or consolation,
as the Almighty is pleased to give, and the case may require.
Whether it may be more or less, it is beautiful; and if rightly received,
it is comfortable and edifying.`'

He died the 25th of the Second month, 1774, in the seventy-third year of his age,
at his house at Newton, after about two weeks`' illness, which he bore with patience;
expressing, near his conclusion, that all was well.
