== Chapter 4

[.chapter-synopsis]
* Ambrose Williams
* Hannah Ludgater
* Sarah March
* Sarah Harris
* Samuel Waring
* Rachel Wilson
* Mary Prideaux
* Joseph Oxley
* Deborah Waring
* William Fry
* Joseph Jackson
* Ann Mercy Bell
* Rebecca Shewell
* Ann Leaver

AMBROSE WILLIAMS, of Pont-y-pool, in Monmouthshire,
was educated in the national way of worship; but, being dissatisfied therewith,
and humbly desiring to be rightly directed, he came to a meeting of Friends, in which,
though held in silence, his heart was replenished with divine love; and,
through the teachings of this divine principle,
he came to experience that the work of righteousness is peace;
and in a few years had his mouth opened to testify to the sufficiency thereof.

He was a constant attender of meetings for worship and discipline;
and a diligent laborer therein on his own account and that of others,
that none might live as in ceiled houses, and let the house of the Lord lie waste.

By his exemplary life and conduct, and great love to his friends and neighbors,
it may be justly said, that he was "`An Israelite indeed, in whom there was no guile.`"

The First-day before his departure, he attended the morning meeting at Pont-y-moil,
though weak in body; and, in a solid, weighty frame of mind,
earnestly recommended all to do their day`'s work in the day time; signifying,
that perhaps he might be the first called from works to rewards;
that he had nothing lay in his way, but had done his day`'s work,
having set his house in order.

He departed this life the 16th of the Third month, 1774; aged sixty-two,
and a minister about thirty-three.years;
and his body was decently interred the 20th of the same at Pont-y-moil.

[.asterism]
'''

HANNAH LUDGATER, of Coggeshall, in Essex, wife of Robert Ludgater, of the same place,
was born in Hampshire, and had her education among Friends;
but in her early days she left the Society, and frequented other places of worship.
In this unsettled state, it pleased the Father of mercies to enlighten her understanding;
so that through the powerful operation of his love,
she saw wherein she had missed her way, became again united to Friends,
and in due time her mouth was opened to tell others what she had felt,
and to invite them to come, taste, and see how good the Lord is.
In this service she was engaged to travel both before
and after her marriage with Robert Ludgater.

She resided for some time in the Isle of Wight, and afterwards,
on her first coming to London,
lived as housekeeper with a person not in religious profession with Friends;
where her innocent and virtuous deportment gained her much esteem,
and the Society for her sake.
She was an affectionate wife,
and much concerned to promote the discipline of the Society among her own sex,
and was a true helpmeet to her brethren; of a weighty and discerning spirit,
accompanied with diligence in laboring for the advancement of truth;
though often pressing through great discouragements arising from bodily infirmities;
which frequently rendered her incapable of attending meetings.
She suffered great pain of body for the last six months of her time,
under which probation her patience and resignation manifested
the happy effects of faithful labor in the day of ability.
Being steadfast in her dependence on the author of her faith,
she had at times access to the fountain of life; under the sensible enjoyment whereof,
she said, '`O how I long to be relieved;
I have no doubt but I shall be mercifully relieved.`'
To a friend who visited her, she said,
'`I have been in a good degree faithful in our meetings,
and have not to charge myself with omitting one journey,
when it was made known to be my duty.
O how have we gone forth, poor and empty;
yet have not lacked! the Supporter has been near, and richly furnished.`'

She departed this life the 28th of the Third month, and was buried at Coggeshall,
the 3rd of the Fourth month, 1774, aged about sixty-five years.

[.asterism]
'''

SARAH MARCH, of Durham, was born in London; and taking heed to the divine light,
which shone in her heart, she had to bear testimony thereto, about the year 1753;
in which service she labored faithfully to promote the same principle in others;
and gave evident proofs of the efficacy thereof by an exemplary deportment.

A little before her death she wrote the following paper,
which she desired might be read in the several meetings in the county,
which was done accordingly.

[.embedded-content-document.paper]
--

[.salutation]
Dear friends

Under great weakness of body,
my concern remains strong for your growth and prosperity in the blessed truth.
In that love which I feel shed abroad in my heart does my spirit salute you;
beseeching you to meet as in the presence of God;
in reverence and humility wait upon him, who is indeed the dread of nations;
and I trust our God will graciously condescend to
overshadow your assemblies with his power,
which brings salvation; and to crown them with his blessing, which makes truly rich,
and adds no sorrow with it.
Let me entreat that no restlessness or impatience may prevail,
although the Lord of life and glory should tarry;
for he will most certainly arise in his own appointed time, with healing in his wings,
for the sake of his own wrestling seed, that are waiting for Israel`'s consolation.
If this be your situation before the Lord in-secret, he will reward openly,
and you will be enabled to praise God acceptably,
and to magnify his great and worthy name; as does my soul at this season,
because I feel the same divine goodness that was my morning light is now my evening song,
which makes me rejoice in the Lord; and my joy no man can take from me.

--

She departed this life the 29th of the Fifth month,
and was buried on the 2nd of Sixth month, 1774,
in Friends`' burial-ground in the city of Durham; in the forty-fifth year of her age,
and a minister about twenty years.

[.asterism]
'''

SARAH HARRIS, of Chipping Norton, in Oxfordshire, widow of Nicholas Harris,
of the same place, was born about the year 1704;
but no account is come to hand of her early youth,
except that while she was a servant to a Friend at Banbury, in the same county,
she was a sober, religious young woman.
Through obedience to the principles of truth, she became useful in her day;
and was of a gentle, affable, kind, and charitable disposition;
a true lover of the religious of all denominations; and one who liberally administered,
in proportion to her circumstances, to the poor and afflicted.

About the forty-sixth year of her age,
she was concerned to bear testimony to that hand which had supported and preserved
her in the various dispensations she had to pass through in life.
She discovered a deep humility and sensibility of her own weakness and unfitness,
as she thought, to be employed in the important work of the gospel ministry;
as she knew and felt it to be an awful undertaking,
and not to be performed in the policy, strength, and wisdom of man;
but in the power and wisdom of God.
Her calm and contented waiting and resignation, before she appeared in meetings,
indicated her keeping invariably in remembrance the injunction of her Lord to his disciples,
namely:
"`Tarry you in the city of Jerusalem until you be endued with power from on high.`"
This laudable diffidence, Christian circumspection, and resignation of soul,
rendered her services very acceptable to such as could taste and
feel that the source of her ministry was the spring of life.

In her last illness, it was apparent to many who visited her,
that she had made provision for a blessed eternity;
and that a lively feeling of divine refreshment was
her support under bodily infirmities and decay.
The visit of death was not unexpected, nor was she unprepared to sustain it.
A sense of dependence and of gratitude, the foundation of true piety,
continued with her to the last; and many comfortable expressions were uttered by her,
in the course of her illness.

She often advised against too anxious a care about the business and things of this world;
and often desired she might be favored with patience to bear her affliction.

One day, after lying still some time, she said, "`They that wait upon the Lord,
shall renew their strength.`"
At another time, to those of her family and friends present, she said,
'`I have desired for you now, as well as at many other times,
that the blessing of heaven might attend;
but there must be a living up to what you know.`'
At another time she said,
'`Let it be the business of your lives to be prepared for such a time as this.`'
Speaking to a person who made inquiry after her welfare, she said,
'`The Lord is my shepherd, I shall not want.`'

It being meeting-day, she said, '`Go to meeting all that can;
and O that my spirit may be refreshed with yours!`' She also advised
not to let business hinder from going to week-day meetings.

She signified that when she gave up to speak a few words in meetings,
it was in great simplicity and fear; and that she witnessed peace in it,
being very careful to wait for divine qualification; and she humbly trusted,
and could say in humility and thankfulness, she never was confounded.
She departed this life in great calmness and peace the 22nd of the Sixth month, 1774,
and was buried the 30th of the same in Friends`' burial-ground at Chipping Norton;
aged seventy-one, and a minister twenty-five years.

[.asterism]
'''

SAMUEL WARING, of Alton, in Hampshire, was the son of Jeremiah Waring of Witney,
in Oxfordshire.
Being favored with the benefit of a religious education,
and yielding to the sanctifying operation of truth,
the Lord was pleased to prepare and qualify him for his service.
He came forth in a public testimony about the 25th year of his age;
and being faithful in the exercise of his gift, he grew therein,
and became an able minister of the gospel.
He was exemplary in his attendance on meetings for worship and discipline;
a diligent attender of the yearly meeting in London upwards of fifty years;
and though not forward in speaking, yet his retired and awful sitting therein,
furnished an edifying example to the attentive observers.
At different periods of his life, he visited friends in South Wales,
the west of England to the Land`'s End, all the southern,
and several of the midland and eastern counties in this nation;
and some of them several times.
In these visits we have cause to believe his service was acceptable;
for being humbled into a deep sense of his own weakness and insufficiency,
as well as the weight and importance of such services, he was not hasty in moving,
but waited for a clear evidence, both as to the concern itself,
and also the proper time for engaging therein.

Having the weight of a large family, and a considerable share of business upon him,
he was steadily concerned that he might not be overcharged therewith,
to the hinderance of his services;
and with that view purposely shunned some flattering prospects of gain,
desiring nothing more than to provide things honest in the sight of all men,
that the ministry of which he had received a part, might not be blamed.
Thus having, through the blessing of Providence, made a comfortable, though moderate,
provision for a numerous family, he quitted business when in a flourishing state,
more than twenty years before his death;
spending much of the latter part of his time in reading and retirement.
He was much given to hospitality,
his heart and house being always open to receive the friends of truth,
in whose company he took great delight.
After having labored in word and doctrine for a long series of time, he was,
some years before his decease, gathered into humble silence,
seldom appearing in public testimony in meetings; but the patient,
resigned frame of his mind under this dispensation,
and his close inward travail in spirit, made it evident beyond all doubt,
that he retained his integrity, love, and zeal, to the end.
Conversing with some friends a few weeks before his departure,
he with great sweetness intimated, that his peace was sure.

During his last illness, which he bore with remarkable patience and composure,
he said repeatedly, that he had no desire either for life or death,
but felt his mind resigned to the Lord`'s will.
After meditating some time in silence, one evening he said,
'`I have been thinking of faithful Abraham, humble Isaac, and wrestling Jacob.
Abraham was called the friend of God, because he was found faithful.`'
Among other weighty and affecting expressions, he mentioned more than once,
that he believed a time of great calamity was coming over the nations,
and that afterwards there would be a gathering of the people to the principle of truth,
when they would flee to it, as doves to their windows.

The day before he died he took a solemn leave of several friends who visited him,
and the monthly meeting being next day, desired his love might be remembered to friends,
saying that he expected he should sit with them no more.

Two of his daughters sitting up with him the last night, and asking how he did,
he replied, '`I have fully as much pain as I can well bear;
but I have thought the Lord can cut the work short in righteousness;
and I hope to bear the portion allotted me with patience.`'
Soon after he added, '`It is all mercy I receive, through Jesus Christ our Lord.
I hope I may say I have endeavored to do nothing against the truth,
and what little I have been enabled to do for the truth,
I have done in a degree of sincerity and uprightness.`'

He was preserved perfectly sensible to the last, and quietly departed this life,
full of days and full of peace, on the 13th of the Second month, 1775,
at Alton aforesaid, aged nearly eighty-four, and a minister about fifty-nine years.
His corpse was interred in Friends`' burial-ground there, the 19th of the same.

[.asterism]
'''

RACHEL WILSON, late wife of Isaac Wilson, of Kendal, in Westmoreland,
was the daughter of John and Deborah Wilson of the same place,
who gave her a religious education.
Influenced by their example,
and being favored with the company and conduct of many valuable
friends traveling in the work of the ministry,
her mind was happily seasoned, and much profited;
and being also early favored with a visitation of divine love,
she was enamored therewith,
and weaned from the fallacious pleasures and amusements
which captivate too many of our youth.

Thus prizing the privileges she enjoyed, and the dawnings of divine wisdom in her soul,
she was much led into solitude and secret retirement before the Lord,
only choosing such company and conduct as might be profitable to her;
and carefully dwelling under the forming hand,
she witnessed a growth in virtue and piety,
and became fitted for the work of the ministry,
into which she was called about the eighteenth year of her age.

Being faithfully devoted to the service of her Lord and Master,
she experienced a growth and increase in heavenly wisdom; and,
by the constraining power of divine love, was drawn forth to visit the churches,
not only in many parts of this nation, but also in Ireland, Scotland, and America.

She also labored much among those not in profession with us,
who flocked to hear her testimony in the course of her travels;
and was eminently qualified for that service,
explaining the way of life and salvation in a manner
that reached the witness in the hearts of the hearers,
whereby many were brought to an acknowledgment of the truth.

She was remarkably diligent and exemplary in the attendance of our religious meetings,
both for worship and discipline; and, when called forth to service,
though she had many children and a large family under her care,
she did not allow these to prevent her from pursuing what appeared her manifest duty;
but what she found in her hand to do, that she did with her might.
She was a loving wife, an affectionate parent, a kind and helpful neighbor,
tenderly sympathizing with the afflicted, and frequent in visiting the sick,
in which visits she was very serviceable, often administering comfort to the drooping,
distressed mind.
In which service she found the reward of peace.

In the course of her religious duty she came to London, about the First month, 1775;
and on delivering her certificate to the morning meeting, she expressed,
in much tenderness, a desire,
that after her being engaged in the service of truth from her youth,
she might be preserved from those rocks and shoals which some had split upon,
and that her sun might go down in brightness.

She entered into her service with great humility,
visited most of the meetings in the city,
and finding her mind concerned for the inhabitants of Gravesend,
having had two meetings with them when she embarked for America,
she went again to visit them.
She was gladly received, and held two meetings in the town-hall, where,
through divine favor, she was helped through her service to her own peace,
and the comfort of many present.

After her return she attended several week-day meetings, in the last of which,
at Devonshire House, she was clothed with divine love,
in an encouraging testimony to the honest-hearted.

The next day, being the 4th of the Second month, she was taken ill,
and was confined wholly to her chamber, and mostly to her bed, for six weeks;
during which time she was favored with quietness of mind,
expressed her resignation either to live or die, and requested her husband,
who attended upon her a great part of the time, that he would tell their children,
it was her great desire they might, above every consideration,
mind the one thing needful, which having been her care,
was her unspeakable consolation in that time of close conflict.

She also in the course of her illness expressed to a friend that she was quite easy,
and to some others remarked the necessity of doing what appeared to be our duty,
while opportunity was afforded.
She said her Master was kind to her, and at times favored with his presence,
which bore up in days of trial, and nights that were wearisome.
She was often retired in mind, and remarked to some who attended her,
that though no one loved her friends`' company more than herself,
yet she had now no desire to see them, but was quite resigned,
though so far separated from her near connections.

She was a pattern of patience, and always appeared satisfied with those about her,
who rendered her any little services.
The last words she was heard to say were, '`Good tidings,`'
which no doubt the summons of death proved to her, as it appeared to have no sting,
nor the grave any victory.

She quietly departed this life on the 18th of the Third month, 1775,
at the house of Richard Chester, at London;
and her remains were interred on the 23rd of the same, in Bunhill Fields,
after a meeting held at Devonshire House.
She was about fifty-four years of age, and thirty-six years a minister.

[.asterism]
'''

MARY PRIDEAUX, wife of William Prideaux, of the county of Cornwall,
was a pattern of meekness and piety;
and as she grew in years she grew in grace and in the knowledge of our Lord Jesus Christ.
She had a part of the ministry committed to her,
in which she was a faithful steward and a bright example to others,
not being forward to appear in ministry,
as well knowing that true silence never shames the gospel.
But when under the constraining power of truth,
her ministry was with the demonstration of the spirit, and with power,
greatly to the refreshment and strength of the honest-hearted;
and when she felt the drawings of truth,
she was ready to leave her near connections in life.
She visited some parts of the west when her name was Mary Davies, and after her marriage,
several times.
Not long before the close of her life,
she found a concern to visit some of the midland counties,
which service seemed near to accomplish her day`'s work,
having soon after her return publicly to declare, happy would it be for all,
in the conclusion of their time, to have to say with the apostle,
"`I have fought the good fight, I have finished my course, I have kept the faith;
henceforth is laid up for me the crown of righteousness,
which the Lord the righteous judge shall give me at that day; and not to me only,
but to all those that love his appearing.`"

A short time after she was taken ill with a fever, which continued about four weeks;
during which she behaved with patience, meekness, and yet with Christian fortitude;
and many heavenly expressions dropped from her, at a meeting in her own house.
She had to commemorate the goodness of the Lord to all those who put their trust in him,
and humbly petitioned that he would be with them to the end;
that they who lived in his fear, might die in his favor;
requesting his protection in every trying season,
with fervent desire that all who were present might know a thorough resignation of will;
for the Lord our God requires obedience from all his servants.
The same evening she signified that she thought her time was near a conclusion.
Some days after she said,
'`Humility is a qualification I desire my children
may be endued with;`' and signified to them her hope,
that her advice in times past might be remembered, saying,
'`I hope it may be as bread cast on the waters, that may return after many days.
I have endeavored to do my duty by you.`'

Her disorder increasing, she desired she might endeavor to bear it;
and that those in health would improve their time while health and strength were afforded,
saying, '`I can do but little now;
it would indeed be bad if I had my peace to make with the Lord.
I have dedicated my health and strength to his service, according to my ability.`'
Finding herself growing weaker,
she desired that her family might be resigned to the will of Providence,
adding that she enjoyed great peace and tranquillity of mind, for which she was thankful;
and further added, Oh, this is a favor indeed, to enjoy such tranquillity!
All seems serene, and the streams of life flow freely; the river seems clear as crystal.
Oh, that none may put off repentance till confined to
a sick bed!`' On seeing one of her daughters,
she said, '`Oh! be good, be good, and fear the Lord, my dear child;`' and again said,
'`Then shall you know, if you follow on to know the Lord,
his going forth to be as the morning: he shall come unto us as the rain,
as the latter and former rains upon the earth.
Oh! the cunning foxes have holes and lodging places,
but the dear Son of God has not where to lay his head.
Lamentable, indeed, where this is the case!`'

The same evening, finding herself in much pain, she expressed,
that she felt the mercy of the Lord, who had forgiven all her offenses;
her omissions and commissions would be remembered no more;
and said she found a pardon for all.
Being in great agony, she desired that patience might have its perfect work,
and often prayed that the Lord would cut the work short in righteousness,
but desired that not her will, but His should be done.
At another time she expressed herself thus:
'`O that I were relieved from this world of peril and difficulty!
I have nothing to encounter with but death, and this is no terror to me.
O that I were safely arrived in the kingdom of heaven,
where I shall be comfortably spoken to by my God!`'
When the agonies of death were upon her,
she said, '`Is this the last fit?
O that it was!
Lord, dear Lord, come quickly.
O death, where is your sting?
O grave, where is your victory?`'
adding, '`What love I feel, what love I feel; my love is to all universally in the Lord.`'

She quietly departed this life the 16th of the Sixth month, 1775; aged about fifty-six,
and a minister thirty-four years.

[.asterism]
'''

JOSEPH OXLEY, of Norwich, was born at Brigg, in Lincolnshire;
and being left an orphan when about eight years of age,
he came under the guardianship of his uncle, Edmund Peckover,
who educated him in the principles of Friends.
But, according to an account left by himself in manuscript,
for the information and caution of his offspring,
he was led away by the influence of irreligious associates
into an indifference towards religion,
a neglect of the due attendance of meetings,
and several unprofitable and disorderly practices.`'
'`But,`' says he, '`at that time I was under such inward convictions,
that my heart was often filled with grief and horror;
however joyous I might appear outwardly, '`I was inwardly smitten and condemned.`'
Yet not sufficiently seeking to take up the cross,
but rather to gratify his youthful inclinations,
the power of evil so far prevailed over him,
that he became the means of trouble and sorrow to his relations and friends.
In process of time it pleased the Lord to meet with him as in a narrow place;
for in the year 1739,
he unexpectedly fell into a most distressing and alarming situation,
wherein his life appeared in immediate danger from
the surrounding pressure of a great crowd,
he being low of stature.
Confusion and terror instantly seized him, and made him cry aloud for help; upon which,
some near him afforded such speedy assistance as, through divine mercy,
extricated him from the great danger he was in.

After his deliverance,
he became deeply humbled in thankfulness that he
was not taken away in that unprepared hour;
and being also sensibly favored with a renewed visitation from on high,
his heart was made to rejoice in admiration of the gracious
abounding of divine love which he felt in his soul.

From this time he closely attended meetings, associated with experienced Friends,
and embraced their advice; humbly submitting to bear the cross,
and to follow the leadings of truth in its progressive manifestations.
Abiding under a daily concern that, as he had believed in the truth, he might walk in it,
he in time experienced a good degree of redemption, and resignation to the divine will.

About the year 1742 he found his mind baptized for the work of the ministry,
which weighty service, he, after some time of deep trial, in great fear and reverence,
gave up to, and appeared in public as a minister, to the satisfaction of Friends.

He travelled in the service of the gospel, at many times,
through many parts of this nation, Scotland, and Ireland;
and in 1770 he passed over the great deep,
and paid a religious visit to friends on the continent of America.
He returned from there in 1772, with the reward of peace in his own bosom,
and the approbation of friends,
as amply expressed in their certificates from various provinces.

He was a man exemplary in conduct, and agreeable in conversation, honest in advice,
charitable in sentiment, universal in benevolence, deservedly esteemed by his neighbors,
and beloved by his friends.

A few months before his decease,
he was impressed with a sense that his departure was at no great distance;
and sometimes hinted to some nearly connected with him that it would be suddenly; yet,
not as fearing it, but rather in a serious and pleasing acquiescence with the prospect.

Accordingly, after attending two meetings on First day, the 22nd of the Tenth month,
1775, which were held in silence; and spending the evening with his family,
in a disposition more than ordinarily pleasant; he went cheerfully up to bed:
where he laid but a few minutes,
before it pleased Almighty goodness to take him from
the vicissitudes of mutability without a struggle,
or passing through the tedious and afflicting pains commonly incident to nature:
no doubt to him an easy passage to a heavenly mansion.

His remains were interred in Friends`' burial-ground, at Norwich,
the 26th of the Tenth month, 1775, in the sixty-first year of his age,
and thirty-fourth of his ministry.

[.asterism]
'''

DEBORAH WARING, widow of Samuel Waring, before mentioned, was a native of Alton,
in Hampshire; and being religiously educated in the principles of truth,
and favored with an early visitation of its sanctifying influence, was,
by yielding obedience thereto, qualified for public service.
About the 18th year of her age,
it pleased the great Lord of the harvest to call her into the work of the ministry;
in which service she was an unwearied laborer; and under the renewing of heavenly virtue,
her doctrine frequently dropped like dew to the consolation of the right-minded,
and edification of the body in love.
She was often led, in an awful manner,
to press the necessity of a reverent waiting for
the fresh opening of the spring of all good;
that every individual might be brought from all exterior dependence,
to know the Lord for themselves; and witness the revelation of his dear son,
the minister of the sanctuary, in their own hearts:
and she recommended`' this doctrine to others by her own example.

She was a very diligent attender of meetings, both for worship and discipline;
and not only at home and in her own county,
but under the prevailing influence of divine love,
her mind was engaged at sundry times to visit friends in several other counties,
having the unity of her monthly meeting in that weighty service; and,
by some remarks of her own, it appears, that the Lord`'s blessed presence was with her,
and strengthened her from day to day.

She was of a tender, sympathizing disposition,
and was enabled to fill up the several relative duties in life with great propriety,
and to continue fresh and lively in old age.

It having pleased the Lord to remove her husband (with whom she had long
lived in much unity and affection) about a year before her,
she was divinely supported under that great trial, beyond her expectation,
as she expressed in sundry living testimonies,
which she delivered in the family at that solemn season.

But her health soon after began to decline,
and her faculties suffered an abatement of their usual strength; yet,
during six months`' gradual decay, she was preserved in much innocence; frequently,
aspiring after that which, from her youth up,
she had preferred to all created excellence, and desiring to be preserved to the end,
in a sense of that power which had been her morning light,
and her guide through the vicissitudes of life.

Being one day observed to be unusually anxious,
and one of her daughters asking her how she did, she replied, '`My poor mind is tossed,
and I long to be fixed, fixed, fixed.
There is one who can walk upon the sea, and command a calm.`'
She afterward wished to be lifted up, to be new-clothed, and go home; and prayed,
'`Gracious and merciful Father, look down upon me, if it is your blessed will.`'

She departed this life without sigh or groan, at Alton, the 3rd of the Second month,
1776, and was interred in Friends`' burial-ground there, the 11th of the same;
aged seventy-eight, and a minister about sixty years.

[.asterism]
'''

WILLIAM FRY, of the city of Bristol,
was favored with the visitation of divine love in early youth,
and was helped thereby to walk circumspectly.
At that time, he stood much alone among the youth; nevertheless, continuing faithful,
he became a good example of watchfulness and self-denial.
About the twenty-seventh year of his age, he first appeared in the ministry,
but for several years seldom; being not only then, but always,
as he expressed himself a little before his death, '`more desirous to feel than to speak.`'
As he was often led into a deep travail of spirit,
that the ministry might be kept living,
and that nothing might be offered in the will of the creature,
he was himself careful in this respect, and waited for the holy anointing,
the only true qualification, before he opened his mouth in testimony.

He travelled in the service of truth through Ireland, Wales,
and many parts of this nation; concerning which,
he spoke to a friend who came to visit him, to this effect;
that he had ever found great peace and satisfaction in giving up to those services,
the remembrance of which was very lively with him,
particularly during his last sickness.

During this illness, which was painful, and of several months`' continuance,
he uttered many weighty expressions.
Being asked by a friend one evening if his pain was then great, he replied,
'`I have been in great pain this day, but my mind is favored with a calm,
which I desire to be thankful for.`'
Observing he was dipped into very low seasons,
he remarked that it had been the case with many favored servants of the Lord,
some of whom he named, and added, it was not to be wondered at that it was so with him;
saying, '`Oh! how have I longed, and do long,
to feel the arisings of that life which is more desirable to a remnant in this day,
than the increase of corn, wine, or oil.`'
He mentioned also that he had a view of a gathering day in Bristol, and,
though he might not live to see it, he should die in the faith of it.

Some days afterwards he expressed himself in the following manner:
'`I think I have been favored, during my illness,
to experience what I have often had to declare;
that it is a good thing to dwell near the truth,
that inexhaustible fountain and ocean of divine love.
The sweet streams issuing therefrom sweeten the bitter cup.
This it is that has supported me under the present afflicting dispensations,
and the deep baptisms which it has been my lot to pass through,
wherein I may say I have been dipped as into the bottom of Jordan.`'
He afterwards added, '`I have been favored with a calmness; may I not say,
a holy calmness; what if I say,
a foretaste of that joy which shall be known when this mortal part puts on immortality;
and have been enabled to bear with patience and resignation,
the present trying afflictions, without murmuring or saying, Lord, what do you;
or why do you deal so with me?
It is comfortable to witness that which has been our morning light to be our evening song.
May those present,
who have been acquainted with the visitation of truth in the morning of their day,
continue to abide under it, and prize it above everything else.
It was excellent advice, to buy the truth, and sell it not:
it is these that will find support under every trial; and though we may have to say,
as our blessed Lord in his agony said, "`If it be possible, O Father,
let this cup pass from me,`" which was the effect of his humanity; but oh,
how soon did the divinity appear in him! "`Nevertheless, not my will, but yours,
be done.`"
You who have known the place where true prayer is wont to be made, remember me,
and desire for me, that I may be preserved, without murmuring or repining, to the end.
It is these, and these only, that dwell near the rock,
that are fitted for a habitation in that city, the walls whereof are salvation,
and the gates stand open all the day; and there is no night there.
It needs not the sun by day, nor the moon by night;
for the Lord God and the Lamb are the light thereof.`'

At another time he said, '`I remember when on board ship,
it was a comfortable sound in the night season, to hear the watchmen say,
"`All is well.`"
I have a hope I shall know the good Pilot, to steer me into that port,
where I may with patriarchs, prophets, and apostles,
and those already gathered like sheaves of corn fully ripe,
enter into the garner of rest and peace.`'

About a month before his death, he said, '`Though many and severe trials come upon us,
yet a little while and they will be over; a short period will put an end thereto.
I have many times thought, and at this time,
how comfortable a thing it is to be able to say with confidence, as one formerly,
'`You shall guide me with your counsel, and afterwards receive me into glory.
Whom have I in heaven beside you, and there is none upon earth that I desire but you.
My flesh and my heart fails, but God is my strength and my portion forever.`"`'

Many other lively expressions dropped at different periods from him,
but his voice becoming broken,
it was with difficulty he could speak so as to be understood for a whole sentence together.
He continued sensible, and in a quiet frame to the last;
and went off as one falling asleep, the 9th day of the Fifth month, 1776,
aged nearly fifty-three, and a minister about twenty-six years.
His remains were interred in Friends`' burial-ground,
near the meetinghouse at the Friars, Bristol, the 15th of the same month.

[.asterism]
'''

JOSEPH JACKSON, of the county of York, was born about the year 1697.
He was convinced of the principle of truth about the year 1740; and, under its influence,
was concerned to bear testimony thereto, about the year 1746.
He was zealous for its promotion, dedicating most of his time to the service thereof,
having left trade to be at liberty for it,
and was diligent in attending meetings for worship and discipline,
visiting most of the meetings in Great Britain.
This concern remained with him until the summer of 1775, when, returning home,
he was visited with sickness.
In the course of his illness, a Friend asking him how he did, he replied,
'`I am very weak in body, but the Lord is good to me, as I have but little pain.
Yet I could wish to be gone, that I might be at rest;
but am willing to wait all my appointed time, until my change come,
as I am favored with peace.`'
He added, '`My time of labor is now over.
I have completed my work within the day, and am now ready to return home to my rest.
O Lord, I long to be with you; yet not my will, but yours, be done.`'

A little after he said, '`Oh! how precious is the truth;
how little is it sought after by many, for lack of knowing its value!
I have often wished, and been moved to pray in secret,
that those who have once known and witnessed it, may never depart from it;
for if they do they will lose their birth-right, and the blessing attending it;
but that they may keep it to the end.
It is the pearl of great price, and worth more than all we are possessed of in this world.
It will purchase us an everlasting inheritance in the world to come;
and this is what I have been concerned to labor for, both for myself and others.`'
It being time for going to meeting, he bade the Friends farewell, saying,
'`My mind will accompany you.`'

Sundry other Friends visiting him at different times,
found him in the same lively disposition,
often expressing his desire that all who made profession
of the truth might live under its holy government.
Such love to his friends, and peaceful serenity of mind, attended him all along,
as contributed much to the satisfaction and refreshment of those who visited him.

He quietly departed this life the 16th, and was buried the 18th of the Twelfth month,
1776, at Gildersome, in Yorkshire, aged about seventy-nine years,
and a minister about thirty years.

[.asterism]
'''

ANN MERCY BELL, of York, was born in London.
She had her education in Friends`' school and workhouse,
being admitted soon after its establishment,
and afterwards continued there as a school-mistress for many years.
Being early favored with divine visitations,
she was not only preserved from the gross pollutions of the world, but was,
in a good degree, enabled to renounce vain and youthful pleasures and amusements,
which she frequently confessed with humble thankfulness and gratitude.

In the year 1731 she married Nathaniel Bell, of York, and became a member of that meeting.
While in a private capacity,
she was well esteemed as a Friend of circumspect life and conduct,
a pattern of plainness, and therein, as well as in other respects, a good example.
At length, steadily adhering to the divine teacher in her heart,
and under the influence of the spirit of truth, she had, from a well-grounded experience,
to declare to others the way of life and salvation.
In this service she faithfully labored, according to ability received,
at home and in adjacent parts; and, in the course thereof, found drawings,
in the love of the gospel, to visit various other parts of England: also,
when engaged in family visits, she found it her concern not to overlook those who,
by misconduct, had incurred the censure of Friends.

Her labors were not confined to those of the Society of Friends; but,
in the course of her travels,
she had compassionately to call and direct people of other
denominations to the unerring teacher in themselves,
and had meetings among them in several places where no friends were settled.

In the year 1753 she found a concern to visit friends in London;
and during her stay in that city, under the influence of love to mankind,
had to exhort the inhabitants thereof, in the streets, markets,
and many places in and about London, Westminster, and Southwark,
calling them to repentance and amendment of life.
In this service she was signally furnished with ability to labor,
to the tendering many of their minds, and acknowledgment of her goodwill to them;
and such was the ardor of her mind, and the flowing forth of love to them,
that she frequently preached three or four times a day, in different parts.
On her return home she had to acknowledge that she was favored with the return of peace;
which she esteemed a sufficient reward for the various exercises
which attended that laborious service.

Towards the conclusion of her time, she expressed her fervent desire,
that he who had been her morning light might be her evening song;
which there is no doubt she mercifully experienced.
Being suddenly seized with an apoplectic fit,
at the approach of the stroke she was heard to say, '`Sweet Jesus,
'`with some other expressions, which,
through the hurry and surprise those about her were in, are not now remembered.

In a few hours after, she departed, without sigh or groan, the 30th of the Twelfth month,
1775; and was interred in Friends`' burial-ground in York, the 4th of the First month,
1776; aged about sixty-nine, and a minister about thirty years.

[.asterism]
'''

REBECCA SHEWELL, daughter of Edward and Sarah Shewell, of Camberwell, in Surry,
was a child adorned with meekness, innocence, and humility; dutiful to her parents,
and affectionate to her brothers and sisters; a lover of the servants of Christ,
fond of reading the Holy Scriptures, and often so tendered in reading them,
that those who were present and heard her, were edified by it.

Being taken with an illness, which continued for twelve months,
she bore it with much patience and resignation of mind.
She was not confined to her chamber more than about three weeks;
in which season she told her mother, that she believed she should die,
and requested her to pray for her; which her mother being enabled to do,
it seemed much to ease her mind.
A few days after, she said, '`I have often been desirous of recovering;
but I find desires will not do,
I must have patience;`' and expressed her thankfulness
to her sisters for their tender care over her;
and said, '`O, that I could keep from groaning, that it might not make them uneasy.`'
She signified her apprehensions that her complaint increased;
not that she wished to live, but it was a fear she should not obtain future bliss.
One time some remarks being made to her on the pleasing things of this world,
and what she might enjoy, she answered, '`I have no desire for these things.
I had rather die and go to Christ.`'
She was frequent in prayer by herself, and often wished to be left alone,
and the curtains to be drawn about her.
Her sister observing her to be in much pain, asked her to take something; she answered,
that none of these things would do her good;
but it being observed the Lord could do her good, she answered, '`He can,
but none of these things can.`'

Her mother asked her, the day before she died, if she thought she should die; she said,
'`Yes;`' she had rather die than live, but was afraid she was not good enough.
Her mother encouraging her,
and intimating that she believed there was a mansion prepared for her;
the child expressed her willingness to go to it, desiring her mother to pray for her;
and the mother answering, '`I do; do you do it yourself?`'
the child said, '`I do, I do;`' and being asked if it was with outward words, she replied,
very fervently, '`No, no, in my heart.`'
She also intimated that she was quite easy; and frequently bade them farewell.
Soon after, her speech failed her; but she appeared to retain her senses to the last.

She departed, without sigh or groan, the 17th of the Second month, 1777,
aged only eight years and four months.

[.asterism]
'''

ANN LEAVER, daughter of John and Mary Leaver, of Nottingham, being taken ill,
signified her belief that her time would not be long, and said,
that the prospect of eternity was awful;
and that though she had not committed any bad thing, yet she had found it difficult,
when at meeting, to get to that steady watchfulness and settled composure she longed for.
She expressed thankfulness for the opportunities
she was sometimes favored with in the family,
in their sitting together at home; and added,
that she hoped the Almighty had blotted out her transgressions;
and prayed that she might be enabled to bear with patience
the trying dispensation she had to pass through,
which she believed was allotted for her further purification;
and begged for a certain evidence, that her conclusion might be happy,
and her passage easy; which was mercifully granted.

In the course of her illness she dropped many expressions,
which show that she looked forward to a glorious inheritance;
some of which are as follow.

After having given her sisters some tender advice, she said,
'`How awful to look at eternity,
and few young people in time of health think so much
of their latter end as they ought to do,
though they have as much cause as those more advanced, having no more certainty of life.`'
She plainly saw that those of a cheerful disposition
were in danger of going too far in company;
adding, '`Those who are taken away in youth escape many snares and temptations,
that such as live longer are in danger to be hurt by.`'
Several times she expressed her humble thankfulness for the last week`'s illness, saying,
that it had been a profitable, though painful, dispensation to her.
At another time, when in great pain, she spoke thus: '`O,
it is hard work! how needful when in health so to live as to be in readiness!
for it is enough to struggle with the pains of the body.`'
She also said,
that she plainly saw it was as necessary for us to watch over our thoughts,
as words or actions; desiring the prayers of those present,
that she might be supported under her affliction with patience.

After a painful day, being in the afternoon favored with stillness and composure of mind,
she thought herself going;
and took a solemn farewell of her near connections and friends;
desiring all present might make due preparation for that solemn and awful time,
when the soul must be separated from the body; saying,
that she did not expect to have had anything of that sort to deliver,
but as it came into her mind, she dropped it; and added, '`I want to be gone,
I seem to have no business here.`'
Her pain returning, she found she should not go so soon as she expected;
but begged for patience, saying, '`The Lord`'s time is the best time.`'

The day she died, the doctor proposing to lay on some blisters,
she said she was out of the reach of blisters; '`No mortal can help me;
there is but one who can help me;`' yet she was willing to submit,
if her father desired it.
But she added, '`O, that we might be a little still, and sit comfortably together!`' Being,
in some degree, free from her sharp agonies for nearly an hour, she said,
'`We are pure and comfortable now;`' and talked pleasantly, saying,
that the unwearied enemy had been endeavoring to trouble her, but she found him a liar.

The same evening she said, '`No one can think what I feel;
but if it is to purify me for an admittance into that holy place,
where no impure thing can enter, I am willing to bear ten times more; and, I hope,
with a tolerable degree of patience too.
I hope I am not impatient; but really the conflict is so sharp, at times,
that I cannot forbear crying out.
O Lord, keep me, keep me: my God help me, and please to release me this night.
I long to be gone.
Although I have had many pleasant prospects in view, I have resigned them all,
and would not return again to the world for any consideration.`'
Much more she said to the same effect.

She at times lamented that people, advanced in years,
should be so closely attached to the world, as too many appeared to be,
saying that they must soon leave it.

Her mother retiring to supper, she soon sent for her again, and told her,
with a sweet composure and calmness, '`My dear mother, I am now going,
and would have my father and sister to come and sit with me a while,
and take a final leave;`' adding, '`My prayer is granted;
for I have earnestly begged I might not see the light of another morning.`'
She took a solemn and affectionate leave,
saying that she wondered she could part with her near connections so easily; '`For,
'`said she, '`I have no tears to shed.
It is not hardness of heart, for I know I love you all as well as ever;
but it is to me an earnest that I am going to something greater.`'
She desired her affectionate love to many of her absent relations,
and particularly to some nearly her equals in years, saying,
'`Let them be admonished from me how they spend their time.`'

After some time, she said, '`It is all over, and I am perfectly happy.
I have no pain.
The conflict is at an end.
Farewell, farewell;`' and pausing a while, she said,
I am now going to join saints and angels,
and the spirits of just men made perfect;`' adding, '`I have no more to say.
I would have you to leave me, for I am going to sleep.`'
Then laying her head quietly on the pillow, she expired, without a sigh or groan,
the 22nd of the Third month, 1777, aged twenty years.

Her corpse was carried to Friends`' meetinghouse in Nottingham; and,
after a solemn meeting, was interred in their burial-ground there.
