== Chapter 5

[.chapter-synopsis]
* Mary Bundock
* Cuthbert Wigham
* Jonah Thompson
* Robert Hayward
* Elizabeth Holme
* Thomas Gawthorp
* Mabel Wigham
* Robert Pryor
* John Scott
* Isaac Sharples

MARY BUNDOCK, of Manningtree, in Essex, was religiously inclined from her childhood;
and as she grew up delighted in the company of solid friends; endeavoring,
amidst the various trials and exercises to which her situation exposed her,
to walk in simplicity and awful fear before the Lord,
who graciously preserved and prepared her for service.

About the thirtieth year of her age she appeared in public testimony;
in which she had the unity of Friends, and continued to labor therein,
both at home and abroad;
frequently traveling into different parts of this nation in the service of truth.

She was of a grave deportment, and of sound judgment,
earnestly concerned to discourage all undue liberties.
The benevolence of her mind appeared in many instances towards her neighbors,
by seasonable advice, and frequently administering to their necessities.
She was a diligent attender of the meeting she belonged to,
in which her travail in silence was helpful and comfortable,
till prevented by bodily infirmities.

In her last illness, which was at times very painful,
she uttered many comfortable expressions.
A friend who came to visit her, saying, '`She is sensible;`' she replied, '`Yes,
I am sensible who has been my preserver from the earliest time of my life,
and has helped me along, and supported me in weakness,
so that I have been revived through his goodness, from time to time.
There is but one power to help.
The last time I attended a public meeting,
it was the fervent desire of my mind for my friends, as well as for myself,
that we might seek to experience this only help near.`'
To another friend she said, '`Dear friend, trust in the Lord;
he never leaves his little ones; no, never, never.
Though outward afflictions happen to the righteous, as well as to the ungodly,
yet light is sown for the righteous, and gladness for the upright in heart.`'

It was no small cause of comfort to observe the lively frame of her spirit,
by which it appeared that, though her outward strength decayed,
her inward strength was renewed day by day.
She departed this life at Colchester, on the 8th of the Tenth month, 1778,
and was buried the 15th of the same, in Friends`' burial-ground there; aged eighty-three,
and a minister about fifty-three years.

[.asterism]
'''
CUTHBERT WIGHAM, of Cornwood, in Northumberland,
was educated in the way of the Church of England,
and was in his youth addicted to many youthful follies, and some gross evils.
But it pleased God, who is rich in mercy towards sinners, to call him by his grace,
and reveal his Son in him; whereby, about the year 1734,
he was convinced of the blessed truth, as it is in Jesus, and received it.

Being thus brought into deep judgment for his transgressions,
and sensibly feeling God`'s wrath poured forth,
he dared no longer follow his old courses and ways of living,
nor dared longer associate with his old companions,
but joined in society with the people called Quakers; and,
several of his neighbors being about the same time convinced of the truth,
he was made instrumental in settling a meeting in Cornwood, in the year 1735.

About a year after his convincement, a dispensation of the gospel was committed to him,
in which he labored faithfully according to the ability given.
His ministry was not with the enticing words of man`'s wisdom,
but in the power and demonstration of the spirit;
and he often had to magnify that power that had redeemed
his soul out of the horrible pit of everlasting darkness.
Having known, as he expressed, the terrors of the Lord for evil-doing,
he was earnestly engaged to warn others to take heed to their ways,
lest they should bring themselves under such terrors as he had felt, but now,
through infinite mercy, was released from,
and come to the enjoyment of that peace which the world cannot give or take away.

In the year 1753 he took a journey on foot, accompanied by a friend,
and had many meetings among a people who were strangers to Friends and their principles;
and also visited various other parts of the North, and some parts of Scotland;
having meetings in his way at several places where no Friends resided.
He was as a nursing father to the young convinced in that day;
and open in love to receive all in whom any tenderness appeared,
whether their station in the world was high or low.

He met with some exercises and cross occurrences in his own family,
which grieved him much, yet he was favored to outlive all his sorrows.
Though, through age and infirmity of body, his natural faculties were much impaired,
yet his mind appeared to be redeemed out of all evil;
and he was brought to the innocency of a little child.
Being perfectly sensible of his approaching dissolution,
he seemed to meet it with cheerfulness, saying,
'`I will wait in patience till my change comes.
Oh! it is a fine thing to be ready;`' and, indeed,
the patience and resignation which appeared in his countenance
evidently denoted the calmness and serenity of his mind.

Thus, in innocency, he finished his course the 9th of the Second month, 1780,
and was buried in a piece of ground given by himself for a burial-ground, in Cornwood;
aged about seventy-seven years, and a minister about forty-three years.

[.asterism]
'''
JONAH THOMPSON, of Compton, near Sherborne, in Dorsetshire, was born near Penrith,
in Cumberland, about the year 1702.
He was grandson of Thomas Lawson, who, in the early times of the Society of Friends,
was a zealous advocate for their principles, as his writings testify.
His parents dying while he was young,
he came under the care of a relation not in religious fellowship with Friends;
who left him entirely at his own liberty respecting his attendance at places of worship,
and the choice of his religious profession.
But being, at that early period, impressed with divine fear,
and a sense of the nature of true religion, he was mercifully preserved.
Though he had little or no expectations from his relations,
or view of subsistence but by his own industry, yet,
relying on the protecting care of Providence, he had the fortitude,
at about the age of fourteen,
to withstand offers which were repeatedly made him of an education at school,
and at the university,
with a view to qualify and provide for him as a minister of the established worship.
This is the more remarkable, as his mind was strongly attached to literary pursuits.
He has since frequently remarked,
that he was then fully convinced of the impropriety of such a mode of making ministers;
believing none could be truly so, but those who were of Christ`'s making,
by the call and qualifications of his holy Spirit.
He therefore put himself apprentice to a Friend, at Kendal, in Westmoreland,
to learn the trade of a weaver, with whom he faithfully served his time.
At leisure hours he prosecuted his studies,
and acquired such a share of learning as qualified him to
undertake the care of a school at Grayrigg in that county.
From there he removed to Yatton near Bristol; and on his marriage a few years after,
he settled in Dorsetshire, where he mostly resided the remainder of his time.

There is reason to believe that he was, while at Grayrigg,
made sensible of a call to the work of the ministry,
on that foundation which in early life had appeared to him so necessary;
and for which there is no doubt but he was in good measure duly prepared and qualified,
through the operation of grace upon his own heart;
and he soon became an able minister of the gospel of Christ.
In the year 1728, he paid a religious visit, in company with William Longmire,
to most of the counties in this nation,
to his own peace and the satisfaction of his friends.

In the year 1750 he visited the meetings of Friends in America,
where his labors of love were generally acceptable; and some years after his return,
he embarked again for the same continent, on which, for some time,
he took up his residence.

After his second return from America, he resumed the employment of a schoolmaster;
and travelled no long journeys from home,
but was a diligent attender of the meeting he belonged to,
and frequently attended the yearly meeting.

His ministry was acceptable to persons of various denominations,
being often led to declare the truths of the gospel with great calmness and deliberation,
and with such convincing clearness as frequently to occasion
many to acknowledge the truth of his doctrine.

For some time before his decease he frequently expressed
his apprehensions of his approaching end,
and particularly on a public solemn occasion, when,
after a clear intimation that the time of his departure was at hand, he added,
in nearly the following words: '`I may say with humility,
and a degree of Christian boldness, I have fought a good fight,
I have finished my course, I have kept the faith;
henceforth there is laid up for me a crown of righteousness incorruptible in heaven.`'

In his last illness he remarked to some friends who visited him,
that he had lived long enough, his services being over, and had nothing to do but to die,
having a well-grounded hope that the change would be to his advantage.
That on reviewing his past life,
he could find but few instances in which he could have acted better,
was he to live his time over again; and that he had a great advantage during his illness,
in having a quiet, easy mind, and no accuser there.
For a near friend and fellow-laborer in the gospel,
who took leave of him a few days before his departure,
he wished a portion of the same peace in the decline of life which he then experienced.

He was preserved in great composure and resignation, and, for the most part,
retained his faculties to the last; and on the 21st of the Fifth month, 1780,
quietly departed this life.
His body was interred in Friends`' burial-ground at Yeovil,
on the 27th. Aged nearly seventy-eight, and a minister about fifty-five years.

[.asterism]
'''
ROBERT HAYWARD, of Suffolk, in the early part of his life,
embraced the tendering visitation of the day-spring from on high, and,
according to the discoveries thereof to his understanding, gave up in obedience;
and being prepared to declare what God had done for his soul,
he invited others to taste and see how good the Lord
is to all those that put their trust in him.

His labors were often favored with general acceptance where his lot was cast,
which was for the most part confined to the county where he dwelt, and places adjacent.
He was industrious in his business, a plain and inoffensive man in life and conduct,
endeavoring by precept and example to be instrumental in promoting the welfare of all.

This continued to be the humble engagement of his mind to his conclusion,
in which the same godly simplicity seemed to attend him.

During the time of his illness he was favored with exemplary patience and resignation,
which were the means of his support under the excruciating pain which at times he felt;
and he would frequently say, '`The Lord is my shepherd, I shall not want.
Grace, nor truth, nor any good thing,
will he withhold from them that put their trust in him.
I find him near to help me in this the time of my affliction,
and nothing to stand in my way.
Oh, what a comfort it is to those that have done their day`'s work in the daytime.
I have endeavored to discharge my duty to the best of my knowledge.
I feel peace, sweet peace, such as the world cannot give, nor take away.`'

At times, many Friends coming to see him,
he frequently had a word of encouragement to drop among them and those about him,
and to tell what God had done for his soul.
He likewise had several comfortable opportunities with his children and grandchildren.
His earnest desires and prayers were put up for the young and rising generation,
that they might be preserved in the fear of the Lord.

The nearer the time of his departure approached, the stronger his memory grew;
and he seemed to experience more of the incomes of divine favor; and,
like a well-watered garden, he was fresh and green to the last.

A few hours before his close he had a fainting fit, and those about him thought him gone;
but after a while he revived, and, like good old Jacob, gave his children his blessing,
and said that he should sleep that night in the arms of his heavenly Father.

He was sensible to the last, and departed this life with great composure,
and full assurance of happiness, being full of days and full of peace,
the 24th of the Tenth month, 1780, and was buried in Friends`' burial-ground at Lynn,
in Norfolk; aged eighty-five years, and a minister nearly fifty years.

[.asterism]
'''
ELIZABETH HOLME, of Newcastle-upon-Tyne, was the daughter of Anthony and Dorothy Wilson,
and born at Highwray, near Hawkshead, in Lancashire.
She was favored with a religious education,
and in her youth her mind was impressed with the fear of God.
She was often drawn into retirement and a watchful state of mind.
Thus she attained a growth in religious experience,
and about the thirty-fourth year of her age,
was concerned to bear testimony to the efficacy of
that divine principle +++[+++the Spirit of Christ]
which she herself had felt: in which service she grew, and,
in company with Lydia Lancaster,
visited the meetings of Friends in Ireland and Scotland.

After her marriage with Reginald Holme, she visited various parts of England;
and in her station of a wife, she conducted herself with prudence and propriety; and,
being preserved in watchfulness,
allowed not her temporal concerns to hinder her services in the church.

Her last illness was short, scarcely ten days, most of which time she kept her bed,
appearing to be under great bodily weakness, but not much pain,
and bright in her understanding to the last.

To a friend who came to see her, at parting she said,
'`Remember me affectionately to your husband,
and let him remember me when he draws near +++[+++the throne of grace],
that I may pass through the valley of the shadow of death,
and be enabled to put off the robe of mortality and put on immortality, full of glory.
I trust to enjoy a part of that portion that is laid up for the faithful;
for such I have endeavored to be, according to the ability given.
I have nothing stands before me.
I do not clearly see that this is the finishing stroke,
but every stroke draws nearer and nearer.
In this I have no will, but stand ready, and in patience wait till his own time.`'

Her daughter sitting by her, she said, '`Oh, sweet peace,
what an enjoyment it is in this weakness.
I have discharged my duty to God and his people in this place.`'

A near friend calling to see her, he said, '`You have labored faithfully among us,
and we shall have a great lack of your company.`'
She said, '`I have so.
I hope it may be as bread cast on the waters, that may arise many days hence.`'
At another time she said, '`I thought I had been going,
but it seems as if the people held me, not so willing to let me go as I am myself.
Oh, that every link of this chain was broken,
that I might lie down in peace forevermore.`'

The morning before she died, being Fifth-day, her daughter sitting by her, she said,
'`I may say with king Hezekiah, the hand of the Lord is upon me,
I am waiting for my change.`'
After asking, '`Is your husband gone to meeting?`'
she added, '`I wish it may be a refreshing season to him,
and all the living members assembled this day, with whom my spirit unites,
and craves the canopy of divine love may overshadow their minds,
and strengthen for the work`'s sake.`'
After a pause, she said to her daughter, '`My dear,
your company is precious to me in this affliction, and your husband`'s,
which I dearly love.
O Lord, let us taste of your goodness, that we may be refreshed.`'

She quietly departed this life the 9th of the Second month, 1781,
and was interred on the 12th, in Friends`' burial-ground in Newcastle:
aged nearly seventy-eight, and a minister forty-four years.

[.asterism]
'''
THOMAS GAWTHORP, of Preston Patrick, in Westmoreland, was born of honest parents,
of our religious profession, at Skipton, in Yorkshire, in the year 1709.
His father dying when he was young, he was put apprentice to a man near Leeds,
not of our profession; and, meeting with severe treatment during his service,
to free himself therefrom, he was induced, towards the conclusion of the term,
to enlist in the army, in which he continued about five years.

While in that service, being, by permission, on a visit to his relations at Skipton,
he attended a meeting there, at which he was effectually reached,
by the powerful testimony of Mary Slater; and from that time attended Friends`' meetings,
when opportunities offered.
Though he labored under great exercise of mind on account of his situation,
yet he was not free to have his discharge purchased,
fearing how he might stand his ground.
One of his officers, observing his dissatisfaction with the way of life he was in,
made him an offer of his discharge,
on his returning the money he had received when he enlisted, which,
after solid consideration, he accepted;
and paying the money so soon as he had earned by his industry sufficient for that purpose,
he obtained his discharge, and returned to Skipton, the place of his birth.

During his residence there, which was not long, he came forth in public testimony.
From there he removed to Kendal,
and soon after accompanied a friend on a religious visit into Scotland.

After his return, he married a young woman of a respectable family,
belonging to Preston Patrick monthly meeting, and settled within the said meeting,
a few miles from Kendal, where he continued to reside when at home,
to the time of his decease.

His mind being devoted to the service of his great Master,
and obedient to the manifestations of +++[+++the spirit of]
truth, he grew in the gift received, and became a deep and able minister of the gospel;
diligently laboring in the openings of life,
for the exaltation of truth in the hearts of the people; unto whom,
from an inward sense of their states, he had often close, pertinent doctrine to deliver;
not in the wisdom of man, nor the eloquence of words,
but in the simplicity of the gospel, and with the demonstration of divine authority,
reaching the witness in the hearts of many.
He, nevertheless, often found it his place not to feed, but to famish,
the eager desire in the minds of the people after words;
by setting them an example of humble and awful worship in solemn silence.

He was exemplary in his diligent attendance of our religious meetings,
and in a circumspect conduct among men in the necessary
management of his outward concerns.

He was frequently engaged to leave his family and worldly affairs,
to pay religious visits to Friends in different parts,
having several times visited several parts of England, Scotland, and Ireland.
He also visited Friends in America four different times.
In all these labors of love we have reason to believe he discharged his duty honestly,
and was made instrumental in the great Master`'s hand
to the stirring up the pure mind in many.

He was also frequently engaged in visiting Friends`' families,
and enabled to speak pertinently to the states of individuals.
In his third visit to America,
he was particularly concerned on account of the hard
and suffering state of the poor negroes,
and we believe his labors on behalf of that oppressed people were of service.

Upon his return from his last visit to America,
he was much reduced in his bodily strength; but his mind seemed centered in peace,
being covered with innocency and sweetness, and patiently waiting for his change;
having an evidence that his day`'s work was nearly accomplished.

He attended the meeting to which he belonged, under great bodily infirmity,
though at a considerable distance, until he was wholly confined.
He departed this life the 29th of the Ninth month, 1781,
and was interred the 4th of the Tenth month following,
in Friends`' burial-ground at Preston Patrick; aged about seventy-one,
and a minister forty-seven years.

His friends of Westmoreland, in their testimony concerning him, say,
'`We doubt not but his conclusion was a happy release from the conflicts
and deep exercises attending his pilgrimage here;
and that he is gathered to the just of all generations,
to reap the reward of his labors.`'

[.asterism]
'''
MABEL WIGHAM, a member of Newcastle meeting, was the daughter of Cuthbert Wigham,
of whom an account has been given,
and was about six years of age when her parents were convinced,
and a meeting settled at Cornwood, the place of her father`'s abode.

In her youth she discovered a warm affection for Friends, and,
as she expressed to some of her near friends, tender desires were raised in her mind,
after an inward acquaintance with that life and virtue which
she was favored to hear livingly testified of,
by her worthy father and many other Friends,
who at that time were concerned to visit that meeting.
Being in a good degree preserved in an innocent frame of mind,
and attending to the reproofs of instruction,
that she might be favored to find the way of life,
she was often drawn into solitary places to pour forth her supplications before the Lord,
that he would in mercy, make himself known to her as the good Shepherd of Israel;
whose voice she might hear and distinguish from the voice of the stranger.

The fruit of her humble,
seeking state of mind soon discovered itself in her
growth in ardent love to truth and Friends,
and in her great desires to attend our religious
meetings and opportunities of worship at home,
as also monthly and quarterly meetings.
In all these she was a good example, by her silent, humble waiting upon the Lord;
where often, in much brokenness of spirit, she dropped her silent tears,
and the good effects thereof were manifested in the reach it had on others present.

A few years after her marriage to Thomas Wigham, of Limestone, in Cornwood,
she appeared in testimony in a few words, which were sweet and savory.
By humbly depending on the Lord for renewed strength,
she came to experience a growth in her gift; and was drawn forth to visit the churches,
for which service she was qualified in a particular manner,
being truly a daughter of consolation.
For notwithstanding her temporal concerns, having a large family,
and being only in low circumstances, she firmly trusted in the Lord who called her,
and freely left all and followed him; often saying, '`The Lord is my Shepherd,
I shall not want.`'

After her return from visiting the meetings in London, about the Sixth month, 1779,
her health became impaired, and a gradual decay took place,
so that she was confined for many weeks.
Her strength reviving, she got out to meetings again for some time,
where she had close and deep service; and, for change of air,
she went into her native county,
which gave her an opportunity of visiting her near relations,
much to their satisfaction and her own peace and comfort,
and of taking a last farewell of her friends and neighbors in that county.
After her return from Cornwood, her disorder made great progress, and wasted her fast,
and she was not able to get to meetings.

During her confinement, several of her friends went to visit her,
in which many precious opportunities were witnessed,
to the melting and humbling their spirits before the Lord,
so that they could truly say the Prince of Peace was there.

She bore her illness with exemplary fortitude and resignation;
and with a cheerful composure she mentioned her dissolution, and often said,
'`The way seems clear, and I have no doubt, if the last conflict was over,
but I shall be admitted to my Master`'s rest, and the joy of the Lord.`'

Much seasonable and tender advice she gave to her children,
encouraging them to seek and serve the Lord in their youth; and that,
if they were chiefly concerned to attain heavenly treasure,
the Lord would provide for their bodies; adding, '`Oh what satisfaction and peace I feel,
in having dedicated my youthful days in seeking the Lord,
and freely spending myself in his service.`'

As she lived, so she died; in love, peace, and unity with her brethren.
She departed this life, without a sigh, the 9th of the Eleventh month, 1781;
and her remains were interred at Newcastle-on-Tyne, the 13th of the same; aged fifty-two,
and a minister twenty-five years.

[.asterism]
'''
ROBERT PRYOR.
Expressions of the late Robert Pryor, of London, committed to writing by his brother,
John Pryor, who attended him in his last illness.

For some months before his death, his usual state of health was altered,
and signs of infirmity appeared, which continued to increase upon him,
and at length terminated in a settled decline.

One day, speaking to me about his will,
he said that some might think he had given a great deal away from his children;
but he was more afraid of their having too much than too little,
as he had seen great riches do much hurt, especially in our Society.
He wished his children to be brought up plainly,
and the boys to be put apprentices to sober, honest Friends.

One time, on taking leave of his son Robert, who had been up to see him,
he desired him to be a good boy, and to speak the truth,
and to keep to the plain language, and not to associate with bad boys,
but choose the best for his companions.
At another time he said, '`Brother, I hope I do not repine,
though I am afraid lest I should.
I have my low times, lest it should not be well with me.
Sometimes I think it may be the enemy that strives to disturb me.`'
Speaking of his being resigned to the will of Providence, he said, '`What signifies it,
whether I die now, or twenty years hence?
though if I look back, my time appears to have been very short.`'

One day he said, '`Dear brother, do not be too anxious after the things of this world,
for my inordinate desire to accumulate wealth, has been a heavy burden to me:
no one knows what I have suffered on that account.`'
He further said, that his having been so solicitous after the world,
had made him but a dwarf in religion;
and that if it had pleased the Lord to spare his life,
he thought he should have found it his place to endeavor
to be a more useful member in the Society;
and to expend more of his income in charitable uses: that the love of money,
and an inordinate desire after wealth, had pierced him through with many sorrows.

One afternoon his nephew came to ask him how he did: upon his taking leave,
after sitting some time in silence, he desired him to keep constantly to meetings,
to love friends`' company, and not to launch out into the vanities of this world,
or associate with those that were likely to draw him aside;
reminding him that there would be an end, which would overtake us all;
and that we ought always to be prepared.

One time, going to bed, he desired me to shut the door,
saying that it was his desire to supplicate, which he did on his knees,
begging the Lord not to leave him, but be with him in the trying moment,
and grant him a safe and easy passage into his glorious kingdom;
hoping he would accept his late repentance, which he trusted was sincere,
though upon a dying bed.
The next morning, as I stood by his bedside, he spoke to me as follows: '`Brother,
I have been in a quiet sleep, and had a comfortable vision.
I thought I had a foresight of that glorious kingdom, where all is peace, serene,
and quiet!
Such a prospect as I had never before seen, and such as no tongue can express,
the glory of that kingdom!`'

At another time, expressing the satisfaction he had in my being with him,
he desired that I would not leave him when the event happened;
and requested to be buried in a plain way, and to be carried into the meeting-house;
as he had seen the use of those meetings.

One morning asking him if he was free from pain, he answered,
'`that he felt only violent oppression; that when the Lord pleased to release him,
he believed he was ready; but hoped to wait the appointed time with patience: adding,
he was as clear in his intellect as ever.
What a favor! and that he was permitted to get home, and settle his affairs,
was a great favor; but above all, that which he saw in his vision!`'

He said that it appeared clear to him,
that the less Friends talked about news and interfered in politics, the better.
He thought they did not belong to them.
He used to read the newspapers when at Bristol, to divert himself; but left it off,
finding his time better employed in reading the Scriptures.

On taking a little refreshment, he said, '`What a favor it is thus to be waited upon,
and to have everything this world can afford,
to alleviate or still the pains of the body!
We have so much the more to be accountable for.`'
One evening, upon my asking him how he did, he said that he lay pretty easy,
and was quiet in his mind.
He thought he had a well-grounded hope, that all would be well with him;
and that if it should please the Lord to take him into his glorious kingdom,
what a happy change it would be!

One evening he said, that he did not know what to think of that night.
He had prayed so often to be released, he was ready to fear lest he had offended.
He should be very thankful to be released from his sufferings; yet hoped he could say,
as that good man Isaac Sharples had expressed in prayer, at his bedside,
"`Your will be done, O Lord, in earth, as it is done in heaven.`"
After this he continued remarkably still and calm, with much serenity in his countenance,
taking little notice, but appearing wholly fixed on the greatest of all objects.

On the seventh day before his decease,
he noticed those about him more than he had done some days before;
and his sister coming in the afternoon, whom he had often expressed a desire to see,
he mentioned it to me, as a great favor, to be permitted to see all his near friends;
which being done, it seemed as if every wish was gratified.

He continued in the same calm, composed state of mind, growing weaker and weaker,
yet sensible to the last; having his desire granted of an easy passage, I have no doubt,
into that glorious kingdom, of which he expressed he had a foretaste.

He departed this life at his house in Budge-row, the 16th of the Seventh month, 1782,
aged about thirty-seven years; and, after a solemn meeting at Gracechurch-street,
was interred in Friends`' burial ground, Bunhill-fields, the 21st of the same.

[.asterism]
'''
JOHN SCOTT, of Amwell, in Hertfordshire, was favored with strength of body,
and an active and vigorous mind.
He was esteemed regular and moral in his conduct, and extensive in his knowledge,
being remarkably diligent and attentive in promoting works of public utility;
in assisting individuals in cases of difficulty; and in the conciliation of differences.
Notwithstanding these qualifications, there is reason to believe,
he frequently experienced the convictions of the Spirit of Truth,
for not faithfully following the Lord, and adhering to the cross of Christ;
by which true believers are crucified to the world; and the world to them.

During the yearly meeting at London, in the year 1783,
he attended many of the meetings for worship,
and appeared to be more religiously concerned than for some years preceding.

On the 1st of the Twelfth month he was seized with a fever,
and expecting it would bring on his end, he was greatly humbled in spirit,
expressing a sense of the happiness of the righteous in futurity;
but being convinced of his own low and unprepared state,
he said he was unworthy of the lowest place in the heavenly mansions,
but hoped he should not be a companion of accursed and wrathful spirits.

In the early part of his illness,
he discoursed with his wife concerning some outward affairs:
particularly desiring that his only and beloved daughter
might be brought up among Friends.

Notwithstanding the severity of the distemper,
he was favored with a clear and unimpaired understanding;
and the exercise of his spirit seemed to be almost
continual for peace and reconciliation with his Maker;
having a hope, that if it should please the Lord to spare him,
he should become a new man; but in much diffidence he expressed a fear,
lest the old things should again prevail.
He also said to the person who attended him, that he had been too proud;
yet he had been remarkably easy of access to persons in low circumstances.

Speaking frequently of his brother Samuel Scott, and expressing a desire to see him,
on the 9th of the Twelfth month, a special messenger was sent to Hartford from Ratcliffe,
where he lay ill, requesting his attendance there.
His brother,
on being informed next morning by letter of his continued solicitude to see him,
reached his house at Ratcliffe about four that afternoon.
Being introduced to his bedside, on asking him how he did, he answered, '`Very bad.
I wanted to see you, I had a great deal to say to you, but I fear now I cannot.`'
What afterwards passed between them was as follows: After a short space of silence,
John Scott began to speak with a voice full of power.
'`I wanted to see you, to tell you, that I have nothing to trust to but the blessed Jesus;
and that if I die, I do not die an unbeliever.
If I die, I die a believer, and have nothing to trust to but mere unmerited mercy.`'

Finding him brought down as from the clefts of the rocks, and the heights of the hills,
into the valley of deep humiliation, his brother rejoiced in spirit,
and spoke comfortably to him;
expressing the deep humiliating views he frequently had of his own state.
John Scott replied, '`Oh! if it is so with you, how must it be with me,
who have been the chief of sinners!`' The insufficiency of self-righteousness being mentioned,
'`Oh!`' said he, with great earnestness, '`righteousness!
I have no righteousness, nor anything to trust to but the blessed Jesus and his merits.`'

Pausing awhile he proceeded, '`There is something within me which keeps me from despairing.
I dare not despair, although I have as much reason to despair as any one;
were it not for him who showed mercy to the thief upon the cross.
The thief upon the cross, and Peter who denied his master, are much before me.`'
Being advised to trust in the Lord, he replied, '`I have none else to trust in.`'
'`Oh!`' said he, '`the Savior, he is the way, and there is no other.
I now see there is no other.
Oh the Savior!
I have done too much against him;
and if I live I hope I shall be able to let the world know it,
and that in many respects my mind is altered.
But I dare not make resolutions.`'
His brother mentioning former times, and the days of his youth,
in which they frequently conversed about,
and were both clearly convinced of the necessity of inward and experimental piety,
he answered, '`I was then very deficient, but I have since been much more shaken.`'
Visiting the sick in a formal customary manner being represented as unprofitable,
he replied, '`Oh! it is not a time to be solicitous about forms!
Here is a scene indeed, enough to bring down the grandeur of many, if they could see it.
I buoyed myself up with the hope of many days.`'
Recommending him to the great object, Christ within, the hope of glory,
to which his mind was measureably turned, his brother seemed to withdraw,
on which he clasped his hand, and took a solemn farewell.

He continued in mutability about two days longer, altogether in a calm and rational state.
About twelve hours before his decease, his speech much faltered;
but by some broken expressions it appeared that the
religious concern of his mind was continued.

On the 12th day of the Twelfth month, 1783, he departed this life,
in remarkable quietness, without sigh or groan;
and was buried in Friends`' burying-ground at Ratcliffe, on the 18th,
being nearly fifty-four years of age.

[.asterism]
'''
ISAAC SHARPLES.

[.embedded-content-document.letter]
--

=== A short narrative of Isaac Sharples, late of Hitchin, written by himself some time before his decease: to which are added some of his expressions a little before his end.

Being now about the eightieth year of my age,
it is in my mind to leave some few hints of the Lord`'s
tender dealings with me from my youth to this time,
for the information and encouragement of those I may leave behind me.
I was born near Prescot, in Lancashire, about the year 1702; my parents,
William and Phoebe Sharples, being members of that meeting.
My mother died about three years after, leaving six children, who, by her removal,
were subjected to much hardship.
My father, for lack of keeping his place, forfeited his unity with Friends,
by which the family became dispersed, and none of us continued in the Society.

When I was about twelve years of age,
by the persuasion of some of my father`'s relations, I was sprinkled at Ormskirk;
from which time I continued to frequent the public worship, until I joined Friends.
At about fourteen I was placed out apprentice to a tailor, where I suffered much;
but my master, to whom I was bound, not having sufficient employment for me,
after I had served about half my time,
turned me over to a Friend for the remainder of the term, whereby I got some relief.
In this family they would often be speaking of my mother,
who was esteemed a valuable Friend.

Having now frequent opportunity of being in Friends`' company,
and observing their regular lives and conduct, it gave me a secret liking towards them;
but looking upon myself to be a settled member of the established church, so called,
and there being most liberty +++[+++in it]
for worldly indulgence, I endeavored to satisfy myself in that way as long as I could,
being often strongly tempted by youthful lusts after
the common evils that are in the world;
yet I was mercifully preserved from the grosser part thereof.
At length it pleased the Lord, who had long followed me by his secret rebukes,
to break in upon my soul by his powerful love and awakening visitations,
to show me that was not my rest, because it was polluted.
My present state and condition being now clearly laid open to my view,
by the light that shined into my dark heart, I saw sin to be exceedingly sinful,
and that it was this which separated me from my God,
and caused him to withhold good things from me.
I was also favored to see my great loss of time and neglect of duty,
and how far I was behind in my day`'s work.
Although the Lord was pleased to wink at the time of ignorance,
yet now I found his call and command was to repentance and amendment of life.
When I set my heart to seek him, I met with great inward opposition from the world,
the flesh, and the devil, who assaulted me with manifold temptations.
But forever magnified be my gracious God, he made good the saying of our blessed Savior,
"`My Father is greater than all,
and none shall be able to pluck you out of my Father`'s hands.`"
Thus, although I was like one cast out and forsaken,
and in great measure destitute of those natural advantages many are favored with,
my education being low, yet, in this state of weakness and ignorance,
the Lord took me under his care and protection.

When out of my apprenticeship,
having but few friends or relations that took much notice of me,
I concluded to travel in the way of my trade, and went to London,
where I worked some time.
Afterwards I proceeded westward, by way of Oxford, Cirencester, and Bristol,
intending to travel through the western counties, and return again to London.
But I had not gone far from Bristol, before kind Providence,
watching over me for my good, mercifully interposed, directing my way in his wisdom.
He was pleased to put a stop to my roving mind,
and to convince me of the truth of that saying, "`It is not in man that walks,
to direct his own steps.

Meeting with employment in my trade in the county of Somerset,
and being convinced of the blessed truth, I settled among Friends,
and continued in that part of the country some years.
About the year 1724,
my mouth was first opened in the work of the ministry at a meeting at Claverham,
in the said county, which I attended for some years, before I went much abroad.
After my stay here about twelve years,
I entered into a married state with Esther Thurston, of Thornbury, in Gloucestershire,
widow, where I then settled.
We lived together in true unity about five years, when she was removed from me by death.
During my residence here,
the Lord laid a concern upon me to pay a religious visit to several northern counties,
and Scotland, also South and North Wales; with which I acquainted my friends,
and had their concurrence and certificate.
I set forward, endeavoring to look with a single eye to my good guide,
who was pleased to enable me to perform this service to my own comfort,
and the satisfaction of my friends.
For this, and for his preservation and care over me every way unto this time,
I bow my soul to my gracious and merciful God.
Although I sometimes set out in great inward poverty,
yet I was secretly supported by an invisible hand, that I could truly say,
the Lord was my shepherd, and bountifully supplied all my needs,
so as many times to make my cup run over, filling my heart with his love;
that I can now say, What shall I render to the Lord for all his benefits,
who has been my morning light, and I humbly hope will be my evening song?

After this journey, I continued at Thornbury about five years longer,
visiting the meetings of my friends in most of the western and northwest counties,
as the Lord was pleased to open my way.
About the year 1743,
a concern was laid upon me to visit the principal towns in the county of Devon,
where there were no Friends;
and notwithstanding the undertaking looked difficult and arduous,
yet as I was preserved in a faithful obedience to the Lord`'s requirings,
He who put me forth was pleased to go before me in such a manner,
that notwithstanding it was sometimes attended with very close exercise,
yet through his divine assistance-I was enabled to
perform this service to a good degree of satisfaction,
and to meet with no opposition; except in one place from an angry priest.
At several towns I had meetings in the streets and market-houses.
I afterwards went into Dorsetshire and Hampshire, and passed over the Isle of Jersey,
in company with my friend Jeremiah Waring.

1744+++.+++ This year I visited Ireland.
1745+++.+++ Visited several western counties as far as Cornwall,
and the circular yearly meeting there.
1746+++.+++ This year I entered a second time into a married state, with Mary,
daughter of Joseph and Mary Ransom, of Hitchin in Hertfordshire, where I then settled.
She has been a true help-meet to me,
we having now lived together in great unity about thirty-six years.

After my marriage, I visited most of the counties of England and Wales,
at different times, as the Lord was pleased to open my way, and enable me for it;
through all which I have to acknowledge with thankfulness to my God,
in whose service I went forth, that I lacked nothing,
but was wonderfully preserved and supported;
yet have nothing to glory in but that arm which was made bare for my help,
and have done no more than was my duty to do.
I have had many public services in barns and other places,
where there were no Friends settled,
and have attended many marriages and burials not herein particularly noticed.
Under a humbling sense of the Lord`'s goodness,
I can now look back with satisfaction and thankfulness to him who
has enabled me so far to do my day`'s work in the daytime;
and am now favored in my old age to drink of that rock,
out of which flow the issues of life; so that now, through his merciful aid,
I can set up my Ebenezer, and say, Hitherto the Lord has helped me.

I was called into the vineyard when young, and have ever since found work enough to do,
either in digging, watering, or pruning: it not being a time for slothful servants,
nor will it do to put that candle, which has been lighted in us, under a bed or a bushel.
The Lord did not find me out among the wise and prudent
of this world but he took me from the stones of the street,
from which, in his wisdom and goodness, he has often raised up children to Abraham.
I have now to rejoice that my day`'s work is so near a happy close,
having only patiently to wait my appointed time, until my change come.

--

Here ends the account our dear friend gives of himself:
what follows is extracted from the testimony of Baldock monthly meeting concerning him.

[.embedded-content-document.testimony]
--

When, through the infirmities attending old age,
he was rendered incapable of going far from home,
he diligently attended his own and neighboring meetings,
frequently appearing therein in short but lively exhortations,
endeavoring to stir up the minds of friends to a faithful attention to their duty.
He had a spirit of discerning beyond many,
and an excellent gift in the discipline of the church,
having a clear sight of the insufficiency of the outward form,
without the influence of the divine power to support it to edification.
His ministry was plain and powerful,
often reaching the witness of truth in the hearts of his hearers.

In supplication he was inward and weighty, an awful solemnity covering his spirit,
whereby he was frequently favored with near access to the throne of divine grace.

An innocent cheerfulness, tempered with gravity, adorned his conversation,
and his conduct was a pattern of meekness, moderation, and love,
which gained him general esteem.
Thus persevering in true watchfulness, the language of the apostle,
which he was known frequently to repeat, may be truly adopted concerning him,
"`Our rejoicing is this, the testimony of our conscience,
that in simplicity and godly sincerity, not with fleshly wisdom, but by the grace of God,
we have conducted ourselves in the world.`"

In his last illness, being sensible his end was approaching,
he expressed himself after this manner: '`I feel my natural faculties fail much.
I desire to be content with the Lord`'s will,
and to wait all the days of my appointed time, until my change shall come.
It is pleasant to think I draw so near the end of my race,
and can now set up my Ebenezer, and say, "`Hitherto the Lord has been my shield,
and exceeding great reward.`"`'

At another time a few friends sitting by him, he said,
'`I find my body advancing quickly towards its dissolution;
but death is no king of terrors to me.
I hope I shall be ready for my final change.
Although our meeting in this place is but small,
it affords me a secret satisfaction to see the forming hand at work in some of our youth,
and that they are measurably called into service; to which I hope they will give up.
The world, and the things of it, have lain too near,
and hurt the growth of some who might have made further advances,
had they not been hindered thereby.`'
He was favored to feel very little pain, his complaint being a gradual decay of nature.
He kept his bed about two or three days, during which time he said but little,
although he seemed quite sensible to the last.
About an hour before his end he turned himself in his bed, and seemed to fall into sleep;
departing quietly without sigh or groan, the 18th day of the Fifth month, 1781,
about the eighty-second year of his age, and a minister about sixty years.

Thus, our dear and worthy friend, after a long and well-spent life, finished his course,
and we doubt not,
has entered that glorious immortality of rest and peace prepared for the righteous.
His remains were interred in Friends`' burial-ground at Hitchin the 23rd.

--
