== Chapter 6

[.chapter-synopsis]
* John Fisher
* Robert Walker
* Rebecca Summers
* Isaac Wilson
* Kezia Merryweather
* Judith Hill
* Thomas Ross

JOHN FISHER, of Youghall, being taken unwell, and his disorder increasing,
he had two friends called up early on Second-day morning, the 14th of Second month, 1785,
to get his will made, and to give some directions about his affairs; which, when done,
he seemed to give himself up, and lament leaving his poor wife and children.
A friend asking him about the state of his mind, whether he had any uneasiness that way,
he answered, '`Indeed he had, and would not conceal it.`'
He bewailed his neglect while health was afforded, to make the necessary preparation,
for such a time as that; and an uneasiness on the latter account increasing,
he dropped many expressions, lamenting his backwardness in duty.
He also particularly regretted losing his father so young,
and the lack of the tender tuition of a religious mother;
which if he had been favored with, he thought he should have done better;
that he had not been undutiful to her; nor did she lack natural affection to him;
yet he plainly saw he had been left too much to himself when young,
and kept a stranger to his best friends, whom he said he did not know till lately.
He spoke several times of his children,
fearing they would suffer loss for lack of his care, if he should be removed from them;
recommended the care of them to some friends then present;
and repeatedly desired that they might be brought up in plainness,
as it was his choice to have them decent and plain.

On Fourth-day morning he was earnest to have a doctor sent for,
who had attended him and was gone to the country,
after which he appeared to be more alarmed and uneasy at his own state, and said,
'`It was sounded in my ears, "`Set your house in order for you shall die,
and not live;`"`' and continued in great distress for some time.
Being desirous to see as many of his relations as were in the house,
several were called to him.
When they came he said, '`My dear friends and relations,
I love you in the bowels of affection,
and have called you to tell you that I am summoned to appear before the great Judge.
I have been negligent in my duty,
and desire that you with me may beseech him to have mercy on me.
I have a ray of hope that he will admit me into some corner of his kingdom.`'
The doctors coming in, interrupted him, and he said,
'`I had rather they would let me die in peace,
I hoped to have a comfortable little meeting with you;
but perhaps we may have it when they are gone.`'

He still seemed in great distress, and on friends coming into his room,
he said to several of them, with a voice that denoted much uneasiness and fear,
that he was going before the great Judge; and uttered many things,
lamenting his backwardness in duty, and neglect in seeking an acquaintance with God.
He desired friends present to retire inward, and pray for him;
and after a short pause addressed himself to one, and asked what he thought of him,
desiring he would speak his mind.
He answering that he did not then find any thing particular to
express further than a desire to seek for mercy and peace for him,
which he had a good degree of hope he would attain; he answered, '`That is what I want,
and not life,`' and added, '`that gives me some ray of comfort.`'
He asked again, whether he did hope it for him;
going on in prayer and earnest entreaties to the Lord,
several times requesting his friends to pray for him.
He was recommended not to look too much for, or depend on, their prayers,
but to look to the Lord; he answered, that was quite his mind,
his dependence was on him alone, and on his dear Son.
On his uncle`'s coming into the room, he said, '`I am going before the great Judge,
which is a serious thing;`' and lamenting his state much as before,
said that if he had submitted to his dear uncle`'s advice,
it would have been better for him;
but yet he apprehended his uncle did not use as much
authority over him as he might have done.

Several friends coming into his room, he lamented his state much as before,
and seeming to be in a great strait, said that he was not yet without a ray of hope.
After many more expressions and fervent prayers,
he said he had a good degree of hope that he should be received in mercy.
After a while he came to say, he had a well-grounded hope,
and that death would be no king of terrors to him.
That this was a glorious day to him, the most glorious he had ever seen;
that he had a wonderfully kind, merciful master, beyond what he could expect,
and that he could sing for joy of what he then felt of God`'s mercy; '`but,`' said he,
'`warn all not to trust to that,
by neglecting and trifling away their time;`' with many more sweet and comfortable expressions.
He also begged his wife to resign him, adding, '`Charge the rich in this world,
that they be not high-minded, nor trust in uncertain riches.`'

His voice growing strong, it came to be raised almost to a melody,
with prayers and praises to the Lord for his merciful dealings to him,
in sparing him that day.
He said the Lord had lifted up the light of his countenance on him,
which was indeed beautiful, and that he had a hope, a well-grounded hope,
that he should find mercy; and at many times after, expressed a desire of being released,
and asked his friends present to pray that he might be taken away.

On seeing his nephew come in, he called him,
and gave him much suitable advice and caution,
desiring he would leave off some superfluities, and not be ashamed to do so,
and say his dying uncle bade him, who he knew loved him well,
and that he should never be sorry for it.
He recommended him to mind and submit to Friends`' advice,
and not do as himself often had done, when he got good advice,
let it in at one ear and out at the other; adding,
that the last friendly visit was very beneficial to him,
that he had treasured up some hints he got,
which seemed to be in particular a solemn warning to prepare for the time then approaching,
and said these were the right sort of visits, and not those of the world.

He had his sister called, saying, his love to her was strengthened.
When she came, he said, '`My dear sister,
I believe I was sent back with a message to you in particular,
to shake yourself from the filth of the earth.
Rise up early and work, lose no time.
Do not be deceived, as I was many times.`'
In particular, he advised her to the constant attendance of meetings,
and not to miss those on First-day afternoon, nor week-days.

On seeing his wife much afflicted, he said to her, '`My dear Mary,
did I not desire you to be strong?
Be strong in the Lord, for he is good and kind.`'

He showed much satisfaction at seeing so many of his friends and relations about him;
and recommended them not to neglect or despise the day of small things,
as he too much had done.
His mother having died the evening before, and lying dead in the house, he said,
'`My friends, you are come to the house of mourning, death below stairs, and death above;
but it is a joyful day to me.`'
At another time he said, '`Dear uncle, I have had a precious meeting here today.`'

He repeated advice several times to Friends to live in love and unity,
and to avoid all breaches, saying,
'`It is a beautiful thing for brethren to dwell together in unity;`' and that he
thought it made something towards the unity of the brethren hereafter,
and was a mark of the Master`'s. A physician coming in, and offering him his hand,
he answered that he had no occasion for him; that he was near going,
and was very easy and well; and that this was a glorious day to him,
far the most so of any he had seen in this life;
describing the Lord`'s goodness and merciful dealings with him.

His wife being present, he said,
'`I think it was divine wisdom that led me first to see her, in goodness to me,
as she proved a blessing to me; and I do not doubt but she will be blest.`'
He recommended her to the kind care and attention of his friends,
and said he had a hope that his children would be preserved,
and that the great Master would take them under his care;
desiring his wife again to be strong, and take what was to come with cheerfulness.

He advised Friends to give no sleep to their eyes
till they have found an acquaintance with God;
and said, '`This is a warning from a tongue you did not expect;
but a new song is put into my mouth, even a song of praise.
Oh that I had a tongue that could ring through the streets.
Beware that you do not attribute these sayings to me; they were never bred in me,
they are all from the great Master.
He can make the stones of the street speak, and I am one of them.`'
After some time he said, '`My outward man grows weaker,
but I perceive my inward man to grow stronger, and he rejoiced in the Lord`'s goodness.

To a young man, not of our Society, he said, '`I am glad to see you,
and am obliged for the trouble you have taken.
There is something good about you.
I believe you are well inclined, but, like many others,
willing to go on in the old beaten track;
but when you feel any of the inward breathings of truth, or its discoveries,
attend thereto, for I know you have a sufficiency of it to begin upon,
in order to make a good ending.`'

To his sister`'s husband he said, '`I have loved you as a brother,
and I know you are an honest man, and have something good in you;
but there is also something of shame.
Remember, if you do not acknowledge God before men, he will not acknowledge you.`'

After a while, his wife being so full that she gave a little vent to her grief, he said,
'`Keep silence;`' and repeated, '`Keep silence before me, O islands,
and let the people renew their strength.`'

On seeing a religious inoffensive man, one of his friends, come into the room,
he called out, '`O, John, I am glad to see you.
There is one, '`said he,
that has minded the day of small things;`' and he
spoke something of the Lord`'s goodness to himself,
and how well it was with him.

To one of his servants he said he hoped he would be faithful to his mistress;
and recommended him, and all of his profession, not to trust to the priest,
or the ringing of a bell, to do the work for them, but to seek for themselves.
That whatsoever was to be known of God was made manifest in man; and, blessing the Lord,
said he had not sent bishop or priest to him to touch him, or engage his attention;
but had come and touched him himself, and done the work for him.

On speaking to a Friend about the lack of regularity in some of his accounts,
by which he thought his family would sustain loss,
he said it was no wonder these accounts should be neglected,
when he had neglected his own great account.

He afterwards uttered many sweet expressions, a few of which, that could be remembered,
were as follow: '`It is better to be here, though in the house of mourning,
than in the house of rejoicing.
O Lord, as I have found you, I will not, I intend, let you go.
O beautiful is his countenance! he has lifted up the light of his countenance on me,
and it is beautiful indeed.`'

On hearing the clock strike six,
he said he had lived twenty-four hours longer than he expected,
and that it was the most glorious, happy day that ever he had.
Though he greatly regretted putting off the work so long;
yet he rejoiced in the Lord`'s goodness,
and hoped in that twenty-four hours he was enabled to find acceptance,
as well as if he had been in the front of the battle.
He also exhorted others not to trust to that, but to begin early,
saying it is a fine thing at such a time to have nothing to do but to die,
and that it was the Lord alone that did the work for him.

He signified his satisfaction in being, in a good degree,
preserved in resignation since the beginning of his sickness,
and that he had not used any angry expressions to those about him,
nor in word or thought murmured at the great Master.

He lamented the pride and vanity of foolish people,
in spending so much time and pains to deck their poor bodies,
an example of the vileness of which he thought was in himself, and said,
'`I believe I am thus strengthened for some good purpose for your sakes,
and wish you may attend to the advice of a dying friend, and think of me sometimes,
that there was such a one.
I am going but a little before you.`'

To a friend he said, '`I remember you gave me some advice several years ago,
which was good advice, though I did not then think it so,
nor did you speak it to me as you should have done; yet I have often thought of it since,
and believe it was of use to me.`'

To his wife he said, '`I do not belong to you nor you to me, now.
It is a great mercy that this was not the sickness or death of a day or two,
for I was not ready; but since this warning, I think I have not been idle one hour.`'
He also said, '`I have been enabled since my sickness, to give up wife, children, and all,
and set no value on them, in comparison of what is before me.`'

The doctor who was sent for, having returned from the country,
when he was informed of it,
his dependence and expectation being taken off from such helps,
and even from the desire of life, he said, '`Give my love to him;
I have no occasion for him now.`'
On a relation expressing a desire that the doctor should see him, as he was sent for,
he consented, and was likewise prevailed on to consent to putting blisters on his legs,
which were exceedingly troublesome to him for two days, and caused a severe conflict,
which himself, and those about him, much lamented,
after the fine easy state of mind he had before attained.
He said he thought they delayed his passage, and that, but for them,
he would have been in his Master`'s house before;
and often prayed to be enabled to hold out to the end,
and that his faith might not fail.

When he observed the light appear on Fifth-day morning,
he desired to be kept quiet that day, as he must mind his own business;
and not to let many come to see him, lest he should be disturbed,
or in anything miss the mark.

Sixth-day evening, by his own desire, there was some blood taken from him,
after which he lay more composed, and turning himself, said, '`Come,
who knows but I may get a little of the great Master`'s company now before I go.`'
After a while, he said, '`Never fear, never fear; I hope all will be well.`'

He said the Lord had greatly favored him many times, when none knew it but himself,
though he had too much neglected it;
that he had an evidence the kingdom was open to receive him.

That night, being very uneasy, he many times prayed to the following purpose:
'`O you most gracious and merciful God, help me O! leave me not in the hour of trial.
O, my God! help me, and be with me, and grant me patience.`'

To a friend, a little before his departure, he said, '`The sting of death is sin,
and that is, through the Lord`'s goodness, taken away from me.`'
Third-day afternoon, the 22nd of Second month, 1785,
he quietly departed with a composed countenance, aged thirty-three years.
His remains were interred in Friends`' graveyard the 25th of the same.

[.asterism]
'''
ROBERT WALKER, of Gildersome, in Yorkshire, was educated in the profession of truth;
and being favored with the visitations of divine love in his youth, was,
by yielding obedience to its heavenly teachings,
redeemed from the follies and vanities incident to youth,
and gradually fitted for being a useful instrument in the church.
About the year 1751 he first appeared as a minister, in much brokenness of spirit.
He kept mostly to meetings about home, till the year 1756,
when his heart being enlarged in gospel love, with the concurrence of Friends,
he visited, at different times, most parts of this nation and Ireland;
and in the year 1773 was engaged in a general visit to the meetings in North America,
and labored among them in much fervency of spirit.
Being favored with a sense of the approaching troubles in that part of the world,
he delivered many faithful warnings, suitable cautions and instructions,
greatly to the encouragement of the upright-hearted.

He was much devoted to the Lord`'s service, of a humble mind,
and exemplary upright conduct, accompanied with innocent cheerfulness;
was properly concerned that his temporal affairs might be conducted reputably;
and was greatly esteemed by Friends and others.

The exercise of his gift in the ministry was attended
with a striking and persuasive simplicity,
and being in the demonstration of the Spirit,
carried its own evidence with power to the hearts of the people;
directing them from all outward dependence to the everlasting foundation, Christ Jesus,
the rock of ages.

With a mind replenished with love,
he engaged in a visit to the meetings of Friends
in London and some of the southern counties;
and was favored to perform the same, in which he expressed he felt great peace;
but his complaints increasing upon him, he retired to a Friend`'s house at Tottenham,
and attended the meetings there on the First-day following,
being the last public meeting he was at, and in which he bore a living testimony.

During his sickness he was mercifully preserved in a tender frame of mind,
and expressed himself thus: '`I have seen my way into London, but not back;
but am quite resigned to the Lord`'s will.
I have labored honestly and uprightly in my great Master`'s cause, and have peace.
I am gradually sinking away.
I desire some of you, if I should be removed, to write to my wife,
and remember my very dear love to her, and to my children.
It will be a close trial to them; but it will be well with me,
and it is my earnest desire for my children, far above all other considerations,
that they may seek the God of their father.`'

He desired his love might be remembered to friends in the north; and said,
'`I have looked towards home with a degree of anxiety, but it was soon taken away,
and now I feel my mind quite easy,
and resigned to the will of him who has been with me all my life long,
and who knows what is best for me.`'

At another time he said, '`People may think of putting off repentance to a dying hour;
but what should I do now, if I had my peace to make.
It is enough to bear the afflictions of the body: '`and added, O Lord,
preserve me in patience, to wait your time.`'

To a friend going into the room, when he had been in great pain,
and requesting to stay with him, he said, '`You may go to your rest; leave me to my Maker,
who knows what is best for me.
All will be well; if I be restored, I hope it will be for his service.`'

To a friend who expressed some hope of his recovery,
and said that his removal would be a great loss in these low times, he said,
'`A stripping time must come, and it will come,
to take the dependence of men from each other;`' and he expressed
that it had often been the fervent exercise of his mind,
that the Almighty would be with him in his concluding moments.

The morning before his departure, taking a solemn leave of those about him, he said,
'`Weep not for me, I am going home; and shall be gathered as a shock of corn fully ripe:`'
begging to be preserved from murmuring till his change should come, which, he said,
would be a glorious change to him.

Thus, in a sweet frame of spirit, being sensible to the last, he departed this life,
at the house of Thomas Phillips, at Tottenham, the 24th of the Ninth month, 1785,
aged about sixty-eight years, and a minister thirty-four years.

His corpse was carried to Devonshire House meetinghouse, London;
after which it was interred in Friends`' burial-ground, near Whitechapel,
the 29th of the same.

[.asterism]
'''
REBECCA SUMMERS, wife of Thomas Summers, of Horsham, in the county of Sussex,
was visited with a painful illness,
which continued on her for about two years before her decease.
She bore it with exemplary patience,
having been all her life remarkable for the meekness of her spirit,
and innocence of her conversation.
She was a sincere lover of her friends,
a diligent attender of our religious meetings when her health permitted,
an affectionate wife, a tender parent, and a kind neighbor;
and of a remarkably forgiving temper to those from whom she had received injuries.
Nevertheless, towards the conclusion of her time, she was very low and poor,
and unsatisfied about her future state; which her husband tenderly observing,
said to her, that however the Lord`'s favor and acceptance might be hidden from her,
he had no doubt but it would be well with her, if she was now removed;
and expressed his fervent desire,
that it might please the author of all good to make known his love to, and acceptance of,
her, before her removal hence; which desire seemed fully answered.

She frequently said, '`Oh merciful Father, if it please you, cut the thread of my life,
and let me dwell with your peaceable ones; yet not my will but yours be done.`'
At another time she said, '`O merciful Father, who art in heaven, yours is the kingdom,
the power, and glory forever.
Hallelujah to the Lamb forever.`'
Being lifted up in bed, she bowed her head, and said, '`My soul is reverently bowed down,
I trust, under a sense of the Lord`'s mercy and goodness.`'
At another time she audibly and fervently said, I am upon the banks of deliverance.
I shall dwell with my merciful Father to all generations;`' adding,
'`it is of no merit to me.`'
She also frequently said, '`Come, sweet Jesus, come.`'

She was favored with her usual understanding; except at some intervals,
for about three days before her departure, she was somewhat wandering;
yet she perfectly knew those about her;
and at times as clear and collected as at any time during her illness;
by which she felt to the utmost the excruciating pain of body;
but evidently partook of that which the eye of man has not seen,
by which she was sustained through all.
Desiring to be lifted up in bed, not long before her end,
those about her intimating a fear it might be too much for her, she answered,
'`What matters it whether I sit up or lie down, if I die in the arms of my Redeemer?`'

Seeing her sister grieve, she said, '`Dear sister, do not do so, we shall meet again.`'
A little time before her end, her speech failed very much,
yet her senses seemed evidently clear; for on being asked what should be done for her,
she said, '`Pray without ceasing;`' and indeed it appeared to those present,
her practice at that time.

She departed this life the 13th of the First month, 1785,
and was buried the 16th of the same, in Friends`' burial ground at Plestow,
near Capel in Surry,

[.asterism]
'''
ISAAC WILSON, of Kendal, in Westmoreland, was the son of Anthony and Dorothy Wilson,
of Highwray, near Hawkshead, in the county of Lancaster,
by whom he was religiously educated;
and being favored with an early visitation of Divine grace, and obedient thereto,
he was preserved amidst the various temptations and
allurements to which youth is exposed.

Having with fidelity served his apprenticeship in Kendal, he settled in business,
and married Rachel, the daughter of John and Deborah Wilson, of the same place;
to whom he was united in a mutual engagement for the promotion of truth and righteousness,
and the welfare of his family, particularly in their best and endearing interests;
in his conduct towards his children, beautifully uniting the authority of a parent,
and the familiar persuasive influence of a friend.
His wife (of whom see an account in this collection)
was much engaged from home in the cause of truth;
and though the separation was a close trial to him, yet he freely gave her up,
encouraging her to follow the pointings of duty;
being sensible that obedience to divine requirings brings peace,
and an increase of light and strength.

Although he was zealously concerned for the support
of our Christian testimony in all its branches,
yet his zeal was so tempered with charity,
that he retained the esteem even of the unfaithful.
A care rested on his mind to preserve love and unity, and where any breach appeared,
he labored to have the occasion timely removed;
and also was much engaged to give private admonitions.

About the fortieth year of his age,
he was concerned publicly to testify to the efficacy of
that divine principle which had been the guide of his youth;
in the exercise of which duty his labors were edifying, and he was lively and fervent.

Although his family was large, and his engagements of a public and private nature many,
yet he so ordered them, as not to interfere with his religious duty,
being concerned constantly to attend meetings both for worship and discipline;
frequently attended the yearly meeting in London; and, in company with other Friends,
visited the monthly and quarterly meetings of Friends in Ireland, Scotland,
and some parts of England.
His disposition was hospitable and charitable;
his conversation was informing and edifying, accompanied with affability.
Being of sound judgment and integrity,
he was often applied to by Friends and others for his advice,
which he freely communicated, and to be an arbitrator in differences,
by which means he contributed to the peace of many families.
Notwithstanding his industry for the support of a numerous family,
he was earnestly and constantly concerned to limit his pursuits in number and extension,
agreeably to the circumscribing rule of truth.

Having been thus diligently concerned, through Divine assistance,
to fill up the religious, relative and social duties of life;
he experienced the gracious power that had been the stay of his youth,
and a support under every trying dispensation of Providence, to be his evening song,
and a staff to lean upon in declining age.

The last two years of his life he was much tried with indisposition;
but the following expressions show the situation of his mind,
which he delivered the day before his death, in the presence of some of his children,
with great power and energy, though under much bodily weakness:

'`I know not how it may be; I may remain with you a while longer,
or be removed at this time; but I am easy as to the event.
If, at times, I breathe a sigh, or a groan, it is not from a troubled mind.
I feel no weight upon my spirit; but all seems clear.
The world, and all that is in it, are nothing to me.
Though I have been tried with pain of body, and deep inward poverty,
yet now the Divine presence is near, and I am thankful to feel I am not forsaken.
The Lord has been with me all my life long, and poured down his blessings upon me;
and he will, my dear children, be with and support you, if you are concerned to seek him.
Oh the matchless lovingkindness of our God!
The tongue of men and angels is too short to show forth his praise.`'
And, after making a kind of melody, which cannot be expressed, he sweetly added, '`Peace!
Peace!
Peace!`'

Thus, with a well-grounded hope that his day`'s work was finished,
he died the 18th of the Eighth month, 1785; and was interred in Friends`' burial-ground,
at Kendal, on the 23rd of the same,
after a large and solemn meeting held on the occasion: aged seventy,
having been a minister thirty years.

[.asterism]
'''
KEZIA MERRYWEATHER, wife of John Merryweather, of Ringwood, in Hampshire,
was the daughter of Benjamin and Elizabeth Evens, of Woodbridge in Suffolk;
who were careful to train her up in a godly conduct, which was blessed to her,
for she gave early proof of an attachment to virtue.
After her marriage it pleased the Lord to permit
weakness of body frequently to attend her,
which, at length, terminated in a settled decline.
In the course of her illness, she gave good advice to several who came to see her;
dropped many comfortable expressions;
and was preserved in much patience and resignation.

Her husband and sister being with her, she expressed to them,
'`I would not have you sorrow as without hope.
Oh, what a difference there is between those who have
endeavored to come up in the path of duty,
and those who have followed lying vanities, when they come to such a time as this.
Now I know the difference.
When I first felt that I was taken for death, I seemed to have a little fear;
but it was soon removed, and now I long for it.
Oh! how I long to be in the full enjoyment of what I now feel.
Lord, hasten your messenger, if consistent with your will.
I believe the Lord, who has been with me in six troubles,
will not forsake in the seventh.`'

Her husband going into her room about two hours before her departure, she said, '`My dear,
I sent for you to see your poor dying wife; but I would not have you hurry yourself,
but come and sit down by me.
I feel so comfortable, I cannot express it; no pains; only cold!`'

She soon after prayed to this effect: '`Oh!
Lord, you have been a gracious God to me; be with me at this time;
and if it be your blessed will,
grant me an easy passage from this troublesome world to the mansion of rest,
where all sorrow is at an end, and all tears are wiped away.`'
Soon after, '`I feel so sweet and easy, that it does not seem as though I could be dying;
if I am, it is a mercy I cannot be sufficiently thankful for.
I did not think it possible for one in such a situation to be so easy.`'
On the apothecary coming in, and asking how she did, she answered, '`Very comfortable;
waiting to go to rest, which I believe will be soon.`'
Soon after, desiring to be turned on her right side,
she said she would have a little sleep, and then go to rest; which she did,
lying as in a comfortable sleep about a quarter of an hour; when, awakening,
she breathed a few times, and expired, without sigh, groan, or struggle,
the 29th of the Ninth month, 1785, aged twenty-eight years;
and was buried in Friends`' burial-ground the 6th of Tenth month following.

[.asterism]
'''
JUDITH HILL, wife of John Hill, late treasurer of Ackworth School,
was the daughter of Andrew and Judith Leaper, of London,
who educated her in the profession of the Church of England,
and brought her up in the practice of dressing, singing, dancing,
and other vain customs of this degenerate world.
These she was often made uneasy with; and about the twenty-third year of her age,
her understanding being further enlightened,
she gave up in obedience to the visitations of truth in her own mind,
joined in profession with Friends, and became a diligent attender of their meetings, and,
under a sense of duty, declined the customs of the world in speech, dress,
and deportment.

This brought much suffering upon her from her parents, especially from her mother; but,
being supported by that divine power that had convinced her judgment,
she bore with much patience the reproaches with which it was her lot to be tried,
which resignation was attended with peace;
and in time she experienced the regard of her near relations,
her mother expressing great satisfaction and full reconciliation with her.
After her convincement she entered into a married state,
and having in time a numerous family, she was concerned to educate them religiously.

In the year 1779,
a suitable friend being needed to superintend the institution of Ackworth,
on its being proposed to her husband, he, after due consideration,
engaged to go and reside there, and she occupied the station of mistress of the family.

About a year before her departure, her health gradually began to decline, and,
the last three months of her confinement, she underwent great bodily affliction,
but was enabled to endure it with exemplary patience
and resignation to the will of the Lord,
whom she found to be her abundant support.

In the forepart of her illness, one night,
being seized with a fainting fit and much pain, her husband, daughters,
and some others being present, being a little recovered,
she expressed herself as follows: '`How it may please the Lord to deal with me I know not;
but if he should be pleased to remove me this night,
I am fully resigned to his divine will, come what may.
I can truly say, I have not desired for myself or children,
either riches or length of days, but that they might be nurtured in the fear of the Lord,
and inherit a portion in the blessed truth.`'

At another time, her husband questioning with her, '`Have you any word of comfort for me?`'
After a short pause, she answered,
'`How it may please the Almighty to order it concerning my life,
is at present hid from me; but this I know, the Lord brought us together,
and has supported through many deep trials and afflictions.
When I have to look back to my childhood and education,
I have cause to acknowledge with great thankfulness, that his preserving hand,
in the time of ignorance,
kept me from joining with the many evils and temptations which were in my father`'s family.
When greater light and understanding were given, I gave up in obedience thereto; and now,
on a strict search, find nothing stands in my way to eternal happiness.`'

When she drew near her end, among other expressions, she said, '`I hope and believe,
when the Lord is pleased to remove me,
to be favored with a place in his glorious mansions.
I can truly say, if I die now, I die in peace with all men.
I have not done many mighty acts, or been a conspicuous character in the world;
nor have I desired it, but, I hope, endeavored, according to knowledge,
to live up to what was manifested to be my duty.`'

The morning before she departed, her daughter hearing her speak,
thought she wanted something, and went to her bedside; she said, '`Did you not hear me?
I said the sting of death, which is sin, is taken away.
The pale horse and his rider will have no victory,
for the guardian angel of the Lord`'s presence encompasses about.`'

After expressing that her time here was near closing,
she desired to see her husband and children, and took a solemn leave of them,
with some tender exhortations and remarks;
signified that her mind was covered with the universal love of God; and added,
'`I feel my little strength weaken quickly,
but my faith in the Lord grows stronger and stronger.
I have a firm hope, and an unshaken assurance of entering everlasting happiness.`'
A solemn pause ensued; then she broke forth in manner following: '`Awful, solemn silence,
how comfortable!
It has been refreshing to my mind at this time.
O seek after it, dear children; keep low and humble,
for all that is exalted shall be brought down; yes, the sturdy oaks of Bashan,
and the tall cedars of Lebanon, will the Lord lay low.`'
Then taking her husband and children each by the hand, she kissed them,
bidding them Farewell, farewell in the Lord.

She quietly departed this life without sigh or groan, the 26th of Tenth month, 1785,
aged nearly sixty years, and was interred the 30th of the same,
in Friends`' burial-ground at Ackworth, in Yorkshire.

[.asterism]
'''
THOMAS ROSS, of Wrightstown, in Bucks county, Pennsylvania, having,
with the near sympathy and unity of his friends and brethren,
come over to England to pay a religious visit to Friends there,
arrived a few days before the yearly meeting in 1784, which he attended,
and afterwards visited Ireland that summer.
On his return, he joined his friend John Pemberton, of Philadelphia,
in visiting the quarterly meetings at Woodbridge and Norwich,
and proceeded forwards to Lincoln, York, and, by Durham, into Scotland.
They had many meetings among those of other societies,
which were generally large and satisfactory; but his bodily indispositions increasing,
he was under the necessity of resting at sundry places; and,
taking a few meetings by the way, he reached York the 2nd of the Eleventh month, 1785,
and attended their monthly meeting the day following,
which was the last meeting he was at.

During the course of his travels, his religious labors were truly acceptable to Friends,
and well received by others; for,
having an especial eye to the putting forth of the Divine hand,
his ministry was attended with living virtue and deep instruction;
and though not in the words which man`'s wisdom teaches, yet in godly simplicity,
and with a zeal becoming true religion.

In meetings for business, he was particularly serviceable;
his remarks being mostly short, pertinent, and very instructive;
exciting to a steady attention to divine counsel
in the transacting of our Christian discipline,
and therein to exercise true judgment, without partiality or respect of persons.

During the course of his illness he was preserved in a heavenly frame of mind.
On many occasions dropping instructive counsel and advice
to the friends who attended on and visited him;
of which the following collection is but a small part.
He frequently said that he knew not why he was continued
in such an exercised state of bodily weakness;
yet doubted not but that it was all in wisdom, and for some good end; adding,
it was not for the clay to say to the potter, '`Why have you made me thus?`'

Sitting in the family where he was, during the forepart of his illness,
he expressed himself thus: '`Dear young people, keep to your first love;
the bridegroom of souls will not be unmindful of the bride while she remains chaste;
some of you, I believe, are espoused to Christ.
O, the ardent desire which I feel for the youth! "`Your name is as ointment poured forth,
therefore do the virgins love you.`"`'

The same day, I have not sought mine own honor,
but the honor of Him who first drew me from my habitation,
and have great reason to praise his name.
One thing which inclines me to think my work may be nearly done is this;
that it never appeared to be laid upon me to pay a general visit to England.`'
At another time he said,
'`O the harmony there is in the Lord`'s family! "`Ephraim shall not envy Judah,
nor Judah vex Ephraim; nothing shall hurt or destroy in all your holy mountain.`"`'

Again he remarked, on his being under bodily oppression,
'`I find no relief but when I feel a revival of that which is the healer of breaches;
but that is not at my command.
My mind was last night much drawn out to my fellow-laborers; O, that they +++[+++may]
keep little!
I have remembered that saying,
"`There are a few names even in Sardis who have not defiled
their garments,`" and I hope there are a few in York.
Dear friends, what a people should we be, did we dig deep enough.
Our lights would shine before men; we should be as the salt of the earth.
How many, who have begun well, have had their garments defiled with the world,
and are become like the salt that has lost its savor.
These are as dead weights in our assemblies,
so that the living are scarcely able to bury the dead.
O, Friends, keep to the truth, for it shall rise above the heads of gainsayers.`"

At another time, '`I could not be more at home any where.
It revives me to see the children about me.
I tell you; young people, the hardest thing I ever found in my passage was,
when I was right, to keep so.
Oh, the desire I felt to get here!
The love I feel for you is like the love of Jonathan and David.
It extends over sea and land; it is like the precious ointment;
so that some can say with one formerly, "`Neither heights nor depths,
principalities nor powers, things present, or to come, shall ever separate us from it.`"
The least sun casts a luster, as the glorious luminaries in the outward creation;
so that we may say, "`Great and marvelous are your works, Lord God Almighty;
just and true are your ways, you King of saints!`"

Again, '`Commune with your own heart, and be still;`" this is doing business.
Oh, how precious is truth!
It may employ us on the highway, and in our outward engagements.
Dear friends, let us prize it.`'
Speaking to the physician, he said, '`The outward man grows weaker;
yet inward support waxes stronger and stronger.`'
The same day he said, '`It is a great favor to have a brook by the way!
Oh! I see my way over all!
It is like a foretaste of what is to, come.
"`Blessed are the dead that die in the Lord!`"
When he breaks in upon us it is like balm.
"`There is balm in Gilead.`"
There are many not willing to go to the house of mourning; but there is occasion for it;
it being high time to repair the breaches.
I have thought for many weeks past, the curtain was nearly drawn.
There seemed but few sands left in the glass;
and yet I sometimes feel such a travail for Zion`'s prosperity,
and the enlargement of her borders,
that I am ready to think the day`'s work is not yet done; and at other times,
I feel so feeble and weak, that all seems nearly over.
The event I cannot tell, but am`' favored to be resigned.`'

At another time, '`Think nothing too near, or too dear, to part with, dear young people,
to purchase the truth.
Your parents cannot give it you, though they may give you all they can.
It is the Lord`'s prerogative.
I have thought it was a great favor to have an education in the truth;
but I have been grieved to see many born in the Society, like Esau,
selling their birthright.
Be not ashamed of the cross, dear friends, deny Him not before men.`'

Again he added, '`Beware of lawful things;
these lawful things are the strongest bait Satan ever laid for our society.
Oh, these lawful things, they have hurt many.
What a testimony would it be, if Friends were to shut up their shops on week days,
to go to meetings, which ought to be the main concern;
though many consider worldly things as such.
When we have done all we can, we are but as unprofitable servants;
we can add nothing to Him who is the fountain of goodness.
Oh, that ocean of ancient goodness!
I seem at times as if I was swallowed up in it.
I have cause to be thankful, that I am favored with a resigned mind, and have no will,
either to live or die.
Oh, Father, receive me into your bosom.`'
At another time, '`Oh, my heart is knit to you, my friends;
and to the seed which is in bondage in many hearts;
and though you may have to go with it into the wilderness, yet be not discouraged.`'

Feeling himself easier, and his mind favored, he said, '`Oh, when he puts his hand in,
as at the hole of the door, how does it smell of sweet myrrh.
I hope I am not insensible from where my help comes.
He sometimes hides himself as behind the curtain,
yet we must not awake or disturb our beloved until he please.`'

Speaking on the general state of mankind, he said thus: '`Oh,
how has my mind been oppressed,
in observing that profaneness which abounds among the people;
many of whom draw iniquity as with cords of vanity, and sin as with a cart-rope.
Yet I have this satisfaction,
that I have not failed to reprove many of those I have seen in this state;
and have often advised innkeepers and others,
to discourage all kinds of wickedness in their houses.
My advice has been generally received without gainsaying,
and I have comfort in the discharge of this duty.
Oh, the vileness of the land of Ireland!
Surely if any nation ever had occasion to mourn because of oaths, that has.`'

Being under much bodily affliction, he said,
'`How can one die better than in the Lord`'s service;
for he has been indeed a wonderful counsellor; he has many times opened a way,
when I could see no way; he will never leave nor forsake those who trust in him.`'
Again, '`It is a trying time, and yet,
I believe I have a well-grounded hope of having done my duty.
I feel no condemnation.
O, dear friends, what a favor indeed, that we have an unction from above!
Keep to the truth and its testimony, whatever may be the consequence,
for it will rise over the heads of gainsayers.`'

At another time,
'`It will not do for any to rest contented with having known the Lord in days past,
and years that are over and gone.
We must follow on to know him; a supply of daily bread is requisite;
and if there is not a hunger and thirst after righteousness,
we may be sure the mind is distempered.
But oh! how have I been pained to see and feel, many of the professors of the truth,
going after the world and its spirit; who, instead of being way-marks,
are as stumbling-blocks to honest inquirers: the state of these is lamentable.
I have been comforted in the prospect of a rising generation,
if they are not hurt by those who ought to be helpers, loving this present world.
I have, in my time, met with many cross winds and boisterous waves;
but have been preserved in a care to keep near the point,
that guides to the harbor of rest.
For these fifty years I have been endeavoring to fight the good fight of faith.
O, dearest Father! not my will, but yours, be done.
Oh, when will the curtain be drawn; that this mortal may put on immortality,
and eternal life, which will, I do believe, be my happy portion!`'

He would often, in thankful commemoration of the goodness of God to him,
break forth in these words, '`What shall I render unto you, O Lord,
for all your benefits.`'

A few days before his decease, on
a friend returning from meeting, he said he had been favored with such a sweet calm,
that he hoped he should have passed away.
A day or two before he died, he broke forth sweetly in these words;
'`Oh joy! joy! joy!`' Again, '`O death, where is your sting?
O grave, where is your victory?
The sting of death is sin!`"
I see no cloud in my way.
I die in peace with all men.`'

He departed this life the 13th of the Second month, 1786, at the house of Lindley Murray,
at Holgate, near York; and was interred in Friends`' burial-ground, in that city,
the 16th of the same, in the seventy-eighth year of his age.
