== Chapter 8

[.chapter-synopsis]
* Henry Kite
* Dorothy Owen
* Job Scott
* Abigail Knight
* Elizabeth Drinker
* Samuel Spavold
* Mary Evens
* Sarah Evens
* Robert Evens
* Francis Evens
* Anna Maria Bowman

HENRY KITE, of Norton, in Hertfordshire,
was but little known to Friends in his early life,
being brought up in the National Church,
and for some time frequented the meetings of the Methodists.
Being favored with an awakening visitation,
he was brought to see the exceeding sinfulness of sin,
and to feel judgment on the transgressing nature in him;
and by obedience to these discoveries he became measurably reformed in life and conduct.

In the year 1768 he frequented our religious meetings, sitting therein in a weighty,
solid frame; and his general conduct being consistent,
he was in the year following received as a member.
A faithful discharge of the duties of his station, which was that of a servant,
procured the esteem of his employers;
who readily made way for his attendance of meetings for worship and discipline,
wherein he was very exemplary.

He was a man of a meek and humble spirit, and although not large in testimony,
yet he grew in his gift, in the exercise whereof he was plain, lively, and edifying,
reaching the witness of truth in the heart.
He was useful also in the discipline of the church,
having been frequently engaged therein to the satisfaction of his friends.
It was his lot to meet with several close trials, which he bore with Christian fortitude.

During his last illness, he said, '`My poor body is much afflicted,
but I am comfortable in mind, which I esteem a great favor.
I have paid my visit to the yearly meeting, and have no cause to repent,
for I believe I was in my place in so doing.`'
And at another time, to his wife, '`My dear, do not weep for me,
although my body is in a suffering state, my mind enjoys a perfect calm,
and I have no fear of death.`'
On being asked by one of his sons how he was, he replied,
'`You see your poor father laboring under great bodily affliction,
but I am preserved with a still, quiet mind,
and I feel the Lord`'s goodness graciously extended to me.`'

To his daughter he said, '`My dear, a few words have sprung in my mind, very comfortably;
which are, "`The Lord is risen in his holy temple,
let all the earth be silent before him.`"
What can the temple be but the body?
O, what a comfort to feel the Lord`'s goodness so graciously extended to me,
a poor creature.
I can truly say, I have given all up.
I have committed all into the hands of a merciful God, to do with me as he pleases:
either to take me, or restore me to health; I have no will in it.
O, what a favor is this, to be resigned either to life or death!`'

At another time, '`I have to remember that "`the Lord is a strong tower,
whereunto the righteous flee, and are saved.`"
I can with great thankfulness say to my God, "`I have fought the good fight,
and have kept the faith,
henceforth there is laid up for me a crown of righteousness.`"`' The day before he died,
among other things, he said, '`I am clear of the blood of every one.
I feel my disorder making its progress,
and it appears to me that I shall be removed in a little time.
My bodily affliction is great, but the sweet peace of my mind is far greater.
O, how I feel the sweet influence of heavenly love!`'

He departed this life the 15th of the Sixth month, 1793, at Norton,
aged about fifty-five years, and was buried on the 21st of the same,
in Friends`' burial-ground at Baldock; and a minister about twenty-four years.

[.asterism]
'''
DOROTHY OWEN, of Dewispren, near Dolgelly, in Merionethshire,
was the daughter of Rowland and Lowry Owen, of the same place.
She was educated in the profession of Friends, notwithstanding which,
she in her youth accompanied other young people in vain and unprofitable amusements.
But about the sixteenth year of her age, being favored with a visitation of divine love,
she became sensible of the errors of such ways; and,
by a strict attention to the reproofs of instruction,
and submission to the operation of truth,
she experienced redemption from the love and spirit of this world.

About the twenty-third year of her age, she appeared in a public testimony;
and her conduct being consistent therewith,
she was made instrumental to the convincing and gathering of many to the
principle and profession of the truth in the neighborhood where she resided;
where, from removals and defection,
the members of our Society were reduced to a very small number.

The sweet savor of her zealous, humble, meek example, and her dedication of time,
faculties, and property, though in low circumstances,
to the glory of God and the good of her fellow creatures,
had a powerful tendency to enforce the doctrine she preached.
She was remarkable for her diligence in the attendance of meetings for worship and discipline,
from which neither distance nor weather kept her back, while of ability;
and she frequently went nearly forty miles on foot in that mountainous country,
to attend the monthly meeting:
even when the inclemency of the season rendered it not only difficult but dangerous.

She contented herself with the least expensive manner of living and dress,
in order to have the more to distribute to the necessities of others;
tenderly sympathizing with the poor inhabitants around her:
and so bright was her example, that one, not in profession with us, declared,
'`Her conduct preaches daily to me.`'

Her last illness was lingering and painful, which she bore with exemplary patience,
and was eminently favored with divine peace,
so as sensibly to affect and gather the minds of those who visited her,
into a sense of the same blessed influence.
Her prospect of future happiness was unclouded; and she said very near the conclusion,
'`The arms of divine mercy are wide open to receive me.`'

She died the 12th, and was buried in Friends`' burying ground at Tyddyn-y-Gareg,
the 17th of the Seventh month, 1793, aged about forty-two years;
and a minister about nineteen years.

[.asterism]
'''
JOB SCOTT, of Providence, in Rhode Island,
was removed by death while on a religious visit in Ireland.
He was a man of strong understanding and quick discernment;
but still more remarkable for having experienced
the vigorous faculties of his mind reduced,
in no common degree, under the humbling power of truth.
When young, he was, according to his own account, much addicted to levity of conduct;
and it is probable that the close exercises which he afterwards passed through,
and the scrupulous disposition of mind in which for some time he appeared to live,
were as the necessary inflections of the crooked wand to the contrary side, in order,
at length, to reduce it to perfect straightness:
wisdom even tormenting with her discipline, and at length returning the straight way.

He arrived in London in the First month, 1793,
and labored diligently in the occupation of his talent as a gospel minister,
in and near the city, until the latter end of the Third month;
when he proceeded leisurely to the Welsh yearly meeting, held at Carmarthen.
On this occasion, as well as at the succeeding one of the Bristol yearly meeting,
his business seemed to be that of leading the people from a reliance on preaching,
by becoming himself, throughout, an example of humble silence.

He afterwards attended the yearly meeting in London, in the last sitting of which,
he delivered some memorable hints respecting the commotions then prevailing in the earth;
and pointing to the path in which the righteous, in such seasons of overturning,
might tread with safety.
After this he went, without much delay, to Ireland;
to the meetings of which he paid a general visit,
and returned to Dublin in the Eleventh month;
but not finding himself clear of a belief of more service in that country,
he went to Ballitore, at which place he fell sick with the small-pox.
He asked several questions respecting that disease;
and afterwards very emphatically declared,
'`It is no matter what is the disorder;`' and in a little while added,
'`Its being that or any other, does not at all alter my feelings.`'

A friend observing that his getting well through it would be a great favor,
he replied with a smile, '`Whichever way it is, I hope I shall get well over it.`'
He also said, '`There is an eternal arm underneath each of us,
which is sufficient to bear up and support; and will do it,
as far as it is needful we should be supported;
and I have long been confirmed in this sentiment,
that nothing could possibly happen that would harm or injure me,
while I kept under the divine influence.`'
Some time after he said, '`Though I am not without some considerable bodily pain,
yet I feel such a portion of that good which is infinite,
that it does not seem worth mentioning.
If there was no greater enjoyment hereafter,
the present would be a state truly desirable, through a never-ending eternity: and yet,
the fulness is still more desirable.`'

To relate all the instructive and comfortable expressions which he uttered,
would swell this account beyond the proposed limits.
A week before his close, dictating a letter to his relations and friends,
after mentioning that his distress of body, through extreme difficulty of breathing,
had for a short time been almost equal to anything
he could suppose human nature capable of supporting,
he said, '`Just now, and for several hours past,
I have been almost as easy as at any time in my life; I think certainly,
never more so in my mind.
I feel no kind of alarm; but the issue is certainly very doubtful.
I feel easiest to address you in this manner,
principally that you may know that my mind enjoys a fulness,
in that which removes beyond the reach of all sorrow.`'

'`I suppose my love was never in a state of greater enlargement,
or less tinctured with selfishness, to all my relations and friends the world over.
My desire for my children`'s substantial growth in the truth,
and strict adherence to all its discoveries, to the close of their days,
is by far the principal wish I have for them.
Out of the enjoyment of a good degree of this precious inheritance,
I know of nothing in this world worth living for.
You that know it, suffer nothing, I most cordially beseech you,
ever to divert your minds from an increasing and fervent pursuit after the fulness of it,
even unto "`the measure of the stature of the fulness of Christ.`"`'

Afterwards, in addition to the foregoing letter, he added,
'`My spirits are under little or no depression at all.
Perhaps I never saw a time before, when all things not criminal,
were so nearly alike to me, in point of any disturbance to the mind.
I do not know, but that when awake, and capable of contemplation,
I nearly rejoice and give thanks in all.
When I verge a little towards sleep, I am all afloat, from the state of my nerves; and,
from the extreme irritation, forced almost immediately,
and with very unpleasant sensations, from beginning repose; but, through all,
the soul seems deeply anchored in God.`'

'`Many and painful have been the probationary exercises of this life to me.
Ah! were there probability of strength, how I could enlarge;
for my heart seems melted within me in retrospective view.
But all the former conflicts, however grievous in their time,
are lighter now than vanity;
except as they are clearly seen to have contributed
largely to the sanctification of the soul;
as they are remembered with awfulness and gratitude before him,
who has not been lacking to preserve through them all;
and as they seem likely to introduce, either very shortly, or before a very long time,
to an exceeding and eternal weight of glory.`'

'`My very soul abhors the idea, that a Christian can ever be at liberty,
while under the influence of heavenly good, to seek, or even desire, much wealth;
though this disposition, in direct opposition to the life and doctrine of Christ,
has gone far towards the destruction of true spiritual religion, I believe,
in almost every religious society in the world.`'

As nature became more oppressed with the disease, he observed it, and said,
that if ever he rose above the present weight which he felt, and seemed sinking under,
it would be through the marvelous display of eternal power and influence.
He requested that if he were removed,
some further particulars might be transmitted to his friends at home; adding,
in substance, '`The Lord`'s will is blessed, and I feel no controversy with it.
It is the Lord that enables me to coincide with his will,
and to say amen to all the trials and conflicts he permits to attend us.
I do not expect to have much to communicate in the course of this disorder,
or that my strength will admit of it;
but my mind is centered in that which brings into perfect acquiescence.
There is nothing in this world worth being enjoyed out of the divine will.`'

Two days before his decease, he said, '`I have no fear;
for "`perfect love casts out all fear; and he that fears is not perfect in love.`"
The same day he prayed thus; '`O Lord, my God,
you that have been with me from my youth to this day, if a man who has endured,
with a degree of patience the various turnings of your holy hand,
may be permitted to supplicate your name, cut short the work in righteousness,
if consistent with your holy will.
You who have wrought deliverance for Jacob,
evince that you are able to break my bonds asunder, and show forth your salvation,
that so my soul may magnify your name forever and ever.`'
And after a short pause, wherein he seemed to feel the earnest of his petition, he added,
'`So be it, says my soul.`'

He frequently gave a word of caution to such as visited him;
and after affectionately addressing one Friend he said,
'`I am waiting patiently for the salvation of God; do you wait with me.
I have no desire, nor the shadow of a desire, to be restored.
I hope the doctors will soon find they have done their part.`'

The evening before his decease, he said, '`You may tell my friends in New England,
and every part of the world,
that never did my soul bless the Lord on account of any worldly enjoyments, as I do now,
in the blessings felt by me to be contained in the prospect of a very speedy release.`'
At another time he said,
'`Some of my wishes are centered in as speedy release as
may be consistent with the will of our heavenly Father;
and an admission, which I have no doubt at all, not in the least degree, of obtaining,
into that glorious kingdom, where the wicked cease from troubling,
and the weary soul is eternally at rest.`'

After another lively declaration, he added, '`I feel,
and I wish you to feel for and with me, after the eternal rock of life and salvation;
for as we are established thereon we shall be in the everlasting unity,
which cannot be shaken by all the changes of time,
nor interrupted in a never-ending eternity.
I do expect considerable derangement will now take place.
It is no discouragement to me, and ought to be none to those who trust in the Lord,
and put no confidence in the flesh.`'

Early in the day in which he was removed, under much suffering, he petitioned, '`O, Lord,
if it be consistent with your holy will, let loose my bonds,
and send the moment of relief to my poor body and soul.`'
Afterwards he said, '`We cannot approve or disapprove, by parts,
the works of Omnipotence rightly; we must approve the whole, and say,
"`Your will be done,`" in all things.`'
And a short time after, his bodily afflictions being great, he said,
'`I find all things must be endured.`'

The extremity of his pain sometimes occasioned him to fear lest he should be impatient;
and he said to the physician, '`Make great allowance for me,
my distress is nearly as much as is supportable by human nature.`'
The physician saying there was a probability of his being very soon released,
perhaps in an hour or two, he replied, '`If so,
the Lord`'s name be blessed and praised forever.
I had much rather it were so than otherwise;
for some time I perceived it hastening fast;`' adding,
'`The desire of my heart is the great blessing of time, and the consolation of eternity.`'
After a while he said to a friend, '`Guard against right hand errors.
Let self be of no reputation; trust in the Lord, and he will carry you through all.`'

He died the 22nd of the Eleventh month, 1793, at the house of Elizabeth Shackleton,
at Ballitore; and was buried the 24th in Friends`' burial-ground there.
He was about forty-three years of age.

[.asterism]
'''
ABIGAIL KNIGHT, daughter of Joseph Knight, of Messing, in Essex, being taken ill,
it was soon perceived that her disorder tended to her dissolution.
Her father tenderly acquainted her with the prospect.
She expressed that she had not much desire to live;
that she did not see anything here to stay for; and, if she might go well,
that she was willing to die.
She was under great exercise of mind for some days, doubting her future happiness;
saying to her father she had done so many things she ought not to have done,
and wishing she had minded more the hints he had frequently given her.

On his telling her he had no doubt from the feeling of his mind,
that if she was removed by the present illness, it would be well with her,
she expressed her doubts and fears, continuing under great exercise for some time,
saying, '`I feel so much pain, that I cannot continue long, and I do not feel easy.`'
But after some days she signified she felt some case,
and hoped her sins would be forgiven her; and that she did not fear death,
but hoped to be favored with a more clear evidence before she departed.

Desiring to be with her father alone, she told him of the exercise of her mind,
which she had felt for attending religious meetings so carelessly.
That she thought it was mockery to sit in such an indifferent manner,
and let the things of the world take up the attention of the mind;
for which she had felt uneasiness, as much, she thought,
as for anything she had done amiss.
She signified that when at times she endeavored to be more gathered in her mind,
the enemy got in and obstructed it;
and that she found herself so weak through unwatchfulness at other times,
as not to be able to withstand his suggestions.
After this conversation she said she felt herself more easy.

Observing what a fine day it was, she said she had thought of one who said,
'`How gloriously the outward sun does shine!
So does the Son of righteousness shine this day on my soul;`' and
hoped she could in measure adopt the language as her own;
that the things which stood in her way seemed gradually removed;
and that she hoped to be favored with a more clear evidence before she departed.
To her sister she said, '`I have but little time,
but if I had my time to spend over again,
I should spend it very differently;`' and that if she might
have the least place in the kingdom of heaven,
it was all she desired; which she thought would be granted.

In the evening, a lad, a member of our Society, coming into the room,
she desired he would take warning by her, saying, '`I little thought, three weeks ago,
I should be so near death as I am;
and you do not know how soon you may be so near;`' asking him if he did not think
he should be in great trouble if he was brought unto such a situation.
She advised him to use the plain language, and plainness of dress;
that she had been too much inclined to dress, but felt great uneasiness,
and hoped for forgiveness; but she added, '`I believe I shall be happy.
I feel so easy in my mind;`' and added,
'`What a fine thing it is to have peace of mind upon a dying bed.
The nearer I am to the close, the more easy and clear my way seems.
I do not dread death,
but seem as if I could meet it with a smile;`' that it was a great favor,
for which she could not be thankful enough;
and that she could not have thought it possible for
her to find forgiveness in so short a time.

Towards the conclusion she signified the sting of death was taken away,
and added pleasantly, '`I think tomorrow, or next day, will finish here.`'
The next morning her father going to speak to her, she seemed quite calm,
and in a sweet frame of mind; and said, she loved to be still;
she felt her heavenly Father near, as an arm underneath,
and often admired the goodness and mercy of the Almighty to her,
in so soon removing things which stood in her way.

About ten o`'clock the same day she was taken with the pains of death,
which being hard to bear, she besought the Lord to give her patience to bear them.
About fifteen minutes before she departed,
when it was expected she would have spoken no more, she said, '`Lord Jesus,
receive my spirit.
Lord, take me to yourself.`'
Soon after, she said, '`Farewell all, in the Lord; my pain will soon be over,
the gates of heaven are open to receive me; the time is almost come.`'
Soon after she departed, on the 24th of the Second month, 1794,
in the nineteenth year of her age.

[.asterism]
'''
ELIZABETH DRINKER, wife of Daniel Drinker, of the city of Philadelphia,
being drawn in gospel love to visit the meetings of Friends in this nation,
arrived here about the Seventh month, 1793.
After visiting the meetings in the city of London, she proceeded into Kent, Sussex,
and the western counties, as far as Falmouth, returning through Bristol to London.
Though frequently tried with indisposition of body,
she was strengthened in her gospel labors to the comfort and edification of many,
being concerned to wait for, and move under, the fresh arisings of divine life.

In the Fourth month following, though in a declining state of health,
she visited the meetings of Friends in Hertfordshire, etc.,
but her complaints increasing, she stopped at Staines, in Middlesex, nearly six weeks.
While at this place she expressed to a friend an
apprehension that her time would not be long in mutability,
and at the same time mentioned, that as she sat in the meeting on First-day morning,
though she had nothing to communicate to others,
and part of the time felt low and discouraged, yet, towards the close,
her mind was comforted in the fresh revival of those expressions of the prophet Habakkuk:
"`Although the fig-tree shall not blossom, neither shall fruit be in the vine;
the labor of the olive shall fail, and the field shall yield no meat;
the flocks shall be cut off from the fold, and there shall be no herd in the stall;
yet will I rejoice in the Lord, I will joy in the God of my salvation.`"`'

She reached London the 18th of the Sixth month,
where for some time she appeared under great conflict of spirit; being very desirous,
if consistent with her Master`'s will, to return to her beloved connections and native land.
But this trying dispensation was permitted to pass over; and,
some time before her dissolution, she seemed relieved from much anxiety respecting them;
and was favored to bear her suffering with great patience,
evincing true Christian resignation and acquiescence in divine appointment.

She attended several meetings under great bodily weakness;
and her last public testimony was at Westminster meeting,
where she stood up with these words, '`Precious, very precious,
in the sight of the Lord is the death of his saints;`' on
which she enlarged instructively and encouragingly.

During her confinement she was led to speak instructively to those about her;
at one time nearly in these words: '`To look back, the world appears trifling and vanity;
and if fresh trials come, and the storm be permitted to beat as against the wall,
it is good to trust in the Lord, who, in gloomy seasons,
is the protector of those that fear him.
After encouraging those present to greater dedication,
she said that the highest anthem that could be sung was, "`Your will be done.`"
At another time she said she believed it was right
that she had given up all and left home;
whether for life or death, she must leave.

The last few days of her life she was much engaged in supplication,
uttering many broken sentences, which, though not fully gathered,
were expressive of the state of her mind,
and breathed the language of consolation and praise.

When near the close, her spirit seemed supported above the last conflict; and,
with an animated countenance, she said, '`Oh,
the beauty! the excellent beauty! the beautiful prospect
in view!`' Then lifting up her hands,
she appeared for some time in sweet silent adoration; after which she spoke but little,
and with difficulty; yet she appeared sensible.
She expired in the evening of the 10th of the Eighth month, 1794, so quietly,
that it was scarcely known when she breathed her last;
and her remains were interred at Bunhill-fields the 15th.

[.asterism]
'''
SAMUEL SPAVOLD, of Hitchin, in Hertfordshire, was born at Bawtry, in Yorkshire,
and had his education among Friends;
and at a suitable age was bound apprentice to a carpenter and joiner in that county.
In the forepart of his time he was much addicted to the follies of youth;
but through the merciful visitation of divine grace,
he became so effectually reached as to be stopped in his
career of vanity about the nineteenth year of his age,
and a short time afterwards received a gift in the ministry.

When out of his time, he came to London, and worked as a ship-joiner at Deptford,
and continued in that employment there and at Chatham for several years;
during which time he was frequently exercised in his gift, and grew therein.
Afterwards he removed to Folkstone,
where way was opened for his further service in the church.
In 1750 he settled at Hitchin,
and during a long series of years labored much in the work of the gospel,
in this and other nations; and was at times baptized into deep exercises,
which much excited the sympathy of his friends;
to whom he approved himself an exemplary pattern of condescension.

He travelled four times through Wales, and as many through Ireland.
He was once in America, and once in Scotland;
and was often engaged in family visits as he passed along;
and a universal love and charity accompanied his gospel labors.
Notwithstanding he was at times large in testimony, he was a lover of silence;
and had often to recommend a reverend humble waiting on God, saying, '`Oh,
how I love this silent waiting, to feel my mind humbled before that great power.
We need to be more inward; the Lord`'s people are an inward people.`'
His life and conduct spoke the same language.

He was remarkably diligent in the attendance of his own meeting, even in old age,
and when bodily infirmity rendered it difficult.
The latter part of his time he was afflicted with several complaints,
which brought on great weakness, and for many months confined him wholly at home;
and at times in much pain, which he bore with fortitude and Christian resignation,
often saying, '`It is all well,
I am content:`' he was also at times weightily led in testimony to some who visited him.
He would sometimes make mention of the love he felt towards his fellow creatures;
and once in particular signified it was so great, that if he had strength,
he could go and preach to them on his crutches;
and he often declared that the Lord had been wonderfully good to him.

Under great bodily affliction, two days before his death, he said to his wife, '`My dear,
I cannot express the joy I feel; the Lord is very good.`'
A little after, '`Eternity is exceedingly solemn and awful to my mind;
a state of eternal duration;`' adding,
'`It rejoices my heart that there are many fellow-travelers going,
as with their hands on their loins, towards the heavenly Jerusalem and land of rest.`'

'`Man is made to glorify God while here, and enjoy him forever in a glorious eternity;
glory and honor be to his great name and power, and that forever.`'
And afterwards to the following import; '`I rejoice in my heart, and am glad,
that the Lord has enabled me to follow him in the straight and narrow way of the cross,
which he has prepared for his children and people to walk in.`'

On the day he departed, among other things uttered in great weakness and difficulty,
but evincing the sweet and heavenly state of his mind, he said,
'`The truth is a precious thing; it is worth seeking for.`'

He seemed pleased with the company of those about him, affectionately saying to some,
on taking leave, '`Farewell, I love you all.`'
He quietly departed this life on the 9th of the First month, 1795, at Hitchin,
in the eighty-seventh year of his age, and was interred there on the 15th;
having been a minister about sixty-five years.

[.asterism]
'''
MARY EVENS, a young woman of seventeen, daughter of Benjamin and Elizabeth Evens,
of Woodbridge in Suffolk, and eldest sister of Kezia Merryweather,
mentioned in the Ninth part of Piety Promoted, was taken from the probations of time,
on the 1st of the Eighth month, 1770:
the following account of her close is but little altered
from one penned by her pious and affectionate mother.

She may be truly said,
to have been an example of patience and resignation
through the whole course of her affliction;
and though (continues her mother) I was almost constantly with her,
yet I never heard her in the least murmur or repine,
though her pain was often very violent; but, she frequently said,
that she was afraid she should not have patience enough.

On the last day which she lived, she lay pretty easy till towards noon,
when she was seized with violent pain in her side.`'
Dear mother, '`said she '`lift me up, I cannot breathe.`'
The pain continued exceedingly sharp for three hours,
during which time she was often concerned to beg for patience;
and desired her father and me to pray for her, that she might have patience granted.
'`Dear mother,`'she said, '`you can not think what pain this is.
This is pain indeed.`'

In her greatest anguish, she broke forth in supplication to the Lord for a little ease,
saying, '`I have received many comforts from your hand, O Lord;
more than I could expect or desire;
and if you are pleased to take me to yourself this afternoon,
it will be the greatest comfort I ever received in my life.`'
After this, observing her to lie still,
I asked if she should like to speak to her brothers and
sisters +++[+++most of whom were younger than herself]. She said,
'`Yes,`' distinctly took leave of them all, and said at parting, '`All, mind and be good.`'
Seeing one of her sisters much concerned, she added,
'`Don`'t fret for such a poor thing as I am.`'

After this, it pleased the Lord to grant her request, and to give her ease.
She gratefully acknowledged it, and had such sharp pain no more;
but lay in a sweet frame of mind, but drawing her breath shorter and shorter,
till the solemn moment arrived.
A few moments before her close, she gave me one hand, and an intimate friend the other;
thus quietly departing about six in the afternoon, as she had besought the Lord, and,
I doubt not, is entered into the heavenly rest of the righteous.

[.asterism]
'''
SARAH EVENS.--An account has just been given of Mary,
daughter of Benjamin and Elizabeth Evens, of Woodbridge.
I come now to relate another deprivation which, in less than half a year after her death,
these pious parents had to undergo in the loss of their daughter Sarah Evens,
who died at the age of nineteen, early in the year 1771.
In this relation, the memorandums of her mother will be my principal guide;
and I shall generally form my little narration in her own words.

But here,
seeing I have still the pious close of another sister and of two brothers to relate,
by which means Piety Promoted will probably contain accounts
of two sons and of four daughters of the same family,
it may not be improper, once for all,
to mention that the parents were persons not only of exemplary conduct themselves,
but very vigilant over that of their children.
Being themselves imbued with a sense of the value of the restraints of the cross,
they were careful to train up their dear offspring in such
a manner as to prepare them for bearing it faithfully,
when they had by degrees to act for themselves.
Some of them, we see, were early delivered from the trials of the world,
passing to final peace through a short path: others still survive,
to bless the Christian care and love, and even the pious restraints,
of their honorable parents.

On the 15th of the Twelfth month, 1770,
Sarah Evens had been down stairs for the last time;
and was very much fatigued with getting up again.
When a little recovered, she said, in an awful manner, '`Mother, I was afraid,
some time ago, I should never get to heaven; but now am in hopes I shall:
for I thought in my sleep, some days since,
that there was only a little piece of something white that kept me;
and I pulled it very hard to get it away; which I did, and then I got there.`'
Some days after, she said, '`I hope the time of my release will soon come.`'

On the 24th, having had a very restless morning,
between twelve and one she fell into a very comfortable sleep.
When she awoke, she said, '`I have been asleep, for which I am thankful.
It was what I prayed for: but I thought my prayers were not worth being regarded;
but they have been mercifully granted.`'
After a little pause she said, '`What should I do now, if I was like some?
May they be brought to a consideration of their ways.`'
Her mother replied, '`My dear, I hope your mind is easy;`' to which she answered, '`Yes,
quite so.
I have not anything that makes it otherwise.`'

Nevertheless, one day being very full of pain, and exceedingly low in her mind,
she said to me, '`Dear mother, I am afraid now I shall not be safe at last.`'
I asked her if there was anything that made her uneasy.
She replied, '`No, but only fears.`'
I said, '`My dear, endeavor to keep your mind still,
and I hope you will again be made easy.`'
On my going to her in the morning, and asking her how she did, she said,
'`My body is no better; but I am favored with an easy mind.
I never knew such a day in all my life as yesterday.
I am like another creature now, for now I witness peace.`'
She continued in patient resignation to the divine will,
not once expressing a desire to live longer,
but often saying it was better for her to go than to stay.
Thus she grew gradually weaker;
and on the last night of her sufferings she was exceedingly restless.
On my requesting her to be as still as she could, she lay still for a few minutes,
and then broke forth in supplication to the Lord, '`O! Father,
be pleased to grant me a little ease before you take me to yourself.`'
In a very short time her request was granted, and then she said,
'`I was afraid my prayers were not worth being regarded; but they have entered,
and I have rest.`'
She was often earnest to be released.
A friend about this time asking her how she did, '`You see,`' said she, '`how I do
I am going, I hope, to heaven.`'

She uttered many more expressions to the same import,
continuing to draw her breath shorter and shorter,
till between six and seven on the 16th of the First month, '`when,`'
continues her sorrowing, not repining mother, '`it pleased the Lord, who gave her to us,
to take her from us; and I doubt not in the least,
that she is entered into that rest which she so earnestly desired and prayed for.`'

And, though it is a close trial to part, yet,
as she expressed a little before her departure that she
had not the least doubt that we should all meet again,
several of her near relations being by her, the fervent breathing of my spirit is,
that we may be enabled to follow her, and live forever in realms of eternal bliss.

[.asterism]
'''
ROBERT EVENS, son of Benjamin and Elizabeth Evens, of Woodbridge,
finished his short course of eighteen years the 29th of the Eleventh month, 1772.
His decease was occasioned by a fall,
in which the butt-end of a fork was forced with violence against the pit of his stomach.
It did not prove immediately mortal, though he had more or less of constant pain,
which he endured with great patience.
His employment was at that time in agriculture,
and he was able to go about his usual business,
if he took care not to pursue it too eagerly;
otherwise the ill effects of over-exertion would occasion a confinement of several days.
He appeared to possess a firm mind, not easily to be moved; and a pleasant temper,
exceeded by few.

As his ailments did not yield to the means made use of, but were rather growing worse,
his employer thought it best for him to be under parental care;
and he returned home about ten weeks before the period of his life.
A rapid decline came on, accompanied with violent pain in the breast and stomach,
and with an almost incessant cough.

In the forepart of his illness,
he seemed to have some expectation that he should recover; but as his disorder advanced,
he was wholly divested of all thoughts of that kind;
and many times expressed to his parents the goodness of the Lord which he felt,
and the comfortable seasons which were his portion.
Being asked how he found his mind when looking to
that awful period which might shortly approach,
his answer was,
'`Entirely easy;`' and the last time a question of this sort was put to him, he added,
'`but it looks as if I might have a lingering time,
yet I hope to be preserved in patience.`'
Contrary, however, to his expectation, on the evening of the same day,
his pain greatly increased, attended with great difficulty of breathing.
No impatient expression escaped him; but, in the greatest extremity,
he fervently prayed for patience; and, between nine and ten, he resigned his breath; and,
says his pious mother and careful attendant, arrived, I fully believe,
at that mansion of rest, where he will sing high praises to Him who sits on the throne,
and to the Lamb, forever more.

[.asterism]
'''
FRANCIS EVENS, son of Benjamin and Elizabeth Evens, so often mentioned in this volume,
died when he had nearly attained the age of twenty-one, on the 25th of Tenth month, 1779.
I take this account of him, as most of the others, from the memorandums of his mother,
and I am inclined here to prefix the little introduction
with which she has prefaced her account of this loss.

"`My mind,`" says she, "`has often been humbled under the late trying dispensation,
wherewith it has pleased Infinite Wisdom again to try and prove us;
and the fervent breathing of my spirit at seasons is, '`Though tried, O Lord,
grant we may not be forsaken; and, though proved, let us not be forgotten of You,
you Fountain of all good, who, in the midst of judgment, remembers mercy.`'

Francis underwent much conflict of mind before he was enabled
to repose with confidence on the bosom of mercy.
Many days and nights he was tossed with tempest,
'`lest he should not be favored to obtain a habitation in the heavens.`'
But, after much labor, and fervent cries to Him who knows the integrity of the heart,
the arm of everlasting mercy was extended, and he was enabled to acknowledge it,
though he did not choose to enter into much conversation.
He appeared from time to time broken and contrited, and would often say,
'`No matter what becomes of the body, if the soul may but enter the glorious kingdom.`'
About two weeks before he died, his mother, perceiving him to be very low,
asked him whether he had any expectation of recovery; '`No,`'
he replied; `'in a very short space I shall be at my everlasting habitation.`'

His mother attended him constantly, and they had many solemn seasons together, which,
says she, were graciously owned by the incomes of the heavenly Father`'s love,
to the tendering of our hearts.
His fever, towards the last, affected his head; and,
when he could not be distinctly heard, his mind seemed attracted upwards.
Yet, probably from the degree of delirium which sometimes prevailed,
he felt occasional disquietude; and once, looking steadfastly at his mother,
who only was then with him, he said, '`I admire my mind should be so tossed;
but not from an apprehension I shall not be received,
for I have had a sure evidence of that.`'

The last two days of his life his pains left him in a good degree,
but the evening before he expired, he appeared to have a hard struggle for half an hour.
The next morning his sister,
passing the door of the chamber in which her dying brother lay, heard him loudly calling,
Father.
She thought her father had been in the room, but she found him below.
He went up directly, and told the youth that his sister said he had called him.
The youth looked attentively at his parent.
'`I did not,`' he replied, '`call for you; but to my heavenly Father.`'
Then he lay still again a few minutes, and quietly breathed his last.

[.asterism]
'''
ANNA MARIA BOWMAN, wife of Henry Bowman, of Ringwood in Hampshire,
and daughter of Benjamin and Elizabeth Evens, of Woodbridge in Suffolk,
sister to the subjects of the four preceding memoirs,
was carried off by a consumption in little more than a year after her marriage,
and in the 27th year of her age, the 20th of the Twelfth month, 1793.

About a month before this, she had been confined to her chamber,
from which time she gave up all expectation of recovery.
About this time a message of love was delivered to her from Samuel Emlen,
of Philadelphia, then in England.
He said that a passage of Scripture had dwelt on his mind on her account,
and that he should hardly do justice to his feelings if he withheld it.
"`In me shall the Gentiles trust, and their reign shall be glorious.`"
This Friend was remarkable for his acquaintance with the Scriptures,
and therefore I think there is some reason to suspect an error,
either in the delivery of the message, or the recollection of it;
for the text stands thus: "`To it (that is, the root of Jesse) shall the Gentiles seek,
and his rest shall be glorious.`"
The languid, diffident, and humble young woman, wondered that he,
an eminent and much beloved minister,
should notice her so much as even to send his love to her;
but she said that the sight which he had of her state was as balm to her mind.

The same evening she requested her husband not to grieve for her,
but to give her up cheerfully.`'
The more readily,`' said she, '`you resign me, the greater will be your peace.
We have lived in love the little time we have been together; and, as I said before,
the more readily you give me up, the greater will be your peace.`'
Afterwards she repeated to an elder sister, who was attending her,
the message of Samuel Emlen, and said to her, '`Well,
I have great encouragement to look forward; and I desire patience,
to continue to the end.`'
She desired her sister, who was writing to their parents, to give her duty to them,
and request them not to grieve;
and to tell them that she should be glad to see them once more,
but that she desired to stand resigned.

The next afternoon she was convulsed to such a degree,
as that those who were with her believed her to be near her close;
but on being put o bed, toward evening she revived, and,
after some inquiry respecting the attack from which she had just recovered, she said,
'`It was a fit, and a warning of what is coming.`'

To a young woman who visited her, she said, '`We have witnessed many seasons together,
and some, I hope, to profit.
I know your situation is much exposed.
You have kept your place, to your credit, and the admiration of many.
Stand open to the manifestations of truth.
Give up, give up, to what you know to be right, and you will find your account in it.`'
On the first of the Twelfth month, John Merryweather, the husband of her sister Kezia,
mentioned in the ninth part of this work,
was telling of the satisfaction which he had in seeing her so easy and resigned;
to which she replied, '`I stand ready, whenever the Lord is pleased to call.`'
Soon after, she desired to see her own brother, and, requesting him to take a chair,
said thus: '`Dear brother, I cannot express what I have felt for you this day.
I know your situation, and the difficulties you labor under;
but let me impress the necessity of attending week-day meetings as much as you can.
You will find your reward.
As to your wife (who the reader should understand
was not at this time a member of the Society),
let her alone.
She is a woman of tender feelings.
Do not persuade her one way or another, as to religion.
Be steady.
The Lord loves you.
I am sure he loves you.`'
She many times desired her relations not to fret; for that, she said, grieved her;
and once she said to her husband, '`Look as cheerful as you can.`'

The next day she was again faint and convulsed, but not so much as before;
yet in the night her sister thought her worse,
and inquired of her whether she were faint.
After a while she replied, '`No. I felt as if I wanted for nothing just then.
Be not frightened.
I do not feel as if I was going.
I think I shall have a clearer evidence at that time.
I think I shall.`'
Her cough and shortness of breath were often very afflicting;
but a sweetly composed frame of mind was the means of her daily support,
and was an instructive lesson to those who attended her.

On the 7th, as she was undressing, in order to retire to rest, she said,
'`I fear I shall not experience such a calm as I did last night.
I have reasoned several times today whether the favor was not too great to be mentioned,
for I felt as if I was in heaven, and saw the angels there.`'
She not infrequently talked in her sleep, and once was heard to say very distinctly,
'`When shall I drink of the water of that clear river?`'
This seemed to show that her sleeping, as well as waking thoughts,
were fixed on the eternal recompense of reward.`'

Her decline was rapid, and her patience did not fail;
but she often begged that it might be continued to her.
The day preceding her departure, her body was restless, she took but little food,
and requested that not any might be offered to her.
About one the following morning, she seemed inclined to sleep,
and desired the family would also retire.
At five, they were again called, and her husband going to her, she only said,
'`My dear Henry,`' and then fell asleep.
In about half an hour her breath became greatly affected for a few seconds;
but again recovering it, she laid her head on the pillow, and in her sleep,
so quietly as scarcely to be perceived, she sweetly breathed her last.
