== Chapter 9

[.chapter-synopsis]
* Elizabeth Evens
* Benjamin Evens
* Jonathan Raine
* Sarah Clare
* Potto Brown
* Tabitha Marriot
* Ann Naish
* Margaret Greenwood
* Jane Fryer

ELIZABETH EVENS.-- Though I have not to record many
particular expressions of Elizabeth Evens of Woodbridge,
wife of Benjamin Evens;
yet as notice has been taken in this volume of so many of her children,
who were conducted by the grace of their Redeemer to a peaceful close,
some account of their pious mother seems an addition almost requisite.

She was the eldest daughter of Francis and Mary Lawrence of Norwich,
and was deprived of both parents by the time she was about sixteen years of age;
at which early period the care of four younger sisters devolved on her;
and she performed her trust so well, that on her marrying, and removing to Woodbridge,
they also came, and dwelt in a house adjoining to her residence.

About the twenty-eighth year of her age, she came forth in the work of the ministry,
uttering in her own meeting at Woodbridge, these words;
"`Obedience is better than sacrifice, and to hearken to the voice of the Lord,
than the fat of rams.`"
This was in the year 1753.
Rather more than three years afterwards,
she set out on a visit to the meetings of Friends in Essex;
after the accomplishment of which service, she had this testimony to bear;
"`I had renewed occasion to be thankful that it pleased my great Master,
not only to move upon my mind to go forth in that service, but to go along with,
and safely conduct me again to my habitation in peace.
It is a cause of more joy than words cal express.`"

Notwithstanding she had the care of a large family of children,
and much affliction fell to her lot,
by the decease of several of them when they were just entering,
or had entered that time of life in which dutiful children become, in some respects,
the companions, the friends, the support, and the solace of their parents;
she continued freely given up to travel in the exercise of the gift which she had received,
as the pointings of duty were manifested to her.
The eastern counties, some of the northern and midland,
with the cities of London and Bristol,
were the principal parts to which her services were directed.

In the year 1782, she was much enfeebled by a paralytic stroke;
nevertheless she continued a diligent attender of meetings when bodily ability admitted;
and even sometimes, when many would think their weakness an almost insuperable bar.
'`Do not give up,`' said she on a particular occasion, '`the assembling with your friends,
for it is many times strength in weakness; and the poor mind,
being stayed upon Him who is the only helper of the helpless, is sometimes,
out of deep poverty, made in secret to bless the name of Israel`'s God.`'

It was also after this debilitating disease had been permitted to enfeeble her frame,
that she paid a religious visit to the meetings of London and some others in the neighborhood;
and after this she visited the families of Friends in Norwich,
and most of the meetings in the county of Norfolk.

She was at length removed from this state of trial,
in which she had so long endeavored to fulfill the gracious design of her Lord,
in visiting her with his love, the 13th of the Fourth month, 1796.
She was not long confined to her chamber, and during this time,
did not express much of her mental feelings;
but there was a sweet composure on her countenance,
which seemed to evince that her day`'s work was done; and that,
with becoming patience and holy resignation, she was waiting for the period which,
through his adorable mercy, should unalterably unite her to the beloved of souls.

[.asterism]
'''
BENJAMIN EVENS--It has generally been esteemed particularly encouraging, to observe,
in collections of this sort, the lively hope expressed by young persons,
who have early felt the touches of redeeming love,
have submitted to its purifying power in the dawn of their faculties,
and have been early gathered into the garner of rest.
But the survey of a long life,
passed in almost uniform conformity to the law of the gospel,
and closing in its peaceful spirit,
even though it has not been marked with the performance
of many signal and attractive acts of service in the church,
holds out probably an instruction equally valuable,
although of a species somewhat different.
One prompts the youthful mind to enter with alacrity,
and without reserve on the heavenly race; the other encourages the humble diffident mind,
which aspires after the crown that is at the end, and has already made some progress,
to persevere in it without fainting.

Benjamin Evens, of Woodbridge, in Suffolk, who finished a course of about eighty years,
the 27th of the Twelfth month, 1798, was considered by the Friends of that county,
as a good example, and a very diligent attender of their meetings.
In those for worship he at times bore a public testimony for truth,
having long been an acknowledged, and approved minister; and,
while his faculties retained their vigor,
he was conspicuously useful in supporting the Christian discipline of the Society.

He did not travel much.
There are not accounts of more than two journeys with a certificate.
The first was to Friends in the counties of Lincoln, Cambridge, Huntingdon, and Norfolk;
the other to those of London and its neighborhood.
At the time of this last visit he was already an old man, but humble and unassuming:
which just tribute to his memory, the writer of this short memorial,
who had then the privilege of having him for a guest,
is desirous of adding to the testimony of his Suffolk friends.

A little incident occurred during this engagement which may not be improper to relate.
In a meeting in which he had been largely engaged in testimony,
he misquoted a passage of Scripture, and in a way that materially affected the sense.
Finding out his error,
he rose again towards the close of the meeting to acknowledge it to the congregation,
to show how his variation implied a doctrine, differing from that of the text,
and to testify his adherence to the latter.
And in his walk from the meeting,
his tears of sorrow flowed as he continued to expatiate on his mistake;
and he appeared to claim and to need all the consolation
which his attendant could afford him.

Some time before his decease, his faculties gave way;
and his last illness was accompanied at times with violent pain;
but he was preserved in love to all,
and enabled to bear his sufferings with a comfortable degree of patience,
and resignation to the will of God: to whom he frequently prayed,
'`O you fountain of all good, look down upon me if it be your will,
and ease me of my pain.`'
Once he expressed himself after this manner: '`My love is to all,
but especially to the faithful.
Let it be known, I die in peace with all men.`'
One night, before composing himself to rest, he exclaimed, '`Farewell, farewell.
All is peace, peace, peace and joy.`'
These consoling words he again repeated, and then he fell asleep.

His prayer seemed mercifully granted during the two last weeks of his life,
as he was generally much relieved from pain; and he at length departed, full of days,
and full of peace.

[.asterism]
'''
JONATHAN RAINE, of Sunnyside, near Crawshaybooth, Lancashire,
where he had removed from Trawden, departed this life the 27th of the Eleventh month,
1773, aged about seventy-five years.
His parents being members of the Society of Friends,
educated him in the principles of our profession;
but he seems to have neglected in great degree the circumspect
way in which they had endeavored to direct him;
and to have been much infected with the spirit of the world, and the vanities of life.
Thus he seems to have remained until his fortieth year, during which time he married,
had three children, and was deprived of them all, and also of his wife.
His residence was then in the county of Durham.

At length, as his friends relate in their testimony of him,
it pleased the Lord to reveal his righteous judgments
against the transgressing nature in him;
when he stooped to the cross of Christ,
and patiently endured the baptism of the Holy Spirit:
thus becoming qualified for the work to which he was called.
The reader may here truly anticipate,
and conclude that the work in question was gospel ministry;
but let him also be sure that by these means also, and only,
qualification for other services, and for every service, in the Lord`'s house,
must be obtained:
and who is there that will not ultimately wish to be the Lord`'s servant,
seeing that his undeceiving lips have declared, "`Where I am, there shall my servant be.`"

In order to be more fully at liberty to follow the vocation
with which this Friend perceived himself to be called,
he left off business, into which he had engaged when young;
for something of what has been termed '`true moderation`' now bounded his desires.
His first appearance as a minister was about the year 1740.

In the year 1746, he married Margaret Birtwistle, daughter of Henry and Mary Birtwistle,
of Rossendale, Lancashire, and soon after came to reside at Trawden,
within the compass of Marsden monthly meeting; where he was a diligent, zealous,
and exemplary minister, and member of religious society.
He travelled through various parts of Great Britain; and in the year 1760,
was one of a committee appointed by the yearly meeting
to visit the meetings of Friends in Ireland.
He attained to a good old age, and had, in the winding up of his days,
but a short allotment of illness.

About two hours before he breathed his last, having lain still for some time,
he desired to be helped up, and, as nearly as can be remembered, spoke as follows:
'`I want to tell you a little of what has appeared to the view of my mind,
as I was lying and reflecting, that my time seemed to be near the conclusion.
I earnestly breathed to the Great Informer,
that he would be pleased to show me my own state, and how it was with me,
and to forgive all my sins.
And there was shown me some little stones, laid in regular order,
and a path through the middle of them.
The first heap, it was told me, were the sins of my youth;
and they were all passed by and forgiven, for the sake of Christ:
though my sins and backslidings were many.
Yes, there was a time when my trouble and distress were such,
I could have wished that man had died as the beast that perishes,
and that there had been no rewards nor punishments after death.
I could have been content to have been shut up in a dungeon,
never to have seen the light again, if I thereby might have gained peace.
In unutterable condescension it pleased the Lord to break in upon my soul,
as the light of the sun after a long darkness; which so overcame me,
that I believe if an account had been brought me
that all I had in the world had been lost,
it would have given me no concern.
Oh, Friends, you that are young, my desires have been earnest for you,
that you might seek after that which is better than any earthly enjoyment;
and bend your necks to that which is able to yoke down every unruly passion,
and every inordinate desire; that thereby you may obtain everlasting peace.

'`The others that were showed me were all white stones.
There was no dirt upon them.
Though there had been many slips, and many omissions,
yet they were all washed away and remitted.
There remained only one, which was,
that I had been sometimes too thoughtful that the
people might have somewhat spoken to them;
and as that sprung from a good intention, it was also remitted: and then, friends,
the peace, the comfort, and sweetness that I felt was unspeakable.

'`I was desirous to leave this as a legacy with you.
Oh, you that are young, seek after it.
Press after that divine help,
which alone can make you possessors of that peace which the world cannot take away.`'
A little while after this, he perceived his wife to be sorrowing, and said,
'`Do not grieve for me, my dear.
I am quite easy.
I could not have believed a few days since, I could be so resigned,
and willing to be dissolved.
But, oh! the condescension of the Almighty,
and the unutterable love which fills my heart!`'

[.asterism]
'''
SARAH CLARE, was the daughter of Thomas and Hannah Clare, of Warrington,
born there in the year 1759, and was removed the 31st of the Seventh month, 1781.
She was an innocent young woman;
but not noticed for anything particularly striking in her conduct,
till she was visited by the illness which terminated her days.
It was a consumption; and after it became the means of confining her,
was only about ten weeks in performing its office.
She had then entered her twenty-third year,
and from the beginning of her illness she appeared to be resigned,
and often bore testimony to the Lord`'s goodness, and to his tender dealing with her,
in favoring her with his presence,
and the lifting up of the light of his countenance upon her.
In an affecting manner,
she once said `'I am afraid I shall not be able to be thankful
enough for the kindness and goodness of the Lord to me:
and this latter part exceeds all.
I cannot convey to another what I have felt, and the desirable prospect I have in view:
nothing in this world to compare to it.
If I might choose, I had rather die than live;
but I do not wish to go before the right time; but to wait in patience.`'
Patience, indeed, seemed to be the covering of her mind.

On one occasion, she expressed her sorrow in observing,
that so many of our youth were strangers to retirement; saying also, '`I love it,
and the company of solid friends.
But,`' said she, '`if others want to come and see me, if it might instruct them,
or cause them to consider their latter end, I should be glad.
One knows not.
It may be brought to their remembrance in future.`'

At another time, she expressed herself thus: '`I feel quite easy.
Death has no terror.
It is a fine thing to have no will or choice of one`'s own, but to trust in the Lord.
Though my cough seems troublesome, and matter hard to get up,
yet hard things are made easy to me.`'
Indeed, such sweetness attended her mind,
that she seemed as though she were in heaven while on earth.

About an hour before her gentle spirit departed,
she took an affectionate leave of the family, who were present,
thinking she was then about to enter into the rest of God.
She was however again detained for a while, and said, with an audible voice,
'`I have been at the door of heaven.
It was open for me.
I beheld the Almighty sitting on his throne.`'
She also said,
that it was then intimated to her that there was something more for her to do.
Then she embraced her sisters, and with great fervency of mind added,
'`Do come and see how good he is.
Oh, it is a sweet place.
He gathers his lambs in his arms, and carries them in his bosom.
Oh, I could invite all to come and see how good he is.
He is not a hard master.
Praises and glory be to him forever.`'

She afterwards, when her voice faltered, was heard to utter the words Jacob and Israel;
and appearing to be in what may be termed a triumphant melody,
breathing shorter and shorter, she quietly passed away.

[.asterism]
'''
POTTO BROWN, son of John and Sarah Brown, of Earith in Huntingdonshire,
was born there the 16th of Fifth month, 1765.
He discovered, in early youth, a serious and religious turn of mind,
which his tender parents were concerned to cherish; and as he grew up towards manhood,
the seed of the kingdom sprung up in his heart, and gradually increased.
He was a good example to the youth, in his words and actions;
and was beloved by those who had any acquaintance with him, both friends and others.
He left behind him a journal of his life; in which many minute particulars,
and incidents relating to himself and others, are noted;
and from which the following extracts are made:

In a letter addressed to a youth with whom he had formed
an intimate acquaintance at school,
he expresses himself after this manner:

[.embedded-content-document.letter]
--

I hope, as we travel on through this transitory state,
we shall be enabled to cast the cares of this world behind us,
looking to the Author of all good: who will help all those who trust in Him.
I believe, beyond all doubt,
that all those who trust in Him will not lack the bread of life.

--

On the 6th of Eleventh month, 1783, a remarkable occurrence fell to his lot,
which take nearly in his own words: '`This morning, a little after four,
I set off from Ely to go to Ramsey,
to attend the marriage of my cousin Joseph Brown Allen, and Ann Turner.
When meeting was gathered, we sat in silence about half an hour; when Thomas Cox,
of Earith, rose up; and having appeared in public testimony about half an hour, sat down:
about a minute after which he was seized with an apoplectic fit, and expired immediately.
This sudden and awful stroke threw the meeting into confusion.
We gathered again in about a quarter of an hour, when Isaac Gray stood up and spoke.
Soon after he had finished his testimony,
cousin Joseph Brown Allen and Ann Turner were married, and the meeting broke up.

'`In this meeting I was favored with a vision as follows: I held down my head,
and shut my eyes; when lo! to my inward view,
I beheld our Savior coming down in the clouds, in the dress of a country farmer,
with a great coat on.
He stretched forth his right hand toward a man who walked to him;
and took hold of his hand.
This man went with him; and he looked towards me with an eye of concern.
I went as I thought towards him, and took hold of his hand;
but he told me that I could not go till the briers and thorns
were removed which lay between him and me.
This gave me a surprise, and all vanished away.
I then held up my head, and saw Thomas Cox dying.

'`The 9th of the same month Thomas Cox was buried at Earith, but I could not go,
because my foot had been very much strained: so I lay in bed till dinner.
The Lord then showed me, to my great comfort, that my dependency must be on him:
so that I began to inquire how it stood with me and my God.
Then was I humbled to cry, "`Help me, O Lord, or I perish.`"
The word was, "`Draw nigh unto God, and he will draw nigh unto you, indeed.`"
Then began I to meditate on the Lord in the night season,
and was greatly refreshed thereby.
A voice passed through me, saying, "`You must not have any conversation,
but what may profit your soul; for unto that man that orders his conduct aright,
will I show my salvation.
Your mind must be set on heavenly things, and your conversation on heaven.`"`'

In a discourse he had shortly after with his cousin Ann King,
on the subject of what he had seen in the meeting at Ramsey, she said to him,
'`I see the interpretation is plain.
The briers and thorns must be cut up before you can go to heaven.
Keep to the exercises that are within you;`' for I had told her, says he,
'`how it had been with me ever since.`'
'`You have read some books to your hurt, which I advise you in future to avoid.`'
'`These words,`' said he, '`were spoke with such authority,
that I knew full well she was empowered of the Lord.
They ran through my heart like oil, and gave strength and comfort to my soul.
Trust you in the Lord, O my soul; for the Lord loves holiness,
and purity is his delight.`'

The 29th of Eleventh month he wrote after this manner:
'`For the last three days nothing material has occurred; but glory be to our God,
for he has dealt wonderfully with his servant.
I cannot express the comfort I have felt in keeping
to the operation of the word of life in my own heart.
The Lord has showed to me the pure state in which our primitive Friends stood;
and also the fallen state of many among us at this day; which is to be mourned by me.
I hear some American friends are landed, who will come and strengthen those,
to whom it pleases the Lord to manifest his glorious work.
He will not be mocked by men of low degree; who set their minds on earthly enjoyments,
and think not on the name of the Lord.
He has given every man ability to know that he is a just God, who dwells in the heavens;
and those who will serve him must set their minds on heaven;
from which they shall receive their help.
Those who are heavenly shall declare his name to all generations,
to the convincement of thousands, that the Lord is God!
Blessed be his name! says my soul, for taking me by the hand,
and leading me out of the paths of vanity!
May I be enabled to evince, by words and actions,
that in conduct the Lord is to be praised; and honored in stillness.
I hope those who shall see my journal after my decease,
may not think I have written this of myself.
I can honestly say, that the Lord has guided my hand and opened my mouth.

'`The next day I went to Littleport meeting;
where it pleased the Lord to open my mouth in a public manner,
in which I had great satisfaction, in that I had been obedient to the divine will.`'

In answer to a letter he received from his mother,
in which she expresses her great concern for his welfare; he says,
'`The Lord has been pleased to pluck my feet out of the miry clay;
and to open my mouth to make known his will among his people.
I hope it will ever be my care to keep near him,
as I have experienced a drawing near of the Lord to me; my heart is broken and contrited:
blessed be his holy name!
He has showed me the way wherein I am to walk.
O, entreat my brothers from me, to follow after the Lord in purity and holiness,
and to wait for his counsel.
O that I could express the hundredth part of what I feel in being renewed in his counsel;
but I must leave them to the Lord.`'

The 2nd of Twelfth month.
This day a cloud covered me, and a temptation wounded my soul.
I was drawn to consider how the Lord pardoned the thief on the cross,
and to make it a cloak for trusting to a dying hour;
but I felt the rod that chastised me, and heard a voice, saying,
"`How camest you to take thought against your God?
He will not be slighted, but looked unto with a single heart, for all help.

The 11th. I found that, during my late journey, while my mind was turned inward,
then was his presence with me; I was preserved in the truth, to my inexpressible comfort.
O may I always keep watch, lest the enemy draw my mind from being stayed on the Lord.

The 17th. Many are the temptations which the enemy lays to draw my mind from the Lord;
but, look you, O my soul, to the Lord with unfeigned sincerity,
and with full purpose of heart,
in the humility of that spirit which enlightens you
and strengthens you against them all.

The 4th of the First month, 1784.
In the course of a visit I lately made to my parents,
two of my relations opened their minds to me, concerning my public appearances,
wishing I might be favored to support the honor of the blessed truth;
which was done in so affecting a manner, that it helped and strengthened me much.
This day I went to Littleport meeting, where I spoke a few words.
Oh, how I felt the Lord with me this day; blessed be his name!
Many were the breathings of my soul at times,
that the Lord would keep his fear always before my eyes, that I might not speak a word,
but to his honor.
Oh, that it was the case of all those who profess with us,
that nothing might be done but to the glory of God: that we may say,
"`Yours is the kingdom, the power and the glory, forever!`"
Then should we answer our high and holy calling.

The 15th of the Second month.
I never used to write concerning my spiritual welfare
till I was in a right frame of mind,
under the influence of the power of truth.
From the 19th of last month I have known a going backwards, as from Jerusalem to Jericho;
but the hand of God was not shortened:
but he has made me know that I must be obedient to him.

The 17th. This day, in my retired thoughts,
I was made sensible how much we ought to keep ourselves in humble reverence to our God,
under a consideration of his omniscience and our nothingness.
Oh, if people would but behold their dependency on Him,
they would be afraid of having their minds taken from under his protection;
much more of doing any thing that would not tend to his glory; but, on the other hand,
they would testify against everything of a contrary tendency;
knowing that God is jealous of his honor,
and will be sought unto with fear and trembling.
David says (Ps. lxxvi.), "`You, even you, are to be feared,
and who may stand in your sight when once you are angry.

The 19th. This day was a day of hard labor to me, because I was off my guard last night,
by entering into a long and needless discourse, which drew my mind from the Lord;
but he was good to me, and heard me when I cried,
for my spirit was bowed down in humility before him,
and heavenly joy abounded when I confessed my error to him.
This is an evil which many of our Society fall into,
even those who have been religiously inclined.
(See Book of Extracts, on the head of Conduct and Conversation.)

The 25th. I have this day oftentimes felt a refreshing power, with a secret promise that,
if I kept under the guidance of the power of truth,
I should not do any thing to dishonor it,
for a fear arose in me that I did things that were not an honor to it.
A voice was in me, "`Humble yourself, and you shall be favored.`"
I have felt a service in keeping a journal, as it helped to keep me from going back;
encouraged me in seeing how I was favored before,
and what progress I had made in the truth.
What pleasure has it given me to write of my progress heavenwards!
On the contrary, what lashes have I felt, when I was not in a frame to write!
When I had walked obedient to his power, he always gave me a frame to write.

The 27th. Last First-day, I wrote to a Friend concerning our serving burials,
which I saw, in a clear light, was not consistent with us as a people; because,
when we serve a burial, it is to gratify the pomp and vanity of the people of the world,
which is a plain contradiction to that Spirit which we profess to be guided by.

The 8th of Third month.
This day I had a concern to speak to a Friend concerning gaping in meeting,
and on another subject.
He was very high in his expressions; but, finding that I spoke according to the Spirit,
he was silent, for truth will always prevail.

The 9th. This day, being alone, I read my journal over to the Second month,
which helped me to see how I followed after God,
who called me to be more and more humbled.
Oh, I felt his goodness to flow towards me!

The 18th. I saw I could not be in such a humble state as I had been called
to come into without I became as clay in the hands of the Great Potter.
I saw that my body was to be the temple of the Holy Spirit,
and that no defiling thought must lodge within me.

The 21st. I went to our meeting at Ely,
and many were the refreshings that my mind there felt.
I saw that the Spirit of Christ was the only way that leads to celestial bliss,
and that he teaches his followers to be humble as he was humble;
that we must not barely believe that he came down among men,
in a body prepared for him, but must also believe in his power,
that leads to life eternal.
Be still, O my soul, and you will find his power made manifest in you.

The 16th of Fourth month.
I find that the more I give up my mind to seek after the kingdom of God and his righteousness,
the more I advance in the work; the more I keep in the power, the stronger I grow.
My soul longs for the living God; yes, my inward cry is raised for the bread of life,
more than the natural man hungers after natural food.
Here ends the journal of this pious young man.

About this time his health began to decline,
and some symptoms appeared that seemed to threaten a consumption;
he was therefore removed from his master`'s to his father`'s house,
that he might try his native air and the effects of medicines;
but the disorder baffled both.
In the latter part of his illness, he was remarkably patient under his bodily affliction,
which was long and sharp; those who assisted in his illness,
said they never saw any one bear so great pain with so much patience.
A little before he was confined to his chamber, his mother, who was helping him to bed,
found he grew weaker, and said to him, '`Potto,
do you not think you are grown weaker within these few days?`'
He answered with as much cheerfulness as if he had been in health, '`Yes, I know I am;
but what matter?
If the outward man grows weaker, the inward man grows stronger;
I experience the strengthening of the new man every day.`'

Another time, being very sick and in great pain, he said he could not bear too much,
mentioning how much Christ bore for him;
but his mother could not expressly remember his words.
One day his father, sitting by his bedside, and observing him appear dull,
asked him if he was any way uneasy about his future state.
He said, No; for he had many comfortable assurances it would be well with him.
He then burst into tears, and said he was uneasy for his brothers,
fearing they might be drawn from the truth.
His father desired him not to make himself uneasy about them;
for there was the same divine hand to guide them, which guided him;
and if they adhered to it, it would do the same for them.

A few days before his departure, a friend from Ely came to see him,
and asked him how he did.
He said he was very ill, but did not wish to live,
nor did he think it his place to pray for death.
The night before his departure, he said to the woman that sat up with him,
'`Go tell my mother that I am very bad, and think she would like to be here.`'
When she came to him, he told her he was a great deal worse;
but he desired that she would not be troubled at his change,
which he expected would be soon.
He uttered many more sweet expressions, which cannot be remembered,
and departed this life the 16th of Tenth month, 1784, aged nineteen years.

The following was found in his pocket-book, after his decease,
giving an account how he spent his time, while ill at home.
Eighth month, 13th. 7 to 8, reading; 8 to 9, walking; 9 to 10, writing; 10 to 11,
retirement; 11 to 12, walking; 12 to 1, dinner; 1 to 2, walking; 2 to 3, reading; 3 to 4,
writing; 4 to 5, walking; 5 to 6, reading; 6 to 7, retirement.

[.asterism]
'''
TABITHA MARRIOT was the daughter of Richard and Susannah Ecroyd,
of Marsden in Lancashire, and was born in the year 1724.
She was enabled early to bend to the visitations of the grace of the Lord,
and by this means had discernment and strength to avoid
the vanities and dangers to which many appear prone.
As she advanced in the path of righteousness) many deep
baptisms and conflicts of spirit fell to her lot,
which she endured with patience,
until she was reduced to a resignation of will that
resembled the clay passive in the hand of the potter.
Thus she was prepared as a vessel fit for the Lord`'s service, in which,
as a gospel minister, she first publicly engaged in the twenty-sixth year of her age.
"`The Lord,`' said she, in a week-day meeting, '`is good to his people;
especially to those who are desirous above all things to be conformable to his will.`'
The declarations of our ministers are called testimonies.
This appears to be truly a testimony.
She bore witness of what she felt.

She was soon concerned to visit Friends in their meetings.
Her first visit in this religious service was in Cumberland,
in company with her beloved elder friend, both as a woman and a minister,
Sarah Taylor of Manchester, of whom there is an account in the ninth part of this work.
She continued frequently to be engaged in this service for about eight years, when,
in the year 1758, she was married to Richard Marriot, of Mansfield in Nottinghamshire,
and went to reside there.
In about two years, however,
they came and settled in the compass of Marsden monthly meeting.
The confinement incident to an increasing family sometimes kept her at home;
yet she still continued to travel in the service of truth,
visited various parts of this nation,
and was often engaged in visiting the families of Friends.
She was esteemed a deeply baptized and powerful gospel minister;
her deportment in the exercise of her gift was grave and comely,
and her expression clear;
and in supplication she appeared to be at times favored
with near access to the throne of grace.

In private life she was an example of meekness and lowliness of heart,
and filled up its various relations with great propriety.
Towards the close of her days she was tried with deep affliction;
but she was enabled not only to support it with becoming resignation and fortitude,
but at times so far to be borne above it,
as even to be much enlarged in her gift of public ministry.
She seemed to aspire after total resignation to the will of the Lord,
in all the dispensations of his providence to her.
She once said to a beloved friend, alluding to the probations of her latter life,
'`The cup that is handed to me, shall I not drink it without repining?`'
and in her last public testimony, she had to declare of the goodness of her Lord.

About the beginning of the Sixth month, 1786, she became ill of a slow fever, and,
on the 15th, she was found by a relation who visited her,
so weak as scarcely to be able to speak audibly.
Yet the same day she revived, and finding her children and some other relations together,
after a time of silence, she addressed them to this import:
'`I have felt so strong a desire for your good, that I must have been weak indeed,
could I not have got down stairs to express it to you.
I have been led to look at the state of our meeting;
and as many of the elders are removed,
I wish you weightily to consider what is in your power to do for the Lord.
Oh! how ardent is the desire of my heart, that you may do nothing against the truth,
but for the truth!
My heart has been humbled in the recollection of the goodness of the Almighty to me,
from my very early years,
in that he gave me his good Spirit to check and reprove me when I had done amiss;
and I am thankful that the Lord inclined my heart to turn at his reproofs,
to receive his corrections, because I had sinned against him.
I regret that I have not made this divine law my more frequent study;
yet this I can say of a truth, I have loved it;
and indeed it has been a lamp unto my feet, and a light unto my path.
I have loved to meet the Lord, and to wait upon him, even in the way of his judgments;
and may now say, though I know not how this weakness may end, I never before,
in the course of my life, have been so continually favored as of late;
never before had such unclouded prospects of that holy habitation,
where all sorrows and tears shall be wiped away.`'

After this opportunity, in which more was uttered than is here set down,
she continued in a feeble state for some weeks;
and then seemed to gain a little strength;
but her disorder returned about the 20th of the Eighth month,
and was attended with considerable lethargy.
Nevertheless, when awake, she was clear in her understanding,
and aware of her approaching close.
On the 4th of the Ninth month, as she was sitting up, she said,
'`Oh that I had wings like a dove, that I might fly away and be at rest:
'`and after she was put in bed, she spoke to this effect: '`I resign myself, my children,
and the church, into the hands of a merciful Creator, who is worthy of high hallelujahs,
and eternal praise, both now and forevermore!
Amen.`'

Her last recorded expression was on the following day, a prayer for the church.
'`O,`' said she, '`most gracious Father,
be pleased to look down with an eye of tender compassion upon your poor afflicted seed.`'
Two days after, on the 7th, she quietly departed.

[.asterism]
'''
ANN NAISH, daughter of Joseph and Betty Naish, of Congersbury,
a village in Somersetshire, about twelve miles from Bristol,
was born about the Third month, 1773.
From her childhood she was of a serious deportment,
and of a calm and condescending temper,
even in cases where her youthful inclination might be opposed:
so that the salutary directions of her parents were readily obeyed.
Her understanding appeared, at least to keep pace with her age, if not to surpass it;
and her steady care to please those who had the charge of her education,
endeared her to them; as her kind, affable,
and obliging behavior gained her the love of her associates.

This promising maid was called in her bloom from the vicissitudes of time.
While she was at boarding-school at Milverton,
not very far advanced in her fifteenth year, she was taken ill.
Her disorder, water in the head, soon affected the part with violent pain,
and was not long in producing frequent delirium, and sometimes convulsions.
She was, however, allowed many intermissions, and clear intervals of reason;
in one of which, a friend asked her, whether she were willing to go.
She replied, that she was willing to leave it to the Almighty;
that at some times she could not desire any thing;
but at others she had desired then to go.

It was a week before her affectionate father saw her;
and he too availed himself of her undisturbed intervals
to apprize her of the uncertainty of her recovery.
She repeatedly expressed, in very satisfactory terms,
her resignation and acquiescence with the will of the Almighty, often saying,
'`I am not afraid to die.`'
At one time she spoke to her father thus: '`Dear father, you have been a tender,
affectionate father to me.
Have I not been a dutiful daughter to you?`'
He answered fully in the affirmative; and she went on, '`Oh,
I would not have been otherwise for all the world!`' There
was at that time some little article of her apparel,
which by some means had been introduced, and which her father thought not consistent.
He gently remarked it to her; and she freely acknowledged it was wrong; saying,
that it proceeded from pride, and that those who kept near to the principle,
+++[+++the Spirit of Truth,]
would be preserved out of such things.

Her gratitude to those about her,
especially to those who were more immediately employed in
the various offices of assistance which her illness required,
seemed to be almost unbounded: and her patience, her serenity,
and the innocence and sweetness of her spirit, brought to mind the words of the Redeemer,
"`Of such is the kingdom of heaven.`"
She departed, after two weeks`' illness, the 4th of the Seventh month, 1787.

[.asterism]
'''
MARGARET GREENWOOD was the daughter of Thomas and Bridget Greenwood,
of Greenwood-haugh in Dent, a district in Yorkshire,
on the confines of Westmoreland and Lancashire.
Her father occupied a small estate,
which till lately was about the yearly value of eighteen pounds.
On this small farm, which, together with knitting, was their sole means of subsistence,
they brought up five children.
These, when at home, as they generally were, and not engaged in the business of the farm,
were employed in knitting, by which they could earn a little money.
Margaret lived constantly with her parents;
for she was afflicted at times from her youth, with an acute rheumatism,
which rendered her incapable of much active exertion.
This had a tendency to temper the natural vivacity of her disposition,
and to render her the more susceptible of religious impressions.
A few years before her death she was much devoted to the promotion of piety,
and was often concerned to notice and to reprove what she saw to be reprehensible,
either in those of her own, or any other society.

About her twenty-seventh year she came forth in the ministry; and her ministry,
as well as her innocent life and conduct, was acceptable to Friends.
A short time before her decease, she went to Dent Town,
in order to warn a vicious and ferocious man of the consequence of his conduct.
It was supposed that she would meet with insult, and rough usage; but he was softened,
and even received her meekly; and she returned in peace.

She had been engaged in order for marriage,
and the day was agreed to be the same on which her sister also was to be married.
Each suitor had the name of John.
One morning early, their father said to the two sisters, pleasantly,
that he supposed they would not give up their Johns for any consideration whatever.
Margaret replied, after a pause, that there was one thing, and but one,
for which she would give up her John: a place in the kingdom of heaven.

She appeared at that time to be free from indisposition; but about ten in the forenoon,
as she sat employed in her knitting, she breathed her last.
The preceding day she had attended the general meeting at Dent Town,
and had borne a lively and weighty testimony;
and as a meeting was held at the same place six days afterward, on account of her burial,
the minds of the people were impressed in an extraordinary manner.
Her remarkable answer and decease were on the 22nd of the Twelfth month, 1787.

[.asterism]
'''
JANE FRYER, of Warrington, Lancashire, daughter of Benjamin and Margaret Fryer,
was born at Kendal, in Westmoreland, in the year 1761.
From an early age she was religiously disposed.
Her mother died when.she was very young,
in consequence of which a considerable care devolved upon her, who was the eldest child.
She afterwards went to be an assistant in the family of a friend at Bristol,
where she was much beloved for uprightness and integrity,
and where she evinced much care and interest for the welfare and preservation of children.
This benevolent and beneficial temper of mind was
the means of inducing her to open a school at Warrington,
to which town she had removed.
Here, also,
she was greatly esteemed by those who united with her in religious profession,
as well as by others who entrusted her with the care of their children:
an employment for which she seemed to be particularly well qualified.
Nor did she teach by precept alone; her example, as a religious character, was salutary;
and on both accounts her loss was much lamented.

Her great concern for the welfare of youth remained
with her in her declining state of bodily health.
She said, '`If my being afflicted might but furnish instruction to our young women,
I should be glad.
I have been very desirous their minds might be weaned
and brought from the exteriors that are about them.
Oh, what vanity they will feel them when such a time as this comes.
My mind has been exercised on their account as I have sat in our meetings.
I have longed that they might experience the work of real religion;
but things have felt so low,
that something of an alarming nature must come to rouse them;
and that language has been sounded in mine ear, "`Cry aloud, and spare not;
lift up your voice like a trumpet;`" but, alas! who is sufficient for these things?
I was but a child.`'

At another time she signified that, being favored with great calmness,
and her mind covered with universal good will,
she was induced to wonder at so general attachment
in her fellow-mortals to sublunary things.

Once, when two friends were with her, she said, '`Oh,
may I have patience to wait the Lord`'s time, without offending him in being over-anxious.
Let us unite together in desiring I may be preserved
in perfect resignation to his holy will.`'
After a short pause of silence, she was engaged in prayer, thus: '`O, dearest Lord,
Almighty Savior, if you will, condescend to favor your poor, unworthy,
afflicted child with the lifting up of the light
of your countenance --who am deeply tried.
But you know best, O Father, what is best for us,
and necessary that we should pass through, in order to fit us for your glorious kingdom;
where nothing that is impure or unholy can ever enter.
Therefore, I beseech you, dearest Lord, let not your hand spare, nor your eye pity,
till you have made me perfect.
Then I hope to be dissolved, poor dust and ashes, and clothed with angel`'s raiment.
O, permit me to join them in praises and thanksgiving.
My will, you know, has been subservient to yours; and I have endeavored,
according to my small ability, even from a child, not to offend you, O my God.
Therefore,
I beg of you to permit the guardian angel of your presence
to conduct my poor soul to its everlasting rest:
believing, if I offend you not, there is one prepared for me,
where I may forever ascribe praises to your holy name.`'

A little after, she desired her friends to pray for her,
telling them it was a trying season, and that she was sometimes ready to say,
'`Why am I thus prolonged?`'
adding, '`You, O Lord, know for what end, and your time is ever best.
Oh, that I may be favored with your divine presence!
That will make up all.`'

At another time she said, '`My mind enjoys great quietness.
Oh, the kindness and condescension of the Almighty to
me!`' She said also to the friends mentioned above,
'`I love you,
and desire that our spirits may unite together in
worshipping Him who can kill and make alive.
I have had today sweetly to feel,
like a foretaste of that peace which I humbly hope to partake of soon,
without interruption.`'
One of her visitors remarking,
that she believed all doubting would be done away before the final removal of Jane,
the latter replied,
'`I have thought so today;`' and then she broke forth in praising her Redeemer.
She also expressed her desire of a release, in the words of the Psalmist: "`Oh,
that I had wings like a dove!
Then could I fly away, and be at rest.`" '`I lie lingering,`' she added,
'`just on the brink of eternity.
What an awful situation!
But as the clay to the potter, who dares say, What do you?
When a child, I loved retirement --and such awfulness attended my mind,
though I had no language to utter, nor knew what it meant;
yet I dared not disobey these tender sensations;
and I believe the Almighty owned these seasons,
and opened my understanding in early years.
I have been desirous not willfully to offend him; and have had many hidden exercises,
remembering it was said, "`In the world you shall have trouble;
but in me peace:`" which brought great sweetness over my mind.`'

'`Blessed forever be his name!`' Soon after,
as she was lying in great composure and serenity of mind,
she left the toils of mortality, in the twenty-seventh year of her age.
Her decease was on the 22nd of the Eighth month, 1788.
