== Chapter 10

[.chapter-synopsis]
* Lydia Hawksworth
* Sarah Grubb
* George and Jeremiah Waring
* Fidelity Hull
* Daniel Bowly

LYDIA HAWKSWORTH, of Bristol, was the daughter of Samuel and Deborah Waring, of Alton,
in Hampshire, and born there about the year 1733.
She departed this life in London, at the age of fifty-five.
Her mind had been early visited with impressions of the love of God,
and as she kept under its influence, she advanced in the just man`'s path,
and was exemplary to others.
Having thus by example been in degree a preacher of righteousness,
she at length believed herself required to bear a verbal testimony to the Lord`'s cause.

In the spring of the year 1768, when she was about thirty-five years of age,
she was married to Abraham Richard Hawksworth, of Bristol,
a Friend who had lately become signal for a remarkable change in conduct;
for having turned from the spirit and manners of the world, to bow to the yoke of Christ.
But their union, so far as death can dissolve the tie, was of short duration.
He died in the course of the same year.
A meeting was held in Friends`' meeting-house in Bristol,
on the occasion of his interment; and his widow, standing up,
and laying her hand on the coffin which contained the remains of her beloved partner,
bore her first public testimony, with weight and clearness; and,
there is reason to believe, with no small effect on the meeting.
Having thus devoted herself to a service for which she had long been under preparation,
she continued exercised in spirit, and humbly waiting for the renewals of power;
by which, in time, she was made an able minister of the gospel.
She was esteemed to be sound in doctrine, clear in spiritual judgment,
and cautious not to be more in show than in substance.
She was a lover of retirement, and in it often, through deep conflict of spirit,
was enabled to grow in the root.
At various times she visited the meetings of Friends
in most of the counties of Great Britain,
once those of Ireland, and was also a diligent attender of meetings for discipline.

Towards the close of her life she was tried with great affliction of body, by illness;
and to all human apprehension, the lamp of life, as herself expressed it,
was just extinguished.
At this time she dictated to a friend some things
which engaged the attention of her mind;
among which were the following advice and observations.

'`Let ministers be careful not to judge too highly of any of their services:
for it is only when the breath of the Lord blows through the trumpet,
that life and harmony are known, and the great truth is evinced,
that it is only his own works that praise him, or benefit the churches:
nothing that man can do.
In most places, the elders need to stand deeper in Jordan.
A more unreserved, total sacrifice of the world must be made,
and even the accursed thing cast out of some of their tents,
before they can stand as valiants for the Lord`'s cause upon earth.
Every shekel of pure gold in the sanctuary ever had, and still must have,
the signature of HOLINESS upon it: for what is of man is but man: the Lord blows upon it,
and lo, it is nothing, however specious in the eyes of man.`'

'`I see clearly that when the ancient simplicity and purity are known again among us,
then the glory of the Lord will appear as in former years;
and his praise sound forth through all the churches.
Therefore, under the fresh flowings of gospel love,
I salute my beloved friends everywhere, and bid them farewell in the Lord.`'

Her last illness was long and painful;
but she was enabled to support it with patience and resignation.
She often experienced her cup to overflow with divine love;
and often administered pertinently to the states of those who visited her.
To a near relation, she expressed herself after this manner: '`Don`'t mourn for me.
I have a comfortable hope that my heavenly Father will receive me into his kingdom.`'

On the 17th of the Twelfth month, 1788, she departed, as has been said, in London,
and her remains were deposited, where she first drew her breath, at Alton.

[.asterism]
'''

SARAH GRUBB, wife of Robert Grubb, of Clonmel in Ireland,
was daughter of William and Elizabeth Tuke of York,
and born there the 20th of the Sixth month, 1756.
When she was very young she was deprived of her mother;
but about the tenth year of her age she became the care of her father`'s second wife,
Esther Tuke, of whom there is an account in this volume, whose tenderness,
and whose solicitude for her increase in things which belong to salvation,
she has frequently confessed.
The care extended in her education had its natural effect:
it was the means of preserving her from many dangers incident to youth.
Nevertheless, the vivacity of her disposition,
and her propensity to withstand that which was connected with self-denial,
occasioned many a struggle,
before she fully submitted to follow the Lord without reserve.

About the age of sixteen it was her lot occasionally to wait upon that eminent minister,
John Woolman, in his last illness;
and his example of resignation and faith made a deep impression on her mind.
To her it was that he said, '`My child, you seems very kind to me, a poor creature.
The Lord will reward you for it.`'

In the twenty-third year of her age, she first appeared as a minister;
for which service she had undergone no small preparation,
and had passed through deep conflict.
Her first appearance was in prayer,
and some of her attendant feelings she thus describes: After enduring,
on a First-day morning, a state of agony till the meeting separated,
she attended that in the afternoon like one deserted; yet, contrary to her expectation,
the matter returned; and, assisted by a seasonable testimony from a ministering friend,
'`I ventured,`' says she, '`on my knees; and in a manner I believe scarcely intelligible,
poured out a few petitions.
Now I feel in such a state of humiliation and fear, as I never before experienced.`'

There is something peculiarly touching to what I
trust are the better feelings of the awakened mind,
when we observe this dedication of the faculties in the prime of youth; when, as it were,
the first fruits of the increase are offered to the Lord; and when,
through the various stages of holy preparation,
the soul is at length conducted to a public confession of his power and goodness.
In the harmony of the divine economy, there is no place for emulation and envy;
but I have often thought this period of open dedication in our visited and called youth,
to be eminently sweet, and deserving of our admiration and love.

Sarah Grubb travelled much.
She first accompanied her mother into Westmoreland and Cumberland;
and in the same year joined another relation in a religious visit in Cheshire and Lancashire.
Other services succeeded, during the time she remained single,
and was a part of her father`'s family.

In the year 1782, she married Robert Grubb, who had sometime lived at York,
and they settled at Foston, a village about ten miles from that city.
Soon after her marriage, she visited Friends in Scotland and Cumberland,
and some other places, in company with Mary Proud, then of Hull.
From this time, she was frequently engaged in traveling in the exercise of her gift:
particularly she accompanied Rebecca Jones, of Philadelphia,
in a visit to Friends of Ireland.
In 1787, she settled with her husband at Clonmel, in that nation.
The following year, she joined several other friends in a visit to some parts of Holland,
Germany, and France; and on her return from this journey,
she was instrumental in establishing a boarding-school for girls,
the children of friends, near Clonmel; of which, when at home,
she had the superintendence.

I pass over her other services in these kingdoms,
and hasten to relate her last undertaking, which was another visit to the continent.
Her husband and George Dillwyn, of America, with the wife of the latter,
were her companions in this journey, as they had been in the former one;
and they left London soon after the yearly meeting, 1790.
They sailed for Dunkirk, where at that time several Friends resided,
and proceeded through Holland.
At Amsterdam, she was tried by a separation from her husband,
who thought himself obliged to return home, to assist his brother and partner,
then considered to be near his end.

From Holland, the remaining company went by way of Munster, to Pyrmont,
where several resided who appeared much separated from the common forms of worship,
and were seeking after substance.
Of this sort they found others at Rintelm and Minden.
I shall trespass on my proposed brevity, to mention a blind woman,
who walked to the latter place seventeen miles to meet them.
She spun for a living, and her friends occasionally assisted her.
The visitors asked her if she were not straitened in this respect.
She replied, that she knew she was poor; but that when the question arose in her mind,
"`Do you lack anything?`"
the acknowledgment always succeeded, "`Nothing, Lord.`"
O, that not any professor of the Christian name would ever fix his desires upon riches.
Here we see it exemplified, that "`Godliness with contentment is great gain,
having the promise of the life that now is, and of that which is to come.`"

They next went to Buer, Osnaburgh, and Herwerden,
(so much mentioned by William Penn,) and by Bielfeld, where they stayed some days,
and through some other places, back to Munster; and were afterwards at Crevelt,
Dusseldorf, and Mulheim, a town near Cologne.
Here Sarah drew up and signed a letter, addressed to Leopold,
then having lately acquired the crown of Hungary,
to which letter her companions added also their names.
It is as follows:

[.embedded-content-document.letter]
--

[.salutation]
To Leopold the Second, King of Hungary, Bohemia, etc.

Among the numerous congratulations awaiting your accession to the imperial crown,
accept, O king, our Christian good wishes,
and solicitude for your present and eternal wellbeing.

We are conscious that we have no claim to the liberty of addressing you,
but from a belief that the Lord Almighty, who rules in the kingdoms of men,
and gives them to whomsoever he will,
has inclined us to leave our habitations to visit some parts of this country,
and now engages us, in gospel love, to express our secret and united prayer,
that you may be an instrument in his holy hand for the advancement of that glorious day,
spoken of by the prophet, "`when swords shall be beaten into plowshares;
and spears into pruning-hooks; when nation shall not lift up sword against nation,
neither shall they learn war any more.`"

The great design of our universal Parent,
in sending his beloved Son a light into the world,
is for his own glory in the salvation of mankind; and for this gracious end,
he has given to all men a measure of his own eternal Spirit.
To cooperate with him herein, dignifies human nature,
and is particularly deserving the most scrupulous attention of princes.
The smallest revelation of this heavenly gift in the believing soul,
having a degree of omnipotence in it,
brings into subjection the natural will and wisdom of man,
and discovers to us the noble purposes of our creation.
It diffuses that true benevolence which characterizes genuine Christianity,
and renders dear to a prince the happiness of all, even the meanest of his subjects;
imprinting upon his mind the superior value of an immortal soul,
to all worldly acquisitions.

Through the neglect of a principle so pure and important,
how has the rational part of God`'s creation been
sacrificed to the irregular passions of sovereigns,
and many unprepared souls precipitated into an awful futurity!
That the gospel dispensation is intended to remedy these evils,
and promote the government of the Prince of Peace;
that the Gentiles are to come to its light, and kings to the brightness of its arising,
are truths to which the sacred records abundantly testify.

May this be your happy experience,
O king! that so the power you are providentially entrusted with,
being subservient to divine wisdom,
your example may influence the minds of other princes, who also beholding its excellency,
may unite in encouraging their subjects to decline, in mutual charity and forbearance,
whatever is contrary to the purity and simplicity of the religion of Jesus.
And may you be enriched with all spiritual blessings; that these,
added to your temporal ones, may not only perfect your happiness,
but perpetuate it beyond the narrow limits of time, and qualify you, acceptably,
to cast down your crown at the feet of Him who is King of kings and Lord of lords;
who lives and reigns forever and ever.

[.signed-section-signature]
George and Sarah Dillwyn, Of Burlington, New Jersey, North America.

[.signed-section-signature]
Sarah Grubb, Clonmel, Ireland.

[.signed-section-signature]
Joshua Beale, Cork, Ireland

[.postscript]
Members of the religious Society of Friends in those countries and Great Britain,
commonly called Quakers.

[.signed-section-context-close]
Mulheim on the Rhine, 29th of 9th Mo., called September, 1790.

--

Soon after this she returned to England, visited her relations in the North,
and reached her home at Clonmel the 12th of the Eleventh month,
greatly exhausted in bodily strength.

Passing a night at Ackworth, on her way from York, with a near and beloved relation,
she thus expressed herself: '`O, my dear!
I think sometimes that I shall soon be gone.
It seems as if my day`'s work was nearly done, and on looking towards home,
as if I might not be long there.`'

On her way to Clonmel, she was at the national meeting of Friends in Ireland,
held at Dublin.
In a sitting of the meeting of ministers and elders,
she gave some account of the journey from which she was then returning.
In doing this, humility seemed to be the covering of her spirit.
'`We have done little,`' said she,
'`but the Lord is doing much;`' and her concluding
words were a humble adoption of those of the Psalmist,
"`Return unto your rest, O my soul, for the Lord has dealt bountifully with you.`"
These are from Psalm 116, a psalm well worth the perusal of the mind conflicted,
and yet hoping in the mercy of the Lord.

Soon after her return, she attended the quarterly meeting at Cork,
where also she gave a humble account of her late journey.
At the close of the meeting she was taken ill,
and was confined at the house of Samuel Neale.
In a message to a young woman who then presided at the school at Clonmel, she said,
'`Salute her very affectionately:
tell her I have been much favored with quietness of mind from the first,
though a stranger to how the present afflictions or trials may terminate;
but the grain of faith and hope which is mercifully vouchsafed,
I esteem preferable to all knowledge.`'

Four days before her close, she dictated a letter to a particular friend,
in which are the following expressions: '`My soul,
though encompassed with the manifold infirmities of a very afflicted tabernacle,
can feelingly worship, and rejoice in nothing more than this,
that the Lamb immaculate is still redeeming, by his precious blood, out of every nation,
kindred, tongue, and people, and making a glorious addition to the church triumphant,
whose names will stand eternally recorded in the book of life.
I express not these things from a redundancy of heavenly virtue,
but from a soul-sustaining evidence, that, amidst all our weakness,
and conflicts of flesh or spirit, an interest is mercifully granted in Him,
who gives victory over death, hell, and the grave.`'
Nearly the last words which she spoke, were those of that cheering passage of holy writ,
where the Savior of men thus addresses his disciples: "`My peace I give unto you.`"

Thus, on the 8th of the Twelfth month, 1790, she finished a course comparatively short,
but filled with deeds of dedication.
Her natural turn of mind, as has been related,
subjected her to deep baptisms and close conflicts;
but grace had so fully effected the work of renovation,
that the observer saw little in her but the unaffected, unassuming, simple,
humble and resigned Christian.

[.asterism]
'''

JEREMIAH WARING, who died at the advanced age of seventy-five, at Thorpe, in Surry,
had been for a long time well known in our religious Society,
especially to such Friends as attended the yearly meeting, at which, for fifty years,
he was nearly constant.
He was the son of Samuel and Eleanor Waring, of Witney, Oxfordshire,
and born there in the year 1716; but, his father removing to Alton, Hampshire,
on his second marriage, he passed his childhood under the care of his grandfather,
Jeremiah Waring, a valuable ministering Friend,
of whom there is an account in the Seventh Part of this work, by John Bell.
Of his father and mother-in-law, Samuel and Deborah Waring,
there are accounts in Thomas Wagstaffe`'s Ninth Part.

Jeremiah, the subject of this memoir,
appears to have been of exemplary conduct from a child.
He was very assisting to his parents in bringing
up a numerous family by the second marriage,
and in the management of their trade; but,
having a competence for his own limited desires,
he never embarked in trade on his own account.
He devoted his talents and time to the service of others,
and particularly to that of the Society of Friends,
and his leisure hours to reading and retirement.
He took great delight in reading the Scriptures, in which, accordingly,
he was very conversant; and he was accustomed, when a young man,
after the avocations of the day, to walk out, like Isaac, into the fields,
and meditate at eventide`' in the law that he loved.
He was hospitable to his friends, and compassionate to the poor;
and his benevolence was not confined to merit.
He used to say, '`Did we receive no more than we deserve, how little should we possess.`'

He was twice married.
His first wife was Barbara, the widow of Daniel Pack, of Alton; his second, Mary,
widow of Daniel Weston, of Ratcliffe.
On occasion of the latter marriage, he removed to reside at Wandsworth, in Surry;
but their union was of short duration.
Of Mary Waring, there is an account in Thomas Wagstaffe`'s Eighth Part.
He continued to reside at Wandsworth until, in the wane of life,
and as infirmities approached, he went to reside with his only daughter and child,
the offspring of the former marriage, at Thorpe-Lee, in the same county,
where his days were closed.

In the summer of 1790, after a journey to Ackworth, his constitution began to decline;
and, though the decay was almost imperceptible to his constant attendants,
it was firmly impressed on his own mind,
that he should not be restored to his accustomed health.
He would say, after taking a medicine, '`This will not do; and nothing will do long.
I am persuaded this illness is intended for my end.`'
At other times he would say, '`I am tired of the doctors.
Physicians can do me no good.
There is but one Physician: the Physician of value.`'
Thus he gently declined for eight months;
but then the advance of dissolution was accelerated,
and for the succeeding three months his ailments made a rapid progress.
His appetite and digestion failed, and he became weaker daily.
He frequently took notice of these symptoms of decay, and would remark,
'`It is a mercy that I can look on approaching dissolution without terror.`'
Yet it does not appear that he had then received
that full assurance which his soul desired;
for he said once, '`Could I have an evidence that I might be admitted to a place of rest,
it would matter not how soon.
Oh, what a glorious change would that be, from a state of pain and sickness!`'

After various fruitless attempts to relieve him, he was, with reluctance,
prevailed on to consult an additional physician;
but he earnestly pressed the first who had attended him,
to say whether he had any hope of his recovery.
Perceiving a hesitation on the part of the medical man, he repeated his question, adding,
'`Don`'t be afraid to tell me, doctor: I can bear it.`'
One day, after suffering considerable pain, he said, '`I am resigned, I think pretty much,
as to life or death.
Your will be done.`'

He had been, as has been hinted,
particularly attentive to the concerns of our religious Society;
but within a week of his close, he told an intimate friend,
and some of his near relations, who were with him,
that he feared he had not been so useful in the Society as he might have been; and,
continued he, with tears, '`I have ever loved the cause; and I wish all those whom I love,
to be more circumspect than I have been.`'
He used to converse pleasantly with his friends who visited him;
but when he was alone with his daughter, he would frequently say,
'`I want to be more inward.`'

A few days before his death he said, '`I have, at times, a hope,
He that has been my morning light will be my evening song.`'
Soon after saying this, he told a Friend who called to inquire how he did,
that he '`thought he might then reasonably expect every day to be his last:`'
and he always spoke of his great change with perfect composure.
The morning preceding his departure, he said, '`I have lived to see the light of this day,
but I scarcely think I shall ever see another.`'
About seven, he sent for his daughter, and said to her, '`I believe I am going.`'
Seeing her distressed, he added, '`No, don`'t distress yourself.
We must part; but I leave you in the hands of a merciful Creator.`'
His daughter said that she had hoped the separation would not so soon have taken place;
to which he replied, '`We know not what is best.
Times and seasons are in the disposal of unerring wisdom.
If he sees this the right time, it is so, and we must submit.`'

Soon after, he was desirous of rising, and while he was assisted in dressing, he said,
'`I long to be clothed with the white linen, the righteousness of saints.`'
In the evening, when retired to rest, he said, '`All my trust is in Infinite mercy.`'
Soon after, some of his relations being in his chamber,
he took an affectionate leave of them, having first said, as nearly as can be remembered,
thus: '`I am going where the wicked cease from troubling, and the weary are at rest.
I feel that goodness and mercy which have been with me at times all my life long,
to be near me now; and, though I have fallen into many frailties incident to my nature,
have never entirely forsaken me: and I have a secret hope that all will be well.
The Lamb and his followers shall have the victory:
those who have come through many tribulations,
and known their garments to be made white in the blood of the lamb, the immaculate Lamb.
May the God, who, I trust I may say, has been mine, and my father`'s,
and my grandfather`'s also, be the God of all present.`'

Within a short time of his close, he desired to be left with his daughter only;
to whom he gave directions respecting his interment, and some other matters;
particularly,
that he might be affectionately remembered to such
of his relations as might incline to attend it.
Soon after this, he said, '`I die in charity with all the world, and have now, I think,
nothing more to wish for, but an easy passage.`'
This, at midnight, was allowed to him, when,
finishing his course with the 2nd of the Tenth month, 1791, he departed without a sigh.

[.asterism]
'''

FIDELITY HULL, of Uxbridge, Middlesex, was the daughter of Thomas and Elizabeth Stark,
of Fordingbridge, in Hampshire.
In her early years,
she was in some degree inclined to indulge herself in a
deviation from the simplicity of her religious profession,
which deviation her more corrected judgment afterwards disapproved;
yet not by any means in such a degree as is usually termed gay or extravagant.
About the twentieth year of her age she was married to Samuel Hull, of Uxbridge,
and became the mother of two children, whom, however, she did not live to educate:
for she soon showed symptoms of a decline, that terminated in her dissolution.

Early in her illness,
her heart became more and more disposed to seek for the knowledge of the Lord;
and when her disease gained ground, she entertained much doubt of recovery;
yet she said that she should not mind the leaving of this world,
if she had an assurance of happiness hereafter.

She now saw the vanity of indulging in dress; also the pernicious tendency,
to young people, of reading novels, and similar productions.
Pernicious indeed is this practice.
Simply considered, it is a waste of time.
Relatively, it indisposes the mind for the serious concerns of real life;
and for its truest, greatest concern, the preparation for a better,
through the grace and redemption of Jesus Christ, our Lord.
Her anxiety on this account was manifested by a letter which she wrote to a relation;
in which she entreated her, that if she had any such books,
they might be destroyed for the sake of her children.
Similar advice she also left in writing,
for such as might have committed to them the care of her own son and daughter.

A few months before her decease, a Friend called to visit her;
and believed it right to address her with a few words of encouragement.
She was, at that time, preserved in a good degree of resignation;
though she had not yet that full assurance of happiness which she had longed for.
Nevertheless, at the time, his words were particularly consoling;
and in a subsequent opportunity,
he was made instrumental of more complete relief to her much tried mind.
She broke out as it were in rapture, '`Why does the Lord deal thus bountifully with me,
a poor sinful creature, undeserving the least of his mercies?
What is this I feel?
You have healed me of all my maladies, both inwardly and outwardly.
O my Lord, and my God, how sweet is your presence!
What shall I render unto you, O my God?
Oh! this is what I wanted.
Now I am happy.
I thank you, O Lord: for you indeed are good.`'

She then paused; but soon she turned her eyes affectionately on her mother, saying,
'`You have no need to sorrow for me, for it will be well with me.`'
Nor was this merely a sudden perception of unexpected relief,
and a transient effusion of joy.
The next day she told some visitors of her favored state,
and expressed herself in a very tender manner.
'`The Lord,`' said she, '`is good.
Yesterday was a memorable day to me.
I think I shall never forget it.
My bonds are unloosed.
There is balm in Gilead.
I feel more sweetness than I can express in words.`'
She also expressed her hope that her visiting friends could feel something of the same;
and she entreated her husband to give her up freely.

But although her consolation was thus great, and at one time, as we have seen,
so transcendent as to supersede her sense of bodily infirmity and pain;
her disease advanced, and her consequent suffering was often felt and acknowledged,
though not repined at.
To her brother, once she said, '`My tribulation is great.
Oh, how careful we had need to be,
to make the Lord our friend! for if I did not feel him near, I could not support +++[+++myself]
under this great affliction.`'
Nevertheless, she had a word of encouragement to most of those who visited her,
and she often exclaimed that God is love; and that those who dwell in him,
dwell in love.

She had once an opportunity of conference with two Friends.
I am not informed whether they were Friends in the ministry,
though there is room to suppose it.
They were encouraging her not to withhold anything she might have to communicate to them.
Making a pause, she replied to this effect: '`I cannot speak unless power is given to me.
I have felt at this season much stripped,
and expect to be tried with the buffetings of Satan.
What can I say to the Lord`'s servants; but that they should hold on their way,
and they will experience peace and joy forevermore.`'

Various admonitory and encouraging remarks were written
or uttered in the course of her illness.
She told some of her relations by letter,
that if they could feel the peace which she felt,
they would leave all the transitory enjoyments of this world, to endeavor after it.
She often earnestly desired those about her to keep near to the Almighty,
and said that he would do great things for them.
Once she said, '`It is clearly presented to my view,
that the gates of heaven are open to receive me.`'
She frequently remarked,
that the peace and comfort of her mind overbalanced her
very great bodily afflictions and infirmities.

Once, when some of her relations returned from meeting, she addressed them thus:
'`I hope you have had a comfortable opportunity together;`' and she remarked,
that though for some time she had been prevented from going to meeting,
yet she was often comforted by the divine presence.
At another time when some friends were present, she expressed herself after this manner,
'`Your will be done: not mine.
It is better to go to the house of mourning than to the house of mirth.
Oh, that we may be favored to feel good from the tree of life!
Perhaps we may see the sun arise in all his glory: which is glorious indeed,
to those who view it in its spiritual appearance.`'
O Lord, be pleased to hear us, for we have great need of your supporting presence.
Give us to sing praises to your great and glorious name forever and forever more.
Amen!`'

About three days before she departed, being so weak as scarcely to be able to speak,
she sent for her husband`'s father, Thomas Hull, a valuable Friend, who lived in the town.
Several others of her relations came with him, to see her; in which visit,
after a solemn pause, she was raised in a wonderful manner in praises and prayer,
to the Almighty; and gave such good admonitions to those around her,
as were the means of greatly humbling and contriting their minds.

She departed at length in great peace, the 15th of the Third month, 1792,
about the twenty-third year of her age.
A large meeting was held at her interment, in which a ministering Friend, (Thomas Cash,
of whom there is an account in this volume,) from a distant part of England,
being present, mentioned in his testimony, the sweet,
heavenly frame of mind in which he had found her,
and the satisfaction which he had felt in being with
her about eight hours before her decease.

[.asterism]
'''

DANIEL BOWLY, jun., son of Daniel and Sarah Bowly of Cirencester, Gloucestershire,
was a young man possessed of a good understanding, and an amiable disposition;
the pliability of which,
together with an employment which frequently exposed him to temptation, promoted,
though it did not sanction,
a wide deviation in conduct from those religious principles in which he had been educated.
Of this deviation he became fully sensible in the course of a long illness;
which he often acknowledged to be a mercy from that divine Providence,
whose fatherly care had many times preserved him from sudden death when unprepared.

In the commencement of the disorder, which proved a consumption,
his mind appeared to be deeply affected with the danger of his situation,
though he then expressed but little of his feelings.
As his weakness increased,
he remarked how exceedingly awful the prospect of the final change appeared;
and he earnestly desired that he might know a fitness for eternity,
and that when the time came, the divine presence might be near.
His past conduct, he said, had been very erroneous;
but that his supplication for forgiveness had, in his illness,
been attended with such sweet refreshment,
that he hoped it might be according to his desires.
At other times,
his sins appeared so great that he could hardly entertain
a hope it would be well with him.
'`What can be expected,`' said he, '`from a deathbed repentance?
That is a time when all would gladly be saved.
There will not probably be an opportunity given me of proving my sincerity,
by an amendment of life; so that men may doubt it;
but the omniscient Being knows how far I am sincere, and I hope, if it really be so,
it will be accepted by Him:
yet there is nothing equal to a proper dedication of time in health.`'

Another time, he said, '`I hope the Almighty will forgive my sins.
It is mercy alone that can save me, who have devoted so much of my life to business,
and the amusements of this world; pleasure, as it is generally called;
but it is a strange sort of pleasure.
It is pain, I feel it pain.`'

In another opportunity, he said, '`What I have to deliver,
is from a prospect of the awfulness of death, which in a short time will be my lot.
Mankind in general are certainly under strong delusion;
yet how kindly the Almighty condescends, from time to time,
to give a degree of his light and help!
But man may outlive this day of grace, which,
through the merciful mediation of my dear Savior, is now extended to me.`'

At another season, appearing much distressed,
he desired his sister to read a chapter in the Bible to him;
after which he broke forth in earnest and pathetic exhortation to those present,
to prepare while time and health were afforded; saying, that a little encouragement,
during the reading, had been given for himself;
and that he believed it was for some one present he had been so tried; adding,
'`I long that my friends would begin the work of religion in the life of it,
for if the first offers are slighted, oh! how does the visitation deaden on the mind!
It appears to me as though my own redemption is now nearly completed,
and that I may be detained here for the good of others;
and I hope if there be anything to be done, the Almighty will enable me to do it.`'

He also said,
'`How comfortable would it be to meet my relations in that state of happiness,
where I believe a residence to be preparing for my soul!
I believe the Almighty detains me here as an example of his great mercy,
and as a warning to some;
but I earnestly entreat none will depend upon the same singular act of mercy.
All the friendships of this world must be given up; and,
if the mind be not illuminated with an immediate proof of the presence of our dear Savior,
yet it should be resigned, and prepare itself for the reception thereof,
by a surrender of everything which does not appear
consistent with a state of preparation.`'

One time, speaking of trade, and that he seemed glad he had done with it, he said,
'`I hope I am not hardened or insensible of my state.
I have earnestly supplicated for repentance,
and have sometimes experienced something like touching the hem of the garment;
but not quite so neither, as that was fully efficacious; but this lasted only for a time,
and I seemed again left.
In the forepart of my illness, a few times I asked for recovery,
if consistent with the divine will;
with desires to be strengthened to lead a different life from my past;
and to serve that good master whose doctrines I have, as it were, trampled under foot;
but I have since seen the favor it may be to me to be taken from such a trial.`'

He said also, '`What a favor it is to be members of our Society!
Its rules forbid nothing that is good for us.
How earnestly do I wish my near connections, in particular, may keep to the truth!
Though the path may appear hard at first,
yet as they follow their Leader with a single eye, it will become more easy.
There may be times of withdrawing of the divine presence,
and then the enemy will seek to enter: but by earnest supplication,
preservation will be granted, and at times a comforting foretaste of future happiness;
and the prospect of getting every day nearer to such an incomprehensible reward,
is a favor beyond expression.

'`How little satisfaction results from a life of pleasure, attending places of diversion, etc.
Ah, the disappointments such meet with!
I believe bitter portions are often their lot.`'
He observed how he had been struck, when at those places of amusement,
with a conviction that he was far more blamable than his companions,
who had not so guarded an education; that, however innocently some of them attended,
it was not so with him.

Embracing one of his brothers with great tenderness,
he desired him to attend to what he had said, which was not in his own will; but,
he believed, through the Spirit of Christ,
who in his unspeakable mercy had made of him such an example.
He exhorted his brother and sister to endeavor to
train up their children in the right way;
as it is from the rising generation an advancement in society is to be expected.
He remarked the many memorable instances in '`Piety Promoted`'
of children from nine years old to fifteen and twenty,
appearing in public testimony in meetings; and he said,
he thought the care of children a great trust; but that the reward would be answerable,
if rightly discharged.
He recommended beginning with them as soon as their minds opened;
and not plunging them into business at too early an age;
and he remarked the great preference due to religion before earthly substance.

One morning, inquiring if it were not the meeting-day to morrow,
and being answered in the affirmative, he said, '`I almost long to go.
How pleasant is the thought of being retired there from the world,
when the generality of the people are in the height of its engagements!`'
How foolish and unwise are men who are bartering their souls for gold,
paltry gold!
The too eager pursuit of it is a great hurt to some of our Society.
If I were to recover, and found business stood in my way to peace of mind,
I think I would give it up entirely; or do but little, and live accordingly.
What signifies grandeur or curious food?
The taste goes no farther than the mouth, then it is over.
If some men heard me talk thus, they would think me foolish; but in this I am wise,
and know what I say.`'

He advised young men not to spend their time unnecessarily at inns,
but rather to go to friends`' houses, where he thought they would be welcome.
He had, he said, thought otherwise; but that in the liberty he then felt,
he could go to any friend`'s house.`'

'`I believe,`' said he, '`the hope which I have, will continue with me to the end;
yet the enemy is very busy,
and would persuade me I have nothing to do with the kingdom of rest;
but that is his temptation, and I must pray for patience;
for I think the prospects I have had from time to time cannot be delusion.`'

A friend asking him how he did, he replied, '`I am very weak,
but I hope I shall be willing to bear everything
the Almighty may be pleased to lay upon me,
so that I can but just get within the gates of peace.`'
At another time, he said, '`I wish I had served my dear Savior in my health.
Oh he is a kind master.
How much time have I lost! how distressing must be the situation
of those who are sleeping the sleep of death,
until the last trumpet be sounded in their ears!`'

Several friends being in his chamber, one evening,
he spoke of that wonderful gift dispensed to all,
even that Holy Spirit which manifests our duty;
and he recommended an immediate compliance with its discoveries;
'`For since`' said he '`these illuminations are not at our command,
it is very unsafe to trifle with them, by giving way to the suggestions of the enemy;
but rather resign whatever may be called for;`' adding,
'`Can we not return a part to Him who gave the whole?
What if it deprive us of a few luxuries?
We can have but food and raiment;
which only differ a little in kind between rich and poor.`'

He recommended, that after being at meeting,
and having been favored there with tender impressions of good, as he sometimes had been,
great care should be taken not to lose them, by too soon entering into conversation,
concerns of business, or attention to anything of a contrary nature,
whereby the mind might be deprived of the benefit intended.

'`Our profession,`' said he, '`is a very exalted one; and if we keep to it,
would make us as lights in the world.
Our religion teaches us to believe in immediate communication with God,
through his beloved Son; which is an unspeakable privilege to all who attend to it: and,
wonderful condescension! that he who is Lord of all, should thus notice poor man; and,
time after time, be visiting with the offers of his mercy to insure our happiness;
visitations we should be very careful not to reject, as being a common favor,
and think we will accept them at some future time.
For, though the Almighty is long-forbearing and delights in mercy,
we know not when may be the last offer of his grace to assist us in the work of salvation.
What a dreadful thing would it be to withstand the last!`'

Speaking of the evidence he had of his future peace, he said,
'`I have a clear view that I shall be received into the kingdom of rest and peace.
I see the gates of heaven standing open to receive me,
and thousands of the just waiting to embrace me.
I desire but just to get within the pales of safety, to be in the presence of the Lord,
and to behold his glorious countenance.
"`O! death, where is your sting?
O! grave, where is your victory?`"
Christ takes away the sting of death.
My dear Savior is reconciled to me.
I know he is.
His mercy is very great.
I cannot speak enough of his mercy.`'

Some one remarking how exceedingly quick the last three weeks had apparently passed away,
he replied, '`Yes, and perhaps there are some who have not done anything in the time,
which is a serious consideration: for in one week a man may be taken sick and die;
and if we do not close in with the visitations of God in time,
we shall be lost forever.`'

At another time,
'`Let us be earnest in making ready for the glorious kingdom of rest and peace, where, Oh,
that we may enter!
And all may, if they will.
Let us endeavor to do a little every day; let none be discouraged,
though their progress in religion may be slow; yet let them keep on in their little way:
for I believe our kind Savior may, at times,
withdraw his sensible presence from us to try how our faith will continue;
yet if we hold on, our reward, at last, will be great,
and as much as those who feel a present one.`'

On the 9th of the Eighth month, his sisters, who lived at a distance, came;
at which he much rejoiced, having often expressed a desire to see them again.
The next morning he affectionately addressed them,
desiring they would be particularly careful of the cultivation of their children`'s minds;
and not make business the first object for their sons; a very little being sufficient,
and that great portions were by no means desirable.
In much weighty advice to those present,
he wished them to make an offering of all they had.
Particularizing one of his sisters, he also said, '`What your conscience tells you,
that mind; and what is told you to put on, that wear; and what is told you to give up,
give.
Fear not the great or rich, but be alike to all.

'`Be religious, and then you will have our Savior`'s arm to lean upon.
Oh, he is a merciful Savior!
I have found him such; an easy master, a kind friend.
Ah! how I regret that I neglected serving him some years.
Think what a superior education we have had, to most;
what a nice institution is ours-the peculiar institution of God;
and I believe it is not to die away, although some of our Society have gone from it,
for whom I am sorry.

'`I believe great advantage may arise from frequently comparing time with eternity,
an awful eternity.
It appears to me exceedingly awful.
Heaven and hell are placed before us.
We have now our choice; and we know what wretches hell is composed of; foul minds,
full of remorse forever; for their worm never dies.
On the other hand, in heaven there is great harmony.
Oh, I have had beautiful prospects!
I have seen the innumerable company of angels, and the spirits of good men!
But how is it?
We are ashamed of not complying with man, and not ashamed of doing so to God.
We can apologize to man and say, we are sorry we did not do so, or so,
and we can directly go, commit neglect before God, and feel no sorrow for it.
Oh, what mercy there is!
In great wisdom and unspeakable kindness is the good Mediator given to reconcile us,
and work redemption in us.
Do not let us fear man.
What is he?
Look upon me, and see a poor weak thing who can hardly speak.`'

After this earnest exhortation to those,
for whose eternal happiness he was so affectionately and deeply solicitous,
he was much exhausted, and, desiring to be put to bed,
uttered the following short prayer; `'Oh, Lord God Almighty,
be pleased to look down upon, and be with us!`' With some difficulty he got to bed;
and for several hours his cough and other symptoms were very alarming,
and were thought to indicate approaching dissolution; but after having slept some time,
he took some refreshment, and said he must now endeavor to say a few words more,
as he might not have another opportunity.
Most of his near relations being present, he called particularly to one of his sisters,
requesting her to sit near him, that she might hear what he had to deliver;
and he was wonderfully strengthened to testify with power to the truth;
beautifully setting forth the means of salvation appointed for all.

Some of his relations standing by his bedside one evening,
he remarked how contemptible the world appeared; and speaking of its wickedness,
he added, '`I would not be understood to despise the world itself.
No; it is the creation of God;
and we are placed there to enjoy all things with temperance.
If it were as it ought to be, it would be a sort of paradise;
it would be a happy pilgrimage to eternity;
it is the depravity of man that makes it so detestable.`'

He cautioned some of his friends to beware of the fatigues and encumbrances of business,
saying,
'`It will not do for those who have been all the week
in the hurry of business to go to meetings,
and appear before the Lord in form only.
A man whose time is wholly engrossed in business in common,
if he goes to meetings pretty constantly, and sits there two hours,
yet it is to be feared his thoughts will be engaged
on that which takes up the greater part of his time;
and if it be so, it is great mockery of God.
Neither will it do to go on in an outward show of dress or address,
if not true worshippers of the Lord, in spirit and in truth.
They must daily give up their minds to him, daily retire to worship him.
I know a man ought to provide for his family, and carry on a proper business,
which I believe to be right; but it should by no means be the first object,
for riches will be nothing in the end.
What would I give now for all the world?
Why nothing at all.

'`I don`'t regard what the natural man may advance in opposition
to this doctrine of giving up all for the sake of religion.
I am now upon the brink of death to the body, but opening into the life of the spirit.
I am going to live forever,
and I am certain nothing will do but giving up every
earthly obstruction for the cause of God.
Make him a sacrifice; offer up all you have; offer up your lives to him,
as Christ did his for your sakes and mine.
Perhaps some may, from the strength of health and abilities,
be ready to conclude what I say proceeds from weakness.
I know it does not, but that it is the truth, and you will all find it so;
and that man who trusts to the strength of his own mind, or natural understanding,
will be wrong, for nothing will do without God.
Now, remember this; think of it upon your deathbed, and you will feel it is true.
So farewell in Christ.`'

The 12th of the Eighth month, addressing one of his sisters, he said, '`Sister,
how many times have I been preserved from death, times more than I can remember!
Ah, how often, sister, have some of us been raised, as it were, from death!
We should often think of it, and how we have answered the kind intention.
It may not be so again.
The next may be the last time.
Then do let us begin to prepare and do everything that is required of us.
I believe plainness of dress is.
We are indeed a chosen people, and what may not be wrong in others is so in us.
Plainness of dress is as a hedge about us.
The world is not then seeking our company.
Do remember what our Savior said, "`Whosoever denies me before men,
him will I also deny before my Father who is in heaven.`"`'

At another time he said, '`I should be distracted if, on this deathbed,
with all this pain and weakness of body, I had my sins before me.
What horror should I feel!`'

A Friend expressing a desire to help him, he replied,
'`None can help me essentially but my dear Savior: he can release me,
if it be his blessed will.`'

He advised one of his relations to bring up her children in a plain way; knowing,
from experience,
what a disagreeable situation those were in who accommodated themselves to their company.
'`This,`' said he, '`will not do.`'
He believed the easy way chosen by many of our Society
had as little religion in it as any,
or less, and was highly displeasing to the Almighty.
He also recommended a single line of conduct.
He often spoke of the benefit of retirement,
and said that other things must be given up to gain it.
He wished not to be interrupted during meeting time; for, although not able to go,
he loved to compose himself, when the nature of his complaints would admit of it,
and was often favored with great stillness at those times.

He impressively said, '`The enemy is still very busy with his insinuations,
and would persuade me that all is done, and so lead to neglect;
but I must watch and pray to the end,
and be very earnest with the Almighty to continue his favors,
and that he will support through all.`'

For some time he was much proved with poverty of spirit, added to great bodily weakness;
but his desires were for patience, saying,
'`It is very trying to bear such great lowness and sinking of body and mind.
What can I do, but endeavor patiently to bear it, looking constantly to the Almighty?`'
Some one asking him how he was, he answered, '`I am very low,
but I keep mine eye upon God.`'

His sister, having sat up with him, remarking how comfortable a night he had passed,
he said, with much sweetness, '`Yes, I prayed for a little respite,
and it has been granted me.`'
About this time his strength recruited so much, for a few days,
that the possibility of a recovery was hinted to him.
This at first seemed almost more than he could bear; but after a pause he said,
'`In this also I will endeavor to seek after resignation, and keep mine eye to my Savior;
who, I ardently hope, will now take me,
having in kind mercy so prepared me for my change.
Can it be, after the near prospect that I have had, that I shall enter life again?
I must endeavor, earnestly endeavor, after patience.`'

Some hours after, being asked how he did, his reply was, '`I feel myself quite resigned.
I have supplicated for patience, and I hope I shall be contented to live,
if it be the Lord`'s will.
I know he can preserve and keep me.
Indeed I have experienced such resignation,
that I think I could feel a pleasure in living, that I might bear my cross in the world.`'
He was indeed preserved in a very patient, waiting, frame of mind,
and expressed but little for several days; but his company was truly pleasant,
and his deportment evinced where his mind was centered;
though he said the enemy was so busy, tempting him to doubt,
that he had hard struggles at times to keep his faith.

The effort of nature, upon which the intimation of recovery was grounded, again subsided;
his cough became more troublesome, and increasing weakness was evident.
He remarked, '`I believe I was too anxious to go, a little time since;
but now I feel willing to wait the Lord`'s time for the end.
I have reason to hope my disorder is making its progress.`'

He was naturally of a compassionate disposition; and, during his illness,
often spoke feelingly of the poor, recommending liberality to them; which, he said,
he had seen to be a Christian duty;
and how much greater satisfaction would result from relieving their needs,
than from unnecessarily accumulating wealth.

About the end of the Eighth month,
he was strongly impressed with a belief that some
one of his relations would be removed before him;
and in a day or two after, an account came that one of his aunts,
who had been for a long time in a poor state of health, was very unexpectedly deceased.
When this was mentioned to him, referring to the above intimation,
he said he thought he should now be soon released.

On the 1st of Ninth month, he said,
'`The state that I expect to enter is that of calmness and peace: divine peace,
the purest spirituality.
When I have spoken of gates or doors, I wished to imply an entrance into this state;
for I believe my ideas of future happiness are not gross.
I hope to live in the presence of God, and to feel constant support from him;
and I do not wish to know more.`'

The next day he was very weak, and reluctantly left his chamber.
Some hours after, he was seized with a violent fit of coughing,
so that the hour of separation seemed, both to himself and friends, fast approaching;
and, in a short respite from the cough, he expressed triumphantly, '`I am happy,
I am happy!
If I never speak more, give my dear love in Christ Jesus to all my friends.`'
After being relieved, by bringing up the phlegm, he was put to bed,
and some time after remarked,
'`Death is awful! very awful! but I have full faith in my foundation.`'

At another time he said, '`I believe my dear Savior is ready to receive me,
figuratively speaking, into his arms; that is into purity;
and I believe that is what all good minds desire to enter into.`'
He desired he might not be disturbed when he was thought to be going;
and hoped he should have an easy passage, and that he might go off in a sweet sleep.`'
He said, '`I have earnestly prayed for you.
Do you pray for me.`'
Shortly after, observing his friends affected, he said,
'`It is not from a callous disposition or hardness of heart,
that I appear unmoved at parting with all my near, dear, and beloved relations.
It is the advantage I shall reap myself, that is my support;
and knowing there is a powerful visitation extended to you,
so that you may all gain an admittance, and soon be in the same place with me.`'

In the evening some one remarking how exceedingly hard it rained, he said,
'`I like to hear it; the sound of it is solemn, being the work of the Almighty.
The withdrawing of the sun, and darkness,
is like what good souls experience in the work of redemption;
when divine light is withdrawn from them, and the damps of melancholy felt.
In these seasons what strange ideas is the mind tried with;
such as are very apt to cast down timid minds; but there is a secret support sustains,
though at such times not sensibly felt.`'

On the 3rd he expressed an earnest desire for an easy passage,
making solemn supplication, as follows, '`O, Lord God Almighty! have pity upon me.
It was you who created both soul and body.`'
Some time after, to a near friend, he said,
'`I believe the enemy has now almost done with me.`'

On the 4th he was very weak, but still and composed.
He said, he was going to the Father and the Son; and, looking on his friends,
bade them farewell.
A short time after, he remarked that he felt such an entire resignation that,
if it were the Lord`'s will, he was willing, even now, to recover or die;
and how comfortable it was to be thus favored to the end.
About twelve o`'clock he took an endearing leave of
two of his cousins who had tenderly waited upon him;
soon after which, a considerable alteration was apparent,
and his voice was become so weak that little could be understood;
but he continued in a heavenly frame of mind, full of love.

The last connected sentence which was distinctly heard,
was as a seal to the foregoing truths, being this: '`I have the satisfaction to say,
I have been washed in Jordan.`'

Not long after this, he appeared to be retiring to sleep; but the fact was,
that he was quietly departing;
which he did in the manner for which he had so often prayed, without a groan,
or even a sigh.

His corpse was interred on the 11th of the Ninth month, 1793,
in Friends`' graveyard at Cirencester.
Aged twenty-five years and eight months.
