== Chapter 11

[.chapter-synopsis]
* Elizabeth Rathbone
* Esther Tuke
* William Prideaux
* Sophia Pope
* Sarah Crawley
* Mary Bass
* Samuel Emlen

ELIZABETH RATHBONE, daughter of William and Rachel Rathbone, of Liverpool,
was born the 15th of the Fourth month, 1756,
and was removed by a decline the 30th of the Ninth month, 1793.
Her mother died when she was little more than four years of age.
Her father, on whose own education not much pains had been bestowed,
was so sensible of his loss,
that he determined to give his own children as good a one as could be obtained,
within the limitations which should always bound
a religious parent in his conduct to his children.
Desirable accomplishments may be purchased at too dear a rate;
and when the acquisition of them really interferes with the more important learning--the
learning of him who is meek and lowly of heart--it is time for the Christian parent,
at least, to be closely on his watch.
Thus limited, her father saw the advantage of mental acquirements;
and his paternal care was repaid by the acuteness and diligence of his daughter.

She quickly imbibed instruction, and was so fond of being taught,
that she was often held up as an example by those who instructed her.
Her disposition was lively and volatile;
yet she was not observed to make any wide deviation from the simplicity of her profession.
This, however, was rather owing to the watchful care of her pious father,
than to her own self-restraint.
Without that, there is reason to fear that she would have wandered far astray.
For, notwithstanding her youth was so carefully guarded,
she admitted many things to a share of her regard, which,
when she was fully awakened to a sense of her spiritual state,
she found it her duty to resign.
One of her great amusements was reading,
and her reading was far from being confined to profitable books.
In the choice, too, of her associates,
she sometimes loved to be among such as rather led her away from the path of self-denial,
than assisted her to enter and pursue it:
and it is probable that in such company she was a welcome visitor.
A good understanding, well informed, added to the vivacity of youth,
and to a temper desirous of pleasing, is generally received with applause;
but there are few who possess these accomplishments, in whom the consciousness of talent,
and the praise of others, do not occasion a secret self-approbation, bordering on pride.

About her seventeenth year, her mind became impressed with serious thought;
and she found that a narrower way than that in which she had been accustomed to indulge,
was the path to peace.
She said to her much beloved sister one day, after having been in some gay company,
'`This kind of visiting I must resign.
I do not know how it may be with you,
but at such times I exert all my powers in such a manner, to accommodate myself,
to appear agreeable, that when I return and reflect, I find I have given all out,
but I take nothing in.`'
Her father, of course, would express his disapprobation of time thus spent,
and said that he saw in it a snare.
She acknowledged that he was right, and soon began to alter her course.
She yielded to one impression of duty after another,
until in a few years she became a very religious character; and,
as the influence she had with many of the younger class was great, a very useful one.
The sequel will show that she had learned to say, I am an unprofitable servant.

She remained for about twenty years a much esteemed member of our religious Society,
but often endured great depression, and even conflict of spirit; not only from the sense,
with which her mind was touched, of the state, the low state of the church;
but from frequent apprehensions that she might be
called to minister to its needs by a public testimony.
Her last illness was lingering.
It afforded ample time for retrospect,
and for application of heart to Him who can supply
every need of his humble and dependent children;
and she was mercifully enabled to avail herself of the opportunity.

In the forepart of her confinement she was deeply tried
with the desertion of that good in which she had delighted,
and with painful apprehensions that her day`'s work,
when weighed in the balance of the sanctuary, would be found lacking.
Her conflicts were great; she dwelt much in retirement,
and was very cautious of relating to others what her soul was passing through.
But about three months before her decease,
she found freedom to open her mind to her sister, her most intimate friend.
She confessed that if she had erred, it had not been for lack of knowledge;
but that a full portion of divine light had been granted to her.
'`I now see,`' said she,
'`it is an awful thing to be found carefully acting in conformity to it.
By this light, in my early years, my understanding has been often opened,
not only to see clearly into my own state, but also into the states of others;
some of whom I seem clear of; and this I count a favor.
My bodily weakness is such, from complicated causes, that I should find it difficult,
if now required of me, to obtain relief.`'

Speaking of some of her social duties, she said,
'`Ah! had I served my Maker with as much faithfulness
and dedication as I have performed these,
I might have looked forward, in this awful time, with confidence.
Yet, I think I dare tell you, I feel my faith so strong,
and so indubitably fixed in the merits and intercession of a crucified Savior,
that my mind is wonderfully supported and stayed in quiet composure,
having an evidence mercifully vouchsafed that some of my
transgressions are blotted out from the Lamb`'s book,
but that this is granted of his own free mercy.
If I had not the most unshaken belief in the gracious Mediator,
I know not what I should do now; but yet I feel I have still to pass,
as through the river of judgment.
I have labored to cast all my care upon Him,
through that help which he has administered.`'

On a certain occasion she was sending a message to her brother`'s wife,
and delivered it nearly thus: '`You may give my love to my sister,
and tell her I should be glad to see her,
as soon as her condition will render it prudent.
And you may also tell her that my mind is so centered in deep, inward quiet,
that I feel resigned and weaned.
Oh, that I could give her an idea of what I now enjoy in this state!
Were ten thousand worlds offered, I would not accept them in exchange for it,
nor change this bed of sickness for the most prosperous
condition that could be placed in my view.
No human help that could be administered would be adequate to what I now feel.
All is made up in this deep inward quiet.`'

Some weeks after this,
when she had been conversing with her sister respecting
her secret conflicts of later years,
and expressing her faith that her multiple transgressions were washed away, she added,
'`I think I have seen, more particularly of late,
that the state of the church triumphant is not more glorified
than the members of the church militant would be,
at seasons, if they had faith to believe, and in the exercise of this faith,
carefully occupied, in deep abasement, with their several gifts.
How precious would be their fellowship!
How would they participate with purified spirits in union and communion!
Oh, how I long that those in the ministry would keep their places!
Then indeed, I do believe,
they and all the living members of the mystical body would know,
in a much larger degree than they do, a partaking together of the glorified state.
But then, '`she faintly and movingly added,
'`I know it is difficult to believe this possible, while engaged in conflict and dismay;
especially when we remember the manifold infirmities which encompass us,
during our continuance in these shackles of mortality.`'

On the 24th of the Ninth month, which did not precede her departure one week,
she made an effort to clasp in her arms her sister, who was then sitting by her;
and she said, in a very moving manner, and with a flood of tears, '`O, my sister,
how have I desired that your mind and mine may be strengthened in the
hour that is approaching!`' In this she alluded to her dissolution.`'
If I dared have asked for it, for your sake my language would have been,
"`If it be possible, let this cup pass from me;`" but I dare not: for how do I know,
if my life was given at my request, what might afterwards follow; what flaw,
or what stain I might contract.`'

The following day, when her sister, who had sat up with her a part of the night,
was about to take her leave, Elizabeth, looking at her tenderly, said, '`O,
my dear sister, your distress moves me, though it appears very endearing.
But let my confidence be your stay,
because the arm that is underneath is worthy to be trusted in.
It is worthy, for it will be found sufficient.
I feel that I dare lean upon it.
It has been my support; and be satisfied that this dispensation is all in wisdom.
I have seen it clearly;
and if the help which has hitherto been mercifully afforded do but continue,
I trust I shall be able to take the cup with resignation,
and keep in patience to the end.
But, if ever, through the pain of the body, I should let drop an impatient expression,
do you deal faithfully with me, and be sure to tell me of it;
for on this head I have many fears.`'

She was much distressed with difficulty of breathing; and on one occasion,
when her sister, who had been endeavoring to give her some assistance, said to her,
'`What shall I do for you?
I do not know how you support these sore nights;`' she replied, with great sweetness,
but very emphatically, '`Oh, they are mixed with constant goodness-constant goodness.`'

In the morning of the 27th,
she said several things respecting the children of her brother and sister Benson,
and respecting the close and intimate union which
she and her sister had been favored with.
'`Oh,`' said she, '`how I wish that your dear Abigail and Rachel may be thus united!
Press it upon their minds.
It is a point of importance for children of the same parents,
to cultivate a tender regard and sympathy with each other.
It is difficult for the best chosen friends to enter so intimately into the varied
circumstances and difficulties that attend our allotments in life,
as two sisters who seek to have the divine cement,
to strengthen the natural bond of union.
My early friendships were carried too far,
and on this account a weight of condemnation ensued;
for I found that I had been planting heavens of my own, and earths of my own;
and when the day of the Lord came, which burns like an oven,
I saw all these pleasant pictures were to be destroyed.`'

To her sister`'s husband, she said thus:
'`As to the intimations of encouragement which I have received from man,
that my spirit was already a pure spirit, I have never been permitted to build upon,
or draw consolation from them; but in the deepest and darkest plunges I have had,
unworthy, totally unworthy as I have felt myself,
and all I had to hope for was divine mercy, my faith has not failed,
that he who said to the leper, "`I will,
be clean,`" was able to render me fit to associate with saints and angels,
and the spirits of the just already made perfect.
I can now freely mention,
that if I had been perfectly obedient to the vocation wherewith I was called,
I was intended to have filled up a different station in the church,
from what I have done.
Whether my life might thereby have been prolonged or not, is hid from me;
but if in this I have erred, I hope it is washed away.
Though I have sometimes looked at the separation of the
spirit from the body with fear and apprehension;
yet it is now wholly taken away.
My last two nights have been sweet nights.
Death has lost all its terrors, and I feel the grave will have no victory over me.`'

A few nights previous to her departure, she often spoke of her father,
as she had frequently done before, in very affecting terms.
She said that she was satisfied that his spirit was sweetly centered in celestial regions;
that she had often been permitted to hold sweet communion with it; and added, '`Ah!
I feel he is gathered.`'

About eleven o`'clock on Seventh-day morning, the 28th,
she was seized with a very strong spasm; and believing herself about to depart,
she desired that her sister and her husband might be called.
After they came to her, the convulsive affection abated,
and she desired to be placed in a chair.
Being there, she said, '`Indeed, my dear sister, my sufferings are very great.
Let me request you to endeavor to reconcile your mind,
'`to her sufferings doubtless she meant, '`and don`'t ask me to get into bed any more.`'
This request was of course readily granted;
and from this time commenced the more apparent symptoms of approaching dissolution.

In the afternoon she asked for two of her sister`'s children,
and spoke to them beautifully,
adapting very remarkably her discourse to their understanding.
When they were leaving her, she made signs for their return; and, kissing them,
as she had done before, she burst into tears, and said, '`My dear children,
may the Lord bless you!`' She had also desired that,
if she lived till morning she might see her own brother and his children.
She also desired her sister`'s husband to read that passage in the Revelation,
where it is said,
"`Blessed are the dead who die in the Lord;`" and when he took the Bible, she said,
'`You may read the whole chapter.`'
This being done, a solemn pause ensued.

Her own brother was now also with her; and with great calmness, and very distinctly,
she thus expressed herself:
'`I have been thinking much this day of the passages which have now been read;
but I did not recollect they were uttered through so much distressing experience.
I am convinced that a submission to the crucifying power must be witnessed a
submission to that which alone can make a separation between joints and marrow,
between the precious and the vile; all must be crucified,
before they can be profitably understood, or opened to our understandings.
But as the unfolding of them is patiently waited for, in child-like simplicity,
these mysteries will be revealed to us: especially,
as we become redeemed from the wisdom of the world, and all its pollutions,
and follow the Lamb immaculate in perfect simplicity-follow
him whithersoever he is pleased to lead us,
without grasping at too much, being assured that sufficient has been,
and will hereafter be, revealed to us.
As we are thus content to follow him in all his manifestations,
we shall experience a measure of the new birth, or of the new life unto righteousness,
to be so formed in us, that whether he may lead, or put us forth into service,
or we may be led in a way incomprehensible to our fellow-pilgrims, it will be enough.
For in this total surrender of our wills to the Divine will,
in which we are enabled to say, Work with me, as it seems good unto you,
the great name will be equally glorified.
For his glory consists in our doing his will;
but this requires the total surrender of all our faculties; of all we have,
and of all we are, to him: and however deeply we may be tried,
whatever we may have to pass through in this life, or in death, it will be our support.
The evidence of it has been to me as the shadow of a mighty rock in a weary land.

'`I have been much tried with poverty, and +++[+++have]
passed through many sore conflicts, even during this sickness;
but my trust and confidence remain unshaken, that as we are stayed upon his name,
which is his power, though we may be brought to the balance of the sanctuary, and +++[+++it]
may appear poised, as to the weight of a hair, and we,
not being permitted to see how it preponderates, or how it may turn with us,
may be surrounded with deep dismay;
yet as we have been willing to surrender ourselves wholly unto him,
he will make up every apparent deficiency.
In this purified state, we shall have to behold Zion a safe hiding-place,
and Jerusalem a quiet habitation; so secure, that not one of her stakes can be removed,
nor one of her cords be broken!

'`Had not my confidence been in prospects and convictions like these,
I know not what I should have done in this trying hour.
It is all I have to lean upon, and I feel its support.`'
After a pause, she added, '`And now, my beloved brothers and sisters,
do you remember this my dying testimony.`'

Her attending relations were apprehensive,
from the struggle which this exertion had occasioned,
that the conflict would have ended in her speedy dissolution; but she again revived,
and passed Seventh-day night and First-day in more ease than was expected.
About twelve, on First-day night, she had a return of the spasm with great violence,
which was succeeded by a slight delirium.
Towards morning she became much troubled,
expressed a fear that her sufferings were prolonged in displeasure,
and said she was sensible of being held on some account; but that on examining herself,
she could not see the cause.
Then she looked on her sister in a very moving manner, and said, '`O my sister,
I fear you can not give me up.
It seems as if I felt your resistance; and my captive spirit needs to be set free.`'
Her sister replied, that she did all in her power to submit;
did not dare to call in question the dispensation; was mercifully permitted to feel calm;
and thought she could venture to say, '`I have resigned you.`'
'`Ah,`' said Elizabeth, '`but have you made a cheerful surrender of me?
for that only will be acceptable from you.`'
Her sister again replied, hoping that she could make some allowance for her weakness;
and would feel that some would also be made by Him
who condescends to compassionate our infirmities;
that her dear sister knew the loss would be very great; yet,
sensible of Elizabeth`'s sufferings,
and beyond all doubt of her fitness to enter the mansions of undisturbed rest,
she had labored against all selfishness.

A short time after this, Elizabeth, looking with unutterable sweetness,
took her sister in her arms, and kissing her, said, '`I am afraid I have afflicted you.
I do, my dear sister, feel for you, for you are to be felt for; but do give me up.
I must go.
May the Lord support you.
I am free to tell you now, and I have not had liberty before to do it, My work is done,
and I am ready.
I do not feel the weight of a hair.
And now, after a conviction like this, if I should turn to you,
and again feel the tender bonds which of myself I could not resign,
you can not wonder if I long to be dissolved.
I have seen it is in wisdom and mercy that my sufferings have been thus prolonged.
Had I been taken in the forepart of my illness,
I fear there was so much dross to be purged away,
that I should not have been found in acceptance;
but I have been mercifully dealt with every way.
And now, all being removed that has appeared as obstruction,
I have nothing to cope with but the conflicts of the body.`'

After this, some medicine was given to her; and as she took the cup in her hand,
she was heard to say, '`O Lord, if it be your will,
grant that this may be the last draught of this kind; but, O Lord,
preserve me in patience.`'

About six, on Second-day morning, the 30th, her sister went to her, and said,
'`I think I have now strength to say, I do freely resign you.
I humbly hope your request will be granted, as I verily believe the Lord has heard it;
and that his arm will be round about you to the end.`'
Elizabeth replied, I am thankful to hear you say so.`'
She continued to the close perfectly clear and sensible, said, in a sweet frame of mind,
something further testifying her love for her sister, and in about half an hour,
without the least apparent emotion, passed quietly away.

[.asterism]
'''
ESTHER TUKE, of York, long known and beloved in the Society of Friends,
who died the 13th of the Twelfth month, 1794, was daughter of Timothy and Ann Maud,
and born at Westcoals, near Halifax, in the year 1727.
Her parents afterwards removed into the neighborhood of Bingley,
where her father died when she was about twenty-five years of age.
In the early part of her life,
she was captivated with some of the vanities to which youth is liable;
but the loss of her father, and a concurrence of some other trying events,
tended to humble her, and to prepare her for the reception of a divine visitation which,
about this time, was powerfully extended to her.
To this gracious influence she bowed in filial submission.
She was willing to bear the cross, and to despise the shame;
and chose rather to suffer affliction with the people of God,
than to enjoy the pleasures of sin for a season.

At this time of her life she was very distantly situated
from the particular and monthly meetings to which she belonged;
yet she was a diligent attender of both.
Many were the exercises which she had to experience;
but as she abode in patience under the operations of the holy Hand,
she became a vessel sanctified, and prepared for the Master`'s use.
About the thirty-fourth year of her age, she gave way to an apprehension of duty,
which had long been in her view; and appeared in public as a minister,
with these few words; "`The just shall live by faith.`"
From this beginning, apparently small, she was enabled to increase;
and as she grew in years she was thought also to grow in faithfulness and dedication;
and truly attained to the state of a mother in Israel.
About four years after this more public espousal of the cause of righteousness,
she entered into the marriage state with William Tuke, of York, then a widower,
with several children.
In this station her discretion as a mother,
and the impartiality of her affection towards her own children,
and those of the former marriage, were such as are too seldom found,
and afforded an instructive example.

As to her travels in the service of truth, they were extensive.
She paid a general visit to the meetings of Friends in Ireland,
was several times in Scotland,
and Friends in most parts of this nation were partakers of her religious labors.
But it is rather the weight than the extensiveness of her service
which those who knew her best have been desirous to commemorate.
She not only deeply lamented the obvious departure
of many among us from our various testimonies;
but the state of such as are engrossed with the cares of this life; for she knew that,
though such may have been in past time awakened,
and may yet retain a specious appearance; yet,
their affections being centered in the earth,
they lose the qualification for religious service, and often obstruct it,
even when they appear to be its advocates.

She was particularly solicitous for the right education of youth;
and such was her concern on this subject,
that she united with a few other Friends in establishing a school at York for girls; and,
at their request, took the superintendence of it.
In the execution of this charge,
she appeared to gain the general good will of the children;
but she had greatly to lament the neglect of parents,
to bring into due subjection the tempers and wills of their offspring.
This neglect increases the difficulty of education,
causes the cross occurrences of life to be more painfully felt,
and renders it harder for the youthful mind to submit to
the necessary restraints of the Christian life.

In the middle stages of life, she was much tried by bodily indisposition.
This increased with advancing years;
but did not prevent her exertions when duty called her into religious service;
and she often travelled under difficulties that few would have encountered.
Still, she looked beyond these afflicting dispensations;
and frequently expressed her desire gratefully to number
the blessings with which she was favored.

Thus, as the course of her life was instructive, not less so were her closing days:
they were strongly marked with the humility of a disciple of Jesus.
She had often mentioned her apprehension that her last illness would be short,
and would not afford much opportunity for verbal expression of her feelings;
and in the view of her final change,
she often testified much satisfaction and peacefulness.
Her last illness accordingly only continued about a week.
Great, at that time, was the sweetness, and deep the solemnity,
frequently felt by her attending relations and friends.
In the self-abasement, already mentioned, she once did express herself to this purpose:
That notwithstanding she felt herself as one of the lowest of beings, yet,
as she had been favored to administer what might be only like a cup of cold water,
in the name of a disciple,
she fully believed that it was not the divine intention that she should lose her reward;
and that, though she should continue as in the depth of poverty,
this belief was sufficient.
And well might she thus say: Her confidence was in the promise of her Lord,
whose words are yes and amen forever! "`Blessed are the poor in spirit,
for theirs is the kingdom of heaven!`"

[.asterism]
'''
WILLIAM PRIDEAUX--In the ninth part of this work, published by Thomas Wagstaffe, in 1795,
there is an account of Mary Prideaux, a Friend, of Cornwall.
It is a pleasing portraiture of a dedicated and happy mind.
She was the wife of William Prideaux, the subject of the present memoir;
and it appears that they were united in a relation even more than conjugal.
The married state is generally allowed, by the virtuous,
to afford the most complete specimen of human happiness: but when,
to the ordinary requisites for producing this happiness,
is added a unity of religious feeling,
and a joint and harmonious endeavor to serve the Lord, then,
the state has attained the summit of the felicity of which it admits.

William Prideaux, of Kingsbridge, in Devonshire, was born about the year 1716;
and in the early part of his life did not profess the tenets of the Society of Friends;
but being convinced about the thirty-third year of his age,
he became a lively and useful member of it.
He was long in the stations of an elder and overseer,
and was a man peculiarly qualified for sympathizing
with the afflicted either in body or mind.

He lived to a very advanced age, surviving his pious wife nearly twenty-three years;
but the various lively expressions that fell from him during
the illness which terminated his lengthened course,
demonstrate that in mind he resembled the prophetic description of the Psalmist,
speaking of the righteous, "`They shall still bring forth fruit in old age;
they shall be fat and flourishing.`"

A few days after he was taken ill, he said, '`It is a mercy, that I feel ability to say,
"`Your will be done.`" `'Tis not in man`'s power to say so;
but I feel the power which enables me, and am thankful for it.
There is no terror in looking forward.`'
Then he broke out, '`O my soul;`' but seemed too full for further utterance,
otherwise than in sounds which bespoke the melody of his heart.
After this, by means of some medical assistance, he appeared to recruit;
but a symptom succeeded which appeared to portend, unless removed, a speedy dissolution;
and he received pleasure when he discovered it.

One day subsequent to this, on taking leave of a relation, he said,
'`I have always loved the truth, and now it does not fail me.
What I have always desired, I now experience.
I have nothing but peace in looking forward or backward.`'
Soon after he said, he loved to see his friends, but loved better to feel them:
twice exclaiming, '`All is well:`' and the same evening he said, '`I have nothing to do now.
What a great favor! we who have loved the truth in our health,
to experience its support on a dying bed!`'

The next day he remarked, '`It is not enough to call God Father by creation only;
but we must know him to be so by regeneration also.`'
On being asked if he were pretty comfortable, '`Yes,`' said he,
'`I don`'t know when I was otherwise.
How should I be otherwise?
My Lord God Almighty is with me, my dear Redeemer, whom I wish you and all to honor,
even in the little concerns of life.
He has done for me far beyond what I could ask or think.`'

Thus he continued a few days, evincing from time to time his resignation, his gratitude,
and his hope; and on the evening before his departure,
on an ineffectual attempt to relieve him by a surgical operation,
the calmness of his mind did not appear to be interrupted.
He had, however, suffered much fatigue from the attempt,
and complied with the request of his medical attendant, in taking an anodyne medicine;
but between four and five in the morning, he distinctly said,
'`I am going;`' and his breathing soon becoming more difficult, it ceased in a short time,
and he passed away without a sigh, in the eighty-third year of his age.
During his illness it had been evident that death was his desire;
but it is not recollected that he ever complained that his sufferings were tedious:
and the true resignation which through grace he had been enabled to attain,
was to be discerned in the serenity of his countenance.

[.asterism]
'''
SOPHIA POPE, daughter of Robert and Margaret Pope, of Staines, in Middlesex,
departed this life the 10th of the Fourth month, 1799,
in the twenty-second year of her age.
She was a young woman of a lively disposition,
and had not been remarkable for peculiar attention to religious duties,
and the concerns of a future state, until about the last year of her life.
About the time that she began to show symptoms of increasing care on these subjects,
her youngest sister Harriet was removed by a consumption, at the age of nearly 18 years.
Harriet had been infirm from her infancy.
A paralytic affection, which occurred before she was one month old,
had disabled her right side.
She, too, closed her days awake to the true interest of life; and Sophia,
the more immediate object of this memoir, now also alive to similar feelings,
penned the following short memorandum respecting her departed sister.

'`My dear sister, a few days before her decease,
mentioned how uncomfortable the state of those must be,
who delayed repentance till an hour when nature seemed scarcely
able to support the weakness under which a debilitated frame labored.
And, though she was not conscious of having committed any great error; nevertheless,
being too unguarded, her disposition had, she feared,
betrayed her into an unbecoming quickness of speech;
but having felt deep remorse whenever that was the case,
she hoped she had met forgiveness: for a sick-bed was not a place to recount past faults:
the mind, at such a time, had enough to do to preserve perfect stillness.
And, as she thought she should soon leave us, she wished that we, who remained,
would be comfortable; and added, that had she lived to a more advanced period,
she might not live in the manner she wished.`'
Her decease was the 25th of the Sixth month, 1798.

Sophia`'s good impressions continued with her; and beside the language of conduct,
are also evinced by some notes which relate to the end of this year,
and the opening of the new one, and were copied from her pocket-book.
On the former of these occasions she says, '`Another year of my life passed!
Ah, could I but improve every one of my remainder!
And though health has forsaken me for the present, still,
if it should please him in whose hands the determination of things pass,
to restore me to health,
I hope a greater attention to the truly needful will be my case.`'
Her new year`'s meditations ran in the language of prayer:
and here I would warn the critical reader, that in such expressions,
he must neither expect perfect accuracy of language,
nor be offended when he perceives it to be lacking.
The mind may be too intensely fixed upon the thing, to advert to the mode.

'`Teach me,`' says she, '`you great Author of all events below,
to bear your dispensations with patience becoming me, who am entirely dependent on you.
And although health has left me,
and I seem gently following a current that leads to my final end,
be pleased to make the passage through the valley of the shadow of death easy: easy,
I say, for O, that the sting might pass first.
Hard it is to the natural part to leave kind parents and friends; but, with your aid,
may they with fortitude support their minds,
hoping that the change may be for a more worthy inheritance
than I could have attained below.`'

By these remarks we see that disease had already seized and impaired her frame.
The same lingering but sure conductor of many a blooming youth to the tomb,
which had cut short her sister`'s days, was now preparing to do the like to hers.
She did not see a third of the advancing year;
but for the most part was preserved in resignation,
and in near affection to her parents and relations.
About three days before her departure, she prayed thus: '`Father,
although I have not walked before you so circumspectly as I ought,
yet you have been pleased, at seasons unknown to any but yourself, in my retirement,
to enable me alone to worship you.
You have many times comforted me.
Support and preserve my dear friends under their trial.
You have been pleased to take my dear sister, I trust, to yourself.
I pray you that my spirit may mingle with hers.`'
After a little pause, she remarked that long life was not desirable,
on account of the many temptations to which we are liable here:
and at another time she said, that she hoped her lamp was trimmed.

[.asterism]
'''
SARAH CRAWLEY was born at Hitchin, in Hertfordshire, in the year 1717.
Her mother, who, like herself, lived to a great age, was, I think,
the daughter of John Field, the compiler of the third, fourth,
and fifth parts of '`Piety Promoted`', and was so ancient as to remember William Penn,
in whose company she had been.
This, her daughter, came forth in the ministry when very young, and found it her concern,
in early life, to visit the meetings in different parts of Great Britain and Ireland.
After this, she travelled little for many years, having, as she said,
no concern for such engagement.
She continued, nevertheless, in the frequent exercise of her gift,
at home in her own meeting, manifesting her constant dedication,
and demonstrating the liveliness of her spirit.
During this long recess from traveling, she kept a small shop,
in the business of a confectioner, in her native town,
and had a long while for an inmate her aged mother.

At length, in the decline of life,
she apprehended herself again called forth to travel in the work of the ministry;
and she accordingly travelled into many parts of England, and once more into Ireland,
sometimes under great weakness of body, yet evidently borne up in spirit.

One of her later visits had been to London,
and at length she believed it her duty to come and reside there.
She accordingly removed into the limits of the Peel monthly meeting,
where she continued the last four years of her life.
In this new situation she was not idle, but frequently visited the meetings of Friends:
until a hurt which she received from a fall in her apartment,
was the means of confining her to her bed-chamber, and mostly to her bed,
during the remainder of her time.
She was admirably supported under this trial, and said,
that all was made up to her by the precious communion
which at seasons her spirit was favored to feel.
She several times remarked,
that her coming so late in life to London might seem strange to others,
as it often had done to herself: nevertheless,
she continued to believe she had been right in taking that step,
and said that she had not repented of it, even in her most proving seasons.

When circumstances which used to give her pleasure were mentioned to her,
she remarked that she seemed to have done with things relating to time;
and that when she was capable of thinking clearly, all her thoughts centered on eternity.
At one time she said, that her mind was particularly struck by that passage of Scripture,
"`I have refined you; but not with silver.
I have chosen you in the furnace of affliction.`"
She also remarked that she had a firm hope that all would be well with her;
for she thought she had been favored to see, as it were, the gate of heaven open;
into which, in a humble manner,
she expressed her trust that in a short time she should be admitted.
Once, also, when a Friend, returning from the Peel meeting,
not far from which Sarah`'s lodging was situated, called on her in her chamber,
she remarked, that although she was then prevented from meeting with her friends,
she had that morning been meeting with the `'General assembly and
church of the first born which are written in heaven.`'

She was a woman of a cheerful disposition,
which did not forsake her when she was finally confined for many months to her bed;
in which, nevertheless, from the nature of the injury she had received,
she was unable to take the repose of a recumbent posture; but constantly,
sleeping and waking, night and day, sat up;
having some contrivance to lean on before her, when she went to sleep.
I several times called on her in this state,
and scarcely ever left her without having been witness to her cheerful turn of mind.

She died the 5th of the Second month, 1799, aged about eighty-one,
having been a minister about sixty years.

[.asterism]
'''
MARY BASS, was the eldest daughter of Henry and Elizabeth Bass, of Ramsey,
in Huntingdonshire, and was born about the year 1775.
She was considered an exemplary young woman;
and as she was bereft of her pious mother at a very early age,
the care of a large family soon devolved on her.
Her mother was daughter of Isaac and Barbara Gray, of Hitchin;
and on the decease of Henry Bass, which took place in the year 1796,
his three daughters settled in that town.

In the year 1799,
she showed symptoms of that disease which was the means of terminating her earthly course.
It was thought to be that afflicting ailment known
by the descriptive name of water in the head.
The pain which it occasioned was at times very intense;
and did not always occur without inducing a temporary delirium.

She did not at first appear to believe that her disease was mortal,
as will further appear;
and she suffered a long train of deep bodily suffering with great resignation.

Taking leave once of a brother, she advised him to be diligent, saying,
'`I am sure there is need of it,
for it is a hard thing to have anything to do on a sick bed.
What a comfortable thing it is that I have nothing to do!
But I believe I shall get better.`'
Her brothers (for it seems more than one were present) appearing affected, she added,
'`You need not grieve, for if I die, I shall go to heaven.`'
Something similar to this she said to one of her sisters.`'
If I die, it is hid from me, and no doubt wisely so.
It is often the case.
I do not wish to be presumptuous about it; but I do not think I shall.
If I do, you have had a greater loss.`'
Here she referred to that of their parents.

After having passed a few days in comparative ease,
her pain returned with great violence: on which she remarked,
'`How trying it is to pass through the fire a second time!`' On another occasion,
being in great suffering,
she signified her apprehension that she should be soon laid low.
To an aunt she once said, '`I do not wish to be selfish;
but I think I had rather die than live.`'

She once desired a sister to be called up in the night,
for she had felt herself so much exhausted by the pain,
that she seemed to believe her end to be approaching.
When her sister arrived she addressed her thus: '`Let me kiss you,
my dear sister;`' then pausing, added, '`Can you give me up?`'
Her sister expressed her hope of submitting to the will of Providence; and Mary replied,
'`But you should do it cheerfully.`'
On First-day evening, after a day of great suffering, she said,
'`I am now only waiting the will of the Lord;`' but
a sense of her close was not yet given to her,
for after a pause she added, '`I do not know but I shall get better yet.`'

The Third-day following, she was very quiet and composed,
and she desired to have some of the Scripture read.
This had not been done for some weeks, though it had been her own daily practice,
when in health.
After this had been done, she remarked that it seemed to her like First-day.
'`Indeed,`' said she, '`it has been to me a Sabbath, a holy day of rest.`'
In the evening she said, '`When the pain has been sometimes so great,
as to make me sweat to a great degree, then I have thought my sufferings, though great,
were nothing in comparison of sweating great drops of blood, through agony of mind.`'

At another time she observed one of her brothers to weep, and said to him, '`Don`'t grieve.`'
Her brother then expressed his sympathy,
and his hope that she might be favored with a little ease: to which she answered,
'`It is very kind.
If it had not been for the presence of the Lord, my sufferings would have been tenfold;
but he has been exceedingly good to me all through my illness.`'

Once, on a First-day in the afternoon, after having been very ill,
she broke forth in supplication, saying, '`O Lord God Almighty,
permit me this once to supplicate your holy name on behalf of my dear brothers and sisters,
both present and absent.
Be pleased, O Lord, to multiply their blessings.
Feed them with food convenient for them.
Make them as pillars in your house.
And my dear sister, be pleased to sanctify her afflictions unto her.
Grant her patience, O Lord.
You can do all things according to your might.
And if it be your will, receive my soul,
and grant me an easy passage into your heavenly kingdom.
You know I love to serve you above all things:
and if I have withheld anything that is right, it has not been through disobedience,
but for fear of being too forward.`'
After some time, she added,
'`I am glad I am thought worthy to be taken from the troubles to come:
for they will be great, and I hope Friends will stand fast.`'

The same evening she was assisted to get out of bed,
when she addressed several of her relations, who were standing by, after this manner:
'`You cannot think how easy this illness has been made to me.
The Lord has been so good to me, that I have not even thought the time long.
I can`'t see my way clear to heaven yet; but I do not know that anything is in my way.`'
A relation remarking that she hoped there was nothing in the way but time, Mary replied,
'`I hope not.
If there was, I hope the Lord would make it manifest, for he has been so kind to me.`'
After sitting awhile in great composure of mind, she said, '`The land mourns,
because of great bloodshed.
Lord, forgive them, for they know not what they do.`'

About this time one of her brothers, not having been lately present, came to see her:
with which visit, though then she was very ill, she appeared to be much pleased;
and after expressing her gladness, she advised him not to look at others for example,
but to follow the dictates +++[+++of truth]
in his own mind.
A wish for her recovery having been mentioned by one of the company, she replied,
'`The Lord is as able to raise me up now as at the beginning, if it be his will.
If not, I hope he will soon release me.`'

She continued about three weeks after this, in great quietness of mind,
and several times signified she was only waiting to be released;
being perfectly resigned to the will of Providence,
which ever way her disorder might terminate.

Thus, being favored to close her days in great peace, on the 20th of the Twelfth month,
1799, and about the twenty-fourth year of her age, she expired without a sigh.

[.asterism]
'''
SAMUEL EMLEN, of Philadelphia,
a frequent and much-loved visitor of Friends in this country, who died in that,
his native city, the 30th of the Twelfth month, 1799,
was the descendant of one of the early settlers in Pennsylvania,
and born the 15th of the Third month,
1729-30. He had the advantage of probably the best
education which Philadelphia then afforded;
and his own genius, aided by a memory uncommonly retentive,
enabled him to improve himself in learning as he advanced in life.
He served a mercantile apprenticeship with James
Pemberton (also mentioned in the present volume),
but never himself engaged in trade.
He was religiously disposed from early youth; and, having the prospect of competency,
he devoted his maturer age, and indeed his whole life,
to pursuits and services of a religious nature.

In the year 1756, Samuel Fothergill, Catharine Peyton,
and Mary Peisley (of whom there is some account in this volume),
were returning from religious visits in North America.
Samuel Emlen bore them company in a vessel bound to Dublin; and,
falling in with Abraham Farrington, a ministering friend also from America,
became his companion in a religious visit to friends in some parts of Ireland.
On this journey, at a meeting at Carlow, Samuel Emlen first appeared as a minister.
He passed the winter chiefly at Warrington with his friend Samuel Fothergill,
a man well adapted to please and instruct him; and,
after continuing some years in England,
he embarked for South Carolina with John Storer of Nottingham,
and accompanied him in his religious visit to that province,
and some other southern parts of North America.

In 1764 he married Elizabeth Mode of Philadelphia,
and as the health of both himself and his wife was infirm, they came to England,
and resided some years at Bristol, in order to be near the Hot well.
Here he had two children born, but his wife was taken from him,
departing in the First month, 1767.
He then returned to Philadelphia; but came again to England the next year,
to conduct to America his two sons.

In 1772 he came again to England on a religious visit.
He crossed the sea with John Woolman.
They arrived in time for the yearly meeting, and Samuel, shortly after,
had to attend the burial of his beloved friend Samuel Fothergill; whom,
in his last journey to England,
he had joined in visiting the families of one or two monthly meetings in London.
In the course of his visit he went to Holland, with William Hunt and Thomas Thornborough,
two American friends, also traveling on religious service.
It is remarkable that his friend and ship-mate John Woolman,
and this his later companion, William Hunt,
were both removed by the small-pox in England in this year:
as his former companion Abraham Farrington had been, but not by that disorder, in 1758.
Of the two former, there are accounts in the eighth part or volume of Piety Promoted;
and of the latter there is one in the Collection
of Testimonies concerning public friends deceased,
published in 1760.
Samuel Emlen, whose talent did not appear to lie so much in general traveling,
as in visiting friends in cities,
and places where he could readily go from house to house, returned to Philadelphia,
if my information be correct, in the following year.

In the year 1784 he came to England again on a religious visit,
in company with four other ministering friends, namely, Thomas Ross, George Dillwyn,
Rebecca Jones, and Mehetabel Jenkins.
They landed in time for the yearly meeting, and soon after,
Samuel Emlen went with George Dillwyn, and John Kendall, of Colchester,
to visit the few friends then resident in Holland.
Previously to his departure from America, he had entered again into the married state,
with a friend of Philadelphia; and he returned to his family in the autumn of 1785.

His next visit to England was in 1792.
He then crossed the Atlantic with Sarah Harrison,
a ministering friend coming to visit England,
and Mary Ridgway and Jane Watson of Ireland, returning from a like visit in America.
He returned, in 1794, with John Wigham and Martha Routh,
two friends going on religious visits from this country, and landed at Boston.

He was a man of a feeble frame of body,
and was afflicted with a disorder which rendered traveling peculiarly harassing to him;
and which probably was some means of preventing him from coming
to London in his seventh and last visit to these nations.
He arrived at Liverpool in the summer of 1796,
accompanied by Deborah Darby and Rebecca Young,
on their return from visiting friends in America; and by William Savery,
a fellow-minister of his own monthly meeting,
that for the Northern District of Philadelphia.
The services of Samuel Emlen were chiefly confined to Lancashire,
and some parts of Ireland.
His absence from home was about eighteen months,
an interval shorter than is often taken up in these religious services;
but during this absence he became again a widower.

Samuel Emlen passed so much of his time in some parts of England,
that we have little need of other information, than that which recollection affords,
to describe his character; and, generally speaking, it is by comparing the life,
and the approach of death; the path which has been trodden,
and the prospects which open on its close;
that instruction and encouragement are derived from narratives like these.
To say little of his cheerful temper, and the store of his memory,
which made his company pleasant to those who loved
to contemplate religion under its brighter forms;
and of course especially so to well-disposed young people,
in whose society he took great delight, I think I may venture to say,
he was a man fearing God, and hating covetousness.
His mind, though often at liberty for lively conversation on outward matters,
seemed to be constantly revolving on the more important
things which pertain to life and salvation.
Thus, few were so ready with a word in season on religious topics;
particularly in addressing with pertinence the various persons to whom
from time to time he thought himself required to minister.

He was well read in the Scriptures,
and eminently versed in some of the prophetical writings: and in later life,
when by a residence with him under the same roof,
I had the most opportunity of observing him,
he used to have the Bible read to him after he had retired for rest.
In his public service he was very fervent,
particularly in endeavoring to arouse the careless professors of a religion which does
not allow all the indulgences which they seem to think themselves at liberty to use.
With all this, and crowning all this, he was a humble man.
He ascribed all he had, and all he was, to the favor of his Lord.
I was considerably struck, once when he was sick in London, to hear him say,
'`Thanks be to the Lord, for the hope I have in his mercy.`'
It then seemed a less strong expression of confidence than, probably,
through inexperience,
I should have expected from a man whose whole life seemed devoted to God.
I have since lived to see that it contained everything
which the self-abased Christian can desire:
and such a Christian was he.

His constitution, as has been hinted, was naturally infirm;
and in the latter years of his life,
had been further impaired from the frequent recurrence
of the pain to which his disorder subjected him.
In the autumn of 1798, after a long walk in a cold wind,
he was attacked by new symptoms of disease,
which his physicians supposed to be those of the gout.
His wrist was affected with violent pain, which immediately spread up his arm,
and seemed to affect the region of the heart.
Such attacks seldom lasted more than fifteen or twenty minutes;
and seldom confined him to the house more than two or three hours,
until within a short time before his decease.

In the Eighth month, the following year, while residing with his son at Westhill,
near Burlington, on account of the prevalence of the yellow fever in Philadelphia,
he thought himself sensible of a slight paralytic affection;
but on his return to the city in the Tenth month, his health seemed to be improved,
and he experienced little interruption in his accustomed employment
of calling on his friends and of visiting the abodes of affliction.
This latter was a practice to which a considerable
portion of his time had long been devoted.
He considered it a religious duty, and it was congenial to his benevolence.
In the Twelfth month his gouty spasms returned with increased violence,
and on the 15th of that month, being at meeting, and having delivered a lively testimony,
he found himself ill; and leaning, through weakness,
on the rail of the ministers`' gallery,
he repeated pathetically those well-known lines of Addison,

[verse]
____

"`My life, if you preserve my life,
Your sacrifice shall be;
And death, if death should be my doom,
Shall join my soul to thee.`"
____

On this, the meeting was broken up; he was assisted to go into an adjoining dwelling;
and, after he recovered a little, was conveyed home;
but the next morning he was well enough to attend
the usual meeting of ministers and elders,
and his own meeting on Third-day.
In this last,
he was large in testimony to the excellency of that faith which had been his shield:
commenting on the text, "`This is the victory that overcomes the world,
even our faith.`"

In the latter part of this week, his spasms returned so frequently,
that his physician urged him to confine himself to his house; and he went out no more.
But during the succeeding week, he received the visits of his friends in his parlor;
and conversed cheerfully with them, and with his family.
Once, while two of his fellow-laborers in the ministry were with him,
he was attacked by a fit of acute pain:
during the extremity of which he manifested the trust of his mind, by saying,
'`I have a comfortable hope that my spirit will be reposed in the bosom of Jesus:
'`and when his suffering abated, he addressed them in a very lively manner,
with this language, '`Remember, "`You have not chosen me; but I have chosen you,
and ordained you, that you should go, and bring forth fruit,
and that your fruit should remain.`"`' When he was alluding
to the care taken of him by those about him,
he said, '`I deem their sympathy and affectionate attendance on me,
as a blessing from heaven; for which God will bless them.`'

During his wakeful hours, the attributes of the Almighty were almost his perpetual theme.
He frequently acknowledged the rich consolation with which he was favored;
and he often repeated these words:
"`Their sins and their iniquities will I remember no more;
and I will cast all their sins behind my back.`"
At one time he exclaimed, '`You shall have a song, as in the night,
when a holy solemnity is kept: and gladness of heart, as when one goes with a pipe,
to come in to the mountain of the Lord.
Oh, the tears of holy joy, which flow down my cheeks!
Sing praises, high praises to my God.
I feel nothing in my way.
Although my conduct through life has not been in
every respect as guarded as it might have been;
yet the main bent of my mind has been to serve you, O God: who are glorious in holiness,
and fearful in praises.
I am sure I have loved godliness and hated iniquity.`'

The day before his decease was the only one in which he was confined to his chamber.
He was on that day visited by several Friends, with whom he still conversed pleasantly.
One of them remarked, that the frame of his mind seemed as serene and peaceful,
as could be conceived of a spirit on the verge of a happy immortality.
At the accustomed time he went to bed easier than usual;
but he was awakened before midnight by a violent return of pain;
and when the common means of alleviation had been unsuccessfully tried,
he desired that nothing more might be done: saying, '`All I want is heaven.
Lord, receive my spirit.`'
He requested those about him to pray for his preservation in patience, himself adding,
'`My pain is great.
My God, grant me patience: humble, depending patience.`'
Presently afterwards he repeated this passage: "`Call upon me in the day of trouble.
I will deliver you; and you shall glorify me.`"
Then with great fervency he said a considerable part of that called the Lord`'s prayer,
subjoining, '`Oh, how precious a thing it is,
to feel the spirit itself bearing "`witness with our spirits that we are his.`"`'

Soon after this he said, '`Oh, the soul is an awful thing.
I feel it so.
You who hear me, mind.
It is an awful thing to die.
The invisible world,
how awful!`' As he was apprehensive of the near approach of dissolution,
he entreated that nothing might be done to him but what he might request, '`that my mind,`'
said he,
`'may not be diverted that my whole mind may be centered
in aspirations to the throne of grace.`'
About three o`'clock in the morning, which was the 30th, he inquired the time;
and when he was told it, he said '`The conflict will be over before five.`'
Shortly after, he prayed for deliverance, saying, Almighty Father, come quickly,
if it be your blessed will, and receive my spirit.`'

He then lay quiet a while, and seemed released; but,
as if he felt again the clog of humanity, he said, in a low voice,
'`I thought I was gone;`' adding,
'`Lord Jesus receive my spirit.`"`' These worthy words
were the last which this Christian uttered,
and about half-past four, he gave up the spirit.
