== Chapter 12

[.chapter-synopsis]
* Hannah Wilson
* Benjamin Kidd
* Sarah Bland
* Mary Ludgater
* Thomas Rutter
* Joshua Wheeler
* Sarah Stephenson
* Joseph Brown
* Richard Baker

HANNAH WILSON, a Friend, who attained to an advanced period in life, and who appears,
from the testimony of her monthly meeting, to have been green in old age,
was born at Simgill, in Grayrig, Westmoreland, the 20th of the Seventh month, 1717.
Her parents were John and Margaret Blamier,
who are said to have given her a religious education.
Being favored when young with the visitation of divine love,
and receiving and adhering to it, she found it a stay to her mind,
and the means of preservation from the dangers incident to youth.
She was frequent in seeking for seasons of retirement, and solitary places,
wherein to wait upon the Lord for the renewal of her strength.
Thus, in her conversation and conduct, she became circumspect herself,
and a good example to others.

About the fortieth year of her age,
and a few years after her marriage with George Wilson of High Wray,
near Hawkshead in Lancashire, she came forth in public testimony;
to the comfort of her friends,
who judged her ministry to flow from the fresh influence of Divine Life.
In this service, she visited some of the counties near that of her birth;
and was esteemed to be well qualified in the useful,
but delicate employment of religious visits to families.
For she was clothed with the spirit of love,
by which means she had much place in the minds of those,
who seemed to dwell at a distance from due subjection of conduct.
She was a very diligent attender of religious meetings,
even when suffering under much weakness of body; and often,
when she came to them with considerable difficulty, she had to minister,
in a lively manner, for the encouragement of others,
to wait steadily and patiently for the help of the Lord: and He,
who had been her morning light, became evidently and remarkably her evening song.

During a long and painful illness, she was favored with much peace of mind;
and at various times said, with clearness and animation,
'`It is sealed to my mind that the day`'s work is done;
and when this painful conflict is over, there is a place of happiness prepared for me.
Lord Jesus come.
Your servant is ready.`'
A few hours only before her departure, she exclaimed with an audible voice,
'`Thanksgiving and glory!`'

She departed the 7th of the Third month, 1800, in remarkable stillness,
having been sensible to the last.

[.asterism]
'''

BENJAMIN KIDD.
Those who have endeavored to travel on, in the path which leads to the heavenly Canaan,
the region of rest, have more or less, at times, found it beset with difficulties;
notwithstanding its just and sole claim to the title of a way of pleasantness,
and a path of peace.
They have in a degree partaken of the experience, "`Without are fightings,
within are fears.`"
To such,
it is pleasant to see these difficulties all surmounted at the close of a long life,
through the love of the Redeemer: who, says the writer to the Hebrews,
is a high priest touched with a feeling of our infirmities.

Thus closed, at the age of seventy-five, the life of BENJAMIN KIDD, of Godalming.
He was a man of a meek and quiet spirit, humane and charitable,
and conscientiously upright in his dealings among men;
and he was enabled to assert in the decline of life, that his care had been great,
that he might do nothing to offend his God.`'

He was an acceptable minister, but was not engaged to travel much,
or to a great distance; yet he once visited, namely, in 1785, the meetings of London;
and also travelled into some counties westward of his habitation.

But, though his conduct was exemplary,
and seemed to hold out to others an invitation to follow him, as he followed Christ; yet,
during his last and long illness, he was at times assailed with doubts,
under the apparent desertion, or withdrawing of that support, that divine good,
which his soul loved, and longed for above all things.
But this solace was again mercifully extended; his doubts were removed; and,
as he told a near relation, '`a sweet assurance was granted him,
of an admission into eternal rest.`'
He added,
that '`he never before had had so bright a prospect;`' and he enjoined her not to grieve,
'`for,`' said he, '`it will be well with me.`'
After this he spoke but little that could be understood;
though he frequently appeared to be engaged in prayer to be released;
yet that he might be enabled patiently to wait the Lord`'s time.

He departed the 15th of the Third month, 1800, having been forty-three years a minister.

[.asterism]
'''

SARAH BLAND, of Norwich, was the daughter of Francis and Mary Lawrence of that place,
and born the 27th of the Fifth month, 1732.
The testimony given by the monthly meeting of Norwich,
imports that she was early visited by the power of truth;
though her youthful inclinations induced her to deviate, in some degree,
from the narrow path, in which its followers find it their safety, as well as duty,
to walk.
But it was at length her happy experience to know her unregenerate will subdued; and,
having passed through various exercises, and baptisms in spirit,
she became able to testify to others what her own eyes had seen,
and her hands had handled;
and received a gift in the ministry about the twenty-second year of her age.

This account which I am now about to prepare,
will probably differ in two respects from the greater
part of those which compose this volume.
Of dying expressions, properly so called, it will contain but few;
and as for a long series of years I was acquainted with Sarah Bland,
and knew something of her worth,
I may take the liberty of deviating the more from the province of compiler,
and of speaking from knowledge.
Her first husband was my maternal uncle; her second, my friend from my childhood.

She was married in or about the year 1755, to Samuel Gurney, of Norwich,
son of Joseph Gurney, of whom there is an account in the Collection of Testimonies,
published in 1760.
To him she was a faithful companion during about fifteen years, which they lived together.
Previous to their marriage, a paralytic disease,
which afterwards increased so as to render him incapable of moving any limb,
had begun to affect him; but when at length it had attained its extreme of disability,
his exemplary patience made his company instructive;
and his knowledge and good humor rendered it pleasant, even to the active and the young.
He departed this course of patient suffering in the early part of the year 1770.

In 1775, she married Thomas Bland, of Norwich,
with whom she passed the remaining part of her life, except occasional journeys;
one of which, in the year 1786, was a visit to Friends in Lincolnshire,
and several counties, as far as Westmoreland,
with the concurrence of her monthly meeting.
She was also concerned to visit some meetings in
the counties bordering on that of her residence;
but her travels in the work of the ministry were not extensive.

A general view of her religious life may be had from a paper,
in the form of an address to the Lord, in acknowledgement of his mercies,
which she wrote about the year 1788.
A part of it is as follows:

[.embedded-content-document.paper]
--

How has mine heart been led to meditate in your law,
and to adore your boundless mercies towards me, from my early infancy to this day!
Your hand, which fashioned me, has pointed out my path;
and in unutterable condescension have you, as a tender father,
checked me when straying from it; and, like a shepherd carrying his lambs in his arms,
brought me back!
Oh! adorable mercy! let me never forget your kindness in my youth.
And when past the days of childhood and of youth, how bountifully did you provide for me,
granting me not only the dew of heaven, but the fatness of the earth! a south land,
and springs of water!
And when, in your wisdom, you have seen good to dispense the bitter cups, the wormwood,
and the gall, your hand bore up my head; yes, your right hand was my support.
You made my bed in my afflictions, and gave me a song of praise in my troubles.

--

She was in some respects of a tender constitution; and as she advanced in age,
had frequent interruptions of health,
which prevented her from the usual engagements of social life,
and from the constant attendance of religious meetings.
On one of these occasions,
at a date subsequent to that of the paper from which the foregoing thanksgiving is extracted,
she committed to writing a memorandum of some further retrospections and meditations,
of which the following is a specimen:

'`Having, from lack of health,
had much leisure to look back and trace the footsteps of my life,
from the early visitations of divine love to my poor soul unto the present day,
my mind has been often bowed under a humble sense of the great mercy,
and unutterable kindness of Providence, in granting his protecting and preserving grace.
I feel at this time, as at many others,
an ardent desire that I may experience the same near to me,
through the remaining days of my life; and be permitted, at the solemn close,
to die the death of the righteous, that my last end may be like theirs.`'

These two extracts were inserted in the testimony
issued by the monthly meeting respecting her;
but she had added to the latter,
some hints of her experience on the subject of those written
memorials which the yearly meeting annually receives,
and in some degree requires, respecting deceased ministers.
'`My mind,`' says she, '`has been often impressed, on hearing the testimonies read,
of several ministering friends deceased; and I have felt,
that whenever it shall please Him in whose hand is the breath of all the living,
to call me from this field of painful labor,
if then my friends have ground for a hope that I have kept the true and living faith,
and unity with my brethren, it is all I desire,
and should rather nothing more might be said:
being sensible it is through the abounding mercy of the Most High, we are preserved.`'

The foregoing extracts may serve to show the tenor of her life,
and that humility was a principal ingredient in her character:
consonant to which disposition I believe it may be remarked,
that in the exercise of her talent as a minister,
she was remarkable for being often engaged in prayer.
She lived to the age of sixty-eight, and departed in peace in the year 1800.
Her last address to some of her relations was finished with these words:
'`You see how a Christian can die; in hope, and humble confidence in her God.`'

[.asterism]
'''

MARY LUDGATER, of Coggeshall, in Essex, was the daughter of Richard and Mary Bradshaw,
of Goswell-strect, London, and born about the year 1770.
Of her childhood and youth, not much is remembered;
but during a residence at Poplar for some years, between her twentieth and thirtieth,
she was considered a serious young woman, and evidently improving in best things.

It is not always from the most conspicuous on the scene of action,
that we hear the most triumphant expressions of hope and praise,
at the approach of death.
The same baptisms which are the means of qualification for eminent service,
sometimes induce a fear, a depression, a sense of unworthiness in the instrument,
which makes it slow in believing that the Lord vouchsafes to regard it,
and that he will finally crown it with eternal blessings;
though it may often have had to hold forth his unfailing lovingkindness,
for the encouragement of others.

Toward the latter end of the year 1800, Mary Bradshaw was married to Thomas Ludgater,
of Coggeshall, in Essex; and the following year gave birth to a daughter.
In a few days she became so ill as to render her recovery very dubious;
but her mind was preserved above the fear of death.
She said to a friend whom she had for some time desired to see, '`Dear friend,
how I have longed to see you!
I wanted to have some conversation with you; but I am so weak, I cannot now say much.
I believe I shall be happy.
I have not buoyed myself up with hope, '`(of recovering,
probably she meant;)`' but oh! the goodness of my heavenly Father!
You would admire,
if I was to tell you what I have passed through since I came to this place.
I have often rebelled, but my heavenly Father has not forsaken me;
for strong convictions have followed, and I hope of late I have been more careful.
Oh! how often I have wished that I might become as a piece of blank paper,
and that all might be begun afresh.
When I have been humbled and obedient, all has gone on so comfortably;
even family concerns, and everything, has gone on pleasantly:
and when I have gone to meetings, and sat, as it were, at the threshold,
oh! what comfortable meetings have I had!`'

At another time, after a sweet pause of silence, she remarked,
'`How sweet it is to feel humility, and not high-mindedness: '`and several times,
when her pain was violent,
she appeared to be craving help to bear her sufferings with patience, saying, '`O,
my heavenly Father.`'
Her sister was once expressing her belief that He would help her,
and making some reference to her innocent life.`'
Oh, '`replied she, '`when once the book of reckoning is opened,
no fig-leaf covering will do.`'
The same evening, she appeared to be sinking fast away from the trials of time;
but she revived, and said, '`I thought I was going.
I have been with my Beloved.
He held me so fast, I thought I should not have returned;`' and she added,
'`He will hold me, and not let me go.
Oh! the sweet fruits I have seen and tasted of!
And, if the foretaste is so sweet, what must the possession be!`' After this,
she told her husband that she never expected to see him again, in mutability;
she took some nourishment, at her own request; asked for her infant, and kissed it,
and said it was a sweet baby;
but more than once said she had quite resigned it to her heavenly Father`'s will.

As she seemed so much to revive,
her medical attendant asked her whether she would be willing to return to her friends.
'`Yes, to be sure,`' she replied,
'`if it is the divine will;`' and she added that she thought she had been enabled to say,
"`Not my will, but yours be done.`"
Yet she observed that the Almighty, who could command the winds and the waves,
that they should come so far, and no farther,
might also permit the disorder to go so far only, if it pleased Him.

After this, however, her disorder increased;
and she besought her heavenly Father that he would grant
that her affliction might soon come to its height;
and that he would be pleased to give her an easy passage.
On the morning of the 23rd of the Ninth month,
she told her husband that she had had rather a trying night;
but that when she thought of her Redeemer, it stilled her.
To her husband and her sister, the day before her decease, she said, Don`'t hold me.
I think you do; but give me up freely, for I am going to rest and peace.`'
Early the next morning, the 26th, she expired.

[.asterism]
'''

THOMAS RUTTER, of Bristol, departed this life in a lively hope of the mercy of Christ,
the 2nd of the Ninth month, 1803, aged 59. He had been a minister from his youth,
having first come forth in obedience to what he regarded
as a requiring of the Lord for that service,
when he was about eighteen years of age.
Previously to this, in his very boyish time,
he had allowed the follies of youth to degenerate into vice;
and at length into infidelity, and a contempt of serious things and serious persons.
However, to please his father, he still continued to go to meetings,
in one of which his attention was caught by a preacher whose subject was
the passage from 1 Pet. 4:18. "`If the righteous scarcely be saved,
where shall the ungodly and the sinner appear.`"
Immediately he was filled with awe,
and with a light which discovered to him clearly his sinful condition;
and he was broken into many tears.
Nevertheless, he soon attempted to shake off these impressions; but in vain:
he sunk under the contest, and then was tempted to despair.
He confessed however in his mind, that he had been divinely visited;
and being sensible that nothing short of the arm
of Omnipotence could save him from being lost,
he sought it earnestly with humble supplication.
He read the Scriptures, he often sought retirement,
and was very diligent in public worship;
but his soul was long detained in a mournful state.

At length his mind was gradually enlarged, and his first comforts arose in meditation,
though they were but faint.
The ministry also of two certain friends was useful to him; and he made them a visit,
supposing that they would feel for his state, and would comfort and instruct him.
But he was disappointed, and led to cry, '`Lord, if you help me not, I perish;
for vain is the help of man.`'
But when, after this gradual preparation,
it pleased Infinite Kindness to afford him a sense of favor,
the current of love was so strong,
that he knew not how to forbear calling on every
creature to join him in the song of praise.
For a time he felt no evil, had an almost continual sense of the Lord`'s presence,
and hastily concluded that his regeneration was complete.
But temptations again beset him,
and he soon felt the further necessity of daily watchfulness and prayer.
Religion appeared to be a very deep work;
but he was supported in the path of patience by some portions of comfort,
and by the secret presence of the Almighty.

It was not long after he was brought into this watchful state,
that he felt his mind strongly impressed to speak by way of exhortation to others.
From this service he was very averse; and endeavored, with contrition and tears,
to examine his call, and, like Gideon, to try the fleece.
The more he examined, the more the evidence was confirmed, till after various baptisms,
he gave up his soul to obey, should further requirings be manifested.
This was not, however, speedily the case.
He underwent a further trial of apparent desertion,
which he humbly received as a chastisement for his delay;
but at length a more full resignation was the means of reproducing peace,
and he found an engagement to come forth with these words:
'`Christ`'s sheep hear his voice.
Let us wait, to hear the voice of Christ.`'
After this also, he sunk very low in his mind, but was gradually enlarged,
and soon became a zealous, reaching, and acceptable minister.

He travelled in most parts of England and Wales, where there are Friends,
and was twice in Ireland;
but to particularize his journeys would be foreign to the purpose of this compilation.
He was twice married: first to Ruth, daughter of Samuel and Deborah Waring of Alton,
Hants, who was removed in 1778, after a union of about ten years; and next,
to Hester Farley, of Bristol, who survived him.

During his last illness, which was painful, and borne with Christian fortitude,
he uttered many expressions, showing his faith, and his resignation;
and he bemoaned the situation of such as defer to the time of sickness,
the important concerns of their souls`' well being.
'`The pains of the body,`' said he, '`are enough to struggle with.`'
Speaking of himself, he said, '`I have nothing to glory in but my infirmities.
I have known something of that law of grace, whereby boasting is excluded.
No merit in me!
All of grace!
All of the pardon and power which are in Christ!! that I had the tongue of an archangel,
to sound forth this glorious truth, that it is "`not by works of righteousness,
which we have done; but according to his mercy he saved us,
by the washing of regeneration, and renewing of the Holy Ghost.`"
Consonant to this also, he frequently said,
'`I never was more deeply sensible of my own unworthiness; and that all is of mercy,
mere mercy!`' A little before his departure he signified his assurance
of an admittance into the kingdom of eternal rest;
and at his close was mercifully favored with an easy
release from the pains of mortality.

[.asterism]
'''

JOSHUA WHEELER, of Hitchin, in Hertfordshire, was the son of Rudd and Fidelity Wheeler,
of the same place, and born about the year 1756.
His childhood, according to his own account,
partook of the wildness sometimes observable at that age.
Nevertheless, he early discovered a disposition to sobriety,
which paternal care tended to cherish;
and it ripened at length into a degree of stability which had its influence upon others.
His mother was removed by death when he was about fourteen, and then a boy at school;
but he had learned to estimate her worth, and his grief was proportionally pungent;
and when he came home to his father`'s family,
and entered into his employment in his trade, he still more sensibly felt her loss,
in the domestic circle in which she now no longer occupied a place.
It is believed that the serious impressions which about this time he received,
were signally blessed to him; and that he became, by his steady conduct,
able to cooperate with the religious exercise of his father`'s mind,
for the preservation of the younger part of the family.

He was used thankfully to call to mind,
and to mention the preservations he had witnessed in early life,
when he was sent out on business to distant markets,
and sometimes among very rough and unprofitable company.
He recounted the care which he found necessary to keep near to the principles of truth,
and to act according to its dictates;
the comfort or the grief which he had found on looking over the transactions of the day,
as his conduct had been steady or deviating;
and the consequent encouragement or caution which it held out to him for the future.

About the twenty-fifth year of his age, he married Elizabeth, daughter of William Brown,
of Ampthill; and they set out in life with many pleasant prospects before them.
But in the course of one year, the health of his wife became so much impaired,
as to prove a trying dispensation to both of them,
during the remaining years which they passed together.
But it nevertheless appears to have been a dispensation of mercy.
It prepared her for a better inheritance; and proved to him a season of refinement,
and of detachment from earthly gratifications;
still further fitting him for usefulness to others.
His wife died in the Fifth month, 1793, after they had been married about twelve years.

Soon after this event, about the thirty-eighth year of his age,
he gave up to an apprehension of duty, which he had some time entertained,
and came forth publicly as a minister.
His testimony was acceptable to his friends,
and he was very solicitous to be preserved from moving without their unity.
Once, in particular, in a religious meeting, with great diffidence,
he expressed his desire to stand open to the feelings
of the least babe who was alive in the truth;
and the belief which his brethren entertained, that he was generally careful,
not only to begin, but to close with the life,
confirmed his testimony to their minds and judgment.
A paper, of which the following is a copy, and dated in the Ninth month, 1793,
will show the reverence with which his mind was clothed, when he entered on the service.
It is entitled, '`The opening of Isaiah`'s ministry.`'

[.embedded-content-document.paper]
--

First, he was favored with a sight of the majesty and glory of God;
and heard the seraphim declare the Lord`'s holiness, and that the earth was full of glory;
and with such power and authority, that the very posts of the door moved,
and the house +++[+++was]
filled with smoke.
Then, as a natural consequence,
he was filled with a feeling sense of his own unworthiness and sinful state,
and under the weight thereof breaks out, Woe is me, for I am undone,
because I am a man of unclean lips, and dwell among a people of unclean lips,
for my eyes have seen the king, the Lord of hosts.
In this humble state was the seraph sent unto him
with the live coal taken from the altar,
which having laid on his mouth, he comforts him.
Lo, this has touched your lips, and your iniquity is taken away, and your sin purged.
Then did he hear the voice of the Lord, saying, "`Whom shall I send,
and who will go for us?`"
Being thus previously prepared, in a grateful sense of the Lord`'s mercy,
and with a willing mind, he was enabled to offer himself.
Here am I, send me.

Thus, O Lord, be pleased to favor me with a sense of your Almighty goodness;
or such a sense thereof as my feeble state may be able to bear;
and that in your light I may see my sinful state, and, with one formerly,
abhor myself as in dust and ashes.
And oh! when sufficiently humbled under a sense thereof,
that I may witness the effects of the live coal, and hear those gracious words,
Your iniquity is taken away, and your sin purged: and under a deep sense thereof,
that I may surrender body, soul, and spirit, into your gracious direction.

--

Towards the latter end of the year 1795, he entered again into a married state,
with Elizabeth, daughter of William Tuke, of York.
It did not appear to be his lot to travel much from home in the exercise of his gift;
yet, with the consent of his monthly meeting, he travelled, in the year 1797,
in some neighboring counties; in 1798, he extended a western journey as far as Plymouth;
and in the following year he went northward as far as York.
In all these journeys,
though not without an engagement of mind arising
from an apprehension of duty on his own account,
he travelled generally in company with others.

After his last journey, his life was almost one continued series of bodily indisposition;
yet he continued anxiously concerned for the cause of Truth.
As private opportunities occurred, he still labored for the good of other individuals,
in a spiritual sense; and one thing which frequently excited his fears was,
lest the gracious purpose of the Lord towards his visited children should,
by one means or other, be frustrated.
For about four months before his last illness,
he enjoyed rather an improved state of health;
yet he did not form great expectations of its continuance;
but rather apprehended that his enfeebled frame would
yield to the rigors of the winter then approaching.
Accordingly, on the last day of the year 1802,
he was seized with an increase of his distemper.
In rather more than two weeks he took to his chamber,
and as his disorder was attended with a distressing degree of nervous irritability,
it proved at times a close trial to his faith.

Once when thus oppressed, he exclaimed, '`Oh, this irritability!
When I try to close my eyes,`'
for after a disturbed night he had been endeavoring to procure a little repose,
'`I seem given up to the powers of darkness and confusion;
but I hope this is not the state my spirit will be centered in.`'
His wife saying that she believed not, he added,
No. I believe my change will be an entrance into peace,
through that mercy in which I can confide; not in any works of my own.`'
Some further consolatory conversation passed between them.
He was then sitting up in his chamber;
but about nine o`'clock he was helped to bed by two assistants,
and he had some refreshing sleep.
Soon, however, the cold sweat of death pervaded him generally;
and on the appearance of this alarming symptom, at his own desire,
his father was sent for.
When Joshua was informed that his father was arrived, he rather hastily,
and as if he feared his articulation would fail him, uttered a few short,
but sweet sentences to some around him, concluding with '`Farewell.
May the Lord bless and preserve you all.`'

This benediction was the last sentence which he attempted to utter;
though it was not till about an hour afterwards, and at half an hour past midnight,
that he breathed his last so quietly,
that the exact moment when he fully put off mortality, was scarcely to be ascertained.
His departure was on the 21st of the First month, 1803.

[.asterism]
'''

SARAH STEPHENSON.--It is scarcely needful here to give a copious account of Sarah Stephenson,
of Melksham, in Wiltshire, who died at Philadelphia, while on a religious visit,
the 25th of the Fourth month, 1802.
The reader who desires further information,
is referred to Memoirs of her Life and Travels in the service of the Gospel,
published in 1807.

She was the daughter of Daniel and Sarah Stephenson,
and born at Whitehaven in Cumberland, in the year 1738.
In her youth she was not without her temptations to the gratifications of a vain mind;
but was inwardly restrained from giving way to them in a great degree; and,
by various exercises and conflicts, was at length brought to take up her cross to them.
When very young, indeed almost in childhood, she had felt the love of Christian virtue;
and when reading the lives and happy conclusion of the faithful, had often paused,
and craved of her heavenly Father,
(in whose power she then appears to have firmly believed),
'`Be pleased to make me like these your servants,
whatever my sufferings in this life may be.
"`If you will be with me in the way that I go, give me bread to eat,
and raiment to put on; you shall be my God, and I will serve you.`"`'

She first came forth in the ministry about the twenty-seventh year of her age,
and not very long after went to reside in Wiltshire.
After this,
the greater part of her life was taken up in upright endeavors to discharge her duty,
as it was opened on her dedicated mind.
Great at times were her conflicts; but transcendently great were her consolations,
and she had often to acknowledge the sweetness of the sustenance with
which her gracious Lord supports the strength of his humble disciples.
She was particularly concerned in the awful service of visiting Friends in their families,
in many, if not in most places where she travelled:
and she travelled in most parts of Great Britain where there are Friends,
in several repeatedly, and in Ireland twice.

At length, about the sixty-second year of her age,
with a body enfeebled by her past labors,
but with a mind strengthened by the long and habitual exercise of faith,
she prepared to set out on a visit to America;
a concern which for many years had attended her mind.
In this journey, Mary Jefferys, of Melksham,
who had been her companion on several former ones,
found herself also bound to attend her.

They landed at New York the 31st of the Eighth month, 1801,
attended several meetings there, on the Main, and in Long Island;
and then proceeding towards Philadelphia, reached it the 8th of the Second month, 1802.
After some rest,
they attended the meetings of Friends in that city as they came in course,
and on the 9th of the Third month,
entered on a visit to the families of one of the monthly meetings; but Sarah was so weak,
that she was scarcely equal to bear the fatigue of three visits in one day.
The engagement was therefore soon suspended;
but she said that the making of the attempt had afforded her satisfaction;
whether she lived to move further in it or not.
After various means, ineffectually used to relieve her ailments,
on the 9th of the Fourth month she was confined to her bed,
and in about three weeks breathed her last.
Her disorder seemed of the pulmonary kind,
and the consequent and violent coughing and expectoration
rapidly fatigued and reduced her.

During her illness, her exercise of mind on account of others,
was for the most part taken from her.
She said she had done what she could in time of health:
and she confirmed the testimony of a minister who had visited her some days before,
namely, that there was nothing in her way.
To one who was affected at observing her increasing weakness, she said,
'`Don`'t be at all uneasy.
I have been sweetly comforted by my good Master`'s presence.`'
A friend remarking to her that "`Her bed had been made in her sickness,`"'`Yes, '`said she,
'`wonderfully so.`'
Being asked how she felt as to recovery, she replied, I have no prospect of it.
I believe I have finished the work.
I have no care, but on account of my dear child: '`by which term she meant her companion,
Mary Jefferys.
The latter, after this, expressed her entire satisfaction at having come with her,
and said that she thought it a favor to be with her,
even though she should be left so far from her native land:
at which Sarah seemed almost overcome with joy, and said, '`Now, how glad I am,
that you have told me!
Now I hope that my good Master will soon take me to rest,
and you will be supported and rewarded.
There is little here but trials, disappointments and conflicts.
Now don`'t hold me, my dear.`'
Then she seemed as if she would sink away; but was heard to say, in a low,
but melodious voice, '`Glory!
Glory!`'

One day, after a fit of violent coughing, which left her much spent, she said,
'`It will be right, let it be which way it may; and that is better than all the world.
It seems as if it must be nearly over now, I have so little strength left.`'
A little after, she seemed to be uttering praises, saying,
'`How good! how good!`' and seemed engaged in sweet supplication.
A friend asking her how she did, she replied, after a pause, '`I cannot say much;
but my king reigns.`'
She uttered but few more expressions; but towards evening, finding herself to sink fast,
she saluted those around her with her dying lips, and said, '`Farewell, farewell:`'
and before seven, she ceased to breathe.

This account being abridged from a larger one in the Memoirs,
I subjoin the concluding exhortation.
'`Here, reader, pause.
Dwell on the closing scene,
and taste the blessedness of the death of those who die in the Lord!`'

[.asterism]
'''

JOSEPH BROWN.--In the present day, when it may at least be said,
that liberality of sentiment, and mutual allowance for difference of judgment,
on religious matters,
prevail in a degree unknown in the times when our
pious forefathers first engaged the attention,
and drew upon themselves the abuse of their countrymen,
it is rare to find any one suffering imprisonment for ecclesiastical causes.
But as in the life of Joseph Brown, we have an instance, and not a solitary one,
of such being the case,
a concise sketch of the attendant circumstances may
not be improperly introduced in this place.

Joseph Brown, was an inhabitant of that retired part of the West Riding, of Yorkshire,
called Lothersdale,
where he endeavored to maintain a wife and a large family of children,^
footnote:[At the time of his commitment he had ten children;
but they were not all dependent on him for support.]
by the laborious trade of constructing dry stone fences,
so common in that and other rocky parts of England.
He also occupied a small quantity of land; but with all his efforts, was but little,
or scarcely above need.
He was a man generally respected,
and about his thirty-first year had come forth in the ministry,
with the acceptance of his friends.
Notwithstanding his poverty,
he was nearly a constant attender of his monthly and quarterly meetings,
generally performing the journey on foot.
He twice attended the yearly meeting in London,
where I remember to have observed with pleasure the
simplicity of his manners and appearance.

In or about the year 1781, he, with several other Friends, was summoned,
at the suit of the Vicar of Carlton, in which parish he lived,
for not having paid his small tithes, which amounted,
as appeared by a subsequent inquiry, to about thirty-four shillings annually,
and were consequently far within the limits of the power of a warrant from a justice.
The magistrates before whom he appeared, judging the alleged demand exorbitant,
recommended a more moderate claim; but the prosecutor refused to abate,
and commenced an Exchequer process.
This, after long delays,
produced a decree which determined the average amount
of nine years`' tithe to be nearly as above stated.
The costs were above half as much more.
For not complying with this decree, in the Fifth month, 1795,
he was committed to York Castle, together with seven others, his neighbors,
and partners in the defense of the suit, and at length in imprisonment.
The names of his fellow-prisoners are, John Wormall, John Stansfield, Henry Wormall,
Henry King, John Wilkinson, William Hartley, and James Walton;
most of them in low circumstances,
and all of them dependent on their own industry for support: the withdrawing of which,
threw the families of some of them upon the charity of some of their friends for relief.

How long they would have remained prisoners is hard to say.
I do not recollect that any attempt was made to sequester their property;
and had this been attempted,
it is probable that the property of some of them
would not have been sufficient for the demand,
costs, and expenses.
At length, however, in consequence of a representation to the king,
stating the suffering case of several of his peaceable subjects,
and the continued delay of the plaintiff, a clause was inserted in an act of Parliament,
empowering certain magistrates to terminate this oppressive case;
by which means (except John Wilkinson,
who had died in the jail) they were liberated after something less than two years`' confinement;
and distraints were made on their property,
to the satisfaction of the examining magistrates.
It may be proper to add,
that they were kindly treated in the castle and generally
pitied by most that heard the case.

The friends of the quarterly meeting of Yorkshire,
in their testimony concerning this friend, observe that,
though he was much afflicted with infirmity of body
(for he labored under a pulmonary complaint),
and various deep exercises of mind, both before, during, and after his imprisonment;
yet he was enabled through all to evince much patience and resignation of spirit.
In the course of his religious labors, say they,
he had frequently to encourage others to a like dependence
on the arm of everlasting help,
as well as to strengthen friends in the support of their various testimonies,
particularly that for which he had so deeply suffered.
He departed this life the 28th of the Sixth month, 1803, aged about fifty-two years,
having been a minister about twenty-one years.

A few days before his departure, some friends called on him
previous to setting out for the quarterly meeting.
He told them that he had also thought of attending it; '`but,`' added he,
'`we are short-sighted creatures.`'
He desired his dear love to friends,
and remarked that he never felt more love to them than at that time;
and that he was easy, and resigned to the will of Providence,
who had been wonderful in goodness, and had supported him through many difficulties,
to his own admiration: so that he had to rejoice, even in tribulation.
He added, that whether it should please the Lord to take him at that time,
or to restore him again, he was easy as to the event.

Thus it appears that peace and love attended his close;
and where peace and love take up their abode,
it would not be an irreverent strain of expression to say, that heaven is begun.

Oh! that every awakened soul would daily seek after the sweet influences of gospel love!
It sweetens society; it begets its likeness in others; it excites gratitude;
and even if bestowed on the ungrateful (as says our dear Redeemer,
love`'s holy and exhaustless fountain, the rain falls on the just and on the unjust),
it brings its own sweet reward with it: for it attracts the approbation of God.
Where then will be contempt?
where the indulgence of evil surmisings, and hard thoughts?
where either studied or careless detraction?
where even the needless disclosure of real failings?
where the least place for any enmity?

These hurtful practices, and pride, the promoter of many of such practices,
will fall before the prevalence of pure Christian love; and surely,
when these are exterminated from the heart,
is it not so far prepared for its best and most sacred purpose,
to be a temple of the holy Spirit?
Amen!

[.asterism]
'''

RICHARD BAKER, of Dover, was born at Sandwich in Kent, the 26th of the Eleventh month,
1734.
His parents, who were of the Presbyterian persuasion,
were anxious for the religious education of their children, in which,
so far as relates to their son Richard, they probably were successful.
About the eighteenth year of his age his mind was closely
exercised respecting the concerns of his soul`'s well-being;
and in this state he joined the society called Methodists,
among whom he was held in great esteem,
particularly as a person who was endued with an extraordinary gift in prayer.
During his continuance in this connection, he was preserved in great humility,
and was earnest to press forward to the true rest.
Thus he became weaned from all dependence on external help,
experienced something of the true silence of all flesh,
and was gradually drawn into the simplicity of truth.

He joined friends about the twenty-third year of his age,
and was an exemplary member of our Society.
He was careful not to exceed the limitations of truth in his trade and outward concerns,
and was solicitous that his moderation should appear to others.
Living in a town where there are often advantageous contracts to be had from government,
and orders for the use of its establishments in that quarter,
he believed it best to decline one of which he might have partaken,
lest he should seem to weaken his testimony against war,
by seeking the profits arising from it.
Indeed, his mind was filled with hopes superior to those of gain;
and the animation of his very countenance, when engaged in religious service,
demonstrated his genuine devotion to the Lord`'s cause.
Nevertheless,
he conducted a considerable business in most of the various
articles necessary to the furnishing of a house,
and conducted it with reputation.

He was much bound to support the discipline of the Society,
and was a very frequent attender of the yearly meeting in London.
Being of a tender constitution, he was at various times much reduced in body,
and appeared as on the brink of the grave.
In particular, during the time of that meeting in 1779,
he became so enfeebled by a disease which appeared of the consumptive kind,
that he was obliged to leave the town,
and to retire to a village on the south side of it.
While he was at this place, our late friend Esther Tuke, of York,
(already mentioned in this volume) then in London, paid him a visit;
but the current of verbal consolation chiefly flowed from him to her,
and to two young people who bore her company; so that Esther,
who had been long a minister in much esteem and acceptance, had to remark that,
as in the temple of old, the glory of the Lord so filled the house,
that there was no room for the priest to minister.
At this time Richard Baker had not come forth with
a public testimony in our meetings for worship.

To another visitor he spoke thus: '`Although I might mention severe pains of body,
yet I have felt more peace and comfort,
and have had more clear openings into that which unlooses the seals,
than ever I had in time of health.
I have endeavored to be fully resigned to the divine disposal, and may say,
with the truest sincerity,
that in that season I have desired more that my feet might be turned into,
and preserved in, the path of the righteous,
than to experience the joys of the kingdom it leads to.
Although I have formerly wondered at the necessity
of loving one`'s neighbor as one`'s self;
yet I have now thought if there was one person in
the world who had more disregard for me than another,
that my love has gone out the strongest to that person.

'`As to my present indisposition, I feel a resignation therein,
which is productive of a peace and comfort that is inexpressible;
and believe if it pleases the Lord to restore me to health,
it will be for the sake of others; but that I leave.
I have seen the state of leaving children to the Lord`'s care,
and that the widows should trust in him.
If anything has lain with more weight than another, during my indisposition,
wherein I have been led to trace back the steps of my life to my very childhood,
it is the not having earlier experienced this state of resignation,
and love to my neighbor, in its full extent.
Although it has been, and is thus with me, it may yet be otherwise;
and this may be preparative to a trying dispensation I may have to pass through; for,
"`Whom the Lord loves he chastens, and scourges every son whom he receives.`"
All care and concern respecting my outward affairs are taken away;
and as to my going or staying here, I leave to my friends, who can judge best for me.`'

On his arrival at home,
he thus wrote to one of the young people who had
accompanied Esther in the before-mentioned visit;
and though his words are certainly not Dying Sayings, yet,
as they show the state of his mind when death seemed at hand,
they are perfectly congenial to the design of this compilation.`'

"`The great decrease,`' says he, '`of those disorders which were lately so prevalent upon me,
and the daily increase of strength which I have been favored with,
for four or five successive days,
give great cause to expect it may seem meet to Divine Providence to answer
those fervent desires my friends have expressed for my recovery:
although I must confess the prospect thereof does not give me any pleasure;
not expecting I shall ever see a time wherein my
spirit will be more subject to the Divine will,
nor +++[+++more]
united and leavened into that power which is out of the
reach of all the united powers of darkness to molest,
or death itself to separate from, than favored to witness in the late illness.
However,
being still mercifully preserved in a sense that every dispensation
of Providence to us is ordered in unerring wisdom,
I feel my mind stayed in a good degree of resignation,
and willing to be brought yet again to be a companion with the tribulated flock of Jesus.
I have only a desire to be preserved in the lowly-minded, watchful state,
where the ear is preserved open to hear the voice of the true Shepherd,
and ability to follow in that which is manifest is witnessed:
that so his great and sacred name may yet be glorified, who over all is worthy,
says my soul.
A sense remaining of the many mercies I am favored with, both spiritually and temporally,
makes everything so easy, that I scarcely dare to call my indisposition an affliction.`'

About the year 1780, and the forty-sixth year of his age,
he came forth in the work of the ministry;
in which service he seemed clothed with universal love;
and as his deep experience was the means of enabling him to say,
with the beloved disciple, "`That which we have seen and heard,
declare we unto you,`" his labors were often consolatory to the spiritual traveller.
His service was chiefly confined to the limits of his own quarterly meeting,
and the neighboring ones, except one visit to Friends in the west,
and one in the north of England, also two journeys into Wales.

His decease at length was occasioned by an injury received by a fall.
He lived in that part of Dover which is built near the foot of the Cliff;
which seems almost to overhang the street, and suggests the idea of ruin,
should any considerable part give way.
On this cliff, accessible by numerous steps, his garden was formed;
and as he was on the stairs leading to it, on the last day of the year 1803,
a part of the chalky cliff fell, with a quantity of earth and some timber,
hurrying him along with them, and overwhelming him.
It seems wonderful that he was not immediately killed;
but he received an injury irremediable by human art.
The bladder was hurt,
and a paralysis also ensued from the bruises occasioned by the tremendous fall;
but the mind was unimpaired; and its faculties, calmed by resignation,
and brightened by love, were still employed in thanksgiving and praise.

On the evening of the fall, he expressed the quietness of his mind; and,
inquiring for a Bible, desired that the 32nd Psalm might be read to him:
repeating the 2nd verse, "`Blessed is the man unto whom the Lord imputes no iniquity,
and in whose spirit there is no guile.`"
The whole of that and the following one being read, he said, "`This poor man cried,
and the Lord heard him, and saved him out of all his troubles.`"
The 34th being also read, he said, with great tenderness,
'`I have felt much refreshed from some of these passages.
I have neither fear nor terror.
I feel quite easy respecting my situation.
My mind is centered in God.
I ask for patience and resignation under this trial.
Surely mercy and goodness have followed me all the days of my life.`'

The next morning, First-day, and the first of the year 1804,
being asked if he lay comfortably, '`My body,`' said he,
'`is as comfortable as you can make it;
and my mind is comforted in a well-grounded confidence
in the mercy of God in Christ Jesus.`'
In the evening he said to his daughter, '`Mary, where is that passage,
"`Many shall hear and fear, and trust in the Lord?`"
Wonderful deliverance;
marvelous indeed!`' In this it is probable that he
alluded to his escape from immediate death,
under the fallen fragments of the cliff.
'`It may be,`' he continued,
'`to prove an encouragement to some poor mind to trust in this preserving power,
that I am on this sick-bed.`'
Being told that the passage was in the 40th Psalm, the whole was read to him;
and he was particularly affected with the verses from the 8th to the 12th, inclusive;
"`I delight to do your will, O my God: yes, your law is within mine heart.
I have preached righteousness in the great congregation: lo,
I have not refrained my lips, O Lord, you know.
I have not hid your righteousness within my heart:
I have declared your faithfulness and your salvation.
I have not concealed your lovingkindness and your truth from the great congregation.
Withhold not you your tender mercies from me, O Lord;
let your lovingkindness and your truth continually preserve me.`"
After this he said,
'`I have yesterday and today been looking over Friends in several places,
and think I never felt greater love than at the present time.
I wish they may be preserved in the truth; and I have earnestly desired,
whatever I suffer, I may not dishonor the great name.
My mind is carried above outward things.
I desire not to boast; but at present I feel no cloud in the way.
It is a great favor to be so comfortable, and feel the divine presence.
When that is withdrawn, then am I troubled.`'
Several times he exclaimed, '`I rejoice in tribulation.`'

On Second-day morning, under sensations of great weakness of body,
his mind seemed so strengthened, enlarged, and centered in divine life,
that like the good scribe, he brought out of his treasury things new and old.
He expressed again his entire resignation to the dispensation allotted to him.
'`I am persuaded,`' said he, '`there was a divine hand in it,
and that he could have prevented it; but his ways are mysterious.
What an inexpressible favor, to feel no dread of death! What poor creatures we are.
I know I am a poor creature to do anything; but through Christ strengthening me,
I can do all things.
My sufferings are great; but what are they compared to Job`'s;
and what did the dear Savior suffer!`' In the latter part of this day he said,
'`How sweet it is to feel that charity that thinks no evil,
but puts the best construction upon all things.
I look over friends with much sweetness and love; never more so.
I feel the greatest confirmation that "`God is love,`"
and that they that dwell in him dwell in love.`'

After he had been up to have the bed made, his married daughter, who was standing by him,
inquired how he felt.
He answered, '`I am more easy now; but such a severe struggle of pain I had,
when sitting in the chair, as was hard to bear: but I have much to be thankful for.
We must labor after resignation, not knowing how the event may terminate.
Labour to be resigned; often feel after that which will support in the day of trouble,
and the Lord will bless you.
Ah, the fading enjoyments of this world!
They cannot afford comfort in a trying day.
If it is the will of God, I had much rather die than live.`'

When this daughter, who lived at some little distance in the town,
took her leave of him for the night, he said, '`Farewell, dear child.
Don`'t fret yourself about me, nor be too anxious; but endeavor to be resigned,
and give up cheerfully.
If you grieve, the dear babe will suffer.`'

The next morning, he appeared so much more ill that his wife, his son-in-law,
and his two daughters, were with him at an early hour.
To these, or some of them, he said, '`I know you all, and I love you all.
I have nothing to communicate that ought to be otherwise.
I am perfectly satisfied.`'
Then he addressed his son and daughter, saying, '`Be watchful, and the Lord will bless you.
Beware of the world, and its delusions.
It often promises what it cannot impart.
I have nearly passed through life;
and I have found no refuge like that of turning in to God,
and placing my confidence in his never-failing arm of power.`'

'`Now, Lord,`' he added, in the voice of supplication,
'`if it be your will, receive me into a mansion of glory.`'
More he said, which was not distinctly heard,
after which he desired to be removed a little, and said, '`I need attendance now;
but I shall not need it long, if it is the will of the Supreme Being.
While the hand of Providence is with us, we need not sink.
That has been my support, a never-failing support to turn to God.`'
Then he seemed afresh engaged in supplication;
but as it was evident that he was in a suffering state,
his daughter inquired of him whether he was in pain.
'`Yes,`' he replied, '`not so much now; but I have not been free all night.
No, no.
They do best that seek after happiness within.
I have found it so in the depth of trials.
There has been no refuge, like that of turning in to God.`'
After a little pause, he added, '`I lay down my head in peace.
God is magnified.
Religion is glorified.`'

About this time, his medical attendant was sent for;
and to him also Richard expressed his resignation and composure of mind.
'`Doctor,`' said he, '`I would not have you make any extraordinary effort to keep me alive.
I had much rather die, than continue in this world.
My outward affairs are settled.
I have no concern about anything.
My mind is wholly redeemed from this present world,
in a greater degree than I ever could have expected.
I die in peace with all men.
I am at variance with no man;
and I die in the hope that when this tabernacle of clay is dissolved,
there is a mansion laid up for me in a better world.`'
A Friend who dwelled in the town coming to see him at his request,
after imparting salutary advice, and testifying his love, he went on,
'`I see the hand of Providence in my present situation.
Some may say one thing, and some another: but it matters not.
I am perfectly satisfied with the will of God.
I looked for no other than immediate death;
but it pleased Infinite Wisdom to spare my life a few hours,
that I might speak to my relations and friends,
and prove an encouragement to some present (several were in the room),
and I have a hope it will be a means of bringing glory to his name.
Many will hear, and fear and trust in his name.`'
After some other matter, he added,
'`I have often thought of late on the words of the apostle, "`I beheld, and lo,
a great multitude, which no man could number, of all nations, and kindreds, and people,
and tongues, stand before the throne.`"
'`You,`' addressing some present, '`are likely to be the support of this little meeting.
Be faithful, and your labors of love will be blessed.`'

Several other comfortable and encouraging sentences
fell from him in the course of this day,
among which was a message to an absent, though intimate Friend,
to whom his daughter was writing a letter.
'`Perhaps,`' said he, '`it may be an encouragement to tell him, to hold on in well doing.
The prize is sure to them that hold out to the end.
Tell him I am carried above all trouble;
out of the reach of that which is troubled about a future state.`'
He desired one of his daughters to pray for his release;
and he said to his children standing by, '`I have done what I could for you;
and my prayers have been heard.
I have watched over you with a fatherly care.
My blessing is with you.
It is pleasant to see tenderness prevail.
I love to see you all about me, my sweet family.`'

But though this dedicated servant of the Lord had
thus so far triumphed over the fear of death,
and as it were exulted at the prospect beyond the grave; it seemed meet to infinite,
unerring, and unsearchable wisdom, to permit him one conflict more.
About four on Fourth-day morning,
notwithstanding he had reposed in some degree of comparative ease, his pains returned,
and seemed to increase as the day drew nigh.
His patience and his faith were tried as it were to a hair`'s breadth.
He often exclaimed, '`Dearest goodness;`' but in this season of deep probation,
the spirit of supplication did not seem with him as at other times.
In his anguish he said, '`If I could but discern the face of death,
if at ever so great a distance, it would afford a glimpse of hope.`'
This, however, shows that still it was not death nor futurity that he feared;
but he added, '`But this seems hid from me.`'
Then turning his soul to his long-accustomed source of support, he uttered this petition.`'
Most gracious God!
Permit me not to lose my confidence in you.
Be my support in this trying season.`'
About seven he appeared desirous to know the medical attendant`'s opinion,
and being informed that there was a probability of his release before long,
he exclaimed with great energy, '`And is there such a prospect?
then am I comforted.
Does the doctor say so?
then am I thankful.`'
From this time his mind seemed much relieved; but his pain for a while continuing great,
he said, '`My sufferings are very great,
but it is my heavenly Father`'s will that it should be so.`'

His close, however, was not immediately at hand.
Towards noon fomentations were applied, which gave him so much relief,
that his fond wife was induced to tell him that she began to have some hopes;
but he replied, '`I am sorry for that.
I want to go home.`'
He afterwards said, '`Be tender to traveling friends.
They have their dippings;
and if they did not sometimes meet with kind friends by the way,
their difficulties would be great indeed.
I have known the difference in my passing along.`'
And he also added, after a little pause,
alluding to that encouraging passage of Matt. 10:42,
"`No one who hands a cup of cold water to a disciple,
from the love they feel to the cause, will go without reward.`"

In the afternoon he said, '`No ease,
no intermission now;`' then with hands clasped together, '`O my God, be my helper,
as you have been my helper.
Grant me patience to endure this suffering.
I have been accustomed to live by faith from day to day,
but now it seems reduced to so short a space, that I cannot see from hour to hour.`'

In the evening his pains seemed a little alleviated;
and his daughter expressing a hope that he would pass quietly away, he replied,
'`If it may be so, it will be a mercy.
A few minutes`' ease, what a favor!`' His strength now failed very fast,
and though his bodily afflictions did not appear much to abate,
yet his mind seemed to continue centered in that holy power
which enabled him to bear them with great composure;
and early on Sixth day morning, the 6th of the First month, 1804, without a struggle,
a groan, or even a sigh, he gently passed away.
