== Chapter 6

[.chapter-synopsis]
* Mary Pooley
* Ralph Baimbridge
* Henry Kite
* Dorothy Owen
* Job Scott
* Abigail Knight
* Elizabeth Drinker
* Samuel Spavold

MARY POOLEY, daughter of William and Mary Pooley, of Tooley Street, Southwark,
was born the 11th of the Fifth month, 1772.
Her parents were concerned to bring her up in plainness and sobriety;
and their endeavors for her preservation therein,
and from the many evils which are in the world, were not ineffectual.
Although of a lively disposition, she was religiously inclined in very early life;
she loved the truth, and the friends of it, and was of a steady deportment.

About the eighteenth year of her age,
she seemed more frequently indisposed than heretofore; and,
although it did not appear unlikely to others that she might still live to see many days,
yet she seemed to have a sense given her that her
stay in this world would not be to an advanced age;
and her indisposition increasing, became a settled decline.
During this trying season her patience was remarkable; she was preserved from murmuring,
and seemed cheerful in spirit, saying, "`Through mercy I do not repine.`"

Many expressions she uttered in the course of her illness,
tending to show the resignation of her mind,
and quiet acquiescence with divine permission.
About a month before her decease, her father asking her how she did, she replied,
"`I seem to be gradually going.
I have remembered the words of Job, '`The Lord gives and the Lord takes away,
blessed be the name of the Lord.`'
It is best to be resigned.
Do not grieve, dear father;
the Lord be with you;`" and again advised her parents to give her up freely, saying,
"`We must part some time or other, and I cannot go better than well.`"

About two weeks before her decease, after having made several solid remarks,
she said to this effect,
"`There is a language that I have often thought of in the time of health, which is, '`O,
that I might walk in all things consistent with the truth I make profession of.`'`"
And at another time, nearer her end, she said, "`I think I may truly say,
I have not murmured in all this illness.
The Lord is my refuge.
I am comfortably resigned to his divine will, and seem to have nothing to do but to die.`"

She continued a few days longer,
during which she uttered many expressions to the same effect as the foregoing.
The day she died, she desired that her father and brother might be sent for,
with whom she had a solemn season; and afterwards appeared serene,
and given up to the Lord`'s will.
She quietly departed, the 12th of the Eleventh month, 1792,
aged about twenty years and a half; and was interred the 18th,
in Long Lane burial-ground, after a meeting held at Horslydown.

[.asterism]
'''

RALPH BAIMBRIDGE, a member of Newcastle meeting, having,
through a variety of dispensations,
been convinced that all outward and ceremonial worship was unavailing,
and that nothing short of the pure, living, eternal substance, Christ Jesus,
the Rock of ages, would truly profit the soul,
he became a lively example of the efficacy of the Divine principle as professed by us,
joined our Society about the twenty-fourth year of his age,
and after a short time received a gift in the ministry.

It does not appear he was much engaged out of the compass of his own quarterly meeting;
yet he sometimes went to the half-yearly meeting in Scotland,
the yearly meeting in London,
and the meetings in some neighboring counties in his way to and from the yearly meeting.
By some minutes which he left behind,
it appears he was deeply baptized into the states of the people as he passed along,
and was generally enabled to discharge his duty faithfully,
and to reap the reward of peace.

His last illness was tedious and painful,
but he bore it with exemplary patience and fortitude.
He saw with composure the period of his life approaching;
and though preserved in a calm resignation to the Divine will,
he sometimes expressed a desire to be dissolved,
being enabled to look forward with a humble confidence,
from the retrospect of a well-spent life, to the enjoyment of its sure reward,
an incorruptible inheritance with the saints in life.

He was favored to the last with the use of his mental faculties;
and at different times uttered weighty and edifying remarks.
He signified, near the beginning of his confinement,
that he had endeavored to discharge his duty faithfully,
and said he saw nothing more for him to do or to undo.
At one time he expressed himself as follows:
"`Though we hear and read of people at these times having great openings, sights,
and revelations, seeming to be enraptured with Christ`'s love, and his meeting them,
it has not been so with me, but I have been in a quiet rest, in a composed waiting state,
feeling a covering of that which was my morning light;
that which called and created me anew, and placed me in a state of sonship.
He is yet with me, and I know that where he is, I shall be also, even as he is.
As it is not likely I can do it myself again, I would wish my friends to be informed,
that I rest in the same faith in that which gathered us to be a people.
I feel him to be yet with me, who has redeemed me out of all distress;
the God who has fed and kept me all my life long.`"

He departed this life the 27th of the Fourth month, 1793,
and was buried the 3rd of the Fifth month following, aged about sixty-four,
and a minister about forty years.

[.asterism]
'''

HENRY KITE, of Norton, in Hertfordshire,
was but little known to Friends in his early life,
being brought up in the National Church,
and for some time frequented the meetings of the Methodists.
Being favored with an awakening visitation,
he was brought to see the exceeding sinfulness of sin,
and to feel judgment on the transgressing nature in him;
and by obedience to these discoveries he became measurably reformed in life and conduct.

In the year 1768 he frequented our religious meetings, sitting therein in a weighty,
solid frame; and his general conduct being consistent,
he was in the year following received as a member.
A faithful discharge of the duties of his station, which was that of a servant,
procured the esteem of his employers;
who readily made way for his attendance of meetings for worship and discipline,
wherein he was very exemplary.

He was a man of a meek and humble spirit, and although not large in testimony,
yet he grew in his gift, in the exercise whereof he was plain, lively, and edifying,
reaching the witness of truth in the heart.
He was useful also in the discipline of the church,
having been frequently engaged therein to the satisfaction of his friends.
It was his lot to meet with several close trials, which he bore with Christian fortitude.

During his last illness, he said, "`My poor body is much afflicted,
but I am comfortable in mind, which I esteem a great favor.
I have paid my visit to the yearly meeting, and have no cause to repent,
for I believe I was in my place in so doing.`"
And at another time, to his wife, "`My dear, do not weep for me,
although my body is in a suffering state, my mind enjoys a perfect calm,
and I have no fear of death.`"
On being asked by one of his sons how he was, he replied,
"`You see your poor father laboring under great bodily affliction,
but I am preserved with a still, quiet mind,
and I feel the Lord`'s goodness graciously extended to me.`"

To his daughter he said, "`My dear, a few words have sprung in my mind, very comfortably;
which are, '`The Lord is risen in his holy temple,
let all the earth be silent before him.`'
What can the temple be but the body?
O, what a comfort to feel the Lord`'s goodness so graciously extended to me,
a poor creature.
I can truly say, I have given all up.
I have committed all into the hands of a merciful God, to do with me as he pleases:
either to take me, or restore me to health; I have no will in it.
O, what a favor is this, to be resigned either to life or death!`"

At another time, "`I have to remember that '`the Lord is a strong tower,
whereunto the righteous flee, and are saved.`'
I can with great thankfulness say to my God, '`I have fought the good fight,
and have kept the faith,
henceforth there is laid up for me a crown of righteousness.`'`" The day before he died,
among other things, he said, "`I am clear of the blood of everyone.
I feel my disorder making its progress,
and it appears to me that I shall be removed in a little time.
My bodily affliction is great, but the sweet peace of my mind is far greater.
O, how I feel the sweet influence of heavenly love!`"

He departed this life the 15th of the Sixth month, 1793, at Norton,
aged about fifty-five years, and was buried on the 21st of the same,
in Friends`' burial-ground at Baldock; and a minister about twenty-four years.

[.asterism]
'''

DOROTHY OWEN, of Dewispren, near Dolgelly, in Merionethshire,
was the daughter of Rowland and Lowry Owen, of the same place.
She was educated in the profession of Friends, notwithstanding which,
she in her youth accompanied other young people in vain and unprofitable amusements.
But about the sixteenth year of her age, being favored with a visitation of divine love,
she became sensible of the errors of such ways; and,
by a strict attention to the reproofs of instruction,
and submission to the operation of truth,
she experienced redemption from the love and spirit of this world.

About the twenty-third year of her age, she appeared in a public testimony;
and her conduct being consistent therewith,
she was made instrumental to the convincing and gathering of many to the
principle and profession of the truth in the neighborhood where she resided;
where, from removals and defection,
the members of our Society were reduced to a very small number.

The sweet savor of her zealous, humble, meek example, and her dedication of time,
faculties, and property, though in low circumstances,
to the glory of God and the good of her fellow creatures,
had a powerful tendency to enforce the doctrine she preached.
She was remarkable for her diligence in the attendance of meetings for worship and discipline,
from which neither distance nor weather kept her back, while of ability;
and she frequently went nearly forty miles on foot in that mountainous country,
to attend the monthly meeting:
even when the inclemency of the season rendered it not only difficult but dangerous.

She contented herself with the least expensive manner of living and dress,
in order to have the more to distribute to the necessities of others;
tenderly sympathizing with the poor inhabitants around her:
and so bright was her example, that one, not in profession with us, declared,
"`Her conduct preaches daily to me.`"

Her last illness was lingering and painful, which she bore with exemplary patience,
and was eminently favored with divine peace,
so as sensibly to affect and gather the minds of those who visited her,
into a sense of the same blessed influence.
Her prospect of future happiness was unclouded; and she said very near the conclusion,
"`The arms of divine mercy are wide open to receive me.`"

She died the 12th, and was buried in Friends`' burying ground at Tyddyn-y-Gareg,
the 17th of the Seventh month, 1793, aged about forty-two years;
and a minister about nineteen years.

[.asterism]
'''

JOB SCOTT, of Providence, in Rhode Island,
was removed by death while on a religious visit in Ireland.
He was a man of strong understanding and quick discernment;
but still more remarkable for having experienced
the vigorous faculties of his mind reduced,
in no common degree, under the humbling power of truth.
When young, he was, according to his own account, much addicted to levity of conduct;
and it is probable that the close exercises which he afterwards passed through,
and the scrupulous disposition of mind in which for some time he appeared to live,
were as the necessary inflections of the crooked wand to the contrary side, in order,
at length, to reduce it to perfect straightness:
wisdom even tormenting with her discipline, and at length returning the straight way.

He arrived in London in the First month, 1793,
and labored diligently in the occupation of his talent as a gospel minister,
in and near the city, until the latter end of the Third month;
when he proceeded leisurely to the Welsh yearly meeting, held at Carmarthen.
On this occasion, as well as at the succeeding one of the Bristol yearly meeting,
his business seemed to be that of leading the people from a reliance on preaching,
by becoming himself, throughout, an example of humble silence.

He afterwards attended the yearly meeting in London, in the last sitting of which,
he delivered some memorable hints respecting the commotions then prevailing in the earth;
and pointing to the path in which the righteous, in such seasons of overturning,
might tread with safety.
After this he went, without much delay, to Ireland;
to the meetings of which he paid a general visit,
and returned to Dublin in the Eleventh month;
but not finding himself clear of a belief of more service in that country,
he went to Ballitore, at which place he fell sick with the small-pox.
He asked several questions respecting that disease;
and afterwards very emphatically declared,
"`It is no matter what is the disorder;`" and in a little while added,
"`Its being that or any other, does not at all alter my feelings.`"

A friend observing that his getting well through it would be a great favor,
he replied with a smile, "`Whichever way it is, I hope I shall get well over it.`"
He also said, "`There is an eternal arm underneath each of us,
which is sufficient to bear up and support; and will do it,
as far as it is needful we should be supported;
and I have long been confirmed in this sentiment,
that nothing could possibly happen that would harm or injure me,
while I kept under the divine influence.`"
Some time after he said, "`Though I am not without some considerable bodily pain,
yet I feel such a portion of that good which is infinite,
that it does not seem worth mentioning.
If there was no greater enjoyment hereafter,
the present would be a state truly desirable, through a never-ending eternity: and yet,
the fulness is still more desirable.`"

To relate all the instructive and comfortable expressions which he uttered,
would swell this account beyond the proposed limits.
A week before his close, dictating a letter to his relations and friends,
after mentioning that his distress of body, through extreme difficulty of breathing,
had for a short time been almost equal to anything
he could suppose human nature capable of supporting,
he said:

[.embedded-content-document.letter]
--

Just now, and for several hours past,
I have been almost as easy as at any time in my life; I think certainly,
never more so in my mind.
I feel no kind of alarm; but the end result is certainly very doubtful.
I feel easiest to address you in this manner,
principally that you may know that my mind enjoys a fulness,
in that which removes beyond the reach of all sorrow.

I suppose my love was never in a state of greater enlargement,
or less tinctured with selfishness, to all my relations and friends the world over.
My desire for my children`'s substantial growth in the truth,
and strict adherence to all its discoveries, to the close of their days,
is by far the principal wish I have for them.
Out of the enjoyment of a good degree of this precious inheritance,
I know of nothing in this world worth living for.
You that know it, suffer nothing, I most cordially beseech you,
ever to divert your minds from an increasing and fervent pursuit after the fulness of it,
even unto "`the measure of the stature of the fulness of Christ.`"

--

[.offset]
Afterwards, in addition to the foregoing letter, he added:

[.embedded-content-document.letter]
--

My spirits are under little or no depression at all.
Perhaps I never saw a time before, when all things not criminal,
were so nearly alike to me, in point of any disturbance to the mind.
I do not know, but that when awake, and capable of contemplation,
I nearly rejoice and give thanks in all.
When I verge a little towards sleep, I am all afloat, from the state of my nerves; and,
from the extreme irritation, forced almost immediately,
and with very unpleasant sensations, from beginning repose; but, through all,
the soul seems deeply anchored in God.

Many and painful have been the probationary exercises of this life to me.
Ah! were there probability of strength, how I could enlarge;
for my heart seems melted within me in retrospective view.
But all the former conflicts, however grievous in their time,
are lighter now than vanity;
except as they are clearly seen to have contributed
largely to the sanctification of the soul;
as they are remembered with awfulness and gratitude before him,
who has not been lacking to preserve through them all;
and as they seem likely to introduce, either very shortly, or before a very long time,
to an exceeding and eternal weight of glory.

My very soul abhors the idea, that a Christian can ever be at liberty,
while under the influence of heavenly good, to seek, or even desire, much wealth;
though this disposition, in direct opposition to the life and doctrine of Christ,
has gone far towards the destruction of true spiritual religion, I believe,
in almost every religious society in the world.

--

As nature became more oppressed with the disease, he observed it, and said,
that if ever he rose above the present weight which he felt, and seemed sinking under,
it would be through the marvelous display of eternal power and influence.
He requested that if he were removed,
some further particulars might be transmitted to his friends at home; adding,
in substance, "`The Lord`'s will is blessed, and I feel no controversy with it.
It is the Lord that enables me to coincide with his will,
and to say amen to all the trials and conflicts he permits to attend us.
I do not expect to have much to communicate in the course of this disorder,
or that my strength will admit of it;
but my mind is centered in that which brings into perfect acquiescence.
There is nothing in this world worth being enjoyed out of the divine will.`"

Two days before his decease, he said, "`I have no fear;
for '`perfect love casts out all fear; and he that fears is not perfect in love.`'`"
The same day he prayed thus; "`O Lord, my God,
you that have been with me from my youth to this day, if a man who has endured,
with a degree of patience the various turnings of your holy hand,
may be permitted to supplicate your name, cut short the work in righteousness,
if consistent with your holy will.
You who have wrought deliverance for Jacob,
evince that you are able to break my bonds asunder, and show forth your salvation,
that so my soul may magnify your name forever and ever.`"
And after a short pause, wherein he seemed to feel the earnest of his petition, he added,
"`So be it, says my soul.`"

He frequently gave a word of caution to such as visited him;
and after affectionately addressing one Friend he said,
"`I am waiting patiently for the salvation of God; do you wait with me.
I have no desire, nor the shadow of a desire, to be restored.
I hope the doctors will soon find they have done their part.`"

The evening before his decease, he said, "`You may tell my friends in New England,
and every part of the world,
that never did my soul bless the Lord on account of any worldly enjoyments, as I do now,
in the blessings felt by me to be contained in the prospect of a very speedy release.`"
At another time he said,
"`Some of my wishes are centered in as speedy release as
may be consistent with the will of our heavenly Father;
and an admission, which I have no doubt at all, not in the least degree, of obtaining,
into that glorious kingdom, where the wicked cease from troubling,
and the weary soul is eternally at rest.`"

After another lively declaration, he added, "`I feel,
and I wish you to feel for and with me, after the eternal rock of life and salvation;
for as we are established thereon we shall be in the everlasting unity,
which cannot be shaken by all the changes of time,
nor interrupted in a never-ending eternity.
I do expect considerable derangement will now take place.
It is no discouragement to me, and ought to be none to those who trust in the Lord,
and put no confidence in the flesh.`"

Early in the day in which he was removed, under much suffering, he petitioned, "`O, Lord,
if it be consistent with your holy will, let loose my bonds,
and send the moment of relief to my poor body and soul.`"
Afterwards he said, "`We cannot approve or disapprove, by parts,
the works of Omnipotence rightly; we must approve the whole, and say,
'`Your will be done,`' in all things.`"
And a short time after, his bodily afflictions being great, he said,
"`I find all things must be endured.`"

The extremity of his pain sometimes occasioned him to fear lest he should be impatient;
and he said to the physician, "`Make great allowance for me,
my distress is nearly as much as is supportable by human nature.`"
The physician saying there was a probability of his being very soon released,
perhaps in an hour or two, he replied, "`If so,
the Lord`'s name be blessed and praised forever.
I had much rather it were so than otherwise;
for some time I perceived it hastening fast;`" adding,
"`The desire of my heart is the great blessing of time, and the consolation of eternity.`"
After a while he said to a friend, "`Guard against right hand errors.
Let self be of no reputation; trust in the Lord, and he will carry you through all.`"

He died the 22nd of the Eleventh month, 1793, at the house of Elizabeth Shackleton,
at Ballitore; and was buried the 24th in Friends`' burial-ground there.
He was about forty-three years of age.

[.asterism]
'''

ABIGAIL KNIGHT, daughter of Joseph Knight, of Messing, in Essex, being taken ill,
it was soon perceived that her disorder tended to her dissolution.
Her father tenderly acquainted her with the prospect.
She expressed that she had not much desire to live;
that she did not see anything here to stay for; and, if she might go well,
that she was willing to die.
She was under great exercise of mind for some days, doubting her future happiness;
saying to her father she had done so many things she ought not to have done,
and wishing she had minded more the hints he had frequently given her.

On his telling her he had no doubt from the feeling of his mind,
that if she was removed by the present illness, it would be well with her,
she expressed her doubts and fears, continuing under great exercise for some time,
saying, "`I feel so much pain, that I cannot continue long, and I do not feel easy.`"
But after some days she signified she felt some ease,
and hoped her sins would be forgiven her; and that she did not fear death,
but hoped to be favored with a more clear evidence before she departed.

Desiring to be with her father alone, she told him of the exercise of her mind,
which she had felt for attending religious meetings so carelessly.
That she thought it was mockery to sit in such an indifferent manner,
and let the things of the world take up the attention of the mind;
for which she had felt uneasiness, as much, she thought,
as for anything she had done amiss.
She signified that when at times she endeavored to be more gathered in her mind,
the enemy got in and obstructed it;
and that she found herself so weak through unwatchfulness at other times,
as not to be able to withstand his suggestions.
After this conversation she said she felt herself more easy.

Observing what a fine day it was, she said she had thought of one who said,
"`How gloriously the outward sun does shine!
So does the Son of righteousness shine this day on my soul;`" and
hoped she could in measure adopt the language as her own;
that the things which stood in her way seemed gradually removed;
and that she hoped to be favored with a more clear evidence before she departed.
To her sister she said, "`I have but little time,
but if I had my time to spend over again,
I should spend it very differently;`" and that if she might
have the least place in the kingdom of heaven,
it was all she desired; which she thought would be granted.

In the evening, a lad, a member of our Society, coming into the room,
she desired he would take warning by her, saying, "`I little thought, three weeks ago,
I should be so near death as I am;
and you do not know how soon you may be so near;`" asking him if he did not think
he should be in great trouble if he was brought unto such a situation.
She advised him to use the plain language, and plainness of dress;
that she had been too much inclined to dress, but felt great uneasiness,
and hoped for forgiveness; but she added, "`I believe I shall be happy.
I feel so easy in my mind;`" and added,
"`What a fine thing it is to have peace of mind upon a dying bed.
The nearer I am to the close, the more easy and clear my way seems.
I do not dread death,
but seem as if I could meet it with a smile;`" that it was a great favor,
for which she could not be thankful enough;
and that she could not have thought it possible for
her to find forgiveness in so short a time.

Towards the conclusion she signified the sting of death was taken away,
and added pleasantly, "`I think tomorrow, or next day, will finish here.`"
The next morning her father going to speak to her, she seemed quite calm,
and in a sweet frame of mind; and said, she loved to be still;
she felt her heavenly Father near, as an arm underneath,
and often admired the goodness and mercy of the Almighty to her,
in so soon removing things which stood in her way.

About ten o`'clock the same day she was taken with the pains of death,
which being hard to bear, she besought the Lord to give her patience to bear them.
About fifteen minutes before she departed,
when it was expected she would have spoken no more, she said, "`Lord Jesus,
receive my spirit.
Lord, take me to yourself.`"
Soon after, she said, "`Farewell all, in the Lord; my pain will soon be over,
the gates of heaven are open to receive me; the time is almost come.`"
Soon after she departed, on the 24th of the Second month, 1794,
in the nineteenth year of her age.

[.asterism]
'''

ELIZABETH DRINKER, wife of Daniel Drinker, of the city of Philadelphia,
being drawn in gospel love to visit the meetings of Friends in this nation,
arrived here about the Seventh month, 1793.
After visiting the meetings in the city of London, she proceeded into Kent, Sussex,
and the western counties, as far as Falmouth, returning through Bristol to London.
Though frequently tried with indisposition of body,
she was strengthened in her gospel labors to the comfort and edification of many,
being concerned to wait for, and move under, the fresh arisings of divine life.

In the Fourth month following, though in a declining state of health,
she visited the meetings of Friends in Hertfordshire, etc.,
but her complaints increasing, she stopped at Staines, in Middlesex, nearly six weeks.
While at this place she expressed to a friend an
apprehension that her time would not be long in mutability,
and at the same time mentioned, that as she sat in the meeting on First-day morning,
though she had nothing to communicate to others,
and part of the time felt low and discouraged, yet, towards the close,
her mind was comforted in the fresh revival of those expressions of the prophet Habakkuk:
"`Although the fig-tree shall not blossom, neither shall fruit be in the vine;
the labor of the olive shall fail, and the field shall yield no meat;
the flocks shall be cut off from the fold, and there shall be no herd in the stall;
yet will I rejoice in the Lord, I will joy in the God of my salvation.`"

She reached London the 18th of the Sixth month,
where for some time she appeared under great conflict of spirit; being very desirous,
if consistent with her Master`'s will, to return to her beloved connections and native land.
But this trying dispensation was permitted to pass over; and,
some time before her dissolution, she seemed relieved from much anxiety respecting them;
and was favored to bear her suffering with great patience,
evincing true Christian resignation and acquiescence in divine appointment.

She attended several meetings under great bodily weakness;
and her last public testimony was at Westminster meeting,
where she stood up with these words, "`Precious, very precious,
in the sight of the Lord is the death of his saints;`" on
which she enlarged instructively and encouragingly.

During her confinement she was led to speak instructively to those about her;
at one time nearly in these words: "`To look back, the world appears trifling and vanity;
and if fresh trials come, and the storm be permitted to beat as against the wall,
it is good to trust in the Lord, who, in gloomy seasons,
is the protector of those that fear him.`"
After encouraging those present to greater dedication,
she said that the highest anthem that could be sung was, "`Your will be done.`"
At another time she said she believed it was right
that she had given up all and left home;
whether for life or death, she must leave.

The last few days of her life she was much engaged in supplication,
uttering many broken sentences, which, though not fully gathered,
were expressive of the state of her mind,
and breathed the language of consolation and praise.

When near the close, her spirit seemed supported above the last conflict; and,
with an animated countenance, she said, "`Oh,
the beauty! the excellent beauty! the beautiful prospect
in view!`" Then lifting up her hands,
she appeared for some time in sweet silent adoration; after which she spoke but little,
and with difficulty; yet she appeared sensible.
She expired in the evening of the 10th of the Eighth month, 1794, so quietly,
that it was scarcely known when she breathed her last;
and her remains were interred at Bunhill-fields the 15th.

[.asterism]
'''

SAMUEL SPAVOLD, of Hitchin, in Hertfordshire, was born at Bawtry, in Yorkshire,
and had his education among Friends;
and at a suitable age was bound apprentice to a carpenter and joiner in that county.
In the forepart of his time he was much addicted to the follies of youth;
but through the merciful visitation of divine grace,
he became so effectually reached as to be stopped in his
career of vanity about the nineteenth year of his age,
and a short time afterwards received a gift in the ministry.

When out of his time, he came to London, and worked as a ship-joiner at Deptford,
and continued in that employment there and at Chatham for several years;
during which time he was frequently exercised in his gift, and grew therein.
Afterwards he removed to Folkstone,
where way was opened for his further service in the church.
In 1750 he settled at Hitchin,
and during a long series of years labored much in the work of the gospel,
in this and other nations; and was at times baptized into deep exercises,
which much excited the sympathy of his friends;
to whom he approved himself an exemplary pattern of condescension.

He travelled four times through Wales, and as many through Ireland.
He was once in America, and once in Scotland;
and was often engaged in family visits as he passed along;
and a universal love and charity accompanied his gospel labors.
Notwithstanding he was at times large in testimony, he was a lover of silence;
and had often to recommend a reverend humble waiting on God, saying, "`Oh,
how I love this silent waiting, to feel my mind humbled before that great power.
We need to be more inward; the Lord`'s people are an inward people.`"
His life and conduct spoke the same language.

He was remarkably diligent in the attendance of his own meeting, even in old age,
and when bodily infirmity rendered it difficult.
The latter part of his time he was afflicted with several complaints,
which brought on great weakness, and for many months confined him wholly at home;
and at times in much pain, which he bore with fortitude and Christian resignation,
often saying, "`It is all well,
I am content:`" he was also at times weightily led in testimony to some who visited him.
He would sometimes make mention of the love he felt towards his fellow creatures;
and once in particular signified it was so great, that if he had strength,
he could go and preach to them on his crutches;
and he often declared that the Lord had been wonderfully good to him.

Under great bodily affliction, two days before his death, he said to his wife, "`My dear,
I cannot express the joy I feel; the Lord is very good.`"
A little after, "`Eternity is exceedingly solemn and awful to my mind;
a state of eternal duration;`" adding,
"`It rejoices my heart that there are many fellow-travelers going,
as with their hands on their loins, towards the heavenly Jerusalem and land of rest.`"

"`Man is made to glorify God while here, and enjoy him forever in a glorious eternity;
glory and honor be to his great name and power, and that forever.`"
And afterwards to the following import; "`I rejoice in my heart, and am glad,
that the Lord has enabled me to follow him in the straight and narrow way of the cross,
which he has prepared for his children and people to walk in.`"

On the day he departed, among other things uttered in great weakness and difficulty,
but evincing the sweet and heavenly state of his mind, he said,
"`The truth is a precious thing; it is worth seeking for.`"

He seemed pleased with the company of those about him, affectionately saying to some,
on taking leave, "`Farewell, I love you all.`"
He quietly departed this life on the 9th of the First month, 1795, at Hitchin,
in the eighty-seventh year of his age, and was interred there on the 15th;
having been a minister about sixty-five years.

[.the-end]
THE END OF THE NINTH PART
