== Chapter 14

[.chapter-synopsis]
* Louisa Conran
* Ann Pumphrey
* Ann Taylor
* Ann Knight
* Hannah Maria Miles

LOUISA CONRAN was the daughter of Samuel and Anne Strangman, of Mount Mellick, Ireland.
At an early age she manifestly showed the tokens of a Divine visitation to her soul; and,
as she bowed in obedience to the leadings of truth,
she became an example of humility and self-denial to the youth;
while her stability and solid conduct recommended her to those more advanced.

In the year 1783 she removed, with her husband, John Conran,
into the compass of the monthly meeting of Lisburne, in the north of Ireland; where also,
as she had previously been,
she was diligent in attending meetings for worship and discipline,
and exemplary in her deportment in them.
She was endowed with clear discernment in matters relating to the discipline,
and was active in the promotion of it.
She seldom missed attending the yearly meeting at Dublin,
and several times attended that of London.
Nevertheless in her last illness, she was tried with poverty of spirit.
"`Blessed,`" indeed, said the lip of truth, "`are the poor in spirit:
for theirs is the kingdom of heaven.`"
Yet this state, like some others which, through adorable mercy,
are preparatory for the reception of "`the true riches,`" is often, for the time,
deeply proving to the creature.
She was accordingly frequent in fervent supplication that her sins might be forgiven,
and that her dross, and tin, and reprobate silver, might be done away.
Yes, even her former "`works of righteousness appeared to her but as filthy rags.`"
She acknowledged that she was nothing; but that Christ was all.
In an emphatic tone, she declared her unshaken belief in him; that he was the Christ,
the Son of God; and that her hopes of salvation were through him.

With respect to the testimonies which friends have to bear, she said,
she had been concerned to keep them from her youth up: and her belief was,
that they were the testimonies of truth.
She took an affectionate farewell of her female servants,
and recommended them to let truth and honesty be the governing principle of their lives.
She desired her love to be remembered to several friends, and concluded with saying,
'`I love all.`'

At length, after a fit of great debility, in which she had dozed for several hours,
her husband, who was sitting beside her, was surprised to hear her speak:
and the last words which she is recollected to have spoken,
and those she spoke distinctly, were the following.
'`Who,`' said she, '`is this great enemy that surrounds me?
Christ will overcome him.`'
It was thought that she then perceived the approach of her dissolution.
After this she appeared sensible, though silent;
and having accepted some liquid which was given to her,
she quietly expired without a sigh.

She departed the 4th of the Twelfth month, 1805, aged fifty years.

[.asterism]
'''
ANN PUMPHREY.-- wife of Stanley Pumphrey, of Worcester,
a memorial was drawn up by her husband, of which the following is a copy,
somewhat abridged, but very little otherwise altered; and that only verbally,
and principally, if not wholly, in the narrative parts.

On reflecting upon the edifying tendency which the expressions of my dear wife,
during the few days of her illness, may have upon her surviving friends,
I have been induced to engage in the task of selecting a few of those expressions.
As they show in an indubitable manner the advantages of religion,
at a period when every other source of consolation would be inadequate,
they may operate as a stimulus to those who are allowed to remain
yet a little longer combatants on this stage of probation.
And, oh! that we who were eye and ear witnesses of this triumph of religion, may,
in an especial manner, evince by our conduct that it has been sanctified to us.

Ann Pumphrey was the daughter of Samuel and Elizabeth Baker, of Birmingham.
Her mother died during her infancy, but her father marrying again,
the loss was very much repaired by the care of her mother-in-law,
of whose watchful attention and parental restraint
she has frequently spoken with affection and gratitude;
having witnessed the advantages which accrue from submission to those whose judgments
are qualified to give counsel in the slippery paths of youth.
She was in early life, as appears from some of her own memorandums, prone to vanity,
and much inclined to follow the fashions and customs of a degenerate world; but,
being followed by the reproofs of instruction which remain
to be "`the way of life,`" she was favored to bow to them;
and sweet was the reward of obedience.
After patiently abiding under the preparing hand,
she appeared in public ministry in the year 1790;
and she was favored to labor in the exercise of her gift to the edification of the church,
not only at home, but abroad.
Having, with the sanction and unity of her monthly meeting,
travelled on a religious visit to Friends in Wales,
in 1798 she accompanied her friend Sarah Lynes through
the Midland and Northern counties of England;
in the course of which journey much arduous and self-denying
service was required and performed.

In the summer of 1800, she removed, on her marriage, to Worcester,
where her conduct and conversation endeared her to Friends.
She was a constant attender of meetings, except when indisposition,
or the indispensable duties attached to a young family, prevented her.
She was low in her own estimation, and charitable in judging of others;
and gratitude for favors received was a prominent trait in her character.
Of her journey through Wales, she has left an interesting narrative; and many fragments,
found since her decease,
are strongly characteristic of a mind seeking after durable riches.

Her last illness was an inflammation of the bowels, immediately following a lying-in,
which was on the Sixth-day, 13th of Twelfth month, 1805.
On the First and Second day following, her pain was very acute.
She did not say much, but appeared in inward exercise of mind.
On Third-day she began to consider her recovery as doubtful, and said to me,
as I sat by her bedside,
that she had anticipated peculiar pleasure in nursing this dear babe; and had,
on mine and the dear children`'s account, been very desirous of being restored,
if it had been the will of Providence.
'`Neither was I,`' continued she,
'`without a prospect of further service in the Lord`'s cause,
but I now believe the work will be cut short in righteousness.
I found it hard work to get to a state of resignation; and to say,
as I think I now can sincerely, "`your will be done.`"
I feel very much for you, my dear; I know your loss will be very great;
but seek after the resignation of pious Job, who, having witnessed great deprivations,
was strengthened to say, "`The Lord gave, and the Lord has taken away,
blessed be the name of the Lord.`"
I have no doubt but if I am taken from you,
you and the dear children will be abundantly cared for by the Father of mercies,
if you abide in his fear.
Should I recover, this will show what serious impressions a sick bed makes upon the mind.
If I do not recover,
it will be a consolation to my friends to know that I have nothing to do but to die:
having an undoubted evidence of an admission into those regions of bliss,
where the wicked cease from troubling, and where the weary are at rest.`'

She remarked, that she had been thinking much of the description her dear Sarah (Grubb,
late Lynes) had given her of the removal of her sister Moore,
of whom there is an account in this volume;
and thought she could adopt it as her own experience;
that though she had found it very hard at first to leave her dear connections,
she was now favored with that degree of resignation;
and that she could give her directions as though she was setting out on a pleasant journey.
And she did leave instructions, how she would have some things disposed of,
with entire composure.

On Third-day night the fever ran high, and her sufferings were very great;
but her head was preserved clear, and remained so to the last,
and her faculties were not the least impaired.

On Fourth-day morning, the 18th, she signified a wish to see some of her near relations;
and messengers were dispatched to Birmingham and Alcester,
with information of the alarming state in which she lay.
In the course of the evening, her father and her brother James came.
During this day she manifested great resignation to the divine will,
and was often advocating the cause of truth.
To her nurse, a person not of our religious society, for whom she had a great regard,
she said, '`God is no respecter of persons;
for all those that fear him and work righteousness, will be accepted of him,
let their profession to religion be what it may.
I am no bigot,
but am fully of the belief that the faithful of all denominations will be accepted.`'
She expressed full satisfaction in all her nurse had done for her, and added that,
though some things might not be quite palatable,
she was sensible the fault was in her own taste, not in the cook;
or words to that import.

Several of her relations coming to see her,
she expressed the sense she had of their kindness,
and addressed several of them in a very edifying manner.
She said that she was desirous that Friends of the place,
when gathered in their religious meetings,
would wait upon the Lord for the renewal of their strength;
upon the Minister of ministers; who can restore judges as at the first,
and counsellors as at the beginning;
that He can qualify others to fill up the places
of those whom he sees fit to take unto himself;
and that He will do it, if there is but faithfulness to every manifestation of his will.
She desired me to remember her affectionately to several, not of our religious Society,
adding, '`I am no bigot.
Pure religion is a very simple religion,
and leads into great purity of conduct and conversation.
Every one has an internal guide to eternal life, if they will but attend to it.`'
And on sending a similar message to some of her poor neighbors, she subjoined,
"`High and low, rich and poor, our heavenly Father made us all.`"

About twelve o`'clock on Fourth-day night, we thought we observed an alarming alteration,
and were very apprehensive her close was near at hand; but, contrary to our expectation,
she revived, conversed pleasantly with a young Friend who sat up with her,
and appeared tolerably free from pain.
I had hitherto had but little rest since my dear wife`'s first attack,
and yielded to the solicitations of my friends to go to bed;
but was called up before day-light on Fifth-day,
another alteration for the worse having taken place.
The same morning, my father, Thomas Pumphrey, arrived from Alcester,
and continued with us to the last, as also did Samuel Baker, his wife, and son.

This, and the day following,
which was that immediately preceding the night of her dissolution,
her mind seemed particularly engaged for the promotion of truth;
and she was led to admonish and comfort many of her
relations and friends who came to see her.
She addressed her own aged father in the most affectionate terms,
believing that he might adopt the language of the Psalmist, and say,
"`The Lord is my shepherd, I shall not want.`"
She encouraged him to continue to trust in the Lord,
who had been his shield through many trying dispensations;
who had seen fit to comfort him with his rod and his staff;
who had blessed him many ways, and would continue to bless him;
that he had been the stay of his youth, and was now the staff of his old age.
To her mother-in-law,
she expressed how much she was obliged to her for
the care exercised over her in her youth,
adding,
'`I believe the restraint that religious parents have over their children
is often a great preservation from the many snares of life.
I have reason to believe it was a great blessing
to me that I was early restrained by my parents,
my disposition being too much prone to vanity.`'

Seeing her father, Pumphrey, in the room,
she observed that she did not know he was there,
but thought the same expressions of the Psalmist she had
quoted to her own father were applicable to him.
At another time, seeing him enter her chamber, she said, '`Dear man,
he is one who loves the truth.
Oh, what love I feel for all those who love and keep in the truth!
Indeed, I feel nothing but love in my heart towards all men.`'

Her nurse lying down upon the bed by her, she thought it had been her husband`'s sister,
Ann, and was going to speak to her; but turning round, saw her mistake, and exclaimed,
'`Ah, dear Mary, it is you, is it?`'
and throwing her arm around her neck, with the utmost affection, she added,
'`You have been very kind indeed.
I am abundantly obliged to you.
I am afraid I shall wear out your patience.
She desired her sister Ann to give her dear love to her absent sisters,
with desires for their preservation; adding, '`I delegate my precious boys,
Samuel and Thomas, to your care.
They have been much with you already.
I am fully satisfied, and can leave them comfortably under your management.
Give my love also to brother John;
I wish he may follow those things that make for peace.`'

I was at this time sitting behind, and supporting her, when she thus addressed me.
'`Ah! my dear Stanley, did you think I forgot you?
No, though last mentioned, you are my most beloved.
I feel much for you.
I know your loss will be very great;
but the lenient hand of time will blunt the edge of grief,
and you will have many things to divert your attention from the mournful subject.
As I mentioned to you before, I would have you endeavor after the resignation of poor,
pious, patient Job; who, when stripped of all, could say, the Lord gave,
and the Lord has taken away; blessed be his name.
It was he who brought us together,
and it is a consolation that he has enabled us to keep our covenant.
I hope he will be your support; and he will, if you are concerned to live in his fear.`'

Speaking of the resigned state of her own mind, she said,
'`Had I not attained this state of resignation,
and been made willing to leave my dear husband and sweet babes;
and my days had been lengthened out, but not in mercy,
what an afflicting state would that have been; but I am enabled to resign all, and say,
your will be done in all things.
"`O death,`" she cried, "`where is your sting?
O grave, where is your victory?`"
Death has no sting for me; neither has the grave any victory.`'
Again; "`Many are the afflictions of the righteous;
but the Lord will deliver them out of all their troubles.`"

Her disorder had now assumed a most serious aspect;
and the surgeons (for a consulting surgeon had been called
in) informed us of the great danger they apprehended.
One time, when they had left the house, she asked what they thought;
whether they did not conceive her case to be dangerous?
Not receiving an immediate answer, she added, '`You need not be afraid to tell me:
I am prepared.`'
The faculty are too apt to show what I consider an improper backwardness
in making patients acquainted with their real state.
I will tell you once for all,
and then you will judge whether I have not great reason to be prepared.
On Second day my mind was powerfully impressed with the message sent to king Hezekiah,
"`Set your house in order, for you shall die, and not live.`"
It naturally affected me; but I did hope for the sake of my dear husband and children,
that, as the term was lengthened out to him,
the like favor might have been mercifully vouchsafed to me.
However, on Third-day the language intelligibly was, you shall not live,
you shall surely die.
'`So you see,`' she repeated, '`I have great cause to be prepared.`'

To a near and dear relation, who had been generally with her during her illness,
she said, '`You have been, my dear cousin, a kind attendant.
Your kindness has soothed and comforted me, many times, under my great bodily affliction.
I feel something pleasant whenever you come near me; and I believe, my dear,
you will be rewarded both here and hereafter.
I have often esteemed it a favor that I have been connected to such kind relations;
and have many times been consoled by it.`'

To a Friend of the meeting, who came to her, she spoke in very encouraging terms:
'`I have sympathized with you,`' said she,
'`and at times have felt the conflicts of your poor mind, have been enabled to stand up,
as I apprehend, for your encouragement;
and have craved that a double portion of the spirit of Elijah, may rest upon the Elishas.
Oh, may you all be faithful to manifested duty; the way of truth is a very simple,
plain way.`'
She expressed herself in an affectionate manner to the surgeon,
and said she felt very grateful for the great attention he had shown,
and was well satisfied with what he had done; that she hoped he would be rewarded,
both in time and eternity.
She also encouraged him to trust in the Almighty, who was no respecter of persons;
but would reward all, according to their works.

Fifth-day night was a night of great bodily conflict.
She was tried for the last day or two, with violent fits of coughing,
which exhausted her so much, that we several times thought nature must yield.
She would frequently say after such exertions, '`Oh,
how thankful should I be for one hour`'s quiet before I go.`'
But many times when we conceived the conflict was nearly over,
she would revive to admiration; and perhaps seeing a fresh face,
or feeling her mind impressed with fresh instruction to those about her,
would speak with the animation and perspicuity of one in full health and vigor.
She sometimes said that she hoped she should not hurt herself;
but when she felt anything upon her mind, she could not refrain; '`For,`' added she,
'`I have but a short time to finish my work in.`'

On one of these occasions two of her cousins came,
whom she had previously expressed a desire to see,
and whom she had not seen during her illness; but she was so ill,
that at first it was Judged improper to introduce them.
Nevertheless, as her dissolution was, to all appearance, very near at hand,
they were admitted to the foot of the bed;
with no other view than that they might witness the last, sad, solemn scene.
However, she revived again, and seeing them there, called them to her by name;
and after addressing them in an edifying, affectionate manner, concluded with, '`Farewell,
farewell; but remember, the way to farewell is to do well.`'
On my telling her she had contributed largely to our consolation under such affliction,
and that it might perhaps be comfortable to her to hear
the testimony which her father had just been giving of her,
namely, '`that she had never, that he recollected, in the whole course of her life,
in any one instance, willfully offended him: '`she replied,
'`I always wished to be a dutiful child.`'

She often expressed her gratitude for the care we took of her,
so that she did not lack anything, and was nicely waited upon.
'`The kind attention,`' she said, '`of my relations and friends on this occasion,
has been great, and has tended to sweeten the bitter cup allotted me.`'
She requested her brother James to send to her friend
Sarah Grubb the intelligence of her case;
to give her dear love to her, and to her husband, and his relations;
to inform her that the precious cement of affection
and regard towards her remained unchanged;
that she frequently recurred to the seasons of divine
refreshment they had experienced together;
and although she had had to drink many bitter cups,
and to pass through deep baptisms with her:
some of which had been as hard to the fleshly part, as the sacrifice of her natural life,
(alluding to their exposure and service in the public markets;)
yet she had never felt any opposition to it in her own mind,
and believed it was in the line of required duty.
She also often expressed her fears that her attendants would be overdone,
and was anxious that they should take care of themselves,
when they were manifesting attention to her.

On Sixth-day evening, the doctors called,
and concluded she could not live through the night.
One of them called also the next morning.
She was then very feeble, and her breathing extremely difficult;
but in a state of entire composure and resignation.
Indeed, during the whole course of her illness,
she was not heard to utter a murmuring word;
and said she had not even a murmuring thought.
The whole of Sixth-day she was evidently in a dying state,
and in the evening it was thought by all present
that in a few more minutes the scene would close.
Her relations were standing round the bed in solemn silence,
and with mournful anxiety awaiting her last expiring breath.
With a view to render respiration less difficult,
two of us were affording her what air we could, by the help of fans; when,
to our admiration, she revived, and said she should like to see her dear son Samuel,
once more.
This was at first rather discouraged, lest it should tend to discompose her:
but she said, she thought she could bear it;
and would endeavor not to distress the child.
He was accordingly brought, and the interview astonished every one.
Although we had been expecting every minute to be her last, she turned round,
put on a smiling countenance to meet the child, kissed him, showed him one of the fans,
observed how fine it was; she had not, she said, seen so fine a one many a day;
told him to be a good boy, to give mother`'s love to his brother Thomas,
and tell him to be a good boy; kissed him again, and bade him farewell.
The child was no sooner gone than she exclaimed, "`Great and marvelous are your works,
Lord God Almighty; just and true are all your ways,
you King of saints!`" '`It is the Lord`'s doing, and it is marvelous in my eyes.
It must be his doing; for the more I consider how I am supported,
the more I am surprised at it!`'

She gradually grew weaker and weaker, till about one o`'clock on Seventh-day morning,
the 21st of the Twelfth month, 1805, when she quietly breathed her last,
in the thirty-ninth year of her age, departing from the vicissitudes of time,
to the unchanging happiness of eternity.

Thus did this amiable pattern of filial, conjugal, and parental affection,
and of Christian patience and holy resignation, finish a comparatively short,
but well spent life; leaving a memorable example of the enlivening,
heart-consoling effects of religion upon the mind, at the awful period of dissolution.
Oh, may the thoughtless be aroused to more reflection; and,
impressed with a sense of the uncertainty of time, attend to the divine injunction,
"`Be also ready.`"

[.asterism]
'''
ANN TAYLOR, a young woman who died at Manchester, the 7th of the Fourth month, 1806,
was the daughter of John and Ann Taylor, of that town, and born in the year 1788.
She received the greater part of her education at home,
and much of the latter part of the time,
was usually employed in the acquirement of useful accomplishments,
under the care of her father`'s second and surviving wife, Jane Taylor,
formerly Jane Ellwood.

The following narrative of the happy temper of mind displayed
by this pious maid in the course of her final illness,
will show that the care extended to her had not been in vain.
It will be related for the most part in the person, and in the words,
of her affectionate mother-in-law.

On Fourth-day, the 25th of the Ninth month, 1805, she was much affected while in meeting,
during the ministry of a Friend, who, among other things, had said, '`Day after day,
week succeeding week, and year after year passes away;
and what preparation is made for our latter end?`'
The consideration, '`Am I ready for the awful change?`'
impressed the mind of Ann.
Attending, after meeting, a corpse to the graveyard,
though then apparently in good health,
she had a strong belief that her own interment would be soon.
On the Seventh-day following she was taken ill with a spitting of blood,
confined to bed for several days, and expressed some fear,
lest she should be removed when unprepared: however,
in about two weeks she was so far recovered as to be able to go about the house.

A short time after this partial amendment, the disease returned,
and she appeared in great distress of mind, saying,
'`I don`'t yet feel sufficiently prepared.`'
I asked her whether any particular thing stood in the way.
She replied, '`I don`'t know of anything but a lack of attention;
not having my thoughts turned inward while in meetings;
which I now see has been a great loss to me.
By allowing my mind to ramble, I have wasted much precious time:
surely it is playing the hypocrite.
Seeing this to be the case, I resolved, when last at meeting, that,
if permitted to go there again, I would be more careful and diligent; but +++[+++I]
now believe I shall never go more.`'

On my remarking it was a favor that our eyes were opened
to see where we had omitted or committed anything,
contrary to known duty, she replied, '`Yes, mother;
and I hope to be very careful every way, the little time allotted me here;
for all things are possible with him who knows what is best for us.`'

She frequently took a retrospect of her life, and strictly scrutinized her conduct.
'`I never, knowingly,`' said she, '`told a falsehood, which now affords me great peace.`'
She often expressed a concern for several young Friends,
who belonged to the same meeting, saying,
'`I believe if some of them were laid upon a sick bed, as I am,
they would see the folly of pursuing anything,
but that which is most likely to fit them for an inheritance in the kingdom of heaven.
But oh! how pure must all be, that enter in there!
There are too few, when young, and in health,
who think deeply enough of their latter end.`'

She had many returns of her complaint;
and she was favored in a particular manner with patience and resignation.
'`It is the Lord`'s doing,`' said she, '`let him do what he will.
I know it is for my refinement, and if I had a greater evidence of going well,
I could leave all earthly things with joy;
for it will be but a little time before those I leave behind me must go;
yet I hope my great-Master will favor me with patience and resignation to wait his time.`'
I said, that I believed she would be favored with greater assurance before leaving us.
She answered '`Then I want nothing more, but shall be happy.`'
One evening she said, '`fear I have not loved my Maker so much as I ought;
which may be the cause of his presence being so long withdrawn now in my affliction.`'
I observed to her, that the patience and resignation with which she was favored,
in so extraordinary a manner, came not from man.
She answered, '`I hope to be preserved from murmuring,
for that would be unwise on my part; and I give myself up entirely into my Maker`'s hands,
to do with me as he sees best.`'

She several times testified great compassion for her fellow creatures,
whose situation excluded them from even the common necessaries of life.
'`How much,`' said she, '`have I to be thankful for,
being provided with every needful thing to relieve my bodily sufferings, and +++[+++also with]
affectionate attention!
There seems very little ground to hope for my recovery, yet it is not impossible;
and if I should be restored to health,
the rest of my days shall be spent to the honor of a merciful Creator;
but I have little prospect of ever getting much better.`'

One day she appeared very thoughtful, and expressed her great fear,
that she was not yet enough prepared to meet the awful event.
The next day she was visited by two Friends, one of whom said that the sweet,
innocent state of Ann Taylor`'s mind, felt very precious to her.
When they were gone, Ann said, '`I love the company of these friends,
and would have such to come and see me:`'
and she several times desired that those who went into her room,
would not converse about the common occurrences of the day;
for her mind was much weaned from earthly things.
A relation, who once came to see her, remarked her exemplary patience; and said,
that when his time was so near a close,
he should think it a great favor to experience the same degree of resignation.
After he had left her, she said, '`I cannot expect to be rewarded like him.
He has given up much; but what have I done to look for any reward?
What crosses have I taken up for Christ`'s sake?`'
It was observed that she had denied herself of many gratifications,
which some were indulging in, and such as many deem innocent and allowable.
She replied, '`Yes,
because I considered myself only a steward over everything I possessed;
and believed it wrong to indulge in anything that would take up too much of my time,
or fill my mind with what was unprofitable:
and though I never felt uneasy with any part of my dress,
yet I now believe it right to make clothing in a manner that will take up the least time.
Convenience and cleanliness should be the only things looked to in apparel;
for it is vanity to dress +++[+++adorn she probably meant]
these poor bodies that are but dust.`'

As her breathing became more difficult, her change seemed approaching fast; but she said,
she felt very comfortable in herself.
One evening, a woman-friend visiting her,
mentioned her belief respecting the future well-being of Ann,
and that her heavenly Father`'s arms were open to receive her.
After this visitor was gone, she saw me shed tears,
and said with an earnest tone of voice, '`Don`'t shed tears for me.
I am going well.`'
This she expressed several times over.
When we were by ourselves, she said, '`Mother,
how can it be that the friend had to say that she wished her evidence
might be as certain that she should enter into rest,
as it was that I shall?
What have I given up, compared with her?`'
After some little further conversation, she remarked, '`You know it is said,
"`In my Father`'s house there are many mansions:`" and if I get to one of the very lowest,
I shall be content.`'
She desired a friend in the room not to be so affected,
for that she should soon be happy; and on my confirming this,
with the expression of my belief, she said, with an overflow of affection,
and a melody that can only be felt, Yes mother, yes; I shall be happy;
and I hope you and I shall meet there together.`'

When her breathing became still more difficult, she continued patient;
but she frequently prayed that she might have a little relief.
When +++[+++thinking her end close at hand]
I called up the family, she inquired whether I thought her going.
I said, '`I believe so.`'
'`Then,`' said she, '`take leave of me, and give my love to Friends, and to every body.`'
Lying still a little, and feeling herself easier, she raised her voice,
and addressed her sister in a distinct manner, as follows: '`Be kind to your mother,
and when poorly, wait on her, and do everything she wishes you to do.
Make a good use of your money.
Mind to give a great deal to the poor.
You know that a short time since we were four; now three; and will soon be only two;
then one; and so we pass away.`'
Turning to me, she requested I would distribute some money to three poor widows,
and mentioned the relieving of others in distress.

After this she laid down her head, and feeling herself better, said, '`Mother,
I think you may be mistaken.
I am not going yet.`'
I told her that I believed she soon would, and her affection seemed again to overflow,
and tendered every one around her.
She bade each individual farewell, and in a distinct manner cried out, '`And now,
O Father, if it be your will, take me quickly.`'
Then having paused a little, she mentioned two young women, our servants.
Being told they were in the room, she looked up, and again said, '`Farewell.`'
She then breathed shorter and shorter, till about seven o`'clock in the morning, when,
without a struggle, she breathed her last.
She departed at the age of eighteen, on the 7th of the Fourth month, 1806.

[.asterism]
'''
ANN KNIGHT, daughter of Edward and Martha Knight, of Great Bardfield, in Essex,
was removed from the trials and temptations of time, the 20th of the Fourth month, 1806,
not having accomplished her sixteenth year.
She was the eldest child of a numerous family, to which,
as she was early addicted to piety, she was an excellent example.
In early youth she preferred the company of those more advanced in years,
to the amusements which commonly engage children:
and was indeed herself of a riper understanding than is common.

It was her practice, when she retired for rest, to examine the transactions of the day;
and when occasion of regret had occurred, she was not satisfied to sleep,
until she felt that peace of mind which ensues from repentance.
As one instance, her mother going to the bedside, found her in tears.
On being questioned as to the cause, she replied, '`On looking over the day,
I find I was out of temper, and too cross to my little sister.
I cannot go to sleep till I find forgiveness; and, dear mother,
I hope you will forgive me also; and then I can go to rest,
and sleep sweetly!`' It should, nevertheless, be remarked,
that few children showed less of temper towards their younger brothers and sisters;
few were more loving;
and few endeavored more to compose and settle their little differences:
so that she had early her share in the blessed character of the peace-maker.

In our religious Society,
in which vanity in dress is certainly more discouraged than in most others,
which mingle in the common concerns of life,
the restraints which prudent parents find necessary to impose
on the disposition which is endeavoring to indulge it,
are often irksome to the inexperienced and youthful mind.
It appears that this pious maid had not been without her temptations this way;
but disease had probably been the means of abating her desire to adorn a body,
of the frailty of which it had warned her.
The 26th of the Second month,
she had returned in ill health from the house of a relation;
and the following day she told her father that she once had thought
that she should like to dress like others;`' But now,
'`said she, '`it is all done away.
I have no desire for it at all: '`and she added,
that what would please her parents would please her;
and that she was very sorry to see some of her relations run out in dress,
and deviate from the plain language, and from their profession.`'
They will find, '`said she, '`that will not bring peace of mind.`'

In a few days she was confined to bed, and said to her parents,
'`I thought I should like to have stopped a little longer with you,
if it had been the Lord`'s will.
It is hard parting with you, but I hope I shall be resigned.
You are very near and dear to me; but the Lord can make hard things easy.`'
It was remarked to her that He had done that for her many times; to which,
with a raised voice, she replied, '`That he has, and I feel easy.
I feel nothing to burden my mind, and that is a favor;
but I hope I shall see my way clearer before I go: '`and this,
there is full reason to believe, she was favored to do.

Between two and three weeks before she died,
two of her brothers came home from school to see her.
She told them that she was glad to see them once more in this world;
and after pausing a little while, she exhorted them to fear the Lord,
and to keep to plainness, in language and dress: saying, '`If you do not,
it will bring a burden on your minds.
I do not accuse you; but I know the enemy is very busy to draw away the mind,
if you do not keep a watch.`'
Addressing also her parents, she said, '`I hope you will give me up to the Almighty`'s will.
He is not a hard master; but a tender Father to his children that obey him.
I have felt him underneath many times to keep me,
when the enemy has been endeavoring to draw me aside from my watch,
both when in meetings as well as out.
But, blessed, be his holy name, he has preserved me; and he will also preserve you,
if you obey him.`'

She mourned, as has been already mentioned, over some of her relations,
whom she apprehended to indulge too much in dress;
an indulgence from which she had some years felt herself restrained:
and she desired her father to write down her feelings,
that he might not forget to tell them how much it had grieved her,
that they should spend in it so much of their precious time.
'`They will find,`' said she, '`it will not bring peace of mind at such a time as this;
and they know not how soon they may be brought as weak as I am.`'
She several times mentioned a first cousin, Ann Taylor,
who had been at her father`'s house, in blooming health,
the summer before she died (and whose happy exit has been just related);
she compared her strength at that time with her present weakness; and said,
'`I had a sense given me, I believe it was a divine intimation,
that I should not see her again.
I do not know which will go first.`'
They died within about thirteen days of each other.

At another time she lamented the vanity and luxury of the world;
she remarked how the bountiful Giver had provided food and clothing for all,
if it were rightly used; and she in particular lamented the vanity of dress,
in such as frequent balls, and the like assemblies.
'`Oh,`' said she, '`what vanity!
This is a world of trouble, and I am freely given up to leave it this night,
if it be his will; as freely as I can sit by that fire-side.
Eternity is awful, to be sure; but I hope and believe I shall be happy.`'

Toward the close of her time she had violent pain in the bowels and limbs,
which induced her to say, '`I hope patience will hold out.
Dear father and mother, pray for me, that patience hold out.`'
She begged to be released, if it were the Lord`'s will: but she said,
'`I hope I shall not be too anxious to be gone: I think I shall not.`'
After one of her fits of great pain, she lay still for a considerable time;
and then said to her father, '`Dear father,
how the Lord has been with me when I lay still.
I was so comfortable, I thought I was in heaven; I was so happy, happy.
Praised be his name forevermore!
I cannot praise him enough, he has been so gracious.
I was in hopes I was going.
Pray do not hold me.
I fear you hold me.
If my pain come again, I know not what I shall do, lest I should murmur,
and that would be a sad thing.
Now I am happy.
I hope patience will hold out.`'

She exhorted a young man, an inmate in the family, to beware of unprofitable company,
and of allowing his temper to arise.
She reminded him that he might soon be brought as low as she was;
and that then he would find it enough to struggle with the pains of the body.

A few days before her departure, early in the morning,
after having lain very composedly for some hours, she called to her mother and said,
'`My dearly beloved mother, I have something to tell you.
This has been a blessed night to me.
I have seen heaven, and they are all happy, happy, there.
The Almighty has been so near me.
I thought he bid me take leave of all the world: which I can freely do,
to possess that peace and happiness which I have seen; yes,
for the lowest place in heaven; as the things of this world signify nothing to me; no,
not in the least.
No matter what becomes of this bit of clay, when the spirit is gone to heaven.
Do not put yourselves to much expense in burying me.`'
After this, reviving after a convulsion fit, she said, '`I thought I had been going;
but I could not go, without once more praising the Lord.
Where are the dear children?
Bid them fear the Lord, and love the Lord Jesus.`'

The day before she died, inquiring the day of the week, and being informed, she said,
'`It is Seventh-day again, and I am here yet.
I want to be gone, but hope I shall have patience to wait the Lord`'s time.
That is the best time.`'
The day of her release, she desired her parents to pray to the Lord for her,
that she might have an easy passage.
This petition appeared to be granted.
She fell asleep for a few minutes, and, without one sigh, expired.

[.asterism]
'''
HANNAH MARIA MILES, daughter of Robert and Hannah Miles, of Melbury Abbotts,
near Shaftsbury, Dorsetshire, was born in the early part of the year 1787.
Her parents joined the Society of Friends by convincement, about the year 1796,
when their daughter was a child of nine years of age.
From her childhood she was serious, and orderly in her conduct.

When she had attained the state of a young woman,
she was seized with a pulmonary consumption, which gradually brought on her dissolution.
In the early stage of her illness, she was sensible that she should not recover,
and she expressed herself in this way: '`I am very unwell,
and believe I shall not recover, but shall have a lingering illness.
I should hot mind it if I had spent my time better; for I have seen enough of this world,
not to wish to live any longer in it, if I had true peace of mind.
I have given way to many hurtful things, such as dress,
not so consistent as it ought to have been; likewise reading improper books, which,
if it have no other bad tendency, takes up that time which may be better employed.
I sincerely hope,
that our family may be careful to avoid those hurtful and hindering things;
and not put off the great work until sickness come.
I have had many good meetings and precious visitations, but too soon forgot them.`'
She also said,
'`It is some satisfaction to me that I have been preserved
from talking much when in company;
but I have nothing to boast.`'

Her distress continued for some time; but once,
being asked whether she felt her mind more composed, she replied,
'`I hope it will be better, but must not expect it at once.`'
Some weeks afterwards, on a First-day, she became much more indisposed;
when no one was present with her but her mother.
After a season of quiet she said, '`Dear mother, I have heard, as it were,
a voice sounding in my ear, "`Watch and pray,
lest you enter into temptation.`"`' Her mother advising her to attend to it,
as to a loud call, she replied, '`I hope I shall, for I think I cannot be with you long.`'
The mother observing, that the parting with her would be a bitter cup, Maria answered,
'`I hope, my dear mother, you will be resigned, and give me up;
for you have many others left, if I should be taken.
Yet I think it will be a great trial to you; but the Lord gave,
and it will be the Lord that takes away.`'

For some weeks she did not say much by way of religious communication;
but she often seemed in deep retirement.
Having at one time been left alone, she was afterwards found in tears,
and the cause being inquired, '`I have reason`', said she,
'`to be thankful that I was not taken away suddenly: if I had, it would, I fear,
have been bad for me.`'
Some time after this, two friends paid her a visit,
which seemed to be very helpful and strengthening to her mind,
for she appeared generally calm and composed.
Reading the Scriptures was her daily practice and delight;
and there is reason to believe they were much,
and profitably opened to her understanding.
When it was thought advisable to employ a physician,
she remarked that it was the last trial;
and that if it would be any satisfaction to her relations she was content,
but that she did not think it would be of use to herself.
Her mother once expressing a hope that some means
might prove helpful to her recovery; '`No,`'
said she, '`I do not expect it;
for I believe more good will be done by my death than if I was to recover.`'

About the time the physician was employed, she was again visited by a ministering friend,
whose testimony seemed to be the means of setting her at liberty,
and making way for her to declare her own exercises,
and to impart advice to those about her.
Soon after this visit, a violent bleeding at the nose came on,
which rendered her so weak, that she lay in a sort of stupor for some days.
At length she revived, and expressed herself thus:
'`I thought I should have gone before now, but I seem a little recovered for the present,
but it will not be long.`'
Seeing her sister much affected, she said, '`Dear sister, do not grieve too much;
for though we love one another dearly, and I know you will miss me,
yet we must part some time or other, and why not now?`'
adding solemnly, after a pause, '`Yes, it will be now.`'

To her two eldest brothers she said, '`brothers,
I hope you will seek the Lord in time of health, for it is a great blessing.
I have a great love for you, and I may be taken away suddenly, but +++[+++I]
hope you will remember what I have said to you.`'
Her aunt, Charlotte Matilda Burt, coming into the room, she said, '`Dear aunt,
you do not shun a sick house; but it may be best for you:
for it is better to go to the house of mourning than to the house of feasting.
Seek the Lord, for it is not such a very hard thing.
Seek you him, and he will be found of you.`'

Some days after, her grandfather, John Miles of Cann, near Shaftsbury, came to see her.
She was then very weak, and her breathing difficult; but on his coming into the room,
she addressed him thus: '`O, dear grandfather, do you seek the Lord God,
for he is merciful.
You are an old man, and ought to be prepared; for there are so many sudden deaths,
that we know not how soon we may be taken.
Do you, dear grandfather, prepare to meet me in heaven.
I have great love for you and my dear grandmother.
Seek you him, that he may be found of you.`'
She then sat still a while, after which, assisted by her sister,
she kneeled down and prayed for her grandfather, and all her dear relations.
On rising from her knees, she seemed much refreshed,
and even her breathing became easier than it had been before this religious exercise.

Awaking one evening from an uneasy slumber, she exclaimed, '`What have I to do with you?
Get you behind me, Satan;`' and then she fervently prayed, '`O Lord, do you protect me,
and support me under the afflictions of the body.
O Lord, you know you are dear to me, and if it be your blessed will, take me to yourself,
from the various pains and tribulations of this life: yet not my will, but yours be done,
O Lord.`'

Her parents remarking that they had great reason to be thankful, on her account:
though their loss would be great, it would be her gain;
and therefore they hoped to be resigned, believing that she was; she replied `'Yes.
I have given you all up: for "`they that love father or mother more than me,
are not worthy of me.`"
Yet I have had a hard struggle with myself to give up such near and dear relations.`'
Being asked if she would be content to be restored again, if it were the Divine will,
she said, '`I hope I should; but I had rather go now;`' adding, '`Not my will be done,
but yours, O Lord.`'
She then desired to see all her little brothers, and her sister Emma.
She took an affectionate leave of them,
after praying fervently for their true preservation in this life,
and more not recollected.
As her cough was now very troublesome, and she found increased weakness,
she did not at this time expect to live over the night;
but requested the company of her parents and the elder part of their family.
To each of these she spoke in great tenderness,
and gave them individually memorable advice.

Continuing to apprehend that her close was at hand,
she again was engaged in supplication in this way.
'`O Lord, do you be pleased to take me this night, if it be your will;
and grant me an easy passage out of this world to the next.
O Lord, I pray you, take me to yourself while my lamp is burning,
that I may not be like the foolish ones, who, when the bridegroom came,
their lamps were gone out.`'
After this she took, with great composure, an affectionate leave of each one present.
'`Give my dear love,`' she added, '`to my sister Betsy,
and tell her to remember what I said to her when she was at home,
and then all will be well.`'
After this she again uttered the language of supplication, '`O Lord,
do you be pleased to give me an easy passage out of this world to the realms of bliss.`'

A pause of stillness ensued, but in a short time she broke forth as in ecstasy:
'`Oh! it seems to me I see the angels walk in white robes!
O death, where is your sting?
O grave, where is your victory?
What has Jesus done for poor sinners?
He bled and died for us!
Oh, what sweetness have I felt in my affliction:
that peace which nothing in this world can give or take away!
Some time since I thought I felt something like peace, but it was not the true rest,
for I was then in a doubting state; but when I came to believe,
no tongue can describe the sweetness I then felt.`'

When morning was approaching, she said, '`I did not think to see the light of another day;
but I believe I have something to say to some one not present;`'
and she inquired whether any one were expected that day.
Being answered '`No`' she replied, '`I think there is.`'
The sequel proved her apprehension to be just; for her uncle, John Miles, of Gillingham,
who had not visited her before during her illness, came that day to see her;
to whom she freely imparted what was on her mind for him.

For two weeks after this,
she was much employed in speaking to several of her
relations in a powerful and affecting manner,
by which her bodily strength appeared to be further impaired.
The last person who saw her, those of the family excepted, was her maternal grandfather,
Thomas Burt, also of Gillingham.
To him she had much to communicate, and she also prayed fervently for him,
and for her absent grandmother.
The week following, her debility increased,
and she appeared thankful that her exercise of mind for her relations was over.
She expressed her hope that she had not spoken in her own strength;
and on being cautioned against exerting herself too much, she cheerfully replied,
'`Never mind the poor body.`'
She often continued to pray for patience to endure the oppressive weakness of her frame,
and to hold out to the end.
At one time she said to her father, '`I do sincerely wish, if it is the Lord`'s will,
I may be taken to-night; and buried at the monthly meeting,
as there may be a large gathering of Friends, that if anything is said,
it may be for the benefit of my dear relations.`'

Two days before her decease, she became at times delirious, through weakness.
She observed it herself, saying,
'`My poor head is not quite right;`' and she testified her thankfulness
that she had been favored with her reason so long.
Once she said, '`Pray for me, for my weakness is so great,
that I fear I shall not be able to pray for myself.`'
She was desired to turn her mind inward, and it was hinted to her that words mattered not.
She answered, '`No, '`and was afterwards often observed as in supplication.
About this time she said, '`Oh, the enemy will be busy,
but I hope my patience will hold out to the end;`' adding, '`My trust is in the Lord.`'

Her cough had now left her, and her breathing was become more difficult;
so that though she often spoke,
the whole of what she said could not be distinctly understood.
Thus she once began, '`The Lord is my staff;`' the remainder was not clearly comprehended.
On the last evening of her life, she spoke thus to her sister: '`Fanny,
when you are in the situation you see me in,
do bear it with patience and Christian fortitude: and I believe you will,
as his grace is sufficient for you.`'
Then she prayed again: '`O Lord, if it be your will,
take me this night out of this pain and affliction of body.`'

At length the approach of death still further impaired her speech;
but she desired to be turned on one side,
and having taken a small quantity of wine and water, with an expressive look she said,
'`No more.`'
Her parents were sitting by her,
when with great composure and sweetness she took both their hands,
and for a considerable time held them in her own, then cold with departing life.
The scene was affecting, and she requested all present to be very still;
but in a while remarked, that her breathing was so laborious,
that she could not be so still as she could wish.
After this, however, she did lie more still for some time,
and her breathing seemed less difficult for a few minutes: when,
reposing her head on one hand, while her mother held the other,
she softly drew her last breath, as the infant drops into the slumber of repose.
