[short="Historical Account of Piety Promoted"]
== A Historical Account Of The Work Entitled Piety Promoted And Of The Compilers And Editors Of The Nine Preceding Parts.

As the volumes entitled [.book-title]#Piety Promoted# have met with a very general acceptance,
and I believe have often proved incentives to a pious life,
by recounting so many instances of happy death,
I have thought that a concise relation of their origin and continuation,
and of the friends who formed the several compilations,
would be a proper introduction to this additional volume; attempted, as it is,
after an interval of more than a century since the publication of the first.

John Tomkins, a Friend, of London, was the author of this volume,
which was published in 1701.
The narratives are arranged according to the dates
when their respective objects departed this life;
and as they begin with 1656, and end with 1700,
this volume contains relations of the peaceful close of many of our early predecessors:
in all, about fifty-nine names, the first being that zealous youth and patient sufferer,
James Parnell, who died of sheer ill usage, in Colchester Castle.

To this volume the author has prefixed a copious preface; from which the following lines,
explanatory of his purpose, which is the same with that of succeeding compilers, may,
not inaptly, be inserted here.

[quote]
____
The design of this collection is,
that godliness and holiness may increase and prevail among men,
that they might have fruit unto holiness, that their end might be everlasting life.
Having, in the course of my reading,
met with many excellent sayings of our dying friends,
that afforded much satisfaction of mind,
I have collected some of them together for the benefit of others:
knowing that usually the words of dying persons make
deeper impression on the minds of men,
than words spoken at other times.

Some account I was obliged to give,
concerning some of our dear friends`' sufferings and labours in the gospel,
the better to let the reader into the understanding of
the weight, and indeed the
meaning of some of their expressions: not with purpose to exalt men;
but to exalt the great God, and his grace in Christ Jesus,
by which they were what they were.
The Lord give them that read,
a heart to understand the things which belong to their peace:
and if these shall be any means to stir up any to more faithfulness and diligence,
in making their calling and election sure, my design is answered;
and God shall have the praise of all; who is worthy forever.
____

The second part or volume appeared the following year, also published by John Tomkins.
It contains upwards of nine sheets, and about forty-five names,
but they are not so methodically arranged as in the former volume.
It has a preface by another hand, without a name,
but [.book-title]#Whiting`'s Catalogue# has the initials "`J. R. John Tomkins,`"
having thus engaged in an acceptable service, seems to have persevered in it to the last;
for, the first volume having been reprinted in 1703, in 1706 he published a third,
containing ten sheets, and about forty-eight names,
rather promiscuously placed as to date.
This volume also is prefaced by a friend of the author, namely, Christopher Meidel.
John Tomkins did not long survive this last publication,
but died in the Seventh month of the same year.

He was born about 1663.
His parents were both of them Friends.
His father died when he was very young; and, as he grew up,
he not only assisted his mother in her business,
but was helpful to another family of children which she had by a second husband,
who survived her, and afterwards fell into poverty.
Tomkins was a diligent peruser and searcher of the Scriptures,
a zealous promoter of the discipline of the Society,
and was also esteemed a skilful minister.
He was about forty-three years of age at the time of his decease,
and left a widow and children.
There is a copious account of some of his dying expressions
in the fourth part of [.book-title]#Piety Promoted,#
and also in J. Kendall`'s [.book-title]#Revised Collection, Vol.
II.# p. 77. Besides these three parts or volumes of [.book-title]#Piety Promoted,#
he was author of the following works:

[.numbered-group]
====

[.numbered]
_1+++.+++_ [.book-title]#The Harmony of the Old and New Testament,# and the fulfilling of the prophecies,
concerning our Lord and Saviour Jesus Christ,
and his kingdom and glory in the latter days with a brief
Concordance of the names and attributes given to Christ, etc.

[.numbered]
_2+++.+++_ [.book-title]#A Brief Testimony to the Great Duty of Prayer,# showing the nature and benefit thereof;
with above one hundred instances of God`'s answering prayer.

[.numbered]
_3+++.+++_ [.book-title]#A Trumpet Sounded,# or [.book-title]#A Warning to the Unfaithful,#
to prize the day of their visitation before it be over:
with a collection of the dying sayings of sundry persons.

====

John Whiting informs us, that John Tomkins died at Maryland Point, near Stratford:
probably at the house of his friend and preface-writer, Christopher Meidel; who,
from the title of one his pieces, seems to have lived at Stratford.
Christopher Meidel was a Dane, or, more accurately, a Norwegian by birth,
and educated at Copenhagen.
Coming to England, in the station of chaplain to Prince George of Denmark,
the husband of Queen Anne, he became preacher to the Danish church in London,
and afterwards pastor to an independent congregation in Nightingale-lane,
East Smithfield.
He was convinced and joined the Society of Friends about 1699.
He seems to have been intimate with Richard Claridge, whom, in 1706,
he attended to the burial of a woman-friend at Barking,
at which town R. Claridge then lived, which, by means of her son,
who was not a member of the Society, was conducted according to the accustomed rites,
in the public graveyard.
Claridge testified against the superstition and pageantry; and,
after the curate had read the service and was gone away, Meidel preached at the grave.

I have not found the time of his decease, but it appears from a letter of his,
dated 22nd of Sixth month, 1708, to our historian, William Sewell,
that he had been taken prisoner in France, probably on his return to his native country.
An extract from this letter may be acceptable to the reader:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Paris, 22nd 6th mo., 1708.

[.salutation]
Dear Friend:

That blessed God who is pleased sometimes to lead his poor travailing children into
paths of straits and difficulties, to try their faith and patience,
and to show his power and goodness in bringing them out again,
has brought me along hitherto, blessed be his name, and kept my poor soul from fainting,
and is still upholding and providing in time of need.
This day two weeks ago I was brought here as a prisoner, having been stopped at Pont,
and kept there, and at St. Lis, a week more.
I have, through mercy,
had other prisoners`' fare since I came in the Grand Chatelet here;
but my money has been expended for some time,
and a letter of credit which our friend John Davison ordered his correspondent
at Antwerp to give me on a merchant at Lisle (for I had some thoughts
of going that way) is in the hands of the Juge de la Police;
neither if I have it can it be of any service at present,
considering the circumstances of Lisle.

If you can find out a friend to give me a little assistance for the present,
it may be of service.
The Lieutenant Colonel examined me strictly, with a great deal of civility,
and after enlarged my prison, which at first was pretty strait and obscure;
yet the Lord was good there also.
I would be glad, if I should be continued here any time, to be somehow or other employed,
toward subsistence, if possible.
We are a great many prisoners of several nations and qualities.

As I was brought chained to other prisoners, through the streets,
I had to sound forth to the people, +++[+++in French]
"`Repent of your sins, O you Parisians,
and the good God will visit you with the saving knowledge of his truth,
and will aid you in the time of adversity which will
come upon all those who go on in their iniquities.`"
The people were very free to give money, which when I refused,
they gave to the other prisoners.
I am civilly or kindly used by most or all of the better sort.
I desire to hear from you when this comes to hand;
and that my dear love may be given to friends there, as if named,
and at Rotterdam and Haarlem; and when you write to England,
mind my dear love and brotherly respects to our dear friends there;
especially to W. P. So, with salutations of true love to you,
with due respects to your dear wife and children,
I conclude your poor obliged friend and fellow traveller,
who desires the prosperity of Zion,

[.signed-section-signature]
C+++.+++ Meidel.

--

John Field, also of London, who, before the death of Tomkins, was well known there,
as the author of many short pieces, several of them controversial,
next took up the work in which the latter had engaged, and, in 1711,
produced a fourth volume, of upwards of eleven sheets,
and having in it about fifty-four different narratives.
This volume has a long preface by an anonymous writer, and also another,
called [.book-title]#An Introduction,# by the compiler, Field.

The fifth volume came out in 1717,
and this likewise is owing to the diligence of John Field.
About fifty-seven deceased friends are commemorated by this volume;
which is about a sheet larger than the fourth.
It is ushered in by a preface of upwards of twenty small pages; which,
like that of the former volume, contains exhortation apposite to the subject of the book.
This preface is subscribed by Thomas Raylton, a printer, in George Yard, Lombardstreet.

John Field, like his predecessor Tomkins,
continued his attention to this means of stirring
up the mind to seriousness and to virtue,
almost to the period of his life,
though it was protracted to an age far beyond that of Tomkins.
For, after having published a third collection, forming the sixth volume, in order,
from the beginning, he finally closed this service and his life, in the year 1723,
at the age of seventy-five.
He was therefore even far advanced beyond the age
of Tomkins when he enlisted as his successor.
This volume, though it consists of upwards of nine sheets,
has accounts of only twenty-nine deceased friends;
but some of them are longer than usual.
Thomas Raylton again took up the pen as prefacer.

John Field had retired to Hammersmith, where he died;
but he was buried at Bunhill-fields, London,
and is described in the register of the quarterly meeting of George-Yard, haberdasher.
This was probably only descriptive of his company.
I have heard that his trade was a woollen-draper.
Thomas Raylton, of course, was his near neighbour, and probably his intimate friend.
He too laid down the body in the same year,
and his remains were interred in the same ground.

In the second edition of this sixth volume, in 1766,
there is added an account of this friend.
He was born in Yorkshire, in 1671, of parents not professing with friends;
but was convinced when about fourteen.
He suffered much for his steady adherence to what he esteemed his duty,
his parents being severe; but at length was apprenticed to a blacksmith,
in which service, though he laboured hard, yet,
as his master and mistress were solid friends, he passed his time comfortably,
and grew in religious attainment.

When he was about twenty-four years of age, he came forth in public testimony,
a service which he had long foreseen, and for which he seems to have been well prepared;
though until the day in which he first thus broke silence,
he had not seen his way clear for entering on that solemn work.
After this he travelled much in the ministry, and at length settled in London,
in the year 1705.
The following year he married Tace Sowle, daughter of Andrew Sowle,
who had been printer to the Society; and in 1718 was himself the printer.
Tace Sowle Raylton was probably his daughter, who, and Luke Hinde,
were afterwards printers, then Luke Hinde alone, and next his widow, Mary Hinde.

To these six parts or volumes, thus published by Tomkins and Field,
no additional volume was printed until 1740, when John Bell, of Bromley, near Bow,
Middlesex, compiled and published a seventh.
It contains thirty-two narratives, with a long preface by the compiler,
in about nine sheets.
Among other names in this volume is that of his own wife, Deborah Bell,
whom he survived upwards of twenty years, and of whom he thus winds up his account:
"`In humble submission to His will, who gave and has taken away, as knowing,
though it is my loss, it is her everlasting gain, I rest; and can,
in sincerity and truth, bless His name, who is worthy forever!`"

John Bell was the son of Reynold Bell, of Gill, in Cumberland, and born in 1681.
I have not learned when he came to London;
but I find that in 1708 he was a member of the Savoy meeting,
and had its certificate to visit Friends in Holland as a minister.
Soon after his return he married Deborah Wynne, above mentioned,
and settled with her at Bradford, in Yorkshire.
In 1715 they removed to London, and lived a while in Clement`'s-lane; and,
pursuant to the direction of the yearly meeting in 1723,
"`that no person`'s name be entered in the morning-meeting`'s book
as a minister till he or she produce a certificate from the monthly
or quarterly meeting to which he or she shall belong`" they were
both certified as ministers from the Bull and Mouth monthly meeting,
together with the before-mentioned John Field, Thomas Raylton, and several others.
Both John Bell and his wife were much engaged in travelling in the ministry.
Before her decease they had removed to Bromley, where, in 1738, Deborah departed,
and John survived her until so late as the year 1761, aged about eighty.

The seven volumes already mentioned have all been printed by the Hindes: Volume I. 1759;
Volume II. 1765; Volumes III.
IV. and V. 1754; Volume VI. 1766; all by Luke Hinde; and Volume VII., 1771,
by Mary Hinde; and are, I believe, sometimes to be met with,
bound together in three volumes, duodecimo.
From the publication of the seventh volume, by John Bell, to the year 1774,
this work remained stationary; but in that year, Thomas Wagstaffe, of London,
added an eighth volume, differing from the others, in small octavo,
of which it contains about fifteen sheets,
and has about sixty-six accounts of deceased Friends.
He has prefixed a short preface, and has added a short concluding address to the reader.

Eight volumes having thus been presented to Friends, and finding a ready demand,
the work again became scarce.
Accordingly, in 1789, John Kendall, of Colchester,
published a revised edition of the whole, except one, namely, Hugh Stamper,
in three volumes, twelves.
He has written a preface, containing a large extract from that of Meidel,
with reflections on the usefulness of the work.
It is printed by James Phillips, successor to Mary Hinde, as printer to the Society;
and has become the edition in general use.
In 1796, Thomas Wagstaffe again became the author of a volume, the ninth, which,
in about seventeen small octavo sheets, contains sixty-six narratives,
together with a short preface.
It has undergone a second edition in twelves,
which has been generally sold as a fourth volume of Kendall`'s collection.

Thomas Wagstaffe was born at Banbury, in Oxfordshire, in the year 1724.
He passed the chief part of his life in London,
where he long carried on the trade of a watchmaker;
but in the decline of life retired to Stockwell, Surry, from which place he dates his last preface.
He, however, left that place when an old man, for Chipping Norton, in Oxfordshire,
where he had relations, and died there in 1802.
He was particularly addicted to inquiries into the transactions of ancient times,
so far as they related to Friends; and had a memory stored with anecdote.
His papers relating to such subjects having been mislaid since his death,
it is probable that some pleasant if not valuable information is lost.
In 1776, he prepared for the press,
some account of the life and gospel-labours of William Reckitt, of Wainfleet,
Lincolnshire;
a little book well worth the perusal of such as love to read accounts
of the travels of Friends devoted to the cause of truth.

Besides the publication and republication of most of these volumes,
some selections from them have been printed; particularly one in 1781, by James Phillips,
in twelves, forming a closely printed volume, entitled, [.book-title]#Brief memorials, etc.,
Particularly of Young Persons,
Extracted from the Eight Volumes Entitled Piety Promoted.#
William Rawes also, of Marnhull, in Dorsetshire, formed a similar, but smaller selection,
under the title of [.book-title]#Examples for Youth.#
William Rawes was an acknowledged minister in good esteem,
and very serviceable in the discipline, in the part where he resided.
He died at Marnhull, in 1805, in his fifty-first year.

This work,
deserving as it is to be made known wherever there is a genuine taste for serious,
religious, Christian subjects, unmixed with superstitious forms,
has not yet been much exhibited to foreigners by translation.
Yet in the year 1770, Mary Hinde published a selection of seventy-two of the narratives,
translated into French by Claude Gay, a native of France,
but long a resident in this country.
It forms a duodecimo volume of upwards of eleven sheets.
Claude Gay has translated all the accounts in the first volume of Tomkins.
From each of the six succeeding volumes, he only takes an account of one man,
and one woman; and he adds two accounts from manuscript, namely,
of John Goodwin and Elizabeth Kendal; both which are in T. Wagstaffe`'s eighth volume.
He has a short preface or introduction, giving some account of the work in general;
in which he makes a useful remark to the following effect.

[quote]
____
I have no further hint to give you, reader, than this;
that if you have received the truth in the love of it,
and should perceive that some of the descendants of this
people do not walk in the steps of their ancestors;
and even that some having with Demas loved this present world,
have wholly turned their back on the truth, be not discouraged,
for truth descends not by inheritance.
Neither be puffed up against them; but stand in the holy fear of God;
and take the advice of the apostle Paul, +++[+++"`Well,
they were broken off through unbelief, and you stand by faith.
Be not high-minded, but fear.
For if God spared not the natural branches,
take heed lest he also spare not you.`"--Rom. 11:20-22.]
that, having finished your course, and kept the faith,
you may receive the crown of righteousness, and enter into the joy of your Lord.
____

Next he inserts an exhortation extracted from the writings of William Penn,
and then he gives an abridgement of the preface of Tomkins.
In the accounts themselves, he simply translates the narrative;
but he gives the expressions of the dying Friend in parallel columns of French and English.

Those who expect an elegant French style in Gay`'s translation will certainly be disappointed.
He probably was not a man who had had the help of a liberal education;
and he had imbibed much of an English idiom from his long residence in England.
But though he was not an eloquent man, he was something better:
he was an upright, simple-hearted Christian.
His birth-place was Lyons, in France,
and his religion at first was that kind of Popery formerly current in France.
But even the inspection of a popish version of the New Testament
was a means sufficient to detach him from the superstition of Popery.
On perusing Acts 17:24, etc., "`God, who made the world, and all things therein,
seeing he is Lord of heaven and earth, dwells not in temples made with hands,
neither is he worshipped with men`'s hands,`" etc.,
the doctrine of transubstantiation (in which, as he told a friend,
the Papists believe that the consecrated wafer is changed into the body, blood,
soul and divinity of Christ,) appeared to be false; and the adoration of the host,
idolatrous.

In fine, he forsook the Romish communion, and went to live at Jersey,
in order to be among Protestants.
Here he met with [.book-title]#Barclay`'s Apology;#
and this book was the instrument to determine him
to settle in the principles and profession of Friends.
He suffered some persecution in Jersey, and was even at length banished,
under pain of corporal punishment; but this was set aside by order of the king.
He, nevertheless, took England for his home in the year 1745,
and died at a very advanced age, at Barking, in Essex, in the year 1786.
He translated, besides the work which has here introduced him to notice,
the first part of William Penn`'s [.book-title]#No Cross, No Crown.#
In private life, he was industrious, very unassuming, and harmless.
In his public ministry, sound and fervent, but tender in spirit.
He travelled at times in the exercise of his ministry, and often on foot;
nor did he confine his labours to the country in which he dwelled;
he extended them to Holland, Germany, and Switzerland.
In a later visit, namely, to Guernsey and the other islands,
he wrote and distributed a paper in French, of which the following is a translation,
and which is worthy to be preserved.

It has already been said that he was a humble man, and consonant with this character,
it may be observed that he was frequently engaged in prayer,
in which it was usual to prefer his petitions in these appropriate terms,
"`For the merits of Christ.`"
He was enabled to endure a lingering disease with great patience,
and declared to those who conversed with him, that all fear of death was removed.

[.embedded-content-document.paper]
--

[.letter-heading]
To The People Of Guernsey.

[.salutation]
My Friends of Both Sexes,

As I passed along your great street, one market day,
I beheld your souls with the eye of faith,
as part of the purchase made by the blood of Christ.
My heart was affected, and deeply impressed, and softened, so that I shed tears.
So I entreat you, in the name of this divine Saviour, do not defile these souls,
which are so dear and precious, by any wilful sin.
Among other things, do not take the name of God in vain:
for he will not hold anyone guiltless who takes his holy name in vain.
God would save you.
Why should any of you destroy yourselves?
Abstain from drunkenness, and from all excess: and even from every appearance of evil.
Love one another, as Jesus Christ loved you.
Apply yourselves to the witness of God within you,
whose holy manifestations and discoveries, as you submit and obey,
will do much more for you than all you can hear from me, or from anyone else.
And though it is in the love of the gospel,
that I invite you all to come and taste how good and merciful the
Lord is toward all those who return to him with their whole heart;
yet I am but a poor instrument,
who have as much need for Him to preserve me in the hour of temptation, as any of you.
But this witness of God is his word, even the Word of Life,
which is able to save your souls.
Amen!

[.signed-section-signature]
Claude Gay.

[.signed-section-context-close]
Guernsey, 1st Seventh month, 1776.

--
