== Chapter 16

[.chapter-synopsis]
* George Gibson
* Thomas Cash
* Samuel Dyer
* James Pemberton

GEORGE GIBSON, of Saffron Walden, in Essex, was the son of Francis and Mary Gibson,
of Royston, in Hertfordshire, where he was born the 15th of the Twelfth month, 1731,
according to the old style.
He settled within the compass of Thaxted monthly meeting,
when he was in his thirty-second year, and came forth in the ministry in his forty-first.
He was a man of great moderation and integrity,
appearing to be much redeemed from the spirit of the world;
and a very diligent attender of meetings for worship and discipline;
in which not only his public ministry, at times,
but the reverence of his spirit in silent waiting, was instructive and encouraging.
In his solemn approaches to God in supplication,
he seemed to be clothed with the genuine spirit of prayer; and in latter life,
as he drew near to the confines of the world to come,
he seemed to have the more frequent access to the great object of the saints`' faith.
He attained to the advanced age of seventy-six, when, in full assurance of peace,
he was gathered on the 23rd of the Seventh month, 1808.

Several months before his departure, his health declined;
and he would frequently express his apprehension
that his continuance in time would not be long;
but he spoke of his close, as of the consummation of his desires; and of his change,
as unspeakably glorious.
It had been his practice for several years, to note down in writing, occasionally,
the feelings of his mind: of which memorandums, a short, but sweet collection remains.
In one of these, dated more than three months before his decease, he says,
'`I am sensible of an increase of such bodily pains,
as indicate the dissolution of this tabernacle; but think I can say,
I feel no alarm at it.
Yet it looks awful.
O Lord, I humbly pray you, be near me, and strengthen me to look to you,
in the time of conflict: O, you that have been my rock and my refuge, my deliverer,
and my hope of eternal salvation.`'

He was enabled to bear his ailments with great resignation; and,
as we find many other pious Christians do at such times,
he prayed that he might not fall into impatience.
Thus we see, that to the last, the creature has neither store-house nor barn.
Every good gift, and every perfect gift, must still come down from the Father of lights;
until complete and accomplished redemption crowns the whole,
and inseparably unites it with him forever.

The seat of the disease which gradually broke the bond of mortality, was the stomach;
and this organ at length failed in its functions, so as to resist all food,
and to occasion great nausea and pain.

When in health, he read much in the Scriptures;
and when he was too weak to be able to read,
he continued to derive comfort in hearing them read.
The thirteenth chapter of the first epistle to the Corinthians, in particular,
had so much place in his mind, that at his request, during his illness,
it was read to him by four different persons, at four separate times.
This is the memorable chapter where the apostle enumerates
the transcendent nature of love.
Our translators have somewhat debased it, by rendering this word by charity;
and I have often wished every reader, in perusing it, to substitute in his mind,
as he goes along, the genuine word, love.
A very few days before his close, he had the following passage from Isaiah read to him:
"`Comfort you, comfort you, my people, says your God.
Speak you comfortably to Jerusalem, and cry unto her, that her warfare is accomplished,
that her iniquity is pardoned, for she has received of the Lord`'s hand,
double for all her sins.`"

He remarked, during his illness, that the company of such friends was pleasant to him,
as his spirit had been, and was, bound to in the everlasting covenant,
which would not be dissolved with time.
'`Rejoice with me,`' once he said,
'`that I shall soon put off these shackles of mortality;`' or to that import.
At another time,
he said that the expressions of Job Scott were much in his remembrance and experience; '`for,`'
said he, '`I never saw a time before,
when all things not criminal were so nearly alike to me,
in point of any disturbance to the mind.`'
The following also, spoken at different times,
demonstrate the object of his thoughts and hopes.`'
I have a glorious prospect in view, and that is more than words.
The enemy is busy; but not able to shake my confidence in the everlasting arm.
The great Master himself experienced temptation and suffering;
and how can his poor servants expect to escape them?
Dear Lord, when will you say, it is enough?
The Lord is progressively doing his work; and, I believe,
taking me home to a glorious inheritance.`'

He frequently uttered, with great solemnity, the genuine filial address, '`My Father,
my Father!`' and sometimes added, '`My heavenly Father.`'
Thus he seemed to exemplify the declaration of the apostle, "`Because you are sons,
God has sent forth the Spirit of his Son into your hearts, crying Abba.`"

Two days before his close, though he was not then confined to his bed,
and there appeared a probability that he would continue some time,
he sent for a person not a member of our Society,
and took leave of him with great composure and firmness;
intimating that it would be the last time he would see him; and adding,
'`If my neighbors inquire after me, tell them that I die in peace with all men;
and with my God.`'

The next day he was chiefly confined to bed, and in the forepart of it,
he requested that he might not be disturbed, as he thought his end to be near.
Afterwards he expressed himself in these words:
'`I have been partaking of the pure stream, that flows from the throne of God.`'
In the afternoon he had a fainting fit; but recovered, and passed the night composed,
and clear in his faculties.
The following day, he suffered great bodily pain, and difficulty of breathing;
but was also clear in his intellects, and was preserved in great patience.
In the afternoon the fainting returned, and between three and four, the conflict ended.

[.asterism]
'''

THOMAS CASH--of Morley, Cheshire,
a man generally esteemed and beloved in our religious Society,
I have not to record many of what are commonly considered dying sayings;
yet as he died in great peace, after having lived in great dedication,
a short survey of his rise, his course, and his decline, will, I believe,
be encouraging to the Christian traveller.

It appears by the testimony which the friends of his own meeting have given of him,
that he was born at Alderly, the 13th of the Eleventh month, Old Style, 1739.
His parents were members of the Society of Friends; and he was a great comfort to them,
by his industry and filial affection;
but he does not seem to have been remarkable for
any particular attention to the concerns of religion,
until his twenty-fourth year.
About that time, however,
he was powerfully and effectually visited with "`the
day-spring from on high;`" his mind became much humbled;
and he often sought solitary places,
in which to pour forth his cries to the Author of all good,
for reconciliation and acceptance with him.
He was made willing to submit to the baptisms which
Infinite Wisdom allotted for his purification;
and he gradually became conspicuous for the fruits of holiness; particularly meekness,
humility, piety towards God, and good will to men.
From this time he was remarkably diligent in his attendance of meetings,
and made his temporal concerns give way to his religious duties.

In the thirty-second year of his age, and after many deep preparatory exercises,
he came forth in the ministry.
For several years his testimonies were short, and delivered in great simplicity.
Indeed, simplicity was his characteristic through life.
He was not one who would be commonly esteemed a man of five talents;
but he occupied honestly and wisely, with those with which he was endowed;
and as he steadily pursued his course, love and esteem followed him.
By degrees, he was much enlarged;
and most parts of the Society in these kingdoms were witnesses of his gospel labors.
These, however, were far from being restricted to the Society alone;
he was eminent for appointing meetings for the inhabitants
in general of the places in which,
in his religious travels, his lot was cast.
His meek deportment and circumspect conduct adorned the doctrine which he preached;
and in domestic life, he was kind to all around him.
During the time he was in a business which occasionally
introduced him into the converse and hurry of the world,
it was his frequent practice to break off and retire,
to seek for a renewal of strength from Him whom he
desired to acknowledge in all his ways;
but about fourteen years before his decease, having obtained a competency,
he declined further business, that he might be fully at liberty for religious service.

He had been for many years almost a constant attender of the yearly meeting;
and he came to that in 1808, in a state of health so weak,
as to be unable to attend all the sittings;
yet he had then in prospect a visit to several of the western counties.
This, though with considerable bodily suffering, he performed;
and having been nearly five months from home,
he returned about the middle of the Ninth month, with his bodily strength much exhausted,
but with a mind fraught with thankfulness and praise.

The following letter, written a short time after his return from this visit,
is interesting, and shows the humble, grateful state of his mind:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Morley, 18th of 10th month, 1808.

[.salutation]
Dear Friend, John Waring:

I have been at home rather more than a month.
I was on my journey about five months, and not well one day in all that time.
But I think I may with thankfulness say, that I had not even a murmuring thought,
either by day or night, the whole of the time.
The Almighty, in tender mercy and abundant compassion, was very gracious to me,
from one step to another, +++[+++during]
the whole of it; and my friends`' kindness very great in every place.
The remembrance of such kindness often causes my eyes to overflow with tears of thankfulness;
and I do not recollect one instance of shyness,
either among the rich or those in lower circumstances, while I was out; and the Almighty,
in unspeakable lovingkindness, was strength in weakness, riches in poverty,
and a present help in every needful time, to whom alone belongs all praise,
world without end.
Amen.

--

In the few meetings which he attended after his return,
and especially in his own particular meeting,
he was more than commonly enabled to evince the continuance
of the concern for the cause of truth and righteousness,
which, for the last thirty-five years of his life,
he had been so zealously endeavoring to promote.

Nearly a month after his return, and before he was confined to his house,
I had an opportunity of paying him a visit, and it was a memorable one.
He was then laboring under the disease which was
the means of loosening the bonds of mortality,
which was, I believe, a dropsy in the chest,
so that his breathing was affected by the little
exertions he made to accommodate his visitors.
He spoke to us of his late journey, during which he said he had not had one day`'s health.
In some of the latter stages of it, particularly when he was in the vicinity of Bristol,
his nightly sleep had been much broken.
He was often waked by the great difficulty of his breathing;
but on these occasions he said he felt the goodness of the Almighty so near him,
that it was no trouble to him to remain awake.
An impaired memory prevents me from relating or recollecting much of his conversation;
but his citizenship seemed to have been much "`in heaven;`" and I may say,
without any strain of expression, that I have seldom paid any one so sweet a visit.

Soon after this, as we learn from the testimony of Morley monthly meeting,
from which I have extracted most of the foregoing narrative,
he was confined to the house, and, during the whole course of his illness,
was preserved in much patience and resignation,
those general attendants on the closing steps of the path of the just.

He often said that the goodness of the Almighty was great to him,
comforting and supporting him under his bodily sufferings.
That appellation of the Supreme Being was one which he most commonly used,
in speaking of the dealings of the Lord with his soul;
and it is an appellation in which the creature,
humbled under a sense of its own infirmity, will always have reason to delight.
The gratitude which he expressed for all the little services which were done to him,
and the peaceful serenity which evidently covered his mind,
were comfortable and instructive to such as visited him.
Thus his outward man gradually decayed, until the 16th of the First month, 1809, when,
with an understanding unclouded by the frailty of his frame,
and with the power of utterance continued to the close, he quietly breathed his last.

Having been somewhat struck, or rather agreeably affected,
with some concluding expressions,
which the Friends of Morley monthly meeting have
subjoined to their testimony concerning Thomas Cash,
I think them worthy also to be preserved in this place.
'`We feel,`' say they, '`our loss in these parts, where the laborers are few; but we know,
and happy, may we not all say, for those who do know, the Rock remains,
the Foundation stands sure.
May we pray the Lord of the harvest, that he will send forth laborers into his harvest.`'

[.asterism]
'''

SAMUEL DYER, of Bristol, was born in that city, the 10th of the Seventh month, 1747.
He was strictly educated in the profession of the church of England,
which was that of his parents.
It appears, from some account left by himself, that at the early age of seven or eight,
he had strong religious impressions.
They were the means of exciting in him fervent desires
for deliverance from the propensities of fallen nature;
which seemed to overcome his best resolutions, and involved him in distress.
When he was about thirteen years of age,
he was further aroused to a sense of his condition, by means of a fit of sickness.
He beheld the dreadful consequence of sin,
and was enabled to pray for redemption from its bondage.
'`In my distress,`' says he, '`I cried unto the Lord; and he heard me, and was pleased,
in degree, to lift up the light of his countenance upon me.`'
The effects, however,
of this visitation do not appear to have been long perceptible to himself;
and his good resolutions, he says, '`vanished like a morning cloud.`'
Nevertheless, it is probable, that the good seed sown in his childhood and youth,
was never permitted to perish.

His friends, in their testimony, relate,
that he went on under many deep exercises and trials,
and when he was about seventeen years of age,
felt himself inclined to attend the meetings of Friends, in Bristol.
He was tired, as he himself remarks,
of the forms and ceremonies in which he had been educated,
and of a ministry which did not relieve his distressed mind.
In his attendance of our meetings,
although he found it difficult to keep his mind in sufficient stillness,
probably from the bias of his education,
as well as from the inherent propensity of the mind to be in action; he, nevertheless,
felt much satisfaction; and at length joined the Society.
About this time, he makes this acknowledgment in his memorandums: '`As to the Divine life,
I have this remark to make, that I should grow more in it,
was I but more in the stillness;
even until the whole birth of the Son of God was brought forth in my soul.
Be still, therefore, O, all that is within me;
and know the Lord`'s strength and power to arise.`'

To this power, about the time of his becoming of age,
he apprehended it his duty to appear in public testimony;
and endeavoring to continue in the faithful discharge of that duty,
he was enlarged in his gift, and often exercised in it,
in the city and vicinity of Bristol.
He afterwards, at different times,
found himself engaged to visit Friends in their meetings in various counties, and,
in some places, in their families.
A visit of this sort in London was among some of his later gospel-labors.

In domestic life he was an affectionate husband and a tender father;
but the limits of his family did not bound his fatherly care.
The youth in general were objects of it;
and some of them have had cause to bless the Lord on his account.

He was long subject to a disease of the asthmatic kind,
which often occasioned him to be confined at home;
and he had been laid up with it during the family visit in London.
His final illness seemed at first only a fit of his accustomed complaint;
but it increased at length so as to confine him to his chamber, and,
after about ten days of this increased state of ailment,
was the means of conducting him to his close.

He suffered much pain in his body; but resignation composed and supported his soul.
Previously to this juncture,
he had often remarked the comfortable state in which his own mind was;
and when his family were setting off for meeting,
from which bodily weakness was detaining him, he used to observe,
that when he was young he was a diligent attender.
'`Go,`' he would say, '`and I hope the Lord will be with you, and give you a good meeting.`'

While disease was thus accelerating the hour of his release,
he was at different times much engaged in prayer.
At one time he prayed for his native city:
'`The Lord bless and preserve this city and its inhabitants;
and draw unto himself thousands and tens of thousands.`'
To a young man who attended on him, he said, '`There is a reality in religion,
and I find it so: nor have I followed cunningly-devised fables.`'

The day before his departure, he expressed himself to this effect:
'`I believe it right to tell you my faith.
I have been a sinner, and have gone into many follies in my childhood; but,
by the love of God in Christ Jesus, I have been enabled to come,
as a poor trembling penitent, to Him, who is the friend of sinners; and by thus coming,
and abiding under the power and operation of his Spirit upon my soul, trusting in him,
and not in my own righteousness, I am what I am.
And I am persuaded, that neither death nor life, nor angels, nor principalities,
nor powers, nor height, nor depth, nor any other creature,
shall be able to separate me from the love of God, which is in Christ Jesus our Lord.`'

The day on which he died, taking leave of a friend, he said,
'`I find I have enough to do to bear the pains of the body.
It is well for me that I have done my work; and I have a full assurance that all is well.
Farewell.
Give my love to Friends.`'
A few minutes before his close, he was again engaged in supplication, after which,
at the age of about sixty-two, on the 30th of the First month, 1809,
he quietly resigned his spirit.

[.asterism]
'''

JAMES PEMBERTON, of Philadelphia, died there in his eighty-sixth year,
the 9th of the Second month, 1809.
He had employed a long life in various occupations of usefulness,
and of active benevolence.
To the service of the Society of Friends he devoted a large portion of his time;
and his love for the cause of truth, his unusual assiduity in what he undertook,
and his long experience, all exercised and used in the fear of his Creator,
contributed to make him eminent.
Nor was he circumscribed by the limits of our Society.
More public objects of service to his fellow men also engaged his attention,
and had his assistance in their promotion: particularly,
he was a strenuous promoter of the measures taken for the abolition of the Slave Trade,
and the relief of the black people.
He was president of the Philadelphia society for improving their condition,
in which station he succeeded the well-known Franklin, who had presided at its rise.
In more early life, before the Revolution had introduced a new system of government,
he had long been a member of the colonial assembly of Pennsylvania,
as representative for his native city.
In short, he seems to have walked usefully and honorably through life;
and to have descended calmly to the borders of the grave; and yet,
in surveying the unknown region which lay beyond it, he dared not to trust,
for a peaceful establishment in it, on any of his former works of righteousness.
All his dependence was on his Savior: and that he found to be an anchor to his soul.

As he felt himself gradually declining,
he looked back to the number of years which he had passed.
Compared with the boundless existence before him, they appeared but as a moment;
but yet he perceived them to have been marked with so many preservations,
that his gratitude was afresh excited to his Almighty Benefactor and Preserver.

Within somewhat less than a month before his end, he had a fainting fit.
After he was come to himself, he remarked,
how awful it was to be on the verge of eternity.`'
But, '`continued he, '`we have a Mediator, an Intercessor.
My mind has, for some time past,
been unusually impressed with the vast importance of the Redeemer`'s mediation.
I have never before seen it with the same clearness.
I am free from pain of body or mind.
The prospect of my change is awful; but, after all, I have nothing to trust to,
but the merits of my Redeemer.`'

The next day he said to Thomas Scattergood,
(a Friend well known and much beloved in this country,) '`I am thankful that,
through divine mercy, I feel an evidence within me, that I am not cast off.
It has been the great desire of my life,
that at the solemn close I might be favored to feel that evidence.
It was all that I wished.
It seems to me that I cannot continue long, but I desire to wait patiently,
and to labor after a perfect resignation to the Divine will.
The longer I live,
I see more clearly that it is not moral righteousness that will do for man.
Nothing but the righteousness of Christ will avail us.
We can claim nothing from our own merits.
We owe all to Divine mercy.`'

Nearly two weeks after this, he said to a friend who came in, and asked him how he was,
'`I am on the confines of eternity, and find nothing in my way; but all is mercy,
mercy!`' Two days after this, after an interval of silence, he exclaimed, '`Oh,
the`' blessing of an easy mind! who can describe it?
It is all owing to Divine mercy, to nothing else: and this, I hope, I enjoy.`'
In the same day he addressed a grandson, who was with him, in a pathetic manner,
as follows:
'`I have often been thinking that whenever any suitable opportunity should offer,
I would unburden my mind to you.
And it has now arisen in me to address you with the words of king David to his son formerly.
Solomon, my son, know you the God of your fathers.
Serve him with a perfect heart, and with a willing mind.
If you seek him he will be found of you; but if you forsake him,
he will cast you off forever.`"
And what a dismal state is this: to be cast off from the presence of that Being,
who is the greatest friend of mankind.
Nothing can be more dreadful.
These expressions, I remember when young, were addressed to me by a very worthy friend,
John Evans, of North Wales, in a letter he wrote to me on the death of my father.
I wish you to impress them deeply on your mind,
and you will find them useful after I am gone.
It is impossible to estimate the advantage of living under Divine protection.
His mercy and goodness are incalculable.`'

In the evening of the same day, which was First-day,
when his children and grandchildren were around him,
he addressed them in an instructive manner, and on several subjects,
some of which it may be useful to introduce here, in a form somewhat abridged.
After recommending his family to live in harmony, '`My dear Father`' +++[+++i.e. Israel Pemberton]
said he, '`was a very upright man.
As occasion offered, he gave advice to us, his children;
and one of his most frequent admonitions,
and which made very great impression on me in early life, was,
To live in the fear of the Lord.
It is the beginning of wisdom.
It is indeed wisdom, and it is founded on love: as those +++[+++whom]
we love, we must fear to offend.
If this principle is attended to through life,
you will not fear when the solemn period shall come.
All will be peace.`'

'`David, speaking of Almighty Providence, says, that "`His mercy endures forever.`"
His mercy has indeed no end--no end!
His goodness has followed me;
and I have been favored in my present indisposition
much more than I had any reason to expect,
and much more than I had deserved.
I recommend to you the diligent perusal of the Holy Scriptures.
Make yourselves acquainted with them.
In them you will find an abundant source of instruction and edification.
Reading the lives of pious men of former ages,
and observing how they were supported under their trials by the Divine arm,
tend very powerfully to place our dependence on Him,
from whom comes all our support-all our benefits:
and to whom it is impossible to make a sufficient return for his inestimable goodness.
My parents took great pains with me,
and I received very great advantages from the constant and unwearied
care of a most affectionate mother`' +++[+++i.e. Rachel Pemberton].

The following day he said to a Friend,
'`It is a great consolation to be free from a guilty conscience at such an hour as this:
and that, I believe, I am.
We have all fallen short, far short, of the glory of God;
but we are under his mercy who cares for us.
There is one thing which is not enough inculcated
in our meetings --the mediatorship of the Son,
our Lord and Savior Jesus Christ:
and I have never seen this so manifested as in my present indisposition.`'
He then adduced some texts of Scripture relating to this subject, with remarks on them,
as: "`No man comes to the Father but by me.`" '`It is a great mercy,`' said he,
'`that God in his wisdom has appointed such wonderful means for the redemption of mankind.
"`We have a high-priest, touched with the feeling of our infirmities.`"
Not,`' he observed, '`such a high-priest as is ordained by man;
but a high priest who is really touched with a feeling of our infirmities.
This mediation of the Son, with the Father, is a great mystery.`'

The following day, in the evening, on being assisted to get into bed, he exclaimed,
'`How many hundreds and thousands there are now sick in the world,
and have nobody to assist them: and I have so many!
How am I loaded with blessings!`' This was on the last day of the First month.
The succeeding day, this was his confession.`'
Never was I more convinced of the goodness of redeeming love`'

In another week, his close approached with perceptible steps.
He had mentioned his doubt of surviving the night of the 7th of the Second month;
but on the 8th, about noon, after some refreshing sleep, his countenance brightened up,
and he thus expressed himself to his only surviving child.
'`As I draw nearer my close, I find the tormenting fear of death taken away,
through the intercession of the great Mediator between God and man.
I am very low,
but not so low but I can yet commemorate the incomprehensible
mercies of an all-gracious God.`'
To a particular friend that day, he said, '`Oh, that I had strength;
that I had the strength of an angel, that I might declare the goodness of the Lord to me;
but eternity is too short to utter all his praise.`'

He continued, '`The Redeemer has said, "`I am the way, the truth, and the life.
No man comes to the Father but by me.`"
And he told his disciples, before he suffered, not to be troubled.
"`You have believed in my Father: believe also in me.
In my Father`'s house are many mansions.
If it were not so, I would have told you.`"
He is, indeed, the Alpha and the Omega, the beginning and the end, the first and the last.
What a blessed company are already gone there before me!
I feel the time of my own departure draws nigh.`'
As he was holding the hand of this visitor, on taking his leave, he said, '`I love you,
and all them that love the Lord Jesus in sincerity.
Farewell.`'
These were the last words which he spoke on a religious subject.
The next day he put off mortality.
