== APPENDIX

=== Containing some Account of Deceased Friends, of an Earlier Date than the Preceding

[.asterism]
'''

JOSHUA MIDDLETON.
At the distance of nearly ninety years, I am disposed to commemorate,
with a short narrative, my maternal great grandfather, Joshua Middleton, of Newcastle,
who died there the 27th of the Eleventh month, 1720.
In doing this, and in looking over the few papers relating to this ancient Friend,
which are in my possession,
I am confirmed in the truth of a common remark of pious persons,
'`That the memory of the just is precious.
It is encouraging to observe, that the general trials, deliverances, habits,
and sources of hope, are the same at every period of time.

Joshua Middleton was born at Darlington, in the county of Durham, in the year 1647.
His parents were of the Presbyterian profession, strict in their way,
and careful to educate their son in the principles of religion which they professed.
He often acknowledged that their care had been of much service to him,
in keeping him out of the vanities of life; and often, with much tenderness,
would recommend to parents, to nurture their children in the fear of the Lord,
and in the diligent reading of the Scriptures.

In his youth, after some years of communion with the Presbyterians,
he was convinced of the principles held by Friends, and joined their Society.
He underwent with this people several sufferings and imprisonments,
which he supported with patience.
Not long after he joined the Society,
he believed it his duty to come forth in the work of the ministry,
and in this service he travelled in many parts of England, and in Scotland.
His brethren of the quarterly meeting of Durham, in their testimony, say of him,
that as he increased in years, the greater was his care of the churches;
and that he exhibited a good example to Friends,
by his constant attendance of monthly and quarterly meetings,
though often under much weakness.
His testimony was plain and intelligible.
He was a man of a meek and peaceable spirit, and much beloved among all sorts of people;
and his endeavors to compose differences were very prevalent.
He was also liberal to the poor, and a great promoter of such liberality.

I am not informed at what period of his life he came to reside at Newcastle.
He had first lived at Raby, a village near Staindrop, in Durham.
I have a letter from him to his daughter Hannah, the wife of Joseph Gurney, of Norwich,
(of whom there is an account in the collection of testimonies concerning
public Friends deceased,) written about four months before his death.
It shows the temper of his mind at that time; and,
if the partiality of a descendant do not deceive me, is worth preserving.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Newcastle, 16th Seventh Month, 1720.

[.salutation]
Dear Hannah,

I had yours, whereby understanding of your health, am glad:
and though I could like well more often to know of your state, yet,
as I receive information thereof from, with whom we have now a frequent correspondence,
I do not take offense at your writing seldom:
nor must you expect many letters from my hand, it being now a +++[+++great]
trouble to write.
So as Providence has placed us at such a bodily distance,
we must endeavor to converse in spirit, remembering one another,
and praying for one another, that we may be preserved out of the evils of this world,
and over all the temptations and besetments that we may
be attended with in this time of our pilgrimage therein;
and willing and resigned unto the good pleasure of our God,
when he shall call us out of it.

This is what I am laboring for as on my own behalf: so would have you use like endeavor,
that we may not sorrow immoderately, or be surprised;
but waiting all the days of our appointed time, till any of our changes come.
So with remembrance of my true love, with my wife`'s, to you and your husband,
and your little ones, and to brother Gurney and his family,
and all the rest of relations,
I conclude this with my fervent prayer to the Lord for his blessing on you all:
not forgetting and her children.

I say,
as the Lord has favored all of you with competent increase in the things of this life,
my desire and prayer is, that your portion may not be in them;
but that you may be blessed with spiritual blessings in heavenly places in Christ Jesus.
Such are the fruits of his blessed Spirit: wherein that you may increase and abound,
is the prayer of your loving father.

[.signed-section-signature]
Joshua Middleton.

--

His last illness seems to have been a painful one; for his son,
in a letter to another of his daughters, settled at Norwich,
dated one week before the departure of their father, thus relates of him:
he had been relieved from his pain and retchings by a removal of the stricture; '`but,`'
says his son, '`he has taken nothing these two or three days,
and grows weaker and weaker; but continues sensible,
and many living expressions drop from him.
I doubt not but God has heard his prayer, and sweetened his bitter cup,
which he said he had to drink.
Soon after he had so said, he broke out into these expressions:
"`Blessed be the name of the Lord!
He has sweetened my cup.
I am refreshed.`"
As we were sitting one night about him, he bid us go to bed, and let him go,
and commit him to the Lord; and he should be received to mercy.`'

[.asterism]
'''

CHRISTIANA PENN was the wife of William Penn, a grandson of the memorable William Penn,
founder of Pennsylvania.
Her parents were Alexander and Jane Forbes, of London.
Jane Forbes was the youngest daughter of Robert Barclay, the apologist,
and of Christiana his wife, (an account of whose close is to be found in Dying Sayings,
Part Eighth.) Christiana Penn died the 1st of the Ninth month, 1733; but as there is not,
that I know of, any printed account of her,
I am induced to abridge an ancient manuscript, one which may, at least,
be interesting to such as like to trace the descendants
of men who have been eminent for virtue;
and will tend, like the rest of this collection, to promote piety,
by showing its blessed consequences at the close of mortality.

After a longer term of previous suffering than often occurs, her first child, a daughter,^
footnote:[Who died a widow, 1803, named Gaskell.]
was born.
Her husband and friends then began to hope;
but she had a view of her approaching dissolution, and endeavored to be prepared for it.
She was fervent and frequent in prayer, and earnest with her mother^
footnote:[She was one of Robert Barclay`'s children, of whom John Gratton says:
'`As they grew in years,
they grew also in the knowledge of the blessed Truth;`'
which he much attributes to the care of their mother.]
to join her in it.
She had a firm confidence that it would be well with her,
often declaring that she did not wish to live.
She mentioned with affection her near connections in life; yet said,
that so great was her comfort in the prospect and assurance of future bliss,
she could freely part with them all.

She said the Lord had been so gracious as to forgive her sins,
alluding to the follies of her youth, which she then esteemed to have been vanities,
and therefore she earnestly desired, if it were his will, that she might be removed;
for she was then ready, and certain of eternal happiness;
but she feared that it might not be so well if she should live longer.
'`Have you not given me up?`'
said she to her mother.
'`I desire you will give me up freely, and not endeavor to hold me, or interrupt me,
but let me go; I am ready, and have nothing to do but to die.`'
At another time, her father inquired of her whether she would be willing to live,
if it pleased the Lord.
She answered, '`God forbid, but that if he have any service for me, I should be willing;
but if not, I desire to die; for now I am ready, and have nothing to do but to die.
My joy is full.`'

She expressed a tender and affectionate regard for her friends, but most for her husband.
She declared that she had great satisfaction in her marriage,
and that she loved him with all her heart; and that her concern for him,
and desires for his good, were very great and strong.
Her patience in her illness, and her fear of offending her Maker by complaining,
were remarkable: careful of her words, that she might not offend with her tongue.
One time being in great pain, and finding herself thirsty, she said,
'`Now my tongue wants cooling, but soon I shall be in Abraham`'s bosom,
where all my sorrows will be at an end, and I shall rest forever.
I have nothing to do but to die.`'
This was frequently her expression.
She would continue in supplication sometimes for hours together.
The sweet, heavenly disposition she was in the latter part of her time,
even surprised those who visited her.
She was so filled with a sense of the favor and goodness of God,
and with firm faith in her future happiness,
that she declared her eternal joy was begun.

She was allowed her understanding perfect to the last.
She often inquired the hour of the day;
was glad when she thought the last was approaching;
firmly and quietly took her final leave; and, without a groan, or the least uneasy sign,
at the age of eighteen years and a quarter, she ceased to breathe.

[.asterism]
'''

MARY NEALE was the daughter of Peter and Rachel Peisley, and born at Ballymore,
in the county of Kildare in Ireland, in 1717.
Her education was among Friends: but an indulgence, too little restrained,
in the company of such as have not the cross of Christ in esteem,
led her into deviations in behavior from the simplicity of her profession;
which at length occasioned a deep remorse.
During several years she thus in some degree gave way to hurtful propensities.
She was not at times without secret reproofs but a fall from a horse,
by which she considered herself to have been in danger of a dislocation of the neck,
and of a sudden death, seems to have been an incitement to permanent reformation.
Not long after, she was much struck in observing the awful, reverent frame of mind,
in which two traveling Friends appeared to sit, waiting upon the Lord;
and a fervent inquiry was raised in her mind after the revelation of the Father,
through the Son.
To this exercise, in her own experience, she was then much a stranger;
but as she persevered, and by the operation of grace in her seeking heart,
she attained the object of her search, and was satisfied.

About her twenty-seventh year, she came forth in the work of the ministry,
and about the same time she fell into some outward trials and distresses;
and she became either a teacher, or otherwise a servant, in the family of a Friend,
of whose daughter she had the care.
After a while she quitted this employ,
in order to be more at liberty to fulfill her duty as a minister;
and she visited in that service, in company with another Friend,
the meetings of Friends in Ireland in a very general manner.

In 1748, she entered on a similar visit to Friends in England,
in which she employed more than two years.
In 1751, she accompanied Catherine Payton, of Dudley, Worcestershire, then
then on a religious visit in Ireland, in a visit to Friends in Munster and Ulster.
In this journey, probably, was laid the foundation of that close religious fellowship,
which rendered them sympathizing companions in further and more extensive services.
In such service they engaged in the year 1753,
and were nearly three years employed in visiting Friends on the continent of North America,
returning in the summer of 1756.

It is not within the plan of this compilation to
give even cursory accounts of such journeys;
but an extract from a letter which she wrote from Bradford, in Yorkshire,
in the first year of her travels in England,
is particularly thought worthy of preservation.
She seems, previously,
to have been tried by means of much deprivation of that heavenly comfort and support,
which she loved and sought.

As I quietly rode along, '`says she,
'`the Lord was pleased in mercy to break in upon my mind by his living presence and power,
and it became the language of my soul, Speak, Lord, and your servant will hear.
After which, many things were divinely opened to me; wherein I greatly rejoiced,
and was thankful to the Lord my God.
I then found a sudden but gentle rebuke; and heard, as it were, a voice that said,
in the secret of my soul,
'`The dispensations you most delight in are least pleasing to me;
and not so beneficial to your soul as that pure poverty of spirit,
brokenness and contrition of heart, which brings into humility of mind.
And the reason why this is so little desired, and so unpleasant to the creature is,
that it can have no part therein; but is wholly excluded and set at naught;
can discover no beauty or excellency in it.
And for this cause it is that I will in no wise despise
the offering of a broken and contrite spirit,
as it is most pure, and without any mixture of the creature.
For whether there be prophecies, divine openings or revelation, consolations,
joying or rejoicing in the Holy Ghost, gifts of healing, or tongue of utterance;
in all these self can rejoice, and have a share, being obvious to it,
and bringing it honor.`'
Then, said I, Lord dispense to me what is most pleasing to you, and best for my soul,
so long as my weak faith and patience can endure; and when I am ready to faint,
give me a little of the wine well refined on the lees, that my soul may rejoice in you,
the God of my salvation.`'

On the 17th of the Third month, 1757, she was married to Samuel Neale,
a valuable minister then residing within the compass of Edenderry monthly meeting;
and in the evening of that day, in an opportunity of religious retirement,
her mind was impressed with a sense of the holy sabbath of rest.
She remarked, that when the Almighty had finished his six days`' work in the creation,
he appointed a sabbath and sanctified it; she observed that, in the time of the law,
the people were forbidden to do any manner of work on the sabbath day;
and she said that there were some present who should, in a short time,
cease from their labors, and enjoy a sabbath in which they should have no work to do.

The next two days were passed in receiving visits from her friends,
and in sweet fellowship with her newly-acquired partner;
but very early in the morning of the 20th, she was seized with a disease which was,
probably, an inflammation of the bowels; and about three in the afternoon she expired.
During this short illness, she sometimes raised her voice in a melodious manner,
though she did not always express herself in words.
She longed to be dissolved, and entreated the Lord to give her a release; and when,
about half an hour before her decease, her pain ceased, she then said,
'`I praise your name, O my God, for this favor.`'

[.asterism]
'''

JONAS BINNS, a boy in his fifteenth year, son of Jonathan Binns, of Crawshawbooth,
in Lancashire, departed this life the 23rd of the Ninth month, 1760.
His surviving father gave a testimony concerning him, which I nearly copy.

[.embedded-content-document.testimony]
--

He had great delight in reading the Holy Scriptures when very young.
He said he preferred learning before money.
He was often alone when others were at their play.
He read much, and was often much affected, being observed, sometimes,
to make a stop in his reading, and plentifully scatter his tears.
And not only in reading, but when solidly set in meetings, tears did run down his face:
which was affecting to the well-minded,
and evidenced that he met with something worth waiting for; which,
when but nine or ten years of age, he confessed.
He was then very desirous to go to meetings, and being asked the reason,
he was very still for a time, and then broke out into tears,
and signified that he met with something in them, which sweetened his mind.
He was steady in his conduct, and careful in his words,
and often reproved others who were not so.
He was remarkably patient under disappointments, and content with such things as he had.
He was dutiful to his parents, and his behavior and conversation were truly edifying.

--

In the thirteenth year of his age he fell into a decline;
and in the last six months of his life he was under great bodily affliction,
which he bore with great patience and fortitude.
He was never heard in the least to repine, but seemed wholly given up to the Divine will.
Thus far his father.
A few of his expressions are preserved, confirming this paternal testimony.

Lying in a weak state, he said, '`The Lord has been very gracious to me all along,
and followed me with the extendings of his love.
Praised be his name.`'
To his brother and other relations present he said, '`Grieve not for me.
It will, I believe, be well with me.`'
He desired those present to take care of their company and their behavior, adding,
'`The Lord has been good to me, and I think I would rather go than stay in this world,
where there are troubles enough for every day.
You have done all you could.
Don`'t sorrow for me.
I am going to eternity --a blessed eternity, where we shall meet again,
if we live as we ought.`'

[.asterism]
'''

JANE CORNOCK, daughter of Thomas Cornock, of Haverford-west, in Pembrokeshire,
and of my paternal aunt Elizabeth, daughter of Silvanus Bevan, of Swansea,
was removed from time on the 17th of the Eleventh month, 1768,
by means of a rapid consumption, at the house of Elizabeth Bevan, of Swansea,
widow of Paul Bevan, her mother`'s brother.

I saw her in London, in the spring of the same year, lively and gay;
though not extravagant, according to the usual acceptation of that word.
In South Wales, the country of her birth and residence,
there was not among the youth in general,
of her own rank in life (though that was by no means high) much, if any,
suitable acquaintance;
and she too freely indulged herself in the company of those
who were much strangers to the restraints of Truth;
and therefore more likely to encourage than to check
the propensity to gaiety which she felt.
She was smart in her dress; deviated from the simple mode of speech used by Friends,
and was admired for singing.
Yet I believe she loved upright Friends,
and she had long been particularly attached to that valuable
relation at whose house she breathed her last,
and who, I believe, saw her expire.
This Elizabeth Bevan was a minister;
and I have heard Jane speak of her in that capacity with evident marks of approbation,
mentioning the weight of spirit which she used to perceive over her aunt,
previous to the appearances of the latter in this service

The last time I saw her, as before hinted, was about six months before her death.
She was then what is called the life of the youthful
parties who attended her aunt in excursions,
common in the vicinity of London;
but I have reason to believe that even then the world had begun to fade in her view.
But I was then a boy, in my sixteenth year;
I partook of the enjoyment which her company afforded;
and though now I can sometimes rejoice in the reflection that many
of those connected with me by consanguinity have been reached,
when wandering, by the crook of the heavenly Shepherd, and can wish, if not pray,
for the collection of many more of them into the fold of safety, yes, of salvation,
I was certainly then neither a religious character, nor a judge of it: though then,
I believe, like her, a lover of good men.

At length, says another relation,
it was the merciful favor of her gracious Redeemer to give her a sight of her errors,
and a true penitent heart for every folly;
also to enable her to hold forth a powerful exhortation to her intimate
acquaintance to shun the pleasing snares and vanities of life.

Being thus redeemed, she had no desire for recovery.
She dropped, before her close, many comfortable expressions; saying,
that though the Lord was pleased to afflict her body, her mind was not afflicted;
that she had sweet assurance, and that at times she seemed already in heaven.

[.asterism]
'''

JOSEPH HARWOOD.--The life of Joseph Harwood, of Manchester,
affords a striking instance of the efficacy of the grace of God,
inwardly revealed to the soul, when it is faithfully and unreservedly obeyed.

He was born in the year 1712, at Bolton in Lancashire,
where his parents lived in good repute.
His father was a conscientious member of the church of England, a man of integrity;
one who professed and knew that religion is an inward work.
He died when his son was not more than twelve or fourteen years of age;
but his piety and instruction had made a deep and
lasting impression on the tender mind of his child,
who, as he advanced in years,
was more and more introduced into those conflicts which attend the Christian warfare.

He was often, before he arrived at maturity, involved in sorrow of heart,
when reflecting on those things which appertain to the life that is to come.
In this state, and from a wish to be more at liberty to attend to the duties of religion,
a very unusual motive for such a step, he entered the army, in the year 1731;
but in so doing, he found himself greatly disappointed.
His companions seeing his anxiety and distress, and being strangers to the real cause,
formed various conjectures concerning him; but such were his sobriety, docility,
and readiness to serve others, that he gained the esteem and confidence of his officers,
and was mostly employed in their particular services.

He continued in the army about fifteen years, beloved and esteemed in his station,
and acquitted himself with credit and fidelity.
But that good and gracious Being, who had visited him early in life,
continued to follow him in mercy and in judgment;
and in the course of the latter years of his military service,
was pleased to show him with indubitable clearness,
the utter inconsistency of all wars and fightings with the Gospel of life and salvation,
and to require him to bear a faithful testimony to the same.
Through the gradual operation of the Holy Spirit,
this conscientious man was made willing,
in conformity with the example and doctrine of Him
who came not to destroy men`'s lives but to save them,
to refuse to bear arms any longer, and to submit to whatever might ensue,
although he knew that a punishment no less than the loss of his natural life was impending.
He was tried by a court-martial, and treated with great moderation and civility;
some who had been his fiercest opposers becoming his advocates.
The remarks which he made on his own behalf, produced great seriousness.
The court forwarded a candid representation of his case to king George the Second, who,
on the intercession of some friends, honorably gave him his discharge,
after about six months`' imprisonment.

Not long after his release, having joined our religions Society,
he took up his abode at Manchester.
In the course of a few years he was brought under a religious
exercise of mind to speak as a minister of the Gospel,
to which he yielded, about the fortieth year of his age.
Being faithful in the use of the talent received, he increased in religious experience;
and though his public testimonies were not long,
he was often baptized into a sense of the condition of the meeting,
being reverently concerned to feel the renewal of power from on high,
before he stood up to minister to others.

He visited the meetings of Friends in Ireland, and several times, those in Scotland;
and also travelled in other parts of this nation.
He was frequently engaged, in gospel love,
to visit Friends in his own meeting and neighborhood,
to see how it fared with them in the best things; when, from easy, innocent conversation,
he was often drawn into solemn silence;
and therein his heart was replenished as with the dew of heaven,
under the lively influence whereof, he offered seasonable exhortation and counsel.

He was careful not to entangle himself with the cares of this life,
seeking to have his treasure in heaven.
Though naturally cheerful, and very agreeable in company,
his words were frequently seasoned with the salt of the covenant,
evidently ministering grace to the hearers.
As his heart was thus warmed with love towards his brethren,
so was he also greatly beloved by them.
Being a man of meek and inoffensive deportment,
and much devoted to the promotion of peace and good will among men,
his company and conversation were acceptable to most who knew him,
of various religious professions.

Some years before his death he became very infirm,
being afflicted with an asthmatic complaint; yet he constantly attended his own meeting,
fervently laboring therein for the arising of Divine life,
and often speaking as a minister, greatly to the comfort of his friends.
After a short illness, he died on the 12th of the First month, 1776,
at the age of sixty-four.

[.asterism]
'''

TABITHA MIDDLETON.-- In the lives of many dedicated and humble servants of the Lord,
it not infrequently happens, that but few incidents are met with,
from which a biographical sketch can be compiled;
while their faithful endeavors to serve the Lord in the way of his requirings,
may have exhibited a bright example to those around them.
Such appears to have been the case with Tabitha Middleton,
of Wellingborough in Northamptonshire, who was the daughter of John and Sarah Hoyland,
of Sheffield.

In a letter to an intimate friend,
she thus describes her sense of the goodness of the Almighty in her youth.

[.embedded-content-document.letter]
--

On looking over years that are past,
I find abundant reason to acknowledge the mercies of Providence,
in extending his heavenly visitation in the very early part of life,
which raised strong desires to walk acceptably before Him.
I well remember the exemplary care of my dear mother, at that time,
whose conduct and advices made lasting impressions on my mind; though,
as I advanced in years, '`the lust of the eye and the pride of life,`'
too much influenced the judgment, and weakened my good resolutions,
which made even life a burden.
But how have I admired to be in this state allured
to prefer Jerusalem before my chief joy;
concluding, that whatever I parted with or suffered,
was not to be compared with the enjoyment of Divine good.

--

When about fourteen years of age, she was deprived of her mother.
By this loss, and other events which succeeded,
her mind appeared to be increasingly turned to seek for the consolations of religion.
She resided at that time at Sheffield,
and manifested a pious care and solicitude for the
younger branches of her father`'s family:
she was much beloved by her young friends generally, to whom she was also a good example,
in a humble and circumspect deportment.

In the year 1783, she was married to Benjamin Middleton, of Wellingborough,
when her religious usefulness became more extensive,
in an enlarged sphere of relative duties; in the faithful discharge of which,
the meek equanimity of her conduct presented an instructive lesson to many.

After a time of much thoughtfulness, she had, when about twenty-five years of age,
yielded to a belief that it was required of her to appear as a minister.
Her communications in this character were acceptable to her friends,
and delivered in great clearness and simplicity; and she was, for several years,
at times, diligently employed in various parts of this nation,
in visiting the meetings of her fellow-professors.
She was much concerned for the right exercise of our Christian discipline,
in the spirit of love and meekness; and, being clothed with true charity,
administered counsel, and sometimes close admonition,
in a way that often appeared to be not only well received,
but to be attended with a blessing, particularly to those in early life.
She was indeed a mother in Israel, an experienced and judicious counsellor,
a firm and sympathizing friend.

She attended her own and a neighboring quarterly meeting, in the autumn of 1809,
and was soon afterwards taken ill.
The symptoms were not alarming until the day preceding her death;
but the awful messenger was not to her a king of terrors.
In the course of this illness she remarked:
"`I have been permitted to live until I am not afraid to die; nor am I anxious to live,
except on account of my husband and children.
If I should be taken away, it may be said I am released from all my labors.`"
She died in peace, on the 18th of the Tenth month, 1809, at the age of fifty-nine.

[.asterism]
'''

MARY ALEXANDER, of Needham-market, in Suffolk, was, at a very early age,
tenderly affected with the visitation of Divine love, which inclined her mind to piety.
Before she had attained her seventeenth year,
she was impressed with a strong apprehension that,
if faithful to the manifestations of the Holy Spirit, she should, at a future day,
be called to the work of the ministry; yet,
notwithstanding this gracious condescension of the Almighty,
for lack of steadily abiding under the operation of his power,
she deviated from the simplicity of her guarded education,
and gave way to youthful propensities averse to religious restriction and seriousness.
Yet mercy and truth followed her; her heart was often made sad,
under a sense of disobedience;
and she sorrowfully felt that there was much which required to be slain by "`the
sword of the Lord`" before she could be brought into a state of acceptance.
Thus humbled and contrited before Him,
she became at length effectually awakened to a search after enduring happiness,
often and earnestly imploring that all within her might
be brought into subjection to his holy will.

She now found much consolation in the perusal of the Holy Scriptures,
and deeply lamented having spent any of her time in reading plays,
and writings of a similar description; being sensible,
that nothing she had ever been in the practice of,
had so much alienated her mind from the fear and love of God;
and she often wished she could warn all,
and especially the youth of her own religious Society,
of the pernicious tendency of such writings.

About the year 1786, she lost her surviving parent; from which time, to the year 1789,
she sustained, from various causes, many deep conflicts of spirit.
Many, also, were the baptisms of her soul,
from a nearer view of the prospect she had long had of a call to the ministry,
which now came weightily upon her, and on which service, in much humility and fear,
she entered in the course of the same year, being the thirtieth of her age.

The general tenor of her subsequent conduct gave evidence to others
that she loved "`the habitation of the Lord`'s house,
and the place where his honor dwells.`"
She was given up in much devotedness, to leave her own comfortable dwelling,
and to advocate the cause of Christ, both among her own friends,
and in more distant parts;
and was frequently constrained to manifest her interest
in the spiritual welfare of her fellow-members,
by paying religious visits to the families of friends;
a duty for which she appeared eminently qualified;
and there is reason to believe that her faithful
labors were often productive of solid benefit,
both in and out of our Society,
and that they yielded to her own mind the peaceable fruits of righteousness.

In the discharge of her more private duties,
she gave proof of possessing a heart expanded by benevolence;
and to sympathize with others,
and render assistance to them in times of difficulty or affliction,
was a conspicuous part of her character.

Her last Christian efforts in advocating the gospel,
were comprised in a visit to the families of friends in the city of Worcester,
and parts adjacent, and in holding some public meetings,
in conjunction with a friend under similar concern.
The last meeting which she attended was held at Alcester,
on the 13th of the Eleventh month, 1809,
and was one to which the inhabitants of the town were invited; it was very large,
and was considered to be remarkably solemn.
In this meeting she was engaged in fervent, vocal supplication.
She had been unwell for several days, and soon after the conclusion of this engagement,
it appeared that she had taken the small-pox.
The disorder did not assume an alarming aspect until after the usual crisis,
when the symptoms were such as to dispel the hopes
that had been entertained of her recovery.
Through the whole of her deeply-trying illness,
she discovered much patience and resignation,
and her mind seemed to be divested of every burden.
Speaking of her late visit, she said she had been favored with a precious evidence,
that she had been there in better wisdom than her own.
Articulation being often difficult, she did not express much; and,
from the extremity of her sufferings, was sometimes anxious to be released,
and thought her spirit long in departing, yet carefully avoided,
either in word or manner, murmuring at the conflict.
She was preserved, with little intermission, sensible to the last;
and during the final efforts of nature,
several times held up her hands as in the attitude of prayer.
She quietly expired on the fourth of the Twelfth month, 1809,
in the fiftieth year of her age.

The friends of Worcester monthly meeting,
in taking a retrospect of her labors among them, observe:
"`We may weep over her as a friend, or as a relation;
we may mourn the loss which the church has sustained, of one of its upright pillars;
but on her account there appears no cause for sorrow.
She was, we believe, favored to finish all she had in commission;
showing herself therein a good and faithful servant,
and we doubt not she has entered into the joy of her Lord.`"

[.asterism]
'''

DEBORAH DARBY was the daughter of John and Hannah Barnard, and was born at Upperthorp,
near Sheffield, in the Eighth month, 1754, and died the 14th of the Second month, 1810.

She was naturally of a sweet and amiable temper, and, in her youth, of a lively,
active disposition.
In early life, she frequently experienced the contriting visitations of Divine love,
and in opportunities of retirement was humbled before God.
Her example, in thus withdrawing from the pursuits of time,
and cultivating a watchful state of mind, and her reverence for the truths of religion,
combined with a kind and cheerful demeanor,
had an attractive and beneficial effect on some of the friends of her youth.
Her care to retire to wait upon the Lord in secret, continued through life;
and having known this habit, at an early period,
to contribute to temper her own vivacity,
she was often engaged to recommend the practice to others,
especially to her younger friends.

In the year 1776, she was married to Samuel Darby; and they lived for a while in London,
but afterwards settled at Coalbrookdale, in Shropshire,
which was the place of her residence until the time of her death.

Having submitted to the convictions of the Spirit of Truth, she learned from experience,
that, whether in prosperity or adversity,
there is no joy comparable to that which results from a conformity with the Divine will.
She was thus prepared to yield to an apprehension
of duty to become a minister of the Gospel,
and first came forth in that character in the year 1779.
Being concerned to keep low and watchful before the Lord,
she advanced from stature to stature in this sacred office,
and her services were truly acceptable to her friends.
In the year 1781,
she first travelled with a certificate of the unity of her monthly meeting;
and from that period, through a course of near thirty years,
she was a diligent laborer in the Gospel of Christ, at home and abroad,
among those of her own religious Society, and other professors of the Christian name.
She repeatedly travelled through most parts of this nation, was several times in Ireland,
and was absent from her native land nearly three
years on similar religious service in America,
in company with her endeared fellow-laborer, Rebecca Young, now Rebecca Byrd.

On landing at New York, the 8th of the Tenth month, 1793,
she made the following memorandum: '`On waking this morning,
we found ourselves in the harbor of New York, and had a beautiful view of the town.
We went to the house of our friend John Murray, who, with his wife,
received us affectionately;
which impressed our minds with gratitude to the Author of Mercies, both ancient and new,
who had thus brought us safely over the mighty ocean.
May He so preserve us, as to bring us at last into that port and haven of rest,
at the end of time, where the morning stars sing together,
and the sons of God shout for joy!`' Having endeavored to know and
to do the will of Him in whose service she had gone forth,
she wrote the following short acknowledgment of his all-sufficient help,
on the day on which she embarked for her native land:
"`We attended a public meeting at Newcastle.
After dining with about one hundred and fifty Friends,
we had a solemn parting opportunity, in which much encouragement was handed,
and prayer put up for mutual preservation, under the influence of humbling Goodness,
that had, we trust, put us forth, gone before us,
and now condescended to be our reward.`"

In the course of this journey,
she often felt her mind warmed with Christian love and compassion
for the native Africans and their descendants,
so numerously settled in the United States; and in the larger cities,
religious meetings were specially held with this degraded and injured class of our fellow-men.
In passing along, both in England and America,
she at times visited those confined in prison, some when under sentence of death,
fervently laboring to turn their attention to the Savior of the world --to Him, who,
as he is applied unto in sincerity and in truth,
will still be found to be the Friend of sinners.

The character of this diligent laborer, when employed in the service of her Lord,
is thus delineated by one who was long and intimately acquainted with her:
"`I can say of her, that in and under all our conflicts,
and the severest of her particular trials,
I never met with one whose conduct evinced a stronger confidence in God,
or whose faith was firmer in the appointed means of salvation.
Thus supported, even when the waves of affliction rose high,
she was enabled to center in resignation,
and to follow on in the line of her religious duty.
Loving the light, she manifested her love by simple and unreserved obedience,
without consulting ease to the flesh, or present gratification.
I think her humility was conspicuous,
rendering her a good example to her fellow servants; to whom, even to the least,
she was ever ready to to give way,
when sensible that the anointing was poured forth upon them.
Her fervent zeal for the welfare and preservation of the youth,
in that path of self-denial which Truth leads unto, cannot be forgotten.
Wherever I travelled with her on its account,
I was witness to her pious and arduous labors with that class of society.
Seldom could her devoted heart feel satisfied to
leave Friends`' families without gathering the children;
and many, I believe, there are in different parts,
who have cause to bless the Lord for having made her an instrument of good to them.`"

The dispositions which have been noticed as obvious in early life, matured by years,
and sanctified by the power of religion,
rendering her an endeared and instructive companion;
one who was ever attentive to the right discharge of her relative and social duties.
She was solicitous for the help of the poor,
and concerned that a due proportion of her outward
substance should be expended to promote their comfort.
She was not apt to take offense, and cautious not to give it;
and exemplified in her conduct, even under the pressure of heavy affliction,
the excellency of that Gospel which she was commissioned to preach.

In the spring of 1808,
Deborah Darby left home on a visit to Friends in the southern and eastern counties.
In the autumn of the same year, she was considerably unwell, and exhausted by fatigue;
and this debility continued through the winter.
She was again absent from home for several weeks in the spring of 1809,
and returned so far improved as to be able to join her friends
in their public assemblies for Divine worship;
but, as the winter approached,
the gradual decay of nature rendered it necessary
for her to confine herself very much to the house.
The following extracts, from a few memorandums left behind,
exhibit the humility with which her mind was clothed.
"`I have had some precious seasons of Divine overshadowing during my illness;
which have been better than all the cordials administered by my medical attendants.`"
"`I am sometimes strengthened to speak well of His name, who lives and reigns,
and is forever worthy.
I have cause to be thankful for strength being granted to sit with my friends,
though often in much poverty of spirit.`"
I have little to remark, my allotment being often in suffering as to the body,
and low in mind; yet I can say, God is good, and a strong-hold in the day of trouble.`"

She endured much bodily suffering previous to her dissolution,
with exemplary patience and sweetness, remarking:
"`Unless the Lord has some further service for me to do,
I could not wish to stay much longer, I suffer so much;
but all in his ordering is best.`"
And at another time, when in great pain, said,
"`It would be a great favor to have a little ease once more before I leave you;
I should like to be a little cheerful,
for I have nothing but the pains of the body to make me otherwise.`"
After having been greatly exhausted by seeing some of her nearest relatives,
she said to a friend sitting beside her, "`The Lord be praised.
He is wonderfully good, even now.`"
The evening before her death, when in extreme suffering, one of her attendants,
who thought she had asked for something, said, "`Can we do anything for you?`"
to whom she replied, "`Rejoice evermore,
and in everything give thanks!`" and shortly afterwards said,
"`The Lord`'s will be done.`"
She seemed to be engaged in supplication for some time after this,
although her expressions could not be understood.

Thus was this faithful disciple enabled, in the closing days of her earthly pilgrimage,
to confide in the Almighty,
and to evince that her soul was prepared to unite in that song of praise and thanksgiving,
which is the blessed employment of those redeemed spirits
who stand before the throne of God and of the Lamb,
forever and ever.

[.the-end]
END OF THIRD VOLUME
