== Chapter 6

[.chapter-synopsis]
* Hannah Stephenson
* Elizabeth Millis
* William Savery
* Mary Tate
* Edward May
* Samuel Clothier Bryan
* Susanna Moore
* Jacob Bell

HANNAH STEPHENSON, daughter of Daniel and Sarah Stephenson, and younger sister of Sarah,
who died in Philadelphia, as already related,
was born at Whitehaven the 15th of the Seventh month, 1745,
but removed with her parents to the Isle of Man, about the seventh year of her age.
There was not any meeting of friends on that island,
nor any member of the Society besides those in her father`'s family.
Yet, though in this remote situation she was exposed to many temptations,
her mind was secretly touched with the visitations of divine love;
and as she gave up to them, after many conflicts,
was favored and enriched with the incomes of peace.

About the year 1762, her father died,
at which time she was far from having forsaken the gaiety of the world;
but it is more than probable that the influence of her more devoted sister,
who had resided at home with her parents for some time before that event,
had a beneficial effect on her mind:
and after the decease of her father it became evident.
The following year she went to live as a servant at Birmingham.
Afterwards she removed to Stebbing, in Essex,
and lived with a woman friend who kept a shop in that place;
and next she became an inmate in the family of Sarah Beek, a valuable friend,
and a minister, who then lived at Witham, in the same county.
It was during her residence in Essex,
that Hannah Stephenson first came forth as a minister,
about the twenty-second year of her age,
in a meeting at the neighboring town of Kelvedon.
This public act of dedication was performed in much brokenness of spirit;
and as she abode in humility,
and was attentive to the clear discoveries of manifested duty,
she became an acceptable and lively minister.

After some residence in Essex, in the year 1778 she again removed,
and settled in London with her younger brother;
but after a residence of about four years, she finally removed to Bristol,
to live with her aged mother.
This last change was in the year 1782.

Previously to her leaving Essex,
she had sometimes found it her concern to travel in the exercise of her gift.
In 1771 she visited London, Kent, and Buckinghamshire, in company with Sarah Beck.
After this she was much at her home for nearly seven years;
but not without performing various services,
particularly visiting the families of some meetings in Essex; but in 1788,
she joined Esther Marshall, of Leeds, in a visit to the meetings of Surry, Sussex,
and Kent; and also to those of Essex, Suffolk, and Norfolk,
and to the families of Friends of Norwich.
The same year she accompanied Deborah Townsend of London,
in visiting the meetings round the metropolis; and in 1781,
the families of that of Tottenham.
After her removal to Bristol,
she was also engaged with the same Friend in several religious services; first,
in the counties of Somerset and Wilts, in 1782; next,
in visiting families in the northern parts of Somersetshire,
and the southern parts of Gloucestershire, in 1783; and lastly, namely, in 1785,
in a visit to meetings in the counties of Dorset, Devon, and Cornwall.

In the next year she joined Ann Jessup, a Friend in the ministry, from Carolina,
in a long northern journey, which extended as far as Glasgow.

In 1787 and 1788, she was united in gospel labor with Mary Davis, of Milverton;
with whom, in the former year, she visited Wales, and in the latter,
the families of Friends in Somersetshire;
and in 1789 she again joined her former companion and very intimate friend,
Deborah Townsend, in Northamptonshire, Lincolnshire, Cambridgeshire, and Hertfordshire.

In 1792,
she was one of several Friends who undertook the important
service of visiting Friends`' families at Bristol:
and the next year she once more engaged in service with her beloved friend Deborah Townsend,
in the counties of Gloucester, Worcester, and Warwick.
After this, she was much confined with her mother until the year 1800,
in the Seventh month of which year,
this dear object of her filial duty and of her tender solicitude, departed,
in the ninety-third year of her age.

The remaining services of Hannah Stephenson were chiefly in what, in a large sense,
may be termed the neighborhood of Bristol; except that in 1801,
joined by an aged ministering Friend, Ann Byrd, of Uffcolme, in Devonshire,
she visited the families of Friends of Liverpool,
having also religious service in their way.
Her last illness was lingering.
In the Tenth month, 1803, it was my lot to see her, both at the house of Joseph Naish,
of Congersbury, Somerset, where she had retired for the benefit of country air,
and at that of John Waring, in Bristol;
from which I think she never again departed till she left the probations of mortality.
She seemed to me like one who was (as I once heard our ancient friend, Isaac Sharpless,
say of himself in the yearly meeting) retiring with her penny.
In this family she had sometime resided;
here she was often visited by Friends who knew her worth, and loved her;
and here therefore she had frequent opportunities
of demonstrating that her attachment to her Lord,
and to his cause, remained in undiminished strength.

One evening in the Eleventh month, some of her near friends were standing round her bed.
A calming solemnity spread gradually over their minds,
and they were gathered into stillness.
She soon expressed her perception of it, though in a feeble voice.
She said she was thankful her lot was cast with those
who knew how to prize this precious feeling;
and that she had felt the assistance of their spirits,
in gathering into this quiet habitation; desiring that they might often seek after it,
and remarking that Jerusalem was to be a quiet habitation: and after a little pause,
with a strengthened voice, she addressed each of the friends with particular exhortation.
She then sweetly expressed her thankfulness for the refreshment which had been granted,
and said it made her sick bed like a bed of roses.

It would exceed the limits which I generally propose to this work,
to insert all the comfortable and instructive expressions,
of which an account now lies before me.
She once desired a young woman, who was her usual attendant,
to say if she did not think her weaker than at any time before.
The young woman assented, and Hannah replied, "`My getting weaker is not grievous to me,
but joyous;`" and then she signified her longing to be finally released.
At another time, being in much pain, she said, "`I am a poor creature,
hastening towards the silent grave;`" but reviving, she added,
"`When I am favored with intervals of ease, all my pain seems swallowed up of sweetness.`"
Speaking once of her bodily sufferings, "`Why,`" said she,
"`should any of us mind being tried,
when the beloved Son himself had a crown of thorns put on his head,
and was crucified between two thieves?`"
"`May I,`" she added, after some pause, "`quietly pass away,
without bringing the least shade on that precious cause which has been dear to my life.
It has been my meat and my drink to do my heavenly Father`'s will, as far as I knew it;
but all through his help: nothing of myself.
To me belongs blushing, and confusion of face.`"

After she had been some weeks confined, addressing herself to a friend, she said,
"`It has unexpectedly occurred to my mind, my dear, that expression of our Lord`'s,
'`Strive to enter in at the strait gate,
for many shall seek to enter and shall not be able.`'
I believe, my dear child, your mind is at times thus engaged.
O then maintain the strife: for, though the way may be narrow to flesh and blood,
yet it will be found wide enough to those who are rightly concerned to walk in it;
and to be a way of pleasantness; and its paths, paths of peace.
'`Strive`' then '`to enter at the strait gate, for many shall seek to enter,
and shall not be able.`'`"

She was one day speaking to some Friends of her gratitude for her allotment in the family,
where she was an afflicted inmate.
She said that it was the kindness of her good Master, and his love,
that had influenced their hearts to render their house a comfortable home to her.
"`Oh,`" said she, "`the precious influence of this love!
How does it open the heart to feel for, and to be helpful one to another!
And how would it thus do for many more, if enough cherished!
It would lead others in tender sympathy, to acts of this kind,
for we are not designed by our great Creator to live to ourselves,
but to be helpful one to another.
Oh! the sweetness I have felt, on this bed,
in retrospecting my attention to intimations in this way.
Many times have I gone to persons in distress, and in proportion to it, of my little,
imparted to their needs.
And oh, how acceptable has it proved!
Even a few shillings, in addition to their few, have produced the tears of thankfulness,
and I have returned abundantly recompensed by sweet satisfaction
in having contributed to the relief of such.
And there are some not in a very abject situation,
yet at times in very straitened circumstances; hard to bear,
and hard to them to make known by asking help.`"
Such she thought should be sought out by those who were of ability;
and she particularly desired that the affluent would view themselves but as stewards,
accountable stewards.

One of her near friends taking a final farewell,
her mind at the time was tenderly affected in a renewed
feeling of her heavenly Father`'s love,
and she broke out in the language of thanksgiving, "`Oh! what shall I render,
what shall I render unto you for all your favors?`"
She continued, saying, "`How repeatedly, by this bedside,
has the cordial of sweet consolation been administered to my poor mind,
through servants and handmaids, all corroborating the same thing,
tending to strengthen my supporting hope,
which I trust has had its origin from the sure word of promise,
which I esteem the greatest of all favors: and may now express,
I believe without boasting, that a comfortable assurance has been given me,
in language strong and clear to the ear of my soul, and that more than once:
I will crown you with glory and honor.
I will crown you with glory and honor.`"
In the afternoon of the same day she pleasantly related
a dream which she had a few nights before.
She seemed to be with her sister in a garden, where her sister,
standing on the steps of a summer-house, appeared to be putting a garment on her.

Not long after this, when the children of the family, among others, were with her,
she sweetly addressed them, and observed,
that though some of them might not then understand all that was said,
yet that it might be as bread cast upon the waters.
She desired the eldest to be an example to her sisters,
importing her belief that it was her heavenly Father`'s will that it should be so;
and expressing her hope that the children would remember what she had said,
as the words of a dying friend.

Her bodily ailments were great.
She suffered much from cough, much from great debility,
and at times from the soreness occasioned by long continuance in bed.
One time, after having prayed for help,
and having taken something which seemed to nourish and relieve her,
she remarked what a favor it was to have such things, at such a time.
One present observed that she had been thinking how some must suffer,
for lack of such accommodations.
To this Hannah replied, "`Providence can make it up to them in some way or other.
He can shorten the conflict.
The Almighty is just and equal in all his ways.`"

In the evening of the 6th of the Second month, 1804,
she told a friend that she had that day seen her end,
with greater light and clearness than she had ever done before,
and that she believed it was not very distant.
She remained only about five days longer.
The day before her departure was a trying one, in which she had little sleep or rest,
and took but little nourishment.
Towards evening, a gentle slumber afforded some respite;
but afterwards her cough returned, her breathing became increasingly difficult,
and her bodily conflict was great.
Some of her friends who had retired, came again to her chamber.
She appeared glad to see them, and with earnestness said, "`Rejoice evermore,
and in everything give thanks.`"
Thankfulness, no doubt, reigned in her soul,
in the expectation of a speedy relief from the oppressive state of her enfeebled frame.
But this she yet was permitted to endure for a time.
"`This,`" she said, "`is a hard conflict.
This is a long conflict.
How shall I endure?
Lord help.
Send a little help from your holy sanctuary, if it be your holy will,
I pray you;`" adding soon, "`Lord, shorten the conflict, I pray you.`"

This, her last audible petition, seemed to be fully answered.
A gradual abatement of suffering took place; and though the power of articulation failed,
her mind seemed to be sweetly composed,
and she frequently appeared to be engaged in mental supplication.
There is reason to believe that to the last she retained her understanding; and at last,
as she had often expressed her desire that it might be the case,
she quietly passed away.

[.asterism]
'''

ELIZABETH MILLIS, of Southwark, was born in that place, about the year 1742.
Her father dying early in life, left a widow and two daughters,
with but slender means of support.
He had however been a watchmaker,
and this his daughter had so well learned one part of that business,
as to be able to maintain herself with reputation,
if her health had been equal to support a life so sedentary.
In process of time she accepted a kind invitation from some relations at Hartford,
to come, and be a resident in their family; in which her conduct was exemplary,
and she became very useful.

She was religiously inclined from her childhood;
and is said to have been very early at times,
exercised in mind with a prospect that it would be
required of her to espouse the cause of truth,
by public ministry.
But she was naturally of a diffident disposition;
and it is thought that so far from being duly helped and encouraged,
by such as should have been as fathers, that she even had her own diffidence increased,
by perceiving that she was not alone in her backwardness
to be engaged in that solemn work.
It was not until about the forty-second year of her
age that she came forth as a public minister.
Her appearances in the ministry were not frequent;
but her friends thought them acceptable and lively; and being of a weakly frame,
bodily affliction frequently prevented her attendance of meetings.

After the decease of her relation at Hartford, she again settled in Southwark.
In her last illness,
she had been speaking of her sense of the state of
the Society in the monthly meeting to which she belonged,
in a manner which evinced her steady and continuing concern for its prosperity.
A Friend, who had been inclined to pay her a visit, being present,
expressed her wish that she might be like Elizabeth at such a time as that:
in which Elizabeth was contemplating the near approach of her closing day.
"`Oh!`" replied she, "`I do not wish any to be like me; for I am far,
very far short of what I ought to have been.
Had I been faithful to knowledge, I might have been more useful,
and escaped many and great afflictions.
But none know all my difficulties, and all my sufferings.
It is of mercy indeed, that I have not been cast quite away, for disobedience:
so that none need be discouraged.
I want to press all to faithfulness, that they may not have to look back as I have done,
and bemoan themselves for past omissions; but of late I have felt a degree of quietude,
which I had no cause to expect I desire to bear all that may be permitted,
to fit and prepare me for the close.
I hope to be patient, and not too anxious.`"
After some time, she added thus: "`I am favored with calmness;
and though this is by no means a time of feasting,
there have been seasons when I seemed as if I could
have called on the whole creation to join me in praise!
This is not often the case; but I desire to be content and thankful.`"

She departed the 31st of the Fifth month, 1804.

[.embedded-content-document.testimony]
--

[.blurb]
=== A short sketch of the engagement of mind of Elizabeth Millis, referred to in the foregoing account.

She earnestly exhorted two women Friends who were with her (one of whom is since departed,
surviving E. M. about four years), to stand firm.
"`You,`" said she, "`whom the great Master has given to see and feel how things are,
had need stand firm.
I never was more sensible of the necessity of your standing firm, than of late;
because there are so many who are not concerned to maintain the conflict,
and to be exercised in an inward labor; but are busied about trifles,
things of little moment in comparison of the inward work.
They are too busy in the outer court; but be firm.
So will you be enabled to stand, and not sink.`"
One of these women-visitants replied, "`We lack faithful brethren to help us.`"
Elizabeth answered, "`That indeed is too much the case; but be faithful.
Who knows but you may be strengthened, to help them?
If you do the part allotted you,
they may in time be aroused to a sense of their condition;
and become more concerned for themselves, and for the cause`' sake,
which seems ready to fall for lack of right support.`"

She then paused, but soon added, "`Oh! how I feel for our young men!
I wish for their preservation: but they must look to Him only, who can preserve;
and not be discouraged by the prevalence of example.
There are but few in the present day; but few to lead the younger ones forward.`"
Her exercise of mind on account of her desire that the men
Friends might be more closely bound to the service of truth,
had indeed been long to this effect.
"`Oh! that our men Friends were more concerned at heart,
and more sensible of the situation of things!
What can be done to arouse them?`"

--

These feelings and these remarks, though thus originally applied to one monthly meeting,
will probably find an appropriate application in many more.

[.asterism]
'''

WILLIAM SAVERY.
In a collection of this kind, published in Great Britain, it will, probably,
be particularly acceptable to many readers to find an account of William Savery,
of Philadelphia; because he attracted general regard in the parts of this nation,
where in the course of a religious visit, his lot was cast.
Those who long had espoused the cause of truth, valued him for his love to it, his zeal,
and his soundness of principle.
To the visited youth,
he was endeared by the lively interest he took in their religious welfare;
and there were few to whom he did not recommend himself
by his cheerful temper and frankness of character.
Indeed, he was a man beloved both abroad and at home;
but he was removed from the society of his friends, at, comparatively, an early period;
departing in his native city the 19th of the Sixth month, 1804,
in the fifty-fourth year of his age.

He had served an apprenticeship to a Friend in the country,
who carried on the business of a tanner;
and served it with the reputation of a young man preserved in a good degree of innocence;
but on his return to the city when his term was expired,
his social and lively disposition led him into hurtful company.
He associated with some who were themselves the votaries of vanity and folly;
and they encouraged him in a deviation from the simplicity of truth.
In this state, however, after some years, he was deeply affected with conviction,
at a meeting held after a burial.
The impressive occasion, and some testimonies then publicly delivered,
were the means of awakening his mind to the infinite concerns of the life to come,
and the impressions which he then received were permanent.
This was in 1778, about seven years after his return to the city,
and in the twenty-eighth year of his age.

The submission of youth to the secret touches of the grace of Christ is lovely;
and though we have often to mourn that so many, for lack of it,
are carried away in the stream of vanity, still, thanks to the Redeemer of men,
these instances of early dedication are not unfrequent.
But it is not so often that we see this blessed subjection take place, when,
on one hand the manly character is fully assumed and established; and when, on the other,
the decay of future years is seldom the subject of contemplation.
Such, however, seems to have been the case of this our departed brother.
If he did not offer to his Lord the beginning of his strength,
it is probable that at length he was induced to bring all his accumulation of strength,
and his knowledge and power of mind, and lay them at the feet of his Savior.

In the autumn of the same year, having been married,
he settled in the compass of the monthly meeting for the Northern District of Philadelphia.
He experienced various conflicts, forsook his former gay companions,
and passed much of his time in retirement.
About the thirtieth year of his age, he came forth in a public testimony for the truth;
and endeavoring to dwell inward with the gift with which he was endowed,
he became an able advocate for the holy cause which he had espoused.
And it is believed that his labors were blessed,
and made conducive to the benefit of numbers: especially of the youth, to whom,
say his fellow-citizens, he was an eminent instrument of good.
In Pennsylvania, also,
there are many inhabitants who ordinarily speak the German language,
their families having originally come from Germany;
and to many of these William Savery was serviceable in a religious sense,
as he had acquired a knowledge of their vernacular dialect.

He was much engaged to travel in the work of the ministry; and in process of time,
believed himself to be so much required to give up his time to that service,
that from the year 1789 to 1795 inclusive,
he was several months in each year absent from home, on these gospel errands.
In 1796, with the full unity of his friends, he embarked for these European parts.
He landed at Liverpool, and soon proceeded to London: after a short stay in that city,
and some other services, he went into Germany,
and visited those who profess with Friends at Pyrmont, Minden, and other places.
He had for a companion David Sands, a ministering Friend from the State of New York;
and they extended their travels as far as Berlin.
After this they bent their course to the south of France, where,
not very distant from the city of Nismes,
there was a small number of persons also professing with us,
scattered in several towns of that district: which service being performed,
they returned through France and Holland, in time for the yearly meeting of 1797.

When thus again returned into the bosom of a society which he loved,
he continued diligent in the exercise of his talent and gift.
He visited Friends in many of the principal towns and cities of England, Scotland,
and Ireland; and often had more public and large meetings,
with persons not members of our Society.
A truly catholic and Christian sentiment,
with the expression of which he concluded his testimony in a very large meeting,
convened in London, I think, for young people, has so much remained on my mind,
and is so fully descriptive of the expanded benevolence of his heart,
then additionally glowing with the fervor of a faithful
servant in the performance of duty,
that I am desirous of placing it here.
It is a hint at a state of universal good-will: which, however apparently distant,
is worthy the contemplation of those who love to trace their
blessed religion to its utmost earthly limits;
a state, said he, "`When every country shall be our country, and every man our brother.`"

Having, by these labors of love,
discharged himself of his apprehensions of duty in these nations,
he returned to his family in the Ninth month, 1798.
Thus, in the occupation of the talent committed to him, he was prompt and diligent;
nor when at liberty from religious service was he less so in his outward concerns,
in which also he labored with assiduity, not only for the support of his family,
but that he might have somewhat to spare for the necessitous and afflicted; to whom,
according to his ability, he was a liberal benefactor.

In 1802, that part of the city in which he lived was visited by a pestilential disease,
which carried off many of his neighbors, after a short illness.
As, at this juncture,
he was so circumstanced as not to be able properly to quit the sad scene and the city,
he gave himself up to be useful in it.
He visited the sufferers, as well among other religious societies, as his own;
he relieved their needs by the distribution of alms committed to his care for that purpose;
and he often was enabled to impart counsel, in the love of the gospel,
to the consolation of many of the afflicted.
The following year the same calamity returned,
and our Friend found himself again engaged in like
manner to be an instrument of succor to the distressed;
devoting himself to the service both night and day.

At length, in 1804, symptoms of a dropsy came on.
He had been of a full and rather corpulent habit;
but his face and the upper parts of his body assumed an emaciated appearance,
while his legs became swollen.
In this state, however, he did not remit in the necessary attention to his business;
and he continued, as he had long been, a very diligent attender of meetings.
In some of these he expressed his belief that his abode in this state would not be long;
but animated with the view of a blessed immortality,
he signified the little concern that this belief occasioned,
provided that blessing were attained.

As to his continued attention to business,
he told a visitor that it was necessary to look to our outward affairs,
seeing there had been so many reproachful failures: and at this time,
when probably his disease had increased, he seemed desirous once more to go to meeting,
that he might warn some of the elderly part of the Society, who, he said,
had got into the earth, and some of the youth, who had got into the air.
"`I thought,`" said he, "`I was strong for the work; but now, I am a child,
brought back to my horn-book; and have nothing to trust to but the mercy of God,
through Christ my Savior.`"
Thus, reverently depending,
he was to the last preserved in great resignation and composure;
and the last words which he is recollected to have said, were, with uplifted hands,
"`Glory to God.`"

[.asterism]
'''

MARY TATE, wife of John Tate, of East Cottingwith, in Yorkshire,
was daughter of Richard and Ellen Shaw, of Newton in Bolland, in the same county,
both members of our religious society.
From her youth she was of an orderly conduct; but as she grew in years,
her serious concern for her most important interest, the well-being of her soul,
and her acceptance with the Lord, increased also.
At length it led her into a lively exercise for the support of our religious testimonies,
and for the welfare of others; and she gave up to the apprehended requirings of duty,
to appear in public ministry, about the thirty-fifth year of her age.
In the course of about eighteen years more, she finished a life of trial:
for as her constitution was peculiarly feeble, she was often subject to illness;
and she bore such allotments with Christian patience.
In that which proved to be her last,
she uttered several expressions which indicated the resignation and hope of her mind.

At one time, she had been speaking respecting some outward things,
to a person who had expressed a hope that Mary would live to enjoy them herself.
She replied, "`I have neither hope nor fear; but am quite easy which way it may be.`"
At another time, her husband expressing his fear that she was going to leave him,
she said, "`If it be so, I shall go to a better place.`"
About two days before her decease,
she broke out in the words of those mentioned in the Revelations:
"`Great and marvelous are your works.
Just and true are all your ways, you King of saints.`"
Adding more of similar import.

"`Thus,`" say the Friends of her monthly meeting, in their testimony,
"`was the spirit of this our exercised Friend released from a very afflicted tabernacle;
and we trust is gathered to the just of all generations,
where sorrow and pain shall be no more.`"
Her departure occurred the eleventh of the Eighth month, 1804.

[.asterism]
'''

EDWARD MAY, of Henley, in Oxfordshire, departed from the vicissitudes of time,
at Ampthill, in the county of Bedford, the 19th of the First month, 1805.
At Henley, he had passed the greater part of his time,
where he long carried on the trade of a clock-maker.
He was a reputable member of our religious society, and having,
towards the middle part of life,
apprehended it his duty to come forth as a public minister,
he endeavored to be faithful in that important and solemn service.
With the concurrence of Friends, at different times,
he visited many parts of this nation in the love of the gospel:
in some of which visits he travelled for a great part on foot.

In the latter part of life he resided a while at Alton, in Hampshire,
but at length removed to Ampthill, in which town one of his sons had some time resided.
Here he evinced his continued concern for the cause of truth,
by his diligence in attending meetings in the place, and others not very distant;
and his private conduct was weighty and exemplary,
so that he was thought to "`show out of a good conduct,
his works with meekness of wisdom.`"

While writing this, which is chiefly copied from the testimony of his monthly meeting,
I am somewhat impressed with a caution, that we should not suffer ourselves,
in briefly reviewing the good conduct of our departed friends,
to degenerate into the habit of mere eulogium.
I do not say this with any particular reference to this Friend,
but as a general remark now occurring: and as it is applicable to every case,
so probably to none more applicable,
than to relations concerning those whom we term the most eminent.
As the disciple is to let his light shine, that it may glorify the heavenly Father,
so the truly Christian observer will behold it,
with a due and ready reference to the giver of the endowment.

At his first confinement to his chamber, he did not apprehend his close to be very near;
yet he examined himself, as to his spiritual state, from his youth up;
and he had the privilege to find that the great work was done, his sins were forgiven,
and all was peace.
He was often engaged in vocal prayer, and his earnest desire was,
as we have seen it has been that of many humble souls, inhabiting afflicted bodies,
that he might be preserved in patience.
And he was preserved in patience, and a quiet, peaceful frame of mind,
throughout his illness, which was a fever;
but he also had an ailment of a very painful nature.

The day before that in which his course in mortality was terminated,
some Friends called to see him.
His disorder had then advanced so far, as that he could scarcely articulate.
Nevertheless, with an audible voice,
he was enabled to bear his last vocal testimony to that Divine Power which
can support the mind under the most afflicting circumstances of time.
He added, with righteous Job, "`All the days of my appointed time will I wait,
till my change come.`"

[.asterism]
'''

SAMUEL CLOTHIER BRYAN.
In the life of Samuel Clothier Bryan, of Glastonbury, Somersetshire,
who attained to the advanced age of ninety-two, we have an instance of long, protracted,
steady perseverance in the path of the just.
His native place was Shepton-Mallet, in the same county,
where he lived upwards of sixty years; after which, and on the decease of his wife,
he removed to Glastonbury.

His education was not what is usually termed liberal;
and he fell into many of the hurtful modes of conduct incident to youth:
so that when it pleased the Lord in mercy to show him his dangerous state,
and to open to him the way of life and salvation,
he found that his evil habits had rooted themselves so deeply,
that the cross of Christ was, in his view, hard to be borne.

But the goodness of the Lord still followed him;
and convinced him that it was the only means of overcoming sin.
Thus he bowed to the revelation of its power, and as he continued in faithfulness,
he experienced deliverance from evil, and an increase in the favor of God.
Such also was his sense of the favor thus conferred on him,
that he felt himself constrained in a public meeting,
to acknowledge the abundant goodness of the Lord, adding,
"`May we never be forgetful of his mercies.`"
At this time he did not expect to be ever alike engaged in future;
but being further instructed in the school of experience,
and believing it his duty to testify from time to time,
of what he had seen and felt of the things which accompany peace and salvation,
he became an acceptable minister,
and so continued nearly to the close of his pilgrimage.

His ministry was plain, edifying, and Scriptural.
He seemed not to seek applause, but simply to do his duty,
and not to desire to attempt more.
His services were chiefly confined within the compass of his own quarterly meeting:
in which, when of bodily ability, he often walked to the neighboring or other meetings;
and was exemplary in the diligent attendance of his own.
Nor was his talent at instruction confined to public meetings only;
his visitors were often instructed by the pertinent
remarks which he had unexpectedly to convey.

In early life he had met with difficulties,
and had labored hard to provide for his needs; but as he was of a humble mind,
mean things satisfied him,
and he could spare to others whom he thought to be in greater need.
His manners were homely,
and he took so little care for the accommodation
of the body that he was thought to neglect it;
yet he possessed a mind independent, save on what he esteemed the law of the Lord.

The infirmities of age, as they increased upon him,
did not appear much to impair his mental vigor.
He often expressed his willingness to depart,
if it were consistent with the will of the Lord;
but he also manifested great resignation and patience,
and full assurance that a rest was prepared for him.
"`It is the greatest of all favors,`" said he,
"`to be released from an old decayed tabernacle,
and to have an evidence of being forever united to the spirits of just men made perfect,
and to God, the Judge of all, and to Jesus the Mediator.
I feel no unity with bad spirits, and believe my portion will not be with them.`"

On the 23rd of the First month, 1805, after a short confinement to his bed,
he peaceably breathed his last.

[.asterism]
'''

SUSANNA MOORE was the daughter of Benjamin and Susanna Grubb, of Clonmel,
in the county of Tipperary, Ireland, where she was born in the Third month, 1770.
She was a woman of an innocent and humble mind, and circumspect in life and conduct.
When she was about twenty-one years of age, she was married to James Moore, of Clonmel,
with whom she lived about fourteen years;
and when she had arrived to her thirty-sixth year,
a period at which the important and endearing characters
of wife and mother are fully developed,
she was taken from her husband, and left him with six daughters;
for the religious education of whom, in her life-time, she had been uprightly careful.

Her health began to decline in the latter part of the year 1804,
and much indisposition was her allotment for several months.
She continued, however, until the Eighth month, 1805,
and rode out for the last time the day but one preceding her decease.
She could scarcely support the exercise, and returned without benefit.
In this crisis, when attempts to relieve a much enfeebled frame were made in vain,
it was her privilege to have those about her who knew how
to estimate the value of spiritual relief to the mind.
It was her greater privilege to know where to seek it for herself.

When she was in bed, her brother, standing by, remarked to her,
that he was sensible God was near, and that he hoped her dependence would be there.
She replied, "`I am very glad.
There is nothing else to look to now.`"
Nevertheless, the night was a distressing one to her, through bodily suffering,
and in the morning a conflict of the mental kind was permitted to assail her.
It has been hinted that she was of a diffident and humble mind; and now,
perceiving the apparent symptoms of her close,
she imagined that if ever she became prepared to enter into rest,
it must be by the means of great inward suffering: and, with this view,
for a short time her depression was very great.

At this juncture her brother`'s wife was engaged in solemn supplication,
praying that the effective word, which had once gone forth in the season of storm,
when no human effort could be of any avail, and which pronounced, "`Peace,
be still,`" so that there was a great calm, might now be mercifully pronounced,
to the calming of the troubled waves.
Thus was her sister enabled to petition; and before the noon of that day,
Susanna was given to believe that the work of final redemption and purification,
which she had seen to be so great, was not now to do.
This peacefully ending conflict calls to mind the words of the evangelical prophet,
who spoke so clearly of the latter times.
"`I will bring the blind by a way that they knew not:
I will lead them in paths that they have not known.
I will make darkness light before them, and crooked things straight.
These things will I do unto them, and not forsake them.`"

In the evening, having first had an opportunity of conversing with her husband alone,
she was desirous of speaking to her sisters.
They accordingly stood around her; and, after a short pause, with great composure,
she addressed them nearly thus: "`What I wanted to say is,
that it is a great comfort to me that the children have such aunts.
I hope you will take care of them, and endeavor to keep them from doing wrong,
and keep them plain.
It is what I always wished, and what I intended.
It is what their father wishes.
I did not think it was now that I was to be taken.
I thought I should have gone on to the end of my time (to her delivery),
and that it would be then; but when I heard of E. M.`'s death,
it came into my mind that as she was taken from her children,
why might not I? But I did not think it possible I could
be brought to be so well satisfied and resigned as I am.
I thought there must be something horrible on my mind if I was going to die:
and it was that which put me in the way I was this morning,
because I could not feel anything like it.^
footnote:[Her meaning, clear, no doubt, to the by-standers, is scarcely so on paper.
She had let in a notion that very deep exercise of
mind must prepare her for eternal rest;
and not feeling herself thus deeply exercised, she was alarmed,
and thought herself about to go unprepared.]
I feel no weight.`"

Having thus spoken concerning herself and her children, she afterwards was enabled,
though in much affliction of her bodily frame, to take leave of them,
as they were standing about her.
"`I wanted,`" said she, "`to tell you, if anything happens to me,
to be good and love one another.
Don`'t fall out with each other; but be kind and loving.
Mind your father`'s example to you.`"
Then to Susanna, who was about fourteen years of age, she added, "`bind what I have said;
and take care of your poor father, and of his things.`"
She also during her illness cautioned Susanna against the reading of hurtful books.
She said that such had been offered to her when she was young;
but that she had refused to read them;
and that she now found the advantage of such an abstinence.
There are some truths that young people can scarcely know,
but by the testimony of the experience of their elders: and I am willing to assure them,
that vain and defiling things impressed on the memory in youth,
will often turn up in more advanced life, at times when the awakened mind,
knowing their polluting tendencies, would gladly cast them away.
In her more private conference with her husband, among many other things,
she desired him not to have her children taught to draw;
and not to permit them to go much from home on visits.

When she was looking round her, not long before her close,
her husband inquired whether she lacked anything.
She replied, "`No; but I like to look about me on those I love.`"
When her sufferings of body became almost too great to be expressed,
her brother`'s wife signified her belief that the arms of
her heavenly Father were ready to receive her;
adding, that her relations all gave her up, for a happier state of being;
and that therefore she hoped the time would not be much prolonged.
The dying friend replied, "`That is a comfort to me in my distress.
I am satisfied.
The sooner the better.`"
She was heard to be in supplication,
when her voice so faltered that much of what she said could not be distinguished;
but when she was almost in the very article of death, one word was distinctly heard,
and that word was, "`Thankful.`"

This account, with more, I have from her brother; who nearly thus remarks on the whole:
"`These things are not noted down to exalt the creature;
but to the praise of the great name of him, whose power was so wonderfully displayed,
in one who thought herself less than the least in his family:
and that others may be encouraged to look to the same source of help and strength;
and in that alone to confide.`"

Susanna Moore departed the ninth of the Eighth month, 1805.

[.asterism]
'''

JACOB BELL, son of Jacob and Sarah Bell, was born at Plaistow, in Essex,
the 18th of the Eighth month, 1783.
He was remarkable during his childhood for his amiable manners.

When he was in his thirteenth year, his father took him as an attendant on a journey;
on which occasion his innocent and engaging, but manly behavior,
attracted the notice of many friends: especially his solid deportment at meeting,
which was often attended with many tears.
This seemed to show that, in those early years,
his mind was endowed with the principle of grace and truth which comes by Jesus Christ.

When he was about sixteen years of age, he was bound apprentice to his brother,
John Bell, chemist, in Oxfordstreet.
He served his apprenticeship with much diligence, and at the expiration of it,
engaged himself as an assistant to his brother.
In about six months, however, he had contracted a pulmonary complaint,
and in the Fourth month, 1805, he came to his father`'s house at Plaistow,
for the benefit of the air.
He seemed at first to mend; but as his amendment was of little duration,
he was recommended to try the air of the vicinity of Southampton.

The disposition of his mind, at this time,
may be seen by the following extract of a letter to his brother,
written not long after his arrival in the neighborhood of Southampton.

[.embedded-content-document.letter]
--

[.salutation]
My Dear Brother,

Reflecting on the varied +++[+++various]
dispensations allotted to mankind by a merciful Creator,
I cannot but at times be thankful for the one allotted me, though apparently afflicted,
whether I should recover or not:
at the same time feeling for the anxiety of my dear relations.
How many are called from this scene of action without many days`' warning.
When we take into consideration the many trying baptisms those
have to pass through who are devoted the best of causes;
if allowed the choice, it seems as though the shorter time might be preferred,
by those who enjoy a hope of mercy;
yet at the same time not doubting that they meet with their reward, manifold here,
as well as hereafter.
Sometimes, looking forward towards the possession of health and strength,
I am ready to fear my weakness in taking up the cross.
At times, petitions are put up for an increase of stability,
and willingness to attend to the inward monitor.

--

After remaining seven weeks near Southampton, and finding an increase of disease,
it was concluded to try the Hot-well water, and accordingly he set out for Bristol;
but at Bath his parents were much alarmed by the breaking of an ulcer in his lungs.
This enfeebled him much; but he thus expressed himself to his mother:
"`You have done what you can.
Make yourselves easy.
I shall do well.`"
He used the Hot-well water freely, but unavailingly;
and as he did not appear to amend after a stay of five weeks,
the physician recommended his return home, where he arrived the 14th of the Ninth month.

While at the Hot-wells, he wrote a letter to a friend,
of which the following is an extract.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Bristol Hot-wells, 28th Eighth month.

[.salutation]
Dear Friend,

Seeing the Almighty sees fit in wisdom and mercy to visit
his created beings with afflictions of various kinds,
it is no doubt our duty to endeavor to bear them with cheerfulness,
and as much fortitude as we are capable of; knowing they are for some good purpose.
Instead of repining at my lot, I have great cause to be humbly thankful;
for how many are called from this transitory scene, as it were at a moment`'s warning:
which has not been my case.

I think I may say I have been favored in a good degree with that serenity of mind,
which you have been so solicitous I might enjoy.
By placing our whole dependence on the Almighty holy arm of power,
we shall be blessed with resignation and patience,
that will uphold us through every difficulty, or season of trial.
Though at times I have been favored to feel great satisfaction and comfort,
in respect to the termination of my disorder,
should it prove contrary to the desires of my friends;
yet it is necessary for me to keep on the watch, and attend to our inward instructor:
knowing our unwearied adversary is ready to rush in at every weak corner.

--

After he came home, notwithstanding the continuance of medical advice,
and of the most unremitted maternal care, he grew worse, and had an additional ailment,
the thrush, which occasioned great difficulty in taking either food or medicine;
but he bore it with Christian fortitude, desiring to be favored with patience,
and was wonderfully supported.

On the Fifth day before his decease, his parents only being with him,
he said nearly as follows: "`Being brought into a state of suffering,
how different things appear to what they have done.
If it please Providence to remove me, I may escape many trials which we are liable to.`"
His mother said she hoped that he felt his mind comfortable under his present situation.
He replied, that at times he did, "`although,`" said he,
"`we are liable to many slips;`" adding,
that he should have wished to see his way with greater clearness.
"`O, father,`" said he, "`is there any hope for me?`"
His father replied, "`Yes,
in a future life;`" and made some other remarks to comfort him in this trying state.
On taking leave of his sister, who afterwards had come into the room, he said,
he hoped she never would be afflicted as he was; desired her to mind the inward teacher,
the Spirit of truth, and to wait upon it in meetings, and not to think of idle subjects,
which had been cause of uneasiness to him;
and he requested she would be attentive to what Providence pointed out to her.

On the Seventh day, a visible alteration took place in him.
On parting with his brother, Sheppard Bell, he said, "`Give my dear love to Betsey,`"
(wife to S. Bell;) "`I suppose I shall never see her again.
Farewell, dear Sheppard.
My time is now short, very short.
I hope you will be patterns in the Society.
Farewell, dear Sheppard.`"

After this, his mind was much stayed upon the Lord.
He prayed very fervently, at one time audibly, as follows: "`O, Almighty Father,
if it please you, shorten my sufferings, and that my patience may hold out.`"
He also desired his father to pray for him; and, after a weighty pause,
supplication was put up to the Almighty,
that he would be pleased to be with him to the end, and grant him a place in his kingdom,
among those who are already sanctified.

He was quietly removed, departing without a struggle, on First-day morning;
and there is cause to believe he was favored with increased clearness,
and that his petitions were granted.
He was upwards of twenty two years of age when he was thus removed.
His decease was the 27th of the Tenth month, 1805.

It may be truly said that his life was a life of innocence.
He had a great regard for the Scriptures of truth.
He particularly desired that his Bible might be given to a young man of his acquaintance,
who had lately opened a boarding-school.
