== Chapter 1

[.chapter-synopsis]
* Joseph Harwood
* Tabitha Middleton
* Mary Alexander
* Deborah Darby

JOSEPH HARWOOD.--The life of Joseph Harwood, of Manchester,
affords a striking instance of the efficacy of the grace of God,
inwardly revealed to the soul, when it is faithfully and unreservedly obeyed.

He was born in the year 1712, at Bolton in Lancashire,
where his parents lived in good repute.
His father was a conscientious member of the church of England, a man of integrity;
one who professed and knew that religion is an inward work.
He died when his son was not more than twelve or fourteen years of age;
but his piety and instruction had made a deep and
lasting impression on the tender mind of his child,
who, as he advanced in years,
was more and more introduced into those conflicts which attend the Christian warfare.

He was often, before he arrived at maturity, involved in sorrow of heart,
when reflecting on those things which appertain to the life that is to come.
In this state, and from a wish to be more at liberty to attend to the duties of religion,
a very unusual motive for such a step, he entered the army, in the year 1731;
but in so doing, he found himself greatly disappointed.
His companions seeing his anxiety and distress, and being strangers to the real cause,
formed various conjectures concerning him; but such were his sobriety, docility,
and readiness to serve others, that he gained the esteem and confidence of his officers,
and was mostly employed in their particular services.

He continued in the army about fifteen years, beloved and esteemed in his station,
and acquitted himself with credit and fidelity.
But that good and gracious Being, who had visited him early in life,
continued to follow him in mercy and in judgment;
and in the course of the latter years of his military service,
was pleased to show him with indubitable clearness,
the utter inconsistency of all wars and fightings with the Gospel of life and salvation,
and to require him to bear a faithful testimony to the same.
Through the gradual operation of the Holy Spirit,
this conscientious man was made willing,
in conformity with the example and doctrine of Him
who came not to destroy men`'s lives but to save them,
to refuse to bear arms any longer, and to submit to whatever might ensue,
although he knew that a punishment no less than the loss of his natural life was impending.
He was tried by a court-martial, and treated with great moderation and civility;
some who had been his fiercest opposers becoming his advocates.
The remarks which he made on his own behalf, produced great seriousness.
The court forwarded a candid representation of his case to king George the Second, who,
on the intercession of some friends, honorably gave him his discharge,
after about six months`' imprisonment.

Not long after his release, having joined our religions Society,
he took up his abode at Manchester.
In the course of a few years he was brought under a religious
exercise of mind to speak as a minister of the Gospel,
to which he yielded, about the fortieth year of his age.
Being faithful in the use of the talent received, he increased in religious experience;
and though his public testimonies were not long,
he was often baptized into a sense of the condition of the meeting,
being reverently concerned to feel the renewal of power from on high,
before he stood up to minister to others.

He visited the meetings of Friends in Ireland, and several times, those in Scotland;
and also travelled in other parts of this nation.
He was frequently engaged, in gospel love,
to visit Friends in his own meeting and neighborhood,
to see how it fared with them in the best things; when, from easy, innocent conversation,
he was often drawn into solemn silence;
and therein his heart was replenished as with the dew of heaven,
under the lively influence whereof, he offered seasonable exhortation and counsel.

He was careful not to entangle himself with the cares of this life,
seeking to have his treasure in heaven.
Though naturally cheerful, and very agreeable in company,
his words were frequently seasoned with the salt of the covenant,
evidently ministering grace to the hearers.
As his heart was thus warmed with love towards his brethren,
so was he also greatly beloved by them.
Being a man of meek and inoffensive deportment,
and much devoted to the promotion of peace and good will among men,
his company and conversation were acceptable to most who knew him,
of various religious professions.

Some years before his death he became very infirm,
being afflicted with an asthmatic complaint; yet he constantly attended his own meeting,
fervently laboring therein for the arising of Divine life,
and often speaking as a minister, greatly to the comfort of his friends.
After a short illness, he died on the 12th of the First month, 1776,
at the age of sixty-four.

[.asterism]
'''

TABITHA MIDDLETON.--In the lives of many dedicated and humble servants of the Lord,
it not infrequently happens, that but few incidents are met with,
from which a biographical sketch can be compiled;
while their faithful endeavors to serve the Lord in the way of his requirings,
may have exhibited a bright example to those around them.
Such appears to have been the case with Tabitha Middleton,
of Wellingborough in Northamptonshire, who was the daughter of John and Sarah Hoyland,
of Sheffield.

In a letter to an intimate friend,
she thus describes her sense of the goodness of the Almighty in her youth.

[.embedded-content-document.letter]
--

On looking over years that are past,
I find abundant reason to acknowledge the mercies of Providence,
in extending his heavenly visitation in the very early part of life,
which raised strong desires to walk acceptably before Him.
I well remember the exemplary care of my dear mother, at that time,
whose conduct and advices made lasting impressions on my mind; though,
as I advanced in years, "`the lust of the eye and the pride of life,`"
too much influenced the judgment, and weakened my good resolutions,
which made even life a burden.
But how have I admired to be in this state allured
to prefer Jerusalem before my chief joy;
concluding, that whatever I parted with or suffered,
was not to be compared with the enjoyment of Divine good.

--

When about fourteen years of age, she was deprived of her mother.
By this loss, and other events which succeeded,
her mind appeared to be increasingly turned to seek for the consolations of religion.
She resided at that time at Sheffield,
and manifested a pious care and solicitude for the
younger branches of her father`'s family:
she was much beloved by her young friends generally, to whom she was also a good example,
in a humble and circumspect deportment.

In the year 1783, she was married to Benjamin Middleton, of Wellingborough,
when her religious usefulness became more extensive,
in an enlarged sphere of relative duties; in the faithful discharge of which,
the meek equanimity of her conduct presented an instructive lesson to many.

After a time of much thoughtfulness, she had, when about twenty-five years of age,
yielded to a belief that it was required of her to appear as a minister.
Her communications in this character were acceptable to her friends,
and delivered in great clearness and simplicity; and she was, for several years,
at times, diligently employed in various parts of this nation,
in visiting the meetings of her fellow-professors.
She was much concerned for the right exercise of our Christian discipline,
in the spirit of love and meekness; and, being clothed with true charity,
administered counsel, and sometimes close admonition,
in a way that often appeared to be not only well received,
but to be attended with a blessing, particularly to those in early life.
She was indeed a mother in Israel, an experienced and judicious counsellor,
a firm and sympathizing friend.

She attended her own and a neighboring quarterly meeting, in the autumn of 1809,
and was soon afterwards taken ill.
The symptoms were not alarming until the day preceding her death;
but the awful messenger was not to her a king of terrors.
In the course of this illness she remarked:
"`I have been permitted to live until I am not afraid to die; nor am I anxious to live,
except on account of my husband and children.
If I should be taken away, it may be said I am released from all my labors.`"
She died in peace, on the 18th of the Tenth month, 1809, at the age of fifty-nine.

[.asterism]
'''

MARY ALEXANDER, of Needham-market, in Suffolk, was, at a very early age,
tenderly affected with the visitation of Divine love, which inclined her mind to piety.
Before she had attained her seventeenth year,
she was impressed with a strong apprehension that,
if faithful to the manifestations of the Holy Spirit, she should, at a future day,
be called to the work of the ministry; yet,
notwithstanding this gracious condescension of the Almighty,
for lack of steadily abiding under the operation of his power,
she deviated from the simplicity of her guarded education,
and gave way to youthful propensities averse to religious restriction and seriousness.
Yet mercy and truth followed her; her heart was often made sad,
under a sense of disobedience;
and she sorrowfully felt that there was much which required to be slain by "`the
sword of the Lord`" before she could be brought into a state of acceptance.
Thus humbled and contrited before Him,
she became at length effectually awakened to a search after enduring happiness,
often and earnestly imploring that all within her might
be brought into subjection to his holy will.

She now found much consolation in the perusal of the Holy Scriptures,
and deeply lamented having spent any of her time in reading plays,
and writings of a similar description; being sensible,
that nothing she had ever been in the practice of,
had so much alienated her mind from the fear and love of God;
and she often wished she could warn all,
and especially the youth of her own religious Society,
of the pernicious tendency of such writings.

About the year 1786, she lost her surviving parent; from which time, to the year 1789,
she sustained, from various causes, many deep conflicts of spirit.
Many, also, were the baptisms of her soul,
from a nearer view of the prospect she had long had of a call to the ministry,
which now came weightily upon her, and on which service, in much humility and fear,
she entered in the course of the same year, being the thirtieth of her age.

The general tenor of her subsequent conduct gave evidence to others
that she loved "`the habitation of the Lord`'s house,
and the place where his honor dwells.`"
She was given up in much devotedness, to leave her own comfortable dwelling,
and to advocate the cause of Christ, both among her own friends,
and in more distant parts;
and was frequently constrained to manifest her interest
in the spiritual welfare of her fellow-members,
by paying religious visits to the families of friends;
a duty for which she appeared eminently qualified;
and there is reason to believe that her faithful
labors were often productive of solid benefit,
both in and out of our Society,
and that they yielded to her own mind the peaceable fruits of righteousness.

In the discharge of her more private duties,
she gave proof of possessing a heart expanded by benevolence;
and to sympathize with others,
and render assistance to them in times of difficulty or affliction,
was a conspicuous part of her character.

Her last Christian efforts in advocating the gospel,
were comprised in a visit to the families of friends in the city of Worcester,
and parts adjacent, and in holding some public meetings,
in conjunction with a friend under similar concern.
The last meeting which she attended was held at Alcester,
on the 13th of the Eleventh month, 1809,
and was one to which the inhabitants of the town were invited; it was very large,
and was considered to be remarkably solemn.
In this meeting she was engaged in fervent, vocal supplication.
She had been unwell for several days, and soon after the conclusion of this engagement,
it appeared that she had taken the small-pox.
The disorder did not assume an alarming aspect until after the usual crisis,
when the symptoms were such as to dispel the hopes
that had been entertained of her recovery.
Through the whole of her deeply-trying illness,
she discovered much patience and resignation,
and her mind seemed to be divested of every burden.
Speaking of her late visit, she said she had been favored with a precious evidence,
that she had been there in better wisdom than her own.
Articulation being often difficult, she did not express much; and,
from the extremity of her sufferings, was sometimes anxious to be released,
and thought her spirit long in departing, yet carefully avoided,
either in word or manner, murmuring at the conflict.
She was preserved, with little intermission, sensible to the last;
and during the final efforts of nature,
several times held up her hands as in the attitude of prayer.
She quietly expired on the fourth of the Twelfth month, 1809,
in the fiftieth year of her age.

The friends of Worcester monthly meeting,
in taking a retrospect of her labors among them, observe:
"`We may weep over her as a friend, or as a relation;
we may mourn the loss which the church has sustained, of one of its upright pillars;
but on her account there appears no cause for sorrow.
She was, we believe, favored to finish all she had in commission;
showing herself therein a good and faithful servant,
and we doubt not she has entered into the joy of her Lord.`"

[.asterism]
'''

DEBORAH DARBY was the daughter of John and Hannah Barnard, and was born at Upperthorp,
near Sheffield, in the Eighth month, 1754, and died the 14th of the Second month, 1810.

She was naturally of a sweet and amiable temper, and, in her youth, of a lively,
active disposition.
In early life, she frequently experienced the contriting visitations of Divine love,
and in opportunities of retirement was humbled before God.
Her example, in thus withdrawing from the pursuits of time,
and cultivating a watchful state of mind, and her reverence for the truths of religion,
combined with a kind and cheerful demeanor,
had an attractive and beneficial effect on some of the friends of her youth.
Her care to retire to wait upon the Lord in secret, continued through life;
and having known this habit, at an early period,
to contribute to temper her own vivacity,
she was often engaged to recommend the practice to others,
especially to her younger friends.

In the year 1776, she was married to Samuel Darby; and they lived for a while in London,
but afterwards settled at Coalbrookdale, in Shropshire,
which was the place of her residence until the time of her death.

Having submitted to the convictions of the Spirit of Truth, she learned from experience,
that, whether in prosperity or adversity,
there is no joy comparable to that which results from a conformity with the Divine will.
She was thus prepared to yield to an apprehension
of duty to become a minister of the Gospel,
and first came forth in that character in the year 1779.
Being concerned to keep low and watchful before the Lord,
she advanced from stature to stature in this sacred office,
and her services were truly acceptable to her friends.
In the year 1781,
she first travelled with a certificate of the unity of her monthly meeting;
and from that period, through a course of near thirty years,
she was a diligent laborer in the Gospel of Christ, at home and abroad,
among those of her own religious Society, and other professors of the Christian name.
She repeatedly travelled through most parts of this nation, was several times in Ireland,
and was absent from her native land nearly three
years on similar religious service in America,
in company with her endeared fellow-laborer, Rebecca Young, now Rebecca Byrd.

On landing at New York, the 8th of the Tenth month, 1793,
she made the following memorandum:

[quote]
____
On waking this morning,
we found ourselves in the harbor of New York, and had a beautiful view of the town.
We went to the house of our friend John Murray, who, with his wife,
received us affectionately;
which impressed our minds with gratitude to the Author of Mercies, both ancient and new,
who had thus brought us safely over the mighty ocean.
May He so preserve us, as to bring us at last into that port and haven of rest,
at the end of time, where the morning stars sing together,
and the sons of God shout for joy!
____

Having endeavored to know and
to do the will of Him in whose service she had gone forth,
she wrote the following short acknowledgment of his all-sufficient help,
on the day on which she embarked for her native land:

[quote]
____
We attended a public meeting at Newcastle.^
footnote:[A town on the western bank of the Delaware, below Philadelphia.]
After dining with about one hundred and fifty Friends,
we had a solemn parting opportunity, in which much encouragement was handed,
and prayer put up for mutual preservation, under the influence of humbling Goodness,
that had, we trust, put us forth, gone before us,
and now condescended to be our reward.
____

In the course of this journey,
she often felt her mind warmed with Christian love and compassion
for the native Africans and their descendants,
so numerously settled in the United States; and in the larger cities,
religious meetings were specially held with this degraded and injured class of our fellow-men.
In passing along, both in England and America,
she at times visited those confined in prison, some when under sentence of death,
fervently laboring to turn their attention to the Savior of the world--to Him, who,
as he is applied unto in sincerity and in truth,
will still be found to be the Friend of sinners.

The character of this diligent laborer, when employed in the service of her Lord,
is thus delineated by one who was long and intimately acquainted with her:

[.embedded-content-document.testimony]
--

I can say of her, that in and under all our conflicts,
and the severest of her particular trials,
I never met with one whose conduct evinced a stronger confidence in God,
or whose faith was firmer in the appointed means of salvation.
Thus supported, even when the waves of affliction rose high,
she was enabled to center in resignation,
and to follow on in the line of her religious duty.
Loving the light, she manifested her love by simple and unreserved obedience,
without consulting ease to the flesh, or present gratification.
I think her humility was conspicuous,
rendering her a good example to her fellow servants; to whom, even to the least,
she was ever ready to to give way,
when sensible that the anointing was poured forth upon them.
Her fervent zeal for the welfare and preservation of the youth,
in that path of self-denial which Truth leads unto, cannot be forgotten.
Wherever I travelled with her on its account,
I was witness to her pious and arduous labors with that class of society.
Seldom could her devoted heart feel satisfied to
leave Friends`' families without gathering the children;
and many, I believe, there are in different parts,
who have cause to bless the Lord for having made her an instrument of good to them.

--

The dispositions which have been noticed as obvious in early life, matured by years,
and sanctified by the power of religion,
rendering her an endeared and instructive companion;
one who was ever attentive to the right discharge of her relative and social duties.
She was solicitous for the help of the poor,
and concerned that a due proportion of her outward
substance should be expended to promote their comfort.
She was not apt to take offense, and cautious not to give it;
and exemplified in her conduct, even under the pressure of heavy affliction,
the excellency of that Gospel which she was commissioned to preach.

In the spring of 1808,
Deborah Darby left home on a visit to Friends in the southern and eastern counties.
In the autumn of the same year, she was considerably unwell, and exhausted by fatigue;
and this debility continued through the winter.
She was again absent from home for several weeks in the spring of 1809,
and returned so far improved as to be able to join her friends
in their public assemblies for Divine worship;
but, as the winter approached,
the gradual decay of nature rendered it necessary
for her to confine herself very much to the house.
The following extracts, from a few memorandums left behind,
exhibit the humility with which her mind was clothed.

[.offset]
"`I have had some precious seasons of Divine overshadowing during my illness;
which have been better than all the cordials administered by my medical attendants.`"

[.offset]
"`I am sometimes strengthened to speak well of His name, who lives and reigns,
and is forever worthy.
I have cause to be thankful for strength being granted to sit with my friends,
though often in much poverty of spirit.`"

[.offset]
"`I have little to remark, my allotment being often in suffering as to the body,
and low in mind; yet I can say, God is good, and a strong-hold in the day of trouble.`"

She endured much bodily suffering previous to her dissolution,
with exemplary patience and sweetness, remarking:
"`Unless the Lord has some further service for me to do,
I could not wish to stay much longer, I suffer so much;
but all in his ordering is best.`"
And at another time, when in great pain, said,
"`It would be a great favor to have a little ease once more before I leave you;
I should like to be a little cheerful,
for I have nothing but the pains of the body to make me otherwise.`"
After having been greatly exhausted by seeing some of her nearest relatives,
she said to a friend sitting beside her, "`The Lord be praised.
He is wonderfully good, even now.`"
The evening before her death, when in extreme suffering, one of her attendants,
who thought she had asked for something, said, "`Can we do anything for you?`"
to whom she replied, "`Rejoice evermore,
and in everything give thanks!`" and shortly afterwards said,
"`The Lord`'s will be done.`"
She seemed to be engaged in supplication for some time after this,
although her expressions could not be understood.

Thus was this faithful disciple enabled, in the closing days of her earthly pilgrimage,
to confide in the Almighty,
and to evince that her soul was prepared to unite in that song of praise and thanksgiving,
which is the blessed employment of those redeemed spirits
who stand before the throne of God and of the Lamb,
forever and ever.

[.the-end]
THE END OF THIRD VOLUME
