// NOTE: NOT MODERNIZED
== Preface.

The following sayings of the dying, give fresh occasion to say something to the living,
in order to stir them up seriously to consider their latter end,
by a timely preparation for it, lest it should come upon them at unawares.
Let such remember that that servant is blessed, whose lord, when he cometh,
shall find him watching.
Many would gladly be welcomed by Christ with "`Come,
ye blessed of my Father,`" who do not consider the terms on which this is to be attained,
viz.: "`Not every one that saith Lord, Lord,
but he that doth the will of God;`" agreeably to that saying,
"`Blessed are they that do his commandments,
that they may have right to the tree of life.`"

What hinders man in his duty to God,
is his not complying with the manifestations of the Holy Spirit,
which is given to him to profit withal.
For the Lord sets before men life and good, death and evil;
and at the same time invites them to choose the good, that they may live;
and to assist them in so good a work, his Word is nigh in the mouth and heart.
It was this Word of faith which the apostles preached,
by whose ministry many were turned unto God from the dark world and the vanities of it,
to serve the Lord in the way of holiness, being brought nigh by the blood of Christ,
by whose death the partition-wall was broken down,
and no difference made between Jew and Gentile, according to that prophecy of Isaiah,
"`It is a light thing that thou shouldst be my servant, to raise up the tribes of Jacob,
and to restore the preserved of Israel.
I will also give thee for a light to lighten the Gentiles,
that thou mayest be my salvation to the ends of the earth.`"
This shows the wonderful kindness of the Lord to the whole race of mankind;
whose will is, that all men should be saved, and come to the knowledge of the truth;
and for that end also Christ gave himself a ransom for all, to be testified in due time.

The history of these things being open to so many nations,
it is wonderful that so few are concerned to search into the mystery of them,
in order to know Christ in them, the hope of glory.
For the bare belief only of what Christ hath done for men without them,
will not secure salvation to them, unless they come to witness his work in them,
and by it to be born again, or from above,
consonant to the doctrine of Christ to Nicodemus.
This certainly is the one thing needful for men to
have the experience of in their pilgrimage here,
which, as they grow up in it, is the only evidence of their future happiness.

It has been the pursuit of this, which, through the grace of God,
has caused many to take the yoke of Christ upon them,
and early to learn of him who is meek and lowly in heart,
and by whose direction they have found rest to their souls.
After this manner the religious have learned the ways of wisdom,
whose ways are ways of pleasantness, and her paths are paths of peace.
These pious ones have often invited others to taste and see that the Lord is good,
and worthy to be obeyed.
But alas! it is not so with the disobedient, who obey not the truth, but unrighteousness.
To such who are in that state, indignation and wrath, tribulation and anguish,
upon every soul of man that doth evil; but glory, honour,
and peace upon every soul of man that doth well.

My friends, in the sense of this I am drawn forth to entreat you,
who have known the good work of God to be begun in you,
that ye labour with the gift of grace bestowed on you, to know the work perfected in you,
and that you may not be always learning,
and not attain to the true knowledge of the truth, which many have long professed.
Rouse up, I beseech you, ye old professors,
and examine into the reason why you are so long before
you obtain a conquest over the world,
and the spirit of it.
I tell you plainly, it is your abiding in conformity to the ways thereof,
which makes you so late with your day`'s work.
You might ere now have been firmly established in the present truth,
had you come to self-denial, and taken up your cross for Christ`'s sake,
who suffered on the cross for you.

I often hear exhortation to the youth, to forsake the ways of this corrupt age,
which would be very well for them to do, but their eyes are sharp, and ears are quick,
and they readily take notice of the example they have at home;
and if that be not completely what it should, it is very likely,
from the defect they see, they will go a step farther, and thus by degrees,
the simplicity of the gospel conversation is in danger to be lost.
In this case it may be said, that if the children of the kingdom will not enter,
others shall come from afar, and sit down with Abraham, Isaac, and Jacob,
in the kingdom of God.
For I have a strong persuasion,
that the gospel power will prevail abundantly in the earth,
and many shall flow to the Lord as doves to the windows.

For since men departed from the teachings of the spirit of God,
to rest on the teachings of men,
they have been spoiled through their philosophy and vain deceit,
after the tradition of men, after the rudiments of this world, and not after Christ.
But thanks be to God, who hath opened the eyes of many to see beyond the doctrines of men.
Such are come to the teachings of Christ,
and to hold the doctrine delivered by him and his apostles,
according to the simplicity of the gospel,
and cannot mix the human inventions of men with the pure doctrines of the Lord.
For they being dead with Christ from the rudiments of the world,
cannot be subject to their ordinances; nay, they cannot touch, taste, or handle,
because they are all to perish with the using,
after the commandments and doctrines of men.

It is to this stability the Lord hath brought many, and will, I believe, bring many more;
for as the Son of righteousness arises, the shadows will more and more flee away,
and then will that which is perfect be known.
The heart will be established with grace,
the divers and strange doctrines of men refused,
and the gospel preached in the demonstration of the spirit and of power;
and men be concerned to work out their own salvation with fear and trembling.

It is for this end I write these lines,
that if possible I may hereby induce the readers to mind the great concern of life,
which is to lay up treasure in heaven,
and thereby answer the end of their stay upon earth.
This cannot be effected, but by the denial of self,
and taking up a cross to the corrupt will and inclinations of degeneracy,
which work our Lord is come to effect, and certainly will,
in all those who come in subjection to his holy spirit;
that being the means afforded men to direct their steps to everlasting life.

It is by this the soul is awakened as it were out of a sleepy condition,
and quickened into a sense of its lost estate and miserable condition,
that if the great saviour of man help not, it must perish.
The sight of this has brought repentance unto salvation upon many,
to a thorough change of heart, and reformation of manners;
for which they became a wondering,
and sometimes were held in derision by those who were strangers
to that divine power which wrought this blessed change.
But, alas! these things are of old date,
and ought not to discourage any from a pursuit after an holy life; because without that,
we are assured, we cannot see the Lord.

Much might be written on a subject tending to a pious life,
in order to stir up the living to a timely preparation for death; which that all,
through the grace of God, may have regard to, is the great concern of my mind.
But it is to be lamented that Christendom, in a general way,
seems to rest contented with the profession of Christ,
and a worship which is according to the prescriptions of men,
whom they call ministers of the gospel,
as if by them they expected their salvation to be wrought out;
when it is more likely that, if the blind lead the blind,
they will both fall into the ditch.
Therefore they are advised to come to Christ, that they may have life, and may know that,
with it, immortality is brought to light through the gospel;
which gospel is not what many apprehend it to be, viz., a record of the four Evangelists,
which must be allowed to be contained in papers and letters; that is, indeed,
an account of the thing, but the thing itself is the power of God unto salvation,
to every one that believeth,
as the apostle Paul expressly declared to the Romans, ch. 1. ver. 16.

It is for want of coming to the experience of this power that men take up with the letter,
and with what they hear from others, and are not in search after the thing in themselves;
and this gospel may more properly be said to be preached in every creature under heaven,
than to be preached to every creature.
For most certainly the first, i.e., the power of God, is everywhere;
the latter comparatively but in few places.
Wheresoever the gospel is instrumentally preached in the demonstration of the spirit,
the people who hear the same, and turn to the Lord, are highly favoured by him.
And if the power of God inwardly revealing itself in men, and the preaching thereof,
by such whom the Lord is concerning for that end, will not prevail with people,
their condition is to be lamented.
Such is the stupidity of some, that when the judgments of God are apparent in the earth,
as sword, famine, pestilence, or drought,
they will attribute those things to natural causes, and thereby, if they could,
set aside the overruling power of God, and by that means hinder his judgments,
when in the earth, from having that good effect, viz.,
to cause the people to learn righteousness

Thomas Raylton.

London, the 20th of the Eighth Month, 1723.
