// NOTE: NOT MODERNIZED
== Preface.

Courteous Reader: As the design of writing and publishing to the world is,
or ought to be, instruction and improvement,
and as the advantage or profit of any knowledge or instruction
is to be considered according to the usefulness of it,
so, the more durable it is--that is,
that it be such as will be of the longest use to us and ours--the more it is to be valued.
In both these respects, the knowledge of ourselves, our frailty,
and the shortness of our time, of which too many are unmindful, will have the preference,
both with respect to the usefulness of them, and their continuance.
For the due consideration of these things will be of advantage to us,
both here and hereafter, and will regulate us, both with regard to our duty to God,
our own souls, our posterity, and our neighbours.

They will be of such real service to us, that no knowledge else,
the knowledge of God and the revelation of his will excepted, can be of equal benefit.
It was under this consideration that the Psalmist cries out, "`Lord,
make me to know my end and the measure of my days, what it is;
that I may know how frail I am.
Behold, thou hast made my days as an hand-breadth,
and my age is as nothing before thee:
verily every man at his best state is altogether vanity.
Surely every man walketh in a vain show: surely they are disquieted in vain:
he heapeth up riches, and knoweth not who shall gather them.`"

For by duly considering the shortness and uncertainty of our continuance here,
we shall be led to improve and redeem the present opportunity as a favour from God.
It is an unquestionable truth, and confirmed by daily experience,
that "`it is appointed unto men once to die;`"`' and the time when, or the age whereat,
we shall be removed hence, is altogether uncertain;
which occasioned the man of God to say, "`Oh! that they were wise,
that they understood this, that they would consider their latter end.`"

The Psalmist had this in remembrance when he recommended
to our consideration the concluding moments of the righteous.
"`Mark the perfect man, and behold the upright, for the end of that man is peace.`"
The great and necessary work, and one thing absolutely and indispensably needful,
that mankind of all ranks and ages ought to be chiefly concerned about,
during this short and uncertain time the Lord affords to us in this world,
wherein we are liable to many temptations, afflictions, and tribulations,
is in the first place to know God, and, in the second, so to know ourselves,
and remember our latter end, that we may live such careful, circumspect, and godly lives,
that we may have peace of mind in the conclusion,
and have the spirit of God to bear witness with our spirits that we are the Lord`'s,
knowing by living experience that Christ in us, by his divine appearance,
is the hope of our glory.

We find, when death approaches, that what is most desirable, and of the greatest comfort,
is to be sensible of the favour of God,
and to be in the enjoyment of that peace which he
gives to all those who have lived godly lives,
and walked in uprightness of heart before him by that ability given them of God,
through the gift of his grace, which is inwardly revealed.
Therefore in good will to all, and in order that the minds of all,
to whose hands these shall come, may be awakened and stirred up to diligence,
whilst health and strength are afforded, to a due remembrance of their latter end,
that through that grace which is given of God to all,
and sufficient in all things when duly regarded, and the power of it waited for,
preparation may be made for that trying time,
and that the call of death may not be a surprise upon any one of us,
is the end wherefore the following collection is made public.

In it the aged, whose stay cannot be long here, will for their encouragement,
if faithful, find expressed by dying lips the great peace,
satisfaction and comfort those who were aged enjoyed at their conclusion,
who had walked before the Lord in truth and with a perfect heart,
and by his help had done that which was right in his sight,
and retained their integrity through all the trials
and difficulties of this life to the end.
Likewise those who are middle-aged will see,
by the example of such who were called off in that stage,
the great benefit and advantage those received and expressed,
who finished their course in the strength of their time,
who were devoted in heart to the service of God,
and having given up their names to do his will,
were faithful in answering his requirings.

Those who are young will see their equals in years
were not exempt from the stroke of mortality,
and by their example may be provoked to diligence,
who were concerned to seek the way of the Lord early,
and an acquaintance with him in their young and tender years,
and had taken the advice of Christ our Saviour,
to`'`"Seek first the kingdom of God and his righteousness,`" "`and had
nothing to glory in but the cross of Christ;`" and what is very affecting,
the lively and sensible expressions of such whose pilgrimage in this world,
ended when they were very young.

If we seriously consider, whatsoever station we may be in, as to this world,
and though we may promise to ourselves many years,
yet when the time of dissolution is at hand, and the gates of death open before us,
and we are ready to enter into an eternal and unchangeable estate,
which may happen to the youngest,
when the hope of our being any longer here is taken away,
we shall then see that all we are possessed of in this world, how much soever it may be,
can add no comfort nor yield any relief.
Then peace with God and the comforts of his love,
and an inheritance in that kingdom which fades not away,
and to be received by the Lord into a blessed eternity
with the spirits of the just made perfect in him,
these will be the things to be desired.

These will be the things to be sought after at such a time as this.
If thou, therefore, whether elder or younger,
readest over the following testimonies with attention,
they may be of use to awaken thee to a consideration of thy condition,
if not already awakened, so as to know thyself, thy frailty and misery without a Saviour.
And if already awakened, the many lively and affecting expressions herein contained,
may be an incitement to thee to pursue more fervently the work of salvation;
and then as I received benefit and comfort in collecting them,
so wilt thou in perusing them;
and the end of my labour in transcribing and publishing them will be fully answered.

Before I conclude this preface, I would earnestly recommend,
especially to the youth of our society of both sexes,
the serious perusal of these following sheets, and not of these only,
but also of the other parts of the Dying Sayings of many
of our worthy ancients and pious friends heretofore published.
For what can be more affecting to tender minds,
or more prevalent with such who are religiously inclined,
to stir them up to remember their latter end, and the uncertainty of their time,
than the good example, and lively testimonies, advice, and admonition,
confirmed by the experience of such, of differing ages and stations,
who through obedience were filled with the love of God,
and witnesses of his favour and goodness, when on their dying beds,
and ready to put off these earthly houses and tabernacles of clay,
who had an assurance of a "`building of God, a house not made with hands,
eternal in the heavens.`"

But let it be strictly observed,
that the tendency of these testimonies and advices of persons near their departure,
both of the elder and younger sort, ever hath been,
that all might be careful to live godly and self-denying lives,
and might take up the cross to their own wills and natural inclinations,
and follow the Lord Jesus Christ in the narrow way, which leads to life,
and might wait for the power of his cross in themselves,
to crucify them to the world and the world to them,
that so the many enticements and allurements of this world, with the hurtful vanities,
fashions, customs, and other evils of it,
might not prevail to divert the mind from seeking
after the true knowledge of God and Christ,
whom to know is eternal life, nor cause them to be forgetful of their latter end;
the frequent consideration whereof many times proves a motive
to a diligent concern to be duly prepared for it.

For we may find by the testimony of our worthy ancient friends,
how they were concerned both for their own children and others,
that they might be preserved from the vanities and corruptions of the world,
and those foolish fashions and fopperies of dress,
which are so prevalent with too many of the professors of truth in our time,
as though a conformity to the world in these things were no crime in them,
though many of their predecessors were called out of them,
and suffered deeply for their testimony.
In like manner the testimonies and advices of the
youth to those who were their equals in age,
were to refrain from these youthful follies which
would prevent them from making that due preparation,
which will administer peace in the conclusion,
in which some of them had been ensnared by their soul`'s enemy,
and were raised up as witnesses for God, to be a warning to others.

It must be acknowledged by all who are duly considerate,
that this generation of friends is highly favoured of God,
in that they have the renewed visitation of his own Spirit in themselves,
and are brought up in the belief of it, and have line upon line,
and precept upon precept, to warn and invite them to give heed to it,
and the truths of the everlasting gospel of Christ,
frequently and freely preached in the power and demonstration of his own spirit,
and the best of Christian advices often repeated in the love and fear of God,
and the prayers of the righteous, which are said to avail much with God,
daily put up for their salvation, and the salvation of mankind in general.

Let it therefore be solidly considered, that for all these,
and many other mercies of God, with which we are favoured,
we must be accountable what improvement is made, for the Lord is looking for fruits.
Whether are we bringing forth fruits of gratitude and a due submission to his will,
who has thus visited and favoured us?
Where wild grapes are brought forth, it is highly displeasing to him,
and offensive in his sight, who now as well as formerly,
has bestowed much labour on his vineyard.
Let none say in their own carnal reasonings, this is a small thing,
and there is little in the other; for he calls for the whole heart,
and the denial of everything that is made manifest by the light
of Christ to be reprovable and displeasing to God.

So that how small and trivial soever those liberties which many take in deportment,
speech, and dress, may appear to them, whilst they have health and strength,
and the appearance of a long continuance in this world,
we shall find by examples in this and the foregoing volumes,
that they were matters of great weight when the trying time came,
and no doubt will be so to all who are truly sensible of the day of their visitation,
that they may improve it,
and are under a concern for the well-being of their never-dying souls.
That these things may be duly considered in time,
and that all may be prepared whensoever it may please the Lord to call us hence,
is the desire and prayer of one who wisheth health and salvation to all mankind.

John Bell.

"`But let patience have her perfect work, that ye may be perfect and entire,
wanting nothing.`" James 1:4.
