== Chapter 2

[.chapter-synopsis]
* Dorothy Trapnell
* John Williams
* Joseph Whalley
* John Haydock
* William and Blessing Fennel
* Thomas Wight
* Hannah Philips
* George Chalkley
* Thomas Busbey

DOROTHY TRAPNELL was born in Topsham, in Devonshire, the 24th of the Sixth month, 1630,
and with her mother Anne Morris,
was one of the first convinced of the blessed truth in that country, about the year 1654.
Her mother was concerned to bear testimony against
the hireling priest in the public worship house;
and gave up her own house for Friends to meet in during her life,
and ordered it to be continued after her decease.

She was a religious woman, of good repute among Friends and others,
being patient and merciful to people in distress,
which caused the loss of her to be lamented by those who knew her.
She would be often speaking of her death,
and made her will many years before her departure,
frequently saying she was not afraid to die; and though she grew ancient,
yet still retained her understanding.
She often advised those who were with her to fear God and love the truth,
telling them with tears,
how freely she could have laid down her life for truth`'s sake at her first convincement.
Some time before her decease, she said to her grandson, Peter Williams,
that she thought she should see him no more,
charging him to love and take care of his mother.
Some hours before her death, which she earnestly desired, she said she was dying,
and took her solemn leave of her relations, friends, and neighbors who were present,
kissing several of them, and praying God to bless them, and theirs.

Then she called for her daughter Williams, and asked if she had left her.
Her daughter came to her, and said she had not left her; and she,
holding her by the hand, earnestly desired the Lord to bless her and hers, and added,
"`I should have been glad to see your children:`" but they living some miles from her,
she expired before they came.
She finished her course and testimony, and laid down the body like a lamb,
without sigh or groan, the 14th day of the Twelfth month, 1715,
aged eighty-five years and almost six months,
and was buried the 19th in Friends`' burying-ground at Topsham,
and was the first laid in that ground.
She died much lamented, being a true Christian, a good friend,
an affectionate mother and grandmother, and a good neighbor;
leaving a good reputation behind her,
whose memory cannot be forgotten by those who were near and dear to her, and she to them.
Such was the respect shown to her memory by other people not of our profession,
as well as from Friends, that it was thought some thousands were at her funeral,
even more than the meetinghouse and burying-ground, though large, could contain; many,
not under our name, coming from the country without any invitation.

[.asterism]
'''

JOHN WILLIAMS, son-in-law to the forementioned Dorothy Trapnell,
was born in Topsham the 14th day of the First month, 1658,
and brought up in the way of the church of England.
When he was upwards of twenty years of age,
he married the daughter of the said Dorothy Trapnell,
then also in the way of the church of England,
where they continued until about the year 1687,
when they were both invited to a meeting where our
dear and worthy friend James Dickinson was.
Some time after he joined in profession with the people called Quakers,
with whom he continued to his end.
Being taken ill about the beginning of the Eighth month, 1717, when going up stairs,
he said to the maidservant, that he thought he should never more come down.
About two days after he said to his wife,
that it had been in his mind almost all the day before, to make his will,
and being taken ill in his head, he did not know whether his memory might continue.
On which his wife said to him, that he used to be low-spirited when sick;
he answered that he must do it; that was, to make his will.
Some hours after, he spoke to his nurse, and a kinswoman who came to visit him,
to the same effect, saying, that his wife was not willing.
Whereon his kinswoman said, she would send a person to do it.
When it was done and signed, he said to his son Peter, "`This is my mind,
and if you love your mother, and be dutiful to her, you may reap the benefit of it.`"

He grew worse and worse, whatever means were used, often speaking of his death,
and saying he had rather die than live, except it were to honor the Lord.
After which he lay about eight hours speechless,
with many other symptoms of immediate death, but recovering out of that state,
he spoke at first like a child, and desired to see his wife and children once more,
which he expressed again on their coming to him; and desiring his wife to, kiss him,
he said, "`Farewell in the Lord.`"
She answering, said, "`In the Lord Jesus we shall fare well.`"
To which he added, "`Farewell in the Lord Jesus.
Do not stay by me to discompose my mind.`"
He called his little grandson, and holding him by the hand, said, "`Sammy,
I desire you may be a good man and fear God, and then God will bless you.`"
An ancient friend coming to visit him, he told him, that he had that night fought,
as it were, with beasts at Ephesus.
The friend said, he hoped he overcame; to which he cheerfully answered, "`Yes, yes,
there is strength enough in the Lord to overcome all.`"
He continued growing weaker and weaker, and on the 27th day of the Ninth month, 1717,
he departed this life, aged about fifty-eight years and nine months.

N+++.+++ B.--Some time after his decease our afore-mentioned friend, James Dickinson,
coming in truth`'s service into the west, came to visit his widow, and looking on her,
said,
he remembered when she and her husband came into the meeting of friends in their finery,
about thirty years before, he had said to old John Colsworthy and wife,
that the couple who came into the meeting would come to us.

[.asterism]
'''

JOSEPH WHALLEY was the son of Joseph Whalley, and Hannah his wife,
of Southfield in Lancashire.
About three or four months before this young man died,
being under some affliction of body, he often desired his mother to keep him company,
saying, "`Come, mother, keep me company, and let us wait a little together.`"
She at one time asked him, what he thought of himself as to his inward condition.
After a little pause, he answered and said,
"`I fear I have not been so careful at times as I ought to have been.
When I have had good meetings, and opportunities of profit,
I have been too apt to grow into forgetfulness again,
by joining with some of my companions in laughter and jesting.
But I hope if it please God to restore me to my former health again,
and lengthen out my day a little longer, I shall be more careful for the future,
for I believe that it is his will and pleasure thus to afflict me for my good,
that I may remember my ways.
I believe, if I had answered the end of my creation,
I should have been a plant to have glorified God in my day,
and I hope that I may in some measure answer it one way or other,
before he takes me out of the world.`"

On the 21st day of the Fourth month, he began to bleed at the nose,
and all the means used to stop it, by men of skill, proved ineffectual.
In about three days after the time it began, finding himself pretty far spent,
and seeing some of his friends and near relations, and particularly his mother,
in a great concern for him, he expressed himself after this manner,
"`I desire you to be easy: mother, I desire you to he easy and not to weep,
for I hope it will be well with me.`"
Then turning himself to the young people present, he said, "`You see that I am a dying man.
I desire you may take warning by me to remember your latter end,
seeing you know not how soon it may be your turn to be in this condition.`"
Then taking his brother by the hand, said, "`I desire you to be a good boy,
and be not stubborn, but be guided by your mother,
and then it will be well for you when you come to a dying hour,
which I am drawing towards, for you must come to me, if you be a good lad,
but I must not return to you; and this I leave with you as a charge,
fox I desire your welfare as for my own soul.`"

Then he wanted to see his cousin, William Fielden,
and showed a concern to speak to him by way of advice and warning.
But he not being in sight, he signified, that though he should warn,
and his warning be neglected, yet he should be clear,
and their blood would be upon their own heads; referring to Ezekiel the prophet; "`And,`"
said he, "`as for our friend John Ecroyd, if I die I would have him be easy,
for I am satisfied he has done his endeavor.`"
He also signified that he believed there had been endeavors used sufficient,
if the Lord saw fit to restore him to health again.
"`But,`" said he, "`when the Lord calls, who can withstand?`"
His father asked him whether he was easy as to himself,
and could be free to die and leave them.
He answered, "`I am easy in my mind, and have no disturbance,
which is to me a sign that an inheritance is provided for me.`"
A neighbor being present, replied, "`It is so.`"
His father asking further,
whether he had any thing upon his mind to say to him; "`I have nothing,`" said he,
"`in commission, but that you walk answerable to the light which God has given you.
Remember my love to Friends,`" said he,
"`for my love is to all;`" and in particular he desired
his respects might be given to Thomas Anderson,
and requested that those present might stay with him,
until it might please the Lord to call him, "`That`" said he, "`they may see the end;
for I hope I shall be no bad example.`"

Then he desired to see some relations, and two public Friends belonging to the meeting,
who being sent for, one came, namely, James Topper, and when he saw him, he said,
"`You have done well to come to see me;`" the Friend answered,
"`I am sorry to see you thus;`" but he replied,
"`I hope you need not be sorry in one sense.`"
The other Friend, namely, Charles Harrison, being absent at a burial,
came not till near his end, and prayed by him.
A little before his departure, he desired that all the young people of the neighborhood,
and his relations, especially the youth, might be invited to his burial; "`For,`" said he,
"`may be it may prove an inducement to them, through me, to remember their latter end.`"
A little before he finished his race, a friend who sat near him thought she heard him,
with a low voice, say, "`Praises, praises;`" which were the last words he spoke,
and in a little time after he departed this life as if he had fallen asleep,
and it is to be hoped, in peace with the Lord, the 25th day of the Fourth month, 1724,
in the twentieth year of his age.

[.asterism]
'''

JOHN HAYDOCK.
I believe the faithful labors and services of that eminent servant of the church,
and ancient and living minister of Jesus Christ, John Haydock,
are yet within the memory of many now living,
who cannot forget that faithful labor of love in
the work of the gospel in which he was very diligent,
he traveling much in several parts of the world,
with whose service in the ministry the church was
often edified and comforted for about fifty years.
It may be truly said of him, he was an instrument in the Lord`'s hand,
gifted by him for watering his heritage,
and was very instrumental to help those who were under convincement,
and labored under great exercise of mind, who were laid hold on, and reached to,
by the visitation of the love of God,
and had the opportunity of sitting under his lively testimonies,
which were both teaching and baptizing.
Such indeed were thereby often greatly encouraged, refreshed, and comforted,
and stirred up in their minds,
so as still to look forward and trust in God who had so graciously visited them,
being witnesses that his ministry tended to the building up in
the most holy faith in our Lord and Savior Jesus Christ,
which gives victory over sin.

His great humility, and pious and godly walking,
adorned the doctrine of the gospel of Christ,
so that by his example he recommended that which he was called
to preach in the power and demonstration of the spirit,
and showed forth the good effects of true religion,
which he labored faithfully for many years to promote among mankind.
Finding nothing in the foregoing parts of the Dying Sayings of Friends, concerning him,
nor anything made public of his labors and travels in the work of the gospel,
and concluding that there are yet remaining some who are as seals of his ministry,
for the reviving of the memory of the just, as he deserves to be accounted,
I have inserted the testimony of Hardshaw Monthly meeting concerning him;
in which place he was many years a serviceable member, which is as follows.

[.signed-section-signature]
J+++.+++ B.

[.embedded-content-document.testimony]
--

[.blurb]
=== A short Testimony concerning our dear and ancient friend John Haydock.

We could not stand acquitted before God or men,
to have buried the corpse of this our worthy friend with a few short sighs,
and so let his name go with him to the grave.
We have raised no monument over his sepulcher, but there is one due to his worth.
His life was of sweet savor, seasoned with the salt of the covenant,
and ought not to go under foot.
He was born of reputable parents in the parish of Standish, in Lancashire,
in the Twelfth month, 1640, by whom he was strictly educated in their religion,
whose principles he held till about the year 1667,
when it pleased the Lord to visit him with his glorious day-spring from on high,
whereby his understanding became enlarged, and his heart opened,
to believe and receive the truth as it is in Jesus.
And for his testimony to it he was, in a few months after,
committed prisoner to Lancaster jail,
where he patiently suffered imprisonment about four months, before he was released.

A year after his commitment, he was called into the ministry of the gospel,
in which service, being endowed with the spirit of wisdom and power,
he was eminently laborious and useful.
He travelled much on truth`'s account, not only in England and Scotland,
but several times visited the nation of Ireland.
He also went over to America,
and visited most of the provinces and islands there from
all which places we have had good accounts of his service,
and there were many convinced who became seals of his ministry.
His doctrine was sweet and heavenly, relishing of the Fountain which it came;
often deep in the mystery not to be comprehended by the world,
but seemed rather matter for the children of light and circumcision,
from whom the veil of the covering is taken away.
He was, from its beginning, a member of this our meeting of discipline,
and through the blessing of God very helpful to us to establish good order,
both by example and precept; for God had given him a profound judgment.
He was a man who suffered much persecution for righteousness sake,
both of tongues and hands, and went through bad reports as well as good;
was rendered as a deceiver, and yet true.
Because he would not swear, he suffered the loss of much of his worldly substance,
and was often imprisoned; all which he bore with invincible patience,
till in death itself he became victor, and is gone to his prepared mansion,
where the wicked cease from troubling, and the rest is made perfect.
He died in Lancaster jail, for his testimony to the truth,
upon the 19th day of the Tenth month, after a week`'s sickness,
and was carried from there to his own house at Coppul,
and was buried in Friends`' burying-ground in Langtree, the 22nd of the same month, 1719,
aged about seventy-nine years, and a minister about fifty years.

--

[.asterism]
'''

[.blurb]
=== WILLIAM AND BLESSING FENNEL. Some account, by way of testimony, from the men and women`'s meeting in Youghall, in Ireland, concerning our dear friends deceased, William Fennel, and Blessing his wife.

The said William was eldest son to John Fennel and Mary his wife, of Killcomonbeg,
in the county of Tipperary, who were early convinced of the blessed truth,
as professed by us, the people called Quakers,
and were serviceable in their time and place.

The said Blessing was the eldest daughter of Robert Sandham and Deborah his wife,
in Youghall,
of whose pious lives and deaths some account is given in the [.book-title]#Dying Sayings of Friends,#
already published.

They, the said William and Blessing, by the account we have had and what we knew of them,
were not only educated in the profession of truth,
but in their minority were sober and religiously inclined, and dutiful to their parents,
and as they grew in years, by and through the Lord`'s grace and good spirit,
grew in sobriety and virtue; their lives and conduct adorned their profession.
They took each other in marriage in the year 1688, and settled in Youghall,
where they became serviceable in several respects,
through the Lord`'s goodness and preserving power.
They were concerned according to the ability received in their place and station,
to maintain truth`'s testimony in the several branches thereof,
and were diligent attenders of meetings for the worship of God,
also those for good order and discipline in the church both at home and abroad,
as province and half-year`'s meetings, while they had ability of body.

They were as lights in that place,
whose house and hearts were open to entertain strangers and their friends cheerfully.
They lived in great love and unity together,
and trained up their children not only in plainness of speech and apparel,
but also in the nurture and admonition of the Lord,
and walked as good examples before them and others in godliness and honesty,
being just in their dealings, and careful and punctual to keep their word and promises,
keeping in moderation and temperance, loving and kind to friends and neighbors,
and affectionate to parents, and charitable to the poor, doing good to all,
but more especially to the household of faith) according to their ability.

The said William, in the time of his last illness, spoke many sensible expressions,
saying there lay nothing in his way that he knew of,
and desired to be dissolved and taken out of that frail tabernacle of clay.
He continued in a sweet, sensible and resigned frame of mind,
often praying to the Lord to bless his children, and to be a comfort to his dear wife;
and one day said to her, "`My dear,
the Lord has been very good to me from my childhood to this day many ways,
and in particular, in blessing me with a tender, loving, and faithful wife,
and dutiful children;`" and that the Lord`'s goodness continued to him in that last sickness;
with other expressions that were affecting to those present.
He departed this life the 13th day of the Seventh month, 1724, aged seventy-three years.

A few weeks after his death, the said Blessing, his widow,
in answer to a letter of a particular friend, T. W., of Cork,
gave the following account concerning her said husband, in these words:

[.embedded-content-document.letter]
--

Although I fully believe the Lord has taken my most dear and tender husband to himself,
yet his removal is my exceeding great loss,
he being a faithful fellow traveller with me in our spiritual journey towards Zion.
He was not a man that would speak so much as some others, but was sincere-hearted to God,
and tender of the honor of his truth,
bearing burdens often for peace-sake in this meeting, laboring to preserve unity,
and keep down a dividing spirit.
If I may be allowed, that best knew him the last half of his years,
to give his character in a few words.
He was a faithful man, fearing God, and hating covetousness,
doing nothing through strife and vain glory, but in lowliness of mind,
esteeming others better than himself.

--

The said Blessing lived about ten years after the death of her husband,
and continued a serviceable woman in her place, being a mother in our Israel,
a teacher of good things, her words being seasoned with grace,
often telling her children the Lord`'s merciful and tender dealings,
and preservations to her and hers all her life long.
Some years before she died, she appeared in a public testimony in this meeting,
telling what God had done for her soul, in a lively manner;
and had a zealous concern to stir up friends to watchfulness
and circumspection in their conduct,
and to do nothing against the truth, but for it.

She was under much weakness and infirmity of body for some time before her last sickness,
yet preserved in a sweet, resigned, and tender frame of spirit to the last,
and often gave good advice to her children, telling them of God`'s goodness to her soul.
Her last illness was short, and being weak before,
did not say much to her children or those about her at that time,
save that to her eldest daughter and her husband, the day before she died,
she said she was glad to see them once more,
and desired the Lord might bless and preserve them in his truth.
Being weak, she could not say much,
but desired her children might live in the fear of God,
and mind the advice she had often given them.
She departed this life the 4th day of the Third month, 1735,
in the seventy-fourth year of her age,
and we doubt not but she is entered into that rest
God has prepared for all who love and fear him.
Given forth by order and on behalf of our said meeting, the 8th day of the Twelfth month,
1735.

[.asterism]
'''

THOMAS WIGHT, of Cork, in Ireland, was taken ill the 13th day of the Ninth month, 1724,
with a cold and a stitch, which continued, though not violent, about three weeks,
part of which time he seemed to amend so as to get downstairs,
and settle his outward affairs.
After which, finding himself growing weaker gradually, he took to his chamber,
and on the day whereon the men`'s meeting was held, though very weak,
he looked into the meeting-books, and in a solid manner spoke to his son Joshua, saying,
"`There will be need of some Friend to write,
or be clerk for Friends about truth`'s affairs.
There are such and such that are qualified, it is too much for one.
Indeed, I have written a great deal in my time, and I have thought many times,
if I had not been divinely supported and borne up under it,
I should have fainted long ago.
When I began first I was but feeble, but the concern grew upon me,
and I took it with alacrity.
I own it took up my mind and thoughts so,
that I was as a stranger to the world and outward business,`" etc.

To his grandson, T. G., who came to take his leave of him,
being about to go over to London, he gave good advice and counsel,
particularly to regard truth, and admonished him to beware of hurtful conduct,
to keep out of superfluity and the vain fashions of the world,
and not to strike hands or join with such as took an undue liberty in various respects;
adding, "`Shun not the cross, but love it,
and be not ashamed of it;`" with more to the same effect.
Several friends came to visit him, to whom he showed much cheerfulness,
and expressed his resignation to the will of God.
The latter end of the month, being the Province meeting, he apparently grew weaker,
and several friends out of the country, and also of the city, came to visit him,
to whom he expressed, in great tenderness of spirit,
the goodness of God to him under his bodily weakness,
and that it was well for him he had not at that time the work of salvation to do,
but that he had the evidence of its being sealed to him.

Afterwards he sent for his grandchildren, to whom, in great brokenness,
he gave tender advice and counsel, to fear the Lord and be dutiful to their parents,
and in much plainness cautioned them to beware of
the vain fashions and hurtful conduct of the world;
and expressed with sorrow and mourning,
that there was too much height and grandeur got into, and lived in,
in many Friends`' families.
When he had spoken and cleared his mind to his children and grandchildren,
he took leave of them, and desired to be kept quiet and still, and so lay for some time;
as if he were near expiring, but he revived.
And understanding that several Friends were still in town,
and not gone home from the Province meeting, he said,
"`I have continued longer than I expected,
and I believe they have stayed longer in town on my account.`"
He desired some of them, particularly named,
might be told that he would willingly have one opportunity more with them; who,
being acquainted with it, readily came, the 4th day of the Tenth month,
and had a seasonable time with him,
first in a solid and silent waiting upon the Lord together by his bedside,
and afterwards in some serious conversation, and concluded in prayer and supplication,
to their mutual comfort and satisfaction.
After which, he said, "`Friends, we read that Jacob said, the Lord was in this place,
and I knew it not; but we can say, the Lord is here, and we know it,
or are sensible of it, glory to his name forever.`"
Growing gradually weaker, he lay in a sweet, tender frame of mind,
and so continued to the 9th of the Tenth month, 1724, on which day he died,
in the eighty-fourth year of his age.

[quote.scripture, , Psa. 37:37]
____
Mark the perfect man, and behold the upright, for the end of that man is peace.
____

[.asterism]
'''

HANNAH PHILIPS, late wife of John Philips,
of the city of Limerick and province of Munster, in Ireland,
was a woman of an exemplary life and innocent conduct, of few words, and a retired mind,
having a due regard to the gift of God in her own heart,
whereby she became a prepared vessel for the Lord`'s use.
For some time before her death,
the Lord was pleased to concern her in bearing a
testimony for his name and truth in public meetings,
to the comfort and edification of Friends.
Being often visited by them in the time of her illness,
though brought very low and weak of body, she was strong in the Lord,
and frequent in prayer and supplication to him.
She also uttered several pious and affecting expressions, saying at one time,
"`I am very weak in body,
but life is here;`" which was manifestly felt to the bowing of the hearts of many present.
At another time, some friends being in the chamber waiting upon the Lord, she said,
"`The Lord is good to Israel, but more especially to the upright in heart.
I have labored that my heart might be so before him.`"
And so went on in great sweetness, praising the Lord for his goodness towards her,
which was largely manifested at that time.

About a day or two before she died, several friends being present, she said,
"`My dear friends, my love is with you, but I cannot now say much, by reason of weakness;
but I desire the Lord may be with you, and prepare you for such a time as this.`"
She was also tenderly concerned in prayer for her family and offspring;
and so continued in much sweetness of spirit to the very last, departing in great peace,
and full assurance of eternal rest, the 14th day of the Eleventh month,
and was buried in Friends`' burying-ground, the 17th of the same,
aged about forty-four years, and a minister nearly two years.

[.asterism]
'''

GEORGE CHALKLEY, the elder, was born of religious parents at Kempton, near Hitchin,
in Hertfordshire.
His father`'s name was Thomas Chalkley, by trade a meal-man.
They were by profession of the Church of England, and zealous in their way.
They had four sons and three daughters; he, being the third son,
was convinced very young, at a meeting by the Chase Side, near Winchinore-hill,
through the powerful ministry of William Brend,
an eminent instrument in the Lord`'s hand in that day, who,
as he sometimes publicly declared, was opened in the words of the preacher,
Ecc. 11:9, "`Rejoice, O young man, in your youth,
and let your heart cheer you in the days of your youth,
and walk in the ways of your heart, and in the sight of your eyes;
but know that for all these things God will bring you into judgment.`"
Upon this subject the Friend spoke so home to his state and condition,
that he was convinced, and two others of his companions reached,
with whom he was walking in the fields, having religious conversation together,
being providentially directed to the meeting by observing some Friends going,
whom they followed there.
One of his two companions was Samuel Hodges, who lived and died a faithful Friend,
at whose house in succeeding time a meeting was settled,
and is there continued at Mims to this day.

George was the first of the family who received the truth,
after which his father and mother were convinced,
and the rest of his brothers and sisters, who lived and died honest Friends,
except the eldest, who was a sober man,
and continued of the persuasion of the Church of England, and died young.
It was not long after their convincement,
when he and his two companions aforesaid met with a trial of their faith and patience;
for, being taken at a meeting together,
they were all three committed to New-prison in Whitechapel,
where having continued prisoners some time,
the magistrates observing their Christian courage and innocency,
and being touched with tenderness toward them, considering their youth, discharged them.

About the twenty-fifth year of his age he married Rebecca Harding,
the widow of Nathaniel Harding, a friend who died under the sentence of banishment.
He met with great disappointments in his early days,
but through the Lord`'s goodness was preserved through, and over them all.
He was, though low in the world, an eminent example of patience and resignation;
and industriously labored with his hands for the support of his
family and conscientious discharge of all his engagements,
so that it may be justly said of him,
that he was careful to owe to no man anything but love.
He was very exemplary in keeping constant to meetings, though in times of hot persecution.
For when friends were persecuted on account of keeping up their religious meetings,
about the year 1680 to 1684, he constantly attended meetings, and never missed,
as far as can be remembered, on the First-days, unless hindered by sickness.
Though he was sometimes concerned to speak a few words by way of exhortation to friends,
when they were kept out of their meetinghouses in the streets,
to stand faithful to the truth,
and to testify of the solid comfort and satisfaction
that those who truly waited on the Lord enjoyed,
notwithstanding their deep sufferings;
yet it pleased the Lord by his good providence so to preserve him,
that he did not suffer imprisonment, though the informers were busy,
in that time of persecution.

When he was about sixty years of age,
he had a concern on his mind to visit friends and meetings in the north of England,
and other parts of the nation;,
and in the seventy-fifth year of his age travelled to Chester,
and from there went over into Ireland, in company with James Bates,
a friend of the ministry from Virginia, in the service of truth: in.
all which places he had good service and satisfaction, and was well received of friends.
In his old age he was attended with very great exercises and weakness by lameness;
yet his activity was remarkable, for he would so far exert his strength,
as often to reach as far as Devonshire-house, and Bull and Mouth meetings,
and sometimes to the workhouse meeting, from Southwark, where he lived;
but his weakness increasing, and he was taken with a violent pain in his side,
which when his cough took him, with which he was often troubled, was very great.
His illness after increased to that degree that it brought him very low.

He continued all the time of his illness in a patient and resigned frame.
On First-day in the afternoon he took to his bed,
and that evening being the 6th day of the First month, after the meeting at Horslydown,
the day before his death, several friends came to visit him, who finding him very weak,
after a little stay, went to take their leave of him.
He desired them to sit down, and after some time of silence,
he broke forth in an intelligible and lively manner to this effect:
"`We have no continuing city here, but seek one to come which has foundations,
whose builder and maker is God.
Friends, may we all labor to be prepared for our last and great change,
that when this earthly tabernacle shall be dissolved,
we may have a habitation with the Lord, a building not made with hands,
eternal in the heavens.
And that it may be thus, the Lord has showed you, O man, what is good, to do justly,
love mercy, and walk humbly with your God.
I do not expect but this will be the last night I shall have in this world,
and desire it may be remembered as the words of a dying man;
that we may labor to be clothed upon with our house that is from heaven;
so that when that hour comes, we may have nothing to do but die.`"

About one or two in the morning the Second-day following, he began to change,
and desired to see his son George,
who with his son-in-law Samuel Thornton coming to see him, found him very low;
and he expecting his end quickly to approach, said he was waiting for his change.
They sitting by his bedside with the nurse, his housekeeper and man,
about the fourth hour in the morning, he prayed fervently after this manner: "`Lord,
now let your servant depart in peace, for my eyes have seen your salvation,
which you have prepared before the face of all people, a light to lighten the Gentiles,
and the glory of your people Israel. And now, Lord, be with your people and servants,
and preserve my near and dear relations and acquaintance,
and keep them from the snares and temptations of the enemy, in your truth,
that they may fear your great name.`"
After a little time of silence,
he desired his son George to remember his dear love in Christ Jesus to his dear brother,
and all friends; "`My old friends,`" said he, "`and acquaintance.`"

About the eleventh hour in the morning, he inquired how the tide was,
which nobody then present could exactly tell.
Some time after he asked again; his man then went out to see,
and told him it would be high water about three in the afternoon.
He then lay still a while as if considering, and spoke cheerfully out aloud,
so that all in the room might hear, "`I shall go off about five.`"
His man asked him, "`Master, how do know?`"
to which he answered, "`Know; I do not know, but I believe it.`"
The apothecary coming to see him, ordered him a comfortable drink,
which he drank willingly, and then said, "`I do not think to drink any more in this world,
but I hope I shall drink plentifully of the river of life.`"
Then drawing on near his end, having ordered a cord to be fastened,
by which he raised himself up as long as he had any strength left in his hands;
and when his hands failed him, and his shoulders and head,
with which he at last raised himself, he spoke very low, and faltered,
yet so as he could be understood, "`Now I am going.`"
And about an hour after, lying all that while still, without either sigh, groan or sob,
departed this life as in a slumber, in sweet peace, just as the clock went five,
as he had foretold; who as he lived, so he died like a lamb;
on the 7th day of the First month, 1725, in the eighty-fourth year of his age,
leaving the succeeding generation a good example.

On the Sixth-day following, being the 11th day of the same month,
the time appointed for his funeral, his body was accompanied by his relations,
who were many, from his own house, to Friends`' meetinghouse at Horslydown,
where was a very large company of friends and neighbors,
among whom he was well beloved,
and several living testimonies were borne to the innocent and exemplary
life and honest zeal of this our deceased friend.
His corpse was accompanied from there to the grave at Friends`' burial-ground in Bermondsey,
Southwark, and there interred with a farther testimony to his exemplary life and conduct,
and services for that holy truth he made profession of.

[.asterism]
'''

THOMAS BUSBEY, of Banbury, in Oxfordshire,
was one whom the Lord endued with the knowledge of the truth in his youthful days,
to which, through the operation of his holy spirit,
he was made willing to give up in faithful obedience.
In the time of his last illness,
through the renewed visitations and fresh influences of divine love,
he dropped many precious and comfortable expressions.

In a short time his distemper increased so upon him as to confine him to the house.
On a First-day some Friends came to visit him,
and sitting together in a weighty frame of mind, he said,
"`If it please the Lord to take me away by this illness, I am not afraid to die,
blessed be the name of the Lord my God, whom I have loved and served from my young years,
and now in this low condition he has not forsaken me.
All glory and honor be given to him, and the dear Lamb that sits with him on the throne,
world without end.
Though I have near and dear things to leave behind me, as wife and children,
to whom I would have been as a shepherd a little longer, if the Lord had seen fit,
but his will be done.
I shall leave and commit them to him,
who has been as a tender father to me from the time
that he first visited my soul unto this day:
oh! what shall I say of his goodness and matchless love.`"

At another time, to a friend that came to visit him,
after having spoken a great deal of the love and
goodness of the Lord to him in the time of his youth,
in turning his feet from the paths of vanity into
the narrow way that leads to eternal rest,
he said, "`Oh! that our young friends, who are growing up,
would come to seek the Lord in their early years.
He would be assuredly found of them; my soul is a witness of what I now speak.
When I was but a lad, I had secret desires after him,
insomuch that I thought I could be content to mourn out my days in a cave of the earth,
so that I might have an assurance of a dwelling with him,
when time here should be no more.
So strong were the desires that the Lord had raised in me,
that nothing short of this would satisfy, which caused me many times, I might say years,
to go mourning and seeking the Lord,
till at length he was pleased to appear by his in-speaking
word in the secret of my heart,
saying, You are mine, wait on me and I will protect you.
Oh! how has he made good his promise; yes, he has done more for me,
both inwardly and outwardly, than at any time ever entered my heart to desire or expect;
the which causes adoration and praises to ascend from me,
who am but as a worm before him.`"

At another time, he being as it were overcome by the love of God,
and in a tender frame of mind, said, "`One taste
of my Father`'s love is better than all the doctor`'s cordials.
Oh! it is this that supports my drooping spirits.
I thank you, O Father, that you have not forgotten me in this low condition.`"
One time speaking to some young friends that came to see him,
some of his expressions were these: "`Keep in the narrow way spoken of by our Savior,
Christ, in whatsoever company you may be.
Keep to an inward exercise of mind, and to the teaching of the Holy Spirit in yourselves,
that you may be thereby prepared,
and ready for whatsoever work and service the Lord may be pleased to call you to;
for he works in whom he pleases, and how he pleases.
Time will fail, and strength will fail; therefore improve your time,
and prepare yourselves while you have time.
My dear friends, my love is to you, and remember my love to friends,
for I shall depart hence before it be long.
Blessed be the Lord, I am strengthened in spirit beyond what I expected.`"
Some Friends of Ireland, in their journey to the yearly meeting at London,
gave him a visit, and the Lord was pleased to favor them,
a little before they took leave of him,
with a degree of divine sweetness and harmony upon their spirits,
by which they were so reached and tendered,
that they declared their great comfort and satisfaction in their visit.

At another time, in sweet composure of mind, speaking to his wife, he said, "`Oh! my dear,
what manner of love is this, wherewith the Lord has loved my soul, that I am, as it were,
overcome therewith, so that I am ready to shout aloud for joy,
and to go beyond my strength,
for I see no end of praising him for his many mercies and visitations of love?
Surely it is as a brook by the way, to confirm my faith and hope in him,
which is as an anchor sure and steadfast,
that all tempests and contrary winds have never been able to shake or overturn,
because it was built upon the invincible rock,
the rock of ages and foundation of all the righteous.
My soul shall sing eternal praises unto it,
because I have tasted of the streams that issue therefrom,
at this time as well as at many other times.
Glory be to God and the Lamb forever and forevermore.`"
Speaking of that power whereby the soul is renewed and made alive to God; "`Oh!`" said he,
"`that we may all keep to it,
it is this which will give us the victory over the
many things that would draw away our minds from him,
and from a faithful dependence upon him.
My soul is a witness for the pure God, that if we keep to the power, in that,
we are made more than conquerors by him who has loved us,
and shed his most precious blood for us.
Though I am weak, and my outward man decays, yet my faith and hope are renewed in him,
so that I know whose I am, and whom I serve,
and nothing shall be able to pluck me out of his hands,
for it is by this power I have been upheld to this day.
Though the archers shot at me, my bow abode in strength,
so that with the patriarch I can say,
the arms of my hands have been made strong by the hands of the mighty God of Jacob,
who has preserved me; endless glory be given to him.`"

The 25th day of the Seventh month, 1726, a friend,
who lived at some distance came to see him, and asking him how he was, he answered,
"`All is well, except the poor body, and that is sorely afflicted,
but the Lord has graciously supported me under it, beyond expectation.`"
After having been a little in silence, he broke forth into prayer,
and returned praises to the Lord for his wonderful lovingkindness,
in affording him his comforting presence in a time of great exercises,
and his strengthening power and supporting arm under such
great pains and long and sore afflictions of body,
with which he was attended.

The 27th of the aforesaid month, some friends who had tarried all night,
in the morning asked him how he was.
He answered, "`I was in hopes I was going once tonight;`" (for he had had a very ill fit,
in which they who were with him thought he was departing.) "`I am very desirous
to be released from this great affliction of body I am under,
if it please the Lord; but his will be done.`"
About two hours after, the said friends being about to take their leave of him, he,
though very weak, being then near his end, raised himself up in the bed,
strengthening him beyond expectation,
and in the aboundings of divine goodness supplicated the Lord to this effect:
that the Lord would be pleased to strengthen and uphold all the weak,
and comfort all the afflicted, whether in body or mind; and that the Lord,
according to his heavenly will, and divine wisdom,
would raise up a powerful and living ministry of the young people among friends;
and that he would graciously vouchsafe of his favor to his people,
to endue the present ministry with a larger demonstration of the spirit,
so that nothing might appear among them but the pure streams and current of life;
that those who were lately convinced, belonging to Eadon meeting, might be preserved,
and attain to an establishment in the truth, and persevere to the end;
and that the youth among us in general,
might be favored with a fresh visitation of the love of God,
to draw their affections from the pleasures and vain fashions of the world,
to an earnest seeking of the Lord,
and thereby to a possession and enjoyment in themselves
of the power and excellency of truth,
which will afford them comfort in a time of trouble and afflictions,
and strength under exercises and weakness, and peace in an hour when all the world,
and the glory thereof, will stand them in no stead.

Towards his end, being weak in bed, a friend came to visit him,
and speaking of the state of things,
and the liberty some of the professors of truth took to revile the innocent, he said,
"`Dear friend, be not discouraged.
Though there is darkness in Egypt, there is light in Goshen; yes,
it is such darkness as may be felt.
My soul has travailed under the weight of it many times; and though it is so,
and has been so, the Lord will have regard to his own seed.
He knows who they are, and where they are.
I could say a great deal, but am much spent,
having had a large morning sacrifice with some of my friends that are gone away today.
Oh! glory to God!
Do not distrust his goodness, he never fails those who have a true dependence upon him;
my soul is a living witness of it.`"
And farther said, "`Although I have been under so long and sore affliction of body,
yet the enemy has never been allowed to tempt me to despair,
or doubt of my future happiness.`"

He left it as a charge with his family, that nothing of mourning apparel,
or anything that had the least appearance thereof,
might be worn on the account of him after his decease.
Many more excellent sayings which he delivered, worthy of memorial,
might have been here inserted for the benefit and encouragement of others,
to follow the ways of piety and virtue,
had it been possible to retain them exactly in mind.
He departed this life the 13th day of the Eighth month, 1726, aged about sixty years,
and was buried in Friends`' burying-ground at Eadon, in Northamptonshire,
the 19th of the same month;
and his funeral was attended by a large company of friends and neighbors.
