== Chapter 3

[.chapter-synopsis]
* Joshua Brook
* Rebecca Jacob
* Frances Griffitts
* Jeremiah Waring
* Ellen Bewley
* Mary Bewley
* Alexander Hopwood
* Sarah Marriott
* Margaret Ellis

JOSHUA BROOK, son of Richard Brook, and Martha, his wife, of Raw, near Huddersfield,
in Yorkshire, was born the 17th day of the Twelfth month, 1701,
and educated in the way of truth, as professed by the people called Quakers.
He was inclinable to learning from his childhood, and as he grew to riper years,
he pursued it with more diligence.
When others, equal with him in age, were spending their time in vanity and play,
he would often be writing, or reading the Holy Scriptures, and some other books,
in which he much delighted;
which was a means of preserving him from the many foolish
and hurtful vanities youth are too much inclined to.

But afterwards, falling into the company of some who pretended to great learning,
he was led to be a great admirer of it, so that his mind was too much taken up with it,
and diverted from a due regard to that inward principle of light and grace in himself.
Afterwards, the manifestation of that divine light shining clearly in his heart,
showed him his neglect of minding that inward teacher;
and then he came to see he must begin to learn anew,
and was brought under great exercise and inward trouble,
insomuch that he was scarcely fit for conversation, but very much desired to be alone.
The company of those who had been his companions became unpleasant to him;
and continuing in a strict course of life,
he was very zealous and diligent in going to meetings, and much retired in them.
His care was such, not to neglect that great duty of the public worship of God,
that long after his infirmity came upon him, which was lameness,
and continued to his end, he would go with his staff and crutch to meetings,
though obliged to rest by the way.
When his infirmity increased upon him that he was not able to walk,
he would ride to meetings as long as he had strength of body to bear it;
but growing weak, he was obliged to stay at home, and in process of time to keep his bed,
when many lively and heavenly expressions dropped from him.

After a long and sore affliction for about four years with his lameness,
which began first on his knee and broke on his leg, and afterwards in his thigh,
a dropsy came on, which proved mortal.
It began about seven months before his end, and grew gradually until he was very big,
and could not lie down in his bed, but sat up in it,
not being able to turn himself without assistance for about seven weeks before his departure.
And although in the time of his long illness his affliction was great and hard to bear,
yet it was much overbalanced by that heavenly love
and inward refreshment which he was favored with.
His patient conduct and the many seasonable expressions
that dropped from him under this heavy exercise,
had great influence,
and were very affecting to all ranks of people that came to visit him, which were many.
How lively he was in his spirit,
and innocent and sweet in his conversation while on his deathbed,
it is to be hoped will not be forgotten by those that visited him.

He often gave good advice to the youth, saying,
'`Though you are young and in the flower of your age, yet think not yourselves secure.
You may see a pregnant example in me,
who was once of as healthful a constitution as most of you.
How soon that overruling hand may bring you into the same condition, you know not.`'
Warning them to give all diligence to make their calling and election sure,
that when pale death looked them in the face, they might not be surprised,
but being fitly prepared, embrace it with rejoicing.

One First-day morning, before the meeting, which was held at his father`'s house that day,
his brother went to see him, and perceiving him dejected in mind,
asked him if he was not under some exercise;`'Yes, '`said he,
'`The Lord is withdrawn from me,
so that I do not feel that comfort and satisfaction as heretofore.`'
His brother replied to this effect: '`Be not discouraged, the Lord is a merciful God,
he may try, but will not leave any that put their trust in him.`'
After the meeting was over many friends went to his bedside,
and several lively and powerful expressions were uttered by him,
with which many were reached, and some young friends, his companions,
were tenderly affected.
His brother going to him, he said, '`The Lord is come again.
I have had a sore day of exercise, with most part of last night,
but now the Lord is returned again, for which I bless his holy name.`'

Some young friends tarried with him that night, thinking him near his conclusion,
having had a sore fit the night before, and his surviving it not being expected,
of which he had a return the night following.
When he felt it come on he beckoned to each of them, and they coming near,
he took them by the hand one by one and kissed them; taking his solemn leave of them.
They remained by his bed side expecting his departure;
but after some time he recovered out of that fainting fit, and looking up,
said with great reverence and sedateness of mind,
'`I thought I had been near the port of eternal rest,
and would gladly have remained there, but I see my time is prolonged,
and for a while I must return again into this troublesome world;
but God will deliver me from all my exercises, blessed be his eternal name:`'
with much more to the same effect.
At another time, one of his familiar friends coming to visit him, asked him how he did;
he answered in much brokenness of spirit,
'`The Lord will in his appointed time cure me of all my maladies,
blessed be his holy name;`' with many more pious expressions to those who visited him.
At another time he said, '`The Lord has plucked my feet out of the mire and clay,
and set them upon a rock.
The Lord has delivered my soul from all unrighteousness;
there is no obstruction in my way.
Death is no terror to me; it is the most pleasant thing that ever my eyes beheld.
I would not, if I might have my health again, remain here.`'
Sometimes saying '`I see to the end of mortality, but I cannot come at it yet.`'

Henry Jackson, a Friend who had a great respect for him in the time of his health,
and often visited him in his sickness, to their comfort and inward refreshment,
the last time he came, a few days before his end, prayed by him;
after which he said in much tenderness to this effect, '`My work is almost done;
I am going to the patriarchs, prophets, and apostles,
to sing hallelujahs and praises forever and evermore.`'
Henry said, as he was coming to visit him,
it seemed to him as though the holy angels of God were waiting to receive
the word of command to conduct his soul into the mansions of glory,
and that he would have wished himself in his condition; to which he answered,
'`It will not be long before we shall meet again;`'
which took such impression on Henry`'s mind,
that soon after he told a friend, he believed it would come to pass,
for he thought his days in the world would not be many.
And about fourteen weeks after, Henry also finished his course.

His distemper growing more violent, he weakened fast; but as his outward man decayed,
his inward comfort increased,
and waiting in patience and resignation to the will of God for
the word of command from the great Disposer of all things,
in a full assurance of his soul`'s salvation, saying he should go to his everlasting rest,
to sing praises forever and evermore.
He departed this life the 13th day of the Seventh month, 1727,
in the twenty-sixth year of his age, and, it is not to be`' doubted,
is arrived where the wicked cease from troubling, and the weary are at rest.

His funeral was attended by a large number of Friends and sober neighbors;
and the aforesaid Henry Jackson being present, bore testimony to the truth,
and repeated several pious expressions which dropped from him on his dying-bed,
with which many were much affected.

[.asterism]
'''

REBECCA JACOB, wife of Isaac Jacob, of Waterford, in Ireland,
daughter of William Penrose and Margaret his wife, of the same city,
was from her childhood of a meek and innocent behavior, and as she advanced in years,
witnessed a growth in the blessed truth,
often being favored in religious retirements with the Lord`'s tendering goodness,
whereby she was strengthened in faith to walk humbly before him.
She was an affectionate and tender friend, companion, and wife.

It pleased the Lord to visit her with a lingering
sickness about two months before her end,
in which time she was not known to repine,
but with cheerfulness of mind yielded to that affliction and weakness of body,
which increasing and her end drawing near,
she asked her mother-in-law if she thought her near departing; who replied,
she thought she was.
Then she desired to wait on the Lord, and, after some time, said,
'`I have a good and loving husband, a good mother-in-law, and lack nothing,
and never repented my coming into the family.
We have what the world can afford, but now the Lord is more to me than all.
I have had many good times alone, when no eye saw me;`' and soon after said,
'`Oh! you great Preserver of men, you have comforted my soul when alone,
and preserved me from evil,
and now I feel your good presence near me;`' then fervently
prayed to the Lord not to forsake her in the needful time,
saying, '`Oh! you holy One, be near me still.`'

She remembered her dear love to friends, and those who might enquire after her,
and calling for her brothers, tenderly advised them to fear God,
and to be dutiful to their parents, and not to grieve them.
Then prayed to the Lord for her husband, saying, '`Oh! you great Preserver of men,
bless and preserve him, I beseech you, in all his ways, in his goings out,
and in his comings in, and in all that he does, or takes in hand to do.`'
Desiring her mother to keep near her to the last, said to her,
'`The comfort of the Lord is more to me than all the world,
and that which grieves me most, is to part with my dear husband.`'
She continued to praise and supplicate the Lord,
entreating him to be near her in the needful time, meaning her passage hence,
and said she was afraid the Lord would be angry if she praised him not.
Then taking her leave of her relations and friends present,
was not heard to speak much after; only once said, '`Oh! you God of my father!
Oh! you holy One, be near me still.`'
Her speech failing from the twelfth hour till half after nine at night,
it then pleased God to put a period to her being here,
and no doubt He has taken her into his glorious rest.

She died the 3rd day of the Second month, 1728.
And the 6th day of the same,
her corpse was attended by friends and friendly neighbors to the meetinghouse,
where several testimonies were borne to the truth,
and was afterwards carried to Friends`' burying-ground and decently interred:
aged twenty-five years seven weeks, and three days.

[.asterism]
'''

FRANCES GRIFFITTS was born at Baltimore, in the county of Cork, in Ireland,
in the year 1656.
She came to`' Cork when she was very young,
where she was convinced of God`'s everlasting truth,
about the twenty-fourth year of her age,
and as she became obedient to the manifestations and dictates thereof, she grew in grace,
and in the saving knowledge of it.
About the thirty-seventh year of her age she received a gift in the ministry,
in great humility, fear, and tenderness,
wherein she was all along very exemplary and careful
not to appear without the motion of divine life,
and a necessity upon her, so that what she delivered was edifying, seasonable,
and satisfactory to friends.
She travelled in some parts of England and Wales in the service of truth;
was a woman of great sincerity, plainness, and self-denial,
very exemplary to her children and family,
for whom being frequently concerned and engaged at heart,
that the Lord would be pleased to reach unto and visit them in mercy and love,
she was favored to see her desire in some degree answered.
She was zealously concerned for the promotion of truth and righteousness,
and was a sympathizer with the afflicted in body, or mind;
a frequent visitor of the sick, and industriously concerned for the relief of the poor.

She was taken ill the 4th day of the Seventh month, 1728, and continued so for some days;
during which she lay in a sweet composed frame of mind,
bearing her sickness with great patience and resignation to the will of God.
Some friends who came to see her, at their taking leave,
desired she might be restored to us, if it were the Lord`'s will.
She answered, it was time for her to look from the world,
and it would be safe for those who were younger than she,
to do nothing against the truth, but for the truth,
and that would administer peace to them in the end.
To a relation and his wife, that asked her how she did, she replied, weak in body,
but not in mind, and that she had nothing to do then but to die; adding,
'`It is a brave thing to be chaste; chaste in our love to God;
to leave nothing to do at such a time as this.`'
The same person desired she might be restored to us again; she answered,
'`There is little likelihood of it.
However, be it as the Lord will, I am ready.
It is no surprise to me; I have been long preparing for it.
The Lord has helped me to do it;`' adding, '`I have not much to say, being weak in body,
but this short sentence I leave with you, Do nothing against the truth,
but all that you can for the truth.`'
And when the aforesaid friends were taking leave of her, she, calling her by her name,
said, '`Be faithful to what is manifested to you.
The Lord has made known his will to you, and oh! be faithful to it,
and you will do well.`'

To a friend who lived in the neighborhood, visiting her,
she said there was a short sentence which was much in her mind,
and she had recommended it to several, '`To do nothing against,
but all that you can for the truth, '`the reward of which will be great peace in the end,
and that she now witnessed, which was more to her than all the world; adding,
'`You are a pretty knot of Friends in this neighborhood,
and I would have you to be preachers.
I do not mean in words or apparel only, but also in life and conduct.`'
To her daughter, Elizabeth Taylor, and another Friend, who were sitting by her, she said,
'`There is a short sentence which has lived in my mind most part of this night,
Have salt in yourselves,
and be at peace one with another;`' with many other sweet
and comfortable expressions which were not perfectly remembered,
signifying her inward peace and satisfaction.
She lived to a good old age, and was taken away, like a shock of corn fully ripe,
the 10th day of the Seventh month, 1728, in the seventy-second year of her age; and,
we are satisfied, died in the Lord,
and is entered into that rest prepared for the righteous.

[.asterism]
'''

JEREMIAH WARING, son of Henry Waring, was born at Hayly, in the parish of Witney,
and county of Oxford, in the year 1652.
While very young, he had the fear of God so impressed on his heart,
that he was led out of many childish vanities and diversions that others,
his equals and contemporaries, were in the practice of;
and by a sober conduct gave early indications of being under the
operation of that power which prepares for the service of God.
As his mind became more and more enlightened by the light of life,
he grew dissatisfied with various ceremonies, customs,
and usages of the church of England, into which he had been initiated.
Hence he was led, while an apprentice in London,
to seek carefully after a people whose doctrines were purely apostolic, and whose lives,
like the primitive Christians, were full of piety and good works.
After having, with a religious, seeking mind,
tried several other professions without finding among them the desired satisfaction,
his unwearied and commendable search after truth at length
led him to a meeting of the people called Quakers,
where the testimonies delivered that day, cooperating with the spirit of God in himself,
he embraced their doctrines with joy and gladness of heart,
and soon became thoroughly convinced of the blessed truth,
which broke in upon his understanding with demonstration and power,
and dispelled the many doubts,
fears and troubles that had heretofore surrounded his mind.

About two years after this, as we judge, being out of his apprenticeship,
he received a dispensation of the gospel to preach to others,
and though in the discharge of his duty he twice suffered imprisonment
in London with others of the then afflicted people of God,
yet he was no ways discouraged thereby, but, as soon as liberty was granted him,
continued visiting the meetings there and thereaway,
exhorting friends to be faithful to the discoveries
of his will which God had made in their souls,
and to stand immoveable for his name and truth on earth.

About the year 1681,
he visited the meetings that were settled near his native place in Oxfordshire,
where his testimony was well received, many having been lately convinced in those parts.
Among these was Mary, the daughter of Henry Wheeler, of Witney, a modest, discreet,
religious young woman, with whom he contracted an honorable intimacy,
and at length obtained her in marriage.

They settled first at Croydon, in Surry, and not long after removed to Ensham,
in Oxfordshire, and at last, about the year 1685, to Witney,
where the Lord was pleased to bless them with many temporal and spiritual blessings,
which enabled them to open their hearts and house to entertain friends,
and to contribute to the necessities of others in distress.
And as he was often engaged abroad in the discharge
of his duty to God and the churches round about,
the conduct and diligence of his wife in their temporal affairs,
rendered his absence very little inconvenient to his family and business.
Inspired with the hope of sharing in the reward of his labors, she spared no pains,
and grudged nothing she could do, to render the benefit thereof as diffusive as possible,
and her endeavors, she used to think, were blessed the more,
the more he was given up to the service of truth,
in which he was indeed an unwearied laborer,
even when old age and infirmity of body might have pleaded his excuse.

He was a minister of the New Testament,
and diligently labored according to the degree of the gift bestowed on him.
His ministry was plain and instructive, and according to the measure of it,
tended to convince the understandings of the ignorant,
to the reformation of those who obeyed not the gospel,
and to the confirming the feeble-minded, and the refreshment of the drooping soul.

For the weak and hindermost of the flock he had a tender regard,
that they might come forward;
and that those meetings might be visited to which no public friend belonged,
rather than too many to go to one meeting at the same time.
He would often say, he went not out at the invitation of others,
except to marriages and burials, but as he found drawings in his own mind,
which have at times engaged him to travel much in this nation,
but more especially in his own and adjacent counties.
He was generally well received, not only for this his labor in the ministry,
but also for his cheerful, free,
and easy behavior in the families where his lot was cast.

He was a zealous promoter of brotherly love and unity,
and where any difference had arisen in families,
would endeavor to reconcile the parties by visiting and treating
with them in a manner becoming a minister of the gospel of peace,
whose labor of love in this respect was generally well accepted,
and doubtless by some to their no small advantage.

His company was sought after by the sick and distressed,
to whom he had frequently a word of advice suitable to their state and condition.
His service in meetings of discipline was too considerable to be wholly omitted here,
or easily forgotten by those who knew it.
Being an elder in the church, he was concerned that the flock of God might be fed,
and took the oversight thereof; not by constraint, but willingly; not for filthy lucre,
but of a ready mind; not as a lord over God`'s heritage, but as an example to the flock.

About three months before his death,
it pleased God to remove hence his dear and loving wife,
after they had lived together above forty-six years,
of whose virtue it may not be amiss to give the following short account.

She was a kind and faithful wife, frugal and industrious, but not covetous.
A mother tenderly affectionate and evenhanded, shining in example; a neighbor peaceable,
obliging, and beneficent, of good report; and it may be said of her,
she was a mother in the church: having brought up children, lodged strangers,
relieved the afflicted, and was diligent in good works.

She departed this life in great peace, in unity with friends,
and in full assurance of an inheritance with the saints in light,
saying on her deathbed, she had done her day`'s work in the day time.
It were easy to enlarge on their virtues, both public and private,
but to avoid prolixity, I shall hasten to make some mention of his last illness,
which seized him the 14th of the Eleventh month, 1729-30,
being the morrow after his return from visiting Stow meeting, and continued about a week,
in which time having some intervals of ease,
he spoke many sweet and heavenly sentences to his children,
and those that came to see him,
among which the following few to his children are remembered.

'`Dear children, when your mother and I came together, it was in the fear of God.
We had but little of this world, yet we were content, and he made that little sufficient.
Our hearts were always open, and our house too, to receive friends,
and we never thought we had the less,
but on the contrary believed we were blessed the more;
for we experienced that saying verified,
They who seek the Lord shall not lack any good thing.
Oh! he is a good and a gracious God.
If you keep to truth and love him, he will never leave you nor forsake you.`'

His daughter speaking to him when he thought he had been alone, he said, '`Are you there?
I felt the love of God so strong upon my heart, I have been supplicating his name,
and I have freely offered up myself to his disposal, to do which way it pleases him.
He can bring down to the grave, and he can raise up again; his will be done.
I had once a desire, with submission, to have visited two or three meetings more,
observing in my last journeys how thin the elders everywhere appeared,
and how religion appeared to be at a low ebb.
Yet the principle of truth must prevail; for the Lord has promised,
he will give his Son the heathen for his inheritance,
and the uttermost parts of the earth for his possession.
And though we see but little of this yet, I shall die, as several elders have before me,
in the faith of it.
Abraham saw but little of that large promise made
to him of multiplying his seed as the stars of heaven,
and as the sand upon the sea shore.`'

Being asked how he did, he said, '`I had a comfortable time both in body and mind,
and have been looking back to my youth, reviewing the narrow way that leads to life;
remembering how our ancient friends used but few words,
and lived in love one with another.
And as it was in the beginning, so it must be again.
But now how many are there who love and take a delight in backbiting, detracting,
and exposing the failures of one another,
and their conversation too often turns upon modes and forms of dress,
things too mean for a true Christian spirit.`'

His children mentioning what a loss it would be to part with such dear and tender parents,
he said, '`We have lived to a good old age, and the Lord has never forsaken us,
and if you cleave to him, he will never depart from you.`'

'`And you, my grandchildren, I caution you against reading profane and idle books,
but read the holy Scriptures, and regard there the precious promises of Christ.`'
After having taken something, he said, '`This will not do.
This poor old house will not do, but I have a new house eternal in the heavens,
where is no pain, no sorrow; where all tears are wiped away.
No need of the light of the sun, nor of the moon to shine in it;
for the glory of God and the Lamb is the light thereof.`'

Mention being made of the Lord`'s rewarding him for his labor and service in the church,
he said, '`We are poor empty creatures, we can merit nothing.
All we have we receive from him, and all we do is but our reasonable duty.
The Lord has no need of us, for he is altogether glorious and happy in himself;
but we have need of him.`'

Another time, when he could take no rest, he said,
'`Sweet Lord! ease your servant for his sake, who loved me from my youth upward.`'

Recovering out of a violent fit of pain, he cried, O Lord,
your will be done! your will be done! your will be done!
You have been with me all my life long; oh! be with me now in these my dying moments,
and with my children and grandchildren, that so we may meet in your heavenly habitation,
where we shall never part more.
Oh! you Shepherd and Keeper of Israel, who neither slumbers nor sleeps,
into your everlasting arms of mercy do I commit them with my own soul.
I sought you in my tender years, and you were found of me,
and have been with me till this very day.
You have cast all my weaknesses behind your back,
where they shall never be remembered more;
and have many times given me a full assurance of
a resting place with you forever and ever.`'

He departed this life the 21st of the Eleventh month,
1729-30. And on the 24th of the same, his corpse,
accompanied by a great many friends from several parts of the county,
was decently interred at Friends`' burying-place in Witney,
after a meeting held on the occasion,
wherein the power and presence of the Almighty was eminently felt,
tendering the hearts of many,
and sealing upon their spirits that he is entered
into that rest which remains for the people of God,
which rest is glorious.
Aged seventy-seven, and a minister nearly fifty years.

[.asterism]
'''

ELLEN BEWLEY, wife of Daniel Bewley, of the city of Dublin, in Ireland,
and daughter of Joseph Inman and Elizabeth his wife, of the said city,
being religiously inclined from her childhood,
was concerned not only in meetings for the worship of Almighty God,
but also at other times, to wait to feel the incomes of that divine power,
which as it is given way to, cleanses the heart,
and nourishes up the soul unto life eternal.
She would often repeat that saying of our blessed Lord and Savior Jesus Christ, Matt. 22:12.
"`Friend, how came you in here, not having a wedding garment?`"
Showing thereby, that being only called a Friend, would avail nothing,
without the wedding garment, the white linen, the saints`' righteousness.
This she was earnestly concerned for at many times, as well as in her last illness,
wherein she expressed to this effect;
that at times she enjoyed so much peace and comfort,
as she had thought mortals could scarcely have been made partakers of;
saying she was easy in her mind to die or live; being freely resigned to the Lord`'s will.

At another time, sitting with her husband and children,
she said they were happy who did not rest only in a name or form of religion,
but waited for the power; and often expressed her trouble for such who seemed at ease,
and satisfied barely in a form, giving way to sleepiness,
and unconcernedness in religious meetings.
She several times expressed her satisfaction in friends`' visits;
and said the Lord was very kind to her in her weakness,
in renewing his blessed presence to the comforting and strengthening of her.
She earnestly desired the Lord would enable her to bear her affliction patiently,
being willing to be dissolved, and was fully satisfied of her future happiness, saying,
'`Praises are due to the eternal God.`'
She was also earnestly concerned for her children, desiring the Lord would bless them,
and that they might walk according to truth, in humility and plainness;
saying she had rather they should die than live, except they did well;
and also desired those about her to be careful to live so as they might be fit to die.

She departed this life in great peace, in Dublin, the 8th day of the Sixth month, 1730,
and was buried in Friends`' burying-ground at Cork-street, Dublin,
the 11th day of the said month.

[.asterism]
'''

MARY BEWLEY, daughter of George Bewley and Blessing, his wife, of the city of Cork,
in Ireland, was a sober, orderly, dutiful and affectionate child to her parents, loving,
meek, and courteous in her behavior, and generally beloved by all who knew her.
She loved and kept to plainness in speech and apparel,
and rather disliked than affected finery and vain fashions.
She was of a weakly constitution,
and seemed in a declining state of health for some time before her last sickness,
which she was taken with in the Sixth month, 1730.
She recovered again so much that, at her desire to see her grandmother, Blessing Fennel,
of Youghall she was carried there the 9th day of the Seventh month; but a few days after,
her weakness and disorder returned, which continued till her death.

She was often thoughtful of her latter end, and under a close concern of mind,
with prayers to the Lord to prepare her for it,
and soon became resigned to the will of God, and grew indifferent,
and rather unwilling to take many medicines,
saying she thought it not well to take too many things, or have a dependence upon them,
or doctors.
When, at one time,
she saw her mother troubled because she did not take things thought suitable for her,
she said, '`Dear mother, be not concerned for me, for if I am to live, I take enough;
but I do not desire to live except to serve the Lord:`'
and desired she might be endued with patience to bear her affliction and sickness.
She was in a close exercise and consideration how she had spent her time,
and what she had said or done amiss;
and prayed to the Lord to pardon and pass by her offenses.
She also desired her parents and near relations about her to pray for her, saying,
'`I am so weak I think I am not able to pray for myself,`' but added, '`we must do it,`'
i.e., pray for ourselves.

The 1st day of the Eighth month, she said to her sister Hannah,
then about twelve years of age, '`My dear sister, honor your father and mother,
and do not give way to little foolish things,
for by small things the enemy draws away the minds of poor children.
My dear, mind your dear sister`'s dying words, and do not put things off to a dying day,
and think it is time enough.`'
That evening her father came from Cork to see her,
to whom she expressed her willingness to die,
but longed for a more full assurance of the love and favor of God.
Next morning he asked her how she did; she answered, '`Very weak,
but I feel a little more comfort now.
I hope the Lord is my strength;`' and in a sensible frame of mind called on the Lord,
saying, '`Dear Lord, forgive me my sins, and teach me to pray.
Lord have mercy on me; my Savior have mercy on me.
Take me, dear Lord, if you please.
Draw me, dear Lord, with the cords of your love;`' with more sensible words,
but her breath failing,
she desired those present might pray to the Lord to make her passage easy.

The doctor one day came, and asked her how she did; she said, '`I am weak,
but the Lord is strong, and on him alone is my dependence.`'
To one of her relations and intimates, about her own age, who came to see her,
first kissing her, she said, '`Dear cousin, I have always loved you, and do so still,
and I believe you are the same to me.
Dear cousin, we are going to part; remember your latter end, and take care of the world;
do not mind the things of it.`'
The 3rd day of the Eighth month she called for her father and mother,
and told them of her weakness of body and exercise of mind,
and how busy her soul`'s enemy was to put thoughts into her mind to disturb her.
She prayed to the Lord to strengthen her,
and also expressed the dearness of her love and affection to them,
for their care over her in keeping her from sundry things which too many run into.
She also said, she formerly seemed to rest satisfied with her education,
but when she grew more in years and understanding, she found that not sufficient;
and then the fear of the Lord, and to live therein,
was what she desired more than the things of this world.

At another time,
she desired her grandmother would pray to the Lord to take her to himself;
and spoke of the temptations of the enemy, and how strongly she was beset thereby.
Her grandmother spoke encouragingly to her, bidding her not to believe the enemy,
who often besets those who are near the Lord.
The child answered, I am very weak, and can do nothing for myself,
but it is the Lord that does all for me;`' adding,
'`Oh! the Lord has been very merciful to me, and is so still.`'
Being filled with a sense of his love, she said, '`How sweet is the love of God to my soul.
Oh! that I could praise him enough for his love and mercy.
Oh! if the love of God is so sweet now, what will it be when I get fully to it.
Oh! that I was with you now, dear Lord; take me into your arms,
dear Lord;`' and so went on praising the Lord, and said,
'`I do not now wonder to have heard so many praising the Lord,
for he is worthy of more praise than I have strength to give him.`'
Afterwards, finding withdrawings of the love of God,
she was under a fresh exercise on that account, and prayed to the Lord to be near her,
and to lift up the light of his countenance upon her,
desiring to be removed where the wicked cease from troubling, and the weary are at rest.

The 4th day of the Eighth month, and First day of the week, inquiring what day it was,
she said she thought she could not have continued so long,
'`but may be I am kept the longer,
because I have too earnestly desired to be gone;`' and therefore
she desired the Lord to give her patience to wait his time,
which is the best time.
Next day she visibly changed for death, and was much spent,
having taken little nourishment for several days; and being asked to take something,
'`Oh`' said she, '`the love of God is what I desire;`' and prayed fervently for it, saying,
Dear Lord, send comfort; why will you withdraw yourself from your poor creature?
One taste of your love before I go.`'
That afternoon she desired to take her last leave of her parents, sister and brother,
and near relations, and said she thought it was better for her to do it then,
lest afterwards she should not be so fit.
And in a very sensible and endeared manner she took leave of them;
and soon after was taken with a faintness, so that it seemed as if she was passing away;
but she revived again,
and that evening the Lord was pleased graciously to satisfy her
soul with the renewed and fresh incomes of his divine love,
in a feeling sense whereof she broke forth, saying, Oh! dear Lord,
how sweet is your love and presence I No tongue can tell it but those that feel it.
Oh! praises to the Lord:
how shall I praise him enough!`' She desired those present to praise the Lord for her,
and said she believed that night she should be with her dear Savior;
and a few hours after, the pangs of death increased, which she bore with great patience,
frequently calling on the Lord while she had strength,
and about the fifth hour in the morning quietly departed this life,
the 6th day of the Eighth month, 1730, aged fifteen years and five months.

[.asterism]
'''

ALEXANDER HOPWOOD, son of Samuel Hopwood and Ann his wife, was born at Austle,
in the county of Cornwall, the 14th day of the First month, 1713.
His parents being such as feared the Lord, having an eye to his honor,
endeavored to inform his mind of the principles of truth when very young,
which had a good effect upon him;
for he was careful in his conduct to avoid those vices which too
much prevail upon the minds of many of the youth in our time.

In the year 1732 he inclined to accompany his father to London,
and they set forward the 26th day of the Second month for Bristol yearly meeting,
and from there to London.
In his journey, but more especially during his stay in the city of London,
the Lord was pleased to renew the visitation of his love to him,
and gave him to experience an increase of the knowledge of his blessed truth.

He got well home with his father the 30th day of the Fifth month,
but afterwards was much out of health at times,
and on the 1st day of the Seventh month was seized with a violent fever.
Next day, his mother being by him, he said, '`If the Lord is pleased to take me,
I am fully satisfied I shall go well, and my soul will be happy,
and have a place among the righteous.`'
The day before he departed, being in a heavenly frame of mind,
which carried him above his bodily weakness,
he broke forth in supplication unto the Lord to this effect:
'`O Lord! you that preserved Shadrach, Meshach, and Abednego, in the fiery furnace,
are able to preserve me unto the end.
O God, what shall my soul say?
I will wrestle with you like Jacob, if I pray all night.
However, if you will not make me like him, give me an evidence of favor with you;
whether I live or die, give me a place within your house.
Lord, if you are pleased to spare my life,
I will obey your commands in everything you are pleased to require of me.`'

He also said he never was guilty of any gross evil, and he was not afraid to die;
and being spent, he lay still in a sweet frame of mind.
His father, mother, sister, and others being in the room,
he looked earnestly on his father, and said.`'
Have you anything on your mind?`'
He answered, '`Yes, child;`' and kneeling down, prayed by him,
and the goodness and love of God came over all present.
The young man making melody,
seemed to have an evidence of that divine favor which
his soul had been so deeply engaged for;
and soon after said, '`O Lord, what shall my soul say?
I have not breath to praise you, O my God! but will do it as long as it lasts.`'

After a little pause, he said, I believe I must take my leave of you.`'
His mother answered, '`Do you think so, my dear?`'
He replied, '`Yes, I do; farewell, all my dear relations.
I hope we shall meet again in heaven.
Give my dear love to my dear brother,
who lay very ill of the same distemper in another room.
Looking on his sister, he said: '`Pray, dear sister, do not weep;
that will but trouble me.`'
Then he began his last farewell, saying, '`Farewell, father,`'
and kissing him several times;
also expressing himself with much love and affection to his mother; and desired,
if the Lord did not see fit to give him a longer time in this world,
he might be favored with a quick and easy passage.
The Lord, of his infinite goodness, was pleased to grant his request,
for after having spent the night pretty much in slumber, near his end said,
'`Call my dear mother that I may take my farewell of her;`' and next morning, like a lamb,
without sigh or groan, he departed this life, being the 10th day of the Seventh month,
1732, aged eighteen years, six months, and twenty-seven days:
and we doubt not is entered into that rest prepared for the righteous.

His body was carried to the meetinghouse at Austle,
where several testimonies were borne to the truth, to the satisfaction of those present;
and from there accompanied by many friends and a great number
of the inhabitants of the town to Friends`' burying-ground,
and there interred the 12th day of the aforesaid month.

[.asterism]
'''

SARAH MARRIOTT, daughter of Richard Marriott and Elizabeth his wife, of Mansfield,
in the county of Nottingham, was a child religiously inclined,
which was observed by her behavior, especially in religious meetings,
she being of a good understanding in the best things.
She was taken ill in the beginning of the eighteenth year of her age,
of a disease which proved a consumption.
After some time she went into Warwickshire for change of air, to some relations there,
but receiving no benefit thereby, she grew weaker, and finding herself declining,
was very desirous to return home,
that she might see her brothers and sisters before she died;
her father and mother being present with her.
Accordingly it pleased the Lord to give her strength to accomplish it,
to her and her relations`' great satisfaction.
She came home the 8th day of the Eleventh month, 1732.

The same evening her heart being opened in the love
of God to impart her mind to her sisters,
and those about her, she signified that she had had a weaning time from the world,
and that she saw nothing engaging in it, but the company of her relations.
She also let us know what an exercising time she had witnessed when at Coventry,
for lack of the presence of the Lord, which he had withdrawn from her a little time;
and that although she had never been guilty of any thing that was bad,
yet she found little things hard enough to get over,
but now could speak of the goodness of the Lord to her.
She said he had been good to her many ways, and that nothing stood in her way,
for which she praised his holy name, in a sweet heavenly frame of mind,
being resigned to his will; and so continued those few days she was with us.
In this time she gave good exhortation to her sisters,
and left some things as a charge to be remembered by them,
as that they might be careful what company they kept,
and to avoid all such as are light and airy, which draws the mind further from God;
but rather to choose the company of such who are religious:
and also to avoid the reading of all vain and unprofitable books,
which tend to corrupt the minds of youth.
She charged them to read the holy Scripture, and such books as promote godliness;
and desired they would be watchful against sleeping in religious meetings,
and set forth the evil of it; as also of singing of songs, and warned them against it,
and further added, that she hoped they would remember her words when she was gone.
Speaking of the visitation of God to her very early, she said,
'`I heard his call before I knew what it was.`'

About twelve hours before her death, being up in her chair,
she desired we might have a little meeting with her,
in which time she was in a solid retired frame of mind,
much desiring she might have an easy passage out of this life;
which was granted her to all appearance.
She all along continued very sensible,
and was not attended with those agonies that are usual,
but lay breathing in spirit to the Lord.
A few hours before her departure,
she desired her love might be remembered to all her relations and friends,
and to all that asked of her;
and that her father and mother might give her up to the Lord,
she desiring to be resigned to the will of him that gave her being.
She departed this life the 12th day of the Eleventh month, 1732, aged eighteen years,
and left a good report behind her.

[.asterism]
'''

[.embedded-content-document.testimony]
--

Being much inclined to leave something in memory of my dear wife, MARGARET ELLIS,
who was very dear to me and my children, I may justly say,
she attained to a good old age,
and that we lived together about fifty-two years with a great deal of satisfaction.
Although we waded through many troubles of several kinds,
yet we still found a secret hand to support us; and we who were most conversant with her,
from good experience can say,
she lived and died in true unity and fellowship with friends of truth,
since she was convinced thereof, and more especially in the afternoon of her day,
when her candle shone brighter and brighter to the end, to our comfort and encouragement,
as appears by the following account.

[.signed-section-signature]
Rowland Ellis.

[.signed-section-context-close]
Plymouth, in the county of Philadelphia, in Pennsylvania, the 8th day of the Sixth month,
1731.

--

MARGARET ELLIS, wife of Rowland Ellis, of Pennsylvania,
for about the last ten years of her life, was deprived of her eyesight,
which she had a sense of about a year before.
For, on a certain time, most of the family being gone to the meeting,
some uneasiness took hold of her mind for neglecting the opportunity,
apprehending the time might soon come upon her when she
would not be able to attend and enjoy those precious times.
So the next meeting-day she went on foot, with a willing mind, though some miles distant,
at the age of seventy-five years, continuing very diligent.
Being deprived of her eyesight, and attended with the infirmities of old age,
yet in this condition she appeared contented in mind,
though she was deprived of what she much desired, i. e.,
the company of Friends at meetings.
Yet her love did not decline, for, whatever would fall in the way,
she would encourage her little family, as many as were able,
to go to meetings at all opportunities; also in the family to sit down together,
and at times she had a word to speak among them
of what the Lord had done for her soul.

She also often spoke to Friends who came to visit her,
of the benefit she had received in meetings,
and that they might not easily neglect such opportunities
through the care and cumbers of this world,
which she was sensible choked the seed the good husbandman had sown.
She was in her last illness affected with the visits of her friends, saying at one time,
'`With what manner of love has the Father loved us!
Surely this is that which Christ left with his disciples as their badge;
when this is enjoyed it unites, and brings us near to himself and one another.`'
She encouraged a friend who had a few words in meetings, to faithfulness, saying,
'`Hide not your talent in the earth, because it seems to you but small;
but press on in the way of faith, and, though it seems to you as a time of night,
the day will break upon you; and as you remain faithful, your talent will be increased.`'
At that time she lovingly took leave of them all, saying to some that wept,
'`Do not mourn for me, for I find my Redeemer is near me, and opens the way,
so that I have nothing to do but patiently undergo whatever he may be
pleased to permit;`' and her spirit being raised above her bodily weakness,
she admired the love and goodness of God to her soul.

At another time, a friend coming to visit her, she signified that the day before,
the low condition of Ruth came before her,
when she came with her mother-in-law from Moab to Bethlehem,
and went into the fields to glean, and happening in the field of Boaz, she found favor,
and was kindly received; and to make her earnings the better,
was admitted to glean among the sheaves,
the reapers being disposed to let fall hands full for her,
inviting her to sit at meat with them, and by degrees she came to be the wife of Boaz.
Which remarks she made in great tenderness of spirit before the Lord,
in the sense of his goodness to them that came to hope under the shadow of his wing;
comparing this to her convincement,
when she came first among friends in their religious meetings, '`Where,`' said she,
'`I was kindly received, and invited to sit down among them,
and partake with them of God`'s goodness, to which at that time I was but a stranger;
yet the Lord in his love and care made himself known to my soul,
and allowed me to sit down with his harvestmen;`'
meaning the ministers of the gospel of Jesus Christ,
whose company she highly valued and prized.
She showed a humble sense of the mercies and lovingkindness
of God to her all her life long,
and now more than ever; `'For,`' added she, '`he is gathering me to himself,
where I shall rest with kings and princes, with God, and holy saints and angels,
with Jesus Christ my Savior and Holy Redeemer,
being sensibly passing out of this world to live forever.`'

In this time of her sickness, which was long and tedious,
she also made observations on Joseph`'s condition when in prison; '`He had,`' said she,
'`the favor of the keeper, the care, the love, the goodwill of the prisoners,
but all this wrought not Joseph`'s deliverance.
He was to stay the Lord`'s time, and so must I. For though I have the love of my friends,
a kind husband, loving and tender children, that are careful of me,
and all other things needful, yet I long to be freed from this mortal part,
which keeps the soul as in prison; yet am waiting the Lord`'s time, which is the best,
and hope shall be content.`'
Some friends from North Wales also came to visit her, and though very weak,
she rejoiced much in their visit saying,
'`I little thought this morning I should have had this opportunity with any of you,
but if otherwise, all was well,
for I find nothing to stand in my way on the other side the grave.`'
Answer being made that that was better than all the world.
'`I know it well,`' said she, '`in this my sickness,
for had I not endeavored to keep a conscience void of offense towards God and man,
it would have been too hard a task for me now in this my great weakness.
For I made it my concern to look over my day`'s work
when night came to lay my head upon the pillow,
and take a view of my own heart,
lest there should be any thing the Lord had a controversy with;
that when the midnight cry came, I might be ready to enter into the bride-chamber,
having the wedding garment.
Let all strive to have their accounts ready, for I can tell you without boasting,
it is an excellent thing to have our lamps trimmed,
that we may enter into the heavenly rest;`' adding,
'`Remember my dear love in the Lord Jesus to all Friends who may inquire for me,
and tell them that as my care has been to live in his fear,
my hope is to die in his favor.`'
So at this time also, desiring to be released, she took her leave of them,
and bade them farewell.

Some friends of the city of Philadelphia also visiting her,
rejoiced to find one of her age retain her senses so well,
but more especially to see that greenness and tenderness which adorned her countenance,
she told them the consideration of Friends in the city came fresh in her mind,
that the elders were mostly removed; '`and,`' said she,
'`you that are coming up in their places stand faithful
for the truth in that which is made manifest to you.
Look not at your own weakness,
and how short you are of them of the first rank that went before.
Be not discouraged in coming up in the Lord`'s service.
He will endue you with strength and wisdom to carry
on his own work to the honor of his name.
Remember the zeal of Phineas, when he executed judgment upon the transgressors,
whereupon the plague was stayed; and how great was his reward!
For the Lord said to Moses, Phineas has turned away my wrath from Israel,
so that I have not consumed them in my anger;
therefore I will give unto him my covenant of peace:`' adding,
'`I am glad to hear a good report of you, and the Lord preserve you.`'
And on parting signified her great love to faithful Friends.

At another time, being set with the family, though very weak, she said,
'`You are young and strong, in the prime of your time, judgment, and understanding;
improve your talents in your time, that is the way to be helpful to your aged parents.
As for me, I question whether ever I shall have the like opportunity with you.
It is my desire you may follow on to know and witness the truth more and more.
Let not the manna gathered yesterday suffice you for today,
so you will come to know substance in yourselves, and strength towards God.
Be careful of your aged father, and helpful to him in his declining years;
he is weak and feeble, and easily cast down too low:
the Lord grant he may be so strong as to run the race with patience.`'
A great concern was often upon her mind,
lest too much liberty should creep into the church, and thereby mar the beauty of Zion,
and cause her excellent name to be a scorn to the heathen.
Oh! that her ministers may be faithful,
lest they give occasion to open the eye in many that watch for more liberty,
and that they may be careful in all things, both in word and deed.`'

The day she died, her children being about her,
it was asked if she had any thing further to tell them; to which she answered,
'`I have spoken to you while I had strength and words given me, what shall I say more?
You have the anointing, the spirit of truth, which will lead you into all truth.`'
Hearing her younger daughter weep, she said, '`Where is your resigning me up,
as you did this morning?
Is your faith weakened so soon?
Get hold of him who in time of great exercise has supported you,
and he will be the same again.`'
About an hour before she departed, she asked, what time of the night it was.
It was answered, about eleven o`'clock.`'
From twelve till break of day I usually had my bad fits,`' said she,
'`and by and by I shall rest quiet and easy with my Savior.`'
Something to take was offered her; she said, '`No more of the fruit of the vine,
no more forever.`'
So having desired their prayers for her short passage, she stretched herself out,
and lifting up her hands, committed her soul to God.
