== A Short Account of Alice Hayes

It has been in my heart for many years to leave behind me
a brief relation of the Lord`'s dealings with me,
from my youth up to this day,
for the encouragement of the young to faithfulness
and continual trust and confidence in the Lord,
who never fails those that truly depend upon Him,
either in temporal or spiritual mercies.

I was born at Rickmansworth, in Hertfordshire, in the year 1657, of honest parents,
who raised me in the profession of the public worship of the church of England.
My mother died when I was very young; but while she lived, she was a tender,
affectionate parent to me, almost to excess.
One instance of her affection was very remarkable.
I being at one time very weak, and thought to be near unto death,
the exercise thereof was so hard to her that she fell down upon
her knees and prayed the Lord to take her life and to spare mine;
which He did, for reasons that are known only to Him.

I continued at home with my father till about the age of sixteen years,
under the sharp government of a step-mother,
whose austerity to me made me weary of living with her,
insomuch that I left my father`'s house, and went to service,^
footnote:[Young, unmarried women at this time would often bind themselves under contract
for a number of years as a servant or governess in large private families,
in order to assist the heads of the household with various domestic duties,
and with the upbringing and education of their children.]
that I might live more at peace than I had done.
The Lord in mercy remembered me, and looked upon my affliction in that day,
though I had not yet come to the knowledge of the truth.
He followed me in those days with His reproofs in my conscience for the sins of my youth,
which were dancing, singing, telling idle stories, and some other vain pastimes,
into which youth are too liable to run.
And not being reproved by my parents for these things, nor by the priest,
I went on grieving the Holy Spirit of God in myself,
not yet knowing what it was that reproved me in secret for these things; though,
through the Lord`'s great mercy and goodness to me,
I was addicted to no worse evils in all my life.

Nevertheless, when the Searcher of all hearts came by His light to open my understanding,
and to set my sins in order before me,
and to make known what it was that reproved me for my misspent time, then,
(oh then!) the day of Jacob`'s trouble^
footnote:[Jeremiah 30:7]
was experienced.
Oh it was dreadful to me to consider how I had overlooked the reproofs of the Almighty,
and I was often ready to bewail myself after this manner:--"`Oh! that I had had parents
that could have informed me that those things for which I was reproved were indeed evil;
or that they had told me that those secret reproofs
I often felt were from the Spirit of the Lord!
Surely I never would have done as I did!`"
But neither my parents, nor the priest, taught me any such doctrine;
both of them considering all such things as but innocent and harmless diversions.
And as for the light, grace, or Spirit of God that reproved me,
I had never heard there was any such thing so near to me as I felt it and found it to be.
Then I was grieved to think that the Lord of glory should
have so long knocked at the door of my dark heart,
and waited for entrance, and that I had so long kept Him out,
though He still followed me with His judgments,
and in great mercy to my poor soul often brought me into deep sorrow.

The consideration of my latter end was laid weightily before me,
with thoughts of eternity, and the words "`ever and ever`" took deep hold of me.
Then, oh, the trouble and surprise I was in!
Insomuch that I could not tell what course to take,
nor to whom I could make known my distressed condition.
Sometimes I have gone into the company of other people,
attempting in this way to divert my sorrow; but that would not do.
Then I would seek out some secret place,
and there I would fall upon my knees and pour out my spirit before the Lord,
begging for mercy and forgiveness at His hands.

Now I am about to relate how the wise hand of the Almighty guided me.
After I left my father`'s house, I went inquiring for a place of service,
and soon heard of one, where I continued some time, and was well beloved in the family.
I served them honestly, and in love.
But it may not be amiss to state how I spent my time
at my first place of service with respect to religion,
which was after this manner: I kept close and constant, as opportunity permitted,
in going to the public worship, and very often went alone into private places to pray,
and greatly delighted to read the Scriptures, and to get passages by heart.
And when my hand was in my labour, my heart was meditating on good things,
and I was very glad that I was away from my father`'s
house because of the quietness I enjoyed.
I was often comforted in my heart in those days, though I knew not from where it came.

As I thus continued in well-doing, according to the best of my knowledge,
the Lord was pleased to appear to me in an extraordinary manner,
and a sweet visitation I had.
I was led into a deep silence before the Lord, where I was taught to wait,
and I dared not utter my own words.
And though I had gathered many good words and Scripture sentences into my brain,
now I came to see this would not do.
After this manner I spent my time, and a good time it was to me.
It was the Lord`'s doing, and He shall have the praise of it; blessed be His name forever!

After some time, I went to live at the house of a justice of the peace,
where my first husband and I became acquainted.
But I should first mention,
that I went for a short time to my brother`'s house
before I entered into my second service,
and while I was there,
I heard a report in the neighborhood of a woman preacher
who was greatly esteemed among the Quakers,
and who was to be at one of their meetings not far from my brother`'s house.
Some of the neighbors, out of curiosity, had a mind to hear and see her,
and so asked me to go with them; to which I consented.
When I came to the meeting, it made a great impression upon my mind.
The solidity of the people, and the weighty frame of spirit they were under,
occasioned many deep thoughts to pass through my heart,
by beholding so much difference between their way
of worship and that of those where I usually attended.
After some time of silence, a woman stood up and spoke,
and her testimony so affected my heart and tendered
my spirit that I could not refrain from weeping.
But, alas, after the meeting was over,
the enemy soon prevailed again and darkened the little spiritual sense I had,
both by means of outward instruments and inward suggestions,
so that I went no more to any such meeting for several years.

The time having come to begin my service at the house of the justice, my mistress,
before I had been with her very long, would often be saying,
"`This Alice will become a Quaker;`" though I still had no such thoughts.
Yet through the Lord`'s goodness to me,
I spent all my spare time either in reading or in getting alone,
or in some religious performance,
and also continued diligent and faithful to the trust
that my master and mistress committed to me,
to their satisfaction, and to my own as well, feeling well pleased with my place.

It was in this family, as I said before, that I became acquainted with my first husband,
Daniel Smith, who in love made suit to me,
and we continued together in that family near two years.
About the end of that time,
it pleased the Lord to visit me with sore lameness occasioned by a sprain in my ankle;
but for some time longer I continued in my service.

That winter my master and mistress removed to London,
and did not have occasion for as many servants in town as they kept in the country.
Some they dismissed, and my mistress provided a place for me until summer,
when they were to return.
At this place I received hurt, with regard to my spiritual condition.
Here I had no help towards heaven, but rather the contrary,
by the bad example and the vain and irreligious conduct in that family.
I therefore caution young people to take special care what company they keep,
and to flee from bad associates as from a serpent.
For surely, such company proved like venom to me,
as it helped to drive good things out of my mind, and so forgetfulness of God followed,
which caused many a sorrowful hour when the Lord brought me to a sense of it.
But blessed be His name, He did not permit me to go on long in this state;
for now my lameness grew worse,
and the time came that I was to leave this family and return to my former master,
the justice, where I longed to be, because it was a more orderly family.

I gladly would have been healed of my lameness in my own time,
that I might be able to perform all of my duties;
but I found that the more I strove for a cure, the worse I grew,
insomuch that I was obliged to go home to my father`'s house.
This was no small exercise on account of my step-mother; but blessed be the Lord,
the day of His love was still lengthened out, and though it came with judgment,
yet it was mixed with mercy.
Great was my pain in body, and much greater was my sorrow of mind.
In this affliction, like Israel of old, I cried to the Lord for help;
for now I saw plainly that if He did not help me, I would be undone forever.
I despaired of man`'s help, for I had tried it many times to no purpose,
so that great and many were my cries and prayers to God to restore me,
resolving to serve Him in newness of life.
This was the covenant I was ready to make with Him.
Oh! the matchless mercies, and long forbearance of a good and gracious God, to a poor,
distressed, disconsolate, and unworthy creature!

Very remarkable was the faithfulness and constancy of my dear friend,
Daniel Smith (afterwards my husband), who, in all my distress and weakness,
never shrunk in his love to me, but continued constant,
though I was brought to be a poor cripple and went about with crutches.
He was a comely and handsome man,
and by this time had taken up a farm where he was likely to do very well,
and seemingly might have found a far better match.
But he, like an honest man, never regarded my lameness, but continued firm and constant,
and waited two years to see how the Lord would deal with me.
And at the end, seeing no amendment in my health,
he nevertheless proposed marriage to me, and accordingly we were married.
A faithful, tender, loving husband I had in him;
who provided for me all things that were needful and comfortable;
a mercy and blessing I hope I shall never forget.
His constancy and faithfulness are worthy to be recorded.
The blessing of God was his reward in this life,
and I have no doubt that he is at peace with his and my God.

In a few months my lameness grew better, so that I left my crutches,
and could walk pretty well.
But, oh, it is to be lamented, that I missed my way;
for having recovered from my lameness, and grown strong,
living in my heart`'s content with a loving husband, and outward things prospering,
I forgot (like Israel of old) the tender dealings and mercies of so gracious a God,
and the promises and covenants I had made with Him;
and I gave myself whatever liberty my unstable mind desired.

Thus I went on for about one year and a half after my marriage; when the Lord,
with an eye of pity, looked upon my wretched and miserable condition,
and laid His hand upon me, in order to awaken me out of this false ease,
by a sickness that brought me near to death.
Then, my conscience being thoroughly awakened,
I beheld my backslidings and disobedience with amazement.
Horror and condemnation took fast hold upon me, and the Witness arose within,
which caused sore distress of mind; and in this condition,
I seemed just about to step out of time into eternity.
I saw, that if I died in this state,
my portion must be with the unbelievers and disobedient,
in the lake that burns with fire and brimstone forevermore.
And indeed, it would have been justice,
had God then cut me off for my covenant-breaking and disobedience.
Oh it was dreadful to me, to behold my time so short, and the work I had to do so great!
I lay under horror and astonishment, wondering how I could endure the torment I deserved.
Let the thoughts of this sink deep into the heart of everyone who reads these lines,
that they may become prepared and truly fitted for the kingdom of rest and peace,
when pale death looks them in the face.
Then it will be easier with them than it was with me;
for no mortal can tell the anxiety I lay in for several nights and days,
looking for that dreadful sentence, "`Depart now, for your time here shall be no more.`"
Oh, the fervent cries and prayers I put up to the Lord at this time,
that He would be pleased to spare me this one time more;
and I begged all that came near me to pray for me.
My cry was, "`Spare me a little longer, and try me once more,
and I will become a new creature.`"

Thus I ventured once again to enter into covenant with the Lord; who,
in great mercy and pity, looked upon me, and spared, and pardoned,
and raised me up from the brink of the grave.
Oh, the boundless mercies of God; how shall they be sufficiently set forth by me!
Everlasting glory be given unto Him; let all that is within me praise His name.
And seeing that it pleased Him to hear my petition, and to raise me up again,
and to give me a little strength,
the remembrance of my former state seized upon me daily,
and called for the performance of my vows and promises to become a new creature.

And now I began, according to the best of my knowledge,
to live according to the following manner: Morning and evening I failed not to pray,
and to read the Scriptures and other books which I believed to be good ones,
constantly going to the public worship when able.
I also resolved to be very mindful of my words and actions,
and to act justly before all men.
And I saw I must walk very humbly before the Lord, in order to become a new creature;
for He let me see that it was holiness He called for at my hands,
and that it was my duty to persevere therein, not for a day, a week, a month, or a year;
but if I would be saved, I must hold out to the end.^
footnote:[Matthew 10:22,24:13; Mark 13:13]

Notwithstanding I set myself strictly to observe the aforementioned performances,
many months had not passed over my head before I found a
very strange alteration and operation in me,
the like I had never felt before.
The foundation of the earth within me began to be shaken,
and it was strange and bewildering to me.
I had hoped that now being found in the aforesaid practices,
I would have witnessed peace and comfort; but behold, I found the contrary!
Instead of peace, came trouble and sorrow, wars and commotions.
I feared that my condition was such, that there had never been one like it,
not then understanding that "`the messenger of the covenant was
coming to His temple,`" even He whom my soul had been seeking;
and that He must sit there, that is, in my heart,
"`as a refiner with fire and as a fuller with soap,`"^
footnote:[Malachi 3:1-3]
to clear His own place, which was defiled by the usurper,
who had taken up his habitation there too long.
Oh, it was a long time indeed that the Lord of life and glory was kept out of His habitation,
for an entrance into which He had waited and knocked nearly twenty years;
during which time I had accumulated much fuel for the fire,
and much work for the refiner,
whose skillful as well as merciful hand preserved me in the furnace.
The bad part in me was so great, and the good so small,
that I thought all would perish together;
for the heat of that fire in my heart was great and terrible, so that, like David,
I was ready to say, "`My bones are all out of joint;`"^
footnote:[Ps. 22:14]
and in the depth of my distress, the enemy was very strong with his temptations.
But oh, the kindness of God to me in that day,
"`for then did help come in the time of need.`"^
footnote:[Hebrews 4:16]
The old adversary was strong, and not willing to lose his habitation,
nor have his goods spoiled; but Christ, the stronger Man, overcame him in due time,
and cast him out; and blessed be God, in a good measure He also spoiled his goods.
The strugglings that I felt in those times I hope will never be forgotten;
and my desire is that these lines of experience may (and I do believe they will) be
of service to some poor distressed traveller who may have to walk in the same steps.

I thought,
that if I had met with a written account of any that had gone through such trials,
it would have been some help to me.
I searched the Scriptures from one end to the other, and read several books,
but I thought none could fully speak to my state.
The third chapter of Lamentations, many of the Psalms,
and the seventh chapter of the Romans did somewhat affect me at times,
whereby a little hope would arise in the thought that the writers
of these books had passed through something like it.
But oh, the bitter whisperings of Satan, and the thoughts that passed through my mind,
were such as my very soul hated!
Yet such were the suggestions of the enemy, that he would charge these upon me,
as if they were my own.
But the Lord, in His own due time,
gave me to see "`that he was a liar from the beginning.`"^
footnote:[John 8:44]

Indeed, had not a secret hand of power supported me in this my bewildered state,
I had surely fainted, and laid down in the depth of despair.
Day and night were alike to me; there was no fleeing from the presence of the Lord,
or from His righteous judgments which pursued me and were now poured upon the transgressing
nature in me which had long continued in its place and taken deep root.
Now the refiner`'s fire was made very hot, in order to burn up the dross and the tin.
Oh, happy is the man or woman who abides the day of His coming;
for sure I am that "`His fan is in His hand,`" and if men will but submit when He appears,
He will thoroughly do that for them which no other can do, namely,
"`purge the threshing floor,`"^
footnote:[Matthew 3:12]
which is man`'s heart, where all the chaff is to be burnt.

This is the baptism that does people good.
May the Lord bring thousands more through this inward experience
in order to prepare an offering to God in righteousness;
for nothing short of this will do, or stand in the great and notable day of the Lord.

After this manner did the Almighty (in great lovingkindness) deal with me,
for His judgments were mixed with mercy to one so unworthy.
And as I continued in patience, resolving to press forward towards the mark,
various were the inward states I passed through.
Yet by the assistance of the light of Christ (without which,
I had surely fallen in the vast howling wilderness,
where so many dangers did attend) I came to witness, under the Gospel dispensation,
what Israel of old passed through while in the land of Egypt and by the Red Sea;
for I experienced their travels in the depths,
with their coming up on the banks of deliverance,
and likewise their travels through the great and terrible wilderness,
where there were fiery serpents and scorpions,
and a drought wherein they could find no water, as in Deuteronomy 8:15.

Marvelous it is to think,
that I could ever be preserved through the diversity of these states,
and this without the assistance of any outward instrument, which, blessed be God,
many now have.
For at this time I was still under the hireling teachers,
to whom I very frequently resorted,
and I would happily have settled under them if I could have found peace.
I was constant in my attendance at the steeple-house; but sorrowful I went in,
and sorrowful I came out, week after week, and month after month,
seeking the living Lord among the dead forms and shadows, but not finding Him there.

And of course it was so with me,
for I lacked the true knowledge of the Lord Jesus Christ,
whom my very soul desired more than any outward enjoyment.
I was grieved at my very heart in that day to behold
the barrenness of both priest and people.
I looked for some fruits of sobriety, especially in the time of worship;
but I saw some were light and airy, with an appearance of pride;
others were rude and careless; and some were sleeping.
And there was so little solidity, that I was often ready to say to myself,
"`Is there no people that serve the Lord better than these?`"
For I observed with sorrow that they would be talking of
their farms and trades until they came to the very door,
and then again as soon as they came out; which I thought not right.
But still I continued under my exercise, grievously weighed down and bowed in my spirit,
wishing in the morning that it were evening, and longing in the evening for morning.
Indeed, so great was the horror I lay under, that I often wished I had never been born.

But it was not long before I came to witness some tenderness spring up in my heart,
which had been so long hard.
I could weep in the sense of my lost and undone state;
but I still knew not where to look or wait for the appearance of Christ,
though I had felt all these inward workings and strivings.
And when I felt a little ease or comfort, I felt it within; for indeed,
_there_ was my grief and my wound.
But I knew not that God was so near me,
nor understood who it was that conveyed comfort to my soul.
I thought that God was only in the heavens above the skies;
for the Scriptures were still a sealed book to me,
and I did not know that He could be so near to me as, by His light,
to let me see the outgoings of my mind, and the very thoughts and intents of my heart.
Nevertheless, at times I felt a little warmth in my heart,
accompanied by a breathing to God in these words: "`Oh Lord, make me one of Your fold,
a sheep of Your pasture!`"
These cries to God, with little else, passed through my heart for many months;
for this was the first good desire that He begot
in me after He led me through judgment for sin.
Then the light, or good Spirit of Christ (which is one),
let me see plainly that I was not in fellowship with His flock.
Therefore the cry remained, "`Lord, make me one of Your fold,
a sheep of Your pasture;`" for as yet I did not see who they were,
nor where they were gathered.

But as I continued under these exercises,
the Lord was pleased to make known to me His people, after many mournful nights and days.
But indeed, this proved a great cross to me,
and I went through great sufferings before I could
submit to be counted a fool among the people of God,
with whom I now have true unity, and I bless God for the privilege.

If any should question, and say,
"`How did you come to have these people shown to you by the Lord, as you say?`"
I will give you this true answer, in much simplicity and integrity of heart.
As I continued under the aforesaid exercise, it frequently ran through my mind,
"`Go to the Quakers;`" as intelligibly to my understanding
as if I had heard an outward voice.
But I was not hasty to give up to this motion,
fearing and doubting lest it should be the enemy
of my soul seeking to deceive and beguile me,
and lead me into error;
and so I continued attending the public worship of the church of England.
At last I could find no peace or comfort there, but still the voice followed me, saying,
"`Go to the Quakers;`" Nevertheless I continued to linger for the aforesaid reasons.
Then that passage came into my mind from the tenth chapter of the Acts of the apostles,
concerning Cornelius, who had continued a long time in prayers and alms,
and an angel from God was sent to direct him to send for Simon Peter,
who would tell him what to do.
These Scriptures opened plainly in my mind; but notwithstanding this,
I reasoned within myself, saying in my heart:--"`As for Cornelius,
I know an angel directed him; but as for me, what do I see?
I only hear, as it were, a voice within me saying,
'`Go to the Quakers,`' and I may be deceived if I heed it.`"
So I strove against the motions of the Spirit of Truth,
not knowing I was under that dispensation wherein God now "`speaks to us by His Son,`"^
footnote:[Hebrews 1:2]
in the hearts of His people.

Yet such was the mercy and love of God to me,
that in this time of my ignorance and infancy,
He was pleased in great mercy to follow me;
so that I can truly say that I witnessed the Scripture to be fulfilled where it says,
"`In the day of Your power, Your people shall be made willing.`"^
footnote:[Ps. 110:3]
It was no less than the power of God that constrained me
to go and hear what sort of doctrine was preached by them,
for I had never but once heard any of those people preach,
and that was five or six years before.
And after long struggling and reasoning, I inquired for a Quaker`'s meeting,
and was informed of the place and day.
I went to it, not acquainting anybody where I was going,
nor had I opened my condition to anyone, nor could I. When I came to the meeting,
there I saw a small number of people waiting upon the Lord,
and after some time a servant of God stood up and declared
such things as I had never before heard from anyone,
whereby my present state was fully spoken to; and I could set my seal to it,
that it was the truth.
The power that attended the testimony reached to the witness of God in my heart;
and a zeal for Him was raised within me,
by the hopes that were begotten through the preaching of the Word of truth.

When the meeting was over, I went away with joy and gladness of heart,
and my understanding was in some measure opened.
A measure of faith was also raised in me that the Lord still had regard unto me,
seeing that my condition had been so plainly opened by a handmaid of the Lord,
whom I had never seen before.
The Lord alone knew my condition at that time;
and as I continued faithful to what He made manifest unto me,
it pleased the Almighty One to make bare His powerful arm for my deliverance
through the many and various exercises that I met with for the Gospel`'s sake.

Soon after I received the truth,
I met with many sorts of enemies which the old adversary raised up;
but forever blessed be the God of my life,
He gave me power and dominion over my inward enemies,
and delivered me also from the outward ones.

My attendance at meetings coming to be known, both in my family and neighborhood,
the devil stirred up some wicked instruments in order to set my husband against me.
My dear husband, who had been so tender and loving to me all our days till now,
grew very unkind, and his love turned into hatred and contempt.
This was very hard for me to bear from one whom I so dearly loved;
but it seemed good to the Lord so to allow it, in order to try me,
whether I loved anything more than Him.
Sometimes when I went to dress myself to go to meeting,
my husband would take away my clothes; but this mattered little to me,
and I would go with whatever I had; so he soon left off this practice.
Many other trials I met with from him, which I think not proper to mention.
But one very close trial he put me to was this: he being pretty cool in his temper,
spoke very seriously to me after this manner;
"`I have now come to a resolution in my own mind what to
do if you do not leave off going to the Quakers.
I will sell all that I have, pay everyone what I owe them, and go and leave you.`"
This struck close to my very life; but then the saying of Jesus came into my mind:
"`He that loves anything more than Me, is not worthy of me.`"^
footnote:[Matthew 10:37]
Here I was brought to the very proof, whether I loved Christ Jesus best, or my husband;
for one of the two must have the preeminence in my heart.
Indeed the time had come for the full proof of my love to God,
whether I could leave father and mother, brothers and sisters, yes,
and a husband that I had loved more than all, for Christ and the Gospel`'s sake.
This is a trial which none can know, but those who experience the same;
for these relations are very near to the heart, and without an invisible support,
the soul cannot hold up under such trials.
But those whose hearts are true to God,
being sanctified and made clean by the washing of regeneration,
are enabled to deny themselves, not only of unlawful things,
but also of the dearest lawful things, for Christ`'s sake and the Gospel`'s.

My husband waited for my answer to what he had proposed,
and after some time of weighing the thing in my spirit, I said,
with a true concern upon my heart: "`Well, husband, if it must be so,
I cannot help it;`" explaining to him that I could not, in compliance to him,
let go of what I had found in God through faith in
His Son who had come to save me from my sins;
nor could I refrain from going to worship God among the people whom He had so
visibly and so fully satisfied me that He acknowledged to be His followers,
and among whom I had felt and witnessed His presence.
Everlasting praises be given to His name,
because when hopes had been raised in me that through faith in
the Son of God my sins would be pardoned for His name`'s sake,
I could not let go of my Savior for the love of a husband,
though nothing else in this world was so dear to me.
The Lord permitted him to inflict many a sore trial upon me,
which were like wormwood and gall to me during the time they lasted.
But I received them as from the Lord`'s hand in kindness,
in order to try how constant I would be in my dependence upon Him alone,
when all in this world that were near and dear to me had turned against me; yes,
father and mother, brothers and sisters; but nothing came so near to me as my husband.

When I truly came to take up the cross for Christ`'s sake,
I met with persecution of various sorts;
but that of the tongue was the hardest for me to bear, and a large share of that I had,
with many cruel mockings.
But thanks forever be to that power who upheld me through grievous abuse, false reports,
belittling, and slighting.
The very remembrance thereof bows my heart and humbles my spirit
in the sense of the kindness of God to me in that day,
who enabled me with patience to go through all the clamor of their tongues,
till it pleased the Lord to remove many of my persecutors and slanderers out of my way,
some of whom I may have occasion to mention.

It being spread about that I had turned Quaker, the priest of the parish,
whose name was John Berrow, having heard of it, came to give me a visit.
Among the rest of his discourse and reasonings with me,
he was so bold as to venture to tell me that the Quakers denied the Scriptures,
and the resurrection, and the man Christ Jesus who died outside the gates of Jerusalem;
and that they only believed in a Christ that was within them.
To this I answered, "`No, they do not say so; nor do they preach such doctrine.`"
To which he replied, "`It may be that they do not yet, until they have got you.
You do not discern their hook, or their gilded pill.
It is a dangerous doctrine they hold, and damnable heresy they are in.`"
To this I only replied, "`If they deny Christ,
I will never be a Quaker;`" and so he went his way.
And after much labour both of body and mind, in searching the Scriptures,
and comparing their doctrines and principles therewith,
I found this priest to be a false accuser.

Some years after this,
I found a weighty concern upon my spirit to go to his public place of worship,
and to charge him with this falsehood in order to vindicate the professors of the truth,
and to clear my own conscience.
I shall afterwards have more occasion to mention this event;
but shall now proceed to say something concerning those instruments before hinted at,
who were the authors of much disturbance to my dear husband, and of great exercise to me.

A cook-maid that lived with the justice whose servant I formerly was,
and a servant maid of my own, being both of a bad spirit,
cared not what lies they made and reported of me.
But the Lord made known their wickedness, and my innocency, in His own time.
My maid, by her stories and deceitful conduct in the justice`'s family,
thought to have preferred herself there,
knowing it pleased the justice`'s wife to hear stories
concerning me because of her dislike for the Quakers.
But in less than six months after she went from me, she was found to be a thief,
and ran out of the parish, and I never saw her more.
As for the cook-maid, she in a very short time came to much poverty,
and I afterwards often relieved her.

Two others were very sour to me, namely, the justice`'s wife and my husband`'s mother.
The two maids before mentioned had so filled them with bitter unkindness towards me,
that they very much troubled my husband, setting him against me.
The justice`'s wife especially caused me to go through great difficulties.
However, this lasted not long, for in a few months after I was convinced of the truth,
she went to London, where she stayed some time.
And when the time of her intended return had come,
and a coach was provided to fetch her home, death struck her,
and she was brought home dead.

My husband`'s mother being very full of wrath and bitterness towards me,
I tried to pacify her by entreaty,
and by acquainting her a little with some of my exercises explaining
to her that I did not go to the Quakers in a stubborn mind,
or in self-will, nor with any ill design of ruining my husband, as some reported.
But when I began to speak these things to her, she flew into a bitter passion,
grievously reproaching me, saying I would be the ruin of her child, meaning my husband.
I could by no means bring her into any moderation, nor would she hear what I had to say,
but departed from me expressing herself in much anger after this manner:
"`I will not endure you any more!`"
She went home, where she soon fell sick and died,
and was buried in less than a week`'s time.

But the enemy soon stirred up another, my husband`'s step-father.
He came one time to our house, full of prejudice against me,
and brought a great book with him, and then sat down.
My husband soon came in, and they both set upon me, reproaching the Quakers.
I attempted to go outdoors, but my husband prevented me,
for he placed himself by the door to hinder my going out.
In those days I could not talk or contend much for the truth; but blessed be the Lord,
I was made willing to suffer for it many ways; but that which was hardest for me to bear,
was from my husband, whom I loved as my own life.
We had not then been married above two years, so that if God had not upheld me,
I would certainly have fainted.

My husband not permitting me to go out as I intended,
the great book was laid upon the table, and they said to me,
"`If you need a book to read,
here is one for you to look into;`" and they urged me to read it.
I took their book, and read awhile to myself, but I soon shut it and would read no more,
for I saw that it had been written by an adversary of the truth.
I then took up the Bible in my hand,
and the first place I cast my eye upon was that passage in the Psalms, where it is says,
"`It is better to trust in the Lord than to put confidence in man; yes,
it is better to trust in the Lord than to put confidence in princes.`"^
footnote:[Ps. 118:9]
Oh, the comfort I felt in reading these words!
It was more to me than any outward treasure, for I found my strength renewed,
and patience was given me to bear all, and to suffer quietly.

My father-in-law used many bitter expressions, saying that if he were my husband,
he would never endure it, insinuating that he would leave me;
my husband being then present,
and having himself before threatened me with the same thing.
Then my husband`'s step-father began to curse and swear,
for which I could not forbear reproving him (in the plain language).
But this so enraged him that he was like a madman, cursing and saying;
"`Do not '`thee`' and '`thou`' me!`"
And in a bitter manner, he said, "`A Quaker, away with you!
If you had been anything else--had you been a Baptist,
and gone to hear them every day of the week--it had not been so bad as this.
But a Quaker!`"
And again: "`If you will not turn from your religion, I will buy a chain,
and chain you to that maple tree that stands in the pasture;
and there you shall be glad to turn for hunger.`"
More might be mentioned, which I omit for brevity`'s sake.
My poor husband said not much at that time,
but only kept me within doors to see and hear what his step-father could do with me.
But blessed be the Lord, these things did not move me.
So let all be encouraged to trust in that ancient
arm of power that never failed in time of need,
nor ever will fail those who have a single eye to His glory.

It was not long before the Lord brought them both to a sense of their error;
for the next time they met,
my father-in-law told my husband he was very sorry for what he had said and done to me,
and that he would never do so again.
And indeed, he never spoke to me in that way again,
but ever after was very loving and moderate to me.
In time, such an impression was made upon him,
that he became very moderate and respectful to all Friends with whom he conversed.
Afterwards my dear husband`'s love to me returned,
and he continued to the end of his life a loving and tender husband,
and an indulgent father to our children.
And through the Lord`'s goodness to him,
he was convinced that it was the truth for which I suffered;
and I do believe he died in the faith, and is at rest with his God; for which,
and all His mercies, let all that is within me give Him the praise.

Having been made an experiential witness of the dealings of the Lord,
and passed through several states,
it pleased the Lord to make me instrumental in His
hand to speak a word in season to others,
both in public and in private; and in my obedience to the motion of the Spirit of God,
I found peace, strength, and encouragement to persevere.

But I may first make a little observation concerning
the deceitful spirit by which John Berrow,
the priest of the parish of Watford, was led, which I beheld to my grief and sorrow.
I felt a concern come upon my spirit to go and reprove him publicly in his worship house,
for his false accusations--as that the Quakers denied the Scriptures,
and the resurrection, and the man Christ Jesus that died outside the gates of Jerusalem,
and that they only believed in a Christ within them--as well as for his going from house
to house in order to discourage well-inclined people from going to Quaker`'s meetings.
For he found the interest of many people declining from him;
as at that time a good thing was stirring among many in that place,
and people were inquiring after the kingdom of heaven.

For these reasons,
I found a great concern upon my spirit that the way
of the Lord and His people might not be misrepresented,
and that the honest inquirer might not be turned out of the way.
As this had rested long and weightily upon my spirit,
I often cried to the Lord to enable me to faithfully
discharge what I saw He required at my hand.
The concern was weighty, and I was not hasty,
lest I should be found running before I was sent.
I therefore waited patiently to be fully satisfied in the matter,
not only a day or a week, but many months; and as my concern grew heavier upon me,
I at last gave up to it, begging the Lord to be with me,
and to give me a full commission for so weighty a service.
It pleased the Lord to confirm me in this thing several ways;
notwithstanding (like poor Gideon of old) I presumed to prove and try the Lord once more.
So I said in my heart: "`Oh Lord, if You will be pleased to send Your servant,
Francis Stamper, to this town tomorrow, then I shall be confirmed.`"

I had not told anybody what I felt the Lord had laid upon me to do,
and it pleased Him to grant me my request.
On the next day, which was the 31st of the eighth month, 1696, when meeting time came,
and Friends were going, Francis Stamper was not among them;
but I had faith to believe he would come.
As I was going to meeting with some Friends,
I said to them that I would go back and wait for Francis Stamper;
at which some of them smiled, knowing he had just returned home from a long journey.
I had waited but a little time before he came, and I very well remember his words: "`Oh,
how has my spirit been dragged here!
I was late last night at London, but must go to Southgate.`"
I took good notice of his words,
but said nothing to him of my concern until after the meeting;
when coming to a Friend`'s house, I told him what I had to do,
and I asked him if he would go with me.
To this he answered, after weighing the thing in himself, "`I will go with you.`"

In the afternoon we both went to the steeple-house,
and sat down in the row opposite the priest,
and waited till he had finished his sermon and prayer.
Then I stood up, and said to the priest, "`Neighbor Berrow, I have a question to ask you,
and I do desire you and this assembly to hear me.`"
But he would not stay, and hastened out, without hearing what I had to say.
Seeing him go out so hastily, I turned to the people and said:
"`John Berrow came to me and said that the Quakers
would tell me that I must deny the man Christ Jesus,
who died outside the gates of Jerusalem,
and that I must believe only in a Christ that was within me.`"
And I bore this testimony to all present at that assembly, saying,
"`We do acknowledge the Scriptures;
and do say and believe that there is no other name given under heaven,
whereby any can be saved, but the name of Jesus Christ,
who died outside the gates of Jerusalem, and was buried, and rose again the third day,
and now sits at the right hand of God,
glorified with the same glory which He had with the Father before the world began.`"
Then I stopped, and Francis Stamper stood up,
and would have said something to the people by way of advice;
but one of the churchwardens with some others, came and compelled us both to go out.
I stepped upon one of the seats, and acquainted the people,
that we would have a meeting that evening at our meetinghouse,
where all who were so inclined might come; and blessed be God,
a large and good meeting it was,
where the glorious presence of the Most High was with us.
And that faithful servant, Francis Stamper, had good service for his God that evening,
as also at many other times in these parts,
where there was great openness among the people, and many were convinced.
In a fresh and lively remembrance of this faithful servant of the Lord,
the following testimony springs in my heart to leave behind me.

[.embedded-content-document.testimony]
--

[.letter-heading]
Alice Hayes`' Testimony concerning Francis Stamper

Francis Stamper was a man given up and faithful to God in his day;
who ran to and fro on the earth for God`'s honor and the good of souls, rising early,
and lying down late.
He was industrious in God`'s vineyard and harvest-field,
for the Lord had made him a skillful and laborious workman,
and a valiant soldier who feared not the great and potent adversary.
Eminent was the power which did attend this man of God, my friend and brother.

I esteem it a mercy from the Lord that I had the privilege
of being well acquainted with him in the service of truth,
as well as in meetings.
I, with many thousands more, have been refreshed under his living testimonies,
which have dropped upon the tender plants like dew,
or the small rain that nourishes the tender blades.
Oh, the remembrance of it often affects my heart,
and the Lord greatly blessed his labour of love;
for by the power that attended his ministry, many were turned "`from darkness to light,
and from the power of Satan to God.`"^
footnote:[Acts 26:18]

He was a man of a tender spirit, and though not advanced in years,
he was as a nursing father.
Many are witnesses how ready and willing he was, upon all occasions,
to go at any season to visit those who were in distress, either in body or mind,
having a word suitable to their various conditions.
And often at these times, the broken heart was bound up,
and the sin-sick soul was encouraged.

Great was the sorrow and mourning at his decease,
many feeling the loss of such an instrument; but not as without hope.
My hope is firm in the living God,
and I have faith to believe that He will raise up to himself more
witnesses and faithful laborers in the place of those He has been
pleased to remove and take to Himself out of this evil world,
as He has done with this servant who has gone in peace,
and has entered into that rest which God has prepared for the righteous.

In the close of this short testimony for my dear
friend and fellow-laborer in the work of the ministry,
I must say: it is of the Lord, and He is worthy to do whatever He pleases.
All that He does is well done, whether He gives or takes away,
blessed be His name forevermore.

[.signed-section-signature]
Alice Hayes.

--

After the Lord had tried me with exercises of various sorts,
He was pleased to prove me further by persecution for tithes,
both in the spoil of my goods and by imprisonment.
I was taken from my farm and family, having five fatherless children,
and was committed to Alban`'s jail,
where I was kept a prisoner about thirteen or fourteen weeks,
and had many pounds`' worth of goods taken from me
in corn and cattle by the priest and impropriator,
because for conscience-sake I could not (in this
day of the Gospel) pay to support their worship,
nor that anti-christian yoke of tithes.
A testimony lives in my heart,
to encourage all those who are convinced of God`'s truth to be faithful in this matter,
and in all things which the Spirit of Jesus Christ shows them to be evil.

I mention my sufferings, not in a boasting way, but for the encouragement of the weak;
for He that bore up my head under all my trials and exercises will bear
up every sincere and honest soul that desires faithfully to do His will.
I bless God in my very heart that He has counted
me worthy to suffer for His name`'s sake;
and truly I can say,
He never permitted any exercise to attend me where He did not also
assist me with power and patience to go through it.
And His word I have witnessed to be fulfilled, that He has been a husband to me,
and a father to my fatherless children.

It is my desire that all, both rich and poor,
may be faithful to God in all His requirings.
But oh, as it was of old, so it is now,
that unfaithfulness makes the work go on slowly and the journey more tedious.
But, blessed be God,
there is a small remnant who are fully given up to follow their true Shepherd,
Christ Jesus, who has come in the power of His Spirit, and is revealed in a remnant,
who are thereby enabled to stand as witnesses for
God against all hireling preachers and time-servers.^
footnote:[A time-server is one who adapts or conforms his religious
opinions and conduct to the prevailing custom of the times,
or to comply with the present ruling powers.]
For the purpose of God is to set His Son on the top of all hills, mountains of show,
and shadows of religion.
It is my belief, that by the assistance of that grace which comes by Christ Jesus,
many more will be raised to bear witness to the free ministry of the Lamb of God.
And happy, yes, thrice happy, will everyone be, who serves God with all his heart,
and with all his outward substance too, if He calls for it.
Oh, let no one withhold anything that the Lord requires, but remember,
"`The earth is the Lord`'s, and the fulness thereof;
and the cattle on a thousand hills are His,`"^
footnote:[Ps. 24:1, Ps. 50:10,]
and He knows what we need.
If a time of stripping from these outward enjoyments is permitted,
it is but for the trial of our faith.
Oh, that not even one who is thus deeply tried will faint or distrust the Lord,
for His "`care and His eye is over the righteous,
and His ear is open to their prayers.`"^
footnote:[1 Peter 3:12]
And as all come to trust in His name, the God of Israel will care for them,
and appear in a way and by a means they do not imagine.
So He will be found to be "`a God near at hand,
and a present help in every needful time.`"
Therefore, let all that fear His name trust in Him; "`for life is more than food,
and the body is more than clothing;`"^
footnote:[Luke 12:23]
and to everyone that trusts in Him, He will give life for the soul,
and bread for the body; as He has done for me in a wonderful manner.

[.asterism]
'''

The greatest part of the foregoing account was written some years ago;
and having since that time seen much of "`the wonders of the Lord in the deep,`"^
footnote:[Ps. 107:24]
I find a concern upon my mind to add something as the Lord shall enable,
for the encouragement of my offspring, for whom I travail in spirit,
and also for all the babes and lambs of God,
and for the mourners in Zion who travel on under heavy burdens.
For the sake of these,
I am made willing to say a little more of the kindness
of God to the workmanship of His hand,
and to call others to faithfulness from a deep sense of the need there is for it.
And I may say, in great lowliness of spirit, that I have no might of my own, nor power,
nor ability, but what He shall be pleased to give me.
And let nothing be attributed to that monster, self,
which too often appears both in preachers and writers,
and proves like the "`fly in the perfumer`'s ointment.`"^
footnote:[Ecclesiastes 10:1]
I do heartily pray that I may wash my hands in innocency,
and be preserved clean from this fault; and that God alone,
who is the Author of all good,
may have the praise from me and from every creature that has breath.
Wonderful have been His favors and mercies to me above many--one
half of which I am not able to set forth.

What I have seen and felt this year, 1708, is unutterable,
being a year wherein I was led into the depths and
beheld much of the wonders of the Lord,
more abundantly than I am able to express;
nor indeed do I as yet see it required at my hand.
Therefore I shall only give the Lord His praise, and admire His wonderful doings,
for I can truly say, "`it is marvelous in my eyes.`"^
footnote:[Ps. 118:23; Matthew 21:42]

When very weak in body,
I have been led by the Spirit into the low valley of deep humility.
Surely, as there is a coming into nearer communion with Christ the Lord,
there will be a very great abasement in the creature,
and all flesh will be brought to silence in His presence, that His voice may be heard,
and His movements seen in His temple with that majesty wherein He appears.
Oh, excellent it is, and very glorious to behold!
That my soul may continually dwell before the Lord is what
(with great humility and tears) I beg of His bountiful hand.
In the living faith that crowns with victory,
I have a hope in me that as I continue in well-doing to the end, for His Son`'s sake,
I shall arrive at the desired port and haven of rest,
where all the righteous sing hallelujah forevermore.

It pleased the Lord to make known His truth to me about the year 1680,
by that servant and handmaid of the Lord, Elizabeth Stamper;^
footnote:[The sister of Francis Stamper.]
and without boasting, I can truly say that from that time to this,
I have been very careful to obey His holy mind and
will as it has been made manifest to me.
And for the encouragement of others unto faithfulness, I can say that I have not,
since I knew the Lord, been one day without His presence--whether more or less--so that,
blessed be God, there has been no complaining in my streets.
For I have said, and still say, that if there were no future reward,
yet the present comfort of obedience is a sufficient encouragement
to the children of men to fear God and keep His commandments.
Those who do so, will live thereby; that is,
they will live by the life of the Son of God;
for He has indeed come that we may have life,
and it is through obedience that the abundance of His life is known.
And this great kindness of God to mankind is not by any merits of our own,
but of His great mercy and for His Son`'s sake.
Through His precious blood we have all these great benefits which
do accrue to both soul and body in our submission to His yoke,
and in learning of Him, who is the pattern in every age.

Moses, in the mount, did His work according to the pattern, by the wisdom of our God.
David, His servant, gave orders unto his son Solomon and the elders,
how to carry on and build that great house which was glorious in its time.
But how much more glorious is this dispensation of
light and grace which shines from the Son Himself,
the express image of the Father, into our hearts; whereby we may now see our way,
and follow the pattern, and not stumble where so many others have fallen!
Some have stuck immovably in forms and in outward shows of good things,
which were but shadows,
because they will not come to the substance or pattern that is made known by the Spirit,
who is sufficient to teach all things necessary for eternal salvation.
Therefore, if men will stumble here,
it must be because "`they love darkness rather than light,`"^
footnote:[John 3:19]
and in their hearts they prefer to remain spiritually in Egypt, a slave under Pharaoh,
rather than to come to where light and good are to be enjoyed.

Oh, what shall be said to stir up the sons of men,
that they may be awakened and no longer sleep in the bed of ignorance?
Arise, and come away to the school of Christ,
who is this pattern of whom I have been speaking!
He has given a measure of His own pure Spirit to everyone that they may profit thereby,
and learn to read inwardly, and ask so as to receive.
For whatever is asked in faith, and in the measure of His Spirit,
will surely be answered in His own time.
And as all times and seasons are in His hands, so He, in His wisdom,
knows when it will be best to deliver the creature out of trouble,
and bring honor to His own name, who is worthy of all praise;
for He is an all-seeing God, and no affliction or trouble can be hidden from Him.
Yet He must be sought unto and waited upon; and they that know Him will trust in Him.
Truly, these know Him to be "`a God at hand,`"^
footnote:[Jeremiah 23:23]
and "`a present help in the needful time,`"^
footnote:[Ps. 46:1]
as my soul has witnessed.
Glory to His worthy name forevermore.

Oh, you into whose hands these lines may come, be earnest for your soul`'s welfare,
while health and strength of body are afforded.
Seek God with all your hearts,
that you may come to the knowledge of the truth as it is in Jesus Christ,
and witness an acquaintance with Him by waiting on him frequently.
Then, when the time of weakness takes hold upon you, and no worldly means will avail,
you will know the angel of His presence to stand by you till death.
This will be more joy than ten thousand worlds at that hour.
Oh, the strength of His love!
Surely the love of God is to the children of men,
that they may prize their time while they have it,
and make all things ready that appertain to eternal life.
This is to fulfill the purpose of our having a being in this world, namely,
to glorify God, and to "`work out our own salvation with fear and trembling,`"^
footnote:[Philippians 2:12]
which must be done, if ever, in the time afforded unto men in this world.

Therefore be wise, you children of men, and come and learn of Christ.
Follow Him; for He has gained the victory,
and has all power in heaven and earth committed to Him.
Resolve, by the help of His grace, to follow on wherever He will lead you; for assuredly,
He will give you power to tread upon scorpions,
and to keep every foul spirit under your feet.
And in your obedience you will learn to be watchful in the light,
by which you may see every appearance of evil.
Resist it by the assistance of the Spirit, and give it no entertainment.
Remember that you are soldiers under the banner of the unconquered Captain, Christ Jesus,
who has always stood by His own in every age,
so that in faithfulness they went out of this world,
though many have sealed with their blood their testimonies for our God and the Lamb,
who was their Captain, and who brought them off the stage of this world in victory,
bearing His mark.

Oh, why would any not follow the Lord, who can help both outwardly and inwardly,
all who stand for Him and the honor of His name?
For indeed, His name is a tower of safety,
which has stood in power against all the instruments that the devil
has raised up in every age to afflict the children of God!
In every dispensation the evil have troubled the good; yes,
the lion still seeks to tear the lamb, and the wolf hunts for his evening prey.
But glory be to God, the true Shepherd is known, and His power is still felt,
in which all the righteous have trusted to this day.
And the living can now say,
"`His power is the same as it was in the beginning--a canopy over the righteous,
and a safe hiding-place in times of trouble, when instruments of cruelty are let loose,
and the greedy do mischief.`"

Such as swear, lie, cheat, commit adultery, or lead a life in any other evil,
let me prevail upon you to repent and forsake the evil of your ways,
and the sins that so easily ensnare you.
Do the devil`'s drudgery no longer; for he is a bad master,
and the wages that he gives are such as he will receive for his own doings.
Therefore, all you who are at a distance from God by reason of evil,
put it far away from you by a true and timely repentance,
that you may know what it is to be washed with the water of regeneration,^
footnote:[Titus 3:5]
and cleansed from sin by the blood of the Lamb.
Thus you will witness the renewings of His favor,
which will be as the balm of Gilead that will thoroughly heal your wound,
and make you strong and fit for the service of Christ our Lord.
He is the best Master that ever a man or woman served, and He gives eternal life.
But all who come to Him "`must believe that He is
a rewarder of those that diligently seek Him,`"^
footnote:[Hebrews 11:6]
and they cannot serve two masters.
They must renounce the devil, their old master, and all his works,
together with the pomps and vanities of this world.
And, like good soldiers,
they must follow the Captain of their salvation in all perseverance,
through good report and bad report, and keep to the standard--the Spirit of Truth.
If you do this, then you may pray to the Giver for whatever you stand in need of;
let it be bread for the soul or the body, or for faith, hope, courage,
the armor of light, or whatever else your need may be.
Take courage and ask,
and you shall receive double comfort for all the troubles
you undergo for Christ and the Gospel`'s sake.
And in exchange for the life which you have lost (which you had in vanity and evil),
you shall find a life that exceeds it a hundred fold
in peace and inward joy by the Holy Spirit.
Submit to the will of God, who has called you with a high calling,
that you should hear His Son and obey Him in all things unto the end.
Then be good soldiers like that blessed apostle who "`fought the good fight,
and kept the faith.`"^
footnote:[2 Timothy 4:7]
Oh, faithful soldiers, carry on, and be not fearful or fainthearted,
for a woe attends such as these; but be valiant and zealous for truth on the earth,
according to that knowledge which God shall give you.
Be found improving your talents, whether you were given five, two, or one;
however small it may be.
For if your hearts are seasoned with the grace of God,
your delight will be in His treasury,
and you will witness an increase in that which will do you good in the end of your warfare,
whether it be long or short.

If you walk in faithfulness, all will end well.
God`'s care over His children and people is the same in every age.
I am a witness of it, though a poor worm and an unprofitable servant;
for if I have obeyed His command, it is but what was, and is, my reasonable duty.
The Scriptures are verified where it is said; "`His eye is over the righteous,
and His ear is open to their cry;`"^
footnote:[Ps. 34:15]
for He is the God and Father of mercies,
and He delights to meet with His own to do them good.
He takes no pleasure in afflicting the children of men,
any further than to bring them into subjection to His Son,
that thereby they may come to know the state of sonship,
and learn submission to His heavenly will.
His will is that all men everywhere repent, and come to the knowledge of the truth,
and be saved with an everlasting salvation--saved both from sin itself,
and from the wrath due to the same.
This is freedom indeed, to be made free by the Lord of all power, who said to the Jews,
"`If the Son makes you free, then you are free indeed.`"^
footnote:[John 8:36]

Oh, that men would strive for this freedom,
and believe in the sufficiency of that grace that has come by Jesus Christ,
and appears in the heart to convince of sin in its first budding!
By the strength of this grace, sin may be crushed like a viper`'s egg,
and be cast out by the assistance of the Spirit, which is one with the grace of God.
The effect of the grace and the coming of Jesus is indeed to save people _from_ their sins;
and all who are willing to be His,
and to believe that He has all power committed to Him in heaven and earth,
and has the victory over the world, the flesh, and the devil--to these, I say,
He can and does give power.
Stronger is He that is in us (that is,
Christ by His Spirit) than he that is in the world;^
footnote:[1 John 4:4]
and Jesus is more powerful to save, than the devil is to compel men to sin;
for he can only tempt.
Yielding to his temptation brought misery upon our first parents;
and yielding is the cause of misery still.

The second Adam, the Lord from heaven, the Restorer of mankind,
did not say that we would not be tempted,
nor that we would be free from the enemy`'s assaults in the earth;
for here the usurper "`goes to and fro,`"^
footnote:[Job 1:7; 1 Peter 5:8]
and has his food--the earth and the dust thereof.
He that was so bold as to approach and tempt the Lord of glory,
will no doubt assail His followers.
And the Lord, knowing well what we would meet with here,
advised and counseled all "`to watch and pray, lest we enter into temptation;`"^
footnote:[Matthew 26:41]
which is as if He had said, "`If anything that is evil troubles you, touch it not;
but pray to Me and I will assist you;`" so that it is the Lord who works this deliverance.
God must have the praise, who alone is worthy; for His own works praise Him,
being wonderfully made manifest in this age of the
world after so long and dark a night of apostasy.
Blessed be God, who is the Spirit of light and of purity,
and has now eminently broken forth by His Son to
enlighten the children of men in the heart.
His Spirit and great power has been stronger than the power of darkness,
pulling down and spoiling the works of the old adversary, yes,
and binding and casting him out.
And He is fitting His creation together for a heavenly building,
to be as a stone or a pillar in this His latter house,
which God is building of living stones, rejected indeed by the worldly wise of this day,
but approved of God, who is the Chief Corner Stone and Lord of all.

We read of some of old who said, "`What shall we do that we may work the works of God?`"
And the answer (by One who well knew) was: "`This is the work of God,
that you believe in Him whom God has sent.`"
Oh, it is a matter of sorrow to think that men and women should be so slow
of heart to believe in the Son of God in His spiritual appearance within!
But blessed be God, a remnant has believed, and thereby these can cry "`Abba,
Father,`" because He has done that in them, and for them,
by the operation of His mighty power, which no other could do.
By this we know that the Son of God has come and has given us an understanding,
that we may know Him that is true, even "`Christ in us, the hope of glory.`"^
footnote:[Colossians 1:27]
This is as an anchor, sure and steadfast, that has never failed when the wind blew,
or the rain descended, and floods of affliction swelled high.
No, no, it has never failed, for the foundation is a tried one,
a rock immoveable in every age.
All that have built upon it, and so continued, have stood fast and sure;
while those who have built upon sand have suffered
great loss when time has come to an end,
and their foundation has been tried.
Oh, it will be dreadful to go out of time into eternity in the displeasure of a long-provoked,
yet patient and just God, who will be just in all His ways,
and render to all foolish virgins, sandy builders, and slothful servants,
a reward according to their doings, even that sentence pronounced in the Scripture;
"`Depart from Me, you workers of iniquity, I know you not.`"^
footnote:[Luke 13:27]

It makes my heart melt within me to think how dismal a state it is to be banished
from the presence of a glorious God who long strives with men by His good Spirit.
But how is it to be lamented, that far too many have refused the offers of His love,
and have chosen their own ways, and hated to be reformed!
Therefore, great will be the condemnation of such,
and dreadful will be the worm that gnaws when they consider how their time is over,
and that all means of grace are gone.
Then these shall see how they have missed the favor of a good God
by choosing their own ways and doing their own works.
Oh, the lost time!
Oh, the loss of the field, and the treasure also!
Therefore, far better is it to mind the work of God,
that by faith in the Son you may witness Him "`to work all your works in you,
and for you, of His own good pleasure.`"^
footnote:[Isaiah 26:12; Philippians 2:12-13; Hebrews 13:21]
There is nothing for man to boast or glory in.
He is only to be pliable as the clay in the hand of the potter,
till he is made a vessel to His praise.
"`God has no delight in the death of him that dies,
but rather that men should obey His commands and live;`"^
footnote:[Ezekiel 18:32]
or surely, He would not set life and death, good and evil, before them, and say,
"`Choose life.`"^
footnote:[Deuteronomy 30:19]
This seems to render it very plain, that there is a choice for mankind,
and an offer of salvation while in this world;
so that men and women may choose life by believing in Christ;
or they may refuse it by unbelief, which leads from God and the Lord Jesus,
into death and darkness.

But blessed be God, who has brought a remnant to the knowledge of His light,
and to obedience as well.
These are made living witnesses of the sufficiency of His grace,
like the apostle of old who, in great buffetings and temptations,
found grace to be effectual;
though we find he had once been in a state where he cried out, "`Oh,
wretched man that I am, who shall deliver me from the body of this death?`"^
footnote:[Romans 7:24]
And again, "`I am carnal, sold under sin.`"^
footnote:[Romans 7:14]
This was a mournful state with Paul for a season, when sorrow possessed his heart,
and he cried out to God who was able to help him.
And in due time he came to witness the sufficiency
of His grace to bring him out of that state,
and to know a better condition, so that he could say,
"`There is therefore now no condemnation to those who are in Christ Jesus,
who walk not according to the flesh, but according to the Spirit;
for the law of the Spirit of life in Christ Jesus
has made me free from the law of sin and death.`"^
footnote:[Romans 8:1-2]
Oh, the blessed freedom that came to believers in that early day by Jesus Christ.
And blessed be God, it is the same in this day as it was then.
For this grace, which has come by Jesus Christ,
does not only enlighten men and women to let them see their sinful condition,
but also gives power to the soul to come out of captivity.
And so long as their is faithfulness in the creature,
the sufficiency of grace is still witnessed to lead
from one degree of strength to another.

Therefore all have reason to thank God as the apostle did, and to say,
"`In Him there is no variation, or shadow of turning.`"^
footnote:[James 1:17]
For indeed, He is the same as ever He was to all who believe and follow Christ Jesus.
And every faithful follower of Jesus is enabled to say (and
that not boastingly) that revelation has not ceased,
nor is the Gospel hidden, except to those who are lost because of unbelief,
and who will not turn or believe in the light of Christ
and its sufficiency--these must lie down in sorrow.
And to all who assert that there is no state of redemption
from sin to be experienced on this side of the grave,
crying out that they are "`full
of putrefied sores,`" and "`have no soundness in them,`"^
footnote:[Quotations from the liturgy of the Church of England]
these are sad complaints indeed!
But how can it be otherwise while they contend for the devil`'s kingdom, which is sin,
darkness, and confusion?
Oh therefore, let me prevail with all to be reconciled to God by believing in His Son,
whom He has appointed Heir of all things, and who is an Advocate indeed,
by and through whom you may find acceptance.
And blessed be the Lord,
there is a remnant of living witnesses who have believed
in the power of His inward appearance,
in which there is victory obtained over the world, the flesh, and the devil.
Oh happy are the souls that can thus believe in His name;
for these shall be baptized with Christ`'s own baptism--even
the baptism of the Holy Spirit and fire;
that is,
His Spirit and Word entering into their hearts as
a fire against every appearance of evil,
to burn it up and destroy it in its first appearance.

Oh! that the children of men would be wise and fear God,
and call upon His name while the door of mercy is open, that their souls may live.
For this I heartily pray, because I have tasted of the good Word of God,
and have known something of the power of the world to come.
And having tasted both of His mercy and His judgment,
I can do no less than invite and entreat all to be
faithful to the Lord and all of His requirings;
so that, in the winding up of all things,
God may have the praise (who is everlastingly worthy),
and our poor souls may find a joy and comfort that no one else can give or take away.

[.asterism]
'''

Some time after being convinced of the truth in the year 1680,
Alice Hayes was called forth into the work of the ministry,
and concerned to visit the churches in several parts of England.
She also travelled through Holland into Germany, as far as Frederickstadt,
and there had excellent service for the Lord.
Many were reached and convinced by her ministry,
it being in the demonstration and power of the Spirit.
About the year 1712, she moved from Hertfordshire and came to settle in Tottenham,
and Friends felt true unity with her both with respect
to her innocent and exemplary life and conduct,
and also her gift in the ministry,
in which she was made very serviceable for the encouragement
of Friends to faithfulness in every branch of their testimony.

Being at the Yearly Meeting in London, in the year 1720, she was taken ill;
but her love being strong to her Friends there, she stayed some days,
and then returned to her house at Tottenham,
where she grew weaker and weaker until she quietly departed this life like a lamb.
During the time of her sickness she gave much good advice and counsel to her family,
as also to others who came to visit her,
dropping many sweet comments regarding her comfortable enjoyment of the Lord`'s presence;
some of which follow.

At one time a Friend of Tottenham coming to visit her, and others coming in, she said,
"`Oh, love one another, and may the Lord make you a living people unto Himself,
and preserve you in perfect love and unity.
I am,`" said she, "`in perfect love to all people.`"
She then desired Friends to "`give her up freely to her God;`" saying,
"`I am willing to die, and I hope it will not be long.
But, oh, I desire to go exactly in the Lord`'s time.
And all that I desire is that the Lord`'s presence may be continued unto me,
and then I fear not the awful hour of death.
My God is my resurrection and my glory.
He is my strength and my refuge, and I am thoroughly resigned to His will;
and in but a little time my soul shall sing praises
to the Lord on mount Zion with all the redeemed,
out of the reach of trouble.`"

Some Friends having come to visit her at another time,
she broke forth in a tender frame of spirit, and said, "`I now wait upon my God;
and He is a God of everlasting lovingkindness,
and has been good to my soul all my life long.`"
She then said, "`Friends,
do not put off making your peace with Him till you come to a dying bed.
There is enough to do now to labour under the afflictions of the body;
I would not be without the favor of God now for all the world.
May the Lord, the God of Abraham, of Isaac, and of Jacob, my God and your God, bless you,
and be a God to you in all your trials, for He has been so to me;
a sufficient helper in times of trouble.`"

Several young people being with her at another time, she tenderly advised them, saying,
"`Be good, and serve God faithfully,
and do not put off the great work of your day to the end;
but timely prepare for your dying hour, that you may have oil in your lamps,
and be in readiness whenever that time shall come.
It has been the joy of my heart to go to meetings, and to meet with the Lord there.
But oh, much more joy will it be to my soul to meet with Him in heaven,
and to have a place in His kingdom.
Through mercy, I am under no terror of death, but am in true peace.
Blessed be my God forever, His goodness is exceeding large.
I would like to praise Him for His goodness, but I am very weak; and I desire,
if it be His will, not to see the light of another day, for my affliction is great;
but let all be in His own time.`"
She then broke forth in prayer, requesting that her passage might be made easy,
and desiring to be supported under her affliction which at times was very sharp.
Yet she bore all with great patience, looking to the Lord, her comforter,
under the deepest provings, and often saying, "`Oh, Lord Jesus, receive my spirit,
for I long to be with You my Savior; yet let me not offend You,
but patiently wait Your time.`"

A few days before her death,
some Friends of Tottenham sat down to wait upon the Lord God with her.
His love was largely manifested and sprung up as a fresh spring;
and after a Friend had been led forth in supplication, she broke forth and said,
"`Oh the love!
This is love that may be felt!
My God, your goodness is wonderful,
and my soul praises You for the overflowing of Your love
at this time;`" with many more sweet and heavenly expressions.
She tenderly acknowledged the kindness of her friends in their visit,
and took leave of them in brokenness of spirit, desiring that "`the Lord be with you,
and strengthen you to be valiant for His truth,
and to keep your meetings in His name and His power;`" saying, "`Oh,
what comfortable times we have often had in our weekday meetings!
How have our cups overflowed with the love of our heavenly Father!`"
After this, she exhorted all "`to abide in the unity of the Spirit of Christ,
every member keeping in their proper place,
being concerned for the honor of truth in maintaining good order in the church.`"

At another time, near her end, she requested that those around her,
when they should see her taking her final breaths,
be very still and inward with the Lord in their spirits,
praying that she would have an easy passage.
She then added, "`All will be well.
I am going home.
I am going home.
I am done with the world, and all that is in it.
But pray that the Lord may pour out His Spirit upon a young generation,
that they may serve Him in cleanness of heart.`"
She then said, "`I have fought the good fight,
and shall obtain the crown immortal;`" adding "`My beloved is mine, and I am His.
He is my all in all.
Into your arms, Lord Jesus Christ, I offer up my soul and spirit.`"
The last words she was heard to say (her voice being soft) were,
"`The Lord my God will help me.`"

She departed this life the 8th day of the seventh month, 1720,
aged about sixty-three years, and was buried the 13th of the same,
in Friends`' burying-ground, at Winchmore-hill.
