== Chapter 12

[.chapter-synopsis]
* Mary Proud
* John Conran
* Mary Fairbank
* Deborah Backhouse
* Elizabeth Bludwick
* Ruiter Sholl
* Susanna Whitrow

MARY PROUD was born in the Fourth month, 1742, at Ross in Herefordshire.
She was the daughter of Rowland and Elizabeth Jones,
who were Friends of exemplary conduct; her mother was a minister in good esteem.
Being left a widow with four small children,
and only a little business for their support,
she consented to part with her daughter Mary, when about fifteen years old,
who came to reside with a near relation in London.
Whilst there, her youthful mind, through unwatchfulness and the prevalence of temptation,
was captivated with the delusive vanities of the present life.
Being, at times, subject to the company of some who did not profess with Friends,
in her twentieth year she accepted an offer of marriage from a young man,
not a member of our Society, but a sober, religious character,
with whom she lived about five years.

But it pleased Divine Wisdom to mar her pleasant prospects of happiness in this life,
for in the short space of four months,
an affectionate husband and their two children were taken off by death.
Thus rendered desolate, she felt as one without hope,
and her inward and outward afflictions considerably impaired her health.
But as she patiently submitted to the chastening of the Lord, she was comforted,
and through the redeeming influence of a Saviour`'s love, she witnessed,
in an unexpected season, the weight of her transgressions to be removed,
and her mind became settled in a peaceful calm.
The subject of this memoir, now Mary Malham, left London, and returning to Ross,
was joyfully received by her valuable mother.
Her mind was about the same time,
strongly impressed with an apprehension that she was called to the work of the ministry;
to which, after passing through deep baptism of spirit, she gave up,
as one who was made willing in the day of the Lord`'s power.

Some years afterwards, viz., in the year 1775,
she was united in marriage to William Proud, of Hull, where they resided for many years;
but towards the decline of life removed into Essex.
Shortly after this she was again left a widow,
and survived her husband upwards of twenty years.
At different periods of her life, she visited as a minister various parts of this island.
In this character she was patient in exercise and deep in travail,
for the arising of the Divine power;
being concerned not to speak but from the renewing of the Holy Spirit.
She was endued with a good natural understanding,
which inclination and a sense of duty led her to cultivate by reading and meditation:
this rendered her an instructive companion:
and being affable and courteous in her manners, she was much beloved.
As her heart was enlarged by Christian love,
her desire for the temporal and spiritual welfare of all was manifested,
and this was shown in an especial manner,
by the interest which she discovered in the advancement of the kingdom of Christ,
both at home and abroad.
She was much concerned for those under suffering, contributing liberally for their relief.

In the Fifth month, 1823,
whilst engaged in the ministry in a monthly meeting at Halstead,
Mary Proud was perceptibly affected with paralysis.
She was removed home that afternoon, but was unable to speak:
the composure of her countenance, and other tokens of mental introversion,
showed that her affections were fixed on heavenly things, to the enjoyment of which,
if in accordance with the divine will,
she greatly longed that her spirit might be speedily admitted.
When the faculty of speech returned,
it was employed on subjects appertaining to the great work of salvation.
To a friend she said: "`I am thankful that the enemy is turned backward.`"
These few words she revived in the hearing of many visitors,
affectionately entreating her younger friends that they would, through Holy help,
withstand his suggestions,
when they would witness all the snares laid for them to be broken; adding,
in the language of encouragement: "`The city, the strong city!
The city, the strong city! flee unto it!`"
From this state of weakness this dear ancient friend so far recovered
as to be generally able to attend meetings at and near home,
and also the two succeeding yearly meetings in London;
yet she experienced considerable bodily infirmity,
which was endured with Christian resignation.
On the 3rd of the Fourth month, 1826, the monthly meeting occurred at Kelvedon,
the place of her residence.
In the meeting for worship,
she was strengthened eminently to advocate the truths of the Gospel;
but returned home much exhausted, before the meeting for discipline was concluded,
remarking, "`That it would be the last.`"
Soon after this, her debility greatly increased;
yet she came downstairs until within a week of her death,
and felt satisfaction in receiving the visits of her friends.

During this last and short illness,
deep and proving were the spiritual conflicts which
Infinite Wisdom permitted her to pass through.
But after a season of mental trial, she spoke as follows: "`My God, my glory! this,
not in the letter, but in the spirit: how precious the feeling!
My God, my glory!
I have mourned his absence.
He regarded it, and regarded me, though I felt myself entirely unworthy of Him;
but he is returned, and I can now sing of his goodness from my youth up,
and speak to his praise.
Oh! his mercies have been beyond all count, daily, hourly,
and oftener than the hours of the day.`"
Saying at another time, "`I believe in that testimony, '`Having loved his own,
He loved them unto the end.`' There seems nothing in the way: do not desire my life,
but pray for my release: though my sufferings are great,
yet they are as nothing compared to the joys in prospect-endless joys.`"

The last day of her continuance on earth, she remarked:
"`This is my dying day;`" and in the forenoon, being raised in her bed,
a solemn silence prevailed,
under which she breathed forth a few sentences with feeble accents.
First, a song of thanksgiving for the precious in-breaking of the Divine presence,
previous to the putting off of mortality; an humble petition,
that the blessing of heavenly preservation might rest upon survivors;--and concluding
with the solemn ascription of praise unto Him who is everlastingly worthy.
Her peaceful close took place the same night, the 23rd of Fourth month, 1826,
at the advanced age of eighty-four.

[.asterism]
'''

JOHN CONRAN was born in the city of Dublin, in the year 1739.
His parents professed with the established Church of England,
and being in easy circumstances, they provided him with a liberal education,
and afterwards placed him as an apprentice with a person in the linen trade at Lisburn.
In this situation he was much exposed to unsuitable company,
and drawn into many youthful dissipations,
for which he was in mercy soon permitted to feel condemnation;
and being led to examine himself, his secret breathings began to be after God.
He became more diligent in the attendance of public worship,
and zealous in those practices and observations in which he had been educated.

But he still found that he had to lament over the evils of his own heart,
and to see that he had not attained to that knowledge of God, and that inward purity,
which he considered as essential to a truly religious life.
He secretly cried for deliverance; sin became a heavy burden;
he gradually forsook the amusements in which he had indulged; sat much alone;
and in reading the Holy Scriptures,
they were often made a means of comfort to his tribulated soul.
Thus, in stillness and retirement,
he was led into an increasing dependence on Divine instruction.
Whilst in this awakened state of mind, when about the thirty-third year of his age,
he attended a quarterly meeting of Friends at Lurgan,
where he was affected in an extraordinary manner by the ministry of Robert Willis,
of America, who was then on a religious visit in Ireland.

Although on terms of intimacy with several members of our Society,
he had previously felt dissatisfied with our principles;
but now the power of the Lord so broke in upon his soul,
that his views were completely changed,
and under a firm conviction of the rectitude of the measure,
he soon afterwards fully embraced the doctrines and views of Friends.
This, however, occasioned him many deep conflicts of spirit.
He often looked back on his former course of life,
and felt the Divine judgments for transgression: thus,
having experienced the terrors of the Lord for sin, he became willing to persuade men.

In the year 1780, John Conran first spoke as a minister of the Gospel.
Being deeply impressed with the solemn nature of the engagement, he was concerned,
in the employment of the gift entrusted to him,
to move under the influence of the Holy Anointing;
and continuing in watchfulness and humility, and in reverent waiting upon God,
his ministry was often delivered under the baptizing
power of the High-Priest of our profession.
Although he frequently spoke but for a short time, it came with Divine authority,
conveying counsel and reproof to the disobedient,
and comfort and strength to the drooping mind,
and to such as were seeking the way to the kingdom of heaven.
He had, at seasons, to endure great poverty of spirit,
and in this way was experimentally qualified to speak to this condition in others.
The doctrinal truths of the New Testament were often the subject of his communications:
he was concerned to draw his hearers from all types and shadows,
inviting them to Christ the substance,
by whom the true and faithful believers being nourished,
are enabled to die daily to the impurities of flesh and spirit,
and to live unto God through Him who died for them.

In the exercise of the discipline of our Society, our departed friend was very useful.
He was zealously concerned for the support of our religious character as a body,
in its original purity,
and for the preservation of his fellow-members in soundness of principle,
and consistency of practice.
Through the aid of Divine grace,
he stood with Christian firmness against that spirit of unbelief
which at one period was very prevalent in the north of Ireland,
when many in our religious Society sorrowfully departed from the truth as it is in Jesus.
This was a time of great distress to him;
but he was emboldened to avow and to maintain his belief in the
efficacy of the propitiatory sufferings and death of Christ,
of the redeeming power of our blessed Saviour; and under all,
gave abundant proof that his first desire was,
to be found faithful to the commission which he had received,
as a good steward of the manifold grace of God.

He scrupulously allotted a portion of each day to religious retirement,
and endeavoured also to maintain, in social intercourse with his friends,
a watchful attention to the guidance of the Holy Spirit.
His conversation was thus sometimes rendered strikingly instructive; yet,
when to others he might appear to be highly favoured, he often remarked,
in true humility, that he was but an unprofitable servant;
that to him belonged nothing but blushing and confusion of face.
He was a man of a grave and serious deportment,
endowed with a good understanding and sound judgment;
and his advice in matters of importance was much valued.
He laboured fervently to impress upon his friends,
the necessity of not being conformed to this world;
and illustrated this doctrine by his own example,
sacrificing things of a secular nature which stood
in the way of performing his religious duties.

In the year 1805, he was deprived by death of an amiable and tenderly-beloved wife;^
footnote:[See [.book-title]#Part 10# of this work.]
this, with other subsequent domestic afflictions, of a peculiarly trying nature,
he was enabled to bear with Christian resignation.
He repeatedly visited the meetings of Friends in Ireland,
and was diligent in attending all those for discipline of which he was a member;
and was several times at the yearly meeting in London.
In the autumn of 1819, when nearly eighty years of age,
he united in a religious visit to the families of Friends in the city of Dublin,
and was strengthened to perform this arduous undertaking
much to the satisfaction of his friends,
and the peace of his own mind.

In endeavouring to excite his brethren to greater devotedness to the service of the Lord,
he would say in substance, "`I serve the best of Masters, who,
I can testify from long and precious experience,
withholds no good thing from those who faithfully obey Him;
and though I have not suffered my outward affairs
to prevent me from attending to my religious duties,
yet even these have not prospered the less; for now, in my declining years, I am,
through mercy, favoured, with more than a sufficiency,
having a little to spare for the relief of others.`"
During his long life, he was permitted to enjoy almost uninterrupted health;
and when the powers of nature were evidently giving
way under the pressure of advanced years,
his spiritual faculties were preserved in extraordinary brightness;
and the promotion of religion in our Society, and in the world at large,
was still dear to his heart.
His death, which was sudden, and rather unexpected at the time,
took place on the 14th of the Sixth month, 1827,
at the house of his kind friend Thomas Christy Wakefield, at Moyallen,
where he had resided for the last few preceding years.

The day before his decease, when in his eighty-eighth year,
he was at the week-day meeting, in which he was engaged in the ministry,
strongly pressing upon his friends to be diligent
in attending their meetings for worship and discipline,
and instructively commenting upon the parable of the supper;
warning them to be careful how they neglected calls from heaven; and saying,
in the course of his exhortation, "`I now again tell you, what I have so often declared,
that other foundation can no man lay than that is laid,
which is Jesus Christ;`" and when about to take his seat, he stepped forward,
and after a few words, closed with this devout acknowledgment,
"`For the many mercies I have received, I praise, honour and magnify, my God.`"
Thus terminated the Gospel labours of this aged and
honourable valiant in the Lamb`'s warfare;
and there is no doubt, that through the redeeming mercy of Him whom his soul loved,
he has been admitted to "`an inheritance incorruptible, undefiled,
and that fadeth not away.`"

[.asterism]
'''

MARY FAIRBANK.--In compiling this volume, an opportunity has been instructively afforded,
to survey the character of more than a few, who, from early to advanced age,
have endeavoured to walk in the path of the just.
The lives of these have convincingly shown,
that there is an efficacy in the religion of Jesus, which sustains the faithful,
though tried disciple,
and enables him to look in humble faith to that Almighty Benefactor,
who richly rewards all that diligently seek Him.
Such may not have spoken of very bright prospects of future bliss; but the steady,
heavenward tenor of their course, has shown on whom their hopes of salvation were fixed,
and that to them the gracious promise was one of consoling reality,
"`Be faithful unto death, and I will give thee a crown of life.`"

In this number may be included Mary Fairbank,^
footnote:[See page 141 of this work.]
who died at the advanced age of eighty-eight.
She was the widow of William Fairbank, of Sheffield;
and they were both Friends highly esteemed in that meeting.
They early entered upon the narrow way which "`leadeth unto
life,`" and their affections being set on things above,
they were moderate in the pursuit of earthly possessions;
but being concerned to seek first the kingdom of heaven and the righteousness thereof,
found that all things needful were added.
They entertained their friends with much Christian hospitality,
and their house was especially open to such as were
travelling in the service of the Gospel.
They were of sound judgment, and were both in the station of elders,
and well qualified for usefulness in the conducting of the discipline.
A considerable portion of their time was also allotted to the service of the church,
in their own meeting, and in the large quarterly meeting of Yorkshire: a duty which,
when properly discharged, involves no inconsiderable occupation of time and talents;
whilst the right performance of it greatly contributes, under the Divine blessing,
to the well-being and prosperity of our Society.

Mary Fairbank survived her husband nearly twenty-six years, and though she deeply felt,
through the remainder of her life, the dissolution of this endearing tie,
she continued to cherish a lively interest in the welfare of her friends;
amongst other duties, watching over the ministry,
and encouraging and counselling the young and inexperienced, as a mother in Israel.
Her frank and courteous manners,
and liberal sentiments towards those who differed from her in religious profession,
were striking and attractive.
Her labours of love were not confined to our Society;
but her charity and sympathy extended to those whom she knew to be in suffering.
To the poor-around her she was a kind and feeling friend,
and a promoter of various useful establishments for their good;
and many years before the education of their children
became so popular as we may rejoice that it now is,
she exerted herself in this benevolent work.

She had seen great changes in the meeting of which
she had been a member nearly seventy years;
and survived most of those with whom she had been
associated in the more active years of life.
The loss of these did not bring with it gloom or repining;
and she found in others less advanced in age,
those whose Christian friendship she valued,
and to whom her society and example were animating and instructive.
That humble trust in God, which had been her support through life,
was mercifully continued, and was an anchor to the soul.
Her energy of mind and cheerfulness of disposition were but little, if at all, abated.
She took a lively interest in what was passing;
and it afforded her sincere delight to hear of devotedness
to the service of her Lord and Saviour,
both in and out of our religious Society.
She was, at the same time, no stranger to conflicts of spirit on her own account,
and not insensible to the trials and sorrows which
the faithful followers of Christ have to endure,
in mourning over those who do not come up in their ranks in righteousness,
or who fall away from that to which they had attained.

As the termination of life approached,
her tranquillity under the trials incident to humanity,
gave fresh evidence of the certainty of that support on which she had long depended.
Her mind appeared not unfrequently to be borne above the infirmities of advanced age;
and gratitude and praise were often the prevailing feelings of her soul;
at the same time she manifested great humility, often saying,
that she had nothing to boast of;
but to feel no condemnation was a favour for which she wished to be sufficiently thankful.
Thus waiting the Lord`'s time, she died on the 22nd of the Sixth month, 1827.

[.asterism]
'''

DEBORAH BACKHOUSE was the daughter of Richard and Elizabeth Lowe, of Worcester.
Being deprived of her father at a very early age,
the care of her education devolved solely upon her mother,
who was piously concerned to train up her children in the right way of the Lord:
desiring much more that they might become possessors of heavenly riches,
than of any thing of a perishable nature.

The tendency of Deborah`'s mind is said, by herself, to have been such as to require,
in early life, much parental restraint;
and she has often feelingly acknowledged the benefit she derived from it,
and the influence which her mother`'s Christian example
and instruction had upon her future character.

When about twenty-five years of age, she had a serious attack of pulmonary disease;
and though evidently not then a stranger in the school of Christ,
there is reason to believe,
that this dispensation tended to deepen her in religious experience.
By continued submission to the baptizing power of the Holy Spirit,
she was prepared to labour for the edification of others,
and spoke first as a minister in the year 1819.
Her communications were neither long nor frequent; but they were clear and instructive;
manifesting great care that she might not minister
otherwise than through the ability which God giveth.

In the year 1822, she was married to James Backhouse, of York.
Her delicate state of health often rendered her incapable of much active exertion;
yet her zeal for the cause of Truth showed itself by acceptable gospel labours,
and a humble, watchful deportment.
She was diligent in attending to the state of her own family,
and endeavoured to suppress in her children, from very early life,
the appearances of self-will,
being mainly anxious that their tender minds might
be imbued with the fear and love of God.
In the management of domestic affairs she was orderly and industrious, rising early,
and directing her household by the law of kindness and discretion.
She was diligent in perusing the Holy Scriptures,
and particularly careful that the servants should not be prevented
from attending at the daily reading of them in the family.

After the spring of 1827, she was unable to attend our religious meetings;
and in the course of the summer and autumn, her disorder, which was a consumption,
made considerable progress, and left but little hope of recovery.
In this prospect,
she was for a time tried by the absence of that sense
of Divine support which she had often experienced,
and felt incapable of attaining that state of resignation which she so much desired.
But she was enabled patiently to wait upon the Lord,
and He was pleased to strengthen her cheerfully to adopt the language, "`Not as I will,
but as Thou wilt.`"
During the last month of her life, whilst her bodily strength was decreasing, her hope,
and faith, and love, became stronger;
and she spoke much on what the Lord had done for her soul,
and earnestly exhorted those around her to take up the cross of Christ,
and attend to the manifestations of his Spirit.

At one time she said, "`I feel myself to be a poor, weak creature,
nothing but a poor worm; and that it is through Divine grace alone,
as it has been measurably attended to, that I have been made any way tolerable.`"
She then earnestly enjoined all around her,
to be very careful not to say a single word that
could possibly attribute any thing to her;
again emphatically saying: "`I am nothing at all but a poor worm:
I have not one scrap of my own; no, not one scrap to trust to.
It is of Divine grace and mercy,
that I am permitted to feel such a portion of inexpressible peace.
For some time past I have seemed free from condemnation,
and have felt comfort in having endeavoured to serve the Lord,
and in doing the little I have been enabled to do for the cause of Truth.`"

She spoke of her deep concern,
that her beloved children might be trained in the fear of the Lord,
and instructed in Divine things; that their tender minds might be closely watched,
and everything withheld from them which would encourage pride,
or any other wrong disposition: remarking,
that she considered children as a very important charge,
and that a great weight of responsibility attached to parents to whom they were committed.
She spoke much on the necessity of keeping to the simplicity of Truth,
in what may be termed little things; saying,
"`I have seen and found that nothing else will do.`"
She longed, that if her dear children should live to grow up,
they might be made as lights in the world;
and said that she had never desired much of this world`'s goods for them,
but only a sufficiency to live in a plain way; that she dreaded the idea of riches,
knowing they were often a great source of temptation.
She then committed her beloved husband and children to the care and keeping of the Lord.

During most of the day preceding her death,
she seemed as if on the confines of eternal glory,
and her hands and eyes were frequently raised in the attitude of adoration.
On several of her relations, and a few other friends coming into the room,
a solemn silence ensued, which she broke by the following expressions,
in an audible voice, "`Surely I believe that the everlasting arms of God,
through Jesus Christ my Saviour, are stretched forth to receive me.
I feel the showers of heavenly love falling around us.
What can be comparable unto this!`"
After another pause, she said:
"`I have a clear view of the outward sufferings of our blessed and holy Redeemer.
Oh! let me adore!
All this for poor, fallen, lost man, that he might be saved.`"

Being requested to take a little water, and finding great difficulty in swallowing,
she said with a sweet and animated countenance:
"`I shall soon be led to living fountains of water,
where I shall drink everlastingly without fear of difficulty.`"
After this she was brought under considerable exercise of mind,
and expressed a belief that it was right for her
to wait "`in the Light,`" to discover the cause.
In a short time she remarked,
that there were some little things in her own house and family,
which were not enough in the simplicity that Truth requires,
which had she been sufficiently attentive to the manifestations of Divine light,
would not have been given way to.
She appeared closely to scrutinize every little thing; and again testified,
that if the light were attended to,
it would clearly show what was or was not in conformity to the Divine will.
She acknowledged in a humble, moving manner,
her regret at not having been more faithful in these matters, saying: "`Yes, Lord, I see;
and if I had paid more attention to the Light, I should have seen long since.
I do most sincerely repent and implore thy forgiveness.`"
Some time after, she remarked to her husband,
that she again felt the showers of heavenly love descending as before.

In the course of the night, she fervently supplicated thus:
"`O gracious Father! be thou pleased to help me in this trying hour,
and be near to preserve and support me from bringing
any shade upon thy holy Truth;`" adding,
shortly after, "`I believe Thou wilt not leave me nor forsake me unto the end.`"
In the morning of the following day she said to one of her husband`'s sisters:
"`O! my dear sister, help me to praise the Lord,
for He has given me the victory over death, hell, and the grave.`"
During the remaining time of her continuance, it appeared as if all was joy and peace,
not interrupted even by bodily suffering.
She passed quietly away, on the 10th of the Twelfth month, 1827,
at the age of thirty-four; and her spirit was added, we cannot doubt,
to the redeemed of the Lord.

[.asterism]
'''

ELIZABETH BLUDWICK, wife of John Bludwick of Warrington, was a native of Cheshire.
In early life her deportment was serious and orderly;
and through the influence of Divine love she became, when further advanced in years,
more deeply impressed with the importance of her eternal interests;
and by increasing attention to the teachings of the Holy Spirit,
she grew in religious experience.
She and her husband were both much esteemed by their friends,
for their conscientious endeavour to walk as became their religious profession;
and for their devotedness to the service of our Society,
and their lively concern for the support of our discipline.

Elizabeth Bludwick was at times concerned to labour as a minister in our religious meetings.
Her communications were not long;
but they were expressed under the influence of Gospel love, and very acceptable.
She had often to recommend inward waiting upon God, and dedication to Him;
engagements of mind which, she could say from experience, had been blessed to her.
For many of the latter years of her life, she suffered much from bodily disease;
but her patience and sweetness of spirit increasingly endeared her to her friends.
She survived her husband about two years; and though in advanced life,
and in a very weak state of health, frequently attended her own meeting.
She often expressed her desire to be able to bear her suffering with patience;
and though tried with poverty of spirit and a sense of her own unworthiness,
it was obvious that she was often favoured with a
consoling evidence that her gracious Lord would,
in his own time, remove her from her present conflicts and sufferings,
to an inheritance in his heavenly kingdom.

On the 7th of the Twelfth month, 1827, she remarked:
"`I wish the friends of this meeting to be told,
that there is a new song for the righteous, a song of praise:
salvation hath God appointed for walls and for bulwarks.`"
To a friend who called to see her, about three weeks before her death,
she expressed her desire to be dissolved, and said, "`Oh! that I had the wings of a dove,
that I might fly away and be at rest.
I have a well grounded hope, that whenever I put off mortality,
I shall put on immortality and eternal life,
and that this will be my portion and habitation forever.`"
Being in extreme pain, she prayed, "`O Lord, if it be thy blessed will,
be pleased to send the guardian angel of thy presence,
to conduct my poor soul to its mansion.
Thou only knowest my sufferings, and art able to deliver me out of them all.`"

On another occasion, she intimated, that her being saved was of mere mercy,
having no righteousness of her own to depend upon.
When it appeared probable that she would not continue much longer, she observed:
"`I shall die in peace with all, feeling inexpressible love to every one.`"
And again, she said: "`Now, Lord, let me depart in peace,
for mine eyes have seen thy salvation.`"
In this heavenly state of mind she was permitted to look towards
an exchange of the trials of time for a peaceful immortality.
She died the third of the First month, 1828, at the age of eighty.

[.asterism]
'''

RUITER SHOLL, son of John and Elizabeth Sholl, of London,
was educated at Ackworth school; and in the Eleventh month, 1824,
was bound an apprentice to Joseph Hargrave, of South Shields.
In the early part of the time of his apprenticeship his conduct was very satisfactory,
and he highly valued his situation.
At South Shields no members of our religious Society resided,
except those of his master`'s family; and as he grew up,
he became acquainted with other young persons,
and showed some unwillingness to submit to the restraint
which a conscientious master thought it right to exercise:
at the same time, it does not appear,
but that his general conduct was such as to ensure
to him the esteem and regard of the family.

In the year 1827, he became unwell from the effect of cold,
and the complaint gradually settled on his lungs.
In the Sixth month he came to London; and in the course of the summer and autumn,
various means were tried to promote his recovery.
Towards the latter end of the year, some amendment took place;
but it was only of short continuance,
and it became obvious that he could not long survive.
Up to even so late a period,
very little had been said to him of the danger of his situation,
and he evidently appeared to avoid any conversation of a religious nature.

In the course of the Twelfth month, a kindly interested friend called to visit him,
who found him very weak, suffering from acute pain in the chest,
and his appearance indicated the near approach to the house appointed for all the living.
He received the visit with marks of satisfaction.
The family were collected, and a portion of Scripture was read:
feelings of great solemnity prevailed,
and the visitor felt it to be his duty to apprize the invalid of his condition,
expressing an earnest solicitude that the great work
of sanctification and redemption might be effected;
and turning the attention of his young friend to Him from whom saving help cometh;
to the sacrifice of Christ, and the meditation of a crucified Saviour.

From this time, his mind was much occupied with the prospect of death:
the certainty that his immortal spirit must soon quit its earthly tabernacle,
and appear before its Almighty Judge, deeply affected him;
and he ardently desired to be prepared for the final change.
Although he was enabled to state,
that he had been preserved from the commission of any "`gross sin,`" yet his
associating with some whose conduct was not under the control of religious principle,
had tended to lead him astray from obedience to the
will of God inwardly made known unto him;
and the consciousness of moral rectitude alone,
was insufficient to support his mind at this solemn moment.
Excellent and indispensable as morality of life is,
it is only as we come to pass from a state of nature to a state of grace,
and our souls experience the renewings of the Holy Ghost,
that our conduct amongst men will redound to the glory of God,
and be viewed with acceptance in his pure and holy sight.

Great were the sufferings in spirit which this young man had to pass through;
forcibly pointing out to those around him,
the necessity of submitting to the power of the cross of Christ.
Whilst under these inward baptisms, he received a visit from two friends in the ministry,
who expressed their belief, that, through redeeming mercy,
a place of rest was prepared for him;
but notwithstanding their bright prospects concerning him,
his soul continued to be deeply tried.
He was often engaged in mental supplication,
and besought his Heavenly Father to permit him to see a little light upon the path.

These trials and conflicts of mind continued until First-day,
the 13th of the First month, 1828, when, in condescending mercy,
the cloud of distress and doubt was dispelled, and the cheering prospect presented,
of an admittance into a mansion of eternal rest.
His mind became composed and tranquil.
He spoke to his parents, brothers and sisters, in terms of gratitude,
and of solicitude on their behalf; saying at one time to his mother:
"`My dear and tender mother, do not grieve for me; but think of the blessed change,
when I shall be freed from my bodily sufferings,
and be permitted to have a mansion in heaven, where I shall behold my Saviour`'s face,
there to join with angels, in singing hallelujahs forever and ever.`"
He was now so weak, that he could scarcely raise himself in his bed without assistance,
and he often begged to be released.

The fear of death appeared to be taken from him,
and he could look forward without dismay,
being comforted in the hope that all would be well; often saying:
"`Oh! that my hour were come: I want to be gone.`"
He was much interested on behalf of one of his school-fellows,^
footnote:[This young Friend died a short time after.]
and on one occasion said to him in substance: "`Be very guarded in thy conduct;
the enemy is constantly devising mischief.
Thou art in a very dangerous and critical situation; lay thy soul open to thy Redeemer,
and put thy trust and confidence in him.
I am going to where I shall behold the face of my Redeemer.
He has guarded and watched over me.`"
He frequently said with much feeling: "`Oh! for patience.
Father of mercies, grant me a little ease.
Oh! grant a little ease; and if it be consistent with thy gracious will,
preserve me in patience to the end.`"

At one time, when his parents and a friend were present,
in feeble accents he besought the Almighty to have compassion upon him, saying:
"`Have compassion upon me, a poor sufferer;
and if it be consistent with thy good pleasure, take me to Thyself.
Wash me, and make me clean in the blood of thy dear Son;
and do Thou be pleased to take me to Thyself.`"
He also prayed on behalf of his beloved mother,
and concluded with grateful acknowledgments for the
blessings which had been bestowed upon him.
At another time, he said to one of his brothers:
"`I am now favoured with a clear prospect that when the change shall take place,
there is a mansion prepared for me in the kingdom of heaven.`"

To a friend, who called upon him a short time before his death,
he conversed on his having been placed at a distance from home; saying,
that he had felt much exposed, and, as it were, alone;
but that he was favoured with preservation from many
of the vices which he saw around him,
for which he felt very thankful: adding, that he recollected, when walking out alone,
he frequently endeavoured to look forward, and form plans for the future,
when out of his apprenticeship;
but that upon these occasions he always felt a check in his mind,
so that he could not proceed, of which he now clearly saw the cause.
Speaking of his approaching dissolution, he remarked,
that he felt no obstacle in the way; but that his desire was,
to be favoured with patience to await the time.

In this state of mind, and with but little apparent alteration,
he continued until the 20th of the First month, 1828.
Having passed a restless night, he was much exhausted,
and requested to be placed in an easy chair.
Soon afterwards he was heard to say: "`If consistent with thy holy will,
be pleased to release me from my sufferings, and take me to thyself.`"
He then raised his eyes, and faintly uttered: "`It is done,
oh! it is done,`" and thus passed peacefully away.
He was in the nineteenth year of his age, and,
until the period at which he was attacked with cold,
enjoyed an almost uninterrupted share of health.
The prospect of such an early termination of his earthly course,
appears to have been far from his thoughts.
Let us, then, who survive, seriously reflect upon the uncertainty of life,
and the awful situation of such as are suddenly called hence in an unprepared state.

And although there is good ground to believe this was not the case
with him whose steps we have briefly traced to the hour of death;
yet, had he attended more early and diligently to the visitation of the love of God,
and the reproofs of his Holy Spirit,
he might have escaped much of the distress through which he had to pass.
Other instances have been set before us in this volume,
which show that none ought to presume on lengthened days.
We are not to expect favour or acceptance with God, if we continue in sin:
the forgiveness which has been mercifully granted to others,
is no security that it will be alike extended to us.
May all, then, seek with increasing diligence,
an establishment upon the sure and immutable foundation, Jesus Christ, the rock of ages,
who liveth and abideth forever!

[.the-end]
THE END OF THE ELEVENTH PART
