== Chapter 2

[.chapter-synopsis]
* William Hornold
* William Crouch
* Robert Hill
* Anne Humphreys
* Joseph Stone
* Mary Turner
* Thomas Dockery

WILLIAM HORNOLD dwelt near Radcliff-highway, in the county of Middlesex,
when the Lord was pleased to qualify and call him into the work of the ministry.
He travelled in that service in England, Scotland, Ireland, and Holland,
and labored zealously therein,
and was very industrious to get meetings in places where none had been,
or at least for several years past.

In 1710 he was taken ill in his travels, and being desirous to get homeward,
got on his way so far as Baldock, in Hertfordshire,
and there continued ill and weak until he died, at the house of John Izard,
who was kind and loving to him.

In the time of his bodily weakness he gave many good exhortations,
and at several times spoke as follows: '`Friends,
I would have you take notice of what I say;
the hand of the Lord God will be upon this nation and other nations,
and the day of the Lord will be terrible to the wicked and ungodly,
for he will assuredly shake their foundations;
and he will sever between the sheep and goats,
and he will winnow the chaff from the wheat.
But he will plead the cause of the righteous, and it shall be well with them; yes,
and his glorious truth shall prosper.
He will make Zion the beauty of nations, and Zion`'s king shall reign in glory over all.
The Lord will also try his own people; they shall suffer troubles;
but he will save and succor the righteous, that truly fear, serve, and love him.
And the Lord will divide between the righteous who have served him in truth,
and those that live only in a bare profession,
and have not been faithful to the Lord in their day.
But as for the righteous, that keep their places, and serve the Lord in truth,
and have washed their garments white in the blood of the Lamb,
they shall shine forth in glory, and shall stand upon Mount Zion,
praising their God and their king with heavenly harps in their hands;
and they shall reign and live with him, who is their God and their king,
forever and ever.`'

Another time he said, '`It is a brave thing for young people, in the days of their youth,
to serve the Lord.
Oh! how glad should I be, if our youth would mind to serve the Lord in their minority,
for the day is coming that will try them; yes,
it will purify them that abide faithful to the Lord their God;`' or to this effect,
with many more seasonable exhortations both to old and young.

He also earnestly exhorted Friends to follow the Lord fully, saying,
'`Let not any thing of the glory of this world steal away
your minds and your hearts from the Lord your God.
Mind that you follow the Lord fully, for his love is to all such,
beyond what testimonies can declare or set forth
to the full;`' with much more to the same effect,
not taken down.

'`Again, I thank the Lord my God,
who has kept and preserved me ever since he made me sensible of his everlasting truth;
and through the help of the Lord my God, I have labored faithfully,
according to the ability the Lord has given.
Yes, I can say, I have labored freely in the service of the Lord that he called me to,
for the promotion of his everlasting truth upon earth,
and for the gathering of the people to the holy way of the Lord.
I have not sought myself, but served my God in truth and faithfulness,
according to that ability the Lord gave me, praised be his holy name forever,
for all honor and glory, thanksgiving and everlasting praises shall be given,
attributed and ascribed to the Lord my God; for it is his due,
and he is everlastingly worthy of it.`'

'`And now I rest in the will of the Lord, and in peace with him;
for I know that everlasting peace with my God is the portion of my soul: praises,
praises, everlasting praises be to the holy name of the Lord my God forever and ever.`'

And speaking a few words to the youth, he said to this effect: '`Oh! remember Moses,
that true servant of God in his day, who saw beyond all the glory of Egypt; and he,
as it were, trampled upon it,
and rather chose to suffer affliction with the people of God,
for his faithfulness to him, than to enjoy the pleasures of sin for a season.
He loved the Lord, and followed him fully, and served him faithfully;
and the Lord was with him, and blessed him in his way;
and so will he still bless all those who labor to follow the example of Moses,
that faithful servant of the Lord, and walk in the path of the righteous,
who have truly loved God and served him in faithfulness in their day and generation:
praised and magnified be the holy and powerful name
of the Lord our God forever and ever.`'

Again he said, '`Oh! good is the Lord, and worthy to he served by all the children of men,
and more especially those that are concerned for the glory of his name.
Oh! thanks, honor, and glory be given to the holy glorious name of the Lord,
for he is good to my soul.`'

At another time he said to some friends who came to visit him, '`O! persevere,
and go on in the way of the Lord, and the Lord will be with you, and will ever bless you;
for no tongue can declare, nor pen set forth,
what the Lord has in store for them that love him.`'

'`I have been a concerned man, a travailer for Zion`'s seed,
and a faithful laborer in the gospel of our Lord Jesus Christ,
according to the ability the Lord gave to me; and now I am going to the Lord my God,
where I shall have everlasting rest with him, and the glorious immaculate Lamb,
who lives and reigns with the Father forever and ever.`'

'`So my dearly beloved friends and brethren, now we must part, and I leave you to the Lord,
desiring the Lord may ever be with you,
and bless you in the way of truth and righteousness;
and if you live and die in the truth, we shall meet again hereafter,
and enjoy everlasting peace in the mansions of glory.
But now we see in part, and know in part; but then I shall see, as I am seen;
and then I shall know, as also I am known.`'

'`I would have you remember these words of counsel,
and that it was given you by one who is your friend and brother,
who loves the ever blessed truth above all.
So, my dear friends, now I leave you, and commit you to him who is worthy,
worthy of everlasting praises, worship, honor, eternal renown and adoration;
unto whom all hallelujahs and high praises are sung, world without end, says my soul.`'

Some of his last words, which could be perfectly understood, when his spirits were weak,
and his voice very low, were as follow:

'`O holy God! you are pure, powerful, and very good unto my poor soul:
blessed and praised be the holy name of the Lord,
for all his mercies every day and every way.
O Lord, you are wonderful in all your works: oh! you are good to all your little ones,
that fear and reverence your glorious and powerful name etc.`'

Thus he lay praising God, and speaking of his goodness,
until his speech was taken from him, which was for a great part of the day he died,
which was the 26th of the Seventh month, 1710;
and was buried in Friends`' burying-place at Baldock on the 29th following.

[.asterism]
'''

WILLIAM CROUCH, according to his best calculation,
was born the 5th day of the Second month, called April, 1628,
in a small village called Penton, by Weyhill, near Andover, in Hampshire.
His father was a substantial yeoman, of good repute in the country,
and well beloved of his neighbors.
His mother was a religious woman,
and had fellowship among the people in that day called Puritans.
She was very watchful over her children, to preserve them from committing any evil,
either in word or action, and would often get them together,
and be with them on their knees in prayer to God;
wherein she has left a good example to others of her sex.

When he was a child, the Lord often visited him in mercy; and as he grew up,
preserved and delivered him from many great temptations and evils incident to youth,
inclining his heart to shun the rude and extravagant company of the times,
and to associate himself with those that were soberly and religiously disposed.
He diligently attended the ministry of such public preachers as were most esteemed,
and followed by the most religious, as he apprehended; and often wrote their sermons,
and was sometimes much affected, returning home, and retiring himself;
and offering his supplications to God.
But not knowing that the Lord was so near unto him as he was,
he witnessed little growth or increase of grace in his heart,
or power over his affections and lusts but was sometimes overcome by sinful temptations,
and often prevailed upon by vain objects,
which afterwards proved a burden and load upon his soul.
Yet the Lord, in his great mercy, did not cast him off,
but with much long-suffering and patience, followed him with the reproofs of instruction,
which he found by experience to be the way of life.
For now, in the year 1656,
he came to be in some measure convinced of the everlasting truth of God,
revealed to the people called Quakers.
And having been at some of their meetings in London,
where he heard the testimony of truth declared, he was further reached by it,
and by degrees fully convinced,
that salvation is only in and through Christ Jesus the gift of God,
and the light of the world spiritually revealed in the heart and conscience,
and sincerely believed in and obeyed.

As he was convinced of the truth, so was he, by the grace of God, enabled to walk in it,
and to keep up a faithful testimony to it in life and conduct,
according to the measure of the divine gift bestowed upon him.
He rested not in the beginning of regeneration, where too many content themselves,
but waited for, and labored after,
through the assistance and influences of the holy spirit,
the gradual and progressive work of sanctification,
having a state of perfection in his view;
and believing it attainable on this side the grave, by the grace of God,
through perseverance in faith, humility, watchfulness and prayer, looking unto Jesus,
that he, who had begun the good work, would confirm it unto the end.
He had a sincere love towards God, his church and people; yes,
towards all the children of men.

When differences arose among Friends, or others, he endeavored what he could,
to reconcile them, being kindly affectioned towards all,
but especially those in whom the love of God appeared.

As to the things of this world, he placed not his affections upon them, but,
as a Friend who well knew him testifies, '`His treasure was in heaven;
and for the treasures of this world,
he put no value upon them any further than to be his servants for necessary uses,
and to do charitable acts therewith towards others.
His charity was large, and many ways, being ready to assist such as were in trouble,
or under affliction of any sort, where either his advice or purse was lacking;
for he spared neither purse nor pains,
when he was called to serve others who needed them.
He practiced the pure religion and undefiled before God and the Father; that is,
he frequently visited the fatherless and widows in their affliction,
and kept himself unspotted from the world.
He was in particular a great support to the poor of the neighborhood where he lived,
in the country, often distributing by others`' hands largely of his charity to them.
Nor did the stranger in distress go empty-handed away from his gates.`'

Nor was he less remarkable for doing justice than exemplary in showing mercy to the poor,
and in helping and supporting the weak and afflicted.
He felt a necessity upon him to keep his word, perform his lawful contracts,
pay his just debts, and to do to all men as he would have others do to him.

What he was in his family, whether considered as a husband, father, or master,
his children and servants, who were immediately under his care,
give an ample testimony of him,
and speak of him to have been a singular pattern of piety and virtue,
in the discharge of all those relations.

The Lord enriched him with a large stock of spiritual and experimental knowledge,
which he had been gathering and treasuring up for many years.
And though he lived not upon his former experiences, but upon Christ, the living bread,
and only nourishment of the immortal soul;
yet those experiences of the lovingkindness of God
were comfortable to him in the openings of life,
to remember, and helpful to him in giving advice and counsel to others.

In his illness, which sometimes was severe upon him,
being sorely afflicted about the space of two years before his death,
the Lord enabled him to manifest much patience,
and meekly to submit himself to the divine will.

About nine months before his own departure,
and at a time when his distemper was sharp upon him, his second wife,
whose name was Ruth, daughter of John Brown, and Ruth his wife, of Wood street, London,
a woman who was an helpmeet indeed, of a loving and tender spirit,
and of the same mind with him in the things of God,
with whom he had lived for fifty years and upwards, in the fear of the Lord,
and entire affection, was by death removed from him.
The parting with so near and dear a relation, of whom he left this testimony,
that she would deny herself to a very great degree to serve him,
beyond what he could ask or expect of her; could not but make a,
deep impression upon him:
but such was his resignation to the will of his heavenly Father,
that he possessed his soul in patience, acknowledging with Job, that
"`The Lord gave, and the Lord has taken away: blessed be the name of the Lord.`"
Job 1:21.

And now drew on the time of his own dissolution,
which the Lord had graciously prepared him for,
and which he patiently expected the accomplishment of.
He often admired the goodness of God to him,
in inclining his mind to seek after good from his youth,
and in preserving him through the whole course of his life to old age.
He also often retired in prayer,
and waited upon the Lord for support under his daily exercise.

He had attained, through divine grace, to that inward peace and satisfaction of mind,
that he declared he had nothing to do but to die.
When he saw his children concerned for him,
he often exhorted them not to desire his life, for he was, through age and weakness,
incapable of being serviceable according to his desire;
and that he had done his day`'s work in his day.

The day before he died, a friend, who had made him several visits in his illness,
went to see him; and found him very weak.
And sitting some time with him waiting upon the Lord,
he was moved to supplicate the Lord on his behalf,
who was pleased to answer the cry of his servant,
and they were greatly comforted together in a sense of the Lord`'s presence and goodness.
After prayer, he expressed his great satisfaction in that heavenly visit, and said,
as before, he had now nothing to do but to die, and waited for the time,
when it should please God to call him out of this world,
and take him to his eternal rest.

The night following, he took his solemn leave of his children who were then present,
telling them he now thought he had but little time,
and the time which he so greatly desired and waited for was near at hand;
which was matter of joy to his soul, desiring the Lord to make his change easy,
that so his patience might hold out to the end; and the Lord granted him his request.

He departed this life the 13th of the Eleventh month, 1710, aged about eighty-two years,
at the house of his son-in-law, Michael Lovell, in London;
and was on the 19th following decently buried in Friends`' burying-ground at Winchmore-hill,
in the parish of Edmonton, Miiddlesex; his corpse being attended by his children,
relations and friends.

[.asterism]
'''

ROBERT HILL, born in the parish of Droitwich, in the county of Worcester,
about the year 1630 was convinced of the blessed truth in the town of Bromsgrove,
in the said county.
The great Lord of the harvest called him to work in his vineyard,
and sent him forth to preach the everlasting gospel; which he zealously did.
The Lord`'s power and presence was with him, and his blessing was so upon his labors,
that he was instrumental to convince many in those
parts Though he met many oppositions in his travels,
and several imprisonments, as he often said,
the Lord was never lacking to carry him on to do his work,
with strength and holy boldness, to stand and make answer for his God and for the truth,
before all opposers.
And when he was brought before the magistrates, and threatened by them,
he feared not their threatenings, nor their jails.

Some years before his latter end he was troubled with much bodily weakness,
which he bore`' with patience; and though his outward sight decayed,
yet his spiritual sight remained: so that, in a good measure,
he beheld the invisible things of God,
and in the sense and love thereof he was often in raptures of life, and said,
'`I am overcome; overcome with the love of my beloved.
So now, come, Lord Jesus, for I am ready; receive my soul into your everlasting glory.
I have a fall assurance of my Father`'s love,
and I long to be with the innumerable company of angels and spirits.
I have an earnest desire, and long to be in the fulness of enjoyment,
where I may ever be singing praises to God and the Lamb forevermore.`'

He frequently gave counsel to those who came to visit him, for the good of their souls,
with much tenderness and tears, that they might not walk in the broad way of the world;
and declared of the Lord`'s mercy towards the sons of men,
if they would hearken to the call of the Lord, and be obedient thereunto;
testifying that was the way to everlasting life.
And it pleased the Lord to make him instrumental to bring many to a sight
of their inward condition for the good of their souls.

And as by Providence his dwelling in his latter time was near to the meeting-place,
he would often give thanks to God for that privilege; and when he was weak in body,
he would say, '`I must go to meeting as long as it pleases God to enable me,
and see if he has any service for me to do.`'
Many times, notwithstanding his weakness, the Lord was pleased to make use of him;
and he returned thanks to God for affording him his presence,
and enabling him by his power,
to publish and declare what the Lord had done for his soul.
He was a great lover of the poor, very charitable to them, and often prayed for them,
and entreated the Lord, he would be pleased to order for their relief,
as it seemed good to him.
His wife, knowing the blessed work of charity was well-pleasing to him,
sometimes told him what she had done in that work; he would say to her,
'`I pray God bless you for it,
and be sure you will have your reward for relieving the poor;
for the Lord delights in a cheerful giver.`'

He often mentioned the goodness of God, being truly sensible of it to his soul;
and having a regard to the poor,
he manifested the same by his frequently administering to his necessitous neighbors,
and also by the gifts and legacies he left them.

He departed this life in peace with the Lord, the 7th of the Twelfth month, 1710,
and was buried the 10th of the same.
Aged about eighty years.

[.asterism]
'''

ANNE HUMPHREYS, late of Saffron-Walden, in the county of Essex, widow,
was a young woman whom the Lord was pleased to visit and bless
with the knowledge of himself and his unchangeable truth,
which she received.
in the love thereof; and by waiting upon the Lord therein,
came to know the work of it in her soul,
and to experience the sanctifying virtue thereof through her obedience thereto.
And the Lord, who by his grace made her what she was,
was pleased to confer upon her a gift of the ministry about three years before she died,
in which she labored faithfully.

In the Fourth month, 1711, she was concerned to go into Ireland to visit Friends,
and landed at Dublin the same month, accompanied by Anne Chapman, of America;
and they visited several meetings in and about the city of Dublin,
and so passed towards the north of that nation.
Being taken ill with a strong fever, she was forced to keep her bed;
but after the fit was somewhat abated, a meeting being appointed for them,
she was desirous to go, and did: and the Lord was pleased eminently to appear with her,
to Friends`' mutual joy and comfort; but she went no more abroad,
the small-pox soon coming out upon her.
Then she expressed herself, saying, '`Lord Jesus, my spirit waits your coming;
my soul waits for you, my Redeemer.
Oh!
Lord God Almighty, you surely have prepared for me a habitation in the heavens with you.
You it is who make me sensible, that here I am not to stay much longer.
O Lord,
I feel at this time your great love and heavenly
spring of life to refresh and comfort my soul.
Into your arms (for you know it is that I have travailed for) I am ready +++[+++to be received],
Lord;
and you have given me to know that my soul is ready to enter into your everlasting kingdom.
O Lord; for this your great mercy, in affording your servant this opportunity,
I do at this time, in all reverent thankfulness, bless and praise your most holy name,
who are surely worthy forevermore.`'

She departed this life at Colerain, on the 20th of the Fifth month, 1711;
aged about thirty, and a minister three years.

[.asterism]
'''

JOSEPH STONE, Jun., of Witney, in Oxfordshire, was born in the Sixth month, 1683,
and descended of honest parents.
He was educated by them in the way of Friends, and was well inclined when young;
and by the early visitations of the grace of God upon his
heart he embraced the yoke of Christ in his youth,
and as he was taught of his Savior himself to eschew the evil and to do good,
he was the more fit to be a messenger to carry the glad tidings of salvation to others,
and to make known to them what the Lord had done for his soul.
Yet this work he could not undertake,
until it pleased the great Lord of the harvest to gift him for it,
which was in the year 1703.
In this work he labored, according to the ability he received,
by whose ministry the seed and heritage of God was often refreshed;
for the springing of love from the spirit of God in one,
will certainly answer to the same divine principle in others,
and fix it as an evidence upon their hearts, that it is the truth.
He was also exemplary in conduct, and of an innocent deportment.

He loved solitariness, choosing to be much alone,
and approved himself a faithful servant and minister of Christ:
he was zealous for promoting the honor of God,
laboring in word and doctrine for that end,
not only in the neighboring meetings about him, but also in several counties in England.
He had a great concern upon him that he might be instrumental in the Lord`'s
hand for turning the hearts of the children of men from darkness to light,
and from the power of Satan unto God.
In his testimony he was concerned for the hinder-most of the flock;
in prayer fervent for the offspring of Friends,
that they might come to witness the grace of God to save them from a vain manner of life;
for he knew that, though.he had his education among Friends,
yet it was not that alone that did make him what he was, but the grace of God,
as he gave up to be guided thereby.
And because of his experience,
which he gained in yielding to the guidance of the spirit of truth,
he was the more frequent in exhorting the youth of
our day to seek the Lord in their early days,
agreeably to the voice of wisdom, who advised the same of old.

He wrote a short account of his call to the ministry,
with some of his labors and travels therein;
as also the comfort and satisfaction he reaped in his service for truth, as follows:

[.embedded-content-document.letter]
--

After it pleased God, in the riches of his love, to bestow on me a gift of the ministry,
and, by his grace, to call me to and qualify me for the same,
which was in the Ninth month, 1703, I was obedient to the heavenly call,
and gave up freely, but not forwardly, to the call.
And, after some time,
I visited some neighboring meetings in some parts of Worcestershire, Warwickshire,
Gloucestershire, and Oxfordshire.
In the year 1707 I went down to the yearly meeting at Bristol,
and then returned home again, where I remained three years,
only visiting some neighboring meetings, and took one journey to London.
But having a concern to visit Friends in the West,
which rested upon me till the year 1710, I then gave up and went,
though not likely to have a companion but part of the journey.

--

On the 4th of the Fifth month, 1710, he left his habitation at Witney,
and went southward to Abingdon quarterly meeting, where he met with his friends,
John and Thomas Wagstaffe, who accompanied him part of his journey, where they left him,
and returned, he pursuing his journey to the Land`'s-End; from which he returned,
visiting Friends through the counties till he got home,
which was on the 30th of the Sixth month.`'

"`I had a very satisfactory journey,`' says he, '`for the Lord was with me,
and was to me mouth and wisdom, language and utterance;
blessed be his glorious name forever.`'

And his divine presence and glorious power was prevailing in our meetings;
for I had many glorious and heavenly meetings in this journey,
to my great satisfaction and comfort,
and to the comfort and edification of the Lord`'s people.

And it is the desire of my soul that the consideration of the Lord`'s
love and goodness may be a binding obligation to us,
forever to walk in true humility and self-denial before him.
The people who were not acquainted with the work of truth,
were free and willing to come to our meetings in those parts,
and were very attentive to the testimony of truth,
and seemed to be well affected with it, many of them appearing very tender in meetings.
I believe the Lord will add to his church such as shall be saved,
and will more and more bring people off from the idle shepherds of this world,
who feed themselves and not the flock,
and will bring them under the guidance and conduct of his Son, the Lord Jesus Christ,
the everlasting Shepherd, who watches over his flock both night and day,
and feeds them in green pastures of life,
and leads them by the still waters of Shiloh`'s brook,
and will at last bring them to the everlasting fold of rest.

Oh! that all who profess the blessed truth might be faithful to him,
that so they might preach for God in their lives and conduct,
and become instrumental in the hand of God,
to the carrying on that great work which he has begun in the earth,
which must be completed by the spirit of judgment, and the spirit of burning.

[.signed-section-signature]
J+++.+++ Stone, Jr.

[.signed-section-context-close]
The 7th of the Fourth month, 1711

In the Sixth month following, he had a concern to visit Friends westward again,
and went so far as Cirencester, in Gloucestershire; but being taken very ill,
he returned back again to his father`'s house at Witney,
and his illness increasing upon him, proved him sorely.
Yet he continued in much resignedness to the will of God,
and signified that people had need not have their day`'s work to do then,
for there was work enough to bear up under the pain of body;
and desired Samuel Waring to remember his love to all Friends.
In the evening, as he sat by him,
he signified that he did not know how the Lord would be pleased to deal with him;
but for the sake of his dear parents, and others, to whom he might be of service,
he should be glad if the Lord should see fit to spare him;
but he freely resigned his will to the will of God.
But before he parted with him, he told him he was going, and that all was well,
all was well, twice; and desired all to go out of the room, except him, to whom he said,
'`I have seen the glory of heaven,
and it is a brave place;`' and could make his appeal to the Lord, and say, '`O Lord,
you know how I have walked before you,
and served you;`' he having that assurance in his own bosom could call death sweet,
because by it he passed out of this house of clay into the mansions of glory!

When he had been ill a few days, he said to them about him, '`This is ordered for my end,
and it will be well with me my soul shall go to rest.`'
One who was with him said, '`How did he know but the Lord might raise him up again?`'
He answered, '`A man that lived a righteous life,
he believed often knew a little beforehand how it would be with him.`'
His nurse wishing those present were as fit to die as he, he answered,
'`I thank God I have nothing to do but to die; all the world is nothing to me,
I have done with it.`'
But adding, his care was a little for his dear father and mother,
and sister and her children, saying, how would they do without him;
for indeed he was very assisting to them.

Another time he said, '`When I am gone hence, I shall receive a new name.`'
At another time he sent for his father, mother, and sister, to take his leave of them:
his father asked him how he did; he said,
'`Very bad;`' and asking him what he had to say to him, he answered, '`Farewell, farewell,
farewell.`'
Then his mother and sister went, and his sister asked him how he did; he answered,
It will be well with me, and that he was not afraid to die;
he did not fear death if it was that minute.`'
And so departed this life the 30th of the Sixth month, 1711,
and left a good savor and blessed memory behind him.
He was a dutiful son, a kind brother, a faithful friend, and a good neighbor.
He left a small treatise behind him, in manuscript, entitled, '`A Call to the Disobedient,
'`and some other papers.

He was buried at Friends`' burying-ground at Witney, many Friends and others attending.
Aged twenty-eight years; and a minister about eight.

[.asterism]
'''

MARY TURNER, the wife of John Turner at Tottenham High Cross, in the county of Middlesex,
was the third daughter of that remarkable sufferer for the testimony of a good conscience,
Richard Vickris, of Chew-Magna, in Somersetshire, deceased, and Elizabeth his wife,
daughter to that ancient worthy, George Bishop, of Bristol.
In her tender years, by the grace of God, through the care of her religious parents,
she was instructed in, and seasoned with the principles of the holy truth,
as professed by the people called Quakers; in which she continued faithful,
and was an example of piety and virtue through the course of her life.

When a little child, our much esteemed friend William Penn coming in at her father`'s,
where he was very conversant, and affected with her pretty innocent deportment,
broke forth, extempore, thus:

[verse]
____
'`Sweet soul!
What makes you stray
From the angelic way?
Was it to teach us how to love
The happy regions above?
If so, O! let your wandering prove our gain,
And take us with you back again.`'
____

She was naturally of a lively and cheerful temper,
which remained when she came to years of discretion,
yet took pleasure in frequent retirement, and divine meditation, in meetings for worship,
and religious conversation,
and received worthy public Friends with great comfort and satisfaction.
When at home alone, she entertained herself chiefly in reading the Holy Scriptures,
Friends`' writings, and the three first books of Thomas a Kempis,
on the Imitation of Christ; at other times with her pen and needle;
for it was rare to find her unemployed in something useful or necessary,
when her health permitted.
In her dress and apparel she was very neat and plain.
The tenderness of her love and affection to her husband, mothers, brother and sisters,
was more than common) and very remarkable,
and likewise so generally extended to her acquaintance,
especially where truth had a prevalence, that it may be said, love predominated in her.

A few years before her death, she was sensible of a gradual decay of bodily strength,
and when weakness and faintness prevailed,
she bore it with much patience and resignation to God`'s holy will.
In a sense of the uncertainty of the comforts here below,
she wrote thus to a near friend:

[.embedded-content-document.letter]
--

The enjoyments of this life appear very changeable,
and we are apt to seek them more than is good for us, which hinders our inward comfort:
so we have something to war against every day.
I desire you may be directed by that divine hand
which orders all things for our good every way,
as we have an eye to it.

--

[.offset]
And in another to a relation:

[.embedded-content-document.letter]
--

I am very sensible of my happiness,
and desire to walk worthy of the mercies I enjoy;
yet the lack of my health has been an affliction to me: but I do not repine at that,
since it is an advantage to us to have some alloy to the comforts of this life,
which are mostly attended with disappointments of one kind or other.

--

On her bed of sickness she said to her brother,
she admired people should so much place their affections on the things of this world,
which are but as dross, and like traveling in misery;
and earnestly desired their family might, with Jacob, obtain a blessing;
and as they had such worthy parents, who had educated them in the ways of truth,
and enjoyed so many favors beyond many others,
there ought to be a double thankfulness to the giver.
She desired her brother to be a comfort to their tender mother,
and to keep up their honorable father`'s name, as one of the branches of the family,
and then there would be a blessing laid up for him.

Speaking to her sisters, she said,
'`We should be good examples in the plainness of our habits,
as we make profession of the principle of truth, and should take up the cross daily;
for we were not born to serve ourselves, but to honor the Lord.
That pain and weakness were hard to bear and when we are going out of the world,
we had need to have nothing then to do: that she waited for the presence of the Lord,
in which was more pleasure than in all the joys of this world.`'
Then turning to one of them said, '`The Lord has done great things for you,
and may have a work for you to do; there is good seed sown in your heart,
and I desire the Lord will bless you.`'

Having been tendered in her spirit, some friends came to visit her, and prayed with her;
whereupon she said, she saw the Lord had not forsaken her,
but sent his servants to visit her, which was a great comfort to her.

Another time one of her sisters coming into the room, '`O sister,`' said she,
'`the old accuser of the brethren lies very near, but the Lord`'s hand is underneath,
and sweetly supports.`'

Some days after, the same sister being by her bedside,
she had an extraordinary concern for her own welfare and her near relations, saying,
'`Dear sister, I have a steadfast hope, but not yet a full assurance.
I desire you, pray earnestly for me, lest there should be anything committed by me,
that may have slipped out of my remembrance,
and I not be earnest enough with the Lord for forgiveness.
I also pray earnestly for you all, that you may come where I hope to be;
and for my dear husband likewise: '`and expressed her great care,
that not one of the family might be lost.

Another of her sisters, leaving her a little time,
desired the Lord would support her under her weakness, she answered, '`He has,
and I believe will;`' and seemed comfortably resigned in her spirit.

A few hours before her departure she desired to be raised in her bed,
on which she seemed as if she should pass away, and bade all farewell; but reviving,
said, '`I thought I had been going,
but the Lord has given me life from the pangs of death, praised be his name:
oh! praises be to the Lord, he has given me a little ease.`'

Her fear was so great of offending the Lord, that perceiving some disposition to slumber,
she said to her mother, then near her,
'`Do you think he will be angry if I should drop asleep?`'

Some time after, being moved again, she seemed refreshed,
and lay in a sweet frame of mind, praising the Lord, saying, '`Lord, you are merciful,
compassionate and true.
You have given me ease: oh!
I will praise your name at all times, from time to time; every hour,
every minute while I live I will praise you.`'
Being in great pain, she said to some that were near her,
'`He will give me ease by and by;`' and earnestly prayed
to the Lord for it after this manner:
'`Dear Lord, give me ease: sweet Lord Jesus, give me ease;`' and then said to her sister,
he would.
Her sister said, she did not doubt but the Lord would answer her desire,
and give her a full assurance; to which she answered, '`I believe he will.`'
Then she desired those by her to pray for her.

Having slumbered a little, she awoke refreshed, and looking on one of her sisters,
she said to her, '`Dear sister, I shall do well, I shall do well.`'
After which she was heard very sweetly in prayer to the Lord to receive her;
and was sensible to the last.

Toward the conclusion of her days,
her weakness was attended with such faintness and pain, sometimes,
that it made her apprehensive it would be very hard
to bear the struggles of her final dissolution,
which she frequently begged of the Lord to make easy;
and he was pleased to answer her desires accordingly;
for she passed hence almost without sigh, groan,
or any visible alteration of countenance.

She departed this life at Tottenham aforesaid, on the 31st of the Sixth month, 1711,
and was decently interred in Friends`' burying-ground in Bunhill-fields, at London,
on the 5th day of the Seventh month following, about the thirty-third year of her age.

[.asterism]
'''

THOMAS DOCKERY, late of Silverdale, was born in Cumberland, near Portinscall,
brought up a scholar, and was reader at Withburne Chapel, in that county;
and being a sober young man,
and having inclinations in his heart after the true worship of God, which is spiritual,
it pleased the Almighty to open his understanding,
and to show him the mysteries of the kingdom of life and salvation,
and the emptiness of the ways, forms, and traditions of the world, and the evil of them,
wherein he had been, among many others.
He was concerned in love, to go to their public places of worship,
and bear a testimony against them; and what wages he formerly had received for reading,
as aforesaid, he carried back and left it with the people,
and told them they were the wages of unrighteousness, for which he could not keep them.

Being joined in society with friends, he grew in the truth,
and became very instrumental in the service of the gospel,
for the confirming of friends in the faith,
and information of such as opposed the truth.

After some time he was drawn forth, in the love of God,
to visit friends`' meetings in England, Scotland, and Ireland.
Five times he visited friends in Scotland, and three times in Ireland;
and at his returns had great peace and satisfaction.

Once at Aberdeen, in Scotland,
the envious priests incensed the magistrates against friends, and he was put in prison,
and remained there about three months;
but the Lord`'s love and presence he enjoyed therein, and great was his peace;
for he experienced the Lord`'s power to preserve him,
and the truth was set over his persecutors, and they set him at liberty.

Then he returned into Cumberland, and abode there a considerable time;
and from there went to Swarthmore, in Lancashire, and continued several years.
Also several times accompanied G. Fox to London, and elsewhere,
in the service of the gospel.

In the year 1683, he settled in Silverdale, in Lancashire,
and belonged to the Yelland meeting and continued
a member of the said meeting above twenty-seven years,
being a diligent attender thereof.
Notwithstanding he was weak and infirm in body for several years before he died,
yet he was frequent in testimony, to the edification of friends,
and the understanding of others.

He was exemplary in humility and lowliness of mind,
lived in peace and unity with friends, and was well esteemed among his neighbors.
When his outward strength decayed, that he grew weaker in body, he was always content,
and after he took to his bed he continued several weeks,
not being much afflicted with pain, the Lord dealing gently with him;
yet he grew weaker and weaker; and when asked how he did, replied, '`Very weakly,
but well content to die, and be removed to eternal rest with the Lord,
whom I have served; which is now to me great satisfaction and content.`'

He continued very quiet in his mind, and sensible to the last,
and as he had lived in peace and unity with Friends,
he died in the same the 6th of the Tenth month, 1711,
and was buried at Friends`' burying-place at Yelland, the 8th day of the said month,
about the eightieth year of his age, and a minister of the gospel fifty years.
