== Chapter 4

[.chapter-synopsis]
* Richard Bockett
* Mary Lamley

RICHARD BOCKETT was born in London, on the 26th day of the Eighth month, in the year 1693.
He was one whom the Lord was pleased to visit in his young years,
and gave him a sight of his holy way, namely, Christ Jesus, the way, the truth,
and the life; and also enabled him to walk therein in a good degree,
wherein he met with that peace and satisfaction which engaged him,
in his very young years, to exercise his mind in spiritual things.

He was seized with a violent fever on the 13th day of the Sixth month, 1721,
which continued on him five weeks,
but remained very sensible all the first week of his illness.
His mother fearing his senses might not long continues was
concerned tenderly to ask him how it was with him,
as to his inward condition,
and whether he had witnessed at times and seasons
the enjoyment of the presence of the Lord.

His answer was, '`Yes, many a time;`' and also said,
it had been his desire rather to be taken out of this world,
than to bring any dishonor to the Lord.
Which was a comfort to her to hear;
this being the seventh day since he was first taken ill.
That evening he took to his bed, expecting to have a very bad night,
but contrary to his expectation, the Lord was exceedingly good to him,
which brought him into great stillness of mind.
After some time, his mother being in the room, he softly called, '`Mother,
let all be still.`'
Then she sat down by his bedside, and was sensible the Lord was near to him,
and was pleased to solace his soul with his goodness in a wonderful manner.
So he lay still for some time, and afterwards broke forth in a heavenly frame of spirit,
and said, '`Mother, I feel no pain.
I lie as in a bed of roses;`' and so continued in
great stillness for some considerable time,
and expressed again,
it was joy unspeakable that the Lord was pleased to make him a partaker of.
She was thankful to the Lord for his merciful visitation that he
was pleased to bestow on him at such a time of need.

Next morning he gave her a more particular account how it had been with him that night,
in the time of his stillness:
he thought his spirit was ascended out of his body into heaven,
where he beheld such a glorious light as he never had beheld,
and heard such sweet melodious sounds, that he desired to tarry there,
but it was not long before he thought his spirit returned into the body again.
After this, his distemper grew stronger on him,
so that his life was not expected by any that saw him.
He was wonderfully preserved in his senses,
and bore his distemper with great patience and resignation to the will of God,
either to live or die; and when his relations could not forbear weeping,
and expecting to part with him, he looked upon them, and said, '`Do not grieve too much;
if we must part, I hope we shall meet in heaven.`'

After five weeks, his distemper pretty well left him,
that he seemed to be in a fair way of recovery, and remained so four weeks,
which gave great hopes of his longer continuance.
But he was suddenly taken with a very great bleeding from his lungs,
which he brought up by a cough that began on a First-day in the evening,
and continued by fits all that night.
The next day in the forenoon, he had another bad fit of bleeding,
so that he was not expected to speak any more, for he seemed as gone.
But the Lord was pleased to break in upon his soul by his mighty power,
by which his mouth was opened in prayer; a small part of which was as follows:
'`O glorious Lord! you can bring down to the brink of the grave,
and can raise up again to praise your holy name.
Your goodness has wonderfully broken in upon my soul at this time,
when at another time I could hardly have desires for myself;
but you have wonderfully appeared to my soul at this time,
and have sealed your salvation to me.`'

A friend coming soon after his prayer was ended,
and finding him to appearance near his end, was willing to tarry with him,
she thinking it would not be long before there would be an alteration,
which was on the fourth day in the evening following.
In this time, she taking an opportunity; asked him how it was with him;
and after some little space of silence, he said,
'`I think that appearance (meaning the last visitation as
before-mentioned) the Lord was pleased to favor me withal,
is an anchor to my mind;
for I think it as an extraordinary favor that the Lord was pleased to favor me with,
and thereto am I anchored.`'

Some time after she said she hoped his work was done, he answering, said,
'`Yes;`' and so finished his course that evening;
and without doubt is entered into that everlasting
rest that is prepared for the righteous.

He departed this life on the 18th day of the Eighth month, 1721,
being near the twenty-eighth year of his age,
and was buried on the 22nd of the same month, from the Bull and Mouth meeting,
in Friends`' burial-ground near Bunhill-fields,
his corpse being attended to the grave by a considerable number of Friends and others.

[.asterism]
'''

MARY LAMLEY, the wife of William Lamley, of Bloxham, near Banbury, in Oxfordshire,
was suddenly visited with illness the First-day of the Second month, 1722.
She said that her Redeemer lived, and because he lived, she lived also,
and that he would stand the last day upon the earth.
She desired Friends that came to see her not to sorrow for her,
for if the Lord was pleased to take her from them,
he could soon raise up one or another of them that
might be of more service than she had been.
She advised them to faithfulness, and to look to that which would never change nor alter;
and above all things in this world, to have an eye to the blessed truth,
for she believed that the Lord had blessings in store for some of them;
advising them to stand faithful in whatsoever the
Lord should require at any of their hands.

At another time she said, '`The Lord deals with us as a tender father does with his child,
who, when he first sets him to work, employs him in small matters, and afterwards,
when the child grows in strength and understanding, he requires greater service of him.
So the Lord gently leads on his people in his work.
The same arm that divided the waters of the sea,
and made them as a wall on the right hand and on the left,
while Israel passed through the midst, as on dry ground, when the enemies pursued,
that same arm caused the waters to return and overthrow them,
that there was not one left;
and yet there was a wilderness for Israel to pass through afterward,
in which many fell +++[+++because]
of their murmuring, unbelief, and disobedience.

'`I do not speak these things because you are ignorant of them,
but because you have had experience in measure of
the wonderful works of the Lord in the deep,
that the pure mind may be stirred up in all, that you may follow the Lord fully,
as his servants Joshua and Caleb, and may obtain an inheritance in the heavenly Canaan.`'

When she had been speaking of the goodness of God to her soul, she said,
it was not for any worthiness in her, or for any works that she had done,
but it was free mercy and love to deal thus graciously with her.

Another time, speaking of several states that Zion`'s travelers pass through, she said,
'`We ought to be concerned to be content in every
state that the Lord is pleased to bring us into.
When we are poor in spirit, we ought to keep the word of patience,
and then the Lord will keep us in the hour of temptation,
and in his own time he will abundantly bless the provision of Zion,
and satisfy her poor with bread; and when he gives us a full cup, and makes it overflow,
then let us remember our state of poverty, that we may be kept humble before him.`'

She had also an exhortation to several Friends, in the words of the prophet Isaiah,
"`Cease to do evil, and learn to do well.`"
She earnestly pressed the necessity of ceasing from evil, and from all that tends to it,
that so they might come to learn of the Lord to do that which is good;
for if any pretend to go about the Lord`'s work, and do not cease from evil,
that will be a contradiction.
She was so resigned to the will of the Lord, that she said she desired to be passive,
as clay in the hand of the potter.

At another time she spoke to one of her neighbors to make good
use of the time the Lord should be pleased to afford her,
in being faithful in the performance of her duty, while she had health and strength,
according to the discoveries the Lord should be pleased to make to her.
She signified that it was her desire, that there might be such an early preparation,
that when death should come, there might be nothing to do but to die.

Another time she spoke to a young person after this manner:
'`I believe the Lord has blessings in store for you,
if you will but be obedient in what he makes his will known to you.
He has given you a larger share of understanding than many others,
and you can not plead ignorance; you know your duty.
Now he that knows his master`'s will, and does it not, shall be beaten with many stripes.
Take heed that be not your portion;
let it be your care to have due regard to that pure light that shines in your heart,
that will show you your duty towards God, and also towards man.
Be obedient to the requirings thereof, and then those that honor the Lord, he will honor,
and beautify them with his living presence;
and that makes young people really beautiful in the sight of the Lord,
and also in the sight of good men.`'

She said at another time, '`I am weak both inwardly and outwardly.
I think I am as empty as ever I was.
I have sometimes been so favored with the divine goodness,
that I have had something to say for the encouragement of others;
but now I do not find that I have any thing either for myself or them.`'

But after some time had passed in waiting upon the Lord, in solemn retirement,
the Lord gave her, as she declared, in measure what her heart desired;
and she spoke to this purpose: '`This evening I have been very poor in spirit.
We ought to learn in every state, therewith to be content; to wait in faith and patience,
the Lord`'s time, which I believe the living in Zion can say,
we have always found to be the best time.
It is he that has the key of David, and when he shuts none can open; and when he opens,
none can shut.
Therefore let it be with us, as it was with the Lord`'s servant Job,
as to that firm trust in God, which he expressed when he said, though he slay me,
yet will I trust in him.

'`My friends, let us wait in faith and patience upon God,
although he may be at times as a sealed fountain unto us,
yet in his own time he will open, and cause the living water to flow, which,
blessed be his name, my soul tastes of at this time, beyond what I did expect,
and now my strength is`' once more renewed in him.
Who could have thought I should have been so favored at this time.
The Lord has made his strength to appear in my weakness.
It was in a very acceptable time he did appear,
and therefore let us always wait for his appearance, that he may be our guide,
and may be known to go before us.
The answer of Christ to some that spoke to him, concerning going up to the feast, was,
My time is not yet come; but your time is always ready.
There is abundance in it.
Let us not make our states look better than they really are,
or attempt to go up to the feast without the Master of the house, for if we do,
he will not be pleased with us.`'

Afterwards, the same evening, taking her husband by the hand, she spoke to this effect:
'`My dear, as we made a solemn covenant with each other, before the Lord and his people,
so I can truly say it has been as much my care to keep it, as ever it was to make it.
I have nothing of the contrary to say of you; but as we came together in love,
so we have passed the time we have had together, in love one to another,
in which I have peace and satisfaction; and we have also lived in love with our friends,
and I desire you may abide therein.

"`If I am taken from you,
let your doors be open to receive such as may be concerned to visit Friends here.
I would have you be willing to make use of opportunities that may be afforded,
that meetings may be kept here as they used to be, for the good of your neighbors,
whom we ought to love as ourselves,
that they may have the invitation to partake of the free love of God.

"`I desire you may stand faithful in your testimony against the hireling priests.
Do not shrink at sufferings.
If they do spoil your goods, take it joyfully.
There were some of old that took joyfully the spoiling of their goods,
and the truth is as worthy to be suffered for now as it was in that time.`'
Be sure your care be to bring up your son in the way of truth.
Do not let fond affection prevail against judgment,
but deal with him as you find it your duty to do; and.
I live in hope, and, if I die now, I think I shall die in that hope,
that he may be made instrumental, in the hand of the Lord, for the good of others.`'

She spoke at another time, being in a very deep sense of poverty of spirit,
as she expressed her thoughts, beyond what she had known before, to this effect:
'`There are diversities of operations by the one spirit,
and it seems to me that the Lord is dealing with us in a particular manner this evening,
and I hope it will be for our good, that we may learn for the time to come,
not to be so apt to distrust the mercy of God in a time of need.
And surely we have no cause to be exalted above measure,
in the thoughts of what at some times passes,
seeing we are so very liable to be stripped of it all;
and if we are stripped of our enjoyments, let us not murmur,
but rather let us say with Job, "`The Lord gives, and he takes away;
blessed be the name of the Lord.`"
And now he has given me a little taste of his love,
and he that gathered little manna had no lack; and he that gathered much,
had nothing over.
Let us be content with what the Lord is pleased to give.
Although I must confess I am still very weak in my inward man,
yet I hope the Lord who has been my support in six troubles,
will not forsake me in the seventh.

Afterwards the Lord gave her a great share of his goodness,
and she spoke to this purpose: '`The Lord is ready to lift up the hands that hang down,
and to confirm the feeble knees; and as we are waiting upon him,
he will touch the ankle-bones, and they shall receive strength;
so that they that have been spiritually lame, as to the performance of service to God,
shall come to walk more uprightly before him, and then neither grace, nor glory,
nor any good thing, will the Lord withhold from them.
Now once more my soul is filled with the goodness of God,
and in a sense of it my heart is engaged to return praises to him.`'

She spoke at another time, '`This evening we have enjoyed that which is beyond words.
I desire that those I may leave behind me, may live in that that is beyond words,
and may be faithful.
It is what I have been often concerned to call people unto,
and the Lord will so furnish his people with strength,
although they may be but few in number, that one shall be able to chase a thousand;
for every tongue that shall rise in judgment against the truth shall be condemned,
and the Lamb and his followers shall have the victory.
Let us not premeditate what we shall say in behalf of truth,
for I believe it will be given us in the time that it may be required of any of us.
The Lord has favored with blessings beyond what we could ask or think; and now,
if we part, surely it will be a good time to part in,
when we are in the breast and arms of our beloved.
If the earnest be so sweet, what will the full possession of the inheritance be?

'`Although my friends are very dear to me, I can freely part with them now,
and leave them under the care and protection of the Almighty.
I believe those will be preserved that are faithful to the Lord.
Although they may meet with storms,
he will be unto them as the shadow of a great rock in a weary land,
and will cover their heads in the day of battle.
And now, friends,
I desire that you would give up those freely that the Lord shall be pleased
to remove from these storms and afflictions into that divine glory,
where the weary shall be at rest, and the wicked cannot come to trouble them.
I believe if we give up ourselves and one another freely to the Lord`'s disposal,
it will be acceptable.
And now I desire we may all once more be committed into the hand of the Lord,
as unto a faithful Creator and loving and tender Father.`'

Afterwards she was concerned in supplication to the Lord,
that if he was pleased to require a testimony of any of
his people at the very last of their time in this world,
he would be pleased to enable them to deliver it faithfully, without adding to it,
or diminishing from it.

She spoke at another time to this effect:
'`We are advised to trust in the Lord with all our hearts,
and not lean unto our own understandings; and I desire we may take this advice,
for if we were to lean to our own understandings in these times of deep poverty,
I think we should be very likely to fall into despair,
when we see ourselves unable to think a good thought, or ask any petition as we ought.
The invitation of the Lord was, unto the weary and heavy laden, to come unto him,
and learn of him; and then, as they were willing to take his yoke upon them,
and learn of him, he promised they should find rest unto their souls.

'`I desire we may all learn of him, for he is the best teacher that we can hearken to.
He instructs his people,
and leads them about sometimes in a way that they have not trodden before,
and therefore we had need keep close to him.
Sometimes he is pleased to try his people with the greatest trial of all,
even lack of water; and then, if we are not watchful,
we are in danger of being like some of old, who murmured, saying,
"`The Lord has brought us out of Egypt, into this wilderness, to slay us with thirst.`"
But I desire that such a thought may never have place in our hearts,
but that we may patiently wait until our spiritual Moses cause the waters to gush out.
I believe the Lord will fill the empty vessels;
there is enough in him to supply our needs, and the needs of the thirsty ones everywhere.
And as the Lord has now made us sharers together of his goodness, I desire that,
in a sense of it, living praises may be returned to his eternal name,
who is worthy of it now, henceforth forevermore.
I can say, unto the honor of his name, without boasting,
I am refreshed both inwardly and outwardly.`'

She said, at another time, '`My friends,
I desire we may make sure of the Lord for our portion,
in seeking him while he is to be found, and calling upon him while he is near;
for there is no other that can support and enable us patiently
to bear those afflictions that may come upon us.
It is certain that trials will come upon us all at one time or another,
and therefore let it be our chief care to keep near the Lord,
and to avoid all those things that would bring wounds upon us;
for if I had had a wounded conscience when these afflictions have been upon me,
I believe it would have been more than I should have been able patiently to bear.
But when the Lord is pleased to favor us with the smiles of his countenance,
this sweetens the chastisements that he is pleased to bring upon us.
Let it therefore be our great care,
to keep a conscience void of offense towards God and towards men,
and then I believe the Lord will be with us, and support us in the greatest of trials,
and we shall have cause in measure to say with the psalmist,
"`He makes my bed in my sickness;`" for he will make it so easy to us,
that we shall be able to bear our afflictions with a quiet and easy mind.`'

She spoke at another time, '`My friends,
the Lord is once more giving his little ones encouragement to trust in him;
for surely in his own time he will arise for the help of his people,
who are poor until he appears.
This deep sense of weakness and poverty of spirit that the Lord brings us into,
is good for us; for it ought to be, and I hope it will be an obligation upon us,
not to be high-minded, but fear; and as we abide in the fear of the Lord,
our hearts will be kept clean.
Let us be willing to sink down deep in the nothingness of self,
that the Lord in his own time may appear, and may be a double portion unto us.
When he comes, his reward is with him, and his work before him;
when he arises he will scatter our enemies.
Oh! let the sincere desires of your hearts be unto the Lord, that his hand may not spare,
nor his eye pity any thing in you, that is contrary unto his pure will;
for although you may have parted with many things for the truth`'s sake,
yet there may he something yet remain that is unclean.
Therefore you had need to be very diligently concerned in searching yourselves,
that you may see what it is that is growing in you,
and which of the two seeds it springs from.
We may observe, that it was while men slept that the enemy sowed the tares,
and if you sleep in carnal security, the enemy will sow that in your hearts,
which if it be permitted to grow, will certainly oppress the pure seed.
Therefore, have due regard unto that great command of Christ,
which he gave to his disciples, for that was to extend to all men,
which command was '`To watch.`'
She said at another time, '`It has been in my mind this night,
to consider how it was with the disciples of Christ when they went fishing,
and toiled all night and caught nothing, until the Lord came,
and directed them to cast the net on the right side of the ship,
and then they obtained that which they labored for.
Now when we are laboring for the spiritual food, and for a season may find nothing,
let us patiently wait for the Lord`'s direction,
and then we shall surely obtain what will be sufficient for us;
for his wisdom is the same to direct his people now as ever it was in that day.`'

The 27th of the Fourth month, 1722, she signified to some friends who came to visit her,
that she had cause to choose a state of affliction,
because of the sweet enjoyment of the love of God,
which he was pleased to favor her with in a more plentiful manner than she had sometimes
experienced when she had more freedom from pain and affliction of body.

The 1st of the Fifth month.--'`It is the inward Comforter who leads
into all truth that we shall all one day stand in need of.
As there ought to be no careless delays in the great concern of working ou.
octr own salvation,
so we had need to be very diligently engaged in waiting
to be endowed with power from on high,
because we are not able to do any thing of ourselves
that will tend to our souls`' eternal welfare;
but as we are diligently waiting upon God, he will give us strength,
according to the service he shall require of us.
His people have cause to say, he is not a hard master,
for he will gather his lambs with his arms, and carry them in his bosom,
and gently lead those that are with young.
Let us be willing to part with all that the Lord requires us to part with,
although it be as near as a right hand or a right eye.

'`My friends, we have no continuing city here; let us therefore seek one that is to come,
whose builder and maker is the Lord.
Let not those be discouraged that are truly concerned to labor in the Lord`'s work,
although they may be but few in number,
the time may come when more may be rightly engaged in it.
Let us all give up freely to serve the Lord in whatever he requires of us,
for he requires obedience to the manifestations of his will, both in male and female.
I desire that those that are truly sensible of the lack of laborers,
may be concerned to pray the Lord of the harvest
to send forth more laborers into his harvest;
and that we may all be truly concerned for the honor of God,
and for the promoting of his truth, more than for any outward enjoyment,
and then the Lord will be with us, and stand by us in our exercises.
We know not what we may any of us have to o through,
before our time in this world may come to an end,
and when we come to lie upon a bed of sickness, and expect our end to be nigh,
nothing that this world can afford is worthy to be compared with peace of conscience.
Let it be our great care to be so prepared for the coming of the Lord,
that whether our days may be few or many in this world,
whensoever the Lord shall be pleased to call us hence, we may be ready.`'

The 14th of the Fifth month.--'`Although the Lord may be
pleased to lead us through the valley of the shadow of death,
yet we have cause to fear no ill,
as the eye of our minds is truly unto him who is invisible;
for he is near to his little ones,
supports them in the deepest exercises that they are brought into;
and therefore if the Lord be pleased to bring us down into Jordan,
let us be willing to follow him there as often as he shall see fit.

'`Although Naaman was to wash but seven times in Jordan that he might be made clean,
yet there is no such limitation to this inward work;
but if the Lord be pleased to try us seventy times seven,
we ought to yield willingly thereunto.
As the gold that is often tried is made the purer from dross
so as we are rightly bowed under the great Refiner`'s hand,
we shall be made the more fit for his service.

'`Let us patiently wait to see the work carried on that is upon the wheel,
that we may not be like the vessel that was marred in the hands of the potter,
but may be formed according to the will of God,
and purged from everything he has a controversy against.
And now the Lord is pleased once more to lift up
the light of his countenance upon my poor soul;
and in a sense thereof, I desire the praise, the glory and honor may be given to him,
to whom alone they belong forever.`'

The 15th of the Fifth month.--'`My friends, I did not know that.
I should have spoken any more, but now the Lord has been pleased once more to revive me,
and I have cause to speak for the encouragement of those that I am likely to leave behind,
that they may be encouraged to follow the Lord fully, and not fear man, who,
if he be permitted to put forth the utmost of his power,
can go no further than to kill the body.
But let us fear him who is able to destroy both body and soul.
Let us fear to offend the living God, who has the sovereignty over us,
and can do whatsoever he pleases with us.
Let us not shun the cross,
but be willing to bear our share of sufferings for the sake of Christ,
whether they be inward or outward, that our consolations may abound.
Let us labor for those inward, sweet enjoyments,
that abundantly exceed all outward visible things.

'`I desire we may come to see for ourselves that wonder which John saw,
"`A woman clothed with the sun,
and the moon under her feet;`" that we may know the
changeable things to be under our feet,
and may be clothed with the Son of Righteousness, who arises with healing in his wings:
and then we shall grow up before him as calves of the stall.`'

The 17th of the Fifth month.--'`Such is the goodness of God to those that wait upon him,
that he causes the dew to fall upon them that see themselves in a thirsty land,
until he is pleased to open the fountain for their refreshment.
I believe it is our great duty to center often to
the fountain from which our supplies come.
In what state soever we are,
the truth is the same in a time of sickness as it is in a time of health.
I desire we may not be like the man that falls being alone,
but may know the everlasting arm to be underneath
when we may see ourselves in danger of falling.
And as we have seen the good effects of it many a time,
I desire we may be diligent in waiting for this holy arm.
Let us wait to know our duty.
We have often heard, that they that wait upon the Lord shall renew their strength.
These come to see their duty, and they also receive ability to perform the same,
although at sometimes they may be so encompassed about,
that they may see no way of deliverance until the Lord opens an eye in them to see it;
yet the Lord will make way in his own time,
for the deliverance of his people who trust in him.`'

The 19th of the Fifth month.--'`There is one thing in particular
that I have observed in this time of weakness of body,
which I esteem as a privilege among many others that I am made partaker of,
and that is this: those days that my affliction is the greatest upon me,
the Lord has been pleased to favor me with the most plentiful visitation of his love,
whether I have had company, or have been alone;
so that thereby I have been encouraged willingly and patiently to bear these afflictions,
being made sensible that the inward enjoyment of the goodness
of God abundantly exceeds health of body,
and those outward enjoyments that I am deprived of.

'`We have cause to be humble before the Lord, from whom all that we have that is good,
comes; let us be willing to go down into the deep as often as he sees meet;
for he will destroy nothing in us that is good.
I believe those that go most down into the deep,
will see most of the wonders of the Lord.`'

The 21st of the Fifth month.--'`It is the Lord alone
that knows the needs of the poor in spirit,
and is able to administer a suitable supply according thereunto.
He can make a little sufficient, until he is pleased to give more,
as he made the little the widow had, sufficient in the prophet`'s time.
Such was his goodness to her, that the barrel of meal did not waste,
nor the cruse of oil fail, until the time that the Lord sent rain upon the earth,
although it was such a time of scarcity that she expected death was near.
I believe the Lord will be the same in this day to them
that have due regard to the voice of the great Prophet,
although at times their provision may appear to be but small,
he will make the little sufficient until the time that he
is pleased to favor them with plentiful showers of his love.
Therefore let us not murmur in a time of scarcity,
nor yet be exalted above measure in a time of plenty; but let us remember,
the hand that feeds us can withhold from us if he sees meet.`'

The 23rd of the Fifth month.--'`Blessed is the man that trusts in the Lord,
whose hope the Lord is, and whose heart departs not from the living God.
He shall be like a tree that is planted by the rivers of waters, whose leaves are green.
Although these may know winter seasons,
yet as their hearts do not depart from the living God,
they shall be like the branches that are grafted into the true vine,
and the living sap will abide in the root.
They shall know their establishment to be by the still waters,
as they are diligently waiting for and truly submitting to that power,
that pleads by fire and sword, against the appearance of that which is contrary to truth.
Let us be willing to yield up that that is for the fire, unto the fire;
and that that is for the sword, unto the sword; and that that is for the famine,
unto the famine; that we may be purged throughout in body, soul, and spirit,
and may know the will of God to be cone in us,
and may have a right to make use of that prayer which our Lord taught his disciples,
after this manner: "`Our Father, who art in heaven, hallowed be your name,
your kingdom come, your will be done in earth as it is in heaven.

'`Surely this is a great attainment,
and it is nothing but the power of God that is sufficient to bring us into this estate,
although many in the world are making use of these weighty words,
who are not truly sensible of them.
It is a great thing to know the great God to be our Father by regeneration.
Those that are his children by regeneration,
do desire that the praise may be returned to his holy name;
and that his will may be done in them as it is in heaven:
and these are passive as clay in the hand of the potter.

'`And they are concerned to ask daily bread of him,
who feeds his people with the bread of life.
They desire of him, that he will be pleased to forgive their trespasses,
as they desire to forgive those that trespass against them;
which the Lord gives them power to do.
And desire in their hearts, that they may not be led into temptation,
but may be delivered from evil, when they are beset as on every hand.`'

The 24th of the Fifth month.--'`When the Lord is pleased
to withhold from us the sweet enjoyment of his love,
although we may be sensible of the lack of it, yet we cannot reach it for ourselves,
and therefore we ought to bow in reverence before him.
He deals with us as a tender father may do with his child,
who may see fit to withhold food from him for a time,
that he may learn subjection to his father.
So the Lord may see fit to hide his face at some times from us,
as he did from his servant of old, who said, You hide your face, and I am troubled.
Although but a little before, he was so favored with the divine presence,
that he thought thereby his mountain was made to stand strong;
yet there was soon an alteration in his state.
When the Lord hid his face, he was troubled; and so it may be with us.
And when the Lord does withdraw from us, let us examine ourselves, that we may come,
by that which shows unto men what their states are,
to discern whether there is any thing amiss in us,
that might give the Lord just cause to withdraw from us.

'`I believe this inquiry will not hurt any of us, any more than it did the disciples,
when the Lord had told his disciples, that one of them should betray him; and one said,
"`Lord, is it I?`" and another said, "`Is it I?`" He that was the guilty person,
was the last as we find that asked this question:
and so those now that are guilty of betraying the innocent +++[+++life]
in themselves, may be the most backward in this work of examination.

'`Surely there is abundance in it; let us be willing to search ourselves,
that by the spirit of truth we may see whether we
are of that number that betray the innocent or not.
If, upon diligent search, we do not find that there is any willful disobedience in us,
to cause the Lord to withdraw from us, but.
it is for the trial of our faith, this, I believe, will be for our good,
as our minds are stayed in patience.
But if our minds are not stayed in patience, we may slight our own mercy,
for the Lord many times may be nearer than we are aware; and before we are aware,
may make our hearts like the chariots of Aminadab.
The Lord had regard to his servant who waited patiently for him,
and the Lord inclined to him, and heard his cry,
and brought him up out of the horrible pit and miry clay,
and put a new song into his mouth, even praises to the Lord.`'

Afterwards, the same evening, she said,
'`Nothing will do now but this inward satisfaction, which the world cannot give,
neither can the world take it away, that is a comfort.
It is well to be concerned to lay up for ourselves this true riches,
which the moth or rust cannot corrupt, nor the thieves steal.
Whatever it may cost us of sufferings, scoffings, or reproaches for it,
it is worth a hundred times more than we have undergone of losses or sufferings.
"`For the sufferings of this present time are not worthy
to be compared with the glory that shall be revealed.

'`Now, if it be the will of the Lord to remove me hence,
if he will be pleased to support me in the needful time,
I think I can freely yield up my soul to Him who gave it,
that it may be delivered from this strait habitation that it is now in.
I do not find that there is any thing between the Lord and my soul,
but that I have free access to him by his Spirit.
As for this body, it seems to be compassed about with afflictions; and yet,
although I speak of my afflictions, I do not do it in a complaining way,
for I have no cause to complain.`'

The 26th of the Fifth month.--'`The Lord sees not as man sees;
for man looks at the outward appearance, but the Lord looks at the heart,
and therefore we had need be concerned that our hearts may be truly
prepared by his Spirit to receive a supply from his hand,
which he is graciously pleased to favor his people with;
for he is near to his people in their afflictions, and is as afflicted with them,
and the angel of his presence saves them.
The promises of God are all Yes and Amen in the one Seed.
Let us abide in it,
that we may know what we have to express one to another to spring from the pure Seed,
and may know it to bear rule in our hearts,
and then we shall be guided thereby to take straight steps in the narrow way,
which the Lord has cast up for us.

'`Let us be willing to wade through these exercises that it may be our lot to meet with,
for the trial of faith will work patience, and patience experience, and experience hope;
and this hope will not make ashamed.
Then we shall not be ashamed to bear our testimony for the Lord,
neither shall we think that because our measures are but small,
therefore we can do him no service, but we shall be willing to cast in our mites,
as the poor widow did.
If we cast in all, the Lord will take notice of it.

'`This I speak, that those may be encouraged in the work of the Lord,
who look upon themselves as the hindermost of the flock.
Let us not be discouraged,
although at some times the work may not seem so prosperous as we may desire:
"`Cast your bread upon the waters,`" and there is a promise,
that it shall be found after many days.
Sow plentifully therefore, that you may reap plentifully;
for those that sow sparingly, shall reap sparingly.
If sometimes we may have but a few words to speak in a meeting,
then let it be our concern to sow to the spirit, that by the light of it,
we may discern what the Lord is pleased to give us for our own comfort and nourishment;
and what he gives us, to distribute to others.
For we read, there is a time to be silent, and a time to speak;
and at sometimes there may be more service in sitting silently in a meeting,
than there would be in speaking words; and as our eyes are single unto the Lord,
and our wills resigned to his pure will, this waiting in silence will be easy to us.
And as in the pure light we shall come to see what, and when to speak, and when to end,
having a clear sight of our duty herein, we shall go safely on.`'

The same evening calling her son to her,
she signified her desire that as the Lord had been pleased to lend him to them,
he might also be pleased to make him his servant,
and give him a place in the house of the Lord.
And she advised him to be obedient to his father.

The 27th of the Fifth month.--'`Our natural lives are very uncertain.
The time past is irrecoverable, and the time to come is very uncertain;
therefore let us be concerned to make good use of this present time,
and be willing to put our shoulders to the work,
that the stone may be rolled from the well`'s mouth,
that we may partake together of the goodness of God.

'`Those that gathered little manna, had no lack; and those that gathered much,
had nothing over.
My friends, there s abundance in it; those whose gifts may be but small,
so that they cannot gather so large a share of the heavenly manna as some may,
yet if they labor faithfully, according to the ability that God is pleased to give them,
and make a right improvement of what he has committed to them,
they will know that little to be sufficient.
And those that are enabled to gather more, will come to see that they have nothing over;
and that what they enjoyed yesterday will not be sufficient for today,
but they will stand daily in need of a fresh supply from the hand of the Lord.

'`There is no other name by which any of us can be saved, but Jesus Christ.
Let us labor to get into his name, for he has promised,
that where two or three are gathered together in his name,
he will be in the midst of them.
And he will make his promise good unto all them that are truly concerned
to labor to get through all the opposition that stands in their way,
that so they may get into the name, spirit, and power of Christ,
and witness him to be as a place of broad rivers unto them.

'`We had need to be concerned for that treasure that will go with us beyond the grave;
this is worth suffering the loss of all things for.
For those that are willing to lose their lives for Christ`'s sake,
the same shall find life eternal.
But those that retain a life in sin, according to the lusts of the flesh,
are in danger of losing that eternal life in the world to come.

'`Therefore let us not love our lives unto the death,
nor count any thing too dear to part with, that we may win Christ.
I desire that the longer we live in the world, the more our zeal for the Lord,
and his truth, may increase.
"`Many are the troubles of the righteous,
but the Lord will deliver them out of them all.`"`'

The 29th of the Fifth month.--Having spoken of her afflictions,
she spoke to this purpose: '`I have no cause to complain,
for I am satisfied the Lord has a good end in it.
He shows his sufficiency to bring his people through abundance of affliction.
I believe that peace and rest will be the sweeter to the weary travelers,
when they come to the full enjoyment of them, without any mixture of sorrow.

'`I believe if there was anything now remaining, that is contrary to the will of God,
he would make it manifest.
It has many times been the sincere desire of my heart to the Lord,
that every secret thing might be revealed; and the Lord is just in all his ways.
As we are truly willing to bring our deeds to the light in our hearts,
the Lord thereby will discover everything that is contrary to his will in us.
The Lord is able to do all things for his people.

'`Testimonies will fail, and words come to an end as to us,
but the word of the Lord will abide forever.
I desire that those who may have more days in this world,
may diligently attend to this engrafted Word, that is able to save the soul.
Let us choose this for our portion.

'`My desire for the sons and daughters of men is,
that they may not give way so much to the many cumbering things,
but may choose this one thing needful,
which will be able to support them in the most needful time.
For if we are taken with anything short of this eternal Word,
and trust in visible things, they will utterly fail.`'

The 31st of the Fifth month.--'`The goodness of the Lord is such to his people,
that he is a present helper in the needful time,
although at some times we may be ready to think that
we shall fall by the hand of the enemy;
yet as we trust in the Lord, he that delivered David out of the hand of Saul,
will deliver us out of the hand of the spiritual enemy.

'`Let us stay our minds in patience, in the times of poverty of spirit,
and I believe we shall see the good effects of it;
the Lord will teach us subjection to himself thereby;
and when he gives us a little taste of his love,
we shall see that we ought to wait upon him,
until he shall be pleased to cause the showers thereof
more plentifully to fall upon us.

'`It is an easy thing to believe in him, when his candle shines upon us,
and we enjoy the light of his countenance; but when he withdraws from us,
and we see ourselves in a thirsty land, where no water is, this, I believe,
is a trial of faith.
That arm of the Lord which has been the guide of our youth,
will be the stay of the aged who trust in it.
When we are brought to a true sense of a spiritual thirst,
the Lord will open the fountain as in the desert.

'`I think I have a few words to speak for the encouragement
of those that I may be likely to leave behind me,
that they fear not man, whose breath is in his nostrils, but that they may fear the Lord;
for they that fear the Lord shall not be confounded,
and they that trust in him shall not be ashamed.
I think a few words at this time may suffice, because of the weakness I am under;
but however I once more witness the Lord to be strength in weakness; in a sense thereof,
I desire the praise may be returned to him, who is worthy of it forever.`'

The 2nd of the Sixth month.--'`The Lord is making
his people sensible of the time to be silent,
and of the time to speak, as they are concerned to wait for instruction from him,
and to hearken to his voice, and to the voice of his servant the prophet, who said,
"`Keep silence, O islands, before me; let the people renew their strength.`"
They were to come near, and then they were to speak; and so it is now,
when we are enabled to come near the Lord,
we are sometimes in a capacity to speak to the honor of his name.

'`I desire that we may follow the Lord, whensoever he is pleased to go forth before us;
and when he is pleased to stand still, let us be willing to be as nothing;
and not think our own thoughts, nor speak our own words; nor walk in our ways.
Let us wait for a fresh command from our great lawgiver,
that according thereto we may go forth in his service, and may know our thoughts, words,
and actions, to be sanctified by his Spirit, that his will in all things may be done,
and then the Lord will be with us,
and bless the labor of love that such are concerned in.
The Lord is once more giving me cause to speak well of his name.
in a renewed sense of his love.
This is an encouragement to trust in his mercy, and when in a state of poverty,
the enemy may assault us,
and may endeavor to cause us to think that we shall never
come to partake of those sweet enjoyments any more,
as we have in times past; let us not believe him, for he was a liar from the beginning.

'`It was when the master of the house had fasted long, and hungered,
that the enemy assaulted him with his temptations.
But our Lord obtained the victory, and he will preserve his people,
that not one hair of their heads shall fall to the ground without his permission.
Although the Lord`'s people may have sorrow as for a night,
yet joy will come in the morning, in the dawning and breaking forth of that eternal day,
when the sun shall arise that shall go no more down;
which is for the light of the New Jerusalem, which has no need of the outward sun,
nor of the moon, for the Lord God is the light thereof,
and sorrow and sighing shall come to an end,
and the tears shall be wiped from all faces.

'`Surely this is a desirable habitation to the weary travelers,
but we ought patiently to wait the Lord`'s time.
Let us be willing to bear our share of sufferings,
remembering what our Lord suffered for us when we were enemies and aliens;
and the Lord might justly have cut us off in that state,
but he was pleased to show mercy unto us.

'`Let us be willing to follow him through many tribulations,
through the assistance of his Spirit,
that we may be found worthy to obtain an inheritance in
the kingdom that is prepared for the followers of the Lamb.
When we have done all, we are but as unprofitable servants;
we have done no more than was our duty to do; there is nothing to be attributed to us,
neither is there any praise belongs unto such, but to God only.`'

The 4th of the Sixth month.--'`It is the inward comforter that our
Lord promised he would pray the Father to send to his followers,
that in my measure I am a, witness of, and this inward enjoyment sweetens every exercise.
I desire we may all wait for it in a sense of our needs,
that we may receive a daily supply from it.
There is something of trial to be met with every day,
and therefore we have need of a supply from the Lord,
to enable us to go forward in the way of our duty.
The goodness of God is very great, and in a feeling sense of it, I have, at this time,
renewed occasion to return the praises to his holy name.`'

The same evening, speaking of the gradual decay of natural strength she was sensible of,
she said, "`The Lord gives, and he takes away, blessed be his name.`"

The 17th of the Sixth month.--'`Being scarcely two days and a half before she departed,
several friends being there to visit her about the seventh hour in the evening,
they found her very weak,
but after they had spent some time in waiting upon the Lord with her,
the Lord was graciously pleased to renew the visitation of his love to her,
by which she was wonderfully revived,
and was publicly concerned in thankful acknowledgments of the goodness of God,
in supplication to him for the continuance thereof.

She had also an exhortation to the Friends,
to follow the Lord in obedience to his requirings; for she signified,
that while disobedience remains in the heart, it tends to hinder the work of the Lord,
and therefore it was her desire, that all might be given up freely to follow the Lord,
that they might know his ways to become ways of pleasantness to them.

She departed this life the 20th day of the Sixth month, 1722,
between the hours of four and five in the morning,
being in the forty-first year of her age.
