== Chapter 1

[.chapter-synopsis]
* James Parnell
* John Camm
* William Robinson
* Mary Dyer
* William Leddra
* Thomas Forster
* Richard Hubberthorn
* Edward Burrough

JAMES PARNELL, born at Retford, in Nottinghamshire,
was a young man who received the blessed truth early.
About the year 1654, he visited George Fox, who was at that time a prisoner in Carlisle,
where he disputed with, and confuted, many priests and others;
and afterwards travelled southward, preaching truth,
and disputing with its opposers in Huntingtonshire, the Isle of Ely,
and some parts in Cambridgeshire, being then in the eighteenth year of his age.

He was the first called a Quaker who preached the gospel in the county of Essex, namely,
at Stebbing, Felsted, Witham, Coggeshall, Halsted, etc.,
by whose ministry many thousands were turned to the Lord Jesus Christ.

About the middle of summer, 1655, he came to Colchester, and on the next day,
being the first-day of the week,
he preached the gospel to thousands of people in that town, first at his lodging,
then at the public parish place of worship,
and then in a great meeting appointed on purpose.
After that he disputed with the town-lecturer,
and with another priest in the French school.
All this was in one day;
in which the wisdom and patience of Christ appeared very gloriously,
for the convincing of many who believed; and he put to silence, by his sound doctrine,
the gainsayers.
But some hardened their hearts, others beat him with their fists and staves,
as particularly one, who struck him with a great staff as he came out of a steeple-house,
and said, '`There, take that for Christ Jesus`'s sake:`' to which he returned this answer,
'`Friend, I do receive it for Jesus Christ his sake.`'
And many other intolerable affronts they offered him.

After he had labored in Colchester, he went back to Coggeshall,
where the professors had appointed a fast.
From there he was committed to Colchester Castle,
and then had in irons to Chelmsford assizes, and there was fined forty pounds,
and committed back again to Colchester.
Here they allowed none to come to him but such as came to scorn, abuse, and beat him;
not allowing him at some times to have food brought to him,
and at other times took the food away when it was brought to him;
and forced him to lie on the stones, which in wet seasons would run down with water.
Then they put him into a hole in the wall, high from the ground,
where the ladder was too short by six feet,
not permitting his victuals to be brought to him,
nor he to draw it up with a basket and a cord, which his friends had provided,
but he must either come down by a rope, or famish in the hole.

After long suffering in this hole,
it having no place either for the air or smoke to pass out,
his limbs were so much benumbed, that one day climbing up to the top of the ladder,
and catching at the rope with his other hand, he missed it,
and fell from a very great height down upon the stones,
whereby he was exceedingly wounded in his head and body, and taken up for dead.
After that they put him into another little hole called the Oven (some ovens more broad),
where they would not allow him to have charcoal, neither would they accept of bail,
nor body for body, which his friends offered, that he might recover of his hurts.
One day, the door being open, he did but once get out of that nasty close hole,
and walk for a little air into a stinking yard before the door,
when the jailor came in a rage and locked up the hole,
and shut him out in the yard all night, being in the coldest time in all the winter.
By these cruelties he grew weaker and weaker,
finding no mercy at the hands of his enemies.
Near his departure he said (being all along borne up in much patience),
'`Here I die innocently:`' and further said, '`Now I must go:`' and turned his head,
and said, '`This death I must die:
I have seen glorious things;`' and to his friends about him, '`Will you hold me?`'
One of them said, '`Dear heart, we will not hold you.`'
Then he said, '`Now I will go:`' and stretching himself out,
fell into a sweet sleep for about an hour (as he often had said,
one hour`'s sleep would cure him of all), and so drew breath no more.
He died about the nineteenth year of his age, in the year 1656.

[.asterism]
'''

JOHN CAMM, born at Cam`'s-gill, within the barony of Kendal,
in the county of Westmoreland, was a man inclined to religion of the strictest sort,
from his childhood.
He, with many more, who sought after the best things,
separated themselves from the national worship of those times,
and met apart at a place called Firbank chapel, and other places,
among which people he was sometimes a preacher.
But in the year 1652, he was (with many hundreds of the congregation,
among whom were John Audland, Francis Howgill, Edward Burrough,
and Richard Hubberthorn) convinced of the truth,
by the preaching of that servant of the Lord, George Fox.
He submitted to the mighty power of the Lord,
and the operation of his blessed Spirit in his heart,
and was made willing to take up the cross,
and forsake the glory and friendship of the world; and after a day of great trouble,
through the spirit of judgment and burning,
wherein he found the old heavens and earth to pass away; even as a prepared vessel,
the Lord filled him with his power, and put his word into his mouth,
and sent him forth to publish the same;
and he was obedient and travelled into all the northern counties,
to the borders of Scotland, and from there to London, in company with Francis Howgill,
with a message from the Lord to Oliver Cromwell, then protector.

After his return from London into the north he, with John Audland, Francis Howgill,
Edward Burrough, and Richard Hubberthorn, went southward;
John Camm and Edward Burrough traveling through the middle of the nation,
the others through other parts, and they met together at London,
with several other of their brethren.

After some time, John Camm and John Audland were called towards Bristol,
where an effectual door was opened to them, and many hundreds were,
by their word and testimony which they published, turned to God.

John Camm was naturally of a weak constitution of body,
and by the daily travels that he underwent, spent his strength exceedingly,
and had a violent cough a considerable time before his death.
He was a man richly furnished with the gifts of the Holy Spirit, patient in exercises,
grave in behavior, profound in judgment, quick in discerning,
and a sharp reprover of wickedness, hypocrisy,
and of disorderly walkers in the profession of truth.
Unity of brethren was his soul`'s delight; his ministry weighty and deep,
not pleasant to itching ears, but reached the witness of God;
careful not to make the gospel chargeable, having an estate of his own;
and often suffered the spoiling of his goods joyfully,
in a faithful testimony against tithes.

He would often call his children together, and exhort them to fear the Lord;
and would wonderfully praise God for his goodness,
counting his bodily weakness a happiness,
being sanctified unto him by that word which had sanctified his soul;
under the sense of which he would say, '`How great a benefit do I enjoy beyond many.
I have such a large time of preparation for death, being daily dying,
that I may live forever with my God in that kingdom that is unspeakably full of glory.
My outward man daily wastes and moulders down, and draws towards its place and center;
but my inward man revives and mounts upwards towards
its place and habitation in the heavens.`'

The morning he departed this life, he called his wife, children and family,
and gave them seasonable instruction to love the Lord, and his way, and truth,
and to walk in the same, saying, his glass was run; the time of his departure was come;
he was to enter into everlasting ease, joy and rest;
charging them all to be patient and content in parting with him.
So, presently fainting, he passed quietly away as into a sweet sleep,
whereupon some about him did weep aloud; at which he was awakened as out of a sleep,
and desired to be helped a little upon his bed, saying,
'`My dear hearts you have wronged me, and disturbed me, for I was at sweet rest.
You should not passionately sorrow for my departure.
This house of clay must go to its place,
but this soul and spirit is to be gathered up to the Lord, to live with him forever,
where we shall meet with everlasting joy.`'
So, again taking his leave of every one of them,
charging them to be content with his departure, he lay down,
and in a little time departed this life.
He was convinced in 1652, and died in 1656, being aged about fifty-two years.

[.asterism]
'''

WILLIAM ROBINSON, of London, merchant, and Marmaduke Stevenson, of Yorkshire, husbandman,
both suffered martyrdom for their obedience to God,
in bearing their testimony to his blessed truth in New England,
on the 27th of the Eighth month, 1659.

When they were brought before the court of Boston in New England,
on the 20th of the said month, the governor said to them, '`We have made laws,
and endeavored several ways to keep you from us, and neither whipping, nor imprisonments,
nor cutting off ears, nor banishment upon pain of death, will keep you from among us.
Give ear, and hearken to your sentence: You shall go to the place from which you came,
and from there to the gallows, and be hanged till you are dead.`'

Accordingly the said William Robinson and Marmaduke Stevenson, with Mary Dyer,
were taken out of prison; who having parted with their friends in prison,
full of the joy of the Lord, who had counted them worthy to suffer for his name,
and having embraced each other with fervency of love and gladness of heart,
in peace with God, were led to the place of execution the back way,
lest their innocent sufferings should too much affect the people;
and when they attempted to speak,
their cruel persecutors caused the drums to be beaten to drown their voice.

One of their chief preachers, meeting the said sufferers going to be executed,
said tauntingly, and shaking his head in a scoffing manner,
'`Shall such jacks as you come in before authority, with your hats on?`'
To which William Robinson said to the people, '`Mind you,
it is for not putting off our hats that we are put to death.`'
When he was upon the ladder, he spoke to the people thus;
that they suffered not as evil-doers,
but as those who testified and manifested the truth,
and that this was the day of their visitation;
and therefore desired them to mind the light that was in them,
which was the Light of Christ; of which they testified,
and were now going to seal it with their blood.
So the executioner put William Robinson to death, and afterwards Marmaduke Stevenson,
who both of them died full of the joy of the Lord, and stood fast in him,
sealing their testimony with their blood,
their countenances not changing when the halters were about their necks.

Their enemies not permitting their bodies to be taken down, cut them down,
and the fall broke the skull of William Robinson;
and with their knives they ripped off their shirts,
and dragged their naked bodies into a hole,
not allowing their friends to take them away and bury them;
and afterwards when a friend brought pales to enclose the ground,
that the brute beasts might not prey on their bodies, it was denied him;
and their bodies were left in a pit in the open field,
which was soon covered with water.

Here follows a copy of William Robinson`'s paper, offered to the court,
before he was sentenced to death, concerning their coming into those parts,
for which they were put to death; which was denied by the governor to be read.

[.embedded-content-document.paper]
--

On the 8th day of the Eighth month, 1659, in the after part of the day,
in traveling between Newport in Rhode Island and Daniel Gould`'s house,
with my dear brother Christopher Holder, the Word of the Lord came expressly to me,
which did fill me immediately with life and power, and heavenly love,
by which he constrained me, and commanded me to pass to the town of Boston,
my life to lay down in his will, for the accomplishing of his service,
that he had there to perform at the day appointed.
To which heavenly voice I presently yielded obedience,
not questioning the Lord how he would bring the thing to pass, being I was a child,
and obedience was demanded of me by the Lord,
who filled me with living strength and power from his heavenly presence,
which at that time did mightily overshadow me,
and my life at that time did say amen to what the Lord required of me,
and had commanded me to do, and willingly I was given up from that time to this day,
the will of the Lord to do and perform, whatever became of my body.

For the Lord had said unto me, my soul shall live in everlasting peace,
and my life shall enter into rest, for being obedient to the God of my life.
I being a child, dared not question the Lord in the least,
but rather willing to lay down my life than to bring dishonor to the Lord.
And as the Lord made me willing, dealing gently and kindly with me,
as a tender father by a faithful child whom he tenderly loves,
so the Lord did deal with me, in ministering his life unto me,
which gave and gives me strength to perform what the Lord required of me.
And still as I did and do stand in need,
he ministered and ministers more strength and virtue, and heavenly power and wisdom,
whereby I was and am made strong in God,
not fearing what man shall be allowed to do unto me, being filled with heavenly courage,
which is meekness and innocence, for the cause is the Lord`'s that we go in,
and the battle is the Lord`'s; and thus says the Lord of Hosts,
the mighty and the terrible God, "`Not by strength, nor by might, nor by power of man,
but by my Spirit,`" says the Lord of Hosts.
'`I will perform what my mouth has spoken, through my servants, whom I have chosen;
my elect, in whom my soul delights.`'

Friends, the God of my life, and the God of the whole earth, did lay this thing upon me,
for which I now suffer bonds near unto death.
He, by his Almighty power, and everlasting love, constrained me,
and laid this thing upon me, and truly I could not deny the Lord,
much less resist the Holy One of Israel.
Therefore all who are ignorant of the motion of the Lord in the inward parts,
be not hasty in judging in this matter, lest you speak evil of the thing you know not.
Of a truth, the Lord God of heaven and earth commanded me by his spirit,
and spoke unto me by his Son, whom he has made heir of all things,
and in his life I live, and in it I shall depart this earthly tabernacle,
if unmerciful men be allowed to take it from me.

Herein I rejoice, that the Lord is with me, the Ancient of Days,
the Life of the suffering Seed, for which I am freely given up,
and singly do I stand in the will of God; for to me to live is Christ,
and to die is gain.
Truly I have great desire and will herein, knowing that the Lord is with me,
whatever ignorant men shall be able to say against me;
for the witness of the spirit I have received,
and the presence of the Lord and his heavenly life accompany me,
so that I can say in truth, and from an upright heart,
Blessed be the Lord God of my life, who has counted me worthy, and called me hereunto,
to bear my testimony against ungodly and unrighteous men,
who seek to take away the life of the righteous without a cause;
as the rulers of Massachusetts Bay do intend,
if the Lord stop them not from their intent.

Oh! hear you rulers, and give ear and listen,
all you that have any hand herein to put the innocent to death, for in the name,
and fear, and dread of the Lord God,
I here declare the cause of my staying here among you,
and continuing in the jurisdiction after there was
a sentence of banishment upon pain of death,
as you said, pronounced against me without a just cause;
as you all know that we that were banished committed nothing worthy of banishment,
nor of any punishment, much less banishment upon pain of death.
And now, you rulers, you do intend to put me to death, and my companion,
unto whom the word of the Lord came, saying,
Go to Boston with your brother William Robinson.
Unto which command he was obedient, who had said unto him,
he had a great work for him to do.
This thing is now seen, and the Lord is now doing it; and it is in obedience to the Lord,
the God of the whole earth, that we continued among you,
and that we came to the town of Boston again, in obedience to the Lord,
the Creator of heaven and earth, in whose hand your breath is.
Will you put us to death for obeying the Lord, the God of the whole earth?
Well, if you do this act, and put us to death, know this, and be it known unto you all,
you rulers and people within this jurisdiction,
that whosoever has an hand therein will be guilty of innocent blood.
Not only upon yourselves will you bring innocent blood, but upon the town,
and the inhabitants thereof, and everywhere within this jurisdiction,
that had the least hand therein.
Therefore be instructed, you rulers of this land, and take warning betimes,
and learn wisdom, before it be hid from your eyes.

[.postscript]
====

Written in the common jail the 19th of the Eighth month, 1659, in Boston,
by one who fears the Lord, who is by ignorant people called a Quaker,
and unto such am I only known by the name of William Robinson,
yet a new name have I received, which such know not.

====

--

Here follows a copy of Marmaduke Stevenson`'s paper
of his call to the work and service of the Lord,
given forth by him a little before he was put to death,
and after he had received his sentence.

[.embedded-content-document.paper]
--

In the beginning of the year 1655, I was at the plough in the east parts of Yorkshire,
in old England, near the place where my outward being was.
And as I walked after the plough,
I was filled with the love and presence of the living God,
which did ravish my heart when I felt it;
for it did increase and abound in me like a living stream,
so did the life and love of God run through me like
a precious ointment giving a pleasant smell,
which made me to stand still.
As I stood a little still, with my heart and mind stayed upon the Lord,
the word of the Lord came to me in a still small voice, which I did hear perfectly,
saying to me, in the secret of my heart and conscience,
I have ordained you a prophet unto the nations.
At the hearing of the word of the Lord I was put to a stand,
seeing that I was but a child for such a weighty matter.

So, at the time appointed, Barbados was set before me,
unto which I was required of the Lord to go, and leave my dear and loving wife,
and tender children; for the Lord said unto me, immediately by his Spirit,
that he would be as a husband to my wife, and as a father to my children,
and they should not lack in my absence, for he would provide for them when I was gone.
I believed the Lord would perform what he had spoken,
because I was made willing to give up myself to his work and service,
to leave all and follow him, whose presence and life is with me,
where I rest in peace and quietness of spirit, with my dear brother,
under the shadow of His wings,
who has made us willing to lay down our lives for his name`'s sake,
if unmerciful men be allowed to take them from us; and if they do,
we know we shall have peace and rest with the Lord forever in his holy habitation,
when they shall have torment night and day.

In obedience to the living God,
I made preparation to pass to Barbados in the fourth month, 1658.
After some time that I had been on the said island in the service of God,
I heard that New England had made a law to put the servants of the living God to death,
if they returned after they were sentenced away, which did come near me at that time;
and as I considered the thing, and pondered it in my heart,
immediately came the word of the Lord unto me, saying,
'`You know not but you may go there.`'
I kept this word in my heart, and did not declare it to any until the time appointed.
So after that, a vessel was got ready for Rhode Island, which I passed in.

After a little time that I had been there, visiting the seed which the Lord had blessed,
the word of the Lord came to me, saying,
'`Go to Boston with your brother William Robinson;`' and at his command I was obedient,
and gave up to his will, that so his work and service may be accomplished:
for he had said unto me, that he had a great work for me to do,
which is now come to pass.
For yielding obedience to, and for obeying the voice and command of the Everlasting God,
which created heaven and earth, and the fountains of waters, do I, with my dear brother,
suffer outward bonds, near unto death.
And this is given forth to be upon record, that all people may know who hear it,
that we came not in our own wills, but in the will of God.

Given forth by me, who am known to men by the name of Marmaduke Stevenson;
but have a new name given me, which the world knows not of,
written in the Book of Life.

[.signed-section-context-close]
Written in Boston Prison, in the Eighth Month, 1659.

--

[.asterism]
'''

MARY DYER, a faithful woman, fearing God,
the wife of a husband of good estate in Rhode Island, and mother of several children,
was also condemned to death at the same time with William Robinson and Marmaduke Stevenson.
When she received the sentence,
that she should be hanged at the place of execution till she was dead, she replied,
'`The will of the Lord be done.`'
Then the governor saying take her away, she answered, '`Yes,
joyfully shall I go;`' and was led to the place of execution between her two fellow-sufferers,
William Robinson and Marmaduke Stevenson.
One of her enemies upbraiding her therewith, she replied,
'`It is the greatest joy and honor I can enjoy in this world;`' adding these words,
'`No eye can see, no ear can hear, no tongue can speak, no heart can understand,
the sweet incomes and refreshings of the spirit of the Lord which I now enjoy.`'
Having seen her two friends die before her face, and giving herself up to die also,
her hands and feet being tied, and her face covered, with the halter about her neck,
she was even with the Lord in joy and peace, an order came for her reprieve,
upon the petition of her son; which being read, and the halter taken off, and she loosed,
was desired to come down; but she tarrying to wait upon the Lord to know his mind,
they pulled her down with the ladder, and had her to prison,
and next morning she was carried out of the country towards Rhode Island.
And as a lively testimony of the virtue of truth, which can look death in the face,
and to be a record to future generations, how truth has conquered in a woman,
is here inserted Mary Dyer`'s letter, which she wrote the day after her reprieve,
as follows:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
The 28th of the Eighth Month, 1659.

Once more to the general court assembled in Boston, speaks Mary Dyer, even as before.
My life is not accepted, neither avails me,
in comparison of the lives and liberty of the truth and servants of the living God,
for which, in the bowels of love and meekness I sought you; yet, nevertheless,
with wicked hands have you put two of them to death, which makes me to feel,
that the mercies of the wicked are cruelty.
I rather choose to die than to live, as from you, as guilty of their innocent blood.

Therefore, seeing my request is hindered,
I leave you to the righteous Judge and searcher of all hearts,
who with the pure measure of light he has given every man to profit withal,
will in his due time let you see whose servants you are,
and of whom you have taken counsel, which I desire you to search into.
But all his counsel has been slighted, and you would none of his reproofs.
Read your portion; for verily the night comes on quickly, wherein no man can work,
in which you shall assuredly fall to your own master.
In obedience to the Lord, whom I serve with my spirit, and in pity to your souls,
which you neither know nor pity,
I can do no less than once more warn you to put away the evil of your doings,
and kiss the Son, the light in you, before his wrath be kindled in you.
For where it is, nothing without you can help or deliver you out of his hand at all,
and if these things be not so, then say,
there has been no prophet from the Lord among you: though we be nothing,
yet it is his pleasure, by things that are not, to bring to nought things that are.

When I heard your last order read, it was a disturbance to me,
that was so freely offering up my life to him that gave it me, and sent me here so to do.
This obedience being his own work, he gloriously accompanied with his presence,
and peace, and love in me, in which I rested from my labor,
till by your order and the people I was so far disturbed,
that I could not retain any more of the words thereof,
than that I should return to prison and there remain forty and eight hours,
to which I submitted, finding nothing from the Lord to the contrary,
that I may know what his pleasure and counsel is concerning me, on whom I wait therefore;
for he is my life, and length of my days; and as I said before, I came at his command,
and go at his command.

[.signed-section-signature]
Mary Dyer

--

Mary Dyer being thus freed as aforesaid, returned to Rhode Island,
where her husband and children dwelt, and after some stay with them,
she went towards Long Island, and was at Shelter Island,
and had good service for the Lord; where she thought she might pass home to Rhode Island:
but she was moved of the Lord to return to Boston again,
and she came there on the 21st of the Third month, 1660.
On the 31st of the same she was sent for to the general court,
where the governor said to her,

[.discourse-part]
_Governor:_ Are you the same Mary Dyer that was here the last general sessions?

[.discourse-part]
_Mary Dyer:_ I am the same Mary Dyer.

[.discourse-part]
_Governor:_ You will own yourself a Quaker, will you not?

[.discourse-part]
_Mary Dyer:_ I own myself to be so reproachfully called.

[.discourse-part]
_Governor:_ The sentence was passed upon you the last general court, and now likewise;
you must return to the prison from which you came,
and there remain till tomorrow at nine o`'clock,
then from there you must go to the gallows, and there be hanged till you are dead.

[.discourse-part]
_Mary Dyer:_ This is no more than what you said before.

[.discourse-part]
_Governor:_ And now it is to be executed;
therefore prepare yourself tomorrow at nine o`'clock.

[.discourse-part]
_Mary Dyer:_ I came in obedience to the will of God to the last general court,
desiring you to repeal your unrighteous laws of banishment upon pain of death,
and that same is my work now, and earnest request,
because you refused before to grant me my request; although I told you,
that if you refused to repeal them,
the Lord would send other of his servants to witness against them.

[.discourse-part]
_Governor:_ Are you a prophet?

[.discourse-part]
_Mary Dyer:_ I spoke the words that the Lord spoke in me.

And beginning to speak of the call of the Lord to her, the governor said, '`Away with her,
away with her.`'
So she was had to prison, and kept close till the next day at the ninth hour,
when the marshal called hastily for her; to whom she mildly replied, '`Stay a little;
I shall be ready presently.`'
But he cruelly replied, he could not wait upon her.
So he had her away with a company of soldiers, beating a drum before and behind,
that they might not hear her speak; and being upon the ladder at the place of execution,
some said to her, if she would return, she might save herself.

[.discourse-part]
_Mary Dyer:_ No, I cannot; for in obedience to the will of the Lord God I came,
and in his will I abide faithful unto death.

[.offset]
A priest called out to her, '`Mary Dyer, O repent, repent.`'

[.discourse-part]
_Mary Dyer:_ No, man; I am not now to repent.

[.offset]
One said that she should say that she had been in paradise.

[.discourse-part]
_Mary Dyer:_ Yes, I have been in paradise several days.

And more she spoke concerning her eternal happiness.
So, sweetly and cheerfully in the Lord she finished her testimony,
and died a faithful martyr of Jesus Christ, the 1st of the Fourth month, 1660.

Here follows the copy of a letter that Mary Dyer sent to the rulers of Boston,
after she had received sentence of death.

[.embedded-content-document.letter]
--

[.salutation]
To the General Court in Boston.

Whereas I am by many charged with guiltiness of my own blood:
if you mean in my coming to Boston, I am therein clear, and justified by the Lord,
in whose will I came, who will require my blood of you be sure,
who have made a law to take away the lives of the innocent servants of God,
if they come among you, who are called by you cursed Quakers; although I say,
and am a living witness for them and the Lord, that he has blessed them,
and sent them unto you.
Therefore be not found fighters against God,
but let my counsel and request be accepted with you, to repeal all such laws,
that the truth and servants of the Lord may have free passage among you,
and you be kept from shedding innocent blood,
which I know there are many among you would not do, if they knew it so to be.
Nor can the enemy, that stirs you up thus to destroy this holy seed,
in any measure countervail the great damage that you will by thus doing procure.

Therefore, seeing the Lord has not hid it from me, it lies upon me,
in love to your souls, thus to persuade you.
I have no self-ends, the Lord knows, for if my life were freely granted by you,
it would not avail me, nor could I expect it of you,
so long as I should daily hear or see the sufferings of these people, my dear brethren,
with whom my life is bound up, as I have done these two years;
and now it is like to increase even unto death, for no evil doing, but coming among you.
Were ever the like laws heard of among a people that profess Christ come in the flesh?
Have such no other weapons but such laws to fight with against spiritual wickedness,
as you call it?
Woe is me for you!
Of whom take you counsel?
Search with the light of Christ in you, and it will show you of whom, as it has done me,
and many more, who have been disobedient and deceived, as now you are.
As you come into this light, and obey what is made manifest to you therein,
you will not repent that you were kept from shedding blood, though by a woman.

It is not my own life I seek (for I choose rather to suffer with the people of God,
than to enjoy the pleasures of Egypt), but the life of the seed,
which I know the Lord has blessed;
and therefore the enemy thus vehemently seeks to destroy the life thereof,
as in all ages he ever did.
Oh! hearken not unto him, I beseech you, for the seed`'s sake, which is one in all,
and is dear in the sight of God, which they that touch, touch the apple of his eye,
and cannot escape his wrath; whereof I having felt,
cannot but persuade all men that I have to do withal; especially you,
who name the name of Christ, to depart from such iniquity as shedding blood,
even of the saints of the Most High.

Let my request have as much acceptance with you, if you be Christians,
as Esther`'s had with Ahasuerus,
whose relation is short of that which is between Christians,
and my request is the same that her`'s was; and he said not that he had made a law,
and it would be dishonorable for him to revoke it;
but when he understood that these people were so prized by her
(as in truth these are to me) you may see what he did for her.
Therefore I leave these lines with you,
appealing to the faithful and true witness of God, which is one in all consciences,
before whom we must all appear, with whom I shall eternally rest,
in everlasting joy and peace, whether you will hear or forbear: with him is my reward,
with whom to live is my joy, and to die is my gain,
though I had not had your forty-eight hours`' warning,
for the preparation to the death of Mary Dyer.

And know this also, that if through the enmity,
you shall declare yourself worse than Ahasuerus, and confirm your law,
though it be but the taking away the life of one of us,
that the Lord will overthrow both your law and you by his
righteous judgments and plagues poured justly upon you,
who now, while you are warned thereof, and tenderly sought unto,
may avoid the one by removing the other.

If you neither hear nor obey the Lord nor his servants,
yet will he send more of his servants among you, so that your ends shall be frustrated,
that think to restrain them you call cursed Quakers, from coming among you,
by any thing you can do to them.
Yes, verily, he has a seed here among you, from whom we have suffered all this while,
and yet suffer,
whom the Lord of the harvest will send forth more laborers
to gather out of the mouths of the devourers of all sorts,
into his fold, where he will lead them into fresh pastures,
even the paths of righteousness, for his name`'s sake.
Oh! let none of you put this day far from you, which, verily, in the light of the Lord,
I see approaching, even to many in and about Boston,
which is the bitterest and darkest professing place,
and so to continue so long as you have done, that ever I heard of.
Let the time past therefore suffice for such a profession
as brings forth such fruits as these laws are.

In love and in the spirit of meekness, I again beseech you,
for I have no enmity to the persons of any;
but you shall know that God will not be mocked, but what you sow,
that shall you reap from him,
that will render to every one according to the deeds done in the body,
whether good or evil; even so be it, says Mary Dyer.

--

[.asterism]
'''

WILLIAM LEDDRA, an inhabitant of the island of Barbados,
who came also into the jurisdiction of bloody Boston in New England,
to visit his friends who lay under great sufferings in prison,
was himself cast into prison, and locked in chains, with a log of wood tied to him,
lying down and rising up with the same, during a miserably cold winter,
in an open prison, till the First month, 1661,
when he was brought to the court at Boston with his chains and log at his heels.
The court told him that he was found guilty, and was to die.

[.discourse-part]
William Leddra asked what evil he had done.

[.discourse-part]
The court replied that his own confession was as good as a thousand witnesses.

[.discourse-part]
_William Leddra:_ What was that?

[.discourse-part]
The court answered, that he had owned, that those who were put to death, namely,
William Robinson, Marmaduke Stevenson, and Mary Dyer, were innocent +++[+++of that]
for which they died; and that he would not put off his hat in court,
and that he would say thee and thou to the magistrates.

[.discourse-part]
_William Leddra:_ Then you put me to death for speaking English,
and for not putting off my clothes.

[.small-break]
'''

After some more words they pronounced sentence of death upon him,
and on the 14th of the First month, 1661, they knocked off his chains,
and he took his leave of his fellow-prisoners in most tender love,
led as a sheep to the slaughter, in the meekness of the spirit of Jesus,
resigned up in the will of God to seal the truth of the testimony he had borne,
with his blood.
Being encompassed with the guards, and as he was about to ascend the ladder, he said,
'`All that will be Christ`'s disciples must take up the cross.`'
And standing where the guards ordered him,
with an exceedingly fresh living countenance he spoke to the people, and said,
'`For bearing my testimony for the Lord against deceit, and the deceived,
am I brought here to suffer:`' which much affected the people.
And as the executioner was putting the halter about his neck,
in the meekness and sense of Christ Jesus he said, '`I commit my cause to you, O God.`'
And just at turning off the ladder he called out, '`Lord Jesus receive my spirit.`'

[.embedded-content-document.epistle]
--

[.letter-heading]
An Epistle of William Leddra, to Friends,
written by him the day before he was put to death.

[.salutation]
To the society of the little flock of Christ, grace and peace be multiplied.

Most dear and inwardly beloved!
The sweet influences of the morning star, like a flood,
distilling into my innocent habitation,
have so filled me with the joy of the Lord in the beauty of holiness,
that my spirit is as if it did not inhabit a tabernacle of clay,
but is wholly swallowed up in the bosom of eternity, from which it had its being.

Alas!
Alas!
What can the wrath and spirit of man that lusts to envy,
aggravated by the heat and strength of the king of the locusts,
which came out of the pit, do unto one that is hid in the secret places of the Almighty?
Or unto them that are gathered under the healing wings of the prince of peace?
Under his armor of light they shall be able to stand in the day of trial,
having on the breast-plate of righteousness, and the sword of the spirit,
which is their weapon of war against spiritual wickedness, principalities and powers,
and the rulers of the darkness of this world, both within and without.`'

O my beloved, I have waited like a dove at the windows of the ark,
and have stood still in that watch, which the Master, without whom I could do nothing,
did at his coming reward with the fulness of his love, wherein my heart did rejoice,
that I might in the love and life of God speak a few words to you,
sealed with the spirit of promise,
that the taste thereof might be a savor of life to your life,
and a testimony in you of my innocent death.
And if I had been altogether silent, and the Lord had not opened my mouth unto you,
yet he would have opened your hearts,
and there have sealed my innocence with the streams of life,
by which we are all baptized into that body which is of God,
with whom and in whose presence there is life, in which, as you abide,
you stand upon the pillar and ground of truth.
For the life being the truth and the way, go not one step without it,
lest you should compass a mountain in the wilderness;
for unto everything there is a season.

As the flowing of the ocean does fill every creek and branch thereof,
and then retires again towards its own being and fulness, and leaves a savor behind it,
so does the life and virtue of God flow into every one of your hearts,
whom he has made partakers of his divine nature; and when it withdraws but a little,
it leaves a sweet savor behind it, that many can say,
they are made clean through the word that he has spoken to them;
in which innocent condition you may see what you are in the presence of God,
and what you are without him.

Therefore, my dear hearts, let the enjoyment of the life alone be your hope,
your joy and consolation,
and let the man of God flee those things that would lead the mind out of the cross,
for then the savor of life will be buried.
And though some may speak of things that they received in the life, as experiences,
yet the life being veiled,
and the savor that it left behind being washed away by the fresh flood of temptation,
the condition that they did enjoy in the life, boasted of by the airy mind,
will be like the manna that was gathered yesterday, without any good scent or savor.
For it was only well with the man while he was in the life of innocency,
but being driven from the presence of the Lord into the earth, what can he boast of?

Although you know these things, and many of you much more than I can say,
yet for the love and zeal I bear to the truth and honor of God,
and tender desire of my soul to those that are young,
that they may read me in that from which I write,
to strengthen them against the wiles of the subtle serpent that beguiled Eve; I say,
stand in the watch within, in the fear of the Lord, which is the very entrance of wisdom,
and the state wherein you are ready to receive the secrets of the Lord.
Hunger and thirst patiently, be not weary, neither doubt.
Stand still, and cease from your own working,
and in due time you shall enter into the rest, and your eyes shall behold his salvation,
whose testimonies are sure, and righteous altogether.
Let them be as a seal upon your arm, and as jewels about your neck,
that others may see what the Lord has done for your souls.
Confess him before men, yes, before his greatest enemies;
fear not what they can do unto you: greater is he that is in you,
than he that is in the world.
He will clothe you with humility, and in the power of his meekness,
you shall reign over all the rage of your enemies in the favor of God, wherein,
as you stand in faith, you are the salt of the earth; for many seeing your good works,
may glorify God in the day of their visitation.

Take heed of receiving that which you see not in the light,
lest you give ear to the enemy.
Bring all things to the light, that they may be proved whether they are wrought in God.
The love of the world, the lust of the flesh, and the lust of the eye,
are without the light, in the world.
Therefore possess your vessels in all sanctification and honor,
and let your eye look at the mark.
He that has called you is holy: and if there be an eye that offends, pluck it out,
and cast it from you.
Let not a temptation take hold, for if you do, it will keep you from the favor of God,
and that will be a sad state; for without grace possessed,
there is no assurance of salvation.
By grace you are saved, and the witnessing of it is sufficient for you,
to which I commend you all, my dear friends, and in it remain your brother,

[.signed-section-signature]
William Leddra

[.signed-section-context-close]
Boston jail, 13th of First Month, 1660-1

--

[.asterism]
'''

THOMAS FORSTER, of London, was convinced about the year 1658,
and thereupon forsook much of this world`'s gain and preferment for the sake of Christ,
(he then belonging to the civil law) and was in his life-time
freely given up to serve the Lord with body,
soul and whole substance, that he might run the race and keep the truth;
which made him willing to deny himself, and take up the daily cross for Christ`'s sake,
that he might be truly wise.
He foresaw, several years before it happened,
that the city of London should be destroyed; and his wife and family, at his admonition,
removed into the out parts,
and by that means escaped the judgment which afterwards came to pass upon the city,
when it was burned by fire in the year 1666.
He also foretold the sufferings which God`'s people have since been tried with, saying,
'`The holy city will be besieged; but blessed are they who keep in the faith,
for the time of deliverance will assuredly come,`' etc.
And a little before his departure out of this world, he said, '`Ah! friends,
abide in God`'s pure holy truth all the day long,
and you shall see the rising of his glory.`'
So he finished his course, and fell asleep, in the year 1660.

[.asterism]
'''

RICHARD HUBBERTHORN was born in the north part of Lancashire;
his father was a yeoman of the county, and of good repute.
Richard was his only son, inclinable from his youth to religion, fearing the Lord,
and was faithful in all things according to the light and knowledge received.
His natural disposition was meek and lowly, and he loved peace among men,
and he sometimes preached among his sober and sincere companions.

When it pleased God to raise up his people in the north parts of England,
this same person was one among the first whose heart
the Lord touched with the sense of his power,
and he went through great afflictions,
through the dispensation of the grace and spirit of Christ Jesus,
until such time as the same power that killed did make alive; it wounded,
and also healed.
Being raised up by the holy spirit of the Lord,
he was made a minister of the everlasting gospel,
and accordingly went forth in the name and power of the Lord Jesus Christ,
and travelled to and fro in the nation for the space of nine years;
and thousands were as seals to the power and verity of his ministry,
and of his faithfulness among the churches of Christ.

He was a man of small stature, of a weak constitution of body, and though slow of speech,
yet he was very wise, and knew his season when to speak, and when to be silent.
When he spoke, it was with such discretion and plainness of words,
that reached perfectly the matter intended; and his speech being with grace,
and his ministry savory, God made him and his service a blessing to many.
He was not easily moved into grief by adversity, or into joy by prosperity;
a faithful contender for the living faith once delivered to the saints,
which stands in the power of God, and works by love.

He was, with many others of the people called Quakers,
taken from the Bull and Mouth meetinghouse in London, and had before Sir Richard Brown,
who with his own hands did violence to him, and then committed him to Newgate,
where being thronged up in a nasty prison, he was taken sick,
and in a few days grew weaker and weaker.

About two days before his decease, some of his dearest friends visiting him,
asked if any thing was on his mind; his answer was,
that there was no need to dispute matters, he knew the ground of his salvation,
and was satisfied forever in his peace with the Lord; and we know, said he,
one another well, and what each of us can say about these things.
During his sickness he expressed much love to friends;
and his mind was redeemed out of all visible things; and several times he would say,
'`The word of the Lord is with me.`'
And farther, '`That faith which has wrought my salvation I well know,
and have grounded satisfaction in it.`'

In the time of his sickness, he was kept feeding in retiredness within,
so that one might feel his strength in the Spirit, that kept him so still,
that it was not remembered that he groaned all the time of his sickness.
On the seventh day in the morning he asked for the mistress of the house, and said,
'`This night, or tomorrow, I shall depart hence.`'
The next morning he said to one sitting by him, '`Do not seek to hold me,
for it is too strait for me; and out of this straitness I must go,
for I am wound into largeness, and am to be lifted up on high, far above all.`'
So in the evening, being the first day of the week, and the 17th of the Sixth month,
1662, he finished his course, according to his own words,
and was gathered up to his Father.
He wrote many treatises, which are collected together in print.

[.asterism]
'''

EDWARD BURROUGH, born in the county of Westmoreland, about the year 1635,
of honest parents, was in his childhood ripe in knowledge,
and did far excel many of his years.
Grey hairs were upon him when but a youth,
and he was inclinable to the best things and the
nearest way of worship according to the scriptures,
accompanying the best men.
His natural disposition was bold and manly, dexterous and fervent,
and what he took in hand, he did with his might.
Loving, courteous, merciful, and easy to be entreated; he delighted in conference,
and reading of the holy scriptures.

When it pleased God to visit his people in the north of England,
this servant of Christ was early called, in the year 1652,
when about seventeen years of age.
He was sent forth by the Spirit of the Lord to preach the everlasting gospel, repentance,
conversion, salvation, and remission of sins,
in the name and power of the Lord Jesus Christ, the savior of mankind;
and was an able minister of the glad tidings of salvation.
In most parts of England, and through Ireland several times,
and in Scotland and Flanders, his ministry was made effectual by the mighty power of God,
in turning many thousands from darkness to light; for as he began early,
so he labored much in the heat of the day, breaking up rough places, and untilled ground,
and often walked as it were among briars and thorns, which scratched, pricked,
and tore with great opposition.
But he broke through them all, not regarding the opposition,
and the sufferings that he met with, for the good of souls.

His industry in the Lord`'s work was very great, he seldom having many hours repose,
making the Lord`'s work his whole business,
not taking so much liberty as to spend one week to himself, about any outward occasion,
in ten years; and it was his grief if any opportunity was missed in doing good.
He was a man of no great learning, which men so much admire,
yet he had the tongue of the learned,
having had experience of the work of God in many conditions,
so that he could speak a word, in due season,
to the understandings and consciences of all men with whom he had converse,
for his words administered grace to the hearer.

At the age of nineteen, in the year 1654, he came up to London,
and was one of the first who preached in that city,
and great opposition he met with there;
but God made his ministry effectual to the conversion of hundreds.
He continued about London very much, at times, between eight and nine years,
speaking of the things of the kingdom of God.
His heart was much drawn towards London, and he often said,
when sufferings came for the gospel`'s sake, '`I can freely go to that city,
(i. e. London,) and lay down my life for a testimony of that truth
which I have declared through the power and spirit of God.`'

In the year 1662, visiting friends in the city of Bristol, he took his leave,
and said to many, '`I am going up to the city of London,
to suffer among friends in that place.`'
A little after his return to the said city,
he was taken from a meeting of the people called Quakers,
at the Bull and Mouth meetinghouse, by soldiers under the command of Sir Richard Brown,
mayor, and committed to Newgate by the said mayor, not for evil doing,
but for testifying to the name of the Lord Jesus, and for the worship of God.
There he lay in prison with six or seven score friends more, upon the same account,
many of them being shut up among felons in nasty places;
and for lack of prison-room they grew weak, sickened, and died,
among whom this young man was one; his sickness increasing upon him daily,
though in much patience he was carried through all.

He was in prayer often, both day and night, saying at one time,
'`I have had a testimony of the Lord`'s love to me from my youth,
and my heart has been given up to do his will.
I have preached the gospel freely in this city,
and have often given up my life for the gospel`'s sake.
Lord, rip open my heart, and see if it be not right before you.`'
Another time he said, '`There lies no iniquity at my door;
but the presence of the Lord is with me, and his life I feel justifies me.`'
Afterwards he said to the Lord, '`You have loved me when I was in the womb,
and I have loved you from my cradle, and from no youth unto this day,
and have served you faithfully in my generation.`'

He spoke to friends that were about him to live in love and peace, and love one another;
and said, '`The Lord takes the righteous from the evil to come:`'
and prayed for his enemies and persecutors, and said, '`Lord,
forgive Richard Brown who imprisoned me.`'
Again he said, '`Though this body of clay must turn to dust, yet I have this testimony,
that I have served God in my generation; and that spirit which has lived, and acted,
and ruled in me, shall yet break forth in thousands.`'
In the morning before he departed, being sensible of his death, he said,
'`Now my soul and spirit is centered in its own being with God,
and this form of person must return from where it was taken.`'
And after a little season, he gave up the ghost, as a martyr for the word of God,
and testimony of Jesus.

He was born in 1635, began to preach 1652, and died 1662,
of whose written labors there is a volume printed,
containing almost nine hundred pages in folio.
