== Chapter 4

[.chapter-synopsis]
* Amariah Drewet
* Benjamin Padley
* Sarah Featherstone
* George Gray
* George Fox
* Joan Vokins
* Robert Lodge
* Stephen Crisp
* Gulielma Maria Penn
* Patrick Livingston
* Andrew Sowle
* Springet Penn
* Richard Baker
* Robert Barrow
* Tudor Brian
* Thomas Hains

AMARIAH DREWET, of Cirencester, in Gloucestershire, preached in his life and conduct;
for he was faithful according to the measure the Lord had given him,
and turned not his back in time of suffering,
but rather blessed the Lord that he was found worthy
to be one of that number to have his faith tried,
often praying for his persecutors.

On the 11th of the Seventh month, 1686, he was visited with sickness,
and the Lord so filled his soul with his love and presence,
that three days before his death he signified,
if it was the last testimony he had to bear,
the love and presence and peace of God was with him; and that he could truly say,
as good old Simeon did, that he had seen the salvation of God.
The night before his departure he said to his wife, '`Go to bed, you have need of rest,
and give me up to the Lord, whose presence I feel, and I resign you up;
may the Keeper of Israel, that good watchman, that neither slumbers nor sleeps,
be with you.`'

At other times he prayed, '`O Lord, strengthen my poor body, that I may praise your name;
my rest is in you.
Oh! the largeness of your love that I feel.
O Lord, hear my cries, and bear up my head in all my exercises.
Oh! your sweet presence, and fresh springs that I feel!
Glory and honor, and praises, be unto your name forever.`'
Again, '`Lord help me, and keep me close to your power.`'
With many other petitions that he put up to the Lord;
admonishing people who came to visit him, and warning the young to fear God,
and watch against those things that did corrupt youth; exhorting them to faithfulness,
that it might be well with them upon their dying bed, as it was with him.
He uttered many more heavenly expressions, which are omitted for brevity.
He lay half an hour, as if he had been asleep, and went away quietly,
without sigh or groan; and so departed this life, on the 25th of the Seventh month,
in the year 1686.

[.asterism]
'''

BENJAMIN PADLEY, son of William and Elizabeth Padley, of North Cave,
in the East Riding of Yorkshire, was a young man that walked in humility,
zeal and love towards God, and to all who walked in his truth.
The Lord was pleased to raise him to bear testimony to his everlasting truth,
in the assemblies of his people;
and his great delight was in the prosperity of the truth,
for which he faithfully and zealously labored to the end of his days,
having regard to the motion of God`'s spirit in his ministry,
and lived according to his testimony.
He was sound, plain, and weighty in his declaration, and kept low and humble,
in a deep sense of the need he had to wait upon God, for the renewing of his mercies,
and fresh openings of the springs of life and love from God,
to help him forward in his spiritual travail, that he might persevere to the end;
and to which he did much exhort, and stir up Friends where he came.

He was taken sick the 17th of Sixth month, 1687;
which sickness continued about eight days.
In this time several Friends, and also neighbors and relations, came to see him;
and in the sense of God`'s love he declared truth among them.
There being some present who did not profess the same truth with us, he said,
'`It is not for any outward thing we travel abroad;
not any man`'s silver or gold that we seek or covet after;
but it is for the gaining of souls.
We have suffered the loss of our goods, scoffings, scornings, and imprisonments;
so that it may appear that it has not been the benefit of
any man`'s goods or estate that has been in our eye,
but for performing the will of the Lord.`'
Several of his neighbors being present, he said, '`It is well for them that can say,
on their dying beds, that their sins and iniquities are blotted out.`'
He prayed to the Lord, that he would mix mercies with his afflictions;
and exhorted friends to faithfulness and righteousness.
Observing his wife to weep, he said, '`O, why do you so?
You must not do so; but keep to truth, and fear not but all will be well.`'
At night he said to her, '`Go to bed, and be not troubled about me.`'
Friends visiting him, he said, '`I am glad to see so many of your faces,
which I thought I should not have done,
being the Lord has been pleased to visit me with sickness,
so that I am not likely to continue many days here; but I feel nothing, but all is well.`'
When his friends would be careful about some physician to help him, he said,
'`I have a physician the world knows not of.`'

When he drew near his end he desired to be helped upon his knees,
and was so powerful in prayer to the Lord, considering the weakness of his body,
that it was an admiration to all present.
After that, few words proceeded from him, but he weakened quickly,
and the next day departed this life, being the 25th of the Sixth month,
in the year 1687.

[.asterism]
'''

SARAH FEATHERSTONE, daughter of Joseph Featherstone and Sarah his wife,
aged about fifteen years, was inclined in her tender years to hear the voice of wisdom,
and to remember her Creator in the days of her youth.
From a child she was harmless, and obedient to her parents,
and of a meek and quiet spirit.
She was taken sick the 9th of the Seventh month, 1688.

Her mother coming to her, she told her that she thought she should be taken from her;
and when her mother would send for a doctor,
she said she was freely given up to the will of the Lord, whether to live or die.
She farther said it was showed her that she was not of a long life; and,
'`if this be the time of my change, I am content.`'
Her sickness increasing, her mother was much concerned; at which she was troubled,
and said, '`Dear mother, your dear and tender love to me has been very great,
and in that love I desire we may rest, freely given up to the will of God;
for the Lord may not see fit to trust me in this wicked world any longer.`'
And farther she said,
'`Oh! the abominable pride of this world! and there are some among us who can
take liberty to fashion themselves in many things like unto the world,
both in their habit and other needless things.
Oh! but the Christian life is another thing;
this is not the adorning that we are to put on; for if the righteous scarcely be saved,
where shall the wicked and ungodly appear?`'

Her distemper being violent, she then said, '`Never so sick in my life;
O! sick at my heart!
O Lord, in mercy remember me, and bear me up above all my afflictions,
for my heart trusts in you.`'
Being asked by her mother whether she would be buried by her father,
or at another burying-place, she answered, '`Dear mother,
bury me where you and my father (her father-in-law) please, I leave it to you;
it is no matter how many miles distant these bodies lie,
our souls shall one day rejoice together;`' with more words,
bidding them about her not to trouble her, or give her any thing, without she desired it.
She lay still in a good frame of mind, with a sweet countenance,
bearing her sickness in much patience; often saying,
'`O! my dear and heavenly Father! come away, come away, for my heart trusts in you.`'
And so fell asleep in the Lord, the 17th of the Seventh month, in the year 1688,
aged fifteen years.

[.asterism]
'''

GEORGE GRAY, of Acquorthies, in Scotland, was a sufferer for the truth;
a poor man in this world, yet rich in faith; of mean education,
yet endowed with divine wisdom;
and bore a sound and faithful testimony among the Lord`'s people.

A little before his departure, being filled with the power of the Lord,
he gave weighty exhortations to all present, especially to his children.
To some friends that came to see him,
he said he had not kept back the word and counsel of the Lord from them;
and now he could say, it was good doctrine, to leave nothing to do till a dying bed:
so finished his testimony, and laid down his body the 8th day of the Twelfth month,
in the year 1689.

[.asterism]
'''

GEORGE FOX was born in the Fifth month, 1624, at Drayton, in Leicestershire.
At eleven years of age he knew purity and holiness.
In the nineteenth year of his age, in the year 1643, he left all,
and travelled up and down the nation, visiting many people who were seeking the Lord,
until the year 1646, at which time he entered into his more public ministry;
for he was sent of God, as the apostles were in the primitive times,
to turn people from darkness to light,
directing all to mind the light of Christ Jesus in their own hearts.
In the year 1648,
several meetings of Friends were gathered to God`'s teaching through his ministry;
in which ministry he faithfully labored forty-four years,
through much suffering and many perils of various sorts,
as by the journal of his life does largely appear.

God gave him length of days, so that he saw his children in the faith,
unto the third and fourth generation, to a great increase.
Great was his care for the preservation of those who had received truth,
that they might walk in the same; and to that end he gave forth many faithful epistles,
and good exhortation and advice, for good order and discipline in the church of Christ,
as appears in the collection of his epistles to friends.

He preached the gospel effectually but two days before he died,
on the 11th of the Eleventh month, 1690, at Gracechurch-street meetinghouse in London.
After meeting, he said, '`I am glad I was here; now I am clear,
I am fully clear;`' and then was the same day taken ill of some indisposition of body,
and continued weak in body for two days, at the house of Henry Goldney,
at White-hart-court, in Gracechurch-street,
and lay in much contentedness and peace to the end, being very sensible.
In this time he mentioned many Friends, and sent for some in particular,
to whom he expressed his mind for spreading truth and Friends`' books in the world;
signifying also to some Friends, saying, '`All is well,
and the seed of God reigns over all, and over death itself; and though I am weak in body,
yet the power of the Lord is over all,
and over all disorderly spirits;`' which were his customary sensible expressions,
being in the living faith and sense thereof, which he kept to the end.

On the 13th of the Eleventh month, in the year 1690,
he quietly departed this life in peace, about the tenth hour in the night:
so he ended his days in a faithful testimony,
in perfect love and unity with his brethren,
being about the sixty-sixth year of his age.

[.asterism]
'''

JOAN VOKINS, wife of Richard Vokins, of the county of Berks, was a faithful woman,
and laborer in the gospel.
After she had received God`'s blessed truth,
she was much concerned that her relations also might receive the same truth;
and by her upright conduct and good example among them,
with the blessing of God and assistance of his grace, her husband, father,
and children received the truth; and her husband was a sufferer for the same,
in his imprisonment in Reading jail, and her eldest son also.
Having received a dispensation of the gospel of Jesus
Christ to preach to others in this nation,
she was also concerned in her spirit to visit several
provinces and islands beyond the seas;
and in order thereunto took shipping from Gravesend in Kent, in the Twelfth month, 1679,
and visited New York, East and West Jersey, and some parts of Pennsylvania,
which at that time was not much inhabited, Long Island, Rhode Island, and New England,
and several of the islands, as Antigua, Nevis, and Barbados.

In her journey to these places she endured many hardships
and sufferings of several kinds;
yet through all she was supported by the power of Christ,
whose peace she felt in her soul.
On the 3rd day of the Fourth month, 1681, she returned from Barbados to England,
and landed at Dover in Kent.
At Sandwich she exhorted the priests and people of that town,
in their public place of worship, to forsake their vanity,
and to come to the spiritual worship of God; and laid before them the danger of the one,
and the benefit of the other.

After her return home to England, she continued her diligence in the Lord`'s work,
and care and service in his church, and among his people, to the end of her days.
About the yearly meeting time, in 1690,
she went up to London to visit Friends thereabout; and, but a few weeks before her death,
by a letter, dated from London, in the Fourth month following,
she signified to her dear friend Theophila Townsend,
another faithful woman-laborer in the gospel, at Cirencester,
that now her service was finished; and said,
'`I could gladly have laid down my body here among the Lord`'s worthies; yet,
seeing it is ordered otherwise, I submit to the will of my God,
and do think to go homeward in a little time.`'

Joan Vokins also said, not long before, to the said Theophila Townsend,
being then with her, that she had some papers,
which she desired might be made public after her decease,
expecting her time was not long to remain in the body,
being well satisfied that she should lay down her head in peace with God,
let death come when it would.
And according to the sight she had, and what she said,
the time of her decease was near at hand, for she did not live to get home,
after she wrote the letter aforesaid in the Fourth month at London.
Coming to Reading, she fell sick there, and upon her dying bed spoke to her son,
Richard Vokins, as follows: '`Son, my weakness is great, and my pains very strong;
but the Lord is large in his love to me, and good to me;
he gives me patience to bear my pains, which are strong.
Ah, son, I have learned a good lesson; Paul`'s lesson; in all states to be content;
and now I have nothing to do but to die.`'
Putting forth her hand to take her leave of him, she farther said, '`Son,
remember the Lord, and he will remember you: remember my love to your wife,
and to all my children.`'
And after a little stop, and her speech low, she spoke these words again,
'`And he will remember you; and be faithful to him, and he will bless you,
and you shall be blessed.`'

She departed this life the 22nd of the Fifth month, in the year 1690,
having finished her course, and kept the faith.

[.asterism]
'''

ROBERT LODGE, of the county of York, was convinced of truth in the year 1660,
and was a faithful minister of Christ Jesus,
and a valiant sufferer for the testimony of a good conscience.
He travelled in the work of the gospel, both in England and in Ireland,
and turned many to righteousness, and did build up many in the most holy faith:
he was not only a planter but a waterer in the vineyard: a son of consolation indeed.

The time of his sickness was but short.
A friend visiting him, he gave account of his infirmities, and questioned his recovery:
but he said, '`The Lord knows my heart, that I have served him;
and it has been of more account to me, the gaining of one soul,
than all my labors and travels.`'

The friend going again the next day, and seeing him near his end, was sorrowful;
to whom he said, '`What! we must meet again,
we must meet again in eternity;`' and put up many heavenly petitions to the Lord.
Another friend taking leave of him, he called him by his name, and said,
'`It is well with me, and I have no disturbance in my mind.`'
And again he said, '`The Lord knows I was never commissioned to go any way,
or to do any thing, but I have willingly answered him; and the Lord,
who has been my rock and refuge, my shield and buckler, and a sanctuary to me,
has been with me all along to this very day.`'
He spoke much more in praises to the Lord for his many deliverances,
praying for the continuance of God`'s life and love to his whole heritage.
After which he spoke little, but that all was well with him; and said, '`Blessed be God,
I have heavenly peace;`' and so fell into a sweet sleep, and went away,
being on the 15th of the Seventh month, in the year 1690.

[.asterism]
'''

STEPHEN CRISP, of Colchester in Essex, received the blessed truth about the year 1655,
when he was about twenty-seven years of age,
and was a preacher of the everlasting gospel of Christ Jesus about thirty-five years.
In that service he travelled in many parts of England, Scotland, Holland, Germany,
and the Low Countries, as by the printed journal of his life more largely appears,
and endured many hardships for his faithful testimony to the blessed truth.
He was greatly capable, through his long experience,
to advise and give counsel to persons in all conditions.

In the latter part of his days, being unable to travel much,
through an indisposition of body,
yet he was diligent in preaching the gospel in Colchester and London.
He lay some time under great exercise and weakness; and about four days before he died,
being under much bodily weakness and pain, he said to George Whitehead,
who came to visit him, '`I see an end of mortality, yet cannot come at it;
I desire the Lord to deliver me out of this troublesome and painful body.
If he will but say the word, it is done.
Yet there is no cloud in my way.
I have a full assurance of my peace with God in Christ Jesus;
my integrity and uprightness of heart is known to the Lord,
and I have peace and justification in Christ Jesus, who made me so; that is,
upright to God;`' and remembered his love to all the faithful in the church of God.
To another friend he said, '`I have fought the good fight of faith,
and have run my course, and am waiting for the crown of life that is laid up for me.`'

To a friend who visited him, he said, '`Serve the truth for the simple truth`'s sake,
and it will preserve you to the end, as it has done me.`'
In his great pain of body, feeling the word of patience to support him,
he said to the friends watching with him, '`Grow in the word of patience,
that it may keep you also in the time of need.`'
The day before he died, he said,
'`I hope I am gathering,`' (as his expression was understood,) '`I hope,
I hope,`' being then hardly able to speak out his words.
George Whitehead, near parting from him, said, '`Dear Stephen,
would you have any thing to friends?`'
After some pause, he gave this answer, '`Remember my dear love in Christ Jesus to all.`'
And on the 28th day of the Sixth month, in the year 1692, he died in the Lord,
at Wandsworth, near London, about the sixty-fourth year of his age.

[.asterism]
'''

GULIELMA MARIA PENN was the wife of William Penn, of Pennsylvania,
and daughter of Sir William Springet, of Durling.
Her illness continued eight months upon her,
in which time she uttered many living and weighty expressions upon several occasions,
both before and near her end.
At one of the meetings held in her chamber,
only her husband and children and one of the servants being present,
in a living power she said, '`Let us all prepare, not knowing what hour, or watch,
the Lord comes.
O! I am full of matter!
Shall we receive good, and shall we not receive evil at the hand of the Lord?
I have cast my care upon the Lord, he is the physician of value;
my expectation is wholly from him; he can raise up, and he can cast down.`'
A while after she said, '`O! what shall be done to the unprofitable servant!`'

At another meeting, before which much heaviness seemed to lie upon her natural spirits,
she said, '`This has been a precious opportunity to me,
I am finely relieved and comforted, blessed be the Lord.`'
At another time, her husband speaking to her of the peace of well-doing,
she replied to him, '`I never did, to my knowledge, a wicked thing in all my life.`'
To a friend, aged seventy-five years, that came to see her, she said, '`You and I,
to all appearance, are near our end.`'
And to another, about sixty-five years old, who came also to see her, she said,
'`How much older has the Lord made me by this weakness than you are!
But I am content.
I do not murmur.
I submit to his holy will.`'
In the height of her sickness she said,
'`It is the great goodness of the Lord that I should be able to lie thus still.
He is the physician of value to me, can I say.
Let my tongue set forth his praise, and my spirit magnify him while I have breath.
O! I am ready to be transported beyond my strength.
God was not in the thunder, nor in the lightning;
but he was heard in the still small voice.`'
She called the children one day, when very weak, and said, '`Be not frightened, children;
I do not call you to take my leave of you, but to see you;
and would have you walk in the fear of the Lord, and with his people in his holy truth.`'
Speaking another time solemnly to her children, she said,
'`I never desired any great things for you, but that you may fear the Lord,
and walk in his truth among his people, to the end of your days.`'

About three hours before her end, a relation taking leave of her, she said,
'`I have cast my care upon the Lord;
my dear love to all friends;`' and lifting up her dying hands and eyes,
prayed to the Lord to preserve them and bless them.
About an hour after, causing all to withdraw, she took her leave of her husband,
saying all that was fit upon that solemn occasion.
She continued sensible, and ate something about an hour before her departure;
at which time her children, and most of the family being present,
she quietly expired in her husband`'s arms,
with a sensible and devout resignation of her soul to Almighty God,
on the 23rd of the Twelfth month, in the year 1693, in the fiftieth year of her age.

[.asterism]
'''

PATRICK LIVINGSTON was born in the year 1634, near Montrose, in the kingdom of Scotland.
He received the blessed truth about the year 1659,
and travelled much in the service thereof,
bearing a faithful testimony to the same for above thirty years,
in many parts of England and Ireland, and most places in Scotland,
where he was made a good instrument in convincing and gathering
many to the knowledge of the inward appearance of Christ Jesus,
particularly that meeting settled at Kinermuck in Aberdeen county,
the largest meeting in all the nation.
In this county he valiantly and patiently endured
several years`' close imprisonment in Aberdeen,
for his faithful testimony to the truth, that is, from the year 1676 to 1679;
and he likewise bore a faithful testimony for truth, by imprisonment in Newgate,
in London, for a considerable time, about the year 1684.

Valiant he was for the truth, especially in times of persecution.
Like a good soldier, he never turned his back in the day of battle,
but through the strength of the Lord was still among the first in suffering,
being fervent and zealous for the cause of truth and honor of God.
His persecutors were sensible that he was a strengthening to his brethren in prison;
and therefore, that it might not be so, they would several times let him go,
or miss some meeting he was known to be at.
Faithful he was to his brethren in their afflictions, and would not leave them,
till he saw an end to that persecution in Scotland in the year 1679;
and from that time no Friend was imprisoned for several years in that city.

After this he returned into England to his dear wife,
who at that time dwelt in Nottingham, but in his latter years,
he with his family lived in London.
He continued to the end a diligent laborer in the Lord`'s vineyard,
several times visiting his native country of Scotland; and the year before he died,
in 1693, he again visited his brethren there,
and was attended with a plentiful measure of the Lord`'s power and presence,
all the time he was among them, though at that time weak in body.
After his return home he grew weaker,
until he departed this life on the 15th of the Fourth month, 1694,
at the house of John Kirton, in Kensington, near London,
being removed there for the benefit of the air, where several friends were present,
witnesses of the following heavenly expressions:

The day before his departure he said, '`I am in unity with all faithful Friends,
and in love to all men.`'
About an hour before his departure, he said, '`O Father!
O Father!`' A little time after, mentioning his weakness of body,
and as if he desired more strength to utter what was in his mind,
which being then apparently given him, he said, '`Let life reach unto all here:`'
and pulling off his night-cap with his own hand
about half an hour before he was removed hence,
he said, '`Blessed, praised, magnified, and exalted be the mighty, powerful,
great and everlasting name of the Lord God, forevermore.
Oh! that your life may arise in full dominion over all,
and that Friends may feel it so in all their assemblies; that they may be kept in love,
concord and unity together, and show it forth in word, work, testimony,
life and conduct unto all;`' adding, '`Life being over all; here we have all we need,
and here there is a lying down in true submission to the will of the Lord,
and laying down our heads in peace and rest with him forevermore.`'
Which last words he repeated twice, and said, '`Here is victory over death, hell,
and the grave, and resting in peace with the Lord forevermore.`'

He died on the 15th of the Fourth month, in the year 1694,
about the sixtieth year of his age.

[.asterism]
'''

ANDREW SOWLE, of London, received the truth as professed by the people called Quakers,
in his young years, and became obedient thereunto,
and gave himself up to the living power thereof,
which enabled him with much cheerfulness to undergo those manifold
afflictions and persecutions with which he was exercised;
for being a just and upright man, he was zealous for the propagation of the truth,
to which, both by conduct and sufferings, he bore a faithful testimony.

He was a printer by trade, and engaged himself freely in the printing Friends`' books,
when he had large offers of advancing himself in the world,
made to him by his other friends and relations, if he would have desisted therefrom.
But his love to truth,
and the desire he had to be instrumental in his calling for spreading it abroad,
would not permit him to hearken to any of those offers.
He freely gave himself up to the service thereof,
even in times of the hottest persecution, believing it his duty so to do,
though therein he should hazard not only his life,
but also that outward substance God had blessed him with.
For several years together he was in continual danger upon that account,
his house being often searched, and his printing materials, as presses, letter, etc.,
as often broken to pieces, and taken away,
as any Friends`' books were found printing by him;
and this they did for many years together.
During this time, though he met with great losses, and had, at one time,
by his adversaries, about a thousand reams of printed books taken from him,
yet he was never heard to complain, but he would say,
he was glad to have any thing to lose for truth,
and that the Lord had made him worthy to be a sufferer for it.
This quiet resignation of himself to the will of God,
caused one of those who came to seize upon his goods,
to do what he could with his partners to put a stop to the seizure;
and when he saw he could not prevail, he went out and wept.
When at another time his adversaries came to take away his printing press,
he was so resigned and easy, in giving up all to his persecutors,
that when they had done their work, and seized upon all, he,
(as he often did in like cases,) set forth meat and drink before them,
according to the command, Rom.
xii., 19, 20, to feed even his very enemies; and his good so overcame their evil,
that some of them departed under a concern;
but one of he chief being filled with malice against the truth, survived not long after,
but died in a miserable condition.

As this sincere man met with great sufferings,
so had he also large experiences of the goodness
of God towards him in many remarkable providences.
At one time he was taken at a meeting of the people called Quakers,
and carried to Newgate, and being examined by Sir Richard Brown, the persecuting mayor,
who, understanding he was a printer, threatened to send him after his brother Twin,
(as he called him,
who some time before suffered in Smithfield for printing
a treasonable book,) to whom this meek man replied,
'`You will not live to see it:`' and the event justified it, for Brown died soon after.

After many exercises and trials many ways, which it would be too long to recite,
he was visited with weakness of body the beginning of the Tenth month, 1695,
and grew weaker and weaker till the 25th of the same month.
His patience and resignation to the will of God, during the time of his weakness,
were such, that he seldom was heard to complain, but would say,
that he was given up to the will of God; saying often,
that he had no dependence on any thing, save upon Christ Jesus, the good Samaritan,
on whom was his whole dependence.

George Whitehead, with another friend, coming to visit him,
he said he had served truth faithfully,
according to what the Lord had been pleased to make manifest to him;
and that in what he had done, he had not sought himself, but the honor of God.
He would often exhort his family to faithfulness,
and his young ones also to seek the Lord in the days of their youth.
His reproofs to those who had done amiss, were so kind and so convincing,
that a servant of his said he stood more in awe of a reproof from him,
than the severest treatment of another.
'`His end,`' said he, '`being in love to convince me,
that I have done that which is not right.`'

William Penn, the night before he departed, came somewhat late to visit him,
and finding him in a sweet composed frame of mind (for indeed
he was to appearance as though he ailed nothing),
asked him how he did; he answered with much cheerfulness,
his satisfaction and peace of mind were great, and that he waited for his change.
The said Friend,
who had been many years acquainted with his industrious and innocent life,
after some discourse with him,
kneeled down and prayed that the Lord would give him the reward of his labor; for,
through him, many blessed truths had been brought into the world, etc.
After prayer was ended, he acknowledged William Penn`'s love,
telling him he was well satisfied in his condition,
and in the truth of God which he had professed;
and that he had nothing to do but to wait in the will of God till his change came:
and so in much love they parted, he signifying his love to, and unity with all Friends,
in the truth.

After that, he lay sweetly retired, waiting for his change,
and had his senses perfectly and clear to the last,
which was about eight the next morning; at which time his wife came to his bedside,
and asked him how he did; he answered, '`Oh Jane, never such a good night as this:`'
and the same minute shut his eyes, and with a hymn of praise to God,
offered up his last breath, and fell asleep, not so much as fetching the least sigh,
nor was any alteration seen in his countenance.
So easily and so quietly did he leave this world, in which he had known much exercise,
and is gone to his everlasting rest, with God`'s faithful servants.

He finished this life the 26th of the Tenth month, in the year 1695,
about eight in the morning, at his house in Holywell-lane, London,
in the sixty-seventh year of his age. Rom. 8:18.
For I reckon, that the sufferings of this present time,
are not worthy to be compared with the glory which shall be revealed in us.

[.asterism]
'''

SPRINGET PENN, eldest son of William Penn of Worminghurst, late of Pennsylvania,
was a young man about twenty-one years of age.
For more than half a year before it pleased the Lord to visit him with weakness,
he grew more retired, and much disengaged from youthful delights,
showing a remarkable tenderness in meetings, even when they were silent.
But when he saw himself doubtful +++[+++as to health]
he turned his mind and meditations more apparently towards the Lord,
often praying with fervency to the Lord,
and uttering many thankful expressions and praises to him, in a deep and sensible manner,
saying one day, '`I am resigned: what God pleases: he knows what is best:
I would live if it pleased him, that I might serve him: but, O Lord, not my will,
but your will be done.`'
One speaking to him of the things of this world, he answered, '`My eye looks another way,
where the truest pleasure is.`'

Another time, his father going to a meeting, at parting he said, '`Remember me,
my dear father, before the Lord.
Though I cannot go to meetings, yet have I many good meetings:
the Lord comes in upon my spirit.
I have heavenly meetings with him by myself.`'
With more to the same purpose, expressing his sentiments of the vanity of this world,
and of his entering into secret covenant with the Lord,
and his thankfulness for the Lord`'s preservation and goodness to him.
Fixing his eyes upon his sister, he took her by the hand, saying, '`Poor Tishe,
look to good things; poor child, there is no comfort without it.
One drop of the love of God is worth more than all the world.
I know it; I have tasted it.
I have felt as much or more of the love of God in this weakness,
than in all my life before;`' with more that he said to his father.

Taking something one night in bed, just before going to rest, he sat up,
and reverently prayed thus: '`O Lord God, you whose Son said to his disciples,
whatsoever you ask in my name you shall receive, I pray you in his name,
bless this to me this night, and give me rest, if it be your blessed will, O Lord:`'
and accordingly he had a very comfortable night,
of which he took thankful notice the next day.
At another time he expressed his desire to serve the Lord if he lived.
He one day saying thus,
'`I am resolved I will have such a thing done;`' immediately he caught himself,
and fell into this reflection with much contrition, '`O Lord,
forgive me that irreverent and hasty expression.
I am a poor weak creature, and live by you, and therefore I should have said,
'`If it pleases you that I live, I intend to do so or so.
Lord forgive my rash expression.`'
He desired his mother-in-law not to trouble herself for such a poor creature as he;
and to pray for him, that he might live and employ his time more in the Lord`'s service.

To his brother he said, looking awfully upon him, '`Be a good boy,
and know there is a God, a great and mighty God, who is a rewarder of the righteous;
and so he is of the wicked; but their rewards are not the same.
Have a care of idle company, and love good company, and good Friends,
and the Lord will bless you.
I have seen good things for you since my sickness, if you do but fear the Lord;
and if I should not live, remember what I say,
when I am dead and gone;`' with many more religious expressions.
Taking his leave of his father, brother, and sister, he said, '`Come life, come death,
I am resigned.
Oh! the love of God overcomes my soul.`'
Feeling himself decline quickly,
and one seeing him not able to bring up the matter that was in his throat,
went to fetch the doctor; but so soon as he came, he said,
'`Let my father speak to the doctor, and I`'ll go to sleep;`' which he did,
and waked no more.

He died the 10th of the Second month, in the year 1696,
in the twenty-first year of his age.

[.asterism]
'''

RICHARD BAKER, of Jordan`'s in Buckinghamshire, received the truth in the love of it,
many years since, and he testified his love to it; 1st. In a circumspect walking,
showing himself a pattern of good works.
2ndly.
By suffering cheerfully for it, and took joyfully the spoiling of his goods,
and the imprisonment of his body; and would often say,
'`If people knew the pleasure of godliness, they would not live in the earth as they did.`'
3rdly.
By a hearty zeal for the prosperity and propagation of it.

A vigilant watchman he was in his station, a sharp reprover of evil,
and an encourager of the good, and a diligent laborer in the work of the ministry,
earnestly endeavoring to bring those he ministered
to into an inward exercise of spirit towards God,
that therein they might be more acquainted with, and subject, to the divine power of God:
concerning which he wrote a treatise, published since he deceased,
although it was written about twenty-six years before;
the reasons whereof he gave upon his dying bed, namely,
that he had read of many in former days, and had observed some in his own time,
who had made fair progress in the way of truth; and had said, done,
and suffered much on behalf of it, who yet had not held out to the end;
but through too great security, or self-confidence,
and for lack of a continual subjection to the power of God,
in and by which alone strength and preservation are to be found,
have by the violent assaults, the subtle insinuations,
or mysterious workings of the enemy, been drawn back again under the power of Satan,
to the invalidating (at least in the eye of the world) the testimonies
such had before given to the sufficiency of the power of God.
And he having by others`' miscarriages learned to beware, had,
from a godly jealousy over himself, suspended the publication of the said sheets,
until he could with greater confidence, and more full assurance,
say with the holy apostle, when the time of his departure was at hand,
"`I have fought a good fight, I have finished my course, I have kept the faith,`" etc.,
which bespoke his great modesty.
Upon his dying-bed, he had the witness in himself that God was pleased with him,
and had a suitable word to every one`'s state that came to him;
and would often clap his hand on his breast, and say, '`All is well here.`'

The day before he departed, many Friends visiting him,
he spoke to all in expressions of great love, and took his leave of them;
and taking his leave of a child who wept, he said, '`Do not cry, I am well,
my peace is made with the Lord.
If you cry, cry that iniquity may be brought down and righteousness brought up.
The power of God and strength of God is with me.
I am going the way of all flesh; I am going before, and others must follow after.`'
So he laid down his life, in the feeling of that power, about the year 1697.

[.asterism]
'''

ROBERT BARROW, born in the county of Lancaster,
but removed and brought up from a child in Westmoreland,
was early convinced of God`'s blessed truth,
and was a zealous laborer in the gospel for twenty-six years,
and a faithful sufferer for the same in London, and other places;
traveling much in this nation, and twice through Scotland, Ireland, and Wales,
to preach Christ Jesus, the light of the world.

In the year 1694 he went forth in the love of God, in company with Robert Wardel,
of Sunderland, both of them being ancient men, to preach the gospel in America.
After they had visited Pennsylvania, and some other parts on the continent,
they took shipping for Jamaica,
where Robert Wardel died the 22nd day of the Second month, in the year 1696.
After Robert Barrow had finished his testimony there,
he took shipping in order for Pennsylvania again, and on the 23rd of the Sixth month,
1696, embarked with various passengers and seamen on board the barque Reformation,
Joseph Kirle, master.
But on the 23rd of the Seventh month, by a storm in the Gulf of Florida,
the vessel ran aground, and to save their lives,
they were forced among the savage cannibals of Florida,
and underwent grievous sufferings of various kinds, being often in great danger of death;
traveling naked in heat and cold, hunger and thirst,
and having no proper food to eat from +++[+++the time of]
their suffering shipwreck, that is,
from the 23rd of the Seventh month to the 15th of the Ninth month following.

At last they arrived at a poor garrison town called St. Augustine,
belonging to the Spaniards in America, maintained partly by the king of Spain,
and partly by the Pope; but the governor, etc., were courteous and generous,
according to their ability, who, after they had clothed and refreshed them,
assisted them to Carolina, which province they reached on the 23rd of the Tenth month,
1696; but several of their company died under the hardships they met with.
Robert Barrow,
by feeding upon such unwholesome food (that little
which they did eat,) was taken with a flux,
which continued upon him;
and together with the great sufferings he underwent in his journeys, being ancient,
he was thereby much decayed in his body;
but his desire was to see his friends once more in Philadelphia,
and he reached Philadelphia from Charleston, in Carolina, in fourteen days.

One remarkable passage I may not omit, namely, the company Robert Barrow was with,
to save their lives, assumed the name of Spaniards,
for the savage Indians stood in fear of them;
and this true-hearted man being directly asked the question, '`Are you a Nickaleer?`'
which is an Englishman; he answered, '`Yes.`'
For his plain dealing, he was stripped naked of his clothes, which till then he had saved.
God permitted not these savages to touch his life, nor the lives of those with him;
though at one time these bloody creatures placed themselves each behind one,
having their arms extended, with their knives in their hands,
ready to execute their bloody design, some taking hold of them by their heads,
with their knees set against their shoulders, waiting for their chief to begin.
They were very high in words, which the English understood not;
but on a sudden it pleased God to work wonderfully for their preservation,
and instantly all these savage men were struck dumb, and like men amazed,
for the space of a quarter of an hour; in which time their countenances fell,
and they looked like another people, and quitted the places they had taken behind them,
and fell to plundering their chests and trunks.

But to return to our friend Robert Barrow,
who behaved himself under all those calamities in great patience,
and by faith overcame even the worst of men, looking to him who is invisible,
who by his grace supported him under all.
By prayer he wrestled with God, to be delivered from those unreasonable creatures,
desiring to lay his bones among his faithful friends in Philadelphia.
And God was so gracious that he sealed an assurance upon his spirit,
even before he was yet off his knees, that his prayer was heard,
and should be answered in due time.
And great strength and comfort he was to his companions in affliction.

When he arrived at Philadelphia, several friends went on board to help him on shore;
but he was so weak that he could not be removed that night,
being the 4th of the Second month,
but he signified to Friends his great satisfaction that the Lord had granted
his request that he might lay down his bones in that place;
that his heart was strong, and he hoped he might see Friends again at the meeting.
He made mention of the goodness of God to him,
and that his presence had attended him in all his exercise.
Next morning he was removed to the house of Samuel Carpenter,
where he slept a considerable time: the same day friends coming to visit him,
he rejoiced, putting forth his hand ready to embrace them, to whom he said,
'`Although my body be weak, my mind is sound and memory good;
and the Lord has been very good to me all along to this very day,
and this morning has sweetly refreshed me.`'
And farther added, '`The Lord has answered my desire, for I desired content,
and that I might come to this place to lay my bones among you.`'
Afterwards he said, '`It is a good thing to have a conscience void of offense,
both towards God and towards men.`'

On the day that he died, he desired a friend to write to his friends in England,
and to acquaint his relations that he had settled his affairs;
and afterwards declared to several friends that were by him, that the Lord was with him,
and all things were well, and that he had nothing to do but to die.
Accordingly, on the same day he departed this life in peace with God,
being the 4th of the Second month, in the year 1697; and was buried the 6th of the same,
in Friends`' burying-ground in Philadelphia, in Pennsylvania.

[.asterism]
'''

TUDOR BRIAN, of London, a youth about seventeen years of age,
was taken ill about the Tenth month, 1696, and from that time decayed daily,
falling into a deep consumption, till the Tenth month following.
Being in the country for his health,
he was often observed to be in retirement in the fields,
sometimes returning with wet eyes;
and his friends apprehending it might proceed from his distemper,
or else from fear of death, his frequent answers were, he was no ways afraid to die,
but willingly resigned himself to the will of God, either for life or death.
About a month before he died,
he was taken so ill as not to be able to go out of his chamber; and so continued,
being daily with a great sense of God upon his spirit;
and would often repeat a full assurance of his future happiness, saying, '`Come,
Lord Jesus, come quickly, and receive my soul.`'
A few days after, he called for a bible, desiring to read; his mother`'s answer was,
'`Child, you are weak;`' he said he could read; and so read the 17th chapter of John,
with trembling lips.
When he came to the 20th verse, "`Neither pray I for these alone,
but for them also which shall believe on me through
their word,`" he took particular notice,
and wept.

On the day before he departed, he fell so ill they thought he was smitten with death;
and several friends, as well then as before, visiting him,
he was much refreshed and comforted, and said, '`O mother,
how merciful is the great God to me,
that has put into the hearts of good friends to visit me!
There are healthier and younger lads than I, that are gone before me,
a poor consumptive lad; he has spared me; surely I shall never forget his mercies.`'
And to the Lord he said, '`Oh! glory, glory and praises, for they are yours forevermore.`'
Then sitting still, he said, '`Oh, you merciful God, you are merciful.
I can say that I have found it so; that when I had no breath, I have sought you,
and it has been given me.`'
His parents, hearing him, wept; but he answered, '`Wherefore are you troubled,
my dear parents?
Be not troubled for me, for I am going to a better place.
If it be the will of the Lord, he can raise me; but if not, his will be done:
it may be he may spare me two or three days.`'
Turning his eyes on his parents, he said, '`You are the nearest in the world to me,
but yet there is a nearer who is above.`'
After some silence he said,
'`I can say that in my younger years I have gone by myself down into the meadows,
and have cried to the Lord, but knew not where he was;
and when I heard his voice I trembled; and as I gave up,
the Lord Jesus made himself known to me.
Then I knew what I sought for:
with more concerning a vision he had of his future happiness;
and he testified against superfluity in the house.

About twelve hours before his death, a near relation desiring,
on behalf of those present, that they might be fitted for their latter end, he said,
'`You must pray, and hang and lean upon the Lord Jesus Christ: for it is of him,
and through him, that we must expect salvation.
Without him you can do nothing.
He died for sinners, and he is merciful to forgive, for he has forgiven me,
blessed be his holy name.
Although some be hardened and stubborn, yet the Lord is merciful; he can and may forgive;
but you that are in the truth, keep in the truth: with more which he said,
concerning remembering our Creator betimes, and concerning death.

About two hours before he died, he prayed thus: '`Lord God be merciful; you are good,
you are bountiful.
Lord have mercy on me!
Come, Lord Jesus, have mercy: you died for sinners; glory,
glory to the God of heaven! oh! praises to your name.
Lord Jesus receive my soul: with more that he said to his father and mother.
Lying still a little, he said,
'`O what a glorious kingdom I am going to! there are dainties enough.
Lord Jesus you have pardoned me.
O what a numerous army has my God!
He has a great one.`'
And so lay praising God till he finished this life, about two in the morning,
on the 3rd of the Tenth month, in the year 1697.

[.asterism]
'''

THOMAS HAINS, son of Thomas Hains and Hannah, his wife, of Southwark,
in the county of Surrey, was educated in the truth,
as professed by the people called Quakers, by his father;
and also for some time at the school of Richard Scoryer, of Wandsworth.
He was a dutiful child, and had a sense of the fear of God upon his heart,
so that during his sickness he behaved himself more like a man than an infant,
(as he called himself) having a care, lest he should say any word amiss.
If he refused to take any thing offered to him, and was again pressed to take it,
he replied, '`Would you have me tell a lie?`'
Once having refused something, he was desired to promise to take it in such a time;
his answer was '`Can I tell what is to come?`'
When he took that which he found refreshed him,
he with much thankfulness acknowledged it;
being also very sensible of the love and tender regard which his parents had towards him,
and expressed it several times to them.
He bore his sickness with much patience, and often expressed his willingness to die;
saying, '`It is better for me to die; this is a troublesome world;
and we should every day and every moment think upon the Lord.`'

A few days before his decease,
he uttered many expressions in prayer and praises to the Lord, saying,
'`You are a God of love, you are a God of mercy;
you know the hearts of them that love you; you know the hearts of them that seek you.
Lord remember your people.
You know the hearts of the ungodly; you know the hearts of the wicked;
you have nourished and brought up children, and they have rebelled against you.`'
He also spoke of the care we ought to take of the never-dying soul,
and that the Lord will send forth his messengers.
Another time, expressing his inward satisfaction at a future state, he said, '`Glory,
glory; joy, joy: come mother, come father, come all; it is a brave place,
there are no tears nor sorrow:`' and praised God, saying,
'`You are worthy to have the honor and the glory forevermore; for to you it does belong.
You are God of heaven,
and of the whole earth;`' and continued about a quarter of an hour in prayer,
and said to the Lord, '`I am an infant, and cannot do anything without you.`'

One evening, several friends coming to visit him,
he desired their prayers to the Lord for him: and the next day himself prayed again,
saying, '`Our Father, who art in heaven,`'etc.
Afterwards he said, '`It is a brave thing to be at peace with the Lord.`'
His end drawing near, he said, '`Father, let me die.`'
And again called out '`Father, father.`'
His father being present, asked what he desired?
He said, '`I do not speak to you, but to my heavenly Father:
have mercy on me;`' and expressed much joy that he had with the Lord;
and desired them about him that he might be still; and so lay secretly praising the Lord.
A few hours before he died, he said, '`I come, Father, I come:`' and being very weak,
his voice was low, but he was heard to say, '`God is my father:`'
and so like a lamb he quietly finished his days the 12th of the Twelfth month,
in the year 1700, aged nine years.

[.the-end]
END OF THE FIRST PART.
