== Chapter 3

[.chapter-synopsis]
* Thomas Janney
* Henry Stout
* Thomas Aldam
* Margaret Kellam
* Joan Kellam
* Sarah Brown
* William Walker
* Ruth Middleton
* Alexander Jaffray
* Mary Padley
* Charles Marshall
* Sarah Padley

THOMAS JANNEY was born in Cheshire,
and received the blessed truth at the first preaching thereof in that county,
which was about the year 1654, being then in the twenty-first year of his age.
The next year he received a gift in the ministry, preaching the gospel of Christ freely;
and travelled into many parts of England and also in Ireland,
and had a fervent and sound testimony for truth;
and his conduct and course of life accorded with his doctrine.

In the year 1683, he with his family went to Pennsylvania, and there settled,
where he stayed about twelve years; and in the year 1695,
he came over again in company with his friend Griffith Owen, of Pennsylvania,
to visit his brethren in England: and after he had stayed some time in London,
he went into Cheshire in the Sixth month of the same year,
where he had many relations who were faithful friends; and though they were dear to him,
and their houses might have been his home, yet he rested little,
but visited the meetings of Friends in several neighboring counties.

The next spring he travelled through several counties where he had been in former years;
and as he had a desire to see the brethren at the yearly meeting in London,
he was there at that time; soon after which he was taken so ill,
having decayed in his natural strength before, that his recovery was much doubted;
and some advised him to go out of the city for the recovery of his health.
After some time he adventured by short journeys from London to Enfield, so to Hertford,
and from there to Hitchin, where his distemper increasing he could go no further,
having a purpose to go for Cheshire.
At Hitchin he lay a considerable time at the house of our friend William Turner;
and friends there were careful and tender over him;
and he having endured much hardship formerly in the service of truth,
by traveling into several climates, and enduring heats and colds,
his body was attended with much pain, so that few expected his recovery.

Two of his relations, who were friends, came from Cheshire to Hitchin to visit him,
and one of them being with him in his chamber, he said to this effect: "`Cousin,
I am glad that you are come.
I hardly expect to recover so as to be able to get into Cheshire.
It is some exercise to think of being taken away so far from my home and family,
and also from my friends and relations in Cheshire.
I would gladly have got down into Cheshire; but I must be content,
however it pleases God to order it.
Worse things have happened in this life to better men than I am.
I shall be missed in America; friends there were troubled when I came away.
I have labored faithfully among them; they will be grieved at the tidings of my death.
My family will miss me.
My care has been for my sons, that they may be kept in the fear of God.
I have been a good example to them.
I have a care upon me, that they may be kept humble while they are young,
that they may bend their necks under the yoke of Christ.
If I am taken away, I am very clear in my spirit.
I have answered the requirings of God; I have been faithful in my day,
and I have nothing that troubles my spirit; my spirit is very clear.`"
He also expressed his concern for his brethren in the ministry, especially the young,
that they might observe the leadings of God`'s spirit in their ministry,
and not lean upon their own natural parts, which, he said,
occasioned various inconveniences;
of which he spoke particularly in the time of his sickness.

After this, the Lord answered his desire, that he recovered,
so as to be able to get down to Cheshire to his relations there;
and he got abroad to some meetings that winter, but yet was weakly in body; and,
towards the spring, he made preparation to get home to his family in Pennsylvania;
but before the ship set sail, his distemper, which had not quite left him,
returned sorely upon him.
He went to his sister`'s, near where he was born,
and she spoke something to him about his family; but he said little,
only these words; "`If it be the will of God that I be taken away now,
I am well content;`" which was the most he said in his last illness,
save to a Friend concerning his burial.

He departed in much quietness of mind, the 12th of the Twelfth month, in the year 1696,
and was buried the 15th of the same, in Friends`' burying-place, in Cheshire,
aged sixty-three years: having been a public minister forty-two years.

[.asterism]
'''

HENRY STOUT, of Hertford, born at Ware, in the county of Hertford, in the year 1631,
was convinced of the blessed truth by the ministry of a woman, in the year 1655,
being then about the twenty-fourth year of his age.
At which time some of the people called Quakers came into that part of the county,
concerning whom he had heard evil reports, and that they denied the Scriptures;
which had prejudiced his mind against them.
But it so happened that there came a woman called a Quaker, and preached in Ware market;
and afterwards a rude rabble followed her down the street, and he seeing them,
followed her also, in pity towards her, and to rescue her from them.
But she turned into a house where there was a meeting; and a Friend was speaking there,
unto whom he listened, and heard him speak much Scripture,
although he named neither chapter nor verse; at which he wondered,
because he had heard that they denied the Scriptures.

After he thus lent an ear, the woman stood up and spoke;
and such a power attended her ministry, that his spirit was much broken,
and astonishment seized on him; and he saw others also with paleness of face,
and they smote their hands.
This brought great fear upon him, lest he should be deceived;
yet was he afraid also that he should offend God, and resist the day of his visitation.
This brought great sorrow upon him for a time, he not being able to distinguish;
but afterwards going to another meeting, he heard another woman,
by whose preaching his convincement was increased; and he was so confirmed,
that he could set to his seal that it was the very
truth which had long been veiled in him;
but now, by the preaching of the gospel, was revealed.
He could say, Christ was come, and he looked not for another;
and it was confirmed by the work that was wrought both within and without.
First, within, the eye which had been shut was now opened,
and the ear that had been deaf, now heard, and the mouth of the dumb could speak,
and the lame could walk, and the mysteries of the kingdom of God were known,
which before were in parables.

He searched the Holy Scriptures, and found it was the good old way,
though new to him and others;
and the Scriptures were opened by the spirit that gave them forth,
and a witness for God he had in himself, according to 1 John 5:10, "`He that believes,
has the witness in himself.`"
Then he took up the cross and denied himself, and so became a gazing stock to the world,
as the Lord`'s people were in those days, as well as in former ages.
Soon after he was moved of the Lord to go to the public places of worship,
to declare against them, and to preach the truth.
Persecution and sufferings soon followed;
for many and various were the trials and exercises which
the Lord`'s people went through in their day.

He was the first called a Quaker who suffered imprisonment in Hertford jail,
for the testimony to the truth; where his sufferings were great,
the prison-windows being shut, that he might not have the benefit of the air,
or the light of the day.
After he was released of that imprisonment,
he was a prisoner five times more in that town of Hertford;
the last of which he was sentenced for banishment,
and continued a prisoner nearly eight years, to the great detriment of his health,
being often put into the common jail;
which trials the Lord carried him through with much patience,
contentedness and quietness of mind, he being given up to the will of God.

He was a serviceable man in many respects,
and willing to do what offices of love he could for any.
He travelled pretty much in the service of truth in his younger years,
while he had strength of body, but some time before his death, distempers grew,
and weakness increased upon him, which made him incapable of being much from home.

The last four months before his death, he went little abroad, but grew weaker and weaker;
the which his wife perceiving, did much importune him to advise with some doctor;
but he answered her thus, "`I would not have you confide too much in doctors,
for they will all prove physicians of no value to me.
I thank God, I know that power which in former ages raised the dead,
and healed all diseases; and if it is the will of God, he can restore and heal me;
if not, I am satisfied; his will be done.`"

His greatest infirmity was a stoppage at his stomach, and shortness of breath,
which often brought faintings upon him; but he bore all with great patience.
And when some friends came to visit him,
he told them his weakness was such that he thought he should hardly recover it;
but however it pleased God to order it, he was fully satisfied:
for he had this testimony, that he had served the Lord with faithfulness,
and with an upright heart, to the best of his knowledge: with more to that effect,
which cannot be well remembered.
At another time to a friend that came to see him, he said,
"`None know the virtue and goodness of truth so well
as when they draw near their latter end,
when all outward comforts fail, and are leaving them,
and sickness and weakness come upon them.`"

He further said that he had travelled in the service of truth in former years,
when he had strength of body,
and the Lord had given him many living testimonies to bear for his name;
in all which he was faithful, and the remembrance of it warmed his heart at that time;
for he could say that his care was,
not to speak more than what the Lord gave him to speak,
that thereby his name might be honored.
Many times, and upon several occasions, he so expressed himself,
as fully manifested the true satisfaction and peace he had with the Lord;
often desiring to be dissolved, that he might go home to his rest.

The Lord`'s love and gentle dealing appeared very largely towards him,
in giving him many times ease of body, and comfortable seasons of refreshment;
and he generally rested well in the night, till about a week before his death.
The sense of it would often make him break forth
into praises and thanksgiving to the Lord,
for his goodness and mercy to him in the night-season.
When he awaked out of his sleep, and when his sleep was taken from him,
he continued quiet, patient, and sensible to the last moment.
And when his wife saw that he slept little, and took little,
hardly enough to keep him alive, she was full of grief; which he perceiving, said to her,
"`You must give me up, for I shall not long continue here:
but it will not be long before you and I shall meet again in that blessed state,
where all tears shall be wiped from our eyes.`"

He kept his bed but four days; and the day before his death, his children being by him,
he said to them, "`You, who are likely to enjoy what I have,
I would have you to remember the advice of your father when I am gone,
and live in the fear of God, and as it becomes the truth; then you will be as monuments,
when I am gone, and it will go well with you, and what I leave will be a blessing to you.
Beware of earthly-mindedness, and pride, and prodigality,
which is a dishonor to any family; and bring up your children in plainness,
and not in the fashions and superfluities of the world, which passes away.
Remember my advice, who speak to you in love: for woe will be to the wicked.
I would say more to you, but my strength fails.`"

The day he died he spoke little, but lay as if he slept;
but sometimes fainting fits would come,
that it was thought he would have gone away in one of them; but he did not,
but fell into a slumbering; and when he awaked,
he desired to be turned on the other side, and then he stretched out his hands and feet,
and said, "`Now I am going to the Lord;`" which were the last words he spoke:
and so departed in peace, without so much as a groan or sigh.

Thus he finished his course, and laid down his body, the 6th of the Tenth month,
in the year 1695, in the sixty-fifth year of his age.

[.asterism]
'''

THOMAS ALDAM, of Warnsworth, in Yorkshire,
received the glad tidings of the gospel of life and salvation very early, that is,
in the year 1651, by the preaching of that eminent and faithful servant of Christ Jesus,
George Fox, soon after he was delivered out of the dungeon in Derby prison.
At this time, Thomas Aldam, John Kellam, Thomas Kellam, Richard Farnsworth,
Thomas Goodyear, and several others of note, received the truth; and many sufferings,
beatings, reproaches, spoiling of goods, and imprisonments he endured,
for Christ`'s sake and the gospel`'s; being often concerned to go into marketplaces,
and public places of worship, bearing testimony against the wickedness of the world,
and against such teachers and leaders as caused them to err, through lightness, pride,
and covetousness.

Before he was convinced,
he was a great follower of the priests and teachers of those times,
but his hungering and thirsty soul not being satisfied among them, he left them,
and waited as alone, until it pleased the Lord to send his servant George Fox,
as aforesaid, into those parts of the country.
And he having received the truth, was valiant for the same upon earth,
and gave up his strength and substance to serve the Lord.
He was very zealous and fervent in spirit, severe against evil,
but tender to the least appearance of that which was good,
watching over his children in the fear of God; given to charity, and to do good to all.

He was one of the first called a Quaker,
who was imprisoned in York Castle upon that account, in the year 1652.
It was for going to Warnsworth steeple-house, and speaking to Thomas Rookbey,
a priest of that place, who procured his imprisonment at York,
where he was kept two years and six months so close,
that he was not permitted once to come home, nor to see any of his children;
and sometimes not permitted to see his wife and relations when they went to visit him.
He was also fined during that imprisonment £40, at the assizes,
for appearing before the judge with his hat on his head,
and for speaking thee and thou to him.

During the aforesaid imprisonment, his adversary Rookbey, the priest, and one Vincent,
an impropriator, sued him at the law for treble damages,
and they made spoil of his goods to the value of £42;
not leaving one cow to give milk for his young children and family.
Thus he suffered for his faithful testimony to the
coming of the Lord Jesus Christ in the flesh,
and for his free ministry;
at other times also he suffered the loss of goods for his testimony to the truth.

As he had been a sufferer himself, so he had a tender sympathy for the Lord`'s people,
his brethren, who were sufferers for the truth,
and would go oftentimes to Oliver Cromwell, and others, the rulers of those times,
and lay the sufferings of Friends before them.

He also travelled into Scotland and Ireland,
and went to the chief rulers there upon the same account.
He went to all, or most of the prisons in England,
where there were any of the people called Quakers,
to take a perfect account of their sufferings,
that he might be the more capable to advocate their cases before the government,
being ready at assizes, sessions, or elsewhere, to plead the cause of God`'s people.

He had a tender regard to love and unity among brethren,
bearing good esteem in his mind for such as labored in the gospel.

When he was about to undertake any journey upon truth`'s account,
he would call his family together,
and in much humility pour out his supplication to God to preserve them.

After thus having served his generation in faithfulness, he was visited with sickness,
in which time he set his house in order; and in the time of his weakness,
the Lord was good to him, and eminently appeared with him, so that he said to his sister,
near his latter end, that he found his strength so renewed,
that he believed he could get to London if the Lord required it: but he answered again,
"`I am clear of the blood of all men.
I find nothing to this man,`" meaning king Charles the Second,
then lately restored to his kingdom.

He was very sensible of his latter end; and the day he died he called for his children,
and exhorted them to live in the fear of God, and to love and obey their mother: and so,
being freely resigned into the hands of God his Creator,
he departed this life in the Fourth month, in the year 1660.

His wife, Mary Aldam, survived him but three months.
She was a woman fearing God, and served him in her generation.
In all the exercises which her husband passed through in those early days,
she never was heard to grudge or repine,
but was given up in all things to God`'s disposing.
Her remembrance is sweet,
and her name to be recorded among the faithful of God`'s people.
She received truth by the ministry of George Fox, at the same time her husband did,
and bore testimony to the same truth, according to her measure.
He had also two sisters, faithful women.

[.asterism]
'''

MARGARET KELLAM, who was convinced about the year 1651,
travelled much in truth`'s service in the breaking-forth thereof,
and many were convinced by her.
She also suffered imprisonment for the same at Exeter, York, and Banbury in Oxfordshire;
and great was the courage that attended her in preaching truth in the streets, markets,
and public places of worship, and to the rulers of the people;
and the Lord was with her.

She finished her course in faith,
signifying before her departure the great peace she enjoyed with the Lord,
and the clearness of conscience she had before him.
And so departed this life in the year 1672.

[.asterism]
'''

JOAN KELLAM was also a woman that truly feared God, and a good example where she dwelt:
she was of sound judgment, and well experienced in the work of the Lord;
zealous for his honor, and faithful to the truth; an encourager of virtue,
and watching over the young, and an instructor of them in the right way of the Lord.
She could speak a word in due season to an afflicted soul,
having passed through many states, and seen the wonders and goodness of the Lord therein;
and was as a mother in Israel.

In the time of her sickness she was well disposed,
and gave good advice to them she left behind her,
that they might persevere in faithfulness,
to the finishing of that work which the Lord had for them to do.
So departed this life in the year 1681.

[.asterism]
'''

SARAH BROWN, wife of Capt.
Brown, of Leicestershire, and mother to Samuel Brown, physician in the town of Leicester,
was one who in her young years fervently and sincerely sought the Lord,
and frequented the assemblies of the best sort of people in that day, called Puritans;
afterwards she joined herself to the Baptists, among whom she walked inoffensively.

But when it pleased God to raise up his people called Quakers,
in the northern parts of this nation,
and gave some of them commission to publish the way of life and salvation,
she received their testimony with great joy and thankfulness
to the Lord and was a nursing mother among that people.
Her husband, at her request, gave up his house for Friends to keep meetings in,
even at the breaking forth of truth in that day:
and she counted nothing too dear to part with for
truth`'s sake and was a good example in conduct,
in temperance, meekness and charity, towards those with whom she was concerned.
She was a true wife and a tender mother, a loving relation,
a good neighbor and firm friend.
She had a word of comfort in due season to many when in afflictions;
she loved to visit the widow and the fatherless, the prisoners,
and the house of mourning; and to feed the hungry, and clothe the naked,
and to wash the saints`' feet.
She suffered imprisonment, and spoiling of goods for the truth`'s sake,
counting all as dross and dung, that she might win Christ.

When death came she received it with contentedness,
being given up to God`'s good will and pleasure, and she lived to old age.

A friend visiting her in her last sickness, said to her,
"`The Lord has sent his messenger`" (meaning, that her end was at hand); she made answer,
"`He is come;`" and desired the Lord to give her an easy passage.
She was first taken ill in the night with a violent pain in her legs,
and her son Samuel Brown being presently called,
she prayed to the Lord to mitigate the violence of her pain,
and to give her strength to bear his hand with patience.
Her son was much grieved for her; which she perceiving, said, "`Child, do not do so;
rejoice and be glad, for you have no other cause.
You have been a dutiful and loving son to me, even to the full.`"
The Lord answered her prayer; and in a short time took away the violence of her pain;
and she praised the Lord, and blessed his name, for his mercies and goodness;
speaking of his great mercy and favor to her all her life long,
to the great comfort of her children about her; and blessed her son, saying,
"`The Lord bless you and yours, for your love and duty to me;
for I do rejoice that you were born unto me.`"
Also to her son`'s wife she said, "`Daughter, you did promise to take care of me,
when weakness should approach; and now you are as good as your word:
the Lord bless you and yours, for all your love to me.`"
And in the sense of the love of the Lord to her she prayed, "`O Lord,
guide your poor hand-maid into your everlasting kingdom,
where I may sing hallelujahs to you forever.`"

She gave order, two days before her departure,
(being sick but six days) to be buried at Leicester, by her grandchildren;
and so died in a good old age, at her son, Samuel Brown`'s, at Leicester,
on the 30th of the Ninth month, in the year 1693, aged eighty-three years.

[.asterism]
'''

WILLIAM WALKER, an inhabitant of Pennsylvania, born in Yorkshire,
but convinced in Pennsylvania,
was one who bore a living testimony to the truth of God in the assemblies of his people.
He came over to visit his friends and brethren in England,
about the latter end of the year 1693, in company with other Friends from those parts,
which was about the time George Keith came over from America.
This our friend often expressed his great sorrow for George Keith,
and the sore exercise and trouble he gave to friends in America,
by his contention and jangling;
and he had a testimony against that spirit but a few days before he died,
that God would judge it.

After he had visited friends about London, he went into several counties,
and also into Wales; and returned to London,
in order to be at the yearly meeting in 1694;
a little before which time he was taken sick there,
and endeavors were used for his recovery, but they proved unsuccessful.
In the time of his sickness he was often filled with
the love and power of God in his soul,
to the comfort of those present.
Observing some to weep, he said, "`Weep not, dear hearts, lest you trouble me.`"
Afterwards he said, "`the goodness of the Lord!`" And lifting up his hands, he said, "`Lord,
you are altogether able to do wonderful things!
You shall be my physician.
Oh the wonders of the Lord!
What have I seen of the transcendent glory!
Though I see but a little, yet it is admirable glory.`"
Again he said, "`The old enemy would have had me let go my hold; but I said,
I have an interest in you, and I will hold you, Lord.`"

Those about him being desirous that he might recover, he said, "`No,
I have no promise of life.`"
Speaking of Christ, he said, "`I can see him; his arm is open to receive me.`"
After some time he said, "`The Lord is a physician indeed, a physician of value.`"
Another time he said, "`We must all double our diligence.`" Another time,
lying in a still frame of mind, he sang in sweet melody as follows:
"`His compassion fails not; he waits to be gracious: Oh the wonders of the Lord!
The wonders of the Lord in the deep.`"
Another time he said, "`My faith is steadfast in the dear Son of God;
that although I am under great weakness and afflictions,
yet in the strength of my Father`'s love I shall be
enabled to stand against the mists of darkness.
The enemy would eagerly unpin my faith:
God`'s people are always preserved while they wait still at home.
Oh! Lord Jesus Christ!
I will hold you fast; your compassion fails not.
Oh! sweet Jesus Christ, I have great cause to hold you fast.
Oh! sweeten death unto me!
Oh! your sweet presence!
In it there is life.
Oh!
Lord, give me strength; I will not let you go: you have regard to them that fear you,
your compassion fails not; you are at my right hand to uphold me.
Oh! my Savior! you are at my right hand to save me; your compassion fails not, O Lord.`"
Afterwards he said, "`Oh!
Lord Jesus!
Come, sweet Jesus, I long for you; now death is pleasant.`"

His wife`'s sister being by him, he said, "`Fear the Lord God.`"
She said, "`Would you say
any thing to your wife?`"
He answered, "`My dear and tender love in the Lord Jesus unto her,
and to all my dear friends everywhere; and that you may double your diligence,
to your soul`'s comfort, the days you have here.
My dear love to our dear friends in America, where I have been sweetly refreshed,
and had many good meetings among them.`"
After a little repose, he said, "`Oh!
Fountain of Life!`" Then stopped, and thus spoke again,
"`I cast the care of my dear wife and children, if living, upon the Lord; I trust in him.`"
After some rest, he said, "`Lord Jesus Christ, come, receive my poor soul: come,
O my soul`'s beloved!
Come, Lord, I long for you.
Lord Jesus Christ, if there be any iniquity in me, search it out.`"

Afterwards he said, "`I feel the angel of your presence to surround me: come,
Lord Jesus Christ, come, come, receive my soul into your bosom.`"
Again he said, "`Come, Lord Jesus Christ, let me entreat you come away,
and receive me out of all sorrow; come away, my Lord.`"
After a little time he said, "`I feel the Fountain of Life; my soul`'s beloved, is come.`"
He died in peace with the Lord, as those then present can testify,
that he was in a sweet, heavenly frame of spirit when he drew his last breath,
which was on the 12th of the Fourth month, in the year 1694, at the house of John Padley,
in Olave`'s Parish, Southwark.

[.asterism]
'''

RUTH MIDDLETON, daughter of Samuel Middleton and Rebecca his wife,
was visited with a consumption in the Tenth month, 1700,
and continued in much weakness of body till the 16th of the Fifth month, 1701.
During her sickness, these expressions, among others, were observed.

One time, her mother being much concerned to part with her,
the child lying still as if she was in a slumber, opened her eyes and said,
"`What`'s the matter?
What`'s the matter?
My dear mother, do not be troubled for me; do not sorrow for me, I shall be happy.
It is the Lord`'s will that I am thus afflicted, and we must be contented.
You know that Abraham was willing to offer up his only son Isaac;
and you do not know if you could freely give me up,
but that the Lord might spare me a little longer to you;
and if it be his good pleasure to take me to himself, his holy name be blessed forever.`"
Another time her mother said, "`How are you now?`"
She replied, "`But indifferent; but I am well satisfied,
for it is the will of God that I am thus afflicted.
Oh! my dear mother, I would be glad if you could freely give me up.`"

One time, going to slumber, she prayed thus: "`Our Father who art in heaven,
hallowed be your name, your kingdom come, your will be done in me,
as it is in heaven. Oh! sweet Lord Jesus,
feed me daily with the bread that comes down from heaven.
Lord, if it stand with your will, grant that I may sleep to refresh this poor needy body:
but you, Lord, know what I stand in need of, better than I can ask.
Lord, be with me, and my father, and mother, and brother.`"
Thereupon she went to sleep: and when she awoke, she said,
"`Oh! blessed and praised be your holy name,
O Father of life! for you have heard my desires, and have answered me;
for I have slept sweetly.`"

Another time she said, "`The Lord said to his followers,
'`Permit the little children to come unto me, and forbid them not,
for of such is the kingdom of heaven.`'
And if I be not happy, what will become of ungodly men and women?
For truly I am afraid of offending anybody, for fear I should offend the Lord.`"
One time she said, "`Pray, mother, have a strict eye over my brother,
for he is very full of play.`"
A friend, after inquiring how she did, said, "`I hope your eye is still to the Lord:`"
her reply was,
"`Although I can hardly speak, I think upon the Lord,
and he knows my thoughts, and answers them;`" with more sensible words.

Another time she said, "`It will not be long before I shall be at rest and peace,
where there is no more pain to the body nor to the mind;
and where there is nothing but joy forevermore.
Dear mother, be willing to part with me, for I am willing to part with you all.
I am not at all concerned for myself, but for you, poor mother,
who does and will make your bed a bed of tears often for me.`"

Hearing her mother question her recovery, she said, "`Oh! what the Lord pleases;
for I am not afraid of death.
I never wronged anybody of a pin to my knowledge, nor loved to make excuses.
I never told a lie but once; when I should have said yes, I said no:
that has been a great trouble to me; but the Lord, I hope, will forgive me,
for I called the maid, and told her the truth.`"

Near her end she desired to come out of the country to London, and said,
"`The air does me no good, and the doctor does me no good:
the Lord is the same at home as here.`"
And when she was removed home, she said, "`Now I am glad;
if I die it is better to be here, and will save a great deal of trouble.`"

A Friend asked her if she was willing to leave father and mother, and go to the Lord;
after some pause she answered, "`If the Lord please,
I am willing this very minute to leave all, for I shall be happy.`"

The night before her departure, after a Friend had prayed by her, she said,
"`I do understand well, and am inwardly refreshed.
I am sorry that I cannot speak so that the Friend could hear,
or else I would give an account of my inward peace with the Lord.`"

A few hours before her death she thus prayed, but her voice was very low: "`Oh,
Lord! withhold not your tender mercies from me at the hour of death.
Oh, Lord! let your lovingkindness continually preserve me.`"
Afterwards she said, "`I desire to slumber; but if I die before I wake,
I desire the Lord may receive my soul.`"

She was thankful for the tender regard her mother had to her, and with a low voice said,
"`Farewell, dear mother; in the love of the Lord, farewell.`"
And then desired to see her father and brother; and feeling for her brother`'s face,
she stroked him and said, "`Farewell, be a good boy.`"

Her father asking her how it was with her, she replied, "`I am just spent,
but I am very easy, and shall be very happy. My body is full of pain,
but the angel of the Lord is with me,
and his presence will forever preserve me;`" and so kissed her relations,
and bade them all farewell.

Her last words were her desire to be remembered to
the Friends who visited her in her sickness;
and, in less than half a quarter of an hour, like a lamb she departed this life,
on the 16th of the Fifth month, in the year 1701, being eleven years, two months,
and four days old.

[.asterism]
'''

ALEXANDER JAFFRAY, of Kingswell, in the north of Scotland, born in the city of Aberdeen,
was one who early remembered his Creator;
and as he grew in years he increased in a religious concern towards God,
and those who he thought feared him.
He joined, when young, with the Presbyterians,
though he was educated in another form of religion; but some time after,
when those people got into rule and government,
they forgot their former low and persecuted condition, and grew high, rigid,
and fierce persecutors of others; therefore he soon disliked them,
and signified the same to some of the chiefest among them,
having been himself one of those commissioners who were deputed by the
nation of Scotland to treat on articles with King Charles the Second,
then in Holland, in the year 1650.

After he left the Presbyterian way, for some time he was among the Independents,
and finding them also to be for setting up themselves, and persecuting others,
he could no longer follow them.
After this he remained in private for some years, a solitary mourner,
not joining with any profession in religion;
nor allowing several of his children to be sprinkled or baptized (as they called it),
because he could not own their way of constituting national churches;
and this was long before he was called a Quaker.
In his solitary retirement he sought the Lord,
waiting for a people who were spiritually touched with a divine coal from the altar,
to kindle true and spiritual sacrifices to God.

When he first heard that God had raised up such a people in England,
who directed all to God`'s pure light, spirit and grace in their own hearts,
as the most sure teacher and leader into all truth, worship and religion,
he said he felt his heart to leap within him for joy.
After weighty examination concerning the people called Quakers,
who preached the truth among them, he found his heart and soul united to them.
This was in the year 1662,
a time when it was as bitter a cross even as death to own them,
especially to one of his repute; and shortly after, several more men of note,
in that nation, were convinced of the same way of truth,
as John Swinton in the southern parts, David Barclay, Alexander Skein, Thomas Mercer,
and others.

This made the priests and others persecute them; but they stood their ground,
through the grace of God, and boldly bore their testimony valiantly,
particularly Alexander Jaffray,
contending for the truth in solemn conferences with the bishop of Aberdeen,
and the chief preachers of that city.

He was faithful in his testimony to the truth to the last;
and in his sickly old age was imprisoned many miles from his own house,
for non-payment of tithes.
It is remarkable that, a little before this imprisonment, being near to death,
as was judged by all who saw him, he signified under his hand,
being altogether unable to speak, by a great swelling in his throat,
that his God had yet a service for him to do, in suffering for his precious truth;
and that he was not to die at that time.

He was taken sick the latter end of the Fourth month, 1673;
and during the twelve days of his sickness,
he uttered many living testimonies to the blessed truth, before many witnesses,
both Friends and other people, who visited him; and a few of them are as follows:

He said that "`it was his great joy and comfort in that hour,
that ever he had been counted worthy to bear a testimony to, and suffer for,
that precious testimony of Christ Jesus,
his inward appearance in the hearts of the children of men, visiting all by his light,
grace and spirit, that convinces of sin; and that it was,
and would be the great judgment and condemnation of many in this nation,
particularly of the professors, that they have so slighted and despised, yes,
hated the said light and witnesses thereunto.`"

Sometimes being overcome in spirit, he said, "`Now Lord, let your servant depart in peace,
for my eyes spiritually have seen, my heart has felt, and is feeling,
and shall ever feel, your salvation.`"

He also prophesied of a great and near trial shortly to come,
wherein some that were not what they seemed to be, should be discovered and fall;
but the upright and lowly ones, the lowly shrubs should be preserved,
when tall and sturdy oaks should be overthrown; which is since fulfilled upon some.

He farther said, that the Lord had given him the garments of praise,
instead of the spirit of heaviness.
Sometimes, when very sick, he would bless the Lord,
that now fighting with a natural death, he had not an angry God to deal with.
"`Oh!`" says he, "`the sting of death is fully gone, and death is mine;
being reconciled to me as a sweet passage, through him that loved me.`"
Another time, seeing the candle almost out, he said, "`My natural life is near an end,
like that candle, for lack of nourishment or matter to entertain it;
but in this we shall differ, that if it be let alone, that goes out with a stink,
and I shall go out with a good savor, praises to my God forever.`"

A little before his breath ceased, he said he had been with his God,
and had seen deep things;
about which time he was filled with the power of God in a wonderful manner,
which much affected those present, and in a little time after, he died like a lamb,
being the 6th day of the Fifth month, in the year 1673, aged fifty-nine years;
and was buried in a piece of ground set apart near his own house at Kingswell,
the 8th of the same month.

[.asterism]
'''

MARY PADLEY, wife of John Padley, timber-merchant, of Olave`'s, Southwark,
was a woman adorned with truth and innocency, chaste, upright, and sincere-hearted,
industrious, yet void of covetousness, so that virtue shone forth in her conduct.
She was also charitable to the poor, plain in apparel, adorning the truth in her conduct,
punctual in performing her promise, and in the discharge of any trust reposed in her.
She spent her days in the fear of God, so the Lord was gracious to her at her death.

She was taken with pains, the 6th of the Seventh month, 1695, at which time she said,
in much tenderness and fervency of spirit, "`My God, and my father, deliver me.`"
And after she was delivered, she praised God for his mercies towards her:
and afterwards being asked by her husband how she did,
finding some unusual symptoms attend her, she answered, "`Weak, but well satisfied.`"
And as a confirmation thereof, she broke forth into sweet praises to the Lord; and died,
leaving behind her four young children.
Aged about twenty-eight years.

[.asterism]
'''

CHARLES MARSHALL, born at Bristol in the year 1637,
was religiously educated by his parents in the Independent way.
In his tender years he had inward desires after the knowledge of God.

After he had continued some years among the Independents, and also the Baptists,
he grew more and more dissatisfied with the empty and lifeless
profession of those among whom he walked.
He spent much time in retirement alone in the fields,
under a sense of his state and condition, crying unto the Lord,
and seeking after his saving knowledge.
In this state he continued,
until it pleased God to send to that city his faithful servant John Audland,
from out of the north of England,
by whose powerful ministry he was turned to the light of Christ Jesus in his own heart,
which had before discovered his state and condition to him.
After he came to turn in his mind to the light of the Lord,
and was thereby and therein resigned, he witnessed God`'s pure power,
love and life to break in upon him; and after manifold exercises and troubles,
was raised up a powerful minister of Christ Jesus,
and an instrument in God`'s hand to turn many to righteousness.

He was moved in the year 1670 to go through the nation of England,
and visit God`'s heritage, which he did within the compass of one year;
and although it was then a time of great persecution,
yet in all his passage through cities, towns, and all the counties of the land,
no man was allowed to lay hands on him, or stop his way.

He continued a faithful minister,
and labored much in the gospel to the time of his sickness, which lasted several months;
in all which time great patience and meekness appeared in him,
although under weakness and affliction of body.

He had some sight and knowledge of his end;
for a little before he was taken ill he earnestly pressed
a particular friend of his to ride out of town with him,
having something of moment to impart to him.
When they were a few miles from London, he said, among other things,
that he was satisfied his departure drew near,
and therefore had a desire to discourse with him
about some particular things before he died.
And when he was taken ill he sent for the same friend,
and told him now he was satisfied he should go abroad no more;
although in his first illness there was no such appearance to others,
which the said friend told him; but whatsoever he said to take him off of such thoughts,
it had no impression upon him; he continued fixed in his mind,
that he should die of that illness.

Several of his friends pressed him to go into the country,
but he desired only to go to John Padley`'s, a Friend that dwelt near the river side,
which he much liked; and at his first going there he was a little better,
but soon altered again.
He lay ill there about three months, under great weakness;
and several Friends often came to see him,
and he would be frequently giving them seasonable counsel and advice,
in many heavenly expressions, and would often exhort them to keep in love and unity,
and to the living divine power and life of truth,
that thereby they might be kept a people fresh and green, and living to God,
that so formality might not prevail over them.
He pressed that a great regard might be had of the poor,
and that some way might be found out for their employment; often saying to this effect,
that in an inexpressible manner he felt their sufferings, by reason of their poverty.
Indeed he was a man who greatly sympathized with
those who were afflicted either in body or mind,
being of a very tender spirit.

A little before his departure, he sending for John Padley and his wife into his chamber,
said to him, "`Dear John, do what you can for the honor of truth,
and the Lord bless you and yours for generations to come.`"
To his wife he said that he desired the Lord might be with
her when she came to such a time as that he was then in,
i.e., a deathbed, and make her passage easy; and his desire was granted,
for she died in less than a year after; and said, on her dying bed,
that the Lord had answered dear Charles Marshall`'s request, for she lay very easy,
and freely given up.
As he lay in this weak condition he was often opening his mind to several of his friends;
particularly when several ministering Friends came to see him, he spoke to this effect:
"`I have loved the brotherhood;
I have sought the unity and peace of the churches for these forty years,
and to my great comfort I never did any thing tending to the breach thereof.
I have two things that lie upon me to Friends,
which I desire may be communicated to them.`"

"`The first is,
that they gather down into the immortal Seed and Word of life in themselves,
and be exercised in it before the Lord,
and duly prize and set a value upon the many outward and inward mercies, and blessings,
and heavenly visitations, that the Lord has eminently bestowed upon them,
since the morning of the day of his blessed visitation;
then shall they grow and be preserved in a living freshness to him:
and the Lord will continue his mercies to them,
and they shall not lack his divine refreshing presence
in their meetings together before him.

"`The second thing is, that those Friends to whom the Lord has given great estates,
ought to cast their bread upon the waters, and do good therewith in their lifetime;
for those who are enjoyers of such things should see that they are good stewards thereof.
Oh! the many poor families that such persons might be a help to! how easily might they,
with a little,
assist many a family to live in the world! and what a comfort would it
be for such to see the fruits of their charity in their lifetime.`"

When our friend George Whitehead came to see him, with much tenderness of spirit,
he signified his great peace and satisfaction, and that he always, from the first,
had an honorable esteem of the unity of his brethren.
A little before his departure,
when our friend William Penn and several others visited him,
he lay as a man gathered up in his spirit unto God; and though he was almost spent,
his voice being very low, hardly to be heard, yet by what was understood,
it might be perceived that he had in possession the earnest of
that blessed peace which he was going to receive the fulness of.
The observation of his peace, and happy condition, much affected those present.
He departed like a child, in a quiet frame of spirit, the 15th of the Ninth month,
in the year 1698, aged sixty-one years,
and was buried from Grace-church-street meetinghouse, in Friends`' burial ground,
near Bunhill-fields, London.

[.asterism]
'''

SARAH PADLEY, second wife of John Padley, aforesaid, of Olave`'s, Southwark,
was a woman of a meek and quiet spirit, and had great sympathy with those in affliction;
and bore a public testimony for God in the assemblies of his people,
and she had an honorable esteem of the faithful elders in the church.

She was taken ill the 26th day of the Fifth month, 1699,
and was sensible her end was near, and on that account was concerned for her husband.
The love of God, with which she was filled, caused her sweetly to praise his name,
so that the sense of the pains and weakness of her body seemed to be taken away.
One time, in the sense of the love of God to her soul, she cried out, "`Oh! death,
where is your sting?`"
Often praying and praising God,
and during the whole time of her sickness she was freely given up to die.

A few days before her departure she said to her husband,
"`You are the dearest of any thing in the world to me; yet I can freely leave you.`"
Another time she said to him,
"`The Lord has answered dear Charles Marshall`'s prayer for me;`" remembering that C. M.,
who died at her house, had desired, upon his dying-bed,
that she might have an easy passage when she came to such a time as he was in; "`for,`"
said she, "`I am very easy;`" and often said that she was resigned to the will of God.

A little before her death,
much through her husband`'s great affection to her and his earnest desire of her life,
she seemed a little to desire life, but presently checked herself for it,
and returned to her former resignation of spirit;
and so lay supplicating and praising God, so that a neighbor present,
not called a Quaker, said that she never saw any lie so sweetly in all her life.
Seeing some about her weep, she said, "`Do not cry for me, for I am going to my rest.`"
A friend said, "`Are you willing to leave your husband?`"
She answered, "`I have often told him I am willing to go when the Lord pleases:`"
and in a little time after she said, "`In a few days, in a few days, they will say,
Sarah Padley is dead.`"
It much affected those about her to see how reconciled she was to death,
speaking very pleasantly concerning it,
and of the felicity that would accrue to her thereby.
She finished her course on the 8th day of the Sixth month, in the year 1699,
aged about thirty-four years.
