== Chapter 3

[.chapter-synopsis]
* William Turner
* Francis Blaikling
* Hayes Hamilton
* Thomas Vokins
* Richard Vokins
* Elizabeth Wills
* Richard Pike
* Thomas Thompson
* Hugh Stamper
* Reuben Satterthwaite
* Joshua Bunion
* Peter Fletcher
* Abraham Fuller
* Robert Barclay

WILLIAM TURNER, of Hitchin, in Hertfordshire,
was one who sought after truth and righteousness from his childhood,
and when but a youth complained to a professor that
he much desired an inward acquaintance with the Lord,
and to be acquainted with the spirit of God, was what his soul longed for.
The professor advised him to be acquainted with the Scriptures, which he had done before,
and could not be satisfied with the reading of what
God did for his people in former ages,
without feeling after God and knowing him for himself.
And it pleased the Lord in the riches of his love to answer the desires of his soul,
and to open the way of life, and to manifest the truth,
as believed by the people called Quakers.
He was convinced thereof, when he was about twenty years of age,
by the ministry of Thomas Green, and having attained to that which his soul longed for,
namely, the true knowledge of God,
he presently became obedient to the good spirit of God,
and suffered both spoiling of his goods and imprisonment for the truth`'s sake;
his love to which he manifested by bearing a faithful testimony to the same.
He was a man of a blameless life and godly conduct,
having regard to the honor of truth in all things,
seeking the advancement thereof over and above his own temporal interest.
He was a hearty lover of the friends of truth,
and especially of the faithful publishers of the gospel,
whom his heart and house were always open to receive.
He was a lover of peace and unity in the church,
and steady in his testimony against looseness and undue liberty,
and those who opposed gospel order.
He was indeed a pillar in the church, and a careful overseer in the flock,
whom sometimes he was concerned to exhort in a brief testimony;
which being delivered in much tenderness and brokenness of spirit,
was of service and comfort to the faithful people of God.

He was much afflicted with pain and weakness of body a considerable time before he died,
but bore it with much patience.
His wife cannot remember that she ever heard one unadvised
word proceed out of his mouth all the time of his illness;
and he would say, that his affliction was not laid upon him in anger,
but whom the Lord loved, he chastises.
When his wife bewailed the loss she should have of him, he said,
"`It will be better for me to go from here, for I shall be at rest and peace,
where there shall be no more trouble.`"
About three days before his death, he called for his children and said,
"`What I have to say, I shall speak in a few words, but remember them when I am gone.
Mind truth above all, and then God will bless you! and be kind to your mother,
and do nothing without her advice;
and do not marry to any but them that love truth well.`"
He charged his children to be none of them that strive to stay at home,
but strive who shall go to meeting.
A little before he died, he said,
"`I find nothing but that it will be well with me to all eternity.`"
To his eldest daughter Elizabeth, wife of John Pryor, he said,
"`Be an upright-hearted woman, and walk uprightly before the Lord.`"
He departed this life the 6th of the First month, 1704,
in the sixty-first year of his age, after he had believed in truth forty-one years.
His body was decently buried in Friends`' burying-ground at Hitchin.

[.asterism]
'''

FRANCIS BLAIKLING, of Winder, near Sedbergh, in Yorkshire,
was a harmless man from his youth, born of good sober parentage.
He was convinced of the blessed truth about the time
of George Fox`'s first coming to publish truth,
which was in the year 1652.
He gladly received the truth in the love of it, and faithfully walked in it,
and cheerfully suffered for it, not only extreme spoiling his goods,
but by a pretty long imprisonment in York castle.
The Lord not only gave him to believe and to suffer,
but also gave him a part of the ministry, to testify unto the blessed truth,
which he had believed in, and to that word of reconciliation, near in the heart.
In work, according to his measure, he was a faithful laborer,
though he did not travel far abroad; neither was his testimony long,
but it was very easy and comfortable to the faithful; and he, in a plain testimony,
hit the mark, both in reproof to the wicked and the comfort of true mourners in Zion.
He was a man well beloved, and esteemed both by Friends and others; wherefore,
in the time of his sickness, many came to visit him,
who found him in a comfortable frame of spirit;
he patiently enduring those bodily infirmities which he was under,
and much resigned in his mind to God`'s will, whether for life or death, often saying,
the Lord was, and always had been, very good and favorable to him,
and he found nothing but peace to his soul from the Lord,
and he was ready to leave this world whenever the Lord pleased to call him out of it.

Thus in much patience and cheerfulness his spirit was borne up in his sickness,
increasing in sweetness of spirit, and in expressions which are not written down,
being not perfectly remembered.
As he lived in love and unity with his brethren, so he died,
saying to many friends who came to visit him, "`Dear friend,
my love and life is with you.`"

He departed this life the 20th of the First month, 1704, aged seventy-three years,
a believer in truth fifty-two years.

[.asterism]
'''

[.blurb]
=== An Account of some remarkable words spoken by HAYES HAMILTON, son of Hugh Hamilton, of Ireland, a little before his death. Aged twelve years.

He said he had been several times in a place by himself,
where he wished he had been forever,
he enjoyed so much of the comfortable presence of the Lord in silent waiting upon him,
and meditating in his law, which drew his soul in a rapture.
He also told his schoolmaster, about twelve days before he died,
the day he left the school (as the said schoolmaster did testify),
that his said master should see him go no more that way,
until he saw him carried to his burial.
His master asked the reason for his saying so.
He said he knew that he had taken the small-pox, and that he should die of that disease,
which accordingly came to pass about twelve days following.

He hearing his mother reading the first of Cor.
15:50, where the apostle Paul says,
"`Flesh and blood cannot inherit the kingdom of God,`"
he asked his father what he thought of that saying;
the father turned that question to his son, and asked his opinion of it; he replied,
as God was a spirit, that which was for his use, he would make it spiritual,
and therefore no longer flesh and blood.

When troubled with several questions about baptism,
he said he could prove from Eph. 4:5, that there was one Lord, one faith,
and one baptism; and he said, "`them that will be satisfied with that of water,
let them hold it; for my part, I depend nothing upon it.
I depend only upon the baptism of the spirit,
and I doubt there are many that talk most about baptism, know very little what it is.`"

He was taken sick, and about a quarter of an hour before he died he sat up in his bed,
his mother and sisters by him, and he asked what day of the week it was.
She told him, and he asked the hour of the day, the which she told; then he said,
"`Heaven is not far from me;`" his aunt asked him if
he was willing to leave his father and mother,
and all the world, to go to heaven; he said, "`Yes, I am;`" and further said,
"`It is a sweet change.`"
She desired the Lord to prepare him, and clear the way for him; he looking in her face,
said, "`I know the way, and who has cleared it.`"
And so died in peace, the 7th of the Third month, 1697,
in the twelfth year and seventh month of his age.

[.asterism]
'''

[.blurb]
=== The dying words of THOMAS VOKINS, son of Richard and Joan Vokins, of West Charlow, in the county of Berks.

The day before his departure he prayed thus: "`Oh! blessed God,
if it be your will to take me this night, make my passage easy; not my will be done;
your will be done.
Oh, Lord! you delivered Jacob out of all his troubles.`"

Another time he said, "`There is a good spirit as well as a bad spirit;
and if the good spirit be taken heed unto, it will be felt as strong to lead into good,
as the bad spirit is to lead into wickedness.`"
Not one hour before he died, his mother and others being present, he said, "`Mother,
the Lord is exceedingly good to me,
and has been all along the eight or nine weeks of my exercises,
and when I could hardly speak, his sweet presence has been with me,
and his life has sweetly refreshed me.`"

As his mother sat by him, she felt the power of the Lord,
and spoke to Friends in the chamber to be still,
and this innocent young man died like a lamb, without sigh or groan,
and those present felt the power of the Lord with him at his departure,
and were greatly refreshed; much was spoken by him of the goodness of the Lord,
but his voice being low, it could not well be heard.
He died the 23rd of the Second month, 1683.

[.asterism]
'''

RICHARD VOKINS, brother to the aforesaid Thomas Vokins, in the time of his sickness,
kept feeding in retirement within,
and when he first took his bed he examined himself before the Lord thus; saying, "`Lord,
have I done any thing to offend you, have I wronged any man?`"
and desiring the Lord would take off all reproach from his people.
During his sickness he was preserved in a quiet frame of mind,
no impatient words coming from him;
expressing how the Lord had preserved him in true simplicity,
which was his great comfort, and gave good advice to several who came to see him;
saying to them; "`It is well with me, you cannot think what I enjoy.`"
In the time of his health, he was a humble, tender-hearted man,
considerate of his servants and poor people that worked for him;
often saying that he would not enrich himself out of their labors;
and was glad when he could do good to any.
One time he called for his two children, and prayed the Lord to bless them;
his wife asked him, if it did not seem hard to part with them; to which he replied, "`No,
all is well, there is nothing troubles me,
all is well;`" desiring his dear children might take him for an example,
and live no worse a life than he had done.

After this, his wife said,
"`The Lord is able to raise you again if it be His will;`" he replied, "`I know he is able,
but he does not intend to restore me again;`" and
he told his doctor he could do him no good.
In the time of his sickness,
the impropriator and servants cleared his orchard of apples to the value of £4,
for tithes.
His wife asked if those people plundering them did not trouble him, he replied, "`No,
not at all, the Lord forgive them, they know not what they do.`"
When his wife perceived his speech to alter,
she again asked him if he was willing to leave the world; he replied, "`Yes,
very willing;`" soon after, his speech went quite away, and next day he died in peace,
being the 12th of the Eighth month, 1696.

[.asterism]
'''

ELIZABETH WILLS, daughter of Daniel and Mary Wills, of Northampton River, in West Jersey,
in America, was on the 2nd of Eighth month, 1687, visited with an ague and fever,
which continuing some days hard upon her, she often called upon the Lord, saying,
"`The Lord help me,
the Lord ease me;`" patiently begging of God for help in her great exercise,
and her cries were felt to proceed from the stirrings of life.
About the tenth hour of the sixth day of her sickness, her extremity being great,
she desired to be remembered to her mother,
who at that time was very ill in another chamber, and her mother understanding it,
she came to her, which much satisfied the child.
Turning to her mother, she embraced her, and said, "`O mother,
I will lie with you;`" and when she had manifested
her kindness and tender love to her mother,
for a little time lay still; there being her father and sister in the room,
she raised herself upright without help, and said,
"`Now I am well;`" giving living praises and thanksgiving to God, saying,
"`Lord God of power and glory; all power, glory and honor be given to you forever, Amen;
for you have helped me, you glorious God of life.
You have eased my heart, O you powerful God of glory; praises, and glory, and honor,
be given to you forever, Amen.
O you God of eternal glory! what shall I say unto you?
all praises be given unto your name, you glorious God of life, you have helped my soul;
praises forever be given unto you, forever, and forever.
Amen.`"
Often saying in this way, "`What I speak,
God gives me to speak;`" and then speaking much more to the same effect,
all tending to the praise and glory of God,
and to the extolling of his great and wonderful name; often saying, "`God is good,
God has touched my heart.`"

Thus she remained praising and giving thanks to God for the space of an hour,
and it grew towards midnight.
Then she desired her two brothers, and her younger sister should be called,
who were in their beds, and when they came, she looked upon them,
but still remained praising and glorifying God, often saying, "`Now I am well,
I feel no pain.
I am willing to live; I am willing to die.
I am willing to leave the world, or I am willing to stay in the world;`" often saying,
"`I am content to live or to die;`" which expressions
greatly tendered the hearts of all present.
She again spoke much, praising and magnifying the great name of God,
to the same effect as before; several times saying, "`What I speak,
God gives me to speak;`" also saying,
"`I did not know God would have given me so much to speak,
for I was never sensible of these things before.`"
Then she took her father by the hand, and kissed him, saying, "`Farewell,
my dear father;`" and then took her mother by the hand, and kissed her, saying, "`Farewell,
my dear mother;`" and then her brothers, taking each of them by the hand,
and kissing them, saying, "`Farewell, my dear brothers;`" and lastly,
took her sisters by the hand, and kissed them, saying, "`Farewell, my dear sisters.`"
Her father hearing her use that expression to every one of them,
he called her by her name, saying, "`Where is that farewell you speak of?`"
she looked upon her father, and readily answered, saying, "`It is in my heart.`"

Her speech was so affecting, that it exceedingly tendered the hearts,
and caused tears to run much from the eyes, of all present; which she beholding,
as one without all sense of sorrow, looked upon her father, saying, "`Father,
you are troubled;`" he answered, no, he was not troubled, but glad;
saying it was more to him to behold her in that condition, than life, or length of days.
Then she said, "`I am well pleased.`"
She beholding her mother weeping, said, "`My mother is troubled;`" her mother answered,
saying, she was not troubled, but desired her to be content in the will of God.
Then she said, "`I am content.`"
She caused her brothers and sisters to speak their minds one by one,
of their satisfaction concerning her condition, which was done by them.
She hearing their sayings, was well satisfied; she often said,
as she was parting with them, "`God has eased me of my pain.`"
And after a little time she talked familiarly with them, as one that ailed nothing;
and in her discourse, spoke in this manner, saying,
"`James Martin (who was a minister of the gospel) is a good man; I would I could see him,
but he is gone to England; I shall see him no more; and John is a good man;`" her father,
standing by, asked her what John; and she said, "`that John who had a meeting in the barn,`"
(which was John Hayton); likewise she said, "`I shall see him no more.`"
She also said, "`Thomas Olive is a good man, and I shall see him tomorrow,`"
which accordingly she did.
When James Martin went away, she said, "`I am sure I cried;`" and said again,
"`Would I could see him.`"
Her father desired her to be satisfied, saying,
"`God has given you a share of that same life which
James has;`" so she mentioned him no more,
but something further of the goodness of God to her, and spoke of one Sarah Kem,
saying she was a good child, she died well.

She lay still, and after a little time her sense of pain came again,
and then she called upon the Lord, saying, "`The Lord help me,
the Lord ease me;`" and as it increased, the more earnestly she called upon the Lord,
saying, "`O Lord, how shall I ascend to you, that you may hear me?`"
And in time the Lord gave her some ease, and she took some rest; and the ninth day,
being the first day of the week, Friends coming to the meeting,
several came to see her before the meeting, unto whom she put forth her hand,
and tenderly asked several of them how they did;
but after meeting she seemed to be somewhat more weakened, and not so quick of memory,
but took her leave of several friends, as they came to her.

That day she several times inquired for a servant boy, who she knew to be negligent,
and often would lie out all night, and at the same time was gone,
and that night late he came again.
She desired to speak with him, so soon as she heard he was come.
When he came to her, she turned herself, and steadfastly looked upon him,
as one renewed with sense and strength, saying, "`God gave me much to speak last night,
and you were not here.
It is better for you that you should walk with God.
You must die as well as I; you must go to the grave as well as I;
and if you do not do better you shall have torment, and I shall have peace.
It would be better for you that you would walk with God, but time is past and gone,
and cannot be recalled.`"
Saying to him, "`Is it not better for you to do well than ill?`"
Her father standing by, asked her what she would have him to do then, if time were past.
She answered, she would have him do well, but she believed he would not;
she then said he might go away; and some time after called to him again, saying,
she would not have him forget what she had said to him.

On the 11th of the Eighth month, 1687, she departed this life,
having laid down her head in peace and rest with the Lord.

[.asterism]
'''

RICHARD PIKE, late of Cork, in Ireland, was born at Newbury, in England,
in or about the year 1627, and came from Ireland, belonging to the horse in the army,
which were sent from England, for the reduction of that nation,
upon the rebellion of the natives.
While he was in the army he had the character of a very sober, conscientious man,
but of great courage, for which he was much esteemed by his superior officers.
In those days he was accounted religiously inclined, and one who sought the Lord,
and the Lord was pleased to be found of him, and revealed his truth to him.
In or about the year 1655, the Lord sent some of his faithful ministers, called Quakers,
to that nation to preach the everlasting gospel,
by whom he was convinced of the way of life and salvation,
to which he became truly obedient,
and soon denied the use of carnal weapons for the destruction of mankind;
and in other things taking up the cross of Christ, despising the shame,
and for truth`'s sake became a great sufferer, by patiently enduring reproaches,
abuses and imprisonments, as well as loss of outward substance.
As he was a faithful follower of the Lord Jesus,
so he was greatly beloved by all faithful friends who knew him; and his deportment,
conduct and commerce among the world, were such as adorned the blessed truth,
being a very upright and just, as well as a very inoffensive man;
insomuch that his greatest persecutors have been heard to say,
if there were any good or honest men among the Quakers, he was one.

In the year 1668 he was, with several friends more, cast into prison by one Rye,
then mayor of Cork, for meeting together to worship God;
in which place he got a violent cold, which ended in a flux, that brought him very low,
the prison being thronged, and without convenience at that time for the sick.
The jailor indulged him for a little time to be a prisoner in his own house.
After his coming home, the distemper increasing upon him,
brought him exceedingly weak and low; though in much pain, yet very patient under it,
and much retired to the Lord, and in a sweet frame of spirit.
The Fifth-day before he died came that worthy mother in Israel, Susannah Mitchel,
to visit him; who, sitting in silent waiting upon the Lord by his bedside,
was moved to pray, which she did with great fervency of spirit.
At which time also the power of the Lord fell upon him in a wonderful manner,
greatly melting and tendering his spirit,
causing him to give forth several sweet and heavenly expressions;
and though he was exceedingly weak in body,
and neither able nor fit to rise out of bed before,
yet the presence and power of the Lord so strengthened him,
that he immediately rose out of his bed, as one that ailed little,
and put on his clothes, in order to go to the prison,
to see and meet his dear companions and fellow-sufferers.
His wife and friends present, seeing this great and sudden alteration;
were in great hopes the Lord would restore him to his health again.

He went abroad to prison, as one that was not sick,
and had a good meeting with Friends there;
the jailor gave him leave in the evening to return home again, which he did,
with little appearance of illness; but soon after his return,
as one that was only raised from his deathbed to
give his last visit to his beloved friends,
his distemper returned again, and he grew exceedingly ill that night,
and so continued growing worse till about the Third-day, in the evening,
at which time he was so bad that it was concluded he was dying.
In his weak conditions the power of the Lord came
upon him again in an extraordinary manner,
so that he was revived, and as one that had new life and strength given him,
and he spoke of the wonderful love of God to his soul, and the preciousness of truth,
with seasonable exhortation to all that were about him.
Thus he continued with the Lord`'s power upon him until the Fifth-day, whereon he died;
having a spirit of discerning given him from the Lord,
by which he saw and spoke directly to the inward states
and conditions of most or all that came to visit him,
giving counsel and advice accordingly, and in particular to some who had been unfaithful.
He spoke so home to their states, that they were almost amazed,
warning them to prize their time, and be more faithful for the time to come.

He also called those of his children who were come to some years of understanding,
in particular Joseph, Elizabeth, and Ebenezer Pike,
and gave them heavenly advice and counsel; and among the rest,
he spoke to them to this purpose: "`Fear the Lord, and be faithful to him,
and be obedient to your mother, and then the Lord will be a father to you,
and provide for and bless you, and the rest of you every day,
and let the blessing of your dying father rest upon
you;`" with more that cannot now be remembered.
It would require a volume to contain the many blessed and heavenly sayings and exhortations,
if they could be remembered, which came from him in the time of his sickness,
especially the last two days of his life, some of which were taken from his mouth,
and committed to writing by a friend present, and read at his burial;
which paper is through some neglect mislaid or lost.

He quietly departed this life, and died in the Lord, the Fourth month, 1668,
being about forty-one years of age.

[.asterism]
'''

THOMAS THOMPSON, of Skipsea,
was convinced of the truth of God by that ancient
and faithful minister of the gospel of Christ,
William Dewsbury, in the Eighth month of the year 1652,
and shortly after had his mouth opened to declare the name of the Lord,
and preach repentance to the people.
He was preserved in faithfulness to the truth to the end of his days,
not turning his back from sufferings, but patiently endured reproach for Christ`'s sake,
and spoiling of goods, with many years`' imprisonment.
When it pleased the Lord to visit him with the illness whereof he died,
which began on the 26th day of the Sixth month, 1704,
his heart was filled with the love of God,
and he was enabled through the goodness of God, though very weak in body,
to go to several meetings, in which the Lord`'s heavenly power did livingly attend him.
On the sixth day of the Seventh month, he was at the monthly meeting held at Harpham,
being the last public meeting he was at,
where he bore a plain and powerful testimony to the ancient truth,
laboring to encourage all Friends to be faithful to God,
and to be diligent in the service of truth, according to their several abilities, gifts,
and endowments,
that so an increase of the peaceable government of Christ might be witnessed,
both in the particular and also in the general.

He was indeed a laborious man in the work of the gospel,
having travelled in truth`'s service several times through Scotland,
and in many places in this nation; and, as he said when upon a dying-bed,
for many years had not omitted any opportunity of being serviceable.
His testimony was plain, but powerful; sound and convincing,
and severe against wickedness;
but to the young and tender-hearted he was very loving and affectionate,
even as a nurse that cherishes her children.
On the tenth day of the month, in the year aforesaid, being the First day of the week,
several Friends visited him in his chamber, he being then very weak,
to whom he declared the lovingkindness of God, and of his tender dealings with his soul,
from his youth to that day; and that he felt the Lord,
who had been the guide of his youth, to be the staff of his old age;
and exhorted Friends to faithfulness and confidence in God,
that they should depend upon the arm of his power and providence forever.

On the 13th day of the month, several Friends being with him,
he said that he was content to live or die, as the Lord pleased, in whom he had peace;
and that he was in no doubt concerning his salvation, but was satisfied forever,
and could say with Job, the Lord had granted him life and favor,
and his visitations still preserved his spirit.
The next day, being the 14th, and the day of his departure out of this world,
he spoke little in the forenoon, being under much bodily weakness and pain at times;
but about the second or third hour in the afternoon, in a heavenly, melting manner,
he said, "`The Lord is my portion, and the lot of my inheritance forever.
I am not dismayed;`" and after a little time,
"`I have peace with God;`" and after a considerable pause,
"`Since the day that the word of the Lord came unto me, saying, As you are converted,
strengthen your brethren; and if you love me, feed my lambs; I have spared no pains,
either in body or spirit,
neither am I conscious to myself of slipping any
opportunity of being serviceable to truth and Friends;
but have gone through what was before me with all willingness possible.
And now I feel the love of God,
and the returns of peace in my bosom;`" which words were
spoken in so living a sense of God`'s heavenly power,
that it wonderfully broke and tendered Friends present.

Another time he said, "`The Lord Jesus Christ has shed his precious blood for us,
and laid down his life, and became sin for us,
that we might be made the righteous of God in him.
O, this is love indeed.`"
Again he said, "`My heart is filled with the love of God.
Oh the excellency! oh the glory! oh how glorious and excellent
is the appearance of God! the rays of his glory fill his tabernacle:`"
and so he sung melodiously, saying, "`O praises, praises, high praises,
and hallelujah to the King of Zion, who reigns gloriously this day.`"
All which being spoken in a heavenly sense of the aboundings
of the sweet life of the divine and living Word,
which was with the Father in the beginning,
mightily overcame and melted the spirits of Friends.
To a neighbor who came in to see him, he said, "`We must put off these mortal bodies;
but for them that fear the Lord there is an immortal one prepared.`"
He continued very cheerful and sensible to the last,
and spoke very cheerfully to several neighbors who came to see him.
About three quarters of an hour before his death,
he spoke to one that had been under convincement several years,
but had not been faithful,
exhorting him to repent and be faithful to what God had manifested to him,
that so he might find mercy; with many more words not remembered,
telling him that he would find it a terrible thing to appear before an angry God.
He said that he spoke to him in love, and would have him take it so;
and bade him remember the words of a dying man, and so bade him farewell.

Another time he said to friends, "`You are my witnesses,
that I have not withheld from you the counsel and mind of God,
and have labored to provoke you to faithfulness and diligence in his service,
that so you might receive a crown of glory at the hand of the Lord,
which is laid up in store for all the righteous,
and my conscience is clear in God`'s sight.`"
Being filled with the living power and love of God,
he often praised his holy and glorious name;
and about the seventh hour he passed away like a lamb, into his Father`'s bosom,
without so much as either sigh or groan, and is at rest in the Lord forevermore.

He departed this life in the seventy-third year of his age,
the 14th of the Seventh month, 1704.
A laborer in the gospel about fifty years.

[.asterism]
'''

[.blurb]
=== The testimony of HUGH STAMPER, of Lurgan, in Ireland, near his departure out of this life.

[.offset]
About twenty friends being present, he said:

[.embedded-content-document.testimony]
--

I die in the same faith that I have made profession of, and lived in,
and suffered for these twenty-three years, and I am as willing to die as to live.
All the desire I have to live, is to see truth prosper, and if sufferings come,
I am willing to suffer for it.
There is no weight or burden lies at my door.
I have wronged no man, neither have I been burdensome to any,
but always if there was any difference, I suffered wrong for peace-sake.
I have not oppressed any man.
So, my dear friends, beware of oppression, walk in love one to another,
passing by infirmities, forgiving one another, for even as Christ said,
if you forgive not one another, how shall your heavenly Father forgive you?
Even as he who would not forgive his brother, missed of pardon.
Keep your hearts clean, and let no rottenness remain therein.
Keep the heart void of offense towards God and man, and when any evil does appear,
judge it down with the light, and be not peevish, nor fretting;
it hinders the springs of life.
Walk humbly before your God, and be of a pure mind to him,
Walk in true love one towards another, and stand not at a distance one from another,
for envy and strife lead from God, and eat as a canker,
so miss of the blessing which is poured down upon the righteous,
as showers of latter rain.
Blessed be the Lord God forever.
Bear up your heads, and give not away your crowns for any visible thing here below,
for they are but trifles, and things of no value.
Dear friends, keep your crowns sure, and then you need not care what scoffers, mockers,
liars, backbiters, and drunkards say, for their way leads to hell,
and they cannot inherit the kingdom of heaven.

Dear friends, in the suffering of all things, you shall come to wear the crown.
No cross, no crown; take notice of that.
Friends, keep your crown, that your bow may abide in full strength in the needful time,
when the pains of death come upon you, which will come upon all in due time.
Death troubles me not, for blessed be the Lord forever,
the enemy dared never so much as once set up his head, either to twist or twine;
since I lay on this my bed of sickness, there is nothing but peace on every side.

My dear friends, I desire you in the bowels of tender love to love one another,
and you will be a comely people, and an honor to God and one to another.
Bear the daily cross, that you may be crowned when time shall be no more,
and come to partake of the mercies of David, namely,
an everlasting covenant which has no end.
If the righteous scarcely be saved, where shall the wicked and ungodly appear?
Oh! the joy and endless felicity that shall be upon the righteous,
and what horror and misery shall be upon the wicked!

And, dear friends, let not a bare profession serve your turn,
for it will not stand you in any stead in such a needful time as this,
but walk answerably to what you profess, that your bow may stand in full strength,
as mine does at this time.
Blessed be the name of the Lord forever, I have no more lying upon me that I know of,
to hinder my journey, than a child.
So, my dear friends, do not will and run in your own wills, but wait daily upon the Lord,
and let your whole dependence be upon him, that you may come in at the right door,
for whosoever climbs up another way is a thief and a robber.
Cast your care upon the Lord, and he will in no way cast you off,
but he will work in you, and for you, and you will become the children of the day,
and of the light.
I do not speak these things to exalt myself, for there is no exalting in the grave,
but I must bear my testimony for God, and for his truth.
Friends, you know these things before;
this is to stir up your minds to stand steadfast in the truth,
and let not your crown be taken from you.
Be faithful in the day of small things, and despise them not,
and the Lord will make you rulers over much, so shall you be honorable men and women,
and he will shower down multitudes of blessings upon your heads.

O friends, I desire you again not to slight this glorious day, which is now dawned,
for it can be called no less than salvation upon earth,
but walk faithfully to the receiving of your crown,
and you will return with sheaves in your bosoms.

--

Thus often exhorting Friends to faithfulness, and to be of an honest heart,
and to keep nothing there but that which is of a right nature, saying,
"`Take notice of my words, for they are the words of a dying man,
and they are very weighty; and if you will not hear,
you shall be made to remember hereafter when I am gone.`"

When the time of his departure came near, he said, "`Come Lord Jesus,
come when it is your blessed will, for I am ready for you.`"
Just before he died he sat up in his bed and spoke these words, "`Now, Lord Jesus,
receive my soul into your everlasting kingdom of glory,
for your kingdom is from everlasting to everlasting;`" and
so departed this life about the ninth of the Seventh month,
1676.
Aged about sixty-five years.

[.asterism]
'''

REUBEN SATTERTHWAITE, born at Skinerhow, in the parish of Hawkshead,
in the county of Lancaster, came of believing parents,
who used a godly care in educating him in the way
of truth as professed by the people called Quakers.
This young man had a care over his own words and actions, that they might become truth,
and he received a gift of the ministry about the twenty-third year of his age,
wherein he did much improve himself until the twenty-sixth year of his age,
wherein he died; in which time he faithfully labored in the gospel.
He travelled into Scotland in company with his friend George Knipe,
who was a nursing father to him,
and they visited every meeting of Friends in that nation.
Being clear of that nation, he came back through Northumberland bishopric,
and the east parts of Yorkshire, and so home: and in the Second month of the year 1694,
he with his said friend set forward for London, and was at the yearly meeting there,
and afterwards visited Friends in the west of England,
even to the Land`'s-end in Cornwall, and so back by Bristol.
In this journey he had very good success,
and was much enlarged in his gift of the ministry;
and from Bristol travelled through Wales to Lancashire home again.
He travelled into Derbyshire, Nottingham and Lincolnshire; and in the Third month, 1696,
again into Scotland with his former friend, George Knipe,
and returned from there through Cumberland, which was the last journey he had,
for he was removed out of this troublesome world the same year.

He was a good example and pattern in righteousness and holiness,
and was valiant for the truth upon earth, and was of a sound mind,
and preached sound doctrine, and often opened the Holy Scriptures,
to the edification of the hearers.
When he was visited with sickness, he bore it patiently, and in the first part,
he got up and walked about the house, but feeling himself weak in body, he said,
"`I am a poor mortal, a worm, and dust and ashes.`"
Though his body was weakened and decayed, yet he was strengthened inwardly,
and often spoke of the kind dealings of the Lord with him,
and how mercifully he had helped him in his travels.
His sickness increasing he kept his bed, and many came to visit him;
to whose conditions he spoke, to the admiration of those about him.
Not long before he died, his sister-in-law being present, he said, "`Oh!
Lord, you know I have passed through many exercises for your name`'s sake,
and you have rewarded me well for the same, for which I praise your holy name.
The Lord God is my staff, as he was to David, who said his staff did comfort him.`"

Some young friends visiting him, he said,
"`I desire you to wait upon the Lord all your days, for the promise of the Lord is to you,
if you will wait upon him,
and love him to the end;`" with more expressions that could not be remembered.
He passed that night in a very good frame of spirit, breathing to the Lord.
On the morrow, being the First-day of the week, several young people came in,
to whose conditions he spoke distinctly,
exhorting them to remember their Creator in the days of their youth.
He was very weak in body, but his words did so affect them,
that they were tendered and broken into tears,
and several Friends present were much comforted thereby.
That night, Margaret his sister, and another Friend sitting up with him,
he taking his sister by the hand, said, "`Dear sister,
tell my father and mother that I must go, I must go home.`"
After some sight which he had, which brought some exercise upon him,
he broke forth into an inward rejoicing of spirit;
and after that he expressed the travail that was upon his mind
for some Friends and meetings in parts which he had visited,
and prayed to the Lord to be gracious and merciful to them,
and spoke many more seasonable words that are not here mentioned.
That same night he departed this life, being the 12th of the Eleventh month, 1696.

[.asterism]
'''

JOSHUA BUNION, who lived near Ipswich in Suffolk in England,
went over to preach the gospel in Ireland in the year 1696.
He was remarkable for his extraordinary innocency in his conduct,
chiefly minding the discharge of his duty, with respect to his ministry,
which was edifying.
He was taken sick going from Dublin to the north of Ireland,
and coming to Ballyhagan in the county of Armagh,
was so weak that he could scarcely alight off his horse without help,
yet his zeal was such that he bore a faithful testimony
for truth in the public meeting the same day.
Afterwards he went to bed, continuing very ill about two weeks.
In the time of his sickness he was very fervent in prayer, and the day before he died,
sitting in a chair, desired another to be set before him, on which he leaned,
and prayed fervently and powerfully to the Lord.
The next day he departed this life, the 23rd of the Fourth month, 1696.
Aged about forty years.
He was buried in Friends`' burying-place, near Ballyhagan aforesaid.

[.asterism]
'''

PETER FLETCHER was born near Pardsay, in Cumberland, in England,
and educated in the profession of truth.
He came over to be an apprentice in Dublin;
and after he had served his apprenticeship he settled in the said city;
he was of good conduct, both in respect to his Christian duty towards God,
in duly attending meetings for the worship of God, and other religious performances,
and ready and cheerful in doing those offices of love which we owe one unto another.
About three years before his death the Lord was pleased to call him into the ministry;
in which he was sound and deliberate in his delivery,
being careful to minister from that ability which God had given him.
He was under weakness of body some months before his death,
in which time he spoke of the Lord`'s dealings with him,
and how he inclined his heart to seek him when he was young,
and had kept him all along to that day,
in a sense of his goodness and power which had preserved him.
He was freely given up to the Lord`'s disposing,
and rather willing to leave the world than stay any longer therein,
if it were the Lord`'s will;
and further said he found nothing but sweet peace to abound in his heart from the Lord;
and so being prepared for his latter end, he departed this life in Dublin,
the 29th of the Fourth month, 1698.
Aged about thirty years.

[.asterism]
'''

ABRAHAM FULLER was convinced of the truth in or about the year 1660,
being about the forty-first year of his age.
He lived most of his time after his convincement at Lyhensa in King`'s county;
he feared the Lord,
and was a serviceable man on several accounts in the church of Christ,
and bore a testimony for the truth, and was a free and open-hearted man to his friends,
distributing of his substance unto those that were in necessity.
He was taken sick about the beginning of the Eighth month, 1694, of an ague and cholic.

In the time of his sickness he expressed his concern for the prosperity of truth,
and sent to speak with some that made profession of it,
and did not walk answerably thereto, and did admonish them to repent,
and amend their lives.
He was often in his illness in supplication to the Lord,
and in returning praises to him for his mercies which he had received from him.
About the 4th day of the Ninth month, most of his children being about him,
and sitting awhile in silence, he then prayed the Lord that he would bless his children,
and preserve them from the evils that were in the world.

One day having a pretty sharp fit of the ague upon him,
his daughter-in-law who attended him said, "`Father,
the fit you had yesterday went away easily;`" he replied, "`Yes,
the Lord`'s power took the pain away.`"
He gave his children good counsel and admonition,
according as he had a sense of their states.
He often in the time of his illness expressed how good the Lord was to him.
Six days before his death, being gone to his bed at night,
he desired to speak with his children that were in the house,
there being two of his sons and his son`'s wife.
After they had sat a little time silent by his bedside,
he said he had a desire to let them know,
that if the Lord had no further service for him to do, he was willing to die;
and then spoke to one of his sons, giving him good advice;
and then called to his other son by name, and said,
"`The Lord make you a sanctified vessel fit for his use.`"

His eldest son, living nearly a mile off, being newly recovered from a fit of sickness,
came to see his father, and when he was about to take leave of him,
which was but about two hours before his death, he spoke to him,
admonishing him to take care of his soul, for it was of great value.
He desired several times in his sickness,
if it were the Lord`'s will that he might be sensible at his departure,
and have an easy passage.
His desire was answered, for in less than a quarter of an hour before his death,
he laid his hand on the bedside, and turned himself,
and desired to be a little raised in his bed; and so departed quietly,
and finished his course about the twelfth hour at night, on the 4th of the Tenth month,
at his son Isaac`'s house at Lismina, and was buried at Friends`' burial-place,
at the Moat a Green.

[.asterism]
'''

ROBERT BARCLAY, of Urie, in Scotland.
This worthy man of God, whose character is written,
as well for their example and encouragement who have
or hereafter may receive the eternal truth,
in which he lived and died, and lives forever,
as for a testimony to the power and goodness of God, in raising him up to his church,
and to his lasting memorial in the churches of Christ, which is blessed forever.
The said Robert Barclay was the son of Colonel David Barclay,
descended of the Barclays of Mathers, in the kingdom of Scotland,
an ancient and honorable family among men, and Katherine Gordon,
from the Gordons of the house of the duke of Gordon.
He was born at Edinburgh, in 1648, educated in France,
and had the advantage of that tongue as well as the Latin.

He returned to Scotland about 1664, being sixteen years of age, where,
by the example and instruction of his honest and worthy father,
who in his absence had received the everlasting truth,
and his conversation was with other servants of God,
he came to see and taste an excellency in it,
and was convinced thereof about the year 1667.
He publicly owned the testimony of the true light, enlightening every man,
and came early forth a zealous and fervent witness for it, enduring the cross,
and despising the shame that attended his discipleship,
and received the gift of the ministry as his greatest honor,
in which he labored to bring others to God, and his labor was not in vain in the Lord.
He was much exercised in controversy, from the many contradictions that fell upon truth,
and upon him for its sake, in his own country chiefly,
in which he ever acquitted himself with honor to the truth,
particularly by his Apology for the Christian divinity
professed by the people called Quakers,
which contains a collection of our principles, our enemies`' objections,
and our answers augmented and illustrated closely and amply,
with many authorities for confirmation.
He wrote several other books which are printed,
and make a volume of nearly two hundred and thirty sheets,
which contain many standing books of sound judgment,
and good service to the truth and church of God.

He travelled often in Scotland and England, and also in Holland and Germany,
to spread the gospel of our Lord Jesus Christ.
He loved the truth, and the way of God, as revealed among the people called Quakers,
above the world, and was not ashamed of it before men,
but bold and able in maintaining it, sound in judgment, strong in argument,
cheerful in travails and sufferings, of a pleasant disposition, yet solid and plain,
and exemplary in his conduct.
He was a learned man, a good Christian, an able minister, a dutiful son,
a loving husband, a tender and careful father, an easy master,
and a good and kind neighbor and friend.
These eminent qualities in one who had employed them so serviceably,
and who had not lived much above half the life of a man,
having outlived his father but four years,
and died at least thirty years short of his age, aggravate the loss of him.

His sickness was short: our friend James Dickinson, of Cumberland,
in his travel into that nation, visiting him when on his deathbed, as he sat by him,
the Lord`'s power and presence bowing their hearts together,
Robert Barclay was sweetly melted in the sense of God`'s love,
and with tears expressed his love to all faithful brethren in England,
who keep their integrity to the truth.
He added, "`Remember my love to Friends in Cumberland, and at Swarthmore,
and to dear George,`" meaning George Fox, "`and to all the faithful everywhere;`" and said,
"`God is good still,
and though I am under great weight of sickness and weakness as to my body,
yet my peace flows; and this I know, whatever exercises may be permitted to come upon me,
it shall tend to God`'s glory, and my salvation, and in that I rest.`"

He died at his own house in Urie, in Scotland, the third day of the Eighth month, 1690,
leaving behind him seven children, four sons and three daughters.

He was born 1648; convinced of truth 1667; wrote his first book for truth 1670;
and his notable [.book-title]#Apology# in and about the 27th year of his age, 1675.
He died in the forty-second year of his age.
