== Chapter 3

[.chapter-synopsis]
* Mary Stout
* Frances Rutt
* John Sager
* Samuel Hunt
* Nicholas Gates
* Mary Moore
* Thomas Camm
* Richard Davies
* Sarah Godfry
* John Peters
* George Newland

MARY STOUT, relict of Henry Stout, of Hartford, was an honest, ancient Friend,
that was early convinced of the blessed truth, and retained her love to it,
and the friends of it, unto death.
Being weak and near her end, she said on her deathbed, the 31st of the First month, 1707,
"`I have nothing to do but to die, if it should be this night.
I have received the earnest of that inheritance that shall never fade away.`"
R+++.+++ T. next day coming to see her, asked her how she did.
She said, "`I am very weak, but very well satisfied to die, if my time be come;
for the Lord is with me, and that is a precious jewel.`"
R+++.+++ T. said, "`So it is, which the world cannot give;`" she said, "`No, nor take away.`"
R+++.+++ T. asking her if she had settled her affairs,
she replied she had nothing to do but to die.

The 6th of the Second month, several Friends being come to visit her, she said,
"`I take your visit very kindly, that I might see you before I die.
I never was thus weak before in my life, yet I have nothing laid to my charge.
The Lord has been with me in my exercise.`"
Then said to G. W., "`And you have been a dear friend to me.`"

On the 7th of the Second month, about the eighth hour in the morning, G. W. went to her,
she then appearing near death, saying to her, "`The Lord make your passage easy,
and give you rest.`"
And near the ninth hour the same morning, she quietly departed without sigh or groan.
Aged about eighty years, and had for some years, at certain times,
used to speak a few weighty and seasonable words in Friends`' meetings.

[.asterism]
'''

FRANCES RUTT, of Hartford, was an ancient, true, and serviceable woman,
to whom the Lord had given a public testimony to bear for the truth,
which she had known and professed for many years, and lived therein,
who was exemplary in her conduct, and a lover of her friends and all people.
When near her end, and Friends stood about her, she said to them,
"`You must not depend upon words, but upon the pure spring of life in your own hearts,
and upon the word of the Lord that endures forever.`"

Thus this faithful woman, who had preached the word,
counseled Friends to depend upon it as that which
is able to quicken and reconcile to God,
sanctify and save the souls of all that are obedient thereto unto death,
as no doubt she experienced it.

She departed this life the 7th of the Third month, 1707.

[.asterism]
'''

JOHN SAGER, of Marsden, in the county of Lancaster, was born the 3rd of the Eighth month,
1627, and convinced of the truth about the beginning of the year 1653,
at a meeting at Brighouse, in Yorkshire, by our dear and ancient friend, George Fox,
of whom he always after retained an honorable esteem.

The said John Sager was constant and zealous in bearing a faithful testimony for truth,
and against tithes,
often exhorting Friends to faithfulness in their testimony against the same.
He often suffered the spoiling of his goods, even in those early days;
the first of which was in the year 1655.
He also suffered imprisonment five times, and often under close confinement,
by reason whereof his tender wife and family went through great hardships.
When with his family, he was a constant attender of week-day meetings,
and meetings for discipline, and very zealously concerned for the promotion thereof,
being a man given up to do and suffer for the truth, of which he had received a measure,
or talent, to improve, and was thereby enabled to bear all his great sufferings,
and other trials, with much patience;
often saying he was made willing by the power of God to give up
his life as a farther seal to the testimony he had borne,
if the Lord did require it.
He often blessed the Lord,
that he had accounted him worthy to suffer for his name`'s sake;
desiring the Lord might forgive his adversaries what they had done against him.

In his latter days, the nearer he drew to his change, which he long waited for,
he was the more raised up in living testimony in meetings,
in exhortation to diligence and faithfulness in the gift received,
and in praising the Lord for his mercies bestowed upon him and his people.
In his last sickness, under the great weakness and distempers,
which then attended his aged body, he was always cheerful and contented,
praising the Lord for his merciful dealings with him.
He was visited by many, both friends and others, and was often raised beyond expectation,
to declare the truth, exhorting all to mind the light of Christ Jesus,
wherewith they were enlightened; often saying all was well with him,
he had nothing to do but to die.

The night before his departure, several Friends coming to visit him, he said,
"`I believe the time of my departure is at hand, and I enjoy great peace and comfort,
and desire the Lord may preserve you, when you come to lie in the condition I do,
and that you may enjoy the same comfort I do now enjoy;`" continuing in fervent prayer.
Next morning, being very sensible to the last, he departed in great peace and quietness,
being the 24th of the Fifth month, 1707.
Aged seventy-nine years and nine months; a minister of Christ.

In the year 1660 he was imprisoned for not swearing,
and remained a prisoner in Lancaster six weeks.
In the year 1668 he was imprisoned again for not swearing,
and was a prisoner at Preston seven weeks.
In the year 1669 he was imprisoned for nonpayment
of tithes at Lancaster four years and six weeks.
In the year 1687 he was a prisoner on the same account at Lancaster one year.
In the year 1691 he was a prisoner again, about tithes at Lancaster,
four years and two months.
So that in all he was a prisoner nearly ten years.

[.asterism]
'''

SAMUEL HUNT, of Nottingham, a minister of Christ, and a faithful servant in his church,
who labored and travelled for the good of souls,
was taken ill at London about the Eighth month, 1707, at the house of Thomas Huttson,
in George-yard, in Lombard-street.
Being apprehensive of his death, he said,
"`I have labored faithfully in the service of the Lord.
I am not afraid to die, for all will be well with me.`"
Soon after he took his bed, he said, "`Dear Lord, you know I love you and your truth,
and have never thought much to spend and be spent for you,
and if my time be come to leave this troublesome world, I am willing.`"

He said to Thomas Huttson and his wife,
"`Our first acquaintance together was in the love of God,
and in that let us live and abide, and in that shall we part one from another.`"

About twelve hours before his departure, several friends were visiting him,
and although he was very weak in body, and his distemper very sharp and strong upon him,
yet he was raised in spirit, and filled with the love of Christ,
insomuch that he uttered many sweet expressions, and precious sayings,
and such a stream of love and life attended him,
that the hearts of all friends there present were melted.
He was heard to say something of the man-made ministers,
but spoke so low it could not be farther understood,
until he was somewhat more strengthened, and his voice raised, then he spoke audibly,
and said, "`Away with this chaffy nature,
it is fit for nothing but to be driven before the wind.
The sound of the instrument is but empty,
except the matter proceed from the pure spring of immortal life.`"
Then being silent, and retired in mind for some time, he broke forth, saying,
"`O sweet composure of mind!
Who is here?
Who is here?
The beloved of my soul, the chiefest of ten thousands!
Dear Lord, I will not let you go!
O your love is sweet and precious!
O that we may live in you, and dwell in you,
you pure ocean and divine fountain of eternal sweetness!
Who can withhold praising you, you living God! oh! we will bless your name.
Praises, honor, and glory, be given to you, through Jesus Christ,
forever and forevermore.`"

When friends were taking leave of him, he said, "`Dear friends, farewell; all is well,
all is well.
If we love one another, and love the Lord, and love his truth, all will be well.`"
When he had taken leave of his wife, and several in the family, and M. H. coming in,
and his wife acquainting him thereof, he said, being sensible to the last, "`Farewell,
dear Mary, farewell in Christ; we have lived in love,
and in love we part;`" these were his last words.
He departed not long after, being the 3rd of the Ninth month, 1707, aged forty-one years.

But before his departure, he dictated the following letter to his son.

[.embedded-content-document.letter]
--

[.salutation]
Son Samuel,

First learn to live in the love and fear of God,
and if you meet with any disappointment,
you may apply yourself to him the more freely for assistance,
it being your father`'s daily practice, in what exercises he has met with in this world.
Be truly honest, both towards God and man;
always laboring in your mind to contradict any thing that may be otherwise.
I recommend this practice: privately to go into your chamber twice a day,
to wait upon the Lord for counsel and instruction in all things.

And it is your father`'s desire, that you may be loving and dutiful unto your mother,
and loving and kind to your wife.

--

[.asterism]
'''

NICHOLAS GATES, late of Alton, in Hampshire, clothier, son of William Gates,
of the same place, was,
from the time he understood there was a God who made the world and all things therein,
desirous to have the true knowledge of him.
In his childhood he took great delight in reading the Holy Scriptures,
and in hearing the best reformed ministers,
and gave himself often to private praying to the Lord unknown, uttering words before him,
until on a time in his chamber kneeling down by his bedside, in order to utter words,
he was stopped, and it was said to him in his heart, as he declared and believed,
by the Lord, "`You need not utter words, for I know your heart and soul`'s desire.`"
So remaining kneeling a while, he arose, but uttered no words.

About the age of twenty-one years,
he came to join with those people in scorn called Quakers,
and was rejected by his father, and became an alien to his father`'s house,
and many times threatened to be cast off, yet he loved his father dearly.
The Lord was more to him than his father, and fitted him for his service,
and gave him a gift of the ministry,
and called him forth freely to preach the gospel of the grace of God,
and made him an experimental witness of the sufficiency thereof.
He labored earnestly therein in several parts of England,
to invite all to receive and come under its teachings.
By the power and grace of God, he was supported under, and carried through,
all the trials and exercises, stonings, stockings, reproachings, imprisonments,
and spoiling of goods he met with for the truth`'s sake, and his testimony thereto.

He was religiously exemplary in his family, and among all where he travelled,
preached sound doctrine, lived a holy life, was just in his dealing,
diligent in his calling, a tender husband, a loving father, a kind friend,
a good neighbor, a follower of peace, delighted in hospitality, sought unity,
and labored to preserve it in the bonds of peace.
He was diligent in attending meetings, both First-days and other days,
and in the service of quarterly and monthly meetings, and in taking care of the poor,
and was greatly blessed of God.
This servant of Christ being taken ill the 10th of the Tenth month, 1707,
the first thing he expressed his care for, was the church,
and to have friends preserved in unity,
saying he was well satisfied with the Lord`'s dealing with him.
"`He has been a good God to me all along, and has let me live to good old age,
and been my support from time to time, and is so in this present exercise.`"
Another time he said, "`My days are expiring quickly;
but I have lived to see the goodness of the Lord in the land of the living.`"

He then expressed his love to his wife in a very tender, affectionate manner,
and prayed to the Lord that he would bless and preserve her and his children to the end,
desiring they might live together in love, and watch over one another therein.
He said he did not know, if he had his time to live over again, that he could die better,
having the evidence in himself of well done; yet he said,
if the Lord did see fit to restore him,
and he could be an instrument to gain more souls to God, he could be glad;
for that was his great joy,
when he considered how he had spent his time in the Lord`'s service.
This honest, zealous old man gave good advice to many that came to see him,
and for their children, laying a charge upon such friends as had them,
to keep their children to the plain language,
and to bring them up in the fear and admonition of the Lord;
and admonishing his own children to do so by their children,
and to ask them questions for opening their understanding,
that they might know what God is, and where he is to be found,
and to do thus while they are young and tender; and said, "`Oh! that men,
especially young men, did know the comfort of living a sober life.`"

A neighbor coming to visit him, asked him how he did; he replied, "`Weak,
and am going soon out of this troublesome world,
to a place where there is neither sorrow nor trouble.`"
After this, he said, "`Friends were formerly known by their fewness of words,
and keeping to their word in their dealings.`"
He very often desired Friends to keep to plainness, both in habit and speech,
warning his daughter Deborah present, and his wife, to watch over her children,
to keep them out of pride, saying, "`There is scarcely a worse weed than pride.`"
A while before he died, he said,
"`The door of entrance is open into the kingdom;`"
into which it is not doubted but he is entered.
He departed the 21st of the Tenth month, 1707, aged about seventy-four,
convinced about fifty-two years; and was honorably buried on the 24th,
in Friends`' burying-ground at Alton,
after a very solemn meeting of many Friends and others,
and left his wife twenty-one children and grandchildren.

[.asterism]
'''

MARY MOORE, late wife of John Moore, of Eldworth, in the county of York,
daughter of Thomas Camm, was seized with sickness,
which continued upon her about three months, which she bore with much patience,
often saying she was well content with the will of God.
Her dear father being then from home in the service of truth,
her husband several times asked her if he might not write to her father,
to acquaint him with her weakness, and to desire his return home.
She answered she should be right glad to see him,
but she would not have his service hindered upon her account,
hoping when that was over he might return in due time to see her.
Accordingly, upon the 30th of the Sixth month, 1707, he got to Eldworth,
and found his daughter very weak;
but the surprise of joy to see him had liked to overwhelm her spirits,
so that for a time she could not speak to him.
In a little time she got over it,
and expressed her great joy and satisfaction to see him, saying,
"`Now the Lord has answered my desire; and now I leave all to his wise disposing,
whether life or death.`"
She continued pretty easy, still, and resigned; and about a week after she grew worse;
but said to her father, "`I am resigned to the will of God, and gathered out of care,
touching visible things; only some fear is upon my mind touching my eldest son,
that it will prove to his harm to be schooled where he now is, therefore,
I desire he may be removed to some good place and school.`"
This was promised her should be done as speedily as well could be;
at which she seemed contented and easy.
She often signified her resignedness to the will of God,
praying be endued with patience to the end of her race:
and the Lord was pleased to hear and answer.
She bore all her long exercise with great patience.
On the 12th of the Seventh month, though much weakened,
she was opened and strengthened to speak very strongly,
which was written down as follows:

"`Oh! what a blessing have I enjoyed in this my quarter of a year`'s weakness.
It has been the best and most sweet, pleasant, and profitable time of all my life.
I have seen the end of all worldly enjoyments.
Although I have a kind father, a loving husband, and dear babes, yet I can freely, yes,
heartily, with all my heart, leave all to be with Christ my Redeemer, my Savior,
and the beloved of my soul.
Oh! he has been near me, yes, with me day and night.
He has so drawn me, and won upon me, with the cords of his love, taking me by the hand,
and opening his arms to receive me into his bosom, that I am overcome with his love.
Very gentle has his hand been upon me;
and he has blessed me with great contentment and patience.
I am freely resigned up to the will of my God.
As for my poor babes, I commit them to the Lord who gave me them.
They have also two good fathers, who will take care of them,
where I can leave them freely; only I desire you, father,
to take care of John`'s schooling and education,
and get him apprentice to some good Friend at Bristol, or elsewhere, as you see fit.
All my care I have cast upon God, and upon you, my father and my husband;
so that I am easy.
Blessed be the Lord for this good and precious time,
wherein I am freely devoted to his will, and right glad to leave this troublesome world,
having the earnest of that eternal glorious redemption,
through my blessed Lord and Savior, Jesus Christ.`"

Then calling her children one by one, charged them, saying, "`Fear God,
dwell in love one with another,
and be sure obey your father;`" then blessing them particularly in the name of the Lord,
and committing them all unto him.
When she parted with her youngest babe, she kissed her, and said, "`They tell me that you,
poor lamb, will have the greatest loss of me;
yet as I have cast all my care for you upon the Lord, I am easy,
and leave you to his protection and divine providence, who gave you all to me,
who never fails those that trust in him, being a tender Father,
both to the fatherless and motherless children.`"

To her eldest son John she farther added, "`I have been a tender mother to you,
and now must leave you.
Therefore, dear child, observe the counsel and advice of your dying mother,
write them down, and imprint them in your mind.
First, I charge you to fear and remember God your Creator in the days of your youth.
Refrain all evil company; be sober and attentive to all good counsel;
let not your mind go roving after foolish toys,
and do nothing but what is good and commendable;
and then you will not need to make any excuse or lie;
for a lying tongue is an abomination to the Lord.
Read, and remember what wise Solomon says will be the portion of such
as despise or neglect the good counsel of father or mother,
and thereby do evil in breaking God`'s command, to obey father and mother.
Oh! dear child, consider of these things, and be wise: God Almighty bless you,
and you all, and preserve you out of all evil.
This is the one great thing that I desire for you; not to be great in the world,
which hurts many; but to be great in virtue and godliness,
which has the promise both of this world, and that which is to come.`"

Then she lay still some little time, desiring all might leave the room except Anna,
her husband`'s eldest daughter,
between whom and her there had been a great endearedness and strong bond of love.
After some time her father, Thomas Camm, coming into the room again,
and hearing her and her daughter Anna in discourse, sat down out of her sight,
and heard her say to Anna, that she left her as a mother to her motherless children;
bidding her call to mind how she and her two younger sisters, by Providence,
fell under her care when very young,
and how she had faithfully discharged her trust in tender care over them;
and she desired no better for hers than she had done for them,
when they could not do for themselves.
Anna then tenderly telling her mother,
she hoped that forever her children should lack nothing
that was in her power to do for them,
she being sensible of the strong obligation of duty she was under,
and so they left things.
After some time, she said, "`What a comfort and joy it is,
to be so near the end of this troublesome world.`"

She was always very glad of friends`' company in visits and little meetings,
which at several times were kept in her chamber, which, she said,
were to her great refreshment; the last was the evening before she died; after which,
she said, "`This is likely to be the last.`"
Next morning she said, "`This night, and a little part of next day will finish here.`"
That night she had very sharp pangs, hard for her father and others to hear;
so that he left the room once or twice, but could not stay easily in or out;
and an exercise or concern came upon his spirit, to pray to the Lord for her;
and the Lord was pleased to hear the supplication that was put up;
so that she had no more such sharp pangs,
and finished her course here on the 15th of the Seventh month, 1707:
and it is not doubted but she is at rest with the Lord.

She was decently interred in her husband`'s burying-place at Eldworth,
on the 17th of the same month, being her birthday, and also her marriage day, and,
had she lived to that day, her age would have been thirty-eight years.

The loss of her was greatly lamented, not only by her relations and nearest friends,
but neighbors, both poor and rich, her loving, innocent,
and wise conduct and deportment having gained her great
respect among persons of all sorts that knew her.
Oh! that many in observing and following her pious example,
may be stirred up more and more to seek after virtue and godliness,
and thereby purchase to themselves a good name, as she has done,
through love and obedience to the Lord Jesus Christ,
is the chief design in publishing these lines.

[.asterism]
'''

THOMAS CAMM, late of Camsgill, in the county of Westmoreland, was born in the year 1641,
of honest, religious, and godly parents, was well educated,
and from his childhood inclined to be religious, and sought after the best things.
He delighted in the company of the best, or most religious sort of people;
and in his tender years the Lord was pleased to visit
him with the light of the day springing from on high,
and thereby convinced him of his blessed and unchangeable truth;
even in the morning of the day, to these latter ages of the world;
and after some time called him forth into the work of the ministry,
for which the Lord fitted him.
Being thus visited and called of God,
he counted nothing too near or dear to part with for truth`'s sake;
but left all to follow the Lord,
and with his whole strength and substance was given up to serve him,
and faithfully to do the work he was called to.
The Lord who had called him to such a great and glorious work,
as preaching the everlasting gospel, did fitly qualify him for the same,
pouring forth upon him of his holy spirit, and endued him with divine wisdom,
whereby he was made an able preacher of the word of life to many,
and could divide it aright, according to the states of the people.

As he was thus called and qualified,
so he was diligent and laborious in the work of the Lord in many parts of this nation,
and was made instrumental to convince and establish many in the way of truth.
His doctrine was sound, and his delivery powerful;
and though his testimony was not with the enticing words of men`'s wisdom,
yet it was in the demonstration of that divine power,
which reached the witness of God in the hearts of the hearers.

Great and many were the sufferings he met with,
and he very patiently bore and went through them, of many sorts and kinds,
as imprisonments, spoiling of goods, mockings and scoffings from those without,
and suffering among false brethren.
In all which he stood firm and faithful in his testimony for truth,
approving himself a true follower of Jesus Christ,
suffering joyfully for his name`'s sake, who had counted him worthy, not only to believe,
but to suffer for him.
As he was a man wonderfully endued with heavenly and divine wisdom,
so he was a man of great humility,
very much laboring for love and unity among brethren,
and where any thing appeared tending to a breach of it,
he always used his utmost endeavors to put a stop thereto,
approving himself to be a man of peace, and always labored for it,
both in the church and also among all sorts of people.

He was a man beloved of God, and by all good men who knew him.
He was a nursing father to many,
encouraging everything that was good in the least child;
but very zealous against every appearance of evil;
especially against that which in any way tended to the laying
waste of that testimony which the Lord required his people to bear,
being zealously concerned to keep his testimony clear in every branch of it.
He was a man well qualified for discipline, and labored very much to promote it,
for the encouragement of those who were weak,
and to bring to judgment those that were loose, and would let their testimony fall.
He was very zealous against that anti-christian yoke of tithes,
and though he suffered very much on that account, yet he stood faithful to the last,
and rejoiced in his sufferings upon that and all other accounts for truth`'s sake.

Though in the latter part of his time he was attended with much bodily weakness,
which through his many hard labors, travels, and sufferings, was come upon him,
yet such was his zeal for truth, and love for the friends of it,
that he was willing to spend his time and strength for and in the service of truth,
which he faithfully performed, to the comfort and edification of the churches of Christ.

On the 17th of the Eleventh month, 1707,
having been in the love of God to visit several meetings in the upper end of Lancashire,
Westmoreland, and the west of Yorkshire, he returned to his son John Moore`'s,
at Eldworth, and that very day it pleased the Lord,
by a gentle hand (as he phrased it) to bring his old distemper upon him.
After some few days it grew more violent and hard upon him;
he bore it with much patience,
and continued in a weakly distempered state of body for five or six weeks,
taking very little natural food, nor getting much sleep or rest at nights;
yet could walk up and down his chamber, and was always pretty cheerful,
and freely resigned to the will of God, often saying,
"`I neither desire to live nor to die, but am well content,
however it shall please the Lord to order it;`" farther saying, "`If the Lord sees fit,
or has yet any farther service for me to do, it is easy with him to raise me up again;
but his will be done, I am very well content, I bless the Lord.`"

Near the conclusion of his days, he said, "`I have great peace and satisfaction,
in that I have done the will of God.
I do not know that I have much more to do, the time of my departure seems to draw nigh;
but I am well satisfied.
I bless the Lord, I can say with the Apostle, '`I have fought a good fight;
I have finished my course; I have kept the faith,
henceforth there is laid up for me a crown of righteousness, which the Lord,
the righteous Judge, shall give me at that day, and not to me only,
but to them also that love his appearing.`'`"

One day, he being alone in his chamber, his son John Moore came and sat down by him,
and asked him how he did; he answered, "`I am but weakly of body,
but strong in the inner man, blessed be the Lord,
who has been my support and strength hitherto.`"
He then farther said, "`I have been pondering in my mind,
and meditating of the wonderful and unspeakable mercies and loving-kindnesses of God,
to me extended all my life long, even to this very day; that I, such a poor, weak,
feeble creature, should be enabled to hold out, and go through those many trials,
travails, sufferings and exercises, both inward and outward, of various kinds,
that have fallen to my lot.
It has indeed been the Lord`'s doing,
who is and has been all along my buckler and my shield,
he shall have the praise and the glory of all, for he alone is worthy of it,
forever and forevermore.`"

His distemper continuing, and his bodily strength growing weaker,
so that there was little likelihood of his recovery,
he gave very plain and distinct directions concerning his burial,
as one not much concerned at his approaching departure.

Being grown so weak he could not well go alone, without some little support,
one evening as he was walking over his chamber floor,
leaning upon his son J. Moore`'s arm, his legs trembled under him, which he observing,
said, "`Dear John, when the pillars of the house begin to tremble, there is feeble work.
But then, blessed are they who, when this earthly tabernacle is ready to be dissolved,
do assuredly know that they have a habitation eternal in the heavens,
whose builder and maker the Lord is; of which, for my part,
I bless the Lord I am well satisfied.`"

About a week before he died, several of John Moore`'s children being in the room with him,
he said to them, "`Now I think I must leave you.
If the Lord had seen fit to spare me a little longer,
I might have been of service to you in counsel and advice; but the Lord,
the great and wise counsellor, as you have your eye to him above all things,
will not be lacking to you in counsel.
I love you entirely, and the blessing of the Almighty rest upon you, if it be his will.`"

He several times spoke concerning Esau; one time he said,
"`Esau`'s mount was in part consumed and consuming,
yet there were branches still remained;`" and said,
"`The Lord lay it waste more and more.`"

Another time he said, "`Faith and patience, hope and charity, are excellent virtues;
the Lord, if it be his will, endue his children and people more and more therewith.`"

When he was grown so very weak that the getting his
clothes on and off was somewhat difficult and troublesome,
he one time said to those about him, "`Dear children,
you have a great deal of trouble and exercise about me, the Lord be your reward;
but you shall see a little time will put an end to all these troubles,
and a happy end it will be for me, I doubt it not at all.`"

Another time, being some days before he died,
John Moore`'s eldest daughter standing by him, he took her by the hand, and said,
"`Dear Anna, the Lord will reward you for your care and pains about me.`"
Seeing her affected with sorrow,
as well she might be for the approaching loss of so near and dear a friend,
he farther added, "`Death will not be said no; but it will be well with me,
the enemy cannot touch me.
The Lord who has been with me,
and has borne up my spirit through and over all the
various exercises and trials of my time;
he will be with me to the end; there is no doubt of it.`"

One time lying upon his bed, in a sweet and heavenly frame of mind and spirit, he said,
"`I have served the Lord in sincerity, with all my heart, and with all my soul,
and with all my strength; hallelujah, hallelujah, hallelujah.`"
And so went on praising and magnifying the Lord,
to the melting and tendering the hearts of all present.
Afterwards he said to John Moore, and some others who were with him, "`Bear me record,
I die in perfect unity with the brethren;
my love is as firm and true as ever in our Lord Jesus Christ,
the author of our salvation.`"

When grown very weak, being asked how he did, he would say, "`Weak of body,
but strong in the Lord;`" saying also, "`In Abraham`'s bosom there is sweet repose.`"
He several times spoke of the efficacy and virtue of the wine of the kingdom;
and about two days before he died, he seemed to be faint,
and J. Moore gave him a little wine to sup, thinking it might refresh him,
but his stomach could not bear it.
Then looking pretty cheerfully at J. Moore, he said, "`Dear John,
you see these things will not do; but one cup of new wine in the heavenly kingdom,
with my dear and blessed Lord and Savior Jesus Christ, will make up all.`"

His strength decaying very fast, he for the most part lay very still and quiet,
as one waiting for his dissolution, not saying much, unless when spoken to,
and then would answer very sensibly to what he was asked.

On the day he died, he was desirous to be helped out of his bed,
but seeing how very weak he was, he was put off for some time; but he still urged it.
J+++.+++ Moore told him, he doubted he was so weak he could scarcely bear it without fainting;
but those with him told him, they were willing to help him the best they could.
To which he replied very cheerfully, "`That is enough: I hope the Lord,
that has been my help in many straits and difficulties, will also now help me.`"
So his clothes were got ready, and by degrees got most of them on;
but before they had quite done, he was likely to faint:
so they sat him down on the bedside, and supported him a little.
After a while he somewhat revived, and looking about him,
he saw J. Moore`'s youngest child, between two and three years old,
standing before him a little way off, and he beckoned with his hand,
that she might come to him, and with a little help he set her upon his knees,
and affectionately kissing and embracing her, he said, "`God Almighty bless you.
The God of Abraham, of Isaac, and of Jacob, bless you, and make you happy,
if it be his will.`"
Then after a little time they got his clothes something better on,
and set him in his chair, where he sat a pretty while; then growing weary,
he desired to lie down upon his bed, which he did, and after a little time,
he was perceived to weaken very fast.
He lay still and quiet, not saying any thing that could be heard or perceived;
but drawing his breath sometimes quicker and sometimes slower,
yet without the least disturbance, or stoppage of phlegm.
He continued so for the space of about six hours;
then stretching himself forth upon his bed, he departed this life without sigh or groan,
as one falling into a deep sleep, on the 13th day of the First month, 1708,
between the hours of eleven and twelve in the night, being aged sixty-six years,
nine months, and ten days.

Thus, having fought the good fight, and finished his course well,
he laid down his head in peace with the Lord, and is freed from all his sufferings,
sorrows, and afflictions here, and entered no doubt into the kingdom of eternal glory,
forever to live, and magnify, and praise the great God, world without end.
On the 15th of the same month, his body was removed from Eldworth in Yorkshire,
where he died, to his late dwelling-house at Camsgill, in Westmoreland,
and on the 16th of the same month was carried in
a solemn manner to Friends`' burying place at Park-end,
in Preston-Patrick, being about half a mile from Camsgill.
It was accompanied there by several hundreds of people, both of the neighborhood,
and also many friends out of several of the adjacent counties,
and was there interred in a decent, Christian manner,
there being a general appearance of sorrow in those present
for the loss of so good and serviceable a man.

The corpse being interred, all, or most that were there, drew into the meetinghouse,
and had a precious edifying season together, the powerful living presence of the Lord,
in an eminent manner, overshadowing the assembly,
to the tendering and affecting many hearts.
Several testimonies were then borne,
to the sufficiency of that universal principle of divine light and grace,
which is given to be a teacher and a leader to all mankind,
and is become the teacher and the leader of all those
who are willing to be taught and led by it.
But it is, and will be, the condemnation of all those who are disobedient to,
and rebel against it, while they continue in that state.
Also several testimonies were borne, concerning this our dear friend, deceased,
as to his faithfulness, care, and labor of love in serving God`'s heritage;
as also with respect to the many trials, travels,
and deep exercises that he had faithfully gone through in his day and time,
upon truth`'s account;
all which he was enabled to perform and go through
by the power and assistance of that divine grace,
and holy spirit of God, which he still accounted his buckler and his shield,
his bow and his battle-axe, and by and through which, he was what he was,
and to which alone, and not to him as man, the praise and glory of all was attributed.

So friends having cleared themselves of what was upon their minds, the meeting broke up,
and friends parted with hearts deeply affected,
and filled with the love and goodness of God,
which had been plentifully shed abroad among them that day; praises, honor,
and glory over all, be given unto God, and to the Lamb,
who sits with him upon the throne, who is worthy forever, and forevermore.
Amen.

[.asterism]
'''

RICHARD DAVIES, of Cloddiecochion, in Montgomeryshire, by trade a felt-maker,
was convinced of the blessed truth about the year 1657,
and became faithful unto the Lord, through the power of it,
and thereby was made a minister of the word of life,
and was concerned freely to preach the gospel of salvation.
He was endued with spiritual gifts,
and serviceable in the exercise thereof in the churches of Christ,
both with respect to his sound doctrine and exemplary conduct,
and diligence to serve the widow and fatherless, and was fervent in prayer.
His last sickness was but short, for he was taken ill on the sixth day of the week,
and died on the First-day of the next following.
Some Friends of Dolobran meeting came to him,
and they had a meeting with him in his bed-chamber,
and he desired them to pray to the Lord, that he might have an easy passage, saying,
"`The fervent prayer of the righteous the Lord will have a regard to.`"
But his pain continuing upon him, the next day, being the 22nd of the First month, 1708,
about the ninth hour in the morning, he departed this life, and had an easy passage,
as it were in a sleep, having often said he must sleep his long sleep.
His body, on the 25th of the same month,
was accompanied by a considerable number of Friends and other people,
to the burying-place near his own house at Cloddiecochion, and there decently interred,
and no doubt but his soul is at rest with the Lord.
Aged seventy-three; a minister about forty-five years.

[.asterism]
'''

SARAH GODFRY, wife of Benjamin Godfry, of Chipin, near Buntingford,
in the-county of Hartford, daughter of George and Sarah Robins, of Sandon,
in the said county, was one who loved truth in her young years,
and with a tender heart did seek the Lord often, both in and out of meetings,
and was very watchful over her words, lest she should offend the Lord,
or give an evil example to others.
She was obedient to her parents, and tender to her brethren and sisters,
and would give them good advice.
After she was married, and had children, she was concerned for them,
and desired a meeting at her house, for the good of her neighbors, which was had;
at the conclusion of which she spoke with a loud voice, and said,
"`Ever blessed and praised be the name of the Lord for this
blessed opportunity;`" which much affected the people,
knowing her great weakness.

She also expressed her willingness to die, and leave husband and children,
to go to the Lord; and then she said, "`Blessed, praised, honored, renowned, magnified,
and glorified be your name, for you are worthy of all blessing, praise, glory, and honor,
for you are a merciful God.`"
After this manner she lay praising the Lord for some time.
A neighbor coming in, who was not called a Quaker, seeing her in such a heavenly frame,
spoke with tears, "`She will not leave her fellow behind her:
she will reap the fruit of her doings, joy unspeakable, and full of glory.`"
"`What a mercy,`" adds the neighbor, "`it is,
the Lord lays no more upon her than he gives her patience to bear.`"
She answered, "`The Lord is very good to me, what a great mercy it is,
that I am so willing to die; what a comfort it is, over what it would be,
if I was in great distress.
I feel no condemnation.`"
She desired her mother to hold her hands as she sat in her chair, "`for,`" said she,
"`I think I am going, and I feel great peace.`"
Her mother seeing her in such a still, comfortable condition, sat a while very still,
and after she said, "`Lord, Lord, receive my soul,`" and so departed like a lamb,
in about a quarter of an hour.

[.asterism]
'''

JOHN PETERS, of the parish of Minver, in the county of Cornwall,
about the 26th year of his age, received the knowledge of the blessed truth,
and joined in profession with the people called Quakers.
Being zealous and faithful to the Lord, he bestowed upon him a gift,
and called him into the ministry of the word of life,
in which he was diligently exercised for many years,
and labored in the work of the gospel of Christ freely
and faithfully to the end of his days.
He was a good example in his life and conduct, and careful so to walk,
that the ministry might not be blamed in any thing by him,
being endued with the spirit of wisdom and understanding.
He travelled much, not only in the county where he lived,
but frequently in the south and western counties of England, and some parts of Wales;
and as he was well known, he was well received by the faithful.

When he thought he was near expiring, he got himself raised in his bed, and said,
"`It is the Lord`'s great mercy,
who in the midst of the pains and anguish that attend our bodies,
gives us resignation of mind to his divine will.
This may be soon spoken of; but it is sweet to come to the living experience of it,
and God has mercifully given me this resignation and quietness of mind,
in which I have peace, notwithstanding the weakness and pains I lie under.`"

Then observing some young people about his bed,
he counseled them to keep low in the fear of the Lord,
not to seek to themselves great things, nor to post after the riches of this world;
though a moderate care, within the bounds of truth, was allowable.
But he spoke against extending our desires that way,
to the forgetting the work of religion, and the preparation for our latter end; "`For,`"
said he, "`a little, with God`'s blessing, will suffice.`"
He sweetly enlarged on the benefit of his blessing,
and the difference between those who enjoyed it and those who were cursed, adding,
"`In my young years I had a belief raised in me, that if I lived in the fear of God,
neither I nor mine should ever lack: and it has been all along confirmed to me.`"
He said farther, "`My heart is full of the love of God,
and the sting of death is taken away.
It would indeed be sad, at such a season of languishing,
to have a load of sin on the soul.`"
Many other seasonable counsels he then gave, that are not noted.

Another day he said to Friends present,
"`We have cause to be thankful to God for making known to us his truth.
I am evidently satisfied that the way the Lord has brought us into, is the way of truth.`"
He spoke of the necessity of living in obedience to it,
that it might be a cross to our wills and bridle to our tongues, and a stay to our minds.
He also said, "`Wait for wisdom and direction from the Lord,
to enable for such services as he requires;`" saying that the strength
of man`'s parts was not sufficient to do the Lord`'s work.
He counseled that love might be the principal motive in all public concerns,
and therein to rebuke, to exhort, and to counsel; and if, in those labors,
we meet with cross and peevish spirited people, that care might be,
not to permit the same spirit to sway us; but to overcome the evil with good, saying,
"`I have nothing in appearance but death before me; but am well satisfied,
however the Lord deals with me; for,`" said he, "`I am sound in mind,
through the Lord`'s mercy, and have abundance of ease.
I am not afraid to die.
The sting of death is taken away;`" for which he praised the Lord.
Some of his relations being desirous he should try another doctor, he said, "`Be quiet,
be still; if the Lord sees fit to lengthen my days, he can soon heal my malady;
if otherwise, I am content; for,`" adds he, "`it is no small comfort to me,
that I did not hearken to the persuasions of some
that would have me go from one doctor to another;
my confidence is in him who is alone the physician of value.
If the Lord has any further work or service for me to do, he can heal me; if not,
I have done with this world.`"

When near his end, he said to his wife, as he had often before,
"`Mourn not for me when I am gone.
I am waiting for my change, desiring to be dissolved; death is not fearful,
the sting is taken away.`"
He often cried to the Lord for a blessing on his son,
whom God had left him of ten children, and said, "`I desired,
before ever God gave me a child,
they might rather be taken off in the innocency of their days, than live to dishonor him.`"
So, in the fear and favor of God, he departed this life, the 11th of the Seventh month,
1708+++.+++ Aged about sixty-three; convinced about thirty-seven;
and a minister about twenty-five years.
He was also a prisoner several years for his testimony against tithes,
and for refusing to swear, in obedience to Christ`'s command.

His body was interred the 13th of the said Seventh month,
in Friends`' burying-ground at Minver,
being attended there by a numerous company of Friends, relations, and neighbors;
and sundry testimonies were borne to the light, life, and virtue,
wherewith God had beautified our friend, while he abode among us;
as also to the necessity of holiness and obedience,
that those who succeed him might come to die the death of the righteous,
and that their latter end might be like unto his.

[.asterism]
'''

GEORGE NEWLAND, son of George and Susannah Newland, of the city of Dublin, clothier,
was an orderly and dutiful child, and sought the Lord in his young and tender years.
When he was drawn or persuaded by his schoolfellows to play, or be wild,
he afterwards would be under such trouble in himself,
that he would weep and mourn in the night season.
When about ten years of age, he desired he might be sent into the country,
and retire from his companions in the city.
So in a while his parents sent him into England, and boarded him at Eleanor Haycock`'s,
widow, near Sanky, and he went to school to Gilbert Thompson, at Sanky, in Lancashire.

About the age of eleven or twelve years,
the Lord concerned him to give testimony to the truth, calling him into the ministry,
in which he was faithful, and travelled in the work thereof,
and in the exercise of that gift the Lord had bestowed upon him,
in the provinces of Leinster, Ulster, and Munster, in Ireland.
Being endued with a good understanding, he was not rash to utter words,
without the help or motion of God`'s Spirit;
so that his testimony and ministry were not only instructing but edifying;
and being an innocent youth, was beloved of faithful friends because thereof,
and his exemplary conduct,
which was according to the holy doctrine of our Lord Jesus Christ.

Between the age of eighteen and nineteen years, he was visited with lingering sickness,
and his mother asked him, after some time, whether he thought he should recover;
to which he then answered, he did not know, but if it was the Lord`'s will,
he had rather die than live; but said he dared not desire it, adding,
although his time had been short in the world,
he had gone through a great deal of exercise and trouble,
that none knew but the Lord alone.
Another time he said to his mother,
"`I have felt more of the Lord`'s love to me since I was sick, in a wonderful manner,
than ever before.`"
Again said, "`I strove to serve the Lord in my health, and now I reap the benefit of it.
I can look forward, and that is a mercy.`"
Being frequently comforted in spirit, and filled with the love of God, he would say,
"`Oh! if the earnest be so precious, what will the fullness be?`" When weak in body,
he was strengthened in spirit, and enlarged to praise and magnify the Lord;
and he was opened to give good counsel and advice to his brother Isaac,
taking him by the hand, kissing him, saying, "`I love you dearly;
be sure you fear and serve the Lord, and be obedient to your parents;
for though you be young and strong now, yet you know not how few your days may be.
I speak to you in love, remember my dying words when I am gone;
and that it will be enough in a dying condition, to bear the pain and affliction of body,
without having a troubled conscience;`" and therefore encouraged him to well-doing.

Much was spoken by him to his sister Elizabeth, whom he called also, and kissed her,
and tenderly desired her to love and fear the Lord, and be dutiful to her parents;
and in like manner to his sister Lydia, saying, he hoped she would be an honest woman;
and said, "`In my health, when I went to bed, I did meditate and think upon the Lord,
and now in my sickness I find the benefit thereof.`"
Then tenderly acknowledging the love and care of his parents towards him, said,
"`If I live, I can never make you amends for your trouble and care over me.`"
A few days before his death, he said unto his mother,
"`I love you dearly;`" and saluting her, said,
"`I hope the Lord will reward you for all your trouble and care over me,
and I hope we shall meet shortly, where we shall never part again.`"
Some hours before his departure, being overcome with the goodness of God,
he was enabled to praise and celebrate his name, saying with admiration, "`How good, Lord,
are you to me!
I am not worthy of the least of your mercies and favors;`"
and continued to praise the Lord in such manner,
that all that were in the room were reached and affected,
and broken by the power of God that attended him, during that season.

His uncle John coming to take leave of him, seeing him in this condition, yet near dying,
said he would not leave him till he saw him in his grave;
although he had intended before to go home to his dwelling that was in the country.
He was tendered to see him in such a frame of mind;
though not a frequenter of the meetings of those called Quakers,
but said he was satisfied this youth was going to his heavenly rest.
That night he was earnest with his mother to lie down and get some rest;
but after a little while called for her again, and said, "`My dear mother,
take it patiently, for you may rejoice that I am going.`"
He desired all to be quiet and still;
and sent several times to see what hour it was by the clock;
and being sensible his change was near, settled his head to the pillow,
and quietly departed this life, like an innocent lamb, on the 24th of the Eighth month,
1708, about the 2nd hour in the morning, and was buried the 26th of the same month,
in Friends`' burying place, near Dolphin`'s Barn,
being accompanied to the grave by many friends and neighbors.
Aged near nineteen, and a minister about six years.

This testimony was given by his friends in Dublin concerning him,
which I thought it right here to insert.

[.embedded-content-document.testimony]
--

It pleased the Lord to favor this youth with a gracious visitation,
even in his childhood, and so to prepare him for his service, whereunto he appointed him,
that there appeared deep impression of a concerned mind,
for the good and eternal wellbeing of his soul.
As he grew in years, he apparently grew in grace, and in the knowledge of God,
and his son the Lord Jesus Christ;
so that the Lord was pleased to put him into the ministry.
Although young, he being sensible of the appearance of the Son of God in his heart,
did deliver his testimony with a good understanding,
not being forward or rash to utter words;
but waited for that which is the fountain of all true ministry,
i.e. The help of the Spirit of God,
that enables God`'s ministers to speak to the edifying, and instructing,
and building up of one another in the love of God.
This being the concern of this innocent youth,
made him to be beloved of faithful friends who knew him; and the more,
because his conversation agreed with his doctrine.

He went abroad sometimes to visit friends in this province of Leinster,
and was also in Ulster and Munster provinces,
and friends had generally a love and respect for him,
and there would commonly be great meetings where he was,
both friends and others admiring the Lord`'s dealings with him, in his tender years,
being but twelve years old when his mouth was first opened in meetings,
in a testimony for God.
We have a great loss of him, he being such a good example to our youth, both in that,
and also in his conduct;
too few being willing to follow him in that true nearness of walking with God, as he did;
but love liberty to the flesh and will, that works not the righteousness of God,
but brings trouble and grief on those who are concerned
for the well-being of their immortal souls;
which this youth was careful to avoid.
His behavior was more like a man of gray hairs, than one not attained to nineteen years,
being not desirous of long life in this world, as he used to express sometimes;
but rather that he might do his day`'s work, being ready and prepared,
when the Lord was pleased to call him hence, to have a portion and lot in God`'s kingdom,
of that life and peace that are everlasting.
When he was visited with the sickness of which he died,
which continued on him about a quarter of a year,
he bore it with much patience and resignation to the will of God, and very cheerfully;
which was comfortable,
both to his parents and friends who visited him in the time of his illness.

Before his departure,
he was concerned to advise and counsel his brother and sister to fear and love God,
and be dutiful to their parents, etc.
And though it is our loss, to have such a one taken from us,
we believe it is his gain to be removed from where trouble and temptations attend,
to where the wicked cease from troubling, and the weary are at rest.

[.signed-section-closing]
Signed in behalf of the said meeting, by

[.signed-section-signature]
Amos Strettell, Richard Sealey, George Rook.

[.signed-section-context-close]
From our meeting in Dublin, the 19th of the Second month 1709.

--
