== Chapter 3

[.chapter-synopsis]
* William Fry
* Joseph Jackson
* Ann Mercy Bell
* Rebecca Shewell
* Ann Leaver
* Mary Bundock
* Cuthbert Wigham
* Jonah Thompson
* Robert Hayward
* Elizabeth Holme
* Thomas Gawthorp
* Mabel Wigham
* Robert Pryor

WILLIAM FRY, of the city of Bristol,
was favored with the visitation of divine love in early youth,
and was helped thereby to walk circumspectly.
At that time, he stood much alone among the youth; nevertheless, continuing faithful,
he became a good example of watchfulness and self-denial.
About the twenty-seventh year of his age, he first appeared in the ministry,
but for several years seldom; being not only then, but always,
as he expressed himself a little before his death, '`more desirous to feel than to speak.`'
As he was often led into a deep travail of spirit,
that the ministry might be kept living,
and that nothing might be offered in the will of the creature,
he was himself careful in this respect, and waited for the holy anointing,
the only true qualification, before he opened his mouth in testimony.

He travelled in the service of truth through Ireland, Wales,
and many parts of this nation; concerning which,
he spoke to a friend who came to visit him, to this effect;
that he had ever found great peace and satisfaction in giving up to those services,
the remembrance of which was very lively with him,
particularly during his last sickness.

During this illness, which was painful, and of several months`' continuance,
he uttered many weighty expressions.
Being asked by a friend one evening if his pain was then great, he replied,
'`I have been in great pain this day, but my mind is favored with a calm,
which I desire to be thankful for.`'
Observing he was dipped into very low seasons,
he remarked that it had been the case with many favored servants of the Lord,
some of whom he named, and added, it was not to be wondered at that it was so with him;
saying, '`Oh! how have I longed, and do long,
to feel the arisings of that life which is more desirable to a remnant in this day,
than the increase of corn, wine, or oil.`'
He mentioned also that he had a view of a gathering day in Bristol, and,
though he might not live to see it, he should die in the faith of it.

Some days afterwards he expressed himself in the following manner:
'`I think I have been favored, during my illness,
to experience what I have often had to declare;
that it is a good thing to dwell near the truth,
that inexhaustible fountain and ocean of divine love.
The sweet streams issuing therefrom sweeten the bitter cup.
This it is that has supported me under the present afflicting dispensations,
and the deep baptisms which it has been my lot to pass through,
wherein I may say I have been dipped as into the bottom of Jordan.`'
He afterwards added, '`I have been favored with a calmness; may I not say,
a holy calmness; what if I say,
a foretaste of that joy which shall be known when this mortal part puts on immortality;
and have been enabled to bear with patience and resignation,
the present trying afflictions, without murmuring or saying, Lord, what are you doing;
or why do you deal so with me?
It is comfortable to witness that which has been our morning light to be our evening song.
May those present,
who have been acquainted with the visitation of truth in the morning of their day,
continue to abide under it, and prize it above everything else.
It was excellent advice, to buy the truth, and sell it not:
it is these that will find support under every trial; and though we may have to say,
as our blessed Lord in his agony said, "`If it be possible, O Father,
let this cup pass from me,`" which was the effect of his humanity; but oh,
how soon did the divinity appear in him! "`Nevertheless, not my will, but yours,
be done.`"
You who have known the place where true prayer is wont to be made, remember me,
and desire for me, that I may be preserved, without murmuring or repining, to the end.
It is these, and these only, that dwell near the rock,
that are fitted for a habitation in that city, the walls whereof are salvation,
and the gates stand open all the day; and there is no night there.
It needs not the sun by day, nor the moon by night;
for the Lord God and the Lamb are the light thereof.`'

At another time he said, '`I remember when on board ship,
it was a comfortable sound in the night season, to hear the watchmen say,
"`All is well.`"
I have a hope I shall know the good Pilot, to steer me into that port,
where I may with patriarchs, prophets, and apostles,
and those already gathered like sheaves of corn fully ripe,
enter into the garner of rest and peace.`'

About a month before his death, he said, '`Though many and severe trials come upon us,
yet a little while and they will be over; a short period will put an end thereto.
I have many times thought, and at this time,
how comfortable a thing it is to be able to say with confidence, as one formerly,
'`You shall guide me with your counsel, and afterwards receive me into glory.
Whom have I in heaven beside you, and there is none upon earth that I desire but you.
My flesh and my heart fails, but God is my strength and my portion forever.`"`'

Many other lively expressions dropped at different periods from him,
but his voice becoming broken,
it was with difficulty he could speak so as to be understood for a whole sentence together.
He continued sensible, and in a quiet frame to the last;
and went off as one falling asleep, the 9th day of the Fifth month, 1776,
aged nearly fifty-three, and a minister about twenty-six years.
His remains were interred in Friends`' burial-ground,
near the meetinghouse at the Friars, Bristol, the 15th of the same month.

[.asterism]
'''

JOSEPH JACKSON, of the county of York, was born about the year 1697.
He was convinced of the principle of truth about the year 1740; and, under its influence,
was concerned to bear testimony thereto, about the year 1746.
He was zealous for its promotion, dedicating most of his time to the service thereof,
having left trade to be at liberty for it,
and was diligent in attending meetings for worship and discipline,
visiting most of the meetings in Great Britain.
This concern remained with him until the summer of 1775, when, returning home,
he was visited with sickness.
In the course of his illness, a Friend asking him how he did, he replied,
'`I am very weak in body, but the Lord is good to me, as I have but little pain.
Yet I could wish to be gone, that I might be at rest;
but am willing to wait all my appointed time, until my change come,
as I am favored with peace.`'
He added, '`My time of labor is now over.
I have completed my work within the day, and am now ready to return home to my rest.
O Lord, I long to be with you; yet not my will, but yours, be done.`'

A little after he said, '`Oh! how precious is the truth;
how little is it sought after by many, for lack of knowing its value!
I have often wished, and been moved to pray in secret,
that those who have once known and witnessed it, may never depart from it;
for if they do they will lose their birth-right, and the blessing attending it;
but that they may keep it to the end.
It is the pearl of great price, and worth more than all we are possessed of in this world.
It will purchase us an everlasting inheritance in the world to come;
and this is what I have been concerned to labor for, both for myself and others.`'
It being time for going to meeting, he bade the Friends farewell, saying,
'`My mind will accompany you.`'

Sundry other Friends visiting him at different times,
found him in the same lively disposition,
often expressing his desire that all who made profession
of the truth might live under its holy government.
Such love to his friends, and peaceful serenity of mind, attended him all along,
as contributed much to the satisfaction and refreshment of those who visited him.

He quietly departed this life the 16th, and was buried the 18th of the Twelfth month,
1776, at Gildersome, in Yorkshire, aged about seventy-nine years,
and a minister about thirty years.

[.asterism]
'''

ANN MERCY BELL, of York, was born in London.
She had her education in Friends`' school and workhouse,
being admitted soon after its establishment,
and afterwards continued there as a school-mistress for many years.
Being early favored with divine visitations,
she was not only preserved from the gross pollutions of the world, but was,
in a good degree, enabled to renounce vain and youthful pleasures and amusements,
which she frequently confessed with humble thankfulness and gratitude.

In the year 1731 she married Nathaniel Bell, of York, and became a member of that meeting.
While in a private capacity,
she was well esteemed as a Friend of circumspect life and conduct,
a pattern of plainness, and therein, as well as in other respects, a good example.
At length, steadily adhering to the divine teacher in her heart,
and under the influence of the spirit of truth, she had, from a well-grounded experience,
to declare to others the way of life and salvation.
In this service she faithfully labored, according to ability received,
at home and in adjacent parts; and, in the course thereof, found drawings,
in the love of the gospel, to visit various other parts of England: also,
when engaged in family visits, she found it her concern not to overlook those who,
by misconduct, had incurred the censure of Friends.

Her labors were not confined to those of the Society of Friends; but,
in the course of her travels,
she had compassionately to call and direct people of other
denominations to the unerring teacher in themselves,
and had meetings among them in several places where no friends were settled.

In the year 1753 she found a concern to visit friends in London;
and during her stay in that city, under the influence of love to mankind,
had to exhort the inhabitants thereof, in the streets, markets,
and many places in and about London, Westminster, and Southwark,
calling them to repentance and amendment of life.
In this service she was signally furnished with ability to labor,
to the tendering many of their minds, and acknowledgment of her goodwill to them;
and such was the ardor of her mind, and the flowing forth of love to them,
that she frequently preached three or four times a day, in different parts.
On her return home she had to acknowledge that she was favored with the return of peace;
which she esteemed a sufficient reward for the various exercises
which attended that laborious service.

Towards the conclusion of her time, she expressed her fervent desire,
that he who had been her morning light might be her evening song;
which there is no doubt she mercifully experienced.
Being suddenly seized with an apoplectic fit,
at the approach of the stroke she was heard to say, '`Sweet Jesus,
'`with some other expressions, which,
through the hurry and surprise those about her were in, are not now remembered.

In a few hours after, she departed, without sigh or groan, the 30th of the Twelfth month,
1775; and was interred in Friends`' burial-ground in York, the 4th of the First month,
1776; aged about sixty-nine, and a minister about thirty years.

[.asterism]
'''

REBECCA SHEWELL, daughter of Edward and Sarah Shewell, of Camberwell, in Surry,
was a child adorned with meekness, innocence, and humility; dutiful to her parents,
and affectionate to her brothers and sisters; a lover of the servants of Christ,
fond of reading the Holy Scriptures, and often so tendered in reading them,
that those who were present and heard her, were edified by it.

Being taken with an illness, which continued for twelve months,
she bore it with much patience and resignation of mind.
She was not confined to her chamber more than about three weeks;
in which season she told her mother, that she believed she should die,
and requested her to pray for her; which her mother being enabled to do,
it seemed much to ease her mind.
A few days after, she said, '`I have often been desirous of recovering;
but I find desires will not do,
I must have patience;`' and expressed her thankfulness
to her sisters for their tender care over her;
and said, '`O, that I could keep from groaning, that it might not make them uneasy.`'
She signified her apprehensions that her complaint increased;
not that she wished to live, but it was a fear she should not obtain future bliss.
One time some remarks being made to her on the pleasing things of this world,
and what she might enjoy, she answered, '`I have no desire for these things.
I had rather die and go to Christ.`'
She was frequent in prayer by herself, and often wished to be left alone,
and the curtains to be drawn about her.
Her sister observing her to be in much pain, asked her to take something; she answered,
that none of these things would do her good;
but it being observed the Lord could do her good, she answered, '`He can,
but none of these things can.`'

Her mother asked her, the day before she died, if she thought she should die; she said,
'`Yes;`' she had rather die than live, but was afraid she was not good enough.
Her mother encouraging her,
and intimating that she believed there was a mansion prepared for her;
the child expressed her willingness to go to it, desiring her mother to pray for her;
and the mother answering, '`I do; do you do it yourself?`'
the child said, '`I do, I do;`' and being asked if it was with outward words, she replied,
very fervently, '`No, no, in my heart.`'
She also intimated that she was quite easy; and frequently bade them farewell.
Soon after, her speech failed her; but she appeared to retain her senses to the last.

She departed, without sigh or groan, the 17th of the Second month, 1777,
aged only eight years and four months.

[.asterism]
'''

ANN LEAVER, daughter of John and Mary Leaver, of Nottingham, being taken ill,
signified her belief that her time would not be long, and said,
that the prospect of eternity was awful;
and that though she had not committed any bad thing, yet she had found it difficult,
when at meeting, to get to that steady watchfulness and settled composure she longed for.
She expressed thankfulness for the opportunities
she was sometimes favored with in the family,
in their sitting together at home; and added,
that she hoped the Almighty had blotted out her transgressions;
and prayed that she might be enabled to bear with patience
the trying dispensation she had to pass through,
which she believed was allotted for her further purification;
and begged for a certain evidence, that her conclusion might be happy,
and her passage easy; which was mercifully granted.

In the course of her illness she dropped many expressions,
which show that she looked forward to a glorious inheritance;
some of which are as follow.

After having given her sisters some tender advice, she said,
'`How awful to look at eternity,
and few young people in time of health think so much
of their latter end as they ought to do,
though they have as much cause as those more advanced, having no more certainty of life.`'
She plainly saw that those of a cheerful disposition
were in danger of going too far in company;
adding, '`Those who are taken away in youth escape many snares and temptations,
that such as live longer are in danger to be hurt by.`'
Several times she expressed her humble thankfulness for the last week`'s illness, saying,
that it had been a profitable, though painful, dispensation to her.
At another time, when in great pain, she spoke thus: '`O,
it is hard work! how needful when in health so to live as to be in readiness!
for it is enough to struggle with the pains of the body.`'
She also said,
that she plainly saw it was as necessary for us to watch over our thoughts,
as words or actions; desiring the prayers of those present,
that she might be supported under her affliction with patience.

After a painful day, being in the afternoon favored with stillness and composure of mind,
she thought herself going;
and took a solemn farewell of her near connections and friends;
desiring all present might make due preparation for that solemn and awful time,
when the soul must be separated from the body; saying,
that she did not expect to have had anything of that sort to deliver,
but as it came into her mind, she dropped it; and added, '`I want to be gone,
I seem to have no business here.`'
Her pain returning, she found she should not go so soon as she expected;
but begged for patience, saying, '`The Lord`'s time is the best time.`'

The day she died, the doctor proposing to lay on some blisters,
she said she was out of the reach of blisters; '`No mortal can help me;
there is but one who can help me;`' yet she was willing to submit,
if her father desired it.
But she added, '`O, that we might be a little still, and sit comfortably together!`' Being,
in some degree, free from her sharp agonies for nearly an hour, she said,
'`We are pure and comfortable now;`' and talked pleasantly, saying,
that the unwearied enemy had been endeavoring to trouble her, but she found him a liar.

The same evening she said, '`No one can think what I feel;
but if it is to purify me for an admittance into that holy place,
where no impure thing can enter, I am willing to bear ten times more; and, I hope,
with a tolerable degree of patience too.
I hope I am not impatient; but really the conflict is so sharp, at times,
that I cannot forbear crying out.
O Lord, keep me, keep me: my God help me, and please to release me this night.
I long to be gone.
Although I have had many pleasant prospects in view, I have resigned them all,
and would not return again to the world for any consideration.`'
Much more she said to the same effect.

She at times lamented that people, advanced in years,
should be so closely attached to the world, as too many appeared to be,
saying that they must soon leave it.

Her mother retiring to supper, she soon sent for her again, and told her,
with a sweet composure and calmness, '`My dear mother, I am now going,
and would have my father and sister to come and sit with me a while,
and take a final leave;`' adding, '`My prayer is granted;
for I have earnestly begged I might not see the light of another morning.`'
She took a solemn and affectionate leave,
saying that she wondered she could part with her near connections so easily; '`For,
'`said she, '`I have no tears to shed.
It is not hardness of heart, for I know I love you all as well as ever;
but it is to me an earnest that I am going to something greater.`'
She desired her affectionate love to many of her absent relations,
and particularly to some nearly her equals in years, saying,
'`Let them be admonished from me how they spend their time.`'

After some time, she said, '`It is all over, and I am perfectly happy.
I have no pain.
The conflict is at an end.
Farewell, farewell;`' and pausing a while, she said,
I am now going to join saints and angels,
and the spirits of just men made perfect;`' adding, '`I have no more to say.
I would have you to leave me, for I am going to sleep.`'
Then laying her head quietly on the pillow, she expired, without a sigh or groan,
the 22nd of the Third month, 1777, aged twenty years.

Her corpse was carried to Friends`' meetinghouse in Nottingham; and,
after a solemn meeting, was interred in their burial-ground there.

[.asterism]
'''

MARY BUNDOCK, of Manningtree, in Essex, was religiously inclined from her childhood;
and as she grew up delighted in the company of solid friends; endeavoring,
amidst the various trials and exercises to which her situation exposed her,
to walk in simplicity and awful fear before the Lord,
who graciously preserved and prepared her for service.

About the thirtieth year of her age she appeared in public testimony;
in which she had the unity of Friends, and continued to labor therein,
both at home and abroad;
frequently traveling into different parts of this nation in the service of truth.

She was of a grave deportment, and of sound judgment,
earnestly concerned to discourage all undue liberties.
The benevolence of her mind appeared in many instances towards her neighbors,
by seasonable advice, and frequently administering to their necessities.
She was a diligent attender of the meeting she belonged to,
in which her travail in silence was helpful and comfortable,
till prevented by bodily infirmities.

In her last illness, which was at times very painful,
she uttered many comfortable expressions.
A friend who came to visit her, saying, '`She is sensible;`' she replied, '`Yes,
I am sensible who has been my preserver from the earliest time of my life,
and has helped me along, and supported me in weakness,
so that I have been revived through his goodness, from time to time.
There is but one power to help.
The last time I attended a public meeting,
it was the fervent desire of my mind for my friends, as well as for myself,
that we might seek to experience this only help near.`'
To another friend she said, '`Dear friend, trust in the Lord;
he never leaves his little ones; no, never, never.
Though outward afflictions happen to the righteous, as well as to the ungodly,
yet light is sown for the righteous, and gladness for the upright in heart.`'

It was no small cause of comfort to observe the lively frame of her spirit,
by which it appeared that, though her outward strength decayed,
her inward strength was renewed day by day.
She departed this life at Colchester, on the 8th of the Tenth month, 1778,
and was buried the 15th of the same, in Friends`' burial-ground there; aged eighty-three,
and a minister about fifty-three years.

[.asterism]
'''

CUTHBERT WIGHAM, of Cornwood, in Northumberland,
was educated in the way of the Church of England,
and was in his youth addicted to many youthful follies, and some gross evils.
But it pleased God, who is rich in mercy towards sinners, to call him by his grace,
and reveal his Son in him; whereby, about the year 1734,
he was convinced of the blessed truth, as it is in Jesus, and received it.

Being thus brought into deep judgment for his transgressions,
and sensibly feeling God`'s wrath poured forth,
he dared no longer follow his old courses and ways of living,
nor dared longer associate with his old companions,
but joined in society with the people called Quakers; and,
several of his neighbors being about the same time convinced of the truth,
he was made instrumental in settling a meeting in Cornwood, in the year 1735.

About a year after his convincement, a dispensation of the gospel was committed to him,
in which he labored faithfully according to the ability given.
His ministry was not with the enticing words of man`'s wisdom,
but in the power and demonstration of the spirit;
and he often had to magnify that power that had redeemed
his soul out of the horrible pit of everlasting darkness.
Having known, as he expressed, the terrors of the Lord for evil-doing,
he was earnestly engaged to warn others to take heed to their ways,
lest they should bring themselves under such terrors as he had felt, but now,
through infinite mercy, was released from,
and come to the enjoyment of that peace which the world cannot give or take away.

In the year 1753 he took a journey on foot, accompanied by a friend,
and had many meetings among a people who were strangers to Friends and their principles;
and also visited various other parts of the North, and some parts of Scotland;
having meetings in his way at several places where no Friends resided.
He was as a nursing father to the young convinced in that day;
and open in love to receive all in whom any tenderness appeared,
whether their station in the world was high or low.

He met with some exercises and cross occurrences in his own family,
which grieved him much, yet he was favored to outlive all his sorrows.
Though, through age and infirmity of body, his natural faculties were much impaired,
yet his mind appeared to be redeemed out of all evil;
and he was brought to the innocency of a little child.
Being perfectly sensible of his approaching dissolution,
he seemed to meet it with cheerfulness, saying,
'`I will wait in patience till my change comes.
Oh! it is a fine thing to be ready;`' and, indeed,
the patience and resignation which appeared in his countenance
evidently denoted the calmness and serenity of his mind.

Thus, in innocency, he finished his course the 9th of the Second month, 1780,
and was buried in a piece of ground given by himself for a burial-ground, in Cornwood;
aged about seventy-seven years, and a minister about forty-three years.

[.asterism]
'''

JONAH THOMPSON, of Compton, near Sherborne, in Dorsetshire, was born near Penrith,
in Cumberland, about the year 1702.
He was grandson of Thomas Lawson, who, in the early times of the Society of Friends,
was a zealous advocate for their principles, as his writings testify.
His parents dying while he was young,
he came under the care of a relation not in religious fellowship with Friends;
who left him entirely at his own liberty respecting his attendance at places of worship,
and the choice of his religious profession.
But being, at that early period, impressed with divine fear,
and a sense of the nature of true religion, he was mercifully preserved.
Though he had little or no expectations from his relations,
or view of subsistence but by his own industry, yet,
relying on the protecting care of Providence, he had the fortitude,
at about the age of fourteen,
to withstand offers which were repeatedly made him of an education at school,
and at the university,
with a view to qualify and provide for him as a minister of the established worship.
This is the more remarkable, as his mind was strongly attached to literary pursuits.
He has since frequently remarked,
that he was then fully convinced of the impropriety of such a mode of making ministers;
believing none could be truly so, but those who were of Christ`'s making,
by the call and qualifications of his holy Spirit.
He therefore put himself apprentice to a Friend, at Kendal, in Westmoreland,
to learn the trade of a weaver, with whom he faithfully served his time.
At leisure hours he prosecuted his studies,
and acquired such a share of learning as qualified him to
undertake the care of a school at Grayrigg in that county.
From there he removed to Yatton near Bristol; and on his marriage a few years after,
he settled in Dorsetshire, where he mostly resided the remainder of his time.

There is reason to believe that he was, while at Grayrigg,
made sensible of a call to the work of the ministry,
on that foundation which in early life had appeared to him so necessary;
and for which there is no doubt but he was in good measure duly prepared and qualified,
through the operation of grace upon his own heart;
and he soon became an able minister of the gospel of Christ.
In the year 1728, he paid a religious visit, in company with William Longmire,
to most of the counties in this nation,
to his own peace and the satisfaction of his friends.

In the year 1750 he visited the meetings of Friends in America,
where his labors of love were generally acceptable; and some years after his return,
he embarked again for the same continent, on which, for some time,
he took up his residence.

After his second return from America, he resumed the employment of a schoolmaster;
and travelled no long journeys from home,
but was a diligent attender of the meeting he belonged to,
and frequently attended the yearly meeting.

His ministry was acceptable to persons of various denominations,
being often led to declare the truths of the gospel with great calmness and deliberation,
and with such convincing clearness as frequently to occasion
many to acknowledge the truth of his doctrine.

For some time before his decease he frequently expressed
his apprehensions of his approaching end,
and particularly on a public solemn occasion, when,
after a clear intimation that the time of his departure was at hand, he added,
in nearly the following words: '`I may say with humility,
and a degree of Christian boldness, I have fought a good fight,
I have finished my course, I have kept the faith;
henceforth there is laid up for me a crown of righteousness incorruptible in heaven.`'

In his last illness he remarked to some friends who visited him,
that he had lived long enough, his services being over, and had nothing to do but to die,
having a well-grounded hope that the change would be to his advantage.
That on reviewing his past life,
he could find but few instances in which he could have acted better,
was he to live his time over again; and that he had a great advantage during his illness,
in having a quiet, easy mind, and no accuser there.
For a near friend and fellow-laborer in the gospel,
who took leave of him a few days before his departure,
he wished a portion of the same peace in the decline of life which he then experienced.

He was preserved in great composure and resignation, and, for the most part,
retained his faculties to the last; and on the 21st of the Fifth month, 1780,
quietly departed this life.
His body was interred in Friends`' burial-ground at Yeovil,
on the 27th. Aged nearly seventy-eight, and a minister about fifty-five years.

[.asterism]
'''

ROBERT HAYWARD, of Suffolk, in the early part of his life,
embraced the tendering visitation of the day-spring from on high, and,
according to the discoveries thereof to his understanding, gave up in obedience;
and being prepared to declare what God had done for his soul,
he invited others to taste and see how good the Lord
is to all those that put their trust in him.

His labors were often favored with general acceptance where his lot was cast,
which was for the most part confined to the county where he dwelt, and places adjacent.
He was industrious in his business, a plain and inoffensive man in life and conduct,
endeavoring by precept and example to be instrumental in promoting the welfare of all.

This continued to be the humble engagement of his mind to his conclusion,
in which the same godly simplicity seemed to attend him.

During the time of his illness he was favored with exemplary patience and resignation,
which were the means of his support under the excruciating pain which at times he felt;
and he would frequently say, '`The Lord is my shepherd, I shall not want.
Grace, nor truth, nor any good thing,
will he withhold from them that put their trust in him.
I find him near to help me in this the time of my affliction,
and nothing to stand in my way.
Oh, what a comfort it is to those that have done their day`'s work in the daytime.
I have endeavored to discharge my duty to the best of my knowledge.
I feel peace, sweet peace, such as the world cannot give, nor take away.`'

At times, many Friends coming to see him,
he frequently had a word of encouragement to drop among them and those about him,
and to tell what God had done for his soul.
He likewise had several comfortable opportunities with his children and grandchildren.
His earnest desires and prayers were put up for the young and rising generation,
that they might be preserved in the fear of the Lord.

The nearer the time of his departure approached, the stronger his memory grew;
and he seemed to experience more of the incomes of divine favor; and,
like a well-watered garden, he was fresh and green to the last.

A few hours before his close he had a fainting fit, and those about him thought him gone;
but after a while he revived, and, like good old Jacob, gave his children his blessing,
and said that he should sleep that night in the arms of his heavenly Father.

He was sensible to the last, and departed this life with great composure,
and full assurance of happiness, being full of days and full of peace,
the 24th of the Tenth month, 1780, and was buried in Friends`' burial-ground at Lynn,
in Norfolk; aged eighty-five years, and a minister nearly fifty years.

[.asterism]
'''

ELIZABETH HOLME, of Newcastle-upon-Tyne, was the daughter of Anthony and Dorothy Wilson,
and born at Highwray, near Hawkshead, in Lancashire.
She was favored with a religious education,
and in her youth her mind was impressed with the fear of God.
She was often drawn into retirement and a watchful state of mind.
Thus she attained a growth in religious experience,
and about the thirty-fourth year of her age,
was concerned to bear testimony to the efficacy of
that divine principle +++[+++the Spirit of Christ]
which she herself had felt: in which service she grew, and,
in company with Lydia Lancaster,
visited the meetings of Friends in Ireland and Scotland.

After her marriage with Reginald Holme, she visited various parts of England;
and in her station of a wife, she conducted herself with prudence and propriety; and,
being preserved in watchfulness,
allowed not her temporal concerns to hinder her services in the church.

Her last illness was short, scarcely ten days, most of which time she kept her bed,
appearing to be under great bodily weakness, but not much pain,
and bright in her understanding to the last.

To a friend who came to see her, at parting she said,
'`Remember me affectionately to your husband,
and let him remember me when he draws near +++[+++the throne of grace],
that I may pass through the valley of the shadow of death,
and be enabled to put off the robe of mortality and put on immortality, full of glory.
I trust to enjoy a part of that portion that is laid up for the faithful;
for such I have endeavored to be, according to the ability given.
I have nothing stands before me.
I do not clearly see that this is the finishing stroke,
but every stroke draws nearer and nearer.
In this I have no will, but stand ready, and in patience wait till his own time.`'

Her daughter sitting by her, she said, '`Oh, sweet peace,
what an enjoyment it is in this weakness.
I have discharged my duty to God and his people in this place.`'

A near friend calling to see her, he said, '`You have labored faithfully among us,
and we shall have a great lack of your company.`'
She said, '`I have so.
I hope it may be as bread cast on the waters, that may arise many days hence.`'
At another time she said, '`I thought I had been going,
but it seems as if the people held me, not so willing to let me go as I am myself.
Oh, that every link of this chain was broken,
that I might lie down in peace forevermore.`'

The morning before she died, being Fifth-day, her daughter sitting by her, she said,
'`I may say with king Hezekiah, the hand of the Lord is upon me,
I am waiting for my change.`'
After asking, '`Is your husband gone to meeting?`'
she added, '`I wish it may be a refreshing season to him,
and all the living members assembled this day, with whom my spirit unites,
and craves the canopy of divine love may overshadow their minds,
and strengthen for the work`'s sake.`'
After a pause, she said to her daughter, '`My dear,
your company is precious to me in this affliction, and your husband`'s,
which I dearly love.
O Lord, let us taste of your goodness, that we may be refreshed.`'

She quietly departed this life the 9th of the Second month, 1781,
and was interred on the 12th, in Friends`' burial-ground in Newcastle:
aged nearly seventy-eight, and a minister forty-four years.

[.asterism]
'''

THOMAS GAWTHORP, of Preston Patrick, in Westmoreland, was born of honest parents,
of our religious profession, at Skipton, in Yorkshire, in the year 1709.
His father dying when he was young, he was put apprentice to a man near Leeds,
not of our profession; and, meeting with severe treatment during his service,
to free himself therefrom, he was induced, towards the conclusion of the term,
to enlist in the army, in which he continued about five years.

While in that service, being, by permission, on a visit to his relations at Skipton,
he attended a meeting there, at which he was effectually reached,
by the powerful testimony of Mary Slater; and from that time attended Friends`' meetings,
when opportunities offered.
Though he labored under great exercise of mind on account of his situation,
yet he was not free to have his discharge purchased,
fearing how he might stand his ground.
One of his officers, observing his dissatisfaction with the way of life he was in,
made him an offer of his discharge,
on his returning the money he had received when he enlisted, which,
after solid consideration, he accepted;
and paying the money so soon as he had earned by his industry sufficient for that purpose,
he obtained his discharge, and returned to Skipton, the place of his birth.

During his residence there, which was not long, he came forth in public testimony.
From there he removed to Kendal,
and soon after accompanied a friend on a religious visit into Scotland.

After his return, he married a young woman of a respectable family,
belonging to Preston Patrick monthly meeting, and settled within the said meeting,
a few miles from Kendal, where he continued to reside when at home,
to the time of his decease.

His mind being devoted to the service of his great Master,
and obedient to the manifestations of +++[+++the spirit of]
truth, he grew in the gift received, and became a deep and able minister of the gospel;
diligently laboring in the openings of life,
for the exaltation of truth in the hearts of the people; unto whom,
from an inward sense of their states, he had often close, pertinent doctrine to deliver;
not in the wisdom of man, nor the eloquence of words,
but in the simplicity of the gospel, and with the demonstration of divine authority,
reaching the witness in the hearts of many.
He, nevertheless, often found it his place not to feed, but to famish,
the eager desire in the minds of the people after words;
by setting them an example of humble and awful worship in solemn silence.

He was exemplary in his diligent attendance of our religious meetings,
and in a circumspect conduct among men in the necessary
management of his outward concerns.

He was frequently engaged to leave his family and worldly affairs,
to pay religious visits to Friends in different parts,
having several times visited several parts of England, Scotland, and Ireland.
He also visited Friends in America four different times.
In all these labors of love we have reason to believe he discharged his duty honestly,
and was made instrumental in the great Master`'s hand
to the stirring up the pure mind in many.

He was also frequently engaged in visiting Friends`' families,
and enabled to speak pertinently to the states of individuals.
In his third visit to America,
he was particularly concerned on account of the hard
and suffering state of the poor negroes,
and we believe his labors on behalf of that oppressed people were of service.

Upon his return from his last visit to America,
he was much reduced in his bodily strength; but his mind seemed centered in peace,
being covered with innocency and sweetness, and patiently waiting for his change;
having an evidence that his day`'s work was nearly accomplished.

He attended the meeting to which he belonged, under great bodily infirmity,
though at a considerable distance, until he was wholly confined.
He departed this life the 29th of the Ninth month, 1781,
and was interred the 4th of the Tenth month following,
in Friends`' burial-ground at Preston Patrick; aged about seventy-one,
and a minister forty-seven years.

His friends of Westmoreland, in their testimony concerning him, say,
'`We doubt not but his conclusion was a happy release from the conflicts
and deep exercises attending his pilgrimage here;
and that he is gathered to the just of all generations,
to reap the reward of his labors.`'

[.asterism]
'''

MABEL WIGHAM, a member of Newcastle meeting, was the daughter of Cuthbert Wigham,
of whom an account has been given,
and was about six years of age when her parents were convinced,
and a meeting settled at Cornwood, the place of her father`'s abode.

In her youth she discovered a warm affection for Friends, and,
as she expressed to some of her near friends, tender desires were raised in her mind,
after an inward acquaintance with that life and virtue which
she was favored to hear livingly testified of,
by her worthy father and many other Friends,
who at that time were concerned to visit that meeting.
Being in a good degree preserved in an innocent frame of mind,
and attending to the reproofs of instruction,
that she might be favored to find the way of life,
she was often drawn into solitary places to pour forth her supplications before the Lord,
that he would in mercy, make himself known to her as the good Shepherd of Israel;
whose voice she might hear and distinguish from the voice of the stranger.

The fruit of her humble,
seeking state of mind soon discovered itself in her
growth in ardent love to truth and Friends,
and in her great desires to attend our religious
meetings and opportunities of worship at home,
as also monthly and quarterly meetings.
In all these she was a good example, by her silent, humble waiting upon the Lord;
where often, in much brokenness of spirit, she dropped her silent tears,
and the good effects thereof were manifested in the reach it had on others present.

A few years after her marriage to Thomas Wigham, of Limestone, in Cornwood,
she appeared in testimony in a few words, which were sweet and savory.
By humbly depending on the Lord for renewed strength,
she came to experience a growth in her gift; and was drawn forth to visit the churches,
for which service she was qualified in a particular manner,
being truly a daughter of consolation.
For notwithstanding her temporal concerns, having a large family,
and being only in low circumstances, she firmly trusted in the Lord who called her,
and freely left all and followed him; often saying, '`The Lord is my Shepherd,
I shall not want.`'

After her return from visiting the meetings in London, about the Sixth month, 1779,
her health became impaired, and a gradual decay took place,
so that she was confined for many weeks.
Her strength reviving, she got out to meetings again for some time,
where she had close and deep service; and, for change of air,
she went into her native county,
which gave her an opportunity of visiting her near relations,
much to their satisfaction and her own peace and comfort,
and of taking a last farewell of her friends and neighbors in that county.
After her return from Cornwood, her disorder made great progress, and wasted her fast,
and she was not able to get to meetings.

During her confinement, several of her friends went to visit her,
in which many precious opportunities were witnessed,
to the melting and humbling their spirits before the Lord,
so that they could truly say the Prince of Peace was there.

She bore her illness with exemplary fortitude and resignation;
and with a cheerful composure she mentioned her dissolution, and often said,
'`The way seems clear, and I have no doubt, if the last conflict was over,
but I shall be admitted to my Master`'s rest, and the joy of the Lord.`'

Much seasonable and tender advice she gave to her children,
encouraging them to seek and serve the Lord in their youth; and that,
if they were chiefly concerned to attain heavenly treasure,
the Lord would provide for their bodies; adding, '`Oh what satisfaction and peace I feel,
in having dedicated my youthful days in seeking the Lord,
and freely spending myself in his service.`'

As she lived, so she died; in love, peace, and unity with her brethren.
She departed this life, without a sigh, the 9th of the Eleventh month, 1781;
and her remains were interred at Newcastle-on-Tyne, the 13th of the same; aged fifty-two,
and a minister twenty-five years.

[.asterism]
'''

ROBERT PRYOR.
Expressions of the late Robert Pryor, of London, committed to writing by his brother,
John Pryor, who attended him in his last illness.

For some months before his death, his usual state of health was altered,
and signs of infirmity appeared, which continued to increase upon him,
and at length terminated in a settled decline.

One day, speaking to me about his will,
he said that some might think he had given a great deal away from his children;
but he was more afraid of their having too much than too little,
as he had seen great riches do much hurt, especially in our Society.
He wished his children to be brought up plainly,
and the boys to be put apprentices to sober, honest Friends.

One time, on taking leave of his son Robert, who had been up to see him,
he desired him to be a good boy, and to speak the truth,
and to keep to the plain language, and not to associate with bad boys,
but choose the best for his companions.
At another time he said, '`Brother, I hope I do not repine,
though I am afraid lest I should.
I have my low times, lest it should not be well with me.
Sometimes I think it may be the enemy that strives to disturb me.`'
Speaking of his being resigned to the will of Providence, he said, '`What signifies it,
whether I die now, or twenty years hence?
though if I look back, my time appears to have been very short.`'

One day he said, '`Dear brother, do not be too anxious after the things of this world,
for my inordinate desire to accumulate wealth, has been a heavy burden to me:
no one knows what I have suffered on that account.`'
He further said, that his having been so solicitous after the world,
had made him but a dwarf in religion;
and that if it had pleased the Lord to spare his life,
he thought he should have found it his place to endeavor
to be a more useful member in the Society;
and to expend more of his income in charitable uses: that the love of money,
and an inordinate desire after wealth, had pierced him through with many sorrows.

One afternoon his nephew came to ask him how he did: upon his taking leave,
after sitting some time in silence, he desired him to keep constantly to meetings,
to love friends`' company, and not to launch out into the vanities of this world,
or associate with those that were likely to draw him aside;
reminding him that there would be an end, which would overtake us all;
and that we ought always to be prepared.

One time, going to bed, he desired me to shut the door,
saying that it was his desire to supplicate, which he did on his knees,
begging the Lord not to leave him, but be with him in the trying moment,
and grant him a safe and easy passage into his glorious kingdom;
hoping he would accept his late repentance, which he trusted was sincere,
though upon a dying bed.
The next morning, as I stood by his bedside, he spoke to me as follows: '`Brother,
I have been in a quiet sleep, and had a comfortable vision.
I thought I had a foresight of that glorious kingdom, where all is peace, serene,
and quiet!
Such a prospect as I had never before seen, and such as no tongue can express,
the glory of that kingdom!`'

At another time, expressing the satisfaction he had in my being with him,
he desired that I would not leave him when the event happened;
and requested to be buried in a plain way, and to be carried into the meetinghouse;
as he had seen the use of those meetings.

One morning asking him if he was free from pain, he answered,
'`that he felt only violent oppression; that when the Lord pleased to release him,
he believed he was ready; but hoped to wait the appointed time with patience: adding,
he was as clear in his intellect as ever.
What a favor! and that he was permitted to get home, and settle his affairs,
was a great favor; but above all, that which he saw in his vision!`'

He said that it appeared clear to him,
that the less Friends talked about news and interfered in politics, the better.
He thought they did not belong to them.
He used to read the newspapers when at Bristol, to divert himself; but left it off,
finding his time better employed in reading the Scriptures.

On taking a little refreshment, he said, '`What a favor it is thus to be waited upon,
and to have everything this world can afford,
to alleviate or still the pains of the body!
We have so much the more to be accountable for.`'
One evening, upon my asking him how he did, he said that he lay pretty easy,
and was quiet in his mind.
He thought he had a well-grounded hope, that all would be well with him;
and that if it should please the Lord to take him into his glorious kingdom,
what a happy change it would be!

One evening he said, that he did not know what to think of that night.
He had prayed so often to be released, he was ready to fear lest he had offended.
He should be very thankful to be released from his sufferings; yet hoped he could say,
as that good man Isaac Sharples had expressed in prayer, at his bedside,
"`Your will be done, O Lord, in earth, as it is done in heaven.`"
After this he continued remarkably still and calm, with much serenity in his countenance,
taking little notice, but appearing wholly fixed on the greatest of all objects.

On the seventh day before his decease,
he noticed those about him more than he had done some days before;
and his sister coming in the afternoon, whom he had often expressed a desire to see,
he mentioned it to me, as a great favor, to be permitted to see all his near friends;
which being done, it seemed as if every wish was gratified.

He continued in the same calm, composed state of mind, growing weaker and weaker,
yet sensible to the last; having his desire granted of an easy passage, I have no doubt,
into that glorious kingdom, of which he expressed he had a foretaste.

He departed this life at his house in Budge-row, the 16th of the Seventh month, 1782,
aged about thirty-seven years; and, after a solemn meeting at Gracechurch-street,
was interred in Friends`' burial ground, Bunhill-fields, the 21st of the same.
