== Preface

It was said by our blessed redeemer that, "`They who Worship the Father,
must worship Him in Spirit and in Truth.`"^
footnote:[John 4: 24.]
Now the object of this work is to explain, in a simple and familiar manner,
how this only true worship can be acceptably performed, and inward,
spiritual Prayer rightly attained.
Few authors have written with greater clearness thereon,
than those from whose works this little volume has been chiefly compiled; they,
therefore, have been preferred: at the same time,
it has been thought necessary to simplify, and render more intelligible,
some of their terms, in order that they may be more generally understood.

While some, into whose hands this little treatise may fall,
may receive it as a Messenger of glad tidings, there will, doubtless, be others,
who may not feel disposed to place much dependence on the simple manner here pointed out,
of drawing near to their Creator; let such, however,
not judge according to the appearance; but, laying aside all reasoning thereon,
in humility and simplicity make trial of it, and feel for themselves, whether,
what is herein stated will not prove to be something
more than an empty dream of the imagination,
or cunningly devised fable.
And, if they do this in sincerity of heart, they will soon have to acknowledge,
to their great consolation, that these are indeed substantial, efficacious,
and incontrovertible Truths;
and that this is the true way to become purified from our many defilements,
to be instructed in heavenly mysteries, to taste of the wine of the kingdom,
and to partake of that bread which nourishes up unto everlasting life.

[.centered]
=== Advertisement.

In the former edition of this work some of the quotations
from Scripture were from the Vulgate Version;
none are now admitted but such as are taken from the authorized English Version.
