== Chapter 1.

The Spirit of God Dwells in the Heart of Man

It is certain from Scripture that the Spirit of God dwells within us,
that a "`manifestation of this Spirit is given to us to profit withal,`"^
footnote:[1 Corinthians 11:7.]
and that this is "`the true Light,
which enlightens every man that comes into the world.`"^
footnote:[John 1: 9.]
"`This is the Grace of God, which brings Salvation, and which has appeared unto all men;
teaching us, that denying ungodliness and worldly lusts, we should live soberly,
righteously, and godly, in this present world.`"^
footnote:[Titus 2:12]
But we make too little account of this internal Teacher, which is the soul of our soul,
and by which only we are able to form good thoughts and desires.

God ceases not to reprove us for evil, and to influence us to that which is good;
but the noise of the world without, and of our own passions within, deafen us,
and hinder us from hearing Him.

We must retire from all outward objects,
and silence all the desires and wandering imaginations of the mind;
that in this profound silence of the whole soul,
we may hearken to the ineffable voice of the Divine Teacher.
We must listen with an attentive ear; for it is a still, small voice.
It is not indeed a voice uttered in words as when man speaks to his friend;
but it is a perception infused by the secret operations
and influences of the Divine Spirit,
insinuating to us obedience, patience, meekness, humility,
and all the other Christian virtues,
in a language perfectly intelligible to the attentive soul.
But how seldom is it that the soul keeps itself silent enough for God to speak!
The murmurs of our vain desires, and of our self-love,
disturb all the teachings of the Divine Spirit.
Ought we then to be surprised, if so many persons, apparently devout,
but too full of their own wisdom, and confidence in their own virtues,
are not able to hear it;
and that they look upon this internal Word as the chimera of fanatics?
Alas! what is it they aim at with their vain reasoning?
The external word, even of the Gospel,
would be but an empty sound without this living and fruitful Word in the interior,
to interpret and open it to the understanding.

Jesus Christ says: "`Behold, I stand at the door, and knock--if any man hear my voice,
and open the door, I will come unto him, and sup with him, and he with me.`"^
footnote:[Revelation 3:20.]
His knocks are the monitions of His Spirit; which touches us, and operates in us.
And to attend to these monitions and follow them, is to open unto Him.

God speaks in impenitent sinners; but these,
engrossed in the eager pursuit of worldly pleasures,
and the gratification of their evil passions, are not able to hear Him.
His word with them passes for a fable.
But woe unto those who receive their consolation in this life.
The time will come when their vain joys shall be confounded.

He speaks in sinners who are in the way of conversion:
these feel the remorses of their conscience, and these remorses are the voice of God,
which upbraids them inwardly with their vices.
When they are truly touched, they have no difficulty to comprehend this secret voice,
for it is this that so pierces them to the quick.
It is that two-edged sword within them, of which St. Paul speaks,
which goes even to the dividing of the soul from itself:
"`The word of God is quick and powerful, and sharper than any two-edged sword;
piercing even to the dividing asunder of soul and spirit, and of the joints and marrow;
and is a discerner of the thoughts and intents of the heart.`"^
footnote:[Hebrews 5:12.]

He speaks in persons enlightened, learned, and whose life, exteriorly regular,
seems adorned with many virtues; but often these persons, full of themselves,
and of their knowledge, give too much ear to themselves to listen to God.
God, who seeks only to communicate himself,
finds no place (so to speak) where to introduce himself into these souls,
that are so full of themselves, and so overfed with their own wisdom and virtues.
He hides His secrets from the wise and prudent, and reveals them to the low and simple:
our blessed Redeemer said: "`I thank you, Oh Father,
Lord of heaven and earth! because you have hid these things from the wise and prudent,
and have revealed them unto babes.`"^
footnote:[Matthew 11:25.]
It is with the humble and child-like that He delights to dwell,
and to disclose to them his ineffable secrets.
It is these who are more peculiarly qualified for
receiving in greater measure the gift of faith;
for, being willing that the pride of Reason should be laid in the dust,
they obstruct not the entrance of this gift by their vain arguments;
but believe with simplicity and confidence.
