== Chapter 5. Method of Attaining to True Prayer

The sort of prayer to which we have alluded, is that of inward silence; wherein the soul,
abstracted from all outward things, in holy stillness, humble reverence,
and lively faith, waits patiently to feel the Divine Presence,
and to receive the precious influences of the Holy Spirit.
And when you retire for this purpose, which should be your frequent practice,
you should consider yourself as being placed in the presence of God,
looking with a single eye to Him, resigning yourself entirely into His hands,
to receive from Him whatsoever He may be pleased to dispense to you; calmly endeavouring,
at the same time, to fix your mind in peace and silence;
quitting all your own reasonings, and not willingly thinking on anything, how good,
and how profitable soever it may appear to be.
And should any vain imaginations present themselves, you should gently turn from them;
and thus faithfully and patiently wait to feel the Divine Presence.

If, while you are thus engaged, something of inward stillness,
or a degree of the softening influence of the Divine Spirit, is mercifully granted you,
you should prize these manifestations of the Presence of God in your soul,
and be carefully, and reverently, attentive thereto; being cautious, however,
not to endeavour to increase them by your own activity; for, by so doing,
you will draw the mind off from that state of holy stillness, and humble watchfulness,
which you should be solicitous as much as possible to maintain:
by fanning the flame there is a danger of extinguishing it,
and thus depriving the soul of that nourishment which was intended for it.

A lively sense of the Presence of God,
will extricate us speedily from numberless mental wanderings,
remove us far from external objects, and bring us near unto our God,
who is only to be found in our inmost centre; which is the Temple wherein he dwells.^
footnote:[1 Corinthians 3:16.]
And when we are thus fully turned inward,
and warmly penetrated with a sense of His Presence, we should in stillness and repose,
with reverence, confidence, and love, permit the blessed food of which we have tasted,
to sink deep into the soul.

The prayer of inward silence is the easiest and most profitable path,
because that with a simple view, or attention to God,
the soul becomes like a humble supplicant before its Lord;
or as a child that casts itself into the safe bosom of its mother.
It is also the most secure,
because it is abstracted from the operations of the imagination;
which being always exposed to the delusions of the enemy,
is often beguiled into extravagancies, and is easily bewildered and deceived;
the soul being thereby deprived of its peace.

It will at first be difficult,
from the habit the mind will have acquired of being always from home,
roving hear and there, and from subject to subject, to restrain it,
and free it from those wanderings which are an impediment to prayer.-- Indeed
those wanderings of the imagination with which beginners are for some time tried,
are permitted in order to prove their faith, exercise their patience,
and to show them how little they can perform of themselves;
as well as to teach them to depend upon God alone
for strength to overcome all their difficulties;
"`for by`" his own "`strength, shall no man prevail;`"^
footnote:[1 Samuel 2:9.]
and if they place all their hope in Him, and faithfully persevere,
every obstacle will be gradually removed,
and they will find that they will be enabled to approach Him with facility,
and that inward silence is not only attended with much less difficulty,
but at times will be found to be easy, sweet, and delightful.
They will know that this is the true way of finding God;
and feel "`His name to be as ointment poured forth.`"^
footnote:[Song of Solomon 1:3.]

And although we should at all times be very watchful
and diligent in recalling our wandering thoughts,
restraining them, as much as may be, in due subjection;
yet a direct contest with them only serves to augment and irritate them; whereas,
by calling to mind that we are in the presence of God,
and endeavouring to sink down under a sense and perception thereof,
simply turning inwards; we wage insensibly a very advantageous, though indirect,
war with them.

Those who have not learned to read, are not, on that account, excluded from prayer;
for the great Teacher who teaches all things, is Jesus Christ himself.^
footnote:[John 14:26.]
They should learn this fundamental rule, that "`the Kingdom of God is within them;`"^
footnote:[Luke 17:21.]
and that it is there only it must be sought.

"`The Kingdom of God is within you,`" says our blessed Redeemer.
Abandon, therefore, the cares and pleasures of this wretched world,
and turn to the Lord with all your heart, and your soul shall find rest.^
footnote:[Matthew 11:28-29.]
If you withdraw your attention from outward things,
and keep it fixed on the internal Teacher,
endeavouring to obey Him in whatsoever He may require of you,
you will soon perceive the coming of the kingdom of God:^
footnote:[Matthew 6:10.]
for the kingdom of God is that "`peace and joy in the Holy Spirit,`"^
footnote:[Romans 14:17.]
which cannot be received by sensual and worldly men.

It is for lack of inward retirement, and prayer, that our lives are so imperfect,
and that we are neither penetrated nor warmed with the divine Light of Truth,
Christ the Light.^
footnote:[John 1:9.]
We should, therefore, be in the daily practice of it;
and there are none so much occupied,
as not to be able to find a few moments of inward retirement to God.
The less we practise silent prayer, the less desire we have for it;
for our minds being set upon outward things, we contract at last, such a habit,
that it is very hard to turn them inward.

"`The Lord is in His Holy Temple, let all the earth keep silence before Him.`"^
footnote:[Hab. 2:20.]
The silence of all our earthly thoughts and desires is absolutely indispensable,
if we would hear the secret voice of the Divine Instructor.
Hearing is a sense formed to receive sounds, and is rather passive than active,
admitting, but not communicating sensation; and if we would hear,
we must lend the ear for that purpose: so, CHRIST, THE ETERNAL WORD,^
footnote:[Revelation 19:13.]
without whose Divine inspeaking the soul is dead, dark, and barren,
when He would speak within us,
requires the most silent attention to His all-quickening and efficacious voice.

We should forget ourselves, and all self-interest,
and listen and be attentive to the voice of our God.
Outward silence is very requisite for the cultivation and improvement of inward; and,
indeed, it is impossible we should become truly internal,
without the love and practice of outward silence and retirement.
And unquestionably our being internally engaged with God,
is wholly incompatible with being busied,
and employed in the numerous trifles that surround us.

When through inadvertency or unfaithfulness we become dissipated,
or as it were uncentred,
it is of immediate importance to turn again gently and peacefully inward;
and thus we may learn to preserve the spirit and unction of prayer, throughout the day:
for if the prayer of inward silence were wholly confined to any appointed half-hour,
or hour, we should reap but little fruit.

It is of the greatest importance, for the soul to go to prayer with confidence;
and such a pure and disinterested love, as seeks nothing from God,
but the ability to please Him, and to do His Will:
for a servant who only proportions his diligence to his hope of reward,
renders himself unworthy of all reward.
Go, then, to prayer, not that you may enjoy spiritual delights,
but that you may be full or empty, just as it pleases God.
This will preserve you in an evenness of spirit, either in desertion or in consolation,
and will prevent your being surprised at dryness, or the apparent repulses of God.

Constant prayer is, to keep the heart always right towards God.
Strive then, when you come from prayer,
not to allow your mind to be too much entangled with outward things,
endeavouring to be totally resigned to the Divine Will;
that God may do with you and yours according to His heavenly pleasure,
relying on Him as on a kind and loving Father;
and though you be taken up with your outward affairs,
and your mind thereby prevented from being actually fixed on Him, even then,
you will always carry a fire about you that will never go out; but which,
on the contrary, will nourish a secret prayer,
that will be like a lamp continually lighted before the throne of God.

A son who loves his Father does not always think distinctly of him;
many objects draw away his mind, but these never interrupt the filial love:
whenever his Father returns into his thoughts, he loves him, and he feels,
in the very inmost of his heart, that he has never discontinued one moment to love him,
though he has ceased to think of him.
In this manner should we love our heavenly Father.
It is by Religion alone that we are enabled to call God, Father,
and that we can indeed become His sons.

True Religion is a heaven-born thing,
it is an emanation of the Truth and Goodness of God upon the spirits of men,
whereby they are formed into a similitude and likeness of Himself,
and become "`partakers of the Divine Nature.`"^
footnote:[2 Peter 1:4.]

A true Christian is every way of a most noble extraction,
of a heavenly and divine pedigree, being born, as St. John expresses it, "`from above.`"^
footnote:[John 3:3. See the marginal reading.]
And in another place he says;
"`Behold what manner of love the Father has bestowed upon us,
that we should be called the sons of God!`"^
footnote:[1 John 3:1.]

If considerations such as these,
are not sufficient to convince us of the folly of our attachment to perishing things,
and to stimulate us to press after those which obtain
for us such great and glorious privileges,
we must, indeed, be sunk into a state of deep and deplorable insensibility; out of which,
even "`if one were to rise from the dead`"^
footnote:[Luke 16:31.]
for that purpose, it would be impossible to arouse us.
