[short="On Defects and Infirmities"]
== Chapter 7. On Defects and Infirmities

Should we so far get off our guard,
as again to wander among externals in search of happiness, or sink into dissipation,
or commit a fault, we must instantly turn inwards;
for having departed thereby from our God, we should as soon as possible return unto Him,
and patiently permit whatever sensations he is pleased impress: for He has declared,
"`as many as I love I rebuke and chasten.`"^
footnote:[Revelation 3:19.]
On the commission of a fault,
it is of great importance to guard against vexation and disquietude,
which spring from a secret root of pride, and a love of our own excellence;
we are hurt by feeling what we are: and if we discourage ourselves, or despond,
we are the more enfeebled; and from our reflections on the fault a chagrin arises,
which is often worse than the fault itself.

The truly humble soul is not surprised at its defects or failings;
and the more miserable and wretched it beholds itself,
the more does it abandon itself to God,
and press for a nearer and more intimate alliance with Him,
that it may avail itself of an eternal strength.
We should the rather be induced to act thus, as God Himself has said:
"`I will instruct you and teach you in the way which you shall go:
I will guide you with My eye.`"^
footnote:[Ps. 32:8.]
