== Chapter 9. On Self-denial

He who expects to arrive at perfection, or a union of the soul with God,
by means of consolation and comfort, will find himself mistaken.
For, from the depravity of our nature, we must expect to suffer,
and be in some measure purified,
before we can be in any degree fitted for a union with God,
or permitted to taste of the joy of His Presence.

Be patient, therefore, under all the sufferings which God is pleased to send you.
If your love to Him be pure, you will not seek him less in suffering than in consolation;
and, surely, he should be as much loved in _that_ as in _this_,
since it was by suffering on the cross that He made
the greater display of His own love for you.

Be not like those, who give themselves to Him at one season,
and withdraw from Him at another.
They give themselves only to be caressed; and wrest themselves back again,
when they come to be crucified; or at least turn to the world for consolation.

No, you will find consolation in nothing,
but a free and full surrender of your will to the Divine Will.
Who savours not the Cross, savours not the things that be of God;`"^
footnote:[Matthew 16:23.]
and a heart that savours the Cross, finds the bitterest things to be sweet:
"`to the hungry soul every bitter thing is sweet.`"^
footnote:[Proverbs 27:7.]
God gives the Cross, and the Cross gives us God.

We may be assured, that there is an internal advancement,
where there is an advancement in the way of the Cross.

As soon as anything presents itself as a suffering, and you feel a repugnance against it,
resign yourself immediately unto God with respect to it,
giving yourself up to Him in sacrifice; and you will find, that, when the Cross arrives,
it will not be so very burdensome,
because you had disposed yourself to a willing reception of it.
Jesus Christ Himself was willing to suffer its utmost rigours.
We often bear the cross in weakness, at other times in strength:
all should be equal to us in the will of God.

If any other way, but bearing the cross, and dying to his own will,
could have redeemed man from that fallen and corrupt state, in which he is by nature,
Christ would have taught it, and established it by His example.
But of all that desire to follow him, He has required the bearing of the cross;
and without exception has said to all: "`If any man will come after me,
let him deny himself, take up his cross and follow me.`"^
footnote:[Matthew 16:24.]
Why then do you fear to take up the cross,
which will direct you to the path which leads to the kingdom of God?

From the cross are derived heavenly meekness, true fortitude, the joys of the spirit,
the conquest of self, the perfection of holiness!
There is no redemption, no hope of the continuation of the divine life in us,
but by our taking up the cross to our carnal appetites, and inclinations:
for all consists in the death of self, and there is no means to obtain life and peace,
but by thus dying to the corruptions of our fallen nature!
Take up your cross therefore, and follow Jesus,
in the path that leads to everlasting peace.
He has gone before, bearing that cross upon which He died for you; that you might follow,
patiently bearing your own, and, upon that, dying to yourself for Him.

And if we die with Him, we shall also live with Him:
"`if we are partakers of His sufferings, we shall also be partakers of His glory.`"

Why do you seek any other path to glory,
but that in which you are called to follow the "`Captain of your Salvation?`"
The life of Christ was a continual cross,
and do you desire a perpetuity of repose and joy?
Know, therefore,
your life must be a continual death to the appetites and passions of fallen nature:
and know also that the more perfectly you die to yourself,
the more truly will you begin to live to God; if you would then enjoy true peace here,
and obtain hereafter the unfading crown of glory, it is necessary that in every place,
and in all events, you should bear the cross willingly.
To suffer, therefore, is your portion; and to suffer patiently, and willingly,
is the great testimony of your love and allegiance to your Lord.

Prepare then your spirit to suffer patiently the
many inconveniences and troubles of this life;
for these you will find, and can never avoid, though you run to the ends of the earth,
or hide yourself in its deepest caverns;
and it is patient suffering only that can either disarm their power,
or heal the wounds they have made.
But while every tribulation is painful and grievous,
and it is the desire of your soul to avoid it, you cannot but be wretched;
and what you labour to shun will follow you wherever you go.
The patient enduring of the cross, and the death of self upon it,
are the indispensable duty of fallen man: and it is thus only,
he can be delivered from his darkness, corruption, and misery,
and be restored to the possession of life, light, and peace.

Having then no other desire but that of ardently reaching after Him,
of dwelling ever with Him, and of sinking into nothingness before Him,
we should accept indiscriminately all His dispensations,
whether obscurity or illumination, fruitfulness or barrenness, weakness or strength,
sweetness or bitterness, temptations, wanderings, pain, weariness, or doubtings;
and none of all these should retard our course.
