== Chapter 11. On Resignation

We should give up our whole existence unto God, from the strong and positive conviction,
that while we are faithfully endeavouring to follow Him,
the occurrence of every moment is agreeable to His immediate will and permission,
and just such as our state requires.
This conviction will make us resigned in all things; and accept of all that happens,
not as from the creature, but as from God Himself.

But I entreat you, who sincerely wish to give up yourselves to God,
that after you have made the donation, you will not snatch yourselves back again:
remember, a gift once presented, is no longer at the disposal of the donor.
Resignation is a matter of the greatest importance in our progress;
it is the key to the inner court; so that whosoever knows truly how to resign himself,
soon becomes perfect: we must, therefore, continue steadfast and immovable therein;
and not listen to the voice of natural reason.
Great faith produces great resignation: we must confide in God, "`hoping against hope.`"^
footnote:[Romans 4:18.]

Resignation is casting off all selfish care,
that we may be altogether at the Divine disposal.
All Christians are exhorted to resignation; for it is said to all:
Be not anxious for tomorrow;
for your Heavenly Father knows all that is necessary for you.`"^
footnote:[Matthew 6:32,34.]
"`In all your ways acknowledge Him, and He shall direct your paths.`"^
footnote:[Proverbs 3:6.]
"`Commit your works unto the Lord, and your thoughts shall be established.`"^
footnote:[Proverbs 16:3.]
"`Commit your way unto the Lord, trust also in Him, and He shall bring it to pass;
and he shall bring forth your righteousness as the light,
and your judgment as the noon-day.`"^
footnote:[Ps. 37:5-6.]

This virtue is practised by continually losing our own will in the will of God;
by being resigned in all things, leaving what is past, in oblivion, what is to come,
after having faithfully done our part, to the direction of God,
and devoting the present moment to Him,
by attributing nothing that befalls us to the creature, but regarding all things in God,
and looking upon all, excepting only our sins, as infallibly proceeding from Him.
Surrender yourselves, then, to be led and disposed of, just as God pleases.

We must willingly cooperate with, and second, the designs of God;
which tend to divest us of all our own operations,
that in the place thereof His may be instituted.
Let this, then, be done in you; and permit not yourself to be attached to anything,
however good it may appear; for it is no longer good,
if it in any measure turns you aside from that which God wills of you.

The Divine Will is preferable to all things else.
And it is our conformity to this sweet yoke that
introduces us into the regions of internal peace.
Hence we may know that the rebellion of our will is the chief occasion of all our disquiet,
and that this is the cause why we suffer so many straights and perturbations.
Oh! if we did but submit our wills to the Divine will, and to all its disposals,
what tranquillity should we feel! what sweet peace!
what inward serenity! what supreme felicity,
and foretastes of blessedness!
Let us shake off, then, all attachment to the interests of self,
and live on Faith and Resignation alone.
