[short="On Conversion"]
== Chapter 13. On Conversion

[quote.scripture, , Ezek. 33:11]
____
Turn, turn from your evil ways.
For why should you die, O house of Israel?
____

[quote.scripture, , Isa. 31:6]
____
Turn unto Him from whom you have deeply revolted.
____

To be truly converted, is to avert wholly from the creature, and turn wholly unto God.

For the attainment of salvation, it is absolutely necessary,
that we should forsake outward sin, and turn unto righteousness:
but this alone is not perfect conversion,
which consists in a total change of the whole man, from an outward to an inward life.

When the soul is once turned to God,
it finds a wonderful facility in continuing steadfast in its conversion;
and the longer it remains thus converted, the nearer it approaches,
and the more firmly it adheres to God; and the nearer it draws to Him, of necessity,
the farther it is removed from that spirit, which is contrary to Him:
thus the soul is so effectually established and rooted in its conversion,
that a state of conversion becomes in some measure natural to it.

Now, we must not suppose, that this is effected by a violent exertion of its own powers;
for the soul is not capable of, nor should it attempt,
any other cooperation with Divine Grace,
than that of endeavouring to withdraw itself from external objects, and to turn inward:
after which, it has nothing farther to do,
than to continue steadfast in its adherence to God.

God has an attractive virtue, which draws the soul more and more powerfully to Himself,
the nearer it approaches towards Him, and in attracting, he purifies and refines it;
just as it is with a gross vapour exhaled by the sun, which, as it gradually ascends,
is rarified and rendered pure: the vapour, indeed,
contributes to its exhalation only by its passiveness;
but the soul cooperates with the attractions of its God,
by a free and affectionate correspondence.
This turning of the mind inward is both easy and efficacious,
advancing the soul naturally, and without constraint,
because God Himself is the centre which attracts it.

All our care and attention should therefore be, to acquire inward silence:
nor let us be discouraged by the pains and difficulties we encounter in this exercise,
which will soon be recompensed on the part of our God,
by such abundant supplies of His strength as will render the exercise perfectly easy,
provided we are faithful in meekly withdrawing our hearts from outward objects and gratifications,
and returning to our centre, with affections full of tenderness and serenity.
When at any time the passions are turbulent, a gentle retreat inward unto a present God,
easily deadens and pacifies them; and any other way of contending with them,
rather irritates than appeases them.
One word of our Saviour, in time past, instantly calmed a boisterous and raging sea;
and can we now doubt, if we sincerely apply to Him in our distress,
that He would still the tumults of the agitated soul?
