== Chapter 14. On Self-annihilation

The soul becomes fitted for union with God,
by giving up Self to the destroying and annihilating power of Divine Love.
This, indeed, is a most essential and necessary sacrifice in the Christian religion,
and that only by which we pay true homage to the sovereignty of God.
By the destruction of the existence of Self within us,
we truly acknowledge the supreme existence of our God;
for unless we cease to exist in Self, the Spirit of the Eternal Word cannot exist in us.
Now it is by the giving up of our own life, that we give place for His coming; and,
in dying to ourselves, He Himself lives and abides in us.^
footnote:[Galatians 2:20.]

We should, indeed, surrender our whole being unto Christ Jesus;
and cease to live any longer in ourselves, that He Himself may become our life;
"`that being dead, our life may be hid with Christ in God.`"^
footnote:[Colossians 3:3.]
By leaving and forsaking ourselves we are lost in Him;
and this can be effected only by the annihilation of Self,
which being the true prayer of adoration, renders unto "`God, and unto the Lamb,
blessing, and honour, and glory, and power, forever and ever!`"^
footnote:[Revelation 5:13.]

This is the Prayer of Truth; "`It is worshipping God in spirit and in truth:`"^
footnote:[John 4:23.]
because we here come to know the spirit to help our infirmities,
and make intercession for us;^
footnote:[Romans 8:26.]
and being thus influenced by the pure Spirit of God,
we are thereby drawn forth and freed from our own carnal and corrupt manner of praying.
We can pay due honour to God only in our own annihilation;
which is no sooner accomplished, than He who never allows a void in nature,
instantly fills us with Himself.

Did we but know the virtues and the blessings which
the soul derives from this species of prayer,
we should willingly be employed therein without ceasing.
It is the pearl of great price; it is the hidden treasure;^
footnote:[Matthew 13:44,46.]
which, whoever finds, sells freely all that he has to purchase it:
It is the "`well of living water, which springs up into everlasting life:`"^
footnote:[John 4:14.]
It is the true adoration of God and comprehends the
full performance of the purest evangelical precepts.

Jesus Christ assures us, that the Kingdom of God is within us;`"^
footnote:[Luke 17:21.]
and this is true in two senses: First, God becomes so fully the Master and Lord in us,
that nothing resists His dominion: then is our interior His kingdom.
And again, when we possess God, who is the supreme Good, we possess His kingdom also,
wherein there is fullness of joy and where we attain the end of our creation.
The end of our creation, indeed, is to enjoy our God, even in this life but,
alas! how few there are who ever come to know the pure joy which His Presence gives.
