[#seventeen, short="Chapter 17 -- Perfection or Union with God"]
== Chapter 17. On Perfection, or the Union of the Soul with God

The most profitable and desirable state in this life, is that of Christian perfection,
which consists in the union of the soul with God,
union that includes in it all spiritual good;
producing in us wonderful freedom of spirit,
which raises us above all the events and changes of this life,
and which frees us from the tyranny of human fear;
it gives an extraordinary power for the well performing all our actions,
and acquitting ourselves well in our employments;
a prudence truly Christian in all our undertakings;
a peace and perfect tranquillity in all conditions; and, in short,
continual victory over self-love and our passions.

It is impossible to attain Divine Union, solely by the activity of meditation,
or by the meltings of the affections,
or even by the highest degree of luminous and elegantly composed prayer; for,
according to Scripture, "`no man shall see God and live.`"^
footnote:[Exodus 33:20.]
Now all the exercises of discoursive prayer, and even of active contemplation,
being performed in the _life_ of our own will,
we "`cannot thereby see God;`" for all that is of man`'s own power or exertion,
must first die, be it ever so noble, ever so exalted.

St. John relates, "`that there was silence in heaven:`"^
footnote:[Revelation 8:1.]
Now heaven represents the centre of the soul, wherein, before the majesty of God appears,
all must be hushed to silence.
All the efforts, nay the very existence of Self-love must be destroyed;
because it is the natural will that is opposed to God,
and all the malignity of man proceeds from it, insomuch,
that the purity of soul increases,
in proportion as the natural will becomes subjected to the Divine Will.

Therefore, the soul can never arrive at Divine Union but by the annihilation of its will;
nor can it ever become one with God,
but by being reestablished in the purity of its first creation.
God purifies the soul by His Wisdom, as refiners do metals in the furnace.
Gold cannot be purified but by fire, which gradually separates from it, and consumes,
all that is earthly and heterogeneous: it must be melted and dissolved,
and all impure mixtures taken away, by casting it again and again into the furnace:
thus it is refined from all internal corruption,
and even exalted to state incapable of farther purification.
It now no longer contains any adulterate mixture; its purity is perfect,
its simplicity complete; and it is fit for the most exquisite workmanship.
Thus we may see that the Divine Spirit, as an unremitting fire,
must devour and destroy all that is earthly, sensual, and carnal, and all self-activity,
before the soul can be fitted for, and capable of union with God.

"`I will make man more precious than fine Gold.`"^
footnote:[Isaiah 13:12.]
But when God begins to burn, destroy, and purify, then the soul,
not perceiving the salutary designs of these operations, shrinks from them;
and as the gold seems rather to blacken than brighten when first put into the furnace,
so the soul conceives that its purity is lost, and that its temptations are its sins.

But while we confess, that the enjoyment of God is the end for which we were created;
that "`without holiness`"^
footnote:[Hebrews 12:14.]
none can attain it; and, that to attain it,
we must necessarily pass through severe and purifying process; how strange is it,
that we should dread and avoid this process,
as if that could be the cause of evil and imperfection in the present life,
which is to be productive of glory and blessedness in the life to come!

Let all, then, press forward towards the mark,
allowing themselves to be guided and governed by the Spirit of Grace,
which would infallibly conduct them to the end of their creation, the enjoyment of God.

It may perhaps be said, that some may feign to have attained this blessed state; but,
alas none can any more feign this, than the wretch,
who is on the point of perishing with hunger,
can for length of time feign to be full and satisfied: some wish or word,
some sigh or sign, will inevitably escape him, and betray his famished state.

"`Be perfect, even as your Father which is in heaven is perfect.`"^
footnote:[Matthew 5:48.]
The soul remaining in its disorderly will, is imperfect; it becomes more perfect,
in proportion as it approaches nearer to the will of God.
When the soul is advanced, so far,
that it cannot in anything depart from the Divine will, it then becomes wholly perfect,
united with, and transformed into the Divine nature;
and being thus purified and united to God, it finds, profound peace, and sweet rest,
which brings it to such perfect union of love, that it is filled with joy.
It conforms itself to the will of its God in all emergencies,
and rejoices in everything to do the Divine good pleasure.

The Lord draws near to such soul, and communicates Himself inwardly to it.
He fills it with Himself because it is empty,
clothes it with His light and with His love, because it is naked;
lifts it up because it is low; and unites it with Himself.

If you would enter into this heaven on earth,
forget every care and every anxious thought, get out of yourself,
that the love of God may live in your soul;
so that you may be enabled to say with the Apostle: "`I live, yet not I,
but Christ lives in me.`"^
footnote:[Galatians 2:20.]
How happy should we be if we could thus leave all for God, seek Him only,
breathe after none but Him; let Him only have our sighs!
O, that we could but go on without interruption,
towards the enjoyment of this blessed state!
God call us thereto.
He invites us to enter into our inward centre, where He will renew and change us,
and show us a new and heavenly kingdom, full of joy, peace content, and serenity.

The spiritual, abstracted, and retired soul has here its peace no more broken,
though outwardly it may meet with combats, and may sometimes be naked, forsaken,
fought against, and desolate, because from the infinite distance,
tempests never reach to that serenest heaven within, where pure and perfect love resides.
For, although the prince of darkness may indeed make violent assaults against it;
yet it makes head against them, and stands like a strong pillar; no more happening to it,
than happens to a high mountain in a storm.
The valley is darkened with thick clouds, fierce tempests of hail, and thunder;
while the lofty mountain glitters by the bright beams of the sun,
in quietness and serenity, continuing clear like heaven, immoveable, and full of light:
such a soul, indeed, is, as "`mount Zion, which cannot be removed, but abides forever.`"^
footnote:[Ps. 125:1.]

In this throne of quiet, are manifest the perfections of spiritual beauty:
here we shall enjoy the true light of the secret and divine mysteries of Christ,
perfect humility, the amplest resignation, the meekness, and innocency of the dove,
liberty and purity of heart; here is witnessed joyful simplicity, heavenly indifference,
continual prayer, total nakedness, perfect disinterestedness, a conversation of heaven.

This is the rich and hidden treasure; this is the pearl of great price.

[.the-end]
Finis.
