== John Crook`'s Advice to His Children and Grandchildren / Written Close to His Death

Dear Children,

I must leave you in a wicked age,
but commit you to the measure of the grace of God in your inward parts,
which you have received by Jesus Christ; and as you love it,
and mind the teachings of it,
you will find it a counsellor to instruct you in the way everlasting,
and preserve out of the ways of the ungodly.

I have seen much in my days,
and I always observed that the fear of the Lord God proved the best portion,
and those that walked in it, were the only happy people,
both in this life (while they continued faithful) and when they come to die,
though they meet with many hardships in the passage.
By experience I can speak it,
that the ways of holiness afford more true comfort and peace to the upright soul,
than the greatest pleasures this world can afford; the former reaches the heart and soul,
while the delights of this world are but a show, and appearance only,
vanishing like a dream; and whoever believes otherwise of them,
will certainly find them to be but lying vanities;
therefore the apostle might boldly put the question to the converted Romans+++[++++++[+++__ddelink__14951_21906343]],
"`What fruit had you then in those things whereof you are now ashamed?
for the end of those things is death.`"

Therefore, dear children, be in love with holiness; make it your companion,
and those that walk in it; you may find buddings of it, from a holy seed in your hearts;
as you mind the inner man, the light will manifest the stirrings of it after God,
which I felt from my tender years; although I understood them not so plainly,
till I heard the truth declared.

I advise you to keep a pure conscience, both toward God and man; for if that be defiled,
hypocrisy and formality will deprive you of all comfortable feeling of God's presence;
and then deadness and dryness will be your miserable portion.

Be careful of how you spend your precious time,
for an account must be given of every idle word, though but few regard it;
but foolish jesting, and vain talking, are said to grieve the spirit of God.
But improve your time in prayer, and religious exercises,
and be diligent in your lawful callings,
for "`The desire of the slothful man kills him.`"

Be careful what company you keep; for a man is commonly known by the company he keeps,
as much as by any one outward thing; and of your behaviour in company; for I have found,
that a wise and sober deportment adds much to a man's reputation and credit in the world.

Watch to the light, and its discoveries of good and evil,
that you may not be ignorant of Satan's devices;
so the net will be spread in vain in the flight of the bird;
for watchfulness will make you in love with a retired estate;
and the more truly and perfectly any man knows and understands himself,
the better discerning will such have of other men; as in the beginning,
when deep silence of all flesh was more in use, the spirit of discerning was more common,
and quicker, than since it has been neglected; therefore be sure you spend some time,
at convenient seasons, in waiting upon God in silence, though it be displeasing to flesh;
for I have had more comfort, and confirmation in the truth,
in my inward retiring in silence, than from all words I have heard from others,
though I have often been refreshed by those also.

Love the holy scriptures, preferring them to all other books whatsoever;
and be careful to read them with a holy awe upon your spirits,
lest your imaginations put constructions upon them to your hurt;
but execute faith in the promise of Christ, who hath said,
"`My spirit shall take of mine, and show them unto you.`"

Keep constantly to religious meetings amongst Friends; but look to your affections,
that you respect not persons, but the power and life of truth, from whomsoever it comes;
not minding the tickling of your affections,
but the demonstration of the truth to your understandings and consciences;
for that will abide when flashes of affections will fade and come to nothing,
after the words are ended.

Love one another truly, manifesting your love by good counsel;
and being helpful to each other upon all occasions;
being good examples to all you converse with, especially to your children,
and those of your own families, that pride and vanity may not be countenanced by you,
but rather reproved; remembering, while they are under your government,
you must give an account of the discharge of your duty to God towards them.

Lastly, Be always mindful of your latter end, and live as you would die,
not knowing how soon your days may be finished in this world:
and while you do live in it, despise not the chastenings of the Lord, whatever they be,
he is pleased to visit you with.
I have been afflicted from my youth up, both inwardly and outwardly,
but God whom I served, provided for me, when all my outward relations forsook me.
I need not mention this affliction in my old age, because, in some measure, you know it;
but I could not have been without it, as the Lord has shown me,
for I have seen his wonders in the deeps: therefore I say again, despise not afflictions,
but embrace them as messengers of peace to your souls (though displeasing to the flesh.)

These things I commend unto you, out of true love to your souls,
knowing how the vain mind of man little regards such advice as this I leave behind me:
but by this advice I show my true love to you, desiring God's blessing upon it;
to whom I commit you all, my dear children, and end my days.

Your loving father and grandfather,

John Crook

