== A Letter of Richard Shackleton to His Daughter Mary

Be careful, my beloved Mary, to centre deep in humility and abasement of self;
it is the tree which takes deep root downwards that
is most likely to stand against the storm.
This is the springtime of your life; may your tender,
innocent heart be open to receive the precious seed,
which I trust the great and good Husbandman will condescend, and has condescended,
to sow therein; may He also be pleased to water it with visitations of love,
immediately and instrumentally; may He guard and protect it from every noxious thing!
You see how your older sisters have made choice of religion, as their principle treasure.
You also be a wise child;
and whatever natural abilities it may please the great Creator to endow you with,
or whatever acquisitions or improvements you make of those natural gifts,
by contemplation, reading, or conversation, remember,
you are only acceptable in the sight of Heaven, (no matter how man may esteem you),
as you take heed to the grace in your own heart, to be restrained by its restraints,
to do nothing contrary to its gentle remonstrances, and to obey,
in humility and simplicity, its leadings and requirings.

My dear child, above all things, be humble, be humble.
Humility goes before honour; it is the humble whom the Lord teaches of his ways.
We have in each of us a certain something, appertaining to self,
(it is of the flesh,) which profits nothing in the work of religion.
This fleshy part is pleased and nourished,
and swells with the praise and commendation of fools, for wise men would not puff up.
We have need of frequent retirement to the gift, the grace in our minds,
that in the tranquil, cool hour of the day, not inflated by vain knowledge,
or perturbed by passion, we may, in the stillness of all flesh, hear what this Monitor,
this good Spirit, this faithful Witness, says to our states.
Perhaps when figuratively speaking, all men speak well of us, this heavenly, sure,
unerring word of prophecy, which preaches to our own particular states as individuals,
will condemn or reprove us.
This is what we are to go by, and to judge and estimate ourselves by;
and not by the crude, superficial, hasty,
partial judgment of capricious mortals whose favour veers about like the wind.
My mind is often exercised on behalf of my children.
You are the children of many prayers.
You have hitherto been a great comfort to your dear mother and me,
and we have no greater joy than to seek your walk in the Truth.
It is neither in our will, nor in our power, to do great things as to this world for you.
We are not like many others who have large possessions and lucrative business.
Providence, in the wise distribution of his favours,
has allotted us a lower rank in life; yet, with industry, care, and prudent economy,
he has enabled us to procure a sufficiency.
And indeed a great redundancy is not desirable;
the lip of truth has pronounced how hard it is for a rich man to enter the kingdom.
A little sufficiency of the things of this life, enjoyed in moderation,
and under a renewed sense of the Divine blessing, is all that I think we should wish for,
and when obtained, should be cause of deep, and humble,
and fervent gratitude to our great Benefactor.

Thy truly affectionate father,

Richard Shackleton
