== William Penn`'s Advice to His Children and Grandchildren

=== Part One

My Dear Children:

Not knowing how long it may please God to continue me among you,
I am willing to embrace this opportunity of leaving you my advice
and counsel with respect to your Christian duty in this world.
And I both beseech you and charge you, by the relation you have to me,
and the affection I have always shown to you, and indeed received from you,
that you lay up the same in your hearts, as well as your heads,
with a wise and religious care.

I will begin with that which is the beginning of all true
wisdom and happiness - the holy fear of God.

Children, Fear God; that is to say,
have a holy awe upon your minds to avoid that which is evil,
and a strict care to embrace and do that which is good.
By the light of Christ in your consciences, you may clearly see if your deeds,
and your words and thoughts, too, are wrought in God or not.
With this divine light of Christ in your consciences, you may bring your thoughts, words,
and works to judgment in yourselves, and have a right, true, sound,
and unerring sense of your duty towards God and man.
And as you come to obey this blessed light in its holy convictions,
it will lead you out of the world's dark and degenerate ways and works,
and bring you unto Christ's way and life, and to be of the number of his true,
self-denying followers, to take up your cross for his sake, that bore his for yours,
and to become the children of the Light, putting it on as your Holy armour,
by which you may see and resist the fiery darts of Satan's temptations,
and overcome him in all his assaults.

I would explain this principle to you:
It is called Light because it gives man a sight of his sin;
and it is also called the Quickening Spirit, for so he is called;
and the Lord from heaven is called and calls himself the Light of the world;
and why is he called the Spirit?
Because He gives man spiritual life.
And Christ promised to send his spirit to convince the world of their sins.
Wherefore, that which convinces you and all people of their sins is the spirit of Christ.
God sent his Son to bless us, in turning us from the evil of our ways.
Therefore have a care of evil, for that turns you away from God;
and wherein you have done evil, do so no more.
But be turned, my dear children, from that evil in thought, as well as in word or deed,
or that will turn you from God your Creator,
and Christ whom he has given you for your redeemer;
who redeems and saves his people from their sins, not in their sins.
This holy, divine principle is called grace, too;
there you will see the nature and office of it,
and its blessed effects upon those that were taught of it in the primitive days.
And why Grace?
Because it is God's love, and not what we deserve; it is his good will, his kindness.
For God so loved the world that he gave his only begotten Son,
that whosoever believeth in him should not perish, but have everlasting life.
And it is this holy Son, that in John 1:14, is declared to be full of grace and truth,
and that of his grace we receive grace for grace; that is,
we receive of him the fullness, what measure of grace we need.
And the Lord told Paul in his great trials,
when ready to stagger about the sufficiency of the grace he had received to deliver him:
My grace is sufficient for you.
Oh, children! love the grace, hearken to this grace; it will teach you,
it will sanctify you, it will lead you to the rest and kingdom of God;
as it taught the saints of old, first, what to deny;
to deny ungodliness and worldly lusts; and then what to do; to live soberly, righteously,
and godly in this present world.
I am the Way, the Truth, and the Life, said he to his poor followers;
and if the truth makes you free, then are you free indeed.
And this truth sheds abroad itself in man, and begets truth in the inward parts,
and makes false, rebellious, hypocritical man a true man to God again.
Truth in the inward parts is of great price with the Lord.
And why called Truth?
Because it tells man the truth of his spiritual state; it shows him this state,
deals plainly with him, and sets his sins in order before him.
So that, my dear children, the light, spirit, grace,
and truth are not different principles,
but different words given to one eternal power and heavenly principle in you,
though not of you, but of God.
Light, to discover and give discerning; Spirit, to quicken and enliven; Grace,
to witness the love of God; Truth, because it tells man the truth of his condition,
and redeems him from the errors of his ways; so that as darkness, death, sin,
and error are the same, so light, spirit, grace, and truth are the same.

O, my dear children! this is the pearl of price; part with all for it,
but never part with it for all the world.
This is the gospel which will sanctify you in body, soul, and spirit,
to God your heavenly Father's use and service, and your own lasting comfort.
Yes, this is the divine incorruptible seed of the kingdom,
of which all truly regenerate men and women, Christians of Christ's making are born.

Receive it into your hearts, give it room there, let it take deep root in you,
and you will be fruitful unto God in every good word and work.
As you take heed to it, and the holy enlightenings and motions of it,
you will have a perfect discerning of the spirit of this
world in all its appearances in yourselves and others;
the motions, temptations, and workings of it, as to pride, vanity, covetousness, revenge,
uncleanness, hypocrisy, and every evil way;
you will see the world in all its shapes and features,
and you will be able to judge the world by it,
and the spirit of the world in all its appearance; you will see, as I have done,
that there is much to deny, much to suffer, and much to do;
and you will see that there is no power or virtue but in the light, spirit, grace,
and truth of Christ,
to carry you through the world to God's glory and your everlasting peace.
Yes, you will see what religion is from above, and what is from below;
what is of God's working, and of man's making and forcing; also,
what ministry is of his spirit and giving, and what is of man's studying, framing,
and imposing.

And be sure that you forsake not the assembling yourselves with God's people,
as is the manner of some in this day,
especially among young people whom the love of this present evil
world has hurt and cooled their love to God and his truth.
But keep close to meetings, not out of novelty, formality, or to be seen of men,
but in pure fear, love, and conscience to God your creator, as the public, just,
and avowed testimony of your duty and homage to him, in which be exemplary,
both by timely coming and a reverent and serious deportment during the assembly.
Be not weary in meetings, or think the time long till it be over,
but let your eye be to him you come to wait upon and serve, and do what you do as to him,
and he will be your refreshment and reward;
for you shall return with the seals and pledges of his love, mercy, and blessings.

Above all things, my dear children,
as to your communion and fellowship with fellow Christians,
be careful to keep the unity of the faith in the bond of peace.
Beware of those who undervalue and undermine brethren behind their backs,
or slight the good and wholesome order of truth for the preserving things quiet, sweet,
and honourable in the church.
Beware of airy and changeable people, the conceited, censorious, and puffed up,
who at last have always shown themselves to be clouds without rain,
and wells without water,
that will rather disturb and break the peace and fellowship of the church
where they dwell than not have their wills and way take place.
I charge you, in the fear of the living God, that you carefully beware of all such;
have no fellowship with them, but to advise, exhort, entreat, and finally reprove them;
for God is and will be with his people in this holy dispensation we are now under,
and which is now among us unto the end of days.
It shall grow and increase in gifts, graces, power, and lustre,
for it is the last and unchangeable one; and blessed are your eyes, if they see it,
and your ears, if they hear it, and your hearts, if they understand it,
which I pray that you may, to God's glory and your eternal comfort.

Having thus expressed myself to you, my dear children, as to the things of God,
his truth and Kingdom, I refer you to his light, grace, spirit, and truth within you,
and the holy scriptures of truth without you, which from my youth I loved to read,
and were ever blessed to me, and which I charge you to read daily;
the Old Testament for history chiefly; the Psalms for meditation and devotion;
the Prophets for comfort and hope; but especially the New Testament for doctrine, faith,
and worship.
For they were given forth by holy men of God in diverse ages,
as they were moved of the Holy Spirit,
and are the declared and revealed mind and will of
the holy God to mankind under diverse dispensations.
They are certainly able to make the man of God perfect, through faith unto salvation;
being such a true and clear testimony to the salvation that is of God, through Christ,
the second Adam, the light of the world, the quickening spirit,
who is full of grace and truth, whose light, grace, spirit,
and truth bear witness to them in every sensible soul, as they frequently,
plainly and solemnly bear testimony to the light, spirit, grace,
and truth both in himself and in and to his people, to their sanctification,
justification, redemption, and consolation, and in all men to their visitation, reproof,
and conviction of their evil ways.
I refer you, my dear children, to the light and spirit of Jesus, that is within you,
and to the scriptures of truth without you,
and such other testimonies to the one same eternal truth as have been borne in our day,
that you may more directly apply what I have said to your pilgrimage upon earth.

=== Part Two

As soon as you wake,
retire your mind into a pure silence from all thoughts and ideas of worldly things,
and in that frame wait upon God, to feel His good presence,
to lift up your hearts to Him,
and commit your whole self into his blessed care and protection.
Then rise, and being dressed, read a chapter or more in the Scriptures,
and afterwards dispose yourselves for the business of the day,
ever remembering that God is present as the overseer of all your thoughts, words,
and actions.
Demean yourselves, my dear children, accordingly, and do not dare to do that in his holy,
all-seeing presence, which you would be ashamed a man would see you do.
And as you have intervals from your occupations,
delight to commune with your own hearts and be still.
As Nebuchadnezzar said on one occasion,
One like the Son of God you shall find and enjoy with you and in you:
a treasure the world knows not of, but is the aim, end,
and diadem of the children of God.
This will bear you up against all temptations,
and carry you sweetly and evenly through your day's business,
supporting you under disappointments,
and moderating your satisfaction in success and prosperity.
In the evening, read again the Holy Scripture,
and have your times of retirement before you close your eyes, as in the morning;
that so the Lord may be the Alpha and Omega of every day of your lives.
And if God bless you with families,
remember good Joshua's resolution - But as for me and my House, we will serve the Lord.

Fear God; show it in all that you desire, do, and refrain from doing.
Keep the inward watch; keep a clear soul and a light heart.
Mind an inward sense upon doing anything.
When you read the Scripture,
mark the places where your spirits are most touched and affected, in a common-place book,
with that sense or opening which you receive;
for they come not by study or in the will of man, no more than the Scripture did;
and they may be lost by carelessness and overgrowing thoughts,
and businesses of this life.
In perusing any other good or profitable book, rather meditate than read much. 

In conversation, mark well what others say or do, and hide your own mind,
at least till last, and then open it as sparingly as the matter will let you.
A just observance and reflection upon men and things gives wisdom.
Be always on your watch, but chiefly in company; then be sure to keep your armour on.
Speak last and little, but to the point; interrupt no one.
Be quick to hear, slow to speak.
It gives time to understand and ripens an answer.
Speak clearly to make yourselves easily understood by everybody,
and in as few words as the matter will admit of is best.

Return no answer to anger, unless with much meekness, which often dispels anger.
Rarely make replies, especially sharp replies, for that adds fuel to the fire.
It is a wrong time to vindicate yourselves, the true ear being then never open to hear it.
Men know not well what spirits they are of.
Silence to passion, prejudice, and mockery, is the best an answer,
and often conquers what resistance inflames.

Be plain in clothes, furniture, and food; excess is a folly and a snare.
Avoid daintiness and choiceness about your persons and houses;
for if it be not an evil in itself, it is a temptation to it.

Prefer elders and strangers on all occasions;
be rather last than first in conveniency and respect, but first in all virtues.

Above all, remember your Creator in the youthful time and forepart of your life;
for good methods and habits obtained then will make
you easy and happy the rest of your days.
Beware of the lusts of the eye, and the flesh, and the pride of life,
which are not of the Father, but of the world.
Oh, my dear children! be not tied to external things;
for then you can never have the true and free enjoyment of yourselves to better things.
The pomp, honour, and luxury of the world are deceptive,
and the unthinking and inconsiderate are taken by them.
But the retired man is upon higher ground; he sees and is aware of the deception,
condemns the folly, and bemoans the deluded.

Have but few books, but let them be well chosen and well read,
whether of religious or civil subjects.
Measure both religion and learning by practice; reduce all to that,
for practice alone brings a real benefit to you; the rest is a thief and a snare.
And indeed, reading many books takes the mind too much from meditation.
Reading yourselves and nature is the truest human wisdom.
The spirit of a man knows the things of man,
and more true knowledge comes by meditation and reflection than by reading.
Much reading is an oppression of the mind and extinguishes the natural candle,
which is the reason of so many senseless scholars in the world.

Do not that which you blame in another.
Do not that to another which you would not another should do to you; but above all,
do not that in God's sight which you would not want man to see you do.

Keep close to the meetings of God's people; wait diligently in them,
to feel the heavenly life in your hearts.
Look for that more than words in ministry and you will profit most.
Above all, look to the Lord, but despise not instruments, man or woman, young or old,
rich or poor, learned or unlearned.

Excuse faults in others, own them in yourselves, and forgive them against you yourselves,
as you would have your heavenly Father and Judge forgive you. 

Love silence, even in the mind; for thoughts are to the mind as words are to the body,
troublesome; much speaking, as well as much thinking, spends; and in many thoughts,
as well as in many words, there is sin.
True silence is the rest of the mind, and is to the spirit what sleep is to the body,
nourishment and refreshment.
It is a great virtue; it covers folly, keeps secrets, avoids disputes, and prevents sin. 

Never meddle with other folks' business, and less with the public,
unless called to the one by the parties concerned,
in which move cautiously and uprightly,
and required to the other by the Lord in a testimony for his name and truth.
He lives happily that lives hiddenly or privately, for he lives quietly.
It is a treasure to them that have it.
The world knows not the value of quiet living;
it doubles man's life by giving him twice the time to himself
that a large acquaintance or much business will allow him.

Envy none; it is God that makes rich and poor, great and small, high and low.
Beware of jealousy, for it devours love and friendship;
it breaks fellowship and destroys the peace of the mind.
It is a groundless and evil surmise.

Meddle not with government; seldom speak of it; let others say or do as they please.
For much knowledge brings sorrow, and much doings more.
Therefore know God, know yourselves; love home, know your own business and mind it,
and you have more time and peace than your neighbours.

If you incline to marry, then be not hasty, but serious; lay it before the Lord,
proceed in his fear, and be well advised.
And when married, avoid occasion of misunderstanding;
allow for weaknesses and variety of constitution and disposition,
and be careful not to show the least disgust or misunderstanding to others,
especially your children.
Never lie down with any displeasure in your minds,
but avoid occasion of dispute and offence; overlook and cover failings.
Seek the Lord for one another; wait upon him together, morning and evening,
in His holy fear, which will renew and confirm your love and covenant;
give way to nothing that would in the least violate it; use all means of true endearment,
that you may recommend and please one another,
remembering your relation and union is the figure of Christ to his church; therefore,
let the authority of love only bear sway your whole life.

If God gives you children, love them with wisdom, correct them with affection;
never strike in passion, and suit the correction to their age as well as fault.
Convince them of their error before you chastise them;
if they show remorse before severity,
never use that but in case of obstinacy or impenitence.
Punish them more by their understandings than the rod, and show them the folly,
shame and undutifulness of their faults rather with a grieved than an angry countenance,
and you will sooner affect their natures, and with a nobler sense,
than a servile and rude chastisement can produce.
I know the methods of some are severe corrections for faults,
and artificial praises when they do well, and sometimes rewards:
but this course awakens passions worse than their faults; for one begets base fear,
if not hatred; the other pride and vain glory,
both which should be avoided in a godly upbringing of youth.
There should be the greatest care imaginable, what impressions are given to children;
that method which earliest awakens their understandings to love, duty, sobriety,
just and honourable things, is to be preferred. 

=== Part Three

Be humble.
It becomes a creature, a depending and borrowed being, that lives not of itself,
but breathes in another's air with another's breath,
and is accountable for every moment of time and can call nothing its own,
but is absolutely a tenant at will of the great Lord of heaven and earth.
And of this excellent quality you cannot be wanting,
if you dwell in the holy fear of the omnipresent and all-seeing God;
for that will show you your vileness and His excellency, your baseness and His majesty,
and the sense of His love to such poor worms,
in the testimonies He gives of His daily care, and mercy and goodness;
that you cannot but be abased, laid low and humble.
The fear and love of God begets humility, and humility fits you for God and men.
You cannot step amiss if this virtue dwell richly in you; for then God will teach you.
The humble He teaches his ways.
Humility seeks not the last word, nor first place; it offends none, but prefers others,
and thinks lowly of itself; is not rough or self-conceited, high, loud, or domineering.
Learn of me, said Christ, for I am meek and lowly in heart.
He washed His disciples' feet, and indeed was himself the greatest pattern of humility.
There is nothing that shines more clearly through Christianity than humility;
of this Christ was the greatest example.
Indeed His whole life was one continued great act of self-denial,
thereby leaving us an example that we should follow His steps.
And the more to illustrate this virtue,
I would have you consider the folly and danger of pride, its opposite.
Pride is the vainest passion that can rule in man,
because he has nothing of his own to be proud of.
He did not only not make himself,
but is born the most naked and helpless of almost all creatures.
He is so absolutely in the power of another, that as I have often said,
he is at best but a tenant at will of the great Lord of all, holding life, health,
substance, and everything at his sovereign disposal; and the more man enjoys his Creator,
the less reason he has to be proud,
because he is the more indebted and engaged to thankfulness and humility.
Wherefore avoid pride as you would avoid the devil; remembering you must die,
and consequently those things must die with you, that could be any temptation to pride.

From humility springs meekness.
The difference is not great between these excellent graces,
yet the scripture observes some.
God will teach the humble his way, and guide the meek in judgment.
It seems to be humility perfectly digested, and from a virtue becomes a nature.
A meek man is one that is not easily provoked, yet easily grieved; not peevish or testy,
but soft, gentle, and inoffensive.
How blessed will you be, my dear children, if this grace adorns you!
There are diverse great and precious promises to the meek in scripture.
God will clothe the meek with salvation,
and blessed are they for they shall inherit the earth.
Christ presses it in his own example: Learn of me for I am meek. 

Patience is an effect of a meek spirit and flows from it.
It is a bearing and suffering disposition; not easily moved to wrath, or vindictive;
but ready to hear and endure, rather than be swift and hasty in judgment or action.
Without it there is no running the Christian race, or obtaining the heavenly crown;
without it there can be no experience of the work of God.
Therefore, says James, let patience have its perfect work.
Patience is wise and will give you great advantage
over those you converse with on all accounts.
For passion blinds men's eyes, and betrays men's weakness;
patience sees the advantage and improves it.
Patience inquires, deliberates and brings to a mature judgment;
you cannot act wisely and safely without it;
therefore I recommend this blessed virtue to you.

Show mercy, whenever it is in your power, that is forgive, pity and help.
Mic. 6: 8: He has shown you O man what is good, and what the Lord requires of you,
to do justly, and to love mercy and to walk humbly,
or to humble yourself to walk with you God: a short but ample expression of God's love,
and man's duty; happy are you if you mind it.
Remember the nature and goodness of Joseph to his brethren;
follow the example of the Good Samaritan.

Charity is a near neighbour to mercy: it consists is not being overly critical of others,
and to relieve the poor.
For the first, remember you must be judged.
And for the last, remember you are but stewards.
Judge not, therefore, lest you be judged.
Be clear yourselves before you fling the stone.
Get the beam out of your own eye; it is humbling doctrine, but safe.
Judge, therefore, at your own peril: see that be righteous judgment,
as you will answer it to the Great Judge.
This part of charity also excludes whisperings, backbiting, talebearing,
and evil-surmising.
For the other part of charity, relieving the poor, it is a debt you owe to God.
The saying is, that he who gives to the poor, lends to the Lord: but it may be said,
not improperly, the Lord lends to us to give to the poor.

I especially recommend little children, widows, sick and elderly persons to you:
spare something from your own table rather than let them go hungry.
Avoid that great sin of needless expense on yourselves and your own houses,
while the poor are hungry and naked.
I have often been moved to see very aged and sick people,
but especially poor helpless children,
lie all night in bitter weather at the thresholds of doors, in the open streets,
for want of better lodging.
I have made this reflection, if you were so exposed, how hard would it be to endure?
The difference between our condition and theirs has drawn from me humble thanks to God,
and great compassion to those poor creatures.
Be good to the poor; be just to them, and think it your duty.
Let the moving passage, Matt. 25:35 live in your minds:
For I was hungry and you gave Me food; I was thirsty and you gave Me drink;
I was a stranger and you took Me in.
Psalm 41: Blessed is he that considers the poor,
the Lord will deliver him in time of trouble: the Lord will preserve and keep him alive,
and he shall be blessed upon the earth.
This is the reward of being faithful stewards and treasurers for the poor of the earth.
Beware of excuses; they are, I know, ready at hand; but read Prov. 3:27:
Withhold not good from those to whom it is due,
when it is in the power of your hand to do so.
Say not unto your neighbour, Go, and come again, and tomorrow I will give,
when you have it with you.
Also bear in mind Christ's doctrine, Matt. 5:42: Give to him that asks you,
and from him that wants to borrow of you, turn not away.
But above all, remember the poor woman, that gave her mite;
which Christ preferred above all, because she gave all she had to God's treasury.

Integrity is a great and commendable virtue.
A man of integrity is a true man, a bold man and a steady man;
he is to be trusted and relied upon.
No bribes can corrupt him, no fear daunt him; his word is slow in coming but sure.
He shines brightest in the fire, and his friend hears of him most when he most needs him.
His courage grows with danger, and conquers opposition by constancy.
He hates flattery in others.
He runs with truth, and not with the times; with what is right and not with might.
It was integrity that preferred Abel's offering, translated Enoch, saved Noah,
raised Abraham to be God's friend and father of a great nation, rescued Lot out of Sodom,
blessed and increased Jacob, kept and exalted Joseph, upheld and restored Job,
honoured Samuel before Israel, crowned David over all difficulties,
and gave Solomon peace and glory, while he kept it;
it was integrity that preserved Mordecai and his people,
and defended Daniel among the lions.
Thus is the scripture fulfilled, the integrity of the upright shall guide them.
O my dear children, fear, love, and obey this great holy and unchangeable God,
and you shall be happily guided and preserved through your pilgrimage to eternal glory.

Self-control I must earnestly recommend to you, throughout the whole course of your life:
it is numbered among the fruits of the spirit and is a great and necessary virtue.
Regarding food, self-control would have you eat to live, and not live to eat.
You cannot be too plain in your diet.
For that which keeps the body low, makes the spirit clear, as silence makes it strong.
It conduces to good digestion, good rest, and a strong constitution.
As in diet so in apparel, I exhort you to exemplary plainness.
Choose your clothes for their usefulness, not for fashion, for covering and not finery,
or to please a vain mind in yourselves or others.
They are fallen souls that think clothes can give beauty to man.
Man cannot mend God's work.
They show little esteem for the wisdom and power of their creator,
that underrate His workmanship to a tailor's invention!
But self-control does not only regard eating, drinking, and apparel,
but also possessions, expenses, business, entertainment, company, speech, sleeping,
as well as every passion of the mind.
Love, anger, pleasure, joy, sorrow, and resentment must all be tempered by self-control.
Therefore learn your will's subjection, and take Christ for your example,
as well as your guide.
It was He that led and taught a life of faith in providence,
and told His disciples the danger of the cares and pleasures of this world.
His sermon upon the Mount is one continued divine
authority in favour of temperance and self-control.
The apostle, well aware of the necessity of this virtue,
gave the Corinthians a seasonable caution: Do you not know, says he,
that those who run in a race all run, but one receives the prize?
Run in such a way that you may obtain it.+++[++++++[+++_en_nkjv_28566]]
And everyone who competes for the prize is temperate in all things.
Now they do it to obtain a perishable crown,
but we for an imperishable crown.+++[++++++[+++_en_nkjv_28567]]
Therefore I run thus: not with uncertainty.
Thus I fight: not as one who beats the air.+++[++++++[+++_en_nkjv_28568]]
But I discipline my body and bring it into subjection, lest,
when I have preached to others, I myself should become disqualified.

I will conclude with this one most comprehensive passage of the apostle, Phil. 4:5:
Let your moderation be known unto all men, for the Lord is at hand.
As if He had said, Take heed!
Look to your ways!
Have a care what you do!
For the Lord is near you, even at the door; He sees you, He marks your steps,
tells your wanderings, and He will judge you.
Let this excellent exhortation live in your minds.
Let it ever dwell upon your spirits, my beloved children, and influence all your actions,
your affections and your thoughts.
It is a noble measure, sufficient to regulate the whole;
they that have it are easy as well as safe.
The world is then kept at arm's length; and such have power over their own spirits,
which gives them the truest enjoyment of what they have:
a dominion greater than that of empires.
O may this virtue be yours!
You have grace from God for that end, and it is sufficient.

William Penn

