== William Evans – Letters from His Parents while at Boarding School

From my mother: 

I hope, my dear children,
you do not forget our anxious concern and solicitude for your good when present with us,
and I trust it has not abated,
but desires are raised that the Lord may be pleased
to take you under his peculiar care and notice,
and that you may indeed be afraid to offend Him in word or action.
Be obedient to those who have the care over you, and kindly affectionate one to another.
Endeavour after stillness, and remember the many favours you receive;
and may the reverent inquiry of your minds be,
What shall I render unto the Lord for all his blessings?
Your dear father desires his love to be remembered to you,
and that you would let us hear from you as often as you can.

With desires for your preservation in the innocency and simplicity of the Truth I conclude.

Your affectionate mother, 

Hannah Evans.

After my beloved father's return from his journey,
he wrote us frequently--from one of his letters the following is taken: 

My Dear Children, 

I have been much concerned on your account for some time past,
understanding several of the boys had given a great
deal of trouble to those who had the care of them;
and though I could scarcely think either of you were of the number,
yet not hearing anything particular, my mind was made very uneasy,
but I hope better things of you.
And if at any time you feel any disquietude of mind,
be patient and endeavour to bear your trials in meekness,
looking with reverent confidence to your great Creator,
who compassionately regards every sigh and tear of the sincere in heart;
whether they be children or more advanced in years.
But then we must also at all times strive to conduct
so as not to grieve the Holy Spirit in our hearts,
which is a continual witness against every evil thought, word or action.
Let your innocent, circumspect deportment be observed by all;
join not with any in the least evil,
but let the fear of the Lord be ever present with you, and that will keep you harmless,
and make you dear unto him and to all good people.

Your mother joins me in near love to you both, desiring your welfare every way.
Your loving father, 

Jonathan Evans.

* * *

Dear Children,

Feeling desirous at all times you may do well,
I cannot but endeavour to revive in your remembrance
the necessity of attending with all diligence,
to the small,
gentle intimations and reproofs of the Holy Spirit of Truth in your own minds.
Keep near to its blessed instructions at all times,
and it will preserve in every season of trial and difficulty,
and as an inexhaustible fountain,
sustain your little minds when depressed with anxious thoughts or discouraging fears.
This is the alone way to happiness here or blessedness hereafter.
For in obedience to this light in our minds,
we are brought to love the Lord our most gracious Redeemer above all,
and by Him are regarded as his children, which is treasure indeed,
that raises the spirit above earthly pleasures,
to a sense of the unspeakable comforts in the regions of immortal bliss.
Here, in this state the fear of death is taken away,
because we know that in the presence of the Lord there is life,
and as we are kept near him, nothing can hurt us.
Now, my dear children, let me earnestly entreat you,
to mind the reproofs which you feel for doing wrong;
this is the Spirit of Truth I have been speaking of, and as you carefully attend to it,
it will lead into all truth--you will fear to offend by a repetition of those things,
for which you have been reproved.
It penetrates through every covering,
and no dissimulation can possibly escape its all-searching power.
Whenever through unwatchfulness you have given way to temptation,
and by the merciful calls of this holy teacher, you become sensible of it, retire alone,
and endeavour to get your minds drawn from every outward thing,
to a reverential waiting upon your Holy Creator for
a renewal of his light and grace upon you,
that you may be strengthened to resist the enemy of all good in his future attempts;
and be sure to avoid those things that have thus beguiled you,
and brought distress upon the tender mind;
for in this watchful state your minds will often be tendered,
and at times sincere petitions will ascend for preservation,
and support in this world of vanity and trouble.

Your affectionate father, 

Jonathan Evans

* * *

Dear Child,

I received your letter, and was glad to hear of yourself and sister being in health,
which is a blessing among the many received, we ought to be thankful for.

Indeed,
many are the obligations we are under to that bountiful
hand from which all our blessings flow.
Let us then evince our gratitude by endeavouring to love Him above all,
and then we shall be afraid to offend Him in thought, word or deed.
My dear child, I feel anxious for your preservation,
and desire you may be careful to associate with such of your school-mates,
as are most seriously inclined; and be sure not to do anything,
in the absence of those who have the care over you,
that you would be afraid they should know,
or that would in any degree wound your own mind.
Learn to love silence; and seek for strength,
that you may be preserved in time of temptation.

With love to yourself and sister, conclude your affectionate mother, 

Hannah Evans.

