== Letters from John Banks to His Children

The following letter I wrote to my daughter, after she was placed at service in London,
in the year 1682.

Sarah Banks, my eldest daughter,

You have been near and dear to me ever since the day you were born,
with a godly care as a tender father,
that you might be nourished up in your young and tender years for your preservation;
with many desires in my heart to Almighty God, that as you grow in years,
he would be pleased to make you sensible and give you an understanding
of those things which make for your everlasting peace,
and the salvation of your soul in the kingdom of glory, when time here shall be no more.

And now, dear child, the Lord having thus far answered my desires,
and enabled me to perform my care towards you;
I have a further concern upon my mind for the good of your soul;
which as you are truly mindful of will tend to your good,
and will never hinder you of anything that is really needful for you.

First of all I would put you in mind, that God,
according to his Divine Wisdom and Providence, gave you life and breath,
which you ought to prize and value as mercies,
amongst many more you have received from him;
and you are also come to an understanding in some degree,
how to behave yourself as a child of God,
by the light and grace of our Lord Jesus Christ,
which he has placed in the secret of your heart, for a teacher to you in all things.
My concern now is to stir you up unto this by way of remembrance;
to be faithful and obedient to its requirings, whether more or less.

This light and grace of our Lord Jesus Christ, teaches you your duty towards God,
to your parents, and to all men and women.
It first teaches you, to fear and love God, and to wait upon, worship,
and serve him with all your mind and strength, that he alone by his Spirit,
manifested in and through Jesus Christ, may be your chiefest love and delight.
It will teach you as you are watchful, to deny all ungodliness and worldly lusts,
to take pleasure and delight in meeting with God`'s people,
to worship him in spirit and truth;
so that you may come more and more to have unity and fellowship with his faithful children,
according to your measure.

This pure light of the Son of God, teaches you to be lowly-minded,
sober and watchful over your words, carriage, and behaviour, in your life and conduct,
and to choose such for your companions; and not those, who though they profess the truth,
are light, careless, and high-minded, and follow the fashions of the world; and tattling,
and tale-bearing,
and meddling with other men`'s and women`'s matters which do not concern them.
Be sure you be found only in what concerns you, and well becomes your place,
being a servant.

This is the way to grow in grace and saving knowledge, and to have the comely adorning,
which is the ornament of a meek and quiet spirit,
which in the sight of God is of great price; and is better than costly attire.
This is the way to be beloved of God, and his people, to grow up a good woman,
and to make a blessed and happy end.
This blessed way and course of life, my soul desires for you, my dear child,
that you may carefully live and keep in it, to the end of your days.
Amen.

The light of Jesus Christ, which thus teaches you your duty towards God,
will also leach you your duty towards all men, women, servants, and children;
especially now in your place where you are a servant.
It will teach you to be faithful, willing, and obedient to your master and mistress,
in all things which are fitting and right;
to be careful that nothing waste under your hand, which is committed to your trust,
nor otherwise; and to watch with an eye for good over all in the family.
If anything else appear, tell it not abroad to any whereby it may cause dissension;
but first tell the party in love, for so you would desire to be dealt with.
This is according to the righteous law of God, which is light,
that teaches to do unto all as we would be done unto;
and when anything happens amiss with yourself, and you are spoken to and reproved for it,
as Paul`'s counsel to Timothy concerning servants was, I exhort you in tenderness,
murmur not, nor answer again, except it be to say it shall be amended.

My dear child, the desire of my heart is unto Almighty God,
that this my counsel and advice may be made effectual unto you;
and that in the serious consideration thereof,
with honest desires raised in you to perform and answer the same,
your heart may be truly broken and tendered before the Lord,
and so kept in all lowliness and humility before him, unto the end of your days.
Amen.

So prays your tender and affectionate father,

John Banks.

While I was in Ireland, I wrote the following letter to my children.

The love of God unto you has been such, as to give you a knowledge of himself,
in and through Jesus Christ, the true and saving light;
and that which is required of you is obedience, and a diligent walking therein,
in all fear, humility and lowliness of mind;
for that greatly tends to make sure the steps, in the way of truth and righteousness;
and it is such the Lord teaches, namely, the humble, by his pure light and grace.
Oh! that a daily care may attend you to follow him in all faithfulness,
in answer to his blessed requirings, whether in words or actions, at home or abroad;
for this is well-pleasing unto him, and a rejoicing unto my soul;
who am still under a weighty concern and tender care for your preservation every way,
in that which is good;
and more especially seeing the Lord has been pleased to take your dear mother from us.
I have no greater joy than to know that you grow in the truth;
and that you are loving and tenderly affectionate one to the other,
in patience and quietness of mind bearing one with another,
in all affairs wherein you are concerned;
so will your undertakings be more easy and comfortable unto you.
Do what in you lies to keep to meetings, and be condescending one to the other therein;
and when you are met together with the Lord`'s people,
let the fear and dread of the Lord be upon you,
that you may be kept in all diligence in waiting upon him,
daily to feel the work of his spirit in your hearts,
to work you into true tenderness and brokenness; that you may grow up,
and bring forth fruit, to the praise and glory of the Lord, and your enduring comfort;
which is my hearty prayer unto the Lord on your behalf.

Farewell, dear children.
Your loving father,

John Banks.
