== A Letter from Francis Howgill to His Daughter Abigail^
footnote:[This letter was written in 1666 from Appleby Jail, two years before his death.]

[.salutation]
Daughter Abigail,

This is for you to observe, and keep, and take heed unto all the days of your life,
for the regulating of your life and conduct in this world; that your life may be happy,
and your end blessed, and that God may be glorified by you in your generation.
These things I bequeath unto you, and counsel you ever to observe,
being the chief things alone I have to bestow upon you,
which I prize more than outward riches.
May you do so also, and observe and keep my sayings; and I charge you before God,
and by the coming of our Lord Jesus Christ, that you observe what I say.
I am moved of the Lord to leave this behind for you,
in tender love and affection unto you, my daughter,
that the Lord may give His blessing unto you, and make your ways prosperous,
and your latter end peace.

First of all, know this: I was never born into great possessions,
nor did I inherit great matters in this world;
but the Lord has always endowed me with sufficiency and enough,
and has been as a tender Father unto me, because my heart trusted in Him,
and did love the way of righteousness from a child.
I have no great portion to bestow upon you of the things of this world;
yet of that little which I have, and God has blessed me with,
there is something I shall give you, which I shall not mention here;
but you will know of it at my decease.
But I commend you to your dear mother, who, I trust, will provide sufficiently for you;
unto whom my heart has been upright before the Lord.
She had a sufficient portion and dowry when I married her,
which I desire not much to lessen or impair;
and whatever was hers (if it please the Lord I die before her) I freely leave unto her,
as was ever my intention and purpose, which has not, nor ever shall change,
through the strength of God--as God only knows, and bears me record.
This shall be manifest unto all in due time, as it is already manifest unto the Lord,
who has been with me in the midst of many troubles, trials, and sufferings,
and has lifted up my head above my adversaries, because I trusted only in his Name;
which at all times I found to be a refuge, and a present help in time of need;
and so it will be unto you, if you fear his Name, and trust in Him forever.

And now, dear child, hearken unto the words of my mouth, and listen unto my counsel.
Ponder these things I leave behind me for you to observe,
that your days may be long upon the earth, and be blessed and comfortable unto you,
and an honor to God in your generation.

The time when you were born and came into the world,
was a time of deep exercise and trouble with me--not from the Lord,
who always spoke peace unto me,
and did sustain me--but by reason of the adversary of mankind,
who always seeks to devour the good in all,
and is the sower of discord and mischief in the hearts of those who fear not the Lord,
neither abide in His counsel.
Into these he enters, as any place is given unto his temptations,
and there he corrupts the mind.
But though there was then a great trial that came upon me,
the Lord kept my heart in uprightness unto Him and gave me much patience.
And though the earth had been removed into the sea,
and all outward things had run into confusion, and nature had changed its course,
yet the Lord gave me a resolution and strength not to be troubled or offended,
because He did support me.
At that time you were born; and therefore I called your name Abigail,
which means the father`'s joy or delight; for in you I was comforted,
and my present trouble was mitigated.

Now, my counsel unto you is that you remember your Creator in the days of your youth,
and fear the Lord in your youth, and learn to know Him and serve Him all your days.
Seek first the kingdom of God, and the righteousness thereof.
His kingdom is not far from you; it is within you.
It consists of life and power, and stands in righteousness, truth, equity, justice,
mercy, long-suffering, patience, love, light, and holiness;
this is the being and centre thereof.
Therefore, seek not the "`lo here`'s`" or "`lo there`'s`" without you,
in this or that outward observation; for many seek there and never find it.
But seek, and you shalt find; wait, and you shall receive.

If you inquire,
'`in what must I seek,`' and '`in what must I wait,`'
and '`how must I seek,`' I inform you:
You must silence all your own thoughts,
and you must turn your mind to that gift which is pure, holy, and good, within yourself.
Seek and wait in that, in the Light of Jesus Christ, wherewith you are enlightened,
and which shows you when you do evil, and checks and reproves.
Take heed unto that, and it will show the evil motions and thoughts; and as you love it,
it will also subdue them, and preserve you out of evil for the time to come.

For though you are born into the world a reasonable creature, yet you must be born again,
and be made a _new_ creature, or else you cannot enter into God`'s kingdom.
You must know the Seed of the kingdom in yourself (of which
you must be born) and be formed again into God`'s image.
I have told you that God has sown it in you-a grain of it, a measure of it,
a portion of it, a measure of Light and Truth, of righteousness and holiness.
Keep turned in your mind to that; love it,
and you will feel the Heavenly Father working in you, and creating you anew unto life,
through Jesus Christ who has enlightened you.
And you will feel the power of the Lord strengthening you in your little,
and making you to grow in the immortal Seed of His kingdom,
and to out-grow and over-grow all evil, so that you will daily die to evil,
and have no pleasure in it, but rather in the Lord,
and in His goodness and virtue shed abroad in your heart,
which you will taste and feel within, and have joy and comfort therein.

Love the Lord with your heart and soul,
even Him that made you and gave you (and all other things in heaven and earth) a being.
Wait for the knowledge of Him in yourself; He is not far from you, but near unto you,
and unto all who call upon Him with an upright heart.
Inquire of your dear mother and she will inform you; she knows Him,
and the way to life and peace; so hearken unto her instruction.

God is a Spirit, a pure Spirit of light, life, and power.
It is He that searches the heart, and shows you when you do evil, or think evil,
or speak evil; and He shows unto men and women their thoughts.
That which shows the evil is good, and that which shows a lie is Truth.
This is within; take heed unto it.
This is called God`'s Spirit in the Scriptures; believe in it, love it,
and it will quicken your heart to good, and also subject the evil.
Here is your teacher near you; love it.
If you act contrary to it, it will condemn you;
therefore take heed unto this Spirit of Truth, and it will enlighten and enliven you.
It will open your understanding, and give you to know what God is,
and to do that which is good and acceptable in His sight.
This Spirit never errs, but leads out of all error and into all truth.

O Abigail, believe my words!
They are the words of God and Truth.
Be not careless, but sober-minded in your youth.
Wait on the Lord within, and hearken unto Him.
God is Light immortal, Life immortal, Truth immortal; an everlasting and eternal Spirit.
He speaks spiritually and invisibly within the hearts and consciences of men and women.
Hear what He speaks and obey His voice, and your soul shall live.
Fear to offend Him, or to sin against Him; for the wages of sin is death.
Therefore prize His love in your young and tender years.

Read the Scriptures and Friends`' books, and take heed unto what you read to obey it,
as far as you understand.
Pray often unto the Lord that He give you His knowledge,
and open your understanding in the things of His kingdom.
Search your heart often with the Light of Christ in you;
manifest and bring your deeds to the Light, that they may be tried.
Examine yourself how the case stands between the Lord and you;
and if you see yourself to be wrong, humble yourself and be sorry.
Turn unto Him, and He will show you mercy;
then take heed for the time to come that you run not into the same evil again.
Keep your heart clean; watch against the evil in yourself in that light which shows it;
therein there is power, and thereby you have power to overcome all evil.

And dear child, mind not the pleasures of sin which are but for a moment,
and their end is misery; but cross and keep under your own will and affections.
Thus your mind will have no pleasure in evil, but only in good;
and you will feel the immortal Seed springing up in you,
to which is God`'s peace and love.

O Abigail! these are great and weighty things, not to be slighted!
Keep company always with those who fear the Lord,
who fear and worship Him in spirit and truth, and lead a holy and a blameless life.
Deny them not, but love them and suffer with them.
And take heed that you follow not the hireling teachers, who preach for gain and riches,
and do not abide in Christ`'s doctrine.
Believe them not, heed them not, for they do people no good;
but you will see them for yourself.
These have an outside show of godliness sometimes,
but deny the power of God and true holiness.
Remember I have told you, as one who has had a perfect knowledge of them.

Be sure that you let nothing separate your love from God and His people.
Those are His people who keep His law, and obey Christ`'s voice, and lead a holy life.
These were ever hated and opposed and persecuted,
and always had evil spoken of them by bad and loose people.
These are God`'s people, and His love and peace and blessing is with them.
Therefore, grow up among them as a natural branch of the living Vine;
and continue all your days in obedience unto God`'s will.
So you will feel joy and love in your heart, which you should pursue above all things,
and you shall attain to and obtain everlasting peace.
May the Lord grant this unto you, according to the riches of His mercy and love,
which endure forever and ever, amen.

And now Abigail, concerning your well-being in this life,
this is my advice and counsel unto you: Love your dear mother,
and always obey and honor her.
See that you grieve her not, nor be stubborn or willful, but submit unto her,
and be as an obedient child to her;
for her love and care has been great over you and your sisters,
which has brought much trouble upon her.
Learn in your youth to read and write a little, and sew and knit,
and all points of good labour that belong to a maid;
and flee all idleness and sloth which nourish sin.
And as you grow up in years, beware of pride, and extravagance, and curiosity;
but be well content with such apparel as your mother will permit you,
in which you may also be a good example unto others.
Be not reckless, nor wild, nor light; but rather temperate, moderate, and chaste,
and not forward in words or speech, but swift to hear, slow to speak.
Always live with your mother,
and be a help to her and cherish her in her old age and latter years,
that she may be comforted in you, and her soul may bless you.
Love your sisters, and be always courteous to them, and to your brother Thomas;
encourage one another in good.

And Abigail, if you live to be a woman of mature years, keep yourself unspotted,
and let not your mind go out after sports and pastimes,
for the end of all these is sorrow; nor seek after young men.
If you have a desire to marry, do not seek a husband, but let a husband seek you;
and if you live an honest and virtuous life in God`'s fear,
then those who fear God will seek after you.
Do not let your affections out after every one that offers love, but be considerate;
and above all things (if you do marry) choose one that loves and fears the Lord,
whose conduct, manner and course of life you know well, before you give consent.
Be discreet and wise.
Hide nothing from your mother, and she will no doubt advise you for your good;
and if she is living, marry not without her consent.
And if you join to a husband, be sure you love him in your heart,
and be obedient unto him, and honor him in the presence of all;
so will his heart be more to you, and his love increase.
Do not grieve him, but be gentle and easily entreated, minding your own business.
And if the Lord gives you children, bring them up in the fear of God,
and in good discipline, keeping them in subjection to you.
And be an example of virtue and holiness unto them,
that you may feel the Lord`'s blessing in youth, and in old age, and all your life long.

O Abigail! remember these things; keep them in mind!
Read over this letter often; get it copied over.
Lay up my words in your heart, and do them;
so you will be happy in this life and in the life to come.
These things I charge you to observe, as expressive of my unalterable mind, and will,
and counsel, unto you; in witness whereof I have set my hand.

[.signed-section-closing]
Your dear father,

[.signed-section-signature]
Francis Howgill

[.signed-section-context-close]
26th of the 5th month, 1666.
