== Letter of Isaac Penington to His Children^
footnote:[This letter was written from Aylesbury Jail.]

[.salutation]
My Dear Children J. J. and M. P.,

Two things I especially desire in reference to your learning--one is,
that you may learn to know and hearken to the voice of God`'s witness in you.
There is something in you that will teach you how to do well, and how to avoid evil,
if your minds are turned to it.
And the same thing will witness to you when you do well,
and will witness against you when you do evil.
Now to learn to know this, to hear this, to fear this, to obey this,
that is the chief object of learning that I desire to find you in.
And when your master, or anyone of the family, turns you to this witness,
or reminds you of this witness,
or reproves you for not hearkening to or obeying this witness, oh love them,
and bless God for them in that respect!
And remember this, that he that hearkens to reproof is wise,
but he that hates or slights reproof is brutish.
That is the dark spirit, which desires to please itself in its dark ways,
and therefore loves not the light which makes his ways manifest and reproves them.
It is the brutish spirit which hates the reproof of the light,
and would continue its vain foolish ways and delights, which the light testifies against.
Therefore, mind the witness of God in your hearts which discovers these things to you,
and leads you out of them as you hearken to it, and come to know, fear,
and love the Lord God by his instruction and testimony.

The way of youth is vain and foolish, and it defiles the mind.
Oh my children, wait for the cleansing.
Watch for that which cleanses the foolish way of children,
which is the light that uncovers and witnesses against your foolishness and vain tempers,
and the temptations of your minds, and leads out of them.
Learn to bear the yoke in your tender years.
There is a vain mind in you,
and there is something which desires to feed and please that vain mind.
But there is something near you and appointed by God to yoke it down.
Oh give no place to vanity, for it will be an occasion of woe and misery to you hereafter.
But the yoke which keeps down the vain mind, oh take that yoke upon you.
For then you shall become not only my children, but the disciples of Christ,
and children of the Most High.
This is the first thing which I mainly and chiefly
desire you should apply yourselves to learn.

The next thing (which will also flow from the first),
is that you learn how to behave yourselves as good children,
both in the family and to persons abroad, in a meek, modest, humble, gentle, loving,
tender, respectful way.
Avoid all rude, rough, bold, unbecoming carriage towards all.
Honor your mother and me as God teaches and requires,
and dearly cleave to one another in the natural relation, which is of God,
wherein you are loved,
having a great proportion of natural affection and kindness one to another.

With the servants, carry yourselves very lovingly, sweetly, meekly, and gently,
so that none may have any cause of complaint against you,
but that all may see your lowliness and be drawn to love you.
And to strangers, carry yourselves warily, respectfully, in a sober, submissive,
humble manner of demeanor.
Do not be disputing and talking much, which is not fitting for your age and place.
Rather, watch what you may observe of good in others,
and what you may learn of those that are good.
And watch also to see how you may avoid any such evil as you observe in any that are evil.
In this way your time will be spent in profit,
and you will feel the blessing of God and of your parents,
and you will be kept out of those evils which your
age and natural tempers are subject to,
and which other children (who are not careful nor watchful) are commonly entangled in.
Mind these things, my children, as you will give an account to God,
who through me thus instructs you--who am your imprisoned father.
I am much grieved when I hear of any ill concerning you.
For this is more a matter of trouble and sorrow to me than my imprisonment,
or anything else I suffer, or can suffer from man.

And remember this one thing, which as a father I admonish you of,
and charge you to take notice of and observe,
which is this--that you do not fly out upon one another, or complain of one another,
because of the evils you observe in one another.
But rather, first take notice of the evil in yourselves.
If by the true light you find your own hearts cleansed from it,
bless God who has done it, and keep to his light and witness in you whereby he did it,
and watch that you are not overtaken by it in the future.
But if you be guilty of the same evil, or have lately done the same thing,
or are liable suddenly to do it--then oh, forbear accusing or blaming another!
In the fear of God wait on him, and pray unto him that you may be delivered from it,
and kept out of it.
And then, in tender pity, love, and meekness,
admonish your brother or sister of his or her evil,
and watch to be helpful to preserve or restore them.
And pray to God to direct you how to be helpful to them.
But it is the bad spirit and nature which is ready to accuse others.
And even when it has never been so bad and guilty, yet it will be excusing itself,
and laying the fault upon others, or remembering some other fault of another,
when it should be sensible of and ashamed of its own.

Dear children, if you bend your minds to learn these things,
the Lord will help you therein, and he will become your teacher, guide and preserver,
and pour down his blessings upon you.
And in this you will be a comfort to me and your mother, and an honor to his Truth.
And may he also give me wise fatherly instructions to teach you further.
But if you be careless, foolish, vain, following your own minds,
and what rises up there from the wicked one,
you will grieve my heart and provoke God against you, to bring evil upon you,
both in this world and forever.

Therefore, children, mind that which is near you--the light of God,
which discovers the evil and the good.
His witness (which observes all you do) is near you.
Yes, he himself is in that light, and with that witness.
Therefore, know that you are in the presence at all times of a holy and just God,
who hates that which is vain and evil, and loves that which is good and right before him.
And he has appointed a day and set a time wherein he will either reward you with peace,
joy, and eternal happiness if you have been good and done that which is good;
or with misery, destruction, and insufferable pain both of soul and body,
if you have been evil and done that which is evil.
God knows well how many instructions you have heard from friends in Truth,
and from your parents,
and how many meetings you have been at wherein you
have been taught and warned of these things.
So if you turn your back upon his light, and will not hear its reproofs,
but will rather be vain, idle, foolish, rash, quarreling,
and doing that which is wrong and then covering it with lies, (and so be as bad,
if not worse, than children who were never thus taught and instructed)--then,
in his just judgment and sore displeasure,
God may separate you from his light and give you up to the black, dark spirit,
(from whom all this wickedness is) to sow in sin here,
and to suffer the flames of eternal fire hereafter.
For this is the reward of the dark spirit,
and also the reward of all who are persuaded by him to be of his nature,
and who hearken to him, and let him work through them.

Oh my children, mind the Truth of God in you!
He will let you see and understand the truth of what I now write,
and in what fatherly love and tender care of you I write these things.
Oh, be warned of the great danger of neglecting the time of
your visitation by God`'s light and witness in you!
And do not go on in the evil ways of the dark, crooked spirit,
who will be tempting you to evil and hindering you
from God as long as you hearken to him.
Therefore,
be not fools to be led by him to destruction in the
evil way and evil works which lead thereto;
but be wise to hearken to the light, and follow it out of that which is evil,
into everything that is good, to the salvation of your souls.

I desire that Friends in the family^
footnote:[The remainder of this letter is not directed to his children,
but to other Friends who lived in his house, and to Gulielma, his step-daughter,
and afterwards the wife of William Penn.]
watch over them in these respects; and when they find just occasion,
to put them in mind of any of these things, in the fear and wisdom of God,
with tenderness and gentleness.
But take heed of upbraiding or aggravating them, lest they be thereby hardened,
and evil is raised and strengthened in them.
And, my dear G. +++[+++doubtless his step-daughter, Gulielma,
afterwards the wife of William Penn]
and Friends, watch over your hearts and ways, that you may be as examples to them,
so that they may not only read these things from my writing,
but also in your carriage towards them and towards one another.
So the Lord bless your watchfulness, care, and endeavors therein,
that I may hear good concerning them,
and be comforted in the mercy and kindness of the Lord towards them.

Your father, who desires your good, and that it may go well with you,
both here and hereafter.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
10th of Third month, 1667
