== John Crook`'s Advice to His Children and Grandchildren / Written Close to His Death

Dear Children,

I must leave you in a wicked age,
but commit you to the measure of the grace of God in your inward parts,
which you have received by Jesus Christ; and as you love it,
and mind the teachings of it,
you will find it a counsellor to instruct you in the way everlasting,
and preserve out of the ways of the ungodly.

I have seen much in my days,
and I always observed that the fear of the Lord God proved the best portion,
and those that walked in it, were the only happy people,
both in this life (while they continued faithful) and when they come to die,
though they meet with many hardships in the passage.
By experience I can speak it,
that the ways of holiness afford more true comfort and peace to the upright soul,
than the greatest pleasures this world can afford; the former reaches the heart and soul,
while the delights of this world are but a show, and appearance only,
vanishing like a dream; and whoever believes otherwise of them,
will certainly find them to be but lying vanities;
therefore the apostle might boldly put the question to the converted Romans+++[++++++[+++__ddelink__14951_21906343]],
"`What fruit had you then in those things whereof you are now ashamed?
for the end of those things is death.`"

Therefore, dear children, be in love with holiness; make it your companion,
and those that walk in it; you may find buddings of it, from a holy seed in your hearts;
as you mind the inner man, the light will manifest the stirrings of it after God,
which I felt from my tender years; although I understood them not so plainly,
till I heard the truth declared.

I advise you to keep a pure conscience, both toward God and man; for if that be defiled,
hypocrisy and formality will deprive you of all comfortable feeling of God's presence;
and then deadness and dryness will be your miserable portion.

Be careful of how you spend your precious time,
for an account must be given of every idle word, though but few regard it;
but foolish jesting, and vain talking, are said to grieve the spirit of God.
But improve your time in prayer, and religious exercises,
and be diligent in your lawful callings,
for "`The desire of the slothful man kills him.`"

Be careful what company you keep; for a man is commonly known by the company he keeps,
as much as by any one outward thing; and of your behaviour in company; for I have found,
that a wise and sober deportment adds much to a man's reputation and credit in the world.

Watch to the light, and its discoveries of good and evil,
that you may not be ignorant of Satan's devices;
so the net will be spread in vain in the flight of the bird;
for watchfulness will make you in love with a retired estate;
and the more truly and perfectly any man knows and understands himself,
the better discerning will such have of other men; as in the beginning,
when deep silence of all flesh was more in use, the spirit of discerning was more common,
and quicker, than since it has been neglected; therefore be sure you spend some time,
at convenient seasons, in waiting upon God in silence, though it be displeasing to flesh;
for I have had more comfort, and confirmation in the truth,
in my inward retiring in silence, than from all words I have heard from others,
though I have often been refreshed by those also.

Love the holy scriptures, preferring them to all other books whatsoever;
and be careful to read them with a holy awe upon your spirits,
lest your imaginations put constructions upon them to your hurt;
but execute faith in the promise of Christ, who hath said,
"`My spirit shall take of mine, and show them unto you.`"

Keep constantly to religious meetings amongst Friends; but look to your affections,
that you respect not persons, but the power and life of truth, from whomsoever it comes;
not minding the tickling of your affections,
but the demonstration of the truth to your understandings and consciences;
for that will abide when flashes of affections will fade and come to nothing,
after the words are ended.

Love one another truly, manifesting your love by good counsel;
and being helpful to each other upon all occasions;
being good examples to all you converse with, especially to your children,
and those of your own families, that pride and vanity may not be countenanced by you,
but rather reproved; remembering, while they are under your government,
you must give an account of the discharge of your duty to God towards them.

Lastly, Be always mindful of your latter end, and live as you would die,
not knowing how soon your days may be finished in this world:
and while you do live in it, despise not the chastenings of the Lord, whatever they be,
he is pleased to visit you with.
I have been afflicted from my youth up, both inwardly and outwardly,
but God whom I served, provided for me, when all my outward relations forsook me.
I need not mention this affliction in my old age, because, in some measure, you know it;
but I could not have been without it, as the Lord has shown me,
for I have seen his wonders in the deeps: therefore I say again, despise not afflictions,
but embrace them as messengers of peace to your souls (though displeasing to the flesh.)

These things I commend unto you, out of true love to your souls,
knowing how the vain mind of man little regards such advice as this I leave behind me:
but by this advice I show my true love to you, desiring God's blessing upon it;
to whom I commit you all, my dear children, and end my days.

Your loving father and grandfather,

John Crook

== A Letter of Richard Shackleton to His Daughter Mary

Be careful, my beloved Mary, to centre deep in humility and abasement of self;
it is the tree which takes deep root downwards that
is most likely to stand against the storm.
This is the springtime of your life; may your tender,
innocent heart be open to receive the precious seed,
which I trust the great and good Husbandman will condescend, and has condescended,
to sow therein; may He also be pleased to water it with visitations of love,
immediately and instrumentally; may He guard and protect it from every noxious thing!
You see how your older sisters have made choice of religion, as their principle treasure.
You also be a wise child;
and whatever natural abilities it may please the great Creator to endow you with,
or whatever acquisitions or improvements you make of those natural gifts,
by contemplation, reading, or conversation, remember,
you are only acceptable in the sight of Heaven, (no matter how man may esteem you),
as you take heed to the grace in your own heart, to be restrained by its restraints,
to do nothing contrary to its gentle remonstrances, and to obey,
in humility and simplicity, its leadings and requirings. 

My dear child, above all things, be humble, be humble.
Humility goes before honour; it is the humble whom the Lord teaches of his ways.
We have in each of us a certain something, appertaining to self,
(it is of the flesh,) which profits nothing in the work of religion.
This fleshy part is pleased and nourished,
and swells with the praise and commendation of fools, for wise men would not puff up.
We have need of frequent retirement to the gift, the grace in our minds,
that in the tranquil, cool hour of the day, not inflated by vain knowledge,
or perturbed by passion, we may, in the stillness of all flesh, hear what this Monitor,
this good Spirit, this faithful Witness, says to our states.
Perhaps when figuratively speaking, all men speak well of us, this heavenly, sure,
unerring word of prophecy, which preaches to our own particular states as individuals,
will condemn or reprove us.
This is what we are to go by, and to judge and estimate ourselves by;
and not by the crude, superficial, hasty,
partial judgment of capricious mortals whose favour veers about like the wind.
My mind is often exercised on behalf of my children.
You are the children of many prayers.
You have hitherto been a great comfort to your dear mother and me,
and we have no greater joy than to seek your walk in the Truth.
It is neither in our will, nor in our power, to do great things as to this world for you.
We are not like many others who have large possessions and lucrative business.
Providence, in the wise distribution of his favours,
has allotted us a lower rank in life; yet, with industry, care, and prudent economy,
he has enabled us to procure a sufficiency.
And indeed a great redundancy is not desirable;
the lip of truth has pronounced how hard it is for a rich man to enter the kingdom.
A little sufficiency of the things of this life, enjoyed in moderation,
and under a renewed sense of the Divine blessing, is all that I think we should wish for,
and when obtained, should be cause of deep, and humble,
and fervent gratitude to our great Benefactor.

Thy truly affectionate father,

Richard Shackleton

== William Penn`'s Advice to His Children and Grandchildren

=== Part One

My Dear Children:

Not knowing how long it may please God to continue me among you,
I am willing to embrace this opportunity of leaving you my advice
and counsel with respect to your Christian duty in this world.
And I both beseech you and charge you, by the relation you have to me,
and the affection I have always shown to you, and indeed received from you,
that you lay up the same in your hearts, as well as your heads,
with a wise and religious care.

I will begin with that which is the beginning of all true
wisdom and happiness - the holy fear of God.

Children, Fear God; that is to say,
have a holy awe upon your minds to avoid that which is evil,
and a strict care to embrace and do that which is good.
By the light of Christ in your consciences, you may clearly see if your deeds,
and your words and thoughts, too, are wrought in God or not.
With this divine light of Christ in your consciences, you may bring your thoughts, words,
and works to judgment in yourselves, and have a right, true, sound,
and unerring sense of your duty towards God and man.
And as you come to obey this blessed light in its holy convictions,
it will lead you out of the world's dark and degenerate ways and works,
and bring you unto Christ's way and life, and to be of the number of his true,
self-denying followers, to take up your cross for his sake, that bore his for yours,
and to become the children of the Light, putting it on as your Holy armour,
by which you may see and resist the fiery darts of Satan's temptations,
and overcome him in all his assaults.

I would explain this principle to you:
It is called Light because it gives man a sight of his sin;
and it is also called the Quickening Spirit, for so he is called;
and the Lord from heaven is called and calls himself the Light of the world;
and why is he called the Spirit?
Because He gives man spiritual life.
And Christ promised to send his spirit to convince the world of their sins.
Wherefore, that which convinces you and all people of their sins is the spirit of Christ.
God sent his Son to bless us, in turning us from the evil of our ways.
Therefore have a care of evil, for that turns you away from God;
and wherein you have done evil, do so no more.
But be turned, my dear children, from that evil in thought, as well as in word or deed,
or that will turn you from God your Creator,
and Christ whom he has given you for your redeemer;
who redeems and saves his people from their sins, not in their sins.
This holy, divine principle is called grace, too;
there you will see the nature and office of it,
and its blessed effects upon those that were taught of it in the primitive days.
And why Grace?
Because it is God's love, and not what we deserve; it is his good will, his kindness.
For God so loved the world that he gave his only begotten Son,
that whosoever believeth in him should not perish, but have everlasting life.
And it is this holy Son, that in John 1:14, is declared to be full of grace and truth,
and that of his grace we receive grace for grace; that is,
we receive of him the fullness, what measure of grace we need.
And the Lord told Paul in his great trials,
when ready to stagger about the sufficiency of the grace he had received to deliver him:
My grace is sufficient for you.
Oh, children! love the grace, hearken to this grace; it will teach you,
it will sanctify you, it will lead you to the rest and kingdom of God;
as it taught the saints of old, first, what to deny;
to deny ungodliness and worldly lusts; and then what to do; to live soberly, righteously,
and godly in this present world.
I am the Way, the Truth, and the Life, said he to his poor followers;
and if the truth makes you free, then are you free indeed.
And this truth sheds abroad itself in man, and begets truth in the inward parts,
and makes false, rebellious, hypocritical man a true man to God again.
Truth in the inward parts is of great price with the Lord.
And why called Truth?
Because it tells man the truth of his spiritual state; it shows him this state,
deals plainly with him, and sets his sins in order before him.
So that, my dear children, the light, spirit, grace,
and truth are not different principles,
but different words given to one eternal power and heavenly principle in you,
though not of you, but of God.
Light, to discover and give discerning; Spirit, to quicken and enliven; Grace,
to witness the love of God; Truth, because it tells man the truth of his condition,
and redeems him from the errors of his ways; so that as darkness, death, sin,
and error are the same, so light, spirit, grace, and truth are the same.

O, my dear children! this is the pearl of price; part with all for it,
but never part with it for all the world.
This is the gospel which will sanctify you in body, soul, and spirit,
to God your heavenly Father's use and service, and your own lasting comfort.
Yes, this is the divine incorruptible seed of the kingdom,
of which all truly regenerate men and women, Christians of Christ's making are born.

Receive it into your hearts, give it room there, let it take deep root in you,
and you will be fruitful unto God in every good word and work.
As you take heed to it, and the holy enlightenings and motions of it,
you will have a perfect discerning of the spirit of this
world in all its appearances in yourselves and others;
the motions, temptations, and workings of it, as to pride, vanity, covetousness, revenge,
uncleanness, hypocrisy, and every evil way;
you will see the world in all its shapes and features,
and you will be able to judge the world by it,
and the spirit of the world in all its appearance; you will see, as I have done,
that there is much to deny, much to suffer, and much to do;
and you will see that there is no power or virtue but in the light, spirit, grace,
and truth of Christ,
to carry you through the world to God's glory and your everlasting peace.
Yes, you will see what religion is from above, and what is from below;
what is of God's working, and of man's making and forcing; also,
what ministry is of his spirit and giving, and what is of man's studying, framing,
and imposing.

And be sure that you forsake not the assembling yourselves with God's people,
as is the manner of some in this day,
especially among young people whom the love of this present evil
world has hurt and cooled their love to God and his truth.
But keep close to meetings, not out of novelty, formality, or to be seen of men,
but in pure fear, love, and conscience to God your creator, as the public, just,
and avowed testimony of your duty and homage to him, in which be exemplary,
both by timely coming and a reverent and serious deportment during the assembly.
Be not weary in meetings, or think the time long till it be over,
but let your eye be to him you come to wait upon and serve, and do what you do as to him,
and he will be your refreshment and reward;
for you shall return with the seals and pledges of his love, mercy, and blessings.

Above all things, my dear children,
as to your communion and fellowship with fellow Christians,
be careful to keep the unity of the faith in the bond of peace.
Beware of those who undervalue and undermine brethren behind their backs,
or slight the good and wholesome order of truth for the preserving things quiet, sweet,
and honourable in the church.
Beware of airy and changeable people, the conceited, censorious, and puffed up,
who at last have always shown themselves to be clouds without rain,
and wells without water,
that will rather disturb and break the peace and fellowship of the church
where they dwell than not have their wills and way take place.
I charge you, in the fear of the living God, that you carefully beware of all such;
have no fellowship with them, but to advise, exhort, entreat, and finally reprove them;
for God is and will be with his people in this holy dispensation we are now under,
and which is now among us unto the end of days.
It shall grow and increase in gifts, graces, power, and lustre,
for it is the last and unchangeable one; and blessed are your eyes, if they see it,
and your ears, if they hear it, and your hearts, if they understand it,
which I pray that you may, to God's glory and your eternal comfort.

Having thus expressed myself to you, my dear children, as to the things of God,
his truth and Kingdom, I refer you to his light, grace, spirit, and truth within you,
and the holy scriptures of truth without you, which from my youth I loved to read,
and were ever blessed to me, and which I charge you to read daily;
the Old Testament for history chiefly; the Psalms for meditation and devotion;
the Prophets for comfort and hope; but especially the New Testament for doctrine, faith,
and worship.
For they were given forth by holy men of God in diverse ages,
as they were moved of the Holy Spirit,
and are the declared and revealed mind and will of
the holy God to mankind under diverse dispensations.
They are certainly able to make the man of God perfect, through faith unto salvation;
being such a true and clear testimony to the salvation that is of God, through Christ,
the second Adam, the light of the world, the quickening spirit,
who is full of grace and truth, whose light, grace, spirit,
and truth bear witness to them in every sensible soul, as they frequently,
plainly and solemnly bear testimony to the light, spirit, grace,
and truth both in himself and in and to his people, to their sanctification,
justification, redemption, and consolation, and in all men to their visitation, reproof,
and conviction of their evil ways.
I refer you, my dear children, to the light and spirit of Jesus, that is within you,
and to the scriptures of truth without you,
and such other testimonies to the one same eternal truth as have been borne in our day,
that you may more directly apply what I have said to your pilgrimage upon earth.

=== Part Two

As soon as you wake,
retire your mind into a pure silence from all thoughts and ideas of worldly things,
and in that frame wait upon God, to feel His good presence,
to lift up your hearts to Him,
and commit your whole self into his blessed care and protection.
Then rise, and being dressed, read a chapter or more in the Scriptures,
and afterwards dispose yourselves for the business of the day,
ever remembering that God is present as the overseer of all your thoughts, words,
and actions.
Demean yourselves, my dear children, accordingly, and do not dare to do that in his holy,
all-seeing presence, which you would be ashamed a man would see you do.
And as you have intervals from your occupations,
delight to commune with your own hearts and be still.
As Nebuchadnezzar said on one occasion,
One like the Son of God you shall find and enjoy with you and in you:
a treasure the world knows not of, but is the aim, end,
and diadem of the children of God.
This will bear you up against all temptations,
and carry you sweetly and evenly through your day's business,
supporting you under disappointments,
and moderating your satisfaction in success and prosperity.
In the evening, read again the Holy Scripture,
and have your times of retirement before you close your eyes, as in the morning;
that so the Lord may be the Alpha and Omega of every day of your lives.
And if God bless you with families,
remember good Joshua's resolution - But as for me and my House, we will serve the Lord.

Fear God; show it in all that you desire, do, and refrain from doing.
Keep the inward watch; keep a clear soul and a light heart.
Mind an inward sense upon doing anything.
When you read the Scripture,
mark the places where your spirits are most touched and affected, in a common-place book,
with that sense or opening which you receive;
for they come not by study or in the will of man, no more than the Scripture did;
and they may be lost by carelessness and overgrowing thoughts,
and businesses of this life.
In perusing any other good or profitable book, rather meditate than read much. 

In conversation, mark well what others say or do, and hide your own mind,
at least till last, and then open it as sparingly as the matter will let you.
A just observance and reflection upon men and things gives wisdom.
Be always on your watch, but chiefly in company; then be sure to keep your armour on.
Speak last and little, but to the point; interrupt no one.
Be quick to hear, slow to speak.
It gives time to understand and ripens an answer.
Speak clearly to make yourselves easily understood by everybody,
and in as few words as the matter will admit of is best.

Return no answer to anger, unless with much meekness, which often dispels anger.
Rarely make replies, especially sharp replies, for that adds fuel to the fire.
It is a wrong time to vindicate yourselves, the true ear being then never open to hear it.
Men know not well what spirits they are of.
Silence to passion, prejudice, and mockery, is the best an answer,
and often conquers what resistance inflames.

Be plain in clothes, furniture, and food; excess is a folly and a snare.
Avoid daintiness and choiceness about your persons and houses;
for if it be not an evil in itself, it is a temptation to it.

Prefer elders and strangers on all occasions;
be rather last than first in conveniency and respect, but first in all virtues.

Above all, remember your Creator in the youthful time and forepart of your life;
for good methods and habits obtained then will make
you easy and happy the rest of your days.
Beware of the lusts of the eye, and the flesh, and the pride of life,
which are not of the Father, but of the world.
Oh, my dear children! be not tied to external things;
for then you can never have the true and free enjoyment of yourselves to better things.
The pomp, honour, and luxury of the world are deceptive,
and the unthinking and inconsiderate are taken by them.
But the retired man is upon higher ground; he sees and is aware of the deception,
condemns the folly, and bemoans the deluded.

Have but few books, but let them be well chosen and well read,
whether of religious or civil subjects.
Measure both religion and learning by practice; reduce all to that,
for practice alone brings a real benefit to you; the rest is a thief and a snare.
And indeed, reading many books takes the mind too much from meditation.
Reading yourselves and nature is the truest human wisdom.
The spirit of a man knows the things of man,
and more true knowledge comes by meditation and reflection than by reading.
Much reading is an oppression of the mind and extinguishes the natural candle,
which is the reason of so many senseless scholars in the world.

Do not that which you blame in another.
Do not that to another which you would not another should do to you; but above all,
do not that in God's sight which you would not want man to see you do.

Keep close to the meetings of God's people; wait diligently in them,
to feel the heavenly life in your hearts.
Look for that more than words in ministry and you will profit most.
Above all, look to the Lord, but despise not instruments, man or woman, young or old,
rich or poor, learned or unlearned.

Excuse faults in others, own them in yourselves, and forgive them against you yourselves,
as you would have your heavenly Father and Judge forgive you. 

Love silence, even in the mind; for thoughts are to the mind as words are to the body,
troublesome; much speaking, as well as much thinking, spends; and in many thoughts,
as well as in many words, there is sin.
True silence is the rest of the mind, and is to the spirit what sleep is to the body,
nourishment and refreshment.
It is a great virtue; it covers folly, keeps secrets, avoids disputes, and prevents sin. 

Never meddle with other folks' business, and less with the public,
unless called to the one by the parties concerned,
in which move cautiously and uprightly,
and required to the other by the Lord in a testimony for his name and truth.
He lives happily that lives hiddenly or privately, for he lives quietly.
It is a treasure to them that have it.
The world knows not the value of quiet living;
it doubles man's life by giving him twice the time to himself
that a large acquaintance or much business will allow him.

Envy none; it is God that makes rich and poor, great and small, high and low.
Beware of jealousy, for it devours love and friendship;
it breaks fellowship and destroys the peace of the mind.
It is a groundless and evil surmise.

Meddle not with government; seldom speak of it; let others say or do as they please.
For much knowledge brings sorrow, and much doings more.
Therefore know God, know yourselves; love home, know your own business and mind it,
and you have more time and peace than your neighbours.

If you incline to marry, then be not hasty, but serious; lay it before the Lord,
proceed in his fear, and be well advised.
And when married, avoid occasion of misunderstanding;
allow for weaknesses and variety of constitution and disposition,
and be careful not to show the least disgust or misunderstanding to others,
especially your children.
Never lie down with any displeasure in your minds,
but avoid occasion of dispute and offence; overlook and cover failings.
Seek the Lord for one another; wait upon him together, morning and evening,
in His holy fear, which will renew and confirm your love and covenant;
give way to nothing that would in the least violate it; use all means of true endearment,
that you may recommend and please one another,
remembering your relation and union is the figure of Christ to his church; therefore,
let the authority of love only bear sway your whole life.

If God gives you children, love them with wisdom, correct them with affection;
never strike in passion, and suit the correction to their age as well as fault.
Convince them of their error before you chastise them;
if they show remorse before severity,
never use that but in case of obstinacy or impenitence.
Punish them more by their understandings than the rod, and show them the folly,
shame and undutifulness of their faults rather with a grieved than an angry countenance,
and you will sooner affect their natures, and with a nobler sense,
than a servile and rude chastisement can produce.
I know the methods of some are severe corrections for faults,
and artificial praises when they do well, and sometimes rewards:
but this course awakens passions worse than their faults; for one begets base fear,
if not hatred; the other pride and vain glory,
both which should be avoided in a godly upbringing of youth.
There should be the greatest care imaginable, what impressions are given to children;
that method which earliest awakens their understandings to love, duty, sobriety,
just and honourable things, is to be preferred. 

=== Part Three

Be humble.
It becomes a creature, a depending and borrowed being, that lives not of itself,
but breathes in another's air with another's breath,
and is accountable for every moment of time and can call nothing its own,
but is absolutely a tenant at will of the great Lord of heaven and earth.
And of this excellent quality you cannot be wanting,
if you dwell in the holy fear of the omnipresent and all-seeing God;
for that will show you your vileness and His excellency, your baseness and His majesty,
and the sense of His love to such poor worms,
in the testimonies He gives of His daily care, and mercy and goodness;
that you cannot but be abased, laid low and humble.
The fear and love of God begets humility, and humility fits you for God and men.
You cannot step amiss if this virtue dwell richly in you; for then God will teach you.
The humble He teaches his ways.
Humility seeks not the last word, nor first place; it offends none, but prefers others,
and thinks lowly of itself; is not rough or self-conceited, high, loud, or domineering.
Learn of me, said Christ, for I am meek and lowly in heart.
He washed His disciples' feet, and indeed was himself the greatest pattern of humility.
There is nothing that shines more clearly through Christianity than humility;
of this Christ was the greatest example.
Indeed His whole life was one continued great act of self-denial,
thereby leaving us an example that we should follow His steps.
And the more to illustrate this virtue,
I would have you consider the folly and danger of pride, its opposite.
Pride is the vainest passion that can rule in man,
because he has nothing of his own to be proud of.
He did not only not make himself,
but is born the most naked and helpless of almost all creatures.
He is so absolutely in the power of another, that as I have often said,
he is at best but a tenant at will of the great Lord of all, holding life, health,
substance, and everything at his sovereign disposal; and the more man enjoys his Creator,
the less reason he has to be proud,
because he is the more indebted and engaged to thankfulness and humility.
Wherefore avoid pride as you would avoid the devil; remembering you must die,
and consequently those things must die with you, that could be any temptation to pride.

From humility springs meekness.
The difference is not great between these excellent graces,
yet the scripture observes some.
God will teach the humble his way, and guide the meek in judgment.
It seems to be humility perfectly digested, and from a virtue becomes a nature.
A meek man is one that is not easily provoked, yet easily grieved; not peevish or testy,
but soft, gentle, and inoffensive.
How blessed will you be, my dear children, if this grace adorns you!
There are diverse great and precious promises to the meek in scripture.
God will clothe the meek with salvation,
and blessed are they for they shall inherit the earth.
Christ presses it in his own example: Learn of me for I am meek. 

Patience is an effect of a meek spirit and flows from it.
It is a bearing and suffering disposition; not easily moved to wrath, or vindictive;
but ready to hear and endure, rather than be swift and hasty in judgment or action.
Without it there is no running the Christian race, or obtaining the heavenly crown;
without it there can be no experience of the work of God.
Therefore, says James, let patience have its perfect work.
Patience is wise and will give you great advantage
over those you converse with on all accounts.
For passion blinds men's eyes, and betrays men's weakness;
patience sees the advantage and improves it.
Patience inquires, deliberates and brings to a mature judgment;
you cannot act wisely and safely without it;
therefore I recommend this blessed virtue to you.

Show mercy, whenever it is in your power, that is forgive, pity and help.
Mic. 6: 8: He has shown you O man what is good, and what the Lord requires of you,
to do justly, and to love mercy and to walk humbly,
or to humble yourself to walk with you God: a short but ample expression of God's love,
and man's duty; happy are you if you mind it.
Remember the nature and goodness of Joseph to his brethren;
follow the example of the Good Samaritan.

Charity is a near neighbour to mercy: it consists is not being overly critical of others,
and to relieve the poor.
For the first, remember you must be judged.
And for the last, remember you are but stewards.
Judge not, therefore, lest you be judged.
Be clear yourselves before you fling the stone.
Get the beam out of your own eye; it is humbling doctrine, but safe.
Judge, therefore, at your own peril: see that be righteous judgment,
as you will answer it to the Great Judge.
This part of charity also excludes whisperings, backbiting, talebearing,
and evil-surmising.
For the other part of charity, relieving the poor, it is a debt you owe to God.
The saying is, that he who gives to the poor, lends to the Lord: but it may be said,
not improperly, the Lord lends to us to give to the poor.

I especially recommend little children, widows, sick and elderly persons to you:
spare something from your own table rather than let them go hungry.
Avoid that great sin of needless expense on yourselves and your own houses,
while the poor are hungry and naked.
I have often been moved to see very aged and sick people,
but especially poor helpless children,
lie all night in bitter weather at the thresholds of doors, in the open streets,
for want of better lodging.
I have made this reflection, if you were so exposed, how hard would it be to endure?
The difference between our condition and theirs has drawn from me humble thanks to God,
and great compassion to those poor creatures.
Be good to the poor; be just to them, and think it your duty.
Let the moving passage, Matt. 25:35 live in your minds:
For I was hungry and you gave Me food; I was thirsty and you gave Me drink;
I was a stranger and you took Me in.
Psalm 41: Blessed is he that considers the poor,
the Lord will deliver him in time of trouble: the Lord will preserve and keep him alive,
and he shall be blessed upon the earth.
This is the reward of being faithful stewards and treasurers for the poor of the earth.
Beware of excuses; they are, I know, ready at hand; but read Prov. 3:27:
Withhold not good from those to whom it is due,
when it is in the power of your hand to do so.
Say not unto your neighbour, Go, and come again, and tomorrow I will give,
when you have it with you.
Also bear in mind Christ's doctrine, Matt. 5:42: Give to him that asks you,
and from him that wants to borrow of you, turn not away.
But above all, remember the poor woman, that gave her mite;
which Christ preferred above all, because she gave all she had to God's treasury.

Integrity is a great and commendable virtue.
A man of integrity is a true man, a bold man and a steady man;
he is to be trusted and relied upon.
No bribes can corrupt him, no fear daunt him; his word is slow in coming but sure.
He shines brightest in the fire, and his friend hears of him most when he most needs him.
His courage grows with danger, and conquers opposition by constancy.
He hates flattery in others.
He runs with truth, and not with the times; with what is right and not with might.
It was integrity that preferred Abel's offering, translated Enoch, saved Noah,
raised Abraham to be God's friend and father of a great nation, rescued Lot out of Sodom,
blessed and increased Jacob, kept and exalted Joseph, upheld and restored Job,
honoured Samuel before Israel, crowned David over all difficulties,
and gave Solomon peace and glory, while he kept it;
it was integrity that preserved Mordecai and his people,
and defended Daniel among the lions.
Thus is the scripture fulfilled, the integrity of the upright shall guide them.
O my dear children, fear, love, and obey this great holy and unchangeable God,
and you shall be happily guided and preserved through your pilgrimage to eternal glory.

Self-control I must earnestly recommend to you, throughout the whole course of your life:
it is numbered among the fruits of the spirit and is a great and necessary virtue.
Regarding food, self-control would have you eat to live, and not live to eat.
You cannot be too plain in your diet.
For that which keeps the body low, makes the spirit clear, as silence makes it strong.
It conduces to good digestion, good rest, and a strong constitution.
As in diet so in apparel, I exhort you to exemplary plainness.
Choose your clothes for their usefulness, not for fashion, for covering and not finery,
or to please a vain mind in yourselves or others.
They are fallen souls that think clothes can give beauty to man.
Man cannot mend God's work.
They show little esteem for the wisdom and power of their creator,
that underrate His workmanship to a tailor's invention!
But self-control does not only regard eating, drinking, and apparel,
but also possessions, expenses, business, entertainment, company, speech, sleeping,
as well as every passion of the mind.
Love, anger, pleasure, joy, sorrow, and resentment must all be tempered by self-control.
Therefore learn your will's subjection, and take Christ for your example,
as well as your guide.
It was He that led and taught a life of faith in providence,
and told His disciples the danger of the cares and pleasures of this world.
His sermon upon the Mount is one continued divine
authority in favour of temperance and self-control.
The apostle, well aware of the necessity of this virtue,
gave the Corinthians a seasonable caution: Do you not know, says he,
that those who run in a race all run, but one receives the prize?
Run in such a way that you may obtain it.+++[++++++[+++_en_nkjv_28566]]
And everyone who competes for the prize is temperate in all things.
Now they do it to obtain a perishable crown,
but we for an imperishable crown.+++[++++++[+++_en_nkjv_28567]]
Therefore I run thus: not with uncertainty.
Thus I fight: not as one who beats the air.+++[++++++[+++_en_nkjv_28568]]
But I discipline my body and bring it into subjection, lest,
when I have preached to others, I myself should become disqualified.

I will conclude with this one most comprehensive passage of the apostle, Phil. 4:5:
Let your moderation be known unto all men, for the Lord is at hand.
As if He had said, Take heed!
Look to your ways!
Have a care what you do!
For the Lord is near you, even at the door; He sees you, He marks your steps,
tells your wanderings, and He will judge you.
Let this excellent exhortation live in your minds.
Let it ever dwell upon your spirits, my beloved children, and influence all your actions,
your affections and your thoughts.
It is a noble measure, sufficient to regulate the whole;
they that have it are easy as well as safe.
The world is then kept at arm's length; and such have power over their own spirits,
which gives them the truest enjoyment of what they have:
a dominion greater than that of empires.
O may this virtue be yours!
You have grace from God for that end, and it is sufficient.

William Penn

== William Evans – Letters from His Parents while at Boarding School

From my mother: 

I hope, my dear children,
you do not forget our anxious concern and solicitude for your good when present with us,
and I trust it has not abated,
but desires are raised that the Lord may be pleased
to take you under his peculiar care and notice,
and that you may indeed be afraid to offend Him in word or action.
Be obedient to those who have the care over you, and kindly affectionate one to another.
Endeavour after stillness, and remember the many favours you receive;
and may the reverent inquiry of your minds be,
What shall I render unto the Lord for all his blessings?
Your dear father desires his love to be remembered to you,
and that you would let us hear from you as often as you can.

With desires for your preservation in the innocency and simplicity of the Truth I conclude.

Your affectionate mother, 

Hannah Evans.

After my beloved father's return from his journey,
he wrote us frequently--from one of his letters the following is taken: 

My Dear Children, 

I have been much concerned on your account for some time past,
understanding several of the boys had given a great
deal of trouble to those who had the care of them;
and though I could scarcely think either of you were of the number,
yet not hearing anything particular, my mind was made very uneasy,
but I hope better things of you.
And if at any time you feel any disquietude of mind,
be patient and endeavour to bear your trials in meekness,
looking with reverent confidence to your great Creator,
who compassionately regards every sigh and tear of the sincere in heart;
whether they be children or more advanced in years.
But then we must also at all times strive to conduct
so as not to grieve the Holy Spirit in our hearts,
which is a continual witness against every evil thought, word or action.
Let your innocent, circumspect deportment be observed by all;
join not with any in the least evil,
but let the fear of the Lord be ever present with you, and that will keep you harmless,
and make you dear unto him and to all good people.

Your mother joins me in near love to you both, desiring your welfare every way.
Your loving father, 

Jonathan Evans.

* * *

Dear Children,

Feeling desirous at all times you may do well,
I cannot but endeavour to revive in your remembrance
the necessity of attending with all diligence,
to the small,
gentle intimations and reproofs of the Holy Spirit of Truth in your own minds.
Keep near to its blessed instructions at all times,
and it will preserve in every season of trial and difficulty,
and as an inexhaustible fountain,
sustain your little minds when depressed with anxious thoughts or discouraging fears.
This is the alone way to happiness here or blessedness hereafter.
For in obedience to this light in our minds,
we are brought to love the Lord our most gracious Redeemer above all,
and by Him are regarded as his children, which is treasure indeed,
that raises the spirit above earthly pleasures,
to a sense of the unspeakable comforts in the regions of immortal bliss.
Here, in this state the fear of death is taken away,
because we know that in the presence of the Lord there is life,
and as we are kept near him, nothing can hurt us.
Now, my dear children, let me earnestly entreat you,
to mind the reproofs which you feel for doing wrong;
this is the Spirit of Truth I have been speaking of, and as you carefully attend to it,
it will lead into all truth--you will fear to offend by a repetition of those things,
for which you have been reproved.
It penetrates through every covering,
and no dissimulation can possibly escape its all-searching power.
Whenever through unwatchfulness you have given way to temptation,
and by the merciful calls of this holy teacher, you become sensible of it, retire alone,
and endeavour to get your minds drawn from every outward thing,
to a reverential waiting upon your Holy Creator for
a renewal of his light and grace upon you,
that you may be strengthened to resist the enemy of all good in his future attempts;
and be sure to avoid those things that have thus beguiled you,
and brought distress upon the tender mind;
for in this watchful state your minds will often be tendered,
and at times sincere petitions will ascend for preservation,
and support in this world of vanity and trouble.

Your affectionate father, 

Jonathan Evans

* * *

Dear Child,

I received your letter, and was glad to hear of yourself and sister being in health,
which is a blessing among the many received, we ought to be thankful for.

Indeed,
many are the obligations we are under to that bountiful
hand from which all our blessings flow.
Let us then evince our gratitude by endeavouring to love Him above all,
and then we shall be afraid to offend Him in thought, word or deed.
My dear child, I feel anxious for your preservation,
and desire you may be careful to associate with such of your school-mates,
as are most seriously inclined; and be sure not to do anything,
in the absence of those who have the care over you,
that you would be afraid they should know,
or that would in any degree wound your own mind.
Learn to love silence; and seek for strength,
that you may be preserved in time of temptation.

With love to yourself and sister, conclude your affectionate mother, 

Hannah Evans.

== Remarks of Sarah R. Grubb on Christian Discipline, as it Respects the Upbringing of Youth.

Christ came to redeem and save from that spirit which opposed the coming of his kingdom.
He has wonderfully displayed the virtue of that good by which evil is overcome,
proving through the whole of his dispensations a coincidence of mercy with justice.
And the operation of this principle appears to be in no case more necessary and profitable,
than in the true support and duty which we owe to children placed under our care.
As there are dispositions manifest in children,
after the knowledge of good and evil is contracted,
which degrade the mind from that innocency wherein they were first created,
and which like an evil tree, if permitted to grow, will produce unwholesome fruit;
so there is also in the power of those who have rightly the care of them,
a means which may, by the concurring operations of Truth,
be rendered effectual to the reduction thereof;
and as both the disorder and the remedy lie deep in the heart,
they must be sought for there, without the love of superiority,
a carnal judgment of good and evil, or the influence of self-will.

To bring children to a true and profitable sense of their
own state and direct them to the spiritual warfare in themselves,
is the main goal of all religious labour on their account;
and herein a single eye ought to be kept to the witness of Truth in their minds,
for that must be visited and raised, before they can so see,
as to repent and convert from evil.
When this is the principal object in the view of those who consider themselves as shepherds,
accountable for the preservation of their flock,
they are religiously engaged to promote it by such means as are put into their power,
under the influence of a Christian spirit;
which gives patience to persevere without fainting,
strength to bear and forbear in their waiting for the springing up of the good seed,
and opens an eye of faith to look for and depend only upon,
the blessing on their endeavours.
Hereby the conduct of such is deeply instructive to children;
and may seal upon their minds the pious concern of their parents or teachers,
and affectionately endear them in a friendship lastingly profitable, when they prove,
through the influence of divine love upon their own understandings, the justice, mercy,
and nobility of that Christian discipline which has been exercised towards them,
and whereby they have obtained sweet communion with, and an opening to,
the fountain of good in themselves.

If in our passage through life, we are often brought to acknowledge that of ourselves,
without divine assistance, we can do nothing,
is it not abundantly obvious in the work of bestowing a religious education on youth?
and should any wisdom preside over that "`which comes down from above, and is first pure,
then peaceable, gentle, and easy to be intreated, full of mercy, and full of good fruits,
without partiality, and without hypocrisy?`"
It is lamentable to see how people in general,
and even some who seek the sense of Truth on other occasions,
seem to consider themselves, at any time, or in any disposition,
qualified to instruct and correct children,
without perceiving that their own wills require to be first subdued,
before they can acceptably be instrumental in subduing the will of others. 

"`Provoke not your children to wrath,`" said the apostle.
A conduct may be exercised towards youth,
which being under the influence of the passions,
has a natural tendency to raise a similar return.
To punish a child because it has offended us, without the discovery of an evil design,
is to act under an unchristian spirit, which revenges injuries.
This is a disposition which is apt to receive its gratifications from a flattering,
cringing spirit,
and from such marks of respect as originate in an impure spring of action; and hence,
teachers of children may, from a superficial judgment,
approve and strengthen the little pharisees under their care;
while the pure life that is struggling in the hearts of some who resemble the publican,
is crushed and disregarded.
Many and deep are the sorrows of the childhood of some,
which proceed from different causes,
and doubtless that incapacity wherein they are placed
for obtaining redress from real grievances,
and the abuse of power being strengthened in those from whom they receive them,
may be numbered among those affecting occasions.
Many children have had a loose, unguarded upbringing,
and grow up as degenerate plants of a strange vine,
having very little care exercised towards them, except to indulge their unruly appetites,
and passionate desires;
these require the yoke to be laid upon them with caution and true judgment,
lest more should be commanded than they possess abilities to perform,
and so their deficiency be unjustly laid to their charge;
yet the cultivation of their minds should be steadily pursued,
under that holy assistance without which we can do nothing acceptably.
Past experience does not appear to be a sufficient qualification for this,
any more than for other religious services, even where it has been right,
and much less so, when it has not been strictly under the influence of that wisdom,
which is pure and without partiality.

Wisdom and strength must be waited for, day by day,
for the right performance of our duties before him
who weighs our actions in the balance of pure justice,
and only approves those which are wrought in the spirit.
To raise children religiously requires a quietude of mind and sympathy in their guardians,
with the state of the good seed in them,
which will lead rightly to discriminate between good and evil;
to discover the corrupt source of many seeming good actions;
and to perceive that a real innocency is the root of others, which custom,
and a superficial investigation, have rendered reprehensible.
Here we see the necessity of true wisdom being renewed,
and the insufficiency of that which is carnal,
and boasts its own experience and strength.
It is the humbled mind to which is unfolded such mysteries of true godliness,
for its own edification, and that of those under its care,
as could not have been received in the support of a false consequence,
and the love of superiority.
If children are to be instructed in the ground work of true religion,
ought they not to discover in those placed over them, a lively example thereof?
or ought they to see anything in the conduct of others,
which would be condemnable in them, were they in similar circumstances?
Of what importance then is it for guardians of children, to rule their own spirits;
for when their tempers are irritable, their language impetuous,
their voices exerted above what is necessary, their threatenings unguarded,
or the execution of them rash, however children may for a time suffer under these things,
they are not instructed thereby in the ground work of true religion;
nor will the witness of Truth as their judgments mature, approve a conduct like this;
though through the bias of self-will, it may be adopted in similar cases,
in a succeeding generation, by those who, instead of having gathered good seed, have,
from the mixture of their upbringing, preferred the bad,
which meeting with a soil suitable to its nature, grows and becomes fruitful,
to the corrupting of many more.

The love of power is so deeply implanted in the natural mind,
that unless we discover it and its evil tendency in the true light,
we are not likely to consider it as an enemy of our own house,
against which we are called to war with as much righteous zeal,
as against the evil in others; yes with more,
because it is declared such are our greatest foes.
Where this corrupt part is cherished, it stains our actions;
and having gained the ascendency over the pure, lowly seed,
bribes and influences the judgment respecting good and evil,
and establishes the mind in self complacence, which, however productive of reproof,
has seldom an ear open to that instruction by which itself stands condemned.
The prodigal display and use of power is the very destruction of Christian discipline.
Power is necessary; not to be assumed in the will of the creature,
but to stand subservient to the judgment of Truth, under which it ought to be exerted;
lying in ambush as a waiting assisting force, ready to be called in cases of difficulty;
when, if it step forth in true dignity, the appearance, rather than the use of it,
may generally prove sufficient,
and its wise retreat render it still more useful and reverenced.
True love, clearness of judgment, and the meekness of wisdom,
are the supporters of true dignity;
and where these prevail in a mind under divine government and control,
they give authority, firmness and benevolence, in thought, word, and deed;
which have a profitable and comfortable effect upon
those who are placed under their influence,
and open a door for undisguised familiarity and affectionate relating,
wherein children receive instruction more suitably and cordially,
than under the arbitrary sway of a continually assumed power.
Should we lay hold of Christian discipline in all its branches,
and return with it to its root, either among children or in the church,
we shall always find it originate in a Christian spirit,
and that every plausible appearance which is defective in this ground,
is so far no better than sounding brass, or a tinkling cymbal.

The right upbringing of children is no doubt a close and arduous work; those, however,
who are rightly engaged therein, and endeavour after their own refinement,
and an increasing acquaintance with the Fountain of purity in themselves,
need not have their eye outward for the establishment of power and authority;
for He who feeds the ravens and clothes the lilies, knows what they stand in need of,
and is able, out of his own treasury, to supply all their needs; to be mouth and wisdom,
tongue and utterance; and will not fail to help under their greatest difficulties,
if they support a patient dependence upon Him alone,
and profitably live under the persuasion, that when He shuts,
no one should attempt to open, and when he opens, none can shut.

== Letters from John Banks to His Children

The following letter I wrote to my daughter, after she was placed at service in London,
in the year 1682.

Sarah Banks, my eldest daughter, 

You have been near and dear to me ever since the day you were born,
with a godly care as a tender father,
that you might be nourished up in your young and tender years for your preservation;
with many desires in my heart to Almighty God, that as you grow in years,
he would be pleased to make you sensible and give you an understanding
of those things which make for your everlasting peace,
and the salvation of your soul in the kingdom of glory, when time here shall be no more.

And now, dear child, the Lord having thus far answered my desires,
and enabled me to perform my care towards you;
I have a further concern upon my mind for the good of your soul;
which as you are truly mindful of will tend to your good,
and will never hinder you of anything that is really needful for you.

First of all I would put you in mind, that God,
according to his Divine Wisdom and Providence, gave you life and breath,
which you ought to prize and value as mercies,
amongst many more you have received from him;
and you are also come to an understanding in some degree,
how to behave yourself as a child of God,
by the light and grace of our Lord Jesus Christ,
which he has placed in the secret of your heart, for a teacher to you in all things.
My concern now is to stir you up unto this by way of remembrance;
to be faithful and obedient to its requirings, whether more or less.

This light and grace of our Lord Jesus Christ, teaches you your duty towards God,
to your parents, and to all men and women.
It first teaches you, to fear and love God, and to wait upon, worship,
and serve him with all your mind and strength, that he alone by his Spirit,
manifested in and through Jesus Christ, may be your chiefest love and delight.
It will teach you as you are watchful, to deny all ungodliness and worldly lusts,
to take pleasure and delight in meeting with God's people,
to worship him in spirit and truth;
so that you may come more and more to have unity and fellowship with his faithful children,
according to your measure.

This pure light of the Son of God, teaches you to be lowly minded,
sober and watchful over your words, carriage, and behaviour, in your life and conduct,
and to choose such for your companions; and not those, who though they profess the truth,
are light, careless, and high-minded, and follow the fashions of the world; and tattling,
and tale-bearing,
and meddling with other men's and women's matters which do not concern them.
Be sure you be found only in what concerns you, and well becomes your place,
being a servant.

This is the way to grow in grace and saving knowledge, and to have the comely adorning,
which is the ornament of a meek and quiet spirit,
which in the sight of God is of great price; and is better than costly attire.
This is the way to be beloved of God, and his people, to grow up a good woman,
and to make a blessed and happy end.
This blessed way and course of life, my soul desires for you, my dear child,
that you may carefully live and keep in it, to the end of your days.
Amen.

The light of Jesus Christ, which thus teaches you your duty towards God,
will also leach you your duty towards all men, women, servants, and children;
especially now in your place where you are a servant.
It will teach you to be faithful, willing, and obedient to your master and mistress,
in all things which are fitting and right;
to be careful that nothing waste under your hand, which is committed to your trust,
nor otherwise; and to watch with an eye for good over all in the family.
If anything else appear, tell it not abroad to any whereby it may cause dissension;
but first tell the party in love, for so you would desire to be dealt with.
This is according to the righteous law of God, which is light,
that teaches to do unto all as we would be done unto;
and when anything happens amiss with yourself, and you are spoken to and reproved for it,
as Paul's counsel to Timothy concerning servants was, I exhort you in tenderness,
murmur not, nor answer again, except it be to say it shall be amended.

My dear child, the desire of my heart is unto Almighty God,
that this my counsel and advice may be made effectual unto you;
and that in the serious consideration thereof,
with honest desires raised in you to perform and answer the same,
your heart may be truly broken and tendered before the Lord,
and so kept in all lowliness and humility before him, unto the end of your days.
Amen.

So prays your tender and affectionate father, 

John Banks.

While I was in Ireland, I wrote the following letter to my children.

The love of God unto you has been such, as to give you a knowledge of himself,
in and through Jesus Christ, the true and saving light;
and that which is required of you is obedience, and a diligent walking therein,
in all fear, humility and lowliness of mind;
for that greatly tends to make sure the steps, in the way of truth and righteousness;
and it is such the Lord teaches, namely, the humble, by his pure light and grace.
Oh! that a daily care may attend you to follow him in all faithfulness,
in answer to his blessed requirings, whether in words or actions, at home or abroad;
for this is well-pleasing unto him, and a rejoicing unto my soul;
who am still under a weighty concern and tender care for your preservation every way,
in that which is good;
and more especially seeing the Lord has been pleased to take your dear mother from us.
I have no greater joy than to know that you grow in the truth;
and that you are loving and tenderly affectionate one to the other,
in patience and quietness of mind bearing one with another,
in all affairs wherein you are concerned;
so will your undertakings be more easy and comfortable unto you.
Do what in you lies to keep to meetings, and be condescending one to the other therein;
and when you are met together with the Lord's people,
let the fear and dread of the Lord be upon you,
that you may be kept in all diligence in waiting upon him,
daily to feel the work of his spirit in your hearts,
to work you into true tenderness and brokenness; that you may grow up,
and bring forth fruit, to the praise and glory of the Lord, and your enduring comfort;
which is my hearty prayer unto the Lord on your behalf.

Farewell, dear children.
Your loving father,

John Banks.

== A Letter from Francis Howgill to His Daughter Abigail^
footnote:[This letter was written in 1666 from Appleby Jail, two years before his death.]^

Daughter Abigail,

This is for you to observe, and keep, and take heed unto all the days of your life,
for the regulating of your life and conduct in this world; that your life may be happy,
and your end blessed, and that God may be glorified by you in your generation.
These things I bequeath unto you, and counsel you ever to observe,
being the chief things alone I have to bestow upon you,
which I prize more than outward riches.
May you do so also, and observe and keep my sayings; and I charge you before God,
and by the coming of our Lord Jesus Christ, that you observe what I say.
I am moved of the Lord to leave this behind for you,
in tender love and affection unto you, my daughter,
that the Lord may give His blessing unto you, and make your ways prosperous,
and your latter end peace.

First of all, know this: I was never born into great possessions,
nor did I inherit great matters in this world;
but the Lord has always endowed me with sufficiency and enough,
and has been as a tender Father unto me, because my heart trusted in Him,
and did love the way of righteousness from a child.
I have no great portion to bestow upon you of the things of this world;
yet of that little which I have, and God has blessed me with,
there is something I shall give you, which I shall not mention here;
but you will know of it at my decease.
But I commend you to your dear mother, who, I trust, will provide sufficiently for you;
unto whom my heart has been upright before the Lord.
She had a sufficient portion and dowry when I married her,
which I desire not much to lessen or impair;
and whatever was hers (if it please the Lord I die before her) I freely leave unto her,
as was ever my intention and purpose, which has not, nor ever shall change,
through the strength of God--as God only knows, and bears me record.
This shall be manifest unto all in due time, as it is already manifest unto the Lord,
who has been with me in the midst of many troubles, trials, and sufferings,
and has lifted up my head above my adversaries, because I trusted only in his Name;
which at all times I found to be a refuge, and a present help in time of need;
and so it will be unto you, if you fear his Name, and trust in Him forever.

And now, dear child, hearken unto the words of my mouth, and listen unto my counsel.
Ponder these things I leave behind me for you to observe,
that your days may be long upon the earth, and be blessed and comfortable unto you,
and an honor to God in your generation. 

The time when you were born and came into the world,
was a time of deep exercise and trouble with me--not from the Lord,
who always spoke peace unto me,
and did sustain me--but by reason of the adversary of mankind,
who always seeks to devour the good in all,
and is the sower of discord and mischief in the hearts of those who fear not the Lord,
neither abide in His counsel.
Into these he enters, as any place is given unto his temptations,
and there he corrupts the mind.
But though there was then a great trial that came upon me,
the Lord kept my heart in uprightness unto Him and gave me much patience.
And though the earth had been removed into the sea,
and all outward things had run into confusion, and nature had changed its course,
yet the Lord gave me a resolution and strength not to be troubled or offended,
because He did support me.
At that time you were born; and therefore I called your name Abigail,
which means the father's joy or delight; for in you I was comforted,
and my present trouble was mitigated. 

Now, my counsel unto you is that you remember your Creator in the days of your youth,
and fear the Lord in your youth, and learn to know Him and serve Him all your days.
Seek first the kingdom of God, and the righteousness thereof.
His kingdom is not far from you; it is within you.
It consists of life and power, and stands in righteousness, truth, equity, justice,
mercy, long-suffering, patience, love, light, and holiness;
this is the being and centre thereof.
Therefore, seek not the "`lo here's`" or "`lo there's`" without you,
in this or that outward observation; for many seek there and never find it.
But seek, and you shalt find; wait, and you shall receive.

If you inquire,
'`in what must I seek,`' and '`in what must I wait,`'
and '`how must I seek,`' I inform you:
You must silence all your own thoughts,
and you must turn your mind to that gift which is pure, holy, and good, within yourself.
Seek and wait in that, in the Light of Jesus Christ, wherewith you are enlightened,
and which shows you when you do evil, and checks and reproves.
Take heed unto that, and it will show the evil motions and thoughts; and as you love it,
it will also subdue them, and preserve you out of evil for the time to come. 

For though you are born into the world a reasonable creature, yet you must be born again,
and be made a new creature, or else you cannot enter into God's kingdom.
You must know the Seed of the kingdom in yourself (of which
you must be born) and be formed again into God's image.
I have told you that God has sown it in you–a grain of it, a measure of it,
a portion of it, a measure of Light and Truth, of righteousness and holiness.
Keep turned in your mind to that; love it,
and you will feel the Heavenly Father working in you, and creating you anew unto life,
through Jesus Christ who has enlightened you.
And you will feel the power of the Lord strengthening you in your little,
and making you to grow in the immortal Seed of His kingdom,
and to out-grow and over-grow all evil, so that you will daily die to evil,
and have no pleasure in it, but rather in the Lord,
and in His goodness and virtue shed abroad in your heart,
which you will taste and feel within, and have joy and comfort therein.

Love the Lord with your heart and soul,
even Him that made you and gave you (and all other things in heaven and earth) a being.
Wait for the knowledge of Him in yourself; He is not far from you, but near unto you,
and unto all who call upon Him with an upright heart.
Inquire of your dear mother and she will inform you; she knows Him,
and the way to life and peace; so hearken unto her instruction. 

God is a Spirit, a pure Spirit of light, life, and power.
It is He that searches the heart, and shows you when you do evil, or think evil,
or speak evil; and He shows unto men and women their thoughts.
That which shows the evil is good, and that which shows a lie is Truth.
This is within; take heed unto it.
This is called God's Spirit in the Scriptures; believe in it, love it,
and it will quicken your heart to good, and also subject the evil.
Here is your teacher near you; love it.
If you act contrary to it, it will condemn you;
therefore take heed unto this Spirit of Truth, and it will enlighten and enliven you.
It will open your understanding, and give you to know what God is,
and to do that which is good and acceptable in His sight.
This Spirit never errs, but leads out of all error and into all truth.

O Abigail, believe my words!
They are the words of God and Truth.
Be not careless, but sober-minded in your youth.
Wait on the Lord within, and hearken unto Him.
God is Light immortal, Life immortal, Truth immortal; an everlasting and eternal Spirit.
He speaks spiritually and invisibly within the hearts and consciences of men and women.
Hear what He speaks and obey His voice, and your soul shall live.
Fear to offend Him, or to sin against Him; for the wages of sin is death.
Therefore prize His love in your young and tender years. 

Read the Scriptures and Friends' books, and take heed unto what you read to obey it,
as far as you understand.
Pray often unto the Lord that He give you His knowledge,
and open your understanding in the things of His kingdom.
Search your heart often with the Light of Christ in you;
manifest and bring your deeds to the Light, that they may be tried.
Examine yourself how the case stands between the Lord and you;
and if you see yourself to be wrong, humble yourself and be sorry.
Turn unto Him, and He will show you mercy;
then take heed for the time to come that you run not into the same evil again.
Keep your heart clean; watch against the evil in yourself in that light which shows it;
therein there is power, and thereby you have power to overcome all evil.

And dear child, mind not the pleasures of sin which are but for a moment,
and their end is misery; but cross and keep under your own will and affections.
Thus your mind will have no pleasure in evil, but only in good;
and you will feel the immortal Seed springing up in you,
to which is God's peace and love.

O Abigail! these are great and weighty things, not to be slighted!
Keep company always with those who fear the Lord,
who fear and worship Him in spirit and truth, and lead a holy and a blameless life.
Deny them not, but love them and suffer with them.
And take heed that you follow not the hireling teachers, who preach for gain and riches,
and do not abide in Christ's doctrine.
Believe them not, heed them not, for they do people no good;
but you will see them for yourself.
These have an outside show of godliness sometimes,
but deny the power of God and true holiness.
Remember I have told you, as one who has had a perfect knowledge of them. 

Be sure that you let nothing separate your love from God and His people.
Those are His people who keep His law, and obey Christ's voice, and lead a holy life.
These were ever hated and opposed and persecuted,
and always had evil spoken of them by bad and loose people.
These are God's people, and His love and peace and blessing is with them.
Therefore, grow up among them as a natural branch of the living Vine;
and continue all your days in obedience unto God's will.
So you will feel joy and love in your heart, which you should pursue above all things,
and you shall attain to and obtain everlasting peace.
May the Lord grant this unto you, according to the riches of His mercy and love,
which endure forever and ever, amen.

And now Abigail, concerning your well-being in this life,
this is my advice and counsel unto you: Love your dear mother,
and always obey and honor her.
See that you grieve her not, nor be stubborn or willful, but submit unto her,
and be as an obedient child to her;
for her love and care has been great over you and your sisters,
which has brought much trouble upon her.
Learn in your youth to read and write a little, and sew and knit,
and all points of good labour that belong to a maid;
and flee all idleness and sloth which nourish sin.
And as you grow up in years, beware of pride, and extravagance, and curiosity;
but be well content with such apparel as your mother will permit you,
in which you may also be a good example unto others.
Be not reckless, nor wild, nor light; but rather temperate, moderate, and chaste,
and not forward in words or speech, but swift to hear, slow to speak.
Always live with your mother,
and be a help to her and cherish her in her old age and latter years,
that she may be comforted in you, and her soul may bless you.
Love your sisters, and be always courteous to them, and to your brother Thomas;
encourage one another in good.

And Abigail, if you live to be a woman of mature years, keep yourself unspotted,
and let not your mind go out after sports and pastimes,
for the end of all these is sorrow; nor seek after young men.
If you have a desire to marry, do not seek a husband, but let a husband seek you;
and if you live an honest and virtuous life in God's fear,
then those who fear God will seek after you.
Do not let your affections out after every one that offers love, but be considerate;
and above all things (if you do marry) choose one that loves and fears the Lord,
whose conduct, manner and course of life you know well, before you give consent.
Be discreet and wise.
Hide nothing from your mother, and she will no doubt advise you for your good;
and if she is living, marry not without her consent.
And if you join to a husband, be sure you love him in your heart,
and be obedient unto him, and honor him in the presence of all;
so will his heart be more to you, and his love increase.
Do not grieve him, but be gentle and easily entreated, minding your own business.
And if the Lord gives you children, bring them up in the fear of God,
and in good discipline, keeping them in subjection to you.
And be an example of virtue and holiness unto them,
that you may feel the Lord's blessing in youth, and in old age, and all your life long. 

O Abigail! remember these things; keep them in mind!
Read over this letter often; get it copied over.
Lay up my words in your heart, and do them;
so you will be happy in this life and in the life to come.
These things I charge you to observe, as expressive of my unalterable mind, and will,
and counsel, unto you; in witness whereof I have set my hand.

Your dear father,

Francis Howgill.26th of the 5th month, 1666.

== Letter of Isaac Penington to His Children^
footnote:[This letter was written from Aylesbury Jail.]

To My Dear Children J. J. and M. P.

My Dear Children, 

Two things I especially desire in reference to your learning--one is,
that you may learn to know and hearken to the voice of God's witness in you.
There is something in you that will teach you how to do well, and how to avoid evil,
if your minds are turned to it.
And the same thing will witness to you when you do well,
and will witness against you when you do evil.
Now to learn to know this, to hear this, to fear this, to obey this,
that is the chief object of learning that I desire to find you in.
And when your master, or anyone of the family, turns you to this witness,
or reminds you of this witness,
or reproves you for not hearkening to or obeying this witness, oh love them,
and bless God for them in that respect!
And remember this, that he that hearkens to reproof is wise,
but he that hates or slights reproof is brutish.
That is the dark spirit, which desires to please itself in its dark ways,
and therefore loves not the light which makes his ways manifest and reproves them.
It is the brutish spirit which hates the reproof of the light,
and would continue its vain foolish ways and delights, which the light testifies against.
Therefore, mind the witness of God in your hearts which discovers these things to you,
and leads you out of them as you hearken to it, and come to know, fear,
and love the Lord God by his instruction and testimony. 

The way of youth is vain and foolish, and it defiles the mind.
Oh my children, wait for the cleansing.
Watch for that which cleanses the foolish way of children,
which is the light that uncovers and witnesses against your foolishness and vain tempers,
and the temptations of your minds, and leads out of them.
Learn to bear the yoke in your tender years.
There is a vain mind in you,
and there is something which desires to feed and please that vain mind.
But there is something near you and appointed by God to yoke it down.
Oh give no place to vanity, for it will be an occasion of woe and misery to you hereafter.
But the yoke which keeps down the vain mind, oh take that yoke upon you.
For then you shall become not only my children, but the disciples of Christ,
and children of the Most High.
This is the first thing which I mainly and chiefly
desire you should apply yourselves to learn.

The next thing (which will also flow from the first),
is that you learn how to behave yourselves as good children,
both in the family and to persons abroad, in a meek, modest, humble, gentle, loving,
tender, respectful way.
Avoid all rude, rough, bold, unbecoming carriage towards all.
Honor your mother and me as God teaches and requires,
and dearly cleave to one another in the natural relation, which is of God,
wherein you are loved,
having a great proportion of natural affection and kindness one to another. 

With the servants, carry yourselves very lovingly, sweetly, meekly, and gently,
so that none may have any cause of complaint against you,
but that all may see your lowliness and be drawn to love you.
And to strangers, carry yourselves warily, respectfully, in a sober, submissive,
humble manner of demeanor.
Do not be disputing and talking much, which is not fitting for your age and place.
Rather, watch what you may observe of good in others,
and what you may learn of those that are good.
And watch also to see how you may avoid any such evil as you observe in any that are evil.
In this way your time will be spent in profit,
and you will feel the blessing of God and of your parents,
and you will be kept out of those evils which your
age and natural tempers are subject to,
and which other children (who are not careful nor watchful) are commonly entangled in.
Mind these things, my children, as you will give an account to God,
who through me thus instructs you--who am your imprisoned father.
I am much grieved when I hear of any ill concerning you.
For this is more a matter of trouble and sorrow to me than my imprisonment,
or anything else I suffer, or can suffer from man.

And remember this one thing, which as a father I admonish you of,
and charge you to take notice of and observe,
which is this--that you do not fly out upon one another, or complain of one another,
because of the evils you observe in one another.
But rather, first take notice of the evil in yourselves.
If by the true light you find your own hearts cleansed from it,
bless God who has done it, and keep to his light and witness in you whereby he did it,
and watch that you are not overtaken by it in the future.
But if you be guilty of the same evil, or have lately done the same thing,
or are liable suddenly to do it--then oh, forbear accusing or blaming another!
In the fear of God wait on him, and pray unto him that you may be delivered from it,
and kept out of it.
And then, in tender pity, love, and meekness,
admonish your brother or sister of his or her evil,
and watch to be helpful to preserve or restore them.
And pray to God to direct you how to be helpful to them.
But it is the bad spirit and nature which is ready to accuse others.
And even when it has never been so bad and guilty, yet it will be excusing itself,
and laying the fault upon others, or remembering some other fault of another,
when it should be sensible of and ashamed of its own.

Dear children, if you bend your minds to learn these things,
the Lord will help you therein, and he will become your teacher, guide and preserver,
and pour down his blessings upon you.
And in this you will be a comfort to me and your mother, and an honor to his Truth.
And may he also give me wise fatherly instructions to teach you further.
But if you be careless, foolish, vain, following your own minds,
and what rises up there from the wicked one,
you will grieve my heart and provoke God against you, to bring evil upon you,
both in this world and forever.

Therefore, children, mind that which is near you--the light of God,
which discovers the evil and the good.
His witness (which observes all you do) is near you.
Yes, he himself is in that light, and with that witness.
Therefore, know that you are in the presence at all times of a holy and just God,
who hates that which is vain and evil, and loves that which is good and right before him.
And he has appointed a day and set a time wherein he will either reward you with peace,
joy, and eternal happiness if you have been good and done that which is good;
or with misery, destruction, and insufferable pain both of soul and body,
if you have been evil and done that which is evil.
God knows well how many instructions you have heard from friends in Truth,
and from your parents,
and how many meetings you have been at wherein you
have been taught and warned of these things.
So if you turn your back upon his light, and will not hear its reproofs,
but will rather be vain, idle, foolish, rash, quarreling,
and doing that which is wrong and then covering it with lies, (and so be as bad,
if not worse, than children who were never thus taught and instructed)--then,
in his just judgment and sore displeasure,
God may separate you from his light and give you up to the black, dark spirit,
(from whom all this wickedness is) to sow in sin here,
and to suffer the flames of eternal fire hereafter.
For this is the reward of the dark spirit,
and also the reward of all who are persuaded by him to be of his nature,
and who hearken to him, and let him work through them.

Oh my children, mind the Truth of God in you!
He will let you see and understand the truth of what I now write,
and in what fatherly love and tender care of you I write these things.
Oh, be warned of the great danger of neglecting the time of
your visitation by God's light and witness in you!
And do not go on in the evil ways of the dark, crooked spirit,
who will be tempting you to evil and hindering you
from God as long as you hearken to him.
Therefore,
be not fools to be led by him to destruction in the
evil way and evil works which lead thereto;
but be wise to hearken to the light, and follow it out of that which is evil,
into everything that is good, to the salvation of your souls.

I desire that Friends in the family^
footnote:[The remainder of this letter is not directed to his children,
but to other Friends who lived in his house, and to Gulielma, his step-daughter,
and afterwards the wife of William Penn.]
watch over them in these respects; and when they find just occasion,
to put them in mind of any of these things, in the fear and wisdom of God,
with tenderness and gentleness.
But take heed of upbraiding or aggravating them, lest they be thereby hardened,
and evil is raised and strengthened in them.
And, my dear G. +++[+++doubtless his step-daughter, Gulielma,
afterwards the wife of William Penn]
and Friends, watch over your hearts and ways, that you may be as examples to them,
so that they may not only read these things from my writing,
but also in your carriage towards them and towards one another.
So the Lord bless your watchfulness, care, and endeavors therein,
that I may hear good concerning them,
and be comforted in the mercy and kindness of the Lord towards them.

Your father, who desires your good, and that it may go well with you,
both here and hereafter.

I+++.+++ P.

10th of Third month, 1667

== Tender Advice, Caution, and Counsel to Parents and Children / By John Griffith

=== First to Parents:

Very much depends upon the right education of children.
I therefore find it in my mind to make a few observations upon this subject,
as it shall please the Lord to open my understanding,
without whose assistance and blessing upon our labors, they prove altogether fruitless. 

The people of Israel were strictly enjoined to make
the training up of their children in the law of God,
their constant care: "`Hear, O Israel, the Lord our God is one Lord;
and you shall love the Lord your God with all your heart, and with all your soul,
and with all your might.
And these words which I command you this day, shall be in your heart,
and you shall teach them diligently unto your children,
and shall talk of them when you sit in your house, and when you walk by the way,
and when you lie down, and when you rise up.`" 

Exceedingly great is the trust reposed in parents and the heads of families.
It is certainly their indispensable duty, as much as they can,
both by precept and example, to form the tender minds of their offspring to virtue,
as says the apostle, "`And you fathers, provoke not your children to wrath;
but bring them up in the nurture and admonition of the Lord.`"
And, "`Train up a child in the way he should go; and when he is old,
he will not depart from it.`" 

Parents must first be acquainted with the way of Truth,
and the nurture and admonition of the Lord themselves,
before they can train up their children therein.
That which is likely to have the greatest influence upon their tender minds is a steady,
circumspect example, in a self-denying conduct before them;
which will beget reverence and honorable thoughts in children
concerning those whom Providence has placed over them. 

Great care should dwell upon the minds of parents,
to make it fully evident to their children that they are much more
desirous they should possess a heavenly than an earthly inheritance;
and are more concerned that their souls be adorned with the graces of the Holy Spirit,
than that their bodies should appear decked with outward ornaments. 

Children will be very likely to value that which they see is preferred by their parents,
whether it be the things of the world, or the things of God.
If this is the case (which I think will be conceded by all thoughtful persons),
O then! how much depends upon them for the promotion
of truth and righteousness on the earth,
both in regard to the present time, and the generations to come.
This fully appears by the Lord's testimony concerning Abraham; "`And the Lord said,
Shall I hide from Abraham that thing which I do?
seeing that Abraham shall surely become a great and mighty nation,
and all the nations of the earth shall be blessed in him.
For I know him, that he will command his children, and his household after him,
and they shall keep the way of the Lord, to do justice and judgment;
that the Lord may bring upon Abraham that which He has spoken of him.`"
Abraham's godly concern appears earnest, even for the child of the bond-woman;
where he said unto the Lord, "`Oh! that Ishmael might live before You.`"

Constant and faithful endeavors,
with secret cries to God that His blessing may attend them,
may prove effectual to the preservation of children.
This care should begin very early,
even as soon as they are capable of distinguishing
what pleases and displeases their parents.
A self-willed, contrary disposition may soon be discovered in children,
which is very earnest to have its own way,
before they can judge what is best for themselves.
This should constantly be subjected to those who are to judge for them.
Children should never be allowed to prevail by a demanding and fretful temper,
not even when what they crave is suitable for them to receive,
were they in a submissive disposition.
By this they will quickly and clearly see,
that it is more to their benefit and comfort to yield
an entire subjection to their providers,
and that nothing is to be obtained by a fretful self-willed temper.
This should be done by a firm and steady hand,
which will make the work of parents abundantly easier in the government of their children,
and may prove a great benefit to them, perhaps through the whole course of their lives;
since by crushing their willfulness in its first buddings, it may thus die away,
so as never more to gain the pre-eminence.
This would be a great blessing,
and they would owe their watchful parents far more for suppressing
this and other pernicious buds in them,
than for the reception of a large outward inheritance.
Indeed,
everything of an evil nature should be kept down
in children by a careful and steady means.
Oh! what a hopeful generation of youths should we have,
were parents in general to exercise this prudent care in all things!
I verily believe that,
instead of sober virtuous youths being as speckled birds amongst the rest,
the rebellious, disobedient and obstinate, would be so;
and this would bring judgment upon them. 

A conscientious discharge of this great duty,
would bring an ample reward to such parents as have no greater
joy than to see their children walking in the Truth.
And even if parents should prove unsuccessful, as it sometimes has happened,
they will be clear of their children's blood in God's sight, which is a very great thing;
so that though the rebellion and evil conduct of their offspring may be their sorrow,
it will not be their sin. 

I have sometimes been much grieved,
when I have seen youth in a path of being ruined through the imprudent
indulgence of their parents (especially mothers) making themselves
and others mere slaves to the perverse desires of their children.
These take great pains to extinguish the flame of their children's
troublesome tempers by such means as add fuel to the fire;
inverting the order of nature, in becoming subject to those who should submit to them.
And by answering their unreasonable cravings, they make themselves more work,
and that of a very disagreeable nature.
Parents who are so very imprudent,
have little reason to reflect upon their children for being self-willed,
and not subject to them when they grow up, because they themselves have cherished, fed,
and supported that selfish disposition in them from their cradles.
And unless the Spirit of God is permitted to lay deep hold of them,
and change the state of their minds,
they are unfit to be a comfort either to themselves or others,
not being formed for good servants, husbands, wives, or members of society. 

Alas! when I take a view of the world,
and reflect how it wallows in abundance of wickedness and corruption--which
mankind possesses in a sort of succession from parents to children,
like outward inheritances--I have no words sufficient
to set forth to the full so deplorable a case.
How sorrowful it is to observe even children, by the power of example,
become like grown men in wickedness and hardness of heart!
Custom and general practice have so changed the common opinion of some gross evils,
that there appears very little remorse in the almost constant practice of them.
Many children are brought up, like their parents,
much strangers to their duty both to God and man.
This almost universal infection of evil, forgetfulness of God,
and wallowing in the pollutions of this world, are very alarming,
and call loudly for a reformation,
lest the Lord break forth in judgment upon the nations as the breach of waters.
It is indeed a painful task for godly parents, amidst so general a depravity,
to raise their children without receiving some stain from this pollution,
which runs down in our day like a strong torrent.
The safest way is, with great strictness and steadfastness,
to keep them out of such company,
though an inconvenience may attend this in various outward respects.
But oh! the soul is the most precious part of them, and parents,
above all other considerations,
ought to be concerned to preserve it untainted with the defilements of this world. 

There is no better rule to act by in this important task,
than perfect submission to the Spirit of Truth,
who is promised to lead us into all truth.
If we mind this,
we shall not indulge our children in anything which
the Spirit testifies against in ourselves.
And we shall be far from pleading that because they are young,
some greater liberties may be allowed them in this or that thing.
Rather, we shall feel that as they are a part of ourselves,
the same divine law should be a rule for both them and us. 

I have taken notice, that some parents, who seem to have learned, in degree,
the lesson of humility and self-denial,
as far as could be discovered by their outward appearance,
yet seem to have no aversion to their children's making a different appearance;
but will even introduce them into vane and worldly things while very young,
plainly manifesting they have a pride in seeing them so.
Such parents, notwithstanding their outward show, exhibit great unsoundness,
and that they themselves are not what they would pass for.
I sincerely wish that parents,
who indulge wrong liberties in their children by allowing them to deviate from
that pure simplicity and self-denial into which Truth leads all who follow it,
would consider the injury their children sustain thereby,
being placed in a variety of difficult and dangerous situations with respect to temptations.
Indeed, inconsiderate tender youth,
through their aptness to crave the glittering things of the world,
and their imprudent parents indulging them therein, are, as it were, prepared for ruin,
unless divine mercy interpose.
Some parents have been pierced through with much sorrow by this means,
and have had great cause to repent when it was too late;
and there has been reason to fear that the blood of their
children will be required at their hands. 

Some perhaps may think I am very sharp and severe upon parents,
insisting that it is not always their fault when children pursue wrong things.
This I have already granted,
and it is true that they are frequently very self-willed and ungovernable.
Such an argument has merit when children are of an age to become their own rulers,
and have ability to clothe and provide for themselves.
But I think it has little weight while their parents provide for them,
who not only have power to advise and persuade, but also to command and restrain.
Here a parent certainly may and ought to maintain absolute authority,
most especially in cases where the testimony of Truth is in danger of suffering. 

It is very observable that Eli was greatly blamed for not restraining his wicked sons,
even though it plainly appears he much disapproved of their practices,
reasoned with them on that account,
and laid before them the deadly consequences of their evil conduct.
How very affecting it is, to consider the fearful calamities which came upon that house,
and also upon Israel, probably in some measure upon the same account. 

The neglect and imprudent indulgence of parents in training
up their children is also a painful loss to the church,
as the consequence thereof tends greatly to obstruct the progress of Truth,
by standing as a stumbling-block in the way of serious inquirers.
When people of the world see that the undue liberties which they are called out of,
are indulged in amongst us, they are offended.
Oh! that parents, children, and all who are unfaithful,
and who easily allow the various branches of our Christian testimony to fall,
would deeply consider the mournful consequence thereof
in retarding the progress of Truth,
and grievously eclipsing the beauty of Zion!
Then I greatly hope a more living zeal and holy ardor would prevail,
and that the careless sons and daughters would arise,
shake themselves from the dust of the earth,
and put on the beautiful garment of holiness and Truth,
that she might become more and more a praise in the earth. 

=== Now to Children:

Having offered a few remarks concerning the important duty of parents,
it now remains to do the same respecting the indispensable duty
of children to honor and obey their parents in the Lord,
which is strongly enjoined in the holy Scriptures,
and is of lasting and indispensable obligation. 

The command is, "`Honor your father and your mother,
that your days may be long upon the land which the Lord your God gives you.`"
Read Matt. 15:4. Mark 8:10. Luke 18:20. Eph. 6:2-3.
In those things which are consistent with the law of God,
no child can stand acquitted before the supreme Judge
for disobeying or dishonoring its parents.
This obedience and honor not only extend to yielding to what they command or direct,
but also to the preservation of a reverent awe and honorable esteem in the heart,
arising from love, which would on all just occasions cherish and protect them.
It is a sin of great weight to disregard and slight parents,
as appears by Duet. 27:16:
"`Cursed is the one who treats his father or his
mother with contempt;`" and Prov. 30:17:
"`The eye that mocks at his father, and refuses to obey his mother,
the ravens of the valley shall pick it out, and the young eagles shall eat it.`"
Chap, 23:22: "`Hearken unto your father,
and despise not your mother when she is old,`" etc.

On the other hand,
very notable is the kind and watchful Providence that attended those who feared the Lord,
and those who loved, honored and obeyed their parents; as Jacob, Joseph, Ruth,
Samuel and David; also the Rechabites (Jer.
35). It would far exceed the bounds of my intention to particularize all those
excellent patterns and examples we are favored with the account of,
which are wonderfully adapted to instruct, encourage and improve the youth,
as well as others. 

It is a very commendable, as well as a very profitable thing,
to be familiar with those sacred writings.
Remember what Paul said of his beloved son Timothy:
"`From a child you have known the holy Scriptures,
which are able to make you wise unto salvation, through faith which is in Christ Jesus.
All Scripture is given by inspiration of God, and is profitable for doctrine,
for reproof, for correction, for instruction in righteousness;
that the man of God may be perfect, thoroughly furnished unto all good works.`"
But let all duly consider, that profiting unto salvation by the sacred writings,
depends entirely upon the holy, living, powerful faith of Christ, which works by love,
purifying the heart.
It is by this that we come to see Him who is invisible,
and consequently to understand the precious mysteries of His kingdom,
as far as is proper and necessary for us to know
them (which is all that is lawful for us to desire).
There are many other good and profitable books,
but none in which is contained such a storehouse
of rich treasure and sublime heavenly mysteries,
wonderfully wrapped up and concealed from earthly wisdom and carnal understanding.
For none can know the things of God, without the assistance of His Spirit,
as appears by 1 Cor. 2:10-15, and many other texts. 

Great has been the concern of the spiritually-living in the church
(as appears by frequent and very pressing affectionate advice,
caution, and counsel to the youth),
both to read the holy Scriptures and other profitable books,
and to carefully refrain from all other books which have the least
tendency to draw the mind out from the holy fear of God,
and from a sober, virtuous course of life, or those which are solely for amusement,
being entirely unprofitable.
Time is very precious, short, and uncertain;
it should therefore be carefully improved to the soul's everlasting advantage.
Moreover,
youth should learn early to yield strict and careful
obedience to the divine Monitor within,
as well as to their parents and all who have the rule over them,
carefully shunning the vain and unprofitable amusements,
as well as the corrupt conduct of the world.
I earnestly advise all to avoid everything in both dress and address,
which might have the least tendency to draw them into a league
or friendship with "`the children of the land,`" or with the depraved
degenerate world that wallows in pollution and great defilements,
lest they should be drawn aside and defiled, as Dinah was,
by going out to see the daughters of the land (see Genesis 34),
and as the children of Israel were,
by their woful intimacy with the daughters of Moab and Midian.
And do not forget the dreadful fall of Solomon, the wisest king, who,
by contracting an intimacy with those who were strangers to God and His holy covenant,
had his heart drawn away from the living and true God,
and so greatly debased himself as to bow down to their paltry dumb idols.
Time would fail to recapitulate the mournful instances recorded in the holy Scriptures,
and other authentic accounts,
concerning the hurtful consequences of God's people mixing and joining with the nations.
It is their safety to be separate and to dwell alone, for He says,
"`Come out from among them and be separate.
Do not touch what is unclean, and I will receive you.`"
(2 Cor. 7:17)

Our youth^
footnote:[He means the youth within the Society of Friends]
have been highly favored with a living, powerful ministry,
which has often reached the witness of God in their hearts.
What a great favor this is when we consider that the greatest part of Christendom,
almost ever since the apostles' days,
have deprived themselves of this by substituting human wisdom and learning in its place.
Thus the panting,
thirsty souls among them could meet with little more
from their ministers than the muddy waters of Babylon.
Indeed, such ministers could not direct seeking hearts to the pastures of Christ's flock;
but instead darkened counsel by a multitude of words without knowledge,
and made void the commandments of God by the precepts, inventions and traditions of men.
In what a blessed time has your lot been cast,
even when evangelical light and truth has manifested itself in perfect purity!
Oh! that our youth would consider and deeply ponder in their hearts,
that notwithstanding the great and earnest labors bestowed in godly love and
zeal for the preservation of the Society in the way of truth and righteousness,
yet very sorrowful and obvious has been the declension in practice of many amongst us.
A mournful flood of undue liberties has flowed in;
many have made grievous advances in those corrupt,
perishing pleasures and trifling amusements,
which our truly pious predecessors wholly denied and turned their backs upon,
having left us large and living testimonies, by way of warning and caution,
to carefully avoid being entangled with such yokes of bondage.
These things have prevailed for lack of abiding in the fear of God,
and not duly considering that He is ever present, beholding all our words and actions,
be they ever so much concealed from the view of mortals.
When the mind is turned to His pure witness in the heart, we find reproof,
correction and judgment, for giving way to wrong things;
and as the youth abide in subjection to this,
they will be afraid to transgress its pure law in the heart,
which they will find to agree exactly with the precepts and injunctions
recorded in Scripture respecting their duty to God,
their parents, and all mankind. 

The reason why many who see their duty, fail in the performance of it,
is their departing from "`the perfect law of liberty,`"
or the "`law of the Spirit of life`" in their hearts.
They may be informed concerning their duty by outward means and laws,
but the ability to perform is only to be found arising from the inward law,
agreeably to Rom. 8:2; "`For the law of the Spirit of life in Christ Jesus,
has made me free from the law of sin and death.`"
In obedience and humble subjection to this holy law, youth would enjoy that pure peace,
heavenly serenity and sweet consolation of soul,
which infinitely surpass all the treasures and pleasures of the earth,
and would have a well-grounded hope of a happy eternity.
It is the adversary who leads to hardness of heart and a self-willed,
rebellious state of mind.
This is sadly observable in some of the youth, who, by their uncontrollable dispositions,
administer great sorrow and anxiety to their parents and friends,
being puffed up with the vain conceit that they are more capable of judging
for themselves than those of far greater wisdom and experience.
In this way, many, it is to be feared, have rushed on to the ruin of both body and soul. 

Very great is the danger when the young and inexperienced are proud and opinionated.
This naturally raises them above instruction,
putting them out of the way of being truly profitable, either to themselves or others.
Such, unless their hearts are mercifully turned by a supernatural power,
are never likely to be fit for governing families,
or to act as members in the church of God.
For it often appears that, unless their unmortified wills and tempers are bowed to,
however unreasonable,
they will break the peace of Society and violate its wholesome order,
being like the unsubjected "`bulls of Bashan.`"
And when any of these assume the outward form of religion,
and take upon themselves to be active members, without a change of heart,
they prove a painful burden to the living members of the body.

I do therefore, in much affection and desire for the welfare of tender youth,
caution and warn them to carefully avoid the company and conversation of all who,
though under the same profession of Christianity,
disregard their parents and those who have the rule over them,
or who slight or speak contemptuously of their superiors, both natural and spiritual.

The fear of the Lord is the beginning of wisdom,
and it is this which makes and keeps the heart clean.
Learn it in a tender age,
and by it you will be taught to remember your Creator in the days of your youth; and,
agreeably to the injunction of our blessed Lord,
you will find that in seeking first the kingdom of God and His righteousness,
all things necessary will be added.
Divine wisdom, as it is sought for and obeyed,
will direct your steps in the course of this short pilgrimage,
in the choice of a proper helpmate, and in all other affairs of importance.
Watchful Providence will indeed be over you in care, guidance, and protection,
if you look to Him and live in His fear.

It greatly behooves you to look diligently to the footsteps of Christ's companions,
who walked with Him through many tribulations,
having washed their robes and made them white in the blood of the Lamb.
Be truly contented with that low, humble, self-denying way which you see they walked in;
you can never revise or improve it.
If you seek more liberty than this path allows, it will only bring darkness,
pain and vexation of spirit upon you.
Read the writings of Friends in early times,
and observe how wonderfully the power and love of God was with them,
and how marvelously they were protected amidst the raging,
foaming waves of earthly powers, combined to lay waste the heritage of God.
What encouraging and excellent accounts left upon record for us,
concerning the powerful overshadowing of heavenly love and life in their religious assemblies,
and the glory of God shining forth amongst them!
This glory and power, through the mercy of God, is not yet departed;^
footnote:[This was written in 1764]
though there have been some withdrawings of it.

Dearly beloved youth, lay to heart the great slackness of zeal which appears in too many;
the dimness, flatness, and painful gloominess,
which has spread over our assemblies in this day.
This is indeed hard to break through,
and it many times deprives us of experiencing the
heavenly places in Christ Jesus our Lord!
It is not of Him that we are in this condition, but it certainly is our own fault,
because wrong things are allowed to prevail.
Oh, that our youth may be stirred up in a godly zeal
to cry out fervently with the prophet Elisha,
"`Where is the Lord God of Elijah?`"
and be vigilant in ardent endeavors to be endued with the same Spirit,
and to succeed those honorable worthies who are now
removed from works to receive a blessed reward.
Consider that the business of your day is to come up in a faithful succession,
maintaining the cause and testimony of God, left with you by your ancestors.
Stand fast, therefore,
in the liberty purchased for you by great sufferings and the shedding of innocent blood.
Be afraid to trample upon it,
which all certainly do who turn away from the Truth as it was received,
held forth and maintained by them.
May Truth be very precious in your eyes from generation to generation,
until time shall be no more!
Those who lightly esteem it, turning their backs upon it,
violating its blessed testimony in its several branches,
will (unless they repent) surely be rejected and cast off,
as being unworthy of so great an honor as that of holding
forth a standard of truth and righteousness to the nations;
and others will be called and chosen for that great and glorious work.
The Lord is able to raise up those who may be compared to stones,
and to make them Abraham's children, by doing his works;
while those who might have been the children of the kingdom, may, by disobedience,
provoke Him to exclude them. 

I shall conclude this affectionate address to our youth with the words of Christ,
by His faithful servant John, to the church in Philadelphia, "`Behold I come quickly;
hold that fast which you have, that no man take your crown.
Him that overcomes, I will make a pillar in the temple of My God,
and he shall go no more out; and I will write upon him the name of My God,
and the name of the city of My God, which is New Jerusalem,
which comes down out of heaven from My God: and I will write upon him My new name.`" 

== Remarks About Daniel Wheeler's Parenting / Written by His Son

It is far from being the intention of the Editor^
footnote:[Daniel Wheeler's son, Daniel.]
to attempt any elaborate delineation of the character of the subject of these Memoirs:^
footnote:[These remarks were appended to the Memoirs of the Life
and Gospel Labors of Daniel Wheeler.]--this he thinks will be best
gathered from the correspondence and memoranda which have preceded.
There is however one feature,
on which he hopes the reader will bear with him while he offers a few remarks,
which appear to be called for by the peculiar opportunities
for observation which he enjoyed,--namely,
the mingled fidelity and tenderness with which his beloved
father sustained the responsible character of a parent.
In reverting to this particular subject,
we who enjoyed the privilege of a filial relationship with him,
feel that we have abundant cause to rise up and call him blessed. 

From their early years,
the benign influence of his devout and pious spirit was forcibly felt;
and it is now a mournful satisfaction to the survivors to recollect,
that their earliest impressions of good were associated
with the affectionate counsels of their departed father.
His was not the language of precept only,--that of his strikingly
consistent example was still more powerful.
It was impossible to observe from day to day the thankful, cheerful,
humble frame of mind which he so uniformly manifested,--his watchfulness
to check every rising of improper feeling,--and above all,
the deep reverence and filial love which pervaded his heart towards the great Author
of every mercy,--without being made sensible of that blessed and all-pervading grace
or Spirit which regulated the daily tenor of his life. 

His children at once loved and honored him;
for while he possessed their entire confidence, and the fullest hold on their affections,
they knew that he was unflinching in the refusal of whatever he
felt to be inconsistent with his principles or their highest good.
Notwithstanding the kindness of his nature,
and the strength and warmth of his parental feelings,
his known firmness precluded all hope of inducing him to yield to their inclinations,
when these stood opposed to their eternal interests.
Many perhaps may have been more systematic in their instructions;
but few could keep more steadily or practically in
view the superior importance of heavenly things.

From their early years,
he patiently labored to imbue the minds of his children
with the love and fear of the Almighty.
He instructed them diligently in the holy Scriptures;
and endeavored to explain in a manner suited to their capacities,
the truths they contain.
He was also persevering in his efforts to exhibit to them
the example of the righteous men and women of other generations:
and especially the exemplification of the fruits of his own principles,
which the lives of the early members of our Society so strikingly display.
For this purpose he set apart a portion of time daily,
in which he read to his family works of this description;
a practice that was continued up to the period when
his religious labors called him from them.
Perhaps some might be ready to think that such a
course would be found irksome by the young;
but certainly in the present instance the result was widely different,
and his children can now recall the feelings of solemn interest
and enjoyment that often attended these readings,
and the short period of quiet by which they were invariably followed.
It was also his custom each evening, when his children had retired to rest,
to visit their chambers,
and endeavor to direct their hearts to their great Creator and Preserver.
On these occasions, he would repeat, or teach them to repeat passages of Scripture,
or poetry of a devotional character, to which his own admonitions were frequently added;
and he generally closed these sweet and well remembered seasons with a solemn pause:
during which, doubtless,
his pious spirit was often engaged in committing them to the Lord.

As his children advanced towards maturity, instead of relaxing his watchful care,
he felt that there was need rather of redoubled vigilance
to shield them from surrounding danger.
Ever anxious for their best welfare, yet deeply sensible that through Divine grace alone,
their youthful minds must be awakened, quickened,
and enabled to lay hold of a Savior's love;
he was earnest in imploring for them this heavenly gift,
and diligent in watching for opportunities to impress
upon them the importance of spiritual things.
One instance of the condescension of the Lord in hearing
and answering his prayers may be here introduced.
As his eldest son attained the age of manhood, earnest were the cravings of his father,
that the Lord would direct his heart "`into the love of God,
and into the patient waiting for Christ.`"
He knew well that to the natural man, the things of God must ever be a mystery;
and he longed that through submission to the operations of the
Spirit of truth they might be opened to his understanding.
Often with parental tenderness he silently watched
the opening convictions of his inquiring mind,
and as opportunities presented,
he labored to explain to him the views he had himself received. 

At one time the sentiments of his son on these all
important subjects were exceedingly unsettled,
and he passed through deep mental conflict before
he yielded to the light of Divine truth in his soul,
which dispelled the doubts and reasonings by which he was assailed.
It was at this period, that one evening his father and he being alone together,
they had much conversation on the points which then
pressed heavily on the mind of the latter.
Before retiring to rest, his father handed him the Bible,
and requested him to read a chapter:
he took the book and read the third chapter of Malachi.
Deep seriousness overspread his countenance,
and after a considerable time of silence he repeated,
'The Lord whom you seek shall suddenly come to His temple,
even the messenger of the covenant whom you delight
in;`"--and He shall be "`like a refiner's fire,
and like fuller's soap,`" adding, 'yes, He will come into His own temple,
the temple of the heart, and there do His own work.
I never understood this chapter before, nor saw, as I now see it,
the spiritual nature of the gospel dispensation.'
The impression thus made was not soon effaced;
and it was evident to his thankful and rejoicing parent,
that the prophetic declaration was indeed fulfilled in his
experience,--that the Lord had come into his temple,
and was there working to the purifying of his soul.
The change which gradually succeeded was most striking; clearly evincing to those around,
that the day had indeed dawned and the day star arisen,
in a heart long oppressed with darkness, and a prey to many doubts.
In reference to this period his father once remarked with much emotion,--"`this
kind can come forth by nothing but by prayer and fasting,`" intimating the long
continued exercise of soul through which he had been led on behalf of his son.

Two avenues to evil which he guarded against with special care were:
the introduction of books of an injurious tendency,
and the associations which he allowed to his children.
With respect to reading,
he was liberal in supplying whatever he thought calculated to improve or expand the mind,
and furnish profitable exercise to the understanding;
but very few productions of a frivolous or hurtful
nature escaped the vigilance of his watchful eye.
On these occasions, he regarded not the inclinations of those he so tenderly loved;
and he has been known, when works that he disapproved had been lent to his young people,
to return them himself to the parties from whom they came,
accompanied by a frank avowal of his sentiments respecting them.
With regard to society for his family, his situation in a foreign country,^
footnote:[Daniel Wheeler's children were principally
raised during their fifteen year stay in St. Petersburg,
Russia.]
far separated from those of his own religious views,
would doubtless have appeared to many to present unusual difficulties.
These he endeavored to obviate, by rendering home as pleasant and cheerful as possible,
and thus leaving his children little to desire beyond its precincts.
Perhaps few domestic circles ever presented a happier scene than his own,
while its links were permitted to remain unbroken.
Doubtless the result of such a system has been to make the changes
and separations (which are inevitable in a world of fluctuation
and mutability) fall heavily on the hearts of survivors;^
footnote:[At the time of this writing (two years subsequent to the death of Daniel Wheeler),
four of his six children were no longer living.]
but the shelter thus afforded to their inexperience,
and to the unfixed principles of early years, was an invaluable safeguard;
and they can now look back with grateful hearts to
the wisdom and care of their departed parent. 

If his labors have not always been attended with adequate results,
his children can freely, though with shame acknowledge,
that the fault rested not with him but with themselves;
and as respects those who have been called from this state of probation,
the survivors are permitted to believe the counsels and
prayers of their pious father were blessed on their behalf,
and that they were made partakers of that redemption which is in Christ Jesus,
and favored to know their robes washed and made white in His precious blood.
And how full of consolation is the belief, that their spirits are now united with his,
who so fondly and faithfully watched over their early years,--shielded them from
temptations to surrounding evil,--and turned their feet into the path that leads
to blessedness:--"`Therefore are they before the throne of God,
and serve him day and night in His temple:
and He that sits on the throne shall dwell among them.
They shall hunger no more, neither thirst anymore; neither shall the sun light on them,
nor any heat.
For the Lamb which is in the midst of the throne shall feed them,
and shall lead them unto living fountains of waters:
and God shall wipe away all tears from their eyes.`"

