[quote.epigraph, , 2 Cor. 6:8-9]
____
By honor and dishonor, by evil report and good report, as deceivers and yet true,
as unknown and yet well known, as dying and behold we live.
____

== Truth Defended

It is not that we love contention, or desire controversy,
or are impatient in bearing reproaches, that we appear thus public,
but such have been the repeated high charges,
and smart lashes that our adversaries (more especially some
of the Presbyterian assembly) have of late taken a liberty,
liberally and lavishly to bestow upon us that we find ourselves concerned
to clear and vindicate the truth and innocency of our Christian profession,
from those black aspersions that have rendered it so frightful and formidable,
as though it were only a mere complication of pestilent errors,
as well as to satisfy the minds of such of our piously-inclined neighbours,
as may be desirous to hear us speak for ourselves,
as also for the information of those who may have been imposed upon,
by that dress wherein our opposers have represented us.
And although these can object nothing material against us now that hath
not been long since over and over offered by some of the same persuasion,
and have as often received answers from some or other of our friends,
(some of which have never yet been by them replied unto) yet forasmuch
as those may not have come to the view of many of our neighbours,
for whom this is chiefly intended,
we thought fit briefly to say so much as we think
may be accommodate to the present occasion;
and which perhaps with unprejudiced minds may bespeak our creed not so unsound and erroneous
as our somewhat different deportment hath rendered us obnoxious and contemptible,^
footnote:[Esther 3:5]
as well as distasteful to those who either ambitiously affect honour and respect,
and love greetings, or think a complaisant compliance to the fashions, customs,
and complements of the age, to be one of the chiefest felicities of this life,
and best expression of their civility and good manners.^
footnote:[John 5:44 and Matthew 23]

We therefore desire our well-disposed neighbours,
candidly to weigh what we have to allege against the clamours of those,
who to be sure will not set us out to our best advantage,
and to receive an account from ourselves what we are,
and what we believe and hold for Christian truths,
who certainly must needs know better our own belief
than those who perhaps never examined it,
to any other end than to find fault, if ever they did it;
and also that you will not think it strange,
that we express not our belief in some particulars,
in the affected terms of other professors of Christianity,
but think it more reasonable and safe to content ourselves with that dress of language,
in which the Holy Ghost thought fit to hand them to us in the Holy Scriptures;
those most excellent and divine writings, which above all others in the world,
challenge our reverence and most diligent reading, those oracles of God,
and rich Christian treasury of divine saving truths, which were written for our learning,
that we through patience and comfort of them may have hope,^
footnote:[Romans 15:4]
and are profitable for doctrine, reproof, correction, and instruction in righteousness,
to the perfecting and thoroughly furnishing of the man of God to every good work,
making him wise unto salvation through faith which is in Christ Jesus;^
footnote:[2 Timothy 3:15-17]
containing all Christian doctrines necessary to be believed for salvation,
and are a sufficient external standard and touchstone to
try the doctrines of men and we say with the apostle,
whosoever shall publish,
and propagate any other gospel and faith than is therein testified of to us,
by those inspired pen-men who were the first promulgators thereof,
though he were an angel let him be accursed;^
footnote:[Galatians 1:8]
all which, and whatsoever is therein contained, we as firmly believe as any of you do;
and as it is the duty of every sincere Christian,
we are heartily thankful to God for them,
who through his good Providence hath preserved them to our time,
to our great benefit and comfort.

We believe in that great omnipotent God, that made and created all things,
and gave us our being, whom in sincerity of heart we fear, reverence and worship,
being seriously concerned for our souls`' welfare to eternity.
We believe that great mystery, that there are three that bear record in Heaven,
the Father, Son, and Holy Ghost, and that these three are one in being and substance.^
footnote:[1 John 5:7]
And as do ye, so do we also hope for and expect salvation,
only and alone through the Son of God our blessed Lord and Saviour Jesus Christ of Nazareth;
believing that God the Father hath ordained him for salvation to the ends of the earth;
and that no other Name is given under heaven, by which men shall be saved;^
footnote:[Isaiah 49:6, Acts 13:47 and 4:12]
who being conceived by the Holy Ghost, in the womb of the virgin Mary,
was born of her at Bethlehem; as also his holy and exemplary life,
perfectly free from sin;^
footnote:[1 Peter 2:21-22, Hebrews 4:15]
his doctrine, miracles, sufferings, and death upon the cross,
without the gates of Jerusalem; his resurrection from the dead,
and ascension into heaven, where he is at the right hand of God the Father,
perfect God and perfect man, and the alone mediator between God and man,
and is our advocate with the Father, and ever liveth to make intercession for us;^
footnote:[Romans 8:1,34 Timothy 2:5-6, 1 John 2:1-2]
and also shall judge both quick and dead.^
footnote:[Acts 10:42]
All which, and whatsoever else is recorded of him in the sacred Scriptures,
we firmly believe.

This Jesus, in whom dwelt the fulness of the God-head,^
footnote:[Colossians 2:9]
we believe offered up himself according to the will of the Father,
an acceptable sacrifice to God, and became a propitiation for the sins of mankind,
to the end of the world,^
footnote:[Ephesians 5:1-2 John 2:2, Hebrews 10:12]
and died for all men, as all died in Adam;^
footnote:[Romans 5:12,18]
through whose blood God proclaims redemption and salvation to man,
and offers to be reconciled, and freely for his Son`'s sake to remit,^
footnote:[2 Corinthians 5:19]
forgive and pass by all past offences to as many
as shall truly and heartily repent of their sins,^
footnote:[Romans 3:25]
and turn from the same, and shall so believe in our Lord Jesus Christ,
and love him as for the future to live a holy circumspect Christian life,
and obey his commands, thereby continuing in his love.^
footnote:[Luke 24:47, Acts 10:43 and 26:20, Ephesians 4:22-24, Romans 8:3-4,
2 Corinthians 5:15-17, Titus 2:14, John 14:15,21,23-24 and 15:10,
2 Timothy 2:1,19 Peter 4:1-3, James 2:12 to the end]

Which holy life so much celebrated and strictly kept to in the primitive ages of Christianity,
that whosoever named the name,
or took the name of Christ upon them were to depart from iniquity,
we believe ought to be inseparable from a true and faithful Christian
as ever accompanying a true living and active faith;
and it seems was thought no less necessary by those who composed the promise that should
be made in behalf of infants before they were admitted into that once sacred catalogue,
(to wit) that as they came to years of discretion,
they should forsake the devil and all his works,
the pomps and vanities of this wicked world, and all the sinful lusts of the flesh,^
footnote:[Titus 2:11-12]
and keep God`'s holy will and commandments,
and walk in the same all the days of their lives:^
footnote:[Luke 1:75]
this we believe to be the bounden duty of mankind,
and though our opposers have scoffed us,
and branded us with error for holding perfection,
because in pleading for a holy righteous life as that which is well-pleasing to God,
and avouching his power to be stronger in man, as man cleaves to it,
and believes to rescue him from under the power of Satan,
than is that of the devil to retrain him in thraldom,^
footnote:[Romans 6:18-19, 22, 2 Corinthians 7:1,
Ephesians 4:1,24 Thessalonians 3:13 and 4:7, Hebrews 12:1,10,14 John 4:4]
we have sometimes made use of the words of Christ and his apostles,
as "`be you perfect as your Father which is in Heaven
is perfect,`" "`he that hath this hope in him,
purifieth himself even as he is pure,`" etc.^
footnote:[Matthew 5:48, Colossians 4:1,12 John 3:3]
Yet have we never pretended to a moral perfection
beyond what is contained in the above promise,
which is sound and true in it self, and is that which God requires of us;
and therefore it is that we frequently press its necessity,
and fervently exhort people to its performance.

And notwithstanding we have hence been falsely accused that
we expect to be saved by our own works as being meritorious,
yet we don`'t acknowledge a holy life as the efficient and procuring cause of our salvation;
which we no less than you totally refer to the free grace,
and mercy of God in Christ without any merit in man,^
footnote:[Ephesians 2:8]
but we esteem it as a constant companion thereto,
and a necessary condition on our part in compliance with God`'s gracious offer,^
footnote:[James 2:18 to the end]
without which we may not obtain it,
being inseparably annexed to that faith which only pleaseth God,
and is but our reasonable duty.^
footnote:[Hebrews 11:6, Romans 12:1-2]

And we believe that although Christ thus offered up himself once for all,
for the sins of all men to the end of the world,^
footnote:[Hebrews 2:9 and 10:12]
thereby rendering repentance and amendment of life prevalent with God;
yet that the traditional belief of that alone is not sufficient
to entitle us to that common salvation that comes by him,
but that it is of necessity that we truly repent
and be converted from the evil to the good,^
footnote:[Acts 3:19]
and therefore it is no less necessary for us now
than it was for believers in the apostles`' days,
that we be turned from darkness to light, or in other terms,
from the dark power of Satan, to the power of God who is light,
that thereby we may every one know the work of redemption and salvation,
wrought in and for our selves:^
footnote:[Acts 26:18-20]
for it is not enough to believe that Christ died,
if we feel not the blessed effects of his death, who came to save us from our sins,
and bless us by turning us from our iniquities,
and gave himself for us that he might redeem us from all iniquity,
and purify unto himself a peculiar people zealous of good works.^
footnote:[Matthew 1:21, Acts 3:26, Titus 2:14]

For we believe such to be the natural state of man in the fall,
that by nature we are dead as to God, at a distance from him prone to evil,
and to gratify the desires of our sensual minds,
swayed by the corrupt and sinful lusts of the flesh,^
footnote:[Genesis 2:17, Romans 5:12-2 Corinthians 5:14, Genesis 6:5, Romans 7:5]
and under the power of a strange king, ruled by the prince of the power of the air,^
footnote:[Ephesians 2:2]
so that our inward man being thus dead from God,
we cannot exercise our spiritual senses towards him,^
footnote:[2 Timothy 2:26]
nor can this natural man perceive, know, or savour the things of God,
which only are spiritually discerned;^
footnote:[1 Corinthians 2:14]
wherefore, notwithstanding our Saviour died for us,
we are yet by nature in a miserable undone condition, in captivity to our souls`' enemy,
except we know the second Adam, the Lord from heaven, that quickening spirit,
to quicken our souls, and make us alive to God again,
that being restored to the use of our inward senses,^
footnote:[1 Corinthians 15:45-47, Ephesians 2:1-5, Colossians 2:13, Romans 8:11,
Ephesians 5:13-14, John 1:9]
we may by the assistance of his Divine Light (wherewith for that
end he hath blest all the sons and daughters of men) see our selves
in this sad and lost state under the wrath of God,^
footnote:[Ephesians 2:3 and 5:6]
and abhor our selves therefore,
and under this living sense (wherein things will appear with another
aspect than before) cry to God for deliverance therefrom,
with such and inward hearty sorrow as works a true repentance for the same.^
footnote:[2 Corinthians 7:10]

It is not our being sprinkled, when infants, that will make us true Christians,
convert us from being children of wrath to become children of grace, and sons of God,
and members of Christ`'s church, and invest us in an interest in him;^
footnote:[John 1:12-13, Romans 8:14]
it is not learning our catechism and subscribing to certain articles of faith,
though never so orthodox,
and being educated in a historical belief of what
Christ did for us above sixteen hundred years ago;
it is not this only that will administer a sufficient, true,
and saving knowledge of Christ, and really interest us in his death and sufferings,
all which people may talk of and please themselves withal,
and yet continue as fast bound under the dominion of Satan (who still
rules where disobedience is) as those less perfect in that lesson,
but the true and saving knowledge of Christ is to
know our selves turned from darkness to light,
from the power of Satan to the power of God,^
footnote:[Acts 26:18]
that by it we may be delivered from the power of darkness,
and be translated into the kingdom of his dear Son,^
footnote:[Colossians 1:13]
to know his saving power really to rescue and redeem us
from under the power of him that hath enthralled us,^
footnote:[John 8:32-36]
and leads captive at his will those who live in the vanity of their minds,
to know him bind this strong man, to spoil his goods and dispossess, and cast him out,^
footnote:[Mark 3:27]
to know Christ to sit in the soul as a refiner, to burn up, consume and destroy,
to purify and thoroughly to purge out whatsoever is contrary to him,^
footnote:[Malachi 3:2-3]
to wash us and make us clean that we may have right to a part in him,
that being cleansed and sanctified, he may take up his abode with us,
exercising his kingly power,
and working in us both to will and to do of his good pleasure.^
footnote:[Luke 3:16-17, Romans 15:16, John 13:1,8 Thessalonians 5:23,
1 Corinthians 1:2, John 14:23, Hebrews 13:21]

The mind being thus disentangled, and having cast off its former yoke,
the old things being done away, all things now become new;^
footnote:[2 Corinthians 5:17, Ezekiel 36:26]
a new tender heart of flesh according to the promise, new thoughts, desires,
inclinations, affections, words, actions, this new inside producing a new outside also,
even throughout a new creature,^
footnote:[Matthew 23:26]
now in Christ indeed,
and really entitled to those benefits that accrue to men through him;
that living faith that pleaseth God and gives victory,^
footnote:[James 2:18 to the end, Hebrews 12:2]
and is ever fruitful to him in good works, being begotten,
and this work of redemption and regeneration thus wrought in the soul by Jesus Christ,
together with that most precious sacrifice he offered up,
when his precious blood shed upon the cross for us,
we believe completes the salvation of every soul that is thus awakened, and made alive,
and set free, by the power and spirit of him that is the way, the truth,
and the life of every soul that truly lives to God,^
footnote:[Romans 6:11-13, John 8:36]
to walk in that holy way of life, truth, and peace,
that was prepared of old for the ransomed and redeemed to walk in.^
footnote:[Isaiah 35:8-9]

And we believe that he graciously waits with exceeding great kindness,
and long-suffering, that men may repent, knocking at the door of every man`'s heart,^
footnote:[Revelation 3:20]
freely offering,
but not imposing his assistance to this most concerning
work and change in the minds of men;^
footnote:[Matthew 23:37]
so that in the day wherein God will judge the world by Jesus Christ,
and every secret thing will be made manifest,
God will be justified and clear of the blood of all men, and every mouth will be stopped,
and every man`'s condemnation will be of himself
for having rejected the day of his visitation,
wherein God calls to man, and offers to be reconciled to him for resisting the strivings,
and slighting the reproofs of his spirit,
which in matchless mercy he hath given man to instruct him, and shew,
and lead him in the way of life and peace.^
footnote:[Nehemiah 9:20]

We believe, that though the depravity of man`'s nature in the fall, is such,
that the natural or carnal man, that is enmity against God in the state of mere nature,
minds only the things of the flesh, and naturally brings forth the works thereof,
and cannot please God, nor keep and observe his laws, but is prone to evil;^
footnote:[Romans 8:5-8]
yet that those who embrace the visitation of God,
and are really regenerated and born again of incorruptible seed,
by the word of God that lives and abides forever,^
footnote:[1 Peter 1:23]
that ingrafted word^
footnote:[James 1:21]
that is quick and powerful,^
footnote:[Hebrews 4:12]
and able to save and sanctify the soul,^
footnote:[John 17:17-19]
are born into a new life, and invested with another and higher power,
and become spiritually minded,
and by the spirit are set at liberty to walk after the spirit,^
footnote:[John 3:6]
and bring forth its fruits, and receive ability from the spirit to serve God acceptably,
being now led by the spirit of God and become his children, taught of him,
and through the spirit of adoption received into their hearts,^
footnote:[Romans 8:14-15]
have right to call God Father, and Jesus Lord,
for having through the spirit mortified the old man or first nature,
with his corrupt and depraved inclinations and evil deeds, and put him off,
having crucified the flesh with the affections and lusts thereof,
they put on the new and heavenly man,
which after God is created in righteousness and true holiness,^
footnote:[1 Corinthians 12:3, Romans 8:13 and 6:6, Ephesians 4:22-24,
Galatians 5:24, Colossians 3:9-10]
and being renewed in the spirit of their minds, they now walk in newness of life,^
footnote:[Romans 6:4 and 7:6]
and are really in Christ, and therefore are changed and become new creatures,
and now think and act under the conduct of a principal
superior to that which formerly governed them,
having their minds raised to a region above that of fallen nature,
so that now the stream of their thoughts, desires and actions, runs in another current,
and the bent of their affections are after those things that are above where Christ is;^
footnote:[Colossians 3:1-2]
that eye being now opened that sees a more transcendent beauty
and desirableness in the invisible and durable treasures of him,
than all the transient felicities of this world can afford.

And we believe that whosoever expects the blessed imputation of Christ`'s righteousness,
ought thus to put on the Lord Jesus,^
footnote:[Romans 13:14]
and to be thus clothed upon, and covered with his righteousness,
and in measure have his holy life brought forth in and through them,
and know him to enliven and influence their minds, and to work in and for them,
and that without him they can do nothing, but through him that strengthens them,
they can do whatsoever he commands them, that as they abide living branches in him,
through that sap and virtue they daily receive from him,
they are made able to bring forth fruits well-pleasing to God,^
footnote:[Isaiah 26:12, Philippians 2:13, Philippians 4:13, John 15:5]
whereby he is glorified.^
footnote:[John 15:5,8]
For though God the Father accepts us in Christ, and for his sake;
yet is the new-birth the indispensable qualification,
and true distinguishing mark of those that are really in him.
He that is in Christ is a new creature, old things are past away,
behold all things are become new.
John says, "`He that saith he abideth in him, ought himself also,
so to walk even as he walked.`"^
footnote:[2 Corinthians 5:17, Galatians 6:1,15 John 2:6. and 3:7-9]

We ascribe nothing to man, as having any power or ability in or of himself to please God,
but attribute all power to do that which is good to Christ alone,^
footnote:[John 15:4-5]
in whom only the Father is well-pleased.
It is through him that men so love and fear God as to eschew evil,
and work that righteousness which is acceptable to him;^
footnote:[Acts 10:34-35]
upon whom therefore man`'s dependance ought to be daily,
to receive from him such suitable supplies,
as through a constant watchfulness may enable them so to walk,
as to continue in his favour and enjoy his smiles:
for it is not as too many seem either to imagine, or would gladly have it to be,
that they may live in sin and disobedience here, and indulge their corrupt inclinations;
and yet hereafter have Christ`'s righteousness imputed to them:^
footnote:[1 Peter 4:18]
for though we are not under the Mosaical law, so as to be obliged to its ordinances,
divers washings, and Levitical priest-hood,
Christ our high-priest having offered up himself once for all, and abolished it;^
footnote:[Matthew 5:20]
yet are we not so under grace, as to be discharged from living well,
though we are not tied to its rites and ceremonies,
yet are we obliged to fulfill its righteousness,
which Christ came not to destroy but to establish:^
footnote:[Romans 3:31 and 8:3-4]
for though God be gracious and merciful to forgive
us our trespasses through the mediation of Christ,
upon our true and hearty repentance, and turning from them;^
footnote:[Isaiah 55:7]
yet it is not that we should take a liberty to go on in sin and rebellion against him.
We are not to sin because he is gracious, that his grace may abound;^
footnote:[Romans 6:1-2]
if so, where is the straitness of this way?
If this be to take up a daily cross to our own wills that we may perform his,
pray where is the liberty of the flesh?

Those that are virtually in Christ, which renders us acceptable to the Father,
and completely espoused to him, must needs have resigned their wills,
as an effect of true love, and requisite to so strict a union,
opposite wills being inconsistent therewith, whence obedience necessarily follows.
The apostle John, after having signified that God is Light,
and that those that would know the blood of cleansing, and true fellowship with him,
and one another, ought to walk in the Light as he is in the Light,^
footnote:[1 John 1:5-7]
tells the young and weak in the faith, whom he calls children,
that he writ those things that they should not sin;
but yet if any through weakness or inadvertency should sin,
and so fall under the Father`'s displeasure,
he tells them that Christ the righteous is both a propitiation
and also an advocate that intercedes with the Father;
and that their keeping his commands was the surest
evidence of their knowing and being in him;^
footnote:[1 John 2:1-6]
but of the strong, whom therefore he calls young men,
he says that the word of God abode in them, and that they had overcome the evil one.

These things may soon be spoken and comprehended in the understanding,
but to experience them fulfilled in ourselves, is our highest interest,
and only can make us sharers in them.
The essence of Christianity and happiness of Christians,
don`'t consist in having our heads stuffed with knowledge,
only to lodge there and feed upon it, but to have our hearts filled with divine love,
which animates us to diligence,
and inspires us with courage and vigor to observe and perform the will of God,^
footnote:[John 14:21-23]
who looks not at what people profess only, or by what name they are called,
but regards the heart, and what principle governs there.
People may make a profession of the best things; and yet continue alive to themselves,
they may alter opinion or persuasion, and yet not turn from darkness to light,
from the power of Satan to God.

There hath not been wanting a very large and splendid profession of Christianity,
adorned with curious, elaborate, and elevated notions,
polished with rhetoric and oratory; but that power and life that reaches the heart,
and gives victory and dominion over its lusts and affections, which war against the soul,
is that which too many are yet strangers to;
when yet to know our lapsed souls restored from their first fallen state in Adam,
and raised to a station where we may both perceive the things of God,
and receive power to work his will, to know our minds redeemed,
and that power vanquished which led us captive, and we leavened by the heavenly gift,
into its own nature; as it is the very life and marrow of that religion,
about whose exterior parts the world is filled with noise;
so it is the proper and most concerning-business of our lives,
to find this great salvation accomplished in us;
the experimental working out whereof in the heart, by the saving grace and Spirit of God,
that is given to man to profit with,
will yield more satisfaction and true contentment to that
soul that sincerely seeks the kingdom of heaven,
and the righteousness thereof, in whom it is begun and carrying on,
than to hear or read all their days of what God hath done through all ages,
for those that truly love and fear him;
for want of which it is that the profession of Christianity is
generally so empty and barren in producing a real pious life,
attended with the fruits of the spirit,
and a due obedience proceeding from the birth of the spirit,
without which the most refined methods of worship
and devotion will not recommend us to God,
who is inaccessible by the birth of the flesh:
nor do we believe that it is acceptable to God for
people to sing before him those songs and psalms,
that were the experiences and spiritual exercises of holy men in times past,
without having some living experience of the same things in themselves;
or that people can properly and truly speak more or farther of the things of God,
than what they have known and experienced.^
footnote:[Galatians 6:3-4]

Where amongst all these sound gospel-scriptural-truths,
is lodged that latent venom so much feared and talked of by our adversaries,
that is so dangerously contagious,
and apt to infect the minds of those that shall incline to converse with us,
or our books, touching our belief in these necessary points of Christianity?
Which of them is it, that being imbibed, is more mortal and destructive to the soul,
and defiles it more than drinking a draught of poison, or going to a bawdy-house?^
footnote:[As said Tho.
Vincent.]
Where are those damnable opinions and heresies wherewith you have been terrified?
Which of them is it, that being persisted in, does necessarily lead to damnation,
and for which "`the devil must needs carry us a pick-pack to hell?`"^
footnote:[T. R.`'s unsavory and uncharitable expression.]
Is it in that we hold forth the infinite love of God to mankind,
in not only freely of his mere grace and favour, providing a sacrifice,
through which an atonement is made for the past transgressions of man,
who was never at all in a capacity to make any for himself,
which is applicable to every one who shall believe, repent and return;^
footnote:[John 3:15-16, Acts 10:1,43 Corinthians 12:7]
but hath also afforded to all the means of faith, repentance and conversion,
for God requires not impossibilities of men,
but expects they should improve those talents distributed to them,
in not only sending forth the Son of his love to die for their sins,
that they should not longer live therein,
but also in sending forth his light and spirit of truth into their hearts,
to lead and guide them into all truth, and causing his grace that brings salvation,
to appear to all men,
to instruct and teach them to deny all ungodliness and worldly lusts,
to forsake the devil and all his works, the pomps and vanities of this wicked world,
to rescue and save them from living in the sinful lusts of the flesh,
and help and strengthen them to return to their obedience, and live a sober,
righteous and godly life, to keep God`'s holy will and commandments,
and walk in the same all the days of their lives.^
footnote:[John 14:16-17, 26 and 16:13, Titus 2:11-12]

Which gift from God to man the holy Scriptures plentifully testify to,
under various denominations, as spirit, light, word, grace, seed, leaven, anointing,
etc. by all which we understand that Spirit or heavenly talent with which God
hath endowed mankind in some degree or other that he may profit with it;
in the improvement whereof by a diligent co-working therewith,
to the answering those holy ends for which we receive it,
we doubt not but to be happy in rendering a good account of our stewardship,
and entering finally into the joy of our Lord.^
footnote:[Matthew 25:14-15]
Our opposers themselves also pretend to the spirit and grace of God,
or else what means their praying for its assistance,
and those plausible finespun discourses of it,
wherewith they sometimes entertain their auditory.
We charitably hope it is more real,
than only to beautify and recommend them to the hearers, as what they cannot well avoid,
for that the Scriptures are so full of that language, and if indeed it be real,
why is that a fault and error in us which is so sound and ornamental in them?
And we think it very strange that they should apprehend any incongruity
in granting this divine principle to be a Divine Light to the mind;
since its proper office is to teach and instruct, to manifest and point to us our duty,
as well as to dispose and enable us to perform it;
and ought to be our leader and governor.
If the godly admonitions,
and exemplary lives of good men were rightly called lights to the world,
surely much more properly may this, whose fountain is light,
and does more nearly illuminate and inform the understanding,
and renders those effectual, justly challenge that necessary, and acceptable appellation.
If then the grace and Spirit of God be in the hearts of men,
surely it is not wholly inactive there,
but will be making some attempts towards accomplishing
the end for which it is placed there;^
footnote:[Titus 2:11-12, John 14:17,24 and 16:7, 8, 13, 14, 1 John 2:27]
it will be at times attacking the enemies, and endeavouring to supplant its contrary,
which being holy and pure in its nature is never reconcilable to sin and evil,
but ever strives against it, and may, as men regard,
it be infallibly known by the nature of its efforts.

And we dare appeal even to all mankind,
whether they find not something placed in their minds and consciences,
which though perhaps not regent there, yet never mingles with,
nor consents to their evil deeds, but always remains undefiled,
and testifies against them, and convicts, reproves, and condemns them for it,
and also oft-times in the cooler temper of their spirits,
manifests their states to them,^
footnote:[John 3:20-21, Ephesians 5:13]
and as it were reasons with them, discovering the evil of their ways,
secretly calling to them to come out of it, begetting desires and inclinations,
sometimes to seek after God, and to make their peace with him.
Now since man in his mere natural state, is totally dead and fallen from God,
that he cannot as of himself think a good thought; and that God only is essentially good,
and as that which is truly, so must needs proceed from him;
this principle in us that ever convicts us for vice and evil,^
footnote:[John 16:13-8]
whether in thought word or deed, and disposeth us to consider of our latter end,
and oft makes men sigh in the midst of laughter,^
footnote:[Proverbs 14:13]
reminding them, that for those things they must give an account,
that draws us heaven-ward and inclines us to virtue and goodness,
to do to all men as we would be done unto, to be just, sober, merciful, temperate,
etc. must needs be something that is not of us, but is pure and immaculate,
and of a divine nature, ever aspiring and raising the mind towards its original.

Whence it cannot be a natural light or mere light of nature, as very many would have it,
who yet talk of the spirit of God being in man, for it is an undoubted truth,
that no agent can act beyond its own sphere,
and raise its object to a state more noble than it self,
nor produce effects of a nature more sublime than its own original.
Besides it is very clear and evident from Scripture,
that the mind of man is oft lighted by a light,^
footnote:[Job 21:17, Ps. 18:28]
superior to that of mere reason,
and that man by the utmost power and extent of human reason and speculation,
(though he may arrive to implicit knowledge that there is a God,
yet) can never attain to a true, spiritual and saving knowledge of God,
without the concurrence of a divine and supernatural agent:
for though the mind of man as a rational being,
be that capacity or candle that is to be lighted,
yet it is Christ that must so enlighten it,^
footnote:[Romans 1:19-2 Corinthians 4:6, Proverbs 20:27, Luke 24:45, John 1:9,
Ephesians 5:13-14, 17]
as to give us a true discerning of those things, that appertain to him and his Kingdom,
and by adhering and yielding obedience to its discoveries,
we shall know an accession of more light.
And the apostle speaking of what God by his spirit had revealed to them, saith expressly,
that the spirit searcheth all things, yea the deep things of God;
and that as none knows the things of a man, save the spirit of man which is in him,
so the things of God knows no man but the spirit of God:
that the natural man neither knoweth nor receiveth the things of the spirit of God,
because they are spiritually discerned,
and to that end they had received the spirit which is of God.^
footnote:[Ps. 36:9, Proverbs 4:1,18 Corinthians 2:10 to the end]
The light of nature is occupied about natural objects,
those things that are within its own region, acting within its own proper orb,
but reaches not to that knowledge of God which is life eternal,
except our natural powers or human capacity be illuminated by the rays of divine light,
for the world by humane wisdom knows not God.^
footnote:[1 Corinthians 1:20]
And Christ saith very plainly and positively, that none knows the Father but the Son,
and he to whom the Son reveals him.^
footnote:[Matthew 11:27]

That these strugglings in us should be the suggestions of Satan,
that he should disquiet and disturb people for their sins, for serving him,
and put them upon endeavouring to be freed from their vassalage under his power,
were absurd to imagine; no, our Saviour puts that beyond a question, when he asks,
"`Can a kingdom divided against it self stand?`"^
footnote:[Mark 3:24-27]
And by and by saith plainly,
that whilst the strong man armed keeps the house his goods are at peace,^
footnote:[Luke 11:21]
till a stronger than he comes to bind him, etc.
So that it is clear it`'s not the devil, but the approaches of a superior power,
that breaks the peace of people for sin,
and that follows and condemns them for disobedience and transgression,
and is the same that would, and only can redeem their minds out of that miserable state,
and bind that strong man, and break his power and cast him out,
would they but join thereto, and accept of deliverance by it.

Nor does its being extended to all men, through all ages from their youth upwards,
bespeak it to be therefore natural or contemptible, but on the contrary,
of the greater moment to all men;
for besides that the apostle saith a manifestation
of the spirit is given to every man to profit withal,^
footnote:[1 Corinthians 12:7]
the blessings and gifts of God are free and valuable from their intrinsic worth;
God in nature ordained nothing in vain,
but by how much any thing is of the greatest use to us,
for sustaining and accommodating our natural life, the more common it is,
as the sun that gives light to all through all ages, etc.
It is we +++[+++who]
fondly rate things according to our fancies,
and esteem and prize them more for their rarity and curiosity, than usefulness;
but God bestows most universally that which is of the absolutest necessity to man.
Are not all men that are born, strangers and enemies to God, in the dark,
and at a distance from him in the state of nature^
footnote:[Ephesians 2:12]
and must therefore be enlightened, converted, and born again,
and made spiritual before we can be reconciled to him; shall not God then,
that would have all repent and be saved,^
footnote:[1 Timothy 2:3-4, 2 Peter 3:9]
cause the light of the Son of Righteousness to shine upon all,
and give a measure of his grace and spirit to all,
to assist them in the accomplishment of that in themselves which they cannot do of themselves,
and yet is of indispensable necessity to our salvation?
Wherefore God by his spirit strives with man so long as his day of visitation lasts.

Since then our opposers acknowledge the spirit and grace of God,
which also is light to be in man, unless they can shew it,
by its manifestly different and superior nature, tendency, and operation,
to be contradistinct from that we have been speaking of;
we see neither absurdity nor error in concluding it to be
one and the same grace and free gift of God to all,
which is always the same in nature, though it differs in degree,
and is that heavenly treasure, which God hath committed to our trust;
and blessed will they be who rightly employ and improve it,
and give place and room to this seed of the kingdom in their hearts, where,
though it may appear at first contrary to the expectation of man, little,
mean and contemptible,^
footnote:[Mathew 13:31-32]
scarcely regarded amongst the stuff, wherewith men`'s minds are filled,
yet join but to it, that it may exert its power and force, and it will grow and increase;
let but this leaven have its perfect work and it
will leaven the whole lump into its own nature.^
footnote:[Matthew 13:33]

Be pleased to consider,
whether we have justly merited the invidious invectives of our adversaries,
in believing that the Lord searches the heart of man, and shews him his thoughts,
that he hath and will remember this latter age of the world,
and hath not forgotten to be gracious in performing those bountiful
promises made in times past to the offspring of the Gentiles,
in placing his law in our hearts, and putting his truth in our inward parts,
in pouring out of his spirit upon all the sons and daughters of men,
in becoming our teacher, and giving us the knowledge of himself,
through the revelation of his Son Jesus Christ, who is come to open our blind eyes,
and to bring us, that were bound in darkness, out of the prison-house,^
footnote:[Luke 13:21, Jeremiah 17:10, Romans 8:27, Revelation 2:23, Amos 4:13,
Jeremiah 31:33-34, Ezekiel 36:26-27, Joel 2:28-29, Acts 2:16-18, Isaiah 54:13,
Matthew 11:27, Isaiah 42:7 and 61:1]
who hath promised to be with his people to the end of the world,
in believing that God hath sent us the Comforter, the Spirit of Truth,
to be our remembrancer, and to guide and direct us in the way of Truth;^
footnote:[John 14:16,17,26 and 16:3]
in attesting the sufficiency and utility of the teachings of this holy unction,
sent into our hearts,^
footnote:[1 John 2:20,27]
in believing that though Christ be in his glorified body in Heaven,
yet that he is present also in the hearts of his people,^
footnote:[John 14:17,20,23 and 17:23, 26, Isaiah 57:15-2 Corinthians 6:16,
Proverbs 8:31]
who is King of Saints, and shall he not then rule in them?

The high and holy One that inhabits eternity,
hath promised to dwell also with the humble and contrite, to revive and comfort them,
shall not he, whose presence fills heaven and earth, be present in the heart of man?
Shall not he that rejoiceth in the habitable parts of the Earth,
and delights in the sons of men, reside in his people?
Are they not members of him, and he their head?
Can there be a more intimate union and communion than between the head and the body,
the vine and the branches?^
footnote:[John 15:4-5]
The same Spirit of life that is in the head, is the life of the body also, and acts it;
he that is joined to the Lord is one Spirit,^
footnote:[1 Corinthians 6:15,17,19]
doth not the life that is in the root pass to the branches also,
and preserves them living?
Are not all dead branches, in whom this life is not?
Whosoever hath the Son of God, and feeds on him, hath life by him;^
footnote:[John 6:56-57, 1 John 5:13]
and those that have not Christ, who is the life of his saints, hath not life.
How could his people in all ages partake of him, if he were not present in them?^
footnote:[Romans 10:6-8, 2 Corinthians 13:5, Colossians 2:20]
Surely this doctrine doth not deserve to be scoffed,
but is most comfortable to those who are sick of love,
and thirst ardently after the enjoyment +++[+++not hear-say]
of him.

Consider seriously these things which are agreeable to Scripture,
and with what reason people have derided us for our belief herein;
terming it the Quakers`' Christ,
as though his manifesting himself in our hearts were another,
or distinct from Jesus Christ of Nazareth,
that is glorified with God the Father in heaven, which we deny:
for though he be ascended into heaven, and sits at the right hand of God,
far above all principalities and powers; yet is not he so circumscribed,
but that (as by him all things were made and created^
footnote:[Colossians 1:16, Ephesians 1:23 and 3:9]) he is the life,
and filleth all in all in his church and people.
Is the divinity and humanity of Christ divided?
Is not their inseparable union the true and entire Christ?
Can then his God-head be present, and he who is the heavenly man be absent?
What think you of him that appeared to John,
and gave him his commission to the seven churches?
whom he describes, Rev.
ch. 1, who saith, "`Behold, I stand at the door and knock, if any man hear my voice,
and open the door, I will come in to him, and will sup with him, and he with me.`"
The same saith, "`I am he which searches the reins and hearts,
and I will give unto every one of you according to your works.`"^
footnote:[Revelation 3:20 and 2:23]

Was not this the true Christ the Mediator, by whom God will judge the world?^
footnote:[Acts 17:31, Romans 2:16, John 1:16]
And can he make this near inspection into the innermost part of the minds of men,
so as no thought can escape his notice, if he be not present there?
What made Paul desire that our Lord Jesus Christ might be with Timothy`'s spirit,
if he thought it impossible?^
footnote:[1 John 4:13]
Do not all acknowledge the Spirit of Christ, who is the anointed, to be in his people,
and is he then absent?
Is its being a mystery,
far beyond our comprehension to conceive how it can be a
sufficient argument that therefore it is not so?
Ought we not in such cases to exercise faith?
and acquiesce in the testimony of the Holy Ghost, expressed in the sacred Scriptures,
rather than interpose with our nice and curious subtleties?
prying unnecessarily into things that are too high for us;
remembering that secret things belong to God; and that those that know most here,
know only in part the things that are invisible; and see them but as through a glass.^
footnote:[1 Corinthians 13:12-9]
Shall men that neither know themselves, nor have any intuitive knowledge of the essences,
even of the meanest things, wherewith nature everywhere presents us,
which are obvious to our senses; yet aspire to those more abstruse,
and undertake to account for that which is beyond
the reach of the most pregnant wits to penetrate.

We hope it`'s no error to avouch the power of Christ
to be stronger than that of the devil,
that he is able really to bind him, to bruise his head,^
footnote:[Genesis 3:15]
and break his power, to dispossess and cast him out,
to fulfill to the uttermost the end of his coming, to destroy the works of the devil,
and to save those from their sins who shall have true faith in his name and power.
Surely it`'s not inconsistent with Christianity to believe that Christ can, or will,
throughly purge his floor; that he can indeed deliver out of the prison-house,
and restore man out of the fall to God again,
and give him power to forsake the devil and all his works, etc.^
footnote:[1 Thessalonians 5:23]

We find it consonant to Scripture, and the gospel-dispensation,
to believe that those who are regenerated and born again of the Spirit,
have through the Spirit mortified the first carnal corrupt nature,^
footnote:[Romans 6:11,2,6,7 Peter 1:4]
which cannot please God, and if dead, and slain, and buried too,
surely then it no longer lives, but the mind is at liberty,
and restored to act in a new life, to walk after the Spirit,
and fulfill the righteousness of the law;^
footnote:[Ephesians 4:22-24, Colossians 3:9-10]
the law of the Spirit of life in Christ Jesus, having set them free from the law of sin,^
footnote:[Romans 8:2,4]
and death which is its wages.
It is for want of people`'s experiencing this real birth of the Spirit brought forth,
and knowing freedom in themselves by it,
which no duties or performances in the will of man,
nor entertaining of the most resined opinions in religion can administer,
short of the law of the Spirit of Christ in their hearts; it is for want of this,
that people are so very apprehensive, of difficulty, even to impossibility,
of living a holy righteous life; which yet is so necessary to our salvation,
that without it we cannot enter the kingdom of heaven, nor see God.^
footnote:[Matthew 5:8, Hebrews 12:14]
Nor is the way broader, or its passage less strait and difficult than they imagine; nay,
it is absolutely impossible for them to walk therein,
while they are immersed in their first corrupt unbridled nature,
which cannot keep the law of God, while their lusts and passions are rampant,
their affections inordinate, and wills unsubjected,
and follow the desires and evil inclinations of their minds without restraint.

But if they come to know another principle and power to govern their minds,
to create in them new clean hearts, to regulate and subject their wills,
to subdue and tame their passions, to limit their desires,
and direct their affections and inclinations wholly after that which is good,
to meliorate their spirits throughout, and make them heavenly-minded,
having an aversion to all evil, and a great love to virtue and goodness:
being thus perfectly transformed where is the extreme difficulty now, for the good man,
out of the good treasure of his heart, to bring forth good things?^
footnote:[Matthew 12:35]
Will not this new well-inclined inside, that now detests evil,
and loves and delights in righteousness, as naturally follow after,
and bring forth that which is good, as before he did evil?
Here is no force upon people`'s natures, but they are converted,
and throughly leavened in another nature,
and are in their measures partakers of the Divine nature,^
footnote:[2 Peter 4]
which only can work the will of God.

We request our piously-inclined neighbours, well and seriously to weigh and consider,
the absolute necessity there is for every true Christian thus to know;
their minds molded and fashioned anew, by the power and Spirit of Christ,^
footnote:[Colossians 1:13]
working mightily in them, in order to their pleasing God by a holy righteous life,
having escaped the corruption that is in the world through lust;
and considering that it is not so soon attained,
as apprehended in the understanding to be necessary:
that with all diligence they address themselves to the performing
that which is the main and proper business of our lives.
Wherefore as it hath pleased the Divine Power to
give us all things pertaining to life and godliness,
so let us with a vigilant attention to, and co-working with that grace,
which to that end is given, work out our salvation with a reverend fear;^
footnote:[2 Peter 1:3, Titus 2:11-12, Philippians 2:12-13]
since a good degree of attainment herein is soon lost,
except there be a constant sedulous watchfulness
upon the mind amidst all business and concerns,
to have a check upon our words and thoughts, and a diligent pressing forward:
for while we live in this world we are liable to temptations,
and may enter thereinto also, without a strict care and watchfulness;^
footnote:[Matthew 26:41]
our senses presenting many baits to our minds on every hand,
which Satan makes use of to beguile,
and many provocations offer themselves in our pilgrimage;
against all which God`'s grace is sufficient armour;^
footnote:[2 Corinthians 12:9]
as our minds are seasoned by it, so that where any shortness is,
it is through insincerity, negligence, or inadvertency

Nor is it a dangerous heinous heresy that we with very many professors of Christianity,
believe the universality of the love of God to all mankind; that God who is good to all,
whose mercies extend to all the works of his hands;^
footnote:[Ps. 145:9]
is sincere in his intention, and attestation thereof, and doth not design to delude us,
when he affirms, that as certainly as he lives he desires not the death of a sinner,
but rather that he would return and live;^
footnote:[Ezekiel 33:11 and 18:23]
that God, whose love and mercy is unlimited,
doth graciously and generously offer salvation, through Jesus Christ,
(upon certain conditions to be performed on our part) to all mankind,
to every individual man and woman upon the face of the Earth,^
footnote:[John 3:14-17, Isaiah 55:1, Revelation 22:17, Romans 5:18]
which is the true gospel-message, good tidings of great joy,
which shall be to all people, peace on Earth, and good will towards men;^
footnote:[Luke 2:10,14]
good cause indeed to rejoice, that all are within the verge of mercy and free pardon;^
footnote:[Isaiah 55:7, Ezekiel 18:21-22, to the end]
that God is indeed no respecter of persons, but among all nations and people,
he or she that fears him, and works righteousness is of him accepted;
and that Christ died for the sins of the whole world, yea, for every man;
surely then all for whom he died are thereby put into a capacity for salvation;^
footnote:[Acts 10:34-35, 1 John 2:2, Hebrews 2:9]
that saving grace hath appeared to all men,^
footnote:[Titus 2:11]
and a manifestation of the Spirit is given to every man to profit withal.
And that none are reprobated,
but those that continue to be deaf to the calls of this grace,^
footnote:[1 Corinthians 12:7, Proverbs 1:20 to the end]
and resist the Spirit,
and hide and neglect their talents till the day of their visitation be over;^
footnote:[Matthew 23:37]
and Christ so withdraws himself, as to cease longer to strive with them;
so that the means being taken away, they are left to themselves,^
footnote:[Nehemiah 9:20,26]
and given up to hardness of heart;^
footnote:[Isaiah 63:10, Ps. 81:11-13]
that being absent that should prepare, tender, and mollify it,
that now they cannot repent, believe, and be converted.

If thus to believe be a dangerous and pernicious error, we confess we are guilty,
and not like to be otherwise;
for we cannot persuade ourselves to embrace that anti-evangelical opinion,
that God from all eternity hath personally and conditionally,
without respect to their accepting or rejecting the salvation offered in Christ,
elected some and reprobated others by an immutable decree,
so that those who are so elected shall certainly be saved, let them do what they will,
for God`'s decree can`'t be reversed, let the unstable mind of man vary as it will:
and those that are reprobated were in effect damned
thousands of years before they were born,
so that their salvation is put beyond all hope,
let them seek it never so earnestly and diligently,
and be never so desirous to serve and please God.
For besides, that this sad tiding instead of glad tiding,
if it were really true in itself, puts an end to the whole business of religion,
by rendering all worship and devotion, all preaching, praying, assembling together,
and holy living as it were useless, by invalidating all whatsoever on man`'s part,
as nothing contributing (as a necessary condition on his part to
be performed or neglected) towards his salvation or eternal destruction.

We dare not take up an opinion so diametrically opposite to the very attributes of God,
and his repeated protestations to the contrary,
and with some men thus presume to arraign his justice, mercy and goodness;
we cannot believe that God who is love itself, and goodness itself,
and hath always manifested a wonderful care and concern for man as his darling creature,
it being disagreeable to his power,
to condemn those that have not deserved to be punished,^
footnote:[Wisdom of Solomon 12:15-16]
and having no pleasure in the death of him that dies,^
footnote:[Ezekiel 18:22, Wisdom of Solomon 11:23-24]
should yet make the major part of mankind with design to damn them, unprovoked thereto,
without ever tendering them salvation;
or that he would make the far greater number wholly
incapable of accepting the salvation tendered them,
by putting it out of their power to perform those
conditions and terms upon which he offers it,
and then condemn them to eternal misery for not complying with
those conditions that it was impossible for them to observe:
for he doesn`'t only call to all the ends of the earth (which
implies all mankind) to look to him and be saved,^
footnote:[Isaiah 45:22]
but he hath given to every one a portion of his Spirit to enable them so to do,
he hath not only sent forth the Son of his love to shed his blood for every man,
to be lifted up as Moses lifted up the brazen serpent,
that whosoever believeth in him should not perish;^
footnote:[John 3:14-16]
but he also draws them,^
footnote:[John 6:44-45]
and as they will receive it,
toucheth them with that Divine Magnet that only can incline and empower them
effectually to turn to that pole in which all our true happiness centers.

But this is the condemnation, that light is come into the world,
and men love darkness rather than light, because their deeds are evil;
and hate the light, and will not bring their deeds to it, lest it should reprove them;^
footnote:[John 3:19-20]
for whatsoever is reprovable is made manifest by the light,^
footnote:[Ephesians 5:13]
but men love their own broad ways,
to pursue the sight of their eyes and desire of their minds,^
footnote:[Ecclesiastes 11:9]
and therefore hate to be controlled therein and reformed.
The apostle stirring up the Ephesians to purity of life,
and to avoid several evils there mentioned saith expressly,
"`Let no man deceive you with vain words,
for because of these things cometh the wrath of God upon the children of disobedience.`"^
footnote:[Ephesians 5:6-7]
And in another place, that "`Those who live after the flesh shall die.`"^
footnote:[Romans 8:13]
So that it is for want of people`'s embracing the means,
and bringing their deeds to the Light of Christ in their hearts,
and heeding the reproofs of instruction,^
footnote:[Proverbs 6:23, Galatians 6:8]
which is the way of life, for want of sowing to the Spirit,
and by it mortifying the deeds of the flesh,
that people are lost and sentenced to perdition,
and not because they were personally and unconditionally reprobated from all eternity.
God who is Lord of all, is^
footnote:[1 Timothy 2:3-4]
gracious unto all, and would have all men to be saved; but they disobey the call of God,
and reject his offers, and resist the strivings of his Spirit,
and are deaf to those knocks of our Saviour for reception and entertainment in their^
footnote:[Revelation 3:20]
hearts, and choose and prefer the present world,
and will not deny themselves to follow Christ.
It is not as these men say, because salvation was never within their reach:
if it were not, what must we think?
Were those feigned tears then that our Saviour shed over Jerusalem,
when the day of its visitation was over?
Saying also, "`How often would I have gathered thee as a hen gathers her chickens,
but you would not;`" not "`you could not.`"^
footnote:[Luke 13:34, Matthew 23:37]

If any men can be so hardy as to entertain an opinion so derogatory to the justice,
mercy, love, and paternal care of God, and repugnant to the gospel-message,
we cannot but admire what should induce them to obtrude it upon others,
and urge it as though it was a necessary point to be believed in the Christian religion;
for we cannot apprehend how this begets love to God, increaseth faith in Christ,
and raiseth our veneration for him, excites to diligence, and encourages piety,
which is that which advanceth true religion; but on the contrary,
that it tends to the indulging some in a security,
and procure in others a slight esteem of the death and sacrifice of Christ,
as being partial, and casts them into despond,
and probably may encourage both to gratify the desires of their minds to the full extent,
since nothing can alter such a supposed decree of God one way or the other.

Yet we deny not the prescience of God, who fore-knows all things, things past, present,
and to come, being at once present to him; so that it may be said,
such who believe in Christ with that living active faith that works by love,
and excites to obedience, and persevere therein unto the end,
and so knows salvation by him, are in him in whom the election is before the world began;
and that those who so believe not, but reject the tenders of his love,
and by persisting in disobedience, neglects so great salvation, are condemned already.
Nor do we deny such a preference as that some are made stewards over more,
and some fewer talents, according to which their improvement ought to be:
where much is given much is required, and where less is given less is required;
for God is just and equal in all his ways, he is not a hard Master,
that he should exact or expect more than the improvement of his own:^
footnote:[Matthew 25:14-28]
had he that received but one talent, employed it, and made it two,
we doubt not but it had been accepted;
for we believe that none are from eternity absolutely excluded without any talent,
and that a day also is afforded wherein it is possible for them to improve it.
So that though the grace may work more powerfully in some than in others,
yet are all left without excuse.

There is yet another opinion dependant on this, which we cannot receive neither,
as they state it, for which our opposers think very ill of us; that is,
once in a state of grace and ever so;
that there is no total or final falling away from grace.
How this doctrine promotes true zeal and piety, and improves Christianity,
we can`'t understand, nor see no other reason why its votaries should be so fond of it,
but because it is concordant to that of personal election and reprobation;
so that those who embrace the one, are bound to believe the other: but otherwise,
certainly it tends rather to slacken than spur on people to that care and diligence,
and constant unwearied watchfulness to prayer, which our Lord so much exhorted to,
and the apostles so solicitously presses the saints everywhere to be found in,
as of absolute necessity.

What else means those promises of reward in the revelations,
to those who should overcome and hold out to the end,
but to engage them to a constant perseverance?
Or what needed it, if it were impossible for them to fall short;
who I suppose none will deny to have been in a state of grace?
And the Church of Ephesus was threatened to have their candlestick removed,
if they repented not, and did their first works;
and that of Laodicea to be spewed out of his mouth.^
footnote:[Revelation 2:3,5:16]
Who can say those foolish virgins in the parable were not once in a state of grace,
whose lamps were once lighted and burning, as well as trimmed,
or else they could not properly be said to be gone out;^
footnote:[Matthew 25:8]
or that those were not called by saving grace,
in whose hearts the heavenly seed sprung up, and for a time prospered,
till the briars and thorns, the overcare and concern about the things of this life,
choked it;^
footnote:[Luke 8:7-8, 14-15]
it was not that they had no day of visitation from God,
wherein they might have wrought out their salvation,
had they continued to make the kingdom of heaven, and its righteousness,
their first and chiefest choice,
and placed their treasure there and disentangled themselves from those unnecessary cares;
the seed that was sown and sprung up,
was the very same with that which in the honest heart brought forth fruit abundantly.

Surely Paul that great apostle was not of these men`'s opinion,
when after he had long laboured in the gospel, takes care to keep under his body,
least while he preached to others he himself should be a cast-away,^
footnote:[1 Corinthians 9:27]
whom yet we doubt not, but they will grant was then effectually called,
and in a state of grace.
And the author to the Hebrews writing in the third chapter,
to those he calls holy brethren, and partakers of the heavenly calling, verse the 12th,
exhorts them to take heed lest there was in any of them
an evil heart of unbelief in departing from the living God.
And again, chap.
4:1, "`Let us therefore fear, lest a promise being left us of entering his rest,
(surely then not eternally reprobated) any of you should seem to come short of it.`"
Verse 11: "`Let us labour therefore to enter that rest,
lest any man fall after the same example of unbelief.`"
Again chap. 6. verses 4-6, speaking of those who had been enlightened,
and had tasted of the heavenly gift, and were made partakers of the Holy Ghost,
and that had tasted the good Word of God, and the powers of the world to come,
(shewed signs that they were effectually called,
and in a state of grace) that if they should fall away it
would be impossible to renew them again to repentance;
not because they were eternally reprobated,
but because they crucified to themselves the Son of God afresh,
because they grieved his good Spirit, and rejected the means.
Hath not the Lord said, "`If a righteous man turns from his righteousness,
he shall die:`"^
footnote:[Ezekiel 18:24-26 and 33:18]
who can be righteous without the assistance of God`'s grace?
No man can make himself so; it is not in man to direct his own ways;
and yet it seems it is possible for him to fall from it,
after he hath lived so long under its conduct as by it to be made righteous,
and one would think should then be sanctified too.

Our Saviour saith of himself, "`I am the true vine, ye are the branches;
my Father is the husband-man, every branch in me that beareth not fruit he taketh away.`"
Again, "`If a man abide not in me, he is cast forth as a branch and is withered.`"^
footnote:[John 15:1-2, 5-6]
Surely those who are branches in Christ, while so, are accepted of the Father;
and yet it seems it is possible for them to fall away and be cut off as withered branches;
whence he often repeats this condition "`if ye abide in me;`" and presently
he saith the way to continue in his love was to do his will,
as he had that of his Father`'s, and continued in his love.^
footnote:[John 15:10]
But though we can`'t embrace their opinion, for their reasons, and as they state it,
but that it is possible for people to make a considerable progress in grace,
and yet for want of a careful and constant watchfulness to that grace they may fall away:
yet we believe such a state and growth in grace through a vigilant attention thereto,
and such a degree of faith attainable, as that there is no more going forth.

But that which seems to be our capital error, and the top of all their charge,
and that which is to silence all pleas in our behalf,
is our omitting the use of the ordinances (so called) of baptism and bread, and wine.
John indeed as the next immediate fore-runner of Christ to prepare his way,
gave an alarm to the Jews that were so secure under the law of Moses,
and proclaimed the kingdom of heaven at hand,
and the time come wherein God commanded the Jews,
as well as others everywhere to repent;^
footnote:[Matthew 3:2, Acts 17:30]
it was not sufficient for them to go on in sinning,
and then offer those respective sacrifices which the law enjoined them for the same,
but now the wrath of God was near to be revealed from heaven
against all ungodliness and unrighteousness of men:^
footnote:[Romans 1:18]
it was not sufficient to deck and make clean the outside of the cup and platter,
but the inside was to be cleaned, and then the outside would be clean also.
The axe was now laid to the root,
and every tree that brought not forth good fruit was to be hewn down.^
footnote:[Matthew 23:25-26 and 3:10]

The law of Moses took hold on exterior acts and could
not make perfect as pertaining to the conscience,
but now that dispensation was about to be established that comes nearer home,
and takes cognizance of the very thoughts,
that sin be not so much as conceived by the will`'s joining thereto.^
footnote:[Hebrews 9:2,9 Corinthians 10:5, James 1:15]
Wherefore John was sent to administer the baptism of repentance
as a lively figure of that which was presently after to follow;
for John`'s baptism was not capable to produce this effect upon the mind:
and he himself testifies, that though he baptized them with water,
yet he that came after him, that was before him, and more honourable than he,
should baptize them with the Holy Ghost, and with fire, that his fan was in his hand,
and that it was he should throughly purge his floor.^
footnote:[Matthew 3: 11-12]
Which is the great work that is to be done under his gospel-dispensation,
to take away the sins of the world, and destroy the works of the devil,^
footnote:[1 John 3:8]
to purify people`'s hearts, and make them spiritually minded;
this is the proper effect of Christ`'s lasting baptism,
not the washing away of the filth of the flesh,
but the answer of a good conscience towards God,^
footnote:[1 Peter 3:21]
to purge our consciences from dead works, to serve the living God in newness of life.

The baptism of Christ is but one, and those who by it are baptized into Jesus Christ,
are baptized into his death, and their old man crucified with him,
that the body of sin may be destroyed, and they no longer serve sin,
because they that are dead with Christ are freed from sin, and made alive to God,^
footnote:[Ephesians 4:5, Romans 6:3,6-8, 11]
to live a holy righteous life:
these are the blessed effects of the baptism of the Holy Ghost and fire,
and benefits that redound to those who are in truth washed by Christ
in that holy laver which entitles us to a part in him;^
footnote:[Zechariah 13:1]
it is our chiefest concern to know this inward spiritual baptism of Christ,
that our hearts may be washed, purified, and sanctified by the Spirit of God;^
footnote:[1 Corinthians 6:11]
and that we really put on Christ, and are in him who is the substance,
in whom the types ended.
John knew and foretold himself that he must decrease, but Christ must increase;^
footnote:[John 3:30]
he doth not say, "`I shall cease presently at once,
so soon as Christ`'s baptism takes place;`" but "`I must decrease.`"
But were water-baptism to continue always amongst Christians,
then would not John decrease: nor will it solve this allegation,
that it was abolished as John`'s, and instituted anew as Christ`'s,
for then hath Christ his different gospel-baptisms, which is erroneous.

We grant that some of the apostles did use water-baptism for a time,
but we believe it was rather in compliance with the circumstances of time than of necessity,
and in condescension to the weakness of believers in the very infancy of the church,
and even the same age wherein John baptized,
who was not only a true messenger of God in his time,
but had gained great credit among the people,
and his memory and message could not soon be forgotten;
nor was it easy to draw them from a practice that but just
before was acknowledged to be of divine authority:
for we find the apostles tolerated the believing Jews to
live in certain rites and ceremonies of the Mosaical law,
notwithstanding the Messiah was come in the flesh and abrogated them;
so difficult it is to disengage people from those things wherein they have been educated,
and to which their minds are once glued,
and some of them would have had the believing Gentiles come under that yoke and be circumcised,
which Paul their great apostle withstood, seeing beyond all those things,
knowing that the kingdom of God was not meats and drinks, but righteousness, peace,
and joy in the Holy Ghost;^
footnote:[Romans 14:17]
and not in word but power,^
footnote:[1 Corinthians 4:20]
not divers washings and carnal ordinances which were shadows and to perish,
but the Body is of Christ, and those that are in him, are in him complete,
believing that if they were circumcised, Christ should profit them nothing;^
footnote:[Colossians 2:10,14,16,17,22, Hebrews 9:9-10, Galatians 5:2]
and yet we see such was his condescension,
that he himself notwithstanding circumcised Timothy,
and when he was at Jerusalem shaved his head, etc.^
footnote:[Acts 21:20-28]
behaving himself as a Jew, for the sakes of those who saw not so far as himself.

And notwithstanding he was such a laborious and zealous publisher of the gospel,
yet we find he baptized but very few, and thanks God that he baptized no more,^
footnote:[1 Corinthians 1:14]
(surely it was not then essential to the gospel) but saith plainly,
that he was not sent to baptize, but to preach the gospel,
to turn people from darkness to light, from the power of Satan to God,
who had delivered them from the power of darkness,
and translated them into the kingdom of his dear Son;^
footnote:[1 Corinthians 1:17, Colossians 1:13]
it is this that is of absolute necessity to our salvation:
he did not then baptize because some others did it,
which yet is as large a commission as perhaps any pretend to now-a-days.
Of which we say as he did of circumcision (though
we do not grant it is the seal of the covenant,
and introduced in room of circumcision as some will have it,
but without scripture-authority) baptism or no baptism
availeth any thing short of a new creature,
which is the truest sign of possessing the inward spiritual grace,
and of being in Christ, and is beyond all visible signs whatsoever.
The apostles having thus indulged it, it is no wonder that it was continued,
and since got footing under the degeneracy, for as corruption entered the church,
and was increased, the spirit and life of Christianity was more and more eclipsed,
and the minds of its professors grew darker,
and then adhered more to external performances;
and not only continued that which had been used by their predecessors,
or at least something in its stead, but by degrees added more rites and ceremonies;
and at length began to trim and deck that religion that in itself was plain, simple,
and homely, and consisted more in power and divine love than outward observations;
which in process of time was so dressed and garnished,
that its August splendour became inviting to others.
Under this degeneracy in degree sprung up infant-baptism, a mere humane invention,
without any scripture-authority either by precept or practice;
wherefore for those who do not use baptism,
as it was instituted under its proper dispensation
to upbraid us for neglecting it is absurd and unreasonable.

But that which makes the loudest out-cry of all, is our disuse of the sacrament,
so called of bread and wine,
it is this is that pestilent mortal error that in our opposer`'s account,
renders us worse then the papists, whatever it is that makes us the spawn of the Jesuits,
which with several others are Epithets,
that to be sure were calculated though unjustly to
render us as odious as may be to the people,
and carry a great deal of rancour in them, and savours of too much gall,
to proceed from the meek spirit of Christianity, that teacheth to be at peace with,
and have charity for all that call on the Lord out of a pure heart:^
footnote:[2 Timothy 2:22]
but whether upon the whole matter we deserve this severe bitter censure,
or whether those that so liberally bestow it upon us,
have a just right to cast the first stone,
is what we desire our sober neighbours to consider, and not judge us also by whole-sale,
from an implicit belief of what others say of us.

We are not ignorant of the great noise and stir there hath been about this in Christendom,
to the scandalizing Christianity among both Jews and Turks:
the papists have improved it to downright idolatry,
affirming it is the real body and blood, and as such adore it,
(one would think it were better let alone) others, that Christ is in it,
though they know not how: one saith it is this, another it is that;
while they all seem to expect that from it which it doth not necessarily administer;
for want of distinguishing between that bread of life that came down from heaven,
that flesh and blood of Christ, which giveth life to all that feed thereon,
by which they dwell in him and he in them,^
footnote:[John 6:51,56]
and that supper which was eaten by the primitive
Christians in commemoration of his death and sacrifice;
which are not so connected, as that the one necessarily includes the other,
as experience abundantly testifies, would people but be true to themselves herein;
how many are there that receive this from year to year,
who yet complain all their lives of deadness, dryness, and leanness of soul,
and want of power,
not receiving that renewing of life and spiritual strength that is proposed in it,
and so but an empty shadow indeed:
for how can they in truth expect to feed on Christ spiritually in their
hearts who will not admit that he really dwells in his saints,^
footnote:[John 14:20,21,23.]
but esteem it an error in those that do; however,
we believe all people ought to be well persuaded in their own minds,
and seriously considerate in these and other religious practises,
and not take up things merely traditionally because others do it;
nor ought they to be vehemently pressed to or against
things not absolutely essential to salvation,
in which their understandings are not clear:
nor should any be scoffed or reproached for those
things which to them are matter of conscience,
and therefore sacred, though to others it may appear of less moment;
a practice that is a great shame among people professing Christianity.
Nor do we judge and condemn those that are found in the practice
either of this or water-baptism as it was primitively used,
whose sober, Christian, circumspect lives witnesseth to their sincere intentions herein,
who may be conscientiously tender in it, and fearful to omit it,
till they are otherwise fully persuaded: but for us,
to whom the barrenness and emptiness of these outward visible things are manifest,
we cannot continue therein, yielding no true soul-satisfaction,
nor administering any inward spiritual grace to us.

Wherefore having tasted that the Lord is good and gracious,
we wait for the sincere milk of that Word by which we have been begotten to God,^
footnote:[1 Peter 2:2-3]
that we may receive strength thereby, and grow in grace,
and the knowledge of our Lord Jesus Christ,^
footnote:[2 Peter 3:18]
and a greater acquaintance with that true inward
spiritual communion and fellowship with him,
wherein he sups with his saints, and they with him;^
footnote:[Revelation 3:20]
and receives life by him, who dwells in them, and they in him;
as the members are joined to the head, and partake of its life, and liveth by it;^
footnote:[Ephesians 5:30]
or the branches to the Vine,^
footnote:[John 15:5]
which receive life, virtue and nourishment from him,
whereby fruit is brought forth to the glory of God, and well-pleasing to him.
It is not sufficient that we participate hereof once a month or quarter,
but as the Jews had their manna, fresh every morning,^
footnote:[Exodus 16:21]
so ought we to receive a daily supply, and renewing of strength in our inward man,
by eating that heavenly bread, that nourisheth up to eternal life,
and drinking plentifully of that well of living water,
which in the saints springs up to life eternal;^
footnote:[John 4:14]
for as in God we live, move, and have our very being;
so is Christ the true and proper life of the inward man by which it truly lives to God,
nor can it live but by him.
Those that are begotten to God by the Word of life, and are born again of the Spirit,
are privileged thus to feed on Christ, and enjoy him,
which none can do that are not first quickened and made alive by him;
none can receive life, sap and virtue from him as head and vine,
that are not first joined to him as members and branches of him;
nor is it sufficient to make people members of Christ,
and give them admittance to feed on him, in that they were sprinkled when infants,
etc. as we have already expressed,
though they should eat bread and drink wine all their days.

Since then we no less enjoy the substance without the sign, why may we not omit it,
as either being but temporary, or not of absolute necessity,
as well as our opposers do that which was instituted
(to use their own term) at the same time,
and with as great solemnity, and greater formality,
and was no less positively commanded under the same pretence?
Why may not the same authority absolve us from the use of this,
and excuse us from being chargeable with the breach of a command of Christ,
as release them from washing one another`'s feet,^
footnote:[John 13:4-5, 8, 14-15]
and secure them from the like censure?
As also that of the apostles, concerning things strangled and blood,
and that of James anointing the sick with oil?^
footnote:[Acts 15:20,29, James 5:14-15]
Why should they be thus partial?
Have we not good reason to conclude, that if these had not been long since laid down,
they would have cleaved as close to them; and that had those of baptism,
and bread and wine been then discontinued also,
they would be now as easy under its omission?
For tradition, custom, and education,
makes greater impressions on men`'s minds than perhaps every one may be sensible of;
nor is it an easy task at first to move them from those
things to which they have been fastened by it.

Would but people wholly relinquish these prejudices, and consider it impartially,
it is probable there may appear no such real difference, as justly to omit the one,
and yet with equal reason to continue the other;
since it is not that bread that gives life to the soul, nor doth necessarily include it,
but that Christ may be, and is received, and fed on without it.
Nor that those can be thought to forget his death and sacrifice
who sensibly partake of the benefits thereof,^
footnote:[Titus 2:14]
and pursue its ends; who are taught and assisted by him to live a godly righteous life,^
footnote:[Galatians 1:4]
and bear about in them the marks of the dying of our Lord Jesus; who died for all,
that those who live should no longer live to themselves,
fulfilling the desires of their minds, but to him that died for them;^
footnote:[Matthew 1:2,21 Corinthians 5:15]
that through the power of his resurrection they may mortify the deeds of the flesh,
and have fellowship with his sufferings,^
footnote:[Philippians 3:10]
in whom his life is made manifest;
neither can those who acknowledge his death and sacrifice,
and partake from time to time of this bread and wine in memory of it,
and yet are not by him redeemed from a vain conversation,
and made conformable to his death,
and so feed on him as to participate of that life that comes by him,
in any wise escape damnation, let their pretensions be what they will.

Since then God hath replenished our hearts with his grace,
and hath not withheld his heavenly manna from us,
but daily owns us by his comfortable presence, to our great satisfaction,
under the omission of these things,
supplying our wants and necessities as we have recourse unto him,
in that which ever hath access unto him, having our continual dependancy on him,
who enables and strengthens those of us that retain our primitive sincerity and integrity,
to lead a sober, pious, Christian life, as becomes the gospel of Christ,
which is the certain product of spiritual grace;^
footnote:[For we intend not to apologize for those
who though they may be called by our name,
yet live loosely and walk disorderly, and are blemishes and a grief to us;
which yet ought to be imputed to their insincerity or unwatchfulness,
and not to the insufficiency of the principle they pretend to.]
and forasmuch as our opposers acknowledge it to be but an outward visible sign,
and dare not say that the inward spiritual grace is tied to it,
nor that it is of absolute necessity to salvation;
with what reason do they unchristian us,
and so load us with calumnies and accusations on this account,
using it as an instance to blacken us,
and condemn in gross our whole Christian profession, principally from hence,
as though it were the chief thing that constitutes a Christian,
and entitles him to the benefits that come by Christ?

What shall we think then of perhaps more than two parts in three of their own assembly,
who no more practice this than do we, and yet are many of them as sober people,
and if we may know (as Christ directs us) by their fruits,
are doubtless as near the kingdom, and no less in a state of grace,
than are those who so exult in, and value themselves upon this performance;
which however it may bound and distinguish particular societies and communions,
it is certain no observations nor performances short
of being ruled and governed by the Spirit of Christ,
as head, can entitle us to a membership in him; we may make a specious shew,
and carry a system of divinity in our heads,
but if he rules not our hearts we are none of his.
It were well they were as thoughtful to fulfill all righteousness in every respect,
and as zealously careful and concerned to observe and punctually perform all
the commands and injunctions to which the Christian religion obligeth them,
and to qualify themselves to be rightful inheritors of those
blessings and promises pronounced by our Saviour,
as they tenaciously adhere to this,
as though it were indeed the sum both of men`'s duty and enjoyments,
and that their salvation turned upon this very pin;
which yet people may perform while their wills are unsubdued, and lusts unmortified.
But we find that men have been apt enough to be busily employed about mint, annis,
and cummin, whilst they neglect the weightier matters, to run into, and cry up,
and maintain those exterior parts of religion,
that are reconcilable to an unconverted state.

If the professors of Christianity were less taken up about signs and shadows,
and nice and unnecessary scrutinies and distinctions wherewith they perplex it,
and more devoted to observe the weighty, important, and indispensable precepts of Christ,
and demonstrate the power that Christianity hath over their minds,
by affording signal instances of their being his true disciples,
and rightful heirs of his kingdom,
being in measure invested with his divine virtues and graces, we should have less envy,
variance, back-biting, and detraction, which weakens the common interest of piety,
and gives our common enemy an advantage over us; and more Christian love, peace,
concord and good neighbourhood amongst us.
If all that mean well did but pursue virtue, love it,
and encourage it wherever it appears, and hate vice and evil in all,
and discountenance it everywhere, and make these the measure of their Christian charity,
rather than parallel opinions in lesser matters, it would bring us nearer together,
and more advance true piety,
than all their contending about different apprehensions in things far less essential.

God, who regards not names, but natures, knows among all nations and people who are his;
and the rule he left us to know also was their fruits,
their actions being the exertion of their wills;
all mankind are either under the power and conduct of the Spirit of God,
or else of the devil; all are either carnal or spiritual-minded,
and as is the spring and bent of their desires and affections, so is their actions;
each birth have their proper products, which are contrary to each other.
So that let what notions or opinions soever possess men`'s heads,
they live according to that spirit and principle that governs their hearts.
We cannot gather grapes of thorns, nor figs of thistles;
no fountain sends forth bitter water and sweet at the same time.
It is an evangelical truth, those that live in envy and strife,
and bring forth the fruits of the flesh,^
footnote:[Galatians 5:19-24]
are of their father the devil;
and those who by the Spirit mortify those corrupt lusts and affections,
and bring forth the fruits of of the Spirit,^
footnote:[Ephesians 5:9]
adorning the doctrine of God our Saviour, by a sober, godly, righteous life, are of God;
for herein the children of God are manifest from the children of the devil.^
footnote:[1 John 3:10]

Thus have we candidly, though briefly,
expressed our real opinion and belief in those points in which
we apprehend our adversaries have endeavoured most to expose us,
which we hope may prove satisfactory to those who are not resolved to think ill of us:
but to speak fully to every critical, trifling objection, were a tedious task,
as well as vastly beyond the extent of our design.
We request our serious neighbours to hear and see for themselves,
and not take things upon trust from others, and to judge the things they know not,
but condemn us by hearsay;
don`'t be imposed upon by those whose peevish humours would have all do like themselves,
who either look not at all,
or but very coyly into the books of those they have taken a pet against,
whose persuasion in some things differs from what they have pronounced orthodox,
as though truth were their peculiar inclosure,
which yet certainly argues either a great deal of prejudice,
or a feeble and fleeting judgment, that dares not trust itself.

Were our books stuffed with such palpable errors as is suggested,
surely it were not so dangerous reading them: who fears to read the alcharon?
But on the contrary, it is a strong indication that they contain much truth;
for as it is the proper object of the understanding,
so where it appears with a clear evidence, answering to peoples own experience,
it is very forcible and prevalent upon the minds
of those who diligently seek it for love of it,
and willingly deposit all pre-engagements of mind in its disquisition.
Be then so just to us, and kind to your selves,
as to relinquish all prejudice and prepossessions,
and impartially examine the truth of these things;
search the sacred Scriptures diligently,
with an inclination rather to find and embrace truth, than to support a received opinion;
try whether it is so or not,
comparing it with your own experiences and the witness of God in your own hearts.
Though our belief in some of these particulars doesn`'t
exactly quadrate to that of our opposers,
it doesn`'t therefore necessarily follow, it is not agreeable to truth and Scripture;
nor can they give us any infallible assurance,
that their conceptions are a true standard of truth,
notwithstanding they vend their apprehensions as the only orthodox, yes,
and are displeased too with those that can`'t be determined by them.

We have no design carrying on behind the curtain,
howsoever our sober demeanour may be uncharitably (not to say maliciously) insinuated,
as only a cover of sheep`'s clothing upon the wolf`'s nature;
and our most solemn declaration of our belief in several
religious points (being undeniable truths) construed,
and suggested by some men as only a fair cover wherewith we guild over our poison,
that it may pass the less suspected, and be the more glibly swallowed.
What think you, is not this the height of prejudice and envy in the abstract?
Would they themselves be content to be thus interpreted?
We have no intent to decoy and trapan people, that we should walk under a disguise,
which intrigues usually have interest at one end of them,
which can`'t be our case who neither give nor take money for preaching;
so that the increase of our numbers will not fill our coffers.

We have no other interest to promote, but the advancement of true piety and Christianity:
and having love and good-will to all people,
more especially to those whose minds are awakened, and hearts warmed,
having true fervent desires, and living breathings towards God,
thirsting after a nearer and more satisfactory knowledge of, and acquaintance with him,
than barely a profession and hear-say of him,
and therefore what we have found advantageous, assistant and satisfactory to us,
in our unwearied pursuit after peace with him, that we recommend to others.
We call people home to the gift of God in themselves, which only can do them good,
that every one may know the good shepherd and bishop of souls for themselves,
and hear and know his voice in them, from that of a stranger,
and learn of him and follow him, who is pure and ever leads to purity and holiness,
that so his offering up of himself for them, may be of benefit to them,
and they experience the great salvation of God.

Impress this upon your minds, and take it along with you,
that notwithstanding our Saviour hath paid a ransom for us,
and made an atonement through the precious blood of his cross;
yet if we experience not the end of his coming, and death effected,
and answered in our selves, it shall avail us nothing;
except we know him a saviour and supporter near;
except we know a principle of Divine Light and life, to illuminate our minds,
to revive and warm our languishing hearts, to beget and increase true love to God,
and the living faith, that gives victory to convert us,
and governs our thoughts to renew and regulate our wills and limit our desires,
and bridles our tongues, to excite holy inclinations,
and keeps up a due heat in our Christianity,
and strengthens our minds in that which is good and well-pleasing to God:
except we know these things in and for our selves,
all our outside shew of religion is but vain,
and our profession of Christ shall profit us nothing,
but we shall lie down in sorrow at last; for none are Christ`'s,
but those that have his Spirit, and are influenced by it; nor are any children of God,
but those that are led by the Spirit of God;^
footnote:[Romans 8:14-9]
which begets in the mind a detestation of sin and evil, and a love to purity,
goodness and virtue.

Wherefore, laying aside all strife and animosities, all envying and evil-speaking,
let us abhor that which is evil, and cleave to that which is good,^
footnote:[Romans 12:9]
and address our selves with a due and humble application to the accomplishment
of that most concerning and important affair of our lives,
the working out our salvation.
And let every one follow the Lord faithfully, according to what is made known to them,
knowing that we shall be judged according to our knowledge,
and that it will be happy for those whose wills and
performances correspond with their understandings,
in that day when all must stand before the judgment seat of Christ,
and give an account of their deeds done in the body and receive a sentence thereafter,
either, "`Come ye blessed,`" or, "`Depart from me ye workers of iniquity.`"

It won`'t be then of +++[+++importance]
what congregation or confession of faith,
or of what persuasion amongst the many wast thou:
among all which there will then be but two sorts, the sheep and the goats;
those that heard the Shepherd`'s voice and followed him,
who were guided and governed by the good Spirit of God in their hearts;
and those who wrapping their talent in a napkin, stifled convictions,
and neglecting the day of their visitation,
continued under the dark power of the evil one.
One may go a great way,
and make a fair shew of religion and piety and yet be turned to the left hand;
it is not having our heads filled with curious sublime notions,
though of never so fine and elevated a speculation;
let`'s trim and garnish our lamps never so finely,
it will not administer an entrance without the heavenly oil,
without that holy divine unction +++[+++which]
fills our hearts, enlightens our minds,
and inflames our affections to a due watchfulness and obedience to its teachings,
which are the most assured marks of our being really in Christ,
in whom only our acceptance is.

That you with us, and we with you,
may so circumspectly live up to that light and knowledge given by Christ,
as that our consciences may not condemn us; but that,
having finished our days here with comfort, we may lay down our heads in peace,
with a well-grounded hope of a joyful resurrection,
and have boldness in the day of judgment, is our hearty desire.

If what we have written for your information, may find some place with those, who,
being impartial, and inquiring, have room to receive it,
and that it contributes to their benefit and satisfaction, we have our end:
but for those who are full, or are critical,
and ready to carp at every word or sentence that is not placed to their mind,
if not also pre-judge it, as it is not intended for them;
so we don`'t suppose it will prove to their good liking,
nor meet with a reception amongst them.
For we don`'t propose to reconcile our whole belief and
persuasion in religious matters to that of our opposers,
who notwithstanding, what we have writ, we expect will yet accuse us of error.

However,
having thus far declared ourselves in the most necessary points
of the Christian religion we don`'t think ourselves farther obliged
to answer the cavils and criticisms of such who may appear contentious,
and will never want something to object against those
that come not up in all things exactly to their level:
whom yet we advise, rather to be quiet, and study to know and govern themselves,
according to that religion that is pure and undefiled before God,
and leads to visit and assist the fatherless, and widows in their affliction,
and to keep themselves from the spots and defilements of this world.^
footnote:[James 1:27]
Were this (as it ought) our principal care and concern in our conduct,
we should have little mind or leisure to differ about matters of less moment:
and while we seem zealously to contend about religion frustrate its end.
We should not be taken up in disputing what that principle
is which God hath placed in us to do us good,
and in mean time neglect its assistance, and obstruct its operation upon the mind,
but be given up to be leavened and changed by it,
that we may partake of the blessings thereof;
and with it build on the foundation which God hath laid,^
footnote:[1 Corinthians 3:11-14]
that which may abide the fiery trial.
To which we recommend you, and remain your peaceable and loving neighbours,

William Chandler,

Alexander Pyot,

Joseph Hodges, etc.

[.the-end]
The End
