== Introduction to the American Edition.

The present edition of Piety Promoted is believed to be the only one extant
which contains all the parts of this interesting and valuable collection.
Its contents extend over a period of more than one hundred and seventy years,
and embrace concise accounts of the godly lives and
peaceful deaths of above six hundred persons.
Among these is to be found a great variety in age, condition in life,
station in the Church, and growth in religious knowledge and experience;
but they all agree in a concurrent testimony to the blessed effects of a religious life,
and to the consolation and support it furnishes on a dying bed.
They form but a small portion of the cloud of witnesses who have lived and died
in the Christian principles and practices of the religious Society of Friends,
and who have proved by happy experience their value and excellence,
both as a rule for the government of conduct through life,
and as a foundation on which they could safely rest their hopes for eternity,
in the hours of sickness and of death.

A distinguishing trait in the character of the primitive
Friends was the earnestness with which they enforced,
both by example and precept,
the indispensable obligation of a life of holiness in the fear of God.
Many of them had been educated after the strictest manner,
among the different religious societies then existing in Great Britain,
and were esteemed for their piety before they joined in profession with Friends.
When they left the societies with which they had been in communion,
although they objected to the notion of three "`distinct`"
and "`separate Persons`" in the Deity,
to the use of the word Trinity as unscriptural, and some other of the school terms;
yet it was not from any dissatisfaction or disunity with the scripture
doctrine of the Holy Three that bear record in heaven,
the eternal divinity of the Lord Jesus, his propitiatory sacrifice on the Cross,
as the one universal offering for the sins of the whole world,
or any of his offices for man`'s salvation.
They declared their full faith in all these,
and that they were seeking to attain to a more full and practical
experience of the heart-changing efficacy of vital religion,
free from those outward rites and impositions of men, on which they believed themselves,
as well as others, to have been improperly relying,
instead of pressing after the living virtue and power of the gospel,
to redeem the soul from the pollution of sin,
and to enable it to walk in newness of life.

While they felt the necessity of having a sound and firm
belief in all the doctrines of the Christian religion,
as set forth in the Holy Scriptures, they were also convinced that,
unless this belief was carried out in the daily walk and conversation,
and accompanied by those fruits of the Spirit which are the evidence of true faith,
as well as the ornament of the Christian, it would be of little avail.
Recognizing in its full extent the declaration, "`Except a man be born again,
he cannot see the kingdom of God,`" and the test laid down by the Saviour of men,
"`By their fruits shall ye know them,`" as well as his solemn words,
"`Not every one that saith unto me, Lord, Lord, shall enter into the kingdom of heaven,
but he that doeth the will of my Father which is in heaven;`" they were concerned
to warn all against the delusive notion that men might live in sin,
and in the indulgence of their carnal wills and appetites,
and yet be saved by a professed dependence on what the Lord Jesus
Christ has graciously done in his flesh for the redemption of mankind.

They were plain, practical, self-denying men and women,
deeply and earnestly engaged to live and walk in the obedience
of faith to all the requirements of the Divine law;
and their minds being enlightened from on high to see the
true nature and effects of the religion of the gospel,
they apprehended that many of its professors were resting their hopes of salvation
in a mere assent of the understanding to the truths recorded in the Scriptures,
without bringing forth those "`good works which were
before ordained that we should walk in them.`"
The inward life of righteousness in the daily fear of God being
the great object of their earnest concern and engagement,
both for themselves and others,
they called on their hearers to come home into their own hearts, and examine,
in the light which Christ gives, whether they were clean and pure, or defiled and unholy.

With no less earnestness they pressed upon all,
the necessity of a close attention and obedience
to the teachings of the Spirit of Truth in the heart,
as the great enlightener and sanctifier of man,
his guide in things pertaining to salvation,
by which every one might come to see his own state, as seen by the Searcher of hearts,
and be shown the way to come out of the thraldom of sin,
into the glorious liberty of the children of God.

They invited men to come to and believe in Christ Jesus the Lord,
not only as testified of in the Bible as the Redeemer, Propitiation, Mediator,
and Intercessor with the Father for lost, fallen man;
but also as he reveals himself in the heart by his Spirit,
showing man his undone condition in the fall,
and the only means by which he can be brought out of it, and be born again of the Spirit,
and also as a swift witness against evil, and a comforter for well-doing.
Esteeming this knowledge as the very essence of true religion,
they dwelt much upon it in their ministry and writings, and, even in their dying sayings,
enjoined it on their hearers as of the first importance to all who hoped for salvation.

The views we have here portrayed sometimes led the opponents of
the early Friends to charge them with slighting or undervaluing,
and with saying but little about,
the work of the Lord Jesus Christ in his outward appearance for man`'s sake,
and with depending for salvation on their own good works.
Such charges they steadfastly denied,
declaring that they had living faith in Him as the only Saviour and Redeemer,
a reverent esteem for all his holy offices,
and that they looked and hoped for salvation only in and through Him.
That such was their religious belief is abundantly evident by their approved writings,
a few extracts from which are here inserted.

George Fox, in a letter to the Governor and Council of Barbados,
makes the following declaration of faith, viz.:

Whereas, many scandalous lies and slanders have been cast upon us, to render us odious;
as that we deny God, Christ Jesus, and the Scriptures of truth, etc.;
this is to inform you, that all our books and declarations,
which for these many years have been published to the world,
clearly testify the contrary.
Yet for your satisfaction, we now plainly and sincerely declare:

That we own and believe in the Only, Wise, Omnipotent, and Everlasting God,
the Creator of all things in Heaven and earth,
and the Preserver of all that he hath made; who is God over all blessed forever,
to whom be all honour, glory, dominion, praise, and thanksgiving,
both now and forevermore!

And we own and believe in Jesus Christ, his beloved and only begotten Son,
in whom he is well pleased,
who was conceived by the Holy Ghost and born of the Virgin Mary;
in whom we have redemption through his blood, even the forgiveness of sins;
who is the express image of the invisible God, the First Born of every creature;
by whom were all things created that are in Heaven and in earth, visible and invisible,
whether they be thrones, dominions, principalities, or powers,
all things were created by Him.

And we own and believe, that he was made a sacrifice for sin, who knew no sin;
neither was guile found in his mouth; that he was crucified for us, in the flesh,
without the gates of Jerusalem; and that he was buried and rose again the third day,
by the power of his Father, for our justification, and that he ascended up into Heaven,
and now sitteth at the right hand of God.

This Jesus, who was the foundation of the holy prophets and apostles, is our foundation;
and we believe there is no other foundation to be laid, but that which is laid,
even Christ Jesus, who tasted death for every man, shed his blood for all men;
is the propitiation for our sins, and not for ours only,
but also for the sins of the whole world: according as John the Baptist testified of him,
when he said, "`Behold the Lamb of God that taketh away the sins of the world.`" John 1:29.

We believe that He alone is our Redeemer and Saviour, the Captain of our Salvation,
who saves us from sin, as well as from Hell and the wrath to come,
and destroys the devil and his works; He is the seed of the woman,
that bruises the serpent`'s head, viz. Christ Jesus, the Alpha and Omega,
the first and the last.
He is, as the Scriptures of truth say of him, our wisdom, righteousness,
justification and redemption; neither is there salvation in any other,
for there is no other name under heaven, given among men, whereby we may be saved.

He alone is the Shepherd and Bishop of our souls:
He is our Prophet whom Moses long since testified of, saying,
"`A Prophet shall the Lord your God raise up unto you, of your brethren like unto me;
Him shall ye hear in all things, whatsoever He shall say unto you:
and it shall come to pass that every soul that will not hear that Prophet,
shall be destroyed from among the people.`" Acts 2:22-23.

He is now come in Spirit,
and hath "`given us an understanding that we know him that is true.`"
He rules in our hearts by his law of love and life,
and makes us free from the law of sin and death.
We have no life but by him, for he is the quickening Spirit, the second Adam,
the Lord from Heaven,
by whose blood we are cleansed and our consciences
sprinkled from dead works to serve the living God.
He is our Mediator, who makes peace and reconciliation between God offended,
and us offending.
He being the Oath of God, the new covenant of light, life, grace and peace,
the author and finisher of our faith.
This Lord Jesus Christ, the Heavenly Man, the Immanuel, God with us,
we all own and believe in; He whom the High Priest raged against,
and said he had spoken blasphemy;
whom the priests and elders of the Jews took counsel together against, and put to death;
the same whom Judas betrayed for thirty pieces of silver, which the priests gave him,
as a reward for his treason; who also gave large money to the soldiers,
to broach a horrible lie, namely, that his disciples came and stole him away by night,
whilst they slept.
After he was risen from the dead, the history of the Acts of the Apostles sets forth,
how the chief priests and elders persecuted the disciples of this Jesus,
for preaching Christ and his resurrection.
This, we say, is that Lord Jesus Christ, whom we own to be our life and salvation.`"

In his Answer to all such as falsely say the Quakers are no Christians, he says, viz.:

We own the Father, the Son and the Holy Ghost, as the Apostles have declared.
"`And it is the Spirit that beareth witness, because the Spirit is truth;
for there are Three that bear record in Heaven, the Father, the Word, and the Holy Ghost,
and these Three are one; and there are Three which bear record in earth, etc.,
which we own, 1 John 5:6-7. And now let none be offended,
because we do not call them by those unscriptural names of Trinity, and Three Persons,
which are not Scripture words; and so do falsely say, that we deny the Father, the Word,
and the Holy Ghost, which Three are one that bear record in Heaven, etc.,
which Three we own with all our hearts, as the Apostle John did,
and as all true Christians ever did, and now do; and if you say we are not Christians,
because we do not call the Father, Son, and Holy Ghost, the Trinity,
"`distinct and separate persons,`" then you may as well conclude that John was no Christian,
who did not give the Father, Word, and Holy Ghost, these names.

We believe concerning God the Father, Son, and Spirit,
according to the testimony of the Holy Scripture,
which we receive and embrace as the most authentic
and perfect declaration of Christian faith,
being indited by the Holy Spirit of God, that never errs: 1st,
That there is one God and Father, of whom are all things; 2ndly,
That there is one Lord Jesus Christ, by whom all things were made, John i. and xvii.
and Rom ix., who was glorified with the Father before the world began,
who is God over all, blessed forever, John xiv.
That there is one Holy Spirit, the promise of the Father and the Son, and leader,
and sanctifier, and comforter of his people, 1 John v. And we further believe,
as the Holy Scriptures soundly and sufficiently express, that these Three are one,
even the Father, the Word, and Spirit.

Robert Barclay in his Apology for the true Christian divinity, has these words, viz.:

First then, as by the explanation of the former thesis appears,
we renounce all natural power and ability in ourselves,
in order to bring us out of our lost and fallen condition, and first nature; and confess,
that as of ourselves we are able to do nothing that is good,
so neither can we procure remission of sins or justification by any act of our own,
so as to merit it, or draw it as a debt from God due unto us,
but we acknowledge all to be of and from his love,
which is the original and fundamental cause of our acceptance.

Secondly: God manifested this love towards us in the sending of his beloved Son,
the Lord Jesus Christ, into the world; who gave himself for us,
an offering and a sacrifice to God, for a sweet smelling savour;
and having made peace through the blood of his cross,
that he might reconcile us unto himself, and by the Eternal Spirit,
offered himself without spot unto God, and suffered for our sins,
the just for the unjust, that he might bring us unto God.

Thirdly then, Forasmuch as all men who have come to man`'s estate,
(the man Jesus only excepted,) have sinned, therefore all have need of this Saviour,
to remove the wrath of God from them, due to their offences:
in this respect he is truly said to have borne the iniquities of us all,
in his body on the tree, and therefore is the only Mediator,
having qualified the wrath of God towards us;
so that our former sins stand not in our way, being,
by virtue of his most satisfactory sacrifice, removed and pardoned.
Neither do we think that remission of sins is to be expected, sought, or obtained,
any other way, or by any works or sacrifice whatsoever, though,
as has been said formerly, they may come to partake of this remission,
that are ignorant of the history.

William Penn, in his Primitive Christianity Revived, has the following, viz.:

We do believe, that Jesus Christ was our holy sacrifice, atonement and propitiation;
that he bore our iniquities,
and that by his stripes we were healed of the wounds Adam gave us in his fall;
and that God is just in forgiving true penitents upon the credit of that holy offering,
Christ made of himself to God for us, and that what he did and suffered,
satisfied and pleased God, and was for the sake of fallen man, that had displeased God:
and that through the offering up of himself once for all, through the Eternal Spirit,
he hath forever perfected those, in all times, that were sanctified,
who walked not after the flesh, but after the Spirit. Rom. 8:1.
Mark that.

In short, justification consists of two parts, or hath a twofold consideration, viz.,
justification from the guilt of sin,
and justification from the power and pollution of sin; and in this sense,
justification gives a man a full and clear acceptance before God.
For want of this latter part it is, that so many souls, religiously inclined,
are often under doubts, scruples, and despondencies,
notwithstanding all that their teachers tell them of the
extent and efficacy of the first part of justification.
And it is too general an unhappiness among the professors of Christianity,
that they are apt to cloak their own active and passive disobedience,
with the active and passive obedience of Christ.

The first part of justification, we do reverently and humbly acknowledge,
is only for the sake of the death and sufferings of Christ: nothing we can do,
though by the operation of the Holy Spirit, being able to cancel old debts,
or wipe out old scores: it is the power and efficacy of that propitiatory offering,
upon faith and repentance, that justifies us from the sins that are past;
and it is the power of Christ`'s spirit in our hearts,
that purifies and makes us acceptable before God.
For till the heart of man is purged from sin, God will never accept of it.`"

George Whitehead, writing in the name of the Society, makes the following declarations,
viz.

The Holy Scripture Trinity, or Three thereby meant, we never questioned, but believed;
as also the unity of Essence; that they are one substance, one Divine infinite Being,
and also we question not, but sincerely believe, the relative properties of Father, Son,
and Holy Ghost, according to Holy Scripture testimony, Matt. 28:19,
and that these Three are One. 1 John 5:7.
`"

We sincerely profess and declare in the sight of God and men,
that we do faithfully believe and profess the divinity and humanity, or manhood,
of our blessed Lord and Saviour Jesus Christ, the eternal Word of God:
and that in the fulness of time he took flesh,
being miraculously conceived by the Holy Ghost and born of the Virgin Mary,
and suffered the cruel death of the cross, as an universal offering and sacrifice,
both in his body and blood shed thereon, for the sins of the whole world;
and was buried and rose again the third day,
and visibly ascended (was seen in his ascending) and passed into heaven and glory;
and that he ascended far above all heavens, that he might fill all things;
and that by his suffering and sacrifice he hath obtained eternal redemption for us,
which, through faith in his name and power, true repentance and conversion,
we livingly receive and effectually partake of.

That we are not pardoned, justified, redeemed or saved by our own righteousness, works,
merits or deservings; but by the righteousness,
merits and works of this our blessed Lord and Saviour Jesus Christ,
being both imparted and imputed to us, as he is of God made unto us, wisdom,
righteousness, sanctification and redemption.
Our reconciliation, redemption, pardon, sanctification and justification,
having respect both to his suffering death, and blood, upon the cross,
as the one peace-offering and sacrifice, and as our High Priest;
thereby making atonement and reconciliation for us,
and giving himself a ransom for all mankind:
and also to the effectual saving work of his grace and good Spirit within us,
bringing us to experience true repentance, regeneration and the new birth,
wherein we partake of the fellowship of Christ`'s sufferings and power of his resurrection.
In which grace we ought to persevere in newness of life and faithful obedience unto him,
unto the end, that we may be heirs of the eternal salvation,
which Christ is the author of.

We sincerely believe also, that the man Christ Jesus,
is the only Mediator between God and men, our Intercessor and Advocate with the Father;
and that he exerciseth his kingly office,
and his priestly and prophetical office in his kingdom and church here on earth,
wherein he governs,
and plentifully affords both immediate inspiration and instruction
to his faithful followers who walk in his light,
to guide them into all truth; and he that hath not the Spirit of Christ is none of his.

And that this same Lord Jesus Christ, who died for all men,
enlightens every man coming into the world, and was and is the light of the world,
the Way, the Truth, and the Life:
and that the same Christ that was crucified and put to death as concerning the flesh,
and quickened by the Spirit and power of the Father,
he is inwardly revealed and spiritually in the hearts
of true and spiritual believers by his holy Spirit,
light, life and grace.
And that therefore his coming and appearing outwardly
in the flesh and inwardly in the Spirit,
cannot render him two Christs, but one and the same very Christ of God,
blessed forevermore.`"

Richard Claridge,
in stating the belief of the Society of Friends on the doctrine of justification,
uses the following language, viz.:

In a word, if justification be considered in its full and just latitude,
neither Christ`'s work without us, in the prepared body, nor his work within us,
by his Holy Spirit, is to be excluded;
for both have their place and service in our complete and absolute justification.

By the propitiatory sacrifice of Christ without us, we, truly repenting and believing,
are, through the mercy of God,
justified from the imputations of sins and transgressions that are past,
as though they had never been committed; and by the mighty work of Christ within us,
the power, nature, and habits of sin are destroyed, that as sin once reigned unto death,
even so now grace reigneth, through righteousness, unto eternal life,
by Jesus Christ our Lord.
And all this is effected, not by a bare or naked act of faith, separate from obedience;
but in the obedience of faith,
Christ being the author of eternal salvation to none but those that obey him.`"

In a pamphlet declaratory of the faith of the religious Society of Friends,
drawn up in the form of question and answer for the
information of the Parliament of Great Britain,
and published in the year 1689, we find the following, viz.:

"`Question.
What`'s your belief concerning the blessed Trinity as our term is?

"`Answer.
Our belief is, that in the unity of the Godhead there is Father, Son, and Holy Ghost,
being those Three Divine Witnesses that bear record in Heaven, the Father, the Word,
and the Holy Spirit, and that these Three are one,
according to Holy Scripture testimony.`"

"`Question.
Do you believe the divinity and humanity of Jesus Christ, the eternal Son of God,
or that Jesus Christ is truly God and man?

"`Answer.
Yes, we verily believe that Jesus Christ is truly God and man,
according as Holy Scripture testifies of Him; God over all, blessed forever,
the true God and eternal life; the one Mediator between God and men,
even the Man Christ Jesus.

"`Question.
Do you believe and expect salvation and justification
by the righteousness and merits of Jesus Christ,
or by your own righteousness or works?

"`Answer.
By Jesus Christ, his righteousness, merits, and works, and not by our own:
God is not indebted to us for our deservings,
but we to him for his free grace in Christ Jesus,
whereby we are saved through faith in him, not of ourselves,
and by his grace enabled truly and acceptably to serve and follow him as he requires.
He is our all in all, who worketh all in us that is well pleasing to God.

"`Question.
Do you believe remission of sins and redemption, through the sufferings, death,
and blood of Christ?

"`Answer.
Yes; through faith in him, as he suffered and died for all men,
gave himself a ransom for all; and his blood being shed for the remission of sins,
so all they who sincerely believe and obey him,
receive the benefits and blessed effects of his suffering and dying for them: they,
by faith in his name,
receive and partake of that eternal redemption which he hath obtained for us,
who gave himself for us that he might redeem us from all iniquity: He died for our sins,
and rose again for our justification; and if we walk in the light as he is in the light,
we have fellowship one with another,
and the blood of Jesus Christ his Son cleanseth us from all sin.`"

Another declaration of faith, dated in 1693, contains the following, viz.:

We sincerely profess faith in God by his only begotten Son Jesus Christ,
as being our light and life, our only way to the Father,
and also our only Mediator and Advocate with the Father.

That God created all things, he made the worlds, by his Son Jesus Christ,
he being that powerful and living Word of God by whom all things were made;
and that the Father, the Word, and Holy Spirit are one, in Divine Being inseparable;
one true, living and eternal God, blessed forever.`"

Yet that this Word, or Son of God, in the fulness of time, took flesh,
became perfect man,
according to the flesh descended and came of the seed of Abraham and David,
but was miraculously conceived by the Holy Ghost, and born of the Virgin Mary.
And also further declared powerfully to be the Son of God,
according to the Spirit of sanctification, by the resurrection from the dead.

That in the Word, or Son of God, was life, and the same life was the light of men;
and that he was that true light which enlightens every man coming into the world;
and therefore that men are to believe in the light,
that they may become the children of the light;
hereby we believe in Christ the Son of God, as he is the light and life within us;
and wherein we must needs have sincere respect and honour to, and belief in, Christ,
as in his own unapproachable and incomprehensible glory and fulness;
as he is the fountain of life and light, and giver thereof unto us; Christ,
as in himself, and as in us, being not divided.
And that as man, Christ died for our sins, rose again,
and was received up into glory in the heavens.
He having, in his dying for all, been that one great universal offering,
and sacrifice for peace, atonement, and reconciliation between God and man;
and he is the propitiation not for our sins only, but for the sins of the whole world.
We were reconciled by his death, but saved by his life.

That Jesus Christ,
who sitteth at the right hand of the throne of the Majesty in the heavens,
yet he is our King, High Priest, and Prophet, in his church, a Minister of the sanctuary,
and of the true tabernacle which the Lord pitched, and not man.
He is Intercessor and Advocate with the Father in heaven,
and there appearing in the presence of God for us,
being touched with the feeling of our infirmities, sufferings and sorrows.
And also by his Spirit in our hearts,
he maketh intercession according to the will of God, crying, Abba, Father.`"

That divine honour and worship is due to the Son of God;
and that he is in true faith to be prayed unto,
and the name of the Lord Jesus Christ called upon, as the primitive Christians did,
because of the glorious union or oneness of the Father and the Son;
and that we cannot acceptably offer up prayers and praises to God,
nor receive a gracious answer or blessing from God, but in and through his dear Son,
Christ.

An opponent having charged the Society with being Socinians,
and denying the divinity of Christ, etc.,
the following declaration of faith was drawn up, signed by thirty-two Friends,
and presented to Parliament in 1693, viz.:

1+++.+++ That we sincerely believe and confess that Jesus of Nazareth,
who was born of the Virgin Mary, is the true Messiah, the very Christ,
the Son of the living God, to whom all the prophets gave witness.
And we do highly value his death, sufferings, works, offices, and merits,
for the redemption and salvation of mankind, together with his laws, doctrines,
and ministry.

2+++.+++ That this very Christ of God, was and is the Lamb of God,
that takes away the sins of the world, who was slain, was dead, and is alive,
and lives forevermore, in his divine, eternal glory, dominion, and power,
with the Father.

3+++.+++ That the Holy Scriptures of the Old and New Testament, are of divine authority,
as being given by inspiration from God.

4+++.+++ And that magistracy or civil government, is God`'s ordinance,
the good ends thereof being for the punishment of evil doers,
and praise of them that do well.

And we know of no other doctrine or principle, preached, maintained,
or ever received among or by us, since we were a people,
contrary to these before mentioned.

The doctrines set forth in the foregoing extracts,
have been steadfastly maintained by the religious Society of Friends,
down to the present day.
In perusing the following pages the reader is requested
to bear in mind the preceding observations and testimonies,
and to remember that those pious persons whose dying sayings are there recorded,
were firm believers in the Lord Jesus, both as he appeared at Jerusalem,
and as he reveals himself in the heart by the Holy Spirit;
and having through Him experienced redemption from sin,
the great barrier between the soul and God,
they dwelt chiefly on the necessity of regeneration and sanctification,
knowing it was the thing most needed among the professors of the name of Christ;
his divinity, and his offices in the work of salvation,
being then seldom denied or called in question.
Notwithstanding all they said of that freedom from sin and obedience unto righteousness,
to which the Holy Scriptures bear such ample testimony,
and of which they were made joyful partakers through submission
to the power of the Holy Spirit working in them;
still their dependence was on the Lord Jesus Christ, their Redeemer, Sanctifier,
propitiation, and complete Saviour.

In putting forth a new edition of Piety Promoted,
it is the desire of the publishers that the serious perusal of its instructive contents
may incite the reader to follow the bright examples there exhibited of humble,
self-denying, and consistent walking with God,
that being found in the footsteps of Christ`'s companions,
he also may receive the end of his faith, even the salvation of the soul.

William Evans.

Thomas Evans.

Philadelphia, 1st Month, 1854.
