== To The Reader.

I here present thee with a collection of the Dying Sayings of many persons
who lived and died in faith and communion with the people called Quakers,
some of whom it pleased God eminently to make use of,
for the gathering of that people into a distinct fellowship
and society from other professions in religion.
And as God was pleased to call them forth into that work, so he supported them in it,
and crowned their labours with success, and gave them not only peace in their own souls,
but also full assurance of eternal life in the world to come.

And inasmuch as the Lord delivered these from evil works,
and has preserved them unto his heavenly kingdom,
and their names are written in his book, so with us they ought to be had in remembrance.
And some "`are worthy of double honour,
especially they who laboured in the word and doctrine,`"
for the service they have done in their generation,
who "`followed the Lord Jesus Christ, denied themselves, and took up their cross,
despising the friendship and glory of this world.`"
For what things were gain to them before, those they counted loss for Christ`'s sake,
for whom they suffered the loss of all things,
and counted them but dung that they might win Christ, and be found in him.
Christ Jesus was the object of their faith, however the world, who were unworthy of them,
represented and slandered them.
It was in the name of Jesus Christ that they preached salvation, faith,
and remission of sins;
"`for there is no other name under heaven given among men whereby we must be saved.`"
This name, which they preached to others, their faith was in,
and that gave them victory over the world,
so that they became more than conquerors through Him that loved them.
Great was their faith, zeal, and labour in the gospel,
speaking in this name of the things of the kingdom of God,
and spreading the same abroad throughout the nations,
notwithstanding they were persecuted for their faithful testimony.
For they made the like choice with Peter and John,
to "`hearken unto God rather than men,`" when they were commanded not to speak at all,
nor teach in the name of Jesus;
for they could not but speak the things which they had seen and heard.

Manifold were their sufferings for the same, as cutting off of ears,
whipping and beating till their flesh was like a jelly, knocking down,
and sore abuses in public places of worship, and in markets and streets;
and many other evil entreatings, which but briefly to mention would make a large volume;
besides long imprisonments under premunire, and otherwise, in nasty jails and dungeons,
and holes, whereby many lost their lives.

Others were openly executed in New England, for no other offence than being Quakers,
and preaching in the name of Jesus, contrary to the command of men.
Yet they steadfastly kept the faith,
like those faithful soldiers recorded in the 11th chapter of the Hebrews, who,
though they were tortured, refused deliverance,
it being not offered them upon terms agreeable to the will of God.
God was with them, and bore up their spirits over all the wrath and cruelty of men, yea,
and over death itself, and filled their souls so much with the joy of the Holy Ghost,
that they declared, as they were led to the gallows,
that it was the greatest joy and honour that they could enjoy in this world:
farther saying, no eye could see, no ear could hear, no tongue could speak,
nor heart could understand, the sweet incomes and refreshings of the Spirit of the Lord,
which they at that time enjoyed.
They also declared, that they suffered not as evil-doers,
but as those who had testified and manifested the truth;
putting the people in mind of the day of their visitation,
and exhorting them to mind the light that was in them, which is the light of Christ;
which they testified of, and were then going to seal +++[+++their testimony]
with their blood; committing their cause to God,
and their souls to the Lord Jesus Christ; praying at the hour of death,
in the words of the martyr Stephen, "`Lord Jesus receive my soul.`"

So that it hath pleased God, not only to give some of his despised people,
called Quakers, faith to believe in Christ Jesus,
who is the "`true light which lighteth every man that cometh into the
world,`" but also hath given them power and ability to suffer for that
blessed testimony which he hath again raised up in this latter age,
and also to seal the same with their blood.
This testimony is the same with John`'s testimony, who was sent from God,
and did "`bear witness of the light, that all men through him might believe.
He was not that light, but was sent to bear witness of that light.
That was the true light, which lighteth every man that cometh into the world.`"

It was the work of the primitive preachers "`to turn people from darkness unto light,
that they might receive the forgiveness of their sins,
and an inheritance among them which are sanctified by faith which is in Christ.`"
And it is the same doctrine which the great Lord of all, Jesus Christ himself,
preached in the days of his flesh -- "`I am the light of the world:
he that followeth me shall not walk in darkness, but shall have the light of life.`"
And again-- While ye have the light, believe in the light,
that ye may be the children of the light.`"
This way the prophet Isaiah exhorted the house of Jacob to walk in,
after he had foretold the peaceable effects that the word of the
Lord should bring to pass in the nations in the latter days;
"`O, house of Jacob, come ye, and let us walk in the light of the Lord.`"
To this agreeth the testimony of John the divine,
"`that the nations of them that are saved shall walk in the light
of God and the Lamb:`" and those who walk in the light,
"`the blood of Jesus Christ our Lord cleanseth them from all sin.`"

Reader, dost thou desire to die the death of the righteous,
and have thy last end like unto his?
Take then heed to this light that shineth in thy heart.
"`For God, who commanded light to shine out of darkness, hath shined in our hearts,
to give the light of the knowledge of the glory of God, in the face of Jesus Christ.`"
Here the apostle asserts, that the great love of God in Christ Jesus is manifested in man.
Therefore, thou who desires to have peace with God on a dying bed,
"`believe in the light,
so thou wilt become a child of the light,`" and wilt do the truth.
He who doth truth, cometh to the light; he loves it, and desires to be tried by it; for,
as our Lord said, he bringeth his deeds to the light,
that his deeds may be manifest that they are wrought in God.

It was this experience that those of our friends, mentioned in the ensuing collection,
attained unto.
They believed in the light, they walked in the light, and,
according to their several measures, they knew the blood of Jesus to cleanse their souls,
and to "`sprinkle their hearts from an evil conscience, and their bodies +++[+++to be]
washed with pure water;`" and when they came to die,
they could declare their experience of the work of Christ in their souls,
and that God had forgiven them their sins, for Christ`'s sake.
They could say that there was no cloud in the way,
God having fulfilled his promise of the latter days upon them, saying,
"`I will forgive their iniquity, and I will remember their sin no more.
Their hearts did not condemn them, but their conscience did bear them witness,
and their thoughts excused them.`"
Blessed are they who arrive at this experience: they can say with the prophet,
"`The work of righteousness is peace, and the effect of righteousness,
quietness and assurance forever;`" and with the apostle, "`Glory, honour,
and peace to every man that worketh good.`"

So that the terms on which we must inherit eternal life, are faith and obedience;
and to that end the apostle declared,
that "`the mystery which was kept secret since the world began,
is now made known to all nations for the obedience of faith.`"
The same apostle saith, that "`God will give to them,
who by patient continuance in well-doing, seek for glory, honour, and immortality,
eternal life: but unto them who obey not the truth, but obey unrighteousness,
indignation and wrath.`"
Therefore is Christ called the "`Author of eternal salvation to all them that obey him.`"

Wouldst thou not be afraid to die?
come then unto Christ, believe in him, and obey him,
and he will bring forth the work of righteousness in thee,
the fruit whereof shall be peace and assurance forever:
Thus it is well with the righteous, even here, as the promise is,
"`It shall be well with him hereafter.`"

Help is laid upon Christ, and he is mighty to save.
Receive him in the "`manifestation of his holy Spirit,
light and grace in thy heart,`" where thou wilt receive power to overcome sin in the bud,
or first appearance of it;
for our Lord has taught us that "`out of the heart proceed evil thoughts,
before they come into action, as murder, adultery, fornication, etc.`"
So that if we keep to the cross of Christ,
that will crucify the "`flesh with the affections and lusts,`"
and we shall be preserved from the consent to sin,
and so from the guilt and wrath to come.
This will make a sick-bed easy to us, death will be no terror to these.
The sting thereof, which is sin, being taken away,
it will be embraced as the door of entrance into eternal rest,
as one of our friends said, viz. Judith Fell,
being as it were her last words,`" This is the way to rest,
this is the way to rest forever.`"
And indeed many are the living testimonies which they have left behind,
of the certainty of their knowledge that their Redeemer lived,
and that there was a crown of life which God, the righteous judge, would give unto them,
and they desired to be dissolved, that they might inherit the same,
having already "`their inheritance sealed unto them by the Spirit of God.`"

Some said as followeth, viz.:

Richard Hubberthorn: "`I know the ground of my salvation,
and am satisfied forever in my peace with the Lord God.`"

Thomas Loe: "`I am near leaving you, I think; but as well in my spirit as I can desire.
I bless the Lord,
I never saw more of the glory of God than I have done this day;`" and he sang, "`Glory,
glory to the Lord forever.`"

Richard Farnsworth: "`I am filled with the love of God more than I can express;
and God has really appeared for us.
If God himself had come down and spoken as a man,
he could not have spoken more clearly to us than he hath done,
by many testimonies from heaven in his people.`"

Josiah Coale: "`For my part, I have walked in faithfulness with the Lord,
and I have thus far finished my testimony, and have peace with the Lord,
and his majesty is with me, and his crown of life is upon me.`"

Francis Howgill: "`As for me, I am well content to die;
and if any enquire after my latter end,
let them know that I die in the faith in which I lived and suffered for.`"

William Bayley: "`Tell my friends, I go to my Father and to their Father,
to my God and to their God; and let not my wife mourn in sorrow,
for it is well with me.`"

Sarah Beck: "`I feel sweet peace and great joy.
O the joy that is laid up for the righteous:
who would not fear the Lord! who would not be faithful!`"

Yea, we find children crying Hosannah upon their dying beds.
A young maid of sixteen or seventeen years old, viz. Elizabeth Braithwait,
who was in prison for the truth, said, I had rather die here than in any other place.
I believe God will shortly set me free from these and all other bonds,
over all their heads; and in his peace, in true patience I possess my soul,
and am contented, if it be his will, to be dissolved.`"

A child of nine years old, viz. Sarah Camm, said, "`My sins are forgiven me,
and I shall have a resting-place in heaven.
The Lord hath redeemed my soul to praise his name on high forever.
Oh, praises, praises to the Lord, bless his holy name,
O my soul.--It will be well with me and all that fear the Lord,
for we shall have everlasting joy in heaven.`"

One about twelve years old, viz. Mary Samm, said,
"`I cannot but praise the name of the Lord whilst I have being.
I do not know how to praise him enough.
I shall die today, and my soul shall go to heavenly joy,
and everlasting peace forevermore.`"

A friend said, viz. Stephen Crisp:
"`I have a full assurance of my peace with God in Christ Jesus;
my integrity and uprightness of heart is known to the Lord,
and I have peace and justification in Christ Jesus.`"

I shall not insert more of this kind in the preface,
for thou wilt find great plenty of such like testimonies behind;
only to show how well it goes with the righteous here,
and how desirable their latter end is, and what blessed fruits righteousness brings,
and what assurance it giveth of everlasting life.
Oh! that I could, by these good examples,
prevail upon some to be wise and understand this, to consider their latter end;
and that those who are young in years might not put off this consideration till old age,
seeing that here are many instances of young persons, who,
if they had forgotten the Lord in their early days,
he would not have spoken peace to them therein.

This may be observed in the instance of Mary Harris, who, for a time,
withstood the visitation of the Lord, and hardened her heart against his reproofs;
though upon her sincere repentance and deep humiliation
she was pulled as a brand out of the burning,
and God showed mercy to her soul.
But what said she, as a warning to others who lived in pleasures?
"`See here, the Lord hath made these bones bare for my rebellion.
Because I would not submit to his precious truth, he hath brought me to the dust,
and I must lay down this body.
Oh! do not you stand out; it will cost you dear if ever you find mercy.`"

Let these things prevail upon some, to be warned by others`' harms:
did she repent upon a deathbed, and obtain mercy?
Do not thou, therefore, presume to go on in sin, because grace has abounded unto her.
God forbid: if thou put it off, thou dost not know but it may be too late.
For thus, indeed, our Lord said, "`Are there not twelve hours in the day?`"
And we read of many called at several hours, as the "`third, fifth, ninth,
and eleventh hour,`" but do not read of any called after the eleventh hour.
It is dangerous standing idle till the last extremity,
lest the long-suffering and forbearance of God should come to an end,
and he should say of thee, as he said of Ephraim of old, who was joined to idols,
"`Let him alone.`"

Therefore, thou who hast not made thy peace with God, turn unto him with all thy heart,
and meet him in the way of repentance; for, as the Psalmist saith, "`The Lord is good,
and ready to forgive, and plenteous in mercy unto all them that call upon him.`"
But if thou choose thy own ways, and say,
"`It is time enough;`" remember what our Lord hath left for a caution to thee,
concerning an evil servant who said in his heart,
"`My Lord delayeth his coming,`" so took liberty,
fell to eating and drinking with the drunken, etc.
"`The Lord of that servant shall come in a day when he looketh not for him,
and in an hour that he is not aware of, and shall cut him asunder,
and appoint him his portion with the hypocrites:
there shall be weeping and gnashing of teeth.`"

To prevent this, let none harden their hearts,
but embrace the offers of grace in the present time,
for the Lord will not always strive with men.
Wherefore the Holy Ghost hath said, "`Today, if you will hear his voice,
harden not your hearts, as in the provocation,
in the day of temptation in the wilderness, when your fathers tempted God.
Wherefore God was grieved with that generation, and said,
They do always err in their hearts: so he sware in his wrath,
they shall not enter into his rest.`"
Read the third and fourth chapters to the Hebrews,
and observe with what fervency that author labours with
them to embrace the present visitation of God`'s love:
for he saith, chap.
iv, ver. 7, that God limiteth a certain day.
Take heed, therefore, lest there be in any an evil heart of unbelief,
in departing from the living God.
"`But,`" said he, "`with whom was God grieved?
Was it not with them that did sin?
To whom sware he, that they should not enter into his rest,
but to them that believed not?`"

Oh! that the youth among us would lay these things to heart,
and embrace the visitation of God to them, that they may not sin against God,
and grieve him; nor, through unbelief,
provoke him to exclude them from that rest which he hath prepared for his people.
Those who are the offspring of believing parents have not those
difficulties to pass through that their parents formerly had,
in respect of making a profession of the blessed truth,
as believed in by the people of God called Quakers.
It is not now as it was in the days of Jael, when the highways were unoccupied,
and the travellers walked in by-ways;
but our fathers have gone before us through the gates,
and "`have prepared the way of the people: they have cast up the highway,
and gathered (in a great measure) the stones out of it,
and lifted up a standard for the people.`"
These privileges have they procured for us, with the hazard of their lives,
like the mighty men of old, who broke through the host of the Philistines,
to fetch water for David out of the well of Bethlehem.

We have great cause to be careful,
having reaped such benefits through their zeal and faithfulness,
not to sit down at ease under the profession of the truth only,
and content ourselves in that, but we must enter into the sheepfold by the Lord Jesus,
who is the Shepherd of the sheep; and himself hath said, "`I am the door; by me,
if any man enter in, he shall be saved.`"
When he putteth forth his own sheep, he goeth before them, and the sheep follow him.
This is the right way to take up a profession of the true religion,
to know the Lord to lead us forth, and in all things to practise from true conviction,
and not from imitation or example only.
It was this door that our fathers, and those who were in Christ before us, entered,
and made a good confession before men, and were not ashamed of the cross of Christ,
nor to bear his reproach, esteeming it greater riches than all the glory of the world.

Neither the frowns nor the flatteries of men could prevail upon them to sell the truth;
no, it had cost them dear, even the loss of all;
and they looked for nothing in this world to recompense them, but the "`Peace of God,
which passeth all understanding,`" and was the legacy our Lord left his disciples.
And in Matt. 19:29,
it is called the "`hundred-fold,`" which our Lord promised they should receive,
who had forsaken anything for his name-sake, besides the inheritance of everlasting life.
This reward was that which those our dear friends had in their prospect,
which made many of them so cheerfully run through such great difficulties,
and when the time came that their end was near, they did sing for joy.

This is also a confirmation to those who are yet behind, that these our friends,
who worshipped God after the way that men call heresy, were accepted of him;
and that the "`anointing`" (or grace of God) which we have received of Christ,
and "`abideth in us, teaching us of all things,
is truth and is no lie,`" or delusion of the devil.
It is that grace of God that bringeth salvation, spoken of in the second of Titus,
which hath appeared to all men,
and hath "`taught them to deny ungodliness and worldly lusts, to live soberly,
righteously and godly in this present world;
looking for the blessed hope and glorious appearing of the great God,
and our Saviour Jesus Christ, who gave himself for us,
that he might redeem us from all iniquity, and purify to himself a peculiar people,
zealous of good works.`"

These, I say, are a cloud of witnesses to the sufficiency of this holy anointing,
and grace of God (which brings salvation to them who follow the teachings thereof),
not only in their holy living, but patient sufferings, and joyful deaths.
It has been a great strength and confirmation to me, to continue in the way of truth,
as professed by the people called Quakers,
to observe the hope that the righteous have in their latter end,
both from what I have been an eye and ear witness of,
as well as from the credible accounts I have seen
of the peaceable and happy end of those,
against whom the hatred of our adversaries hath been mostly bent,
and against whom they have spoken all manner of evil.
I have observed, that the Lord upheld them in their service, through all opposition,
and stood by them to the end; as one of them declared, viz., Edward Burrough,
even at the point of death, that the presence of the Lord was with him,
and his life he felt to justify him: so that I have desired to follow their faith,
"`considering`" (as the apostle saith) "`the end of their
conversation`" which was peace with God through Jesus Christ;
and that the Lord owned them, even to the last,
though they were hated and persecuted of men.
The experience of the prophet was their experience, who said,
"`For the Lord God will help me, therefore shall not I be confounded:
therefore have I set my face as a flint, and I shall not be ashamed;
he is near that justifieth me, who will contend with me?`"
And the Apostle saith, "`Who shall lay anything to the charge of God`'s elect?
It is God that justifieth.`"
And if this light, spirit, grace, and anointing, be sufficient to lead some,
it is able to lead all men, if they will follow the teachings thereof, into all truth.

The blessed hope of life and immortality, which is brought to light through the gospel,
hath been the consolation of the children of God.
For if their hope in Christ had been in this life only, they had been the most miserable,
considering the many tribulations and persecutions that they have met with in this world.
But we look for a better resurrection, when the hour shall come, "`in the which,
all that are in their graves shall hear his voice, and shall come forth;
they that have done good, unto the resurrection of life; and they that have done evil,
unto the resurrection of damnation.`"
For we believe, that the dead shall be raised incorruptible, and we shall be changed:
"`So when this corruptible shall have put on incorruption,
and this mortal shall have put on immortality,
then shall be brought to pass the saying that is written,
Death is swallowed up in victory.`"
But we are cautious,
and desire not to pry into those secret things which God hath seen meet,
in his divine Wisdom, to reserve unto himself,
remembering the reproof of the apostle to some in his day, who were questioning,
"`How are the dead raised, and with what bodies do they come?`"
Leaving it to the All-wise God to give us a body as it pleaseth him; since we are told,
that "`God will change our vile or low body,
that it may be fashioned like unto Christ`'s glorious body,
according to the working whereby he was able, even to subdue all things unto himself.`"

The design of the publication of this collection is,
that godliness and righteousness may increase and prevail amongst men,
that they may have "`Fruit unto holiness, that their end may be everlasting life.`"
Having in the course of my reading, met with many excellent sayings of our dying friends,
that afforded me much satisfaction of mind, as aforesaid,
I have collected some of them together for the benefit of others; knowing,
that usually the words of dying persons make deeper impression on the minds of men,
than words spoken at other times.
I have contented myself, for the most part, with what I have by me,
except the sayings of two or three,
which I have inserted at the desire of their relations;
for if I had collected all that I know of this kind, it would make a large volume:
but here are witnesses enough to establish the truth, for I intend brevity.

Some account I was obliged to give,
concerning some of our dear friends`' sufferings and labours in the gospel,
the better to let the reader understand the weight, and indeed meaning,
of some of their expressions, not with purpose to exalt men, but to exalt the great God,
and his grace in Christ Jesus, by which they were what they were.
The Lord give them that read,
a heart to understand the things which belong to their peace;
and if these shall be a means to stir up any to more faithfulness and diligence,
in making their calling and election sure,
my design is answered and God shall have the praise of all, who is worthy forever.

John Tomkins.

London the 28th of the Eleventh Month, 1701.
