== Chapter 2

[.chapter-synopsis]
* Andrew Taylor
* Elizabeth Cowperthwaite
* William Wilson
* Mary Watson
* Grace Watson
* George Harrison
* Elizabeth Barker
* John Crook
* Sarah Beckwith
* John Burnyeat
* Henry Haydock

ANDREW TAYLOR received truth in the year 1672,
when it pleased God to visit many about the borders of England, in (Cumberland,
by sending his servants to declare the word of life amongst them.
Through his faithfulness and true zeal for the Lord, he came to be wonderfully changed,
and suffered several imprisonments for meeting among the Lord`'s people.
A man diligent in business, faithful and upright among men.
His way was, to be better than he appeared, so that people loved and esteemed him.
After several years, having approved himself just and honest towards men,
God bestowed his heavenly riches upon him,
and called him to the work of the ministry about the year 1679, fitting him for the same;
so that by him many were convinced of the truth and right way of the Lord,
not only in his own country, where he was best known, but in other parts;
for he travelled diligently in many parts of England, and also in Scotland and Ireland.

He was zealous to reprove sin, and careful to preach the gospel freely,
his own endeavours sufficiently supplying his necessities.
At last his body being much spent through his many labours and travels,
a universal weakness or consumption seized him.
Having little pain or sickness, he grew weaker and weaker, and,
being satisfied that his end drew nigh, there continued a travail upon his spirit,
that the Lord God who had been with him,
and borne him up in many deep trials and exercises, would receive him into his rest.
The friends present were witnesses of the hope that he had in his latter end;
and a little before he died, he prayed, saying, "`Come, Lord Jesus, come quickly;
for now I am ready.`"
Being filled with heavenly joy, he departed this life the 3rd day of the Third month,
in the year 1698, in the fifty-fifth year of his age,
and about nineteen years a preacher of the gospel.

[.asterism]
'''

ELIZABETH COWPERTHWAITE, wife of Hugh Cowperthwaite, of Flushing,
in Long Island in America, was convinced of truth about the year 1652,
in the north part of Old England, and continued therein faithful to the end.
She was a woman serviceable to the church of Christ in several respects,
as well by a public testimony to the blessed truth,
which she bore in much plainness and sincerity, delighting in the prosperity of truth,
and of the people of God.
She had true judgment when to speak, and when to be silent;
and divided between the precious and the vile, being tender to the brokenhearted,
but as a sword against that which was evil,
and which tended to division in the church of Christ;
very desirous that the young generation might grow up in the life of truth,
as in the education thereof.

She was at times sick several months before she died,
which she endured with great contentedness, often expressing the love of God to her,
and said that she felt his heavenly presence.
In the time of her sickness she bore many faithful
testimonies to the glory of the worthy name of God,
strengthening and encouraging friends in his work and service,
and against the spirit of separation; for the Lord had sealed it upon her heart,
that that which leads out of the heavenly unity, and brotherly fellowship,
was a false spirit, and not of the Father.
She often said that such could not be heirs with the true seed,
and exhorted those about her against the superfluity of the world;
showing them the ill consequence thereof.
Those friends who came to see her, she exhorted to faithfulness,
saying there is nothing like it.
She continued sensible to the last,
and departed this life on the 15th of the Tenth month, in the year 1697.

[.asterism]
'''

WILLIAM WILSON, of Langdale-chapel, in the county of Westmoreland,
was a man of an innocent life, and though he had little of outward learning,
yet God was pleased to teach him himself, and called him to bear a testimony to his name;
and he did it faithfully, not only in many parts of this nation, but in Germany,
and was several times in Scotland.

He was a man of a lowly and meek spirit, upright and just among his neighbours,
which caused them often to submit their matters in difference to his arbitration,
in which he was careful to find out the truth and ground of things,
and would never countenance deceit.
In this service he had success, seldom missing his desired end, viz., to make peace.
Faithful he was in his testimony for the truth,
and a sufferer for the same in the prison of Kendal, in the year 1666,
and several other times afterwards, as well as by distress on his goods.
Besides that, he suffered cruel mockings, stockings, stoning, blows and wounds,
by cruel usage, both from priests and people; particularly at Eshdale in Cumberland,
where he exhorted the people to mind that of God in their consciences,
and turn to that holy light and law which he had put into their inward parts,
that by the same they might come to know the will of God, and do it.

Because of these and such like words, one Parker, a priest,
in cruel rage did beat and wound him, and with one of his crutches broke his head,
and caused the blood to run down his shoulders.
The priest being lame, and not able, as he would, to effect his cruel purpose,
caused his horse to be brought, on which he mounted,
and in the sight of the people broke his staff in three pieces upon William`'s bare head,
which made the people cry out against such merciless work;
but before the said Parker got home he was struck with sickness,
that he never came more to the steeple-house;
and during the time of his sickness he was very loathsome while above the ground,
and so died.

A few weeks after, the said W. Wilson went to the same place at Eshdale;
and for speaking a few words to the people, one Fogo, a priest,
took him by the hair of his head, pulled him to the ground,
and drew him out of the steeple-house; and also in rage and cruelty abused his brother,
Michael Wilson.
But a few months after, this same Fogo, riding over some sands,
accompanied with several people, fell into a quick-sand, and was immediately smothered.

William Wilson left behind him a widow and two daughters,
to whom he was a true husband and a tender father,
instructing his children to keep in the fear of the Lord,
and to walk in the way of truth, which he walked in himself, often saying to them,
it would be the best portion that they could enjoy.
His sickness was short.
Being lately come off a long journey, wherein his body was much spent and weak, he said,
"`I have not served the Lord unfruitfully.
I have no trouble upon me, and I am very sensible that all is well with me.`"
Again he said he was content whatsoever way the Lord pleased: he was as a dove, harmless;
and as a lamb, innocent.
A few hours before he died, he walked several times over the room, and said,
as he had often before, "`My peace far exceeds my pain.`"
And standing upon his feet between two friends, he said,
"`Oh that every one would mind the Lord, that they might keep life.`"
Then he sat down, and drew breath no more.

He deceased at his own house, at Langdale-chapelsteel, in Westmoreland,
the 10th of the Fifth month, in the year 1682.

[.asterism]
'''

MARY WATSON, wife of Samuel Watson, of the county of York, was one who,
for the sake of the blessed truth, denied herself,
and was made willing to part with those things which she thought stood in her way,
abhorring all manner of evil; and was a tender, nursing mother; nourishing, exhorting,
and building up the young in the most holy faith.
Though weak in body, she was much given to fasting on religious accounts,
and giving of alms; spending much of her time in private retirement,
frequent in prayer and praising the Lord, delighting in meditations; like Mary,
of whom our Lord said, she had chosen that good part,
which shall not be taken away from her. Luke 10:42.
Whilst she had strength of body to go to public meetings,
she had a word to speak in season, suitable to the states and conditions of many;
and also was instrumental, in the Lord`'s hand,
in keeping things in good order relating to church affairs.

In the time of her weakness of body,
she was sometimes under fears of her great passage from mortality;
but through travail of soul,
in the living faith which she received of Christ the author of it,
she was kept steadfast, and obtained victory,
which God in his own time manifested to her soul.
And afterwards she made acknowledgments of the same to the refreshment of others.
Several weeks before her decease, she gave an account,
that the work of her redemption was wrought and completed,
and all her doubts and fears were removed; and now she waited to be dissolved,
and to be with Christ who redeemed and sanctified her; so that, as a wise virgin,
she was prepared to enter into eternal joy.
She was filled with praises while she had any strength remaining;
and her eye was to that heavenly family, out of all the families of the earth,
where she gladly desired to be rejoicing with her dear children and relations gone before,
as often her expression was.

She had a tender regard to her offspring whom she left behind, that they might,
through the grace of God, be gathered to Christ Jesus, the heavenly Shepherd;
with many heavenly prayers for them.
Her exhortation to them who were with her, and also for those absent, on her dying bed,
was that they might walk humbly before the Lord their Creator,
and watch against all the evil temptations of this world; the flesh,
and the vanity and lusts thereof; that so they might not be captivated with pride,
vain-glory, or intemperance; but, abiding in the holy fear of God,
all evil would be suppressed and slain upon the cross; and humility, righteousness,
meekness of spirit, and holiness, should grow up in them,
and be not only to them as a comely garment, but as a never-failing portion.

At last, all visible helps and outward enjoyments failing,
she had the Lord for her portion,
and kept in possession of that heavenly treasure in her soul,
and fed upon that living bread and wine of the kingdom,
of which she is now in the more full enjoyment.
She spoke often of her being surrounded with the glory of the Lamb,
and was sensible in her expressions to the last few hours; and said to her husband,
"`Love, pray for me.`"
So gave up the ghost, in a sweet, still manner, on the 2nd day of the Ninth month,
in the year 1694.

[.asterism]
'''

GRACE WATSON, daughter of Samuel Watson, of the county of York,
was well inclined from her infancy, being subject to her parents, and hating a lie;
and in the latter part of her time was much given to retiredness and reading.
In the time of her sickness she had more than ordinary concern
in a travail of spirit and combating with the enemy of her soul;
in which exercise she kept close to the power of an endless life inwardly;
but made no great appearance until the Lord had given her victory over the enemy,
and delivered her from his secret temptations.
Having passed through the ministration of judgment, her enemy,
the crooked serpent (as she expressed herself), was driven far from her dwelling,
so that nothing hindered her refreshments; and the well springing up, her joy was great;
and through her experience she sung the song of Moses, and the song of the Lamb,
in a spiritual triumph, with humiliation and brokenness of spirit.

She spoke seasonably and distinctly concerning the wiles of the devil, who, she said,
had laid his snares in trades, dealings, and conversation in the world,
and also in families.
Though, according to common prudence,
one would have advised her to silence (her weakness of body considered),
yet she was so full, and had such constraint upon her,
that words flowed from her a long time, in great sweetness and heavenly refreshment;
insomuch that those with her were humbled before the Lord, in the sense of his presence,
which caused many tears.

As any came into her chamber, whether her friends (called Quakers) or others,
she had a suitable testimony, as if she had felt no weakness of body;
so that much was spoken which was not taken down.
Some of that which was taken, is as followeth: "`Oh,
heavenly Father! what hast thou done for me this night?
How hast thou removed the crooked serpent! and not only removed him,
but taken him quite away; so that I can truly say, oh, heavenly Father! thy will be done!
Thou hast shone in upon me with thy marvellous light;
thou hast showed me the glory of thy house,
the most glorious place that ever my eyes beheld:
neither did I think thou hadst such a place for any, much less for me, a poor worm,
a pelican, once ready to think myself destitute.`"
Again she said, "`But now hath the Lord taken me up; he hath removed the crooked serpent;
so that I can say, I defy him, I defy him.`"
And further said to the Lord, "`If thou requirest my life this night of me,
I freely give it unto thee.
Oh, heavenly Father, thy will be done; and if thou hast farther work for me,
keep me in that which I now enjoy,
for there will my greatest care be;`" meaning to be kept therein.

She said, "`Thou hast made my cup to run over, over, over.
O heavenly Father, thou hast taken away all my pain.
I am as if I ailed nothing, though of myself I could do nothing;
scarcely move one of my fingers, my tongue being ready to cleave to the roof of my mouth;
but thou hast been a light to my feet, and a lantern to my path.
How can I cease praising thee, thou God of power! thou art more to me than corn,
wine and oil.
Thy love is sweeter to my taste than the honey, or the honey-comb.
Oh! it is more to be valued than the costly pearls, and the rich rubies.
The gold of Ophir is not to be compared unto it, O blessed, O praised,
O magnified be thou forever!`"

When she was asked how she did, her reply was, "`I am but weak of body,
but strong in the Lord, and in the power of his might.`"
Once she was questioning something, but she checked herself.
"`Why do I so?
my case is no doubting one;
the Lord hath created a clean heart and renewed a right spirit within me,
so that all fears and doubts are taken away.
"`For,`" she added, "`the gates are open,
and the angels are ready to receive me into the bosom of my heavenly Father,
where I shall sing praises with his redeemed ones.`"
It was not perceived, in all the time of her sickness, that she desired to live;
but many times she said as above, "`If thou requirest my life this night,
it is freely given to thee.
Oh!
Lord, do with me what thou pleasest.
Oh! heavenly Father, thy will be done.
What hast thou done for me, a poor stripling, in comparison of many?
Thou hast made my bed, thou hast taken away my pain, and my sickness is gone.`"
And so lay all that day, with many other times, in this frame of spirit.

She said, "`The Lord has a people in this city, and other parts,
that he will take to himself, and crown with glory and honor.`"
She exhorted those present to prize their time,
and not to give themselves too much to the things of this world.
"`How many,`" said she, "`have laid up great riches, earthly treasure,
and in one night have been deprived of all!`"
Her sister weeping by her, she said, "`Weep not; remember David and be comforted.
The tongues of men and angels cannot declare the wonderful greatness of God.
O heavenly Father, how sensible of thee hast thou made me!
Thou hast strengthened me, otherwise I should not have been able to speak so much of thee.
With thee is fulness of joy, and at thy right hand are rivers of pleasure forevermore.`"

She spoke of the parable of the ten virgins,`" Oh! therefore,`" said she,
"`keep upon your watch-tower, that whether he comes at midnight, or cock-crow,
or dawning of the day, +++[+++you may]
be ready; for that is the wedding-chamber indeed, and he is the heavenly bridegroom.`"
Speaking of her parents and relations,
she said they were as near to her as the flesh to the bone;
and taking her sister by the hand, she said to her, "`Though we be separated outwardly,
we shall meet in the kingdom of glory.
O! what cause have I to bless the Lord on their behalf,
whom I am sure never countenanced any evil in any of us, but reproved it.
The words of my dear and tender mother I do remember, since I was but ten years of age,
who said, she had fought the good fight of faith,
and the crown of glory was laid up for her.
These words having remained upon my mind, and taken deep impression upon me,
I can now say, I finish my course with joy, and shall receive the crown of glory.`"
She farther said, that the Lord was a God at hand in six troubles, and in seven; "`nay,
if thou bringest me to the eighth,
thou wilt never leave me:`" such was her confidence in the Lord.
She departed this life in London, the 20th of the Sixth month, in the year 1688,
aged nineteen years and nine months.

[.asterism]
'''

GEORGE HARRISON, of the parish of Killington, in the county of Westmoreland,
came of a family of note in the world,
and underwent some hardships from his relations upon the account of truth,
which he received in the year 1652,
and soon after travelled in the service of the gospel in many counties of England,
through great afflictions, sufferings, and persecution,
from those who were high in profession of religion in that day.
He was an able minister of Jesus Christ, and valiant for the Lord.
When he came into a meeting of professors,
he would challenge of them the order of the true church, according to 1 Cor. 14:30,
which is, "`If any thing be revealed to another that sitteth by,
let the first hold his peace.`"

In the latter part of his time he went southward, and came to Edmundsbury, in Suffolk,
and declared truth through the streets of that town.
Afterwards he went to an inn there, desiring some refreshment for his money,
but they would not entertain him.
So he went to Bradfield-manger, and put up his horse at an inn,
and called for something to eat and drink;
but they perceiving by his language that he was a Quaker, refused also to entertain him,
and led his horse out of the stable; for which cruelty he meekly returned to them,
in the words of Christ, Matt. 25:43, viz., "`I was a stranger,
and ye took me not in.`"

This innocent young man was obliged to ride abroad all night;
and it being a very wet season, and he having been tenderly brought up,
took a great cold.
He went to Haveril, a town between Suffolk and Essex,
where the people grievously beat him for his testimony to the truth; which hardship,
with the great cold that he had received by being forced abroad all night without food,
greatly injured his health, and put him in a fever.
After this, with difficulty, he got to Coggeshall, in Essex,
and was kindly received by Robert Ludgater;
and afterwards he removed to the house of Thomas Creek, of Little Coggeshall,
a mile further.

During his sickness, he felt the love and peace of God to be with him,
and said to the friends about him, "`Come, friends,
rejoice with me:`" and so lay praising God to the last hour.
He died at the house of Thomas Creek aforesaid, aged about twenty-six years,
and was buried in the orchard of Thomas Sparrow, tanner, at Stansted, in Essex,
the latter end of the Fifth month, in the year 1656.

[.asterism]
'''

ELIZABETH BARKER, wife of John Barker, merchant in Tower street, London, being sick,
a Friend went to visit her; and when she understood that he was below,
she caused those present to withdraw, and sent for him up.
He asking her how she did, she wept, and said, "`I am a poor weak woman;
and I have prayed to the Lord that if I am to die of this sickness,
he would let me know it; and I do not see it yet, though I am weak enough to expect it.`"
She expressed much concern for her three children, if she should be taken away.
The Friend answered, it was true that children are very near to tender parents,
but we ought to be resigned, and commit them to God who gave them to us; and besides,
if she should die, their grandfather and grandmother Barker were not only able,
but willing to take care of them.

Upon which she seemed somewhat satisfied: after a space of silence she said,
"`It is assurance of my peace with God that I do earnestly desire.`"
And further, "`For these two years past God has been at work in my heart,
and I endeavoured to answer his will, and have denied myself of some things;
but I l`'ve had a care not to do it in imitation of others,
but from a conviction in my own conscience.
I hope, if I live, I shall be faithful to God,
and keep those covenants that I have made with God.`"
Afterwards she said, "`Oh the presence of God! it is that which my soul desires to enjoy.
God has been good to me many times; for when I have been alone at home,
as well as in meetings, the Lord has broken in upon my heart.
When I have been troubled and exercised in my mind,
I have gone in secret and prayed to the Lord, and I know he has heard me,
and several times answered my prayer, not only for myself, but for my children also.`"

She particularly mentioned one time,
when one of her children was in appearance near to death;
"`I bowed my soul before the Lord, with earnest cries to him for my child;
and the child fell into a sleep, and awakened much better,
even before she took any medicines.`"
After some pause, she asked the Friend who was with her,
what his thoughts were concerning her recovery; to which he replied,
he had little to say to that; and desired her to keep her mind stayed upon the Lord,
whom she acknowledged had mercifully visited her,
and she would find him still to extend his mercy and favour to her,
with his good presence, which was the most comfortable support upon a sick-bed.

She replied, "`God has been with me in this sickness,
but I want more of his presence:`" and added, "`In the first of my sickness, and before,
at times, I used to be terrified with the thoughts of death; but now it is not so.
I am not afraid of death; that fear is taken away.
Yesterday they thought I was dying, and they were in a great hurry about me;
but I was not so in myself, for I felt great sweetness and stillness upon my mind.`"
Afterwards she said, "`I do not find that the Lord doth lay any thing to my charge.`"
Speaking concerning her child, she said, "`When I was last year in Yorkshire,
God did many times visit my soul, and I had large enjoyments of him;
and one time praying to him, I fervently asked the Lord to give me a son;
and now God has answered me in this request;
my desire is (which she spoke with much concern) that, when he is grown up,
he may be a preacher of righteousness.`"
She spoke upon several things, which are omitted, for she had a clear understanding,
and was in a right mind and frame of spirit.

Another time the same person visiting her, she desired all in the room might be still,
and she waited in much retiredness of mind, secretly breathing to the Lord in her heart;
and the Friend prayed by her, with whom she heartily joined.
Upon his leaving her, she said, "`This has been a good time.
I have many visitors, but too few of this kind.
I have felt the Lord`'s presence, but he will be quickly gone again.
I have not so much of these sweet enjoyments as I desire.`"
After some more that passed,
he asked her if she desired to speak with any particular Friend in the city,
and he would acquaint them with it; she answered,`" I have not; I am easy in my mind.`"

About three days before her departure, when it was thought she was dying,
the same Friend being sent for, she told him that she was willing to die,
if it was the will of God;
and gave him an account of the concern that she had upon
her mind for a relation who came lately to visit her,
whose sister had married one that was not called a Quaker.
Said she, "`I entreated her not to do the like; also I prayed her mother,
that she would not suffer it to be; and I desired her not to forsake the truth,
and God would never forsake her; and they both wept; and when she comes again,
I will endeavour to make her promise me not to marry one that is not a Friend.`"
The person replied,
"`But then she must also keep her promise;`" to which she earnestly answered,
"`Ah! so she must.`"
The rest that she said at that time is omitted; only,
that she had a great desire to speak to the other sister who is married;
but she said she was in the country.

Her father and mother coming to visit her, found her in a heavenly frame of mind;
and she said, "`O mother, thou knowest that I have been afraid of death,
and how I have loved vain and foolish things;
but I have prayed to the Lord to forgive me all my sins.
And now, instead of that fear of death, there is much sweetness upon my soul;
and all those vain things I once loved, I now loathe;
and all the world is nothing to me:`" with much more,
expressing her satisfaction and peace of conscience.
She spoke of the exceeding joy and comfort that she felt,
and how sweet the presence of God was to her soul;
and she made heavenly melody to God in her heart,
which tenderly affected the minds of those present.

Her sickness increasing, she grew weaker; and though sometime before,
she did not see that she should die,
yet afterwards was satisfied concerning her departure; and, in order thereunto,
bequeathed several things to her relations and children,
and gave directions concerning the ordering of her children and family,
and also where she would be buried.
She received assurance of her future happiness; for, a few hours before her decease,
the said Friend before mentioned, coming to visit her, found her very much spent,
and her kindred and relations mourning about her; and he prayed,
desiring that all might submit their wills to the will of God,
who giveth and taketh away as he pleaseth.

A considerable time after he was gone, lying very still, she said, "`The voice said,
'`Submit, submit;`' and I say, I have submitted,
I have submitted;`" or to the same effect.
When these words were spoken, a relation present said,
"`Thou art going to leave us;`" she replied, "`I shall be happy.`"
She also, in the time of her sickness,
saw a vision of the difficulty of her passage out of this world,
and of the felicity of the place she at last was to arrive at.
She peaceably ended her days the 6th of the Third month, in the year 1701,
aged twenty-eight years.

[.asterism]
'''

JOHN CROOK was born in the year 1617, and received the blessed truth,
as testified of by the people called Quakers,
at its first being preached in Bedfordshire, which was about the year 1654.
He was a man of note in that county, having been a justice of the peace;
and the Lord by his spirit made him an able minister of the gospel of Jesus Christ.
He had great discoveries in the mysteries of the gospel, was sound in doctrine,
and a skilful archer, hitting the mark.

In former years, when he was out of prison, he labored much in publishing the gospel,
and many were the seals of his ministry.
As he had received a part of the ministry,
so also he had a share of sufferings for his faithful testimony,
being imprisoned in divers places, as at London, Huntingdon, Aylesbury, and Ipswich;
and as he sealed to the truth by sufferings,
so he was careful to adorn the same by conversation,
and had regard to the power of godliness in life and doctrine, above dead forms,
and to the spirit above the letter, yet highly esteemed the Holy Scriptures,
with respect to the sacred doctrine thereof, being well read therein,
and devoted for the faith and practice thereof, as the Lord gave him understanding.
He was eloquent, allegorical, and mysterious, many times in his ministry;
but did not thereby deny or invalidate the history of Christ, etc.,
as recorded in the Holy Scriptures.

The mystery of Christ in spirit, and as revealed and formed in true believers,
and their sincere conformity to him in spirit and conversation, he greatly esteemed;
desiring the professors of Christianity might come
into the true sense and experience thereof,
by a true, living and feeling faith in Christ, and sincere obedience to him.

He spent his former years mostly in and about Bedfordshire and the counties adjacent,
and his latter years in Hertfordshire,
being often disabled from travelling far by reason of several infirmities of body,
so that he would say (with Israel), "`I have been afflicted from my youth,`" Psalm cxxix.
Under the sorrow and grief that he had with some of his children, he would sometimes,
in a tender frame of spirit, comfort himself in the words of David, viz.,
"`Although my house be not so with God, he hath made with me an everlasting covenant,
ordered in all things, and sure,`" 2 Sam. 23:5; and said,
that the Lord did remember the kindness of his youth.

His patience under his bodily infirmities was very remarkable,
and as a good Christian he made the best use of them,
saying that the furnace of affliction was of good
use to purge away the dross and earthy part in us;
and that, did he not feel and witness an inward power from the Lord to support him,
he could not subsist under his pains, they were so great,
which continued with him to his end;
yet he was not remembered to have uttered an unsavoury word, or impatiently to cry out;
and when the extremity of his fits was over,
he would express his inward joy and peace that he had with the Lord.

He would many times say, that many of our ancient friends were gone to their long home,
and we are making haste after them; "`Thus,`" said he, "`they step away before me,
and leave me behind, and I that would go, cannot.
Well, it will be my turn soon;`" in which he seemed to rejoice.

He finished his course the 26th day of the Second month, in the year 1699,
in the eighty-second year of his age, and was buried at Friends`' burial-ground,
at Sewel, in Bedfordshire.

[.asterism]
'''

SARAH BECKWITH, daughter of Marmaduke Beckwith, of Audborough, near Masham in Yorkshire,
was from a child sober and grave in her deportment,
not addicted to light and needless words,
but behaved herself as one who was watchful lest she should offend the Lord,
or be an evil example to others.
She was obedient to her parents, and tenderly affectionate to others,
one sincerely devoted to serve the Lord,
and seek his kingdom and the righteousness thereof.
She loved retirement, and when her business was over,
would walk alone in the fields and other places, where she sought the Lord,
and would sing praises to him, when she thought nobody saw or heard her.

In her sickness she was much troubled with shortness of breath,
and often prayed to the Lord, to enable her to praise him whilst she lived.
About five days before her decease, having some ease,
she desired to be raised up in her bed,
and spoke largely of the tender dealings of God with her,
desiring those who were young to prize their time,
not knowing how few their days might be; "`For,`" said she,
"`many are the temptations of the enemy, especially to youth, presenting length of days,
and persuading them that it is soon enough to trouble themselves with such a concern,
for so he would have persuaded me; and many ways was I tempted,
which caused such exercises that I was brought nigh to despair.
I sought the Lord night and day.
No ear heard me but the Lord alone, who heard my call,
and afterwards gave me some comfortable assurance of my salvation:
but the enemy hath been very busy, and has sorely hurried me,
since I began with this illness.`"

Afterwards she prayed, "`Lord,
give me full assurance of my salvation before I depart hence!
O Lord, let not my distemper overcome my senses, till I come to a full enjoyment!
I pray thee, let not my desires cease, till thou answerest the desires of my heart;
and let nothing quench thy love.`"
And the Lord answered her cries, and caused her cup to overflow,
so that she sung heavenly praises to the God of her salvation.
She also gave tender advice to her sisters,
and desired them to love and fear the Lord above all, and keep in the truth; saying,
"`Oh! press after it, to feel the working of it in your own hearts;
and when you are in it, keep in it, and under the government of it.
Heed not to deck yourselves, but be meek and low.
None ought to pride themselves in any endowment, either beauty, or any other thing;
because it is not theirs, but the Lord`'s who gave it them,
and can take it away when he pleaseth;`" saying, "`What is all now to me?`"

She also spoke of the condition of some who were grown careless,
and were got into liberty; "`Such,`" said she,
"`are ill examples to those that are coming up.`"
She said there were many who professed truth that knew little what truth is.
"`It does not consist only in coming to meetings, and wearing plain apparel and the like,
unless they come to feel the operation of truth in their own hearts;
for all such outward appearances will stand in no stead,
without the love of God be inwardly felt and enjoyed.
It is an easy thing to come to meetings; and some are ready to think, that doing so,
and behaving themselves soberly, is sufficient; but the Lord seeth at all times,
and he will have no such mockery.
I bless God, I have not been guilty of seeming what I was not.`"

Her love was great to faithful friends, and she much desired their company,
and wonderfully prized the love and mercies of God, saying, "`It is not for my deserts,
for I had nothing to engage the Lord with, but it is his free love to me.`"
She said there was man`'s righteousness, and the righteousness of God;
but man`'s righteousness must be rent off,
and man covered with the righteousness of Christ Jesus, who said,
"`I lead in the way of righteousness, in the midst of the paths of judgment,
that I may cause those that love me to inherit substance.`"`'

Speaking of the way of truth, she said, it was a strait and narrow way,
and not to be kept in without a daily watch; and further said,
"`But although a strait way, yet it is a pleasant path, and delightsome.
Oh! here is peace in abundance.
It is so sweet, I could delight always to enjoy it, and to live therein;
gold is not worthy to be compared to it.`"
She thus continued, being taken up with heavenly thoughts, saying, "`Lord,
give me fully to drink of the well of water that is within the gate,
for thou hast raised my heart, and I am overcome with thy love.
O! I long, I long!
O! Lord, open thou the windows of heaven, and pour of thy blessings into my soul,
until there be not room to receive, that I may bless and praise thy name.`"

Her end drawing nearer, she prayed the Lord to give her an easy passage;
and taking her leave of her sister Hannah, she said if she was worse,
some should call her.
Taking her by the hand, she said, "`Dear sister, thou hast been near and dear to me,
and careful of me: the Lord requite thee,
and be near to thee when thou comest to lie on thy dying bed.`"
Near morning, her distemper growing upon her, she said, "`I am as sensible as any of you,
and I am well content to die.
I have no doubt of my salvation:`" with many more good expressions,
which could not be perfectly understood, her voice being low;
but she was sensible to the last,
saying within a very little time of drawing her last breath, "`Lord,
take me away;`" and presently after, she gently and comfortably passed out of this world,
to live forever in a world which hath no end.
She departed this life the 24th of the Ninth month, in the year 1691.

[.asterism]
'''

JOHN BURNYEAT was born in the parish of Lowes-water, in the county of Cumberland,
about the year 1631; and when it pleased God to send his faithful servant George Fox,
with other of the messengers of the gospel of peace and salvation,
to proclaim the day of the Lord in the county of Cumberland, and north parts of England,
this dear servant of Christ was one that received their testimony,
which was in the year 1653, when he was about twenty-two years of age.

Through his waiting in the light of Christ Jesus, unto which he was turned,
he was brought into deep judgment, and great tribulation of soul,
such as he had not known in all his profession of religion,
and by this light of Christ were manifested all the reprovable things;
and so he came to see the body of death, and power of sin which had reigned in him,
and felt the guilt thereof upon his conscience,
so that he did possess the sins of his youth.
"`Then,`" said he, "`I saw that I had need of a Saviour to save from sin,
as well as the blood of a sacrificed Christ to blot out sin,
and faith in his name for the remission of sins;
and so being given up to bear the indignation of the Lord because of sin,
to wait till the indignation should be over,
and the Lord in mercy would blot out the guilt that remained,
which was the cause of wrath, and sprinkle my heart from an evil conscience,
and wash our bodies with pure water,
that we might draw near to him with a true heart in the full assurance of faith,
as the Christians of old did.`" Heb. 10:22.

Thus did this servant of the Lord, with many more in the beginning,
receive the truth (as more at large may be seen in
the journal of his life,) in much fear and trembling,
meeting often together, and seeking the Lord night and day,
until the promises of the Lord came to be fulfilled, spoken of by the prophet Isaiah,
chap.
xlii.
7, xlix.
9, and lxi.
3+++.+++ Some taste of the oil of joy came to be witnessed,
and a heavenly gladness extended into the hearts of many,
who in the joy of their souls broke forth in praises to the Lord,
so that the tongue of the dumb, which Christ the healer of our infirmities unloosed,
began to speak, and utter the wonderful things of God.
Great were the dread and glory of that power,
which in one meeting after another were graciously and richly manifested amongst them,
to the breaking and melting many hearts before the Lord.
Thus, being taught of the Lord, according to Isa. 54:13, John 6:45,
they became able ministers of the gospel,
and instructors of the ignorant in the way of truth.

After four years waiting, mostly in silence, he appeared in a public testimony,
which was in the year 1657,
being at first concerned to go to divers public places of worship,
reproving both priests and people for their deadness and formality of worship,
for which he endured sore beating with their staves and bibles, etc.,
and imprisonment also in Carlisle jail,
where he suffered twenty-three weeks`' imprisonment
for speaking to one priest Denton at Brigham.
After he was at liberty he went into Scotland in the year 1658,
where he spent three months, travelling both north and west.
His work was to call people to repentance,
from their lifeless hypocritical profession and dead formalities,
and to turn to the true light of Christ Jesus in their hearts,
that therein they might come to know the power of God, and the remission of sins.

In the year 1659 he went into Ireland,
and preached the truth and true faith of Jesus in many parts of that nation.
About the Seventh month following, meeting with Robert Lodge,
a minister concerned in the same work, he joined with him,
and they laboured together in that nation for about twelve months,
in the work of the gospel, and returned to Cumberland in the Seventh month, 1660.
In the year 1662 he travelled to London, where he met with George Fox,
Richard Hubberthorne, and Edward Burrough; and in his returning home through Yorkshire,
at Rippon he was committed to prison, and kept fourteen weeks,
for visiting the friends who were prisoners there.

After he was discharged of that imprisonment he returned home, where he abode,
except at times visiting friends in adjacent counties,
till the beginning of summer in 1664, when he took shipping again for Ireland,
and visited most of the meetings in that nation.
From thence he embarked for Barbados, in order to perform his journey into America,
which had lain before him for four years; and from Galway he arrived at Barbados,
after a passage of seven weeks, and stayed three or four months there,
and had great service, and much exercise also,
occasioned by the imaginations of John Perrot,
and that fleshly liberty he had led many into, not only there,
but in Virginia and other places.

From Barbados he went to Maryland about the Second month, 1665,
and afterwards to Virginia, labouring in the work of the gospel.
In the Fourth month, 1666, he came to New York, so to Rhode Island, New England,
and Long Island, till the Second month, 1667, at which time he went again to Barbados,
and spent that summer there.
In the Seventh month of the same year he sailed from thence,
and arrived at Milford-Haven, in Wales, and laboured much in the gospel in this nation,
from the time of his arrival from America, till the latter end of the year 1669,
when he went over and spent that winter among friends in Ireland,
and returned to London in the year 1670.

In the Fifth month, 1670, he embarked for Barbados again,
in company with William Simpson, who died in peace with the Lord in that island.
From thence he went to New York, Long Island, Rhode Island, and New England,
and afterwards to Virginia and Maryland, where he met George Fox and several brethren,
just come from Jamaica.
Having spent much time and labour up and down in America,
till the 25th of the Second month, 1673, they came from the Capes of Virginia,
and arrived at Galway in Ireland, the 24th of the Third month,
and from thence they came to the yearly meeting at London, in 1674.

From that time he continued in this nation, labouring among the churches,
until the Eighth month, 1681, when he went to Ireland again,
and tarried there till the Sixth month, 1684, and then he came into Cumberland,
and so to Scotland, and into the north parts of England again,
visiting the meetings of Friends, and so returned to Ireland the 25th of the First month,
1685, where he tarried till he departed this life.

In the latter part of his life he took a wife in Ireland, and had by her one son.
After the death of his wife, he had some intentions to go for England,
about the year 1688; but seeing the troubles and wars in Ireland coming on,
and that many afflictions would attend Friends in that nation,
and people being possessed with fears fled for England; our dear friend,
though he had opportunity, had no freedom to go,
but gave himself up to stay with Friends there,
and bear a part of the sufferings that might attend them.
In this time he was a precious instrument in the Lord`'s hand,
able and skilful in the ministry, for the comforting of his people;
for he was a cheerful encourager of them, a dear friend and true brother;
a diligent overseer and tender father; a perfect and upright man in his day.

Having been at a province-meeting at Rosenallis,
where he bore a living testimony to the comfort of friends,
he went from thence to Mountrath and Ballinakill,
and so to a monthly meeting at New Garden; after which he came home with John Watson,
and feeling himself not well, took his bed, and was visited with a fever,
and continued sick twelve days; in all which time he was preserved in his senses,
and in a sweet frame of spirit.
He often said he was finely at ease, and quiet in his spirit,
and the Lord did attend him with his heavenly power and presence, to his comfort,
and the satisfaction of those about him.
He said that he ever loved the Lord, and the Lord loved him from his youth.

He peaceably departed this life on the 11th day of the Seventh month, in the year 1690,
and was decently buried at New Garden, the 14th of the same.
Convinced at the age of twenty-two; a labourer in the gospel thirty-three;
aged fifty-nine years.

[.asterism]
'''

HENRY HAYDOCK, of Warrington, in the county of Lancaster,
was a faithful man in life and conversation, and walked as becometh the blessed truth,
of which he made profession When he was upon his dying-bed,
and in outward appearance nigh gone, the Lord, who is the God of the living,
raised him up by his divine power, to the admiration of those present,
to bear a living testimony for him, which was in this wise, viz. "`Friends,
I was never a public preacher in all my life; but now, by the power of God,
I am one at my death.
Glory be to God forevermore, who hath the life and breath of all men in his hand,
and can lengthen at his pleasure; who knows how to dispose of us.

Therefore, friends, be you all faithful to the Lord,
for great things will the Lord bring to pass for his people,
who are true in their hearts to him.
Such as serve God faithfully, they shall have a living reward from him,
and their rest shall be with the Lord Jesus Christ;
which rest my soul is already entered into,
and is set down with God in the Paradise of his pleasure,
taking its repose with God the Father, and our Lord Jesus Christ,
and all the holy men of God since the foundation of the world.
And though my body go down to the earth,
yet my soul and spirit shall have its residence with the living God in heaven,
where they who are unfaithful to the Lord cannot come.
I was well nigh my last breath, but the Lord loosed my tongue,
that I might declare of his goodness.`"

Again he said, "`The Lord in my healthful days did put his living word in my heart,
and though I have been by some looked upon as a stripling,
and as one that knew not much of the things of God,
yet my soul hath had many sweet seasons and opportunities.`"
Again he said, "`I have a very good wife, faithful and loving to me,
and three sweet children; call them, that I may kiss them before I die,
for my time here will not be long.`"
So they brought one of his daughters to him, and he said, "`Thou art Elizabeth,
my youngest daughter,`" and kissed her many times.

He farther said, "`Silver and gold I have not much to leave thee;
thou hast hitherto been a good child; the blessings of the living God rest upon thee,
and the blessing of me, thy dying father, be with thee also.`"
So then he took his son, and said, "`Thou art Roger, my sweet son.
In thee I have taken great delight; yet now thy father is about to take his last breath;
and that which I desire of the Lord, is, that he will bless thee and thy two sisters,
and bless you all, that you may keep up my name, and live as your father hath done.
Though I have not filled up the number of many years, yet I, thy father,
do witness peace with God.`"
Being pretty much spent, he said, "`The Lord bless thee, my son, and thy two sisters;
the blessing of your father be with you all;`" and so kissed him many times,
and let him go.

Then he called for his daughter Alice, and said, "`Thou art Alice, my first born,
and I love thee well.
It hath been real and true; and though some men can show it more,
yet I love you all well,
and I hope the Lord`'s care will be over you when I am dead and gone;
and I believe you will not want.
Alice, (said he) kiss me,
for thou must never kiss me more:`" so clasping her in his arms, he kissed her,
and bade her farewell.
And then said, "`I have now made an end of what lay upon my mind; therefore, everlasting,
living, pure, invisible God, into thy hand of power I recommend my soul.`"

He lay still and quiet till a little before his departure,
when the very pangs of death seized on him; then were his sighings many,
yet had the savour of life in them.
Afterwards he lay still and very quiet, rejoicing in his spirit, and said,
"`My soul doth magnify the Lord, and my spirit rejoiceth in God my Saviour,
who hath saved me from sin; but what shall I say to the rebellious?
If they will serve the devil, they will have a bad portion in the end.`"
He said, "`Though there may some of all persuasions find salvation, yet that people,
in scorn called Quakers, who are really faithful to God, are satisfied in God,
and they know salvation to their immortal souls, having been redeemed by Jesus Christ,
who is come to save many.`"

He prayed for his brother and sister, saying, "`Lord,
thou knowest I have one brother and sister,
who are not in that faith in which I am about to lay down my head.
Lord, bring them to it, if it be thy blessed will, and confirm them in the same,
that they may receive that blessed reward thou hast made my soul a witness of.`"
And said, "`So my strength now failing, as to my outward man,
I once more recommend my soul into thy hands, Lord Jesus Christ.`"
He departed this life the 5th day of the Fourth month, in the year 1688,
aged about thirty-three years.
