== Chapter 1

[.chapter-synopsis]
* John Bowron
* Hugh Roberts
* Priscilla Cotton
* Andrew Graham
* Thomas Wresle
* William Captain
* Roger Gill
* William Smith
* Margaret Thompson
* William Gibson
* Eleanor Barcroft
* Thomas Gettos
* James Blackhouse
* Mercy Johnson

JOHN BOWRON, was born at Cotherstone in Yorkshire, near Barnard-Castle, in the year 1627,
which was the place of his outward habitation to his death.
He received the truth by the ministry of George Fox and James Nayler,
when they came into those parts; which was about the year 1653.
Soon after he went to Stratford steeple-house, and preached to the priest and people,
and from thence to the cross, and at Barnard-Castle, and at Rumbel steeple-house,
and the people threw snow at him, as he stood upon a stone speaking to them.

Then he went to Bowes, and stood up in the steeple-house yard,
and spake to the people there; and one of the men cried out to the people, "`Hang him,
hang him in the bell-house;`" and some time after, that man hanged himself.
After that he travelled into Allandale, and had a meeting there, and so to Scotland.
At Edinburgh he preached to the people as he went through the streets of that city,
and at the cross, and there were English soldiers who were kind to him;
and he travelled through that nation.
The soldiers were very kind to him, but the priests were in a rage against him,
for he was a dread to them.

About the year 1656 he took another journey to Scotland,
and at Birkwell he took shipping for Barbados, and was kindly received in that island,
and had many good meetings there;
and they would have had him tarry with them as long as he lived.
When his service was over in that island, he took shipping for Surinam,
and travelled upon the coasts of Guiana, a country of South America,
three or four hundred miles.
He went to their sort of worship, which was performed by beating upon hollow trees,
and making a great noise with skins, like a sort of drums;
and he declared the word of the Lord among them by an interpreter.
He travelled +++[+++among the Indian natives in several of their settlements],
and spake to their kings,
who were arrayed with fish-shells hung about their necks and arms;
and they spake to him in their language, and confessed he was a good man,
come from far to preach the white man`'s God.

After he had declared the name of the Lord in this barbarous country,
he returned with his interpreter back to Barbados again, and stayed a little time there,
visiting Friends; and a ship presenting, he embarked for England,
which proved a long perilous voyage of thirteen weeks.
After they had been at sea about six weeks, they met with a violent storm,
which took away their rigging, and their provisions grew scanty,
so that for five weeks they were reduced to a pint of water,
and a biscuit a day each man.
There were about sixty persons on board, and some died;
but at length they arrived at Dover, where he took passage by land for London,
and met with George Fox, and Francis Howgill, to whom he gave an account of his voyage.
This was about the time that Richard Cromwell was made protector of England,
to whom he went with a message from the Lord, and warned him of the day of the Lord.

After John Bowron returned home into Yorkshire, and rested a little time,
he took his journey into Scotland again, and so into Ireland,
travelling through all that nation from sea to sea, and returned back again;
and so continued visiting that nation of Ireland six times in six years.
He was divers times in prison for the testimony of truth; as at Durham jail,
and at Richmond house of correction twenty weeks in a sharp winter;
and for being at a meeting at Croft-bridge, they took from him a horse and two steers,
and imprisoned him again in Durham jail;
afterwards he was released by the bishop of Durham.

He oftentimes travelled to London in company with John Langstaff, and to Bristol,
and the west of England, till of latter years hindered by age and bodily infirmity.
After many journeys, and sore travail and labour, the Lord gave him this blessing,
that he lived to be full of days, and died in peace in the same house where he was born.
About two weeks before his death he rode to the meeting as he used to do,
and bore his testimony among Friends; and two or three days after,
went to the burial of an ancient Friend; and his grandchild waited upon him,
where he spoke at the graveyard a pretty while.

The first-day after, finding his strength decay, he desired his son, Henry Bowron,
to go to the meeting, and acquaint Friends that his days were almost spent,
and he knew not that he should come any more amongst them;
and his son answered his desire, and many Friends came to see him.
Two days after, he arose without help, and came cheerfully forth of his chamber,
desiring his son to trim him, which he did; after, he took his grandchildren by the hand,
saying, "`Stay with me, go not away, for I am taking my journey to a city, New Jerusalem,
that needs not the light of the sun, nor the light of the moon,
for the Lord God and the Lamb is the light thereof.`"

He added,`" Zion is a precious habitation:
he that dwelleth within the gates of Zion shall never want.`"
Again, "`What can be expected?
I have seen many good days.
I have seen the wonders of God both by sea and land.
The sea saw the wonders of God, and fled, and Jordan was driven back.`"
Sometimes he would pray to the Lord, saying, "`Lord bless this nation,
and the city of London, which I dearly love.`"
The night before he died, Thomas Raylton came to visit him, and being told who it was,
he said, "`Thomas, pray with me,`" and he did so,
and the presence of God was felt amongst them, and praises were given to the Lord.

Though he was weak in body, yet strong in the inward man,
and expressed his satisfaction with that opportunity.
After, he said, "`Thomas, what meeting had ye yesterday?`"
meaning the quarterly-meeting; he answered they had a good meeting, of which he was glad;
further he inquired, "`What way art thou going?`"
Thomas told him southward; he said, "`Tell friends of London how I am,
and mind to give my love to them and to George Whitehead;`"
and in great sweetness of spirit,
and peace of soul, he continued till about midnight, sensible to the last.

He died the 5th day of the Eighth month, 1704, aged seventy-seven years;
a minister fifty-one years.

[.asterism]
'''

HUGH ROBERTS, late of Pennsylvania, formerly of Wales,
was a man fitted and qualified by God`'s power to be a serviceable
minister of the gospel to the church of Christ in America,
in which country he lived about eighteen years.
His company was very desirable, being greatly edifying;
he had passed through many trials and exercises,
so could by experience speak a word in season to the travailing and weary soul.

His doctrine in the meetings of God`'s people dropped as dew,
and his speech as small rain upon the tender plants; for in the openings of life,
things both new and old came forth of the treasury of wisdom.
His testimony was comfortable to the hearts of the people, in the sense of God`'s love,
who is the author of all good to his people; a man zealous for good order in the church,
and skilful to accommodate differences when they happened.
He travelled in the work of the gospel in, Maryland, Long Island, Rhode Island,
and New England, where his service was effectual to the people,
and to himself a great satisfaction.

At his return homewards, being weakly of body, having been much spent,
he lay sick at the house of John Rodman in Long Island,
where his friend John Bevan visiting him, he said,
"`Nothing lies in my way as an obstruction to hinder my peace with God.`"
After that he got home to Pennsylvania.
A friend of his taking his farewell of him, said to him,
"`I believe thy deep trials and exercises are nearly at an end,
and that peace and joy everlasting will be thy portion from the Lord for thy faithfulness.`"
In much brokenness of heart, and sense of the presence of God upon his spirit,
he answered the friend after this manner, "`I am satisfied thereof,
and can bless my God for it.`"
He departed this life the 18th of the Sixth month, 1702,
and his body was buried at Merion the 20th of the same.

[.asterism]
'''

PRISCILLA COTTON, formerly wife of Arthur Cotton,
who then dwelt at Plymouth in Devonshire, now of Colchester in Essex,
was one of the first that received Friends in Plymouth; namely,
John Audland and Thomas Arey, in 1654.
She lived an honourable life, and was valiant for truth,
and often bore public testimony to it in steeple-houses, and other places,
against the priests and professors, who walked out of the truth;
and for her testimony she suffered several imprisonments and cruel dealings from them,
and other instruments employed by them.

She travelled in several places, bearing testimony for truth in the living power of God.
She also in her life-time gave forth several good papers, which are printed; and lastly,
the day she died, she left a paper for Friends,
as a testimony of her good will and love to them all; which is as followeth.

The Testimony of Priscilla Cotton, to Friends, the day she died.

All my dear friends, who have found your Redeemer, oh! wait upon him at all times,
that you may stand continually in his presence where life is,
that with the light you receive from him, you may see your thoughts, and deny them,
that in stayedness you may be kept, when the hasty froward spirit would arise,
and keep it down.
With the measure of God`'s spirit all may be weighed, the words to what they tend,
that no lightness may appear in your words, nor unsavouriness, that no offence come,
but edification by all you speak.
Let the elders watch, that at no time the younger may see lightness, laughter,
or words of offence, but that you may always keep down the evil in yourselves,
and may minister grace to all you have to do withal, that God`'s spirit be not grieved.
So keep the field clean, that was once ploughed up and made green and beautiful,
that no stones or hurtful weeds grow in it to oppress the Seed.

Friends, the cross is the power of God; when you flee the cross, you lose the power;
that which pleaseth self, is above the cross, and that which pleaseth man,
is above the cross; and that which shuns the cross, yields to the carnal part,
and loses its dominion.
Though the cross seems foolishness, stand in it; though it seems weak, stand in it;
though it be a stumblingblock to the wise, stand in it; there the dominion, authority,
and crown are received.
This is not for you to be exercised in for a time only, as at your first convincement,
but daily, even to the death, as long as a desire, will or thought remaineth in you,
contrary to God`'s pure light, and judge it by it; and as you wait in the light,
you will come to know a cross in the use of meat, drink, and apparel,
and keep to the cross when alone, or in company;
what the pure mind of God stands against in you, that the cross is against.

So friends, watch daily to keep Christ`'s command,
'`Take up your daily cross;`' be not at liberty one day, but deny thy own will,
thy own thoughts, and thy own self.
Taking up the cross, you feel the power, the strength of the Lord God,
which breaks down all, keeps in order, in safety, and in peace.
This preserves from stubbornness, willfulness, and headiness,
and brings all to be subject, as dear children, unto God,
and subject one unto another as brethren.
In the light and in the cross there are no evil thoughts, no hard speeches,
no contention, no loving preeminence; but as brethren and sisters, pitiful,
tenderhearted, courteous, forgiving, forbearing, long-suffering,
and supporting one another.
Here the power of the cross is known, which brings all to God`'s praise,
and to his honour and glory, and to his children`'s prosperity and peace: so let it be.

Amen.

Priscilla Cotton.

After this, seeing her departure was nigh at hand,
she desired several Friends to be called; being come,
she desired to be lifted up in her bed;
and in a sense of life she spake suitably to every one for some time,
exhorting Friends to peace and unity, and to keep in the cross,
which is the power of God, that all might witness a mortification to sin,
and a renewedness to life,
that the living God and his holy truth might be honoured by all;
and that Friends might keep out of the fashions and customs of the world,
both in words and apparel, every one answering the truth therein.

After this she called for her husband, who was at that time weak; embracing him,
she said, "`My dear husband, the Lord hath largely manifested his love to us,
and large has been our experience thereof, ever since he brought us together to this day.
And now, my dear, the Lord will separate us, but grieve not;
let thy eye and expectation be to him,
and the Lord who hath hitherto helped us will be thy help and support;
in whom let thy trust be forever!`"

In like manner she called for her daughter,
and gave her charge to live in subjection to God`'s truth,
and to forsake what she was convinced to be sin and evil, saying if she feared the Lord,
and walked in his truth, it should be well with her; but if not, thou wilt be miserable.
She also spake to other friends and relations, which for brevity is omitted.
Afterwards she said,
"`Let me lie down that I may die;`" so in great stillness
and quietness she departed this life,
about four hours after she had spoken these words, the 4th day of the Sixth month, 1664.

[.asterism]
'''

ANDREW GRAHAM, of Cumberland, near the borders of Scotland,
was a man of large understanding, a loving temper, and willing to do good unto all,
which increased his esteem with all sorts of people.
When the Lord was pleased to send his servants called
Quakers to preach the gospel in the borders of England,
in Cumberland, he with many hundreds came to hear their testimony,
and did confess unto the truth.
But he was before closely joined in fellowship with a people of good repute in the country,
and it was hard for him to leave them, which occasioned his halting as between two,
some considerable time, until the Lord was pleased to renew his visitation to him,
and by his righteous judgments awakened him to a true sense of his state;
so that he was deprived of peace,
until he gave up to be faithful to what the Lord
by his spirit discovered to him to be his duty.

He joined with the people called Quakers from that time,
and was a good example in conversation among men, in humility, and in self-denial,
and in suffering;
and in about two years time the Lord committed to him a part of the ministry,
and he faithfully laboured in the work of the gospel, in the churches of Christ,
both in some parts of England, and in Scotland.
His service was great in the meeting to which he more peculiarly belonged;
and the more for his innocency, true zeal, and being devoted to the service of the truth,
labouring to bring people to the life and power of godliness.
He was as a nursing father,
or cherisher of those in whose hearts he saw God had begun his work,
as well as he was terrible against ungodliness.

He was suddenly seized with a great sickness, and lay sick but a short time;
in which he said, "`I see they are happy who, when death comes,
have nothing to do but to die;
for the pains of the body at this time are enough to struggle with.`"
As he lived, so he died, ending his days in a travail of spirit,
that Friends might be faithful; and Friends visiting him,
the Lord`'s power and presence was plentifully enjoyed,
to the tendering of the hearts of many.
He finished his course in this life on the 15th of the Eleventh month, 1704.
Aged sixty-two years.

[.asterism]
'''

THOMAS WRESLE, of Winteringham, in the county of Lincoln,
was an early seeker of truth and righteousness;
and for some time had his conversation among the Baptists.
He received the truth in the year 1655, wherein he much improved,
and approved himself a faithful man, loving truth, and the friends thereof,
with all his heart, and serving it and them faithfully to the end of his days.
He was exemplary in his conversation, and helpful to his neighbours;
and having a good understanding, was able to give counsel and advice,
which was esteemed amongst them.
In his sickness he said, "`I have seen where the weary are at rest,
and where the wicked cease from troubling;
and I have received an earnest of that blessed inheritance,
which is laid up in store for all the faithful.`"

A day or two before he died, some of his friends visited him,
which greatly comforted him, as he signified; to whom he said,
"`I have loved truth with all my heart, and all the friends of it, and feel nothing,
but that all is well with me.`"
In and with much fervency, he said,
"`I desire that Friends would keep up their meetings
in the name and power of the Lord Jesus Christ,
and that the Lord may bless and prosper them.`"
He exhorted Friends to keep their ancient zeal, love, and integrity,
which the Lord raised in them in the beginning, saying,
"`That is my great comfort now upon my dying bed;`" and taking his leave of Friends,
said, "`It is life, it is life, Friends, that overcomes death.
Give my dear love to all faithful Friends everywhere;`"
and life and truth was felt to flow among them at that time.

He died the 21st of the Twelfth month, 1704

[.asterism]
'''

WILLIAM CAPTAIN came out of England with his parents into Ireland, after the civil wars;
and was convinced at Mountmellick meeting.
He was bred a scholar, and in his youth intended for a priest.
He was a faithful, patient, and deep sufferer for the testimony of a good conscience,
and often in prison for meeting to worship God, and for tithes;
holding forth a good conversation, as became the gospel.

In the time of his sickness, some Friends being present, he said to them as followeth;
"`The Lord hath appeared to me in a wonderful manner,
when I was ready to sink under great affliction; then did he take me by the hand,
as he did Israel of old, and raised me over mine afflictions.
Whereas I had need of a physician, the Lord was unto me instead of a physician;
and when I had need of patience, he gave me patience; and when I had need of sleep,
he accompanied me with his living presence from time to time;
whereby my soul was sweetly consoled, so that I can say with the Psalmist,
"`It is good for me that I was afflicted;`" and with Simeon,
that "`Mine eyes have seen his salvation;`" and with Job, that "`My Redeemer liveth,
and mine eyes have seen him.`"
See how good the Lord is.
Oh! my soul, praise thou the Lord, let all that is within me praise the Lord.`"
Another time he said, "`The truth which the Quakers profess is the way to salvation,
and there is no other way.`"
He died a prisoner for the testimony to truth, the 30th day of the Ninth month, 1672.

[.asterism]
'''

ROGER GILL, of London, shoe-maker, received the blessed truth,
as professed by the people called Quakers, about the year 1683.
Ile formerly went among those called Baptists,
and I have heard him say that before he received
truth he was guilty of many gross and enormous crimes.
But by the power and virtue of the spirit of God, he came to know his heart changed,
and being washed and sanctified, and the fear of God placed therein,
which preserved him from those vices he had formerly been addicted to,
for which he was very thankful to the Lord.
Some years before he died,
God gave him a dispensation of the gospel of our Lord Jesus Christ to preach,
and he was faithful and diligent in that service, and was an able minister,
having a word in season to speak to the weary soul;
and very zealous he was for the prosperity of the truth.

In the year 1699 he had a concern upon his mind to visit the brethren in America,
and to preach the gospel to the people on that continent.
He went over the sea for that purpose, in company with his friend Thomas Story,
concerned in the same work; where they had not travelled long,
before they heard the people in Philadelphia, in Pennsylvania,
were visited with a malignant distemper, which caused great mortality.
At hearing thereof Roger Gill said he felt a great weight and exercise to come upon him,
so that he had no ease in his spirit till he came amongst them at Philadelphia.
The sickness increasing, he visited the sick, and preached in their public meetings,
saying that when he was one hundred miles off them,
his love in the Lord was such to them, that had he wings he would fly into Philadelphia.

It was the time of their yearly-meeting whilst he was there; where he, with others,
was concerned in public, earnestly to supplicate the Lord for the people;
and particularly Roger Gill fervently and devoutly interceded the Lord to stay his hand,
and if he would please to accept of his life for a sacrifice,
he did freely offer up his life to the Lord for the people.
When meeting was over he often expressed the ease of his mind,
and that it was with him that he had not much to do but visit Friends of Burlington,
in West Jersey, about twenty miles off.

He accomplished that journey;
and at his return to Philadelphia was taken sick with the distemper,
which filled him with great pain and affliction of body,
and he remembered in his sickness the free-will-offering up of himself unto the Lord;
saying to Friends about him,
"`It is not in my heart to repent of the offer I have made.`"
He was cheerful, notwithstanding his great affliction of body;
and exhorted Friends to faithfulness, and said,
"`The Lord hath sanctified my afflictions to me,
and hath made my sickness as a bed of down:`" and
when some did speak of their hope of his recovery,
he said in much love,
"`Truly I have neither thoughts nor hopes about being raised in this life;
but I know I shall rise sooner than many imagine,
and receive a reward according to my works.`"
His sickness continued seven days upon him;
and a few hours before his death he took his leave and said, "`Farewell, farewell,
farewell forever,`" and sweetly passed away out
of this life on the 2nd day of the Eighth month,
1699.
It was observed that the sickness stopped, and very few were buried of it after him.

He left a widow and two sons behind him in England.
He was aged about thirty-four years.

[.asterism]
'''

WILLIAM SMITH, of Elsham, in the county of Lincoln, was an elder in the truth,
having received it in the love of it, and walked faithfully therein to the end,
and was a preacher of righteousness;
in conversation a man of sincerity and godly simplicity,
giving no occasion of offence to Jew or Gentile, neither to the church of Christ,
and much beloved by friends and neighbours.
When on his dying bed, several Friends visiting him,
found him in a heavenly frame of mind.
He being told Friends`' love was to him, he answered, "`I have friends on earth,
and friends in heaven, the Father, Son, and Holy Ghost,
whom I have true fellowship withal, though yet in this earthly tabernacle;
my treasure being in heaven, my heart is there also, where the Father, Son,
and Holy Spirit dwelleth.`"
As he lived, so he died in the Lord, and is blessed, for so saith the spirit,
and he is at rest from his labours.

He departed this life the 17th of the Twelfth month, 1701.
Aged seventy-nine years.

[.asterism]
'''

MARGARET THOMPSON, wife of John Thompson, near Mountmellick, in Ireland,
being upon her deathbed, and a few days before she died, calling her children to her,
said unto them, "`Fear the Lord, and abide in the fear of the Lord.
I do not allow you any thing further, than as you abide in the truth,
and love one another.`"
After that she said, "`The Lord helps me, and I find all temptations taken away.`"
Another time she said, "`They that die in the Lord,
have unity one with another;`" and she confessed the love of God, and said,
"`I will lean upon my beloved;`" and further said to Friends present,
"`Dear brethren and sisters, I exhort you in the Lord to love one another,
and walk in God`'s truth forever.
Women Friends, I exhort you all in the love of God, govern well in your own houses,
or else you cannot govern well in the church of Christ.

Likewise, young women, be sober-minded, and fear the Lord, and be charitable,
and walk in love to the end.
Dear friends, I salute you all in the Lord;
and I here give in my testimony against paying of tithes, for I never paid any tithes,
nor ever condescended to the paying of any, this being my last testimony.`"
She also exhorted Friends to their first love, which they had received in the beginning,
bearing her testimony against the vain fashions of the world.
She died the 5th of the Third month, 1688.

[.asterism]
'''

WILLIAM GIBSON, born in Caton, near Lancaster, about the year 1629,
being a soldier in the garrison in Carlisle, Cumberland, and he, with three others,
understanding that a preacher called a Quaker, who was a stranger,
had appointed a meeting in that city, agreed to go together to the meeting,
with an intent to abuse the said Friend, whose name was Thomas Holmes.
William coming first to the meeting,
and hearing the Friend powerfully declaring the truth,
was so affected and reached by his testimony, that he stepped up into the meeting,
near the place where Thomas Holmes stood, and knowing the design of his fellows,
waited to defend the Friend +++[+++against]
any that durst offer to abuse him.
From this time he became a constant frequenter of Friends`' meetings,
and quitted his place in the garrison, and employed himself in the trade of shoemaking,
and waited upon God in silence, under the exercise of his power,
for the space of three years.
Afterwards he received a dispensation of the gospel to preach,
and became very serviceable in divers places of the county of Lancaster.

On the 22nd day of the Sixth month, 1662, he married Elizabeth Thompson,
daughter of William Thompson, of Crossmore, in Lancashire, and settled in Sankey meeting,
near Warrington, for some years; and some were convinced of truth by his ministry,
who continue faithful to this day, and many others confirmed in the blessed truth;
so that his memorial is of good savour in those parts he
afterwards travelled southwards in the work of the gospel,
and was imprisoned at Maidstone, in Kent, for his testimony, which imprisonment was long;
from whence being discharged, he went to London, and removed his wife and family thither,
where his service was well known to Friends in that city,
and many other parts of the nation, and many are the seals of his ministry.

Though he was severe in reproof,
and terrible in his ministry to the hypocrite and the workers of iniquity,
yet he was as a tender father to the mourners in Zion, and divided the word aright,
speaking a word in season to the tempted, afflicted, and travailing soul;
a cherisher of such as loved and feared the Lord;
and oftentimes his ministry was to the refreshment of the weary,
and the overflowings of his cup administered true comfort and consolation to the thirsty,
panting souls.

He was a lover of unity amongst brethren, but as a sword against that spirit, which,
under pretence of love to the light of Christ Jesus in their consciences,
would plead for a liberty that was out of the truth,
and sought to draw others from the footsteps of the flock of Christ:
to which purpose he wrote a book, entitled, "`An Epistle of Love.`"
He was a man devoted to the service of God, and was an example to believers,
even in word, in conversation, in charity, in spirit, in faith, and in purity,
and gave attendance to reading, and to exhortation, and to doctrine,
given to hospitality, and apt to teach, and was approved as a minister of God.
He had suffered hard imprisonments, and the spoiling of his goods,
for his testimony`'s sake against hireling priests,
who feed themselves and not the flock, and against their maintenance by tithes.

In the Third month, 1684, he travelled into his native country, Lancashire,
though he had been out of health;
and in his return home was taken sick of an ague and fever at Coventry,
yet got to London, and continued ill for three months.
On his sick-bed he exhorted Friends who came to visit him, to faithfulness,
and trust and confidence in the Lord, and to the love of the brethren;
and testified against that spirit which leads out of unity into a self-separation.

He left two sons and one daughter,
to whom he gave good advice in the time of his sickness,
directing them to that blessed and divine light of Christ, which he had preached,
and by which he had received the knowledge of God, and by walking in it,
salvation to his soul; desiring that they might know the same, and walk in it.
"`It will show you,`" said he, "`what is good, and what is evil: refrain from evil,
and do the good; take heed to God`'s word in your hearts,
so you will know your ways cleansed by it.`"

He charged them to avoid all vain and idle company,
and to be diligent in frequenting assemblies of the Lord`'s people,
and to have an ear open to receive the good counsel and advice of them who fear the Lord,
and are faithful to him, and to keep society with such, and to flee youthful lusts,
which war against the soul.
Moreover he said, "`Love the righteous judgments of the Lord,
and have regard to the fear of God, and love humility;
so shall you receive wisdom and understanding.
Be obedient to your mother, and be tender over her; and be not conceited,
nor high-minded.`"
He also charged them to read the Scripture, and other good books.

Thus did this good man, like Abraham, charge his children to walk before the Lord.
He was very resigned, and given up to die, and expressed his love to the brethren,
saying, "`My love in the Lord Jesus is to all the faithful.
Remember my dear love to them, and to all the faithful labourers.`"
Not long before he died, John Field visiting him, he looked earnestly on him;
his wife asking if he knew him, he answered "`No;`" she told him; he replied,
"`He is the first man I did not know.`"
At this time he seemed very retired in his mind unto the Lord, his rock, and his refuge;
several times lifting up his hands, and showed a willingness to be turned, and then said,
"`I have spoken my mind while I could speak, and now I cannot.`"
He died the 20th of the Ninth month, 1684, about five in the afternoon,
and was honourably buried at Friends`' burying ground, in Bunhill-fields,
many hundreds of friends and brethren accompanying his corpse to the grave.
Aged fifty-five years, a minister twenty-six years.

[.asterism]
'''

ELEANOR BARCROFT, daughter of William Barcroft, near Edenderry, in King`'s County,
Ireland, was a young woman of a clean and innocent conversation,
obedient to her parents and loving to all, but especially to the godly,
whose company was her delight; and as her life was good, so was her death.
In the time of her sickness, she desired to have the tenth chapter of Luke read,
wherein two passages were remarkable to her;
the one of the man inquiring who was his neighbour, the other of Martha and Mary;
at the reading of which she was much refreshed.

The morning before she died, it was observed she prayed with a low voice,
and did wrestle in spirit with the Lord; and in the afternoon the Lord did so appear,
that the pangs of death were as it were taken away,
so that she sung hymns and spiritual songs of praise to Christ her Redeemer;
and afterwards said, "`Oh! that I might live with thee forever, and forevermore.`"
Then she took leave of her parents and relations.
Being asked how she did, she answered,
"`I feel neither pain nor trouble;`" and hearing her mother weep, said,
"`Why doth my mother weep, for I am well.`"
With these and some other words which cannot be well remembered,
because of the sorrow of those about her,
she departed this life with the seal of assurance in the true faith,
and is gone to her rest, and hath left a good memorial behind her.

She died the 27th of the Eighth month, 1678, in the nineteenth year of her age.

[.asterism]
'''

THE words and testimony of THOMAS GETTOS, of Bandon, in Ireland,
about eight hours before his departure out of this life.
He was weak in body, but fervent in mind, and perfect in memory;
taken from his mouth the 22nd of the Third month, 1682.

"`I have known the terrors of the Lord for sin,
and for transgression committed against him in the time of my youth.
But he that is an everlasting fountain of life and mercy,
did not leave me in the greatness of my wickedness,
but in the abundance of his pity and compassion visited me, and found me out,
and laid hold on me by his judgments, and did awaken me,
even in that dead state and condition he found me in.
Ile made manifest his living truth, viz. Christ Jesus, the light of the world,
which enlightens every one that cometh into the world, of the whole stock of mankind.

So the light and life being made manifest to me, it became the joy of my heart,
and the life of my soul.
I was brought to see that I must come to deny the world,
and the glory and riches thereof, and the honour thereof,
and all things that are beneath.
It became a very great cross to the fleshly part, which I saw I must daily keep to;
for when I went from that which crucified me to the world, and the world to me,
my enemy prevailed over me; so that I saw the words of Christ fulfilled in me,
in that respect, according to his testimony, who declared on this wise;
'`Whosoever doth not bear his cross, and come after me, cannot be made my disciple.`'

When I came to see that heavenly treasure, made manifest, and revealed in my soul,
and kept my affections thereunto,
the yoke of Christ which seemed to be so heavy became light;
even so it is unto all them that keep in faithful obedience unto him,
and take up his daily cross.
I have known a travel towards that spiritual kingdom of our Lord and Saviour Jesus Christ;
for I saw a race set before me, and I saw, if I did run with all my might,
it was possible for me to obtain the prize.

Therein I have had an exercise of my faith;
for had I not believed in the object of my faith, Christ Jesus,
it had been impossible for me to run that blessed race.
As I was faithful and obedient to the manifestation of Christ,
who is God`'s righteousness, which is manifest and received in the internal parts,
I received daily supplies of strength in my greatest exercises.
Unto whom then shall I return the glory and the praise
of this wonderful work of my salvation,
and eternal happiness, but unto Christ Jesus, the great fountain of life, mercy,
and truth, and righteousness! which I do desire to return at this time,
and at all other times, unto him who lives and reigns forever, God over all,
blessed forevermore.

And now, my friends, as the Lord brought these things unto my remembrance,
I could do no less than declare unto you the wonderful dealings of the Lord to my soul,
that all thereby might receive the instructions of the Lord,
who is forewarning the sons and daughters of men,
according to the greatness of his wisdom.
Certainly, although the Lord never created man to destroy him,
yet his determination shall stand forever; that is,
they that take warning in the day of their visitation, and return with all their hearts,
and with all their souls, shall find the way of life made manifest, and revealed in them,
which leads unto the Father, who is an eternal fountain of life.
But they that neglect the day of their visitation, must he shut up under darkness,
until the great day of the Lord.

And then they shall come to know they have rebelled against him,
and must know his righteous judgments, although it be to their everlasting destruction.
Here they shall see and know that their destruction was and is of themselves;
and God will be glorified, even in the destruction of his enemies.
And now it is the desire of my heart and soul, even before the Lord God Almighty,
that all may be warned and awakened out of that state of deadness
and security which the god of this world hath brought them into,
so that the righteous judgments of the Lord might be made manifest unto them;
that so they may lay hold of his mercy in the day of their visitation.

And as for my dear friends,
who have known the gathering arm of his power into the holy habitation of our God,
which is Jerusalem, which is from above, the mother of us all,
I warn you all in the fear of the Lord to be careful to keep your habitation,
for in that consists your safety.
While Israel kept the place wherein God ordained them to be outwardly,
Balaam could not curse them, nor could any enchantment be found to prevail against them;
but when the wiles of their adversaries enticed them out of their habitations,
how many thousands were destroyed thereby!

The enemy stands without this holy habitation of the people of the Lord,
to entice his people to mix with a wrong seed,
and then we give our strength to our enemies,
and so befool away that heavenly treasure which God hath committed to our charge.
Notwithstanding the enemy hath prevailed over many upon this account,
yet I have taken notice of the goodness of this heavenly shepherd,
and great bishop of our souls, who hath sought after them also,
that have been scattered out of the fold by that means.
Many he hath laid hold on by the crook of his judgments,
and brought them back to the fold again.
And behold how many have perished, to the grief of the shepherd, and of the flock also.

But oh! forever blessed and praised be the Lord,
that hath kept and preserved a remnant that have faithfully followed him,
who are built upon the rock Christ Jesus, where they stand steadfastly,
showing forth the greatness of his love.
They are as a city on a hill, that are seen far and near,
and are become the light of the dark world, by the shining of their holy conversation;
and so shining by reflection, receiving their light continually from Christ Jesus,
the true light of the world.

Blessed are all they who know the gathering into this blessed city,
and abide steadfast unto the end; for the Lord hath chosen Mount Zion unto himself,
that from thence his glory might be proclaimed throughout all generations.
And now, my dearly beloved friends, whom I dearly salute,
even in the bowels of our Lord and Saviour Jesus Christ;
oh! my love unto you all is beyond expression,
who have kept in faithful obedience to the truth.
Oh! the blessed satisfaction that we have found in him,
when we have been gathered into his name, and there drank together in one spirit,
so that our souls have been exceedingly refreshed,
and we have been made partakers of the heavenly bread,
which hath been broken plentifully unto us, even at the table of the Lord.

Oh! never forget those blessed opportunities; but as you are kept in spiritual health,
you will feel a hungering after the bread of life, day after day,
and a thirsting after the water of life also.
So being kept here, you are capable of the blessing of the Lord,
and will see the-Scripture fulfilled in yourselves, which saith,
'`Blessed are they that hunger and thirst after righteousness,
for they shall be satisfied.`"`' About eight hours
after he had delivered this to Friends present,
he died in peace the 22nd of the Third month, 1682.

[.asterism]
'''

JAMES BLACKHOUSE, of Yelland Conyers, in the county of Lancaster,
was born of believing parents, called Quakers, in the year 1668,
and when he grew up he received the same faith,
and for several years professed truth in much sincerity and plainness.
He was a man of a blameless conversation, and a good example,
and of great service in divers affairs of truth, until, in the year 1697, he was,
at the suit of the dean and chapter of Worcester,
apprehended and committed to Lancaster castle for his Christian testimony against tithes.
Here he continued for some time a faithful sufferer, until he fell sick of body,
which increased upon him to the finishing of his life in this world.

When he was, as to outward appearance, nigh unto death, the Lord revived his spirit,
and he sang, and made pleasant melody unto God in his heart; and said,
"`The Lord hath appeared in a wonderful manner unto my soul,
and hath removed and taken away the pains of this my outward body,
and hath received me into his bosom, and hath set me upon his holy mountain,
which is as sure as Mount Zion, that cannot be moved,
and it is better for me to die than to live.`"
He died, a faithful sufferer for the testimony of Jesus Christ, in Lancaster castle,
the 13th day of the Fourth month, 1697.
Aged twenty-nine years.

[.asterism]
'''

MERCY JOHNSON, wife of Elihu Johnson, of Manchester, and daughter of Samuel Watson,
of Stanforth, in the county of York, was born the 7th day of the Fifth month, 1670.
She received a gift of the ministry while unmarried;
and in the year 1697 travelled with Jennet Stow in the work
of the gospel into the western and southern parts of England,
and in some part of Wales.
In the year 1699 she went, with her father, Samuel Watson, into Scotland,
to visit the meetings of Friends in that nation.
She was a tender woman, of a weakly constitution of body, though many times,
when in the Lord`'s service, she seemed very strong,
and was concerned in her spirit for the good of all, and for the prosperity of truth,
and desired no long life in this world.

In the beginning of her illness she often desired of the Lord to give
her patience to undergo what might be suffered to come upon her.
Her illness abated, but in some time came again violently upon her;
also she was sensible her end drew near,
and often desired it in the time of her sickness.
The Lord favoured her with his presence, and made her sick bed pleasant to her,
insomuch that she sang praises to the Lord, the giver of all good things.
Many Friends visited her in her sickness,
and it was a comfort to them and her relations to feel the Lord`'s presence with her;
and she declared of the goodness of God,
and how well content she was to be taken off the stage of this world, saying,
"`I am not in love with it.`"
Many were her excellent sayings, which are not remembered.

Near her latter end she was more filled with God`'s salvation,
and some of her words were as follow; some Friends being present,
"`Happy are you whose kingdom is not of this world, but of the Father`'s;
the Father`'s kingdom, your kingdom Friends, love God better than all.
Be faithful to the Lord every one, although you are but few.
I could have been glad that the whole meeting had been here;
surely they will remember what I said the last meeting I opened my mouth among them;
that was, to prize their precious time, not knowing how long they might have time,
neither what exercises they have yet to meet withal.
Now the time draws near that I shall go to an everlasting kingdom, where all sorrow,
tears and sighing shall be done away.
Glory, glory in the highest, to the Lord my God, who hath been with me,
and borne up my head in time of great exercises.
I have nothing to do but to die.
Keep you near to the Lord,
that so when you come to lay down your heads you may have nothing to do but die.`"

Speaking to her husband, she said, "`Oh! my dear,
I have in the time of my health desired to live with the Lord, and to be faithful to him,
and now I see I have nothing to spare;
what will become of those who live a careless life,
and do not make a right use of their precious time?`"
She was, in the time of her speaking these words, filled with the love of God,
and the sweet spirit of life did attend her, to the comfort of those present;
and she said, "`This outward body grows weaker and weaker,
yet blessed and praised be the Lord, my inward man grows stronger and stronger.`"
In time of silence she made songs of melody to God in her heart;
and after a Friend prayed by her, she said, "`I am so filled with God`'s love,
I shall never be emptied again.`"
She much longed to go out of this world,
waiting for the coming of the Lord to remove her, and said, "`My dear children,
I have prayed for them who are near and dear to me; but now I can leave them freely,
and commit them into the hand of my God.`"
Speaking to her husband and them, she said, "`I must part with all,
and I will bid you all farewell; the Lord bless you all, and keep you all,
in all your exercises that will come upon you.
I believe the Lord will be with you, as you have an eye to him.`"

Another time she said, "`Have nothing to do with them of ill spirits, but keep to God,
and he will give you power over them.`"
She was much grieved to see any professing truth to be light and airy,
out of the savour of it, and said, "`A day of trial will come upon them.`"
Another time, being in a quiet frame of mind, she said,
"`The sooner a period is put to this life,
the sooner I shall go to my everlasting comfort.`"
One wishing her a good night, she said, "`I shall have a good night,
let it be how it will; blessed and praised be the name of the Lord,
I am full of his goodness.
What a great difference betwixt being thus, and in some of my sick fits!
There is a great comfort in one, but not in the other;
only that I think that it is doing the work, and hastening me to my everlasting joy.`"

A little before she was taken away, having got some rest in sleep, when she was awakened,
said, "`Now I am very sensible I must go soon to my joy,
that will last forever;`" and speaking to her husband, said, "`Fare thee well, my dear,
now I shall be well in a little time.`"
She lay still a little while again, then said to those present,
"`Oh! the`' Lord is the best master you can serve while you live,
for he will reward you in your afflictions as he rewards me.
Oh! he is a fountain set open for me in a full manner in my affliction.
Glory, glory, praises, praises to his eternal name.
I will praise him whilst I have breath in my nostrils; he has been a merciful God to me,
and has helped me over many things, and has blotted out my sins,
and will remember them no more.
Oh! praise, honour, and glory to him forevermore.
Now into thy hand I commit my dear husband and children, whom thou hast bestowed upon me,
and will take me from them; bless and preserve them to the end.`"

Thus she was drawn forth to supplicate the Lord for all, saying, "`I love all,
and God above all, for what he hath done for me.`"
After this, she asked what hour it was; they told her four in the morning; she said,
"`I shall surely be gone in a few hours to my everlasting rest;`"
desiring her dear love might be remembered to all Friends in general.
Then she lay down quietly, waiting for her change, and desired all might be still,
and none come to disturb her in her passing away; after she awaked, she said,
"`Let us praise the Lord once more; we will love him above all.
All glory, praise, and eternal renown to his most worthy name; he hath filled my heart,
and is near to crown my soul.
I would not live if I might choose to have the whole world.
Oh! thou, the Lord, art better than all; my soul magnifies thee; honour, glory,
and eternal praises be given to thee forever, and forevermore;
I will praise thee to the end.
Lord be with my dear husband and children to the end.`"

She said, "`I hope you will remember me when I am gone, to the comfort of your souls.`"
She said to her husband, "`The Lord united us in his own love together,
and in his love he will part us.
I was always satisfied before and since, that the Lord`'s hand brought us together.`"
The First-day of the week several friends came to visit her,
whom she exhorted to be faithful to what God had made known to them;
and her words had power with them, to the tendering the hearts of them she spoke to.
A little before her departure, she had a mind to send for her father to her burial,
who was an ancient man, about eighty years of age, and dwelt forty miles off.
He coming, she was glad,
and told him how good God had been unto her in the time of her sickness, and said,
"`If it was not for the hope of glory which is to come, I had fainted.`"

After this, she said, "`Now, Lord, when thou pleasest, remove me;
I am content with thy will, when thou seest meet.`"
She continued in a heavenly frame of mind;
and a young woman who used to go to meeting coming to see her, she gave her good advice;
and afterwards fell asleep.
When she awoke, her husband asked her if she would drink any thing; she said,
"`I have had a full draught of the goodness of my God;
I did not so much as think of cordials;`" and so
continued praising the Lord for his goodness,
and the enjoyment of his presence.
She said, "`My troubles in a little time will be over,
and I shall be at rest and peace with my God,
where I shall praise him forever;`" and she said,
"`Methinks in a vision I have seen my dear mother and sisters, in shining garments,
where I shall be soon.
He is a great and mighty king that I am going to.
Oh! love so, that you that stay a little behind may come after.`"

A little before she died her husband asked her how she did, and she said,
"`Come near,`" and she kissed him, and bade him farewell; and presently again she said,
"`Let us bid farewell again;`" and so died, as if she had fallen asleep,
about the tenth hour at night, the 14th of the Twelfth month, 1704,
in the thirty-fourth year of her age.

A few words of tender counsel and advice to Friends,
given forth by Mercy Johnson upon her dying bed, two days before she died;
which she desired might be communicated to Friends.

Dear friends, both old and young, wherever these may come, my love salutes you dearly,
desiring the welfare of your bodies and souls.
I have in my measure laboured amongst Friends in many places whilst with them,
for the prosperity of truth and good of souls, and now shall be taken away.
I find great concern upon me to leave as advice and tender caution to all,
that you may keep near to truth, and love it, seeking the honour of it above all things.
Dear Friends, love one another, and as you have an eye to truth,
and seek the honour of it before your own, then will your love flow one unto another;
and whispering, with backbiting, and tale-bearing, will be removed from you,
for I have seen the ill effects of such things many times.

And, dear Friends, in your meetings for business upon truth`'s account,
have your eye to the Lord, and wait to have your minds stayed upon him,
respecting one another above yourselves for truth`'s sake,
and you waiting upon the Lord to work in you, and for you,
and to open your mouths to speak a word in season.
Reason not, but give up freely to act and speak for truth, whether you be young or old;
not in high-mindedness, but in true fear before the Lord.
For I must tell you, the humble, and those that abase themselves, the Lord will exalt;
but the high-minded, and those of an exalted spirit, the Lord will abase and humble,
and make them know he is God, and will be bowed to by every high spirit.
Therefore, dear friends, let the truth have the reign in you, to govern your words,
though never so few, that they may be rightly seasoned with grace,
that so you may edify one another.

Suffer no unruly spirit to appear in your meetings, neither in old nor young;
but stand in the counsel of God, and he will give you a word in due season,
to stop the mouths of all gainsayers of the blessed truth,
and of the work you are called to do in your days.
Thus the Lord will bless, and more and more prosper his work in you, to your comfort,
and his eternal praise, to whom all is due.
I can tell you, it will be well with you to be faithful to the Lord,
when you come to a dying-bed, as I now am.
I feel peace and true consolation with the Lord, and my love herein dearly salutes you,
and bids you all farewell, who am your dear and tender sister,

Mercy Johnson.
