== Chapter 2

[.chapter-synopsis]
* Tacy Davis
* Mercy Emes
* Sarah Kirkbride
* Sarah Thompson
* James Baines
* John Blaikling
* Thomas Gilpin
* Richard Andrews
* Priscilla Richards

TACY DAVIS, wife of Richard Davis, of Welsh Pool, in Montgomeryshire,
formerly dwelt in London, but after her marriage,
removed with her husband to Pool aforesaid, where were few or no Friends at that time,
which was about the year 1659.
She had a public testimony in meetings, and was instrumental to bring many to the truth,
and was an entertainer, with her husband, of strangers,
and a nursing mother to those in prison for the testimony of a good conscience.
They lived together to old age,
and she cheerfully went through the various exercises and hard sufferings which attended,
in those days, those that professed the blessed truth.

She was taken sick the 29th of the Second month, 1705,
and had been at a meeting the same day, which was kept at their house about forty years.
After the extremity of her pain was somewhat abated, she said,
"`People do not think it so hard to die, as I find it;`" and prayed thus; "`O Lord,
accept of me in thy well-beloved Son, Christ Jesus.
I have loved thee with all my soul and spirit.
I have kept thy commandments.
Oh!
Lord, bless my family with all heavenly blessings;
grant to them that they may live in thy fear.`"
She said to the servant-maid, who was not a Friend,
"`Remember thy Creator in the days of thy youth;
leave off thy vanity before such a day as this overtake thee.
I have nothing to do but to strive with this natural distemper.
I loved the Lord in my young days, and he kept me from many evils;
and when he was pleased to make known his blessed truth to me,
he helped me to work out my salvation with fear and trembling.
That work I have not to do now; the Lord Jesus Christ did it in me,
and for me;`" upon which the maid wept much.

At another time, pain coming on her, she said, "`I feel I am of a strong constitution,
and that nature would not yield to my distemper;`" and prayed fervently, saying, "`Come,
Lord Jesus Christ, come quickly and put an end to my pain.
Lord, I long to be with thee forever.`"
Another time she prayed, "`Lord, I am the workmanship of thy hands;
thou hast often helped me in the time of need,
for thy name`'s sake help me now in the time of my distress; thou art my God, my hope,
and my help, I will trust in thee, oh my God!
Oh God! hasten thy coming for thy son Christ Jesus`'s sake.`"
Another time she said to her husband, "`I have done too little for the Lord.`"
Her husband put her in mind of her many former services,
and particularly visiting his servants when in prison for Christ`'s sake,
feeding them when hungry, entertaining strangers, and when sick,
very tender in helping them, etc., she replied,
"`All this is too little to do for the Lord Jesus`'s sake, who hath loved us.

We must not depend upon these things,
but we must depend and trust in our Lord and Saviour Jesus Christ;
and when we have done all, let us account ourselves unprofitable servants,
for we have done but that which was our duty.`"
A little before she died,
she desired her husband to praise the Lord with her for all his mercies, and said,
"`At this time I feel his living presence to my great comfort.`"
She prayed herself, saying, "`O Lord, thou hast been a father to me,
thou hast kept me from evil, and now I trust in thy great name,
that thou wilt not forsake me; for thy Son Christ Jesus`'s sake, take me to thyself.`"
And she was heard: about the sixth hour in the afternoon,
on the First-day of the Third month, in the year 1705,
the Lord in his love and mercy took her to himself,
in great quietness and peace of spirit, in about the ninetieth year of her age.

[.asterism]
'''

MERCY EMES, was the wife of Charles Emes, of Warwick, and daughter of John Garner,
of Kinningsworth, of the same county, yeoman.
Her first husband`'s name was Charles Devalc, a Frenchman,
who was formerly a priest of the church of England, and chaplain to the Earl of Essex,
but for conscience-sake he left that church, and joined with the Baptists in London;
amongst which people he continued until his death.

The said Mercy, before she was his wife, attended upon the countess of Ranclagh,
from which family Charles Devale married her.
She did from a child seek after the kingdom of heaven,
and when she was among the Baptists,
was dissatisfied with the doctrine which she often heard
preached of God`'s absolute reprobation of men;
and upon that account sought for a people who had better tidings to preach.
In her inquiry she came to a meeting of the people called Quakers,
where she heard preached the "`free grace of God, which bringeth salvation,
that it appeared to all men, teaching them to deny ungodliness and worldly lusts;
that we should live soberly, and righteously, and godly, in this present world, etc.`"

From that time she, with two other of her acquaintance who were with her,
left the Baptists and embraced the truth,
and joined in fellowship with the people called Quakers;
among which people she married Charles Emes.
She often praised the Lord for the knowledge of his truth,
which she loved and valued above all outward enjoyments,
and ordered her conversation according thereto, unto the end of her days.

Her sickness held her about five weeks,
in which time she said it was a good thing to be ready to die,
and not to have that work to do when we are to leave the world.
The Lord was large in his love to her;
for which she blessed his name in the sense of his mercy;
and as her friends and neighbours came to visit her,
she exhorted them in great love and tenderness,
which caused much brokenness of heart amongst them.
One visiting her, she said, "`I have a love to thee; thou art convinced,
but not converted; hold on thy way, the Lord will do thee good.`"

Another time, two friends visiting her, one inquired how she did, she answered,
"`I am a dying woman; I am going to my God and thy God;`" she said,
"`Why so long coming to see me?`"
he told her the reason: she replied, "`Thy heart is towards Zion,
and so is the other friend`'s;
keep your shoulder to the work which God hath put upon you;
hold him forth to the nations; be not ashamed of Christ, he is a glorious Saviour;
if I should live I must declare it; if I live I cannot hold my peace.`"
She testified to the service of women`'s meetings, saying,
"`Women have a service for God as well as men, and women`'s meetings are of service,
and this is my testimony before I die.`"

To a friend who was under some doubtful thoughts, she spoke by way of encouragement,
saying, "`Thou wilt meet with many troubles,
but it will be well with thee in the end;`" with more words to that purpose.
She spent much of the time of her sickness in praising God.
The day before she died,
she spoke to several friends concerning their states and conditions in the truth.
She was freely resigned to die, and nothing seemed hard to her to part with,
except her two little children, of whom she often said,
"`My little babes;`" but she declared her satisfaction
that the Lord would provide for them,
which is in part fulfilled already.
A few hours before she died, her husband coming to her bedside about midnight,
found her pouring out her soul to the Lord, and she said to him,
"`The sting of death is taken away; I am not afraid to die.
I have the evidence of God`'s love sealed to me:
my bed is a bed of roses;`" which expression she used several times in her sickness;
so resigning her soul unto the Lord.

She finished this life the 31st of the Eighth month, 1697,
and was buried among friends at Warwick.

[.asterism]
'''

SARAH KIRKBRIDE, wife of Joseph Kirkbride, of Pennsylvania, and daughter of Mahlon Stacy,
of West Jersey, in America, was virtuous from her childhood,
and very dutiful to her parents, and an example of piety to her latter end.
She was taken sick the 24th day of the Ninth month, 1703.
In the time of her sickness she uttered many living and weighty expressions,
desiring to be dissolved, saying, "`I have not been afraid of death these many years;
death is no terror unto me; my God hath taken away its sting.`"
She being under great weight of bodily affliction,
and seeing her husband under trouble for her, said, "`My dear,
if it please the Lord to strip thee of thy meet-help again, my God will be thy rock,
he hath been thy stay hitherto, and he will never leave thee.
The Lord will bring me to his holy hill, and I shall praise him upon Mount Zion,
with the saints and holy angels.`"

She again said, "`I shall praise thee, O my God, and my Christ, world without end.`"
Soon after, her husband was moved to pray by her,
that the Lord would be pleased to support and strengthen
her in her distress and great affliction,
and to bear up her exercised soul,
and to make them truly willing to submit to his holy will, whether in life or death;
at which words she said, "`Amen, Amen.`"
A little after, her husband asked her how she did, she said,
"`I am sweetly comforted in my affliction; the Lord is exceeding good to my soul.`"

Many more good expressions she uttered upon several occasions, that cannot be remembered.
The evening before she departed this life, some friends being come to see her, she said,
"`I am weak of body, but the Lord is very good to my soul,
and hath filled me with his love; but my bodily weakness is such,
that it renders me incapable of praising him as I ought to do.`"
To her husband she said, "`The Lord hath heard thy prayers for me this morning,
and hath satisfied my soul to the full;`" more she said to the same purpose,
taking her husband`'s children by the hand, embracing them,
and exhorting them to fear the Lord, and to love and obey their father; and said,
"`He hath been a good father to you.`"
A little before she died, she said, "`My God, I come,
I come;`" and soon after she departed this life,
and is entered into that rest that will never have an end.

She died the 28th of the Ninth month, 1705, aged twenty-nine years.

[.asterism]
'''

SARAH THOMPSON, daughter of George Thompson, of Crook, in Westmoreland, was a maid who,
in her life-time, did truly fear the Lord,
and remembered her Creator in the days of her youth.
She sought the honour and promotion of truth,
according to the measure of grace which she had received;
and according to the understanding God had given her, she was faithful,
and her understanding was good, and capacity large in things natural,
as well as religious.
She took great delight in reading the Holy Scriptures, and other religious books,
and was careful to put in practice what she did read,
and would often be speaking of heavenly things in the family,
and exhorting to virtue and patience;
for it was a great trouble to her when she saw any
impatience or indifference in the family.

She was obedient to her parents, and very tender over them;
kind and compassionate to all, and was beloved of them that knew her.
Her temper was sweet, and of a cheerful spirit and good courage, but not rash,
and of few words,
and very careful not to give offence to those she was at any time in company with,
who were not of our profession in religion,
and very sorrowful when she saw any professing the truth,
who did not walk answerably to the same.

She was much afflicted with shortness of breath, which she patiently bore,
and would say she durst not murmur at it, lest she should offend the Lord.
She often retired alone into solitary places, and said that when she had been alone,
and meditating upon the things of God,
that the Lord did wonderfully break in upon her soul,
by his glorious light and good spirit, and let her see over the world, time,
and mortality, into eternity, which appearance of his presence did very much affect her.
She also said that the Lord had showed her that the time would
not be long until he would ease her of all her pain and sorrow,
and take her to himself.
Another time she said the Lord was present with her,
and comforted her in the midst of all her afflictions,
and spoke peace to her soul in the midst of her troubles,
which she said made hard things easy to her.

She sickened the 1st of the Twelfth month, 1702.
In the time of her illness the Lord`'s power and presence attended her,
and she uttered many weighty expressions, with wholesome counsel and advice,
to the comfort of those about her.
Observing her friends sorrowful, she said, "`You trouble me to see you so;
why are you so unwise?
It would be more satisfaction to me, if you did not one of you shed a tear for me;
must we not all part?
What! is death a terror to you?
It is no terror to me.
I am not at all daunted at it, for I am content whether I live or die;
for if I am spared at this time, you must not keep me long,
having been sensible some time, that I have not long to live.
Cannot you freely give me up, and part with me?
I am but a poor infirm creature, and it will be well with me.
I shall be freed from many troubles, and from many dangers,
which you will be exposed to that stay behind; for I see as long as we are here,
we are liable to many temptations.
I know they will be exercises to you, but keep to that which is good,
and God will keep you, for he hath kept me many a time, as I have kept my mind to him.`"
This she spoke on the Sixth day of the week, in the afternoon.

At another time, her father and mother, and two sisters, standing at her bedside,
she said to them, "`I must die; and I have a word of counsel to you all;
be faithful to your gifts that God hath given you; I beg it of you;
and overcharge not your minds with any thing of this world,
for you see how frail flesh is,
and how soon we are gone;`" with many more weighty expressions which were not remembered.
After this she said, "`I desire you to remember my words when I am gone,
that it may be well with you at your latter end,
that you and I may meet in the mansions of glory, where we may never part.
And be all of you content, for it is well with me.
I have made my peace with God, and I feel nothing to rise up in judgment against me,
for the Lord hath forgiven me my sins and mine iniquities,
and I feel my mind is very quiet and still,
and hath been ever since I begun with this illness.

There is nothing cumbereth my mind, not so much as a temptation is presented,
and I have been borne over my exercises far beyond
my expectation,`" Her brother Isaac being from home,
in the service of truth, she said, "`Remember my dear love to my dear brother.
If I die, tell him from me, that my soul is gone into everlasting rest,
where I hope we shall meet again in the heavenly joy, where we shall never part.
I think I have done,
and I will take my leave of you;`" then taking them one by one by the hand,
she kissed them, and bade them all farewell; and said,
"`I do not know when my life will go; I would gladly die.`"
She prayed to the Lord, and continued in prayer a considerable time;
in which she was very powerful, and was filled with divine praises,
and the power of God was felt by them that were present with her,
and their hearts were abundantly comforted,
and were made to bless the name of the Lord on her behalf.

She prayed fervently for the preservation of those
who should be left behind when she was gone;
he had kept and preserved her from the many hurtful things that are in this world,
and that he would help them through their exercises, as he had helped her many a time,
for which she blessed his name,
and so concluded her prayer with returning living praises and thanksgivings unto God.
Then she signified to them how she had felt the Lord`'s
power to support her in her life-time;
"`for,`" said she, "`I have often cried to the Lord to help me through my exercises,
and he hath answered my prayer many a time, to my great admiration.`"
She lay still a while, and afterwards began to pray again to the Lord,
with a heavenly sweet melody, which did attend her; but she spoke so low,
few of her words could be distinctly understood by them that were present.

Then she asked for her grandmother, who was above eighty years of age, who coming to her,
she took her by the hand, and said to her, "`Thou art now very ancient:
the Lord hath been very merciful to thee, and hath given thee many years,
far above what many attain to; and if thou comest short of making thy peace with God,
thou canst not say it was for want of days.
But see to the improvement of thy gift, I beg of thee before thy days be over,
that it may be well with thee at thy latter end,
that thy soul and mine may meet again in heavenly joy.`"

Her cousin, Robert Thompson, a young man, coming in, asked her how she did; she answered,
"`I am passing away in peace, and so may all do that keep faithful to their God.`",
Then lying quiet, and slumbering a little, afterwards said,
"`I have had a sweet dream;`" her mother asked what: she answered,
"`I thought there were four angels that were conducting me to the land of rest.
I have had this dream,`" said she, "`twice over, but I am here yet.
I am long a going, you have waited long:`" her mother said,
"`Thy death is hard to win;`" she said, "`It will come by and by,
I have prayed to the Lord to make my way easy through death.`"

Her sickness increasing upon her, she grew very weak,
so that it was thought she would not have spoken any more,
it being about two hours before her departure,
yet the Lord was pleased to give her strength again,
so that many weighty words proceeded from her,
to the tendering of the hearts of them that were about her, both friends and others.
Speaking to her father and mother, desiring them not to mind the things of this world,
but to serve the Lord in their day, who is worthy to be served, who is the Lord of lords,
and the King of kings; desiring them to remember the words of their dying daughter;
exhorting to love and charity, and to be prepared for their latter end,
where they might meet in everlasting joy, never to part.

Then asking for her cousin above-named, he came to her, and she said, "`Dear cousin,
whom I love as my own soul, thou art young, and in the prime of thy time,
see thou serve God in the flower of thy age.
The Lord hath created thee that thou mightest serve him;
see thou answer the end for which thou wast created.
And dear cousin, I believe the Lord hath a service for thee if thou be faithful to him,
and I wish well for thy soul, as for my own,
desiring thou mayest be faithful to God in thy day,
that thou mayest have thy account ready, against the day of dissolution,
that thou and I may meet again,
where we shall live to sing Hosannah to the Lord forevermore.`"

Asking for one who was related to her, she said,
"`I have something to say to him;`" he coming to her, she said to him,
"`I remember there was a time when thou thoughtest thou shouldst have died,
and thou wast under great exercise, for I believe thou hadst lived a very loose life,
and the Lord smote thee with his judgments, and I remember thou madest a vow,
that if the Lord would spare thee at that time, thou wouldst amend and do so no more;
and it pleased the Lord to spare thee; but oh!`" said she,
"`hast thou fulfilled thy vow?`"
She exhorted him to more faithfulness, that he might obtain peace to his soul,
before the day of his visitation went over his head.

She said to her sisters, "`Be sure you be good to my mother when I am gone,
and mind not the fading things of this world;`" after which she spoke not many words;
but if she was asked how she did, she would reply, "`I am very well,
and in a sweet frame; I am going to a sweet place!`"
She departed the 6th day of the Twelfth month, being the Seventh day of the week,
about the first hour in the afternoon, 1702.
Aged nineteen years.

[.asterism]
'''

JAMES BAINES, son of William and Sarah Baines,
of Strangerthwait in the county of Westmoreland,
was one who began to seek the Lord in his young years.
As he grew in sincerity and zeal for the blessed truth,
and increased in his concern for the promotion thereof, some time before he died,
God opened his mouth in a public testimony for the Lord Jesus Christ and his pure religion;
in which he was very fervent,
having a sight how eminently God would appear for those who were faithful.
He had a word of encouragement to them,
but was sharp in judgment to the backsliders and unfaithful:
and although he was under much affliction,
by reason of bodily infirmities and distempers which grew upon him,
yet he was more and more devoted to truth`'s service,
as if he had known that his time was not to be long in this world,
even to within some hours that his last sickness seized upon him.

Notwithstanding he was under great pain and exercise of body,
yet the power and presence of the Lord were with him,
which was his great support and strength.
He often spoke of the goodness of God to his soul, and of that inward sweetness,
peace and comfort, that the Lord was pleased to afford to him in his afflictions,
to the great satisfaction of those who were present.
He gave much wholesome advice in the time of his sickness to Friends and others,
and spoke of the prosperity of truth,
and said in particular to his relations as followeth:
"`As we are children of believing parents, and have had our education amongst Friends,
so I would not have you to rest contented there, but be solid, and weighty,
and humble yourselves under the mighty hand of God;
and as you abide here you will feel the goodness of the Lord to spring in your souls,
to your great comfort and inward peace and satisfaction.
I know our natural tempers are inclinable to be light and airy, like other people,
therefore we have more occasion to be bowed and weighty in our minds.`"

Speaking concerning tithes,
he desired Friends would keep up their testimony against them; "`For,`" said he,
"`I could have slipped sufferings if I would have given way to it,
but it was a thing I durst not do;
but I accounted it a great mercy that the Lord had blessed me with
something to part with for his name and truth`'s sake.`"
Although he suffered pretty much at times, upon the account of tithes,
yet the Lord`'s goodness to him did overbalance all,
so that he had a word of encouragement to others on that account.
Upon occasion, speaking of the uncertainty of riches, he said,
"`At some time I pursued them,
and they fled from me;`" but this use he said he made of it;
"`to conclude it was not a city here I was to look after, but one in the heavens,
whose maker and builder is God.`"
This he spoke as caution to others.

At several times he expressed his great peace with God here,
and full assurance of eternal blessedness in the world to come,
through the atonement made by the Lord Jesus Christ,
and the work of sanctification of his Spirit.
The day before he died, hearing that that ancient Friend, Anne Camm, was deceased,
he said, "`Ah! that honest, honourable woman, is she gone to her eternal rest before me?
I shall follow her very shortly, where we shall meet never to part again.`"
Many were the comfortable expressions and seasonable
advices which he gave forth in his sickness,
that cannot be remembered; and as, in his lifetime, he honoured the truth,
so was his latter end comfortable and full of peace; in which he departed this life,
the 1st of the Tenth month, 1705, aged fifty-one years;
and was buried at Friends`' burying-ground, at Sedbergh meetinghouse.

POSTSCRIPT.--The Testimony of Isaac Alexander concerning James Baines,
in a letter dated the 8th of the Tenth month, 1705,
who also died the 11th of the Twelfth month, after him.

Our truly beloved and esteemed friend, James Baines,
departed this life the 1st of this instant; and though he was afflicted with great pain,
yet he bore it with admirable patience.
Though I live remote from him, and notwithstanding my unfitness,
I went often to visit him; and I do not remember that since I came amongst Friends,
any Friend was so universally visited by all sorts of people as he was,
especially by faithful Friends.
Neither did I ever visit a Friend in such a case,
who had that reach upon all sorts of people,
both in the expressions he declared in the time of his sickness,
and also the frame of his spirit.
It was admirably reaching and melting, beyond what I can express,
and so continued to the end, as sweet and sensible as ever.
He died with the greatest esteem and love to Friends and truth,
and in great esteem and interest in the hearts of Friends;
he died in a most happy and blessed condition.

Isaac Alexander.

[.asterism]
'''

JOHN BLAIKLING, of Draw-well, il the parish of Sedbergh, in Yorkshire,
bordering on Westmoreland, was born in the Ninth month, 1625, and he and his wife,
and his father and mother,
were people of good repute and esteem amongst all that knew them,
being all very religiously inclined from their youth.
They were all convinced of the truth in the Third month, 1652,
by the ministry of that truly honourable servant of Christ, George Fox,
whom they received into their house with joy,
because of the glad tidings of salvation that he brought to them;
soon after which John Blaikling accompanied George Fox to Firbank chapel,
where many were also convinced of truth.

About the latter end of the year 1654, or beginning of 1655,
John Blaikling received a dispensation of the gospel to publish to the world,
and was very serviceable therein to many, and soon after,
he was called by the Lord into the county of Durham, Northumberland,
and the east of Yorkshire, where he had then,
and many times since in his frequent visits of those places, good service,
and was with great respect received and loved whilst he lived.
A few years after, he travelled into Scotland, visiting a great part of that nation,
and in his return, as well as going out, visited the northern counties of England.

After it pleased God to raise up others to bear testimony
of his truth in the meeting John Blaikling belonged to,
and the adjacent meetings, to answer the service in part,
which before lay much upon John, he was not only glad thereof,
but a great encourager of them,
and all others at all times that came up in a public testimony for the Lord Jesus Christ,
who is the true light.

He also travelled into many other cities and counties; as at London, Bristol,
Lincolnshire, Norfolk, Suffolk, and Essex, and most counties of England,
and many times to London;
in which service he faithfully continued till weakness of body and old age prevented.
The last time he visited London, was when he came up to the yearly meeting in 1698;
that service being over, he visited the most of Friends`' meetings in the county of Kent,
and his service was very acceptable amongst them.

He was endued with a great gift of discerning, of solid judgment,
and deep understanding in heavenly things,
as well as in the things relating to this life; his ministry was attended with power,
and though his utterance was not eloquent, yet full of profound and weighty matter,
suitable to the several states in the auditory where he did minister.
He was an example in a tender, humble life and conversation,
and zealous for good order in the Church of Christ,
as well as steadfast in opposing and bearing testimony
against such as would endeavour to break unity,
and so lead into a loose liberty, disorder, and confusion, as well as other evil works.

It was at J. Blaikling`'s house, which is called Draw-well,
that the memorable meeting was held for the endeavouring the recovery of John Story,
and John Wilkinson, and others,
who opposed the good order and discipline now established in the churches of Christ.
The said meeting began upon the 3rd day of the Second month, 1676,
and continued four days:
but notwithstanding the labours of many brethren
met at that time from divers parts of the nation,
and particularly four Friends from the city of London,
the said John Story and John Wilkinson continued
in their contention and opposition to Friends;
and not long after William Rogers published a book against Friends, which J. Blaikling,
etc., answered, entitled "`Antichristian Treachery Discovered,
and its Way Blocked Up;`" a volume in folio, of about 50 sheets.

He was a great supporter of such as were in low circumstances in the world,
often assisted them in difficult cases, to the exposing himself to great hazard of loss;
and many times he was blessed with good success therein.
He obtained the blessing of a peace-maker, being of a good understanding,
was qualified with judgment and patience to reconcile differences about temporal affairs,
which was a means to bring him into many concerns of trust for orphans, etc.,
which is always attended with great care and trouble, and which often fell to his lot.

The loss of him in the church, as well as among the neighbourhood, is great.
He was not only called to believe in, and preach Christ Jesus, the truth, the way,
and the life, but also to suffer for his name`'s sake,
not only by loss of goods to a great value,
but also by imprisonments several times at York, about sixty miles from his family,
both on account of meetings for the worship of God,
and in a firm testimony against tithes.

Whilst he had strength, he was diligent in attending meetings;
but old age and bodily infirmities growing upon him latterly, sometimes prevented him.
Several times he expressed to friends in private the comfort that he had in the
Lord`'s peace and presence with him to his satisfaction in his old age,
and that his day`'s work was nigh done, and his reward and rest with God sure.
This testimony agrees with the last letter I received from him, save one part,
as followeth:

Dear John,

I love thee in the truest love that springs from Jesus Christ the fountain thereof,
by and in which my life standeth;
though as to bodily health and strength I grow weak and feeble,
but my life in God standeth, whose I am, and I am comfortably content.
I am scarcely able to walk to the door, nor have I been at a meeting these several weeks,
but the Lord`'s will be done.
I am comforted in the remembrance of my former services for the Lord, his truth,
and people, for which I want not my reward in this my old age.
I take time to read.
I am almost blind, yet well content.

J+++.+++ Blaikling.

He often signified his preparedness to leave this world,
with fervent desires for truth`'s prosperity,
and the preservation of unity and concord amongst brethren,
in a faithful and steady testimony for the same in every part thereof,
as led into by God`'s power in the beginning.
Not long before his death,
his ancient and intimate friend and acquaintance Thomas Camm being with him,
he said to him, "`Thou and I have not sought our own interest,
but have devoted ourselves to serve the Lord, his truth and people; he is,
and will be our great reward in the end of all our troubles.

I am greatly satisfied that I have faithfully served the Lord, and done my day`'s work,
and enjoy the earnest of that peace and rest God hath laid up for his people;
and if thou and I shall never have opportunity to meet again in the outward,
yet in eternity our spirits, with the spirits of just men made perfect,
shall meet never to part again.
I pray God with all my soul, if it be his will for his truth and people`'s sake,
to lengthen thy days, and grant thee that strength of body and health,
that at least thou mayest be able once more to visit London, Bristol,
and the southern parts of this nation, which will be of great service,
and acceptable unto many.`"
This he spoke with great tenderness of spirit; to which Thomas Camm replied,
"`The will of the Lord be done,
I am in his hand:`" so in much brokenness embracing and kissing each other, they parted;
this was four or five days before his death.

He had a short sickness, and an easy death, falling into a fainting fit,
as sometimes before.
He passed quietly away out of this world, without sigh or groan,
wanting about four months of eighty years,
and was honourably buried at Friends`' burial-place, at Sedbergh meetinghouse,
the 4th day of the Fifth month, 1705.

[.asterism]
'''

THOMAS GILPIN was born in the year 1622, son of Thomas Gilpin, of Mill-hill,
in the parish of Caton, near Lancaster.
His parents had five sons, and five daughters, whereof Thomas was youngest son;
they were people of good repute in the country, and were religious,
being called Puritans, who educated their children very strictly.
After his father`'s decease, his mother removed with her children to Kendal,
in Westmoreland, five of her children being dead;
and she was so zealous as to force them into acts
of religion before they knew what they did,
as to pray without a form, etc.
Thomas being but about ten years of age, considered it was not right,
for he said he knew not who to pray to.
After he grew up in more years, and his mother deceased,
he ran into foolish and wanton delights, as sports and pastime, music and dancing.

He went to London as apprentice to a tallow-chandler, and after went into the wars,
(being the time of the civil wars in England,) where he was tempted into more evils.
Yet in all this time the Lord followed him by his good spirit,
reproving him in his own conscience for his sins,
which brought great fear and trouble upon him;
but by one means or other he endeavoured to get over these convictions,
and so continued a considerable time striving against the good spirit of God.
But oftentimes the Lord again did awaken him,
and brought the consideration of death upon him, even in the time of sickness,
and of battle, which he was often in.
Then he would cry to the Lord for mercy,
and that he would deliver him from death at such times,
making promises of reformation for the future.

And God was merciful and spared him, yet he forgot his promises and covenants,
and fell into the same evils again;
after which the Lord brought double fear and torment upon him.
At last he received the blessed truth, as preached by the people called Quakers;
and in believing in and obeying the light and spirit
of Christ manifested in his own heart,
he came to receive power over those sins which had prevailed in times past over him,
and so came truly to know repentance, and remission of sins, in the name of Jesus Christ,
the true light of the world.
And afterwards,
in the remembrance of the unspeakable long-suffering and mercy of God unto him,
he said in his life-time,
"`Shall it not be recorded to posterity for the benefit of my children,
and my children`'s children, that it may be a warning to the obstinate and rebellious,
to turn from the evil of their ways, whilst the spirit of the Lord striveth with them,
lest the day of their visitation go over their heads.`"

In 1653 Ambrose Rigg, Thomas Robinson, and Jane Waugh, came into the county of Oxford,
to preach the free gospel of the grace of God;
at which time Thomas Gilpin received their testimony.
After eight or nine years waiting upon God in silence,
God gave him a dispensation of the same gospel to preach to others,
and he became an able minister, showing himself approved unto God,
a workman that need not be ashamed, rightly dividing the word of truth.
In this service he labored much, travelling through many parts of England,
but chiefly in the counties of Oxford, Berks, and Bucks;
he was a prisoner for his testimony to the truth twice at Oxford,
and once in Newgate in London.

His settlement was in the parish of Warborough, in the county of Oxford,
where he married Joan, the daughter of Thomas Bartholomew, of the same parish,
husbandman;
in which place he was instrumental to settle a church
or meeting of the people called Quakers,
which remaineth to this day, as well as in many other parts where he travelled.
He was successful by his ministry to turn many to righteousness,
and for building them up, and establishing them in the most holy faith.

In the year 1702, and the eightieth of his age,
he was weak in body for the most part of the winter,
but complained little of either sickness or pain, his body gradually decaying.
In the time of his sickness he desired one of his
sons to remember his dear love to friends,
and give them account of his sickness and departure.
As he was zealous for God and his truth in the time of his health, so he was to his end,
for he went to Friends`' meetings for the worship of God as long as he was able, saying,
"`I am willing to be a good example so long as I have strength to go.`"

When he was so weak that he could hardly go out of his chamber,
he desired friends to meet in his room, which was not long before he died;
at which time he signified to friends that he was satisfied,
that as to words he must cease, but this was his comfort,
that he enjoyed the power of the Word of life, which is beyond all words.
He exhorted friends to faithfulness, and to keep their meetings,
and not to look out at his being removed from them;
putting them in mind of the goodness and love of God,
which had been largely manifested both to him and them,
in carrying them through many trials and exercises,
and in preserving them in love and unity one with another,
which he desired they would be careful to continue in.
When he had done speaking, a friend prayed,
and Thomas Gilpin`'s heart was much comforted in feeling the presence of the Lord,
as well as those present, who were much tendered and broken into tears,
and at the conclusion he again recommended love and unity one with another;
and also declared that he was given up in the will of the Lord,
and took his leave of them all.

This was the last meeting he had with friends; but he was much visited by friends,
and it was a comfort and delight to him to see them,
and sometimes it was hard for him to part with them, saying,
"`This is such a parting as we never had before.`"
The Lord was very good to him all the time of his sickness,
and did often cause his heart in the feeling of life
to sound forth praises to the name of God;
and he said he believed he as much desired to die, as ever any one did desire to live,
although he wanted for nothing in this world; but said, "`I long to be dissolved,
and be with the Lord, yet am willing to wait God`'s good pleasure.`"

The day before he died, viz. the 2nd of the 12th month, some friends visiting him,
he desired one of them to supplicate the Lord on his behalf, to put an end to his days,
and make his passage easy.
After some time the friend prayed to that purpose; when he had done,
Thomas Gilpin lifting up his hands, said,
"`The Lord grant thy request which thou hast made to him this day.`"
Though at that time to outward appearance he seemed likely to have lived some days,
yet he quickly altered, and the morrow, about the fifth hour in the afternoon,
he departed this life, being the 3rd day of the Twelfth month, 1702.
He left behind him three sons and two daughters, and all of them had children.

He was buried honourably the 8th of the Twelfth month, 1702,
after he had professed truth forty-nine years,
and had been a minister of the gospel forty years.

[.asterism]
'''

RICHARD ANDREWS, son of Richard Andrews, late of London, silk-man, and his mother,
one of the daughters of our ancient friend, Thomas Gilpin aforesaid,
was educated by his father-in-law, Moses West, of Hempsted, in Hertfordshire,
and his own mother, not only in useful learning,
in order to his accomplishment for trade and good settlement in the world,
but also it was their great care to have him brought up in the way of truth.
He was put apprentice in London to the silk trade; but after some years,
what by the examples of others, and temptations of the enemy,
he declined from his former simplicity and sobriety, and good inclination to truth,
into more liberty and vain company and fashions of the world,
which was a grief to his father and mother.

He was taken ill about eight or nine months before he died, of a decay of nature,
which terminated in a consumption; and such was the goodness of God to him,
that he was awakened in himself to a consideration of his inward condition,
the visitation of God by his spirit being upon him,
and he had frequent visions in the night of the near approach of his latter end.

Being at Hempsted with his father and mother,
he had opportunity to retire alone into private places,
where he poured out his soul to the Lord in supplication,
and great travail of soul came upon him, especially towards his latter end,
for he was bowed in deep humility, praying for the light of God`'s countenance,
in whose presence is life, peace and comfort.
But the Lord was pleased to chastise him, by hiding his face from him for a time,
yet he kept his hold, trusting in the Lord;
though in this state he met with many assaults from the devil,
and temptations to despond of God`'s mercy.
Now he knew what it was to read in the book of conscience,
and for his works to go beforehand to judgment.

Now he disliked the company of those young men, his former companions,
with whom he used to walk abroad in the fields, sometimes on First-day afternoon,
and neglecting going to meeting for the public worship of God,
which now became a very great trouble to him,
and that he should spend his precious time so vainly.
His powdering and apparelling, and such like follies,
he particularly expressed a great sorrow for,
promising that if the Lord should prolong his days,
he would endeavour to follow the best examples and
strictest way of living amongst faithful Friends;
calling to mind, and praising the good life of his grandfather Gilpin.

A friend visiting him,
together with the good advice of his father concerning
the Lord`'s hand that was upon him,
it being not in anger but in mercy, that he might turn unto him,
with fervent desire after him, and enjoyment of him, and when he should obtain that,
his wants should be supplied; so after some time the Lord did appear in him,
and did lift up his spirit as a standard against the enemy of his soul,
who came in like a flood, and tempted him to doubt of his mercy,
so that he was comforted like a man reprieved from judgment,
though not as yet having a full assurance of his pardon;
but a living hope sprang up more and more, which became as an anchor to his mind.

His company became delightful, because of those serious reflections he made on things,
and religious discourses which he had with those about him.
One time he said to his father and mother, "`I will appeal to you,
if you ever heard me repine at the exercise and pain
I have gone through since I have been at home,
all this time of my great weakness?
No,`" said he, "`I have desired the Lord to let me have all my punishment in this life.`"
Indeed, he was sweet and cheerful under all his pain, which was very great;
and he grew very bright and living when he had got dominion over his doubts and fears.

Near his latter end, through the prevalency of his distemper,
he was somewhat broken in understanding, and wandered in his discourse,
though his talk was inoffensive; yet, as if he had foreseen this, a little before,
a kinsman of his, not one called a Quaker, offered to tarry with him;
to which he showed himself unwilling, giving this reason to his father and mother,
saying, "`May be I shall be light-headed, and ramble in my words,
and he or others may inconsiderately reflect upon my profession.`"
Though his sickness was long, his death was pretty sudden,
having kept his bed but four days, in which time, whilst sensible,
he was kept in a most sweet, resigned frame of soul;
being by his bedside was like being in a well-replenished meeting.

Near his end, he said to his father and mother, "`Do not grieve,
the Lord is with me,`" with much more to the same purpose; so lying still and quiet,
he went away with a smile, and is at peace with the Lord.

He died about the twenty-first year of his age.

[.asterism]
'''

PRISCILLA RICHARDS, daughter of John Richards, of Howsey, near Liskeard,
in the county of Cornwall, and of Priscilla his wife,
was born at Liskeard the 18th of the Sixth month, 1680;
and though educated in her father`'s family,
who were mostly strangers to the living way of truth, now in this our age revealed,
only her mother frequented the meetings of the people called Quakers;
yet did this young maiden begin according to the advice of the wise man,
to remember her Creator in the days of her youth.

She not only came to the meetings of the said people,
but turned with her heart to the Lord; and as she came towards seventeen years of age,
she grew in the fear of God, and in plainness and solidity,
not regarding the gaiety of this perishing world so as to set her heart thereon,
but became very modest in her habit, speech, gesture, and in all her deportment,
and was greatly in love with the company of the best Friends,
to whom she also became very acceptable.
Though the family in which she lived might minister occasion to her,
to look out at the ways and glory of this world, yet she was as one weaned therefrom,
and delighted in retirement of spirit,
and in that society which might be helpful to her in her
way to that heavenly habitation to which she was travelling,
and whereunto the Lord brought her in the very prime of her blooming years.
She was scarcely twenty years of age when she was visited with some infirmities of body,
which still drove her nearer the Lord;
and although she met with some exercises grievous to her tender spirit,
yet she was resigned to the will of God.

About the beginning of the year 1704, it was perceived by some symptoms,
that her distemper tended to a dropsy, in which abundance of care,
both of parents and able physicians was used, yet her disease increased,
so that it was apparent some months before she died,
that there was little or no hopes of her recovery, which she foresaw,
yet was very well satisfied and resigned to the will of God,
in which she had peace and great quietness of mind,
and would often testify as much to her mother and those about her,
as well as friends who frequently visited her;
for she having her affections drawn out of the world,
it became easier to her to leave it.

In a letter to a particular friend, who married her near relation,
written about fourteen days before she died, she says thus:

Dear Cousin,

I should have given an account of my sickness, but exceeding illness hindered me,
and my mother, what with sorrow for me, and want of time, occasioned the same neglect.
I am now very ill, being swollen all over my body, except my hands and arms,
and am scarcely able to walk the chamber without help;
but I am freely given up to the will of my heavenly Father, whether for life or death.
I should be glad to see any of you here,
for my time in this world is not likely to be long.
I have been a little better at my heart this four or five days,
but how it will please the Lord to deal with me, I know not.
My dear love is to thee, thy wife and children,
wishing you health and peace in this life, and happiness in the life to come; being,
dear cousin, thy affectionate, etc.,

P+++.+++ Richards.

This was written in a time of great weakness of body,
but her spirit was strong in the Lord, having kept the faith,
and by it was made a conqueror.
About this time, her mother sitting by her, she said,
"`It is well for me that I feared the Lord in my youth,
seeing old age is not likely to be my lot.`"
Those friends who visited her in the time of her weakness,
were greatly comforted in the testimony she gave,
and sense they had of her living condition of soul, in a dying state of body.
To a friend who said to her, "`I hope, if thou dost recover,
thou wilt live to praise the Lord;`" she replied,
I do not desire life upon any other terms.`"
Her expressions were many and frequent as to her peace and acquiescence of mind, but,
her friends not supposing her end to be so near, they were not duly written down.

Her mother at a certain time,
hearing her speaking of her willingness to be with the Lord, said,
"`What!hast thou no sympathy with my sorrow and grief, at the parting from thee,`" etc.,
she replied, "`Mother, thou beginnest to grow old,
and it will not be long ere we meet again in a better place,
if we are found doing the will of God.`"
In this sweetness of temper she abode without reluctancy
or impatience at her state of body,
which decayed daily.
On the twelfth of the Seventh month, 1704, she was taken with some fainting fits,
which made her attendants stir more than usual, at which she reviving said,
"`Why did you not let me alone, I was very easy,
and in much quiet;`" and then turning to her mother, she said, "`Time will come;
do not grieve, nor make the Lord angry.`"

To some about her, "`Do not leave repentance until a dying hour,
for the body hath enough to do to bear its pains.`"
At night, her father going to bed, took leave of her.
She said, "`If she never saw or spoke to him more, she was well.`"
But then her pains returned on her, yet she got up the next day,
but had again some such dying fits, however continued till the next day after,
always being very sensible, under no manner of disturbance in mind.
On the 14th of the Seventh month, being sensibly weakened,
and feeling the approaches of death, she said, "`Come, come, come,
why so long;`" and in a very little time after called out, "`Lord Jesus,
receive my spirit,`" and presently breathed forth her last,
according to her prayer to the Lord, that she might not go stupified out of the world,
for she died in full understanding, and soundness of mind,
and is gone to rest in the Lord, blessed be his name forever.

On the 18th of the Seventh month, 1704, her body was decently buried,
from her father`'s house, in Friends`' burial ground, in the parish of Liskeard.
Thus we have here an example of what one of old said of youth that is soon perfected,
which shall condemn the many years and old age of the ungodly.
