[quote.epigraph, , Wisdom]
____
Honourable age is not that which stands in length of time,
nor that is measured by number of years, but wisdom is the gray hair unto men,
and an unspotted life is old age. -Wisdom
____

== Preface.

The following pages have been compiled with a view of exhibiting to young
persons the happy effects and peaceful termination of a religious life,
in those of their own age.
The materials for the narratives have been principally
obtained from the different volumes of Piety Promoted,
and other authentic memoirs of deceased children;
but as many of the accounts were more detailed than appeared
necessary to answer the design of the present work,
they have been written anew, and somewhat abridged.
For the liberty thus taken,
it is hoped that the desirable object of embracing as much
instructive matter in as small a space as practicable,
will be considered a sufficient apology.

The frequent vocal reading of the Holy Scriptures and other religious books, in families,
is a practice which has been productive of good to many.
It not only accustoms children to habits of stillness and sobriety,
but is often a means of making serious impressions on their minds,
which exercise a salutary influence over their characters and conduct through life.
There are probably few persons,
whose privilege it has been to receive an education
in families where this christian duty has been observed,
who cannot recur to some of these seasons of religious retirement,
as times of heavenly visitation,
wherein their spirits have been contrited before the Lord,
and induced to enter into covenant with Him.

Those who are duly sensible of the great responsibility
which attaches to the parental relation,
and who feel a correspondent engagement of mind faithfully
to discharge their duty towards their families,
cannot neglect the practice of thus collecting them,
either for silent waiting or devotional reading.
Where this is done with minds reverently disposed
to seek the Divine blessing on their endeavours,
we cannot doubt but that He who hears and answers prayer,
and who beholds with approbation the tender solicitude of
pious parents for the eternal welfare of their offspring,
will graciously assist them by the secret influences of his Holy Spirit.
And although it may sometimes be the case that but little benefit is apparent,
at the time, from the labour thus bestowed,
yet this should not be made an apology for its discontinuance.
The lessons of religious instruction instilled into their minds may prove as "`bread
cast upon the waters,`" the advantages of which will be seen and felt "`after many days:`"
Even if the exertions of parents to "`lead their children in the paths of righteousness
for his name`'s sake,`" should not ultimately be crowned with complete success;
yet, if they honestly endeavour, by precept and example,
to train them up in a holy life and conduct,
they will at least enjoy the consoling reflection of having discharged
their duty as regards this important part of their stewardship.

In the list of religious books, the inspired writings are, unquestionably, preeminent.
But while we cheerfully bear our testimony to their superior
excellence as an external means of moral and religious instruction,
and desire to see them made the subject of attentive, daily perusal,
it is proper that we should also avail ourselves of other helps which are offered to us.
Of these, we may safely place next to the Sacred Volume,
the history of the closing days of those who, through the mercy of God in Christ Jesus,
have had an interest in Him, and enjoyed, in their dying hours,
"`a hope full of immortality and eternal life.`"
Their blameless and consistent walk;
the unspotted example which they maintained amid
the corruptions and temptations of the world;
their unshaken confidence in the goodness of God,
the divine support which they experienced in the hour of disease and death,
and the glorious prospects which brightened their hopes in looking beyond the grave,
have justly been considered among the most powerful incentives to virtue.
The reading of these narratives to children,
has often been found to kindle in their minds, even at a very early age,
sincere and ardent desires to live the life of the righteous,
that at last they may die the same peaceful and triumphant
death as those of whom they hear such happy accounts.

In an age like the present, when the allurements to vice are numerous and seductive,
and their pernicious tendency heightened by the demoralizing
influence of libertine principles,
it becomes parents to watch over their children with the most sedulous attention;
to use every means for guarding them from the prevailing contamination;
to cherish and strengthen their feeble aspirations after Heaven and holiness,
and to instruct them thoroughly in the doctrines of the gospel,
which form the only solid basis for a religious life,
and furnish the alone certain hope of a glorious immortality.

An attentive observer of youth cannot fail to perceive that their
minds are the subjects of divine visitation at a very early period.
That "`grace of God`" "`which is shed on us abundantly through Jesus Christ
our Saviour,`" pleads with them for sin and invites them to godliness,
when they are so young as scarcely to be capable of appreciating its high origin.
It is, then,
both the interest and the duty of those who are their nearest
friends and the natural guardians of their infancy,
to teach them that it is the voice of their heavenly Father pleading with them in love;
to impress upon them the great importance of yielding obedience
to its gentle intimations in the secret of their minds;
and, as Eli instructed Samuel,
reverently to answer His sacred calls in the submissive language "`Speak, Lord,
for your servant hears.`"

In the morning of life, while the animal spirits are buoyant,
the physical powers vigorous and teeming with health,
the imagination lively and the senses susceptible
of vivid impressions from external objects,
the world with its pursuits and pleasures presents
strong attractions to the youthful mind.
All is bright and cheering;
and in that mistaken confidence which is the result of inexperience,
children are apt to conclude that all will continue to be bright and happy.--Should
a transient shade be thrown over their joyous path by some unexpected cloud of sorrow,
the impression is quickly effaced by a succession of new and pleasing
objects.--They dwell only on the bright side of the picture,
and readily conclude that as they have good health and spirits,
agreeable and kind friends, and fair prospects of a long and happy life,
it will be time enough some years hence, to become religious and prepare for death.
In the midst of these pleasing but deceptive anticipations how many have
suddenly been cut down and consigned to the cold and silent grave!

It is important therefore for those who have the charge of children,
early to impress their minds with a deep sense of
the shortness and uncertainty of human life,
of the emptiness and transitory nature of all temporal enjoyments,
the unspeakable importance of an early and entire surrender of the heart to God,
and a timely preparation for that solemn period when they must bid a final
farewell to all visible objects Their accountability to their Heavenly
Father should also form a prominent feature in early education.
That as he is everywhere present with them, on all occasions,
and privy to the most secret thoughts and intentions of the heart,
whatever they think or say or do is known and remembered by him,
and must be accounted for in that day when they shall stand before
his judgment seat to receive a reward according to their deeds,
whether they have been good or evil.
They should also be taught that the great business
of life is to serve and glorify their Creator,
and thus prepare for their transition to another state of existence,
which will be eternally happy or miserable according as they obey
or reject the religion of Christ Jesus their Lord.

A common error, and one which has a very pernicious tendency on the minds of youth,
is the false idea that a religious life is one of gloomy
privation and sadness.--To the correction of this perversion,
the force of parental example and precept should be perseveringly directed.
The conduct of parents should evince to their offspring,
that although religion always leads to seriousness and self-denial,
it is never incompatible with innocent cheerfulness and affability,
nor the proper enjoyment of those outward blessings which
a kind and beneficent Father has poured forth around us.
That while it teaches us to use the present world as not abusing it,
there are consolations and pleasures springing from true religion as a perpetual fountain,
more pure, elevated and permanent than anything this changeful life can give;
and although from the necessities of our present condition,
we pursue the lawful avocations requisite to provide
for our short and uncertain stay on earth,
yet that our highest enjoyments are derived from the life that is to come,
and our hearts and affections set on things in heaven,
where Christ sits at the right hand of God.

Where parents preserve this heavenly temper and lead a life corresponding thereto,
the work of religious education will be greatly facilitated.
Children are not only very observant, but they are imitative creatures.
They are quick to perceive what objects predominate in the minds of their parents,
and where their attachment and pursuits are mainly directed; while from affection,
and the confidence they place in them, as well as the disposition to copy after others,
they will soon be brought to love and to pursue the same objects.
If parents are making the acquisition of riches a primary object,
or are delighting in the fashions and pleasures of the world,
living in a costly and luxurious manner,
and taking their comfort in the good things of this life,
their professions of a self-denying religion,
or their lessons on the vanity and emptiness of worldly enjoyments,
can have but little weight with their children.
How important is it then that they should steadily
watch over and regulate their own hearts,
by the restraining influences of the spirit of Christ,
and live such lives as they would wish to see imitated by their beloved offspring.

When we contemplate the endless duration and unchangeable nature of that "`recompense
of reward`" which is reserved in Heaven for the self-denying and devoted christian,
a foretaste of which is vouchsafed to him, at seasons, in his pilgrimage through time;
and contrast with it, the short and uncertain tenure of human life,
the emptiness of all earthly enjoyments,
and the lightness of those afflictions which are but as for a moment,
who but must adopt the language of the inspired preacher,
respecting the highest temporal gratifications, "`Vanity of vanities--all is vanity.
To fear God and keep his commandments is the whole duty of man.`"

Such considerations will animate us to pursue with greater diligence "`the
things which make for our everlasting peace;`" to count the riches,
the pleasures and the pursuits of time but as dross,
in comparison of the excellency of the knowledge of Christ Jesus our Lord, if, happily,
we may at last "`be found in Him, not having our own righteousness,
but that which is through the faith of Christ--the
righteousness which is of God by faith.`"

That the perusal of the following pages may be a means of promoting this blessed work,
by kindling in the minds of youth, availing desires after pure and undefiled religion,
and strengthening their resolutions to walk in "`the narrow way
which leads to life,`" is the sincere wish of the compiler.

[.signed-section-context-close]
Philadelphia, 2nd Month, 1835.
