== Chapter 2

[.chapter-synopsis]
* George Chalkley
* Charles Parry
* Mary Ann Clapp
* William Tyler Barling
* Ruth Middleton
* Hannah Hill
* Elizabeth Merritt
* Peace Ring
* Mary Samm
* Elizabeth Wills

GEORGE CHALKLEY, son of Thomas Chalkley, of Frankford, in Pennsylvania,
delighted in reading the Holy Scriptures and other good books,
was obliging and obedient to his parents,
and ready to do any service he could for his friends.
He was diligent in attending religious meetings, and loved the company of pious persons.
To his mother he was, in an uncommon degree, kind and affectionate,
cheerfully doing whatever he could to serve her,
and requested her not to do some things which he thought too much for her; saying,
"`Mother, let me do it,
for if I was a man you should not do anything at all,`"--meaning as to labour.
His filial love and care for her, in her husband`'s absence,
was truly affecting and grateful to her.

In reading the Scriptures, or other religious works,
he was in the practice of writing down such passages as particularly interested him,
and committing them to memory.
One text which he had thus copied out,
was the fifteenth verse of the 57th chapter of Isaiah,
which seemed applicable to his own state, viz.: "`For thus says the high and lofty One,
that inhabits eternity, whose name is holy; I dwell in the high and holy place,
with him also that is of a contrite and humble spirit,
to revive the spirit of the humble, and to revive the heart of the contrite ones.`"

He was taken ill on the 5th of the eighth month, 1733,
and during the course of his sickness behaved more like a wise man than
a child of ten years old--being often very fervent in prayer,
not only on his own account,
but also entreated that God would preserve his people all the world over.
His father was absent in another part of the world,
and though he would gladly have seen him, yet he said he should never see him more,
desiring his mother to give his dear love to him,
and tell him that he was gone to his heavenly Father.

On one occasion, being in great pain, he prayed,
"`Sweet Jesus,--blessed Jesus,--give me patience to bear my misery and pain,
for my misery is greater than I can well bear.
O! come, sweet Jesus;--why are you so long in coming?
I had rather be with you than in the finest places in the world.`"
At another time he said, "`my misery and pain is very great,
but what would it be if the wrath of God was in my soul.`"
His heart was full of love to his relations and friends who came to see him,
and he took a last leave of them with a sweetness and tenderness which affected many.
He died the 13th of the 8th month, 1733, aged 10 years.

[.asterism]
'''

CHARLES PARRY, of Rochdale, England, died the 12th of fifth month, 1842, aged 10 years.
This dear child had been early instructed in the school of Christ,
and by obedience to the manifestations of divine grace verified
in his experience the truth of the Scripture promise:
"`They that seek me early shall find me.`"
He evinced great tenderness of conscience, feeling sorrow for his sins,
whenever he had done anything wrong,
and desiring forgiveness both of his parents and of his heavenly Father.
He was fond of reading the Bible and other religious books,
and took good notice of what he read, often making pertinent observations respecting it.
During his sickness he often desired his mother to pray for him;
and once on being reminded that he must endeavour to pray for himself, he replied,
"`Yes--I do pray for myself every night and many times in the night.
Last night,
I prayed to my heavenly Father that a crown of glory might be prepared for me,
and that I might sit at the right hand of God.`"
Another time he was heard to pray that the Lord would be pleased to release him,
if it were consistent with his will; and though he suffered much,
desired to be preserved in patience,
and expressed his belief that when released from the pains of mortality,
"`heaven would be his home.`"

[.asterism]
'''

MARY ANN CLAPP died in the year 1816, in the eleventh year of her age.
When quite young she loved to hear religious conversation, and to read in the Bible,
Hymns for Children, and other religious books.
She frequently retired alone for secret prayer,
and would sometimes tenderly and solemnly reprove
her brother and sisters for their faults,
and exhort them to pray to God for forgiveness.

Her mother hearing her cry one night, inquired the cause of it;
the child replied that some time before, she had spoken what was not strictly true,
and she was now grieved that ever she had committed so great a sin,
fearing her Maker would not forgive her.

When about five years old she lost a sister, which much affected her mind;
and afterwards, in alluding to it, she said, "`I thought I might die too,
and I felt afraid if I did die, that I should not go to heaven.`"
Being asked what she did when she felt these fears, she answered,
"`I used to go by myself and cry, and pray.`"

When taken ill, she was under concern of mind about her future state,
and being asked whether she was willing to die, she replied, "`I should be willing,
if I knew that my sins were pardoned;`" adding,
"`I should be glad to be one of the little flock,
which the Saviour carries in his arms.`"
But, through the condescending mercy of God,
this anxiety and distress of mind did not long continue before she received
a comfortable evidence that her sins were forgiven her.
She desired her mother to pray with her and soon became quiet, saying,
"`My doubts are all removed--my sins are forgiven; I am willing to die, at any time,
when God shall please.`"
She requested her mother to read to her out of the Bible and other good books,
and although she could repeat the following lines, yet it was her wish to have them read,
viz:

[verse]
____
See Israel`'s gentle Shepherd stand
With all engaging charms:
Hark! how He calls the tender lambs,
And folds them in his arms.
____

She frequently spoke of dying, saying,
"`I long to be in my Saviour`'s arms;--there are
no terrors in death to them that love God.`"
After alluding to the kindness of her parents, she observed,
"`I shall not feel the lack of father or mother in heaven;
my Saviour will be all in all.`"

Her uncle and aunt being about to return home, she took leave of them,
and desired her love to be given to her cousins, saying,
"`Tell them to be good girls and seek the Lord early, and they will surely find Him.`"
On another occasion, "`I am sure that I love God, because he is good-good to me;
He has given me many good things; He preserved me, and he has forgiven my sins;
I am sure that I love God with all my heart.`"
A friend praying with her, she desire him to pray for other little children also,
that they all might become good and be happy:
Being asked whether she felt assured of going to heaven; she said:
"`I think I cannot be deceived--I think I shall certainly go to heaven,
because I love God with all my heart and mind.
He will never cast off any who love him so much Inquiry
being made whether she had thought of God that morning,
she replied, "`O! yes, I love Him, and have been thinking of Him with pleasure.`"

The rehearsal of the following lines afforded her much satisfaction:

[verse]
____
Hope wipes the tear from sorrow`'s eye,
And faith points upward to the sky:
The promise guides her ardent flight,
And joys, unknown to sense, invite
Those blissful regions to explore,
Where pleasures bloom to fade no more.
____

While having her apparel changed,
she remark "`I shall not need clothes much longer--I shall soon
be clothed in the robes of the Saviour`'s righteousness`" and,
at another time,
"`I shall soon be in that happy place--soon shall rest my head on my Saviour`'s bosom.
Why are His chariot wheels so long in coming.`"

It being observed to her that she had lost much sleep in her sickness, "`Yes,`" said she,
"`but

[verse]
____
In wakeful hours of night
I call my God to mind.
____

By her request a number of her companions were sent for,
whom she addressed with much tenderness gave them good advice,
and bade them an affectionate farewell.
Being in great distress of body, she said, these are pleasant groans to me,
for they are the last,`" and then repeated these lines.

[verse]
____
Jesus can make a dying bed
Feel soft as downy pillows are,
While on his breast I lean my head,
And breathe my life out sweetly there.
____

To those who stood around her dying bed, she said,
"`I wish you were all as happy as I am,`" and frequently
mentioned her prospect of future felicity,
saying, "`Come, Lord Jesus, come quickly--Lord Jesus receive my spirit.`"
After alluding again to the peace and joy which she felt,
she quietly fell asleep in the Lord Jesus.

[.asterism]
'''

WILLIAM TYLER BARLING, of Witham, Essex, England; died 24th of tenth month, 1839;
aged ten years.

This dear child was naturally of an affectionate and tractable disposition;
and though before his illness not remarkably serious,
he showed at times much tenderness of conscience When between five and six years of age,
on returning one evening from a visit, his mother observed him appear dejected,
and asked him if he had been good.
He said, "`No; please take me to (naming a friend.) I am so unhappy;
I met with an accident, and did not tell her; I cannot go to bed.`"
His mother went with him, and he directly told the friend what he had done,
and asked her to excuse him.
When he returned home and was put to bed, he told his mother he was very sorry,
and hoped he should not make her unhappy any more.
May those little children who read this account, be induced to follow his example.

A short time before he was confined to his couch,
he lost a little friend to whom he had been much attached;
and whose illness and death made a deep and lasting impression upon his mind.
At about seven years of age, he was visited by severe illness;
it was succeeded by a spine complaint, which, with little exception,
confined him for nearly four years to his bed or couch.
During this period his sufferings were at times very great;
but it pleased his heavenly Father to render this affliction the
means of his becoming a remarkable instance of early piety.
He was made willing to bear his privations with cheerful patience,
and sweetness of spirit; evincing the sufficiency of divine grace, which enabled him,
while yet a little child, to love his Saviour;
and by his meek and quiet submission to pain and suffering,
to be a striking example to those around him.
He passed the greater part of his long confinement
in pursuing different branches of study,
and was particularly interested with books of geography, or of voyages and travels.
Those of a trifling and unedifying nature he invariably declined,
having no relish for them.
But his favourite occupation was reading the Holy Scriptures,
which was his constant daily practice as long as he had strength to do so.
He would have his Bible by his bedside, and read a portion to himself,
the first thing after he awoke in the morning,
unless he was interrupted by others being in the room;
in which case he would wait until he was left alone.
It was with difficulty he could manage to write, yet he occasionally penned memorandums,
a few of which are here inserted.

[.embedded-content-document]
--

Eighth month, 1836.--I have now begun to read the Scriptures regularly.
I trust Providence will enable me to understand what I read.

Eleventh month 26th.--I am eight years old today.
O God!
I should very much like to be a better boy, and more patient and good than I now am:
be pleased to help me, O Heavenly Father!

Third month, 1837.--I was born in Kensington, in the year 1828,
on the 26th of the Eleventh month.
I lost my father when I was about two years old.
Some months after he died, we went to Witham, and from there to Colchester,
where we now reside.
I have one brother; and my dear mother keeps a school.
I have been more than a year in bed; I am very happy.

Eighth month 1st.--What is life?
`'tis but a vapour, soon it vanishes away.

Eleventh month 26th.--I am nine years old today; I feel stronger than I did last year,
for which I hope I am thankful.
I trust it will please Providence to make me a good boy;
and willing patiently to bear and suffer what He thinks right.

Second month, 1838.--"`Rejoice evermore; pray without ceasing;
in everything give thanks; for this is the will of God in Christ Jesus concerning you.`"

Eleventh month 25th.--First-day; tomorrow will be my birthday.
Providence has been pleased to add many favours and mercies during the past year,
for which I hope to be thankful;
and I hope my Heavenly Father will enable me to resist the temptations of the evil one,
and also to spend this year better than the one which is past; and may myself,
and my dear mother, and brother, and everybody,
increase in all good things spoken of in the Bible.
And may it please, you, O Heavenly Father! to protect and direct me,
in the way you would wish me to go, now and ever.

Twenty-seventh.--Our Saviour Jesus Christ said,
'`Permit the little children to come unto me;`' I
hope I am one of those that come to him.

--

The last memorandum he penned was occasioned by reading Sewell`'s History of Friends,
in which he was much interested.
The memorandum was left unfinished, viz:

[.embedded-content-document]
--

Eighth month, 1839.--When reading the lives and sufferings of some of our ancient Friends,
I cannot help feeling sorry that we differ so much from them in manners and appearance;
and I am ready to fear that if we were called upon to bear--

--

Here he laid down his pen, but from the tenor of what he has written,
we may infer what he designed to add.
About this time he requested his mother to let his clothes be made plain,
thus showing his conscientious desire to do right, even in little things.

For some weeks prior to this, he had spent most of his time upon an inclined couch,
instead of lying on his back;
owing to this change his health had derived decided benefit,
and he was able to read and write with greater ease.
It was about this time that, one morning,
this beloved child requested his mother and the servant
to lead him to the side of the bed,
and leave him a short time, which they did.
On going again into the room, his mother found him on his knees in tears.
He directly said, "`Dear mother, I am sorry to make a display of what I have been doing,
but I am too weak to rise from my knees without assistance;
and I felt so overcome with the goodness of the Almighty in restoring me thus far,
that I dared not go downstairs until I had thanked him on my knees for all his blessings.`"
His health now so much improved,
that his mother ventured to indulge the hope of seeing him restored to his natural strength,
but Divine Providence had ordered otherwise; and having made him fit for a better world,
was pleased to call him early to enjoy his everlasting inheritance.
While staying by the sea-side at Walton,
his brother and he were seized with scarlet fever.
At the commencement of his illness, he expressed his belief that he should not recover,
and though at times suffering most severe pain from the violence of the complaint,
as well as from the means used to subdue it,
he evinced an exemplary patience and submission.

About a week before his decease,
on his mother asking him if he thought he should recover, he said, "`No, dear mother!
I believe I am going to heaven.`"
On being asked if he wished to live, he said,
"`He had hoped to be a comfort and a support to his mother, and to do good,
but for nothing else.`"
Soon after, he told his mother to whom to give all his books; and then said, "`To you,
dear mother, I give my Bible; I love that, and I love you more than I can tell you.`"
Many times, when sensible, he tried to read his Bible, but could not;
and when thus unable, from weakness, would request his mother to read to him.
Those about him frequently heard him praying for patience; and he several times said,
"`Don`'t grieve, dear mother, there are many more ill than me.`"
When suffering such extreme pain that he could hardly keep a limb still,
if his mother sat down and read a chapter from the Bible to him,
he was enabled to be calm and quiet; so strikingly did Divine grace,
in this interesting child, triumph over his bodily sufferings.

On First-day night, the 20th instant, on being asked if he felt comfortable, he said,
"`O yes! dear mother, I have nothing to do;
I have long thought my time in this world would be short; don`'t,
oh please don`'t grieve.
God will comfort you; he makes me feel so happy.`"
On Second-day, he said sweetly, "`No more tears, no more sorrow,
no more crying,--all bliss.`"
Soon after, on being turned round, he looked at his mother with an imploring expression,
and said, "`Dear mother, let me go where angels go;
oh let me go where angels go,`" three times.
In the night he repeated the hymn, "`Go when the morning shines,`" etc.
During Third-day he was drowsy; at night he asked his mother to sit on the bed,
and read to him, which she did.
Between one and two o`'clock, he became worse,
and requested his brother to be brought in, of whom he took a most affectionate leave,
as he did of his mother and an attendant.

On Fourth-day afternoon, the 23rd, the pain was as violent as nature seemed able to bear;
yet through all he continued patient, and requested those about him to be still.
When the pain was a little subsided, he called out: "`Oh, mother, mother!`"
On her going to him, he said very faintly, "`better now,`" and soon after added,
"`I am ready; oh, let me go where angels are.
Oh, please.
Heavenly Father, take me now!`"
In a little while, with his eyes turned upwards, he said with much earnestness, "`Oh,
yes, dear Joseph John, I am coming; it will soon, soon be over.`"
About seven o`'clock, on being told the servant was come to take leave of him,
he put out his hand, and said, "`Farewell, Mary, I am going; be a good girl; think of me:
read the Bible: and oh! really pray.`"

The difficulty of breathing now increased; he scarcely spoke till about twelve,
when he exclaimed, "`Farewell all; I am going to glory, glory, glory; please.
Heavenly Father, take me now!`"
For some time, those about him could only tell what he said,
by watching the movement of his lips.
At last he exclaimed, "`It is all over--victory! victory! victory!
Oh, holy!`"
Then his happy spirit departed from all pain and sorrow,
to be forever with his Lord and Saviour, who had so remarkably,
in the case of this beloved child,
exemplified the blessed effects resulting from obedience to his gracious invitation,
"`Permit the little children to come unto me, and forbid them not.`"
His remains were interred at Colchester, on the 27th,
in the same grave that contained his former little friend, Joseph John Cross.

[.asterism]
'''

RUTH MIDDLETON, daughter of Samuel and Rebecca Middleton, of London,
died of consumption in the twelfth year of her age.
She was a child of innocent and orderly deportment,
careful to live in the fear of the Lord, and when attacked with illness,
the fear of death was taken away and an evidence
mercifully granted that her sins were forgiven,
and a place prepared for her in the mansions of unfading bliss.

The prospect of parting with this beloved child was
a source of great affliction to her mother,
which Ruth observed, and on one occasion said to her, "`What is the matter,
my dear mother?
do not sorrow for me, I shall be happy.
It is the Lord`'s will that I am thus afflicted, and we must be contented.
You know that Abraham was willing to offer up his only son Isaac, and you do not know,
if you could freely give me up, but that the Lord might spare me a little longer to you;
and if it be His good pleasure to take me to Himself, His holy name be blessed forever.`"

Being asked how she was, she replied, "`But indifferent--yet I am well satisfied,
for it is the will of God that I am thus afflicted,--O, my dear mother,
I should be glad if you could freely give me up.`"
When about to compose herself for sleep, she prayed thus, "`Our Father who is in heaven,
hallowed be your name; your kingdom come,--your will be done in me as it is in heaven--O,
Sweet Lord Jesus, feed me daily with the bread that comes down from heaven.
And, Lord, if it be your will, grant that I may sleep to refresh this poor needy body;
but you, Lord, know what I stand in need of, better than I can ask--Lord be with me,
and my father, and my mother, and brother.`"
On awaking from refreshing sleep, she gratefully acknowledged the favour,
and vocally returned thanks to her heavenly Father, saying,
"`blessed and raised be your holy name, O, Father of life,
for you have heard my desires and answered me, for I have slept sweetly.`"

At another time she said, "`The Lord said to His followers,
"`Permit the little children to come unto me, and forbid them not,
for of such is the kingdom of heaven.
And if I be not happy, what will become of ungodly men and women,
for truly I am afraid of offending any body, for fear I should offend the Lord.`"
A friend expressing a hope that her mind was still directed to the Lord, she answered,
"`Although I can hardly speak, yet I think upon the Lord,
and He knows my thoughts and answers them.`"
Again, "`It will not be long before I shall be at rest and peace,
where there is no more pain to the body nor to the mind,
and where there is nothing but joy forevermore.
My dear mother, be willing to part with me, for I am willing to part with you all.
I am not at all concerned for myself, but for you, my poor mother, who do,
and will make your bed a bed of tears for me.`"

Doubts being expressed as to her recovery, she answered with earnestness, "`O,
what the Lord pleases; for I am not afraid of death.
I never wronged anyone of a pin, to my knowledge, nor loved to make excuses.
I never told a lie but once,--when I should have said yes, I said no,
which has been a great trouble to me; but the Lord, I hope,
will forgive me--for I called the maid and told her the truth.`"

The night before her decease, a friend having prayed with her, she remarked,
"`I understand well, and am inwardly refreshed.
I am sorry I cannot speak so that the friend could hear,
or else I would give an account of my inward peace
with the Lord.`"--Her voice was very weak and low;
but a few hours before her close, she was heard to pray thus, "`O, Lord,
withhold not your tender mercies from me at the hour of death.
O, Lord,--let your lovingkindness continually preserve me.`"
Soon after, "`I desire to slumber; but if I die before I awake,
I desire the Lord may receive my soul.`"

She was thankful for the tender care of her mother,
and took an affectionate leave of her, saying, "`Farewell, dear mother,
in the love of the Lord, farewell.`"
Then asked for her brother, and bidding him farewell, desired him to be a good boy.
Her father inquiring how she felt, she answered, "`I am just spent.
I am very easy and shall be very happy,--my body is full of pain,
but the angel of the Lord is with me, and His presence will forever preserve me.`"
She then took a last farewell of all her connections and friends present,
and peacefully departed to her everlasting rest in heaven.

[.asterism]
'''

HANNAH HILL, daughter of Richard Hill, of Philadelphia,
was endowed with good natural abilities, of an amiable and forgiving temper,
sober and courteous in her behaviour, and an example of piety,
humility and obedience to her parents.

When very young, her mind was visited by the spirit of Christ,
and being obedient to its requirings, she grew in grace and religious experience.
Her conduct was instructive, adorned with modesty, gravity, and good sense,
and free from anything like levity or jesting.
She was fond of reading,
in which she spent much of her leisure time instead of running to play with other children;
and took particular delight in perusing the Holy Scriptures,
and other works of a serious character.
The circumspection and watchfulness of her conduct,
the solidity and innocence which clothed her mind, and the maturity of her judgment,
rendered her society pleasing to her acquaintances, and afforded a bright example,
both to the youth and those of riper age.

In her twelfth year, she was seized with a violent disease,
which increased so rapidly that in a few days her life was despaired
of Notwithstanding she had lived in so exemplary a manner,
yet, during the first few days of her sickness,
her mind was under great exercise respecting her future state; frequently exclaiming,
"`Am I prepared--am I prepared?
Oh! that I might die the death of the righteous,
and be numbered with those at the right hand.
O, Almighty God, prepare me for your kingdom of glory.`"
She earnestly entreated those around her to help with their prayers,
that her passage out of time might be made easy.
A friend present kneeled down and prayed, during which time,
notwithstanding her extreme pain, she laid very still, with uplifted hands and eyes,
and appeared to be very attentive.

Soon after this, the conflict and anxiety of her mind was mercifully removed,
and in the assurance that her sins were forgiven and a mansion prepared for her in heaven,
she was very willing to die, saying to her father, "`I shall die,
and am now very willing;`" and after a little while prayed, "`O, most glorious God,
now give me patience, I beseech you,
with humility to bear what it shall please you to lay upon your poor afflicted handmaid.`"
She now entirely made death her choice, and would often say,
she had rather die and go to God, than continue in this world of trouble; adding,
"`When will the messenger come?
O, hasten your messenger!
Oh! that I could launch away like a boat that sails, so would I go to my dear brother,
who is gone to heaven before me.`"

Doctor Owen coming to visit her, she desired him to sit down by her, and said,
"`All the town knows you are a good doctor; but I knew, from the beginning,
that I should die, and that all your endeavours would avail nothing.
The Lord has hitherto given me patience, and I still pray to him for more,
that I may be enabled to hold out to the end; for my extremity of pain is very great.`"
She earnestly requested her parents to give her up freely to the will of God,
observing that it would be better both for them and for her to do so;
and when she thought she had prevailed, she added, "`Now I am easy in my mind.`"

Some of her attendants encouraging her with hopes of recovery, she said,
"`Why is there so much ado about me, who am but poor dust and ashes?
We are all but as clay, and must die.
I am going now, and another next day, and so, one after another,
the whole world passes away.`"
Taking leave of one of her friends,
who said he "`would see her again tomorrow,`" she replied, "`You may see me,
but I shall scarcely see you any more--though I will not be positive--
God`'s will be done.`"
Observing that those about her were sorrowing at the prospect of her dissolution,
she inquired very sweetly, "`Why are you troubled and weep,
seeing I am going to a better place!
O, that the messenger would come--that my glass was run.`"

The acuteness and long continuance of her bodily sufferings
induced her to fear that the Lord was
offended with her, which was a source of additional suffering;
but it pleased her heavenly Father to remove these doubts which she thankfully acknowledged,
saying, "`I think the Lord has showed me that I do not bear all this for myself only.
Glory be to His infinite name, there is nothing can be compared to Him.`"
When the first day of the week came, she desired that her cousins might go to meeting;
"`for it may be, said she,
that the Lord will be displeased if all the family stay
at home,`" and she desired them "`not look on one another,
but to wait on God.`"

Her prayers were frequently put up to God,
humbly beseeching that He would be pleased to grant her patience,
and refresh her soul with living water which might spring up in her unto eternal life.
It pleased the Lord also to clothe her mind with entire resignation to His blessed will;
she often said, that she was freely given up to submit to it, whether for life or death;
and not long before her decease,
she told her father "`the Lord had assured her that she should be happy.`"
It was observed that such an assurance was comfortable indeed, "`Aye,`" said she,
"`this is matter of joy and rejoicing can my soul say by living experience.`"

Taking leave of her sister and a cousin, to whom she was tenderly attached, she said,
"`Dear sister, my desires are that you may fear God; be dutiful to your parents;
love truth, keep to meetings, and be an example of plainness.`"
To her cousin, "`Be a good boy; observe your uncle`'s and aunt`'s advice,
and the Lord will bless you.`"
She spoke several times respecting the manner of her interment,
desiring that certain persons might be invited, and commending her spirit to God, saying,
"`Glory--glory--glory`"--as with the sound of a hymn,
she triumphantly departed out of time,
and joined that happy company of redeemed children,
whose spirits always behold the face of our Father who is in heaven.

[.asterism]
'''

ELIZABETH MERRITT was born in Dutchess county, state of New York, in the fourth month,
1807.
She possessed an amiable and affectionate disposition,
and an extraordinary tenderness toward every animated object around her;
and being attentive both to the voice of heavenly
wisdom and the instructions of her care-takers,
she attained a remarkable judgment in spiritual as well as natural things.
Being fond of learning, she soon began to read and took great delight in her books,
often leaving the company of her little associates for the sake of perusing them.
Before she was five years of age, she had, of her own accord,
selected and committed to memory the speech of the apostle Paul before king Agrippa;
and having remarked to her parents, that she thought it a very extraordinary one,
she repeated to them the first twenty-two verses.
Thus early was her susceptible mind imbued with the love of the sacred volume.

When about nine years old she was taken ill and brought so low
that her life was despaired of While lying in extreme pain,
she frequently appeared to be engaged in supplication;
but her tongue was so much swollen that her words could not be distinctly understood.
She recovered from this attack, and as her bodily strength was renewed,
her faith seemed to be more firmly established on the "`Rock of ages,`" her deportment
manifesting that she was seeking a kingdom not of this world--that is a heavenly.
She was desirous of attending religious meetings, and her conduct when there,
was solid and exemplary,
and some who were older than herself have been reproved by her for misbehaving there,
as well as on other occasions.

She was taken ill at Friends`' boarding school at Nine Partners,
on the 29th of fourth month, 1818; and, as her disease appeared dangerous,
she was removed to the house of her uncle, and her parents sent for.
Upon their coming and finding her very ill, they were much affected, which she observed,
and said, "`O, mother, don`'t weep.
I want you to be reconciled to your lot,
be it what it may--it is what we all have to pass
through--I feel perfectly willing to die,
perfectly resigned.`"
A few hours after this,
she informed her mother that she did not feel so happy as in the morning,
and being asked the cause, replied, "`Oh! my sins--my sins!`"
She was then engaged in supplicating the throne of grace,
but in so low a tone of voice as not to be perfectly understood--there is cause, however,
to believe that He who hears the prayers of the sincere penitent,
was pleased to forgive her sins for Christ`'s sake,
who died for her and offered up his precious life a sacrifice for sinners.

The next day, she many times expressed her resignation to the divine will,
and on her mother`'s manifesting some uneasiness
that the doctor did not come so soon as was expected,
she said, "`There is but one Physician that can help me.`"
On third day morning her bodily distress was extreme,
and she several times remarked that "`her pain was greater than tongue could tell,
and if we knew how she felt, we would pity her`"--adding,
"`O mother--supplicate my heavenly Father to relieve
me from my pain`"--and in a few minutes after,
she was herself engaged in prayer for a considerable time,--the following,
is all that could be recollected--

[.embedded-content-document.prayer]
--

O, gracious Father! be pleased to relieve your poor afflicted child,
and do with me what you see fit--Remember your afflicted child,
who suffers more than tongue can express.
Please to look down upon me,
who am in your hand and whom you have helped from time to time, as you have seen best.
O, merciful Father! look not on me alone,
but on all your afflicted children wherever they are,--not
only on those who stand strewing their tears around my bed,
but on my dear brothers and sisters and the rest of the family who are at home.
I have been wonderfully tried since lying here, in looking around,
and freely strewing my tears on my pillow, for those dear children, the world over,
who are advancing toward their everlasting home,
without a knowledge of the blessed Truth;
and in prayer that they may not remain in darkness forever and ever.
O, gracious Father!
I pray you remember my dear parents who are mourning by me.
Make them to rejoice in your righteous Son, and crown their heads with glory.
O,
most merciful Father! be pleased to remember them while advancing in years--be
their strength in weakness and support them in all their trials,
for it is unto you alone they have to look, both now and forevermore.

--

Addressing her parents, she said, "`Trust in the Lord and keep his commandments;
then will you be good examples to your children,
and be crowned with glory when your heads are covered with gray hairs.`"
To her brother, "`And now, my dear brother, let me impress upon your mind this language,
'`Remember your Creator in the days of your youth.`' Now while you hear me speak,
stamp these words on your heart: write them as with iron,
so that you will remember them when we are separated, never to see each other more,
but in happiness, where I hope to see you all.
Remember me to my dear brothers and sisters at home,--tell
them what you have heard and seen--tell them,
from a sister that loves them, that they must be good children,
and then they will bring a crown of glory on themselves and their parents.
And do get the Bible, all your leisure moments you have,
and read while your little sisters and brothers are sitting by the fireside,
and not only read, but try to understand what you read, so you will be a help to them,
and a bright shining light to others.
Try to help your sisters out to meetings--and take your little brothers,
one by one hand and the other by the other,
and lead them to meeting--not only go to meeting, but know what you go for,
and worship in spirit and truth--that you and your sisters and brothers,
may experience a being washed and purified in the blood of Jesus.`"

After this she appeared very quiet in mind,
manifesting entire resignation to the will of her heavenly Father,
whether in life or death; and taking leave of her relations,
she departed this life the 14th of 5th month, aged about eleven years.

[.asterism]
'''

PEACE RING died at Bedminster, near Bristol, England, the 12th of the 6th month, 1825,
aged eleven years.

His disposition was meek and affectionate,
which endeared him to his friends and relations.
In the beginning of the year 1825,
he was attacked with cough and hemorrhage from the lungs,
with other distressing symptoms indicating the approach of consumption,
yet as his sickness became worse,
he was mercifully favoured with increased resignation to the will of his heavenly Father.

On the 27th of the month, apprehending that he should not continue much longer,
he called the family to his bedside,
and in the most affectionate manner took leave of them all.
His mind appearing to be deeply affected on his own account,
he uttered the following prayer, "`O most gracious Being,
forgive all my sins which I have committed in this
wicked world:`" and then repeated the Lord`'s prayer:
adding "`I am going--pray for me, all of you pray for me.`"

At another time he expressed, "`O, that I may go to the mansions of rest--O,
you most gracious Being your will be done.`"
His sister expressing a belief that he would go to heaven, he said,
"`I hope I shall;`" hope the Lord has forgiven my sins, and that I shall meet you there,
in the presence of God.`"

Under all his bodily sufferings,
he evinced an extraordinary degree of resignation to the Lord`'s disposal, saying,
"`I will bear whatever the Lord chooses to lay upon me.`"
On one occasion he said,
"`Oh! that I had never told a lie to grieve that
great Being--Oh! that my sins may be forgiven;
gracious Father, take me to the realms of bliss.
O, most gracious Being, I am ready when you may choose to take me.`"
A little after, in allusion to the heavenly kingdom,
and as if he had a foretaste of blessedness and felicity, he exclaimed,
"`O that beautiful place where peace reigns and happy spirits dwell!`"

Some time after, he addressed his parents, "`O my dear father and mother,
I don`'t know how to give you up--but the Lord`'s will be
done--bless the Lord O my soul Hallelujah--praise the Lord!`"
Again, "`Heavenly Father, keep me--praise the Lord, O my soul!`"
On the following morning, he said to his brother,
"`The Lord can strengthen me if he chooses, but his will be done;
that great Being has answered my prayers.`"
Being told he was a God who not only heard but answered prayers, he replied,
"`I have found it so many times.`"
About two weeks after, he departed this life.

[.asterism]
'''

MARY SAMM +++[+++grand-daughter of William Dewsbury]
of Bedfordshire, aged about twelve years,
being taken unwell was under great concern of mind respecting the condition of her soul,
and frequently retired alone, weeping in secret before the Lord.
Her aunt observing this, inquired the cause, to which she replied,
"`I am troubled for lack of a full assurance of my eternal
salvation,--not anyone knows my exercise but the Lord alone,
what I have gone through since I came to Warwick.
It was begun before I came, but it was then small.
I thought I should not live long; and that, if I died,
I did not know where my soul would go.
But I hope the Lord will give me satisfaction +++[+++herein]
before I die.
Though it is but hope, yet for this my soul shall praise His name forever.`"

Not long after this, she received a greater assurance of future happiness;
and some of her friends being in the chamber, she said to them,
"`I have been twice nigh unto death; but the Lord, in his tender mercy,
prolonged my days, that I might seek His face in the light of Christ,
and come to be acquainted with Him before I go hence.`"
Again, "`If this distemper does not abate, I must die;
but my soul shall go to eternal joy;
eternal and everlasting life and ace with my God forever.`"
At another time she said, "`They that live longest endure the greatest sorrow--therefore,
O Lord, if it be your will, take me to yourself,
that my soul may rest in peace with you.`"

On the following day, she desired all to withdraw from her room, that she might be alone;
and after a considerable time, her mother and grandfather went in again, when she said,
"`I have now received full satisfaction of my eternal salvation--it
is now done--it is now done--I am very willing to die,
that the Lord may glorify His name this day, in His will being done with me.`"
She frequently prayed to the Lord for his gracious assistance, saying, "`Help me,
O my God,
that I may praise your holy name forever,`" and when one advised her to avoid speaking,
probably from a fear that the exertion might injure her, she said "`I shall die;
and I cannot but praise the name of the Lord while I have
a being,--I don`'t know how to praise Him enough.`"

Her grandfather inquiring how she felt, she answered,
"`I have had no rest tonight or today--I did not know but I should have died this +++[+++last]
night, but very hardly I got through it.
I shall die today--and a grave shall be made and my body put into it,
but my soul shall go into heavenly joy, and to everlasting peace.`"
Soon after expressing these words, being in a quiet and heavenly frame of spirit,
she yielded up her breath to Him who gave it,
and entered into that glorious rest which is prepared for the righteous.

[.asterism]
'''

ELIZABETH WILLS, daughter of Daniel Wills of New Jersey,
being attacked with severe illness was earnestly engaged in prayer to God,
that He would be pleased to be near by His holy spirit and
support her under the exercise and suffering which she endured.
Being mercifully favoured with an answer to her prayers,
she broke forth in grateful commemoration of the Lord`'s goodness, in this way,
"`Now I am well--Lord God of power and glory! all power,
glory and honour be given to you forever, amen!
You have helped me--O glorious God of life, you have eased my heart.
O, praises, and glory and honour be given to you forever.
O, God of eternal glory, what shall I say unto you--all praises be given unto your name,
for you have helped my soul:
praises forever be given unto you--forever--and forever--Amen.`"

She expressed much more to the same import,
tending to the praise and glory of her Creator,
and indicating the gratitude and love which filled her heart or his mercies,
often saying, "`God is good; He has touched my heart.
Now I am well; I feel no pain; I am willing to live, or I am willing to die.`"
She took an affectionate leave of her parents, brothers and sisters,
desiring that they might not improperly grieve at her removal;
and asked for a servant lad whom she knew to be negligent in his duty;
and he being absent, she requested to see him as soon as he came home.
On his return, she steadfastly looked on him and said,
"`God gave me much to speak last night and you were not here.
It were better for you that you should walk with God.
You must die as well as I: you must go down to the grave as well as I,
and if you do not do better you shall have torment, and I shall have peace.
It would be better for you if you would walk with God.
Time that is past and gone cannot be recalled.
Is it not better for you to do well than ill?`"
She died in great peace with the Lord, aged twelve years.
