== Chapter 4

[.chapter-synopsis]
* Ann Knight
* Ann Hughes
* Lydia R. Smith
* Susannah Whitrow
* Priscilla Cuthbert
* Peter W. Hall

ANN KNIGHT, daughter of Edward and Martha Knight, of great Bardfield, Essex, England,
died the 20th of the 4th month, 1806, in the fifteenth year of her age.

She was the eldest child of a numerous family, to whom she was an example of piety.
She preferred the company of those advanced in years,
to the amusements which commonly engage children,
and evinced more than ordinary maturity of understanding.
It was her practice when retiring for rest, to examine her conduct during the past day,
and if any occasion of regret occurred,
she was not satisfied to go to sleep until she felt that peace
of mind which accompanies sincere repentance and forgiveness.
On one of these occasions, her mother going to the bed side, found in her tears,
and inquiring the cause, she replied, "`On looking over the day,
I find I was out of temper, and too cross to my little sister.
I cannot go to sleep until I find forgiveness; and, dear mother,
I hope you will forgive me also, and then I can go to rest and sleep sweetly.`"
It should however be remarked,
that few children were more uniformly affectionate
toward their younger brothers and sisters,
or used more tender and prudent endeavours to compose their little differences,
so that she was early entitled to the blessing pronounced upon the peace-makers.

Returning in ill health from the house of a connection, she remarked to her father,
that she once thought she should like to dress as others did, "`but now, said she,
it is all done away--I have no desire for it`"--adding, what pleased her parents,
would please her,
and that she was very sorry to observe some of her relations
run out in dress and deviate from the plain language,
and from their profession.
"`They will find, said she, that it will not bring peace of mind.`"

In a few days after this she was confined to the bed, and said to her parents,
"`I thought I should like to have stopped a little longer with you,
if it had been the Lord`'s will.
It is hard parting with you, but I hope I shall be resigned,
you are very near and dear to me, but the Lord can make hard things easy.`"
It was replied that he had many times done this for her; to which, with much emphasis,
she answered, "`That he has--and I feel easy--I feel nothing to burden my mind,
and this is a favour--but I hope I shall see my way clearer before I go.`"

About two weeks before her death, two of her brothers coming to see her,
she exhorted them to fear the Lord and to keep to plainness in language and dress,
saying, "`If you do not,
it will bring a burden on your minds--I do not accuse you--but
I know the enemy is very busy to draw away the mind,
if you do not keep a watch.`"

Addressing her parents, she said, "`I hope you will give me up to the Almighty`'s will.
He is not a hard Master, but a tender Father to his children that obey Him.
I have felt Him underneath, many times, to keep me,
when the enemy has been endeavouring to draw me aside from my watch;
both when in meetings and out +++[+++of them.]
But blessed be his holy name, He has preserved me,
and He will also preserve you if you obey Him.`"

She mourned, as has already been mentioned, over some of her connections, who,
she thought, indulged too much in dress,
and desired her father to write down what she had to say respecting it,
that they might be made acquainted with the grief she felt
that they should waste so much of their precious time.
"`They will find,`" said she,
"`that it will not bring them peace of mind at such a time as this;
and they know not how soon they may be brought as weak as I am.`"

At another time she lamented the vanity and luxury of the world;
remarked how the bountiful Giver had provided food and clothing for all,
if it were rightly used,
and particularly regretted the extravagance of dress
in such as frequented balls and assemblies.
"`This is a world of trouble,`" said she,
"`and I am freely given up to leave it this night,
if it be His will,--as freely as I can sit by that fire-side.
Eternity is awful; but I hope and believe I shall be happy.`"

Towards the close of her time she suffered much pain, which induced her to say,
"`I hope patience will hold out.
Dear father and mother pray for me, that patience may hold out.`"
It was her earnest desire to be released if it was consistent with the Lord`'s will,
yet in entire resignation she added, "`I hope I shall not be too anxious to be gone.`"
After a violent paroxysm of pain she laid still for a considerable time, and then said,
"`The Lord has been with me while I lay still.
I was so comfortable I thought I was in heaven.
I was so happy--happy.
Praised be His name forevermore.
I cannot praise him enough, He has been so gracious.
I was in hopes I was going--pray do not hold me--I fear you hold me.
If my pain come again, I know not what I shall do lest I should murmur,
and that would be a sad thing.
Now I am happy--I hope patience will hold out.`"

A few days before her departure she called her mother and said,
"`I have something to tell you.
This has been a blessed night to me.
I have seen heaven; and they are all happy--happy--there.
The Almighty has been so near me.
I thought he bid me take leave of all the world, which I can freely do,
to possess that peace and happiness which I have seen--yes,
for the lowest place in heaven; the things of this world signify nothing to me--no,
not in the least.
No matter what becomes of this bit of clay, when the spirit is gone to heaven.
Do not put yourselves to much expense in burying me.`"

After this she had a convulsion fit, and on reviving from it, said,
"`I thought I had been going; but I could not go without once more praising the Lord.
Where are the dear children?
Bid them fear the Lord and love the Lord Jesus.`"
The day before her death she remarked, "`It is seventh day again,
and I am here yet--I want to be gone;
but hope I shall have patience to wait the Lord`'s time--that is the best time.`"
She desired her parents to pray that she might have an easy passage,
which petition seemed to be granted.
She fell asleep for a few minutes, and without a sigh expired.

[.asterism]
'''

ANN HUGHES, daughter of Thomas Hughes of Clonmel, Ireland,
deceased the 29th of 9th month, 1820, aged nearly fifteen years.

She took cold in the 2nd month, 1820,
and in a short time symptoms of consumption appearing,
the physician recommended a change of air;
but as her health did not improve she returned home in the 7th month,
and continued from that time gradually growing weaker until the 29th of 8th month,
when she was attacked with a slight hemorrhage from the lungs.
Two days after, a repetition of the same symptoms with increased violence,
occasioned some alarm,
and in the evening of that day a friend had a religious opportunity in her chamber,
which,
with the aforementioned occurrence seemed to impress her mind with the awfulness of
her situation and the great uncertainty of her continuance in this state of being.

On sixth day night, the 22nd of ninth month,
she was seized with a third and more copious discharge of blood
from the lungs--so great as almost to produce suffocation;
and although the circumstance was affecting to those around her,
she was mercifully favoured with calmness and fortitude, saying to her father,
although she could only speak at intervals and with difficulty,
from the effusion of blood,
"`Don`'t be alarmed--I feel easy--perfectly easy--my mind
is very calm--I have a kind Providence who is good,
very good to me--I hope soon to be in heaven.`"

At another time she said, "`O,
what a good thing it is for people to mind their places of worship.
I often went to meeting and came home again, as poor and empty as I went there;
but now I see the difference.`"
A short time before her decease,
she had a visit from two of her relations who indulged considerable taste for dress.
She said but little while they stayed;
but after they were gone appeared a good deal affected, and remarked to her father,
"`I have often thought upon the folly of dress,
but I think I never saw so plainly the foolishness of it as I now do.`"

During the latter part of her illness,
she spent much of her time in reading the Holy Scriptures and other religious books,
and made it her practice to have a few chapters of
the bible read to her after she was settled in bed,
and would sometimes ask to have it read during the night.
She was entirely resigned to the approach of death,
and mentioned that she had no wish to live,
though it was trying to part with her connections; saying,
"`I am going to leave a good earthly father,
but I am going to a very--very-good heavenly Father.`"

On first day, the 24th, symptoms of dissolution were apparent.
Though most of the day a death-like coldness pervaded her enfeebled frame,
but in the evening she revived a little, and requested to have the bible read, saying,
"`I think it comforts me; read in the New Testament about our Saviour,
that I may try to get some instruction.`"
Observing that her father grieved at the prospect of parting with her, she said,
"`I don`'t like to see you so,
or any of you--I think you ought all to be glad to give me up--I
am going early from a world of snares and temptations.`"

On fourth day, several of the family standing about her bed she broke forth very sweetly,
"`He that was with Moses in the burning bush, the great I AM, is a present help.
I often admire at His goodness who has made my cup, as it were to overflow;
and though at times I feel empty,
I know it to be the work of the enemy--I am going a short road to a beautiful mansion.`"
On perceiving her brother John, who had come to her bed side, she said to him,
"`I hope you will mind and grow steady, and not try to please the world,
for that is all vanity; but take up the cross and despise the shame.
No cross--no crown--that is true;
without we take up the cross we cannot win the crown--I
have often thought there was a great deal in these words,
No cross--no crown.
I feel a great deal of love for you all.
I hope to be happy through the mercy of my Redeemer--He is strong and powerful.`"

On the following day, a friend inquiring how she was, she replied,
"`Middling--but I am finely in mind,
and what is the body to that--I never thought I was good enough to be cared for.
I have been cleansed and purified in the fire.
I hope it is not presumption; but I feel very easy.
I do not like to complain, when I think of our Saviour`'s sufferings,
and many others we read of.`"
The following day she quietly passed away from time to a blessed and happy eternity.

[.asterism]
'''

LYDIA R. SMITH, of Smithfield, Rhode Island, deceased the 29th of eleventh month, 1821,
in the fifteenth year of her age.

Her disposition was lively, her apprehension quick, and her temper kind and forgiving.
She early evinced a nice sense of right and wrong,
and her tender mind was grieved with the evils she saw,
especially the sin of intemperance.
She loved to read books of a religious character and to attend meetings for divine worship,
and manifested a strong dislike to the vain fashions and customs of the world.
When attacked by the lingering illness which eventually terminated her life,
she expressed doubts of her recovery, but showed no alarm;
the calm and collected state of her mind evincing that she was sustained
by that food which nourishes the sou! up unto eternal life.

The remedies used for her recovery failed to procure any amendment in the disease;
but her love for her Saviour seemed to increase as her bodily powers were enfeebled,
and also her love to those around her,
often expressing her gratitude for their kind attentions,
and for the blessings dispensed to her by Him from
whom every good and perfect gift comes.
The critical state she was in being mentioned to her, and the question asked,
whether she felt anything in her way, she replied with a composed countenance,
that she was not sensible there was much stood in her way to happiness--though
she felt that she had sometimes been too rude,
and feelingly commented on the vanity and emptiness of the things of this world.

On the 25th of eleventh month, 1821, she became much worse,
and it being proposed to call in a physician, she seemed unwilling, saying,
"`A physician can do me no good,`"--and next day remarked
that she felt easy in her mind and willing to die.

On the 27th, she said to her eldest brother, "`You have lost a dear babe and brother,
and will soon lose a sister,--O be prepared to follow them.
Our heavenly Father`'s house is open to receive all
those who are willing to come unto Him.
You must repent and believe in Him whom God has sent;`"
exhorting him to seek the pearl of great price.

On the 25th, she observed,
"`I shall soon be taken from a world of trouble to
a world of rest--Yes--I shall be at peace.`"
Seeing her mother and sisters weep, she said, "`I do not like to see you weep.
We must all die some time, and why should not I now?
I shall be happy in my heavenly Father`'s kingdom, where joys are ever new.
Do not mourn for me.
You have done a great deal for me,
and I hope you will be rewarded and prepared to meet me in the heavenly kingdom,`" adding,
very impressively, "`you ought to have your lamps trimmed and burning.
I love you all--but he that loves father or mother, or any other thing more than Christ,
is not worthy of him.`"

She exhorted her sisters to be kind to their mother,
and endeavour to support her in her trials, and then solemnly took her leave of them.
Her father and youngest brother coming into the room,
she remarked that "`they had been kind to her,
and she humbly hoped they would be rewarded by that Being before
whom we must all give an account of the deeds done in the body.
Dear father,
I hope you will meet me in that kingdom where neither moth nor rust does corrupt,
nor thieves break through and steal.
Dear brother, I hope you will be kind to our parents and mind their counsel.
I am the youngest of the family--you know not how soon it may be your turn--O,
be prepared.`"

Shortly after this a relation came into the room whom she had desired to see;
and after a silent pause, she said to her,
"`Your dress is not becoming a Friend--I advise you not to curl your hair or
to wear gay clothing--you ought not to spend your precious time in such vanities.
You must not follow the fashions of this world--remember you must be laid upon a deathbed.
Your mind must be changed, then you will be clothed with innocence,
and resemble the dove returning to the ark with the olive leaf in her mouth.
This world has nothing to bestow upon you.
He that loves anything more than me, +++[+++said our blessed Lord]
is not worthy of me.`"

The next day her articulation so failed that but little she said could be understood,
yet she was heard to say,
"`Happy--Happy`"--and in a peaceful and resigned frame of
mind she quietly departed to her heavenly inheritance.

[.asterism]
'''

SUSANNAH WHITROW, was the daughter of Robert Whitrow, of Covent Garden, London.
It appears that she, with some others of her father`'s family,
had lived in great pride and extravagance,
following after the vain fashions of a wicked world,
and disregarding the convictions of divine grace in their own minds; for which,
when laid on a sick bed, she was brought to feel the judgments and terrors of the Lord.
Under a sense of her sins and the weight of iniquity which lay upon her,
she would frequently cry out for mercy and forgiveness, saying, "`Lord,
are my sins forgiven?
Had not my eyes seen these vanities, my heart had not gone after them.
Shall I have no help for my distress!
O strengthen me to see my desires.`"

It pleased the Lord in the riches of his mercy to hear her prayers,
and to blot out her sins for the sake of his dear Son, Christ Jesus our Lord;
and having thus obtained pardon for herself,
she became exceedingly concerned on account of her father,
who she feared was too little engaged for his own salvation; praying after this manner:
"`Lord,
remember not his offences--let me bear them--make his friends to
be his enemies that you may have mercy on him--carry him through,
and let him not perish with the world.
Blessed Lord, hear me; leave me not unsatisfied, but grant my request.
Set his mind on things above--turn him and he shall be turned:
there is no way for him but to watch and pray continually, lest the tempter prevail.`"

To her mother, who had not joined in the pride and folly of the family,
she thus expressed herself, "`O,
my bowed down and brokenhearted mother! what have been your sufferings in this family!
how have you been oppressed with our iniquities! how often have you told my father,
the Lord would visit him with sore and grievous judgments,
if he did not repent and turn from the evil of his ways!
How often have you said the Lord would plead your righteous cause with us!
Now the day is come which you have so long warned us of;
now the Lord has broken in upon us.
O,
how great have been your care and pains which you have taken to bring us into the fear
of the Lord--great shall be your reward--the Lord will give you beauty for ashes,
and the garment of praise for the spirit of heaviness--you are blessed, my mother.`"

Soon after this, she said, "`Blessed are the poor in spirit.
Lord I am poor and needy.
I need your strength continually to withstand the tempter.
O Lord stand by me, move not from me; for if you go the tempter will come.
I will hold you fast; you are my Saviour, you shall save me from the tempter.`"

On another occasion she remarked,
"`I fear I shall not have a place so near the Lord as my soul desires.
I have done nothing for the Lord, but he has done all for me--therefore I desire to live,
that I might live a holy and righteous life; that my citizenship might be in heaven,
though my body be here on earth; that I might invite all, as David did,
to taste and see how good the Lord is.
They have tasted of their perishing life of vanities, yes, they have drank a full cup,
their measure is running over; but they never tasted the joys that attend the humble,
holy life of Jesus.
Oh, if they had ever tasted the least mite thereof,
they would bid adieu to all their life of vanity.
Ah, they would not dare to spend their precious time in adorning themselves,
patching and painting,
and curling their heads--the christian life is another thing--they
must not give themselves liberty to think their own thoughts,
much less to act such abominations as these.`"

After this, she spoke on the parable of the wise virgins,
exhorting all to keep very diligently on the watch, saying,
"`the Lord will come as a thief in the night, and in a day when he is not looked for;
therefore, watch and pray continually: here the tempter cannot enter;
this is the way my Saviour spoke of, when he said, you must take up your daily cross;
this is that flaming sword you must pass through,
before you can come to the tree of life.
This is the cup my Saviour asked you if you could drink of,
and this was that baptism he asked if you could be baptised with.
Come, all you that call yourselves Christians, what +++[+++evidence]
of the life of the holy Jesus is in you, who was a man of sorrows?
You light and airy ones--you wild and careless ones--you
that are lovers of pleasure more than of God,
you workers of iniquity who are always crying Lord, Lord,
but do not the things that I say, this shall be your dreadful doom;
that you are sayers but not doers.
You workers of iniquity that think you can never have enough of the pride of life,
the lust of the flesh, and the lust of the eye, which is not of my heavenly Father,
and so you are of your father, the devil; for his servants you are whom you obey.`"

On another occasion she thus expressed herself, "`Be holy, as I, the Lord your God,
am holy.
This, they say, is impossible.
Oh! would the holy, just and true Lord, command that which is impossible?
In this, they count the Lord a hard Master.
But what can my soul say of your power,
when I sought you but could not find you--I knocked hard, but none would open;
for my sins stood like mountains, that I could not come near you.
I would eagerly have prayed, but could not.
I lay several days and nights prostrate before you, struggling for life,
but could find none; and I said, there is no mercy for me.
Then said I, I will never leave you--if I perish, I will perish here.
I will never cease crying unto you.
Then I heard a voice, saying, '`Jacob wrestled all night before he obtained the blessing.
O,
then your word was strength to my soul--then my stony heart was broken to pieces before
the Lord--then the spirit of prayer and supplication was poured into my soul,
and now I can sing, as David did, of mercy and of judgment.
Unto you, O Lord, will I sing; with a rended heart and with my mouth in the dust,
will I sing praises unto you, my blessed Saviour.`"

For several days she had great conflict of spirit, and strong were her cries to the Lord,
for strength to overcome the tempter.
"`I would not, said she, allow a thought to wander--if I move,
I shall be drawn off my watch, and then the tempter will prevail.`"

But through the Lord`'s mercy and power, the enemy of her soul was at length conquered,
and she broke forth after this manner,
"`It is finished--I have overcome--my Saviour has bound
him;`" for which unspeakable favour she magnified the Lord,
singing praises to his name,
and declaring the wondrous works which he had wrought for her soul.

Addressing those around her, she said, "`Don`'t you feast, but fast and pray;
and be contented with mean things.
Oh! what matter for fine houses or silken apparel.
Remember Him that sat on the ground, that wore a garment without a seam, our blessed,
holy Lord,
who went up the mountain to pray--that withdrew into
gardens and desolate places of the earth;
my soul has fellowship with Him.`"
"`O glorious One, you have overcome my heart,
you have ravished my soul--you pure and holy One, what shall I say of you,
or what shall I render to you for your lovingkindness to me.
My heart is overcome with your love; praises be unto you for your lovingkindness to me.
How shall I do to set forth your goodness; for my heart drops before you.`"

She was remarkably filled with divine consolation and holy joy,
singing praises and hallelujahs to the Lord;
and spoke much concerning the Lamb and His followers,
who had washed their robes and made them white in his blood.
Towards evening, two persons coming to see her, she uttered many instructive expressions,
and with much earnestness of spirit observed, "`O, Israel,
what has your God done for you!
What shall we do for the daughters of Jerusalem,
who are haughty and go with outstretched necks and lustful eyes.`"

Several days after, she said, "`O beloved of my soul, what shall I say of you,
for you are too wonderful for me.
Praises be unto you.
Come all you holy prophets, praise the Lord with me.
Praise the Lord, O, my soul, upon the loud-sounding instrument.
You glorious angels, that excel in glory, sin praises to Him that sits upon the throne.
O, how am overcome!
You stones in the street, why do you not rise up to praise Him that lives forever!
O light, praise the Lord, and darkness, praise and exalt Him above all things forever!
You sun, and moon, and you stars in the firmament of his power,
magnify the Lord above all forever!
All you fishes in the sea, why do you not come forth to praise the Lord, the mighty God,
who gives you breath and being?
I will praise you while I have my breath.
Praise the Lord, O, my soul, sing praises to the God of my salvation: my holy One,
you have overcome my heart, you have ravished my soul.`"

"`My dear mother, I shall be as a new-born babe--I shall be very simple;
but the Lord is with me.
I must lay down this body.
The Lord will not trust me longer in this world.
Happy am I. My Saviour, my soul loves you dearly--your love is better than wine.
My Saviour, my holy One, how glorious are you!
I have seen your glory, my heart is overcome with your sweet countenance.
O, come away, why do you stay!
I am ready--I am ready.`"

Soon after this she quietly departed this life, and has doubtless,
entered into that unspeakable glory laid up in heaven for the righteous,
of which her soul was permitted to enjoy so large a foretaste,
even while clothed with mortality.
She was aged fifteen years.

[.asterism]
'''

PRISCILLA CUTHBERT, daughter of Thomas Cuthbert, was born at Brentford in England.
Some months before she was taken with her last illness,
she was observed to be under much concern of mind,
and would withdraw from the company of other children and deny
herself the diversions with which they amused themselves.
She frequently retired into solitary places, and read some religious book,
sometimes weeping much, and at other times praising the Lord.

When sickness came, she bore it with exemplary patience and submission;
praying the Lord to be her comfort and to comfort her beloved parents,
acknowledging their tender care in bringing up and
educating myself and her brothers and sisters.
On one occasion, her father coming to her,
she endeavoured to wipe the tears from his face, and said, "`Lord,
comfort my father and mother, and bless my poor sisters and brothers.`"
She advised her brother to obey his parents and fear the Lord, adding,
"`He will bless you.`"
She was entirely resigned as regarded the issue of her sickness, remarking,
"`I am willing to live to praise the Lord, and I am willing to die.`"

At another time she said,
"`In the time of my health I have been afraid when
I have seen the dead nailed up in their coffins;
but now, the Lord has taken away that fear--blessed be His name.
Therefore take you notice that stand by me, I am neither afraid of death nor the grave,
but am willing to die when it pleases the Lord.`"
She was often engaged in prayer on behalf of her parents,
expressing more than ordinary affection for them,
and also spoke of the peaceful state of her mind and her willingness to die, saying,
"`I am going where, I trust in the Lord, I shall have rest; for the Lord is my rest.`"

She died on the following day, at the age of about fifteen years.

[.asterism]
'''

PETER W. HALL, son of Thomas Hall, died at Brookfield school, near Wigton, England,
on the 5th of the 3rd month 1841, aged nearly fifteen years.

He evinced considerable originality of thought and great proneness for minute investigation,
even from a child.
He was of studious habits and while at school displayed
a strong bias for the medical profession,
which probably induced a closer application to study than
was quite consistent with prudent regard for his health.
As he advanced in years, his desire for information increased.
He possessed strong reasoning powers,
which not infrequently occasioned his father considerable uneasiness,
lest the cultivation of this faculty should lead him from the simplicity of the Truth,
to seek that "`knowledge which puffs up,`" to the neglect of that which alone can edify.
Indeed, the seeds of vanity were sown in his heart , for he acknowledged,
when brought to see the emptiness of such things, that previous to his attack of illness,
he had thought there was no science beyond his reach,
and that he had formerly hoped he should one day distinguish himself in the world,
and to accomplish this end, he was ready to devote his days and nights to study.
But the Shepherd of Israel, whose eyes are over all his works,
allowed him not to become entangled in the delusive vanities of life.
The rod of affliction in the divine hand,
humbled his spirit and soon stained the glory of this world in his view.
The uncertainty of life and the awful realities of another state of being,
were brought closely home to his mind,
through the instrumentality of a friend in the ministry,
who was led to address some of the youth; and the impression thus made,
was renewed and strengthened by the sudden and unexpected decease of a near relation,
about his own age, to whom he was greatly attached.
The good seed thus sown, fell into ground measurably prepared by the great Husbandman,
and it was not long before fruit was brought forth to the praise of his holy name.

A troublesome cough, languor, and a gradual prostration of strength,
which came on while at the school, were the first indications of latent disease,
but a hope was cherished that relaxation, change of air,
and exercise would soon restore him.

Daring the progress of the complaint,
although for some time he was backward in speaking of his feelings,
yet the gentleness and meekness of the true disciple,
and the increasing tenderness of spirit inseparable from a change of heart,
gave silent but sweet evidence to his nearest connections,
that he was under the preparing hand of his Heavenly Father.
As his illness assumed more alarming symptoms,
much anxiety was felt by his parents to learn from himself,
whether he was fully aware that they had but little hopes of his restoration.
Allusion being made to the uncertainty of his recovery, he said, "`I feel resigned,
however it may be.`"

Not long afterwards,
being informed that the physicians considered his case beyond their skill,
with great calmness, he inquired their opinion of the precise nature of the complaint,
and how long they expected he would continue in this state of being.
He was informed, they thought he might go almost any moment,
but that probably twelve hours might be the extent of his continuance.
To this he meekly replied, "`I am resigned; I have nothing to do but to die.`"
After this, he spoke largely on the great love and mercy of God in Christ Jesus,
and declared where his hopes were fixed.
"`I have nothing of my own to depend upon; my trust is in that dear Saviour, who said,
'`Come unto me all you that labour and are heavy laden,
and I will give you rest.`' I feel nothing now to
make me uncomfortable--his mercy is inestimable.
All my sins, and they have been so numerous,
nothing but a Saviour`'s blood could have washed them away--all, I hope,
are now forgiven.`"

After this period,
(first month 1841) contrary to the expectation of his friends and the medical attendants,
his life was prolonged several weeks.
During this time, the wonders of redemption, which human wisdom can never comprehend,
were largely unfolded to the comfort of his own mind and
the edification of others who were favoured to be with him.
His sister coming into the room, he addressed her very sweetly,
calling her attention to the uncertainty of life
and the need of a continual preparation for death,
by watchfulness and prayer and a daily walk with God.
He urged her to diligence in reading the Scriptures and meditating thereon.
In her interactions with others, he enjoined her to practise the Saviour`'s precept,
"`All things whatsoever you desire that men should do to you, do unto them.`"

Although about this time the medical men thought him expiring,
he was borne up above the fear of death.
Already, he seemed to be a partaker of the joys of heaven,
and contemplated with delight the goodness and mercy of God.
He was strengthened to speak with clearness, for nearly an hour and a half,
on some gospel truths very precious to him,
viz. the sufferings of a dying Saviour,--the efficacy
of his blood to cleanse from all sin,
the gift of the Holy Spirit which leads to true faith and perfect obedience,
as its secret admonitions are attended to,
bringing every thought into captivity to the obedience of Christ.

Soon after this he spoke to his father on what he apprehended
was the state of some of the boys in the school,
expressing a very earnest desire that they might
be brought to feel the exceeding sinfulness of sin,
and how dreadful it was for any to be living as without God in the world.
"`O,`" added he, "`that such were brought to repentance.`"
After expressing his thankfulness for the merciful dealings of his Heavenly Father,
particularly for having been for the last few months under immediate parental care,
and for the advantage he found in having a chamber to himself,
where he could wait upon the Lord in inward retirement, previous to going to rest;
he added, "`Oh! father,
how refreshing these opportunities have been--they were precious.`"
To a young female who had been watching very tenderly over him he spoke thus; "`Oh,
J+++_______+++, this is the time for you, the time of health, to prepare for death.
It will not do to trust to a sick-bed repentance.
Prepare now to meet your God; then I hope your deathbed will be as comfortable as mine.
Do care tenderly for your brother.
You girls who have brothers, watch over them,--they need it.`"

Having expressed a desire to see some of the boys who were at the school,
they were called singly to his bedside.
To the first he said, "`The doctor has told me,
that probably I have not more than twelve hours to live.
In that short period how could I prepare for death, if my peace had not been made?
I wish to recommend you to read your Bible very attentively.
Begin each day with supplication to be preserved from evil,
and be sure to close each day with a close examination how it has been spent.
If you have done wrong, crave earnestly to be forgiven for the dear Saviour`'s sake.
Attend diligently to the opportunities for reading and waiting upon God;
and be not afraid to avow yourself one of his followers.
Remember what the Saviour himself said; '`Whosoever shall be ashamed of me,
and of my words, of him will the Son of Man be ashamed,
when he shall come in his own glory, and in his Father`'s, and of the holy angels; but,
whosoever shall confess me, that is, he who acknowledges me before men,
and who is not afraid of manifesting himself to be a true believer and follower of Christ,
'`him shall the Son of Man also confess before the angels of God.`' Life is very short;
many are cut off as in a moment; the longest is but one hundred years,
and what is that compared with eternity?
When this life closes, it is but the beginning of that which will last forever.
If there were no other consideration than this,
how foolish it would be to attend only to the things
which belong to this brief portion of time,
and neglect those of eternal importance!
Live then each day as if it were your last.`"

Another he exhorted, with fond affection and with great earnestness of spirit,
to be continually in a state of preparation.
"`Watch and pray daily: never miss examination at the close of each day,
how that portion of time has been spent.
"`Seek earnestly for repentance for every sin of omission and commission;
and when favoured to do what is right, Oh! do not trust to that;
nothing but the mercy of God in Christ Jesus can save us, blotting out our sins.
Pray for continual preservation,
for the enemy is ever busy with his temptations to mislead.
Resist him, and he will flee from you.
How wonderful is the Saviour`'s love!
He who was equal with God, left the bosom of his Father,
took upon himself our nature and became an inhabitant of this earth,
leading the most painful life, tempted, tried,
led into the wilderness among the wild beasts there; and to crown all,
suffered the ignominious death of the cross;
without which sacrifice not one soul could hope to be saved;
for all have sinned and fallen short of the glory of God.
Now He remains forever our gracious Intercessor with the Father,
presenting our prayers with acceptance to him.
This is not all: He has given each of us his holy spirit, to lead and guide us.
O, mind that--it will manifest that which is evil, and if attended to, lead to peace.
Such transcendent love and mercy must not be slighted.
Watch diligently--look to the Saviour,
who was never overcome.`" His mind now appeared relieved,
and he broke forth in sweet praises,
commemorating the Lord`'s goodness in having dealt so graciously with him,
and given him the assurance that all his sins were freely forgiven for Christ`'s sake;
adding,`" it is this which makes my deathbed so easy and comfortable.
How wonderful is the Lord`'s goodness!
Oh, my Saviour!
What transcendent love!
What mercy, to be called in my youth by the most gentle, yet the most effectual means;
and all my sins--they were so many,
nothing but Your blood could wash them out--now seem entirely taken away.
Mercy! mercy! adorable mercy!
I have done nothing to promote the Lord`'s glory: that is humiliating;
yet we find those who wrought but one hour in the vineyard received their reward.
But, indeed, our own works never can save us.
All the righteousness of man is as filthy rags.
We can do nothing but by the ability which is given by the good
Spirit of God,`"--a sentiment which he often and feelingly expressed.

Towards evening, he received a message of love from the girls in the school,
and though so much exhausted that it seemed scarcely
possible for him to endure more fatigue,
he expressed a wish to see them all, at intervals, and to begin with the first class,
saying,
"`I do feel a desire to see them--the good Master will require nothing
but what he will give strength to perform.`" Believing that he really
felt the love of Christ constraining him to this service,
his request was granted.
He spoke to them with remarkable fervency of spirit and very solemn feelings,
and it appeared to be a message of love to their soul a.

On taking each by the hand, he spoke nearly as follows:
"`You see me now upon my deathbed.
I was not aware that my end was so near.
If I had put off to a deathbed repentance,
how could I have been prepared in so short a time for a never-ending eternity?
I want to entreat you to prepare for death now in the* morning of life.
The flower that is offered in the bud, is no mean sacrifice.
Give God your heart now.
Begin every day with supplication to Him for preservation during the day;
and before you closest your eyes in sleep,
examine how that portion of time has been spent.
Crave forgiveness for all your sins in the name of the dear Saviour.
Seek in Him for more strength to watch and resist the enemy; yes,
watch and pray--the spirit may be willing, but the flesh is weak.
Many a snare does the enemy lay to entangle,
but the good Spirit of God will discover all these.
If you are enabled to do any good thing, do not depend upon that for acceptance.
It is all through mercy, pure, unmerited mercy, that we are saved,
by having our sins washed away in the blood of the Lamb.`"

To another, he said,
"`You must expect many scoffings and deridings in submitting to the cross of Christ.
Let not this discourage you.
Remember who has said, '`Whosoever shall be ashamed of me and my words,
of him also will the Son of man be ashamed,
when he comes in the glory of his Father with the holy angels;
but whosoever shall confess me before men,`' not
being afraid to evince his love by obedience,
'`him will I confess also before my Father which
is in heaven.`' What is the longest life,
and what is time, compared with eternity?
A few years may be yours, but that is uncertain.
Be prepared to meet your God--your everlasting judge, now in your youth.
Live every day as if it were your last--this is the only way to peace,
and to know a deathbed made comfortable.
Let nothing induce you to put off this preparation.
The Lord has said,
'`My spirit shall not always strive with man.`' You
may be called away in a state of insensibility,
or the poor body may be so racked with pain, that your mind cannot then centre upon God.
This is my dying advice.
Farewell--I hope we shall all meet again in that happy kingdom.`"

This was a heart-tendering season--every eye was suffused with tears,
save that of the dear child--he had none to shed.
He was fast approaching that city where "`God shall wipe away all tears
from the eyes;`" and already appeared to participate in its bliss.
The opportunity was a great relief to himself; and after the children had retired,
he said, "`Oh, father, how thankful I am for this opportunity, how happy do I feel!
Oh, heavenly Father, how merciful are you!`"

The night was spent nearly, if not entirely, without sleep,
but in the sweet enjoyment of that peace which is
the precious gift of the Prince of Peace,
graciously imparted to those who humbly endeavour to do his will.
"`Oh, how happy do I feel!`" he again repeated, "`I do not wish to sleep.`"
Nature was too far exhausted to admit of seeing any more of the girls at that time;
but he desired his kind love to be given to each,
with the assurance that he felt an equal degree of love for all.

Many and fervent were his prayers that he might be
preserved in humility and patience to the end.
On seventh day, after a little broken slumber, the following petition was audibly put up:
"`O holy Father, enable me through the name of Jesus Christ,
to be made meet for an admittance into those holy mansions
where nothing that is impure or unholy can ever enter.`"
He very frequently besought the Lord for more patience and more humility,
and his requests were answered, for humility was the clothing of his spirit,
and patience seemed to have its perfect work.
Nothing like complaint or murmuring ever escaped his lips.

After being reduced apparently to the verge of the grave,
a very decided improvement took place without any perceptible cause; his breathing,
which had been very laborious, became much easier; he slept on either side,
and frequently asked for food, which he quite enjoyed.
Even the medical men began to entertain a hope of his restoration.
This change, so agreeable to those around him, occasioned the dear boy a very close trial.
He thought he had nearly done with time, and now the prospect of recovery,
or of lingering longer upon this earth, brought him very low.
"`Oh, father,`" he said, "`the doctors have made me very low-spirited:
I thought I was near my close, now that does not appear to be the case,
more means are to be used for my recovery; Oh, how much rather would r die!`"

A moment`'s reflection, however,
convinced him that it was quite as necessary to be resigned to live as to die,
if it was the Lord`'s will; and he quickly regained his normal serenity of mind,
often meekly uttering these words: "`Not my will, but yours, be done, O Lord!
Grant me patience, I pray you, your time is the best time.`"

On the 2nd of second month,
he received an acceptable religious visit from two female friends,
who were made the instruments of much comfort to his mind,
and he frequently afterwards offered thanksgiving
and praise for the benefits thus conferred on him.
Soon after, he supplicated thus:
"`Oh righteous Father! you have dealt mercifully with me in all things
If it be your will to make use of me as an instrument in the church,
you can raise me up again, for all power is yours.
If not, I crave of you to take me to yourself Oh, your unutterable kindness!
You have not brought me to death by a very painful disease.
You have freely forgiven all my sins, through the mediation of the dear Saviour,
the only mediator between you and sinful man.
O be with me to the end.
Grant me more patience and humility even for your name`'s sake, amen.`"
A little afterwards he said, "`Oh Lord, if I may be removed to the regions of bliss,
may it be done in a short time; but not my will, but yours be done.`"

After a season of deep trial from bleeding at the nose and much coughing,
under which nature seemed ready to sink, he thus addressed his heavenly Father: "`O,
will you be pleased to look down with an eye of pity upon a poor sinner,
who has nothing of his own to offer to you,
for all my righteousness is as filthy rags Grant
me patience and humility through Jesus Christ,
who descended from heaven to save sinners, of whom I am chief:
yet through his unutterable love, and tender compassion,
I humbly hope I shall be permitted to enter your kingdom,
to join forever the choir of angels in praising you, to whom all glory and power belong,
even forever--amen.`"
Shortly after, he exclaimed, "`Oh, most gracious Saviour, how I love you!
I crave to do all your commandments.
What unutterable love! to leave the right hand of the majesty on high;
to be put to the most painful death as an atonement for our sins!
Leave me not, I pray you, but preserve me from evil--preserve me in watchfulness,
in humility, in resignation to your holy will.
Come, Lord Jesus, come quickly.`"

Prayer and praise seemed to be the constant engagement of his spirit.
His mother entering the room, he said, "`O mother, what a sweet opportunity we had!
O, how comforting!
I would not exchange the enjoyments of this sick-bed for all the buoyancy of health.`"
As night approached,
he requested to be placed in a recumbent posture and then
desired his father to leave him alone for a short time.
Before sinking to rest, he prayed thus: "`O merciful Father,
through the mediation of Jesus Christ,
whose precious blood was shed as a sacrifice for sin, receive me, if it please you,
into your kingdom.
You know all my backslidings--how often I have turned from you;
but you have blotted out all my transgressions for his sake.
Oh! what kindness!
Sustain me, I pray you, for the enemy is very busy, in all situations,
but your power can preserve.
Grant me, I pray you, to be fully resigned to your will, whether to live or die;
and may your will be done.
Amen.`"
His whole soul seemed to be absorbed in adoration
and praise for the redemption of fallen man,
and he once more exclaimed, "`Oh! adorable Saviour!
Merciful Father,
I have nothing of my own to offer unto you--He alone is the Mediator--through
Him only I hope to be admitted into your kingdom,
having all my sins washed and made white in his blood.
How great and marvellous are your works.
Lord God Almighty!`"

Shortly after this, an attack of coughing and expectoration came on,
which threatened immediate dissolution; when relieved,
he was distinctly heard to breathe thus, "`O gracious Father,
enable me through Jesus Christ,
to bear patiently every trial which you may yet see fit to give.`"
Often did this dear child express his astonishment
that any should think religion a gloomy thing,
"`None,`" said he, "`can be so happy as the good;
none can have such cause for cheerfulness.`"

Every little attention bestowed upon him was so gratefully received,
that it was a pleasure to wait on him.
He evinced the fondest affection for his step-mother, often exclaiming, "`O mother,
dear mother, I can never reward you for all your kind ness.
O, how I love you!
May a gracious God reward you; I cannot do it.`"
A near relation, dressing his chest, which was extremely sore, observed,
"`We never need complain,
when this poor child has such a chest as this;`" to which he sweetly replied,
"`Neither must I complain of this, when the dear Saviour, the Son of God,
suffered incomparably more for me.`"
He seemed to have arrived at that state recommended by the Apostle,
"`Pray without ceasing--in everything give thanks.
When the energies of nature were sinking under the pressure of the disease,
and no comfortable position could be found to rest his wearied, aching frame,
he found in God a never-failing refuge.
In one of these trying seasons, he broke forth thus: "`O merciful God,
how marvellous are your works, and your ways past finding out!
Oh! Jesus, you died upon the cross for me, that my sins might be blotted out;
that I might be washed and purified in your blood, O Lamb of God.
How many kind friends I have about me who try to alleviate
my sufferings--it is you that prepare their hearts.
Come, my Saviour; come quickly--but Oh! for patience to wait your appointed time,
for your will is best: forgive my impatience, O Jesus, my sweet Saviour.
Amen.`"

Another time he remarked "`Oh! how sweet to wait upon the Lord,
in silence and in prayer!`"
Once, when much exhausted, he said to his mother, "`O, dear mother,
I think I cannot survive much longer; my bodily strength seems well nigh gone,
but if I live, I know I shall be provided for night and day--but my Saviour had,
when on this earth, nowhere to lay his head.`"
Awakening out of a slumber, he said, "`Oh, dear mother, when I was asleep,
I thought I saw all my sins arrayed against me, like a mountain, ready to overwhelm me,
but on looking up, I saw a ladder firmly fixed, the top of which reached to heaven:
this I grasped and began to ascend, as my only means of escape.
That ladder, I think, was Christ: He is my only hope of salvation.`"

Sixth-day evening, of second month, he prayed, '`Oh, gracious and merciful Father,
who dwell within the heavens,
look down upon me who am one of the meanest of your
creatures--O prepare me a place in your kingdom!`"
Speaking of the goodness and mercy of the Almighty toward him, he said,
"`He has created a clean heart and renewed a right spirit within me.`"
To a young friend, watching by him, he said,
"`Remember now your Creator in the days of your youth, while the evil days come not,
nor the years draw nigh, when you will say, I have no pleasure in them.
I remembered my Creator, and now he has not forsaken me.
Oh! how glorious to think that I shall soon be an inhabitant
of the celestial city--I shall not be here long--no,
`'tis but the twinkling of an eye and all will be over.`"

Eighth of second month, he had a better night than usual,
yet it Was evident that the complaint was making stealthy but sure progress.
His medical attendants met in the afternoon: and after they were gone,
he appeared wishful to know what they then thought of his case.
On being informed that their hope was now only to alleviate, not to arrest the disease,
with a sweet and most expressive smile, he gently uplifted his eyes, and said,
"`Blessed be the name of the Lord!
Oh, happy, happy,`"--his grateful placid look spoke the rest.
Several days passed over without any decided change,
but the little remaining strength was gradually wasting away.
As the medical men had strongly enjoined him to converse as little as possible,
much expression was not heard;
yet day after day he was engaged in scarcely audible whispers,
breathing out his supplications to God,
and the solemn accents of thanksgiving often broke from
his lips in a tone too low to be correctly repeated.
"`Sweet Jesus!
Merciful Saviour!
Inconceivable is your goodness!
Equal with the Father,
you left the glories of heaven to die for poor sinful man--love unutterable! even I,
the lowest and most unworthy of your creatures,
hope to gain an admission into your heavenly kingdom, through your intercession,
O my Saviour.`"
Great was his love to those about him,
and a desire to be found faithful in imparting what
he felt for the well-being of one of his school-fellows,
for whom he had previously evinced a deep religious concern, induced him,
after having obtained his father`'s permission,
to break through the doctor`'s injunction.
The opportunity, at his own request, was a private one;
an air of cheerfulness and heartfelt satisfaction
was spread over the dear child`'s countenance,
on his father`'s return into his chamber,
affording a silent evidence of solid peace of mind.
After this, from time to time,
others of the children whom he had not previously addressed,
were introduced into his chamber, to whom he spoke in accordance with his feelings,
with tendering effect.

On the 10th of second month, as his mother entered his room,
he replied to her kind inquiries, "`Oh! dear mother,
every succeeding day brings me nearer to my peaceful home.`" About this time
he disposed of his books and other little things as presents to those about him,
and with great calmness, but with tremulous hand,
he inscribed those last mementoes of his love.
He continued a sojourner on earth longer than was expected,
'`with his loins girt about and his light burning,`'
patiently awaiting the coming of his Lord,
his work appearing to be accomplished, and his warfare ended.
His faculties remained clear to the last.
The sweetness and innocence of his conversation,
the cheerfulness and serenity of his mind, the liveliness of his faith,
his gentleness and love, and the meekness and patience of his spirit,
afforded beautiful evidence that the work of righteousness is peace,
and the effect of righteousness is quietness and assurance forever.
After a day of considerable enjoyment, and an entire exemption from pain,
he sunk to repose as in the arms of redeeming love,
and was mercifully favoured with an easy passage to the realms of bliss--to join,
as we humbly hope, in that holy anthem, so dear to him on earth,
"`Worthy is the Lamb that was slain`"--yes, "`blessing, and honour, and glory, and power,
be unto Him that sits upon the throne, and unto the Lamb forever.`"
