== Chapter 5

[.chapter-synopsis]
* Barbara Scaif
* Sarah Featherstone
* Mary Bewley
* Joseph Poole
* Elizabeth Fletcher
* Charles Coleby
* Henry Atkinson
* Tudor Brain
* Ann Crowley

BARBARA SCAIF, of Blackside, in the county of Westmoreland, England,
was a child that feared the Lord, and was obedient to her parents.
She and her sister being taken ill with the small pox,
many of the neighbours came to see them,
and their company and conversation being disagreeable,
she desired her mother not to allow them to stay, "`For,`" said she,
"`we have no need of such empty talk as is used among too many; we would be quiet,
that we may pray to the Lord to forgive us the faults we have committed;
and if He spare our lives at this time, I hope and believe we shall amend,
and have a care of displeasing the Lord while we live.`"

About the seventh day of her illness, being under much concern, she prayed thus--"`O,
Almighty God!
I cry unto you; blot out all my transgressions, and my sins;
let them come no more into your remembrance.
I beg it of you, in the name of Jesus Christ, with all my soul and with all my strength.
Let your favourable countenance be upon me.`"
Her prayers were frequently put up to the throne of grace, not only for herself,
but also for her parents and her sister,
beseeching the Lord to strengthen her to resign herself freely to His will.
She advised her brother to be "`faithful to the Lord and to his religion;
to love the Lord with all his heart,
and not to love the world nor the pleasures thereof.`"
Alluding to her relations, she said, "`I can freely part with and leave them all,
for the enjoyment of the comfort and happiness which my soul is made sensible
of;`" and concluded with praises to the Lord for the riches of his grace
and the comfort she had received from Him.

Being pressed by her attendants to take some food, she declined, saying,
"`Do not trouble me with it; for if thereby you think to keep me, it is all in vain.
I must die and leave you; neither would I desire to live for all the world:
for to be with the Lord is better than ten thousand worlds,
with whom I shall rest forevermore--even with God and His saints--his
faithful people and servants--glory to his name forevermore.`"

She manifested much tenderness of spirit and watchfulness
over herself lest she should speak an unbecoming word.
She was kind and sympathising to those about her,
and seemed more concerned at the trouble she gave them in waiting upon her,
than for her own sufferings.
On the day of her decease she told her mother,
that that morning would nearly finish her time in this world, "`for,`" said she,
"`the Lord will ease me, before long,
take away all my pain and wipe all tears from my eyes.`"
Presently after, she remarked,
I am ready to leave this world,`" and desired her
parents to be contented with the will of the Lord,
and about one o`'clock in the morning she quietly departed to her rest in Jesus.
She was about fifteen years of age.

[.asterism]
'''

SARAH FEATHERSTONE, daughter of Joseph and Sarah Featherstone,
died in the sixteenth year of her age.
When very young she was desirous of hearing and obeying the voice of heavenly wisdom,
and was careful to remember and fear her great Creator.
To her parents she was affectionate and obedient,
and on all occasions showed herself to be of a meek and quiet spirit.

Soon after being taken ill,
she informed her mother that she believed she should be removed from her;
and when it was proposed to send for a physician, seemed unwilling, observing,
"`I am freely given up to the will of the Lord, whether to live or die.
It was showed me that I was not of a long life,
and if this be the time of my change I am content.`"
The anxiety and affliction of her mother at the prospect of losing her beloved child,
were a source of trouble to her, and she earnestly desired her to seek after resignation,
saying, "`Your dear and tender love to me has been very great,
and in that love I desire we may rest, freely given up to the will of God;
for the Lord may not see fit to trust me in this wicked world any longer.
O, the abominable pride of this world!
There are some among us who can take liberty to
fashion themselves in many things like the world,
both in their habit and other needless things.
Oh! but the christian`'s life is another thing--this
is not the adorning that we are to put on;
for if the righteous scarcely be saved, where shall the wicked and the ungodly appear.`"

Her disorder being very severe, she said, "`I was never so sick in my life.
I am sick at my heart.
O Lord, in mercy remember me and bear me up above all my afflictions,
for my heart trusts in you.`"
After this she laid very still, bearing her sickness with much patience,
and shortly before her close, said, "`O, my dear and heavenly Father! come away,
come away, for my heart trusts in you`"--and so fell asleep in the Lord.

[.asterism]
'''

MARY BEWLEY, daughter of George Bewley, of Cork in Ireland,
was a sober and affectionate child,
obedient to her parents and courteous and gentle in her demeanour;
qualities which endeared her to such as had the pleasure of her acquaintance.
She loved and kept to plainness in her apparel and conduct,
and disliked the finery and vain fashions of the world.
Being of a delicate constitution and often in ill health,
she was thoughtful about her latter end, and under the feeling of religious concern,
was frequent and earnest in prayer to God,
that through the aid of his grace she might experience a preparation for her final change.
This fervent exercise of spirit,
was mercifully regarded by Him who hears and answers prayer;
and she was enabled to resign herself entirely to his will,
often expressing that she had no wish to live except to serve the Lord,
and begging for patience to bear her afflictions in a becoming manner.

After she was taken ill,
the consideration of the way in which she had spent her past time,
and of what she had said or done amiss, often employed her serious thoughts;
and being brought to see the exceeding sinfulness of sin,
she prayed to the Lord "`to pardon and pass by her offences,`" desiring
also the help of the spirits and prayers of those about her.
Addressing her sister Hannah, she said, "`Honour your father and mother,
and do not give way to little foolish things,
for by small things the enemy draws away the minds of poor
children--mind your dear sister`'s dying words,
and do not put off to a dying day and think it is time enough.`"

In the evening, her father coming to see her,
she expressed to him her willingness to die,
but longed for a more full assurance of the love and favour of God.
The following morning however, when he inquired how she was, she answered, "`Very weak,
but I feel a little more comfort now.
I hope the Lord is my strength:`" and she called upon God, saying, "`Dear Lord,
forgive me my sins and teach me to pray.
Lord have mercy on me--my Saviour, have mercy on me--take me, dear Lord, if you please;
draw me with the cords of your love.`"
The doctor inquiring respecting her feelings, she replied, "`I am weak,
but the Lord is strong, and on Him alone is my dependence.`"

To her parents,
she expressed great affection and gratitude for the tender care they had exercised
in preventing her from indulging in things which too many run into--and said,
that she had formerly been too much disposed to rest satisfied in a religious education,
but as she grew in years she found this was not sufficient,
and ardent desires were raised in her mind that she
might live continually in the fear of the Lord.
About this time she was much tried by the suggestions of the enemy of her happiness,
which she mentioned to her grandmother, and requested her prayers for her,
that the Lord would take her to himself--and when her grandmother
spoke encouragingly to her and informed her that it was
often the experience of those who lived near the Lord,
to be beset with the temptations of the wicked one, the child answered,
"`I am very weak and can do nothing for myself.
It is the Lord that does all for me.
The Lord has been very merciful to me and is so still.`"
Her heart being filled with gratitude and love to God, for his manifold mercies,
she broke forth after this manner:
"`How sweet is the love of God to my soul--O that
I could praise Him enough for his love and mercy.
If the love of God is so sweet now, what will it be when I get fully to it?
O, that I was with You now; dear Lord,
take me into your arms--I do not now wonder to have heard so many praising the Lord,
for he is worthy of more praise than I have strength to give him.`"

After this season of heavenly consolation and enjoyment,
it pleased the Lord to withdraw the light of his
countenance and permit her to be tried with desertion;
under which dispensation,
her prayers were earnest that he would not entirely forsake her,
but in his own time "`lift up the light of his countenance again upon her,
and receive her where the wicked cease from troubling and the weary are at rest.`"
She then prayed for patience to wait the Lord`'s time,
and being asked to take some nourishment, seemed to decline it, saying, "`O,
the love of God is what I desire.
Dear Lord, send comfort--why will you withdraw yourself from your poor creature?
O for one taste of your love before I go.`"

Apprehending death to be near, she desired to take leave of her parents and the family,
which she did in a very affectionate manner;
and it pleased Him who is rich in mercy to all those that call upon Him,
to satisfy her soul with the renewed incomes of his love,
in a humble sense whereof she said, "`O, dear Lord,
how sweet is your love and presence--no tongue can tell but those
who feel it--O praises to the Lord--how shall I praise him enough?`"
She desired those present to unite with her in magnifying the worthy name of the Lord,
and expressed her belief that she should be with her dear Saviour that night,
and continued praising Him as long as her strength permitted.
She departed this life on the 6th of eighth month, 1730,
aged fifteen years and five months.

[.asterism]
'''

JOSEPH POOLE, son of Joseph and Sarah Poole, deceased the 29th of twelfth month, 1785,
aged about sixteen years.

In his childhood he manifested a remarkable innocency and sweetness of disposition,
and a sobriety uncommon in one of his years,
seldom indulging himself in those plays and pastimes
to which children are generally addicted.
Being endued with a good understanding,
enlarged by obedience to the early visitations of divine grace,
he attained a considerable degree of religious experience,
and would often speak on serious subjects in so sensible a manner,
as to excite the admiration of those who heard him.

Being fond of learning, and having a peculiar taste for such studies,
he made considerable progress in the mathematics and other useful branches of science,
as well as literature, which, however, did not appear to elate him.
He was remarkably diligent in reading the holy scriptures,
and greatly delighted in the company of pious persons
and the attendance of religious meetings.
About a year and a half before his decease,
it pleased the Lord to visit him in an eminent manner
with the influence of the Holy Spirit,
to draw him into nearer and more intimate acquaintance with himself,
and wean his affections from all sublunary objects.
As he yielded to the operation of that baptism which
is compared to a refiner`'s fire and fuller`'s soap,
he was purified from the pollutions of sin,
and "`to the praise of the glory of God`'s grace,
wherein he has made us accepted in the Beloved,`" it may be said,
that he became emphatically "`a new creature.`"

Continuing steadfast in his love and obedience to Christ Jesus,
he soon found it his duty to declare unto others what the Lord had done for his soul,
and appeared in public testimony in several of the
meetings of Friends to their edification and comfort.
The state of his mind, at the period when he first yielded to this requisition,
may be gathered from the following memorandum, found after his decease,
and dated 7th of eighth month, 1785, viz:

"`Many perturbations and trials have been the lot of my inheritance.
May the Lord sanctify them to me so as to render acceptable
those things which seem bitter to the taste,
and qualify me to labour in His vineyard to His honour, praise and glory;
of which He alone is worthy.`"

He was weighty and fervent in spirit,
and his deportment solid and instructive--cautious not to
speak either in meetings for worship or discipline,
without a clear evidence of divine requiring,
and his words being few and savoury tended to minister grace to the hearers.
His public declarations were short, connected, and free from affectation.
He evinced a tender feeling for the situation of the poor
and those in affliction and would frequently visit them,
freely contributing to the relief of their necessities,
as well as imparting counsel or consolation.

A portion of almost every day was devoted to retirement and religious contemplation,
in which he took great delight,
and would occasionally record the fruits of the solitary hours which he thus passed.
The following was written on such an occasion, viz.: "`How precious is your presence,
O God! how sublime are your delights.
How beautiful is your majesty, excelling that of all outward princes.
Placed far above all principalities, you delight those who humbly seek you,
with refreshing well springs from your divine fountain--you
have reserved delightful pleasures for them.
O, Lord, I have heard your voice which is sweet;
I have beheld your countenance which is comely--keep me in a humble, reverent,
watchful state;
knowing the enmity there is between your precious seed which you have sown in our hearts,
and that of Satan who is an enemy and a destroyer.
O Lord, give me power to overcome, that so when time here shall fail me,
I may be received into your everlasting mansions,
where the wicked cease from troubling and where the weary are at rest.`"

In this watchful state of mind he sojourned on earth,
bearing the daily cross and walking in that self-denying
path which the righteous in all ages have trodden;
until it pleased Him whose ways are past finding out,
to call him from works to a blessed reward in heaven.

He was taken ill with the small pox in the twelfth month, 1785,
and though he suffered much from the disease, was favoured with patience,
and uttered many expressions which evinced his confidence and trust in the Lord`'s power,
and his assurance of mercy and acceptance through Jesus Christ his Redeemer.
The day on which he was attacked, he observed to his mother, "`I am very sick,
but I have sweet peace, and is not that well.`"
After a painful night, he remarked, I have had a hard night of it;
but I have felt so much of the love of God that it makes amends for all my hardships.`"
On another occasion, being in much pain, he said, "`O, Lord, why am I thus afflicted,
seeing you know the integrity of my heart?`"
and then prayed the Lord to grant him a little ease if it was consistent with His will.
Soon after which he fell asleep, and on waking appeared much refreshed,
and gratefully acknowledged the Lord`'s mercy and goodness in answering his petition.

He expressed to his mother his hope that she would be enabled to say with Job,
"`The Lord gave and the Lord has taken away, blessed be the name of the Lord.`"
A few days before his decease,
his spirit seemed to be drawn into near sympathy
with some American friends recently in England,
with whom he had become acquainted, and he desired his dear love to be conveyed to them,
particularly John Pemberton and George Dillwyn and their companions.
The morning of his departure, several persons coming into the room,
he spoke in a lively and pertinent manner to their states;
and the last words he was heard to utter, were,
"`I have tried it--I have proved it--nothing will
do but what has the Master`'s stamp upon it.`"

In a few moments after this, he fell into a sweet sleep and quietly departed.

[.asterism]
'''

ELIZABETH FLETCHER was the daughter of John and Mary Fletcher, of Danby Dale, Yorkshire,
England.

When about five years of age a complaint appeared in her knee,
from which she suffered much for a long time,
and at length it became evident that her life could only be prolonged by amputation.
In the eleventh year of her age, after solidly considering the proposal,
she cheerfully submitted to this painful operation,
and for a considerable time after her recovery, enjoyed good health.

She was placed at Ackworth School,
where she gained the love of her teachers and acquaintance;
for though of a lively disposition, she was very affectionate and dutiful.
While there, some symptoms of disease returned; but after leaving that seminary,
she was placed at Sheepscar School, near Leeds.
During her stay there, her sister Mary was taken ill and died,
and the following extracts from a letter addressed to her by Elizabeth,
show that her mind was no stranger to the important concerns of the soul`'s salvation.

[.embedded-content-document.letter]
--

I often feel very anxious about your everlasting welfare,
as well as the rest of the family`'s, but yours more, because you are so poorly;
yet I hope the Almighty, who is ever willing to help the poor and needy soul,
will prepare you for the awful change, before He takes you to Himself;
if it be his will so to do.
But if it please him to spare you, I should think it a great favour.
Unerring Wisdom knows what is for the best; so we should be willing to say: Not my will,
but yours, O Lord, be done!
O my dear sister! may we be prepared before the awful day of judgment,
when we shall have to give an account of our thoughts, words, and actions.
My beloved sister, I think you will find very kind promises in the holy bible.
I remember some very gracious ones, Matt. 11:28 to 30; Ecc. 11:1. and xii.
1.; Psalm ciii.
and cxx.
1, and many more you will find in that holy book.

My dear sister, I hope you will not be offended at me,
for what I have taken the liberty to write to you;
for I have felt very uncomfortable a long time,
and as if I could not keep it from you any longer.
O, my dear sister!
I cannot express what a desire I feel on your account,
but I hope you will be prepared! for we know neither the day nor
the hour when it may please the Almighty to call us away.
So farewell; if we never meet again in this world, I hope we shall in the next: farewell,
my very dear sister.

--

While thus tenderly solicitous for the eternal welfare of a beloved relative,
this precious child was not negligent of the state of her own mind;
but there is good reason to believe,
that by taking heed to the convictions of the Spirit of Truth, she was growing in grace,
and in the knowledge of that salvation, which is the gift of God,
through our Lord and Saviour Jesus Christ.

In the twelfth month 1824, her complaint assumed so alarming a character,
that it was deemed necessary to remove her home,
and a long scene of acute bodily suffering ensued,
during which divine support and preservation were mercifully vouchsafed,
enabling her to endure with becoming fortitude and patience the trials allotted her.

In the time of her illness she uttered many heavenly expressions,
evincing her love for her God and Saviour,
and her resignation to his blessed will--and also gave good
advice to her relations and others who came to see her.
A few of those noted down by her mother, are as follows:

13th of fifth month, 1825.
She said she ought to bear all that was laid upon her with patience;
but felt so weak both in body and mind, she did not know what she must do;
and was afraid she should not have patience.

14th of fifth month.
She called her mother to her bedside, and, with tears trickling down her cheeks, said,
"`O mother how different I feel this morning! What a good night I have had!
The Lord is good;--how He has comforted me--how merciful!
O mother!
I hope we shall all meet again! Now I find nothing particularly to stand in my way;
and I hope the Lord will be with me to the last.
You have been a kind mother to me; I hope the Lord will reward you.`"

First day morning, 15th of fifth month,
she took hold of the hand of one of her younger brothers,
who was apt to give way too much to his temper,
and in a very solemn manner desired him to be careful for the time to come,
for he did not know how soon he might be laid upon a deathbed;
and the sooner he gave up the better;
for as he grew older his inclinations to evil would be stronger,
and the work would be harder.
She then reminded him that it was near meeting time, and desired him when there,
at his first sitting down, to endeavour to settle his mind on the Almighty,
who was able to help and support him; and that he should not allow his mind to ramble.

21st of fifth month, she said, "`O dear mother! what I have felt this night!
I believe I should not have been here now if I had been more patient.
When my pain was so great,
I thought if I only could sink away and be at rest!
but I fear I have been too impatient to be gone.
I believe I shall be at rest,
for there is a place prepared for me in His glorious kingdom.
The light afflictions which I have had here are as
nothing in comparison of the joys to come.
I have prayed for all my dear brothers and sisters, that they may be preserved,
and live in the fear of the Lord, and walk uprightly before Him;
so that we may all meet again in his glorious kingdom, never more to part.
Christ died for our sins, and spilt his precious blood for us.
What a gracious Redeemer!
When the final close comes,
I believe the Lord will send his angels to receive my spirit unto his glorious kingdom,
there to rest forevermore.
I hope my brothers and sisters,
and near relations will be here to see this poor
bit of clay committed to the silent grave;
and I believe it will not be long before I am gone hence.`"

At another time she remarked what a favour it was
that she was likely to be taken away in her youth,
for she did not seem as though she should ever be
as able to encounter with the world as many are;
that she was freely given up, and had rather die than live.
She then petitioned the Almighty that her father, mother, brothers and sisters,
might be so preserved in his fear,
as to be favoured to meet again where all sorrow and tears are wiped away forevermore.

At another time, after lying still awhile, on being asked if she had got a little sleep,
she replied: "`have had far greater enjoyment than that of sleep.
I have been meditating about heavenly things: what an enjoyment is this!
I believe I have been too impatient when my pain was sharp;
I have endeavoured to be more patient, but I have fainted by the way.
Last night I prayed fervently for help, and my prayer was answered.`"
On her mother raising her up in bed, she said: "`I hope this will be the last time,
if it please the Almighty; but I must wait my appointed time,
though I long to be gone.`"

On its being observed to her, that she was worse today, she replied: "`No,
no! weaker in body, but stronger in mind.
What a comfortable day I have had!
I cannot express the comfort I feel;--the all-protecting arm supports me.
What comfortable sufferings!`"

On the evening of the same day, she said: "`I long to be gone.
What a Saviour!
What a blessed Redeemer have I! Had I been taken away soon after I was taken sick,
what a state should I have been in; so thoughtless are youth when in health.
What a merciful Father have I had to do with!
He has led me gently along step by step; and his guardian care has been over me.
Dear father and mother, give me up freely into the hands of a merciful God.
I believe He will be with you and support you, only put your trust in Him;
the Lord gives and takes away at his pleasure.`"

Soon afterwards she prayed after this manner:
"`Be pleased gracious Father! to take me to yourself this night,
if it be consistent with your holy will.`"

She then gave some directions about her funeral,
and wished everything to be done with as much stillness and calmness as could well be;
for she delighted in stillness and to be alone.

First day morning, the 22nd. She said her mind felt poor and low;
and she supplicated the Almighty that He would never leave nor forsake her,
but be with her to the end, and arise as with healing in his wings.
Enlarging thus: "`O gracious Father! grant me patience that I may hold out to the end;
for my body is exceedingly weak.
May your everlasting arms be underneath to support and bear me up in my low seasons!`"

23rd of fifth month.
She said: "`O mother!
I am afraid I am over anxious; I fear I shall offend Him.`"
Shortly after she prayed as follows: "`Be pleased, O gracious Father, to support me,
and give me patience.
I fear there is something more to be done; I fear I have offended You,
in slighting your gracious calls.
If any wrong thing yet remains in me, be pleased, I humbly beseech You, to remove it.
I love to be afflicted and to feel pain;
then I think You are proving and trying my faith
and confidence in You... O gracious Father!
King of Saints!
You who have suffered upon the cross, and whose blood was spilt for our sins! be pleased,
I pray You, if there be anything yet in me that is unclean,
not to leave me nor forsake me, until You have made me clean,
and washed my robes in the blood of the Lamb; only be pleased to give me patience,
for I am afraid I shall offend You; for I cannot think a good thought without your help.
O bountiful Father; I know I have slighted your gracious calls in days that are past,
and thought I would put it off until a more convenient time.
What a poor disobedient creature I have been!
Be pleased, I pray You,
to grant me an inheritance in your glorious kingdom
of rest.--I long to be still and quiet,
that I may listen to hear your still small voice in the secret of my heart;
and I want to clear my mind while I have strength;
for I wish at last to have nothing to do but to die.
I humbly pray You that You will grant me an easy passage;
and be pleased to receive my spirit into your never ending kingdom.
I pray You to support my dear father and mother,
and give them crowns of glory when time is done.`"

24th. This morning she said to her mother:
"`I have been comfortable this night far beyond my expectation.
I was afraid I should offend the Lord last night,
by not being patient enough in my very weak state of body; and after I had a little rest,
I turned my mind inward, and prayed to Him,
that he would be pleased to be with me this night and comfort me;
when this passage was unexpectedly brought to my remembrance:
'`The Lord pities them that fear Him, like as a father pities his own children:
and I was comforted; for I can truly say I was afraid to offend Him.--O,
how gracious and merciful a Father He is to me! how often
have I slighted his gracious calls in days that are past:
though I have often endeavoured to seek Him,
but have fallen short and fainted by the way; then I had to go back and begin again.
What a kind and merciful Father!

"`I cannot express the comfort I have felt this night.
I believe I have been over anxious to be gone,
but now I feel quite resigned to wait patiently the Lord`'s time,
which certainly is the best time.
This last day or two, I thought I should soon take my flight,
and be at rest forevermore.`"

At another time she said, "`I have been very comfortable to day;
and felt what I never felt before:
I believe I am washed and made white in the blood of the Lamb,
who died for me and all mankind.
What a gracious and forgiving Father is He I believe
I shall be happy forevermore! what a favour!
The Lord has been so mercifully kind to me all my life long;
He followed me from day to day, and I often slighted his reproofs,
and thought perhaps I would pay attention to his
gentle invitations at a more convenient season;
but I found this would not yield me any solid comfort.
I saw I must give up my whole heart.`"

How often is this the case with little children,
when their heavenly Father is pleased to visit their minds by his good Spirit,
and reprove them for their evil conduct or words,
or to incline them to walk in the ways of religion.
They think they are young, and it will be soon enough some years to come;
or they are so full of play, that they cannot attend to it now,
and so put by these gentle impressions to some future time, when in their apprehension,
it may be more convenient to attend to them.--But,
ah! little do such disobedient children think,
that the present time is the only convenient season--their heavenly Father,
whom they thus slight and neglect, may not visit them again by his good Spirit;
and in the midst of their play and folly, death may cut them off. May all, therefore,
of whatever age, hearken to the reproofs of this divine monitor,
surrender their whole hearts to the Lord, and obey his blessed instructions;
for this is the way to obtain eternal life.

Again, she remarked, "`What a merciful and forgiving Saviour have I had to deal with!
I have been favoured with a lingering sickness,
and there have been many little things to be done away;
but through mercy I had rather die than live,
for I often felt myself very unfit to encounter with the world.`"

"`And now, dear parents, I hope you will give me up freely;
and I hope my dear brothers and sisters will be a comfort to you,
when my body is laid in the dust.
I often think about my dear sister Ann; but I believe the Lord is near her,
and will never leave nor forsake her in her low seasons.`"

"`I wish my love to be remembered to all my friends and relations,
who are not at my funeral;
and it is my desire that all things may be done as still and quietly as possible.`"

The gradual progress of the disease reduced her to a state of extreme weakness,
in which she could not raise her hand,
nor scarcely articulate a word so as to be understood;
and after about six months confinement, she peacefully breathed her last,
on the 5th of the sixth month 1825, aged sixteen years.
Having made an entire surrender of her heart to the Lord,
and patiently endured those refining baptisms which were necessary to purify her spirit,
we doubt not, she is entered into the joy of her Lord;
and through his mercy joined the innumerable company of redeemed children,
to sing the praises of the Lord God and the Lamb, through the endless ages of eternity.

[.asterism]
'''

CHARLES COLEBY of Alton, in Hampshire, England, was the son of Joshua and Mary Coleby,
of London.

In childhood he discovered an active and cheerful disposition,
and his becoming deportment gained him the esteem
and affection of his school-fellows and teachers.
After the completion of his education,
he was placed as an apprentice with his uncle at Alton,
where he discharged his duties in business with fidelity.

He early evinced a serious turn of mind by his reverent behaviour
in meetings and during the time of silence before meals,
as well as by his general orderly conduct.
He also manifested a desire to read books on religious subjects,
especially the Holy Scriptures, in which he appeared to delight.
When about the age of fifteen,
in replying to a letter from his father relative to the selection of books,
he observes that he has been reading Newton`'s Dissertation on the Prophecies,
from which he derived much satisfaction,
and that he was surprised anyone could entertain principles
of infidelity after a careful perusal of this work,
in which there are such clear proofs of the scripture prophecies having been fulfilled.

For many months previous to the commencement of the affliction which terminated his life,
there appeared to be an increased watchfulness in all his actions,
and renewed attention to his religious duties, retiring when opportunity offered,
for meditation and prayer.
Those who witnessed his comparatively innocent life,
entertained the hope that he would have but little conflict
of mind to pass through when brought on a sick-bed;
yet it pleased divine Wisdom to try him with deep baptisms of spirit,
arising in part from the awful impressions he had of the exceeding sinfulness of sin.

He often lamented that during the time he was at Ackworth school,
he had told some known untruths,
the recollection of which brought him into great mental affliction,
as did also the following circumstance, which occurred when he was about seven years old.
While with an uncle at Harleston, he had taken a farthing without his leave,
which he now requested his aunt, who attended him during his illness, to return,
saying it might appear a small sum, and it was not the amount, but the act,
which pressed upon his mind.
The request being complied with, he appeared to be relieved.
He bore his long illness with much patience, and often asked to be alone, or, when able,
retired into another room;
and on these occasions he was earnestly engaged in prayer
to the Almighty that he might be assisted to hold fast,
his faith and be favoured to close his life with
calmness and resignation to the Divine will.
In vocal supplication he evinced a strong sense of the necessity of a Redeemer,
which he often expressed with much fervency, believing that through Him alone,
we obtain forgiveness of sins and have access to God.

He was desirous to have his mind abstracted from all outward objects
and weaned from a dependence on any but the Lord alone;
observing, "`Oh! that I could love him more and more,
and that he would be pleased to give me a broken heart and a contrite spirit.`"
On its being remarked that his sufferings were great, he would reply,
"`They are small indeed when compared with those of my dear Redeemer.`"
Once, about midnight, he broke forth in fervent supplication for a considerable time,
concluding with these words, "`Yours is the power,
mine is the weakness--yours is the glory, mine is the shame--Amen.`"

During the last few days of his life, being extremely sore and weary with lying,
he suffered much pain whenever he was moved, yet did not complain,
but said he humbly hoped that his patience might hold out to the end;
often desiring the prayers of those about him.
The day before his death, his sufferings were extreme,
and he seemed desirous to be released, yet centered in resignation,
saying very sweetly to his father, "`pray for me, but be sure to say,
your will be done and not mine.
'`During the night he was at times much agitated,
and was concerned lest he should say anything amiss
during the unsettled state of his mind.
But in the morning this was mercifully removed and succeeded by a holy calm,
which no language can express,
and of which all in the room seemed in a degree to partake.
From this time until his death, about an hour and a half, he was engaged in supplication,
but his voice was so feeble that little could be understood; yet once,
he clearly articulated, "`Your will be done.`"
He departed without a struggle, on the 1st of the fifth month, 1819,
aged sixteen years and a half.

[.asterism]
'''

HENRY ATKINSON, was the son of William and Ann Atkinson, of Darby Dale, in Yorkshire,
England.
Previous to his leaving Ackworth school, symptoms of a complaint appeared,
which finally terminated in his decease;
and this affection soon increased so as to render much bodily exertion impracticable.
Being a youth of a religious turn of mind,
much of his time was spent in retirement and meditation, the good effects of which,
more conspicuously appeared as the period of his dissolution approached,
proving the efficacy of divine grace,
and offering encouragement to others of the rising generation
to love and serve their Creator in the days of their youth.

13th of second month, 1825.
Several of his relations sitting by him in stillness,
he desired his sister to read the 25th chapter of Matthew, which being done,
he commented on the words "`I do not know you, depart from me you wicked and slothful servant,`"
saying, "`What a situation to be in!--how needful it is that we should be prepared!
Though you are all well at present, you know not how soon you may be laid as low as I am,
and there is enough to do to bear the pains of the body without having a troubled
mind--but I hope to bear with patience what may be laid upon me.
I have not committed such great sins as some have done,
yet I have done enough to repent of, and I hope the Lord will forgive me.
When I was at Ackworth school, once or twice I told an untruth,
for which I was smitten to the ground,
and fell down on my face and begged of the Lord to forgive me.`"

He then spoke of the contrast in the circumstances of Lazarus and the rich man,
and the awful condition of the latter; adding,
"`What a sad state such are in who trust in riches!
If I had all the world, what would it profit me at such a time as this?`"
alluding also to the awfulness of eternity,
that "`when thousands and thousands of years were expired,
it was still but as the beginning.`"
Seeing some of his relations weep, he said, "`Weep not for me, but weep for yourselves;
I hope my peace is made with God,
and I don`'t know how soon it may please Him to take me to himself.`"

21st of second month.
This morning he prayed fervently that the Almighty
would send the messenger of death quickly,
but soon added, "`Although I wish to be gone, yet the Lord`'s time is the best time,
and it is not right to wish for any other.`"
His agony being great, he repeated some expressions interceding for ease,
and presently after remarked, that "`the way to heaven lay by the gates of death,
and what a +++[+++fearful]
thing it would be for sinners to be so near dying as he was,
and yet in an unprepared state.`"
Towards evening, his sufferings continuing,
he prayed with much fervour that the Lord would keep him, adding, "`Lord Jesus,
receive my spirit.`"
He expired on the following morning; aged sixteen years.

[.asterism]
'''

TUDOR BRAIN, of London, was taken unwell when about seventeen years of age.
Being removed to the country with a view of benefitting his health,
he was often observed to retire alone into the fields,
and would sometimes return with marks of weeping on his countenance.
His friends apprehended this might proceed from the fear of death,
but he informed them "`he was not afraid to die,
but willingly resigned himself up to the will of God, either for life or death.`"

About a month before he died, he became so ill as to be confined to his chamber,
but through divine condescension, was favoured with the sense of the Lord`'s presence,
and frequently mentioned his full assurance of future happiness; saying,
"`Come Lord Jesus, come quickly and receive my soul.`"
On one occasion he called for a bible and read the
17th chapter of John with trembling lips,
and when he came to the 20th verse, viz. "`Neither pray I for these alone,
but for them also which shall believe on me through their word,`" he was much affected.

The day before his departure, he was extremely ill,
but several of his friends visiting him, he seemed refreshed and comforted,
observing to his mother, "`How merciful is the great God to me,
that has put it into the hearts of good friends to visit me.
There are healthier and younger lads than I, who are gone before me,
a poor consumptive lad--he has spared me--surely I never shall forget his mercy.`"
Then addressing himself to the Almighty, he said, "`O, glory,
glory and praises are yours forevermore.
O merciful God; you are merciful;
I can say that I have found it so--that when I had no breath,
I have sought you and it has been given me.`"

Seeing his parents weep, he said, "`Be not troubled for me,
for I am going to a better place.
If it be the will of the Lord, he can raise me, but if not, his will be done.`"
Then fixing his eyes upon them he said, "`You are the nearest in the world to me,
but yet there is a nearer that is above.`"
After a pause, he added,
"`In my younger years I have gone by myself into the meadows and have cried to the Lord,
but knew not where he was; and when I heard his voice, I trembled, and as I gave up,
the Lord Jesus made himself known to me; then I knew what I sought for.`"

A relation expressing a desire that those present might be prepared for their latter end,
he said, "`You must pray, and hang, and lean upon the Lord Jesus Christ;
for it is of Him, and through Him, that we must expect salvation.
Without Him you can do nothing, for He died for sinners,
and he is very merciful to forgive--he has forgiven me, blessed be his holy name forever.
Although some be hardened and stubborn, yet the Lord is merciful;
he can and may forgive--but you that are in the truth, keep in the truth.`"

About two hours before he died, he prayed as follows, "`Lord God,
be merciful--you are good, you are bountiful.
Lord have mercy on me--come Lord Jesus, have mercy.
You died for sinners--glory, glory to the God of heaven.
Oh, praises to your name--Lord Jesus receive my soul.`"
Presently after, "`Oh! what a glorious kingdom am I going to! there are dainties enough!
Oh, what a numerous army has my God.`"
Thus with a song of praise on his lips he finished
his earthly course and we have no doubt,
has entered that glorious celestial city,
not one of whose inhabitants can say "`I am sick.`"

[.asterism]
'''

ANN CROWLEY, daughter of Thomas Crowley of London,
during an illness of several months continuance,
was preserved in much patience and uttered many expressions,
showing the fervent and heavenly state of her mind.
Through the power of the Lord Jesus, who conquered death,
and gives his saints the victory over it,
she was enabled to contemplate the close of her life without fear, saying,
"`The pains of death are hard to bear,
and I am sensible they are not on me now--but they
are near approaching--death is no terror to me;
O death, where is your sting!
O grave, where is your victory!
My dear mother, it will be a bitter cup, but it is of the Lord`'s preparing,
and therefore drink it willingly.`"

On another occasion she said, "`This is hard work--it is indeed hard to bear,
but the Lord is with me in these trying moments.
I did not think my dissolution was so near, but I am ready.
Take me, Father, take me to yourself this evening, if it be your will,
for I long to be with You in paradise.
Though I have endured so many moments of agonizing pain,
the Lord has been my support through the whole,
and I doubt not will continue to be with me to the end.
O,
Father--Father--Father--bow the heavens and come down--be with your people universally,
all the world over.
Why do you weep?
Weep not for me, but give me up to the Lord, for I am happy,
far happier than I can express.
I wish every one of you could feel what I feel at this time,
for it is beyond expression--Oh! it is like a heaven upon earth--it
has not entered into the heart of man to conceive what good things
God has in store for them that love Him.`"

She earnestly entreated one of her sisters to make
a full surrender of her heart to the Lord,
saying, "`O my sister, give up-give up now in the days of your youth,
for the Lord loves an early sacrifice--O prepare yourself,
lest it should please the Lord to cut you down in the flower of your youth.`"

About two weeks before her decease she prayed to the Almighty as follows,
"`You have been pleased to give me a taste of your goodness, and a sight of your glory,
and it is glorious indeed.--But O Father, I long to be with You,
that I may enjoy it in a more plentiful manner.`"
Then, as if she had received an assurance that her prayer was heard,
added "`The gates of heaven are open to receive me.`"
At another time she said,
"`I have never murmured at what it is the Lord`'s will I should suffer,
but I was content if the pain had been much greater,
if it was the will of my heavenly Father.
O Lord, I long to be with you;
when my soul shall join the angels and archangels that are in heaven.`"

To her brothers and sisters she said, "`It is my desire that you,
my tender brothers and sisters, may come to the same experience.
I was visited long before I was laid on this bed of sickness: if I had not been,
it would be miserable +++[+++for me]
indeed`"--and a little after, "`My spirit was warmed in the renewing of your love.`"

About six days before her close she sent for her three brothers separately,
to her bed side, and in a most tender manner cautioned them against pursuing the riches,
gaiety and grandeur of the world; and advised them to walk in the path of virtue,
to keep close to divine instruction, and to watch and pray continually; saying,
"`I feel it needful even on my deathbed.`"--To one of them she said,
"`Give up,--O give up--remember, the fear of the Lord is the beginning of wisdom;
seek that wisdom now in the days of your youth--Step gently along,
and keep your mind low and humble before Him.`"

After this she lay still for some time, and then observed,
"`Though painful my nights and wearisome my days,
yet I am preserved in resignation and patience.`"
Some of her friends coming to see her, she expressed to them,
"`My pains of body are great, but my dependence is on the Lord,
and my only comfort is in Him.
I thought from the beginning that I should not get over it,
but within these three weeks I have seen clearly that I shall not.`"
She also observed that her mind had been visited
by the spirit of Christ long before her illness,
and she had felt great uneasiness in wearing gay apparel,
and also in speaking in the plural language to one person,
and had found it difficult to take up the cross in these respects,
but when she did her satisfaction was great.
"`Oh! said she, what I feel for those whose minds are involved in the world.`"
Many other expressions uttered by her on this occasion
evinced the happy state of her mind,
and to one of her friends she said, "`I am ready--I have nothing to do but to die.`"

The evening before her departure,
she exhorted her sister against indulging a spirit of pride in her dress, adding,
"`Gaiety proceeds from pride, and pride is the root of all evil.`"
In the night her pain increased and the approach of death
was apparent--much of her time was passed in prayer;
and calling for her mother,
she bade her "`Farewell,`" and expired the 12th of second month, 1774,
being not quite seventeen years of age.
