== Chapter 7

[.chapter-synopsis]
* Frederick Hunter
* Ruiter Sholl
* James Parnell
* Isaac Walker
* Grace Watson
* Sarah Crook

FREDERICK HUNTER, son of Simeon and Sarah Hunter, of Sherburn, England,
deceased the 30th of sixth month 1822, aged eighteen years.
Impressed with the importance of a guarded education,
his parents placed him at Ackworth School,
where he manifested a docile and submissive disposition,
and the habits of simplicity which he acquired there, were not soon effaced.
From Ackworth he went to Leeds, and afterwards to Epping School,
where symptoms of a disease in his knee appeared,
and he returned home about mid-summer in 1820.

Early in the following spring, being on a visit at Highflatts, his knee became worse,
and his parents thought it expedient to remove him home.
On his arrival at Sherburn, his mother was much affected at his emaciated appearance;
observing which, he said to her, "`Do not weep,
mother! for I am persuaded all this will terminate for the best.`"
After this he was seldom able to sit up for more than an hour at a time,
but although his bodily afflictions increased, he was never heard to murmur.

In narrating some transactions of his past life to his mother, he remarked,
"`I know that I have sinned; but having obtained pardon, through redeeming love,
I feel all to be done away.`"
On fifth-day morning, the 27th of sixth month, as his father was sitting by his bed side,
after a solemn pause, Frederick said to him,
"`I feel it to be my duty to express my obligations
to you for your great care in bringing me up,
and educating me in the way you have done; and also to my dear mother,
for her affectionate attention all my life long, and particularly during my long illness.
It further appears to be my duty to give you a few
hints respecting things of a more serious nature.
Be not high-minded but fear.
An incessant love of this world has done much harm to many;
therefore love not the world nor the things of the world.
If any man love the world, the love of the Father is not in him.
I feel as though I could not sufficiently praise
the Lord for what he has done for my soul.
O, help me to praise Him, for He is my strength and my song,
and has become my salvation.`"

After this his mind appeared to enjoy a sweet calm,
and when his aunt was taking leave of him, he said to her,
"`Farewell--you see how happy I am,`" and soon after to his mother,
"`I want to be gone home--I long to be gone home.`"
These were the last words he was heard to speak;
and in about two hours his spirit departed to the mansions of rest and peace.

[.asterism]
'''

RUITER SHOLL, son of John and Elizabeth Sholl, of London,
was educated at Ackworth School, and in the early part of the year 1824,
placed apprentice at South Shields.
Although his general conduct was such as to win the
esteem of the family in which he lived,
yet he sometimes evinced an unwillingness to submit to those salutary
restraints which a conscientious master thought it proper to exercise,
and he formed an acquaintance with some young persons,
whose society was a disadvantage to him.

In the year 1827, he became unwell; the disease gradually settled on his lungs,
and though an amendment was sometimes apparent, yet its duration was short,
and it became more and more obvious that he could not survive long.
In the sixth month, he was removed to London; but up to a late period of his illness,
little had been said to him on the danger of his situation,
and he evidently appeared disposed to avoid conversation of a religious nature.

In the twelfth month, a friend who called to see him, found him very weak,
suffering from acute pain in the chest,
and his whole appearance indicating a near approach to the house appointed for all living.
He received the visit with marks of satisfaction:
an opportunity of much solemnity occurred,
in which the visitor thought it his duty to apprise the invalid of his critical situation,
expressing an earnest and affectionate solicitude that the great
work of redemption and sanctification might be accomplished;
and turning the attention of his young friend to Him from whom all saving help comes,
the atoning sacrifice and mediation of a crucified and risen Saviour.

From this time his mind was much occupied with the prospect of death.
The certainty that his immortal spirit must soon
appear before its Almighty and impartial Judge,
deeply affected him, and he ardently desired to be prepared for the awful event.
Although, through the restraining power of Divine Grace,
he had mercifully been preserved from the commission of any gross sin,
yet his association with those who were not governed by religious principle,
had led him from obedience to the known will of God,
and at this period of serious self-examination,
he found that moral rectitude alone was insufficient to afford him peace of mind,
or that sustaining hope of acceptance in Christ Jesus,
which the work of regeneration only can confer.

Great were the conflicts of mind which he suffered before he was
brought to experience the precious evidence of forgiveness;
clearly pointing out to those around him,
the necessity of an early submission to the yoke and cross of Christ.
During this season of mental suffering,
he was often engaged in supplication to his heavenly Father,
and He who afflicts not willingly, but wounds to heal,
was at length pleased to dispel the clouds of distress and doubt,
and animate his disconsolate spirit with a humble but stedfast
hope of an admittance into the mansions of eternal rest,
when time to him should be no more.
His mind now became composed and tranquil, and addressing his mother he said,
"`My dear and tender mother, do not grieve for me, but think of the blessed change,
when shall be freed from my bodily sufferings,
and permitted to have a mansion in heaven where I shall behold my Saviour`'s face,
there to join with angels in singing hallelujah forever and ever.`"

His weakness had become so great that he could scarcely
raise himself in bed without assistance,
and he often prayed to be released.
He could now contemplate death without dismay,
in the cheering hope that all would be well--saying, "`Oh! that my hour were come.
I long to be gone.`"
He was much interested on account of one of his school-fellows,
and said to him in substance, as follows--"`Be very guarded in your conduct,
the enemy is constantly devising mischief.
You are in a very dangerous and critical situation, lay your soul open to your Redeemer,
and put your trust and confidence in Him.
I am going where I shall behold the face of my Redeemer.
He has guarded and watched over me.`"

He frequently said with much feeling, "`Oh! for patience!
Father of mercies, grant me a little ease--Oh! grant a little ease,
and if consistent with your gracious will, preserve me in patience to the end.`"
At another time, in feeble accents,
he thus interceded with the Almighty--"`Have compassion upon me, a poor sufferer,
and if it be consistent with your good pleasure,
take me to yourself--Wash me and make me clean in the blood of your dear Son,
and be pleased to take me to yourself.`"
He also prayed for his mother,
and concluded with grateful acknowledgments for the blessings bestowed on him.
Afterwards, he observed to one of his brothers,
"`I am now favoured with a clear prospect that when the change shall take place,
there is a mansion prepared for me in the kingdom of heaven.`"

He continued in this state of mind and with but little apparent alteration in his disease,
until the 20th of the first month 1828.
Having passed a restless night,
he was much exhausted and requested to be placed in an easy chair.
Soon after which he was heard to say, "`If consistent with your holy will,
be pleased to release me from my sufferings and take me to yourself.`"
He then raised his eyes and faintly uttered "`It is done--Oh!--it
is done`"--and passed peacefully away,
in the nineteenth year of his age.

This interesting case furnishes another instance of the adorable mercy of God,
in pardoning the returning and penitent sinner through
the blood of the everlasting covenant,
and preparing the immortal spirit by great tribulation, to enter the kingdom of heaven.
Yet the deep and painful conflicts which he had to pass through,
ought to teach us not to presume on divine mercy, but by a lowly,
humble and obedient walk with God endeavour, while in health,
to experience a state of preparation for death;
that being born again of the spirit of Christ,
when the solemn messenger is sent to summon us from time to eternity,
we may have nothing to do but to die--and, in humble confidence, be able to say,
"`Come Lord Jesus--your servant is ready.`"

[.asterism]
'''

JAMES PARNELL was born at Retford, in Nottinghamshire,
and embraced the principles of the religious Society of Friends at an early period.
About the year 1654, being then in the 17th year of his age, he visited George Fox,
who was at that time a prisoner at Carlisle: here he disputed with,
and confuted those who opposed the doctrines he promulgated;
and afterwards travelled southward, preaching the gospel in Huntingdonshire,
the Isle of Ely and parts of Cambridgeshire, and was the first of those called Quakers,
who preached in Essex, many being converted by his ministry to the Lord Jesus Christ.

About mid-summer 1655, he went to Colchester, and on the day after his arrival,
being the first of the week, he preached the gospel to thousands in that town,
first at his lodgings, then at the public place of worship for the parish,
and then at a large meeting appointed for the purpose;
after which he disputed with the town lecturer,
and with another person in the French School.
In all these labours of love he was enabled to show
forth the wisdom and patience of Jesus Christ,
convincing many who believed unto salvation,
and by sound doctrine putting to silence the gainsayers.
But some whose hearts were hardened, cruelly abused him,
beating him with their fists and with sticks--particularly one man,
who struck him with a large staff as he came out of the meetinghouse, saying,
"`There--take that for Christ Jesus`' sake`"--to which he meekly answered, "`Friend,
I do receive it for Jesus Christ`'s sake.`"

After he had fulfilled his mission at Colchester, he returned to Coggeshall,
where a fast had been appointed:
here he was unjustly apprehended and sent to Colchester castle,
and from there brought in irons to Chelmsford assizes.
Although his persecutors could find nothing whereof to accuse him,
except such things as related to the law of his God,
yet they fined him forty pounds and committed him close prisoner to Colchester castle.
His keeper allowed none to visit him, except such as came to abuse and beat him,
sometimes not allowing him to have food brought to him, and at other times,
when it was brought, they unfeelingly took it away;
and compelled him to lie on the stones, which in wet weather would run down with water.

They subsequently put him into a hole in the wall,
at a considerable height from the ground,
the only access to which was by a ladder six feet too short;
and would not allow his food to be taken up to him,
nor permit him to draw it up by a cord and basket which his friends had kindly provided.
He was therefore obliged to ascend and descend by a rope,
and after suffering long in this hole, which had no aperture for the admission of air,
or for the smoke to pass out, his limbs became so much benumbed,
that one day having climbed up to the top of the ladder,
and attempting to catch at the rope,
he missed it and fell down from a great height upon the stones,
by which his head and body were much wounded, and he was taken up for dead.

After this, he was put into another hole called the oven, though some ovens are larger,
where they would not allow him to make use of charcoal,
neither would they accept of bail, nor body for body,
which some of his friends freely offered,
in order that he might have an opportunity of recovering from the injuries he had received.
The door of his prison being one day opened,
he ventured to walk out into the jail yard for air and exercise,
at which the jailer was so enraged that he locked the door and
kept him out all night in the severest weather in winter.

The blessed fruits of the religion he professed shone
forth conspicuously in his long and painful imprisonment,
enabling this dear youth to suffer patiently and
cheerfully for the testimony of a good conscience,
and to count all things but loss and dross,
in comparison of the excellency of the knowledge of Christ Jesus his Lord.
At the hands of his relentless persecutors he could find no mercy,
yet he meekly endured it all,
committing his righteous cause unto Him who is the refuge of the oppressed,
and the helper of the needy in his distress.
At length their repeated cruelties destroyed his health; he grew weaker rapidly,
and the happy hour was evidently at hand when he was to be liberated from their power,
and translated into the glorious kingdom of the dear Son of God.

Near his departure, being in a triumphant frame of mind, he said to those about him,
"`Here I die innocently.`"
And a little after--"`This death I must die--I have seen
glorious things.`"--Then addressing his friends asked,
"`Will you hold me?`"--and they expressing their resignation to part with him, he added,
"`Now I go.`"
He had often said that one hour`'s sleep would cure him of all his pains,
and he soon fell into a sweet slumber which continued about an hour,
when he quietly departed to his everlasting rest in Jesus,
being in the nineteenth year of his age.

[.asterism]
'''

ISAAC WALKER, son of Peter and Mary Walker, of Dean Scales, near Cockermouth, Cumberland,
was born the 7th of second month, 1825.
From a child he was of a sweet disposition, and being endued with a good understanding,
and a quickness of perception,
he sought the company of individuals of more experience than himself.
He was nevertheless fond of play, and was not infrequently led into childish follies,
for which he afterwards endured much heartfelt sorrow.
About the eleventh year of his age, he was sent to Wigton school,
where he remained as a scholar, three years, after which he was taken as an apprentice.
He fulfilled the duties of this situation in an exemplary manner,
and by the propriety of his conduct, and the amiability of his disposition,
he endeared himself to all around him.

It was during this period, and when he was rather more than fifteen years of age,
that an event of a very impressive nature, took place in the school,
viz. the removal by death, after a protracted illness, of one of the boys,
in whom the power of Divine grace was remarkably exemplified,
and who had been his intimate friend and companion.^
footnote:[P. W. Hall, of whom see a brief account, page 88]

The following extracts are from Isaac Walker`'s letters, written at this period:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Brookfield, 1st month 29th, 1841.

The time has now arrived, a time which I have long anticipated,
when my late schoolfellow, P. W. Hall, is about to be gathered to his rest.
In all probability, he is now laid upon that bed from which he will never rise,
and his flitting hours are numbered,
and his existence here about to be terminated in death;
but how pleasing is it to observe his pious resignation,
and firm belief in the mercy and long-suffering of the One Great Sacrifice,
made for mankind, by the Beloved Son, who, to use one of P. W. H.`'s expressions today,
"`Left the bosom of the Father, and came and offered himself for guilty man.`"

--

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Brookfield, 2nd month 8th, 1841.

[.salutation]
Dear Sisters,

I hope soon to have a little more leisure,
for since W. A. G.`'s departure, much labour has rested upon me.
But such times are, or may be, very useful; for it is then,
that the mind finding peace from no other source, turns, ardently turns,
to the Fountain of All light and life, and seeks the presence of Him,
whose arm is strong to deliver,
and whose right hand is able to save to the very uttermost.
P+++.+++ W. H. still languishes upon the bed of death, the last, and in some instances,
the pleasantest period of life here below; and truly it seems to be such with him.
His mind, freed alike from the cares and pleasures of this life,
turns to God and to that happy land, on which his thoughts are centred.
Ah! happy state!
How glorious to leave every cumbrance behind, and to soar in faith to the land of peace,
in hourly expectation of quitting this forever,
and of being added to the "`hundred and forty and four thousand,`"
who are continually praising the Lord God and the Lamb.

--

Isaac Walker had a strong predilection for Natural History,
and often devoted his leisure hours to the study of it.
It is interesting to know, that even in this, his favourite pursuit,
he was careful to preserve a very tender conscience,
and also to watch over the boys who had a similar taste;
instructing them strictly to avoid any approach to cruelty.
About the close of the year 1841 he was liberated from his engagement at school,
from an apprehension that his health was too delicate to
permit him to fulfill the arduous duties of the situation;
indications of pulmonary disease having frequently appeared.

After having been at home some months, his health appeared so far recruited,
as to induce him to wish to return to the school, which he did in the fourth month, 1842,
but the symptoms of the disease again making their appearance,
and in a more alarming degree, he finally relinquished his situation.

Notwithstanding the blamelessness of his life and conduct in the sight of men,
he was made deeply to feel the corruptions of his own heart
when brought under "`the spirit of judgment and burning.`"
When retiring to rest, on the 7th of fifth month, he thus expressed himself:
"`I have sunk deep, very deep, into iniquity, yet I believe,
if I should be called away soon, it will not be without a hope of forgiveness.`"

Fifth month 10th. His sister alluding to the many advantages he had enjoyed,
beyond the lot of most, he replied, "`Whatever use I may have made of them;
I feel however, very calm, and so free from temptation,
that I am persuaded the Almighty`'s arms are underneath for my support.`"
Adding, "`I have been a great sinner; my sins are more than the hairs of my head,
but the blood of Christ cleanses us from all sin.
Yes, though my sins be as scarlet, they shall be as snow,
though they be red like crimson, they shall be as wool.
The Lord is good and gracious, slow to anger, and of great mercy.`"
On his sister remarking to him, that if he were taken in early life,
he would escape many troubles, he replied, "`Yes, I shall escape a flood of iniquity.
I scarcely expect to recover, and I scarcely desire it; I have no will of my own;
the will of the Lord be done.`"

On the 26th of fifth month,
he was informed that the medical attendants now considered his case beyond their skill.
He received this information with the greatest calmness, and meekly replied,
"`I thought so; for the last few days I have felt that I must go,
and I have no wish that it should be otherwise.`"

During the day, he was very composed,
often dwelling on the love and mercy of God in Christ
Jesus;--a theme on which he loved to muse.
In the evening he expressed himself thus,
"`I am lost in wonder when I consider how often I have backslidden,
after having for some time been enabled to do right;
and when again made sensible of my sins, with a desire to turn from them,
how ready the Lord has been to receive me!
His mercy is unbounded!
Oh! what an awful thing it must be,
when an unrepenting profligate is informed that he must die in a short time.`"

Fifth month 31st. He said, "`Satan has been tempting me with the query,
'`How can you be saved,
seeing you have done nothing to promote the glory of God?`' But I have just been thinking,
if my life were spared to three score years and ten,
I should still have nothing of my own to trust to.
No: It is all through mercy, pure, unmerited mercy.`"

On one occasion, after sitting in stillness for some time, he thus expressed himself,
"`It is a fearful thing to fall into the hands of the living God;
it makes the flesh to tremble, while the renewed spirit may rejoice.
Oh! the Lord is merciful ever ready to forgive the repentant sinner.`"
In a time of mental anxiety,
he told one of his sisters that he had very frequently supplicated, that,
if it pleased his heavenly Father,
he might have a yet clearer evidence that all his sins were forgiven; and that,
during the night before, while thus engaged, the query, Where is your faith?
passed quickly through his mind, conveying both reproof and encouragement.
Since then all fear of death had been taken away.

Sixth month 1st The dear invalid`'s spirit was refreshed
by an acceptable religious visit from some Friends.
When they were gone, he remarked, "`What a delightful opportunity we have had;
oh! it was sweet!`"
He then spoke of the great love of God, in having drawn him as out of a deep pit,
and freely forgiven all his sins, saying,
"`They are all washed away in the blood of the Lamb.
What encouragement there is in the Scriptures of Truth, to the repentant sinner!
The promises are all to him whose heart is changed.`"
He appeared at this time much cheered by the passage,
"`The Lord looks at the heart,`" saying, "`How very good we may appear unto men,
while the heart is estranged from God; but the heart must be changed,
and then we may look for forgiveness.
It would profit nothing, if we wept for a whole week,
if it were only the working of the passions: we must feel our sins a burden,
we must hate all sin; and then.
He who died for our sins, has promised to give rest to such as seek Him.
When I consider what a few filthy rags I have,
to lay in the scales against mountains of sin,
I marvel much at the love of God in Christ Jesus.`"

One day, in the fluctuations of the disorder, it was remarked to him,
that he appeared a little stronger; he replied, "`I may improve for a time,
but I have no thoughts of permanent recovery, neither do I desire it;
but not my will be done.`"

On another occasion, when much exhausted, a person who was present said,
it was trying to see one so young, so reduced by illness.
He replied,
"`I would not exchange my situation with anyone possessing
all the health and strength this world can bestow,
without the peace of mind I now enjoy.`"

Seventh month 6th. On one of his sisters saying, she thought his strength was decreasing,
he sweetly answered, "`Yes, I am getting nearer and nearer to my everlasting rest.
Oh! it is a happy thought, that I have nothing to do but to die.
Rest assured that whenever the change takes place, whether suddenly or more gradually,
I have now no doubt all will be well.
I am going to the mansions of endless bliss, where tears are wiped from every eye,
and sorrows are unknown.
The Lord is indeed very merciful to me, and I firmly believe.
He will beat me up above every trial and temptation.
Satan does at times tempt me to doubt, but the Lord preserves me above all.`"
At another time,
he spoke largely of that sweetly absorbing theme the love of God in Christ Jesus, saying,
"`Where could such poor mortals as we look, if it were not for a Saviour?
But our finite comprehension can form no idea of this love;
we may admire and be lost in amazement, but we can do nothing more while here.
Oh! there is no joy, like the joy which the righteous feel:
there may be sensual pleasure felt at times by the wicked, but no real joy or comfort,
for they are like the troubled sea, when it cannot rest,
whose waters cast up mire and dirt.
But the righteous are all serene and peaceful, looking forward to a better home.`"

Some time afterwards he said,
"`The pains of the body are much easier to bear when there is a peaceful mind.
The Lord is merciful; all this that I endure, is sent in mercy, yes, all in mercy.`"
His sister expressing a hope that he would be spared much suffering, he quickly replied,
"`Think what the dear Saviour suffered; what matchless love,
to leave so glorious a kingdom, and come down to this earth, even among his enemies,
who He knew,
would persecute and slay Him! and what a marvellous
display of love is there in that passage,
'`Father, forgive them,
for they know not what they do!`' I have been meditating upon this today,
and how pleasant it is, followed by a sweet peace.`"
In a little time he added, "`I shall be happy forever,
and I trust we shall all meet on high;--but we must strive.`"

On its being remarked to him, how insignificant this world would now appear in his view,
he said, "`The pleasures and treasures of this earth, are not worth a thought,
but on it there are millions of immortal souls.
Oh! that these would consider their latter end,
for it is a fearful thing to die unprepared.`"

Another time, when reduced to a state of great weakness, he said to his mother,
and to one of his sisters, "`You seem to think my cough is troublesome,
but I have always had strength given for all my need; and I trust I shall to the end;
and patience fails not; but remember, it is not my own, no, I am nothing,
and have nothing;`" his sister added, but you will soon have all things.
"`Yes,`" he replied, "`I have nothing to do but to die.`"

After this, when asked if he wished to see his medical adviser, he said, "`I think not,
there is nothing more that he can do; I shall probably be released in a few days,
and then what a glorious change!`"
This day he was unable, for the first time, to come downstairs,
after which he survived about a week, in a state of great bodily weakness,
but nevertheless he was strong in the Lord, and ready to depart,
but patiently waiting his appointed change.
He again expressed his full belief that all his sins were forgiven, and that,
through mercy, he should be admitted within the pearl gates.

The First-day before his death, he appeared to be in great pain,
but no murmur or impatient word escaped his lips,
nor indeed had such been known to do so during the whole of his long illness.
He maintained a cheerful equanimity,
wishing to make his sufferings appear as light as possible.
Towards three o`'clock next morning, thinking he was going,
the family were called to his bedside, of whom he took an affectionate leave.
He then inquired how long they thought he might remain.
On being told they did not think he would continue much longer, he gently replied,
"`I am thankful; all is peace, peace, peace.
Yes, rest assured, happy is my end.`"
On seeing his mother and sisters weep, he said, "`No, weep not,
but rather rejoice that I am going to Heaven, where all is joyful, peaceful,
happy forevermore.
Oh! my dear brothers and sisters, be sure you let me meet you all again.`"
On his father coming into the room, he said with great solemnity and affection, "`Father,
I have been strengthened to speak to the dear family,
concerning the glory of those eternal regions of bliss, to which I am fast hastening.
Oh! it is a glorious land, where all is peace, holiness,
purity and bliss forever and ever;--where the shadow of a cloud can never come,
nor any sorrow,--for God Himself shall wipe away all tears from every eye.
May you, and each of you, so live, that when your end comes,
you may be permitted to join me there.
I believe youth is the most favoured season for giving up the heart to God.
It is mostly the case, that an idly spent youth,
is followed by a blighted and slothful old age.
Youth is the season for improvement of all kinds, and I trust that many of you,
my dear brothers and sisters, may feel this to be the case, and spend your youth aright,
and be ready at all times to meet death in peace.
I am happy, happy, happy!`"
After this he revived a little, and, with the greatest possible calmness,
gave directions how he wished his books and other little tokens
of affection to be distributed among his near relatives.
He then said, "`Well!
I think I have settled all on earth,
let me now turn to heaven and see if all is right there.`"
After a pause, he added, "`Yes, all is right there.
I think there is no account against me there.
And now Lord Jesus, when it is Your will, I am prepared.
Sweet Jesus, if you had not died,--ah! the deathbed of the sinner!`"
After this he asked how long it was thought he might continue here;
he was told he might be taken any moment; he then said, "`I am thankful.
Oh! happy change.`"

Contrary to all expectation, he was permitted to revive for a short time,
and sweetly trusting in Him, who is everlasting strength, he said,
"`It may be the Lord`'s will to have another token of resignation, before He takes me.
I trust all will soon be over, but we must wait the Lord`'s time.
I feel even more patience than yesterday.
How different would be my condition if I knew that after a few moments,
I must enter those dark abodes, where the worm dies not,
and where there is a fire in the soul that never can be quenched.`"

When he was informed that his symptoms now indicated his approaching end, he smiled,
as if this was welcome information, and then said,
"`It is pleasant to feel patient and resigned,
perhaps leaning more to a wish to go than otherwise.`"
Then to one of his sisters he said, "`Oh, Agnes! would it not be sweet to be in heaven!`"
Soon afterwards, he offered up this petition,
"`Oh Lord! grant me strength to endure whatsoever You are pleased yet to send,
and to bear it in that patience You require!;
and grant me your Almighty support even to the end.`"

Second-day evening about seven o`'clock he observed, "`Patience is yet granted.
I should like us to have a little stillness together;
oh! let us praise the Lord to the end.`"
It was now thought that his close was near,
and his soul was lifted up in prayer and praise;--he supplicated thus,
"`Oh! heavenly Father!
Almighty God!
If it be your will now to release your unworthy servant, Your will be done.`"
A little while afterwards he exclaimed, "`All is peace, Oh! the Lord is merciful,
full of compassion; let us all rejoice in him.
A change from an earthly to a heavenly Kingdom, will truly be a glorious one.`"
On observing his mother weep, he said, "`Don`'t weep, mother, but give me up freely;
you have others to look to.`"

About this time he said, "`I think the hour of my departure is nigh; oh, how sweet I oh,
how happy!
I believe there is nothing more to accomplish.
It may be if I fall asleep, I shall not revive much again in this world; if so,
farewell! and mother, and all of you, be ready.`"

After a time of stillness he said, "`I fear I am not yet to go.
It is rather hard to bring the mind back to earth,
when it is so near Heaven;`" he soon afterwards observed,
"`Satan tempts to break very good resolutions; he has been trying to tempt me,
but the Lord has delivered me out of his power.`"
He now regained his normal composure, and said to his mother,
"`The Lord has given me resignation again.
Oh! the Lord is merciful.`"

Third-day morning, one of his sisters going to his bedside, he smiled sweetly, and said,
"`Well, Mary Ann, do you think that I shall get home today?`"
He sometimes expressed a fear, that he was too anxious to be gone, saying,
"`It would be so sweet to be released.
Oh! it is sweet to meditate on the mercies in store for me,
but my hours of meditation are well nigh over here.
I do not feel much strength given for supplication; pray for me to be patient,
willing to wait the Lord`'s time.`"

During the day, his sister inquired if his breathing oppressed him, it seemed so heavy.
He calmly replied, "`No; and, if it did, it would but release me.
I have been looking at my arm, and see it is getting very thin,
there will not be ranch weight left; but, if the soul strengthens, as the body decays,
it is everything I desire.`"

At a time of much bodily pain he remarked, "`These are but temporary sufferings,
and will bring their reward, they are all symptoms of my approaching end.`"
On taking leave of one of his brothers he said,
"`I have many dear brothers and sisters;`" he then called them all by name, and said,
"`But these are nothing to heaven.`"
After lying in a suffering state for some time, he gently said "`Come, Jesus, come!
O, Lord Jesus! receive my spirit.`"

When the little remains of strength were fast wearing away,
it was cheering to notice the state of perfect resignation, and lamb-like patience,
in which he was preserved, frequently repeating, in feeble accents;
"`All is now peaceful, all is now happy; Lord not my will, but yours be done.`"

On fourth-day morning, the 19th of 7th month, the last of his earthly existence,
he called his sister S. to his bedside, then held out his arm,
and asked in a whisper "`how his pulse felt?`"
On being told it was very weak, he said, "`Oh! yes.
I think before another day I shall have done with earth, and then.
Oh!
Heavenly Father! grant that peace may be my portion,
purity and holiness the covering of my spirit,
righteousness and goodness the clothing of my mind.
And Oh! will you keep my mind from wandering from you,
or in any degree murmuring against your holy will,
and may I in patience wait my appointed hour.`"
After this aspiration to his heavenly Father, turning to those about him, he said,
"`I am happy, very happy, quite ready to enter into the joyous Kingdom.`"

A little before the last conflict of nature, he sweetly uttered these affecting words;
"`Happy is the Christian`'s dying-bed; all peaceful, all happy,
all ready and longing to be at rest.
Oh! when the end seems approaching near, patience is strengthened,
all things are strengthened; faith is strong.
Oh! a deathbed is well worth waiting for, for sweet are the joys it promises.`"

Thus filled with all joy and peace in believing the
solemn and long anticipated moment of release arrived,
the conflict ended, and the patient sufferer sweetly slept in Jesus.

[.asterism]
'''

GRACE WATSON, daughter of Samuel Watson, of the County of York, England,
was a young woman of sober and circumspect deportment,
obedient to her parents and hating a lie--and towards the latter part of her time,
much given to retirement and reading.

During her last illness, she was under great distress of mind,
in consequence of the temptations with which she was beset,
but as she endeavoured to keep close to the Lord
and stay herself upon him in living faith,
he was pleased in due time to give her the victory and bruise Satan under her feet;
in grateful commemoration of this unmerited mercy,
she could experimentally sing the song of Moses, and the song of the Lamb,
ascribing all glory and honour and praise to his excellent and worthy name.

Having passed under the ministration of condemnation,
and patiently endured the judgments of the Lord for sin,
she experienced the first and fallen nature to be
changed and that new creation brought forth,
in which "`all things are of God;`" and feeling the
sweet incomes of the joy of His salvation,
she thus expressed herself "`O heavenly Father--what have you done for me this night?
How have you removed the crooked serpent and taken him quite away,
so that I can say truly "`Your will be done`'--You have shone in upon
me with your marvellous light--you have showed me the glory of your house,
the most glorious place that ever my eyes beheld--neither did I think you had +++[+++prepared]
such a place for any--much less for me,
a poor worm--once ready to think myself destitute.`"

On another occasion, "`If you require my life this night of me,
I freely give it unto you--O heavenly Father,
your will be done--If you have further work for me,
keep me in that which I now enjoy--you have made
my cup to run over--you have taken away all my pain.
I am as if I ailed nothing,
though of myself I could do nothing--scarcely move one of my fingers,
my tongue being ready to cleave to the roof of my mouth.
But you have been a light to my feet and a lantern to my path.
How can I cease praising you, O God of power?
You are more to me than corn, wine or oil.
Your love is sweeter to my taste than the honey or the honey comb.
Oh! it is more to be valued than the costly pearls,
and the rich rubies--the gold of Ophir is not to be compared to it.
Oh! be blessed--praised--and magnified, forever.`"

Being asked how she was, she replied, "`I am but weak in body,
but strong in the Lord and in the power of his might.`"
On one occasion she expressed some doubts, but soon after added, "`Why do I so?
My case is no doubting one,
the Lord has created a clean heart and renewed a right spirit within me,
so that all fears and doubts are taken away.
The gates are open--the angels are ready to convey
me into the bosom of my heavenly Father,
where I shall sing praises with his redeemed ones.`"
During all her sickness she never manifested any desire to live,
but often expressed her entire resignation to the Lord`'s will,
whenever he saw fit to take her to himself--saying,
"`O Lord! do with me what you please; heavenly Father, your will be done.
What have you done for me, a poor stripling in comparison with many.
You have made my bed, you have taken away my pain, and my sickness is one.`"

She exhorted some present "`to prize their time and not
give themselves too much to the things of this world.
How many have laid up great riches, earthly treasure,
and in one night been deprived of it all.`"
Her sister weeping by her, she said, "`Weep not--remember David and be comforted.
The tongue of men and angels cannot declare the wonderful greatness of God.
O heavenly Father, how sensible of your presence have you made me.
You have strengthened me, otherwise I should not have been able to speak so much of you.
With you is fullness of joy, and at your right hand are rivers of pleasure forevermore.`"

Commenting on the parable of the ten virgins,
she admonished those present after this manner, "`Oh! therefore,
keep upon your watch tower, that whether He come at midnight, at cock-crowing,
or at the dawn of day, you may be ready, for that is the wedding chamber indeed,
and He is the heavenly Bridegroom.`"
She expressed the most lively and tender affection for her parents and relations,
and taking her sister by the hand observed, "`Though we be separated outwardly,
we shall meet in the kingdom of glory.
Oh! what cause have I to bless the Lord on their +++[+++her parents]
behalf, who I am sure never countenanced any evil in any of us, but reproved it.
The words of my dear and tender mother, I remember, since I was but ten years of age,
who said she had fought the good fight of faith,
and the crown of glory was laid up for her.
These words having remained upon my mind, and made a deep impression on me,
I can now say, I finish my course with joy and shall receive the crown of glory.`"

Her strong and unshaken confidence in the Almighty was conspicuous to the last, saying,
"`The Lord is a God at hand in six troubles and in
seven--no--if you bring me to the eighth,
you will never leave me.`"
She soon after departed this life aged above nineteen years.

[.asterism]
'''

SARAH CROOK, daughter of George Thompson, of Crook, in Westmoreland,
died the 6th of twelfth month 1702.

In her childhood she was concerned to remember her Creator and to live in his fear,
endeavouring according to the grace given her,
to promote the honour and prosperity of the Lord`'s cause.
She was endued with an excellent understanding, which,
being cultivated with care and sanctified by divine grace, her capacity became large,
as regarded things natural and divine.
In the Holy Scriptures and other religious works, she took great delight,
and was careful to practice the excellent precepts which she read there,
frequently speaking to the family respecting heavenly things,
and exhorting them to patience and virtue.

Her temper was cheerful and amiable; kind and compassionate to all,
courageous but not rash; tender and affectionate to her parents,
and watchful over her words and actions, lest she should give offence to any.
It was her practice to spend much of her time in retirement,
and in meditation on the things of God,
in which seasons she said the Lord was pleased to
break in upon her soul by his blessed Spirit,
and enable her to look with an eye of faith beyond time and mortality,
into an endless eternity,
accompanied with an assurance that it would not be long
before he would release her from all her pain and sorrow,
and take her to himself.

She suffered much from shortness of breath,
and being of a delicate constitution was often sick,
yet she bore it with patience and cheerfulness,
observing that "`The Lord was present with her, and comforted her in all her afflictions,
and spoke peace to her soul in the midst of her troubles,
which had made hard things easy.`"
During the course of her last illness, she uttered many weighty expressions,
giving suitable advice to those about her.
Observing her friends weep, she said, "`You trouble me to see you so;
why are you so unwise?
must we not all part?
What! is death a terror to you?
It is no terror to me--I am not at all daunted at it,
for I am content whether I live or die.
Cannot you freely give me up and part with me; I am but a poor infirm creature;
and it will be well with me.
I shall be freed from many troubles and dangers, which you will be exposed to,
that stay behind.
I see that as long as we are here,
we are liable to many temptations--I know they will be exercises to you,
but keep to that which is good, and God will keep you, for he has kept me many a time,
as I have kept my mind unto him.`"

At another time her father and mother and two sisters, standing by her bed side,
she said to them, "`I must die--and I have a word of counsel to you all;
Be faithful to the gifts that God has given you, I beg it of you;
and over-charge not your minds with anything of this world,
for you see how frail flesh is, and how soon we are gone.`"
"`I desire you to remember my words when I am gone,
that it may be well with you at your latter end,
and that you and I may meet in the mansions of glory, where we may never part.
All of you be content, for it is well with me... I have made my peace with God,
and I feel nothing to rise up in judgment against me,
for the Lord has forgiven me my sins and my iniquities.
My mind is very quiet and still, and has been ever since I began with this illness.
There is nothing cumbers my mind; not so much as a temptation is presented;
and I have been borne over my exercises far beyond my expectation.`"

Her brother being absent from home, she desired her dear love to be given to him, saying,
"`If I die, tell him from me that my soul is gone into everlasting rest,
where I hope we shall meet again in heavenly joy.`"
Soon after this, she was engaged in fervent prayer to the Lord,
for the preservation of those left behind when she was gone,
that as he had preserved her from many hurtful things,
so he would be pleased to help them through their exercises, as he had often helped her,
for which she blessed and praised his holy name.
"`I have often cried unto the Lord,`" said she, "`to help me through my exercises;
and he has answered my prayers many a time to my admiration.`"

Inquiring for her grandmother, who was above eighty years of age,
she took her by the hand and thus addressed her,
"`You are now very ancient--the Lord has been merciful to you, and given you many years,
far above what many attain to, and if you come short of making your peace with God,
you cannot say it was for lack of days.
But see to the improvement of your gift--I beg it of you--before your days be over;
that it may be well with you at your latter end,
and that your soul and mine may meet in heavenly joy.`"
A relation coming in and asking how she was, she replied, "`I am passing away in peace,
and so may all do that keep faithful to their God.`"
In a short time after, she thus addressed him, "`Dear cousin,
you are young and in the prime of your time--see that you serve God in the flower
of your age--the Lord has created you that you might serve him;
see you answer the end for which you were created.
I believe the Lord has a service for you if you be faithful to him.
I wish well for your soul as for my own,
desiring that you may be faithful to God in your day,
and have your account ready against your day of dissolution,
that you and I may meet again,
where we shall live to sing Hosannah to the Lord forevermore.`"

She desired her father and mother, "`Not to mind the things of this world,
but to serve the Lord,
who is worthy to be served--who is Lord of lords and King of kings,`" exhorting them,
to "`remember the words of their dying daughter, to live in love and charity,
and to be prepared for their latter end,
that they might meet in everlasting joy never to part.`"

To another relation she said,
"`I remember there was a time when you thought you should have died,
and you were under great exercise, for I believe you had lived a very loose life,
and the Lord smote you with his judgments.
And you made a vow, that if the Lord would spare you at that time,
you would amend and do so no more--but Oh! have you fulfilled your vow?`"
She then exhorted him to greater faithfulness, that he might obtain peace to his soul,
before the day of his visitation passed over.

Having endeavoured through the course of her life,
to answer the great purpose for which she was created,
by living in the daily fear of her Creator, and obeying his commandments,
she experienced "`the consolations of the gospel to abound by Christ Jesus,`"
supporting and cheering her spirit through a long and tedious illness.
The approach of death brought no terror,
and she was enabled by the power of Him who gives
us the victory through Jesus Christ our Lord,
practically to illustrate the truth of that triumphant exclamation of the apostle,
"`Death is swallowed up in victory.
O death, where is your sting?
O grave, where is your victory?`"
