== Chapter 10

[.chapter-synopsis]
* William Coates
* Thomas Phillips Wright
* Mary Barron
* Hannah H. Hartshorne
* Mary Brook Swetman
* Anna Maria Boyce
* Lydia S. Rogers
* Thomas Hattersly

WILLIAM COATES, of Sutton, in the Forest, Yorkshire, deceased the 22nd of second month,
1824, in the twenty-third year of his age.
He was of a kind and compassionate temper towards all around him,
very affectionate and tender to his parents,
and a diligent attender of religious meetings.
Being the eldest and only surviving son of his parents,
he evinced much sympathy with them in the prospect of his being taken from them;
and in the forepart of his illness when a little hope was entertained of his recovery,
he remarked that he sometimes thought he might be
restored for the sake of his father and mother.

As his disease grew worse,
his father inquired after the state of his mind in the prospect of futurity,
to which he replied, "`there appeared nothing to stand in his way,
but that he did not witness so clear an evidence as he could desire.
One morning, calling his parents to him, he expressed his dear love for them,
ut said he was going to leave them, yet he hoped they should meet again.
He then prayed with much fervour--"`Sweet Jesus! look upon me and help me,
that I may be as one of your sons,
and have an admittance granted me into your Father`'s kingdom,
if consistent with your holy will--Oh! sweet Jesus, your name is dear to me.`"

At another time he supplicated after this manner, "`O Lord,
consider my weakness--my poor weak state,
and let me have a little hope of being admitted into your glorious kingdom.
Teach me, gracious Saviour, to pray aright,
that I may be where there is no sorrow or crying--I thank you, Lord Jesus Christ,
for enabling me to put up these humble petitions.`"

On another occasion he thus breathed out his fervent supplication, "`O Lord,
if consistent with your holy will, I humbly pray you to make me love You above all;
indeed, I can with sincerity say, I do love you above all.
Be pleased to grant me an admittance into your glorious kingdom,
where there is no sorrow,
and where nothing that is unholy must ever enter--where praises, honour and renown,
are ascribed to your great name forever and ever.
Amen.`"

He observed that "`he had done with the world, and had committed all to the Almighty,
who was a gracious God, merciful and worthy to be praised.
He had done all things for him, who could do nothing for himself,`" saying repeatedly,
"`Your will be done.`"
During the course of his illness he often expressed in a very lively manner,
the Lord`'s tender love towards him, and at one time broke forth in this manner,
"`Father continue your love to me, and make me fit for your kingdom.
Sometime since I was afraid to call you Father.
I love the Almighty and I hope he loves me.
Seek and you shall find--what encouragement!
I have sought him with all my might: I feel as much love as ever.`"

His bodily weakness increased,
yet his faith and confidence in the Divine Arm seemed to strengthen,
and he continued in a sweet composed frame of spirit,
resigned to the Lord`'s will--on one occasion he said, "`Sweet Jesus,
strengthen me and make me fit for your glorious kingdom,
where there is nothing but peace and good will toward men.
Honour, dominion, and majesty forever and ever +++[+++be to you.]
Just and true are your ways, O King of kings--Honour and glory to your name.`"
The few last days of his life he was so weak and his voice
so low that it was with difficulty he could be heard.
About an hour before the solemn close, he appeared to be in supplication,
very little of which could be understood: the last words he was heard to say were,
"`Lord receive me,`" he then fell into a calm slumber, and quietly passed away.

[.asterism]
'''

THOMAS PHILLIPS WRIGHT, was a child of early piety,
and throughout the course of his life maintained a steady rectitude of conduct;
being exemplary in his conversation, dress and address, dutiful to his parents,
and during his apprenticeship, very diligent in his master`'s business.
In a letter written to his parents in the eighth month 1820, he says,

"`It is far from my desire to depart in the least degree from that simplicity
and plainness in which I have hitherto been brought up.
I do not expect to be great,
nor indeed do I wish it--and so often as we see the contaminating effects of riches,
surely they cannot be desirable; but it is much better,
and more desirable to be good than great.
And although I am very far from the former,
yet I do at seasons feel as if covered with the Divine hand,
which is a comfortable state for the mind to be in.
It is a state that I am at times favoured to feel in our silent meetings,
which are seasons of great refreshment to the mind,
if we are rightly disposed to seek after the good Shepherd,
who will lead us by the still waters and into the green pastures.`"

Fourth month 1825.
In a letter written to his father during his last illness, he says of his health,
"`These little amendments are somewhat encouraging,
and yet to build upon them will not do.
I do not know when I feel more comfortable than when I endeavour
to resign myself to Him who does not willingly afflict.
This state is hard to come at.`"
"`I have lately thought what a consolation it is to feel
an evidence of the Divine origin of the Scriptures of Truth,
more than can be conveyed by mere reading and education.
They may be interesting and pleasing, but surely not so profitable,
unless we are favoured to see the spirituality thereof.`"
I sometimes have a hope that, should I be taken hence, I shall be happy,
though it must be entirely through the mercy of our blessed Redeemer,
who pleades for us poor mortals.`"

Seventh month 20th: He remarked to one of his parents that,
"`If he had been removed in the forepart of his illness, he was not prepared,
and therefore it had been lengthened out in mercy--and what a mercy, added he,
should I be prepared to enter one of the heavenly mansions--the
least--the very least--not for anything that I have done,
but all in mercy.`"
On the 27th, in the evening, he said, "`What poor creatures we are, if left to ourselves,
without support.
I can experimentally say that God not only hears but answers prayer,
for I had a remarkable proof of it in the forepart of this affliction.
Wonderful--wonderful, said he, how wonderful is the love of God,
it is too deep for us to comprehend.`"

The love of God and the stupendous mercy of our blessed Saviour in dying for our sins,
were often his delightful theme.
The day before he died, being in great bodily suffering, he said to his father,
"`Oh! what should I have done without a Saviour?
Wonderful--for Jesus to take upon himself to bear our infirmities!
I cannot help expressing it again.
I think I was not enough sensible of it in the forepart of my illness,
but now I feel it.`"
He presently added, "`Sweet Jesus!
I hope he will soon come and take me to himself.`"

A few hours before his close, the conflict of expiring nature being very distressing,
he prayed as follows, "`O, most holy, most gracious God, be pleased,
if consistent with your most holy will, to release my spirit,
but not my will but yours be done.`"
Afterward he said "`now let us all be still,`" and thought himself just going,
but in a little while observed to a friend who sat up with him,
"`It is an awful thing to die, but I am not afraid of death.`"
He was favoured with a remarkably peaceful and quiet
exit on the 5th of eighth month 1825,
being twenty-three years of age.

[.asterism]
'''

MARY BARRON, wife of George Barron, of Birmingham, deceased the 5th of first month 1827,
aged twenty-three years.
In the early part of her illness,
her mind was under sorrow and conviction on account of omissions of duty,
and she observed to a friend, "`I do not feel quite easy; I have many sins to repent of.
I have not prayed as I should have done:`" after which with much earnestness, she added,
"`The enemy is very busy, I feel him so.`"
There is reason to believe that the sincere engagement of her spirit,
in seeking a place of repentance was graciously accepted by Him "`who
keeps mercy for thousands,`" and pardons iniquity and transgression;
for soon after this, her mind became tranquil and composed,
and she repeated the Lord`'s prayer in a very distinct and feeling manner.
A few hours after, she prayed thus, "`O Lord, have mercy upon me.
Though I have been unmindful of praying unto You, even from my cradle,
yet you have had compassion on me and given me to taste of your sweetness,
such as I never before felt, and if it should please You to raise me up at this time,
I hope I shall endeavour to live in your fear, and continually pray unto You, O,
sanctify this affliction to my dear husband, and bring him to know and fear You,
that he may not neglect to say, as I have done, Enable me, O Lord,
to bear your hand upon me, and if it please You that this cup should not pass from me,
enable me to say--Your will be done.
O, Lord, send a blessing upon all my friends, every one of them.
Amen, Amen.`"

She observed that "`she had often heard the benefit of prayer spoken of,
but never knew the sweet efficacy of it until laid on a bed of sickness.`"
How sorrowful is it that persons professing to be christians,
should thus neglect one of the greatest consolations and
purest sources of spiritual strength which the gospel affords,
and risk the salvation of an immortal soul on the uncertainty of a deathbed repentance,
when it often happens that the pain and disease of the body,
disqualify the mind for attention to the all-important concerns of eternity.

On taking a final leave of her husband,
to whom she had been married not quite twelve months, she observed,
"`We have loved each other too much and the Lord too little.`"
A friend coming to see her, she remarked,
"`The love of life holds very close to me;`" and after a short pause,
interceded for divine support, saying, "`O heavenly Father, be with me!
I am weak and cannot fix my mind in prayer as I wish to do.`"
To her medical attendant she observed, "`It is an awful thing to die--I feel it so.`"
The last words she uttered were "`Your will, O Lord,
be done;`" soon after which she departed this life.

[.asterism]
'''

HANNAH.
H+++.+++ HARTSHORNE, daughter of John and Hannah Hartshorne, of Shrewsbury, New-Jersey,
evinced from early childhood a tenderness of feeling under religious impressions,
a lively sense of Divine love and mercy,
and a desire to become of the number of those children
concerning whom the blessed Saviour said,
"`Of such is the kingdom of heaven.`"
Being of a sprightly and active disposition,
she felt the restraints of a guarded education a cross to her natural inclination,
especially in wearing plain and simple attire.

From the time she was twelve years of age,
it was her frequent practice to retire alone to her chamber, to wait upon the Lord,
and hold communion with Him who had graciously touched her heart with his love,
entering into a close examination of her conduct during the day;
and such were the sweet peace and comfort she derived from this Christian duty,
that she found even her bodily pains mitigated,
when she could retrospect the past with an approving conscience,
and offer the evening oblation with innocency and acceptance.

In the ordering of Divine providence she was tried with a long and painful sickness,
being confined to the bed about three years,
during two of which she was deprived of the use of nearly all her limbs.
The disease was attended with severe and protracted suffering,
which she was Divinely strengthened to endure with patience and resignation,
meekly yielding to the painful dispensation,
in the humble belief that it was permitted in wisdom for some good end, remarking,
"`I believe if I entirely resign my own will,
that power which has been with me +++[+++hitherto]
will continue with me to the end of my pilgrimage.`"

Though many trials and privations attended her situation,
yet her mind was preserved from murmuring or repining at her lot,
being rather disposed to commemorate the Lord`'s mercies,
as appears by the following extract from her diary:

"`Can I be grateful enough for the many blessings I daily
receive from that good hand which has been near me?
Poor and unworthy as I am, my heavenly Father is mindful of me,
and has graciously condescended to sweeten the bitter cup of suffering which in mercy
He has seen fit I should drink of And although at times grievous to be borne,
I believe my afflictions have been blessed to me many ways;
they have had a tendency to wean me from the world,
and stain the enjoyments thereof in my view.
O,
that all my young friends knew the incalculable benefit
arising from an early dedication to the Lord!
We can never begin too soon to prepare for death.
I now see there is more real enjoyment in humbly submitting to His will concerning us,
than in all the pleasures of this world, which soon pass away,
and will never afford peace of mind.
May others see the Lord`'s hand in my illness; the marvellous lovingkindness of my God,
who has wonderfully been my support.`"

Her mind was often introduced into a feeling of great poverty and desertion, which,
joined to the diffidence and timidity of her disposition,
led her to fear that she had offended her heavenly Father.
Being thus brought under close exercise,
and weaned from all dependence on former experiences of Divine good,
she was earnest in seeking daily supplies of that bread
which comes from above and endures unto everlasting life.
Of this she was, from time to time, permitted to partake,
and thereby strengthened to bear without a murmur all that her
dear Redeemer was pleased to appoint for her purification and refinement,
saying, "`If it is the will of my heavenly Father,
I think at times I could cheerfully suffer, if possible,
more than I have already gone through; but when He is pleased to say it is enough,
I shall be thankful,
though I know it is an awful thing to die.`"--"`I am a poor creature, but I feel quiet,
and hope it is not a false rest.
I have nothing of my own to trust to, but the grace and the merits of my blessed Saviour,
who has done much for me.`"

On one occasion,
after giving some directions and leaving messages for some of her friends, she said,
"`Live so as to be prepared in health for such a time as this.
Read the scriptures; I have found great comfort in reading them,
and though I sometimes could not feel that +++[+++benefit which]
I have at other times felt, yet it now affords me satisfaction.
How differently things appear to us on a sick bed!
Many opportunities I have not improved.
I am sorry for not having been careful enough when at meeting to
have my mind engaged as it ought to be--Now I feel +++[+++how great is]
the privilege of attending meetings--Oh! prize it.`"

She spoke of her dissolution with much composure, remarking,
"`I believe my death will be without a struggle; I feel that it will be peaceful,
and that you will be spared the trial of seeing me suffer at the last.`"
"`How dreadful it must be to feel distress at such
a time as this--what can be equal to it?`"

At another time she said, "`It is through the crucified Immanuel I hope for acceptance;
I have done nothing to merit the favour.
I have had a bitter cup, but it has been sweetened to me;
I have not had one pain too much.
Sweet peace has followed taking up the cross: many things were a cross to my inclination,
but I endeavoured to be faithful, and have been rewarded.
Dress is trifling--I have considered it so since being sick; it is vanity,
the world with all its follies.
Oh! if the light in us becomes darkness,
how great is that darkness--It is necessary to have oil in our vessel.
You also be ready, for at such an hour as you think not, the son of man comes.
As my bodily powers weaken, I am stronger in the inner man.`"

After hearing a chapter read, she broke forth in this manner: "`O,
the prospect I have had this morning of the happy state!
I want to go to join in singing praises and thanksgivings--I long
to enjoy what I have been favoured to see--It is but a foretaste,
yet almost too much for any clothed with mortality to feel.--What
is to be compared to a happy eternity!`"

Having passed through a season of deep mental conflict,
through adorable mercy her exercise was succeeded by a holy calm and serenity,
under which feeling she exclaimed,
"`Rejoice with me--I have had a sweet prospect of
angels coming to carry me to the bosom of my Saviour.
I have seen the white robe, and a new name,
and it fully compensates for all my sufferings--I long to be gone.`"
Some days after, in a feeble voice, she was heard to say,
"`Receive me into your kingdom--O, the quiet and sweet peace!
I only asked for the lowest seat, and the arms of my Saviour are open to receive me.`"

A few weeks previous to her decease, the power of articulation entirely failed,
leaving her mental faculties unimpaired, and her body relieved from pain.
At this period, she and her friends apprehended the close was near,
a clear prospect being given her of entering into rest,
and that a crown of glory awaited her, which she intimated in an impressive manner,
and with a composed and pleasant countenance.
But in unsearchable wisdom she was again permitted to be deeply tried in body and mind;
yet through it all the everlasting arm was evidently
underneath to stay and support her exercised mind.
She informed those about her, by writing,
that she had been too anxious to be released to enjoy
the blessed rest of which she had so bright a prospect,
but that she now felt peace in being resigned to life or death, adding,
"`I believe it is not entirely on my own account that I am continued in suffering.`"

At another time--"`As much as I suffer,
I would not change my situation for anything in this world; for what is it to me now?
I feel nothing in my way.
Let not the world nor the things of the world, ever stand in the way of duty:
the cross must be borne if we expect to obtain the crown.`"

She continued from this time in a quiet and peaceful state,
her mind being stayed on Christ Jesus the captain of her salvation;
and agreeably to her prospect previously expressed,
she was favoured with an easy passage.
A few hours before the solemn close her speech returned,
and the last word she pronounced was "`Resignation`"--a virtue, the excellence of which,
through the Lord`'s assistance,
she had been enabled eminently to show forth during her long and painful illness.
She sunk away as one going into a gentle slumber,
and deceased the 6th of the fifth month, 1828, in the twenty-third year of her age.

This instructive instance of the power of true religion,
to sustain and comfort the mind under long and painful sufferings,
weaning it from all lower and '`visible gratifications and
filling it with those consolations which are in Christ Jesus,
ought to encourage us to bow to the secret pleadings of the divine witness in our hearts,
that by faithfully following its dictates we may grow up in the fear and love
of God and experience preservation from the pollutions which are in the world.
Then should it be our lot to suffer long with illness,
we may hope to have the comfort of divine support,
know "`the Lord to make our bed in sickness,`" and when
he sees that the appointed time is come for our release,
we shall have a blessed hope of eternal life--being enabled to say with the holy apostle,
"`These light afflictions, which are but for a moment,
are not worthy to be compared with the glory which shall be revealed hereafter.`"

[.asterism]
'''

MARY BROOK SWETMAN, of Street near Glastonbury, England, deceased in the twelfth month,
1819.

She had been for some years occasionally indisposed with a disease which was very flattering,
its effects being sometimes scarcely perceptible.
In the twelfth month, however, it returned with more alarming and dangerous symptoms,
and about three days before her death she was entirely confined to her bed.

On the 18th, one of her sisters being with her she said, "`Why should I be afraid to die?
No-I am not afraid--I shall be happy--quite happy--all will be well.`"
Next morning she remarked,
"`All my worldly expectations and youthful pleasures are nipped in the bud;
but it is all right--it is all in best wisdom.`"

On various occasions,
her expressions evinced that her mind was centered in resignation to the divine will,
and her trust and confidence in the mercy and goodness of the Lord unshaken.

At another time, speaking to the friend to whom she was soon to have been married,
she said, "`I have often thought if you and I had lived together a few years,
I might have forgotten better things.`"
Her friend informing her of the dangerous situation she
was in and the probability she would hardly live a week,
and of the conflict he had endured in attaining a degree of resignation,
she paused awhile and calmly replied,
"`I am resigned to the will of Him who knows what is best.`"
After this she expressed to her sister, "`I do not feel afraid to die,
but I have not that full assurance +++[+++I desire]
and how am I to attain it.
Oh! how am I to attain it?`"
Her sister recommending prayer, she answered, "`How shall I pray--Oh! how shall I pray!`"
But the Holy Spirit which is graciously vouchsafed to help our infirmities,
and to teach us how to pray, was not withdrawn from her,
and she soon appeared to be engaged in mental supplication.
Her friend coming into the room, read some portions of the bible to her,
after which an interval of silence occurred; when she observed,
"`Oh! the wonderful goodness of the Almighty!
Oh kind and sweet Saviour! how vain and trifling are all the pleasures
of this life compared with the joys of the realms above.`"

On second-day morning, the 20th, she desired her friends might be called,
and looking with a pleasant countenance on all around her, she said,
"`O my dear father and mother, I am happy--yes,
very happy--I did not call you because I thought there was any immediate danger,
but thought I would say what I could while I felt able.`"
Then with great earnestness she added, "`I am going to heaven--you will, I hope,
soon meet me there, through the goodness of the Almighty.`"
After a little pause, she proceeded, "`This body must drop--but the soul will never die.
Oh! the sweet peace I feel.
I am blessed every way, far more than I deserve, and may you all be blessed.`"

At another time she said,
"`Oh! what a privilege to be thus called so early from this troublesome world!
If I had lived.
I might not have done what I ought.
Not my will, but yours be done, O God.
Oh! the wonderful goodness of the Almighty.`"
When in great pain,
she frequently petitioned the Lord to favour her
with patience sufficient to preserve her from murmuring.
To one of her sisters she remarked, "`O sister, I am happy--happy--happy;
what a satisfaction it must be to you all to see me leave this world without regret,
and with an assurance of eternal happiness.`"

On one occasion she expressed herself thus:
"`You have said you will love those who love You.
I have loved You, and do love You.
Oh! this is a sweet promise and there are many more.`"
She then took an affectionate leave of each individual,
sent messages of love to some of her absent relatives and friends,
and desired they might be informed that "`she was happy,
and glad to leave this world for the joys of heaven.`"
This affecting scene being over, she said, "`Oh! what composure I feel,
in giving you all up.
I have many ties to bind me here, but now I give you all up with pleasure.`"
After a pause,
"`I have often thought this a beautiful hymn,`" and repeated the first stanza:

[verse]
____
God moves in a mysterious way
His wonders to perform;
He plants his footsteps in the sea,
And rides upon the storm.
____

Observing that those around her were weeping, she said, "`You are all in tears,
but I have not dropped a tear since I first knew my danger.
How is that?--It is the goodness of the Almighty that thus enables me to be resigned.
Oh! what a mercy--the Lord is so kind to me.
Not my will, but yours be done, O God,
has been my earnest prayer ever since I had an idea of danger.`"
Soon after this she exclaimed, "`O death, where is your sting!
O grave, where is your victory!
May you never forget,`" looking upon those around her,
"`that the pains of death are made sweet,--though hard to bear, yet they are sweet,
when borne without a murmur.`"
Suffering acute pain from the violence of the disease, she remarked to her attendants,
"`Were not my hopes fixed on heaven, what should I do!
But mine are fixed never to be moved.
When will you take me, O kind Almighty, you great and good Being.
It is wrong to murmur--yes--very wrong.`"
She soon appeared to be in a calm slumber, which continued a few minutes,
when she addressed those present, "`Farewell--Farewell--I think I am going--O,
come Quickly,--come quickly,--sweet Saviour--if it
be your holy will--and take me--to yourself.
I am happy--happy--happy.
O--sweet Saviour--your countenance has indeed shone round about me.`"
After a short pause,
"`O kind and merciful Lord God--You has not--forsaken me--nor will you.`"
She then peacefully expired.

[.asterism]
'''

ANNA MARIA BOYCE, daughter of Jonathan and Anna Boyce, of Lynn, Massachusetts,
deceased the 18th of first month, 1831.

Being of a lively, animated disposition, she had, contrary to the advice of her parents,
allowed her mind to be drawn aside from the simplicity of truth as professed by Friends;
and although in other respects she had been in a good degree
careful to perform her filial and social duties,
yet her indulging in some of the prevailing fashions of the day,
was a source of much painful conflict to her when laid upon a sick bed.
But being brought, through the manifestations of the light of Christ in her conscience,
to perceive their vanity and sinfulness,
and to feel that godly sorrow which works repentance,
she was favoured to experience the remission of her sins,
and to place her whole confidence in her dear Redeemer.
Thus she obtained a well-grounded hope that a mansion
was prepared for her in his heavenly kingdom;
and during her long and protracted illness,
was preserved in much sweetness and composure, evincing great patience and resignation,
although her sufferings at times were very severe.

The conflict and distress of mind which she experienced
for her departures from those Christian testimonies,
furnish an admonition to others to be more faithful in supporting them,
that they may not, on a dying bed, in addition to the pains of the body,
have the bitter reflection of having been unwilling to take up the cross,
and follow their blessed Saviour in the way of his leadings.

After having been confined to her chamber about two months,
her disease began to assume a more serious aspect, and she informed her sister,
with great composure, that the physician had told her that her case was very doubtful,
which was no more than she expected.

To another sister she said: "`I must soon be laid in the silent grave.
Remember my sickness; and not, as some have done before,
too easily forget the advice and admonition that a dying sister has left them:
but take warning, and be making preparation for eternity.
It is the will of Providence that I should be cut off in my youth from all earthly pleasure--all
things here are uncertain--place no dependence on anything here below;
but remember that we are placed here to make preparation for eternity.`"

She tenderly advised them to be faithful in the maintenance of our precious testimonies,
that so they might be ornaments in society;
and enjoined upon them the necessity of daily reading the Holy Scriptures,
and of shunning the vain fashions and maxims of the world.
She entreated them to be diligent in attending meetings for Divine worship,
and to endeavour, when there, in humble reverence to wait upon the Lord,
that so their spiritual strength might be renewed,
and they preserved from running into sin and temptation.
She expressed her thankfulness that she had time to prepare for death,
and frequently said; "`Oh! what would have become of me,
if I had been taken as some have been, without a moment`'s warning,
and no time to make preparation.
I hope soon to meet my Saviour and my God in peace; and I hope also, to meet you there.`"

On seeing two of her former associates enter the chamber, she addressed them as follows:
"`You are young as well as myself, and are liable to be taken down on a sick bed.
Do, friends, be preparing yourselves; for when you are brought down to a sick bed,
the pains of the body will be enough to bear, without the stings of a guilty conscience.
I want you to be on the watch before the midnight cry is heard.`"

At another time, when some of her young friends called to see her, she said;
"`The last time I was visiting was at your house;
and I have often thought how vainly and idling we
have been in the practice of spending our time:
passing away the evenings in what is called innocent amusement,
which tends not to profit, nor to afford us any instruction or benefit.
I have often thought, when returning home, that I received no good from it,
although I took an active part with you and went astray.`"

Ninth month 28th, 1830.--She requested a private interview with her parents,
to whom she expressed herself as follows: "`I have but a very short time to live!
Will you forgive me, your disobedient, ungrateful child?
I have been ungrateful--you have done much for me, and more than I have deserved.`"
They answered they felt nothing but love towards her; and she continued:
"`You must soon follow me--do not put off the work, but be prepared;
and be careful that the cares of your family do not choke the good seed;
for I believe it is often the case.
I have been greatly distressed in my mind; and how it will be with me I cannot yet see.`"

It appeared that her faith was often tried, as it were to a hair`'s breadth;
yet her confidence and faith in her Redeemer never forsook her;
and she was finally given to feel that assurance of peace which she longed for.

After relating some circumstances which had recently exercised her mind,
she remarked to her brother:
"`I feel very differently now from what I have ever done before;
there appears nothing in my way.
I have always hoped I should see such a state, but have entertained fears about it.`"

After her brother withdrew, she sent for others of the family,
to inform them of the great change she had experienced in her mind, saying:
"`Mountains have been removed.
I have a new song put in my mouth,
even praises to Him who has delivered me and pardoned my sins.
All I have to say is, '`Bless the Lord, O my soul! forget not all his mercies--praises,
living praises be to his holy Name!`'`"

A female in the neighbourhood, who had been one of her associates,
being also in a declining state of health, and beyond the reach of human help,
she frequently expressed much anxiety on her account,
and several times proposed writing to her.
After having it on her mind a number of days,
she informed her friends that she could not preserve peace of mind,
without having it done, and accordingly dictated as follows:

[.embedded-content-document.letter]
--

[.salutation]
My dear C+++______+++e,

I have long thought of you,
with much anxiety for your welfare both here and hereafter;
and I could not feel easy in my mind without addressing you.
I have long been confined to a bed of sickness, during which time I have suffered much,
and enjoyed much.
I believe there is a great lesson for us all to learn, which is,
resignation to the Divine will.
Alas! my dear C.,
but a few months ago you and I joined in the circle of youthful
hilarity.--we are now confined to our sick chambers,
where I suspect our days will end, believing we are both ill of the same disorder.
This shows us the uncertainty of human life,
and the instability of all earthly enjoyments.
Oh, C.! I hope you will be favoured, to put your trust in the Lord Jehovah;
for in Him is ever lasting strength.
If you wish to find a place of repentance, pray to your heavenly Father in secret,
and He will reward you openly.

[verse]
____
Prayer is the contrite sinner`'s voice,
Returning from his ways;
While angels, in their songs rejoice,
And cry: "`Behold, he prays`"!
____

It was by prayer that I obtained remission of sins;
and it is by prayer that you will find a place of repentance.
I have long been desirous for your eternal and everlasting welfare;
and I hope you will be favoured to realize a place of rest:
we are all candidates for eternity, and must either be happy or miserable.
It matters not whether we are taken from this state of existence in the bloom of life,
or at a more advanced age, if we are only prepared to meet our blessed Saviour,
who is ready to receive those who trust in Him.
These are the genuine feelings of my heart.
As I am too weak to say much more, I must therefore bid you farewell;
and as we never expect to meet on earth, may we meet in that city which has foundations,
whose builder and maker is God.

[.signed-section-closing]
From your truly attached friend,

[.signed-section-signature]
Anna Maria Boyce.

--

This letter was written a few days before the death of her friend,
who received much satisfaction and encouragement therefrom,
and who was in the end favoured with the blessed prospect of inheriting a crown of life.

Feeling a desire to leave a testimony for her young friends, she dictated the following:

[.embedded-content-document.testimony]
--

I have thought much, during my sickness, of my dear young friends,
on account of dress and address;
believing there never was a time when the love of dress
prevailed more among young Friends than at the present day.
Is it not sorrowfully the case, that many of you can scarcely be distinguished as Friends?
Oh, my dear friends! what will all your gay dress avail
you when cast upon a sick bed and a rolling pillow!
I was once one of your companions,
and joined in the giddy circle--I am now confined to a bed of sickness and suffering,
from which I never expect to arise.
I feel it my duty to leave this testimony,
hoping it may be a warning to some to leave all fading, perishable enjoyments,
and become followers of the dear Son of God,
who is ever able to save those who come unto Him in sincerity of heart!
Oh! my young friends,
if you could feel the necessity of becoming followers of the dear Lamb of God,
I believe you would no longer remain in the way of sin and transgression.
Although my bodily strength is nearly exhausted,
yet my mind is preserved calm and tranquil;--billow after billow has past over me,
yet the Lord has been my helper and support, which compensates for all bodily suffering.
Oh! that my dear young friends would not put off
the great important work of their soul`'s salvation;
for we have no lease of our lives.
Our minutes are dealt out to us as it were by number;
and we know not how soon we may be called upon to
give an account of the deeds done in the body.
We have all sinned, and fallen short of the glory of God.
But there is a way and a means provided,
whereby we may become initiated into His holy presence;
even by the pardoning love of our dear Redeemer.

But a short time must elapse,
before I shall be laid in my solitary grave--I am now young like you,
but must be cut off in the bloom of life.
I desire you may so conduct yourselves in the simplicity of the truth,
that when the awful summons shall arrive, you may be prepared to meet the answer of,
'`Well done, good and faithful servant, you have been faithful over a few things,
therefore I will make you ruler over many things; enter into the joy of your Lord.`"

I have much cause to be thankful for the many favours and
blessings bestowed upon me during my long protracted illness:
I believe the Lord has been my support in the day of trial and suffering;
and that He visited and revisited me,
before I knew his precious countenance to shine upon me in so remarkable a manner.
"`He brought me up out of the miry clay, and established my goings;
and He has put a new song in my mouth, even praise to His name.`"

O Lord! your mercy reaches unto the heavens, and your faithfulness unto the clouds:
for you have redeemed those that were afar off,
and called in sons and daughters who had gone astray as sheep from your fold!

--

A concern also resting upon her mind on account of her brothers and sisters,
she dictated an affectionate address to them;
the admonition it contains is mostly comprised in the foregoing.

Twelfth month 21st.--She exclaimed to one of her sisters: "`Oh,
when will the happy time arrive that I shall be released from suffering!`"
Her sister asked her if she felt willing to go; to which she very emphatically answered:
"`Yes, it will be a very happy time to me;`" and she informed another friend,
she thought she felt a well-grounded hope.
During the whole of her sickness,
she appeared very desirous that all her dear relations and
friends might come to the saving knowledge of the truth,
and that her death might be sanctified to them for good.

Twelfth month 22nd.--She remarked that she had suffered much,
and how much longer she had to suffer she could not tell, perhaps months,
and perhaps not more than a week;
but "`that life is long which answers life`'s great end.`"
"`Many times have I said, O! death, where is your sting!
O! grave,
where is your victory! and I hope shall still say so with
a clear conscience in the sight of heaven.`"

She observed,
that it had been difficult for her at times to keep
her mind centred upon the Source of all good,
and that she was afraid she should be drawn off the watch, and grow impatient,
from lying so long in such suffering,`" and added: "`not my will, but yours, O God,
be done!`"

Twelfth month 24th.--A friend calling to see her,
she expressed her thankfulness for having retained her senses through her sickness,
and for having time and opportunity to prepare for the change; and further said,
she had a pleasing hope, that she should soon meet her dear Saviour, face to face.

The day before her death, she was impressed with a belief that her end was at hand;
and several times mentioned it.
In the evening she told the family to prepare for the coming night,
as she believed it would be her last.
About midnight her cough stopped, and she wished her brothers and sisters to be sent for;
they arrived in time to participate in the solemn parting.
She appeared to overflow with love towards them,
and expressed her thanks to the Author of all good,
for the great care that had been taken of her during her sickness.
She entreated them not to mourn for her, but to mourn for themselves;
saying she was going in peace to the happy place,
and longed for the time of her departure.

A few minutes before her death she bid them all an affectionate farewell; and then,
appearing to fall into a gentle sleep, quietly departed, aged twenty-four years.

[.asterism]
'''

LYDIA S. ROGERS, daughter of John and Elizabeth Jones, of the city of Philadelphia,
was born the 16th of sixth month, 1810.

Her disposition was amiable, and being naturally of a cheerful and lively temper,
she was drawn by the temptations of the enemy into lightness and frivolity,
and to take much delight in gaiety of apparel,
which deviations from the christian path were causes of condemnation and sorrow
to her mind when the awful period of dissolution was approaching.

She was attacked with bleeding from the lungs in the eighth month, 1833,
but after a confinement of two weeks she nearly recovered her usual state of health,
although some symptoms of pulmonary disease still remained.

In the third month 1834, she was married to Samuel Rogers,
and was able to attend to her domestic concerns until the eleventh month following,
when she became seriously indisposed.
The prospect of separation from those she loved,
the fear of death and a sense of her own unfitness to meet its solemn summons,
produced great conflict of mind.
She was frequently occupied in reading the Holy Scriptures,
and the society of serious and religious people became peculiarly pleasant to her.
She was evidently aware of the danger of her situation,
and on being asked about this time what she thought respecting it, observed,
"`Perhaps I may last until Spring, but I do not expect to get well, nor do I wish it.`"

Under the exercises which she passed through during this period,
there is cause to believe that the Holy Spirit,
who is a reprover for sin as well as a comforter for well doing,
and whose operations are compared to a refiner`'s fire and fuller`'s soap,
was secretly at work in her heart, setting her sins in order before her,
and producing that godly sorrow which works unfeigned repentance.
Many times her spirit was much contrited,
and she would entreat her friends to pray for her;
mourning over her misspent time and er multiplied transgressions, saying,
"`I fear my sins are too many ever to be forgiven.`"

During this time the enemy was permitted to buffet her with his suggestions,
which induced her to exclaim, "`O,
what an unwearied adversary! how he tempts me!`" and to her sister she remarked,
"`Can it be that I shall be forgiven my many sins?`"
But although thus tried with doubts and fears, He whose mercy is over all his works,
was pleased in his own time to grant her an evidence of pardon and reconciliation,
and to animate her drooping spirit with the humble hope that she
should at last be received into the kingdom of heaven.
One day, after some hours of quiet retirement,
she broke forth in this manner--"`Now I feel as I never felt +++[+++before]--I shall
be received--I am perfectly resigned to live or die--I am very happy--O my dears,
do not weep for me,
I can truly say this is the happiest evening of my life--Praise the Lord,
O my soul--bless his holy name.`"
Afterward she observed, "`I want nothing worldly to divert me from the great work.`"

In looking back over her past life,
and her indifference and neglect respecting the great duties of religion,
she seemed almost ready to question whether the evidence of forgiveness could be real,
and on the 14th of first month 1835,
again asked her sister if she thought it possible her sins were forgiven; adding,
"`I have been so neglectful when I had strength,
will the Lord receive me at this late hour?`"
After a time of solemn silence she desired to be helped to a kneeling posture,
and then feelingly petitioned the Most High for the aid of his grace,
and that she might be thoroughly washed and purified.
A female minister of the gospel calling to visit her, spoke encouragingly to her state,
and was also engaged in fervent supplication on her behalf.
These religious exercises afforded her much comfort; her mind was peaceful,
and appeared to overflow with gratitude and love.

Continuing in this inward frame of mind,
and steadily abiding under the refining baptisms of the Holy Spirit,
she experienced sweet peace to flow in her heart,
and a grateful sense of the Lord`'s mercies to her.
On the 15th she seemed full of comfort, and several times remarked,
"`How little I suffer, and how much the dear Master suffered.
O! how kind he is to me.`"
And again, "`O, the sweet peace--I cannot be mistaken;
it is all the heavenly Father`'s work.`"
She often mentioned what a comfort the bible was to her,
and what a blessing it was that she could now understand it,
and take hold of the promises it contained, after having neglected it so much.

She expressed deep concern on account of such as do not
believe in the divinity of our Lord Jesus Christ,
saying, "`What can they have in an hour like this to rest their hopes upon?`"
and mentioned her desire,
that such might be brought to feel the efficacy of the Redeemer`'s love; adding,
"`He gave his precious life for us.`"

On the 16th she expressed great love for all her friends, many of whom she named,
and remarked, "`I would be glad to do something for the blessed cause:
I feel that I have espoused it,
and if it will do anyone good to see me here entirely changed,
I should be glad some of my thoughtless friends should see me.`"

On the 17th she was under much inward conflict and trial, but in the evening observed,
"`It comes sweetly into my mind that we need not be dwelling so much on our past sins,
but just lay them all open before our blessed Father--he can see them all at one glance,
and as quickly forgive them.`"

Being now brought in good degree to the blessed teaching
of the spirit of Christ in her own heart,
she found it to be indeed a light to her mind,
unfolding the mysteries of redemption and giving her to see clearly the true meaning,
as well as the precious value of the Holy Scriptures.
She spent much time in reading these, particularly the New Testament--and one morning,
after having been so employed, she looked up with a joyful countenance and exclaimed,
"`This has been a sealed book to me, but now what beauty and consistency I see in it.
Oh! what can they have to rest upon, who do not believe in the Saviour!
I would not exchange my belief for a thousand, thousand worlds.`"

In the ordering of Him whose dealings with his ransomed
children are all in perfect wisdom and goodness,
though past our finding out, she was permitted, on the 20th,
to experience a season of great tossing and distress; and when, through mercy,
a degree of calmness was restored, she remarked,
"`I feel better now--but what an agonizing time has my poor mind had.
I fear I have taken hold of promises that do not belong to me.
O, I have been such a sinner!`"
This painful dispensation gradually passed away,
and on the morning of the 22nd she could say, "`All is peace and comfort,
though I am very weak.
There are some clouds through the day, but my nights are all joyous.
The Father is very near me this morning.`"

Soon after this she was thought to be dying,
and her connections being called she took an affectionate leave of them, saying,
"`I am going home,`" and seemed filled with holy joy.
In the afternoon she faintly articulated,
as though replying to a query respecting her removal,
"`not yet--not yet--stay a little longer;`" and when still
further recovered from the state of great exhaustion,
in which she had been lying, she remarked, "`I believe my time is to be prolonged.`"
From this period until her decease,
her mind was more engaged on behalf of others than during the previous part of her illness,
and many opportunities occurred in which she imparted
impressive admonition to her friends.

On the evening of the 24th,
she had an attack of suffocation which rendered it
doubtful whether she would survive the night,
in allusion to which, she sweetly remarked, "`If I do not,
there need be no bustle--I believe all is done, everything is ready.`"
Next morning the state of her mind was very peaceful and heavenly and she observed,
"`This is a sweet morning to me,--Praise the Lord, O my soul.`"
Although her weakness was great and much suffering consequent on the disease,
yet her mind was so absorbed in the contemplation of heavenly things,
as scarcely to have any sense of suffering.
At her request the family were collected, and after a time of solemn waiting in silence,
she addressed them in earnest entreaty to close in with the offers
of divine mercy and not put off the period of submission,
testifying from her own experience, that the Lord is not a hard master,
requiring more than he enables to perform.

On the 26th, her mind appeared much exercised, and often engaged in prayer.
She remarked that she could not communicate anything to those around her,
unless her dear Father gave it to her; adding, "`Remember,
Joshua`'s army compassed the city seven times before they were commanded to shout.
If I dared to speak of myself I should say a great deal, for I am earnest for your help.`"
The next day she saw many of her friends:
great was the exercise she underwent on their account,
and deep her sense of the exceeding sinfulness of sin,
under which impressions her mouth was opened in a wonderful and affecting
manner to speak to the states of those who came into her room.

A few days previous to her dissolution her sufferings became extreme,
and though mercifully strengthened to endure them with much patience and resignation,
she said,
"`I hope my patience will hold out--I fear I do not bear trial
as I ought--It is not my wish to be relieved from suffering,
but to bear it to the honour of my Lord:
if he saw fit he could relieve me--I only desire what will tend most to His glory.`"
She seemed afraid that her friends paid too much attention to her needs, often saying,
"`You are all taken up with me--I wish some poor neglected one could have part of what
I receive;`" and on one of her visitors remarking that she was comfortably situated,
she answered, "`Yes--I have every earthly comfort, but that will not satisfy the soul.`"

One of her dresses which had ruffles on the sleeves being put upon her,
the sight of them seemed to affect her; she desired a pair of scissors to be brought,
and had them cut off, saying, "`O! these ruffles illy become dying hands.`"
She also requested to have some ornamental articles of her dress burnt, observing,
"`They will be useful to no one--finery is indeed a great burden.`"

On the evening of the 10th of second month,
she had the fourteenth chapter of John read to her,
which had been her daily practice for some time previous.
Her weakness rapidly increased; it was evident that the solemn change was near,
and the family were collected around her dying bed.
To her husband she said,
"`The dear Saviour is the way--he is the door--knock
and it shall be opened--all that will come may come.`"
She took a most affectionate and impressive leave of her family, saying,
"`Farewell--farewell--love to all.
The horses are come--the chariot of Israel, to carry me home.
Take me to yourself, if you have purified me.
Happy--happy--happy!
O, praise him--he is a God of love.
These light afflictions, which are but for a moment,
will work out for us a far more exceeding and eternal weight of glory.`"

She called one in the room to her, and gave her sweet counsel,
enjoining upon her to let the Lord have the first place in her affections, saying,
"`Love Him first--Him last--and through all--then all will go well.`"
Presently after, as if all the energies of her dying frame were summoned to the effort,
she broke forth in a loud voice,
urging on those present the necessity of bowing to the cross of Christ:
"`The dear Saviour,`" said she, "`hung nailed to the tree,
bleeding for us--for our sins;`" and afterwards,
"`It is hard work to die--but the sting of death
is gone--thanks be to God--he has given me the victory--O,
help me to praise the Lord.`"

Thus, with a hymn of praise on her expiring lips,
this dear young woman ceased to breathe on the morning of the 11th of second month, 1835,
in the twenty-fifth year of her age.
Her ransomed spirit, we joyfully believe,
was received into the mansion prepared for it by
Him who had so marvellously redeemed her unto Himself,
and is now one of that happy company who surround the throne of God and the Lamb,
with the unceasing anthem of "`Salvation, and glory, and honour,
to Him that sits on the throne, and unto the Lamb forever.`"

May this memorable instance of the uncertainty of life and of all temporal enjoyments;
of the adorable mercy of God in Christ Jesus to the sincere penitent;
and of the power of his blessed spirit in purifying the soul,
weaning it from earthly attachments,
filling it with the pure and precious consolations of the gospel,
and conferring on it a hope full of immortality and eternal life,
encourage others to yield in unreserved obedience
to the early visitations of heavenly love;
that thus living in the fear and love of God,
they may experience preservation from the snares which beset the paths of youth;
know the light of Christ Jesus to be their safe guide through
the trials and temptations of the present changeful life,
and in the awful close have a well-grounded hope
of admission into the mansions of eternal glory.

[.asterism]
'''

THOMAS HATTERSLY, died at Hansworth Woodhouse, England, on the 16th of seventh month,
1843, aged 24 years.

He was brought up to the business of a teacher,
in which he was employed for some years before his death, and his unwearied diligence,
exemplary and upright deportment,
and the`' concern he manifested for the religious welfare of the scholars,
won for him in a remarkable degree their lasting esteem and affection.
Early in 1843 he was attacked with pulmonary disease,
which left little hope of his recovery, and separated him from his school,
and those for whose well-being he had been so solicitous.
The pupils felt this event keenly,
and addressed to him several letters expressive of their affectionate interest and concern.
In his reply he says, "`Though you have had line upon line, precept upon precept,
here a little and there a little,
I have felt a wish that this further warning may not De lost upon you.
You know that but a few short months ago, I seemed as healthy,
as strong and as hearty as any of you; and as likely to reach old age as most.
I had never, that I recollect, previous to that period, experienced three days`' illness,
except at school, when at least fifty other boys were laid upon a sick-bed.
I mention these things to mark the contrast.
I am now +++[+++labouring]
under a complaint which has very often proved fatal; how it may terminate in my case,
I know not.
It may be supposed that I feel weary of sitting or reclining, day after day,
not allowed to write, or to read but in the strictest moderation,
but that is far from being the case.
I am truly thankful +++[+++in being able]
to say,
that those silent and solitary hours have been passed with much pleasure and much profit.`"

His disease made rapid progress.
On the 19th of sixth month,
his sister enquiring whether he felt comfortable in the prospect before him, he replied,
`"Since I came here,
I believe I may say it has been my constant prayer
to be entirely resigned to the will of God;
to have my past sins forgiven for the sake of Jesus Christ;
to be purified from every defilement; that I might be preserved from +++[+++using]
a mere form of words, without the heart accompanying them, and that,
if it pleased the Almighty, I might have some evidence of my being forgiven.
I think I may say I have had a great degree of resignation granted me,
and at times a feeling of the presence of God in my prayers.`"

During times of much trial,
he frequently expressed his sense of the presence
of his blessed Redeemer being near to support him,
and on one occasion said, "`I have heard within me, more than once, the language,
"`Your sins are forgiven you for His name`'s sake.`"

On the 24th he expressed that he felt increased comfort from the renewed and clearer
evidence he was favoured with that his sins were forgiven him by his gracious Saviour,
who was both able and willing to save him; and at another time,
his sister remarking that he had looked very happy that day,
and asking him if it was not so, he sweetly and calmly replied, "`Quiet trust.`"
This precious state of mind seemed to be permitted
to remain during the short remnant of his days,
and his confiding and tranquil departure has left in the
minds of his bereaved friends the consoling belief,
that through the mercy of Him in whom he trusted,
his blessed portion is "`quietness and assurance forever.`"
