== Chapter 12

[.chapter-synopsis]
* Anne Ashworth
* Thomas Williams
* Abigail Backhouse
* James Nicholson
* Arthur Gilkes
* Richard Stansfieid

ANNE ASHWORTH, of Poynton near Stockport, England, deceased the 2nd of fifth month, 1838,
aged twenty-six years.
She was the wife of Thomas Ashworth and daughter of Thomas and Rebecca Christy.
Her health having become very delicate, she endured much suffering,
and several times expressed her apprehension that she should not recover.
Early in the first month, 1838,
a slight hemorrhage from the lungs appeared to awaken her
mind to a still deeper sense of the uncertainty of her life,
and much conflict of mind ensued.
She remarked to her husband,
"`It is an awful thing to be placed as between time and
eternity!`" and the language of her exercised mind,
was, "`What shall I do to be saved?`"
In endeavouring to attain a state of resignation to the Divine
will under the prospect of leaving her beloved husband and babe,
she passed through many conflicts, in allusion to which she afterward remarked,
"`None can tell what I passed through;`" but she was enabled to add.
They are now no tie to me.

Although her mind was mostly in a calm and settled state,
yet as her disease made progress,
she greatly desired to feel a clearer assurance of her acceptance,
and writing to one of her sisters, she said,
"`I fear my dear brothers and sisters think too highly of my religious attainments.
Surely it requires great preparation of heart to be made
fit for that pure and holy place--Oh I do not weep,
but pray for me!`"

On the 19th of 3rd month, she said to her husband; "`It seems hard to bear these pains:
my only regret is to leave you--but I cannot look back, all seems so gloomy,
and to look forward so pleasant: Heaven must be a blessed place.
We read, eye has not seen nor ear heard, neither have entered into the heart of man,
the things which God has prepared for them that love him.
Oh! that I may have patience, and never allow a murmur to come from my lips.
On the 8th of the 4th month, she said,
"`I feel that I must be entirely resigned to the will of the Almighty,
whether I ever get better or not.
I endeavour to press forward; and in doing so, I find the greatest peace and comfort,
but I dare not look back into the world.`"
Some days after, her father asking her if she felt resigned to go and leave all,
she replied, "`I am willing to leave all, but I feel greatly for my dear husband:
I dare not let my thoughts go back into the world for a moment; if I do,
I cannot be comfortable until I get back to that which is good.`"
At another time, when several of her relations were present, she said,
"`I would have you all begin now to have your peace made with the Lord.
Be careful when you go to meetings to avoid restlessness and unsettlement,
and remember who it is you go there to worship.
Oh, I have felt such support during my illness, and at times such peace,
I can hardly describe it; yet, at other times, I have felt much poverty.`"

She several times expressed the comfort she had experienced in
silently waiting upon the Almighty in our religious meetings;
but added, "`I have not always employed my time and thoughts profitably.`"
On the afternoon of the 22nd of 4th month, several of her relations being around her bed,
she said, "`I hope all my brothers and sisters will begin now, in time of health,
to make their peace with the Lord, for a sick-bed is not the time.
Some may say, sickness and pain bring us nearer the Lord,
but let them be careful how they reason in this way and put off.
I trust they all will be careful how they let their
impressions about my illness pass away from them;
how apt is the mind to forget these things,
and get from under them!`" She afterwards added,
"`I have endeavoured to live in the fear of the Lord,
and before entering into anything of importance,
(and regarding my marriage in particular,) I have sought his counsel; and Oh,
how clearly has he shown me what was right!`"

At one time when under great suffering of body, she said,
"`This has been a most comforting afternoon.
Oh, I have felt so comfortable in the midst of all my affliction, I thought I could say.
Not my will, but yours be done; though I feel myself so unworthy;
I know I am nothing but what the Lord is pleased to make me.`"
At other times, however,
it pleased the Lord to prove her faith and patience
by the withdrawing of his blessed presence,
and on one of these occasions, she remarked, with tears,
"`I have lately felt such poverty, it seems as though I was quite deserted.`"

On the 23rd, while recounting the Lord`'s mercies to her from very early life, she said,
"`I have loved the Lord.
He has been very good to me; when I was a child,
I have fervently prayed to the Lord that he would be pleased to forgive me my sins.`"
On the 26th, in reference to the state of her mind, she remarked,
"`I think it feels peaceful.
Oh! how is my whole heart and mind engaged in supplicating my Saviour
that he would be pleased to make me fit for his heavenly kingdom,
and although my prayers are feeble, he knows they are sincere.`"

She felt much concern on account of some of her relations engaged in business,
and observed, "`I have heard people talk about their great trades and business,
and make them of much importance.
Oh, I have seen that they are nothing at all,
compared with the salvation of the immortal soul.`"

On the 27th, she said, "`The Almighty is often very near to us,
when we are not at the time sensible of it;--but Oh! we should ever keep on the watch,
and then we should never lose his blessed teachings and instructions.`"
She expressed a desire that if consistent with the Divine will,
she might be spared the severe sufferings which some have to pass through at the close;
saying, "`What a favour it would be!`"

Fourth month, 28th. She said, "`This has been a trying day to me;
my mind has been so poor and depressed.
Oh! my Saviour, be pleased to intercede for me.
Be pleased to purge me with hyssop, and I shall be clean;
wash me and I shall be whiter than snow:
enable me to bear with patience all that is needful for my refinement;
and grant me the lowest seat in your house, that I may praise you forever.
Amen.`"

On the 29th, she remarked, "`Many times in the +++[+++last]
night,
my supplications were put up to the Lord that he
would be pleased to grant me patience to bear all,
and I believe my prayer was answered.`"
In the afternoon she sent for her father and said, "`Now I feel happy.
O, if I had strength and voice, how could I sing praises with his saints!
I seem already to have been among them.
How long do you think it will be before the time will come?`"
Afterward, when in great pain, "`I wish you all to pray for me.
I feel such joy and peacefulness; I believe my peace is made,
and no one need be afraid to die if they feel the peace I feel.`"
After this season of heavenly consolation,
the dear sufferer had again to pass through another trying baptism,
doubtless designed for her further purification and the trial of her faith and love,
during which, she remarked, "`I feel so poor,
as though my blessed Saviour had withdrawn himself.
Oh!
I feel so discouraged; though I do not feel condemnation.`"

On the 1st of fifth month,
after being engaged in supplication for support under the approaching trial, she said,
"`I feel more comfortable now,
and a calmness and stillness--how precious to feel
it`"--and in sending a message to one of her sisters,
she said, "`Tell her that I am very happy,
but feel the need of keeping near to my Saviour.`"

She frequently expressed her gratitude and concern
for those who so carefully waited on her,
and in one of her prayers said, "`Bless all those who have waited upon me,
with the best of your blessings, O Lord.`"
During a violent paroxysm on the 2nd she appeared to be dying,
and with a clear and audible voice and joy depicted in her countenance, exclaimed,
"`I am going to heaven--pray for me.
Do not mind the world--All of you do anything to get to
heaven--it is a glorious place--I dare not look at the end,
it is so glorious--O pray for me that my passage may be
soon and easy.`"--A very solemn and affecting scene ensued,
in which she took leave of all present,
and addressed pertinent counsel to each of her domestics.
Her mind appeared to be expanded with divine love toward all,
desiring they might all be brought to experience the blessings of true religion, saying,
"`I am going to the glorious kingdom of heaven`"--and to her husband,
"`Keep near the Lord--do not weep, you could not wish me back--I cannot weep,
I am so happy--what a happy family shall we be if we all
meet in heaven--press forward to heaven and meet me there.`"
She then broke forth in prayer for the preservation of her beloved husband and father;
and also interceded, "`I thank you for all your matchless mercies,
and pray that you will not forsake me,
but carry my head over the remaining waves and billows safely into your kingdom.`"
Again, "`O Lord, blessed Saviour, when it shall please you to release me, O Lord Jesus,
come--Your will be done--give me fortitude to bear
these afflictions;`" and in allusion to her suffering,
said, "`Not one pain too many.
Lord, if it be the means of preparing me for your blessed kingdom.`"
She continued almost constantly engaged in prayer until the solemn close,
in which her petition was remarkably answered, for she passed away without any struggle,
and we doubt not has been permitted to join the multitude before
the throne in celebrating the praises of her God and Saviour.

[.asterism]
'''

THOMAS WILLIAMS was born at Ramsgate, in England, in the year 1806.
He was not by birthright a member of the Society of Friends,
but being placed at a Friend`'s school and afterwards apprenticed to a member,
his mind became early impressed with a sense of the
privileges of having a right in this religious society,
and applying for admission, his request was acceded to.

His conduct was consistent and exemplary,
his uprightness and integrity gaining him the respect of his acquaintances.
He was diligent and attentive to his business,
yet at the same time evinced that he was seeking
a better inheritance than this world can give,
and which will never fade away.
His business was one which required very close attention,
and though he managed it without an assistant,
yet he did not allow it to prevent his regular attendance
at religious meetings both on first and other days.

The illness which terminated his life, was, during the last few weeks of its course,
rapid in its progress.
His mind was preserved in great calmness and composure,
and his expressions furnish ground to hope that through
the mercy of God in Christ Jesus our Lord,
his spirit, when released from the bonds of mortality,
was joyfully gathered to the just of all generations.

A few days before his close he remarked to one of his sisters,
"`What an unspeakable favour it is to be a member of our religious society!`"
and expressed regret that many who possess this privilege do not value it sufficiently.
He observed that he was not afraid to die,
but hoped through mercy to be taken from the trials of life to a place of rest; adding,
"`All will be well, either way.`"
To a friend who called to see him he remarked, with much sweetness,
that he hoped he could, without presumption, adopt the language of John Woolman, '`O,
my Father--my Father, how comfortable are you to my soul at this trying season!`" adding,
"`I feel such peace--such sweet peace!`"

He, frequently spoke of his situation with great composure, and on one occasion,
when he felt extremely weak, said, "`I hope I shall have patience;
it is trying to nature not to see the event,
but (as if checking himself for this expression) Providence is abundantly kind.`"
Such were the resignation and contentment of mind with which he was favoured,
that when taking the medicines prescribed for him, he would frequently smile and say,
"`Even my medicine is sweet to me.`"

On the 6th of the sixth month,
he received a farewell visit from two friends whom he highly esteemed,
and in replying to some observations which had been made, remarked to them,
"`I have not been what I ought;
but through mercy I feel that precious union and communion with Infinite Love,
or rather so grafted into the spirit of love, that I do not doubt.`"
Love seemed to be the clothing of his spirit, and selfishness to be removed;
experiencing, as he expressed himself, "`I to be annihilated, and love implanted.`"

In the course of the 7th, he sweetly referred to the character pi our blessed Lord,
who was tempted as we are, yet without sin; and added, "`O,
that my temptations may be without sin.`"
On the following day he said, "`What a blessed thing it is to be a true Quaker,
and how few know it!
The goodness and mercy of God have been very great towards me.`"
After recovering from a spell of exhaustion and faintness, he prayed,
"`O gracious Lord! grant me patience.
Preserve me from temptation--O gracious Lord! let me not sin against you in my weakness.`"

His mother and sister standing around him at one time,
he looked at them with much emotion, and then smiling said very affectionately,
"`All looks very pleasant--I would long if I dared`"--adding,
"`May the blessings of heaven which have been so
abundantly showered down upon me from the beginning,
descend upon you!`"
On recovering from another fainting fit, he said,
"`O what a blessed thing it was!`" meaning no doubt the bright prospect he had had of
heaven--"`in one moment more I thought I should have been in eternity--one little struggle.`"

After a visit from his physician, he inquired his opinion of him;
and on being told he considered him worse, he said to his mother and sisters,
"`Pray for me, my dears, that in my weakness I may not be assailed by temptation.
I have a most pleasant prospect;
but I hope I shall be able to bear what He may be pleased to lay upon me first.
What some poor creatures suffer without the consolations of religion!
What an unspeakable favour to be brought under its influence and to know it truly--O,
it is of unutterable value!`"

His sister remarking that it was pleasant to see him smile Yes,`" said he, "`I do smile,
though I do not feel quite so clear as I wish--the
things of the world will pass before me,
yet as I do not willfully sin, and my great weakness is not a fault,
I hope I have no cause but to smile.`"

During the night previous to his decease,
he was greatly exhausted by continued fainting fits, and on recovering from one of them,
his countenance beaming with joyful anticipation, he said, "`O,
how beautiful! just at the gates and saw the beautiful company!
O how unspeakably beautiful!
I was just at the gates, but could not get in; could not break the silver cord,
though only a thread.
What a disappointment! and now for patience to wait a little longer.`"
It was not long, however, that his redeemed spirit had to wait for an entrance,
for it pleased his gracious and compassionate Lord,
shortly after to proclaim his release from his afflicted
tabernacle and admit him as we trust,
within that glorious holy city, "`None of whose inhabitants can say, I am sick,
for the people that dwell therein are forgiven their iniquities.`"

He peacefully expired on the 9th of the sixth month, 1833, in the 25th year of his age.

[.asterism]
'''

ABIGAIL BACKHOUSE was carefully brought up by her parents,
but it does not appear that she fully experienced the blessings of true religion,
until near the close of life.
In the 4th month, 1841, she was attacked with illness of an alarming character;
On this 30th, desiring to hear that passage read, "`Him that comes unto me,
I will in no way cast out,`" she remarked to her sister, "`Although I have not said much,
I have not been insensible to my danger, and I feel as though I might die at any time.
I do not seem to have that sense of acceptance which I should like.
Do you think there is any hope for me?
I know that I have neglected to do many things that I ought to have done,
and I feel sorry now.
But then, is there not a difference between feeling very sorry for our sins,
and feeling a sense of the love and mercy of God in the pardon of them?
I ought to have thought more about these things sooner.
I feel that I love God; but I know that I ought to have loved him more.`"
Her mind being brought under great exercise and concern for her salvation,
she prayed with much fervency as follows:
O Lord God! you who see us altogether as we are;
you know my many sins of omission and commission.
You know that I have allowed the world,
the flesh and the devil too much to draw my affections from you.
O Lord, I am very sorry.
Be pleased to look down upon me, and to blot out my sins, for the sake of your dear Son,
Jesus Christ; and if it be your will, that at this time I should lay down my life,
O be pleased to grant me an admittance into that city,
where there shall be no more sin.`"

To her husband she remarked, "`Where much is given, much is required;
but where little is given, little is required.
I have not been faithful in the little;
but how true it is that all we can do of ourselves is of no avail--I see that if I recover,
I must do very differently to what I have done`"--"`I have
often heard of people making good resolutions on a sick-bed,
and forgetting them when restored to health.`"

The engagement of her soul on her own account continued to be fervent,
and she was much tried with a sense of desertion of heavenly good,
and much cast down--and on the 5th of 5th month, desiring to be left alone,
her attendants overheard her earnestly petitioning for mercy;
and on their returning into the room, she said to them with clasped and trembling hands,
"`O, the feelings of my mind are beyond all description.
O,
my sins are so great--It seems to me as though not
one action of my life had ever been accepted.
I thought I knew what it was to take up the daily
cross--I talked about it and I heard others talk;
and I thought I knew as much as they did;
but now I see that I knew nothing about it.--I never
did know what it was to take up the daily cross,
to be divinely directed; and therefore what can I expect now?
Do you think there can be any mercy for me?`"
She was reminded that it was a mercy to be enabled thus to see herself a sinner,
and that all her own righteousness could avail her nothing;
that nothing short of the Holy Spirit could effect this work,
and that a broken and contrite heart, God would accept--she replied,
"`I do indeed see myself to be a poor lost creature, and can most earnestly pray,
God be merciful to me a sinner; but then my sins are so great.`"
It was remarked that they were not greater than the remedy provided,
nor than Christ was both able and willing to forgive, and that it is declared,
he wills not the death of any, but that all should return to him,
repent and live--`"That,`" she rejoined, "`is a comfort to me, and also the promise.
Him that comes unto me,
I will in no way cast out--Oh! that he may have compassion upon me.`"

She soon after supplicated very earnestly, "`God be merciful to me a sinner--Oh,
pardon me, I beseech you, most merciful God.
I am very unworthy, but pardon me, I pray you;
blot out all my sins for your Son`'s sake.`"
Much more was said which cannot be recollected;
but the anguish of her spirit did not seem to be abated, and with much feeling she said,
"`O, my feelings are distressing--do you think my prayers will be heard?`"
It pleased the Lord, whose ways are not as man`'s ways and whose wisdom is unsearchable,
to withhold from her any sensible evidence of acceptance,
and still to try her with desertion,
and it being proposed that all present should sit down in
silence around her bed and wait upon the Lord;
after a time of stillness a very solemn feeling spread over the company,
and it pleased the Lord in a remarkable manner to make known his power,
to open the door of access to his footstool in prayer;
and to speak the word of peace to her troubled and fainting soul.
After a season of solemn silence, she said to her sister,
"`I believe it right for me to tell you what a very
remarkable change has taken place in my feelings.
Such a flood of divine love and mercy is poured into my soul,
as I never before had any conception of.
I never comprehended the possibility of anyone, in this state of existence,
being favoured with such feelings.
O, what a mercy!
It is inexpressible!
Such love!
I can now fully believe that my sins are forgiven for Jesus`' sake:
a broken and contrite heart has been accepted.`"

The change in her feelings was apparent in her looks--heavenly joy beamed in her countenance
and gratitude to Him who had thus revealed his blessed light in her sou],
flowed in her heart.
"`If I am permitted to recover,`" said she,
"`I hope I shall be strengthened to be a self-denying servant of the Lord.`"
Under the feeling of the new life she had begun to live,
and of the joys of God`'s salvation,
she rejoiced in the prospect of the Lord`'s will being done in her and by her, saying,
"`If it is his will to take me to himself now, I can truly say, I am resigned.
I have never done anything +++[+++to deserve such a favour,]
it is all mercy, free unmerited mercy.`"
Alluding to the parable of the labourers who were sent into the vineyard, she said,
"`They received every one a penny; even those who had but just entered,
received the same as those who laboured long--Oh! what a mercy that I have been invited
to enter at the eleventh hour--that I have been permitted to enter!--I was so very unworthy;
but I feel that an entrance has indeed been granted me.`"
Next day, she said, "`It comes near to a mother`'s feelings to part with her children,
but I can now say, I am perfectly resigned:
I leave them to the Lord and to the care of their relations.
It is my desire that they should be brought up in the fear of the Lord,
and most decidedly as Friends.`"

It pleased the Lord to permit the peaceful and joyous state of her mind,
to be interrupted by intervals of cloud; in which, for the trial of her faith,
the light of his countenance was withdrawn, and a fear raised,
lest something still stood in her way to final acceptance.
At these times she was strengthened to make her appeal to Him in whom she had believed,
and at length he was graciously pleased again to appear and dispel the darkness,
giving her indubitable evidence that, although thus tried and proved,
she stood accepted in his sight.
A short time before her close, being asked if she continued to feel comfortable,
she replied, "`Yes--very--indeed`"--and soon after,
her spirit was released from its earthly tenement to join the company
of those who having come out of great tribulation have washed their
robes and made them white in the blood of the Lamb.`"
She died the 7th of fifth month, 1841 aged 27 years.

[.asterism]
'''

JAMES NICHOLSON, the son of Thomas and Elizabeth Nicholson, was born at Whitehaven,
in the year 1795.
It appears that in early life he was favoured with a sense of the convicting,
regenerating power of the Holy Spirit; and yielding obedience to its dictates,
he was made willing to bear his cross and in humility to follow his gracious Redeemer.
Being concerned to abide under the sanctifying influence of Divine grace,
he experienced preservation; and was enabled to become a preacher of righteousness,
in life and conduct,
and to bring forth fruits to the praise of Him whose blessing peculiarly
rests on an early surrender of heart to his service.

In the year 1823,
he believed that it was required of him publicly
to declare to others the unsearchable riches of Christ,
and what had, in unmerited mercy, been done for his own soul.

His communications in the ministry were instructive and edifying.
He was often earnestly engaged to impress upon Friends
the importance of an early dedication of heart,
and the need of watchfulness unto true prayer, that a preparation might be experienced,
lest the solemn messenger should be sent in an unexpected moment.

His views of Christian redemption were clear, sound, and scriptural;
a living faith in the atoning sacrifice of Christ our Saviour,
being accompanied with a full belief in the necessity
of obedience to Divine grace in the soul.

In his solemn approaches to the footstool of Divine mercy,
his mind was clothed with deep reverence, manifesting self-abasement,
and much fervency of spirit.

He was often concerned to exhort Friends faithfully
to maintain our various Christian testimonies,
and that the affairs of society should be conducted
under the influence and direction of Divine wisdom.

Love to God and to his fellow-men being sweetly portrayed
in the character of this dear Friend,
he was affectionately disposed to sympathize with the afflicted,
and through the aboundings of the love of Christ,
he was frequently enabled to administer comfort and consolation
to minds bowed down in seasons of deep probation.

In the year 1832, he was united in marriage to his friend Sarah Waite,
a member of the same meeting; but this endearing tie was soon severed,
no doubt in unerring wisdom.

Having been in a declining state of health,
(and the fatal nature of his complaint not being for some time apprehended,)
and believing it right to use all suitable means for its restoration,
he was induced to take a journey on that account.
He reached Carlisle without much apparent fatigue, where,
at the house of his brother-in-law, symptoms of approaching dissolution appeared.
While the ultimate result of the complaint was hid from his view, he had often to express,
in much brokenness of spirit, his resignation to the Divine will,
however it might terminate.

On the day preceding his death, which took place on the 9th of sixth month, 1836,
a few friends calling to see him,
he entered with much interest and feeling into the state of our society;
and concluded some instructive observations in nearly these words:
"`I firmly believe that He who raised us to be a
people will never allow the Christian testimonies,
of which we make a profession, to fall to the ground; but.
Friends, hold to your principles, for we have not followed cunningly devised fables.`"

A short time before his decease, he said to a friend, "`Oh,
how my love abounds to my friends!
I always loved them; but I think I never felt it so much before:
perhaps I am not going to be long among you.`"
On the last morning of his life, his dear wife was strengthened to inform him,
that it was the opinion of his medical attendant his close drew near;
and soon after inquired if anything rested upon his mind.
He with much composure, replied, "`No; I feel quite resigned,
and am perfectly easy in body and mind.
If anything further is required of me, time will be given.`"
He again repeated, "`We have not followed cunningly devised fables.`"
He then desired his dear love to be given to many of his friends,
and in a short time afterwards very peacefully passed away.

Thus closed the life of our much loved friend.
He had, we believe,
in time of health endeavoured to know an establishment
on the only sure foundation--Christ Jesus,
the Rock of Ages; and thus, through the infinite mercy and lovingkindness of our God,
we humbly trust his spirit was permitted to enter into His glorious kingdom,
to unite with the just of all generations, in singing praises to the Lord God,
and to the Lamb, forevermore.

[.asterism]
'''

ARTHUR GILKES was the son of Benjamin and Maria Gilkes, of Nailsworth,
in the county of Gloucestershire, and was educated by his father,
who kept a school at that place.
He was deprived of the care and attentions of his affectionate mother,
when he was about thirteen years of age, a loss which he sensibly felt.
When he had attained his eighteenth year,
he was engaged as an assistant to his brother in a school.

It was during the time of his being thus employed,
that his mind was evidently brought under the influence of the Holy Spirit;
and he felt the necessity of that change of heart, that new birth,
without which it is impossible to enter the kingdom of heaven.
He said very little on these important subjects except to his nearest relatives;
and the work that was then going forward in his mind
was not known to the superficial observer,
but to those who were made acquainted with his feelings it was evidently
a time in which he was concerned to enter into covenant with his God.

Some weeks previous to the vacation, which took place in the sixth month, 1838,
his health became delicate, and he was affected with cough,
but no immediate cause of alarm was apparent.
In the following month he became worse, a medical friend was consulted,
and it was hoped that a change of air by the seaside might tend to restore him to health;
but this was not the case, and the symptoms of consumption were soon developed.
It was now evident, that the disease had, though in a great degree unsuspected,
been for some time undermining his constitution.
On his return to London, further medical advice was obtained,
he was removed from there to Nailsworth,
in the hope that his native air might be beneficial but it was ordered otherwise,
and it soon appeared right to apprize him of his real situation,
which was done with all the tenderness that duty and affection could suggest.

He received the information with calmness and submission,
and it was manifest that although he felt the seriousness of his situation,
and his own unworthiness, he could look with a humble hope to his Saviour and his God.

Notwithstanding the anxious fears of his friends that the
disease was rapidly hastening him to the grave,
it pleased his heavenly Father to prove his faith
and patience by an illness of nearly thirteen months.
During this time of trial it was cause of great thankfulness to those around him,
to see how his heart was influenced by the love of God,
how it strengthened him in weakness,
and enabled him to rejoice in the Lord his Redeemer
as he approached "`the valley of the shadow of death.`"

In a letter which he wrote soon after the disease had assumed alarming symptoms, he says:
"`I have much time to spend alone, and I assure you, my dear uncle,
that during these moments I do endeavour to offer up a silent prayer to the Almighty,
that He may be pleased to direct my feeble steps aright,
and lead me in that path wherein alone there is true peace and comfort.`"

Not very long afterwards, he writes thus:
"`I can say that I have often felt thankful for the
lenient afflictions which I have to bear,
for they have been the cause by which I have been brought to a fuller
sense of my own unworthiness and have made me humbly endeavour to offer
up petitions for help to Him from whom true help can alone be procured.`"
In another part of the same letter he says:
"`I am quite aware that in such cases as mine, there is very little hope of recovery;
this knowledge makes me endeavour more and more to attain
to that state in which I may in confidence say,
'`Yes, though I walk through the valley of the shadow of death, I will fear no evil,
for you are with me, your rod and your staff they comfort me.`'`"

In another letter he remarks:
"`It is with pleasure I am able to inform you that the Almighty, in his mercy,
has permitted me to enjoy a peaceful and comfortable state of mind,
though I have at times been brought very low,
and have been led to consider my own utter unworthiness.`"
Although he was aware of the gradual, but certain approach of death,
yet so gentle were the dealings of the Lord with him,
that he had hitherto been spared much acute suffering,
and was still capable of social enjoyment, and able to rise early in the day.
His mind seemed to be awakened to a lively sense
of the continued mercies of his heavenly Father,
and to a grateful acknowledgment that all, even his domestic comforts,
were to be attributed to his lovingkindness.

To many of his later memoranda he appended passages
of Scripture which had impressed his mind,
and which in some cases were strikingly appropriate to his situation.
After having passed a comfortable night, he remarks:
"`I saw clearly that it is the duty of every Christian,
to return thanks for the mercies of the night,
and humbly to seek for the protection and guidance of the Almighty throughout the day,
and for an increase of faith in Jesus Christ our
Saviour;`" which is followed by this quotation,
"`The righteous shall be glad in the Lord, and shall trust in Him,
and all the upright in heart shall glory.`"
On one occasion, alluding to the state of his mind in the morning, he observes,
"`The remainder of the day I was permitted to feel a more patient resignation
to the Divine will;`" and in the record of the same day there occurs this extract,
"`Lord, make me to know my end, and the measure of my days, what it is;
that I may know how frail I am.`"
He was enabled with cheerfulness to endure his trials,
and through all to acknowledge the goodness of the Lord.
On one occasion he remarks: "`Though in much pain, I was permitted to feel content,
and to look upon my afflictions as blessings from the Almighty,
who orders all things aright:`" and immediately subjoins,
"`Blessed is every one that fears the Lord,
that walks in his ways;`" and he further adds:
"`I will sing unto the Lord because he has dealt bountifully with me.`"

Having so richly experienced the lovingkindness of the Lord, his faith was strengthened,
and to use his own terms,
he was permitted to feel an entire resignation to the Divine will,
and a willingness to put himself into the hands of the Almighty;
and on reviewing his past life, a humble desire was raised in his heart,
"`that the remainder of it might be spent in the praise and service of the Almighty.`"
In reference to a disappointment he had met with, he says,
"`But I hope I was preserved in a Christian spirit,
and was better able to command my temper, for which I felt thankful;`" and then adds:
"`Oh give thanks unto the Lord, for he is good; for his mercy endures forever.`"
Again he says:
"`I endeavoured humbly to return thanks for the many mercies of the past week,
and to ask for a continuance of them.
Though unable to attend meeting,
I was permitted to spend the time in a peaceful and resigned state of mind,
and to have comfort in feeling that though alone, yet God was with me.`"
He then adds, "`I will praise you, Oh, Lord my God, with all my heart,
and I will glorify your name forevermore.`"
On another occasion he says: "`Not quite so well today,
but patient and resigned to the Divine will, feeling confident that the Almighty will,
watch over and assist those who humbly endeavour to draw near to Him,
through faith in Jesus Christ.`"

The following remark in his journal, evinces his endeavour to seek the Lord.

"`Some of the family attended meeting, while I was permitted to spend most of an hour,
I think I may say, in communion with my Maker.
Enjoyed peace of mind during the remainder of the day.`"
At this time he seems to have kept closely on the watch,
and was often in the practice of reviewing his conduct.
He says, "`I looked back upon the actions of the past days,
and endeavoured humbly to seek forgiveness for all that I have omitted to do,
and for what I have done amiss,
and also for assistance to conduct myself in a manner
which shall be pleasing in the Divine sight.`"
As the strength of the dear invalid decreased,
he was particularly fearful of giving way to feelings of impatience,
and was much concerned to attain a state of true resignation to the Divine will.

In a letter to his uncle, he remarks:
"`I am able to say that I do feel that Jesus Christ did indeed die for me;
that He is my Saviour, and that by and through Him alone, I can hope for salvation.`"
His strength continued to decline, and in his journal is the following record:
"`I found myself very weak,
but felt able and willing to trust in the mercy and
goodness of the Almighty;`" and again,
"`My bodily weakness increases,
but I hope that my mind is strengthened by faith and trust in the Almighty,
through Jesus Christ, my Saviour and Redeemer.`"
On the evening of the 26th of seventh month, 1834,
after sitting up and conversing cheerfully for some time,
he retired to rest without any apparent symptom of dissolution;
but about midnight he appeared to be sinking,
and the family were summoned to his bedside: his breathing became very difficult,
and the power of utterance nearly failed;
but on being inquired of as to the clearness of his prospect,
he intimated in reply that he was quite happy; and shortly after passed quietly away,
in the 21st year of his age.

[.asterism]
'''

RICHARD STANSFIELD, late of Lothersdale in Yorkshire,
was the youngest son of John Stansfield, one of the seven Friends who,
in the years 1795 and 1796, suffered much loss of property,
and a tedious imprisonment in York Castle, in consequence of refusing,
for conscience sake, to pay tithes.
The gracious regard of that blessed Redeemer,
for whose sake the father was made willing to endure persecution,
was very early extended to his child, who was, in his tender years,
favoured with serious impressions.
His disposition was meek and amiable, and he appears to have been, through Divine grace,
much preserved in the fear of God;
and to some of the exercises of his mind in his youthful days,
he referred at a later period of his life, in an instructive manner.

After leaving Ackworth school, he was introduced into the wool trade;
but on the expiration of his apprenticeship,
his inclination not leading him to mercantile pursuits, he entered on a farm.
His capital was very limited,
and it was only through great industry and care that he was able,
with credit and respectability, to maintain his family.
After being a house-keeper about two years, he was united in marriage to Elizabeth Dixon;
to her he was a most affectionate husband,
and to his children a tender and judicious father.
He possessed a very diffident mind, and his demeanour was remarkably mild and unassuming.
The circle in which he moved was not an extended one,
but by such as had the opportunity of being acquainted with him, he was highly esteemed.
He lived much secluded from the world,
but there is good ground to believe that it was his
primary concern to seek communion with his Maker.

In the course of a lingering illness, which commenced with inflammation of the lungs,
in the sixth month, 1835,
he manifested a remarkable degree of patience and resignation to the Divine will;
and often expressed his thankfulness even for his sufferings,
believing they were intended for his further purification,
and his confidence that the Lord would not lay upon
him more than He would enable him to bear.

During the first month, 1836, the inflammatory symptoms had much abated,
yet the physician gave no hope of his ultimate restoration to health;
he appeared to be fully aware of his critical situation,
and to be often engaged in mental supplication.
He remarked to his wife, in speaking of his dear children,
that it was his earnest prayer they might choose the Lord for their portion,
and he believed they would be provided for; "`yes,`" he said, "`the Lord will provide.`"
His cough becoming relieved, he said, "`How thankful I feel, that my cough is better;
it allows me more time for reflection.`"
Appearing on one occasion much tried, his wife inquired the cause; to which he replied,
"`I have cause to mourn my many backslidings;`" but
in a short time he spoke of the Lord`'s mercy,
saying,
"`He is very gracious to poor unworthy sinners.--Though your sins be as scarlet,
I will make them white as snow.`"
"`On the 29th of the same month he expressed his assurance
that he should be enabled to bear his pain saying that the Lord
laid nothing on his children but what he would strengthen them to bear,
and added, "`It is very little that we have to suffer,
in comparison with what our Saviour suffered.
Oh, what adorable love, that God sent his only begotten Son,
that whosoever believes on Him should not perish, but have everlasting life.`"
On the 30th, he enjoyed much of the presence of his Saviour, and remarked,
"`My heart overflows with love.`"

On another occasion, his heart being filled with divine love, he said,
"`Oh! how good the Lord is!
I have had dark seasons;
but He is very near,--He is waiting to be gracious.--What
a favour it is to be afflicted! it allows us time to prepare;
while some are taken very suddenly: we ought to rejoice instead of complaining.`"
At another time, when his wife was sitting by him, he said,
"`Jesus is all I have to look to.--I have no righteousness of my own to boast
of,--but He is very merciful to poor unworthy sinners;--I feel him very near.--Yes,
He is waiting to be gracious to us and our dear offspring.`"
Then addressing his wife, he said, "`Let the Lord be your chief delight;
then he will be very near to you: His protecting arm will be underneath you;
and He will support and guide you.
And if we are parted here, we shall meet again in Heaven, where parting will be no more.
He will withhold no good thing from you, if you only put your trust in Him.`"
A while after he said, "`My dear, I have enjoyed much peace tonight;
I feel quite refreshed; these are precious seasons.`"

31st. Two friends calling to see him, after a short time of silence, he said,
"`'`Draw nigh unto the Lord,
and He will draw nigh unto you.`' He never did cast
off any who came to Him in truth and uprightness.
Seek the Lord while He may be found.
I have found Him a present help in this time of need,
forever blessed and praised be His name, for He alone is worthy both now and forever.`"

4th of second month.
After a time of silence with two dear friends who visited him,
he expressed much of the goodness of the Lord to his soul and of the mercy
of God in sending his Son Jesus Christ to die for sinful man.
He petitioned for preparation for everlasting rest, and added,
"`'`In my Father`'s house are many mansions;`' our dear
Saviour told his followers so for their encouragement;
and if I am but permitted to enter the lowest room,
where the unwearied enemy can no more disturb, it will be enough.`"
He often said he felt much peace of mind, not such as the world gives, nor,
blessed be the Lord`'s holy Name, can take away.

5th of second month.
Speaking of the love of God, he said, "`We are without excuse,
seeing He would draw us with the cords of His love, if we did not turn our backs on Him.
How inviting are His promises; '`Come unto me,
and be saved all you ends of the earth.`' He wills
not the death of any but rather that all should return.`"

7th. He remarked that his heart was made to rejoice in his affliction,
and to ascribe all praise and glory to God.
8th. He supplicated fervently, first on his own account, then for his dear children,
and also for his wife, saying, "`O Lord!
I beseech you, gather them under the shadow of your wing; lead them gently, O Lord,
in the way you would have them to go;--unto your care I must leave them,
for I have no other that I can trust: You alone can guide them aright.`"

At another time, after having passed a restless night, he said,
"`How thankful I ought to be for all the benefits I enjoy! and I do feel
thankful in my heart to my God for all His mercies to me.
Sweet Jesus!
I will look to You as long as I live; for You are my only hope.
Continue with me to the end, if it be consistent with Your most holy will.
Purge me, and cleanse me, and make me fit for your blessed kingdom.
Take away everything which is not consistent with your holy will;
for You are my Shepherd, my Friend, my keeper!`"
He often spoke of the love and mercy of God in sending His dear Son to die for our sins.

At one time he said,`" I am very weak; but the Lord in his tender mercy,
is inclined still to look down with an eye of pity.
He still has regard for my poor soul that it may not be wholly lost.
Oh! how good He is to a poor unworthy creature!
His mercy is indeed very great:--Ah! what should I do without Him?
All would he lost!--but He condescends in His love and adorable wisdom,
to have regard to a poor unworthy creature.
He has in a wonderful manner preserved me on every side.--Oh! it seems
as if the enemy was not permitted to discourage me from looking unto Jesus,
the author and finisher of my faith.`"

On another occasion, being asked how he was, he said, "`I am very weak;
but Christ is strong, and He is very willing to lend me His aid.`"
A few friends being in his chamber, after a time of silence he remarked,
"`There is a passage of Scripture where our Saviour says, '`Peace I leave with you;
my peace I give unto you, not as the world gives;`' oh no, it is quite of another nature;
the peace of the world brings sorrow, but His peace is the fruit of righteousness.`"

On the evening preceding his decease, he was engaged in prayer to the following effect:
"`O,
sweet Jesus! condescend in your lovingkindness to look down upon a poor afflicted worm.
I can do nothing of myself; therefore I have delivered all into your care;
and You are very good!
Continue your lovingkindness unto the end, I beseech you;
and land me safe on that shore where I shall have done with this world of trouble.
I do not doubt that You will be with me to the end,
my God! and it will be a great rejoicing to me:--then I shall be safe;
the unwearied enemy will no more disturb me.
I shall have nothing to do but to praise You!
Then I can sing praises to Your adorable name forever!--but I must not crave it too much.
Do with me, O my God! as seems best in your most holy sight.`"

Early the next morning, being in great suffering,
his sister asked what could be done for him?
he replied, "`Let us compose ourselves in the Lord: that is best for us.`"
On one present remarking he was very ill, he said,
"`I would not change for the whole world.`"
A short time before his spirit took its flight, he exclaimed with great distinctness,
though his breathing was very difficult, "`Great and marvellous are your works,
Lord God Almighty!
Just and true are all your ways, O King of Saints!`"

He departed this life on the 29th of second month, 1836, aged 32 years.

Meditating on his peaceful transit from time to eternity,
how forcibly does the triumphant exclamation of the
Apostle suggest itself to the mind! "`O death,
where is your sting?
O grave, where is your victory?
Thanks be to God, which gives us the victory, through our Lord Jesus Christ.`"

[.asterism]
'''

I apprehend few persons can read the foregoing pages
without feeling desires raised in their minds,
that when called to lay upon a dying bed,
they may enjoy the peace and consolation which crowned
the closing days of the subjects of these brief memoirs,
and be enabled to look forward to an endless eternity,
with a well grounded hope of being accepted through the
merits and mediation of the adorable son of God.

This happy state is undoubtedly attainable by all; and those who fail to realize it,
will, in the end, be brought to the mournful acknowledgment that the fault is their own,
and their destruction, of themselves.

The means of salvation are freely offered for our acceptance;
the terms upon which we may become the redeemed of
the Lord are clearly pointed out in the sacred volume;
and it rests with ourselves, either to choose the Lord Jesus for our portion,
and thereby obtain an interest in that redemption
which he purchased for us by his precious blood,
or to deny Him and reject his blessed government in our hearts, the consequence of which,
we are assured from the highest authority, will be, that in the day of final retribution,
he also will deny us before his Father and the holy angels, saying,
"`Depart from me, you workers of iniquity, I know you not.`"

It is important for us to bear in mind,
that neither good desires nor virtuous resolutions will avail us anything,
unless they are reduced to practice.
If we wish to die the death of the righteous, we must live the life of the righteous.
We must take up our cross and follow the footsteps of the flock of Christ`'s companions.
"`You are my friends,`" said our holy Redeemer, "`if you do whatsoever I command you.`"
And it follows as a necessary consequence, that if we do not keep his commandments,
we cannot be his friends;
we do not belong to that happy number whom he condescends
to acknowledge as his brethren and sisters,
and to whom, at the last day, he will address the joyful invitation, "`Come,
you blessed of my Father,
inherit the kingdom prepared for you from the foundation of the world.`"

To have Christ Jesus for our friend is the highest privilege
and purest happiness of which a rational being is capable.
It is to be united to Him who has all power in heaven and earth;
whose faithfulness and love far surpass the most
constant and disinterested earthly affection,
and who is graciously disposed to do for us abundantly more than we can ask or think,
as respects both our temporal comfort and our eternal felicity.

This unspeakable privilege is as freely conferred on youth,
as it is on those of riper years.
Even children may become the friends of Christ,
if they comply with the terms on which he offers them his friendship.
The Lord Jesus when personally on earth,
was pleased on several occasions to evince his love for little children.
Some, he healed of their diseases; others, he raised from the dead;
and when his disciples would have sent away those who brought them to receive his benediction,
he rebuked them, saying,
"`Permit the little children to come unto me and forbid them not,
for of such is the kingdom of heaven: and he took them in his arms,
and put his hands upon them, and blessed them.`"
He offered up his life as a propitiatory sacrifice
for their sins in common with the rest of mankind,
and voluntarily submitted to a painful and ignominious death on the cross,
in order to save their immortal souls from endless destruction.
Such is his kindness and condescension,
that he still continues to visit them by his good Spirit in their hearts;
and though they may feel themselves unworthy of the regard and care of
Him who is "`now Lord of all,`" yet if they faithfully serve him,
and live in his fear,
he will guide them by his counsel during the short
and uncertain period of their stay on earth,
and afterwards receive them up into glory.

In order to entitle us to the character of the friends of Christ,
we must deny ourselves every sinful indulgence,
and whatever is opposed to the purity and righteousness of his kingdom; for he declares,
"`Whosoever does not bear his cross and come after me, cannot be my disciple.`"
To do this, requires a constant watchfulness over our own spirits and tempers;
the subjection of our wills, and a continual mortification of our selfish appetites.

The Holy Scriptures inform us, that mankind universally,
inherits a fallen and corrupt nature, which is prone to evil as the sparks fly upward;
and a little attention to what is passing in our own breasts,
will confirm this truth in the experience of every unprejudiced observer.
How often are children betrayed, by their wayward propensities, into anger, malice,
revenge, falsehood, the use of bad language, disobedience to parents,
and other evil actions and thoughts, which are offensive in the Divine sight.
The enemy of their happiness,
who is ever seeking to allure them from the paths of innocence and virtue,
adapts his temptations to the weakness of their nature,
and makes use of their untoward dispositions as a
means of accomplishing his wicked designs.

It is however no sin to be tempted;
the evil lies in yielding to the temptation and surrendering
our hearts to the power of the tempter.
If we "`resist the devil,
he will flee from us,`" our strength will be increased to withstand his future assaults;
the rich reward of peace will more than compensate us for every trial,
and if we persevere,
we shall at length be made "`more than conquerors through Him who has loved us.`"

He who was "`tempted in all points as we are,
yet without sin,`" and who was perfectly acquainted with the frailty of human nature,
addressed his immediate followers in this emphatic language, "`What I say unto you,
I say unto all, watch!
_Watch and Pray,_
lest you enter into temptation:`" and there is no lesson with which
it is more important for young persons to be early acquainted,
than the great duty of watchfulness over their thoughts and conduct,
and daily prayer to the Lord for preservation from sin,
and strength to withstand the various temptations with which
the slippery paths of youth are surrounded.

Our dear Redeemer, whose providential care is extended over every part of his creation,
beholds with tender compassion the frailty of his children.
"`He knows our frame and remembers that we are but dust.`"
He "`is touched with the feeling of our infirmities,`" and
in order to assist us in working out the soul`'s salvation,
has placed a manifestation of his own blessed Spirit in each of our hearts,
as a swift witness against evil, and as a comforter when we do right.
"`The grace of God which brings salvation has appeared unto all men,
teaching us that denying ungodliness and worldly lusts, we should live soberly,
righteously and godly in this present world; looking for that blessed hope,
and the glorious appearing of the great God and our Saviour Jesus Christ,
who gave himself for us, that he might redeem us from all iniquity,
and purify unto himself a peculiar people, zealous of good works.`"

This spirit of Christ or grace of God, strives with children while they are very young;
forewarns them against the commission of evil,
and condemns them when they have done amiss, producing distress and trouble of mind,
even though their fault may be known to themselves only; and on the other hand,
when they have been obedient to its monitions and endeavoured to do right,
it imparts a peace and tranquillity which far transcend
all the pleasures and delights of the world.

It is of the utmost importance that children should attentively
listen to this inward monitor and implicitly obey its instructions,
for it is the messenger of Christ`'s love to their souls.
It is "`the still small voice`" of mercy pleading
with them--it is the angel of His presence,
sent to conduct them safely through the difficulties
and dangers of this ever-changing state of existence,
to those "`perpetually abiding habitations`" which He has gone before to prepare
for his obedient followers--and as they yield to its secret manifestations,
it will not only "`lead them into all truth`" but preserve them from evil of every kind.

There are few temptations more common to youth,
or so often fatal to their religious improvement, as procrastination.
No sooner are they awakened to a sense of the exceeding sinfulness of sin,
and the necessity of leading a religious life,
than the tempter presents his suggestions to delay.
He represents to them that they are young and have a long life in prospect,
and it will be time enough to become religious some years hence--that they may
take their ease and enjoy the gratifications of the world for a while,
and at last make very good men and women;
and he never fails to present instances of persons among their acquaintance,
who did not "`take a serious turn`" until they were much older than themselves,
and yet became pious people.
Year after year the minds of youth are thus unhappily
diverted from the great work of the soul`'s salvation,
still resolving, and perhaps with some sincerity,
that by and by they will make a full surrender to what they know is right,
and dedicate themselves to the Lord`'s service.

But alas! they know not that this "`by and by,`" this "`more
convenient season,`" will ever come to them;
they do not reflect on the awful uncertainty of life,
or the possibility that the offers of mercy with which they are
thus trifling may be the last that will be tendered to them.
The day of their visitation may quickly pass by,
and the language become applicable to their situation,
"`How often would I have gathered you as a hen gathers her chickens under her wings,
and you would not.
Behold your house is left unto you desolate,
and the things which belong to your peace are hid from your eyes.`"
The cold night of the grave may before long close over them,
in which there is neither work nor knowledge, nor device;
and even before the dawning of another day,
their condition may be unalterably fixed for a never-ending eternity.

The preceding pages furnish abundant evidence that the health
and vigour of youth are not exempt from the stroke of death,
and the occurrences of almost every day confirm the fact.
How many of our young friends, who, but a little while ago,
were as strong and lively and joyous as ourselves,
and whose prospects of a long life were as flattering as our own,
are now mouldering in the silent tomb.
We have no certainty that it may not be our turn next;
and inasmuch as there is no repentance in the grave,
no returning to correct mistakes or repair the errors we have committed,
how dangerous is the condition of those who are putting off the
all-important work of redemption to a more convenient season.

The same reasons which now induce them to delay,
will operate with equal or increased force in every succeeding year of their lives;
new motives for procrastination will also be suggested,
while the continued neglect of known duty, and long familiarity with sin,
will enervate their virtuous resolutions,
and render the mind an easy prey to the wiles of the tempter;
until at length it becomes so entirely enslaved to his power,
that there is little hope it will ever be emancipated from the loathsome bondage.
With peculiar propriety, therefore,
may the exhortation of the Apostle be addressed to youth,
"`Today if you will hear his voice, harden not your hearts.
Now is the accepted time--Now is the day of salvation.`"

The present is an age in which children enjoy peculiar advantages,
as respects both literary and religious instruction,
and it is unquestionably their duty to make a correspondent improvement.
These advantages are blessings committed to our trust,
to be improved to the glory and praise of the beneficent Giver,
and for which we shall at last have to render an impartial account.
If we neglect or misuse them,
they will certainly add to our condemnation in that great
day when the Judge of all the earth shall reckon with us.
When we contemplate the ample provision which is made for supplying all our needs,
the profusion of spiritual and temporal benefits
dispensed to us by the bounty of kind Providence,
and remember that "`where much is given,
much will be required,`" we cannot but acknowledge that the responsibility
which rests on the present generation is serious,
and that we owe a deep debt of gratitude and love to our Father who is in heaven.

Among these advantages it is not the least, that we are permitted to assemble unmolested,
for the purpose of offering the tribute of grateful
adoration to the Author of all our blessings.
Those who properly estimate their dependent condition and the duty they owe to the Almighty,
cannot omit the diligent performance of this reasonable service.
They will not merely attend at their respective meeting places,
but by watchfulness and prayer,
strive to attain that "`preparation of the heart`" which
will qualify them for reverent waiting on the Lord,
and the performance of Divine worship in spirit and in truth.
Indifference or neglect in this christian duty is a certain evidence
that our hearts are not right in the sight of God.

Another great blessing is, the free access to the society of pious persons,
which is not only profitable as a means of religious improvement,
but as a preservative from the pernicious influence of evil company--than which,
there is not a deadlier bane to youthful piety and innocence.
As evil communication is always found to corrupt good manners and destroy good morals,
so a frequent fellowship with those who live in the habitual fear of God,
tends to strengthen virtuous resolutions, to increase our love of holiness,
and animates us to pursue with greater diligence
the "`things which accompany salvation.`"

It is not, however, the company of the profane and dissolute only,
which young persons should shun.
The friendships and pleasures of the world,
and intimate association with those who are captivated by its vain pursuits,
are prejudicial to a religious life.
"`If any man love the world, the love of the Father is not in him.`"
If our affections are set on heaven and heavenly things,
our hearts and conduct will be there also,
and we shall have little relish for the amusements and idle discourse
which are too common even among many who profess the holy name of Christ.
Not that we are to make religious subjects a common theme of discourse--this
would be to err on the other hand but we are to guard against unprofitable converse,
and to observe, in all our association with the world, the injunction of Holy Scripture,
"`Let your conduct be such as becomes the Gospel of Christ.`"
If "`for every idle word that men shall speak,
they shall give an account in the day of Judgment,`"
what a fearful reckoning will it be to those,
the greater part of whose time is spent in trifling conversation,
while the levity of their deportment manifests that
"`God is not in all their thoughts.`"

The Scriptures of Truth,
which were written under the immediate inspiration of the Holy Spirit and preserved
through a long succession of years by the providence of the Almighty,
constitute the richest outward treasure which the christian possesses.
They furnish an inexhaustible fund of doctrine, instruction, warning,
reproof and consolation;
and those who live in conformity with the teachings of the Spirit of Christ Jesus,
cannot but have a reverent esteem for them and be
diligent in the perusal of their invaluable pages.
This was a distinguishing trait in the character of those young
persons whose peaceful deaths are recorded in the present volume,
and in a country where the bible is so easily accessible,
it is scarcely possible that any advancement can be experienced
in the work of religion while a love for its precious contents
or a frequent and serious perusal of it is lacking.

It is in the sacred volume that we are taught the doctrines of our holy religion.
The existence of one Almighty Being; the creation and fall of man; his accountability;
the promise of a Deliverer; the Divine character, miraculous birth,
holy life and mighty miracles of our Lord and Saviour Jesus Christ,
his adorable condescension and mercy in voluntarily offering
up his life a propitiatory sacrifice for the sins of mankind,
and that effusion of the Holy Spirit which constitutes the glory of these gospel days,
are all traced there in characters which cannot be mistaken.
These important truths are necessary to be believed,
not merely by a bare assent of the understanding to their literal accuracy,
as recorded by the inspired penmen,
but by a practical and saving faith which shall influence our hearts
and become the regulating principle of all our actions.

These solemn truths ought never to be made the subject of familiar and common conversation.
We should approach them with reverence and fear,
and rather accustom ourselves to meditate upon them in humble, silent admiration,
than too freely to impart our thoughts and feelings to others.
If we duly consider the import of these scripture passages,
"`Sanctify the Lord of Hosts himself, and let him be your fear,
and let him be your dread,`" and "`Let every one that names the name of
Christ depart from iniquity,`" we shall feel a holy care in making use
of the awful names which are employed to describe the Supreme Being.
The needless introduction of them into conversation,
even though it be professedly religious,
can scarcely be considered in any other light than as a violation of that injunction,
"`You shall not take the name of the Lord your God in vain,
for the Lord will not hold him guiltless that takes his name in vain.`"

We should also guard with vigilant caution against a disposition to think lightly,
or to speak irreverently, of the Lord Jesus, of his glorious offices as our Redeemer,
Mediator and Intercessor with the Father,
or as the great Propitiation for the sins of the world.
The more we contemplate his Divine character as delineated in Holy Scripture,
his love for sinners, his compassion for the sorrows and sufferings of the human family,
and the gracious offers of pardon and reconciliation which he holds out for our acceptance,
the more our hearts will glow with reverent gratitude and adoration,
and in humble acknowledgment of his unbounded mercy, be prepared to say,
"`What shall I render unto you, O Lord, for all your benefits?`"

There is no ornament so lovely and engaging in youth,
as that of "`pure and undefiled religion`"--nothing that will so effectually
shield us from the dangers and snares that beset the path of life,
or mitigate the afflictions and sorrows which are
inseparable from the present imperfect state of existence.
If we have in our possession this "`pearl of great price,`" we
may be happy in the most discouraging and trying circumstances,
and meet sickness, pain, and even death itself, with calmness and resignation,
in the humble assurance that under the direction of a wise and beneficent Providence,
all things will ultimately work together for our good.

Without the consolations of religion, our search for happiness will be fruitless.
The world with all its glittering pleasures can yield us no solid enjoyment;
the mind will be involved in continual anxiety and unsettlement,
a prey to disappointment and vexation,
and incapable of taking any real satisfaction even in the good things of this life;
while as regards that which is to come,
there will be "`a fearful looking for judgment and fiery indignation.`"
Like the mariner driven upon the boisterous ocean without a pilot or compass,
we shall be the sport of every adverse gale, tossed by every angry billow,
and continually in dread of being swallowed up in the threatening deep,
without the cheering hope of being safely landed at last in the haven of eternal rest.

Inasmuch, therefore, as our present happiness and our everlasting salvation are at stake,
with an awful uncertainty how soon the die may be cast,
which will determine our portion forever, either with the righteous or the wicked,
it becomes us to be earnest in the inquiry,
What are our hopes and prospects for eternity, and what would be our sentence,
were we at this moment summoned before the judgment seat of Christ?

If we are living in opposition to the convictions of Divine grace in our own minds,
and to the doctrines and precepts of the Holy Scriptures,
we have no reason to believe that we shall find acceptance,
unless by unfeigned repentance and amendment of life,
we obtain an interest in the mercy and merits of Jesus Christ, our great atonement.
Every moment`'s delay is hazarding our immortal souls,
and trifling with that omnipotent Being, who, though he "`keeps mercy for thousands,
and forgives iniquity,
transgression and sin,`" has declared that "`he will by no means clear the guilty.`"
It surely behooves us, under such circumstances,
to make an early sacrifice of our whole hearts to God,
and by obedience to the teachings of his Holy Spirit,
and a faithful improvement of those means of religious
instruction with which he has blessed us,
to "`use all diligence to make our calling and election sure,
before we go hence and are seen of men no more.`"

As it becomes the primary concern of our lives thus to regulate
all our actions in conformity with the will of God,
we shall often feel "`the consolations of the Gospel to abound by Christ,`" and be prepared
from living experience to adopt the devout language of the royal Psalmist,
"`One thing have I desired of the Lord, and that will I seek after:
that I may dwell in the house of the Lord all the days of my life,
to behold the beauty of the Lord, and to inquire in his temple.
For in the time of trouble he shall hide me in his pavilion;
in the secret of his tabernacle shall he hide me; he shall set me upon a Rock.
Therefore will I offer in his tabernacle, sacrifices of joy; I will sing, yes,
I will sing praises unto the Lord.`"
