== Conclusion.

And now, Reader, before thou close the book, pause a little, and consider,
what progress thou hast made in this heavenly race.
The prophet Isaiah, after describing the coming of Christ,
and very emphatically setting forth his office, the peaceable government of his power,
and its glorious effects upon his followers, in chap. 11,
in the next chapter declares what the faithful experience:
"`And in that day thou shalt say, O Lord!
I will praise thee; though thou wast angry with me, thine anger is turned away,
and thou comfortedst me.
Behold, God is my salvation, I will trust and not be afraid,
for the Lord Jehovah is my strength, and my song, he also is become my salvation.`" Isaiah 12:1-2.

The same living, divine power,
the same inexhaustible source of wisdom and goodness remains.
The enjoyments of time are transient, its pleasures are delusive;
let therefore all trust in his arm: this is the strength and beauty of men;
their alone help and dependence is here, in all their exercises through time,
that when they come to close, as has been the case with the just in all generations,
in effect, to declare, "`Behold, God is my salvation, I will trust and not be afraid;
for the Lord Jehovah is my strength and my song, he also is become my salvation.`"

[.the-end]
END OF THE EIGHTH PART
