== The Journal of Charles Marshall

I was born in the city of Bristol, in the Fourth Month, 1637.
My education and upbringing was after the strictest manner of religion,
my parents being such as feared the Lord.
I was kept much from the company of other children,
and about the fifth and sixth years of my life I learned to read the Scriptures of truth,
in which, after a little time, I took much delight.
In my very tender years I had an abhorrence of swearing, lying, and such like sins;
and not only so, but many times I had inward desires and breathings to know God.
So by about the eleventh and twelfth years of my life,
I not only longed to know the true and living God, but I also sought after Him,
and loved and esteemed sober, honest people who feared the Lord.

I went with my mother to the meetings of the Independents in
the days when they were still tender and sincere.
Sometimes I went to the Baptists`' meetings to hear
those men who were esteemed most zealous in their day.
Among this people, and in these assemblies,
there were sometimes spiritual awakenings through the
inward stirrings and strivings of the gift of God;
and under the sense of this,
living pantings and breathings sprung up in many souls after the true,
spiritual knowledge of God who is a Spirit.
But most went out from this state of tenderness, into a profession of the saints`' words,
works, and enjoyments, and left this pure measure of light, life, and truth behind.

Now as I advanced in years, I grew more and more dissatisfied with lifeless,
empty professions and professors,
feeling the burden of the nature of sin which lay upon my spirit.
In the sense of my sin, I became solitary and mourned like a dove without a mate.
And seeing I could not find the living among the dead professions of Christianity,
I spent much time in retirement alone, in the fields and woods, and by springs of water,
where I delighted to lie down and drink.
And in those days of retirement, strong, great, and many were my cries unto the Lord.
Sometimes, being retired into places that were free from all other company,
in order to ease my heart I would cry aloud because of heaviness of spirit.

In those days I had openings of the miserable
fall and inexpressible degeneration of mankind,
and the captivity and bondage which my soul lay in.
In a true sense of this state of bondage and slavery, I cried out, "`Oh,
that my soul might be eased from these heavy burdens and loads of death and darkness!
Oh, that I might be saved out of the state of gross Egyptian darkness,
and from the land of drought, the land of anguish, the land of horrible darkness!
Oh, undeclarable fall!`" said my soul, "`Oh,
inexpressible wall of partition and separation!
Oh, gulf unutterable!`"
For the fallen and undone state of the sons and daughters of
men was opened to me beyond all words to demonstrate.

At that time, as I walked and beheld the creation of God Almighty,
everything testified against me.
Heaven and earth, the day and the night, the sun, moon, and stars, yes,
the watercourses and springs of the great deep, all kept their respective places.
The grass and flowers of the field, the fish of the sea and fowls of the air,
all kept their order; but man alone, the chief work of God`'s hand, was degenerate.
Then I cried out bitterly,
"`Man`'s state in the fall is worse than that of the
beast that perishes! '`For the ox knows his owner,
and the donkey his master`'s crib,`' but man, in this state, is ignorant of God his maker,
and has become a stranger unto Him, walking in enmity and disobedience,
and serving and obeying the devil, who neither created anything,
nor can preserve any living thing!`"
From the beginning, Satan`'s appearance against God has been pure enmity, altogether evil,
a destroyer and a murderer.
And such is the inexpressible, thick darkness that has come over man,
that he gives himself up in body, soul, and spirit, to be led by him.
In this I saw that thick darkness had come over the families of the earth,
and I could set my seal to the truth of that Scripture, "`Darkness covers the earth,
and gross darkness the people.`"

So in a deep sense of man`'s miserable condition,
and particularly of my own captivity and share in this darkness, misery, and sorrow,
I fell to the ground,
and cried unto God for deliverance and redemption out of this state.
And though the witness of God stirred in me in this way,
and indeed was the revealer of this miserable state,
yet still I did not have a clear knowledge of Him who had revealed it to me.

In that time, which was about the year 1654, many were seeking after the Lord,
and there were a few of us that kept one day of the week in fasting and prayer.
When this day came, we met together early in the morning, and without tasting anything,
we sat down sometimes in silence.
As any found a concern upon their spirits and an inclination in their hearts,
they kneeled down and prayed to the Lord.
Sometimes, before the day ended, there might be twenty of us gathered together.
Men, women, and sometimes children, spoke a few words in prayer,
and we were sometimes greatly bowed and broken
before the Lord in humility and tenderness.

To one of these meetings, in the year 1654, came dear John Audland and John Camm,
messengers of the ever-living God.
By John Audland`'s powerful ministry (which was committed to
him by the Lord) I was reached and turned to the Spirit of God
(the very One who had formerly revealed my condition unto me,
as before-mentioned). The testimony that was borne by
these two messengers was readily received,
and as I kept close to the Spirit, to which I was turned,
I saw a great separation made between light and darkness, the day and the night,
the precious and the vile.
And as my mind loved the light, judgment was set up in my heart, even "`laid to the line,
and righteousness to the plummet`" (Isa. 28:17).

I was brought into great dread, fear, and awe of God,
and also had great esteem and regard for His messengers,
who brought the acceptable tidings of life and salvation,
and through whom true doctrine dropped as the dew.
Because their words were gracious words,
there was a great fear in my heart of rebelling against
any part of the counsel I received from them.

I then experienced a long travel through the administration of condemnation,
which indeed was glorious in it`'s time.
And as I kept down to the judgment of the Lord in my heart,
I found the operation of it was like a sword, a fire, and a hammer,
and the evil nature was in some measure overcome,
and then something of divine refreshment and love flowed in,
which refreshed me in my travels.

But then the old subtle enemy began to lay snares and hunt after my soul,
which had in some measure been rescued out of the jaws of death.
For when I had precious openings of the way of Truth
(through which a secret hope and joy sprang up),
then the enemy led me away from sinking down into a sweet enjoyment and treasuring up,
to spend my own bread in disputes for Truth against opposers,
and to declare it to those who I thought had some love for it.
But when I had thus spent the bread which was
given to me for the strength of my own soul,
and came home and communed with my heart, I found myself quite empty,
having leaked out that which was given for my refreshment and consolation,
and I saw that my Beloved had withdrawn.
Then distress took hold of me beyond expression, and I was greatly bowed down.
By having some understanding of the cause,
I was ready to promise that if I ever came to my former peace, refreshment,
and feeding again, I would not run out recklessly, nor spend my portion,
by which that inward trouble and barrenness had come over my spirit.
And here the enemy (who by his transforming had thus led me
out) worked with subtlety in the day of my trouble,
in order to bring great discouragements and unbelief over my spirit.

My soul has in remembrance the great anxiety of spirit,
and a sense of the withdrawings and hidings of the Lord`'s face,
and the veil that then came over me.
In this way I was led out in a zeal which was not according to true knowledge (that is,
the knowledge which the Lord`'s power gives in its leadings);
and when I had promised and then broken covenant,
I was pursued by the Lord as a covenant breaker.
But in time the Lord helped me over this exercise, and I learned to stand as a fool,
and to sit in silence before the Lord among His people,
rather than to wrong my condition and grieve the Spirit of God.
And when I thus remained obedient to wisdom`'s direction,
then a secret joy would spring up in me, with pure peace and inward ease.
But if I felt life and joy and the light of the Lord shining upon my tabernacle,
yet did not keep low in humility (where growth in the Truth is experienced),
then the enemy would work with subtlety again to persuade me
that there was no need for such a severe watch and inward care,
as was necessary before.
Through this deception he prevailed sometimes to lead me out into a liberty,
both inward and outward, which had a tendency to bring me again into inward bondage.

Through frequent refreshings, openings, prophecies, and promises,
I was sometimes ready to conclude that my mountain was immoveable.
But I soon found a withdrawing of the Lord`'s presence,
and then came to experience a winter again, and the various storms of the enemy.
And not having yet learned to be content in want, as well as in abounding,
I not only fell into a poor, murmuring state, but also into great trouble;
for because of this change, fears and doubts were ready to enter.
I toiled in this night, but could catch nothing that administered any lasting comfort.
Here I was willing and running and striving, being in great fear and sorrow;
and the more I toiled, "`kindling sparks of my own`" (Isa. 50:11),
the more my sorrow increased; for I had not yet learned the state of resignation.

Then, having been brought very low,
and having mourned many days in the sense of the withdrawings of the presence, love,
and power of my God, being in deep distress and amazement,
Israel`'s travels in the wilderness were opened to me--
how the Lord tried them with lack of bread and water.
I saw that their happiness stood in becoming content and resigned to the will of God,
and in the belief of the Lord`'s faithfulness to help endure the trial.
But Israel murmured, and thereby grieved the Spirit of God;
and so did I. But through the lovingkindness of God,
the state of resignation was opened to me,
in which man stood before he fell through transgression into his own working and willing.
And when my understanding was thus opened, my soul cried unto the Lord my God, "`Oh,
preserve me in pure patience and passiveness, and in living, acceptable obedience,
and I will trust in You!`"

As I believed in the light of the Lord, and in it became comprehended and resigned,
God`'s pure power, love, and life broke in as formerly, which greatly refreshed me.
Then the sun shone upon my tabernacle, and I bowed before the Lord,
blessing and praising His holy, glorious name.
Then the Lord instructed me,
and His pure Spirit and power opened in me the way of preservation,
which was to center down into true humility.
So my soul began to be as the dove that found a place for the sole of her feet.

Nevertheless, the enemy continued to tempt by his allurements,
and laid his baits and snares, so that if at any time my heart was drawn to look abroad,
or went out to view the land (as Dinah did, Gen.
34), I was in great danger of being defiled.
Indeed, I found that if, at any time, I went out from this pure,
preserving power of God which had begun to work in my soul through inexpressible travail,
and let in the spirit and reason of the world,
and thereby beheld a beauty in any fruit besides
what was brought forth by the tree of life,
then a wound, a stain, and a defilement would quickly come over me.
And if, at any time, the enemy prevailed in the inward ground,
causing me to cleave to his temptations through
the lust of the flesh or the lust of the eye,
then I became afraid (for I knew the wrath of God);
and the power of the Lord (in love to my soul) would
work mightily to sanctify and cleanse it again.

I passed through this inward exercise when no friend or intimate acquaintance knew of it.
Oh, I remember the nights of bitter sorrow that I passed,
even though I walked blamelessly among men, and no defilement could be discerned by any.
For in the great love of God to my soul, in those days of inward travail and exercise,
judgment followed quickly upon any outgoing of my mind.
But as I kept single to the Lord, and upright in heart, not joining to any iniquity,
I found the Lord near at hand in many exercises that happened in our city and elsewhere,
even through the working of the power of darkness in James Nayler,
and the runnings forth of John Perrot and others.^
footnote:[James Nayler and John Perrot were both prominent ministers
among the early Quakers who ran out into error and imagination,
and so brought a measure of division and disgrace upon the young Society.
Nayler openly confessed to his error, publicly repented on multiple occasions,
and was restored to the Society of Friends before his
death in 1660. Perrot apparently emigrated to Barbados,
where he and his views passed away in disrepute.]
God let me (who was then but a young lad) see through all
those subtle workings and transformings of the enemy,
and by a secret hand preserved me.
Of those trying times, I have not much upon me to leave in writing.
Those things are known unto the Lord, along with the ends and causes,
and His permission and letting loose of the enemy.

God has desired the keeping low of His people in every generation;
and by His power He has secretly struck at everything
that has a tendency to rob Him of His honor.
He delights in the humble, and dwells with the brokenhearted and contrite in spirit.
In this low state is safety and preservation for us in this age,
and in all succeeding ages.
Through these exercises (of which I have hinted), I have learned that,
from the very beginning of the work of restoration and redemption,
everyone`'s preservation is found in an inward retiredness unto the Lord,
and in keeping low (in His pure fear, awe,
and dread) and feeling after His soul-redeeming, preserving power,
which quickens and enlivens.
And as this is abode in, it keeps alive in its own pure nature, over the world,
and over its spirit and defilement.

I have a sense upon my spirit, beyond utterance,
of the potent workings of the enemy in the generations of mankind, to accomplish his end,
namely: that after the Lord God Almighty has appeared in any age,
in the free dispensing of His love, and the breaking forth of His power,
and the making bare of His arm in order to restore man into covenant
with Him--then has the enemy appeared with all his power and subtlety,
to gradually and secretly undermine and frustrate the work of God.
His great end has been, by different snares,
to draw the visited people into a lessening of their estimation of the power, appearance,
and manifestation of God in their day,
and to draw their mind out (by his various transformings) into
an esteem for either the manifestation that has been,
or what may be yet to appear.
This leads the mind out of a due regard for the present manifestation,
which alone can work the eternal welfare of the creature.
This was the case with those to whom it was said, "`Oh that you knew,
even in this your day, the things that belong to your peace!`"
This I have learned of the Lord,
and therefore leave it both to Friends to whom it may come in this age,
and to God`'s people in the following generations of the world.

After about sixteen years of travel in spirit, in the year 1670,
in the thirty-third year of my age,
God Almighty raised me up by His power that had been working in my heart many years,
to preach the everlasting Gospel of life and salvation.
Then a fresh exercise began, for the enemy tempted me to withstand the Lord,
and to look to my own weakness of body and spirit,
and to my insufficiency for such a great work.
And such was the prevalence of the enemy of my soul,
that had not the Lord God (in His inexpressible love) stood by me, bore with me,
and helped me, I would have perished after all through disobedience.
For when the power of God fell upon me,
and a few words were required of me to speak in
the assemblies of the Lord`'s people in Bristol,
many reasonings beset me, namely: that these were a wise people,
and I could add nothing to them; or that I might hurt my own condition;
or that imaginations might be the real ground of such requirings;
or that many wise men might look upon me as a presumptuous lad, and so judge me, etc.
Thus I reasoned many times through meetings, until I was in sore distress.
And when these meetings were over (wherein I had been disobedient),
my burden was unbearable.
Oh, then I was ready to covenant with the Lord that
if I felt the requirings of His power again,
I would faithfully give up in obedience to Him!
But when I was tried again,
the same rebellious mind would be stirred up by the power of the enemy.

Then the Lord withdrew the motion and feeling of His power, and all refreshment with it,
and hid His face from me.
I was left in great sorrow,
having a sense that others were feeding on the bread of life in our meetings,
and drawing the water of life, but my soul went without, having great bars over it,
sealing it down (so to speak) under darkness.
I beheld the displeasure of the Lord, and was bowed down in great anguish.
My soul cried out to the Lord to try me again with the breaking in of His power,
and to give me a clear knowledge of His requirings, and I would obey Him.
Then the Lord God of life again heard my cry, and opened my heart that was fast shut.
And when I began to feel the power of God stir in my inward man,
I was glad on the one hand,
but very sorrowful on the other--fearing lest I should be rebellious again.

Indeed, it was so hard for me to open my mouth in those meetings of Bristol,
that had not the Lord caused His power to be manifest
in my heart like new wine in a vessel that needed vent,
and so broke through forcibly many times, I might have perished.
But the Lord had regard to my state,
and also knew the people`'s state among whom I was gathered.
And when, by the great love and power of my God, I had at last broken through,
then the enemy`'s snares were manifest, for which my soul praised the Lord God of my life.
Truly I have been, and still am,
often broken in the sense of His goodness to me when but a child, no, but a worm.
And at this time, in a true sense and fresh remembrance of Your love,
I do bless and magnify and extol Your name, O Lord.
Indeed, You are God, and do good, and are worthy of all fear, obedience, reverence,
and honor, forever and ever.

After I had gotten dominion in measure (through the goodness, love,
and power of God) over that which did hinder me, I faithfully gave up liberty, estate,
relations, and all to my God,
and was drawn forth into the assemblies of the Lord`'s people in the city of Bristol,
and the places adjacent.
As I gave up in obedience, I found my way made easier,
and I saw the enemy (who strove to hinder me) more and more conquered.
In the year 1670, I received this commission from God:
"`Run through the nation and visit My breathing, bruised seed,
which I begat among My people in the day of their first tender visitation.
Proclaim My acceptable year, and the day of perfect deliverance to My breathing,
tender seed,
and also the day of vengeance to come upon all
who have bruised it--either among My people,
or in the world.`"
Then I cried unto the Lord, "`How shall I visit Your people in these times,
when the rod of the wicked is upon their backs, and when men, in almost every place,
are endeavoring through violence to scatter the assemblies of
Your people? How shall I meet with them?`" And the Lord said,
"`Go, I will prosper your way;
and this present exercise which is over My people shall be as a morning cloud,
and I will be to them as the tender dew throughout the land.`"
So I bowed before the Lord, and traveled in obedience to His command;
and from the latter end of the tenth month, 1670, to the 20th of the twelfth month, 1672,
I was at about four hundred meetings.^
footnote:[During this long journey in the service of the Gospel,
Charles Marshall visited most parts of England, and was several times in London.
Once, during a brief stay at his home,
he became so ill that nearly all despaired of his life.
On another occasion he met with a close trial in the death of his child.]

In my travels many were convinced, and the mouths of opposers were stopped,
and the Spirit of God fell upon several who now have a testimony to bear for His name.
I was many times brought very low in my body, even to the brink of the grave.
Yet God Almighty, in lovingkindness, raised me up again in a marvelous manner,
particularly on two occasions.
Great were the trials, sorrows, difficulties, and jeopardies,
both inwardly and outwardly, that I went through, which God Almighty alone knows.
And great were His deliverances in many ways.
On one occasion, when in Lancashire near Margaret Fox`'s, I was wonderfully preserved,
together with four others.
We had come down to the sea shore in order to cross the sands,
and two persons who lived on the other side informed us that we might go over safely,
and nothing appeared to the contrary.
But when I attempted to go, I was stopped in my mind,
and after waiting a while upon the Lord, I was clearly forbidden to go.
It was shown me, that if any attempted to go at that time, they would certainly perish.
This caused me to hinder passengers from going,
and in about an hour`'s time the sea overflowed, so that if we had gone,
in all likelihood we would have all perished.
When some who were there saw this, they were greatly tendered,
and magnified the name of the Lord.

In visiting the city of London, I left a short paper, a copy of which here follows:

[quote]
____
A warning to all people who have lent their ear to the declaration of the Truth,
but have not received it in the love of it.
A warning to those who are convinced of the Truth,
but who have not subjected themselves to it in the pure living obedience.
A warning to all that have begun in the Spirit, and set their faces Zionward,
that they neither return back into Egypt (spiritually so called),
nor sit down along the way.

The dreadful Day of God`'s vengeance is proclaimed,
in which all professors of Christianity and their professions shall be tried.
The floor will be thoroughly purged, the wheat fanned, the gold tried,
and the Day of God will come upon all images and likenesses.
Indeed, there will be a treading down of all that has risen up without the ancient,
eternal power.
There will be a day of calamity, misery, amazement, and distress,
upon the inhabitants of the city of London, and of sorrow upon the nation of England;
and after this a day of gathering throughout the nations of the dispersed of Israel,
and the scattered of Jacob.
____

In the name and authority of God Almighty,
I also cleared my conscience of the city of Bristol,
and did not keep back the counsel of the Lord from them.
But in the power and demonstration of His Spirit, and in all plainness,
I declared the Truth as it is in Jesus,
manifesting the many snares of the enemy that attend Friends of that city.
I am clear of the blood of the inhabitants of that city,
and of all professing Truth therein;
and am assured that a day of deep trial will come upon many of its inhabitants.
And as was my testimony to the city of London, so it was to the city of Bristol.

In my travels through the land, there were many attempts made for my imprisonment;
but the Lord was with me, and His word was as a fire in my bones,
"`to run through the land.`"
Truly the Lord helped me in spiritual battle against the enemy of the souls of men.
At that time, laws were made against all dissenters,^
footnote:[Dissenters were those who would not conform to the doctrines, beliefs,
or practices of the Church of England.]
and magistrates were empowered to fine the owner of any
house where a meeting was held twenty pounds,
along with twenty pounds for the preacher, and five shillings for each hearer.
And the one who informed the magistracy of any such
meeting was to receive a third part of every fine.
But though this was a time of sore persecution throughout the nation,
in my passage through cities, towns, and all the counties in England,
no man was permitted to lay hands on me, or stop my way; neither did any man,
that I know of, lose five pounds on my account, in all the nation.
I leave this to posterity, not out of any glory to self,
but to magnify and exalt the holy power of the Lord,
and that many travelers yet to be raised up may be refreshed,
and trust in the Lord Jehovah, in whom is everlasting strength.
Though He calls us to hard things, yet He is not a hard Master,
for He gives power to all that believe and trust in Him,
whose right arm of salvation has done glorious things in our day.
Unto Him be given everlasting, ever-living praises, honor, holy thanksgiving and renown,
forever and ever.

After this, I did not travel so constantly,
nor keep an account of many remarkable things
and deliverances that I met with in my travels.
But this I can say in truth,
and in the presence of my God who opened the door of people`'s hearts so effectually,
that I believe thousands received the Word of life,
and many were added to the church in diverse places.
Some meetings were settled where there was never a Friend before.
In one place, a whole meeting was convinced at one time,
and I never heard that any of them turned back, but all remained faithful unto the Lord.
The tenderness I have seen in many places through the land,
and the watering showers of life that descended upon the Lord`'s plantation,
are beyond expression.
Many that had apostatized and backslidden were effectually reached and brought back again.
And so I may truly say that the Lord was with me, and made way for me,
according to His word to me before I went forth.

I continued laboring until John Story and John Wilkinson, with their adherents,
opposed the order and discipline that was then set up in the churches of Christ.
This opposition was carried out under the deceptive
pretense of standing against imposition;
but it took its true origin from a desire for undue liberty in the flesh,
and from a fearful,
slothful spirit that turned away from the power of the Lord
and the daily dependence on its fresh arising and quickening.
These men sought to retain the ministry of the
doctrinal part of Truth in a dry and dead spirit,
while endeavoring to lay waste our monthly, quarterly, yearly, and women`'s meetings,
calling them "`forms`" and "`idols,`" when indeed it was the
same divine power and wisdom which gathered us to be a people,
that caused the setting up and settling of good order and discipline amongst us.

Great was the travel and work of our ancient and honorable Friend, George Fox,
in this weighty concern, in the first breaking forth of Truth in this age.
Several other brethren were also deeply concerned in
settling meetings in the said good order,
and we found the Lord with us in our work and service.
The power of the Lord had worked mightily to settle us in good order
that we might appear to the world to be guided by His wisdom,
being found in a form of godliness that arose from His power inwardly in the soul.

But the enemy, who desired us to be people in confusion, and a Babel instead of a Zion,
wrought in the earthly, sensual wisdom of some loose-spirited men,
who had lost their sense of the leadings of the Almighty.
These were led into a false imagination that we were
going from the inward guidance of God`'s Spirit,
to set up forms like other professions, thereby leaving the light of Christ Jesus,
which was to be every man`'s guide in faith and practice.
Hereupon they endeavored, with all their strength,
to break down and lay waste the meetings before-mentioned,
claiming that "`an imposition on conscience,`" was the cause of their separation,
when in truth their opposition arose from the power of darkness working in them,
whereby they lost their light and led many into their errors.

This spirit brought great affliction and travail upon
some in the beginning of its workings in Westmoreland,
and in Bristol, Wiltshire, Gloucestershire, and some other places.
Great were the disorders it made in Bristol and Wiltshire, because of which,
the Lord concerned me (along with other faithful
brethren) to make war against it in His name and power.
So in great travail, tears, and distress of spirit, for several years together,
we ran between the living and the dead in those counties.
I can say in truth that the Lord God guided me to
travel in His name and dread throughout the land,
and was with me in this day of deep exercise.
Indeed I have cause (with great bowing of spirit) to magnify His glorious name,
who preserved me faithful over all discouragement.
My bow He made strong, and my quiver He daily replenished with arrows,
and I labored as one eating the bread of adversity and drinking the water of affliction,
sparing neither strength nor substance.

I very well remember the day that I received instruction of
the Lord in a vision concerning that people,
in which their work, end, and downfall, was shown to me.
So it became the great concern of my soul to invite faithful Friends
of Wiltshire to have a meeting on purpose to wait upon the Lord,
in a deep exercise of soul,
and to cry to Him to appear for His name`'s sake and His people.
Friends readily answered my desire, and we agreed upon such a meeting.
When we were waiting upon the Lord,
this was the cry of my soul amongst Friends and brethren: "`O Lord,
what will You do for Your great name that is dishonored? What will You do for Your
heritage? For the enemy and destroyer desires now to scatter and devour Your lambs,
and trample down Your vineyard!`"
Thus we cried, with bowed hearts before the Lord, who heard from heaven,
His holy habitation, and His power broke forth in a wonderful way,
tendering His people before Him.
Indeed, His presence and heavenly wisdom comforted and confirmed His servants,
and Friends were opened to speak well of the name of the Lord,
and the greatness of His power and appearance.

It was afterwards concluded that this meeting should continue,
which was the case for many years, and in it our wrestling prevailed with the Lord.
Truly He attended us with His heavenly power and presence,
and from that time onward we saw a blasting of
that dividing spirit in all its undertakings,
and a mighty confirming of the Lord`'s heritage and people.

The same power of God wrought a great travail in the city of Bristol,
where the Lord many times appeared and disappointed the
design of those preachers of separation.
David`'s sling and stone smote their Goliath that rose up against the armies of Israel,
and the glory of the Lord shone over all.
I cannot forget the many days, nights,
and years of sorrow I went through in that city and nearby counties,
where I labored in the power of the Most High for the settling
of the churches of Christ in peace and good order.

After this time the enemy filled the heart of the priest of the parish where I dwelt,
and he labored many months to get me into prison and take away my goods.^
footnote:[For conscience sake,
early Quakers would not pay obligatory tithes to the Church of England,
and often suffered long imprisonments and loss of property as a result.]
He spared no cost until he got me into Fleet Prison in London,
whereby I came to be separated from my dear wife and children.
Here I was confined both before and during the time of the Great Frost,^
footnote:[The Great Frost of 1683/84 is one of the four
or five coldest winters on record in the British Isles.
The Thames River in London was completely frozen for about two months,
and the ice was reported to be some eleven inches thick.
The ground was frozen to a depth of 27 inches in London,
and more than four feet in Somerset.]
and after about a year`'s time, my family also removed to London.
In this imprisonment I suffered much in body, spirit, and substance,
all of which is known to the Lord who was with me.

After the space of about two years, the priest came to the prison,
caused the doors to be opened, and brought me out; and sometime after he died.
I then settled with my family near London,
and for many years labored in the Gospel in that city.
I was greatly concerned for the sick,
and in several other services for God`'s church and people,
and was frequently engaged with some in the government
on behalf of the Lord`'s suffering people,
and the good of my native country.

For the last three years,
I have several times visited the city of Bristol and adjacent counties,
and God Almighty has wrought in me a great travail in those visits,
and afforded me strength to follow through.
Indeed, His glory did shine over all, His river ran, His latter rain descended,
the springs of the deep broke open,
and the mysteries of the kingdom and travels of spiritual Israel were abundantly opened.
And now, my soul`'s cry to the God of my life is that we may all be a worthy people,
to the praise and renown of the name of the Lord!

[.asterism]
'''

__Charles Marshall was a medical doctor by profession,
but the greater part of his adult life was devoted to
the nurture and encouragement of the flock of Christ.
In both preaching and writing,
he was always careful to stay back to the leadings and movings of the Spirit,
convinced that man`'s natural wisdom and resources contribute
nothing to the cause of Christ or the increase of His kingdom.
Speaking of his ministry, William Penn (founder of Pennsylvania) once wrote:
"`He was not one who affected words or elegancy of speech,
or leaned upon memory or former revelations;
but one who waited for the feeling of God`'s living and
heavenly power to carry him forth in his ministerial exercises,
whereby, as a right gospel minister,
he often refreshed the family and heritage of God.`"__

__Although he suffered much by the envious persecutors of his day,
he was said to be "`not moved by abuses or injuries,
imputing such things to ill-nature or ignorance.`"
Through many trials and imprisonments he continued faithful to the end,
turning many "`from darkness to light, and from the power of Satan to the power of God.`"
In a short testimony to his life, his wife Hannah wrote, "`As his last moments drew near,
he closed his eyes with his own hand, and with cheerfulness and composure,
as one that had the sting of death taken away, resigned his soul to God,
the 15th of the ninth month, 1698, in the sixty-second year of his age.`"__
