== Chapter 11

[.chapter-synopsis]
* Samuel Baker Pumphrey
* Lindley Murray
* Elizabeth Wheeler
* James Brandwood
* Ann Crowley

SAMUEL BAKER PUMPHREY, a young man who died before he was twenty-five years of age,
was the eldest son of Stanley and Ann^
footnote:[See part X. of this work.]
Pumphrey of Worcester, and was born there, the 14th of the Fourth month, 1801.
He was from his infancy much afflicted, and of a delicate constitution,
little hopes being entertained by his parents that he would survive the age of childhood.
As he attained the state of youth, his frame, though still feeble,
became more invigorated,
and he was placed for several years at the boarding-school of Joel Lean, near Bristol.
His becoming behaviour and application to his studies endeared him to his master,
and gave rise to a mutual esteem and friendship, which terminated only with his life.

At the age of sixteen, Samuel was introduced into his father`'s business,
in attending to which he was assiduous; and he was a good example,
both at that period of his life, and afterwards,
when he became a principal in the concern.
He was a youth of promising talent; possessing also much genuine benevolence,
and feeling for the sufferings of others,
and a mind refined by virtuous and pious contemplation.
He was fond of reading;
and the books which he selected were of a description calculated to improve the mind,
as he was always averse to works of a trifling, uninstructive character.
He took much pleasure in the company of young friends;
and often availed himself of a facility which he possessed,
of directing the conversation to some useful object.
And whilst the youth of the poorer classes of society obtained his marked attention,
it was evinced in a manner free from all invidious distinction.

Though removed from this transitory scene in the prime of his days,
his life was not a useless one.
From his early youth, he was a zealous advocate of the peaceable doctrines of the Gospel,
and wrote several essays in defence of these Christian views,
which were printed anonymously.
In one of these essays, written in the year 1820,
with a view to its publication in a periodical work,
there was a uniform deviation from that plainness of speech which Friends,
as a religious Society, believe to be in accordance with the simplicity of the Gospel.
At a subsequent period, this circumstance became a source of regret to the writer,
who resolved never again to adopt a similar procedure.
He kept to this resolution, being convinced, that however desirable the end in view,
this was not a sufficient warrant for him to deviate from those testimonies,
which though by some accounted trivial, were to him important,
and felt to be a religious duty to uphold.
He took an active part in promoting the scriptural
education of the poor in his native city;
and devoted much of the leisure of the latter years of his life,
in support of the mitigation and final extinction of slavery.

He was a diffident young man, of little account in his own estimation,
gentle in his manners, and peculiarly careful to avoid everything like tale-bearing,
or detracting from the character of others:
at the same time he narrowly scrutinized his own conduct,
and would often imagine there was an unbecoming quickness in his expressions,
which was not obvious to those to whom they were addressed.
These virtues were the result of an early,
persevering endeavour to bear the cross of Christ, in whom, as his Lord and Saviour,
he sincerely believed.
He was diligent in reading the Holy Scriptures, and a great lover of retirement,
to which he regularly devoted a portion of his time, morning and evening.
For the last four years of his life,
he was in the habit of writing memorandums on his religious progress,
and of faithfully recording those errors for which he felt condemned.
In thus noticing his own experience,
he often laments the want of greater watchfulness in religious meetings; whilst,
at other times,
his soul was refreshed with that sensible and immediate influence of the love of God,
which contributed to his growth in grace,
and in the saving knowledge of our Lord Jesus Christ.

As this volume does not exhibit much of the conflicts of the young,
described in their own language,
a somewhat copious selection from the diary of Samuel B. Pumphrey is inserted,
in the hope that it may quicken those at the same critical period of life,
to examine and to know for themselves, whether Jesus Christ is in them.

1822.--First month, 5.
"`Oh! that Jerusalem were to me more a shelter from the
storm! but I am not sufficiently humble to dwell there.
Death often, and almost always, appears to me a king of terrors.
I trust it may be otherwise at the awful time of dissolution.`"

Tenth month, 11. "`I could desire,
that my deeds might be more brought to that holy light of the Lord,
which would reprove me for my vain pride and arrogance.`"

Tenth month, 23. "`These last few days I have felt uncomfortable,
for having been foolishly gay one evening.
It is, in some degree, a comfort to feel a swift witness:
may I desire to be more circumspect, and ever willing to crave that the rod,
as well as the staff, may comfort me.`"

Eleventh month, 14. "`This was a day which I trust I shall long remember.
It began good; and it was the language of my heart in the morning, '`Truly,
God is good to Israel.`' But in the afternoon I was too light and airy; and the thought,
that it was observed by one whom I truly esteem, vexed me: this is pride,
not contrition.`"

Twelfth month, 19. "`I have now continued, with various intermissions,
my practice of retiring at the close of the day; +++[+++for twelve months;]
and now that another year has almost closed upon me, let me inquire how it is with me.
Art thou in health?
Art thou strong in Him who goeth before thee?
Dost thou still retain thy integrity, in thy small measure?
Ah! that I could answer these questions to satisfaction.`"

1823.--Second month, 5. "`The beginning of every day,
is the commencement of a new day in the spiritual state:
new trials and new temptations may assail us, and a progress must be made.
May I be more desirous, the longer I live,
to yield obedience to that which will help me to pursue my course.`"

Eighth month, 28. "`What with the consideration of outward trials, and inward besetments,
I fear I have murmured at my state.
Let me remember, I deserve nothing; it is of mercy I have what I have.
'`If I were but as thankful for favours, as I am cast down with my trials,
what a harvest of praise would He receive, in whose hands my breath is.`'`"

Eleventh month, 10. "`One instance of petulancy has occurred today;
and I have also spoken improperly of a person, behind his back.
These are faults which I desire to be preserved from.`"

1824.--Seventh month, 1st. "`I desire to remember, more and more,
that if I am anything--if I have at all entered into the Christian path,
it is through the mercy of God in Christ Jesus;
and that to me belongs nothing but blushing and confusion of face.`"

Eighth month, 18. "`If I could but confine my attention to its proper object,
during times of religious retirement,
I might perhaps record this as a day better spent than is now the case.
My mind has, I trust, nevertheless,
been profitably led to consider the abundant mercy of the Almighty,
in snatching me as a brand from the burning; and, at times,
I have been enabled to acknowledge that I am not my own, I am bought with a price;
and therefore that my life should be more at the disposal of Him, through whose mercy,
whilst yet in the midst of iniquity, I was suddenly stopped,
and my life redeemed from destruction.`"

Ninth Month, 9. Festiniag, North Wales.
"`Much terrified by a storm of thunder and lightning,
which I experienced among the mountains yesterday;
but today have been favoured to feel more composed than I expected.
I wish that I may more and more remember, that the Almighty is my perpetual guard,
and that

`'Tis of his mercy I can sleep

One single night without alarm;

and therefore that gratitude ought to be as much the feeling of my heart,
for my continual favours, as for those which may appear more special.
But oh!
I am not thankful enough for any.`"

Ninth month, 15. "`Returned from my journey into North Wales,
during which I have had frequent cause to acknowledge,
that I have been as it were crowned with lovingkindness and tender mercies.
I have frequently, during the course of this journey, been as it were devoid of feeling,
amidst scenes which I should have supposed would have been
most calculated to arouse and invigorate the mind.

'`Give what thou wilt, without Thee we are poor;

And with Thee rich, take what thou wilt away.`'

Though this want of feeling was trying, yet I have been comforted,
in hoping that the Almighty has been pleased to stain
even the beauties of his own works in my eyes,
that nothing short of love to Him may be my desire,
and that I may prefer Jerusalem above my chief joy.`"

Ninth month, 16. "`Desirous, on entering the meetinghouse,
that the favours I am continually receiving, and some of which I deem special,
might make me more humble:--felt afterwards deserted of everything good;
yet I hope the meeting was not wholly unprofitable.`"

Ninth month, 19. "`Favoured in the morning, in some degree,
to feel abstracted from earthly things: in the afternoon strove, but not sufficiently,
to prevail.
Felt unwilling to retire to make this memorandum, which, after my numerous favours,
is ingratitude.`"

Ninth month, 25.
"`I believe I did not bear a faithful testimony against profane language this morning;
though I trust it is my desire to be more willing to confess the Lord before men.`"

Tenth month, 7. "`Got from bad to worse at meeting, until I lost almost all sense of good.
I should rejoice, could I but conquer this wandering of the imagination,
during seasons of retirement.`"

1825.--First month, 20. "`Oh! that I were more deeply humbled,
under a sense of my unworthiness!
Surely the valley is sweet to dwell in, for there the dew remains long.
'`Blessed are they that walk in the valley, for how safely do they walk.`'`"

Fourth month, 19. "`Rebellious, though in a very trifling matter,
which has beclouded this evening.
The sin is rebellion,
and it is of little consequence in what it is in despising
the gentle monitions that the crime consists.`"

Eighth month, 25. On parting from some beloved friends travelling on religious service,
to whom he felt much united, after some other remarks, he adds,
"`Whether my course here is shortly to terminate or not, I know not; but at this parting,
as well as at Ackworth, at the general meeting,
the last interview of the apostles with the elders of Ephesus^
footnote:[See Acts, xx, 25.]
has been brought to my recollection.
I desire that, however it may be, I may profit by the remembrance,
and more and more strive to experience the language of the apostle, '`With me,
to live is Christ, and to die is gain.`' I am bound to acknowledge,
that the most trying dispensations have been administered in mercy;
and therefore I believe, that if preserved in faithfulness, even death will,
through adorable mercy, be my gain.
Oh! may deep humility and resignation be my portion!
I have not chosen the Lord; but I humbly trust He has chosen me.
Wonderful condescension!`"

1825.--Tenth month, 21. "`My mind is too much occupied with my future life.
Oh! that I did but feel more the awful importance of having my loins girded,
and my lamp burning.
My hope and trust is in that Power which brought me up out of a horrible pit;
which has supported me in many humiliating dispensations; and will be with me,
if I am preserved faithful, even in the valley of the shadow of death.`"

Eleventh month, 1st. "`Too much occupied with future plans, so that the present,
which abounds with cause for humble gratitude, has been overlooked.
How desirable is that state,
where every thought is brought into captivity to the obedience of Christ.`"

On the 20th and 21st of the Twelfth month in the same year,
this pious young man attended the monthly and quarterly meetings at Worcester,
apparently in usual health.
The following day he complained of being unwell, and afterwards had an attack of fever,
succeeded by inflammation of the heart and lungs.
During his illness he expressed but little on religious subjects;
but he was preserved in remarkable quietness and mental composure,
a sweet feeling of peace overshadowing him.
He seemed to have nothing to do but to die; for he had been seriously engaged,
in time of health, to seek preparation for death.
On Seventh day, the 21st of the First month, 1826, he became suddenly worse:
he was preserved sensible to the last; and very early on the following morning,
after some close and painful conflicts of nature, he breathed quietly for a few seconds;
and his peaceful spirit was released from the further trials of life, and permitted,
we cannot doubt, to enter into the joy of his Lord.

LINDLEY MURRAY was a native of Pennsylvania,
and his parents were respected members of our religious Society.
His father designed him for a merchant, and gave him a suitable education;
but the son having entertained views of literary improvement,
superior to what is generally afforded by mercantile engagements,
gave a decided preference to the law; and having pursued his studies for four years,
with an eminent solicitor, he commenced practice in New York,
where his knowledge and talents soon developed themselves,
and appeared likely to gain for him considerable eminence.
But it pleased Divine Providence,
that the course of his ardent pursuits should be arrested by sickness;
and that a succession of circumstances,
which might then appear opposed to his future usefulness and comfort,
should contribute to direct his life to objects of a higher and far more important nature.

During his youth,
the natural vivacity of his mind led him into some of the gaieties
which are too often indulged in at that period of life;
but there is good reason to believe,
that he was early made sensible of the operation of Divine grace,
and that his morals and principles were preserved from contamination.
About the year 1784, in the thirty-eighth year of his age,
his constitution being very much enfeebled by illness,
his physicians advised the trial of a milder climate,
as the most likely means to reestablish his health.
He had, some years before, been in this country,
which induced him to give a decided preference to England.
At this time he had been married about seventeen years;
and the prospect of leaving their home and near connections was,
to him and his beloved wife, a severe trial.
They hoped, however, that with the blessing of Providence on the means thus used,
they might be favoured, at no distant period, to return to their native country.
They landed in England in the First month following,
and in the course of that year fixed their residence at Holdgate, near York,
at which place they continued to live until the time of Lindley Murray`'s decease.

For some years previously to his settling in this country,
through the goodness of the Lord to his soul,
he had been led to form a correct estimate of the value of all earthly pursuits;
to turn his back on the applause of the world;
and had become a consistent member of our religious Society; his mind, as it matured,
having made the principles of his education those of his judgment.
The humility of his deportment,
and the Christian spirit which breathed through his whole conduct,
greatly endeared him to the members of York monthly meeting,
and afforded him a scope for usefulness, of which he diligently availed himself,
for the benefit of all around him.
His health continued so delicate,
as to prevent his taking a very active part in our meetings for discipline,
or in the concerns of society at large; yet, contemplating his time, his talents,
and all that he possessed, but as a trust, of which he had to render an account,
he proved, by his future life, how much may be done for the good of others,
under circumstances apparently unfavourable, when the love of God, and of our fellow men,
are the governing principles of the heart.

Instead of yielding to depression, or adopting habits of personal indulgence,
in consequence of his bodily infirmities and confinement,
he diligently and successfully employed himself as an editor and author,
more especially for the benefit of the young.
In his publications, which were very extensively adopted,
he not only excluded whatever was calculated to impress
false principles and sentiments in morals and religion,
but he also aimed to make the course of instruction in the elements
of useful knowledge subservient to a far higher object,
that of imbuing the susceptible minds of youth with the
purest principles and precepts of Christian morality.
And there is good reason to believe that, under the Divine blessing,
these labours have had a decided and extensive influence
in the formation of virtuous and religious character.
His faculties, both natural and spiritual, brightened by use;
and his mental vigour and energy were strengthened by a judicious,
industrious occupation of his time.

Whilst health permitted him,
he was a diligent attender of our meetings for worship and discipline;
but during nearly the last twenty years of his life,
he was unable to unite with his friends in this public
demonstration of a dependence on Almighty God;
yet his zeal and devotion were not in any degree diminished.
His delight was still in the law of the Lord,
and in his law did he meditate day and night.
In life and conversation he was a preacher of righteousness,
illustrating in his deportment our Christian testimonies, with uniform consistency.
Nor, though necessarily more secluded from the society of his friends,
were his love and attachment to them abated.
He was ready, when of ability, to be consulted by them; and continued, to the last,
to take a lively interest in their welfare.
He rejoiced especially in any indication of their spiritual growth;
and was greatly concerned for the due exercise of our Christian discipline,
in the spirit of meekness and wisdom.

In his discharge of the duties of an elder,
his experience and judgment were highly valued.
He manifested a truly Christian feeling for the faithful,
humble labourers in the work of the ministry.
He loved the society of the honest,
simple-hearted travellers towards the heavenly kingdom;
and although their situation might be obscure, and their mental acquirements limited,
he valued their acquaintance, and treated them with Christian friendship and esteem.
His charities, both public and private, but particularly the latter, were extensive.
He was a firm friend to the education of the poorer classes of society; which he evinced,
not only by his liberality in assisting public institutions for this purpose,
but by his kind attention to the wants of those in his own neighbourhood,
at a period considerably prior to the general interest being excited to the subject.
He was very solicitous for the improvement of the condition
of the Indian aborigines of his native country,
and of the African race.

He took a lively interest in the proceedings of the Bible Society,
and in other efforts for the extension of the kingdom of Christ upon earth.
His exemplary moderation and simplicity,
in everything connected with his own expenditure, in his dress,
in the furniture of his house and table,
and the entire coincidence of his beloved and faithful partner in all his views,
enabled them to devote a considerable portion of their income,
and the profits which he derived from his numerous works,
to objects of piety and benevolence.
He was, at the same time, hospitable in his house; and liberal,
though discriminating and judicious in his charity.
His mind, indeed, was richly imbued with Christian love;
from whence flowed that patience, charity, and forgiving temper,
so uniformly evinced by him.

This dear Friend, notwithstanding his various privations from the state of his health,
was remarkable for cheerfulness; and he was frequently led to number his blessings,
and to acknowledge, that his afflictions,
and what appeared to be the most adverse circumstances of his life,
were designed to promote his final well-being.
He never repined at his long confinement; but was wont to observe,
how pleasant was his prison, if he might use the term.
In the latter years of his life, his bodily infirmities increased;
but his mind was preserved in intellectual and spiritual brightness,
and he continued particularly watchful,
that his weakness of body should not lead to any habits of indolence,
or unnecessary self-indulgence.

Whilst thus cultivating the Christian enjoyment of life, he was often led,
with great humility,
to contemplate the close of it as the commencement of a state of endless felicity.
He frequently expressed the sense of his own imperfections and unworthiness;
and uniformly evinced, that his hopes of salvation rested solely on the mercy of God,
through the atonement and mediation of Jesus Christ.
On the occasion of the fiftieth anniversary of his union with his beloved wife,
he thus expresses himself in writing: "`In the course of the long period of our union,
we have had our trials and afflictions;
we have seen a variety of trying events and situations;
but we have been favoured too with many great and distinguished blessings.
Even the afflictions, and what appeared to be adverse occurrences,
were designed for our final wellbeing.
I hope the gracious intention of these dispensations will be fully answered,
by our being safely landed,
through the atonement and intercession of our blessed Redeemer, on those happy shores,
where no clouds nor storms are ever known; and where,
after millions of ages of happiness shall have passed away,
we shall only seem to have begun our felicity--felicity that will never end.`"

The following memorandum, found in his writing-desk, but to which there is no date,
bears testimony to the habit of watchfulness and self-examination,
so necessary to the growth of the Christian.

"`Preserve me from all vain self-complacency, from seeking the applause of men,
and from all solicitude about what they may think or say of me.
May I be made truly humble, and of a meek and quiet spirit.
If I have done any good to my fellow creatures,
or in any degree promoted the will of my heavenly Father,
may I unfeignedly give Him all the glory; attributing nothing to myself,
and taking comfort only from the reflection,
that an employment in his service affords an evidence that
his mercy is towards me that I am not forsaken by Him,
and He is training me for an inhabitant of his blessed kingdom;
there to glorify and serve my God and Redeemer forever.`"

In this state of preparation and watchfulness, we have every reason to believe,
was this faithful servant found, when the messenger of death delivered his hasty summons,
and called him from the labours of the church militant on earth,
to the joys of the church triumphant in heaven.
On the evening of the 13th of the Second month, 1826,
he was suddenly seized with a severe attack of indisposition;
and on the morning of the 16th he breathed his last, in great peace and resignation,
in the eighty-first year of his age.

ELIZABETH WHEELER was the daughter of William and Elizabeth Tuke, of York,
and was born there, in the year 1760.
Being deprived of maternal care in her infancy,
she was much from home during her childhood; but on her father`'s second marriage,
was privileged with the care of a pious mother-in-law, to whom she became much attached,
and whom she often spoke of with great esteem and affection.
By submitting to the humbling visitations of the love of God to her youthful mind,
she was early introduced into that sphere of usefulness
and dedication which marked her future life.
When at home,
she rendered assistance in the school which was superintended by her parents;
and though her department in the family was principally of the domestic kind,
yet there is good ground to believe,
that her religious example had a beneficial influence.
She was also some time in Ireland, to assist her beloved sister, Sarah Grubb,
in an institution similar to that at York.

About the twenty-third year of her age, she first appeared as a minister.
The following extract from a memorandum, made some years subsequent to this period,
indicates a deep sense of the nature of this engagement:

"`Oh! the need for me singly to present my cause, my all,
before Him who can so carry forward the great work of purification in the heart,
as that a right preparation may be received for the accomplishment of every Divine purpose;
that I, the smallest vessel in the Lord`'s house, if one at all, may but be clean,
and preserved from drawing down his righteous displeasure, in the inquiry,
'`Who hath required this at thy hands.`' This is, at present,
the breathing of my prostrated soul; for in, I trust, a little renewed capacity,
through holy help, to labour after, and dwell near the root of life,
the consideration of the awful importance of a gospel-messenger,
in the most confined sphere, has humbled me as into the dust; believing,
that if those at this day are instrumental in the Lord`'s hand, in removing the rubbish,
or in any degree in raising the dead,
it must be by their dwelling beyond the craving of the multitude;
being so buried in baptism the full time, as to have no will of their own,
self being of no reputation,
but approving themselves mindful to accompany their Master through suffering,
as well as rejoicing.`"

In the year 1795, she married Joshua Wheeler, of Hitchin,^
footnote:[See part X. of this work.]
and became a valuable and useful member of that monthly meeting.
Both before and after her marriage she several times travelled on religious service.
Her communications as a minister were not very frequent in her own meeting;
but being reverently concerned to wait before the Lord for the influence of his Spirit,
her offerings were weighty and instructive,
and to the comfort and edification of her friends.
She exercised a tender care for the best welfare of her own family,
and in times of religious retirement with them,
often imparted suitable counsel and encouragement.
Her friends, and those around her, particularly when under affliction,
shared her sympathy and kind attention.
In 1803, she was deprived by death of her beloved husband;
but was supported by the Most High, under the pressure of this great affliction,
and enabled to fulfill the duties that devolved upon her,
in the education of her three daughters;
being concerned to unite firmness with affectionate kindness,
in her conduct as a parent.

The following sentiments, extracted from some written counsel to her children,
may be not unsuitably introduced into this memoir.

"`Whatever station in life may be in future allotted you, be sure,
set out and abide in simplicity.
Follow the example of none,
but as you are convinced they are willing to be governed
by the regulating principles of Truth.
In dress, as well as in the furniture of our houses, I have been long persuaded,
more injury is done to the tender plant in the youthful mind,
by giving way to extreme nicety as to the texture of apparel,
than by some transient turns of gaiety itself.
Therefore,
let your choice in the necessary conveniences of life ever be with an eye to usefulness,
simplicity, and neatness, which being to be had at a moderate expense,
whatever may be possessed, you will always be able to do more for others;
and the satisfaction this will ever procure, through the progressive stages of existence,
will far outbalance every trifling enjoyment.`"

Elizabeth Wheeler was accustomed to notice with much feeling,
the return of that period at which she was left a widow; and though, to the last,
it failed not to excite very tender sensibility,
the remembrance of it was ever mingled with Christian submission.
In allusion to this subject, she writes thus:

1818.--First month, 21.
"`The fifteenth anniversary of my widowhood reviewed with awfulness and fear,
lest the time past has not been sufficiently improved;
but commemorated with gratitude of heart, under a sense of many continued,
unmerited blessings, amid varied conflicting scenes, which,
if but permitted acceptably to purge away the remaining dross,
and purify for a better inheritance, may all be ascribed to mercy, unutterable mercy.
'`Bless the Lord, O my soul, and forget not all his benefits.`'`"

1819.--Twelfth month, 31. "`The increase of bodily indisposition, of late,
fails not to awaken anticipations of a better state, where encumbrances, sorrow,
and separation have no place; but where,
if in adorable mercy an admittance should ultimately be granted to an erring,
tribulated traveller,
all might and praise be forever ascribed to the Father and Fountain of purity.
At the close of this day,
the outgoings of the year with me were sealed with much suffering,
from violent spasmodic affection on my breast;
but after a little settlement the incoming of another
year was sweetly productive of humbling,
consoling reflections; when feelings of gratitude and praise were not wanting,
to the God and Father of my life,
whose blessings to this day have been unmeritedly showered down.`"

The state of the health of this dear Friend was such,
that for several years she was mostly confined to her own habitation during the winter.
This, in addition to much bodily suffering, was no small trial;
but she was enabled to endure it with exemplary patience,
and often to number her present blessings.
For several weeks previous to her death, she was more unwell than usual;
and frequently spoke of having discouraging and humbling
views of her own spiritual condition;
at other times she was favoured with the sensible enjoyment of the love of God;
and about three weeks before her close, one morning remarked,
that she had felt a near union of spirit with her departed husband,
and communion with the Source of all good;
and again alluded to it after the usual reading of the Scriptures in her family,
addressing her children in a very instructive manner.

After a severe attack of spasm, she was, for the last two days,
able to express very little in a connected and intelligible manner,
and during the most of that time,
appeared to suffer much from pain and extreme difficulty of breathing.
As her strength declined, respiration became more easy, and, for the last few hours,
conflict and suffering were succeeded by a peaceful calm, in which she quietly expired,
on the 17th of the Second month, 1826; and her surviving friends consolingly believe,
that her prepared spirit was permitted to join those of the just made perfect,
through Him, who "`by one offering hath perfected forever them that are sanctified.`"

JAMES BRANDWOOD was the eldest son of John Brandwood, of Entwistle,
in the parish of Bolton in Lancashire, yeoman, and was born in the Eleventh month, 1739.
Having left behind him an account in writing,
of his early experience in the work of religion, the following abstract is taken,
nearly in his own words, from this narrative.

"`It pleased the all-wise and gracious God, who gave me being, to follow me by his grace,
even from my youth, often bowing my mind in serious considerations,
that I was placed here as on his footstool, for a short space of time,
and must ere long remove, to appear before his judgment seat; also,
how short and transient present enjoyments are,
compared with the eternal nature of the life to come;
whereby my mind was led to conclude, this world is not my resting-place,
the life to come is my home, eternity is the chief end and design of my being.

Running in my own will and strength, from year to year, I heard sermons, read many books,
and talked with professors: some said one thing, and some another.
I then began to read the Scriptures more; but alas! they were to me, in many places,
as a sealed book.
I prayed often in secret places, and learned to sing,
thinking I was thereby preparing myself to join the heavenly host.
I talked with religious professors about doctrinal points,
and endeavoured to form as just notions and opinions about the coming, life, doctrines,
sufferings, and death of Christ, as I could; and this I called faith.
But this faith not proceeding from the quickening power of Divine grace,
but from the workings of the natural understanding, was a dead faith,
and could not be an evidence of things not seen,
nor work by love to the purifying of my heart,
so as to give victory over the various sinful lusts and vanities of this world; but,
on the contrary, I was abundantly overcome thereby, from day to day.

In this condition I travelled long,
and was sorely tossed between the secret reproofs of Divine grace in my conscience,
and the workings of the adversary.
About the twentieth year of my age, it pleased God, in unspeakable mercy,
further to enlighten my soul, through the Spirit of his Son,
as with the day-spring from on high;
whereby I was enabled to see more clearly my fallen and corrupt state,
and my sins were set in order before me, appearing exceedingly sinful,
and opposite to the holy will of God.
In this day, all my former building in religion was shaken to the very foundation.
In this situation I cried, "`Oh! what shall I do?
to whom shall I flee?
for in this sinful state I cannot dwell with Him that is holy.`"

The Scriptures now began to be more opened to my understanding; and though I was told,
that by a certain ceremony, which had been performed in my infancy,
'`I was made a member of Christ, a child of God,
and an inheritor of the kingdom of heaven;`' yet,
in the opening of the Scriptures to my understanding, I saw this could not be true;
for there I was informed, that the members of Christ were made such by other means,
even by his own baptism with the Spirit, as saith the apostle,
'`By one Spirit are we all baptized into one body;`' and that, '`if any man be in Christ,
he is a new creature.`' I also saw,
that the children of God were such as were begotten of Him through Christ,
the incorruptible Seed and Word of God, and born again unto newness of life,
bringing forth the fruits of the Spirit.
And that the kingdom of heaven and government of Christ are within,
by the influence of his Spirit, which as a pure principle in his children and people,
ruleth and leadeth them in his service.

I also saw,
that all my prayers and songs of praise had been a sacrifice of my own preparing,
and offered up in my own vain imagination, in a fallen and unconverted state;
and that it was only in and through the Spirit that God could be acceptably worshipped.
I also saw,
that all my former faith was no more than a bare assent of the
natural understanding to certain things whereof I had no evidence,
but what arose from the letter of Scripture, and other outward means; whereas,
in the opening of the Scriptures,
I saw that '`he that believeth hath the witness in himself,`' even the
Spirit of Him who is the Author and Object of true and living faith,
by which the quickened soul received an evidence of things not seen,
and an humble confidence in the saving power and redeeming love of God through Christ.
I also saw, that I had trusted too much in, and been carried about with,
the changeable doctrines of men,
and neglected the teachings of the grace and good Spirit of God in my soul, which,
as a swift witness against evil, had followed me with inward and secret reproof,
even from my infant years.

As I was brought more and more into stillness, and humbled under the Divine hand,
the Light of Christ arose, and more enlightened my mind;
whereby I saw into the purity of that faith which was once delivered to the saints,
and that holy religion, which, through the power of Divine Grace, was taught,
and which wrought in the primitive believers in Christ.
As these things opened in my view, a strong persuasion arose therefrom,
that it was not my duty to join any of the various
professions of religion with which I was acquainted;
and if, at any time, I tried to join with any of them,
it brought distress and trouble over my mind.
I then said in my heart,
'`Is there no people on earth preserved in the simplicity of the Truth,
with whom I can unite?`' Whereupon it came into my mind,
to go to a meeting of the people called Quakers;
a people of whose religious principles I had very little knowledge,
neither did I know more than one person of that persuasion.
Being encouraged by repeated drawings of mind towards them,
I went many miles to one of their meetings, accompanied by several others.

Being sat down in the meeting, which was but small,
my mind was seized with great surprise,
considering the vast difference between that multitude
of words and ceremonies to which I had been accustomed,
and the solemn silence in which we sat; and the breathing of my spirit was,
'`If this be right, confirm it to me this day.`' After some time,
my mind was brought into more stillness, desiring to unite in the solemn pause,
in which Divine goodness favoured my soul with a sense of his gracious presence,
and the promise of Christ opened to my mind with great sweetness,
though I had not understood it before,
'`Where two or three are gathered together in my name, there am I in the midst of them.`'

In this my soul rejoiced, and said, '`This is the truth,
this is what I have long been seeking for.`' Towards the latter part of the meeting
some testimonies were borne in great simplicity and plainness of speech,
but in the demonstration of the Spirit.
When I came amongst this people, I met with great opposition,
both from professors and profane; but knowing in whom I had believed,
and that his power is greater than he that is in the world, my faith was strengthened,
and my spirit frequently bowed before Him for help and support in that day, in which,
blessed be his name, I often found his secret hand underneath,
enabling me to stand in patience, and bear the cross.`"

James Brandwood appears to have been early made instrumental
to the convincing of several others,
of the truth of our religious principles,
and became a member of our Society in the year 1761;
and a meeting was shortly afterwards settled at Edgeworth, where he resided many years.
Soon after he was admitted amongst Friends, he spoke as a minister.
His offerings in that character were concise, forcible, and comprehensive;
and being concerned reverently to wait for the renewed influence of the Lord`'s power,
they were acceptable to his friends.
In consequence of his joining our Society, he was disinherited by his father,
who died when his son was forty-seven years of age.

After this, for many years he followed the profession of a land-surveyor and conveyancer:
he was never married, and lived most of his life in a retired part of the country.
He was a plain countryman, possessed of a good understanding;
but had not the advantage of a liberal education.
Few men appear to have been more free from the love of the interests of this world;
but Christian virtues and unobtrusive deportment,
combined with his cheerful and instructive conversation,
gained him the general esteem of all classes with whom he had intercourse.
He was scrupulously tender of the reputation of others,
so that his most intimate friends scarcely ever heard
him speak to the disadvantage of an absent person.

In the decline of life, however, through a combination of circumstances,
he became less diligent in the attendance of our religious meetings, and,
in the course of a few years, was discontinued as an acknowledged minister;
yet he was enabled to bear, with becoming patience, some deeply trying circumstances,
which during this period were permitted to attend him.
After some time, it pleased his gracious Lord to reanimate his love to his brethren,
and he was again acceptably engaged in the work of the ministry.
Early in the year 1824, he removed to West Houghton, near Wigan,
and some months afterwards was reinstated as an acknowledged minister.
Notwithstanding his advanced age, being in his eighty-fifth year,
he was diligent in attending meetings, clear and instructive in ministry,
much to the comfort and edification of his friends;
and his society was pleasant and instructive to them.

Towards the close of the following year, he became unwell, from which time to his death,
he was mostly confined to the house.
During his illness, he was preserved in patient resignation,
and he was enabled to communicate much valuable counsel.
At one time, he requested that passage of Scripture to be read,
in which the apostle says, "`We preach Christ crucified, unto the Jews a stumbling-block,
and unto the Greeks foolishness; but unto them who are called, both Jews and Greeks,
Christ, the power of God, and the wisdom of God;`" on which he exclaimed, "`Wonderful,
and very good;`" and after a few minutes silence, added,
"`This passage dwelt very much upon my mind whilst
in bed this morning;`" and he expressed his surprise,
that any seriously-thinking man, with the New Testament in his hand,
could be drawn into that dangerous disbelief and practice,
of reasoning away the propitiation and atonement of Christ,
who was crucified for our sins.

Adding, "`Such as are favoured with a sense of their own unworthiness,
and the exceeding sinfulness of sin before God, as they humbly seek unto Him for help,
come to know that he is also Christ, the wisdom of God, and the power of God.`"
Three days before his death, in the course of an interesting conversation,
he remarked to this effect: "`I have indeed lived a great while,
and have seen a good deal, both of good and evil; and having,
through Divine mercy and forgiveness, got through all, I feel my mind very comfortable,
and am thankful I am thus favoured.`"
The following day, on its being remarked by one who came to visit him,
that he had been a good liver, he replied, deeply affected:
"`It is not for any righteousness of my own that I shall gain acceptance:
but all my hope is in the mercy of God in Christ Jesus.`"
After a pause, though then very weak, he was enabled to speak for some time,
on the fall of man,
and his restoration through the atoning sacrifice of our Lord Jesus Christ; but which,
he added, it is not the duty of believers too nicely to define or explain;
but rather to wait for his spiritual appearance in their own hearts.
This was his last religious communication; and he peacefully departed this life,
on the 23rd of the Third month, 1826.

ANN CROWLEY was born at Shillingford in Oxfordshire, in the year 1765.
She received from her parents, William and Katherine Crowley, a guarded education.
In her very early years, she was visited with the gentle reproofs of instruction,
and felt the joy and peace attendant on yielding to them.
By unwatchfulness for a time, she lost, in degree, these softening impressions,
and indulged in some gratifications inconsistent with the simplicity of her profession;
yet, through the merciful care of the Shepherd of Israel,
these deviations were not of long continuance.
She remarks, in some memorandums upon her early religious experience,

"`About the sixteenth year of my age,
I was renewedly favoured with a powerful visitation of heavenly love and light, by which,
through the tender mercies of a compassionate Father,
I saw clearly there was no way to obtain present peace and everlasting happiness,
but by believing in, and yielding obedience unto the dictates of unerring Wisdom,
the Spirit of Truth revealed in the heart.
And as I gave up faithfully to follow the gradual unfoldings of the Lord`'s will,
I felt an increase of strength to bear the cross, and despise the shame.`"

Thus persevering in watchfulness, she experienced the blessing of preservation;
and being more and more instructed in the school of Christ,
she was in due time qualified to speak unto others, of what he had done for her soul.
After passing through many deep exercises and preparatory baptisms,
she first came forth as a minister in her twenty-sixth year.
Her feelings in a meeting for worship, in the immediate prospect of this requiring,
she thus describes:

"`My mind was deeply prostrated throughout the time of our sitting together,
and I felt the love of God abundantly shed abroad in my heart,
insomuch that I could experimentally adopt the language,
'`In the day of the Lord`'s power,
his people are a willing people.`' Yet so great was the fear that attended my mind,
lest I had not passed through the needful preparation to
qualify rightly to minister in the name of the Lord,
and that I should, by speaking, darken counsel by words without true knowledge,
that I suffered the meeting to break up.
And though this brought my poor mind under renewed conflict,
yet I could appeal to my merciful Master, who knew it was not wilful disobedience,
but a fear of running before my spiritual Guide,
that I did not feel much condemnation in trying the fleece both wet and dry.`"

The following day, at a friend`'s house, it appears that during a time of solemn silence,
to use her own expression,
"`The mighty power of God seemed evidently to overshadow them.`"
Under this precious feeling,
she was made sensible that that was the accepted time for the offering to be made;
and she adds, "`I ventured to stammer forth a few expressions,
which arose in that degree of life and power,
that no doubt remained but that it was really the operation of Divine love.
And oh! the blessed reward of peace that flowed into my humbled heart:
language is inadequate fully to describe this heavenly enjoyment.`"
It is scarcely probable,
that any one who had not passed through similar mental conflicts,
can fully understand the deep suffering, and the close searchings of heart,
which many experience who believe themselves called to the
ministry of the Gospel in our meetings for worship.

The high profession made by our Society,
of a dependence on the renewed discoveries of the Spirit of Christ,
for a right qualification thus to minister,
ought to lead those who are so engaged to act with reverent watchfulness,
and in the filial fear of God.
At the same time, we that are hearers should remember,
that we are never so likely to form a correct judgment
of the ministry that is offered to us,
or to be edified by what we hear, as when our minds are fixed on God,
in humble but fervent desire,
that He will graciously grant unto us also of his Holy Spirit, and enable us,
in simplicity and faith, to receive with gladness of heart,
that ministry which comes from Him through his faithful servants.

In the year 1796, soon after the decease of her surviving parent, Ann Crowley,
with three of her sisters, removed to Uxbridge,
where she resided the remainder of her life,
and where she laboured diligently amongst her friends, and with much acceptance to them,
in the service of the Gospel; her ministry being sound and weighty, and attended,
in an eminent degree, with the baptizing power of Truth.
It may be truly said of this dedicated servant of the Lord,
that it was her concern to adorn the doctrine which she was engaged to promulgate,
by a correspondent life and conversation.
She was a bright example of Christian love and meekness,
endearing herself to her friends by her kind and affable manners,
and her warm interest in their spiritual welfare; of great humility,
and endeavouring to occupy her time and faculties to the glory of God,
and the good of her fellow creatures.

Although of a very weakly frame, she travelled much as a minister; visiting,
at different periods, nearly all the meetings of Friends on this island,
and some of them repeatedly.
Her last religious engagement from home, was in the year 1819,
amongst Friends of her own quarterly meeting.
In the course of this visit, as had many times been the case before on similar occasions,
her ministry among her friends, in London and its neighbourhood,
was awakening and instructive, inviting them, with much affectionate earnestness,
to a close searching of heart before the Lord.
She afterwards remarked,
that the discharge of this little debt of love had yielded her much relief,
and was attended with a feeling of sweet peace.
Her health was at this time in a declining state, and her bodily sufferings often great.
This continued to be the case for several years,
and frequently prevented her attending our religious meetings;
but when able to meet with her friends,
she was often strengthened powerfully to minister amongst them.

In a retrospect of past years, and in contemplating the future,
this dear friend thus feelingly writes concerning herself.
"`The Lord my God hath hitherto sustained both body and mind, and,
in the midst of inexpressible suffering, and great poverty of spirit,
has graciously kept +++[+++me]
in a good degree of patience and resignation to his unerring will;
which I consider as unmerited, yea, boundless mercy, vouchsafed in time of great need.
May my tribulated soul receive a portion of strength to lean on the staff of faith,
and renewedly adore and praise his great and excellent name,
who is eternally worthy of all power and renown.
May it be ascribed unto Him, by my humble walking in his fear and counsel,
the few more fleeting days that in inscrutable wisdom may yet be lengthened out,
for purposes hid from the human mind, but doubtless in mercy,
that the work may be fully accomplished.

Oh! that the afflictions dispensed in pure, unerring wisdom,
to one of the weakest and most unworthy of the Lord`'s children,
may have the intended and blessed effect of preparing for a resting-place
amongst those who have passed through great tribulation,
and have known their robes washed and made white in the blood of the immaculate Lamb.
This is more the fervent desire of my heart, than for any earthly enjoyment;
for in deep abasement of mind I can truly say, I have not asked for riches, honour,
or length of days; but for an understanding heart,
to fulfill my religious and civil duties with holy acceptance.
I can very feelingly acknowledge myself an unprofitable servant,
not worthy to bear testimony to the never-failing
mercies and goodness of my Heavenly Father;
yet, for the encouragement of others, I feel bound, in a sense of heartfelt gratitude,
to acknowledge,
that there is a rich reward attached to an honest endeavour to
employ our time and talents in the service of our great Creator,
in that way and manner which are clearly manifested by the light
of the Holy Spirit in the secret of our hearts.`"

In the early part of the year 1825,
this deeply tried servant of Christ was laid on a bed of sickness,
with little expectation of being ever raised from it.
Her complaints assumed a serious character, and were attended with very acute pain.
When speaking of her sufferings, she remarked:
"`The dispensations of inscrutable wisdom are all in love and mercy,
and it is for us dependent beings to say in truth and sincerity,
'`Thy will be done.`'`" On one occasion,
when sending messages of love to some of her friends in the neighbourhood, she added,
"`and I feel it to flow towards friends of the quarterly meeting,
particularly to the dear young people, desiring they may embrace the Truth,
live under its influence, and reap the rich reward.
Oh! the inexpressible love of God which I now feel.
How do I desire, that thousands, and tens of thousands,
may come into the enjoyment of it,
by giving up their hearts to fear and love their Creator.`"

At another time, she said: "`It has been a comfortable day to me;
I feel love to flow towards all my dear friends everywhere, and to the whole human race.
I believe in the universality of the love of God; it is not to be limited:
those are in error that would limit it.
In every nation, tongue, and people,
those that fear God and work righteousness will be accepted of Him.`"
In the course of the summer,
she so far recovered as to be able to go a short distance from home, for a little change;
and attended two meetings, in which she was enabled to exert her weak bodily powers,
in advocating the cause most dear to her.
In the First month following she was again confined to her bed, and suffered much pain,
which she endured with great patience,
desiring that the Divine will might be fully accomplished; and often said,
that she felt poor and needy,
but her hope and trust in redeeming love and mercy were unshaken.

She continued to evince a lively interest in the concerns and best welfare of her friends;
and in times of religious retirement with them, she imparted Christian instruction,
when too weak to be raised in her bed.
On one occasion, after having been much exhausted, and when apparently sinking fast,
she said: "`My countenance appearing distressed, does not indicate distress of mind;
pain of body will distress the countenance.`"
And then added, "`Thy will be done; Thy blessed will be done!
O my soul, praise the Lord! bless and magnify his name!`"
On being asked if she was comfortable, she replied: "`All is comfort.`"
And at another time said, that her great affliction had been abundantly made up,
and that help had been extended in the needful time.
She also expressed a wish, that the language might be accepted,
"`Now let thy servant depart in peace, for mine eyes have seen thy salvation.`"
Some time after, she said: "`If it were the Lord`'s blessed will to release me,
it would be cause of thankfulness;`" and she expressed a humble hope,
that a place of rest was prepared for her.

During the last few weeks of her life, her breathing was so much affected,
as to make it difficult for her to say much, without producing spasms,
which were very distressing; and one day she said: "`Though I cannot express much,
I feel holy quiet.`"
The day preceding her release was one of extreme suffering; and in the evening,
a friend taking leave of her, she said: "`If I am gone in the morning,
there will be cause to rejoice.`"
The forepart of the night, she became easier; and on the following day,
the 10th of the Fourth month, 1826, she gradually sunk away in great quietness,
and her purified spirit, through redeeming mercy, was, we may consolingly believe,
received into its heavenly mansion, to joy unspeakable and full of glory.
