== Chapter 4

[.chapter-synopsis]
* Thomas Brown
* Abraham Farrington
* Hannah Carleton
* Agnes Penquite
* Elizabeth Daniel
* Elizabeth Estaugh
* Anna Webster
* Eleanor Shotwell
* Peter Fearon
* Ellis Hugh
* Rachel Pemberton

THOMAS BROWN, was born in Barking, in the county of Essex, Great Britain,
on the 1st of the Ninth month, 1696,
came whilst young with his parents into the province of Pennsylvania,
and lived some time in the city of Philadelphia,
from whence he removed with them to Plumstead, in Bucks county,
where he first appeared in the ministry; some years after which, he settled in that city.
His gift in the ministry was living, deep, and very edifying;
and in the exercise thereof, he was remarkable for an awful care,
not to appear without clear and renewed evidence
of the motion of divine life for that service.
Though not a man of literature, he was often led into sublime matter,
which was convincing and persuasive,
in setting forth the dignity and excellence of the Christian religion, yet,
was very attentive that those heights should not detain him beyond his proper gift,
but to close, in and with, the life,
which made his ministry always acceptable to the living and judicious.

Although he was not led to visit the churches in distant parts,
yet he was sometimes concerned to attend the neighbouring meetings,
of two of which he has preserved minutes,
which being a lively description of his concern for the promotion of the cause of truth,
it is thought well to subjoin in his own words.

"`1756, Eighth month, 9th. I went to Concord quarterly meeting,
but found no cause to espouse the cause of God in a public manner that day.
The next day I went to the youth`'s meeting at Kennet, which was to great satisfaction.
My soul was so bended towards the people, that I could scarcely leave them,
being engaged in a stream of the ministry,
to extol the divinity of that religion that is breathed from heaven,
and which arrays the soul of its possessor with degrees of the divinity of Christ,
and entitles them to an eternal inheritance.
It also introduces a language,
intelligible only to the converted souls who have access to a celestial fountain,
which is no less than a foretaste of eternal joy,
to support them in their journey towards the regions above,
where religion has room to breathe in its divine excellencies in the soul.
Here it is instructed in the melody of that harmonious song of the redeemed,
where the morning stars sing together, and the sons of God shout for joy.

1756, the 29th of the Eighth month, I visited Gwynedd meeting,
where in waiting in nothingness before God,
without seeking or striving to awake my Beloved before the time,
by degrees my soul became invested with that concern that the gospel introduces,
with an opening in these words,
'`I think it may conduce to my peace to stand up and engage in a cause dignified with
immortality and crowned with eternal life.`' The subject raised higher and brighter,
until my soul was transported on the mount of God, in degree, and beheld his glory;
where I was favoured to treat on the exalted station of the redeemed church,
which stands in the election of grace, where my soul rejoiced with transcendent joy,
and adored God.
Returned home in peace.`"

His conduct and conversation were innocent and edifying,
being much weaned from the world and the spirit of it.
He was careful not to engage in worldly concerns, so as to encumber his mind,
and draw it off from that religious contemplation in which was his chief delight.
This happy state of mind he maintained to the last,
as evidently appeared to those friends who were with him towards his conclusion;
to some of whom he expressed himself in the following manner, viz.:

"`I am fine and easy, and don`'t know but what I may recover.
If I should, I expect to see many a gloomy day, but, nevertheless,
I am willing to live longer, if I might be a means of exalting religion,
that the gift bestowed on me might shine brighter than it hath ever yet done,
or else I had abundantly better go now.
I think I have shone but glimmeringly to what I might have done,
had I been still more faithful;
though I cannot charge myself with a presumptuous temper or wilful disobedience.
But I can say,
it has often happened with me as with the poor man at the pool of Bethesda,
whilst I was making ready another has stepped in.
I am sensible that my gift has been different from some of my brethren:
I have not been led so much into little things, but I am far from judging them.

I have often to pass through the valley of the shadow of death,
and have experienced the possibility of a soul`'s subsisting
the full space of forty days without receiving anything,
only living by faith, and not by sight.
Provided they keep upon the foundation of convincement and conviction,
and not turn aside to take a prospect of the world,
and desire to draw their comfort from visibles;
they will be supported by an invisible yet invincible power;
for he will be sure to appear, and when he doth appear,
at times rends the veil from the top to the bottom, with an invitation,
as Samuel used to say (meaning Samuel Fothergill), '`Come up hither,
and behold the Bride,
the Lamb`'s wife.`' Then the soul will have to enjoy and see things beyond expressing;
my tongue can do little or nothing at setting it forth.
The soul will be filled with holy admiration, and say,
'`Who is she that looketh forth as the morning, fair as the moon, clear as the sun,
and terrible as an army with banners.`'

Although the soul has at times to behold the glory, splendour,
and magnitude of the true church or spouse of Christ,
yet those extraordinary sights are but seldom.
Though I have had, at times, to espouse the cause of God,
yet there are times that the soul is so veiled,
and surrounded with temptations and fiery trials, and all good out of sight,
that I have wondered that I was made choice of.
But I have experienced, that they that would reign with Christ must suffer with him.
I never expect to get beyond it, while I am clothed with this clog of mortality.
People may have a regular outside, and be diligent in attending meetings,
and yet know little or nothing of true religion; for formality and externals are nothing;
religion is an internal subject, subsisting between Christ and the soul.

I don`'t confine it to our name,
but amongst the different names there are those that my soul is nearly united to,
who are in a good degree, I do believe,
in possession of that religion which is revealed from heaven.
And I am in the faith, that there will be those raised up who will shine as bright stars,
and religion will grow and prosper,
and the holy flame rise to a greater height than it hath ever yet done.
I can say with the holy apostle, '`I have nothing to boast of,
save my infirmities,`' yet thus much I venture to say, that if I die now,
I die a lover of God and religion.`"

After expressing a compassionate sympathy with the poor afflicted churches up and down,
he concluded with this saying, "`Be of good cheer, little flock,
for greater is he that is in you, than he that is in the world.`"
In the sixty-first year of his age, he was seized with an apoplectic disorder,
which gradually increasing, deprived him of life, on the 21st of the Sixth month, 1757,
and he was interred in Philadelphia the next day.

ABRAHAM FARRINGTON, of Burlington, in New Jersey, was born in Bucks county, Pennsylvania,
of parents professing the truth as held by the people called Quakers.
About nine months after his birth his father dying,
and his mother some time after marrying from among friends, exposed him to a loose,
irregular, education.
About ten years of age he was put apprentice, where, through eleven years`' servitude,
he suffered great bodily hardship, and much greater danger as to the better part; yet,
says he, in a manuscript left for the use of his children, "`I took delight in my bible,
and believe the good hand was with me, who inclined my mind thereto.
Though I followed lying vanities, and so forsook my own mercies,
yet I could say my prayers every night, till I grew afraid to say them any more,
and seemed like one abandoned from good for several years.`"

Having served his time out,
he providentially became a resident in Benjamin Clark`'s family, at Stony-brook,
who were exemplary, and kind to him; "`I thought,`" says he,
"`they were the best people in the world, careful in their words,
yet cheerful and pleasant, so that I thought I must be a Quaker.`"
Edward Andrews, from Eggharbour, being at a quarterly meeting at Crosswicks, "`He came,
adds Abraham, with power to give me my awakening call.
I was much reached; but after the manner of the world, looking at the man,
gave him the praise; +++[+++thinking to myself]
he is a brave man, he preaches well, I wish I lived near him,
I would go to hear him every First-day; at the same time not minding what he directed to,
Christ in ourselves, the true teacher, who will not be removed till we remove from him.
In us is the place he has ordained to reveal himself.
I afterwards went more to Friends`' meetings than I had done before,
and read much in Friends`' books, but was yet in the dark.
The time of my deliverance was not come, the sins of the Amorites were not full.
I was under Moses in the wilderness, come out of Egypt, but Joshua`'s time was not come,
the Saviour, the warrior that brings through judgment,
and makes war with the old inhabitants;
yet I sometimes longed for something which I could not find, a lot in the good land.

I think this year, Thomas Wilson and James Dickenson, came into the country,
and some time afterwards to visit the meeting of friends`' at Crosswicks.
I happened to be at the meeting before they came in.
The sight of them struck me:
the heavenly frame of mind which their countenances manifested,
and the awe they seemed to sit under, brought a stillness over my mind,
and I was as ground prepared to receive the seed.
James stood up in the authority of the gospel,
and in it he was led to unravel me and all my works from top to bottom,
so that I looked on myself like a man dissected or pulled to pieces.
All my religion as well as all my sins,
were set forth in such a light that I thought myself undone.
After he sat down, Thomas stood up and brought me together again,
I mean what was to be raised, bone to his bone,
with the sinews and strength that would constitute a Christian.

I almost thought myself new born, the old man destroyed and the new man made up,
concluding I should never be bad again, that my sins were forgiven,
and I should have nothing to do but to do good.
I thought I had gotten my lot in the good land,
and might sit now under my own vine and fig-tree, and nothing more should make me afraid.
Poor creature!
I had only a sight; I did not yet think what powerful adversaries I had to war with.
This has been the miserable case of many: they have sat down under a convincement,
and in the form of religion, some depending on former experience or former openings,
some on their education,
some a bare belief and historical knowledge of the Scriptures and principles of truth.
Thus, though I received the truth, yet I was like the stony ground.
I received it with joy, but had not root in myself; my heart grew hard again;
for when tribulations, persecutions, temptations, and trials came upon me, I fell.

Oh! how I moped at times, and wandered about as a prisoner at large.
I would have run, but I could not: my offended judge, my accuser, was in me.
I could not fly from him; yet great goodness was near,
and his power kept me from gross evils in a great degree.
I kept pretty much to meetings, but there was such a mixture of undigested matter in me,
it was not to be soon separated.
Oh! the necessity there was, and still is,
of a continual watch against our souls`' enemies, both within and without.`"
Having passed through various probations,
he had considerable openings into the Divine sense of the Scriptures,
and also saw that the Lord had a work for him to do,
in preaching the gospel of the Lord Jesus Christ, to which he at length gave up,
and being faithful therein, was made helpful to many, being sound in testimony,
and at times very particularly led to explain passages in the Scriptures,
to the comfort and information of hearers.

He was an affectionate husband and parent,
diligent in attending meetings for worship and discipline,
and manifested therein a zealous concern for the promotion and honour of truth,
waiting for wisdom to see his duty, and strength to perform it.
He divers times travelled abroad on this continent in the service of truth,
and frequently to the neighbouring meetings, to satisfaction;
his outward circumstances being at times difficult,
gave him an opportunity to show an example of Christian resignation,
and to see its effects in many providential assistances.
In 1756 he laid before his friends a religious concern
to visit the churches in Great Britain,
which had been on his mind upwards of ten years, wherewith the meeting concurring,
he had their certificate, and embarking, after a favoured voyage of about four weeks,
landed at Dublin.
He visited the meetings of Friends in Ireland, and by the accounts from thence,
had very weighty and acceptable service there.

Having laboured faithfully in that nation to strengthen the brethren,
and assist in building up the waste places, he embarked for England,
visited the churches in some of the northern counties,
attended the yearly meeting at Penrith, and afterwards that in London:
his labour of love in the ministry, being to edification and comfort,
was truly acceptable.
After attending the yearly meetings at Colchester, Woodbridge, Norwich,
and the quarterly meeting of York,
he visited many meetings in the northern and midland counties,
from whence good accounts were received of his weighty and affecting labours.
He returned to London the latter end of the Twelfth month, 1757.
Having travelled with great diligence, and laboured fervently, his health was impaired;
nevertheless he attended meetings till his disorder increased
so as to render him incapable of further service.
While favoured with health, he had faithfully served his gracious Master,
and when visited by sickness, with a prospect of soon closing his earthly pilgrimage,
he was enabled to look forward with humble confidence
in the mercy of God through Christ Jesus.
He had spent but little time in London previous to his illness,
yet the sweetness of his spirit, and his labours in gospel love,
had greatly endeared him to many there.

His conversation was innocently cheerful, yet grave and instructive:
he was a man of a weighty spirit, a valiant in Israel;
a sharp reprover of libertine and loose professors;
but tender to the contrite and humble; and a lover of good order in the church.
He was strong in judgment, sound in doctrine, deep in Divine things; often explaining,
in a clear and lively manner, the hidden mysteries wrapped up in the sayings of Christ,
the prophets, and apostles; and it may truly be said,
he was well instructed in the kingdom, bringing forth, out of his treasure,
things new and old.
His ministry was in plainness of speech, and attended with Divine authority,
reaching the witness of God in man, and to the consolation of the mourners in Zion;
frequently pointing out, in a lively manner, the path of the exercised travellers,
and the steps of heavenly pilgrims;
by which he was made helpful to such as are seeking the true rest,
which the Lord hath prepared for his people.
It may truly be said, he was eminently gifted for the work of his day,
qualified to expose the mystery of iniquity,
and to point out wherein true godliness consisted.

His distemper increasing, he was confined to his bed, at the house of Thomas Jackson,
in Devonshire-square, where all necessary care was taken of him.
During his illness, he was very sweet and tender in his spirit, and remarkably patient.
He uttered many comfortable and heavenly expressions, and several times said,
"`He apprehended his time in this world would be
but short;`" and seemed fully resigned to quit mortality,
having an evidence, "`That he should be clothed upon with immortality,
and be united with the heavenly host.`"
He had frequently been heard to say, in time of health,
"`That he thought he should lay down his body in England,
and not see his friends in America more;`" to which he appeared freely given up,
and he often expressed his desire,
"`That he might be favoured with an easy passage,`" which was graciously granted.

He departed this life the 26th of the First month, 1758, like a lamb,
without either sigh or groan, as one falling into a sweet sleep;
aged about sixty-seven years; and on the 30th of the same,
his body was carried to Devonshire-house, where a large and solemn meeting was held,
which was owned by Him whose presence is the life of religious meetings;
and from thence his body was carried, by friends,
to their burying-ground in Bunhill-fields, a large concourse accompanying it;
and was there decently interred among the remains of primitive worthies,
and valiant soldiers in the Lamb`'s war, who loved not their lives unto death,
for the word of God and testimony of Jesus.
He was in the profession of the truth forty-four years, a minister thirty years.

HANNAH CARLETON, late wife of Thomas Carleton, of Kennet, in Chester county,
Pennsylvania, was born at Haverford, in the said county, about the Fifth month, 1689.
She was sensible of the Lord`'s visitation of love to her soul in her young years;
and as she gave heed thereto,
was preserved in a good degree from the vanities and evil conversation of the world.
As she grew in years she grew in the truth,
was a serviceable friend in the society and her neighbourhood, in many respects;
and was helpful in that weighty work of visiting friends`' families,
having at times to impart, not only in such opportunities,
but in our more public meetings,
of her experience of the work of truth in her young years,
and pressing on others the necessity of the same work in themselves.
Being taken with a bleeding at the nose,
she was so weakened by it that for some months before her decease,
she did not go from home nor much out of doors.
She apprehended her end was near, and when it was proposed to send to a doctor for help,
she said, "`It seems needless,
for I am in the hands of the great physician who knows what is best for me.`"

A neighbour signifying she hoped to see her better, she answered,
"`Better I shall be in a little time.`"
The friend replied, "`In a better state of health I mean;`" she answered,
"`I neither expect nor desire it,`" admiring the
kindness of the Almighty in favouring her so,
that she felt neither sickness nor pain.
Another time she said, "`As I have laboured for peace and love,
so now I see nothing but peace before me,`" with several other sentences
which manifested that the peace and quietness she was favoured with,
were graciously dispensed to her by the Father of mercies in her last moments.
She departed this life, the 6th of the Fifth month, 1758,
and was buried in friends`' burying-ground in Kennet, the 8th of the same month,
in the sixty-ninth year of her age.

AGNES PENQUITE, of Wrightstown, in Bucks county, Pennsylvania, departed this life,
the 20th day of the Eleventh month, 1758, being upwards of one hundred years old.
She brought a certificate with her from Europe, dated the 6th day of the Second month,
1686.
She was of an innocent, pious life and conversation,
and a good example in attending meetings both on First and week-days,
until a few years before her death.
She was a minister above seventy years; her testimony, though generally short,
was mostly to satisfaction and edification; and in her declining age,
when nature seemed almost spent, she appeared more divinely favoured than common,
to the admiration of some.
When she could no longer attend meetings, she would often, at meal times,
appear in prayer, with praises to the Lord,
to the comfort and satisfaction of those present; and frequently signified,
"`She had the evidence of divine peace.`"
Not long before her departure, she said, "`That her sweet Lord had not forsaken her,
but was still with her to comfort and refresh her in her old age.`"
Thus she was removed from time to eternity, like a shock of corn fully ripe.

ELIZABETH DANIEL, wife of James Daniel, of Salem, in New Jersey,
was born in the year 1709.
She was a woman endowed with a lively gift in the ministry,
and by yielding in obedience to the heavenly call,
and following the paths of true wisdom, it became as a crown and diadem on her head;
for the truth was her chief adorning, and by it she was advanced from a poor, low,
despised girl, to be as a mother in our Israel.
By this Divine wisdom she was enabled to stand in the midst
of the congregation with reputation and honour,
for the cause of our God, and to plead with gainsayers and the lukewarm,
to join in with the glorious truth that had made her free,
in the demonstration of the power of pure Gospel love; and in the stream thereof,
she was often led forth to comfort the mournful travellers in Zion,
and in the line of experience could tell what great
things the Lord had done for her soul,
through her obedience and trust in him.
To Him she freely attributed all she received, as from his bountiful hand,
and thereby gave the glory to God, and administered comfort to weary, travailing souls.
But being of a backward spirit, from a sense of her own weakness,
she was loath to give up to travel in truth`'s service,
which often brought her very low under such exercises.

She some times travelled in Pennsylvania and Maryland,
of which service her friends gave comfortable accounts;
and she was also useful in building up the church within
the limits of the monthly meeting to which she belonged.
She was very lively to the last,
and her testimonies were accompanied with power that
made them truly seasonable to the auditory,
the Divine presence being evidently with her;
under a sense whereof she was very much resigned,
and rather desirous to depart and be at rest with the Lord.
On being asked how she was, she answered with much calmness,
"`I am in great pain of body, but quite easy in mind,
free to depart and be released from my various exercises;
and feel as if my day`'s work was done,
and that I might lay down this tabernacle in peace.
But oh! the pain at times is so great, nature is ready to shrink,
and I am afraid I shall not be able to bear it with that patience I ought,
though I strive for it, for my mind is quite easy and resigned.`"
Her pain was great under the extremity of a sharp pleurisy; and after seven days,
this servant of the Lord quietly departed in peace, on the 30th of the Tenth month, 1760,
in the fifty-first year of her age, and the 26th of her public ministry.

ELIZABETH ESTAUGH was the daughter of John and Elizabeth Haddon, Friends of London,
and was born in the year 1682.
Her parents gave her a liberal education, and having an estate in lands in New Jersey,
they proposed coming over to settle, and in order thereto,
sent persons over to make suitable preparation for their reception.
But they being prevented from coming, this Friend, with her father`'s consent, came over,
and fixed her habitation at the place where he proposed to reside, if he had come;
she being then about twenty years of age, in a single state of life,
and exemplary therein.

In the year 1702, she was married to John Estaugh,
who settled with her where she then dwelt, the place being called Haddonfield,
in allusion to her maiden name.
There they lived together, nearly forty years, except,
her several times crossing the sea to Europe, to visit her aged parents,
and when he was called abroad on truth`'s service, to which she freely gave him up.
She was endowed with great natural abilities, which,
being sanctified by the spirit of Christ, were much improved,
whereby she became qualified to act in the affairs of the church,
and was a serviceable member,
having been clerk to the women`'s meeting nearly fifty years,
greatly to the satisfaction of Friends.
She was a sincere sympathizer with the afflicted, of a benevolent disposition,
and in distributing to the poor,
was desirous to do it in a way most profitable and durable to them, and, if possible,
not to let the "`right hand know what the left did.`"

Although in a state of affluence as to this world`'s wealth,
she was an example of plainness and moderation;
zealously concerned for maintaining good order in the church,
diligent in attending meetings at home, where her service seemed principally to be,
and from her awful sitting in them,
we have good cause to believe she was an humble waiter therein,
which administered edification to the solid beholder.
Her heart and house were open to her friends,
to entertain whom seemed one of her greatest pleasures.
She was prudently cheerful, and well knowing the value of friendship,
was careful not to wound it herself,
nor encourage persons in whispering and publishing the failings,
or supposed weaknesses of others.

Her last illness confined her about three months, being often in great bodily pain,
but favoured with much calmness of mind, and sweetness of spirit,
which rendered her confinement more easy to herself and those with her,
and affords matter of encouragement to survivors,
to press after the mark for the prize of the high calling of God in Christ Jesus.
She departed this life, the 30th of the Third month, 1762, as one falling asleep,
full of days, like a shock of corn fully ripe.
Her body was interred on the 1st of the Fourth month following,
in Friends`' burying-ground at Haddonfield, being accompanied by many friends and others,
where a solid meeting was held: aged about eighty-two years.

ANNA WEBSTER, an elder, wife of John Webster, of Plainfield, New Jersey,
departed this life, the 20th day of the Fifth month, 1762,
in the thirty-sixth year of her age.
She was favoured when young to have her mind turned to him
who is able to preserve all that put their trust in him;
and by her obedience to the manifestations of Divine light,
she was enabled to conduct herself in a steady and upright manner;
and in the time of her last sickness,
gave much useful and instructive advice to her husband, children and friends.
She divers times entreated her husband, "`To give up to the Lord`'s disposing,
and not to be over troubled about her;`" expressing her dependence on the Lord,
and resignation to his will; with desires, "`That the Lord would be with and comfort him,
and that he might seek for heavenly wisdom,
and thereby be directed how to walk before the Lord,
and bring up their children in his fear,
that they may have a portion in heaven;`" charging her children, "`To consider the poor,
and administer to their necessities.`"

At one time, speaking to her eldest son, she said: "`My dear child,
let it never be said of thee, '`The foxes have holes,
and the birds of the air have nests,
but the Son of Man hath not whereon to lay his head.`"`' She earnestly importuned Friends,
"`To keep, not only themselves but their offspring, to week-day meetings,
and teach them to wait on the Lord, that he might mercifully bless them.`"
She also recommended, "`Unity amongst Friends,`" expressing,
"`Her sorrow at the breach thereof,`" and urged closely,
"`The necessity of living in love;`" entreating Friends,
"`To notice her husband and children in their distress,
and watch over and advise her children, not sparing to tell them their faults.`"
She advised her children, "`In all their undertakings to seek the Lord for counsel,
especially in that of choosing companions;
and expressed her experience of the favours received thereby; saying,
"`She had often magnified that gracious hand which was with her when a poor orphan child;
and pressed them to serve the Lord in their youth,
which would draw Divine blessings on them; adding;
"`There are excellent accounts of God`'s love to such as
give up all in their youth:`" and charged them,
"`'`to avoid bad company, and keep to plainness;`" strongly advising,
"`against disobedience to parents.`"

At a time when several young people were present, one of whom was light and airy,
she testified against her vain practices in very moving expressions, and informed her,
"`That the enemy would incline the mind in meetings
to such vanities as were practised out of meetings.`"
She was often concerned in fervent prayer and supplication to the Almighty,
"`that she might have sure hope before her change, and bear patiently her distress;
and for the poor, afflicted seed, that the Lord`'s work might be carried on in the earth,
and that he would destroy all the inventions of the enemy,
which lead people to sin against him.`"
Many more deep and weighty expressions she uttered, which for brevity sake are omitted.
May the dying, penetrating language of one whose general conduct was virtuous,
have a proper impression on the minds of survivors,
and stir them up to prepare for their great and final change.

ELEANOR SHOTWELL, late wife of Jacob Shotwell, of Rahway, in New Jersey,
was a tender-hearted Friend, and encouraged such as sought the Lord.
She was an elder of sound judgment, concerned for the church`'s welfare,
and that Zion might be restored to her primitive beauty,
and was a pattern of plainness and self-denial.
In the Ninth month, 1762,
being on her journey to attend the yearly meeting in Philadelphia,
a friend mentioned the danger of going to said city,
on account of an infectious distemper then prevalent there, to which she replied:
"`She had no fear on that account,
and that it was no matter where we departed out of the world,
so that we were in our duty.`"
She accordingly went to the meeting, and attended the sittings of it,
until she was suddenly seized with a violent disorder,
attended with extreme pain for nearly three days,
which she bore with a calm and even mind.

To a friend, who visited her, she said: "`She was almost gone, and in great pain of body,
but exceeding peace of mind.`"
At another time she said: "`It was satisfactory that her peace was made with the Lord,
and that it would be terrible to have a wounded conscience
at such a time to struggle with.`"
Concerning her husband and children, whom she dearly loved, she said:
"`Though she was not likely to see them again, she was glad in the Lord,
that she had given up to attend the yearly meeting;`" expressing her desire,
"`That her offspring should be brought up in plainness,
and that Friends`' watchful care might be over them;
and that her husband might be preserved in self-denial,
and humble resignation to the Lord`'s will in all his trials.`"
She departed this life, on the 2nd day of the Tenth month, 1762,
in the forty-sixth year of her age, and was interred in Friends`' burying-ground,
at Philadelphia.

PETER FEARON was the son of John and Elizabeth Fearon of Great-Broughton, in Cumberland,
and born in or about the year 1683.
He came amongst Friends from convincement,
during his apprenticeship with his uncle Peter Fearon,
and appeared in a few words in meetings before he was twenty years of age.
In the latter end of 1703, with the concurrence of Friends, he left England,
and landed in Virginia, where he stayed about three months, then went to Burlington,
New Jersey, in the Second month, 1704, and from that time until his decease,
he was a useful member of that meeting.
Between the years 1704 and 1730, he travelled in the service of the gospel,
through most parts of America, where meetings were then settled,
and to some provinces several times;
and employed above two years in visiting Friends in England, Scotland, and Ireland;
returning with satisfactory certificates of the approbation
and unity of Friends with his religious labours.

After those travels, his worldly circumstances being attended with difficulties,
and his desires earnest that he might get through them with credit,
he went many voyages to sea as a factor, chiefly to Boston and the island of Barbados;
and through many difficulties, he was enabled to pay his debts, and to save sufficient,
with care and industry, to yield a comfortable subsistence in old age,
and to be helpful to some others.
In those undertakings he took certificates, and returned such as were very satisfactory,
both of his diligence in his outward business,
and of his care to edify the churches with the gift of gospel
ministry which had been committed to him.

Whilst in Barbados, in the beginning of 1746,
a concern came upon him to visit Friends in Tortola, which,
by their large and full certificate, appears to have been very seasonable;
and was the first visit after those worthy Friends, Thomas Chalkley, John Cadwalader,
and John Estaugh, had laid down their heads in peace among them.
They say, "`He came in a needful time, as a cloud full of rain upon a thirsty land;
greatly to our mutual comfort and joy in the Lord, and in one another.`"
One of his last voyages by sea, was in 1750,
and on purpose to perform a religious visit to Friends in Barbados and Tortola,
having his friend, Thomas Lancaster, for a companion;
and when they had performed their service, the said friend was, after a sharp sickness,
removed by death at sea.

Besides this, he met with other severe trials in his pilgrimage through life,
particularly in the long confinement of his wife,
who was seized with the palsy five years before her death,
and lay most of that time entirely helpless.
His behaviour towards her, was that of an affectionate husband,
with much tenderness and care;
and his frequent practice of visiting the sick and afflicted,
evinced a sympathizing heart, and was very becoming his station.
He was preserved in the exercise of his ministry, in much love and gospel simplicity.
His sense of the nature and spirit in which the discipline should be managed,
is thus expressed in an epistle which he wrote to Friends in Tortola, viz.:

"`That you may grow up together a spiritual house that holiness becomes,
and a care according to gospel order may be kept to amongst you,
and that no harshness be used one towards another, but tender and helpful,
and not apt to judge or censure one another,
that you may be kept in that universal spirit of love,
that seeks the good of all and hurt of none, and yet gives all their due,
and what is right and just.`"

His diligence in attending meetings was remarkable; for,
though he lived three miles from the particular meeting in Burlington to which he belonged,
it was very uncommon for bodily infirmities,
or any extremities of weather to keep him at home on meeting days;
and the year before his decease, he visited several general meetings,
both in this and the neighbouring provinces.
A life so spent in fervent endeavours to promote truth and righteousness among mankind,
was, as we have cause to hope, in a suitable preparation to be closed at a short warning.
He was seized with a fit by his own fireside,
which quickly deprived him of understanding, and about three days after,
he breathed his last, on the 21st of the Twelfth month, 1762,
in the seventy-ninth year of his age, having been a minister about sixty years.
He was interred on the 23rd, in Friends`' burying-ground at Burlington,
after a solid meeting held on the occasion.
Having observed strict temperance and moderation,
he finished his course in a good old age; being an example of prudence and steadiness,
which we desire may be often remembered, and usefully improved,
to the advantage of such as are left behind.

ELLIS HUGH was born in Merionethshire, in the principality of Wales,
and came over with his parents into Pennsylvania, when about twelve years of age,
and afterwards settled at Exeter in Berks County.
He was naturally of a cheerful disposition,
and for some time indulged himself in keeping company with such,
whose conversation and conduct were unprofitable and vain; for which,
though it does not appear he was guilty of immoral practices,
he was closely reproved by the witness of God in the secret of the heart,
and his condition being thereby plainly manifested to him,
as likewise the danger of pursuing such courses,
he did not dare to go on any longer in vanity.

Submitting to the reproofs of instruction,
he was brought under great exercise and godly sorrow for his past sins; in which state,
the conversation of his former companions, once his delight, was become a burden,
and increased his distress.
But avoiding to feed their light, airy dispositions, keeping his mind retired,
and reading the Holy Scriptures, when they sought to entice him, had such an effect,
that they forsook him, which was a great ease to his mind,
in that it afforded him opportunity for a further search after the will of Him,
who in mercy had called him to glory and virtue.
As he was thus engaged, after many deep baptisms and trials, it pleased the Lord,
about the thirty-fourth year of his age, to call him to the work of the ministry;
which was an exceedingly humbling exercise to him,
and many sore conflicts he had therein, through the buffetings of Satan;
but by endeavouring to follow the Lord in the way of his requirings,
help was administered, so that he at times, had to experience, that he gives,
"`The oil of joy for mourning, and the garment of praise for the spirit of heaviness.`"
His chief inducement to come and settle in these parts,
was a strong draught of love attending his mind, which, however,
he did not hastily give way to,
having felt drawings hither nearly eight years before he came;
of so great moment did the removing himself and family appear to him.

He was a diligent attender of First and week-day meetings for worship,
as also of monthly, quarterly, and yearly meetings,
even when age and infirmity of body rendered travelling very difficult to him.
He likewise visited some of the neighbouring provinces on truth`'s service,
with the unity of Friends; and by accounts received from the places he visited,
his labours of love were well approved, and serviceable.
He was frequently engaged to visit Friends`' families;
which weighty work he undertook in much diffidence of himself,
and fear of a forward spirit, often saying,
"`That former appointments and engagements thereto,
were of no account for future services; but that such as went,
must wait for renewed qualifications to enter upon that work;`" which he used to say,
"`He thought must be a good one, since it occasioned greater nearness,
and was a renewal of love, both among visitors and visited;`" and by accounts received,
his service in it was so in a good degree.

In meetings for worship, he was a good example in silent, patient waiting upon the Lord;
and when raised to bear a public testimony, it was with that Divine power and authority,
which accompanies a true gospel minister, and made lasting impressions upon some minds.
Though he was of an exceedingly tender disposition,
yet being a lover of good order in the church,
and well knowing the dangerous tendency of undue liberty, he endeavoured,
both by precept and example, to promote the former and discourage the latter;
in which he gave repeated proofs,
that the near connections of natural kindred did not bias his judgment.
His deportment being meek and loving,
and his conversation familiar and instructively cheerful,
gained him the esteem of most who knew him, of different ranks and religious persuasions.
He was a nursing father in the church,
and particularly so to those whom the Lord had visited,
and those who were under affliction, whether of body or mind;
nor was his charity in this respect confined to the members of our Society.

He was an affectionate husband, a tender parent, a kind master; and having,
by the blessing of Divine Providence on his honest industry,
obtained a competency of the necessaries of life, was very hospitable,
entertaining both friends and others freely and kindly;
not with ostentation or for applause, but for the promotion of piety and virtue,
and the good of mankind.
As his natural strength abated in the last years of his life,
he appeared more bright and lively in his public ministry, both at home and abroad.
The day he was taken with his last sickness, at the funeral of one of his sons,
which was the last meeting he was at,
he was remarkably favoured in his public testimony to a large gathering of people;
and in supplication at the same meeting,
his great Lord and master was pleased to favour him
with a transcendent view into the beauty of holiness,
crowning a life, a great part of which had been, according to the measure received,
devoted to his honour,
with evident tokens of his being near to the kingdom of everlasting rest and peace.

The same evening he was taken ill at his own house in Exeter,
and continued for about eleven days, mostly in extreme pain,
yet bore it with patience and resignation to the Divine will.
Though he inclined much to be still and quiet,
yet he uttered many comfortable expressions, some of which were taken down in writing.
At one time he said, "`It is a fine thing to have a clear conscience.`"
And one morning, "`Here is another day: Lord so preserve me through it,
that I may do nothing to offend thee.`"
In the evening he said, "`Lord bless this night to me.`"
And taking something to give him ease, he said, "`He that turned water into wine,
is able to give a blessing.`"
After lying still some time, he said, "`Sorrow at night, but joy cometh in the morning.`"
In the morning he said, "`I remember a dream I had about fifty years ago;
I thought I was in a room alone, just going to die,
and as I was much concerned and troubled because there was no one present to see me die,
I thought the great Physician of value stood by me and said,
'`I will be with thee;`' and I have a little faith, that he will be with me,
and if I am favoured with my senses,
hope I shall not give over wrestling for a blessing.`"

A little before noon, he said, "`Lord, this is the way of mortal men,
when they come to lie on a sick bed, they crave thy favour,
though at other times many are forgetful of thee.`"
At another time he said,
"`Though affliction may not seem pleasant during its continuance,
yet it worketh an exceedingly great joy to them that love and fear God.`"
In the evening, being in great bodily pain, he said,
"`Lord give me ease if it be thy blessed will.`"
The next day being the first day of the week,
several friends came to see him before meeting, to whom he said,
"`Fear God and serve him, and his regard will be to you,
but if you neglect to worship him,
he will cast you off forever,`" or words nearly to that import.
Being fearful they would overstay the time for meeting, he inquired what hour,
saying to them, "`Don`'t neglect the business of the Lord,`" and when they were going,
desired, "`They would remember him when it was well with them.`"
In the evening inquiring what sort of a meeting they had that day, and being answered,
a good meeting; he said with seeming joy, "`The Lord is not limited to persons,
but all that worship him aright shall be accepted of him,`" or words to that effect.

A little after midnight, being in great bodily pain, and from the symptoms,
it was thought for about an hour he was departing,
during which he appeared to have his mind retired to the Lord,
and then reviving a little, said, "`This has been a blessed meeting.`"
The next morning taking leave of a neighbour, he said, "`Farewell,
and if we never meet again in this world,
I hope we shall meet in a more glorious place among the righteous.`"
The day before his departure, his speech failed much, though he remained very sensible;
and the last words he was heard to say, were, "`Lord in heaven receive my soul.`"
Then growing weaker until the third hour, next morning,
being the 11th of the First month, 1764, he departed this life, in a quiet frame of mind,
aged seventy-six years and some months.

RACHEL PEMBERTON was born at Burlington, in West New Jersey, in the year 1691,
being the daughter of Charles Read, who was one of the early settlers of Pennsylvania,
under the grant to William Penn.
It pleased the Lord to extend the gracious visitation of his Holy Spirit to her,
in her tender age, and as she submitted to, and abode under it,
she happily experienced it to lead her into a life of righteousness and great circumspection.
About the eighteenth year of her age, she was married to that worthy Friend,
Israel Pemberton,
who united with her in a pious concern for the prosperity
and prevalence of the cause of truth,
her sincere love to which, and the friends thereof,
she uniformly manifested by her kind sympathetic care as a mother in Israel.
She usefully filled the station of an overseer and elder,
being carefully concerned to rule her own family well,
and that her offspring might have a portion in that treasure which faileth not.
She was a true sympathizer with those under affliction of body or mind,
demonstrating her sensibility herein, by her frequent visits to such,
which were weighty and comforting, her conversation being solid and instructive.

In the First month, 1754,
it pleased Divine Providence to deprive her of her beloved husband,
in whom was removed a father, a friend and counsellor to her and the church;
which close trial, after forty years living together in much harmony,
she was enabled to bear with Christian calmness and resignation;
having often to experience the reality of that truth left upon record,
"`A father to the fatherless, and a judge for the widow, is God in his holy habitation.`"
She continued her house open for the reception of friends visiting the city of Philadelphia,
whether near or from remote parts, as it had been in her husband`'s time,
particularly for the entertainment of those who came
from Europe on religious visits to America,
with whom she was often brought into much sympathy under their weighty travail and exercise.
Few have been more zealously concerned,
and diligent in the attendance of religious meetings,
seldom allowing the inclemency of weather to prevent her;
and continued to manifest the like concern when very feeble; which diligence, was,
in the time of her confinement and languishing state, a satisfactory reflection to her,
as her attendance had been from a real sense and persuasion of duty.

On the 22nd day of the Tenth month, 1764,
she attended the Second-day`'s meeting of ministers and elders,
which was the last meeting she was at.
Her feeble state required her confinement to her chamber the 25th,
and she gradually weakened; yet love to the cause of truth continued,
and her concern was great,
that the professors thereof might live under its preserving influence.
She uttered many lively expressions at different times in the course of her illness,
in acknowledgement of the goodness and mercy of the Lord,
"`In preserving her in patience under great bodily pain,
and with an evidence of her future well-being.`"
She departed this life, on the 24th day of the Second month, 1765,
and was interred in Friends`' burial-ground in Philadelphia,
on the 27th of the same month.
