== Conclusion

The memoirs contained in these volumes furnish ample testimony that the happy effects
of pure and undefiled religion are peculiar to no age or condition in life.
The child of tender years, and the aged veteran in the Lamb`'s army,
the humble servant as well as the master,
the unlearned no less than those who were skilled
in knowledge as they submitted to the cross of Christ,
and under the teachings of the Holy Spirit,
learned of Him who is meek and lowly in heart, accepting the Lord Jesus in living faith,
as their Redeemer, their propitiation, their Leader and Sanctifier,
were made joyful partakers of that Salvation which
he purchased for us by his precious blood,
and amid the pains of expiring nature,
were supported by the hope of a glorious immortality.
Jesus Christ was their Rock and Refuge, and their hope of Salvation;
and he remains to be the only foundation to the present day.
Those who build upon Him,
through obedience to the power of his Spirit in the secret of their own hearts,
will find that He is a Rock against which neither death nor hell can prevail.

Religion is a work of daily self-denial and mortification to the natural mind;
and those who expect to enjoy its consolations and its privileges, must deny themselves,
take up the daily cross, and follow the Lord Jesus in the regeneration.
And seeing there is such a cloud of witnesses to its excellency and advantages, who,
though dead, yet speak to us, in the inviting language,
"`follow us as we followed Christ,`" may their bright
examples induce the reader to lay aside every weight,
and the sin which may easily beset, and to run with patience the heavenly race,
looking unto Jesus, the Author and Finisher of the saints`' faith,
that at the close of life he may inherit a crown of glory that shall never fade away.

[.the-end]
END OF FOURTH VOLUME.
