== Chapter 2

[.chapter-synopsis]
* Humphrey Smith
* John Audland
* Richard Farnsworth
* Mary Harris
* Josiah Coale
* Francis Howgill
* Thomas Loe
* Elizabeth Furly
* Margaret Molleson
* Jane Whitehead
* William Bayley
* Joseph Briggins
* Robert Jeckel

HUMPHREY SMITH, of Little Cowrne, in the county of Hereford, formerly a public preacher,
was convinced of truth about the year 1655,
and came to be an able minister of the gospel of Christ, which he freely preached,
and turned many to righteousness,
and gave forth many warnings and exhortations to the people,
as may be seen at large in the printed collection of his works.
The Lord showed him in a vision, in the fifth month, 1660,
the destruction of the city of London by fire,
which was six years before it came to pass; and which vision he published before-hand,
as a warning to the people to repent; part whereof is as follows:

[.embedded-content-document.paper]
--

[.blurb]
=== Part of the vision of Humphrey Smith, which he saw concerning the burning of the city of London, in the fifth month, 1660, which was three years before his decease, and six years before it was fulfilled.

As for the city herself, and her suburbs, and all that belonged to her +++[+++I beheld]
a fire was kindled therein, but she knew not how, even in her goodly palaces,
and the kindling of it was in the foundation of her buildings.
There was none could quench it, neither was there any able;
and the burning thereof was exceedingly great, and burned inward in an hidden manner,
which cannot be expressed.
The fire consumed foundations which the city stood upon, and the tall buildings fell,
and it consumed all the lofty things therein,
and the fire searched out all the hidden places, and burned most in secret places,
but the consumption was exceedingly great wherewith it was consumed.

And as I passed through her streets, I beheld her state to be very miserable,
and very few were those that were left in her, who were but here and there one,
and they feared not the fire, neither did the burnings hurt them;
but they were (and walked) as mournful people, and the fire burned everywhere,
so that there was no escaping of it.
And thus she became a desolation, and as an astonishment;
for the burning was suffered of God for her chastisement,
and could not be quenched nor overcome.
There was none could stop the flaming; and the fire consumed all things,
both stone and timber; and burned under all things, and under all foundations;
and that which was lifted up above it fell down, and the fire consumed it.

The flaming continued, though the foundation was burnt up,
and all the lofty part brought down by the fire; yet there was much old stuff,
and part of broken desolate walls and buildings in the midst,
which the fire continued burning against; and that which was taken, as to make use of,
which yet escaped the fire, became useless in men`'s hands, as a thing of naught.
And the vision thereof remained in me, as a thing that was secretly showed me of the Lord.

And now let her wise men find out the matter, and her prudent men read,
and her divines, so called, interpret the vision,
and let every one look to their own ways.

--

This, with much more that Humphrey Smith saw, was printed and published in the year 1660,
as a warning whereby people might stand in the day of trial,
and endure the hour of trouble.
See it at large in his printed vision in the year 1660.

Besides other things which the Lord revealed to him,
he had also a clear sight of his own sufferings, and death thereby.
For about the year 1662, travelling among friends about London,
he told some of them that he had a narrow path to pass through; and said several times,
before he was taken up, he saw he should be imprisoned,
and that it might cost him his life.
Taking leave of his friends, he set forward, in the will of God, westward;
and being in a meeting of the people called Quakers, at Alton in Hampshire,
he was taken from thence, and had before the two lieutenants of the county,
who committed him to the stinking close prison of Winchester, where,
after a whole year`'s imprisonment, he fell sick.

In the time of his sickness he spoke many precious words to friends about him,
signifying that he was given up to the will of God, either in life or death.
And as he lay under great illness, he said,
"`My heart is filled with the power of God;`" and, "`It is good for a man,
at such a time as this, to have the Lord to be his friend.`"
Another time he said, "`Lord, thou hast sent me forth to do thy will,
and I have been faithful unto thee in my small measure,
which thou hast committed unto me; but if thou wilt yet try me further,
thy will be done.`"
Also he said, "`I am the Lord`'s; let him do what he will.`"
And near the time of his departure, he prayed earnestly, saying, "`O Lord,
hear the inward sighs and groans of thine oppressed,
and deliver my soul from the oppressor: hear me, O Lord, uphold and preserve me.
I know that my Redeemer liveth: thou art strong and mighty, O Lord.`"
He prayed that the Lord would deliver his people from their cruel oppressors;
and for those who had been convinced by him, that the Lord would be their teacher.

He lay quiet and still, sensible to the last moment, and died a prisoner for the truth,
in the common jail of Winchester, on the 4th of the Eighth month, in the year 1663.

[.asterism]
'''

JOHN AUDLAND was born in the county of Westmoreland, near Cam`'s-gill, and when a child,
he was ripe and quick of understanding.
About the eighteenth year of his age, the Lord inclined his heart towards himself,
and he delighted in reading the scriptures; and having a large knowledge and memory,
could discourse of things relating to religion, and became an eminent preacher,
not only amongst the most strict sort of professors, but sometimes also at chapels,
and public parish places of worship,
where great multitudes of people would flock after him.

About the twentieth year of his age he married Anne Newby, of Kendal,
belonging to the same religious meeting, afterwards the wife of Thomas Camm,
of Cam`'s-gill in Westmoreland.
This John Audland was one of those before mentioned,
who was convinced the first time that he heard George Fox at Firbank chapel,
and received him into his house.
Seeing the emptiness of his own high-flown notions and profession in religion,
he sat down in silence and astonishment, like Job, for many days;
and great was the work of the Lord upon him, being stripped of his earthly wisdom,
and in that state he mourned and wept bitterly, for he saw where he had been,
and that it was the Lord alone that could help him.

In great compassion the Lord revealed his saving health and arm of power,
by which he raised him up,
and filled him with wisdom and strength for the performance of that work +++[+++in which]
he would concern him, in gathering home the outcasts of Israel,
and the dispersed of Jacob; and sent him forth to preach redemption,
in the name of the Lord Jesus Christ, to the poor, and deliverance to the captive,
and the day of vengeance upon the wicked.
Leaving all his outward concerns; he went forth, and the dread, wisdom,
and majesty of the Lord was with him,
and many hundreds were turned to the Lord through him, as an instrument in God`'s hand.
Bristol, and several counties in the west of England,
were witnesses of the power and efficacy of his ministry, who with John Camm,
was of the first of those called Quakers who went to that city,
preaching Christ Jesus the light of the world.
He was often concerned in disputations, and the Lord furnished him with matter,
so that he stopped the mouths of gainsayers; his testimony was large and free,
affecting almost to all sorts of people, and he had a word in season to all conditions;
but notwithstanding he was young and strong,
yet that service much spent him several years before he died.

He had been several times in prison for his testimony`'s sake, as at Newcastle,
and at Bristol; and often in great perils, sore beatings, and cruel mockings,
both of the rabble, and also of the bitter spirited professors, but through all,
the Lord preserved him faithful.
He growing weak by a lingering distemper of a cough and consumption,
would often say in his sickness, "`Ah! those great meetings in the orchard at Bristol,
I may not forget.
I would so gladly have spread my net over all, and have gathered all,
that I forgot myself, never considering the inability of my body.
But it is well, my reward is with me, and I am content to give up and be with the Lord,
for that my soul values above all things.`"
Near his death, friends visiting him,
the Lord did wonderfully open his mouth in exhortation,
to their great refreshment and joy, as if he had been without sense of sickness.
He had a tender regard to his dear wife; "`But in this,`" said he,
"`my will is in true subjection, submitting to the will of the Lord,
whether life or death.`"
He desired his wife to give him up freely to the disposing hand of the Lord;
and the Lord strengthened her freely to recommend him into his hands,
which made him easy.

He was often, in the time of his sickness,
exceedingly filled with the high praises of God,
being overcome in the sense of God`'s love, joy, and everlasting peace.
When he grew weaker, he would be helped up upon his knees,
and upon his bed fervently supplicated the Lord, in the behalf of his whole heritage,
that they might be preserved in the truth, out of the evil of the world;
and that his gospel might spread, and be published,
to the gathering of all that appertain to Israel.
So was he sweetly taken away in the joy of the Lord, on the 22nd of the First month,
in the year 1664.

He was convinced in 1652, and died 1664, being aged about thirty-four years.

[.asterism]
'''

RICHARD FARNSWORTH, of Balby, in Yorkshire,
was also one of those whom the Lord raised up early in the work of the ministry.
He suffered about twelve months`' imprisonment at Banbury, in Oxfordshire,
in the year 1655, and many were turned to God by him.
He was mighty in discourses, and disputes with priests and professors,
and after much labour in the work of the ministry, and great sufferings and persecutions,
he at last finished his testimony in London.

A little space before his departure out of this life, sitting up in his bed,
he spoke in as much power and strength of spirit
as he had ever done at any time in his health,
these words following: "`Friends, God hath been mightily with me,
and hath stood by me at this time,
and his power and presence have encompassed me all along.
God hath appeared for the owning of my testimony, and hath broken in upon me as a flood,
and I am filled with his love more than I am able to express;
and God has really appeared for us.
If God himself had come down, and spoken as a man,
he could not have spoken more clearly to us than he hath done,
by the many testimonies from heaven in his people.
Therefore I beseech you, friends, here of this city of London, whether I live or die,
be you faithful to your testimony God hath committed to you.`"
He died in the city of London, in the year 1666.

[.asterism]
'''

MARY HARRIS, of London, a maid young and beautiful,
went often with her relations to the meetings of the people called Quakers,
and had a love raised in her to the blessed truth,
and to them who held it in a pure conscience;
yet still lived in the customs and fashions of this evil world.
But the same love of God that had begotten tenderness in her heart, and love to truth,
followed her, and would not suffer her to sit down in the world without trouble.
The Lord visited her with great weakness, so that she grew ill,
and fell into a consumption for about three years;
and being often visited by Josiah Coale, and put in mind to consider,
whether the hand of the Lord was not upon her for her unfaithfulness and disobedience,
she did consider the matter, and the Lord set it home upon her heart,
and she cried to him for mercy; and applied her heart to the Lord,
and his faithful messengers, saying,
"`I have hardened my heart at many precious meetings, when the Lord hath smitten me;
and I have seen plainly, that the Lord would have gathered me; but I said in my heart,
if I receive this, if I give up to this, I must be a Quaker, and I cannot be a Quaker.
Then would I take my heart from attending upon the ministration of truth,
and then my heart became more hard.
What shall I do,`" said she,
"`that now I may receive the faithful sayings of the servants of the Lord?
Oh! that my heart were open; but it is shut and hard:
when shall I find mercy in this state?`"
She remained so for some time, and grew weaker and weaker in body;
and on the first day she took her bed she was much
under the righteous judgments of the Lord,
and felt his word in her heart as fire.
But the Lord in judgment remembered mercy, and having brought her very low,
he showed her the child`'s state, which she with great delight desired;
and indeed she became as a little child, fit for the kingdom of heaven.

Then did the Lord rend the veil, and showed her his glory,
and the preciousness of his pure truth, and the light shined out of darkness,
and in it she saw light, and received the knowledge of God;
and her heart was filled with joy and praises to the Lord, saying, "`I am well;
I feel no pain.
I am full; my cup runs over.
I am filled as it were with marrow and fatness.
I have seen his glory, and tasted his precious truth.
How pure is God`'s everlasting truth?
Nothing so pure; and they who indeed receive it, are made pure by it.
Praised be the Lord who hath made me partaker of it, and placed me among his people.
Oh! blessed God, who hath given me cause to sing aloud of thy praise.`"

Many precious words she spoke to several persons who came to visit her,
to their several conditions, showing to some, who lived in pleasure, her hands, saying,
"`See here, the Lord hath made these bones bare for my rebellion;
because I would not submit to his precious truth.
He hath brought me to the dust, and I must lay down this body as a sacrifice.
Oh! do not you stand out, it will cost you dear, if ever you find mercy.`"
Then she would sing praises to the Lord, and exhorted all speedily to embrace truth,
and warned others professing truth, from following the fashions of the world,
crying to the Lord to wash her thoroughly.
Some would say to her,`" It may be thou mayest recover.`"
"`No, no,`" she replied, "`I must lay down this body for my rebellion.
In my vain life, if any had said I should recover,
it would for a little time seem to refresh me;
and if they had said surely I could not live long, it would cast me down;
but now I long for death.
I must lay down this body; for,`" said she, "`when I received God`'s everlasting truth,
I received the sentence of death:`" and this she was positive in all along.

More sensible expressions she uttered, which I omit for brevity.
About half an hour before her departure, she was taken with a very great trembling,
and seemed to be somewhat troubled; when one near her said, "`What is the matter?
art thou in any doubt concerning the truth of which thou art made partaker?`"
She replied, "`No, no; that is God`'s pure everlasting truth, which the people of God,
called Quakers, are made partakers of, and for which they suffer; that is everlasting,
that is the true spirit, and their God is my God;
and although I see it not now as I have seen it, yet I bring in my testimony,
that is the truth that shall abide forever; that is pure,
and nothing that is defiled shall be sheltered under it.
That is the truth which enlighteneth every man coming into the world:
the little seed in me is become great, great, great!
Blessed be God who hath placed me among his people, and I possess what they possess;
and when the faithful die as I die, my portion will be their portion; and my cup is full,
it runs over and over.`"
Then she breathed a little thicker for about the space of a quarter of an hour;
and so without groan or sigh, or the least motion, she shut her eyes and slept.
Glory to God forever.

She died at the widow Mary Forster`'s, in that called St. John`'s street,
near Smithfield, London, in the year 1668.

[.asterism]
'''

JOSIAH COALE, born of a family of good repute among men, near the city of Bristol,
was convinced of God`'s everlasting truth,
through the powerful ministry of that servant of God, John Audland, about the year 1655.
The word of life pierced Josiah to the heart,
and wrought effectually to his salvation and redemption.
He walked for a time under deep judgment, and mournfully,
so that he became a gazing stock and wonder to his former acquaintance.
But God`'s arm was strong, and plucked up every evil plant, and purified him,
and made him fit for the Lord`'s use,
and an able minister of the everlasting gospel of Christ Jesus; an incessant labourer,
few more spent in God`'s service.
His soul seemed wholly bent to the renowning the name of Christ;
and the enemies of truth he ever accounted his enemies.

His declaration was to the ungodly like an axe, or hammer,
and a sword sharp and piercing,
being mostly attended with an eminent appearance of the dreadful power of the Lord,
to the cutting down many tall cedars, and making the strong oaks to bow;
but to the faithful and diligent, who minded the things of Christ more than their own,
oh! how soft and pleasant were the streams of immortal life that ran through him,
to the refreshing of those!
It was his life and joy to be speaking the word of the Lord, and not his own words;
and many thousands were living witnesses to the power,
virtue and efficacy of his ministry; but above all,
he was terrible to the sowers of strife, secret backbiters,
and such as rend the holy body, and separated from the life, love,
and fellowship of the blessed truth; who, in their own selfish spirits,
set themselves over their brethren, by feignedness and deceitful appearances,
to the destroying the simple-hearted.

In his conversation, his kindness was so mixed with seriousness,
and his familiarity with a stayed and exemplary behaviour,
that he was an honour to the truth,
and therein a confirmer of his holy testimony and weaker brethren.
He was hardy, valiant, and fixed; not of those who shun the cross,
or sell their birth-right for a mess of pottage.
He baulked no danger for the sake of his blessed testimony,
which he bore faithfully in England, Holland, the Low Countries, and Barbados;
and had also sore travels among the heathen in America, as in Maryland, Virginia,
and New England, preaching the gospel of Christ among them.
He travelled on foot through the wilderness, from Virginia to New England,
in danger of wild beasts and venomous creatures, +++[+++enduring]
much hunger and cold, and weariness, and through bogs and waters,
often obliged to eat chestnuts for food when hungry,
as appears at large in the record of New England`'s persecution.

He was a good example, as well for his liberality as faithfulness;
for as the prosperity of God`'s truth was above all things most in his eye,
so he was always cautious of making the gospel chargeable to any; for,
having some estate of his own, he freely employed it in the Lord`'s service,
counting nothing too dear for the name and service of the Lord.
Thus having laboured his natural strength away in this heavenly warfare,
for the promotion of the glorious truth of the Lord,
and for the advancement of its interest and dominion in the world,
for above twelve years together, he did, with perfect understanding,
and in an extraordinary enjoyment of the Lord`'s life, majesty, and presence,
to the refreshment of the beholders, cheerfully lay down his mortal body.

George Fox, visiting him upon his sick-bed,
queried whether he had any thing upon his mind to write to friends in England,
or beyond sea.
He said that he was clear of writing to them;
and that as the Lord by his power had carried him through England and other nations,
so he had nothing to write; but he desired his love to all friends.
One thing, he said, did lie upon him,
in that he understood Lodowick Muggleton (a most blasphemous
ranter) and his company would boast against him;
and understanding George Fox was preparing a book in answer to the said Muggleton,
desired he might put in a few words as his last testimony against Muggleton;
which George Fox desired him to prepare, and he would call for it as he came back.

He spake them forth in the power of the Lord, as fresh as if he had ailed nothing,
and a friend took it in writing, which is as followeth:

[quote]
____
Forasmuch as I have been informed,
that Lodowick Muggleton hath vaunted concerning my departure out of the body,
because of his pretended sentence of damnation given against me;
I am moved to leave this testimony concerning him, behind me,
viz. That he is a son of darkness, and a coworker with the prince of the bottomless pit,
in which his inheritance shall be forever.
The judgment that I then declared against him, stands sealed by the Spirit of the Lord,
by which I then declared unto him,
that in the name of that God that spanneth the heavens with his span,
and measureth the waters in the hollow of his hand, I bind thee here on earth,
and thou art bound in heaven; and in the chain under darkness,
to the judgment of the great day thou shalt be reserved;
and thy faith and strength thou boasted of I defy and trample under foot.
I do hereby further declare the said Lodowick Muggleton to be a false prophet,
in what he said to me at that time,
viz. That from henceforth I should always be in fear of damnation,
which should be a sign to me that I was damned; which fear I never was in since;
so that his sign given by himself did not follow his prophecy,
which sufficiently declares him to be a false prophet.
____

George Fox, when he came back again, found Josiah sitting by the fireside,
filled with the power of the Lord, and speaking to friends about him as followeth:
"`Well, friends, be faithful to God, and seek nothing for self, or your own glory;
and if any thing wrong arise, judge it down by the power of the Lord God,
that so you may be clear in his sight, and answer his witness in all people;
then will you have the reward of life.
For my part, I have walked in faithfulness with the Lord,
and I have thus far finished my testimony, and have peace with the Lord,
and his majesty is with me, and his crown of life is upon me:
so mind my love to all friends.`"

Then he spoke to Stephen Crisp, saying, "`Dear heart, keep low in the holy fear of God;
that will be thy crown.`"
Afterwards he said, "`A minister of Christ must walk as I have walked.`"
Then he desired George Fox to pray, that he might have an easy passage:
and friends seeing him begin to be heavy, desired him to go and lie down on the bed,
which he did; and friends sat about him, and held him,
and he was filled with the power of the Lord and seed of life, which was over all.
So in that he departed away, in the arms of friends, as he sat on the side of his bed,
and had a very easy passage into eternal life.

He died in London, aged thirty-five years and two months, in the year 1668.

He laboured in the ministry twelve years, and wrote many treatises,
which are collected together in one volume.

[.asterism]
'''

FRANCIS HOWGILL, of Grayridge, in the county of Westmoreland,
an early minister of the gospel of Jesus Christ,
was convinced of the blessed truth by George Fox,
at that notable meeting at Firbank Chapel, in Westmoreland, in the year 1652.
He soon became a powerful minister, and preached Christ freely as he had received him.
He came to London with Edward Burrough early, to visit that city;
and travelled to Bristol and divers parts of the nation,
and suffered imprisonment in Appleby jail, in the year 1652; and a nasty,
stinking prison it was.
He was set at liberty the latter end of the year,
and grew valiant and bold for the name of the Lord, travelling up and down on foot,
preaching the gospel.
He went to the steeple-houses, and to many places,
warning both priests and people of the day of the Lord that was coming upon them,
directing them to Christ Jesus their teacher and Saviour.

He came also to London, on foot, with John Camm, to admonish Oliver Cromwell,
soon after he was made protector; and he went with Edward Burrough to Ireland,
and preached Christ under great sufferings there, until he and Edward Burrough aforesaid,
were banished by Henry Cromwell out of Ireland.
Afterwards he was imprisoned in London, in the year 1661,
at the time when the Fifth Monarchy people rose up in arms,
but was clear of that bloody act; and so was set at liberty,
and continued labouring up and down the nation, in the work of the Lord,
and turned many to God.
In the latter end of the Fifth month, in 1663,
he was sent for out of the market in Kendal, by the magistrates,
who tendered him the oath of allegiance,
and because for conscience-sake he could not take it, they sent him to Appleby jail;
and at the assizes, for refusing to take the oath,
sentence of premunire was given against him by the judge, in these words:
"`You are put out of the king`'s protection, and the benefit of the law;
your lands are confiscated to the king during your life,
and your goods and chattles forever; and you to be a prisoner during your life.`"

[.discourse-part]
F+++.+++ Howgill replied, "`An hard sentence for my obedience to the commands of Christ;
the Lord forgive you all.`"

[.discourse-part]
_Judge:_
"`Well, if you will yet be subject to the laws of the king,
the king will show you mercy.`"

[.discourse-part]
_Francis Howgill:_
"`The Lord hath showed mercy unto me, and I have done nothing against the king,
or government, or any man, blessed be the Lord, and herein stands my peace;
for it is for Christ`'s sake I suffer, and not for evil doing.`"

[.small-break]
'''

The court broke up, and many were sorry to see what was done against him;
but he signified how contented and glad he was,
that he had any thing to lose for the Lord`'s precious truth,
of which he had publicly borne testimony,
and that he was counted worthy to suffer for it.
He was kept a prisoner in Appleby jail four years and a half;
and his body being much spent in his public travels and labours in the gospel,
was not able to endure such close confinement,
though he bore his suffering in much patience and
cheerfulness until the time of his decease.

He was taken ill the 11th of the Eleventh month, 1668,
and though his departure drew nigh, yet was he kept in perfect understanding,
being often very fervent in prayer; and uttered many comfortable expressions,
to the refreshment of those about him.
Two days before his death, his wife and friends being present, he said, "`Friends,
as to matter of words you must not expect much from me,
neither is there any great need of it,
or to speak of matters of faith to you who are satisfied;
only that you remember my dear love to all Friends who enquire of me,
for I ever loved Friends well, and any other in whom truth appeared.
Truly God will own his people, as he hath ever hitherto done,
and as we have daily witnessed;
for no sooner had they made that act against us for banishment,
to the great suffering of many good Friends,
but the Lord stirred up enemies against them, even three great nations,
whereby the violence of their hands was taken off.
I say again, God will own his people, even all those that are faithful; and as for me,
I am well, and content to die; I am not afraid at all of death.
Truly one thing was of late in my heart,
and that I intended to have written to George Fox and others,
even that which I have observed, which thing is, that this generation passeth away,
when so many good and precious Friends, within these few years have been taken from us;
and therefore Friends had need to watch and be very faithful,
so that we may leave a good, and not a bad savour, to the next succeeding generation;
for you see that it is but a little time that any of us have to stay here.`"

Often he said in the time of his sickness, that he was content to die,
and that he was ready;
and praised God for the many sweet enjoyments and refreshments
he had received on that his prison-house bed where he lay,
freely forgiving all who had a hand in his restraint.
And he said, "`This was the place of my first imprisonment for the truth at this town;
and if it be the place of my laying down the body, I am content.`"

Several persons of note, inhabitants of Appleby, as the mayor and others,
went to visit him some of whom praying God might speak peace to his soul,
he sweetly replied, "`He hath done it;`" and they all spoke well of him.
A few hours before his death, some being come to visit him,
he prayed fervently with many heavenly expressions,
that the Lord by his mighty power would preserve
them out of all such things as would spot and defile.
A little after, recovering some strength, he further said,
"`I have sought the way of the Lord from a child, and lived innocently, as among men;
and if any enquire after my latter end, let them know,
that I die in the faith that I lived in and suffered for.`"
These words he spoke, with some other words in prayer,
and sweetly finished his course in much peace with the Lord, in the Eleventh month, 1668.

He laboured in the gospel sixteen years:
there is a volume of his works printed in about 740 pages in folio.

[.asterism]
'''

THOMAS LOE, of Oxfordshire, was a faithful servant and minister of Christ Jesus,
and converted many to truth, especially in Ireland,
where he travelled through great hardships.
His first going thither was about the year 1657; Francis Howgill, Edward Burrough,
and others, having been there before him.
He had an excellent gift, sound and clear in the ministry, powerful in speech,
sharp and quick in his understanding; and many people flocked after him,
and received truth by his ministry in that nation;
and others he confirmed in the truth who were convinced before.
He was often publicly engaged with priests and opposers,
and the Lord made him a sharp instrument in his hand
to confound the adversaries of truth,
and the mouths of gainsayers were stopped.
His company was very desirable, being pleasant and sweet in conversation,
and sympathizing with his friends in affliction,
so that he could speak a word in due season.

He was several times a prisoner for the testimony of truth,
and went out of England several times to visit the nation of Ireland,
in which travels his natural strength was much impaired.
He also laboured in the work of the ministry in London, being often there;
and was taken sick in that city,
expressing on his deathbed what exceeding encouragement
and glory he saw and felt of the Lord,
as followeth: "`Glory to thee, O God, for thy power is known.
God is the Lord.`"
Then speaking to William Penn, whom the Lord had made him instrumental to convince,
he said, "`Dear heart, bear thy cross.
Stand faithful for God, and bear thy testimony in thy day and generation,
and God will give thee an eternal crown of glory, that shall not be taken from thee.
There is not another way that the holy men of old walked in, and it shall prosper.
God has brought immortality to light, and immortal life is felt: glory, glory,
for he is worthy.
My heart is full, what shall I say?
His love overcomes my heart; my cup runs over, my cup runs over.
Glory, glory to his name forever.
He is come, he has appeared, and will appear.
Friends, keep your testimony for God, live with him, and he will live with you.`"

Another time he said to some friends, "`Be not troubled,
the love of God overcomes my heart.`"
And again he spoke to George Whitehead, and other friends present, viz., "`George,
the Lord is good to me; this day he has covered me with his glory.
I am weak, but I am refreshed to see you: the Lord is good to me.`"
Another friend asked him, "`How art thou, Thomas?`"
He answered, "`I am near leaving you, I think; but as well in my spirit as I can desire,
I bless the Lord; and I never saw more of the glory of God than I have done this day.`"
And then being expected to depart, the power of the Lord arose in him,
and he sung to the Lord, "`Glory, glory to thee forever.`"
And so continued praising God for some time, which much affected the standers by.

He departed in peace with God, on the 5th of the Eighth month, in the year 1668,
at London.

[.asterism]
'''

ELIZABETH FURLY, daughter of John Furly of Colchester, in the county of Essex,
was a child that loved the Lord, and also those who feared him.
Her delight was to hear truth preached, and to be with such who excelled in virtue;
she feared and hated a lie,
and lived and died in the faith which the people called Quakers profess.
She was taken sick at her father`'s house in Colchester, the 11th of the Twelfth month,
in the year 1669.

Two days before she died, being filled with the love of God,
she uttered many precious sayings concerning the Lord, and his mercies towards her;
praying to the Lord that she might be faithful to the end.
In the presence of several persons she spoke as followeth: "`Whatever is not of thyself,
O Lord, purge out of me; yea, purge me thoroughly, leave no wicked word in me,
thrust away the power of darkness.
O Lord, make me able to praise thee: let me not come into that way which is evil,
for if I do, I shall dishonour thee and thy truth.
I hope I shall never rebel against thee more, but have full satisfaction in thee,
and in thy ways, and not in the evil one and his ways.
Wash me, O Lord, thoroughly,
let not an unadvised word come out of my mouth;`" with more to the same purport.
"`Show them, O Lord, the evil of their ways, that have done evilly,
and lay a burden upon their spirits, that they may leave it.
I feel no pain, the Lord is good to me; good is the will of the Lord.
Let thy will be done in earth as it is done in heaven.
Everlasting kindness hast thou shown me,
and I hope I shall never forget it while I am in this world;`"
with more in admiration of the kindness and mercies of God,
and her desire to serve him whilst she lived.

To one of her brothers she said, "`Improve thy time,
for thou knowest not how soon thou mayest be taken
away;`" warning him of the danger of an evil life,
and took him about the neck and kissed him, saying, "`Mind what I say,
O dear brother;`" and with many more words she exhorted him.
She also admonished her other brothers with tender expressions, saying, "`Love the Lord,
brothers, love good men: hate the devil; but oh, love the Lord,
and then you will be a joy to your father and mother.`"
When she saw one of her sisters weep, she said, "`Weep not for me, I am very well.
All serve the Lord, that he may be your portion.
In my Father`'s house there is bread enough, there is fulness, want of nothing; yea,
there is fulness of bread, durable riches and honour.
I desire never to forget the Lord.`"
as she walked in innocency, so she died in peace, and entered into glory,
the 16th day of the Twelfth month, in the year 1669, aged thirteen years and five weeks.

[.asterism]
'''

MARGARET MOLLESON, wife of Gilbert Molleson of the city of Aberdeen in Scotland,
was in her youth an enquirer after the best people,
and joined herself in worship with the most strict
and refined in profession then in that city.
But it having pleased God,
who beheld her hungering desires after himself and his righteousness,
to send some of his faithful witnesses and servants called Quakers,
from the nation of England into the north of Scotland,
who preached the everlasting gospel;
she was one of the first in those parts that received the same.

Coming to taste of the unspeakable love of God, she delighted often to retire therein,
out of the cumbering cares of her family and business.
And although her love to her husband, and cares of her many children, were great,
yet her greatest delight and care was,
to draw nearer and nearer to the true and living God,
the chiefest beloved of her travailing soul.
For that end she often resorted to the public meetings of the people called Quakers,
as well as being frequently in private with the Lord in prayer;
which gave her husband (who was not one called a Quaker) cause to say,
that her knees were worn with kneeling at prayer.

For about four months before her departure hence, he usually found her,
when he awaked in the night-time, in meditation; and after her departure,
he also said before several people coming to visit him,
that he had lost a true Mary and a Martha, none knowing how great his loss was,
and he could not but much lament it.

On the 16th of the Tenth month, 1669, in the morning, she was taken suddenly sick,
and the same day in the evening died,
having been for some time before made sensible of her end; yet her physician,
not supposing that she had been so dangerous, said to her, she needed not fear,
his life for hers; to which she answered, "`Fear, I have no cause;
but thou wilt see thou art mistaken.`"
Many relations and neighbours being in her chamber, were in great sorrow;
among whom was a great professor, and an old acquaintance of hers,
who desired those about her to pray for her; which she hearing,
when others thought she had been dying, answered, "`My advocate is with the Father,
and my peace is made.
I am feeding at a table none of you perceiveth.`"
Some lamenting much her being like to be taken away from her nine children,
who were all about her bed, she said, "`As many of them as shall truly fear the Lord,
and follow him, shall be provided for:`" which hath been since truly fulfilled.

Fixing her eyes on her son Gilbert, who was then about ten years of age,
she said in a heavenly frame of mind, "`Truth is precious, cleave to it.`"
She observing the people in her chamber much lamenting, said to them,
"`Settle yourselves, and be stayed in your minds, for ye are now to see the last.`"
Being to reap eternally the fruit of her great and spiritual labours,
she had true cause given her then to declare before those present,
viz. "`Now interruption is to cease,
and my eternal joy is already begun;`" the certain earnest of which she received,
and +++[+++had]
often preferred before all other enjoyments.

Her life and conversation, as well as her latter end,
were such as gained her not only great love and esteem from friends of truth,
but also from others of her acquaintance.

She departed hence on the 16th of the Tenth month, in the year 1669,
about the forty-second year of her age, at Aberdeen, in the kingdom of Scotland.

[.asterism]
'''

JANE WHITEHEAD was the wife of Thomas Whitehead, of North Cadbury in Somersetshire.
Her maiden name was Jane Vaugh, and she was born in Westmoreland,
her relations living about Hutton in the same county;
whom she left in obedience to the Lord, and travelled in his service,
and bore witness against the false ways and worships of the world;
and for the sake of her testimony endured much persecution.

In the year 1655, coming to Banbury in Oxfordshire,
to visit her dear friend Anne Audland, then a prisoner for the truth, she,
for bearing witness thereto, and against their cruelty and wickedness,
was also taken and committed to prison, and lay there five weeks.
Not long after, coming again to the said town,
the magistrates tendered her the oath of abjuration;
which she refusing for Christ`'s sake,
who saith "`Swear not at all,`" was imprisoned twelve months in a low, wet, nasty place,
in the winter season, that sometimes she would be over shoes in water;
which she endured with much patience.

In the Fourth month, 1662, she was again imprisoned at Banbury,
for worshipping God at a meeting of the people called Quakers,
where she lay in the same nasty prison three months.
These things she suffered before she was married.
Afterwards Thomas Whitehead, aforesaid, took her to be his wife,
by whom she had five children that she left behind her.

At Ivelchester, she endured five months`' imprisonment, with a young child at her breast,
in a cold winter,
for speaking the words of truth and soberness to the priests of North Cadbury.
But the Lord upheld her by the word of his power,
in the manifold exercises and tribulations which she passed through,
too tedious here to relate.
Those abuses which she endured brought her tender body into weakness,
which attended her several years before she died; and,
under great exercises and weakness of body,
she acknowledged that the Lord was wonderfully good to her.
She often said that the Lord had broken in upon her,
and with his heavenly presence did fill her, to the comfort of her soul: and said,
"`O that the Lord may never take his presence from me.`"
To the last she was kept sensible,
and declared that she had the testimony of God`'s love,
and that it would be well with her,
and that she had no desire to live any longer in this world.
She charged her children to be obedient to their father, and that they should mind truth,
and then the blessing of the Lord would be with them.

The morning before she died, being sensible her death was at hand,
she told a Friend that she was going to her long home; and soon after departed this life,
in the love and peace of God, on the 28th day of the Seventh month, in the year 1674.

[.asterism]
'''

WILLIAM BAYLEY, who was a Baptist teacher at Poole, was convinced of the blessed truth,
as professed by the people called Quakers, in the year 1655,
and travelled up and down in many places in the service of the Lord.
His gift in the ministry, both as to matter and utterance, was plain and prevalent;
he divided the word aright, for he fed the fat with judgment;
and yet he had milk for babes, and stronger meat for those of riper age.
He was mighty in the holy Scriptures,
being well acquainted both with the history and mystery thereof,
through the assistance of the Holy Spirit, which gave him a true understanding in both.
It was given him, not only to believe and preach the word of faith,
but also to suffer for the same, sometimes by cruel persecutions;
being thrown down and dragged upon the ground by the hair of his head;
and his mouth and jaws endeavoured to be rent and broken asunder,
that the ground whereon he lay was smeared with blood.
Yet as if this butchering of him had not been enough to make him a sacrifice,
a heavy gross-bodied persecutor stamped upon his breast with his feet,
endeavouring to beat the breath out of his body;
and when this persecutor had done his pleasure, he commanded the jailor to take him away,
and put him in some nasty hole for his entertainment and cure.

For the maintenance of his family,
he several times adventured his life upon the mighty waters, being master of a ship;
and many beyond the seas were partakers of his labours, and comforted by his ministry.
In his return home from visiting friends in Barbados, he fell sick;
and a little before his departure,
desiring to be remembered to his dear wife and children, he said, "`Well,
shall I lay down my head in peace upon the waters?
God is the God of the whole universe, and though my body sink,
I shall swim a-top of the waters.`"
Remembering his love to Friends in general, and some by name, he immediately sung,
being filled with the power of God,
"`The creating word of the Lord endures forever;`" and spoke to them who sat by,
and took several by the hand, exhorting them to fear God, and not to fear death.

He said, "`Friends at London would have been glad to see my face.
Tell them, I go to my Father and to their Father; to my God, and to their God.
Remember my love to my wife; she will be a sorrowful widow;
but let her not mourn in sorrow, for it is well with me.`"
He then took is leave of the Friends on board, saying, "`I see not one of you,
but wish you all well.`"
A Friend of New England asked him how it was with him: he said, "`I am perfectly well:
and mind my love to Friends in Rhode Island, and New England,
and to Friends in Barbados.
I went freely in tender love to them.`"
He uttered more sensible words; and about half an hour past four in the morning,
he departed this life, as if he had gone to sleep, being on 1st day of the Fourth month,
in the year 1675, on board the _Samuel_ of London,
in the latitude of 46 degrees and 36 minutes.

[.asterism]
'''

[.blurb]
=== Concerning A Child About Thirteen Years Old.

JOSEPH BRIGGINS, son of William Briggins of Bartholomew Close, in London,
having been a dutiful child to his parents, and ready to receive instruction,
was taken sick the 20th of the Fourth month.
Being, as it was thought, very near death; after he had lain silent for about an hour,
he began to appear full of joy and pleasantness, saying,
"`I shall praise the Lord, for he is only to be praised;`"
with many more words which they could not remember.
He said, in admiration,
"`Oh! I have never heard of any other God but thee, my holy One;
I have heard of thee, but now I see thee in glory.`"
Calling for his father and mother, he said, "`Father, father, oh! father,
oh! pure and glorious is my Saviour who hath appeared,
and hath taken me into his kingdom.
Oh! my eye hath seen his glory.`"
Then he prayed, "`Thou most glorious God,
great and wonderful things are brought to pass by thy own pure holy power,
by which thou hast revealed thy Son.
Oh! my King, let all people fear and stand in awe of thy power,
by which thou hast gathered many out of their sinful ways, into pure obedience to thee.
Thou hast given us a living knowledge.
Oh! pure, glorious, and holy God, let thy life reach unto all my dear friends,
and keep them that know thee sure and steadfast upon thy holy foundation, Christ Jesus,
my king, whose appearance is very glorious at this day,
and of his government no end is to be, but thousands of thousands, millions of thousands,
shall come to see, and be made partakers of his glorious, bright, shining day.`"

Another time he said, "`There are many ways and baptisms in the world; but oh! thou pure,
holy, holy One, we have known thy spiritual baptism into Christ Jesus my Lord,
by whom the living water we have known and felt.
Oh! it is indeed exceedingly pure, by which we have been washed from all our sins.
Oh! my King, thou wast slain, and by the virtue of thy pure blood we have this given.
Oh! that all may wait continually upon thee,
that they may be kept from all the deceitful ways of the world.`"
To those standing by he said, "`Mind and serve the Lord in your day,
for the holy truth received by you is the way in
which you must wait and obey;`" with much more.
Then he lay silent a little while; but again said,
"`The Lord hath taken me into his kingdom,
he hath discovered the fresh springs of his love to my soul.
All that know the Lord be obedient to his power,
and he will discover himself more to you, and you shall know more.
Thousands, thousands, millions, shall the Lord call.`"
With more words, after some time of silence.

Some who knew him very well, wondered to hear him speak as he did,
and said they had never heard such words come from him before.
He replied, "`The Lord hath fully made known that to my soul,
which I had some feeling of before.`"
The next day he was very earnest in prayer softly to himself, but some words were heard,
viz.: "`Oh! let all that know the pure truth, come and receive it, saith my soul.`"
He also sung of the olive tree, and of the fruit thereof, which he fed on,
and of his refreshment thereby.
He was asked what he meant by the olive tree.
He said, "`The tree of life.`"
Many more sayings he uttered before he departed to his everlasting rest,
which was on the 3rd day of the Fifth month, in the year 1675,
in the thirteenth day of his sickness.

[.asterism]
'''

ROBERT JECKEL, of Newcastle-upon-Tyne, in the county of Northumberland,
having a desire to visit George Fox, who was then at Swarthmore, set out on his journey,
in company with several friends,
but began to be sick the same day that he went from home,
and was ill at several places by the way; but still pressed forward,
and would not be satisfied to stay short of Swarthmore,
where he came the 2nd of the Fifth month, 1676,
and went to bed presently after he came in, and lay sick there nine days.
During his illness, these following words, with many more, were spoken by him, viz.:
"`No separation like unto this; soul separated from the body,
the spirit returning to God that gave it, and the body to the earth,
from whence it came.
Great has the lovingkindness of the Lord been to me, and not to me only,
but to all my dear friends who are faithful unto death.
I have always been faithful to the truth, as to what was manifested;
for God hath loved me from a child.`"
He added, spreading out his hands,
"`O! the blessed precious truth is above all the world,
and this is my living testimony I have to bear for the Lord, and his truth;
for always I loved truth, and preferred it before all the world; for truth is precious;
and to be valued before all things.
Therefore, oh! my dear friends! prize this precious truth, for it abides forever;
let nothing divert your minds from that service of truth you have,
for as that is kept to, truth answers truth in every heart.

As to the principle of truth, it will reign over all.
Though strange things may happen in this nation,
yet the Lord will crown his blessed truth, and his glory is over all.
Therefore, all my dear friends,
be faithful to that manifestation in your own particulars,
for a profession will stand none in stead,
unless they live in the life and power of truth.`"
Another time he said, "`Though I was persuaded to stay by the way, being indisposed,
before I came to this place, yet this was the place where I would have been,
and the place where I should be, whether I live or die.`"
George Fox visiting him,
exhorted him to offer up his soul and spirit to the
Lord who giveth breath and life to all,
and he takes it again; and he lifted up his hands and said, "`The Lord is worthy of it,
and I have done it.`"

George Fox then asked him if he could say, "`Thy will, O God, be done on earth,
as it is done in heaven;`" and he lifted up his hands and eyes, and cheerfully said,
he did it.
His mouth was often filled with praises to the Lord, exhorting those about him, saying,
"`Dear friends, dwell in love and unity together, and keep out of jars,
strife and contention, and be sure to continue faithful to the end,
and be not weary in well-doing; for this is a good testimony,
They that continue faithful to the end shall be saved.`"
He said, "`If any bad spirits speak evil of me when I am gone,
you are living witnesses`" (speaking to two friends present,
who were his neighbours) "`that I am an innocent man, and the Lord hath cleared me,
and I lay down my head in peace.
As to my wife, I give her freely up to the Lord; for she loveth the Lord,
and he will love her.
I have often told my dear wife, as to what we have in outward things,
it was the Lord`'s first before it was ours,
and in that I desire she may serve the truth to the end of her days.
And now, my dear friends, I commit you all to the Lord,
to be preserved and kept in his everlasting power, and bid you all everlastingly, yea,
everlastingly, farewell.
All is done, and to the Lord I leave you all; I commit you all, farewell.`"
Afterwards he said, "`Let us go hence in peace, for I shall go hence,
and be no more seen in mutability.`"

About two hours before he died, George Fox took him by the hand,
and asked him if he was satisfied of his seeing him.
He lifted up his hands, and with a gladness of heart, and smilingly,
praised the Lord and said, that his comfort flowed in as a flood.
George Fox asked him what he said; and he spoke those words over again.
And in much patience the Lord did keep him;
and he was in perfect sense and memory all the time of his weakness, often saying,
"`Dear friends give me up, and weep not for me, but be willing to bear a part with me,
// lint-disable obsolete-spellings "doings"
for I am content with the Lord`'s doings.`"
He often said that he had no pain; but went away by little and little,
lifting up his hands while he had strength, praising the Lord,
and made a comfortable end, on the 11th of the Fifth month, in the year 1676.
