== Chapter 3

[.chapter-synopsis]
* William Sixsmith
* Francis Patchet
* Christopher Bacon
* William Coale
* Sarah Beck
* John Matern
* Giles Barnardiston
* Alice Curwen
* Mary Samm
* Mordecai Hearn
* Sarah Camm
* Joseph Featherstone
* Judith Fell
* Jonah Lawson
* Elizabeth Braithwait
* David Barclay
* Joseph Fuller
* Robert Widders
* Ann Whitehead
* Barbara Scaif
* Mary Scaif

WILLIAM SIXSMITH, of Warrington in the county of Lancaster,
a young man about twenty-one years of age,
was in time of health a pattern of piety and good example.
When he was taken sick, he freely resigned up himself into the hand of the Lord,
refusing a physician, saying,
"`I am satisfied with the Lord`'s love;`" and that he knew his Redeemer lived, who,
if he pleased, was able to restore him to health, and if not, he was content.
In the time of his sickness he was very patient and quiet, often praising God.
A little before his death, calling his father,
with an innocent look he gave him his right hand, saying,
"`I desire thou wilt not be troubled.`"
And so laid down his life in peace, the 24th of the Seventh month, in the year 1677.

[.asterism]
'''

FRANCIS PATCHET, of Scotforth, in the county of Lancaster,
was a prisoner for his testimony against tithes:
the priest who prosecuted him removed him up to the Fleet prison in London,
where he died a prisoner.

In the time of his sickness he prayed, "`Lord God everlasting,
glory and honour forever be given to thy name.
Thou hast made way for thy redeemed as in ancient days,
when thou madest the sea dry land for thy people Israel to go through.
O glory and honour forever be unto thy name, who art unchangeable in all thy ways.
Thou madest man in thy own image, but he lost it through disobedience.
O Lord, in thy unspeakable love thou sent thy only Son Christ Jesus to redeem us again.
Oh! everlasting praises to thy name forever;`" with many other words.
Again he said, "`There is no God like our God;
he has given his Son a light into the world, and his salvation to the ends of the earth.
Oh! this blessed day wherein truth hath appeared: Oh!
England`'s glory.
Friends, obey the truth, love the truth, buy the truth, and sell it not: Oh!
Christ Jesus, the way, the truth, and the life.`"

Again he said, "`Glorious is the house of God, a house of holiness, a pure house,
a house of love, and her gates praise.
Our God is a consuming fire; he consumes all that is bad, all inpurity, all uncleanness,
all that is unholy, all that is wrong.`"
Thus he went on praising God for sending his Son for the redemption of man,
and spoke much of the Lord`'s making a way for his people in the nation of England.
At another time he said, "`My strength fails me.`"
On which, one by him replied, "`I hope the Lord doth not fail thee:`" he answered,
"`Through mercy the Lord never failed me;`" with
more concerning the Lord`'s building of Zion, etc.
Another time he said, speaking of the Lord, "`Oh! thy precious light,
in which I see thy glory: what will become of them that despise thy light?`"
Again, "`The false prophet and the hireling the Lord will cut down,
and all that resist his blessed work which he hath begun in this
nation of England;`" with more words of exhortation to friends,
and praises to God; and so finished his testimony, a prisoner for truth,
the 2nd of the Tenth month, in the year 1677.

[.asterism]
'''

CHRISTOPHER BACON, of Polling-hill, in Somersetshire,
was formerly a soldier in the king`'s army.
About the year 1656, some of the Lord`'s servants, called Quakers,
coming into that country to preach the gospel, he went to one of the meetings,
not to receive good, but rather to scoff and deride.
But, through the Lord`'s mercy, he was reached in his conscience,
and received the blessed truth in the love of it;
and afterwards received a dispensation of the gospel of Christ to preach,
and was a diligent labourer in the work of the ministry.
He travelled to London, and into Ireland and Wales,
and many parts of the nation of England, and several were convinced of the truth by him.

In the year 1678, he came into the county of Cornwall, and there fell sick,
being weak of body before, but had a good meeting of Friends in the town.
Upon his sick bed he desired a Friend by him to write comfortably to his wife,
if the Lord should take him away, and advise her,
that she bring up her children in the fear and counsel of the Lord;
and it was his fervent desire that his wife might be kept to truth; and +++[+++likewise]
for all friends.
And said, "`Since it is my lot,
after many great labours and travels for the service of truth,
to come here and lay down my body, I am well satisfied in God`'s will and pleasure,
and am at this time free and clear in my mind, willing to be with God.`"

Then making some pause, he said, "`O! friends, keep in mind your latter end,
and that will make you draw nigh to the Lord, and seek after him.`"
He further said, "`Friends,
take heed that you lose not an heavenly inheritance for an earthly.`"
The day before he died, being the First-day of the week,
he spoke to friends as they were going to meeting, minding his dear love to friends,
and said, "`The Lord`'s presence be amongst you,
for his presence hath attended me in all my labours, travels, sufferings, and exercises,
for his name`'s sake.`"
His end drawing near, and his body weak,
he continued to the last moment in sweet harmony, lifting up his hands,
and in much quietness and peace he gave up the ghost the 29th of the Tenth month,
in the year 1678, aged about fifty-five years.

[.asterism]
'''

WILLIAM COALE, of Maryland, in America,
was convinced of the blessed truth about the year 1657,
and was a man of an innocent and tender spirit, of true judgment,
and stood in the power and love of God against unrighteousness and false liberty;
and for true liberty in Christ Jesus, and for holiness, peace, and unity in the church.
He freely and tenderly preached the cross of Christ,
and was living and weighty in his testimony.
He suffered imprisonment in Jamestown prison, in Virginia, with George Wilson,
a Friend of Old England, who travelled into America to preach the gospel,
whom the magistrates of that town persecuted to death,
after they had cruelly beaten and whipped him, and kept him long in iron chains;
and the said William Coale was also much decayed in his body by that cruel imprisonment,
and never recovered it.

His visit to friends in Virginia was very serviceable to many,
some were turned to the Lord through his ministry,
and many were established in the blessed truth.
In the time of his sickness he was cheerful in spirit,
freely given up to the will of God, as a living man prepared to die, saying,
"`The living presence of the Lord is with me;`" with many words more of
the great satisfaction he had from the Lord concerning his peace,
saying, "`I bless the Lord, I have finished my course,
and I have nothing to do but to wait on the Lord to die.`"
So in a short time he departed very peaceably and quietly, about the year 1678.

[.asterism]
'''

SARAH BECK, wife of John Beck, of Dockra, in the county of Westmoreland,
was an innocent woman, and one that feared the Lord.
Even from a child, her heart was set to seek him and the prosperity of his truth,
and the welfare of all people; and her chiefest care was to serve and obey the Lord.
Being sick near unto death, it was thought she was dead, but recovering a little,
she said, "`I was well, I was very well, if I had gone.`"
And after that, she praised and magnified the name of God,
which much affected the hearts of many who were with her in her sickness.
She said, "`O Lord, thou hast satisfied my soul.
I desired that I might praise thee, and I am satisfied: honour,
glory and hallelujahs be to thee, thou God of my life.
I feel sweet peace and great joy: oh! the joy that is laid up for the righteous:
oh! who would not fear the Lord! who would not be faithful.`"

Taking her leave of her husband and her friends, one by one, she said,
with a cheerful countenance, "`I am near going; this sweet end will come;
it makes my heart glad when I remember my end;
it will be the happiest hour that ever came to me.`"
Some observing her to be in great pain and very sick, said one to another,
"`It is very hard;`" she answered, "`Nay, it is very easy, for the Lord sweetens it.
Oh! thou glorious God, thou hast satisfied my soul.
I am filled with thy pure presence;`" with these words,
"`that I may praise thee while I have breath and being!`" as indeed she did,
for even at the very hour of death she said,
"`Call in the family;`" and holding her husband by the hand,
made sweet melody in her heart, saying, "`Dear God,
what shall I render to thee for this evening sacrifice?`"
Thus she went on praising God till her natural strength failed,
and then turned her face to the pillow and said no more;
but died as if she had fallen asleep, being the thirteenth of the Sixth month,
in the year 1679.

[.asterism]
'''

JOHN MATERN was a German, and educated in the learning of the schools,
intending to be a priest.
But it pleased God to visit him, even in his own country, in the year 1674,
and his wife`'s father, Christopher Proham, who was a priest, was convinced also,
and was a faithful friend, and died in peace with God in England,
where they and their families came to live.

John Matern laboured about six years in great integrity,
instructing youth in the knowledge of the tongues,
and endeavoured to bring them to the fear of the Lord,
and knowledge of his blessed truth.
He lay sick about a week, and about four hours before he departed, at his desire,
they called the youth of the school into his bed-chamber,
where he had a meeting with the family, and he was filled with divine praises,
magnifying the great power of God; and his prayer was fervent,
that the Lord would carry on the good work begun among the children,
and prosper his truth daily everywhere.
He exhorted the children, as they sat around about him,
to be faithful in their measures to a little, and more should be added.

He gave thanks to God for many particular mercies, but more especially,
that he had received the knowledge of the everlasting truth,
and had walked uprightly therein; for which, he declared at that time,
that he had the testimony of a good conscience,
and was entering into eternal rest with the Lord.

He died in rest and peace on the 1st of the Seventh month, in the year 1680.

[.asterism]
'''

GILES BARNARDISTON, of Clare, in the county of Suffolk,
came of a family of great account in the world,
and had his education accordingly at the university,
and his natural parts were answerable thereto; but when he received the truth,
he saw not only the emptiness of those things, but of their way of worship also; and,
like Moses, chose rather to join with the poor suffering people of God, called Quakers,
than to enjoy the pleasures of sin for a season.
After he was converted, it pleased God to commit a dispensation of the gospel unto him,
and He laid a necessity upon him to preach the same;
which he faithfully performed to the day of his death,
not regarding the tenderness of his body so much, as to fulfill the will of God.

When he was about to enter upon an hard journey, or otherwise exercised, he would say,
"`That is but for a short time, and we shall have done in this world;
and I desire that I may be faithful to the end,
that I may enjoy that of the hand of the Lord, that I received the truth for.
If it had not been to obtain peace of conscience whilst I am in this world,
and hopes of everlasting rest with God in the world to come,
I would never have left the glory and pleasure of this world, which I had,
and might have had, a share of, with them that are in it.
Neither would I now leave my house and home, where I have a loving wife,
with all that a man, fearing God, needs to desire, if it was not to obey the Lord,
and to make known his truth unto others, that so they may come to be saved.
For this cause do I forsake father and mother, wife and estate;
and whosoever thinks otherwise of me,
with the rest of my faithful brethren whom God hath called into his work,
to declare his name and truth among the sons of men, they are all mistaken of us,
and I would they knew us better.`"
He continued faithful in the Lord`'s work to the end; and he was blessed in his labour,
for he turned many to righteousness.

It pleased the Lord to visit him with sickness, in his return from London to Chelmsford,
and his sickness was short; in which time he gave testimony to the goodness of God,
and said that the Lord was his portion, and that he was freely given up to die,
which was gain to him.
And on the 11th of the Eleventh month; in the year 1680, he departed in peace.

[.asterism]
'''

ALICE CURWEN, of Lancashire, with her husband Thomas Curwen,
travelled in the work of the ministry in divers parts of America, as New England,
New York, Long Island, Rhode Island, and Barbados; and after many long journeys,
and much service, returned home about the Third month, 1677.

The said Alice, being upon her dying bed,
was asked if she thought she should recover of her sickness; to which she answered,
"`I do not know what the Lord has to do; but I am freely given up to his will,
whether it be life or death; I am as clear as a child.`"
Another time, complaining of the unfaithfulness of some professing truth, she said,
"`But those who are faithful, the Lord will preserve them,
though they may meet with many trials and besetments, both inwardly and outwardly.`"
And again, "`All stand faithful for the Lord in their day,
and none need be afraid of death, for it will be easy to them as it is to me.`"
She often, in the time of her sickness, made melody to God in her heart, and said,
"`Oh! my heavenly Father, how hast thou filled my cup, and made it to overflow;
for I can do no less than bless and praise thy eternal name.`"

She often desired God`'s will might be done, whether it was life or death;
"`For,`" said she, "`to me to live is Christ, and to die is gain.`"
She exhorted friends to be diligent, and to know life and virtue in themselves;
"`For,`" said she, "`the time will come that words shall cease,
and life shall more arise;`" and said, if she lived she must declare it; and if she died,
she must leave it as a testimony for the Lord.
Toward the latter end of the last night she lived, her pain was great,
and she spoke to friends about her, saying, "`Pray to the Lord for me,
that he lay no more upon me than I am able to bear;
that I may not offend this good God.`"
And immediately she prayed to the Lord, and had a little ease,
and lay still as if she had been in a slumber, and so grew weaker,
and was sweetly carried through to the end.
She died in London in the year 1680.

[.asterism]
'''

MARY SAMM, daughter of John Samm, of Bedfordshire,
and grand-daughter of William Dewsbury, of Warwick, aged about twelve years,
being taken sick, and her aunt finding her under a concern of mind, asked her,
why she walked so often alone in the garden, when she was well,
for she would many times be weeping alone.
She replied, "`Dear aunt,
I am troubled for want of a full assurance of my eternal salvation.
Not any knows my exercise but the Lord alone,
what I have gone through since I came to Warwick.
It was begun before I came, but it was but a little.
This was my trouble, I thought I should not live long, and that if I did die,
I did not know whither my soul should go;
but I hope the Lord will give me satisfaction before I die.
It is but hope, and though but hope,
yet for this my soul shall praise his name forever.`"

The next day, having more assurance of her future happiness,
and some friends coming into her chamber, she said,
"`I have been twice in my days nigh to death,
but the Lord in his tender mercy prolonged my days,
that I might seek his face in the light of Christ,
and come to be acquainted with him before I go hence.`"
Also she said, "`If this distemper do not abate, I must die;
but my soul shall go to eternal joy;
eternal and everlasting life and peace with my God forever.`"
At another time, "`They that live longest, endure the greatest sorrow; therefore, O Lord,
if it be thy will, take me to thyself, that my soul may rest in peace with thee.`"
With many more good words.

The day following she desired all to go forth of the room.
After a considerable time, her mother and grandfather went in again, when she said,
"`I have now received full satisfaction of my eternal salvation.
It is now done, it is now done.`"
And after saying something to her mother, she said, "`I am very willing to die,
that the Lord may glorify his name this day,
in his will being done with me:`" often praying to the Lord,
to lay no more upon her than she was able to bear, saying, "`Help me, O my God,
that I may praise thy holy name forever.`"
Her grandfather advising her to stillness, she answered, "`Dear grandfather, I shall die,
and I cannot but praise the name of the Lord whilst I have a being.
I do not know how to do to praise him enough.`"
Her grandfather inquiring how she did, she replied, "`I have had no rest to-night,
nor today.
I did not know but I should have died this night, but very hardly I tugged through it;
but I shall die today, and a grave shall be made, and my body put into a hole,
and my soul shall go into heavenly joy, and into everlasting peace forevermore.`"

After more expressions, her aunt asked her if she thought she was upon her deathbed:
she replied, "`Yea, yea, I am upon my deathbed.
I shall die today, and I am very willing to die,
because I know it is better for me to die than to live.`"
After some time, and other expressions, she inquired the time of the day,
which being told, she said, "`I thought it was more.
I will see if I can have a little rest and sleep, before I die.`"
So she lay still, and had a sweet sleep, and awaked without complaint;
and then in a quiet, peaceable frame of spirit laid down her head the same day in peace,
being the 9th of the Second month, in the year 1680, in the twelfth year of her age.

[.asterism]
'''

MORDECAI HEARN was a young man whom the Lord in his mercy reached to in his tender years,
and called by his holy Spirit in his heart, and he hearkened to the call of the Lord,
so that he became a prepared vessel, by the Lord, for his use and service.
God opened his heart, and mouth also, sometimes, to declare of his goodness and mercy,
and speak to the praise of his grace in the congregations of his people,
until the twenty-third year of his age, when it pleased the Lord to accept of his mite,
offered in faithfulness and sincerity, and to cut his work short in this evil world,
and give him his heavenly crown of reward.

He was visited with illness, which brought him into a consumption;
and in his weakness and great affliction of body,
he said to some friends who stood by him, as he lay in bed, as follows:
"`Blessed be the Lord,
that ever he made me to remember my Creator in the days of my youth,
seeing old age is not likely to be my portion;
but a portion hath the Lord provided for me among the faithful,
in which my soul rejoices with you, dear friends; for this is our joy,
and the crown of our rejoicing.`"
Another time he said, "`Friends,
the Lord is wonderfully good to me in my sore affliction;
he comforteth me with his sweet presence,
which is more to me than all the fading things of this world.
Oh! it is good to trust in the Lord,
for he never faileth them that put their trust in him.`"
And so he lay in a sweet, quiet, and tender frame of spirit.

Many friends being about him, he exhorted them, with tears on his cheeks,
to follow the Lord fully, and to go on in his work and service,
and the Lord would be with them.
This he spoke in so living a sense of the Lord`'s power,
that those about him were much broken into tears, which, when he beheld, he,
with a sweet heavenly countenance said, "`Friends, weep not for me; it is well with me.
Death is no terror to me, for the sting thereof is taken away,
so that I am not afraid to die.
And although my body be laid in the dust, yet in this, dear friends,
remember that I am now going but a little before, and you must follow me.`"
And soon after these words were spoken, he raised himself upon his knees, being in bed,
and returned praises to the Lord for his goodness and
lovingkindness that was then shed abroad in their hearts.
He besought the Lord that he would be with his servants and handmaids;
and that he would prosper that work which he had begun.

At another time, a near relation came to visit him, whom he entirely respected and loved,
who had much lost his former condition in the truth,
to whom he spoke in much love and tenderness, saying,
"`Oh! that our portion might be together.
I fear thou despairest.
Oh! do not distrust the Lord, for he is all sufficient; he is able to restore thee:
but I fear thou dost distrust his mercy.
The thought of it is more grievous to me than all my afflictions.
Oh! that we should be separated; that grieves me.`"
Being full of pain, and weak, he groaned, saying,
"`Surely the Lord will release me in his time; surely the Lord will ease me of this pain,
for I am pained.
I do not desire to live here.`"

When he drew near to his departure, he awaked out of sleep or slumber; and soon after,
his mother discerning him to breathe short, said to his sister,
"`I think thy brother is now dying:`" and he, hearing her voice, spoke these words:
"`I am glad, I am glad; I go away with joy.`"
He called for his father, mother, and sister, to kiss them, and said, "`Weep not for me,
for I have peace with the Lord.`"
He lived some hours after, and lay praising him, saying,
"`The Lord is worthy to be waited upon; he will release me in his own time,`" etc.
Speaking to those about him, he said,
"`To outward appearance my time is but short in this world; but this I have to say,
the Lord hath been good to me in my pilgrimage,
and therefore be you faithful to the Lord in his requirings, to the end of your days,
and he will never leave you nor forsake you.`"
He quietly departed this life, the ninth day of the Seventh month, in the year 1681,
being twenty-three years and ten months old, at Sabridgworth in Hertfordshire.

[.asterism]
'''

SARAH CAMM, daughter of Thomas Camm, of Cam`'sgill, in Westmoreland,
and of Anne his wife, a child of nine years old,
was visited with sickness the 13th of the Seventh month, 1682.
She declared that she should be taken away by death, saying,
"`I am neither afraid nor unwilling to die,
but am freely given up thereto in the will of God.`"
When she saw her relations weep, she would say, "`Oh! do not so, do not so.`"
Being near death, her sickness increased; but she was very patient, only had deep sighs.
Her father asked her if she could not pray to the Lord for help; her answer was,
she could, and did pray.
She further said, it was her belief, that the Lord, the great God of heaven and earth,
would keep her, and preserve her soul, whatever might become of her body.

In the fifth day of her sickness,
being under more than usual exercise of mind and spirit,
after a little space she revived, and sat upright in her bed,
and with a cheerful countenance said as followeth, "`My sins are forgiven me,
and I shall have a resting place in heaven.`"
Then looking at her mother, she said, "`Oh! my mother,
there is also a place prepared for thee in heaven,
and thou shalt as certainly enjoy it as any here.
I do not,`" said she, "`desire my mother`'s death, or removal from you;
yet we shall meet in heaven in God`'s time.`"
Seeing her friends weep, she said, "`Oh! you should not do so; I am well, I am well.`"

Her father desired the company to withdraw,
lest they should trouble her but she soon called them in again, and said,
"`Shall I go down to the horrible pit?
Nay, the Lord hath redeemed my soul:`" and called her brother,
to whom she spoke very sensibly.
To her sister she said, "`Be content, for it is, and will be well with me.
I must go to a more fair place than ever my eyes beheld.
It will be well with me, and all that fear the Lord,
for we shall have everlasting joy in heaven,
when the wicked shall be tormented in hell.`"
Seeing her sister weep, she said, "`Do not cry, dear Mary, lest thou grieve the Lord:
be subject to the Lord`'s will in all things, and love and be faithful to the truth,
and do not forsake thy religion, whatever thou suffer for it.`"
And further said, "`I am satisfied with my religion.
I will not forsake it,
though I should be fed with the bread of adversity and water of affliction.
Oh! praises, praises to my God, and my Father.
Our Father, which art in heaven,
hallowed be thy name;`" and so said to the end of the Lord`'s prayer twice over;
and the third time till she came to that petition, "`Thy will be done on earth,
as it is done in heaven,`" which she spoke deliberately, signifying to those about her,
that they were all to mind that; "`For,`" said she,
"`I am freely given up to his blessed will in all things: praises to my God,
bless his name, O my soul.`"

Another time, her father having her in his arms, she said, "`Oh! my dear father,
thou art tender and careful over me, and hast taken great pains with me in my sickness,
but it availeth not, there is no help nor succour for me in the earth;
it is the Lord that is my health and physician,
and he will give me ease and rest everlasting.`"
Near her end she took leave of the family particularly, saying, with a pleasant voice,
"`Farewell, farewell unto you all, only farewell;`" signifying,
that now she had no more to say; and so went on praising the Lord,
and continued in a sweet frame till she died, wanting eleven days of nine years old.

She died the 18th of the Seventh month, in the year 1682.

[.asterism]
'''

JOSEPH FEATHERSTONE, of Crowland, in Lincolnshire,
was a man whom the Lord endued with much meekness, and he loved truth,
and to do the will of God.
In the time of his sickness he was freely resigned to the will of God,
saying to his wife, "`My dear, give me up to the will of the Lord,
for I can freely give up all.`"
When some of his friends came to visit him, he exhorted them to faithfulness, and said,
"`The Lord will make a dying-bed comfortable to you;`" that
though he felt much sickness and pain upon his body,
yet the refreshment he felt from the Lord made all his troubles easy.

He prayed that his wife and friends might be preserved
in God`'s holy fear and undefiled way,
to bear a testimony to the blessed truth to the end of their days.
The day before he died, being somewhat restless, his wife said, "`Dear heart,
thou art restless;`" he answered, with a cheerful countenance,
"`Dost thou not know where the weary go to rest?`"
and said, "`My rest and fellowship are with the Lord.`"
A little before his death, he rested a pretty while, and being asked how he did, he said,
"`I am well, blessed be the Lord;`" and desired his wife to be satisfied;
and then lifting up his hands, he said, "`O Lord, thou art the eternal God.`"
And so fell asleep in the Lord the 26th of the Ninth month, in the year 1682.

[.asterism]
'''

JUDITH FELL, a young woman twenty-four years of age, daughter of Thomas and Anne Fell,
near Ireby, in Cumberland, was never inclinable to vain company,
nor to pride nor lightness of carriage, but always was very sober,
and ready to be a good example to others,
so that she abundantly enjoyed the love of the Lord;
insomuch that on her sick-bed she was wonderfully filled, to the refreshment of others.
Her sickness increasing, which was at times very severe upon her,
some inquired of her how she did; she replied, "`I am well every way.
If I should live ever so long, it can never be better; for my heart is fully satisfied,
and my soul magnifies God, who is worthy forever.`"

Another time she requested her father not to desire her health,
for she said she felt that which was beyond all her weakness and sickness.
Another time she said the sting of death was removed,
and she felt victory over the grave; and so praised the Lord, saying,
"`Surely it is thou, O God, that lives and reigns, and must reign forever;
and they are ever blessed who serve thee, and fear thy name.
Thou, O God, reignest in the hearts of the sanctified, and thou hast sanctified my heart,
so that I can truly praise thy name.
Thou knowest, Lord, for what end thou hast cast me on this bed of sickness;
surely it is for the glory of thy name; therefore, Father, glorify thyself in me.`"
The day before she died, she said she saw that that day she was given to her friends;
and so continued quiet and easy in her spirit, and several times slept very sweetly.
At the end of that night her sickness increased, and she desired to see some friends;
and spoke words to their great refreshment.

The next day, after great fits of illness, she broke forth in praises, saying,
"`He is come that brings joy: Oh! the streams of his love run over all,
even to the skirts of the garment.
Now is the fountain set open for Judah and Jerusalem to bathe in.
Once more solace thyself, my soul, and delight thyself in thy Saviour;
for I feel his love and life run afresh in my soul,
so that now my spirit doth magnify him that lives forever.`"
Her distemper prevailing upon her, they thought that she would not have spoken any more;
but she lifted up her head and said, "`This is the way to rest;
this is the way to rest forever.`"
In a little time she drew her last breath, and ended her life comfortably,
in the twenty-fourth year of her age, in the year 1682.

[.asterism]
'''

JONAH LAWSON, son of Thomas Lawson, of Westmoreland, aged about fourteen years,
was a youth well inclined, of a peaceable spirit, and not known to tell a lie.
He was taken sick of the small-pox; and in his sickness,
his father putting him in mind of the difference betwixt this world and heaven,
where is nothing but joy, the lad answered, "`Ay, father,
I hope I have but little to answer for, and that I have a good conscience.
I have abhorred lying and swearing, and what I saw to be evil; and am willing to die,
if it be the Lord`'s pleasure, or to live to praise him.`"
His sister weeping, he said to her, "`Weep not, I hope we shall meet in a better place.`"
Soon after he uttered these words to the Lord:
"`The time thou hast appointed for me on earth; give me grace to praise thy name.`"
Presently after, as if answered from heaven, he said, "`O, sweet God.`"
A little before his departure, his father and sister being present, he said,
"`I am coming, I am coming.
I must yield, I must yield.`"
He died on the 23rd of the Twelfth month, in the year 1683, aged fourteen years.
After his death, his father found the following verses of Jonah`'s making, viz.:

[verse]
____
Humility the spring of virtue is;
Humbling thyself, virtue thou canst not miss.
Delight in virtue; vice be sure to shun:
He`'s happy that a virtuous course doth run.
____

[.asterism]
'''

ELIZABETH BRAITHWAIT, a young maid of seventeen years of age,
died in prison for the testimony of a good conscience, at Kendal, in Westmoreland.
From a child, God by his grace inclined her heart to love, fear, and serve him;
and she was truly obedient to her parents, sober and chaste in her life and conversation,
kind to all, and of a meek and quiet spirit.
She was, with several others of the people called Quakers, taken up by a warrant,
dated the 25th of the Fifth month, 1684,
for not going to church (so called) and carried to Kendal jail.
After some time, she had liberty for a few days to be at her brother`'s house;
but complaint being made against the keeper, she was sent for,
and she was not easy till she returned to prison, for she said, "`That is my place,
and my present home; there I have most peace and content.`"

About two months after her commitment, viz.: the 17th of Seventh month,
she was taken sick in prison, and her mother coming to visit her,
asked if she had a mind to go home; she replied, "`No, no; I am at home in my place,
to my full content; and if my God so order it that I be dissolved,
I had rather die here than in any other place.
I am glad that I got to this place before I began to be sick:
here I have peace and true content in the will of God, whether life or death.
I am only grieved that there should be so little
tenderness or pity in the hearts of my persecutors,
to keep such a poor young one as I am in prison.
The Lord forgive them, I can freely.`"
She further said, "`that her imprisonment was by the permission of the Almighty,
who is greater, and above the greatest of my persecutors,
who I believe will shortly set me free from these, and all other bonds,
over all their heads; and in his peace, in true patience I possess my soul,
and am contented, if it be his will, to be dissolved.`"

A friend asked her why she was so willing to die.
"`Oh,`" said she, "`I have seen glorious sights of good things.`"
The friend queried, "`What things;`" she answered,
"`They are so excellent and glorious that it is not utterable;
and now I have nothing but love and good-will to all.`"
But more especially she was glad in the love and unity she felt with friends;
"`with whom,`" said she, "`I have been often refreshed in our meetings together,
with the refreshment that comes from the presence of the Lord.
Oh! the good evening meetings we have had.`"
Another time she said to her mother,
"`They say that we shall spend all our riches with lying here in prison; nay,
our riches are durable, and our treasure hidden, laid up in heaven.`"
Her mother seeing her lie under great weight of sickness, would sometimes weep;
but she was always troubled at it, and said, "`Dear mother, do not weep,
but resign me freely up into the hand of the Lord.
Weep not for me, for I am well, Christ my Redeemer is with me.`"
And to her sister she said, "`Come sister, lie down by me, do not sorrow for me,
I am well content to live or die; for my God hath blessed me, and will bless me,
and his blessings rest upon me.`"

A little before she departed, her speech failed; after which she would sing in her heart;
lifting up her hands with a cheerful countenance,
and taking her friends by the hand with great affection,
so fell asleep in the Lord on the 28th of the Seventh month, in the year 1684,
in the seventeenth year of her age.

[.asterism]
'''

DAVID BARCLAY, of Urie, in the kingdom of Scotland, father of Robert Barclay,
the great and eminent apologist for true Christianity,
was convinced of truth in the Seventh month, in the year 1666,
being then in the fifty-sixth year of his age; and abode in the truth,
and in constant unity with the faithful friends thereof to the end;
having suffered the spoiling of his goods, and many other indignities,
besides several tedious imprisonments, after the sixty-sixth year of his age.

In the latter end of the Seventh month, 1686,
being past the seventy-sixth year of his age, he was taken with a fever,
which continued upon him for two weeks;
during which time he signified that he had a quiet and contented mind,
freely resigned up to the will of God.
About two days before he died, being troubled with the gravel, and much pain,
in an agony he said, "`I am going now;`" but instantly checking himself, added,
"`but I shall go to the Lord, and be gathered to many of my brethren,
who are gone before me.`"
Upon the 11th day of the Eighth month, between two and three in the morning,
he growing weaker, his eldest son drew nigh to him, and he said, "`Is this my son?`"
Robert answered, "`Yea;`" signifying his travail,
that he that loved him might be near him to the end.
To which he answered,`" The Lord is nigh.`"
Repeating it once again, he said, "`You are my witnesses in the presence of God,
that the Lord is nigh.`"

A little after he said, "`The perfect discovery of the day-spring from on high;
how great a blessing it hath been to me and my family!`"
Robert Barclay`'s wife desiring to know if he would have something to wet his mouth,
he answered, "`It needs not.`"
She said it would refresh him; he then laid his hand upon his breast,
saying he had that inwardly that refreshed him: and after a little while he added,
"`The truth is over all.`"
He took his eldest son Robert to him, and blessed him,
and prayed God he might never depart from the truth.
When his son`'s eldest daughter came near, he said, "`Is this Patience?
let patience have its perfect work in thee.`"
And after kissing his son`'s other four children, he laid his hands upon them,
and blessed them.
Perceiving one by, (who was not a friend in the truth,) weeping much,
he wished she might come to the truth, bidding her not weep for him, but for herself.

A sober man, an apothecary that waited upon him in his sickness, coming near,
he took him by the hand, saying, "`Thou wilt bear me witness,
that in all this exercise I have not been curious to tamper, nor to pamper the flesh.`"
The man said, "`Sir,
I can bear witness that you have always minded the better and more substantial part,
and rejoice to see the blessed end the Lord is bringing you to.`"
He replied, "`Bear a faithful and true witness;
yet it is the life of righteousness (repeating these
words twice over) that we bear testimony to,
and not empty profession.`"
He, supposing a man that was by him to be a carpenter, said to his son,
"`See thou charge him to make no superfluity upon my coffin.`"

About three in the afternoon there came several friends from Aberdeen to visit him,
and he took them by the hand, and said they were come in a seasonable time.
And after some words were spoken, and Patrick Livingston had prayed,
which ended in praises, he held up his hands, and said, "`Amen, Amen, Amen, forever.`"
After they stood up, looking at him, he said,
"`How precious is the love of God among his children, and their love one to another.
Hereby shall all men know that you are my disciples, if you love one another.
How precious a thing it is to see brethren dwell together in love!
My love is with you; I leave it among you.`"

Perceiving some of his friends to weep, he said, "`Dear friends, all mind the inward man,
heed not the outward; there is one that doth regard, the Lord of Hosts is his name.`"
After he had heard the clock strike three, in the afternoon, he said,
"`Now the time comes.`"
And a little after he was heard to say, "`Praises, praises, praises to the Lord:
let now thy servant depart in peace.
Into thy hands, O Father, I commit my soul, spirit, and body.
Thy will, O Lord, be done on earth as it is in heaven.`"
A little after five in the morning, on the 12th day of the Eighth month,
in the year 1686, he fell asleep like a lamb, in remarkable quietness and calmness;
there being standing about him, to behold his end, about twenty persons,
who were witnesses to what is above said.

[.asterism]
'''

JOSEPH FULLER, a young man about twenty-five years of age, son of Abraham Fuller,
of Queen`'s County, in Ireland, having been sick three days,
his father desired some relations to sit down,
and wait upon the Lord in Joseph`'s chamber.
He being asked if it was not tiresome to sit so long, his answer was,
"`I bless the Lord for this opportunity.`"
His brother`'s wife asking him how he did, he said, "`I have had a wearisome night;
but I have had joy in the presence of the Lord.`"
Next night he sang praises to the Lord, and said to his sister, "`Never,
since I was born, such words came from me; this is from the Lord.`"
More he said to the same purpose to his father, and further said to him,
"`Tell all my brothers and sisters,
that they take their minds from the things of this world,
and have their minds fixed upon the Lord.`"
Taking his father by the hand, he said, "`Farewell, farewell.`"

Afterwards he said, "`Well, I thought to have gone when I bid you farewell,
(his sister being also with his father,) but I shall not go yet.`"
A little while after he said to his sister, "`Jane, I am long a dying.`"
About a quarter of an hour before he drew his last breath, he said to his sister,
"`See what hour it is.`"
She replied, "`It is seven.`"
Then he asked her, lies my head right for dying?
If it doth not lie right, do thou lay it right.`"
She told him it did lie right.
So he lay until he drew his last breath,
which was a quarter past the seventh hour in the morning,
on the 17th of the Seventh month, in the year 1686.
Aged about twenty-five years.

[.asterism]
'''

ROBERT WIDDERS, born in Upper Kellet, in Lancashire, of honest parents,
was a seeker after the Lord, and the knowledge of his way;
and when George Fox visited those parts, he received the knowledge of the truth,
which was in the year 1652.
He was a faithful servant of Christ, and laboured for the good of souls; and to that end,
in the year 1671, he travelled with George Fox in divers parts of America, as Barbados,
Virginia, Maryland, Jamaica, Long Island, Rhode Island, etc.,
and great perils they went through both by sea and land, and in the wilderness,
and lying in the woods, in danger of wild beasts, and through all the Lord supported him,
and kept him faithful to the end.

He was many times concerned to go to the public places
of worship to call the people to repentance,
for which he endured hard sufferings, as at Coldbeck steeple-house,
where the people threw him down among the seats,
afterwards dragged him out into the yard, and threw him on the ground,
punching and beating him so cruelly, that the blood gushed out at his mouth,
and he lay for dead.

For speaking to the people at Acton steeple-house, he was sent to Carlisle jail,
where he lay in a dungeon among thieves a long time,
and was not suffered to come out day nor night, till he was released.
At Lamplough steeple-house they tore the clothes upon his back,
and the hair off his head; and in Bishop Aulkland,
speaking to the people as he passed through the town, they stoned him with stones,
which very sorely bruised his head.

He afterwards travelled into Scotland with George Fox,
and there went to a steeple-house called New Munckland, besides many other places,
where in the fear of God, and love to the people`'s souls,
he was constrained to direct them to the word of God in their hearts.
Through all which sufferings the Lord kept and preserved him by his power,
blessed be his everlasting name forever.

Also, for his faithfulness in his testimony against tithes,
and for the true worship of God in spirit and truth, he had much spoil of his goods;
but when his cattle, corn, and household goods were as it were by wholesale swept away,
he was not in the least dejected nor concerned, knowing well for what he suffered:
his loss on these accounts was of considerable value.

He was faithful, noble and valiant for God`'s truth, over all its gainsayers;
though he was not large in declaration, yet he was large in integrity and zeal,
and was endowed with a word of wisdom, and in discerning and sound judgment,
and gave good advice and admonition to friends,
for establishing them in the faith wherever he came;
and the Lord prospered his work in his hand.

During the time of his sickness he was in a resigned frame of mind,
given up to the will of God, and spoke of the mercies of God to his church, saying,
"`God will comfort Zion, and repair her decayed places,
and make her desert as a paradise, and her wilderness as a garden of the Lord:
mirth and joy shall be found there, thanksgiving and the voice of praise.`"
At another time, speaking of his own experience,
he said that the work of righteousness is peace,
and the effect of righteousness is quietness and assurance forever.
He would often upon his deathbed say his heart was filled with the love of God;
and that there was nothing betwixt him and the Lord.
Saying to the Lord, "`Thou hast taught me the way of life, and makest me full of life,
and makest me full of joy with thy countenance.`"
His love to God, and good-will to his brethren,
filled his heart with tender and heavenly comfort,
so that within two hours before his death, he discoursed sensibly with friends about him,
and passed quietly and patiently away, in the First month 1686,
after he had been a believer in the truth thirty-four years,
being then in the sixty-eighth year of his age.

[.asterism]
'''

ANN WHITEHEAD, wife of George Whitehead, of London,
was an early believer in the blessed truth.
In the year 1656 she travelled on foot about two hundred miles, into Cornwall,
to visit George Fox and other Friends in Launceston prison, in that county;
and in that journey convinced many people, some of whom were of account;
and in her return confirmed and established several who were newly convinced.
She continued a faithful woman to the end,
and was very serviceable in the church of Christ, not only in respect to her ministry,
but also to the poor widows and orphans, and to the sick, whom she did truly consider,
and spared not herself to serve them who were in distress,
so that nothing might be wanting.

In the year 1686, finding herself indisposed in health,
she went a few miles out of London to a friend`'s house, where, continuing weak,
about four days before her decease, she declared in the presence of several, saying,
"`Friends, I would not have you too much concerned about me; as to my going hence.
I am in the hand of the Lord.
I desire the God of peace and love may be among all Friends,
and that they may be kept in love, and peace, and concord,
unto which we were gathered in the beginning;
and that the same that gathered us in the beginning,
may always preserve Friends in the spirit of love, and of the same mind:
as the God of love and peace may please to dispose of me, I am content in his will.`"
Her ancient friend, Mary Stout of Hartford, visiting her,
and she being asked if she knew her, replied, "`Yes, very well; it is Mary Stout.
I have my memory very well, and my understanding is clear, though I am very weak;
but I am given up to the will of the Lord, whether to die or live;
for I have been faithful to him in what I knew, both in life and death.`"

When she discovered any friends to be troubled, she would say,
"`There is no cause for you to be troubled or concerned, for I am well, and in peace,
and have nothing to do.`"
Besides the many seasonable, tender and Christian exhortations and counsels,
which on her dying-bed she gave, in the love of God, to particular friends,
some friends from London coming to visit her, she said,
"`What! do you come on purpose to see me!
I take it as an effect of the love of God; and I pray God bless your children.`"
Another time to one of the same friends, she said, "`Remember me to all friends.
I pray God bless your families, and if I never see thy face more, it is well with me.
God doth know my integrity, and how I have been, and walked before him;
and I am in charity with all Friends; and be not over careful, or troubled for me,
but be retired and quiet.`"

The evening before she died she said to her husband, George Whitehead,
"`The Lord is with me; I bless his name; I am well.
It may be you are afraid I shall be taken away; and if it be,
the will of the Lord be done.
Do not trouble yourselves, nor make any great ado about me; but, my dear, go to bed,
go to rest; and if I should speak no more words to thee,
thou knowest the everlasting love of God.`"
Another time, said she had done with all things in this life;
that she had nothing troubled her, but was at true peace and ease every way.
And but a few hours before she departed, said, "`Though I am in a dying condition,
yet it is a living death; and though weakness doth seize on my body,
yet my understanding and sense is as perfect and clear as when I was in perfect health.`"
And so, in true love and charity with all,
she quietly departed this life on the 27th of the Fifth month, in the year 1686.

[.asterism]
'''

BARBARA SCAIF, daughter of William Scaif and Isabel his wife, of Blackside, near Appleby,
in the county of Westmoreland, with her sister Mary,
were both taken sick on the 30th day of the First month, 1686,
within one and the same hour, of the small-pox; and were both of them dutiful children,
fearing God, and making profession of the principle of light and life in Christ Jesus,
to which the people called Quakers bear testimony.

At the beginning of their sickness, divers of the neighbours came to visit them;
but Barbara said, "`Mother, suffer but a few to stay.
When they have seen us, desire them to go into the house,
for we have no need of such empty talk as is used amongst too many.
We would be quiet,
that we may pray to the Lord to forgive us the faults we have committed;
and if he spare us our lives at this time, I hope and believe we shall amend,
and have a care of displeasing the Lord while we live.`"
About the seventh day of her sickness she prayed to the Lord, saying, "`O, Almighty God!
I cry to thee; blot out all my transgressions, O Lord, and all my sins;
let them come no more into thy remembrance.
I beg it of thee, in the name of Jesus Christ, with all my soul,
and with all my strength; and let thy favourable countenance be upon me.`"

She also prayed that the Lord would confirm and strengthen her weak sister,
to give up herself freely, as she blessed the Lord she herself had done;
and then prayed for her parents; and many supplications besides, for a considerable time,
in the presence of several people that were not called Quakers, who said,
"`How can any die better than she is like to do?`"
To her brother she said, "`Be faithful to the Lord, and to thy religion,`" etc.
Being asked if she could freely part with her dear relations, her answer was,
"`I can freely part with, and leave them all,
for the enjoyment of the comfort and happiness which my soul is made sensible
of;`" and praised the Lord for the riches of his grace and comfort that
she had received from him to her immortal soul.

Being pressed to receive some meat, she said, "`Do not trouble me with meat,
for if thereby you think to keep me, it is all in vain, for I must die and leave you.
Neither would I desire to live for all the world;
for to be with the Lord is better than ten thousand worlds,
with whom I shall rest forevermore, even with God and his saints,
his faithful people and servants: glory to his name forevermore.`"
In her sickness she manifested great love to her parents,
and also to her sick sister Mary, saying, "`Go to her, do not stay with me,
whatever may befall me; that too sharp sickness may not fall on her,
until she know her peace with God.`"
To her brother she gave religious counsel, saying, "`Love the Lord with all thy heart,
and with all thy soul, all thy life-time; love not the world,
nor the pleasures thereof.`"
All the time of her sickness she was tender in her spirit, and circumspect,
not an unbecoming word proceeded out of her mouth; kind and pitiful to those about her,
not so much concerned at her own sickness, as for them who attended her,
considering the trouble they had in helping her.

That day she had lain a month sick (being much like
as she had been for three weeks before),
she was very cheerful, and able to express herself, and said to her mother,
"`What thinkest thou of this forenoon?`"
Her mother asked her what she meant: she replied,
"`It will go far in my time in this world, for the Lord will ease me ere long,
take away all my pain, and wipe away all tears from mine eye.
Call in my father (said she) that he may see my departure.`"
Her father being come, he said, "`Barbara, how dost thou?`"
She replied, "`I am ready to leave this world; therefore, father and mother, be content,
and bear me company a little while.`"
And about the first hour in the afternoon she departed this life,
as if she had fallen asleep, on the 27th of Second month, in the year 1686.

[.asterism]
'''

MARY SCAIF was elder sister to the aforesaid Barbara,
taken sick the same hour that she was,
and for whom her sister Barbara had been often tenderly concerned in supplication to God,
to give her the knowledge of his peace that hath no end.
She lived about two weeks after her said sister, her sickness being also the small-pox;
and in the Lord`'s time, who keepeth covenant, and shows mercy,
and giveth the spirit of supplication and prayer to them that believe,
he gave her a clear understanding, and she prayed unto God as followeth: "`O great God,
Jehovah, of heaven and earth, whose splendour filleth heaven,
and thy wonders fill the earth, have mercy upon me thy hand-maid,
who am as a worm before thee, yet part of thy creation.
Lord, help my weak soul, revive my drooping spirit:
by thy consoling presence strengthen my faith, I beseech thee,
and help me through this exercise.
I beseech thee, Lord, that thy will may be done in earth,
as it is done in heaven;`" and continued in prayer a considerable time,
supplicating for a willing mind, to resign herself up to God.

She was much inclined from a child to read the holy Scriptures;
and she often spoke of Job, David, and others of God`'s servants in former ages.
"`And now,`" said she, "`I do know God`'s love to be the same to me as it was to them,
so that I am neither afraid nor unwilling to die; for God blotteth out my transgressions,
and lays nothing to my charge,
and I do believe there is a place prepared for me in heaven.
And, dear mother, do what thou canst not to sorrow.
My love is great to thee, and my advice is, that you go and live near some good meeting,
and bring up my brother amongst friends.`"
Her sister being dead, she spoke of her own death also,
and was satisfied that her soul should ascend up to God in heaven, "`where,`" said she,
"`I believe my sister Barbara`'s soul is ascended, to rest with the Lord forever.`"
Her sickness increasing, she grew weaker,
and departed this life on the 13th of the Third month, in the year 1686.
