== Chapter 4

[.chapter-synopsis]
* David Barclay
* Joseph Fuller
* Robert Widders
* Ann Whitehead
* Barbara Scaif
* Mary Scaif
* Amariah Drewet
* Benjamin Padley
* Sarah Featherstone
* George Gray
* George Fox
* Joan Vokins
* Robert Lodge
* Stephen Crisp
* Gulielma Maria Penn
* Patrick Livingston
* Andrew Sowle

DAVID BARCLAY, of Urie, in the kingdom of Scotland, father of Robert Barclay,
the great and eminent apologist for true Christianity,
was convinced of truth in the Seventh month, in the year 1666,
being then in the fifty-sixth year of his age; and abode in the truth,
and in constant unity with the faithful friends thereof to the end;
having suffered the spoiling of his goods, and many other indignities,
besides several tedious imprisonments, after the sixty-sixth year of his age.

In the latter end of the Seventh month, 1686,
being past the seventy-sixth year of his age, he was taken with a fever,
which continued upon him for two weeks;
during which time he signified that he had a quiet and contented mind,
freely resigned up to the will of God.
About two days before he died, being troubled with the gravel, and much pain,
in an agony he said, "`I am going now;`" but instantly checking himself, added,
"`but I shall go to the Lord, and be gathered to many of my brethren,
who are gone before me.`"
Upon the 11th day of the Eighth month, between two and three in the morning,
he growing weaker, his eldest son drew nigh to him, and he said, "`Is this my son?`"
Robert answered, "`Yea;`" signifying his travail,
that he that loved him might be near him to the end.
To which he answered,`" The Lord is nigh.`"
Repeating it once again, he said, "`You are my witnesses in the presence of God,
that the Lord is nigh.`"

A little after he said, "`The perfect discovery of the day-spring from on high;
how great a blessing it hath been to me and my family!`"
Robert Barclay`'s wife desiring to know if he would have something to wet his mouth,
he answered, "`It needs not.`"
She said it would refresh him; he then laid his hand upon his breast,
saying he had that inwardly that refreshed him: and after a little while he added,
"`The truth is over all.`"
He took his eldest son Robert to him, and blessed him,
and prayed God he might never depart from the truth.
When his son`'s eldest daughter came near, he said, "`Is this Patience?
let patience have its perfect work in thee.`"
And after kissing his son`'s other four children, he laid his hands upon them,
and blessed them.
Perceiving one by, (who was not a friend in the truth,) weeping much,
he wished she might come to the truth, bidding her not weep for him, but for herself.

A sober man, an apothecary that waited upon him in his sickness, coming near,
he took him by the hand, saying, "`Thou wilt bear me witness,
that in all this exercise I have not been curious to tamper, nor to pamper the flesh.`"
The man said, "`Sir,
I can bear witness that you have always minded the better and more substantial part,
and rejoice to see the blessed end the Lord is bringing you to.`"
He replied, "`Bear a faithful and true witness;
yet it is the life of righteousness (repeating these
words twice over) that we bear testimony to,
and not empty profession.`"
He, supposing a man that was by him to be a carpenter, said to his son,
"`See thou charge him to make no superfluity upon my coffin.`"

About three in the afternoon there came several friends from Aberdeen to visit him,
and he took them by the hand, and said they were come in a seasonable time.
And after some words were spoken, and Patrick Livingston had prayed,
which ended in praises, he held up his hands, and said, "`Amen, Amen, Amen, forever.`"
After they stood up, looking at him, he said,
"`How precious is the love of God among his children, and their love one to another.
Hereby shall all men know that you are my disciples, if you love one another.
How precious a thing it is to see brethren dwell together in love!
My love is with you; I leave it among you.`"

Perceiving some of his friends to weep, he said, "`Dear friends, all mind the inward man,
heed not the outward; there is one that doth regard, the Lord of Hosts is his name.`"
After he had heard the clock strike three, in the afternoon, he said,
"`Now the time comes.`"
And a little after he was heard to say, "`Praises, praises, praises to the Lord:
let now thy servant depart in peace.
Into thy hands, O Father, I commit my soul, spirit, and body.
Thy will, O Lord, be done on earth as it is in heaven.`"
A little after five in the morning, on the 12th day of the Eighth month,
in the year 1686, he fell asleep like a lamb, in remarkable quietness and calmness;
there being standing about him, to behold his end, about twenty persons,
who were witnesses to what is above said.

JOSEPH FULLER, a young man about twenty-five years of age, son of Abraham Fuller,
of Queen`'s County, in Ireland, having been sick three days,
his father desired some relations to sit down,
and wait upon the Lord in Joseph`'s chamber.
He being asked if it was not tiresome to sit so long, his answer was,
"`I bless the Lord for this opportunity.`"
His brother`'s wife asking him how he did, he said, "`I have had a wearisome night;
but I have had joy in the presence of the Lord.`"
Next night he sang praises to the Lord, and said to his sister, "`Never,
since I was born, such words came from me; this is from the Lord.`"
More he said to the same purpose to his father, and further said to him,
"`Tell all my brothers and sisters,
that they take their minds from the things of this world,
and have their minds fixed upon the Lord.`"
Taking his father by the hand, he said, "`Farewell, farewell.`"

Afterwards he said, "`Well, I thought to have gone when I bid you farewell,
(his sister being also with his father,) but I shall not go yet.`"
A little while after he said to his sister, "`Jane, I am long a dying.`"
About a quarter of an hour before he drew his last breath, he said to his sister,
"`See what hour it is.`"
She replied, "`It is seven.`"
Then he asked her, lies my head right for dying?
If it doth not lie right, do thou lay it right.`"
She told him it did lie right.
So he lay until he drew his last breath,
which was a quarter past the seventh hour in the morning,
on the 17th of the Seventh month, in the year 1686.
Aged about twenty-five years.

ROBERT WIDDERS, born in Upper Kellet, in Lancashire, of honest parents,
was a seeker after the Lord, and the knowledge of his way;
and when George Fox visited those parts, he received the knowledge of the truth,
which was in the year 1652.
He was a faithful servant of Christ, and laboured for the good of souls; and to that end,
in the year 1671, he travelled with George Fox in divers parts of America, as Barbados,
Virginia, Maryland, Jamaica, Long Island, Rhode Island, etc.,
and great perils they went through both by sea and land, and in the wilderness,
and lying in the woods, in danger of wild beasts, and through all the Lord supported him,
and kept him faithful to the end.

He was many times concerned to go to the public places
of worship to call the people to repentance,
for which he endured hard sufferings, as at Coldbeck steeple-house,
where the people threw him down among the seats,
afterwards dragged him out into the yard, and threw him on the ground,
punching and beating him so cruelly, that the blood gushed out at his mouth,
and he lay for dead.

For speaking to the people at Acton steeple-house, he was sent to Carlisle jail,
where he lay in a dungeon among thieves a long time,
and was not suffered to come out day nor night, till he was released.
At Lamplough steeple-house they tore the clothes upon his back,
and the hair off his head; and in Bishop Aulkland,
speaking to the people as he passed through the town, they stoned him with stones,
which very sorely bruised his head.

He afterwards travelled into Scotland with George Fox,
and there went to a steeple-house called New Munckland, besides many other places,
where in the fear of God, and love to the people`'s souls,
he was constrained to direct them to the word of God in their hearts.
Through all which sufferings the Lord kept and preserved him by his power,
blessed be his everlasting name forever.

Also, for his faithfulness in his testimony against tithes,
and for the true worship of God in spirit and truth, he had much spoil of his goods;
but when his cattle, corn, and household goods were as it were by wholesale swept away,
he was not in the least dejected nor concerned, knowing well for what he suffered:
his loss on these accounts was of considerable value.

He was faithful, noble and valiant for God`'s truth, over all its gainsayers;
though he was not large in declaration, yet he was large in integrity and zeal,
and was endowed with a word of wisdom, and in discerning and sound judgment,
and gave good advice and admonition to friends,
for establishing them in the faith wherever he came;
and the Lord prospered his work in his hand.

During the time of his sickness he was in a resigned frame of mind,
given up to the will of God, and spoke of the mercies of God to his church, saying,
"`God will comfort Zion, and repair her decayed places,
and make her desert as a paradise, and her wilderness as a garden of the Lord:
mirth and joy shall be found there, thanksgiving and the voice of praise.`"
At another time, speaking of his own experience,
he said that the work of righteousness is peace,
and the effect of righteousness is quietness and assurance forever.
He would often upon his deathbed say his heart was filled with the love of God;
and that there was nothing betwixt him and the Lord.
Saying to the Lord, "`Thou hast taught me the way of life, and makest me full of life,
and makest me full of joy with thy countenance.`"
His love to God, and good-will to his brethren,
filled his heart with tender and heavenly comfort,
so that within two hours before his death, he discoursed sensibly with friends about him,
and passed quietly and patiently away, in the First month 1686,
after he had been a believer in the truth thirty-four years,
being then in the sixty-eighth year of his age.

ANN WHITEHEAD, wife of George Whitehead, of London,
was an early believer in the blessed truth.
In the year 1656 she travelled on foot about two hundred miles, into Cornwall,
to visit George Fox and other Friends in Launceston prison, in that county;
and in that journey convinced many people, some of whom were of account;
and in her return confirmed and established several who were newly convinced.
She continued a faithful woman to the end,
and was very serviceable in the church of Christ, not only in respect to her ministry,
but also to the poor widows and orphans, and to the sick, whom she did truly consider,
and spared not herself to serve them who were in distress,
so that nothing might be wanting.

In the year 1686, finding herself indisposed in health,
she went a few miles out of London to a friend`'s house, where, continuing weak,
about four days before her decease, she declared in the presence of several, saying,
"`Friends, I would not have you too much concerned about me; as to my going hence.
I am in the hand of the Lord.
I desire the God of peace and love may be among all Friends,
and that they may be kept in love, and peace, and concord,
unto which we were gathered in the beginning;
and that the same that gathered us in the beginning,
may always preserve Friends in the spirit of love, and of the same mind:
as the God of love and peace may please to dispose of me, I am content in his will.`"
Her ancient friend, Mary Stout of Hartford, visiting her,
and she being asked if she knew her, replied, "`Yes, very well; it is Mary Stout.
I have my memory very well, and my understanding is clear, though I am very weak;
but I am given up to the will of the Lord, whether to die or live;
for I have been faithful to him in what I knew, both in life and death.`"

When she discovered any friends to be troubled, she would say,
"`There is no cause for you to be troubled or concerned, for I am well, and in peace,
and have nothing to do.`"
Besides the many seasonable, tender and Christian exhortations and counsels,
which on her dying-bed she gave, in the love of God, to particular friends,
some friends from London coming to visit her, she said,
"`What! do you come on purpose to see me!
I take it as an effect of the love of God; and I pray God bless your children.`"
Another time to one of the same friends, she said, "`Remember me to all friends.
I pray God bless your families, and if I never see thy face more, it is well with me.
God doth know my integrity, and how I have been, and walked before him;
and I am in charity with all Friends; and be not over careful, or troubled for me,
but be retired and quiet.`"

The evening before she died she said to her husband, George Whitehead,
"`The Lord is with me; I bless his name; I am well.
It may be you are afraid I shall be taken away; and if it be,
the will of the Lord be done.
Do not trouble yourselves, nor make any great ado about me; but, my dear, go to bed,
go to rest; and if I should speak no more words to thee,
thou knowest the everlasting love of God.`"
Another time, said she had done with all things in this life;
that she had nothing troubled her, but was at true peace and ease every way.
And but a few hours before she departed, said, "`Though I am in a dying condition,
yet it is a living death; and though weakness doth seize on my body,
yet my understanding and sense is as perfect and clear as when I was in perfect health.`"
And so, in true love and charity with all,
she quietly departed this life on the 27th of the Fifth month, in the year 1686.

BARBARA SCAIF, daughter of William Scaif and Isabel his wife, of Blackside, near Appleby,
in the county of Westmoreland, with her sister Mary,
were both taken sick on the 30th day of the First month, 1686,
within one and the same hour, of the small-pox; and were both of them dutiful children,
fearing God, and making profession of the principle of light and life in Christ Jesus,
to which the people called Quakers bear testimony.

At the beginning of their sickness, divers of the neighbours came to visit them;
but Barbara said, "`Mother, suffer but a few to stay.
When they have seen us, desire them to go into the house,
for we have no need of such empty talk as is used amongst too many.
We would be quiet,
that we may pray to the Lord to forgive us the faults we have committed;
and if he spare us our lives at this time, I hope and believe we shall amend,
and have a care of displeasing the Lord while we live.`"
About the seventh day of her sickness she prayed to the Lord, saying, "`O, Almighty God!
I cry to thee; blot out all my transgressions, O Lord, and all my sins;
let them come no more into thy remembrance.
I beg it of thee, in the name of Jesus Christ, with all my soul,
and with all my strength; and let thy favourable countenance be upon me.`"

She also prayed that the Lord would confirm and strengthen her weak sister,
to give up herself freely, as she blessed the Lord she herself had done;
and then prayed for her parents; and many supplications besides, for a considerable time,
in the presence of several people that were not called Quakers, who said,
"`How can any die better than she is like to do?`"
To her brother she said, "`Be faithful to the Lord, and to thy religion,`" etc.
Being asked if she could freely part with her dear relations, her answer was,
"`I can freely part with, and leave them all,
for the enjoyment of the comfort and happiness which my soul is made sensible
of;`" and praised the Lord for the riches of his grace and comfort that
she had received from him to her immortal soul.

Being pressed to receive some meat, she said, "`Do not trouble me with meat,
for if thereby you think to keep me, it is all in vain, for I must die and leave you.
Neither would I desire to live for all the world;
for to be with the Lord is better than ten thousand worlds,
with whom I shall rest forevermore, even with God and his saints,
his faithful people and servants: glory to his name forevermore.`"
In her sickness she manifested great love to her parents,
and also to her sick sister Mary, saying, "`Go to her, do not stay with me,
whatever may befal me; that too sharp sickness may not fall on her,
until she know her peace with God.`"
To her brother she gave religious counsel, saying, "`Love the Lord with all thy heart,
and with all thy soul, all thy life-time; love not the world,
nor the pleasures thereof.`"
All the time of her sickness she was tender in her spirit, and circumspect,
not an unbecoming word proceeded out of her mouth; kind and pitiful to those about her,
not so much concerned at her own sickness, as for them who attended her,
considering the trouble they had in helping her.

That day she had lain a month sick (being much like
as she had been for three weeks before),
she was very cheerful, and able to express herself, and said to her mother,
"`What thinkest thou of this forenoon?`"
Her mother asked her what she meant: she replied,
"`It will go far in my time in this world, for the Lord will ease me ere long,
take away all my pain, and wipe away all tears from mine eye.
Call in my father (said she) that he may see my departure.`"
Her father being come, he said, "`Barbara, how dost thou?`"
She replied, "`I am ready to leave this world; therefore, father and mother, be content,
and bear me company a little while.`"
And about the first hour in the afternoon she departed this life,
as if she had fallen asleep, on the 27th of Second month, in the year 1686.

MARY SCAIF was elder sister to the aforesaid Barbara,
taken sick the same hour that she was,
and for whom her sister Barbara had been often tenderly concerned in supplication to God,
to give her the knowledge of his peace that hath no end.
She lived about two weeks after her said sister, her sickness being also the small-pox;
and in the Lord`'s time, who keepeth covenant, and shows mercy,
and giveth the spirit of supplication and prayer to them that believe,
he gave her a clear understanding, and she prayed unto God as followeth: "`O great God,
Jehovah, of heaven and earth, whose splendour filleth heaven,
and thy wonders fill the earth, have mercy upon me thy hand-maid,
who am as a worm before thee, yet part of thy creation.
Lord, help my weak soul, revive my drooping spirit:
by thy consoling presence strengthen my faith, I beseech thee,
and help me through this exercise.
I beseech thee, Lord, that thy will may be done in earth,
as it is done in heaven;`" and continued in prayer a considerable time,
supplicating for a willing mind, to resign herself up to God.

She was much inclined from a child to read the holy Scriptures;
and she often spoke of Job, David, and others of God`'s servants in former ages.
"`And now,`" said she, "`I do know God`'s love to be the same to me as it was to them,
so that I am neither afraid nor unwilling to die; for God blotteth out my transgressions,
and lays nothing to my charge,
and I do believe there is a place prepared for me in heaven.
And, dear mother, do what thou canst not to sorrow.
My love is great to thee, and my advice is, that you go and live near some good meeting,
and bring up my brother amongst friends.`"
Her sister being dead, she spoke of her own death also,
and was satisfied that her soul should ascend up to God in heaven, "`where,`" said she,
"`I believe my sister Barbara`'s soul is ascended, to rest with the Lord forever.`"
Her sickness increasing, she grew weaker,
and departed this life on the 13th of the Third month, in the year 1686.

AMARIAH DREWET, of Cirencester, in Gloucestershire,
preached in his life and conversation;
for he was faithful according to the measure the Lord had given him,
and turned not his back in time of suffering,
but rather blessed the Lord that he was found worthy
to be one of that number to have his faith tried,
often praying for his persecutors.

On the 11th of the Seventh month, 1686, he was visited with sickness,
and the Lord so filled his soul with his love and presence,
that three days before his death he signified,
if it was the last testimony he had to bear,
the love and presence and peace of God was with him; and that he could truly say,
as good old Simeon did, that he had seen the salvation of God.

The night before his departure he said to his wife, "`Go to bed, thou hast need of rest,
and give me up to the Lord, whose presence I feel, and I resign thee up;
may the Keeper of Israel, that good watchman, that neither slumbers nor sleeps,
be with thee.`"
At other times he prayed, "`O Lord, strengthen my poor body, that I may praise thy name;
my rest is in thee.
Oh! the largeness of thy love that I feel.
O Lord, hear my cries, and bear up my head in all my exercises.
Oh! thy sweet presence, and fresh springs that I feel!
Glory and honour, and praises, be unto thy name forever.`"

Again, "`Lord help me, and keep me close to thy power.`"
With divers other petitions that he put up to the Lord;
admonishing people who came to visit him, and warning the young to fear God,
and watch against those things that did corrupt youth; exhorting them to faithfulness,
that it might be well with them upon their dying bed, as it was with him.
He uttered many more heavenly expressions, which are omitted for brevity.
He lay half an hour, as if he had been asleep, and went away quietly,
without sigh or groan; and so departed this life, on the 25th of the Seventh month,
in the year 1686.

BENJAMIN PADLEY, son of William and Elizabeth Padley, of North Cave,
in the East Riding of Yorkshire, was a young man that walked in humility,
zeal and love towards God, and to all who walked in his truth.
The Lord was pleased to raise him to bear testimony to his everlasting truth,
in the assemblies of his people;
and his great delight was in the prosperity of the truth,
for which he faithfully and zealously laboured to the end of his days,
having regard to the motion of God`'s spirit in his ministry,
and lived according to his testimony.
He was sound, plain, and weighty in his declaration, and kept low and humble,
in a deep sense of the need he had to wait upon God, for the renewing of his mercies,
and fresh openings of the springs of life and love from God,
to help him forward in his spiritual travail, that he might persevere to the end;
and to which he did much exhort, and stir up Friends where he came.

He was taken sick the 17th of Sixth month, 1687;
which sickness continued about eight days.
In this time several Friends, and also neighbours and relations, came to see him;
and in the sense of God`'s love he declared truth amongst them.
There being some present who did not profess the same truth with us, he said,
"`It is not for any outward thing we travel abroad;
not any man`'s silver or gold that we seek or covet after;
but it is for the gaining of souls.
We have suffered the loss of our goods, scoffings, scornings, and imprisonments;
so that it may appear that it hath not been the benefit
of any man`'s goods or estate that hath been in our eye,
but for performing the will of the Lord.
Several of his neighbours being present, he said, "`It is well for them that can say,
on their dying beds, that their sins and iniquities are blotted out.`"
He prayed to the Lord, that he would mix mercies with his afflictions;
and exhorted friends to faithfulness and righteousness.
Observing his wife to weep, he said, "`O, why dost thou so?
thou must not do so; but keep to truth, and fear not but all will be well.`"

At night he said to her, "`Go to bed, and be not troubled about me.`"
Friends visiting him, he said, "`I am glad to see so many of your faces,
which I thought I should not have done,
being the Lord hath been pleased to visit me with sickness,
so that I am not likely to continue many days here; but I feel nothing,
but all is well.`"
When his friends would be careful about some physician to help him, he said,
"`I have a physician the world knows not of.`"
When he drew near his end he desired to be helped upon his knees,
and was so powerful in prayer to the Lord, considering the weakness of his body,
that it was an admiration to all present.
After that, few words proceeded from him, but he weakened apace,
and the next day departed this life, being the 25th of the Sixth month, in the year 1687.

SARAH FEATHERSTONE, daughter of Joseph Featherstone and Sarah his wife,
aged about fifteen years, was inclined in her tender years to hear the voice of wisdom,
and to remember her Creator in the days of her youth.
From a child she was harmless, and obedient to her parents,
and of a meek and quiet spirit.
She was taken sick the 9th of the Seventh month, 1688.

Her mother coming to her, she told her that she thought she should be taken from her;
and when her mother would send for a doctor,
she said she was freely given up to the will of the Lord, whether to live or die.
She farther said it was showed her that she was not of a long life; and,
"`if this be the time of my change, I am content.`"
Her sickness increasing, her mother was much concerned; at which she was troubled,
and said, "`Dear mother, thy dear and tender love to me hath been very great,
and in that love I desire we may rest, freely given up to the will of God;
for the Lord may not see meet to trust me in this wicked world any longer.`"

And farther she said,`"O! the abominable pride of this world! and there are some amongst
us who can take liberty to fashion themselves in many things like unto the world,
both in their habit and other needless things.
Oh! but the Christian life is another thing;
this is not the adorning that we are to put on; for if the righteous scarcely be saved,
where shall the wicked and ungodly appear?`"
Her distemper being violent, she then said, "`Never so sick in my life;
O! sick at my heart!
O Lord, in mercy remember me, and bear me up above all my afflictions,
for my heart trusteth in thee.`"
Being asked by her mother whether she would be buried by her father,
or at another burying-place, she answered, "`Dear mother,
bury me where thou and my father (her father-in-law) please, I leave it to you;
it is no matter how many miles distant these bodies lie,
our souls shall one day rejoice together;`" with more words,
bidding them about her not to trouble her, or give her any thing, without she desired it.

She lay still in a good frame of mind, with a sweet countenance,
bearing her sickness in much patience; often saying,
"`O! my dear and heavenly Father! come away, come away, for my heart trusteth in thee.`"
And so fell asleep in the Lord, the 17th of the Seventh month, in the year 1688,
aged fifteen years.

GEORGE GRAY, of Acquorthies, in Scotland, was a sufferer for the truth;
a poor man in this world, yet rich in faith; of mean education,
yet endowed with divine wisdom;
and bore a sound and faithful testimony amongst the Lord`'s people.

A little before his departure, being filled with the power of the Lord,
he gave weighty exhortations to all present, especially to his children.
To some friends that came to see him,
he said he had not kept back the word and counsel of the Lord from them;
and now he could say, it was good doctrine, to leave nothing to do till a dying bed:
so finished his testimony, and laid down his body the 8th day of the Twelfth month,
in the year 1689.

GEORGE FOX was born in the Fifth month, 1624, at Drayton, in Leicestershire.
At eleven years of age he knew purity and holiness.
In the nineteenth year of his age, in the year 1643, he left all,
and travelled up and down the nation, visiting many people who were seeking the Lord,
until the year 1646, at which time he entered into his more public ministry;
for he was sent of God, as the apostles were in the primitive times,
to turn people from darkness to light,
directing all to mind the light of Christ Jesus in their own hearts.
In the year 1648,
several meetings of Friends were gathered to God`'s teaching through his ministry;
in which ministry he faithfully laboured forty-four years,
through much suffering and many perils of various sorts,
as by the journal of his life doth largely appear.

God gave him length of days, so that he saw his children in the faith,
unto the third and fourth generation, to a great increase.
Great was his care for the preservation of those who had received truth,
that they might walk in the same; and to that end he gave forth many faithful epistles,
and good exhortation and advice, for good order and discipline in the church of Christ,
as appears in the collection of his epistles to friends.

He preached the gospel effectually but two days before he died, viz.,
on the 11th of the Eleventh month, 1690, at Gracechurch-street meetinghouse in London.
After meeting, he said, "`I am glad I was here; now I am clear,
I am fully clear;`" and then was the same day taken ill of some indisposition of body,
and continued weak in body for two days, at the house of Henry Goldney,
at White-hart-court, in Gracechurch-street,
and lay in much contentedness and peace to the end, being very sensible.
In this time he mentioned divers Friends, and sent for some in particular,
to whom he expressed his mind for spreading truth and Friends`' books in the world;
signifying also to some Friends, saying, "`All is well,
and the seed of God reigns over all, and over death itself; and though I am weak in body,
yet the power of the Lord is over all,
and over all disorderly spirits;`" which were his wonted sensible expressions,
being in the living faith and sense thereof, which he kept to the end.

On the 13th of the Eleventh month, in the year 1690,
he quietly departed this life in peace, about the tenth hour in the night:
so he ended his days in a faithful testimony,
in perfect love and unity with his brethren, being about the sixty-sixth year of his age.

JOAN VOKINS, wife of Richard Vokins, of the county of Berks, was a faithful woman,
and labourer in the gospel.
After she had received God`'s blessed truth,
she was much concerned that her relations also might receive the same truth;
and by her upright conversation and good example among them,
with the blessing of God and assistance of his grace, her husband, father,
and children received the truth; and her husband was a sufferer for the same,
in his imprisonment in Reading jail, and her eldest son also.
Having received a dispensation of the gospel of Jesus
Christ to preach to others in this nation,
she was also concerned in her spirit to visit divers
provinces and islands beyond the seas;
and in order thereunto took shipping from Gravesend in Kent, in the Twelfth month, 1679,
and visited New York, East and West Jersey, and some parts of Pennsylvania,
which at that time was not much inhabited, Long Island, Rhode Island, and New England,
and several of the islands, as Antigua, Nevis, and Barbados.

In her journey to these places she endured many hardships
and sufferings of several kinds;
yet through all she was supported by the power of Christ,
whose peace she felt in her soul.
On the 3rd day of the Fourth month, 1681, she returned from Barbados to England,
and landed at Dover in Kent.
At Sandwich she exhorted the priests and people of that town,
in their public place of worship, to forsake their vanity,
and to come to the spiritual worship of God; and laid before them the danger of the one,
and the benefit of the other.

After her return home to England, she continued her diligence in the Lord`'s work,
and care and service in his church, and among his people, to the end of her days.
About the yearly meeting time, in 1690,
she went up to London to visit Friends thereabout; and, but a few weeks before her death,
by a letter, dated from London, in the Fourth month following,
she signified to her dear friend Theophila Townsend,
another faithful woman-labourer in the gospel, at Cirencester,
that now her service was finished; and said,
"`I could gladly have laid down my body here among the Lord`'s worthies; yet,
seeing it is ordered otherwise, I submit to the will of my God,
and do think to go homeward in a little time.`"

Joan Vokins also said, not long before, to the said Theophila Townsend,
being then with her, that she had some papers,
which she desired might be made public after her decease,
expecting her time was not long to remain in the body,
being well satisfied that she should lay down her head in peace with God,
let death come when it would.
And according to the sight she had, and what she said,
the time of her decease was near at hand, for she did not live to get home,
after she wrote the letter aforesaid in the Fourth month at London.
Coming to Reading, she fell sick there, and upon her dying bed spoke to her son,
Richard Vokins, as followeth: "`Son, my weakness is great, and my pains very strong;
but the Lord is large in his love to me, and good to me;
he gives me patience to bear my pains, which are strong.
Ah, son, I have learned a good lesson; Paul`'s lesson; in all states to be content;
and now I have nothing to do but to die.`"

Putting forth her hand to take her leave of him, she farther said, "`Son,
remember the Lord, and he will remember thee: remember my love to thy wife,
and to all my children.`"
And after a little stop, and her speech low, she spoke these words again,
"`And he will remember you; and be you faithful to him, and he will bless you,
and you shall be blessed.`"
She departed this life the 22nd of the Fifth month, in the year 1690,
having finished her course, and kept the faith.

ROBERT LODGE, of the county of York, was convinced of truth in the year 1660,
and was a faithful minister of Christ Jesus,
and a valiant sufferer for the testimony of a good conscience.
He travelled in the work of the gospel, both in England and in Ireland,
and turned many to righteousness, and did build up many in the most holy faith:
he was not only a planter but a waterer in the vineyard: a son of consolation indeed.

The time of his sickness was but short.
A friend visiting him, he gave account of his infirmities, and questioned his recovery:
but he said, "`The Lord knows my heart, that I have served him;
and it hath been of more account to me, the gaining of one soul,
than all my labours and travels.`"
The friend going again the next day, and seeing him near his end, was sorrowful;
to whom he said, "`What! we must meet again,
we must meet again in eternity;`" and put up many heavenly petitions to the Lord.
Another friend taking leave of him, he called him by his name, and said,
"`It is well with me, and I have no disturbance in my mind.`"
And again he said, "`The Lord knows I was never commissioned to go any way,
or to do any thing, but I have willingly answered him; and the Lord,
who hath been my rock and refuge, my shield and buckler, and a sanctuary to me,
hath been with me all along to this very day.`"
He spoke much more in praises to the Lord for his many deliverances,
praying for the continuance of God`'s life and love to his whole heritage.
After which he spoke little, but that all was well with him; and said, "`Blessed be God,
I have heavenly peace;`" and so fell into a sweet sleep, and went away,
being on the 15th of the Seventh month, in the year 1690.

STEPHEN CRISP, of Colchester in Essex, received the blessed truth about the year 1655,
when he was about twenty-seven years of age,
and was a preacher of the everlasting gospel of Christ Jesus about thirty-five years.
In that service he travelled in many parts of England, Scotland, Holland, Germany,
and the Low Countries, as by the printed journal of his life more largely appears,
and endured many hardships for his faithful testimony to the blessed truth.
He was greatly capable, through his long experience,
to advise and give counsel to persons in all conditions.

In the latter part of his days, being unable to travel much,
through an indisposition of body,
yet he was diligent in preaching the gospel in Colchester and London.
He lay some time under great exercise and weakness; and about four days before he died,
being under much bodily weakness and pain, he said to George Whitehead,
who came to visit him, "`I see an end of mortality, yet cannot come at it;
I desire the Lord to deliver me out of this troublesome and painful body.
If he will but say the word, it is done.
Yet there is no cloud in my way.
I have a full assurance of my peace with God in Christ Jesus;
my integrity and uprightness of heart is known to the Lord,
and I have peace and justification in Christ Jesus, who made me so; that is,
upright to God;`" and remembered his love to all the faithful in the church of God.

To another friend he said, "`I have fought the good fight of faith,
and have run my course, and am waiting for the crown of life that is laid up for me.`"
To a friend who visited him, he said, "`Serve the truth for the simple truth`'s sake,
and it will preserve thee to the end, as it hath done me.`"
In his great pain of body, feeling the word of patience to support him,
he said to the friends watching with him, "`Grow in the word of patience,
that it may keep you also in the time of need.`"
The day before he died, he said,
"`I hope I am gathering,`" (as his expression was understood,) "`I hope,
I hope,`" being then hardly able to speak out his words.
George Whitehead, near parting from him, said, "`Dear Stephen,
wouldst thou have any thing to friends?`"
After some pause, he gave this answer, "`Remember my dear love in Christ Jesus to all.`"
And on the 28th day of the Sixth month, in the year 1692, he died in the Lord,
at Wandsworth, near London, about the sixty-fourth year of his age.

GULIELMA MARIA PENN was the wife of William Penn, of Pennsylvania,
and daughter of Sir William Springet, of Durling.
Her illness continued eight months upon her,
in which time she uttered many living and weighty expressions upon divers occasions,
both before and near her end.
At one of the meetings held in her chamber,
only her husband and children and one of the servants being present,
in a living power she said, "`Let us all prepare, not knowing what hour, or watch,
the Lord cometh.
O! I am full of matter!
Shall we receive good, and shall we not receive evil at the hand of the Lord?
I have cast my care upon the Lord, he is the physician of value;
my expectation is wholly from him; he can raise up, and he can cast down.`"

A while after she said, "`O! what shall be done to the unprofitable servant!`"
At another meeting, before which much heaviness seemed to lie upon her natural spirits,
she said, "`This has been a precious opportunity to me,
I am finely relieved and comforted, blessed be the Lord.`"
At another time, her husband speaking to her of the peace of well-doing,
she replied to him, "`I never did, to my knowledge, a wicked thing in all my life.`"
To a friend, aged seventy-five years, that came to see her, she said, "`Thou and I,
to all appearance, are near our end.`"
And to another, about sixty-five years old, who came also to see her, she said,
"`How much older has the Lord made me by this weakness than thou art!
But I am content.
I do not murmur.
I submit to his holy will.`"

In the height of her sickness she said,
"`It is the great goodness of the Lord that I should be able to lie thus still.
He is the physician of value to me, can I say.
Let my tongue set forth his praise, and my spirit magnify him whilst I have breath.
O! I am ready to be transported beyond my strength.
God was not in the thunder, nor in the lightning;
but he was heard in the still small voice.`"
She called the children one day, when very weak, and said, "`Be not frightened, children;
I do not call you to take my leave of you, but to see you;
and would have you walk in the fear of the Lord, and with his people in his holy truth.`"
Speaking another time solemnly to her children, she said,
"`I never desired any great things for you, but that you may fear the Lord,
and walk in his truth among his people, to the end of your days.`"
About three hours before her end, a relation taking leave of her, she said,
"`I have cast my care upon the Lord;
my dear love to all friends;`" and lifting up her dying hands and eyes,
prayed to the Lord to preserve them and bless them.
About an hour after, causing all to withdraw, she took her leave of her husband,
saying all that was fit upon that solemn occasion.

She continued sensible, and ate something about an hour before her departure;
at which time her children, and most of the family being present,
she quietly expired in her husband`'s arms,
with a sensible and devout resignation of her soul to Almighty God,
on the 23rd of the Twelfth month, in the year 1693, in the fiftieth year of her age.

PATRICK LIVINGSTON was born in the year 1634, near Montrose, in the kingdom of Scotland.
He received the blessed truth about the year 1659,
and travelled much in the service thereof,
bearing a faithful testimony to the same for above thirty years,
in many parts of England and Ireland, and most places in Scotland,
where he was made a good instrument in convincing and gathering
many to the knowledge of the inward appearance of Christ Jesus,
particularly that meeting settled at Kinermuck in Aberdeen county,
the largest meeting in all the nation.
In this county he valiantly and patiently endured
several years`' close imprisonment in Aberdeen,
for his faithful testimony to the truth, viz., from the year 1676 to 1679;
and he likewise bore a faithful testimony for truth, by imprisonment in Newgate,
in London, for a considerable time, about the year 1684.

Valiant he was for the truth, especially in times of persecution.
Like a good soldier, he never turned his back in the day of battle,
but through the strength of the Lord was still amongst the first in suffering,
being fervent and zealous for the cause of truth and honour of God.
His persecutors were sensible that he was a strengthening to his brethren in prison;
and therefore, that it might not be so, they would several times let him go,
or miss some meeting he was known to be at.
Faithful he was to his brethren in their afflictions, and would not leave them,
till he saw an end to that persecution in Scotland in the year 1679;
and from that time no Friend was imprisoned for several years in that city.

After this he returned into England to his dear wife,
who at that time dwelt in Nottingham, but in his latter years,
he with his family lived in London.
He continued to the end a diligent labourer in the Lord`'s vineyard,
several times visiting his native country of Scotland; and the year before he died,
viz. 1693, he again visited his brethren there,
and was attended with a plentiful measure of the Lord`'s power and presence,
all the time he was among them, though at that time weak in body.

After his return home he grew weaker,
until he departed this life on the 15th of the Fourth month, 1694,
at the house of John Kirton, in Kensington, near London,
being removed thither for the benefit of the air, where several friends were present,
witnesses of the following heavenly expressions, viz.

The day before his departure he said, "`I am in unity with all faithful Friends,
and in love to all men.`"
About an hour before his departure, he said, "`O Father!
O Father!`"
A little time after, mentioning his weakness of body,
and as if he desired more strength to utter what was in his mind,
which being then apparently given him, he said,
"`Let life reach unto all here:`" and pulling off his night-cap
with his own hand about half an hour before he was removed hence,
he said, "`Blessed, praised, magnified, and exalted be the mighty, powerful,
great and everlasting name of the Lord God, forevermore.
Oh! that thy life may arise in full dominion over all,
and that Friends may feel it so in all their assemblies; that they may be kept in love,
concord and unity together, and show it forth in word, work, testimony,
life and conversation unto all;`" adding, "`Life being over all;
here we have all we need,
and here there is a lying down in true submission to the will of the Lord,
and laying down our heads in peace and rest with him forevermore.`"
Which last words he repeated twice, and said, "`Here is victory over death, hell,
and the grave, and resting in peace with the Lord forevermore.`"
He died on the 15th of the Fourth month, in the year 1694,
about the sixtieth year of his age.

ANDREW SOWLE, of London, received the truth as professed by the people called Quakers,
in his young years, and became obedient thereunto,
and gave himself up to the living power thereof,
which enabled him with much cheerfulness to undergo those manifold
afflictions and persecutions with which he was exercised;
for being a just and upright man, he was zealous for the propagation of the truth,
to which, both by conversation and sufferings, he bore a faithful testimony.

He was a printer by trade, and engaged himself freely in the printing Friends`' books,
when he had large offers of advancing himself in the world,
made to him by his other friends and relations, if he would have desisted therefrom.
But his love to truth,
and the desire he had to be instrumental in his calling for spreading it abroad,
would not suffer him to hearken to any of those offers.
He freely gave himself up to the service thereof,
even in times of the hottest persecution, believing it his duty so to do,
though therein he should hazard not only his life,
but also that outward substance God had blessed him with.
For several years together he was in continual danger upon that account,
his house being often searched, and his printing materials, as presses, letter, etc.,
as often broken to pieces, and taken away,
as any Friends`' books were found printing by him;
and this they did for many years together.
During this time, though he met with great losses, and had, at one time,
by his adversaries, about a thousand reams of printed books taken from him,
yet he was never heard to complain, but he would say,
he was glad to have any thing to lose for truth,
and that the Lord had made him worthy to be a sufferer for it.

This quiet resignation of himself to the will of God,
caused one of those who came to seize upon his goods,
to do what he could with his partners to put a stop to the seizure;
and when he saw he could not prevail, he went out and wept.
When at another time his adversaries came to take away his printingpress,
he was so resigned and easy, in giving up all to his persecutors,
that when they had done their work, and seized upon all, he,
(as he often did in like cases,) set forth meat and drink before them,
according to the command, Rom.
xii., 19, 20, to feed even his very enemies; and his good so overcame their evil,
that some of them departed under a concern;
but one of the chief being filled with malice against the truth, survived not long after,
but died in a miserable condition.

As this sincere man met with great sufferings,
so had he also large experiences of the goodness
of God towards him in many remarkable providences.
At one time he was taken at a meeting of the people called Quakers,
and carried to Newgate, and being examined by Sir Richard Brown, the persecuting mayor,
who, understanding he was a printer, threatened to send him after his brother Twin,
(as he called him,
who some time before suffered in Smithfield for printing
a treasonable book,) to whom this meek man replied,
"`Thou wilt not live to see it:`" and the event justified it, for Brown died soon after.

After many exercises and trials divers ways, which it would be too long to recite,
he was visited with weakness of body the beginning of the Tenth month, 1695,
and grew weaker and weaker till the 25th of the same month.
His patience and resignation to the will of God, during the time of his weakness,
were such, that he seldom was heard to complain, but would say,
that he was given up to the will of God; saying often,
that he had no dependence on any thing, save upon Christ Jesus, the good Samaritan,
on whom was his whole dependence.

George Whitehead, with another friend, coming to visit him,
he said he had served truth faithfully,
according to what the Lord had been pleased to make manifest to him;
and that in what he had done, he had not sought himself, but the honour of God.
He would often exhort his family to faithfulness,
and his young ones also to seek the Lord in the days of their youth.

His reproofs to those who had done amiss, were so kind and so convincing,
that a servant of his said he stood more in awe of a reproof from him,
than the severest treatment of another.
"`His end,`" said he, "`being in love to convince me,
that I have done that which is not right.`"
William Penn, the night before he departed, came somewhat late to visit him,
and finding him in a sweet composed frame of mind (for indeed
he was to appearance as though he ailed nothing),
asked him how he did; he answered with much cheerfulness,
his satisfaction and peace of mind were great, and that he waited for his change.
The said Friend,
who had been many years acquainted with his industrious and innocent life,
after some discourse with him,
kneeled down and prayed that the Lord would give him the reward of his labour; for,
through him, many blessed truths had been brought into the world, etc.

After prayer was ended, he acknowledged William Penn`'s love,
telling him he was well satisfied in his condition,
and in the truth of God which he had professed;
and that he had nothing to do but to wait in the will of God till his change came:
and so in much love they parted, he signifying his love to, and unity with all Friends,
in the truth.

After that, he lay sweetly retired, waiting for his change,
and had his senses perfectly and clear to the last,
which was about eight the next morning; at which time his wife came to his bedside,
and asked him how he did; he answered, "`Oh Jane,
never such a good night as this:`" and the same minute shut his eyes,
and with a hymn of praise to God, offered up his last breath, and fell asleep,
not so much as fetching the least sigh, nor was any alteration seen in his countenance.
So easily and so quietly did he leave this world, in which he had known much exercise,
and is gone to his everlasting rest, with God`'s faithful servants.

He finished this life the 26th of the Tenth month, in the year 1695,
about eight in the morning, at his house in Holywelllane, London,
in the sixty-seventh year of his age.
Rom. 8:18.
For I reckon, that the sufferings of this present time,
are not worthy to be compared with the glory which shall be revealed in us.
