== Chapter 4

[.chapter-synopsis]
* William Garton
* Charles Ormston
* John Ormston
* Thomas Robinson
* Thomas Robinson
* Stephen Smith
* William Allen
* William Simpson
* Joseph Coale
* William Smith
* John Steel
* Thomas Lloyd
* Elizabeth Moss

WILLIAM GARTON, of Ifield, in the county of Sussex, was an early fruit to God,
a faithful believer in his blessed truth, and a servant in the church of Christ.
He was zealous against all unrighteousness,
and much for the unity of the spirit in the bond of peace among brethren;
an elder indeed, watching for good over the flock, a sympathizer with the afflicted,
and a mourner in the house of mourning, more in deed than in words.
Though but a plain man,
yet God endowed him with a large understanding and sound judgment,
which has been approved in difficult cases.
He was firm and constant in spirit in times of suffering and persecution,
preferring the service of truth, and the testimony of it, before all worldly things.

He was an example of virtue in the church, also in his family;
and his removal hence was a great loss to both; a true loving husband and tender father.
He had a great care that his children might be trained up in the fear of God,
and knowledge of his blessed truth;
which labour God was pleased to answer to his satisfaction.
He would often say,
the greatest portion he desired of the Lord for his children was the blessed truth,
and that they might love, fear, and serve the Lord,
and then he did not doubt that they would want any good thing;
and to that end he would often be giving them good counsel and admonition.

Two days before his decease, being visited by a friend,
he said that he had always endeavoured +++[+++to promote]
the prosperity of truth to the best of his understanding;
and that he had nothing of trouble upon him;
but did bless God that he had an opportunity to give this testimony to those present;
exhorting an ancient friend to keep low in God`'s fear, and make straight steps,
that he might lay down his grey hairs in peace.
Another time, several Friends coming from a meeting to visit him,
he desired that his love might be remembered to all Friends.

Another time he said, "`I have always sought the peace of the church,
according to my ability.`"
Being asked by a young man that watched with him how he did, he replied,
"`I am the better to see young men come up in the truth.`"
A friendly person coming to see him on his sick-bed, he put out his hand to him, saying,
"`Ah! thou lackest something: these be serious times.`"
Two ministering Friends visiting him the day before he died, he seemed very much revived,
and said, "`I never did any thing against the truth knowingly, since I was convinced.`"

One taking his leave of him, hoping for his recovery, he replied,
"`If it be the Lord`'s will,
let me go in peace:`" he also said that he felt the Lord to come in upon his spirit.
Near his end he prayed for his wife, and children, and grandchildren,
that God would make up the loss of him to them.
He further said, "`Oh Lord, I pray thee, remember the ancients,
that they may still hold on their way; and, oh! my God, if it stand with thy will,
visit more and more those who are not of thy fold, and bring them in by thine arm,
that they may come to know rest for their souls,
that at the last we may be bound up together in the bundle of life;`"
and so concluded with hymns and praises unto God.

Another time, after some friends had prayed by him, which was to his great satisfaction,
and the room being clear of company, he said to his daughter who was standing by,
"`Oh dear child, I have known much of the goodness of the Lord,
but not in such a large manner before as now: the very fountain is open,
and the love of God is over all; praises, praises to the Lord.`"
He uttered many heavenly expressions, and gave good exhortation to those about him,
which are not here inserted.
A little time before he died, he called for his relations, embraced his wife in his arms,
and took his last leave of her, and of his son and daughter;
holding out his hand and taking leave of all Friends who came to see him,
till his strength failed; and so sweetly died in the Lord, in an honourable good old age,
the 8th day of the Seventh month, in the year 1701,
being the sixty-sixth year of his age.

[.asterism]
'''

CHARLES ORMSTON, merchant at Kelso, in Scotland,
was convinced of the blessed truth about the year 1665.
He was a good example and pattern of godliness,
which he showed forth in the upright life and conversation he had amongst men,
and bore a faithful testimony among the Friends of that meeting to which he belonged,
and at whose house the meeting was kept to his dying day.

He was in the year 1668 cast into Edinburgh prison,
upon the account of his owning those people called, in scorn, Quakers.
He remained prisoner about twenty-two months; and his wife,
who was not at that time called a Quaker,
having several times made application to the privy council for his release,
did at length obtain an order for the same on the 20th of the Twelfth month, 1669.
Afterwards, Friends settling their meeting at his house, the earl of Roxburgh,
whose lodging was hard by, being angry that it should be so near by,
caused the town-militia to be raised, and by force hauled Friends out of their meeting,
and laid several of them up in prison, amongst whom C. Ormston was one.
His adversary at length perceiving that neither keeping them out of their meeting-room,
nor yet locking up his doors, would hinder them to meet under the pillars of the house,
gave over his persecution.

This our friend fell sick about the latter end of the year 1684,
and continued to grow weaker for about two months time.
Having before put his outward affairs in order,
and feeling himself very weak and nigh his end, upon the 21st of the Twelfth month, 1684,
in the evening, he called for his two sons,
(his daughters not professing truth) the elder whereof came to him,
whom he took by the hand, and exhorted him to a faithful walking in the truth,
as he had formerly done, and instructed them in many things.
About three quarters of an hour after, he fell asleep in the Lord,
having left a good savour of his upright life and conversation behind him.

[.asterism]
'''

JOHN ORMSTON, eldest son to the aforesaid Charles Ormston,
was an example of sobriety and godliness, having from a child shunned evil;
and when he was mocked for refusing to bear company with others in their vain recreations,
he bore it patiently, not reviling again.
He was given to retirement, and a careful instructor of his younger brother.
He was much troubled with bleeding, which brought him into a consumption,
and he told those about him he did believe he should die.

Being near his end, he desired his father to pray by him, which he did;
and about three or four days before he died,
he inquired of his sisters the day of the month, which being told him, he answered,
"`The twenty-second shall be my day;`" which proved true,
for upon the 22nd of the Tenth month, in the year 1682, he departed this life,
and entered into that blessed rest prepared for the faithful.
Aged twenty years and four months.

[.asterism]
'''

THOMAS ROBINSON, of Bridge-end, near Kelso, in Scotland,
was convinced of the truth about the year 1669, in which he walked circumspectly,
in a good conversation, to his latter end,
being a good example in the place where he lived;
and often exhorted his friends and brethren, in the meeting to which he belonged,
to faithfulness.

He was several times imprisoned about the years 1672
and 1673 for meeting with the people called Quakers,
to worship God.
After having lived to a good old age, it pleased the Lord to visit him with sickness,
which continued about twelve days, in which time he was kept in patience,
and often signified that he felt the love of the Lord in his soul;
and exhorted his neighbours and relations, who came to see him,
to fear the Lord and to turn to him, while they had time.

Many more seasonable expressions he spoke, even when he was in great pain,
which much affected the standers by; to whom he said,
"`Let patience have its perfect work:`" he also signified
that being walking one evening by himself,
as his manner was,
he prayed fervently to the Lord that he might have
a seal of his assurance before his departure;
and immediately he was filled with great joy, and the word of the Lord came to him,
saying, "`Is not my grace sufficient for thee?
That is done already: thy peace is made.`"
A little before he departed some of his children, with others, being present,
and he being about to take his last leave of them, said,
"`Humble your hearts before the Lord, and make use of your time,
and slip no opportunity of making your peace with God.`"
At last, recommending his spirit into the hands of the Lord Jesus Christ,
he sweetly laid down his head in peace upon the 28th of the Ninth month,
in the year 1698, being about the seventy-third year of his age.

[.asterism]
'''

THOMAS ROBINSON, son of the before mentioned Thomas Robinson,
was convinced of the truth about three years before his parents,
when he was about thirteen years of age, and but few Friends in those parts;
and he was so effectually converted, that although many endeavours were used,
both by promises and threatenings, they were not able to overturn his faith.

He was a youth of a sober and religious conversation,
insomuch that he was a wonder to many; and by his faithfulness to the truth,
though a child, he was very instrumental to the convincement of his parents,
who afterwards lived and died in the same faith.
Many disputes he had with priests and others, and was so furnished with arguments,
that they were often astonished at him.

About the twentieth year of his age,
God was pleased to call him to the work of the ministry;
at which time he was concerned to go to public places of worship,
and bear testimony to the people against their evil deeds.
His ministry was living, and he had a clear discerning of the spirit of antichrist,
that secretly worked for the hurt of God`'s heritage,
which he advised friends to watch against.

He travelled through the northern counties of England,
and also visited all the meetings of Friends in his own nation,
and had several sights of things to come, some of which he saw come to pass;
and also had a vision of his own death two years before he died.
He was visited with sickness, which continued about seventeen weeks,
and in all that time he was not heard to repine, or speak frowardly,
though his sickness was attended with much exercise.
Many times he sung praises to the Lord, to the affecting of others who heard him;
and declared that he valued not the pains and trouble of
his body if it was the Lord`'s will so to try him;
but that the Lord`'s everlasting truth might be raised over all;
and all lets and hindrances be taken out of the way,
and he to feel preservation in the truth, to the end of his days.
With many more good expressions.

The night before he died, he entreated his parents not to repine at the Lord`'s doing,
saying it was his will to remove him from the evil to come.
After a little silence his father asked him if he
had any thing more upon his mind to say;
he answered, "`Little more, but that all might be kept faithful who profess the truth,
the precious truth.`"
And farther said, "`Let me rest, I have done, I have done;`" and fell asleep,
and slept till about break of day,
and then departed this life on the 2nd of the Eighth month, in the year 1678,
about the twenty-third year of his age.

[.asterism]
'''

STEPHEN SMITH was born the 19th of the Seventh month, 1623.
He received the truth in the love of it in the year 1665,
and gave up to obey and walk therein.
He truly loved God`'s faithful messengers and people,
how despised and suffering soever they were; and he suffered with them,
both in person and estate, by imprisonment and spoil of goods,
for his tender conscience and testimony on behalf of Christ Jesus.

He was a man fearing God, and of good report in that county,
being an exemplary preacher of righteousness in his conversation,
and one truly kind and ready to do good in his day.
God also endued him with a living ministry and experimental
testimony to tell of his goodness,
and speak of his praise to others, from an inward sense thereof in himself,
and to the comfort and encouragement of many who heard.
He travelled in divers parts of the nation, in the work and service of God,
in the gospel of his Son.

In the time of his sickness, when he was in the greatest extremity of weakness,
he often declared of the lovingkindness of the Lord God,
by which he was upheld above the fear of death.
To several who came to visit him on his sick-bed, he said,
it was a blessed and heavenly thing to have the mind clear and holy,
free from all troubles and cumbers of this world, as he said his mind was,
having all given up to the will of the Lord, that it might be truly done on earth,
as it is in heaven; adding,
"`O what a blessed and heavenly habitation is this for the soul of man to rest in,
which I have a full assurance of!`"

At another time, one who came to see him he exhorted to dread and fear the Lord God,
and to repent of all,
whatsoever that holy and pure witness in his conscience makes manifest to be evil,
if happily he might find mercy with the Lord; which will be better to thee (said he),
than all the world besides.
A little after came into the chamber another person,
and the power of the Lord being with him, he was refreshed in his spirit,
and he desired the said person to fear the Lord,
that thereby she might be preserved out of all evil; and added,
"`Love the truth above all, for the truth is a very precious thing;
and be sure keep low and humble to it,
and be not high-minded nor exalted above the pure witness of God in thy conscience,
for that would be hurtful.`"

Another time, in remembrance of the tender dealings of the Lord to him,
he said to his sons, who were present, "`My days are very near drawing to an end;
and though my father and mother cast me off when I was a little lad,
the Lord hath always preserved me, and his blessings did always attend me,
having been often in many great dangers, both by sea and land.
Having my mind sober and chaste to God,
and having the fear of the Lord placed in my heart, by which I was preserved out of evil,
I did the thing that was right in the sight of the Lord,
so that I found favour of the Lord, and gained the love and favour of people,
in dealing justly and truly with all people, not wronging any man.`"
This he gave in charge to his sons,
that they might always be kept sober and chaste in their minds,
having always regard to the fear of the Lord placed in their hearts,
that thereby they might be preserved out of evil,
doing always that which is just and right;
and to be sure to be courteous and kind to all, loving the good in all,
and bearing their testimony against the evil in all, wheresoever it did appear.

He farther said, "`And whensoever you go about that which is weighty,
take counsel of good and sound Friends,
so that all things may be done to the glory and honour of the Lord and his blessed truth,
in which your blessings are all yea and amen.`"
He moreover advised his sons, saying, "`Do not run into the cumbers of the world,
but wait upon the Lord, and he will find out a way for you in his time;
for the Lord is calling, and taking me out and from all troubles and cumbers,
and from the evil that is coming upon this wicked world, in a good time,
wherein I am assured of that sound and perfect peace,
wherein my soul will rest with the Lord forever; so that I have no more to do now,
but desire the Lord to make my passage easy to my heavenly rest.`"

A little before his departure, being filled with the spirit,
he praised and magnified God, and prayed, saying, "`Lord, and dearest God,
oh! assist in this heavenly passage from death to life;`" and soon after said,
"`Now I am going into my sweet sleep;`" and immediately and innocently
laid down his head in perfect peace with the Lord,
the 22nd of the Seventh month, in the year 1678, at his house, near Guildford, in Surrey,
aged fifty-five years and three days.

[.asterism]
'''

WILLIAM ALLEN, of Earls Colne, in the county of Essex,
received the blessed truth in the year 1654,
and the power of the Lord made a speedy change in him.
Soon after, he had a dispensation of the gospel of Christ Jesus given to him from God,
and he was stirred up with zeal in his soul against the false ways, worships,
superstitions, and profaneness of those times;
which zeal for God produced living testimonies from him,
in divers towns and places where he travelled, against those things which were evil,
which sometimes occasioned him to come under hard sufferings, bonds and imprisonments.

In these he behaved himself as a faithful and courageous soldier of Christ Jesus,
and a good example to his fellow-sufferers, preaching the gospel of peace,
both in life and doctrine, and stopped the mouths of gainsayers.
This had a sweet and comfortable effect upon many,
who were reached in their consciences by his testimony and ministry,
and by his innocent conversation;
so that they embraced the truth he preached and suffered for,
and became heirs of the salvation of God, to their everlasting comfort,
and the furtherance of the gospel.

He was of severe carriage to such as made profession of truth,
and walked not with a straight foot in the gospel;
but he was very tender over all such as were young,
and under exercise about their inward condition,
and sometimes spoke effectually to their conditions,
to the easing of their afflicted spirits.
He was an example in the county where he lived,
encouraging Friends to observe the good order of the truth,
and to keep the gospel void of offence; not exalting himself above his brethren,
but carried a good respect to them, and to their counsel and judgment.

He served the Lord Jesus Christ, and his church and people,
without weariness to the end of his days;
and would lament those who sat themselves down at ease,
and would often say that a terrible day would overtake them who were at ease in Zion.
In the time of his health, when he was able to go abroad and visit Friends, he would say,
"`God hath made me a huntsman,
and I must visit many of them who are in their holes and caves;
I must be clear of their blood:`" and would relate
the sore travails and pangs that he had for some,
which often made his soul very sorrowful.

His labours in the gospel were chiefly in the counties of Norfolk, Suffolk, Cambridge,
and Essex; and for his testimony to the truth he was imprisoned in Colchester castle,
where he was instrumental to gain divers to the truth.
He was also imprisoned at Cambridge, and at Ely, and Lynn in Norfolk,
and many were turned to God by his ministry.
He was a diligent labourer in the Lord`'s vineyard for about twenty-four years,
and the last year and a half of his time he was much
afflicted with bodily weakness and sickness;
but he would often say that he was content with the will of his Father.

In the time of his sickness he showed the meekness
and patience of Christ which dwelt in him;
but the Lord, in due time, seeing his exercise to be enough, put a period to his days.
He was filled with the peace of God to the last, so that he said he could shout for joy,
but that he wanted strength of body; and which, he said,
was but an earnest of what he should more fully enjoy
when his earthly tabernacle was dissolved.
He spoke largely of the enjoyment of the glory of God in his soul,
and of the assurance he had of eternal life;
some of his expressions in his sickness were as follows:
"`The earth is filled with the glory of the Lord: praises, praises unto my God,
who reigns over all, over all.
He hath redeemed my soul from the grave, and my life from the horrible pit.
He hath plucked my feet out of the mire and clay.
Glory, glory be given unto thy great name, oh! my good God.
As for my part I have fought the good fight, and have kept the faith;
and a large share of the glory of my God is sealed in my soul.
It is but an earnest that I have here of that crown of life
and glory which my Father hath in store for me.`"

Concerning his sickness, he said,
"`It hath pleased the Lord to exercise me as he did Job,
for the trial of my faith and patience.
I have trodden his steps these twelve months.
A full reward thou hast given me of life and glory.
Oh! my good God, how good art thou to me!
I have received abundance of good at thy hand, and shall not I receive a little evil?
Blessed be thy name for thy goodness.
My cup overflows, I cannot utter it;`" and so continued,
often speaking of the glory of the Lord, and the immortality that rested upon him.
He charged friends to be faithful,
that the dread of God might always rest upon their hearts,
that they might answer his love, in yielding obedience to his requirings; and then,
if they met with exercises for the trial of their faith, yet the Lord would be with them,
if they abode faithful to the end; and the same crown of life they should enjoy,
which he had assurance of.

"`Therefore,`" said he, "`watch, and keep your garments, and oil in your vessels,
that you may be ready to enter with the bridegroom.
But as for those that continue in hypocrisy and disobedience,
and shun the cross of Christ, and neglect to work while it is day,
the night will come upon such unawares,
and the foolish virgins`' state they will be found in;
and though they may desire oil of the wise, the wise will have none to spare;
but the door will be shut upon such, and misery will be their portion.
He also gave good counsel to his two daughters, saying there was a blessing for them,
for their father`'s sake, if they would bow to truth, and abide faithful therein.`"

He longed to haste away; but was also willing to wait God`'s pleasure.
More was spoken by him as friends came to visit him, and as his strength would permit,
which was not taken in writing.
After his speech grew low he could not well be heard,
and seemed for some hours as if he was departing.
At last he said to a friend, "`I was almost gone, but I cannot go yet;
there is some secret counsel of God in it.`"
After some little time, more friends coming in, he was, beyond outward likelihood,
enabled to declare much to them, exhorting them to faithfulness, and said,
"`I am glad to see my friends about me.
I go to my God and your God, my Father and your Father.
My bosom is full of love to all my Father`'s children;`" and then said, "`Now,
Lord Jesus, how acceptable is it to leave all the world,
and be gathered up to thee:`" and so, committing his spirit to the Lord,
soon fell asleep.

His end was honourable, and he is crowned with immortality and eternal life,
and he left the world in a good age, having attained to about sixty-three years.
He died the 21st of the Eleventh month, in the year 1679, at Earls Colne,
in the county of Essex.

[.asterism]
'''

WILLIAM SIMPSON, born in Lancashire, where he also received the truth,
was a faithful minister and prophet of the Lord,
and was much concerned in going through markets and towns,
and to great men and magistrates, and priests`' houses, and public places of worship,
declaring against their false worship, and evil ways and works;
and was often imprisoned for the truth,
and underwent cruel and hard sufferings by the jailers.
He was moved of the Lord to go at several times, for the space of three years,
barefoot through markets, courts, cities and towns, and to priests`' houses,
as a sign to the people; telling them so should they be stripped, as he was.

Sometimes he was moved to put on hair sackcloth, and to besmear his face black,
and to tell them so would the Lord besmear all their religion.
Great sufferings did this poor man undergo; many sad blows, and sore whippings,
with staves, and wands, and thorn-bushes, coach-whips, and horse-whips, on his bare body.
This was before king Charles the Second came in;
that that generation might have taken warning, and they would not,
but rewarded his love with cruel usage: only the mayor of Cambridge did nobly to him,
for he put his gown about him, and took him into his house.

In the year 1670 he went to Barbados, in company with that faithful servant of God,
John Burnyeat, to preach the gospel of Christ Jesus in that island;
and after they had some service for God there, he was taken sick of a fever,
in which time he felt great peace and consolation of the spirit.
After he had been sick several days, he signified to Friends about him that he should die.
In the observation of his submission and innocent behaviour on his sick-bed,
some shed tears; and he taking notice of it,
tenderly desired that they should not be grieved.
Growing weaker, and his voice low, he said to those about him, "`Friends, be noble,
and do not hinder me in my passage, for I am an innocent man.`"
Being asked whither he would go, he said,
"`I must pass away;`" and by what more was said at that time,
Friends were assured that his heart was wholly fixed upon the Lord.

A few hours before he died, a person came to visit him who had not been, though invited,
at any meeting William had been at in the island,
and taking him by the hand asked him how he did; he answered,
"`I am a very sick man;`" and looking towards the man,
he was endowed with the power and spirit of the Lord,
by which he marvellously preached the glorious gospel of our Lord Jesus Christ,
for about a quarter of an hour, praising and magnifying the Lord;
which was so contrary to the expectations of those about him,
(considering the circumstances of his weak condition,) that it caused amazement,
trembling, and tears.

He preached the doctrine of perfection, and freedom from sin on this side the grave,
exhorting friends to be valiant for truth upon earth;
and that they should not be again entangled with the yoke of bondage;
but to stand fast in the liberty wherewith Christ hath made them free;
that every bond and yoke might be broken, and that which is pure and holy,
of the Lord God, might go free in all; that God might be glorified and honoured,
and they preserved in the day of trial, which must come upon all flesh;
and so to grow from grace to grace, and from strength to strength,
and from one degree of holiness unto another,
and that a daily growth might be witnessed in all.
Farther saying, "`O friends! it is the life that the Lord looks at;
for he that hath the Son hath life; and he that hath not the Son hath not life.
Examine yourselves; no Son, no life; without the Son,
without life:`" and thus he declared wonderfully,
often praising and glorifying God after this manner;
--"`Oh! all that is within me praise and magnify the Lord God,
who is worthy forever and ever of all glory.
Everlasting praises to the God of my life, who is only worthy, and lives over all,
and is above all, God blessed forever.
Amen.`"

About three hours after he had given this testimony,
he departed this life in much quietness, being the 8th day of the Twelfth month,
in the year 1670, and was honourably buried in a garden belonging to Richard Forstal,
at Bridge-town, in Barbados.

[.asterism]
'''

JOSEPH COALE, of Reading, in the county of Berks,
a young man about nineteen years of age,
was convinced of truth in the breaking forth of God`'s blessed day in our age.
When the ministers of Christ Jesus our Lord came to Reading,
he was one of the first that received their testimony,
and was one of the first in the county of Berks that
suffered imprisonment on the truth`'s account.
In the year 1655 he was committed to the counter in Reading, by Henry Frewin, justice,
and afterwards to the jail, for declaring, in the public place of worship,
that Cain`'s sacrifice was not accepted, but was an abomination to the Lord.

He preached the everlasting gospel, and the day of God`'s visitation to the world;
and his ministry was effectual,
not only for the convincement but also for the establishment and confirmation of many,
he being experienced in the work and dealings of the Lord God,
and also of the wiles and baits of the enemy of the souls of mankind;
a faithful witness-bearer to the truth,
not in words only but in life and conversation also;
walking in innocency and lowliness of mind, in which he was a good example and pattern,
as became the gospel of Christ Jesus.

Being delivered out of prison, he was moved, in the year 1656,
to travel abroad in the west of England,
to visit his friends and brethren who were prisoners
for the truth in Launceston jail in Cornwall,
where, at that time, our dear Friend George Fox was also a prisoner, with other Friends.
In compassion to their sufferings he was conscientiously concerned to lay before
justice Anthony Nichols the cruelty of the jailor towards his friends,
carrying also with him a letter from George Fox to the said justice; who,
instead of relieving the oppressed,
committed the said Joseph Coale to the rest of his friends at Launceston as a vagrant.

He lay there many months, after he was fined at the assize,
for the most part in a wretched place called Doomsdale, where they used to put murderers,
after they were condemned to die.
It was so noisome that it was observed few who went in ever came out in health;
and the filth of the prisoners, that from time to time had been put there,
had not been carried out, as the people said, for many years; so that it was like mire,
and in some places to the top of the shoes in water, etc.
The jailor would not let Friends clean it,
neither would he let them have beds or straw to lie on.
Being released, he went on farther westward to visit Friends,
but was committed by justice Ceely again to Launceston jail as a wanderer,
where he lay three months.

In the year 1657, he being with other Friends met to worship God, near Penryn,
in Cornwall, captain Fox, governor of Pendennis-Castle, with a troop of horse,
came and abused Friends in a wicked manner, and Joseph was much beaten,
and some of his blood shed, to the hazard of his life.
He was also afterwards, for declaring truth in the public place of worship at Exeter,
fallen upon by the rude people, and haled by the hair of the head,
and had to the town-hall, and from thence to jail, a very filthy place;
and they put a great pair of double irons upon one of his legs,
and ordered the jailor not to let him have any bed nor straw to lie upon;
but the next week he was set at liberty.

In the same year he was committed to Dorchester jail for
exhorting people to repentance in the market-place at Lyme,
and for declaring truth in the steeple-house at Bridport.
In 1661 he was again imprisoned at Exeter for not swearing;
being taken from a peaceable meeting, and tendered the oath.
Many other times he hazarded his life for the testimony of the blessed truth, in stocks,
and stonings, and divers other hardships and difficulties.
He was once in Ireland with Edward Burrough, in the service of the gospel.

Last of all, he was committed to the jail of Reading, on the 13th of the Fifth month,
1664, by William Armourer, a justice of the peace, because,
for conscience-sake towards the Lord, he could not break his command, who had said,
"`Swear not at all.`"
After six years being shut up in prison, and much deprived of common air to breathe in,
he was greatly impaired in his health.
In the time of his sickness,
he gave forth many heavenly exhortations to Friends who came to visit him;
and this was his faith, which he declared on his dying bed, saying,
that the light of that glorious everlasting day of the Lord,
which is broken forth in this our day, shall never be extinguished,
notwithstanding all that men can do: "`And though,`" said he,
"`it may be in the hearts of men to destroy and root out, if it were possible,
the righteous from off the earth, yet the Lord doth not intend so,
neither is it in his heart to suffer it so to be,
but to exalt his own name and kingdom over all;
and the wrath of man shall turn to the glory of God, and the rest he will restrain.`"

Death was made easy to him;
and near his departure he bid one of his fellow-prisoners farewell,
and resigned up to him that office of love and care
which he exercised amongst his brethren and sisters,
in bonds for the truth`'s sake.
Being filled with heavenly love and life, and fully satisfied,
he laid down his head in peace,
and full assurance of everlasting rest and joy in the Lord.
Aged about thirty-four years.

[.asterism]
'''

WILLIAM SMITH, born at Besthorp, in Nottinghamshire,
was formerly a pastor of an Independent congregation,
and lived after the strictest manner of that people,
and was convinced of God`'s everlasting truth about the year 1658.
He was a faithful labourer in the gospel, and many were turned unto God by his ministry;
for he approved himself a minister of Christ Jesus, in tumults, in labours, in travails,
in watchings, in necessities and distresses,
which came upon him through the often spoiling of his goods,
and long and tedious imprisonments of his body.
For refusing to pay tithes to an impropriator,
he was kept close prisoner one time twenty-one weeks among felons,
in a dungeon in Nottingham jail;
and another time he had the value of forty-two pounds taken from him,
at the same time he was in prison for seven pounds, demanded by Dove Williamson,
priest of Elton.

Indeed, many were his sufferings for his testimony to the truth,
which for brevity sake are omitted; all which he patiently endured,
as seeing him who is invisible, that he might hold fast faith and a good conscience.
In the times of his imprisonment he wrote several useful books,
which remain in the printed collection of his writings.
When he was at liberty he travelled abroad,
to the nourishing and strengthening of them who did believe.
Though he was often visited by sickness, he was kept in much patience and contentment;
and much of the power and presence of God appeared in him many times,
when he was in great weakness of body, to the admiration of the beholders.

In his last sickness, he was a great comfort to them who visited him,
being a living man in the life of truth.
After he had been ill seven weeks, his pains began to cease,
yet he continued in weakness; but other distempers came upon him,
which he bore with great patience.
Waiting quietly, and having his mind retired, he spoke little till one evening,
when many Friends being in the room, sitting in silence, and he in his bed,
he turned towards them, and plentifully declared of the great love of God:
and Friends were much refreshed and tendered.
He also testified of a large portion which he had in life eternal;
and then he spoke to Friends to be mindful of truth, and of their service therein,
more than of their daily food; and so committed them to the grace of God.

The day before he was taken away he called for all his children, who were six or seven,
and tenderly exhorted them to keep in the fear of God, and to love the truth,
and God would be a father and portion to them.
The next day he departed this life, being the 9th of the Eleventh month, in the year 1672.

[.asterism]
'''

JOHN STEEL, of Cumberland, was brought to the knowledge of the truth in the year 1654,
and was obedient thereunto;
and the Lord gave him a public testimony to bear not long after he was convinced,
which continued with him to the end of his days.
He was a man of an excellent spirit,
and clear in discerning the states and conditions of many,
to whom he was made very serviceable by good counsel, wholesome advice and instruction.

His manner in public testimony was to deliver himself in few words, and not often,
yet very weighty and profound.
He was severe against deceit and wrong spirits,
but very willing always to encourage the well-doers;
a good example in conversation in his family, and abroad amongst men,
as well as in the church.

When he was first taken sick he said to his wife, "`I must leave thee;`" she replied,
"`My dear, why art thou of that belief?`"
He answered, "`It is my belief, and that I shall be well,
and get to the place of pleasantness that I have been travailing for above these twenty
years;`" exhorting her to take heed to the pure light wherewith she was enlightened,
"`for,`" said he, "`it is the way, and there is not another.`"
He bore a living testimony on his dying-bed, in the name and power of the Lord,
to several who came to visit him, both Friends and other people, exhorting, warning,
and reproving, as he was moved of the Lord.

The day before he died, several Friends being come to see him,
he bade them sit down and mind well what he said;
and he uttered many very weighty sayings, which were not written down;
but this was remembered, that he said,
"`None could die the death of the righteous but they that lived the life of the righteous.
Though death may seem hard to some, it doth not seem hard to me;
for I feel my passage sweetened this day.`"
He exhorted Friends to keep the unity, and beware of a wrong spirit, and then said,
"`I have little more to Friends, but it may be I have something to say to others.`"

After a little time he desired several of his neighbours, who were not called Quakers,
to be sent for, and most of them being come, the power of the Lord came upon him,
and he said,
"`I am not ashamed this day to say the spirit of the Lord
is upon me;`" and so declared to them several weighty things,
and said, "`Though some of you have been long in a profession of religion,
if the question were put to you, What is the guide of your minds?
I believe you will be put to a stand for an answer.`"
Some of their hearts were so reached that they wept.
A few hours before he died, he uttered many heavenly expressions in prayer to the Lord,
to the great refreshment of the standersby.
Thus the Lord, who alone is worthy of praise, accompanied him by his power to the last.

He was convinced of truth in the year 1654, and died in Cumberland, in 1680.

[.asterism]
'''

THOMAS LLOYD formerly dwelt at a place called Macemore, in Montgomeryshire, in Wales.
In his young days he was brought up at the university of Cambridge,
and afterwards removed with his family to Pennsylvania,
where he was president and deputy-governor of that province several years;
and in the last part of his time he had his share with other friends in the exercises
occasioned through the contention of George Keith with Friends in that country.

Being taken sick, and near his end, he said to Friends about him, "`Friends,
I love you all.
I am going from you, and I die in unity and love with all faithful Friends.
I have fought a good fight, I have kept the faith,
which stands not in the wisdom of words, but in the power of God.
I have fought, not for contention and strife, but for the grace of our Lord Jesus Christ,
and the simplicity of the gospel.
I lay down my head in peace, and desire you may all do so: friends, farewell all.`"

He farther said to Griffith Owen, a Friend who was then intending for England,
"`I desire thee to mind my love to Friends in Old England,
if thou livest to go over to see them.
I have lived in unity with them, and do end my days in unity with them,
and desire the Lord to keep them faithful unto the end,
in the simplicity of the gospel.`"
After a few days`' sickness, he departed this life on the 14th of the Seventh month,
in the year 1694, aged about forty-five years, leaving six children behind him,
and was buried in Friends`' burial-ground in Philadelphia, in Pennsylvania.

[.asterism]
'''

ELIZABETH MOSS, daughter of Thomas Monk of South Liverton Hall in Nottinghamshire,
whose mother afterwards married Samuel Watson of Knight Stainforth,
in the county of York, and late wife of Thomas Moss, merchant in London,
was educated under a tender, zealous, and religious mother,
who brought her up in the nurture and admonition of the Lord;
and she was a dutiful and obedient child.
When she grew up, and came to receive the truth, she gave up to it,
and continued faithful therein to the end.
She was exemplary in her family, and took great pains to instruct her servants,
that she might bring them to a sense of their dangerous condition without a Saviour.

She was a great lover of retirement, and much given to prayer, contemplation,
reading of the Holy Scriptures, and spent much of her time alone in her chamber;
so that frequently, when her husband returned home from his affairs abroad,
he found her weeping; upon which he has sometimes said to her,
"`If some persons saw thee at these times,
they might think thou wast under discontent:`" her answer was, "`No, my dear,
there is nothing at all of that;
but the Lord`'s power and presence hath broken my heart and tendered my spirit,
in a living sense of his goodness and tender dealings towards me.
I can say he is truly good to my soul,
and I have tasted of the incomes of his heavenly love and life.
I heartily wish that all who make profession of the blessed truth, were enjoyers with me,
for my soul hath been overcome with his love; and although I have lost all my children,
and many of my near relations, yet is the Lord pleased to sweeten all my afflictions,
and make hard things easy to me.`"

She was indisposed some time before she kept her chamber,
and her sickness increasing upon her,
she was advised to remove out of the city for the recovery of her health, which she did,
and was some time at Shacklewell.
But notwithstanding, she grew worse; and being sensible that her end drew near,
she sent for Samuel Waldenfield, George Whitehead, and some other Friends,
that she might see them before she died.
The day before she died, Samuel Waldenfield and John Field coming to visit her,
she was much revived, and spoke to this purpose, as followeth,
directing her speech to Samuel Waldenfield.

[.embedded-content-document.testimony]
--

I had a desire to see thee,
and to invite thee to my burial, (she having sent for him the day before;)
but I hope, (said she to John Field,)
thou wilt not take it amiss that I spoke first to Samuel,
for I did not know of thy coming.
Thy visit being altogether free, I kindly accept of it as freely,
and desire thee also to be at my burial.
Though I did not know that I should have seen the light of another day,
yet the Lord having spared me, I am glad to see your faces,
that I may tell you how good and gracious the Lord hath been to my soul;
for I can truly say, I have sought him with many tears, in my secret chamber,
and poured out my soul unto him; and said, O Lord,
do thou come down and tabernacle in me, and take up thy abode with me.
For I testify Jacob`'s seed hath wrestled with God for a blessing, and hath prevailed;
and now he is become my portion, and the lot of my inheritance forever.
He hath poured of the oil of joy into my sorrowful soul,
and hath fed me with the finest of the wheat,
and with honey out of the rock hath he sustained me,
and the sting of death is taken away.

I say, my dear friends, I have not the work to do now, I bless my God for it,
but am ready to be dissolved; and I do freely resign my life to my God.
I remember my dear and tender mother, who was a woman that truly feared him,
and her prayers and petitions were often put up to the Lord,
on the behalf of her offspring; and we have reaped much benefit thereby.
I have blessed the Lord many a time that ever I was born of her.
I speak not these things boastingly; no, for what am I but a poor lump of clay?
But only to extol the powerful name and goodness of my God,
who hath been so bountiful and gracious to me,
for there is forgiveness and mercy with him, that he may be feared.

Therefore be encouraged to keep faithful to the Lord,
all that are within the hearing of my voice, both husband, friends, and servants.
I exhort you all, do justly, love mercy, and walk humbly with your God,
that so it may be said unto us all, "`Come, ye blessed of my Father;`"
which is what my soul hath desired, and that I might never hear that dreadful sound, "`Go,
ye cursed.`"
The Lord hath answered my desire this day, and hath loosed my tongue,
that was ready to cleave to the roof of my mouth,
and hath strengthened me to praise his great and honourable name.
Oh! praise the Lord with me, my friends, and pray for me,
as I shall do for you whilst I have breath,
that I may be preserved and kept in patience to the end;
for it is they that hold out to the end that shall be saved.
And though I have a dear and tender husband,
and want for nothing that is convenient for me, yet I can freely part with all.
I hope the Lord will preserve him near to himself to the end of his days.

--

Cornelius Mason coming in, she said,
"`Remember my dear love to thy wife and dear children; she hath been kind in visiting me,
and we have lived in much love and friendship together.
I truly desire the Lord may keep you faithful to himself to the end of your days;
and now I am comforted, and can say, Lord, here I am before thee,
do with me as it seemeth good in thy sight.`"
This is the substance of but part of what she said,
for she continued a considerable time speaking of
the mercies and dealings of God to her soul,
and praising him for the same, to the comfort of those present.
Samuel Waldenfield spoke a few words,
and returned praise and thanksgiving to the Lord for his
endless love and tender mercies to his servants and people;
during which she was filled with heavenly joy, and spoke some words afterwards,
desiring her dear love might be remembered to all faithful Friends, with whom, she said,
she was in perfect unity; and so parted with them in much sweetness,
love and satisfaction.

Soon after came our friend George Whitehead, whom she had desired to see,
and she was refreshed and comforted to see him; and said, "`Dear George,
I am glad to see thee, having always had much love and respect for thee,
thou having been at my father`'s house, and known my mother well.
Though I am weak of body, yet the Lord hath comforted me with his living presence,
and death is no terror to me;
but I am freely resigned and given up into the hand
of my God;`" with much more to the same effect.

Being much spent with the other Friends, she could not raise her voice as she did before;
but with love and sweetness, and a smiling countenance,
spoke of the goodness of the Lord to her soul,
and recommended her counsel to those that were present,
that they might not leave that work to do,
but labour to make their calling and election sure,
before they were cast upon a bed of languishing, as she was upon;
but through the love of her heavenly Father, she was waiting for her change,
and desired that she might hold out to the end in true patience.
She desired George Whitehead also to be at her burial,
and after he had spoken a few words in prayer and supplication on her behalf,
she parted with him in much love and unity.
Afterwards she said, "`O that I had wings like a dove! for then would I fly away,
and be at rest:`" with many other living and heavenly expressions.

These things are written,
not only for the comfort but encouragement of those who are yet behind,
to love the Lord above all, and follow him fully,
that he may not forsake them in the day of distress.
This Friend often said the eternal God was her refuge,
and underneath was the everlasting arm of his power,
to uphold and lift up her head above the floods of
temptations and trials that she met withal;
by which she was enabled to sound forth praises,
and humble thanksgiving to his holy and blessed name.

She departed this life the next day, being the 3rd day of the Second month,
in the year 1702, aged about thirty-nine years,
and was buried at Friends`' burial ground in Bunhill-fields, London.

[.the-end]
END OF THE SECOND PART
