== Chapter 4

[.chapter-synopsis]
* Hannah Turner
* Thomas Upsher
* Priscilla Cuthbert
* Elizabeth Whiddon
* Robert Sandham
* Deborah Sandham
* Edward Parker
* Eleanor Cannings
* Henry Pontyn
* Isaac Alexander
* Anne Camm

HANNAH TURNER, daughter of Thomas Turner, of Coggeshall, in the county of Essex,
in visiting her acquaintance, was taken sick at Goussingbeckingham-hall,
in the said county, and quickly after being taken sick was sensible she should die.
Her mother being with her, she desired her to bear it with patience,
and remember how it was with Abraham, and with many in our day,
in parting with their only child.
"`Dear mother, consider, it may be this great trial may prove to our sanctification;
bear it with patience.`"
For several days she lay in a composed state, praying to the Lord to forgive her offences.

She was troubled that she was so far from her friends and neighbours,
and would have been glad to see them.
She expressed her concern for an acquaintance of hers,
entreating her mother to say to her as followeth: "`Consider my death as a precedent,
and remember she must come before the bar of the great God, as well as I,
and can no way shun it; and how doth she think to stand there without great repentance.`"
Another time she desired to have her love remembered to Friends at London,
and ordered the manner of her burial.

Her father coming off a journey to see her, she said, "`Dear father,
how often have I been comforted to consider how the Lord
hath preserved thee through many jeopardies of thy life,
both by sea and land.`"
She also admonished her nurse not to go into jollity and pastime,
nor be ashamed of the cross of Christ.
"`What if people mock thee, be not ashamed; remember Solomon`'s words,
that '`I know thou for all these things God will bring thee into
judgment.`'`" Many other exhortations she gave to this lass,
saying, "`Take notice of what I say;`" to which she answered,
breaking forth into weeping, "`I hope I shall.`"
At other times she spoke several weighty and seasonable exhortations,
which are not taken down, and so passed away, inwardly breathing to the Lord,
which was a great comfort to those with her;
and died on the 8th day of the Twelfth month, 1705, in the nineteenth year of her age.

[.asterism]
'''

THOMAS UPSHER was born in the parish of Lexden, in the borough of Colchester,
in the county of Essex, and was sprinkled or baptized, as they call it, a few days after,
according to the manner of the church of England, the 11th of the Sixth month, 1672,
but was educated in the Presbyterian way, and was religiously inclined from his youth,
often seeking the Lord for the good of his soul,
and delighted in reading the Holy Scriptures.
About the fourteenth year of his age he left the Presbyterians,
and joined himself with the people called the General Baptists,
and was zealous in that way, and became a preacher among them when young,
and was well esteemed by them,
until it pleased the Lord more effectually to visit him by the light of Jesus Christ,
unto which he turned his heart,
and came to see the emptiness of his former professions and talk of religion,
without the knowledge of God and Christ by the revelation of the Spirit.

A few days after he was convinced of truth, he wrote a letter,
which was sent to the Baptist meeting, to be read on the First-day of the week,
showing the cause why he left them.
This letter was dated the 13th of the Ninth month, 1692,
so that he was twenty years of age when he came among the people called Quakers,
and was a diligent attender of the meetings of that people for the worship of God,
waiting upon him in silence and retirement of mind, for his teaching and counsel,
until he was pleased to give him a gift in the ministry,
which he received in great humility, and entered upon his ministry,
in speaking a few words amongst Friends, in much fear and tenderness,
to the comfort and refreshment of many.
God in tender mercy did increase his gift,
so that he became an able minister of the gospel,
to the turning of many from darkness to the light of Christ Jesus;
and in that service he travelled in most parts of England, and also in Ireland.

As he often in the time of his health remembered and spoke of his death,
so he did in his sickness, saying, "`I do not expect to live long in this world.
I have been preparing for a better.
I do not desire to live here on my own account.
I long more and more to be at home with my God,
yet I would not be of that sort to desire my reward before my work is done.
There is nothing here can invite my stay,
but if God hath further service for me in this world,
I am resigned and given up to his will.`"
In a letter to a particular friend, written in the time of his sickness,
he expressed himself in these words:

[.embedded-content-document.letter]
--

When I consider those many unaccountable changes which we, and ours,
and all we have in this world are subject to,
it seems a sufficient antidote against the inordinate love of it, and it appears to me,
that it is the want of due thoughtfulness which makes many so much engaged in it,
as almost wholly to sequester all those religious endeavours
which are really necessary to make sure of an eternal interest.

It is now a long time since I have enjoyed one day of perfect health as heretofore.
I consider it as a preparatory summons from this frail state of life; and to conclude,
I thank God I am not altogether unmindful of my duty,
in setting my house in order against the time shall come that I must die, and not live.
I hope to live in a far better state,
and there to enjoy all the generations of the just that are gone before,
and shall hereafter follow.

--

About the same time, several Friends being with him, he, speaking of his death,
desired they might bear him witness, saying, "`My dependence, hope, and trust,
is only and alone in the Lord Jesus Christ,
and that I do not value myself upon any qualification or endowment,
but lay all down at the feet of Jesus, and am as nothing before him.`"

About two days after, though weak in body, he was carried in a coach to Ipswich,
to the burial of a Friend.
When he came there, he seemed very unfit for the service of the day,
there being much people at the burial; but the Lord strengthened him to declare,
as at other times, the truth and word of life for about an hour and a half,
which much affected the people in general; and Friends, who knew his weakness of body,
admired the love and goodness of God to him.
He prayed also, and spoke at the grave some time,
and appeared stronger after the meeting than before,
and continued better a few days after.
But his sickness returned again, and he was very patient under the extreme pains,
which he said no tongue could express, desiring to be resigned;
and the Lord blessed him with resignation, faith, and patience, under all.

To a Friend that came to visit him,
who made some observation of the prevalency of his distemper, he said, "`Now,
in all likelihood, I am about to take my last leave of you all,
and I pray God from my heart to bless you.`"
Many sound expressions were spoken to those who visited him in his sickness; to some,
counsel and advice; to others, his own experience of the mercy and goodness of God.
Being desired to send for another physician, he answered, "`No, I am satisfied:
if God had been pleased to have said amen to means,
there has been sufficient means used for my recovery,
and therefore I shall have my eye only to the Lord for help.`"

At another time he said,
"`My tongue is not able to express what I feel of the love
and goodness of God now when I have most need of it;
that saying used by that plain, despised people is very true,
that life is better than words.
There is one thing I cannot find out,
why the Lord should so abound in his love and mercy to me,
who am unworthy of the least of his mercies.`"
There was a great refreshment felt many times in being with him in silence,
in time of his sickness.
On a First day, in the morning, several Friends being in his chamber,
he desired that they might wait upon the Lord together;
and the Lord was pleased to open his mouth to praise his holy name.

Although very weak in bed,
some Friends desiring him to say little to those who came to visit him, his answer was,
"`I know not whether I may have another opportunity to do it.`"
He remembered the faithful, and spoke of their blessed estate; at the sight of which,
he was even as it were in a rapture of joy,
praising the Lord to the comfort of those present, saying,
"`Oh! that I might declare of the wonders of the Lord that I have seen in the deeps,
but I am resigned to the will of the Lord.`"
His pains and exercises were very great, and, as he often said, unknown;
yet he also said, "`The Lord is very good to me,
and bears up my spirit in the midst of them all.`"

Taking leave of several friends who visited him, he said, "`Oh! that you may so live,
that we may meet again in the mansions of eternal rest.`"
He remembered his dear love to friends everywhere, saying, "`They are near my life,
I have true unity with them in spirit.`"
At another meeting in his chamber, about fourteen days before he died,
the state of the church, and many precious truths were opened to him,
and in a heavenly frame of spirit he spoke of the wonderful wisdom, love,
and goodness of God,
exhorting Friends to be more faithful and diligent in the service of the Lord.

About ten days before his death, finding himself, as he thought, somewhat better,
he went to the meeting, being the First-day of the week,
and prayed fervently in the forenoon meeting, praising the name of the Lord,
in a true sense of his mercy and goodness.
But in a day or two he altered much, his distemper prevailing upon him.
He desired to be carried decently to his grave, saying, "`I love decency,
and desire to die in great humiliation,
and commit my spirit into the hands of the Lord Jesus Christ.`"
About the time of his death, he was in a heavenly frame of spirit,
and spoke of a glorious meeting, and said,
"`The Lord in the riches of his mercy will keep all them that trust in him,
under all their trials to the end.`"
And so departed this life, the 10th of the Eighth month, 1704.
Aged thirty-two years two months.
He left behind him three children; and his wife, in the time of his sickness,
was much indisposed, which was an addition to his exercise.

[.asterism]
'''

PRISCILLA CUTHBERT, born at Brentford, in Middlesex, in 1697,
was the daughter of Thomas and Isabella Cuthbert, of the same place.
Some months before her sickness,
she was observed to have a religious concern upon her mind,
and retired from the rest of the children, and denied herself diversions among them,
and got into solitary places, and read in good books, and sometimes weeping by herself,
and other times praising the Lord.
She had a sight of her death before she sickened, and spoke of it to several.

When her sickness came, which continued three weeks, she bore it with much patience,
praying to the Lord to be her comfort, and said,
"`I hope the Lord will comfort my dear father and mother;`" acknowledging the labour
and tender care and cost which her parents had been at for her bringing up,
and the education of herself and sisters and brothers.
When her father came to her, upon her inquiry after him,
she laid her arms about his face to wipe off the tears, and said, "`Lord,
comfort my father and mother, and bless my poor sisters,
and my brothers;`" and gave good advice to her brother to obey his parents,
and fear the Lord, saying he will bless thee.
She said to her father, "`I am willing to live to praise the Lord,
and I am willing to die, if it were at this moment of time.`"
She desired that when she was buried, none that laughed or were vain should be there,
but such as feared the Lord; and in a sweet frame of mind praised the Lord.

Another time she said, "`I have, in the time of my health,
been afraid when I have seen any dead nailed up in their coffins;
but now the Lord hath taken away that fear, blessed be his name.
Therefore take you notice, who stand by me,
that I am neither afraid of death nor the grave,
but I am willing to die when it pleaseth the Lord;`" and soon after fell asleep.
She often prayed for her parents,
to whom she expressed more than ordinary affection
and regard for their love and tenderness to her,
expressing her willingness to die, and her comfort in the Lord.

Her school-mistress visiting her, she said,
"`I am going where I trust in the Lord I shall have rest, for the Lord is my rest.`"
Near her end, her father speaking of his purpose to stay with her that night,
she replied, "`No, no, for I shall not die this night,
though it will not be long before I do.`"
He went to bed: and the next day her father coming to her,
she having had some rest in the night, she praised the Lord;
a neighbour present supposed she might, by her praising God, disturb her father,
to which she made no answer, till after some time, she said,
"`Is my father disturbed at my praising the Lord?
no, no, I know he is not.
Indeed if I was dying, as some have done of late, rending and tearing with bad words,
my father and mother too would have great reason to be troubled,
but to have a child die in the Lord, I hope great is their comfort.
I know their trouble is mixed with joy,
blessed be the Lord for it;`" upon these words several
young women present broke forth into tears.

About two hours before she died,
her father asked her if he and her mother should
turn her to see if she could have a little rest,
she answered, "`Do what you please.`"
A friend present advised all to be quiet and still,
and in a little time hearing one weep, she said, "`Who is that, my sister Elizabeth?`"
reply was made, no; she replied, "`For the Lord`'s sake do not cry for me,
do not cry for me.`"
These were the last words she was heard to speak:
and so departed this life without sigh or groan,
about the ninth hour of the sixth day of the Sixth month, 1701,
in the fourteenth year of her age.

[.asterism]
'''

ELIZABETH WHIDDON, wife of Henry Whiddon, of Cork, in Ireland;
was from her childhood given to sobriety, beyond what was common in one of her years,
when she was about fourteen years of age,
and was a woman of an exemplary life and conversation.
She was called of the Lord to give testimony to his name and truth,
though she was backward and unwilling to be concerned in so weighty a work,
yet afterwards grew more strong, and declared of the wonderful things of God.

In the time of her sickness she enjoyed a great refreshment
from the presence of the Lord,
which tendered the hearts of friends present,
and caused her to praise and magnify the God of her salvation,
some days before her death.
Her brother, Joseph Pike, visiting her one morning, and inquiring how she did, she said,
"`Oh! dear brother, though I have not slept all this night,
yet I am as one that wants it not.
Though my body is extraordinarily weak, yet I am strong,
the power of the Lord carrying me over all weakness; but above all,
the Lord said this night to me, in the powerful and fresh openings of life,
'`Thou shalt praise me in the heavens;`' which hath so overcome my soul,
and raised my spirits, that I am as one that wants no sleep,
nor is sensible of pain or weakness;`" and so went
on in praising and magnifying the Lord,
with many good expressions that cannot well be remembered.

About a day before she died, observing her sister Elizabeth Allen to weep,
looking upon her with a composed countenance, she said, "`Sister, why dost thou weep?`"
She answered, because unwilling to part with her.
She replied, "`Oh!
I shall go to everlasting joy and felicity, where I shall be at rest.`"
She departed this life the 23rd day of the Fifth month, 1693,
to receive the recompense of reward, even a crown eternal,
of which she had received before-hand a full assurance.

[.asterism]
'''

ROBERT SANDHAM, born near Petworth, in Sussex, in England,
was convinced very early of truth at Youghall, in Ireland, where he then dwelt,
and he soon became a faithful follower of it, and sufferer for it,
bearing a steadfast testimony to it against its opposers;
and was a preacher of it in his life and conversation amongst
the inhabitants of that town until the end of his days.
He lay sick two weeks,
in which time he often exhorted Friends that came
to visit him to be faithful to the truth;
and to some, negligent therein, he said much in warning them to be no longer so,
but to hasten out of a lukewarm state, lest the portion thereof should be theirs.
Some relations and neighbours visiting him, he exhorted them to receive the truth;
"`For,`" said he, I bear my testimony now on my dying-bed,
that it is the truth which the Quakers profess;
therefore be faithful to the Lord and his truth, whilst you have health and strength,
and delay not till you come to a dying-bed, as too many are apt to do,
for then oftentimes men and women find it enough to bear
their sickness and pains;`" which affected most present.

To his wife, with whom he had lived about twenty-four years in much love, he said,
"`I am freely given up to the Lord`'s will.
I therefore desire thee also to give up, and bear my death with patience,
and the Lord will make up thy loss of me in being near unto thee.`"
He often exhorted his children to love the Lord and his truth,
and be obedient to their mother, and love one another, and all honest Friends,
and delight to go to meetings.
One of his children being of age to remember what he said, he said to her,
"`Tell thy two young sisters when they are grown up,
that it is my charge to them so to do, for they may not remember what I say to them now,
and the Lord will be a father to you and a husband to your mother.`"

Seeing one of them crying, he said, "`Be good children, love the Lord,
and obey your mother, and though I am taken away,
you will have your mother left with you, and she will take care of you.`"
Soon after he drew nigh his end, being in a sweet frame of mind,
resigned up to the Lord`'s will, often speaking of his mercies to him.
He said,
"`The Lord hath fully satisfied my desires;`" and
took a solemn farewell of his wife and children.
A friend being present, prayed to the Lord to be near him in that present exercise,
and make his passage easy; after which he took the said friend by the hand,
and expressed his great peace and satisfaction, and passed away,
being sensible to the last.

He died the 28th of the Eighth month, 1675.

[.asterism]
'''

DEBORAH SANDHAM, wife of Robert Sandham aforesaid, was born near Youghall, in Ireland;
she received truth soon after her husband, and was a faithful,
serviceable woman to her end, bearing a true and sound testimony for God and his truth,
and was very exemplary in conversation.
She survived her husband about twenty years, taking due care of her children,
which fulfilled their father`'s dying words to them.

When it pleased the Lord to visit her with the sickness whereof she died,
she perceiving one of the family to be much concerned at it, said, "`Be not concerned,
I am freely given up to the will of the Lord, either to live or to die.
If the Lord have any further service for me, he can lengthen my days, if not,
I am freely resigned to his will.`"
She was often in her sickness inward with the Lord,
being kept in great patience and quietness, exhorting Friends,
and inviting some of her relations and neighbours who came to visit her,
to receive the truth; also warning some unfaithful ones,
not to let slip the day of their visitation.

She also exhorted her children to mind her frequent advice and counsel to them,
and to fear the Lord, and to keep out of all that which grieves his righteous spirit;
as (said she) your dear and tender father on his deathbed exhorted you, even so do.
Love the truth, and love one another, and then the Lord will be a father to you,
as truly he hath been a husband to me.
My desires have been, and are still, that you may fear and love the Lord,
and reverence him, for your mother doth not die without a hope,
that the Lord who hath begun his good work in you, will carry it on,
and that the blessing of the Lord will rest upon you,
which is more than all visible things; as my soul hath been a witness of,
as my mind hath been kept from coveting after them, having seen,
that godliness is great gain, and in the gain of it is great peace.

One of her daughters not being with her in the time of her sickness,
she desired to be helped up, that she might write a few lines with her own hand,
as her last words to her, which were as follow: "`I not knowing as yet,
whether it be the will of my heavenly Father to finish my days, I am,
through the great mercy of God, freely given up.
Oh! this I have in my heart to say to thee, be faithful, be faithful,
and dwell in holy patience; and the same is to thy husband.
Oh! that you may come to holy silence with fear and dread,
then will the work of the Lord prosper, which is more than all works.
Thou hast many of my exhortations, which get together, and keep and mind,
and the God of peace support thee; thou not being in a condition to come to me,
so farewell in the Lord.`"

The day before her departure, she was fervent in prayer to the Lord,
that he would bless his people, and enable them to walk faithfully before him,
and that his truth might prosper,
and that he would please to raise more faithful labourers
for the gathering many more unto righteousness;
also that he would be pleased to bless her children, and their offspring,
and make them his; with much more which cannot be remembered.

The day she died, she said to one of her daughters, "`Thou art my first-born,
and always very dear to me.
I cannot now say much more to thee, but mind my former exhortations,
and remember that truth was more than all, and truth was over all with me,
and truth was thy mother`'s chiefest treasure;`" often saying,
"`My dear child give me up, give me up; entreat the Lord to enable thee to give me up,
for I am freely given up to the Lord`'s will.
Taking her last farewell of her children and grandchildren, with friends and the family,
she desired to have her dear love remembered to Friends at Cork, and elsewhere;
my love also (said she) extends farther, to all Friends in England.
Some time after, turning herself about in her bed, she said,
"`I am now a going to leave you.`"
And so she quietly, and in great peace,
departed this life the 15th day of the Fifth month, 1695, in Youghall, where she dwelt.

[.asterism]
'''

EDWARD PARKER, of Thornbury, in Gloucestershire,
was convinced of the blessed truth by John Audland and John Camm,
at their first coming into those parts, which was about the year 1654.
He bore a public testimony for truth, and continued faithful to his death;
and on his dying bed gave very living testimonies to the truth,
to many Friends and others about him.
His last words were,`" Lord, come,
thy servant is ready:`" and then departed this life in the year 1667,
in the fiftieth year of his age.

[.asterism]
'''

ELEANOR CANNINGS, wife of Joseph Cannings, of Thornbury, in Gloucestershire,
was convinced by John Audland and John Camm, about the year 1654,
when they came into that county.
She was a zealous woman,
and often exercised in bearing a faithful testimony for the truth against the priests,
for which she suffered many and great abuses from the rude people.
She continued a sincere-hearted Friend to the end of her days,
and on her dying bed gave many good exhortations to friends about her, saying,
a little before her death, "`I am well satisfied, and am going to a better habitation.`"
She was buried at Hasel, the 19th of the First month,
about the seventy-third year of her age.

[.asterism]
'''

HENRY PONTYN, of French-Hay meeting,
was a faithful labourer in the ministry of our Lord Jesus Christ, as well beyond sea,
as in this nation of England, and endured many sufferings and hardships,
and several years`' imprisonment at Gloucester for his faithful testimony for God,
and continued faithful to his death.
On his dying bed he said that the Lord had done well for him,
and the chastisements of the Lord are good;
exhorting his children and friends about him to live in the fear of the Lord,
that they might die in his favour, saying, "`The end will crown all.`"
He died in the sixty-seventh year of his age.

[.asterism]
'''

ISAAC ALEXANDER, son of Thomas and Alice Alexander, of Bendrig, in Killington,
in the county of Westmoreland, was born in the year 1680,
and convinced of the blessed truth in the year 1694, in the fourteenth year of his age.
In his seventeenth year he received a gift of the ministry,
and became an able minister of the gospel of our Lord Jesus Christ.

In 1698 he travelled abroad in the work of the gospel, and went into Yorkshire,
and through the east parts of England, till he came to London;
and after his return home he travelled in the same service into Scotland,
and visited all the meetings of Friends in that nation.
After his return thence, he went into the southern and western parts of England;
and three years after, he visited all the meetings of Friends in Ireland,
and most of the meetings in England and Wales.

In the Eighth month, 1705, he began to be much out of health,
and yet attended Friends`' meetings till the middle of the Tenth month following.
On the 21st of the same, several friends sitting by him, he,
being sensible of God`'s salvation, said in admiration thereof to the Lord, "`To thee,
to thee, be salvation and praise!
This is a day of great salvation.`"
He signified what great mercy it was that the Lord should visit us in our young years,
and reveal his blessed truth to us,
and how unworthy many were before the Lord did make bare the arm of his salvation;
further saying, "`How near has the Lord been to me in the time of my sickness!
Although I have formerly felt much of his power and presence,
yet never enjoyed such plenty thereof,
as since I have been visited with this sickness;`" instancing one night,
wherein he could not sleep,
he enjoyed more abundantly of the love of God than at any other time before.

He said, "`Oh! what an excellent thing it is to keep in the truth,
and visit one another in the life of it.`"
He made a great difference between those who visit
the sick in the sense of the divine life,
and other visitors, who no sooner meet but they begin to talk of their worldly affairs.
He said, "`Friends, get into an inward acquaintance with the Lord in spirit,
for it is a good thing to retire to the rock; there is safety, there is good standing,
an excellent bottom, and room enough.`"
He further said, "`If any go out of the bounds of truth,
thinking thereby to bring others in,
they will find themselves to be in slippery places;`" and "`Beware of joining with false,
unsettled spirits.`"

Another time, two friends sitting by him, he felt the power and presence of the Lord,
and sang praises to him after an heavenly manner, saying, "`My heart is full,
though I can truly say, I have no desire to speak,
but as I feel it spring from the life.`"
On the 28th of the Tenth month he said, "`As I lay on my bed very weak of body,
I thought I could never die better, for I felt my salvation sealed unto me.
Oh! love God, love God, for he is worthy.
You may love any thing else too much, but you can never love God too much.
Oh! what hath he done for my soul; he hath given me everlasting comfort; it is enough;
it is enough, indeed.`"

He said, moreover, "`There are two things which are to my great satisfaction:

[.numbered-group]
====

[.numbered]
_1st._ "`That ever since the Lord manifested himself to me,
I have freely given up myself to his requirings, and delivered his word faithfully,
and have not sought to please men, neither did I look for great things.
What I desired was, that I might have a place amongst the sanctified.

[.numbered]
_2ndly._
"`I have always been against libertine spirits, and have had no familiarity with them;
these things are now my comfort.`"

====

He also said, "`Oh!
I have seen glorious things, yea, such things as I never saw before.
I beheld a friend lately deceased in a glorious place, and that I was to be with him;
and I said it is enough to be there.
Oh! such salvation!`"
Again, "`I am glad I can say, O death, where is thy sting; and grave,
where is thy victory?`"
Another time, some friends visiting him,
he related to them how the Lord had raised him from nothing to bear a testimony for him,
and wheresoever the Lord drew me I have followed him,
both in this nation and other nations, and sought not favour and interest among men.

He warned and cautioned the negligent to be diligent and faithful,
and come up in the service of truth; and said,
"`The Lord will cause a dreadful day to overtake
the disobedient and the negligent;`" saying,
"`It is sealed to my soul, that it hastens on apace.`"
He often said at times, in great weakness of body,
"`I desire to be dissolved and to be with Christ, but the Lord`'s will be done;`" adding,
"`The Lord`'s presence is here;`" giving thanks for his divine help, saying,
"`I never wanted comfort from him in this time of sickness.
Friends, it is an excellent thing to have a conscience void of offence towards God.
Keep your hearts clean.
I have discharged my duty to all people,
so that I find nothing but that I am fully clear; I am fully clear.`"

After a little time he broke forth in a sweet harmony,
and lifted up his voice in prayer to the Lord, which had been very low several weeks,
saying, "`Lord God! though my exercises and pain of body abound,
thy power and life do much more abound,
and carry me over all;`" fervently begging of the Lord to
be with all his faithful labourers all the world over,
rendering thanks for his glorious appearance, saying, "`Worthy, worthy, art thou, O Lord,
of all honour, thanksgiving and praise.`"
He prayed for an easy passage out of this world, which the Lord granted him;
for about the second hour the same day, in the afternoon, he fell asleep,
and twelve hours after, he said to a friend present, "`Lay my head better;`" which done,
he said,
"`Now I will fall upon my sleep,`" and immediately
went away as if he had fallen into a natural sleep.

He died the 12th of the Twelfth month, 1705, at the house of James Wilson, at Aba,
near Kendal; and the 15th of the same month was buried at Brigflats, near Sedbergh.

[.asterism]
'''

ANNE CAMM, late wife of Thomas Camm, of Camm`'s-Gill, was daughter of Richard Newby,
in the parish of Kendal, in Westmoreland, a family of good repute,
being always religiously inclined.
Her father was convinced of the blessed truth in 1652, and died therein a faithful man.
Anne Camm was born in the Eighth month, 1627;
and was well educated in learning proper for her sex.
About the thirteenth year of her age,
she was sent up by her parents to an aunt at London,
where she became acquainted with a religious people called Puritans.
Her stay in London was about seven years, from whence she returned to Kendal.
After some time there, she removed to the city of York,
and dwelt in a family of great account in the world, her mistress being a pious woman,
after whose decease she returned again to Kendal,
her society still being with the most religious where she came.

At Kendal there was a seeking people, who met often together,
sometimes sitting in silence, other times in religious conferences,
and often in fervent prayer.
John Audland living remote, yet sometimes fell in amongst them; and about the year 1650,
John Audland and she married,
and they were both convinced of truth in the beginning of 1652,
by the ministry of that honourable servant of Christ, George Fox.
So powerfully did God, by his sanctifying word and spirit, work upon them,
that they were thereby made effectual instruments in his hand,
to preach the gospel unto others in the next year, 1653, and so forward,
until the Lord put a period to their days.

The first place the said Anne Audland was called of the Lord to visit, except about home,
was the county of Durham, about the beginning of the year 1654,
and she preached truth to the people in the town of Aukland, in the said county,
on a market-day, for which she was imprisoned in the town jail,
where she spoke to the people through the window,
and several were affected with her testimony; and towards evening she was discharged.
John Langstaff, who was of great repute among his neighbours, owned her testimony,
and went with her into prison, and when released brought her to his house;
but John`'s wife being no Friend, chid with her husband,
which made Anne very uneasy to stay there.
So she walked out in the fields to seek some covert place to take up her lodging in;
but Anthony Pearson, of Rampshaw, a late justice of the peace,
who lived some miles distant, having knowledge by George Fox, who was at his house,
of Anne`'s coming to that town, came with a horse and pillion,
and took her home to his house that night.

After her service in those parts was over, she returned home;
and in the winter following, she, with Mabel Camm, wife of John Camm,
travelled through Yorkshire, Derbyshire, Leicestershire, into Oxfordshire,
to the town of Banbury, where Mabel Camm had a concern to go to the steeple-house;
and spoke to the priest and people, and Anne accompanied her.
Whereupon the people rudely hurried them out of the house, and abused them in the yard.
The priest passing by, Anne Audland said, "`Man, behold the fruits of thy ministry.`"
Next day they were sent for before the mayor,
who had got two witnesses to swear Anne had spoken blasphemy,
for which they committed her to prison.
Mabel Camm was dismissed, and travelled to Bristol, where she met with her husband,
John Camm.

After some days, two men in Banbury gave bond for her appearance at the next assize,
by which she was a kind of prisoner at large,
which gave opportunity for her to have several meetings with the people in the town.
Her two bonds-men, and several hundreds more, came to be convinced of truth,
and turned to the Lord Jesus Christ,
being the fruits of that effectual powerful ministry God had called her to bear,
so that many were added to the church,
and a large meeting of Friends there was in that town,
and several other meetings in the country adjacent were settled.
For this cause their adversaries were angry,
and they threatened that she should be burned when the assize came.

When the assize came, John Audland, John Camm, and Thomas Camm were there,
and some Friends from London and Bristol;
and the substance of the charge or indictment drawn up against her was,
that she had said God did not live,
because she had said concerning the priest at Banbury,
that "`True words may be a lie in the mouth of some that speak them;`" alleging,
Jer. 5:2, "`And though they say the Lord liveth,
(which nothing can be more true,) surely they swear falsely.`"

The judge of the court was moderate,
observing her sober and wise answers to his questions, and her innocent boldness,
and comely personage, and seeing the uncertainty of the evidence against her,
and that the matter of fact charged, did not amount to what was designed,
gave the matter to the jury thus, viz.,
"`That she acknowledged the Lord her God and Redeemer to live,
and that there were gods of the heathen and of the Philistines that were dead gods.`"
Some upon the bench perceiving their end would not be answered,
went off to influence the jury to bring in something against the prisoner,
lest they should come off with discredit.
One of the bench observing the injustice in that matter, stepped off also, telling them,
he would sit no longer with them, till more justice was amongst them,
and was convinced of truth.
Other officers in the court threw away their staves,
and bore testimony against their arbitrary proceedings.

The jury returning into court, and being asked if they were agreed,
they answered they were; and being asked what they found, they made answer,
"`Only misdemeanour.`"
A friend present told them it was illegal to indict
her for one fact and bring her in guilty of another;
for they ought to have found her either guilty or not guilty,
upon the matter of fact charged in the indictment.
The judge told Anne, if she would give bond for her good behaviour,
she might have her liberty.
She refusing, they sent her to prison again: but the judge was heard to say,
that the prisoner should have been discharged,
but the judge had a mind somewhat to please the angry justices.

Her adversaries were confounded, and slipped off the bench one after another,
in disorder, without dismissing the court, so that truth was that day exalted,
and the Lord`'s power magnified in frustrating the designs of wicked men.
The prison where Anne was sent to, was a close nasty place, several steps below ground,
on the side whereof was a sort of common-sewer,
that received much of the mud in the town, that at times did stink sorely;
besides frogs and toads did crawl into the room, and no place for fire,
yet she was in great content because it was God`'s cause.

Her fellow-prisoner was Jane Waugh, a labourer in the gospel,
who came some months before to visit her, and was committed to prison with her;
but God`'s presence and peace being with them, made their nasty stinking jail a palace,
where she remained seven or eight months, and from her first commitment,
about a year and a half, and was at last discharged by the mayor and aldermen.
The same day Richard Farnsworth was set at liberty, who,
with other men Friends were prisoners in another room;
but Jane Waugh still continued a prisoner.

Anne had frequent meetings in Banbury before she left it;
and also went to the mayor to demand the liberty of her friend Jane Waugh,
who was imprisoned for no other fact,
than for coming many miles in love to visit her in prison,
and she was soon after set at liberty.
Being clear of those parts, she travelled through the counties to Bristol,
where she met with her husband John Audland.
John and Anne Audland continued in their service and labour
in the ministry in several parts of this nation,
south, west, and northward, until John Audland fell sick,
and died in the latter end of the year 1663,
having been married to his wife Anne about thirteen years, and left behind one daughter,
since dead, and one son named John, born a few days after his father`'s death.

The 30th of the Third month, 1666, Thomas Camm married the said Anne Audland,
and they lived together in true love, serving the Lord forty years wanting six months.
She was one with her husband in all his services and sufferings,
as at one imprisonment three years at Kendal,
he not being permitted so much as to see his family; another time at Appleby,
near six years, during the first part of which he was straitly confined, the latter,
through favor of the sheriff and jailor, he had much liberty.
They travelled together in the work of the ministry into the southern parts of the nation,
as London and Bristol, etc., especially at London.
About twenty-six years ago, she had like to have died in that city,
as also of later years at Bristol.

The last time she was there, she was brought nigh the grave;
at which time she expressed many heavenly sayings,
that will not be easily forgotten by some, warning all to prize their time,
and prepare for their latter end, as God had inclined her to do,
so that she enjoyed unspeakable peace here,
with full assurance of eternal rest and felicity in the world to come, which, said she,
I have desired to enter into as gain, rather than to live, if God so please.

It was her manner often to retire alone in her closet, or some private place,
exercising herself in fervent prayer,
and to set apart some time almost daily for reading the holy Scriptures,
and other good books,
and she was very diligent in frequenting meetings for the worship of God, etc.
She was not forward to appear in preaching or prayer in public meetings,
but when she did, it was fervent, weighty, and with the demonstration of the spirit,
and with power, to the refreshment of the church, her doctrine dropping as dew,
but with zeal to lay waste the mountain of Esau.

She had wisdom to know the time and season of her service,
in which she was a good example to her sex,
for without extraordinary impulse and concern,
it was rare for her to preach in large meetings,
where she knew there were brethren qualified for the service of such meetings.
She was grieved when any, especially of her sex, were too hasty, forward,
or unseasonable in their appearing in such meetings; and would give advice to such,
not without good effect.
She behaved herself as an humble servant of her Lord and Master, Christ Jesus,
washing his disciples`' feet, and helping and serving, as a nursing-mother,
the weakest and tenderest of the flock of Christ,
and was an encourager of those who came forth in a testimony for God,
though but of a stammering tongue.

The last opportunity she had amongst friends was the 2nd of the Ninth month, 1705,
at a monthly-meeting at Kendal; and notwithstanding her great age and weakness of body,
with the coldness of the season, she would not excuse herself from that day`'s service;
and the Lord was with her in good counsel and advice to friends,
pressing all to faithfulness and diligence in their service for God,
that they might receive their reward with those who had nearly served out their day.
The next day her illness began.
About the 16th of the said month, finding her husband under concern,
because of her sickness, she said as followeth:

"`My dear,
if it be the Lord`'s good pleasure, who joined us together, and has blessed us hitherto,
to separate us outwardly, I entreat thee be content therewith,
and give me freely up to the Lord, for thou knowest we must part,
and if I go first it is but what I have desired of the Lord many a time.
I believe the consideration of the desolate condition I should be in,
if left behind thee, will have that place with thee,
that thou wilt the more freely commit me to the Lord, whose I am, and whom I loved,
feared and served with an upright heart all my days.
His unspeakable peace I enjoy, and his saving health is my portion forever.
I pray thee be content with what the Lord pleaseth to do with me; whether life or death,
his holy will be done.
Let us, my dear, leave all to the Lord.
However it be, it will be well.
I have loved thee with my soul, and God has blessed us, and will bless thee,
and be with thee, and make up all thy losses.
Death is gain to me, though it be thy loss, and for my gain`'s sake,
I hope thou wilt bear with patience thy loss.
I bless the Lord I am prepared for my change.
I am full of assurance of eternal salvation, and a crown of glory,
through my dear Lord and Saviour Jesus Christ, whom God the Father has sent to bless me,
with many more, by turning us from the evil of our ways into the just man`'s path,
which shines more and more to the perfect day.
If God now please to finish my course, and take me out of this earthly tabernacle,
I am well content.
I am clear, and have discharged myself in the sight of God to all Friends,
except something of late has been upon my mind,
to send Friends in the south a farewell epistle,
especially to Friends about Bristol and Banbury.
She said the substance thereof was the remembrance
of her dear love to them all in the truth,
with tender advice to the professors of truth, to walk in, and keep to,
the simplicity thereof, out of heights and exaltedness,
under the power of the cross of Christ,
by which they will be more and more crucified to the world, and baptized into Christ,
and put him on, the new and heavenly man, in whom they will become new creatures,
and enabled to serve God in spirit,
and keep to the unity thereof in the bond of peace and love,
which the god of the world is still labouring to break and dissolve.
I have seen him at work to make a breach and separation amongst Friends,
and if he prevail,
it will be under specious pretences of a more angelical
appearance than at any time before,
and will be a bait taking to all that live above the cross and true self-denial.
I would all were warned to stand their ground in the power of God,
which only can bruise Satan, and preserve out of his subtle baits and snares.`"

Next day several Friends came to see her, to whom she gave good advice and counsel,
"`To prize their time: and oh!
I bless my God,`" said she, "`that I lie now in great peace,
And content of mind and soul, though my body be held with pain.
Oh! that it may be so with you all, my dear friends.`"
When she was very weak, some Friends would ask her if she knew them; "`Yes,`" said she,
"`I know you every one.
I have my understanding as clear as ever, for how should it be otherwise,
since my peace is made with God through the Lord Jesus Christ.
I have no disturbance in mind,
therefore is my understanding and judgment so good and clear,
for it were sad to lie under affliction of body and mind, to feel pinching pangs of body,
even to death, and to want peace with God.

Oh! that would be intolerable to bear.
Oh! let my soul praise the Lord for his peace and plenteous redemption.`"
Her son-in-law, John Moore, having skill in physic, administered somewhat to her,
after which they thought she was better, and he was gone towards Swarthmore.
She soon grew worse again; upon which her husband would have sent for him back,
and also for her daughter, but she was unwilling, saying, "`Be not careful in the matter;
the Lord my God is near me, and I have thy company, and it is enough,
and all will be well.
If this lump of clay, in which I dwell, be dissolved,
I have full assurance of an house and dwelling, God is the maker of,
that will never wax old, nor be dissolved.
Oh! my soul, bless thou the Lord, and be glad in his salvation forevermore.`"

Her illness increased upon her, and many friends came to visit her, to whom she said,
"`Oh! the cross is the only way to the crown immortal.
Shun it not, therefore, lest you fall short of the crown;
and stand up nobly for your testimony to the truth in all things,
and particularly against the popish antichristian yoke of tithes,
for which many have not only suffered great spoil of goods, but imprisonment till death,
and have received a crown of life.
Oh! if all that have been called to this testimony, had stood firm and true therein,
God would have wrought wonders more abundantly, but unbelief makes a long wilderness;
it is well if some die not in it, and never see the promised land.`"

About two days before she died, she gave good advice to her grandchildren and servants,
and said to her husband, "`My dear,
thou hast spent much time and strength in serving truth and Friends;
thy reward with God is sure.
I never grudged thy absence in that good service; and if it be the time of our parting,
as I think now it will, I pray thee quit thyself of the things of this world,
as much as may be,
that thou mayest with the more freedom pursue that
honourable service for truth to the end of thy days.
I hope the Lord will give thee strength to travel into the southern parts again,
and remember my love to all friends, and warn all, but especially the rich, to keep low,
and not be high-minded, for humility and holiness are the badge of our profession.
God Almighty keep us all low and humble; it is a safe and blessed state.
And, my dear, one thing I beg of thee; give me up freely to the Lord.
The Lord joined us, and gave us to each other; let us bless his name,
if he now take us from each other in the outward, that is all;
for our joining in spirit stands and remains forever.
Oh! therefore let me go easy out of this world,
where I have had a great share of trouble many ways thou knowest,
and get to that haven of rest, that I have the full assurance of sealed upon my spirit.`"

A little before she died, some fainting fits taking her, she revived again, and said,
"`I was glad, thinking I was going to my eternal rest without disturbance.`"
Again she said,
"`I have both a sight and sense of eternal rest with God in the world to come;
and therefore I labour hard to be swallowed up in immortal life,
and to be made possessor of that rest that cannot be disturbed, where sorrow will cease,
and be no more forever. Oh! my soul, this is thy glorious portion; therefore bless thou the Lord,
and wait patiently his good and appointed season.`"

Then she desired to be helped up in her bed; but her pains increased:
she grew very weak and faint, and said, "`Methinks I grow weak and cold.
My hands and feet are grown very cold, yet my heart is very strong before it yields.
I must meet with sharper pangs than I have yet felt.
My God has hitherto laid a gentle hand upon me.`"

She desired to lie down again, but could not stay, but being set up in bed again,
she said, "`This pain is hard to flesh and blood, but must be endured a little time;
ease and eternal rest is at hand.
I am glad I see death so near me.
Oh! remember me to all my dear babes and grandchildren.
I shall with these eyes behold them no more.
God Almighty bless them all, and make them all his children,
that I may enjoy them forever in the heavens above.
Neither shall I see my sons and daughter.
Ah! my prodigal son, what shall I do for him?
I have prayed and longed for his return.
The time may come, God grant it may, but I shall not see it in my time.
He is my son, the son of a godly father, and therefore I cannot but love him.
Tell him it is his immortal soul`'s well-being that I am concerned for;
not so much his outward state here, for that, though never so miserable,
will quickly end, but the misery of the soul separated from God will never end.
And, my dear, though our counsel has not had the desired end, yet I do entreat thee,
remain a father to him in repeated counsel.
Leave him not to run on in the way of misery, but labour and pray for his return.
Oh! thou hast been true to me in bearing with me many a heavy burden,
and hast done abundance for him every way, for my sake;`" with more to that purpose.
"`My love to his wife; I desire she may mind heavenly things,
and pray God bless their offspring, that they may walk in the steps of their grandfather,
who is gone to his eternal rest; with well-wishes for her son and daughter Moore,
and blessings upon their children.`"

The day she died, many friends came to see her, being their monthly meeting-day,
to whom she gave good advice, and expressed her joy and comfort in the salvation of God,
peace and perfect redemption.
Seeing friends weep, she said, "`Be not concerned, for all is well;
I have only death to encounter, and the sting of it is wholly taken away;
the grave has no victory, and my soul is ascending above all sorrow and pain.
So let me go freely to my heavenly mansion, disturb me not in my passage.
My friends, go to the meeting, let me not hinder the Lord`'s business,
but let it be chief, and by you all done faithfully,
that at the end you may receive your reward, for mine is sure.
I have not been negligent, my day`'s work is done.`"
Friends went to the meeting, and in a little time her pains increased,
which she bore with patience, but sighed deeply,
praying the Lord to help her through her agony of death.

After some words, she said, "`Oh! my God, oh! my God, thou hast not forsaken me,
blessed be thy name forever.
Oh! my blessed Lord and Saviour who suffered, for me and all mankind,
great pains in thy holy body upon the cross, remember me, thy poor hand-maid,
in this my great bodily affliction.
My trust is in thee, my hope is only in thee, my dear Lord.
Oh! come, come, dear Lord Jesus, come quickly, receive my soul.
To thee I yield it up; help me now in my bitter pangs.`"
These indeed were very great, and her husband prayed by her,
that the Lord would make her passage easy; and she had no more such pangs,
but drew her breath shorter by degrees, and said very little more,
but that it was good to leave all to the Lord; saying, "`Oh! pray, pray,
pray,`" and so fell asleep in the Lord, in a good old age,
being in her seventy-ninth year, as a shock of corn in season.
She died the 30th of the Ninth month, 1705, and was honourably buried:
many ancient Friends of about thirteen adjacent meetings accompanied her to the grave,
the 3rd of the Tenth month, 1705,

[.the-end]
END OF THE THIRD PART
