== The Introduction.

Pursuant to the title is the following collection made, viz. to promote piety,
and excite all to live the life of the righteous,
that they may be blessed in their death, and welcomed after,
with the loving invitation of the Lord Jesus Christ, viz. "`Come,
ye blessed of my Father,
enter into the kingdom prepared for you from the foundation of the world.`"
Also to show that they are those that truly believe in God, and the Lord Jesus Christ,
his dear Son, who came from him,
who receive that power through which they are enabled to do righteousness,
and by him only are made righteous; it is such that promote piety.

The knowledge only of what is right and good, the profession thereof,
or being educated in the doctrines of the Christian religion,
will not entitle any to eternal happiness, if the doing part be wanting.
For piety is not promoted by a bare notion and profession, or saying prayers,
hearing sermons or declarations, but by a holy life, and a rightly ordered conversation.
Nor is salvation known to any of the professors of Christianity, from sin whilst here,
or from eternal wrath hereafter,
by any other way than by faith and obedience unto Christ.

For they that fear God, and work righteousness whilst here,
will find acceptance with God, and enjoy his favour.
As they continue faithful therein unto death, they shall have the crown of life,
whether young or old.
As they fear the Lord, he teaches them, and they learning of him,
come to be established in righteousness, and know their peace to be great whilst here,
and inherit glory in God`'s kingdom hereafter.
But if any pretend to love Christ, and continue doing evil, such keep not his commands,
abide not in his doctrine, nor love him;
for by their evil doing they declare they hate the light,
and by living in iniquity are found in that which is hateful in God`'s sight;
from all which he in great love sent his Son to redeem mankind.

It is therefore by me tenderly desired, for the promotion of piety,
that all may think of God, and seriously consider their latter end; love, receive,
and learn of the light, grace, and spirit of God, which is in them,
and shows what is evil, and reproves them, when they think, speak, or do amiss.
This spirit will give unto all who join with it, a good understanding,
teach them to prize and improve their present time,
and strengthen unto every good word and work, and preserve them, whether young or old,
in that fear towards God, which Abraham had, who was God`'s friend, of whom,
when God had tried him, he said, "`Now I know thou fearest me.`"

Oh! how excellent is the fear of God! so generally and worthily commended;
though by many too little minded, and lived in;
which is the cause piety is no more promoted.
But that it may be by all that profess and desire to be God`'s people and children,
let them learn and live in that holy fear, which Moses wrote of, Duet. 4:10. saying,
that the people should learn to fear God all the
days that they should live upon the earth;
for all those that do not fear God, but love and live in sin, the Lord of hosts, said he,
will be a swift witness against them.
But if mankind fear him as they ought, and think upon his name,
the Lord of Hosts hath said, they shall be his.

Let not, therefore, the love of the world, or the things of it, or the fading vanities,
sinful pleasures, or evil lusts that are therein, either of the eye, the flesh,
or pride of life, be followed by any that would promote piety, and die happily,
and live eternally.

Note 1. I esteem myself obliged in the following
account to give hints of some of the labours,
services, and sufferings of the deceased,
the better to lead to the meaning of some of their expressions,
and to show forth the virtue and excellency of that faith they had in Christ,
who suffered and died for them, and that it was not only given to them to believe,
but also to suffer for his name`'s sake.

2+++.+++ To excite all that have not received Christ, the true light, to receive, believe in,
love and obey him faithfully unto death.

3+++.+++ As a memorial of the deceased, and for the sake of the living, that they,
by the dying sayings of the deceased may be stirred up, as aforesaid,
to remember and prepare for their latter end, and to make a blessed conclusion here,
and then to be favoured with the like assurance in their last moments,
as the deceased mentioned in the following accounts had, to the comfort of their souls,
and satisfaction of their near and dear relations and friends,
who were the more confirmed in the belief of what they said,
being then about to launch into eternity,
at which time the awakened conscience dares not dissemble,
that desires to be happy hereafter.

If reading the following treatise, written for these ends,
be in any wise instrumental to the good of the living,
to excite them to prepare for their latter end, as I pray God it may,
my design will be answered, and the Great God, through Jesus Christ,
shall have the praise, for he is worthy forever, saith my soul.

J+++.+++ Field
