== Preface.

Impartial Reader, the Author`'s design in continuing these collections,
having already been discovered in his two former treatises upon this subject,
to be no less than the promoting of piety,
I hope I shall not need to recommend this third part of his so necessary,
useful and commendable labours to thy serious perusal, especially in such an age as this,
wherein impiety is so sensibly promoted, not only by the notoriously profane,
but also by the presumptuously careless professors of Christianity.

How much conducing to obtain this excellent end, the dying words,
even of the worst of men, and malefactors, have been esteemed,
is evident by the practice of most governments in exposing them to public view,
as a warning against vice, and incentive to virtue.
How much more shall we count the dying words of the righteous,
whose death is precious in the eyes of the Lord, likely to answer this end,
and therefore worthy, with their lives and names, to be had in everlasting remembrance.

Although the short reflections given upon the birth, conversion, labours, travels,
conversation,
and sufferings of many of these precious servants and handmaids of the Lord,
are very inviting, as well as instructive,
in showing forth that free and universal grace of God,
whereby they came to be what they were,
and that arm of power whereby they were upheld in,
and delivered out of many tribulations; yet the main intention of the Author is,
to send us to the house of mourning, which, saith Solomon,
is better to go to than the house of rejoicing; that we may learn so to live,
as to be prepared to die, and enter upon an eternal state.

If death-beds were more frequented, and places of recreation less,
we might hope the advantage would make amends for that part of self-denial.
There we may often hear a more reaching sermon in a few broken words,
than the most elegant in the pulpit;
but especially from two sorts of experienced teachers, namely, sinners repenting,
and saints triumphing: there we may hear all agreeing in one common prayer,
viz. Oh! let me die the death of the righteous, and let my latter end be like his.
There we may hear men discovering what they really believe,
often very differently from what they formerly professed;
and many with the repenting thief, come to have a better religion upon their death-bed,
than all their life-long before.
There we may hear those who have been eagerly pleading for sin,
now crying out against it as the sting of death.

Those who have exclaimed against good works, as dangerous to their faith,
now wishing that all their time had been spent in going about doing good.
Those who have charged God foolishly with an absolute reprobation, now trusting in,
and begging his universal mercy.
Those who have known Christ after the flesh only, now desiring to feel him within,
as the hope of glory.

Those who have grieved, resisted, and mocked at the holy spirit,
now seeking for strength and comfort from it.
Those who have opposed the light of Christ,
now gladly embracing it in the dark valley of the shadow of death.
Those who have lived upon outward observations,
and been feeding upon husks with the prodigal,
now looking towards their Father`'s house for the substance, the water of regeneration,
the bread of life, and the new wine of the kingdom.

There we may hear teachers, tutors, confessors, and such like,
who have had people`'s faith and conscience at their command, often exclaimed against,
if not as bad examples, yet as miserable comforters, and physicians of no value.
Now names, notions, creeds, traditions, controversies, honours, riches, compliments,
pastimes, etc., are little regarded when death, the king of terrors, is in view,
and the great Judge stands at the door, who, without respect of persons,
judgeth and rewardeth according to every man`'s work.
Now nothing will administer comfort but the inward absolution of our holy high priest,
the Lord Jesus Christ;
nothing but the unction of the blessed spirit of intercession and adoption.
Here those who have loved God above all, and their neighbours as themselves,
are found to have the best religion, and to be the true believers in Christ,
and witnesses of his redemption and salvation;
and those to be the true and most honourable scholars,
who have been taught by the grace of God, which brings salvation,
and hath appeared unto all men, to deny ungodliness and the world`'s lusts,
and to live soberly, righteously and godly in this present world.

There we may find the righteous, with Abraham, Isaac, Jacob and Joseph, advising,
encouraging and blessing their posterity; with Moses going up to the top of the mount,
to take a view of the good land, in retirement and solitariness with the Lord;
with Joshua engaging others to fear and serve him alone,
and to put away their strange gods; with Samuel,
mourning and praying for those who have forsaken the Lord; with David,
expressing their faith in his promises concerning their house,
and their religious concern for their building of his; recommending truth,
justice and mercy to succeeding generations;
with Hezekiah appealing to God about their sincerity. 

In short, with Job, Simeon, Stephen, Paul,
and others of the faithful servants and followers of Christ, embracing death,
hastening to meet it, longing to be dissolved and to be with him, their captain,
fore-runner and rewarder.
Thus preaching and praying, and praising the Lord freely and fervently,
boldly and experimentally, and all without book, as the holy spirit gives utterance,
has upon a death-bed often proved an affecting,
tendering and converting season to many hearers.

To such an house of mourning, or shall I say rejoicing,
the Author of these collections kindly invites thee, Christian reader; where,
by hearing the dying songs and sayings of the ransomed and redeemed,
who knew in whom they had believed,
thou mayest also come to know and believe in that great and true light,
which enlightens every man coming into the world; for it was by the inshining thereof,
that the feet of these blessed ones, now at rest with the Lord,
as of all the righteous ages past, were guided into the way of truth and peace.

This opened their states, tried their reins, sifted their words, weighed their actions,
stayed their minds, changed their hearts, condemned disobedience, justified faithfulness,
counselled in difficulties, discovered the enemy, unveiled the painted harlot, the world,
and the false church, and gave them the light of the knowledge of the glory of God,
in the face of Jesus Christ, for whose sake they suffered the loss of all,
and followed him in the regeneration and self-denial,
and are now entered with him into that rest which remains for the people of God.

Christopher Meidel.
