== Preface

The book you have in hand was compiled,
edited and printed by William Backhouse and James Janson,
two members of the Society of Friends (Quakers), in the year 1813.
A second edition was prepared and printed in 1815,
which altered only a few Scripture citations,
changing them from the Vulgate Version to the Authorized English Version (KJV).

This book is unique among the publications of the Society of Friends
in that it does not originate from the pen of a Quaker,
but is rather a compilation of excerpts written by three so-called "`mystic`"
writers who lived and died within the pale of the Roman Catholic Church.
Now, early Friends were a decidedly Protestant society,
having found great cause (with many others) to part with the church or Rome in
many particular points of doctrine and practice (such as Papal infallibility,
inquisitions, bloody crusades and persecution against dissenters,
prayers to and for the dead, the selling of indulgences,
the doctrine of transubstantiation, purgatory,
along with various superstitious ceremonies and manifest
forms of corruption.) It would nevertheless,
in the opinion of this editor,
be both uncharitable and unwise to therefore reject or discount all of
the writings of the many pious and sincere seekers of truth who lived,
loved Christ, wrote, suffered, and died,
at times and in places where the church remained entirely under papal dominion.
Some of these honest and faithful seekers of truth were Francis Fenelon,
the Archbishop of Cambray, Jeanne Guyon (both of France),
and Michael de Molinos (of Spain), all of whom in the late 1600`'s and early 1700`'s,
were persecuted, punished,
or banished by the Church of Rome for holding views and publishing works that stressed
the great necessity of experiencing both the inward life of Christ in the soul,
and the inward death of self on His cross.
And although it can be truly asserted that there were differences
in certain points of doctrine or practice,
both between these three writers themselves,
as also between their writings in general compared to those of early Quakers,
I think it can hardly be denied that,
with respect to a great many fundamental doctrines
and realities relating to the inward nature,
experience, and effect of the gospel of the Lord Jesus Christ,
they all spoke with one voice (and I believe by one Spirit).

The attentive reader will find the views of Fenelon, Guyon,
and Molinos represented in this treatise to be in sweet agreement with the doctrines
of early Friends on many important subjects,
such as: the Light of Christ that enlightens every man coming into the world;
the inward experience of Christ`'s coming and kingdom in the heart;
the purifying work of grace in the soul of the believer;
the living faith which is a gift of God;
the necessity of turning inward to the light and grace of Christ, man`'s true Teacher;
the importance of watching, waiting,
and continually communing with Christ in the heart by prayer;
the fact that all men are called to this inward communion with God,
and not only a predestined few;
the need for diligent watchfulness over the heart
at all times "`for from it flow the issues of life;`"^
footnote:[Proverbs 4:23]
the ways and reasons that God employs trials, dryness,
and tribulation for the purging and polishing of His vessels;
the necessity of self-denial at all times;
the need to experience a veritable
crucifixion of the self-life by obedience to the power of the Spirit,
and resignation to the Lord in all trials and difficulties;
and the possibility of perfection, or an experienced union with God,
on this side of the grave, etc.

The following quotation from Gerhard Tersteegen (who was neither
Catholic nor Quaker) seems worthy of insertion in support of the
publication of this treatise by the Society of Friends.

[quote]
____
Amongst those elect and God-devoted souls are also particularly to be reckoned those,
who are generally called "`Mystics,`" (that is, secret or hidden,) whose writings,
next the Holy Scriptures,
contain a true definition of real inward Christianity and genuine divinity.
It is true,
that most of them lived and were known with their writings in the Romish church;
yet in bearing testimony to the truth, I must say,
that the sincere amongst them were more evangelical and reformed than most protestants.
I mean to say, they were real inward Christians,
who did not continue clinging to externals,
but served and worshipped God in spirit and in truth,
by withdrawing their affections and confidence from all created things, from themselves,
and from all their own works, through true faith and union with God in Christ.
And although I do not approve nor defend all the minor points
and external incidents that occur in such writings,
yet it is certain, that more divine unction, light, counsel, comfort, and peace,
for a soul that is seeking after God,
is to be found in a single page of the true mystic writings,
than is often contained in many folio volumes of weak and watery school divinity,
as many enlightened divines amongst the protestants themselves concur in testifying.

But why is it that such valuable works are generally so little esteemed and used?
Is it not because an inquisitive curiosity does not find
food in them?--Is it not that the nature of the old man,
and the life of self is too severely attacked?--And is it not because they do not require
to be reasoned and speculated upon (like other books which are accommodated to the taste
of the old Adam) but rather insist upon mortification and self-denial?
____

[.signed-section-signature]
Jason Henderson

[.signed-section-context-close]
Dec. 2022
