== Introduction

It was said by our blessed Redeemer that, "`They who worship the Father,
must worship Him in Spirit and in Truth.`"^
footnote:[John 4:24]
Now the object of this work is to explain, in a simple and familiar manner,
how this one true worship can be acceptably performed, and how inward,
spiritual prayer can be rightly attained.
Few authors have written with greater clearness upon this subject,
than those from whose works this little volume has been chiefly compiled; these,
therefore, have been preferred.
At the same time, it has been thought necessary to simplify,
and render more intelligible, some of their terms,
in order that they may be more generally understood.

While some into whose hands this little treatise
may fall may receive it as a messenger of glad tidings,
there will doubtless be others who may not feel disposed to place much dependence upon
the simple manner of drawing near to their Creator which is here pointed out.
Let such, however, not judge according to appearances; but,
laying aside all reasoning thereon,
let them in humility and simplicity make a trial of it,
and feel for themselves whether what is herein stated will not
prove to be something more than an empty dream of the imagination,
or a cunningly devised fable.
And, if they do this in sincerity of heart,
they will soon have to acknowledge (to their great
consolation) that these are indeed substantial,
efficacious, and incontestable Truths;
and that this is indeed the true way to become purified from our many defilements,
to be instructed in heavenly mysteries, to taste of the wine of the kingdom,
and to partake of that bread which nourishes up unto everlasting life.

[.signed-section-signature]
William Backhouse & James Janson

[.signed-section-context-close]
1815
