== Chapter 2. On Faith

There are two sorts or degrees of Faith.
The first is that by which the mind gives its assent to
the truth of a thing based upon the testimony of another.
The second is of a more excellent nature, being of Divine origin,
and is a gift of the Holy Spirit.
By the first,
we believe in the existence of God and in the truths
which He has revealed to us in the Holy Scriptures.
This is an essential thing in the beginning of the spiritual path;
for "`he that comes to God, must believe that He is,
and that He is a rewarder of them that diligently seek Him.`"^
footnote:[Hebrews 11:6]
And if we put our whole trust in Him, and endeavor in all things to obey Him,
we shall be in a state of preparation for the reception
of that true and _living faith_ which is "`the gift of God.`"^
footnote:[Ephesians 2:8, Hebrews 12:2]

It is only by this living faith that we shall be
enabled to overcome all of our spiritual enemies,
and to clearly understand those mysteries which are incomprehensible to human reason.
For reason, being born of man, is weak and uncertain and easily errs; but true faith,
being born of God, cannot err.
Reason, therefore, must always follow and submit to this living faith,
and not go before or seek to control it.

It is by faith that, "`being justified,
we have peace with God through our Lord Jesus Christ.`"^
footnote:[Romans 5:1]
And when this precious gift has been granted to us, it produces in us hope,^
footnote:[Romans 5:2]
love,^
footnote:[1 Peter 1:8]
confidence,^
footnote:[Ephesians 3:12]
joy,^
footnote:[Romans 5:2]
and holiness^
footnote:[Acts 15:9]
of heart.
We shall then be enabled to feel an entire dependence on the goodness, power, justice,
and mercy of God, and a confidence in His promises;
as well as more fully experience and comprehend the operations of His Spirit on the mind.

Faith is an essential prerequisite for the proper performance of all our duties to God.
Indeed, without it we cannot possibly please Him;^
footnote:[Hebrews 11:6]
neither would we ever be induced to seek Him,
or believe in the influence of His Holy Spirit upon our souls.
It is by faith that we are supported in our path to peace,
and are enabled to persevere through the difficulties and
besetments which we may have to encounter on our way.
It is through this holy gift that we suffer the pains of dryness,
and the lack of consolation, without fainting; being thereby strengthened to "`endure,
as seeing Him who is invisible.`"^
footnote:[Hebrews 11:27]
And it is only by faith that we can attain to the practice of true, inward,
and spiritual prayer.
