== Chapter 3. On Prayer.

Prayer is the communion of the soul with God.`"^
footnote:[God is a Spirit; so is the soul.
Bodies can experience interaction and communion; so can souls.
When souls have been assimilated into a state of purity,
they then have union with their Maker.
This was the bliss of Paradise.
Sin interrupted it, and so holiness must restore it.
To a soul thus distressed,
the Creator communicates Himself in a manner which is as
insensible to the natural eye as the falling of dew;
but it is not less refreshing in its secrets powers to the inner
man than the dew is to vegetation.--Anonymous Essay on Devotion.]
It is not a work of the head, but of the heart, and one which ought always to continue.
It is the medium through which life and food are conveyed to the soul,
and the channel through which gifts and graces of the Holy Spirit flow and are communicated.
Every secret longing of the soul towards God is prayer.
And all people are therefore capable of prayer, and are called to it,
just as all are called to and are capable of salvation.

St. Paul has enjoined us to "`pray without ceasing;`"^
footnote:[1 Thessalonians 5:17]
and our Lord says: "`I say unto all, watch and pray.`"^
footnote:[Mark 13:33,37, and 14:38]
Come, then, all you who are thirsty, to these living waters;^
footnote:[Revelation 22:17]
and do not lose your precious moments in "`hewing out cisterns that will hold no water.`"^
footnote:[Jeremiah 2:13]
Come, you famishing souls who find nothing whereupon to feed; come,
and you shall be fully satisfied.
Come, you poor afflicted ones, who groan beneath your load of wretchedness and pain,
and you shall find ease and comfort.
Come, you sick, to your Physician,
and be not fearful of approaching Him because you are filled with diseases;
expose them to His view, and they shall be healed.

Children, draw near to your Father, and He will embrace you in the arms of Love.
Come, you poor, stray, wandering sheep, return to your Shepherd.
Come, you who have been seeking happiness in worldly pleasures and pursuits,
but have failed to find in them the satisfaction you expected.
Come and learn how to be truly happy here, and eternally happy hereafter.
Come sinners, to your Savior.
Come, you dull, ignorant, and illiterate;
you who think yourselves the most incapable of prayer.
You are indeed more peculiarly called and adapted thereto.
Let all, without exception, come; for Jesus Christ has called us all.

You must however learn a kind of prayer which may be exercised at all times,
which does not obstruct outward employments,
and which may be equally practiced by all ranks and conditions of men;
by the poor as well as the rich, by the illiterate as well as the learned.
This cannot, therefore, be a prayer of the head, but rather of the heart.
It is a kind of prayer which nothing can interrupt but unregulated and disordered affections.
And though you may think yourselves ever so dull, and incapable of sublime attainments,
yet, by prayer, the possession and enjoyment of God is easily obtained.
For He is more desirous to give Himself to us than we can be to receive Him.

Prayer is the guide to perfection, and to all the sovereign good.
It delivers us from every vice, and obtains for us every virtue;
for the one great means to become perfect, is to walk continually in the presence of God.
He himself has said: "`Walk in my presence, and be perfect.`"^
footnote:[Genesis 17:1]
It is only by prayer that we are brought into, and maintained in, His presence;
and when once we have fully known Him, and the sweetness of His love,
we shall find it impossible to relish anything so much as Himself.
