[#four, short="All Capable of Prayer"]
== Chapter 4. All Are Capable of Attaining to Inward, Spiritual Prayer

If all were willing to pursue the spiritual path,
then shepherds while they watched their flocks,
might have the Spirit of the primitive Christians,
and farmers at the plough might maintain a blessed union and communion with God,
and tradesmen while they exhausted their outward man with labor,
would be renewed in internal strength.
Every sort of vice would soon disappear,
and all mankind would become true followers of the Good Shepherd.

Oh when once the Lord has gained the heart, how easily is all moral evil corrected!
It is for this reason that God, above all things, requires the heart.
It is the conquest of the heart alone that can extirpate
all dreadful vices which are so predominant among men.
Jesus Christ would become the universal and peaceful Sovereign,
and the hearts of all mankind would be wholly renewed.

The decay of inward piety is unquestionably the source
of the various errors that have arisen in the world;
all of which would speedily be sapped of their strength
and overthrown if true inward religion were established.
If, instead of engaging our erring brethren in vain disputes,
we would but teach them simply to believe, and diligently to pray,
we would lead them sweetly unto God.
Oh how inexpressibly great is the loss sustained
by mankind from their neglect of the inward life!

Some excuse themselves by saying that this is a dangerous way,
or pleading the incapacity of simple persons to comprehend spiritual matters.
But the Scriptures of Truth affirm quite the contrary.
Isaiah says: "`The way-faring man, though a fool, shall not err in this way.`"^
footnote:[Isaiah 35:8]
And where can be the danger of walking in the only true way--which is Jesus Christ^
footnote:[John 14:6]--giving ourselves up to Him, fixing our eye continually on Him,
placing all our confidence in His grace,
and turning with all the strength of our soul to His pure love?

Simple people, so far from being incapable of this perfection,
are by their teachableness, innocency, and humility,
peculiarly adapted and qualified for its attainment.
And because they are not accustomed to reasoning, they are less employed in speculations,
and less tenacious of their own opinions.
Because of their lack of learning,
they often submit more freely to the teachings of the Divine Spirit;
whereas others who are blinded by self-sufficiency and enslaved by prejudice,
give great resistance to the operations of grace.

We are told in Scripture, "`that unto the simple, God gives understanding;`"^
footnote:[Ps. 119:130]
and we are also assured that God cares for them: "`The Lord preserves the simple.`"^
footnote:[Ps. 116:6]
Christ said to His Apostles; "`Let the little children to come unto Me,
for of such is the kingdom of Heaven.`"^
footnote:[Matthew 19:14]
If the simple are incapable of reasoning, then teach them the prayer of the heart,
not of the head; the prayer of God`'s Spirit, not the prayer of man`'s invention.

Alas, it is by expecting them to pray in elaborate forms,
and being meticulously critical therein, that you create their chief obstacles.
Many children have been led astray from the best of fathers,
by endeavoring to teach them such refined and polished language.

The simple and undisguised utterances of filial love are
infinitely more expressive than the most studied language.
The Spirit of God needs none of our complex arrangements and methods.
When it pleases Him, He easily turns shepherds into prophets.
And He is so far from excluding any from the temple of prayer,
that He throws wide open the gates that all may enter in; while wisdom cries out,
"`Whoever is simple, let him turn in here!
And as for him who lacks understanding, Come,
eat of my bread and drink of the wine I have mixed.`"

To teach men to seek God in their own heart, to think of Him,
to return to Him whenever they find they have wandered from Him,
and to do and suffer all things with a single eye to please Him,
is the most natural and easy course.
It is leading the soul to the very source of grace,
wherein is to be found all that is necessary for sanctification.

Oh, that all would immediately put themselves into this way, which is Jesus Christ,
that His Kingdom might be established in their hearts!
For as it is the heart alone that can oppose Christ`'s sovereignty,
it is by the subjection of the heart that His sovereignty is most highly exalted.
And since none can attain this blessed state besides
those whom God Himself leads and places therein,
so we do not pretend to introduce any into it,
but only to point out the shortest and safest road that leads to it.
And we beseech you not to be hindered in your internal progress by any external exercises,
nor to rest in the shadow instead of the substance.
If the water of eternal life was shown to some thirsty souls,
how inexpressibly cruel would it be to confine them to a sequence of external forms,
and thereby prevent their approaching it,
so that their longing shall never be satisfied but only perish with thirst!

Oh you blind and foolish men, who pride yourselves on science, wisdom, wit, and power!
How well do you verify what God has said,
that His secrets are hidden from the wise and prudent, and revealed unto little ones,
or babes!`"^
footnote:[Matthew 11:25]
