== Chapter 5. Method of Attaining to True Prayer

The sort of prayer to which we have alluded is that of inward silence,
wherein the soul--withdrawn from all outward things, in holy stillness, humble reverence,
and living faith--waits patiently to feel the Divine Presence,
and to receive the precious influences of the Holy Spirit.
And when you retire for this purpose, which should be your frequent practice,
you should consider yourself as being placed in the presence of God,
looking with a single eye to Him, resigning yourself entirely into His hands,
to receive from Him whatsoever He may be pleased to dispense to you; calmly endeavoring,
at the same time, to fix your mind in peace and silence,
quitting all your own reasonings, and not purposely thinking on anything,
however good or profitable it may appear to be.
And should any vain imaginations present themselves to your mind,
you should gently turn from them,
and thus faithfully and patiently wait to feel the Divine Presence.

If, while you are thus engaged, something of inward stillness,
or a degree of the softening influence of the Divine Spirit,
is mercifully granted to you,
you should prize these manifestations of the Presence of God in your soul,
and be carefully and reverently attentive thereto; being cautious, however,
not to endeavor to increase them by your own activity.
For by doing so,
you will draw your mind off from that state of holy stillness and humble
watchfulness which you should seek as much as possible to maintain.
And by attempting to fan the flame there is a danger of extinguishing it,
and thus depriving your soul of that nourishment which was intended for it.

A living sense of the Presence of God will speedily
disentangle us from numberless mental wanderings,
remove us far from external objects, and bring us near unto our God,
who is only to be found in our inmost center, which is the Temple wherein He dwells.^
footnote:[1 Corinthians 3:16]
And when we are thus fully turned inward,
and warmly penetrated with a sense of His Presence,
we should permit the blessed food we have tasted to sink deep into the soul,
in stillness and repose, with reverence, confidence, and love.

The prayer of inward silence is the easiest and most profitable path,
because with a simple turning of the attention to God,
the soul becomes like a humble supplicant before its Lord;
or as a child that casts itself into the safe bosom of its mother.
It is also the most secure,
because it is withdrawn from the operations of the imagination,
which being always exposed to the delusions of the enemy, is often beguiled into excess,
and is easily bewildered and deceived, so that the soul is thereby deprived of its peace.

Because of the habit the mind will have acquired of being always away from home,
roving here and there from one subject to another,
it will at first be difficult to restrain it,
and to free it from those wanderings which are an impediment to prayer.
Indeed these wanderings of the imagination with which beginners are for some time tried,
are permitted in order to prove their faith, to exercise their patience,
and to show them how little they can perform of themselves;
as well as to teach them to depend upon God alone
for strength to overcome all their difficulties;
"`for by his own strength, no man shall prevail.`"^
footnote:[1 Samuel 2:9]
But if these will place all their hope in Him, and faithfully persevere,
every obstacle will be gradually removed,
and they will find that they will be enabled to approach Him with ease.
Inward silence will not only be attained with much less difficulty,
but at times it will be found to be easy, sweet, and delightful.
They will then know that this is the true way of finding God;
and feel "`His name to be as ointment poured forth.`"^
footnote:[Song of Solomon 1:3]

And although we should at all times be very watchful and diligent in recalling our wandering
thoughts and restraining them as much as possible into a proper subjection,
yet a direct contest with them only serves to augment and irritate them.
However, by calling to mind that we are in the presence of God,
and endeavoring to sink down under a sense and perception
of this truth by simply turning inwards,
we wage a very advantageous, though indirect, war with them.

Now, those who have not learned to read, are not, on that account, excluded from prayer;
for the great Teacher who teaches all things is Jesus Christ Himself.^
footnote:[John 14:26]
These should learn this fundamental rule: that "`the Kingdom of God is within them;`"^
footnote:[Luke 17:21]
and that it is there only where it must be sought.

"`The Kingdom of God is within you,`" says our blessed Redeemer.
Abandon, therefore, the cares and pleasures of this wretched world,
and turn to the Lord with all your heart, and your soul shall find rest.^
footnote:[Matthew 11:28-29]
If you withdraw your attention from outward things,
and keep it continually fixed on the internal Teacher,
endeavoring to obey Him in whatsoever He may require of you,
you will soon perceive the coming of the kingdom of God.^
footnote:[Matthew 6:10]
For the kingdom of God is that "`peace and joy in the Holy Spirit,`"^
footnote:[Romans 14:17]
which cannot be received by sensual and worldly men.

It is for lack of this inward retirement and prayer that our lives are so imperfect,
and that we are neither penetrated nor warmed with the divine
Light of Truth--Christ the Light of the world.^
footnote:[John 1:9]
We should, therefore be in the daily practice of it;
and there are none who are so occupied that they cannot
find some moments for inward retirement to God.
The less we practice silent prayer, the less desire we will have for it;
for our mind being set upon outward things, we soon contract such a habit of doing so,
that it is very hard to turn it inward.

"`The Lord is in His Holy Temple, let all the earth keep silence before Him.`"^
footnote:[Habakkuk 2:20]
The silence of all our earthly thoughts and desires is absolutely indispensable
if we desire to hear the secret voice of the Divine Instructor.
Hearing is a sense created to _receive_ sounds, and is rather passive than active.
It receives, but it does not communicate sensation.
And if we desire to hear the Lord, we must lend our ear to Christ, the eternal Word,^
footnote:[Revelation 19:13]
without whose Divine inspeaking the soul is dead, dark, and barren.
And when He speaks within us,
it requires the most silent attention to His life-giving and efficacious voice.

We should therefore forget ourselves, and all self-interest,
and listen and be attentive to the voice of our God.
Outward silence is very requisite for the cultivation and improvement of inward silence;
and indeed, it is impossible to become truly inward,
without the love and practice of outward silence and retirement.
And it is unquestionably true that our being inwardly engaged with God is very incompatible
with being continually busied and employed in the numerous trifles that surround us.

When through inadvertency or unfaithfulness we become distracted or dissipated,
or (as it were) uncentered,
it is of immediate importance to turn again gently and peacefully inward;^
footnote:[This is not a turning inward __to ourselves__,
or to anything that man has or is by nature.
It is a turning inward to the working, teaching, correcting, shining,
crucifying and vivifying that is the work of the Spirit of God,
who appears (as He has always done) in His temple.]
and in this way we will learn to preserve the spirit
and unction of prayer throughout the day.
For if the prayer of inward silence were wholly confined to any appointed half-hour,
or hour, we should reap but little fruit.

And it is of the greatest importance for the soul to go to prayer with both confidence,
and with such a pure and selfless love as seeks nothing
from God but the ability to please Him and to do His Will;
for a servant whose diligence is only proportional to his hope of reward,
renders himself unworthy of all reward.
Go then to prayer, not that you may enjoy spiritual delights,
but that you may be full or empty, just as it pleases God.
This will preserve you in a steadiness of spirit in times of feeling desertion or consolation,
and will prevent your being surprised at dryness, or at the seeming repulses of God.

Constant prayer is to keep the heart always right towards God.
Strive then, when you come from prayer,
not to allow your mind to be too much entangled with outward things,
endeavoring to be totally resigned to the Divine Will,
that God may do with you and yours according to His heavenly pleasure,
relying on Him as on a kind and loving Father.
And though you may be taken up with your outward affairs,
and your mind is thereby prevented from being actually fixed on Him, even then,
you will always carry a fire with you that will never go out;
but which (on the contrary) will nourish an inward secret prayer
that will be like a lamp continually lit before the throne of God.

A son who loves his father does not always think distinctly of him;
many objects draw away his mind, but these never interrupt the filial love.
And whenever his father returns into his thoughts, he loves him,
and feels in the very inmost part of his heart that
he has never discontinued one moment to love him,
though he has sometimes ceased to think of him.
In this manner we should love our heavenly Father.

It is by true religion alone that we are enabled to call God our Father,
and that we can indeed become His sons.
But true religion is a heaven-born thing,
it is an emanation of the truth and goodness of God upon the spirits of men,
whereby they are formed into a similitude and likeness of Himself,
and become "`partakers of the Divine Nature.`"^
footnote:[2 Peter 1:4]

A true Christian is in every way of a most noble descent,
of a heavenly and divine pedigree, being born, as St. John expresses it, "`from above.`"^
footnote:[John 3:3. See the marginal reading.]
And in another place he says;
"`Behold what manner of love the Father has bestowed upon us,
that we should be called the sons of God!`"^
footnote:[1 John 3:1]

If considerations such as these are not sufficient to convince
us of the folly of our attachment to perishing things,
and to stimulate us to press after much greater and glorious privileges, we must, indeed,
have sunk into a state of deep and deplorable insensibility.
And as our Lord has declared, even "`if one were to rise from the dead,`"^
footnote:[Luke 16:31]
it would yet be impossible to arouse us.
