== Chapter 6. On Spiritual Dryness

No sooner will you have given yourself up to serve the Lord in this inward way,
than He will begin to purify you, and try your faith,
in order to draw you even nearer to Himself.
And, for this purpose, He will lead you through the paths of dryness and desertion;
so that often,
when you endeavor to fix your mind in silence in order to feel after your God,
you will not experience the comfort and refreshment you expected.
On the contrary,
you will be more than usually beset with a multitude
of troublesome and unrelenting imaginations,
insomuch, that you will begin to think that you labor to no purpose,
and that the prayer of inward silence is an attainment to which you need not aspire,
seeing that your imagination is so ungovernable, and your mind so void of good.
But this state of dryness is very profitable, if it be endured with patience.^
footnote:[__Note from Jeanne Guyon:__
"`If you wish to receive real profit from the Holy Scriptures and other spiritual books,
you must peruse them with deep attention and introversion of mind, observing,
whatever you have chosen, to read only a small part of it;
endeavoring to taste and digest it, to extract the essence and substance thereof;
and proceed no further while any savor or relish remains in the passage.
When this subsides, take up your book again, and proceed as before,
seldom reading more than half a page at a time; for it is not the quantity that is read,
but the manner of reading that yields us profit.
Those who read fast,
reap no more advantage than bees would do by only skimming over the surface of a flower,
instead of waiting to penetrate into it, and extract its sweets.
If this method were pursued, we should be more fully disposed for retirement and prayer.]

The Lord makes use of this veil of dryness for various ends,
one of which is that we may not know what He is working in us, and so may be kept humble.
For if we felt and knew distinctly what He was working in our souls,
satisfaction and presumption would doubtless get in.
We would imagine we were doing some good thing, and reckon ourselves very near to God,
and this self-complacency would prevent real spiritual advancement.

Therefore, though in this prayer of inward stillness,
you may feel yourself to be in a dry and comfortless state,
not being able to get rid of your troublesome thoughts, nor experience any light,
consolation, or spiritual feeling, yet be not afflicted,
nor desist from your undertaking.
Rather resign yourself at that time with determination,
and patiently persevere as in His presence; for, while you persevere in that manner,
your soul will be inwardly improved.

Do you believe that when you come away from prayer in the same condition as you began it,
without feeling yourself profited thereby, that you have been toiling in vain?
That is a fallacy; because true prayer consists,
not necessarily in the enjoyment of light and spiritual knowledge,
but in enduring with patience, persevering in faith and silence,
believing that you are in the Lord`'s presence,
and continually turning your heart to Him with tranquillity and simplicity of mind.

We must be aware that fallen nature is always an enemy to the Spirit; and that,
when she is deprived of sensible pleasures, she remains weak, melancholy,
and full of irritability.
Hence from the uneasiness of your thoughts, the laziness of your body,
nagging desires after sleep,
and the inability to restrain your senses (every
one of which desires to follow its own pleasure),
you will often feel impatient to come to the end of your prayer.
Happy are you if you can persevere amidst this painful trial!
Remember, that "`They who wait upon the Lord shall renew their strength;
they shall mount up with wings as eagles; they shall run and not be weary,
they shall walk and not faint.`"^
footnote:[Isaiah 40:31]

The prayer of internal silence is well exemplified by that wrestling in which
the Holy Scriptures say the patriarch Jacob strove all night with God,
until the day broke and He blessed him.
Therefore, the soul is to persevere,
to wrestle with the difficulties that it will meet with in inward prayer,
without desisting, until the Sun of internal Light begins to appear,
and the Lord gives His blessing.

If you go to prayer with the spirit and intention of praying,
so long as you do not retract that intention (though
through the predominance of evil and frailty,
your thoughts may wander), you will, nevertheless, pray in spirit and in truth.
God, in His own due time, will help you to overcome all your difficulties; and,
when least you expect it,
He will give you holy inclinations and more effectual desires after serving Him.
Do not distrust Him, therefore, but only yourself; and remember, as the apostle says,
that "`He is the Father of mercies, and God of all comforts.`"^
footnote:[2 Corinthians 1:3]
His comforts are sometimes withdrawn, but His mercy endures forever.
He only deprives you of what is sweet and sensible
of His grace because you have need of being humbled.

Be of good courage then,
and though it may seem to you that you toil often without gaining much advantage,
yet you must recollect, we must plough and sow before we can reap;
and if you persevere in faith and patience,
you will reap an abundant reward for all your labors.
Would you be so unreasonable as to expect to find without seeking,
or to suppose that the door will be opened without your taking the pains to knock?
The farmer might as well expect to see his fields waving with grain,
without having taken the trouble to put seed into the ground.

It is no hard matter to adhere to God while you are
in the enjoyment of His comforts and consolations;
but if you would prove your faithfulness to Him,
you must be willing to follow Him through the paths of dryness and desertion.
The truth of a friend is not known while he is receiving favors and benefits;
but if he remains faithful when treated with coldness and neglect,
it is a proof of the sincerity of his attachment.

Though God has no other desire than to impart Himself to those that love and seek Him;
yet He frequently conceals Himself from us that we may be roused from slothfulness,
and induced to seek Him with fidelity and love.
But, with what abundant goodness does He recompense our faithfulness!
And how sweetly are the seeming withdrawings of His
presence followed by the consolations of His Love!
David says, "`I waited patiently for the Lord; and He inclined unto me, and heard my cry.
He brought me up also out of a horrible pit, out of the miry clay,
and set my feet upon a rock, and established my goings.
And He has put a new song in my mouth; even praises unto our God.`"^
footnote:[Ps. 40:1-3]

In seasons of the withdrawings of His Presence,
we are apt to believe that it will be a proof of our fidelity,
and evince the ardor of our love,
to seek Him __by an exertion of our own strength and activity;__
and that this exertion will induce Him more speedily to return.
But this is not the right way when we find ourselves in this state.
With patient resignation, with self-abasement,
with repeated breathings of an ardent but peaceful affection,
and with reverential silence, we must await the return of our Beloved.
Thus, only, shall we demonstrate that we seek nothing but Himself and His good pleasure,
and not the selfish delights of our own sensations.

When we feel the sweetness of the grace of God,
it is very common for us to suppose that we love Him;
but it is only in the withdrawings of His Presence that our love can be tried,
and the measure of it truly known.
It is in these seasons that we are convinced of the weakness and misery of our nature,
and how incapable we are, of ourselves, to think or do any good thing.
There are many who, when they experience melting of heart, shedding of tears,
and other sensible delights, imagine that they are the favorites of God,
and that they then truly possess Him;
and so they often pass the rest of their lives seeking
after more of these pleasurable sensations.
But these should be cautious lest they deceive themselves.
For these consolations, when they proceed from the natural man,
and are occasioned by their own reflections or self-admiring,
hinder them from discerning the true light, or taking one real step towards perfection.
We should therefore be attentive to distinguish the touching of our emotions or affections,
from those operations which proceed purely from God,
leaving ourselves to be led entirely by Him,
who will be our light in the midst of darkness and dryness.

It is of no small advantage in prayer to patiently suffer the lack of consolation,
and the trouble and tenacity of a wandering imagination;
for this is an offering up of one`'s self as a whole burnt offering and sacrifice.
And as you exercise yourself in calmly rejecting your vain thoughts,
and peacefully enduring your dark and desolate state,
it is as though the Lord were setting so many crowns upon your head.
It is therefore of great importance that you endeavor
at all times to keep your heart in peace,
that you may keep pure the temple of God.
And the way to keep it in peace, is to enter into it by means of inward silence.

When you see yourself more sharply assaulted, retreat into this region of peace,
and you will find a fortress where you will be enabled to triumph over your enemies,
visible and invisible, and over all their snares and temptations.
Within your own soul resides Divine Aid, and Sovereign Help.
Retreat within, and all will be quiet, secure, peaceable, and calm.
Thus, by means of inward silence--which can only be attained by Divine
Help--you may begin to experience tranquillity in tumult,
solitude in company, light in darkness, serenity in pressures, vigor in despondency,
courage in fear, resistance in temptation, peace in war, and quiet in tribulation.
