[short="On Defects and Weakness"]
== Chapter 7. On Defects and Weakness

If we should get so far off our guard as to again
wander among external things in search of happiness,
or sink into dissipation, or commit a fault, we must instantly turn inwards;
for having departed thereby from our God, we should as soon as possible return unto Him,
and patiently permit whatever sensations He is pleased to impress upon us.
For He has declared, "`As many as I love, I rebuke and chasten.`"^
footnote:[Revelation 3:19]
On the commission of a fault,
it is of great importance to guard against vexation and disquietude,
which spring from a secret root of pride, and a love of our own excellence;
for we are only pained by feeling what we really are.
And if we discourage ourselves, or let ourselves sink into despair,
we are thereby the more enfeebled; for from a continued reflection upon our fault,
a fretfulness arises, which is often worse than the fault itself.

The truly humble soul is not surprised at its defects or failings;
and the more miserable and wretched it beholds itself,
the more it abandons itself to God and presses for
a nearer and more intimate alliance with Him,
that it may avail itself of His eternal strength.
We should be even more induced to act thus, as God Himself has said:
"`I will instruct you and teach you in the way which you shall go;
I will guide you with My eye.`"^
footnote:[Ps. 32:8]
