[short="On Temptations and Tribulations"]
== Chapter 8. On Temptations and Tribulations^
footnote:[Or "`trials`", and so throughout this chapter.
In the King James Version,
// lint-disable invalid-characters
the Greek word πειρασμός is generally translated "`temptations`",
as in James 1:1-2:12, 1:14 etc.,
but most modern English translations render this word "`trials`".]

Although "`God cannot be tempted by evil, nor does He Himself tempt any man;`"^
footnote:[James 1:13]
yet it is evident that temptations are permitted for our good, and, if rightly endured,
they tend to our refinement.
"`Therefore,`" says the apostle,
"`count it all joy when you fall into various temptations; knowing this,
that the trying of your faith works patience.`"^
footnote:[James 1:2]
And in all our trials, however painful they may feel to us,
or of whatever nature they may be, we should remember that it is said:
"`Blessed is the man that endures temptation; for when he is tried,
he shall receive the crown of life, which the Lord has promised to those who love Him.`"^
footnote:[James 1:12]

We are by nature so evil, proud, and ambitious, and so full of our own appetites,
our own judgments and opinions,
that if temptations and tribulations were not permitted to try, humble, and purify us,
we would never arrive at a state of acceptance with God.

The Lord, seeing our misery and perverse inclinations,
and being thereby moved to compassion,
often withdraws His strength from us that we may feel our own weakness;
allowing us to be assaulted by violent and painful motions of impatience and pride,
and various other temptations.
And some, who have long been in the practice of sin,
are permitted to be assailed by gluttony, luxury, rage, swearing, despair,
and a great many other aggravations, in order that they may know themselves,
and be humbled.
With these temptations, Infinite Goodness humbles our pride,
and gives us in them the most wholesome medicine.

"`All our righteous deeds,`" as Isaiah says, "`are as filthy rags;`"^
footnote:[Isaiah 64:6]
because of the vanity, conceitedness, and self-love with which they are defiled.
It is therefore necessary that they should be purified
with the fire of temptation and tribulation,
so that they may be made clean, pure, perfect, and acceptable in the sight of God.
The Lord polishes the soul which He draws to Himself with the rough file of temptation,
freeing it thereby from the rust of many evil passions and propensities.
By means of trials and tribulations, He humbles, subjects, and exercises it,
showing it its own weakness and misery.
In this way He purifies and strips the heart,
that all of its operations may be made pure and useful.
Oh, how happy would you be if you could quietly believe that
all the trials and tribulations with which you are assaulted,
are permitted for your gain and spiritual profit!

Perhaps you will say that when you are harassed by others,
or wronged and injured by your neighbor,
that this cannot be for your spiritual advantage,
seeing it is the effect of another`'s fault and malice.
But this is no other than a cunning and hidden device of the enemy.
For though it is true that God does not will the sin of your neighbor,
yet He wills His own good effect in you;
and the trouble which accrues to you from another`'s fault should improve you,
by increasing your patience and exercising your forbearance and charity.

Consider how the Lord makes use of the faults of others for the good of your soul.
Oh, the greatness of divine wisdom!
Who can pry into the depths of the secret and extraordinary means, and the hidden ways,
whereby He guides the soul which He desires to purge, transform, and dignify?
Indeed, it is sometimes the greatest temptation to be without temptation,
because then we are most liable to fall into a state of lukewarmness.
We therefore ought not to repine when temptation assaults us; but with resignation,
peace, and faithfulness, we must shut our hearts against it.
If you desire to serve God, and arrive at the sublime experience of internal peace,
you must pass through this rugged path of temptation and tribulation,
and therein be polished, purged, renewed, and purified.

A direct contest and struggle with temptations often serves to augment them,
and can withdraw the soul from that adherence to God which should
ever be its principal occupation to strive after and maintain.
The surest and safest method of conquest, is simply to turn away from the evil,
and draw yet nearer and closer to God.
A little child, on perceiving a monster, does not wait to fight with it,
and will scarcely turn its eyes towards it;
but quickly shrinks into the bosom of its mother in total confidence of safety.
So likewise should the soul turn away from the dangers of temptation, and flee to its God.
"`God is in the midst of her,`" says the Psalmist, "`she shall not be moved.
God shall help her, just at the break of dawn.`"^
footnote:[Ps. 46:5]
"`The name of the Lord is a strong tower; the righteous flee to it and are safe.`"^
footnote:[Proverbs 18:10]

If we do otherwise, and in our weakness attempt to attack our enemies,
we shall frequently feel ourselves wounded, if not totally defeated.
But, by casting ourselves into the presence of God, and relying solely on Him,
we shall find supplies of strength for our support.
This was the help sought for by David: "`I have set the Lord always before me,`" he says,
"`because He is at my right hand, I shall not be moved.
Therefore, my heart is glad, and my glory rejoices.
My flesh, also, shall rest in hope.`"^
footnote:[Ps. 16:8-9]
And, it is said in Exodus, "`The Lord shall fight for you,
and you shall hold your peace.`"^
footnote:[Exodus 14:14]

You cannot be hurt by men or devils if you always keep near to your God; for,
"`Who is he that will harm you, if you become followers of that which is good?`"^
footnote:[1 Peter 3:13]
But if you are hurt, it is your pride, your passions,
and your many unsubdued evil propensities, that rise up and injure you;
and as long as these remain, the enemy will make use of them,
and seek to draw your mind away from adherence to God.

"`Every man is tempted, when he is drawn away by his own desires and enticed.`"^
footnote:[James 1:14]
Therefore know your own corrupt state,
and the need you have of being purified by trials and temptations.
And keep always on the watch,
lest the unwearied enemy gain access to your soul by his insinuations and pleasing allurements,
which he will suit to your present situation and condition.
For in your passage through life,
there are many things which he will offer you as temptations,
endeavoring to produce in you an inordinate inclination and desire for them;
which if you give way to while you are in this manner tempted,
great will be the danger of your being wholly overcome.

If the malignant enemy is not resisted in his first attack,
he enters by gradual advances, in order to take entire possession of the heart.
And so long as opposition is deferred by habitual negligence,
our power of opposing becomes every day less,
and the strength of the adversary is proportionally greater.
Therefore, when you feel in yourself a strong and eager desire after something,
and find your inclination carrying you too hastily to do it,
strive to moderate yourself by retreating inwards.
To do all things well, we must do them as in the presence of God,
otherwise we shall soon get off our right center,
and be in danger of being wholly overthrown.

Oh blessed soul,
if you would but be content and quiet in the fire of temptation and tribulation,
and allow yourself to be fully proved and tried,
patiently enduring the assaults of the enemy and the withdrawing of heavenly good,
how soon would you find yourself rich in eternal treasures!
How soon would the Divine bounty make a rich throne in your soul,
and a pleasant habitation for you to refresh and comfort yourself in!
Know this: that although the Lord may _visit_ for a season,
yet He takes up His _abode_ in none but peaceful souls--that is,
those in whom the fire of temptation and tribulation has consumed all corrupt propensities.
The Lord reposes nowhere but where quietness reigns, and self-love is banished.

If, out of chaos,
His Omnipotence has produced so many wonders in the creation of the world,
what will He not do in your soul (created after His
own image and likeness) if you keep constant,
quiet, and resigned to Him, under a true sense of your own nothingness?

"`Therefore, cast not away your confidence, which has great reward.`"^
footnote:[Hebrews 10:35]
But keep constant, oh blessed soul, keep constant!
For it will not be as you imagine;
and you are never nearer to God than in such times
of desertion for the trial of your faith.
Although the sun is sometimes hid in the clouds, yet it changes not its place,
nor loses any part of its brightness.
The Lord permits these painful temptations and desertions to purge and polish you,
to cleanse and disrobe you of _self_; that through such trials you may become entirely His,
and give yourself up wholly to serve Him.

Oh how much is there to be purified in a soul that must
arrive at the holy mountain of transformation and perfection.
For while any portion of evil, anything of self remains in us,
we must be subject to trials and temptation.
But when self is crucified, there is then nothing left for the tempter to act upon.
Oh, how resigned, naked, denied,
and crucified ought the soul to be that would not hinder the entrance of the Divine Lord,
nor His continual communion with it!
