[short="On Self-denial"]
== Chapter 9. On Self-denial

He who expects to arrive at perfection, or a union of the soul with God,
by means of consolation and comfort, will find himself mistaken.
For, due to the depravity of our nature, we must expect to suffer,
and be in some measure purified before we can be in any degree fitted for union with God,
or permitted to taste of the joy of His Presence.

Be patient, therefore, under all the sufferings which God is pleased to send to you.
If your love to Him is pure,
you will not seek Him less in suffering than you do in consolation.
And, surely, He should be as much loved in the one as in the other,
since it was by suffering on the cross that He made
the greater display of His own love for you.

Be not like those who give themselves to Him at one season,
and withdraw from Him at another.
These give themselves only to be caressed,
and then wrest themselves back again when it is time to be crucified;
or at least they turn to the world for consolation.
But true consolation is found in nothing but a free
and full surrender of your will to the divine will.
Whoever does not savor the cross, cannot savor the things that are of God;^
footnote:[Matthew 16:23]
and a heart that savors the cross, finds even the bitterest things to be sweet.
"`To the hungry soul every bitter thing is sweet.`"^
footnote:[Proverbs 27:7]
God gives the cross, and the cross gives us God.
And we may be assured that there is real internal advancement
wherever there is an advancement in the way of the cross.

As soon as anything presents itself as a form of suffering,
and you feel a repugnance against it,
resign yourself immediately unto God with respect to it,
giving yourself up to Him as a living sacrifice; and so you will find that,
when the cross arrives, it will not be as burdensome,
because you have already disposed yourself to a willing reception of it.
Jesus Christ Himself was willing to suffer its utmost severity.
We often bear the cross in weakness, at other times in strength;
but all should be equal to us in the will of God.

If any other way but bearing the cross and dying to his own will
could have redeemed man from his fallen and corrupt state,
in which he lives by nature,
Christ would have both taught it and established it by His example.
But of all who desire to follow Him, He has required the bearing of the cross;
and without exception has said to all: "`If any man will come after Me,
let him deny himself, take up his cross and follow Me.`"^
footnote:[Matthew 16:24]
Why then do you fear to take up the cross,
which will direct you to the path which leads to the kingdom of God?

From the cross are derived heavenly meekness, true fortitude, the joys of the Spirit,
the conquest of self, and the perfection of holiness!
There is no redemption, nor hope of the continuation of the divine life in us,
but by our taking up the cross to our carnal appetites and inclinations.
For all consists in the death of self,
and there is no means to obtain true life and peace but
by thus dying to the corruptions of our fallen nature!
Take up your cross therefore,
and follow Jesus in the path that leads to everlasting peace.
He has gone before, bearing that cross upon which He died for you, that you might follow,
patiently bearing your own, and, upon it, dying to yourself for Him.

And if we die with Him, we shall also live with Him.
"`If we are partakers of His sufferings, we shall also be partakers of His glory.`"^
footnote:[Romans 8:17; 1 Peter 4:13]

Why do you seek any other path to glory but that in which
you are called to follow the "`Captain of your Salvation?`"
The life of Christ was a continual cross,
and do you desire a continual state of ease and joy?
Know, therefore,
that your life must be a continual death to the appetites and passions of fallen nature.
And know also that the more perfectly you die to yourself,
the more truly you will begin to live unto God.
If then you desire to enjoy true peace here,
and obtain the unfading crown of glory hereafter, it is necessary that in every place,
and in all events, you should bear the cross willingly.
To suffer the death of self, therefore, is your portion;
and to suffer patiently and willingly is the great
testimony of your love and allegiance to your Lord.

Therefore,
prepare your spirit to suffer patiently the many
inconveniences and troubles of this life;
for these you will surely find, and can never avoid,
though you run to the ends of the earth, or hide yourself in its deepest caves;
and it is only a patient suffering that can either disarm their power,
or heal the wounds that they have made.
But while every tribulation is painful and grievous,
and the desire of your soul is to avoid it, yet you cannot help but be wretched;
and the very thing you labor to avoid will follow you wherever you go.
The patient enduring of the cross, and the death of self upon it,
are the indispensable duty of fallen man.
Only thus can he be delivered from his darkness, corruption, and misery,
and be restored to the possession of life, light, and peace in Christ.

Having then no other desire but that of ardently reaching after Him,
of dwelling always with Him, and of sinking into nothingness before Him,
we should accept without distinction all that He dispenses,
whether obscurity or illumination, fruitfulness or barrenness, weakness or strength,
sweetness or bitterness, temptations, wanderings, pain, weariness, or doubting;
and none of these will truly retard our course.
