[short="On Mortification"]
== Chapter 10. On Mortification

All endeavors to merely rectify the external man,
only impel the soul yet further outward into that world
in which it is already ardently and zealously engaged,
and thus its powers are diffused and scattered abroad;
for applying itself directly to external things,
it thus invigorates those very senses it is aiming to subdue.

This kind of mortification can never subdue the passions, or lessen their activity.
The only effectual method to effect this, is true inward silence,
by which the soul is turned wholly and altogether inward to possess a present God.
If the soul directs all its vigor and energy towards Him
in the center of its being,
this simple act separates and withdraws it in some measure from the outward senses.
The exercising of all its powers internally,
leaves the outward senses more faint and impotent; and the nearer it draws to God,
the further it feels itself detached from outward things,
and the passions are less influenced by them.

In the mortification of the eye and ear--which continually supply the busy imagination
with new subjects and stimuli--there is little danger of falling into excess.
God will teach us this, and we have only to follow where His Spirit guides us.

The soul finds a double advantage by proceeding in this way; for first,
in withdrawing from outward objects, it draws the nearer to God; and second,
in approaching nearer to Him (in addition to the sustaining power
and virtue it receives) it finds itself further removed from sin.
And so at length, turning the mind inward to God becomes, as it were, habitual.
