== Chapter 11. On Resignation

We should give up our whole existence unto God,
from the strong and positive conviction that,
while we are faithfully endeavoring to follow Him,
the occurrences of every moment are agreeable to His immediate will or permission,
and just such as our state requires.
This conviction will make us resigned in all things; and accept all that happens,
not as coming from the creature, but as from God Himself.

But I entreat you--you who sincerely wish to give up yourselves
to God--that after you have made the offering of yourselves,
you do not snatch yourselves back again.
Remember, a gift once presented, is no longer at the disposal of the giver.
Resignation is a matter of the greatest importance in our spiritual progress;
it is the key to the inner court; so that whosoever knows truly how to resign himself,
soon becomes perfect.
We must, therefore, continue steadfast and immovable therein,
and not listen to the voice of natural reason.
Great faith produces great resignation.
We must confide in God, "`hoping against hope,`"^
footnote:[Romans 4:18]
like Abraham the father of faith.

Resignation is a casting off of all selfish care,
that we may be altogether at the Divine disposal.
All Christians are exhorted to resignation, for it is said to all:
"`Be not anxious for tomorrow;
for your heavenly Father knows all that is necessary for you.`"^
footnote:[Matthew 6:32,34]
"`In all your ways acknowledge Him, and He shall direct your paths.`"^
footnote:[Proverbs 3:6]
"`Commit your works unto the Lord, and your thoughts shall be established.`"^
footnote:[Proverbs 16:3]
"`Commit your way unto the Lord, trust also in Him, and He shall bring it to pass;
and He shall bring forth your righteousness as the light,
and your judgment as the noon-day.`"^
footnote:[Ps. 37:5-6]

This virtue is practiced by continually losing our own will in the will of God;
by being resigned in all things, leaving what is past in oblivion,
leaving what is to come (after having faithfully done our part) to the direction of God,
and devoting the present moment to Him;
by attributing nothing that befalls us to the creation below,
but regarding all things as from God, and looking upon all (excepting only our sins),
as infallibly proceeding from Him.
Surrender yourselves, then, to be led and disposed of just as God pleases.

We must willingly cooperate with, and unite with the designs of God;
which tend to divest us of all our own operations,
so that His may be instituted in the place thereof.
Let this, then, be done in you;
and do not allow yourself to be wrongly attached to anything, however good it may appear;
for it ceases to be good if in any measure it turns
you aside from that which God wills concerning you.

The Divine will is preferable to all other things.
And it is our conformity to this sweet yoke that
introduces us into the regions of internal peace.
Understanding this,
we may know for certain that the rebellion of our
will is the chief occasion of all our disquiet,
and that this is the cause why we suffer so much distress and perturbation.
Oh, if we did but submit our wills to the Divine will, and put all at His disposal,
what tranquillity would we feel!
What sweet peace, what inward serenity,
what supreme felicity and foretastes of blessedness!
Let us, therefore, shake off all attachment to the interests of self,
and live on faith and resignation alone.
