== Chapter 13. On True Conversion.

"`Turn, turn from your evil ways.
For why should you die, O house of Israel?`"^
footnote:[Ezekiel 33:11]
"`Turn unto Him from whom you have deeply revolted.^
footnote:[Isaiah 31:6]`"

To be truly converted, is to turn wholly away from the creature, and wholly unto God.

For the attainment of salvation,
it is absolutely necessary that we should forsake outward sin and turn unto righteousness.
But this alone is not perfect conversion,
which consists in a total change of the whole man, from an outward to an inward life.

When the soul is truly turned to God,
it finds a wonderful ease in continuing steadfast in its conversion;
and the longer it remains thus converted or turned, the nearer it approaches,
and the more firmly it adheres to God.
And the nearer it draws to Him, of necessity,
the farther it is removed from that spirit which is contrary to Him.
Thus the soul becomes so effectually established and rooted in its conversion,
that a state of conversion becomes in some measure natural to it.

Now, we must not suppose that this is effected by a violent exertion of its own powers;
for the soul is not capable of (nor should it attempt) any other cooperation
with Divine grace than that of endeavoring to withdraw itself from external objects,
and to turn inward to the Lord.
After which,
it has nothing farther to do than to continue steadfast in its adherence to God.

God has an attractive virtue,
which draws the soul more and more powerfully to
Himself the nearer it approaches towards Him.
And in His attracting, He purifies and refines it,
just as it is with an impure liquid that is evaporated by the sun; which,
as it gradually ascends, expands and is rendered pure.
The liquid, indeed, contributes to its evaporation only by its passiveness;
but the soul cooperates with the attractions of its God
by a free and affectionate correspondence and communion.
This turning of the mind inward is both easy and efficacious,
advancing the soul naturally and without constraint,
because God Himself is the center which attracts it.

Our care and attention should therefore be to acquire inward silence.
And let us not be discouraged by the pains and difficulties we encounter in this exercise,
which will soon be recompensed on the part of our God by such an abundant
supply of His strength as will render the exercise increasingly easy,
provided we are faithful in meekly withdrawing our hearts from outward objects and gratifications,
and returning to our center, with affections full of tenderness and serenity.
When at any time our passions are turbulent,
a gentle retreat inward unto a present God will easily deaden and pacify them.
Any other way of contending with them rather irritates than appeases them.
One word of our Savior in time past instantly calmed a boisterous and raging sea;
and can we now think, if we sincerely call on Him in our distress,
that He cannot calm the turmoil of the agitated soul?
