== Chapter 14. On the Crucifixion of Self

The soul becomes fitted for union with God by giving up
self to the destroying and crucifying power of Divine love.
This, indeed, is a most essential and necessary sacrifice in the Christian religion,
and the only way by which we pay true homage to the sovereignty of God.
By the destruction of the existence of self within us,
we truly acknowledge the supreme existence of our God;
for unless we cease to live in self, the Spirit of the eternal Word cannot live in us.
Now it is by the giving up of our own life, that we give place for His coming;
and in dying to ourselves, that He Himself lives and abides in us.^
footnote:[Galatians 2:20]

We should indeed surrender our whole being unto Christ Jesus,
and cease to live any longer in ourselves, that He Himself may become our life,
and that "`being dead, our life may be hid with Christ in God.`"^
footnote:[Colossians 3:3]
By leaving and forsaking ourselves, we are lost in Him,
and this can only be effected by the crucifixion of self,
which is the true praise of adoration that renders unto "`God, and unto the Lamb,
blessing, and honor, and glory, and power, forever and ever!`"^
footnote:[Revelation 5:13]

Indeed, this is the prayer of Truth.
It is "`worshipping God in spirit and in truth;`"^
footnote:[John 4:23]
for we here come to know the Spirit to help our weaknesses,
and to make intercession for us according to the will of God.^
footnote:[Romans 8:26-27]
And being thus influenced by the pure Spirit of God,
we are thereby drawn forth and freed from our own carnal and corrupt manner of praying.
We pay due honor to God only by the crucifixion of self.
And in the measure that this is accomplished, He who never allows a void in nature,
continually fills us with Himself.

Did we but know the virtues and the blessings which
the soul derives from this kind of prayer,
we would willingly be employed therein without ceasing.
For it leads to the pearl of great price; to the hidden treasure;^
footnote:[Matthew 13:44,46]
which, whoever finds, freely sells all that he has to purchase it.
It leads to the "`well of living water, which springs up into everlasting life,`"^
footnote:[John 4:14]
to the true adoration of God, and the full performance of the purest evangelical precepts.

Jesus Christ assures us that the Kingdom of God is within us;`"^
footnote:[Luke 17:21]
and this is true in two senses: First,
in the sense that God becomes so fully the Master and Lord in us,
that nothing resists His dominion; and then our interior is His kingdom.
And second, when we possess God (who is the supreme good), we possess His kingdom also,
wherein there is fullness of joy, and where we attain the purpose of our creation.
The purpose of our creation, indeed, is to enjoy our God,
even in this life but (alas!) how few there are who ever
come to experience the pure joy which His presence gives.
