[#fifteen, short="Divine Influence vs. Man`'s Will"]
== Chapter 15. Man Acts More Nobly Under the Divine Influence, than He Can Possibly Do by Following His Own Will

Some persons, when they hear of this prayer of silence,
falsely imagine that the soul remains dead and inactive;
but the truth is that the soul acts therein more nobly and
more extensively than it has ever done before;
for God Himself is its beloved, and it now acts by the agency of His Spirit.
When St. Paul speaks of our being "`led by the Spirit of
God,`" he does not mean that we should cease from action,
but that we should act through the internal agency of His grace.
This is finely represented by the prophet Ezekiel`'s vision of the wheels,
which had a living Spirit; and wheresoever the Spirit was to go, they went also.
They ascended and descended according as they were moved;
for the Spirit of Life was in them, and they "`did not turn when they went.`"^
footnote:[Ezekiel 1:9]
Thus the soul should be equally subservient to the will
of that life-giving Spirit with which it is enlightened,
and be scrupulously faithful to follow only as it moves.
Our activity should, therefore,
consist in endeavoring to acquire and maintain such
a state as may be most susceptible of Divine impressions,
and most pliable to all the operations of the eternal Word.

While a canvas is unsteady, the painter is unable to depict a true image; and likewise,
every act of our own selfish spirit is productive of false and erroneous features.
It interrupts the work, and defeats the design of this adorable Painter.
Thus we must remain in peace, and move only when He moves us.
Jesus Christ has the life in Himself, and He is the life of every living soul.^
footnote:[John 5:26]

As all action has value only in proportion to the dignity of its true cause or source,
this sort of action is unquestionably more noble than any other.
Actions produced by the Divine source or cause are Divine; but creaturely actions,
however good they may appear, are only human.
Jesus Christ, the Word, "`has life in Himself;`"^
footnote:[John 5:26]
and being communicative of His nature, He desires to communicate it to man.
We should therefore make room for the inflow of this Life,
which can only be done by the ejection of the fallen nature,
and the suppression of the activity of self.
This is agreeable to the assertion of St. Paul: "`Therefore, if anyone is in Christ,
he is a new creation; old things have passed away; behold, all things have become new.`"^
footnote:[2 Corinthians 5:17]
But this state can be accomplished only by dying to ourselves,
and to all our own activity, that the influence of God may be substituted in its place.

Man may, indeed, open the window; but it is the Sun Himself that must give us the Light.
Jesus Christ has exemplified this in the Gospel.
Martha did what was right; but because she did it in her own spirit, Christ rebuked her.
The spirit of man is restless and turbulent, and for this reason it does little,
though it would appear to do much.
"`Martha,`" says Christ, "`You are worried and troubled about many things;
but one thing is needful;
and Mary has chosen that good part which shall not be taken away from her.`"^
footnote:[Luke 10:41-42]
And what was it that Mary had chosen?
To repose in tranquillity and peace at the feet of Christ.
To all appearances she ceased to act, that the Spirit of Christ might act in her;
she ceased to live, that Christ might be her life.

St. Peter, in the warmth of his affection,
told the Lord that for His sake he was ready and willing to lay down his life.
But, at the word of a young damsel, he denied Him.

The many troubles in life come from the soul not abiding in its place,
and not being content with the will of God, and with what is afforded therein,
one day at a time.
Many souls may be resigned to the _general_ will of God,
and yet fail with respect to the present moment.
And being outside of the will of God, they fall, and renew such falls,
as long as they so continue; but when they return into the Divine will,
all will go on well.
God loves what is done in His own order, and of His own will and time;
and while you faithfully give yourself up thereto, you will do all things right.

All men have more or less of impassioned desires,
except those who live in the Divine will.
Some of these desires may appear to be good;
but if they are not according to the will of God,
the one who rests in the Divine will is infinitely more peaceful,
and glorifies God the more.
This shows us how necessary it is to renounce ourselves
and all our own activity in order to follow Christ;
and we cannot truly follow Him without being animated by His Spirit.
Now, in order that His Spirit may gain admission in us,
it is necessary that our own spirit should first be subdued:
"`He that is joined unto the Lord,`" says St. Paul, "`is one Spirit.`"^
footnote:[1 Corinthians 6:17]

All things should be done in their season.
Every state has its commencement, its progress, and its consummation;
and it is an unhappy error to stop at the beginning.
There is no skill acquired by man except what involves a necessary process.
We must first labor with diligence and toil,
and at last we shall reap the harvest of our perseverance.
When a sailing vessel is in port,
the mariners are obliged to exert all their strength
in order to clear her from there and put her to sea;
but at length they turn her with facility, just as they please.
In like manner, while the soul remains bound in sin and creaturely entanglements,
very frequent and strenuous endeavors are requisite to effect its freedom.
The cords which hold it must be loosed, and then, by strong and vigorous efforts,
it pushes off gradually from its old port.
But then, by leaving the port behind,
it proceeds to the haven to which it desires to steer.

When the vessel is thus put in motion, in proportion as she advances on the sea,
she leaves the land behind; and the farther she departs from the old harbor,
the less difficulty and labor is required in moving her forward.
At length she begins to get sweetly under sail,
and soon proceeds so swiftly in her course, that the oar, which has become useless,
is laid aside.
How is the pilot now employed?
He is content with spreading the sails and holding the rudder.
To spread the sails is to lay the mind open before God,
that it may be acted upon by His Spirit.
To hold the rudder is to restrain the heart from wandering from the true course,
recalling it gently and guiding it steadily to the dictates of the blessed Spirit,
which gradually gains possession and dominion of it; just as the wind, by degrees,
fills the sails and drives the vessel.

While the winds are fair, the mariners rest from their labors,
and the vessel glides rapidly along without their toil.
And when they are thus at rest, leaving the vessel to the wind,
they make more progress in one hour than they could have accomplished
in a great length of time by all their former efforts.
Indeed, were they now even to attempt using the oar,
they would not only fatigue themselves,
but also hinder the vessel by their ill-timed labors.

This is also the course of action that we should pursue inwardly;
and by the Divine influence it will indeed advance us in a very short
time infinitely farther than a whole life spent in repeated acts of self-exertion.
Truly, whosoever will take this path, will find it easier than any other.

If the wind is contrary and blows up a storm, instead of putting out to sea,
we must cast anchor to hold the vessel.
Our anchor is a firm confidence and hope in God,
waiting patiently for the calming of the tempest,
and the return of a more favorable breeze, even as David "`waited patiently for the Lord,
and He inclined unto him, and heard his cry.`"^
footnote:[Ps. 40:1]
We must, therefore, be resigned to the Spirit of God,
giving up ourselves wholly to His divine guidance;
never allowing ourselves to be disquieted by any occurrence;
for disquiet is the door by which the enemy gets into the soul to rob it of its peace.
Nor should we concern or busy ourselves with what others say and do,
for this will only be a cause of disturbance.

Let us calm all the motions of our heart just as soon as we see it in agitation.
Let us quit all pleasure that comes not from God alone.
Let us do away with all unprofitable thoughts and musings.
Let us diligently seek God within us, and we shall infallibly find Him; and with Him,
shall find joy and peace.
Such joy and peace endures in the midst of suffering,
and because it flows from an inexhaustible source,
becomes a perpetual fountain of delight.
"`Peace I leave with you,`" said Christ to His followers, "`My peace I give to you;
not as the world gives do I give to you.`"^
footnote:[John 14:27]

Did we but know the blessedness of hearkening unto God,
and how greatly the soul is strengthened and invigorated thereby,
all flesh would surely be silent before the Lord.^
footnote:[Zechariah 2:13]
Truly, all would be still, just as soon as He appears.
But to encourage us even further in boundless resignation to Him,
God assures us by the same Prophet,
that we should fear nothing in thus giving up ourselves to Him,
because His care for us surpasses the greatest tenderness that we can conceive:
"`Can a woman,`" He says, "`forget her nursing child,
and not have compassion on the son of her womb?
Surely they may forget, yet I will not forget you.`"^
footnote:[Isaiah 49:15]
Oh blessed assurance, full of consolation!
Who, knowing this,
shall be fearful of resigning themselves wholly to the dealings and guidance of God!

All men seek after peace, but they seek it where it is not to be found.
They seek it in the world, which is ever promising, but can never give us solid peace;
for, wherever we go,
we carry with us the fruitful source of every perplexity--our
own _unsubdued and selfish will_.
The love of liberty is one of the most dangerous passions of the heart.
If we follow this inclination, instead of true liberty, it reduces us to slavery.
As our passions are the worst of tyrants, if we obey them even partially,
we must always be in a perpetual strife and conflict within.
And if we give ourselves up entirely to them,
it is horrid to think to what extremities they will lead us; for they torment the heart,
and like a torrent, sweep all away before them, and yet never are satisfied.
True liberty is to be found only in Christ, whose truth shall set us free,^
footnote:[John 8:32]
and who shall make us experience that to serve Him is to reign.

That piety by which we are sanctified and entirely devoted to God
consists in doing His will precisely in all circumstances of life.
Take whatever steps you please, do whatever deeds you will, let them shine with luster,
yet you shall not be rewarded except for having done the will of your Sovereign Master.
Even if your servant did wonders in your house,
yet if he did not do what you required of him, you would not value his service,
and might justly complain of him as a bad servant.

There is no good spirit but the Spirit of God;
and whatever spirit removes us from the true good, is but a spirit of illusion,
however flattering it may appear.
Who would desire to be carried in a magnificent chariot on a road to the abyss!
The way which leads to a cliff is frightful, even if it should be covered with roses;
but the way that leads to a crown is delightful,
though it should be thickly set with thorns.
He has given His good Spirit to instruct us,^
footnote:[Nehemiah 9:20]
therefore, let us no longer follow our own will but His;
so that not only our religious actions, but also all others,
may be done with no other view but that of pleasing Him.
Then our whole conduct will be sanctified.
Then our deeds will become a continual sacrifice,
and incessant prayer and uninterrupted love will occupy our heart.
Therefore, let us submit to the crucifixion of our own will,
that His will may reign in us!
For it is His prerogative to command, and it is our duty to obey.
