[#sixteen, short="Chapter 16 -- Peace and Rest before God"]
== Chapter 16. On the Possession of Peace and Rest Before God

The soul that is faithful in the exercise of that love and
adherence to God which has already been described is astonished
to feel Him gradually taking possession of their whole being,
and a continual sense of His Presence may become, as it were, natural to it.
The Presence of God diffuses an unusual serenity
throughout all our faculties--it calms the mind,
and gives sweet repose and quiet even in the midst of our daily labors; and yet,
it is necessary that we continue resigned to Him without reserve.

We must however urge it as matter of the highest
importance to cease from self-action and self-exertion,
that God Himself may act alone.
He says by the mouth of His Prophet David, "`Be still, and know that I am God.`"^
footnote:[Ps. 46:10]
Yet those greatly err, who accuse this type of prayer with idleness,
a charge that can only arise from inexperience.
If they would but make some efforts towards the attainment of it,
they would soon experience the very opposite of what they suppose,
and find their accusations to be groundless.

This appearance of inaction is, indeed, not the consequence of barrenness or apathy,
but rather of fruitfulness and abundance;
and this will be clearly perceived by the experienced soul.
The interior is not a stronghold that can be taken
by the storms and violence of human effort.
It is rather a kingdom of peace which is to be taken by love.
Let us then give ourselves up to God without apprehension of danger.
He will love us and enable us to love Him; and that love, increasing daily,
will produce in us all other virtues.
He alone can replenish our hearts, which the world has agitated and intoxicated,
but never could fill.
Truly, He will take nothing away from us but what makes us unhappy.

Let us therefore no longer fear to commit ourselves wholly to God.
What risk do we run in depending solely on Him?
But those who expect all from themselves will inevitably be deceived,
and must receive this rebuke of God by His prophet Isaiah: "`Look,
all you who kindle a fire, who encircle yourselves with sparks.
Walk in the light of your fire and in the sparks
you have kindled--This you shall have from My hand,
you shall lie down in torment.`"^
footnote:[Isaiah 50:11]

As the soul advances thus far,
it has need of no other means to prepare or fit it to draw
near to the Lord besides this quietude of heart;
for now the presence of God (which is the great objective),
and a continual state of prayer begins to be powerfully felt,
and the soul experiences what the Apostle Paul says, that "`eye has not seen,
nor ear heard, neither have entered into the heart of man,
the things which God has prepared for them that love Him.`"^
footnote:[1 Corinthians 2:9]
The soul enjoys something of transcendent blessedness,
and comes to feel that "`it is no longer she that lives, but Christ that lives in her;`"^
footnote:[Galatians 2:20]
and that the only way to find Him is to turn inward to where He is present.
As we do this, we are filled with the consolations of His presence,
are amazed at so great a blessing,
and enjoy an internal communion which external matters cannot interrupt.

The same may be said of this kind of prayer that was once said of wisdom:
"`All good things come together with her.`"^
footnote:[Wisdom of Solomon 7:11]
For various virtues now flow from us into action with so much sweetness and ease,
that they appear natural and spontaneous.
