[#seventeen, short="Perfection, or Union with God"]
== Chapter 17. On Perfection, or the Union of the Soul with God

The most profitable and desirable state in this life is that of Christian perfection,
which consists in the union of the soul with God,
a union that includes all spiritual good,
produces in us a wonderful freedom of spirit which raises
us above all the events and changes of this life,
and frees us from the tyranny of human fear.
It gives an extraordinary power for the well-performing of all our actions,
and acquitting ourselves rightly in all our employments.
It furnishes with a prudence that is truly Christian in all undertakings,
a peace and perfect tranquillity in all conditions, and, in short,
a continual victory over self-love and fleshly passions.

It is impossible to attain divine union solely by the activity of meditation,
or by the warming of our affections,
or even by the highest degree of enlightened and elegantly composed prayer; for,
according to Scripture, "`no man shall see God and live.`"^
footnote:[Exodus 33:20]
Now all the exercises of spoken prayer, and even of active contemplation,
when performed _in the life of our own will_, cannot cause us to see God;
for all that is of man`'s own power or exertion--be
it ever so noble or exalted--must first die.

St. John relates, that "`there was silence in heaven:`"^
footnote:[Revelation 8:1]
Now this heaven represents the center of the soul, wherein,
before the majesty of God appears, all must be hushed to silence.
All the efforts, yes the very existence of self-love must be destroyed;
for it is the natural will that is opposed to God,
and all the evil of man proceeds from it.
Indeed,
the purity of soul increases in proportion as the
natural will becomes subjected to the Divine will.

Therefore,
the soul can never arrive at true Divine union except by the crucifixion of its will;
nor can it ever become one with God but by being
reestablished in the purity of its original creation.
God purifies the soul by His wisdom as refiners purify metals in the furnace.
Gold cannot be purified but by fire,
which gradually separates from it and consumes all that is earthly and contrary.
This must be melted and dissolved, and all impure mixtures taken away,
by casting it again and again into the furnace.
It then no longer contains any corrupting mixture; its purity is perfect,
its simplicity complete, and it is thereby fit for the most exquisite workmanship.
Thus we may see that the Divine Spirit, as an unremitting fire,
must devour and destroy all that is earthly, sensual, and carnal,
together with all self-activity,
before the soul can be fitted for and capable of true union with God.

God says, "`I will make man more precious than fine gold.`"^
footnote:[Isaiah 13:12]
But when He begins to burn, destroy, and purify,
then the soul (not perceiving the beneficial designs
of these operations) shrinks back from them.
And even as the gold, when first put into the furnace,
seems rather to blacken than to brighten,
so the soul often believes that its purity is lost,
and that its temptations are its sins.

But if we confess that the enjoyment of God is the end for which we were created;
that "`without holiness`"^
footnote:[Hebrews 12:14]
none can attain it; and that, to attain it,
we must necessarily pass through a severe and purifying process--how
strange is it that we should dread and avoid this very process!
Let all then press forward towards the mark,
allowing themselves to be guided and governed by the Spirit of grace,
which would infallibly conduct them to the end of their creation, the enjoyment of God.

"`Be perfect, even as your Father who is in heaven is perfect.`"^
footnote:[Matthew 5:48]
The soul remaining in its own disorderly will is imperfect.
It becomes more perfect in proportion as it approaches nearer to the will of God.
When the soul has come so far that it cannot in anything depart from the Divine will,
it then becomes wholly perfect, united with, and transformed by the Divine nature.
And being thus purified and united to God, it finds profound peace and sweet rest,
which brings it to such an experience of love, that it is filled with joy.
It conforms itself to the will of its God in every event that arrises,
and rejoices in everything to do God`'s pleasure.

The Lord draws near to such a soul, and communicates Himself inwardly to it.
He fills it with Himself because it is empty.
He clothes it with His light and with His love because it is naked.
He lifts it up because it is low, and unites it to Himself.

If you desire to enter into this heaven on earth,
forget every care and every anxious thought, depart from yourself,
that the love of God may live in your soul.
Thus you may be enabled to say with the Apostle, "`I live, yet not I,
but Christ lives in me.`"^
footnote:[Galatians 2:20]
How happy would we be if we could thus leave all for God, seek Him only,
breathe after none but Him, let Him alone have our sighs!
Oh, let us go on without interruption towards the enjoyment of this blessed state!
God call us thereto.
He invites us to enter into our inward center where He will renew and change us,
and show us a new and heavenly kingdom full of joy, peace, contentment, and serenity.

Here, the spiritual, retired,
and heavenly-minded soul finds a peace that is no more broken.
And though outwardly it may meet with many combats, and may sometimes feel naked,
forsaken, fought against, and desolate,
yet these tempests never reach that serenest heaven within,
where pure and perfect love resides.
For although the prince of darkness may indeed make violent assaults against it,
yet it continues steadfast and stands like a strong pillar,
with no more happening to it than what happens to a high mountain in a storm.
The valley below is darkened with thick clouds and
harassed with fierce tempests of hail and thunder,
while the lofty mountain above glitters in the bright beams of the sun.
In quietness and serenity it continues clear, immoveable, and full of light.
Such a soul is indeed "`as mount Zion, which cannot be removed, but abides forever.`"^
footnote:[Ps. 125:1]

In this throne of quietude are manifest all the perfections of spiritual beauty.
Here we shall enjoy the true light of the divine mysteries of Christ.
Here we shall find perfect humility, full resignation,
the meekness and innocency of the dove, liberty and purity of heart.
Here is witnessed joyful simplicity, heavenly impartiality, continual prayer,
shameless nakedness, perfect selflessness, and true citizenship in heaven.
This is the rich and hidden treasure; this is the pearl of great price.

[.the-end]
Finis.
