== Chapter 2

[.chapter-synopsis]
* Ellis Lewis
* John Gough
* Rachel Moxham
* John Haslam
* Sophia Hume
* Ann Crowley
* Thomas Roylance
* Ambrose Williams
* Hannah Ludgater
* Sarah March
* Sarah Harris
* Samuel Waring
* Rachel Wilson
* Mary Prideaux
* Joseph Oxley
* Deborah Waring

ELLIS LEWIS, an ancient Friend of Tyddin y Garreg, near Dolgelly, in Merionethshire,
North Wales,
was born of parents professing the truth as held by the people called Quakers;
and in his very tender years was favoured with a visitation of divine love,
which had such an effect on him that he appeared in a public testimony,
about the thirteenth year of his age, in the English language,
to which he was not accustomed, in a remarkable and tendering manner.
He continued faithful, and travelled in the work of the ministry divers times,
through the principality, and likewise in divers parts of England,
adorning the doctrine he preached by an innocent life and conversation,
and well esteemed by Friends in many parts where he came.

A few years before his death,
the infirmities of age rendered him incapable of travelling;
yet he retained a lively sense of truth, and love to his brethren;
having that ornament of a Christian mind, a meek and quiet spirit.
Being patiently resigned to the divine will, he laid down his head in peace,
the 23rd of the Eleventh month, 1764, and was buried in Friends`' burial-ground,
at Tyddin y Garreg, the 28th of the same, aged eighty-seven,
and a minister seventy-four years.`"

[.asterism]
'''

JOHN GOUGH, son of James Gough,
was a young man of a good natural disposition and capacity,
well furnished with useful learning; and as he grew up,
being favoured with deep religious impressions, he sought after and attained best wisdom,
to a degree in general exceeding his age.
On his entrance into active life, a propriety and steadiness of deportment,
that might adorn advanced years,
attracted the notice and respectful regard of the best Friends
who had the opportunity of observing or being acquainted with him.

He was a dutiful son, an affectionate brother, an exemplary pattern of plainness,
sobriety, and circumspection of life,
giving evident indications he was early acquainted
with the grace and truth which came by Jesus Christ.
He was, for a season, an assistant to his father in his school,
but meeting with an opportunity of engaging with a Friend of London as a clerk,
he removed thither;
in which station he conducted himself with fidelity and
honour during the short time he continued in it.

Being taken ill of a fever, which terminated his life, he said,
a little before his departure, "`I have done all that I had to do,
and must now go home.`"
He departed this life about the Tenth month, 1769, aged nearly twenty-one,
and was buried in Friends`' burial-ground, at the Park, Southwark,
after a very large and solemn meeting, in which the hearts of many were tendered.
His father, writing concerning him, says, "`Through divine favour and assistance,
I freely give him up; thankful for having such a son,
who hath left behind him too few like him in pure unmixed goodness,
which diligently exerted itself to do well.`"

[.asterism]
'''

RACHEL MOXHAM, daughter of John and Esther Moxham, of Melksham, in Wiltshire,
was of an innocent and mild disposition, but fond of company,
so that it appeared needful to her mother to be watchful over her on that account.
About the fifteenth year of her age,
religious impressions were observed to fix on her mind, so that she became sedate,
loved retirement, and was mercifully taught how to wait, and what to wait for.
One evening, after a silent opportunity of mental introversion,
she said to her mother nearly as follows:
"`I have thought it my duty to thank thee for thy care in
preventing and restraining me from unsuitable company,
which I took hardly.
I believe, had I had the liberty I coveted,
I should not have known the peace and comfort I now
feel in obedience to the principles of truth;
but should have gone in the broad way that leadeth to death.`"

She continued steadily serious, looking towards the recompense of reward;
and a few days before her decease, expressed a desire to attend the quarterly meeting.
She accordingly went; and a Friend had there to mention the uncertainty of time,
and the comfort of having, in a dying hour, hope towards God.
This she took to herself, and said, that evening, her work was nearly finished.
The quarterly meeting was on a Second-day;
and the Sixth-day morning following she complained of illness.
In about two hours after, her parents were so apprehensive of danger,
as to be affected with sorrow, which she observing, said, "`Do not grieve for me,
but rejoice evermore, and give thanks that I am going to everlasting rest;`" then said,
"`I hope,`" paused a little, and added, "`I am going to everlasting rest and peace.`"
She expressed to a friend the sense she had of her departure;
and hoped the Almighty would be near,
and sustain the spirits of her parents under the trial, as he did hers at that time.

She settled herself in the bed, and took leave of her friends,
under the influence of such a sweet and awful solemnity
as much affected the minds of those present,
no words being spoken, except her saying, "`Lord receive my spirit.`"
Thus she quietly departed, after about eight hours`' illness,
on the 20th of the Third month, 1772, aged nearly eighteen years,
and Friends were favoured with a remarkably solemn meeting at her interment, the 24th,
at Melksham aforesaid.

[.asterism]
'''

JOHN HASLAM, of Handsworth Woodhouse, in Yorkshire,
was of a sober and innocent disposition from his infancy.
His parents dying when he was young,
the care of his education devolved on Gilbert Heathcote, a physician.
Early giving up to a precious visitation from on high, he was prepared for service,
and called to the work of the ministry about the 25th year of his age.
He was soon drawn forth in the love of the gospel frequently
to visit the churches in various parts of this nation.
He visited Ireland twice, and Holland once,
and paid a general visit to Friends in most of the colonies in America.

He was exemplary in a deep inward exercise of spirit,
and in patient waiting for the arising of the divine life,
as a necessary qualification for service either in ministry or discipline,
"`Being,`" to use his own words addressed to ministers
in an epistle found among his papers,
"`a strength to a living, edifying ministry,
and a check to that which was forward or floating; either not duly anointed,
or not waiting truly for the resurrection of that
life which reaches the witness in others,
and opens into the treasury, where wisdom to divide the word aright is received.`"

He had a clear discerning of the opening of the heavenly gift,
and was careful to give way to the requirings thereof, and was well accepted therein,
yet he was often proved with deep inward poverty;
and in imparting something of his experience in that respect to a friend,
who remarked it was a safe state, he replied, he knew it to be so,
but that it was possible sometimes to be depressed too low for the gift.
He was remarkably endued with patience and resignation in the loss of his wife, and,
in some years after, of an only daughter, whom he survived about six years;
and though her tender care over him was well supplied, yet, being far advanced in years,
his bodily strength and memory gradually declined.

He became incapable of attending meetings for about three years before his decease;
yet he expressed great satisfaction with the visits of his friends,
and appeared to be in a patient, resigned, and innocent frame of mind.
As his natural strength was thus worn out by almost imperceptible degrees,
he was divested of this state of mutability, without much appearance of pain,
the 4th of the Tenth month, 1773, and interred on the 6th of the same,
in Friends`' burial-ground at Handsworth Woodhouse, aged eighty-three years,
and a minister about fifty-seven years.

[.asterism]
'''

SOPHIA HUME was born in South Carolina, and was descended, on her mother`'s side,
from the stock of friends.
Her grandfather was William Bayley, formerly a Baptist preacher at Poole,
but was early convinced of truth, and became a living, powerful minister;
for an account of whom see Vol. I. p. 72.
Her grandmother was Mary Fisher,
who was one of the first friends that visited New England in the year 1656, and who also,
before her marriage with William Bayley, viz., about the year 1660,
under a great concern of mind, went to Adrianople, to visit the Great Turk:
the particulars of which are related in Sewel`'s History.

Her mother continued in profession with friends, but marrying out of the Society, this,
her daughter, was educated agreeably to her father`'s mind;
and for a considerable time took great delight in
the pleasures and delusive amusements of this world.
About the thirty-eighth year of her age her judgment was
opened to see the vanity and folly of these practices;
and she, in measure, forsook them,
but was not fully convinced of the principle of truth
in her own mind until about the year 1741,
when, having Barclay`'s Apology by her, she looked into it, as she often expressed,
to furnish herself with matter for conversation;
but in the perusal of it her judgment was convinced of the truth of friends`' principles:
she joined the Society, and became a steady, exemplary member.

She came afterwards from South Carolina to reside in London, and about the year 1747,
a concern came upon her to visit the inhabitants of her native country,
from whence she sent the following account in a letter to a friend.

"`A concern I had often felt in my soul for the happiness
and eternal welfare of my native country revived in my breast;
when I was to return and abase myself, by telling what God had done for my soul,
and to call them from those things,
in which I had often run to an excess of riot with them; and from which I had been,
by the great love and powerful hand of God, brought and redeemed.
When I arrived in Carolina, I found it my place and duty to keep meetings,
with those few that professed with me; and though, at first,
the meetings were sometimes interrupted by the rude and uncivil treatment of many,
we met pretty quietly,
and some of the inhabitants would now and then come and sit with us,
to whom my mouth was opened at times in rehearsing what God had done for my soul.`"

During her continuance there,
she wrote a short account of the dealing of the Lord with her,
which was soon after published.
From thence she went by land to Philadelphia,
a journey of between eight and nine hundred miles; and after her return from America,
under a tender concern, she laboured, both by word and writing,
to bring people to believe and live under that divine principle, the spirit of truth,
which she had found, by happy experience, to be as a fountain of life.

In her private station she adorned the gospel by a life of humility and self-denial,
and was zealous against all superfluity, both in dress and furniture.
Thus preserved through a course of many years,
towards the close of her time she appeared in remarkable tenderness, and,
as if she were sensible that her dissolution was approaching, she gave directions,
in divers respects, relating to her burial, with much composure.
On the 26th of First month, 1774, she was suddenly taken ill, and,
being seized with an apoplexy, in about twelve hours departed this life.
After a very large and solemn meeting at Gracechurch-street meetinghouse, London,
her remains were interred in Friends`' burial-ground near Bunhill Fields.
She was nearly seventy-three years of age, and about twenty-five years a minister.

[.asterism]
'''

ANN CROWLEY, daughter of Thomas Crowley, of Gracechurch-street, London,
being seized with illness, which continued for several months,
was preserved in much patience,
and uttered many expressions which showed the fervency of her mind.
At one time she expressed herself thus: "`The pains of death are hard to bear,
but I am sensible they are not on me now, but they are near approaching;
death is no terror to me.
O death, where is thy sting?
O grave, where is thy victory?
My dear tender mother, it will be a bitter cup; but it is the Lord`'s preparing,
and therefore drink it willingly.`"

Being removed into the country for the benefit of the air,
she expressed herself to the following effect: "`This is hard work;
it is indeed hard to bear, but the Lord is with me in these trying moments.
I did not think my dissolution was so near, but I am ready, Take me, Father,
take me to thyself this evening, if it be thy will,
for I long to be with thee in paradise.
Though I have endured so many moments of agonizing pain,
the Lord has been my support through the whole, and, I doubt not,
will continue to be with me to the end.
Oh, Father!
Father!
Father! bow the heavens, and come down;
be thou with thy people universally all the world over.

Why do ye weep?
Weep not for me, but give me up to the Lord, for I am happy;
far happier than I can express.
I wish every one of you could feel what I feel at this time, for it is beyond expression.
Oh, it is like a heaven upon earth;
it hath not entered into the heart of man to conceive what
good things God hath in store for them that love him.`"
To one of her sisters she said, "`Oh! my sister, give up, give up now,
in the days of thy youth; for the Lord loves an early sacrifice.
Oh, prepare thyself! lest it should please the Lord to
cut thee down in the flower of thy youth.`"

About two weeks before her departure,
she earnestly prayed that it might please the Almighty to take her that night,
and expressed herself as follows:
"`Thou hast been pleased to give me a taste of thy goodness, and a sight of thy glory,
and it is glorious indeed; but, oh, Father!
I long to be with thee, that I may enjoy it in a more plentiful manner.
The gates of heaven are open to receive me.`"
She said, "`I have never murmured at what it is the Lord`'s will I should suffer;
but I was content if the pain had been much greater,
if it was the will of my heavenly Father.
Oh, Lord!
I long to be with thee,
where my soul shall join the angels and archangels that are in heaven.`"
She further added, "`It is my desire that you, my tender brothers and sisters,
may come to the same experience.
I was nearly visited, long before I was laid on this bed of sickness; if I had not been,
it would be miserable indeed:`" and a little after,`"
My spirit was warmed in the renewing of thy love.`"

About six days before her close,
she sent for her three brothers separately to her bedside; and,
in a most affectionate and tender manner, cautioned them against the gaiety, riches,
and grandeur of the world; and exhorted them to walk in the path of virtue,
to keep close to divine instructions, and likewise to watch and pray continually: adding,
"`I feel it needful, even on my deathbed.`"
To one of them she said, "`Give up, O give up;
remember the fear of the Lord is the beginning of wisdom.
Seek thou that wisdom now in the days of thy youth.
Step gently along, and keep thy mind low and humble before him.`"
After lying still a little time, she said, "`Though painful my nights,
and wearisome my days, as Samuel Fothergill said,
yet I am preserved in resignation and patience.`"

Some friends visiting her, she expressed to them, "`My pains of body are great,
but my dependence is on the Lord, and my only comfort is in him.
I thought from the beginning that I should not get over it;
but within these three weeks I have seen clearly I shall not.`"
She further observed, that she had been visited long before her illness,
and had found great uneasiness in wearing things that were gay,
and also in speaking in the plural language to one person; and added,
that she found it difficult to take up the cross, but when she did,
her satisfaction was great.
"`Oh! what I feel for those whose minds are involved in the world,`" with much more;
all importing the happy state of her mind; saying to one friend, "`I am ready,
I have nothing to do but die.`"

She particularly requested of her father, that after her decease,
her body might be buried from Devonshire-house meeting; and desired,
that the young folks of that quarter, in particular, might be invited to attend;
hoping it might prove a profitable time to them.
The evening preceding her departure,
she spoke to one of her sisters to the following effect--"`Gaiety proceeds from pride,
and pride is the root of all evil:`" and she fervently exhorted against it.
In the night her pains were exceedingly great, and she felt the approach of death;
and in the last two hours continued uttering ejaculations.
Calling for her mother, on her coming to her she said, "`Farewell:`" and expired,
the 12th of Second month, 1774, being not quite seventeen years of age.

[.asterism]
'''

THOMAS ROYLANCE, of Newton, near Middlewich, in Cheshire;
was born of parents professing truth; who,
having been weightily concerned for its promotion, and sufferers for its testimony,
had a great care of his education; which had a good effect on his mind,
as appears by his own account in manuscript, viz.,

"`I was through divine favour, early inclined to the love of truth,
and to seek after it to the best of my understanding, often seeking places to pray,
and pour out my soul to the Lord,
in beseeching him for wisdom and strength to enable
me to persevere in well-pleasing to him.

And blessed, magnified, and eternally praised be his holy and most worthy name;
he hath many times, in his own time, answered,
and caused my cup to overflow in praises to his name, and admiration of his goodness.
My soul, being as a well watered garden, hath rejoiced in his love; and,
in abasedness of self, hath largely ascribed praises and glory to him, who,
with the Son of his love, through the Holy Spirit, is eternally worthy.
Amen.

I early loved good men, and had a desire to go to meetings;
so that while I was but very young, if any thing offered to let or hinder my going,
I can remember I have wept to go, though four miles distant from us.
I can also remember, that in my very young years, I loved to be speaking of good things;
and often found it my place to reprove boys that were my companions,
and sometimes others, for unsavoury words, or any thing unseemly.
The Lord always sufficiently helped me,
though it was with persons of greater age and capacity, as to the outward, than myself,
when I found my mind engaged to converse with them on religious subjects;
and as I grew up, I had great love to truth, and honest, sincere friends;
in whose company and good conversation I much delighted.`"

He was much given up to the service of truth;
and much concerned that the discipline of the church
might be managed in a weighty and proper manner.
He was an example of plainness,
and zealously concerned to warn those who took undue liberties,
and was helpful in opening the understandings of many.
About the sixtieth year of his age, he came forth in a few words in the ministry,
which was acceptable and edifying.

He left a few remarks on that subject, worthy to be preserved.
"`Although,`" says he, "`there have sometimes been words in my heart, and, as it were,
in my mouth, which I do not know but they might have been of ease to myself,
and of service to others, had I delivered them;
and I have been spoken to by some Friends, both in a private and public capacity,
or station, thereon; but was always forbearing and backward that way,
and have been afraid of too much forwardness in some, who,
I have been and still am afraid, have not edified thereby.
+++[+++I had]
always a fear of, and a dislike to, the noise of the tool,
the working of self and the creature, in our meetings,
as it was not to be heard in the building of the Lord`'s house or temple of old.
But that ministry which comes with a true flow from the divine spring,
having its evidence and authority with it, I still loved, and greatly do love,
and the vessel it flows through, for its sake, whether it be in rebukes or consolation,
as the Almighty is pleased to give, and the case may require.
Whether it may be more or less, it is beautiful; and if rightly received,
it is comfortable and edifying.`"

He died the 25th of the Second month, 1774, in the seventy-third year of his age,
at his house at Newton, after about two weeks`' illness, which he bore with patience;
expressing, near his conclusion, that all was well.

[.asterism]
'''

AMBROSE WILLIAMS, of Pont-y-pool, in Monmouthshire,
was educated in the national way of worship; but, being dissatisfied therewith,
and humbly desiring to be rightly directed, he came to a meeting of Friends, in which,
though held in silence, his heart was replenished with divine love; and,
through the teachings of this divine principle,
he came to experience that the work of righteousness is peace;
and in a few years had his mouth opened to testify to the sufficiency thereof.

He was a constant attender of meetings for worship and discipline;
and a diligent labourer therein on his own account and that of others,
that none might live as in ceiled houses, and let the house of the Lord lie waste.
By his exemplary life and conduct, and great love to his friends and neighbours,
it may be justly said, that he was "`An Israelite indeed, in whom there was no guile.`"

The First-day before his departure, he attended the morning meeting at Pont-y-moil,
though weak in body; and, in a solid, weighty frame of mind,
earnestly recommended all to do their day`'s work in the day time; signifying,
that perhaps he might be the first called from works to rewards;
that he had nothing lay in his way, but had done his day`'s work,
having set his house in order.
He departed this life the 16th of the Third month, 1774; aged sixty-two,
and a minister about thirty-three years;
and his body was decently interred the 20th of the same at Pont-y-moil.

[.asterism]
'''

HANNAH LUDGATER, of Coggeshall, in Essex, wife of Robert Ludgater, of the same place,
was born in Hampshire, and had her education among Friends;
but in her early days she left the Society, and frequented other places of worship.
In this unsettled state, it pleased the Father of mercies to enlighten her understanding;
so that through the powerful operation of his love,
she saw wherein she had missed her way, became again united to Friends,
and in due time her mouth was opened to tell others what she had felt,
and to invite them to come, taste, and see how good the Lord is.
In this service she was engaged to travel both before
and after her marriage with Robert Ludgater.

She resided for some time in the Isle of Wight, and afterwards,
on her first coming to London,
lived as housekeeper with a person not in religious profession with Friends;
where her innocent and virtuous deportment gained her much esteem,
and the Society for her sake.
She was an affectionate wife,
and much concerned to promote the discipline of the Society among her own sex,
and was a true helpmeet to her brethren; of a weighty and discerning spirit,
accompanied with diligence in labouring for the advancement of truth;
though often pressing through great discouragements arising from bodily infirmities;
which frequently rendered her incapable of attending meetings.

She suffered great pain of body for the last six months of her time,
under which probation her patience and resignation manifested
the happy effects of faithful labour in the day of ability.
Being steadfast in her dependence on the author of her faith,
she had at times access to the fountain of life; under the sensible enjoyment whereof,
she said, "`O how I long to be relieved;
I have no doubt but I shall be mercifully relieved.`"
To a friend who visited her, she said,
"`I have been in a good degree faithful in our meetings,
and have not to charge myself with omitting one journey,
when it was made known to be my duty.
O how have we gone forth, poor and empty;
yet have not lacked! the Supporter hath been near, and richly furnished.`"
She departed this life the 28th of the Third month, and was buried at Coggeshall,
the 3rd of the Fourth month, 1774, aged about sixty-five years.

[.asterism]
'''

SARAH MARCH, of Durham, was born in London; and taking heed to the divine light,
which shone in her heart, she had to bear testimony thereto, about the year 1753;
in which service she laboured faithfully to promote the same principle in others;
and gave evident proofs of the efficacy thereof by an exemplary deportment.
A little before her death she wrote the following paper,
which she desired might be read in the several meetings in the county,
which was done accordingly.

Dear friends,

Under great weakness of body,
my concern remains strong for your growth and prosperity in the blessed truth.
In that love which I feel shed abroad in my heart doth my spirit salute you;
beseeching you to meet as in the presence of God;
in reverence and humility wait upon him, who is indeed the dread of nations;
and I trust our God will graciously condescend to
overshadow your assemblies with his power,
which brings salvation; and to crown them with his blessing, which makes truly rich,
and adds no sorrow with it.

Let me entreat that no restlessness or impatience may prevail,
although the Lord of life and glory should tarry;
for he will most certainly arise in his own appointed time, with healing in his wings,
for the sake of his own wrestling seed, that are waiting for Israel`'s consolation.
If this be your situation before the Lord in-secret, he will reward openly,
and you will be enabled to praise God acceptably,
and to magnify his great and worthy name; as doth my soul at this season,
because I feel the same divine goodness that was my morning light is now my evening song,
which makes me rejoice in the Lord; and my joy no man can take from me.

She departed this life the 29th of the Fifth month,
and was buried on the 2nd of Sixth month, 1774,
in Friends`' burial-ground in the city of Durham; in the forty-fifth year of her age,
and a minister about twenty years.

[.asterism]
'''

SARAH HARRIS, of Chipping Norton, in Oxfordshire, widow of Nicholas Harris,
of the same place, was born about the year 1704;
but no account is come to hand of her early youth,
except that while she was a servant to a Friend at Banbury, in the same county,
she was a sober, religious young woman.
Through obedience to the principles of truth, she became useful in her day;
and was of a gentle, affable, kind, and charitable disposition;
a true lover of the religious of all denominations; and one who liberally administered,
in proportion to her circumstances, to the poor and afflicted.

About the forty-sixth year of her age,
she was concerned to bear testimony to that hand which had supported and preserved
her in the various dispensations she had to pass through in life.
She discovered a deep humility and sensibility of her own weakness and unfitness,
as she thought, to be employed in the important work of the gospel ministry;
as she knew and felt it to be an awful undertaking,
and not to be performed in the policy, strength, and wisdom of man;
but in the power and wisdom of God.
Her calm and contented waiting and resignation, before she appeared in meetings,
indicated her keeping invariably in remembrance the injunction of her Lord to his disciples,
viz., "`Tarry ye in the city of Jerusalem until ye be endued with power from on high.`"
This laudable diffidence, Christian circumspection, and resignation of soul,
rendered her services very acceptable to such as could taste and
feel that the source of her ministry was the spring of life.

In her last illness, it was apparent to divers who visited her,
that she had made provision for a blessed eternity;
and that a lively feeling of divine refreshment was
her support under bodily infirmities and decay.
The visit of death was not unexpected, nor was she unprepared to sustain it.
A sense of dependence and of gratitude, the foundation of true piety,
continued with her to the last; and many comfortable expressions were uttered by her,
in the course of her illness.
She often advised against too anxious a care about the business and things of this world;
and often desired she might be favoured with patience to bear her affliction.

One day, after lying still some time, she said, "`They that wait upon the Lord,
shall renew their strength.`"
At another time, to those of her family and friends present, she said,
"`I have desired for you now, as well as at many other times,
that the blessing of heaven might attend;
but there must be a living up to what you know.`"
At another time she said,
"`Let it be the business of your lives to be prepared for such a time as this.`"
Speaking to a person who made inquiry after her welfare, she said,
"`The Lord is my shepherd, I shall not want.`"

It being meeting-day, she said, "`Go to meeting all that can;
and O that my spirit may be refreshed with yours!`"
She also advised not to let business hinder from going to week-day meetings.
She signified that when she gave up to speak a few words in meetings,
it was in great simplicity and fear; and that she witnessed peace in it,
being very careful to wait for divine qualification; and she humbly trusted,
and could say in humility and thankfulness, she never was confounded.
She departed this life in great calmness and peace the 22nd of the Sixth month, 1774,
and was buried the 30th of the same in Friends`' burial-ground at Chipping Norton;
aged seventy-one, and a minister twenty-five years.

[.asterism]
'''

SAMUEL WARING, of Alton, in Hampshire, was the son of Jeremiah Waring of Witney,
in Oxfordshire: for an account of whom, see Vol.
I., page 39. Being favoured with the benefit of a religious education,
and yielding to the sanctifying operation of truth,
the Lord was pleased to prepare and qualify him for his service.
He came forth in a public testimony about the 25th year of his age;
and being faithful in the exercise of his gift, he grew therein,
and became an able minister of the gospel.
He was exemplary in his attendance on meetings for worship and discipline;
a diligent attender of the yearly meeting in London upwards of fifty years;
and though not forward in speaking, yet his retired and awful sitting therein,
furnished an edifying example to the attentive observers.

At different periods of his life, he visited friends in South Wales,
the west of England to the Land`'s End, all the southern,
and divers of the midland and eastern counties in this nation;
and some of them several times.
In these visits we have cause to believe his service was acceptable;
for being humbled into a deep sense of his own weakness and insufficiency,
as well as the weight and importance of such services, he was not hasty in moving,
but waited for a clear evidence, both as to the concern itself,
and also the proper time for engaging therein.

Having the weight of a large family, and a considerable share of business upon him,
he was steadily concerned that he might not be overcharged therewith,
to the hinderance of his services;
and with that view purposely shunned some flattering prospects of gain,
desiring nothing more than to provide things honest in the sight of all men,
that the ministry of which he had received a part, might not be blamed.
Thus having, through the blessing of Providence, made a comfortable, though moderate,
provision for a numerous family, he quitted business when in a flourishing state,
more than twenty years before his death;
spending much of the latter part of his time in reading and retirement.

He was much given to hospitality,
his heart and house being always open to receive the friends of truth,
in whose company he took great delight.
After having laboured in word and doctrine for a long series of time, he was,
some years before his decease, gathered into humble silence,
seldom appearing in public testimony in meetings; but the patient,
resigned frame of his mind under this dispensation,
and his close inward travail in spirit, made it evident beyond all doubt,
that he retained his integrity, love, and zeal, to the end.
Conversing with some friends a few weeks before his departure,
he with great sweetness intimated, that his peace was sure.

During his last illness, which he bore with remarkable patience and composure,
he said repeatedly, that he had no desire either for life or death,
but felt his mind resigned to the Lord`'s will.
After meditating some time in silence, one evening he said,
"`I have been thinking of faithful Abraham, humble Isaac, and wrestling Jacob.
Abraham was called the friend of God, because he was found faithful.`"
Among other weighty and affecting expressions, he mentioned more than once,
that he believed a time of great calamity was coming over the nations,
and that afterwards there would be a gathering of the people to the principle of truth,
when they would flee to it, as doves to their windows.

The day before he died he took a solemn leave of divers friends who visited him,
and the monthly meeting being next day, desired his love might be remembered to friends,
saying that he expected he should sit with them no more.
Two of his daughters sitting up with him the last night, and asking how he did,
he replied, "`I have fully as much pain as I can well bear;
but I have thought the Lord can cut the work short in righteousness;
and I hope to bear the portion allotted me with patience.`"
Soon after he added, "`It is all mercy I receive, through Jesus Christ our Lord.
I hope I may say I have endeavoured to do nothing against the truth,
and what little I have been enabled to do for the truth,
I have done in a degree of sincerity and uprightness.`"

He was preserved perfectly sensible to the last, and quietly departed this life,
full of days and full of peace, on the 13th of the Second month, 1775,
at Alton aforesaid, aged nearly eighty-four, and a minister about fifty-nine years.
His corpse was interred in Friends`' burial-ground there, the 19th of the same.

[.asterism]
'''

RACHEL WILSON, late wife of Isaac Wilson, of Kendal, in Westmoreland,
was the daughter of John and Deborah Wilson of the same place,
who gave her a religious education.
Influenced by their example,
and being favoured with the company and conversation of
many valuable friends travelling in the work of the ministry,
her mind was happily seasoned, and much profited;
and being also early favoured with a visitation of divine love,
she was enamoured therewith,
and weaned from the fallacious pleasures and amusements
which captivate too many of our youth.

Thus prizing the privileges she enjoyed, and the dawnings of divine wisdom in her soul,
she was much led into solitude and secret retirement before the Lord,
only choosing such company and conversation as might be profitable to her;
and carefully dwelling under the forming hand,
she witnessed a growth in virtue and piety,
and became fitted for the work of the ministry,
into which she was called about the eighteenth year of her age.

Being faithfully devoted to the service of her Lord and Master,
she experienced a growth and increase in heavenly wisdom; and,
by the constraining power of divine love, was drawn forth to visit the churches,
not only in divers parts of this nation, but also in Ireland, Scotland, and America.
She also laboured much among those not in profession with us,
who flocked to hear her testimony in the course of her travels;
and was eminently qualified for that service,
explaining the way of life and salvation in a manner
that reached the witness in the hearts of the hearers,
whereby many were brought to an acknowledgment of the truth.

She was remarkably diligent and exemplary in the attendance of our religious meetings,
both for worship and discipline; and, when called forth to service,
though she had many children and a large family under her care,
she did not suffer these to prevent her from pursuing what appeared her manifest duty;
but what she found in her hand to do, that she did with her might.
She was a loving wife, an affectionate parent, a kind and helpful neighbour,
tenderly sympathizing with the afflicted, and frequent in visiting the sick,
in which visits she was very serviceable, often administering comfort to the drooping,
distressed mind.
In which service she found the reward of peace.

In the course of her religious duty she came to London, about the First month, 1775;
and on delivering her certificate to the morning meeting, she expressed,
in much tenderness, a desire,
that after her being engaged in the service of truth from her youth,
she might be preserved from those rocks and shoals which some had split upon,
and that her sun might go down in brightness.
She entered into her service with great humility,
visited most of the meetings in the city,
and finding her mind concerned for the inhabitants of Gravesend,
having had two meetings with them when she embarked for America,
she went again to visit them.
She was gladly received, and held two meetings in the town-hall, where,
through divine favour, she was helped through her service to her own peace,
and the comfort of many present.

After her return she attended several week-day meetings, in the last of which,
at Devonshire House, she was clothed with divine love,
in an encouraging testimony to the honest-hearted.
The next day, being the 4th of the Second month, she was taken ill,
and was confined wholly to her chamber, and mostly to her bed, for six weeks;
during which time she was favoured with quietness of mind,
expressed her resignation either to live or die, and requested her husband,
who attended upon her a great part of the time, that he would tell their children,
it was her great desire they might, above every consideration,
mind the one thing needful, which having been her care,
was her unspeakable consolation in that time of close conflict.

She also in the course of her illness expressed to a friend that she was quite easy,
and to some others remarked the necessity of doing what appeared to be our duty,
while opportunity was afforded.
She said her Master was kind to her, and at times favoured with his presence,
which bore up in days of trial, and nights that were wearisome.
She was often retired in mind, and remarked to some who attended her,
that though no one loved her friends`' company more than herself,
yet she had now no desire to see them, but was quite resigned,
though so far separated from her near connections.

She was a pattern of patience, and always appeared satisfied with those about her,
who rendered her any little services.
The last words she was heard to say were,
"`Good tidings,`" which no doubt the summons of death proved to her,
as it appeared to have no sting, nor the grave any victory.
She quietly departed this life on the 18th of the Third month, 1775,
at the house of Richard Chester, at London;
and her remains were interred on the 23rd of the same, in Bunhill Fields,
after a meeting held at Devonshire House.
She was about fifty-four years of age, and thirty-six years a minister.

[.asterism]
'''

MARY PRIDEAUX, wife of William Prideaux, of the county of Cornwall,
was a pattern of meekness and piety;
and as she grew in years she grew in grace and in the knowledge of our Lord Jesus Christ.
She had a part of the ministry committed to her,
in which she was a faithful steward and a bright example to others,
not being forward to appear in ministry,
as well knowing that true silence never shames the gospel.
But when under the constraining power of truth,
her ministry was with the demonstration of the spirit, and with power,
greatly to the refreshment and strength of the honest-hearted;
and when she felt the drawings of truth,
she was ready to leave her near connections in life.

She visited some parts of the west when her name was Mary Davies, and after her marriage,
several times.
Not long before the close of her life,
she found a concern to visit some of the midland counties,
which service seemed near to accomplish her day`'s work,
having soon after her return publicly to declare, happy would it be for all,
in the conclusion of their time, to have to say with the apostle,
"`I have fought the good fight, I have finished my course, I have kept the faith;
henceforth is laid up for me the crown of righteousness,
which the Lord the righteous judge shall give me at that day; and not to me only,
but to all those that love his appearing.`"

A short time after she was taken ill with a fever, which continued about four weeks;
during which she behaved with patience, meekness, and yet with Christian fortitude;
and many heavenly expressions dropped from her, at a meeting in her own house.
She had to commemorate the goodness of the Lord to all those who put their trust in him,
and humbly petitioned that he would be with them to the end;
that they who lived in his fear, might die in his favour;
requesting his protection in every trying season,
with fervent desire that all who were present might know a thorough resignation of will;
for the Lord our God requires obedience from all his servants.
The same evening she signified that she thought her time was near a conclusion.
Some days after she said,
"`Humility is a qualification I desire my children
may be endued with;`" and signified to them her hope,
that her advice in times past might be remembered, saying,
"`I hope it may be as bread cast on the waters, that may return after many days.
I have endeavoured to do my duty by you.`"

Her disorder increasing, she desired she might endeavour to bear it;
and that those in health would improve their time whilst health and strength were afforded,
saying, "`I can do but little now;
it would indeed be bad if I had my peace to make with the Lord.
I have dedicated my health and strength to his service, according to my ability.`"
Finding herself growing weaker,
she desired that her family might be resigned to the will of Providence,
adding that she enjoyed great peace and tranquillity of mind, for which she was thankful;
and further added, "`Oh, this is a favour indeed, to enjoy such tranquillity!
All seems serene, and the streams of life flow freely; the river seems clear as crystal.
Oh, that none may put off repentance till confined to a sick bed!`"

On seeing one of her daughters, she said, "`Oh! be good, be good, and fear the Lord,
my dear child;`" and again said, "`Then shall ye know, if you follow on to know the Lord,
his going forth to be as the morning: he shall come unto us as the rain,
as the latter and former rains upon the earth.
Oh! the cunning foxes have holes and lodging-places,
but the dear Son of God hath not where to lay his head.
Lamentable, indeed, where this is the case!`"

The same evening, finding herself in much pain, she expressed,
that she felt the mercy of the Lord, who had forgiven all her offences;
her omissions and commissions would be remembered no more;
and said she found a pardon for all.
Being in great agony, she desired that patience might have its perfect work,
and often prayed that the Lord would cut the work short in righteousness,
but desired that not her will, but His should be done.
At another time she expressed herself thus:
"`O that I were relieved from this world of peril and difficulty!

I have nothing to encounter with but death, and this is no terror to me.
O that I were safely arrived in the kingdom of heaven,
where I shall be comfortably spoken to by my God!`"
When the agonies of death were upon her, she said, "`Is this the last fit?
O that it was!
Lord, dear Lord, come quickly.
O death, where is thy sting?
O grave, where is thy victory?`"
adding, "`What love I feel, what love I feel; my love is to all universally in the Lord.`"
She quietly departed this life the 16th of the Sixth month, 1775; aged about fifty-six,
and a minister thirty-four years.

[.asterism]
'''

JOSEPH OXLEY, of Norwich, was born at Brigg, in Lincolnshire;
and being left an orphan when about eight years of age,
he came under the guardianship of his uncle, Edmund Peckover,
who educated him in the principles of Friends.
But, according to an account left by himself in manuscript,
for the information and caution of his offspring,
he was led away by the influence of irreligious associates
into an indifference towards religion,
a neglect of the due attendance of meetings,
and divers unprofitable and disorderly practices.
"`But,`" says he, "`at that time I was under such inward convictions,
that my heart was often filled with grief and horror;
however joyous I might appear outwardly, I was inwardly smitten and condemned.`"

Yet not sufficiently seeking to take up the cross,
but rather to gratify his youthful inclinations,
the power of evil so far prevailed over him,
that he became the means of trouble and sorrow to his relations and friends.
In process of time it pleased the Lord to meet with him as in a narrow place;
for in the year 1739,
he unexpectedly fell into a most distressing and alarming situation,
wherein his life appeared in immediate danger from
the surrounding pressure of a great crowd,
he being low of stature.
Confusion and terror instantly seized him, and made him cry aloud for help; upon which,
some near him afforded such speedy assistance as, through divine mercy,
extricated him from the great danger he was in.

After his deliverance,
he became deeply humbled in thankfulness that he
was not taken away in that unprepared hour;
and being also sensibly favoured with a renewed visitation from on high,
his heart was made to rejoice in admiration of the gracious
abounding of divine love which he felt in his soul.
From this time he closely attended meetings, associated with experienced Friends,
and embraced their advice; humbly submitting to bear the cross,
and to follow the leadings of truth in its progressive manifestations.
Abiding under a daily concern that, as he had believed in the truth, he might walk in it,
he in time experienced a good degree of redemption, and resignation to the divine will.

About the year 1742 he found his mind baptized for the work of the ministry,
which weighty service, he, after some time of deep trial, in great fear and reverence,
gave up to, and appeared in public as a minister, to the satisfaction of Friends.
He travelled in the service of the gospel, at divers times,
through many parts of this nation, Scotland, and Ireland;
and in 1770 he passed over the great deep,
and paid a religious visit to friends on the continent of America.
He returned from there in 1772, with the reward of peace in his own bosom,
and the approbation of friends,
as amply expressed in their certificates from various provinces.

He was a man exemplary in conduct, and agreeable in conversation, honest in advice,
charitable in sentiment, universal in benevolence, deservedly esteemed by his neighbours,
and beloved by his friends.
A few months before his decease,
he was impressed with a sense that his departure was at no great distance;
and sometimes hinted to some nearly connected with him that it would be suddenly; yet,
not as fearing it, but rather in a serious and pleasing acquiescence with the prospect.

Accordingly, after attending two meetings on First day, the 22nd of the Tenth month,
1775, which were held in silence; and spending the evening with his family,
in a disposition more than ordinarily pleasant; he went cheerfully up to bed:
where he laid but a few minutes,
before it pleased Almighty goodness to take him from
the vicissitudes of mutability without a struggle,
or passing through the tedious and afflicting pains commonly incident to nature:
no doubt to him an easy passage to a heavenly mansion.
His remains were interred in Friends`' burial-ground, at Norwich,
the 26th of the Tenth month, 1775, in the sixty-first year of his age,
and thirty-fourth of his ministry.

[.asterism]
'''

DEBORAH WARING, widow of Samuel Waring, before mentioned, was a native of Alton,
in Hampshire; and being religiously educated in the principles of truth,
and favoured with an early visitation of its sanctifying influence, was,
by yielding obedience thereto, qualified for public service.
About the 18th year of her age,
it pleased the great Lord of the harvest to call her into the work of the ministry;
in which service she was an unwearied labourer;
and under the renewing of heavenly virtue,
her doctrine frequently dropped like dew to the consolation of the right-minded,
and edification of the body in love.
She was often led, in an awful manner,
to press the necessity of a reverent waiting for
the fresh opening of the spring of all good;
that every individual might be brought from all exterior dependence,
to know the Lord for themselves; and witness the revelation of his dear son,
the minister of the sanctuary, in their own hearts:
and she recommended this doctrine to others by her own example.

She was a very diligent attender of meetings, both for worship and discipline;
and not only at home and in her own county,
but under the prevailing influence of divine love,
her mind was engaged at sundry times to visit friends in divers other counties,
having the unity of her monthly meeting in that weighty service; and,
by some remarks of her own, it appears, that the Lord`'s blessed presence was with her,
and strengthened her from day to day.
She was of a tender, sympathizing disposition,
and was enabled to fill up the several relative duties in life with great propriety,
and to continue fresh and lively in old age.

It having pleased the Lord to remove her husband (with whom she had long
lived in much unity and affection) about a year before her,
she was divinely supported under that great trial, beyond her expectation,
as she expressed in sundry living testimonies,
which she delivered in the family at that solemn season.
But her health soon after began to decline,
and her faculties suffered an abatement of their usual strength; yet,
during six months`' gradual decay, she was preserved in much innocence; frequently,
aspiring after that which, from her youth up,
she had preferred to all created excellence, and desiring to be preserved to the end,
in a sense of that power which had been her morning light,
and her guide through the vicissitudes of life.

Being one day observed to be unusually anxious,
and one of her daughters asking her how she did, she replied, "`My poor mind is tossed,
and I long to be fixed, fixed, fixed.
There is one who can walk upon the sea, and command a calm.`"
She afterward wished to be lifted up, to be new-clothed, and go home; and prayed,
"`Gracious and merciful Father, look down upon me, if it is thy blessed will.`"
She departed this life without sigh or groan, at Alton, the 3rd of the Second month,
1776, and was interred in Friends`' burial-ground there, the 11th of the same;
aged seventy-eight, and a minister about sixty years.
