== Chapter 2

[.chapter-synopsis]
* Tabitha Marriot
* Ann Naish
* Margaret Greenwood
* Jane Fryer
* Lydia Hawksworth
* Sarah Grubb
* Jeremiah Waring
* Fidelity Hull

TABITHA MARRIOT was the daughter of Richard and Susannah Ecroyd,
of Marsden in Lancashire, and was born in the year 1724.
She was enabled early to bend to the visitations of the grace of the Lord,
and by this means had discernment and strength to avoid
the vanities and dangers to which many appear prone.
As she advanced in the path of righteousness,
many deep baptisms and conflicts of spirit fell to her lot,
which she endured with patience,
until she was reduced to a resignation of will that resembled
the clay passive in the hand of the potter.

Thus she was prepared as a vessel meet for the Lord`'s service, in which,
as a gospel minister, she first publicly engaged in the twenty-sixth year of her age.
"`The Lord,`" said she, in a week-day meeting, "`is good to his people;
especially to those who are desirous above all things to be conformable to his will.`"
The declarations of our ministers are called testimonies.
This appears to be truly a testimony.
She bore witness of what she felt.
She was soon concerned to visit Friends in their meetings.
Her first visit in this religious service was in Cumberland,
in company with her beloved elder friend, both as a woman and a minister,
Sarah Taylor of Manchester, of whom there is an account in the ninth part of this work.
She continued frequently to be engaged in this service for about eight years, when,
in the year 1758, she was married to Richard Marriot, of Mansfield in Nottinghamshire,
and went to reside there.

In about two years, however,
they came and settled in the compass of Marsden monthly meeting.
The confinement incident to an increasing family sometimes kept her at home;
yet she still continued to travel in the service of truth,
visited various parts of this nation,
and was often engaged in visiting the families of Friends.
She was esteemed a deeply baptised and powerful gospel minister;
her deportment in the exercise of her gift was grave and comely,
and her expression clear;
and in supplication she appeared to be at times favoured
with near access to the throne of grace.

In private life she was an example of meekness and lowliness of heart,
and filled up its various relations with great propriety.
Towards the close of her days she was tried with deep affliction;
but she was enabled not only to support it with becoming resignation and fortitude,
but at times so far to be borne above it,
as even to be much enlarged in her gift of public ministry.
She seemed to aspire after total resignation to the will of the Lord,
in all the dispensations of his providence to her.
She once said to a beloved friend, alluding to the probations of her latter life,
"`The cup that is handed to me, shall I not drink it without repining?`"
and in her last public testimony, she had to declare of the goodness of her Lord.

About the beginning of the Sixth month, 1786, she became ill of a slow fever, and,
on the 15th, she was found by a relation who visited her,
so weak as scarcely to be able to speak audibly.
Yet the same day she revived, and finding her children and some other relations together,
after a time of silence, she addressed them to this import:
"`I have felt so strong a desire for your good, that I must have been weak indeed,
could I not have got downstairs to express it to you.
I have been led to look at the state of our meeting;
and as many of the elders are removed,
I wish you weightily to consider what is in your power to do for the Lord.
Oh! how ardent is the desire of my heart, that you may do nothing against the truth,
but for the truth!
My heart has been humbled in the recollection of the goodness of the Almighty to me,
from my very early years,
in that he gave me his good Spirit to check and reprove me when I had done amiss;
and I am thankful that the Lord inclined my heart to turn at his reproofs,
to receive his corrections, because I had sinned against him.
I regret that I have not made this divine law my more frequent study;
yet this I can say of a truth, I have loved it;
and indeed it has been a lamp unto my feet, and a light unto my path.
I have loved to meet the Lord, and to wait upon him, even in the way of his judgments;
and may now say, though I know not how this weakness may end, I never before,
in the course of my life, have been so continually favoured as of late;
never before had such unclouded prospects of that holy habitation,
where all sorrows and tears shall be wiped away.`"

After this opportunity, in which more was uttered than is here set down,
she continued in a feeble state for some weeks;
and then seemed to gain a little strength;
but her disorder returned about the 20th of the Eighth month,
and was attended with considerable lethargy.
Nevertheless, when awake, she was clear in her understanding,
and aware of her approaching close.
On the 4th of the Ninth month, as she was sitting up, she said,
"`Oh that I had wings like a dove,
that I might fly away and be at rest:`" and after she was put in bed,
she spoke to this effect: "`I resign myself, my children, and the church,
into the hands of a merciful Creator, who is worthy of high hallelujahs,
and eternal praise, both now and forevermore!
Amen.`"
Her last recorded expression was on the following day, a prayer for the church.
"`O,`" said she, "`most gracious Father,
be thou pleased to look down with an eye of tender
compassion upon thy poor afflicted seed.`"
Two days after, on the 7th, she quietly departed.

[.asterism]
'''

ANN NAISH, daughter of Joseph and Betty Naish, of Congersbury,
a village in Somersetshire, about twelve miles from Bristol,
was born about the Third month, 1773.
From her childhood she was of a serious deportment,
and of a calm and condescending temper,
even in cases where her youthful inclination might be opposed:
so that the salutary directions of her parents were readily obeyed.
Her understanding appeared, at least to keep pace with her age, if not to surpass it;
and her steady care to please those who had the charge of her education,
endeared her to them; as her kind, affable,
and obliging behaviour gained her the love of her associates.

This promising maid was called in her bloom from the vicissitudes of time.
Whilst she was at boarding-school at Milverton,
not very far advanced in her fifteenth year, she was taken ill.
Her disorder, water in the head, soon affected the part with violent pain,
and was not long in producing frequent delirium, and sometimes convulsions.
She was, however, allowed many intermissions, and clear intervals of reason;
in one of which, a friend asked her, whether she were willing to go.
She replied, that she was willing to leave it to the Almighty;
that at some times she could not desire any thing;
but at others she had desired then to go.

It was a week before her affectionate father saw her;
and he too availed himself of her undisturbed intervals
to apprize her of the uncertainty of her recovery.
She repeatedly expressed, in very satisfactory terms,
her resignation and acquiescence with the will of the Almighty, often saying,
"`I am not afraid to die.`"
At one time she spoke to her father thus: "`Dear father, thou hast been a tender,
affectionate father to me.
Have I not been a dutiful daughter to thee?`"
He answered fully in the affirmative; and she went on, "`Oh,
I would not have been otherwise for all the world!`"

There was at that time some little article of her apparel,
which by some means had been introduced, and which her father thought not consistent.
He gently remarked it to her; and she freely acknowledged it was wrong; saying,
that it proceeded from pride, and that those who kept near to the principle,
+++[+++the Spirit of Truth,]
would be preserved out of such things.
Her gratitude to those about her,
especially to those who were more immediately employed in
the various offices of assistance which her illness required,
seemed to be almost unbounded: and her patience, her serenity,
and the innocence and sweetness of her spirit, brought to mind the words of the Redeemer,
"`Of such is the kingdom of heaven.`"
She departed, after two weeks`' illness, the 4th of the Seventh month, 1787.

[.asterism]
'''

MARGARET GREENWOOD was the daughter of Thomas and Bridget Greenwood,
of Greenwood-haugh in Dent, a district in Yorkshire,
on the confines of Westmoreland and Lancashire.
Her father occupied a small estate,
which till lately was about the yearly value of eighteen pounds.
On this small farm, which, together with knitting, was their sole means of subsistence,
they brought up five children.
These, when at home, as they generally were, and not engaged in the business of the farm,
were employed in knitting, by which they could earn a little money.
Margaret lived constantly with her parents;
for she was afflicted at times from her youth, with an acute rheumatism,
which rendered her incapable of much active exertion.
This had a tendency to temper the natural vivacity of her disposition,
and to render her the more susceptible of religious impressions.
A few years before her death she was much devoted to the promotion of piety,
and was often concerned to notice and to reprove what she saw to be reprehensible,
either in those of her own, or any other society.

About her twenty-seventh year she came forth in the ministry; and her ministry,
as well as her innocent life and conversation, was acceptable to Friends.
A short time before her decease, she went to Dent Town,
in order to warn a vicious and ferocious man of the consequence of his conduct.
It was supposed that she would meet with insult, and rough usage; but he was softened,
and even received her meekly; and she returned in peace.
She had been engaged in order for marriage,
and the day was agreed to be the same on which her sister also was to be married.
Each suitor had the name of John.
One morning early, their father said to the two sisters, pleasantly,
that he supposed they would not give up their Johns for any consideration whatever.
Margaret replied, after a pause, that there was one thing, and but one,
for which she would give up her John: a place in the kingdom of heaven.

She appeared at that time to be free from indisposition; but about ten in the forenoon,
as she sat employed in her knitting, she breathed her last.
The preceding day she had attended the general meeting at Dent Town,
and had borne a lively and weighty testimony;
and as a meeting was held at the same place six days afterward, on account of her burial,
the minds of the people were impressed in an extraordinary manner.
Her remarkable answer and decease were on the 22nd of the Twelfth month, 1787.

[.asterism]
'''

JANE FRYER, of Warrington, Lancashire, daughter of Benjamin and Margaret Fryer,
was born at Kendal, in Westmoreland, in the year 1761.
From an early age she was religiously disposed.
Her mother died when she was very young,
in consequence of which a considerable care devolved upon her, who was the eldest child.
She afterwards went to be an assistant in the family of a friend at Bristol,
where she was much beloved for uprightness and integrity,
and where she evinced much care and interest for the welfare and preservation of children.
This benevolent and beneficial temper of mind was
the means of inducing her to open a school at Warrington,
to which town she had removed.
Here, also,
she was greatly esteemed by those who united with her in religious profession,
as well as by others who entrusted her with the care of their children:
an employment for which she seemed to be particularly well qualified.
Nor did she teach by precept alone; her example, as a religious character, was salutary;
and on both accounts her loss was much lamented.

Her great concern for the welfare of youth remained
with her in her declining state of bodily health.
She said, "`If my being afflicted might but furnish instruction to our young women,
I should be glad.
I have been very desirous their minds might be weaned
and brought from the exteriors that are about them.
Oh, what vanity they will feel them when such a time as this comes.
My mind has been exercised on their account as I have sat in our meetings.
I have longed that they might experience the work of real religion;
but things have felt so low,
that something of an alarming nature must come to rouse them;
and that language hath been sounded in mine ear, '`Cry aloud, and spare not;
lift up thy voice like a trumpet;`' but, alas! who is sufficient for these things?
I was but a child.`"

At another time she signified that, being favoured with great calmness,
and her mind covered with universal good will,
she was induced to wonder at so general attachment
in her fellow-mortals to sublunary things.
Once, when two friends were with her, she said, "`Oh,
may I have patience to wait the Lord`'s time,
without offending him in being over-anxious.
Let us unite together in desiring I may be preserved
in perfect resignation to his holy will.`"
After a short pause of silence, she was engaged in prayer, thus: "`O, dearest Lord,
Almighty Saviour, if thou wilt, condescend to favour thy poor, unworthy,
afflicted child with the lifting up of the light
of thy countenance--who am deeply tried.
But thou knowest best, O Father, what is best for us,
and necessary that we should pass through, in order to fit us for thy glorious kingdom;
where nothing that is impure or unholy can ever enter.
Therefore, I beseech thee, dearest Lord, let not thine hand spare, nor thine eye pity,
till thou hast made me perfect.
Then I hope to be dissolved, poor dust and ashes, and clothed with angel`'s raiment.
O, permit me to join them in praises and thanksgiving.
My will, thou knowest, has been subservient to thine; and I have endeavoured,
according to my small ability, even from a child, not to offend thee, O my God.
Therefore,
I beg of thee to permit the guardian angel of thy presence
to conduct my poor soul to its everlasting rest:
believing, if I offend thee not, there is one prepared for me,
where I may forever ascribe praises to thy holy name.`"

A little after, she desired her friends to pray for her,
telling them it was a trying season, and that she was sometimes ready to say,
"`Why am I thus prolonged?`"
adding, "`Thou, O Lord, knowest for what end, and thy time is ever best.
Oh, that I may be favoured with thy divine presence!
That will make up all.`"
At another time she said, "`My mind enjoys great quietness.
Oh, the kindness and condescension of the Almighty to me!`"
She said also to the friends mentioned above, "`I love you,
and desire that our spirits may unite together in
worshipping Him who can kill and make alive.
I have had today sweetly to feel,
like a foretaste of that peace which I humbly hope to partake of soon,
without interruption.`"

One of her visitors remarking,
that she believed all doubting would be done away before the final removal of Jane,
the latter replied,
"`I have thought so today;`" and then she broke forth in praising her Redeemer.
She also expressed her desire of a release, in the words of the Psalmist: '`Oh,
that I had wings like a dove!
Then could I fly away, and be at rest`'. I lie lingering,`" she added,
"`just on the brink of eternity.
What an awful situation!
But as the clay to the potter, who dares say, What dost thou?
When a child, I loved retirement --and such awfulness attended my mind,
though I had no language to utter, nor knew what it meant;
yet I durst not disobey these tender sensations;
and I believe the Almighty owned these seasons,
and opened my understanding in early years.
I have been desirous not willfully to offend him; and have had many hidden exercises,
remembering it was said, '`In the world ye shall have trouble; but in me peace:`'^
footnote:[This, thus placed, is commonly supposed to be a text of Scripture;
but it is not one.
The nearest to it, is the last verse of the 16th chapter of John,
"`These things have I spoken unto you, that in me ye might have peace.
In the world ye shall have tribulation; but, be of good cheer,
I have overcome the world.`"]
which brought great sweetness over my mind.
Blessed forever be his name!`"

Soon after, as she was lying in great composure and serenity of mind,
she left the toils of mortality, in the twenty-seventh year of her age.
Her decease was on the 22nd of the Eighth month, 1788.

[.asterism]
'''

LYDIA HAWKSWORTH, of Bristol, was the daughter of Samuel and Deborah Waring, of Alton,
in Hampshire, and born there about the year 1733.
She departed this life in London, at the age of fifty-five.
Her mind had been early visited with impressions of the love of God,
and as she kept under its influence, she advanced in the just man`'s path,
and was exemplary to others.
Having thus by example been in degree a preacher of righteousness,
she at length believed herself required to bear a verbal testimony to the Lord`'s cause.

In the spring of the year 1768, when she was about thirty-five years of age,
she was married to Abraham Richard Hawksworth, of Bristol,
a Friend who had lately become signal for a remarkable change in conduct;
for having turned from the spirit and manners of the world, to bow to the yoke of Christ.
But their union, so far as death can dissolve the tie, was of short duration.
He died in the course of the same year.
A meeting was held in Friends`' meetinghouse in Bristol,
on the occasion of his interment; and his widow, standing up,
and laying her hand on the coffin which contained the remains of her beloved partner,
bore her first public testimony, with weight and clearness; and,
there is reason to believe, with no small effect on the meeting.

Having thus devoted herself to a service for which she had long been under preparation,
she continued exercised in spirit, and humbly waiting for the renewals of power;
by which time, she was made an able minister of the gospel.
She was esteemed to be sound in doctrine, clear in spiritual judgment,
and cautious not to be more in show than in substance.
She was a lover of retirement, and in it often, through deep conflict of spirit,
was enabled to grow in the root.
At various times she visited the meetings of Friends
in most of the counties of Great Britain,
once those of Ireland, and was also a diligent attender of meetings for discipline.
Towards the close of her life she was tried with great affliction of body, by illness;
and to all human apprehension, the lamp of life, as herself expressed it,
was just extinguished.

At this time she dictated to a friend some things
which engaged the attention of her mind;
among which were the following advice and observations.

"`Let ministers be careful not to judge too highly of any of their services:
for it is only when the breath of the Lord blows through the trumpet,
that life and harmony are known, and the great truth is evinced,
that it is only his own works that praise him, or benefit the churches:
nothing that man can do.
In most places, the elders want to stand deeper in Jordan.
A more unreserved, total sacrifice of the world must be made,
and even the accursed thing cast out of some of their tents,
before they can stand as valiants for the Lord`'s cause upon earth.
Every shekel of pure gold in the sanctuary ever had, and still must have,
the signature of "`Holiness`" upon it: for what is of man is but man:
the Lord bloweth upon it, and lo, it is nothing, however specious in the eyes of man.
I see clearly that when the ancient simplicity and purity are known again amongst us,
then the glory of the Lord will appear as in former years;
and his praise sound forth through all the churches.
Therefore, under the fresh flowings of gospel love,
I salute my beloved friends everywhere, and bid them farewell in the Lord.`"

Her last illness was long and painful;
but she was enabled to support it with patience and resignation.
She often experienced her cup to overflow with divine love;
and often administered pertinently to the states of those who visited her.
To a near relation, she expressed herself after this manner: "`Don`'t mourn for me.
I have a comfortable hope that my heavenly Father will receive me into his kingdom.`"
On the 17th of the Twelfth month, 1788, she departed, as has been said, in London,
and her remains were deposited, where she first drew her breath, at Alton.

[.asterism]
'''

SARAH GRUBB, wife of Robert Grubb, of Clonmel in Ireland,
was daughter of William and Elizabeth Tuke of York,
and born there the 20th of the Sixth month, 1756.
When she was very young she was deprived of her mother;
but about the tenth year of her age she became the care of her father`'s second wife,
Esther Tuke, of whom there is an account in this volume, whose tenderness,
and whose solicitude for her increase in things which belong to salvation,
she has frequently confessed.
The care extended in her education had its natural effect:
it was the means of preserving her from many dangers incident to youth.
Nevertheless, the vivacity of her disposition,
and her propensity to withstand that which was connected with self-denial,
occasioned many a struggle,
before she fully submitted to follow the Lord without reserve.

About the age of sixteen it was her lot occasionally to wait upon that eminent minister,
John Woolman, in his last illness;
and his example of resignation and faith made a deep impression on her mind.
To her it was that he said (as mentioned in the 8th part of Piety Promoted) "`My child,
thou seems very kind to me, a poor creature.
The Lord will reward thee for it.`"
In the twenty-third year of her age, she first appeared as a minister;
for which service she had undergone no small preparation,
and had passed through deep conflict.
Her first appearance was in prayer,
and some of her attendant feelings she thus describes: After enduring,
on a First-day morning, a state of agony till the meeting separated,
she attended that in the afternoon like one deserted; yet, contrary to her expectation,
the matter returned; and, assisted by a seasonable testimony from a ministering friend,
"`I ventured,`" says she, "`on my knees; and in a manner I believe scarcely intelligible,
poured out a few petitions.
Now I feel in such a state of humiliation and fear, as I never before experienced.`"

There is something peculiarly touching to what I
trust are the better feelings of the awakened mind,
when we observe this dedication of the faculties in the prime of youth; when, as it were,
the first fruits of the increase are offered to the Lord; and when,
through the various stages of holy preparation,
the soul is at length conducted to a public confession of his power and goodness.
In the harmony of the divine economy, there is no place for emulation and envy;
but I have often thought this period of open dedication in our visited and called youth,
to be eminently sweet, and deserving of our admiration and love.

Sarah Grubb travelled much.
She first accompanied her mother into Westmoreland and Cumberland;
and in the same year joined another relation in a religious visit in Cheshire and Lancashire.
Other services succeeded, during the time she remained single,
and was a part of her father`'s family.
In the year 1782, she married Robert Grubb, who had sometime lived at York,
and they settled at Foston, a village about ten miles from that city.
Soon after her marriage, she visited Friends in Scotland and Cumberland,
and some other places, in company with Mary Proud, then of Hull.

From this time, she was frequently engaged in travelling in the exercise of her gift:
particularly she accompanied Rebecca Jones, of Philadelphia,
in a visit to Friends of Ireland.
In 1787, she settled with her husband at Clonmel, in that nation.
The following year, she joined several other friends in a visit to some parts of Holland,
Germany, and France; and on her return from this journey,
she was instrumental in establishing a boarding-school for girls,
the children of friends, near Clonmel; of which, when at home,
she had the superintendence.

I pass over her other services in these kingdoms,
and hasten to relate her last undertaking, which was another visit to the continent.
Her husband and George Dillwyn, of America, with the wife of the latter,
were her companions in this journey, as they had been in the former one;
and they left London soon after the yearly meeting, 1790.
They sailed for Dunkirk, where at that time several Friends resided,
and proceeded through Holland.
At Amsterdam, she was tried by a separation from her husband,
who thought himself obliged to return home, to assist his brother and partner,
then considered to be near his end.

From Holland, the remaining company went by way of Munster, to Pyrmont,
where several resided who appeared much separated from the common forms of worship,
and were seeking after substance.
Of this sort they found others at Rintelm and Minden.
I shall trespass on my proposed brevity, to mention a blind woman,
who walked to the latter place seventeen miles to meet them.
She spun for a living, and her friends occasionally assisted her.
The visitors asked her if she were not straitened in this respect.
She replied, that she knew she was poor; but that when the question arose in her mind,
"`Lackest thou anything?`"
the acknowledgment always succeeded, "`Nothing, Lord.`"
O, that not any professor of the Christian name would ever fix his desires upon riches.
Here we see it exemplified, that "`Godliness with contentment is great gain,
having the promise of the life that now is, and of that which is to come.`"

They next went to Buer, Osnaburgh, and Herwerden,
(so much mentioned by William Penn,) and by Bielfeld, where they stayed some days,
and through some other places, back to Munster; and were afterwards at Crevelt,
Dusseldorf, and Mulheim, a town near Cologne.
Here Sarah drew up and signed a letter, addressed to Leopold,
then having lately acquired the crown of Hungary,
to which letter her companions added also their names.
It is as follows:

[.embedded-content-document.letter]
--

[.letter-heading]
To Leopold the Second, King of Hungary, Bohemia, etc.

Amongst the numerous congratulations awaiting thy accession to the imperial crown,
accept, O king, our Christian good wishes,
and solicitude for thy present and eternal wellbeing.
We are conscious that we have no claim to the liberty of addressing thee,
but from a belief that the Lord Almighty, who ruleth in the kingdoms of men,
and giveth them to whomsoever he will,
hath inclined us to leave our habitations to visit some parts of this country,
and now engages us, in gospel love, to express our secret and united prayer,
that thou mayest be an instrument in his holy hand
for the advancement of that glorious day,
spoken of by the prophet, "`when swords shall be beaten into ploughshares;
and spears into pruning-hooks; when nation shall not lift up sword against nation,
neither shall they learn war any more.`"

The great design of our universal Parent,
in sending his beloved Son a light into the world,
is for his own glory in the salvation of mankind; and for this gracious end,
he hath given to all men a measure of his own eternal Spirit.
To cooperate with him herein, dignifies human nature,
and is particularly deserving the most scrupulous attention of princes.
The smallest revelation of this heavenly gift in the believing soul,
having a degree of omnipotence in it,
brings into subjection the natural will and wisdom of man,
and discovers to us the noble purposes of our creation.
It diffuses that true benevolence which characterizes genuine Christianity,
and renders dear to a prince the happiness of all, even the meanest of his subjects;
imprinting upon his mind the superior value of an immortal soul,
to all worldly acquisitions.

Through the neglect of a principle so pure and important,
how hath the rational part of God`'s creation been
sacrificed to the irregular passions of sovereigns,
and many unprepared souls precipitated into an awful futurity!
That the gospel dispensation is intended to remedy these evils,
and promote the government of the Prince of Peace;
that the Gentiles are to come to its light, and kings to the brightness of its arising,
are truths to which the sacred records abundantly testify.

May this be thy happy experience,
O king! that so the power thou art providentially entrusted with,
being subservient to divine wisdom, thy example may influence the minds of other princes,
who also beholding its excellency, may unite in encouraging their subjects to decline,
in mutual charity and forbearance,
whatever is contrary to the purity and simplicity of the religion of Jesus.
And mayest thou be enriched with all spiritual blessings; that these,
added to thy temporal ones, may not only perfect thy happiness,
but perpetuate it beyond the narrow limits of time, and qualify thee, acceptably,
to cast down thy crown at the feet of Him who is King of kings and Lord of lords;
who liveth and reigns forever and ever.

[.signed-section-signature]
George And Sarah Dillwyn, Of Burlington, New Jersey, North America.

[.signed-section-signature]
Sarah Grubb, Clonmel, Ireland.

[.signed-section-signature]
Joshua Beale, Cork, Ireland

[.postscript]
====

Members of the religious Society of Friends in those countries and Great Britain,
commonly called Quakers.

====

[.signed-section-context-close]
Mulheim on the Rhine, 29th of 9th Mo., called September, 1790.

--

Soon after this she returned to England, visited her relations in the North,
and reached her home at Clonmel the 12th of the Eleventh month,
greatly exhausted in bodily strength.
Passing a night at Ackworth, on her way from York, with a near and beloved relation,
she thus expressed herself: "`O, my dear!
I think sometimes that I shall soon be gone.
It seems as if my day`'s work was nearly done, and on looking towards home,
as if I might not be long there.`"
On her way to Clonmel, she was at the national meeting of Friends in Ireland,
held at Dublin.
In a sitting of the meeting of ministers and elders,
she gave some account of the journey from which she was then returning.
In doing this, humility seemed to be the covering of her spirit.
"`We have done little,`" said she,
"`but the Lord is doing much;`" and her concluding
words were an humble adoption of those of the Psalmist,
"`Return unto thy rest, O my soul, for the Lord hath dealt bountifully with thee.`"
These are from Psalm cxvi., a psalm well worth the perusal of the mind conflicted,
and yet hoping in the mercy of the Lord.

Soon after her return, she attended the quarterly meeting at Cork,
where also she gave an humble account of her late journey.
At the close of the meeting she was taken ill,
and was confined at the house of Samuel Neale.
In a message to a young woman who then presided at the school at Clonmel, she said,
"`Salute her very affectionately:
tell her I have been much favoured with quietness of mind from the first,
though a stranger to how the present afflictions or trials may terminate;
but the grain of faith and hope which is mercifully vouchsafed,
I esteem preferable to all knowledge.`"

Four days before her close, she dictated a letter to a particular friend,
in which are the following expressions:

"`My soul,
though encompassed with the manifold infirmities of a very afflicted tabernacle,
can feelingly worship, and rejoice in nothing more than this,
that the Lamb immaculate is still redeeming, by his precious blood, out of every nation,
kindred, tongue, and people, and making a glorious addition to the church triumphant,
whose names will stand eternally recorded in the book of life.
I express not these things from a redundancy of heavenly virtue,
but from a soul-sustaining evidence, that, amidst all our weakness,
and conflicts of flesh or spirit, an interest is mercifully granted in Him,
who giveth victory over death, hell, and the grave.`"

Nearly the last words which she spoke, were those of that cheering passage of holy writ,
where the Saviour of men thus addresses his disciples: "`My peace I give unto you.`"
Thus, on the 8th of the Twelfth month, 1790, she finished a course comparatively short,
but filled with deeds of dedication.
Her natural turn of mind, as has been related,
subjected her to deep baptisms and close conflicts;
but grace had so fully effected the work of renovation,
that the observer saw little in her but the unaffected, unassuming, simple,
humble and resigned Christian.

[.asterism]
'''

JEREMIAH WARING, who died at the advanced age of seventy-five, at Thorpe, in Surry,
had been for a long time well known in our religious Society,
especially to such Friends as attended the yearly meeting, at which, for fifty years,
he was nearly constant.
He was the son of Samuel and Eleanor Waring, of Witney, Oxfordshire,
and born there in the year 1716; but, his father removing to Alton, Hampshire,
on his second marriage, he passed his childhood under the care of his grandfather,
Jeremiah Waring, a valuable ministering Friend,
of whom there is an account in the [.book-title]#Seventh Part# of this work, by John Bell.
Of his father and mother-in-law, Samuel and Deborah Waring,
there are accounts in Thomas Wagstaffe`'s [.book-title]#Ninth Part.#

Jeremiah, the subject of this memoir,
appears to have been of exemplary conduct from a child.
He was very assisting to his parents in bringing
up a numerous family by the second marriage,
and in the management of their trade; but,
having a competence for his own limited desires,
he never embarked in trade on his own account.
He devoted his talents and time to the service of others,
and particularly to that of the Society of Friends,
and his leisure hours to reading and retirement.
He took great delight in reading the Scriptures, in which, accordingly,
he was very conversant; and he was accustomed, when a young man,
after the avocations of the day, to walk out, like Isaac, into the fields,
and meditate at eventide in the law that he loved.

He was hospitable to his friends, and compassionate to the poor;
and his benevolence was not confined to merit.
He used to say, "`Did we receive no more than we deserve, how little should we possess.`"
He was twice married.
His first wife was Barbara, the widow of Daniel Pack, of Alton; his second, Mary,
widow of Daniel Weston, of Ratcliffe.
On occasion of the latter marriage, he removed to reside at Wandsworth, in Surry;
but their union was of short duration.
Of Mary Waring, there is an account in Thomas Wagstaffe`'s [.book-title]#Eighth Part.#
He continued to reside at Wandsworth until, in the wane of life,
and as infirmities approached, he went to reside with his only daughter and child,
the offspring of the former marriage, at Thorpe-Lee, in the same county,
where his days were closed.

In the summer of 1790, after a journey to Ackworth, his constitution began to decline;
and, though the decay was almost imperceptible to his constant attendants,
it was firmly impressed on his own mind,
that he should not be restored to his accustomed health.
He would say, after taking a medicine, "`This will not do; and nothing will do long.
I am persuaded this illness is intended for my end.`"
At other times he would say, "`I am tired of the doctors.
Physicians can do me no good.
There is but one Physician: the Physician of value.`"
Thus he gently declined for eight months;
but then the advance of dissolution was accelerated,
and for the succeeding three months his ailments made a rapid progress.

His appetite and digestion failed, and he became weaker daily.
He frequently took notice of these symptoms of decay, and would remark,
"`It is a mercy that I can look on approaching dissolution without terror.`"
Yet it does not appear that he had then received
that full assurance which his soul desired;
for he said once, "`Could I have an evidence that I might be admitted to a place of rest,
it would matter not how soon.
Oh, what a glorious change would that be, from a state of pain and sickness!`"
After various fruitless attempts to relieve him, he was, with reluctance,
prevailed on to consult an additional physician;
but he earnestly pressed the first who had attended him,
to say whether he had any hope of his recovery.
Perceiving a hesitation on the part of the medical man, he repeated his question, adding,
"`Don`'t be afraid to tell me, doctor: I can bear it.`"
One day, after suffering considerable pain, he said, "`I am resigned,
I think pretty much, as to life or death.
Thy will be done.`"

He had been, as has been hinted,
particularly attentive to the concerns of our religious Society;
but within a week of his close, he told an intimate friend,
and some of his near relations, who were with him,
that he feared he had not been so useful in the Society as he might have been; and,
continued he, with tears, "`I have ever loved the cause;
and I wish all those whom I love, to be more circumspect than I have been.`"
He used to converse pleasantly with his friends who visited him;
but when he was alone with his daughter, he would frequently say,
"`I want to be more inward.`"

A few days before his death he said, "`I have, at times, a hope,
He that has been my morning light will be my evening song.`"
Soon after saying this, he told a Friend who called to inquire how he did,
that he thought he might then reasonably expect every day to be his last:
and he always spoke of his great change with perfect composure.
The morning preceding his departure, he said,
"`I have lived to see the light of this day,
but I scarcely think I shall ever see another.`"
About seven, he sent for his daughter, and said to her, "`I believe I am going.`"
Seeing her distressed, he added, "`Nay, don`'t distress thyself.
We must part; but I leave thee in the hands of a merciful Creator.`"
His daughter said that she had hoped the separation would not so soon have taken place;
to which he replied, "`We know not what is best.
Times and seasons are in the disposal of unerring wisdom.
If he sees this the right time, it is so, and we must submit.`"

Soon after, he was desirous of rising, and whilst he was assisted in dressing, he said,
"`I long to be clothed with the white linen, the righteousness of saints.`"
In the evening, when retired to rest, he said, "`All my trust is in Infinite mercy.`"
Soon after, some of his relations being in his chamber,
he took an affectionate leave of them, having first said, as nearly as can be remembered,
thus: "`I am going where the wicked cease from troubling, and the weary are at rest.
I feel that goodness and mercy which have been with me at times all my life long,
to be near me now; and, though I have fallen into many frailties incident to my nature,
have never entirely forsaken me: and I have a secret hope that all will be well.
The Lamb and his followers shall have the victory:
those who have come through many tribulations,
and known their garments to be made white in the blood of the lamb, the immaculate Lamb.
May the God, who, I trust I may say, has been mine, and my father`'s,
and my grandfather`'s also, be the God of all present.`"

Within a short time of his close, he desired to be left with his daughter only;
to whom he gave directions respecting his interment, and some other matters;
particularly,
that he might be affectionately remembered to such
of his relations as might incline to attend it.
Soon after this, he said, "`I die in charity with all the world, and have now, I think,
nothing more to wish for, but an easy passage.`"
This, at midnight, was allowed to him, when,
finishing his course with the 2nd of the Tenth month, 1791, he departed without a sigh.

[.asterism]
'''

FIDELITY HULL, of Uxbridge, Middlesex, was the daughter of Thomas and Elizabeth Stark,
of Fordingbridge, in Hampshire.
In her early years,
she was in some degree inclined to indulge herself in a
deviation from the simplicity of her religious profession,
which deviation her more corrected judgment afterwards disapproved;
yet not by any means in such a degree as is usually termed gay or extravagant.
About the twentieth year of her age she was married to Samuel Hull, of Uxbridge,
and became the mother of two children, whom, however, she did not live to educate:
for she soon showed symptoms of a decline, that terminated in her dissolution.

Early in her illness,
her heart became more and more disposed to seek for the knowledge of the Lord;
and when her disease gained ground, she entertained much doubt of recovery;
yet she said that she should not mind the leaving of this world,
if she had an assurance of happiness hereafter.
She now saw the vanity of indulging in dress; also the pernicious tendency,
to young people, of reading novels, and similar productions.
Pernicious indeed is this practice.
Simply considered, it is a waste of time.
Relatively, it indisposes the mind for the serious concerns of real life;
and for its truest, greatest concern, the preparation for a better,
through the grace and redemption of Jesus Christ, our Lord.
Her anxiety on this account was manifested by a letter which she wrote to a relation;
in which she entreated her, that if she had any such books,
they might be destroyed for the sake of her children.
Similar advice she also left in writing,
for such as might have committed to them the care of her own son and daughter.

A few months before her decease, a Friend called to visit her;
and believed it right to address her with a few words of encouragement.
She was, at that time, preserved in a good degree of resignation;
though she had not yet that full assurance of happiness which she had longed for.
Nevertheless, at the time, his words were particularly consoling;
and in a subsequent opportunity,
he was made instrumental of more complete relief to her much tried mind.
She broke out as it were in rapture, "`Why does the Lord deal thus bountifully with me,
a poor sinful creature, undeserving the least of his mercies?
What is this I feel?
Thou hast healed me of all my maladies, both inwardly and outwardly.
O my Lord, and my God, how sweet is thy presence!
What shall I render unto thee, O my God?
Oh! this is what I wanted.
Now I am happy.
I thank thee, O Lord: for thou indeed art good.`"

She then paused; but soon she turned her eyes affectionately on her mother, saying,
"`Thou hast no need to sorrow for me, for it will be well with me.`"
Nor was this merely a sudden perception of unexpected relief,
and a transient effusion of joy.
The next day she told some visitors of her favoured state,
and expressed herself in a very tender manner.
"`The Lord,`" said she, "`is good.
Yesterday was a memorable day to me.
I think I shall never forget it.
My bonds are unloosed.
There is balm in Gilead.
I feel more sweetness than I can express in words.`"
She also expressed her hope that her visiting friends could feel something of the same;
and she entreated her husband to give her up freely.

But although her consolation was thus great, and at one time, as we have seen,
so transcendent as to supersede her sense of bodily infirmity and pain;
her disease advanced, and her consequent suffering was often felt and acknowledged,
though not repined at.
To her brother, once she said, "`My tribulation is great.
Oh, how careful we had need to be,
to make the Lord our friend! for if I did not feel him near, I could not support +++[+++myself]
under this great affliction.`"

Nevertheless, she had a word of encouragement to most of those who visited her,
and she often exclaimed that God is love; and that those who dwell in him,
dwell in love.^
footnote:[I take this opportunity of observing that this, though true,
and a very common saying, with many pious Friends,
is a transposition of the text of 1 John 4:16, "`God is love:
and he that dwelleth in love, dwelleth in God, and God in him.`"
This whole chapter is eminently worthy of serious and repeated attentive perusal.
It is the effusion of love, through "`the disciple whom Jesus loved.`"
Read it; rivet in your recollection, ye tender and beloved youth.]
She had once an opportunity of conference with two Friends.
I am not informed whether they were Friends in the ministry,
though there is room to suppose it.
They were encouraging her not to withhold any thing she might have to communicate to them.
Making a pause, she replied to this effect: "`I cannot speak unless power is given to me.
I have felt at this season much stripped,
and expect to be tried with the buffetings of Satan.
What can I say to the Lord`'s servants; but that they should hold on their way,
and they will experience peace and joy forevermore.`"

Various admonitory and encouraging remarks were written
or uttered in the course of her illness.
She told some of her relations by letter,
that if they could feel the peace which she felt,
they would leave all the transitory enjoyments of this world, to endeavour after it.
She often earnestly desired those about her to keep near to the Almighty,
and said that he would do great things for them.
Once she said, "`It is clearly presented to my view,
that the gates of heaven are open to receive me.`"
She frequently remarked,
that the peace and comfort of her mind overbalanced
her very great bodily afflictions and infirmities.

Once, when some of her relations returned from meeting, she addressed them thus:
"`I hope you have had a comfortable opportunity together;`" and she remarked,
that though for some time she had been prevented from going to meeting,
yet she was often comforted by the divine presence.
At another time when some friends were present, she expressed herself after this manner,
"`Thy will be done: not mine.
It is better to go to the house of mourning than to the house of mirth.
Oh, that we may be favoured to feel good from the tree of life!
Perhaps we may see the sun arise in all his glory: which is glorious indeed,
to those who view it in its spiritual appearance.
O Lord, be thou pleased to hear us, for we have great need of thy supporting presence.
Give us to sing praises to thy great and glorious name forever and forever more.
Amen!`"

About three days before she departed, being so weak as scarcely to be able to speak,
she sent for her husband`'s father, Thomas Hull, a valuable Friend,
who lived in the town.
Several others of her relations came with him, to see her; in which visit,
after a solemn pause, she was raised in a wonderful manner in praises and prayer,
to the Almighty; and gave such good admonitions to those around her,
as were the means of greatly humbling and contriting their minds.
She departed at length in great peace, the 15th of the Third month, 1792,
about the twenty-third year of her age.
A large meeting was held at her interment, in which a ministering Friend, (Thomas Cash,
of whom there is an account in this volume,) from a distant part of England,
being present, mentioned in his testimony, the sweet,
heavenly frame of mind in which he had found her,
and the satisfaction which he had felt in being with
her about eight hours before her decease.
