== Chapter 3

[.chapter-synopsis]
* Daniel Bowly
* Elizabeth Rathbone

DANIEL BOWLY, Jr., son of Daniel and Sarah Bowly of Cirencester, Gloucestershire,
was a young man possessed of a good understanding, and an amiable disposition;
the pliability of which,
together with an employment which frequently exposed him to temptation, promoted,
though it did not sanction,
a wide deviation in conduct from those religious principles in which he had been educated.
Of this deviation he became fully sensible in the course of a long illness;
which he often acknowledged to be a mercy from that divine Providence,
whose fatherly care had many times preserved him from sudden death when unprepared.

In the commencement of the disorder, which proved a consumption,
his mind appeared to be deeply affected with the danger of his situation,
though he then expressed but little of his feelings.
As his weakness increased,
he remarked how exceedingly awful the prospect of the final change appeared;
and he earnestly desired that he might know a fitness for eternity,
and that when the time came, the divine presence might be near.
His past conduct, he said, had been very erroneous;
but that his supplication for forgiveness had, in his illness,
been attended with such sweet refreshment,
that he hoped it might be according to his desires.
At other times,
his sins appeared so great that he could hardly entertain
a hope it would be well with him.
"`What can be expected,`" said he, "`from a deathbed repentance?
That is a time when all would gladly be saved.
There will not probably be an opportunity given me of proving my sincerity,
by an amendment of life; so that men may doubt it;
but the omniscient Being knoweth how far I am sincere, and I hope, if it really be so,
it will be accepted by Him:
yet there is nothing equal to a proper dedication of time in health.`"

Another time, he said, "`I hope the Almighty will forgive my sins.
It is mercy alone that can save me, who have devoted so much of my life to business,
and the amusements of this world; pleasure, as it is generally called;
but it is a strange sort of pleasure.
It is pain, I feel it pain.`"
In another opportunity, he said, "`What I have to deliver,
is from a prospect of the awfulness of death, which in a short time will be my lot.
Mankind in general are certainly under strong delusion;
yet how kindly the Almighty condescends, from time to time,
to give a degree of his light and help!
But man may outlive this day of grace, which,
through the merciful mediation of my dear Saviour, is now extended to me.`"

At another season, appearing much distressed,
he desired his sister to read a chapter in the Bible to him;
after which he broke forth in earnest and pathetic exhortation to those present,
to prepare whilst time and health were afforded; saying, that a little encouragement,
during the reading, had been given for himself;
and that he believed it was for some one present he had been so tried; adding,
"`I long that my friends would begin the work of religion in the life of it,
for if the first offers are slighted, oh! how does the visitation deaden on the mind!
It appears to me as though my own redemption is now nearly completed,
and that I may be detained here for the good of others;
and I hope if there be anything to be done, the Almighty will enable me to do it.`"

He also said,
"`How comfortable would it be to meet my relations in that state of happiness,
where I believe a residence to be preparing for my soul!
I believe the Almighty detains me here as an example of his great mercy,
and as a warning to some;
but I earnestly entreat none will depend upon the same singular act of mercy.
All the friendships of this world must be given up; and,
if the mind be not illuminated with an immediate proof of the presence of our dear Saviour,
yet it should be resigned, and prepare itself for the reception thereof,
by a surrender of everything which does not appear consistent with a state of preparation.`"

One time, speaking of trade, and that he seemed glad he had done with it, he said,
"`I hope I am not hardened or insensible of my state.
I have earnestly supplicated for repentance,
and have sometimes experienced something like touching the hem of the garment;
but not quite so neither, as that was fully efficacious; but this lasted only for a time,
and I seemed again left.
In the forepart of my illness, a few times I asked for recovery,
if consistent with the divine will;
with desires to be strengthened to lead a different life from my past;
and to serve that good master whose doctrines I have, as it were, trampled under foot;
but I have since seen the favour it may be to me to be taken from such a trial.`"

He said also, "`What a favour it is to be members of our Society!
Its rules forbid nothing that is good for us.
How earnestly do I wish my near connections, in particular, may keep to the truth!
Though the path may appear hard at first,
yet as they follow their Leader with a single eye, it will become more easy.
There may be times of withdrawing of the divine presence,
and then the enemy will seek to enter: but by earnest supplication,
preservation will be granted, and at times a comforting foretaste of future happiness;
and the prospect of getting every day nearer to such an incomprehensible reward,
is a favour beyond expression.
How little satisfaction results from a life of pleasure, attending places of diversion, etc.
Ah, the disappointments such meet with!
I believe bitter portions are often their lot.`"
He observed how he had been struck, when at those places of amusement,
with a conviction that he was far more blameable than his companions,
who had not so guarded an education; that, however innocently some of them attended,
it was not so with him.

Embracing one of his brothers with great tenderness,
he desired him to attend to what he had said, which was not in his own will; but,
he believed, through the Spirit of Christ,
who in his unspeakable mercy had made of him such an example.
He exhorted his brother and sister to endeavour to
train up their children in the right way;
as it is from the rising generation an advancement in society is to be expected.
He remarked the many memorable instances in "`Piety Promoted`"
of children from nine years old to fifteen and twenty,
appearing in public testimony in meetings; and he said,
he thought the care of children a great trust; but that the reward would be answerable,
if rightly discharged.
He recommended beginning with them as soon as their minds opened;
and not plunging them into business at too early an age;
and he remarked the great preference due to religion before earthly substance.

One morning, inquiring if it were not the meeting-day to morrow,
and being answered in the affirmative, he said, "`I almost long to go.
How pleasant is the thought of being retired there from the world,
when the generality of the people are in the height of its engagements!
How foolish and unwise are men who are bartering their souls for gold, paltry gold!
The too eager pursuit of it is a great hurt to some of our Society.
If I were to recover, and found business stood in my way to peace of mind,
I think I would give it up entirely; or do but little, and live accordingly.
What signifies grandeur or curious food?
The taste goes no farther than the mouth, then it is over.
If some men heard me talk thus, they would think me foolish; but in this I am wise,
and know what I say.`"

He advised young men not to spend their time unnecessarily at inns,
but rather to go to friends`' houses, where he thought they would be welcome.
He had, he said, thought otherwise; but that in the liberty he then felt,
he could go to any friend`'s house.
"`I believe,`" said he, "`the hope which I have, will continue with me to the end;
yet the enemy is very busy,
and would persuade me I have nothing to do with the kingdom of rest;
but that is his temptation, and I must pray for patience;
for I think the prospects I have had from time to time cannot be delusion.`"

A friend asking him how he did, he replied, "`I am very weak,
but I hope I shall be willing to bear everything
the Almighty may be pleased to lay upon me,
so that I can but just get within the gates of peace.`"
At another time, he said, "`I wish I had served my dear Saviour in my health.
Oh he is a kind master.
How much time have I lost! how distressing must be the situation
of those who are sleeping the sleep of death,
until the last trumpet be sounded in their ears!`"

Several friends being in his chamber, one evening,
he spoke of that wonderful gift dispensed to all,
even that Holy Spirit which manifests our duty;
and he recommended an immediate compliance with its discoveries;
"`For since`" said he "`these illuminations are not at our command,
it is very unsafe to trifle with them, by giving way to the suggestions of the enemy;
but rather resign whatever may be called for;`" adding,
"`Can we not return a part to Him who gave the whole?
What if it deprive us of a few luxuries?
We can have but food and raiment;
which only differ a little in kind between rich and poor.`"

He recommended, that after being at meeting,
and having been favoured there with tender impressions of good, as he sometimes had been,
great care should be taken not to lose them, by too soon entering into conversation,
concerns of business, or attention to anything of a contrary nature,
whereby the mind might be deprived of the benefit intended.
"`Our profession,`" said he, "`is a very exalted one; and if we keep to it,
would make us as lights in the world.
Our religion teacheth us to believe in immediate communication with God,
through his beloved Son; which is an unspeakable privilege to all who attend to it: and,
wonderful condescension! that he who is Lord of all, should thus notice poor man; and,
time after time, be visiting with the offers of his mercy to insure our happiness;
visitations we should be very careful not to reject, as being a common favour,
and think we will accept them at some future time.
For, though the Almighty is long-forbearing and delighteth in mercy,
we know not when may be the last offer of his grace to assist us in the work of salvation.
What a dreadful thing would it be to withstand the last!`"

Speaking of the evidence he had of his future peace, he said,
"`I have a clear view that I shall be received into the kingdom of rest and peace.
I see the gates of heaven standing open to receive me,
and thousands of the just waiting to embrace me.
I desire but just to get within the pales of safety, to be in the presence of the Lord,
and to behold his glorious countenance.
"`O! death, where is thy sting?
O! grave, where is thy victory?`"
Christ taketh away the sting of death.
My dear Saviour is reconciled to me.
I know he is.
His mercy is very great.
I cannot speak enough of his mercy.`"
Some one remarking how exceedingly quick the last three weeks had apparently passed away,
he replied, "`Yes, and perhaps there are some who have not done anything in the time,
which is a serious consideration: for in one week a man may be taken sick and die;
and if we do not close in with the visitations of God in time,
we shall be lost forever.`"

At another time,
"`Let us be earnest in making ready for the glorious kingdom of rest and peace, where,
Oh, that we may enter!
And all may, if they will.
Let us endeavour to do a little every day; let none be discouraged,
though their progress in religion may be slow; yet let them keep on in their little way:
for I believe our kind Saviour may, at times,
withdraw his sensible presence from us to try how our faith will continue;
yet if we hold on, our reward, at last, will be great,
and as much as those who feel a present one.`"

On the 9th of the Eighth month, his sisters, who lived at a distance, came;
at which he much rejoiced, having often expressed a desire to see them again.
The next morning he affectionately addressed them,
desiring they would be particularly careful of the
cultivation of their children`'s minds;
and not make business the first object for their sons; a very little being sufficient,
and that great portions were by no means desirable.
In much weighty advice to those present,
he wished them to make an offering of all they had.
Particularizing one of his sisters, he also said, "`What thy conscience tells thee,
that mind; and what is told thee to put on, that wear; and what is told thee to give up,
give.
Fear not the great or rich, but be alike to all.
Be religious, and then you will have our Saviour`'s arm to lean upon.
Oh, he is a merciful Saviour!
I have found him such; an easy master, a kind friend.

Ah! how I regret that I neglected serving him some years.
Think what a superior education we have had, to most; what a nice institution is ours,
the peculiar institution of God; and I believe it is not to die away,
although some of our Society have gone from it, for whom I am sorry.
I believe great advantage may arise from frequently comparing time with eternity,
an awful eternity.
It appears to me exceedingly awful.
Heaven and hell are placed before us.
We have now our choice; and we know what wretches hell is composed of; foul minds,
full of remorse forever; for their worm never dieth.
On the other hand, in heaven there is great harmony.
Oh, I have had beautiful prospects!
I have seen the innumerable company of angels, and the spirits of good men!
But how is it?
We are ashamed of not complying with man, and not ashamed of doing so to God.
We can apologize to man and say, we are sorry we did not do so, or so,
and we can directly go, commit neglect before God, and feel no sorrow for it.
Oh, what mercy there is!
In great wisdom and unspeakable kindness is the good Mediator given to reconcile us,
and work redemption in us.
Do not let us fear man.
What is he?
Look upon me, and see a poor weak thing who can hardly speak.`"

After this earnest exhortation to those,
for whose eternal happiness he was so affectionately and deeply solicitous,
he was much exhausted, and, desiring to be put to bed,
uttered the following short ejaculation; "`Oh, Lord God Almighty,
be thou pleased to look down upon, and be with us!`"
With some difficulty he got to bed;
and for several hours his cough and other symptoms were very alarming,
and were thought to indicate approaching dissolution; but after having slept some time,
he took some refreshment, and said he must now endeavour to say a few words more,
as he might not have another opportunity.
Most of his near relations being present, he called particularly to one of his sisters,
requesting her to sit near him, that she might hear what he had to deliver;
and he was wonderfully strengthened to testify with power to the truth;
beautifully setting forth the means of salvation appointed for all.

Some of his relations standing by his bedside one evening,
he remarked how contemptible the world appeared; and speaking of its wickedness,
he added, "`I would not be understood to despise the world itself.
No; it is the creation of God;
and we are placed there to enjoy all things with temperance.
If it were as it ought to be, it would be a sort of paradise;
it would be a happy pilgrimage to eternity;
it is the depravity of man that makes it so detestable.`"
He cautioned some of his friends to beware of the fatigues and encumbrances of business,
saying,
"`It will not do for those who have been all the
week in the hurry of business to go to meetings,
and appear before the Lord in form only.

A man whose time is wholly engrossed in business in common,
if he goes to meetings pretty constantly, and sits there two hours,
yet it is to be feared his thoughts will be engaged
on that which takes up the greater part of his time;
and if it be so, it is great mockery of God.
Neither will it do to go on in an outward show of dress or address,
if not true worshippers of the Lord, in spirit and in truth.
They must daily give up their minds to him, daily retire to worship him.

I know a man ought to provide for his family, and carry on a proper business,
which I believe to be right; but it should by no means be the first object,
for riches will be nothing in the end.
What would I give now for all the world?
Why nothing at all.
I don`'t regard what the natural man may advance in opposition
to this doctrine of giving up all for the sake of religion.
I am now upon the brink of death to the body, but opening into the life of the spirit.
I am going to live forever,
and I am certain nothing will do but giving up every
earthly obstruction for the cause of God.
Make him a sacrifice; offer up all you have; offer up your lives to him,
as Christ did his for your sakes and mine.
Perhaps some may, from the strength of health and abilities,
be ready to conclude what I say proceeds from weakness.
I know it does not, but that it is the truth, and you will all find it so;
and that man who trusts to the strength of his own mind, or natural understanding,
will be wrong, for nothing will do without God.
Now, remember this; think of it upon your deathbed, and you will feel it is true.
So farewell in Christ.`"

The 12th of the Eighth month, addressing one of his sisters, he said, "`Sister,
how many times have I been preserved from death, times more than I can remember!
Ah, how often, sister, have some of us been raised, as it were, from death!
We should often think of it, and how we have answered the kind intention.
It may not be so again.
The next may be the last time.
Then do let us begin to prepare and do everything that is required of us.
I believe plainness of dress is.
We are indeed a chosen people, and what may not be wrong in others is so in us.
Plainness of dress is as a hedge about us.
The world is not then seeking our company.
Do remember what our Saviour said, "`Whosoever denieth me before men,
him will I also deny before my Father who is in heaven.`"`'

At another time he said, "`I should be distracted if, on this deathbed,
with all this pain and weakness of body, I had my sins before me.
What horror should I feel!`"
A Friend expressing a desire to help him, he replied,
"`None can help me essentially but my dear Saviour: he can release me,
if it be his blessed will.`"
He advised one of his relations to bring up her children in a plain way; knowing,
from experience,
what a disagreeable situation those were in who accommodated themselves to their company.
"`This,`" said he, "`will not do.`"
He believed the easy way chosen by many of our Society
had as little religion in it as any,
or less, and was highly displeasing to the Almighty.
He also recommended a single line of conduct.
He often spoke of the benefit of retirement,
and said that other things must be given up to gain it.
He wished not to be interrupted during meeting time; for, although not able to go,
he loved to compose himself, when the nature of his complaints would admit of it,
and was often favoured with great stillness at those times.

He impressively said, "`The enemy is still very busy with his insinuations,
and would persuade me that all is done, and so lead to neglect;
but I must watch and pray to the end,
and be very earnest with the Almighty to continue his favours,
and that he will support through all.`"
For some time he was much proved with poverty of spirit, added to great bodily weakness;
but his desires were for patience, saying,
"`It is very trying to bear such great lowness and sinking of body and mind.
What can I do, but endeavour patiently to bear it, looking constantly to the Almighty?`"
Some one asking him how he was, he answered, "`I am very low,
but I keep mine eye upon God.`"

His sister, having sat up with him, remarking how comfortable a night he had passed,
he said, with much sweetness, "`Yes, I prayed for a little respite,
and it has been granted me.`"
About this time his strength recruited so much, for a few days,
that the possibility of a recovery was hinted to him.
This at first seemed almost more than he could bear; but after a pause he said,
"`In this also I will endeavour to seek after resignation,
and keep mine eye to my Saviour; who, I ardently hope, will now take me,
having in kind mercy so prepared me for my change.
Can it be, after the near prospect that I have had, that I shall enter life again?
I must endeavour, earnestly endeavour, after patience.`"

Some hours after, being asked how he did, his reply was, "`I feel myself quite resigned.
I have supplicated for patience, and I hope I shall be contented to live,
if it be the Lord`'s will.
I know he can preserve and keep me.
Indeed I have experienced such resignation,
that I think I could feel a pleasure in living,
that I might bear my cross in the world.`"
He was indeed preserved in a very patient, waiting, frame of mind,
and expressed but little for several days; but his company was truly pleasant,
and his deportment evinced where his mind was centred;
though he said the enemy was so busy, tempting him to doubt,
that he had hard struggles at times to keep his faith.

The effort of nature, upon which the intimation of recovery was grounded, again subsided;
his cough became more troublesome, and increasing weakness was evident.
He remarked, "`I believe I was too anxious to go, a little time since;
but now I feel willing to wait the Lord`'s time for the end.
I have reason to hope my disorder is making its progress.`"
He was naturally of a compassionate disposition; and, during his illness,
often spoke feelingly of the poor, recommending liberality to them; which, he said,
he had seen to be a Christian duty;
and how much greater satisfaction would result from relieving their wants,
than from unnecessarily accumulating wealth.

About the end of the Eighth month,
he was strongly impressed with a belief that some
one of his relations would be removed before him;
and in a day or two after, an account came that one of his aunts,
who had been for a long time in a poor state of health, was very unexpectedly deceased.
When this was mentioned to him, referring to the above intimation,
he said he thought he should now be soon released.
On the 1st of Ninth month, he said,
"`The state that I expect to enter is that of calmness and peace: divine peace,
the purest spirituality.
When I have spoken of gates or doors, I wished to imply an entrance into this state;
for I believe my ideas of future happiness are not gross.
I hope to live in the presence of God, and to feel constant support from him;
and I do not wish to know more.`"

The next day he was very weak, and reluctantly left his chamber.
Some hours after, he was seized with a violent fit of coughing,
so that the hour of separation seemed, both to himself and friends, fast approaching;
and, in a short respite from the cough, he expressed triumphantly, "`I am happy,
I am happy!
If I never speak more, give my dear love in Christ Jesus to all my friends.`"
After being relieved, by bringing up the phlegm, he was put to bed,
and some time after remarked,
"`Death is awful! very awful! but I have full faith in my foundation.`"

At another time he said, "`I believe my dear Saviour is ready to receive me,
figuratively speaking, into his arms; that is into purity;
and I believe that is what all good minds desire to enter into.`"
He desired he might not be disturbed when he was thought to be going;
and hoped he should have an easy passage, and that he might go off in a sweet sleep.
He said, "`I have earnestly prayed for you.
Do you pray for me.`"
Shortly after, observing his friends affected, he said,
"`It is not from a callous disposition or hardness of heart,
that I appear unmoved at parting with all my near, dear, and beloved relations.
It is the advantage I shall reap myself, that is my support;
and knowing there is a powerful visitation extended to you,
so that you may all gain an admittance, and soon be in the same place with me.`"

In the evening some one remarking how exceedingly hard it rained, he said,
"`I like to hear it; the sound of it is solemn, being the work of the Almighty.
The withdrawing of the sun, and darkness,
is like what good souls experience in the work of redemption;
when divine light is withdrawn from them, and the damps of melancholy felt.
In these seasons what strange ideas is the mind tried with;
such as are very apt to cast down timid minds; but there is a secret support sustains,
though at such times not sensibly felt.`"
On the 3rd he expressed an earnest desire for an easy passage,
making solemn supplication, as follows, "`O, Lord God Almighty! have pity upon me.
It was thou who created both soul and body.`"
Some time after, to a near friend, he said,
"`I believe the enemy has now almost done with me.`"

On the 4th he was very weak, but still and composed.
He said, he was going to the Father and the Son; and, looking on his friends,
bade them farewell.
A short time after, he remarked that he felt such an entire resignation that,
if it were the Lord`'s will, he was willing, even now, to recover or die;
and how comfortable it was to be thus favoured to the end.
About twelve o`'clock he took an endearing leave of two
of his cousins who had tenderly waited upon him;
soon after which, a considerable alteration was apparent,
and his voice was become so weak that little could be understood;
but he continued in a heavenly frame of mind, full of love.

The last connected sentence which was distinctly heard,
was as a seal to the foregoing truths, being this: "`I have the satisfaction to say,
I have been washed in Jordan.`"
Not long after this, he appeared to be retiring to sleep; but the fact was,
that he was quietly departing;
which he did in the manner for which he had so often prayed, without a groan,
or even a sigh.
His corpse was interred on the 11th of the Ninth month, 1793,
in Friends`' graveyard at Cirencester.
Aged twenty-five years and eight months.

[.asterism]
'''

ELIZABETH RATHBONE, daughter of William and Rachel Rathbone, of Liverpool,
was born the 15th of the Fourth month, 1756,
and was removed by a decline the 30th of the Ninth month, 1793.
Her mother died when she was little more than four years of age.
Her father, on whose own education not much pains had been bestowed,
was so sensible of his loss,
that he determined to give his own children as good a one as could be obtained,
within the limitations which should always bound
a religious parent in his conduct to his children.
Desirable accomplishments may be purchased at too dear a rate;
and when the acquisition of them really interferes with the more important learning--the
learning of him who is meek and lowly of heart --it is time for the Christian parent,
at least, to be closely on his watch.

Thus limited, her father saw the advantage of mental acquirements;
and his paternal care was repaid by the acuteness and diligence of his daughter.
She quickly imbibed instruction, and was so fond of being taught,
that she was often held up as an example by those who instructed her.
Her disposition was lively and volatile;
yet she was not observed to make any wide deviation from the simplicity of her profession.
This, however, was rather owing to the watchful care of her pious father,
than to her own self-restraint.
Without that, there is reason to fear that she would have wandered far astray.
For, notwithstanding her youth was so carefully guarded,
she admitted many things to a share of her regard, which,
when she was fully awakened to a sense of her spiritual state,
she found it her duty to resign.

One of her great amusements was reading,
and her reading was far from being confined to profitable books.
In the choice, too, of her associates,
she sometimes loved to be among such as rather led her away from the path of self-denial,
than assisted her to enter and pursue it:
and it is probable that in such company she was a welcome visitor.
A good understanding, well informed, added to the vivacity of youth,
and to a temper desirous of pleasing, is generally received with applause;
but there are few who possess these accomplishments, in whom the consciousness of talent,
and the praise of others, do not occasion a secret self-approbation, bordering on pride.

About her seventeenth year, her mind became impressed with serious thought;
and she found that a narrower way than that in which she had been accustomed to indulge,
was the path to peace.
She said to her much beloved sister one day, after having been in some gay company,
"`This kind of visiting I must resign.
I do not know how it may be with thee,
but at such times I exert all my powers in such a manner, to accommodate myself,
to appear agreeable, that when I return and reflect, I find I have given all out,
but I take nothing in.`"
Her father, of course, would express his disapprobation of time thus spent,
and said that he saw in it a snare.
She acknowledged that he was right, and soon began to alter her course.
She yielded to one impression of duty after another,
until in a few years she became a very religious character; and,
as the influence she had with many of the younger class was great, a very useful one.
The sequel will show that she had learned to say, I am an unprofitable servant.

She remained for about twenty years a much esteemed member of our religious Society,
but often endured great depression, and even conflict of spirit; not only from the sense,
with which her mind was touched, of the state, the low state of the church;
but from frequent apprehensions that she might be
called to minister to its wants by a public testimony.
Her last illness was lingering.
It afforded ample time for retrospect,
and for application of heart to Him who can supply
every want of his humble and dependent children;
and she was mercifully enabled to avail herself of the opportunity.

In the forepart of her confinement she was deeply tried
with the desertion of that good in which she had delighted,
and with painful apprehensions that her day`'s work,
when weighed in the balance of the sanctuary, would be found wanting.
Her conflicts were great; she dwelt much in retirement,
and was very cautious of relating to others what her soul was passing through.
But about three months before her decease,
she found freedom to open her mind to her sister, her most intimate friend.

She confessed that if she had erred, it had not been for want of knowledge;
but that a full portion of divine light had been granted to her.
"`I now see,`" said she,
"`it is an awful thing to be found carefully acting in conformity to it.
By this light, in my early years, my understanding hath been often opened,
not only to see clearly into my own state, but also into the states of others;
some of whom I seem clear of; and this I count a favour.
My bodily weakness is such, from complicated causes, that I should find it difficult,
if now required of me, to obtain relief.`"

Speaking of some of her social duties, she said,
"`Ah! had I served my Maker with as much faithfulness
and dedication as I have performed these,
I might have looked forward, in this awful time, with confidence.
Yet, I think I dare tell thee, I feel my faith so strong,
and so indubitably fixed in the merits and intercession of a crucified Saviour,
that my mind is wonderfully supported and stayed in quiet composure,
having an evidence mercifully vouchsafed that some of my
transgressions are blotted out from the Lamb`'s book,
but that this is granted of his own free mercy.
If I had not the most unshaken belief in the gracious Mediator,
I know not what I should do now; but yet I feel I have still to pass,
as through the river of judgment.
I have laboured to cast all my care upon Him,
through that help which he has administered.`"

On a certain occasion she was sending a message to her brother`'s wife,
and delivered it nearly thus: "`Thou mayest give my love to my sister,
and tell her I should be glad to see her,
as soon as her condition will render it prudent.
And thou mayest also tell her that my mind is so centred in deep, inward quiet,
that I feel resigned and weaned.
Oh, that I could give her an idea of what I now enjoy in this state!
Were ten thousand worlds offered, I would not accept them in exchange for it,
nor change this bed of sickness for the most prosperous
condition that could be placed in my view.
No human help that could be administered would be adequate to what I now feel.
All is made up in this deep inward quiet.`"

Some weeks after this,
when she had been conversing with her sister respecting
her secret conflicts of later years,
and expressing her faith that her multiple transgressions were washed away, she added,
"`I think I have seen, more particularly of late,
that the state of the church triumphant is not more glorified
than the members of the church militant would be,
at seasons, if they had faith to believe, and in the exercise of this faith,
carefully occupied, in deep abasement, with their several gifts.
How precious would be their fellowship!
How would they participate with purified spirits in union and communion!
Oh, how I long that those in the ministry would keep their places!
Then indeed, I do believe,
they and all the living members of the mystical body would know,
in a much larger degree than they do, a partaking together of the glorified state.
But then,`" she faintly and movingly added,
"`I know it is difficult to believe this possible, whilst engaged in conflict and dismay;
especially when we remember the manifold infirmities which encompass us,
during our continuance in these shackles of mortality.`"

On the 24th of the Ninth month, which did not precede her departure one week,
she made an effort to clasp in her arms her sister, who was then sitting by her;
and she said, in a very moving manner, and with a flood of tears, "`O, my sister,
how have I desired that thy mind and mine may be strengthened in the hour that is approaching!`"
In this she alluded to her dissolution.
"`If I durst have asked for it, for thy sake my language would have been,
"`If it be possible, let this cup pass from me;`" but I dare not: for how do I know,
if my life was given at my request, what might afterwards follow; what flaw,
or what stain I might contract.`"

The following day, when her sister, who had sat up with her a part of the night,
was about to take her leave, Elizabeth, looking at her tenderly, said, "`O,
my dear sister, thy distress moves me, though it appears very endearing.
But let my confidence be thy stay,
because the arm that is underneath is worthy to be trusted in.
It is worthy, for it will be found sufficient.
I feel that I dare lean upon it.
It hath been my support; and be thou satisfied that this dispensation is all in wisdom.
I`'ve seen it clearly; and if the help which,
is hitherto been mercifully afforded do but continue,
I trust I shall be able to take the cup with resignation,
and keep in patience to the end.
But, if ever, through the pain of the body, I should let drop an impatient expression,
do thou deal faithfully with me, and be sure to tell me of it;
for on this head I have many fears.`"

She was much distressed with difficulty of breathing; and on one occasion,
when her sister, who had been endeavouring to give her some assistance, said to her,
"`What shall I do for thee?
I do not know how thou supportest these sore nights;`" she replied, with great sweetness,
but very emphatically, "`Oh, they are mixed with constant goodness-constant goodness.`"
In the morning of the 27th,
she said divers things respecting the children of her brother and sister Benson,
and respecting the close and intimate union which
she and her sister had been favoured with.
"`Oh,`" said she, "`how I wish that thy dear Abigail and Rachel may be thus united!

Press it upon their minds.
It is a point of importance for children of the same parents,
to cultivate a tender regard and sympathy with each other.
It is difficult for the best chosen friends to enter so intimately into the varied
circumstances and difficulties that attend our allotments in life,
as two sisters who seek to have the divine cement,
to strengthen the natural bond of union.
My early friendships were carried too far,
and on this account a weight of condemnation ensued;
for I found that I had been planting heavens of my own, and earths of my own;
and when the day of the Lord came, which burns like an oven,
I saw all these pleasant pictures were to be destroyed.`"

To her sister`'s husband, she said thus:
"`As to the intimations of encouragement which I have received from man,
that my spirit was already a pure spirit, I have never been permitted to build upon,
or draw consolation from them; but in the deepest and darkest plunges I have had,
unworthy, totally unworthy as I have felt myself,
and all I had to hope for was divine mercy, my faith has not failed,
that he who said to the leper, "`I will,
be thou clean,`" was able to render me meet to associate with saints and angels,
and the spirits of the just already made perfect.
I can now freely mention,
that if I had been perfectly obedient to the vocation wherewith I was called,
I was intended to have filled up a different station in the church,
from what I have done.
Whether my life might thereby have been prolonged or not, is hid from me;
but if in this I have erred, I hope it is washed away.

Though I have sometimes looked at the separation of the
spirit from the body with fear and apprehension;
yet it is now wholly taken away.
My last two nights have been sweet nights.
Death has lost all its terrors, and I feel the grave will have no victory over me.`"
A few nights previous to her departure, she often spoke of her father,
as she had frequently done before, in very affecting terms.
She said that she was satisfied that his spirit was sweetly centred in celestial regions;
that she had often been permitted to hold sweet communion with it; and added, "`Ah!
I feel he is gathered.`"

About eleven o`'clock on Seventh-day morning, the 28th,
she was seized with a very strong spasm; and believing herself about to depart,
she desired that her sister and her husband might be called.
After they came to her, the convulsive affection abated,
and she desired to be placed in a chair.
Being there, she said, "`Indeed, my dear sister, my sufferings are very great.
Let me request thee to endeavour to reconcile thy
mind,`" to her sufferings doubtless she meant,
"`and don`'t ask me to get into bed any more.`"
This request was of course readily granted;
and from this time commenced the more apparent symptoms of approaching dissolution.

In the afternoon she asked for two of her sister`'s children,
and spoke to them beautifully,
adapting very remarkably her discourse to their understanding.
When they were leaving her, she made signs for their return; and, kissing them,
as she had done before, she burst into tears, and said, "`My dear children,
may the Lord bless you!`"
She had also desired that,
if she lived till morning she might see her own brother and his children.
She also desired her sister`'s husband to read that passage in the Revelation,
where it is said,
"`Blessed are the dead who die in the Lord;`" and when he took the Bible, she said,
"`Thou mayest read the whole chapter.`"
This being done, a solemn pause ensued.

Her own brother was now also with her; and with great calmness, and very distinctly,
she thus expressed herself:
"`I have been thinking much this day of the passages which have now been read;
but I did not recollect they were uttered through so much distressing experience.
I am convinced that a submission to the crucifying power must be witnessed a
submission to that which alone can make a separation between joints and marrow,
between the precious and the vile; all must be crucified,
before they can be profitably understood, or opened to our understandings.
But as the unfolding of them is patiently waited for, in child-like simplicity,
these mysteries will be revealed to us: especially,
as we become redeemed from the wisdom of the world, and all its pollutions,
and follow the Lamb immaculate in perfect simplicity--follow
him whithersoever he is pleased to lead us,
without grasping at too much, being assured that sufficient hath been,
and will hereafter be, revealed to us.

As we are thus content to follow him in all his manifestations,
we shall experience a measure of the new birth, or of the new life unto righteousness,
to be so formed in us, that whether he may lead, or put us forth into service,
or we may be led in a way incomprehensible to our fellow pilgrims, it will be enough.
For in this total surrender of our wills to the Divine will,
in which we are enabled to say, Work with me, as it seemeth good unto thee,
the great name will be equally glorified.
For his glory consists in our doing his will;
but this requires the total surrender of all our faculties; of all we have,
and of all we are, to him: and however deeply we may be tried,
whatever we may have to pass through in this life, or in death, it will be our support.
The evidence of it hath been to me as the shadow of a mighty rock in a weary land.

I have been much tried with poverty, and +++[+++have]
passed through many sore conflicts, even during this sickness;
but my trust and confidence remain unshaken, that as we are stayed upon his name,
which is his power, though we may be brought to the balance of the sanctuary, and +++[+++it]
may appear poised, as to the weight of a hair, and we,
not being permitted to see how it preponderates, or how it may turn with us,
may be surrounded with deep dismay;
yet as we have been willing to surrender ourselves wholly unto him,
he will make up every apparent deficiency.
In this purified state, we shall have to behold Zion a safe hiding-place,
and Jerusalem a quiet habitation; so secure, that not one of her stakes can be removed,
nor one of her cords be broken!
Had not my confidence been in prospects and convictions like these,
I know not what I should have done in this trying hour.
It is all I have to lean upon, and I feel its support.`"

After a pause, she added, "`And now, my beloved brothers and sisters,
do you remember this my dying testimony.`"
Her attending relations were apprehensive,
from the struggle which this exertion had occasioned,
that the conflict would have ended in her speedy dissolution; but she again revived,
and passed Seventh-day night and First-day in more ease than was expected.
About twelve, on First-day night, she had a return of the spasm with great violence,
which was succeeded by a slight delirium.
Towards morning she became much troubled,
expressed a fear that her sufferings were prolonged in displeasure,
and said she was sensible of being held on some account; but that on examining herself,
she could not see the cause.

Then she looked on her sister in a very moving manner, and said, "`O my sister,
I fear thou canst not give me up.
It seems as if I felt thy resistance; and my captive spirit wants to be set free.`"
Her sister replied, that she did all in her power to submit;
did not dare to call in question the dispensation; was mercifully permitted to feel calm;
and thought she could venture to say, "`I have resigned thee.`"
"`Ah,`" said Elizabeth, "`but hast thou made a cheerful surrender of me?
for that only will be acceptable from thee.`"
Her sister again replied, hoping that she could make some allowance for her weakness;
and would feel that some would also be made by Him
who condescends to compassionate our infirmities;
that her dear sister knew the loss would be very great; yet,
sensible of Elizabeth`'s sufferings,
and beyond all doubt of her fitness to enter the mansions of undisturbed rest,
she had laboured against all selfishness.

A short time after this, Elizabeth, looking with unutterable sweetness,
took her sister in her arms, and kissing her, said, "`I am afraid I have afflicted thee.
I do, my dear sister, feel for thee, for thou art to be felt for; but do give me up.
I must go.
May the Lord support thee.
I am free to tell thee now, and I have not had liberty before to do it, My work is done,
and I am ready.
I do not feel the weight of a hair.
And now, after a conviction like this, if I should turn to thee,
and again feel the tender bonds which of myself I could not resign,
thou canst not wonder if I long to be dissolved.
I have seen it is in wisdom and mercy that my sufferings have been thus prolonged.
Had I been taken in the forepart of my illness,
I fear there was so much dross to be purged away,
that I should not have been found in acceptance;
but I have been mercifully dealt with every way.
And now, all being removed that hath appeared as obstruction,
I have nothing to cope with but the conflicts of the body.`"

After this, some medicine was given to her; and as she took the cup in her hand,
she was heard to say, "`O Lord, if it be thy will,
grant that this may be the last draught of this kind; but, O Lord,
preserve me in patience.`"
About six, on Second-day morning, the 30th, her sister went to her, and said,
"`I think I have now strength to say, I do freely resign thee.
I humbly hope thy request will be granted, as I verily believe the Lord has heard it;
and that his arm will be round about thee to the end.`"
Elizabeth replied, "`I am thankful to hear thee say so.`"
She continued to the close perfectly clear and sensible, said, in a sweet frame of mind,
something further testifying her love for her sister, and in about half an hour,
without the least apparent emotion, passed quietly away.
