== Appendix

[.heading-continuation-blurb]
Containing Some Account Of Deceased Friends, Of An Earlier Date Than The Preceding.

[.chapter-synopsis]
* Joshua Middleton
* Christiana Penn
* Mary Neale
* Jonas Binns
* Jane Cornock

JOSHUA MIDDLETON.
At the distance of nearly ninety years, I am disposed to commemorate,
with a short narrative, my maternal great grandfather, Joshua Middleton, of Newcastle,
who died there the 27th of the Eleventh month, 1720.
In doing this, and in looking over the few papers relating to this ancient Friend,
which are in my possession,
I am confirmed in the truth of a common remark of pious persons,
"`That the memory of the just is precious.`"
It is encouraging to observe, that the general trials, deliverances, habits,
and sources of hope, are the same at every period of time.

Joshua Middleton was born at Darlington, in the county of Durham, in the year 1647.
His parents were of the Presbyterian profession, strict in their way,
and careful to educate their son in the principles of religion which they professed.
He often acknowledged that their care had been of much service to him,
in keeping him out of the vanities of life; and often, with much tenderness,
would recommend to parents, to nurture their children in the fear of the Lord,
and in the diligent reading of the Scriptures.

In his youth, after some years of communion with the Presbyterians,
he was convinced of the principles held by Friends, and joined their Society.
He underwent with this people divers sufferings and imprisonments,
which he supported with patience.
Not long after he joined the Society,
he believed it his duty to come forth in the work of the ministry,
and in this service he travelled in many parts of England, and in Scotland.
His brethren of the quarterly meeting of Durham, in their testimony, say of him,
that as he increased in years, the greater was his care of the churches;
and that he exhibited a good example to Friends,
by his constant attendance of monthly and quarterly meetings,
though often under much weakness.
His testimony was plain and intelligible.
He was a man of a meek and peaceable spirit, and much beloved among all sorts of people;
and his endeavours to compose differences were very prevalent.
He was also liberal to the poor, and a great promoter of such liberality.

I am not informed at what period of his life he came to reside at Newcastle.
He had first lived at Raby, a village near Staindrop, in Durham.
I have a letter from him to his daughter Hannah, the wife of Joseph Gurney, of Norwich,
(of whom there is an account in the collection of testimonies concerning
public Friends deceased,) written about four months before his death.
It shows the temper of his mind at that time; and,
if the partiality of a descendant do not deceive me, is worth preserving.

Newcastle, 16th Seventh Month, 1720.

Dear Hannah,

I had thine, whereby understanding of your health, am glad:
and though I could like well more often to know of your state, yet,
as I receive information thereof from, with whom we have now a frequent correspondence,
I do not take offence at thy writing seldom:
nor must you expect many letters from my hand, it being now a +++[+++great]
trouble to write.
So as Providence has placed us at such a bodily distance,
we must endeavour to converse in spirit, remembering one another,
and praying for one another, that we may be preserved out of the evils of this world,
and over all the temptations and besetments that we may
be attended with in this time of our pilgrimage therein;
and willing and resigned unto the good pleasure of our God,
when he shall call us out of it.

This is what I am labouring for as on my own behalf:
so would have you use like endeavour, that we may not sorrow immoderately,
or be surprised; but waiting all the days of our appointed time,
till any of our changes come.
So with remembrance of my true love, with my wife`'s, to thee and thy husband,
and your little ones, and to brother Gurney and his family,
and all the rest of relations,
I conclude this with my fervent prayer to the Lord for his blessing on you all:
not forgetting +++____+++and her children.

I say,
as the Lord hath favoured all of you with competent increase in the things of this life,
my desire and prayer is, that your portion may not be in them;
but that you may be blessed with spiritual blessings in heavenly places in Christ Jesus.
Such are the fruits of his blessed Spirit: wherein that you may increase and abound,
is the prayer of thy loving father.

Joshua Middleton.

His last illness seems to have been a painful one; for his son,
in a letter to another of his daughters, settled at Norwich,
dated one week before the departure of their father, thus relates of him:
he had been relieved from his pain and retchings by a removal of the stricture;
"`but,`" says his son, "`he has taken nothing these two or three days,
and grows weaker and weaker; but continues sensible,
and many living expressions drop from him.
I doubt not but God has heard his prayer, and sweetened his bitter cup,
which he said he had to drink.
Soon after he had so said, he broke out into these expressions:
'`Blessed be the name of the Lord!
He has sweetened my cup.
I am refreshed.`' As we were sitting one night about him, he bid us go to bed,
and let him go, and commit him to the Lord; and he should be received to mercy.`"

CHRISTIANA PENN was the wife of William Penn, a grandson of the memorable William Penn,
founder of Pennsylvania.
Her parents were Alexander and Jane Forbes, of London.
Jane Forbes was the youngest daughter of Robert Barclay, the apologist,
and of Christiana his wife, (an account of whose close is to be found in Dying Sayings,
Part Eighth.) Christiana Penn died the 1st of the Ninth month, 1733; but as there is not,
that I know of, any printed account of her,
I am induced to abridge an ancient manuscript, one which may, at least,
be interesting to such as like to trace the descendants
of men who have been eminent for virtue;
and will tend, like the rest of this collection, to promote piety,
by showing its blessed consequences at the close of mortality.

After a longer term of previous suffering than often occurs, her first child, a daughter,^
footnote:[Who died a widow, 1803, named Gaskell.]
was born.
Her husband and friends then began to hope;
but she had a view of her approaching dissolution, and endeavoured to be prepared for it.
She was fervent and frequent in prayer, and earnest with her mother^
footnote:[She was one of Robert Barclay`'s children, of whom John Gratton says:
"`As they grew in years,
they grew also in the knowledge of the blessed Truth;`"
which he much attributes to the care of their mother.]
to join her in it.
She had a firm confidence that it would be well with her,
often declaring that she did not wish to live.
She mentioned with affection her near connections in life; yet said,
that so great was her comfort in the prospect and assurance of future bliss,
she could freely part with them all.

She said the Lord had been so gracious as to forgive her sins,
alluding to the follies of her youth, which she then esteemed to have been vanities,
and therefore she earnestly desired, if it were his will, that she might be removed;
for she was then ready, and certain of eternal happiness;
but she feared that it might not be so well if she should live longer.
"`Hast thou not given me up?`"
said she to her mother.
"`I desire thou wilt give me up freely, and not endeavour to hold me, or interrupt me,
but let me go; I am ready, and have nothing to do but to die.`"
At another time, her father inquired of her whether she would be willing to live,
if it pleased the Lord.
She answered, "`God forbid, but that if he have any service for me, I should be willing;
but if not, I desire to die; for now I am ready, and have nothing to do but to die.
My joy is full.`"

She expressed a tender and affectionate regard for her friends, but most for her husband.
She declared that she had great satisfaction in her marriage,
and that she loved him with all her heart; and that her concern for him,
and desires for his good, were very great and strong.
Her patience in her illness, and her fear of offending her Maker by complaining,
were remarkable: careful of her words, that she might not offend with her tongue.
One time being in great pain, and finding herself thirsty, she said,
"`Now my tongue wants cooling, but soon I shall be in Abraham`'s bosom,
where all my sorrows will be at an end, and I shall rest forever.
I have nothing to do but to die.`"
This was frequently her expression.

She would continue in supplication sometimes for hours together.
The sweet, heavenly disposition she was in the latter part of her time,
even surprised those who visited her.
She was so filled with a sense of the favour and goodness of God,
and with firm faith in her future happiness, that she declared her eternal joy was begun.
She was allowed her understanding perfect to the last.
She often inquired the hour of the day;
was glad when she thought the last was approaching;
firmly and quietly took her final leave; and, without a groan, or the least uneasy sign,
at the age of eighteen years and a quarter, she ceased to breathe.

MARY NEALE was the daughter of Peter and Rachel Peisley, and born at Ballymore,
in the county of Kildare in Ireland, in 1717.
Her education was among Friends: but an indulgence, too little restrained,
in the company of such as have not the cross of Christ in esteem,
led her into deviations in behaviour from the simplicity of her profession;
which at length occasioned a deep remorse.
During several years she thus in some degree gave way to hurtful propensities.

She was not at times without secret reproofs but a fall from a horse,
by which she considered herself to have been in danger of a dislocation of the neck,
and of a sudden death, seems to have been an incitement to permanent reformation.
Not long after, she was much struck in observing the awful, reverent frame of mind,
in which two travelling Friends appeared to sit, waiting upon the Lord;
and a fervent inquiry was raised in her mind after the revelation of the Father,
through the Son.
To this exercise, in her own experience, she was then much a stranger;
but as she persevered, and by the operation of grace in her seeking heart,
she attained the object of her search, and was satisfied.

About her twenty-seventh year, she came forth in the work of the ministry,
and about the same time she fell into some outward trials and distresses;
and she became either a teacher, or otherwise a servant, in the family of a Friend,
of whose daughter she had the care.
After a while she quitted this employ,
in order to be more at liberty to fulfill her duty as a minister;
and she visited in that service, in company with another Friend,
the meetings of Friends in Ireland in a very general manner.

In 1748, she entered on a similar visit to Friends in England,
in which she employed more than two years.
In 1751, she accompanied Catherine Payton, of Dudley, Worcestershire,
then on a religious visit in Ireland, in a visit to Friends in Munster and Ulster.
In this journey, probably, was laid the foundation of that close religious fellowship,
which rendered them sympathizing companions in further and more extensive services.
In such service they engaged in the year 1753,
and were nearly three years employed in visiting Friends on the continent of North America,
returning in the summer of 1756.

It is not within the plan of this compilation to
give even cursory accounts of such journeys;
but an extract from a letter which she wrote from Bradford, in Yorkshire,
in the first year of her travels in England,
is particularly thought worthy of preservation.
She seems, previously,
to have been tried by means of much deprivation of that heavenly comfort and support,
which she loved and sought.

"`As I quietly rode along,`" says she,
"`the Lord was pleased in mercy to break in upon
my mind by his living presence and power,
and it became the language of my soul, Speak, Lord, and thy servant will hear.
After which, many things were divinely opened to me; wherein I greatly rejoiced,
and was thankful to the Lord my God.
I then found a sudden but gentle rebuke; and heard, as it were, a voice that said,
in the secret of my soul,
The dispensations thou most delightest in are least pleasing to me;
and not so beneficial to thy soul as that pure poverty of spirit,
brokenness and contrition of heart, which brings into humility of mind.
And the reason why this is so little desired, and so unpleasant to the creature is,
that it can have no part therein; but is wholly excluded and set at naught;
can discover no beauty or excellency in it.
And for this cause it is that I will in no wise despise
the offering of a broken and contrite spirit,
as it is most pure, and without any mixture of the creature.

For whether there be prophecies, divine openings or revelation, consolations,
joying or rejoicing in the Holy Ghost, gifts of healing, or tongue of utterance;
in all these self can rejoice, and have a share, being obvious to it,
and bringing it honour.
Then, said I, '`Lord dispense to me what is most pleasing to thee, and best for my soul,
so long as my weak faith and patience can endure; and when I am ready to faint,
give me a little of the wine well refined on the lees, that my soul may rejoice in thee,
the God of my salvation.`'`"

On the 17th of the Third month, 1757, she was married to Samuel Neale,
a valuable minister then residing within the compass of Edenderry monthly meeting;
and in the evening of that day, in an opportunity of religious retirement,
her mind was impressed with a sense of the holy sabbath of rest.
She remarked, that when the Almighty had finished his six days`' work in the creation,
he appointed a sabbath and sanctified it; she observed that, in the time of the law,
the people were forbidden to do any manner of work on the sabbath day;
and she said that there were some present who should, in a short time,
cease from their labours, and enjoy a sabbath in which they should have no work to do.

The next two days were passed in receiving visits from her friends,
and in sweet fellowship with her newly-acquired partner;
but very early in the morning of the 20th, she was seized with a disease which was,
probably, an inflammation of the bowels; and about three in the afternoon she expired.
During this short illness, she sometimes raised her voice in a melodious manner,
though she did not always express herself in words.
She longed to be dissolved, and entreated the Lord to give her a release; and when,
about half an hour before her decease, her pain ceased, she then said,
"`I praise thy name, O my God, for this favour.`"

JONAS BINNS, a boy in his fifteenth year, son of Jonathan Binns, of Crawshawbooth,
in Lancashire, departed this life the 23rd of the Ninth month, 1760.
His surviving father gave a testimony concerning him, which I nearly copy.

He had great delight in reading the Holy Scriptures when very young.
He said he preferred learning before money.
He was often alone when others were at their play.
He read much, and was often much affected, being observed, sometimes,
to make a stop in his reading, and plentifully scatter his tears.
And not only in reading, but when solidly set in meetings, tears did run down his face:
which was affecting to the well-minded,
and evidenced that he met with something worth waiting for; which,
when but nine or ten years of age, he confessed.

He was then very desirous to go to meetings, and being asked the reason,
he was very still for a time, and then broke out into tears,
and signified that he met with something in them, which sweetened his mind.
He was steady in his conduct, and careful in his words,
and often reproved others who were not so.
He was remarkably patient under disappointments, and content with such things as he had.
He was dutiful to his parents, and his behaviour and conversation were truly edifying.

In the thirteenth year of his age he fell into a decline;
and in the last six months of his life he was under great bodily affliction,
which he bore with great patience and fortitude.
He was never heard in the least to repine, but seemed wholly given up to the Divine will.
Thus far his father.
A few of his expressions are preserved, confirming this paternal testimony.
Lying in a weak state, he said, "`The Lord hath been very gracious to me all along,
and followed me with the extendings of his love.
Praised be his name.`"
To his brother and other relations present he said, "`Grieve not for me.
It will, I believe, be well with me.`"
He desired those present to take care of their company and their behaviour, adding,
"`The Lord hath been good to me, and I think I would rather go than stay in this world,
where there are troubles enough for every day.
You have done all you could.
Don`'t sorrow for me.
I am going to eternity --a blessed eternity, where we shall meet again,
if we live as we ought.`"

JANE CORNOCK, daughter of Thomas Cornock, of Haverford-west, in Pembrokeshire,
and of my paternal aunt Elizabeth, daughter of Silvanus Bevan, of Swansea,
was removed from time on the 17th of the Eleventh month, 1768,
by means of a rapid consumption, at the house of Elizabeth Bevan, of Swansea,
widow of Paul Bevan, her mother`'s brother.

I saw her in London, in the spring of the same year, lively and gay;
though not extravagant, according to the usual acceptation of that word.
In South Wales, the country of her birth and residence,
there was not among the youth in general,
of her own rank in life (though that was by no means high) much, if any,
suitable acquaintance;
and she too freely indulged herself in the company of those
who were much strangers to the restraints of Truth;
and therefore more likely to encourage than to check
the propensity to gaiety which she felt.
She was smart in her dress; deviated from the simple mode of speech used by Friends,
and was admired for singing.
Yet I believe she loved upright Friends,
and she had long been particularly attached to that valuable
relation at whose house she breathed her last,
and who, I believe, saw her expire.
This Elizabeth Bevan was a minister;
and I have heard Jane speak of her in that capacity with evident marks of approbation,
mentioning the weight of spirit which she used to perceive over her aunt,
previous to the appearances of the latter in this service The last time I saw her,
as before hinted, was about six months before her death.

She was then what is called the life of the youthful
parties who attended her aunt in excursions,
common in the vicinity of London;
but I have reason to believe that even then the world had begun to fade in her view.
But I was then a boy, in my sixteenth year;
I partook of the enjoyment which her company afforded;
and though now I can sometimes rejoice in the reflection that many
of those connected with me by consanguinity have been reached,
when wandering, by the crook of the heavenly Shepherd, and can wish, if not pray,
for the collection of many more of them into the fold of safety, yea, of salvation,
I was certainly then neither a religious character, nor a judge of it: though then,
I believe, like her, a lover of good men.

At length, says another relation,
it was the merciful favour of her gracious Redeemer to give her a sight of her errors,
and a true penitent heart for every folly;
also to enable her to hold forth a powerful exhortation to her intimate
acquaintance to shun the pleasing snares and vanities of life.
Being thus redeemed, she had no desire for recovery.
She dropt, before her close, many comfortable expressions; saying,
that though the Lord was pleased to afflict her body, her mind was not afflicted;
that she had sweet assurance, and that at times she seemed already in heaven.

END OF THE TENTH PART.
