== Chapter 1

[.chapter-synopsis]
* William Briggins
* Elizabeth Markes
* Barbara Bevan
* William Kirton
* Mariabella Farmborough
* Joshua Holme
* Thomas Wilson
* Edward Wilson
* Margaret Lancaster
* George Knipe
* Matthew Dickenson
* Jeremiah Waring
* Thomas Everden

WILLIAM BRIGGINS, of London, was convinced of the blessed truth about the year 1671,
the manner whereof was as followeth: He frequented the Presbyterian meetings before,
and the informers and officers came to the meeting where he was.
Their preacher slipped away by a private door; and he, as well as other hearers,
made the best of his way to escape.

Then it came in his mind to go and see how it fared with the Quakers.
So he went to their meeting in Gracechurchstreet,
and got as much out of sight as he could, for fear of being seen.
There William Bayley was declaring, and after a little time came a mob and informers,
with a band of soldiers.
These rushed into the meeting, and he expected the preacher to slip away,
as the other had done; but to his great surprise, he went on preaching,
till they hauled him away into the yard, and had him to their guard.

After they had carried him away, another Friend stood up and preached;
and they returning, took him away also.

At this time it opened in his mind, that it was the truth they declared,
and that they knew it was worth suffering for.
Between that time and the year 1685, he met with great sufferings and loss of goods,
for peaceably frequenting meetings to worship the Lord; and was twice a prisoner,
in the Counter and in Newgate, many months at a time;
and by reason of his strait confinement in prisons, he was much impaired in his health,
grew weakly and sickened.

Although his pains were great, yet, as he said, his eye was to the Lord;
and often declared that the Lord had been good to him from his youth to that day;
and praised him, that he was pleased to reveal the knowledge of his Son,
our Lord and Saviour, unto him; and that, through the assistance thereof,
he was directed to do unto all mankind as he would have others do unto him.

He advised all, that they be faithful to the Lord;
and though they had received but little, yet, in the good improvement thereof,
he would give them more talents.
And above all things,
he cautioned to keep above and out of the encumbrances of this world;
and that we assist the poor and needy, and administer of our abundance in this world,
to help them in their necessity;
and in whatsoever condition the Lord is pleased to suffer to come on us,
we ought to be content; as he said, he had been an experiencer of,
both in and out of prison, in sickness and in health.
He witnessed that saying of the prophet Isaiah, c. xxvi., ver. 3, 4, fulfilled,
"`Thou wilt keep him in perfect peace, whose mind is stayed on thee,
because he trusteth in thee.
Trust ye in the Lord forever: for in the Lord Jehovah is everlasting strength.`"
And that if at any time we should be in distress, either inward or outward,
if our dependence and eye were to the Lord,
and with an upright heart we patiently waited on him,
he in his own due time will work deliverance, as he said, I have experienced many a time.

This it was that rejoiced his heart,
and made him both willing and ready to suffer whatever the Lord saw meet for him.
Though weakness of body increased,
he felt the spirit of the Lord to lift up his standard, to which he retired,
and was strengthened in his inward man.
A little before he departed, he sounded forth a pleasant harmony,
which made all in the room admire.
After some time he said,
"`Lift me up;`" and then he uttered many heavenly expressions
concerning his assurance of rest and peace with the Lord;
for he said, in this last agony death had been hard, and done his worst,
and that he then felt the living power of the Lord, which was above death,
and praised the Lord he had gotten the victory, saying,
"`It is recorded in the Scripture, some men`'s sins go beforehand to judgment,
and some follow after; but, through the great mercy of God,
I have witnessed mine to go before, and have nothing to do but to die.`"

He advised all to keep to meetings, and watch over their words and actions,
and have their dependence and reliance on God,
and they should find him a present help in the time of need.
Then he called all in the room by their names,
and desired that the Lord might direct them, and keep them all in faithfulness to him;
and that they might experience that Scripture fulfilled, "`It is shown unto thee, O man,
what is good, and what the Lord requireth of thee, to do justly, love mercy,
and walk humbly with the Lord thy God; and to visit the fatherless in their afflictions,
and to keep unspotted from the world.`"

He was kept in his senses to the very last, and after he had spoken much, he was faint,
and called for something to take; and bidding all present farewell,
he laid down his head on his pillow,
and in about an hour after departed this life in much stillness,
the 27th of the Fifth month, 1688, in the sixtieth year of his age.

[.asterism]
'''

ELIZABETH MARKES, wife of William Markes, of North Crowley, in Buckinghamshire,
was taken ill with a fever about the 11th of the Seventh month, 1703, with great pain,
which she bore with much patience,
which was a virtue she was endued with from her childhood.
In the time of her health she often desired,
that the Lord would be pleased to give her a little time of retirement before her death.
She took notice in her weakness of her petition being granted,
and gave praises to the Lord for his gentle visitations and fatherly care over her.

One of her servants standing by, who was helpful to her in her weakness,
she took her by the hand, and in great zeal said unto her, "`Ah,
poor lass! in thy health and strength remember this day;`" meaning the day of her death.
She also desired her burial should be plain, and no superfluity on her coffin.
She would have her family called into her chamber several times during her weakness,
and prayed very fervently.

A few days before her departure, being very weak in body,
she desired to be set up in her bed, and the Lord opened her mouth in praises to himself,
saying, "`God is good to Israel, and to all that are of an upright heart.
Oh! praises, praises, everlasting praises, and hallelujah be given to Israel`'s God,
for he is worthy of praises.
Oh, Lord!
I pray, if it be thy blessed will, preserve my tender offspring,
that they may be a succeeding generation to serve thee and thy blessed truth.
And if it be thy blessed will to raise me from this sick bed, I shall be content:
but not my will, but thy holy will be done: I freely submit unto thee.`"
She often lifted up her dying hands with inward hymns of praises,
when her strength failed to utter words: so laid down her head in peace with the Lord,
the 29th of the Seventh month, 1703.

[.asterism]
'''

BARBARA BEVAN, daughter of John Bevan, of Trevrygg, in Wales, was an honest, sober,
virtuous young woman, zealous for the holy name and truth of God,
and greatly desired and travailed for the exaltation and spreading thereof,
labouring that all might come to love and live therein,
and order their lives and conversations by it,
which she came to know and experience in her own heart, by the divine power of God.
Though she was before soberly educated by her parents,
and when she was but six years of age, diligently kept to Friends`' meetings,
and was dutiful to her parents, loving to her relations and neighbours,
and for her orderly behaviour in meetings,
well beloved by the faithful who were acquainted with her; yet as she grew up,
the enemy laboured very often to draw her mind to delight in vain objects,
and at times prevailed, to her great grief and exercise of mind.

But it pleased the Lord to visit her with sickness of body,
when about sixteen years of age, and to show her state and condition to her,
and let her see, as she afterwards declared, that the form of truth,
and the profession of it only, would not satisfy without possession;
and that she had great need of a Saviour;
and that the pleasures and delights here below were but as dross
and dung in comparison to God`'s salvation and life-giving presence;
and that there was but one way to obtain it, and that is, as she said,
by giving up in obedience to the Lord, that he might work and operate in her heart,
who had many times begat desires and breathings in her soul after him.

She came to receive a dispensation of the gospel about the sixteenth year of her age,
and travelled in the work of the ministry,
and was concerned to visit Friends in West Jersey, and some parts of East Jersey,
and her service she zealously performed, being concerned for the honour of God,
and her labour was acceptable, and well received.
She afterward returned with her father into Wales; and though she was weak in body,
in the year 1704 she travelled in North and South Wales, about six hundred miles,
and her service and labour of love were well received, and effectual to many.

She was sound in doctrine, and the savour of life attended her declaration,
and she was a good pattern and example in her conversation
amongst those she conversed with;
and at monthly meetings she exhorted Friends to be
faithful in their testimony against tithes,
and to keep clear of the world`'s spirit, and the fashions thereof.
After she sickened, she had some meetings in the family where she was,
and earnestly exhorted to beware of an easy state and lukewarm condition;
and admonished to wait often upon the Lord,
that they might get something in store against a trying time.

She was sensible her time here was not to be long, and declared she was not afraid to die.
Seeing some of her relations weep, she said, "`Why weep ye on such an occasion?`"
The day before she departed, she spoke in like manner to her father, mother,
and relations then about her, "`I love you all, and have a love to the family.`"
She had an easy passage, and departed this life the Seventh day, in the evening,
being the 26th of the Eleventh month, 1705; and on the 28th of the same month,
her body was accompanied by relations, friends, and neighbours,
to the meetinghouse at Trevrygg, where there was a good meeting,
to the satisfaction and comfort of many then gathered, and after, meeting she was buried.
Aged about twenty-three years; a minister about seven.

[.asterism]
'''

WILLIAM KIRTON, son of Richard and Sarah Kirton, of West Town,
in the parish of Kensington, near London, Middlesex, aged about twenty-two years,
was carefully educated by his parents in the Christian religion,
and holy profession thereof.
He was from a child dutiful to his parents, and tenderly affectionate to them,
and to his brothers and sisters.
Being well-inclined when he went to school,
he gave his brothers and school-fellows good advice, and was exemplary in his solid,
sedate, and wise deportment, which was also tempered with much sweetness,
that he was well-beloved, both at school and in the family at home;
and as he grew in years, he grew in grace.

He was afflicted before his sickness with much pain,
which he bore with abundance of patience; and in his sickness he would often say,
"`It is a hard, rough way that I tread; the Lord support me, and keep me,
that I may not tread, or step aside, but be preserved to the end;`" and often said,
"`Oh! when shall I go to rest, on the other side, or beyond all pains and troubles?
but, Lord, let it be thy time, and be pleased to give me patience.`"
Afterwards he said, "`I am bound for heaven; I am for eternity.`"

Again, his brothers and sisters standing by, he said to them, "`I beg of you,
be dutiful to our dear parents; you cannot do too much for them.
If I were to live.
I should think it my duty to serve them.
And to thee, brother Benjamin, thy standing is on slippery places;
have a care and live well, that thou mayest die well, and come to me.`"
He said often to his brother and sister, "`Live every day as if it were your last day.`"
On the day he died, he said to his mother, and aunt Damaris Kirton, "`Sit close to me,
and I will keep close to the Lord.
Methinks I see the Lord coming to call me this day, or to send the angel of his presence;
and I am ready to meet him.`"
Afterwards he said, "`How gloriously the outward sun doth shine;
so doth the sun of righteousness shine upon my soul this day.`"

A while after he asked if it rained, and it was told him it did; then after a pause,
he said, "`It is a mollifying day;
the Lord mollify and tender all our hearts and spirits.`"
Then, after a time of stillness, he said to his aunt Damaris, aforenamed,
"`I have something to say,
but my breath is very short;`" and desired of the
Lord to give him breath that he might speak,
and in a little time he was answered,
and the Lord opened his mouth in a wonderful manner to those that were about him.
He particularly directed himself to the youth,
and expressed a great concern that the young generation that were coming up,
might remember their Creator in the days of their youth, etc., which,
with the living presence of the Lord that was then felt,
so tendered the hearts of all present, that there was scarcely a dry eye;
but his excellent exhortation was not taken verbatim, so is here omitted.

He concluded with a fervent prayer to the Lord,
and fell asleep in the Lord the 3rd of the Ninth month, 1706,
and his corpse was buried in Friends`' burying-ground, in Hammersmith, in Middlesex,
the 7th of the same.
As he was well beloved and esteemed, he was accompanied by many friends and neighbours,
he having said, "`I do not care how much company is at my burial;
for I believe the Lord will meet with them.`"
And so the Lord was pleased to appear in that solemnity,
blessed be his holy name forever.
"`Precious in the sight of the Lord is the death of his saints.`"
Ps. 116:15.

[.asterism]
'''

MARIABELLA FARMBOROUGH, wife of Thomas Farmborough,
was convinced of the blessed truth about the year 1670, at a meeting of Friends,
when they met in the streets, being kept out of their meetinghouses; though,
for many years before, she was for hearing such as she believed,
preached and declared through their own experience
of what the Lord had done for them and in them.
After her convincement she received a testimony,
for the sake whereof she suffered divers imprisonments in Newgate,
the Counter and Bridewell, in London; and also in Newgate and Bridewell,
in the city of Bristol.

She was a tender, serviceable woman, and was instrumental in the hand of the Lord,
by the testimony he gave her to bear for his name and truth,
to turn people from darkness to light.
She was remarkable for going early to meetings, and used to say,
"`She loved to be one of the two or three at early meetings.`"
Though in her old age she was afflicted with lameness and weakness of body,
yet she was loath to miss meetings, though she could not go without help;
and when she came from thence would say,
she found herself much better than when she went.

She lived an innocent life, and was very serviceable with our dear friend Mary Elson,
and other ancient Friends, in visiting Friends, in encouraging them to their duty,
in going to meetings for worship,
and also to those appointed for taking care of our poor and distressed.
A little time before her departure she said her day`'s work was done,
and that she could say she had not overdone,
neither left undone what God required of her, according to the best of her knowledge.
She quietly departed this life, the 3rd of the First month, 1708,
in the eighty-third year of her age.

[.asterism]
'''

JOSHUA HOLME, son of Thomas Holme, and Jennet his wife, of Flookburgh, in Cartmel,
Lancashire, was born in the year 1684, and educated in the true Christian religion,
and way of truth professed by the people called Quakers.
In his childhood and tender years,
he came to have some experience of the work of the Lord in his soul;
and as he humbly waited upon God in his holy fear,
and was exercised in frequent prayer to him in his spirit,
he increased in Christian experience.
And being faithful to the discoveries of the holy spirit,
he was made more and more a partaker of his great love and goodness.

In the Third month, 1709, he was taken with a fever,
which for two weeks was pretty moderate, but afterwards grew more sharp; and,
as his bodily affliction increased, such was the assistance of the spirit of God,
that he grew more and more a partaker of its comforts.
Influenced by this heavenly life, he uttered many savoury expressions,
to the satisfaction, and greatly tendering of the hearts of those present,
though several of them were not of the same profession.
"`I have had many hard nights,`" said he, "`but I have been comforted,
for God hath appeared to me above whatever I could
think,`" with more words to this effect;
for which he returned praises to the Lord.

The evening following, he supplicated the Lord, saying, "`O Saviour of souls!
O Saviour of souls! have pity on my soul; for terrible, terrible, O Lord God,
art thou to the wicked;`" and continued supplicating the Lord for a considerable time.
When his doctor told him there was hope of life, but he might prepare for death,
he replied, "`I have done that long since.`"
Some of his friends coming to visit him, he said to them,
"`When I was working with the apprentices and workmen in the shop,
I was often under great exercise of mind,
which occasioned me many times to walk into the garden and fields in the evening-tide,
and there to pour forth my supplications to the Lord;
and at such times I had a sense of the goodness of the Lord, which did strengthen me,
and help me over the temptations of the enemy.
I have kept also to my exercise in meetings, which is now my comfort;
but what will become of those who do not keep to their exercise in meetings?`"
When he had given this relation, he said to them,
"`If this be the last opportunity I should have with you,
I am well satisfied;`" and so concluded in thankful acknowledgments to the Lord.

Another time his mother said to him, "`I am afraid thou wilt die,
and we are sorry to part with thee.`"
He replied, "`Very likely; so am I with you: but if it please God it must be so,
do not murmur, for we must all be separated.`"
Another time, he said, "`What will become of those who go to meetings,
and neglect their duty in waiting upon God in the meeting-time,
for many of our young people do not walk according to truth.
Ah! it is heart-work that God accepts of: praises to God forever.`"
Adding, "`I think I may not live long; but I have taken heed to my ways,
which is my comfort now.
I am sealed, I am sealed to the day of redemption; I am satisfied of it.`"

After some time returning praises to God, he said, "`O Lord God,
thou hast been bountiful to my soul;`" he went on, "`I have been low, tender, and humble,
and that is my comfort now;
for I have that in my heart which doth burn against sin and wickedness.`"
The day before he died, he spoke many excellent things for about an hour,
which were not noted, except this saying, "`Be prepared,
be prepared for your latter end;`" which had a sensible effect upon the persons present,
as being serious advice from the mouth of a dying man,
who had witnessed the greatest satisfaction of a sick-bed, of being ready for his change,
and assured of an eternal state of glory;
without which assurance all must needs be in a dreadful apprehension of
everlasting misery in their last and most important moments here.
He died the 27th of the Third month, 1709, and was buried the 29th of the same,
at the Height, in Cartmel; aged twenty-five years.

[.asterism]
'''

THOMAS WILSON, late of Kendal, son of John and Elizabeth Wilson, of Coldbeck,
in Cumberland, was born in the year 1670,
and educated by his parents in the way of truth.
About the year 1701, the Lord called him to the work of the ministry,
and raised him up in a public testimony,
which he faithfully bore by the ability given him of God,
being truly concerned for Zion`'s welfare,
that all who were convinced of the blessed truth might grow in the enjoyment of it;
that by the power thereof they might be enabled to stand in a trying day.

He travelled very much in the service of truth, visiting Friends in many parts.
In the year 1702, he went in the work of the ministry into Northumberland and Scotland.
In 1703, he laboured in the same work in Westmoreland, Yorkshire, Lancashire,
and Cheshire.
In 1704, he removed out of Cumberland to Kendal, in Westmoreland.
In 1705 he went into Ireland, to preach the word of life and gospel of peace,
and in the south and west parts of England, travelling about eleven months.
In 1706, he visited Friends in their meetings in Cumberland, Scotland, Northumberland,
Durham, and some parts of Yorkshire.
In 1707 he laboured in that service amongst Friends in Lancashire, Cheshire,
Worcestershire, Gloucestershire, Bristol, London, and several other parts of this nation.
In 1708 he travelled again into Lancashire, Cheshire, Wales, Herefordshire,
Gloucestershire, Bristol, Somersetshire, Devonshire, and Cornwall,
returning through Dorsetshire and Hampshire to London, and then homewards.
In about a month`'s time after he got home, he began to be out of health,
being about the 1st of the Fourth month, 1709.

He bore his sickness with much patience, and desired to be quiet and inwardly retired,
being wholly resigned up to the Lord, either to live or die;
and was also very thankful to God,
for his heavenly visitation in the time of bodily weakness, expressing himself thus:
"`O Lord, in thy great love and mercy,
thou hast given me victory over the enemy`'s power,
and by thy powerful hand bearest up my spirit, and makest my soul triumph over hell,
death, and the grave.`"

Several Friends coming to visit him, he said,
"`Peace with the Lord in a dying hour is better than all this world.
It is gladness to me to think I must die,
being fully satisfied it will be abundantly more gain to me to die than to live.`"
He lamented the condition of those who spend their time negligently,
and in forgetfulness of God, saying, "`A woeful portion they will meet with at one day.`"
Therefore he fervently exhorted to more diligence, warning them to prize time,
and be more careful for time to come; and his,
expressions being seasoned with the grace of God,
they overcame and melted several Friends into tenderness,
and they were greatly comforted and refreshed by his words.

The day before his departure, he said, "`I desire that Friends may grow in the truth.
Oh! the heavenly life in the truth is glorious,
to feel it spring and run amongst God`'s people.
I now remember Scotland, Ireland, and England.
Oh! the precious times I have had in these three nations!
How the life and power of God`'s word hath filled
me amongst the assemblies of the people of God!`"
Then he prayed to the Lord,
that he would preserve all his servants in the spring of life, and said to those present,
"`Keep down to the root of life in yourselves,
for I feel at this time consolation in the power of God.`"

Being sensible his time here was short,
he desired to see several friends who lived near before he died,
and at his request they were sent for;
to whom he declared how desirous he was to see them,
and told them he sent for them to take his last leave of them before he died.
He spoke severally to many of their states and conditions,
and often advised Friends to keep their minds out of the world, many times saying,
"`This world, this world, hinders the growth of the seed of God in the hearts of many.`"
He earnestly desired to have his dear love remembered to Friends,
saying his dear love in Jesus Christ was to all the faithful.

He was very much filled with the sense of the Lord`'s goodness,
and his spirit was raised above his bodily weakness; and in this heavenly frame of mind,
he fervently prayed for the preservation and prosperity of the Church of Christ in general,
and particularly for the meeting he then belonged to.
After some time spent in prayer and praises to the Lord,
having delivered most of what was in his mind by way of advice to Friends,
to be faithful and watchful, he said, what he had to say he had said, save one thing,
and that was as followeth: "`I believe a trying day will come,
that will try the foundations of people;
and I exhort you to get down to truth in yourselves, where you may be able to stand;
for in the day of trial none will be able to stand,
save those that have their rooting in the truth, for that it would be short and sharp.`"

He then prayed that Friends might be able to stand in that day, saying,
"`God will be with all them that fear him.
As for me, I am ready, and wait to be dissolved,
that I may be with Christ forever;`" and closed his solid
and prophetical expressions with this serious admonition,
"`Friends, I desire you to remember what I have said, and mind them,
as they are the words of a dying man;`" concluding with, "`Now, friends,
you may take your time.`"
Then turning himself from them, he said, "`Now, Lord, I will wait for my change,
be it longer or shorter;`" and lay still and quiet
the remainder of that night and the next day,
till about two or three hours before his departure,
which was the 15th of the Fourth month, 1709, in peace, and finished his course with joy,
being sensible of the love of God to his soul,
and having assurance of that eternal inheritance which will never fade away.

He was buried the 17th of the Fourth month, 1709, in Friends`' burial-ground in Kendal.
Aged about thirty-nine years.
A minister about eight years.

[.asterism]
'''

EDWARD WILSON, belonging to Grayrigg meeting,
was convinced of the blessed truth in early days, about the year 1655,
and some few years after appeared in a public testimony among Friends,
though not in many words, yet in much innocency and brokenness of heart.
He was a man of a meek and quiet spirit, and of good esteem amongst Friends,
as also among his neighbours.
He was very serviceable in entertaining Friends with a free and open heart.

In the Sixth month, 1709, it pleased the Lord to visit him with sickness of body,
by which he was taken off.
On his deathbed he often expressed the peace and satisfaction he met with from the Lord,
as also his willingness to leave this world: and so died in peace with the Lord,
and in assurance of eternal life, the 5th of the Seventh month, 1709,
and was buried in Friends`' burying-ground, in Lambrig, the 7th of the same,
being about sixty-eight years of age.

[.asterism]
'''

MARGARET LANCASTER, the wife of John Lancaster, of Thorncroft, near Great Strickland,
in Westmoreland, was born in the year 1658,
and was convinced of the blessed truth about the year 1697;
and in the year 1701 she appeared in a public testimony amongst Friends.
In the Eighth month, 1708, it pleased the Lord to visit her with sickness,
of which she did not recover.
Although her pain and exercise of body was for a long time very great,
yet she was enabled to endure it with much patience,
and was preserved very sensible to the last.
She often desired of the Lord and prayed to him,
that he would enable her to bear with patience what he had pleased to lay upon her.

Towards the latter end of her illness,
she often expressed how glad she was that the conclusion
of her time in this world was so near,
because she had a full assurance of peace and rest in the
kingdom of glory with the Lord her Saviour and Redeemer,
when time to her in this world should be no more.
She called her husband and family, to take her leave of them; and,
being filled with divine life, she gave good advice to them all;
in a sweet and tender frame of spirit,
and told those present the great gain it would be to love and fear God above all.
Then she said, "`Now I expect to be dissolved, and see you no more.`"
So this handmaid of the Lord sweetly finished her days, the 14th of the Seventh month,
1709, and was buried the 16th of the same, in Friends`' burying-ground at Newby-head.
Aged about fifty-one, and a minister eight years.

[.asterism]
'''

GEORGE KNIPE, of the parish of Hawkshead, in the county of Lancaster,
was born in the year 1653.
He was brought up by his parents in the religion of the church of England,
and in his youth much inclined to vanity; but about the year 1675,
being the twenty-second year of his age, the Lord was pleased,
by the true light which lighteth every man that cometh into the world,
to show him the vanity of his ways, and his then deplorable state and condition;
and brought him not only to a godly sorrow for his sins and vanity,
for which he had often felt reproof, but to an unfeigned repentance.

He now gave up in obedience to the requirings of God`'s holy spirit in his heart,
and became a diligent frequenter of the meetings of the Lord`'s people called Quakers,
and was made partaker of the like precious faith that was delivered to the saints.
The Lord having revealed to him the way of life, he made public profession thereof,
and walked therein;
so that the great change that was wrought in him was very
evident and conspicuous to all who knew him.
For, as before he was in the practice of singing idle songs,
and his discourses were vain, now he was sober, serious and religious,
and very circumspect and godly in his conversation.
So efficacious was the power of the blessed truth which he received, believed in,
and obeyed.

Continuing faithful to the Lord, he was pleased, in the year 1685,
about ten years after he was convinced, to call and put him into the ministry;
to which call he was obedient, and became a diligent,
zealous and faithful labourer in the gospel of peace he travelled much,
willingly to preach the same for the good of souls;
and was made very serviceable in many parts, as England, Scotland, and Ireland,
and the whole time of his life, after he was called into the work of the ministry,
he mostly spent in travelling to publish the glad tidings of the gospel of salvation,
and to preach Christ, whom the Lord hath given for a witness and covenant of the people,
for a light of the Gentiles.

He devoted himself to serve the Lord, whom he truly loved and feared.
He had unfeigned love to his brethren, and good will to all men,
whose salvation he earnestly desired.
He was of a sympathizing spirit with those under exercise and affliction,
and laboured for love and unity.
He was a man of peace, yet zealous for the truth,
and the preservation of the testimony thereof in its simplicity.
And although he was very little of a scholar, yet well understood the Holy Scriptures,
both in the letter and mystery, and his ministry was plain, and doctrine sound,
and his preaching reaching, edifying and lively; the Lord being with him,
and his presence and power attending him, made his doctrine very prevalent,
tending much to promote piety and virtue, he loving and living a godly and virtuous life,
agreeable to what he taught.

In his travels he went to the house of R. Robinson, the 27th of the Seventh month, 1709,
and being sorely afflicted with sickness, he could not travel,
but was preserved in a living sense of the love of God, and often praised the Lord,
and gave good exhortations to the family.
Those that came to visit him were greatly comforted, and he declared in their company,
and often expressed, he was freely resigned and content in the will of God;
and that he was well satisfied he had spent so much of his time in the Lord`'s service.
In a sweet frame and temper of spirit he continued till the 4th of the Eighth month,
1709, being the fifty-sixth year of his age, and then departed in peace with God,
after he had laboured in the ministry twenty-four years.

At his funeral, many being met to perform the last office of love,
to see his body interred, the Lord was pleased eminently to appear,
and crown that assembly with his divine presence; and though he be removed from us,
which is the church`'s great loss, yet we are satisfied his gain is much greater,
being entered into the kingdom that never shall have end.

[.asterism]
'''

MATTHEW DICKENSON, of Cumberland, was born in the year 1627,
and was convinced by the spirit of truth,
and received it in the love thereof in the year 1653.
One of the first who received truth in that county was this worthy and ancient Friend,
who was faithful to the requirings of the Lord;
and the Lord fitted him to bear testimony to his holy name and truth,
soon after his convincement,
and caused him to call and warn both priests and people to turn
to the light of the Lord Jesus that shone in their hearts,
and to repent of their wickedness, and to believe in Christ, and to obey him.

He was much concerned to go to the public places of worship
to preach the gospel of Christ in love to people`'s souls,
being greatly desirous that they might receive it as he had done.
But he met with deep sufferings by beatings, abusing and imprisonment;
yet he persevered in true faith, sincere love, great zeal, and godly courage;
so that there were but few public places in all the
county but what he visited and laboured among them.
He travelled but little to visit Friends abroad,
but frequently attended meetings at home,
and was very instrumental in settling a meeting called Westside,
though he belonged to Pardsay meeting, in Cumberland.

He was an innocent man, and of a blameless conversation among all sorts of people,
and steadfastly walked so in the churches of Christ.
He retained his integrity to the end, and a little before his death, said,
"`I feel the Lord`'s love and power over all, and am satisfied all will be well.`"
He died the 23rd of the Ninth month, 1709.
Aged about eighty-two; a minister nearly fifty-six years.

[.asterism]
'''

JEREMIAH WARING, son of Jeremiah and Mary Waring, of Witney, in the county of Oxford,
born the 21st of the First month, 1688,
was a youth endued with divine and natural capacity; both which excellencies in him,
through divine goodness, and parental education, seemed to overgrow his tender years.
About the fourth or fifth year of his age, a Friend being at his father`'s house,
who was concerned in supplication to the Lord,
perceived him reached with an immediate touch of divine love;
which thing the Friend observed to his parents.

As he grew in years, he grew more obedient thereto,
and became in a good degree leavened into the nature of it;
so that he seemed worthy to be called a wise son, by whom is made a glad father.
He not only prospered in things divine,
but was also of great service to his parents in their business,
which he managed with care and dexterity.
And though he was but a youth,
he admitted those things in his mind no farther than their proper limits;
but always had a veneration and regard for truth,
that he might be ready to defend and maintain the same,
whensoever it might be required of him;
for which service the Lord was pleased to administer to him suitable qualifications.

And for a proof of his verity, the meeting to which he belonged,
being one First-day gathered to worship God in spirit and truth,
and there being none concerned verbally,
Friends were attacked by an old adversary of truth,
who came in and made disturbance by way of inquiry,
which this young man so suitably answered, that he went off;
but returned thither again in the afternoon, and brought with him many people,
and endeavoured to insinuate into them that we denied the death of Christ;
to corroborate which, he read part of a sentence out of a book written by a Friend.
But this youth opposed him, and made it obvious that his assertion was false,
and that he had perverted the author`'s words; which gained so much upon the auditory,
that they went off with satisfaction, and this disturber with shame.
And as he was zealously concerned for maintaining and defending
truth`'s principles against open and professed enemies,
so he was for putting in practice the wholesome order of our disciplined church,
that truth might be preserved from all intestine foes;
and in meetings appointed for that purpose he was very serviceable.

He was given much to reading and retirement, and having read many authors,
both ancient and modern,
he traced almost every custom and ceremony made use of by those called Christians,
to their very source from whence they were taken,
and how long they had been in the performance of them.
These he collected into a book, and placed each particular in its proper class,
and also many wise and notable sayings of judicious men,
concerning the spirituality of the true Christian religion;
between which he had left proper spaces,
designing as we suppose to fill it up with the product of his own fruitful genius;
and had he lived to complete the work, he,
would doubtless have given the world a sufficient proof of his excellent qualifications.
A very worthy Friend who is since deceased, Thomas Ellwood, desired to view his writings,
which when he had perused he returned, and with them this character,
that "`The composer resembled the industrious bee, which gathered honey from every herb;
and like the wise master-builder, had brought materials for the building,
though he did not live to finish the work.`"

To be short, he was of a clean life, and of a blameless conversation,
a zealous attender of meetings, and an example to the youth where he lived.
He was very industrious in spreading friends`' books, and it may be said of him,
he lived beloved, and died lamented, both by friends and neighbours;
for he was a dutiful child, a tender brother, a faithful friend, and a good neighbour.

He went from home to the city of London in his father`'s business,
and was there taken ill on the Fourth-day of the week, and died the Second-day following,
at a relation`'s house.
He uttered many precious sayings and heavenly expressions; but his relations,
and those that came to visit him, were not so careful as to pen them down.
He signified what a concern he had for his parents and friends in the country,
whom he thought would be involved in tears and sorrow,
when the news of his illness reached their ears.
He expressed his resignation to the will of the Lord, whether in life or death.

He often called on his mother, being in hopes he should see her before she died;
but his distemper increased so fast,
that before she came he put off this mortal clothing, and ascended, we do not doubt,
into those celestial mansions of everlasting bliss,
of which fruition he had an earnest whilst on earth, though young in years.
As the wise man says, "`Though the righteous be prevented with death,
yet shall ye be in rest.
For honourable age is not that which standeth in length of time,
nor that which is measured by number of years; but wisdom is grey hairs unto men,
and an unspotted life is old age.`"

He departed this life the 24th day of the Second-month, 1710,
and was interred in Friends`' burying-place, near Bunhill-fields, London.

[.asterism]
'''

THOMAS EVERDEN was formerly an inhabitant of Canterbury, England, and went into America,
and lived at Fishing Creek, on the Eastern Shore.
He was one whom the Lord fitted for the work of the ministry,
and he preached the gospel of peace.
The Lord also gifted him to be helpful in the government of the church,
and to maintain the order of the gospel.
In the meekness of the wisdom and power of God was he made to testify
against those that stood not faithful in their testimonies for the truth,
which the Lord required at their hands.
And such as would not be restored by the spirit of meekness in the labour of love,
and be prevailed upon to be orderly in their conversation,
he was zealous that they should be testified against;
and careful he was to maintain the testimony of truth in the simplicity thereof.

He also zealously and faithfully laboured long in the Lord`'s vineyard,
to the convincing, building up, and confirming many in the faith of God`'s elect,
in many parts of America.
The Lord`'s power and presence attended him in all the services he concerned him in,
and greatly blessed him and his labour in the gospel.
He retained his love to the Lord, his zeal for his name,
and concern for his glory to the end,
as may partly appear by the following account of his dying sayings,
and the epistle he wrote a few days before his death.

He was taken ill about the 10th of the Third month, 1710,
and continued weak about three or four weeks;
in which time he very often expressed his great satisfaction
relating to his future state,
for he declared,
he did expect the Lord had sent the messenger of death to summon him to his long home;
and said, "`Death is made easy to me, because I know the sting is taken away,
and my Lord is near me.`"
He also often said, "`I have but little pain, for my Lord, whom I have served,
is with me, and fills my treasury.`"

He often exhorted his children, friends and neighbours, to keep to truth,
and in love with one another; adding,
"`How good a thing it is to have the favour and smiles of Jesus upon a dying-bed,
which cannot be had out of the truth.`"
Therefore he exhorted all to serve the Lord faithfully,
and to stand up for the testimony of truth in their day, not fearing the frowns of men;
for, said he, "`what should I have done now, if I had gained the whole world,
and had now been destitute of the favour of my Lord,
which is more to me than all the world.`"
With many such expressions, good admonitions, and advice,
he continued until his departure, which was on the 4th day of the Fourth month, 1710.

A copy of the afore-mentioned letter, sent about ten days before his death,
directed to the meeting of ministering Friends at West-River.

From Fishing Creek, the 24th of the Third month, 1710.

Friends: In the love of the Lord Jesus Christ I salute you all.
I am at this time very weak in body, in expectation of my dissolution to be near at hand.
Blessed be the Lord God who hath called us, and chosen us to be witnesses,
not only in word and doctrine, but in a holy life and godly conversation.
His living and powerful presence is with me, and in this I greatly rejoice.
My brethren, my love abounds greatly to you,
and I embrace you and salute you in the same love
and life with which the Lord hath loved me.

Receive this friendly exhortation from your dying brother, as I think,
that as God has given us a gift, and opened our mouths in his name,
that you abide and live in his name;
for herein are we made instrumental for the gathering of others, and to glorify his name.
What! hath God chosen us, and counted us worthy to speak to his church and people,
and to turn many to righteousness.
Surely, brethren,
it greatly concerns us to walk even as our Lord walked when he was upon the earth,
according to the measure of the gift of grace that we have received from him,
in patience, in meekness, and wisdom, and heavenly gravity, and few words,
such as minister grace to the hearers, and those who converse with us.
Since I last saw you, my service has been chiefly at Cecil and Chester,
and Great Choptank.

Farewell, farewell in the Lord.

Thomas Everden
