== Chapter 5

[.chapter-synopsis]
* Alexander Seaton
* Thomas Raylton

ALEXANDER SEATON was born at Cuttle-Craggs, near Lethinty,
in the parish of Daviot and shire of Aberdeen, in the north of Scotland,
in or about the year 1652; son of John Seaton, from the Seatons of Meldrum;
and brought up a scholar, and for some time in the college in the old town of Aberdeen.
While he was a scholar, there was a dispute between the students of Aberdeen,
and Robert Barclay and George Keith, who defended the principles of truth,
as held by the people called Quakers, against the students, in the year 1675.

He being present, was so far convinced of the truth of the doctrine held by Friends,
as afterwards to own the same publicly.
So that while he was a young man, it pleased the Lord to open his understanding,
and show him the mysteries of his kingdom, and way of life and salvation;
and being joined in society with the people in scorn called Quakers,
he grew in the truth, and became very instrumental in the service of the gospel,
for the confirming of friends in the truth, and information of others,
yea even such also that opposed the truth.
He was drawn forth in the love of God, to visit Friends`' meetings in Scotland,
Ireland and England, several times, was imprisoned at Aberdeen,
and suffered very much at Glasgow for his testimony to the truth.
He was a faithful,
zealous and sound minister of the gospel of our Lord and Saviour Jesus Christ;
exemplary in humility and lowliness of mind, lived in peace and unity with friends,
and was well esteemed amongst his neighbours.

When under weakness and affliction of body, he bore it with much patience,
and was very sweet in his spirit, as may appear by the following expressions, viz.,
several being come to see him, he said, "`Since these severe fits,
I was concerned about my latter end, and it was opened to me,
that I should depart in peace.
There is a mansion of glory prepared.`"
At another time, when his family was about him, he said,
"`l do not put off repentance and amendment of life until the time of a dying bed,
for commonly it hath enough to do for itself.
The Lord hath been very good to me, even from my youth,
and hath followed me with his goodness,
and never left me in the time of divers exercises.
His presence is near, and it is manifested to me, that when my departure comes,
it shall be in peace.
The Comforter is near, and will endure, and the afflictions will have an end.`"

At one time when some friends came to see him, he said,
"`I have partaken of the earnest of that joy that will never have an end.
My rock, my fortress, my strong tower, dwelleth with me,
and does not leave me or forsake me, blessed be his name.
I hope to be with him forever, and that is more than a thousand worlds.
There is a mansion of glory prepared.
In my Father`'s house, said Christ, there are many mansions,
if it had not been so I would have told you;
there has been a discovery of a mansion of glory.`"

Some friends coming before meeting, to see or visit him, he said,
"`Job was hardly put to it, and his friends were all mistaken,
in that they did not believe that the Lord afflicted man without a sinful cause.`"
His wife persuading him to take something, lest he should faint, he consented, saying,
"`Let me try to eat one bit with my friends,`" but turning the case, added,
"`Christ said, labour for the bread that perisheth not,
but nourisheth up to eternal life.
Praises wait for the Lord in Zion.
No trials, no afflictions, no temptations,
can obstruct his presence from the inhabitants thereof.
Praise is comely for the upright, but becometh no wicked person.`"

Sometimes, being much pained, he would say, "`Lord give me some ease,
or take me to thyself.
O Lord give patience, sustain and support me under these sharp afflictions.
Let the lifting up of my hands be as the evening sacrifice, acceptable unto thee.
O Lord! thou art my rock, the shadow of a mighty rock in a weary land.
The Lord hath promised to be with his children through the region and shadow of death,
and bring them to a lasting eternity,
where there is joy forevermore;`" and therefore said to his wife, "`Be content.`"

Another time, after having got some rest in sleep, he said, "`Why am I kept here.
Let me go home.
Lord receive my spirit.
I recommend my soul to thee.
Receive me into thy everlasting kingdom, and the mansion of glory thou showedst me.`"
A near friend coming in to see him, asked him how he was; he said,
"`I would fain be gone, the Lord hath been very good to me,
and led me through the cross to inherit the crown.
When he seemed to be a little eased of the pain which was often violent upon him,
his wife asked him if anything troubled him,
as to the settling of his affairs or children; he said, "`No,
the greatest trouble that attends me, is to part with thee,
who hast been made a blessing to the family.`"

At another time he said, "`The Lord hath been good to me from my childhood.
He began to place his fear in my heart very early.
The Lord never fails those who trust in him, he will be with them to death,
and through death unto eternity.
Fear God and serve him, prefer his fear above all things, and he will provide for you.
And said to his wife, "`My dear, the Lord is a father to the fatherless,
and a husband to the widow, that love and fear him,
therefore be content and resigned to the will of the Lord.`"

About two or three weeks before his decease, several friends having been at meeting,
went to see him, and after a time of silence, a friend spoke a few words,
after which Alexander being very much broken into tears, said,
"`It is the invisible power that supports under affliction.
Moses endured, seeing him that is invisible.`"
At another time he said, "`A sharp war, the sooner peace,`" Several Friends,
belonging to Lurgan, Ballindery and Lisburn meetings, hearing that he was very weak,
came to see him, whereupon his wife asked him if he knew them; he said, "`I do very well,
but it is a trouble to me to speak; but all is well, and will be everlastingly well.`"

His distemper was tedious, being often extremely sharp,
all which he bore with admirable patience,
and departed this life in great peace and quietness, the 23rd day of the First month,
1723.
And we have good ground to believe that the Lord hath received
him into his kingdom of everlasting rest.
His corpse was decently buried the 25th day of the said month,
lovingly accompanied by friends and neighbours.
Aged about seventy-one years; a minister about forty-seven.

[quote.scripture, , Psa. 116:15]
____
Precious in the sight of the Lord is the death of his saints.
____

[.asterism]
'''

[.embedded-content-document.testimony]
--

[.blurb]
=== THOMAS RAYLTON.--Some account of the birth, education, and convincement of that faithful minister of the everlasting gospel, Thomas Raylton, found after his decease, in his own hand-writing: to which is added some farther relation of his ministry, etc., since his settlement in London, taken from the testimony of the Bull and Mouth monthly meeting, concerning him.

I was born on the 30th day of the Sixth month, 1671, in Bowes,
in the north part of Yorkshire, and educated in the way of the church of England.
But in the year 1685, being about fourteen years of age,
and then a scholar with one Richard Wharton, priest of the parish,
and teacher of a freeschool in Bowes aforesaid,
it providentially happened that by the invitation of Francis Wrightson,
one called a Quaker, at whose house a meeting was kept,
about two miles from the place of my abode, my mother went to a meeting there,
and took me to ride before her.
At this meeting were two ministers, namely, John Bowron and George Rook,
the latter then living in Cumberland, but since in Ireland,
being come to visit Friends thereaways, by whose powerful ministry and lively prayer,
it pleased God to open my heart, and to let me see the vanity of this present world,
of which, for my short time, I had had some share,
for which I had been often secretly smitten by the just witness of God in my own heart.

Yet, for all that, I was pretty much a stranger to it,
and so was not sensible from whence it came, until I came to be affected with the gospel,
which, I may say, was glad tidings of salvation to me.
From that day, I was joined in heart with those people that directed to Christ within,
the hope of their glory.
And although I have had many instructors in Christ since, yet I have not many fathers,
for the said George Rook, who preached the word by the gospel of Jesus Christ,
was the instrument under the Lord for my convincement; for which, I bow my knees,
and worship and thank the Lord for his goodness hitherto.

After I was joined with those people, the word of God more powerfully wrought in me,
and showed me that I was to alter the course of my conversation; that was,
to leave the corrupt life, and shun evil company.
And forasmuch as I was bowed before the Lord, and had given up my name to serve him,
I then saw I must walk in the narrow way, and leave the vain compliments,
the putting off the hat, and bowing the knee to man, etc.
I was soon taken notice of, and complaint made to my mother,
of my neglecting to conform to these things, by the priest, my then master,
who was moved at my behaviour, and I suppose, intended at that time to have used the rod,
and having made preparation, called me to him.
He said, "`I heard today that thou wentest by Mr. Bounskell,
and didst not put off thy hat, and bid good morrow;`" adding,
"`What is thy reason for so doing?
whether is it pride or religion?`"
Upon which I told him it was not pride.`"
"`Then,`" said he, "`it must be religion; and if so,
thou must not be whipped and so laid down the rod.
"`But,`" said he, "`if for religion, let me know why thou refusedst, and give me some precedent.`"
So I told him I had been reading in the Revelations,
and there I found that an angel showed John many things, and that John said,
"`When I had heard and seen,
I fell down to worship the angel that showed me those things; but the angel said,
See thou do it not, for I am of thy fellow servants, and of thy brethren the prophets,
and of them which keep the sayings of this book: worship God.`"
And from this I told him, I refused to do it unto men.

But he endeavoured to persuade me, that what he requested of me,
was no more than a civil respect between man and man;
and from thence he thought I might the better conform to it.
To make me the more willing to believe it was no worship, but respect,
as he had said before,
he turned me to the place of Heth and Abraham`'s bowing to each other,
and also proceeded to show me something of the like kind among the Children of Israel,
in the time of Moses and Joshua.
But all these were to no purpose to me,
for my eye was open to see a more glorious dispensation than that of Moses, yea,
or the prophets.

For though they were good men, and by the spirit of Christ in them,
they did foretell the coming of Christ, and of his sufferings;
yet they did not live to see those things come to pass, which they had spoken of.
So that he had no force in his argument to make me use those things,
which might be used among the fathers, and also after the law.
And since the New Testament is silent,
and gives no account of either Christ or his apostles being in the practice of bowing;
I did not see why either knee or hat should be expected of me.
As for the latter, I have no account at all, therefore I stood to my principle,
and kept to the light and understanding the Lord
hath given me through Jesus Christ my Saviour,
who then was come to my house in spirit, and had brought salvation with him.

That day I told one of my school-fellows that what
my master had shown me was but out of the law,
and not of the gospel, which he told my master, and I had a quiet day.
It is to be observed that this was but the beginning of further exercise,
for as it was in some measure begun,
(though I had at that time met with favourable treatment from my examiner whose moderation,
as I have said, then appeared,) yet after this,
whether it was grief which he was then in,
being in all probability likely to part with one from his flock,
over which he might look upon himself to be pastor, or from the persuasion of my parents,
he began to be more severe, and told me that unless I would make congees to him,
as he called them, he would teach me no longer.

Although I must confess I would gladly have learned a little more,
being then a bible-scholar, yet +++[+++rather than]
to have it in a way I saw I must deny and bear testimony against,
I forsook the school at that time, and went home to my father`'s house,
and told my mother the occasion of my coming.
Although she took me to the first meeting but a few weeks before,
yet she then repented it, and would not hear of my suffering by my master,
so as to give me any relief; upon which I left the house for a while.
But I think I may say, the arm of the Lord wrought for me,
for my master presently sent word to my mother,
that he had done what was in his power to persuade me to be conformable,
but he saw it would not do, therefore desired her to send me to school again,
and said he would leave me to my liberty about religion.

The tidings were brought to me, as I was alone under an hedge, where I was retired,
not then knowing what would become of me, who had both left the school,
and knew not with whom to lodge.
But whilst I was in this condition, the tidings I have mentioned were brought to me,
which I received gladly, and went to school again,
and found it pretty much as had been told me;
and thus the Lord pleaded my innocent cause, to whom be glory ascribed forever.
Thus far I was got on my way, and was still to go farther.

My parents had taught us from our childhood to ask of them to pray to God to bless us;
and though it is true there is not an evil in the thing itself,
yet the bringing of it into such a form as to use it every night and morning,
this also I found was my place to leave off, at which they were very much offended,
and began to beat me into a compliance with them.
But that would not do, for I had read that saying of our Lord,
"`Whosoever loves father or mother more than me, is not worthy of me.`"
So that in an holy resolution I went on,
not much doubting but the Lord would help me over that as he had over other things before,
which, in time, he did.

The course I took, after much threatening and several beatings upon the above subject,
was this.
I left my father`'s house, and was kept privately for about fifteen days; but as Moses,
by the good providence of God, and care of his sister,
who watched to see what would become of him,
was ordered to his mother again to be his nurse, a providence to be commemorated,
so was I watched over by some of those people to whom I was joined in fellowship,
and by them sent for to come to one of their meetings.
I being then remote from it, yet at their request I went;
for meetings were precious to me.
I had been but at about two meetings from the first,
and that was about three quarters of a year before,
and a good meeting this also was to me.

After the meeting was over,
some of the Friends undertook to go and offer me to my father again.
I went along with them, and coming there,
they told my father it was their desire that he would take me home again,
as I was his son; and if he would not accept of me as a son,
then as a servant into his house; but if he would not as either, "`then,`" said they,
"`he must become our care, forasmuch as he is become one of us.`"
This proposition took such place with my parents,
that the Friends were thanked for the care they had over me.
Thus I was brought home again, and had free access to their presence morning and evening,
without insisting upon the aforementioned ceremony,
which was the cause of my leaving their house,
because they were wroth that one of their children should leave their religion,
and decline going to church, as they called it.

For about seven weeks more I lived with them at peace,
and went to meetings with their knowledge; and at the end of that time,
being the 30th day of the Fourth month, 1686,
I went apprentice to a Friend in the county of Durham, by the approbation of my parents,
being conducted thither by my father.
Thus my freedom was brought about, so that I might well, with some of old,
sing unto the Lord, and say, he had delivered me from the noise of the archers,
in the places of drawing water.
In the time of my seven years`' apprenticeship to a laborious trade, being a blacksmith,
at leisure times I often read the Scriptures of the Old and New Testament,
in which I found great benefit, being often broken into many tears when I read,
and especially when I met with places that mentioned the call of God to sinners,
and their return to his call, in order for their conversion and salvation.

My delight was much in reading some places of the prophets,
which prophesied of the coming of the just One,
and of the work of restoration that he would bring to pass,
and although I have said I delighted in those things, yet the crown of my rejoicing was,
that I was counted worthy to know this blessed work begun.
I not only read in private, but in the family we used to read much by candle-light,
my master and mistress allowing it, and were in the practice thereof themselves,
being honest Friends who feared God, with all their children,
who were dutiful to their parents,
and kept very much out of the evil communication of the world,
so that we were a comfort one to another, as we kept to that which was good.

When I have been alone at my work, the Lord very often comforted me with his holy spirit,
and gave me a sight that he would give me a dispensation of the gospel to preach;
and for seven years the word of the Lord was often very powerful in my heart,
not only to the fitting of me for so great a work,
but growing upon me to the affecting of my heart.
During those years, living breathings often ran through me to the Lord,
that he would preserve me in his fear.

After I had served out the full time of my apprenticeship,
I went to the place of my birth, and there followed my trade about a year.
But it was not long until the Lord brought that which I had seen before more near, viz.,
the work of the ministry.
The nearer it came to me, I still saw the more need to be weighty and solid,
and much inward in spirit, often filled with the word of life,
so that I could scarcely hold my peace in the assemblies of the people of God;
yet much inward and still, often remembering the building of Solomon`'s temple,
where there was not the sound of a hammer or iron tool.
In this quietness in meetings,
I was greatly refreshed and filled with inward joy to the Lord,
but could not yet utter by words what I felt.
For, indeed, as the ministry is a great work,
it made me the more cautious how I entered into it,
remembering it was not approved that one of old laid hold of the ark +++[+++unbidden]
when it was shaken.
By all this experience and carefulness,
in not offering until I was fully satisfied it was my incumbent duty,
I found it safe not to appear in the ministry until
I was fully satisfied of the Lord`'s requirings therein,
although the Lord had been often with me from meeting to meeting, and,
in his visitations, left his holy dew upon my spirit.
Thus was I filled with the odour of his good ointment,
with which I was anointed to preach the gospel; and thus I was led into the ministry.

Upon or about the 30th day of the Tenth month, 1695,
in a meeting at the house of John Bowron, in Cotherstone, where I was, amongst many more,
after a little time, my soul was divinely touched with the power of God,
and his word was again in my heart, as a burning fire in my bones.
I could no longer contain; my tongue being loosed,
my mouth was opened to speak of the Lord unto his people in that meeting.
I cannot but observe one thing, and that was,
the holy silence which was in the forepart of that meeting, before my mouth was opened.
Although there were several there that had public testimonies,
yet that power by which I was opened, bound them to silence.
But after I had spoken what I then delivered, there stood up a Friend,
and was like one that had a seal to set to the words I had spoken.
As I grew in testimony, a concern came into my mind to visit Friends in Cumberland,
where, after some time, I went, and was kindly received by them,
and was at most of their meetings, if not all.

[.signed-section-signature]
T+++.+++ Raylton.

--

This our dear friend Thomas Raylton,
after he had travelled much in the service of the truth,
settled in London about the year 1705,
where he was very serviceable and edifying in his ministry, sound in his doctrine,
mighty in the Holy Scriptures, zealous for the truth,
and a faithful reprover of any undue liberty in the professors of it.

He was many years afflicted with infirmity of body; but being fervent in spirit,
was strengthened in the work of the ministry beyond expectation;
so that he bore his testimony to the truth at times, in the meetings of Friends,
not only in London, but in most counties of England.
The year before his death, in much bodily weakness, he took a journey from London,
and visited the brethren in his native county, to their mutual comfort,
and returned home well satisfied in his service there.

In his last sickness, which took him about the beginning of the Ninth month, 1723,
he bore the extremity of his pain with great patience and resignation;
having some time before signified a sense of his approaching departure, by saying,
"`My day`'s work is nigh finished.`"
And but a few days before his death, he told a friend that he had settled his affairs,
being satisfied that his departure was at hand;
adding in a sensible and humble manner,`" Doubtless it will be a glorious change to me.`"
To his wife he thus expressed himself "`My dear, be easy, let me go,
and rejoice when I am gone to so great salvation.`"

He departed this life in peace and full assurance
of future happiness at two in the morning,
the 6th day of the Tenth month, 1723, in the fifty-third year of his age,
and was decently buried on the ninth of the same month,
in Friends`' burying-ground near Bunhill-fields.

[.the-end]
END OF THE SIXTH PART
