== Chapter 1

[.chapter-synopsis]
* John Wynn
* Deborah Wynn
* Deborah Bell
* Jennet Stow
* Abraham Anthony

JOHN WYNN, of Bradford, in Yorkshire,
was convinced of the blessed truth at a meeting of Friends in Pall-Mall,
near Westminster,
about the time of the coming in of king Charles II. Being then in the army,
and standing amongst the rest in their ranks to be viewed by some of the chief officers,
he laid down his arms because he could practise war no more, and when discharged,
he went down into Yorkshire, and worked at his trade there, being a clothier.

As he continued faithful to the visitation of truth, he grew in grace,
and in the saving knowledge of Jesus Christ our Lord;
and being subject to the divine manifestation and work of the power of God in his heart,
he became a sanctified vessel fitted for the great Master`'s use,
who in his wisdom called him to the work of the ministry,
in which he grew and laboured faithfully in those times of persecution,
wherein he suffered deeply for his testimony.

He was a man of courage, filled with a holy zeal, and qualified,
as a good soldier in the Lamb`'s warfare, for the work in those perilous times;
his bow abiding in strength, and his arrows being sharp and piercing,
were carried home to the mark, so that he fought manfully under the banner of Christ,
and turned not his back in the day of battle.
He was an able minister of the everlasting gospel, and laboured faithfully therein,
and travelled much for the spreading of it in those
trying times in most parts of England and Wales,
and especially in the eastern parts.
His service on that account tended much to the strengthening
and confirming the children of God,
and convincing of gainsayers.
He retained his integrity to the end,
and the strength of that holy zeal kindled in his heart for the blessed truth,
and the promotion of its cause, remained always with him.
For a farther account of his labours, service, and sufferings,
the reader is referred to divers testimonies concerning him, published in the year 1715.

Towards the latter part of his time, he travelled into the west parts of Yorkshire,
to visit the meetings of friends there.
Having a sense that his day`'s work was nigh finished,
he told friends in divers places he was come to take his leave of them,
although then in a good measure of health.
After his return, he signified his great satisfaction and easiness of mind.
About three weeks after he had finished that journey,
going a few miles to visit a neighbouring friend who was sick,
a service that he was frequently concerned in, he came home not very well,
and continued weakly about thirteen days.
In the time of his weakness, the great concern that was upon his mind was,
that friends might stand faithful to the Lord God,
exhorting such thereto as came to visit him.
He declared, a little before his departure, that he was clear and easy in his spirit,
and saw nothing to stand in his way, but witnessed the peace of God to abide upon him,
saying he had laboured faithfully to clear himself
of those who were of a libertine and frothy spirit,
as he then called it.

The day that he died, a little before his departure, as he was walking about the room,
a fainting fit seized him, and he sat down and leaned back in his chair,
and seeing his wife weeping over him, he looked upon her, and said, "`Why wilt thou,
my dear?
the Lord gave thee unto me, and thou must give me up again.`"
She answered and said, "`I hope I shall as far as the Lord enables me,
for I hope it will be well with thee.`"
He said, "`I never doubt that:`" which were the last words he spoke,
for the Lord was pleased to make his passage easy out of this world,
so that he gave neither sigh nor groan, but in a quiet stillness,
like one falling asleep, he departed this life the 16th day of the Ninth month, 1699,
in the sixty-fourth year of his age,
having been a true labourer in the work of the ministry about thirty-six years.
Having, through the grace of God, fought the good fight of faith,
and finished his course,
we have no cause to question but that his soul is at rest with the Lord,
being entered into the possession of that crown of eternal
life that is laid up in store for all the righteous,
where he will live to praise and magnify the Lord God,
and the Lamb who sits with him upon the throne, forever and evermore, world without end.
Amen.

His body was buried in Friends`' burying-ground, at Bradford aforesaid,
the 20th day of the aforesaid month,
being accompanied to the grave by many Friends and sober neighbours,
where divers living testimonies were borne to the comfort of the upright in heart,
and particularly by that eminent minister of Christ, William Ellis,
who had been effectually reached to by his ministry in his young years.

[.asterism]
'''

DEBORAH WYNN, wife of the aforesaid John Wynn, had a sober and religious education,
and was favoured with the visitation of truth in her young years,
and by giving up to the manifestation thereof,
she came to experience the work of its power in her heart, and,
by being obedient thereto, attained to a degree of settlement in the truth when young.

This prepared her to undergo those trials and exercises
which early began to fall to her lot;
for about the sixteenth year of her age,
her father and mother were both taken up and carried prisoners
to York for the testimony of a good conscience towards God.
She being their only child,
the management of their trade and business fell under her care;
and during their imprisonment she travelled, to York, twenty-two miles, on foot,
twice in two weeks, to visit them,
and to carry them what money she had got for their support.
Being sincere in heart to God, and through his grace faithful to the truth,
she grew in experience,
and about the eighteenth year of her age she was
concerned to bear a public testimony in meetings,
to the comfort and edification of Friends.

She was afterwards married to John Wynn, and they settled at Bradford,
the place of her nativity, and, being both ministers,
and the meeting in its course held at their house,
heavy sufferings fell to their share in the time of the informers,
who stripped them three several times of all their outward substance that was valuable.
For such was the cruelty of the persecutors and informers in those days,
that at one of the times mentioned she was lying sick,
and they went to take the bed from under her; but the neighbouring women,
abhorring the inhumanity of such an attempt, interrupted their design,
and would not suffer it; but they, finding a pewter flagon in the room with caudle in it,
poured it out, and took the flagon away with the rest of the booty.
Their avarice being not yet satisfied,
they met her husband in the street as they went away,
who had been at a neighbouring market, and was driving his horse before him,
with the goods on his back, and his riding-coat upon the pack;
all which they seized and took away with the rest of the plunder.

Being deprived of his horse, pack and coat,
he came home and found his shop stripped of the goods, and his house of the furniture,
that he had neither chair nor stool to sit down upon to rest him,
until some of his kind neighbours, whom he found there bemoaning this unchristian usage,
went and brought him in, some one thing, and some another, for their present use,
until they could procure furniture of their own for their necessary accommodation.
Afterwards, divers of the inhabitants of the town,
hearing of his intention of buying more goods to carry on his trade, came to him,
and earnestly entreated him he would buy no more,
for he might see they were resolved to ruin him.
He told them he was not at all discouraged; he had a little money left,
and intended to lay it out for goods as far as it would go;
and if they took them from him also, they could have no more than all;
but he believed they would be limited in the Lord`'s time;
which came to pass accordingly.

Through all which, with her dear husband, she retained her integrity,
and stood faithful to truth`'s testimony,
so that they were favoured of the Lord together to surmount
all difficulties their great sufferings brought upon them.
She was a woman of a sound judgment,
great sincerity and circumspection in the course of her conduct,
tender and living in her public ministry;
and by her godly and courteous conversation she gained the love and esteem
of both Friends and others in the town and country where she lived.
Her heart and house were open to receive and entertain the messengers of Christ,
who were concerned to go to and fro to promote piety and virtue,
and publish the gospel of glad tidings to mankind;
and she delighted much in that service.

It was my lot to marry her only daughter,
after which time she chose to live with us to the end of her days,
which was upwards of seventeen years,
which tended much to our satisfaction and mutual comfort.
She being acquainted with divers of the first publishers
of the gospel of glad tidings in these latter days,
her conversation was very agreeable and informing.
She was a loving and affectionate mother, a faithful friend,
and endued with wisdom to give counsel in times of greatest difficulty,
having had large experience of the dealings of God,
and the preserving power of Jesus Christ our Lord;
she retained her zeal for truth and concern for its promotion,
and was diligent in attending meetings as long as
her ability of body continued to go abroad.

She was confined to the house the last year of her time,
growing weak by reason of old age; and during that time,
she employed herself much in reading the Holy Scriptures and Friends`' writings,
with many of whom, in her youth, she had been acquainted.
She continued in a sweet, heavenly frame of mind, often expressing, in much tenderness,
the lovingkindness and goodness of God to her, frequently saying,
"`The Lord hath been my support in all my difficulties,
and hath preserved me from danger; and his goodness is still continued,
and I have great cause to praise him and speak well of his name.`"
This she would often repeat, with many other weighty and lively expressions,
signifying how resigned she was to the will of God, and desirous to be dissolved,
being duly prepared for that great change.
About three months before her departure she was confined to her chamber,
but still continued in a sensible frame of mind, and waited patiently for her removal,
expecting its drawing nigh,
although she had no distemper upon her but weakness through old age.

Her daughter`'s affection and care were great over her both night and day,
for fear she should drop off suddenly, though a nurse constantly attended her.
When she saw +++[+++her]
weep, and under trouble at the apprehension of parting with her, she would send for me,
and would desire me to advise my wife not to be troubled or concerned on her account;
for, though she had no distemper, pain nor sickness,
she said we must not expect she would always continue with us,
but would have us give her up freely, she being prepared,
and ready to be received by Jesus Christ into eternal felicity.

I told her we were resigned to the will of God,
and thankful he had so long prolonged her days,
and accounted it a great blessing our being favoured with her company to that time.
She added, "`Your care over me, and your concern for me,
have been too great in every respect, I think;
and I have been often thankful to the Lord,
who hath been pleased to bless me with such loving and affectionate children.
I have been afraid my dear daughter would hurt her own health by caring too much for me.
The Lord who was the stay of my youth, and has been with me to old age,
is still near to comfort, and will be so to you when I am gone,
and bless and preserve you to his own honour and your peace
unto the end:`" with much more at divers times,
too tedious to relate.

She grew gradually weaker, yet sat up most days,
and could walk over the room with a little help.
In the evenings, when business was over, we went up and sat down by her,
and had many comfortable seasons together, for she continued in a sweet frame of mind,
and very cheerful and sensible.
On the 14th of the Sixth month, 1727, being the second day of the week,
my dear wife and the nurse took her up and dressed her about ten in the morning,
as usual, and she sitting in her chair, they perceived she grew very weak,
and sent for me.
I went up and sat down by her, and taking her by the hand, asked her how she was,
she answered, "`Very weak, child.`"
I asked if she was sick or faint, she said "`No.`"

I asked if she had any pain, she said, "`No.`" I asked if she apprehended herself going,
she said she could not tell, but she was weaker than ever she was before.
I bade her lean her head upon my breast, which she did, and was as quiet for some time,
as if she had been in a doze, that we could scarcely discern her breathe;
and her daughter sitting by weeping, she lifted up her eyes and said, "`Dear child,
weep not for me,`" and leaning her head on my breast again,
near the middle of the day she passed away so quietly,
that we scarcely knew when she drew her last breath.
She was about eighty-two years of age, and a minister about sixty-four years,
and I doubt not,
is entered into that undisturbed and glorious rest prepared for
the sincere and upright-hearted followers of the Lord Jesus Christ.

On the seventeenth day of the aforesaid month,
her body was carried from our dwelling-house in Clement`'s
lane to the meetinghouse in Gracechurch-street,
where many friends met on that occasion,
and divers living testimonies were borne to the truth; and after a solemn meeting,
her corpse was accompanied by a large number of friends
to Friends`' burying-ground near Bunhill-fields,
and there decently interred.

[.signed-section-signature]
J+++.+++ B.

[.asterism]
'''

[.embedded-content-document.testimony]
--

DEBORAH BELL, wife of John Bell, of Bromley, in Middlesex, late of Gracechurch-street,
London, daughter of the before-mentioned John and Deborah Wynn, was born at Bradford,
in Yorkshire,
and being carefully educated in the way of truth by her pious and faithful parents,
she sought the way of the Lord, and the knowledge of his blessed truth, when very young,
and was mercifully favoured to partake of that virtue and
divine goodness which maketh fruitful towards God,
as she frequently expressed herself.
In her minority she often earnestly desired that the Lord
would be pleased to enable her to come up in doing his will,
and that in all things she might be perfectly resigned to answer his holy mind and requirings,
and be fully given up in heart in all sincerity,
and by his grace devoted to serve and obey him, according to the ability received.
He in mercy and lovingkindness heard her humble petitions,
and granted the early visitations of his love and goodness,
in the pourings forth of his holy Spirit, and gradually,
by the work of his own divine power, so prepared and sanctified her heart,
that she was made a vessel of honour.

As she became acquainted with his divine and living word, when very young,
she grew in experience of that work which is wrought by the power of Christ,
by which alone salvation and perfect redemption is witnessed.
Being an humble follower of Jesus Christ our Lord,
and through the operation of his grace freely resigned, and cheerfully given up,
to follow these manifestations of the divine light and workings of the Spirit,
which are inwardly revealed, she was so fitted for her Master`'s use and service,
as early to become a branch in Christ Jesus, the true and living vine,
laden with fruit to the praise and glory of God, the good husbandman.
Being led through deep travail, and close exercise and affliction of mind,
she thereby gained great experience,
and was made sensible of various states and conditions,
which tended to qualify her for that great and weighty
work whereunto she was afterwards called.

About the nineteenth year of her age the Lord saw meet in his wisdom
to commit a dispensation of the everlasting gospel to her to preach,
in which service, she being faithful, grew in the knowledge of God,
and had great experience of his dealings, and like the wise scribe,
who was well instructed to the kingdom,
brought forth out of the good treasury of her heart, things both new and old;
so that she became an able minister thereof,
to the comfort and edification of the churches where she came.
Many, who were unacquainted with the work of the blessed truth in themselves,
were reached to by her powerful and lively ministry,
in the service of which she often appeared strong when in bodily weakness,
which frequently attended her,
to the admiration of those who had the knowledge of her outward infirmities.

She laboured faithfully in word and doctrine,
and visited many of the meetings of Friends in most parts of England, Wales, Scotland,
and was twice in Ireland, and had good service where she came,
for she duly regarded the motions and guidance of truth in all her services,
and in an especial manner, when under a concern to travel on that account.
She earnestly desired to be fully satisfied of being rightly called,
and to see her way clearly opened, both as to the time when, the place where,
and the people to whom, it was her duty to minister,
and was ever very careful to return when she found her mind clear and easy.
She would often say, which I mention for the instruction of others,
that there was great danger in exceeding the commission
by staying abroad beyond the right time.

She greatly desired that all the ministers of Christ,
who found themselves concerned to travel in the service of the gospel,
might take due care not to miss their way on that hand; neither might,
when in their travels, be drawn aside out of the right line opened to them by the truth,
through the persuasion of unwary inconsiderate people,
but might wait for the power of Christ our Lord to preserve them steady
in mind in all their services for the promotion of the blessed truth,
frequently repeating that she had observed divers
whom she believed to have been rightly drawn forth,
who yet through weakness and instability had missed their way in those particulars,
and thereby received hurt and lessened their service.

When she was under a concern to go abroad to visit the churches,
the weight of that exercise brought her very low, both in body and mind.
She waited diligently for the counsel of God, and full satisfaction in herself,
before she made her concern known to any; for her whole dependence was,
in great humility, on Christ our Lord, to put her forth, and go before her,
and to give her strength and wisdom,
to discharge herself faithfully to her own comfort and peace,
the edification of the people, and his honour.
But though she was strong in the Lord, and zealously concerned for the cause of truth,
yet, by nature, of a weakly constitution, and through hard travel, and close exercise,
which often was upon her for the truth`'s sake,
her bodily infirmities increased before old age came on.

Towards the latter part of her time, being often infirm,
she frequently rejoiced in the Lord, and expressed the great comfort, peace,
and satisfaction which she had in having devoted her youthful days to his service,
and being freely given up faithfully to obey his calls and holy
requirings whilst a degree of health and strength was granted,
and she was able to undergo such service,
often saying an early devotion was very acceptable to God,
and the strength of youth could never be so well and profitably employed,
as in faithfully serving the Lord in humility and sincere obedience in
whatsoever work he in his wisdom may be pleased to qualify them for,
and call them into.
For wheresoever it happened that any such lived to
be attended with the infirmities of old age,
the comfort and peace they would enjoy,
would be abundantly more to them than all the comforts of this life;
for she could by living experience say,
that nothing in this world was worthy to be compared with it.

She often earnestly desired the sense thereof might lay hold of our youth,
that they might give up their minds to seek the Lord early,
and devote the strength of their time to his service,
that in the end they might be made partakers of the same comfort and peace,
which was her greatest joy and real cause of rejoicing,
and became more and more so as she drew near her conclusion.
This I publish for their perusal, that if by any means they might be prevailed on,
and stirred up to consider how necessary and truly profitable it
is to begin early in that great duty recommended by the wise man,
"`Remember now thy Creator in the days of thy youth, while the evil days come not,
nor the years draw nigh, when thou shalt say, I have no pleasure in them.`"

Being under a concern to visit a few meetings in Hertfordshire, and as far as Huntington,
though in a weak state of health, she undertook that journey, which proved her last,
towards the middle of the Seventh month, 1738.
She was from home ten days, and had six meetings, and although weak in body,
yet she appeared strong in her ministry, and had good service,
much to the satisfaction and comfort of Friends where she came.
When she came home she rejoiced much,
and said she was humbly thankful to the Lord who had enabled her to perform that journey,
and had given her strength to discharge herself faithfully of that concern she was under,
and that her heart was filled with that peace and comfort
which he is pleased to favour his obedient servants with,
and that she apprehended her day`'s work was nigh finished,
for she saw no more work her great Master had for her to do;
and she had no desire to live, but to serve and glorify him.

The last time she was at an evening-meeting at Bromley, about two weeks before she died,
she bore a living testimony to the truth,
and was concerned in supplication to the Lord in a particular manner,
and in great fervency prayed for the preservation, growth,
and settlement of the youth amongst us, in the living, eternal truth,
to the affecting and tendering of many hearts.
When she came home from the meeting she was filled with divine comfort and said,
"`It is now finished,
I do not expect you will have me with you at that meeting any more.`"

Afterwards her weakness of body increased, and she took a cold, which seized her lungs,
and occasioned a hoarseness, which she was often liable to.
On the 22nd day of the Eighth month, being the first day of the week,
we went to London to meeting, but being so much indisposed,
she was under some difficulty to stay the time of it, and did not go in the afternoon,
but waited for me at a friend`'s house until meeting ended.
Coming home, she continued weakly,
though a little better at times till Fourthday evening,
but she grew much worse again that night; she therefore had the advice of a physician,
but it had not the desired effect.

Her affliction increasing, on Sixth-day morning a pleurisy came on,
which distemper she had been liable to, more or less, for the last ten years of her time,
having had divers severe fits of it, which much affected her breathing.
Though means were used to remove it, she found no relief, and the pain grew more violent,
so that her affliction was great,
and in an humble submission she earnestly desired of the Lord that he
would give her strength to bear her pain and affliction patiently.
Her petition was fully granted, for she was endued with patience to an uncommon degree,
and bore her affliction with such a firm resignation and thankfulness of heart,
and with tender love and condescension to all about her,
and abundance of sweetness she still enjoyed,
as appeared by many precious and lively expressions which dropped from her,
which deeply affected, and often tendered the hearts of all about her.

When her pain was very great, she expressed herself at times after the following manner:
"`This is hard work indeed.
One had need to have nothing else to do at such a time as this.
I am sure it is as much as I am able to endure, to bear the afflictions of the body.
One had not need to have terror of mind besides.
Appealing to a young woman standing by her, whom she dearly loved,
and who had duly attended her in her illness, she said,
"`Thou knowest I have had very little respite from pain since I was first taken ill.
I would have none put off that great work of repentance till such a time as this;
if I had that work to do, what a dreadful thing it would be.`"
At another time, divers young people being present, she said,
"`I would have our young people be willing to bear the cross in their youth,
and despise the shame; for that is the way to have true peace in themselves.`"
Another time she said, "`I now feel that which my soul has longed for.`"

Seeing divers young women standing round her bed,
whose growth and settlement in the blessed truth she had often been concerned for,
she looked solidly upon them, and spoke on this wise,
"`I was early convinced that unless I was born again, I could not see the kingdom of God.
I have witnessed it, and you know I have preached this doctrine to you;
and you must know it for yourselves.`"
This she spoke with such authority as pierced the hearts of all present,
and I believe will not easily be forgotten.

At another time, looking steadily upon us, with a composed countenance, she said,
"`I have always been sincere, and never had anything in view but the great cause of God,
and that I might be clear of the blood of all men;
and I have discharged myself faithfully, for whatsoever my hand found to do,
I did it with all my might, and I never spared myself; and I am fully clear and easy,
and my day`'s work seems to be done.`"
At another time, observing the distress I was in, she looked earnestly upon me, and said,
"`The Lord brought us together, and has been with us,
and thou must give me freely up to him again, and he will support thee,
and take care of thee.`"
At another time, I being in deep distress of mind,
under the consideration of my great loss of so dear a companion,
if she should be removed, I asked her if she had not rather live with me a little longer,
if Providence saw meet.
She looked pleasantly upon me, and, after a little pause, said,
"`I have no desire nor will of my own.
I stand in the will of God.`"

At another time, under the sense of her great pain, she said,
"`I earnestly desire the Lord may release me whilst
I have strength and patience to bear my afflictions;
but I neither murmur nor repine.`"
Observing the sadness of my countenance, she said, "`Why should I not go now?
I can never go better.`"
I told her if Providence pleased to raise her again, she might be with me longer,
and be of service, and yet go well.
She readily answered, "`There may be danger in that; I am now ready.`"
At another time I told her, when bemoaning myself,
if the Lord should see meet to remove her from me at that time,
that I believed he would receive her into the mansions of glory.
She replied and said, "`I never doubt that.
I trust through Christ to be received into the arms of eternal bliss, for I am in peace,
and perfectly easy.`"
At another time she looked upon me, and said, "`The Lord gave me to thee,
and thou must give me up to him again.`"

Toward the latter part of her illness, being in great pain,
and observing the concern I was in for her, she said, "`My dear,
I am afraid thou holdest me.`"
I answered, "`No; I have freely given thee up, and stand resigned in the will of God.`"
She looked pleasantly upon me, and replied, "`That is very good in thee.`"
Afterwards, her affliction and pain being very great and heavy upon her,
she prayed fervently, and said,
"`Lord be pleased to grant me a little ease before I go hence,
and be seen of men no more, no more, no more.`"
And the Lord was pleased to answer her fervent supplication;
for the day before her departure, all pain and affliction seemed to be removed,
and she continued quiet and easy, in a still, sweet frame of mind.

Although she spoke not much during that time, which could be perfectly heard,
yet she remained very sensible,
and her sweet and lively breathings plainly declared she
continued in inward prayer and praises to the Lord,
her lips often moving;
and sometimes expressions were heard tending to signify the full assurance
she had of an inheritance in eternal felicity and glory amongst the just.
Many more precious and weighty expressions she dropped during her illness,
which the distress of my mind prevented me from remembering perfectly.

About the fifth hour in the evening, being the Fifth-day of the week,
and the 2nd of the Ninth month, 1738, she sweetly finished her course,
and went away like an innocent lamb;
and notwithstanding the great affliction and pain
she underwent for seven days and seven nights,
that brightness and innocency which truth had impressed,
remained on her countenance when the soul was released,
and had taken its flight into the regions of bliss and glory.
She was aged about forty-nine years, and a minister upwards of thirty years.

She was endowed with many eminent gifts and qualifications; an able minister,
rightly dividing the word of truth through that wisdom received from God,
which proved effectual to the convincing of divers,
and the edifying and reaching of many.
She was zealous for the cause of God, and of a discerning spirit and good understanding,
so that the enemies of truth could not stand before her, for her bow abode in strength,
and her arrows were often carried to the mark, and were sharp against undue liberty,
deceit, and the works and workers of unrighteousness.
She dearly loved the children of the light,
and sincerely sympathized with such in their afflictions
who were seeking the way to Zion,
and often had a word of comfort to them.

Her heart and house were always open, according to the example of her pious parents,
to receive the ambassadors of Christ, remembering what he said,
"`Whosoever shall give to drink unto one of these little ones a cup of cold water only,
in the name of a disciple, verily I say unto you, he shall in no wise lose his reward.`"
And likewise what he told his disciples, "`Verily, verily I say unto you,
he that receiveth whomsoever I send, receiveth me; and he that receiveth me,
receiveth him that sent me.`"
Her delight was in the company of those who laboured for the promotion of the gospel,
and, through a good degree of experience,
she had sometimes a word of advice and encouragement to such.

She was a loving and affectionate wife, and the gift of God to me,
and as such I always prized her; a help-meet indeed both in prosperity and adversity,
a steady and cheerful companion in all the afflictions and trials which attended us,
and a true and faithful yokefellow in all our services in the church.
Being ever one in spirit, we became one in faith and practice,
in discerning and judgment, and our concern and labour was the same,
which nearly united us, and a life of comfort and satisfaction we lived;
our souls in the nearest union, delighting in each other,
and the love and presence of God,
wherewith we were often favoured in our private retirements, sweetened every bitter cup,
and made our passage easy and pleasant to us.

But, alas! what shall I say; the Lord, who is all-wise,
and only knows what is best for us, hath called her hence,
who is worthy to do whatsoever he sees meet.
Therefore, in humble submission to his will who gave, and hath taken away, as knowing,
though it is my loss, it is her everlasting gain, I rest,
and can in sincerity and truth bless his name who is worthy forever.

[.signed-section-signature]
John Bell

--

On the 7th day of the month aforesaid, her body was accompanied from our dwelling-house,
at Bromley, to the meetinghouse in Gracechurch-street, London, whence,
after a solemn meeting, many being affected with the removal of so near a friend,
it was carried to Friends`' burying-ground near Bunhill-fields, and buried by her mother,
according to her desire.

[quote.scripture, , Psa. 116:15]
____
Precious in the sight of the Lord, is the death of his saints.
____

[.asterism]
'''

JENNET STOW was a pious young woman,
who lived within the compass of Settle monthly meeting, in the county of York.
She greatly feared the Lord, and remembered her Creator in the days of her youth,
and was of those who joined in with the visitation
of truth in her young and blooming years,
and gave up her name to serve the Lord,
who was graciously pleased in his wisdom and goodness to give her
a dispensation of the gospel of glad tidings to preach.
Being devoted in heart to answer the Lord`'s requirings,
she laboured faithfully according to the ability he gave,
and visited the churches of Christ in divers parts of England, Scotland, and Ireland,
and was made a serviceable instrument in the Lord`'s
hand for the comfort and edification of his people,
where her lot was cast.

She was diligent in the discharge of her duty,
whilst health and strength were afforded to her;
she faithfully laboured in word and doctrine, and improved the talents bestowed upon her,
until infirmity and bodily weakness laid hold of her,
and rendered her in a great degree unfit for public service.
By the thankful and affecting expressions, which herein follow,
may be plainly seen the sincerity and integrity of her humble mind,
and her great love to God, and fervent concern for the cause of truth,
and likewise the blessed reward of peace and comfort she enjoyed,
and the assurance and evidence she had of her well-being,
near the finishing of her testimony and the conclusion of her time here.

Being weakly in body, and apprehending she drew near her end, she expressed herself thus,
viz., "`It is a brave thing to live near the Lord,
for I feel his goodness near at this very season, which warms my heart;
blessed be his holy name.
My heart is full of love.
Lord, let me live here, and do what thou wilt with my body.
Oh!
I feel a great deal of peace in my soul.
Lord, thou hast answered my cries, notwithstanding thou hast tried me every way.
I feel thou wilt carry me on to the end, and then all tears will be wiped away,
all sorrowing will be over.
Then it will be well with me; glory, glory, to thy heavenly name.`"

Then she lay singing praises to God for some times
and began to say again,`" Blessed be his holy name;
I feel as the house of Saul grows weaker and weaker,
the house of David grows stronger and stronger; though I can scarcely lift up a finger,
yet I feel myself strong in the Lord.
Lord, thou hast turned me every way: thou hast made me what thou wouldst have me to be,
praised be thy holy name, that I am yet alive to make mention of thy name.`"
Then she prayed for the family, and desired of the Lord,
that the offspring thereof might grow in the truth; and said, "`Lord,
thou hast put a song in my mouth; I can sing praises to thy holy name.`"

People, not of our profession, coming in, she exhorted them to live in the fear of God,
that they might die in his favour.
She said, "`Maybe you will say, I am mad, +++[+++or]
she is light-witted.
So they said of our Saviour, but I must tell you, if you will not hear now,
you will one day remember what I say.
Oh! it is a brave thing to have oil in our lamps,
and our lamps trimmed when the bridegroom cometh,
that we may be ready to enter into the chamber with him.
Oh! glory to God.
I am ready, come when thou pleasest, at midnight or cock-crow;
glory to God forever.

"`These few lines come in true love
to all that may see them when I am gone to my long home,
as indeed I do not expect to be long or many days,
because I feel so many distempers to attend this poor house of clay.
Glad I am, that it hath pleased the Lord to work upon my heart in the flower of my age,
and hath made me willing to serve him in the days of my youth,
so that I was made to forsake all that was near and dear to me,
and fully to give up and follow the Lord wheresoever he was pleased to draw me.
And now I find abundance of peace in it,
and an answer of well-done returned into my bosom,
which is great comfort to me on a sick bed, which is likely to prove a dying bed.
I find abundance of peace returned into my travailing soul,
who hath often gone mourning on my way with my hands upon my loins.
And although I have gone on my way weeping, yet I shall return with joy to Zion,
with joy and songs of deliverance in my mouth,
praising the Lord who hath been my rock in every time of trial.
I have fled thither and have found safety.
Blessed are they who are found building upon him.
These are they who know whither to fly when the tempest beateth, and the rain descendeth.
They trust not in the arm of flesh, but they depend upon the Lord, who is a sure rock,
and the righteous fled thither, and found safety.
As one that hath been concerned for the welfare of souls for some years,
that all would prize their time while they have it,
and not slight the day of their visitation, for it may be,
such as are now in being may not live to see another day.

"`I can truly say, it hath been a concern upon my mind for some years,
if it pleased the Lord to order it that I lived so long,
as that a trying day might come upon this nation, that I might live so,
as to be sheltered under the Lord`'s wing.
For indeed it is those who are found labouring in the summer
time who have something to feed upon when winter approaches.
Therefore I desire that I may prevail with you,
as one that desireth the welfare of souls;
let nothing in this world deprive you of the precious enjoyment of truth.
Oh! it is lovely in the eyes of a remnant, and more desirable than all visible things.
I can truly say, that truth is as precious in my eyes this day, as ever it was,
so that I can say, that the Lord is my portion, and the lot of my inheritance.
In this long time of weakness I feel the Lord to be near,
and he beareth up the spirit of my mind, glory be to his name,
for he beareth up his children in a trying time,
who have been made willing to confess him before men;
those are they whom he will not deny before his Father which is in heaven.
Although you have been as the off-scouring of the world, be not discouraged,
for the Lord is on his way, and it is my faith to believe,
that the Lord will get himself a name, and his name will become famous in Israel.
Therefore be not discouraged, but go on in the name of the Lord.
Although you may think yourselves weak,
yet the Lord will be strength in the midst of weakness.
I speak by good experience, blessed be the name of the Lord for it.

"`I have often thought when it pleased the Lord to draw my mind to visit this nation,
Scotland, and Ireland, then I said, Lord, I am weak, very despicable in the eyes of men,
how shall I appear before them?
I can truly say, that it was the word of the Lord that ran through me.
Be not afraid, for though thou art weak, yet I am strong,
and I will make thee as a trumpet in my hand, which shall give a certain sound.
Blessed be the Lord, who hath fulfilled his promise not only to my comfort,
but to the satisfaction of others, who have not gone under the name of Quakers,
and blessed be his name for it, for it is the Lord`'s doing and not my own,
and he shall have the praise of it.
It belongeth not to man or woman, for we are but instruments in the hand of the Lord,
and of ourselves can do nothing that is good: farewell.`"

N+++.+++ B.--I presume the foregoing expressions of this Friend, in her illness,
were committed to writing, owned by her, and her name put to them before her departure.

She died at the house of William Young, of Droinfield, in Derbyshire, of a consumption,
in the year 1702, aged about thirty years,
and was buried in Friends`' burying-ground there.

[.embedded-content-document.testimony]
--

[.blurb]
=== Doctor Heathcot`'s testimony, concerning Jennet Stow, who was her physician, and attended her in her illness.

When first I beheld that holy woman who left this legacy behind her,
I thought I never saw so heavenly an image.
Her eyes seemed full of concern, but not for this world.
But what way soever her outward eyes looked,
I still thought that the eye of her mind was toward the door,
where her beloved was wont to come in.
And truly I have some reason to believe,
that he seldom or never knocked in the days that I knew her,
but she was ready to let him in without making many excuses,
and he that made her heart clean, delighted often to visit her.

The first time I cast my eye upon her was in a meeting,
and though she spoke no words in that meeting,
yet the very sight of her preached aloud to me.
I thought it a good meeting, that I met with her; her look was humble, serious, steady,
full of watchfulness, love and earnest longings,
and wrestling in the depth of patience for her Beloved, whose blessed presence,
and living enjoyment she often wanted, though favoured with it more than others,
as far as I could judge.
She lived in my house some months, and I thought myself highly favoured of the Lord,
that he was pleased to order it so.
The more I knew of her, the more I loved her, and the more I loved her,
the better I was pleased, for I found it never did me any harm,
being a love not of my own, but of the Lord`'s begetting,
for whose sake alone we loved one another.

In meetings she was valiant to fetch water for others.
Her dwelling was deep,
and the water she brought up was living to all whose senses were lively.
The sound of her voice was beyond all the music I ever heard,
and the least sound that dropped from her in a meeting, with words,
or if only a sigh or sound of any sort,
I thought it always brought my mind nearer to the Lord,
from whence everything of hers had its sweetness.
When she had not the immediate sense of this power, she was less than others,
having little or no life but it, and being as dead to everything else, very despicable,
to those whose life and delight are in this world,
unacquainted with this secret life hid with Christ in God.

A true disciple she was, denied herself, took up and carried her daily cross,
and followed him who hath bid us all do so, if we will be his disciples.
She hated sin, pitied sinners,
and had a mantle of love to cast over the least that
belonged to or looked towards her Master`'s family.
I am loth to say she was pure gold, yet never saw anything more like it;
for being oft put into the fire, she was more refined.
Her life grew stronger as her body decayed, that life which death hath no power over.
Though her pains were great and long,
so was her patience and her strength to bear wonderful, as well it might be,
being in and from the Almighty.
I am not sorry that she is gone, nor that I am left;
but may my life and latter end be like hers, then I know, in life or death,
happy shall I be, and the same happiness I desire for all mankind.

[.signed-section-signature]
Gilbert Heathcot, M. D.

--

[.asterism]
'''

ABRAHAM ANTHONY, of Rhode Island, in America, and companion to William Wilkinson,
of New England, in a visit to Friends in this nation,
was visited with sickness at the house of Roger Dickenson, of Whitby, in Yorkshire.
His patience and quietness, in the time of his greatest affliction of body,
was admirable, with a free resignation to the will of God, saying, "`If I may live,
I am willing; but if I must die, the will of the Lord be done:`" often praising God,
and many times expressed his great satisfaction that it had pleased
the Lord to cast his lot among friends in that place.

The day before he died, several Friends standing about him, he said, "`Friends,
stand fast in the Lord, and bear a faithful testimony for God in your day,
and stand fast in the truth.
What signifies this world, or the riches of it?
They are not to be valued, for the love of the Lord is above all.
Be weighty in your spirits,
and watchful and fervent in that great duty of prayer
when you approach before the Almighty Jehovah.
It is a dreadful thing to appear before the Lord unprepared,
for the Lord will be terrible to the wicked.
Israel is to dwell alone, and not to be numbered among the nations.
And you elders, be ye faithful.
I am raised up beyond my expectation to exhort you elders to faithfulness,
though but young to many of you, and the least in mine own eyes,
yet strong in the Lord my God.
Friends, I did not leave my own country in my own will, or in my own strength,
or in my own time.`"
Then he said, "`O Lord, I love thee more than wine:`" and lifting up his hands, he said,
"`O! the joys of heaven, glory to the Father, and the Son, as it was in the beginning,
so be it world without end.
Amen, amen, amen.`"

Several other good expressions he uttered during the time of his sickness,
which are not here inserted,
but were much comfort and satisfaction to those who were often with him,
and a sealed evidence on their spirits that he is gone to rest with the righteous,
in that kingdom of peace which God has prepared for
all them that love our Lord Jesus Christ,
where the spirits of the just made perfect do sing praises, hallelujahs,
and hosannas to him that lives on high, who is God over all, worthy of all glory, honour,
and praise, forever.
Amen.

He was taken ill the second day of the First month, 1713,
and departed this life in peace with the Lord on the 13th, about four in the morning,
and was buried in Friends`' burying ground at Whitby, on the 14th,
about four in the afternoon, being the First-day of the week;
aged about thirty-one years.
