== Chapter 4

[.chapter-synopsis]
* Mary Dowden
* Peter Fearon
* Jane Fearon
* Sarah Stephenson
* Margaret Stones
* Hannah Hill
* Isabella Gerard
* William Blundon

MARY DOWDEN, of Wandsworth, in Surry,
was daughter of Christopher Grainger and Mary his wife, of the liberty of Westminster.
She was born about the twentieth day of the Sixth month, 1646,
and had a liberal education,
and when young was much taken with the gay fopperies of the times,
and although she was not guilty of gross enormities,
the Lord was pleased to reach to her and bring her through judgment,
in order to redeem her from the evils of the world.

As she gave way to his workings upon her own heart,
it pleased the Almighty to favour her with further manifestations of his love and light,
whereby she came to see her state and condition as it really was in the sight of God;
and as she became obedient, love and light increased,
and she was brought to know where he feeds his flock,
and causes them to rest at noon-day.
During the time she was under the work and operation of
the divine power and Spirit of God in her own heart,
she had many outward troubles and trials to pass through, in particular,
when she was convinced of the blessed truth, about the year 1675.
Her husband, Robert Archer, who died about the year 1688,
showed a very great aversion thereto,
and would often express himself in very harsh terms on that occasion,
though otherwise a very good husband,
which made it more difficult for her to make open profession,
but yet she was preserved in the truth,
and lived to the end of her days an ornament to her Christian profession.

She was married in the year 1697, to John Dowden, of Cranbrook, in the county of Kent,
one of her own persuasion, who departed this life in the year 1701,
from which time she continued a widow.
She was a woman of extensive charity, and very serviceable among her neighbours,
relations, and friends, in affairs both religious and civil, according to her ability,
accounting her outward substance the Lord`'s, and she his steward,
which was so impressed upon her mind,
that when she spoke of it she generally expressed herself thus:
"`The Lord hath lent me;`" and instead of saying, "`I will give,`" she would say,
"`I will hand;`" and indeed it would far exceed the intended account,
just to hint the several branches of her good conduct.

About the beginning of the Sixth month, 1734,
inclining to make some alteration in her will, she sent for a kinsman,
to whom she communicated her mind on that head,
and desired one might be drawn according to her directions; which being done,
and she taken ill, sent for him again, who came with it, and when it was executed,
she expressed her satisfaction, saying,
"`I wanted to settle the earthly matters for the best, and now I am easy.
I have nothing that lies as a burden or load on my mind.
My conscience is clear, I have nothing to do but to die.`"

At another time she said, "`I long to be with Christ.
Oh! how I am straitened till this be accomplished:`" adding,
"`Oh! how the people called Quakers run out in dress,
and are altered from what they were in days past.
Oh! this world, I am weary of it.`"
She often admired the goodness of God in his providential care over her,
both temporally and spiritually; and advised all about her to keep low in their minds,
and not to let in a worldly exalted spirit.
To her kinsman, taking his leave of her, who said, "`The Lord bless thee,
dear aunt;`" she answered, "`Child, he does bless me, he does bless me.`"
She often desired stillness and to be alone.
To her kinsman`'s wife, she said, "`Child, keep to meetings.`"

At one time, when she was in an agony, she desired to die very quickly,
but catching her words, she paused a little, and then said in a solemn manner,
"`Not my will, but thine be done;`" and she continued in a heavenly frame of mind.
Her kinsman asking her how it was with her, as to her inward condition,
after a short pause, she answered, "`Strong in the Lord,
and steadfast in the faith;`" and he taking leave of her, she said,
"`The Lord I hope will bless thee, and my last love is to all, every body,
all the world.`"
She continued in great pain until the 5th day of the Seventh month, 1734,
and about six in the evening, she fell asleep, departing without sigh or groan,
aged eighty-five years and upwards, leaving a sweet savour behind her,
by her holy life and godly conversation.

Her corpse was carried from her own house, to Friends`' meetinghouse at Wansworth,
attended by many friends and relations; and after a solid meeting,
wherein divers living testimonies were borne to the truth,
was interred in a solemn manner in Friends`' burying-ground there,
on the eighth day of the aforesaid month.

[.asterism]
'''

PETER FEARON, of Sheaton, in the county of Cumberland, was born at Great Broughton,
in the said county, in the year 1651, and educated in the way of the church of England.
About the fourteenth year of his age,
he was bound apprentice to our worthy friend John Banks,
and in the time of his apprenticeship he received the blessed truth;
and as he grew in the life and power thereof,
it became his concern to bear a public testimony to the virtue and excellency of it.

As he grew in the ministry, his heart was enlarged,
and he travelled in the service of the gospel in most parts of this nation,
and visited Friends in Scotland and Ireland several times.
In company with our worthy friend James Dickenson, he also visited Friends in Holland,
and divers parts of Germany, in which places he had good service,
being skilful in dividing the word aright, sharp against the hypocrites and rebellious,
yet tender to the mourners and disconsolate.
He was an able minister, sound in doctrine, convincing to gainsayers,
confirming and edifying to the churches; very serviceable in meetings for discipline,
and zealously concerned for promoting good order therein,
being particularly gifted for that excellent work.

He was a diligent attender of meetings for the worship of God,
and also those for discipline in his own meetings at home, and of good service,
though sharp against opposite spirits that withstood the truth.
He was a patient sufferer, and bore a faithful testimony against the payment of tithes,
and was true to the other branches of our Christian testimony;
free and open-hearted to entertain Friends who travelled for the service of the gospel;
a kind and loving husband, and his godly conversation adorned his ministry.
He was tender and loving to those who were young,
in whom he perceived a concern for the promotion of truth,
that it may be justly said of him, he was not only a faithful elder in our Israel,
but also a tender father in the church of Christ.

In the latter part of his time he grew infirm, and weak in body,
yet of sound mind and memory to the last.
A little before his departure,
he said he was glad he had got so far through the world unspotted,
and that he had fought a good fight and kept the faith,
and that there was a crown laid up for him.
Thus this good man had cause to rejoice when he was near to leave this world.
He finished his course and testimony the 14th day of the Eleventh month, 1734,
and on the 17th day of the said month his body was accompanied by a great number
of Friends and sober neighbours to Friends`' burying-ground in Cockermouth,
in the said county, and there decently interred,
where divers living testimonies were borne to the truth.
Although the removal of so serviceable a member is the church`'s great loss,
we make no doubt but he is entered into that glorious rest and kingdom which
is prepared for all them that faithfully serve the Lord in their generation.
He was aged eighty-three years, and a minister about fifty-six years.

[.asterism]
'''

A short testimony concerning our ancient and worthy friend JANE FEARON.

JANE FEARON, wife of the aforesaid Peter Fearon, was born of religious parents,
who lived and died in the truth, whose care was to educate her in the way thereof.

She was favoured with the love of God in her young years,
and came under the baptism of his Holy Spirit,
by which she was made a member of the true church.
Afterwards she came to witness the more large and powerful
effusions of the divine grace or Holy Spirit of God,
in order to proclaim the everlasting gospel.

Thus gifted and prepared for the ministry, she was sent forth,
and made to run to and fro in the earth to discharge
that trust which God had committed to her.
She was moved and engaged in mind to go and visit the Isle of Man, along with a friend,
where they both suffered imprisonment for the testimony`'s sake.
After which she travelled into Scotland, and visited friends in that nation;
and shortly after was engaged to travel into Wales,
and from thence through many counties in the west of England;
in all which travels she was wonderfully borne up,
and fitted for the service she was called unto.

Soon after she returned from these travels,
she was married to our dear and worthy friend Peter Fearon:
she still retained her integrity, and was zealous for the truth, and the cause thereof,
often bearing a living and powerful testimony,
declaring the universality of God`'s love to all the children of men,
directing them to that inward means, the promise of God unto all succeeding ages,
by the mediation and merits of Jesus Christ our Lord and Saviour, viz.,
the spirit of truth, which is to lead us into all truth, or as the apostle expresseth it,
"`Christ in you the hope of glory.`"
After this she travelled into Ireland and Scotland several times,
and met with a great many besetments and difficulties
in her pilgrimage through this life,
too tedious here to mention.
Through all which travels and services in the truth, she was preserved in a clean, pure,
and exemplary conduct; so that we may truly say, her conversation adorned her profession.

She was always very diligent in attending meetings,
even when by the infirmities of age it could not be expected.
She was endowed with a capacity beyond many, ready in discerning, of a mature judgment,
and might truly be esteemed a mother in Israel: a loving wife, an affectionate mother,
a kind neighbour, and ready to do good to all.
Although it be our loss to part with so valuable a friend,
we are fully satisfied it is her everlasting gain,
being gone beyond the reach of all disturbance, where the wicked cease from troubling,
where all sorrows and tears are wiped away,
and the soul received into eternal tranquillity, peace, and joy in the Holy Ghost.

She calmly departed this life the 18th day of the Ninth month, 1737,
in the eighty-second year of her age; having been nearly fifty years a minister;
and was buried the 21st day of the same month,
in Friends`' burying-ground at Cockermouth, in Cumberland,
being attended to her grave by many friends and others.

None of the dying sayings of the aforesaid worthy ancient friend being come to my hand,
that the memory of so worthy a woman,
and faithful servant and minister of Christ might
be revived and perpetuated to generations to come,
on deliberate consideration, I concluded the foregoing brief testimony concerning her,
well deserved a place in this collection.
During the long and intimate acquaintance I had with her,
I received great benefit and advantage both by her ministry and godly conversation,
which were truly informing and edifying to me,
whensoever it happened that I was favoured with her company.

It may be truly said, she was not only a living minister in the church of Christ,
but a nursing mother where she saw any of the youth under
the work of the divine power and preparing hand of the Almighty,
in order to make them fit vessels for his use;
for which service she was particularly gifted and qualified,
and made an instrument of help and great good to many.
In confirmation whereof, and which induced me the more to publish it,
that by the ordering and wisdom of Providence, she was at the first meeting of Friends,
which it was my lot, more by accident than design, to drop into,
and was the first minister I ever heard who preached up life and salvation,
and perfect redemption out of the state of the fall by Jesus Christ our Lord,
and the sufficiency of that divine principle that
comes by him to effect this great and necessary work,
and bore testimony to the light of Christ in the heart,
the immediate means whereby all things reprovable are made manifest.

This doctrine was suitably adapted to my condition at that time,
I having before received and believed in that inward
and divine principle she bore testimony to,
and known something of the work of it in my own heart; but till that time,
in all my searchings among professors of divers names,
I never met with any who held it to be sufficient to save from all sin,
whilst we are clothed with these mortal bodies.
For I having never had any conversation on religious subjects with any Friend,
nor read any of their writings, was wholly ignorant of their principles.
I ever after highly esteemed and valued her as a messenger of glad tidings,
and as one who bore testimony to the means by which the captives might be set at liberty,
and be rendered capable of answering the end of their creation, viz.,
to glorify that God who made them, and show forth his praise,
whose service she faithfully answered during her
long pilgrimage and course through this world.

J+++.+++ Bell.

[.asterism]
'''

SARAH STEPHENSON, daughter of Daniel Stephenson, and Hannah his wife, of Kendal,
in the county of Westmoreland, was a child of a tender and weak constitution,
many times out of health, yet, when any way better, of a bright and cheerful countenance.
During the whole time of her illness, she had a great thought of a future state,
and was often heard to pray to the Lord with great fervency of spirit,
insomuch that several times those about her were affected with a sense of divine goodness.
She would often be speaking of her going to her brother John,
who died in his infancy some years before, and that she would go to him,
and much rather choose to die than live,
which she several times with great earnestness signified.
Her mother one time asked her what was the reason that she seemed so desirous to die,
telling her she had many privileges more than many poor children.
She replied, in a solid, weighty manner, "`If I die now I shall go to heaven,
but if I live longer, I know not how it may be with me.`"

At another time, when she saw her father under some trouble, she said, "`Dear father,
do not grieve for me, for I shall be happy.`"
Another time, when she perceived her mother weeping, she said,
"`Do not grudge my happiness, for I shall go to heaven.`"
The day before she died, her father asked her if she knew him; she replied, "`Yea,
she was likely to know her dear father;`" and perceiving him under some trouble,
she said, "`The Lord comfort thee.`"
Then her nurse inquiring what she would have, she replied, with a pleasing smile,
"`It is no matter for any natural food.`"
At another time a young man came to visit her, and asked her how she did;
after some silence, she returned this answer:
"`I am praying that I may be prepared for that holy place,
into which no unholy thing must enter.`"
The person hearing those words, and considering the frame of her mind,
it did so affect him, that it occasioned many tears.
A sober neighbour, a priest`'s wife, who several times came to see her,
and heard some of her expressions, turning to her mother, said,
"`You have great reason to be content,
to hear what a happy condition your child is in;`" the neighbour further added,
"`I never heard the like in all my life.`"

Much more of the same nature the child spoke, but they neglecting to write it down,
it cannot be so perfectly remembered.
This is written with earnest desires,
that those who are young in years may rightly consider
how short and uncertain their time may be here,
so that through divine assistance, timely preparation may be made,
that at the conclusion of time, we may have admittance into the heavenly kingdom,
into which no unclean thing must enter,
and of which we believe this young plant had full assurance.
She departed this life the 18th day of the Seventh month, 1736,
aged thirteen years and three months.

[.asterism]
'''

MARGARET STONES, wife of John Stones, of the city of York,
daughter of George Paine and Elizabeth his wife, was born at Littleport,
in the Isle of Ely, and county of Cambridge,
and had the privilege of a religious education, her mother being careful,
as she herself declared,
to instruct her children early to live in the fear and love of God,
who was graciously pleased to visit her and overcome her heart,
and to draw her to love him again, when about ten years of age,
for which she was humbly thankful to the end of her days.

And as through the gradual work of his grace and visitation of his love she became obedient,
she was prepared for service,
for about the nineteenth year of her age she was called into the work of the ministry,
in which she laboured faithfully, as she declared a little before her death, saying,
that she had been careful in serving the Lord in her known duty,
and had done what she could,
and had such peace as gave her reason to think it was acceptable.
She further said, that she might not fall short in that point,
whilst she was young and able,
she industriously worked with her hands to provide herself necessaries,
as much as might be;
in both which respects she expressed her great satisfaction when near her end.

During the time of her last illness,
she was divers times drawn forth in a very lively manner
to acknowledge the Lord`'s great love and favour to her,
at one time expressing herself in prayer to this effect: "`Oh!
Lord, thou hast been with me through many trials,
and in the various exercises I have met with in this life, thou hast been my support.
Thou wast also with me on the great ocean, and comforted me,
and those that were with me there at that time.
Thou mighty God of Jacob, I thankfully remember thy kindness,
thy fatherly care and tender dealings.
Oh! be pleased in thy mercy to draw the hearts of many after thee;
reach to the youth amongst us, the rising generation,
that they may become thine;`" with much more to that purpose.

Her heart being enlarged in the love of God,
she thankfully acknowledged his abundant mercy,
and that she was then a witness of his ancient power,
and that his holy arm was then her support,
which had been invisibly underneath to bear her up through the many besetments, straits,
and difficulties of her life;
frequently and earnestly begging that the Lord would be pleased
to bear her up still until she had finished her course,
which she was sensible was near at hand.
Whilst under her great affliction of body, which continued about thirteen weeks,
she was under an earnest care and concern of mind
for the youth among Friends in a particular manner,
and she besought the Lord on their account, and desired help for all in general,
that they might be brought home to him,
fervently recommending that impressions of love and virtue might be endeavoured
early to be made by those who have the education of the youth,
saying, "`Early impressions lasted long, and were not easily erased out.`"

She expressed her sorrow for those children who in their minority were corrupted
by such as should instruct them in that great Christian duty of love;
saying,
it was a pity that their tender age should be imposed upon
by those who should teach them love both to God and man,
and she feared the load of such would be too heavy for them,
but desired their hearts might be changed and turned unto God before it was too late,
and that both young and old might learn of Christ, the pure fountain of love,
in which she had been careful to walk.

Her affliction and great pain being heavy upon her, made the time seem long and tedious,
yet she often acknowledged the abundant mercy and kindness of God,
who had preserved her in the time of temptation,
and delivered her from the jaws of death,
and kept her alive to sound forth his praise near the finishing of her life;
and said she had nothing to do but to die.
The first day of the First month, 1739, she laid down her head in peace,
and is now at rest from her labours; aged about fifty-two years,
and a minister about thirty-three years.
Her body was buried in Friends`' burying-ground, in York, the 4th day of the same month.

[.asterism]
'''

HANNAH HILL, daughter of Richard Hill and Hannah his wife,
of Philadelphia in Pennsylvania, was a child of a very sober and courteous behaviour,
a pattern of piety, plainness, and obedience to parents,
and of a womanly and obliging temper to all, religiously inclined when very young,
and diligent in reading of the Holy Scriptures,
as appears by the following testimonies given concerning her.
On the 23rd day of the Fifth month, 1714, being the sixth day of the week,
she was seized with a violent fever and flux, which so increased upon her, that,
the third day following,
both herself and others present expected she would then have departed.
But the Lord was pleased to continue her a little longer to testify
of his goodness for the encouragement of the living;
for at this time she was in a deep travail of spirit about her future state,
and divers times would say, "`Am I prepared?
Am I prepared?
Oh! that I might die the death of the righteous,
and be numbered with them at the right hand!
Oh, Almighty God! prepare me for thy kingdom of glory.`"

She earnestly entreated those about her to help with their prayers,
that her passage might be made easy.
A friend present, being moved thereto, kneeled down and prayed; during which time,
notwithstanding her extreme pain, she lay still with great attention,
lifting up hands and eyes.
A little after, she said, "`Father, I shall die, and am now very willing.`"
After some time she said, "`O most glorious God, now give me patience, I beseech thee,
with humility to bear what it shall please thee to lay upon thy poor afflicted handmaid.`"
After this she entirely made death her choice, and would often say,
"`I had rather die and go to God, than continue in this world of trouble;`" adding,
"`When will the messenger come?
Oh! hasten thy messenger.`"

Then turning to her father, she said,
"`Oh! that I could launch away like a boat that sails,
so I would go to my dear brother who is gone to heaven
before me;`" desiring those present not to grieve;
saying, "`I am but going to a better place.`"
Doctor Owen coming to visit her, she prayed him to sit down by her, and said,
"`All the town knows thou art a good doctor,
but I knew from the beginning that I should die,
and that all your endeavours would signify nothing;`" and added,
"`The Lord hath hitherto given me patience, and I still pray to him for more,
that I may be enabled to hold out to the end, for my extremity of body is very great.`"

She earnestly requested her parents to give her up freely to the will of God, saying,
it would be better both for them and her so to do.
And when she thought she had prevailed, she said, "`Now I am easy in mind.`"
When some seemed to encourage her with hopes of recovery, she said,
"`Why is there so much ado about me who am but poor dust and ashes.
We are all but as clay, and must die.
I am going now, another next day, and so one after another the whole world passes away.`"
One taking leave of her said, "`I intend to see you again tomorrow;`" she replied,
"`Thou mayest see me, but I shall scarcely see thee any more,
though I will not be positive: God`'s will be done.`"

She would divers times say to her dear mother,
"`Art thou sorry I am going;`" and to others about her, "`Why are ye troubled and weep,
seeing I am but going to a better place;`"adding, "`Oh! that the messenger would come,
that my glass was run.`"
At another time she said, "`O my dear mother, I fear the Lord is displeased with me.`"
One answered, "`Dear child, why shouldst thou entertain such thoughts?`"
"`Because,`" said she, "`I am continued thus long to endure the extremity of body,
which none knows but myself, nor can any think how great my pains are.`"
But it pleased the Lord to remove her doubt, for afterwards she said to her father,
"`I think the Lord hath showed me I do not bear all this for myself only.
Glory be to his infinite name; there is nothing can be compared to him.`"
When the first day of the week came,
she asked if her mother intended to go to the meeting; who answered, "`No,
she could not leave her dear child in that condition.`"
Then she said, "`Let my cousins go,
for it may be the Lord will be displeased if all the family stay at home;`" adding,
"`not to look upon one another, but to wait upon God.`"

She would repeatedly say,
she was freely resigned and willing to submit to the will of God,
whether in life or death, and was frequent in prayer to the Almighty,
still humbly beseeching the Lord to grant her patience,
and divers times put up her supplications to him for living water,
and that it might spring up in her unto eternal life.
Not long before her departure, she said, "`Father,
the Lord hath assured me I shall be happy.`"
It was answered, "`that is comfortable indeed; "`Ay,`" replied she,
"`this is matter of joy and rejoicing can my soul say by living experience.`"

When she took her leave of her dear and only sister, and her cousin Lloyd Zachary,
whom she dearly loved, she expressed herself thus; "`Dear sister,
my desires are that thou mayest fear God, be dutiful to thy parents, love truth,
keep to meetings, and be an example of plainness.
Dear cousin, be a good boy, observe thy uncle`'s and aunt`'s advice,
and the Lord will bless thee, and they will regard thee as their own, and do for thee.`"
During the time of her illness, she often spoke of her funeral,
and desired that friends and others might be invited,
mentioning divers by name that were nonresidents,
and some strangers who were lately come into the country, lest they should be forgotten.
So she recommended her spirit to God, saying, "`Glory, glory,
glory;`" and as with the sound of an hymn, this innocent maid closed her eyes,
and expired as one falling into a sweet sleep, without sigh or groan.
She departed this life the 2nd day of the Sixth month, 1714,
aged eleven years and about three months.

An abridgement of _Thomas Chalkley`'s_ testimony concerning _Hannah Hill,_ junior.
"`There is something on my mind to write in memory of that dear innocent soul,
Hannah Hill, junior, who departed this life in the twelfth year of her age,
in peace with God, and in great love and unity with his people,
and in much assurance of her own eternal happiness.`"
I was well acquainted with this tender young maiden for several years before she died,
and I took good notice of her conversation,
which was bright and shining in that which is commendable in youth.
Oh! saith my soul, that the youth of our age, and this city, might follow her example.
She was a pattern of piety, plainness and obedience to parents,
and of a womanly and obliging temper to all.

It was my lot to be for some months a co-habiter in the family,
and I observed that she was always very dutiful to her parents,
loving to her friends and neighbours, and kind to the servants both white and black.
I also observed, that many times when other children were at play in the streets,
she would be either at her book or needle, at both which she was dexterous,
and it rather seemed a delight to her than a burden.
She had an extraordinary talent in reading the Holy Scriptures, and other good books,
in which she took much delight.
May the minds of young people be stirred up by her example to put the same in practice,
is my hearty desire.

This testimony I have to give concerning her, that she lived and died beloved,
and the loss of her is lamented by those who knew her.
One great virtue I may not omit mentioning,
which would be very becoming in Christians of riper years, viz.,
she would often sympathize with those who were in affliction, or under exercise,
of which I was a witness, which greatly affected my heart to consider,
that her years were so green and her soul so ripe.
May all who cast their eyes on these lines, say with the man of God of old,
'`Oh! that I had wings like a dove,
for then would I fly away and be at rest.`' Ps. 55:6.`"

An abridgement of _Griffith Owen`'s_ testimony concerning _Hannah Hill._
"`The Lord hath been pleased in his great love to give a gift or
manifestation of his Holy Spirit to the sons and daughters of men,
to show unto them the way to eternal happiness, and to help them to walk in it.
And although it is universally extended,
yet those who give up their hearts to obey and follow
the manifestations and requirings thereof,
do only find favour with God, and are good examples to mankind in their generation,
patterns of righteousness, meekness, humility, self-denial, patience, temperance,
godliness, brotherly kindness, and charity, which are fruits of the Holy Spirit.
These have evidently appeared in some of our age when young in years,
amongst whom may be recorded Hannah Hill, daughter of Richard Hill, and Hannah his wife,
of Philadelphia in Pennsylvania;
considering how she spent that short time the Lord was pleased to give her in this world;
her meek and godly behaviour from a child, her dutifulness to her parents,
her love and good will to all,
but especially to those who walked in obedience to the truth.

I knew her from a child, and I never beheld any airy, light,
indecent behaviour or expressions from her,
but her conversation was adorned with much gravity, modesty, meekness, and plainness.
I was several times with her when on her deathbed,
and was much tendered and comforted in a sense of the love and power of God that attended,
in which time she uttered many wise and heavenly expressions,
beyond what could be expected from one of her age.
I was made to say, it is the Lord`'s doing, and it is marvellous in my eyes.
What can be written can add nothing to the state and condition of the deceased,
whom the Lord, I believe, hath taken to himself,
to rest in the mansions of glory forever and ever.

It is for the sake of the living I write this,
and especially with a regard towards our young people,
for whom my secret cries and prayers are often put up to the Lord,
that he would be pleased to work upon their hearts,
as he did upon the heart of this maiden, a willingness to forsake the vanities, follies,
pride, high-mindedness, and the many evils which are in the world,
and that they might be brought to live godly lives,
and by an innocent and righteous conversation,
the work of regeneration might clearly appear in all their actions and behaviour,
that those who conversed with them, and beheld their good works,
coupled with the fear of God,
might have cause to acknowledge they are the seed whom the Lord hath blessed.`"

[.asterism]
'''

ISABELLA GERARD, daughter of Robert Gerard and Anne his wife, of Rotterdam, in Holland,
was a young woman of excellent parts, and modest and sober beyond many of her years.
She was religiously inclined from a child,
and took great delight in reading the Holy Scriptures,
and other books on religious subjects, and was obedient and affectionate to her parents,
who had carefully instructed her in the way of truth,
as professed by the people called Quakers.

She laboured under a consumption and asthma for some years,
which affliction she bore with great courage and patience.
Her distemper increasing very much some months before her death,
she would often say to her mother, "`Dear mother, if it were not for thee,
I should be content to leave this world, but thou wouldst miss me much.`"
She kept her chamber about two weeks before her end,
in which time she was very sweet in her spirit.
The day before her departure, she said to her mother, "`Dear mother,
let nothing keep thee away from me;`" having, as she told her mother afterwards,
a sense that her end was near.

About two hours before she departed, the servants who were with her,
perceiving some change, called her father and mother, they being gone to rest.
When they came to her, she said, "`Dear father and mother, I am dying,
and if you had been with me, I believe I should have died this night,
but I could not go without seeing you.`"
They being much affected, she said, "`Do not grieve nor weep.
Ye do not see me weep, I am well content to go; give me up, I shall be well.`"
She spoke several things to her father and mother in particular,
with great presence of mind, and of her brothers and sisters,
they being all from home at that time,
and desired her dear love might be remembered to them, and that they would fear the Lord;
and added, "`I hope you will have comfort of them that are left.`"

Her mother asked her if she would have any of her relations sent for; she answered, "`No,
I have thee and my father, and that is enough; and when I wanted you,
I had the company of my sweet Saviour.
Dear mother,
I cannot tell thee the sweetness I have had upon my spirit in this time of my last illness,
and some time before.
The Lord hath been with me in all my weakness, which hath been a great favour.
He hath preserved me from evil when the enemy would have drawn me into despair and murmuring,
because of the greatness of my oppression and weakness;
and in this last illness I have not so much as had
the least doubt on my mind of my future well-being;
is not that a great mercy?
I have laboured for content, and now I have got it; is not that a great favour?
Dear mother, although I love thee dearly,
and could have been contented to have lived a few years longer with you,
because I know you will grieve for me, yet I am content.`"

Her mother asked her if she had anything to say to some of her relations.
She answered, "`I fear there is little to be done with them,
but remember my dear love to them,
and I would have them remember that they do not know how soon it
may be their lot to be in the same condition as I am in.
Speaking of a kinswoman whom she thought too light and airy, she said,
"`What hard work will she find when she comes to
be as I am`" After that she was a little still,
desiring to lie in her mother`'s arms; but finding her oppression to increase,
she said to her mother,
"`Pray to the Lord that he would please to give me an easy passage.`"

Her mother answered, "`Dear child, I have desired it,
and I believe thou wilt have an easy passage.`"
Then she prayed with a loud voice to the Lord, that he would bless her father and mother,
and comfort them in their great affliction, and in all their afflictions,
and bless them in all their undertakings; and also for her brothers and sister;
and then said, "`Farewell, my dear father; farewell, my dear mother, farewell;
now I am going, speak no more to me.`"
And so, lying down on the bed,
she sweetly departed this life without either sigh or groan,
encountering the very agonies of death with uncommon courage and cheerfulness of mind;
and we are persuaded that she is entered into the joy of her Lord,
having run a short race, but a painful pilgrimage.
She died the 25th day of the Eighth month, 1727, aged nearly twenty-two years.
Her corpse was accompanied by her relations and friends
to the ground where Friends usually bury in Rotterdam,
and decently interred, the 28th day of the same month.

[.asterism]
'''

WILLIAM BLUNDON was born in the parish of Kingsclear, in the county of Southampton,
in the year 1655, and educated in the way of the Church of England.
Until about the twenty-eighth year of his age,
he lived according to the course of this world,
in the reigning vanities and sinful diversions of the times,
having little regard to religion, till about that time;
being visited with a lingering illness, which brought him low,
he began to consider how he should account for his misspent time.
Whereupon he in some measure reformed and left the Established Church,
and joined with those high professors, the Presbyterians,
but did not find that satisfaction he was in the pursuit of.
The cowardliness of their pastor, who for fear of persecution left his flock,
and the lifeless profession of his hearers,
discovered to him the foundation they were upon;
yet he remained in hopes to find something more certain and substantial;
and having heard of the people called Quakers,
he inclined to go to one of their meetings,
to see if he could find what his soul longed for.

Accordingly, he went to a meeting in a right disposition of mind, in great humility,
earnestly desiring of the Lord,
that if they were a people who did in truth enjoy
the sweet influence of his love and life,
that he might then be made a partaker with them.
And his cries were answered,
for in that meeting he was made sensible of the presence of the living God,
and found his heart livingly touched and broken in a sense of the goodness of the Lord;
and "`Oh!`" he hath been heard to say, "`let me never forget that day;
let me never forget the bowings down of my soul at that time.`"
We have good reason to believe he never did forget it;
for from that time forward he came constantly to Friends`' meetings, and,
by a circumspect conduct, approved himself a religious, solid, and good man; and,
as he said, through many trials within and without,
he at length arrived to solid peace of mind.

About the year 1710 he found it his duty sometimes
to bear testimony to the truth in our public meetings,
and being faithful therein, the Lord, who often chooseth the mean things of this world,
enlarged his gift, and made him an acceptable preacher of glad tidings to many.
In his ministry he was very plain, severe against pride, licentiousness,
and every evil way; but tender towards those in whom were good inclinations,
wherever he found them.
And as Paul advised Timothy to rebuke those that sinned, before all,
that others might beware; so this good man did, without respect of persons,
being neither to be awed by fear, nor biased by favour.

It seemed to be the delight of his soul to deliver
the whole counsel of God as revealed to him,
that he might be clear of the blood of all men;
and though some might be ready to account him their enemy for his plain dealing,
yet he thought it his duty to warn them, whether they would hear or forbear.
But to the living among us, he was witnessed to be a son of consolation, indeed,
and a waterer of the vineyard of God.
This was his life and delight, to enjoy the life of God in his own soul,
and to recommend it to others; and as he had felt the virtue of it,
he was therefore a zealous and faithful witness to it.
This was what he laboured to settle all upon,
that they might come to feel Christ by the power of his Spirit in their own hearts,
which might redeem them from all iniquity, and purify them to himself,
a peculiar people zealous of good works;
and the word of life hath often been witnessed to flow through him,
to the consolation and comfort of the church.

He continued fresh, green and living to the very last, and as he often said,
the guide of his younger years was the staff of his age.
In the time of his weakness,
he advised Friends that came to see him to keep to the truth,
and to hold it in the power of it,
that they might know it to keep them clean from the evils of the world,
and from the world`'s ways, fashions and spirit.
Some weeks before his death, a Friend, of the ministry, going to visit him,
found him in a sweet frame of mind,
and he expressed his desire of death rather than life, if it were the will of God;
and said, "`I have done all that such a poor old man as I can do.
I find nothing, but I am clear of all.
I have often spread my case before the Lord with earnest breathings to him,
that he would be pleased to show me if any thing stood in my way,
if any thing in me was contrary to his will,
and I find there is nothing laid to my charge; the great God speaks peace to me,
and his pure life is with me.`"

Then applying himself to the Friend, he said, "`Dear Friend,
take care of the friendship and love of this world to which thou art much exposed; and,
in thy ministry to others, oh! be careful and watchful, get down low, and abide low.
Take care of selfish thoughts and of selfish wisdom,
and open not thy mouth till the pure life is witnessed to arise in thee,
and then thou wilt answer and reach to the life in others,
and wilt enjoy peace in thy own mind.
Oh! keep to the pure sense of life,
and it will keep thee as it hath kept me all along
to this day:`" with more words to that purpose.

His mind seemed to be quite weaned from this world, and full of divine joy and comfort,
hoping to put off a weak and feeble body, and to be clothed with immortality,
that he might no longer, as through a glass, but face to face,
see and enjoy Him whom he loved and had served,
and join the glorious company and church of the first-born above,
and there rest with saints and angels, and the spirits of the just.
The faith and approaching prospect of this, as he said, made him contemn death, yea,
made him long for it, being no king of terrors to him,
but a welcome messenger of a joyful release, a summons from mortality to immortality,
from the infirmities, pains and watchfulness of this life,
to the joys and comfort of an endless one.

He was beloved of his neighbours for his just, humble, and inoffensive life;
and in the church was a bright example of primitive simplicity and truth.
Great was his love to God, and zeal for his name,
labouring much in his own and neighbouring meetings,
though he never travelled much abroad, to bring the young generation to a sense of truth,
and to encourage and establish the elders in it.
He was an heavenly-minded man; for though he was a sojourner here,
his mind and meditations were much in heaven,
so that with the apostle Paul he might well say, "`I am crucified with Christ,
nevertheless I live, yet not I but Christ liveth in me,
and the life which I now live in the flesh I live by the faith of the Son of God,
who loved me and gave himself for me.`" Gal. 2:20.

He was very diligent in attending meetings,
and careful to be exemplary in going one of the first to them;
and so diligently exercised in them to retire down out of self to the springings of life,
that sleepiness, even in others, was a very great burden to him;
and it is a plain evidence of a want of that exercise of spirit,
and sense of that divine presence, in which the great benefit of our meetings consists.
In his living he was very abstemious,
which good observation on a weak constitution led him to,
and by which his life was lengthened out to a great age.
He was, in brief, a man much devoted to God and his service, and who had,
by living under a sense of the virtue and power of the spirit of God,
gained a conquest over the world, the flesh and the devil,
and was renewed up in a good degree into the image of him that created him,
Col. 3:10; and it may be said of him, that he was a just man in his generation,
one who feared God, and eschewed evil, whose memory, as saith the wise man, is blessed.

His weakness and confinement were long,
but that part of it which seemed to usher in death, but of few days`' continuance.
He was patient and sensible to the last hour, and expressed his hope that he was going.
He died with ease, as if he had fallen asleep, and was taken from us in a good old age,
and hath left a sweet memorial behind him.
He departed this life the 19th day of the First month, 1740,
aged upwards of eighty-four years, and a minister about 29 years,
and was buried in Friends`' burying-ground at Baghurst the 23rd of the same month.

[.the-end]
END OF THE SEVENTH PART.
