== Chapter 2

[.chapter-synopsis]
* Robert Plumsted
* Lydia Lancaster
* William Backhouse
* Hannah Smith
* Mary Slater
* John Ransome
* Agnes Hall
* Sarah Marsden
* Samuel Watson
* Grace Chambers
* Alice Hall
* Boswell Middleton
* John Goodwin
* Catharine Burling

ROBERT PLUMSTED, of Gracechurch-street, London,
was in his youth addicted to gaiety and the delusive pleasures of this transitory world;
but was preserved out of the gross evils thereof.
About the twenty-eighth year of his age,
it pleased Divine Providence in great mercy to manifest to him,
that if he would obtain peace he must walk in the narrow path of self-denial.
Thus by adhering to the dictates of divine grace,
he was enabled to deny himself of the pleasures and pomps of this world,
take up his cross,
and in a good degree was brought into conformity to the leadings of truth.
Sometimes for about a year before his decease,
he appeared in a few words in our religious assemblies in a tender manner,
which was acceptable to Friends.

He was afflicted with a long and painful illness,
in which he had at times access to the throne of grace, and when reduced very low,
uttered these words distinctly: "`Lord! as thou hast continued me to this moment,
let me not depart without undoubted evidence of thy favour.`"
He quietly departed this life the 14th of the Seventh month, 1760,
at the Hot-Wells near Bristol, and his corpse being brought to London,
was interred the 23rd of the same, at Winchmore-hill, in Middlesex,
accompanied by many friends,
after a large and solemn meeting at Devonshire-house in London.
Aged thirty-six years.

[.asterism]
'''

LYDIA LANCASTER was the daughter of Thomas and Dorothy Rawlinson, of Graithwaite,
in the county of Lancaster, who both descended from families reputable among men;
and they both came among friends on the principle of convincement,
and were religiously concerned to instruct and example their children therein,
as the most precious of all blessings.
That powerful hand which alone can give the increase,
mercifully extended an excellent blessing to several of their children,
and particularly to this their daughter; and as it opened the heart of Lydia of old,
so it opened her`'s, to receive the heavenly message.
In her young years she became sensibly acquainted with the Lord,
and witnessed his gracious dealings with her, in order to redeem her to himself,
and make her a sanctified vessel to place his name in.

About the fourteenth year of her age,
she had a view of the will of Providence to engage her in the ministerial service;
under which concern she continued about ten years, growing in wisdom and experience,
that she might come forth in the right time, endued with proper qualifications.
In this time of deep travail and heavenly discipline,
she learned to say with the prophet Isaiah, "`He wakeneth me morning by morning,
he wakeneth mine ear to hear as the learned.`"

About the twenty-fourth year of her age, she came forth in a living, powerful testimony,
and grew therein.
The blessed author of all spiritual riches having abundantly
replenished her with the treasures of his kingdom,
she soon became an able dispenser thereof to the churches,
having a word in due season to divers states; and like the well-instructed scribe,
brought out of the treasures committed to her, things new and old.
And as she was eminently favoured by her great lord and master,
she became humbly devoted to his requirings.
When called forth into the various parts of his vineyard,
she freely gave up to spend and be spent for his name`'s sake.

She visited this nation, or the greatest part of it, several times;
Ireland and Scotland twice; also the continent of America;
in all which she was rendered instrumental to build up many in the most holy faith;
particularly in America she left many seals of her ministry,
both in the edification and help of those who were of the society,
and the convincement of others, gathering them to the great Shepherd of the flock.

Her openings into the mysteries of the kingdom were deep and instructive,
adapted to the state of those amongst whom she laboured;
close and with authority to the negligent and careless;
yet all her ministry was attended with that love
and tenderness which accompanied her lord and master,
who came to seek and to save that which was lost.
She was favoured with a most excellent utterance, her gesture awful, her voice solemn;
and all her demeanour in the exercise of her gift,
becoming the dignity of the gospel ministry.
She was signally favoured in supplication,
having near access in spirit to the throne of majesty and grace,
before whom she worshipped with calm rejoicing and awful reverence.

Thus, through a course of many years she retained her zeal and integrity,
and in her old age was strong in the power of an endless life.
Great indeed was her growth in religious experience, even to the stability of salvation,
and an assurance that she should never fall, yet accompanied with the deepest humility.
Filial love, which casts out fear, was the covering of her spirit,
and rested almost constantly upon her for several months before her removal.

About six weeks before her departure,
she thus expressed herself to a Friend she had favoured with an intimate acquaintance:
"`My natural strength is not so much impaired as to give
me reason to expect a sudden removal from this world;
but I feel so constantly day and night the virtuous life,
and my Father`'s holy presence is so constantly with me,
and I enjoy so much the spiritual communion and fellowship of saints,
as to give me an apprehension I am not far from mine
everlasting home;`" to which she sweetly added,
"`A glorious crown and everlasting song is before me.`"
The Friend to whom she thus expressed herself being deeply affected with
the sense of the over-shadowing of the Holy wing at that instant of time;
she further added, "`If the foretaste be so joyous,
what are the riches of the saints`' inheritance beyond the grave?`"

She was supported to labour in the gospel almost to the conclusion of her days,
having attended the funeral of an ancient Friend, William Backhouse, several miles off,
on the First-day of the week,
and preached the gospel in the demonstration of its own power;
and finished her course the Seventh-day following; and as she lived so she died,
in great favour with God and man, full of days, and full of peace.
She died at Lancaster the 30th of the Fifth month,
and was honourably interred in Friends`' burial-ground, the 1st of the Sixth month, 1761.
Aged about seventy-seven years, and a minister about fifty-three years.

[.asterism]
'''

WILLIAM BACKHOUSE was born in the year 1695, at Yealand, near Lancaster,
of religious parents.
His father dying when he was about two years old, a prisoner in Lancaster castle,
for his conscientious testimony against the payment of tithes,
the education of his children devolved solely on his mother,
who was religiously concerned in this duty, both by precept and example,
and it pleased divine Providence to bless her endeavours with success therein.
About the twenty-sixth year of his age he came forth in a public testimony,
and by faithful obedience to the requirings of the heavenly giver,
he witnessed an enlargement in his gift, and was an acceptable minister.

He visited the churches in most parts of this kingdom, Scotland, Ireland,
and the continent of America, much to the comfort and satisfaction of friends,
he being furnished with sufficient strength for the service of the day;
being sound in doctrine, tending to information, instruction, and edification;
exemplary in attending meetings both for worship and discipline,
in the latter of which he was highly serviceable, being a lover of peace, of a loving,
courteous disposition to all; an affectionate husband, a tender parent,
and kind neighbour, which procured the love and esteem of them all.

In his last sickness, being a gradual decay of nature,
it pleased the Almighty to favour him with many precious earnests of a blessed inheritance.
Divers friends who visited him, were in a good degree made sensible thereof.
In some of these opportunities he was engaged in a lively manner,
though in deep humility,
to commemorate the gracious dealings of the Lord with him in the course of his pilgrimage,
and thankfully to rejoice that he had laboured in his day
to perform what he believed was required of him;
and could make his appeal to his heavenly Master, saying,
"`Although I have had the world to struggle with
for the support and prudent provision for my family,
yet thou knowest, O Lord,
I have been more concerned for thy honour and the good of souls,
than for any other considerations.`"

Though greatly blessed in his nearest connections of life,
yet being weaned from this world and its enjoyments,
he waited with great patience and resignation for his dissolution.
He departed this life the 21st of the Fifth month, 1761,
and was buried at Yealand the 24th of the same.
Aged sixty-six: a minister above forty years.

[.asterism]
'''

HANNAH SMITH, wife of John Smith, of Philadelphia,
was the daughter of James and Sarah Logan,
and born there on the 21st of the Twelfth month,
1719-20. By the care of her parents she was in a great measure
preserved from the levities incident to early youth,
and by opportunities of improvement afterwards,
she acquired such qualifications as gained her much respect and esteem.
Though the affluent situation in which her parents were placed,
yielded flattering prospects of the ease and gaiety of the world,
the durable riches of true religion appeared to her a treasure of much more consequence,
and not to be relinquished for shadows and delights that die in the enjoyment.

Thus at a period when the slippery paths of vanity in a succession of increasing allurements,
are apt to ensnare youthful minds,
it pleased the Lord to bless her endeavours against
the temptations of vain and unprofitable company,
and to strengthen her love to inward retirement.
Having tasted of the visitation of divine love to her soul,
she saw it to be the pearl of great price,
and that her all must go to purchase the field where it lay.
From that time forward there is reason to believe this purchase
became the principal business of her life,
and with great sincerity and ardour she laboured to have all those
disquieting affections silenced which arise from temporal objects,
and she was helped at times to know the breathing of her soul answered,
and was made to partake of the joys of God`'s salvation;
under which her care over her words and deportment was increased.

She continued to take suitable opportunities of retirement,
and for reading the Holy Scriptures; and in the relation of a child, wife, and mother,
was tenderly careful to fill up her place becoming those stations.
About the year 1756 she appeared +++[+++in the ministry of the gospel]
in a few words in much simplicity of heart and godly sincerity,
and was concerned in visiting Friends in their families,
and also accompanied some of her own sex to divers
large yearly meetings in the neighbouring provinces.
After her return to Philadelphia, which was half a year before her departure,
she continued to attend religious meetings with as much
diligence as the weakness of her constitution would admit,
and when there to clear herself of what she believed required of her.

During her last illness she told her husband several
times that she believed she should not recover;
and though her bodily pain at times was very sharp, she was favoured,
with an entire confidence in the mercy of God through Jesus Christ,
whom she found to be a refuge from storms, and a sure defence in the day of distress.
Another time, acquainting him, with great sweetness of spirit, of the state of her mind,
she said, "`Notwithstanding the close trials I undergo, my foundation remains sure,
and I have a hope, yea, an unshaken hope,
that there is a place of rest prepared for me.`"

At another time, mentioning the prospect of her change being near,
she entreated her husband to strive for resignation, "`for`' says she, "`I am easy,
I feel no guilt.`"
A few evenings before her decease, as her husband sat by her bedside,
she desired that her children and all about her might
keep as still and quiet as possible when she departed,
and after mentioning several other things relative thereto,
told her husband that she felt pardon and forgiveness for all omissions of duty;
and concluded this very affecting conversation with these words,
"`Oh the infinite lovingkindness of a merciful God,
who has made such a poor creature as I am so rich in faith and firm in hope,
that I shall be accepted of him.`"
She departed this life on the 19th,
and was decently interred on the 23rd of the Twelfth month, 1761;
aged about forty-one years.

[.asterism]
'''

MARY SLATER, late wife of William Slater, of Lothersdale, in Yorkshire,
was descended of honest parents, though her mother did not profess with us,
her father being after his marriage convinced of our principles.
Being of a very gay, sprightly temper,
she was soon carried away with the delusive vanities and pleasures which abound;
though often attended, when very young, with strong convictions.
These were stifled for a time by various scenes of dissipation and folly,
to which she had recourse, till the Father of mercies, by his good Spirit,
effectually reached her when in the full career of mirth,
being at a public evening entertainment of the neighbouring youth,
about the fifteenth year of her age.
This strong and humbling visitation, as she often expressed,
brought her to see the folly of such mirth and jollity,
being at that time attended with such an awful dread on her mind,
as made her willing to depart from these vain amusements,
having no longer pleasure in them.

She now began to see the situation she was in, and the need she had of saving help,
by which a secret hunger and thirst were begotten
in her after divine and substantial food,
which led her with diligence to attend the way of worship in which she had been educated;
but finding no true satisfaction or proper nourishment for her disconsolate panting soul,
she often returned from the place of worship in tears and great anxiety of mind.
She then went among the Baptists, in hopes of meeting what she so ardently desired after;
but, being here also disappointed, she was led to attend Friends`' meetings;
though till now she even abhorred the name, yet at length,
through divers close conflicts and probations,
she came to experience that divine comfort and consolation
which her soul had so longed for and laboured after.

The way of life and salvation being then pointed out to her,
she had soon to tell to others what the Lord had done for her soul; for,
about the seventeenth year of her age, she came forth in a public testimony;
and being faithful and diligent in the exercise of her gift,
she became an able minister of the word,
being freely given up to her great Master`'s service,
though often under great temporal inconveniences.
Her husband was never possessed of much of this world,
yet their house and hearts were open to entertain their friends with the best they had;
and it was often cause of humble thankfulness to her mind that,
notwithstanding their low beginning, they never wanted what was needful,
ever preferring the welfare of Zion before her chiefest joy.

She visited, several times, most parts of England, Scotland and Ireland,
in which her services were acceptable, and left lasting impressions on many minds;
her ministry being in the demonstration of truth, and in the power thereof.
She was fervent in prayer, being often favoured with near access to the throne of grace,
to the baptizing of the assemblies into an awful adoration of him who lives forever.

Thus through a variety of services she laboured faithfully,
as well in the discipline as ministry,
so that the memorial of her labours has left a sweet savour behind.
In private life, she was exemplary in conduct,
and in the near relation of wife and mother; in conversation innocently cheerful,
yet solid and savoury, which rendered her company very acceptable.

For some weeks before her death she was confined to her bed,
under such bodily affliction that she had not strength to say much
further than signifying her satisfaction at seeing Friends,
and her unity with them.
At one time she said to a friend who visited her, that she was very weak in body,
but the Lord was strong; adding that she was easy and had peace of mind,
her day`'s work being done.
There is no doubt but she has laid down her head in peace.
She departed this life the 3rd of the Third month, 1762, aged sixty-nine years,
and was interred the 7th of the same,
in Friends`' burial ground in Lothersdale aforesaid.

[.asterism]
'''

JOHN RANSOME, of Northwalshanm, in the county of Norfolk,
was a lively example of true piety,
and through a course of many years laboured for its promotion;
which he continued till illness deprived him of his faculties,
and by which means we are deprived of any expressions from him in his last illness.
That such an example should not be lost,
as an incitement to future generations to fill up every duty,
and be truly serviceable also in their day,
the following abstract of a testimony from the quarterly
meeting of Norfolk concerning him is here inserted,
viz:

"`He was educated in the profession of truth, and in his young and tender years,
reached by the extendings of divine love, and happily closing in therewith,
he soon gave ample proofs of its efficacy,
that as he grew in years he grew in the knowledge and obedience of truth.
He came forth in the ministry about the twenty-eighth year of his age.
Many were the precious gifts bestowed upon him,
and the testimony given him to bear was truly comfortable;
his openings deep and instructive,
and he became an instrument of singular benefit to many,
from a true sense that was given him of their states and conditions.

As an elder and overseer he was without rebuke:
his mind being filled with unbounded charity and love,
counsel and reproof were well received from him;
and as he felt deeply for the infirmities of all, so he exposed the failings of none.
Thus eminently covered with the spirit of healing,
he seldom met with an obstinacy able to withstand it.
He never designed offence to any, and if through misapprehension it was conceived,
he was unwearied in his application to remove it; strong in the truth,
yet for the sake of it, subject to the weakest; suffering all things,
and in condescension sacrificing every selfish consideration to their help.

He loved mankind in truth, and thus qualified,
he became a pattern in word and conversation, adorning the gospel he preached.
He was endued with a large share of natural understanding,
which being sanctified by the great and good hand that blessed him with it,
rendered him very successful in putting an end to
differences among his neighbours and friends.
In the nearest connections of life he was equally exemplary; being a tender,
loving husband, an indulgent parent, an affectionate relation,
and strictly regardful of every duty towards his servants,
his care over whom was attended with singularly good consequences.
In these and many other respects, the loss of him is sensibly felt by us;
but we firmly believe it is his eternal gain.
His services in the wholesome and necessary discipline
established in our society were very great,
both in monthly and quarterly meetings.

As he was exceedingly industrious in what he believed to be his duty,
so was he likewise in visiting the churches;
devoting much of his time and outward substance to that service,
more particularly in the last ten or twelve years of his life.
He constantly attended the service of the yearly meeting in London for many years;
the last time of his being there he was seized with
that illness which concluded his natural life;
but notwithstanding his indisposition,
he visited several large meetings in Hertfordshire, Essex, and Suffolk.
He got to his own dwelling-house at Northwalsham, the 20th of the Sixth month,
and departed this life the 2nd of the Seventh month, 1762,
in the fifty-second year of his age.
His body was interred on the 6th of the same, in Friends`' burial-ground there;
a very large concourse of friends and others attending the solemn occasion.`"

[.asterism]
'''

AGNES HALL, daughter of William and Dorothy Kidd, of Settle, in the county of York,
gave early tokens of a religious inclination and filial affection;
being very serviceable in her youth to her infirm mother, during her widowhood,
in bringing up a pretty numerous family of children, she being the eldest,
her father dying when she was about seventeen.
Her conduct may truly be said to have been exemplary in plainness, moderation,
and industry; in benevolence and unaffected piety; being of a meek and quiet disposition,
her words few and savoury, which made her company truly valuable.

About the thirty-seventh year of her age she had to preach the glad tidings of the gospel;
though not large or frequent for some years, yet was seasonable, sweet, and edifying,
much tending to encourage the youth to give up the prime of life to the service of truth;
having to acknowledge her thankfulness to the Almighty,
that he had wrought a willingness in her heart in her early days to bow to his yoke,
which she found by blessed experience to be easy, and his burden light.
She never travelled much in the work of the ministry,
but was a diligent attender of meetings near home,
and very serviceable in the management of the affairs of the church.

Her indisposition of body rendered her unable to get to meetings a year before she died.
When friends visited her, though she lamented her lonely situation,
and being deprived of getting to meetings,
yet she had at times to rejoice that she felt the great I AM to be near;
he that had been the stay of her youth, to be a staff to lean upon in old age,
and to bear up with patience, under great affliction of body,
in a lively hope and assurance of a resting-place amongst the righteous.

A friend visiting her a little before her death,
she was much affected with a sense of the great declension in the church,
and of many superfluities that were crept in,
which our ancient Friends had to take up their cross to,
and bear their testimony against, the thoughts whereof much discouraged her;
being convinced our principle remained the same,
and that we had no nearer way now to the fold of rest than they had.

About an hour before her death, several Friends visiting her, she being set up in bed,
in a lively frame of mind, expressed her great satisfaction in their company,
that she sensibly witnessed the goodwill of her heavenly Father to be near,
which she had valued all her life long.
Under the influence hereof she rejoiced and was comforted,
and was strongly engaged on the youths`' account (some young friends being present),
that they might choose truth for their portion,
and Jacob`'s God for the lot of their inheritance,
which far exceeded everything this transitory world would afford.

She was sorry she had not had more frequent opportunities of their company while she
had strength to express her warmth of desire for their growth in the best things,
that would stand them in stead when everything else would fail.
When they took their leave, she said she was glad of that opportunity;
and if she never saw them more, she hoped they should meet in a better place.
She was soon after got up in a chair,
where in a few minutes she quietly departed this life, on the 1st of the Eighth month,
1762.
Aged seventy-six years; and was decently interred in Friends`' burial-ground, at Settle,
the 4th of the same.

[.asterism]
'''

SARAH MARSDEN, wife of Caleb Marsden, of Highflatts,
within the compass of Pontefract monthly-meeting, was born in the year 1706,
and being favoured with a religious education,
and the visitations of truth in her young years,
by yielding obedience thereto she became a sober, grave, discreet young woman,
a diligent attender of meetings, and honestly labouring to improve her time therein.
About the year 1749, it pleased the Lord to call her into the work of the ministry,
which she in great fear and tenderness gave up to; and although never large in testimony,
yet she was plain, sound, and edifying, rather backward in her public appearances,
and afraid, as she said, to awake her beloved till he pleased.

But when she felt the holy fire burn, then she offered her gift,
and was careful when that abated to sit down in meetings,
where too many are intent on words.
She was a diligent labourer in spirit, her very countenance being awful and affecting,
and like the worthy elders and nobles of the people (Num. 21:18),
digging as with the staff the Lord had given her,
and sometimes broke forth in solemn supplication to the great Law-giver,
that the well of life might spring up,
which at times she was the happy instrument of effecting,
to the consolation of the right-minded.

She was naturally of an affable, peaceable disposition, an affectionate wife,
a tender mother,
and weightily concerned to train up her children
in the nurture and admonition of the Lord;
kind to her friends, charitable to the poor, and an example of humility,
self-denial and resignation to the divine will,
and also of industry and prudent management of the affairs of this life.
Her last illness was long and tedious,
which she endured with much patience and resignation; saying, "`My body is full of pain,
yea, more than I can well bear.
O the sad state of those in my weak condition, who want peace of mind!

But forever blessed be my God, who now on my sick-bed answers the desire of my mind,
in giving me an evidence of my peace with him,
having nothing to do but to bear with patience the painful
afflictions that are permitted to attend me.
I find it work enough to struggle with nature; one had need have nothing else to do.
My breathing and travail of soul hath often been to the Lord that
he would let me see my duty and give me strength to perform it.
If I had my time to spend over again, I know not that I could spend it much better.
I can truly say, I have never been too forward in my appearances in meetings,
and other things relating to the Society; but always in great fear,
which sometimes hath been so great that I have been too backward,
and hurt myself thereby.`"

To some friends present, she said, "`Dear friends, stand in your lots: fear not man;
come up in your proper places, and the God of peace will be with you,
and strengthen you to perform and come up in the way of your duty to him,
and one unto another;
and so you will be preserved in the pure love and unity of one spirit.`"
At another time a friend called to see her, to whom she said,
"`Thou and I have been very near one to another.
O my body is full of pain!
I am sometimes ready to say, Lord! what have I done?
I want to be eased and dissolved: my stay here seems very long,
at morning I wish for night, at night I long for morning; but yet blessed be my God,
I feel his hand underneath, and he bears up my spirit,
or I could not tell how to endure my affliction.`"

At another time, being very weak, she said to her husband and children,
"`At the time of my departure be as still as you can, and feel for yourselves,
and do not mourn to excess, for all will be well.
Do not mourn for me; but rather rejoice when I am delivered from these pains,
for my change will be a happy one.`"
One evening lying very still,
those who attended her thought she had been going to depart;
but after some time she opened her eyes, and seeing her relations standing by her,
she raised her voice in a surprising manner, and said, "`I am entirely sensible,
and behold you every one, and glad I am to depart in peace.`"
She took her solemn farewell of all present, in a very loving,
affecting and cheerful manner,
those present thinking the time of her departure had been very near;
but she continued some days longer, mostly lying in a still, quiet,
peaceable and resigned frame of mind, patiently waiting her dissolution.
Near her conclusion, her voice being very weak, she was heard to say,
"`O that my sweet Redeemer would come and take me to himself! do not hold me,
let me go freely.`"
She died the 8th of the Eighth month, 1762,
and was interred in Friends`' burial-ground at High-flatts, the 11th of the same;
aged fifty-six years.

[.asterism]
'''

SAMUEL WATSON, of Killconner, in the county of Carlow, in Ireland,
having been a bright and lively pattern of true religion and virtue,
in order that such an example should not be lost,
the following testimony given forth concerning him
is thought meet to be inserted in this collection,
viz.:

"`Our dear and well esteemed friend Samuel Watson, of Killconner,
in the county of Carlow, in Ireland,
succeeded his worthy and honourable father John Watson, of the same place,
not only in his outward possessions there,
but in a zealous concern for the testimony of truth, and support of its cause.
Blessed with the great advantage of a religious education,
and made livingly sensible in his childhood of the precious
influence of divine goodness extended to his soul,
he grew up in sobriety, circumspection, and in the favour of God and good men,
being preserved through the dangerous path of youth
from the evils that are in the world.

When a young man and introduced into meetings of discipline,
great was the holy fear that attended his mind therein,
and his ardent desire was that he might never say
or do anything against the cause of truth.
As this fear was happily kept to,
he not only found it to be a fountain of life to preserve him from the snares of death,
but experienced it to initiate him into the rudiments of true wisdom,
by which in process of time he had skill to rule well in the house of God.

Qualified and influenced by this wisdom,
he was not only of singular service in the monthly meeting to which he belonged,
hut of eminent and memorable use in the more general meetings of business, which,
while of ability of body, he attended with exemplary diligence, in this nation;
and was also much esteemed and well received by Friends in England for his visits there;
for it had pleased the Lord to endue him in a good measure
with the gifts and qualifications of an elder in his house,
and a father in the family.

Often under the fresh influence of the divine anointing,
he was enabled to drop living counsel, to the affecting and tendering of many hearts,
and to raise that life in meetings of discipline
which alone is the crown of all our religious assemblies.
Though sharp in reproof to those in general who trampled upon the testimony of truth,
or lived in a carnal security,
yet he greatly rejoiced to see the buddings forth of good desires in any of the youth,
and was a tender nursing father to such.

Strong and fervent were his desires that the youth amongst us,
and particularly his own children and their offspring,
might dedicate their hearts fully to the service of God,
that there might be a succession of faithful members
in the church whereof Christ is the head,
following the ancients in that self-denying path which they had walked in:
at times observing, that when Friends lived more retired and inward,
the revelation of the spirit and divine help was witnessed in a larger degree;
often desiring in his declining years,
when his natural strength and faculties gradually decayed,
that he might never survive the inward sense and
feeling of that which is the life of the soul:
also sorrowfully remarking, that some by grasping at the present visible enjoyments,
had left large possessions to their families; but their table had become a snare,
and to several there was left neither name nor memorial among us.

In religious visits to the families of Friends he was often
eminently favoured and opened in suitable counsel,
in an extraordinary manner; and indeed not only on these appointed occasions,
but in more private conference with those of his family and his friends,
it was apparent he dwelt near the fountain of divine sweetness,
for words of sweet savour, edification,
and tenderness would often at such times flow from him.

To conclude, he was a careful, affectionate father, husband, and friend,
helpful in a civil as well as a religious capacity amongst his neighbours,
and charitable to the poor.
He departed this life in peace, at his own house in Kilconner,
the 14th of the Fifth month, 1762,
and was interred in Friends`' burying-ground at Ballybrumhill,
in the county of Carlow aforesaid, the 17th of the same; aged seventy-six years.`"

[.asterism]
'''

GRACE CHAMBERS, an ancient and honourable Friend, of Kendall, in Westmoreland,
was born at Munckhelsden, in the county of Durham,
and while young was virtuously inclined, and when she grew up was of a strict,
exemplary life and conversation, remarkable for her plainness and simplicity of apparel,
manners, and deportment, endowed with a good understanding and benevolent disposition,
and exerted herself to the utmost of her power to be serviceable in her day.
This gained her an extensive acquaintance among Friends and others,
having occasionally free access to several families of distinction in her neighbourhood,
to whom her affectionate visits were acceptable and of service,
and from whom she met with that civil and courteous
behaviour which was due to one of her amiable qualities.

She had considerable skill in surgery, and in administering relief in many disorders,
which she did without fee or reward,
and was much devoted to visit the sick and those under affliction,
to whom she was greatly helpful.
Her openness and generosity to her friends and hospitality to the poor,
were very remarkable.
In the close of her time she was strong and lively in her testimony,
even when bodily strength was so much abated,
that it was with difficulty she got out to meetings;
but having been exemplary in this and other respects, she continued so to the last.

Being far advanced in years, and attended with the infirmities incident to old age,
she bore all with Christian patience and resignation to the all-wise, disposing hand,
and finished a well-spent life, accompanied with the evidence of a future well-being,
at her house at Sedgwick, near Kendall, the 22nd of the Ninth month, 1762,
and was decently interred in Friends`' burial-ground at Preston-Patrick,
the meeting she belonged to, the 26th of the same; aged eighty-five years.

[.asterism]
'''

ALICE HALL, wife of Isaac Hall, of Little-Broughton, in Cumberland,
was born the 30th of the Eleventh month, 1708, at Blackhouse, in Allendale,
in Northumberland, and daughter of John and Isabella Fetherstone,
who being religious Friends,
carefully educated their children in the principles of truth.
She was early favoured with divine visitations, and being obedient thereto,
grew in religious experience to a good degree of stability and settlement therein.
Having received a gift in the ministry,
through an humble attention to the leading of the Good Shepherd,
she became skilful and serviceable in the church, and freely gave up to that service,
as she found her mind engaged and drawn thereto.

In her unmarried state she was concerned to visit friends twice in Ireland,
most parts of England, Wales, and Scotland; was both a good example in private life,
and in her public ministry,
abiding under the seasoning virtue which rendered her conversation edifying and agreeable.
After her marriage, which was in the year 1743,
she remained zealous for the cause of truth,
and was often concerned to travel in the service thereof,
visiting several parts of her native land, and Ireland a third time.

In the year 1760, she found an engagement to visit the churches in America,
which proved a very close trial, in parting from her husband and children;
but after recommending them to the protection of that hand which is forever sufficient,
she proceeded on her voyage, and landed in America in the Tenth month, 1761,
and diligently set about her services, visiting the provinces generally,
although weak in body, in company of a Friend, of Pennsylvania, named Ann Newland.
Her labours of love through the different provinces
were to the general satisfaction of Friends,
as appears by divers certificates transmitted from thence.

She was also enabled to visit many meetings in the
provinces of Pennsylvania and the Jerseys,
although under great bodily weakness and exercise of spirit; yet her meek, lowly,
and innocent deportment, together with her lively and edifying ministry,
made lasting impressions on many minds, and rendered her company very acceptable.
In the course of her visit, she was an example of great patience and humility,
steady in attention to her own business, and prudent in conversation,
discharging her duty faithfully in her weighty undertaking.

A little before she was confined by illness, she expressed to some Friends,
after the last public meeting she was able to attend, which was at Chester,
in New Jersey, that she was clear;
and although the yearly meeting at Philadelphia was then to be held in a few days,
she said she could not see that she should be at it.
She got to her lodging at Isaac Zane`'s, in Philadelphia, the 22nd of the Ninth month,
1762, and her distemper increasing,
notwithstanding all the tender care affection could dictate,
she expired the 6th of the Tenth month following.

She endured her last illness, which was very sharp, without any signs of murmuring,
but in lamb-like patience expressed an entire resignation in the divine will,
whether to live or die.
Her body was carried to one of the meetinghouses in Philadelphia,
and after a large and solemn meeting was decently
interred in Friends`' burial-ground in the city,
the 8th of the Tenth month, 1762.

[.asterism]
'''

BOSWELL MIDDLETON, of Boroughbridge, in the county of York,
having through a long course of years maintained
a steady testimony in opposition to all undue liberties,
and laboured for the promotion of truth,
which he was enabled to do through divine experience and obedience to the heavenly light;
and though, through extreme old age,
his memory became impaired for the last two or three years of his life,
yet a short account of him, for the encouragement of such as may hereafter read this,
claims a place in these memoirs.

He was a diligent attender of meetings,
and peculiarly qualified for the support of discipline,
awfully waiting for the arising of that divine power which is unerring,
to direct his judgment.
He twice suffered imprisonment by a priest for the nonpayment of his demands,
about eleven years, which he bore with much Christian patience and resignation,
being exemplary in suffering, and was so attended by divine assistance,
that he fervently desired his adversary might be forgiven.

About the seventieth year of his age, his mouth was opened in public testimony,
which was sound, refreshing and edifying,
greatly to the satisfaction of the right-minded; and as he bought the truth,
he was careful not to sell it: so it may be justly said,
truth and its friends were his beloved companions,
and his conduct among men gained him love and esteem.

To some friends who visited him a little before his decease,
he appeared to be in a still, quiet, sweet, composed frame of mind,
and took his last leave of them in his usual tender and affectionate manner.
Much might be said of this worthy Friend;
but as his life was a series of close exercises and trials, it may suffice to say,
he endured them as a man whose mind was weaned from the world,
having his eye fixed on a far better country, namely, an heavenly,
into which there is no doubt of his being entered.
He departed this life the 8th of the Fifth month, 1763,
in the ninety-sixth year of his age, and a minister about twenty-seven years;
and was buried at Burton, near Barnsley, the 10th of the same.

[.asterism]
'''

JOHN GOODWIN, an ancient Friend at Eskyrgoch, in Montgomeryshire, in North Wales,
was early favoured with the blessed visitation of +++[+++the Spirit of]
truth, and by faithfully adhering to the dictates thereof,
he experienced its effects to be redeeming him,
and purifying him as a vessel for the great Master`'s use.
At about the twenty-seventh year of his age, he was called to the work of the ministry,
in which, through faithfully and diligently waiting for all-sufficient help,
he became an able minister of the gospel,
and was instrumental to turn many from darkness to light,
and from the power of Satan to the power of God.

He might well be numbered among the valiants of Israel;
often visiting the principality of Wales, and, in the younger part of his life,
divers parts of England.
He filled up the several duties of life with good repute, being an affectionate husband,
a tender father, a good neighbour; also, in a religious sense, a wise, nursing father,
pleasant in conversation,
yet weighty and instructive to those who inquired the way to Zion; when led to reprove,
he was careful to abide in the spirit of meekness and wisdom.
He was of an upright life and conversation,
a fervent lover of the cause of truth and people of God,
zealous of the honour of truth and the support of its testimony in all its branches.

In his younger years, when in low circumstances,
and anxious for the support of his family, he purposed removing to America, (his parents,
brother and sisters being gone thither before,) but finding a stop in his mind,
and feeling after divine counsel, he found it his place to settle in his native land,
and it livingly arose in his heart that the Lord would provide for him and his family,
in which he believed.
And in the close of his days, he said with thankfulness,
the Lord had fulfilled it to him; which is worthy of commemoration,
and may serve as a way-mark to others who read this account,
to have their eye to Him in faith, with whom counsel dwells for direction,
in all their concerns of life.

He continued fresh and lively to old age, and about three weeks before his decease,
at the last public meeting he attended,
he was enabled to bear testimony in the life and
power of truth in a remarkable manner to those present,
amongst whom were divers not in society with us.
After meeting, he said he was fully clear of the people, and released from that service;
signifying his time here was near a conclusion, and that now, after a painful affliction,
he should soon be at rest with the righteous, for which he longed; yet said,
"`Let patience have its perfect work.`"

During his illness he appeared to be in a heavenly frame of mind,
abounding with praises to God for his continued mercies,
often expressing how valuable the enjoyment of the love of God is on a dying-bed.
He desired his love might be remembered to his brethren and sisters in Christ,
being sensible and clear in his understanding to the last hour.
He quietly departed this life, as one falling into a sweet sleep,
the 7th of the Twelfth month, 1763,
and was buried in Friends`' burial-ground at Llwyndee, the 12th of the same;
aged about eighty-two years.

[.asterism]
'''

CATHARINE BURLING, daughter of John and Arn Burling, of the city of New York, in America,
was taken ill of a slow fever, which weakened her gradually, so that,
to use her own expressions, she was reduced step by step;
all means used for her help proving ineffectual.
When she was brought low, and her recovery appeared doubtful,
she was for a time under great exercise of mind concerning her future state,
and prayed to the Lord for a little more time, and that she might witness a better state;
which he was graciously pleased to answer, not long after,
she saying her mind was changed.

She came to witness the child`'s state, filled with innocency, abounding in love;
often saying,
"`My mind is like a little child`'s.`" Her heart came to be filled with the love of God,
and in the aboundings thereof, for several weeks before her departure,
she was at times enabled to declare of the Lord`'s goodness to her in a wonderful manner;
and also, to exhort many who came to visit her, to amendment of life,
that when they came to lie on a sick-bed they might be made
enjoyers of that peace she was then made a partaker of;
often saying she felt his peace flow in her mind as a gentle stream,
and that her cup ran over.

Though order of time may not be kept strictly to,
yet many were the sweet expressions which this young woman uttered, some of which,
as nearly as could be remembered, are as follows, viz.:
"`Many wearisome nights have I gone through, and have watered my pillow with my tears.
I was long in doubt of my eternal happiness, and in the time of greatest distress,
I cried to the Lord that he would be pleased to lengthen my time a little longer,
that I might be more fully prepared.
And he was graciously pleased to hear and grant my request;
and now he has been pleased to grant me a full assurance of it, and to lengthen my time,
that I might speak of his goodness to others, and tell what he has done for my soul.

O praises, praises, praises, be given to his great and glorious name!
My tongue is too short by far: O if, I had the tongue of an angel,
I could not sufficiently express my gratitude to that gracious
God who has been thus pleased to favour me in so eminent a manner!
My disorder is very changeable: very flattering it would be to some,
but it does not flatter me.
I am resigned to the Lord`'s will, let him do just as best pleaseth him with me,
his poor frail creature.

A few days ago, when I thought I was just launching into eternity,
that boundless ocean of eternity,
I prayed to the Lord that he would be pleased to give me a little longer time,
and he was graciously pleased to hear and grant my request.
The work of regeneration is a great work.
I know it now experimentally.
I am become a new creature, new thoughts, new desires,
my affections set upon things above.
I have a new name written in the Lamb`'s book of life,
and the white stone is given to me.`"

She at the same time advised her brothers and sisters to plainness of speech and apparel,
saying, "`Remember our blessed Lord, that great pattern of plainness,
who when on earth went up and down doing good, and wore a garment without seam.
He was crucified, he was nailed to the cross for our sins, for my sins:
O love inexpressible!`"

During the last five weeks of her illness she was
frequently speaking of the Lord`'s goodness to her,
being favoured in an extraordinary manner; often saying,
"`I have nothing to do with this world.
O let my time be employed in praising the Lord,
and telling of his gracious dealings with my soul!`"
One evening, as her father was sitting by her bedside, she said to him,
"`Thou art my father, but now I have another father; I have an heavenly father.
I love thee dearly, but I love him much more.
Oh! he is the chiefest of ten thousands!`"

She would often say, "`I am thankful to the Lord for all his favours conferred on me,
and when I do not speak I am thankful in my heart, and that is more than words.
The Lord does not require lip-honour,
but when my heart is filled I cannot help speaking.`"
At another time, "`Many are the changes and vicissitudes I experience,
and what may come next none of us knows;
but I am resigned and thankful for all his mercies, his poor frail creature:
he must do with me just as he pleases; we should be thankful for all the Lord`'s favours.
I hope and pray that I may be kept thankful and humble, meek and low, before him,
waiting for my change, and a happy change it will be to me.`"

One morning, as her mother and sisters were putting on her clothes,
she desired them to stop, and then expressed herself to this effect:
"`I now no longer wonder that the martyrs could sing in the flames.
I could do the same.
I think I could go through burning flames, if required, for the love of Christ.
O it is inexpressible!`" and spoke much more, and then prayed in an extraordinary manner.
At another time she spoke to the purpose following: "`Now I know how precious the soul is.
O that people would prize their time, and prepare while health is granted them!
I bless the Lord I am prepared; if he is pleased to call me the next moment, I am ready.
But I am thankful for the little time he has granted me to be with you; but,
O how shocking,
how horribly shocking must it be for such poor souls who are unprepared
and deprived of their senses at such a time as this!`"

She often exhorted and advised many young people, at different times,
against reading romances and idle books, saying,
"`It has been the greatest trouble and exercise of mind to me,
more than anything I have done.
It has cost me many a wearisome night, and many a bitter tear,
though I have never read but a few, and those that were deemed the most harmless.
I know there are some who deem them innocent amusements,
and say those books are instructive, and there are good morals in them.
But, O! must we go to such books for good morals?
Read the Scriptures, which are the best of all books.
And there are other good books`'

One following the sea coming into the room, and standing by her bedside,
after a few minutes she spoke to him to this import:
"`Thou art one that saileth on the great waters,
and there thou mayst see God`'s wonders in the great deeps;
and thou art much in company with sailors and such like men,
and I know they are light and frothy in their conversation.I
desire thee to keep thy mind watchful and near the Lord,
which if thou doest, thou wilt be preserved in his fear.`"

When she mended, after a severe turn of illness,
one evening she called her little brothers to her,
and kissed them in a very loving manner; and then being removed to the bedside,
as she sat thereon she said, "`O I am full of love!
I feel a degree of divine love.`"
A neighbour being in the room, noticing how easy and composed her countenance was,
she answered, "`How can my countenance be sad when my mind is at peace.`"
The neighbour answering, "`Which the world cannot give,`" she returned,`" No,
nor take away.`"
Two neighbours, not of our Society, coming into the room, she spoke to one of them,
saying, "`Thou seest me very weak and low, but my mind is at peace,
sweet heavenly peace of mind.
I hope and pray that thou mayest feel the same when thou comest to lie on a sick-bed.`"

Through the prevalence of her distemper, and for want of sleep,
she became delirious for some days, with small intermissions;
and then at such intervals she seemed filled with divine love.
The last day before her departure, she bade her sister tell her mother, "`I am resigned,
patiently waiting and quietly hoping for my happy change.`"
A little before her departure, she told her father she was not afraid to die.
Soon after she said to one of her sisters, "`I feel as if I am going to paradise.`"
About noon the same day she desired her mother to tell a
friend present that she should go easy and to rest.
She departed this life, without sigh or groan, the 10th of the Fourth month, 1764,
between the hours of eight and nine in the evening, in the eighteenth year of her age,
and was decently interred in Friends`' burying-ground in New York.
