== Chapter 3

[.chapter-synopsis]
* John Alderson
* Stephen Sedgewick
* Elizabeth Kendall
* Gharrett van Hassen
* Rachel Chandler
* David Coulson
* Lucy Ecroyd
* Joseph Milthorp
* Alice Alderson
* Mary Waring
* Candia Corbyn

JOHN ALDERSON, of Ravenstondale, in Westmoreland, was the son of our ancient Friends,
Ralph and Alice Alderson, of the same place,
and was educated by them in a religious manner, who both by example and precept,
were signally serviceable to him in the time of his youth, to whom he demeaned himself,
as he became truly religious, in a very dutiful manner.

About the nineteenth year of his age,
he was remarkably favoured with a humbling visitation from on high,
and as he kept under it he became fitted for the work of the ministry,
into which he was called about twelve years afterwards.
In a short time he grew skilful in it, and laboured with unwearied diligence,
visiting divers parts of England several times: he also visited Ireland and Scotland;
in all which there is good reason to believe his labours were acceptable,
and of good service to the churches.
In time of silence he was close and steady,
in a fervent travail of spirit before the Lord;
was often enabled to unfold the deep mysteries of the kingdom and the work of regeneration;
and also strongly to press Friends to a steady watchfulness against the
many subtle wiles and temptations of the enemy of man`'s happiness.

In the beginning of the year 1764, although under great weakness of body,
he found a concern to pay a religious visit to Friends in the southern
parts of the nation and in company with his beloved friend Anthony Mason,
he came to London, but under great indisposition,
being able to attend but a few meetings in that city,
in which he appeared in public testimony, to the comfort and satisfaction of many,
particularly in the meeting of ministers and elders.
But his natural strength decreasing,
he was confined about seventeen weeks at the house of our friend Thomas Jackson,
where all necessary care and assistance were administered to him.

In the course of his illness he was led, under the influence of divine love,
to leave a few hints respecting the beginning and progress of truth upon his soul,
and expressed himself to this effect:
That he was mercifully visited with the dayspring from on high,
and in the light of the Lord it was clearly discovered to him,
what he should do and what he should abstain from.
But being addicted to youthful follies and vanities, he was unwilling to renounce them,
as well as to come up in obedience to the advice and admonitions
of his faithful and experienced parents in the truth.

By his disobedience he put out the candle which the Lord had lighted in his soul,
and continued for some time to walk in darkness.
In this dark and wilderness state, the Almighty, for wise purposes by him unseen,
suffered Satan to try and prove him with various temptations;
not only with the glory of temporal delights,
but with sins exceedingly sinful in their nature.
He had received a measure of light and grace, but he rebelled against it;
and though he was kept from gross pollutions, yet his vain, light, and airy mind,
and aspiring imagination, were unwilling to submit to the yoke of Christ,
to follow him in humility and self-denial.

As he had, by transgression against the inward law, which is light,
forfeited his right to the tree of life,
he found no way for a return but by the flaming sword,
which in an eminent manner seemed furbished for him
in order to divide the precious from the vile,
and which did execute the fierce anger of the Lord upon his transgressing nature,
which was strong, and unwilling to have sin destroyed both root and branch.
For some time the Lord executed his just judgments,
so that his terrors made him afraid that his mercy was clean gone from him forever,
which brought him to despair of attaining life eternal.

But when the Almighty, who redeems Zion through judgment,
was pleased to say it was enough,
and this dispensation of condemnation had humbled his spirit,
and bowed his neck to the yoke of Christ,
by the powerful operation of his spirit he became as clay in the hands of the potter;
and though the ministration of condemnation had been glorious,
he could now sing of judgment and mercy.
And as he kept faithful to the discoveries of the light,
which shone brighter to the perfect day,
he was preserved therein from turning again to folly; knowing, by purchased experience,
that all who are saved from sin, and persevere in a life of righteousness,
must walk steadily in the light of the Lord.

While he was in the employment of a shepherd, being alone,
he was by the love of God so powerfully attracted to love him again, and all mankind,
that under the sacred influence and holy anointing thereof,
he found the gospel of salvation flowed universally towards all,
and the word of life sprang and flowed in his soul
as if he had been preaching to many people.

Thus this dear Friend became qualified for the work of the ministry,
a dispensation of which was given to him,
that he might show unto man the way of life and salvation.
Much excellent counsel and advice also dropped from him, in the course of his illness,
to ministers and elders in their various states and allotments,
his understanding and memory being preserved clear and strong to the last,
being also blessed with remarkable serenity and calmness in that proving season.

Towards the close of his time, after commending every one to God,
and to the word of his grace and good spirit, he added, "`For whose sake,`" says he,
"`I have travelled in the deeps; and now, in the seeming conclusion of my time,
I witness renewed peace and divine refreshment, and with my languishing breath,
under the influence of gospel love, I am enabled to pray for the peace of our Zion,
that truth and righteousness may prosper within her gates,
and the salvation of our God may be appointed as walls and bulwarks about her city.
This is what I continue earnestly to wish, not only for my brethren and fellow-members,
but for every one who may receive the invitation of God`'s
love and be obedient to the dictates of his spirit,
and so become inhabitants of this holy city, the city of the great king,
who is ever worthy to rule and reign in the hearts of his people.`"

Then added, "`Thus having relieved my spirit,
there remains nothing but to desire my endeared love
may be remembered to my affectionate wife,
who,`" says he, "`I desire may not grieve beyond measure,
but freely resign me into the hands of my faithful Creator; also to my dear children,
with my dear aged parents and relations according to the flesh; telling them,
that through the continued lovingkindness of a merciful Saviour, it is well with me.
I am favoured with a comfortable evidence,
that if I am removed with the present weakness of body,
he will receive me into the arms of his mercy; and that I go to their God, and my God,
to their Father and my Father, to join the heavenly host,
in ever magnifying his love and mercy,
who hath loved and washed us in the blood of the immaculate Lamb: to whom,
with the Father, through the holy spirit, be glory, honour, and praise, now,
and eternally in the heavens.
Amen.`"

He departed this life the 26th of the Fourth month, 1764, about midnight,
and his body was interred in Bunhill-fields the 30th of the same,
after a large and solemn meeting at Devonshire-house, held for that purpose:
aged nearly forty-three, and a minister about twelve years.

[.asterism]
'''

STEPHEN SEDGEWICK, an ancient Friend belonging to Bentham monthly meeting, in Yorkshire,
was born about the year 1684, and educated in the way of truth as professed by us.
When very young, he became concerned to live a sober and religious life,
frequently seeking solitary places to pour forth his soul in supplication to the Lord,
that he might know an inward acquaintance with him for himself.
As he grew in years he grew in saving knowledge,
so that about the twentieth year of his age his mouth was opened in the ministry,
and through faithfulness he became an able minister of the gospel,
having frequently to declare to others what the Lord had done for his soul,
to the encouragement of the weak and sincere mind.

He laboured diligently, and visited most parts of the meetings in this nation, Scotland,
and Ireland, and was frequently engaged in visiting the families of Friends;
for which service he was eminently qualified.
During the latter part of his life he was afflicted with bodily weakness,
yet still continued a constant attender of meetings, both for worship and discipline;
and it was clearly observable, the nearer he drew towards his final change,
the more lively and bright he grew in his gift in the ministry.

His life and conversation were remarkably regular and inoffensive,
his benevolence extended to all, whereby he obtained a good report and esteem.
During his last illness he often declared to those who visited him,
that his day`'s work was done, that he had nothing to do but to die,
and that he was in true peace with the Lord and all men.
He departed this life the 10th of the Fifth month, 1764,
and was buried in Friends`' burial-ground at Lower-Bentham: aged about eighty years,
and a minister sixty years.

[.asterism]
'''

ELIZABETH KENDALL, late of Manningtree, in Essex,
was convinced of truth in her young and tender years;
although in the beginning she was not sensible what it was that followed her with reproofs,
if at any time she missed or turned out of the way
which she was convinced she should walk in;
which brought great anguish upon her tender mind,
and made her to seek solitary places to pour out her tears before the Lord,
who heard her prayers and supplications for preservation, and was her alone helper.

Her parents not being at all sensible of her trouble of mind,
and that it was for her soul`'s sake, that it might rest in the day of trouble,
began to be very harsh with her,
by threatening and using all endeavours to drive her from such thoughtfulness,
fearing it would be her ruin.
But powerful was that good hand and arm which was made bare for her support,
so that the more her suffering increased the stronger she grew.

At this time she was quite unacquainted with Friends,
not knowing there was such a people; but some time after,
her parents removing to a place near which some Friends resided,
she became acquainted with them, in whose company she was often refreshed,
and her afflicted mind much comforted.
Hearing of a meeting she found means to get to it, in which,
though there were but few words spoken, she was melted down as wax before the fire,
not wanting to hear words; but was sensible these were the people she was to join with,
which she did for peace sake, about the nineteenth year of her age.
Then did her sufferings increase by her parents,
but in a more severe manner from her father,
he having a great dislike to the name Quaker, saying,
"`I had rather she had been any thing but that,`" and spoke much against them.

Yet was she steady and immoveable,
many times having much to say in vindication of the truth, but he could not bear it,
therefore was more severe against her.
About the twenty-first year of her age she came forth in a public
testimony to the great comfort and satisfaction of Friends,
which occasioned a fresh trouble to her parents,
and made her sufferings still greater from them;
yet it did not alter her steady resolutions in pressing
forward in that which brought peace,
neither occasioned her to show any uneasiness to her parents.

One day her father being in great warmth took her
by the arm and thrust her out at the door,
saying,
"`Let me never see you more if you do not leave the Quakers;`"
she patiently bore it and went to a Friend`'s house,
who gladly received her until further way was opened.
After some time it pleased the Almighty to grant her father
a visitation of the day-spring from on high,
which brought him to a sight of his state and condition,
and made him seek a place of repentance.

He became willing to suffer and to endure the cross,
and betook himself to a very circumspect way of life and after a considerable time,
hearing his daughter was to be at a meeting near where he resided,
he privately got to it;
in which she was favoured to bear a living testimony to the truth,
and was made instrumental to his being fully convinced.
After meeting he embraced her with tears, saying, "`My dear child, hold on thy way,
fear no man, thou art in the right.`"
And from that time he constantly went to meetings;
and continued faithful to the end of his time; some time after his wife, one son,
and another daughter, joined Friends.

After some time she settled at Bradfield, near Manningtree in Essex,
and being freely given up to the Lord`'s requirings, grew much in the truth;
her testimony was large, lively, and powerful,
to the great comfort and satisfaction of the honest-hearted.
She was often concerned to go forth and leave all that was near and dear to her behind;
was several times drawn to visit friends in this nation, once in Ireland,
twice in Wales and Scotland, and in all was well received.
She appeared much to the consolation of the afflicted,
but as a sharp threshing instrument to the careless,
and to the stirring up and awakening many.
A pattern of plainness and true humility, zealous for promoting the truth,
having no greater joy than to see its professors prosper in it,
nor spared any pains to admonish or rebuke where occasion required.

For several years before her decease she was attended with great bodily weakness,
yet as long as it was possible to be had to meetings did not give it over.
Soon after her being disabled from attending meetings,
she was taken with something of the palsy, which affected her speech,
so that she could not well express herself, but was sometimes understood to say,
"`I love, I love all;`" nothing more pleasant to her than to see her friends.

She was often retired in her mind, sweetness appearing in her countenance;
a pattern of patience, not finding fault with what was done for her,
nor heard to say it was hard she should be afflicted with so many weaknesses;
but always appearing in an easy frame of mind with great pleasantness,
endeavouring to make those about her sensible she
counted it a great favour she was provided for.
She departed this life the 19th, and was interred the 24th of the Second month, 1765,
in Friends`' burial-ground at Manningtree, about the eightieth year of her age,
having been a minister about fifty-eight years.

[.asterism]
'''

GHARRETT VAN HASSEN, an ancient friend of Dublin, was born in Holland.
He was a signal instance of the mercy and long forbearance of a gracious God,
having been favoured with a divine and powerful visitation
about the fortieth year of his age,
and thereby reclaimed from a state of unregeneracy and sin, witnessing true repentance.
He joined in society with us the people called Quakers, and through faithfulness,
being led on in the paths of piety and love to God and men,
he received a gift in the ministry in England,
and about the year 1737 he went to Ireland,
and for the most part of the remainder of his time resided at Dublin.

He was a fervent labourer in the ministry,
and zealous in his testimony against the inordinate love of the world,
affectionately tender to the youth, and was often concerned for their preservation.
He visited the meetings of friends in Great Britain;
and in the year 1747 he performed a visit to most
or all the families of friends in Ireland,
and also to such as had by misconduct justly incurred the censure of the Society;
in which labour he was well received, having extensive charity.

During the latter part of his time, he was greatly afflicted with bodily infirmities,
disabling him in a great measure for public service;
but he still retained his love to God and the brethren,
and at or near his conclusion had the comfortable
assurance of his removal to a better state,
which he signified by the following expressions among others:
"`I am going to your Father and my Father; to your God and my God.
I die daily, nevertheless I live, and not I, but Christ liveth in me.`"
He departed this life the 30th of the Sixth month, 1764; aged about seventy,
and a minister upwards of twenty-eight years.

[.asterism]
'''

RACHEL CHANDLER, formerly PENFOLD, was born at Guildford, in the county of Surry.
Her mother dying when she was young, subjected her to many inconveniences,
which she occasionally mentioned;
but being favoured with an early visitation of divine love,
was preserved from the grosser pollutions of the age.
By gradually submitting to the sanctifying operation of +++[+++the Spirit of]
truth, she was fitted for the work of the ministry,
and diligently labouring to improve the talent committed to her trust,
in due time became an able minister of the gospel, sound in doctrine,
rightly dividing the word of truth.
She travelled through divers parts of this nation in full unity with her friends,
and to the peace and satisfaction of her own mind.

Her ministry was attended with a lively demonstration of the spring from whence it flowed;
she was often favoured with near access to the throne of grace,
in fervent supplication for the restoration of Zion to her primitive purity and beauty;
and in commemoration of the Lord`'s goodness to her
through the various dispensations of his providence,
would frequently exhort the youth to remember their Creator in the days of their youth,
and dedicate the prime of their days to his service.

She was a nursing mother to the tender and well-inclined,
and a true sympathizer with the bowed-down and afflicted in spirit,
but a sharp reprover of the rebellious and stiff-necked;
an affectionate friend and kind neighbour; a pattern of industry, humility,
and self-denial;
a good example in discharging the several relative duties
suitable to her station and circumstances in life,
which made her beloved both by friends and others.

She was long afflicted with a sore disorder,
which rendered her incapable of travelling for a considerable time;
but she constantly attended her own meeting, and after, when her inability increased,
the meeting was held at her house, where she frequently appeared in public testimony,
under a living sense that the Lord had not forsaken her in this time of outward affliction.
To her husband and a friend who came to see her, she said, if she died then,
her desire was that they would look to their own standing, and not grieve for her,
but rather rejoice she was landed safely from a world of peril and difficulty,
a life of temptation and probation;
that the last thing she had to struggle with was death, and that was made easy,
the sting thereof being taken away.

At another time, being in great pain, +++[+++she said,]
"`Oh! if I had my peace to make now, what should I do!
It is enough to bear the infirmities of the body without the load of a guilty conscience.`"
Being a little easier, she said that her pain was often very strong,
yet at times she witnessed great sweetness,
which supported and enabled her to bear her affliction; further adding,
a little of the balm of Gilead was very comfortable to her,
and that she longed for the time to come when she might
drink large draughts of water from the well of life.

She was several months confined to her bed,
but bore her affliction with remarkable patience and resignation,
and continued sensible to her end, departing this life the 18th of the Fifth month, 1765,
and was interred in Friends`' burial-ground at Kingston the 24th of the same;
aged forty-two, and a minister sixteen years.
A few months before her death,
she drew up a brief memorial of the gracious dealings of the Lord with her soul,
which she desired might be communicated to Friends, and is here annexed.

[.embedded-content-document.testimony]
--

[.blurb]
=== A brief memorial of the Lord`'s gracious dealings with Rachel Chandler, formerly R. Penfold, late of Esher in Surry, written by herself a few months before her decease, and at her particular request communicated to Friends.

When I consider that the grave cannot celebrate the praise that is due
to the Lord on account of his gracious and merciful dealings to my soul,
I am inclined to say so much on God`'s behalf as may suffice to let mankind know,
that he of his own free mercy first visited my soul,
when it was gone very far astray from the right path,
and at about the seventeenth year of my age,
laid the axe to the root of the corrupt tree, and shook my sandy foundation;
so that my feeble building, grounded on profession and name, was made to totter,
and I to cry out in the anguish of my spirit,
What shall I do to become what I ought to be,
that so I might obtain favour and peace with God!

Such was my sorrow night and day, that I often wished I had never been born,
or that I had died very young, before I had knowledge of good and evil;
for now that the book of the law was opened, the commandment came,
sin revived that had been hid and covered with a fig-leaf covering, and I died;
and as one sensible of the terrors of the Lord, I often cried,
O wretched creature that I am, who shall deliver me from this body of sin and death?
Thus went I secretly mourning on my way for a long time,
while my adversary laid many baits in my way to catch my unwary feet;
yet whenever I yielded to the forcible power of conviction,
though in ever so trivial things, I found peace.

But as I had gone a great way from the Father`'s house,
so I had a great way to come back, and it took up much time,
for there was a long war between the house of Saul and the house of David;
but blessed be God, the father and fountain of life,
the house of David grew stronger as the house of Saul grew weaker,
so that in time my enemies were discomfitted,
and what I had seen and heard in secret at the bottom
of Jordan and in the depth of the sea,
was I required to proclaim as on the house-top.

This was so weighty an engagement, that it took up much time to be fitted for,
lest not being rightly prepared I should be drawn in a forward
zeal to do that which was not required of me,
as poor Uzzah did, or being rightly anointed, yet through a forward mind to be doing,
should be hastily drawn to offer sacrifice before Samuel came.
After repeated manifestations and convincing circumstances had been afforded,
yet the confirming evidence being wanting,
I durst not appear in public testimony for God, until, Gideon-like,
I had tried the fleece every way,
by which the long-forbearance of the Lord was discovered to me-ward,
who knew my withholding was not from obstinate rebellion,
but through fear of taking that on me which I was not called to,
and that my desire in doing his work was that I might be his servant,
and found answering the end for which I was made, that, rightly improving my talent,
I might at last have an entrance into the joy of my Lord.

At length,
having waited the season for the accomplishing the
work of manifesting my love by my obedience,
I gave up in great weakness and trembling to speak a few words in meetings,
in the twenty-sixth year of my age, and had great peace in so doing.
Although I have never been called to much service, yet,
having one talent committed to my trust,
I have found an absolute necessity to improve the small portion of grace received,
and also to watch and guard against temptations, which I have had my share of many ways,
but find none more dangerous nor subtle than self, the most cruel foe,
of which I am the more free to speak in order to inform others,
that they may beware and not attribute that honour to self which belongs to God.

I have seen it in many shapes, had many a combat with it, and do rejoice in this,
to see it under foot and the Lord to be uppermost.
There self is of no reputation; and that I may still witness this,
that as my eye has been steadily fixed on my good guide,
who first found me out when alone in a desert land,
and a concern hath been raised to follow him only in the way of his leadings,
so he also may have the glory and praise in conducting me safely
thus far on my journey through many difficulties and straits,
which but only to look back upon makes me shudder,
insomuch that approaching death appears a pleasant
release from a world of trials and besetments,
which while here we are liable to.

I am ready to conclude my work is almost done, my day nearly at an end,
my sun nigh setting,
in which the curtain of the night will be drawn over my earthly tabernacle,
which pain and weakness make to shake, so that I suppose what I do,
I had need to do quickly, for no device or work can be done when the spirit is departed.
Therefore having love to my fellow-citizens, as well as goodwill to strangers,
I am willing for their encouragement to leave this
small hint of the goodness of God to a poor worm,
who am far from being able to speak one half of what hath been done for me,
only that men may glorify God when they find my footsteps,
and consider that as weak as I have been,
yet the great condescension of divine wisdom and omnipotence is such,
that now being confined as a prisoner at home by my incurable malady in the flesh,
my spirit is at liberty to praise God and give glory to him,
under a renewed sense that I have so far fought the good fight,
and have been hitherto helped to keep the faith.
I feel peace to be my reward, which makes ample amends for all my sorrows, yea,
and the present pain.

Hallelujah to God on high, peace on earth, and goodwill to men, saith my soul.
O let all cleave to him as to a most sure and certain guide,
who will not leave his people comfortless,
blessed be his name! but will come again and cause them to rejoice,
and their joy shall exceed the joy of harvest, when corn and wine increase.

[.signed-section-signature]
Rachel Chandler.

[.signed-section-context-close]
Esher, Ninth month, 1764.

--

[.asterism]
'''

DAVID COULSON, was born at Nottingham, the 9th of the Fourth month, 1713,
of religious parents, and educated in the way of truth.
In his youth he was strongly addicted to vain amusements and company,
gratifying himself therein for some years.
His father dying when he was young, he was much laboured with by his tender mother,
who with many tears sought his reformation, which often affected him for a short space;
but still his inclination to vanity was so great,
that he stifled the convictions of truth.

About the twenty-first year of his age, happening to lodge in a damp bed,
an inflammation in his eyes followed, by which he lost his sight,
and being visited with sickness, was reduced very low.
Nevertheless he did not break off from his companions,
their vain conversation serving for an excuse to divert him in his dull situation,
and although pain and sorrow of heart were often his portion,
yet it was hard for him to take up the cross and follow Christ in the way of self-denial,
until about the twenty-sixth year of his age, when a powerful visitation was extended,
that he dared no longer to resist.
He had to see that if he did not join in therewith,
it would be the last visitation that would be afforded;
he therefore consulted not with flesh and blood, but gave up to the heavenly vision;
of the humiliation of which day he would often speak with reverence and gratitude.

About the thirty-third year of his age,
his mouth was first opened to declare to others what God had done for his soul,
and a concern was soon raised in him to visit the churches; to which,
notwithstanding his want of sight, he gave up, and excepting Kent and Sussex,
he visited all the counties in England, and some of them divers times;
and through the merciful care and protection of his great Lord and Master,
he was so preserved as never to meet with any fall
or accident to lay him up one day in all his travels.

For some years before his death, he was afflicted with a sharp,
painful disorder in his stomach and bowels,
which rendered travelling on horseback impracticable,
yet occasionally attended some neighbouring +++[+++meeting]
or the quarterly meeting he belonged to; under all which he had to remark,
that he had not neglected his day`'s work, in which, he said, he found peace,
and that he could say without boasting,
he never had omitted anything that he apprehended his duty.

The next day after his return from the circular-meeting at Stourbridge, he was taken ill,
and continued so for some time, but at times got out to meetings.
On the 24th of the Eleventh month, 1765, in the afternoon he went to meeting,
and in the evening had an acceptable time in the family,
in which the divine life spread like to the odour of the precious ointment.

In the course of his illness he dropped many heavenly expressions, some of which follow:
"`O! it is a good thing to live near the Lord while in health,
for I find it now enough to do to grapple with the pain of the body.
But I thank God I am quite easy whether I live or die.
Death is no terror, for my life is in Christ, and the Lord sweeteneth every bitter cup.
But it is not so with those who follow lying vanities,
for they are forsaking their own mercies.
The Lord can bring low, and can raise again, at his pleasure.
If I should at this time be restored, I hope I shall be more redeemed,
and brought nearer the Lord in that pure covenant of life.
I often think what will become of them that are lukewarm in religion,
for if we keep ever so near the Lord, and serve him with all our mind and strength,
we have nothing to spare, no, no; we are but unprofitable servants,
we have done but that which is our duty.
I pray God support me under all the trials and exercises of this day.`"

To one who attended him, he said to this effect: "`Keep near the Lord,
and seek him with all thy heart, for thou knowest not how soon the messenger may come,
whether at midnight, at cock-crow, or at the dawning of the day.
O let nothing hinder thee from seeking him!
Look not at thy poverty, for what signifies all the greatness and riches of this world?
if we keep near the Lord, he can be abundantly more than this unto us.`"
To another he said, "`O poor girl, serve the Lord! thou canst never do anything better;
the Lord loves an early sacrifice; give him, therefore, the sacrifice of thy youth.
I can say nothing more than to desire you to keep near the Lord, for I wish you all well.
The Lord has been my strength and preserver, my all in all; the Lord is my shepherd.`"

To some friends coming into the room: "`Now, friends,
do you think it is fit to put off repentance to such an hour as this?
O, it is a sad thing! for we all know we must die, it cannot be otherwise with any.
But if we take not up our daily cross, and be regenerated and born again,
we cannot see the kingdom, much less enter into it.
The Lord can bring low and raise again, blessed be his holy name; his holy will be done,
come life, come death.`"
The latter part of the day he spoke little, but lay in a sweet disposition,
desiring to be still, was sensible to the last, and quietly departed this life,
as one going into a sweet sleep, about the second hour in the morning,
the 9th of the Twelfth month, 1765; aged fifty-two, and a minister twenty years.

[.asterism]
'''

LUCY ECROYD, wife of John Ecroyd, of Edge-End, in the county of Lancaster,
and daughter of James and Ann Bradley, of Bromyard, in Herefordshire,
was mercifully visited with the manifestation of divine grace while very young.
The tender care of an affectionate parent, who watched over her children for good,
was blessed to her in an eminent manner;
the wholesome advice she was frequently concerned to administer,
made deep and awful impressions on her mind,
though she was soon deprived of this great blessing,
her mother dying when she was about thirteen years of age.

After which, being exposed to unprofitable company,
she found the truth of the apostle`'s assertion,
that "`Evil communications corrupt good manners;`" for she was thereby drawn into vanity,
leavened into the spirit of this world, and too much attached to its fading enjoyments.
In this time of forgetfulness and departure from her first love,
she met with many close inward trials and outward disappointments,
finding no rest to her weary soul, till passing through judgment,
by which Zion must be redeemed, and enduring many sore conflicts,
her feet were mercifully turned into the way of peace.

About the nineteenth year of her age, her mouth was first opened by way of testimony,
being a good example in word, in conversation, in charity, in faith and purity,
she adorned the doctrine of our Lord.
Much might be added to commemorate her worth,
the innocency of her deportment and exemplary conduct
through the various parts of her service,
whether in her public station or more private service; let it suffice to say,
her heart was devoted to God, and from thence out of the good treasures thereof,
she brought forth things new and old.

About the twenty-fourth year of her age she visited London,
in company with her beloved friend Rebecca Smith, of Nailsworth, in Gloucestershire,
since deceased, where her service was very acceptable.
Indeed, it may be recorded to the memory of them both,
they were instrumental of good to many in their said visit; and,
in all her services being carefully concerned to keep under
the guidance of the holy hand which put her forth,
she was kept in the right line, conducted therein with safety through her service,
and was favoured with the return of peace in her own bosom.

In the latter part of her life, when in health,
she frequently intimated a persuasion that her race was nearly over,
expressing a fervent desire that, through divine mercy, she might be enabled,
by patient continuance in well-doing, to hold out to the end.
Thus she retained her integrity to the close of life,
ever preferring Zion`'s welfare before her chiefest joy.
In her last illness she spoke but little;
but her patience under such great bodily affliction,
and the sweet composure of her countenance and deportment,
clearly evinced she had access to the place where prayer is wont to be made.
She departed this life the 26th of the First month, 1776,
and was interred in Friends`' burial-ground in Marsden, in Lancashire;
aged forty-one years.

[.asterism]
'''

JOSEPH MILTHORP, a member of Pontefract monthly meeting, in Yorkshire,
was educated in the principles of the church of England.
But as he advanced towards man`'s estate, being of a thoughtful disposition,
and unsatisfied with the principles of his education, he,
after various researches among the different modes of profession,
joined himself to the Romish church,
and for divers years constantly attended their worship,
and strictly observed their ceremonial institutions,
for some time firmly believing Christ Jesus to be the author thereof.
At times he was led to believe there was a subduing
of the passions and a renovation of heart,
which the truly righteous experienced, also a fruition of inward peace,
which they at times possessed; to all which he found himself,
in great measure a stranger.
This caused him many times secretly to mourn and
pour forth earnest prayers to the Father of mercies,
that he might become a partaker of the same happy experience.
While he was thus exercised it came into his mind
to go to a meeting of the people called Quakers,
for an account of which take his own words, in a letter, viz.:

[.embedded-content-document.letter]
--

I sat at ease a long time,
yet earnestly desired that if the Lord had any particular regard to that people,
or approved of their manner of worship, he would make me sensible of it.
Being thus set and grown weary of silent waiting, divine power seized upon my body,
soul and spirit, which caused me to break out into abundance of tears,
and my body greatly to tremble.
Then said I, "`O Lord! why am I thus?`"
To which inward cry of mine, something which till then I knew not,
though I had often felt a measure of the same power, though never to that degree,
answered, "`If thou did but love the Lord thy God with all thy heart, mind and soul,
that love would be so prevalent over thee, that it would teach thee what to do,
and what to eschew.`"
O the surprising state I then found myself in!
How was my heart then filled with love, peace and joy unspeakable and full of glory!
Soon after, an honest Friend stood up in tears and much trembling, and said,
"`It is an excellent thing if we can say of a truth,
Jesus Christ lives in us.`" These words reached my state, I then bowed in my mind,
adoring the divine power that then influenced me, and said,
"`Dear Lord! if thou art he that I have long sought and mourned for, tell me,
O thou that hast ravished my heart! what I should do to be saved,
or to continue in thy favour?`" Upon which the humble Jesus,
the divine bridegroom of my soul, affectionately answered,
"`I require no rite or ceremonial worship of thee, but that thou give up thy heart.
It is there I would reign, it is there I would rule,
and there I would be worshipped in spirit and truth.`"

--

It was some time before he could get from under the
prejudices he had in favour of the Roman church,
but continued to frequent both the mass house and Friends`' meetings,
until through a further visitation by an instrumental means, he was effectually reached,
became a valuable and useful member, exemplary in conduct,
careful to have the discipline maintained,
and at times was concerned in a short testimony, which was very acceptable.
+++[+++He was]
a peaceable neighbour, and being of extensive knowledge,
was capable of advising in many cases, which he was always ready to do,
demonstrating that the living divine principle he had embraced,
led him to the exercise of every Christian virtue.

For divers years before his death, he was at times sorely afflicted with disease,
the acuteness of which he bore with exemplary patience.
His last illness was short,
and apparently attended with no symptoms of death till near the time of his departure;
and though he was suddenly called, yet not unprepared, for,
being asked a little before his death how he was, he expressed himself thus:
"`I am pretty easy, though not without some bodily pain,
yet inward comfort helps greatly;`" and added, "`I am weary, weary of this world,
if it would please Providence to take me to himself, O how acceptable it would be!`"
He departed this life the 3rd, and was interred the 5th of the Seventh month, 1766,
in Friends`' burial-ground at Burton; aged about fifty years.

[.asterism]
'''

ALICE ALDERSON, wife of Ralph Alderson, of Ravenstondale, in the county of Westmoreland,
was convinced of truth in her young years,
and carefully abiding under its divine teachings
consistent to the advice of the wise king Solomon,
"`Trust in the Lord with all thy heart,
and lean not to thy own understanding,`" she came to receive a gift in the ministry,
and though for a considerable time in a few words,
yet greatly to the edification of the church.

Being faithful in a little, she witnessed an increase therein, and,
clothed with the comeliness of the gospel, became valuable in the Lord`'s house,
devoting the prime and flower of her youth, her middle age and decline of life,
to his service; labouring diligently in the cause of truth, both in England, Scotland,
and Ireland, and once in America; in all which, her labours of love were well received,
and tended much to the edification of the church.

In her ministry, though she had not much human learning,
she was frequently furnished with copious expressions
well adapted to the matter she had to deliver,
deep and weighty in her delivery,
and enabled to speak feelingly to the state of meetings and individuals.
She was remarkably diligent in attending meetings when at home, even to old age,
often signifying that she believed none would be injured thereby in their outward circumstances,
as the blessing of Divine Providence upon the honest endeavours of the faithful
would be ample recompense for all their labour and seeming loss of time.
When old age had so far weakened her constitution that she could no longer attend meetings,
she retained the divine anointing which had been
her support through the various stages of life.

The last meeting she was at, being the day she took to her bed,
she had to revive the encouraging invitation of the prophet Hosea,
"`Come and let us return unto the Lord, for he hath torn and he will heal us;
he hath smitten and he will bind us up; after two days will he revive us;
in the third day he will raise us up, and we shall live in his sight.
Then shall we know, if we follow on to know the Lord,
his going forth is prepared as the morning, and he shall come to us as the rain,
as the latter and former rain unto the earth.`" Hosea 6:1-3.

A few days before her departure, when some friends were sitting by her,
she was remarkably favoured with the overshadowing of divine goodness,
wherein she had weightily to caution ministers and elders
to be exceedingly watchful over their own spirits,
strongly advising them to live in the bond of love and unity,
signifying she clearly saw the subtle enemy of man`'s
happiness endeavouring to draw them aside,
in order to mar or deface that work which Divine
Providence allotted them to be engaged in,
saying that the Lord had permitted her to be buffeted and brought low,
even to the gates of hell,
and had again in great mercy lifted up her head and
given her the glorious earnest of eternal happiness;
concluding in fervent prayer for the small meeting she was a member of,
and for all the small gatherings of the Lord`'s people the world over.

In the time of her illness she was afflicted with exceedingly sharp pain,
which she bore with great resignation,
often praying for patience to bear what might be permitted to be laid on her.
A divine serenity and sweetness accompanied her last moments,
that indeed it might be said her sun went down in brightness.
She departed this life on the 15th of the Eighth month, 1766,
and was honourably interred in Friends`' burial-ground the 18th of the same,
at Ravenstondale, accompanied by many Friends and others; aged eighty-eight,
and a minister sixty years.

[.asterism]
'''

MARY WARING, late wife of Jeremiah Waring, of Wandsworth, in the county of Surry,
and widow of Daniel Weston, of Ratcliffe, was the daughter of Joseph Pace, of Southwark;
being favoured with an early visitation of divine love,
she was clearly convinced of the evil tendency of those undue liberties
whereby too many of our unwary youth have been ensnared and gone astray.
As she submitted to the sanctifying operation of truth,
her mind was redeemed from a vain conversation,
and gradually fitted for the work of the ministry;
and being careful to improve the gift received,
she became an able minister of the gospel, sound in doctrine,
and skilful in dividing the word aright.

She travelled much in the service of truth,
having at sundry times visited Friends in most of the counties of England and Wales,
and once most of the colonies on the continent of America;
in all which her service was acceptable,
and she laboured much for the preservation of good order and discipline in the church.
Of an open, generous, and charitable disposition, a lover of truth and the friends of it,
and was much beloved by them.
In her last illness, which was lingering and painful,
being confined from meeting about six months,
she was favoured with some acceptable visits from divers of her friends,
and would frequently say to them that her mind was preserved in a calm,
peaceable resignation to the divine will.

Among other expressions of weight which she uttered, the following are remembered, viz.,
that she believed herself near her end,
for she did not see that she had any thing more of religious duties to do,
meaning of a public nature; "`For,`" said she, "`when I look at our meetings,
I seem to have no concern there;
and whereas I used to be anxious about the quarterly meetings,
I now scarcely think of them, yet,`" added, "`I wish well to the cause,
and believe it will prosper, but that a trying day will come first.`"
She departed this life at Wandsworth, the 9th of the Tenth month, 1766,
and was buried at Ratcliffe, near London, the 16th of the same, attended by many friends;
aged fifty-four, and a minister thirty years.

[.asterism]
'''

CANDIA CORBYN, wife of John Corbyn, of the city of Worcester,
was born about the year 1671, at Pontypool, in Monmouthshire,
and about the eighteenth year of her age, was reached by truth,
through the powerful ministry of Thomas Wilson, which, taking deep root in her heart,
she brought forth good fruits.
In a few years she received a gift in the ministry,
in the exercise of which she was sound and clear,
and evidently favoured with the renewings of that
divine life which preserved her fresh and green;
being often tenderly concerned both in testimony and supplication on behalf of the youth,
that their tender minds might be preserved from the many snares that lie in the way,
and be so formed and enlarged by the divine hand,
as to become living branches in the true vine, and serviceable members in society.

She was frequently engaged to bear testimony to the
universality and sufficiency of the grace of God,
extended through the Christian dispensation, to all mankind;
and she earnestly laboured that Friends would retain
a grateful sense of the liberties we now enjoy,
to hold our religious meetings without molestation; often recounting the many hardships,
which she well remembered,
our ancient Friends were permitted to undergo for the trial of their faith.
She continued a diligent attender of meetings both for worship and discipline,
in love and charity as a mother in Israel, faithfully discharging her duty towards all,
hospitable to strangers, a friend to all, especially the poor, fatherless, and widow;
in her connections in life, a steady pattern of piety and virtue, so that it may be said,
in doctrine and practice,
the dew of heaven rested on her branches even to very advanced age.

Her last illness being but short,
she calmly departed this life the 28th of the Fourth month, 1767,
and her remains were decently interred in Friends`' burial-ground
at Worcester the 3rd of the Fifth month following;
aged ninety-six, and a minister seventy-three years.
Although no expressions of this ancient friend are preserved,
yet as through a long course of years she was preserved unspotted and strong in her love,
as was the case of Caleb formerly, the account is worthy of preservation,
that all may see and be encouraged, that if they keep to this living divine principle,
they will be enabled to hold out to the end.
