== Chapter 4

[.chapter-synopsis]
* Richard Hipsley
* Edmund Peckover
* Elizabeth Roberts
* Kezia Day
* Benjamin Trotter
* Rebecca Smith
* Thomas Dann
* John Burton
* William Reckitt
* Joshua Toft
* Richard Reynolds
* James Wilson
* Daniel Stanton
* Elizabeth Atkinson
* Thomas Mawditt

RICHARD HIPSLEY, a member of Claverham monthly meeting, in the county of Somerset,
was born in the parish of Church-hill, in the said county, about the year 1708:
his parents were religious, faithful Friends,
who carefully educated him in the way of truth, and as he grew in years he grew in grace,
by which his understanding was opened and enlarged,
that about the thirty-fifth year of his age his mouth was first opened in a public testimony,
in which he was very diffident and cautious.
And the Lord, who knew his sincerity, was pleased so to enlarge his heart therein,
that he became an able minister,
and being fitted and prepared he could no longer withhold,
but was concerned to visit divers parts of this nation and Ireland,
to general satisfaction.

He was eminently qualified to speak a word in season, in monthly and quarterly meetings,
which he was diligent in attending, as well as frequently the yearly meeting in London.
He was a man of a cheerful spirit, pleasant and affable in conversation, a good husband,
and tender father, a kind neighbour, doing to all as he would be done unto;
his house and heart were open to entertain his friends.
He was afflicted with a long illness, the dropsy, and was often in great pain,
which he bore with much patience, believing his departure drew near,
frequently expressing his resignation to the divine will,
and often signified to them who visited him in his illness,
that it appeared to him all was well, and that he had nothing to do but to die.

He quietly departed this life the 8th of the Fifth month, 1767,
and was buried in Friends`' burial-ground at Sidcott, the 13th of the same,
accompanied by a large number of friends and others,
where several living and powerful testimonies were borne,
to the satisfaction and comfort of those who were present.

[.asterism]
'''

EDMUND PECKOVER, of Wells, in Norfolk, was the son of Joseph and Catharine Peckover,
both persons of great esteem in the Society.
He was early favoured with a divine visitation,
of which a more particular account cannot be given
than is in a paper found in his own hand-writing.

[.embedded-content-document.paper]
--

The tender dealings of the Almighty with me in my youth,
being often fresh in my remembrance, brings a most grateful sense thereof over my mind,
under which I cannot but with reverence commemorate the same.

It was no small advantage to me, that I was favoured with religious and godly parents,
whose concern and care to bring me and the rest of their children
up in the nurture and admonition of the Lord was great.
What I look upon as very remarkable, is,
that before I arrived at an age capable to retain those good and wholesome admonitions,
which in the wisdom of God, they often communicated to me,
I felt the good hand of the Lord at work in me,
in a manner suitable to my tender capacity,
impressing upon my heart a living sense of his greatness and goodness,
which often brought me under much awfulness and fear,
dreading to do anything that I knew was not well-pleasing in his sight.

Here I could distinguish that I had peace and satisfaction,
and met with encouragement in myself, beyond what I am able to express;
and when I had been drawn away into anything which tended to hinder
my growth in that which I found to my soul`'s advantage,
sorrow and trouble took hold of me.
Under a sense hereof, I often made vows and promises,
that I would never join with the like again, which being my first-fruits before the Lord,
I believe he had a tender regard to,
and often assisted me to perform those covenants into which,
through some good measure of divine influence, I then entered.

In the time of this exercise, great and many were the conflicts I had to encounter with;
but, to the praise of his great name, I speak it,
his compassionate fatherly care was over me,
and always attended me with such a portion of his divine and saving grace,
that I knew preservation thereby through things of the most trying and pinching nature,
in the experience whereof thankfulness would arise.

--

Thus through faithfulness to the divine manifestations,
he was early anointed to preach the gospel, even in his minority,
while at the school of our friend Gilbert Thompson (mentioned in
the forepart of this treatise) in the fifteenth year of his age.
And as he abode in faithfulness he increased in his gift, and in the year 1714,
and in the eighteenth year of his age, in company with Edward Upshur, of Colchester,
he visited divers counties; and also Ireland, about the twentieth year of his age,
in company with George Gibson, as well as most parts of this nation, Scotland, Ireland,
and America, in the succeeding part of his time.

He was indeed an elder worthy of double honour,
being of an exemplary life and unstained character,
and in the exercise of his gift frequently opened and enlarged in divine counsel,
and as a cloud filled with celestial rain to the reviving
and refreshment of the living heritage of God.
Zealous for the prosperity of the church and for the ingathering of all,
he spared not to spend himself in the strength of his days,
and divine goodness was pleased to preserve him a strong
man and an able minister for a long course of years.
He usually delivered himself with great fervency
in the flowing forth of divine love upon his spirit.

About three years before his decease, he received a shock of a paralytic kind,
which both in his own apprehension and that of his friends,
seemed to threaten him with a hasty dissolution.
Under this affecting visitation,
by the account of a relation who visited him the same evening,
he was graciously preserved in a broken, tender, living frame,
and expressed himself after this manner:
that he had now the satisfaction of a good conscience,
and of having discharged himself in the duty required of him,
according to the ability afforded him; declaring at the same time,
the great consolation he inwardly enjoyed.

The next morning after a short sleep, and taking some little refreshment,
he was somewhat revived,
and signified he was well pleased that his outward affairs were settled,
and was fully satisfied with the manner in which they were ordered.
That he was entirely resigned to the disposal of all-wise Providence,
whether it might be to lengthen his days or to take him hence;
but he felt a blessed assurance,
and found the Lord who had been his support through many trials,
from his youth to his advanced years, still to be near him, and could experimentally say,
his Redeemer lived, who hath been the strength of his faithful people,
and who had brought to pass many things in his no short pilgrimage,
which to outward appearance seemed very unlikely.

After this he lay in a sweet and quiet frame, and his pain lessening,
he appeared pretty cheerful,
and in time he became so far restored as to be able to go abroad in a carriage,
but with considerable difficulty to himself.
And though in common conversation his apprehension and memory seemed much impaired,
yet his public appearance in meetings continued sound, consistent, and savoury.

A few months before his death he was rendered totally unable to attend meetings,
and continued gradually to decline, and the gracious Lord,
who had been his strength and stay in the prime of his life,
supported him in his last moments,
for then he appeared to be favoured with a comfortable foretaste
of that glorious immortality which is prepared for the righteous.
Though he was deprived of bodily strength to speak so distinctly as usual,
yet he was sufficiently understood to intimate the
inexpressible joy and felicity that he felt,
and seemed to pass away as with an heavenly song of divine praise in his mouth.
He departed this life at Wells, the 19th of the Seventh month, 1767,
and his remains were interred at Fakenham, the 22nd,
after a large and solemn meeting of relations, friends, and neighbours;
aged about seventy-two, and a minister about fifty-seven years.

[.asterism]
'''

ELIZABETH ROBERTS, late wife of William Roberts of Edmundsbury, in Suffolk,
was daughter of James Morley, of Wymondham, in Norfolk.
This our friend was early impressed with a sense of religion, which attending to,
she grew in grace and in the knowledge of the truth.
About the twenty-second year of her age she was raised up to bear testimony thereto,
in which she faithfully laboured in much zeal and Christian love for some years.
In conduct and behaviour she was exemplary, as well as in word and doctrine instructive,
devoting the prime of her youth and health to the service of truth.

About two years before her decease she fell into a great decline of bodily strength,
which disabled her from travelling;
but she retained a lively sense of the divine goodness,
rejoicing that she had in the time of health and strength
been diligent to do her duty according to ability received.
She bore her affliction, which was great, with becoming patience and resignation,
and the day she died,
prayed the Lord to be with her to the last and give her an easy passage;
which it is believed she happily experienced,
passing away without any apparent uneasiness, at the age of forty-one years,
the 9th of the Tenth month, 1767.

[.asterism]
'''

KEZIA DAY, late wife of Samuel Day, of Stansted Mountfitchet, in the county of Essex,
was visited in her tender years, and being faithful, had, at times,
to recommend her friends to the internal teacher,
and being careful not to move in the wind, earthquake, or fire,
but waiting to hear the still small voice,
her appearances were truly satisfactory and comfortable to the living.
In the course of her bodily weakness she was enabled to bear her affliction with patience,
and being weaned from a dependence on visibles,
her attention seemed to be fixed on an everlasting inheritance.
She was favoured with much serenity, and a comfortable evidence,
that He who had been her support in life,
would preserve her to a happy conclusion in his favour,
and that she should enter the joy of her Lord.

Her lively exhortations and sincere breathings to God near
her end were to the comfort and edification of those present,
to whom she had to declare, that the truth had been her preservation until that time;
having to acknowledge the riches of divine love.
She desired, that those with whom she was most nearly connected would give her up freely,
and not grieve too much, but rather rejoice in hope.
At another time she said, she hoped she had been faithful to what had been required.
She quietly departed this life without sigh or groan, on the 20th of the Second month,
1768, and was interred in Friends`' burial-ground at Stansted aforesaid,
the 28th of the same; aged about twenty-eight years, and a minister about six years.

[.asterism]
'''

BENJAMIN TROTTER, of the city of Philadelphia, was born in that city about the year 1699,
and was one whom the Lord early visited and reached
to by the reproofs of his divine light and grace,
for those youthful vanities and corrupt conversation which by nature he was prone to,
and pursued, to the grief of his pious mother,
who was religiously concerned to restrain him.
But as he became obedient to the renewed visitations of the heavenly call,
denying himself of those things he was reproved for, he not only ceased from doing evil,
but learned to do well; and continuing faithful,
became an example of plainness and self-denial,
for which he suffered much scoffing and mocking of
those who had been his companions in folly;
yet he neither fainted nor was turned aside by the reproaches of the ungodly,
which thus fell to his lot for his plain testimony against their evil conduct.

In the twenty-sixth year of his age, he appeared in the work of the ministry,
and laboured therein in much plainness and godly sincerity,
adorning the doctrine he preached by an humble circumspect life and conversation,
being exemplary in his diligence and industry to labour honestly for a livelihood,
though often in much bodily infirmity and weakness, desiring as he sometimes expressed,
that he might owe no man anything but love.
His inoffensive openness and affability,
drawing many of different denominations to converse with him,
he had some seasonable opportunities of admonishing
and rebuking the evil doer and evil speaker,
which he did in the plainness of an upright zeal for the promotion of piety and virtue,
tempered with true brotherly kindness and charity,
respecting not the person of the proud, nor of the rich because of his riches,
but with Christian freedom declaring the truth to his neighbour, and was thus,
in private as well as public, a preacher of righteousness.

He at several times visited most of the meetings
in the provinces of Pennsylvania and New Jersey,
and some in the adjacent provinces,
and for upwards of forty years was a diligent attender
of our religious meetings in the city of Philadelphia,
and zealously concerned for the maintenance of our
Christian discipline in meekness and true charity;
careful in the exercise of that part of pure religion,
visiting the widow and fatherless in their afflictions,
and often qualified to administer relief and consolation to their dejected minds.

In his public testimony, a little before his last sickness,
he expressed his apprehensions that his time would be short,
and fervently exhorted to watchfulness and care,
to keep our lamps trimmed and our lights burning,
and urged the necessity of being prepared to meet the bridegroom,
as not knowing at what hour he would come.
In his last sickness, which lasted upwards of six weeks,
he underwent great difficulty and pain, being afflicted with the asthma and dropsy,
which he bore with exemplary patience and resignation,
and was never heard to utter a murmur or complaint,
but frequently expressed his thankfulness that he had not more pain;
and was often engaged in prayer that he might be preserved in patience to the end,
which was graciously granted him, so that he was capable of speaking,
to the comfort and edification of those who visited him.
He departed this life in the Third month, 1768, and after a solemn meeting,
in which several living testimonies were borne,
was interred in Friends`' burial-ground in that city, the 24th of the same,
aged upwards of sixty-eight years.

[.asterism]
'''

REBECCA SMITH, late of Nailsworth, in the county of Gloucester,
was one who was a good example in purity of life and manners, sincerely loved the truth,
and diligently sought the promotion thereof.
Through the operation of divine love on her mind, in her young years,
she preferred the cause of truth,
and about the twenty-ninth year of her age received a call to the ministry, and,
being inwardly sensible that a dispensation of the gospel was committed to her,
she delayed not with vain consultations,
but readily submitted to that proving engagement, and,
cheerfully surrendering her will to divine requirings,
soon grew skilful in dividing the word; thereby evidently showing, to serious,
awakened minds, that in this, as in other religious services,
the Lord loveth a cheerful giver.

She was a diligent, exact attender of meetings,
and there was something instructive in that weighty
retired manner in which she usually sat in them,
often long in silence,
being careful to feel divine life precede and put forth to service,
and when raised in ministry, not to exceed the opening of the gift.
Thus her testimony was preserved clear and edifying, truly acceptable to Friends,
both at home and abroad where she travelled, being also serviceable in the discipline.

Having known many deep inward afflictions and close refinings,
she obtained the tongue of the learned, and often had a word to speak in due season.
Thus serving her generation,
she fulfilled the ministry she received to testify to the sufficiency of divine grace,
and finished her course with joy the 28th of the Eleventh month, 1768;
aged fifty-four years.

[.asterism]
'''

THOMAS DANN, a member of Dorking monthly meeting, in the county of Surry,
was born at Nutfield, in the said county, of honest and religious parents.
In his young years he was much addicted to vanity,
yet by the tender visitations of kind Providence, he was preserved from gross evils.
As he grew to man`'s estate, through the same gracious visitations,
the beauty and comeliness of this world was stained in his view,
and he fitted for service, into which he was called about the thirtieth year of his age.

He was a preacher of righteousness, not only in word and doctrine,
but in life and conversation; a diligent attender of meetings for worship and discipline,
earnestly recommending friends to an humble waiting on the Lord,
for counsel and direction in the management of the affairs of the church;
and though not concerned to travel much abroad,
yet he visited some adjacent counties to good satisfaction.
A just reprover of the libertine, but very tender to the sincere-hearted,
ready to give advice and counsel to those who stood in need, much concerned for peace,
and often instrumental in composing differences amongst his friends and neighbours;
a sympathizer with the afflicted, liberal and compassionate to the poor,
a loving husband and tender father,
yet not indulging his children in anything he believed inconsistent with the truth;
a good master, and a sincere friend.

It pleased the Lord, some time before his departure,
to give him a sense that his day was near at an end, his work was almost done,
and that all was well with him.
He often expressed in his illness that he found nothing stand in his way;
in the forepart of which his pain was very great,
but he was fervently engaged to beseech the Lord to grant him patience,
that he might endure it with becoming resignation, which was mercifully afforded him;
for which, and the many repeated favours received,
he had to praise and magnify God`'s holy name, and to declare with Jacob of old,
that the Lord had been with him all his life long.
In this comfortable assurance he quietly departed this life,
the 23rd of the Second month, and his corpse, accompanied by many Friends and neighbours,
was decently interred at Rygate, the 1st of the Third month, 1769; aged sixty-five,
and a minister thirty-five years.

[.asterism]
'''

JOHN BURTON, a member of Sedbergh monthly meeting, in Yorkshire, was born at Dent,
within the compass of that meeting,
and was favoured with the visitation of divine love in his young years,
whereby he came to see the emptiness of all mere outward profession and performances,
and that no worship would find acceptance with his
Creator but that performed in spirit and truth.
Under the influences thereof he was brought into communion with our Society,
and by taking heed to the inward anointing, and abiding faithful thereto,
agreeable to 1 John 2:27, he arrived to a good degree of Christian experience,
and to see the necessity of regeneration, the refining hand working powerfully in him,
in order to fit him for further service,
to which he was called in the early part of his time,
and became truly devoted to the great Master`'s use,
to be led and conducted according to his requirings.

Though he had but little human learning, he was often led forth in a living,
powerful testimony, in matter exceedingly copious and pertinent,
being enabled to divide the word aright,
and to speak feelingly to the states of the people.
He was endued with a large gift in the ministry,
and often dipped into great sufferings with the seed
of life that lay oppressed in the hearts of many.
But when he who was his life appeared, he was as a holy flame,
warming and comforting the hearts of the afflicted,
and as a sharp sword to the lukewarm and careless,
tender and affectionate to those who were young in the ministry,
greatly rejoicing when the word of life arose in them,
though declared but in a few expressions, treating them with much love and respect,
lest they should sink under discouragement.

In the course of his Christian progress he had to visit Ireland,
and divers of the northern counties, and London several times:
he also visited the American colonies;
in all which he conducted much to the satisfaction of Friends.
Though of a free, cheerful disposition and behaviour, yet he was properly guarded,
being a plain man,
bearing a faithful testimony against the pride and vain show of the present age.
He was a man that was truly engaged for the good order of the church,
and that the line of discipline might be kept to,
waiting in those meetings in an humble manner for divine direction,
whereby he was qualified in much love to speak with authority and judgment,
being clear-sighted in difficult matters.

In the latter part of his time he was much confined at home, through bodily infirmities;
when visited by friends, he received them in much love,
his mind still retaining strong and hearty desires that the church of Christ might flourish,
and appear in her ancient beauty, and Zion keep her garments unspotted of the world.
In the beginning of his illness, he, in a very moving, pathetic manner, bewailed,
to some friends who visited him,
the loss the church sustained by many pursuing the
riches and grandeur of this perishing world,
instead of durable riches and righteousness.

About two days before he died,
he expressed himself to some intimate friends who visited him,
that he had passed through many deep and humbling
baptisms in the course of his own experience,
and on the account of the backsliding of many under our name, and some of his own family.
But now they seemed to him to be all over, being filled with light,
divine consolation and peace on every hand, which was enough for all;
and that it would be the happy experience of all such who served the Lord in sincerity,
and had Zion`'s welfare at heart.
But that a fearful and terrible day would overtake the careless,
if there was not a turning to the Lord while the offers of mercy were extended.

He likewise said that when he believed it his duty
to leave his family and the near connections of life,
he had never omitted one journey on truth`'s account, in which he had then great peace.
Thus this servant of the Lord departed in faith and
full assurance of a resting-place with the righteous,
the 23rd of the Third month, 1769, in the eighty-seventh year of his age,
having been a minister about sixty years;
and was interred in Friends`' burial-ground in Dent,
a large and solemn meeting being held on the occasion.

[.asterism]
'''

WILLIAM RECKITT, of Wainfleet, in Lincolnshire, having, through a variety of exercises,
and many trying seasons, given evident marks of stability of mind,
and through a firm confidence in that hand which led him forth into service,
filled up his duty; for the encouragement of others,
that they also may follow the footsteps of those that are gone,
although under the most trying seasons,
the following account of him claims a place in these memoirs.

He was born in the year 1706, and educated among Friends; and,
about the thirty-sixth year of his age, came forth in the work of the ministry,
in much simplicity and innocency, to the satisfaction of Friends,
it being in the life of truth, the only authority of all true ministry.
He laboured faithfully in divers parts of England and Ireland; and about the year 1756,
a concern came on him to visit America; and, with his friends`' unity and concurrence,
he embarked for Philadelphia, but was, soon after they sailed,
taken by a privateer and carried into Morlaix.

Through the favour of a French merchant there, who voluntarily became his security,
he was sent to Carhaix, in Brittany,
where he resided five months before his liberty was obtained;
during which he was preserved in meekness and innocence.
By accounts from thence,
his lamb-like nature gained much on some of the French inhabitants,
and led them to treat him with much respect,
and he had several opportunities with them to his satisfaction,
particularly with the chief magistrate of the town.
In a letter to a Friend he gives this account of it:

[.embedded-content-document.letter]
--

He asked me many questions concerning our principles`' which I answered short,
but so full that he made no objections; and I was thankful in my mind it was so,
for it was somewhat difficult for the young man my interpreter,
though he is always ready to assist me when I have occasion.

When I got home to my solitary dwelling,
and considered how often the Lord had appeared on my behalf, and had been my advocate,
I was much bowed in thankfulness before him.
I much desire I may be remembered by you, (meaning Friends,) for good,
when it is well with you, for I am afraid I should not hold out to the end,
or that I should bring some dishonour to truth.
O how grievous a thing I have thought it would be if I should
now bring up an evil report of the good land,
and so thereby discourage poor souls that have set their faces thitherward!
I had rather, if it was consistent with the will of my heavenly Father,
be gathered home in a good time.

My fears have all been concerning myself, for surely I never saw more of my own weakness.
It hath been indeed a searching time to me; and yet it springs in my heart to say,
if the Lord hath any delight in me, he will bring me safely through all.
He knows the integrity of my heart.
I did not set out in a forward spirit, but in his counsel, and in it at this time I stand.
He knows best what will be most for his own honour.
And as to what will become of this earthen tabernacle,
it seems to be the least of my care, so that I may finish my course with joy.

--

After his return from France he returned home, but the concern remaining,
in about four weeks he came back to London, and again embarked,
and arrived safely at Philadelphia in the year 1757.
After visiting most of the provinces in North America,
to the comfort and edification of Friends, he embarked for Barbados,
but was again taken and carried into Martinico, and after about two weeks`' confinement,
through the favour of the commissary,
he embarked on board a cartel ship for the island called St. Kitt`'s,
where he had several meetings, and also at Nevis, where he had two meetings;
at one of which a priest stood up, and addressing the people,
told them the everlasting gospel had been preached among them that day;
and recommended it to the observation and practice of all present;
and our friend declared he never felt the power of truth rise so high as at those meetings.
After which, finding his mind clear, although invited to stay and have more meetings,
and was told many of the inhabitants were descendants from friends,
he returned to St. Kitt`'s, so called, and soon after embarked for Philadelphia,
and from thence for London.
In about three years after, he again visited America, and divers parts of this nation.

In private life he was an affectionate husband, a tender father, and kind friend,
adorning the gospel with a becoming conversation.
Thus persevering in a course of virtue, about a year before his decease,
he wrote again to the friend before mentioned in the following manner,
which shows the integrity of his heart continued:

[.embedded-content-document.letter]
--

The sap of life lies very deep in the root,
and that must be waited for in those sorrowful and pinching times I have met with.
Yet I have had a comfortable hope raised in me of late that all would be well in the end,
the prospect of which to me hath seemed exceedingly pleasant;
and if safe I should much desire it might be hastened;
but that is not my proper business,
to look for or desire the reward before the day`'s work is finished.
I have served a good master,
but have ever looked on myself one of the weakest of his servants;
yet have endeavoured to come up in faithful obedience to his will made manifest in me,
and in this now I have great peace,
and an assurance of an inheritance that will never fade away,
if I continue in the way of well-doing to the end of the race.

--

After this he visited the city of London,
which he often hinted he thought might be the last time:
but his love and integrity to the cause of truth continued,
and it was evident the fervency of his mind was as strong as ever.
His illness was very short: he was taken with a fit of the ague at night,
and next morning about four departed this life, the 6th of the Fourth month, 1769,
and was interred in Friends`' burial-ground the 9th of the same;
aged about sixty-three years.

[.asterism]
'''

JOSHUA TOFT, an ancient friend of Leek, in Staffordshire,
was favoured in the early part of his life with the knowledge of the blessed truth,
and by obedience thereto became when young in years an example of religion and virtue.
His concerns in business at that time requiring his being much from home,
and to be conversant with those unacquainted with the circumspect conduct
and manner of behaviour of the people he had joined in communion,
he was exposed in the youthful part of his life to severe and ill treatment.
But his mind being clothed with the patience of the holy word,
he experienced by its blessed fruits of meekness and love,
the ignorance of foolish men not only silenced, but sometimes their wrath and enmity,
through his faithful testimony, turned into respect and friendship.

Though his beginning in the world was small, yet being blessed by Providence,
whose is the earth and the fullness thereof, as well as the dew of heaven,
he was satisfied with a moderate competency,
and in the full strength of life and flow of business,
which would have enabled him to accumulate much wealth, with noble fortitude,
believing it to be required of him, he declined trade,
more fully to devote himself to his great Lord and master`'s service in the gospel ministry,
into which he had been called about the thirty-second year of his age,
in which he diligently and faithfully laboured many
years in various parts of this nation and Ireland,
to the comfort and edification of the church, and his own peace.

Nearly twenty years before his decease, he was disabled from travelling much from home,
being seized with a disorder in his head, which affected at times his understanding,
and deprived him, for more than fourteen years of the latter part of his life, of sight.
After the loss of which, his faculties became as strong as before,
and his understanding perfect which continued to the last.
With exemplary patience, cheerfulness and resignation, he bore great affliction of body,
as well as deprivation of sight,
signifying all that was laid upon him was in love and intended for his good,
and hoped he should receive it as such.

A day or two before his departure, he said he had been much consoled,
having received a most gracious promise, "`I have been with thee, I am with thee,
and will be with thee.`"
He quietly departed this life the 15th of the Eighth month, 1769, aged upwards of eighty,
a minister forty-eight years, and was interred in Friends`' burial-ground at Leek,
on which occasion the same ever-glorious truth that had been with
him in the beginning and close of his pilgrimage through life,
was manifested to the renewed encouragement of many, to prove for themselves likewise,
that the gifts and callings of God are without repentance.

[.asterism]
'''

RICHARD REYNOLDS, late of Winterburn, in Gloucestershire, was born at Banbury,
in the county of Oxford, and in his very early years manifested a religious disposition,
and knew in some degree the purifying hand of divine goodness to fit him for service,
so that, about the twentieth year of his age, he appeared in the ministry,
to the satisfaction of Friends.
He resided for many years in the city of Bristol, where his business,
before he retreated from it to Winterburn, lay;
which he was induced to do from a desire of withdrawing
from the encumbering pursuit of temporal things,
often expressing the hurt sustained by an over solicitude for things of this life.

A considerable time before his decease he was taken with a sudden indisposition of body,
as he was travelling on the account of temporal concerns,
and his mind became alarmed with this instruction,
"`Set thy house in order;`" to which he diligently attended,
in a spiritual sense especially.
In the course of his illness he appeared much resigned to divine disposal,
and uttered many instructive sayings to those who were with him,
very intelligibly and with clear understanding,
expressing that "`the Father`'s love is the best cordial.
This is a trying time.
We had need to lay up a good foundation against the time to come;`"
adding that the peaceful state of his mind was all owing to divine goodness; "`for to us,
O Lord, belongeth shame and confusion of face.`"
He was under deep travail of spirit that he might
be thoroughly purified and made meet for the kingdom,
and was enabled to pray that the Lord would lift up the light of his countenance,
and through Christ forgive all his omissions,
which there is good reason to believe was granted.
With much sensibility he mentioned the saying of the leper to Christ,
"`Lord! if thou wilt, thou canst make me clean;`" and the gracious answer, "`I will;
be thou clean.`"

That which lay with the greatest weight and dissatisfaction on his mind,
was his having been too closely attached to worldly things.
And a little before his departure, he said in an affecting manner,
"`Too much assiduity! too much care!
I might have been a better example.
So much care and pains alienate the mind: the Lord is merciful;
I hope he will forgive me that sin.
I would have you take warning by me.`"
This last saying he repeated with much concern,
and then laying in a composed manner for a few hours, quietly expired at Bath,
the 8th of the Twelfth month, 1769,
and was buried in Friends`' burial-ground near the Friars, in Bristol,
the 15th aged about sixty years, and a minister about forty years.

[.asterism]
'''

JAMES WILSON, of Kendal, was born in the parish of Kirby-Lonsdale, in Westmoreland,
in the year 1677.
His parents, Edmund and Jane Wilson, educated him in the way of the church of England.
When young in years, his heart was much bent to seek after real religion,
being uneasy with the dead formalities in which he was educated,
his soul thirsting after the enjoyment of the Lord`'s presence.
In this time of seeking after good,
he devoted much of his leisure time to reading the Holy Scriptures,
especially the New Testament; in the perusal whereof his mind was more informed,
tendered, and broken, than by all the instrumental labour he had partaken of.
Some time after, being convinced of the principles of truth, he joined our Society;
and in the thirtieth year of his age came forth in the work of the ministry,
and was soon drawn into, and eminently qualified for,
much extensive labour in the church, and amongst the people in Great Britain and Ireland.

He devoted much of the prime and strength of his life to the service of truth,
diligently labouring in the ability it gives, both at home and abroad,
to the honour of the great name, and the edification of many;
frequently attending meetings on public occasions, and divers appointed in fresh places,
wherein his labours were well received,
and he was made instrumental to the convincement of many.
He was very serviceable and successful in accommodating differences amongst his neighbours;
and having frequent access to persons of high rank in life,
he was thereby very useful not only to remove prejudices from their minds,
by opening the doctrines and principles most surely believed among us,
but in obtaining their friendly regard and assistance when occasion required.
Thus he spent a long and useful life,
through many close trials and afflictions which attended him both within and without.
He bore all with steadiness and resignation,
and his memory and understanding were preserved to the admiration of many who knew him.

Some lines he wrote about sixteen years before his decease,
seem to describe the state of his mind in succeeding years, viz.:

[quote]
____
I am now waiting,
and beseeching God Almighty to grant me the continuance
of his blessed grace and holy spirit,
to aid and assist me for a full preparation for death, and calmly to resign myself to it;
and above all, to grant me his aid in that painful and trying season,
that I may forever praise his holy name, who is forever worthy with his dear Son,
who is my dear and blessed Saviour.
Amen.
____

He departed this life at his house in Kendal, the 30th of the Twelfth month, 1769,
and was interred in Friends`' burial-ground the 1st of the First month, 1770;
aged ninety-two and a minister upwards of sixty years.

[.asterism]
'''

DANIEL STANTON, of the city of Philadelphia, was born there about the year 1708.
His father dying before his birth, and his mother a few years after,
he suffered great trial and hardships when very young;
but being early concerned to seek the knowledge of God,
he had a fervent desire to attend religious meetings,
though subjected to many difficulties and discouragements
before that privilege was allowed him.
Yet being earnest in his desires to obtain divine favour,
he was eminently supported under great conflicts and probations,
and continuing faithful to the degrees of light and grace communicated,
a dispensation of the gospel ministry was committed to him
some time before the term of his apprenticeship was expired;
and abiding under the sanctifying power of truth, he grew in his gift,
and became a zealous and faithful minister.

Though he was very exemplary in his industry and diligence,
in labouring faithfully at his trade to provide for his own support,
and after he married and had children, for their maintenance,
and was often concerned to advise others to the same necessary care;
yet he continued fervent in spirit for the promotion of truth and righteousness,
so that he was soon engaged to leave home, and the nearest connections of nature,
to publish the glad tidings of the gospel,
frequently visiting the meetings of Friends in the
province of Pennsylvania and the adjacent provinces,
and several times as far as the eastern parts of New England.

In the year 1748, in company with Samuel Nottingham,
he visited the few meetings in the Island of Barbados,
and by the way of Antigua to Tortola, where after staying some time,
they embarked for Europe.
Their voyage thither was attended with some singular hazards and danger,
which occasioned their landing in Ireland, where,
after he had visited the meetings of Friends, he embarked for England,
and visited the meetings generally in Great Britain,
to the comfort and satisfaction of Friends; his meek,
circumspect conduct and conversation, and lively, edifying ministry,
rendering his visits very acceptable, and his memory precious.

After his return to his native country he visited Friends
in all the southern provinces as far as South Carolina,
and about two years before his death,
the families of Friends in some parts of West Jersey, the city of New York,
and Long Island.
He returned from this service with great peace and satisfaction,
expressing his apprehension that he was now clear of all places,
and that his stay here was nearly over,
having an evidence that he had been faithfully concerned
from his youth to fear and serve God.

When at home he was much employed in visiting the sick and afflicted,
to whom he administered his spiritual advice and experience,
and was often engaged in humble prayer for their support;
and in the distributing to the necessitous according to his circumstances,
he manifested his benevolent disposition.
His love to the rising generation was very great,
which he manifested by his affectionate notice of them,
and especially of those who were religiously inclined,
his house being open to receive such.
His concern was great, that those who had the glad tidings of the gospel to publish,
might be true examples to the flock,
and adorn the doctrine they had to deliver by a circumspect life and conversation.

On the 5th day of the Fifth month, 1770, he was violently seized with the bilious colic,
and continued in great pain for several days, but being somewhat easier,
he attended two meetings on First-day,
in which he was much favoured in his public ministry, and expressed,
that he thought his time would not be long.
He was enabled to attend the monthly meeting at Philadelphia the 25th of the said month,
which was the last public meeting he was at,
being the next morning seized with a renewed attack of the same disorder,
which increased on him for several days;
yet through all he was mercifully supported in much resignation and patience,
rather inclining, if it was the Lord`'s will, to be released.

During the time of his sickness,
he often expressed his concern lest his friends should be too anxious for his recovery,
saying, if he should live longer,
and through any human frailty or infirmity occasion any reproach,
it would be the cause of sorrow to them.
The evening of the First-day before he died, several friends coming to see him,
he spoke a considerable time to them,
having before been desirous of such an opportunity of the company of his friends,
to sit down and wait on God, which was his great delight.
The evening before he died, he expressed to his friend Israel Pemberton,
who sat up with him, his great thankfulness, that his head was preserved from pain,
and his understanding clear;
and that though it had been a time of close trial and deep probation,
he could say he felt the evidence of divine support to attend him.
He died the 28th of the Sixth month, 1770,
in the sixty-second year of his age and forty-third of his ministry,
and the next day his body,
attended by a large number of people of divers religious denominations,
after a meeting being held for that purpose was interred
in Friends`' burial-ground in that city.

[.asterism]
'''

ELIZABETH ATKINSON, of Milden-Hall, in Suffolk,
was the daughter of Edward and Elizabeth Peachy, of the same place,
Friends well esteemed, who gave this their daughter a religious education.
While very young, she was favoured with a divine visitation,
and yielding obedience to the heavenly vision,
she became qualified for her master`'s use,
and received a gift in the ministry about the twenty-second year of her age.
She was faithfully concerned to yield obedience to the manifestations of duty,
in which she experienced peace.

When about thirty, she joined in marriage with Samuel Atkinson,
a Friend of the same meeting, and some few years after,
it pleased the Lord to try her in a close manner,
by dissolving this very near and close connection.
Thus being left a widow with six young children and in low circumstances:
this dispensation of heaven was attended with baptisms and exercises on many accounts,
her situation being such that she found it necessary to
use unwearied diligence for the support of her family,
not willing to be burdensome, but having a few things, was therewith content.
It does not seem that her family,
whose necessity she ever appeared to have due regard to,
hindered her in her gospel-labours;
but she was obedient to the requirings and manifestations of duty,
faithfully given up to go on the Lord`'s errands.

At the awful approach of the undeniable messenger of death,
she possessed a quiet composure of soul, often wishing to be dissolved,
to be with Christ;
yet humbly waiting the Lord`'s time for the accomplishment of his will.
Being full of days and full of peace,
she was greatly favoured to very near the end of her time, sensible and lively,
and was frequently engaged to express that the Lord`'s
goodness to her had been great and wonderful;
earnestly recommending to those who visited her to serve him faithfully,
and in an especial manner to the youth,
to dedicate the bud and blossom of their days to him,
for that they could not serve a better master.

A short time before her death, finding her mind very low,
she was fearful she had offended.
Earnest were her cries unto the Lord, that she might not depart under a cloud,
which he graciously answered by the renewing of his love,
and lifting up of his glorious countenance,
so that she broke forth in the following words, "`Glory,
honour and high renown be given to him, who wears the heavenly crown.
The Lord is my reward, and at his right hand are rivers of pleasure,
and that forevermore.`"
She departed this life the 3rd of the Seventh month, 1770,
and was buried in Friends`' burial-ground at Milden-Hall, the 8th of the same;
aged eighty-eight, and a minister sixty-six years.

[.asterism]
'''

THOMAS MAWDITT, of Collumpton, in the county of Devon,
was educated in the way of the church of England,
and about the twentieth year of his age was convinced of the blessed truth.
By the accounts received of him,
he appeared in the ministry about the thirty-third year of his age,
and his services therein were acceptable.
He was a diligent attender of meetings, though of an infirm constitution of body;
of an exemplary conduct among men, and of an innocent deportment.

Having left behind him a narrative in manuscript of his convincement,
the following is a copy of it, viz.:

[.embedded-content-document.testimony]
--

Some passages of my life having of late been brought fresh into my remembrance,
I thought proper to commit them to writing, that others might see the great love of God,
in Christ, to my soul, and be encouraged to follow on to know and obey him.
While I was young and tender in years,
the Lord was pleased to put his fear into my heart,
which was to me the beginning of wisdom,
because it made me careful both of my words and actions.

So long as I kept upon my watch against sin,
the Lord gave me true peace and quietude of mind, but when I was unwatchful,
the tempter often prevailed with his temptations,
which brought the righteous judgments of God upon my soul,
and made me cry unto him for mercy and forgiveness.
The Lord was gracious to me, and forgave me time after time, as I repented of the evil,
so that I can from my own experience say,
that there is mercy with the Lord that he may be feared;
and thus he gave me strength to call upon him while he was near,
and to seek him while he was to be found.

He was near in Spirit, reproving me for my sins, although I then knew him not;
and in this state I often made covenant, that if the Lord would forgive me,
then I would live more watchfully than I had hitherto.
But as it was made in my own will, it was soon broken,
and I was still under the administration of condemnation;
the sense thereof often made me cry unto God,
that he would deliver me from the body of this death.
In this state, when I would do good, evil was present with me,
and I did the things I would not; and finding myself overcome time after time,
notwithstanding my endeavours to the contrary,
I was ready to conclude that there was no living without sin in the world,
although I found it a burden too heavy to bear.

About this time I began to think what people to join with,
for I was not satisfied in the way I was in,
and I besought the most high God that he would direct me what people to join with.
While I was under this concern of mind, on a First-day of the week,
as I was walking to the place of worship in company with two of the people called Quakers,
one of them asked me to go with them to their meeting, adding,
that there were to be two strangers there that day.
I accordingly went, and after we had sat some time in silence,
one of them stood up and spoke, and after that the other.

I do not remember much of what they said,
but it appeared to me that their preaching was like that of the apostles,
and that they were enabled by a measure of the same
spirit and a degree of the same power.
I also felt such a measure of that spirit and power which
helped them in their ministry as I never enjoyed before;
and it was to me a day of glad tidings of great joy, and my soul did magnify the Lord,
and my spirit rejoiced in God my Saviour.
This gave me full satisfaction of mind what people to join with,
although at first it looked strange to me to see a people sit in silence as they did,
for I had been feeding upon words, until I was directed unto Christ,
the word nigh in the heart, and to know him to be my teacher.
Thus the Lord brought me off from a man-made ministry,
to the minister of the sanctuary and true tabernacle, which God had pitched and not man,
everlasting praise be given to his name.

Here the Lord brought me into a state of silence,
out of my formal prayers and will-worship, to wait upon him,
until he was pleased to help me to pray with the spirit and with understanding.
But when he was pleased to show me that I must use the singular number,
as thou and thee to one person, it was as death to me,
for I saw I should be despised and rejected.
Here I found in degree that cross which the apostle spoke of,
that crucified to the world, and the world to him;
and until I knew my own will in measure slain, I was not able to use it.

But when I did use it, after I believed it was required of me, I had great peace of mind;
and if at any time I did not use it for fear of offending man,
I was under condemnation and trouble of mind until I used it without respect of persons.
I know it was the Lord`'s doing, for I did it not in imitation but by revelation.
Neither could I any more pull off my hat and bow to any man.
Thus the Lord led me step by step into obedience to him;
and as long as I lived in obedience to what he was pleased to manifest unto me,
I reaped that peace and joy in the Holy Ghost,
that all the favour and friendship of men is not to be compared with.

About this time a concern came upon my mind to bear
a public testimony in meetings to the truth,
which made me both to fear and tremble; whereupon I let in the reasoner,
and looked to my own weakness as a man,
and how unfit I was for so great a work as the work of the ministry;
when I should have looked unto the Lord,
who is able to strengthen the weak and confirm the feeble-minded,
and which I had in times past witnessed to my comfort.
Here it was I lost my peace and quiet which I had in a state of obedience,
for I went from the true witness within, even the spirit of truth, which did lead,
and would have led me into all truth, and I joined with the reasoner,
and so erred and went astray from the way of the Lord as a lost sheep.

Here the enemy of mankind got advantage upon me,
and I could not stand faithfully in my testimony for the truth as I formerly had,
but grew weaker and weaker, and was tossed with a tempest and not comforted.
Yet in this sorrowful state I sometimes had a little hope that the Lord would deliver me,
which was some stay to my mind, and I was made to cry,
"`Lord! if thou slay me, yet will I trust in thee.`"
I would often pray unto God, that he would restore me again,
and that if it pleased him to bring the like concern upon me any more,
I would be faithful and obedient to his requirings.

But this I could not attain to, which brought me very low in my mind,
and I was almost ready to despair,
for I found myself so hardened that I could not lament my state and condition as formerly,
so that I was afraid the day of my visitation was over.
When all hope seemed to be lost, the word of God was unto me,
As thou hast gradually fallen, so thou shalt gradually rise;
which had so good an effect as to bring with it a living hope,
that was an anchor to my soul, steadfast and sure,
and preserved my mind from being carried away with the floods of temptation,
which were many and great in those days.

It was through faith in Christ, the word nigh in the heart,
which I found to be quick and powerful,
that I came to be restored again in due time to a state of obedience;
and the Lord now favoured me with many good meetings,
which made me often desire for the meeting-time, for in my silent waiting upon him,
I found my strength renewed.
After this it was shown me that I must alter the place of my sitting; and one day,
as the meeting-time drew on,
I prayed to God in my heart that he would favour me with a good meeting.
But the answer was, "`If thou dost not go and sit in that place,
how canst thou expect a good meeting?`"
Until now I was not come to a resolution; but now, when the meeting-time came,
I went and sat in the place showed me, not knowing further what might be required of me;
and, after some time of silence,
I found a concern of mind to speak to the people s followeth:
"`There is a seed of God amongst you, but it lieth oppressed,`" etc.

And now I can say, after many years`' experience, Hitherto the Lord has helped me,
and he is not a hard master, as some slothful servants have said,
for he doth not gather where he hath not strewn, neither reap where he hath not sown.
All who are born of that seed which is incorruptible,
and of the word of God which liveth and abideth forever,
can say there is no condemnation to them that are in Christ Jesus,
who walk not after the flesh, but after the spirit;
for the law of the spirit of life hath made them free from the law of sin and death.
Here, in brief, have I shown what the Lord hath done for my soul,
for it is he that hath plucked my feet out of the miry clay,
and set them upon a rock that was higher than I; wherefore to him shall the honour,
glory, and praise be given, who is over all worthy forever and evermore.

[.signed-section-signature]
Thomas Mawditt

[.signed-section-context-close]
1748.

--

In his last illness his understanding and senses were preserved,
and he expressed his being refreshed in his spirit;
and as he found his end approaching he frequently desired,
if agreeable to the will of the Almighty, that he might be released,
under a well-grounded apprehension that his day`'s work was done.
He departed this life the 13th of the Seventh month, 1770; aged eighty-one,
and had been a minister about forty-eight years.

[.the-end]
End of the Second Volume
