[short="On Faith"]
== Chapter 2. On Faith

There are two sorts or degrees of Faith:-- the first is,
that by which the mind gives its assent to the truth
of a thing on the testimony of another;
the second is of more exalted nature, being of Divine origin,
and is a gift of the Holy Spirit.
By the first, we believe in the existence of God,
and in the truths which He has revealed to us in the Holy Scriptures.
It is an essential principle in the beginning of the spiritual path;
for "`he that cometh to God, must believe that He is God,
and that He is a rewarder of them that diligently seek Him.`"^
footnote:[Heb. 11:6]
And if we put our whole trust in Him, and endeavour in all things to obey Him,
we shall be in a state of preparation for the reception
of that true and living Faith which is "`the gift of God.`"^
footnote:[Eph. 2:8.]

It is only by this Faith that we shall be enabled to overcome all our spiritual enemies,
and clearly to understand those mysteries which are incomprehensible to human reason;
for reason being born of man, is weak and uncertain, and easily errs; but faith,
being born of God, cannot err; reason, therefore, must follow and submit to faith,
not go before and control it.

It is by Faith that, "`being justified, we have peace with God,
through our Lord Jesus Christ.`"^
footnote:[Rom. 5:1.]
And when this precious gift has been granted to us, it produces in us Hope,^
footnote:[Rom. 5:2.]
Love,^
footnote:[1 Pet. 1:8.]
Confidence,^
footnote:[Eph. 3:12.]
Joy,^
footnote:[Rom. 5:2.]
and Holiness^
footnote:[Acts 15:9.]
of heart.
We shall then be enabled to feel an entire dependence on the goodness, power, justice,
and mercy of God, and a confidence in His promises;
as well as more fully to experience and comprehend
the operations of His Spirit on the mind.

Faith is an essential requisite for the proper performance of all our duties to God:
indeed, without it we cannot possibly please Him;^
footnote:[Heb. 11:6.]
neither should we ever be induced to seek Him,
or believe in the influence of His Holy Spirit upon our Souls.
It is by Faith that we are supported in our path to Peace,
and are enabled to persevere through the difficulties and besetments,
which we may have to encounter on our way:
it is through this holy principle that we suffer the pains of dryness,
and want of consolation, without fainting; being thereby strengthened to "`endure,
as seeing Him who is invisible.`"^
footnote:[Heb. 11:27.]
And it is only by Faith that we can attain to the practice of true, inward,
and spiritual prayer.
