== Chapter 3. On Prayer

Prayer is an intercourse of the soul with God.`"^
footnote:[God is a Spirit; so is the mind.
Bodies can have intercourse; so can souls.
When minds are in an assimilating state of purity, they have union with their Maker.
This was the bliss of Paradise: sin interrupted, and holiness must restore it.
To a soul thus distressed, the Creator communicates Himself,
in a manner which is as insensible to the natural eye, as the falling of dew;
but not less refreshing in its secrets powers, than the dew is to vegetation.
--Anonymous Essay on Devotion.]
It is not a work of the head, but of the heart; which ought always to continue.
It is the medium through which life and food are conveyed to the soul,
and the channel through which the gifts and graces of the Holy Spirit flow and are communicated.
Every secret aspiration of the soul to God is prayer:
all are therefore capable of prayer, and are called thereto, as all are called to,
and are capable of Salvation.

St. Paul hath enjoined us to "`pray without ceasing;`"^
footnote:[1 Thess. 5:17.]
and our Lord saith: "`I say unto all, watch and pray.`"^
footnote:[Mark 13:33,37, and 14:38.]
Come, then, all ye that are athirst, to these living waters;^
footnote:[Rev. 22:17]
nor lose your precious moments in "`hewing out cisterns that will hold no water.`"^
footnote:[Jer. 2:13.]
Come, ye famishing souls who find nought whereon to feed; come,
and ye shall be fully satisfied.
Come, ye poor afflicted ones, who groan beneath your load of wretchedness and pain,
and ye shall find ease and comfort.
Come, ye sick, to your Physician, and be not fearful of approaching Him,
because you are filled with diseases; expose them to His view, and they shall be healed.

Children, draw near to your Father, and he will embrace you in the arms of Love.
Come, ye poor, stray, wandering sheep, return to your Shepherd.
Come, ye who have been seeking happiness in worldly pleasures and pursuits;
but have failed to find in them that satisfaction ye expected: come,
and learn how to be truly happy here, and eternally happy hereafter.
Come, sinners, to your Saviour.
Come, ye dull, ignorant, and illiterate;
ye who think yourselves the most incapable of prayer: ye are more peculiarly called,
and adapted thereto.
Let all, without exception, come; for Jesus Christ hath called all.

You must however learn a species of prayer which may be exercised at all times,
which doth not obstruct outward employments,
and which may be equally practised by all ranks and conditions of men;
by the poor as well as the rich, by the illiterate as well as the learned.
It cannot, therefore, be a prayer of the head, but of the heart.
It is a species of prayer which nothing can interrupt but irregular and disordered affections.
And though you may think yourselves ever so dull, and incapable of sublime attainments,
yet, by prayer, the possession and enjoyment of God is easily obtained;
for He is more desirous to give Himself to us than we can be to receive Him.

Prayer is the guide to perfection, and the sovereign good;
it delivers us from every vice, and obtains for us every virtue:
for the one great means to become perfect, is to walk in the presence of God.
He himself has said: Walk in my presence, and be thou perfect.^
footnote:[Gen. 17:1.]
It is only by prayer that we are brought into, and maintained in, His presence;
and when once we have fully known Him, and the sweetness of His love,
we shall find it impossible to relish anything so much as Himself.
