== Chapter 4.

All Are Capable of Attaining to Inward, Spiritual Prayer.

If all were solicitous to pursue the spiritual path, shepherds,
while they watched their flocks, might have the Spirit of the primitive Christians,
and the husbandman at the plough, maintain a blessed intercourse with his God;
the manufacturer, while he exhausted his outward man with labour,
would be renewed in internal strength: every species of vice would shortly disappear,
and all mankind become true followers of the Good Shepherd.

Oh when once the heart is gained, how easily is all moral evil corrected!
It is, for this reason, that God, above all things, requires the heart.
It is the conquest of the heart alone,
that can extirpate those dreadful vices which are so predominant amongst men;
such as drunkenness, blasphemy, lewdness, envy, and theft.
Jesus Christ would become the universal and peaceful Sovereign,
and the hearts of all mankind would be wholly renewed.

The decay of internal piety,
is unquestionably the source of the various errors that have arisen in the world;
all of which would speedily be sapped and overthrown,
were inward religion to be established.
If, instead of engaging our wandering brethren in vain disputes,
we could but teach them simply to believe, and diligently to pray,
we should lead them sweetly unto God.

Oh how inexpressibly great is the loss sustained by mankind,
from the neglect of the interior!

Some excuse themselves by saying, that this is a dangerous way;
pleading the incapacity of simple persons to comprehend spiritual matters.
But the Oracles of Truth affirm the contrary.
Isaiah saith: "`The way-faring men, though fools, shall not err therein.`"^
footnote:[Isa. 35:8]
And where can be the danger of walking in the only true way, which is Jesus Christ?^
footnote:[John 14:6.]
of giving ourselves up to Him, fixing our eye continually on Him,
placing all our confidence in His grace,
and turning with all the strength of our soul to His pure Love?

The simple, so far from being incapable of this perfection, are by their docility,
innocency, and humility, peculiarly adapted and qualified for its attainment;
and as they are not accustomed to reasoning, they are less employed in speculations,
less tenacious of their own opinions.
Even from their want of learning,
they submit more freely to the teachings of the Divine Spirit; whereas others,
who are blinded by self-sufficiency, and enslaved by prejudice,
give great resistance to the operations of Grace.

We are told in Scripture, "`that unto the simple, God giveth understanding;`"^
footnote:[Ps. 119:130.]
and we are also assured, that God careth for them: "`The Lord preserveth the simple.`"^
footnote:[Ps. 116:6.]
Christ said to his Apostles; "`Suffer little children to come unto me,
for of such is the kingdom of Heaven.`"^
footnote:[Matt. 19:14.]

The simple are incapable of reasoning, teach them, therefore, the prayer of the heart,
not of the head; the prayer of God`'s Spirit, not of man`'s invention.

Alas! by wanting them to pray in elaborate forms, and to be curiously critical therein,
you create their chief obstacles.
The children have been led astray from the best of Fathers,
by your endeavouring to teach them too refined, too polished a language.

The simple and undisguised emotions of filial love are infinitely
more expressive than the most studied language.
The Spirit of God needs none of our arrangements and methods: when it pleaseth Him,
he turns Shepherds into Prophets; and,
so far from excluding any from the Temple of Prayer, He throws wide open the gates,
that all may enter in; while "`Wisdom crieth, Whoso is simple let him turn in hither;
as for him that wanteth understanding, she saith to him, Come, eat of my bread,
and drink of the wine which I have mingled.`"^
footnote:[Prov. 9:3-5.]

To teach man to seek God in his heart, to think of Him,
to return to Him whenever he finds he has wandered from Him,
and to do and suffer all things with a single eye to please Him,
is the natural and ready process; it is leading the soul to the very source of Grace,
wherein is to be found all that is necessary for sanctification.

O that all would at once put themselves into this way, which is Jesus Christ,
that His Kingdom might be established in their hearts!
For as it is the heart alone that can oppose His sovereignty,
it is by the subjection of the heart that His sovereignty is most highly exalted.
And since none can attain this blessed state,
save those whom God Himself leads and places therein;
we do not pretend to introduce any into it,
but only to point out the shortest and safest road that leads to it:
beseeching you not to be retarded in your progress by any external exercises;
not to rest in the shadow, instead of the substance.
If the water of eternal life was shown to some thirsty souls,
how inexpressibly cruel would it be, by confining them to a round of external forms,
to prevent their approaching it: so that their longing shall never be satisfied,
but they shall perish with thirst!

Oh ye blind and foolish men, who pride yourselves on science, wisdom, wit, and power!
How well do you verify what God hath said,
that His secrets are hidden from the wise and prudent,
and revealed unto The Little Ones--The Babes!`"^
footnote:[Matt. 11:25.]
