[short="On Spiritual Dryness"]
== Chapter 6. On Spiritual Dryness

No sooner will you have given yourself up to serve the Lord in this inward way,
than he will begin to purify you, and try your Faith;
in order to draw you nearer to Himself.
And, for this purpose, He will lead you through the paths of dryness and desertion;
so that, when you endeavour to fix your mind in silence, in order to feel after your God,
you will not experience the comfort and refreshment you expected; but, on the contrary,
you will be more than usually beset with a multitude
of troublesome and importunate imaginations;
insomuch, that you will begin to think that you labour to no purpose,
and that the prayer of internal silence is an attainment to which you need not aspire,
seeing that your imagination is so ungovernable, and your mind so void of good.
But this state of dryness is very profitable, if it be suffered with patience.^
footnote:[NOTE.
If you wish to receive real profit from the Holy Scriptures and other spiritual books,
you must peruse them with deep attention, and introversion of mind, observing,
whatever you have chosen, to read only a small part of it;
endeavouring to taste and digest it, to extract the essence and substance thereof;
and proceed no further, while any savour or relish remains in the passage.
When this subsides, take up your book again, and proceed as before,
seldom reading more than half a page at a time; for it is not the quantity that is read,
but the manner of reading, that yields us profit.
Those who read fast,
reap no more advantage than bee would do by only skimming over the surface of a flower,
instead of waiting to penetrate into it, and extract its sweets.
If this method were pursued, we should be more fully disposed for retirement and prayer.
--Guyon]

The Lord makes use of the veil of dryness,
to the end we may not know what he is working in us, and so may be humble; because,
if we felt, and knew, what he was working in our souls,
satisfaction and presumption would get in;
we should imagine we were doing some good thing, and reckon ourselves very near to God;
and this self-complacency would prevent our spiritual advancement.

And, though in the prayer of mental stillness,
you may feel yourself to be in a dry and comfortless state,
not being able to get rid of your troublesome thoughts, nor experience any light,
consolation, or spiritual feeling, yet be not afflicted,
nor desist from your undertaking; resign yourself at that time with vigour,
and patiently persevere as in His presence; for, while you persevere in that manner,
your soul will be internally improved.

Do you believe, that when you come from prayer in the same manner as you begun it,
without feeling yourself profited thereby, that you have been toiling in vain.
That is a fallacy; because true prayer consists, not in enjoying the light,
and having knowledge of spiritual things, but in enduring with patience,
and persevering in faith and silence; believing that you are in the Lord`'s presence,
turning to Him your heart with tranquillity and simplicity of mind.

We must be aware that nature is always an enemy to the spirit; and, that,
when she is deprived of sensible pleasures, she remains weak, melancholy,
and full of irksomeness.
Hence from the uneasiness of thoughts, the lassitude of body, importunate sleep,
and your inability to curb the senses, every one of which would follow its own pleasure;
you will often feel impatient to be at the end of your prayer.
Happy are you if you can persevere amidst this painful trial!
Remember, that "`They who wait upon the Lord shall renew their strength;
they shall mount up with wings as eagles; they shall run and not be weary,
they shall walk and not faint.`"^
footnote:[Isaiah 40:31.]

The prayer of internal silence may be well typified by that wrestling,
which the Holy Scriptures say, the patriarch Jacob had all night with God,
until the day broke, and He blessed him.
Wherefore, the soul is to persevere,
and wrestle with the difficulties that it will meet with in inward prayer,
without desisting, until the Sun of internal Light begin to appear,
and the Lord give it His blessing.

If you go to prayer with the spirit and intention of praying,
so long as you retract not that intention, although, through misery and frailty,
your thoughts may wander, you will, nevertheless, pray in spirit and in truth.
God, in his own due time, will help you to overcome all your difficulties; and,
when least you think, will give you holy purposes,
and more effectual desires of serving Him.
Distrust not Him, therefore, but only yourself; and remember that, as the apostle saith,
"`He is the Father of mercies, and God of all comforts.`"^
footnote:[2 Cor. 1:3.]
His comforts are sometimes withdrawn, but His mercy endureth forever.
He hath deprived you of what was sweet and sensible in His grace,
because you required to be humbled.

Be of good courage then,
and though it may seem to you that you toil without gaining much advantage,
yet you must recollect, we must plough and sow before we can reap;
and if you persevere in faith and patience,
you will reap an abundant reward for all your labours.
Would you be so unreasonable, as to expect to find without seeking;
or for it to be opened to you, without your taking the pains to knock?
As well might the husbandman expect to see his fields waving with grain,
without his having been at the trouble to put the seed into the ground.

It is no hard matter to adhere to God,
while you are in the enjoyment of his comforts and consolations;
but if you would prove your fidelity to Him,
you must be willing to follow Him through the paths of dryness and desertion.
The truth of a friend is not known, while he is receiving favours and benefits from us;
but if he remain faithful to us when we treat him with coldness and neglect,
it will be a proof of the sincerity of his attachment.

Though God hath no other desire, than to impart Himself to those that love and seek Him;
yet He frequently conceals Himself from us, that we may be roused from sloth,
and induced to seek Him with fidelity and love.
But, with what abundant goodness doth he recompense our faithfulness! and how sweetly are
these apparent withdrawings of Himself succeeded by the consolations of His Love!
David saith, "`I waited patiently for the Lord; and He inclined unto me, and heard my cry.
He brought me up also out of a horrible pit, out of the miry clay,
and set my feet upon a rock, and established my goings.
And he hath put a new song in my mouth; even praise unto our God.`"^
footnote:[Ps. 40:1-3.]

In seasons of the withdrawings of His Presence,
we are apt to believe that it will be a proof of our fidelity,
and evince the ardour of our love,
to seek Him by an exertion of our _own_ strength and activity;
and that this exertion will induce Him the more speedily to return.
But this is not the right procedure, when we are in this state: with patient resignation,
with self-abasement, with the reiterated breathings of an ardent, but peaceful affection,
and with reverential silence, we must wait the return of our beloved.
Thus, only, we shall demonstrate, that we seek nothing but Himself,
and his good pleasure; and not the selfish delights of our own sensations.

It is very common for us, when we feel the sweetness of the grace of God,
to fancy that we love Him;
but it is only in the withdrawings of His Presence that our love can be tried,
and the measure of it known.
It is at these seasons that we are convinced of the weakness and misery of our nature,
and how incapable we are, of ourselves, to think or do any good.
There are many who, when they experience meltings of heart, shedding of tears,
and other sensible delights, imagine that they are the favourites of God,
and that then they truly possess Him;
and so pass all their lives in seeking after those pleasurable sensations;
but they should be cautious lest they deceive themselves; for these consolations,
when they proceed from nature, and are occasioned by their own reflections,
or self-admirings, hinder them from discerning the true light,
or making one step towards perfection.
You should therefore be attentive to distinguish those meltings of the affections,
from the operations which purely proceed from God,
leaving yourselves to be led forward by Him;
who will be your light in the midst of darkness and dryness.

It is of no small advantage in prayer, patiently to suffer the want of consolation,
and the trouble and importunities of a wandering imagination:
it is an offering up of one`'s self in a whole burnt offering and sacrifice.
And as many times as you exercise yourself, calmly to reject your vain thoughts, and,
peacefully to endure your dark and desolate state,
so many crowns will the Lord set upon your head.

It is of great importance that you endeavour, at all times, to keep your heart in peace;
that you may keep pure that temple of God.
The way to keep it in peace, is, to enter into it by means of inward silence.

When you see yourself more sharply assaulted, retreat into that region of peace;
and you will find a fortress that will enable you to triumph over all your enemies,
visible and invisible, and over all their snares and temptations.
Within your own soul resides Divine Aid, and Sovereign Succour.
Retreat within it, and all will be quiet, secure, peaceable, and calm.
Thus, by means of mental silence, which can only be attained by Divine Help,
you may look for tranquillity in tumult; solitude in company; light in darkness;
forgetfulness in pressures; vigour in despondency; courage in fear;
resistance in temptation; peace in war; and quiet in tribulation.
