== Chapter 8.

On Temptations and Tribulations

We are by nature so base, proud, and ambitious; and so full of our own appetites,
our own judgment and opinions,
that if temptations and tribulations were not permitted to try, humble, and purify us,
we should never arrive at a state of acceptance with God.

The Lord, seeing our misery, and perverse inclinations,
and being thereby moved to compassion, withdraws his strength from us,
that we may feel our own weakness;
suffering us to be assaulted by violent and painful suggestions of impatience and pride,
and divers other temptations: and some, who have long been in the practice of sin,
by gluttony, luxury, rage, swearing, despair, and a great many other besetments;
in order that they may know themselves, and be humble.
With these temptations, Infinite Goodness humbles our pride; giving us, in them,
the most wholesome medicine.

"`All our righteousnesses,`" as Isaiah saith, "`are as filthy rags;`"^
footnote:[64:6.]
through the vanity, conceitedness, and self-love, with which they are defiled.
It is, therefore,
necessary that they should be purified with the fire of temptation and tribulation;
that so they may be clean, pure, perfect, and acceptable in the sight of God.

The Lord polishes the soul which he draws to himself, with the rough file of temptation;
freeing it thereby, from the rust of many evil passions and propensities.
By means of temptation and tribulation He humbles, subjects, and exercises it;
showing it its own weakness and misery.
It is thus that He purifies and strips the heart;
in order that all its operations may be pure, and of inestimable value.
Oh, how happy would you be, if you could quietly believe,
that all the trials and temptations wherewith you are assaulted,
are permitted for your gain and spiritual profit!

But you will perhaps say, that when you are molested by others,
or wronged and injured by your neighbour,
that this cannot be for your spiritual advantage seeing,
that it is the effect of their fault and malice.
This is no other than a cunning and hidden device of the enemy because,
though God wills not the sin of another, yet He wills His own effect in you;
and the trouble which accrues to you from another`'s fault should improve you,
by increasing your patience and exercising your forbearance and charity.

Consider, how the Lord makes use of the faults of others for the good of your soul.
Oh, the greatness of the divine wisdom! who can pry into the depths
of the secret and extraordinary means and the hidden ways,
whereby He guides the soul which he desires to purge, transform, and dignify.

It is often the greatest temptation to be without temptation;
because we are then most liable to fall into a state of lukewarmness; wherefore,
we ought not to repine when it assaults us; but with resignation, peace, and constancy,
shut our hearts against it.
If you would serve God, and arrive at the sublime region of internal peace,
you must pass through this rugged path of temptation and tribulation;
and therein become polished, purged, renewed, and purified.

A direct contest and struggle with temptations rather serves to augment them;
and withdraws the soul from that adherence to God,
which it should ever be its principal occupation to strive after and maintain.
The surest and safest method of conquest, is simply to turn away from the evil,
and draw yet nearer and closer to our God: a little child, on perceiving a monster,
does not wait to fight with it, and will scarcely turn its eyes towards it;
but quickly shrinks into the bosom of its mother, in total confidence of safety: so,
likewise, should the soul turn from the dangers of temptation to its God.
"`God is in the midst of her,`" saith the Psalmist, "`she shall not be moved;
God shall help her, and that right early.`"^
footnote:[Ps. 46:5.]
"`The name of the Lord is a strong Tower to which the righteous flee and are safe.`"^
footnote:[Prov. 18:10.]

If we do otherwise, and in our weakness attempt to attack our enemies,
we shall frequently feel ourselves wounded, if not totally defeated: but,
by casting ourselves into the presence of God, and relying solely on Him,
we shall find supplies of strength for our support.
This was the succour sought for by David: "`I have set,`" saith he,
"`the Lord always before me: because he is at my right hand, I shall not be moved.
Therefore, my heart is glad, and my glory rejoiceth: my flesh, also,
shall rest in hope.`"^
footnote:[Ps. 16:8-9.]
And, it is said in Exodus, "`The Lord shall fight for you,
and ye shall hold your peace.`"^
footnote:[14:14.]

Although "`God cannot be tempted with evil, neither tempteth He any man;`"^
footnote:[James 1:13.]
yet it is evident that temptations are permitted for our good, and, if rightly endured,
tend to our refinement "`therefore count it all joy,
when ye fall into divers temptations; knowing this,
that the trying of your faith worketh patience.`"^
footnote:[James 1:2.]
And in all our besetments, however painful they may feel to us,
or of whatever nature they may be, we should remember that it is said:
"`Blessed is the man that endureth temptation: for when he is tried,
he shall receive the crown of life,
which the Lord hath promised to them that love him.`"^
footnote:[James 1:12.]

You cannot be hurt by men or devils, if you keep always near to God; for,
"`who is he that will harm you, if ye be followers of that which is good.`"^
footnote:[1 Peter 3:13.]
But if you are hurt, it is your pride, your passions,
and your many unsubdued evil propensities, that rise up and injure you;
and as long as these remain, the enemy will make use of them,
and seek to draw your mind away from its adherence to God.

"`Every man is tempted, when he is drawn away of his own lust, and enticed.`"^
footnote:[James 1:14.]
Therefore know your own corrupt state,
and the need you have to be purified by means of temptation,
and keep always on the watch, lest the unwearied enemy gain access to your soul,
by his insinuations and pleasing allurements,
which he will suit to your present situation and condition: for,
in your passage through life,
there are many things which he will offer you as temptations;
endeavouring to produce in you an inordinate inclination and desire for them;
which if you give way to whilst you are in this manner tempted,
great will be the danger of your being wholly overcome.

If the malignant enemy is not resisted in his first attack,
he enters by gradual advances, and takes entire possession of the heart:
and so long as opposition is deferred by habitual negligence,
the power of opposing becomes every day less,
and the strength of the adversary proportionably greater.
Therefore, when you feel in yourself a strong and eager desire after anything whatsoever,
and find your inclination carry you too precipitately to do it,
strive to moderate yourself by retreating inwards,
and seeking after tranquillity of mind.
To do all things well, we must do them as in the presence of God,
otherwise we shall soon get off our right centre,
and be in danger of being wholly overthrown.

Oh, blessed soul! if you would but be content and quiet in the fire of temptation and tribulation,
and suffer yourself to be fully proved and tried,
in patiently enduring the assaults of the enemy and the desertion of heavenly good,
how soon would you find yourself rich in celestial treasures! how
soon would the Divine bounty make a rich throne in your soul,
and a goodly habitation for you to refresh and solace yourself in!
Know, that although the Lord may for a season visit,
yet he taketh up His abode in none but peaceful souls;
and those in whom the fire of temptation and tribulation
hath consumed all their corrupt propensities:
the Lord reposeth not Himself any where, but where quietness reigns,
and self-love is banished.

If, from chaos,
His Omnipotence has produced so many wonders in the creation of the world,
what will He not do in your soul, created after His own image and likeness,
if you keep constant, quiet, and resigned; with a true sense of your own nothingness?

"`Cast not, therefore, away your confidence, which hath great recompense of reward,`"^
footnote:[Heb. 10:35.]
but keep constant; O blessed soul! keep constant; for it will not be as you imagine:
nor are you at any time nearer to God, than in such times of desertion,
and trial of your faith; for, although the sun is hid in the clouds,
yet it changes not its place, nor loses any part of its brightness.
The Lord permits these painful temptations and desertions, to purge and polish you,
to cleanse and disrobe you of self; that you may become by these trials entirely His,
and give yourself up wholly to serve Him.

Oh how much is there to be purified in a soul,
that must arrive at the holy mountain of perfection, and of transformation, with God!
For, whilst any portion of evil, any thing of self, remains in us,
we must be subject to temptation.
When self is annihilated, there is then nothing left for the tempter to act upon.
Oh, how resigned, naked, denied, annihilated, ought the soul to be,
that would not hinder the entrance of the Divine Lord,
nor his continual communion with it!
