== Chapter 10.

On Mortification.

All endeavours merely to rectify the exterior,
impel the soul yet farther outward into that about
which it is so warmly and zealously engaged;
and thus its powers are diffused and scattered abroad;
for its application being immediately directed to externals,
it thus invigorates those very senses it is aiming to subdue.

This species of mortification can never subdue the passions, or lessen their activity.
The only method to effect this, is inward silence; by which the soul is turned,
wholly and altogether inward, to possess a Present God.
If it direct all its vigour and energy towards this centre of its being,
the simple act separates and withdraws it from the senses;
the exercising of all its powers internally, leaves the senses faint and impotent;
and the nearer it draws to God, the farther is it separated from the senses,
and the less are the passions influenced by them.

In the mortification of the eye and ear,
which continually supply the busy imagination with new subjects,
there is little danger of falling into excess: God will teach us this,
and we have only to follow where his Spirit guides.

The soul has a double advantage by proceeding thus: for,
in withdrawing from outward objects, it draws the nearer to God;
and the nearer its approaches are made to Him,
besides the secret sustaining power and virtue it receives,
it is farther removed from sin: so that, at length, to have the mind turned to God,
becomes, as it were, habitual.
