== Chapter 15.

Man Acts More Nobly Under the Divine Influence, than He Can Possibly Do by Following His Own Will.

Some persons, when they hear of the prayer of silence,
falsely imagine that the soul remains dead and inactive; but, unquestionably,
it acteth therein, more nobly and more extensively than it had ever done before;
for God Himself is its lover, and it now acteth by the agency of His Spirit.
When St. Paul speaks of our being led by the Spirit of God,
it is not meant that we should cease from action;
but that we should act through the internal agency of His grace.
This is finely represented by the prophet Ezekiel`'s vision of the wheels,
which had a Living Spirit; and whithersoever the Spirit was to go, they went,
they ascended, and descended as they were moved: for the Spirit of Life was in them,
and they turned not when they went.^
footnote:[Ezek. 1.]
Thus the soul should be equally subservient to the will
of that vivifying Spirit wherewith it is enlightened,
and scrupulously faithful to follow only as that moves.
Our activity should, therefore,
consist in endeavouring to acquire and maintain such a state,
as may be most susceptible of Divine impressions,
most flexile to all the operations of the Eternal Word.

Whilst a tablet is unsteady, the painter is unable to delineate a true copy:
so every act of our own selfish spirit, is productive of false and erroneous lineaments;
it interrupts the work, and defeats the design, of this adorable painter:
we must then remain in peace, and move only when he moves us.

Jesus Christ hath The Life in Himself, and He is the life of every living soul.^
footnote:[John 5:26.]

As all action is estimable only in proportion to the dignity of the efficient principle,
this action is incontestibly more noble than any other.
Actions produced by Divine principle, are Divine; but creaturely actions,
however good they may appear, are only human.
Jesus Christ, the Word, hath The Life in Himself; and being communicative of His nature,
He desireth, to communicate it to man.
We should, therefore, make room for the influx of this Life,
which can only be done by the ejection of the fallen nature;
and the suppression of the activity of Self.
This is agreeable to the assertion of St. Paul: "`If any man be in Christ,
he is a new creature: old things are passed away; behold all things are become new!`"^
footnote:[2 Cor. 5:17.]
But this state can be accomplished, only by dying to ourselves,
and to all our own activity, that the influence of God may be substituted in its stead.

Man may, indeed, open the window; but it is the Sun himself, that must give the Light.
Jesus Christ has exemplified this in the Gospel: Martha did what was right;
but because she did it in her own spirit, Christ rebuked her.
The spirit of man is restless and turbulent; for which reason it does little,
though it would appear to do much.
"`Martha,`" saith Christ, "`Thou art careful, and troubled about many things;
but one thing is needful;
and Mary hath chosen that good part which shall not be taken away from her.`"^
footnote:[Luke 10:41-42.]
And what was it that Mary had chosen?
Repose, tranquillity, and peace.
She apparently ceased to act, that the Spirit of Christ might act in her;
she ceased to live, that Christ might be her life.

St. Peter, in the warmth of his affection, told the Lord, that for His sake he was ready,
willingly to lay down his life; but, at the word of a young damsel, he denied Him.

The many troubles in life, come from the soul not abiding in its place,
and not being content with the will of God, and what is afforded therein,
from time to time.
Many souls may be resigned as to the general will, and yet fail as to the present moment:
being out of the will of God, they fall; they renew such falls,
as long as they continue out of the Divine will; when they return into it,
all will go on well.
God loves what is done in His own order, and of His own will and time;
and while you faithfully give yourself up thereto, you will do all things right.

All men have more or less of ardent desires, except those who live in the Divine will.
Some of these desires may appear to be good;
but unless they be according to the will of God, he who rests in the Divine will,
though he be exempt from all these desires, is infinitely more peaceful,
and glorifies God more.
This shows us how necessary it is to renounce ourselves, and all our own activity,
to follow Christ Jesus; and we cannot follow Him, without being animated with His Spirit.
Now that His Spirit may gain admission in us, it is necessary,
that our own spirit should be first subdued:
"`He that is joined unto the Lord,`" saith St. Paul, "`is one Spirit.`"^
footnote:[1 Cor. 6:17.]

All things should be done in their season: every state has its commencement,
its progress, and its consummation; and it is an unhappy error to stop in the beginning.
There is even no art but what has its process;
and at first we must labour with diligence and toil,
but at last we shall reap the harvest of our industry.
When the vessel is in port,
the mariners are obliged to exert all their strength that they may clear her thence,
and put to sea; but at length they turn her with facility, as they please.
In like manner, while the soul remains in sin and creaturely entanglements,
very frequent and strenuous endeavours, are requisite to effect its freedom;
the cords which hold it must be loosed; and then, by strong and vigorous efforts,
it pushes off gradually from its old port; and, in leaving that at a distance,
it proceeds to the haven to which it wishes to steer.

When the vessel is thus put in motion, in proportion as she advances on the sea,
she leaves the land behind; and the farther she departs from the old harbour,
the less difficulty and labour is requisite in moving her forward:
at length she begins to get sweetly under sail;
and now proceeds so swiftly in her course, that the oar, which is become useless,
is laid aside.
How is the pilot now employed?
He is content with spreading the sails, and holding the rudder.
To spread the sails, is to lay the mind open before God,
that it may be acted upon by His Spirit; to hold the rudder,
is to restrain the heart from wandering from the true course, recalling it gently,
and guiding it steadily to the dictates of the Blessed Spirit,
which gradually gains possession and dominion of it;
just as the wind by degrees fills the sails, and impels the vessel.

While the winds are fair, the mariners rest from their labours,
and the vessel glides rapidly along without their toil; and when they thus repose,
and leave the vessel to the wind, they make more way in one hour,
than they had done in a length of time by all their former efforts:
were they now even to attempt using the oar, they would not only fatigue themselves,
but retard the vessel by their ill-timed labours.

This is the manner of acting we should pursue interiorly; it will, indeed,
advance us in very short time, by the Divine influence,
infinitely farther than a whole life spent in reiterated acts of self-exertion;
and whosoever will take this path, will find it easier than any other.

If the wind be contrary and blow a storm, instead of putting out to sea,
we must cast anchor to hold the vessel.
Our anchor is a firm confidence and hope in God,
waiting patiently the calming of the tempest, and the return of a more favourable gale,
as David "`waited patiently for the Lord, and He inclined unto him, and heard his cry.`"^
footnote:[Ps. 40:1.]
We must, therefore, be resigned to the Spirit of God,
giving up ourselves wholly to His divine guidance;
never suffering ourselves to be disquieted by any accident;
for inquietude is the door by which the enemy gets into the soul, to rob it of its peace:
neither should we concern, or busy ourselves, with what others say and do,
for this will be a great cause of disturbance to us.

Let us pacify all the motions of our heart, as soon as we see it in agitation.
Let us quit all pleasure that comes not from God alone.
Let us do away all unprofitable thoughts and musings.
Let us diligently seek God within us, and we shall infallibly find Him, and with Him,
joy and peace; such joy and peace as will endure in the midst of suffering, and which,
flowing from an inexhaustible source, become perpetual fountain of delight.
"`Peace I leave with you,`" said Christ to His followers, "`my peace I give unto you,
not as the world giveth, give I unto you.`"^
footnote:[John 14:27.]

Did we but know the blessedness of hearkening unto God,
and how greatly the soul is strengthened and invigorated thereby,
all flesh would surely be silent before the Lord;^
footnote:[Zech. 2:13.]
all would be still, as soon as He appeareth.
But to engage us further in a boundless resignation, God assures us, by the same Prophet,
that we should fear nothing in thus giving up ourselves to Him,
because He takes care of us,
surpassing the highest tenderness of which we can form an idea:
"`Can a woman,`" saith He, "`forget her sucking child,
that she should not have compassion on the son of her womb?
Yea, she may forget; yet will I not forget thee.`"^
footnote:[Isaiah 49:15.]
Oh blessed assurance, full of consolation!
Who, after this,
shall be fearful of resigning themselves wholly to
the dispensation and guidance of their God!

All men seek for peace, but they seek where it is not to be found.
They seek it in the world, which is ever promising, but can never give us solid peace;
for, wherever we go, we shall carry this fruitful source of every perplexity,
our own unsubdued and selfish will.
The love of liberty is one of the most dangerous passions of the heart.
If we follow this propensity, instead of true liberty, it reduces us to slavery.
As our passions are the worst of our tyrants, if we obey them partially,
we must always be in a perpetual strife and contest within;
and if we entirely give ourselves up to them,
it is horrid to think to what extremities they will lead; they will torment the heart,
and, like a torrent, sweep all before them, and yet never be satisfied.
True liberty is to be found only in Him, whose truth shall set us free,^
footnote:[John 8:32.]
and who shall make us experience, that to serve Him is to reign.

That piety by which we are sanctified, and entirely devoted to God,
consists in doing His will precisely in all circumstances of life.
Take what steps, you please, do what deeds you will, let them shine with lustre,
yet you shall not be rewarded, but for having done the will of your Sovereign Master.
Although your servant did wonders in your house, yet if he did not what you required,
you would not value his service, and you might justly complain of him as a bad servant.

There is no good spirit but that of God: that spirit which removes us from the true good,
is but a spirit of illusion, however flattering it may appear.
Who would be carried in a magnificent chariot on the road to an abyss!
The way which leads to a precipice is frightful,
although it should be covered with roses;
but the way that leads to a crown is delightful,
although it should be thick set with thorns.
He has given His good Spirit to instruct us,^
footnote:[Neh. 9:20.]
therefore, let us no longer follow our own will but His;
so that not only our religious actions, but also all others,
may be done with no other view but that of pleasing Him:
then will our whole conduct be sanctified;
then will our deeds become continual sacrifice; and incessant prayer,
and uninterrupted love, will occupy the heart: therefore,
let us submit to the annihilation of our own will, that His will may reign in us!
For it is His prerogative to command, and our duty to obey.
