[#sixteen, short="Peace and Rest before God"]
== Chapter 16. On the Possession of Peace and Rest Before God

The soul that is faithful in the exercise of that
love and adherence to God already described,
is astonished to feel Him gradually taking possession of its whole being;
and now enjoys continual sense of that Presence,
which is become as it were natural to it.
The Presence of God diffuses an unusual serenity
throughout all our faculties--it calms the mind,
and gives sweet repose and quiet even in the midst of our daily labours;
but then we must be resigned to Him without reserve.

We must however urge it as matter of the highest importance,
to cease from self-action and self-exertion, that God Himself may act alone:
He saith by the mouth of His Prophet David, "`Be still, and know that am God.`"^
footnote:[Ps. 46:10.]
Yet those greatly err, who accuse this species of prayer of idleness,
a charge than can only arise from inexperience.
If they would but make some efforts towards the attainment of it,
they would soon experience the contrary of what they suppose,
and find their accusation groundless.

This appearance of inaction is, indeed, not the consequence of sterility and want,
but of fruitfulness and abundance;
this will be clearly perceived by the experienced soul, which will know and feel,
that its silence is full and unctuous,
and the result of causes totally the reverse of apathy and barrenness.
The interior is not a strong hold, to be taken by storm and violence;
but a kingdom of Peace, which is to be gained only by Love.
Let us then give ourselves up to God without apprehension of danger.
He will love us, and enable us to love Him; and that love, increasing daily,
will produce in us all other virtues.
He alone can replenish our hearts which the world has agitated and intoxicated,
but never could fill.

He will take nothing from us but what makes us unhappy.
He will only make us despise the world, which we do perhaps already.
We shall only be made to alter a little in our actions, and correct the motive of them,
by making all referrible to Him.
Then the most ordinary and seemingly indifferent actions will become exercises of virtue,
and sources of consolation.
We shall behold in peace the approach of death, as the beginning of life immortal,
and as St. Paul saith, "`we shall not be unclothed; but clothed upon,
and mortality shall be swallowed up of life.`"^
footnote:[2 Cor. 5:4.]

Let us therefore no longer fear to commit ourselves wholly to God.
What risk do we run, in depending solely on Him!
Ah! He will not deceive us, unless by bestowing an abundance beyond our highest hopes:
but those who expect all from themselves, will inevitably be deceived,
and must suffer this rebuke of God by His prophet Isaiah:
"`Behold all ye that kindle fire, that compass yourselves about with sparks;
walk in the light of your fire, and in the sparks that ye have kindled.
This shall ye have of mine hand, ye shall lie down in sorrow.`"^
footnote:[Isa. 50:11]

The soul advanced thus far, hath no need of any other preparative than its quietude;
for now the Presence of God, which is the great effect, or rather continuation of Prayer,
begins to be powerfully felt, and the soul experiences what the Apostle Paul saith,
that "`Eye hath not seen, nor ear heard, neither have entered into the heart of man,
the things which God hath prepared for them that love Him.`"^
footnote:[1 Cor. 2:9.]
The soul certainly enjoys transcendent blessedness,
and feels that it is no longer she that lives, but Christ that liveth in her;^
footnote:[Gal. 2:20]
and that the only way to find Him is to turn the mind inward.
We no sooner do this, than we are filled with the consolations of His Presence:
we are amazed at so great blessing, and enjoy an internal converse,
which external matters cannot interrupt.

The same may be said of this species of prayer, that is said of wisdom:
"`All good things come together with her.`"^
footnote:[Wisdom 7:11.]
For the virtues now flow from us into action with so much sweetness and facility,
that they appear natural and spontaneous.
